### ISSUE TITLE
Circular constraint dependency with generic

### ISSUE THREAD

**Issue by ChanyaKushima** [dotnet/roslyn#38092]
Because the following code is including circular constraint dependency, I want to call error, CS0454.
~~~
class A<T>
{
}

class B <U> where U : A<U>
{
}
~~~

U is circular constraint dependency.

**Comment by RikkiGibson** [comment]
Did you mean `U : A<U>`?

**Comment by ChanyaKushima** [comment]
Oops, we can write code such as:
~~~
class A<T> { }
class B : A<B> { }
~~~
Sorry, I have no issues.
