### ISSUE TITLE
Expose IsInExpressionTree

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#38100]
Useful in code fixes as the rules are slightly different in expressions.

Preferable via a static mehtod and not via some service locator. Don't know if `SemanticFacts` is a thing.

**Comment by sharwell** [comment]
This interface method:

https://github.com/dotnet/roslyn/blob/b0df544ac729ff09031d3cf38e2cbfb3d69436a5/src/Workspaces/Core/Portable/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs#L54

Exposes implementations for C#:

https://github.com/dotnet/roslyn/blob/b0df544ac729ff09031d3cf38e2cbfb3d69436a5/src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs#L702-L722

And Visual Basic:

https://github.com/dotnet/roslyn/blob/b0df544ac729ff09031d3cf38e2cbfb3d69436a5/src/Workspaces/VisualBasic/Portable/Extensions/SyntaxNodeExtensions.vb#L1001-L1023

**Comment by CyrusNajmabadi** [comment]
Needs to go through API review process.
