### ISSUE TITLE
VS2019 INT preview does not permit changing language versions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#38106]
**Version Used**:  VS2019 INT Preview (see below)

**Steps to Reproduce**:

1. Create New Project (.NET Framework 4.5)
2. Project > Properties > Build > Advanced

**Expected Behavior**:

`Language version` selector permits changing the language version

**Actual Behavior**:

`Language version` selector is greyed out and does not even show active language version.

![image](https://user-images.githubusercontent.com/3804346/63300332-d2d69900-c28c-11e9-9a25-2278283d8db4.png)

![image](https://user-images.githubusercontent.com/3804346/63300393-f1d52b00-c28c-11e9-8415-8c91fbd03e9b.png)

**Comment by sharwell** [comment]
@cartermp

**Comment by miloush** [comment]
Kind of duplicate of https://github.com/dotnet/roslyn/issues/37703 :)
