### ISSUE TITLE
Auto-completion should ignore numbers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38108]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/698734/auto-completion-should-ignore-numbers.html)._

---
Please do not give an auto-complete suggestion for numbers. Auto-completion is a very useful feature for names, as they tend to be part of a limited set of possibilities and they can be obscure and easy to mistype, but the same is not true for the set of possible numbers.

With the current behaviour, when the suggestion box appears I cannot navigate to another line without first hitting the Escape key (screenshot: http://prntscr.com/ouft68). If the number is one that is &quot;easily guessed&quot;, then it typically takes very little effort for me to type it myself. The auto-suggestion is rarely (if ever) correct, so having to dismiss it every time that I type a number is very distracting and awkward.

---
#### Visual Studio Feedback System on 8/18/2019, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't believe this is roslyn.  Maybe some other tool?
