### ISSUE TITLE
Should static local functions be able to access non-static local functions from parent scope?

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#38129]
**Version Used**: master from SharpLab (a08336fd917ddb3cb884f37f974830da24143c6d)

**Steps to Reproduce**:

Compile the following code:

```c#
class C
{
    static void M()
    {
        int i = 42;
        
        static void StaticLocal() { }
        int Local() => i;

        static void SL()
        {
            StaticLocal();
            Local();
        }
        
        SL();
    }
}
```

**Expected Behavior**:

Since `Local` gives access to local state, `SL` should not be able to call it.

**Actual Behavior**:

[The code compiles fine and `SL` captures state.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMACAwgWAFADe+GJGKAjAGxkAsGAsgBQCUxpRepXGAlgHYxeGALwYaaANxtuGadwrUUdAMowIMHgGMAMgHtNEADYsMBDAF85XfoL0HjzEQD5eUvFdILaGZdpYeSDhkZVXUtOyMWN2DuCIdo4MtOYICfP2YEkiTzIA===) I think that goes against the design of local functions. Or is this actually the intended behavior?

**Comment by RikkiGibson** [comment]
It seems like a bug to me. Looks like this causes 'SL' to be an instance member on the same display class as 'Local', in effect ignoring the 'static' modifier.

**Comment by gafter** [comment]
Fixing this could "break" some existing programs, so this is a compat issue and should be fixed sooner rather than later.

**Comment by svick** [comment]
@gafter I have just submitted https://github.com/dotnet/roslyn/pull/38177 that should fix this. Is there any chance this can make it into the initial non-preview release of C# 8.0?

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/38177.
