### ISSUE TITLE
DoesNotReturnIf incorrectly handled

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#38124]
**Version Used**: 

VS 16.3.0 Preview 2.0

**Steps to Reproduce**:

```cs
static void M1(string? s)
{
    Debug.Assert(s != null);
    Console.WriteLine(s.Length); // no warning
}

static void M2(string? s)
{
    Debug.Assert(false);
    Console.WriteLine(s.Length); // CS8602
}
```

**Expected Behavior**:

Both `M1` and `M2` have no warning.

**Actual Behavior**:

`M2` produces CS8602 warning.

**Comment by agocke** [comment]
What target framework?

**Comment by ufcpp** [comment]
netcoreapp3.0

The `Debug` class is in

Assembly System.Diagnostics.Debug, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview8-28405-07\ref\netcoreapp3.0\System.Diagnostics.Debug.dll

and its signature is

```cs
        [Conditional("DEBUG")]
        public static void Assert([DoesNotReturnIf(false)] bool condition)
        {
        }
```

**Comment by RikkiGibson** [comment]
Looks like the fix was merged, so will close this issue. Thanks for reporting it @ufcpp.
