### ISSUE TITLE
Nested classes somehow absorb their enclosing region

### ISSUE THREAD

**Issue by GingerLoaf** [dotnet/roslyn#38122]
**Version Used**
2.0.0.6140902

**Steps to Reproduce**:
Given this class
namespace Wave.InteractiveStreams.Filter.Logic
{
    public class RootClass
    {

        #region Fields

        private string stringField = null;
        private int intField = 0;

        #endregion

        #region Constructors

        public RootClass()
        {

        }

        #endregion

        #region Classes

        public class NestedClass
        {

            #region Nested Fields

            private string stringField = null;
            private int intField = 0;

            #endregion

            #region Nested Constructors

            public NestedClass()
            {

            }

            #endregion

        }

        #endregion

    }
}

and this Rosyln parser

private class RegionSyntaxWalker : CSharpSyntaxWalker
{

    private readonly Dictionary<string, List<string>> m_classToRegionsMap = new Dictionary<string, List<string>>();

    private readonly Stack<string> m_classNameStack = new Stack<string>();

    public RegionSyntaxWalker()
        : base(SyntaxWalkerDepth.StructuredTrivia)
    {
    }

    public IDictionary<string, IList<string>> WalkRegions(SyntaxNode node)
    {
        m_classToRegionsMap.Clear();
        DefaultVisit(node);

        var copy = new Dictionary<string, IList<string>>();
        foreach (var item in m_classToRegionsMap)
        {
            copy[item.Key] = item.Value;
        }

        m_classToRegionsMap.Clear();

        return copy;
    }

    public override void VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        m_classNameStack.Push(node.Identifier.ToFullString().Trim());
        base.VisitClassDeclaration(node);
        m_classNameStack.Pop();
    }

    public override void VisitRegionDirectiveTrivia(RegionDirectiveTriviaSyntax node)
    {
        if (!m_classToRegionsMap.TryGetValue(m_classNameStack.Peek(), out List<string> regions))
        {
            regions = new List<string>();
            m_classToRegionsMap[m_classNameStack.Peek()] = regions;
        }

        regions.Add(node.GetText().ToString().Trim());

        base.VisitRegionDirectiveTrivia(node);
    }

}

**Expected Behavior**:
I expect that if I call RegionSyntaxWalker.WalkRegions on the first file I posted that I would end up with this:
{
    "RootClass" :["#region Fields","#region Constructors","#region Classes"],
    "NestedClass":["#region Nested Fields", "#region Nested Constructors"]
}

**Actual Behavior**:
I get this: {
    "RootClass" :["#region Fields","#region Constructors"],
    "NestedClass":["#region Classes","#region Nested Fields", "#region Nested Constructors"]
}

"#region Classes" is defined as a member of RootClass, yet my code analyzer seems to want to parse NestedClass before parsing "#region Classes". It seems out of order to me. I am simply trying to get the list of regions per class (including nested ones) so that I can validate them!

**Comment by RikkiGibson** [comment]
`#region` directives are not members but they are structured trivia and get associated with nearby syntax nodes based on a set of rules.

One of the rules (I might not have this perfectly right, so forgive me) is: lines containing only trivia get associated with the following syntax token. This makes it so comments get associated with the code directly below them for example, which is usually the desired behavior.

The directive is included in the LeadingTrivia for 'public' keyword belonging to the NestedClass declaration, so they're being visited after the NestedClass node itself by-design.

I think if you manually visit the parts of a ClassDeclarationSyntax yourself in the order you want instead of calling base.VisitClassDeclaration you might be able to get the behavior you want.

**Comment by GingerLoaf** [comment]
I will give that a shot. I simply want a list of regions within each class... including nested ones!

**Comment by GingerLoaf** [comment]
That seemed to have done it! I just used each ClassDeclarationSyntax and manually searched for any child trivia

`public override void VisitClassDeclaration(ClassDeclarationSyntax node)
{
	var className = node.Identifier.ToFullString();
	if (!m_classToRegionsMap.TryGetValue(className, out List<Tuple<string, Location>> regions))
	{
		regions = new List<Tuple<string, Location>>();
		m_classToRegionsMap[className] = regions;
	}

	var childTriviaLists = node.ChildNodes().Select(n => n.GetLeadingTrivia()).ToArray();
	foreach (var childTriviaList in childTriviaLists)
	{
		foreach (var childTrivia in childTriviaList)
		{
			if (!childTrivia.IsKind(SyntaxKind.RegionDirectiveTrivia))
			{
				continue;
			}

			regions.Add(new Tuple<string, Location>(childTrivia.ToFullString().ToLower().Trim(), childTrivia.GetLocation()));
		}
	}

	base.VisitClassDeclaration(node);
}`

Thank you for helping me understand. Not a bug! working as expected
