### ISSUE TITLE
switch expression snippet cause switch statement snippet.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38142]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/699250/switch-expression-snippet-cause-switch-statement-s.html)._

---
<h1>Problem</h1>
<p>On C# 8.0, I tryed to insert switch expression. Then, Visual Studio said “Note: Tab twice to insert the ‘switch’ snippet”. So, I enterd tab twice, but the following ‘switch’ snippet was inserted.</p>
<p>Sample:</p>
<pre><code>int b = a switch (switch_on)
{
    <span class=hljs-keyword>default</span>:
}
</code></pre>
<p>This is switch “statement” snippet. but I want switch “expression” snippet because a variable (or literal) is at the beginning of the sentence.</p>
<h1>Solution</h1>
<p>So I think it resolve if we have a new snippet.<br>
It is best to be inserted with the above action, but if it is defficult, you should add a new snippet such as “swe”.<br>
I want the snippet to insert a following code.</p>
<pre><code>int b = a switch {
    
};
</code></pre>
<p>or</p>
<pre><code>int b = a switch {
    _ =&gt; <span class=hljs-keyword>throw</span> <span class=hljs-keyword>new</span> NotImplementedException();
};
</code></pre>

---
#### Visual Studio Feedback System on 8/20/2019, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippets.
