### ISSUE TITLE
Questionable nullability in ISymbolExtensions.RewriteInheritDoc

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#38145]
https://github.com/dotnet/roslyn/pull/37999/commits/249e314f4f880a0c4e3735ee18711309d4d78e29#diff-c7b19cdd45d6fd5f89518de58a798e1cR1021

A Contract.AssertNotNull has been added, but it's not clear this is always true.

**Comment by sharwell** [comment]
> but it's not clear this is always true.

A more correct statement is the following:

> but it's clear this is not always true

Example:

```csharp
class SomeType {
  /// <inheritdoc/>
  void SomeMethod() {
  }
}
```

**Comment by agocke** [comment]
Sounds good, I'll let you choose how to annotate this

**Comment by agocke** [comment]
See https://github.com/dotnet/roslyn/pull/37999

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
