### ISSUE TITLE
Symbols/Namespaces not being resolved

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38157]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/700665/symbolsnamespaces-not-being-resolved.html)._

---
<p>I’m working through a heap of old code, refactoring it, changing it a little. But It’s very difficult to find where the problems are because Visual Studio keeps forgetting that it has already valided files. And is refusing to go through and validate them. For example, out of the 138 errors, I can see some that say …</p>
<p>The type or namespace name ‘EntityComponentSystem’ could not be found (…)</p>
<p>So i go through and open those files. Visual studio updates and acknowledges that there’s nothing wrong with those files. The types are found. This is the case for probably 99% of the errors listed in the error list. They aren’t errors at all. So I have to individually go through and open every file just so VS can parse the file and see that there’s nothing wrong.  This isn’t a great experience.<br><br>Just changed a few more things. Hit build, now instead of 100 errors I have 332 errors, clicking through them from the top I see that there are one or two files that do actually have errors but mostly these files having nothing wrong with them. Making it very hard to narrow in on the actual issues.</p>

---
#### Visual Studio Feedback System on 8/20/2019, 01:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/20/2019, 03:20 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Gavin Williams solved on 8/20/2019, 01:16 AM, 0 votes: 

<p>Clean Solution from the Build menu helped a lot.</p>

**Comment by gafter** [comment]
This is a problem for projects that did not build previously.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
