### ISSUE TITLE
Regex highlight in Regex.IsMatch

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#38167]
**Version Used**: 

Microsoft Visual Studio Community 2019
Version 16.2.0
C# Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/3105979/63408600-aa71aa80-c404-11e9-959f-435460e08403.png)

**Expected Behavior**: regex highlighted in IsMatch

**Actual Behavior**:  regex is not highlighted in IsMatch

**Comment by CyrusNajmabadi** [comment]
Works for me.  Is 'str' defined?

![image](https://user-images.githubusercontent.com/4564579/63409951-0279c400-c3a7-11e9-8d44-ee18fb911590.png)

**Comment by alrz** [comment]
I don't see it now, there was something up with the project itself.
