### ISSUE TITLE
"Add null check" adds unreachable null check

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/roslyn#38178]
**Version Used**: 
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

**Steps to Reproduce**:
```csharp
public static class MonadicNullable
{
    public static U? Apply<T, U>(this T? nullable, Func<T, U> applicator)
        where T : struct
        where U : struct
    {
        if (nullable is null)
            return null;
        else
            return applicator(nullable.Value);
    }
}
```
**Expected Behavior**:
```csharp
public static U? Apply<T, U>(this T? nullable, Func<T, U> applicator)
    where T : struct
    where U : struct
{
    if (applicator is null)
        throw new ArgumentNullException(nameof(applicator));

    if (nullable is null)
        return null;
    else
        return applicator(nullable.Value);    
}
```
**Actual Behavior**:
```csharp
public static U? Apply<T, U>(this T? nullable, Func<T, U> applicator)
    where T : struct
    where U : struct
{
    if (nullable is null)
        return null;
    else
        return applicator(nullable.Value);
    if (applicator is null) //CS1062 : Unreachable code detected
        throw new ArgumentNullException(nameof(applicator));
}
```
The added null check has 2 issues
1. It is placed on a dead branch of code 
2. It is paced after the argument has already been dereferenced.

See also #38093

**Comment by CyrusNajmabadi** [comment]
Current logic is pretty simple, it just places the null check for a specific parameter after any existing null checks for the parameter that precedes it.  I'm not sure how useful it is to try to detect and special case what's going on here.

**Comment by AlgorithmsAreCool** [comment]
The dead branch issue is just bad luck. But maybe if it could make sure the bill check precedes the first dereference of the parameter?

**Comment by CyrusNajmabadi** [comment]
> The dead branch issue is just bad luck. But maybe if it could make sure the null check precedes the first dereference of the parameter?

That seems reasonable :)

**Comment by AlgorithmsAreCool** [comment]
For reference, this still occurs. The null check is placed after the else block and is unreachable. 

That being said, NRT has made this a non-issue for me in day to day code.

**Comment by CyrusNajmabadi** [comment]
> For reference, this still occurs.

Yeah, we def have not invested in making any changes here at all.  We'd possibly take a reasonably scoped community PR.  But the pattern is so niche as to not warrant getting off our backlog :)

**Comment by AlgorithmsAreCool** [comment]
Not complaining at all, I'd forgotten about it because nullable annotations make it a non-issue. Yall can close it if you want.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Thanks!
