### ISSUE TITLE
Cast to a non-nullable value type should update variable state to non-null

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#38170]
**Version Used**: 

Branch master (13 Aug 2019)
Latest commit a08336 by David:
Merge pull request #37916 from dibarbet/partial_load_str

Update partial load dialog string to better match task center.

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
class C
{
  void M(II? i)
  {
    S s = (S) i; // CS8605: Unboxing a possibly null value.
    i.ToString(); // CS8602: Dereference of a possibly null reference.
  }
}

interface II {}
struct S : II {}
```

**Expected Behavior**:
`CS8602` is not reported for `i.ToString()`. If the variable contains a null value an exception will be thrown from the cast.

**Actual Behavior**:
Roslyn repots `CS8602: Dereference of a possibly null reference.` for the dereference of `i` in the code above.

**Comment by sharwell** [comment]
The behavior you observed is the behavior I would expect. You can use `i!` to treat the parameter as non-null.

**Comment by sharwell** [comment]
In my previous comment, I missed that `S` was a value type.
