### ISSUE TITLE
Nullable analysis doesn't propagate explicit null-check correctly

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38190]
Nullable analysis doesn't propagate that explicit null check of `a?.b != null` implies `a != null`. It works correctly if explicit null check is replaced with pattern matching.

**Version Used**: 
Current release/16.4-preview-1, master a08336, latest Int Preview

**Steps to Reproduce**:

```csharp
public class A
{
    public A a;
}
public class B : A { }

#nullable enable
public class Program
{
    public void foo(A a)
    {
        if (a is B b)
        {
            var bb = b?.a as B;
            if (bb != null)
            {
                _ = b.a.ToString();     // potentially nullable-dereference warning (wrong)
            }
        }
    }

    public void foo2(A a)
    {
        if (a is B b)
        {
            if (b?.a is B bb)
            {
                _ = b.a.ToString();     // no warning (correct)
            }
        }
    }
}
```

Or see [warnings here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAzAAmwCZ8BBAWACgBvK/ewg0/CAbioF8q9CSAhfCDL5q+LpSoBiAHYBXADbyIweXHxxpy1dwLFCARgDsVWpQaNCAFnwAzAPZ2AFMwgBKOg1PnzANwgJ8YCD8AF4WADoIAH5Ilih8PnYzb3oASxt8RyDgfABCMLlFd2SUrxTvAH1QiIhwgBU7AGUYBFTpAHNHV1ZvAHpe/AAHO3hpGFSIRQBPfEKlFTgAWhREOBtV6QBjNQB3f2k29sydhDsO4vKxD3pxa4tsa3s7ImcWC88783TM2ujY1PiAmy71Kn3KVTCv3qTRahy6PXM/VmdnwewQBw6mU2dgQCDgmxgIO84nM4g4QA===)

**Expected Behavior**:
- No warnings in both cases.

**Actual Behavior**:
- Warning in first case.

**Comment by RikkiGibson** [comment]
I think this is innate to how our flow analysis works unfortunately. We may split the state after visiting `b?.a as B`, but we just unsplit afterwards and whatever information we found is no longer available once we visit `bb != null`.

**Comment by petrroll** [comment]
IDE suggests `Use pattern matching` (i.e. transformation from 1st to 2nd) so it's not that big of an issue.
