### ISSUE TITLE
XAML code behind file (.g.i.cs) not auto-updated when editing the xaml file in IDE

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#38192]
**Version Used**: latest 16.3 dogfood build

**Steps to Reproduce**:

1. Create a C# WPF application (.netcore or .netframework)
2. Add a new `TextBlock` control from Toolbox
3. Add a new `IsVisibleChanged` event handler to the text block:
![image](https://user-images.githubusercontent.com/10605811/63474139-d6088b00-c42c-11e9-8edb-0f727a6079af.png)
4. This should auto-generate `TextBlock_IsVisibleChanged` handler in xaml.cs file and hook it up to the control
5. Open the .xaml.cs file nested under the xaml file and invoke Find All References on `TextBlock_IsVisibleChanged`

**Expected Behavior**:
`TextBlock_IsVisibleChanged` reference in code behind file (MainWindow.g.i.cs) is found and the method is not flagged as unused private member (IDE0051)

**Actual Behavior**:
Find All References shows no references and the unused members analyzers also flags the added event handler as unused
![image](https://user-images.githubusercontent.com/10605811/63474226-35669b00-c42d-11e9-82f2-5e080012d673.png)

6. Build the project and invoke Find All References on `TextBlock_IsVisibleChanged`. This time you see the Expected Behavior and the reference to the method in code behind file is found and the IDE0051 is also not generated.
![image](https://user-images.githubusercontent.com/10605811/63474588-8aef7780-c42e-11e9-85d1-f2e0bf32806c.png)

7. If you again edit the xaml file and add a new handler or manually change the name of any existing handler, the incorrect behavior in step 5 again repros until you build the project again to regenerate the up-to-date code behind xaml file.

**Comment by onovotny** [comment]
Just want to make sure that Xamarin Forms and UWP/Windows UI XAML is considered for this as well.

**Comment by debonte** [comment]
This is a VS issue. I filed VS bug [970889](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/970889)

**Comment by mavasani** [comment]
Thanks @debonte. I'll close this issue then.

**Comment by debonte** [comment]
We (VS XAML team) have decided not to fix this until we receive more complaints from customers, because:
1. This regression was introduced in VS 15.0 (March 2017) and this is the first time it has been reported.
2. This issue only affects event handlers whose event args objects are not derived from System.EventArgs -- IDE0051 isn't shown for more typical event handlers.
3. The fix is complex and therefore could introduce instability for little benefit.

**Comment by mavasani** [comment]
One potential workaround that can be applied for IDE0051: Replicate https://github.com/dotnet/roslyn-analyzers/pull/3155 that was done for [CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801?view=vs-2019) so we bail out on this case. Tagging @Evangelink

**Comment by Evangelink** [comment]
Happy to help if you want to go this way.

**Comment by mavasani** [comment]
@Evangelink I think that sounds like a reasonable compromise, given we have seen few reports for this issue on analyzers repo for CA1801.
