### ISSUE TITLE
CS7038 Failed to emit module (IAsyncEnumerable returns IAsyncEnumerable)

### ISSUE THREAD

**Issue by joshlang** [dotnet/roslyn#38201]
EDIT:  This was my original bug.  Then I noticed when I compiled it, it actually dies with `error CS7038: Failed to emit module` ... so I changed the title (seems more important)

.net core 3.0 preview 8.

```
async IAsyncEnumerable<string> GetStrings([EnumeratorCancellation] CancellationToken cancellationToken = default)
{
    yield return await Task.FromResult("");
    yield return await Task.FromResult("");
}

async IAsyncEnumerable<string> GetStrings2([EnumeratorCancellation] CancellationToken cancellationToken = default) 
    => GetStrings(cancellationToken);

IAsyncEnumerable<string> GetStrings3([EnumeratorCancellation] CancellationToken cancellationToken = default) 
    => GetStrings(cancellationToken);
```

GetStrings() has some customizable logic (imagine)… And GetStrings2 or GetStrings3 just want to call it with specific parameters for the consumer's convenience.

GetStrings2 warns `CS1998` (async method but no awaits)

GetStrings3 warns `CS8424` (the enumerator cancellation attribute has no effect because it's not async)

It seems to me that at least *one* of these should work!

**Comment by jcouv** [comment]
Fix is in 16.4p2 (`GetStrings2` now produces an error)

**Comment by joshlang** [comment]
Perfect.  Thanks for being so speedy.  I implemented the GetStrings3 solution you referred to earlier, and it worked just fine.

I had been confused about how to chain those calls with [EnumeratorCancellation].  But after thinking through the purpose of it (.WithCancellation), I understand the logic.

**Comment by Logerfo** [comment]
Being forced to write the `await foreach` every time really sucks, specially if you're passing the data through several nested stuff. Is this really the only way to achieve this? Am I missing something?

**Comment by joshlang** [comment]
Yes, you're missing jvouc's advice :)

```
async IAsyncEnumerable<string> GetStrings([EnumeratorCancellation] CancellationToken cancellationToken = default)
{
   ...
}

// Then nesting:

IAsyncEnumerable<string> NestedThing(CancellationToken cancellationToken = default) 
    => GetStrings(cancellationToken);
```

Tested it, works great.

**Comment by Logerfo** [comment]
Oh, I get it now, there is no `async` modifier. But it seems to me that `NestedThing` will not be a blocking call, but "call and forget", since `IAsyncEnumerable` is not awaitable. Is that correct?

**Comment by joshlang** [comment]
No, it's like a Task returning a Task without "async".  You can still await it.

For IAsyncEnumerable, you're still ultimately creating an IAsyncEnumerable, and you consume it just like normal.  Generally `await foreach (var x in asyncEnumerableThing) { … }`

**Comment by Logerfo** [comment]
Hmm, I see. Does the following also work as expected: `NestedThing().WithCancellation(token)`? Since there is no attribute...

**Comment by joshlang** [comment]
You can test it yourself - just try it out.  It's all good.  You can still do `.WithCancellation`.  You get all the goodness of the original declaration.

**Comment by Logerfo** [comment]
Alright, thanks!
