### ISSUE TITLE
Nested for loop increment variable defaults to i

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38210]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/704799/nested-for-loop-increment-variable-defaults-to-i.html)._

---
Not sure if this is a problem or a feature request, but I'm reporting it as a problem...

Whenever I write a nested for loop in Visual Studio, the increment counter defaults to i. However, this conflicts with the outer for loop which also uses i. I have used Eclipse in the past and it always put the inner loop counter as j (and k, etc.). Visual Studio always seems to use i which conflicts with the counter variable in any outer loops.

It would be nice if this was fixed.

---
#### Visual Studio Feedback System on 8/22/2019, 04:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment]
For loop is generated using code snippet.

**Comment by CyrusNajmabadi** [comment]
@akhera99 Do we have a new snippet for `for` loops?

**Comment by akhera99** [comment]
> [@akhera99](https://github.com/akhera99) Do we have a new snippet for `for` loops?

We do and it checks to see availability of the incrementor. This can be closed since we're not investing in legacy snippets.
