### ISSUE TITLE
WorkFlow errors not shown during build results

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#3821]
Open a Workflow Service Application and create a variable with invalid Default values like below 
![image](https://cloud.githubusercontent.com/assets/10550513/8489748/0461977c-20d4-11e5-826e-751545e932c4.png)

You can see the blue warning signs next to the default values.

If we build the solution at this state, we see no errors or warnings.

![image](https://cloud.githubusercontent.com/assets/10550513/8489787/5323b82c-20d4-11e5-990e-0c6ce9983cff.png)

**Comment by CyrusNajmabadi** [comment]
Workflow services are legacy now.  Haven't heard about this from anyone.  Closing out.
