### ISSUE TITLE
cannot use local variable -continued-

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/520579/cannot-use-local-variable-continued.html)._

---
File &quot;Entity.cs&quot; contains several type definitions including 'Map' and 'Content'. Some errors still existed, but I took a break from &quot;Entity.cs&quot; to create a new file &quot;EventArgs.cs&quot; and created several types within. When I switched back to &quot;Entity.cs&quot;, which I never closed, visual studio reported more errors than existed.

I restarted Visual Studio to attempt to clear this problem. When I reloaded the solution, there were zero errors reported in the file &quot;Entity.cs&quot; even though there are errors (see attachment for one example).

Suggestion: create a quick-fix button that allows the user to completely rebuild the &quot;reported&quot; errors buffer, since restarting Visual Studio didn't fix the issue.

I included a zip of the solution, which did not let me include 4 files:
.vs\TheradenCore\v15\Server\sqlite3\db.lock
.vs\TheradenCore\v15\Server\sqlite3\storage.ide
.vs\TheradenCore\v15\Server\sqlite3\storage.ide-shm
.vs\TheradenCore\v15\Server\sqlite3\storage.ide-wal

---
#### furrychemistry on 4/5/2019, 07:06 PM: 

I closed the file's tab and reopend it, which reloaded the errors.<br>This used to occur when Visual Studio loads the document tab when loading the solution.
#### furrychemistry on 4/5/2019, 07:09 PM: 

-- When I reopened the tab, Visual Studio showed the errors correctly --
#### Visual Studio Feedback System on 4/8/2019, 02:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
