### ISSUE TITLE
String Display Incorrectly in VS2017

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38219]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/489766/string-display-incorrectly-in-vs2017.html)._

---
I am moving from VS 2013 to VS 2017. One issue I am now running into is strings are not working as I would expect in the new version. 

For example: If I define the following in both versions...

Dim s3 As String = &quot;This is one more test &quot;&quot;with double quotes&quot;&quot; &quot; &amp; vbCrLf &amp; &quot;Now on another line.&quot;

When viewing the variable in Locals window/Immediate window/or calling other functions the variable is returning:
VS2013 (as expected):  		
&quot;This is one more test &quot;with double quotes&quot;   Now on another line.&quot;

VS2017 (incorrect):
&quot;This is one more test &quot;&quot;with double quotes&quot;&quot; &quot; &amp; vbCrLf &amp; &quot;Now on another line.&quot;

---
#### Visual Studio Feedback System on 3/14/2019, 11:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by gafter** [comment]
It is possible that this is intentional.

**Comment by gafter** [comment]
Also repros on Visual Studio 2019

**Comment by vatsalyaagrawal** [comment]
New behavior is by design. Do we have a way to bypass the new behavior.

**Comment by gafter** [comment]
@vatsalyaagrawal I'm not sure what behavior you are requesting instead of this.

**Comment by ivanbasov** [comment]
The request seems to be incorrect. The behavior is by design. 
1. If we `Console.Write("This is one more test ""with double quotes"" " & vbCrLf & "Now on another line.")`, we see
```
This is one more test "with double quotes" 
Now on another line.
```

2. However, when we display a value stored in a variable in the Watch Window or in Interactive Window, we add quotes around it like `"a"`, if just a single character stored in the value. Therefore, displaying double-quotes and `vbCrLf` seems to be consistent.
