### ISSUE TITLE
IDE1005

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38244]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/516075/ide1005.html)._

---
I need to disable this message. I have 1.6M lines of code in 22 projects with over 15 years of development. This has become a great hindrance, I don't need my hand held, I need to control my own development environment. A way to turn off this warning is all I require. Thank you.

---
#### Visual Studio Feedback System on 4/3/2019, 10:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/22/2019, 10:59 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
You can disable/suppress IDE1005 (InvokeDelegateWithConditionalAccessId) by setting the Preference for "Prefer conditional delegate call" to "No" from Tools Options dialog:

![image](https://user-images.githubusercontent.com/10605811/63609704-7e813100-c58c-11e9-978e-1016a9c29cff.png)

**Comment by CyrusNajmabadi** [comment]
hey @Michael Flum.

Could you provide a little more data here?  I would be interested to know what about this particular feature you didn't like.  It seems like it's a pure win in terms of just reducing the amount of cruft that has to be written around a very common pattern.  Thanks!
