### ISSUE TITLE
Dictionary<,> and HashSet<> instances should be created with an explicit IEqualityComparer<> for Symbols

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#38248]
#37247 changed `Symbol` equality to ignore nullability by default.

As a result, instances of `Dictionary<,>` and `HashSet<>` should be created with an explicit `IEqualityComparer<>` when the key type argument may be `Symbol`. That includes cases where the key type argument is a interface implemented by `Symbol` such as `Cci.IReference`.

**Comment by chsienki** [comment]
I believe all the required cases have been covered, so closing this. 

There outstanding work at https://github.com/dotnet/roslyn-analyzers/issues/2493 that covers creating an analyzer to prevent new cases, but we do have some level of symbol equality correctness in the analyzers already that should catch most instances.
