### ISSUE TITLE
Feature Request: Add a DnxWorkspace

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3824]
It's probably premature to start work on this until the Dnx stuff has been finalized, but I'd like to get the conversation started.

Right now it's really difficult to create workspaces containing Dnx projects. I originally attempted to create one by looking at the Omnisharp project, but it involved working with the (currently) [undocumented](http://docs.asp.net/en/latest/dnx/design-time-host.html) Design Time Host. It also involved copying the `Microsoft.Framework.DesignTimeHost` code right out from the ASP .Net repository as it's not distributed as a NuGet package yet.

Ultimately, I gave up and will be using the `VisualStudioWorkspace` until this stuff matures. 

That being said, I think it would be greatly beneficial for the Roslyn project to have a `DnxWorkspace` for the same reasons it's nice to have the `MSBuildWorkpace`. Often consumers of Roslyn would like to do their analysis outside of Visual Studio. Today that's really difficult unless you have David Fowler on your team. :)

**Comment by Pilchie** [comment]
Tag @mattwar and @jasonmalinowski.

I believe in the scenario, but I wonder what the right API is to expose it.

**Comment by Pilchie** [comment]
Also tagging @davidfowl.

**Comment by SLaks** [comment]
These seems to be a DnxWorkspace [here](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Dnx/).
Source might be https://github.com/davidfowl/ProjectJsonWorkspace

**Comment by davidfowl** [comment]
I'll update the repository to take the latest changes into account

**Comment by JoshVarty** [comment]
There is also: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.ProjectModel.Workspaces/ProjectJsonWorkspace.cs

Since they've taken the lead here, I'm assuming this probably isn't going to make it into Roslyn, correct? If that's the case, feel free to close this issue as it looks like there are now reasonable options out there.

**Comment by jasonmalinowski** [comment]
We still need to figure out what it means for project.json and MSBuildWorkspace to play together for the command line scenarios, which we still don't have a good answer for yet.
