### ISSUE TITLE
Ruleset file corruption when using multi-select to set analyzer severity for first time in a project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38252]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/408855/ruleset-file-corruption-when-using-multi-select-to.html)._

---
On any project (at least, any CPS-based project) when there is no ruleset file yet associated with the project, VS will create one when I modify the severity of any single analyzer rule in Solution Explorer.<br><br>Solution Explorer also supports multi-selection to change severity on several rules at once. This is super-useful when I want to turn off all analyzers for a project, which is a common workaround to this bug https://github.com/NuGet/Home/issues/6279<br><br>However, the problem is that if multi-selection is used to change the severity when no .ruleset file yet exists for the project, VS creates one .ruleset for *each* selected analzyer, each .ruleset file has only one analyzer severity set. And only the last .ruleset file is actually associated with the project. See repro recording.

---
#### Jinu Joseph [MSFT] on 12/17/2018, 02:44 AM: 

<p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

#### Andrew Arnott [MSFT] on 4/17/2019, 02:03 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Visual Studio Feedback System on 8/23/2019, 03:01 AM: 

I'm closing this report, because in the last 90 days there was no internal developer activity and very small number of new votes or comments. Sorry, we would like to look at this further, but we just don’t have the time right now. Our goal in closing older issues such as this one is to keep customers informed on which issues are currently being pursued by Visual Studio teams. If you still have trouble with our latest version, please report it as a new problem.

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment]
Have we seen this before?

**Comment by mavasani** [comment]
Yep, this was filed by @AArnott and @sharwell was going to mark this as help-wanted and add to backlog.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
