### ISSUE TITLE
Completion: VSMac TypeScript completion doesn't commit with Enter

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#38250]
**Version Used**: 
16.3

**Steps to Reproduce**:

1. Open a .cshtml file in VS (as part of ASP.NET Core MVC project) that contains a JavaScript block
2. open completion in the JS block
3. commit with Enter

**Expected Behavior**:
https://github.com/dotnet/roslyn/blob/4b8c6a7e3eef5cfb7e049d67d5449af3c44101f9/src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs#L307 returns false because on Windows `item.DisplayText.StartsWith(textTypedSoFar, StringComparison.CurrentCultureIgnoreCase)` returns false for `a\0`.

**Actual Behavior**:
The problem on Mono is that comparison returns true for `a\0` and so completion in VSMac in TypeScript doesn't commit

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs,6fc358925a8c4e66

In `TextTypedSoFarMatchesItem` we should explicitly account for `typedChar` being `\0`. We're just getting lucky accidentally. On Mac we're not lucky because that StartsWith comparison is platform-specific.

**Comment by KirillOsenkov** [comment]
FYI @DavidKarlas @AmadeusW @sandyarmstrong

**Comment by KirillOsenkov** [comment]
@jinujoseph this is blocking JavaScript completion in the new WebTools on the new editor in VSMac for 16.3. We'll try to find a workaround, but if there's a chance you can fix this for 16.3 that would be fantastic! Should be relatively straightforward (test the `typedChar` for `\0` explicitly instead of relying on string comparison in current culture, which is flaky). if `typedChar` is `\0` then it's not a filter character and we need to commit.

**Comment by gafter** [comment]
@KirillOsenkov Is this a Roslyn issue?  If so, can you please tag this with the relevant Roslyn Area?

**Comment by vatsalyaagrawal** [comment]
@ivanbasov do we have a fix ready for this one? PR and unit test.

**Comment by KirillOsenkov** [comment]
Update to everyone, now we're not convinced it'a Roslyn bug. After debugging on Windows we see `\n` correctly being passed as a typedChar, instead of `\0`. This bug is not blocking us for 16.3 and I suggest we carry it over until we investigate more.

**Comment by KirillOsenkov** [comment]
@DavidKarlas is pointing out that the bug is only for .js blocks inside .cshtml files. I will investigate some more and report back soon.

**Comment by ivanbasov** [comment]
Assigned to @KirillOsenkov to provide more info.

**Comment by KirillOsenkov** [comment]
@ivanbasov OK we have finally found time to investigate this more. It is indeed a Roslyn bug and we now understand what is going on. 

Basically if you place a function breakpoint in `TextTypedSoFarMatchesItem`, then bring up completion inside a JavaScript script inside a .cshtml file, then press Enter to commit, VS will pass `\0` char to `Helpers.IsFilterCharacter`: http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/AsyncCompletion/Helpers.cs,9540adb32256e2de

On this line, the `\0` char is appended to the `filterText`:
https://github.com/dotnet/roslyn/blob/404c680eea91b6111985b86072554581fbd69558/src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs#L105

In our opinion, `\0` is never a filter char, so a fix would be to insert 

```
if (ch == '\0`)
{
    return;
}
```

at line 107:
https://github.com/dotnet/roslyn/blob/404c680eea91b6111985b86072554581fbd69558/src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/Helpers.cs#L107

This way we never have to even call string comparison for a string that contains a null char (if you remember, there is a behavior difference between Mono and .NET Framework here, causing this bug to happen in the first place).
