### ISSUE TITLE
Strange suggestion to introduce constant for 'true'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38266]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/680962/strange-suggestion-to-introduce-constant-for-true.html)._

---
VS suggests that I &quot;Introduce constant for 'true'&quot;, when it should know that those are special values in a boolean method and just because I use it a few times, I don't need a constant for it.

---
#### Roi Chen [MSFT] on 8/7/2019, 05:00 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature. It will allow other developers to easily find it and engage on it.

**Comment by miloush** [comment]
I just got `return index + 1;` underdotted with _Introduce constant_ and I am not very excited either... perhaps ±1 int constants should be excluded too?

**Comment by CyrusNajmabadi** [comment]
@miloush can you supply a picture?  'introduce constant' is a refactoring in Roslyn.  So it shouldn't have any sort of `underdots`.

For example, i don't see anything:

![image](https://user-images.githubusercontent.com/4564579/63653873-81645900-c727-11e9-8b00-be50b99bf654.png)

![image](https://user-images.githubusercontent.com/4564579/63653876-85907680-c727-11e9-8982-8da39caa2dcb.png)

**Comment by CyrusNajmabadi** [comment]
> VS suggests that I "Introduce constant for 'true'", when it should know that those are special values in a boolean method and just because I use it a few times, I don't need a constant for it.

Could you clarify what you mean by "suggests"?  There is a refactoring offered.  But it only comes up if you explicitly bring it up.  The belief there is that if this is something you want to do, why would we stop you?  For example, it's not uncommon to have a state machine with two states.  in those cases, people do use bools.  And you can absolutely want to then name those bools at some point to make the code clearer.  If we don't offer the feature then, a user would then have to go do this all manually.

**Comment by miloush** [comment]
> So it shouldn't have any sort of underdots.

Oh no, I stand corrected and with cleaned display. :confounded:

I agree that since you need to have a cursor at the number/bool and explicitly invoke the refactoring, offering a constant introduction is a reasonable option.
