### ISSUE TITLE
Cannot implicitly convert `Task<T>` to `Task<T?>`

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#38261]
Currently it's not possible to return an instance of `Task<T>` from a method returning `Task<T?>`. For asynchronous methods, this is not problematic because the awaited result of `Task<T>` can be converted to `T?`. However, method using pass-through to avoid the state machine overhead cannot use this approach.

This situation occurs several times in #35258. It makes code review difficult because while this case is safe, it's not obvious when looking at any given use of the suppression operator whether it falls into this known safe case or is some other situation.

📝 This situation would also apply to `ValueTask<T>`.

Potential solutions seem to include:

1. The compiler having some special knowledge of predefined types like `Task<T>` where the parameter is essentially `out T` but not marked as such due to limitations on covariant types in C#.
2. The ability to mark compile-time covariant generic type parameters (might further require an annotation in the definition of `Task<T>`).
3. A helper method like this:

    ```csharp
    public static Task<TResult?> AsNullable<TResult>(this Task<TResult> task)
      where TResult : class
    {
      // This is a known safe conversion
      return task!;
    }
    ```

**Comment by agocke** [comment]
By design. Compiler is acting appropriately

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/33010
