### ISSUE TITLE
C# IntelliSense incorrently enumerates unrelated extension methods in VS2019 16.3.0 Preview 2.

### ISSUE THREAD

**Issue by dnobori** [dotnet/roslyn#38276]
**Version Used**: 
.NET Core 3.0.0-preview8-28405-07
VS2019 16.3.0 Preview 2

**Steps to Reproduce**:

Sample code:

```csharp
class ABC
{
}

static class Extensions
{
    public static void Hello<T>(this T value) where T : ABC
    {
    }
}

public class Program
{
    static void Main(string[] args)
    {
        Program p = new Program();
        p. // <- type this and incorrect IntelliSense enumeration occurs.
    }
}
```

Visual Studio 2019 16.3.0 Preview 2 incorrently enumerates the unrelated extension method `Hello()` when the developer types 'p.' on the above sample code. 

**Expected Behavior**:
![2](https://user-images.githubusercontent.com/3041130/63647554-f8b4df80-c75d-11e9-9085-c6f2bceefb2a.jpg)

I confirmed that existing non-preview Visual Studios (including VS2017 15.9.13 and VS2019 16.2.2 RTM) doesn't show this incorrect extension method `Hello()` in the IntelliSense enumeration list.

**Actual Behavior**:
![1](https://user-images.githubusercontent.com/3041130/63647555-fbafd000-c75d-11e9-9fea-5234fd5749f2.jpg)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/38109

**Comment by dnobori** [comment]
Thank you so much!
