### ISSUE TITLE
Completion window doesn't appear after commiting compiler directives

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38289]
**Version Used**: 
Version 16.3.0 Preview 3.0 [29221.207.master]

**Steps to Reproduce**:

See: ![Nullable](https://user-images.githubusercontent.com/1103906/63662642-9661ea80-c802-11e9-9667-a954fd44ad15.gif)

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/63662663-a7126080-c802-11e9-9849-fc00a6e618ff.png)

**Actual Behavior**:
Need to manually invoke completion window.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl did anyone do the completion work yet for `nullable` and the `enable/disable/restore` keywords?

**Comment by davkean** [comment]
Doesn't work for any of the directives.

**Comment by davkean** [comment]
@RikkiGibson It doesn't appear to be a regression, this doesn't work in 15.9 or 16.2 either.
