### ISSUE TITLE
A bunch of files in the Roslyn folder are mistakenly queued for ngen

### ISSUE THREAD

**Issue by mthalman** [dotnet/roslyn#38296]
The Roslyn bits included in 4.8 SDK installed from the VS 16.3 Preview Build Tools are causing several files to be queued for ngen that are not valid files to be ngen'd.

**Steps to Reproduce**:

1. Run the following steps on a Windows machine with Docker for Windows installed, targeting Windows containers.
2. Create a new folder on the desktop.
3. Download https://download.visualstudio.microsoft.com/download/pr/6bd8729b-a836-4721-8988-6b9b23649a10/fc200a5e2b37cf4052a63f0b7b66fd1b/vs_buildtools.exe to the new folder.  This URL is what https://aka.ms/vs/16/pre/vs_buildtools.exe is pointing to at the time of creating this issue.
4. Create a file named "Dockerfile" in the same folder with the following contents:
```
# escape=`

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

COPY vs_buildtools.exe .

RUN start /w vs_BuildTools.exe ^ `
    --add Microsoft.Net.Component.4.8.SDK ^ `
    --quiet --norestart --nocache --wait

RUN \Windows\Microsoft.NET\Framework\v4.0.30319\ngen update
```
5. From command line, change the directory to the new folder that you created.  Run the following command: `docker build .`

**Expected Behavior**:
The `docker` command should succeed.

**Actual Behavior**:
The `docker` command fails due to the `ngen` call in the Dockerfile.  Ngen fails due to 2 sets of errors:
1. `X is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)`.  Caused by the following files:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csc.exe.config
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csc.rsp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csi.exe.config
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csi.rsp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.EditorConfig.targets
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.VisualBasic.Core.targets
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\vbc.exe.config
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\vbc.rsp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\VBCSCompiler.exe.config
```

2. `The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)`.  Caused by the following files:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.DiaSymReader.Native.amd64.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.DiaSymReader.Native.x86.dll
```

Full ngen log file is attached: [log.txt](https://github.com/dotnet/roslyn/files/3542580/log.txt)

This is related to #30341 but that issue may be fixed now because I don't see any cases of .pkgdef files causing ngen errors.

**Comment by richlander** [comment]
@jasonmalinowski -- do you know that VS doesn't run into these NGEN issues? It would seem like it would.

**Comment by jasonmalinowski** [comment]
@richlander: hmm? It absolutely logs these too: #30341.

**Comment by richlander** [comment]
Ah, yes. Does it cause ngen for actual binaries to fail or just produce an error message for itself? If it is the former, then this issue should be getting more traction than it is.

**Comment by mthalman** [comment]
It ngens everything it can but then returns a non-zero exit code because of the error.  So anything relying on the exit code is going to have issues.

**Comment by richlander** [comment]
Ah! That makes sense. Does the build tool SKU know how to deal with that?

**Comment by mthalman** [comment]
I don’t believe the Build Tools SKU calls `ngen update` so it’s not really concerned about the result. The problem is with attempting to call `ngen update` _after_ installing Build Tools.

**Comment by richlander** [comment]
Ah. That is horrible, then. It just leaves garbage behind in its wake. That should definitely be fixed, then. This means that you need to do crazy things like we are doing in our Dockerfile to get the expected/desired performance.

**Comment by mthalman** [comment]
After upgrading to the VS 16.4 BuildTools, this particular file is no longer relevant to this issue since it seems to not be included in the ngen queue: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.EditorConfig.targets`

**Comment by mthalman** [comment]
These files are no longer queued for ngen in VS 16.5 Build Tools.  The issue looks to be resolved.
