### ISSUE TITLE
Internal Compiler error

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#38299]
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.2.1
VisualStudio.16.Release/16.2.1+29201.188
Microsoft .NET Framework
Version 4.7.03062

Installierte Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

Application Insights-Tools für Visual Studio-Paket   9.1.00611.1
Application Insights-Tools für Visual Studio

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.290.48383
Weitere Informationen finden Sie unter https://www.asp.net/.

Azure App Service-Tools v3.0.0   16.2.290.48383
Azure App Service-Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.2.290.48383
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C#-Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Fabric.DiagnosticEvents   1.0
Fabric-Diagnoseereignisse

IntelliCode-Erweiterung   1.0
Detaillierte Informationen zur IntelliCode Visual Studio-Erweiterung

JetBrains ReSharper Ultimate 2019.1.3   Build 191.0.20190704.212735
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure-Tools   2.9
Microsoft Azure-Tools für Microsoft Visual Studio 0x10 – v2.9.20626.2

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Service Fabric-Tools für Visual Studio   2.5
Microsoft Azure Service Fabric-Tools für Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Continuous Delivery Tools für Visual Studio   0.4
Die Konfiguration von Azure DevOps-Pipelines von der Visual Studio-IDE aus wird vereinfacht.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio-Tools für Container   1.1
Jetzt können Sie Ihre ASP.NET Core-Anwendung in der Zielumgebung entwickeln, ausführen und überprüfen. Drücken Sie F5, um die Anwendung direkt in einem Container mit Debugfunktionen auszuführen, oder STRG+F5 zum Bearbeiten und Aktualisieren Ihrer Anwendung, ohne den Container erneut erstellen zu müssen.

NuGet-Paket-Manager   5.2.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage-Erweiterung   1.0
Detaillierte Informationen zur ResourcePackage-Erweiterung von Visual Studio

ResourcePackage-Erweiterung   1.0
Detaillierte Informationen zur ResourcePackage-Erweiterung von Visual Studio

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript-Tools   16.0.10627.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools 10.4 für F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 für f# 4.6

Visual Studio-Tools für Container   1.0
Visual Studio-Tools für Container

Visual Studio-Tools für Kubernetes   1.0
Visual Studio-Tools für Kubernetes

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

**Steps to Reproduce**:

1. Clone [this](https://github.com/taori/Sandbox.git) repository, commit https://github.com/taori/Sandbox/commit/2ca1d597b62250f6a096bdaa8d8ad03d90efdcd8
2. Build whole solution
2. Set debug breakpoint as seen in screenshot
3. Start debugging, wait for breakpoint, then hit F10

![grafik](https://user-images.githubusercontent.com/5545184/63725564-056b2d80-c85b-11e9-823f-e05a63d58c53.png)

The code looks a little different with this commit, but the issue still happens.

**Comment by svick** [comment]
I can't reproduce this on VS 16.2.3 or 16.3.0 Preview 2.

**Comment by taori** [comment]
@svick I can give you a dump if you want or perhaps you can watch it live on teamviewer?

**Comment by svick** [comment]
@taori Sorry, I'm just a volunteer contributor. The best I can do is to suggest you to upgrade to VS 16.2.3 and see if that fixes the issue. If not, hopefully, a Microsoft employee will come along soon and help you resolve the issue.

**Comment by taori** [comment]
@svick oh ok. I wasn't aware. Did you build the whole solution before launching the composable web application? This problem might be related to dynamically loaded assemblies. Since there is no reference to the plugins, merely launching the application might not make this issue show up.

**Comment by svick** [comment]
@taori 

>  Did you build the whole solution before launching the composable web application?

Yes, I did. Specifically, what I did:

1. Build → Build Solution.
2. Set a breakpoint at line 15 of src\ComposableWebApplication.SDK.Web\Extensions\MvcBuilderExtensions.cs.
3. Set ComposableWebApplication as the startup project.
4. <kbd>F5</kbd>
5. Wait for the breakpoint to be hit.
6. Press <kbd>F10</kbd> several times.

I didn't see Internal Compiler error while doing this.

**Comment by taori** [comment]
Very curious. still happens to me with 16.2.3

**Comment by jinujoseph** [comment]
Closing this issue.
Confirmed by vendors, no repro in 16.4.Preview2
