### ISSUE TITLE
Intellisense ignore case sensitivity in case of enums and prefers wrong items

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#38297]
```
        void M(SampleEnum sampleEnum)
        {
            
            N($$
        }

        void N(SampleEnum sampleEnum) { }
        enum SampleEnum
        {
            One,
            Two
        }
```

Type `s`.

**Expected**
The selected item is `sampleEnum`.

**Actual**
The selected item is `SampleEnum`.

Please note it works fine with classes (`SampleClass `is available but not default). The issue happens with enums.

**Comment by 0xd4d** [comment]
Very similar to this: https://github.com/dotnet/roslyn/issues/38293

**Comment by allisonchou** [comment]
Design meeting notes (11/29): This is something we agreed should be addressed via abiding by more [filtering rules](https://blog.280z28.org/archives/2011/12/105/) (prefix match and validity match) but it will need a proposal.

**Comment by genlu** [comment]
case sensitivity is respected in current behavior. closed
