### ISSUE TITLE
"View call hierarchy" silently fails for a lot of (valid) caret locations

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38303]
**Version Used**: 
Current master. 

**Steps to Reproduce**:
```csharp
using System;

namespace ConsoleApp5
{
    class Program
    {
        sta[||]tic Pr$$ogram Main(Prog$$ram asdf)
        {
            return null;
        }

        sta[||]tic v[||]oid Main2(in$$t asdf)
        {

        }
    }
}

```

**Expected Behavior**:
Either all locations above will trigger "Cursor must be on member name" error or none of them does (preferable). 

Ideally the service uses `IRefactoringHelpersService` [helpers](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/CodeRefactorings/IRefactoringHelpersService.cs,0a897af4d97aaa71) to handle all logical caret positions. 

**Actual Behavior**:
`$$` locations silently fail while `[||]' produces "Cursor must be on member name" modal error window.

**Solution**:
- [x] Introduce simple fix to properly error out whenever nothing is shown
- [ ] Enable the service for all unambiguous locations (i.e. anywhere in the declaration)

**Comment by petrroll** [comment]
- [x] Introduce simple fix to properly error out whenever nothing is shown
- [ ] Enable the service for all unambiguous locations (i.e. anywhere in the declaration)

**Comment by itaibh** [comment]
For me it didn't find anything:

![image](https://user-images.githubusercontent.com/140983/105970026-93bb9280-6091-11eb-849a-76685f6164f2.png)

**Comment by CyrusNajmabadi** [comment]
closing due to lack of feedback.
