### ISSUE TITLE
Invalid optimization performed by C# compiler for IEnumerable<T> on arrays

### ISSUE THREAD

**Issue by jkotas** [dotnet/roslyn#3830]
```
    enum Enum0 { First }
    enum Enum1 { First }
...
    var source = new Enum0[3];
    bool b = source is IEnumerable<Enum1>;
```

b will be false in this code. It should be true just like when the code is changed to:
```
    object source = new Enum0[3];
    bool b = source is IEnumerable<Enum1>;
```

**Comment by mburbea** [comment]
The same issue happens with other convertible types like `byte` and `sbyte` and `int` and `uint`
e.g.
```csharp
        object o = new int[3];
        Console.WriteLine(o is uint[]);
```
This returns True, but will be False if I change object to `var`. Amusingly resharper warns me that this expression is always False (but its actually true).
![image](https://cloud.githubusercontent.com/assets/213233/8530303/3dcba5ee-23ee-11e5-9462-f2a8f52c0d3c.png)

There's actually several other places in the C# compiler where the runtime allows it, but the compiler optimizes it into an error. I would love if it were fixed.

Unfortunately, this is most likely a breaking change.

**Comment by aevitas** [comment]
According to [Eric Lippert's StackOverflow answer here](http://stackoverflow.com/a/1179094/318973), this is actually an inconsistency between the C# type system and the CLR type system, in which the reason why the decision to leave the inconsistency in was made.

Granted that it's a bug, is this something that should be fixed on compiler level?

**Comment by gafter** [comment]
See an answer to this at

http://blogs.msdn.com/b/ericlippert/archive/2009/09/24/why-is-covariance-of-value-typed-arrays-inconsistent.aspx
