### ISSUE TITLE
Find-Refs filter-list includes lots of options unnecessarily.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#38314]
Here's an example of what i see when i bring up the filter list:

![image](https://user-images.githubusercontent.com/4564579/63801268-beb21d80-c8c4-11e9-802a-c45f40548701.png)

Note that in my case i just have 28 reads and 2 writes.  However, the list is filled with a bunch of other inapplicable cases, all with 0 count.  These should not be in the list.  Note: this is def a bug.  No where else do things work this way.  We always only see items for the values actually in the list.  For example, imagine if filtering on error code worked this way.  You'd have thousands of items in the list, almost all with `(0)` next to them.  Instead, the control works properly and you get:

![image](https://user-images.githubusercontent.com/4564579/63801363-f5883380-c8c4-11e9-93d5-90d51c4c5d8a.png)

**Comment by mavasani** [comment]
@CyrusNajmabadi - just a quick update. This issue was just fixed by the platform team in 16.4 branch.

**Comment by CyrusNajmabadi** [comment]
nice.  thanks for letting me know!
