### ISSUE TITLE
Public API for `GetDocument(DocumentId)` that returns non-null Document

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#38326]
We should add a public API to get `Document` from a `DocumentId` that returns a non-null `Document` or throw if not found.  This would help us avoid using null-forgiving operator (!) when enabling nullable ref.

e.g.

```cs
public Document GetRequiredDocument(DocumentId documentId);
```

We will probably also need an analyzer/codefix to flag usage of `GetDocument(id)!` in code with nullable-ref already enabled.

**Comment by genlu** [comment]
Based on the current usage of nullable suppression operator `!` (225 total in roslyn.sln), we probably want to consider adding the `GetRequiredX` API for the following:

Solution.GetDocument(DocumentId?)
Solution.GetProject(ProjectId?)
Solution.GetAdditionalDocument(DocumentId?)
Project.GetCompilationAsync(CancellationToken)
Project.GetAnalyzerConfigDocument(DocumentId)
Document.GetSemanticModelAsync(CancellationToken)

**Comment by mavasani** [comment]
How about `Document.GetSyntaxRootAsync`?

**Comment by genlu** [comment]
Yes, we have a couple instance of suppression on `GetSyntaxRootAsync` too, so likely we will need to have it as well. Note that the list above isn't supposed to be complete, more of a top priority list, since it's just the top usage of `!` based on roslyn.sln (the annotation in which is patchy at best)
