### ISSUE TITLE
VS crash

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#38333]
**Version Used**: 15.9.15 & 16.2.3

**Steps to Reproduce**:

1. Open git history window
2. Click keyword textbox
3. Type :  `\` `Enter` `BackSpace`

**Actual Behavior**: VS crash.

**Comment by RikkiGibson** [comment]
This bug doesn't appear to be related to Roslyn. Am I missing something?

**Comment by jaredpar** [comment]
This issue appears to be a Visual Studio bug specific to the git integration. This repository is for C# and Visual Basic related issues hence closing this out. Could you please file this bug with VS feedback and they'll route it to the appropriate team? 

https://developercommunity.visualstudio.com/spaces/8/index.html
