### ISSUE TITLE
Nullability infotip is not shown with <Nullable>enable</Nullable> in csproj

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#38346]
**Version Used**: 
Visual Studio 2019 16.3 Preview 3 d16.3

**Steps to Reproduce**:

1. Create a C# project
2. Enable nullable reference types in csproj by adding this to the csproj file.
```xml
<Nullable>enable</Nullable>
```
3. Write the following code
```c#
namespace Demo
{
    using System;
    using System.Text.Json;

    class Program
    {
        static void Main(string[] args)
        {
            string s3 = JsonSerializer.Serialize((a: 1, b: 2, c: null as string));
            Console.WriteLine(s3);
                        
        }
    }
}
```
4. Mouse over to the `s3` in the last line

**Expected Behavior**:
A tooltip window shows up, and the nullability analysis result is included.

![image](https://user-images.githubusercontent.com/12908526/63890436-d1495700-c997-11e9-9264-b0858139f3cd.png)

**Actual Behavior**:
The nullability analysis is not available in the tooltip; it is not available until you add `#nullable enable` to the open file.

![image](https://user-images.githubusercontent.com/12908526/63890495-f938ba80-c997-11e9-8401-1a4fcf54a23a.png)

**Comment by RikkiGibson** [comment]
Do you still get this behavior if you set `<Nullable>enable</Nullable>` in the project, close the solution and re-open it?

**Comment by mazhou-msft** [comment]
This behavior is constant. The only way to get the tooltip annotation for nullability analysis is to put `#nullable enable` in source.

**Comment by RikkiGibson** [comment]
Throwing this in the IDE bucket to start, let me know if this is not the right triage @jasonmalinowski
