### ISSUE TITLE
Code Action preview window showing the end of the content

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#38345]
**Version Used**: 
Visual Studio 2019 16.3 preview 3 d16.3

**Steps to Reproduce**:

1. Create a C# project
2. Move the cursor to `Program` and hit `Ctrl` + `.`
3. Move the cursor to select "Add accessibility modifier"

**Expected Behavior**:
Code Action preview window shows up, also the about-to-change content is visible from the first line without the need to scroll mouse up or down

![image](https://user-images.githubusercontent.com/12908526/63889907-ca6e1480-c996-11e9-8f16-3b1652160254.png)

**Actual Behavior**:
Code Action preview window shows up, the about-to-change content isn't visible, the content is showing the end of the changes and I need to scroll up to see the diff. 

![image](https://user-images.githubusercontent.com/12908526/63889858-b4f8ea80-c996-11e9-941b-163aa5c3e9c4.png)

**Comment by davkean** [comment]
@jinujoseph Heads on this regression in 16.3.

**Comment by mavasani** [comment]
@heejaechang Is this something that Roslyn controls or is it platform controlled?

**Comment by heejaechang** [comment]
@mavasani we setup projection buffer, so we should take a look first.

**Comment by mavasani** [comment]
Thanks, I will investigate.

**Comment by mavasani** [comment]
@heejaechang I verified we are generating the correct preview element and also set the vertical alignment correctly: https://github.com/dotnet/roslyn/blob/8edb65ca478610af3d5f436e3b0e708873addea3/src/VisualStudio/Core/Def/Implementation/PreviewPane/PreviewPane.xaml.cs#L115

Additionally, I also verified there have been no changes in the preview pane implementation for past few months. Who should take a look at this on the platform team?

**Comment by mavasani** [comment]
Tagging @olegtk - can someone from the platform team take a look?

**Comment by olegtk** [comment]
Ouch, seem like a very recent regression, 16.2 Preview2 was fine. @jinujoseph, please route to the editor.

**Comment by vatsalyaagrawal** [comment]
Opened internal bug for editor team per @olegtk suggestion.

**Comment by kendrahavens** [comment]
@olegtk This is making demoing a bit of a pain. Could you link to the internal editor bug? I'm wondering if the update will land before .NET Conf. Thanks.

**Comment by olegtk** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/977191, fixed in 16.3 Preview4, which shipped yesterday.
