### ISSUE TITLE
Update our cached reference count in server

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#38357]
Presently the compiler server will cache the last 100 references read off of disk. This number was chosen arbitrarily as dictated by the comment in [the file](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Server/VBCSCompiler/MetadataCache.cs#L17):

``` csharp
        // Store 100 entries -- arbitrary number
        private const int CacheSize = 100;
```

At the time this number was chosen though desktop was the primary scenario. It's possible this number was based off of the average reference count for desktop projects which is typically less than 100. Hence the cache would comfortably persist across compilations for desktop projects (or maybe the number was completely arbitrary). 

This number though doesn't help us with .NET Core style projects where reference counts are significantly higher:

|Target Framework|Average Reference Count|
|--|--|
|.NET Standard|165|
|.NET Core|201|
|ASP.NET Core|323|

This means for newer projects the compiler server reference cache effectively does not exist. At least half of the references are getting evicted on every compilation. Based on this I think we need to update our reference cached count to 350 to ensure we're providing the most value for the

**Comment by agocke** [comment]
SGTM

**Comment by cartermp** [comment]
References count distribution for aspnet core

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6309070/63907546-b810cc80-c9d0-11e9-9768-8e5fd9bf6975.png)

**Comment by cartermp** [comment]
References count distribution at 50th/75th/95th percentile which looks like it matches the above

|percentile_References_50 | percentile_References_75 | percentile_References_95
-- | -- | --
341 | 366 | 408

Not sure which number matters the most here but we may wanna do more than 350
