### ISSUE TITLE
Bad error message for generic field

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#38352]
```cs
#nullable enable
public class C<T> {
	T t;
}
```
```
warning CS8618: Non-nullable field 't' is uninitialized. Consider declaring the field as nullable.
```
The recommendation here is something that cannot be done, we shouldn't recommend making the field nullable when it's of type T.

**Comment by RikkiGibson** [comment]
This looks like a scenario where we might suggest use of the `[MaybeNull]` attribute?

**Comment by RikkiGibson** [comment]
I think this is fine now due to `T?`. /cc @cston @333fred
