### ISSUE TITLE
 [loc][Query][roslyn] Localizability of "0; "WRN_UninitializedNonNullableField"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#38369]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Non-nullable {0} '{1}' is uninitialized. Consider declaring the {0} as nullable.

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
assumed that the placeholder {0} will be replaced with "field" and translated accordingly. Please kindly inform us what this placeholder will be replaced with.

**Comment by miloush** [comment]
If you just searched this codebase for WRN_UninitializedNonNullableField, you would have found out that {0} can be either "field" or "event" or "property" and {1} is the name of that member.

**Comment by jaredpar** [comment]
As @miloush stated `{0}` can be replaced with "field", "event" or "property" while `{1}` is the name of the former.
