### ISSUE TITLE
[Regression] Code fix previews are not visible by default

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38365]
**Visual Studio Version**:
Version 16.4.0 Preview 1.0 [29228.128.master]

**Summary**:

Not sure if this also occurs in 16.3 as don't currently have build installed.

**Steps to Reproduce**:

1. Navigate to a code fix/refactoring that has a preview

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/63910494-3ec5b800-ca6a-11e9-8c96-167f84a4dc07.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/63910496-44bb9900-ca6a-11e9-8274-e48ffd1031e1.png)

**User Impact**:

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/38345.
