### ISSUE TITLE
CS8617 warning. Maybe fixed but....

### ISSUE THREAD

**Issue by SebastianMirocha** [dotnet/roslyn#38360]
**Version Used**: 

- VS2019 16.2.3
- .Net Core 3.0 Preview 8

**Steps to Reproduce**:

1. Create a solution with two .Net Core libraries (Lib2 references Lib1).

```
	<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
			<TargetFramework>netcoreapp3.0</TargetFramework>
			<LangVersion>8.0</LangVersion>
			<Nullable>enable</Nullable>
		</PropertyGroup>
	</Project>
```

2. Add following interface to Lib1 project:

```
    namespace Lib1
    {
        public interface IFace
        {
            string? FilePath { get; }
            bool? LoadSolverConfiguration(bool isDefault) => true;
        }
    }
```

3. Add following class to Lib2 project

```
    using Lib1;

    namespace Lib2
    {
        public class Implementation : IFace
        {
            public string? FilePath => null;
            bool? IFace.LoadSolverConfiguration(bool isDefault) => true;
        }
    }
```

**Expected Behavior**:

No warning.

**Actual Behavior**:

Warning CS8617 Nullability of reference types in type of parameter 'isDefault' doesn't match implemented member 'bool? IFace.LoadSolverConfiguration(bool isDefault)'.

Maybe the same case as in [#37927](https://github.com/dotnet/roslyn/issues/37927) (CS8614) but please verify it's not.

**Comment by RikkiGibson** [comment]
tagging @cston.

**Comment by cston** [comment]
Yes, this looks to be the same issue as https://github.com/dotnet/roslyn/issues/37927, fixed in https://github.com/dotnet/roslyn/pull/36784.
