### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of "0; "IDS_CSCHelp"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#38368]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
\r\n                             Visual C# Compiler Options\r\n\r\n                       - OUTPUT FILES -\r\n-out:<file>                   Specify output file name (default: base name of\r\n                              file with main class or first file)\r\n-target:exe                   Build a console executable (default) (Short\r\n                              form: -t:exe)\r\n-target:winexe                Build a Windows executable (Short form:\r\n                              -t:winexe)\r\n-target:library               Build a library (Short form: -t:library)\r\n-target:module                Build a module that can be added to another\r\n                              assembly (Short form: -t:module)\r\n-target:appcontainerexe       Build an Appcontainer executable (Short form:\r\n                              -t:appcontainerexe)\r\n-target:winmdobj              Build a Windows Runtime intermediate file that\r\n                              is consumed by WinMDExp (Short form: -t:winmdobj)\r\n-doc:<file>                   XML Documentation file to generate\r\n-refout:<file>                Reference assembly output to generate\r\n-platform:<string>            Limit which platforms this code can run on: x86,\r\n                              Itanium, x64, arm, arm64, anycpu32bitpreferred, or\r\n                              anycpu. The default is anycpu.\r\n\r\n                       - INPUT FILES -\r\n-recurse:<wildcard>           Include all files in the current directory and\r\n                              subdirectories according to the wildcard\r\n                              specifications\r\n-reference:<alias>=<file>     Reference metadata from the specified assembly\r\n                              file using the given alias (Short form: -r)\r\n-reference:<file list>        Reference metadata from the specified assembly\r\n                              files (Short form: -r)\r\n-addmodule:<file list>        Link the specified modules into this assembly\r\n-link:<file list>             Embed metadata from the specified interop\r\n                              assembly files (Short form: -l)\r\n-analyzer:<file list>         Run the analyzers from this assembly\r\n                              (Short form: -a)\r\n-additionalfile:<file list>   Additional files that don't directly affect code\r\n                              generation but may be used by analyzers for producing\r\n                              errors or warnings.\r\n-embed                        Embed all source files in the PDB.\r\n-embed:<file list>            Embed specific files in the PDB.\r\n\r\n                       - RESOURCES -\r\n-win32res:<file>              Specify a Win32 resource file (.res)\r\n-win32icon:<file>             Use this icon for the output\r\n-win32manifest:<file>         Specify a Win32 manifest file (.xml)\r\n-nowin32manifest              Do not include the default Win32 manifest\r\n-resource:<resinfo>           Embed the specified resource (Short form: -res)\r\n-linkresource:<resinfo>       Link the specified resource to this assembly\r\n                              (Short form: -linkres) Where the resinfo format\r\n                              is <file>[,<string name>[,public|private]]\r\n\r\n                       - CODE GENERATION -\r\n-debug[+|-]                   Emit debugging information\r\n-debug:{full|pdbonly|portable|embedded}\r\n                              Specify debugging type ('full' is default,\r\n                              'portable' is a cross-platform format,\r\n                              'embedded' is a cross-platform format embedded into\r\n                              the target .dll or .exe)\r\n-optimize[+|-]                Enable optimizations (Short form: -o)\r\n-deterministic                Produce a deterministic assembly\r\n                              (including module version GUID and timestamp)\r\n-refonly                      Produce a reference assembly in place of the main output\r\n-instrument:TestCoverage      Produce an assembly instrumented to collect\r\n                              coverage information\r\n-sourcelink:<file>            Source link info to embed into PDB.\r\n\r\n                       - ERRORS AND WARNINGS -\r\n-warnaserror[+|-]             Report all warnings as errors\r\n-warnaserror[+|-]:<warn list> Report specific warnings as errors\r\n-warn:<n>                     Set warning level (0-4) (Short form: -w)\r\n-nowarn:<warn list>           Disable specific warning messages\r\n-ruleset:<file>               Specify a ruleset file that disables specific\r\n                              diagnostics.\r\n-errorlog:<file>              Specify a file to log all compiler and analyzer\r\n                              diagnostics.\r\n-reportanalyzer               Report additional analyzer information, such as\r\n                              execution time.\r\n\r\n                       - LANGUAGE -\r\n-checked[+|-]                 Generate overflow checks\r\n-unsafe[+|-]                  Allow 'unsafe' code\r\n-define:<symbol list>         Define conditional compilation symbol(s) (Short\r\n                              form: -d)\r\n-langversion:?                Display the allowed values for language version\r\n-langversion:<string>         Specify language version such as\r\n                              `latest` (latest version, including minor versions),\r\n                              `default` (same as `latest`),\r\n                              `latestmajor` (latest version, excluding minor versions),\r\n                              `preview` (latest version, including features in unsupported preview),\r\n                              or specific versions like `6` or `7.1`\r\n-nullable[+|-]                Specify nullable context option enable|disable.\r\n-nullable:{enable|disable|warnings|annotations}\r\n                              Specify nullable context option enable|disable|warnings|annotations.\r\n\r\n                       - SECURITY -\r\n-delaysign[+|-]               Delay-sign the assembly using only the public\r\n                              portion of the strong name key\r\n-publicsign[+|-]              Public-sign the assembly using only the public\r\n                              portion of the strong name key\r\n-keyfile:<file>               Specify a strong name key file\r\n-keycontainer:<string>        Specify a strong name key container\r\n-highentropyva[+|-]           Enable high-entropy ASLR\r\n\r\n                       - MISCELLANEOUS -\r\n@<file>                       Read response file for more options\r\n-help                         Display this usage message (Short form: -?)\r\n-nologo                       Suppress compiler copyright message\r\n-noconfig                     Do not auto include CSC.RSP file\r\n-parallel[+|-]                Concurrent build.\r\n-version                      Display the compiler version number and exit.\r\n\r\n                       - ADVANCED -\r\n-baseaddress:<address>        Base address for the library to be built\r\n-checksumalgorithm:<alg>      Specify algorithm for calculating source file\r\n                              checksum stored in PDB. Supported values are:\r\n                              SHA1 or SHA256 (default).\r\n-codepage:<n>                 Specify the codepage to use when opening source\r\n                              files\r\n-utf8output                   Output compiler messages in UTF-8 encoding\r\n-main:<type>                  Specify the type that contains the entry point\r\n                              (ignore all other possible entry points) (Short\r\n                              form: -m)\r\n-fullpaths                    Compiler generates fully qualified paths\r\n-filealign:<n>                Specify the alignment used for output file\r\n                              sections\r\n-pathmap:<K1>=<V1>,<K2>=<V2>,...\r\n                              Specify a mapping for source path names output by\r\n                              the compiler.\r\n-pdb:<file>                   Specify debug information file name (default:\r\n                              output file name with .pdb extension)\r\n-errorendlocation             Output line and column of the end location of\r\n                              each error\r\n-preferreduilang              Specify the preferred output language name.\r\n-nosdkpath                    Disable searching the default SDK path for standard library assemblies.\r\n-nostdlib[+|-]                Do not reference standard library (mscorlib.dll)\r\n-subsystemversion:<string>    Specify subsystem version of this assembly\r\n-lib:<file list>              Specify additional directories to search in for\r\n                              references\r\n-errorreport:<string>         Specify how to handle internal compiler errors:\r\n                              prompt, send, queue, or none. The default is\r\n                              queue.\r\n-appconfig:<file>             Specify an application configuration file\r\n                              containing assembly binding settings\r\n-moduleassemblyname:<string>  Name of the assembly which this module will be\r\n                              a part of\r\n-modulename:<string>          Specify the name of the source module\r\n

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
Would you please check if the elements wihtin angle brackets can be translated?

**Comment by miloush** [comment]
At least make sure anyone will be willing to read your question...

```

 Visual C# Compiler Options

 - OUTPUT FILES -
-out: Specify output file name (default: base name of
 file with main class or first file)
-target:exe Build a console executable (default) (Short
 form: -t:exe)
-target:winexe Build a Windows executable (Short form:
 -t:winexe)
-target:library Build a library (Short form: -t:library)
-target:module Build a module that can be added to another
 assembly (Short form: -t:module)
-target:appcontainerexe Build an Appcontainer executable (Short form:
 -t:appcontainerexe)
-target:winmdobj Build a Windows Runtime intermediate file that
 is consumed by WinMDExp (Short form: -t:winmdobj)
-doc: XML Documentation file to generate
-refout: Reference assembly output to generate
-platform: Limit which platforms this code can run on: x86,
 Itanium, x64, arm, arm64, anycpu32bitpreferred, or
 anycpu. The default is anycpu.

 - INPUT FILES -
-recurse: Include all files in the current directory and
 subdirectories according to the wildcard
 specifications
-reference:= Reference metadata from the specified assembly
 file using the given alias (Short form: -r)
-reference: Reference metadata from the specified assembly
 files (Short form: -r)
-addmodule: Link the specified modules into this assembly
-link: Embed metadata from the specified interop
 assembly files (Short form: -l)
-analyzer: Run the analyzers from this assembly
 (Short form: -a)
-additionalfile: Additional files that don't directly affect code
 generation but may be used by analyzers for producing
 errors or warnings.
-embed Embed all source files in the PDB.
-embed: Embed specific files in the PDB.

 - RESOURCES -
-win32res: Specify a Win32 resource file (.res)
-win32icon: Use this icon for the output
-win32manifest: Specify a Win32 manifest file (.xml)
-nowin32manifest Do not include the default Win32 manifest
-resource: Embed the specified resource (Short form: -res)
-linkresource: Link the specified resource to this assembly
 (Short form: -linkres) Where the resinfo format
 is [,[,public|private]]

 - CODE GENERATION -
-debug[+|-] Emit debugging information
-debug:{full|pdbonly|portable|embedded}
 Specify debugging type ('full' is default,
 'portable' is a cross-platform format,
 'embedded' is a cross-platform format embedded into
 the target .dll or .exe)
-optimize[+|-] Enable optimizations (Short form: -o)
-deterministic Produce a deterministic assembly
 (including module version GUID and timestamp)
-refonly Produce a reference assembly in place of the main output
-instrument:TestCoverage Produce an assembly instrumented to collect
 coverage information
-sourcelink: Source link info to embed into PDB.

 - ERRORS AND WARNINGS -
-warnaserror[+|-] Report all warnings as errors
-warnaserror[+|-]: Report specific warnings as errors
-warn: Set warning level (0-4) (Short form: -w)
-nowarn: Disable specific warning messages
-ruleset: Specify a ruleset file that disables specific
 diagnostics.
-errorlog: Specify a file to log all compiler and analyzer
 diagnostics.
-reportanalyzer Report additional analyzer information, such as
 execution time.

 - LANGUAGE -
-checked[+|-] Generate overflow checks
-unsafe[+|-] Allow 'unsafe' code
-define: Define conditional compilation symbol(s) (Short
 form: -d)
-langversion:? Display the allowed values for language version
-langversion: Specify language version such as
 latest (latest version, including minor versions),
 default (same as latest),
 latestmajor (latest version, excluding minor versions),
 preview (latest version, including features in unsupported preview),
 or specific versions like 6 or 7.1
-nullable[+|-] Specify nullable context option enable|disable.
-nullable:{enable|disable|warnings|annotations}
 Specify nullable context option enable|disable|warnings|annotations.

 - SECURITY -
-delaysign[+|-] Delay-sign the assembly using only the public
 portion of the strong name key
-publicsign[+|-] Public-sign the assembly using only the public
 portion of the strong name key
-keyfile: Specify a strong name key file
-keycontainer: Specify a strong name key container
-highentropyva[+|-] Enable high-entropy ASLR

 - MISCELLANEOUS -
@ Read response file for more options
-help Display this usage message (Short form: -?)
-nologo Suppress compiler copyright message
-noconfig Do not auto include CSC.RSP file
-parallel[+|-] Concurrent build.
-version Display the compiler version number and exit.

 - ADVANCED -
-baseaddress:
Base address for the library to be built
-checksumalgorithm: Specify algorithm for calculating source file
 checksum stored in PDB. Supported values are:
 SHA1 or SHA256 (default).
-codepage: Specify the codepage to use when opening source
 files
-utf8output Output compiler messages in UTF-8 encoding
-main: Specify the type that contains the entry point
 (ignore all other possible entry points) (Short
 form: -m)
-fullpaths Compiler generates fully qualified paths
-filealign: Specify the alignment used for output file
 sections
-pathmap:=,=,...
 Specify a mapping for source path names output by
 the compiler.
-pdb: Specify debug information file name (default:
 output file name with .pdb extension)
-errorendlocation Output line and column of the end location of
 each error
-preferreduilang Specify the preferred output language name.
-nosdkpath Disable searching the default SDK path for standard library assemblies.
-nostdlib[+|-] Do not reference standard library (mscorlib.dll)
-subsystemversion: Specify subsystem version of this assembly
-lib: Specify additional directories to search in for
 references
-errorreport: Specify how to handle internal compiler errors:
 prompt, send, queue, or none. The default is
 queue.
-appconfig: Specify an application configuration file
 containing assembly binding settings
-moduleassemblyname: Name of the assembly which this module will be
 a part of
-modulename: Specify the name of the source module
```

**Comment by miloush** [comment]
And if by angle brackets you mean `[]` there is only two words in the whole text you are asking about, which are ` [,[,public|private]]`, which are command line parameters and should not be translated.

I hope you are not translating any of the words after hyphen either.

**Comment by jaredpar** [comment]
Please let us know if you need anything beyond @miloush answer.
