### ISSUE TITLE
Add 'Remove Parameter' to Change Signature from Quick Action and Refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38384]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/354008/add-remove-parameter-to-change-signature-from-quic.html)._

---
<p>i love the Change Signature option when it comes to removing or reordering parameters.  so many times i know i now need to remove a parameter that is no longer used.  the Change Signature... option brings up the dialog box that allows me to remove one or more parameters.  it would be nice if VS could recognize the parameter i was on when i selected the Quick Action and Refactoring option and show a secondary menu where Remove Parameter was one of the options.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/43641-changesignature.png"> Image:43641-changesignature.png</a></p><p><p>could be changed to something like:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/43642-replace.png"> Image:43642-replace.png</a></p><p>where Change Signature sub menu could contain an option to 'Remove assignedStandardId' and an option to bring up the entire Change Signature dialog.</p><p>just an idea.  i know i do this quite a bit during refactoring.</p><p><p>another nice option would be that when there are two parameters, a new Change Signature sub menu could contain an option to 'swap order of parameters'</p><p>thanks!</p>

---
#### Fiona Niu[MSFT] on 10/11/2018, 03:21 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about two weeks on our next steps. </p>

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
