### ISSUE TITLE
syntax highlighting for custom keywords (like ViewBag, ViewData etc.)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38388]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/429907/syntax-highlighting-for-custom-keywords-like-viewb.html)._

---
<p>Please add one feature that should allows us to define custom keywords and highlighting styles.<br>I
 really needed this for words like &quot;ViewBag&quot;, which is now displays as 
normal text (black) but i really want to make it noticeable.<br>Thanks.</p>

---
#### Jane Wu [MSFT] on 1/18/2019, 00:04 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Cameron on 2/18/2019, 01:02 PM: 

<p>Hi there,</p><p>Was there a solution to this query? I would like to know how to do the same thing except with specific words in a csv file opened in VS code.</p><p>Thanks.</p>

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this.
