### ISSUE TITLE
Search in Git history window doesn't work fine with multiline.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#38385]
Sometimes, we will commit with multiline message, such as:

Enter the following commit message:
```
first line
second line
```
Search `first` in git history window can find this commit, but `second` can't.

**Comment by jaredpar** [comment]
This issue appears to be a Visual Studio bug specific to the git integration. This repository is for C# and Visual Basic related issues hence closing this out. Could you please file this bug with VS feedback and they'll route it to the appropriate team? 

https://developercommunity.visualstudio.com/spaces/8/index.html
