### ISSUE TITLE
I hope to get option to insert "#nullable enable" when C# source code is created

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38387]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/399522/i-hope-to-get-option-to-insert-nullable-enable-whe.html)._

---
<p>In Visual Studio 2019 and C# 8.0, I want to use &quot;#nullable enable&quot; by default. I request an option to insert &quot;#nullable enable&quot; in all source codes when created, in Visual Studio 2019.</p>

---
#### Jane Wu [MSFT] on 12/5/2018, 06:54 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by sharwell** [comment]
Is it a viable alternative to specify the default behavior in the project file (where it would automatically apply to source files in the project)?

```xml
<PropertyGroup>
  <Nullable>enable</Nullable>
</PropertyGroup>
```

**Comment by CyrusNajmabadi** [comment]
`<Nullable>enable</Nullable>` is now the default in .net projects.  Given that, i don't think we need a feature here for older projects.
