### ISSUE TITLE
Global.Microsoft.VisualBasic.MyServices.Internal.ContextValue is not defined

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38405]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/693419/globalmicrosoftvisualbasicmyservicesinternalcontex.html)._

---
Upgraded to Preview 2.0 and VB Core 3.0 applications no longer compile, they are multiple errors and warnings.

---
#### Visual Studio Feedback System on 8/14/2019, 03:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### James Mu solved on 8/13/2019, 11:35 PM, 0 votes: 

<p>I solved this problem by adding the following code to a new VB code file:</p><pre>Namespace Global.Microsoft.VisualBasic.MyServices.Internal
    Public Class ContextValue(Of T)
        Public Property Value As T
    End Class
End Namespace
</pre>

**Comment by paul1956** [comment]
This is fixed in Preview 9, which you can preview
For preview 2.0 ONLY, Under Tools/Options/Package Sources, add a new source by clicking +,
https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json with the name dotnet-core.
