### ISSUE TITLE
CS8602 When using AutoMapper ForPath

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38404]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/622380/cs8602-when-using-automapper-forpath.html)._

---
When using AutoMapper in dotnet core 3.0 and C# 8 will nullable reference types, I'm receiving a CS8602 error when using the `ForPath` method.

If `d.LastModifiedBy` is marked as nullable, I receieve a warning for the following code:

`.ForPath(d => d.LastModifiedBy.UserId, x => x.MapFrom(s => s.Transaction.LastModifiedBy))`

There should be a way for developers, like those who work on AutoMapper, to mark parameters as being null-safe. During mapping with the `ForPath` method, AutoMapper will create the `d.LastModifiedBy` object and an exception will not occur.

The workaround is to surround all my . ForPath methods with `#pragma warning disable CS8602 // Dereference of a possibly null reference.`

This workaround could lead to additional null reference exceptions occurring, such as if `s.Transaction` was null.

---
#### Visual Studio Feedback System on 6/26/2019, 02:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 06:34 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
It looks like the user is requesting a feature where parameters can be annotated such that warnings are suppressed on arguments for those parameters.

I think this is something we can re-examine when more feedback comes in and we get a better understanding of the use cases that motivate this feature.

At this point, if you know that the method you're calling is going to call your delegate/expression tree with "filled-in" arguments, or if it's not compiling and running the expression tree but only traversing it, that's a good candidate for the '!' suppression operator.

**Comment by jcouv** [comment]
I didn't fully understand this issue. Would it be possible to provide a small self-contained repro, such as a [sharplab](https://sharplab.io/) snippet?

> If `d.LastModifiedBy` is marked as nullable, I receieve a warning for the following code:
> `.ForPath(d => d.LastModifiedBy.UserId, x => x.MapFrom(s => s.Transaction.LastModifiedBy))`

I assume the warning would be on the dereference of `d.LastModifiedBy`. If so, the problem seems unrelated to the `ForPath` method.

If the warning is produced on passing a possible null value to a non-nullable parameter of the `ForPath` method, there are a few possible solutions:
- mark that parameter as nullable (ie. `ForPath` can handle null values)
- mark the argument with a `!` suppression (`ForPath(argument!)`)

I'll leave this issue open for another couple of weeks to give the user a chance to provide more details. Thanks

**Comment by Davilink** [comment]
I guess it something like that
![image](https://user-images.githubusercontent.com/1498932/91219204-4012da80-e6e8-11ea-9993-fd5d1f7efe56.png)
```csharp
public class Customer : BaseEntity
{
  public string Name { get; set; } = default!;
  public virtual Address? Address { get; set; }
}
```
