### ISSUE TITLE
we should provide analyzer performance insight to users so that user can decide which analyzers they want to disable for a certain solution

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38424]
analyzers perf is very sensitive to how code is written. some analyzer runs cheap on a file, but very expansive on other code. so just enabling all analyzers by default sometimes cause a problem for users.

internally, we run this monitor to track bad analyzers (http://source.roslyn.io/#Microsoft.CodeAnalysis.Remote.Workspaces/Diagnostics/PerformanceTrackerService.cs,19) and we have been running it for a while.

we should provide this information to users and let users to disable those reported bad analyzers for thier solution easily through UI.

with editorconfig work we did, and work to change analyzer severity through LB, I think now we have all the pieces to create analyzer blame UI and let users to control what analyzers run on what solution/project.

**Comment by CyrusNajmabadi** [comment]
Closing out due to no movement in 5 years.
