### ISSUE TITLE
.editorconfig is causing memory explosion in syntax trees

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#38426]
(FYI: This may be one of the root causes of #38330 reported by @davkean.)

I have a solution which is made up of multiple copies of the project-system repo (~400 projects in total). Looking a dump of the managed heap, nearly 10% of the managed heap (243mb of 2.3Gb) is consumed by duplicated strings held by `CSharpSyntaxTree.ParsedSyntaxTree`. The issue is that the project-system repo has an .editorconfig that turns diagnostics on/off and `Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath` does substring parsing of rules of the form "dotnet_diagnostic.<diagnostic>.severity". Since it does this _for each syntax tree in the solution_ (~6 million of them in this case), each substring parse is duplicated over and over and over again. It looks like if `AnalyzerConfig.Section` just did this substring parsing once and passed back the same string for everyone, this would eliminate the duplication.

**Comment by panopticoncentral** [comment]
I reran our perf test with this fix and while it improves things, there is still an issue. Although the strings are shared now, we seem to be still creating an instance of `ImmutableDictionary<string, ReportDiagnostic>` per parse tree. In my test solution with 352 projects, there are 33,304 instances of this dictionary with 4.5 million nodes, taking up 165 MB of the managed heap, about 10% of the heap and by far the largest single chunk of memory.

**Comment by jasonmalinowski** [comment]
@agocke Should this be closed now that #38760 is merged?

**Comment by agocke** [comment]
Waiting for @panopticoncentral to confirm that the perf problem is ameliorated.

**Comment by panopticoncentral** [comment]
I was finally able to create a VS drop with the fix included and verified that the memory is gone, so you can consider this verified!

**Comment by agocke** [comment]
@panopticoncentral Great, thanks!
