### ISSUE TITLE
update build error more frequently when build + intellisense error filter is selected like when "Build only" is selected

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38428]
right now, when "Build Only" is selected in error list, we update build errors as they come in.

![image](https://user-images.githubusercontent.com/1333179/64053135-ff649d80-cb35-11e9-8757-4d3b998491f8.png)

but when "Build + intellisense" is selected in error list, we don't update build errors until whole build is done and relies on live errors (intellisense errors) during that time. and we do de-duplication when build is done with all errors build has reported again live errors.

![image](https://user-images.githubusercontent.com/1333179/64053151-0d1a2300-cb36-11e9-9313-bd446b5d915b.png)

we should try to improve "build + intellisense" case so that user can see build error update sooner like "build only" case.

**Comment by heejaechang** [comment]
complication is cost de-duplication. more frequently we do, we take away more resources from build.

if that cost turns out to be fine, updating more frequently is straightforward.

**Comment by CyrusNajmabadi** [comment]
Closing out as this will all be handled by LSPClient in teh future.
