### ISSUE TITLE
Include parameters', this class' fields' and local variables' values on stack trace

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/roslyn#38423]
I've seen this when executing Python in some environments: when an error (exception) is raised, all pertinent values up and down the stack are captured. This greatly improves debugging, in many cases allowing a bug to be fixed without having to reproduce the entire scenario by stepping through code, etc.

**Version Used**: Both .NET Framework and Core

**Steps to Reproduce**:

Throw an exception, or use "new StackTrace()"

**Expected Behavior**: Values are captured and shown in the stack trace

**Actual Behavior**: Values are not captured

**Comment by RikkiGibson** [comment]
This looks like it might be more appropriate as a feature request in https://github.com/dotnet/coreclr.

**Comment by TahirAhmadov** [comment]
For those who come across this, I found an existing item here: https://github.com/dotnet/coreclr/issues/24573
