### ISSUE TITLE
CodeActions light-bulb isn't stable

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38431]
**Version Used**: 
Current Int Preview

**Steps to Reproduce**:
```csharp

using System;

namespace ReordTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var result = method($$arg);
        }
    }
}
```
1.  Hammer `Ctr`+`.` and `esc` at specified location
2.  Sometimes move caret elsewhere

> Note: Tried to find a reliable repro, can't.

**Expected Behavior**:
The same lightbulb actions always show up.

**Actual Behavior**:
Sometimes one CodeActions is missing
![image](https://user-images.githubusercontent.com/1764721/64055194-d8ab6480-cb3f-11e9-91d6-248e92d1f6e5.png)
![image](https://user-images.githubusercontent.com/1764721/64055199-dba65500-cb3f-11e9-8e24-485b26d88821.png)

**Comment by petrroll** [comment]
And I've managed to invoke this as well (seems to happen if I press ctr+. quickly enough): 
![image](https://user-images.githubusercontent.com/1764721/64055498-9edb5d80-cb41-11e9-8d95-93066a879bc7.png)

**Comment by huoyaoyuan** [comment]
Experienced in 16.2 too.
Sometimes it throws exception. Sometimes it only shows at left margin, but not under the corresponding word.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
