### ISSUE TITLE
provide an option to log what IDE is doing somewher

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38432]
some long-running features provide a way to log its activity in some places such as output window or binlog and etc.

for example, liveshare or live unit test or source-based discovery provides an option in the options page to log every activity it does in the output window.

project system provides MSBuild binlog to save all design-time build activity in bin log.

we should provide one for our BG workloads such as workspace events, solution crawler events, diagnostic events and etc.

**Comment by heejaechang** [comment]
opened follow some users feedback who want to know what IDE is exactly doing at the moment. it could be helpful for dev as well.

**Comment by CyrusNajmabadi** [comment]
Closing out. We already have telemetry and logs we collect.
