### ISSUE TITLE
Provide special error message and/or code fix for when a variable is referenced on the same line that it's initialized.

### ISSUE THREAD

**Issue by TheUnlocked** [dotnet/roslyn#38446]
This is a proposal stemming from https://github.com/dotnet/csharplang/issues/2744, for if you want to see some additional discussion of it.

If you write the line
```csharp
Func<int, int> factorial = n => n <= 1 ? 1 : n * factorial(n-1);
```
then you get the error `CS0165 Use of unassigned local variable 'factorial'`. The solution to this seems unclear at first, but a lightbulb with a "Use local function" code fix pops up, and that will of course resolve the issue.

However, there are other situations where you won't be so lucky:
```csharp
class Foo : IFoo {
    public Func<IFoo> fooAction;
    public string fooString;
    public Foo (Func<IFoo> fooAction, string fooString) {
        this.fooAction = fooAction;
        this.fooString = fooString;
    }
}

Foo obj = new Foo(() => obj, "Hello, World!");
```
Here the same error appears, but no IDE assistance is provided to fix it, leaving a programmer wondering how they can solve the issue. Of course, simply initializing `obj` to another value (like `null`) before assigning it would work, but the programmer wouldn't necessarily know that. I propose adding a special error message in this case, for example `Use of unassigned local variable 'obj'. 'obj' must be initialized before it can be assigned in terms of itself.` or something like that (I'm not the greatest at writing good errors). Additionally, I propose a code fix in this situation (possibly _only_ for when the variable is used in a lambda expression) to convert
```csharp
Foo obj = new Foo(() => obj, "Hello, World!");
```
to
```csharp
Foo obj = null; // or default
obj = new Foo(() => obj, "Hello, World!");
```

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
