### ISSUE TITLE
Better Peek Definition

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38459]
Customer request copying here:

**Version Used**: 
Visual Studio 2019

**Steps to Reproduce**:

1. Create a more narrow focus.
2.  Don't want to have to scroll up and down to get the documentation. 
3. Would like to have summary, params, returns (if any), remarks, exceptions (if any). When looking for help on a given method no need to display how the method is implemented (can use Go To Definition for this) and should therefore show the actual documentation. 

**Expected Behavior**:
![ReSharperCtrlShiftF1](https://user-images.githubusercontent.com/46729679/64201895-a30ac200-ce44-11e9-96ee-94f808678101.png)

**Actual Behavior**:
![peekwindow](https://user-images.githubusercontent.com/46729679/64202519-3395d200-ce46-11e9-9f35-7c08f7303fd5.png)

**Comment by jmarolf** [comment]
@cartermp I think F# has a behavior similar to this for QuickInfo. What was learned from the design over there?

**Comment by cartermp** [comment]
F# example:

![image](https://user-images.githubusercontent.com/6309070/64203869-4bbb2080-ce49-11e9-883e-7d7ba04261af.png)

Each link is clickable and will go to definition.

Big learning there is that lots of folks prefer clicking the links than hitting f12.

**Comment by allisonchou** [comment]
Notes from today's design meeting (10/26):
We will prototype the primitives and behaviors on our side, and if the team thinks it is a good idea, we will talk to the Editor team about getting APIs. Ideally, this ends up being owned by Editor.

**Comment by CyrusNajmabadi** [comment]
closing due to lack fo feedback and large implementation cost.
