### ISSUE TITLE
IDE offers suggestion to "InlineTemporaryVariable" where (with lambdas) it changes the behavior of the program

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#3846]
Is it by design that the IDE offers to "InlineTemporaryVariable" in places where doing so will change the meaning of your program? and it's just up to you the user to figure out those places and know to avoid them?

I ran into a case today where I inlined a temporary via the quick-fix, and my program started crashing. This isn't a "theoretical" repro -- it's something I actually ran into.

**Repro1:** In this case, inlining the member-access causes it to now happen after a method-call that invalidates the member-access. I guess I'd have liked to see a red warning box around the intermediate thing (even though doing isn't possible in all cases).

``` cs
var keys = new LinkedList<string>(new[] { "a", "b", "c" });
var t = keys.First.Value; // IDE offers a quick-action to InlineTemporaryVariable "t"...
keys.RemoveFirst();
Console.WriteLine(t); // prints "a"

// InlineTemporaryVariable "t" ==> it prints "b" instead
```

``` vb
Dim keys As New LinkedList(Of String)({"a", "b", "c"})
Dim t = keys.First.Value ' IDE offers a quick-action to InlineTemporaryVariable "t"...
keys.RemoveFirst()
Console.WriteLine(t) ' prints "a"

' InlineTemporaryVariable "t" ==> it prints "b" instead
```

**Repro2:** Trickier one here. Inlining the variable causes it to no longer have its value captured inside the lambda closure. I think I rarely want to see the option to inline into a lambda since it's so likely to be dangerous.

``` cs
var keys = new LinkedList<string>(new[] { "a", "b", "c" });
IEnumerable<string> x = new[] { "abc", "bc", "ab", "ac", "a", "b", "c" };

while (keys.Any())
{
    var t = keys.First.Value; // IDE offers a quick-action to InlineTemporaryVariable "t"...
    x = x.Where(r => r.Contains(t));
    keys.RemoveFirst();
}

Console.WriteLine(String.Join(",", x)); // prints "abc"

// InlineTemporaryVariable "t" ==> it throws NullReferenceException instead
```

**Comment by AdamSpeight2008** [comment]
I think this is tricky to fix. I needs to know if all of variables referenced in the statement, and other statements subsequent can affect it. I band-aid fix would be not offer the "fix" if any of the variables referenced in the statement are used.

Eg. `keys` is referenced between where current temporary and where it is in-lined..

**Comment by Pilchie** [comment]
This is definitely tricky to fix.  So far we've decided that recognizing side effects is something that the user is responsible for.

cc @DustinCampbell

**Comment by DustinCampbell** [comment]
Right. We do our best try to be smart, but side effects are challenging. Additionally, we don't want to stop providing a refactoring because we hear a lot of feedback that people are puzzled when they don't appear for an esoteric reason. I think the right thing to do here is try to detect such cases and mark the conflicts in the preview. We should have the same design principle for Inline Temporary Variable as we do with Inline Rename: Allow the user to refactoring, but do our very best to let them know the consequences.

**Comment by AdamSpeight2008** [comment]
Is it possible to detect a semantic change? So that we could inform the user that the meaning of the code is different.

**Comment by DustinCampbell** [comment]
@AdamSpeight2008 we do detect many semantic changes. However, this is a slippery slope as it is not possible to detect all semantic changes (c.f. the halting problem).

**Comment by CyrusNajmabadi** [comment]
This is by-design.  These are tools to quickly make changes, not ensure preserving exact semantics (indeed, any change will practically always change semantics in some way).  inline-temp *especially* is for use when the user is saying they simply what that initialized value inserted at all reference sites (whether or not that changes semantics).
