### ISSUE TITLE
find all references and navigate to not using caches

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38465]
our code used to work without persistent service and persistent service was an optional component. if persistent service doesn't exist or doesn't work for whatever reason, we used to cache find all reference or go-to index in memory.

this seems changed now and at the same situation, it looks like we don't cache at all and re-calculate everything from scratch every single time.

it might be okay for one-off FAR or go to time to time but when doing that many times, it shows big performance degradation.

the most common case for this is when one opens multiple VS for same solution (same sln file). then 1 VS will use cache and the other VS won't use any cache making second one very slow on these operations.

another case is one doing FAR or go to (SymbolFinder) on MSBuildWorkspace or AdhocWorkspace or any custom Workspace. these workspace will never use persistent service by default. so always get worst performance.

also, it is not possible for them to enable persistent service since it requires location service (to know where to save the persistent file) and that service is internal and can't provided by users.

it would be nice to put back the in memory cache so that people can get in memory cache by default at least.

**Comment by heejaechang** [comment]
it looks like FAR still has an in-memory cache. but it looks like it caches all the time. my memory could be wrong but it used to only cache open file index and one that failed to use persistent service.

now, it just caches everything in memory.  basically FAR has opposite issue compared to navigate to.

...

go to doesn't cache anything if persistent service can't be used.

**Comment by CyrusNajmabadi** [comment]
Can you please tag me in these discussions?  I was heavily involved in these decisions (and all the perf testing around them).  I would def not want things changed without fully validating all the scenarios here.

**Comment by CyrusNajmabadi** [comment]
> this seems changed now and at the same situation, it looks like we don't cache at all and re-calculate everything from scratch every single time.

I can't repro this.  The cache is used and we both persist and load from it for all these features.
