### ISSUE TITLE
Visual Studio Profession 2019 Performance Issue.

### ISSUE THREAD

**Issue by Ultronvision** [dotnet/roslyn#38479]
**Microsoft Visual Studio Profession 2019. Version 16.2.3. Window 10 with Lates updates**: 

**Main Issue**:
I have just opened two projects in two different VS IDE windows. The servicehub.host.clr.x86(32 bit) take 96% of CPU time for a minute and during this time IDE behaves very slow, even IntelliSense are not show the suggestion very slow. I am not sure how to solve this issue, either I have to switch back to VS Community 2017 or what.

**Expected Behavior**:
VS IDE should be smooth and.
**Actual Behavior**:
Very hight cpu utilization and 900 MB of RAM usage.

**Comment by jmarolf** [comment]
Please create a trace so we can investigate. Instructions are [here](https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues#performance-issues)

**Comment by sharwell** [comment]
@Ultronvision Please submit a feedback ticket using the steps above, and it will get investigated by one of the performance teams 👍
