### ISSUE TITLE
[Question] Cannot see C#-roslyn in visual studio 2013, 2015.

### ISSUE THREAD

**Issue by alxest** [dotnet/roslyn#3847]
I tried to follow instructions in [this link](https://github.com/dotnet/roslyn/blob/master/docs/samples/csharp-syntax.pdf).
However, I am stuck in the first instruction in 3rd page. I cannot find "roslyn" under "Visual C#".
I followed installation instructions written [here](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging).
I tried both in visual studio 2015 and 2013.
I tried to find "Roslyn SDK Project Templates" and "Roslyn SDK Syntax Visualizer". I was able to find [this](https://visualstudiogallery.msdn.microsoft.com/e2e07e91-9d0b-4944-ba40-e86bcbec1599) and installed it, but it didn't work.
I also tried "Click here to go online and find templates" inside visual studio - file - new - project, with .NET framework 4.5, with keyword "roslyn", but nothing appeared.

**Comment by dalestone** [comment]
Yeah there doesn't seem to be anything under Visual C# Roslyn, however under Visual C# -> Extensibility there is a Compiler Platform Console Application template which has the following:

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

So you should be able to carry on and test the example in csharp-syntax.pdf

**Comment by alxest** [comment]
@dalestone Thanks for your reply. I checked "Extensibility" tab in 2015 (there isn't one in my 2013) and it was successful. 
FYI: In my VS, there is no "Compiler Platform Console Application", but "Stand-Alone Code Analysis Tool" exists, which gives me almost the same as you wrote.

**Comment by dalestone** [comment]
Yeah it doesn't seem to be supported in 2013.

Ah OK thanks for the info. I am using Visual Studio Community 2015 RC Version 14.0.22823 D14REL just to clarify to anyone reading.
