### ISSUE TITLE
Liveshare FAR requires UI thread

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#38477]
Currently, liveshare FAR requires the UI thread as it calls into the [AbstractFindUsagesService](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/FindUsages/AbstractFindUsagesService.cs,bc260059e380e9ca).  This requires the UI thread to get third party definitions (which in this case means XAML).  We need to remove UI thread dependencies (and editor dependencies) from the liveshare implementation in order to create a proper LSP version of FAR.

Known UI dependencies in FAR
1.  [XAML navigation](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Workspace/VisualStudioSymbolNavigationService.cs,266)
    a.  Service provider
    b.  IVsHierarchy
    c.  IVsSymbolicNavigationNotify
2.  [Invisible editor](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/FindReferences/VisualStudioDefinitionsAndReferencesFactory.cs,66) (find source line)

For 1), we need to work with the XAML team to define a way to provide navigation in the new VS APIs as many of the concepts being used there may go away.

Generally, the approach being considered is to move to the lower level data API SymbolFinder, but we still need to figure out how to handle 1).

**Comment by CyrusNajmabadi** [comment]
> Generally, the approach being considered is to move to the lower level data API SymbolFinder

Please don't do this.

**Comment by allisonchou** [comment]
Resolved by #42854.
