### ISSUE TITLE
Extend Introduce local for expression statement to handle unbounded LHS of assignment expr.

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#38482]
**Steps to Reproduce**:
```csharp
$$unboundedIdentifier = 42;
```

**Expected Behavior**:
Introduce local offered & ->
```csharp
int unboundedIdentifier = 42;
```

**Actual Behavior**:
No refactoring offered as fixed by #38476

**Comment by CyrusNajmabadi** [comment]
This works now:

![image](https://user-images.githubusercontent.com/4564579/218617191-8c41d1f6-667a-4f59-8bee-2249214a01a6.png)
