### ISSUE TITLE
Relaxed ordering for ref this does not check language version

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#38486]
**Version Used**: Roslyn 2.7.0 or newer

**Steps to Reproduce**:

Run the following code:

```c#
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

class Program
{
    static void Main()
    {
        string code = @"
struct S {}

static class Extensions
{
    static void M1(this ref S s) {}
    static void M2(ref this S s) {}
}";

        var tree = SyntaxFactory.ParseSyntaxTree(code, new CSharpParseOptions(LanguageVersion.CSharp7));

        var compilation = CSharpCompilation.Create("a.dll", options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddSyntaxTrees(tree)
            .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

        foreach (var diag in compilation.GetDiagnostics())
            Console.WriteLine(diag.ToString());
    }
}
```

**Expected Behavior**:

Both methods report an error saying that such code is not available in C# 7.0.

**Actual Behavior**:

Only `M2` reports an error:

> (7,20): error CS8107: Feature 'ref extension methods' is not available in C# 7.0. Please use language version 7.2 or greater.

I think this happens because when the ordering of modifiers on `ref` extension methods was relaxed in 2.7.0, a language version check wasn't added for the new syntax.

I think this isn't a serious problem and fixing it would be a breaking change, so this might not be worth fixing, but I thought it was worth reporting anyway.

This behavior was discovered in https://github.com/dotnet/docs/issues/13877.

**Comment by RikkiGibson** [comment]
We would accept a fix for this.

**Comment by gafter** [comment]
Moving to 16.4 because of the compatibility issue.
