### ISSUE TITLE
C# compiler fails to parse is operator with a recursive pattern using type parameters

### ISSUE THREAD

**Issue by GGG-KILLER** [dotnet/roslyn#38485]
**Version Used**: master (31 Aug 2019) on SharpLab

**Steps to Reproduce**:
1.  Create a type with generic type parameters:
```cs
public readonly struct Box<T>
{
    public T Obj { get; }

    public Box(T obj)
    {
        this.Obj = obj;
    }
}
```
2. Attempt to use that type in an `is` expression with recursive pattern matching:
```cs
public static bool RecursiveIsBox<T>(object x)
{
    return x is Box<T> { Obj: T _ };
}
```
3. The following 5 errors are emitted:
```
error CS1525: Invalid expression term '{'
error CS1002: ; expected
error CS1002: ; expected
error CS0305: Using the generic type 'Box<T>' requires 1 type arguments
error CS0119: 'T' is a type, which is not valid in the given context
```

p.s.: SharpLab sample [here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACBcIBMD2AdgDYCeGsCArgMYwYBC+AHgDwAqAfALABQA3nwzCM6DOwwB5YACsM/DAHM4MANwYAvnyEixTZgAoJ+WQEodwwbxE2MMABYBLKADppcgLwYTM1Rc18Wrx8YigAjABsogBMjHxWNqGRGMD4+MQYAJJQ+hycBj5wdBjM5tYiCbbCKADsJRjOjCx5KSwYAGTtrcxusg1Q4hgA+n7lwkE2/klRqekYAEpFVAhQjgBucNm5XAWyRfSl/pVVtfWN25zyUrIgg0OaozZBGkA=)

**Expected Behavior**:
The code is parsed and accepted and works in the same way as if the operations were done separately as in the following code:
```cs
public static bool IsBox<T>(object x)
{
    return x is Box<T> box && box.Obj is T _;
}
```

**Actual Behavior**:
The errors are emitted.

**Comment by RikkiGibson** [comment]
Seems like a dupe of #38121

**Comment by RikkiGibson** [comment]
Compiler version `3.4.0-beta1-19426-03+b18d90790da95b6862def56802fa4249e4868bb4` parses this code correctly. I also tried checking out the commit SharpLab says it's using (b4cad27), and added the example in the issue description as a test. It works there too.

**Comment by GGG-KILLER** [comment]
I am still getting an error when I input the code in sharplab:
![image](https://user-images.githubusercontent.com/5892127/64291177-e72dbd80-cf3d-11e9-9d3f-bfe98ac21b9e.png)

**Comment by RikkiGibson** [comment]
Filed ashmind/sharplab#420. Please let us know if you are able to repro this issue on a recent compiler (e.g. by building from source, or by adding a compiler from [MyGet](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers) to your project)

**Comment by GGG-KILLER** [comment]
Ok, thank you very much for your assistance @RikkiGibson.

I'll be closing this as a duplicate of #38121 then.
