### ISSUE TITLE
Automatic namespace imports break muscle-memory and impedes typing

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#38497]
**Version Used**: 
VS 2019 16.3 Preview 4 (Int Preview)

**Steps to Reproduce**:

1. Set caret inside of a private non-static method
2. Type 'this.'

**Expected Behavior**:

Completion list is displayed with non-static member items of this class.

**Actual Behavior**:

Completion auto-completes to 'CallConvThiscall' and adds a using for `System.Runtime.CompilerServices`.

Auto-importing is nice but IMO needs to be a bit less aggressive. I frequently find myself needing to undo what it did. One obvious case is when the user types a keyword, especially 'this', 'value', etc. These should never be considered for completion/auto-namespace-import or they should be added to the completion list so the keyword is the selected match when the user types a commit character.

**Comment by gundermanc** [comment]
**cc:** @AmadeusW, in case you have any input here.

**Comment by CyrusNajmabadi** [comment]
The situation above is just a plain bug.  Typing 'this' should always prefer a match against 'this' as you type due to it being either a case-sensitive-prefix or 'case-sensitive-exact' match.  That it *ever* preferred CallConvThiscall is just busted.  Maybe some sort of race condition?

Tagging @ivanbasov .

**Comment by ivanbasov** [comment]
@genlu is it the unimported types completion?

**Comment by gundermanc** [comment]
I'm not seeing 'this' in the completion list at all. I think it's selecting CallConvThiscall because it's indeed the closest match in the list. Seems like adding keywords to the completion list might fix the issue.

**Comment by CyrusNajmabadi** [comment]
> Seems like adding keywords to the completion list might fix the issue.

This should be the case.  If you're not seeing keywords in the list, then *that* is the bug.  If you can provide a repro that would be great.

**Comment by ivanbasov** [comment]
@gundermanc could you please share a screenshot?

I could not repro the issue. Here is mine:
![image](https://user-images.githubusercontent.com/5455484/64463178-eb7de600-d0b7-11e9-91b5-faf701d68bff.png)
I have `this` selected.

**Comment by gundermanc** [comment]
Interestingly it's not repro-ing for me anymore. Perhaps there's something I'm missing.

**Comment by CyrusNajmabadi** [comment]
@gundermanc could you perhaps have been in a static member?

**Comment by gundermanc** [comment]
It was a constructor IIRC. Granted, it was in a Razzle project, so perhaps there was something off about the design-time build.

**Comment by CyrusNajmabadi** [comment]
OMG....
OMG.............


Razzle is still in use..............

OMG....

The bad memories you just made me think about again.......

**Comment by CyrusNajmabadi** [comment]
I can't repro this either.  Closing out.
