### ISSUE TITLE
IDE0041 only offers `is null` when there's a cast

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#38506]
**Version Used**: 
3.4.0-beta1-19426-03+b18d90790da95b6862def56802fa4249e4868bb4

**Steps to Reproduce**:
```C#
using System;

class Program
{
    static void Main() { M1(new object()); M2(new object()); }

    static void M1(object obj)
    {
        if ((object)obj == null)
        {
            throw new ArgumentNullException(nameof(obj));
        }
    }

    static void M2(object obj)
    {
        if (obj == null)
        {
            throw new ArgumentNullException(nameof(obj));
        }
    }
}
```

**Expected Behavior**:
IDE0041 offers to "Use 'is null' check" on both M1 and M2.

**Actual Behavior**:
IDE0041 only offers to "Use 'is null' check" in M1.

**Comment by huoyaoyuan** [comment]
Should IDE0041 cover unconstrained T, which will be supported since C# 8?

**Comment by sharwell** [comment]
> Should IDE0041 cover unconstrained T, which will be supported since C# 8? 

Can you give an example here? I'm not sure what scenario it would be covering.

> Can code fix varies based on language version?

Yes, and we have some code fixes already that do this.

**Comment by CyrusNajmabadi** [comment]
I don't mind the idea of offering `is null` instead of `== null` or `is object` instead of `!= null`.  However, this should be through a new feature that users can opt into.  I don't think this option should now have hte effect of complaining about thousands of lines of code that it didn't complain about before.

**Comment by stephentoub** [comment]
I'm happy if it's a separate IDEXXX number or whatever.  What I don't like about the current state of things is that it leaves the code base in an inconsistent state: some checks are done with `is null`, others with `== null`, and VS doesn't offer anything to address that.  It's related to why I dislike `is object` being include in these refactorings, and end up undoing them when IDE0041 is applied globally: `is object` can't be used in all cases `!= null` can be used and thus the code base is inherently inconsistent (the other main reason is it's a "cute" trick I need to think through every time I see it; whereas `is null` is just as clear as `== null`, `is object` isn't anywhere as clear as `!= null`, and I have to think about what it is every time I see it... I wish IDE0041 didn't use it and that I could turn it off.)

**Comment by CyrusNajmabadi** [comment]
The goal was not consistency here.  The code was already inconsistent to begin with in that it used to have a mix of things like `(object)x == null` versus `x == null`.  The only point in tihs particular analyzer was to say "if you're trying to explicitly indicate you want a reference-null test, then here's a better way to do it".  If the code wasn't trying to be explicit about it being reference-null, we don't touch it at all.

> `is object` isn't anywhere as clear as `!= null`

Agreed.  I don't think that change should have been made.  We should instead just do `is not null` once `not` patterns are available.

**Comment by stephentoub** [comment]
> was already inconsistent to begin with in that it used to have a mix of things like (object)x == null versus x == null

Previously we had code like:
```
if ((object)a == null) throw ...;
if (b == null) throw) ...;
if (c == null) throw ...;
```
It's clear why the cast is there for anyone familiar with operators, and trying to make it consistent by adding the casts to the others results in more "this is not needed" warnings.

In contrast, this is inconsistent:
```
if (a is null) throw ...;
if (b == null) throw) ...;
if (c == null) throw ...;
```
and just looks strange, as all of them could use `is`.

**Comment by stephentoub** [comment]
> Agreed. I don't think that change should have been made. We should instead just do is not null once not patterns are available.

Can we remove that, or make it a separate rule number?

**Comment by sharwell** [comment]
> `is object` isn't anywhere as clear as != null, and I have to think about what it is every time I see it... I wish IDE0041 didn't use it and that I could turn it off

`<Features>strict</Features>` isn't officially supported, and `not` patterns do not exist yet. The only two not-null checks that work properly for value types are `!(x is null)` and `x is object`. The latter was chosen for readability.

> `is object` can't be used in all cases `!= null` can be used

Can you give more information about this? Also note that `is null` cannot be used in all cases where `== null` can be used, so I'm especially interested in cases where `is object` is unique. (An example for `is null` would be the `ImmutableArray<T>` handling of `== null`.)

**Comment by stephentoub** [comment]
> Can you give more information about this?

Try using it with pointers.

**Comment by CyrusNajmabadi** [comment]
> In contrast, this is inconsistent:

They look equally inconsistent to me :)  In both cases there is a mix of styles used.  previously it was `cast + == null` and `== null`.  And afterwards it's `is null` and `== null`.  

But i suppose you're saying "previously, it was always `== null` in some form, so there was consistency there".  :)

**Comment by stephentoub** [comment]
> so there was consistency there

Yes. Plus, the former can't be made consistent without new warnings. The latter can.

**Comment by sharwell** [comment]
Design review conclusion:

* The current refactoring was not intended to catch all cases (see https://github.com/dotnet/roslyn/issues/38506#issuecomment-529287573)
* It is not possible for `is null` and `is object` to handle all potential null check scenarios. Each of these has its own unique limitations.

Since consistency is not possible in the current language and the current analyzer is behaving as intended, we decided not to make a change to the current behavior, although we will revisit the behavior if/when a new not-null check syntax becomes available.

**Comment by stephentoub** [comment]
😦

**Comment by stephentoub** [comment]
@sharwell, can this be revisited now that we have `is null` and `is not null`?  Lack of an analyzer / fixer here makes us resort to much less accurate means, e.g. https://github.com/dotnet/runtime/pull/43360.

**Comment by jaredpar** [comment]
> It is not possible for is null and is object to handle all potential null check scenarios.

Can we elaborate a bit on what cases can't be handled here?

**Comment by sharwell** [comment]
> Can we elaborate a bit on what cases can't be handled here?

```csharp
public void Method(ImmutableArray<int> array)
{
  if (array == null)
    throw new ArgumentNullException(nameof(array));
}
```

**Comment by stephentoub** [comment]
That can't be handled because it's fundamentally not a null check. It's a good thing that `is null` and `is not null` don't work for that, IMO, and being consistent on all other checks using `is null`/`is not null` helps to highlight how odd this particular operator== is.

**Comment by CyrusNajmabadi** [comment]
I would be ok with a new setting allow someone to opt into saying they prefer this check over a `==` check.  We can also enable it for a few well known types.  i.e. for strings.

**Comment by jaredpar** [comment]
Agree with @stephentoub. The `is null` check doesn't work here by design. This isn't some case where we have to get into deep language semantics as to when `is` will or won't work. It's a feature that does not work for known value types. There are other examples in the language where this happens.
