### ISSUE TITLE
Automatically comment out a new line when enter is pressed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38516]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/703623/automatically-comment-out-a-new-line-when-enter-is.html)._

---
With the code `string test = "this is a test";` if the cursor is put after &quot;is&quot; and the enter key is pressed, VS maintains the string (ie it changes the code to `string test = "this is" + " a test";` split across both lines). The same should be done with comments. If the comment `//This is a test` exists and the cursor is put after &quot;is&quot; with the enter key pressed, the resulting 2 lines should be

```
//This is
// a test
```
Currently what happens is the comment is broken with the resulting two lines being:

```
//This is
 a test
```

---
#### Jane Wu [MSFT] on 8/22/2019, 02:19 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
Everyone agrees the proposed behavior is desired. Marking **help wanted**.
