### ISSUE TITLE
Generate Local variable outside of current block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38511]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/683584/generate-local-variable-outside-of-current-block.html)._

---
When Quick Actions suggest to create a local variable, when we are in a code block (if, using, etc.) The local variable could be created outside of the block (just before)

This should be a new quick action or replacing the Create Local variable.

Example:

```
using (var db = CreateContext())
{
    blogs = db. Blogs.ToList()
}

```

The quick action is called on blogs

---
### Original Comments
(no comments)

**Comment by CyrusNajmabadi** [comment]
> When Quick Actions suggest to create a local variable, when we are in a code block (if, using, etc.) The local variable could be created outside of the block (just before)

I don't have any reason to believe that would be the preferred behavior.

**Comment by sharwell** [comment]
What about a refactoring on the local variable itself called "lift to containing scope"?

**Comment by CyrusNajmabadi** [comment]
> What about a refactoring on the local variable itself called "lift to containing scope"?

I'd be amenable to that.  *or*, alternatively, say you wrote the following:

![image](https://user-images.githubusercontent.com/4564579/64637978-bde7b400-d3b9-11e9-9a0d-e0a3d2a7c4fc.png)

Having a fix for this that would fixup the declaration to be in scope of the usage might be nice.  I'm a little uncertain of what the primary usecase is for this feature.

**Comment by sharwell** [comment]
Design review conclusion: Will wait for more feedback regarding specific scenarios. A few cases were identified where a user would want to reference newly-defined or existing variables in a broader scope, but it was not clear how often these actions would be used among an already crowded menu.

If this was implemented, several very challenging situations may arise involving multiple variables with the same name, which may or may not have the same (or compatible) types.
