### ISSUE TITLE
Intellisense does not list members for 3th parameter in GroupJoin

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38518]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/705206/intellisense-does-not-list-members-for-3th-paramet.html)._

---
<p>What steps will reproduce the problem?</p><ol><li>Create a linq query and add a GroupJoin in it</li><li>Start typing the content of the 3th parameter</li><li>After typing the “.” the auto complete list appears, but it does not contain the members of the class</li></ol><p>What is the expected output? What do you see instead?<br>
Visual Studio editor should display the list of member for the specified class.</p><p>PS the members of the class ARE listed in the 2nd parameter!</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/89512-vsproblem.png">vsproblem.png</a></p>

---
#### Visual Studio Feedback System on 8/22/2019, 04:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mrdnote** [comment]
Thanks for adding my reported issue!

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  But it's possible i don't understand the issue (and i don't see any attached image).  Could you supply a repro case and a picture?  Thanks!

**Comment by mrdnote** [comment]
Looks like this has been fixed in the current version of VS 2019 and 2022.
![image](https://user-images.githubusercontent.com/5628584/220885685-9ac94345-8a72-49ec-923a-14a630674fba.png)

**Comment by CyrusNajmabadi** [comment]
Closing out then.
