### ISSUE TITLE
Move AdditionalProperty to `Microsoft.VisualStudio.LanguageServices.FindUsages` namespace as this is specific to FAR columns.

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#38528]
This should be moved to `Microsoft.VisualStudio.LanguageServices.FindUsages` namespace as this is specific to FAR columns.

_Originally posted by @mavasani in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzA1MzA5NTEy/timeline/more_items_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
