### ISSUE TITLE
Considerer using async method instead of sync

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38535]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/662304/considerer-using-async-method-instead-of-sync.html)._

---
<p>I would like to suggest a warning or message when a sync method is being used instead of its async version. For example, supposing we have this interface:</p><pre><code>public interface IFoo  {      int DoSomething();      Task&lt;int&gt; DoSomethingAsync(); } </code></pre><p>and in the code we are using the sync version:</p><pre><code>var result = foo. DoSomething(); </code></pre><p>I would like to see a warning/message saying that <code>DoSomething</code> has an async version.<br> This idea came to my mind when I noticed that a service in my company was suffering from thread starvation. <br>After some hours we figured out that a few methods were being called with the sync version instead of async, which was blocking the thread and causing a lot of timeouts.</p>

---
#### Jane Wu [MSFT] on 7/25/2019, 09:48 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This can be done by the customer by supplying their own analyzer to look for this pattern.

**Comment by jaredpar** [comment]
Thanks for the suggestion. Unfortunately adding such a diagnostic would be a breaking change as it would be raised in existing code bases. The compiler does not accept such changes. Customers can enable this type of diagnostic in their applications by authoring an analyzer for this scenario.
