### ISSUE TITLE
Why you can not wrap a select case?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38530]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/692463/why-you-can-not-wrap-a-select-case.html)._

---
Hello,

in vs 2019 you can wrap a if, while etc block but not a select case block. 

Can you please implement these? So you can wrap each case block inside a select case?

Thanks and best regards

---
#### Jane Wu [MSFT] on 8/15/2019, 00:31 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
Can you give an example of the specific request here? I'm having trouble understanding what the desired behavior is. 😄

**Comment by SvendK** [comment]
Hi, I came here from a Google Search, and I guess what Andrey means is the following: 

Here it's hard to see the three cases
```
Select Case line.Type
    Case LineType.ProdLn, LineType.Discount, LineType.AcountingLines
        debtorOrderLines.Add(line.ConvertToDebtorOrderLine(journal, master))
End Select
```

What he (and I) just wanted, was to have linefeeds after each case parameter so they were aligned, like this:
```
Select Case line.Type
    Case LineType.ProdLn, 
         LineType.Discount, 
         LineType.AcountingLines
        debtorOrderLines.Add(line.ConvertToDebtorOrderLine(journal, master))
End Select
```
I guess the problem with allowing this is to see when is it a case parameter and when is it the "body" of the case, the "what to do when hit". But the comma should do it, right?

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this space.
