### ISSUE TITLE
Choose patterns and paradigms while developing code

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#38538]
[Original devcomm feedback](https://developercommunity.visualstudio.com/content/idea/710883/choose-patterns-and-paradigms-while-developing-cod.html)

* Ability to choose a coding paradigm: TDD, DDD, etc.
* Provide Quick Actions/notifications to lead user towards paradigm

Customer Quote:
> It would be great that while creating a new project I could select what type of design or paradigm I would like to keep such as DDD or TDD and then during development some scafolding of the main concepts may happens. On DDD Entity, Event AgregateRoot classes for example. On DDD for example when creating some class the Visual studio could show some hints. if the developer was writing logic methods referencing many times some class a suggestion could pop up saying : “ it looks like this is domain logic to this entity.. if so consider moving this to the class” . Or in another use case. Regarding if a developer choose TDD when any new public or internal method of some class was created... a pop up would say:” you have chosen TDD in this project! You should start with the unit tests! “

(I'm leaving the devcomm feedback open to see if it accumulates votes there.)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
