### ISSUE TITLE
Allow deleting entries in FindXXX dialogs. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38537]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/701847/allow-deleting-entries-in-findxxx-dialogs.html)._

---
Allow deleting entries in FindXXX dialogs such as Find all references / Find callsites, ... 
Usecase: Want to investigate all callsites of some function
- Find all references on method declaration
- Go one by one (from top bottom) checking them (not changing)
- Some of them might require more investigation, get skipped -&gt; no way to mark them / preserve info that one should return to them.

---
#### Jane Wu [MSFT] on 8/21/2019, 04:10 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Petr Houska [MSFT] on 8/26/2019, 05:14 PM: 

E.g. Call hierarchy allow deleting items.

**Comment by CyrusNajmabadi** [comment]
This would be a request for the platform.  @olegtk
