### ISSUE TITLE
Fix and enable VSTHRD100 "Avoid async void methods"

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#38545]
moving to new VS SDK introduced new warning VSTHRD100 abd VSSDK006 which is suppressed for now. @sharwell  want to enable those.

**Comment by heejaechang** [comment]
VSSDK006 is suppressed due to - CheckServicesExistAnalyzer  somethings throw AD0001 exception

**Comment by sharwell** [comment]
I believe VSSDK006 is enabled again by #38472, so updating this title to focus on just VSTHRD100.

**Comment by CyrusNajmabadi** [comment]
Appears to be enabled now:

![image](https://user-images.githubusercontent.com/4564579/152653494-14060b24-2821-4d62-89a8-22b662182422.png)

**Comment by sharwell** [comment]
Still have one location to fix:

https://github.com/dotnet/roslyn/blob/f857c3dac873ac615d4348ca4e273b00597210af/src/VisualStudio/Core/Impl/SolutionExplorer/AnalyzersCommandHandler.cs#L408-L410
