### ISSUE TITLE
Roslyn IDE features exhibiting numerous regressions

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#38559]
**Version Used**: 
Visual Studio 2019 Int Preview 16.4

**Steps to Reproduce**:

1. Open a C# project
2. Type some method name 'Foo'

**Expected Behavior**:
Signature help appears and is classified.

**Actual Behavior**:
Signature help appears unclassified.

![image](https://user-images.githubusercontent.com/5387680/64454691-76eb7d00-d0a0-11e9-8e95-552c33be73b8.png)

**Comment by gundermanc** [comment]
@heejaechang FYI

**Comment by gundermanc** [comment]
Colorization of namespace names is incorrect in latest 16.4 Int Preview:

![image](https://user-images.githubusercontent.com/5387680/64554267-eb682b00-d2ef-11e9-92ac-9b94c0c4d560.png)

**Comment by gundermanc** [comment]
Duplicate outlining regions:
![image](https://user-images.githubusercontent.com/5387680/64554476-57e32a00-d2f0-11e9-9f3a-4412b8de6906.png)

One offers colorized tips:

![image](https://user-images.githubusercontent.com/5387680/64554499-65001900-d2f0-11e9-8712-05f2cfe7a4f2.png)

The other does not, seemingly from TextMate.

![image](https://user-images.githubusercontent.com/5387680/64554516-6f221780-d2f0-11e9-9708-937b368d8937.png)

**Comment by heejaechang** [comment]
@gundermanc I think new intellicode experiment is messing up something that causes text mate to pick up regular C# file as a valid buffer to classify.

what textmate look for as content type it should classify?

**Comment by gundermanc** [comment]
TextMate features light up for anything marked 'code++'. IIRC Extensibility has special content-types for lighting up a language server without turning on TextMate.

**Comment by heejaechang** [comment]
@gundermanc so Roslyn content type is not based on code++ so somebody is injecting that when editor/buffer is created.

can you turn off this and see whether it repro?
![image](https://user-images.githubusercontent.com/1333179/64557478-7815e780-d2f6-11e9-8107-58a0075aabea.png)

we think intellicode or lib it is using is injecting that content type to Roslyn content type.

**Comment by gundermanc** [comment]
Ah, that was the problem

**Comment by vivlimmsft** [comment]
This was caused by IntelliCode using the incorrect content type to activate LSP in C# buffers. We're making a change to use the base content type that only includes LSP functionality, without TextMate.

This feature was activated by targeted notification for users on the Int Preview channel. We turned off the targeted notification, so this should no longer be happening.
