### ISSUE TITLE
Null reference warning when validation expression result relayed as boolean

### ISSUE THREAD

**Issue by JeremyCaney** [dotnet/roslyn#38561]
If I write the following code,
```
public void DoSomething(string value) {
  Console.WriteLine(value.Length);
}
```
I will receive the warning, 
> `CA1062`: In externally visible method `void DoSomething(string value)`, validate parameter `value` is non-null before using it. If appropriate, throw an `ArgumentNullException` when the argument is null or add a Code Contract precondition asserting non-null argument.

Similarly, in a slightly different construction—such as retrieving the value from a function that may result in a `null` value—I may receive:
> `CS8602`: Dereference of a possibly null reference.

This is totally expected; after all, the parameter `value` may well be `null` since `#nullable` doesn't include runtime checking. As the warning suggests, I can easily fix this by adding a guard clause, such as:
```
public void DoSomething(string value) {
  if (value == null) {
    throw new ArgumentNullException(nameof(value));
  }
  Console.WriteLine(value.Length);
}
```
If, however, I store the result of the validation expression (`value == null` in this case) to a `bool` and check that value, I will still get the `CA1062` (or `CS8602`) warning:
```
public void DoSomething(string value) {
  var isInvalid = value == null;
  if (isInvalid) {
    throw new ArgumentNullException(nameof(value));
  }
  Console.WriteLine(value.Length);
}
```
My expectation would be that the previous two code examples would yield the same results. 

This may well be expected based on Roslyn's flow analysis implementation. That said, it limits the methods through which `null` references can be validated. For example, it restricts the use of utility methods that assist in creating guard clauses, similar in _structure_ to Code Contracts:
```
public static void Requires<T>(bool isValid) where T : Exception, new() {
  if (!isValid) {
    throw new T();
  }
}
```
> **Note:** This is obviously a contrived example. A real implementation would be far more sophisticated, accounting for e.g. variable names and/or error messages.

FWIW, the project I'm working on happens to be targeting .NET Standard 2.2, but I wouldn't expect that to be relevant here since I'm just referencing internal code and not .NET Standard libraries.

**Comment by jaredpar** [comment]
> This may well be expected based on Roslyn's flow analysis implementation

This is indeed a limitation of our flow analysis and simultaneously the overall design that C# chose for this feature. At the moment there are no plans to expand the flow analysis to this level. 

> For example, it restricts the use of utility methods that assist in creating guard clauses, similar in structure to Code Contracts:

Not necessarily. There are a host of control attributes that let functions express information about their affect on inputs. For instance a helper function `ThrowIfNull` can be authored that plays into C# flow analysis. Example:

``` csharp
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;
public class C {
    public void M(object? o) {
        ThrowIfNull(o);
        o.ToString();
    }
       
    static void ThrowIfNull<T>([NotNull]T? value) where T : class { } 
}
```

**Comment by cawoodm** [comment]
![Image](https://github.com/user-attachments/assets/e73af176-8811-4b61-8b16-195cae4977d0)
False warning of doublly-validated null value.
