### ISSUE TITLE
Regression: Operator '==' cannot be applied to operands of type 'T' and 'default'

### ISSUE THREAD

**Issue by filipnavara** [dotnet/roslyn#38568]
**Version Used**: 

.NET SDK 5.0.100-alpha1-014075

**Steps to Reproduce**:

1. Get https://github.com/dotnet/performance
2. Run `dotnet run -f netcoreapp5.0 -c Release` from `performance/src/benchmarks/micro/` directory

**Expected Behavior**:

No error.

**Actual Behavior**:

```
corefx/System.Buffers/ArrayPoolTests.cs(44,21): error CS0019: Operator '==' cannot be applied to operands of type 'T' and 'default' [/Users/filipnavara/agent/_work/1/s/work/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
```

Relevant code: 

https://github.com/dotnet/performance/blob/97d49cfc30502b835122d360ca4b93f29215d4cc/src/benchmarks/micro/corefx/System.Buffers/ArrayPoolTests.cs#L39-L47

This worked few hours ago with the latest .NET SDK from git master (as of 06/09/2019, 18:09:56 UTC; reported by BDN as `.NET Core 5.0.0-alpha1.19456.2 (CoreCLR 5.0.19.45509, CoreFX 5.0.19.45516), X64 RyuJIT`). I assume the Roslyn dependency got bumped and introduced some breaking change.

**Comment by filipnavara** [comment]
The only dependency update that fits the time frame: https://github.com/dotnet/core-sdk/pull/4620

**Comment by filipnavara** [comment]
Last known good .NET Core SDK 5.0.100-alpha1-014074. That literally reduces it to single dependency update.

**Comment by yyjdelete** [comment]
You can see #36492 for more infomation.
In fact, it used to work as `item is null` and never works when `T` is `byte`.

**Comment by filipnavara** [comment]
Thanks for the link. Looks like issue in dotnet/performance code then. /cc @adamsitnik
