### ISSUE TITLE
`MSB4062: Assembly with same name is already loaded` when `Microsoft.Net.Compilers.Toolset` is only used for a part of projects in solution

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#38570]
**Version Used**: 
dotnet-sdk: 3.0.100-preview9-014004(Also not work for old versions)
Microsoft.Net.Compilers.Toolset: 3.2.1

**Steps to Reproduce**:

1. Create two csproj, add reference of `Microsoft.Net.Compilers.Toolset` to the first, and add reference of the first to the second, no code is needed.
xxxx.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.2.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
xxxx1.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\xxxx\xxxx.csproj" />
  </ItemGroup>

</Project>
```
2. Try `dotnet build` with the second csproj. (Run `dotnet clean` first if already has an successful build for the first csproj.

**Expected Behavior**:
Build success.

**Actual Behavior**:
> C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\Roslyn\Microsoft.CSharp.Core.targets(59,5): error MSB4062: Failed to get from assembly C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll Load the task "Microsoft.CodeAnalysis.BuildTasks.Csc". Assembly with same name is already loaded Please confirm that the <UsingTask> declaration is correct, the assembly and all its dependencies are available, and the task contains a public class that implements Microsoft.Build.Framework.ITask.

It is something by designed, that must reference the same version of `Microsoft.Net.Compilers.Toolset` for all projects in solution?
An workaround is to use `dotnet build /nodeReuse:false` instead or reference the same version of `Microsoft.Net.Compilers.Toolset` for all projects.

**Comment by jaredpar** [comment]
This behavior is "By Design". The MSBuild nodes on .NET Core can only load a single version of a task assembly. In this situation you've essentially asked MSBuild to load two different versions of the `Csc` Task assembly which it can't do. The NuPkg file must be applied to the whole build or node re-use needs to be disabled. 

Note: MSBuild does have this issue discussing ways to make this type of scenario work. https://github.com/microsoft/msbuild/issues/1754
