### ISSUE TITLE
Consider suppressing the formatter when IDE0055 is suppressed

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#38587]
**Version Used**: 16.3 Preview 3

**Steps to Reproduce**:

Run **Format Document** on a file containing the following:

```csharp
#pragma warning suppress IDE0055 // Fix formatting
int value = new int ( );
#pragma warning suppress IDE0055 // Fix formatting
```

**Expected Behavior**:

The code inside the IDE0055 suppression is not reformatted.

**Actual Behavior**:

The **Format Document** command ignores the IDE0055 suppression, and formats the code anyway.

**Comment by dibarbet** [comment]
Design review outcome - 
1.  The suppression application should be modified in the following ways
     a.  Output `pragma warning suppress format` instead of `pragma warning suppress IDE0055`
     b.  Local / global suppression should not be offered for this case.
     c.  It should no longer say "Fix formatting"
2.  The formatter should respect both `pragma warning suppress format` and `pragma warning suppress IDE0055`
