### ISSUE TITLE
[Feature Request] Display compiler errors inline

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#38589]
This is a screenshot from MonoDevelop:
[Some code with a compiler error](https://cdn.discordapp.com/attachments/169726586931773440/620557050702725140/unknown.png)

There's an error in that code, which squiggles the line. Right next to the line, the error message is drawn (cannot assign void... in this case). This way, i don't need to hover over it or look at the error list.

I'd like to have that feature in VS, please.

**Comment by CyrusNajmabadi** [comment]
Can you show the experience if there are multiple errors ont he same line?   Also, you can include images in-line in github :)

![image](https://user-images.githubusercontent.com/4564579/64565009-ab14a700-d307-11e9-894c-6ef5fce07ba2.png)

**Comment by AdmiralSnyder** [comment]
I don't use MonoDevelop, don't know how multiple issues are handled - i saw the screenshot in chat.
I implemented a initial version of that feature in my [C# var CodeLens extension](https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner)
I just write the errors vertically one after the other if there are more than 1 per line.
Here is a screenshot: 
![ErrorHighlighter](https://user-images.githubusercontent.com/16213022/64573180-ac2af000-d36a-11e9-8ab3-68b9d9cda619.png)

**Comment by AdmiralSnyder** [comment]
hey, so after my c# var codelens extension https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner
has been made obsolete, my other extension, https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.ShowInlineErrors is gonna be obsoleted, too? Time to build something new :-) :-(

**Comment by AdmiralSnyder** [comment]
@akhera99 your screenshots look great ❤️

**Comment by AdmiralSnyder** [comment]
hey @akhera99 did you enable the error display for other languages, too? i changed my extension to be used for "code" (iirc) and it works for c++/JS/F#, that way, too, magically.
