### ISSUE TITLE
WinRT legacy collection tests throwing OOM

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#386]
A number of the LegacCollection tests are throwing OOM on a somewhat random basis.  This has been seen across a number of machines now that have no changes themselves.

**Comment by ManishJayaswal** [comment]
The issue might be in:
 Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.AddModuleData(IEnumerable`1 modules)
	           Src\Test\Utilities\HostedRuntimeEnvironment.cs(89,0):

**Comment by jaredpar** [comment]
I agree.  Having an email thread about this right now.

**Comment by agocke** [comment]
This looks like broader infrastructure to me. I would assign it to the secondary monitor.

**Comment by jaredpar** [comment]
@agocke assign where?

**Comment by MattGertz** [comment]
Needs verification.
