### ISSUE TITLE
[Question] Why I was able to overrid a implemented method with an extension method?

### ISSUE THREAD

**Issue by paule96** [dotnet/roslyn#38607]
Hi corefx Team,

I have a big Question to the following Code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
  public static void Main()
  {
    bla test = new blup();    
    Console.WriteLine(test.Any());
    
  }
}
public class blup: bla{
  public bool Any(){
    return true;
  }
}
public class bla{

}
public static class Extensions{
  public static bool Any(this bla klaus){
    return false;
  }
}
```

The `Console.WriteLine(test.Any())` returns `false`. So the extension method was called. But in the [documentation ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#binding-extension-methods-at-compile-time) about extension methods there is this sentence `You can use extension methods to extend a class or interface, but not to override them.`.
But this is not true for the code above.

The simple answer is, that the IL only knows the static code and not the runtime values. So with the explicit casting in the line `bla test = new blup();` to `bla` the IL think the extension method is the right thing. 
But this is maybe a big problem. In my real case, I have a class that inherited from `IEnumerable` and tries to override extension methods like `Any`. But like in the sample above that wouldn't work in a function that wants an `IEnumerable` as input like this:

```csharp
public void sample(IEnumerable<supertype> source)
```
In this method, always the extension method for `IEnumerable` is preferred. Because at compile time you can't know the real type.

So now to the question:

Is this behavior by design or is this a bug?

And question number 2:

How I can override the extension methods of IEnumerable for my type so all functions in the framework use my implementations?

**Comment by paule96** [comment]
Okay so my understanding was basicly right. So I try another thing:

```csharp
public static class Extensions
    {
        public static bool Any<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
        {
            if(source.GetType().IsGenericType && source.GetType().GetGenericTypeDefinition() == typeof(TypeThatInheridFromIEnumerable<>))
            {
                var realtype = source.GetType();
                var test = realtype.GetMethod("Any").Invoke(source, new object[] { predicate });
                return (bool)test;
            }
            else
            {
                return System.Linq.Enumerable.Any(source, predicate);
            }                                                        
        }
    }
```

But this is also not a good idea because for my calls in my code it works fine. But somewhere in the framework my extension method isn't used. So that is also not the solution.

**Comment by gafter** [comment]
@paule96 You are correct.  I think your question about the language is answered?

**Comment by paule96** [comment]
Yes more or less.
There is spawned a new question. How to override extension methods. But the answer is also: you can't. 

Because all the references of your project are all ready compiled. 🤷‍♀️

So if this sentence is write we can close the issue. 

> maybe we should start a issue on the docs page, to add a warning about this behavior.
