### ISSUE TITLE
Provide an option to auto fill switch cases based on switch parameter

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38633]
Customer Request Copying Here

>Provide an option to auto fill switch cases based on switch parameter.

**Comment by CyrusNajmabadi** [comment]
We  have that:

![image](https://user-images.githubusercontent.com/4564579/64722470-644bbc00-d483-11e9-96d1-a8b15acf26cb.png)

**Comment by mikadumont** [comment]
Thanks, I will go ahead and close this.

**Comment by CyrusNajmabadi** [comment]
You're welcome! :)
