### ISSUE TITLE
Change field type

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38634]
Customer Request Copying Here

>Propose to change field type of the field or parameter: 

![image](https://user-images.githubusercontent.com/46729679/64722870-29965380-d484-11e9-9b2f-9d835d4c42eb.png)

**Comment by CyrusNajmabadi** [comment]
Yes.  We should def get htis.  As well as "add a cast" if one exists.

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
