### ISSUE TITLE
Complete a catch with default exception and braces

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#38631]
Customer Request Copying Here

>Complete a catch with default exception and braces. Today only fill out the catch keyword.

**Comment by jinujoseph** [comment]
**Design Meeting Notes**

We believe the customers are asking for "snippet support for Catch"
we have snippet for try catch and try catch finally but no support for catch today

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and investment in snippet expeirences.
