### ISSUE TITLE
Add an API to construct an IArrayTypeSymbol or an IPointerTypeSymbol from an ITypeSymbol

### ISSUE THREAD

**Issue by fschmied** [dotnet/roslyn#3863]
To produce a constructed generic type symbol from a basic type symbol, the `INamedTypeSymbol` interface has a `Construct` method. However, there doesn't seem to be an API to make an array or pointer type from an `ITypeSymbol` (or `INamedTypeSymbol`).

Please add one.

Use case: When writing a refactoring or code generator using the Roslyn API, one can use `IAssemblySymbol.GetTypeByMetadataName` to retrieve a type from an assembly using its full name. That API naturally only supports basic types, it does not support retrieving constructed generics, array types, pointer types, etc. If the refactoring or code generator needs to use a symbol representing a certain array type, there doesn't seem to be a public way to get that.

**Comment by kzu** [comment]
This should be closed, since it can be done now directly from the Compilation:

![image](https://user-images.githubusercontent.com/169707/62430760-24acea00-b6f7-11e9-9c30-427c2e32b87d.png)
