### ISSUE TITLE
3.4.0 Compiler Toolset does not allow comparing to "default"

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#38643]
**Version Used**: 
Microsoft.Net.Compilers.Toolset v3.4.0-beta1-19456-03

**Steps to Reproduce**:

1. Create a new console app with

```C#
class Program
{
    static void Main(string[] args)
    {
        var x = new object();
        if (x != default)
        {
            Console.WriteLine("Hello world");
        }
    }
}
```

2. Reference the 3.4.0 toolset package

```xml
 <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset"
        Version="3.4.0-beta1-19456-03"
        PrivateAssets="all"/>
  </ItemGroup>
```

3. Compile and see the failure

Program.cs(10,17): error CS0019: Operator '!=' cannot be applied to operands of type 'object' and 'default' 

This compiles using `Microsoft (R) Visual C# Compiler version 3.4.0-beta1-19417-02 (64f75cda)` that's shipped with a SDK, but not using `Microsoft (R) Visual C# Compiler version 3.4.0-beta1-19456-03 
(3c865821)`

**Comment by jcouv** [comment]
This is an intentional breaking change in Roslyn 3.4. See bullet (3) in https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md

**Comment by pranavkm** [comment]
Thanks @jcouv. We noticed this in AspNetCore when maestro picked up a new version of the compiler. It was a fairly small change to fix it - https://github.com/aspnet/AspNetCore/pull/13548/commits/67d8cd9e85e922a5727bb853501937403ff0132a, but I wanted to make sure it wasn't accidental.

**Comment by jcouv** [comment]
Re-opening as we got much feedback on this part of the compat break.
