### ISSUE TITLE
IntroduceLocal should not be offered on a local declaration

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#38644]
Repro:
1. put the cursor on the local name in a local declaration
2. invoke the lightbulb

I expect InlineTemporary rather than IntroduceLocal, but IntroduceLocal is offered and it is at the top.
We could either not offer IntroduceLocal in that scenario, or at least bump it down.

**Comment by CyrusNajmabadi** [comment]
Not seeing this:

![image](https://user-images.githubusercontent.com/4564579/76272469-bace6300-6238-11ea-9516-2a651aaef2aa.png)

@jcouv can you clarify if this is still a problem?

**Comment by jcouv** [comment]
Local declaration ‘int $$i =!1;”.
Not local function...

**Comment by jcouv** [comment]
Here's a screenshot of this issue. I run into it regularly.

![image](https://user-images.githubusercontent.com/12466233/78096675-18b11f00-738f-11ea-8ce1-6edc7138505a.png)

**Comment by CyrusNajmabadi** [comment]
Ah thanks.  Agreed :)

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is expected.  The idea here is that we're offering to introduce a constant for you here.  This is important for the case where someone does a bunch of `int i = magic_value` in a bunch of places.  This allows extracting that magic value to a constant somewhere (and updating all cases where that is used).
