### ISSUE TITLE
Containing Type and Containing Member in FAR are unknown in F# projects

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#38651]
**Version Used**: 
Master 29311.136 + Vsix from (InternalServer)\ContainingMemberAndContainingTypeColumns 
**Steps to Reproduce**:

1. Create a new F# Console App (.NET Core)
2. Right click argv
3. Select Find all references

**Expected Behavior**:
References are shown with all info
**Actual Behavior**:
Containing type and member are set as unknown

![image](https://user-images.githubusercontent.com/10537189/64743406-a8a38000-d4b4-11e9-856b-6d9e8a54c327.png)

**Comment by chborl** [comment]
Fixed in original PR https://github.com/dotnet/roslyn/pull/37802
