### ISSUE TITLE
I hate the error highlighting on a case fallthrough error

### ISSUE THREAD

**Issue by tuespetre** [dotnet/roslyn#38665]
Dear d(otnet💻|iary📔), I hate the error highlighting on a `case` fallthrough error. It indicates to me that something is wrong with the pattern I have specified rather than a `case` fallthrough issue. I would much rather see a highlight on the `case` keyword to indicate that something is wrong with the `case` mechanism itself as opposed to the pattern used to select it. Maybe we all have an error highlighting system that we have to learn to steer in order to flourish. 🤔

**Comment by JoeRobich** [comment]
Hi @tuespetre, Could you include a screenshot in your description that demonstrates the issue you describe and how you would like to change it? Thanks!

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/43005

**Comment by tuespetre** [comment]
nice, thanks!
