### ISSUE TITLE
Broken Links on Building Testing and Debugging Wiki Page

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/roslyn#38697]
On https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging the following links are broken:

![image](https://user-images.githubusercontent.com/14079228/64913314-9e2ef380-d70b-11e9-8d9c-7f5d5a554008.png)

Happy to submit a PR to fix but I don't know where they're supposed to point to 😀

**Comment by johnallers** [comment]
Doesn't seem like this is an issue anymore now that the wiki has been moved to the docs folder (#41157).

**Comment by spottedmahn** [comment]
>Doesn't seem like this is an issue anymore

Great!

>The wiki has been moved to the docs folder

New wiki page location: https://github.com/dotnet/roslyn/blob/master/docs/wiki/Building-Testing-and-Debugging.md

Works, thanks!
