### ISSUE TITLE
Nullable directive changes not considered top level edit

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#38694]
**Version Used**: 16.4 P1 (29312.127 master)

**Steps to Reproduce**:
Create two files in a .net core 3 project
Class1.cs
```cs
namespace ConsoleApp12
{
    class Class1
    {
        public static void SomeMethod(string someString)
        {

        }
    }
}
```
Program.cs
```cs
#nullable enable

namespace ConsoleApp12
{
    class Program
    {
        static void Main(string[] args)
        {
            string? someString = null;
            Class1.SomeMethod(someString);
        }
    }
}
```

Add `#nullable enable` to Class1.cs
Go back to Program.cs and note that there is no warning on calling Class1.SomeMethod(someString) may be null.

Make an edit to anywhere in Program.cs and note that the warning appears after the edit.

**Expected Behavior**:
The warning should appear without needing to make an edit in Program.cs

Through debugging, it appears that the nullable edit is [not being considered a top level edit](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/DocumentState.cs,283).  Since the nullable annotation is trivia, `SyntaxTree.IsEquivalentTo` is returning that the trees are equivalent.

**Comment by RikkiGibson** [comment]
It might be more clear to title this issue "Nullable directive changes not considered top level edit".

**Comment by jcouv** [comment]
Tagging @ryzngard I'm not familiar with the notion of top-level edit. Could you take a look?

**Comment by gafter** [comment]
I'm removing the Compiler tag here so that it is clear who will be doing the investigation.  If the IDE team wants to involve the Compiler team, please do so explicitly.

**Comment by jasonmalinowski** [comment]
Explicitly adding compiler: the IDE calls SyntaxTree.IsEquivalent, which answers if two trees are equivalent modulo trivia. Per the docs:

> If true then the trees are equivalent if the contained nodes and tokens declaring metadata visible symbolic information are equivalent, ignoring any differences of nodes inside method bodies or initializer expressions, otherwise all nodes and tokens must be equivalent. 

It seems this API is not correctly handling updates to nullable trivia which most definitely changes "metadata visible symbolic information".

**Comment by jasonmalinowski** [comment]
And @333fred @jaredpar this isn't a great IDE experience here so we would probably want this fixed for 16.4.

**Comment by RikkiGibson** [comment]
So if SyntaxTree.IsEquivalent were updated to understand that changes to `#nullable` directives make the trees non-equivalent, we would just start doing the right thing in this scenario?

**Comment by gafter** [comment]
@RikkiGibson Yes, probably so.
