### ISSUE TITLE
The compiler produces code with useless redundant instructions for `(X, Y) = (x, y)`

### ISSUE THREAD

**Issue by Konard** [dotnet/roslyn#38702]
**Version Used**: Visual Studio 2019 (16.2.5), dotnet SDK v2.2.402

**Steps to Reproduce**:

1. `dotnet new console`
2. Create `Point.cs` file with `Point` class from [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#deconstruction)
3. `dotnet build -c Release`
4. Open the compiled DLL in the ILSpy and inspect `Point` class constructor.

**Expected Behavior**: The compiler will produce short and efficient code

**Actual Behavior**: The compiler produces code with useless redundant instructions

The code of example from documentation:
```
public class Point
{
    public int X { get; set; }
    public int Y { get; set; }

    public Point(int x, int y) => (X, Y) = (x, y);
}
```

The constructor compiles to:
```
.method public hidebysig specialname rtspecialname 
	instance void .ctor (
		int32 x,
		int32 y
	) cil managed 
{
	// Method begins at RVA 0x2074
	// Code size 29 (0x1d)
	.maxstack 3
	.locals init (
		[0] int32,
		[1] int32,
		[2] int32
	)

	IL_0000: ldarg.0
	IL_0001: call instance void [System.Runtime]System.Object::.ctor()
	IL_0006: ldarg.1
	IL_0007: stloc.0
	IL_0008: ldarg.2
	IL_0009: stloc.1
	IL_000a: ldarg.0
	IL_000b: ldloc.0
	IL_000c: dup
	IL_000d: stloc.2
	IL_000e: call instance void RoslynBug.Point::set_X(int32)
	IL_0013: ldarg.0
	IL_0014: ldloc.1
	IL_0015: dup
	IL_0016: stloc.2
	IL_0017: call instance void RoslynBug.Point::set_Y(int32)
	IL_001c: ret
} // end of method Point::.ctor
```
This is equivalent of:
```
public Point(int x, int y)
{
	int num2 = X = x;
	num2 = (Y = y);
}
```

But I was expected to get a result similar to this:
```
public Point(int x, int y)
{
    X = x;
    Y = y;
}
```
Which compiles to a shorter (and I assume more efficient code):
```
.method public hidebysig specialname rtspecialname 
	instance void .ctor (
		int32 x,
		int32 y
	) cil managed 
{
	// Method begins at RVA 0x2072
	// Code size 21 (0x15)
	.maxstack 8

	IL_0000: ldarg.0
	IL_0001: call instance void [System.Runtime]System.Object::.ctor()
	IL_0006: ldarg.0
	IL_0007: ldarg.1
	IL_0008: call instance void RoslynBug.Point::set_X(int32)
	IL_000d: ldarg.0
	IL_000e: ldarg.2
	IL_000f: call instance void RoslynBug.Point::set_Y(int32)
	IL_0014: ret
} // end of method Point::.ctor
```

The complete example is here: https://github.com/Konard/RoslynBug

**Comment by RikkiGibson** [comment]
Is this built in release mode?

**Comment by Konard** [comment]
@RikkiGibson I updated the IL code, it is now in release mode, was in debug mode. The issue persists.

**Comment by RikkiGibson** [comment]
In these kinds of samples, it's good to also test a user-defined struct type with a few fields in it, since the JIT is not able to do as many optimizations in that scenario.
