### ISSUE TITLE
"Go to base" on override says "The symbol has no base"

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#38700]
**Version Used**: Version 16.4.0 Preview 2.0 [29315.5.master]

**Steps to Reproduce**:

```c#
class F
{
    public override string ToString() // caret on ToString here
    {
        return base.ToString();
    }
}
```

With the caret on `ToString` in the method signature, invoke "Go to base". 

**Expected Behavior**:

Does the same as "Go to definition" on `base.ToString()` call (i.e. MAS).

**Actual Behavior**:

Dialog appears saying:

> The symbol has no base.

**Comment by ivanbasov** [comment]
@drewnoakes Why `Go to base` should do the same as `Go to definition` if it cannot do the right thing?
We already have `Go to definition` for the purpose. I think `Go to base` should not contain the self method but only overridden methods from inherited classes and implemented methods from interfaces.

**Comment by drewnoakes** [comment]
@ivanbasov my belief is that "Go to base" should be able to navigate to the base in cases where "Go to definition" of that base can also navigate.

In the above example, I want to go the definition of an overridden method from the definition of that override. With the caret on the overriding method's name, I should be able to go to the base symbol regardless of whether it's defined in my project or not.

For example:

```c#
class B : LibraryType
{
    override void M() {}
}

**Comment by ivanbasov** [comment]
Thank you for explanations, @drewnoakes ! It seems that I misread your original question. Sorry!

We actually attempt to show the base for external classes here: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/FindSymbols/SymbolFinder.cs#L167

It seems that it misses navigating out of project files which is available here:
https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs#L108

We need to extend SymbolFinder to properly support Metadata symbols.
