### ISSUE TITLE
Show Parameter Info should show the target type of an assignment

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#38707]
**Version Used**: 16.3-preview3

This is a feature request. It feels RHS of assignments would be easier to write if I could see what type of thing is expected to be assigned. It's possible that this is already available via a different command, or that this has been considered and rejected before. Please let me know if that's the case.

```cs
class C
{
    string Prop { get; set; }
    void M()
    {
         // ctrl+shift+space here should show me the type of the assignment target (string)
        Prop = [||];
    }
}
```

This might actually just amount to adding a command which when used on the RHS of an assignment, shows quick info for the LHS expression symbol.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
