### ISSUE TITLE
Add an analyzer, codefix for organize imports

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#38716]
This came up during the design review for https://github.com/dotnet/roslyn/pull/38593

I'd like the ability to have an analyzer to report on unorganized imports with a code fix to automatically sort the usings.  Ideally the severity could be configured by editor config as well and used by fix all.

This will prevent comments like [this ](https://github.com/dotnet/roslyn/pull/38410#discussion_r320898797) from occurring so often :) as the sorting would be enforced automatically.

We should of course share the implementation of the code fix with the current sort usings command.

**Comment by airbreather** [comment]
FWIW StyleCop.Analyzers has a version of this:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/045aba1fa6acad3959a1329521958cc5ca5abfe1/StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1210UsingDirectivesMustBeOrderedAlphabeticallyByNamespace.cs

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/045aba1fa6acad3959a1329521958cc5ca5abfe1/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/OrderingRules/UsingCodeFixProvider.cs

**Comment by CyrusNajmabadi** [comment]
Closinng out as speculative.
