### ISSUE TITLE
正在下载用于nuget.org的intellisense index-Downloading intellisense index for nuget.org

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38717]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/576978/正在下载用于nugetorg的intellisense-index.html)._

---
<p>VSF_TYPE_MARKDOWNDownloading the IntelliSense index for nuget.org is running all the time, unable to debug the program, prompt to install the Android SDK when debugging the program</p>

---
#### Visual Studio Feedback System on 5/22/2019, 00:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### 冰尘 on 5/23/2019, 07:54 AM: 

I has this problem too. This prolbem was found since VisualStudio2019 upgrade to v16.1.0
#### Visual Studio Feedback System on 5/24/2019, 11:30 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

#### Eduardo Gasparoto Semprebon on 5/28/2019, 05:31 AM: 

<p>Same issue here, using 16.1.1.</p><p>Already tried to clear the solution, deleted the .vs folder... Nothing</p>

#### jim liu on 6/2/2019, 00:02 AM: 

I repair the installation solved this  issue.
#### 彬彬 廖 on 6/11/2019, 05:26 PM: 

<p>I repair the installation, and still can't solve this issue.</p><p>my computer works in offline mode.</p>

#### Mayuresh Sawardekar on 6/18/2019, 08:40 AM: 

<p>Any update on the issue above ? Even repairing the installation did not help.</p>

#### Cagri (Charlie) Aslan [MSFT] on 6/18/2019, 11:35 AM: 

<p>Thanks for the feedback. Is it possible for you to use the 'record' functionality in the 'send feedback' tool and capture VS when it is having the problem? It will get us perf traces that should let us figure out what's going on. Thanks!</p>

#### Mayuresh Sawardekar on 6/18/2019, 01:27 PM: 

Hopefully the video comes through. Thanks
#### David Roth on 6/18/2019, 00:33 PM: 

<p>After upgrading to 16.1.3 yesterday, I do not see this issue anymore</p>

#### Mayuresh Sawardekar on 6/18/2019, 00:44 PM: 

<p>I am on VS 2019 v16.1.3 . I am not able to see "record functionality" in "send feedback". All I see is "Report a problem" and "Suggest a feature"</p>

#### Cagri (Charlie) Aslan [MSFT] on 6/18/2019, 00:46 PM: 

<p>This might help: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019</a></p>

#### Mayuresh Sawardekar on 6/18/2019, 01:31 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/480/140a11e6-f6dc-4ab9-96df-c5c26b5dd5e1.html" nodeid="480">@Cagri (Charlie) Aslan [MSFT]</a> : I did send over the VS capture via the "send feedback" tool. Hopefully it came through.</p>

#### Cagri (Charlie) Aslan [MSFT] on 6/18/2019, 01:43 PM: 

<p>It says it is still uploading. I'll check again in a couple of hours. Thanks!</p>

#### Mayuresh Sawardekar on 6/19/2019, 06:25 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/480/140a11e6-f6dc-4ab9-96df-c5c26b5dd5e1.html" nodeid="480">@Cagri (Charlie) Aslan [MSFT]</a>  Any update on it yet ?</p>

#### 419830883 on 6/26/2019, 08:30 PM: 

<p>In 16.1.4,this problem still exists.Is there any solution?</p>

#### 刘涛 on 6/26/2019, 08:37 PM: 

<p>我目前的解决办法是通过Android Studio 中Android Sdk tool 下载对应的SDK与工具 到C:\Program Files (x86)\Android\android-sdk暂时解决的,</p><p>关于Bug修复进度Allen在帮忙跟进</p><p>https://developercommunity.visualstudio.com/content/problem/600284/xamarinandroid-sdk-manager-offline-mode-after-upgr.html</p><p>Translated from Bing:</p><p>My current solution is to download the corresponding SDK and tools from Android Sdk tool in Android Studio to C:\Program Files (x86)\Android\android-sdk for temporary solution.</p><p>Allen is helping to follow up on the bug fix progress</p><p>Https://developercommunity.visualstudio.com/content/problem/600284/xamarinandroid-sdk-manager-offline-mode-after-upgr.html</p>

#### Eduardo Gasparoto Semprebon on 6/27/2019, 01:07 AM: 

<p>Still same issue in 16.1.4. I don't have Android SDK in the machine.</p>

#### Mayuresh Sawardekar on 6/27/2019, 04:50 AM: 

<p>I too dont have Android SDK in the machine. Help needed to resolve this issue.</p>

#### John Burke on 6/28/2019, 11:40 AM: 

<p>I am having the issue as well.  Upgraded to 16.1.4 and it still exists.  Anything I can do to workaround?</p>

#### 419830883 on 7/9/2019, 08:44 PM: 

<p>This issue has been solved in 16.1.6,thanks for everyone!</p>

#### John Burke on 7/11/2019, 10:56 AM: 

<p>I upgraded to 16.1.6 and it is not fixed.  Still getting the message.</p>

#### Ray on 8/23/2019, 01:55 AM: 

It's now 16.2.3 and.... you guessed it: issue is still here!  <br><br>Removed nuget.org from VS.NET setting and solution settings, restarted several times, reinstalled VS.NET, told my mum about it...  and it just refuses to move on like a bad date. <br><br>Thankfully I don't have OCD otherwise this would drive me crazy
#### zebal on 9/13/2019, 05:23 AM: 

<p>I have the same issue, VS 16.2.5</p><p>Fresh installed system and VS.</p><p>"Downloading intellisense index for nuget.org"</p><p>Firewall is open.</p><p>This should be fixed, what information do you need?</p>

#### Rob Relyea [MSFT] on 9/13/2019, 03:42 PM: 

<p>No idea which component is trying to download some intellisense index from <a target='_blank' href="http://nuget.org">nuget.org</a>.<br>
I strongly believe this is not the NuGet team trying to do this.</p>
<p>It would be interesting to figure out who might be downloading an intellisense index via <a target='_blank' href="http://nuget.org">nuget.org</a>.<br>
Which component of VS? Which workload are you running?</p>
<p>Does this only happen when you have a solution loaded?<br>
Etc…</p>
<p>-Rob Relyea<br>
NuGet Team.</p>

#### Ge Ge on 9/13/2019, 11:08 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/1707/fd314950-9f6e-4bf9-90a0-982362e25620.html" nodeid="1707">@Rob Relyea [MSFT]</a> "Downloading intellisense index for nuget.org" will only show in the Background Task button (in the bottom left of the screen). And yes, it seems only happen when having a solution loaded.</p><p><strong></strong><u></u><sub></sub><sup></sup></p><p>My solution:</p><p>1. Use VPN to finish the download.</p><p>2. If it doesn't work, go to Options &gt; NuGet Package Manager &gt; Package Sources, and delete "nuget.org" item (back up the info if you want). Restart VS 2019, problem solved. And then you can add the "nuget.org" back.</p><p>At least works for me :P</p>

#### zebal on 9/14/2019, 05:20 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/1707/fd314950-9f6e-4bf9-90a0-982362e25620.html" nodeid="1707">@Rob Relyea [MSFT]</a></p><p>It's a background task in VS usually starting together with intellisense (that is when intellisense is doing parsing job on load of solution). and so far only when loading Unreal Engine 4 project.</p><p>It happens randomly, sometime yes sometimes not, I usually restart VS to get rid of it thanks to to its randomness.</p><p>I tried to reproduce the issue why recording my system with perfview but the problem didn't occur :(</p><p>I also tried the suggestion to remove and re-add nuget.org link in options, but can't tell if that solved the issue, it's too early to conclude, I'm sure this background task will come back once, and if so I'll record system and send you pefview logs.</p>

#### Visual Studio Feedback System on 9/14/2019, 01:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Ge Ge solved on 7/25/2019, 09:04 PM, 0 votes: 

<p>Use VPN to finish the download.</p><p>If it doesn't work, go to Options &gt; NuGet Package Manager &gt; Package Sources, and delete "nuget.org" item (make a screen shot if you want). Restart VS 2019, problem solved. And then it won't start donwloading any more if you add the "nuget.org" back.</p>

#### 419830883 solved on 7/9/2019, 08:43 PM, -3 votes: 

<p>This issue has been solved in 16.1.6,thanks for everyone!</p>

**Comment by sharwell** [comment]
📝 The investigation for this issue was limited to _only_ the case of the "Downloading IntelliSense Index" message. Debugging scenarios are not related to this message, and are not being covered by this issue. If you are experiencing a debugging problem, please file a new feedback with the details even if you are seeing the "Downloading IntelliSense Index" message.

**Comment by CyrusNajmabadi** [comment]
@sharwell "Downloading IntelliSense index" is only ever reported in this single place:

```c#
                    var title = string.Format(EditorFeaturesWpfResources.Downloading_IntelliSense_index_for_0, _source);
                    await _service._progressService.OnDownloadFullDatabaseStartedAsync(title).ConfigureAwait(false);
```

This is specifically in the following try/catch:

```c#
                try
                {
                    var title = string.Format(EditorFeaturesWpfResources.Downloading_IntelliSense_index_for_0, _source);
                    await _service._progressService.OnDownloadFullDatabaseStartedAsync(title).ConfigureAwait(false);

                    var (succeeded, delay) = await DownloadFullDatabaseWorkerAsync().ConfigureAwait(false);
                    if (succeeded)
                    {
                        await _service._progressService.OnDownloadFullDatabaseSucceededAsync().ConfigureAwait(false);
                    }
                    else
                    {
                        await _service._progressService.OnDownloadFullDatabaseFailedAsync(
                            EditorFeaturesWpfResources.Downloading_index_failed).ConfigureAwait(false);
                    }

                    return delay;
                }
                catch (OperationCanceledException)
                {
                    await _service._progressService.OnDownloadFullDatabaseCanceledAsync().ConfigureAwait(false);
                    throw;
                }
                catch (Exception e)
                {
                    var message = string.Format(
                        EditorFeaturesWpfResources.Downloading_index_failed_0,
                        "\r\n" + e.ToString());
                    await _service._progressService.OnDownloadFullDatabaseFailedAsync(message).ConfigureAwait(false);
                    throw;
                }
```

So, regardless of what happens (completion/cancellation/error) we should always be getting a message to one of:

OnDownloadFullDatabaseSucceededAsync,
OnDownloadFullDatabaseFailedAsync,
OnDownloadFullDatabaseCanceledAsync

These then bottom out in https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/SymbolSearch/VisualStudioSymbolSearchService.ProgressService.cs#L82 where we should always be setting the TaskCompletionSource for the task-center task appropriately.

The only thing i can think of that would ever keep "Downloading_IntelliSense_index_for_0" in the task-center UI perpetually would be if we literally were making no progress downloading hte index.  i.e. if the call to `Microsoft.VisualStudio.RemoteControl.RemoteControlClient.ReadFileAsync` literally was just taking forever.

**Comment by JohnyL** [comment]
VS 2019 16.4.0 Preview - the problem *still* exists.

**Comment by sharwell** [comment]
It looks like the background notification shows even when the download operation is waiting for future retry. Perhaps we should only show the message during the actual download operation?

Also, I'm wondering if a workaround would be disabling completion suggestions from NuGet packages:

![image](https://user-images.githubusercontent.com/1408396/67264707-b7406800-f460-11e9-9ba5-d09e5152e536.png)

**Comment by WrongBit** [comment]
@sharwell : good point, but didn't help. In VS team settings are living separate life from real code - nobody care. And yes, PROBLEM STILL EXIST! I'm tired of that girlish animation with the one useless task "download hell knows what I don't use".

**Comment by CyrusNajmabadi** [comment]
It's likely something has crashed somewhere.  So the task is never completing.  More data will need to be collected to determine what is happening here.

**Comment by asymmetricblue** [comment]
I encountered this today in 16.3.1, I could not open a specific solution without it going into a non-responsive state. Opening VS without opening a project was fine.

I normally operate disconnected from the Internet with a local nuget source configured.

I was able to work around it by setting Enabled=0 in HKCU\SOFTWARE\Microsoft\VisualStudio\16.0_hhhhhhhh\Roslyn\Features\SymbolSearch as suggested by one of the users in the original dev community ticket.

**Comment by JohnyL** [comment]
VS 16.4.0 - the problem still exists. None of suggestions did work.

**Comment by LuohuaRain** [comment]
I have the same problem too, vs 16.4.0

**Comment by mkamoski** [comment]
FYI, in Vs Pro 16.4.2 the problem persists.

-- Mark Kamoski

**Comment by Krazysdaki** [comment]
16.4.5 Still.

**Comment by meesii** [comment]
16.5.2 Still.

**Comment by altimumdelta** [comment]
Yeah I still have 16.3.10 on a physically-remote PC (occasional network) and it keeps trying to download Intellisense Index for Nuget.org and never completes it just keeps going forever, but I only do minor C# stuff there so I had no problems with my work.

**Comment by altimumdelta** [comment]
I have the same thing too. Keeps trying, never finishes ... it keeps the background activity icon to constantly animate and because it never ends it breaks the purpose of that as well.

**Comment by Bosch-Eli-Black** [comment]
I've disabled the "Suggest usings for types in NuGet packages" setting and also removed nuget.org from the Package Sources list, but I'm still seeing this message.

Should VS still be trying to reach out to nuget.org even if it's not in the Package Sources list? That is, can the IntelliSense index be downloaded from places other than nuget.org?

**Comment by sharwell** [comment]
@Bosch-Eli-Black It turns out the "Suggest usings for types in .NET Framework assemblies" feature also uses this index. Can you try disabling _both_ of these options and see if it resolves the message?

**Comment by Bosch-Eli-Black** [comment]
@sharwell Ah, I see! I've now tried turning off both the "Suggest usings for types in NuGet packages" and "Suggest usings for types in .NET Framework assemblies" settings, and that seems to have fixed the issue!

Is there anything information that I can provide that might help with fixing this issue? I'm thinking that in my case, the problem is probably being caused by the fact that I'm behind a proxy.

**Comment by Otiel** [comment]
It seems that there are two existing workarounds:
* Set the registry key `Enabled = 0` in `HKCU\SOFTWARE\Microsoft\VisualStudio\16.0_xxxxxxxx\Roslyn\Features\SymbolSearch` (and create if it doesn't exist).
* Or, disable the following in VS settings:
  * Suggest usings for types in .NET Framework assemblies
  * Suggest usings for types in NuGet packages

![image](https://user-images.githubusercontent.com/3851902/88171400-8c698700-cc1f-11ea-8838-c5d0a4ea8112.png)

The question is: do both methods accomplish the same thing? What is really disabled when modifying the registry key?

**Comment by CyrusNajmabadi** [comment]
> The question is: do both methods accomplish the same thing?

THey do not.  While they both download and use the same index, the option determines which features the index powers.  The first will offer to add reference to well known MS .net framework assemblies.  The second will offer to add nuget references to popular nuget packages.

**Comment by Otiel** [comment]
@CyrusNajmabadi My question wasn't regarding the difference between both settings, but between the registry edit and unchecking both settings.

**Comment by CyrusNajmabadi** [comment]
The registry setting is undocumented and unsupported.  I can't comment it as i do not want to convey any sort of contract or belief about what that key is or what impact it would have to change it at all.

**Comment by Bosch-Eli-Black** [comment]
Do we have a path forward to fix this?

**Comment by CyrusNajmabadi** [comment]
We'd need a repro to be able to investigate what is going on.

**Comment by Bosch-Eli-Black** [comment]
Okay. What kind of logs should I send you?

**Comment by jmarolf** [comment]
@Bosch-Eli-Black If you file a feedback ticket as per the directions [here](https://github.com/dotnet/roslyn/blob/master/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md#performance-issues) we will be able to see logs of what is happening.

**Comment by sharwell** [comment]
@CyrusNajmabadi I believe this is fairly easy to reproduce if you either work offline or block access to the site containing the database via a firewall.

**Comment by CyrusNajmabadi** [comment]
Ah yes.  I imagine that if the connection is blocked.  We will simply keep retrying indefinitely.  One thing we coudl do it have some sort of decay on retry when that happens.

**Comment by sharwell** [comment]
@CyrusNajmabadi We do have a long delay between retries, but the status message remains visible during the delay. The status message essentially says "we don't have the necessary information to provide a requested feature", which is a permanent situation for some users. Ideally we'd have a way to allow users to disable the feature (either for the current session or permanently) directly from the status message.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi We do have a long delay between retries, but the status message remains visible during the delay. The status message essentially says "we don't have the necessary information to provide a requested feature",

interesting.  that seems unfortunate.  we could have this dismiss more aggressively.  

> Ideally we'd have a way to allow users to disable the feature (either for the current session or permanently) directly from the status message.

**Comment by Bosch-Eli-Black** [comment]
I see value in the progress indicator, because it signals to me that not all of VS's features are ready, so if something such as autocomplete doesn't work properly, I have an indication as to why.

If downloading the index fails, though, it would be nice if the progress indicator went away and instead there was just a message saying that the download had failed, with a little "See more" link going to an article saying why the download might have failed (e.g. firewall issues, proxy, etc.).

After the backoff period is over and VS tries to download the index again, I'd like to see the progress indicator again. Then when the download fails again, the error message should come back, etc.. This would be somewhat annoying for the user, but I think it would provide a more clear indication of what's going on, and it would still be less annoying than what happens currently :)

**Comment by sharwell** [comment]
Design review conclusion: the progress indicator is not providing value that outweighs the clear drawbacks. For now, disable this indicator altogether but do not otherwise change the behavior of the indexing/options system.

**Comment by zahirtezcan** [comment]
I have inspected the symbol search code of Roslyn myself and I found out that it downloads the index file from https://az700632.vo.msecnd.net/pub/RoslynNuGetSearch/Elfie_V1/Latest.xml which is a single element XML file where the element contains an attribute named "content"

"content" attribute contains the (1) deflated and (2) base-64 encoded of the so-called index as a string. I have added some pointers to the code for the resolution [here](https://vsf-prod.westus.cloudapp.azure.com/comments/1183781/view.html).

Here is a sample code to download the xml and extract the index file for offline storage.

```
var element = XElement.Load(@"https://az700632.vo.msecnd.net/pub/RoslynNuGetSearch/Elfie_V1/Latest.xml");
var attribute = element.Attribute("content");
string base64 = attribute.Value;
byte[] deflated = Convert.FromBase64String(base64);
string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);


using (var inmem = new MemoryStream(deflated))
using (var inflater = new DeflateStream(inmem, CompressionMode.Decompress))
//using (var outFile = File.Create(@$"{localAppData}\Microsoft\VisualStudio\16.0_eb78fb52\PackageCache\Format1\nuget.org.txt"))
using (var outFile = File.Create(@"nuget.org.txt"))
{
    inflater.CopyTo(outFile);
}
```

As a workaround I have copied the `nuget.org.txt` file into VisualStudio local settings directory under `PackageCache\Format1` folder. VS local settings directory is under `%LocalAppData%\Microsoft\VisualStudio\` and looks like `16.0_eb78fb52` with possibly different alphanumeric characters after `16.0_`
