### ISSUE TITLE
[Regression] CodeLens does not work for Visual Basic

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#38722]
**Version Used**: 
Version 16.4.0 Preview 2.0 [29316.148.master]

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/1103906/65011523-26550900-d957-11e9-89fe-bb7106b94db1.png)

**Expected Behavior**:
CodeLens to show

**Actual Behavior**:
Space is reserved for CodeLens but the lenses themselves don't show up.

**Comment by davkean** [comment]
Actually, it looks like it eventually shows - I have PLM turned on, @heejaechang is this expected that CodeLens only shows after IntelliSense stage has finished?

**Comment by heejaechang** [comment]
I don't believe code lens listen to PLM. but code lens runs on OOP after solution information is pushed to OOP. probably need to see perf trace to see whether PLM made the timing of first OOP solution synchronization timing got changed or not.

**Comment by ivanbasov** [comment]
Tried PLM with @heejaechang with the latest VS. It seems it works much slower than the regular loading. Need to make perf tests what is happening there.
@dibarbet please let me know if you have a better context.

**Comment by ivanbasov** [comment]
reassigning to @dibarbet per suggestion by @jinujoseph

**Comment by dibarbet** [comment]
@davkean tried this out today a bunch of times with plm enabled and disabled on int.preview(29323.36.master).  I didn't notice any difference between the two - code lens took a couple seconds after space was reserved to appear.  

Can you still repro it on later versions of VS?  If so, could you provide a dump?
Thanks!
