### ISSUE TITLE
Bad Change Preview

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#38728]
Original code:
![image](https://user-images.githubusercontent.com/2371880/65068892-665bc200-d93e-11e9-9544-a0a8ef42c200.png)
Invoking ctrl+. on the `localFunction` variable:
![image](https://user-images.githubusercontent.com/2371880/65068874-5cd25a00-d93e-11e9-93c2-d7575735c1e0.png)

Note that the refactoring worked as you'd expect, but the preview didn't show the change.

**Comment by CyrusNajmabadi** [comment]
This is definitely a dupe.  something broke on the editor side.

**Comment by dibarbet** [comment]
@333fred can you scroll up in the preview pane?
If so I believe this is a dupe of https://github.com/dotnet/roslyn/issues/38345

**Comment by davkean** [comment]
This is a dupe of https://github.com/dotnet/roslyn/issues/38345, and in turn of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/977191.
