### ISSUE TITLE
Enhance local variable assignment tracking

### ISSUE THREAD

**Issue by Pretasoc** [dotnet/roslyn#38745]
**Version Used**: 

Visual-Studio-2019-Version-16.2.5

**Steps to Reproduce**:

Consider the following code snippet:

```
void Foo(object key)
{
    IDictionary<object, object> dictionary = CreateDictionary(); // May return null
    // Bar() returns an object
    var foo = dictionary?.TryGetValue(key, out object fooValue) ?? false ? fooValue : Bar();
    //                                                                     ~~~~~~~~
}
```
**Expected Behavior**:

The compiler can statically prove, that in the branch `fooValue` is used, it is always assigned.

**Actual Behavior**:
The comiler errors:
> The local variable `fooValue` might not be initialized before accessing.

**Comment by jaredpar** [comment]
Thanks for the suggestion. The compiler does not currently track this type of flow analysis for nullability. It's something we could consider in the future.

**Comment by RikkiGibson** [comment]
This looks similar to #36218. It's another question of whether we should bring some of the scenarios currently supported in nullability analysis back to definite assignment analysis.

Basically, if you change the code to `dictionary != null && dictionary.TryGetValue(key, out object fooValue) ? fooValue : Bar()`, definite assignement will start working as you expect.

**Comment by Pretasoc** [comment]
@RikkiGibson You are right, i tried to search for duplicates, but obviouly failed. The alternative code is exactly what i ended up with.
