### ISSUE TITLE
The SyntaxKind Enum could be in a separate library.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#38761]
The `SyntaxKind Enum` should be in a separate library, as its source is duplicated in multiple projects in the solution. eg `Microsoft.CodeAnalysis.VisualBasic` and `VisualBasicSyntaxGenerator` 
This also the same for CSharp projects.

Maybe we should start to separate them out, along with the helper methods, to a library dll. So there isn't a mismatch.

**Comment by gafter** [comment]
We're trying not to have a zillion assemblies.

**Comment by sharwell** [comment]
It is not possible to correct this. We have an internal review team that watches for this kind of split and files bugs to have them corrected (re-merged).

**Comment by CyrusNajmabadi** [comment]
> So there isn't a mismatch.

There shouldn't be a mismatch.  We don't duplicate the enum.  We just link in the actual source directly.  So the file is always the same contents across all these projects.

**Comment by jmarolf** [comment]
Yeah, I think linked files is the correct solution to problem like this in the roslyn repo. We are very constrained on the number of assemblies we can load.
