### ISSUE TITLE
Expand selection on method should include XML docs

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#38762]
**Version Used**: 16.4.0-pre.2.0+29318.173.master

**Steps to Reproduce**:

```c#
class C
{
    /// <summary>A method</summary>
    void M()
    {
    }
}
```

1. With the caret inside method `M`, invoke _Expand Selection_ until the selection spans `void M() { }`
2. Invoke _Expand Selection_ again

**Expected Behavior**:

Selection expands to include XML doc and method body.

**Actual Behavior**:

Ensure class `C` is selected.

This makes it hard to perform follow on actions such as:

- comment entire method without leaving invalid dangling documentation
- cut method to clipboard to paste somewhere else

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
