### ISSUE TITLE
Feature Request: NewLinesForBracesInMethodsWithMultilineParameters

### ISSUE THREAD

**Issue by johnrom** [dotnet/roslyn#38766]
I was directed here from an `omnisharp-vscode` issue: https://github.com/OmniSharp/omnisharp-vscode/issues/3283

With dependency injection. I like my constructors formatted like this:

```
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) {
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

However, the best I can do (that I know of) with the options given is:

```
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) 
{ // gross
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

Is it possible to add a special option for that case? I'd still like a child constructor to appear like this:

```
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) : base(myClass2, myClass3)
{
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

**Comment by ryzngard** [comment]
Design Review: We believe this scenario is important and works well as a validation for work towards an extensible formatter, being tracked at #31691 . We'll close this issue but keep it linked to use as a validation of design.
