### ISSUE TITLE
Custom columns are blank when FAR on a literal

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn#38778]
**Version Used**: 

**Steps to Reproduce**:

1.  Open VS and create a console app with this code:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            string s = "asdf";
        }
    }
```
2. Select the string `"asdf"`, right click, and choose Find All References
3. If Containing Member, Containing Type, or Kind columns are not displayed, right click on the column labels in the FAR window and show them

**Expected Behavior**:
Containing Member should be Main
Containing Type should be Program 
Kind should be Read

**Actual Behavior**:
The columns are empty

**Comment by CyrusNajmabadi** [comment]
Closing out.
