### ISSUE TITLE
Operators are classified as methods in tooltips

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/roslyn#38783]
**Version Used**: VS 16.2

**Steps to Reproduce**:

- Hover over any of the operators below `==`, `!=`, `<`

```C#
namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            _ = 1 == 1;
            _ = 1 != 1;
            _ = 1 < 1;
        }
    }
}
```

**Expected Behavior**:

They get the same color as shown in the editor

**Actual Behavior**:

They get the same color as methods

This also happens in the 'Find All References' window.

**Comment by dpoeschl** [comment]
Note also that the definition of overloaded operators are not classified as methods (even though they are classified as methods at their usage sites).
