### ISSUE TITLE
IDE0067 False Positive

### ISSUE THREAD

**Issue by GrimGadget** [dotnet/roslyn#38796]
**Version Used**: VS2019 16.2.5 

**Steps to Reproduce**:
```csharp
        public override Stream ToStream<T>(T input)
        {
            if (input == null) throw new ArgumentNullException(nameof(input));

#pragma warning disable IDE0067 // Dispose objects before losing scope
            // This method creates a new stream.  It's pointless to return a disposed object.
            return ToStreamAsync(input).GetAwaiter().GetResult();
#pragma warning restore IDE0067 // Dispose objects before losing scope
        }
```

**Expected Behavior**:
Disposed state of the return value should be ignored.  It's never appropriate for a return value to be disposed when returned.  Particularly if the instance is created as new inside the method and then used as a return value.

**Actual Behavior**:
Get IDE0067 warning saying the object should be disposed before losing scope.

**Comment by mavasani** [comment]
@GrimGadget Would you be able to provide a minimal compilable repro? I tried the below code snippet on latest VS2019 16.3 bits and don't see IDE0067:

```csharp
using System;
using System.IO;
using System.Threading.Tasks;

class Test
{
    public Stream ToStream<T>(T input)
    {
        if (input == null) throw new ArgumentNullException(nameof(input));

        return ToStreamAsync(input).GetAwaiter().GetResult();
    }

    private Task<Stream> ToStreamAsync<T>(T input)
    {
        return Task.FromResult<Stream>(File.OpenRead(null));
    }
}
```
