### ISSUE TITLE
Indent characters change from tabs to spaces at line break

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38798]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/742548/indent-characters-change-from-tabs-to-spaces-at-li.html)._

---
[regression] [worked-in:16.3 preview 1]
my settings
indenting: Smart
Tab size: 4
Indent size: 4
Keep tabs: true

The sample code is as follows.

```cs
namespace Sample
{
	public class Hoge
	{
		public int Test()
		{
			int x = 1;
			return x;
		}
	}
}
```

If you place a cursor at the beginning of &quot;int x&quot; and type enter key, the indent of the new line is incorrect.
There should be 3 tabs but 3 spaces as shown in the code below.

```cs
namespace Sample
{
	public class Hoge
	{
		public int Test()
		{
			
   int x = 1;
			return x;
		}
	}
}
```

In VS2019 (not preview) and previous VS2019 preview, the line was broken correctly like the following code.

```cs
namespace Sample
{
	public class Hoge
	{
		public int Test()
		{

			int x = 1;
			return x;
		}
	}
}
```

---
#### Visual Studio Feedback System on 9/23/2019, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
https://github.com/dotnet/roslyn/pull/38907 fixed in 16.4.Preview2
