### ISSUE TITLE
Fusion tests break on machines without 4.6 installed

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#388]
Our fusion unification tests fail on a machine with just 4.5.1 our below unification test is failing:

``` csharp
TestMatch(
    "System.Runtime.Handles, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "System.Runtime.Handles, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    AssemblyIdentityComparer.ComparisonResult.Equivalent,
    unificationApplied: true);
```

Disabling this test in order to get more unit tests running on Jenkins.

**Comment by theoy** [comment]
@jaredpar - can you work out whether you or @tmat want to take this one? Thanks! :smile:

**Comment by jaredpar** [comment]
I can take a look at this.

JaredPar from a phone
http://blog.paranoidcoding.com/
________________________________

**Comment by tmat** [comment]
Well, the fix is to upgrade the test machine to 4.4 RC.

**Comment by tmat** [comment]
We can also conditionally run those failing tests only if the machine has the corresponding FX.

**Comment by jaredpar** [comment]
@tmat 

Upgrading is not an option right now.  If we force the upgrade then how are customers to run our tests?  Should they be required to install pre-releases of Visual Studio?  At the moment we do not require this.

**Comment by tmat** [comment]
Yes, that's why my second comment to make this particular test conditional on the version of .NET framework the tests are running on. 

The question is what we want from Jenkins. Do we want it to be able to run all tests, or just some. We will have tests that depend on the latest CLR version. If we have control over the server Jenkins runs on then I'd prefer it runs as many tests as possible.

**Comment by jaredpar** [comment]
@tmat 

This is an on going debate at the moment.  I think at the end of the day Jenkins will need to be running 4.6 to verify our core scenarios.  At the same time we need a customer story that doesn't involve them installing builds of Visual Studio / .NET that they can't access.  

I agree that short term the test just needs to detect the runtime and change based on that.

Do you have a reliable way of checking the runtime version we could use here?

**Comment by jaredpar** [comment]
It appears this error was a short lived issue.  I went to re-enable this test today to work out the failure and it turns out I forgot to disable it in the first place.  So it's been happily passing for this past month without any reported issues.

**Comment by gafter** [comment]
Verified that this test is not disabled. See https://github.com/dotnet/roslyn/blob/stabilization/src/Compilers/Core/CodeAnalysisTest/MetadataReferences/AssemblyIdentityComparerTests.cs#L525-L529
