### ISSUE TITLE
Code formatting breaks briefly after code is fixed

### ISSUE THREAD

**Issue by decriptor** [dotnet/roslyn#38819]
**Version Used**: 
Roslyn (Language Service)
3.3.1-beta3-19454-05+3b423bd305daf81076d4d7b105101361c2

**Steps to Reproduce**:

1. Put a C# file into a non-compilable state briefly and fix it. ie, a simple if block condition
2. Hit enter. The cursor isn't aligned to the expected location

**Expected Behavior**:
Correct indentation

**Actual Behavior**:
Only indents once

Tabs are used for all indenting in this file.

![incorrect_formatting_csharp](https://user-images.githubusercontent.com/49821/65534575-ff4d8880-debc-11e9-8fa4-088cd82141f2.gif)

**Comment by decriptor** [comment]
This is reproducible on both VSwin and VSmac

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Definitely doesn't seem desirable :) I can look to see if we can figure out where indentation/smart-indentation is going off the rails here.

**Comment by CyrusNajmabadi** [comment]
Hunh.  I can't repro this at all.  Very odd.  @decriptor if you hit this again, can you just copy the code you had prior to hitting enter, and tell us where your caret is.  Something about my repro case isn't matching yours.

**Comment by CyrusNajmabadi** [comment]
Note: this depends on using 'tabs' for indentation.  Indentation works properly if you are set to 'spaces'.  No clue why this would affect anything.

**Comment by CyrusNajmabadi** [comment]
Repro:

Ensure only tabs are used for indentation:

```c#
public class Example
{
	public void Test(object session)
	{
		if (session == null)return;
	}
}
```

Hit enter between `)` and `return`.  

`return` is then indented *3 spaces* instead of *3 tabs*.  There is likely some sort of conversion internally that is just computing "3 indents" but then converting that to just 3-spaces instead of the proper actual indentation.

**Comment by KirillOsenkov** [comment]
Great bug!

**Comment by CyrusNajmabadi** [comment]
I have a potential fix.  Testing now.
