### ISSUE TITLE
Test plan for "lambda discard parameters"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#38820]
[Championed issue](https://github.com/dotnet/csharplang/issues/111)

- [x] Specification checked in to `csharplang` (PR https://github.com/dotnet/csharplang/pull/2901)
- [x] `(_, _) => 0` with LangVersion 8 (error) (see `DiscardParameters_CSharp8`)
- [x] `(_, _) => 0` with LangVersion Preview (ok) (see `DiscardParameters`)
- [x] also works with explicit types `(int _, string _) => 0` (see `DiscardParameters_WithTypes`)
- [x] also works in delegate syntax `delegate(int _, string _) { return 0; }` (see `DiscardParameters_InDelegates`)
- [x] discard parameters in delegates do not allow attributes (see `DiscardParameters_InDelegates_WithAttribute`)
- [x] discard parameters are not in scope and cannot be read from or written to (see `DiscardParameters_NotInScope`)
- [x] that a single `_` is not a discard parameter (ie. is in scope and can be read from) (see `DiscardParameters_NotADiscardWhenSingleUnderscore`)
- [x] Verify semantic model on discard parameters (see `DiscardParameters_NotInScope`)
    - [x] parameter symbol has `IsDiscard` set to `true`
    - [x] parameter symbol has `_` as name
    - [x] parameter symbol has expected type and nullability
- [x] variable named `_` allowed inside a lambda with discard parameters (see ` DiscardParameters`)
- [x] discard parameters with `ref`, `in` and `out` parameters (see open question below) (see `DiscardParameters_RefAndOut`)
- [x] multiple `_` parameters on local function (still error) (see `DiscardParameters_OnLocalFunction`)
- [x] unicode underscore `\u005f` doesn't cound as discard (same as in other contexts) (see `DiscardParameters_UnicodeUnderscore`)
- [x] `@_` is not a discard (same as in other contexts) (see `DiscardParameters_EscapedUnderscore`)
- [ ] test lambda in expression tree (disallow) (see `DiscardParameters_ExpressionTreeNotAllowed`)
- [x] test no regression on shadowing of underscore (see https://github.com/dotnet/roslyn/pull/38786#discussion_r341869731)

Questions raised on team review today:
- [ ] confirm desired debugging and EE behavior. Are the values visible? F# doesn't show discards while debugging, but we should try if we can. (`debugger-discards` branch)
- [x] LDM: confirm whether we want the discards to be in scope or block visibility in some way or disallow locals named `_` within a scope where discard parameters exist. Some scenarios:
    - `int _ = 1; Func<int, int, int> x = (_, _) => _++; /* this currently binding to the local declared outside the lambda? */`
    - `Func<int, int, int> x = (_, _) => { int _ = 1; return _; } /* this is currently allowed */`
- [x] test `nameof(_)` (see `DiscardParameters_NotInScope_Nameof`)
- [x] ~~verify `GetAttributes()` if we have a new symbol~~ (latest implementation removed the new parameter symbol)
- [x] allow expression trees unless good reason not to (see `DiscardParameters`)
- [x] test IDE rename
- [x] test `GetDeclaredSymbol` (see `DiscardParameters_NotInScope`)
- [x] test FindAllRefs
- [x] LDM: should we extend the feature to local functions? (see lambda-to-local-function refactoring)

## Productivity
- [x] converting from lambda with discards to local function (currently produces code with invalid parameters)
- [x] no IDE diagnostic reporting that discard parameters are unused
- [x] QuickInfo shows lambda parameter discards as `(discard) int _`
- [ ] IDE doesn't use a special classification for discards (same as in other contexts)
- [x] test rename (see `RenameLambdaDiscard`)

## Open issues for LDM:
- [ ] Should we produce a distinct error for `out` or `ref` discard?

**Comment by chsienki** [comment]
Looks good, couple of notes:

- IDE rename works, but incorrectly reports conflicts (true of single shadowed discard params too)
- As noted lambda -> local function works but introduces invalid code.
- EE during debugging will display correctly and allow editing but fail in immediate / locals / watch with ambiguity.
- Hover in IDE doesn't show value during debugging, but does in watch / locals?
- Discards seem to be allowed in expression trees / missing test?

**Comment by jcouv** [comment]
Filed a follow-up issue for discards in debugger: https://github.com/dotnet/roslyn/issues/48408
I'll close this test plan now
