### ISSUE TITLE
Optimize away redundant field initializers

### ISSUE THREAD

**Issue by GSPP** [dotnet/roslyn#3882]
Code in the wild often has redundant field initializers:

```
class C {
    int x = 0;
    public C() {
    }
}
```

Sometimes this is written for bad reasons, sometimes this actually increases clarity (e.g. in the presence of many initialized fields).

Roslyn should optimize this away. This should result in identical semantics.

In case you wonder: All JITs (x86, x64 and RyuJIT) do not optimize this away. Our .NET JITs are very poor at optimizing in general. Relying on that happening is probably not a good choice.

This optimization should work for instance fields and for static fields. As far as I can tell the readonly and volatile modifiers don't have any impact here.

**Comment by mikedn** [comment]
Roslyn already optimizes the code in your example. When optimizations are enabled the following IL is produced:
```
.method public hidebysig specialname rtspecialname instance void .ctor() cil managed
{
    .maxstack 8
    L_0000: ldarg.0 
    L_0001: call instance void [mscorlib]System.Object::.ctor()
    L_0006: ret 
}
```
It also optimizes static the initialization of static fields but it appears that in that case an empty static constructor is still generated:
```
.method private hidebysig specialname rtspecialname static void .cctor() cil managed
{
    .maxstack 8
    L_0000: ret 
}
```

**Comment by GSPP** [comment]
Good! The try Roslyn online service apparently has Debug mode on or an old version. Or, I did something wrong.

**Comment by Joe4evr** [comment]
Try Roslyn also has an option to switch between Debug and Release mode.

**Comment by GSPP** [comment]
OK, I see it now. What's the process to close this issue? Am I supposed to do that?

**Comment by mikedn** [comment]
I suggest you leave it open, perhaps someone from the Roslyn team can comment about the empty static constructor. I don't think it should be generated when all the static initializers are optimized away.
