### ISSUE TITLE
Test plan for "function pointers"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#38830]
- [Proposal](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md)
- [Championed issue](https://github.com/dotnet/csharplang/issues/191)

- [ ] Specification checked in to `csharplang`.
- [ ] Tests based on specification...

**Comment by AlekseyTs** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/43321

**Comment by jcouv** [comment]
@AlekseyTs Don't forget to link the new test plan into the feature status document. Thanks
