### ISSUE TITLE
Incorrect analysis: IDE0059 Unnecessary assignment of a value

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/roslyn#38844]
**Version Used**: 16.4

**Steps to Reproduce**:

1. Open up SignService.sln from https://github.com/dotnet/SignService
2. See messages

**Expected Behavior**:
No false analysis

**Actual Behavior**:
```
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0059	Unnecessary assignment of a value to 'ppKey'	SignService	D:\dev\SignService\src\SignService\Utils\DistinguishedNameParser.cs	23	Active
Message	IDE0059	Unnecessary assignment of a value to 'ppVal'	SignService	D:\dev\SignService\src\SignService\Utils\DistinguishedNameParser.cs	23	Active
```
Those out variables are used in a while loop and then passed into `Marshal.PtrToStringUni`.

https://github.com/dotnet/SignService/blob/aa17184f886b647042c0d6d8323e2d21943e3fb5/src/SignService/Utils/DistinguishedNameParser.cs#L23-L30

The suggestion to use a discard is wrong.

**Comment by frevds** [comment]
Here is a simple example where it occurs for me: https://github.com/dotnet/roslyn/issues/39238

**Comment by Dean-NC** [comment]
Yep, it's a bug.  I've noticed the same when I assign a value to an int that's outside/just above a do-while loop, where I want the int to have an initial value before the loop, and then change the value inside the loop.  I check the value in the while().  In this case, it says it's not needed and I should use a discard.  This is wrong.  If I let you do that, my variable won't get the initial value.

It's nice that you try to look out for us, but it has gone way too far.  It's not too smart for it's own good.

**Comment by CyrusNajmabadi** [comment]
@mavasani Have you fixed this?  
@Dean-NC if not, would you be willing to contribute a fix hre?

**Comment by mavasani** [comment]
I verified this no longer repros on latest 16.6 builds, closing...
