### ISSUE TITLE
Editor tests periodically fail with Win32Exception Invalid window handle

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#3885]
See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_windows_release/158/ and http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_windows_debug/1262/.

Starting point from @jaredpar 

> It appears to be a race condition in WPF shut down because we aren’t disposing handles.

**Comment by jasonmalinowski** [comment]
@agocke, @tannergooding, are we still seeing this? The links are no longer good.

**Comment by jaredpar** [comment]
@jasonmalinowski indeed this still happens on a semi-regular basis.

**Comment by jasonmalinowski** [comment]
@jaredpar: link?

**Comment by jaredpar** [comment]
@jasonmalinowski looking.  It will take me a bit to dig through the logs and find a recent one.

**Comment by jaredpar** [comment]
@jasonmalinowski it's not in the most recent logs (jenkins only caches a small number of jobs).  For now lets close.  I'll reopen the next time this shows up and paste the stack trace in.
