### ISSUE TITLE
show Potential Fixes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38854]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/736875/show-potential-fixes-1.html)._

---
unable to see show potential fixes option if the list is huge (refer attachment for better understanding)

---
#### Visual Studio Feedback System on 9/17/2019, 11:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/19/2019, 03:00 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
![show](https://user-images.githubusercontent.com/10605811/65629970-5587fd80-df89-11e9-891a-d23e8294fd1e.png)

**Comment by CyrusNajmabadi** [comment]
This is a platform issue to decide what htey want to do here.
