### ISSUE TITLE
Intellisense should not show GetType for span

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#38878]
**Version Used**: master

**Steps to Reproduce**:

```csharp
using System;

public class C {
    public static void M() {
        var span = new int[]{}.AsSpan();
        span.GetType();
    }
}
```

The above fails to compile with the following error:

error CS0029: Cannot implicitly convert type 'System.Span<int>' to 'object'

Therefore it would be best if intellisense didn't suggest the GetType() method. Alternatively span could hide GetType with a working, non boxing implementation.

**Comment by CyrusNajmabadi** [comment]
Interesting.  I wonder if htis is actually a bug in the compiler.  I believe we're just calling LookupSymbols here.  But if this is not a valid name from the calling context, it shouldn't be offered (similar to how the compiler filters out inaccessible members and the like).  

It seems like it would be busted for the IDE to now have to know about this one single language rule about member-lookup and have to filter out these members.

**Comment by DoctorKrolic** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/59884. @CyrusNajmabadi please close this issue and move it to "Completed" section. Tagging you just because you commented here earlier

**Comment by CyrusNajmabadi** [comment]
Sounds good.  Thanks.  Fixed in https://github.com/dotnet/roslyn/pull/59884.
