### ISSUE TITLE
Can't install VS2019 since: VS_InstallerShell.exe has an invalid certificate

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#38872]
download vs_enterprise__1063459011.1568747910.exe and excute, will generate:
C:\Program Files (x86)\Microsoft Visual Studio\Installer
But then the window is closed and vs2019 isn't installed.
Execute vs_installer.exe will show:
VS_InstallerShell.exe has an invalid certificate. Please ensure the appropriate Microsoft certificates are installed.

I search in internet, so many pepple have this problem.

**Comment by razer89** [comment]
same problem here..can't solve it

**Comment by razer89** [comment]
> 
> 
> download vs_enterprise__1063459011.1568747910.exe and excute, will generate:
> C:\Program Files (x86)\Microsoft Visual Studio\Installer
> But then the window is closed and vs2019 isn't installed.
> Execute vs_installer.exe will show:
> VS_InstallerShell.exe has an invalid certificate. Please ensure the appropriate Microsoft certificates are installed.
> 
> I search in internet, so many pepple have this problem.

You need to update windows and restart after, everything will work perfectly after that.

**Comment by CreateAndInject** [comment]
@razer89 Why do you edit your comment?
I can install vs2019 a few month ago.
I know I can update windows to resolve it.
BUT I don't want to update, because windows will update .net framework.
Some program can run on .net 3.5 sp1(2.0.50727.3053), but can't run on 2.0.50727.8806.
So, how to install 2019 without update windows? Or how to install older .net framework 3.5 on windows7(I don't know how to uninstall .net 3.5 on windows7, since it's a part of windows 7)?

**Comment by CreateAndInject** [comment]
I find a lightweight way to resolve it without updating windows:
Install KB3004394.
But it seems there's a bug, and should install KB3024777 to fix the bug, but I can't install KB3024777 on my pc(Nothing happen when doubleclicking).

**Comment by laxmikantht** [comment]
> I find a lightweight way to resolve it without updating windows:
> Install KB3004394.
> But it seems there's a bug, and should install KB3024777 to fix the bug, but I can't install KB3024777 on my pc(Nothing happen when doubleclicking).

**Comment by laxmikantht** [comment]
Thanks for your help..  It's worked for me. The certificate problem is solved after installed KB3004394.

**Comment by CyrusNajmabadi** [comment]
Closing out as external and as customers have reported this is no longer an issue.
