### ISSUE TITLE
expose something that let third party to hint our cache

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#3888]
during dev14, winform team moved part of their code to use Roslyn directly to get code information for C# and VB.

that improved some scenario's perf, but also it made some scenario noisy since at the time, they didn't have a way to hint Roslyn's cache or implement their own cache.

so, whenever the scenario got "cache-miss" in Roslyn side, the scenario had to pay penalty.

as more and more outsider depending on Roslyn to get code information, this probably will become a common thing to happen.

we might need to do something around cache one more time.

**Comment by CyrusNajmabadi** [comment]
Lacks a concrete proposal or partner team requesting actual change.

Will also likely not be relevant as we move OOP and move to just allowing the runtime to handle this.
