### ISSUE TITLE
References to VB.NET methods are not showing up in CodeLens if they are in an aspx page.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38897]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/720917/references-to-vbnet-methods-are-not-showing-up-in.html)._

---
What steps will reproduce the problem?
1. Create a VB.NET class in project A with some methods
2. Create an aspx page in a separate project B in the same solution.
3. In one of the aspx pages, refereence one of your methods from project A.
4. Look at CodeLens  for your methods in project A.

What is the expected output? What do you see instead?
Expected: CodeLens shows usages of the methods.
Actual: CodeLens does not show usages of the methods; you hvae to use Find to find them.

---
#### Visual Studio Feedback System on 9/4/2019, 00:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is now through razor.  And whether or not these are investing in these scenarios.
