### ISSUE TITLE
Intellisense is not very smart, suggests "struct" instead of "string"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38899]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/726472/intellisense-is-not-very-smart-suggests-struct-ins.html)._

---
Let's say I'm defining a simple class in C#. Now I want to define a string member, so I type &quot;public str&quot;. At this point Intellisense suggests

struct

instead of

string

In order to autocomplete &quot;string&quot;, I must type &quot;i&quot; or else &lt;up&gt; once to focus it in the drop down.

This seems entirely wrong because string is much more likely to be used here; in fact struct is (I believe) not even legal here. &quot;string&quot; also comes fiirst alphabetically, so why suggest &quot;struct&quot; instead?

---
#### Visual Studio Feedback System on 9/9/2019, 03:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
> This seems entirely wrong because string is much more likely to be used here; in fact struct is (I believe) not even legal here. 

This is incorrect.  It's completely legal to declare a nested struct inside a class.

> This seems entirely wrong because string is much more likely to be used here;

That's very likely true.  I'm curious why Pythia/IntelliCode didn't figure that out.

--

Finally, this is a case where MRU will help.  We could always consider persisting that again to help make sure once these common patterns are established through typing, that they're remembered across sessions.

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/76273004-ff0e3300-6239-11ea-9cc8-9640c4a4392e.png)

The above could only happen when MRU is involved.  In which case, it's not clear to me that we shouldn't follow what MRU is doing.

**Comment by davidorbelian** [comment]
@CyrusNajmabadi So what should one do if having same issue? Is there any way to reset that behavior? I don't know why, but that just happened to me too and now I get that sick "struct" instead of "string" suggestion every time, and that is really very often. That's just impossible to work like that.

**Comment by CyrusNajmabadi** [comment]
The mru shiuld not persist when you close/open vs. So that should resolve things.

**Comment by davidorbelian** [comment]
> The mru shiuld not persist when you close/open vs. So that should resolve things.

Yes, that did the job. Have to restart VS and then it still suggests `struct` instead of `string` until I choose that in the drop-down. Then it uses `string` as the first suggestion when I type `str..`, though still suggests `struct` when typing `st..`.

**Comment by CyrusNajmabadi** [comment]
> though still suggests struct when typing st

this indicates taht you commited `struct` at some point, making it the most-recently-used.
