### ISSUE TITLE
'Suppress diagnostic' should appear before 'Configure diagnostic'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#38914]
**Version Used**: 16.4 Preview 1

**Steps to Reproduce**:

1. Expand the light bulb for a diagnostic
2. Attempt to suppress the diagnostic

**Expected Behavior**:

The localized action (suppress diagnostic) should appear before the project-wide action (configure diagnostic). This matches the default selection of 'Fix single' when 'Fix All' is also available.

**Actual Behavior**:

Suppressing diagnostics now takes several additional steps relative to earlier releases, because it is more deeply nested and not selected by default.
![image](https://user-images.githubusercontent.com/1408396/65779687-17134f80-e0fd-11e9-9793-ee6ad68434c8.png)

**Comment by mavasani** [comment]
I would like to defer to customer feedback on this. Can we bring this up in design meeting when both @kendrahavens and @mikadumont are present (so in 2 weeks from now).

**Comment by sharwell** [comment]
@mavasani I have hit this several times myself. Is there a way to at least turn off the new feature so it's not always in my way?

**Comment by mavasani** [comment]
There is none.  Is your request about not nesting suppressions or not showing configuration menus Having suppression at the top level cluttered the light bulb and there have been many requests in the past to nest all suppression actions.

**Comment by mavasani** [comment]
If required, we can even create 2 separate top level items for "Configure" and "Suppress". I would still like PMs to make a call here instead of us designing it :)

**Comment by sharwell** [comment]
The main problem is the ordering, not the nesting. When the menu is expanded, 'Suppress' should be the first selected item.

**Comment by mavasani** [comment]
Available options:

1. Move configuration items below suppression items in current menu
2. Introduce separate top level items for "Configurations" and "Suppressions"
3. Introduce an option to deviate from the default behavior.

**Comment by CyrusNajmabadi** [comment]
> The main problem is the ordering, not the nesting. When the menu is expanded, 'Suppress' should be the first selected item.

I agree. Here's my logic:

It is *often* the case that i want to suppress a multitude of reported issues.  So i want quick access to that option.  I will perform the action, and then likely perform it some unbounded amount of times ore.

However, the same does not hold true for 'configuring' the analyzer.  If i configure, i'll likely only configure it once or twice to get it at the level i want, then i'll never touch it again.  

As such, we've made the option you only invoke a tiny handful of times more important than the one i might invoke over and over again.

**Comment by sharwell** [comment]
This is extremely aggravating. The new menu ordering has made suppressions virtually unusable.

**Comment by mavasani** [comment]
Fix is trivial here. You need to adjust the ExtensionOrder attributes on all implementations of http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/Supression/IConfigurationFixProvider.cs,24

**Comment by sharwell** [comment]
Design review conclusion: it is fine to reorder these. We should rename the group to "Suppress or Configure issues" at the same time.
