### ISSUE TITLE
Copy fully qualified name of selected identifier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38927]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/725281/copy-fully-qualified-name-of-selected-identifier.html)._

---
Often I want to share a class or a function or a member etc with another team member  and browsing in VS I can easily copy a name like &quot;Foo&quot; and send it to them but that is ambiguous for them to find in a very large codebase.

Instead I'd like to send them the fully qualified namespace &quot;Team::Project::Component::Foo&quot;
I find myself doing this a lot the hard way by hovering over the object to see it's intellisense info and typing tha tout manually which is error prone and tedious.

---
#### Jane Wu [MSFT] on 9/5/2019, 11:22 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by kendrahavens** [comment]
You can currently open Class View (Ctrl+Shift+C) and when you copy (Ctrl + C) from an item selected in Class View you get the fully qualified name. This would be much more accessible if we could do it from the Editor with an **Edit > Copy Fully Qualified Name** command.

**Comment by CyrusNajmabadi** [comment]
> Instead I'd like to send them the fully qualified namespace "Team::Project::Component::Foo"

@kendrahavens It's possible this is a request for a C++ feature (given the `::`s).

**Comment by kendrahavens** [comment]
Ah, thank you! I've reopened the devcomm issue asking for what language they'd like to see it in.
