### ISSUE TITLE
show outlining for comments (separate option)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38928]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/725721/show-outlining-for-comments-separate-option.html)._

---
**Now:**
Show outlining for comments and preprocessor regions 

**Suggest:**
Show outlining for comments
Show outlining for preprocessor regions

---
#### Jane Wu [MSFT] on 9/9/2019, 00:02 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
