### ISSUE TITLE
Task already completed exception in Workspace.TryApplyChanges

### ISSUE THREAD

**Issue by Sergey-Vlasov** [dotnet/roslyn#38936]
In my Visual Studio extension I create a temporary workspace like this:
```
Microsoft.CodeAnalysis.Workspace w = new Workspace();
Microsoft.CodeAnalysis.Project project = w.CurrentSolution.AddProject();
w.TryApplyChanges(project.Solution);
```
It worked fine for several years, but after the recent VS 2019 16.3.0 update it generates the following exception:

> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
>    at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.LanguageServerClientEventListener.StartListening(Workspace workspace, Object serviceOpt)
>    at Microsoft.CodeAnalysis.Host.DefaultWorkspaceEventListenerServiceFactory.Service.EnsureListeners()
>    at Microsoft.CodeAnalysis.Workspace.GetEventHandlers[T](String eventName)
>    at Microsoft.CodeAnalysis.Workspace.RaiseWorkspaceChangedEventAsync(WorkspaceChangeKind kind, Solution oldSolution, Solution newSolution, ProjectId projectId, DocumentId documentId)
>    at Microsoft.CodeAnalysis.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent)
>    at Microsoft.CodeAnalysis.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent)
>    at Microsoft.CodeAnalysis.Workspace.ApplyProjectAdded(ProjectInfo project)
>    at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
>    at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)

Note that it looks very much like a race condition, because I don't see the error when running the code first time on a "cold" machine. But when all assemblies are already in memory, the exception occurs every time.

Looking at source:
```
        public void StartListening(Workspace workspace, object serviceOpt)
        {
            // mark that roslyn solution is added
            _taskCompletionSource.SetResult(null);
        }
```
Maybe there should be a check that result is not yet set?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
