### ISSUE TITLE
Use Enhanced Colors For VB is only listed under C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#38934]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/734508/use-enhanced-colors-for-vb-is-only-listed-under-c.html)._

---
Visual Basic options should be selectable under Visual Basic or listed in 2 places also the text should be &quot;Use Enhanced Colors for C# and Visual Basic&quot; not just &quot;Basic&quot;

---
#### Jane Wu [MSFT] on 9/16/2019, 00:19 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by JoeRobich** [comment]
Issue was reported for 16.3 Preview 3. The Option is available under `Tools > Options > Text Editor > Basic > Advanced` in 16.3.1 and 16.4 Preview 1. 
![image](https://user-images.githubusercontent.com/611219/65995265-fd01a600-e449-11e9-8d6b-40e309bb8233.png)

"Basic" is the name that we've used for "Visual Basic" in the Text Editor Options. I would defer to @kendrahavens whether this is something we would want to consider changing.

**Comment by paul1956** [comment]
The exact issue from (Preview 3) does not happen in 16.4.0 Preview 1.0, so I think you can close this issue. The issue of what you call Basic is not worth changing at this time.

**Comment by JoeRobich** [comment]
Thanks @paul1956!
