### ISSUE TITLE
System.Index indexing for arrays does not use pattern-based Index

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#38942]
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHABgAIcCAWAblNJwGZq9KBhS0gb1MqDqBAGyU0AOxiUAsgApJMANoBdShAQIAlEMEBeAHzrNSgHoEV9SgHprlAO4ALAJ4B+AUI+CaYgMaONWTkaKlhtIUNKMLMLRhJdL2ExRSCAZQAHCAkAHkUjKHSJHUiCiRjLRIT4oR9xKSCAGTRYXKkjDFhi9thyuIBfIA==

**Comment by alrz** [comment]
we can save up a few locals as well, index doesn't need to be captured in a local if it's not sideeffecting, I think we have a helper for that.
