### ISSUE TITLE
Compile without switch optimizations

### ISSUE THREAD

**Issue by shargon** [dotnet/roslyn#38956]
# Issue Title

Is possible to specify some flags in the compiler for disable some optimizations? 

# General

As i know, when a switch have a lot of entries, is added a method `ComputeStringHash` is possible to prevent this optimizations?

**Comment by CyrusNajmabadi** [comment]
>  is possible to prevent this optimizations?

The only exposed option is `-optimize[+|-]                Enable optimizations (Short form: -o)`.  You cannot control individual optimizations.

**Comment by gafter** [comment]
@shargon This is not really an optimization.  It is just efficiently generating code for the construct.
