### ISSUE TITLE
IAsyncEnumerable iterator method generates InvalidProgramException at runtime

### ISSUE THREAD

**Issue by maloo** [dotnet/roslyn#38961]
**Version Used**: Core 3.0.100

**Steps to Reproduce**:

1) Call this function:

        object _splitsLock = new object();
        public async IAsyncEnumerable<SplitBatch> GetSplits(IEnumerable<string> ids,
            DateTime from, DateTime to, [EnumeratorCancellation] CancellationToken ct)
        {
            if (to == from)
                yield break;
            try
            {
            }
            finally
            {
                lock (_splitsLock)
                    Console.WriteLine("");
            }
        }

**Expected Behavior**: No InvalidProgramException

**Actual Behavior**: InvalidProgramException

I stripped it of most code while still triggering the error. The lock in the finally block is needed to trigger the exception. Function is called from a grpc streaming server call in asp.net core.

**Comment by agocke** [comment]
@jcouv Could you take a look at this? Sounds like a compiler bug

**Comment by jcouv** [comment]
I can repro. I'll investigate. 
Thanks for reporting this with a self-contained repro!

**Comment by maloo** [comment]
Great, I was hoping it would be enough
