### ISSUE TITLE
Nullable reference type: possible generics inconsistency

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/roslyn#38982]
Greetings,

with the new C# feature of nullable reference types there appears to be an inconsistency with generics:

```
static void Foo<T>(T State, Action<T> Bar)
{
  Bar(State);
}

void Main()
{
  string? Value = null;
  Foo(Value, a =>
  {
    //Here "a" is of type "string" and not "string?"
  });
}
```

Shouldn't "a" be of type "string?"?

**Comment by sharwell** [comment]
@theunrepentantgeek The type `T` in the example should be `string?`, which would produce the following full signature:

```
static void Foo(string? State, Action<string?> Bar)
```

The lambda should have picked this up as well, but apparently did not.

**Comment by sharwell** [comment]
Ah, this is just an IntelliSense bug. The _compiler_ is correctly determining that the type of `a` is `string?`, but Quick Info is presenting it to the user as `string`. You can see this with the following:

```
static void Foo<T>(T State, System.Action<T> Bar)
{
    Bar(State);
}

static void Main()
{
    string? Value = null;
    Foo(Value, a =>
    {
        //Here "a" is of type "string" and not "string?"
        string? y = a;
        string x = a;
    });
}
```

**Comment by jasonmalinowski** [comment]
@333fred Just to check, is this related to any of the lambda stuff you've been doing or is this something we should investigate?

**Comment by 333fred** [comment]
Yes, in fact this will be resolved by https://github.com/dotnet/roslyn/pull/38769. Note that there will be some inconsistencies with local functions nested _inside_ these lambdas, but my hope is that they're rare enough to not notice for now.

**Comment by jasonmalinowski** [comment]
Can confirm it works now.
