### ISSUE TITLE
Pattern matching: override deconstruct

### ISSUE THREAD

**Issue by akiraKido** [dotnet/roslyn#38993]
I'm not sure if this is the right place for this issue. If it is inappropriate for this repository, I would be thankful if you could direct me to a more suitable repository. Thank you in advance.

---

For pattern matching, I'd like to deconstruct a certain struct I made as follows:

	public struct Result<T>
	{
		public readonly bool IsSuccess;
		public readonly T Value;
		public readonly string? Message;

		private Result(bool success, T value, string? message) =>
			(IsSuccess, Value, Message) = (success, value, message);

		public void Deconstruct(out bool success, out T value, out string? message) =>
			(success, value, message) = (IsSuccess, Value, Message);

		public void Deconstruct(out bool success, out string? message) =>
			(success, message) = (IsSuccess, Message);
		public void Deconstruct(out bool success, out T value) =>
			(success, value) = (IsSuccess, Value);

		public static Result<T> Fail(string message) => new Result<T>(false, default, message);
		public static Result<T> Success(T value) => new Result<T>(true, value, null);
	}

so that I would be able to do something like this:

	switch (TryGetValue(ref input, ref length))
	{
		case (false, string e):
			return Result<JsonNode>.Fail(e);
		case (true, JsonNode value):
			values.Add(value);
			break;
	}

This currently doesn't compile, saying that the deconstruction is ambiguous, despite explicitly declaring their types.

This works:

	switch (TryGetValue(ref input, ref length))
	{
		case (false, _, var e):
			return Result<JsonNode>.Fail(e);
		case (true, var value, _):
			values.Add(value);
			break;
	}

but the `_` seems verbose to me.

**Comment by CyrusNajmabadi** [comment]
This is likely a request for dotnet/csharplang.  Would you mind porting it over there?

**Comment by akiraKido** [comment]
@CyrusNajmabadi Thanks for the guidance! I'll do so.
