### ISSUE TITLE
Constrain params arguments.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#3899]
I'm thinking something like:
```
public void Foo(params int[] args) where params : NotNullOrEmpty
{
    ...
}
```
What do you think?
Perhaps a new keyword is cleaner idk:
```
public void Foo(paramlist int[] args)
{
    ...
}
```

**Comment by MgSam** [comment]
I don't follow what your proposal is trying to say. How does not wanting an array to be null or empty have anything to do with the `params` keyword? Why wouldn't you want such functionality on any argument?

You should take a look at the method contracts [proposal](https://github.com/dotnet/roslyn/issues/119).

**Comment by JohanLarsson** [comment]
While failing fast is nice, failing to compile is nicer. Lets use string split as an example:
```
public String [] Split(params char[] separator)
```
Here it would make sense to constrain it to have at least one item.
I don't know of a clean way o do this as of now.
```
public String [] Split(char separator, params char[] separators)
{
    // prepend separator to separators...
}
```
I have not thought long and hard about this, just posting the idea so that programmers who are better than I am can flame :)

**Comment by whoisj** [comment]
See #119

**Comment by JohanLarsson** [comment]
Yeah, it is the same thing, after reading it the second time. Close this as a dupe, sry guys.
