### ISSUE TITLE
VS 2019 intellisense "is" operator not suggesting enum values

### ISSUE THREAD

**Issue by Xargonus** [dotnet/roslyn#38997]
**Version Used**: 
VS 2019 16.3.1

**Steps to Reproduce**:

1. var a = DayOfWeek.Monday;
2. bool equalsMonday = a == DayOfWeek.Monday
3. bool isMonday = a is DayOfWeek.Monday

**Expected Behavior**:

Intellisense suggests DayOfWeek.{Monday, Tuesday,...} values after typing "DayOfWeek." for both line 2. and 3.

**Actual Behavior**:

Intellisense suggests this only for the 2nd line, not when using the is operator.

2:
![image](https://user-images.githubusercontent.com/26150359/66048405-c0a57700-e529-11e9-9cc1-6565868dd111.png)

3:
![image](https://user-images.githubusercontent.com/26150359/66048375-b3888800-e529-11e9-836b-6238986f8ac7.png)

**Comment by KristianJakubik** [comment]
Hi, this looks interesting. Can I take a look at this and submit PR.

**Comment by DoctorKrolic** [comment]
No longer reproducible:
![devenv_lo9lDYC2D5](https://user-images.githubusercontent.com/70431552/166983450-dc7d1ad8-e28d-42d0-af89-67b6da307709.png)

**Comment by CyrusNajmabadi** [comment]
Thanks for checking!
