### ISSUE TITLE
Special case params with few arguments

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#3900]
Something inexpensive like:

```
public struct SingleItemArray<T>
{
    internal readonly T item;

    public SingleItemArray(T item)
    {
        this.item = item;
    }

    public int Count { get { return 1; } }

    public T this[int index]
    {
        get { return item; }
    }
}
```

**Comment by svick** [comment]
Could you explain in more detail how do you imagine that would that work? Why is that `SingleItemArray<T>` even necessary, wouldn't passing just `T` be enough? And what would happen if you try to treat `SingleItemArray<T>` like a real array (e.g. by assigning it to a field of type `T[]`)?

Also, considering that it's relatively easy to work around (by writing a single parameter overload), I'm not sure this would be worth it.

**Comment by JohanLarsson** [comment]
The code is just dumb pseudo code if that was not clear. It would be an optimization for cases like:
```
public String [] Split(params char [] separator)
```
Where 97% of the times it is called with just one char.
I'm no compiler designer but my thinking is that the compiler can figure out when it can replace the array with something cheaper.

**Comment by HaloFour** [comment]
Check out #36 (Allow support for params `IEnumerable<T>` methods), specifically the conversation started in the third comment by @jaredpar.  Concept is being able to use `params` with a helper struct `Arguments<T>` which is optimized for small argument sets.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
