### ISSUE TITLE
'Generate method' action does not appear on name token following `?.`

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#39001]
**Version Used**: Visual Studio 16.3.1

'Generate method' should appear for `foo?.NonExistentMethodName`, whether `foo` is a reference or value type. It currently shows up for neither.

I ran into this in several unrelated projects when changing the type of `foo` somewhere else in the file and then wanting to generate the same methods that had been called on the type it used to have.

The workaround is to delete the `?` and add `.Value` if `foo` is a value-typed expression, generate the method, then manually undo.

**Comment by CyrusNajmabadi** [comment]
> 'Generate method' should appear for foo?.NonExistentMethodName, whether foo is a reference or value type. It currently shows up for neither.

Hrmm.. it shows up for me for reference types, but not value types.
