### ISSUE TITLE
`default` needs explicit type in if cond expr

### ISSUE THREAD

**Issue by stanciuadrian** [dotnet/roslyn#39007]
**Version Used**: Visual Studio Community 2019 Preview v16.4.0 preview 1.0

**Steps to Reproduce**:
1. Check `.NET Core 3.0 SDK` in the Individual Components section of the installer
2. Compile this .NET Core console program:
```csharp
class Program
{
    public interface Iface { }
    static Iface GetImpl() => null;
    static void Main(string[] args)
    {
        var impl = GetImpl();

        if (impl != default)
        {

        }
    }
}
```

[Sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATAAmwEYB2AWACgBvS/OwgZnwEsA7eBAMwgGM58Aktz74q+AL616xAGyDh/AOJwYAsAAcANgAoAlPgC8APnysArps0BuKXVmEALPgCyENtuIAGANoBdfBAIAOZQurai4fT4AG6BLBqahvjKqgl6NhSR9Myc+NrMCfgAhAb4KHDcFjBhFFFRNJm1dXSSTS2UrUA===) compiles this code successfully with `Default (3.3.1)` but fails on `master (23 Sep 2019)`.
 
**Expected Behavior**: compilation successful
Was there a spec change?

**Actual Behavior**:
Compilation fails on the `if` line:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0019	Operator '!=' cannot be applied to operands of type 'Program.Iface' and 'default'	default1	C:\Work\source\repos\default1\Program.cs	12	Active
```

Changing the condition to `impl != default(Iface)` fixes the error.

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/24725
