### ISSUE TITLE
ScriptState<T> should be serializable so it can be stored in non-InProc ASP.NET session state

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/roslyn#39025]
I was hoping to create an initial C# script (per website user), run it, cache its current state in ASP.NET Framework 4.7.2 session state, and then continue execution as website users type in subsequent commands (submitted to the website's serverside via AJAX).  The mechanism is described here:- https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#-continue-script-execution-from-a-previous-state

But because my website uses `Microsoft.Web.Redis.RedisSessionStateProvider` and `Microsoft.AspNet.SessionState.SessionStateModuleAsync` for session state (i.e. it's not InProc), I think that this plan is doomed to failure because `ScriptState<T>` is not serializable.

Could `ScriptState<T>` (and any other participating classes) be made to be serializable to enable this usage?

**Comment by tmat** [comment]
No, we don't have plans to make `ScriptState<T>` serializable. 

Have you considered the security implications of sending arbitrary code from a web sit to a web server and running it there?

**Comment by Andrew-Webb** [comment]
> Have you considered the security implications of sending arbitrary code from a web site to a web server and running it there?

Well, I'm new to Roslyn scripting so the next thing I was going to look into was sandboxing what I had in mind, to prevent writes / bad things in general.  I would expect that https://dotnetfiddle.net/ is sandboxing in some way.

Are you saying that the Roslyn scripting I'm using isn't or can't be sandboxed?

If not, then I guess that the hosting environment should be limited to a local app running on one's own machine(?)

**Comment by Andrew-Webb** [comment]
> Are you saying that the Roslyn scripting I'm using isn't or can't be sandboxed?

It would seem not:- https://github.com/dotnet/roslyn/issues/10830
Good to know.  I will drop the website plans.

**Comment by tmat** [comment]
It is definitely not easy to write a service that runs arbitrary code securely. What you'd want to do is to run the code in a container or a dedicated process whose privileges are restricted by ACL. Even then DOS attacks are a problem.

**Comment by Andrew-Webb** [comment]
I completely understand.  What I might do is define a very simple DSL and write an interpreter for it.  All I need is the equivalent of Linq's `Select` and `Where` on local collections of objects that have been provided by an external API.  No arbitrary code.

Thanks for your time and attention.
