### ISSUE TITLE
Quick fix for inconsistent accessbility issue doesn't help

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39039]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752631/quick-fix-for-inconsistent-accessbility-issue-does.html)._

---
The problem I got is in the following situation:
- a Response class is internal
- another class has a public property of that type

Suggested fixes are:
- Replace with methods
- Convert to full property

Expected: change visibility of the property or of the class or do something else entirely

---
#### Visual Studio Feedback System on 9/28/2019, 10:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Related to #23326. The user is looking for a quick fix for compiler error CS0053. There are several other related situations with different error IDs that would be handled by the same fixer.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  These are scenarios where completion is very suitable for fixing.
