### ISSUE TITLE
Visual Studio says that cast to double is redundant when it is not (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39042]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/750100/visual-studio-says-that-cast-to-double-is-redundan.html)._

---
<p>Visual Studio says “Cast is redundant” here:</p>
<pre>            long x = 121645100408832000;
            return ((long)(double)x == x) &amp;&amp; ((long)(double)(x + 1) == x + 1);
</pre><p>If I “Remove Unnecessary Cast” as Visual Studio suggests, then the return value changes from false to true.</p>

---
#### Visual Studio Feedback System on 9/27/2019, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by christophertrml** [comment]
Hey C# team! This is my first time trying to contribute to Roslyn, so pardon any silly questions. I've done some work tracking down this issue, and I believe I have a solution but I wanted to validate it here first before I make the necessary changes.

According to the C# spec, an explicit conversion is one where information can be lost (such is the case here, going from a `long` to a `double`). However, the conversion kind mapped in this file here: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionEasyOut.cs#L54 shows the mapping of u64->r64 to be `Implicit`. There are a couple of other mistakes in this vein as well (for example, the mapping of u64->r32 is also set to `Implicit`). 

I've made changes in a branch to set these to be explicit as per the spec, and doing so fixed this particular bug. Doing this broke about 20 tests though. I'm happy to keep going down this path and figure out why these tests broke if this is the correct solution here, but I wanted to verify with you guys that I'm going down the right path before I dedicate time to fixing tests.

Thanks!

**Comment by CyrusNajmabadi** [comment]
it's unlikely you would be changing the compiler here.  As per the language, this *is* an implicit conversion.  That is spec'ed out here: https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#implicit-numeric-conversions

> The implicit numeric conversions are:
> ...
> From `long` to `float`, `double`, or `decimal`.

The issue here is not in the compiler or language itself, but in the actual IDE feature which attempts to figure out which casts are redundant.  That feature itself needs to be fixed up to change whatever logic it is using to stop thinking that the above contains a cast to remove.

I have to go out now.  Hopefully you can find the IDE code that looks for unnecessary casts.  If you can't, i can help point you in the right direction.

Thanks!

**Comment by CyrusNajmabadi** [comment]
Also, @christophertrml thanks for looking into this.  Really excited that you would be interested in fixing this.  Roslyn can be a bit daunting at first, so we'd def like to help you get to being able to fix this issue as long as you're still interested in doing that.

CHeers!

**Comment by christophertrml** [comment]
Awesome, yeah, I was concerned I was getting too deep in the weeds with what I was finding. This is where I've been stepping through the code here: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs#L427 . If I'm understanding correctly, the specific branch I've linked to is one that wholesale marks explicit numeric casts as always necessary, so then would the solution to this problem then be another new special case in this code path that looks for implicit numeric casts that have the potential to lose precision, and always short circuit to false at that point?

**Comment by CyrusNajmabadi** [comment]
> So then would the solution to this problem then be another new special case in this code path that looks for implicit numeric casts that have the potential to lose precision, and always short circuit to false at that point?

That would seem reasonable!
