### ISSUE TITLE
Navigation bar doesn't include events defined on base interfaces

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#3904]
The events list of the navigation bar doesn't appear to include events defined on a base interface when a `WithEvents` field is of an interface type. I discovered this while trying to handle the `IWpfTextView.LayoutChanged` and `IWpfTextView.Closed` events. These events are actually defined on `ITextView` which is a base interface of `IWpfTextView`. The events defined on `IWpfTextView` itself: `BackgroundBrushChanged` and `ZoomLevelChanged` are correctly included in the list. This doesn't appear to affect events defined on base classes (e.g. `Control.MouseMove` from a `Button` instance), only events defined on base interfaces.

Here's a min repro:
```VB.NET
Interface IBase
    Event BaseEvent()
End Interface

Interface IDerived
    Event DerivedEvent()
End Interface

Public Class Class1
    WithEvents Derived As IDerived

End Class
```

And a screenshot:
![image](https://cloud.githubusercontent.com/assets/10539978/8630132/0d2d8174-2717-11e5-9dca-9a6dd8a8b11a.png)

**Comment by AnthonyDGreen** [comment]
FYI: The completion list for the `Handles` clause does correctly include events from all levels of the type hierarchy.

**Comment by Pilchie** [comment]
I feel like we've seen this before, but I don't see a dupe here on GitHub.  Is there an internal bug tracking this?

**Comment by dpoeschl** [comment]
@AnthonyDGreen This looks to be working as expected. Your repro code, and the code in the screenshot, do not have ```IDerived Inherits IBase```, so BaseEvent shouldn't be available. This matches the completion in the Handles clause.

If you update the repro to add ```Inherits IBase``` to ```IDerived```, then BaseEvent shows up in the events of Derived in the NavBar (as expected), which matches the completion in the Handles clause.

**Comment by dpoeschl** [comment]
Assigning to @AnthonyDGreen for verification.

**Comment by AnthonyDGreen** [comment]
D'oh! Sorry for the false alarm. Thanks, David!
