### ISSUE TITLE
Go To Member not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39043]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/749408/go-to-member-not-working-1.html)._

---
Sometimes the &quot;Go To Member&quot; functionality is not working. It is just showing &quot;no results&quot;. Running &quot;Go To All&quot; shows the corresponding symbols but also stuff from other files. A restart of Visual studio fixes the problem at least for some time. We are using Visual Studio 2019 16.3.1

---
#### Visual Studio Feedback System on 9/26/2019, 11:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by themobydisk** [comment]
I can reproduce this on 16.4.1.

**Comment by CyrusNajmabadi** [comment]
Going to tentatively close as being fixed by https://github.com/dotnet/roslyn/pull/42059.  We haven't seen other reports of this, and there isn't a repro to pin this down for certain.
