### ISSUE TITLE
Compilation allows method to return without assigning out variable of custom value type

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#39062]
**Version Used**: 
VS 15.9.11

**Steps to Reproduce**:
Compile the following program:
```
public static class Program
{
    public static void Main(string[] args)
    {
	DoesNotAssign(out var x);
    }

    internal static IDisposable DoesNotAssign(out CancellationToken cancellationToken)
    {
	return null;
    }
}
```

**Expected Behavior**:
Compiles with error "CS0177 The out parameter 'cancellationToken' must be assigned to before control leaves the current method"

**Actual Behavior**:
Compiles with no errors. X is set to the default cancellation token value.

**Notes**:
From my experimentation, this happens for `CancellationToken` or other custom value types (e. g. `internal struct Foo { }`, but does not happen for reference types or primitive value types (e. g. `int`, `string`).

**Comment by gafter** [comment]
A value type that contains no fields is considered definitely assigned when all of those fields are assigned.  If you have an empty struct type, it will not require assignment.

See also https://github.com/dotnet/roslyn/issues/23688#issuecomment-354521255

**Comment by gafter** [comment]
That's about right.  It depends on what is in your reference assembly.  You can use the `-features=struct` compiler flag to make the compiler pay attention to private fields from imported assemblies.  That may fix the issue for `CancellationToken` for you.

**Comment by madelson** [comment]
@gafter I'm surprised that this is considered desirable behavior. When would someone legitimately not want to assign an out parameter? This certainly burned me as it led to a bug in our codebase that could have easily been detected by the compiler.

I get that for backwards compatibility this probably cannot change to an error, but at least it feels like it should be a warning.

**Comment by gafter** [comment]
@madelson This would be considered desirable behavior when your million-line program fails to compile on the newly released version of the compiler.  We could make it a warning only by adding a separate definite assignment analysis pass in the compiler just to compute the warning.

**Comment by madelson** [comment]
@gafter a warning is what I am suggesting. And in the case of the million-line program I imagine that anything caught by this would have a high likelihood of being a bug so you'd be happy to see those warnings.

As far as whether this would need a separate pass, I can't comment on that since it feels like an implementation detail. To be honest, it's not clear to me why this "no public fields means it doesn't need to be assigned" rule is desirable in any context, or whether this logic is out-variable specific.
