### ISSUE TITLE
Quick info doesn't show nullable type when mousing over var

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#39076]
Paste the following into a C# 8 application:

```csharp
#nullable enable

namespace ConsoleApp65
{
    class C
    {
        void M()
        {
            object? o = null;
            var s = (string?)o;
        }
    }
}
```

Mouse over "var".

**Expected:** it shows System.String?
**Actual:** it shows System.String

**Comment by ryzngard** [comment]
@jasonmalinowski We have the exact opposite problem now, but I think this can safely be closed :)

**Comment by jasonmalinowski** [comment]
Hah! Good call. :smile:

**Comment by jasonmalinowski** [comment]
Actually wait a second...this is still broken:

![image](https://user-images.githubusercontent.com/201340/149597819-a858da9f-cf39-470b-86d8-d1861cb8ad9a.png)

**Comment by jasonmalinowski** [comment]
Mousing over "s" does show it's of type string?, but this isn't working right.
