### ISSUE TITLE
Extract method drops nullable annotation on explicit cast

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#39075]
Copy into a C# 8.0 app:

```
#nullable enable

namespace ConsoleApp65
{
    class C
    {
        void M()
        {
            object? o = null;
            var s = (string?)o;
            Console.WriteLine(s);
        }
    }
}
```

Invoke extract method on the "o" in the "var s..." line. Do *not* select the cast, just the o.

**Expected:** the generated method returns string? because that's the explicit cast before it.
**Actual:** it returns just string which breaks code.

**Comment by sharwell** [comment]
Why wouldn't it return `object?`?

**Comment by jasonmalinowski** [comment]
There is special logic in extract method that says if the thing you are extracting is an expression being casted, the return type of the method is the type of the cast.
