### ISSUE TITLE
Generate method drops ? on class-constrained T

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#39074]
Paste the following into a C# 8.0 app:

```
#nullable enable

namespace ConsoleApp65
{
    class C
    {
        public T? M<T>() where T : class
        {
            T? t = null;
            return M2(t);
        }
    }
}
```

Invoke Generate Method on M2.

**Expected:** M2 is generated with a parameter accepting T?
**Actual:** the parameter is just T so it doesn't work right

**Comment by CyrusNajmabadi** [comment]
Not repro.  I get:

![image](https://user-images.githubusercontent.com/4564579/199306852-9bd857b5-4064-4e2e-a284-55167a7eb870.png)
