### ISSUE TITLE
Add parameter wrap to code cleanup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39108]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/748441/add-parameter-wrap-to-code-cleanup.html)._

---
Would like to have this feature in code cleanup: https://docs.microsoft.com/en-us/visualstudio/ide/reference/wrap-align-indent-parameters?view=vs-2019

That way, this could be apply to the entire file, project or solution.

Thanks!

---
#### Jane Wu [MSFT] on 9/25/2019, 08:07 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
