### ISSUE TITLE
Use a singleton for AnalyzerActions.Empty

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#39102]
**Version Used**: Unknown

:link: https://developercommunity.visualstudio.com/content/problem/531240/occasional-outofmemoryexception.html

One of the heap dumps showed 3,486,047 instances of Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, but at most 5,000 were not empty. Using a singleton for the empty case would save a large amount of memory.

As a step past this, we could attempt avoid placing empty items in the dictionary at all, and internally treat missing the same as empty.

**Comment by mavasani** [comment]
Yep, large part of analyzer action registration code was written by John Hamby as a quick prototype. I think we need to perf tune and cleanup quite a bit of the code here.

**Comment by mavasani** [comment]
In review: https://github.com/dotnet/roslyn/pull/40691
