### ISSUE TITLE
Quick Class implementation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39110]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/737464/quick-class-implementation.html)._

---
<p>I have not yet found a shortcut like this (if it exists please direct me to it).  I would like to be able to use a shortcut keyboard command (i.e. Ctrl+K Ctrl_C : Comment) to be able to instantiate a new class with all the properties set to their respective defaults.  Something like with the cursor being in &quot;new CustomClass&quot; the user could press &quot;Ctrl+C Ctrl+I&quot; for default Class Implementation. </p><pre>CustomClass myClass = new CustomClass {
    Property1 = &quot;&quot;, // String default
    Property2 = false, // Bool default
    Property3 = DateTime.Now, // DateTime Default
    etc........
}</pre>

---
#### Jane Wu [MSFT] on 9/17/2019, 07:04 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out.  This may be better handled by copilot.
