### ISSUE TITLE
Search items from metadata in Go-To-All (Ctrl + T)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39115]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/746165/search-items-from-unimported-namespaces-ctrl-t.html)._

---
Please, add a feature to find items from unimported namespaces by pressing Ctrl + T, just like in the text editor itself.

---
#### Игорь on 9/24/2019, 00:46 PM: 

(private comment, text removed)
#### Jane Wu [MSFT] on 9/25/2019, 01:53 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

![94737-1](https://user-images.githubusercontent.com/46729679/66350517-62eda200-e910-11e9-8644-aca2b9800e45.jpg)

![94738-2](https://user-images.githubusercontent.com/46729679/66350523-654ffc00-e910-11e9-8f5d-7d1556f25ce9.jpg)

**Comment by Dreamescaper** [comment]
And where should it navigate, if that's type you don't have source for?

**Comment by jmarolf** [comment]
I either download the source using sourcelink, or decompile it. This seems like a potential way to replace some of the functionality of the object browser

**Comment by CyrusNajmabadi** [comment]
CLosing due to lack of feedback and large implementation complexity.
