### ISSUE TITLE
Avoid unnecessary casts when refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/742342/avoid-unnecessary-casts-when-refactoring.html)._

---
I love the refactoring features of Visual Studio, but I have seen multiple scenarios where it suggests adding unnecessary casts in order to do another refactoring. My most recent one being converting to a conditional expression. Here is the code before refactoring, the refactored code, and what I believe the code should be refactored to:

```
'Before Refactoring:
If useparallel Then : Me.itmNames.ItemsSource = Me.Players.AsParallel(). AsOrdered(). Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)})
Else : Me.itmNames.ItemsSource = Me.Players.Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)})
End If

'Refactored By Visual Studio 2019:
Me.itmNames.ItemsSource = If(useparallel,
	Me.Players.AsParallel(). AsOrdered(). Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)}),
	DirectCast(Me.Players.Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)}), Object))

'Refactored By Me (notice that I do not include the unnecessary DirectCast):
Me.itmNames.ItemsSource = If(useparallel,
	Me.Players.AsParallel(). AsOrdered(). Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)}),
	Me.Players.Select(Function(pd, index) New With {. Name = pd. Name, . Index = index, . ColumnWidth = Me.GetScoreColumnWidth(index)}))
```
This is, of course, not hard to change, but neither are things like removing unnecessary parentheses and some other refactorings. I just thought I would mention this as a refactoring improvement since it adds an extra method (as opposed to just making the code look prettier but still the same after being compiled).

---
#### Jane Wu [MSFT] on 9/22/2019, 11:25 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in this scenario.
