### ISSUE TITLE
SyntaxFactory.MethodDeclaration no longer accepts SyntaxKind.EndOfFileToken for semicolonToken

### ISSUE THREAD

**Issue by jkears** [dotnet/roslyn#39128]
Previous to upgrading to 3.3.1 (was on 3.1.0) I was able to pass a SyntaxKind.EndofFileToken into semicolon parameter on the SyntaxFactory.MethodDeclaration method but after the upgrade to 3.3.1  now receive a runtime exception … System.ArgumentException: 'semicolonToken'. 

**Steps to Reproduce**:
 
 SyntaxFactory.MethodDeclaration(attributeLists: SyntaxFactory.List<AttributeListSyntax>(),
              modifiers: modifiers,
              returnType: SyntaxFactory.ParseTypeName("void"),
              explicitInterfaceSpecifier: interfaceSpecifier,
              identifier: SyntaxFactory.Identifier("On" + method.Name.Replace(" ", "")),
              typeParameterList: null,
              parameterList: parameterList,
              constraintClauses: SyntaxFactory.List<TypeParameterConstraintClauseSyntax>(),
              body: SyntaxFactory.Block()
            .WithOpenBraceToken(
                SyntaxFactory.Token(SyntaxKind.OpenBraceToken))
            .WithCloseBraceToken(
                SyntaxFactory.Token(SyntaxKind.CloseBraceToken)),                
                semicolonToken: SyntaxFactory.Token(SyntaxKind.EndOfFileToken)).NormalizeWhitespace();

2. Runs perfectly on 3.1.0

3. Switch to 3.3.1 to receive an argument exception "SemiColon"
 

**Expected Behavior**:
3.1.0 sample generation...

partial void OnInitializeConstructorParameters(RoleId roleId, ApplicationId appId, string name, string description, List<Permission> permissions)
        {
        }
**Actual Behavior**:
Runtime Argument Exception "SemiColon"

**Comment by CyrusNajmabadi** [comment]
> Previous to upgrading to 3.3.1 (was on 3.1.0) I was able to pass a SyntaxKind.EndofFileToken into semicolon parameter on the SyntaxFactory.MethodDeclaration method but after the upgrade to 3.3.1 now receive a runtime exception … System.ArgumentException: 'semicolonToken'.

This sounds like something very bad to do.  Not certain why this would have ever been accepted, but it definitely violates constraints that are expected to be in place for the tree.

**Comment by jkears** [comment]
Thanks for your prompt response.
I am not sure I agree as I was able to do this previously and now no longer.  

What I am trying to generate is a method, with an empty body and I do not want, nor can I have a trailing semicolon after the body.

Perhaps there is an alternative way to achieve this simple task. Can you please advise me on the best approach.

**Comment by CyrusNajmabadi** [comment]
> Perhaps there is an alternative way to achieve this simple task

Just pass 'default' for `semicolonToken: default`.

**Comment by gafter** [comment]
If you want an "empty" body, create a block with no statements in it.
