### ISSUE TITLE
<see> tags in XML docs should be clickable links in the IntelliSense popups.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39139]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/721266/tags-in-xml-docs-should-be-clickable-links-in-the.html)._

---
What it says on the tin :)

---
#### Jane Wu [MSFT] on 9/3/2019, 07:50 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
This was implemented in #35667

**Comment by truegoodwill** [comment]
For anyone who wants to use a hyperlink, the tag `<see href="https://mylink.com" />` will work ... you just don't get `href` suggested in intellisense yet.
