### ISSUE TITLE
System.Runtime.CompilerServices.NullableAttribute is not returning if there are no even properties with null and without null.

### ISSUE THREAD

**Issue by pavinan** [dotnet/roslyn#39133]
**Version Used**:  netcoreapp3.0, sdk - 3.0.100

**Steps to Reproduce**:
If a class has 3 nullable props and 3 non-nullable props ``NullableAttribute`` is **returned**.
But if a class has 3 nullable and 2 non nullable ''NullableAttribute'' is **not returned**.

Below program will work fine. 
But if you un-comment ``Content2`` or comment out ``dummy`` this will give 0 attrs.

That is everything must be even.

```csharp
class Program
{
    static void Main(string[] args)
    {
        var props = typeof(Todo).GetProperties();

        foreach (var propItem in props)
        {
            var attrs = propItem.GetCustomAttributes();
        }
    }
}


public class Todo
{
    public string? Content { get; set; }
    //public string? Content2 { get; set; }
    public Test? MyProperty { get; set; }

    public string dummy { get; set; } = string.Empty;
    public Test dummy2 { get; set; } = default!;
}

public class Test
{
    public int MyProperty { get; set; }
}
```

**Expected Behavior**:
``System.Runtime.CompilerServices.NullableAttribute`` must be returned for nullable properties.

**Actual Behavior**:
``System.Runtime.CompilerServices.NullableAttribute`` is not returned for nullable properties.

**Comment by gafter** [comment]
You appear to be assuming something about the encoding of nullability annotations.  We should point point you to our actual documentation for how these things are represented.

**Comment by cston** [comment]
@pavinan, the compiler emits a NullableContextAttribute(value) on the class with the most common value that would be used for NullableAttributes on the members, and the NullableAttributes with that value are skipped (see [nullable-metadata](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md)).

In the example above, when `Content2` is commented out, the most common NullableAttribute value for the members is 1 so a `[NullableContext(1)]` is emitted on the class and the `[Nullable(2)]` attributes on the properties are also emitted. When `Content2` is uncommented, the most common NullableAttribute value is 2 so a `[NullableContext(2)]` is emitted on the class so the `[Nullable(2)]` attributes on the properties are not needed.

**Comment by pavinan** [comment]
@cston Ok I understood now. 
I need to check NullableContextAttribute before checking Nullable attribute. 
Thanks for explanation.

**Comment by cston** [comment]
@pavinan, just to clarify, a NullableAttribute on the member will override any NullableContextAttribute on that member or on the containing type, so it's necessary to check for NullableAttribute in all cases.

**Comment by pavinan** [comment]
@cston ok good to know.
