### ISSUE TITLE
[Proposal] String interpolation

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/roslyn#39132]
An option to expand the string interpolation to a call other than string.Format would be nice to have.

For example, I want
`logger.LogInformation($"Hello {name}")`
to be expanded to
`logger.LogInformation("Hello {0}", name)`
rather than
`logger.LogInformation(string.Format("Hello {0}", name))`

Compiler can require the method to have a specific signature and annotated with an attribute for this.

**Comment by RikkiGibson** [comment]
Please put language proposals in https://github.com/dotnet/csharplang.

**Comment by HaloFour** [comment]
You can already achieve this by having the method accept `FormattableString` instead of `String`.

**Comment by nvmkpk** [comment]
It is wokring, I did not know something like this already exists. But why doesn't BCL make use it?

**Comment by RikkiGibson** [comment]
will close assuming this is addressed. If you'd like [corefx](https://github.com/dotnet/corefx) to start using FormattableString in more APIs please find or open an issue on their side.
