### ISSUE TITLE
Add ability to customize the xml comments format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39141]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/406779/add-ability-to-customize-the-xml-comments-format.html)._

---
<p>I am using /// to generate documentation but would like to alter the template / snippet that is inserted.  I see there might be a way to do it with custom snippets, but seems like it should be a built in option.</p>

---
#### Jane Wu [MSFT] on 12/13/2018, 05:51 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Dinakar Nethi [MSFT] on 1/4/2019, 03:28 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by kendrahavens** [comment]
I'd like to know if multiple users are interested in making this experience easier.

**Comment by CyrusNajmabadi** [comment]
Clsing out due to lack of feedback.
