### ISSUE TITLE
Refactoring "Compute constant value" not available on constant-only-values.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39142]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/759053/refactoring-compute-constant-value-not-available-o.html)._

---
<p>Hi,</p><p>Today, there is a refactoring available to <em>Compute constant value</em> if you have an expression like below:</p><pre>var foo = Some.Namespace.With.A.Constant + &quot;my own string&quot;;</pre> <p>However, this does not appear on the simpler variant like this:</p><pre>var foo = Some.Namespace.With.A.Constant;</pre> <p>In practice, I can just append <strong>+&quot;&quot;</strong> to the value and then use the refactoring, but it should not be necessary.</p> <p>Best regards, he who tries to get rid of some inter-solution dependencies in old stuff and wants to save some time next time.</p>

---
#### Jane Wu [MSFT] on 10/8/2019, 05:29 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is not a Roslyn feature.  It is provided by resharper: https://www.jetbrains.com/help/resharper/Reference__Options__Languages__CSharp__Context_Actions.html
