### ISSUE TITLE
<code> tags in XML comments should render as monospaced, syntax highlighted code in the IntelliSense popups.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39140]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/721265/tags-in-xml-comments-should-render-as-monospaced-s.html)._

---
What it says on the tin :)

---
#### Jane Wu [MSFT] on 9/3/2019, 07:50 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
I'm going to treat this as three separate issues, with this issue focused on only one of them.

1. `<code>` elements should render with a monospaced font. This was already implemented as part of #35667
2. Newlines and/or indentation in `<code>` elements should be preserved (similar to the difference between `<pre>` and `<tt>` in HTML) ⬅️ **This issue**
3. Contents of a `<code>` element should be syntax highlighted (moved to #39154)

**Comment by sharwell** [comment]
This issue (specifically the subset identified in my previous comment) was fixed by #53140
