### ISSUE TITLE
Degraded IntelliSense on RHS of await

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#39150]
**Version Used**:  VS 16.4 P1

**Steps to Reproduce**:
```csharp
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp24
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var request = new Request();
            var meh = await request$$.ReadAsStreamAsync();
        }
    }

    class Request
    {
        public Task<Stream> ReadAsStreamAsync() => null;
    }
}
```
1. Place cursor at `$$`
2. Type `.`
3. IntelliSense window does not open and cannot be prompted with `CTRL + Spacebar`

**Expected Behavior**:
IntelliSense window opens, suggesting members of `request`

**Actual Behavior**:
IntelliSense window denies me

**Comment by ivanbasov** [comment]
It seems that the issue is caused by introducing range expressions: position between dots now is within a RangeExpression. Therefore, we do not expect an intellisense here. And we cannot get recommendations for intellisense from the semantic model. I'd resolve this issue as by design but would like to get a confirmation from the compiler team. @agocke ?

**Comment by CyrusNajmabadi** [comment]
This is definitely *not* be design.  We need to support this case.  It's SOP that for intellisense the code may be in a form that parses differently than what we'd like.  From teh user perspective, they're not typing a range, they're just hitting dot, expecting an appropriate value to appear there.

**Comment by Suchiman** [comment]
@ivanbasov without `await`, this scenario works and this issue predates ranges IIRC, i only recently got annoyed enough with it to report it. Basically, this breaks my muscle memory when i work with `await` but otherwise it works fine

**Comment by ivanbasov** [comment]
> @ivanbasov without `await`, this scenario works and this issue predates ranges IIRC, i only recently got annoyed enough with it to report it. Basically, this breaks my muscle memory when i work with `await` but otherwise it works fine

Thank you, @Suchiman ! Let me see without `await`

**Comment by agocke** [comment]
The parse tree here is appropriate. I'll take no position on the user scenario, though
