### ISSUE TITLE
Explicit interface implementation 'RefCustomModifiers' is not inherited

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#39167]
https://github.com/dotnet/roslyn/blob/82f09c4e6067d3a164000f1acf355ee8e774fad5/src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Symbols/PlaceholderMethodSymbol.cs#L169-L178

**Comment by gafter** [comment]
Can you please explain what "it" is in "it does not currently work", or otherwise elaborate on what the issue is?

**Comment by jcouv** [comment]
@sharwell I'm able to remove this property/block from the code and still compile roslyn with `build.cmd`. So I think the issue is now fixed.
Can you confirm this was indeed the correct interpretation of the issue?
