### ISSUE TITLE
C#, Inconsistant Label Indentation when Formatting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/763973/c-inconsistant-label-indentation-when-formatting.html)._

---
Formatting a section or document which contains labels can result in inconsistant indentation of labels. If a label followed a non-bracketed if statement, the label will be indented further than if it follows a a bracketed if statement

Sample 1:

```csharp
    void Foo()
    {
        if (true)
        {
            Console.WriteLine("True");
        }

    Cleanup:
        // Do Cleanup
        return;
    }
```

Sample 2:

```csharp
    void Bar()
    {
        if (true)
            Console.WriteLine("True");

        Cleanup:
        // Do Cleanup
        return;
    }
```

---
#### Visual Studio Feedback System on 10/8/2019, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't find any way to repro this.
