### ISSUE TITLE
Intellisense conditional conversion option finnicky

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39173]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/757387/intellisense-conditional-conversion-option-finnick.html)._

---
[regression] [worked-in:16.1]
```
if (! String.IsNullOrWhiteSpace(var))
return var
else
return var2;
```

It offered to simplify the String and convert to conditional. I simplified String first and then it lost the option to change the conditional. As soon as I converted string back to String, the option came back, I used it, then I changed String back to string.

---
#### Visual Studio Feedback System on 10/3/2019, 02:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.  Both options showed up all the time no matter what order of operations i went in.
