### ISSUE TITLE
C# Editor, view scrolling in error when moving selected lines up/dn.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39170]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/761825/c-editor-view-scrolling-in-error-when-moving-selec.html)._

---
Use the following batch file to generate foo.cs
```
@echo off
setlocal
echo>>foo.cs class C
echo>>foo.cs {
call :GEN_FIELDS
call :GEN_METHODS
echo>>foo.cs }
goto :EOF

:GEN_FIELDS
echo>>foo.cs #region fields
for /l %%i in (1,1,100) do echo>>foo.cs int int%%i;
echo>>foo.cs #endregion
goto :EOF

:GEN_METHODS
for /l %%i in (1,1,100) do call :GEN_METHOD %%i
goto :EOF

:GEN_METHOD
echo>>foo.cs int fn%1() 
echo>>foo.cs {
echo>>foo.cs return int%1;
echo>>foo.cs }
goto :EOF
```

Add foo.cs to some project. I used a .NET Console project, but anything C# would do.

Open the file.
Hold Ctrl and type in order A K F M A Home
End
Ctrl-M, CTRL-M (to unfold the class).
Move to beginning of line, say, 449 (i.e. fn87).
Shift-Down once, to select.
Alt-Up a few times. Notice how the view (in error) scrolls upwards.
Now try either Alt-Down, or even Undo (Ctrl-Z). The view _continues_ to scroll upwards!

Expected: I shouldn't have to write this, but... the view should obviously not scroll like this unless it's required to keep selection/caret visible.

---
#### Visual Studio Feedback System on 10/7/2019, 01:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tamlin-mike** [comment]
Since it seems you might have problems to decipher this (over three months without any change in status could indicate that), let me elaborate:

CTRL+A = Edit.Select All
CTRL+K, CTRL+F = Edit.FormatSelection (just for good measure)
CTRL+M, CTRL+A = Edit.CollapseAllOutlining
CTRL+M, CTRL+M = Edit.ToggleOutliningExpansion

Additionally I suggest you add the "Bug" label to this, since it most certainly is a bug.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  This is editor/platform.  @olegtk for awareness in case you want to investigate.
