### ISSUE TITLE
VB.NET code pattern snippet works within interpolated strings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39176]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/743715/vbnet-code-pattern-snippet-works-within-interpolat.html)._

---
Place cursor of vb.net editor before the closing quote in string below and press Tab key
Dim SQLText As String=$&quot;SELECT&quot;

---
#### Visual Studio Feedback System on 9/23/2019, 11:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as this is hte legacy snippet system we are not investing in.
