### ISSUE TITLE
C# Auto Format not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39175]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/746119/c-auto-format-not-working.html)._

---
Just started using C#.  None of the auto formatting works as does in VB.  For example braces aren't indented.  None of the code is properly indented either after typing.  All &quot;Auto Format&quot; options are on under Tools.... Options.... Text Editor... C#... Code Style... Formatting.  There is also no EditorConfig file.  This happens on all projects.   VB properly auto formats.  See attachments for screenshots. Visual Studio Enterprise 2019 Version 16.3.0. I did search various forums, but could not find any information.

---
#### Visual Studio Feedback System on 9/25/2019, 03:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
I have been unsuccessfully able to repro this issue and have asked the user for more details in the original ticket.
