### ISSUE TITLE
switch expression "no best type found" conflicts with IDE0007 C# use 'var' instead of explicit type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39171]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/759620/switch-expression-no-best-type-found-conflicts-wit.html)._

---
First of all I have a switch expression that returns instances of classes that all have a common superclass, so I would expect the switch expression to return the common superclass type instead of having a &quot;no best type found&quot; error.

Secondly, if I manually specify the type of the variable to put the result of the switch expression in, I get the IDE0007 suggestion.  If I follow the suggestion I'm back at the &quot;no best type found&quot; error.

---
#### Visual Studio Feedback System on 10/7/2019, 02:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
This sounds like target-typed switch working as expected. Perhaps on the IDE side the "use var instead of explicit type" should be disabled in this scenario. Do we provide a way for the IDE to know that the switch expression is target-typed?

**Comment by mavasani** [comment]
@allisonchou mentioned she was looking at this..
