### ISSUE TITLE
C# reference count shown as 0 for operators <, >

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39177]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/742322/c-reference-count-shown-as-0-for-operators.html)._

---
Shows:
        0 references
        static public bool operator &lt;(OrderingMeasure a, OrderingMeasure b)
Although it's used

---
#### Visual Studio Feedback System on 9/23/2019, 01:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Related to #30210
