### ISSUE TITLE
C#, Simplify init refactoring also for arrays

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39218]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/768513/c-simplify-init-refactoring-also-for-arrays.html)._

---
```
class RFE_SimplifyInit
{
  struct S { public int a, b; }
  void working()
  {
    S s = new S();
    s.a = 1;
    s.b = 2;
  }
  void rfe()
  {
    int[] rg = new int[2];
    rg[0] = 1;
    rg[1] = 2;
  }
}
```
Working example:
- Place cursor on line `S s =`.
- Invoke QuickActions.

Result: You get the option `Object initialization can be simplified`, and when executed you get the expected
```
S s = new S
{
  a = 1,
  b = 2
};
```

RFE:
- Place cursor on line `int[] rg =`.
- Invoke QuickActions.

Result: No option to simplify.

Expected: Option to simplify, with result
```
int[] rg = new int[2]
{
  1,
  2
};
```

Considerations, expected limitations:
For implementation simplicity, and to retain sematical correctness and sequence points in case init expressions are more complex, only consider the refactoring when array-elements assignments index-order is both sequential and starting from zero.

---
#### Jane Wu [MSFT] on 10/10/2019, 00:14 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
It can do even better.  It can just refactor this to:

```c#
int[] rg = { 1, 2 };
```

That said, i question how of this happens to be useful enough to need a dedicated fix.

**Comment by CyrusNajmabadi** [comment]
This works now.  You get offered to make this a collection expression.
