### ISSUE TITLE
'Generate Equals' should use lifted == operator on nullables if it would have used == for the underlying type

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#39236]
**Version Used**: 16.3.4, 16.4p1

In any situation where `==` is *already* being generated as the most preferable option for a value type, I believe `==` would be the most preferable option for the nullable version of that value type:

Actual:

```cs
class Foo
{
    public decimal A { get; }
    public decimal? B { get; }

    public override bool Equals(object? obj)
    {
        return obj is Foo foo &&
               A == foo.A &&
               EqualityComparer<decimal?>.Default.Equals(B, foo.B);
    }
}
```

Expected:

```cs
class Foo
{
    public decimal A { get; }
    public decimal? B { get; }

    public override bool Equals(object? obj)
    {
        return obj is Foo foo &&
               A == foo.A &&
               B == foo.B;
    }
}
```

Would you accept a PR? I recently implemented https://github.com/dotnet/roslyn/issues/31984, so my head is still in this space.

**Comment by CyrusNajmabadi** [comment]
I would be fine with this.

**Comment by sharwell** [comment]
Sounds good to me
