### ISSUE TITLE
Rename tracking is active but uninvokable in ASP.NET projects

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#39239]
**Steps to Reproduce**:

1. Create a new ASP.NET project of some kind that has a .razor file.
2. In the Razor file, go into the @code section or a @ expression, and change an identifier name.

**Expected Behavior**: No rename tracking is active.

**Actual Behavior**: we do our dotted outline showing it's active:

![image](https://user-images.githubusercontent.com/201340/66689472-dd376280-ec3f-11e9-9579-a1e50cd4eda1.png)

However, the command can't actually be invoked.

Seems we should either make it invokable (hard?) or at least don't track renames in buffers where the command is disabled.

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of feedback on this.  Rename in razor is also owned by razor now.
