### ISSUE TITLE
Able to navigate to generated file in blazor app

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#39241]
In creating a new blazor app, with no modifications, I was getting errors in *.g.cs files and able to click the error list to navigate to them. 

![image](https://user-images.githubusercontent.com/475144/66690068-98f99180-ec42-11e9-82fc-ad0a851828a2.png)

**Comment by tmat** [comment]
This is a known issue.

/cc @nguerrera

**Comment by CyrusNajmabadi** [comment]
This should go through razor
