### ISSUE TITLE
Signature help sometimes fails to wrap, preventing the current parameter from being seen

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#39255]
**Version Used**: VS 16.3.4

Repro:

```cs
public static class C
{
    public static void M()
    {
        var longVariableNameForSpacing = Method([||]
    }

    public static object Method(
        System.Collections.Generic.Dictionary<string, string> a,
        System.Collections.Generic.Dictionary<string, string> b,
        System.Collections.Generic.Dictionary<string, string> c,
        System.Collections.Generic.Dictionary<string, string> d,
        System.Collections.Generic.Dictionary<string, string> e)
    {
        return null;
    }
}
```

![image](https://user-images.githubusercontent.com/8040367/66706586-8c3c7280-ed02-11e9-9962-00880c4d2de7.png)

Pixel density is at 125% for these monitors, resolution 2560x1440.

**Comment by CyrusNajmabadi** [comment]
Note: i'm seeing tis all the time as well when coding in roslyn.  it's bad and basically makes sig help practically useless.   I'm on:

![image](https://user-images.githubusercontent.com/4564579/66706439-59d14c00-ece7-11e9-8ee9-dfaee8997423.png)

Here's an example:

![image](https://user-images.githubusercontent.com/4564579/66706442-6786d180-ece7-11e9-80cc-74fac158d6b8.png)

This is not useful.  And the moment you go past the first few paramters, you get nothing to help you.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph for visibility.  This is a bad regression in a core scenario.  I've felt this issue acutely in the last few days after upgrading.  You don't realize how important those signatures are until they're gone :D

**Comment by sharwell** [comment]
@CyrusNajmabadi we have been tracking this issue from other sources. We'll mark it as an appropriate duplicate during the work week.

**Comment by olegtk** [comment]
Not a known issue, please route to the editor, @jinujoseph. Thanks!
Just to confirm - is it a regression in 16.3 or 16.4?

**Comment by jnm2** [comment]
I first noticed it in 16.3, but I don't know when the regression started.

**Comment by jinujoseph** [comment]
Routed [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002020)
