### ISSUE TITLE
The "Convert to conditional expression" refactoring is sometimes mislabeled

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#39260]
**Version Used**: VS 16.4.0 Preview 1.0

**Steps to Reproduce**:

Have code like the following:

```c#
if (AreSimilarCore(node1, node2))
{
    return true;
}

return false;
```

Invoke refactoring on the `if`.

**Actual Behavior**:

VS offers to simplify the code, with the suggestion being labeled as "Convert to conditional expression", even though the refactored code does not contain the conditional expression:

![](https://user-images.githubusercontent.com/287848/66714599-bbadb680-edb8-11e9-80e5-3bec4d6d4164.png)

**Expected Behavior**:

The refactoring is labeled accurately, e.g. with "Simplify if statement".

**Comment by sharwell** [comment]
Interesting. The code fix is converting the code to this conditional expression:

```
return AreSimilarCore(node1, node2) ? true : false;
```

which is then getting reduced to the form seen in the preview. It may be difficult to know in advance whether or not this simplification applies, so perhaps a more general message like the following would be better?

> Simplify conditional logic

**Comment by CyrusNajmabadi** [comment]
> Another possibility is the "Simplify if statement" proposed by @svick above.

That would be my preference.  Thanks :)
