### ISSUE TITLE
Publish packages to Azure DevOps public feeds instead of MyGet

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#39279]
**[dotnet5](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet5)** feed

- Microsoft.CodeAnalysis.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Common.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Compilers.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Scripting.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Scripting.Common.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Workspaces.Common.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Workspaces.MSBuild.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.CodeStyle.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.Features.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.Scripting.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.Workspaces.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.VisualBasic.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.VisualBasic.CodeStyle.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.VisualBasic.Features.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.VisualBasic.Workspaces.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Build.Tasks.3.4.0-beta3-final.nupkg
- Microsoft.Net.Compilers.3.4.0-beta3-final.nupkg
- Microsoft.Net.Compilers.Toolset.3.4.0-beta3-final.nupkg
- Microsoft.NETCore.Compilers.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Debugging.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.PooledObjects.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Features.3.4.0-beta3-final.nupkg

[**vssdk**](https://dev.azure.com/azure-public/vside/_packaging?_a=feed&feed=vssdk) feed

- Microsoft.CodeAnalysis.EditorFeatures.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.EditorFeatures.Common.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.EditorFeatures.Text.3.4.0-beta3-final.nupkg
- Microsoft.VisualStudio.LanguageServices.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.CSharp.EditorFeatures.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.InteractiveHost.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.EditorFeatures.Wpf.3.4.0-beta3-final.nupkg

[**vs-impl**](https://dev.azure.com/azure-public/vside/_packaging?_a=feed&feed=vs-impl) feed

- Microsoft.VisualStudio.IntegrationTest.Utilities.3.4.0-beta3-19514-03.nupkg
- Microsoft.CodeAnalysis.LanguageServer.Protocol.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.Apex.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.CodeLens.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.Debugger.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.FSharp.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.IntelliTrace.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.ProjectSystem.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.Razor.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.TypeScript.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.UnitTesting.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.ExternalAccess.Xamarin.Remote.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Remote.Razor.ServiceHub.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Remote.ServiceHub.3.4.0-beta3-final.nupkg
- Microsoft.CodeAnalysis.Remote.Workspaces.3.4.0-beta3-final.nupkg
- Microsoft.VisualStudio.LanguageServices.LiveShare.3.4.0-beta3-final.nupkg
- Microsoft.VisualStudio.LanguageServices.Razor.RemoteClient.3.4.0-beta3-final.nupkg

TODO:
- Should Feetures/EditorFeatures be published to `dotnet-core` or `vssdk` feed?

**Comment by tmat** [comment]
@jaredpar @jasonmalinowski Makes sense?

**Comment by jasonmalinowski** [comment]
Only edit I see is EditorFeatures.Wpf should go in vssdk feed -- even though it doesn't expose an API it's MEF composable, and it's something say VS for Mac consumes. And in practice LanguageServices has a dependency *on* that, so it's odd the dependency would leave the vssdk feed.

The rest looks good.

**Comment by tmat** [comment]
@jasonmalinowski Updated.

**Comment by jasonmalinowski** [comment]
Looks good to me then.

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/43242

**Comment by dibarbet** [comment]
Resolved in https://github.com/dotnet/roslyn/pull/45416
