### ISSUE TITLE
'Add parameter to method' Quick Action can add wrong parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39270]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/772301/add-parameter-to-method-quick-action-can-add-wrong.html)._

---
The 'Add parameter' Quick Action can add the wrong parameter in specific situations.
For instance, this will happen when an existing parameter accepts a base class of the passed argument type. 
Is this behaviour by design, or can this be fixed/improved?

Here is some code sample to reproduce the problem:
```
class BaseClass { }

class MyClass : BaseClass
{
    void TestFunc()
    {
        MyClass param1 = new MyClass();
        int newparam = 1;

// The 'Add parameter' Quick Action on the following method call adds the wrong parameter.
        // It should add an 'int newparam' parameter.
        // But instead it adds a 'MyClass param11' parameter.
        MyFunc(param1, newparam);
    }

void MyFunc(BaseClass param1) { }
}

```

---
#### Visual Studio Feedback System on 10/10/2019, 08:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
I have reproduced the issue. @CyrusNajmabadi do you know if it is by design or just a bug?

**Comment by CyrusNajmabadi** [comment]
Seems just like a bug to me.
