### ISSUE TITLE
Disable /warnAsError in non-Correctness runs

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#39278]
I have had a few instances lately where my build is fine locally, but I get warnings in CI due to nullability changes in the base branch. This means I have to merge the base branch in, fix it locally, and push back up before getting any test results.

It feels like we might as well put warnAsError in the Correctness build *only* so this kind of thing does not prevent developers from getting test results.

/cc @jaredpar @JoeRobich @dotnet/roslyn-infrastructure

**Comment by sharwell** [comment]
It does run the risk of having an architecture or platform difference let critical warnings get through. The correctness build only runs one configuration.
