### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "cmdidErrorListSetSeverityHidden|ButtonText"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#39286]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
&Silent

File Name:
VisualStudio\Core\Def\xlf\Commands.vsct.xlf

==========================================
Query:
Is silent translatable in this context?
It seems to be a command (other strings):
Now interpreted as "not logged". Please confirm or advise. This concerns the following strings: 
Silent 0; "cmdidErrorListSetSeverityHidden|LocCanonicalName"
Silent 0; "cmdidSetSeverityHidden|LocCanonicalName"
0; "cmdidErrorListSetSeverityHidden|ButtonText"
0; "cmdidErrorListSetSeverityHidden|LocCanonicalName"

**Comment by sharwell** [comment]
@mavasani I believe we should be using "Refactoring" here for consistency with Tools&rarr;Options.

**Comment by mavasani** [comment]
> Is silent translatable in this context?

No, all the context menu commands here map to the exact string value that will added in the .editorconfig file by that command.

> I believe we should be using "Refactoring" here for consistency with Tools→Options.

I have been part of internal email threads where the preferred editorconfig term was "silent". If we decide to change this, then we need to update all the other tooling where we auto-generate silent in editorconfig files and also update the unit tests accordingly.

**Comment by PDostalek** [comment]
@mavasani  Could you please provide us strings that should not be translated in this command menu ? We would like to check consistency. Thanks

**Comment by PDostalek** [comment]
Are we talking about strings from this file ? VisualStudio\Core\Def\xlf\Commands.vsct.xlf

**Comment by mavasani** [comment]
@PDostalek All the commands starting with `cmdidErrorListSetSeverity` in Commands.vsct should not be translated.

**Comment by PDostalek** [comment]
I will make changes according to your comment. Thanks !

**Comment by janbaltus** [comment]
@mavasani 
all 3 examples need to be locked or only command  cmdidErrorListSetSeverityDefault|CommandName?

0; "cmdidErrorListSetSeverityDefault|ButtonText"
0; "cmdidErrorListSetSeverityDefault|CommandName"
0; "cmdidErrorListSetSeverityDefault|LocCanonicalName"

**Comment by cristianosuzuki77** [comment]
@wli3

**Comment by wli3** [comment]
@sharwell @mavasani please work with @janbaltus @cristianosuzuki77 to resolve the issue soon. We are closing on 16.8 loc

**Comment by mavasani** [comment]
@janbaltus @cristianosuzuki77 Yes, all those strings should be locked and not localized.
