### ISSUE TITLE
Blazor preview 5.  When using intellisense to create an override in the @functions block the entire block disappears.  

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39294]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/591477/blazor-preview-5-when-using-intellisense-to-create.html)._

---
Type my function and then 

```
@functions
{

OrganizationView[] oragnizations;
    override oni

}
```

At this point I have the overrides list up in intellisense so I hit tab.  After that I get this....

```
@functions
{}
```

And loose all that I typed before.

---
#### Visual Studio Feedback System on 6/3/2019, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Robert Haken on 6/3/2019, 04:25 PM: 

Same here.
#### Visual Studio Feedback System on 6/3/2019, 10:31 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

#### Visual Studio Feedback System on 10/10/2019, 10:15 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
![RazorPage-eatCommit](https://user-images.githubusercontent.com/1408396/66857150-8382b100-ef3b-11e9-9f02-05b0bbb58eef.gif)

![RazorComponent-commit-formatting](https://user-images.githubusercontent.com/1408396/66857151-841b4780-ef3b-11e9-965f-94db29b9e36d.gif)

![RazorPage-commit-formatting](https://user-images.githubusercontent.com/1408396/66857152-841b4780-ef3b-11e9-98a9-019130651f3f.gif)

**Comment by timheuer** [comment]
Adding Blazor example where also overrides are essential to dev experience.

![blazorformat](https://user-images.githubusercontent.com/4821/67132711-7e816400-f1be-11e9-8815-54efeb3e9637.gif)

**Comment by dpoeschl** [comment]
I'm not seeing this delete code, but I do see it indenting incorrectly. I've tried both repros (the original and @sharwell's) and only see indentation issues (similar to what @timheuer's gif shows). @sharwell Does it still delete code for you on latest? If so, can you help me repro sometime? Thanks!

**Comment by dpoeschl** [comment]
Ping @sharwell to see if this is still deleting code. I only see the formatting issues.

**Comment by sharwell** [comment]
@dpoeschl I was never able to reproduce this. I just copied the images from the original feedback so they are visible to other users.

**Comment by jasonmalinowski** [comment]
[I definitely reproduced the dropping of the keywords during some dogfooding.](https://twitter.com/jasonmalinowski/status/1205734194858483715?s=20)

**Comment by CyrusNajmabadi** [comment]
Closing out as these experiences are owned by the razor team.
