### ISSUE TITLE
[portable pdb] DateTime constants - validate that we don't use local date time values

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#3929]

**Comment by ManishJayaswal** [comment]
@tmat @tannergooding what validation needs to happen here? Can we close this issue?

**Comment by tannergooding** [comment]
@ManishJayaswal, I believe we just need a test that produces a portable pdb and validates that: `new MetadataReader().GetBlobReader().ReadDateTime().Kind == DateTimeKind.Utc`

I'm working on adding such a test to `Roslyn.Compilers.CSharp.Emit.UnitTests` now.

**Comment by tannergooding** [comment]
This was resolved with PR #9374
