### ISSUE TITLE
Updating dotnet/versions occasionally errors with 'Update is not a fast forward'

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#39308]
Example builds:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3145509 
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3143639

When publishing build info updates to dotnet/version in quick succession as done here
https://github.com/dotnet/roslyn/blob/master/eng/publish-assets.ps1#L122
it will sometimes fail with
```
Publishing E:\A\_work\3542\s\artifacts\packages\Release\NonShipping to channel dev16.4
Error updating versions: Could not update dotnet/versions 'heads/master' to '4e2d35b8002d79592594d73903d830f8db1ed632': Update is not a fast forward
   at Microsoft.DotNet.VersionTools.Automation.GitHubApi.GitHubClient.<PatchReferenceAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.VersionTools.Automation.GitHubVersionsRepoUpdater.<UpdateBuildInfoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPublish.Program.<Go>d__1.MoveNext() in /_/src/Tools/RoslynPublish/Program.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPublish.Program.Main(String[] args) in /_/src/Tools/RoslynPublish/Program.cs:line 19
```

The tool [queries ](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.VersionTools/Automation/GitHubVersionsRepoUpdater.cs#L81)the master branch for latest commits, then applies a commit with the new build info.  When this happens multiple times in succession, occasionally the query for the latest commits will not return the latest commit.

Example:
In [this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3143639), we see
```
Publishing E:\A\_work\3542\s\artifacts\packages\Release\Shipping to channel dev16.4
Publishing E:\A\_work\3542\s\artifacts\packages\Release\NonShipping to channel dev16.4
Error updating versions: Could not update dotnet/versions 'heads/master' to '4e2d35b8002d79592594d73903d830f8db1ed632': Update is not a fast forward
```

Looking at the master branch log, we see a successful [commit ](https://github.com/dotnet/versions/commit/8db4b41f383c084eb31ccd8f0de9da2824107c99) for the first dev16.4 channel publish, but no further successful commits.  Looking at the [hash of the failed commit](https://github.com/dotnet/versions/commit/4e2d35b8002d79592594d73903d830f8db1ed632), we see that it's parent is actually `1dc94d9` which is the commit prior to applying the first successful commit.  The parent commit should be the id of the previous commit, `8db4b4`

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3145509 has a similar failure, but it published two successful commits before failing.  

It seems like we need to add a delay in between attempts to publish to dotnet/versions to account for github delays in processing.

**Comment by dagood** [comment]
There's an underlying bug in VersionTools here: https://github.com/dotnet/buildtools/issues/2221. It *should* be doing retries automatically in this situation. Now that the package lives in dotnet/arcade it should be easy to submit a fix if you'd like.

The ref update can also collide with other builds doing their publishing, so fixing that bug will help there too.

**Comment by dibarbet** [comment]
Closing, was resolved by https://github.com/dotnet/arcade/pull/4320
