### ISSUE TITLE
Optimize boxing of boolean values

### ISSUE THREAD

**Issue by footcha** [dotnet/roslyn#39314]
It happens rather often in applications that there is implicit conversion `boolean->object` that causes boxing (and memory allocation in a heap) of a boolean value each and every time the conversion is called. This can produce quite significant memory allocations if such conversions happen in a hot path. Is it worth optimizing this specific conversion at compile time by a compiler? Bellow there is a workaround in C# however compiler can solve this more conventionally by emitting similar byte code at compile-time.

```csharp
public static class BoolExtensions
{
    private static readonly object boxedFalse = false; // one-time boxing
    private static readonly object boxedTrue = true; // one-time boxing

    public static object Boxed(this bool value)
    {
        return value ? boxedTrue : boxedFalse;
    }
}
```

**Comment by svick** [comment]
Related discussion about doing  this at the CLR level: https://github.com/dotnet/coreclr/issues/8423.

**Comment by gafter** [comment]
This is not an optimization.  It is a change that would cause the compiler and/or runtime to fail to obey its specification.

The language specification says

> Boxing a value of a _non_nullable_value_type_ consists of allocating an object instance and copying the _non_nullable_value_type_ value into that instance.

The specification is crystal clear that allocation of an object instance is required.
