### ISSUE TITLE
Invalid suggestion: use var instead of explicit type

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn#39313]
**Version Used**: 16.4p2

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1427284/66927603-12580200-effe-11e9-8326-6c389c7a9455.png)

Code like that, where the .Parent property returns `PackagePart?`.

**Expected Behavior**:
No IDE0007 message

**Actual Behavior**:
IDE0007 message.

When the quick fix runs, and it puts `for(var cursor = this ...`, yields a different warning since it'd be trying to assign a nullable to a non-nullable.

**Comment by allisonchou** [comment]
This should be fixed by #40755 in 16.6.
