### ISSUE TITLE
Naming rule fix generates code with errors

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/roslyn#39317]
**Version Used**: 16.4p2

**Steps to Reproduce**:

Code with the following along with an `.editorconfig` rule (based on the Roslyn one):

```
# Static readonly fields are PascalCased
dotnet_naming_rule.static_readonly_fields_should_be_pascal_case.symbols                               = private_static_readonly_field_symbols
dotnet_naming_rule.static_readonly_fields_should_be_pascal_case.style                                 = pascal_case_style
dotnet_naming_rule.static_readonly_fields_should_be_pascal_case.severity                              = warning
```

![image](https://user-images.githubusercontent.com/1427284/66938671-9ff01d80-f00f-11e9-901f-fffb0c49713e.png)

**Expected Behavior**:
An alternate fix or automatic suppression of the warning when a property matches the target name already.

**Actual Behavior**:
Code generates a conflict with a property that already exists.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and complexity of solutino.
