### ISSUE TITLE
Local method System.BadImageFormatException error

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#39310]
The following causes a `System.BadImageFormatException` to throw when the local method is called:

```c#
        [TestMethod]
        public void Invalid_Program()
        {
            Invalid_Program2<int>();

            static void Invalid_Program2<T>()
            {
                int x = 0;
                var y = (T)(dynamic)x;
            }
        }
```

Moving the local method out of the outer method so it becomes a normal method works fine. I believe this is a somewhat recent regression, somewhere between a .NET Core 3.0 beta and 3.0 release version as I do believe this was working at some point but I may be wrong about that.

This is compiled in a .NET Standard 2.1 library with C# 8 enabled in VS2019 with .NET Core 3.0 release version installed.

**Comment by jkotas** [comment]
This field is in non-generic type:

```
    .field public static class [System.Linq.Expressions]System.Runtime.CompilerServices.CallSite`1<class [System.Runtime]System.Func`3<class [System.Linq.Expressions]System.Runtime.CompilerServices.CallSite,object,!!0>> '<>p__0'
```

but its type is referencing generic variable `!!0`.

**Comment by jkotas** [comment]
Bad IL generated by Roslyn

**Comment by 0xd4d** [comment]
https://github.com/dotnet/roslyn/issues/29340

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/roslyn/issues/29340
