### ISSUE TITLE
VB implementation of WriteDocumentationCommentXml does not respect filterTree

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#39315]
During review of [DevDiv 999063](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/999063), I found that syntax trees were reconstituted 115603 times in less than 100 seconds, including 217 cases for just **src/Compilers/VisualBasic/Portable/Lowering/Rewriter.vb**. CPU analysis suggests that the trees are being requested by this method:

```
Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation+DocumentationCommentCompiler.WriteDocumentationCommentXml
```

I noticed that this block:

https://github.com/dotnet/roslyn/blob/1de29ff0ae5661a0ac4b8208ac42570bce4c9417/src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs#L108-L113

is not present in the corresponding VB compiler method:

https://github.com/dotnet/roslyn/blob/1de29ff0ae5661a0ac4b8208ac42570bce4c9417/src/Compilers/VisualBasic/Portable/Compilation/DocumentationComments/DocumentationCommentCompiler.vb#L59-L65

**Comment by AlekseyTs** [comment]
It looks reasonable to add similar logic for VB. Also, it looks like existing code is incorrectly passing ```filterSpanWithinTree``` for all trees in the compilation.

```
                For Each tree In compilation.SyntaxTrees
                    MislocatedDocumentationCommentFinder.ReportUnprocessed(tree, filterSpanWithinTree, diagnostics, cancellationToken)
                Next
```
