### ISSUE TITLE
Bug: Null-forgiving operator suppresses CS8620 warning

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#39311]
**Version Used**: 3.3.1

**Steps to Reproduce**:
```cs
List<string?> list = new List<string?>();
List<string> list1 = list.Where(x => x != null).ToList(); // warning CS8619
List<string> list2 = list.Where(x => x != null).ToList<string>(); // warning CS8620
List<string> list3 = list.Where(x => x != null)!.ToList(); // warning CS8619
List<string> list4 = list.Where(x => x != null)!.ToList<string>(); // no warning here (bug)
```

**Expected Behavior**:
`list1`: warning CS8619: Nullability of reference types in value of type 'List<string?>' doesn't match target type 'List<string>'.

`list2`: warning CS8620: Argument of type 'IEnumerable<string?>' cannot be used for parameter 'source' of type 'IEnumerable<string>' in 'List<string> Enumerable.ToList<string>(IEnumerable<string> source)' due to differences in the nullability of reference types.

`list3`: warning CS8619: Nullability of reference types in value of type 'List<string?>' doesn't match target type 'List<string>'.

**`list4`: warning CS8620: Argument of type 'IEnumerable<string?>' cannot be used for parameter 'source' of type 'IEnumerable<string>' in 'List<string> Enumerable.ToList<string>(IEnumerable<string> source)' due to differences in the nullability of reference types.**

**Actual Behavior**:
`list1`: warning CS8619: Nullability of reference types in value of type 'List<string?>' doesn't match target type 'List<string>'.

`list2`: warning CS8620: Argument of type 'IEnumerable<string?>' cannot be used for parameter 'source' of type 'IEnumerable<string>' in 'List<string> Enumerable.ToList<string>(IEnumerable<string> source)' due to differences in the nullability of reference types.

`list3`: warning CS8619: Nullability of reference types in value of type 'List<string?>' doesn't match target type 'List<string>'.

**`list4`: no warning**

**Comment by RikkiGibson** [comment]
Seems like for `list3` the inferred type argument is `string?`, while for list4 we provide an explicit `string` type argument and suppress the warning about the receiver mismatch.

**Comment by ronnygunawan** [comment]
@RikkiGibson is the null-forgiving operator supposed to also suppress warnings about receiver nullability mismatch? It doesn't say so in [spec](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types-specification.md).

But if it is, then I think it's a very useful functionality.

**Comment by RikkiGibson** [comment]
Seems like implicit type arguments to extension methods is not called out in the spec, but it's the way it works in practice.

I will close this because there doesn't appear to be anything actionable in the compiler in this issue. It may be good to ping on a relevant issue in csharplang to flesh out the null-forgiving operator spec, though.

**Comment by ronnygunawan** [comment]
Ok. I moved the issue to [csharplang](https://github.com/dotnet/csharplang/issues)
