### ISSUE TITLE
C# formatter's "Make private fields readonly" option fails to consider separated partial classes

### ISSUE THREAD

**Issue by RachelDavids** [dotnet/roslyn#39323]
VS Enterprise 16.3.5

**Steps to Reproduce**:
using the following code - using separate files - If used in the same file behavior is as expected.
Apply code-cleanup - including "Make private fields readonly when possible"
```
	partial class MyTest : Form
	{
		private bool _disposed;
	}

	partial class MyTest
	{
		protected override void Dispose(bool disposing)
		{
			if(!_disposed)
				base.Dispose(disposing);
                       _disposed = true;
		}
	}
```

**Expected Behavior**:
```
	internal partial class MyTest : Form
	{
		private bool _disposed;;
	}

	internal partial class MyTest
	{
		protected override void Dispose(bool disposing)
		{
			if (!_disposed)
			{
				base.Dispose(disposing);
			}
                       _disposed = true;
		}
	}
```
**Actual Behavior**:
```
	internal partial class MyTest : Form
	{
		private readonly bool _disposed = true;
	}

	internal partial class MyTest
	{
		protected override void Dispose(bool disposing)
		{
			if (!_disposed)
			{
				base.Dispose(disposing);
			}
			_disposed = true; // this line fails to compile 
		}
	}
```

**Comment by sharwell** [comment]
@mavasani for a bug in symbol start/end analysis

**Comment by mavasani** [comment]
Do we know which code fix is adding `_disposed = true;`?

**Comment by RachelDavids** [comment]
@mavasani @sharwell  - my mistake - the **_disposed = true; **  line should also be in the original code

**Comment by RachelDavids** [comment]
Have corrected the code in initial comment

**Comment by mavasani** [comment]
Original code (with the correct code) and partial types split across files does not generate a Make fieldreadonly diagnostic. I believe the issue might be in the way code cleanup is doing the operations/analysis at a single file level...

**Comment by sharwell** [comment]
The Code Cleanup entry to the code fix APIs is here:

https://github.com/dotnet/roslyn/blob/813fa93aa8beeaa718a4f82d4620f86e2e797f8f/src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs#L181-L182

I'm guessing the analyzer framework bug is in this:

https://github.com/dotnet/roslyn/blob/d9f276923b6a9ff7620bcffa5a4b0254fb65d3c2/src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs#L210-L244

**Comment by CyrusNajmabadi** [comment]
I don't repro this at all.
