### ISSUE TITLE
If I'm trying to reference a new class, property, etc. that only newer frameworks/standard/core target, some helpful refactor recommendations would be nice. I find I spend a lot of time trying to understand when given features came in for what version....

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39332]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/776570/if-im-trying-to-reference-a-new-class-property-etc.html)._

---
If I'm trying to reference a new class, property, etc. that only newer frameworks/standard/core target, some helpful refactor recommendations would be nice. I find I spend a lot of time trying to understand when given features came in for what version. Having that built into the IDE so I can make more intelligent choices would be helpful.

---
#### Visual Studio Feedback System on 10/14/2019, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
Could you pls share a scenario you are trying to achieve here ?
