### ISSUE TITLE
"Make field readonly" doesn't consider designer writes

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#39345]
**Version Used**: Version 16.4.0 Preview 3.0 [29416.158.master]

**Steps to Reproduce**:

## `C.cs`

```c#
partial class C
{
    private object _foo; // IDE0044 Add readonly modifier

    public C()
    {
        _foo = new object();
    }

    public int O() => _foo.GetHashCode();
}
```

## `C.Designer.cs`

```c#
partial class C
{
    void M()
    {
        _foo = null;
    }
}
```

**Expected Behavior**:

Do not suggest adding `readonly` modifier when field has writes from designer files.

**Actual Behavior**:

Adding `readonly` is suggested.

**Comment by RikkiGibson** [comment]
looks like a dupe of #39323
