### ISSUE TITLE
IDE0059 "Remove redundant assignment" can break code logic

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#39344]
**Version Used**: Version 16.4.0 Preview 3.0 [29416.158.master]

**Steps to Reproduce**:

```c#
void M(int i)
{
    bool b = false;
    try
    {
        if (i == 0)
        {
            b = true; // IDE0059 Unnecessary assignment of a value
        }
    }
    finally
    {
        if (!b)
        {
            Console.WriteLine("Exception");
        }
    }
}
```

**Expected Behavior**:

Does not remove assignment to `b`.

**Actual Behavior**:

Removes assignment to `b`.

**Comment by mgravell** [comment]
Yeah, another repro of this where the affected code would have broken `Monitor` usage; I *cannot* repro in a reduced sample, but:

![image](https://user-images.githubusercontent.com/17328/67197678-3f892380-f3f5-11e9-9b3d-aa3993d2ef79.png)

**Comment by stephentoub** [comment]
Just hit this as well.

**Comment by jnm2** [comment]
Same here. To add to the initial example, this is also not an unnecessary assignment:

```cs
void M(int i)
{
    bool b = false;
    try
    {
        SomethingThatCouldConceivablyThrow();

        b = true; // IDE0059 Unnecessary assignment of a value
    }
    finally
    {
        if (!b)
        {
            Console.WriteLine("Exception");
        }
    }
}
```
