### ISSUE TITLE
RFE: (C# only?) Make Rename progress dialog less greedy of system interaction with "parent" frame window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39356]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/774480/rfe-c-only-make-rename-progress-dialog-less-greedy.html)._

---
Problem:
When doing a refactoring rename operation, especially noticable in C# if you rename a namespace, it can take a _long_ time (we're talking minutes, which for even larger projects can probably become both hours and days).
During this time, the Visual Studio Frame window is completely unresponsive, making it impossible for user to interact with to the point it can't even be minimized to get it out of the way.

Suggestion:
Make the Rename progress dialog Task less UI-greedy. Allow interaction with normal system-provided (frame-) window operations; especially minimize.

---
#### Jane Wu [MSFT] on 10/12/2019, 00:00 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This should not be an issue anymore with the way we do progress now.
