### ISSUE TITLE
Highlight same code entity in multiple files.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39352]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/780549/highlight-same-code-entity-in-multiple-files.html)._

---
When I select variable, function or any other code entity it is highlighred everywhere in the file, and it is very convenient.
Unfortunately when I create multiple Tab Groups and have multiple files side by side highliting is not working across files.

For example, when I select class name in one file same name is not highlighted in the other file.

---
#### Jane Wu [MSFT] on 10/16/2019, 08:27 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
