### ISSUE TITLE
RFE: C# analyzer/refactoring for implicit bool conversion types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39358]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/771012/rfe-c-analyzerrefactoring-for-implicit-bool-conver.html)._

---
I won't comment on neither the suitability nor the sanity of the following example.
Suffice it to say it is a boiled down representation of a very widespread existing library, meaning the interface is in fact carved in stone.
```
// C#
class RFE_AutoBoolDeduction
{
  class foo
  {
    public static implicit operator bool(foo f) { return true; }
  }
  void tst(foo f)
  {
    // expected:
    //  1. &quot;(bool)&quot; getting &quot;dimmed&quot; to display it's redundant (whether or not prepended by a negation operator),
    //  2. refactoring (&quot;lightbulb&quot;) to remove it
    // actual: *crickets*
    if (!( bool)f)
    {
    }
  }
}
```

---
#### Jane Wu [MSFT] on 10/10/2019, 11:49 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
I think we would take a PR that implemented this.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
