### ISSUE TITLE
Analyze solution with WPF projects - MSBuildWorkspace

### ISSUE THREAD

**Issue by sk78v** [dotnet/roslyn#39359]
**Version Used**: VS 2017, 

**Steps to Reproduce**:
Added binding redirect to config file
```
<dependentAssembly>
        <assemblyIdentity name="Microsoft.Build" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
    </dependentAssembly>
```

 ```
var properties = new Dictionary<string, string>() {                                 
                                    { "DesignTimeBuild", "true" },
                                    { "BuildingInsideVisualStudio", "true" }
                                };
var sourceCodePath = "path to wpf project";
var msBuildWorkSpace = MSBuildWorkspace.Create(properties);
var solution = msBuildWorkSpace.OpenSolutionAsync(sourceCodePath).Result;
foreach (Microsoft.CodeAnalysis.Project project in solution.Projects)
{
  var projectCompilation = solution.GetProject(project.Id).GetCompilationAsync().Result;
}

```
project compilation fails with this error "error CS5001: Program does not contain a static 'Main' method suitable for an entry point"

**Expected Behavior**:
No compilation errors.
**Actual Behavior**:
error CS5001: Program does not contain a static 'Main' method suitable for an entry point

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@sk78v You should need to do more binding redirects than just that one. What happens if you also add redirects for Microsoft.Build.Framework and Microsoft.Build.Engine?

**Comment by jasonmalinowski** [comment]
Closing out as stale -- in any case with the latest 4.9 packages we'll handle redirects for you in our own separate process so nothing should be needed to be done anymore.
