### ISSUE TITLE
RFE: C# refactoring preview, add user-setting 'Preview Delay'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39357]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/771202/rfe-c-refactoring-preview-add-user-setting-preview.html)._

---
Scenario:
When engaging refactoring on a large code block, the refactoring preview can consume quite a lot of time (multiple seconds) to preview the refactoring. This can (and do) become a problem in multiple scenarios, f.ex.
- if you are seasoned, or just fast, and know exactly what the refactoring will do.
- if you are not interested in the default refactoring at all, but are now held waiting for several seconds, perhaps for each option, to scroll down to the actual refactoring you are after
- the &quot;jerkyness&quot; introduced by all these delays can make you unintentionally engage the wrong refactoring when using keyboard to scroll in a list (say 10 in total, and you want to get to entry 5). This is not a hypothesis, this is a fact I have myself experienced, and been hurt by, multiple times (more than a few hundred).
- ...

Suggestion:
Add a setting
- Delay Time (ms) until preview is generated.

It could be set to a default of zero, to keep current behaviour, while allowing more seasoned users to turn it up to prevent this delay/these delays.

It could (maybe even should?) also allow a timeout of -1, meaning it would never automatically pop up the preview, but instead display a prompt for input generate and display the preview (for the selected refactoring).

Sidenote:
An optional setting &quot;Delay Threshold (min # of lines affected)&quot; could at first blush seem like logical too, but it's obviously impossible for the editor to know how many lines a specific refactoring will affect, so that's a No.

---
#### Jane Wu [MSFT] on 10/10/2019, 11:49 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
cc @olegtk for info

**Comment by CyrusNajmabadi** [comment]
@olegtk shoudl this go to you guys?

**Comment by olegtk** [comment]
Well, [LightBulb preview is async](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.isuggestedaction.getpreviewasync?view=visualstudiosdk-2019), but the result is UI emement and it's still constructed on the U thread so can affect responsiveness if takes too long. Otherwise it should not block navigation through items or invokation.
I don't see an internal ticket for this feedback, do we get any traces?

**Comment by CyrusNajmabadi** [comment]
Closing as external.
