### ISSUE TITLE
Design proposal: C# Editor Settings UI, delimiters spacing, simplification (low priority)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39368]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/775024/design-proposal-c-editor-settings-ui-delimiters-sp.html)._

---
For your consideration,

The current Editor Settings UI for spacing could be improved. These settings are split into two, usually disjunct due to lexicographical sorting, settings -- one for &quot;before&quot; and one for &quot;after&quot; -- using checkboxes. This is f.ex. breaking semantical (and syntactical) locality.

Proposal:
Convert to 4-state combobox settings.
- Space before
- Space after
- None
- Both

Pros:
- It could clean up the UI. F.ex. semantical locality would be preserved.
- It could reclaim vertical space.
- It could clean up the code (one single implementation of applicable choices).
- It could simplify documentation of the settings.
- It would simplify localization. Each setting would require one single localization string; the choices would be common for all consumers of the combobox.

Cons:
- Would possibly require redesign/implementation of columnar settings list.

Example in attached mockup image. I am not a graphical artist. Wording in the png is equally for expository purposes only. It is purely to present the concept.

Proposal intentionally limited to delimiter spacing, and C#. There are likely other settings groups that could benefit from similar multi-state common ancestry, common even across editors/languages.

---
#### Jane Wu [MSFT] on 10/13/2019, 07:39 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and as we are not likely investing in these legacy options UI scenarios.
