### ISSUE TITLE
QuickInfo cut off in 16.4p2

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#39366]
![image](https://user-images.githubusercontent.com/4564579/67043125-2f640200-f0de-11e9-99d6-139f106918e8.png)

That's the quick info for:

```c#
        //
        // Summary:
        //     Gets the TValue associated with the specified key.
        //
        // Parameters:
        //   key:
        //     The type of the key.
        //
        // Returns:
        //     The value associated with the specified key. If no results are found, the operation
        //     throws an exception.
```

Note the cutoff after "If no..."

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph @jasonmalinowski

**Comment by jinujoseph** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1003779

**Comment by gundermanc** [comment]
Editor will take a look at this. In the meantime..

@CyrusNajmabadi IIRC this tip isn't actually quick info, it's part of Editor outlining, which appears to not have changed in the last few years, and it's hosting a WPF text view that Roslyn creates. Can you confirm that the WPF text view creation code hasn't regressed?

If it's on our end, I think this might be a product-wide XAML resource change or even a WPF regression.

**Comment by CyrusNajmabadi** [comment]
>@CyrusNajmabadi IIRC this tip isn't actually quick info, it's part of Editor outlining, which appears to not have changed in the last few years, and it's hosting a WPF text view that Roslyn creates.

I thought that was undone because of your remoting scenarios.  i.e. we no longer host the wpf text view.  Instead, we actually transcribe the buffer to classified text spans and that gets displayed instead.

@jasonmalinowski do you know?

**Comment by gundermanc** [comment]
>I thought that was undone because of your remoting scenarios. i.e. we no longer host the wpf text view.

That's true for Quick Info but the outlining tips are still text views from what I can tell.

**Comment by olegtk** [comment]
I can repro this on 15.9 so I assume it's not a regression.
