### ISSUE TITLE
Task List (C#), find "TODO" etc even when in para's

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39360]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/768827/task-list-c-find-todo-etc-even-when-in-paras.html)._

---
Place the following code in a .cs file (that's in a project).

Open the &quot;Task List&quot; view.

Expected: TODO 1-5 listed.

Actual: Only TODO 1,3,5 listed.

Since this may be an intentional limitation, I post this as a suggestion to reconsider that design decision, and fix it to work as expected. In case this behavior is as unexpected to Microsoft as it is to us, feel free to move it to the Bugs section.

```
class RFE_TaskListCommentsEvenWhenInPara
{
  /// &lt;summary&gt;
  /// some text, followed by para, since these comment blocks don't handle br - Bad Design(tm).
  /// TODO: 1. This comment in summary will visible in the Task List view.
  /// &lt;para&gt;TODO: 2. This comment in para in summary should also be visible in the Task List view.&lt;/para&gt;
  /// &lt;/summary&gt;
  /// &lt;remarks&gt;
  /// TODO: 3. This comment in remarks summary will visible in the Task List view.
  /// &lt;para&gt;TODO: 4. This comment in para in remarks should also be visible in the Task List view.&lt;/para&gt;
  /// &lt;/remarks&gt;
  void tst()
  {
    // TODO: 5. This comment in method will be visible in the Task List view.
  }
}
```

---
#### Jane Wu [MSFT] on 10/10/2019, 00:14 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by tamlin-mike** [comment]
@vsfeedback messed up when copying from DC. Corrected version below
```
class RFE_TaskListCommentsEvenWhenInPara
{
  /// <summary>
  /// some text, followed by para, since these comment blocks don't handle br - Bad Design(tm).
  /// TODO: 1. This comment in summary will visible in the Task List view.
  /// <para>TODO: 2. This comment in para in summary should also be visible in the Task List view.</para>
  /// </summary>
  /// <remarks>
  /// TODO: 3. This comment in remarks summary will visible in the Task List view.
  /// <para>TODO: 4. This comment in para in remarks should also be visible in the Task List view.</para>
  /// </remarks>
  void tst()
  {
    // TODO: 5. This comment in method will be visible in the Task List view.
  }
}
```
