### ISSUE TITLE
IDE0047 Remove unnecessary parentheses fails to appear for switch expressions

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#39363]
**Version Used**: 16.4.0 P1

**Steps to Reproduce**:
1. Have a switch expression that contains unnecessary parentheses.
2. Pull up code fixes menu.

![switchbug](https://user-images.githubusercontent.com/16968319/67036612-c88c1c00-f0d0-11e9-8f15-333bcb19aabc.png)

![switchbug2](https://user-images.githubusercontent.com/16968319/67036734-fcffd800-f0d0-11e9-80df-067aaa6700e7.png)

**Expected Behavior**: Code fix option IDE0047 appears to remove unnecessary parentheses.

**Actual Behavior**: No code fix shown. IDE0047 does appear for the local variable declaration on line 16, so this seems to be an issue specific to switch expressions.

**Comment by CyrusNajmabadi** [comment]
Should be trivial fix.  Just have to update the parentheses removal logic to account for this new case.
