### ISSUE TITLE
Find References doesnt show implicit cast operator reference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39375]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/729263/find-references-doesnt-show-implicit-cast-operator.html)._

---
When class contains implicit cast operator , it's reference is not shown .

---
#### Visual Studio Feedback System on 9/11/2019, 03:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We have no facility for this and hte feature is working as expected.
