### ISSUE TITLE
Rename class name or namespace

### ISSUE THREAD

**Issue by ndung** [dotnet/roslyn#3938]
Hi,

From example that I see, Renamer only work with SyntaxToken. Can Renamer be used to rename class or namespace like ReSharper does? I have this snippet but it does not work. Thanks

            var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
            ITypeSymbol typeSymbol = semanticModel.GetTypeInfo(identifierNameSyntax, cancellationToken).Type;
            string thisNamespace = SyntaxNodeHelper.GetNamespaceName(document);
            string className = typeSymbol.ToString();
            string newName = className.Replace(typeSymbol.ContainingNamespace.ToString(), thisNamespace);
            var originalSolution = document.Project.Solution;
            var optionSet = originalSolution.Workspace.Options;
            var newSolution = await Renamer.RenameSymbolAsync(document.Project.Solution, typeSymbol, newName, optionSet, cancellationToken).ConfigureAwait(false);
            return newSolution;

**Comment by jmarolf** [comment]
The Renamer cannot rename tokens, it accepts symbols and then renames all instances of that symbol across the solution.

A few quick questions:
```C#
string newName = className.Replace(typeSymbol.ContainingNamespace.ToString(), thisNamespace);
```
In the snippet above I assume that class name contains the same name as its containing namespace? Like this?
```C#
namespace My
{
    class MyClass
}
```
and you want to rename the class to be whatever the value of thisNamespace is? So if it was "ThisNamespace" the result should be:

```C#
namespace My
{
    class ThisNamespaceClass
}
```

Or is your goal to change the name of the namespace itself?

**Comment by ndung** [comment]
Hi @jmarolf,

I want to change the name of the namespace itself. The result should be

       namespace ThisNamespace
       {
            class MyClass
       }

I thought I can do it by renaming the full class name.

Thanks.

**Comment by jmarolf** [comment]
@ndung The symbol for the class and the symbol for the namespace are two separate things.  You can acquire the fully qualified name of a symbol including its containing namespace, but this is just a string. Modifying it does not cause anything to happen to the namespace itself.  Looks like you want to pass the namespace symbol to the Rename class like this:

```C#
var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
ITypeSymbol typeSymbol = semanticModel.GetTypeInfo(identifierNameSyntax, cancellationToken).Type;
string thisNamespace = SyntaxNodeHelper.GetNamespaceName(document);
var namespaceSymbol = typeSymbol.ContainingNamespace;
var originalSolution = document.Project.Solution;
var optionSet = originalSolution.Workspace.Options;
var newSolution = await Renamer.RenameSymbolAsync(document.Project.Solution, namespaceSymbol , thisNamespace, optionSet, cancellationToken).ConfigureAwait(false);
return newSolution;
```

Though it depends on the actual shape of the namespace.

**Comment by mattwar** [comment]
I suspect he just wants to put the class in a different namespace, and not rename all other occurrences of the original namespace.

**Comment by jmarolf** [comment]
@mattwar good point.  @ndung  please let us know what the end goal is here.  Renamer.RenameSymbolAsync is going to rename every location in your solution that mentions that namespace.  If you just want to rename something in one place, you can replace the single node or token at that location.

**Comment by ndung** [comment]
Hi @jmarolf, I want to rename all other occurrences of the original namespace as well, and your solution works. Thanks!
Thanks also to @mattwar
