### ISSUE TITLE
Variable suggestions show duplicated filter buttons on completion window

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39381]
Not sure I understand what these filters do, the have the same tooltip:

![image](https://user-images.githubusercontent.com/1103906/67065886-bc30bd80-f1bb-11e9-8cec-1daabb8b1022.png)

**Comment by ivanbasov** [comment]
Thank you, @davkean !
@jinujoseph it is worth to fix it in 16.4. Hope to provide a fix soon. We should send it to QB.

**Comment by ivanbasov** [comment]
fixed with #39499
