### ISSUE TITLE
C# Intellisense: Disable most recently used members

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39391]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/741677/c-intellisense-disable-most-recently-used-members.html)._

---
I'd like to be able to disable this feature: https://docs.microsoft.com/en-us/visualstudio/ide/visual-csharp-intellisense?view=vs-2019#most-recently-used-members

If I have a type **DateTime** and a variable **dateTime** and I've _most recently_ typed **DateTime**, then typing **datet.. ** doesn't autocomplete to **dateTime** but **DateTime**.

Which ends up happening a lot eg:

&gt;var dateTime = DateTime.Now;
&gt;dateT [TAB] =&gt; DateTime.

It's also mentioned here: https://stackoverflow.com/questions/43922535/autocomplete-case-issue

PLEASE let me turn this off. :)

---
#### Visual Studio Feedback System on 9/22/2019, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/17/2019, 04:56 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
@sharwell you maybe interested in reviewing this one. It matches with the idea of setting a higher priority to IntelliCode vs MRU.

**Comment by jinujoseph** [comment]
cc @AmadeusW for info

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
