### ISSUE TITLE
EE - Cannot evaluate NameOf expression in watch window

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#3939]
See http://screencast.com/t/PsADwR1I950g

Complete repro code:
```
Module Module1

    Sub Main()
        Dim c = New C()
    End Sub

    Class C
        Public ReadOnly Property P As String = Init()

        Public Shared Function Init() As String
            Return NameOf(P)
        End Function
    End Class
End Module
```

Reproduced in VS Enterprise 14.0.23.23103 D14REL
C# is not affected.

**Comment by amcasey** [comment]
```VB
?nameof(P)
(1) : error BC30043: 'P' is valid only within an instance method.
```

**Comment by amcasey** [comment]
The VB failure seems straightforward.  When we're rewriting the synthesized method to update all the ```Me``` references, we find one as the receiver of the ```nameof``` argument.  We should probably just ignore it (and any other expression that has a constant value and will, therefore, not be emitted).

I'm more confused about why C# doesn't exhibit the same behavior.

**Comment by amcasey** [comment]
It looks like C#'s ```LocalRewriter``` is reducing it to a constant.

**Comment by amcasey** [comment]
```C#
        private BoundExpression VisitExpressionImpl(BoundExpression node)
        {
            ConstantValue constantValue = node.ConstantValue;
            if (constantValue != null)
            {
                TypeSymbol type = node.Type;
                if (type?.IsNullableType() != true)
                {
                    return MakeLiteral(node.Syntax, constantValue, type);
                }
            }
```

**Comment by amcasey** [comment]
In VB the ```LocalRewriter``` runs after the ```CapturedVariableRewriter```.

**Comment by amcasey** [comment]
@KevinH-MS Can you please verify?
