### ISSUE TITLE
Suggested LINQ refactoring is not correct

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39408]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/740980/suggested-linq-refactoring-is-not-correct.html)._

---
In WPF project
IDE Suggest to convert LINQ in follow code, but converted result is compile error

(WrapPanelMain is an instance of WrapPanel)
            foreach (var item in WrapPanelMain.Children)
            {
            }

---
#### Visual Studio Feedback System on 9/20/2019, 01:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/17/2019, 04:54 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Ivan Basov [MSFT] on 10/18/2019, 11:55 AM: 

<p>Thank you for your feedback!</p>
<p>I tried Convert To Linq with the following code:<br>
void Do(Panel panel, bool mode)<br>
{<br>
foreach(var item in panel.Children)<br>
{<br>
CheckBox ch = item as CheckBox;<br>
if (ch != null) ch.IsChecked = mode;<br>
}<br>
}</p>
<p>The converted foreach looks like the following one:<br>
foreach (var ch in from item in panel.Children<br>
let ch = item as CheckBox<br>
where ch != null<br>
select ch)<br>
{<br>
ch.IsChecked = mode;<br>
}<br>
which seems to be correct and he build succeeded. Could you please let us know what code is generated in you case?</p>

#### Akira Kawamata on 10/19/2019, 00:34 AM: 

<p>In Visual Studio 16.3.5...</p><p>private void checkAllCommon(bool mode)<br>{<br>    foreach (var item in WrapPanelMain.Children)<br>    {<br>        CheckBox ch = item as CheckBox;<br>        if (ch != null) ch.IsChecked = mode;<br>    }<br>}</p><p> converted to...</p><p>private void checkAllCommon(bool mode)<br>{<br>    foreach (var ch in from item in WrapPanelMain.Children<br>                       let ch = item as CheckBox<br>                       where ch != null<br>                       select ch)<br>    {<br>        ch.IsChecked = mode;<br>    }<br>}</p><p> Error Message is...</p><p>エラー CS1934 ソース型 'UIElementCollection' のクエリ パターンの実装が見つかりませんでした。'Select' が見つかりません。範囲変数 'item'  の型を明示的に指定してください。 WpfApp3 C:\xdelme\WpfApp3\WpfApp3\MainWindow.xaml.cs 29 アクティブ</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
Reproduced. `WrapPanel.Children` is a `UIElementCollection `which implements an indexer over `UIElement `and `IList`, `ICollection `and `IEnumerable `but not `IList<T>`, `ICollection<T>` or `IEnumerable<T>`. We should either add `object` to the query or can avoid conversion of `<T>` is not supported.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
