### ISSUE TITLE
Adding readonly modifier via quick fix deletes preceding blank line

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/roslyn#39404]
**Version Used**: 3.4.0-beta1 (and 3.3.0)

**Steps to Reproduce**:

```csharp
        const string c1 = "hi";
        const string c2 = "world";

        int x = 5;
```

1. Hover over `x`.
2. Lightbulb will appear. Click it.
3. Select "Add readonly modifier"

**Expected Behavior**:

```csharp
        const string c1 = "hi";
        const string c2 = "world";

        readonly int x = 5;
```

**Actual Behavior**:

```csharp
        const string c1 = "hi";
        const string c2 = "world";
        readonly int x = 5;
```

I'm curious if this is related to https://github.com/dotnet/roslyn/issues/36759 (which appears to be fixed via https://github.com/dotnet/roslyn/pull/36994).

_Originally reported via https://developercommunity.visualstudio.com/content/problem/703857/adding-readonly-modifer-via-altenter-delets-blank.html_

**Comment by Therzok** [comment]
Since both comments and whitespace are syntax trivia, I assume it's a duplicate

**Comment by sandyarmstrong** [comment]
@Therzok perhaps, but I can't reproduce https://github.com/dotnet/roslyn/issues/36759 anymore.

**Comment by Therzok** [comment]
From the looks of it, it most likely needs AddElasticMarker, as other usages of KeepLeadingTrivia also pass that:
https://github.com/dotnet/roslyn/pull/36994/files#diff-889a17509e2865e48bcf1bb4aa2945abR90

**Comment by jinujoseph** [comment]
Related to #35489

**Comment by CyrusNajmabadi** [comment]
Not repro.  I get:

![image](https://user-images.githubusercontent.com/4564579/218860253-bb51386d-c464-4c33-8cb0-4454fcc3df26.png)
