### ISSUE TITLE
Compiler should optimize conversion from bool? to bool when code tests for true

### ISSUE THREAD

**Issue by yahorsi** [dotnet/roslyn#39409]
Hi Guys,

I was surprised to see that when we have bool? and need to check if it's true in if statement then doing it using just like:
```csharp
if (v == true)
{
}
```
works way slower than if we would explicitly do
```csharp
if (v.GetValueorDefault())
{
}
```

In the first case, when we call it like if (v == true) I see compiler emits an unnecessary call to the HasValue
```csharp
        bool? flag = v;
        bool flag2 = true;
        if ((flag.GetValueOrDefault() == flag2) & flag.HasValue)
        {
        }
```

Is that something expected and made on purpose?
Here is a link to the SharpLab to demonstrate the difference in the generated assembler.

https://sharplab.io/#v2:C4LghgzgtgPgAgBgAQGUAWYBOAHAMmAIwDoAlAVwDtgBLKAUwG4BYAKDgCYBGV1uTgNiQckAYSQBvVkmlCBQgCxIAZggAUBAPYaANgH4kANwCUUmZJYzLSakqSqDRAOJ1gANTDaydAPKYAInRKYGTawKpGJhZW0ubR0XwAnKoARIQAxslGzFHRAL6m0vksBbKCcIpKnOpaeoaRlrFxNnYGSAC8bUjAmF71cY1xMokp6ZnZg0WWRblAA=

**Comment by jinujoseph** [comment]
related to #22800

**Comment by yahorsi** [comment]
Hello @jinujoseph 

I see you have assigned Nullable Reference Types label but this seems related more for the value types.

To shorten the issue it could be described as following: Implicit or explicit casts from the bool? to bool could be done using GetValueOrDefault() call, call to the HasValue is unnecessary and significantly affects performance.

Regards

**Comment by jrmoreno1** [comment]
@yahorsi : which makes false == null.

**Comment by yahorsi** [comment]
@jrmoreno1 Correct, thanks, that optimization could only apply when we test for true

**Comment by RikkiGibson** [comment]
@xtqqczze I think we can just track under #52629.
