### ISSUE TITLE
Incorrect concatenation of localized string fragments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39411]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/603108/incomprehensible-warning-german.html)._

---
I know that the localisation quality of Visual Studio is constantly decreasing. Now it sometimes reaches the point of total incomprehensibility (does that word exist?).

The warning in German reads &quot;Erwartete Aufgabe wird zurückgegeben kein Wert.&quot; See attached screenshot.

What is that warning trying to tell me? I don't get it.

If I try to translate this broken sentence into English, it might sound something like &quot;Expected task is being returned, no value.&quot; Do you know what that means?

Please tell your localisation team to do some work. And no, any kind of contextless automatic machine translation is the worst you can do. Really really bad. Machines don't have a clue what they're doing, but they're very certain about it!

---
#### Visual Studio Feedback System on 6/12/2019, 02:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/12/2019, 02:20 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 8/7/2019, 02:35 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Here is the detailed explanation from @tmeschter :

> The issue here is that the code for Quick Info is attempting to create a single logical phrase by joining together individually-translated substrings. There is no way this can be properly localized, and changes will need to be made in Quick Info, not just the individual resources or translation.
>
> Looking at this in English, we're trying to create the following text:
>
> > Awaited task returns no value.
>
> But this text is actually split across two resources:
>
> > {Awaited_task_returns} {no_value}
>
> This is done so the Awaited_task_returns resource can be reused to generate strings like
>
> > {Awaited_task_returns} <type name>.
>
> E.g.
>
> > Awaited task returns System.Int.
>
> There are several things wrong with this:
>
> 1. The translators see the individual resources out of context and have no way of knowing that they are meant to go together. Even if the individual translations make sense, the combination may be meaningless.
> 1. The Quick Info code orders the two resources in a way that makes sense for English but won't necessarily make sense for other languages. For example, the Japanese translation would be something like "Awaited task value returns not", and there's no way to assemble that properly out of the resources we currently have. Something similar is happening in German.
> 1. The code forces a space in between Awaited_task_returns and no_value. This is completely wrong in Chinese, Japanese, and Korean as they generally do not use spaces for delineating words.
Logically what we want are two separate resources, each a complete logical phrase:
>
> > "Awaited task returns no value."
> > "Awaited task returns {0}."
>
> Where {0} represents the type name. I suspect the "type name" is actually something more complicated then just straight text, like a colorized chunk of C# or VB code. That's going to be more complicated to deal with but the approach is the same.
