### ISSUE TITLE
Visualizing Deferred Execution Calls in Visual Studio 2019

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/roslyn#39418]
I’d like to see somehow visualized in VS,  show the user that the line of code is “deferred execution”. Of course, this is done a lot in LINQ queries and other calls like AsParallel on a collection.
 
For example, doing collection.AsParallel() in a loop doesn’t do anything unless something comes after it like ForAll(). The same sort of idea for LINQ queries too. I am thinking that analyzers might be able to help with this too.

Not sure the best way to visualize this in Visual Studio 2019. Always willing to discuss.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
