### ISSUE TITLE
Code fixes never shows up if you navigate to it and the file has never been open before

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39437]
This is 100% repro and has occurred up on stage presenting the fixes.

**Visual Studio Version**:
Version 16.4.0 Preview 3.0 [29421.117.master]

**Summary**:

**Steps to Reproduce**:

Make sure Full Solution Analysis is turned on.

1. `git clone https://github.com/davkean/audio-switcher`
2. `cd audio-switcher`
3. `git checkout 9d8fa8d1d1dde083abc6d813617df05b088d88f1`
4. `src\AudioSwitcher.sln`
5. Open Error List and wait for "Use pattern matching" analysis message to appear
6. Double-click it to navigate to source code
7. Drop lightbulb

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/1103906/67252753-0f5a8700-f4c0-11e9-9b60-449a59ebd03e.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/67252740-079ae280-f4c0-11e9-9e4f-abfbc36604b8.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as this was entirely rewritten and we have gotten no other reports on this.
