### ISSUE TITLE
Autogeneration of interface implementation for IDiaStackWalkHelper is confused by indexed getter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39434]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/784552/autogeneration-of-interface-implementation-for-idi.html)._

---
After importing the DIA com type library in my C# project, I try to implement the IDiaStackWalkHelper interface. Using the automatic inteface implementation skeleton generation command results in an incorrect implementation of the `get_registerValue` method.

The generated skeleton thinks that `registerValue` is a normal property, when it is not. It's a named indexer, which isn't supported in C# and must be implemented as a pair of regular methods.

This error is instantly detected by intelisense who points out that the members aren't implemented.

---
#### Visual Studio Feedback System on 10/21/2019, 03:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
AfAICT, there's no way for C# to implement this at all.  So implement-interface tryign it's best here is fine.

**Comment by henke37** [comment]
That's my point! There isn't a way to do it with a nice named indexer, since those don't exist, so it must be done more bluntly with a pair of methods.

The current generated result is simply impossible to use. It treats it like a normal property, which is no good. The index must be available.

**Comment by CyrusNajmabadi** [comment]
> so it must be done more bluntly with a pair of methods.

Can you clarify how this can be done?

**Comment by henke37** [comment]
By simply defining the `get_registerValue` and `set_registerValue` methods directly.

**Comment by CyrusNajmabadi** [comment]
Can you be more explicit.  What should the signatures be there?  i tried `public ulong get_registerValue()` and `public void set_registerValue(ulong value)` and that did not work.

**Comment by henke37** [comment]
You need to include the index as the first argument.

**Comment by CyrusNajmabadi** [comment]
Got it.  reactivating.
