### ISSUE TITLE
IDE0054 and IDE0063 triggered when NOT using C#8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39430]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752720/ide0054-and-ide0063-triggered-when-not-using-c8.html)._

---
Problem since upgrading to VS Community 2019 16.3.

.Net Framework projects only support C#7.3, but various C#8 hints are triggered which lead to code changes that look valid in the IDE but do not compile (&quot;language feature XXX is not availabel in C#7.3&quot;). 

I can prevent this by manually disabling the rules in a .ruleset file, but it would be better to disbale rules automatically that target a higher version.

---
#### Visual Studio Feedback System on 9/28/2019, 07:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/30/2019, 00:25 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Tom Austin on 10/15/2019, 02:43 AM: 

<p>Is there anymore info on this? It's still an issue.</p>

#### sean on 10/17/2019, 00:48 PM: 

<p>I am using VS Professional 16.3.5 and am experiencing this issue.</p><p>I am using a type that implements `IDisposable`.</p><p>My csproj is an SDK style project.</p><p>It has `&lt;LangVersion&gt;latest&lt;/LangVersion&gt;` and `&lt;TargetFramework&gt;net472&lt;/TargetFramework&gt;`, so it is not a .NET Core project.</p><p><br>Do I have to explicitly set `&lt;LangVersion&gt;7.3&lt;/LangVersion&gt;` to not get the `IDE0063` recommendation?</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Both [IDE0054](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/UseCompoundAssignment/CSharpUseCompoundAssignmentDiagnosticAnalyzer.cs#L24) and [IDE0063](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementDiagnosticAnalyzer.cs#L71) check language version before offering. 

I was unable to reproduce this issue in 16.4P2 or 16.3.5 with netframework 4.7.2 and no langver set. 

If `LangVersion` is set to `Latest` then we expect both of these to be offered, since latest is c# 8.  It's recommended that netframework projects either use default or lower version than c# 8.

**Comment by cantak** [comment]
This is a bad answer. `latest` is not c# 8.0 when you are using .Net. You're saying that messages will include items that if I let the IDE handle will break my project? Really?

**Comment by nickdevore** [comment]
![image](https://user-images.githubusercontent.com/2029923/67333979-50f62c80-f4d6-11e9-8dc5-0381f04300f0.png)

If you attempt to change the value via the IDE for this (right click on project --> properties --> Build --> Advanced) you're no longer able to select a language version.  You'll have to make sure the `LangVersion` property in your .csproj file is `default`

**Comment by nvmkpk** [comment]
I am have 16.3.7 and my project targets .net framework 4.5.2. I do get IDE0063 suggested.

**Comment by sharwell** [comment]
@cantak `latest` is not a real version. If you use it, you are going to get different experiences across different versions of Visual Studio, and when you upgrade Visual Studio you might get changes in project behavior. The project maintainer also becomes fully responsible for manually ensuring the selected target framework(s) are compatible with the current compiler's interpretation of "latest", or else you end up in an unsupported scenario. I highly recommend setting `LangVersion` to a specific version in the project file, followed by using `default` as the second choice.

**Comment by NagayamaToshiaki** [comment]
This issue still happens on VS2022 Version 17.13.5.

**Comment by CyrusNajmabadi** [comment]
@NagayamaToshiaki please file a new issue with a repro.  Thanks.
