### ISSUE TITLE
To have a better pattern to remove the OOP and Servicehub related IVT types

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#39446]
Currently, we don't have a good pattern to give extern access when it comes to some classes related to OOP and ServiceHub related types.

Example:
Internal repos may have classes derives from the [ServiceHubServiceBase](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Remote/ServiceHub/Shared/ServiceHubServiceBase.cs)

Then it becomes troublesome, because this class can't be exposed via Interface and Wrapper types either they need to create their own ServiceHubBase. ([Example](https://github.com/Cosifne/testimpact/blob/dev/shech/SBDIVTRemove/src/Shared/ServiceHubBase/RolsynServiceHubBase.cs)) or move all the implementation to Roslyn

Problem of first approach:
Because PinnedSolutionInfo is internal, and session [classes ](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Remote/RemoteHostSessionHelpers.cs)in Roslyn like KeepLiveSession will some time pass PinnedSolutionInfo to the target ([Example](https://github.com/dotnet/roslyn/blob/0a497dde742a8aa9e7fe5457eba4109b737b3a1e/src/Workspaces/Core/Portable/Remote/RemoteHostSessionHelpers.cs#L194)). Then the host has to accept object type parameter. And to make things worse, RPC will just pass the JObject as the type at runtime, then we need to manually deal with the deserilization ([Example](https://github.com/Cosifne/roslyn/blob/shech/SBDIVTCleanUp/src/Workspaces/Remote/ServiceHub/ExternalAccess/UnitTesting/Api/UnitTestingPinnedSolutionInfoWrapper.cs)

Problem of the second approach:
The servicehub host class may reference other type in other repo, and since there is no MEF on OOP side. Then other team may need to move more and more classes to Roslyn. ([Example](https://github.com/dotnet/testimpact/blob/53f45b513a433629f14fb56fa3bfd472251db1a9/src/SourceBasedTestDiscovery/SourceBasedTestDiscovery/SourceLocation/OOP/RemoteTestSourceLocationLookupService.cs#L24))

**Comment by Cosifne** [comment]
@sharwell 
FYI

**Comment by CyrusNajmabadi** [comment]
This is entirely different now from when this was opened.  closing this out as not actionable.
