### ISSUE TITLE
Fly out menus trigger too fast and get in the way of primary menus. 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#39440]
Then menu rows are small, and the fly outs trigger too fast on hover, which often ends up triggering sub menus that then hide the original menu.

**Comment by jspinella** [comment]
I'm not sure what this has to do with Roslyn. Is this an ASP.NET Core Web App you're working with?

**Comment by jmarolf** [comment]
I bellieve @mikadumont is refereing to the flyouts on the lighbulb menus themselves:

![image](https://user-images.githubusercontent.com/9797472/67337123-530eba00-f4db-11e9-8b76-e30018c8f0e8.png)

**Comment by jinujoseph** [comment]
Tracked externally https://developercommunity.visualstudio.com/content/problem/52240/ctr-popups-will-overlap-when-showing-code-editors.html
