### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp puts a lot of resource litters in the output folder

### ISSUE THREAD

**Issue by nefcanto** [dotnet/roslyn#39458]
I don't use CodeAnalysis at all. But I don't know why, my output folder contains a lot of folders related to cultural resources of `Microsoft.CodeAnalysis.CSharp`.

I've asked it first [here](https://github.com/aspnet/AspNetCore/issues/15255).

Can you create a clean output folder when there is no need for localization resources?

**Comment by gafter** [comment]
@nefcanto Please provide a complete project that demonstrates the issue that concerns you, and identify what specific output folder you are talking about and which files you are referring to.

**Comment by nefcanto** [comment]
After upgrading to .NET Core 3.0, based on [this issue](https://github.com/aspnet/AspNetCore.Docs/issues/14593) I had to replace `RazorViewEngineOptions` with `MvcRazorRuntimeCompilationOptions` which is located inside `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` NuGet package. This package results in this bin folder:

![67266404-0e742600-f4bd-11e9-8a8c-3b59039bf5a2 1](https://user-images.githubusercontent.com/12782347/67550710-ff3ae580-f713-11e9-9fef-17e13f48b045.PNG)

And when I look inside each of these folders, I see this:

![image](https://user-images.githubusercontent.com/12782347/67550763-25f91c00-f714-11e9-823b-2239c0f98966.png)

Is this information enough?

**Comment by vankampenp** [comment]
I had the same issue. Same folders but content is 
Microsoft.CodeAnalysis.CSharp.resources.dll
Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
Microsoft.CodeAnalysis.resources.dll
Microsoft.CodeAnalysis.Workspaces.resources.dll

After removing
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />

From the project file it was resolved. I got that reference when scaffolding an addition to my project.

**Comment by jmarolf** [comment]
@nefcanto and @vankampenp 

if you are using the new sdk-style project format you can add this property to your project
```
<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
```

this should ensure that these resource dlls are not deployed

**Comment by nefcanto** [comment]
@jmarolf, that solved my problem. Thank you so much.

**Comment by jmarolf** [comment]
@nefcanto I am going to close this issue in that case. Things are working as designed

**Comment by svrooij** [comment]
> @Nefcanto and @vankampenp
> 
> if you are using the new sdk-style project format you can add this property to your project
> 
> ```
> <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
> ```
> 
> this should ensure that these resource dlls are not deployed

@jmarolf Why for heavens sake it this still an "issue" 4 years later. Who ever wants all those crazy resource files **for an analyzer**, that shouldn't even be deployed anywhere. Analyzers are run at build time right, there is absolutely no need to deploy these files ever. I added a package to my solution, and they just appeared.

**Comment by bugproof** [comment]
Every single time I deal with this. I don't even have `Microsoft.VisualStudio.Web.CodeGeneration.Design` anywhere in my projects. There should be more detailed instructions how to find the culprit package that causes this.
