### ISSUE TITLE
Find All References on variable cannot show initialisation code and total reference count at same time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39464]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/780519/find-all-references-on-variable-cannot-show-initia.html)._

---
[regression] [worked-in:12.0.40629.00 Update 5]
The results of a **Find All References for a variable** (local or global) in a C# Project **cannot show two bits of information at the same time** like VS2013 did:
1) You **cannot view how many references were found** unless you turn on Group by: Definition* (Any option that starts with 'Definition' in the name). In VS2013 this information was included in the tool window's title - very convenient and would be great to bring back (why was it removed?).

2) You **cannot view the variable's initialisation code** unless Group by: &quot;No Grouping&quot; is selected. When grouped by *anything* then the declaration of the variable is omitted (which can be convenient), however **it should never hide the reference where the variable was initialised** because this is a critical reference!

---
#### Visual Studio Feedback System on 10/17/2019, 03:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 03:47 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is a request for the platform to show those values better.
