### ISSUE TITLE
C# auto completion misses global scope resolution prefix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39469]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/782559/c-auto-completion-misses-global-scope-resolution-p.html)._

---
Pressing tab after an ``x = new`` statement, the C# auto completion does not prepend the `global::` keyword even though `x` is declared with it.

---
#### Visual Studio Feedback System on 10/17/2019, 10:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 03:52 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
Here is an example where this could be helpful:

```
namespace ClassLibrary1
{
    class System
    {
        void M()
        {
            global::System.AppDomainManager appDomainManager;
             // Try to type the following line:
            appDomainManager = new global::System.AppDomainManager();
             // Trying to type AppDomainManager refers to the local AppDomainManager not to the global one.
            // The question is how to get the global one.
        }

        private class AppDomainManager
        {
            public AppDomainManager(int i)
            { }
        }
    }
}
```

**Comment by ivanbasov** [comment]
Maybe we could find the declaration for the symbol and then check `IsGlobalAttribute(node)` for the corresponding syntax node.

**Comment by CyrusNajmabadi** [comment]
FWIW: It's always been by-design that what's on the right is the 'simplest' representation of the type of the thin on the left.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
