### ISSUE TITLE
 FXCop Analyzers setting Severity causes an error and strange behaviour

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39461]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/751814/fxcop-analyzers-setting-severity-causes-an-error-a.html)._

---
This problem started when i followed your message and installed the FXCop Analyzers into Visual Studio. 

I really like some warnings it gives but some specifying logging and naming conventions i want to ignore. So i tried to set the Severity of that issue to a certian level. No matter what level you will end up in an error (attached as PNG File).

Once Visual Studio encountered that error the spacebar, Backspace and Enter button on the keyboard sometimes do no longer work until you restarted Visual Studio. The rest of the Buttons functions as normal. 

This is an ASP .NET Core 3.0 Project that started with Preview 2 and is now updated to the latest release. The Rosyln Analyzers are updated 2.9.5-beta1.final. 

Visual Studio is running Version 16.3.0 Preview 3.
```
  &lt;entry&gt;
    &lt;record&gt;988&lt;/record&gt;
    &lt;time&gt;2019/09/27 12:12:11.168&lt;/time&gt;
    &lt;type&gt;Error&lt;/type&gt;
    &lt;source&gt;Editor or Editor Extension&lt;/source&gt;
    &lt;description&gt;System.NotSupportedException: Changing document &amp;apos;D:\PROJECTNAME\SOMEPATH\SOMEPATH\SOMEPATH\Views\SOMEVIEW\SOMEVIEWSFILE.g.cs&amp;apos; is not supported.&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace, IProgressTracker progressTracker, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, ImmutableArray`1 operations, IProgressTracker progressTracker, CancellationToken cancellationToken)&amp;#x000D; &amp;#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, ImmutableArray`1 operations, String title, IProgressTracker progressTracker, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument, IProgressTracker progressTracker, CancellationToken cancellationToken)&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&amp;lt;&amp;gt;c__DisplayClass20_0.&amp;lt;InvokeCore&amp;gt;b__0()&amp;#x000D;&amp;#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager, Object extension, Action action)&amp;#x000D;&amp;#x000A;--- End of stack trace from previous location where exception was thrown --- &amp;#x000D;&amp;#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;/description&gt;
  &lt;/entry&gt;
```

---
#### Visual Studio Feedback System on 9/28/2019, 06:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/30/2019, 00:33 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Manish Vasani [MSFT] on 10/16/2019, 04:45 PM: 

<p>Thank you for reporting the issue. I think this may have been fixed by <a target='_blank' href="https://github.com/dotnet/roslyn/pull/38200">https://github.com/dotnet/roslyn/pull/38200</a>, which was fixed in VS2019 16.4 Preview1. Would you mind installing the latest preview from <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview">https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview</a> and checking if it still repros?</p>

#### Sebastian on 10/17/2019, 01:42 AM: 

Hi, <br>yes it seems to work right now.<br><br>Only one small thing: Every second time i am setting a severity the recommendation window for the Roslyn anayzers pops up again on the top, even if they are installed. But this is not really annoying. <br><br>Thanks for fixing :)<br>
#### Manish Vasani [MSFT] on 10/17/2019, 05:43 AM: 

<p>&gt; Only one small thing: Every second time i am setting a severity the recommendation window for the Roslyn anayzers pops up again on the top, even if they are installed. But this is not really annoying.</p><p><br></p><p>Ah, I have seen that prop up a few times as well. I will try to harden the detection. Thanks!</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @mavasani for info
