### ISSUE TITLE
Live Share - Support Empty -> Nonempty Workspace

### ISSUE THREAD

**Issue by daytonellwanger** [dotnet/roslyn#39475]
Live Share recently added a feature for empty workspace sharing. After sharing an empty workspace, the host may then open a solution/folder. Today, Roslyn will not update its remote workspace to reflect the added solution/folder, which results in the absence of many language feature, e.g. FAR and go to def. Roslyn should subscribe to a "workspace roots changed event" and update the remote workspace appropriately.

**Comment by dibarbet** [comment]
Closing as dupe of https://github.com/dotnet/roslyn/issues/40362
