### ISSUE TITLE
Generate Type on 'VB Imports' does not generate proper Type

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#3948]
**Repro:**
1. Open a VB library
2. Set the editor to

``` VB
Imports Sample

Public Class C1
End Class
```
1. Place the cursor on the Imports statement and invoke the lightbulb on the import statement.
2. Choose the Code action to generate the type Sample

**Expected:**
 Type Sample gets referenced properly

**Actual:**
 Lightbulb still exists to generate type 'Sample'

**Comment by Pilchie** [comment]
I can't repro this.  I get the lightbulb back, but to remove the unused Import for Sample.

**Comment by basoundr** [comment]
It doesnt repro in EditorTestApp because ETA does not have a default namespace. Try repro-ing in Visual Studio.

**Comment by CyrusNajmabadi** [comment]
Unlikley to make any changes here given lack of feedback.
