### ISSUE TITLE
Null validation missing from collection initializer

### ISSUE THREAD

**Issue by FunctionalFirst** [dotnet/roslyn#39497]
Using .NET Core 3.0, the following call to `Add` produces the expected warning.
```c#
public class MyCollection : System.Collections.IEnumerable {
    public void Add<T>(T key, T value) {}   
    public System.Collections.IEnumerator GetEnumerator() => default!;
}

var c = new MyCollection();
c.Add("", null); //WARNING: Cannot convert null literal to non-nullable reference type.
```
But, the equivalent collection initializer compiles without warning.
```c#
var c = new MyCollection() {
    { "", null }	
};
```

**Comment by jcouv** [comment]
Relates to https://github.com/dotnet/roslyn/issues/43561 (enforcing attributes on the `Add` method used inside a collection initializer). We may be able to fix those together since same area of the code.

**Comment by RikkiGibson** [comment]
This appears to work in the most recent compilers. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4GIYFcA2OLA4CmABETAcQLABQtAbhAE4kDGJAvCTEQO4kBZAJ4BhAPZ4irAC5QxMABQBKANy1WAOgCCCBAoBE+uN1w5VJAPQWA6loBKAOQCSDgOIgSIiDBhjpbeXoiJn9sPBIcKGlgiBwSaTFueQBaMPxCUiYiADNg8lZSaSEAByINWgZmNgBGTm4+QVEJYhk5RSUSAG9aEl6ukkNjNJIAXwBIWhG1OhoAAQBmElmAJkbxSVb5Eg9Z6o11ltl5AGcNXcXumj6lxdmAFhIdBAAeABUAPgVXkgBrIiFjN9GDgsEQOp0Rn0en0Fks9gcpEcYKcnABRbBgGIJFiuIjSdFYTFMCDY5Scd4kBA5CC4aQAQmmI1oQA=)
