### ISSUE TITLE
Edit.GotoBrace, not multi-caret aware

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39507]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/784513/editgotobrace-not-multi-caret-aware.html)._

---
Tested in C#, but probably applies to any lanuage using braces.

Repro
```
  void fn1() { something1 }
  void fn2() { something2 }
```
- Select fn1's closing brace.
- execute Edit.InsertNextMatchingCaret. You should now have two carets.
- execute Edit.GotoBrace

Expected: Both carets still active, now before each functions opening brace.
Actual: Any secondary caret(s) dropped. Single caret placed before fn1's opening brace.

It would be nice if Edit.GotoBrace became multi-caret aware.

---
#### Jane Wu [MSFT] on 10/20/2019, 11:55 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing due to lacck of broad feedback on this.
