### ISSUE TITLE
Show reference to namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/438024/show-reference-to-namespaces.html)._

---
<p>On hovering above a ```using``` statement, the tooltip now shows only the name of the namespace — that's duplicate with what's already written in the code. It would be good to show all (or the number of) references to the specific namespace (i.e. where the non-fully-qualified type names in that namespace appear) in the document on the tooltip so that we could know whether it is frequently referenced or we can just fully qualify the only type name in the document instead of using a ```using``` statement.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/57176-screenshot.png"> Image:57176-screenshot.png</a></p>

---
#### Jane Wu [MSFT] on 1/29/2019, 02:24 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Simon Brand [MSFT] on 10/7/2019, 00:04 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by WrongBit** [comment]
I don't think such analytic should be in tooltip. More useful is to show in what assembly such namespace sit.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
