### ISSUE TITLE
Specifying a parameter on a method as a nullable enum with a default value displays the numeric value instead of the enum value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39502]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/789266/specifying-a-parameter-on-a-method-as-a-nullable-e.html)._

---
[regression] [worked-in:16.4.1 preview 1]
consider the code 
public enum MyEnums
{
   EnumValue = 1,
}
public class C 
{
  public void Method1(MyEnums? myParameter = MyEnums.EnumValue)
  {
  }
  public void Method2(MyEnums myParameter = MyEnums.EnumValue)
  {
  }
}

When using both methods, The intellisense tooltip for  myParameter will list myParameter = 1 for MyMethod1 (nullable) 
and will display the correct value for Method2 (EnumValue)

---
#### Visual Studio Feedback System on 10/24/2019, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/218860481-38623c9c-7820-4811-8a3a-7f3aa47d5c03.png)

![image](https://user-images.githubusercontent.com/4564579/218860512-2b1ed80d-07e3-4568-a443-58451442f232.png)

![image](https://user-images.githubusercontent.com/4564579/218860549-0d56b56d-281d-4387-98ff-7f87b103a431.png)

![image](https://user-images.githubusercontent.com/4564579/218860577-f72c8b5a-5804-49b5-bccc-608602105dd3.png)
