### ISSUE TITLE
Suggestion: Fix broken view auto-scrolling

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39505]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/789701/suggestion-fix-broken-view-auto-scrolling.html)._

---
Create a dummy cs file consisting of 50 linefeeds, then at line 50
`class C {}`
and then another 50-or-so linefeeds.

For the test I had 55 visible lines in the view (including one CodeLens line displaying 0), with font size set to 85% (if that makes a difference).

Repro:
- Place caret at start of line 50
- Scroll the view so line 44 is the first visible line.
- Ctrl+I, 'c' (i.e. incremental search for 'c'). OK.
- Back to beginning of line. Scroll up one line, so line 45 is the first visible.
- Ctrl+I, 'c'.

Expected: View stays put. Exactly the same as when line 44 was the first visible line.

Actual: View scrolls down so (in the test I did) now line 23 becomes the first visible. That's 22  lines of unwanted scrolling I won't ever get back (and in the real world it's code I referenced that has now vanished way out of sight and wasting my time).

Now for a real kicker; remove all trailing newlines, and try to repeat. All of a sudden it does _not_ scroll down, even if you start with line 49 as first visible.

This kinda suggests a rather massive bug in some &quot;MakeSureCaretIsVisible&quot; or similar method.

---
#### Visual Studio Feedback System on 10/22/2019, 10:01 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
I cannot repro the above behavior.
