### ISSUE TITLE
RFE: C#, copy fully qualified name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/784542/rfe-c-copy-fully-qualified-name.html)._

---
Use-case: Would be useful while documenting C#.
Priority: Low. Nice to have.
Feature precedence: Yes; `File.CopyFullPath`.

I found myself needing the fully qualified name to a type's member (in this case a method of a class, but any member or typename of &quot;anything&quot; applies), to use in reference documentation.

What I ended up doing was
- select member (name)
- copy
- swap document
- paste
- swap document
- ctrl+home
- down to enclosing typename line
- ctrl+right to typename
- select that
- copy
- swap document
- ctrl-left
- paste
- '.' (dot)
- swap document
- up to namespace declaration line
- ctrl+right to namespace decl.
- select namespace
- copy
- swap document
- left (over the dot)
- ctrl-left (to start of classname)
- paste
- '.' (dot)

Whew, typing it out, it surprised even me how many steps are actually required!

What would have simplified this _a lot_ would have been something like `Edit.CopyFullyQualifiedName`, probably tucked away under Edit/Advanced submenu. Then the workflow would have been
- select member
- CopyFullyQualifiedName
- swap document
- paste

Done.

Considerations:
While it makes sense to have this in the `Edit` namespace (where the handler could do preliminary checks like &quot;if multiple carets are active, don't even attempt the operation&quot;), it's definitely a language-specific operation, why it probably would need some plumbing added,  to ask the concrete language editor
- do you have support for this operation?
- is caret or selection on something you can perform this operation for?

and finally `Execute`.

If implemented, it could be nice to be able to do this even for references (as opposed to definitions). Say you have a subclass accessing something from a baseclass. To make it concrete, say you have class hierarcy C1 { mX } -&gt; C2 -&gt; C3, and in C3 you use C1's mX; it could then be nice to be able to copy the FQN of mX.

---
#### Jane Wu [MSFT] on 10/20/2019, 11:55 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by sharwell** [comment]
A possible workaround here is using Class View in Visual Studio. The Copy functionality in this view copies the fully-qualified name for types, and the type-qualified name for members.
