### ISSUE TITLE
Intellisense & Auto suggest registration of classes and interfaces with Unity  - in visual studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/373225/intellisense-auto-suggest-registration-of-classes.html)._

---
<p>When we use a DI tool like microsoft unity or AutoFac, while creating new classes and interface during the development, we sometimes forget to register the classes</p><p>Visual studio should detect the un-registered classes and suggest all the classes to be registered. </p>

---
#### Fiona Niu[MSFT] on 11/2/2018, 00:48 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by CyrusNajmabadi** [comment]
Closing out.  This can be done by an analyzer by the user or unity.
