### ISSUE TITLE
CompletionLists don't help make clear which object properties are nullable and which aren't.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#39516]
A picture to help show what i mean:

![image](https://user-images.githubusercontent.com/4564579/67534429-ee8e5f00-f682-11e9-8200-b2cf22ff5b63.png)

In this completion list, it is not easy to figure out which of these properties are required (i.e. must not be null) and which are optional.  Even though this property is marked as having a nullable return type, it's necessary to go and investigate the quick-info tooltip for each to discover that.  Contrast that with the TypeScript model of optionally-nullable properties:

![image](https://user-images.githubusercontent.com/4564579/67534537-652b5c80-f683-11e9-9472-8820f45ebcec.png)

Here it's trivial to see which properties would be required or not.  Just look for the `?` at the end of the property name.  

This 'lifting' of the information to be directly exposed on the completion list is *super useful* and makes it very clear what you really need to be providing, versus what you can optionally provide.

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph @jasonmalinowski .  This would be very nice to have with NRTs (and for nullable value types as well).  This is something i'd be happy to contribute if you were interested.  

Thanks!

**Comment by sharwell** [comment]
For the specific scenario in question, the C# objects would need constructor parameters for all required values. Otherwise, you'll end up with warnings in the objects that one or more values has not been set.

**Comment by sharwell** [comment]
Duplicate of #26489

**Comment by CyrusNajmabadi** [comment]
I don't think of this as the same thing.  There is an open question about if we might add the return type (and if that would be something you opt into/out-of).  However, unless we are saying we will always show teh return type, then there's a need to still know if the prop is nullable or not in a *quick* fashion. 

This is also more relevant now that NRTs are coming onto the scene.  The disparity here feels high, and I would prioritize getting this information in before working on getting return types in.

Can you:
1. consider reopening this?
2. consider taking the linked issue to a design meeting sooner?

I'd also like @jasonmalinowski's thoughts on this.  Right now, this experience feels 'not great'.  Would you guys be open to me contributing just the `? in completion` change, without trying to discuss or solve the issue of `return types in completion` change?

Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you provide a different motivating example? The scenario described above applies very clearly to TypeScript, but does not apply as described to C#.

**Comment by sharwell** [comment]
We'll take this to a design review earlier to consider the `?` suffix. For reference, I am currently opposed to this change for two reasons:

1. The comparison is made to TypeScript, but C# does not have any feature which maps to the TypeScript feature for which `?` is shown in completion lists.
2. C# already requires via constructors that required properties are initialized, and we already have clear signature help representation of this. Even if we wanted to highlight "optional" properties to help with using the object initializer syntax in combination with constructors, it likely wouldn't work as well as one would hope because there is no language mapping between constructor parameters and properties of the type.

**Comment by CyrusNajmabadi** [comment]
> C# already requires via constructors that required properties are initialized

Unfortunately constructors don't allow for things like collection initializers.  i.e. if you have:

```c#
new Foo
{
   SomeList = { a, b, c }
}
```

You cannot switch that easily to be a constructor:

```c#
new Foo(someList: { a, b, c })
```

That no longer works as this is no longer a property whose getter can give back the initialized list to add values into.  `newing` up the collection is also unpalatable here due to things like large type names.  Implicit arrays are also not possible here because there may be no common type of all the values in the list (but all the types may be convertible to the parameter type of the collections' `Add` method).

**Comment by CyrusNajmabadi** [comment]
NOte: this goes beyond the object initialization scenario.  This just plain affects all completion scenarios.  Here's hte issue:  right now there is no clear indication of which properties/fields are nullable.  So this means I'll common write similar to:


```c#
void Foo(PropertyInfo info)
{
     info.DeclaringType.GetMethod(...);
}
```

The problem here is that `DeclaringType` is nullable, so i'll either have to write this as:

```
info.DeclaringType!.GetMethod(...);
```

or 

```
info.DeclaringType?.GetMethod(...);
```

or

```
if (info.DeclaringType != null)
```

The problem though is that i don't know i need to do any of this until i get the warning message from teh compiler.  That's really unpleasant. 

The only other option is to carefully look at each completion item to see waht is in the quick-info list.  

I really want the completion list to tell me *up front* that the value could be null so i can write my code accordingly.

@jasonmalinowski for eyes.

**Comment by ryzngard** [comment]
There's a few things that I think would improve this experience: 

Reduce time it to takes to show the info for completion list. Right now it's 700ms, which is quite long. 
Make the info for completion match quickinfo. 

There is definitely hesitation on adding the "?" in the completion list. We don't have any type information there already. For the examples provided, I think enriching the experience with a better detail info experience will help.

**Comment by CyrusNajmabadi** [comment]
> For the examples provided, I think enriching the experience with a better detail info experience will help.

I'm not sure if that's really going to help out.  It would require manually going through and looking at each item one at a time.  That's a lot of effort to figure out this basic information.

For normal classes that are newable, but need their properties assigned post-construction, this just pushes the burden onto users to have to manually examine each and every property.

**Comment by ryzngard** [comment]
> For normal classes that are newable, but need their properties assigned post-construction, this just pushes the burden onto users to have to manually examine each and every property.

I don't think nullable reference types really define that contract though. Being nullable doesn't mean you _have_ to assign it. Not being nullable doesn't mean the value is useful.

**Comment by CyrusNajmabadi** [comment]
> I don't think nullable reference types really define that contract though

I do get that.  However, I think more often than not it *would* though.  If you have something settable and null/non-null it's a strong indication of intent of the api.  

There's a certain irony here too in that originally (prior to the work that is being done right now in the compiler) things like 'nullability' were stored at the Field/Property level in the compiler to indicate this information rather than storing them in the type itself.  There's a bit of a duality here in terms of how these can be thought of (and/or represented in the UI).  

But i'm not going to belabor the point.  If this isn't somethin you want to do, that's ok.  But i do ask that there be something to surface this sort of information better than having to look at each property one at a time.

**Comment by ryzngard** [comment]
> But i do ask that there be something to surface this sort of information better than having to look at each property one at a time. 

Would a different icon be sufficient? I still feel like adding the "?" doesn't really convey the information you want. I could also be stuck between the differences in typescript vs c#. In typescript, the "?" is indicating that a property doesn't have to exist at all right? I.e I could implement an interface and not have to provide properties that are marked with "?". You can't do the same in C#. The important bit here is that you need to know if a property you're working with can be null when you use it. Adding a "?" may fix the first handful of properties as you can gloss them, but what if there's 100 properties? It gets just as tedious at that point.

**Comment by CyrusNajmabadi** [comment]
> Would a different icon be sufficient?

Potentially!  Would certainly be willing to try that out.

> but what if there's 100 properties? It gets just as tedious at that point.

Hasn't gotten tedious in TS so far :D

**Comment by Joe4evr** [comment]
@sharwell 
> C# already requires via constructors that required properties are initialized

This is not always the case. Many a DTO framework out there require a public parameterless constructor and public settable properties to fill in values, which means you get this same problem when you want to construct such an object in code. See also dotnet/csharplang#2328 for a potential solution to that one.

**Comment by sharwell** [comment]
> Hasn't gotten tedious in TS so far :D

The meaning of `?` is _completely_ different in TS, so its usability has no real influence here. The concept it is presenting in TypeScript does not exist in C#.

Note that the main problem with the `?` suffix stemmed from an unresolvable ambiguity in the treatment of reads and writes. One user might be relying on `?` to determine whether or not the target is declared in a manner that would allow assigning null to it, while another user might be relying on `?` to determine whether or not the value might be null when read. As the left hand side of the expression in both cases, the information necessary to present this as a simple `?` does not exist (has not yet been typed).

> This is not always the case. Many a DTO framework out there require a public parameterless constructor and public settable properties to fill in values, which means you get this same problem when you want to construct such an object in code.

The C# language cannot today represent this requirement at all, so there isn't an obvious way to present the information in the IDE.

**Comment by CyrusNajmabadi** [comment]
> Note that the main problem with the ? suffix stemmed from an unresolvable ambiguity in the treatment of reads and writes. 

THere's no ambiguity to me.  The ? simply states: this property/field's type is *nullable*.  A piece of information that is supremely helpful to know when writing code.  I'm going to have to deal with that information *at some point*.  All i'm saying is that knowing it earlier, and in bulk, is nicer than learning it later, one at a time.

> The concept it is presenting in TypeScript does not exist in C#.

That is not hte argument i was making.  I was stating that the bulk presentation of these concepts is not "tedious" as andrew was worried about.

> The C# language cannot today represent this requirement at all, so there isn't an obvious way to present the information in the IDE.

Of course there is.  :) The IDE is not bound by the language.  It can choose to present things in ways that are still generally useful, even if only tangentially related to hte language proper.  For example, i find it super helpful to know *en masse* which methods are extension methods.  And i find it helpful to know that something is generic just by sight.  

The IDE could certainly present information *in some form* to let the user know that things are nullable.  I've proposed `?` as a simple and easy way to convey that, but i'm open to other ideas as well.

**Comment by CyrusNajmabadi** [comment]
> As the left hand side of the expression in both cases, the information necessary to present this as a simple ? does not exist (has not yet been typed).

I don't see why that is.  It doesn't matter if it's LHS/RHS/whatever.  The information is simply stating: this property was declared as nullable.   It could be something like `Foo?` it could be something like `Foo (declared as nullable)`.  It could be something like `(SpecialIcon) Foo`, etc. etc.  `?` is just a simple and pretty clear way to indicate this information.

**Comment by sharwell** [comment]
> The information is simply stating: this property was declared as nullable.

This is your interpretation. Even if this interpretation is obvious to you, it is fundamentally opposed to another completely valid interpretation of "might be null when read at this location".

> Of course there is. :) The IDE is not bound by the language.

The keyword in my statement is 'obvious'. Maybe we can find a way to present the information, but since it's not based on a specific language-supported representation of state, the result is not currently considered obvious.

**Comment by CyrusNajmabadi** [comment]
> This is your interpretation. Even if this interpretation is obvious to you, it is fundamentally opposed to another completely valid interpretation of "might be null when read at this location".

Then show both.  

FFS, i don't get the pushback here.  It's highly valuable to know this information.  Currently, the only approach is to simply write things out slowly, manually try to look at each bit of quick info, or wait for squiggles to show up.

*All* i'm asking for is that some effort be put in toward making this valuable information much more *apparent* for users to help aide in coding.  

*Today* coding with nullable on is a PITA.   I don't know how i can state that any simpler.  It entirely throws a wrench in the coding process as i write and have to continually go back and appease the diagnostic system.  At the very least, if i could get a little information that might make me consider this *as i'm typing that property* it would be valuable.  I can choose waht to do with that information, but it doesn't mean breaking the flow of coding.

**Comment by CyrusNajmabadi** [comment]
Let's step back:

Here's my general feedback.  Coding with nullable today is difficult and feels like it has more that interferes with flow.  I made some proposals that i thought might help *but i am not wedded to them*.  However, i think effort should be made to help with the problem *even if imperfect*.  I think having more information rather than less can help allow people to grok more at a glance instead of requiring more overt effort.

Finally, i brought up TS not because i feel that C#'s nullable is an exact match for TS's optional.  But because all the above applies in the TS case as well and demonstrates that *good enough* (though technically inaccurate at times) solutions can be *highly* beneficial.  In other words, trying to make something exact and perfect and totally in line with the language *is not* necessary, and can actively hamper and limit the benefits we can provide the user and the typing experience.  TS is used to demonstrate that that's the case in a *similar* (but not identical) scenario.

**Comment by Joe4evr** [comment]
> The C# language cannot today represent this requirement at all, so there isn't an obvious way to present the information in the IDE.

Which is why there's a proposal to make it representable.

**Comment by CyrusNajmabadi** [comment]
> Note that the main problem with the ? suffix stemmed from an unresolvable ambiguity in the treatment of reads and writes. 

For the object creation experience, it doesn't seem like there's any ambiguity.  You can do one of a few things in an object-creation like so:

```c#
new Foo
{
    Prop = ...
}

//

new Foo
{
    Prop = { ... }
}
```

The former will be a write, the latter will be a read.  In both cases, when i'm bringing up intellisense for `Prop` it's still useful to know how the prop was declared.  Because this is at object creation time, there can't have been former writes (in the user's code surrounding this code) to this property.  As such, even from the language's perspective, this prop will only have the nullability information it was *declared* with.  As such, i don't even see how there's any ambiguity.

**Comment by sharwell** [comment]
> Here's my general feedback. Coding with nullable today is difficult and feels like it has more that interferes with flow. I made some proposals that i thought might help but i am not wedded to them. However, i think effort should be made to help with the problem even if imperfect. I think having more information rather than less can help allow people to grok more at a glance instead of requiring more overt effort.

I agree. My push back is based on the fact that it is nearly impossible to change directions on a feature after we start presenting it to users. We're still in the very early days of establishing practices around NRT and I don't think we're at a point where we can commit to a specific experience without having a high degree of confidence in how the changes affect the broader development picture.

**Comment by CyrusNajmabadi** [comment]
Closing out.
