### ISSUE TITLE
Integration tests sometimes have broken installation

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#39517]
Tests:

Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicErrorListNetCore.ErrorList
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicErrorListNetCore.ErrorsDuringMethodBodyEditing
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicSquigglesNetCore.VerifySemanticErrorSquiggles
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorsDuringMethodBodyEditing
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorLevelWarning
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSquigglesNetCore.VerifySemanticErrorSquiggles
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSquigglesNetCore.VerifySyntaxErrorSquiggles
Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.OpenCSharpThenVBSolution
Roslyn.VisualStudio.IntegrationTests.Workspace.WorkspacesNetCore.ProjectReference

**Comment by dibarbet** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=401364&view=logs

**Comment by sharwell** [comment]
The tests are not flaky. Something broke the installation
![image](https://user-images.githubusercontent.com/1408396/67536392-c6efc480-f68b-11e9-8752-16e4bdaa4874.png)

**Comment by sharwell** [comment]
Full image

![image](https://user-images.githubusercontent.com/1408396/67536417-e8e94700-f68b-11e9-9263-840e36259372.png)

**Comment by dibarbet** [comment]
closed by https://github.com/dotnet/roslyn/pull/39587
