### ISSUE TITLE
Breaking change in 3.3.1

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#39524]
I have a library that has this call:
```cs
return new CSharpCompilationOptions(
    OutputKind.DynamicallyLinkedLibrary,
    allowUnsafe: true,
    specificDiagnosticOptions: CreateSpecificDiagnosticOptions(descriptors, suppressed));
```

It is compiled vs `Microsoft.CodeAnalysis.CSharp.Workspaces 3.0.0` and shipped in a nuget with dependency constraint `Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.0.0) `

Problem is if consumer of the library updates to `Microsoft.CodeAnalysis.CSharp.Workspaces 3.3.1` things explode:

```
System.MissingMethodException : Method not found: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String, System.String, System.String, System.Collections.Generic.IEnumerable1<System.String>, Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray1<Byte>, System.Nullable1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32, System.Collections.Generic.IEnumerable1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider, Boolean, Microsoft.CodeAnalysis.MetadataImportOptions, Microsoft.CodeAnalysis.CSharp.NullableContextOptions)'.
```

![image](https://user-images.githubusercontent.com/1640096/67604307-87a0a100-f77b-11e9-9c9e-8940ef357a16.png)

It is painful!

**Comment by CyrusNajmabadi** [comment]
@jaredpar @dotnet/roslyn-compat-council this is significant.  Anyone on 3.0 and using the primary (i.e. all `... = default`) constructor is broken by this change.  It seems to have come about in:  https://github.com/dotnet/roslyn/pull/37017

The new constructor was added, but no compat shim was put in place.  Not sure how this was missed by compat tools.

**Comment by CyrusNajmabadi** [comment]
Note: from @JohanLarsson:

```c#
new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
```

The only option that seems to be available is for customer to have to supply *every* parameter to the full constructor.  Trying to have anything defaulted will just be broken.

**Comment by JohanLarsson** [comment]
Workaround:
Use this constructor:

```cs
return new CSharpCompilationOptions(
    outputKind: OutputKind.DynamicallyLinkedLibrary,
    reportSuppressedDiagnostics: false,
    moduleName: null,
    mainTypeName: null,
    scriptClassName: null,
    usings: null,
    optimizationLevel: OptimizationLevel.Debug,
    checkOverflow: false,
    allowUnsafe: false,
    cryptoKeyContainer: null,
    cryptoKeyFile: null,
    cryptoPublicKey: default,
    delaySign: null,
    platform: Platform.AnyCpu,
    generalDiagnosticOption: ReportDiagnostic.Default,
    warningLevel: 4,
    specificDiagnosticOptions: specificDiagnosticOptions,
    concurrentBuild: true,
    deterministic: false,
    xmlReferenceResolver: null,
    sourceReferenceResolver: null,
    metadataReferenceResolver: null,
    assemblyIdentityComparer: null,
    strongNameProvider: null,
    publicSign: false,
    metadataImportOptions: MetadataImportOptions.Public)
```

**Comment by agocke** [comment]
Investigating, this is the result of us moving NullableContextOptions from Microsoft.CodeAnalysis.CSharp to Microsoft.CodeAnalysis. Since type forwards cannot support name changes, I'm not sure there's anything we can do here. ☹️ 

If we change the name to the 3.0 version, we'll break everyone compiling against 3.3. Leaving it as it is breaks 3.0.

Unfortunately I have to recommend we do nothing, and consumers will have to upgrade or call one of the overloads, as mentioned previously.
