### ISSUE TITLE
Regression in VS2015 Go To Definition behavior with WPF projects.

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#3952]
When working on WPF projects, I've noticed a regression in Go To Definition behavior. When pressing F12 on a constructor for a class defined in `.xaml` and code, it now jumps to the XAML instead of the constructor. 

Repro:
1. New WPF Project
2. New class:
```CSharp
 class Class1
    {
        public Class1()
        {
            var x = new MainWindow(); //F12 on MainWindow
        }
    }
```

3. Press F12 on `MainWindow()`.

**Expected behavior (VS2013):** Jump to code-behind constructor.

**Actual (VS2015):** Jumps to XAML declaration.

VS 2015
![image](http://i.gyazo.com/f4a599e65a1271714e14cbe7c7992be1.gif)

VS 2013
![image](http://i.gyazo.com/7d1ea8d211dd0c3bcbc91dd77a9ec10b.gif)

**Comment by Pilchie** [comment]
Tag @dpoeschl.  I think we fixed this recently.

**Comment by Pilchie** [comment]
@JoshVarty is this still an issue with the VS2015 RTM build?

**Comment by dpoeschl** [comment]
Yes, this was fixed for RTM, and it does not reproduce for me locally. @JoshVarty Please let me know if you're still seeing this against RTM.

**Comment by JoshVarty** [comment]
Tried it just now and it looks good to me, thanks guys!
