### ISSUE TITLE
VS 16.3.0 Preview 2 - Error List IDE0047 Description Blank

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39529]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/716124/vs-1630-preview-2-error-list-ide0047-description-b.html)._

---
The error list is missing a description for IDE0047. See attached screenshot.

---
#### Visual Studio Feedback System on 8/28/2019, 09:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 8/29/2019, 09:50 AM: 

<p>Please provide the snapshot of the behavior. It’ll help us understand the issue better.</p>

#### bugreporter5367 on 8/29/2019, 10:19 AM: 

Please see attached repro project.
#### bugreporter5367 on 10/16/2019, 01:43 PM: 

@jinujoseph Reattaching the sample repro. I just confirmed that it still repros with VS 16.4.0 Preview 2.0.
#### Jinu Joseph [MSFT] on 10/16/2019, 01:29 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/5345/8c9648eb-1a63-6b24-a66b-43ffcbbc2ad3.html" nodeid="5345">@bugreporter5367</a>, unfortunately, the repro project is missing from the attachment. Could you pls update to the latest build and see if you still see this issue and if so could you try reattaching the project again pls. </p><p>We have not been able to repro this issue. Sorry for the inconvinence caused.</p>

#### Jinu Joseph [MSFT] on 10/16/2019, 01:54 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/5345/8c9648eb-1a63-6b24-a66b-43ffcbbc2ad3.html" nodeid="5345">@bugreporter5367</a> thanks much for the project . I have a repro now</p>

#### Visual Studio Feedback System on 10/16/2019, 01:57 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment]
Resolved in https://github.com/dotnet/roslyn/pull/39649 for 16.5P2
