### ISSUE TITLE
DeclarationNameCompletionProvider fails to resolve proper overload with out parameter

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#39539]
**Version Used**: 
VS16.4 P2

**Steps to Reproduce**:

```
            int.TryParse("", out var $$);
```

**Expected Behavior**:
No suggestions (as disabled for int).

**Actual Behavior**:
`numberStyles`, `number`, `styles` etc. 
There is TryParse overload with `StringStyles` second parameter, but it does not work here, as it is not `out`.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
