### ISSUE TITLE
DeclarationNameCompletionProvider should suggest out parameter name

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#39538]
**Version Used**: 
VS16.4 P2

**Steps to Reproduce**:
```csharp
            bool TryGetSomething(out string resultValue)
            {
                resultValue = "";
                return true;
            }

            TryGetSomething(out $$);
```

**Expected Behavior**:
I would expect to have `resultValue` name suggested. It probably should have higher priority than names suggestions based on type.

**Actual Behavior**:
For string/int/etc : no names suggestions
For other types : names suggestions only based on argument type.

**Comment by jinujoseph** [comment]
cc @ivanbasov

**Comment by CyrusNajmabadi** [comment]
This is how the feature works: 

![Image](https://github.com/user-attachments/assets/07274498-7f13-4068-9aba-45dfc0c666fb)
