### ISSUE TITLE
Add Import not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39531]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/623872/add-import-not-working.html)._

---
After updating to 16.2.0 preview 3 the import namespaces feature (when you do Ctrl + . ) stopped working

System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.GetPackageSources()
   at async Microsoft.CodeAnalysis.AddImport.AbstractAddImportCodeFixProvider.RegisterCodeFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Visual Studio Feedback System on 6/27/2019, 01:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/27/2019, 10:19 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Joey Robichaud [MSFT] on 6/27/2019, 00:50 PM: 

<p><a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/623872/add-import-not-working.html#">@yfernandes</a> Sorry that we broke you. We introduced a bug in Preview 3 when querying NuGet packages that has already been resolved for the final release. </p><p>Can you find the Using Directives group in Tools &gt; Options &gt; Text Editor &gt; C# &gt; Advanced and try turning off `Suggest usings for types in NuGet packages`?</p><p>Please let me know if you still have any more trouble.</p><p>-Joey</p>

#### sean on 10/24/2019, 07:30 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/121162/89b8f6bd-9749-64cb-af6c-bac9620d9d84.html" nodeid="121162">@Joey Robichaud [MSFT]</a> This appears to still be broken in 16.3.6, however the solution of disabling "Suggest usings for types in NuGet packages" did solve the problem for me.</p><p>This bug is brutal, because the cause (and solution) isn't obvious and importing usings is such a common practice, not having it kills productivity.</p>

#### Joey Robichaud [MSFT] on 10/25/2019, 02:16 PM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/33952/sean.html">sean</a> I was wondering if you could help me with some steps to reproduce your issue?</p>
<p>I expected a minimal repro with 16.3.5 to be:</p>
<ol>
<li>Create new Console app project</li>
<li>Inside the Main method type <code>JsonConvert</code></li>
<li>Press ctrl+. to bring up quick fixes</li>
</ol>
<p>Expected Outcome:<br>
Suggestion to import Newtonsoft.Json</p>
<p>Actual Outcome:<br>
Gold bar warning that CSharpAddImportCodeFixProvider had encountered an error.</p>
<p>However I am not getting an error locally.</p>
<p>-Joey</p>

#### sean on 10/25/2019, 02:53 PM: 

<p>Joey,</p><p>I'm not sure how to reproduce the issue - however I'm on 16.3.6.</p><p>The issue I originally reported was closed and my voted was merged into this one.<br>In my original issue I reported my VS version was 16.3.6 and the issue appeared after upgrade from 16.3.5.</p>

---
### Original Solutions
(no solutions)

**Comment by GeertVL** [comment]
I got the same issue after installing 16.3.6 and by creating a simple new class library. 
Even the nuget package manager cannot open anymore.

**Comment by br3nt** [comment]
I just followed the instructions:

> Can you find the Using Directives group in Tools > Options > Text Editor > C# > Advanced and try turning off `Suggest usings for types in NuGet packages`?

I can confirm that after deselecting `Suggest usings for types in NuGet packages` and then resarting VS, the `using <package>`  option was appearing i the suggestion context menu and the error was no longer occurring.

**Comment by br3nt** [comment]
A followup to my last comment....

I just noticed that when unchecking `Suggest usings for types in NuGet packages`, it also removes the `Manage NuGet Packages...` option when right clicking on the project's Dependencies folder.

I also now have issues with the Package Manager Console where it is getting stuck on `Initializing PowerShell host...` which I wasn't experiencing before.

Checking `Suggest usings for types in NuGet packages` brings back the `Manage NuGet Packages...` option, but I'm still stuck with the `Initializing PowerShell host...` bug.

**Comment by br3nt** [comment]
Is this bug mentioned by the OP some how related to or have a connection with the bug mentioned [here](https://developercommunity.visualstudio.com/content/problem/784506/package-manager-multiple-errors-displayed-on-tools.html)??

**Comment by daveaglick** [comment]
I was having the same problem - the CSharpAddImportCodeFixProvider kept crashing and I wasn't getting "add using" code fixes. Turning off "Suggest usings for types in NuGet packages" resolved the issue for me.

**Comment by pranavbhagwat81** [comment]
I have tried Turning off "Suggest usings for types in NuGet packages". still I have the same issue.
