### ISSUE TITLE
C# pattern match crashes VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39548]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/784408/c-pattern-match-crashes-vs-2019.html)._

---
In VS 2019 16.3.5, or 16.4P2, open C# interactive and type the following:
```
var x = (false, 4);
x is (false, var y)
```
Press enter after `;`
Expected the second expression to evaluate to `true`,
but instead right after typing the last `)` VS hangs then restarts.

---
#### Visual Studio Feedback System on 10/20/2019, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:11 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Robert Larkins on 10/27/2019, 11:04 PM: 

<p>I was able to replicate this on 16.3.6.</p>

---
### Original Solutions
(no solutions)

**Comment by agocke** [comment]
@gafter Could you take a look?
