### ISSUE TITLE
Completion lists show "starting intellisense" forever

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#39541]
![image](https://user-images.githubusercontent.com/4564579/67625827-13581300-f7f8-11e9-9a4d-31e7dbbe1adf.png)

Clicking view status only shows me this:

![image](https://user-images.githubusercontent.com/4564579/67625829-1bb04e00-f7f8-11e9-9a8b-0d647ca3fcb4.png)

**Comment by CyrusNajmabadi** [comment]
tagging @sharwell @jinujoseph

**Comment by jnm2** [comment]
I'm also seeing a full-page "loading intellisense..." marquee instead of a diff view when I open the triple-paned merge conflict resolution window. It never completes. To use the merge view, I have to close it, wait long enough, and open the merge view again.

**Comment by dibarbet** [comment]
@CyrusNajmabadi @jnm2 just want to confirm, which version is being used?  the latest preview build (16.4P2)?

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/67721885-de34f780-f994-11e9-8fec-02e5d247192e.png)

Yes.  Tons and tons of problem with this release.

**Comment by dibarbet** [comment]
The 'wait that doesn't finish' should be fixed in 16.4 P3 or GA in the VS platform.  I'll leave this open until I verify which release it makes it into.

**Comment by CyrusNajmabadi** [comment]
@dibarbet for my own edification, what issue was causing this?  Thanks!

**Comment by dibarbet** [comment]
It's related to partial load mode, paraphrasing what the VS project people said - the operation progress service was not using JTF, so if there was work being done on the UI thread to complete PLM (e.g. some parts of the design time build) then it could (cancellably) deadlock.

**Comment by dibarbet** [comment]
This should have been fixed in 16.4 GA.

**Comment by amirburbea** [comment]
Bug has reappeared in release edition of VS
