### ISSUE TITLE
Intellisense suggests Nullable<T> properties in property pattens

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/roslyn#39555]
**Version Used**: 
Visual Studio 2019 16.3.0

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```
**Steps to Reproduce**:

Insert this code and trigger intellisense inside the inner braces

```csharp
 public void M()
        {
            int? a = 0;
            int b = a switch
            {
                {  }//trigger intellisense inside these braces
            };
        }
```

**Expected Behavior**:

Not suggest `Nullable<T>` properties since the `{ }` expression implies non-nullity

**Actual Behavior**:

`Nullable<T>` properties `HasValue` and `Value` are suggested, but subsequently do not compile if used.

![Screenshot_4](https://user-images.githubusercontent.com/10837869/67712677-72518f80-f992-11e9-81eb-c3f916517bc4.png)

![image](https://user-images.githubusercontent.com/10837869/67713050-1804fe80-f993-11e9-9990-c8a449b344b1.png)

**Comment by AlgorithmsAreCool** [comment]
@jinujoseph  I'm not sure if this applies to Nullable Reference Types. I'm using old school `Nullable<T>` here.

**Comment by ryzngard** [comment]
Looks like pattern matching intellisense bug. My guess is this would trigger using the 'is' operator as well

**Comment by CyrusNajmabadi** [comment]
I don't repro anything here:

![image](https://user-images.githubusercontent.com/4564579/152903605-6f507267-d032-4188-a7de-a8fd26149f69.png)

We get no intellisense at all in these braces.

**Comment by sharwell** [comment]
And verified that for more complicated types, we get members:
![image](https://user-images.githubusercontent.com/1408396/152904111-87ee65b9-176b-4ab7-8096-75894c6e22b3.png)

**Comment by AlgorithmsAreCool** [comment]
Thank you mysterious stranger who fixed this at some point!
