### ISSUE TITLE
To prevent an unsafe abort when evaulating the function

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#39559]
![image](https://user-images.githubusercontent.com/1640096/67725841-0ac43000-f9e4-11e9-9668-4e07d9b64f7a.png)

Have seen ^ somewhat frequently while debugging lately.

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by plnelson** [comment]
Besides changing the code to avoid taking locks, a workaround is to uncheck "Enable property evaluation and other implicit function calls" in Options -> Debugging -> General.  I temporarily do that when debugging code that takes locks within property getters or ToString implementations.

It's good practice to avoid code that may deadlock inside functions the debugger might try to evaluate - property getters, ToString, DebuggerDisplay, etc.

**Comment by ranjan-ranjan** [comment]
https://stackoverflow.com/a/53060625/5035500

**Comment by 333fred** [comment]
That link is unrelated to this issue. Tomas has pointed out the likely cause for roslyn specifically.

**Comment by Techtonictools** [comment]
While using Nunit v3.12.0 and stepping through code in a dotnet core 3.1 library on Windows 10 with VS 2019 v16.5.0, this dialog appears more often than not. The difference being the "function". In my case this last time the dialog stopped everyting, the function was System.DateTime.ToString. 

I've hit it countless times in the past two hours and it is disruptive. It has been happening not just today, but every day. Any work-arounds would be **deeply** appreciated.

**Comment by 333fred** [comment]
@Techtonictools this repository is unable to help with failures related to `System.DateTime`. If you're seeing debugability issues with things in the core library, the appropriate repo to file that on is dotnet/runtime.

**Comment by tinmac** [comment]
Neither of these settings averted the error:
 Options -> Debugging -> General
- Uncheck 'Enable property evaluation and other implicit function calls'   
- Check 'Use Managed Compatibility Mode'

**Comment by HughWarrington** [comment]
What does the message even mean? What is an "unsafe abort"? All google results for that phrase lead back only to discussion of this one error message!

Also, the Help button takes you to a page which makes no reference to the message.

**Comment by MAkif06** [comment]
Hi, when run .net application I am getting this error: "To prevent an unsafe abort when evaluating the function System.Linq.SystemCore EnumerableDebugView<T>.Items.ge t' all threads were allowed to run. This may have changed the state of the process and any breakpoints encountered have been skipped" . In addition that this exception, I also get this error : "Invalid object name 'Platform_AdminUser_Permission". I tried your advices for the first exception but nothing change, do you have any ideas for the second exception ?

**Comment by tmat** [comment]
@MAkif06 You'll need to ask whoever provides the API you're calling. This is not a Roslyn API, so we won't be able to help here.

**Comment by MAkif06** [comment]
Thanks for your answer

**Comment by JamesNK** [comment]
I frequently see `To prevent an unsafe abort when evaluating the function` when debugging Protobuf messages. For example:

![image](https://github.com/dotnet/roslyn/assets/303201/08e9eb7f-d534-4506-abf7-109639dceec6)

I think the cause might be [a lock around a dictionary](https://github.com/protocolbuffers/protobuf/blob/e912bc2e3a1d187148f1dbc078d1f41fc398cf0c/csharp/src/Google.Protobuf/JsonFormatter.cs#L976-L983) in the Google.Protobuf package.

Will changing this lock to `ConcurrentDictionary` solve the problem?
