### ISSUE TITLE
SymbolTreeInfo is ignoring extension method from VB compiled PE reference

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#39558]
Here's the code that builds SymbolTreeInfo for metadata:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/SymbolTree/SymbolTreeInfo_Metadata.cs,393

The problem is the IL for module contains extension methods in VB looks like this (i.e. sealed but not abstract):
![image](https://user-images.githubusercontent.com/788783/67721576-1f78d780-f994-11e9-8efa-d5b5e6f81164.png)

One issue this causes is "add using" won't be able to fix a reference to extension method declared in such a metadata reference.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and that we're unlikely to change these experiences.
