### ISSUE TITLE
Rename NewLinesForBracesInObjectCollectionArrayInitializers to NewLinesForBracesInExpressions

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/roslyn#39557]
Split off from #36913, [as mentioned by @sharwell](https://github.com/dotnet/roslyn/issues/36913#issuecomment-546015089):

> Design review conclusion:
>  * ~For fixing this issue (#39396), we should use NewLinesForBracesInObjectCollectionArrayInitializers.~ Done in #36913
>  * We should rename NewLinesForBracesInObjectCollectionArrayInitializers to NewLinesForBracesInExpressions, and update the Tools → Options and .editorconfig strings to reflect this change. @tiesmaster has the option of implementing this in #39396, or we can implement it separately.
>  * We should verify that pattern matching braces are also controlled by NewLinesForBracesInExpressions.

**Comment by tiesmaster** [comment]
@sharwell I'm going to try to tackle this, however, I was wondering if any backwards compatibility needs to be taken into account? And if so, how?

**Comment by sharwell** [comment]
@tiesmaster We already renamed this .editorconfig property once. You can approach it the same way. Here's the old property from the first time:

https://github.com/dotnet/roslyn/blob/d025402fd8fd05067358082bc5426103e6a4a810/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs#L51

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative and due to no movement.
