### ISSUE TITLE
IntelliSense don't suggest return-types for local function with modifiers

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#39579]
**Version Used**: 
VS 16.4.0Preview2

**Steps to Reproduce**:

1. Remove the return type of local function, and typing it again;
```cs
        public static void Method()
        {
            static void XXX() { }
            async Task YYY() { }
        }
```

**Expected Behavior**:
Type will be suggest for the place after modifiers.

**Actual Behavior**:
No intellisense is shown after `static`;
Only `void` and another `async` is shown after `async`;
![image](https://user-images.githubusercontent.com/1819074/67825916-da74b280-fb05-11e9-9006-2f328c77c988.png)

Only another `async` is shown after `static async`;

**Comment by CyrusNajmabadi** [comment]
Not repro:

![image](https://user-images.githubusercontent.com/4564579/199311211-743a6811-4252-4c22-a8eb-770286477045.png)
