### ISSUE TITLE
Automatic indentation issue with tabs

### ISSUE THREAD

**Issue by jbevain** [dotnet/roslyn#39591]
**Version Used**: 
VisualStudio.16.Release/16.3.7+29424.173
Microsoft .NET Framework Version 4.8.03752
C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b

**Steps to Reproduce**:

1. Create C# project,
2. Set C# editor to use the superior and one true setting, `Keep tabs`,
3. Input following code:

```csharp
namespace CSProjConsole
{
	class Program
	{
		static void Main(string[] args)
		{
			switch (args.Length)
			{|CARET|}
		}
	}
}
```

As in:

![image](https://user-images.githubusercontent.com/79284/67904524-d491c800-fb2b-11e9-8f3d-c3d97c9ce487.png)

4. Press enter

**Expected Behavior**:

![image](https://user-images.githubusercontent.com/79284/67904321-3b62b180-fb2b-11e9-84fd-e9ba55e9ae1a.png)

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/79284/67904295-2ab23b80-fb2b-11e9-85dd-91fdfa460818.png)

There are 3 spaces in front of the `}`, which are the number of tabs that should have been inserted.

**Notice that this doesn't happen if you choose the inferior setting "Insert spaces"**

**Comment by CyrusNajmabadi** [comment]
Spaces FTW.

Note: i fixed this here: https://github.com/dotnet/roslyn/pull/38893
Will be in the next VS update.  Cheers!

**Comment by jbevain** [comment]
Beautiful, thanks!

**Comment by CyrusNajmabadi** [comment]
You're welcome!
