### ISSUE TITLE
Unexpected CS0146 When Inheriting from a Nested Class

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#39603]
**Version Used**: 
VS 2019 16.4 Preview 2 (latest public preview)

**Steps to Reproduce**:

```
class A : A.B { // <- Error	CS0146	Circular base class dependency involving 'A.B' and 'B'

  class B { }

}
```

**Expected Behavior**:
There should be no error, because class `B` is simply nested for convenience purposes, but otherwise has no dependence on class `A` (apart from the fact that `A`'s private members would be accessible, but in this case there is no code in `B` that references anything from `A`).

**Actual Behavior**:
Error CS0146

**Additional Info**:
Also VS 2019 16.4 Preview 2 crashes when I hover over red squiggles under `class A` with a message box saying _A new guard page for the stack cannot be created._:

```
Faulting application name: devenv.exe, version: 16.4.29411.138, time stamp: 0x5da11b53
Faulting module name: KERNELBASE.dll, version: 10.0.17134.799, time stamp: 0x0117c7be
Exception code: 0xe0434352
Fault offset: 0x00112c92
Faulting process id: 0x6548
Faulting application start time: 0x01d58fc482200bce
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 906c8fcd-91f7-45e3-9220-c8cdb09f8fd6
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by gafter** [comment]
The specification says

> It is a compile-time error for a class to depend on itself. For the purpose of this rule, a class **_directly depends on_** its direct base class (if any) and _directly depends on_ the nearest enclosing class within which it is nested (if any). Given this definition, the complete set of classes upon which a class depends is the transitive closure of the _directly depends on_ relationship.
