### ISSUE TITLE
Test plan for "static lambdas"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#39606]
Championed issue: https://github.com/dotnet/csharplang/issues/275
Speclet: https://github.com/dotnet/csharplang/blob/master/proposals/static-lambdas.md
Main PR: https://github.com/dotnet/roslyn/pull/39121

## Compiler scenarios
- [x] LangVer (`DisallowInNonPreview`)
- [x] static lambda cannot reference locals, parameters or `this` (`StaticLambdaCannotCaptureInstanceField`, `StaticLambdaCannotCaptureParameter`, `StaticLambdaCannotReferenceBase` and following)
- [x] static lambda can reference static fields/methods/properties (`StaticLambdaCanReferenceStaticField`, `StaticLambdaCanCallStaticMethod` and following)
- [x] static lambda can reference `const` field/local (`StaticLambdaCanReferenceConstField` and following)
- [x] static lambda inside regular lambda (`InstanceLambdaCannotHaveLocalsCapturedByInnerStaticLambda`, 
- [x] regular lambda inside static lambda (still cannot capture outer locals, parameters or `this`) (`StaticLambdaCanHaveLocalsCapturedByInnerInstanceLambda`
- [x] similar mixing of static and regular with lambdas and local functions (`StaticLambdaCannotReferenceInstanceLocalFunction`, `StaticLambdaCanReferenceStaticLocalFunction`, `StaticLambdaCannotHaveLocalsCapturedByInnerStaticLambda`, `StaticLambdaCanHaveLocalsCapturedByInnerInstanceLocalFunction`): outer and inner, either may be lambda or local function, either may be static or instance, check referencing variables from outer and middle scope.
- [x] verify `nameof` (can still reference)
- [x] can reference type parameters from enclosing method (`default(T)`), should be same as local functions
- [x] verify with various lambda syntaxes (with/without types)
- [x] test in top-level statements, with `nint`, 
- [x] success cases should be executed (produce an output), verify diagnostics and emit diagnostics
- [x] `static delegate` (including parse tree test)
- [x] parse tree test for all supported lambdas
- [x] verify accessibility of private members (instance and static)
- [x] capture what metadata we emit (although no guarantee, same IL as non-static lambda to avoid inefficiency)
- [x] `static` should not interfere with caching (this falls under the "should not effect emit/validity" umbrella)
- [x] verify that static lambda can be used in expression tree
- [x] verify semantic model, verify symbol API, (verify `.IsStatic`), verify data flow
- [x] verify IOperation (`IAnonymousFunction`, symbol covers need for API)
- [x] Static anonymous funcs as call arguments:
  - [x] `M(static ...)`
  - [x] `M(ref static ...)`
  - [x] `M(param: static ...)`
  - [x] Also indexers: `obj[static ...]` and variants
- [x] test with lambda discard parameters
- [x] test in ternary (with cast on one side, or with target-typing with new feature), ref ternary (error), and switch expression
- [x] review language parser for "is possible lambda" function
- [x] check diagnostic and parse tree on trying to convert a static lambda to a function pointer (review message)

## Productivity
- [x] ~~converting static anonymous function to static local function~~ This refactoring does not seem to exist for regular anonymous functions.
- [ ] make anonymous function 'static' #45832 
- [x] recommend `static` keyword
- [x] verify what captures are displayed (empty set)
  - in practice we display whatever is being captured, including things which are an error to capture.

## LDM
- [x] confirm `static delegate` (current implementation allows)

**Comment by huoyaoyuan** [comment]
> recommend `static` keyword

Please take in mind for an option to **not** suggest `static` keyword.
Many short lambdas, especially in LINQ, will look very redundant with `static`.

**Comment by CyrusNajmabadi** [comment]
@huoyaoyuan this just means: as the user is typing, the completion list should offer the `static` keyword to ensure that they can quickly complete to it instead of having to type the whole word out.

**Comment by huoyaoyuan** [comment]
Well I misunderstood as an IDE diagnostic like static local functions.
`readonly` structs and struct members both became available with no keyword recommender support. I guest you were too busy for the due date.

**Comment by CyrusNajmabadi** [comment]
> readonly structs and struct members both became available with no keyword recommender support. I guest you were too busy for the due date.

That sounds like something was simply missed in the test plan.  It's normally a requirement that new syntactic forms be supported in intellisense for a lang feature to ship.

**Comment by jcouv** [comment]
The feature was merged and open test plan follow-ups have tracking issues. I'll go ahead and close the test plan.
FYI @jaredpar
