### ISSUE TITLE
Crash from closed textview in visual tree in dialog page

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#39601]
**Version Used**: 
Visual Studio 2019 16.4 Preview 2

**Steps to Reproduce**:

Intermittent repro that's received a fair bit of feedback internally.

1. Tools > Options > C# > Code Style (perhaps via Ctrl+Q).
2. Switch to another pane and back several times
3. Close tools options
4. Re-launch to the same page

**Expected Behavior**:

Page opens.

**Actual Behavior**:

VS intermittently crashes with an ObjectDisposedException in an Editor margin from the embedded textviewhost.

The problem seems to be in the way that [AbstractOptionPreviewViewModel](http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.Implementation/Options/AbstractOptionPreviewViewModel.cs,9a39115621aed465) provides the textviewhost to the view.

When the dialog page closes, a code path calls Dispose on the ViewModel, closing and clearing the textviewhost.

My theory is that this happens after the UI has been dismissed (at least part of the time) leading to no databinding update for the text view host's binding in the UIElementDialogPage, keeping the view in the visual tree. UIElementDialogPages appear to stick around for the entire VS session, so, the next launch of the dialog, the old textview is in the visual tree, and if the initial layout triggers a SizeChanged event, causes a crash.

**Root cause:**

The exception stems from a recent change in Editor, which listens to the SizeChanged event on a Disposable object.

I'm making changes on our side to make this scenario less likely to throw, but from a local repro, it seems that Roslyn is intermittently keeping around a closed view when dialog page closes, which is at best a leak, and at worst, a potential reliability issue.

**Comment by gundermanc** [comment]
Editor improvements: https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/211434?_a=overview

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
