### ISSUE TITLE
Generate object creation expression

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#3960]
Hi,
Basically I am trying to generate ```new System.DateTime(ticks)```

Here is code I am using:
```
SyntaxFactory.ObjectCreationExpression(
    SyntaxFactory.QualifiedName(SyntaxFactory.IdentifierName(nameof(System)), SyntaxFactory.IdentifierName(nameof(DateTime))),
    SyntaxFactory.ArgumentList().AddArguments(SyntaxFactory.Argument(SyntaxFactory.IdentifierName("ticks"))),
    null);
```

But it generates ```newSystem.DateTime(ticks)``` - note missing space between ```new``` and ```System```.
Now, I know I can use different overload and provide my own new token with space in trailing trivia, but I think above should work too. Am I doing something wrong here?

**Comment by bkoelman** [comment]
To get whitespace inserted, I believe you need to tag your new nodes for auto-formatting.

```csharp
newSyntaxNode = newSyntaxNode.WithAdditionalAnnotations(Formatter.Annotation);
```

Then, depending on your scenario (for example, if you are writing a code fix provider), VS runs the formatter over your code. If not, you can do that yourself, like this:

```csharp
var newRoot = root.ReplaceNode(method, newMethod);
var formattedRoot = Formatter.Format(newRoot, Formatter.Annotation, document.Project.Workspace);
```

**Comment by Przemyslaw-W** [comment]
That worked, thanks :)
