### ISSUE TITLE
C#, Not functional "Cancel" button for namespace rename operation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39616]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/774651/c-not-functional-cancel-button-for-namespace-renam.html)._

---
If you start a namespace rename refactoring operation in a large-ish project, and the millisecond you hit return you realize &quot;Shit! I was to move just this class to a new namespace - not rename everything!&quot; you likely try to click the &quot;Cancel&quot; button in the progress dialog stating &quot;Please wait for an editor command to finish...&quot;, hoping the global Undo will handle the few files it might have already mod ified.

Well, you're out of luck.

Actual:
The Cancel button does nothing. Result: Data Loss.

Expected:
Immediate reaction to user clicking the Cancel button, aborting the operation.

I repeat, _Immediate_ reaction. Cancel usually, but especially in a context such as this, is a _highest priority_ operation. It should override pretty much _everything_ else.

Workarounds:
None known, but maybe trying to VS and kill all helper processes from e.g. Task Manager? Hitting the Reset button on the computer?

---
#### Visual Studio Feedback System on 10/12/2019, 01:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:21 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
+1 rename in general doesn't behave well when cancelled.

**Comment by CyrusNajmabadi** [comment]
I've looked through, and things should not be good now that we moved to async-commit.  we pass a real cancellation token here now.
