### ISSUE TITLE
C#8 Nullable check doesn't consider local function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39610]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/794236/c8-nullable-check-doesnt-consider-local-function.html)._

---
I'm doing a null check within a local function and Visual Studio/Roslyn still emit warning that objet cann be null 

Code :

```C#
bool ReponseCoherente(ReponseClient? reponse)
                => reponse != null
                && reponse.Type == ReponseServeur_InformationsPSPatient;

if (ReponseCoherente(informations))
{
    serveurClientRequest = RecupererLoginRequestDepuisReponseServeurClient(informations); // Warning here on informations
}
```

---
#### Visual Studio Feedback System on 10/27/2019, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/28/2019, 10:42 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
We don't currently do flow analysis across functions.  

@333fred  this would require annotation of local functions right? Do we have an issue tracking that?

**Comment by 333fred** [comment]
@agocke is currently working on this.

**Comment by gafter** [comment]
This requires us to be able to produce separate "when true" and "when false" states from a bool-returning local function.  It is not in the current design that we do such a thing.

**Comment by RikkiGibson** [comment]
Related to #45770

**Comment by jcouv** [comment]
We can handle this situation automatically, but it is now possible to use a nullable attribute to augment the signature of the local function. Adding `[NotNullWhen(true)]` on the parameter of the local function should do the trick.
I'll go ahead and close as by-design. Thanks

**Comment by RikkiGibson** [comment]
> We can handle this situation automatically

Not sure I understand this statement. The design is that nullable state doesn't flow out of local functions. So the solution is to use attributes as you described.

**Comment by jcouv** [comment]
Sorry was a typo. I meant "we can't handle this situation automatically"

**Comment by AraHaan** [comment]
A fix to this above code is on the parameter when calling said method is to use the ``!`` operator to explicitly mark it as not null to avoid the warning.
