### ISSUE TITLE
C#, Editor wrong vertical position in presence of folded content preceeding cursor pos

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39618]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/798512/c-editor-wrong-vertical-position-in-presence-of-fo.html)._

---
For completeness: Indent=tab, tab=4, view font default at 85% size.

Repro:
- Use the source file below, modified to instructions in it.
- Place this file in a project. Any project.
- Fold/collapse the method named so.
- Set bookmark on line marked so.
- Either manually scroll bookmarked line to vertical center of view, or use goto bookmark to have it done automatically.
- Close VS.
- Start VS with the same project.

Expected: View restored to same state as when closing VS, i.e. scrolled to same position, with caret at same line.

Actual: Caret is beyond the bottom of the view, with nary a pixel or two of its top peeking over the bottom edge of the view. Those two pixels _are_ blinking, but that's about the only good one can say about this.

As this happens with even the empty-body method collapsed, i.e. a mere two lines &quot;hidden&quot; from view, it suggests some seriously screwy logic and/or math inside the layout engine in presence of folds.

```
public class C
{
	void m1()
	{
		/*
		70-ish empty lines, just to create vertical spacing
		*/
	}

void line_80_collapse_me()
	{
	}

void line_84_display_the_bug()
	{
		// Place bookmark here (just to have a reference), and scroll this to be the middle vertical of view.
	}
}
```

---
#### Visual Studio Feedback System on 10/30/2019, 01:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
