### ISSUE TITLE
Local function reference gets "this." prefix suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39614]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/795288/local-function-reference-gets-this-prefix-suggesti.html)._

---
Local function reference gets &quot;this.&quot; prefix suggestion

---
#### Visual Studio Feedback System on 10/28/2019, 02:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/39228
