### ISSUE TITLE
Saving (ctrl+S) while renaming (F2) variable (before hitting apply) prompts windows save file dialog

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/792601/saving-ctrls-while-renaming-f2-variable-before-hit.html)._

---
I have a variable: (C#)

var myVariable = &quot;blabla&quot;;

I want to rename it, I hit F2 while my cursor is on the variable name. 
I begin typing (and the file gets a *, because its an unsaved change).
Now i DON'T press 'apply' on the rename dialog, but i save with (ctrl+S) instead.

What happens is i get a 'default' windows file 'save as' dialog to save the .cs file, wich is weird, why would it just save the file within visual studio?

---
#### Visual Studio Feedback System on 10/25/2019, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
