### ISSUE TITLE
Smart indentation failing on C# code

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#39611]
**Version Used**: VS 16.3.7

**Steps to Reproduce**:

1. Create new ASP.NET Core Web Application
2. In Startup code go to where ConfigureWebBuilder is and follow that wrapping pattern to add .ConfigureLogging()

**Expected Behavior**:
ConfigureLogging would indent at the same spot as existing.
CTRL+K,D would reformat indents even if off

**Actual Behavior**:
Neither of the above is happening
![noindent](https://user-images.githubusercontent.com/4821/67988539-893fee00-fbed-11e9-9c13-c2ca00a77459.gif)

**Comment by sharwell** [comment]
This is primarily a failure of Smart Indent, which should have indented line 25 to the same level as line 21.

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and lack of feedback.
