### ISSUE TITLE
When a variable is known to be null, its dependent fields can be treated as non-null

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#39624]
In researching https://github.com/dotnet/roslyn/issues/39264 I discovered the following issue, which is the same issue without pattern-matching.  There is some code in `NullableWalker` to support this but not a complete solution, added during the fix for https://github.com/dotnet/roslyn/issues/39264.  See a mention of this issue in the code.

```csharp
        [Fact]
        [WorkItem(39624, "https://github.com/dotnet/roslyn/issues/39624")]
        public void NullTestVsDependentSlots_01()
        {
            CSharpCompilation c = CreateNullableCompilation(@"
#nullable enable
class C
{
    string? field = string.Empty;

    void M1(C c)
    {
        if (c != null)
        {
            if (c.field == null) return;
        }
        if (c == null) return;
        c.field.ToString(); // improperly reports possible null dereference of c.field
    }
}
");
            c.VerifyDiagnostics(
                );
        }
```

**Comment by jaredpar** [comment]
Closing as this level of flow analysis is beyond what we plan on implementing for the compiler.
