### ISSUE TITLE
Roslyn JavaScript compiler

### ISSUE THREAD

**Issue by BalassaMarton** [dotnet/roslyn#3963]
Is there a Roslyn compiler for JavaScript? Or is there a plan to create one? I'm in the middle of a large ASP.NET project where the server will generate convoluted JS code on the fly, and I was wondering: it would be nice if I could build JS syntax trees, transform them with syntax tree rewriters, and then emit them as JS code. In the short term, I only need to generate code, so I don't really need a compiler, just the SyntaxNodes. I'm thinking about implementing it myself, but contributing to a project this big requires coding standards that only worth the time if there is substantial demand.

**Comment by gafter** [comment]
There are no such plans at this time.

**Comment by listepo** [comment]
+1
