### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.UnitTests.Editing.AddImportsTests.TestSafeWithMatchingSimpleNameInAllLocations started failing after ITypeSymbol.NullableAnnotation API was added.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#39641]
```ITypeSymbol.NullableAnnotation``` API was added in https://github.com/dotnet/roslyn/pull/39498 and TestSafeWithMatchingSimpleNameInAllLocations unit-test started failing in that PR. Presumably due to the fact that presence of NullableAnnotation affects the way symbols are matched by involved components.

Per request in https://github.com/dotnet/roslyn/pull/39498#discussion_r340840007, the base-line for the test is restored to the original state and the test is disabled.

**Comment by 333fred** [comment]
Closed in https://github.com/dotnet/roslyn/pull/41028.
