### ISSUE TITLE
Microsoft.CodeAnalysis.Shared.Utilities.SymbolEquivalenceComparer should be modified to properly deal with differences caused by nullability

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#39643]
```ITypeSymbol.NullableAnnotation``` API was added in https://github.com/dotnet/roslyn/pull/39498 and some unit-test started failing in that PR due to the fact that SymbolEquivalenceComparer stopped treating some symbols equivalent when the only difference comes from NullableAnnotation.
A temporary workaround was added to AreEquivalent method to get tests passing, it is not guaranteed to handle all different situations that can arise in the real world. A more robust long term solution should be implemented instead.

**Comment by CyrusNajmabadi** [comment]
Closed with https://github.com/dotnet/roslyn/pull/42825 and https://github.com/dotnet/roslyn/pull/42852
