### ISSUE TITLE
Add some UI to indicate that IntelliSense is working

### ISSUE THREAD

**Issue by ymassad** [dotnet/roslyn#39657]
NOTE: I am not sure if I am posting on the correct forum. If I am not, please let me know which forum is more suited.

I am creating a custom CompletionProvider by inheriting from Microsoft.CodeAnalysis.Completion.CompletionProvider.

Some items that I would like to display in the IntelliSense might require some time to calculate. Assume for example that sometimes, I need 2 or 3 seconds to obtain some data.

It would be very nice to have a way for the CompletionProvider to show some UI indicating that completion items are being calculated. Currently, when the user asks for completion, nothing happens, the user has to wait for 2 or 3 seconds and then the intellisense UI will appear after that.

Is  there currently anything implemented that I can use to show some "waiting" UI. If not, I would like to request such feature to be implemented.

**Comment by CyrusNajmabadi** [comment]
@ymassad This is the right forum.  But this might also be something better to bring up at gitter.im/dotnet/roslyn.

There are definitely a lot of issues with what you're proposing.  I'm happy to dive more into what the issues are if you're interested . Just ping me over in gitter and i can walk you through things whenever is a good time for you.

**Comment by CyrusNajmabadi** [comment]
@ymassad Have dumped a lot of information for you into our gitter chat.  we may be in disparate timezones, but i'll happily provide more detail there if you have more questions.

**Comment by ymassad** [comment]
Thanks @CyrusNajmabadi for your help!

**Comment by CyrusNajmabadi** [comment]
Covered everything in our offline chat.
