### ISSUE TITLE
Nullable Reference Types: return MaybeNull with this modifier

### ISSUE THREAD

**Issue by GhostTyper** [dotnet/roslyn#39651]
See this code snippet:

``` csharp
public class UniversalHolder<T> : IEnumerable<T> where T : UniversalEnumerable?
{
    private T[] values;

    /// <summary>
    /// Returns an element of the holder.
    /// </summary>
    /// <param name="name">The name of the element.</param>
    /// <returns>The element specified by the index or null if the index
    /// doesn't contain any element.</returns>
    public T this[string name]
    {
        [return: MaybeNull]
        get
        {
            foreach (T value in values)
                if (value != null && value.Name == name)
                    return value;

            return default(T);  // Analyzer: Possible null reference return.
        }
    }
```

My aim was to make it clear to the code analyzer that I wanted to maybe return `null`. However I utterly failed at this, because whatever I try, the analyzer tells me (loosely translated): "possible null reference return".

I think this shouldn't happen - or what am I doin' wrong here?

**Comment by huoyaoyuan** [comment]
As I mentioned sometime ago in this repo, currently the nullable attribute only take effects when calling other methods; not for returning method in current method.
Follow-up support of this should be already in backlog.

**Comment by jcouv** [comment]
Here's the backlog work item to have attributes take effect within method bodies as well: https://github.com/dotnet/roslyn/issues/36039

I'll close this issue as duplicate. Thanks
