### ISSUE TITLE
Configuring code style for "infer member names in anonymous types" persists the wrong setting

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#39664]
**Version Used**: 
Version 16.5.0 Preview 1.0 [29429.152.master]

**Steps to Reproduce**:

1. CTRL+. and navigate to Configure or Suppress Issues

``` C# 
        static void Main(string[] args)
        {
            var foo = new Foo();

            var bar = new { RuleName = foo.RuleName }; 

            Console.WriteLine(bar.RuleName);
        }
```

**Expected Behavior**:
```
dotnet_style_prefer_inferred_anonymous_type_member_names = true:suggestion
```

**Actual Behavior**:
```
dotnet_style_prefer_inferred_tuple_names = true:suggestion
```

![image](https://user-images.githubusercontent.com/1103906/68101486-f91de380-ff21-11e9-9b60-f684212fa796.png)

After you apply the setting from the IDE, it does not apply and the analyzer still fires.

**Comment by jinujoseph** [comment]
@davkean you wanted to set it to false or true here ? the UI shows that you are selecting true.

**Comment by mavasani** [comment]
Tagging @allisonchou

**Comment by davkean** [comment]
@jinujoseph I did want to set to it false above, but it doesn't matter which option I choose - the wrong setting is persisted/modified.

**Comment by sharwell** [comment]
Ah, now I see. I was looking for a mistake in the _value_, where it's actually a mistake in the _key_.

**Comment by mavasani** [comment]
@allisonchou mentioned she will look into this.

**Comment by mavasani** [comment]
@sharwell This seems to be an issue in the analyzer(s), not the configure code style option code fix. The generated diagnostic ID (IDE0037) is for inferred tuple names, and it associated with the correct code style option by the code fix: https://github.com/dotnet/roslyn/blob/ad175163a22afe8a642fc8cad967dfa41d2458b8/src/Features/Core/Portable/UseInferredMemberName/AbstractUseInferredMemberNameDiagnosticAnalyzer.cs#L14-L15

I believe the suggestion here is that IDE0037 should not be reported by the analyzer here?

**Comment by mavasani** [comment]
Ah, I think I see the issue now. This analyzer uses different code style options based on the location of the diagnostic (which has the same ID):

https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/CSharp/Portable/UseInferredMemberName/CSharpUseInferredMemberNameDiagnosticAnalyzer.cs#L43

https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Features/CSharp/Portable/UseInferredMemberName/CSharpUseInferredMemberNameDiagnosticAnalyzer.cs#L74

We need to modify the constructor here to pass in both options: https://github.com/dotnet/roslyn/blob/ad175163a22afe8a642fc8cad967dfa41d2458b8/src/Features/Core/Portable/UseInferredMemberName/AbstractUseInferredMemberNameDiagnosticAnalyzer.cs#L15
