### ISSUE TITLE
Symbol publishing checks are failing

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#39687]
We have been failing symbol checks when trying to insert into VS for the past day or so. There might be a problem with our symbol publishing, or there might be a problem with the check that decides if all the symbols are present.

**Comment by genlu** [comment]
Do we know what's going on? @RikkiGibson

**Comment by RikkiGibson** [comment]
At this point it seems like symbols occasionally just take a really long time to become available. I am looking into what we can do to make it better.

**Comment by JoeRobich** [comment]
See https://github.com/dotnet/arcade/issues/4288

**Comment by JohnTortugo** [comment]
> At this point it seems like symbols occasionally just take a really long time to become available. I am looking into what we can do to make it better.

Hey @RikkiGibson so the symbols eventually got available in the server? Also, are we sure this wasn't happening before this week?

**Comment by jmarolf** [comment]
The symbol publishing system says it can take up to 24 hours for them to be available. We've just been getting lucky with them showing up quickly. They eventually appear on the system, but we shouldn't block insertions for 24 hours waiting for them

**Comment by JohnTortugo** [comment]
Thanks @jmarolf . Did you got that info by e-mail? Can you please copy me there? I've been looking for confirmation about this behavior for a while now and never found much info about this.

I think there isn't much we can do from the Arcade/.net infra for this right now. Am I right?

/cc @mmitche @markwilkie

**Comment by JohnTortugo** [comment]
@RikkiGibson is this still affecting you guys or was it a transient issue?

**Comment by RikkiGibson** [comment]
We stopped seeing this issue after Nov 5th. The very long symbol publish times I think were just a transient issue. I don't think this issue is actionable on our side at this point.

**Comment by JohnTortugo** [comment]
Thanks @RikkiGibson
