### ISSUE TITLE
Refactoring several class definitions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/712365/refactoring-several-class-definitions.html)._

---
What steps will reproduce the problem?
1. In a code file, declare several interfaces or classes. For example by copy-pasting an existing defininition into several with different names.
2. Select all the new class or interface definitions and click &quot;Ctrl&quot; + &quot;.&quot; (for refactoring menu).
3. Not able to move the new classes into own files.

What is the expected output? What do you see instead?
I would like to have a refactoring command that would factor out the selected classes to files with names based on the individual class names. Having 10 classes/interfaces selected should then generate 10 new code files with the respective interfaces or classes.

Please provide any additional information below.

---
#### Visual Studio Feedback System on 8/27/2019, 01:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/26/2019, 03:56 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
The ask is multiple class move to separate files instead of doing one at a time. cc @mikadumont  in case this is being tracked elsewhere

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and high complexity cost.
