### ISSUE TITLE
C# Rename Refactoring misbehaves when multiple carets are active

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39684]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/753709/c-rename-refactoring-misbehaves-when-multiple-care.html)._

---
When multiple carets are active, rename refactoring can still be engaged, and presents an error message making no sense (f.ex. if you only see the first caret and it is on a renamable identifier).

Suggestion: Disable rename refactoring when multiple carets are active.

---
#### Visual Studio Feedback System on 9/29/2019, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/3/2019, 02:21 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Expanding on this for my interpretation of the issue: 

With multiple cursors, a user still gets "You must rename an identifier" from the check in [https://github.com/dotnet/roslyn/blob/f1f2f517e3ade7371ee1ea8ed68872128aff0c80/src/EditorFeatures/Core.Wpf/InlineRename/CommandHandlers/RenameCommandHandler_RenameHandler.cs#L87](RenameCommandHandler_RenameHandler). We could improve this error message

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this issue.
