### ISSUE TITLE
ExtractMethod does not work on parts of a switch expression

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39690]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/751819/extractmethod-does-not-work-on-parts-of-a-switch-e.html)._

---
If you have a C# 8 switch expression such as below:

int Foo(int x) =&gt; x switch
        {
            1 =&gt; 1,
            _ =&gt; 1 + x
        };

If you highlight 1 + x and choose extract method from the context menu, it should create:

int Foo(int x) =&gt; x switch
        {
            1 =&gt; 1,
            _ =&gt; NewMethod(x)
        };

private static int NewMethod(x) =&gt; x+1;

What it actually creates is:

int Foo(int x) =&gt; NewMethod(x);

private static int NewMethod(int x)
        {
            return x switch
            {
                1 =&gt; 1,
                _ =&gt; 1 + x
            };
        }

---
#### Visual Studio Feedback System on 9/28/2019, 07:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/30/2019, 00:01 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Should this issue be closed? @akhera99

**Comment by akhera99** [comment]
> Should this issue be closed? @akhera99

yep, thanks
