### ISSUE TITLE
Static local function should not be able to call non-static generic local function from parent scope

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#39706]
**Version Used**: VS2019 16.4.0 Preview3

Seems fix for #38129 not works for generic local function.

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKFygZgAJ0iBhAG2igyIG9cinmmUMA2EgFiIFk4YACwD2AEwAUASkYtmDHLMVEAlgDsYKogF4iABgDcMpcxQ8AMsIDGECgB4AKgD4pR4/Vdvmy7XsMLPRAC+HkpsaEQQPlLajioA1HF+ASQYAJziEJJJAWycpkQAyjAQMMqWFtYULv6e8sksFTa2ajDOWSGKwTVuRSVljVXt3SxdgUA===
```cs
        static void Method()
        {
            int i = 0;
            void Local<T>()
            {
                i = 0;
            }
            Action a = () => i++;
            Console.WriteLine(a);
            static void StaticLocal()
            {
                Local<int>();
            }
            StaticLocal();
        }
```

**Expected Behavior**:
It should not compile. And get an error as it did when used without generic.
`error CS8421: A static local function cannot contain a reference to 'Local'.`
See `Item 2`(#38129) in https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md

**Actual Behavior**:
It compile without error, and get an non-static method.

**Comment by cston** [comment]
@yyjdelete, thanks for reporting this issue.
