### ISSUE TITLE
The project reference to F# project looks as assembly reference 16.4.0 Preview 3.0

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#39703]
**Version Used**: 
16.4.0 Preview 3.0

**Steps to Reproduce**:

1. Create C# Library .Net Framework 4.7.2
2. Create F# Library .Net Framework 4.7.2
3. Add project reference to F# Librarty from C# Library
4. Try to use type and member from F# project in C# class.

**Expected Behavior**:
1. The Intellisense should show members from the F# project.
2. The editor with C# class should not shown members from the F# project as undeclared.
3. Find All References feature should shown references in F# project.
4. Go to Definition should navigate to F# files.

**Actual Behavior**:
1. The Intellisense not show members from the F# project.
2. The editor with C# class shown members from the F# project as undeclared.
3. Find All References feature not shown references in F# project.
4. Go to Definition navigate to metadata.

[FSVideo.zip](https://github.com/dotnet/roslyn/files/3812796/FSVideo.zip)

**Comment by jasonmalinowski** [comment]
@Droni: the C# completion system isn't linked to the "live" F# text editor, so you need to do a build before the F# members will appear in C# code. So the first issue you saw is expected.

@brettfo @TIHan For 3 and 4, that's still something we haven't hooked up?

**Comment by jasonmalinowski** [comment]
I guess the go to definition is one is https://github.com/dotnet/roslyn/pull/33723, but I wasn't sure about Find References.

**Comment by TIHan** [comment]
For 3 and 4, yes, that is something that hasn't been hooked up. I'm curious how Roslyn will hook into F# here.

1 and 2 would be more involved I imagine.

**Comment by nilekirk** [comment]
Any progress here? Not to be able to 'Go To Definition' in VS is really, really annoying.

**Comment by CyrusNajmabadi** [comment]
We're examining alternate ways of accomplishing this.  But no eta.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We provided a syustem to support gotodef with f#.
