### ISSUE TITLE
Get class/method documentation From given Type/MethodInfo

### ISSUE THREAD

**Issue by aammfe** [dotnet/roslyn#39707]
As Title Describe How To obtain Documentation for Type/MethodInfo
```
/// <summary>
    /// TestClass contains several cref examples.
    /// </summary>
    public class TestClass
    {
        /// <summary>
        /// This sample shows how to specify the <see cref="TestClass"/> constructor as a cref attribute.
        /// </summary>
        public TestClass()
        { }
    }
```

**Comment by gafter** [comment]
Can you please describe your issue using a complete sentence of complete question?  I have no idea what you're trying to say.

**Comment by aammfe** [comment]
How To get Documentation Xml node using roslyn ?
as in sample code class has documentation how I can get this `<summary> ... </summary>` node in XML ?


`var xmlNode = GetClassDocumentation<TestClass>();`

```



/// <summary>
    /// TestClass contains several cref examples.
    /// </summary>
    public class TestClass
    {
        /// <summary>
        /// This sample shows how to specify the <see cref="TestClass"/> constructor as a cref attribute.
        /// </summary>
        public TestClass()
        { }
    }
```

**Comment by CyrusNajmabadi** [comment]
From any Roslyn `ISymbol`, you can call `GetDocumentationCommentXml`.  See https://github.com/dotnet/roslyn/blob/086d773b7f4ebf47f86a78762394d0bd758a6d73/src/Compilers/Core/Portable/Symbols/ISymbol.cs#L218 for more details.

**Comment by bert2** [comment]
@CyrusNajmabadi do you know if Roslyn offers a way of getting the `ISymbol` for a `MethodInfo`?

**Comment by svick** [comment]
@bert2  Do you already have a `Compilation` that contains the members you're interested in? If not, Roslyn might not be the best way of achieving your goals.

If you do, something like the following method should work for simple cases:

```c#
public static IMethodSymbol GetSymbol(this Compilation compilation, MethodInfo methodInfo)
{
    var typeSymbol = compilation.GetTypeByMetadataName(methodInfo.DeclaringType.FullName);
    var methodSymbol = typeSymbol.GetMembers(methodInfo.Name).Single();
    return (IMethodSymbol)methodSymbol;
}
```
