### ISSUE TITLE
VS Error List window missing errors from Output window on build

### ISSUE THREAD

**Issue by airbreather** [dotnet/roslyn#39717]
**Visual Studio Version**:
Visual Studio Enterprise 2019 16.2.5

**Summary**:
I'm running into an issue where build errors that come from building a solution are reported in the Output window, but not in the Error List window.

Searching around, this looks like a symptom that never quite seems to go away, and has had multiple different causes in the past (typically, it seems, a race condition), so I've tried to get as reliable a repro as possible.  Trying out the steps from https://github.com/dotnet/project-system/issues/1411#issuecomment-277796618 seemed to do it, and I minimized it from there.

**Steps to Reproduce**:
1. File > New > Project...
1. Console App (.NET Core)
    - (name / location don't seem to matter)
1. Wait for background tasks to finish (bottom-left should say "No background tasks running." when clicked)
1. File > Close Solution
1. Restart Visual Studio
1. Using an external text editor, edit the generated `Program.cs` file to have an error.
    - I changed "`using System;`" to "`using Cystum;`" for this.
1. Read the next two steps before continuing, because speed seems to matter.
1. File > Recent Projects and Solutions > (what should be the most recent solution)
1. Run "Build > Build Solution" **as soon as** the "Build" menu becomes available

**Expected Behavior**:
The build fails, and the "Error List" window lists why.

**Actual Behavior**:
The build fails as expected, but the "Error List" window is empty.

The error does show up on the "Output" window; eventually, errors from future attempts do manage to make it into the "Error List" window.

**User Impact**:
With a much more complex solution, the window for reproducing this bug seems to be larger, to the point where I was worried I would have to live in the "Output" window for a while.

**Comment by airbreather** [comment]
@davkean thank you for checking in and pinging me.  Confirmed, these steps do not reproduce the issue in 16.3.8.

**Comment by davkean** [comment]
@airbreather Thanks for following up, and sorry for the late reply.
