### ISSUE TITLE
Put nullable attributes in netstandard2.0, or allow custom nullable attributes

### ISSUE THREAD

**Issue by jahmai** [dotnet/roslyn#39718]
It is very limiting to have the Nullable attributes only available for NetCore3 and NetStandard2.1.
I have to keep using NetStandard2.0 until we are no longer using NetFx, which could take a while.
I want to adopt nullable, but without the nullable attributes, it isn't possible to turn on WarningsAsErrors without using the #nullable to suppress warnings all over the place.
Ideally, the nullable attributes are defined in a package that is compatible with NetStandard2.0, but allowing a custom attribute with the same name is a good fallback.

**Version Used**: 

Visual Studio 16.3.1

**Steps to Reproduce**:

Create a custom attribute named "NotNullIfNotNull" or any of the other Nullable attributes defined in System.Diagnostics.CodeAnalysis. Apply it and compile.

**Expected Behavior**:

Nullable warning is suppressed by custom attribute.

**Actual Behavior**:

Nullable warning is not suppressed.

**Comment by Therzok** [comment]
@jahmai I've worked around this by creating this nuget packageby providing my own nullable attributes, make sure the namespace is correct.

As an alternative, I've also published this nuget package: https://www.nuget.org/packages/Compat.System.Diagnostics.CodeAnalysis/

**Comment by agocke** [comment]
We use our own copy of the NullableAttributes in Roslyn, which targets netstandard2.0. See https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/InternalUtilities/NullableAttributes.cs

This seems to work fine.

**Comment by jahmai** [comment]
Thanks both! I believe I have found a bug then, raised it as #39728
