### ISSUE TITLE
MSBuildWorkspace incorrectly evaluates project when iterating over TargetFrameworks

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/roslyn#39724]
When a project which uses multi-targeting is loaded into `MSBuildWorkspace`, the code iterates over the values in `TargetFrameworks`, and evaluates the project after setting `TargetFramework` for each value.

This is done here:

https://github.com/dotnet/roslyn/blob/4f38fdac37fabe1414f089de9759f7e1a7d90c03/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L65

This code uses `SetProperty`, which simulates a `TargetFramework` property being set from *inside* the XML of the project.

I believe this to be incorrect, and I think that `SetGlobalProperty` should be used here instead. This is what happens during a real build.

Since the `TargetFramework` property is currently not global, it is set *too late* during evaluation and there are observable side effects, most notably in NuGet imports.

**Version Used**: 3.3.1

**Steps to Reproduce**:

Here's what currently happens for a project with `TargetFrameworks` set to `net48;netcoreapp3.0`, and which includes an `ExamplePackage` NuGet that has `props` and `targets` imports:

On restore, NuGet will generate the following code in the `*.nuget.g.props` file (similar code is also generated in the `*.nuget.g.targets` file):

```XML
<ImportGroup Condition=" '$(TargetFramework)' == 'net48' AND '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="$(NuGetPackageRoot)examplepackage\1.0.0\build\ExamplePackage.props" Condition="Exists('$(NuGetPackageRoot)examplepackage\1.0.0\build\ExamplePackage.props')" />
</ImportGroup>
```

However, this file is included **before** the `TargetFramework` property is set, and therefore the `ExamplePackage.props` import is skipped. On the other hand, the `ExamplePackage.targets` import is included, since the `TargetFramework` property is set by then.

Setting the `TargetFramework` as global would fix this issue and cause the `ExamplePackage.props` file to be imported correctly.

**Expected Behavior**: `ExamplePackage.props` and `ExamplePackage.targets` should be included in the evaluation.

**Actual Behavior**: Only `ExamplePackage.targets` is included in the evaluation.

**Comment by dotMorten** [comment]
@shaggygi Could the reason for this be why I'm seeing a crash in DocFX? https://github.com/dotnet/docfx/issues/5508

It fails to remove the TargetFramework property around this code specifically, which appears to have changed since.

**Comment by shaggygi** [comment]
@dotMorten was this intended for @sharwell ?

**Comment by dotMorten** [comment]
@shaggygi Oops. Damn auto complete. Yes :)

**Comment by dotMorten** [comment]
Actually I can confirm using `v3.5.0-beta2-final` resolves the issue :)
