### ISSUE TITLE
Convert foreach to LINQ can leave unnecessary parentheses

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#39727]
**Version Used**: 16.4

Filing as a result of this conversation: https://github.com/dotnet/roslyn/pull/39695#discussion_r343802349

This example can be seen in this unit test: https://github.com/dotnet/roslyn/blob/8a090dae33f4305b2c1756b63dcaf4a058d76362/src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs#L3827

**Steps to Reproduce**:

1. Paste C# code

```C#
using System.Collections.Generic;
using System.Linq;

class C
{
    void M(IEnumerable<int> nums)
    {
        int c = 0;
        $$foreach (int n1 in nums.AsQueryable())
        {
            c++;
        }
    }
}
```

2. Remove the $$ and invoke the lightbulb item "Convert to LINQ (call form)"

**Expected Behavior**:
```C#
int c = nums.AsQueryable().Count();
```

**Actual Behavior**:
```C#
int c = (nums.AsQueryable()).Count();
```

**Comment by ronnygunawan** [comment]
Parentheses still needed for this though:
```cs
int c = 0;
foreach (int n1 in from n1 in nums select n1) {
    c++;
}

// Converted into LINQ:
int c = (from int n1 in
             from int n1 in nums select n1
         select n1).Count();
```
