### ISSUE TITLE
Strange behaviour of pattern matching

### ISSUE THREAD

**Issue by vabka** [dotnet/roslyn#39721]
**Version Used**: 3.1.100-preview1-014459 (but reproduced in earlier versions)

**Steps to Reproduce**:
```cs
using System;
static class Demo 
{
    static void NotOkCase(object obj)
    {
        if((obj is string s) == false) 
        {
             Console.WriteLine("obj is not a string");                
        }
        else
        {
            //uh-oh use of unassigned variable
            //Console.WriteLine(s);
        }
    }
    
    static void OkCase(object obj)
    {
        if(!(obj is string s)) 
        {
            Console.WriteLine("obj is not a string");
        }
        else 
        {
            Console.WriteLine(s);
        }
    }
}
```

**Expected Behavior**:
I can use 's' in NotOkCase.

**Actual Behavior**:
I can't.

**Comment by CyrusNajmabadi** [comment]
This is how the language works.  There is no understanding about how `== bool-val` works wrt to definite-assignment.  

If you want this to work, you'll have to file a language request over at csharplang.

**Comment by gafter** [comment]
You need to use `!` to negate the expression, which is specified to preserve definite assignment states.  `== false` does not do the same.
