### ISSUE TITLE
Ruleset include path needs to be updated

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#3972]
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/CodeAnalysisRules.ruleset#L4
This path is no longer valid:
..\..\Tools\Microsoft.CodeAnalysis.Toolset.Open\Rulesets\Roslyn.ruleset
The Roslyn.ruleset is now under 
https://github.com/dotnet/roslyn/blob/master/build/Rulesets/Roslyn.ruleset

@agocke

**Comment by KirillOsenkov** [comment]
Also shouldn't there be some validity check that would fail when an include path can't be resolved?

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/roslyn/commit/4598030019f844d4b2099f3b934848042cefc637
