### ISSUE TITLE
Workspace-level Nuget packages need to specify exact dependency on Microsoft.Composition

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#3973]
Currently the workspace-level NuGet packages specify the dependency like this:
Microsoft.Composition (≥ 1.0.27) 
However it should be exact version, since Roslyn binaries are compiled to reference exactly 1.0.27 and there will be a runtime failure to load 1.0.27 assembly if you happen to install 1.0.30 for instance.

@agocke

**Comment by amcasey** [comment]
Seems like @jmarolf is a good candidate for this one. :)
