### ISSUE TITLE
Call to multisignature method from C# library causing ambiguity

### ISSUE THREAD

**Issue by Hydroper** [dotnet/roslyn#39751]
**Version Used**: `dotnet --version`: 2.2.402

**Steps to Reproduce**:

1. Run the commands `mkdir vbveldrid && cd vbveldrid && dotnet new console -lang vb`.
2. Then `dotnet add package Veldrid --version 4.7.0 && dotnet add package Veldrid.StartupUtilities --version 4.7.0 && dotnet add package Veldrid.SDL2 --version 4.7.0`
3. Write the following to `Program.vb`:

```vb
Imports Veldrid
Imports Veldrid.SDL2
Imports Veldrid.StartupUtilities

Module Program
    Dim _graphicsDevice As GraphicsDevice
    Sub Main(args As String())
        Dim windowCI As New WindowCreateInfo()
        With windowCI
            .X = 100
            .Y = 100
            .WindowWidth = 960
            .WindowHeight = 540
            .WindowTitle = "Veldrid Tutorial"
        End With

        Dim window = VeldridStartup.CreateWindow(windowCI)
        Dim _graphicsDevice = VeldridStartup.CreateGraphicsDevice(window)
        While window.Exists
            window.PumpEvents()
        End While
    End Sub
End Module
```

4. `$ dotnet run`

**Expected Behavior**:

Expected program to compile.

**Actual Behavior**:

Compiler reports the error:

```
Program.vb(17,37): error BC31429: 'CreateWindow' is ambiguous because multiple kinds of members with this name exist in class 'VeldridStartup'.
```

**Comment by gafter** [comment]
The compiler appears to be correctly reporting an ambiguity.  We have

```vb
Namespace Veldrid.StartupUtilities
    Public NotInheritable Class VeldridStartup
        Public Shared Function CreateWindow(windowCI As WindowCreateInfo) As Sdl2Window
        Public Shared Function CreateWindow(ByRef windowCI As WindowCreateInfo) As Sdl2Window
    End Class
End Namespace
```

There is no way (in VB) for the compiler to decide between these two methods.  I suggest you file a bug against the `VeldridStartup` API, as its design makes it unusable from VB.
