### ISSUE TITLE
Rewrite Find Symbol Results tool window for better result presentation UX

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#3977]
The current Find Symbol Results window is written in native code and uses window messages and other obsolete constructs. It's also severely limiting to how we can present results to the user.

If we rewrite this window in WPF, we could gain these benefits:
1. Asynchonous population
2. Hierarchical presentation (group by symbol and its references)
3. Visual separation of derived types, interface implementations, variable reads/writes, etc.
4. Multiple result sets (via tabs or multi-instance tool window or "result history list")

**Comment by dpoeschl** [comment]
@KirillOsenkov Can you add any non-dupes to the existing list at https://github.com/dotnet/roslyn/issues/903? We've also talked to the Editor team about things we can improve here, and ways of getting out of the old UX without rewriting.

**Comment by KirillOsenkov** [comment]
"ways of getting out of the old UX without rewriting" LOL how is that? :)

**Comment by KirillOsenkov** [comment]
I've updated the list, we should close this bug as a dupe of #903. How do I do that?
