### ISSUE TITLE
cs files in project root whose names start with @ cause compile time error CS2011

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#39780]
**Version Used**: 
VS 2019 16.4 Preview 3

**Steps to Reproduce**:

1. Place a cs file that starts with `@` in the project root. For example: `@empty.cs`
2. Try compiling the project

**Expected Behavior**:
As long as none of the cs files contain erroneous code, project compiles. Naming a file such that it begins with `@` should have no effect.

**Actual Behavior**:
Compilation fails with: `CS2011: Error opening response file <path to @empty.cs>`

Changing file name from `@empty.cs` to `!empty.cs` for example makes everything compile.

**Comment by jaredpar** [comment]
This behavior is by design. The `@` symbol is used to indicate response files and hence these are processed as rsp files, not C# files.
