### ISSUE TITLE
IDocumentTrackingService is null in the OOP process

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#39781]
Both @CyrusNajmabadi and I found this while attempting to refactor code that runs in OOP. See https://github.com/dotnet/roslyn/pull/39699#discussion_r343383146

**Comment by CyrusNajmabadi** [comment]
Closing out as this is by design.  OOP will have no concept of these as it is intended to be stateless.  The caller needs to pass this info in if relevant.
