### ISSUE TITLE
Remove consecutive blank lines between class members

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39794]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/809464/req-merge-multiple-blank-lines-between-class-membe.html)._

---
Please add the ability to merge multiple blank lines between class members to a predefined number, eg. 1. Or the ability to set the maximum number of blank lines between members and for code cleanup to be able to remove those extra blank lines.

---
#### Visual Studio Feedback System on 11/7/2019, 00:15 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment]
Note: This is already implemented as a Roslyn-specific analyzer (RS0101). You may want to port this rule as an IDExxxx rule.

**Comment by CyrusNajmabadi** [comment]
Enable IDE2000 for this:

![image](https://user-images.githubusercontent.com/4564579/199312220-30f3cca2-70fe-4e27-bc92-4adb13d70cec.png)
