### ISSUE TITLE
Disable Hyperlinks in code tooltips (VS 2019 C# code editor)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39793]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/813017/disable-hyperlinks-in-code-tooltips-vs-2019-c-code.html)._

---
<p>Since upgrading to Visual Studio 2019, the code tooltips that appear when your mouse hovers over symbols in your code now include clickable hyperlinks that navigate to other code files. These tooltips are incredibly dangerous and time-costing because accidental clicks happen very frequently and the sudden, unexpected transition is very intrusive.</p> <p>Please can we have an option to disable these hyperlinks. (Specifically: in C# code files, but best in all languages.)</p> <p>Even better would be an option to make the tooltips ignore all clicks and not be hit-tested at all unless a key was held -- perhaps Ctrl. In older versions of visual studio, these tooltips existed and clicking them accidentally blocked the click event and was thus somewhat annoying, already.</p> <p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/103682-untitled.png"> Image:103682-untitled.png</a></p><p>^^^ I don't need to click that! ^^^</p><p>The inclusion of links in these tooltips is extremely disturbing to my workflow -- they pop up at exactly the instant I am trying to use the mouse to position the caret and now include time-costing hyperlinks! In fact, it slows me down enough to keep me from upgrading to visual studio 2019!</p>

---
#### Visual Studio Feedback System on 11/8/2019, 02:06 AM: 

4. Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
@olegtk should this be an editor feature to apply across the full IDE?

**Comment by olegtk** [comment]
Yes, this should be platform feature, route it to the editor. Thanks!

**Comment by sharwell** [comment]
This was moved back to developer community by reopening the original issue.
https://developercommunity.visualstudio.com/content/idea/813017/disable-hyperlinks-in-code-tooltips-vs-2019-c-code.html
