### ISSUE TITLE
local introduce variable is very inconsistent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39806]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/706053/introduce-local-variable-is-very-inconsistant.html)._

---
What steps will reproduce the problem?
1. call any chained non void method
2. press alt+enter on that method and it is supposed to show an option to create a local variable for that method.
3. But it doesn't show all the time

What is the expected output? What do you see instead?
Every non-void method call / new instance initialization should show the option to autocreate a variable to be assigned to.

Please provide any additional information below.

---
#### Visual Studio Feedback System on 8/22/2019, 08:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 9/5/2019, 11:57 AM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Please provide more details that could help us understand/repro this issue. If possible please provide snapshots describing what you believe should be showing but is not showing.</p>

#### Visual Studio Feedback System on 9/17/2019, 07:38 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### anmotupa [MSFT] on 9/18/2019, 11:42 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 11/12/2019, 09:01 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Example code showcasing issue:

```c#
var a = items
        .Select(i => i.Name)
        .Distinct()
        .ToArray()
```

Selecting any of the LINQ above, such as `Select` or `Distinct`, does not currently present the option to introduce a local value capturing the output of that call. 

### Proposed Solution

Allow "introduce local variable" to capture chained calls up to the selected method.

### Examples

User selects `Select` above and generates a new local. The code would then be: 

```c# 
var local = items.Select(i => i.Name);
var a = local
        .Distinct()
        .ToArray()
```

User selects `Distinct` above. 

```c#
var local = items.Select(i => i.Name).Distinct();
var a = local.ToArray();
```

### Similar Patterns

In the case of logical operators we allow locals to be introduced. The behavior is very similar: 

```c#
bool NullOrEmpty(string s)
{
    return s == null ||
           [|s == string.Empty|];
}
```

Selecting around the `[|` and `|]` above and introducing a local is allowed, and will generate the following:

```c#
bool NullOrEmpty(string s)
{
    var local = s == string.Empty;
    return s == null ||
        local;
}
```

### Constraints 

We should not allow generation of a local for ALL occurences of the selected chain method. That is allowed for other local generation, but I believe does not make sense in this case.

**Comment by CyrusNajmabadi** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/4564579/68814135-ddef5a00-062c-11ea-90e6-fcdd238bc3c6.png)

**Comment by ryzngard** [comment]
@CyrusNajmabadi what version did you try this on? Where did you put your cursor? I swear I tried this and verified and couldn't get it working.

**Comment by CyrusNajmabadi** [comment]
I'm on 16.4p4.  I selected `items.Select(i => i.Name)` and `items.Select(i => i.Name).Distinct()` (over multiple lines)

**Comment by ryzngard** [comment]
Based on design review, the current implementation should be expanded. I'm writing up a proposal now that includes current and changed behavior.

**Comment by CyrusNajmabadi** [comment]
@ryzngard do we still need to do anything with this?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response
