### ISSUE TITLE
NotNullIfNotNull is not working with implicit operator

### ISSUE THREAD

**Issue by sakno** [dotnet/roslyn#39802]
Probably Roslyn compiler ignores `NotNullIfNotNullAttribute` when it is applied to `implicit operator`.
Let's assume that we have a class
```csharp
public sealed class Foo
{
  private readonly int value;
  
  internal Foo(int value) => this.value = value;

  [return: NotNullIfNotNull("foo")]
  public static implicit operator string?(Foo? foo) => foo is null ? null : foo.value.ToString();
 }
```
Now we can convert it into `string` implicitly as follows:
```csharp
string str = new Foo(10);
```
In this case the compiler emits CS8600 warning: `Converting null literal or possible null value to non-nullable type`. However, it is obviously that `new` operator is null-safe.

**Comment by SirIntellegence** [comment]
This happens with explicit casts as well.

**Comment by SirIntellegence** [comment]
I have a project to test both cases if you want it.

**Comment by eerhardt** [comment]
@jcouv @cston - I think this is going to be a pretty big issue in .NET 5 now that `XElement` is fully annotated. The most common way to make an XElement is to pass in a string to the ctor. But XElement's ctor takes an XName, which has an implicit op from string. Now any dev who has nullable enabled will get a warning when creating an `XElement` this way:

![image](https://user-images.githubusercontent.com/8291187/91593228-65d8f300-e925-11ea-85c6-18e60a471be7.png)

Any chance we can look into fixing this?

**Comment by jcouv** [comment]
Moving issue up to 16.8.
