### ISSUE TITLE
Mistyping after a region causes region to expand....

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39808]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/589219/mistyping-after-a-region-causes-region-to-expand.html)._

---
If your code contains a #Region/#EndRegion block, and you type a command after that #End Region statement slowly, the previous region will suddenly expand without request. This seems to happen if the compile sees an opportunity to compile the code while you are typing. This also happens if you type something random after a #end Region statement a wait a few seconds.

---
#### Visual Studio Feedback System on 5/30/2019, 07:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 6/7/2019, 04:18 PM: 

<p>Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Please provide more details that could help us understand/repro this issue. If possible please provide snapshots/sample project that would be very helpful.</p>

#### sam.marrocco on 6/17/2019, 10:40 AM: 

<p>Here is a detailed step-by-step way to duplicate the issue:</p><p>-Open Visual Studio 2019 and create a new VB.net Windows Forms project.</p><p>-Navigate into the Form1 class code.</p><p>-Enter the following code:</p><p>#Region "One"<br> Public Sub One()<br> End Sub<br>#End Region<br>#Region "Two"<br> Public Sub Two()<br> End Sub<br>#End Region</p><p>-Now COLLAPSE both regions "One" and "Two"</p><p>-Click your cursor in the area AFTER the LAST #End Region of this  code. Now type the letter 'd' (or any character) and wait a few seconds.  The previous Region (Region "Two") will expand on its own. The "+"  collapse/expand indicator in front of that #Region "Two" will also  disappear until the 'd' character is deleted and you hover the mouse  cursor over the missing "+" symbol.</p>

#### sam.marrocco on 7/11/2019, 01:05 PM: 

<p>I have added more details to duplicate the issue. Please re-assess and update status.</p>

#### Visual Studio Feedback System on 11/12/2019, 05:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change these experiences.
