### ISSUE TITLE
Intellisence suggests name already contained in type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39811]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/808046/intellisence-suggests-name-already-contained-in-ty.html)._

---
Once one types type name within class definition, Intellisense recommends fileds, properties, whatever. Its &quot;suggested name&quot; is invalid though in case class contains that type.

```
class A
{
    public enum FileType { C, D }
    public FileType
}
```

Now Intellisense will recommend to create property &quot;FileType&quot; while &quot;The type 'A' already contains a definition for 'FileType'&quot;.

---
#### Visual Studio Feedback System on 11/6/2019, 00:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Dreamescaper** [comment]
What is the expected behavior here?

IMHO, current behavior is better than not showing that option (because I might want to use that suggestion, and then add some suffix) or adding some auto-generated suffix (because most likely I'll have to change it anyway).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
