### ISSUE TITLE
Stashes aren't removed when clicking Drop All

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#39815]
**Version Used**: 16.3.9

**Steps to Reproduce**:

1. Click Drop All

**Expected Behavior**: All stashes are removed

**Actual Behavior**: Always show `calculating`, but if I close and reopen VS, these are removed.

By then way, when I opening VS, VS show `calculating` forever even if there's nothing.
![image](https://user-images.githubusercontent.com/2529999/68848129-bd95cd00-070a-11ea-9119-352567609527.png)

**Comment by sharwell** [comment]
@CreateAndInject Can you report this using the Report a Problem tool in Visual Studio? This will allow the issue to be routed to the appropriate team. 👍

**Comment by CyrusNajmabadi** [comment]
This is not roslyn.
