### ISSUE TITLE
interpolated strings for ILogger

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39825]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/818361/interpolated-strings-for-ilogger.html)._

---
<p>The ILogger methods allow to use format strings and parameters. The current methods are error prone because the format strings do not behave like string. Format(). The order of the parameters is important. This is causing confusion and errors in our code.</p> <p>logger. LogWarning(&quot;Hello {1},{0}&quot;, 0, 1) produces &quot;Hello 0,1&quot; while &quot;Hello 1,0&quot; is expected.</p> <p>The best way to solve the confusion is to create overloads for interpolated strings as use in . FromSqlInterpolated. The implementation could do late string building as with the current format strings.</p> <p>So allow logger. LogWarning($&quot;Hello {one}, {zero}&quot;) where one and zero are variables.</p>

---
#### Visual Studio Feedback System on 11/13/2019, 11:21 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by gafter** [comment]
Moved to https://github.com/aspnet/Extensions/issues/2680
