### ISSUE TITLE
Add build warning if component does not have Parameter defined

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39821]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/714309/add-build-warning-if-component-does-not-have-param.html)._

---
I am refactoring a few of my components, changing Parameter names, etc.  When the Parameter name on a component does not exist, it would be nice to get a compile warning or error

---
#### Jane Wu [MSFT] on 8/28/2019, 01:04 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by gafter** [comment]
I don't understand the issue.  What do you mean by "component".  Can you please give an example of the code that you would expect an error for?

**Comment by sharwell** [comment]
Based on the screenshot submitted with the original feedback, this may be related to Razor. It's difficult to tell from the limited description though.
