### ISSUE TITLE
Trailling commas in object/list initializers and enums in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39828]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/819413/trailling-commas-in-objectlist-initializers-and-en.html)._

---
It would be nice if IDE could be set up to remind to add trailing commas to object and list initializers and enums (and wherever else possible), so that subsequent changes that would add items to the existing lists wouldn't have to touch the existing lines making diffs cleaner.

I.e. for a code like:
```C#
enum Something
{
    One,
    Two
}
```
it would be nice to have an optional suggestion to add a comma after `Two`. So that when a `Three` is added to a list, the diff would highlight only one line (since the line with `Two` would not be touched).

---
#### Visual Studio Feedback System on 11/13/2019, 11:22 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by heaths** [comment]
Is this a dup of #25206 or does IDE support require explicit implementation besides .editorconfig support?

**Comment by jmarolf** [comment]
it should not. I think this is a dupe
