### ISSUE TITLE
Custom sorting for "usings" (C#) and "Imports" (VB.NET)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39824]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/815148/custom-sorting-for-usings-c-and-imports-vbnet.html)._

---
I know it sounds totally finicking, but I would love if the &quot;sort usings (resp. Imports) and remove unused namespace&quot; command could be complemented with a custom sort logic as I have a more sophisticated algorithm than &quot;alphabetical with System first&quot;:

In our project we sort &quot;`System.*`&quot; first, &quot;`Microsoft.*`&quot; second, all NuGet-imports third, our own namespace last, within each section alphabetical. In another one we do it similair but within each section according to the length of the imports.

So my request is for a custom sorting option in C# and VB.NET (maybe other languages as well) where one can browse the file system for an assembly that contains a class that implements IComparer&lt;String&gt; with the sort logic. Either one has to specify the fully qualified class name of the comparer after selecting the assembly, or the UI fills a list with all the IComparer&lt;String&gt; - implementations it found in the assembly and lets us select it. From then on usings/Imports are sorted according to the custom sort logic.

As an additional request I would like to be able to specify the (absolute or relative) path to the assembly and the fully qualified class name of the comparer also in the &quot;.editorconfig&quot; file to enforce all people working on the project to use the same sort algorithm.

---
#### Visual Studio Feedback System on 11/11/2019, 11:24 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback and high complexity to solve a niche area.
