### ISSUE TITLE
'variable assigned is never used' indication is incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39832]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/656306/variable-assigned-is-never-used-indication-is-inco.html)._

---
See below example code. The code is arguable silly, but it does compile and run, and was foudn in the 'wild'. Visual studio highlights the line:

int timeoutMins = 20;

... as having a redundant assignment, but the value of 20 **is** passed in, and is also returned by the output parameter of Foo().

I expect VS has spotted that the assignment to timeoutMins  is followed by it being passed as an output argument, but it's also being passed an an input argument!

```
        static void Main(string[] args)
        {
            Console.WriteLine(&quot;Hello World!&quot;);

int timeoutMins = 20;
            Foo(out timeoutMins, timeoutMins);

Console.WriteLine($&quot;Foo() result: timeoutMins = {timeoutMins}&quot;);
        }

static void Foo(out int timeoutMins, int timeoutMinsDefault)
        {
            timeoutMins  = timeoutMinsDefault;
            Console.WriteLine($&quot;Foo() internal state: timeoutMins = {timeoutMins}&quot;);
        }
```

---
#### Visual Studio Feedback System on 7/23/2019, 02:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/23/2019, 11:15 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Gustav Frisholm on 8/29/2019, 07:20 AM: 

I have the same issue. VS reports string is not used when it is in fact set in the constructor:<br>
#### Gustav Frisholm on 8/29/2019, 07:20 AM: 

        private string _identityUrl;<br><br>        public OutOfNetworkMargincallController(RelayContext context, IOptions optionsAccessor)<br>        {<br>            this.context = context;<br>            _options = optionsAccessor.Value;<br>            ampApi = new AmpApi(_options.EnvironmentUrl);<br>            _identityUrl = _options.EnvironmentUrl + "/identity/oauth2/token";<br>        }
#### Dean Jackson on 10/17/2019, 09:03 AM: 

<p>Confirmed using VS 16.3.3.  I pasted the code provided in the original post at the top, into my program.cs file of a new console project, and yes, the light-bulb tells you that this line: </p><p>int timeoutMins = 20;</p><p>is an "Unnecessary assignment", which is not correct.</p>

---
### Original Solutions
(no solutions)

**Comment by colgreen** [comment]
Here's an edited my original report on developercommunity:

See example code below. Arguably the code is silly, but it does compile and run, and this pattern was found in an existing code repository. Visual studio highlights this line:

    int timeoutMins = 20;

...reporting it as a redundant assignment, but the value of 20 is actually used; it's passed to Foo() as an input parameter, it just happens to also be set/returned by an output parameter.

I expect VS has spotted that the assignment to timeoutMins is followed by it being passed as an output parameter, but it's also being passed an an input parameter!

    static void Main(string[] args)
    {
        Console.WriteLine(&quot;Hello World!&quot;);

        int timeoutMins = 20;
        Foo(out timeoutMins, timeoutMins);

        Console.WriteLine($&quot;Foo() result: timeoutMins = {timeoutMins}&quot;);
    }

    static void Foo(out int timeoutMins, int timeoutMinsDefault)
    {
        timeoutMins  = timeoutMinsDefault;
        Console.WriteLine($&quot;Foo() internal state: timeoutMins = {timeoutMins}&quot;);
    }

I.e. it's a slightly bonkers pattern but it is legal C# code, and Visual Studio's suggestion breaks it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
