### ISSUE TITLE
Find References does not display all references for getter if those references are conditional

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39847]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/729179/find-references-does-not-display-all-references-fo.html)._

---
When a class contains **indexer** which contains both **getter** and **setter** and getter is accessed via **conditional** **access** , such a reference is not displayed .
But thanks very much for finaly distinguishing setters and getters in your references search !

---
#### Visual Studio Feedback System on 9/11/2019, 03:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/17/2019, 10:03 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@mavasani It seems like the Find All Reference feature is ignoring `?[` syntax.
