### ISSUE TITLE
Find all references to a class shows all references to Finalize method of all classes instead of references to the class I searched on

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/717321/find-all-references-to-a-class-shows-all-reference.html)._

---
What steps will reproduce the problem?
1.  Open a solution with several classes and VB.NET projects
2.  Navigate to the definition of a class, e.g., Public Class Foo
3.  Right click on the class name Foo and Find All References

What is the expected output? What do you see instead?
I expect to see references to class Foo - variable declarations for sure.  Maybe method calls on instance variables, etc.

I see every reference to &quot;Overridable Overloads Sub Object.Finalize()&quot; and every class that is derived from Object in the scope (project or solution) even though they are not of class Foo (or derived from Foo).  That swamps the actual data that I am looking for and gives me is signal to noise ratio of 1:100 or 1:1000.

Please provide any additional information below.

---
#### Visual Studio Feedback System on 8/30/2019, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:25 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### R Pond on 11/11/2019, 06:22 AM: 

We have the same problem.  It happens both when rightclicking the class name and doing &#39;find all references&#39; from there, and also when clicking the &#39;27 references&#39; link above the class name.

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is a Visual Basic specific bug, and can be observed in code like the following

```
Class TestClass2
    Protected Overrides Sub Finalize()

    End Sub
End Class

Class TestClass
    Protected Overrides Sub Finalize()

    End Sub
End Class
```

It does not occur for similar code in C#:

```
private class TestClass2
{
    ~TestClass2() { }
}

private class TestClass
{
    ~TestClass() { }
}
```

**Comment by CyrusNajmabadi** [comment]
This was fixed due to how we cascade in FAR now.
