### ISSUE TITLE
Intellisense bug: when contents of string interpolation contains newline, the final double quote is incorrectly moved

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39846]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/814365/intellisense-bug-when-contents-of-string-interpola.html)._

---
Example:

_logger?. LogError($&quot;{guid} failure: {await httpResponseMessage
		. Content
		. ReadAsStringAsync()
		. ConfigureAwait(false)}&quot;);

... becomes...

_logger?. LogError($&quot;{guid} failure: {await httpResponseMessage
		. Content
		. ReadAsStringAsync()
		. ConfigureAwait(false)}
	&quot;);

... on save.  This doesn't compile.

---
#### Visual Studio Feedback System on 11/10/2019, 10:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidnmbond** [comment]
It's also worth noting that string interpolation does not currently support newline characters, though I can see no logical reason why not.

**Comment by CyrusNajmabadi** [comment]
@davidnmbond What do you mean by that?  You can both embed newline characters with an escape like so:

```c#
                    var v = $"foo\nbar";
```

Or you can directly embed a newline like so:

```c#
                    var v = $@"foo
bar";
```

This matches how normal strings work.

**Comment by davidnmbond** [comment]
I mean:
    var text =$"They list of people includes: {(string.Join(", ", people.Where(p=>p.IsHappy)
        .OrderBy(p=>p.Surname)
        .ThenBy(p=>p.Forename)
        .Select(p => $"{p.Forename} {p.Surname}"))}.  They are all happy.";

**Comment by CyrusNajmabadi** [comment]
> There is no real need for this constraint.

Yes there is.  You have a normal interpolated string.  So the lexer isn't going to consume newlines in the middle since that's not allowed there.  If you want this, you can write it as:

```c#
                var text = $@"They list of people includes: {
                    (string.Join(", ", people.Where(p => p.Length > 21)
                    .OrderBy(p => p.Surname)
                    .ThenBy(p => p.Forename)
                    .Select(p => $"{p.Forename} {p.Surname}")))}.  They are all happy.";
```

`@` strings can span multiple lines in C#, non-@ strings cannot.  That's regardless of whether they're interpolations or not.

**Comment by CyrusNajmabadi** [comment]
This part doesn't make sense:

> ... on save. This doesn't compile.

We don't manipulate code on save.  So this must be some other tool.  Need more info on a repro that causes this.
