### ISSUE TITLE
Refactoring: Convert static class to singleton

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#39851]
```cs
static class C
{
   public static string Value => "value";
}

// usages
var v = C.Value;
```
```cs
class C
{
   public static C Instance { get; } = new C(); // rename annotation on Instance
   public string Value => "value";
}

// usages
var v = C.Instance.Value;
```
 shouldn't offer a fix when an extension method is present.

**Comment by YairHalberstadt** [comment]
> ```csharp
> class C
> {
>    public static C Instance { get; } = new C(); // rename annotation on Instance
>    public string Value => "value";
> }
> ```

This isn't a Singleton. Should it also generate a private constructor?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
