### ISSUE TITLE
IDE0019 should match is/cast

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#39860]
**Version Used**: Version 16.5.0 Preview 1.0 [29513.106.master]

**Steps to Reproduce**:

```c#
string M(object o)
{
    if (o is string)
    {
        return (string)o;
    }

    return "";
}
```

**Expected Behavior**:

Should produce IDE0019 (or some other diagnostic) with code fix that results in:

```c#
string M(object o)
{
    if (o is string s)
    {
        return s;
    }

    return "";
}
```

**Actual Behavior**:

No diagnostic.

**Comment by drewnoakes** [comment]
Other examples of where this could be applied are in: https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/213737?_a=files

**Comment by CyrusNajmabadi** [comment]
This is supported:

![image](https://user-images.githubusercontent.com/4564579/219780740-391354dc-7940-483e-9fae-cc4e487fa85f.png)

![image](https://user-images.githubusercontent.com/4564579/219780826-852eb046-8f92-4573-b415-d7c0ecd14587.png)
