### ISSUE TITLE
How to show CS8321 warning?

### ISSUE THREAD

**Issue by kharada7** [dotnet/roslyn#39862]
**Version Used**: 

- Micrsosoft.CodeAnalysis.FxCopAnalyzers 2.9.7
- Microsoft.CodeAnalysis.CSharp 3.3.1
- .NET Framework 4.8
- Visual Studio Enterprise 2019 16.3.9

**Steps to Reproduce**:

1. Add codes like this: 

```C#
public class Example
{
    public void Hoge(string msg)
    {
        Console.WriteLine(msg);
    }

    private void Fuga(int number)
    {
        Console.WriteLine(number);
    }
}
```

2. Open the ruleset file and check CS8321

3. Build the project

**Expected Behavior**:

VS2019 shows warning CS8321.

**Actual Behavior**:

CS8321 was not shown.

Maybe method is not function. But what is "local function" of C#?

**Comment by Joe4evr** [comment]
A local function is a method defined *inside* another method.

**Comment by gafter** [comment]
CS8321 tells you when a local function is not used.  Your program has no local function, therefore it has no unused local function to report using CS8321.

**Comment by CompCodeNet** [comment]
Please point us to a list of all the CSXXXX messages if you would. Thank You.
