### ISSUE TITLE
Decompiled source includes an empty comment above each method

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#39877]
**Version Used**: VS master 29513.77

**Steps to Reproduce**:

1. Open ProjectSystem.sln from https://github.com/dotnet/project-system
2. Navigate ManagedProjectSystemPackage.cs
3. Go To Defition on the `PackageRegistration` attribute (or open any project and Go To Definition on anything from a reference that doesn't have XML comments)

**Expected Behavior**:

Decompilation is shown without comments above members

**Actual Behavior**:

An empty single line comment is displayed, initially collapsed, above members.

This is annoying because it means I have to expand each collapsed section to see if there is any comments for me to read.

**Comment by siegfriedpammer** [comment]
Sorry for taking so long to get to this! (It seems I did not get notified by github for this issue...)

@davidwengier if there are no XMLDoc comments on the member no comment is added by ILSpy. Comparing the output of ILSpy and Visual Studio 16.4.3 sheds some light on the actual issue:

![ilspy_output](https://user-images.githubusercontent.com/344204/72568466-7b2e6f00-38b8-11ea-8b3b-1f75a3d366c8.png)

![vs16 4 3_output](https://user-images.githubusercontent.com/344204/72568485-8a152180-38b8-11ea-951c-769f4eb58182.PNG)

In the screenshots we can see two problems regarding XMLDoc currently present in the decompiler integration:
1) "MetadataAsSource-transformed" XML comments contain superfluous `///` markers for every line-break in the original comment. This is tracked on our end by https://github.com/icsharpcode/ILSpy/issues/1908, which will land in VS once ILSpy 6.0 is considered mature enough.
2) The second problem is that `DocCommentConverter.ConvertToRegularComments` seems to remove `<devdoc>` tags, but does not remove the comment completely, if it is empty after filtering all XML elements.

The decompiler integration simply invokes that service after the decompiled source is generated (containing standard XML documentation comments as understood by the compiler):

https://github.com/dotnet/roslyn/blob/7d97db435f1d30285efdc8f77e1d573ea8b5075a/src/EditorFeatures/CSharp/DecompiledSource/CSharpDecompiledSourceService.cs#L135-L142

@sharwell I think a sensible solution is to remove the comments in the `DocCommentConverter` visitor implementation, if the comment content/text is empty. Actually, the first problem (see https://github.com/icsharpcode/ILSpy/issues/1908) could have been fixed there as well, but I was not sure, what side-effects a bugfix might have.

---

Addendum: I just opened `PackageRegistrationAttribute` using standard MAS (= no decompilation) and it has the same problem, i.e. empty comments:

![image](https://user-images.githubusercontent.com/344204/72569903-cd24c400-38bb-11ea-945a-7813e95ad0be.png)

**Comment by siegfriedpammer** [comment]
Possible fix: https://github.com/dotnet/roslyn/compare/master...siegfriedpammer:dev/siegfriedpammer/mas-xmldoc-fixes
