### ISSUE TITLE
NuGet package description typo

### ISSUE THREAD

**Issue by cyungmann** [dotnet/roslyn#39887]
https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/3.3.1 has "Destkop" instead of "Desktop"

Would submit a PR but I couldn't quickly find this text anywhere in the repo.

**Comment by Youssef1313** [comment]
I think it was fixed in #39272, but not sure when it's reflected in nuget.org

**Comment by svick** [comment]
The description of packages since [3.5.0](https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/3.5.0) contains the correct spelling, so this issue can be closed.
