### ISSUE TITLE
Can't use ?. in an expression returning a ReadOnlySpan

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#39883]
**Version Used**: Visual Studio 16.4 preview 4

**Steps to Reproduce**:

Compile the following:

```csharp
using System;
public class C
{
	public ReadOnlySpan<char> M(string? s)
	{
		return s?.AsSpan() ?? throw new ArgumentNullException();
	}
}
```

**Expected Behavior**:

Compiles without error

**Actual Behavior**:

Error CS0023	Operator '?' cannot be applied to operand of type 'ReadOnlySpan<char>'

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi has very kindly explained to me why this error occurs, but I think the error message is extremely confusing, so I will leave this open so it can hopefully be labelled with diagnostic-clarity.

A better message would be "? operator cannot be used in expression returning type of `ReadOnlySpan` as it would require creating a temporary Nullable of a ref type".

**Comment by RikkiGibson** [comment]
Seems like when the type `ReadOnlySpan<char>?` appears in source we use this diagnostic:
```xml
  <data name="ERR_BadTypeArgument" xml:space="preserve">
    <value>The type '{0}' may not be used as a type argument</value>
  </data>
```

Don't know how helpful that is though.

**Comment by CyrusNajmabadi** [comment]
The message was clarified:

![image](https://user-images.githubusercontent.com/4564579/199312669-ea29b059-5c1e-4201-8964-8703497e8fd1.png)

Closing out.
