### ISSUE TITLE
Enabling nullable reference context forces too many "?" suffixes.

### ISSUE THREAD

**Issue by Yen-David** [dotnet/roslyn#39886]
**Version Used**: C# 8

**Steps to Reproduce**:

1. Enable nullable reference context.
2. Create a new class library.
3. You realize the need to use the "?" suffix extensively for public member parameters.

**Expected Behavior**:

Both "string" and "int" should indicate default behaviors, while "string?" and "int?" indicate nullable types and "string!" and "int!" indicate non-nullable types, for syntactical consistency. Defaults should be set as follows, to adhere to Internet protocol conventions, loose on inputs and strict on outputs, given that most API's prefer location transparency, local and remote alike: (1) inputs default to nullable and outputs to non-nullable; (2) returns and getters default to non-nullable to make null propagation optional, while out parameters and setters default to nullable for default values, especially in the case of TryXXX() methods, which make all nullable returns obsolete; (3) public and protected member inputs default to nullable for caller-friendliness and Internet-friendliness, as all inputs should be optional and have good defaults, while internal and private member inputs to non-nullable, as nulls should be handled at the "public surface".

This way, we can eliminate most type suffixes and encourage a very well-behaving API design.

**Actual Behavior**:

You realize the need to use the "?" suffix extensively for public member parameters.

**Comment by CyrusNajmabadi** [comment]
This is both a request to change the language, and the default behavior of corefx.  Both are unlikely to happen. However, if you do want to push forward with this, the right locations are:

1. dotnet/csharplang
2. dotnet/corefx

Roslyn is not the right repo for this as it is the location of the compiler, which is behaving correctly as per all specifications.

**Comment by CyrusNajmabadi** [comment]
> Defaults should be set as follows, to adhere to Internet protocol conventions, loose on inputs and strict on outputs,

Note: this is unlikely to ever happen.  This approach masks issues and violates the approach corefx has taken for decades about validating and throwing on invalid values (like null).

**Comment by Yen-David** [comment]
I am aware that this is unlikely to happen. However, given the breaking changes of nullable references and the need to enable a context to make the new feature less intrusive, it may be a good idea to have a more stable long-term direction. How am I supposed to move this issue to dotnet/csharplang? Should I copy it over to the new location and "close" this one?

**Comment by CyrusNajmabadi** [comment]
> I am aware that this is unlikely to happen. However, given the breaking changes of nullable references 

Nullable references are not a breaking change.  That's a core part of their design.

**Comment by Yen-David** [comment]
I added a new issue at dotnet/csharplang (https://github.com/dotnet/csharplang/issues/2983). You can close this one if you wish. Changing the interpretation of "string" from a nullable string to a non-nullable string IS a breaking change. If you fear that my proposal WOULD create too much work for you in the long run, please communicate your concerns with the C# team.

**Comment by Yen-David** [comment]
No worries, the new work will not hit you until at least a year later. By then, you'll be working for Facebook like Eric Lippert, the best C# compiler developer.

**Comment by CyrusNajmabadi** [comment]
> Changing the interpretation of "string" from a nullable string to a non-nullable string IS a breaking change.

The compiler never does this.  It would only happen if you added something to your project file, or used `#nullable enable`.  In which case there is no break.  You wrote new code with new meaning.  Any code you didn't touch preserves the same meaning, even with the new compiler.

**Comment by Yen-David** [comment]
So, I am making a new library. Should I turn the option on or not? Why not make it a default for all new C# projects? Why must I turn it on manually every time, if it's that good? I am afraid that this feature would not last, subject to fierce changes in the new few years, up to 2023 when .Net 8 is shipped.

**Comment by CyrusNajmabadi** [comment]
>So, I am making a new library. Should I turn the option on or not?

Do you want NRT semantics?  Or do you not want them?  If you want them, turn the option on.  If you don't, leave it off.

> Why not make it a default for all new C# projects?

Such questions are better suited to dotnet/project-system.  They can decide what they would prefer.  At some point it might be a good default to switch to.  Probably once it reaches some critical mass in the ecosystem.

> Why must I turn it on manually every time

Because it's not the default.

> I am afraid that this feature would not last

If you are concerned about the future of a feature, my recommendation would be to not use it.

--

Note: most of this conversation is out of scope for this repo.  If you wish to discuss things further, i recommend some reasonable venue like gitter.im/dotnet/roslyn or discord.gg/csharp.  Cheers!

**Comment by Yen-David** [comment]
Well, at least I've got a recommendation from you: try not to use a new feature until it becomes default, which is much less likely to change in future. Thank you for addressing my fear, the reason why I opened this issue in the first place.

**Comment by Yen-David** [comment]
Without people trying the new feature, you'll unlikely get good feedback from them. That means that the new feature will remain an option forever, for the small minority only. Why should I design my API for the extreme minority? Let's forget everything that's not default in the base libraries. Cheers!

**Comment by CyrusNajmabadi** [comment]
Note: most of this conversation is out of scope for this repo. If you wish to discuss things further, i recommend some reasonable venue like gitter.im/dotnet/roslyn or discord.gg/csharp. Cheers!

**Comment by Yen-David** [comment]
Don't worry. It's over. Cheers!

**Comment by CyrusNajmabadi** [comment]
Can you close out this issue then?  Thanks.

**Comment by Yen-David** [comment]
Oops, I just saw this. No objection to the closure, of course. I am in the Eastern Time Zone. That's why. Cheers!
