### ISSUE TITLE
read external file

### ISSUE THREAD

**Issue by ndung** [dotnet/roslyn#3989]
Hi, do you have any idea how to read external file within roslyn analyzer? Because it is using .net portable library, some features to read file are missing. 

Thanks.

**Comment by jmarolf** [comment]
Take a look at [additional files](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md)

**Comment by ndung** [comment]
Hi @jmarolf, thanks for pointing it out. I just read the article and it works!
