### ISSUE TITLE
C# override completion does not seem to be adding using directives

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#39909]
**Version Used**: 16.5.0 Preview 2.0 [29519.175.master]

Is this a known regression?

**Comment by jasonmalinowski** [comment]
@ivanbasov?

**Comment by ivanbasov** [comment]
It is definitely a regression. Working fine in 16.3.9 but fails to add in 16.5.1. Let me see what happened between. Thank you!

**Comment by CyrusNajmabadi** [comment]
@genlu do we know what happened here?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/43173
