### ISSUE TITLE
Go to Base with caret inside class members

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#39908]
I would like to be able to use the Go to Base command in a context like the following:

```cs
class Derived : Base
{
    void M1() { }
    
    || // caret here

    override void M2() { }
}
```

Desired behavior: I hit Alt+Home and it shows the bases for `class Derived`, just as if I had hit it over the class name syntax. This is similar to how the Run Tests in Context (ctrl+R, T) command will run all the tests in the class when the caret is inside the class.

Perhaps other commands would be applicable too. Go to Definition to list the various declarations of a partial class, etc.

/cc @sharwell @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
