### ISSUE TITLE
Error list experience on closing documents

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#39902]
Follow-up issue to discuss https://github.com/dotnet/roslyn/pull/39892#issue-342926809. That PR restores the prior error list behavior of removing closed file diagnostics from error list whenever a document is closed. This issue tracks discussing if we want to change that experience.

**Comment by dpoeschl** [comment]
Design Meeting Notes

We would like to keep the new behavior (diagnostics not cleared when files closed) for C#/VB, but will help partner teams that want to restore the old behavior (diagnostics cleared when files are closed) for their languages.
