### ISSUE TITLE
Use Base Type Where Available refactoring 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#39905]
Customer request copying here:

 **Steps to Reproduce**:

 1. Have a keyboard shortcut, lightbulb suggestion, or right click context menu option when your caret is on a type to `Use Base Type Where Available`

 3. The `Use Base Type Where Available` dialog will open

 ![image](https://user-images.githubusercontent.com/46729679/69269349-aed56d00-0b85-11ea-8498-7648356aa90e.png)

 4. Select one of the base types

 5. Have an option to select if you want to replace type usages in the `is` operator and/or in the `typeof` operator. 

 6. If conflicts are found prompt the user to resolve the conflicts and if there are no conflicts the refactoring will perform immediately.

**Comment by ryanbrandenburg** [comment]
Design Meeting Notes:
> The general thinking here is that we're not sure the value this would generate would justify the upkeep cost. "Least specific type" is a less common design-principal in C# than in say Java. If developers still think they would benefit from this we can provide some guidance on writing their own analyzer.
