### ISSUE TITLE
Not obvious how to remove CS8618 warning with generics

### ISSUE THREAD

**Issue by jonesdwg** [dotnet/roslyn#39917]
Consider the following generic class:

```csharp
public class Merge<T>
       where T : notnull      
    {
        private bool _first = true;
        private T _merged; // CS8618 warning on the constructor
        private readonly Func<T, T, T> _merge;

        public Merge(Func<T, T, T> merge)
        {
            _merge = merge;
        }
       
        public T Next(T item)
        {
            if (_first)
            {
                _first = false;
                _merged = item;
            }
            else
            {
                _merged = _merge(_merged, item);
            }
            return _merged;
        }
    }
```
It's not obvious how to get rid of the uninitialised _merged warning. From the documentation, I'd expected the following to work, but it doesn't:

```csharp
   [MaybeNull] private T _merged;
```
NB: The the following does remove the warning.

```csharp
   private T _merged = default!
```

Kind of duplication of [37511](https://github.com/dotnet/roslyn/issues/37511), but ideally I'd like some way of telling the compiler that I never want to read the value of this field unless it's been initialised. FWIW, I also tried:

```csharp
   [MaybeNull][DisallowNull] private T _merged;
```

**Comment by RikkiGibson** [comment]
We now allow `T?` on unconstrained type parameters in C# 9, so the fix is to change your delegate type to `Func<T?, T, T>`.

**Comment by RikkiGibson** [comment]
Thanks for filing this issue, I hope the solution is useful to you.
