### ISSUE TITLE
'Generate Equals and GetHashCode...' should honor 'csharp_style_var_when_type_is_apparent = false:error' editorconfig setting

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#39916]
**Version Used**: 16.4.0 Preview 5.0

**Steps to Reproduce**:

1. Set .editorcofig as follows:
```editorconfig
[*.cs]
csharp_style_var_when_type_is_apparent = false:error
```
2. Write a new class with 10 or more fields or properties:
```cs
class S {
    public int A;
    public int B;
    public int C;
    public int D;
    public int E;
    public int F;
    public int G;
    public int H;
    public int I;
    public int J;
}
```
3. Open Quick Actions on `S`, select `Generate Equals and GetHashCode...`, leave all fields selected.

**Expected Behavior**:
Generated `GetHashCode` declares `hash` as:
```cs
HashCode hash = new HashCode();
```

**Actual Behavior**:
Generated `GetHashCode` declares `hash` as:
```cs
var hash = new HashCode();
```
which then produces error at the `var` keyword.

**Comment by sharwell** [comment]
This refactoring should be using the fully-qualified type name, and applying the simplifier attribute to it.

**Comment by CyrusNajmabadi** [comment]
On it.
