### ISSUE TITLE
Slow analyzer hurt editor experiance

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#39927]
https://github.com/dotnet/roslyn-analyzers/issues/3048#issuecomment-554668909

With ^ the editor experience in Visual Studio suffered a lot.
- Typing lag
- Test runner slow or not running tests at all.
- Lightbulb taking 30 s to open etc.

I'm thinking maybe the analyzers used by the current document should also move out of process. Benefits would be that a crash would not crash VS and a memory leak would not hurt VS in the same way.

**Comment by CyrusNajmabadi** [comment]
@JohanLarsson can you file some reports using https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues ?
