### ISSUE TITLE
Change 'Implement Interface' refactoring to offer 'Embed Interface members in Region' at the same time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39930]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/825471/change-implement-interface-refactoring-to-offer-em.html)._

---
I would like to propose that the 'Implement Interface' / 'Implement Interface Explicitly' refactorings offer the chance to wrap the generated interface members in a Region. The default Region name could be prepopulated with the Interface name.

---
#### Visual Studio Feedback System on 11/20/2019, 01:00 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Support for this was intentionally removed as just being a pattern that we no longer want to support.
