### ISSUE TITLE
Menu that clicks the number of public / private methods not being used anywhere in the system.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39937]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/813189/menu-that-clicks-the-number-of-public-private-meth.html)._

---
In large projects with many modifications, it is sometimes difficult to know how many public / private methods are orphaned and no longer used. With this menu you will be able to validate orphaned methods more easily.

---
#### Visual Studio Feedback System on 11/11/2019, 00:13 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
Can we make unused private/public methods a code style rule so it can show up in the error list? Similar to unused parameters / private members.

**Comment by ryanbrandenburg** [comment]
Design Meeting Notes:
> This is probably better suited as a larger tool that Roslyn could consume rather than as something contained entirely within the IDE. As such we've filed https://github.com/dotnet/sdk/issues/24911 which we would build upon for IDE experience.

**Comment by CyrusNajmabadi** [comment]
CLosing out as out of scope.
