### ISSUE TITLE
C# editor: tooltip for extension lacks info

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39933]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/824332/c-editor-tooltip-for-extension-lacks-info.html)._

---
When you show tooltip for extension, only signature is shown. It could be nice to have full extension description like it's shown for normal method - summary, parameters. No need to show exceptions, it's useless.

---
#### Visual Studio Feedback System on 11/18/2019, 11:32 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.   We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
I was not able to reproduce this issue. When I selected an extension method in completion, it showed me the summary and parameter info the same way it does for other methods.
