### ISSUE TITLE
Intellisense should avoid suggesting the current property I'm in as a return value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#39931]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/822337/intellisense-should-avoid-suggesting-the-current-p.html)._

---
Consider this code sample:

```
public class TestClass
{
    private int someBackingProperty;

public int SomeBackingProperty
    {
        get
        {
            return <text cursor here>
        }
    }
}
```

- If I type `return someB`, it suggests `someBackingProperty`
- If I type `return someb`, it suggests `SomeBackingProperty`, which will cause a `StackOverflowException`

Failing to type a capital B makes it suggest `SomeBackingProperty`, I am not sure why that is because what I typed is still closer to `someBackingProperty` because of the lowercase s at the start.

Due to some unfortunate decisions of the most popular naming style for C#, the name of the backing field will typically be one capitalization away from suggesting the wrong thing.

Is it possible to make Intellisense never suggest the property I'm in currently? I am okay with it showing up as an option but I think it should never be highlighted (where hitting Tab will immediately insert it).

Also,

- It might be valuable to have a compiler warning if Roslyn detects that a property's body will cause a `StackOverflowException`

---
#### Visual Studio Feedback System on 11/18/2019, 01:53 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.   We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
