### ISSUE TITLE
Need to have a way to specify group/order for CodeFixAction provided by CodeFixProvider

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn#3994]
Our CodeFixActions suggest missing nuget packages and we wanted to place them in a separate group below code refactoring suggestions in Ctrl. menu. As we discussed in email, we would like to keep using Roslyn's infrastructure instead of implementing our own code that dials with Ctrl. menu.  It would be nice if grouping support could be added in U1 timeframe.

**Comment by CyrusNajmabadi** [comment]
Needs to provide an API proposal and go thruogh teh API review process.
