### ISSUE TITLE
Roslyn vs DLR

### ISSUE THREAD

**Issue by hardvain** [dotnet/roslyn#3995]
Given that roslyn can express all of the C# syntactic and semantic models, and dlr is pretty lightweight for language creations, which is recommended for creating a new programming language for the CLR. Thought the language i intent to create is a dynamic language, will using roslyn help me more when compared to dlr? I was first intending to use dlr to create the expression tree and the emit IL from it. But should I use roslyn? Are there any materials towards using roslyn for creating a programming language targeting clr?

**Comment by DustinCampbell** [comment]
Currently, Roslyn does not support the notion of adding more languages. It's not designed to be a toolkit for building compilers or languages. It's very tuned to C# and VB. That might change someday in the future, but that's where we'd at today.

**Comment by govert** [comment]
[Irony](http://irony.codeplex.com/) is a toolkit for developing new .NET languages. @KirillOsenkov wrote a nice [introduction / walkthrough](http://blogs.msdn.com/b/kirillosenkov/archive/2009/10/31/irony.aspx) about it many years ago.

**Comment by dsaf** [comment]
[Nitra] (https://github.com/JetBrains/Nitra) is a promising language work-bench.
