### ISSUE TITLE
Make Features Layer Portable

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#3998]
This is required to expose Features APIs like completion for OmniSharp and VS Code.

**Comment by dfkeenan** [comment]
:+1:  Just making it public would be awesome.  But the more that is portable the better :smile:

**Comment by DustinCampbell** [comment]
Well, "just making it public" is a lot of work. Right now the internal APIs are not suitable to be made public. However, we're actively working on designing several of the key APIs included there to become public for developing editing experiences.

**Comment by dfkeenan** [comment]
I didn't mean to trivialize to amount of effort involved.  Just letting you know I would be keen to get my hands on some of the stuff in there.  And letting you know I appreciate the work you (and the rest of the team) are doing.

**Comment by DustinCampbell** [comment]
I suppose I should have added a :smile: to not have come across so grouchy earlier.

It'd be cool to know what you're interested in getting out of the Features layer. General "make it all public" requests aren't as helpful since we have to support this API for years to come and need to be judicious about what we expose.

:smiley:

**Comment by dfkeenan** [comment]
Haha, I was more worried that maybe I came off as sounding demanding/disrespectful.  I guess that's one of the pitfalls of text based chat, much easier to misinterpret meaning.  Especially when the people involved don't know each other. Anyways back on topic.....

To be honest I haven't looked into what all the "Features" are (so much code).  But I know completion services would be a big ticket item.  I was using it when it was public in one of the early CTPs.  Being able to implement a `ISnippetCompletionProvider` would be helpful too, though from memory they are pretty small and call another interface to get the snippet files (that stuff might have been in EditorFeatures).

I was creating a small code (script) editor using Roslyn and AvalonEdit.  Over like 2 weekends I had a pretty cool little editor with:

- Semantically aware syntax highlighting (i.e. could tell when a token was a keyword and when it wasn't).
- Code completion
- Snippets (using the VS Snippet file format)
- Diagnostic squiggles
- Tooltips for symbols

I still had some kinks to work out and the implementation might not have been the best but still pretty cool for so little effort on my part.  My plan was to get as many VS code editor features in there as I could.  I wanted to be able to provide an editor for automation/macros/extensions in other applications. So obviously the more you make public the less I would have to reinvent. :smile:  

But with the generosity of the Community Editions of VS that becomes less of a problem, and more about the fun of making something cool.

**Comment by DustinCampbell** [comment]
Features layer binaries are now portable with #4759.

**Comment by david-driscoll** [comment]
@DustinCampbell has this landed in the nightlys yet?  I was looking and 09/03 still only had .NET 46 as the supported framework.

**Comment by Pilchie** [comment]
I think the thing missing is updating the folder structure for the nuget.  The actual binary is portable now.

**Comment by DustinCampbell** [comment]
Yup -- I'm looking at that right now. I completely forgot to update the nuspec.

**Comment by davkean** [comment]
Going to drop infrastructure, and add IDE as this is a product work item.

**Comment by Pilchie** [comment]
The nuget package fix was actually submitted on Sep 4 too, just forgot to close this issue.
