### ISSUE TITLE
Code fix for adding null-check in a nullable context

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/roslyn#39996]
Something I miss in a context where variables are nullable is a fix to either add an if-statement or a .? (if applicable) when `null` could be expected.

It would minimize the number of key strokes.

The exact behavior should be discussed. But preferably, it should be a suggestion.

**Comment by robertsundstrom** [comment]
I have identified 3 different fixes:

1. Put an `if (x != null)` statement at a particular occurrence.
3. Add a `?.` at a particular occurrence.
2. Surround the rest of the code block. Find the place in the current scope where the nullable variable is first dereferenced. Put an `if (x != null)`  statement around the remainder of the code in that scope.

The type:

```csharp
class Foo 
{
    Bar? Bar;
}
```

Before fix:

```csharp
var bar = foo.Bar;

Console.WriteLine(bar);
```

After fix:

```csharp
var bar = foo.bar;

if (bar != null) 
{
    Console.WriteLine(bar);
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
