### ISSUE TITLE
KeepUnbalancedDirectives should keep unbalanced warning suppressions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#3999]
Suppose you remove both of the `ClassDeclarationSyntax` nodes from the following code using `SyntaxRemoveOptions.KeepUnbalancedDirectives`:

```csharp
namespace NamespaceName
{
  class ClassName
  {
#pragma warning disable SomeWarning
  }
  class ClassName2
  {
#pragma warning disable SomeWarning2
#pragma warning restore SomeWarning2
  }
}
```

### Expected results

```csharp
namespace NamespaceName
{
#pragma warning disable SomeWarning
}
```

### Actual results

```csharp
namespace NamespaceName
{
}
```

**Comment by Pilchie** [comment]
Moving to compilers, since this is a core compiler API on syntax.

**Comment by mattwar** [comment]
Unlike #if and #region, #pragma's don't have natural pairings. They are just used that way sometimes.
