### ISSUE TITLE
Using directive placement is not grouped intuitively

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#40003]
These two sections of the generated **.editorconfig** file should either be placed together or merged.

https://github.com/dotnet/roslyn/blob/04a8b13dddda6d435f027783c76db6323b525a16/src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb#L37-L39

https://github.com/dotnet/roslyn/blob/04a8b13dddda6d435f027783c76db6323b525a16/src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb#L124-L125

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  If we want to merge these just merge them.  These issues don't solve anything.
