### ISSUE TITLE
Description of code fix for "unnecessary assignment" is misleading when the variable is removed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#40002]
**Version Used**: 
Version 16.5.0 Preview 2.0 [29524.9.master]

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1103906/69509358-c6996080-0f8c-11ea-8e95-6155117dd1ae.png)

**Expected Behavior**:
"Remove unnecessary variable"

**Actual Behavior**:
"Use discard '_'

**Comment by sharwell** [comment]
@mavasani This is similar to https://github.com/dotnet/roslyn/issues/38507#issuecomment-530051256
