### ISSUE TITLE
IDE tests failed in the C# 9.0 pattern-matching feature branch

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#40015]
The following IDE tests fail in the C# 9.0 pattern-matching feature branch:
- `SymbolCompletionProviderTests.PositionalPatternSecondPosition`
- `PropertySubpatternCompletionProviderTests.PropertiesInRecursivePattern_InPositional_Incomplete`
- `PropertySubpatternCompletionProviderTests.PropertiesInRecursivePattern_InPositional_Incomplete_WithoutClosingBrace`
- `PropertySubpatternCompletionProviderTests.PropertiesInRecursivePattern_PositionalInFirstProperty_AfterComma`
- `WhenKeywordRecommenderTests.TestForSwitchCase_SemanticCheck_NotAfterPredefinedType_BeforeBreak`
- `WhenKeywordRecommenderTests.TestForSwitchCase_SemanticCheck_NotAfterPredefinedType_BeforeWhen`
- `WhenKeywordRecommenderTests.TestForSwitchCase_SemanticCheck_NotAfterPredefinedType`

These are skipped for now in the feature branch.  We'll have to investigate and adjust the tests if necessary.

**Comment by gafter** [comment]
Per our conversation, I am assigning to @CyrusNajmabadi for reviewing the affected tests.

Please assign back to me if you identify any compiler misbehavior.

**Comment by CyrusNajmabadi** [comment]
yup.  i'll takea  look asap.

**Comment by Youssef1313** [comment]
@gafter @CyrusNajmabadi Is this still an issue?
These tests seem to exist un-skipped in master.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We fixed all of these :)
