### ISSUE TITLE
CS0121 (ambiguous invocation) thrown when enabling nullable reference types for parts of solution

### ISSUE THREAD

**Issue by mareklinka** [dotnet/roslyn#40033]
**Version Used**: VS 2019 (16.3.10)

**Steps to Reproduce**:
Open unit test in attachment: [AmbiguityRepro.zip](https://github.com/dotnet/roslyn/files/3895511/AmbiguityRepro.zip)
Try compiling the code.

**Expected Behavior**:
The compilation works without issues.

**Actual Behavior**:
CS0121 is returned in Output pane (not in Error List pane). The compiler thinks the call to `ExecuteAsync` is ambiguous (apparently to itself, since there is no other method).

**Explanation I can guess at**
This has something to do with setting `<Nullable>enable</Nullable>` on the `Infrastructure` project and keeping it disabled on the `Implementation` project. Then it errors out. If I keep nullable reference types disabled on both projects, the solution compiles. If I enable NRT on both, it compiles as well.

Could someone explain why this is happening? I came across this behavior when experimentally enabling NRT on our production code (on a few projects at a time). Also, sorry for weird naming, I just threw together the fastest repro I could, it kinda reflects our code organization.

**Comment by jcouv** [comment]
Sorry, we've not been able to take a look at this yet. Would it be possible to provide a self-contained repro, for example as a link to a [sharplab repro](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEEAsBuWBiAdgVwBsCBDAIwIFNEKczLZwBmRAb1kQ+WZQDZlVEAWQAUKRgB5hAe1IArCgGMALgH4ANIhnzlKxADlCJchQCUAPkQBLJRQC2AZxOJ2nNjE4fEAN2IAnRASW9kqIALyIOBQA7ogAMkFKklqKqhrJyvpSOAZEdKZmwiaY7p4cLqUAZlK+FMQKABbCPv7WdlY4VjYOTm6lpZYViMKttgB0OUaUVvYRhiblfaUgAOzFi4sLi4HBowCCACb7w11FiAD0Z4hRfjgzwjhZVBQAHgAOKRT78yWlAL4L/xgvyAA=) or snippet?

**Comment by mareklinka** [comment]
As far as I understand the problem it requires multiple projects in a solution to interact. One of them is nullable enable and one is not. I don't think I can minimize it more than the repro in the attachment above.

**Comment by jcouv** [comment]
Ah, makes sense. Thanks

**Comment by BlowaXD** [comment]
Took me several hours to figure out that I had the same issue and then found this issue.
https://github.com/BlowaXD/csharp-nullable-weird-behavior

Hope this helps.

Thanks

**Comment by jcouv** [comment]
Fix is in for 16.5p3
