### ISSUE TITLE
Refactoring to reverse the direction of a for loop

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40046]
Either direction:

```cs
for (var i = foo; i < bar; i++)
```

```cs
for (var i = bar - 1; i >= foo; i--)
```

Maybe variations:

```cs
for (var i = foo; i <= bar; i++)
```

```cs
for (var i = bar; i >= foo; i--)
```

Or:

```cs
for (var i = foo; i != bar; i++)
```

```cs
for (var i = bar; i >= foo; i--)
```

If the increment is anything other than adding or subtracting constant 1, the for loop can't be reversed without potentially changing the reversed sequence. E.g. 0, 2, 4 could become 5, 3, 1.

**Comment by CyrusNajmabadi** [comment]
I'm up for this
