### ISSUE TITLE
Need to evaluate how our code change services handle linked documents

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#40040]
Because the result of our services (e.g. MoveType service) is often used as an intermediate state which will undergo further change made by other, say, refactorings, it will need either propagate changes made to one of many linked files to others, or consolidate changes made in all linked documents, before passing it on. Otherwise, there will be inconsistency in the content among linked documents, causing problem in downstream code changes.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should either do this in a milestone or accept our behavior here.
