### ISSUE TITLE
[Proposal] DataAnnotations for properties

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#40054]
I suggest that you allow using the attributes defined in System.ComponentModel.DataAnnotations with any property in C#, F#, VB.NET, not just ASP.NET. For example:
```C#
[Required]
[MinLength(2)]
[MaxLength(12)]
public string FirstName { get; set; }
 ```
ASP.NET generates server side validation code for these attributes (beside the client side validation scripts), so, I think you can make Roslyn borrow the class that generates the server side code to generalize the concept outside ASP.NET. No need of course for the attributes used with tag helpers to affect the UI such as DisplayAttribyte, although it can be used with XAML in wpf, uwp and Xamarin if Xaml added the tag helpers concept too.

C# and VB.NET ask for property auto-validation for years, and it is strange it didn't happen till now, while it is supported in ASP.NET for ages!

**Comment by ronnygunawan** [comment]
`System.ComponentModel.DataAnnotations` comes with [Validator](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator?view=netcore-3.0) class. You can use it to validate your annotated models.

**Comment by huoyaoyuan** [comment]
> C# and VB.NET ask for property auto-validation for years, and it is strange it didn't happen till now, while it is supported in ASP.NET for ages!

Unlike application framework, the language/compiler itself avoids to special treat too much things.
It's very easy to implement it, but it's architecturally wrong. It can be a good candidate of custom generator API.

**Comment by gafter** [comment]
Language feature requests belong in [`csharplang`](https://github.com/dotnet/csharplang) for C#.  This repo is for the implementation of the language and the IDE.  Since the language currently doesn't work this way, we won't implement it.

**Comment by VBAndCs** [comment]
@gafter
> This repo is for the implementation of the language and the IDE

It seems to me that this is just a validation code generation, which doesn't need any language change. Why can't the IDE generate this validation code in a pre compiling mode?

**Comment by huoyaoyuan** [comment]
> which doesn't need any language change

The meaning of `DataAnnotation` is language specification. Language is not application framework. Any behavior must be spec'ed before implement.

**Comment by gafter** [comment]
@VBAndCs The IDE does not generally modify the source of the user's program without the user requesting that by some gesture. The meaning of a program is defined by the C# specification.  If the meaning of a method body does not include validation according to the language specification, then no validation will occur.

**Comment by VBAndCs** [comment]
@gafter
ASP.NET does it , why not the IDE? You can add some IDE framework to auto-generate co
de for attributes and user-defined code templates.
You are using AI to suggest auto complete code. I think it is more human inelegance to make the IDE write repeated blocks of code, especially that ASP.NET already does this!
Thanks anyway.

**Comment by gafter** [comment]
ASP.NET does not modify a user's program.  It generates the user's C# program by assembling snippets from elsewhere.

**Comment by VBAndCs** [comment]
@gafter
This is exactly what I am asking for. The IDE will not change the source code. It will generate a temp file containing the new modified code, and add it to a temp solution so C# use it to build the exe/dll. The IDE can highlight the attribute in the original code when a validation exception occurs.
So, the idea complies to your conventions:
1. No source code is altered.
2. The programmer gets what he asked for when he used the arribute.
3. No change whatsoever in C# nor VB.NET compilers. They have no idea about all of this.

**Comment by VBAndCs** [comment]
Another case exists in EF:

```C# 
[MaxLength(500)]
public string Url { get; set; }
```

Docs say:
> Entity Framework does not do any validation of maximum length before passing data to the provider. It is up to the provider
> or data store to validate if appropriate. For example, when targeting SQL Server, exceeding the maximum length will result in
> an exception as the data type of the underlying column will not allow excess data to be stored.

It is very bad to pass wrong data to the provider, while we already wrote a code to mark it as bad!
This is not how should modern languages work.
