### ISSUE TITLE
'left' and 'right' in generated equality operators should be nullable.

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#40053]
**Version Used**: 16.4.0 Preview 6.0

**Steps to Reproduce**:

1. Paste following code:
```cs
#nullable enable
using System;

namespace N {
    public class C {
        public int X;
    }
}
```
2. Run `Generate Equals and GetHashCode...` on `C`, leave `Generate operators` checked.

**Expected Behavior**:
Generated operators:
```cs
public static bool operator ==(C? left, C? right) => EqualityComparer<C?>.Default.Equals(left, right);
public static bool operator !=(C? left, C? right) => !(left == right);
```

**Actual Behavior**:
Generated operators:
```cs
public static bool operator ==(C left, C right) => global::System.Collections.Generic.EqualityComparer<global::N.C>.Default.Equals(left, right);
public static bool operator !=(C left, C right) => !(left == right);
```
Which then cause this code to produce warning:
```cs
C? c = null;
if (c == null) { // Possible null reference argument for parameter 'left' in 'bool C.operator ==(C left, C right)'.
}
```

**Comment by CyrusNajmabadi** [comment]
Not repro.  We do generate this correct in a nullable enabled region:

![image](https://user-images.githubusercontent.com/4564579/152890503-97b9d31d-b267-4744-a0ea-5464b77dd4cc.png)
