### ISSUE TITLE
TypeInfo.ConvertedType.NullableAnnotation is None when binding a 'var' keyword

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#40052]
This is being observed in https://github.com/dotnet/roslyn/pull/40030 as I'm removing the IDE's nullable wrappers. If you run [this test](https://github.com/dotnet/roslyn/blob/8d1995963dc0d7add5f6482e323ced9bae2f971b/src/EditorFeatures/CSharpTest/CodeRefactorings/UseExplicitOrImplicitType/UseExplicitTypeRefactoringTests.cs#L298) in the branch it fails. The test is calling GetTypeInfo on the argument and grabbing the ConvertedType [here](https://github.com/jasonmalinowski/roslyn/blob/d3e3d359ca97e4652582206cb052646d66bcdb06/src/Features/CSharp/Portable/TypeStyle/UseExplicitTypeCodeFixProvider.cs#L93). The old nullability APIs say that it is indeed nullable, but the new ITypeSymbol.NullableAnnotation still says None.

I believe the expectation now is the ITypeSymbol.NullableAnnotation should have brought along the annotated state of Annotated.

**Comment by AlekseyTs** [comment]
@jasonmalinowski Could you please clearly describe the issue in following terms?
- Here is a source
- On this node/token an API is called (which API)
- Here is the result
- Here is what expected.

**Comment by jasonmalinowski** [comment]
If you look at [this test](https://github.com/dotnet/roslyn/blob/8d1995963dc0d7add5f6482e323ced9bae2f971b/src/EditorFeatures/CSharpTest/CodeRefactorings/UseExplicitOrImplicitType/UseExplicitTypeRefactoringTests.cs#L301-L311), the highlighted span is the code. If we call GetTypeInfo on the "var" keyword, the TypeInfo has ConvertedNullability property saying it's annotated as "string?", but the ITypeSymbol given by the ConvertedType property has a NullableAnnotation of "none". The expectation in this case would be it carries along the nullability.

**Comment by AlekseyTs** [comment]
I believe this issue should be fixed by https://github.com/dotnet/roslyn/pull/40338.
