### ISSUE TITLE
catch/finally on using statement for C# and VB

### ISSUE THREAD

**Issue by jmaine** [dotnet/roslyn#4005]
It would be nice to be able to put a catch/finally blocks directly on the using statement (like it is currently possible on a try block) for VB and C#.

Example C#:

```
using (var v = new Resource()) 
{

}
catch (Exception e)
{

}
finally
{

}
```

Example VB:

```
Using r = As new Resource()

Catch Ex as Exception

Finally

End Using
```

If an exception is though at the end of the Using block (from the Dispose() method) and somewhere between the braces of the using block, the exceptions will be aggregated either by throwing a AggregateException or by placing the exception thrown at the end into a property of the exception thrown between the braces. Secondly either relax the IDisposable contract so that the Dispose() can throw exceptions or create a new interface for that purpose. And this new interface would be treated like the IDisposable interface in a using statement.

This would make it easier to properly code WCF clients, network and file streams where exceptions thrown at the closing of the stream need to be caught and dealt with accordingly.

**Comment by HaloFour** [comment]
You can do the following now, although the auto-formatter will fight you:

```cs
using (var resource = new Resource()) try {
}
catch (Exception exception) {
}
finally {
}
```

What is the lifetime of the resource in your example?  Is the variable available in the `catch` and `finally` clause or is it disposed of by then?  This seems like trying to bring try-with-resources from Java to C#.

**Comment by jmaine** [comment]
Yes, it is exactly like bringing try-with-resources over to C#. The resource will be closed before finally or catch clauses are run. Even exceptions thrown in constructor of the example in the resource declaration area will be caught in the catch clause.

''''
var resource = null;
try {


}

**Comment by jmaine** [comment]
The compiler will also emit the above for the Exception class even when the user does not specify it. The same goes for the finally clause.

**Comment by gafter** [comment]
> It would be nice to be able to put a catch/finally blocks directly on the using statement (like it is currently possible on a try block) for VB and C#.

Why would it be nice?

**Comment by jmaine** [comment]
It would simplify common patterns like this in the code:
```c#
try {
    using (var resource = new Resource()) {

    }
}
catch (Exception e) {

}
```
to
```c#
using (var resource = new Resource()) {

}
catch (Exception e) {

}
```

Second, `using` would not swallow up exceptions into a black hole if something between the braces throws an exception and `Dispose()` also throws an exception and would allow the user to retrieve the suppress exception if he or she wanted to or needed to. (I personally do not mind if `try` or `using` is used for this feature.)

**Comment by gafter** [comment]
(Note to self) this looks a lot like Java's try-with-resource construct.

**Comment by HaloFour** [comment]
That being the case I'd think I'd prefer Java's syntax to the syntax proposed above.  This syntax is one missing curly brace away from being mistakenly associated with the wrong `try` block.

Is there a particular reason why `try` blocks require curly braces?  If they didn't you could always use `try using (...)` although I imagine the formatter would still fight over the indentation of the block as it does now with `using (...) try`.

Honestly in Java I find TWR a bit annoying because often enough I still want to be able to access the resource from the `catch` or `finally` block so I have to double-`try` anyway.

**Comment by gafter** [comment]
@HaloFour 
> Is there a particular reason why `try` blocks require curly braces?

Yes, it removes a syntactic ambiguity when try blocks are nested.

**Comment by jmaine** [comment]
@gafter 
> (Note to self) this looks a lot like Java's try-with-resource construct.

Exactly, I have seen this boiler plate code that this would replace many times in c# that it is at least worth looking into.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.
