### ISSUE TITLE
Why is StartsWith more slower than Contains?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#40063]
StartsWith/EndsWith is more slower than Contains, almost 10x:
```
        static void Main(string[] args)
        {
            string str = "abcdaaaaaa";
            for (int i = 0; i < 10000000; i++)
                str.StartsWith("abcde");
        }
```

My PC, StartsWith = 3000ms, Contains = 300ms, MyStartsWith = 700ms:

```
static class Extension
{
    public static bool MyStartsWith(this string str, string value)
    {
        if (str == null)
            throw new NullReferenceException();
        if (value == null)
            throw new ArgumentNullException();
        if (value == "")
            return true;
        if (value.Length > str.Length)
            return false;
        for (int i = 0; i < value.Length; i++)
            if (str[i] != value[i])
                return false;
        return true;
    }
}
```

**Comment by huoyaoyuan** [comment]
First of all, here's the wrong position to ask. This problem belongs to the runtime repo.

You can answer yourself if you do a quick search to the source code:
https://source.dot.net/#q=string.StartsWith
https://source.dot.net/#q=string.Contains
Parameter less `StartsWith` does a culture-aware comparison, but `Contains` does an ordinal comparison.

**Comment by CreateAndInject** [comment]
Thanks!
I viewed .net source and found:
IndexOf/StartsWith/EndsWith use CurrentCulture by default
Contains use Ordinal by default
