### ISSUE TITLE
TypeScript: Feature Request: Fill switch statement on Enum (Visual Studio 2019)

### ISSUE THREAD

**Issue by fwd079** [dotnet/roslyn#40064]
Hi,

**Not a bug**, but a feature request please.

**Version Used**: 
N/A

**Steps to Reproduce**:

1.  Create an enum.
2.  Create a variable in a method for that enum, assign value.
3.  Type sw(tab)(tab) and press Enter.

**Expected Behavior**:
Like C#, enum values to be auto-listed as cases.

```typescript
 let status: StatusETW = etw.EtwStatusId as StatusETW;
            switch (status) {
                case StatusETW.Cancelled:
                    break;
                case StatusETW.Completed:
                    break;
                case StatusETW.Draft:
                    break;
                case StatusETW.EligibleToWork:
                    break;
                case StatusETW.Expired:
                    break;
                case StatusETW.UnComplete:
                    break;
                case StatusETW.Unlock:
                    break;
                default:
                    break;
            }
```

**Actual Behavior**:
This happens:
```typescript
let status: StatusETW = etw.EtwStatusId as StatusETW;
            switch (status) {

                default:
            }
```

Kind Regards.

**Comment by CyrusNajmabadi** [comment]
@fwd079 can you please refile this over at github.com/microsoft/typescript?  Thanks!

**Comment by fwd079** [comment]
> @fwd079 can you please refile this over at github.com/microsoft/typescript? Thanks!

Okay sure, posted [there](https://github.com/microsoft/TypeScript/issues/35428) now.

Kind Regards.
