### ISSUE TITLE
LSP handling of Code Actions is expensive

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#40086]
Also tracked by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1030399

1. In the case where the client does not support workspace edits, don't precompute the results of actions. Line 52 here causes the code action to produce its updated solution, but when a client doesn't support workspace edits, that result is never used:

https://github.com/dotnet/roslyn/blob/67adb950bd7216812a29cbb1e56f9c18a48d63d5/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionsHandler.cs#L51-L53

2. In the case where the client _does_ support workspace edits, do we really want to be calculating all possible futures before the user has even invoked the lightbulb?

**Comment by dpoeschl** [comment]
Talked with @dibarbet about this. We'd like to only calculate the operations (updated solutions) when the lightbulb has been expanded and the code action selected. We are discussing with other teams to make sure there was no compelling use case for calculating everything ahead of time.

**Comment by CyrusNajmabadi** [comment]
> Talked with @dibarbet about this. We'd like to only calculate the operations (updated solutions) when the lightbulb has been expanded and the code action selected. 

That seems the most sensible and sane.  At teh very least the protocol should support this.  i.e. as much as possible the protocol should allow deferring expensive operations untli the host needs them.

> We are discussing with other teams to make sure there was no compelling use case for calculating everything ahead of time.

Even if tehre is some compelling case (which i can't think of myself), it seems like that should be up to the host to decide to do, and shouldn't be the default.

**Comment by dpoeschl** [comment]
Fixed by https://github.com/dotnet/roslyn/issues/40086
