### ISSUE TITLE
Remove Workspace.OnWorkspaceFailed (breaking change)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40085]
Document load failures are now captured on `TextAndVersion`, so this event is no longer needed.

Also remove `Workspace` parameter from `TextLoader.LoadTextAndVersionAsync` API and from `MSBuildProjectLoader` constructor.

**Comment by sharwell** [comment]
We won't be able to remove the event itself, but we can stop using it at any time. Likewise, we cannot remove the `Workspace` parameter from `LoadTextAndVersionAsync`, but we can stop using it within the method.

**Comment by tmat** [comment]
I disagree. We can certainly remove it. First, we mark it as obsolete and then we remove it in 4.0.0.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This should go through API review.
