### ISSUE TITLE
Unexpected alignment of function arguments in IDE.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#40098]
Start with the following code:
```
Module Module1

    Sub Main()
        Test(
            1)
    End Sub

    Sub Test(x As Integer, y As Integer, z As Integer)

    End Sub
End Module
```

Type a comma after the ```1``` in the argument list, then press Enter and type ```2```.

Observed:
```
    Sub Main()
        Test(
            1,
2)
    End Sub
```

Expected:
```
    Sub Main()
        Test(
            1,
            2)
    End Sub
```
Works as expected in the middle of the argument list. For example, if continue with typing a comma after the ```1```, then pressing Enter and typing ```3```:
```
    Sub Main()
        Test(
            1,
            3
2)
    End Sub
```

**Comment by sharwell** [comment]
@CyrusNajmabadi This sounds related to the indentation changes

**Comment by CyrusNajmabadi** [comment]
We are unlikely to change indentation in vb due to high complexity of impl and high risk of regression.  For now, we have an lightbulb to allow you to tweak to one of many different wrapping styles for parameters.
