### ISSUE TITLE
Allow Razor to Create/Update/Delete C# content in the Workspace.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#40094]
For future scenarios Razor will need to be able to populate the Roslyn Workspace with its parsed Razor C# output. The requirements we've discovered so far are:

1. Load something by Razor into a location that has a workspace
2. Provide the workspace to Razor's loaded component
3. Provide an API that Razor can create/update/delete C# documents.

/cc @jinujoseph

**Comment by jinujoseph** [comment]
tracked internally [here ](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1030104)
cc @jasonmalinowski , @dibarbet @tmat

**Comment by CyrusNajmabadi** [comment]
Not sure what we need here.  This has had no movement in 3 years, so assuming we're good.  If not, we should define what we need and place in a real milestone.
