### ISSUE TITLE
Handling of command line arguments and paths across diferent platforms.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#401]
Related to #312 
## The goals are

a) Backward compatibility with old versions of CSC
b) .csproj files do not need to be different between Windows or Unix-like OSes

A particularly interesting issue here is how to handle paths, since Unix-like system require file path separators to be "/", while on Windows either "/" or "\" are acceptable, while "\" is very common.
## The following is basically the proposal. (and it is also what is currently implemented)
- CSC understands both "/" and "\" styles of path separators, but there are very few scenarios where it cares about paths. In most cases paths are just conveyed transparently to the file system.
- CSC will not change path separators.The reason is that "\" is actually a valid character that could be a part of file name on Unix. Without probing the actual file system, there is no way to figure what /home/foo\bar.cs means.Generally resolving paths is not responsibility of the compiler.
- In command line tool (CSC)we expect the user to specify paths in the format that underlying file system understands. I.E  on Linux you should do "csc.exe  some/folder/test.cs",  on Windows you should do  either  "csc.exe  some\folder\test.cs"  or "csc.exe  some/folder/test.cs".
  This is the natural behavior seen in many existing tools.
- When invoked externally via build system, It is responsibility of the build system to resolve paths and form them according to the environment.
  This implies that .csproj files use Windows style paths for compatibility reasons, but when they are resolved and passed to the CSC, so that paths like     " ....\proj\foobar.cs " become "  /home/user1/solution/proj/foobar.cs "

I.E - build tool is responsible for reverting "\" and making paths suitable for the platform. This is already seems to be the behavior exhibited by XBuild on Unix-like systems.
- In rare cases where compiler needs to build paths on the fly, it will use platform-specific separators. This is the only sensible way to concat directories and relative paths. Just calling this out.
- CSC understands both "-" and "/" as tokens for compiler options
  This is preexisting behavior. Both  /o+ and  -o+  should work regardless of the platform.
  Note: csc /?  advertises "/" as a way to specify options. Perhaps we should suggest "-" on Unix like systems instead.
- There is an obvious ambiguity between rooted absolute paths like /tmp/lala/test.cs  and options like /debug    on Unix

For now we will use the following heuristic - anything that looks like an option, but is followed by a slash is actually a path.  For example /debug/test.cs   is actually a path.
The only inconvenience here is that you cannot build files in root folder - like  " csc /test.cs ", but it does not appear very limiting and it is possible to do /./test.cs as a workaround

NOTE: This is not the final solution for the path|switch ambiguity. Just something that works.
There could be other schemes for disambiguating "/" on Unix. The alternative proposal is to introduce another command line switch /s:<path> that would unambiguously resolve to a path. Even if you have a file "s" in the root, you would be able to do "csc.exe /s:/s"

**Comment by agocke** [comment]
I think we should also consider using the GNU-style argument '--' indicating that all following arguments are files and not options. This can be very convenient when passing arguments manually.

**Comment by jaredpar** [comment]
Closing until we get feedback in this area.
