### ISSUE TITLE
Rename 'MultiAdd' extensions to 'Add'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#40102]
The code currently contains several `MultiAdd` extension methods that add a single element to a dictionary. These methods should have been called `Add`, because they are only adding a single element.

https://github.com/dotnet/roslyn/pull/40078#discussion_r352937129

**Comment by CyrusNajmabadi** [comment]
Closing out.  If someone wants to do this, they can just go ahead and do it.
