### ISSUE TITLE
Unify Completion Commit characters between C# and VB

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4010]
VB and C# have different sets of commit characters, but neither I, @DustinCampbell, @jasonmalinowski, or @rchande can think of why.

One supposition was type characters, but they *should* be in the list.

**Comment by DustinCampbell** [comment]
FWIW, I think I originally pulled the VB commit characters from the old VB language service. However, they are a pure subset of the C# commit characters and there are several characters in the C# set that *should* be commit characters (like ```&```). Also, TypeScript uses the same commit characters as C#, so this should be pretty trivial.
