### ISSUE TITLE
Add NuGet Package wiki entry for latest Roslyn release

### ISSUE THREAD

**Issue by slang25** [dotnet/roslyn#40109]
As the wiki isn't publically editable (https://github.com/dotnet/roslyn/issues/18516), can I suggest the follow addition to https://github.com/dotnet/roslyn/wiki/NuGet-packages, under the `Versioning` section:
- Version `3.4` includes C# 8.0 (Visual Studio 2019 version 16.4, .NET Core 3.1)

**Comment by RikkiGibson** [comment]
Done, thanks!
