### ISSUE TITLE
VS2019 Intellisense keeps suggesting an unused namespace instead of the one I keep using

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40118]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/701626/vs2019-intellisense-keeps-suggesting-an-unused-nam.html)._

---
It really comes down to the fact that I am really frustrated with VS (going back to the dawn of intellisense in the IDE) constantly suggesting "Data" instead of "Diagnostics" after I type "System.D"  I never, ever, ever type out System.Data (I would always, always, always use "using System.Data;" or an aliasing using) and yet I have a double-digit number of System.Diagnostics.Debug(ger) calls in my open windows.  And I am literally typing out Debugger.Launch in several spots, and yet when I'm trying to quickly type out another Launch, the IDE yet again and quite inexplicably suggests "System.Data" as the namespace I want.

---
#### Visual Studio Feedback System on 8/21/2019, 02:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fannie Wang [MSFT] on 8/23/2019, 02:46 AM: 

<p>Hi Richard,<br>
I try it on VS 16.1.6 and record a video:</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/89742-video.mp4">video.mp4</a><br>
Could you please check the above steps?<br>
Does this happen on all projects or the specific one? Could you provide a sample project that can exhibit this behavior?</p>

#### Visual Studio Feedback System on 9/3/2019, 08:13 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Visual Studio Feedback System on 9/6/2019, 00:48 AM: 

<p>Our team is unable to investigate this issue further without the requested information. Please update to the latest version of the product and if the problem still occurs, reply with the requested information. Thank you for sharing feedback on Developer Community.</p>

#### Richard Keith Patrick on 11/22/2019, 08:37 AM: 

It happens on all projects. It&#39;s happening right now on a brand-new workstation, brand-new job, brand-new installation of VS 2019.  Yesterday, I dropped at *least* 10 System.Diagnostics.Debugger.Break() AND Debug.WriteLine, yet sure enough, I&#39;m coding this morning, and doing my usual &quot;s-y-CTRLSPACE-d-CTRLSPACE&quot;, expecting to see &quot;System.Diagnostics&quot;, but instead VS decides for some reason that escapes me that I want &quot;System.Data&quot; instead, even though I have not made a single reference to *anything* in System.Data.  <br>Seriously, can you at least deprecate the term &quot;Intellisense&quot; if the thing is just going to pick the first item out of a list?
#### Visual Studio Feedback System on 11/28/2019, 10:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
