### ISSUE TITLE
CS8620, incorrect generic argument nullability inferred on optional parameter even though it has [AllowNull]

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40110]
**Version Used**: 16.4, not present in 16.3

I would have expected `[AllowNull]` to mean that `T` is inferred as non-nullable. `T` does not need to be nullable in order for `= default` to fit an `[AllowNull] T` parameter.

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

static class Extensions
{
    public static T Foo<T>(this IList<T> p1, [AllowNull] T p2 = default)
    {
        throw new NotImplementedException();
    }

    static void M()
    {
        var instance = new List<object>();

        // CS8620 Argument of type 'List<object>' cannot be used for parameter 'p1' of type
        // 'IList<object?>' in 'object? Extensions.Foo<object?>(IList<object?> p1, object? p2 =
        // null)' due to differences in the nullability of reference types.
        //      ↓
        var x = instance.Foo();
    }
}
```

One workaround is to specify the types explicitly. This causes the text to fade, showing that the explicit type is not needed:

```cs
        // Faded to show as unnecessary
        //                   ↓
        var x = instance.Foo<object>();
```

**Comment by RikkiGibson** [comment]
Tagging @cston

**Comment by sharwell** [comment]
Oh, now this is fascinating. This means we can use a meaningless default parameter to work around the absence of a `where T : defaultable` constraint.

**Comment by sharwell** [comment]
I'm not able to reproduce this. Perhaps the behavior changed?

**Comment by jnm2** [comment]
The repro is the code above. [Here it is on sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4DEAdgK4A2tEwtcABHJY8wLABQvAAgCYAjAIAMLfsIAsAbnGThAOgAimCAHNKAe1iYAxlCUBhbQTgBBDrVxRMUeXx5SAbJMEsAogA94lO9r+vADevCzhkgDMim4AKiwAYtraADyxAHwAFDAAFvYsAJIAMvYwaeksAA7CSCwA2hb02gDuAHJ0tAC6LPGVHgC8LObYEHQwAJRhEaE8EXMsuQgtLJRwzSyt2jAFYJXMYOzwBD76cJUwmIGZ445zAL68U+GuktIsALLXTywz8xFoEAQLEw/hgEEopxYg1W6xKsBS2mAACs4PoYFkbo9Zn8WAB6XEsYwAZQAHC5BBILAgNNQDpQYCxtNgFrhKqwAORwsqIlFo9Lslj6cE6BnAVjUKBwAgsbDaIGVQEQA7wIHs6oCpkstnfOb4ljs4qlBHI1EwAD8/OBlH1PNNZq8vnYAX8SiSqVtaItmUN8I95oq1VqfvtfShOoiepo9HGAoI1FYMG0Qxw2EQ7FOUCtCxyrCjDGAmFomBguEZzIQcFTFYhCdZcCM4fCevmgGTCRssAFA7xQq2wcGnV3Ja63CIPHh3IA=), reproing the warning against master.

**Comment by jcouv** [comment]
No longer seems to [repro](https://sharplab.io/#v2:D4YgdgrgNlCGBGUCmACJYHILAChcAEAmARgIAYV9iAWAbnMuIDoARAS1gHMwB7AZwAubAMZ8mAYR4ATJAEEMUAJ582fenhxUAbJUIoAogA8B6FTzB9cAb1wo7lAMyMdAFRQAxHjwA8LgHwAFAIAFqooAJIAMqoCvn4oAA7EADQoANqyMDwA7gBy0FAAuihuCXoAvCgyAGaw0AIAlLb2Njj27SghAE45KGBI2Si5PALhALYJyGPoJlJGwkgJQuYBDertAL64zXbalNQoALKrOyitHfYAbrBdKGwWArBgCyiV/YPRgt488ABWSMIBIE1ts2hcUAB6CEocQAZQAHFpCBRZF1OBBpmABCgeNVOooEqgAOSfWI/f6AvxElDCJ68bHwVAQPhIKQoao8W4JG6waYmW5EpLU3H4wmndpQlBEqIxb5/AECAD8VLuYCl5IVioMxlMbHMYk8Pg1gOVARlX2NSviSVSlq1ZVe4vsksgMAa1KkEFQAh4VTY1WqSC66AWfFVnWCqFdcHgbCgbAEihxeODgeDz29BKQYiddklHUAyYS5lDXW6GV6qwRPBZMQ2rdb2LY4DZAA===). 
Will have to check
