### ISSUE TITLE
Move instance method 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#40115]
**Steps to Reproduce**:

Ability to move a method from one class to another updating all method invocations and call sites. 

1. Have a keyboard shortcut with an option to `move method`. 
2. Have a dialog similar to move type to namespace with an option to select the destination class. 
![image](https://user-images.githubusercontent.com/46729679/70097930-6d11e100-15df-11ea-82dc-b4bb081da074.png)

3. Click `ok` to apply the refactoring. 

before
```csharp
class C
{
  private int a;
  private void M(B b)
  {
    b.N(a);
  }
}

class B
{
  public void N(int a)
  {
  }
}
```

 

after
```csharp
class C
{
  private int a;
  public int A
  {
    set { a = value; }
    get { return a; }
  }
}

class B
{
  public void N(int a)
  {
  }

  private void M(C c)
  {
    this.N(c.A);
  }
}

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
