### ISSUE TITLE
Suggested name for class properties now in lowercase

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40119]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/747563/suggested-name-for-class-properties-now-in-lowerca.html)._

---
[regression] [worked-in:16.2.*]
If I trying to create new class property for example

```
public List<SomeEntity> ...
```
In previous version of Visual Studio 2019 I have suggested name in uppercase like SomeEntities
Now it looks like in lowercase and suggested type is field not property.

If I using _prop_ snippet I have same result.

I tried to disable IntelliCode extension, but I have the same behavior.
For methods suggested name looks as expected.

Please see screnshots.

---
#### Visual Studio Feedback System on 9/25/2019, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 10/9/2019, 03:42 PM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Please provide more details that could help us understand/repro this issue. Do you have an editor config file? If you do, please share the editor config.</p>

#### Visual Studio Feedback System on 10/15/2019, 08:26 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### sv.volkoff on 11/23/2019, 00:59 PM: 

<p>Still have the same issue with latest version of VS 2019 Pro.</p><p>Reproduced in all projects and solutions, .editorconfig used in some projects.</p>

#### Игорь on 11/23/2019, 02:06 PM: 

<p>I also have a problem. Visual Studio 2019 does not suggest property names. I haven't an editor config file. The problem started to occur after installation Visual Studio 2017 version 15.9.7. Reinstallation Visual Studio 2019 does not help<br></p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/106527-94735-vs-2019-does-not-suggest-a-property-name.jpg"></p>

#### Visual Studio Feedback System on 11/25/2019, 09:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Jane Wu [MSFT] solved on 10/23/2019, 08:27 PM, 0 votes: 

Our team is unable to investigate this issue further without the requested information. Please update to the latest version of the product and if the problem still occurs, reply with the requested information. Thank you for sharing feedback on Developer Community.

#### Игорь on 11/15/2019, 02:21 PM: 

<p>I also have a problem. Visual Studio 2019 does not suggest property names. I haven't an editor config file. The problem started to occur after installation Visual Studio 2017 version 15.9.7. Reinstallation Visual Studio 2019 does not help</p>

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The customer may have some editorconfig setting that changed this.
