### ISSUE TITLE
Consider folding '#region' on 'Collapse to Definitions'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40122]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/823022/ctrlmctrlo.html)._

---
Ctrl+M，Ctrl+O
Maybe we should also fold the #region

---
#### Visual Studio Feedback System on 11/17/2019, 10:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This has an option:

![Image](https://github.com/user-attachments/assets/8f598887-84b8-4077-b1d7-f5cfa8880d3f)

**Comment by Montago** [comment]
Why is this closed ? 

the feature worked perfectly before someone "fixed" it ... 

Fold the #Regions when we say so !

**Comment by CyrusNajmabadi** [comment]
@Montago see post above yours

**Comment by Montago** [comment]
> [@Montago](https://github.com/Montago) see post above yours

Something broke in my Visual Studio 2022 after upgrading to 17.12.4. 

Regions are not folding - actually they expand when i press CTRL+M + O

I've checked that the checkbox IS CHECKED - i've also tried unchecking, save and close, then come back and check it again and it didnt fix the issue with regions not folding.

**Comment by CyrusNajmabadi** [comment]
@Montago please open a new issue then as that is a different problem than the fixed issue here.
