### ISSUE TITLE
C# Interactive tool window does not have an icon

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/823243/new-find-in-files-has-no-icon.html)._

---
<p>[regression] [worked-in:pre-16.4]<br>
Many of the new tool windows continuously miss window icons.</p><p>While these are not visible most of the time, if you have narrow enough tool window tabs in dock panels, <strong>icons are displayed instead of text</strong>. Without icons assigned to the tool windows, <strong>those tabs stay completely empty</strong>.</p><p>Windows affected by this and suggested fix:</p><p>- C# Interactive - menu item has an icon, add this to the window.<br>- new &quot;Find in Files&quot; preview 16.4 - add the magnification glass from the previous tool window<br>- possibly more which I do not use in such narrow space (I remember this was a common oversight throughout recent releases).</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/105283-annotation-2019-11-16-195053.png"> Image:105283-annotation-2019-11-16-195053.png</a></p>

---
#### Visual Studio Feedback System on 11/18/2019, 00:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
Note: not a regression , same behavior is seen in dev15

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback/impact.
