### ISSUE TITLE
Code Folding doesn't work for if/else etc. in C# without the optional curly brackers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40126]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/824336/code-folding-doesnt-work-for-ifelse-etc-in-c-witho.html)._

---
[regression] [worked-in:2017]
I think in VS2017 I could have folding in C# code like the following where curly brackers aren't being used. This doesn't seem to work in VS2019, nor do the vertical folding lines appear (that show nesting level of code), they only seem to connect curly brackets too. 

This is unexpected from an IDE's code editor backed by Roslyn, and is only expected to occur in naive-parsing generic text editors like Notepad++. 

The first thing I do when refactoring deeply nested code I've inherited is to remove the curly brackets that are not needed since they make the code more convoluted/unreadable. The current naive code folding in VS2019 seems to punish me and tries to enforce putting curly brackets everywhere, since without code folding I can navigate and refactor long code listings much harder

```
using System;

public class Class1
{
	public Class1()
	{
        if (condition1 &&
            condition2 &&
            condition3)
            doSomething();
        else
            if (someothercondition)
                doSomethingElse();
            else
                doOther();
	}
}
```

---
#### Visual Studio Feedback System on 11/19/2019, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
