### ISSUE TITLE
Output Window Warning Links to the Wrong File

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40121]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/820419/output-window-warning-links-to-the-wrong-file.html)._

---
# Setup
Visual Studio 2019 version 16.4.0 preview 4.0
I have two almost identical files in my solution. They are in two different projects a core and a .net Framework.
The only difference between the files is that I have added a ? after string in the Core version of the file which creates a warning because I haven't enable the nullable annotation.

When compiling I get the expected warning in the output window:
1>Program.cs(9,19,9,20): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

When I double click the warning it takes me to the file in the .NET framework project which doesn't have the issue. It should have taken me to the Core version of the file where the warning belongs to.

If I go to the Error List window and double click the same warning then it is taking me to the right file.

---
#### Visual Studio Feedback System on 11/14/2019, 11:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
Closing this issue, as it's not a Roslyn issue. The feedback item will be the primary tracking again.
