### ISSUE TITLE
How can I remove unnecessary UsingCode?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#40155]
**Version Used**: 

Microsoft.Net.Compilers3.4.0
Microsoft.CodeAnalysis.CSharp.Workspaces3.4.0

**Steps to Reproduce**:

1. I used "DependencyContext.Default.GetDefaultAssemblyNames();" to get all namespace;
2. I built a string.
3. Compile it using the “CSharpCompilation.Emit method”.

**Expected Behavior**:
using System;
using UT.Model;
**Actual Behavior**:
![image](https://user-images.githubusercontent.com/16236903/70205884-9dcd5400-1760-11ea-9c4f-5374131dbbca.png)

If I use string compilation,  I have to refer to the namespace accurately. can I get rid of useless references?

**Comment by CyrusNajmabadi** [comment]
Get diagnostics from the compilation instance and filter for those with ID="CS8019".  These will let you know all the usings that aren't necessary.

**Comment by NMSAzulX** [comment]
@CyrusNajmabadi  Thank you!  And I got lots of errors with ID="CS0234".   Like: "FxResources" and "System.Numerics.Hashing". 

How do I filter these useless assemblies?
![image](https://user-images.githubusercontent.com/16236903/70210533-e5a6a800-176d-11ea-8be9-99a0ae53b14c.png)

**Comment by NMSAzulX** [comment]
@CyrusNajmabadi  
I used this:  
var types = assembly.ExportedTypes;  
Cannot find this class “LightLambda” .
Cannot find namespace : "System.Linq.Expressions.Interpreter". 

And Now I solved it with removing them from sets.
`
            DefaultNamesapce.Remove("System.Linq.Expressions.Interpreter");
            DefaultNamesapce.Remove("System.Net.Internals");
            DefaultNamesapce.Remove("System.Xml.Xsl.Runtime");
`
There's no better way.

**Comment by CyrusNajmabadi** [comment]
> How do I filter these useless assemblies?

Well, you could just look for those particular diagnostics you're getting.

**Comment by NMSAzulX** [comment]
@CyrusNajmabadi  I had to add  "CSXXXHelper" to deal those error: CS0234 \ CS0246,  Thanks.

https://github.com/dotnetcore/Natasha/blob/master/src/Natasha/Core/Engine/ComplierModule/Utils/CS0234Helper.cs
