### ISSUE TITLE
IDE: Repeat key broken in overwrite mode

### ISSUE THREAD

**Issue by ronnygunawan** [dotnet/roslyn#40156]
**Version Used**: 16.5.0 Preview 1.0

**Steps to Reproduce**:

1. Open a large solution (important. I can't repro this issue in small solution)
2. Write a long line
```cs
var s = "The quick brown fox jumps over the lazy dog";
```
3. Press <kbd>Insert</kbd> to switch to `OVR` mode
4. Put cursor at the beginning of the line, then hold spacebar

**Expected Behavior**:
All characters overwritten by spaces

**Actual Behavior**:
Only half of the characters were overwritten, it skips one character after each space:
```cs
// before and after
var s = "The quick brown fox jumps over the lazy dog";
 a       T e q i k b o n f x j m s o e   h   a y d g ;
```

**Comment by dpoeschl** [comment]
> (important. I can't repro this issue in small solution)

I can repro this in a default console app.

**Comment by dpoeschl** [comment]
This doesn't seem to repro in non-Roslyn languages, so perhaps it really is a Roslyn problem (and not an Editor bug)...

**Comment by dpoeschl** [comment]
The result is different every time, but here's an example:

![OverwriteBug](https://user-images.githubusercontent.com/235241/70570844-88d23580-1b51-11ea-80b7-21a13fb21810.gif)

**Comment by dpoeschl** [comment]
@ronnygunawan How frequently is this impacting you? Is it something you do a lot, or did you just stumble on it once but expect it to not be a common action you take?

@olegtk Any ideas on how to diagnose this? Have you ever seen something similar?

**Comment by olegtk** [comment]
wow, never seen anything like this. I can repro it on C# console app on 16.4, but only in cs file, not in App.config. Debugging...

**Comment by olegtk** [comment]
Got it, please route the bug to the editor, @jinujoseph

**Comment by ronnygunawan** [comment]
@dpoeschl it's not really a common action that I take. I only do this when writing a console app with `Console.Write("\r........`.

**Comment by jinujoseph** [comment]
@olegtk routed [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036149)

**Comment by AmadeusW** [comment]
This has been fixed in VS-Platform/pullrequest/218467
Thank you for bringing this up to our attention!
