### ISSUE TITLE
Failing C# REPL integration tests on 16.4 Preview 5

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#40160]
With the integration VM image updated to dev16.4 Preview 5 there are now 22 consistently failing C# REPL unit tests.

- [x] Skip REPL Tests (https://github.com/dotnet/roslyn/pull/40161)
- [ ] Fix underlying issues

**Comment by lameox** [comment]
Judging by [this](https://dev.azure.com/dnceng/public/_build/results?buildId=460013&view=results) and [this](https://dev.azure.com/dnceng/public/_build/results?buildId=460141&view=ms.vss-test-web.build-test-results-tab) test run - which are functionally equivalent code - it seems that `Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.VerifyExecuteInput()` is flakey.

**Comment by CyrusNajmabadi** [comment]
Stupendous!
