### ISSUE TITLE
Intellisense suggests incorrect capitalization for method parameters of types that begin with two-letter acronyms

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40170]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/834783/intellisense-suggests-incorrect-capitalization-for.html)._

---
When typing the name of a method parameter of a type that begins with a two-letter acronym, Intellisense will suggest the incorrect capitalization for the first two letters. For example, if the parameter is of type IOStream then Intellisense will incorrectly suggest "iOStream" instead of the correct capitalization "ioStream". This conflicts with the Capitalization Conventions outlined here: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions.

---
#### Visual Studio Feedback System on 11/27/2019, 00:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
