### ISSUE TITLE
Not useful quick fix for inacessible to protection level error 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40171]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/834881/not-useful-quick-fix-for-inacessible-to-protection.html)._

---
VS tells me that I can't call a method because of its protection level but there's no related quick fox for that (like making the method public)

---
#### Visual Studio Feedback System on 11/27/2019, 01:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
