### ISSUE TITLE
More 'depth-first' initializing of implicit constructors.

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/roslyn#40174]
**Version Used**: 
Whatever version is currently on try.dot.net -- I think that's the latest

**Steps to Reproduce**:
1. Create a static class with static properties -- I haven't found a way to replicate this with a non-static property because you can't use an accessor in a non-static property in-line initializer.
2. Make sure that the first static property calls an accessor of the second static property within the initializer.
3. When you attempt to call the first Static Property, you'll be met with a null reference exception.
4. When you reverse the order of the properties, it will work fine.

Here's a simple use case to see it in action. 
```csharp    
private class MyTestClass
{
    public static int FirstArrayEntry {get;} = MyList[0];
    private static IList<int> MyList {get;} = new List<int> {1};
}
```

Here's a better representation of the actual use-case which triggered us to find this bug:
```csharp    
private class MyTestClass
  {
    public static IDictionary<int,string> MyDictionary {get;} = PerformSomeOperationToReceiveDictionary();
    private static Lazy<bool> CheckIfIShouldAddOtherThingsToDictionary {get;} = new Lazy<bool>(PerformDatabaseOperationToGetMyValue);

    private static IDictionary<int,string> PerformSomeOperationToReceiveDictionary() {
      var dictionary = new Dictionary<int,string>();
      dictionary.Add(0,"Some data has been added");

      if (CheckIfIShouldAddOtherThingsToDictionary.Value) {
        dictionary.Add(1,"I am now adding other data");
      }
      return dictionary;
    }

    private static bool PerformDatabaseOperationToGetMyValue() {
      //using(myDB) {
        return true;
      //}
    }
}
```

If you create an explicit static constructor and attempt to initialize the values in the same order, it becomes very clear why this behavior occurs. However, it becomes much more difficult to diagnose when you rely on the implicit constructor. Add to that the fact that Static Code Analyzers will tell you that your code is incorrectly ordered, and will tell you to change the order to align it with an ideal. It makes for a confusing experience.

**Expected Behavior**:
I expect to be able to change the order of any of my fields, properties, methods, etc, and have the code work just the same. 

**Actual Behavior**:
The order of in-line initializers determines the order of code executed in the implicit constructor and defines the order in which the properties, fields, methods must be declared in a file.

**Comment by CyrusNajmabadi** [comment]
> I expect to be able to change the order of any of my fields, properties, methods, etc, and have the code work just the same.

This would be a breaking change to the language.

**Comment by EdLichtman** [comment]
Just for clarification, I don't mean that I expect to be able to change the order of operation within a function. the order of operation within a function is the natural order of things. but when we have such a strongly-opinionated community driving the order in which we include each property, method and field in the file, then I don't believe the order in which we include them should determine if the code gets a null reference upon initializing an object property.

In the example I gave above, fields, properties, methods, etc should always be ordered with public at the top, private at the bottom, and split into sections, with fields, followed by constructor, followed by properties, followed by methods I believe -- at least, that's one school of thought,

So by imposing this ordering it means that in that example we would have to put a public property below a private property, and thus go against the preferred ordering of a file.

The way we solved this was by making the Lazy Initialized Value a field, which goes above public properties, and that works, so perhaps instead of using depth-first to initialize the property, could it possibly use static analysis to give a compiler warning?

**Comment by CyrusNajmabadi** [comment]
> So by imposing this ordering it means that in that example we would have to put a public property below a private property, and thus go against the preferred ordering of a file.

That's your own preferred ordering.  It's up to you to decide what the right thing is to do when that ordering impacts flow of execution.

> could it possibly use static analysis to give a compiler warning?

Yes.  You can use Roslyn's analyzer framework to analyze and report back deviations with your particular coding style choices.

**Comment by RikkiGibson** [comment]
In case anyone else was curious about the version in use:

<img width="575" alt="Screen Shot 2019-12-05 at 1 10 32 PM" src="https://user-images.githubusercontent.com/5833655/70274355-dd943b80-1760-11ea-9869-62bac8818661.png">

**Comment by EdLichtman** [comment]
> 
> 
> > So by imposing this ordering it means that in that example we would have to put a public property below a private property, and thus go against the preferred ordering of a file.
> 
> That's your own preferred ordering. It's up to you to decide what the right thing is to do when that ordering impacts flow of execution.
> 
> > could it possibly use static analysis to give a compiler warning?
> 
> Yes. You can use Roslyn's analyzer framework to analyze and report back deviations with your particular coding style choices.

So are you saying that there is already a feature in Roslyn to turn on that will say "Accessing a variable before it's declared may result in a null reference" or something of that sort, when specifically pertaining to in-line static field initialization?

**Comment by CyrusNajmabadi** [comment]
> So are you saying that there is already a feature in Roslyn to turn on that will say "Accessing a variable before it's declared may result in a null reference" or something of that sort, when specifically pertaining to in-line static field initialization?

Yes.  Look at https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019 .  Note: you may have to write your own analyzer here to catch this sort of issue.

**Comment by EdLichtman** [comment]
> 
> 
> > So are you saying that there is already a feature in Roslyn to turn on that will say "Accessing a variable before it's declared may result in a null reference" or something of that sort, when specifically pertaining to in-line static field initialization?
> 
> Yes. Look at https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019 . Note: you may have to write your own analyzer here to catch this sort of issue.

Ohhh,.. Neat! If I end up needing to write my own analyzer to catch that issue, is there a way to contribute that for other people to use?

**Comment by RikkiGibson** [comment]
I could see us warning on this pattern in a warning wave, but it could be a long time before that gets done.

There are community projects out there which distribute sets of useful analyzers. [Roslynator](https://github.com/JosefPihrt/Roslynator) is one. You might be able to interest them in your analyzer idea and contribute it to them.

**Comment by EdLichtman** [comment]
I appreciate that! I'll look to do that with Roslynator. should I keep this open as a one day might be useful thing, or just close it?

**Comment by gafter** [comment]
This would be a breaking change compared to the [current language-specified behavior](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#static-field-initialization):

> The static field variable initializers of a class correspond to a sequence of assignments that are executed **in the textual order in which they appear in the class declaration**.  ...

Emphasis mine.  Since this would require a language change, it would have to be specified in `csharplang` before we would consider making a change in the Roslyn compiler.
