### ISSUE TITLE
Update whitelist of analyzer dependencies to include Microsoft.VisualBasic.dll

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#4017]

**Comment by heejaechang** [comment]
@jmarolf can you give me a bit more info what do you want? why only MS.VB.dll how about MS.CSharp.dll?

**Comment by jmarolf** [comment]
I can investigate MS.CSharp.dll, but I know that today Microsoft.VisualBasic.dll is listed as a dependency in all VB analyzers so we need to add it to the white-list if we don't want warning to pop up when VB analyzers are loaded.  VB templates have workaround for this that I would like to remove.
