### ISSUE TITLE
Fragile logic in classification of Stackalloc conversion

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#40197]
```
        public override Conversion GetStackAllocConversion(BoundStackAllocArrayCreation sourceExpression, TypeSymbol destination, ref HashSet<DiagnosticInfo> useSiteDiagnostics)
        {
            if (sourceExpression.Syntax.IsLocalVariableDeclarationInitializationForPointerStackalloc())
            {
```

We should not be checking syntax here, all required information should be available from bound nodes.

**Comment by gafter** [comment]
I don't understand this issue.  The conversion being applied here depends on the syntactic context in which the expression appears in source.  Bound expressions encapsulate the analysis of syntax, generally in isolation from the enclosing syntax, and we use "target typing" to take that context into account.  This is a singular place in the language that the syntactic context makes a difference.  This conversion only occurs during binding, when we are supposed to be accessing the syntax.

If you think it would be better to place a boolean flag in the `BoundStackAllocArrayCreation` bound node - we could do that, but the logic for initializing it would be exactly the same.

**Comment by AlekseyTs** [comment]
> If you think it would be better to place a boolean flag in the BoundStackAllocArrayCreation bound node - we could do that, but the logic for initializing it would be exactly the same.

I think that would be the right thing to do. During our offline conversation, we agreed that it would be good to follow a principle that a Syntax node associated with a Bound node should not carry a semantics meaning.

**Comment by gafter** [comment]
See also https://github.com/dotnet/csharplang/pull/3010
