### ISSUE TITLE
Visual Studio 2019 intellisense doesn't work on projects created with VS 2017

### ISSUE THREAD

**Issue by dsajanice** [dotnet/roslyn#40192]
**Version Used**: Visual Studio 2017 and Visual Studio 2019

**Steps to Reproduce**:

1. Create a project with a simple class in Visual Studio 2017
2. Open the project with Visual Studio 2019
3. Add a simple class which say inherits from IDisposable in VS 2019. Observe the lack of intellisense support to implement the dispose pattern on the class.

**Expected Behavior**:
VS 2019 intellisense should work on older projects created with VS 2017.

**Actual Behavior**:
Intellisense in VS 2019 doesn't work as expected on projects created in VS 2017.

**Comment by dpoeschl** [comment]
Hi @dsajanice, thanks for the bug report. I'm having trouble understanding exactly what's wrong / reproducing the failure. 

For example, I made a C# .NET Framework Console App in VS2017, and then open it in VS2019. I get a working completion list when I go to make `Program` implement `IDisposable`, and then I get the lightbulb to show up with all the choices to implement dispose. 

Does it only happen with a particular kind of application? What precisely isn't working (completion list, lightbulb, etc.)? Is there any other information you can provide?

Thanks!
