### ISSUE TITLE
The Simplifier fails to simplify

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#40201]
This is a case that the Simplifier should have been able handle.

![image](https://user-images.githubusercontent.com/611219/70338947-b5f5af80-1802-11ea-9b88-61811c47c1a2.png)

Because it handles it when the unused `typeSymbol` variable name is changed to a discard.

![image](https://user-images.githubusercontent.com/611219/70338929-ad9d7480-1802-11ea-830b-66971ea8da87.png)

Or when it is removed entirely.

![image](https://user-images.githubusercontent.com/611219/70338909-a4aca300-1802-11ea-8a62-b1c6dc62c8df.png)

**Comment by JoeRobich** [comment]
To repro:
1, open Roslyn.sln
2. open PreferFrameworkTypeDiagnosticAnalyzerBase.cs
3. Inline `cancellationToken` in the `AnalyzeNode` method.

**Comment by dpoeschl** [comment]
More simplified standalone repro:

```C#
using System.Threading;

class C
{
    void Test()
    {
        var ct = CancellationToken.None; // Inline `ct`
        if (!(Helper(ct) is string notDiscard))
        {
            
        }
    }

    object Helper(CancellationToken ct) { return null; }
}
```

**Comment by CyrusNajmabadi** [comment]
Is it the presence of the pattern?

**Comment by dpoeschl** [comment]
I’d have to double check, but I believe I saw that the condition negation was significant too...

**Comment by dpoeschl** [comment]
We've had other possible reports of similar issues from @RikkiGibson and @davkean. Feel free to add more repros here.

**Comment by dpoeschl** [comment]
Updating with findings so far. I think this is a compiler issue. When we finally get down to this point:

https://github.com/dotnet/roslyn/blob/ae013d6bbfa5f9c63581c38f079dd4bff98b8c4a/src/Workspaces/Core/Portable/Utilities/AbstractSpeculationAnalyzer.cs#L201-L209

`newTypeInfo` correctly comes back as bool for (a complexified version of) `!(Helper(ct) is string _)`, but as ErrorType for (a complexified version of) `!(Helper(ct) is string notDiscard)`

**Comment by RikkiGibson** [comment]
Could you show what the complexified version of that looks like?

**Comment by dpoeschl** [comment]
@RikkiGibson I updated the [post above](https://github.com/dotnet/roslyn/issues/40201#issuecomment-564318019) with more info.

**Comment by dpoeschl** [comment]
@jaredpar Can someone from the compiler team help with this? I'm down into 
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs#L1425-L1430
and the _guardedNodeMap has precomputed that the `IsPattern` in [the repro](https://github.com/dotnet/roslyn/issues/40201#issuecomment-564318019) has type `bool`, but the surrounding PrefixUnary negation of that has Error Type. Having trouble debugging where that is all predetermined.

**Comment by jaredpar** [comment]
@333fred can help with that.
