### ISSUE TITLE
intellisense explicit cast vs dot

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/594082/intellisense-explicit-cast-vs-dot.html)._

---
<p>Example:</p>
<p>var r = new Random();<br>
<code>(int)r.</code><strong>&lt;cursor&gt;.Next();</strong></p>
<p>Upon typing the “.” above.<br>
<strong>Expected</strong>: show intellisense options for Random<br>
I would continue to type:<br>
<code>(int)r.GetDouble();</code></p>
<p><strong>Actual</strong>: r is streated as an int, giving intellisense options for int.</p>
<p>Since the dot has higher precedense than the cast it should also apply to intellisense.</p>

---
#### Visual Studio Feedback System on 6/4/2019, 02:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 6/4/2019, 01:29 PM: 

<p>Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Please provide more details that could help us understand/repro this issue. If possible please provide a sample project where this issue is occurring.</p>

#### Peter on 6/4/2019, 10:54 PM: 

<p>I'm sorry I made an assumption about the scope of the bug.</p><p>Correct description follows:</p><p>1. Type the full line of code.</p><p>var x = (int)r.PropertyA();</p><p>2. Place cursor after the "r" and press "." (leaving the code after it intact)</p><p>Screencast: <a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/76933-2019-06-05-07-52-35.mp4">2019-06-05-07-52-35.mp4</a></p>

#### Visual Studio Feedback System on 11/12/2019, 05:06 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Ivan Basov [MSFT] on 11/13/2019, 00:39 PM: 

<p>Thank you for your feedback!</p>
<p>I have tried to reproduce the issue with latest version of Visual Studio. And it works fine for me. We realized that the issue could happen with version 16.1 mentioned in feedback logs. Sorry for inconveniences! Could you please update to the latest bits? Please let us know if it helps or not.</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/104650-untitled.png"></p>

#### Peter on 11/15/2019, 06:20 AM: 

<p>I've updated the first post to match the conversation.</p>
<p>This is in Visual Studio 16.3.9.</p><p>1. as expected</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/105108-2019-11-15-15-17-15.jpg"></p><p>2. As expected</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/105109-2019-11-15-15-15-58.jpg"></p><p>3. Giving suggestions for int rather than Random.</p><p>Expected the same drop-down as in 1 and 2</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/105110-2019-11-15-15-11-27.jpg"></p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/4564579/219785868-32b8c9ec-c4ea-4fb8-b727-210357b736df.png)
