### ISSUE TITLE
.NET compiler produces incorrect string constants in MSIL when C# source files encoded with non-UTF-8 encoding

### ISSUE THREAD

**Issue by NSentinel** [dotnet/roslyn#4022]
.NET compiler produces incorrect string constants in MSIL (as compared to previous version,  even to VS 2015 RC)  when C# source files encoded with non-UTF-8 encoding (e.g. UTF-8 without BOM or windows-1251 (Russian)) and contains string constants in international language (e.g. Russian text). The source text file encoding seems not respected anymore and treated as ASCII when encoding is not UTF-8. 

The similar issue also has resource compiler (*.resx) result in generating incorrect source file.

The issue appears after a transition from VS 2015 RC to VS 2015. VS 2015 RC works as expected.

Visual Studio info:

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

OS info:

Microsoft Windows 10 Pro /  Version 10.0.10240 Build 10240

**Steps to reproduce the issue:**

Create console project with following source file in windows-1251 encoding and compile it.

```C#
using System;

namespace EncodingTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string test = "Тестовая строка";
            Console.WriteLine(test);
        }
    }
}
```

[Ready to use solution] (https://connect.microsoft.com/VisualStudio/Feedback/DownloadFile?downloadLink=2110cc92-d654-4d3e-8f44-050700a428f4%3BEncodingTest.zip)

**Expected results:**

```C# 
.method private hidebysig static void Main(string[] args) cil managed
{
    .entrypoint
    .maxstack 1
    .locals init (
        [0] string str)
    L_0000: nop 
    L_0001: ldstr "\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0441\u0442\u0440\u043e\u043a\u0430"
    L_0006: stloc.0 
    L_0007: ldloc.0 
    L_0008: call void [mscorlib]System.Console::WriteLine(string)
    L_000d: nop 
    L_000e: ret 
}
```
To emphasize:

```C# 
L_0001: ldstr "\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0441\u0442\u0440\u043e\u043a\u0430"
```

**Actual results:**

```C#
.method private hidebysig static void Main(string[] args) cil managed
{
    .entrypoint
    .maxstack 1
    .locals init (
        [0] string str)
    L_0000: nop 
    L_0001: ldstr "\u00d2\u00e5\u00f1\u00f2\u00ee\u00e2\u00e0\u00ff \u00f1\u00f2\u00f0\u00ee\u00ea\u00e0"
    L_0006: stloc.0 
    L_0007: ldloc.0 
    L_0008: call void [mscorlib]System.Console::WriteLine(string)
    L_000d: nop 
    L_000e: ret 
}
```

To emphasize:
```C#
L_0001: ldstr "\u00d2\u00e5\u00f1\u00f2\u00ee\u00e2\u00e0\u00ff \u00f1\u00f2\u00f0\u00ee\u00ea\u00e0"
```

[Microsoft Connect Entry] (https://connect.microsoft.com/VisualStudio/feedback/details/1571354/net-compiler-produces-incorrect-string-constants-in-msil-when-c-source-files-encoded-with-non-utf-8-encoding)

**Comment by 13xforever** [comment]
Considering that this potentially touches everyone with non-windows1252 ansi codepage, I'm surprised this issue deemed to be less severe than RyuJIT bugs that are going around.

This should be a hotfix, and not slated for 1.1 update.

**Comment by jaredpar** [comment]
Looks like another occurrence of #4264

@13xforever the milestone is primarily tracking what official release this fix will be a part of.  We publish daily builds of the compiler toolset to [myget](https://www.myget.org/gallery/roslyn-nightly) and a toolset build every three weeks to nuget.org.  These allow us to hot patch the compiler as early as a day after the fix is submitted to Github.  

Note: As a short term work around you can explicitly specify the code page in the project settings using the CodePage element in the csproj file:

``` xml
<CodePage>1251</CodePage>
```

**Comment by 13xforever** [comment]
I can fix one project, but we have source build system, with dozens and dozens of dependencies, it is much easier to force older msbuild tools usage.

**Comment by Pilchie** [comment]
You can also run msbuild with the `/p:CodePage=1251` command line option when building on the command line, or set the environment variable `CodePage` to `1251` for VS to pick it up as well.

**Comment by NSentinel** [comment]
Thanks for all suggestions. 

As for me, I've just made simple tool to parse thru all my sources, detect encoding (via [Detect File Encoding using Mozilla Charset Detector (UDE.CSharp)] (https://www.nuget.org/packages/SimpleHelpers.FileEncoding) thanks to *Khalid Salomão* for simplification this task) and converts them to UTF-8 when needed.

**Comment by miloush** [comment]
It is quite frustrating to work under source control with clients using different code pages. There should be an option to always save files as UTF-8 (if not the default), or the _Save documents as Unicode when data cannot be saved in codepage_ option should use Unicode if data cannot be saved in ASCII.

**Comment by KoHHeKT** [comment]
@miloush Such option exists Tools - Options - Environment - Documents - Save Document as Unicode if cannot be saved in Codepage. But, unfortunately, it is disabled by default.

**Comment by KoHHeKT** [comment]
@NSentinel could you share your tool? I think, it will be popular.

**Comment by cnblogs-dudu** [comment]
Same issue in #4222 and #4255.

**Comment by NSentinel** [comment]
@KoHHeKT I've published [tool source](https://github.com/NSentinel/EncodingMixToUtf8). Hope it helps!

**Comment by AlekseyTs** [comment]
@NSentinel Could you please verify if #4303 fixed the issue?

**Comment by AlekseyTs** [comment]
@jaredpar Please verify

**Comment by NSentinel** [comment]
@AlekseyTs Sorry for a long delay. Seems bug was fixed at least for my case.
