### ISSUE TITLE
There's a bug in map mode scroll bar when there's collapse

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#40224]
**Version Used**: 16.4
When I collapse some code, scroll bar is like the follow picture:
Whatever I drag gray area or white area, the code window deosn't move view in the first few seconds, then it can move, but my mouse cursor isn't on the top of scroll bar.

![image](https://user-images.githubusercontent.com/2529999/70371381-3274b500-190d-11ea-97fc-cbcc59c7d0c5.png)

![image](https://user-images.githubusercontent.com/2529999/70371461-42d95f80-190e-11ea-9c1b-1f4c1459e810.png)

**Comment by CreateAndInject** [comment]
When I drag the scroll bar from top to bottom, everytime the scroll bar meet the gray area(collapse flag), it will stop about 1 second and continue move.

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by olegtk** [comment]
We would need traces to investigate this, I cannot reproduce it off hand.

**Comment by CreateAndInject** [comment]
[ClassLibrary1.zip](https://github.com/dotnet/roslyn/files/3949870/ClassLibrary1.zip)

Open the above solution, expand `Class1` and `Class3`, collapse `Class2`, make sure what you see is like the following screenshot.
Press Mouse Left in the position 1/2 as the screenshot, and move up slowly, you will find the scrollbar doesn't follow the mouse cursor in a few seconds, after a few seconds, the scrollbar can move.

![image](https://user-images.githubusercontent.com/2529999/70614759-10996c00-1c46-11ea-907e-ffab00d6d819.png)

**Comment by olegtk** [comment]
I see. Yes, I can repro it. It seems like drag operation gives no visible feedback while mouse is over collapsed region.
@jinujoseph, please route this to the editor. Thanks!

**Comment by jinujoseph** [comment]
Routed [here ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036177)

**Comment by CreateAndInject** [comment]
@olegtk @jinujoseph Why can't I view your link [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036177) even if I log in my own account.

**Comment by jinujoseph** [comment]
@CreateAndInject it's tracked in internal store so don't think you have access to.
you can file an issue at https://developercommunity.visualstudio.com/ so you can track status or continue to ping @olegtk  here
