### ISSUE TITLE
when using an "is type pattern expression" the new variable is defined in the outer scope

### ISSUE THREAD

**Issue by mauriziodepascale** [dotnet/roslyn#40231]
**Version Used**: 
.NET core 3 project in VS2019

**Steps to Reproduce**:

1. compile the following snippet:
public static void Main()
{
	object x = "not an int";
	if (x is int y)
	{
		//y should be defined only in this scope
	}
	y = 1; //no error here, looks like y is being defined in the outer scope
}

**Expected Behavior**:
compiler error 

**Actual Behavior**:
no compiler error

**Comment by CyrusNajmabadi** [comment]
This is by design.  It's exactly how the language is specified to work.
