### ISSUE TITLE
go-to dying repeatedly in latest VS.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40235]
I'm using 

![image](https://user-images.githubusercontent.com/4564579/70381333-339de600-18fd-11ea-8449-b4ce1069949c.png)

After only a few minutes of editing i consistently get into the state where 'go to' is totally broken and returns no values:

![image](https://user-images.githubusercontent.com/4564579/70381335-44e6f280-18fd-11ea-8d64-ce8e5ca09474.png)

I believe @jnm2 is also running into this.

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph

**Comment by CyrusNajmabadi** [comment]
tagging @sharwell  @mavasani  as well.

**Comment by jnm2** [comment]
Ctrl+T is causing 16.5-p1 to freeze a few times per hour in the Roslyn solution. Some F2 renames  seem to have the same effect.

It sometimes unfreezes after five minutes of me using a second VS instance while waiting for it. Other times, Windows brings up the Restart/Close/Wait dialog and I close it.

**Comment by CyrusNajmabadi** [comment]
I'm seeing similar behavior.  Other behavior i've noticed is that when i try to navigate to a 'go to' result that the VS UI will hang for sometimes up to 20-30 seconds.  It *sometimes* comes back, but other times it just is totally hung.

I can't seem to get any debugging information to narrow this down.  I'm hoping this is just a single regression that just happens to be hitting a few core scenarios.

is it possible to rollback to 16.4 p5 or anything like that?  @sharwell ?

**Comment by jnm2** [comment]
@CyrusNajmabadi why roll back to a 16.4 preview when you can run 16.4?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi why roll back to a 16.4 preview when you can run 16.4?

Does roslyn work with 16.4?  it also means losing all the fixes/improvements in all the preview releases.  I basically just want to move back 1 minor step, not a major step.

**Comment by jnm2** [comment]
Roslyn works with 16.4 for me. The smallest step back from 16.5-p1 that you can take is to go to 16.4 release, right? 16.4-p5 would be stepping even further back.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  I mean: 16.5 preview x then. :)

**Comment by jinujoseph** [comment]
@olegtk  for info

**Comment by olegtk** [comment]
There was a related UI delay bug intropduced in 16.5 Preview1, fixed in Preview2. Are there any traces of the delay to confirm it?
@veler FYI

**Comment by veler** [comment]
Hello, this isn't related to what I fixed recently. However I recently reported an issue with Open Folder.
@CyrusNajmabadi , by any chance, did you open a large folder in Visual Studio, or a solution?
Also, if you use the new Find in Files (Tools>Options>Preview Features, uncheck Use previous Find in Files), do you succeed to search everything? Do you also succeed to find files or symbols in Visual Studio Search (Ctrl+Q) ?

**Comment by CyrusNajmabadi** [comment]
> by any chance, did you open a large folder in Visual Studio, or a solution?

Yes.  I am working in Roslyn.sln which is quite large.

> Do you also succeed to find files or symbols in Visual Studio Search (Ctrl+Q) ?

No, it also fails.

> Also, if you use the new Find in Files (Tools>Options>Preview Features, uncheck Use previous Find in Files), do you succeed to search everything?

Yes, finding in files works fine.

**Comment by veler** [comment]
Sounds good, thank you. Here are some additional steps to try to figure out what's going on.
Can you please :
1. Restart VS and Open the folder.
2. Take a look at the background tasks in the bottom-left of the UI

You should expect to see first a "File indexing" task.
![image](https://user-images.githubusercontent.com/3747805/70464217-4fc39380-1a73-11ea-848a-2bb1f28ece06.png)

Then a "Scanning data" one that successfully goes to 100%.
![image](https://user-images.githubusercontent.com/3747805/70464283-72ee4300-1a73-11ea-8e14-e09eaf278e0d.png)

Does this work ? Are you able to search?

Then, can you please try the following:

1. Close VS.
2. Delete the `.vs` folder from your repository.
3. Start VS and Open the folder
4. Take a look at the background tasks and check if the tasks described above seems to be working (Scanning data succeeded to reach 100%)

Thank you in advance

**Comment by CyrusNajmabadi** [comment]
No.  I see:

![image](https://user-images.githubusercontent.com/4564579/70481584-e86c0a80-1a97-11ea-85ad-f5955a7679ff.png)


The deleting the .vs folder approach did not help.

**Comment by CyrusNajmabadi** [comment]
Note: @jinujoseph i'm seeing tons of other bad behavior like:

![image](https://user-images.githubusercontent.com/4564579/70481640-13eef500-1a98-11ea-9a88-539ec93ec8a3.png)


Note that the tests are simply hung and do not run.  I'm guessing somethin is just breaking *horribly* with OOP.  Except instead of any sort of crash/yellow-bar, we're just getting messages sent that never return, and all features just sit there spinning forever with no results returning.

**Comment by CyrusNajmabadi** [comment]
Doesn't seem to repro in 16.5p2.  Will open a new issue if i run into anything.
