### ISSUE TITLE
Typo on "New Language Features in C# 6" wiki page

### ISSUE THREAD

**Issue by pfusik** [dotnet/roslyn#4023]
https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#nameof-expressions

    (if x == null) throw new ArgumentNullException(nameof(x));

should probably be:

    if (x == null) throw new ArgumentNullException(nameof(x));

**Comment by dsaf** [comment]
C# vNext syntax has been leaked!

**Comment by gafter** [comment]
Fixed
