### ISSUE TITLE
Convert to conditional expression refactoring introduces incorrect cast to non-nullable type

### ISSUE THREAD

**Issue by nxtn** [dotnet/roslyn#40244]
**Version Used**: Visual Studio 2019 version 16.5

**Steps to Reproduce**:

```cs
#nullable enable

using System;

class Class
{
    private static T? GetValueOrDefault<T>() where T : unmanaged
    {
        return null;
    }

    public static void Method()
    {
        IConvertible? nullableInterface;

        if (Environment.Is64BitProcess)
        {
            nullableInterface = GetValueOrDefault<long>();
        }
        else
        {
            nullableInterface = GetValueOrDefault<int>();
        }
    }
}
```

```diff
+Expected Behavior
-Actual Behavior
```

```diff
    public static void Method()
    {
+        IConvertible? nullableInterface = Environment.Is64BitProcess ? GetValueOrDefault<long>() : (IConvertible?)GetValueOrDefault<int>();
-        IConvertible? nullableInterface = Environment.Is64BitProcess ? GetValueOrDefault<long>() : (IConvertible)GetValueOrDefault<int>();
    }
```

**Comment by jasonmalinowski** [comment]
Can confirm this still repros even after the new symbol wrapping.

**Comment by CyrusNajmabadi** [comment]
@333fred this is another case where not having nullable information in IOp is a problem.  in this case, the iop tree just tells us that we ahve have an IConversionOperation node.  but the conversion says it it to `IConvertible` rather than `IConvertible?`, so that' the conversion we maintain.

**Comment by CyrusNajmabadi** [comment]
Checked the type that the ConversionOperation points to.  It has no `.NullableAnnotation` either.

**Comment by DoctorKrolic** [comment]
No longer reproducible:
![VpBDtz4gY8](https://user-images.githubusercontent.com/70431552/166984515-601d7ef9-fbb5-4153-9de7-bb36804a256f.png)
@CyrusNajmabadi close this issue please

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic Thanks!
