### ISSUE TITLE
Issue with upgrading to Microsoft.Net.Compilers to 3.4.0

### ISSUE THREAD

**Issue by TheDestinyGroup** [dotnet/roslyn#40250]
Hi,

I'm experiencing issues updating a ASP.Net MVC projects with Microsoft.Net.Compilers 3.3.1 to either Microsoft.Net.Compilers or Microsoft.Net.Compilers.Toolset 3.4.0.

I'm using VS 2017 15.9.17 for my ASP.Net MVC and .Net Core 2.x projects.

I also have VS 2019 16.4.0 installed on the same PC which I use for some newer .Net Core 3.x projects.

When attempting to update Microsoft.Net.Compilers 3.4.0 via the NuGet Package Manager the install would constantly fail.

I then removed Microsoft.Net.Compilers 3.3.1 from the project.

When attempting to install either Microsoft.Net.Compilers or Microsoft.Net.Compilers.Toolset 3.4.0 via the NuGet Package Manager or via the NuGet Package Manager Console the install would constantly fail.

I also tried Microsoft.Net.Compilers.Toolset 3.4.0 in another of my ASP.Net MVC projects with the same result.

Example output from the NuGet Package Manager is:-
```
Attempting to gather dependency information for package 'Microsoft.Net.Compilers.Toolset.3.4.0' with respect to project 'DestinyWebcast', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 725.89 ms
Attempting to resolve dependencies for package 'Microsoft.Net.Compilers.Toolset.3.4.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.Net.Compilers.Toolset.3.4.0'
Resolved actions to install package 'Microsoft.Net.Compilers.Toolset.3.4.0'
Retrieving package 'Microsoft.Net.Compilers.Toolset 3.4.0' from 'nuget.org'.
Adding package 'Microsoft.Net.Compilers.Toolset.3.4.0' to folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Added package 'Microsoft.Net.Compilers.Toolset.3.4.0' to folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Install failed. Rolling back...
Package 'Microsoft.Net.Compilers.Toolset.3.4.0' does not exist in project 'DestinyWebcast'
Removing package 'Microsoft.Net.Compilers.Toolset.3.4.0' from folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Removed package 'Microsoft.Net.Compilers.Toolset.3.4.0' from folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Executing nuget actions took 3.04 sec
```
Example output from the NuGet Package Manager Console is:-
```
Attempting to gather dependency information for package 'Microsoft.Net.Compilers.Toolset.3.4.0' with respect to project 'DestinyWebcast', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 35.99 ms
Attempting to resolve dependencies for package 'Microsoft.Net.Compilers.Toolset.3.4.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.Net.Compilers.Toolset.3.4.0'
Resolved actions to install package 'Microsoft.Net.Compilers.Toolset.3.4.0'
Retrieving package 'Microsoft.Net.Compilers.Toolset 3.4.0' from 'nuget.org'.
Adding package 'Microsoft.Net.Compilers.Toolset.3.4.0' to folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Added package 'Microsoft.Net.Compilers.Toolset.3.4.0' to folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Install failed. Rolling back...
Package 'Microsoft.Net.Compilers.Toolset.3.4.0' does not exist in project 'DestinyWebcast'
Removing package 'Microsoft.Net.Compilers.Toolset.3.4.0' from folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Removed package 'Microsoft.Net.Compilers.Toolset.3.4.0' from folder 'D:\Data\Documents\Visual Studio 2017\Projects\DestinyWebcast\packages'
Executing nuget actions took 2.67 sec
```
I was able to successfully re-add Microsoft.Net.Compilers 3.3.1 to the project.

I'm not sure what I'm missing. Is the package no longer compatible with VS 2017, is there an issue with installation of the package when the latest version of VS 2019 is already installed on the PC?

Is the issue related to the build issues that the .Net Core team had with release of .Net Core 3.1 and the VS 2019 16.4 update whereby the MSI installers included a different version of the .Net Core 3.1 runtime then the expected version as documented at https://github.com/dotnet/core/issues/3950 and  https://github.com/dotnet/runtime/issues/492

Les

**Comment by dev-masih** [comment]
looks like version 3.4.0 has more issues than I thought https://github.com/dotnet/roslyn/issues/40129

**Comment by jaredpar** [comment]
> Install failed. Rolling back...

If you try this from the command line do you get any actionable error message? This package is used by a number of customers so it's generally usuable. Likely an issue specific to your configuration. But need to see an error to make progress here.

**Comment by TheDestinyGroup** [comment]
Hi,

If I use the command line then the package downloads without error, but after I update the reference to the package to the VS2017 project file, the project file then fails to load.

The changes I make to the project file and the packages file are is to change the references to "Microsoft.Net.Compilers.Toolset" from "3.3.1" to "3.4.0"

Les

**Comment by jaredpar** [comment]
@TheDestinyGroup 

> If I use the command line then the package downloads without error, but after I update the references to "Microsoft.Net.Compilers.Toolset" in the VS2017 project and packages.config files (This step is completed automatically when using the Package Manager or Package Manager Console), the project file then fails to load.

In that case can you file the bug on the NuGet team? If it is working from the command line then that suggests the error is in the VS UI which is outside our control. It's possible this will eventually flip back to us but without an error message there isn't really much that we can do here.

**Comment by MichaelCave** [comment]
I just read an article that says the 3.4.0 is not compatible with VS 2017:

https://developercommunity.visualstudio.com/content/problem/815463/method-systemstringgetpathsofalldirectoriesabove-n.html

**Comment by jaredpar** [comment]
@MichaelCave that's correct

**Comment by MichaelCave** [comment]
@jaredpar the OP is using VS2017, I had to remove the refs to 3.4. in my .csproj files for my app to work after upgrading my nuget packages.
