### ISSUE TITLE
Have access to var in property

### ISSUE THREAD

**Issue by Aurelien54** [dotnet/roslyn#4025]
I think it could be great to do that:

        public int MyProperty { 
            get {
                return MyProperty;
            }
            set {
                MyProperty = value;
            }
        }
That could be handful specialy for the class that implements INotifyPropertyChange.

        /// <summary>
        /// Old way
        /// </summary>
        private int myVar;
        public int MyVar {
            get { return myVar; }
            set {
                Notify(nameof(MyVar));
                myVar = value; 
            }
        }
        
        /// <summary>
        /// New way
        /// </summary>
        public int MyProperty { 
            get {
                return MyProperty;
            }
            set {
                Notify(nameof(MyProperty));
                MyProperty = value;
            }
        }

**Comment by HaloFour** [comment]
Why is it such a hardship to define the backing field for scenarios where you want to include logic in the property accessor methods?

**Comment by mburbea** [comment]
I suspect its more of a concern of scoping and avoiding undesirable assignments/reads?
I think @Aurelien54 wants the naked field available only through this property, not through other methods. That way, he can have his validation always applied even through internal calls.

e.g.
```csharp
    public int MyProperty { 
        get {
            return MyProperty;
        }
        set {
            if(MyProperty < 0 || MyProperty > 10) throw new ArgumentOutOfRangeException(nameof(MyProperty))
            Notify(nameof(MyProperty));
            MyProperty = value;
        }
    }
```
Now, I can't accidentally assign in the internals of the class without validating it is of the proper size. I can see a use for something like this. 

Unfortunately, using the property name for this would be a **breaking change**. It's already possible to have recursive properties (but most likely unwise to do), so you'd probably need another keyword or a contextual one for such a feature, or worst case you'd have to define the variable in the scope of the property.
```csharp
public int MyProperty{
         int _myProperty
         get{...}
         set{...}
     }
```
Now there is no ambiguity, and I can freely refer to this _myProperty only in the scope of the property itself.

**Comment by HaloFour** [comment]
Perhaps.  If scoping is the primary concern then I would agree, and I do see some utility in property-scoped fields, although there are some issues that would need to be addressed such as `readonly` backing fields.

However, I would expect that the reason that auto-properties are being used at all here is to avoid the keystrokes necessary to define a backing field, which property-scoped fields do not resolve.  I'm generally not a fan of having the short-hand syntax completely evolve into supplanting the normal syntax unless there is an exceptionally good reason for it (I'm looking at you primary constructors).  This situation doesn't seem to warrant another syntax, in my opinion.

**Comment by Inverness** [comment]
I think avoiding undesirable reads and writes would be better served by a person or team establishing a convention for field names to indicate when they should never be accessed directly.

**Comment by mburbea** [comment]
@Inverness, sadly the best intents and naming conventions won't stop a "clever" programmer trying to do something the wrong way. 
I think property scoped fields could be useful form of encapsulation, which would basically provide a nice upgrade and add value over simple get_/set_ methods.

**Comment by paul1956** [comment]
Because it defeats the purpose of having auto implemented properties especially for READONLY variables.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by HaloFour** [comment]
@paul1956 

Auto-implemented properties exist specifically to provide a concise syntax **when no additional logic is required in the property accessors**.

[Auto-Implemented Properties (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/bb384054.aspx)

If you need logic in your property accessors you already have the option of the proper property definition syntax which is only slightly more verbose in requiring the definition of a backing field.  It makes little sense to try to evolve the auto-implemented property syntax to allow for custom accessors given that the entire point of the syntax is to automatically implement those accessors.

**Comment by bkoelman** [comment]
I like how this proposal reduces the access scope of the properties' backing field. It prevents that the field is assigned from other places unintentionally, bypassing any validation or expected side effects. 

In the getter/setter scope, we could have something called `storage` that refers to an auto-generated backing field, just like the undeclared identifier `value` refers to the setter input.

```csharp
public int Example
{
    get
    {
        return storage;
    }
    set
    {
        if (storage != value)
        {
            // NotifyPropertyChanged...
            storage = value;
        }
    }
}
```

@HaloFour what issues do you think need to be addressed for `readonly` backing fields?

**Comment by HaloFour** [comment]
@bkoelman

Judging from the tags added to this issue it appears that this proposal is on the short list to be not considered.  Simply declare a proper backing field if you want logic in your properties.

My comments were for @mburbea 's inline proposal (which he should post as a new issue).

The issue with `readonly` fields is that they can only be assigned to directly in the constructor.  They cannot be assigned to in a property setter method.  This is fine for readonly auto-implemented properties as they define no setter method and while you use property setting syntax to assign it in the constructor the compiler just replaces that with direct assignment to the backing field.  The compiler could do the same if the property didn't define a setter method, but if it did (which might not make sense but would be perfectly legal) then there would be no way to assign that field.

**Comment by bkoelman** [comment]
Ah yes, I was also referring to the inline proposal. 

About the readonly issue, we could allow direct assignment as with readonly properties, like:

```csharp
public readonly int Example = 123 // 123 is assigned without running the setter block
{
    get
    {
        return storage;
    }
    set
    {
        if (storage != value)
        {
            // NotifyPropertyChanged...
            storage = value;
        }
    }
}
```

The 123 assignment would not call the setter block, but directly assign the auto-generated backing field. This could also be applied when assigned from within constructor. But then it may get non-obvious when the setter runs and when not. For example:

```csharp
public class C
{
    C()
    {
        Example = 5; // directly assigns backing field, does not run the setter code block
    }

    C(string s)
    {
        OtherMethod();
    }

    void OtherMethod()
    {
        Example = 6; // does run the setter code block
    }
}
```

**Comment by jnm2** [comment]
Using a backing field without naming it was considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
