### ISSUE TITLE
Allow any built-in or 3rd party fixer in code cleanup profiles

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#40263]
Currently fixers included in a code cleanup profile are added by the product team on a case-by-case basis. Only then can they be included by users. Since all fixers, (including 3rd party fixers) can be specified in EditorConfig it'd be natural to be able to include any of those in a code cleanup profile.

Inspired by [comment](https://github.com/dotnet/roslyn/issues/37129#issuecomment-559702988).

> Also editorconfig could be useful for storing cleanup profiles for whole team so every dev will not have to construct same cleanup profile. Currently fixes which are not listed in cleanup list have to be used manually line by line, rule by rule which is time consuming process and could save a lot of time to every dev team.

**Comment by jmarolf** [comment]
related to https://github.com/dotnet/roslyn/issues/40163

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
