### ISSUE TITLE
Update Building wiki page 

### ISSUE THREAD

**Issue by dhusemann** [dotnet/roslyn#4026]
Update https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging

to reflect RTM Packages.

**Comment by ChrisMissal** [comment]
[Getting the code](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging#getting-the-code) has changed, it appears the steps should be:

1. Clone https://github.com/dotnet/roslyn
2. Change directory to `<clone dir>` and run `.nuget\NuGet.exe restore Roslyn.sln`
3. Open Roslyn.sln

**Comment by diryboy** [comment]
It's confusing, the Roslyn.sln in master branch is placed under root, but in the releases/VS2015 branch, it's placed under src folder.

I tried to build both branches, only get failed: in the master branch, the first time of build gave me something like 180000 errors, the second time gave me 2 errors about not being able to uninstall some VSIX packages, when I switch to the releases/VS2015 branch and build src\Roslyn.sln it gave me 128 succeeded, 3 failed with error about the VSIX uninstall.

>There was a problem uninstalling the extension with a VSIX identifier of "1F42C6D0-F876-4AF0-8185-1BEB0A325BB2". You need to use the Programs and Features pane in the Windows Control Panel to remove VisualStudio Interactive Components.
>There was a problem uninstalling the extension with a VSIX identifier of "0b5e8ddb-f12d-4131-a71d-77acc26a798f". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Language Services.
>There was a problem uninstalling the extension with a VSIX identifier of "21BAC26D-2935-4D0D-A282-AD647E2592B5". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Expression Evaluators.

And I got warnings about not finding `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll` but that dll actually exists. and mscorlib.dll under `\.NETPortable\v4.5\Profile\Profile7\` actually not exists..

**Comment by diryboy** [comment]
Looks the building wiki page has been updated. I succeeded building Roslyn.sln master in VS2015 today(ee37843baf0f45e88d183767c07247959d3d1224), with the warnings

The referenced component 'System.Collections' could not be found.	CSharpFeatures

**Comment by davkean** [comment]
I've updated this page to reflect the current world.
