### ISSUE TITLE
Indexer resolution for subclasses of `KeyedCollection<TKey, TItem>`

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn#40270]
**Version Used**: 

```
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.5.0 Preview 2.0 [29601.14.master]
VisualStudio.16.IntPreview/16.5.0-pre.2.0+29601.14.master
Microsoft .NET Framework
Version 4.8.03752
```

**Steps to Reproduce**:

```cs
using System;
using System.Collections.ObjectModel;

namespace SimpleWinForms
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            var collection = new CustomCollection();
            collection.Add(TaskDialogResult.OK);
            collection.Add(TaskDialogResult.Cancel);

            var button = collection[0];
        }
    }
    public enum TaskDialogResult : int
    {
        None = 0,
        OK = 1,
        Cancel = 2,
    }

    public class Container
    {
        public Container(TaskDialogResult result)
        {
            Result = result;
        }

        public TaskDialogResult Result { get; }
    }

    public class CustomCollection : KeyedCollection<TaskDialogResult, Container>
    {
        public Container Add(TaskDialogResult result)
        {
            var button = new Container(result);
            Add(button);

            return button;
        }

        protected override TaskDialogResult GetKeyForItem(Container item) => item.Result;
    }
}

```

**Expected Behavior**:

1. No `System.Collections.Generic.KeyNotFoundException` without the indexer overloads
2. No inherited indexers shown once there is an overload in place

**Actual Behavior**:

1. The intellisense shows 2 overloads for the indexer:
![overloads](https://user-images.githubusercontent.com/4403806/70492895-05691200-1b5a-11ea-984a-8dbf1ff79ced.gif)
One for `KeyedCollection<TKey, TItem>` and one `Collection<T>`.

1. If the above code is executed it fails with `System.Collections.Generic.KeyNotFoundException`:
```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key 'None' was not present in the dictionary.
  Source=System.ObjectModel
  StackTrace:
   at System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key)
   at SimpleWinForms.Program.Main() in C:\Development\!Repro\SimpleWinForms\SimpleWinForms\Program.cs:line 19
```
The `0` is treated not as an index but as `(TaskDialogResult)0`. I guess it can be argued that it makes sense, given that `KeyedCollection<TKey, TItem>` defines its indexer as `TItem this[TKey key] { get; set; }`. However However `Collection<T>`, which `KeyedCollection<TKey, TItem>` inherits from, defines its indexer as `T this[int index] { get; set; }`. 
And (❗️) `Collection<T>.this[int index]` indexer is shown by the intellisense.
From a consumer point of view this behaviour is unexpected.

2. To overcome the `KeyNotFoundException` we can introduce a new indexer overload:
```cs
    public class CustomCollection : KeyedCollection<TaskDialogResult, Container>
    {
        public new Container this[int index]
        {
            get => base[index];
            set => base[index] = value;
        }

		// ... existing
	}
```

Now the call `var button = collection[0];` works as expected, but the intellisense shows 3 overloads!
![overloads1](https://user-images.githubusercontent.com/4403806/70493320-5d544880-1b5b-11ea-93e0-3904d6fbd407.gif)

----

Originally reported in https://github.com/dotnet/winforms/pull/1133#issuecomment-562930731

**Comment by sharwell** [comment]
Most of the confusion here comes from the implicit conversion of a constant 0 to an enum type. If you were to use `collection[1]` instead, the other indexer would be used.

**Comment by RussKie** [comment]
What about not showing overloaded indexers?
