### ISSUE TITLE
C# automatic string literal wrapping gets wrong indentation with Keep Tabs enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40277]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/102134/c-automatic-string-literal-wrapping-gets-wrong-ind.html)._

---
I really like the feature that the C# editor now automatically adds the proper concatenation when pressing ENTER in a non-verbatim string literal, but I cannot get it to indent correctly after the second line of the string literal. I am using VS 2017 V15.3.2.

E.g. I start with a new Console Application for .NET 4.7 and type the following line inside the Main method:
```C#
			string s = "Lorem ipsum dolor sit amet";
```

Then I place the cursor after 'Lorem' and press ENTER, so I get this - still OK:
```C#
			string s = "Lorem" +
				" ipsum dolor sit amet";
```

Then I place the cursor after 'ipsum' and press ENTER, then it unexpectedly outdents by three levels:
```C#
			string s = "Lorem" +
				" ipsum" +
	" dolor sit amet";
```

For every further line break it outdents by one more level

I would be glad if this could be resolved. Or can it be caused by some editor setting?
Thank you.

---
#### Blair Wang [MSFT] on 6/26/2018, 08:43 PM: 

Thanks for reporting this problem. After careful evaluation of the problem impact &amp; severity we are closing this problem as low priority. We understand that this might not be an ideal resolution for you, but be assured that we don’t make these decisions lightly.  We prioritize problem investigations by impact and severity for a broad set of customers; the impact of this problem is limited relative to other existing problems. 
 
 We have made significant improvements to the product over the past few months, notably in the areas of performance, reliability &amp; general quality of the product. It is possible that this problem has been addressed in the latest version of Visual Studio. We encourage you to update to latest version of Visual Studio and continue to give us feedback.

#### Christian Hornung on 10/22/2019, 06:42 AM: 

The problem is still present in VS 2019 version 16.3.5, unfortunately.<br>It only occurs if the editor is set to use tabs instead of spaces for indentation - maybe that helps to narrow it down.
#### Christian Hornung on 12/4/2019, 01:45 AM: 

Still a problem in 16.4.0.

---
### Original Solutions
(no solutions)

**Comment by dpoeschl** [comment]
As Christian mentions, this only repros when I have Keep Tabs set. Here's what I see with Visible Whitespace enabled:

![image](https://user-images.githubusercontent.com/235241/70566610-41e04200-1b49-11ea-8587-61dc53435124.png)
