### ISSUE TITLE
ArgumentException An entry with the same key already exists

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40291]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/637100/argumentexception-an-entry-with-the-same-key-alrea.html)._

---
When switching between files:

System.ArgumentException: An entry with the same key already exists.
   at System.Collections.Specialized.ListDictionary.Add(Object key, Object value)
   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CompletionSource. <GetCompletionContextAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations. <CallExtensionPointAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Fiona Niu[MSFT] on 7/9/2019, 02:37 AM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide some screenshots and repro steps , a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario?</p>
<p>We look forward to hearing from you</p>

#### Fiona Niu[MSFT] on 7/15/2019, 03:03 AM: 

<p>This is a quick reminder on our previous request for more information. Please reply within seven days from now so we can make progress on resolving your issue, otherwise the feedback will be closed.</p>

#### Fiona Niu[MSFT] on 7/23/2019, 07:57 PM: 

<p>Thank you for your feedback. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/24/2019, 00:18 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### himanshu on 7/28/2019, 01:50 PM: 

Same issue in VS 2019 16.2 update
#### Timtim Bwasheze on 9/29/2019, 08:20 AM: 

I also get this error when I press save with Hot Reload enabled in a xamarin.forms project with android as startup project. Hot Reload does not work. VS 2019 v16.3.1 Xamarin.Forms v4.2.0.815419<br><br>Error Message:<br>System.ArgumentException<br>  Message=An element with the same key already exists in NameScope<br>Parameter name: name<br>
#### Alex Corrado [MSFT] on 11/19/2019, 11:32 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/9688/a9b0f77b-5737-4766-a5e0-ced4503f5fef.html" nodeid="9688">@Timtim Bwasheze</a> I believe that is a different issue that has been resolved in the upcoming VS 2019 16.4 and Xamarin.Forms 4.3 releases. If you are able to try one of those builds and the issue still persists, please open a new feedback ticket so we can take a closer look. Thanks!</p>

#### Visual Studio Feedback System on 11/19/2019, 06:27 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
Yes, the issue should be fixed with the following fix: https://github.com/dotnet/roslyn/pull/36146
Please let me know if you are able to reproduce it in 16.4 or later.
