### ISSUE TITLE
C# Interactive crashes VS when using an if statement

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/roslyn#40301]
**Version Used**: 16.4.1

**Steps to Reproduce**:

1. Open C# Interactive window
2. Type `string input = "1118";` (newline)
3. Type `if (Int32.TryParse(input, out var result`
4. At some point after this (perhaps before or after adding closing parens) Intellisense window pops up.
5. Window freezes for a few seconds and then VS restarts.

**Expected Behavior**:
Code entered in window should not crash VS.

**Actual Behavior**:
Crashes shortly after Intellisense pops up (may or may not be related).

**Comment by jcouv** [comment]
FYI @tmat @ivanbasov

**Comment by tmat** [comment]
I can't reproduce the crash. @CoolDadTx could you file a VS Feedback item with a crash dump attached. Thanks!

**Comment by tmat** [comment]
Actually, there is an existing VS Feedback ticket: https://developercommunity.visualstudio.com/content/problem/758581/c-interactive-crashes-visual-studio.html?childToView=848079#comment-848079

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/39584

**Comment by CoolDadTx** [comment]
Thanks for the update
