### ISSUE TITLE
Duplicate code fixes reported if analyzer reference is installed as a VSIX as well as a nuget reference

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#4030]
See https://github.com/icsharpcode/RefactoringEssentials/issues/28

**Comment by mavasani** [comment]
I investigated this further and we are correctly de-duplicating the analyzers and hence only a single diagnostic is being generated. However, we have no de-duplication of the CodeFixProvider itself, so we end up with 2 instances of the fixer, one from each source, and they end up reporting a duplicate fix. Equivalence key de-duplication only works across code actions reported by a single fixer instance, so isn’t useful here.

There is no way to turn off or suppress a fixer, so I don’t see a workaround at the user end. I see the following path for this:

1. Long term: we must fix our CodeFixService to de-duplicate analyzer references or individual fixer instances between VSIX and nuget packages.
2. Short term workaround: RefactoringEssentials.sln can separate out the CodeFixProviders into a separate project/assembly. Then they ensure that this assembly is added only to a single source: either the VSIX or the nuget package.

**Comment by Pilchie** [comment]
Related discussion about analyzers themselves in #18818.  

Moving this to @kuhlenh to go with that.

**Comment by CyrusNajmabadi** [comment]
Should be fixed with all the work we've done around torn analyzers.
