### ISSUE TITLE
Should have a code suggestion warning that arrayvar[^0] is always invalid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40314]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/545640/should-have-a-code-suggestion-warning-that-arrayva.html)._

---

Should alert people that accessing `arrayvar[^0]` is always past the end of the array. The possible fix would be to change it to `arrayvar[^1]` since people may erronously think that `[^0]` points to the last element.

Language C# 8

---
#### Jane Wu [MSFT] on 4/25/2019, 00:08 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Simon Brand [MSFT] on 10/8/2019, 02:43 AM: 

<p>Thanks for your suggestion. Which language is this for? In C++ <code>array[^n]</code> is not valid syntax.</p>

#### adegeo [MSFT] on 10/8/2019, 10:23 AM: 

<p>C#</p><p>Sorry for not providing that. I'll do so now.</p>

#### Simon Brand [MSFT] on 10/9/2019, 01:35 AM: 

<p>Thanks. This got routed to the C++ team, so I’ve moved it to the C# team.</p>

#### Visual Studio Feedback System on 11/25/2019, 02:39 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
@mavasani This may fall under the .NET 5 analyzers list

**Comment by CyrusNajmabadi** [comment]
@mavasani for roslyn-analyzers?

**Comment by genlu** [comment]
Design meeting decision: Move this to Roslyn-analyzer repo.
