### ISSUE TITLE
Quick Actions - Suggest Casting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40312]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/829828/quick-actions-suggest-casting.html)._

---
<p>When opening 'Quick Actions' on certain call it would show to cast the object.</p> <p>e.g: Math.Floor( 5 / 2 ) would error 'call is ambiguous between the following methods or properties' would suggest casting it to double or decimal</p>

---
#### Visual Studio Feedback System on 11/21/2019, 08:08 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
