### ISSUE TITLE
Compiler crash when using ranges in Expression<Func<>>

### ISSUE THREAD

**Issue by Simon-Campbell** [dotnet/roslyn#40326]
Code which creates an expression using the range syntax causes a compiler crash.

```csharp
        public static Expression<Func<string, bool>> CreateCrashingExpression()
        {
            // Create an expression that compares the "tail" of the string value
            // with some known value.
            return (string a) => a[7..] == "RIGHTSUFFIX";
        }
```

**Version Used**: 
- .NET Core SDK 3.1.100
- MS Build 16.4.0+e901037fe

This is the CSC details in `C:\Program Files\dotnet\sdk\3.1.100\Roslyn\bincore` (hope this is the right version information!)

![image](https://user-images.githubusercontent.com/7017162/70685780-42c2d080-1d0f-11ea-8073-c9ca991cb723.png)

**Steps to Reproduce**:

1. Install .NET Core SDK 3.1.100 
2. Clone https://github.com/Simon-Campbell/csharp-range-expression-crash
3. Run `dotnet build` from the root of the cloned folder
4. The compiler will crash

**Expected Behavior**:
In the sample app: creates an expression which can then be invoked

**Actual Behavior**:
Compiler crash (see build log in linked repository)

**Comment by jaredpar** [comment]
Thanks for filing. Will take a look.

Index and ranges though are not supported in expression trees. So the result of this bug won't be to enable the scenario but rather to produce an error here instead of crashing.

**Comment by Joe4evr** [comment]
Support for ranges in expressions can be tracked separately at dotnet/csharplang#2545.
