### ISSUE TITLE
C# Interactive doesn't support C# 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40341]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/836385/c-interactive-doesnt-support-c-8.html)._

---
<p>Please have C# interactive support C# 8.0.</p><p>I believe that the whole purpose of the C# interactive compiler is for playing and experimenting with new code.<br>Lack of support for C# 8 makes the interactive tool completely unusable.</p>
<p>Here’s a sample console:</p>
<pre>Microsoft (R) Visual C# Interactive Compiler version 3.3.1-beta3-19461-02 ()
Loading context from 'CSharpInteractive.rsp'.
Type &quot;#help&quot; for more information.
&gt; var x = new int[] { 1, 2, 3 };
&gt; var a = x[^1];
(1,11): error CS0518: Predefined type 'System.Index' is not defined or imported
(1,11): error CS0656: Missing compiler required member 'System.Index..ctor'
&gt;
</pre>

---
#### Visual Studio Feedback System on 11/27/2019, 11:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/12/2019, 00:09 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
The Interactive Window only supports .NET Framework at this point. Hence features are limited to C# 7.3 and lower. Too enable C# 8 we would need to first enable running on Core CLR (see https://github.com/dotnet/roslyn/issues/4788).

**Comment by matthew-a-thomas** [comment]
@tmat It looks like you recently closed #4788 with this comment:

>We are gonna use the Core CLR that are found using VS process environment variables.

How does that impact this issue?

**Comment by tmat** [comment]
The Interactive Window now supports running on .NET Core.

Execute the following command to switch to .NET Core host process:

```
#reset core
```

Then all C# 8 (and later) features should be available:
![image](https://user-images.githubusercontent.com/41759/101705929-ee931f00-3a3c-11eb-8cd4-e868426ab038.png)

**Comment by jods4** [comment]
This is great! ...but not very discoverable.

Is there a reason this isn't the new default? 
C# interactive should keep up with new releases and not be stuck in the past so I'd expect C#9 / Core support out of the box, and being able to go back to .net framework as an additional step, esp. now that .NET 5 has replaced .NET Fx for good.

Is there an option to change this?
A small UI (dropdown) to go between .net fx and core next to the buttons that are already there would be good, too.

**Comment by genyx** [comment]
this is needed!

**Comment by MgSam** [comment]
@tmat 
I just discovered this thread after literally waiting for years for .NET Core support in C# Interactive. I don't think an obscure thread on Github is the right way to announce new functionality. I'm pretty sure most Microsoft employees don't even know about this feature, as people continue to request C# Interactive to get updated and the response I've seen is akin to "we may at some point".

Can you at minimum make a blog post on MSDN DevBlogs about this or better yet, make .NET Core the default? I see no reason whatsoever that .NET Framework should still be the default.

**Comment by IanKemp** [comment]
.NET Core really, really, **really** needs to be the default.

**Comment by jods4** [comment]
Yeah, the more time passes the less .net fx as default makes sense.

It's 2022, .net fx has reached its end of life and was officially superseded by .net 5, in a few month .net 7 will be released.

I think it's time: please make .net core the default in C# Interactive for the next VS release!

**Comment by HansOlavS** [comment]
@IanKemp is totally right! .NET Core/.NET 6 really *really* needs to be the default. That should've been switched in VS 2022 and .NET 6, in my opinion. It was probably just forgotten by the product team.

**Comment by Cereal-Killa** [comment]
Agreed, we need this to default to the latest and the greatest.

**Comment by s-sergio** [comment]
only adding noice on this, I hope one day to have the .NET RELP directly in cmd without csi.exe or VS.
But let's wait until .NET be multiplataform first, I cannot run .NET 6 in my mobile yet.

**Comment by ScottRFrost** [comment]
FYI this issue is still occurring (.NET Core isn't the default) and I just lost a half hour or so investigating

**Comment by weitzhandler** [comment]
Any plans to make it default in VS 2022 C# Interactive? I often find myself searching for this issue to discover `#reset Core`. Please make the latest .NET RTM version (currently .NET 8) and the latest C# version the defaults of the REPL.
