### ISSUE TITLE
VS no longer reports error if you try to use async in a project that targets <.NET45

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#4035]
REPRO:
(1) File>New>VB>ClassLibrary(Portable) and target .NET4 + Windows8
(2) Add a method "Public Async Function FAsync() As Task"
(3) BuildAll

WHAT I GET: merely a warning that the method lacks await operators
WHAT I EXPECT: also a compile-time error

Note that if I build from the command-line using "msbuild", then I do correctly get the compile-time errors.

```
Class1.vb(2,5): error BC31091: Import of type 'AsyncTaskMethodBuilder' from assembly or module 'ClassLibrary3.dll' failed.
Class1.vb(2,5): error BC31091: Import of type 'IAsyncStateMachine' from assembly or module 'ClassLibrary3.dll' failed.
Class1.vb(2,5): error BC35000: Requested operation is not available because the runtime library function 'System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext' is not defined.
```

I think the wording of the error is incorrect also. The error is phrased "import of AsyncTaskMethodBuilder from ClassLibrary3.dll" -- but we're never trying to import this type **from** that class library!

Also I think the third error should never be given to the user. `Requested operation`? That sounds like an internal diagnostic compiler string, not a user-facing message.

For comparison, VS2013 used to give an error within VS, and it gave a nicely-phrased actionable error:
```
error BC36948: Cannot find all types required by the 'Async' modifier. Are you targeting the wrong framework version, or missing a reference to an assembly?
```

**Comment by gafter** [comment]
The VB compiler is apparently reporting language diagnostics too late (as the language constructs are defined in terms of APIs that do not exist on the platform).

**Comment by gafter** [comment]
Adding a related bug in Area-Analyzers, as the build error should be appearing in the Error window.

**Comment by gafter** [comment]
After looking at the language specification, it does not appear the language spec refers to these types explicitly. This is therefore appropriate as a late-reported diagnostic. While it would be nice to report a problem earlier, the primary problem is (#4567) that VS fails to relay the build diagnostic to the error window.

**Comment by ljw1004** [comment]
I don't think that's the right criterion for "late-reported vs early-reported". The bottom line should that early-reported is always better for the user of VS, so we should always prefer it, and only fall back to late-reported if it's too difficult to report early.

**Comment by gafter** [comment]
@ljw1004 We should discuss this offline, but we have a carefully worked out policy for where to detect and report errors. One of the principal criterion is how to avoid repeating code and/or repeating work. This kind of error does not result from errors during typing.

**Comment by heejaechang** [comment]
@ljw1004 @gafter what is happening here (for error list case) is that, IDE think live analysis (compiler errors) can produce BC31091 and BC35000 so it throws away those errors reported from build (actually only for opened file, but that is just our tweak for user experience). 

so that is why they are missing from error list. if these errors will be never reported from live analysis from compiler, we can explicit exclude them.

but generally fix the issue, we need this.
https://github.com/dotnet/roslyn/issues/1400

**Comment by heejaechang** [comment]
by the way, if you change "Build+Intellisense" to "Build Only", you will see all errors reported from build (output window) as they are.

"Build Only" option is added specifically for people who don't like our de-duplication (or issues our de-duplication logic has)
