### ISSUE TITLE
Ruleset editor equivalent for .editorconfig.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#40365]
The ruleset editor is very useful for example when disabling an entire category. This is useful when disabling StyleCop documentation analyzers in test projects for example.

![image](https://user-images.githubusercontent.com/1640096/70831001-c0f7a380-1df1-11ea-8ed7-cdddde242da0.png)

**Comment by xperiandri** [comment]
As I understand this is covered by https://github.com/madskristensen/EditorConfigLanguage/ but not yet for rules.
@madskristensen right?

**Comment by madskristensen** [comment]
@xperiandri No, the repo you linked provides the language service only and no other UI for dealing with .editorconfig files.

**Comment by mavasani** [comment]
@JohanLarsson You can now do this operation with a single .editorconfig entry, see https://github.com/dotnet/roslyn/pull/38886#issue-321838740

**Comment by mavasani** [comment]
Tagging @mikadumont for the more generic request for a UI over .editorconfig.

**Comment by mavasani** [comment]
NOTE: You can find a rule's category by looking at the "Category" column in error list, which is hidden by default.

**Comment by JohanLarsson** [comment]
![image](https://user-images.githubusercontent.com/1640096/73913796-2f1f8a80-48b8-11ea-9315-6392c666305a.png)

Looks like the catergory column shows something else.

**Comment by mavasani** [comment]
@sharwell you want to fix this in StyleCop analyzers to have the correct category?

**Comment by JohanLarsson** [comment]
Pretty sure `StyleCop` does it right. I think the bug is in the error list UI.

**Comment by mavasani** [comment]
Ah, I didn’t notice your diagnostics were from build, not Intellisense. Unfortunately, the diagnostics shown from explicit build cannot find the category as the build output does not have this data. Switching to Build + Intellisense should show the correct values.

**Comment by sharwell** [comment]
For transparency, we've discussed the option of an editorconfig UI a few times internally. While no decisions have been made, there are two important recurring themes:

1. The custom UI is "challenging" to create and maintain. Aside from the obvious time it takes for design work and the relatively high amount of work that UI testing takes, we have extremely strict requirements for accessibility that must be met. For anything we can deliver as a text editor, the latter two points are resolved automatically so we can put all the real work into the design.
2. We want to find a way to deliver the [EditorConfig Language Service](https://github.com/madskristensen/EditorConfigLanguage/) as a default installation item for Visual Studio, and then work to improve the user experience when working with this extension.

**Comment by jmarolf** [comment]
# Editorconfig UI Proposal

## Entry points

### View -> Other Windows

![image](https://user-images.githubusercontent.com/9797472/87332129-fc756000-c4ef-11ea-8b72-4e7ba0720358.png)

### Analyzer Project Node in Solution Explorer

![image](https://user-images.githubusercontent.com/9797472/87332236-24fd5a00-c4f0-11ea-9bce-b468c023a749.png)

### Right click in .editorconfig file

![image](https://user-images.githubusercontent.com/9797472/87329834-74da2200-c4ec-11ea-8352-1642a127aa30.png)

### Ctrl+Q Search

Shows up in search for editor config in the ctrl+q search.

## Features

### Minimum UI Proposal

- Search
- Set editorconfig values
- Filter based on columns

![image](https://user-images.githubusercontent.com/9797472/87331801-748f5600-c4ef-11ea-9553-97a593109e9c.png)

### Maximal UI Proposal

Additional Features:

- Categorized sections
  - Code Style
  - Naming Style
  - IDE Analyzers
  - Analyzers
- Access to editors from Tools->Options
  - Show previews of style settings
  - Allows editing of nameing styles

![image](https://user-images.githubusercontent.com/9797472/87333305-ca64fd80-c4f1-11ea-836e-72b4f1759693.png)

**Comment by allisonchou** [comment]
**Notes from today's design meeting (7/13)**:
It was determined that we need a more complete proposal. Some questions to be answered:
- How will we support 3rd party analyzers?
- LSP? We should have higher confidence that this would be able to translate well to the LSP world.

**Comment by jmarolf** [comment]
## Overview

Three sections:

- Category Tree
  - List all editorconfig files that apply to the solution
  - Lists all the categories under each editorconfig
  - Selecting a category updates the Tabular Data Control section
- Tabular Data Control
  - Whitespace
  - Code Style
  - Naming Style
  - Analyzers
- Setting Application Sample
  - The same as tools -> options. Shows what the setting will do once applied

![image](https://user-images.githubusercontent.com/9797472/87977130-14fef080-ca83-11ea-8837-0fa606553fdd.png)


### Whitespace

| Description | Preference |
|:------------|:-----------|
|             |            |

### Code Style

Columns:

| Description | Preference | Severity |
|:------------|:-----------|:---------|
|             |            |          |

![image](https://user-images.githubusercontent.com/9797472/87975798-f8fa4f80-ca80-11ea-9e7e-643e906adcb7.png)


### Naming Style

### Analyzers

| ID | Description | Severity |
|:---|:------------|:---------|
|    |             |          |

**Comment by huoyaoyuan** [comment]
Side note:
RuleSet designer resets comments in ruleset file. Editorconfig designer should preserve them.
