### ISSUE TITLE
[Cloud Environment] Source files always open in Miscellaneous Files project

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#40362]
**Version Used**: 

master 29609.17 (16.5 Preview 2)

**Steps to Reproduce**:

1. Create a new cloud-connected environment but point devenv.exe to the folder containing your solution rather than the solution itself.
2. Connect to the server from a client.
3. On the client, double-click on the solution file to open it.
4. Open any source file in the solution.

**Expected Behavior**:

The source file opens in the appropriate project. For example, the Nav Bar shows the project's name, and completion lists show other types and members from the same project and from referenced projects. 

**Actual Behavior**:

The source file opens in the Miscellaneous Files project, as reflected in the Nav Bar. Other types and members from the same project and referenced projects are not available in the completion list, etc.

**Comment by tmeschter** [comment]
Note that this does _not_ reproduce if the server is pointed at the solution to begin with, rather than a folder.

**Comment by jasonmalinowski** [comment]
@dibarbet Did you make any progress on this one? Fine to say "no" but don't want to reinvestigate things.

**Comment by jasonmalinowski** [comment]
So trying this locally, it seems @dibarbet's changes to move much of the Cloud Environment case to LSP seems to help. Most features are now using the LSP thing which don't care if the local Workspace is initialized right, and I am seeing the local Workspace get files added on demand which fixes up a few other things. I'm seeing navbars broken which @dibarbet is looking at.

I'll test more tomorrow to see if there's other problems.

**Comment by jasonmalinowski** [comment]
I'm unable to reproduce the Miscellaneous Files behavior here -- the files being opened locally are being opened in the Remote workspace, and most features now being on LSP is behaving right. The only obvious bug I found was #40989 which is unrelated to anything here and is something @dibarbet is now looking at.
