### ISSUE TITLE
IDE0004 - incorrectly suggest to remove cast in string interpolation

### ISSUE THREAD

**Issue by NSentinel** [dotnet/roslyn#4037]
Visual Studio info:

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

OS info:

Microsoft Windows 10 Pro / Version 10.0.10240 Build 10240

Repro case:

```C#
using System;

class Sample 
{
    public enum State: ushort
    {
        None = 0x00,
        State1 = 1 << 0,
    }
	
    public static void Main() 
    {
		State alarmState = State.State1;
		
		string str = $"State: {alarmState} [{(ushort)alarmState:X4}]";
						
		Console.WriteLine(str);
    }
}
```

Visual Studio incorrectly suggest to remove cast to **(ushort)**, 

![example](https://cloud.githubusercontent.com/assets/2722498/8813072/23baee22-3009-11e5-9709-6aaef57a3fef.png)

so code becomes:

```C#
string str = $"State: {alarmState} [{alarmState:X4}]";
```

this leads to System.FormatException during execution since string (Enum.ToString) can't be formated as numeric value:

```C#
   in System.Enum.ToString(String format)
   in System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   in System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   in System.String.Format(String format, Object arg0, Object arg1)
   in Sample.Main()
```

[Microsoft Connect Entry](https://connect.microsoft.com/VisualStudio/feedback/details/1489559/ide0004-incorrectly-suggest-to-remove-cast-in-string-interpolation)

**Comment by EamonNerbonne** [comment]
For people experiencing this bug in VS2015 now, a workaround is to suppress warning IDE0004 in the build tab of the property pages of the affected project.

**Comment by Pilchie** [comment]
Hey @DustinCampbell, does #4643 fix this too?  Care to add a test to verify?

**Comment by DustinCampbell** [comment]
No, and I wouldn't expect it to.

**Comment by dpoeschl** [comment]
Note that explicit ToString() calls on the casted value work correctly (cast not marked as unnecessary):

```C#
Console.WriteLine(((ushort)alarmState).ToString());
```

**Comment by miloush** [comment]
I am still getting a variant of this in 16.7.0 Preview 3.1:
```C#
char c = '4';
string s = $"{(int)c:X4}";
```

The cast to `int` is marked as redundant, but results in s being `"4"` rather than `"0034"`.

Maybe no cast should be treated as redundant if there is formatting (or at least when the value is `IFormattable`)?

**Comment by CyrusNajmabadi** [comment]
> I am still getting a variant of this in 16.7.0 Preview 3.1:

Can yu please open an issue on that?  Thanks!
