### ISSUE TITLE
Liveshare publish diagnostics should be cancellable

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#40388]
Publish diagnostics in the liveshare client should be cancelled if we get updated diagnostics for the document being calculated.

Also should not be async void.

**Comment by CyrusNajmabadi** [comment]
Note: > Also should not be async void.

this is the more critical part as i have no idea how you'll actually test this.

For that matter, how *are* tests passing here  i.e. there's now way for the test to know once you've processed diagnostics.  So how does it not insta fail when it checks on this stuff?

**Comment by CyrusNajmabadi** [comment]
Sent you some info on gitter btw.

**Comment by CyrusNajmabadi** [comment]
Closing out, we do not have publish diagnostics anymore.
