### ISSUE TITLE
Flag to allow stopping on analyzer/refactoring exceptions in debugger

### ISSUE THREAD

**Issue by Rpinski** [dotnet/roslyn#4038]
In VS 2015 RTM currently all unhandled exceptions thrown in analyzers/refactorings are catched to show the "yellow error bars" on editor's top. When debugging an analyzer with a separate VS instance there seems to be no chance to stop the debugger as soon as the exception occurs. But it used to work in RC and previous CTPs.

Would it be possible to add a configuration flag or something similar to disable the catching behavior in this case? That would help a lot when trying to analyze unhandled exceptions in custom extensions.

Thank you very much.

**Comment by Pilchie** [comment]
You'll need to use the Exceptions tool window, and configure your debugger to break on all first chance exceptions, not just unhandled ones.

**Comment by srivatsn** [comment]
The yellow bar is a feature to not let errant fixers crash VS for end users and so enabling first chance exceptions is the right thing to do here. Since that option exists, the incremental value of adding a configuration flag specifically for this is small.
