### ISSUE TITLE
Incomplete switch expression is parsed as switch statement

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40399]
**Version Used**: current master

The `switch` text is parsed as SwitchStatementSyntax, but it should be parsed as SwitchExpressionSyntax.

[SharpLab in Syntax Tree mode](https://sharplab.io/#v2:C4LghgzsA+ACBMACAwgWAFAG8ON4glgHbCICyAFLAIwB0yA9oRPQDYCmDL9ATogMaseAShx5s6PJMSwA7P0G8IAd3zA+AC1G4Avhl3ogA===
)

```cs
class C
{
    int M(System.ConsoleColor color)
    {
        return color switch
    }
}
```

It came up because of the [Update 'Populate switch' to support switch-expressions](https://github.com/dotnet/roslyn/pull/40232) work. The existing statement form of this feature offers autocompletion at `[||]switch (e)`. The expression version of this would be `e switch[||]`.

/cc @CyrusNajmabadi

**Comment by gafter** [comment]
We had it working that way at first, but it got the parser quite confused when typing new text before an existing switch statement.  We found that this disambiguation reduced such problems.  So it is by design.

**Comment by jnm2** [comment]
Thanks.

@CyrusNajmabadi Since this is by design, should we do anything to make the experience better? Seems like it would be super nice to be able to be in an expression, type `expr switch[||]`, press Ctrl+., Enter, and have all the cases generated. It would require CSharpPopulateSwitchExpressionDiagnosticAnalyzer to register for `SwitchStatementSyntax` in addition to `SwitchExpressionSyntax`.

Or should we just delete the test?

https://github.com/dotnet/roslyn/blob/8b2bfdfefa57d290a23f1c14701aefe7762a4bb7/src/EditorFeatures/CSharpTest/PopulateSwitch/PopulateSwitchExpressionTests.cs#L964-L998

Our chat that led to this: https://gitter.im/jnm2?at=5df59385e72656230146d3cd
