### ISSUE TITLE
No autocomplete after using (c#8 syntax)

### ISSUE THREAD

**Issue by giladfrid009** [dotnet/roslyn#40393]
**Version Used**: 
16.4.1
**Steps to Reproduce**:

T represents a proper class.

doesn't autocomplete: (c# 8 syntax)
`using T obj = new T();`

correctly autocomplete: (older syntax)
```
using (T obj = new T())
{
}
```

**Expected Behavior**:
correct auto-completion of T

**Actual Behavior**:
the program doesn't autocomplete after using the new using syntax of c# 8. (without brackets)

**Comment by CyrusNajmabadi** [comment]
tagging @dpoeschl .  Did we miss this during the ide test pass for simple-usings?

**Comment by dpoeschl** [comment]
Note, this only impacts the _first_ T (immediately after `using`), not the subsequent T in the object creation.
