### ISSUE TITLE
Roslyn doesn't detect error and generates a C7038 error: Failed to emit module

### ISSUE THREAD

**Issue by malain** [dotnet/roslyn#40405]
**Version Used**: 
SDK Version: 3.1.100
Windows 10 pro 1909

**Steps to Reproduce**:
1- Use the following code

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```
```
using System;
namespace console1 {
    class ConcreteClass    {
        private ConcreteClass _next;
        public void Foo()   {
            return _next == null ? throw new NotImplementedException() : _next.Foo();
        }
    }
    class Program     {
        static void Main(string[] args)        {
        }
    }
}
```

2- dotnet build

**Expected Behavior**:
Error : CS0127	Since 'ConcreteClass.Foo()' returns void, a return keyword must not be followed by an object expression

**Actual Behavior**:
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 110,44 ms for ...\console1.csproj.
CSC : error CS7038: Failed to emit module 'console1'. [...\console1.csproj]
Program.cs(11,31): warning CS0649: Field 'ConcreteClass._next' is never assigned to, and will always have its default value null [...\console1.csproj]

Build FAILED.

Program.cs(11,31): warning CS0649: Field 'ConcreteClass._next' is never assigned to, and will always have its default value null [...\console1.csproj]
CSC : error CS7038: Failed to emit module 'console1'. [...\console1.csproj]
    1 Warning(s)
    1 Error(s)

**Comment by RikkiGibson** [comment]
This also repros the issue:

```cs
class C
{
    void M1()
    {
        var x = true ? throw null : M2();
    }
    
    void M2() { }
}
```
