### ISSUE TITLE
Introduce constant offered for constant values

### ISSUE THREAD

**Issue by prjm** [dotnet/roslyn#40401]
**Version Used**: 

Microsoft Visual Studio Community 2019, Version 16.4.1

**Steps to Reproduce**:

1.  Declare a constant value
2.  Move the cursor to the name of the constant value
3.  Open "Quick Actions" (CTRL + .)

**Expected Behavior**:

Introduce Constant is not offered (because we already have a constant)

**Actual Behavior**:

Introduce constant is offered

![c](https://user-images.githubusercontent.com/11259216/70870647-22587780-1f96-11ea-83ca-7444fa6650f5.PNG)

**Comment by CyrusNajmabadi** [comment]
Yes, i believe this was explicitly asked for. i.e. internal customers wanted to be able to extract out to a new constant, and then update this point.  i.e. they might to `const string C = V + "whatever"`

**Comment by prjm** [comment]
OK, I can understand how this refactoring can be used.
If this is the intended behavior, then everything is fine and i'll close this issue.
