### ISSUE TITLE
Designer fails to open in VB WinForms with CRLF in text property

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#4040]
Filed on behalf of LMKz from comment on [this blog post](http://blogs.msdn.com/b/somasegar/archive/2015/07/20/visual-studio-2015-and-net-4-6-available-for-download.aspx#10629520).

**Repro Steps:**
Open a form that contains a label that contains crlf in the text property... Designer fails to open with an exception "Could not find type 'Microsoft.VisualBasic.Strings'."

**Comment by davkean** [comment]
I did a quick test for this in VS2015, we seem to roundtrip at least the default code gen (first line below). I also played around with a few variations as well:
```
Me.Label1.Text = "This is the first line" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "This is the second line" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "This is the third lined"
Me.Label1.Text = "This is the first line" & Microsoft.VisualBasic.ChrW(13) & Microsoft.VisualBasic.ChrW(10) & "This is the second line" & Microsoft.VisualBasic.ChrW(13) & Microsoft.VisualBasic.ChrW(10) & "This is the third lined"
Me.Label1.Text = "This is the first line" & Global.Microsoft.VisualBasic.Strings.ChrW(13) & Global.Microsoft.VisualBasic.Strings.ChrW(10) & "This is the second line" & Global.Microsoft.VisualBasic.Strings.ChrW(13) & Global.Microsoft.VisualBasic.Strings.ChrW(10) & "This is the third lined"
Me.Label1.Text = "This is the first line" & Microsoft.VisualBasic.Strings.ChrW(13) & Microsoft.VisualBasic.Strings.ChrW(10) & "This is the second line" & Microsoft.VisualBasic.Strings.ChrW(13) & Microsoft.VisualBasic.Strings.ChrW(10) & "This is the third lined"
Me.Label1.Text = "This is the first line" & Strings.ChrW(13) & Strings.ChrW(10) & "This is the second 
line" & Strings.ChrW(13) & Strings.ChrW(10) & "This is the third lined"
Me.Label1.Text = "This is the first line" & ChrW(13) & ChrW(10) & "This is the second line" & ChrW(13) & ChrW(10) & "This is the third lined"
```
These all roundtrip - looking at the error message, I suspect it might have more to do with project setup. We should probably contact the customer (https://social.msdn.microsoft.com/profile/lmkz/)  to get a better repro.

**Comment by DustinCampbell** [comment]
I've spent a fair amount of time trying to find a repro for this, but have been unsuccessful.

**Comment by davkean** [comment]
@lmkz is on GitHub now, so we can ask. @Lmkz do you have a repro for this?

**Comment by lmkz** [comment]
Hi, last correspondence I had about this was with tatiana.solyanik@microsoft.com:

Hi, I had some email correspondence with Dustin Campbell at MS about this bug, I've emailed him the designer.cs file and the .vbproj file in question. I also can't reproduce it at my end with a new project, presume it is something to do with a project created in an earlier version of VS...

Probably not a biggie as I've just replaced with Environment.NewLine and works fine now.

**Comment by DustinCampbell** [comment]
Thanks @lmkz -- sorry we couldn't get to the bottom of it. Both @davkean and I spent time trying to figure out a repro and I couldn't see anything strange with the .designer file.

**Comment by GregBartlett** [comment]
I know this is resurrecting an old issue, I've been having this same issue with VB winforms using 2019 targeting 4.6.2.  It seems like when I have this issue, something adds back in the Microsoft.VisualBasic reference
![image](https://github.com/dotnet/roslyn/assets/4138091/f003f38e-f89e-4235-8511-c175b0dbe384)
![image](https://github.com/dotnet/roslyn/assets/4138091/49a5dcb0-37c6-4d64-b1db-2b2f04b0ef9e)

As soon as I remove this reference, the designer loads just fine.   

Thought it'd be useful to add this for someone who has the same issue.
