### ISSUE TITLE
RS0022 (DeclarePublicAPIAnalyzer) fires on Roslyn sources

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#4041]
**Repro:** Self build Roslyn.sln with locally built compiler/analyzer toolset.

[`ExposedNoninstantiableTypeRuleId`](http://source.roslyn.io/Roslyn.Diagnostics.Analyzers/R/b9892852f6cc0f98.html) rule fires on the below source files:

```
Desktop\DesktopStrongNameProvider.cs(118,16): error RS0022: Constructor makes its noninheritable base class inheritable, thereby exposing its protected members. [c:\Roslyn\Open\src\Compilers\Core\Portable\CodeAnalysis.csproj]
MetadataReference\PortableExecutableReference.cs(22,19): error RS0022: Constructor makes its noninheritable base class inheritable, thereby exposing its protected members. [c:\Roslyn\Open\src\Compilers\Core\Portable\CodeAnalysis.csproj]

```

/cc @gafter @jaredpar @tmeschter  We need to either fix the analyzer rule or these types (I think it is the later), as this will block the subsequent toolset update.

**Comment by gafter** [comment]
@mavasani @tannergooding The toolset update should now be unblocked.
