### ISSUE TITLE
Switch expression with delegate tuple element in error state causes IDE freeze and crash to desktop

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#40411]
**Version Used**: VS 16.4.1

If you edit the file into this state, or open the file for the first time in this state, the entire IDE will freeze for 5-20 seconds and crash to the desktop.

```cs
using System;

class C
{
    void M(int p)
    {
        var (a, b) = p switch
        {
            // Edit one of the tuple values in the switch
            1 => (new Func<int, int>(n => 1), 42),
            2 => ((n => n), 42),
            3 => ((n => n + 42), 42)
        };
    }
}
```

If `var (a, b)` is replaced with `_`, the problem disappears.

```cs
using System;

class C
{
    void M(int p)
    {
        _ = p switch
        {
            // Edit one of the tuple values in the switch
            1 => (new Func<int, int>(n => 1), 42),
            2 => ((n => n), 42),
            3 => ((n => n + 42), 42)
        };
    }
}
```

**Comment by ryzngard** [comment]
@jnm2  I wasn't able to reproduce this in 16.4.2 or 16.4.3. I didn't immediately see any changes from Roslyn for those iterations, but it's possible a fix went in that resolved this issue. Do you mind testing on either of those versions?

**Comment by jnm2** [comment]
I can confirm that this problem reproduces in 16.4.3. Let me double-check the repro to make sure I didn't leave out something important (last time it was `<Nullable>enable</Nullable>` in the csproj)

**Comment by jnm2** [comment]
Nope, just pasting the top sample into a brand new project without any special settings immediately crashes 16.4.3.

**Comment by jnm2** [comment]
VS does not seem to load netcoreapp3.1 projects with `/safemode`, but I disabled ReSharper and discovered that the problem disappeared. Sorry about that!

**Comment by jnm2** [comment]
Reported to JetBrains through ReSharper feedback tool: https://resharper-support.jetbrains.com/hc/en-us/requests/2451686 (apparently private)

**Comment by jnm2** [comment]
ReSharper ticket: https://youtrack.jetbrains.com/issue/RSRP-477866
