### ISSUE TITLE
Implicit indexing for arrays is inefficient

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#40425]
**Version Used**: sharplab default as of today

https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYAYAEMEBYDcqqMAzNnJgMKYDeqmD2ZOWAMgIYDOwCAFK2G4AeFgD5MEQcAA0mMADtgc+QBMApgA8AlJgC84ydwDaAPQQBdQikZNsCNl2Bx+UkfYNTZCpQvXa9HsaGwAB0lAD2AK6KmAC0mBZWNqR2DtwkvCxG5hKeyj6qmjr6ucZmlvSMKSyYHNy4mfbZpTL5yn7FgcBGwSGsavIA5sAAFnEJFSgAvkA

**Steps to Reproduce**:

Compile the following code in Release:

```
public class C {
    public string Last3(string[] list, int index) => list[^1];
    public string Last4(string[] list, int index) => list[list.Length - 1];
}
```

**Expected Behavior**:

The generated bytecode for `Last3` is the same as the bytecode for `Last4`.

**Actual Behavior**:

The bytecode for `Last3` creates an instance of `System.Index`, and uses that instance to find the effective index. The resulting bytecode is more complex than `Last4`, and the JIT assembly code is also less efficient than the corresponding code produced for `Last4`.

**Comment by Therzok** [comment]
Fixed via https://github.com/dotnet/roslyn/pull/38988

**Comment by jaredpar** [comment]
Closing as this is fixed now.
