### ISSUE TITLE
C# async functions retain local variables beyond lifetime of function

### ISSUE THREAD

**Issue by wernsingj** [dotnet/roslyn#40420]
I was doing memory profiling on our codebase and was surprised to encounter large local variables that were being held onto despite the fact the function should have been out-of-scope. Upon further investigation, I realized this was a side effect of the function being "async". As far as I understand, it seems that when an async function does something truly async, the called async function becomes the caller for purposes of invoking the continuations. An unexpected side effect of this is then the local variables in the async function end up being held onto beyond the expected lifetime of the function (as it is now the bottom frame on the call stack). This behavior happens in both Debug and Release modes.

My question is whether or not this is truly expected behavior and best practices to avoid it. If this is expected behavior, I would suggest it should be documented better. As async functions are commonly used for I/O, it is very common these async functions contain large amounts of transient data that the developer probably wants garbage collected instead of held onto during later stages of the program.

**Version Used**: 
.NET Core 3.1, but older versions also show this issue.

**Steps to Reproduce**:
1. Create an empty C# console project (.NET Core 3.1 or older is fine).
2. Paste the following code and update the "D:\LargeFile.tsv" path to point to an arbitrary semi-large file.
3. Run the code in Debug or Release mode and notice the consumed memory displayed to the Console.

```csharp
using System;
using System.IO;
using System.Threading.Tasks;

namespace AsyncTest
{
    class Program
    {
        // Location of file for which to get file length (should be a few MB to demonstrate problem).
        public const string FileName = @"D:\LargeFile.tsv";

        static async Task Main(string[] args)
        {
            // Get and display the file length async.
            int length = await GetFileLengthAsync(FileName).ConfigureAwait(false);
            Console.WriteLine($"Length of '{FileName}' is {length:#,0} bytes");

            // Garbage collect as much as GC-able objects as possible.
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.WaitForFullGCComplete();
            GC.Collect();

            // Display amount of .NET memory still in-use after garbage collection.
            Console.WriteLine($"Used memory: {GC.GetTotalMemory(true):#,0}");
        }

        public static async Task<int> GetFileLengthAsync(string fileName)
        {
            // Get the length of the file.
            int result = await InternalGetFileLengthAsync(fileName);

            // 1. If this line is uncommented, then "bytes" will be GC'ed.
            //await Task.Yield();

            return result;
        }

        // This function reads all the bytes of the file but just returns the length.
        public static async Task<int> InternalGetFileLengthAsync(string fileName)
        {
            // Load all bytes from file into byte array.
            var bytes = await File.ReadAllBytesAsync(fileName);

            // Return length of byte array.
            int length = bytes.Length;

            // 2. If these lines are uncommented, then "bytes" will be GC'ed. It does not work
            // if you just uncomment one of the following statements.
            //bytes = null;
            //await Task.Yield();

            return length;
       }
    }
}
```

**Expected Behavior**:
Expected behavior is that the "bytes" variable inside "GetFileLengthAsync()" has been garbage collected as the function is no longer in scope. As a result, the consumed memory displayed on the console should be quite small.

**Actual Behavior**:
Actual behavior is that the "bytes" variable inside "GetFileLengthAsync()" is still being referenced on the stack, so the consumed memory displayed on the console is larger than whatever the size of the file pointed to by the path. The fact the variable is still referenced can also be confirmed by taking a memory snapshot at the bottom of the Main() method.

**Comment by jaredpar** [comment]
> Actual behavior is that the "bytes" variable inside "GetFileLengthAsync()" is still being referenced on the stack, 

This is not the case. The generated state machines do hold references to the state machines lower in the stack when an `await` can't complete immediately. Those are all cleared out though once the `await` completes and the method resumes. At the point the `GC` code is running here there is no path to the `InternalGetFileLengthAsync` state machine. If you believe this is in accurate could you list the path which holds this reference?

> The fact the variable is still referenced can also be confirmed by taking a memory snapshot at the bottom of the Main() method.

That is not a definitive way of tracking if a reference is alive or not. That just tracks the memory held by the system.

**Comment by wernsingj** [comment]
Thanks for the reply.  I have tried what you suggested and added a loop around the GC.Collect() and tried the "WeakReference", but the weak reference reports that it is still alive.

Here is the updated code:
```csharp
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace AsyncTest
{
    class Program
    {
        // Location of file for which to get file length (should be a few MB to demonstrate problem).
        public const string FileName = @"C:\Users\John\Downloads\Oct25.doc";

        private static WeakReference bytesReferenced;

        static async Task Main(string[] args)
        {
            // Get and display the file length async.
            int length = await GetFileLengthAsync(FileName).ConfigureAwait(false);
            Console.WriteLine($"Length of '{FileName}' is {length:#,0} bytes");

            for (int i = 0; i < 100; i++)
            {
                // Garbage collect as much as GC-able objects as possible.
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.WaitForFullGCComplete();
                GC.Collect();
            }

            // Display amount of .NET memory still in-use after garbage collection.
            Console.WriteLine($"Used memory: {GC.GetTotalMemory(true):#,0}");

            // Display if still referenced.
            Console.WriteLine($"Is still referenced: {bytesReferenced.IsAlive}");
        }

        public static async Task<int> GetFileLengthAsync(string fileName)
        {
            // Get the length of the file.
            int result = await InternalGetFileLengthAsync(fileName);

            // 1. If this line is uncommented, then "bytes" will be GC'ed.
            //await Task.Yield();

            return result;
        }

        // This function reads all the bytes of the file but just returns the length.
        public static async Task<int> InternalGetFileLengthAsync(string fileName)
        {
            // Load all bytes from file into byte array.
            var bytes = await File.ReadAllBytesAsync(fileName);

            // Keep weak reference to array as well so we can check if alive.
            bytesReferenced = new WeakReference(bytes);

            // Return length of byte array.
            int length = bytes.Length;

            // 2. If these lines are uncommented, then "bytes" will be GC'ed. It does not work
            // if you just uncomment one of the following statements.
            //bytes = null;
            //await Task.Yield();

            return length;
        }
    }
}
```

Here was the output when run in Release mode:
```
Length of 'C:\Users\John\Downloads\Oct25.doc' is 1,911,296 bytes
Used memory: 2,052,176
Is still referenced: True
```

Another observation is that if you place a breakpoint at the end of the Main() method, you can go down the call stack (because InternalGetFileLengthAsync() is still on the call stack) and actually read the contents of the "bytes" variable - so there is definitely some reference to the completed async function state machine being maintained somewhere. Here is a screenshot of reading the contents of the "bytes" variable from a breakpoint at the end of the Main() method.
![Screenshot](https://user-images.githubusercontent.com/54190184/71234068-77550000-22ac-11ea-9bba-b83ed2795cd1.gif)

**Comment by wernsingj** [comment]
Another observation I want to add to my reply above.  When I run the above program, sometimes it reports the "bytes" variable is still alive and sometimes it doesn't.  Whether or not it is still alive is not due to garbage collection though, it seems as though the "await" has some freedom as to when it wants to clear-up the call stack.  Sometimes it clears up the call stack and removes the fact "InternalGetFileLengthAsync()" method is the initiator of the continuation and sometimes it does not.  When it clears up the call stack, only then is the reference to the variable removed.  This behavior can be observed by adding this line `Console.WriteLine(new StackTrace().ToString());` at the end of the Main() method to display the call stack.  Below are two separate runs, compiled in Release mode, and with no other changes made to the code:

```
Length of 'C:\Users\John\Downloads\Oct25.doc' is 1,911,296 bytes
Used memory: 2,052,248
Is still referenced: True
   at AsyncTest.Program.Main(String[] args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at AsyncTest.Program.GetFileLengthAsync(String fileName)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at AsyncTest.Program.InternalGetFileLengthAsync(String fileName)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.IO.File.InternalReadAllBytesAsync(FileStream fs, Int32 count, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
Length of 'C:\Users\John\Downloads\Oct25.doc' is 1,911,296 bytes
Used memory: 140,000
Is still referenced: False
   at AsyncTest.Program.Main(String[] args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Despite the non-determinism, I think the original complaint of my issue still remains as the compiler may unpredictably persist references to local variables beyond the expected lifetime of the function.

**Comment by jaredpar** [comment]
> Despite the non-determinism,  I think the original complaint of my issue still remains as the compiler may unpredictably persist references to local variables beyond the expected lifetime of the function.

The non-determinism is in the GC, not the compiler. The compiler emits the same code and references every time it's run.

**Comment by wernsingj** [comment]
I do not believe the GC is the cause of the non-determinism because, if you refer to my previous reply, the stack trace is different between different runs of the same code.  I think the non-determinism is instead from the task scheduler.  When the task scheduler picks the same thread to run the continuation (which seems to happen most of the time), then you can see the completed async function is still on the stack trace and this is what is causing the (supposedly out-of-scope) local variables to still be referenced.  My belief is further backed by the fact that if you put a breakpoint in the "Main()" method you can actually read the contents of the local variable in the out-of-scope async function (I have a screenshot of that in a prior reply).

**Comment by jaredpar** [comment]
> . I think the non-determinism is instead from the task scheduler. 

That is also a reasonable explanation here. The task scheduler by virtue of picking current thread and executing promptly vs. deferring to the thread pool for scheduling can change the set of values that are strongly referenced on the stack.
