### ISSUE TITLE
Question: Indirect References for a DTO and Entity

### ISSUE THREAD

**Issue by lixaotec** [dotnet/roslyn#40423]
Dear fellows, 

I was wondering if is it possible to create an indirect connection between two properties at different classes, so  Intelisense would recognizes as one for indication 'references count'? (without inheritance or other language feature)

Like (concept):

```csharp
class Person {
  string Name {get; set;}
}


class PersonDto {
  ///<feature-connect>Person.Name</feature-connect> // or any other thing  
  string Name {get; set;}
}
```

So when I see though IDE would appear 1 references at Name property.

How could that be achieved?

Thanks

**Comment by sharwell** [comment]
You can use this:

```
/// <seealso cref="Person.Name"/>
```

**Comment by lixaotec** [comment]
Thanks @sharwell
