### ISSUE TITLE
System.InvalidOperationException: Unexpected value &apos; at  at Microsoft.CodeAnalysis.TaggedTextExtensions.ToClassificationTypeName(String taggedTextTag)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40440]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/847963/systeminvalidoperationexception-unexpected-value-a.html)._

---
The problem happened in  Microsoft.CodeAnalysis.TaggedTextExtensions.ToClassificationTypeName(String taggedTextTag) 
at the time I inserted a certain library assembly name on my code 
it has triggered a yellow banner below top menu ribbon with this error

here is the log

<entry>
    <record>1992</record>
    <time>2019/12/05 18:22:14.016</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.InvalidOperationException: Unexpected value 'ContainerStart' of type 'System.String'&#x000D;&#x000A;   at Microsoft.CodeAnalysis.TaggedTextExtensions.ToClassificationTypeName(String taggedTextTag)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ClassificationExtensions.ToClassificationSpans(IEnumerable`1 parts, ITextSnapshot textSnapshot, ClassificationTypeMap typeMap)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Presentation.SignatureHelpClassifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()</description>
  </entry>

---
#### Visual Studio Feedback System on 12/9/2019, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by valimaties** [comment]
I have the same error, using InformationBox project from GitHub. When Intellisense opens popup, yellow banner shows which shows me a link to the error file, indicating this error:

> System.InvalidOperationException: Unexpected value 'ContainerStart' of type 'System.String'   at Microsoft.CodeAnalysis.TaggedTextExtensions.ToClassificationTypeName(String taggedTextTag)   at Microsoft.CodeAnalysis.Editor.Shared.Extensions.ClassificationExtensions.ToClassificationSpans(IEnumerable`1 parts, ITextSnapshot textSnapshot, ClassificationTypeMap typeMap)   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Presentation.SignatureHelpClassifier.GetClassificationSpans(SnapshotSpan span)   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
> --
>

**Comment by chhornung** [comment]
I just got a very similar error in V 16.8.3 (experimental instance with all third-party extensions disabled) and tracked it down to a very specific situation: It happens when entering a comma in the argument list of an attribute constructor call when the XML doc summary of that constructor contains a bullet list.

Example code to reproduce (I placed this in a new .NET Framework 4.8 C# Console App project):
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp10
{
	class Program
	{
		// Place caret here and delete and re-enter the comma to trigger the error:
		//     v
		[Test(1, 2)]
		static void Main(string[] args)
		{
		}
	}

	class TestAttribute : Attribute
	{
		/// <summary>
		/// <list type="bullet">
		/// <item><description>Item 1</description></item>
		/// <item><description>Item 2</description></item>
		/// </list>
		/// </summary>
		public TestAttribute(int a, int b)
		{
		}
	}
}
```

Error message:
`
InvalidOperationException:
Unexpected value 'ContainerStart' of type 'System.String'
`

Log file attached.
[ActivityLog.xml.log](https://github.com/dotnet/roslyn/files/5787643/ActivityLog.xml.log)

**Comment by naminodarie** [comment]
Is it the same problem as #50114 ?
