### ISSUE TITLE
Roslyn fails to detect null values returned as non-nullable via switch expressions

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#40443]
**Version Used**: 

```
ranch master (14 Dec 2019)
Latest commit e8a539c by Mikayla Hutchinson:
Move breakpoint resolver down into Features (#28321)

* Use embedded resources for ProximityExpressionsGetter tests

* Move breakpoint resolver down into Features
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
using System.Collections.Generic;
public class C {
    public static void Main() {
        var map = new Dictionary<string, string>();
        map.GetOrAdd("", _ => "" switch { _ => null });
        map[""].ToString(); // crash, no warnings
    }
}

internal static class Extensions
{
    public static V GetOrAdd<K, V>(this Dictionary<K, V> dictionary,
                                   K key,
                                   System.Func<K, V> function)
        where K: notnull
    {
        if (dictionary.TryGetValue(key, out var value))
            return value;
            
        value = function(key);
        dictionary[key]  = value;
        return value;
    }
}
```

**Expected Behavior**:
```
Warning [CS8603]: Possible null reference return.
```
reported for `"" switch { _ => null }`

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by alrz** [comment]
I wonder how these issues is found, running R# test suit against Roslyn?

**Comment by jcouv** [comment]
We may need to refresh this issue with a new code sample. The above produces an error ([sharplab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABABixIEYAWAbmJIGZKAmLAYSwG9it+27XkQGisAN2QAnLAFtkABywBeLDAwB3LABEAlgGMALroD2eKQE8APNTIAaSlTIA+ABQBKBiLH95CgHQA4hiGAPJSAILAwK4ARLEOAPoqzljxWADOGrqG+gAWPFjJyqnwSFgAvp5YAPQ1OFJSJjIcAMoAHACsZABsIFgAciZYqBgZhliGFgrYGsgZWABmJnAwwEvNk3nYWTn5OAAeClJjGaYw/nw+cooA2vEAuv4AKiathlK6MADmHnS19X0UnmeQcMGGcykMC+3wyV34FWIiKIxC+hgwUOQCEcPTYWAAogd0TAzmY4URhKJmDisAA1LDBMKRaJWADSDlpbkMeV0Cz0RnO0ms7LpqWABmMZiFdnh1zl8rlrKwAGsMBYZd4FVrtdR/CROmyOalFqsBWZ3LLRBpticsKz+uDDGUELLKdddIssK5xWbzBYXpZGbSsXAMK5VeqsCsJpIZJIEKH3BbNfKSAB2CQhjBebWWgTx0MqJamyUwcNqzx5/g+0tC24Rh78VQF7NVygZls5gTIipAA==)): "error CS8506: No best type was found for the switch expression."

When I tried to tweak the code sample, I got a nullability warning as I expected (ie. on the `map.GetOrAdd` invocation).

**Comment by TessenR** [comment]
@jcouv You can now use the original example again. Master branch is required instead of default for your sharplab link in the comment above to compile the code sample.

Pretty sure there were some changes earlier as I remember tinkering with the example when you posted the comment and didn't manage to get incorrect results back then.

However, as of now it again doesn't warn and crash with a NullReferenceException.

**Comment by RikkiGibson** [comment]
This scenario now reports the expected warning on [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFAACADIdQIwAsA3FdQMwMBMhAwoQDeVQmN58RlcTMIA3CAkKQADoQC8hNHADuhACIBLAMYxDAe1IIAngB4mtADQNGtAHwAKAJTtpssaoAdADicDAA8ggAggAmMR4ARAnOAPoaboRJhFA6hjDGABbChGnqGZg4hAC+PqL+yhAqANpJALqBACrmAMowCIZoAOberIQA9GOExgjQBc5o5oQ6imgDg1B1YlVU25RUA/AIpFguAGy8hACiAB7waFAW91RSMlxnhABqhKER0XG2AGlnB9PDACoYoAYTGZLIo7EDPhkYtDHnDHJt6pisZiAYQANZwazovzY0lkpiBagAVkBwIyADMMGhTI8vBiZDoCogiACQFpzDAKlgMS96oZ6YQPMiWbCbJ0bD8PhAsBg4B4CUTCOYMDB5Io9Sq4F42SSsdQAOwG1W+Mns8QKQ0aQiM5kwtDqwm1U0yaVuuFNDWtMSaB3Wu1iC1WuA28S7KpAA===).
