### ISSUE TITLE
`Else` not offered in VB Completion after `Exit For`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40449]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/847080/vbnet-else-randomly-missing-in-intellisense.html)._

---
[regression]
Over the last few weeks, the ELSE part of an IF ELSE statement has gone missing in intellisense.
If adding ELSE to an existing logic check, it is not present.  When creating a new IF ELSE statement it is there as normal.

Please see video.

---
#### Visual Studio Feedback System on 12/9/2019, 03:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dpoeschl** [comment]
Simple standalone repro, where `Else` is not offered at the $$

```VB
Class C
    Sub M()
        For Each x In {}
            If True Then
                Exit For
                $$
            End If
        Next
    End Sub
End Class
```

**Comment by dpoeschl** [comment]
This fails in Visual Studio 2017 as well.

**Comment by CyrusNajmabadi** [comment]
Closing as we haven't heard any more feedback on this and this is not an area we are investing in.
