### ISSUE TITLE
Using the non-obsolete constructor of SuggestedActionsSource throws an exception

### ISSUE THREAD

**Issue by LaraSQP** [dotnet/roslyn#40458]
There is an error in the title. It should read **SuggestedActionSet** not _SuggestedActionsSource_. 

So, turns out that using the **obsolete** constructor of **SuggestedActionSet** is the only way to avoid the following exception.

> System.InvalidOperationException: Can only compare ISuggestedActionCategories defined with SuggestedActionCategoryRegistryServiceat Microsoft.VisualStudio.Language.Intellisense.Implementation.SuggestedActionCategoryComparer.Compare(String x, String y)at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultLightBulbPresenterDefaultIconUIElementProvider.GetUIElement(ISuggestedActionCategorySet itemToRender, ILightBulbSession context, UIElementType elementType)at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb..ctor(LightBulbSession session, LightBulbPresenterStyleFactory presenterStyleFactory)at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTagger.<Microsoft.VisualStudio.Text.Tagging.ITagger<Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTag>.GetTags>b__10_1()at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTag.get_Glyph()at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbGlyphFactory.GenerateGlyph(IWpfTextViewLine line, ISuggestionTag tag)at Microsoft.VisualStudio.Text.Editor.Implementation.CanvasAndGlyphFactory`1.GenerateGlyph(IWpfTextViewLine line, ITag tag)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMarginVisualManager`1.AddGlyph(TGlyphTag tag, SnapshotSpan span)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.RefreshGlyphsOver(ITextViewLine textViewLine)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

This is a breaking change.

Let me know if you need more details.

**Comment by CyrusNajmabadi** [comment]
This doesn't appear to be a roslyn issue.  @olegtk can you get this to the relevant team?

**Comment by LaraSQP** [comment]
Good point.

Could you please give me a url to the repo or whatever that applies?

Much appreciated.

**Comment by CyrusNajmabadi** [comment]
@LaraSQP I don't believe it is public.  I've paged someone from an internal VS team to take this bug and migrate to their system.  Thanks!

**Comment by LaraSQP** [comment]
Figures.

**Comment by olegtk** [comment]
@LaraSQP, please file a bug via https://developercommunity.visualstudio.com please. Thanks!

**Comment by LaraSQP** [comment]
No can do, I'm afraid. Have no Microsoft account or plans for one.

Link here (github) and ask away. That's my best.

**Comment by olegtk** [comment]
ok, then file it on https://github.com/microsoft/vs-editor-api and I will route it internally.

**Comment by LaraSQP** [comment]
There you go.

https://github.com/microsoft/vs-editor-api/issues/20#issue-540117959
