### ISSUE TITLE
DiagnosticAnalyzers depend on receiving WorkspaceAnalyzerOptions

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#40463]
For dotnet-format running CodeStyle diagnostic analyzers without IVTs is impeded because they all expect to be able to pull an OptionSet out of their AnalyzerOptions. This uses an extension method which only works when the AnalyzerOptions is an instance of WorkspaceAnalyzerOptions.

Now that the compiler reads .editorconfig documents, Option values can be retrieved from AnalyzerConfigOptions if they are stored in the .editorconfig file.

Fixed by https://github.com/dotnet/roslyn/pull/38675

**Comment by CyrusNajmabadi** [comment]
can we take thsi one step further?  can the IDE place all options in this bag, even if they don't have editor_config equivalents?  @jasonmalinowski ?  It would be great for breaking the dependency on these features with the Workspace.  Thoughts?

**Comment by jasonmalinowski** [comment]
@JoeRobich and I were chatting on that other PR and we weren't sure why we still have analyzers using options that _aren't_ representable in .editorconfig, since that implies we can't ever run them in a build and be able to configure those. So we may have to just do that audit first.

**Comment by JoeRobich** [comment]
This is resolved by https://github.com/dotnet/roslyn/pull/38675
