### ISSUE TITLE
Add EditorConfigStorage to Options used by Analyzers and CodeFixes

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#40464]
Created from comment: https://github.com/dotnet/roslyn/pull/38675/#discussion_r358426076

Some DiagnosticAnalyzers retrieve an OptionSet only to pass it into Code Generation and Simplification services. These services then request values for Options which do not have EditorConfigStorage. To make these analyzers and code fixes useful without having a Workspace Options fallback, we need to add EditorConfigStorage so they can be configured in .editorconfig files.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative, and given that we heavily refactored these areas.
