### ISSUE TITLE
Possible memory leak in Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Helpers

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#40478]
I had my VS crash due to an OOM, and looking at the dump I don't see anything terribly suspicious but I do see there are more Solution objects in memory than I'd expect, i.e. there's not just CurrentSolution being held. The path to the root is listed as:

```
Microsoft.CodeAnalysis.Solution    <0xEF1BAC9C> 
Microsoft.CodeAnalysis.Project    <0xEF1BACAC> 
Microsoft.CodeAnalysis.Document    <0xEF1BACF0> 
Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Helpers+<>c__DisplayClass1_0    <0xEF227D58> 
Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Helpers+<>c__DisplayClass1_1    <0xEF227DC8> 
Action    <0xEF227DD8> 
Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.HyperlinkHelper+<>c__DisplayClass0_0    <0xEF229CC0> 
```

and there's a few being held that way. This looks like it's something for clickable quick info -- do we have a leak or something where we sometimes leak Solutions? I would have assumed that those practically always pointed to the CurrentSolution of the main workspace since there's no other editing or asynchrony happening...?

Dump at ``\\mlangfs1\public\jasonmal\Dumps\Roslyn\40478``.

**Comment by genlu** [comment]
I think this is fixed in https://github.com/dotnet/roslyn/pull/50849
