### ISSUE TITLE
[Proposal] Freeze operator

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#4047]
Freeze operator can be used to prevent further changes of variable.
Example
```
static void Func(bool something)
{
    int i = 0;
    
    if (something)
    {
        i = 10;
    }
    else
    {
        i = 15;
    }

    freeze i;

//    i += 1  // Compilation error, because i has been frozen
}
```

**Comment by HaloFour** [comment]
How would that work with conditionals?

```cs
int i = 0;
if (something) {
    i = 10;
    freeze i;
}
else {
    i = 15;
}
i += 1;  // is this a compiler error?
```

**Comment by KalitaAlexey** [comment]
This is ambiguous. That's must be forbidden to freeze variable inside branch and then attempt to use it outside of branch

**Comment by MgSam** [comment]
Are there really a lot of scenarios where you would want to unconditionally freeze the state of a local variable after using it for a while? If you're running into this problem frequently maybe your methods are too long.

**Comment by KalitaAlexey** [comment]
@MgSam 
At first since C# doesn't support readonly arguments freeze operator may be used to freeze arguments to prevent some errors.
At second sometimes I have a variable which value I want to freeze after I have assigned a value to it.
Example
```
int i = 0;

if (something)
{
    i = 10;
}
else if (somethingElse)
{
    i = 20;
}

freeze i;
```

**Comment by dsaf** [comment]
@KalitaAlexey 
> At first since C# doesn't support readonly arguments freeze operator may be used to freeze arguments to prevent some errors.

I was under impression that this feature is in the works - the infamous ```let``` keyword.

**Comment by KalitaAlexey** [comment]
@dsaf let keyword is the best option. I've rethink about freeze and it is nonsense operator
