### ISSUE TITLE
code clean up is not working on all instances

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40480]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/855103/code-clean-up-is-not-working-on-all-instances.html)._

---
For example the this preference rule is not getting applies for simplifies object initialization case.

It is not adding this for the following usecase:

All the thisClass properties should have a this qualifier if the code cleanup worked.
            SomeClass myClass = new SomeClass
            {
                ClassProp1 = thisClassProp1,
                ClassProp2 = thisClassProp1,
                ClassProp3 = thisClassProp1,
                ClassProp4 = thisClassProp1,
            };

---
#### Visual Studio Feedback System on 12/12/2019, 10:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
