### ISSUE TITLE
Navigation on a project diagnostic should open the project file

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40482]
**Version Used**: 
16.5.0 Preview 2.0 [29615.19.master]

**Steps to Reproduce**:

1. Add a linked file entry to a project whose target file does not exist.
2. Build the project
3. Double-click on the reported error in Error List

**Expected Behavior**:

The project file is open.

**Actual Behavior**:

Nothing happens.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.
