### ISSUE TITLE
VB.Net nullable enum intellisense not suggesting the enum

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/853060/vbnet-nullable-enum-intellisense-not-suggesting-th.html)._

---
Hi,

If you have a nullable property or argument, the intellisense will not suggest the enum values as it normally does when the property or argument is not nullable.

I tested with C#, it correctly suggest the enum on both nullable and non-nullable properties.

Please see attached gif file for the reproduction.

Tested on:
Microsoft Visual Studio Professional 2019
Version 16.4.1

Thanks

---
#### Visual Studio Feedback System on 12/12/2019, 00:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/18/2019, 03:05 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by dpoeschl** [comment]
Expected (matches what you see in VB when the type is non nullable):

![image](https://user-images.githubusercontent.com/235241/71199475-e0a42700-224a-11ea-8ee5-ac2fe149c54f.png)

Actual (when the type is nullable):

![image](https://user-images.githubusercontent.com/235241/71199366-a63a8a00-224a-11ea-875d-72cbc3c6f0bd.png)

**Comment by CyrusNajmabadi** [comment]
Not repro for me, it recommends ConsoleColor as expected:

![image](https://user-images.githubusercontent.com/4564579/219786857-0c93b511-4392-47fb-8141-bd2cc4397b8d.png)
