### ISSUE TITLE
Need GetRequiredOperation helper

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#40505]
The IDE / workspaces layer needs a helper method for `SemanticModel.GetOperation` that has a non-null return. This will avoid the use of null-suppression in a number of places in favor of a declarative helper method.

**Comment by jasonmalinowski** [comment]
@jaredpar: do you imagine adding the helper to the compiler or us just having an extension method?

**Comment by jaredpar** [comment]
At this point just thinking about extension method as that's how we've seemingly solved similar cases.

I do think once we get further along in nullability, perhaps when one assembly is fully annotated, we should start looking at this IDE helpers and seeing if we should make them first class APIs.

**Comment by CyrusNajmabadi** [comment]
This exists now: 

![image](https://user-images.githubusercontent.com/4564579/219786986-cf64f1ed-c1ce-45a8-8ca8-e4c77ac3624a.png)
