### ISSUE TITLE
VS2015 SDK not available

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4051]
https://github.com/dotnet/roslyn/wiki/Getting-Started-on-Visual-Studio-2015 states that install of "Visual Studio 2015 SDK" is required (and links to https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx), but the page it links to does not contain a download link for the SDK.

**Comment by bkoelman** [comment]
During install of Community Edition, I selected Custom install and checked "Visual Studio Extensibility Tools". Then installed ".NET Compiler Platform SDK" from the instructions above. It installed successfully. Next, I created a new Analyzer project, F5. In the second instance, I see the squiggles appear from the Uppercase analyzer, so all seems to work without installing the SDK from step 2.

**Comment by Pilchie** [comment]
Yeah, we should update the instructions there.  Checking "Visual Studio Extensibility Tools" installs the SDK for you.

**Comment by jmarolf** [comment]
@bkoelman let me know if https://github.com/dotnet/roslyn/wiki/Getting-Started-on-Visual-Studio-2015 makes sense, and I'll close this issue.

**Comment by jmarolf** [comment]
Actually, I'll close it, and you can tell me if I missed something and need to reactivate it :smiley:

**Comment by bkoelman** [comment]
Step 1 makes me think Professional edition is not supported, but it is,
right?

Step 3 I did not install C++, is that required?

For the rest, LGTM

**Comment by bkoelman** [comment]
Also, the screenshot has extra Github option checked, but it is not
mentioned in the text.
