### ISSUE TITLE
Generic fields are treated as Properties

### ISSUE THREAD

**Issue by pjc0247** [dotnet/roslyn#40520]
**Version Used**: 

**Steps to Reproduce**:

https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABATARgLACgUAYACFDAFgG5dcUBmYtYjAdkIG9dDPi6SA2QgCIBLAMbAhAewB2YAE4BPADwl80RvgB8hAA6yJ2wgF5CUgKYB3QaPHS5SlWpUaAFAEpKOLt0b8AqlIBrKQlzKQBxUzNZUWUMVXUtADMAG1gjEwtCfyCQ8MjTaJFY+Kc3Dy9cAHpKwkhYRI4uWh9iUkIAMQkJNzZGr05dfQBtACIwEYBddLGR8v7OFNhR8anp8bnOAF9cTaA=
```cs
using System;
using System.Collections.Generic;

public class Program {
    public static Dictionary<string, string> prop = new Dictionary<string, string>();
    public static UnknownGeneric<string, string> fld = new UnknownGeneric<string, string>();
    
// asdf
    public static void Foo() {
        prop["a"] = "a";
        fld["a"]  = "a";
    }
}
```

**Expected Behavior**:

`prop` should be treated as a field.

**Actual Behavior**:
`Dictionary<,>` is parsed into a __Property__ even though it never be declared as a Property.<br>
However, Unknown generic type is parsed into a __Field__ which doesn't make any consistency.

![image](https://user-images.githubusercontent.com/1961216/71220579-6045fa80-230c-11ea-872d-52bc904d7ed4.png)

__prop__
![image](https://user-images.githubusercontent.com/1961216/71220544-3d1b4b00-230c-11ea-8d72-0067b7066259.png)

__fld__
![image](https://user-images.githubusercontent.com/1961216/71220742-009c1f00-230d-11ea-85fc-fd2a389149ba.png)

**Comment by CyrusNajmabadi** [comment]
The property-reference is there because the *indexer* of Dictionary is being accessed.  Indexers are just properties, so this is expected.

With the UnknownGeneric, the compiler has no idea what is going on, so you're getting the error recovery logic doing its best guess as to what's going on.

**Comment by pjc0247** [comment]
@CyrusNajmabadi Thanks. It totally makes sense. but makes me writing more codes.
