### ISSUE TITLE
[Proposal] Property/Event scoped fields

### ISSUE THREAD

**Issue by mburbea** [dotnet/roslyn#4052]
#### Property scoped fields and Event scoped fields

This is a breakout from the discussion I started in #4025.
A Property/Event scoped field is a field that can be declared inside the block of a property or an event. (from herein I will simply refer to properties, however, everything mentioned below follows without loss of generality for events).
Currently, properties are an abstraction and a sugar around fields, that dictate how to access and modify a field. This allows you to add custom logic to the getting and setting of an object. Namely, lazy initialization and argument validation, as well as implementing the observable pattern used in frameworks like WPF.
```csharp
private SomeObj _field;
public SomeObj Property
{
       get
       {
          return  LazyInitializer.EnsureInitialized(ref _field, DefaultInitializer);
       }
       set
       {
             if (value == null) throw new ArgumentNullException(nameof(Property));
             if (IsValid(value)) throw ArgumentException("SomeObj is not properly initialized", value);
             _field = value;
             NotifyPropertyChanged(nameof(Property));
       }
}
```
However, with the current implementation, I can still access the naked field. If I want, I can get `_field` before it has been assigned and suffer a `NullReferenceException`. I can modify the field, and set it to an invalid state, or by pass the notification step.

The proposal here, is to allow the declaration of fields inside the block. This will encapsulate the fields and will allow the fields to only be accessed within the scope of the property. Any number of fields may be declared in a properties scope. It is legal to declare two separate property scoped fields with the same name. e.g. 
```csharp
public SomeObj Property
{
      SomeObj _field;
      //
}

public SomeObj Property2
{
      SomeObj _field = new SomeObj(...);
      //
}
```
It will be an error for any method or constructor to access the `_field`.
A property scoped field may be declared static or instance specific. However, it is only legal to declare an instance field in the scope of an instance property. The syntax will make no assumption about the expected staticness of the field, and will require declaring a field to be static.

A property scoped field may only declare the visibility modifier of `protected` or `private`, and will by default be assumed to be `private` (like normal fields). 

A property scoped field can also be declared volatile, and it will be legal to place attributes on the field. Effectively, it may be used like a normal field with only the restrictions of visibility and scope.

##### Open Questions
1. cardinality of fields
I personally think there should be no restriction on the number of fields in a single properties scope, but this does lead to some question as to why you might need more than one. Should this be restricted?

2.`readonly`  
there might be a need to assign a property scoped field from the (static) constructor of a class. While it will be legal to call the setter, there may be a desire to only allow setting the field(s) from the constructor. If there are multiple fields in the property scoped field, how would one go about assigning them in an unambiguous fashion?
3. `struct`
A struct type may have difficulty using them with constructors as you must ensure all fields are assigned. While certainly this completely bizarre pattern works, it is not ideal.
```csharp
public Struct MyStruct
{
      private double Baz{...}
      public int Foo
      {
            int foo;
            get{...}
            set{...}
      }
      public MyStruct(double baz){
             this =default(MyStruct);
             this.Baz = baz;
      }
}
```

**Comment by bbarry** [comment]
dupe? #850

**Comment by mburbea** [comment]
Oh yeah, that is a good proposal. I'll close this one.
