### ISSUE TITLE
Incorrect parameter reference in template code

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4054]
After internal fixes for #2940, VS2015 RTM contains the following code in `{AnalyzerName}.Test\Helpers\DiagnosticResult.cs `:

```csharp
            if (column < -1)
            {
                throw new ArgumentOutOfRangeException(nameof(line), "column must be >= -1");
            }
```

Note the mismatch between `nameof(line)` and the parameter being validated, which is `column`.

**Comment by jmarolf** [comment]
This has been fixed internally.  I'll reply back here when I can give you a VSIX to test.
