### ISSUE TITLE
Show the block declaration when locating the matching bracket via Ctrl+]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40567]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/864077/show-the-block-declaration-when-locating-the-match.html)._

---
When I locate a matching curly bracket via Ctrl+] the text editor scrolls to the line where the bracket resides, but usually I have to scroll a little bit to understand what type of block I'm seeing: is it a cycle, a method declaration, etc.

On the screenshots attached:
1) the cursor is somewhere in the code at the closing curly bracket
2) I press Ctrl+] and the cursor moves to the matching opening curly bracket, but I have to scroll up to understand what type of block it is;
3) I would like this scroll to happen automatically after I click Ctrl+] at step 2) to show me where I am after moving to the matching bracket

---
#### Visual Studio Feedback System on 12/20/2019, 01:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is taken care of with sticky-scroll: 

![image](https://user-images.githubusercontent.com/4564579/219788263-9dc6ff22-2cdc-42f3-a5ac-516b3ab1dfc1.png)
