### ISSUE TITLE
Is there a API that allows .dll files to be translated into SyntaxTree?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#40579]

**Comment by huoyaoyuan** [comment]
There can't be. Conversion from source code to dll is one way and loses information.
Converting from dll to SyntaxTree is the core component of **decompiler**, just without transforming to textual code.

**Comment by NMSAzulX** [comment]
@huoyaoyuan 3Q，DLL这种看样子只能去看看dnspy了。不知道roslyn有没有这方面的计划。

**Comment by gafter** [comment]
No, there is no decompiler that is part of Roslyn.
