### ISSUE TITLE
[Bug/Question] VS2015 RTM no longer finds dependencies of analyzer assemblies

### ISSUE THREAD

**Issue by axel-habermaier** [dotnet/roslyn#4057]
The following worked with all previous versions of VS2015, but no longer works with VS2015 RTM: I have an assembly A that contains various C# analyzers, referencing version 1.0.0 of the ``Microsoft.CodeAnalysis.CSharp`` nuget packages. It references assembly B that contains some supporting code. Both A and B lie at the same location on the disk, i.e., in the same directory. When I reference A as an analyzer assembly in some C# project, VS2015 RTM shows the following warning:

``Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Users\Axel\Documents\Visual Studio 2015\Projects\ClassLibrary4\ClassLibrary1\bin\Debug\ClassLibrary1.dll' depends on 'ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' but it was not found. Analyzers may not run correctly.	
``

Consequently, the analyzers in A are not working. Is that scenario no longer supported or is it a bug?

**Comment by axel-habermaier** [comment]
A possible workaround seems to be to _additionally_ add assembly B as an analyzer reference, even though B does not contain any analyzers. Is that how it is supposed to work?

**Comment by tmeschter** [comment]
@axel-habermaier That is how it is meant to work, yes. By requiring that dependencies be specified we can ensure that builds are consistent (that is, do not happen to depend on the order in which dependencies are loaded) and that we're really loading the dependencies specified (rather than a different copy of a library that just happens to have been loaded for some other purpose).

**Comment by axel-habermaier** [comment]
@tmetscher: Thanks for the info. While it makes sense, the behavior is still surprising and inconsistent with how references normally work. I therefore suggest to rephrase the warning so that it gives a hint to a possible solution to the problem, something like:

``Warning MissingAnalyzerReference Analyzer assembly 'C:\Users\Axel\Documents\Visual Studio 2015\Projects\ClassLibrary4\ClassLibrary1\bin\Debug\ClassLibrary1.dll' depends on 'ClassLibrary2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' but it was not found. Analyzers may not run correctly until you explicitly add the required assemblies as analyzer references as well.``
