### ISSUE TITLE
C# Nullable - Inconsistent validation or by design?

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#40584]
In a piece of code where the C# nullable types have been turned on [in this case, I have done it at the project level by setting `<Nullable>enable</Nullable>`. Things work fine all over the place, but I have noticed some irregularities. For example, consider this block of code:

```
public void Foo(SomeEnumType e, string? nullableStringValue) 
{
     if ((e == SomeEnumType.Value1) && (nullableStringValue == null)) 
     {
          throw new ArgumentNullException(nameof(nullableStringValue));
     }

     string bar = e switch 
     {
          SomeEnumType.Value1 => nullableStringValue

          // other things to do with the other values

         _ => "Unknown context"
     }
}
```

Now, since we have already checked for `null` when `e` is `SomeEnumType.Value` before the switch statement, I do not expect to get a squiggle / error on the line inside the switch statement where the `nullableStringValue` is being dereferenced. 

However, there **is** a squiggle and an error there! 

Is this a bug or is this by design?

**Comment by huoyaoyuan** [comment]
It should be by design. The compiler cannot remember complex conditions between blocks. Refactor it to make checks nested so that compiler can remember nullable information based on scopes.

**Comment by sujayvsarma** [comment]
So the fix would be to move the null check inside the switch? The problem with that would be that if the switch is many statements below the argument validation block, then it is invalidating an argument value at that point may no longer make sense ?

Another option would be to toggle the nullable feature off exactly around the switch.

Which one do you think is better?



- Sent from mobile. Pardon typos.

On Dec 26, 2019 10:47, Huo Yaoyuan <notifications@github.com> wrote:

It should be by design. The compiler cannot remember complex conditions between blocks. Refactor it to make checks nested so that compiler can remember nullable information based on scopes.

**Comment by huoyaoyuan** [comment]
It depends on your preference and code flavor. Generally toggling nullable feature should be avoided unless extremely necessary, like `IEquatable<T>` previously.
If handling of null is simple, `?? throw` or `?? "Default"` won't add a lot of noise.

**Comment by sujayvsarma** [comment]
Makes sense. thank you for the quick reply.

Please close this item.


- Sent from mobile. Pardon typos.

On Dec 26, 2019 11:12, Huo Yaoyuan <notifications@github.com> wrote:

It depends on your preference and code flavor. Generally toggling nullable feature should be avoided unless extremely necessary, like IEquatable<T> previously.
If handling of null is simple, ?? throw or ?? "Default" won't add a lot of noise.

**Comment by sujayvsarma** [comment]
@huoyaoyuan . I found one more of this strange validation "gap". See attached screenshot.

![image](https://user-images.githubusercontent.com/7371750/71616046-375e1900-2bda-11ea-9518-ad5e5d3e2729.png)

**Comment by huoyaoyuan** [comment]
Similar issues happen on other ways testing bools/nullable bools, like `?? false`.
Currently, the compiler supports ?: but not switch expression on bools. See https://sharplab.io/#v2:D4AQTAjAsAUAxAOwK4BsUEMBGKCmACHBLXWEAZj3DwGE8BvWPJyikAFjwFkAKAZQBcATgEsEAcwD8eANYBKRswYxmKvADd0gvAGM8AXkoQADADoAkgGcAcqhQB5QQHUAFsP45eAB3Tac3OXgWAO5u2s4KqvQRkcxCSPh6AHx4RgA00TF4AGboKBYJydImADKEYvzhyjEAvgDcGcwNTBpa2mD6hqaWNmgOLm4e3r7+shJGAFxFpeIV9VVM1bDVQA= .
