### ISSUE TITLE
Use Implicit Type refactoring may break nullability

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40594]
**Version Used**: 
Version 16.5.0 Preview 1.0 [29501.166.master]

**Steps to Reproduce**:

```C#
#nullable enable

using System;

class Program
{
    static void Main(string[] args)
    {
        string? s = "abc";
            
        if (args.Length > 0)
        {
            s = null;
        }

        Console.WriteLine(s);
    }
}
```

**Expected Behavior**:

Refactoring is not offered if the nullability of the inferred type doesn't match the explicit type.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/71471933-f8d6f180-27c8-11ea-974a-81b29e40b088.png)

**Comment by sharwell** [comment]
No change should be necessary here once #40755 is merged.

**Comment by CyrusNajmabadi** [comment]
This now works as intended as hte language always thinks of 'var' as nullable, and uses flow analysis to ensure that it is used properly.
