### ISSUE TITLE
Add refactoring to annotate TryGetXxx method out params with NotNullWhen(true)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40593]
When annotating code with nullable annotations it would be useful if the IDE offered a refactoring to add `NotNullWhen(true)` on all `out` reference typed parameters of a method that has signature `bool TryGetXxx(…, out p1, … out pn)`. The refactoring should also make the parameters nullable if they are not yet (add `?`).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
