### ISSUE TITLE
how to multiple edit document in  a CodeFixProvider

### ISSUE THREAD

**Issue by w371987114** [dotnet/roslyn#40598]
#### Analyzer package

Microsoft.CodeAnalysis.Analyzers

#### Package Version

v2.6.2

#### Repro steps
I create a `CodeFixProvider` to  move `Message.Show()` text to another *.cs file
Now I can add the property to the current file;it looks like this:
![image](https://user-images.githubusercontent.com/17959236/71390606-f4310280-263b-11ea-8a42-2caa4275ee7b.png)

follow this guid [applying-multiple-changes-to-a-solution-in-roslyn](https://stackoverflow.com/questions/31481251/applying-multiple-changes-to-a-solutio),I try to use `Workspace.TryApplyChanges()`, but I got `TryApplyChanges cannot be called from a background thread` error ,then I know It is normal for fix this error [Calling TryApplyChanges from a background thread explodes in hard-to-understand ways #17782](https://github.com/dotnet/roslyn/issues/17782)

And Now,I want to know,is there a way to edit another `*.cs` file in a `CodeFixProvider`?
I wish the preview changes can show all the changes

**Comment by mavasani** [comment]
@w371987114 `workspace.TryApplyChanges` is not meant to be called from a CodeFixProvider. You instead want to use a [SyntaxEditor](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Editing/SyntaxEditor.cs,6b0ef9b1d0beaf05), apply multiple edits using this editor and then invoke editor.GetChangedDocumentAsync() to get the new document with multiple edits.

**Comment by CyrusNajmabadi** [comment]
I think they want to edit multiple files.  In which case, you should return a properly updated `Solution` from the code action instead of just updating a `Document`.

**Comment by mavasani** [comment]
Ah thanks @CyrusNajmabadi - I misread the question as multiple edits to the same document.

**Comment by w371987114** [comment]
CyrusNajmabadi is right
So, is there a way to edit another document in a `CodeFixProvider`?
and the preview changes form can see all the changes of document in the project

**Comment by sharwell** [comment]
@w371987114 When you register the code fix, have it return a `Solution` instead of a `Document`. The updated solution may contain changes to any number of documents. The automatic preview will only show the changes to the first document, but if you click **Preview changes** it will show all changes.

**Comment by w371987114** [comment]
> @w371987114 When you register the code fix, have it return a `Solution` instead of a `Document`. The updated solution may contain changes to any number of documents. The automatic preview will only show the changes to the first document, but if you click **Preview changes** it will show all changes.

`sharwell` gave me a right answer,`CodeAction.Create` has a overload method with `Func<CancellationToken,Task<Solution>> ` parameter, It can register solution CodeFix.
my code is like this:
```c#
    public class MyAnalyzerCodeFixProvider : CodeFixProvider
    {
        public sealed override async Task RegisterCodeFixesAsync(CodeFixContext context)
        {
            ....
            context.RegisterCodeFix(
                CodeAction.Create(title, c =>
                    FixRegexAsync(context.Document, variableDeclare, c), equivalenceKey: title), diagnostic);

        }
        private async Task<Solution> FixRegexAsync(Document document,
            InvocationExpressionSyntax invocationExpr,
            CancellationToken cancellationToken)
        {
            ....
            var solution = document.Project.Solution;
            var cultureDocument =
                document.Project.Documents.FirstOrDefault(c => c.Name == "CultureMessageText.cs");
            if (cultureDocument == null) return document.Project.Solution;
            var cultureRoot = await cultureDocument?.GetSyntaxRootAsync();
            if (cultureRoot == null) return document.Project.Solution;
            ....
            solution = solution.WithDocumentSyntaxRoot(document.Id, newRoot);
            solution = solution.WithDocumentSyntaxRoot(cultureDocument.Id, cultureRoot);

            return solution;
        }
   }
```
