### ISSUE TITLE
Missing nullability warning

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#40597]
**Version Used**: 
Version 16.5.0 Preview 2.0 [29625.16.master]

**Steps to Reproduce**:

```C#
#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;

class Program
{
    static ImmutableArray<string> F() => default;

    public static void Z<T>(IEnumerable<T> a, ImmutableArray<T> b, Func<T, T, bool>? c = null)
    {
    }

    static void Main()
    {
        Z(new[] { "a", null, "c" }, F());
    }
}

```

**Expected Behavior**:

Warning CS8620.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/71485077-58ec8880-2807-11ea-8e41-0541058f0826.png)

![image](https://user-images.githubusercontent.com/41759/71485088-60ac2d00-2807-11ea-8ff4-b3d6c4d122a8.png)

![image](https://user-images.githubusercontent.com/41759/71485017-175bdd80-2807-11ea-90db-94f58b45a2bd.png)

BTW, if `c` is passed `null` explicitly at the call-site the result of the type inference changes and the warning is displayed.

![image](https://user-images.githubusercontent.com/41759/71485161-a5d05f00-2807-11ea-9b95-02825d62b2fa.png)

**Comment by jcouv** [comment]
It looks like we fixed this problem.
``` chsarp
#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;

class Program
{
    static ImmutableArray<string> F() => default;

    public static void Z<T>(IEnumerable<T> a, ImmutableArray<T> b, Func<T, T, bool>? c = null)
    {
    }

    static void Main()
    {
        Z(new[] { "a", null, "c" }, F()); // warning CS8620: Argument of type 'ImmutableArray<string>' cannot be used for parameter 'b' of type 'ImmutableArray<string?>' in 'void Program.Z<string?>(IEnumerable<string?> a, ImmutableArray<string?> b, Func<string?, string?, bool>? c = null)' due to differences in the nullability of reference types.
    }
}
```
([sharplab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWAChiABAJgEYyAGLUygFgG5b7KA6AYQHskMAxgBcAljxgBnDgEkAtrLhD8GViSIV2AdmIBvYlgPsAbFjkKl6DAEEATjeQBPADwMaAPiwAxABQBKLAC8HsAYAGbIiEKq+oakAMzG9IxYAFpOACpu3gxxGR7IADSm8orKtvbOmVioRaQArBlF6UWoPHxuAPxYAoFY8Ei+MQZ6RIZYAL7EQ4mkyQCyyCIwftMjY2Mp3jAYAO4A2gC6WDpYAETIp0X9CEWnAqcTRT6+vsxYAPTvWDvINjBLAHMsFwAMoADiM5BoICwtgBcFkuCEWB4oSwQgcAAdsAByMylSzlRwuSjuHHdZAwGA8ZGobBwCQYYBYUI8GxYTG/ZCIoQYdk41Dk1HorG4/EWTBE5yuDpuclLLA42ZaDhpGVZHIkmiyrCFYrmMp2Ynq6q1Boy2qkjotNoITrdXrXXzk4BwbBCHhYYAiUKhPm4AQYCRYBVCAAW2GuaBECBEGJRaJsYX9MEDIuxUmmkyI4yAA==))

I'll go ahead and close. Thanks
