### ISSUE TITLE
Call to Abstract Event: result in BAD IL generation, instead of compilation error

### ISSUE THREAD

**Issue by dzeitlin** [dotnet/roslyn#406]
Call to abstract event compiles (even in CTP5), results in BAD IL generation when trying to call it.

Sample code:
http://tryroslyn.azurewebsites.net/#b:releases-Dev14CTP5/K4Zwlgdg5gBAygTxAFwKYFsDcAobECG6qIADvgMaowDCA9hCLQDaoCCJJTY5+yY9AZmwBvbDBglgAIy7kY+KSgBOFZDHJN8IEDABCW1AHUwyABatFyFeWQBRAG6oIyMTFHjxkmd3mXra1EdnGFYbfggYAFkEBydkHHEAX1xPaVl1TW14YBJUJWMzAHlHJSUwABMnWOCALj0DAvM/VWqXcXcPL3TaErLKmEC4kLD6KJigto8Oj3ly8rcYKQMAOmjWmABqAF4Ye3wmYFRMGESYAHoz+AAJQoBVABkAET1bGABaD4A+OrylWiUaHAAAwAJiBAFY6tR8BAILQ1DwmEx5BEFMpVIsDDAiOgpHk6gByAAKfygKnQy30ICMJia6JsrVW4ziBNcMyUGB6VGEmOpTPWbx2ewORxO50ucBuD2euleHze3wGpX+gNBEKhMLhCP2yJhvnpaiW1OxGDxSkJJNoZMIlIatIsBsZawmrJmyTZEjSPnstAqMAAYrRaAAKACUHumHiNqH5E02O0DtGOF2udyeL3eXx+yoB1GBYMhNE18PUOpR+qsGOjJtx+JgxNJ5Nt1MaDsrDImsZZHuSSRSGS0Okt1vQrkjKF43t980i+EgYYjHvEcByeUaxV+FSqcZAAHdaFQdhBULvsrl8rSN6UtxBWmGEjMYHuD13gtsonOIA++33kkAAA==

**Comment by theoy** [comment]
Nice catch! Gah, we should definitely fix that! Thanks @dzeitlin for your contribution/letting us know! :bow:

**Comment by dzeitlin** [comment]
Thanks for the quick response. I'm writing this on behalf of the DuoCode (http://duoco.de) project which uses Roslyn extensively for conversion of C# code to JavaScript.
