### ISSUE TITLE
Declaring a variable twice in the Immediate window results in an "internal error"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4060]
**Repro**:
1. Create a new blank console application
2. Set a breakpoint on the last brace of Main
3. Press F5, wait for breakpoint to be hit
4. Open Immediate window
5. Type `int foo;` and press ENTER (results in `Expression has been evaluated and has no value`)
6. Enter `int foo;` and press ENTER

**Expected:** 
`A local variable named 'foo' is already defined in this scope.`

**Actual:**
`Internal error in the expression evaluator.`

**Comment by CyrusNajmabadi** [comment]
This doesn't seem to repro anymore.  I get a use message saying the variable is already declared.  Closing this out:

![image](https://user-images.githubusercontent.com/4564579/198709340-fac8fb9b-0acd-441d-81d9-d1186368b6bd.png)
