### ISSUE TITLE
Extract superclass refactoring - similar to Extract Interface, but generate a base class

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#40601]

**Comment by mikadumont** [comment]
Extract Superclass 

Overview 

This refactoring allows you to extract certain members from a selected class into a new base class. The original class will extend the created base class. 
If the current type already implements any interfaces, these interfaces can also be extracted into the new base class. 

User Story 

The example below shows how to extract an abstract class LoggerBase from the existing Logger class. 

Before refactoring 

public class Logger : ILogger 

    { 

        public string FirstName { get; private set; } 

        public string LastName { get; private set; } 

        public int age { get; private set; } 

        public void person() 

        { 

        } 

    } 

    public interface ILogger 

    { 

        void person(); 

    } 

After refactoring 

public abstract class LoggerBase : ILogger 

    { 

        public string LastName { get; private set; } 

        public abstract void Person(); 

    } 

    public class Logger : LoggerBase 

    { 

        public string FirstName { get; private set; } 

        public int Age { get; private set; } 

        public override void Person() 

        { 

        } 

    } 

    public interface ILogger 

    { 

        void Person(); 

    } 

Steps to extract Superclass 

Place cursor on the class name in the editor or solution explorer.  

Press (Ctrl + .) or (Alt + Enter). 

Select Extract Superclass.  

The Extract Superclass dialog will open.  

 

Specify a name for the base/parent class and where it should be placed – in a new file or in the same file as the original type.  

Select members that you want to transfer to the new base/parent class. The list of members can contain:  

Members of the current type 

Interfaces that the selected type currently implements 

To make/keep individual members abstract select the checkbox in the Make Abstract column next to them. If there is at least one member marked abstract the base class will be created abstract too.  

To apply the refactoring, click Ok.  

If no conflicts are found, the refactoring will be performed immediately.
