### ISSUE TITLE
Inline Temp Variable not handling collection initializers correctly

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#40615]
**Version Used**: 16.4.2

Original code:

```cs
using System.Collections.Generic;
public class Test
{
    public List<object> Prop1 { get; }

    static Test M()
    {
        var t = new Test
        {
            Prop1 = { new object() },
        };

        t.Prop1.Add(new object());

        return t;
    }
}
```

Invoking `Inline Temporary Variable` on `t` results in this code:

```cs
using System.Collections.Generic;
public class Test
{
    public List<object> Prop1 { get; }

    static Test M()
    {
        new Test
        {
            Prop1 = { new object() },
        }.Prop1.Add(new object());

        return new Test
        {
            Prop1 = { new object() },
        };
    }
}
```

Which is clearly incorrect.

**Comment by CyrusNajmabadi** [comment]
That looks exactly right.  You inlined the initializer into the two places it was current referenced.  i.e. both usages of 't' were replaced with `new Test { Prop1 = { new object() }, }`, which is exactly what inline-temp is supposed to do.

**Comment by 333fred** [comment]
@CyrusNajmabadi then why was the refactoring offered at all? This changes the semantic meaning of the code, and unless something has changed I'm pretty used to inline local only being offered when it's actually a temp local and not affecting the semantic meaning of the code.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi then why was the refactoring offered at all?

To let people inline the variable.

> This changes the semantic meaning of the code,

Pretty much all our code-actions do :)  

They're not 'refactorings' they're 'speedups'.  

> and unless something has changed I'm pretty used to inline local only being offered when it's actually a temp local and not affecting the semantic meaning of the code.

That has never been the case :)    It's always been a shortcut to just say "hey... instead of having the temp, i want to recompute thsi value at every reference point".

**Comment by 333fred** [comment]
Alright. I'll close this as by design, but it definitely didn't feel right to me.

**Comment by CyrusNajmabadi** [comment]
Can you explain why?  How would you expect 'inline' to work in this case?

**Comment by 333fred** [comment]
@CyrusNajmabadi I wouldn't expect it to work or be offered at all.
