### ISSUE TITLE
Create and initialize field refactoring should respect naming code style

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#40611]
When introducing a new field based on a constructor parameter, the new field is always given the same name as the parameter (even if the Code Style/Naming rules indicate a leading underscore should be used)

**Comment by sharwell** [comment]
This appears to already be working. Here's the feature in a project that uses a naming style of underscores for fields:

![image](https://user-images.githubusercontent.com/1408396/72013977-d6ef5d00-3213-11ea-97fa-99b0dd585aa7.png)

And here it is in a project where the naming style feature was not configured to require underscores (so it used the default of camelCase without prefix):

![image](https://user-images.githubusercontent.com/1408396/72014051-fdad9380-3213-11ea-9a4e-ad9050f4b1d2.png)

**Comment by vatsalyaagrawal** [comment]
Per customer feedback, this issue is not reproducible.
