### ISSUE TITLE
Syntax Visualizer VSIX package link is broken

### ISSUE THREAD

**Issue by razvan-panda** [dotnet/roslyn#4061]
Link in wiki on [Syntax-Visualizer](https://github.com/dotnet/roslyn/wiki/Syntax-Visualizer#syntax-visualizers) needs to be fixed to point to the [.NET Compiler Platform SDK](https://visualstudiogallery.msdn.microsoft.com/2ddb7240-5249-4c8c-969e-5d05823bcb89) extension which contains the Syntax Visualizer (or some better alternative).

**Comment by jmarolf** [comment]
@razvan-panda take a look at  https://github.com/dotnet/roslyn/wiki/Syntax-Visualizer and let me know if that fixes it to your satisfaction.

**Comment by razvan-panda** [comment]
Great, thank you.
