### ISSUE TITLE
Add  Intellisense for writing lambda expressions

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#40610]
Add Intellisense for writing lambda expressions - For example, if typing out a LINQ statement starting Array.Empty<string>().Select and pressing tab, define a skeleton lambda expression for the Func argument.

**Comment by jinujoseph** [comment]
related to #12363

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
