### ISSUE TITLE
The question is a bug or feature

### ISSUE THREAD

**Issue by kronic** [dotnet/roslyn#40618]
The Test(int a) function returns False instead of null, is this normal behavior?
[https://github.com/dotnet/runtime/issues/1187](Original)
```csharp
#region

using System;

#endregion

namespace MlTest
{
	internal static class Program
	{
		private static void Main()
		{
			var b = Test(10);
			Console.Write(b?.ToString() ?? "null"); //False
			Console.ReadKey();
		}
		private static bool? Test(int a) =>
			a switch
			{
				1 => true,
				2 => false,
				_ => default
			};
	}
}

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/issues/1187#issuecomment-569247252

Copying directly:
> I believe this is more suited to dotnet/roslyn (or even dotnet/csharplang) rather than this repo. It appears that the switch statement above generates a `bool` value, not `bool?`.
> IL generated: (Compiler version: '3.4.0-beta4-19568-04 (82f2e254)'. Language version: preview. Compiler optimisations on)
> ```
> Test:
> IL_0000:  ldarg.0     
> IL_0001:  ldc.i4.1    
> IL_0002:  beq.s       IL_000A
> IL_0004:  ldarg.0     
> IL_0005:  ldc.i4.2    
> IL_0006:  beq.s       IL_000E
> IL_0008:  br.s        IL_0012
> IL_000A:  ldc.i4.1    
> IL_000B:  stloc.0     
> IL_000C:  br.s        IL_0014
> IL_000E:  ldc.i4.0    
> IL_000F:  stloc.0     
> IL_0010:  br.s        IL_0014
> IL_0012:  ldc.i4.0    
> IL_0013:  stloc.0     
> IL_0014:  ldloc.0     
> IL_0015:  newobj      System.Nullable<System.Boolean>..ctor
> IL_001A:  ret         
> ```
> 
> Which is roughly the same as:
> ```cs
> private static bool? Test(int a)
> {
> 	bool value;
> 	switch (a)
> 	{
> 	case 1:
> 		value = true;
> 		break;
> 	case 2:
> 		value = false;
> 		break;
> 	default:
> 		value = false;
> 		break;
> 	}
> 	return value;
> }
> ```
> 
> The runtime is doing what exactly it is told to do by the compiler here.

Is this by the language design? For me it is very confusing as I was looking at the return type of the method and thinking that `default` in that switch expression must be `default(bool?)`, not `default(bool)` but it does somewhat makes sense.

**Comment by 333fred** [comment]
This is, somewhat unfortunately, a feature. `default` is typeless, and contributes nothing to type inference. So the info we start with is just bool. `default` can be target-typed to bool, and so it is, so the entire switch is typed as bool. /cc @gafter

**Comment by gafter** [comment]
When a switch expression has a natural type, and that natural type can be converted to the eventual target type, the switch expression is typed using that natural type.

Generally speaking, you should avoid writing `default` when you mean `null`.
