### ISSUE TITLE
Incorrect handling of NotNullWhen after nullable bool comparison

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#40614]
**Version Used**: Version 16.5.0 Preview 2.0 [29622.1.master]

**Steps to Reproduce**:

```c#
#nullable enable

using System.Collections.Generic;

class C
{
    void M(Dictionary<int, string>? d)
    {
        string? s = null;
        if (d?.TryGetValue(1, out s) != true)
        {
            s.ToString(); // valid CS8602 Dereference of a possibly null reference
        }
        else
        {
            s.ToString(); // invalid CS8602 Dereference of a possibly null reference
        }
    }
}
```

**Expected Behavior**:

No diagnostic in `else` block as `s` is definitely assigned to a non-`null` value.

**Actual Behavior**:

Diagnostic.

**Comment by gafter** [comment]
I suspect this is by design, though it is a reasonable request.

**Comment by jcouv** [comment]
Might relate to https://github.com/dotnet/roslyn/issues/41107 (another issue with analyzing a null conditional.

**Comment by jaredpar** [comment]
Going to let #42398 be the primary bug here.
