### ISSUE TITLE
ConvertedTypeSymbol is null when testing nullable type equality with null

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#40628]
With the following code:

```
SyntaxTree tree = CSharpSyntaxTree.ParseText(
@"namespace N
{
    public class C
    {
        public bool Foo()
        {
            int? i = 0;
            return i == null;
        }
    }
}");

var compilation = CSharpCompilation.Create("ConvertedTypeSymbolTest")
    .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location))
    .AddSyntaxTrees(tree);
var model = compilation.GetSemanticModel(tree);
var root = (CompilationUnitSyntax)tree.GetRoot();
var nullExpression = ((BinaryExpressionSyntax)((ReturnStatementSyntax)((MethodDeclarationSyntax)((ClassDeclarationSyntax)((NamespaceDeclarationSyntax)root.Members[0]).Members[0]).Members[0]).Body.Statements[1]).Expression).Right;
var convertedTypeSymbol = model.GetTypeInfo(nullExpression).ConvertedType;
```

convertedTypeSymbol is null and I think it should be int?. 

If I change i variable to string, it is not null (it is string as expected).

Also if I keep i variable as an int? but I change == to >, the convertedTypeSymbol is int?. 
Sounds that it’s only null with Nullable<T> and with == or !=.

**Comment by gafter** [comment]
I suspect this may be a bug in the nullable walker.

**Comment by jcouv** [comment]
Assigning to @333fred to take a look. Thanks

**Comment by 333fred** [comment]
This has nothing to do with nullable. Will keep investigating.

**Comment by 333fred** [comment]
Dug into this a bit more. We literally do not have a `BoundConversion` in the tree when the type it's being converted to `Nullable<T>`. Surprisingly, this same bug also affects VB:
```vb.net
Class C
    Public Sub M(s As String, i As Integer?)
        Dim discarded = (s = Nothing)
        discarded = (i = Nothing)
    End Sub
End Class
```

The first `Nothing` should (and does) have a `ConvertedType` of `System.String`. But the second `Nothing` has a `null` `ConvertedType`, when it should have a `ConvertedType` of `System.Int32`.

**Comment by 333fred** [comment]
Further, I can confirm that this results in an IDE quickinfo bug where type info isn't shown for that `null` constant.

I misspoke about the VB bug. It does have a bug, but the bug is slightly different. It should be returning `int`, but it's returning `int?`.

**Comment by AlekseyTs** [comment]
I think the current behavior is expected and follows language specification:
```
7.10.9 Equality operators and null
The == and != operators permit one operand to be a value of a nullable type and the other to be
the null literal, even if no predefined or user-defined operator (in unlifted or lifted form) 
exists for the operation.
For an operation of one of the forms
x == null    null == x    x != null    null != x
where x is an expression of a nullable type, if operator overload resolution (§7.2.4) 
fails to find an applicable operator, the result is instead computed from the HasValue property 
of x. Specifically, the first two forms are translated into !x.HasValue, and last two 
forms are translated into x.HasValue.
```

As such the null literal is not getting converted to any type.

**Comment by 333fred** [comment]
@MatthieuMEZIL does this make sense to you? Closing the bug.
