### ISSUE TITLE
Visual Studio Suggestion: Predictive Errors

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#40621]
It would be great if Visual Studio/Roslyn would identify methods with the following criteria:
1.  The inputs are reasonably "knowable" 
2.  The method is side-effect free.

And then run the method and return any errors at design time.  That way something like the following would be identified as a potential run-time error:
![image](https://user-images.githubusercontent.com/13609558/71518411-5ece8200-2878-11ea-9c75-a9e4a2900aea.png)

**Comment by CyrusNajmabadi** [comment]
Roslyn already supports this through analyzers.  It's up to the relevant API authors to write analyzers that check for this sort of thing though.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is covered by analzyers.
