### ISSUE TITLE
No quick fix for CS8370 upgrading .NET Framework projects to 8.0 language version

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#40624]
**Version Used**: VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150

**Steps to Reproduce**:

Use a C# 8.0 feature such as a switch expression in a .NET Framework project.

**Expected Behavior**: Quick fix to offer upgrading the project's language version to 8.0. 

**Actual Behavior**: No quick fix offered.

I am pretty sure the quick fix used to be available in previous builds. After the unfortunate advanced build options deprecation it was the only convenient way to upgrade project language version.

**Comment by jmarolf** [comment]
@cartermp I believe this was intentional

**Comment by cartermp** [comment]
Yes, this is intentional because C# 8 is not considered supported on .NET Framework.

**Comment by 06needhamt** [comment]
Forgive me for asking but why can’t C# 8 be supported on the .NET Framework?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miloush** [comment]
That does not make it any less valid fix... clearly if a developer used C# 8 syntax, and the error says upgrade to 8.0, then upgrading to 8.0 is a reasonable fix. From the compiler standpoint of view, nothing is going to break if you upgrade, and you can also add '(unsupported)' to the fix name if it helped. This is not inadvertently breaking things that accidentally worked, it feels like actually investing into decreasing developers' productivity.

What makes editing a project file manually a better fix?

**Comment by sharwell** [comment]
Unfortunately, we are not allowed to implement the requested behavior due to a managerial decision outside the scope of this team. It should be possible for a third-party analyzer to implement this change independently.

**Comment by miloush** [comment]
Understood; thank you @sharwell for the transparency.
