### ISSUE TITLE
Unable to retroactively complete generic in return parameter of extension method

### ISSUE THREAD

**Issue by mqudsi** [dotnet/roslyn#40635]
**Version Used**:  Visual Studio 16.4.0 Preview 2.0

**Steps to Reproduce**:

1) In a C# .NET Core 3.1 project, create a class with the following code:

```csharp
    public static class DbExtensions
    {

        internal static IQueryable
            AsNoTracking<TEntity>(this IQueryable<TEntity> queryable, bool noTrack)
            where TEntity : class
        {
            return noTrack ? queryable.AsNoTracking() : queryable;
        }


    }
```

2) Attempt to change `IQueryable` to `IQueryable<TEntity>`, selecting the `IQueryable` and overtyping it with `IQueryable<TEnt` (one character at a time)

**Expected Behavior**:

The intellisense completions will include a (top) suggestion of `TEntity`, derived from the context.

**Actual Behavior**:

The intellisense completions list does not include the generic `TEntity` parameter:

![image](https://user-images.githubusercontent.com/606923/71549801-2f5b6a80-2989-11ea-834c-920b8420cb4a.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and complexity of solution.
