### ISSUE TITLE
Update diagnostic analyzers and code fix providers to support eventual addition of "var?"

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#40645]
The compiler team plans to [add support for "var?"](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-12-18.md#var). As a result, issue #39313 and PR #40568 are currently blocked.

Once `var?` is implemented, the applicable diagnostic analyzers and code fix providers will have to be updated to support the change.

**Comment by sharwell** [comment]
My understanding is `var?` will not actually appear in the source. Rather, `var` will always infer `T?` instead of `T` when `T` is a non-nullable reference type.

**Comment by allisonchou** [comment]
Ah, it seems I've misunderstood. "Make var have a nullable annotated type and infer the flow type as normal" is the conclusion from the meeting notes ... so if I'm understanding correctly, does this mean that eventually no action will have to be taken to fix #39313 by the IDE team, since the warning that we are trying to assign a nullable to a non-nullable would disappear?

**Comment by jcouv** [comment]
@allisonchou Yes, I think that's correct. We'll solve the problem by fixing how `var` works instead of adding a concept of `var?`.
So I think we can close this issue.
