### ISSUE TITLE
 New IntPtr(CLng(Console.ReadLine)) causes IDE0004

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40657]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/864982/new-intptrclngconsolereadline-causes-ide0004.html)._

---
 New IntPtr(CLng(Console.ReadLine)) causes IDE0004, prompting to delete the CLng conversion.
However, if you really delete that, New IntPtr(Console.ReadLine) causes BC30057 and BC30519, complaining about overload failure.
So IDE0004 here is a wrong suggestion.

---
#### Leenrung on 12/21/2019, 08:12 PM: 

Sorry, BC30519 only, no BC30057
#### Visual Studio Feedback System on 12/23/2019, 00:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not planning on investing in these scenarios.
