### ISSUE TITLE
GetHashCode() quick action does not respect 'var' preferences

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40653]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/868219/gethashcode-quick-action-does-not-respect-var-pref.html)._

---
Create a class.  Add at least one property or field
Open Tools | Options | Text Editor | C# | Code Style | General
Set 'var' preferences:
For built-in types -> Prefer explicit type

Click OK

In the text editor, place the cursor on the class declaration
Choose the Quick Actions "screwdriver" that appears
Select "Generate equals and GetHashCode..."
Select at least one of the fields or properties of the class
Click OK
[Visual Studio will add three methods]
Unfold the GetHashCode() method
Note that "var hashCode = [VALUE]" is shown.

With the above selected option to prefer explicit types, this code should be:
"int hashCode = [VALUE]"

Please fix this.

---
#### Visual Studio Feedback System on 12/26/2019, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by VaderConsulting** [comment]
This is my reported problem.  Following here so that I can keep up with the status.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  With the option set to prefer non-var, i get:

![image](https://user-images.githubusercontent.com/4564579/152891153-6830eb03-6ad0-47b8-891f-d90c12e1c2cf.png)

But if i change my var preference to:

![image](https://user-images.githubusercontent.com/4564579/152891193-8d1d138d-2238-4794-9a6d-03d9a67092f4.png)

then i get:

![image](https://user-images.githubusercontent.com/4564579/152891223-b8b35bfa-72b2-4f41-8cff-debf4d073f14.png)
