### ISSUE TITLE
Exception ex{"OperatorToken"}

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4067]
With Visual Studio 2015 I am creating a Code Refactoring that does nothing and I am getting a exception ex{"OperatorToken"} with little useful information.

I have broken it down to show where I think the issue is, the first 5 lines are setup

```
       Dim semanticModel As SemanticModel = Await document.GetSemanticModelAsync(cancellationToken)
        Dim root As SyntaxNode = Await document.GetSyntaxRootAsync(cancellationToken)
        Dim OldCondition As BinaryExpressionSyntax = CType(invocation.Condition, BinaryExpressionSyntax)
        Dim OldConditionoperatorToken As SyntaxToken = OldCondition.OperatorToken
        Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.OperatorKeyword, "Is").WithLeadingTrivia(OldCondition.GetLeadingTrivia).WithTrailingTrivia(OldCondition.GetTrailingTrivia)
```

The following line throws the exception ex{"OperatorToken"} with no additional information
            Dim NewCondition As BinaryExpressionSyntax = SyntaxFactory.BinaryExpression(OldCondition.Kind, OldCondition.Left, operatorToken, OldCondition.Right)

If I substitute  OldCondition.operatorToken or OldConditionoperatorToken  for operatorToken it works as expected.
My eventual goal if to switch right and left and change operatorToken to "IsNot" as shown below
            Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.OperatorKeyword, "IsNot").WithLeadingTrivia(OldCondition.GetLeadingTrivia).WithTrailingTrivia(OldCondition.GetTrailingTrivia)
           Dim NewCondition As BinaryExpressionSyntax = SyntaxFactory.BinaryExpression(OldCondition.Kind, OldCondition.Right, operatorToken, OldCondition.Left)

**Comment by paul1956** [comment]
The problem is this line, but I am not sure why it shouldn't work or why the error message is not helpful.
Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.OperatorKeyword, "Is")...
It needs to be
Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.IsKeyword)

**Comment by gafter** [comment]
We would need a complete program demonstrating the issue you're experiencing to help you diagnose the issue.

**Comment by paul1956** [comment]
Solved the issue, but exception messages like ex{"OperatorToken"} are really not very useful especially to a VB programmer and they appear throughout the API's. I can point to some source lines if needed.

**Comment by gafter** [comment]
Yes, please let us know where those less-than-helpful exceptions occur.

**Comment by paul1956** [comment]
Below is a list of all the places where ArgumentException("operatorToken") is used, generally the ArgumentException("Anything") errors are the issue because there is no way to know what is wrong just from seeing an error that says Ex{"operatorToken"}. It would be nice to know what is it looking for and what it got.

C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(86709):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(92577):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(92721):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(92865):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(93009):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(93153):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(93297):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(93448):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(93578):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(96257):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(96516):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(96775):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(97034):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(97293):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(97552):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(97811):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(98070):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(98329):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(98588):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(98847):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(99116):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(99256):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101403):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101573):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101748):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101776):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101862):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101921):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(101986):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(102007):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(103503):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(103760):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(104017):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(104274):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(104531):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(104788):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(105045):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(105302):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(105559):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(105816):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(106073):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(106330):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(106587):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(106844):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(107101):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(107358):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(107615):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(107872):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(108129):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(108386):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(108643):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(108900):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(109157):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(109414):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(109683):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(109849):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(109869):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(110009):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(110149):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(110289):                    Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(110435):                Throw new ArgumentException("operatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(110561):                    Throw New ArgumentException("OperatorToken")
  C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb(116925):                    Throw new ArgumentException("operatorToken")

**Comment by CyrusNajmabadi** [comment]
Would need a repro of where this is happening.

**Comment by paul1956** [comment]
This is so old I have no idea and don't care anymore I will close.
