### ISSUE TITLE
Visual Basic - Nullable Enum Values are not evaluated as constant expressions

### ISSUE THREAD

**Issue by 06needhamt** [dotnet/roslyn#40675]
I came across this issue while trying to implement a fix for #40240

In C# everything works as expected and the constant expressions for nullable enum values are evaluated in `Features/Core/Portable/PopulateSwitch/PopulateSwitchStatementHelpers.cs` as expected. But in Visual Basic the constant expressions for nullable enum values come back as unspecified. However, it seems to work as expected for non-nullable enums.  

Edit Tests to show the issue

Works as Expected
```
Module Program
    Sub Main(args As String())
        Dim bar As Bar = Program.Bar.Option1

        Select Case bar
            Case Program.Bar.Option1
                Exit Select
            Case Program.Bar.Option2
                Exit Select
            Case vbNull
                Exit Select
            Case Else
                Exit Select
        End Select
    End Sub

    Enum Bar
        Option1 = 1
        Option2 = 2
        Option3 = 3
    End Enum
End Module
```

Expressions are not properly evaluated

```
Module Program
    Sub Main(args As String())
        Dim bar As Bar? = Program.Bar.Option1

        Select Case bar
            Case Program.Bar.Option1
                Exit Select
            Case Program.Bar.Option2
                Exit Select
            Case vbNull
                Exit Select
            Case Else
                Exit Select
        End Select
    End Sub

    Enum Bar
        Option1 = 1
        Option2 = 2
        Option3 = 3
    End Enum
End Module 
```

**Comment by gafter** [comment]
Can you please provide a test that illustrates the issue and add it to the issue description?

**Comment by 06needhamt** [comment]
@gafter I have added a test which demonstrated the issue. Let me know if you need any more info

**Comment by gafter** [comment]
@06needhamt Both of these programs compile without error and have the same runtime behavior.  I suspect your concern is with the behavior of the Roslyn APIs when inspecting these programs.  Can you please provide a sample program that compiles a program and inspects it using the Roslyn APIs, and illustrates what you find unexpected about the results?

**Comment by 06needhamt** [comment]
@gafter Compile and run a Roslyn instance from the master branch

Create a new VB .NET Core Console App and paste in the two tests.

Put a breakpoint [https://github.com/dotnet/roslyn/blob/c6d423199dc9ec962eafa8a993436854dc209f9a/src/Features/Core/Portable/PopulateSwitch/PopulateSwitchStatementHelpers.cs#L87](here).

Execute the add missing cases code fix on both tests.

Notice on the first one the constant value is 1 and on the second it is ‘unspecified’.

The C# equivalent of both these tests work as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 06needhamt** [comment]
I can no longer reproduce this issue with the latest master, has anything notable changed in these API's?

**Comment by 06needhamt** [comment]
Closing as i can no longer reproduce
