### ISSUE TITLE
How do I optimize the build?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#40693]
When I use roslyn, I find that there are a lot of useless DLL, in the debug folder, such as cs / de / es / fr / it / ja / ko / pl / ru / tr / zh-Hans / zh-Hant and so on.

How do I prevent them from building?

![image](https://user-images.githubusercontent.com/16236903/71667760-67a3e400-2da1-11ea-8a0e-5c176f7f438b.png)

![image](https://user-images.githubusercontent.com/16236903/71667810-9c17a000-2da1-11ea-9d6a-3dc41826369f.png)

**Comment by jaredpar** [comment]
> When I use roslyn, I find that there are a lot of useless DLL, in the debug folder, such as cs / de / es / fr / it / ja / ko / pl / ru / tr / zh-Hans / zh-Hant and so on.

These DLLs are not useless and instead are a part of our localization story. They contain all the resource strings for non-english environments. 

> How do I prevent them from building?

There is no way to prevent them from building. Their presence is necessary for our build output to be correct.

**Comment by NMSAzulX** [comment]
@jaredpar  Thank you~!

**Comment by jmarolf** [comment]
@NMSAzulX 

In general, if you are using the new sdk-style project format you can add this property to your project
```xml
<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
```

or add this at the commandline
```cmb
msbuild /p:SatelliteResourceLanguages=en
```

this should ensure that these resource dlls are not deployed.

Though as @jaredpar says you are not expected to do this when building this repo

**Comment by NMSAzulX** [comment]
@jmarolf  Thank you very much~!
