### ISSUE TITLE
Error in TestWriter

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#4069]
Some how a space after a line-continuation has been removed ([TestWriter Line 179](https://github.com/dotnet/roslyn/blob/master/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/Tests/TestWriter.vb#L179)), which isn't valid.

**Comment by AdamSpeight2008** [comment]
Try editing that file by adding the missing space and save it. The space is deleted.

**Comment by Pilchie** [comment]
Is this an IDE issue with the pretty lister, or an issue with the compiler code?

**Comment by AdamSpeight2008** [comment]
The IDE i think as it happens when I save. Both SaveAll and Save as

**Comment by AdamSpeight2008** [comment]
Forgot to add info about which build it is.
```
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA906
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA906
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA906
Microsoft Visual C++ 2015

```

**Comment by AnthonyDGreen** [comment]
Adam, could you be more specific in describing the problem. I tried pasting the content of that file into VS and forcing a format document and couldn't reproduce what you're describing. Yes, the pretty-lister removes extra whitespace before and after the underscore character but that shouldn't produce any error. Whitespace after the underscore isn't required.

Could you paste a screenshot?

**Comment by Pilchie** [comment]
Please let us know if you still see a problem here.
