### ISSUE TITLE
Incrrect sugestion about CType

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40696]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/867300/incrrect-sugestion-about-ctype.html)._

---
Next fragments of code:
Constructor:    
```
<Flags>
Public Enum CycleKind
    None = 0
    SPEC = 1
    PAC = 2
    TU025 = 4
    TU050 = 8
    TU075 = 16
    TU100 = 32
End Enum
Public Sub New(key As Integer,
                   kind As CycleKind,
                   start As Integer,
                   lengthChange As Decimal,
                   title As String,
                   city As String)
        Me.Key = key
        KeyBuilder.RegisterKey(key)
        Me.Kind = kind
        Me.Start = start
        Me.LengthChange = CInt(lengthChange)
        Me.Title = title
        Me.City = city
    End Sub
```
Getter in control-editor:
        
```
Get
    Dim dkind = If(cmbKind.SelectedIndex > -1, Cycle.CycleKind.TU100, 2 ^ cmbKind.SelectedIndex)
    Return New Cycle(nKey, CType(dkind, Cycle.CycleKind), dpStart.SelectedId, udPercent.Value, dpTitle.Text, sCity)
End Get
```
This part of code is fully tested and works as designed, but CType required (from double to an enum) in the getter marked as redundant (Warning IDE0004).

---
#### Visual Studio Feedback System on 12/26/2019, 00:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/30/2019, 02:47 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change these VB experiences.
