### ISSUE TITLE
Dependencies on Visual Studio assemblies and Visual Studio SDK.

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/roslyn#407]
I have noticed that you have recently commited a lot of Visual Studio codebase to the repository, that's an incredible amount of great value you are giving to the community!

At the moment all the EditorFeatures depend on bunch of Microsoft.VisualStudio.* assemblies that come with Visual Studio. Do you plan to remove in the nearest future those dependencies and make EditorFeatures base only on Roslyn and .NET Framework?

I have gone through all the issues, blogs, source code etc. and I am unable to find that information.

I assume that projects in VisualStudio directory (e.g. CSharpVisualStudio) are depending on Visual Studio SDK on purpose to allow package creation and are intended to be the connection point between open sourced Roslyn and commercial Visual Studio.

**Comment by khellang** [comment]
This also ties into the following UserVoice suggestions:

http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/5786689-support-net-builds-without-requiring-visual-studi
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6123777-distribute-visual-studio-sdk-as-a-nuget-package

If you care, go vote! :wink:

**Comment by sharwell** [comment]
Interesting. So far I haven't expanded the [vsxdeps](https://github.com/tunnelvisionlabs/vsxdeps) project to include the **.targets** files from the SDK, but that seems like an obvious next step.

**Comment by mattwar** [comment]
The EditorFeatures layer is meant to be tied to the VS editor, but not VS otherwise. There is/was a possibility of rehosting the editor in other products. The Features layer is meant to only have dependency on .net.

**Comment by mkosieradzki** [comment]
Thank you very much for response.

In this situation Microsoft.CodeAnalysis.Completion.CompletionService should be exposed from Features layer as public API. Currently it is set as internal and used in nearly every project through InternalsVisibleTo. I assumed you plan additional entry points to the Features layer as toolkits including completion service. 

There is currently NO entry point to access all the implemented logic related to code completion. (That's a really huge amount of code).

So any chance to expose CompletionService as public in features or through additional toolkit library?

Do you plan to create and official nuget package for Features?

**Comment by Pilchie** [comment]
I’m currently working on the reverse half of this – the ability for third parties to implement our `ICompletionProvider` type and provide items to be included in our `CompletionService`.  Once that’s done, I’d definitely be interested in seeing what it would take to expose consumption of completion publicly.
--
Kevin Pilch-Bisson
    http://twitter.com/Pilchie

**Comment by khellang** [comment]
Wasn't there some public completion APIs available at some point? Recommender?

**Comment by dfkeenan** [comment]
I really hope you make the features APIs public.  I'm mostly interested in completion, though I could take advantage of a few otherthings like brace completion.

I was using the completion API from one of the earlier CTPs I was sad to find they had all been made internal.

**Comment by sharwell** [comment]
@dfkeenan Can you clarify - are you interested in using these APIs as part of implementing support for a new language, or are you interested in creating an extension that modifies the IDE behavior when working with C# or VB?

**Comment by dfkeenan** [comment]
@sharwell I was working on a WPF app with scripting suport using AvalonEdit in conjunction with Roslyn to do the syntax highlighting, squiggles (error/warning text markers), completion, snippets and runing of the scripts.  

I stopped working on it when scripting was put on hold.  But now that it's back I thought I could pick-up where I left off.

**Comment by mkosieradzki** [comment]
+1 dfkeenan. I also want to do something like AvalonEdit + Roslyn without reflection (BTW. I've seen so many projects like this, even one from Microsoft based on 2012 Roslyn build AFAIR.
.
This is the actual reason of original question - if there would be an open sourced component backed by Microsoft it doesn't make any sense to develop your own. 

Except you want to this for example via web :). Which is another good reason why despite the editor component code completion API should be public.

**Comment by jmarolf** [comment]
@khellang You can call [Recommender.GetRecommendedSymbolsAtPosition](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Recommendations/Recommender.cs,13) which will do some of what want, but completion has a lot of other pieces that can do more.

**Comment by mkosieradzki** [comment]
[Microsoft.CodeAnalysis.Completion.CompletionService](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionService.cs) - this API  is just begging to be public :). It does EXACTLY what is required in the editor.

**Comment by mkosieradzki** [comment]
@jmarolf Thanks for your recomendation. Actually Recommender.GetRecommendedSymbolsAtPosition does contain MOST of useful (for my purpose) logic inside. Actually CompletionService is not as interesting as the Recommender.

I decided to create my minimalistic WPF code editor from scratch (without using AvalonEdit or stuff) and I must say Roslyn API makes this task quite easy, if not trivial at all :).

Is it possible to obtain somewhere official build of Microsoft.CodeAnalysis.CSharp.Features and Microsoft.CodeAnalysis.Features assemblies? I browsed through all the nuget packages and nightly builds and I am unable to find those assemblies in any package.

**Comment by Pilchie** [comment]
We don't have packages for those because they don't contain any public APIs.  What are you looking for from them?

**Comment by mkosieradzki** [comment]
I wanted to do some reflection-based calls.

But you are right - I thought Recommender is actually in Features not Workspace - too much code browsing - I confused it with trivial KeywordRecommenders which are in Features - but are not as useful as Recommender.GetRecommendedSymbolsAtPosition.

Thanks that's a really helpful answer.
