### ISSUE TITLE
Unable to open .net core projects due to invalid microsoft.build.framework dependency

### ISSUE THREAD

**Issue by pkrukp** [dotnet/roslyn#40719]
Hi,

**Version Used**: 
Microsoft.Build.Locator 1.2.6
Microsoft.CodeAnalysis.Workspaces.MSBuild 3.4.0
MSBuild from VS 2019 16.4.0

**Problem description**:

In short:

I'm using MSBuildLocator to register msbuild and then open .csproj using MSBuildWorkspace.OpenProjectAsync(). I'm getting error diagnostics in project.GetCompilationAsync().GetDiagnostics(). There are no msbuild assemblies in program output folder. VS/msbuild can compile that project. 

The pseudo code looks like this:
```
MSBuildLocator.RegisterMSBuildPath(vs2019Instance.MSBuildPath)
var workspace = MSBuildWorkspace.Create();
var project = await workspace.OpenProjectAsync(path);
var compilation = await project.GetCompilationAsync();
var diagnostics = compilation.GetDiagnostics();
```

I have removed binding redirects that are added by default to exe .config. They redirect all microsoft.build.* assemblies to 15.1.0.0, but I am using MSBuildLocator to register various versions of msbuild, which are not known during application startup. For example if user has only msbuild/VS 2015 and compiles older code which is supported by that msbuild, I can't redirect assemblies to 15.1 because they won't exist on his machine.

**Why this happens**:

I tracked it down to two microsoft.build.framework.dll loaded: one registered by msbuildlocator, and one old version from GAC, which seems to be hardcoded somewhere - in roslyn? in msbuild?

```
Microsoft.Build.Framework.dll	Microsoft.Build.Framework.dll	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Build.Framework.dll	Yes	No	Skipped loading symbols.		32	16.04.0.56107	<Unknown>	06D30000-06D54000	[22372] RoslynOpenProject.exe	[1] RoslynOpenProject.exe	
Microsoft.Build.Framework.dll	Microsoft.Build.Framework.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll	Yes	No	Skipped loading symbols.		57	4.8.3752.0 built by: NET48REL1	02.03.2019 07:38	7C3D0000-7C439000	[22372] RoslynOpenProject.exe	[1] RoslynOpenProject.exe	
```

I already filled an issue for msbuild project, but I'm not sure if this is a problem in msbuild itself or in roslyn. The assemblies are loaded during MSBuildWorkspace.OpenProjectAsync call.

Could someone please take a look this issue - there's a detailed description, repro program, fusion logs etc: https://github.com/microsoft/msbuild/issues/5002 

This behavior does not seem correct - shouldn't msbuild assemblies from registered version be used? It seems that there's a hardcoded dependency somewhere? Or some hidden dependency on assemblies that are not part of msbuild and thus not handled by MSBuildLocator?

**Comment by jinujoseph** [comment]
cc @jasonmalinowski

**Comment by pkruk2** [comment]
Hello, 
I noticed that some labels were applied like Question or Concept-API, does this mean that this is some deeper issue?

**Comment by jasonmalinowski** [comment]
Closing this old bug out, if for no other reason that at this point Roslyn has rewritten how we use MSBuild in MSBuildWorkspace so using MSBuildLocator is no longer required -- we're now launching our own process to take care of that for you. As far as the original question about that GAC version or how MSBuildLocator would work with VS2015 versions; that indeed would be a question for MSBuild.
