### ISSUE TITLE
Autocomplete multiple times

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40736]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/769962/autocomplete-multiple-times.html)._

---
<p>Let's say I have the following classes in a .net project:</p><p>Product.cs</p><p>ProductFactory.cs</p><p>ProductProviderFactory.cs</p><p>ProductFixtureCustomizer.cs</p><p>and so on. </p> <p>If I'm trying to autocomplete to insert a reference to 'ProductFixtureCustomizer', I have to type the prefix out and then select it from a dropdown. Most other IDEs have the ability to continually show the suggestions when typing. </p><p>Ideally, I would be able to do the following:</p><p>1. Type 'Pro'</p><p>2. Select 'Product' out of suggestions list</p><p>3. Type 'Fix' (After 'Product')</p><p>4. Select 'ProductFixtureCustomizer' out of suggestions</p><p><br></p><p>Unfortunately, as soon as you have used the suggestion, no more suggestions will be made so step 4 is currently impossible. This means I either have to type out 'ProductFix' before tab completing or select 'ProductFixtureCustomizer' out of an arbitrarily large list of suggestions coming from typing 'Pro', neither of which is ideal.</p>

---
#### Jane Wu [MSFT] on 10/10/2019, 00:11 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by genlu** [comment]
We do support [various kind of camel case matching](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/PatternMatching/PatternMatchKind.cs,03d0277c03e1158c,references), so you could just skip the "select" step above and keep typing the the starting character of next word. I believe this would address the feedback nicely.

For example:

![image](https://user-images.githubusercontent.com/788783/72102952-06b66780-32dd-11ea-8012-520a8b44f4b9.png)
