### ISSUE TITLE
Member indent after indenting access modifiers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40743]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/831765/member-indent-after-indenting-access-modifiers.html)._

---
Hi
Currently, I set the indentation for an access modifier to look like this.

```cpp
class Rectangle {
    public:
    int blahblah;
};
```

I would like the class members to be indented twice instead of once, so it looks like this. However, there is no option to do that. 

```cpp
class Rectangle {
    public:
        int blahblah;
};
```

It's the same issue as [this](https://stackoverflow.com/questions/20695923/indenting-issue-after-access-specifiers-in-visual-studio-express).

```

```

---
#### Visual Studio Feedback System on 11/25/2019, 00:43 AM: 

Thank you for taking the time to provide your suggestion.
#### Patrick Slamp on 12/17/2019, 11:29 PM: 

I would also like to have this feature in visual studio 2019. I find that it makes C++ code easier to read.

**Comment by CyrusNajmabadi** [comment]
@kendrahavens this is a C++ request, not a Roslny one.
