### ISSUE TITLE
Disable code analysis scrollbar annotations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40742]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/831271/disable-code-analysis-scrollbar-annotations.html)._

---
A feature to enable/disable code analysis message annotations for the vertical scrollbar. I want to still see errors, warnings, changes, find results etc., but not code analysis messages.

---
#### Visual Studio Feedback System on 11/25/2019, 00:28 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Related to #29123

**Comment by CyrusNajmabadi** [comment]
This is not Roslyn.   Can you move to editor @olegtk ?
