### ISSUE TITLE
Not found:Diagnostic with Code Fix (NuGet + VSIX) template

### ISSUE THREAD

**Issue by balubchand** [dotnet/roslyn#4074]
With visual studio 2015 RC, I had used "Diagnostic with Code Fix (NuGet + VSIX) template" to create live code analyser where I could generate a nugget package as well as VSIX file.

The template is not available after the release of VS 2015 RTM. I have explicitly installed Roslyn SDK but still the template is not there in my Visual Studio 2015 RTM

Where can I get the similar template for visual studio 2015

**Comment by bkoelman** [comment]
Maybe this helps? #4051

**Comment by Pilchie** [comment]
We've updated the template to indicate that it is only applicable with a Target Framework of .NET 4.5.2 or higher.  Take a look at the Target Framework dropdown at the top of the New Project dialog.

**Comment by balubchand** [comment]
Thanks the framework change option helped
