### ISSUE TITLE
Show the name of the argument being passed to a function if the argument is a primitive type.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40740]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/772308/show-the-name-of-the-argument-being-passed-to-a-fu.html)._

---
It is really annoying to see primitive values like `true` `false` or `"SomeArgument"` or `0` being passed to a function without actually knowing what argument that value actually relates to.
One has to see the documentation of the function or see definition of the function to map what the passed primitive value to the argument in the function.

It would be useful to show in the function call which argument a primitive value being passed actually relates to.

---
#### Pratik Sanglikar [MSFT] on 12/16/2019, 01:57 PM: 

<p>I faced the issue for C#, but support might be missing for other languages as well.<br>Consider a sample .NET Core Console app. <br><br>Program.cs<br></p><pre><br>namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            Sample.MethodAcceptingPrimitiveTypes("abc", 1, true, false);
        }
    }
}<br><br></pre><br>Sample.cs<br><pre><br>namespace ConsoleApp2
{
    class Sample
    {
        public static void MethodAcceptingPrimitiveTypes(string someString, int someInt, bool someBool, bool confusingBool)
        {
            Console.WriteLine($"{someString}, {someInt}, {someBool}, {confusingBool}");
        }
    }
}<br><br></pre><br>Now, consider, a user just navigating the codebase finds a call to `MethodAcceptingPrimitiveTypes()` but can't comprehend what the passed parameters map to unless the user goes and finds the definition of the `MethodAcceptingPrimitiveTypes()` or parameter mapping is specified in the call by <br><pre>Sample.MethodAcceptingPrimitiveTypes("abc", 1, someBool: true, confusingBool: false);</pre><br>Now, we as VS, can be intelligent and tell the user that passed in value `"abc"` is actually for the argument `someString` or the passed value `true` is for `someBool` and `false` is for `confusingBool`.<br><br>Intellij Idea does this by just showing the parameter name near the passed value to indicate what argument of the method the passed in value actually maps to.<br><br>Let me try to find a screenshot of comparison of Idea and VS side by side to better explain it.

**Comment by kendrahavens** [comment]
Specifically looking for "parameter hints", but only for primitive types to avoid verbosity.

**Comment by jmarolf** [comment]
fixed by https://github.com/dotnet/roslyn/pull/45425
