### ISSUE TITLE
Style await with Keyword - Control Category

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40741]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/830435/style-await-with-keyword-control-category.html)._

---
The setting "Keyword - Control" under Fonts and Colors does not affect the await keyword, but it probably should.
If it does not make sense to group it into the Control category it would be nice to be able to define a custom color/font for it that is separate from the "Keyword" color/font.

---
#### Visual Studio Feedback System on 11/21/2019, 07:30 PM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 11/21/2019, 08:08 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler does the language consider `await` to be a control flow keyword?

**Comment by RikkiGibson** [comment]
It feels like it should be categorized similarly to `return` and `yield`. I can't speak definitively on this though.

**Comment by 333fred** [comment]
I mean, it does affect the control flow of the method. Seems like it should be.
