### ISSUE TITLE
Exception dialog popped up while typing code in VS2015 RTM

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4075]
I found this info in `c:\Users\Bart\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml`, hope it helps:

```xml
  <entry>
    <record>1973</record>
    <time>2015/07/23 10:59:25.917</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified SnapshotPoint or SnapshotSpan  is on a different ITextSnapshot than this SnapshotSpan.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.EnsureSnapshot(ITextSnapshot requestedSnapshot)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.IntersectsWith(SnapshotSpan snapshotSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMarginVisualManager`1.RemoveGlyphsByVisualSpan(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
```

**Comment by Pilchie** [comment]
This looks like an issue with the editor itself.  I'll pass along to them and report back here.

**Comment by markw-t** [comment]
Thanks for the report. Do you have any further context on what you were doing when the exception dialog popped up, @bkoelman ? Can you make it show again?

**Comment by hgirish** [comment]
I had the same error. The error occurred when I opened bower.json and typed comma after the last item in dependencies.

**Comment by bkoelman** [comment]
@markw-t Cannot repro it anymore. My cursor was at the top scope of a class, no build errors. Then I typed ImportAdder and resolved its using. This caused a squiggle under it, obviously. I believe I then alt-tabbed away to copy in some code. It was this copy-in action (if I recall they were comments) that caused the popup.

Maybe it helps to know that I have Resharper v9.1.2 (released July 21st) installed. Something that may also be related: A problem that occurs sometimes, not always (also in the RC and CTPs). I'm running Win 8.1 in HyperV Manager. It connects through some sort of remote desktop interface, called Enhanced Session. In control panel (both host and VM), I have set keyboard speed to maximum. Now with all this, sometimes it happens that (only in VS) keyboard strokes are "missed". Most notably pressing the spacebaar in RC was ignored sometimes, I recall. In RTM, I even got once that typing a space in a line (no selected text) deleted the next identifier. All this is hardly reproducible as it seems timing related.

**Comment by Pilchie** [comment]
@hgirish That issue is likely unrelated.  Can you look at the Activity Log entry and extract the error message/stack trace so we can route appropriately?

**Comment by markw-t** [comment]
Thanks @bkoelman - Im not sure if the extra details will be important or not. If you hit a repro again, especially if it's repeatable, it'd be good to know if disabling ReSharper stops you seeing it.

**Comment by bkoelman** [comment]
I will keep that in mind, thanks.

**Comment by hgirish** [comment]
@Pilchie, I tried same thing on different computer and had same issue. Entering comma in bower.json dependencies section cause the errror.  I do have Resharper 9.1.2 installed.

Below are last 4 entries from activity log

  <entry>
    <record>517</record>
    <time>2015/07/24 18:13:49.589</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function VBDispatch::GetTypeLib</description>
  </entry>
  <entry>
    <record>518</record>
    <time>2015/07/24 18:13:49.589</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Leaving function VBDispatch::GetTypeLib</description>
    <guid>{80CC9F66-E7D8-4DDD-85B6-D9E6CD0E93E2}</guid>
  </entry>
  <entry>
    <record>519</record>
    <time>2015/07/24 18:13:54.449</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified SnapshotPoint or SnapshotSpan  is on a different ITextSnapshot than this SnapshotSpan.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.EnsureSnapshot(ITextSnapshot requestedSnapshot)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.IntersectsWith(SnapshotSpan snapshotSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMarginVisualManager`1.RemoveGlyphsByVisualSpan(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
  <entry>
    <record>520</record>
    <time>2015/07/24 18:13:54.456</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified SnapshotPoint or SnapshotSpan  is on a different ITextSnapshot than this SnapshotSpan.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.EnsureSnapshot(ITextSnapshot requestedSnapshot)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotSpan.IntersectsWith(SnapshotSpan snapshotSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMarginVisualManager`1.RemoveGlyphsByVisualSpan(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>

**Comment by markw-t** [comment]
@hgirish if you follow the same steps with Resharper disabled (easiest to accomplish by starting Visual Studio in "Safe Mode" , devenv /safemode) , do you still see the dialog?

**Comment by hgirish** [comment]
I spend few hours in "Safe Mode" and so far dialog has not popped up.  So I guess it might be related to Resharper or WebEssentials.

**Comment by markw-t** [comment]
Thanks @hgirish . You can try disabling extensions individually to isolate whether R# or WebEssentials is to blame. Meanwhile we'll assume this is an extension-caused issue unless anyone can repro in safe mode. Thanks!

**Comment by bkoelman** [comment]
In my case, it is likely a Resharper bug indeed...
http://blog.jetbrains.com/dotnet/2015/07/23/critical-issue-with-resharper-9-1-2-in-visual-studio-2015-rtm-workarounds-and-estimates/

**Comment by markw-t** [comment]
Thanks for letting me know @bkoelman
