### ISSUE TITLE
Inlining variable declaration results in ugly namespace

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40750]
I encountered this in the compiler code, in `ReturnsAwaitableToVoidOrInt`.

![image](https://user-images.githubusercontent.com/12466233/71784914-ebcab700-2fad-11ea-9527-8797760da407.png)

![image](https://user-images.githubusercontent.com/12466233/71784920-fedd8700-2fad-11ea-8702-1925451f2edc.png)

This was on 
```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.5.0 Preview 1.0
VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150
Microsoft .NET Framework
Version 4.8.03752

```

**Comment by jcouv** [comment]
Tagging @333fred @jasonmalinowski as FYI

**Comment by ryzngard** [comment]
Is this a NRT enabled file? @y87feng reduced the repro to the simplifier not behaving correctly in those cases.

**Comment by jcouv** [comment]
`ReturnsAwaitableToVoidOrInt` is in a file with `#nullable enable`, but I'm not sure whether that's a factor. 
I assumed the issue was related to nullable, because otherwise I would think that the IDE test harness would have prevented such a regression.

**Comment by CyrusNajmabadi** [comment]
IDE simplification works by rebinding shorter symbol names and then checking for symbol equality.  It would nto surprise me *at all* if this was broken in `nullable enable` senarios due to either getting the wrong speculative symbols back, or having equality checks subtly break. 

When they do, that's when you get the `global::...` names since we can't find any way to make things shorter while getting the right type.

**Comment by jcouv** [comment]
@CyrusNajmabadi That wouldn't surprise me.

@jasonmalinowski @ryzngard Could we move this issue from backlog to be investigated in 16.5 or at least 16.6? 
I worry that it may be widespread, rather than a rare occurrence.

**Comment by jcouv** [comment]
Confirmed the issue:
``` csharp
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInlineDeclaration)]
        public async Task InlineVariable_NullableEnable()
        {
            await TestInRegularAndScriptAsync(@"
#nullable enable
class C
{
    void M(out C c2)
    {
        [|C|] c;
        M(out c);
        c2 = c;
    }
}", @"
#nullable enable
class C
{
    void M(out C c2)
    {
        M(out global::C c);
        c2 = c;
    }
}");
        }
```

**Comment by ryzngard** [comment]
This is also reproducible with generating equality overrides in a nullable context

**Comment by jcouv** [comment]
I debugged briefly and traced it to `ReplacementBreaksTypeResolution` where we end up asking whether two `C` symbols are compatible (`SymbolsAreCompatible`), but one is annotated with `None` and the other with `NotAnnotated`.
@333fred has a PR that may help with that. Fred, could you add the above test in `CSharpInlineDeclarationTests` and see if it now works in your branch?

**Comment by CyrusNajmabadi** [comment]
Would def like to know why one is annotated and the other is not! :-)

**Comment by 333fred** [comment]
The test does not simplify with my changes. Will need to investigate to see what's causing this.

**Comment by jcouv** [comment]
Here's a compiler-level repro:
``` csharp
        [Fact]
        [WorkItem(40750, "https://github.com/dotnet/roslyn/issues/40750")]
        public void TODO2()
        {
            var source =
@"#nullable enable
class C
{
    void M(out C c2)
    {
        M(out global::C c);
        c2 = c;
    }
}";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();
            var tree = comp.SyntaxTrees[0];
            var model = comp.GetSemanticModel(tree);
            var type = tree.GetRoot().DescendantNodes().OfType<DeclarationExpressionSyntax>().Single().Type;

            var statement = SyntaxFactory.ParseStatement("M(out C c);", options: TestOptions.RegularPreview);
            Assert.True(model.TryGetSpeculativeSemanticModel(type.SpanStart, statement, out var speculativeModel));

            var type2 = statement.DescendantNodes().OfType<DeclarationExpressionSyntax>().Single().Type;
            var symbol2 = speculativeModel.GetSymbolInfo(type2);
            Assert.Equal(PublicNullableAnnotation.NotAnnotated, ((ITypeSymbol)symbol2.Symbol).NullableAnnotation);
        }
```
