### ISSUE TITLE
Using empty params pointer arrays results in invalid IL and BadImageFormatException

### ISSUE THREAD

**Issue by kekekeks** [dotnet/roslyn#40768]
**Version Used**: .NET Core SDK 3.0.11, same behavior in SharpLab

**Steps to Reproduce**:

```cs
static unsafe class Wat
{
   public static unsafe void Test(params int*[] types)
   {

   }
   public static void Crash()
   {
      Test();
   }
}

public static class Program
{
   public static void Main()
   {
      Wat.Crash();
   }
}
```

**Expected Behavior**:
Roslyn produces valid IL

**Actual Behavior**:
Roslyn attempts to use `Array.Empty<int*>()` which results in invalid IL and causes the runtime to throw BadImageFormatException.

[SharpLab](https://sharplab.io/#v2:C4LglgNgPgAgjANgAQFcB2BnAhgMwKZIwBMSA6lsALABQA3jUozAMyGKqa4EwAsSAKngzAAFAAcsAJywBbDEjBpgAKgDaAXSTAAnmKEBKBo3rVGZpEaQBfSyzbJeSAMLSMACxGHTxy2cHDPAG5LG2pQmmJmGhMzYiJLGPMyCgA6Fyx3IJCaKyA==)

**Comment by YairHalberstadt** [comment]
I'll fix this
