### ISSUE TITLE
Specifying RuntimeMetadataVersion in the Csc task

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#4076]
It does not appear to be possible to specify a value for RuntimeMetadataVersion through the Csc task.

**Comment by davkean** [comment]
Can you give us a background on why you need this? Usually this is pulled from the corlib (mscorlib/System.Runtime) itself.

**Comment by erik-kallen** [comment]
Because I'm building an mscorlib, and I get a warning saying that I must specify it but there is no parameter to do so. (actually, I found out that it is possible to specify because I can specify a response file and add the /runtimemetadataversion:nnn directive to that).

**Comment by ericstj** [comment]
You can specify this in a .rsp file and pass that in.  That's what we do.
