### ISSUE TITLE
Unify editorconfig parsers

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#40774]
## Background

We have an editorconfig parser in the compiler layer here:
https://github.com/dotnet/roslyn/blob/9ba266a76ef4ea79f54551c8860a5021d1deffc0/src/Compilers/Core/Portable/CommandLine/AnalyzerConfig.cs#L109 `AnalyzerConfig` is used to parse all the editorconfig options when analyzers are run in the compiler etc. 

There is also `Microsoft.VisualStudio.CodingConventions` (which is internal) [here](https://devdiv.visualstudio.com/DevDiv/_git/aa950f06-430f-48af-8bb9-bcaf4f29e5fd?path=%2Fsrc%2FMicrosoft.VisualStudio.CodingConventions%2FEditorConfig%2FEditorConfigParser.cs&version=GBmaster&line=40&lineEnd=41&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)

This parser is used to provide a `ICodingConventionsSnapshot` instance in Visual Studio that is used by roslyn and presumably others.

## Problem

As it exists today, roslyn uses two different editorconfig parsers that have entirely different runtime semantics regarding casing (see https://github.com/dotnet/roslyn/issues/40705 for an example where an issue will reproduce or not depending on which parser is used). In general I don't think that we want to have to handle the semantics or engineering costs of having two different parsers.

## Engineering Proposal

Since the compiler team has already agreed to support an editorconfig parser in-perpetuity, I propose we refactor `AnalyzerConfig`'s parser so it can be consumed in `Microsoft.VisualStudio.CodingConventions`. I'll leave the details vaugue but it seems at the very least we could produce a source based package that `Microsoft.VisualStudio.CodingConventions` consumes to ensure that we have consistent behavior.

CC: @olegtk @agocke @sharwell @jasonmalinowski

**Comment by jasonmalinowski** [comment]
So right now us trying to _use_ both of these parsers was a transition mechanism while we sort out any remaining issues with the new one. Right now the editor one is only used if you explicitly opt into it in Visual Studio, and we're also working to remove the remaining use of it in things like dotnet-format. If Microsoft.VisualStudio.CodingConventions wants to consume ours they're welcome to, but that's their decision for their needs.

**Comment by jmarolf** [comment]
Absolutely. This if more of a discussion for @olegtk and friends. I assume that they do not want to maintain a parser when the compiler team already needs to.

**Comment by olegtk** [comment]
Surely we are open to not having to maintain the parser :) What are our options? source package? @aditya-kadam owns it nowadays.

**Comment by jmarolf** [comment]
Source package was my thought about what would be easiest

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
