### ISSUE TITLE
Batch fix not available when multiple fix actions available

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4078]
I have created an analyzer with code fix provider. The fix provider uses `WellKnownFixAllProviders.BatchFixer`. When the fix provider registers a single code action, VS2015 RTM shows the links to apply the same fix in document/project/solution.

![batch-for-single-fix](https://cloud.githubusercontent.com/assets/10324372/8852345/f965d090-3154-11e5-927d-455dae3d9c35.png)

But when the fix provider instead returns two code actions (with different titles), then the document/project/solution links are no longer shown.

![no-batch-for-multiple-fixes](https://cloud.githubusercontent.com/assets/10324372/8852351/fdc7a168-3154-11e5-8d6f-825233a0c90d.png)

I have read [the documentation](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md), but could not find anything related, other than to use different titles (which I do). 

If this intended behavior or a bug?

**Comment by Pilchie** [comment]
Tag @mavasani.

Do the fixes have different values for `CodeAction.EquivalanceKey`?  That's what's used to ensure the "same" fix is applied at each location.

**Comment by bkoelman** [comment]
Both code actions have a null equivalence key. I changed it to use the same value as title, now it works as expected.

Turns out I misread the documentation and assumed that teh value from Title would be used when no explicit equivalence key is specified:

> Each unique equivalence key for a code fixer defines a unique equivalence class of code actions. Equivalence key of the trigger code action is part of the FixAllContext and is used to determine the FixAll occurrences code fix. Normally, **you** can use the 'title' of the code action as the equivalence key. However, there are cases where you may desire to have different values. Let us take an example to get a better understanding.
