### ISSUE TITLE
classes inheriting from an interface with default implementation can't access it without explicit casting

### ISSUE THREAD

**Issue by bigworld12** [dotnet/roslyn#40788]
**Version Used**: 3.1.100 sdk , .net standard 2.1 project

**Steps to Reproduce**:
```cs
interface IA
{
    string MyString => "hey";
}
class AImp : IA
{
    public string OtherString => MyString + " dotnet";
}
```

**Expected Behavior**:
should work fine

**Actual Behavior**:
getting an error "the name `MyString` doesn't exist in the current context"

**Work Around**:
explicit casting 
```cs
interface IA
{
    string MyString => "hey";
}
class AImp : IA
{
    public string OtherString => ((IA)this).MyString + " dotnet";
}
```
---
cf : https://github.com/dotnet/roslyn/issues/17952

**Comment by gafter** [comment]
It has long been the case that methods in an interface are not inherited into classes that implement that interface.  The default implementation for the method doesn't change that.  The compiler is behaving as designed.
