### ISSUE TITLE
Complete hang in goto-def

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40784]
32bit dump uploaded here: https://drive.google.com/file/d/1itYGyyu2g9Mn2NC5wRtwbiUB1uKGZwxy/view?usp=sharing

This is in:
![image](https://user-images.githubusercontent.com/4564579/71924772-878e2b80-3144-11ea-825c-ccf42cf947af.png)

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
This is a dupe of #40455.
