### ISSUE TITLE
EditorConfig - Keep case statement on same line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/865866/editorconfig-keep-case-statement-on-same-line.html)._

---
EditorConfig allows for a lot of configuration in your styling but I cannot find any combination of settings that works for the common case of case statements with a single statement.

```csharp
switch (input)
{
    case 1: Console.WriteLine("1"); break;
    case 2: Console.WriteLine("2"); break;
    case 3: Console.WriteLine("3"); break;
};
```

It is very common to have a single statement (plus the `break`) in a case statement. Most styling I've seen prefers to have the case label and the statement on the same line. This is similar to single line `if` statements being kept on the same line. However if you format the document, irrelevant of `editorconfig` settings then you get this.

```csharp
switch (input)
{
    case 1:
        Console.WriteLine("1");
        break;
    case 2:
        Console.WriteLine("2");
        break;
    case 3:
        Console.WriteLine("3");
        break;
};
```

You then have to go back and fix your cases. It would be nice if you could set an option to keep case statements on the same line as the case label . Personally I use a block statement if there is more than 1 statement, besides the break, so ideally the setting would be to keep the statement on the same line as the label if it is not a block statement and/or has only a single statement. but the `break` statement should not be included in the count because this is required for non-empty case labels so it shouldn't impact anything and resolves this formatting issue.

```csharp
switch (input)
{
    case 4: break;
    case 5: break;
};
```

```csharp
switch (input)
{
    case 4:
        break;
    case 5:
        break;
};
```

**Comment by jinujoseph** [comment]
@mavasani is there an option to do this today ?

**Comment by mavasani** [comment]
I am not sure. @CyrusNajmabadi or @sharwell would probably know.

**Comment by CyrusNajmabadi** [comment]
There is not.  but i would consider the current behavior a bug.  The formatter is designed to "keep single line constructs on a single line".  A 'case' section of a switch should follow this behavior.

**Comment by sharwell** [comment]
The requested behavior can already be enabled by setting the following option in .edtiorconfig:

```
csharp_preserve_single_line_statements = true
```

**Comment by CyrusNajmabadi** [comment]
Yup.  I cannot repro the issue myself.  It seems like it's working properly.  The only thing i *can* repro is this:

```c#

        switch (input)
        {
            case 1: case 2:
                Console.WriteLine("1"); break;
        }
```

This formats to:

```c#
        switch (input)
        {
            case 1:
            case 2:
                Console.WriteLine("1"); break;
        }
```

That's not particularly desirable to me as there are times when you want to have all the cases simply stated in a single line.  However, it's not a huge deal IMO.
