### ISSUE TITLE
Symbol recognition improvement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/854499/symbol-recognition-improvement.html)._

---
In the situation where we have just created a new class and many of the "using" directives are missing.

It would be great if VS2019 Intellisense was able to utilise an unrecognised but repeated symbol in the current file I am typing, on the basis that "if it's in the current file, I'll assume it'll make sense when usings are added."  
 
eg.

```csharp
public class Example
{
   public Example( IUnrecognised instance )
   {
      _instance = instance;
   }
}
```

Obvioulsy IUnrecognised is not picked up by Intellisense, on the basis the using provides not linkage.  So if I now try to type...

```csharp
public class Example
{
   public Example( IUnrecognised instance )
   {
      _instance = instance;
   }
   IUnreco... 
}

```

... in order to declare the private member _instance, I have to type it completely by hand.  Not a huge deal, admittedly, but it's a departure from how 95% of typing code feels.

It would be nice if by the time I had type IUn... Intellisense had figured out that a local symbol in the file matched this, and offered me text completion on the basis of that earlier symbol.

The point being, I want to express code at this point, not stop and hook all the background library references up, just to make typing feel right - I can do that in a minute when the basic code is in place.

---
#### Visual Studio Feedback System on 12/12/2019, 09:50 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @genlu does completion of unimported type help here

**Comment by sharwell** [comment]
I like this idea. Here are some specific improvements that could occur:

* Members of an unbound symbol could present completion with a builder instead of limiting to members of System.Object
* An unknown type name at a type reference location in the current scope could trigger future completion lists in the scope to offer that name as a type, even though it is not yet bound
* An unknown member name at a member reference location could augment completion later in the same scope

**Comment by CyrusNajmabadi** [comment]
Blast from the past.  I wrote this feature back in 2005.  It allowed you to complete an word at any point to any other word 'in scope' (i.e. in the file somewhere).  This was also super useful when you were in comments and wanted to complete out a word you had used in the file.  Or, conversely, if you had written an identifier in a comment and now wanted to complete to that in your code.

**Comment by genlu** [comment]
@jinujoseph Yea, I believe this particular scenario would be helped by import completion, i.e. when you type `IUnrecognised` in the code sample above (either for the very first time as the parameter type, or later as the field type), it would be provided by completion and selecting it would add the proper using.

>  I wrote this feature back in 2005. It allowed you to complete an word at any point to any other word 'in scope' (i.e. in the file somewhere). 

@CyrusNajmabadi sounds like this would add many items to the list as noise (e.g. words from comments which usually wouldn't be used in actual code). Are there more restrictions on what words will be qualified?

**Comment by CyrusNajmabadi** [comment]
We didn't add it to the completion list.  We did let you complete to it with ctrl-space.  It was actually a little smarter too.  Say you had `foo$$bar` and there was `fooabcdefghijkbar` in the file somewhere.  We would complete out the middle section.  Basically, the feature was "at the point i'm at, can i 'complete out' the word i'm in to match something else in this file?  hitting ctrl-space would then cycle through potential matches.

**Comment by genlu** [comment]
@CyrusNajmabadi Oh I see, this sounds like a good idea.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Completion now does add these imports, as does pasting.
