### ISSUE TITLE
Add Item does not support Enum type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40798]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/857268/add-item-does-not-support-enum-type.html)._

---
With re:sharper i used to be able to add items of type enum. Can we please support that type?

**Comment by jinujoseph** [comment]
cc @mikadumont can we get a screenshot of this feature

**Comment by kendrahavens** [comment]
User added screen shot:
![image](https://user-images.githubusercontent.com/8293542/72027188-ef22a480-3232-11ea-8bab-d3a0b24702ea.png)

**Comment by CyrusNajmabadi** [comment]
This is a request for template support, which is out of scope for roslyn.
