### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "Open_Documents_and_Projects"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40809]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Open Documents and Projects

ID:
0; "Open_Documents_and_Projects"

File Name:
VisualStudio\Core\Def\xlf\ServicesVSResources.xlf

==========================================
Query:
Is Open a verb or an adjective here, i.e. are the documents and projects open already or is this the action to open them?

**Comment by jasonmalinowski** [comment]
@PDostalek Open is an adjective. This is saying "process documents that are already open". Did we also make further changes here @mavasani?

**Comment by mavasani** [comment]
Yes, I just removed this resource string yesterday and replaced it with "Open documents"

**Comment by PDostalek** [comment]
thx for reply
