### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "Extract_interface"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40807]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Extract interface...

ID:
0; "Extract_interface"

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf

==========================================
Query:
Is "Extract" an imperative, infinitive or noun?

**Comment by ryzngard** [comment]
@PDostalek "Extract" is a commanding verb in this context, which makes it imperative.

**Comment by PDostalek** [comment]
thanks
