### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "Suppress_or_Configure_issues"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40806]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Suppress or Configure issues

ID:
0; "Suppress_or_Configure_issues"

File Name:
EditorFeatures\Core.Wpf\xlf\EditorFeaturesWpfResources.xlf

==========================================
Query:
Please clarify what "Configure issues" means.

**Comment by mavasani** [comment]
Configure is used in the context of https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019. The configure sub-menus allow users to either change the effective severity of reported diagnostics (https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#automatically-configure-rule-severity) OR change the options passed to the analyzers to change the semantics of analyzer execution.

**Comment by PDostalek** [comment]
Thanks for reply
