### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "Convert_to_switch_expression"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40805]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Convert to 'switch' expression

ID:
0; "Convert_to_switch_expression"

File Name:
VisualStudio\Core\Def\xlf\Commands.vsct.xlf

==========================================
Query:
We assume "switch" is not localizable. Just an expression . Please confirm

**Comment by dpoeschl** [comment]
Hi @PDostalek,

`switch` is a keyword in C#, and should not be localized.

**Comment by PDostalek** [comment]
Thanks
