### ISSUE TITLE
"Stand-Alone Code Analysis Tool" project template doesn't build by default

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#4080]
When you create a new project from this template and hit F5, the project doesn’t build:

![cannotstartdebugging](https://cloud.githubusercontent.com/assets/11762653/8853678/b8422dbe-3110-11e5-88f9-7e37375559a3.png)

because it is not configured to build by default:

![notconfiguredtobuild](https://cloud.githubusercontent.com/assets/11762653/8853711/df3c91de-3110-11e5-9cf0-414b344bc494.png)

**Comment by jmarolf** [comment]
Can't reproduce this.  @lgolding please let me know if you discover what caused this.

**Comment by lgolding** [comment]
Thanks Jonathon. I will close this for now. I'll reopen if I see it again.

**Comment by TheJP** [comment]
I have the same problem
