### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "Extract_method_plus_local"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40808]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Extract method + local

ID:
0; "Extract_method_plus_local"

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf

==========================================
Query:
Does "local" mean "local data?"

**Comment by ryzngard** [comment]
In this case local is a local variable that may be moved into the extracted method

**Comment by PDostalek** [comment]
Thank you
