### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "discard"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#40804]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
discard

ID:
0; "discard"

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf

==========================================
Query:
Please provide context details
Is "discard" a verb or a noun ?

**Comment by mavasani** [comment]
Please see https://docs.microsoft.com/en-us/dotnet/csharp/discards for context.
