### ISSUE TITLE
IDE0059 "unnecessary assignment" appear in loop and local function 

### ISSUE THREAD

**Issue by pendenaor** [dotnet/roslyn#40843]
**Version Used**: 
Visual studio 2019 community 16.4.2
csc version 3.4.1-beta4-19610-02 (c4e5d138)

**Steps to Reproduce**:
Copy / Paste this snippet
```cs
namespace Sample
{
    public class Test
    {
        public static void Main()
        {
            var test = true;
            var rng = new Random();

            void TestOn()
            {
                test = true;
            }

            while (rng.Next() == 1)
            {
                if (rng.Next() == 2)
                {
                    if (test) continue;
                    TestOn();
                }

                if (rng.Next() == 3)
                {
                    break; // if this line is commented, the warning vanish
                }
                else
                {
                    test = false;
                }
            }
        }
    }
}
```
**Expected Behavior**:
No warning.

**Actual Behavior**:
A warning appears.

**Comment by allisonchou** [comment]
I could no longer get this bug to repro in 16.8 Preview 2.1. If you continue to see this issue, please let us know.

**Comment by CyrusNajmabadi** [comment]
@allisonchou could you create a test case that validates this?   Thanks!

**Comment by allisonchou** [comment]
Actually, upon further investigation, I'm not sure that this is even a bug.
The warning appears on the line `test = true`, which I don't believe has any bearing on the rest of the code. Even if `test` is set to true on that line, we either break out of the loop *or* test is set to false before we go through the next iteration of the while loop.
@CyrusNajmabadi, is this assessment correct?

**Comment by CyrusNajmabadi** [comment]
That's a really good question.  @mavasani to validate if the flow analysis really is that good, or if this indicates a bug for other cases.

**Comment by mavasani** [comment]
@allisonchou's analysis is correct, this is by design. It can be confirmed by making either of the following changes to the test code:

1. Add an explicit read for `test`, either just before `break;` or just after the end of loop, say add a statement `Console.Write(test);`
2. Make the break conditional, i.e. change `break;` to `if (rng.Next() == 4) break;`, so there is a possible back edge in the loop where value written to `test` in the local function `TestOn` could be read.

**Comment by CyrusNajmabadi** [comment]
That is very cool  thanks for confirming this Allison and Manish!
