### ISSUE TITLE
Add Type Conversion to C# Refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40846]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/879385/add-type-conversion-to-c-refactoring.html)._

---
When using VB.NET, I was able to add type conversion (CInt, CBool, CDbl, CType, etc.) using Visual Studio's refactoring capabilities. However, I cannot seem to find this for type conversion in C#. I would like to suggest/request this addition to the refactoring capabilities of Visual Studio 2019. Thank you.

---
#### Visual Studio Feedback System on 1/8/2020, 11:29 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out as we re unlikely to change these vb experiences.
