### ISSUE TITLE
Missing Core Assembly on TypeSymbols (MissingCorLibrarySymbol and TopLevel)

### ISSUE THREAD

**Issue by rog1039** [dotnet/roslyn#40841]
**Version Used**: 
3.4.0.0

**Steps to Reproduce**:

I have a repository with two solutions that illustrates the problem. 
Repository is [here](https://github.com/rog1039/RoslynQuestion).
* RoslynTestSolution.sln - this is the code I wish to analyze with Roslyn
* RoslynAnalysis.sln - contains the code that uses Roslyn to analyze RoslynTestSolution.sln

The analysis solution contains two xUnit test cases which show the problem. The output from the test is below:

The test solution has two projects:
* Project1
* Project2

Each project has a class, Class1 and Class2 respectively. Each class has a single int property called Id1 and Id2 respectively. When examining the IPropertySymbol of the two properties, the `Type` properties are different. In `Class1.Id1`, the type property is an instance of `PENamedTypeSymbolNonGeneric` whereas for `Class2.Id2` the Type property is an instance of `TopLevel` which has a containing assembly of `<Missing Core Assembly>`.

There is a project reference from Project2 to Project1. Interestingly, I do not get the 'missing core assembly' issue if I remove that project reference.

**Expected Behavior**:

```
Property Type: int:mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089      | - Property: Project1.Class1.Id1
Property Type: int:mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089      | - Property: Project2.Class2.Id2
```

**Actual Behavior**:

```
Property Type: int:mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089      | - Property: Project1.Class1.Id1
Property Type: int:<Missing Core Assembly>, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null   | - Property: Project2.Class2.Id2
```

So it is not clear to me why the Id2 property in the second project does not resolve properly, but it does on the first project. Am I doing something wrong here?

I also have tried two different ways of retrieving the semantic model. Each way is a separate unit test. However, they give the same result. So as a second question, is there any reason to prefer either 
```csharp
var projectCompilation = await project.GetCompilationAsync();
var semanticModel = projectCompilation.GetSemanticModel(syntaxTree);
```
or
```csharp
//Never called await project.GetCompilationAsync(); in this example
var semanticModel = document.GetSemanticModelAsync();
```
over the other?

**Comment by rog1039** [comment]
I expanded on the code in my repro case to show some additional behavior that doesn't seem correct. I added properties like the following to the classes under analysis by Roslyn:
```csharp
public int Id2A { get; set; }
public Int32 Id2B { get; set; }
public string Description2A { get; set; }
public String Description2B { get; set; }
public DateTime DateTime1 { get; set; 
```
Initially, I had only one property with a type of ```int```.  When I run the analysis on the code above, I get the following output:
```csharp
Property Type: int               :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Id1A
Property Type: int               :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Id1B
Property Type: string            :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Description1A
Property Type: string            :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Description1B
Property Type: System.DateTime   :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.DateTime1

Property Type: int               :<Missing Core Assembly>, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null             | - Property: Project2.Class2.Id2A
Property Type: Int32             :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.Id2B
Property Type: string            :<Missing Core Assembly>, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null             | - Property: Project2.Class2.Description2A
Property Type: String            :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.Description2B
Property Type: DateTime          :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.DateTime1
```

So not only are int/Int32 and string/String resolved differently from each other, the uppercase version is stated as having a containing assembly of my project rather than mscorlib. In the first project, Roslyn understands that string and String are the same type but in the second project Roslyn doesn't seem to understand this.

**Comment by rog1039** [comment]
I expanded on the code above to test classes outside of mscorlib. I added properties referencing types in System.Xml (automatically included in my project from the New Project wizard) and Newtonsoft.Json (added via nuget) to explore further.

So there seems to be two different but likely related issues here. 
1. Project2 has unresolved TypeSymbol's for all types referenced that are from external assemblies. Seems that since Project2 has a project reference to another project in the solution that Roslyn is unable to resolve any types from external assemblies. I did add a property that referenced a Project1 type and that was resolved correctly. Latest output is below:
2. Perhaps caused by 1 above, Roslyn does not recognize that int/Int32, string/String, and similar keyword types are the same type.

Code from Project1
```csharp
public class Class1
{
	//mscorlib types
	public int Id1A { get; set; }
	public Int32 Id1B { get; set; }
	public string Description1A { get; set; }
	public String Description1B { get; set; }
	public DateTime DateTime1 { get; set; }
	
	//External assembly types
	public XmlComment XmlComment { get; set; }
	public JsonReader JsonReader { get; set; }
}

public class Class1B{}
```

Code from Project2
```csharp
public class Class2
{
	//mscorlib types
	public int Id2A { get; set; }
	public Int32 Id2B { get; set; }
	public string Description2A { get; set; }
	public String Description2B { get; set; }
	public DateTime DateTime1 { get; set; }
	
	//External assembly types
	public XmlComment XmlComment { get; set; }
	public JsonReader JsonReader { get; set; }

	//Referenced project type
	public Class1B Class1B { get; set; }
}
```

And the output from the unit test:

```csharp
Property Type: int               :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Id1A
Property Type: int               :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Id1B
Property Type: string            :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Description1A
Property Type: string            :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.Description1B
Property Type: System.DateTime   :mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089                | - Property: Project1.Class1.DateTime1
Property Type: System.Xml.XmlComment:System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089              | - Property: Project1.Class1.XmlComment
Property Type: Newtonsoft.Json.JsonReader:Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed        | - Property: Project1.Class1.JsonReader


Property Type: int               :<Missing Core Assembly>, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null             | - Property: Project2.Class2.Id2A
Property Type: Int32             :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.Id2B
Property Type: string            :<Missing Core Assembly>, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null             | - Property: Project2.Class2.Description2A
Property Type: String            :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.Description2B
Property Type: DateTime          :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.DateTime1
Property Type: XmlComment        :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.XmlComment
Property Type: JsonReader        :Project2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.JsonReader
Property Type: Project1.Class1B  :Project1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null                            | - Property: Project2.Class2.Class1B

```

My [repository ](https://github.com/rog1039/RoslynQuestion) has all the latest changes.

**Comment by glitch100** [comment]
@rog1039 did you ever resolve what was causing this? I seem to get it occasionally on a netstandard or netcore project for `CancellationToken`s

**Comment by rog1039** [comment]
I could not resolve this. I assume this is a bug in Roslyn and that it cannot resolve symbols in projects that contains project-to-project references. This sounds crazy to me because it seems like a bug that people would run into often. Unfortunately, I cannot find any reference of this issue impacting anyone else.

I find it interesting that you receive this occasionally because I receive this every single time. I've never seen it work correctly.

I never heard back from anyone on this issue but @jcouv did move it the 16.5 milestone so I sort of took that to mean they will fix this for version 16.5 but really I do not know.

**Comment by glitch100** [comment]
I think it's down to the project the inconsistency sorry. I hope it does get fixed as it's causeing me serious issues haha

**Comment by rog1039** [comment]
I hear you. I can't go forward with my project either until this is fixed.

**Comment by jaredpar** [comment]
Moving to IDE as it's MSBuild workspace evaluation

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard any more reports on this.
