### ISSUE TITLE
Differences in expression body for lambdas and enums

### ISSUE THREAD

**Issue by daveaglick** [dotnet/roslyn#4085]
I'm noticing some differences in expression bodies when using enums. Specifically, the Roslyn compiler appears to add a `Convert` expression whereas the previous compiler did not. Take the following code:

```
using System;
using System.Linq.Expressions;
					
public class Program
{
	public enum TestEnum
    {
        Foo,
        Bar
    }
	
	public static void Main()
	{
		Expression<Func<TestEnum, bool>> expected = x => TestEnum.Bar == x;
		Console.WriteLine(expected.Body.ToString());
	}
}
```

The old compiler outputs `(1 == Convert(x))`. Roslyn outputs `(Convert(Bar) == Convert(x))`.

I would understand if this is fixing a bug or a premature optimization or something with the old compiler, but the odd thing is that Roslyn itself doesn't seem to have the same hangups about optimizing the enum value when used directly (I.e., not via an `Expression`). If you put the following into TryRoslyn:

```
using System;
using System.Linq.Expressions;

public class C {
    public enum TestEnum
    {
        Foo,
        Bar
    }
    
    public void M() 
    {
        Func<TestEnum, bool> compiled = x => TestEnum.Bar == x;
    }
}
```

you can see that the relevant part decompiles to `return C.TestEnum.Bar == x` or the following IL which does not contain any type of conversion for `TestEnum.Bar`:

```
IL_0000: ldc.i4.1
IL_0001: ldarg.1
IL_0002: ceq
IL_0004: ret
```

This might be related to #3292, but it's different enough I figured I'd open a new issue so that it doesn't get lost in the noise. Feel free to close and reference from the other one if it's the same thing.

**Comment by gafter** [comment]
@VSadov I think you were looking at this issue?
