### ISSUE TITLE
[Flaky] CSharp_FixupSpanDuringResolvableConflict_NonReferenceConflict is flaky

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#40850]
Seen in https://dev.azure.com/dnceng/public/_build/results?buildId=477708&view=ms.vss-test-web.build-test-results-tab&runId=15180274&resultId=156922&paneView=debug

**Comment by sharwell** [comment]
Duplicate of #29483

**Comment by dibarbet** [comment]
I could have sworn I searched for it and didn't find anything...

**Comment by sharwell** [comment]
It's a different test name, same underlying cause. It affects about a dozen tests.
