### ISSUE TITLE
InitializeAsync of AbstractPackage invokes MEF synchronously

### ISSUE THREAD

**Issue by ZoeyR** [dotnet/roslyn#40860]
The following line in an async package initializer creates the MEF service synchronously.

https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage%602.cs#L73

MEF is an async capable service and should be retrieved on a background thread via `GetServiceAsync` to avoid UI delays.

**Comment by sharwell** [comment]
Unfortunately there is no asynchronous API for MEF, so this is our only option for these services.

**Comment by ZoeyR** [comment]
@sharwell that's not the issue. Right now the `ComponentModel` property gets the `IComponentModel` service itself synchronously. That service can be retrieved in an async fasion.

**Comment by CyrusNajmabadi** [comment]
@sharwell can we just do this?

**Comment by CyrusNajmabadi** [comment]
Does thsi still apply.  Looking at the code we now have:

![image](https://user-images.githubusercontent.com/4564579/220766229-d80e277a-8016-4a3b-b6f2-ccd6e0f304df.png)

So this doesn't seem to apply: > Right now the ComponentModel property gets the IComponentModel service itself synchronously. That service can be retrieved in an async fasion.

Given that, i think this can be closed out.  Please reopen if you disagree.
