### ISSUE TITLE
Populate HelpLink dictionary for CS compiler errors

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/roslyn#40863]
I'd like to populate the HelpLink's dictionary for CS compiler messages, so that each compiler error links to the relevant docs.microsoft.com page, rather than doing a Bing search as current behaviour. See https://github.com/dotnet/docs/issues/16448 for original discussion.

https://github.com/dotnet/roslyn/blob/bbe84f5b1551eff5fff8fc951c31455a81b32339/src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs#L71-L79

My plan would be to generate links of the format `https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-messages/cs{ERR_CODE}`. This would mean help links would also be generated for compiler errors where no docs page yet exists - for these I plan to add a redirect to [this page ](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error) in the docs repo. Adding a redirect means we don't have to maintain a specific list of links in roslyn, and also that the addition/removal of pages remains fully within the docs team's control.

Does this fit with what the team are looking for here? I'd be happy to do a pull request for this. 🙂 

cc @mavasani @mairaw @BillWagner

**Comment by mavasani** [comment]
Tagging @jaredpar @agocke

**Comment by sharwell** [comment]
It was my understanding that the current service can be updated to return the correct link for known IDs without needing to make any changes to the Roslyn implementation itself.

**Comment by agocke** [comment]
Not sure what the appropriate implementation is, but I like the idea.
