### ISSUE TITLE
Filter visible code to user defined levels

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40872]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/841650/in-visual-studio-provide-code-levels.html)._

---
<p>... to solving some Cross-Cutting Concerns (ccc) in development.  </p><p>The idea to solve the problem of ccc is to create mutliplie level<br> of code (code-lines) for one class/file at design time.<br> These level are mixed togheter by the ide at runtime or can also viewed<br> by designtime.</p> <p>The system is more syntaxtic sugar of an ide feature as it is a pattern or archtecture, but<br> it is focused to make the readability of code better without  disadvantages of performance lossing or hardreading code like in the  AOP.</p> <p>This is a typcial behavior in drawing programs (for example,  paint.net, Inkscape, …), to focus on one part of a picture. So why not  use this for coding?</p> <p>The following is a much simplified example:</p><p>

![Imgur](https://imgur.com/3YWklTT.gif)

---
#### Kendra Havens [MSFT] on 1/3/2020, 06:36 PM: 

<p>Interesting idea! Thank you for taking the time to provide feedback. Do you have an idea of what would define these levels in code? In your gif you are hiding WriteLines since they don’t contribute to the business logic. I’d be interested to see this idea expanded.</p>

#### Florian Hilfenhaus on 1/8/2020, 11:48 AM: 

<p>First i am sorry for the late response. I would let the user define this levels. So you can rename "Business-Level" in everything you want. And you can add more level if you like (but i think more than three and you will lost overview). If you code in the "Business"-Level VS tracks the lines you added. if you swtich to higher level this lines are hidden.<br>In the ground level all are included. Hope this answers your question, if not please contact me and i try to be more precice.</p>

#### Kendra Havens [MSFT] on 1/8/2020, 11:56 AM: 

<p>Thank you for the additional info! It would help to build out the idea a bit more so it can be written as a proposal on our open source GitHub repo for further design discussion with the community.</p><p>How would a user specify some arbitrary code as belonging in a certain level?</p><p>Where would these defined levels be edited? Are you envisioning a Tools &gt; Option, a new window dialog, something in EditorConfig, etc? </p>

#### Florian Hilfenhaus on 1/8/2020, 00:11 PM: 

<p>In my mind there is an entry under the views -&gt; code-level (your suggestion with an entry in option could be a good idea to define default layer for different vs projects). This will open the window i have provided in my gif. In that window you can add a level by hitting the plus button and remove a level by hitting the remove level (his will delete the current selected level). Mybe the default level nameing is simple level-0,level-1,level-2,level%n%....With a double click on a level you can change the name. I think to have a good overview it is important that VS shows the current level at the botton of vs (where the line, column counter is) or that each layer defines a color for the code.</p>

#### Kendra Havens [MSFT] on 1/8/2020, 02:18 PM: 

<p>Thank you. Adding/removing/renaming levels makes sense. How would a user specify that "Writeline" is excluded from the "business-level", for example?</p>

#### Florian Hilfenhaus on 1/9/2020, 00:47 PM: 

<p>The idea was that it is context sensitve (it depends of the current layer). For example if you have select the "1"-level you can write a line "var userPwd = "1234567!@";" this line is now automaticly linked to the level "1". If you switch to the "0"-level and write "System.Diagnostics.Trace.WriteLine("Hello World");" this line is connected to the level "0" and all above are merged down.
I am not sure if your idea to configure the "Writeline" is a better aproach.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
