### ISSUE TITLE
VS complete hang in navigate-to

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40898]
![image](https://user-images.githubusercontent.com/4564579/72187566-e05ffd00-33ac-11ea-87e3-8e8ff8a7c3ca.png)

Uploading 32bit dump now.

This is 16.4.2.

**Comment by jinujoseph** [comment]
Can you see if you submit as a Feedback ticket with trace attached.

**Comment by CyrusNajmabadi** [comment]
Going to close out now that 16.5p2 is out.  Will open a new issue if i still run into things.
