### ISSUE TITLE
Strange yellow-bad notification about TFMs and nuget TMs.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40899]
I have no idea what this means or why roslyn tells me this:

![image](https://user-images.githubusercontent.com/4564579/72190206-d5f53180-33b3-11ea-900b-713ea7702652.png)

Hoping someone knowledgeable about this area can explain/fix.  Note this is when opening roslyn.sln

**Comment by jinujoseph** [comment]
cc @drewnoakes , @tmeschter  is this coming from project system

**Comment by drewnoakes** [comment]
Yes, from the project system. @davkean added the message to indicate when a project's configuration is invalid such that you can expect other things to not work.
