### ISSUE TITLE
Is inline rename functionality can be used by languages other than Roslyn based?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#4089]
Is it possible to use inline rename in languages other than based on Roslyn?
I mean is this Visual Studio SDK API or some Roslyn-specific feature?

**Comment by dpoeschl** [comment]
It is currently a Roslyn-specific feature.

**Comment by xperiandri** [comment]
So this UI when an identifier is highlighted with green background is done by Roslyn integration into Visual Studio and is not exposed via public API, isn't it?

**Comment by Pilchie** [comment]
That is correct.  Tagging @markw-t from the editor team, as we've considered moving it to the VS Editor layer instead.

**Comment by xperiandri** [comment]
@markw-t do you have something to add?
We want to use this in F# Power Tools to provide consistent experience across languages.

**Comment by markw-t** [comment]
Not really; it'll be considered as a potential change for future releases, but we don't have concrete plans yet I'm afraid.

**Comment by xperiandri** [comment]
It is a shame.
Such gaps reduce interest to F# within .NET community...

"Future releases" mean VS vNext or VS 2015 Update X?

**Comment by markw-t** [comment]
No concrete plans at all; I'm afraid I can't say when this might happen at this point.
