### ISSUE TITLE
InlineRenameSession mixes data and UI operations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#40890]
See #34254

https://github.com/dotnet/roslyn/blob/d9ed55cff24ccc480f444e5fe75f17460d4cd3ca/src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameSession.cs#L300-L304

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to change this, we should chance this.
