### ISSUE TITLE
CS8424 being raised on non-async iterators is too aggressive.

### ISSUE THREAD

**Issue by casperOne** [dotnet/roslyn#40893]
**Version Used**: 

C# 8.0
.NET Core SDK 3.1.100

I have the following method:

````csharp
public static IAsyncEnumerable<string> GetAsyncEnumerable(
    this TextReader reader,
    [EnumeratorCancellation] CancellationToken cancellationToken
)
{
    // Validate parameters.
    if (reader == null) throw new ArgumentNullException(nameof(reader));

    // The implementation.
    async IAsyncEnumerable<string> Implementation() {
        // The line.
        string line;

        // While the line is not null.
        while (!cancellationToken.IsCancellationRequested &&
            (line = await reader.ReadLineAsync().ConfigureAwait(false)) != null
        )
            // Yield
            yield return line;
    }

    // Return the implementation.
    return Implementation();
}
````
I am currently getting CS8424 on the `cancellationToken` parameter.

I believe this is too aggressive. 

The desire here is to perform parameter checks on the inputs at the call site, not when the enumerable is first iterated.

[This is done often in LINQ over `IEnumerable<T>`](https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Select.cs#L17).   As you can see from the linked example, there is no usage of `yield return`; it delegates to another method/class which may or may not use an iterator.

I wish to do the same with `IAsyncEnumerable<T>`; before anonymous functions, the way to do this was to have a private method which was the iterator, which was called from the method that performed the parameter checks.

That's not possible in this case; while I can implement the async iterator in another private method, I still have to apply the `EnumeratorCancellation` attribute to the outermost method so that the compiler will properly wire up the `WithCancellation` call.

Note, some might say that with C# 8.0, we don't have to do null checks if nullable reference types are enabled.  This isn't completely true (for a number of reasons and is a separate issue) but more importantly, this isn't only about nullable reference checking, it can be any kind of logic check that needs to be done at the call site *before* iteration occurs.

Looking back at the language design meeting notes all I can find about [cancellation and async iterators is from the 4/22/2019 meeting](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-04-22.md#defaultcancellationattribute-and-overridinghidinginterface-implementation).

That seems to have led to #39961 and possibly #35166 (although the latter may have spurned the topic at the LDM), but I don't see anything specific to saying that the method where the attribte is applied on the parameter must be on an *iterator*.

It's possible from the wording of the proposed spec that this may be intended, specifically (emphasis mine):

> We find that a reasonable compromise to support both scenarios in a way that is convenient for both producers and consumers of async-streams is to use a specially annotated parameter in **the async-iterator method**.

If that's the case, and I should take this to https://github.com/dotnet/csharplang, then apologies, I'll do so.

Thanks in advance.

**Comment by jcouv** [comment]
CS8424 is by-design and appropriate for the code you shared. This method is returning `IAsyncEnumerable<>` but is not `async`, so the compiler is not producing an async-iterator for this code. The `[EnumeratorCancellation]` attribute is ignored/useless there. 

What you want to do here is add `[EnumeratorCancellation] CancellationToken cancellationToken` to the local function (which is an async-iterator) and remove the attribute `[EnumeratorCancellation]` from `GetAsyncEnumerable` method.

**Comment by casperOne** [comment]
@jcouv Thanks for the response, much appreciated.

Does that mean there should *not* be a `CancellationToken` on the `GetAsyncEnumerable` method as well?

**Comment by jcouv** [comment]
@casperOne No, it's fine to keep the `CancellationToken` parameter on `GetAsyncEnumerable`. If the caller of `GetAsyncEnumerable` has a cancellation token to pass in, then it can just be passed in. If the caller doesn't have a cancellation token, then whoever gets handed the collection later on can push their own cancellation token with `.WithCancellationToken`.
I have a short write-up on this that may help clarify: http://blog.monstuff.com/archives/2019/03/async-enumerables-with-cancellation.html

**Comment by casperOne** [comment]
@jcouv If we keep the `CancellationToken` on `GetAsyncEnumerable`, does that mean it needs to be combined with the external `CancellationToken`, like so?

````
public static IAsyncEnumerable<string> GetAsyncEnumerable(
    this TextReader reader,
    CancellationToken externalToken
)
{
    // Validate parameters.
    if (reader == null) throw new ArgumentNullException(nameof(reader));

    // The implementation.
    async IAsyncEnumerable<string> Implementation(
        [EnumeratorCancellation] 
        internalToken
    ) {
        // Combine the cancellation token sources
        using var linked = CancellationTokenSource.CreateLinkedTokenSource(internalToken, externalToken);

        // Get the token.
        var cancellationToken = linked.Token;

        // The line.
        string line;

        // While the line is not null.
        while (!cancellationToken.IsCancellationRequested &&
            (line = await reader.ReadLineAsync().ConfigureAwait(false)) != null
        )
            // Yield
            yield return line;
    }

    // Return the implementation.
    return Implementation();
}
````

Also, what's the guidance here?  Is it generally not advisable to pass a `CancellationToken` to a method that returns `IAsyncEnmerable<T>` if it's not going to attribute the `CancellationToken` parameter with the `EnumeratorCancellation` attribute?
