### ISSUE TITLE
Roslyn codebase contains usages of StartsWith, EndsWith, IndexOf that operate in the current culture, where ordinal comparison is required

### ISSUE THREAD

**Issue by VladimirReshetnikov** [dotnet/roslyn#409]
Roslyn codebase contains usages of StartsWith, EndsWith, IndexOf that operate in the current culture, where ordinal comparison is required. This could lead to unexpected results in some cases. e.g.
```cs
"\u0640.".StartsWith(".") // => true
```

They should be replaced with 
```cs
"\u0640.".StartsWith(".", StringComparison.Ordinal) // => false
```
or other appropriate code.

**Comment by sharwell** [comment]
I have a couple questions:

1. Do all of the cases you observed use the `StartsWith` (or equivalent) method that does not specify a `StringComparison`, or do some instances explicitly provide `StringComparison.CurrentCulture` where they should provide `StringComparison.Ordinal`?

1. Do you have a suggestion for a general approach to identify and avoid these situations in the future?

**Comment by VladimirReshetnikov** [comment]
1. Most of cases I've seen just use overload with single argument that use current culture.
2. I suppose, it's possible to create an analyzer that detect such cases.

**Comment by theoy** [comment]
Nice catch, @VladimirReshetnikov! :smile:

**Comment by VladimirReshetnikov** [comment]
@jaredpar 

In some places there is an incorrect assumption that a string length is greater or equal to its prefix length. Here is a simplified example:

```cs
using System;

class Program
{
    static string DropPrefixIfPresent(string text, string prefix)
    {
        if (text.StartsWith(prefix))
        {
            return text.Substring(prefix.Length);
        }

        return text;
    }

    static void Main()
    {
        Console.WriteLine(DropPrefixIfPresent("REACT", "RE")); // ACT
        Console.WriteLine(DropPrefixIfPresent("REACT", "FW")); // REACT
        Console.WriteLine(DropPrefixIfPresent("ÆON", "AE"));   // N
        Console.WriteLine(DropPrefixIfPresent("ÆON", "AEON")); // System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
    }
}
```
