### ISSUE TITLE
[VB] IntelliSense is incorrectly showing instances members where only shared members are allowed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4090]
In VS 2015 RTM, IntelliSense is incorrectly showing instances members where only shared members are allowed.

C#:
![image](https://cloud.githubusercontent.com/assets/1103906/8864194/10122a24-3154-11e5-8389-b0819615c491.png)

VB:
![image](https://cloud.githubusercontent.com/assets/1103906/8864181/e8c71d94-3153-11e5-8957-3e1d2c4b49c4.png)

**Comment by dpoeschl** [comment]
/cc: @rchande I think this was regressed in 5d7006e1. This gets incorrectly interpreted as a "color color" case, which sets ```excludeInstance``` to false.

**Comment by rchande** [comment]
Please verify, @davkean .

**Comment by rchande** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/b525221906ad81605ed40ed54bd833d200c02902
