### ISSUE TITLE
Should `var` in `foreach` be inferred as nullable?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40903]
Relates to https://github.com/dotnet/roslyn/issues/40477

PR https://github.com/dotnet/roslyn/pull/40755 changed the inference of `var` locals to use the nullable version of a type. But `foreach` variables are read-only. Should we make an exception for such variables?

**Comment by jasonmalinowski** [comment]
One important point here: the original inferred type is visible in the IDE -- even if the _diagnostics_ are the same because flow analysis is ultimately used, the IDE still allows the decision to be distinguished.

**Comment by sharwell** [comment]
I believe the same applies to `using` statements and maybe some others?

**Comment by alrz** [comment]
>and maybe some others?

probably `let` in linq. not sure how this could apply to `ref var` though.

**Comment by jcouv** [comment]
From offline discussion with Mads, he feels that regularity is preferable in this case (`var` in `foreach` should be nullable like other `var`s) and that the downside is small in any case.

I'll go ahead and close the issue. Thanks
