### ISSUE TITLE
Fix VisualBasicSyntaxFactsService.IsLeftSideOfCompoundAssignment

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#40917]
VB supports compound assignments, following should be fixed:
https://github.com/dotnet/roslyn/blob/61761f5fe90ec9cf0bfeb9157aea8f89a1555fc3/src/Workspaces/VisualBasic/Portable/LanguageServices/VisualBasicSyntaxFactsService.vb#L1336-L1339

**Comment by mavasani** [comment]
Tag @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
👍
