### ISSUE TITLE
C# rename refactoring; bug with macro-conditional code sections

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40942]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/880432/c-rename-refactoring-bug-with-macro-conditional-co.html)._

---
repro:
```
class CTmp
{
  int tmpA;
  void foo()
  {
    tmpA = 1; // <- rename here
#if false
    tmpA = 2;
#endif
  }
}
```
- Initiate rename refactoring (CTR+R,CTRL+R) of 'tmpA' on indicated position.
- Change identifier to e.g. `tmpB`. 
- Hit Alt+C to `Include comments'. Notice how the identifier in the disabled code section properly also renames.
- Hit Alt+C a few more times if you feel like it, and see how the identifier in the disabled code section toggles between being renamed, and not. Amazing, isn't it? Not so much...
- Make sure `Include comments` is selected.
- Hit return to finalize the refactoring.
- Stare in disbelief at how the -- just recently properly changed -- identifier in the disabled code section reverts back to its old value.

Expected: **Not** discard the displayed interactive preview result upon committing to the refactoring.

---
#### Visual Studio Feedback System on 1/9/2020, 11:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @ryzngard

**Comment by CyrusNajmabadi** [comment]
Closing out.  Renaming with conditional sections is not supported as a conditional section can (and often is) anything (including non-code).
