### ISSUE TITLE
Intellisense yield return completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40949]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/882092/intellisense-yield-return-completion.html)._

---
Intellisense does not complete "yield ret..." as "yield return"

<space> is cursor position when pressing the space key.
_ is cursor

Examples where completion works:
yie<space> => yield
ret<space> => return

This does not generate completion:
yield ret<space> => yield ret _

Expected behavior:
yield ret<space> => yield return _

The intellisense tooltip is consistent with observed behavior.
"return" is strongly highlighted when completion works and softly highlighten when completion doesn't work.

---
#### Visual Studio Feedback System on 1/13/2020, 01:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/13/2020, 11:48 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ivanbasov** [comment]
This is not a regression. It is reproducible in 16.5 as well in 16.4 and in 2017 as well . The code causing the confusion is here: https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L65

The completion provider adds a suggestion item. Then, completion CompleitonSource sets HasSuggestedItem and then ItemManager sets SoftSelection.

If we comment the line above, the following tests fail: 
-  https://github.com/dotnet/roslyn/blob/342b2712e2db77cdb270eb948616406b6b75550f/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb#L4336
- https://github.com/dotnet/roslyn/blob/342b2712e2db77cdb270eb948616406b6b75550f/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb#L4362
- https://github.com/dotnet/roslyn/blob/342b2712e2db77cdb270eb948616406b6b75550f/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb#L4390

**Comment by ivanbasov** [comment]
@CyrusNajmabadi @sharwell the root cause seems to appear for a very long time. Maybe it was intentional. Do you have an idea?

@genlu FYI

**Comment by CyrusNajmabadi** [comment]
Not intentional.  We likely need to special case this.  There is practically zero chance of someone realistically naming a type `yield` at this point, so it would be fine to optimize for the likely case that someone is writing `yield return`.

**Comment by sharwell** [comment]
Even if we don't assume there is no type `yield`, we should be able to quickly check for it in context.

**Comment by mehrdad995gta** [comment]
This still is present in Visual studio comunity Version 16.5.0

**Comment by sageikosa** [comment]
This one has been bugging me since it first started interrupting my flow.  Yield can be auto-completed by pressing the space key (the drop-down shows up with yield selected), whereas return or break (after the yield) does not show up selected in the drop-down list so that pressing space only inserts the text typed.  However, using Tab to select "return" or "break" in context after yield does insert the text with only the minimal "r" or "b" entered.  The ability to select the secondary context keywords with space used to work in some previous version of Visual Studio.  Auto-complete consistency with space has the advantage that often the thumb of one's hand only have to drop to activate, whereas the tab requires either a hand move from home position.
