### ISSUE TITLE
overloading with confusable signatures

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#40941]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/882038/overloading-with-confusable-signatures.html)._

---
assume you have this class:
    public class OverloadingConstructor
    {
        public OverloadingConstructor(string s1, string s2 = "")
        {
         ...
        }
        public OverloadingConstructor(string s2 = "")
        {
         ..
        }
   }

If I create an instance:
                OverloadingConstructor overloadingConstructor = new OverloadingConstructor("set s1");
I thought it'll use the first constructor, but it uses the second.
workaround:
                OverloadingConstructor overloadingConstructor = new OverloadingConstructor(s1: "set s1");
I'd prefer a compiler error "confusable signatures"

(the example project uses the Debug-Output)

---
#### Visual Studio Feedback System on 1/13/2020, 01:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
