### ISSUE TITLE
New not null syntax "is {}" vs "!= null" for structs

### ISSUE THREAD

**Issue by pebezo** [dotnet/roslyn#40957]
**Version Used**: C# 8, .NET Core 3.1

**Steps to Reproduce**:

When using a nullable struct (for example Datetime?) the IDE shows a `Possible System.InvalidOperationException` warning when inside an "if (something is {})" block.

```csharp
DateTime? date = null;

if ((new Random().Next(3) == 2))
{
    date = DateTime.Today;
}

if (date != null)
{
    DateTime bar = date.Value;
    Console.WriteLine("Date is " + date + "-" + bar);
}

if (date is {})
{
    DateTime bar = date.Value;  // <- warning here
    Console.WriteLine("Date is " + date + "-" + bar);
}
```
![image](https://user-images.githubusercontent.com/1287097/72373316-07cd0780-36d6-11ea-8f4e-0655d8701ebd.png)

**Expected Behavior**:

Both "if" statements should behave the same way; no warning on he second "if".

**Actual Behavior**:

The IDE shows a warning, although the program seems to run correctly.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/pull/40892

**Comment by jcouv** [comment]
I verified that we're no longer producing a warning in 16.5p3, as a result of https://github.com/dotnet/roslyn/pull/40892. I'll go ahead and close the issue. Thanks
