### ISSUE TITLE
Proposal: finally/else clause in loops

### ISSUE THREAD

**Issue by jveselka** [dotnet/roslyn#4095]
Note: This proposal is inspired by Python else clause

It is reasonably common to handle differently cases where loop is finished by control condition yielding false (or exhausting enumerator in case of foreach) and cases where loop is finished by break statement.

## Proposed change:
The syntax would allow new form of while statement
```
while-statement:
	while   (   boolean-expression   )   embedded-statement
	while   (   boolean-expression   )   embedded-statement   finally   embedded-statement
```
And the behavior would change
* If the boolean expression yields false, control is transferred to the finally embedded statement or to the end point of the while statement if finally clause is not present.

Analogicaly for the do, for and foreach statements

## Use-case
```C#
for (int i = 0; i < processingLimit; i++)
{
	if (TryFindNugget(databuffer[i], out result))
		break;
}
finally
{
	ProcessingLimitReachedWithoutFindingNugget();
}
```
#### 1) Using boolean local
```C#
bool nuggetFound = false;
for (int i = 0; i < processingLimit; i++)
{
	if (TryFindNugget(databuffer[i], out result))
	{
		nuggetFound = true;
		break;
	}
}
if (!nuggetFound)
{
	ProcessingLimitReachedWithoutFindingNugget();
}
```
#### 2) Using helper false-returnig function
```C#
for (int i = 0; i < processingLimit || ((Func<bool>)(() => { ProcessingLimitReachedWithoutFindingNugget(); return false; }))(); i++)
{
	if (TryFindNugget(databuffer[i], out result))
		break;
}
```
## Keyword considerations:
Feature is small enough not to justify new keyword, so there are two options:
1. `else` - analogical to Python; has symmetry with if statement
2. `finally` - makes probably more sense in context of loops

**Comment by HaloFour** [comment]
C# loops don't have expressions or values, so you couldn't depend on some kind of `Boolean` on which to trigger the conditional.  At best you could try to rely on whether or not a `break` statement was hit, but that isn't very clear either.  I think that this falls into the same category as proposals to extend the loop syntax to make the first iteration special, etc., simply not worth the effort and the current "workarounds" are clearer anyway.

**Comment by svick** [comment]
Neither `finally` nor `else` sound appropriate for this to me. `finally` is a block that *always* executes when control leaves the preceding `try`. What you're proposing is not similar to that.

`else` has already been proposed in #134 to mean a block that executes when the loop doesn't execute at all (e.g. empty collection in a `foreach`). That proposal makes more sense to me than this one.

**Comment by whoisj** [comment]
Maybe call it `lastly`, and exiting the loop early skips it?

```while-statement:
    while   (   boolean-expression   )   embedded-statement
    while   (   boolean-expression   )   embedded-statement   lastly   embedded-statement```

**Comment by HaloFour** [comment]
I think a separate syntax here would just be confusing.  Would it execute if the loop condition was never met?  Would it execute if the code within the loop broke out early?  Would it execute if an exception was thrown?  You're not saving much typing, it's worth it to be explicit with that kind of logic.

**Comment by jveselka** [comment]
I acknowledge all remarks and must admit that in most cases there are better alternatives already present in the language. We don't need to (or even want to) have everything that Python does, right? :-)
