### ISSUE TITLE
FAR (Find All References) to have more group by options

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#40962]
**Version Used**: 
Visual Studio 2019 Preview

**Actual Behavior**:
We currently have the following group by options: 
![image](https://user-images.githubusercontent.com/46729679/95272455-2db2b300-07f5-11eb-80a5-037544be2b80.png)

**Expected Behavior**:
Add more group by options: 
1. Type
2. Type and Member
3. Namespace
4. Namespace and Type
5. Namespace, Type, and Member
6. Folder and File
7. File
8. Project and NameSpace

**Comment by CyrusNajmabadi** [comment]
This would need to go through the platform to support.
