### ISSUE TITLE
FAR (Find All References) UI Updates

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#40963]
Direct customer ask copying here: 

> 1.	Merge references if they are on the same file. If they are on multiple projects but compile from the same source code anyways there is no reason to display the same result 2~6 times.

> 2. Merge occurrences on the same line button/functionality. Very self-explanatory, if it happens multiple times in the same line there’s no need to show multiple results.

> 3. Show reference type icon, if they are the same as the icons shown in the solution explorer even better. It becomes ridiculously easier to see what is a methods and what is a property just by using these icons. (see attached image for example.
![image](https://user-images.githubusercontent.com/46729679/72386321-0c91bb80-36d6-11ea-802a-d0e51a5778cc.png)

**Comment by CyrusNajmabadi** [comment]
We do the merging now.
