### ISSUE TITLE
Clean up GetConvertedTypeWithAnnotatedNullability and GetTypeWithAnnotatedNullability

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#40961]
These two extension methods predate the compiler's nullable types API where the top level nullability is baked into the ITypeSymbol. These were used to do the IDE wrapping when you had a TypeInfo in hand. When we moved to the newer compiler API we removed the wrapping but these methods stayed around as a few odd uses still existed. We assumed that for the most part calling GetTypeInfo on an expression desires the flow state, and that seemed to generally be the case, but the extension methods were trying to do something different.

We need to investigate the remaining uses, figure out what the code is actually trying to do, and then either leave the method (explaining why it's actually the right thing) or just remove them.

**Comment by jasonmalinowski** [comment]
FYI @jcouv after seeing your PR I filed to track potentially cleaning up those extension methods you saw. At this point we think those are needed only for really rare things (where you're binding an expression and _don't_ want the flow state which is unusual), or it's just doing the wrong thing and we should delete them entirely.

**Comment by CyrusNajmabadi** [comment]
Clsoing out as speculative.

**Comment by jasonmalinowski** [comment]
Looks like we actually still have a use...I can't imagine why but would be quick to delete.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If you want to fix this, assign to yourself and to a milestone.  Having tracking issues sit in the ether for four years is not helping us manage this project.  It is very actively making it difficult as we have a deluge of speculative issues makign no progress impeding our ability to know which stuff we *should* be working on.

**Comment by jasonmalinowski** [comment]
Chatted with @CyrusNajmabadi on this one -- assigned to me, but keeping in backlog until I'm active on this project again.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  Please reactivate if you want to work on this and can assign to an actual milestone.  We don't want floating issues that go nowhere since no one ever checks the backlog.

Note: assinging to 18 is fine here.
