### ISSUE TITLE
Introduce explicit downcast refactoring if a variable requires a cast to compile

### ISSUE THREAD

**Issue by y87feng** [dotnet/roslyn#40967]
If a variable requires a cast to make it compile, add a refactoring that will introduce cast refactoring #33533
Error code: CS0266, CS1503

**Add explicit downcast**: 
context code:
```csharp
class C {}
class D : C {}
void doSomething(D d);
C returnC();
```

1.  types mismatch: `int` cannot be converted to `string`
```csharp 
string foo()
{
    return 1[||];
}
```
Results in `no refactoring`

2. assignment with constructor
```csharp
D d = [|new C()|];
```
Results in
```csharp
D d = (D)new C();
```

3. assignment with object creation expression - don't add cast except there is an explicit cast operator
```csharp
C c = new D();
D d = c[||];
```
Results in `no refactoring`

4. assignment with method return value
```csharp
D d = r[||]eturnC();
```
Results in
```csharp
D d = (D)returnC();
```

5. variable passed as method parameter
```csharp
doSomething([||]c);
```
Results in
```csharp
doSomething((D)c);
```
6. return variable with implicit cast
```csharp
D returnD()
{
         C c;
         return [||]c;
}
```
Results in
```csharp
D returnD()
{
         C c;
         return (D)c;
}
```

7. return the return value of another method
```csharp
D returnD_func() {
    return [||]returnC();
}
```
Results in
```csharp
D returnD_func() {
    return (D)returnC();
}
```

8. pass the return value of the method as parameter
```csharp
doSomething([||]returnC());
```
Results in
```csharp
doSomething((D)returnC());
```

9. the argument of base constructor
```csharp
class Test {
    public Test(D d) {}
}
class Derived_Test : Test  {
    public Derived_Test (C c) : base([||]c) {}
}

C c;
Derived_Test dt = new Derived_Test(c);
```
Results in
```csharp
class Test {
    public Test(D d) {}
}
class Derived_Test : Test  {
    public Derived_Test (C c) : base((D)c) {}
}

C c;
Derived_Test dt = new Derived_Test(c);
```

Consider cases:

10. have multiple choices
```csharp
class E : D {}
void doSomething(D d);
void doSomething(E e);

C c;
doSomething([||]c);
```

11. already have a cast
```csharp
class E : D {}
// void doSomething(D d);
void doSomething(E e);

C c;
doSomething([||](D)c);
```

12. generic type
```csharp
Func<C, C> func = d => d;
Func<D, D> func2 = [||]func1;
```

**Comment by mavasani** [comment]
Design meeting review:

- Add explicit cast code fix for compiler errors 
- Case 10: 
   - Can add cast to multiple potential derived types 
   - Offer multiple code fixes? 
   - Show the least specific type? 
   - What should be the limit? Should we bail out if we reach the limit? 
   Conclusion: smallest set of least specific types, with limit of 3, and exceeding the limit don't show any code fix, but log telemetry 
- Case 11: 
   - Don't remove existing cast but mark the outer cast for simplification 
- Case 12 
   - Is there a reasonable way to determine the correctness of cast and add it if possible? 
   - Should we worried about whether it will work at runtime or not? 
   - Use ClassifyCoversion API 
- Case 2 
   - Only offer if explicit conversion operator is defined by C, use ClassifyConversion API
