### ISSUE TITLE
SymbolFinder.FindReferencesAsync doesn't find any references for the indexed property C#

### ISSUE THREAD

**Issue by Droni** [dotnet/roslyn#40978]
**Version Used**: 
Version 16.5.0 Preview 1.0

**Steps to Reproduce**:

1. 
```C#
public class Test
{
  int this[int index] { get { return 0; } set { }  } // try to find references for this property declaration

  Test Create() { return new Test() { [0] = 0, [1] = 1 }; }
}
```

**Expected Behavior**:
SymbolFinder.FindReferencesAsync should be return 2 references and 1 declaration
The "Find All References" Visual Studio command should show all references

**Actual Behavior**:
SymbolFinder.FindReferencesAsync returns zero references
The "Find All References" Visual Studio command showing nothing

**Comment by CyrusNajmabadi** [comment]
Indexers are not supported by the find references system. This is due to their being no easy way to create a syntactic index that would limit the amount of work done to find them.

**Comment by Droni** [comment]
![image](https://user-images.githubusercontent.com/1456574/72416053-e415ca00-3786-11ea-8a84-eaa3af358489.png)
It looks strange. In this case the one reference was found. The problem only in the object initializer

**Comment by vatsalyaagrawal** [comment]
Related to #31819
