### ISSUE TITLE
ObsoleteAttribute is not ignored for type constraints on obsolete types

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/roslyn#4097]
I have two obsolete types, Class1 and Class2. Class1 uses Class2 in a generic type constraint. C#6 will generate a warning  "CS0612: 'Class2' is obsolete" for this scenario. In C#5, the obsolete attribute on the using type masked all usages of obsolete types/members.

This appears to be a regression/bug in C#6 RTM.

Repro-Sample: https://github.com/MichaelKetting/RoslynIssueReproduction/tree/Roslyn-4097-ObsoleteError-On-TypeConstraint

See https://github.com/MichaelKetting/RoslynIssueReproduction/blob/Roslyn-4097-ObsoleteError-On-TypeConstraint/Project1/Sample.cs for code.

**Comment by MichaelKetting** [comment]
I have two obsolete types, Class1 and Class2. Class1 uses Class2 in a generic type constraint. C#6 will generate a warning  "CS0612: 'Class2' is obsolete" for this scenario. In C#5, the obsolete attribute on the using type masked all usages of obsolete types/members.

This appears to be a regression/bug in C#6 RTM.

Repro-Sample: https://github.com/MichaelKetting/RoslynIssueReproduction/tree/Roslyn-4097-ObsoleteError-On-TypeConstraint

See https://github.com/MichaelKetting/RoslynIssueReproduction/blob/Roslyn-4097-ObsoleteError-On-TypeConstraint/Project1/Sample.cs for code.

**Comment by gafter** [comment]
It is a bug.

**Comment by AlekseyTs** [comment]
Sounds like the same issue as https://github.com/dotnet/roslyn/issues/5701

**Comment by AlekseyTs** [comment]
@gafter Please verify.
