### ISSUE TITLE
Simplifier could simplify ambigous reference but doesn't.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40973]
Note: this came out of a discussion i was having with @sharwell .  We don't offer to simplify here, but we could.

I personally am totally fine with this behavior.  However, we're putting it up for completeness as there may be some merit in exploring simplification even in ambiguous situations:

![image](https://user-images.githubusercontent.com/4564579/72395977-0c9eb500-36f0-11ea-828a-abbf1001d8bc.png)

**Comment by sharwell** [comment]
Another case where symbols have ambiguous resolution in the above code is:

```
// For static or instance methods
_ = nameof(Example.Goo);

// For instance methods
_ = nameof(this.Goo);
```

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
