### ISSUE TITLE
Analyzer crashes are often put into whatever tool window has focus

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#40993]
Roslyn's logic for showing analyzer errors often puts them into whatever Window has focus, including Find All References, Solution Explorer, and few others.

![image](https://user-images.githubusercontent.com/1103906/72479157-bc3a6b00-3847-11ea-9fdb-d90c05263446.png)

Given analyzers can crash in the background without any user interaction, it would be better for Roslyn to just pick either a document window or use the global one.

**Comment by davkean** [comment]
This is the problem: https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/src/VisualStudio/Core/Def/Implementation/InfoBar/VisualStudioInfoBarService.cs#L75. It's asking for WindowFrame, it should ask for DocumentFrame (be aware that there might not be any document open), or grab the global infobarhost.

**Comment by jmarolf** [comment]
The service that shows the dialog should just be updated to use the new inforbar apis. Those didn't exist when I first wrote this and so I (incorrectly) attach an infobar to the active document.

**Comment by davkean** [comment]
It's being attached to the active window, not active document. That should be the miminum change.

**Comment by davidwengier** [comment]
The comment above that line clearly indicates that tool windows are a desired target (eg, interactive window) so I don't think thats the right change. I think perhaps we should now be calling the `ActiveView` method when a fixer or refactoring fails, here:
https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/EditorLayerExtensionManager.cs#L75

**Comment by davkean** [comment]
How will that prevent these messsages from ending up in random tool windows?

**Comment by davidwengier** [comment]
Oops, typo, "now" should have been "not". There is a `ShowInfoBarInGlobalView` which seems like it would be a better fit.
