### ISSUE TITLE
Renaming C# symbols reports errors

### ISSUE THREAD

**Issue by craxal** [dotnet/roslyn#41]
After running Visual Studio 2015 for a while, renaming stops working, reporting an error: "Object reference not set to an instance of object."  Repro is difficult, because when first launching VS, rename works just fine.  Dumps aren't retrievable, because VS doesn't crash when this issue happens.

**Things to try**
1. Create an ASP.NET MVC project with a Cloud Service project.
2. Build and run the project at least once. Terminate project execution.
3. Press F2 over an existing symbol defined in the project.
4. Add one or two new classes (controllers or views may work, too).
5. Press F2 over the new class name.

**Expected**
* The rename box appears, the symbol name is highlighted, and the user can rename the symbol.

**Actual**
* Error dialog appears with the message: "Object reference not set to an instance of object."

**Comment by Pilchie** [comment]
We've see a report of this issue before (http://connect.microsoft.com/VisualStudio/feedback/details/1050027/connect-visual-studio-2015-variable-rename-throws-nullreferenceexception), but we haven't been able to reproduce it.  Any chance you could attach a debugger to VS the next time this starts to happen and capture a memory dump at the time of the NullReferenceException?

**Comment by Pilchie** [comment]
Actually, that report is on VS2013, so it's probably not related.

**Comment by dpoeschl** [comment]
I also tried to reproduce this for a while but was unsuccessful. How often does this happen to you?

When the failure occurs, what's the state of the left-most navigation bar?  
![image](https://cloud.githubusercontent.com/assets/235241/5966820/71321a34-a7bc-11e4-9e6b-e3660fac8e39.png)


I'd also like to reiterate Kevin's request for a memory dump at the time of the NullReferenceException.

**Comment by dpoeschl** [comment]
Hi @craxal, have you seen problem occur again?

**Comment by dpoeschl** [comment]
Closing this for now. If you see it again or can provide more context, please re-open. Thanks!
