### ISSUE TITLE
"use var" and the change to var nullable inference needs design

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#41008]
In #40755 the compiler is changing the behavior of var, where it always infers a nullable type so further assignments can be made to it. How this interacts with "use var" is unclear. There are at least two classes of people:

1. People who just want to use var and let the compiler figure things out, they don't care what the nullability of local variables.
2. People who want to use var, but also want to be able to state that certain local variables are non-null to get warnings immediately if somebody assigns a potentially null value to it, rather than seeing warnings later.

These are somewhat at odds of each other. If a developer has "string s = SomethingThatReturnsANonNullableString()", the developer in the first category would happily change that to var. A developer in the second category however might have intentionally wrote "string" because they _didn't_ want this new var behavior and we're stomping over that. Right now the answer from the LDM is "if you want to be explicit about non-null, be explicit about the type", and if that's the answer the IDE needs a way to respect that.

My initial gut was the IDE just shouldn't suggest to use "var" if the stated type is non-nullable, but that's problematic if you are a person in category 1.

**Comment by sharwell** [comment]
Design review conclusion: The following should ship in the same preview release as the compiler change to the semantics of `var`.

1. The **Use Explicit Type** refactoring should replace `var` with the non-nullable reference type if no nullable assignment is made to the variable.
2. The **Use Implicit Type** refactoring should still offer to use `var` if doing so will widen the declared type of the local to the nullable reference type.
3. The Quick Info for `var` should be modified to include an additional line highlighting the initial nullability:
    * The initial value is not null
    * The initial value may be null

**Comment by jasonmalinowski** [comment]
Closing this work item since we've had the discussion; I've inline-edited @sharwell's post with tracking bugs to track the fixing of those issues.
