### ISSUE TITLE
params to Dictionary<string,T> 

### ISSUE THREAD

**Issue by cordasfilip** [dotnet/roslyn#4100]
Here is something that I thought that should be in C# 

 if we want a collection of named params in a function 

```
public string Func1(params Dictionary<string,object> keyValuePairs)
{
        //SOME WORK...
}

//Call

Func1(Key1:"VALUE1",Key2:"VALUE2"...);

I see a lot of use case for something like this.

#For example 
String.Format("{a}  is not {b}",a:"C#",b:"Java");
```

just an idea to think about.

**Comment by aluanhaddad** [comment]
If I understand your proposal correctly, this to allow a function to be declared such that it's arguments would require theirs names to be explicitely specified. Is that the intent here?

**Comment by cordasfilip** [comment]
Yes. So you get a name value pair rather then just the object in params. or rather then just to be an Dictionary<string,T> it can be Dictionary<object,T> where if no name is specified the key would be the index. 
#For example 

public void Func1(string format,params Dictionary<object,string> keyValuePairs)
 {
        var result = format;
         foreach(var item in keyValuePairs)
         {
                result =  result.Replace("{"+item.Key+"}",item.Value)
         }
       return result;
}

So when the function is called 
Func("{0} is not {b}","java",b:"c#") => returns "java is not c#"
and the dictonery would map to 
         keyValuePairs = new Dictonery<object,string>
                 {
                        {0,"java"},
                        {"b","c#"}
                 }
if 
Func("{a} is not {b}",a:"java",b:"c#") => returns "java is not c#"
and the dictonery would map to 
         keyValuePairs = new Dictonery<object,string>
                 {
                        {"a","java"},
                        {"b","c#"}
                 }

if 
Func("{0} is not {1}","java","c#") => returns "java is not c#"
and the dictonery would map to 
         keyValuePairs = new Dictonery<object,string>
                 {
                        {0,"java"},
                        {1,"c#"}
                 }
if 
Func(format:"{a} is not {b}",a:"java",b:"c#") should get an error 

As i said just something that i needed a few times. I'm not sure that this might be the best way to do this so if any one thinks there might be a nicer way of doing this write what you think.

**Comment by deaddog** [comment]
I appreciate what this could bring. I have been in a similar situation multiple times, where I have been looking to have a method that accepts a variable amount of argument-pairs. However I disagree with you approach.

**Firstly**; what you are doing is having identifiers implicitly converted to strings, which heavily hinder what you can do in terms of keys. As far as I can tell from you examples only strings and integers are allowed and both are implicit. What about a `char->string` mapping? Or maybe a `Type->string` mapping?

**Secondly**; your syntax would not allow me to do a variable number of dictionaries as this syntax expects a different result. Naturally the parser could identify what type of input you are providing but then you would have difficulties implementing the actual method:
```csharp
Func1("{a} is not {b}", a: "java", b: "c#");
Func1("a string format", dict1, dict2, dict3);

public void Func1(string format,params Dictionary<object,string> keyValuePairs)
{
    // Is keyValuePairs a single dictionary or multiple?
}
```
I realise that you are not specifying your dictionary as an array - and thus probably don't condier the above an issue. But this will create a special case where one single type is allowed in declaration as a non-array. To avoid that, you could instead use this definition:
```csharp
public void Func1(string format,params KeyValuePairs<object,string>[] keyValuePairs)
{
    // keyValuePairs is now multiple elements consistently.
}
```
This is also not consistently converting a range of kvps to a dictionary without needing it (your example would suffice with an array or even enumerable).

**Thirdly**; even with the above change, this is not allowing for arguments with three elements each. I know that this is even less used, but supporting any size of arguments would clearly be a more flexible solution. Currently I do this (and two-element arguments) using tuples as they are the exact way of representing what you are looking for. Though I clearly agree that the following is not very nice to read nor write:
```csharp
Func1("{a} is not {b}", Tuple.Create("a", "java"), Tuple.Create("b", "c#"));

public void Func1(string format,params Tuple<object,string> keyValuePairs)
{
    var result = format;
    foreach(var item in keyValuePairs)
    {
        result =  result.Replace("{" + item.Item1 + "}", item.Item2)
    }
    return result;
}
```
However there is an issue describing a simpler syntax for tuple declaration and instantiation (https://github.com/dotnet/roslyn/issues/347) and as of right now it might make it into C#7 (https://github.com/dotnet/roslyn/issues/2136). I personally think this is a much better solution.

**Comment by cordasfilip** [comment]
First i changed the output type from void to string that was a mistake. 
I will try to answer the points you made.

 Firstly:
I don't see the need for any other type then string, in fact the hole integer thing can be scraped and let the key be a string and have an error if you don't call with a named parameter(the integer thing is just a solution for the case when there is no name for the parameter). 

Secondly:
 I might not have given all examples for different type the params should be ```Dictonery<string,T>``` no ```Dictonery<string,string>```

This should work as params do today.

For example 
```
Lets say there is a class

 class Test 
        {
            public static string Func1StringParams(string format, params string[] input)
            {
                return "params are string";
            }

            public static string Func1DictoneryParams(string format, params Dictionary<string, Dictionary<string, string>> input)
            {
                return "params are Dictonery";
            }

            public static string Func1ObjectParams(string format, params Dictionary<string, object> input)
            {
                return "params are Object";
            }     
        }

And that we have a main method
static void Main(string[] args)
        {
            string str1 = "C#";
            string str2 = "Java";

            Dictionary<string,string> dict1 = new Dictionary<string,string>{};
            Dictionary<string,string> dict2 = new Dictionary<string,string>{};

            object obj1 = new object();
            object obj2 = new object();

            Test.Func1StringParams("{a} is not {b}", a: str1, b: str2); //returns "params are string";
            Test.Func1StringParams("{a} is not {b}", a: dict1, b: dict2); //returns will not compile since the parametar is not a valid type;
            Test.Func1StringParams("{a} is not {b}", a: obj1, b: obj2);//returns will not compile since the parametar is not a valid type;
            Test.Func1StringParams("{a} is not {b}", a: obj2, b: str2); //returnswill not compile since the parametar is not a valid type;
            Test.Func1StringParams("{a} is not {b}", a: dict1, b: str1); //returns will not compile since the parametar is not a valid type;
            Test.Func1StringParams("{a} is not {b}", str1); //returns will not compile since the parametar is not a valid type;
            Test.Func1StringParams("{a} is not {b}", dict1); //returns "params are string";
            Test.Func1StringParams("{a} is not {b}", obj1); //returns will not compile since the parametar is not a valid type;

            Test.Func1DictoneryParams("{a} is not {b}", a: str1, b: str2); //returns  will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", a: dict1, b: dict2); //returns "params are Dictonery";
            Test.Func1DictoneryParams("{a} is not {b}", a: obj1, b: obj2);//returns will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", a: obj2, b: str2); //returns will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", a: dict1, b: str1); //returns will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", str1); //returns will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", dict1); //returns will not compile since the parametar is not a valid type;
            Test.Func1DictoneryParams("{a} is not {b}", obj1); //returns will not compile since the parametar is not a valid type;

            Test.Func1ObjectParams("{a} is not {b}", a: str1, b: str2); //returns "params are Object";
            Test.Func1ObjectParams("{a} is not {b}", a: dict1, b: dict2); //returns "params are Object";
            Test.Func1ObjectParams("{a} is not {b}", a: obj1, b: obj2);//returns "params are Object";
            Test.Func1ObjectParams("{a} is not {b}", a: obj2, b: str2); //returns "params are Object";
            Test.Func1ObjectParams("{a} is not {b}", a: dict1, b: str1); //returns "params are Object";
            Test.Func1ObjectParams("{a} is not {b}", str1); //returns will not compile since the parametar is not a valid type;
            Test.Func1ObjectParams("{a} is not {b}", dict1); //returns will not compile since the parametar is not a valid type;
            Test.Func1ObjectParams("{a} is not {b}", obj1); //returns will not compile since the parametar is not a valid type;
        }
```
Thirdly
I don't like the tuple because it isn't used that much.
I will give a real world example where this might help.

I went and looked at the source code for MVC frame work. 
today there is a helper method called Html.Label and there are two overloads for the method(I know there are more but I the two are to make a point)
```
@Html.Label("Label Name", new { @class="label-style" })
@Html.Label("Label Name", new Dictionary<string,object>{ {"class" , "label-style"} })
```
Source is hear http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/Html/LabelExtensions.cs
The implementation is

```
 public static MvcHtmlString Label(this HtmlHelper html, string expression, string labelText)
        {
            return Label(html, expression, labelText, htmlAttributes: null, metadataProvider: null);
        }

        public static MvcHtmlString Label(this HtmlHelper html, string expression, object htmlAttributes)
        {
            return Label(html, expression, labelText: null, htmlAttributes: htmlAttributes, metadataProvider: null);
        }

 internal static MvcHtmlString Label(this HtmlHelper html, string expression, string labelText, object htmlAttributes, ModelMetadataProvider metadataProvider)
        {
            return Label(html,
                         expression,
                         labelText,
                         HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes),
                         metadataProvider);
        }

        internal static MvcHtmlString Label(this HtmlHelper html, string expression, string labelText, IDictionary<string, object> htmlAttributes, ModelMetadataProvider metadataProvider)
        {
            return LabelHelper(html,
                               ModelMetadata.FromStringExpression(expression, html.ViewData, metadataProvider),
                               expression,
                               labelText,
                               htmlAttributes);
        }
as you can see one method calls the other just so we can get to use the call for Anonymous type.
@Html.Label("Label Name", new { @class="label-style" }) 
and the method for conversion uses reflection to get the values

public static RouteValueDictionary AnonymousObjectToHtmlAttributes(object htmlAttributes)
        {
            RouteValueDictionary result = new RouteValueDictionary();

            if (htmlAttributes != null)
            {
                foreach (PropertyHelper property in HtmlAttributePropertyHelper.GetProperties(htmlAttributes))
                {
                    result.Add(property.Name, property.GetValue(htmlAttributes));
                }
            }

            return result
}

That is a lot of code just for some cool locking code.
I think this is used often. Now if the Dictonery prams were added the hole thing could be simplified.

 public static MvcHtmlString Label(this HtmlHelper html, string expression,params Dictionary<string,object> htmlAttributes)
        {
the method can be called like so
@Html.Label("Label Name", @class:"label-style" ) 
```
There are also places where I can see a use for this like
Database.Query("INSERT INTO Table1 Value(@param1)",@param1:DateTime.Now);
httpClient.Get("http://www.someservice.com",q1:1,q2:2) //returns the data from address "http://www.someservice.com?q=1&q2"

The Tuple's not used all that much, and I didn't find how this(#347) new feature would create something similar.

**Comment by GeirGrusom** [comment]
Although not supported by the CLR, what about this:

    void Foo(IDictionary<string, object> dict = new Dictionary<string, object>());

    void DoFoo()
    {
        // The function definition implies that unless explicitly stated a new Dictionary<string, object>()
        // is supplied. The following code then applies initializers to that object.
        Foo({ ["Foo"] = 123, ["Bar"] = "Baz"});
    }

**Comment by cordasfilip** [comment]
This part I like A LOT IDictionary<string, object> dict = new Dictionary<string, object>());

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
