### ISSUE TITLE
Quick Fix suggests wrong code if 'Convert to conditional expression' is applied on conditional expressions (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41001]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/882816/quick-fix-suggests-wrong-code-if-convert-to-condit.html)._

---
'Quick fix' suggests/produces wrong code if 'Convert to conditional expression' is applied on conditional expressions: '()' is missing:

class Program
    {
        static void Main()
        {
            var data1 = new Data()
            {
                InnerData2 = new InnerData()
                {
                    InnerMember = "inner member",
                },
            };
            var data2 = new Data()
            {
                InnerData2 = new InnerData()
                {
                    InnerMember = "inner member",
                },
            };

// data1. InnerData1 and data1. InnerData1 is null -> ValueEquals() should return 'true'
            Console.WriteLine($"Result is '{data1. ValueEquals(data2)}' but should be '{data1. ValueEqualsOrg(data2)}'");
            // console shows: Result is 'False' but should be 'True'
        }
    }

class Data
    {
        public InnerData InnerData1;
        public InnerData InnerData2;

// two instances are equal if 
        // - InnerData1 of instance and other are both null or InnerData1.InnerMember of instance and other are equal 
        // - InnerData2 of instance and other are both null or InnerData2.InnerMember of instance and other are equal 
        public bool ValueEquals(Data other) // refactored from ValueEqualsOrg()
        {
            return other == null
                ? false
                : InnerData1 == null ? other. InnerData1 != null : ! InnerData1.ValueEquals(other. InnerData1) // <- missing '()' !!
                ? false
                : ! (InnerData2 == null ? other. InnerData2 != null : ! InnerData2.ValueEquals(other. InnerData2));

// should be:
            // return other == null
            //     ? false
            //     : (InnerData1 == null ? other. InnerData1 != null : ! InnerData1.ValueEquals(other. InnerData1)) // <- '()' added
            //     ? false
            //     : ! (InnerData2 == null ? other. InnerData2 != null : ! InnerData2.ValueEquals(other. InnerData2));
        }

public bool ValueEqualsOrg(Data other) // this method has been refactored with 'Convert to conditional expression'
        {
            if ( other == null )
            {
                return false;
            }
            if ( InnerData1 == null ? other. InnerData1 != null : ! InnerData1.ValueEquals(other. InnerData1) )
            {
                return false;
            }
            if ( InnerData2 == null ? other. InnerData2 != null : ! InnerData2.ValueEquals(other. InnerData2) )
            {
                return false;
            }
            return true;
        }
    }

class InnerData
    {
        public string InnerMember;
        public bool ValueEquals(InnerData other)
        {
            if ( other == null )
                return false;
            if ( InnerMember != other. InnerMember )
                return false;
            return true;
        }
    }

Regards

---
#### Visual Studio Feedback System on 1/14/2020, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  The only place where "convert to conditional" is offered is on:

```
if ( InnerMember != other. InnerMember )
    return false;

return true;
```

Where we convert htat to `return InnerMember == other.InnerMember;`.  This change is correct and preserves sematnics.  When i run teh above code before after the fix i get teh exact same results.
