### ISSUE TITLE
csc on coreclr shouldn't include default response file

### ISSUE THREAD

**Issue by kazzmir** [dotnet/roslyn#4101]
Using f56e3c29e8676ac652f600e6a8108e9c333a3b09 I successfully built roslyn, and have Binaries/Debug/csc.exe but running it produces this error.

    $ /tmp/mono.linux.1/bin/mono ~/tmp/dotnet/roslyn/Binaries/Debug/csc.exe x.cs
    Microsoft (R) Visual C# Compiler version 0.0.0.0
    Copyright (C) Microsoft Corporation. All rights reserved.

    error CS0006: Metadata file 'System.Deployment.dll' could not be found
    error CS0006: Metadata file 'System.Web.Mobile.dll' could not be found
    error CS0006: Metadata file 'System.Web.RegularExpressions.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.Activities.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.ComponentModel.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.Runtime.dll' could not be found

I don't see a file resembling 'System.Deployment' in either the mono directory or the roslyn directory. I am on Ubuntu 14.04.

I admit I am rather new to roslyn, and C# in general, so this may be user error.

**Comment by davkean** [comment]
This looks like the default response file has invalid references, looks like a compiler bug, perhaps you need to a portable response file?

**Comment by kazzmir** [comment]
I rebuilt roslyn with d922169787707ad064e3414fd3120e3be2c4ca75. I get the same output from running csc.exe as before.

    $ Binaries/Debug/csc.exe x.cs
    Microsoft (R) Visual C# Compiler version 42.42.42.42
    Copyright (C) Microsoft Corporation. All rights reserved.

    error CS0006: Metadata file 'System.Deployment.dll' could not be found
    error CS0006: Metadata file 'System.Web.Mobile.dll' could not be found
    error CS0006: Metadata file 'System.Web.RegularExpressions.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.Activities.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.ComponentModel.dll' could not be found
    error CS0006: Metadata file 'System.Workflow.Runtime.dll' could not be found

How do I get a portable response file? Where would I put it?

**Comment by davkean** [comment]
Try pass ```csc /noconfig```

**Comment by kazzmir** [comment]
It works with /noconfig

**Comment by gafter** [comment]
We probably need a different default response file on linux.

**Comment by davkean** [comment]
I would consider a portable different response file for everywhere except desktop/.NET Framework.

**Comment by davkean** [comment]
Although what does a response file even mean in the package world?

**Comment by gafter** [comment]
@davkean It affects what happens when you type `csc.exe`.

**Comment by davkean** [comment]
Understood, but in the old days, csc lived next to mscorlib, system, etc. Therefore, including mscorlib, System, etc in the response file worked.

In the cross-plat world, this isn't the case, csc.exe cannot possible know how to include and build against System.Runtime.dll (the new mscorlib) without understanding how to find NuGet packages and know which thing inside is the thing it needs to build against.

**Comment by VSadov** [comment]
We need to think about the default response file. 
System.Web.Mobile.dll really?

Does not look like 1.1 though.
