### ISSUE TITLE
Simplifying object instantiating where expected type is known

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41014]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/885113/simplifying-object-instantiating-where-expected-ty.html)._

---
You have already made some greate enhancment in code to make it more productive, clean, compact, shorter. Following sugestion in same direction.

if we have a class:

```csharp
class Abc 
{
  public int A, B, C;
  public Abc(int a) { A = a; }
  public Abc() { }
}
```

then

```csharp
Abc abc1 = new Abc(1);
Abc abc2 = new Abc(1) { B = 2, C = 3 };
Abc abc3 = new Abc() { A = 1, C = 10 };
```

colud be simplified to:

```csharp
Abc abc1 = (1);
Abc abc2 = (1) { B = 2, C = 3 };
Abc abc3 = { A = 1, C = 10 };
```

as well as in array creation:

```csharp
Abc[] abcList = { (1),  (1) { B = 2, C = 3 }, { A = 1, C = 10 } };
List<Abc> abcList = { (1),  (1) { B = 2, C = 3 }, { A = 1, C = 10 } };
```

or in function call:

```csharp
void Method(Abc a, List<Abc> b, string[] c);

Method({ C = 9}, { (1),  (1) { B = 2, C = 3 }, { A = 1, C = 10 } }, { "orange", "aple" });
```

or in any other place where expected type is known in advance.

---
#### Visual Studio Feedback System on 1/15/2020, 11:49 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
`Abc abc1 = (1);` this is already legal code.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Lang design takes place on dotnet/csharplang.  Thanks!
