### ISSUE TITLE
In ASP.NET Razor, Visual Studio throws a NotReferencedException when renaming a class or dictionary referenced in CSHTML file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41020]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/886286/in-aspnet-razor-visual-studio-throws-a-notreferenc.html)._

---
In the default namespace within the .cs file:
```
    public static class Config
    {
        public static decimal Price = 1;
    }   
```

Inside a regular .cshtml razor pages file in the same namespace and all:
```
<p>@(Config.Price) Text</p>
```

Visual studio throws a **NotSupportedException** when renaming either `Config` or `Price` from inside the .cs file (the rename option is shown in the context menu) 
And Visual Studio shows a **"You cannot rename this element"** when renaming the same Variable / Class inside the cshtml file.

Commenting out ALL the occurrences of `Config.Price` in cshtml html files allows me to rename `. Price` properly from the .cs file.

---
#### Visual Studio Feedback System on 1/15/2020, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as razor is external to this project.
