### ISSUE TITLE
Add EditorConfig naming convention support for labels

### ISSUE THREAD

**Issue by castholm** [dotnet/roslyn#41039]
Currently, it is not possible to define EditorConfig naming conventions for labels. I propose that `label` is added as an applicable symbol kind supported for both C# and VB.

Since labels are regular named identifiers like most (all?) other applicable symbol kinds they should probably offer similar warnings and code fixes, but one relevant consideration is whether an integer literal label in VB (e.g. `100:`) should be handled as any other alphanumeric label or if it should be silently ignored.

**Comment by mavasani** [comment]
Design meeting review: We would accept a PR to implement this support.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
