### ISSUE TITLE
Static Extension Methods are not returned by the completion service

### ISSUE THREAD

**Issue by npolyak** [dotnet/roslyn#41038]
**Version Used**: 
3.4.0

**Steps to Reproduce**:
I am testing the CompletionService. It should allow me to see the Linq extension methods on an array, but I do not see them. Here is the code:

        static void Main(string[] args)
        {
            string code = @"using System;
            using System.Linq;

           namespace RoslynCompletionTests
           {
                 public static class MyTestClass1
                 {
                       public static void Print()
                       {
                              int[] array = {1,2,3,4,5,6};

                              var result = array.Select(i => new { I = i }).Select(v => v.I);
                       }
                 }
           }";
            var host = MefHostServices.Create(MefHostServices.DefaultAssemblies);
            
            Type[] types =
            {
                typeof(object),
                typeof(Enumerable),
                typeof(IEnumerable),
                typeof(Console),
                typeof(Assembly),
                typeof(List<>),
                typeof(Type)
            };

            ImmutableArray<string> imports = types.Select(x => x.Namespace).Distinct().ToImmutableArray();

            ImmutableArray<MetadataReference> references =
                types.Select(t => MetadataReference.CreateFromFile(t.Assembly.Location) as MetadataReference)
                     .ToImmutableArray();

            AdhocWorkspace workspace = new AdhocWorkspace(host, "Custom");

            string name = "MyTestProj";

            ProjectId id = ProjectId.CreateNewId(name);

            ParseOptions parseOptions = new CSharpParseOptions();

            CompilationOptions compilationOptions =
                new CSharpCompilationOptions
                (
                    OutputKind.DynamicallyLinkedLibrary,
                    usings: imports,
                    allowUnsafe: true);

            ProjectInfo projInfo =
                ProjectInfo.Create
                (
                    id,
                    VersionStamp.Create(),
                    name,
                    name,
                    LanguageNames.CSharp,
                    parseOptions: parseOptions,
                    compilationOptions: compilationOptions,
                    metadataReferences: references);

            Project proj = workspace.AddProject(projInfo);

            SourceText text = SourceText.From(code);

            Document doc = proj.AddDocument("MyDoc.cs", text);

            SemanticModel semanticModel = doc.GetSemanticModelAsync().Result;

            CompletionService completionService = CompletionService.GetService(doc);

            string strToFind = "array.";
            int idx = text.ToString().IndexOf(strToFind) + strToFind.Length;

            var results = completionService.GetCompletionsAsync(doc, idx).Result;
        }

The results contain only 24 items and no Linq extension methods whatsoever. 
**Expected Behavior**:
Need to see the extension methods, e.g. Where<>(...), Select<...>(...) etc.

**Actual Behavior**:
it returns no extension methods - only public methods and properties defined on the class.

**Comment by npolyak** [comment]
It is quite possible that I am doing something wrong, e.g. not using some kind of options etc. Please help!

**Comment by CyrusNajmabadi** [comment]
does your compilation or workspace report any diagnostics?

**Comment by npolyak** [comment]
I compiled and Emited the project - compiled fine, no diagnostics at all.

**Comment by npolyak** [comment]
Thanks, Cyrus, seems like everything started to work after I added these two magic lines:

.Concat(new[]
            {
                Assembly.Load("System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),
                typeof(Microsoft.CSharp.RuntimeBinder.Binder).Assembly,
            }

to assemblies that form MetadataReferences. I had those lines long ago, and I was hoping I do not need to use them anymore.

**Comment by npolyak** [comment]
everything works after I added missing assembly references.
