### ISSUE TITLE
Syntax.xml.Generated.vb is not included in Roslyn Source

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4104]
I think my application is crashing in GetBinaryExpressionOperatorTokenKind in Syntax.xml.Generated.vb but I have no way to be sure. How do I set Visual Studio to step through Roslyn Source like I can with .Net? Also the error message Throw New ArgumentException("OperatorToken") is not really useful and I can't find Syntax.xml.Generated.vb in Roslyn Source on GitHub.

I am passing in IsKeyword but it seems to want IsExpression and returns IsKeyword,

If I pass in IsExpression to the line below it faults with ex.message = "Specified argument was out of the range of valid values." & vbCrLf & "Parameter name: kind"

Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.IsExpression).WithTriviaFrom(OldCondition.OperatorToken)

The next line works to produce the token but I crash in the second statement which is looking for IsExpression not IsKeyword.
Dim operatorToken As SyntaxToken = SyntaxFactory.Token(SyntaxKind.IsKeyword).WithTriviaFrom(OldCondition.OperatorToken)
 Dim newRoot As SyntaxNode = root.ReplaceNode(invocation, SyntaxFactory.TernaryConditionalExpression(SyntaxFactory.Token(SyntaxKind.IfKeyword), SyntaxFactory.Token(SyntaxKind.OpenParenToken), NewCondition, SyntaxFactory.Token(SyntaxKind.CommaToken), invocation.WhenFalse, SyntaxFactory.Token(SyntaxKind.CommaToken), invocation.WhenTrue, SyntaxFactory.Token(SyntaxKind.CloseParenToken)).WithLeadingTrivia(invocation.GetLeadingTrivia()).WithTrailingTrivia())

**Comment by Suchiman** [comment]
> I can't find Syntax.xml.Generated.vb in Roslyn Source on GitHub.

That's because this file is obviously generated.
I think you should be able to get this exact file by cloning the `releases/VS2015` branch and building it once. The file is being generated while building from the `Syntax.xml` file.

**Comment by paul1956** [comment]
Is Release the same as Master on Github because that one gets 5,000 errors when I load Roslyn.sln with the released version of Visual Studio. If not where do I get it?

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by Pilchie** [comment]
Per the [wiki page about building](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging) (which needs to be updated to say RTM, and not RC), you probably need to restore nuget packages before opening the solution.

Also, you can see the file in http://source.roslyn.io, though it's huge and pretty slow to render.

**Comment by paul1956** [comment]
Did restore the nuget packages before loading and tried to follow wiki page about building but RC is different than production. Did find it on  http://source.roslyn.io (can't get the file to render at all on IE under Windows 8.1) which is why I was hoping to open it on my machine locally) that is how I could find out where my issue was but I was hoping to be able to debug the crash using the Source. I don't see any way to tell Visual Studio to find the source on my machine or http://source.roslyn.io or Github when it encounters an Exception. So far my experience with Exception error message is not very good. They know exactly what the issue is and only report the operand name in the exception message.

**Comment by SamB** [comment]
Opening the solution in VS doesn't really do all that much to get you  closer to generating a copy of Syntax.xml.Generated; it's much simpler to build from the commandline, as shown on the wikipage.

It does seem like it would be a good idea to arrange that such critical generated files could be hosted somewhere appropriate for the PDBs for packaged releases to refer to, though.  Perhaps in a dummy branch/repository, like those pre-built documentation branches that git.git has (had?).

**Comment by davkean** [comment]
We don't yet publish symbols/source which let step into the code, we'll factor in the generated code when we do this - this is being tracked by https://github.com/dotnet/roslyn/issues/3.
