### ISSUE TITLE
Extract Method not correctly inferring a local can be made non-null

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#41058]
**Version Used:** 3.5.0-beta3-20063-01+1f921815c4544e703bf721cb8e6c86d5cf6bda63

1. Paste the following code into a C# 8.0 file:

```
    public void M()
    {
        string? a = null;

        if (a != null)
        {
            a.ToString();
        }
    }
```

2. Select the "a.ToString()" and extract method

**Expected:** the parameter in the method created is of type 'string', since a was known to be not-null at the point of use.
**Actual:** the parameter in the method created is still of type string?, which means this introduces a nullable warning that shouldn't be there.

**Comment by jasonmalinowski** [comment]
@ryzngard: I'm surprised by this one -- we had a bunch of tests for all sorts of cases, but for some reason this isn't working...?

**Comment by ryzngard** [comment]
:( 

It looks at least similar to this test case http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests/CodeActions/ExtractMethod/ExtractMethodTests.cs,2434 

I would have expected this to work

**Comment by ryzngard** [comment]
@jasonmalinowski  I tested in 16.5 Preview 4 and wasn't able to reproduce this. Maybe there was another bug that was surfaced through this and was fixed?

**Comment by jasonmalinowski** [comment]
@ryzngard do we need any further tests?

**Comment by ryzngard** [comment]
This should be covered by http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests/CodeActions/ExtractMethod/ExtractMethodTests.cs,2434
