### ISSUE TITLE
Remove OrganizingService and dependent files

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#4109]
After a discussion with @rchande over the failure of `src\EditorFeatures\CSharpTest\Organizing\OrganizeTypeDeclarationTests` it was determined that `src\Features\Core\Organzing\OrganizingService.cs` and it's dependent files are not used and can be deleted.

**Comment by tannergooding** [comment]
FYI. @rchande, @amcasey, @jasonmalinowski, @dpoeschl, @Pilchie, @DustinCampbell

**Comment by tannergooding** [comment]
I have submitted PR #4111 as a temporary workaround for the issue until we can determine whether or not removing the code is the proper course of action.

**Comment by DustinCampbell** [comment]
I'm not sure removing it is the right course of action. I think we need to take a closer look.

**Comment by tannergooding** [comment]
I do agree that removing the files is the probably not the correct course (unless we determine that they have no future use).

The correct course is likely to fix up all of our tests to be independent of line endings (see PR #4111 for an example). I believe this work will need to be done anyways to get all of our unit tests successfully running on Linux/Mac which already have different default line terminators (then what is expected on Windows).

**Comment by amcasey** [comment]
Do we know if there are other features that exist only to be tested (i.e. cannot be triggered from the product)?

**Comment by jasonmalinowski** [comment]
I think if we did, we would have already deleted them by now.

**Comment by DustinCampbell** [comment]
FWIW, there are two reasons I'm concerned about removing the files:

1. It's unclear to me that these tests aren't providing coverage that we wouldn't get elsewhere.
2. We really might want to add the feature. :smile:

**Comment by jasonmalinowski** [comment]
For your first concern, isn't there some tool where we can get code coverage with/without and then see what the delta is? It seems it'd be best to directly add coverage for that instead of relying on indirect coverage.

**Comment by jasonmalinowski** [comment]
@Pilchie, @DustinCampbell, any different opinions on this? I'm OK deleting the code. If we want to add the feature, we have source control.

**Comment by DustinCampbell** [comment]
My opinions remain the same, so @Pilchie would need to weigh in. I don't think the first question has been addressed since such a tool would need to be actually run before we know anything.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't done anything about this in 8 years and it hasn't been a problem.
