### ISSUE TITLE
Incorrect overloaded function picked - Overloaded function + Generics

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#41106]
In a library, I have these two function signatures:

```
public ulong Update<T>(IEnumerable<T> objects)
```

and 

```
public ulong Update<T>(T item)
```

When the calling code tries to do this:

```
IList<string> list = new List<string>();
// add stuff to "list"

// call the update() func
Update(list);
```

I expect the first signature (the one where parameter type is `IEnumerable<T>`) to be selected and used. However, I find that the second signature (the one with the `T item` parameter) is the one that is selected and used.

PS: "selected & used" -- it is the one that `F12` in Visual Studio goes to, and the one that is used at run-time.

If I specifically change the call to:

```
Update(list.AsEnumerable());
```

The first signature overload is used. But this is not what I want to do (or expect the callers of that function-set to be doing).

This is confusing, since `IList<T>` implements `IEnumerable<T>` and so one would expect that the `(IEnumerable<T> objects)` signature be the one that is used.

What am I doing wrong? Or is this a bug?

**Comment by CyrusNajmabadi** [comment]
> What am I doing wrong?

The `public ulong Update<T>(T item)` overload is viewed to be better than the `public ulong Update<T>(IEnumerable<T> objects)` overload.  Here's the simple intuition why:

When the compiler tries to resolve `Update(list)` it has to choose between the two overloads.  First, for both, it does generic type inference, this produces:

```c#
Update<int>(IEnumerable<int> objects); // and
Update<IList<int>>(IList<int> item);
```

Then, it sees which of these is 'better'.  The latter is better as it's an exact match of the type of the `list` argument passed in.  i.e. `list`'s type is `IList<int>` and the second method exactly takes this.

The language and compiler are working as spec'ed.

**Comment by sujayvsarma** [comment]
Wow. Okay. That makes perfect sense. Thank you @CyrusNajmabadi 

Follow up question -- How should I change the `IEnumerable` one then to cause that one to get picked? Because that function has been written for an enumerable (has an iterator to loop over elements) while the other is not.

**Comment by CyrusNajmabadi** [comment]
> Follow up question -- How should I change the IEnumerable one then to cause that one to get picked? 

1. Rename it?
2. Have it do a dynamic check if it was given an IEnumerable and if so, have it call the IEnumerable-taking overload?

**Comment by sujayvsarma** [comment]
Thanks again. I found renaming it (your option 1) was a better way, since it also communicates the intent clearly than an overload would. 

Thank you for your help. Good night now! :)
