### ISSUE TITLE
Get rid of TestChangeSignatureOptionsService 

### ISSUE THREAD

**Issue by ivanbasov** [dotnet/roslyn#41118]
No tests for this?

(I also admit I'm surprised we have a this as a mock at all -- I would have assumed the tests just directly call into the engine and don't need to call through this. I don't see very many tests using this, can we just delete it which also gets rid of static test state and the risk of sharing it between tests?)

_Originally posted by @jasonmalinowski in https://github.com/dotnet/roslyn/pull/38748/files#r367158802

**Comment by ivanbasov** [comment]
We can refactor VisualStudioChangeSignatureOptionsService and use it directly in tests.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
