### ISSUE TITLE
Performing a Ctrl+Q search leads to redundant GoTo items

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#41115]
**Version Used**: 
Visual Studio 2019 Int Preview 16.5 29716.156

**Steps to Reproduce**:

1. Create a console app with a 'Program.cs' file.
2. Perform a 'Ctrl+Q' search for 'Program.cs'. Note that there is one file, and one class result.
3. Perform a 'Ctrl+T' search for 'Program.cs'.

**Expected Behavior**:
There is one file and one class result.

**Actual Behavior**:
There is one file and two exactly matching class results.

![image](https://user-images.githubusercontent.com/5387680/72833718-3f8b0080-3c3c-11ea-8377-d2fbe1acce22.png)

Effectively the problem is that the same feature (GoTo/NavigateTo) is being lit up by Roslyn via both LSP and an in-proc provider. The intent, however, is to leave Ctrl+T on the in-proc provider to avoid regressing the scenario and build out the new Ctrl+Q exclusively via LSP, eventually switching both over to LSP.

To facilitate this transitionary period, there is a _VSServerCapabilities.DisableGoToWorkspaceSymbols_ capability on the LSP client that can be set to eliminate LSP results from the GoTo feature.

I'd also recommend using this opportunity to move from the 'workspace/beginSymbol' message that was introduced temporarily for 16.3 to the official 'workspace/symbol' protocol which has been upgraded to support streaming via $/progress/IProgress<T> notifications.

Refer to the [C++ language server update](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/217789) for more information.

**cc:** @dibarbet

**Comment by dibarbet** [comment]
> To facilitate this transitionary period, there is a _VSServerCapabilities.DisableGoToWorkspaceSymbols_ capability on the LSP client that can be set to eliminate LSP results from the GoTo feature.
> 
> I'd also recommend using this opportunity to move from the 'workspace/beginSymbol' message that was introduced temporarily for 16.3 to the official 'workspace/symbol' protocol which has been upgraded to support streaming via $/progress/IProgress notifications.

Will introduce the capability for preview 3 definitely, but not sure if the move to workspace symbol will happen in preview3

**Comment by CyrusNajmabadi** [comment]
> Refer to the C++ language server update for more information.

This is not available.

**Comment by gundermanc** [comment]
```
        [JsonRpcMethod(Methods.InitializeName)]
        public InitializeResult Initialize(JToken arg)
        {
            return new InitializeResult()
            {
                Capabilities = new VSServerCapabilities()
                {
                    WorkspaceSymbolProvider = true,

                    // C++ language service has its own non-LSP go to provider,
                    // so we set this capability to avoid having duplicate symbol
                    // results in GoTo.
                    DisableGoToWorkspaceSymbols = true
                }
            };
        }
```

```
        [JsonRpcMethod(Methods.WorkspaceSymbolName, UseSingleObjectParameterDeserialization = true)]
        public async Task<SymbolInformation[]> WorkspaceSymbolAsync(
            WorkspaceSymbolParams args,
            CancellationToken cancellationToken)
        {
            ..
        }
```

args.progress isn't null, the client supports streaming, and you should use progress.ReportProgress() to send back batched updates (perhaps per project) and return an empty array.

If args.progress is null, the client doesn't support streaming, and you should just return all results in a single array.

**Comment by dibarbet** [comment]
Resolved by https://github.com/dotnet/roslyn/pull/41264
