### ISSUE TITLE
Go to Members doesn't filter properly in latest dogfood

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#41122]
**Version Used**: 
> Microsoft Visual Studio Enterprise 2019 Int Preview
> Version 16.5.0 Preview 3.0 [29720.21.master]
> VisualStudio.16.IntPreview/16.5.0-pre.3.0+29720.21.master
> Microsoft .NET Framework
> Version 4.8.04084
>
> ...
> 
> C# Tools   3.5.0-beta3-20063-01+1f921815c4544e703bf721cb8e6c86d5cf6bda63
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Steps to Reproduce**:

1. Open Compilers.sln
2. Open `src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs`
3. Search for a member with `ctrl+,` then type `m VisitLocalFunctionStatement` in the Go to All search box

**Expected Behavior**:
Only members contained in LocalRewriter.cs are shown

**Actual Behavior**:
Members from all over the solution are shown

![image](https://user-images.githubusercontent.com/5833655/72846446-715c9100-3c55-11ea-9c50-8b9ae8ded70d.png)

/cc @dotnet/roslyn-ide

**Comment by dibarbet** [comment]
This seems to be an inconsistent repro depending on if cntrl + Q search is activated.
If cntrl+Q search is running, I see results from outside of the file.  If it's not, it filters properly.

Should be fixed in https://github.com/dotnet/roslyn/pull/41264
