### ISSUE TITLE
Converting from if to switch removes comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/886271/converting-from-if-to-switch-removes-comments.html)._

---
Steps to Reproduce:

Use the following code: 

```csharp
            bool? abc = true;
            if (abc == true)
            {
                Console.WriteLine(3);
            }
            // some comment here
            else if (abc == false)
            {
                Console.WriteLine(4);
            }
            else if (abc is null)
            {
                Console.WriteLine(14);
            }
```

Now use a quick fix to change this to a switch statement:

Expected: 
 Comment should be retained. 

Actual:
I get this: 

```csharp
            bool? abc = true;
            switch (abc)
            {
                case true:
                    Console.WriteLine(3);
                    break;
                case false:
                    Console.WriteLine(4);
                    break;
                case null:
                    Console.WriteLine(14);
                    break;
            }
```
---
#### Visual Studio Feedback System on 1/16/2020, 00:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/16/2020, 02:56 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
FYI: @alrz @allisonchou
