### ISSUE TITLE
Is scripting engine included in version which is published in nuget?

### ISSUE THREAD

**Issue by hungdluit** [dotnet/roslyn#4114]

**Comment by dfkeenan** [comment]
No v1.0.0 is the latest on Nuget.  It does not include scripting.  Scripting is not coming until v1.1 (so I believe).  If you are super keen and want to tryout beta bits the nightly builds are on https://www.myget.org/gallery/roslyn-nightly.

**Comment by hungdluit** [comment]
Thanks for response

The most interesting is, can the engine support me to load a solution and execute methods one-by-one?

**Comment by dfkeenan** [comment]
I'm sorry. I haven't actually tried using it myself, so I don't know the API/usage scenarios it supports.  I am just a random guy from the internet.  I thought I could quickly help you out.  Someone who actually works on the Roslyn team might chime in to give you an answer to your follow question.

**Comment by ManishJayaswal** [comment]
scripting APIs do not support taking in a solution file and then building it using MSBuild and loading all the assemblies that are generated from the build. I don't think we will provide that support in future too but user app ( host)  can provide their custom resolver which supports taking a .sln file and doing the above steps, if they want to. We currently do not provide an ability for the host to pass in multiple assemblies ( which can happen when you are building a solution) but we can add it if needed, in future.

@tmat FYI

**Comment by hungdluit** [comment]
Thanks, *ManishJayaswal <https://github.com/ManishJayaswal>*

I hope, the feature you mentioned will be included in release.

2015-10-24 6:35 GMT+07:00 Manish Jayaswal <notifications@github.com>:

**Comment by ManishJayaswal** [comment]
It will likely not be in this release. However you should be able to use a project ( instead of a solution) in this release. If you get the project working and want the solution functionality then please open an issue for it.

**Comment by hungdluit** [comment]
I seems like, I have to build the projects I need by hand. 

The preference project should be complied to dll, and used as an additional library. Is that right?

**Comment by ManishJayaswal** [comment]
yes, once you have the output dll, you should be able to #r it in your script.
