### ISSUE TITLE
Move using directive style options from Advanced to Code Style

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41147]
These 2 using directive rules should be moved under code style options since there are EditorConfig options for them: 

![image](https://user-images.githubusercontent.com/46729679/72944035-a38cf200-3d2c-11ea-99d5-686249ab5373.png)

**Comment by sharwell** [comment]
Marked as needing a design review since these have not moved in many releases so users might be expecting them in the same place.

**Comment by CyrusNajmabadi** [comment]
It's also not really a code-style.  Curious why these are in .editorconfig.

**Comment by CyrusNajmabadi** [comment]
Oh.  Wait.  Is this referring to the first two options, or the second two?  I latched on the checkmarks, but i think now maybe you're talking about the unchecked ones.

**Comment by mikadumont** [comment]
I am referring to the first 2 unchecked ones.

**Comment by mikadumont** [comment]
If we want to keep these where they are then we should think about what we want to do with other options regarding usings under code styles:
![image](https://user-images.githubusercontent.com/46729679/72944942-4e9eab00-3d2f-11ea-8975-4caa3491b7f8.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
