### ISSUE TITLE
Quick action : move type to *.vb duplicates enum

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41155]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/637617/quick-action-move-type-to-vb-duplicates-enum.html)._

---
when using Quick action : move type to *.vb for a file which also contains an enum creates a duplicates enum in the new file created.

---
#### Visual Studio Feedback System on 7/9/2019, 11:48 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be changing these experiences.
