### ISSUE TITLE
Compiler warning when using IEnumerator in a loop

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41168]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/893454/compiler-warning-when-using-ienumerator-in-a-loop.html)._

---
Hello,

I am working with Unity and C# and faced an issue with IEnumerator, loops and the "yield"-keyword. I created an endless loop in the following setup (example).

```
IEnumerator Foo()
{
    int number = 0;
    while(true)
    {
        if (number == 1)
        {
            yield return new WaitForSeconds(1.0f);
        }

// Missing a yield return outside if-block
    }
}
```

Considering the code above, "yield return new WaitForSeconds(1.0f);" will never be reached and therefore, an endless loop is created.
I would like to suggest that the compiler creates a warning or error when such a situation occurs similar to the following:

```
public bool IsThatTrue(bool b)
{
    if (b)
    {
        return b;
    }
}
```

In this case, the compiler tells me that not all code paths return a value.

I feel like it should be possible to recognize the potential endless loop (while(true)) and give a warning if inside that loop not all paths have a "yield return".

Kind regards
Kevin

---
#### Fiona Niu[MSFT] on 1/22/2020, 07:09 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by 333fred** [comment]
There are limited forms of this, like the simple example given above, that we _could_ theoretically be able to detect. However, this is an extremely expensive request. There are some heuristics that we can apply, but this is effectively attempting to solve the halting problem. Even for these limited scenarios, this would be an extremely expensive analysis that has very little general-purpose use, and as such this is not a feature on our radar.
