### ISSUE TITLE
Add FxCop/Roslyn Analyzers file and class exclusion rules to Tools/Options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41167]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/893755/add-fxcoproslyn-analyzers-file-and-class-exclusion.html)._

---
It looks like FxCop excludes some files (e.g., *.designer) from code analysis.

[Excluding files](https://stackoverflow.com/questions/31069364/excluding-a-file-from-the-roslyn-analyzers)

However, the rules for excluding these files is hard coded.

It would be of value to add there rules as options on .editconfig or under Tools, Options, Text Editor, Code Style and allow adding templates or files so as to exclude Native Methods.  For example, it seems that naming a class _UnsafeNativeMethods_ does not exclude it from analysis. 

Also, it seems that if the code editor opens an .rtf file (for instance, when Find locates an expression in an included RTF file), it gets analyzed, which, obviously, is not intended.

---
#### Fiona Niu[MSFT] on 1/22/2020, 07:07 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
@mikadumont , @mavasani

**Comment by mavasani** [comment]
Couple of things to note:

1. Each analyzer is responsible for declaring if it analyzes generated code or not. This public API already exists. Can you elaborate which rules are analyzing and reporting issues in generated code files when you don't expect (please provide rule IDs)? We should file bugs on specific rules as infrastructure is already in place.

2. Starting VS2019 16.5, you can also explicitly turn off all analyzer diagnostics on any source file or folder by using the following .editorconfig feature: https://github.com/dotnet/roslyn/pull/38886#issue-321838740

**Comment by Youssef1313** [comment]
I think what the user asks for is the already-supported editorconfig `generated_code` option documented [here](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#exclude-generated-code)

@mavasani This could be closed, I think.

**Comment by CyrusNajmabadi** [comment]
Closing out as this seems to be done.
