### ISSUE TITLE
Add item template parameter parentrootnamespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41170]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/890788/add-item-template-parameter-parentrootnamespace.html)._

---
<p>RootNamespace identifies the folder | namespace in which the item template is being generated.  I would like to be able to step up one level so I can step down into another namespace.  For example, if my RootNamespace is MyProject.MyTopContainer.MyContainer.Servcies, I want to add a using statement in the template to another namespace MyProject.MyTopContainer.MyContainer.Models, without hardcoding the full namespace path of MyContainer.</p> <pre>namespace $rootnamespace$ //MyProject.MyTopContainer.MyContainer.Services
{   <br>       //   I don't want to hard code this in a template
 using MyProject.MyTopContainer.MyContainer.Models; <br>          
       //I'd rather use this to get to MyProject.MyTopContainer.MyContainer<br> using $parentrootnamespace. Models;             
   ...
}</pre><p></p><p>Please create an item template parameter ParentRootNamespace.  This would allow me to go up a level.  As a stretch goal, allow the parameter to accept a numeric value, ParentRootNamespace(2), to allow me to specify how far up the namespace I want to traverse, defaulting to 0 for the immediate parent.</p>

---
#### Visual Studio Feedback System on 1/20/2020, 07:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jmarolf** [comment]
This is a Visual Studio request no a roslyn one. We should re-open the [original ticket](https://developercommunity.visualstudio.com/content/idea/890788/add-item-template-parameter-parentrootnamespace.html) and assign it to the VS team.

Incidentally you can do what the user is asking in VS today by writing your own [`TemplateWizard`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.templatewizard.iwizard?view=visualstudiosdk-2017) and passing in whatever properties your template needs.  Though admittedly this is much harder to do correctly.

**Comment by mikadumont** [comment]
Ok will close and link to platform team.
