### ISSUE TITLE
IBrokeredSettingsManager is being renamed ISettingsManager3; please update references

### ISSUE THREAD

**Issue by JoshuaBStevens** [dotnet/roslyn#41197]
ISettingsManager3 has already been added to the RPC contracts assembly (as a verbatim copy of IBrokeredSettingsManager).  IBrokeredSettingsManager will be removed after all references to it are gone.  Please update all IBrokeredSettingsManager references to use ISettingsManager3 instead.

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by tmat** [comment]
I don't see any references to `IBrokeredSettingsManager` in Roslyn master. I guess we didn't end up using it? @dpoeschl

**Comment by JoshuaBStevens** [comment]
@tmat that may be because it was renamed ISettingsManager3.  The old name is still valid but deprecated.  I plan to remove it eventually.

**Comment by jinujoseph** [comment]
ya looks like it was in draft but never merged https://github.com/dotnet/roslyn/pull/40142
