### ISSUE TITLE
Wiki page is missing from top level tabs in roslyn....

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#41204]
![image](https://user-images.githubusercontent.com/4564579/73099512-8416d600-3ea0-11ea-9380-5871187f4e50.png)

Note: links to the wiki from google no longer work.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @sharwell @jinujoseph 

Links like https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues no longer work as well.  They just redirect to the home page.

**Comment by jasonmalinowski** [comment]
Reaching out internally if there's some reason this was turned off.

**Comment by 06needhamt** [comment]
I think this was because #41157 was merged earlier.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jmarolf** [comment]
@CyrusNajmabadi the plan is to move all of this to the [docs](https://github.com/dotnet/roslyn/tree/master/docs/wiki) folder (which is done) so that people can submit prs without having write access to this repo.

**Comment by jasonmalinowski** [comment]
We've turned the wiki back on because this broke a bunch of links. @jmarolf is fixing it up.
