### ISSUE TITLE
Project.RemoveDocument() doesn't validate the DocumentId given belongs to the project instance

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#41211]
https://github.com/dotnet/roslyn/blob/4a7c827296aeabadad587a6619ecf1a3f373cddf/src/Workspaces/Core/Portable/Workspace/Solution/Project.cs#L600-L603

This implementation blindly assumes that the documentId given belongs to the containing project. Right now it's "legal" to pass a documentId from an unrelated project, which will remove the document from the other project.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If you think this needs to be fixed please assign to a dev/milestone.
