### ISSUE TITLE
Pattern matching - Local variable might not be initialized before accessing

### ISSUE THREAD

**Issue by JKamsker** [dotnet/roslyn#41228]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Version 16.4.2

**Code to analyze**:
```
            Reward reward = new VoucherReward();
            var isVoucherReward = (reward is VoucherReward voucherReward);
            if (!isVoucherReward)
            {
                throw new BlException(ErrorCode.RewardNotFound, "Reward is not a voucher reward!");
            }

            voucherReward.Progress = progress;
```
**Expected Behavior**:
Roslyn shouldn't complain here because i check isVoucherReward and throw. Because of this, voucherReward is always initialized.

**Actual Behavior**:
Visual studio won't let me compile this code and shows the error "Local variable 'voucherReward' might not be initialized before accessing"

**Comment by huoyaoyuan** [comment]
The analysis seems only applies to the `is` declaration is directly placed in the condition of `if` block.
Extending the analysis to saved variable won't be acceptable, since its endless complexity.

**Comment by CyrusNajmabadi** [comment]
This is by design.  Roslyn doesn't do flow analysis through multiple variables.
