### ISSUE TITLE
Read .editorconfig properties in other .NET languages' analyzers and formatters?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#41225]
I discuss with @nojaf usage of .edtiorconfig in F# formatter https://github.com/fsprojects/fantomas/issues/650
Regarding that I want to ask:
1. How to read common .NET Coding Conventions and Naming Conventions from .editorconfig using existing Roslyn code regardless Visual Studio instance?
2. How to read common .NET Coding Conventions and Naming Conventions from .editorconfig using Roslyn classes within Visual Studio?
3. How to reuse existing Roslyn code to read custom F# specific conventions?
4. How to provide custom F# specific conventions to consumers in Visual Studio (i. e. F# language formatter)?

**Comment by CyrusNajmabadi** [comment]
> How to read common .NET Coding Conventions and Naming Conventions from .editorconfig using existing Roslyn code regardless Visual Studio instance?

This isn't exposed publicly. But you can see our code for that here: https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser.cs

> How to read common .NET Coding Conventions and Naming Conventions from .editorconfig using Roslyn classes within Visual Studio?

See above.

> How to reuse existing Roslyn code to read custom F# specific conventions

I don't believe you would be able to.

> How to provide custom F# specific conventions to consumers in Visual Studio (i. e. F# language formatter)?

That question would have to go to the F# team: https://github.com/dotnet/fsharp/

**Comment by xperiandri** [comment]
@CyrusNajmabadi, thank you very much!
Could you also point to the place where you discover .editorconfig files and calculate effective having several files?

**Comment by jmarolf** [comment]
@xperiandri [here ](https://github.com/dotnet/format/blob/master/src/Utilities/EditorConfigOptionsApplier.cs) is where we use reflection to get the editorconfig options from the workspace. I don't know what exactly you need. Do you want something to help find and parse the editorconfig? do you want to just pull whatever the naming styles are?

**Comment by xperiandri** [comment]
@nojaf knows better.
I think he needs:
1. Code that recursively discovers .editorconfigs until the file marked as the root
2. Parses all discovered .editorconfigs and returns a filterable dictionary of settings for a particular directory. This includes filtering out options enabled for files other than `.fs`, `fsx` and `fsi`

**Comment by nojaf** [comment]
Hello, I'm a bit confused in regards to this issue.
Fantomas does not use Rosyln in any way, shape or form.

We already have code in Fantomas that does `1`.
As for `2` we also have some code that uses reflection to construct our configuration object, so main thing left there is doing some parsing of the `.editorconfig` file itself.

**Comment by jmarolf** [comment]
[here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CommandLine/AnalyzerConfig.cs) is the parser for editorconfig that the compiler uses. Its a public type so you can use that if its helpful or re-use any of the logic/tests. nuget package that contains that type is [here](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/)

**Comment by nojaf** [comment]
Thanks for the pointer @jmarolf , I think this issue can be closed.
