### ISSUE TITLE
c# intellisense not autocompleting type names in VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41234]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/882734/intellisense-focus.html)._

---
When IntelliSense pops up the currently suggested item does not have focus. You have to press the arrow down key first so it gets selected.

I'll encounter this problem regularly, it was also in 2017. I thought many people would have made an issue/problem for it, but a quick search did not show any signs. A workaround which works most of the time is restart Visual Studio. I'm not aware of any tools I have which might interfere/cause this.

See attached file.

---
#### Visual Studio Feedback System on 1/13/2020, 01:34 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 1/14/2020, 01:15 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Visual Studio Feedback System on 1/23/2020, 10:35 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by ziacik** [comment]
In my case, this helped as suggested in the ticket:

> It is possible that you have entered “suggestion mode”. Please press ctrl+alt+space to go back to normal mode and try again.

**Comment by genlu** [comment]
@ziacik Thanks for mentioning that. We are actually using this issue to track the work of making the state of Suggestion Mode more obvious (and actionable) so people can figure out what's going on and switch to regular mode if needed.

I couldn't find a detailed document for suggestion mode (except being mentioned briefly [here](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019#list-members)), but the idea behind it is to support folks doing Test Driven Development, where they would write tests first using types and members not defined yet, so completion wouldn't get in their way by selecting and committing undesired items.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Suggestion-mode is a platform feature.  And the user enables/disables it at the platform level.  Any work on making this more obvious falls on them, not us (just as it would if this was in vscode, or vs4mac).
