### ISSUE TITLE
Why is NullableExtensions internal?

### ISSUE THREAD

**Issue by chrischu** [dotnet/roslyn#41231]
Hi!

I was just playing around with Microsoft.CodeAnalysis 3.4.0 and the new nullable reference type feature introduced in C# 8 and stumbled upon the `NullableExtensions` class that is internal unfortunately.

Is that because the public API is actively being worked on and is not yet ready for use? Or will this API never become public?

Thanks in advance!

**Comment by CyrusNajmabadi** [comment]
Idon't think they'd ever be released.  They're very tiny helpers that can easily be written in place, or added in an external codebase.  i.e. they're just:

```c#
        public static ITypeSymbol? GetConvertedTypeWithAnnotatedNullability(this TypeInfo typeInfo)
            => typeInfo.ConvertedType?.WithNullableAnnotation(typeInfo.ConvertedNullability.Annotation);

        public static ITypeSymbol? GetTypeWithAnnotatedNullability(this TypeInfo typeInfo)
            => typeInfo.Type?.WithNullableAnnotation(typeInfo.Nullability.Annotation);
```

**Comment by jasonmalinowski** [comment]
So in 3.4, that's all internal because it was some internal scaffolding we knew we were getting rid of but didn't have the time to do so. In 3.5 (not yet released), there are new APIs directly on the compiler API that replace everything in the 3.4 implementations. What's left in 3.5 is what @CyrusNajmabadi linked to, and we have https://github.com/dotnet/roslyn/issues/40961 tracking getting rid of that.

**Comment by jasonmalinowski** [comment]
@chrischu take a look at the 3.5 beta packages and see if that does what you want. Let us know if those aren't making sense and we can help.

**Comment by jasonmalinowski** [comment]
(I'll close this in a few days if @chrischu is back on the right track.)

**Comment by chrischu** [comment]
I tried out the new 3.5 APIs and they do mostly what we need, however I ran into one case I cannot quite explain, maybe you can help me out :).

When I have a nullable field (`string? Nullable;`) and I get the `ITypeSymbol` for its type from the `FieldDeclarationSyntax` with `var typeSymbol = semanticModel.GetSymbolInfo(fieldDeclaration.Declaration.Type).Symbol as ITypeSymbol;` the resulting `ITypeSymbol` does not include the `NullableAnnotation`. Is that expected behavior?

I know I can workaround the issue by using `((IFieldSymbol) semanticModel.GetDeclaredSymbol(fieldDeclaration.Declaration.Variables.Single())).NullableAnnotation`, but I was wondering if there was an easier way to achieve this.

Oh and another thing: Is there an ETA on the RTM release of 3.5?

Thanks!

**Comment by jasonmalinowski** [comment]
Which build are you using? https://github.com/dotnet/roslyn/issues/40925 was a known issue we just tracked down and fixed a week or two ago. If you try the latest 3.5 bits in https://dotnet.myget.org/gallery/roslyn you can see if that's fixed for you.

> Oh and another thing: Is there an ETA on the RTM release of 3.5?

I believe answering such a question is unfortunately above my pay grade. :smile: Did you have a particular concern?

**Comment by CyrusNajmabadi** [comment]
> and I get the ITypeSymbol for its type from the FieldDeclarationSyntax

Can you instead do `GetDeclaredSymbol` on the `VariableDeclarator` of the `FieldDeclaration`?  That will give you back the `IFieldSymbol` which you can then get the `.Type` off of.

**Comment by chrischu** [comment]
> Which build are you using? #40925 was a known issue we just tracked down and fixed a week or two ago. If you try the latest 3.5 bits in https://dotnet.myget.org/gallery/roslyn you can see if that's fixed for you.
Haven't quite gotten around to try the package from the MyGet feed, but since we shifted strategies a little bit (see below) we are fine with the current workaround for now.

> I believe answering such a question is unfortunately above my pay grade. 😄 Did you have a particular concern?
Originally me and my team planned to make the switch to C# nullable reference types (instead of using ReSharper with the ImplicitNullability plugin and Fody/NullGuard) pretty soon, but seeing as a bunch of our internal tools (and R# as well) aren't quite ready for that we will postpone that a bit. Therefore now the release of the RTM version is no longer such a big concern for us in the short term :).

> Can you instead do GetDeclaredSymbol on the VariableDeclarator of the FieldDeclaration? That will give you back the IFieldSymbol which you can then get the .Type off of.
That works!

**Comment by jasonmalinowski** [comment]
Going to close then as it sounds like you've got a plan then. If you run into more issues feel free to file bugs and tag me.
