### ISSUE TITLE
Conditional assignment does not set non-null initialization state

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41273]
**Version Used**: SharpLab x64 (unknown commit)

**Steps to Reproduce**:

```csharp
#nullable enable

using System;

public class C1 {
    string x;
    
    public C1()
    {
        try
        {
            x = "";
        }
        catch (Exception)
        {
            x = "";
        }
    }
}

public class C2 {
    string x;
    
    public C2() // warning CS8618: Non-nullable field 'x' is uninitialized. Consider declaring the field as nullable.
    {
        try
        {
            x = "";
        }
        catch (Exception)
        {
            x ??= "";
        }
    }
}
```

**Expected Behavior**:

No warning for either `C1` or `C2`.

**Actual Behavior**:

A warning (CS8618) is reported for `C2`.

**Comment by jcouv** [comment]
Tagging @gafter as I wonder if this is a known limitation of analysis of `try/catch`.

**Comment by gafter** [comment]
I suspect the handling of `??=`

**Comment by jcouv** [comment]
Ah, right. Only the second sample has a warning. Tagging @333fred instead then for likely `??=` issue.
