### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by lawrencelebowsky** [dotnet/roslyn#41281]
**Version Used**: 
3.4.0 
**Expected Behavior**:
Using a non beta version I would expect not to have the beta word from the file version
**Actual Behavior**:
Microsoft (R) Visual Basic Compiler version 3.4.0-beta4-19568-04

**Comment by jaredpar** [comment]
Sorry for the confusion here but that is not acutally a beta version of the compiler. It's just a quirk of how our infrastructure was working for a while. We've recently changed our infra to avoid this problem.
