### ISSUE TITLE
"Change signature" refactoring moves non-argument tokens of multi-line method invocations

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#4128]
A minor but somewhat annoying bug that hit me today.

---

**Repro**:
In VS2015 RTM, declare the following method:

``` csharp
void M( int a, int b ) { }
```

And use it in a multi-line invocation:

``` csharp
M(
    1,
    2
);
```

Use the "Change signature" quick action on M, and swap the parameters order.

**Expected result**:

``` csharp
M(
    2,
    1
);
```

**Actual result**:

``` csharp
M(
    2
,
    1 );
```

---

FWIW, VS 2013 moves all the parameters on one line, i.e. `M( 2, 1 );`. This is not desirable either, since it may result in very long lines.

**Comment by dpoeschl** [comment]
Thanks for filing this. /cc: @brettfo as FYI because it's related to something he's been working on.

**Comment by brettfo** [comment]
This should work when #1017 is fixed.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
