### ISSUE TITLE
New Visual Basic VSIX Project doesn't offer .Net 4.6

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4129]
![target list](https://cloud.githubusercontent.com/assets/12789369/8896331/357a9a70-33ad-11e5-8335-63316994dd8f.png)

**Comment by Pilchie** [comment]
Support for targeting .NET 4.6 from portable class libraries will be coming as part of the VS Tools for Windows 10.

**Comment by Pilchie** [comment]
This should be available if you install the Tools for Windows 10 development option in VS setup.
