### ISSUE TITLE
Refresh button in reference dialog

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41303]
**Direct customer ask copying here:**
> Create a refresh button in the references dialog. It'd be super helpful when refactoring and such - I find myself clicking then finding refs over and over to effectively do this.
![EPfSLu3XkAEpmTD](https://user-images.githubusercontent.com/46729679/73417853-6f867380-42ce-11ea-9d01-07c4be0f6aed.png)

**Comment by sharwell** [comment]
Yeeessssssssssss

**Comment by Neme12** [comment]
This would also be great in the Find Results window in Visual Studio.
