### ISSUE TITLE
C# IDE: caret disappears after invoking Add Using via keyboard

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#4130]
When using keyboard (Ctrl+.) to invoke Add Using lightbulb on an unbound identifier in a C# file (VS 2015 RTM), the caret disappears in the editor. Everything else keeps working fine (Line/Column update, features work, everything OK except caret not rendering). Also there's a dotted focus rectangle around the Document Well:

![caretdisappears](https://cloud.githubusercontent.com/assets/679326/8896777/3239024e-33bb-11e5-89b1-89a91bafca56.png)

I'm guessing this is some sort of focus issue where instead of returning focus to the editor somehow the document well content presenter itself gets focused (or some other parent in the visual tree).

**Comment by KirillOsenkov** [comment]
To bring back the caret click in the editor using the mouse.

**Comment by davkean** [comment]
@KirillOsenkov does this happen to you all the time?

@basoundr @dpoeschl this sounds very much like the focus issue that you both ran into, maybe the same?

**Comment by Pilchie** [comment]
I believe the editor fixed a bug here between RC and RTM.  Perhaps there is a case that got missed?  /cc @markw-t

**Comment by dpoeschl** [comment]
@davkean This looks much more like the issue @Pilchie is referring to than the focus issue we were talking about recently (which could not be fixed by clicking in the editor).

**Comment by basoundr** [comment]
@davkean This sounds like the same issue except that I dont remember seeing the dotted line around the document.

**Comment by markw-t** [comment]
Thanks for the report. We did fix some focus issues with light bulb between RC and RTM of Visual Studio 2015, but we are still tracking several RTM focus issues in which the focus disappears from the editor after taking a light bulb/quick action. It would be very useful to see a screen capture video of your repro if you have a chance to capture one, so we can make sure we have the exact steps you take right before you hit the problem (this seems to be critical in the repros we've seen so far)

**Comment by HellBrick** [comment]
I've encountered this issue on RTM as well. Don't have the repro unfortunately, but here's another piece of info just in case: when I had returned the focus back by `Ctrl+W,S`, `Esc` (move the focus to Solution explorer and back to the editor), it just kept getting lost all the time after using the light bulb again.

**Comment by KirillOsenkov** [comment]
This issue also reproduces in EditorTestApp.

**Comment by Pilchie** [comment]
Moving to external and resolving.  There are internal bugs tracking this on the editor team.  @markw-t feel free to re-activate this if you find something in Roslyn that needs to change.
