### ISSUE TITLE
complie error CS0193

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41305]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/855599/complie-error.html)._

---
 B = 0.16666666666667 * ep + 0.1875 * efourp + 0.1875‬‬ * esixp + 0.18229166666667 * eeightp;

error:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0193	* 或 -> 运算符只能应用于指针

---
#### Visual Studio Feedback System on 12/13/2019, 02:32 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Visual Studio Feedback System on 12/13/2019, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/16/2020, 05:46 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by YairHalberstadt** [comment]
The error message is "Error CS0193 * or-> operator can only be applied to pointers"

So it looks like this is a parsing error.

**Comment by gafter** [comment]
There are non-printable characters in your source that are causing this problem.  In addition to the error message you report, you will also see two error messages:

```none
error CS1056: Unexpected character '‬'
error CS1056: Unexpected character '‬'
```

These errors are referring to the two bad (but unprintable) characters immediately after `0.1875` and before ` * esixp` in your source.  Remove those characters from your source and the errors will go away.

If you are having difficulty doing so, I suggest you retype the offending line from scratch.
