### ISSUE TITLE
default(SyntaxToken).ValueText could return an empty string

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41304]
**Version Used**: 1b4b5ba7e615e8fdbde036806bac710977e0239c

**Steps to Reproduce**:

```
default(SyntaxToken).ValueText
```

**Expected Behavior**:

Returns `""`.

**Actual Behavior**:

Returns `null`.

This is the only situation where `SyntaxToken.ValueText` returns `null`, and it forces the property itself to have type `string?` instead of `string`. If we update the return value for this case, the property no longer needs to be nullable.

**Comment by CyrusNajmabadi** [comment]
I'm in favor of this.  We already return `""` for things that don't actually have values (i.e. operators/keywords/etc.).  So being `""` for *all* tokens without values would be very nice.
