### ISSUE TITLE
Add a public member of CompletionContext that allows callers to get a snapshot of the completion items for testing purposes

### ISSUE THREAD

**Issue by ymassad** [dotnet/roslyn#41311]
**Version Used**: 
Microsoft.CodeAnalysis.Features, Version=2.6.0.0

For the purposes of testing completion providers, it will be useful for the CompletionContext class to provide a public method that returns a snapshot of the completion items saved in the currently internal Items property.

**Comment by CyrusNajmabadi** [comment]
It's intentionally not exposed.  There may be no actual backing "snapshot" of items to give the user.  That's currently an implementation detail.

If you want a snapshot for testing purposes, you can wrap the existing context object in your own type and expose that for testing.  Your own type then forwards everything along to the real type.

**Comment by Dreamescaper** [comment]
Had same issue, used reflection to get Items in tests.

> you can wrap the existing context object in your own type and expose that for testing. 

Not sure how it's going to work - CompletionContext is sealed class.

**Comment by CyrusNajmabadi** [comment]
> Not sure how it's going to work - CompletionContext is sealed class.

Composition:

`class MyWhatever { private CompletionContext _context; }`

your MyWhatever can track all the information you need for tests, and it will pass along the data as appropriate to the underlying CompletionContext type.

**Comment by Dreamescaper** [comment]
Sure, but I cannot pass this to `ProvideCompletionsAsync` method, which I want to test. So how it helps?

**Comment by CyrusNajmabadi** [comment]
> Sure, but I cannot pass this to ProvideCompletionsAsync method, which I want to test. 

Have an overload that you can test.  Pass it this guy.  Have the normal guy call this guy as well.

**Comment by sharwell** [comment]
It's not possible to test the `CompletionContext.Items` directly, but you can test through `CompletionServiceWithProviders.GetCompletionsAsync`.

**Comment by ymassad** [comment]
@sharwell, how can I test my custom completion provider using the solution you suggested? Can you provide an example?

**Comment by sharwell** [comment]
@ymassad One example would be the testing in `AttributeNamedParameterCompletionProviderTests` in the context of #40097 (prior to this pull request, the class uses internal-only access points for testing, but starting with that pull request it should work like any other completion provider using public APIs).

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
