### ISSUE TITLE
Add Parameter quick fix should add XML doc comment if required

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#41318]
If we use our Add Parameter fix, we should consider automatically adding a XML <param> tag for the parameter if the user has the diagnostic on that would require it.

**Comment by jasonmalinowski** [comment]
#25840 tracks having a quick fix to do the second step automatically, but this would track just doing it automatically.

**Comment by jasonmalinowski** [comment]
In particular the diagnostic I had in mind was:

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573

If that's enabled and there's already at least one doc comment for the other parameters, then we should be adding this automatically or else you're just going to have to do it yourself.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
