### ISSUE TITLE
XML comments from the parameters do not appear

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41321]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/811360/bug-les-commentaires-xml-des-parametres-napparaiss.html)._

---
When I type "///" nerdadds adds an XML comment.

<summary>
        This feature writes the value of an object in a file
        /// </summary>
        "Param name" -" object-type input</param>
        "param name"path" -parametre entry - file path</param>
        WriteInFile (List<object> objects, string path)

Intellisense shows me the name and description of the function "this function writes the value of an object in a file"
The problem is that intellisense should show me the names and types of settings. He should write "object-type input" but does not.

---
#### Visual Studio Feedback System on 11/8/2019, 00:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/12/2019, 06:47 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Design meeting review:

- Additional information potentially takes up lot of space, especially for large parameter lists
- We already show this info if you hover over parameter + also in signature help
- Not heard customer requests on this earlier

**Conclusion:** Wait for more feedback

**Comment by CyrusNajmabadi** [comment]
Closing otu due to lack of feedback.
