### ISSUE TITLE
Better help link for IDE analyzers 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#41324]
Extract from mail 
From @mavasani 
For IDE error codes, we should temporarily hook up the help link for analyzers to https://docs.microsoft.com/visualstudio/ide/editorconfig-code-style-settings-reference, and once we have a dedicated documentation page per IDE rule, we should apply a similar redirection logic

**Comment by Youssef1313** [comment]
@mavasani Can you provide some info if I want to start working on this?

- Should this go into VS docs or .NET docs? (that may depend on whether IDExxxx are only available on VS or are available on command line builds - which I don't know)

- Should this follow the same template for CAxxxx rules?

**Comment by mavasani** [comment]
Thanks @Youssef1313. I am actually working actively with doc team on this work. Once we have laid the ground work for this, I’ll ping you if you are interested on helping out.
