### ISSUE TITLE
Code analysis misdetects IReadOnlyDictionary as collection for CA1710/1711

### ISSUE THREAD

**Issue by RobinHood70** [dotnet/roslyn#4133]
Code analysis flags classes that implement IReadOnlyDictionary as incorrectly named if you use a suffix of "Dictionary". This is incorrect based on both the obvious naming and the pattern outlined in CA1710 in the paragraph "Types with the 'Dictionary' suffix follow this enumeration pattern."

**Comment by lgolding** [comment]
@RobinHood70 Is this diagnostic coming from FxCop, or have you installed the FxCop Analyzers NuGet package?

**Comment by RobinHood70** [comment]
Neither version of FxCop is installed. This is coming from the built-in rulesets that came with Visual Studio Community 2015. Microsoft.Rules.Managed, to be specific. I assume it's some kind of attribute issue in the IReadOnlyDictionary class.

**Comment by mavasani** [comment]
@RobinHood70 Microsoft.Rules.Managed corresponds to the FXCop rules for the post build binary analysis tool FXCopCmd.exe, which is triggered when you invoke "Run Code Analysis" in VS. I verified that the rule implementation in FXCop indeed doesn't account for IReadOnlyDictionary as a valid base type for Dictionary types. So the rule does need to be fixed.
However, we are in process of moving all the FXCop rules to [Roslyn based source analyzers](http://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/1.1.0-beta1-20150812-01), so we should fix this in the Roslyn analyzer for CA1710/CA1711. I'll open a work item in roslyn-analyzers repo to track this work and close this issue.

**Comment by RobinHood70** [comment]
@mavasani 
Thanks for the info. I wasn't aware that it was still running FxCop behind the scenes. I've followed the new thread.
