### ISSUE TITLE
No C# experience in cloud environments when opening a folder

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#41330]
Opening a folder by itself results in a C# experience with no completion, semantic colorization or anything else. Just a basic file. If I instead connect to the cloud environment with a csproj/solution things work just fine.

Would probably make sense to choose a "default" csproj based on the folder opened to resolve project system information.

**Comment by jinujoseph** [comment]
cc @dibarbet

**Comment by CyrusNajmabadi** [comment]
Closing out.  Cloud environments are not a thing.
