### ISSUE TITLE
Need some clarification on how to debug PDB/Source embedding

### ISSUE THREAD

**Issue by iCodeWebApps** [dotnet/roslyn#41337]
Hey Team,

I am hoping you could help me figure out how to confirm, given a DLL, that it has an embedded PDB with embedded Source in the PDB?

I am familiar with the C++ Build Tools, and the use up dumpbin /headers to confirm that the PDB is embedded.

I also need a way to confirm that the source is embedded in the PDB.

I am using the following cjproj configuration to embed my pdb in the dll, and to embed source in the pdb:

```
<EmbedSources>true</EmbedSources>
<EmbedAllSources>true</EmbedAllSources>
<DebugType>embedded</DebugType>
<Optimize>false</Optimize>
```

BONUS QUESTION: it seems that I do in fact have my sources embedded based on being able to Go To Definition on a method in the DLL.  However, I am still not able to Step-Into the code while Debugging.  What am I missing?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of responses here.
