### ISSUE TITLE
Replace Generic Parameters with used Type Arguments in descriptions

### ISSUE THREAD

**Issue by vritant24** [dotnet/roslyn#41353]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13074644/73584670-c4e98e80-444e-11ea-905a-5c1dc5c38162.png)

Could this instead say `Reads structures of type byte from the accessor into an array of type byte`?

**Comment by sharwell** [comment]
We replace `T` everywhere else, it sure seems like we could replace it for `<paramref>` 👍

**Comment by mavasani** [comment]
Design meeting review:
We will accept a PR that implements this support.

**Comment by AdmiralSnyder** [comment]
just so nobody else picks this issue: i already got a working impl. need to confirm some decisions and will make a pr probably this week.

**Comment by Youssef1313** [comment]
@mavasani, this needs to be closed I think.
