### ISSUE TITLE
The new decompilation log should be collapsed by default

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41351]
The decompilation log in #41007 is not collapsed by default, so for short files it is readily visible. The outlining applied to decompiled source files should collapse this region by default.

/cc @siegfriedpammer

**Comment by siegfriedpammer** [comment]
I just tested this and I cannot reproduce this. All comments should be collapsed by default.

**Comment by CyrusNajmabadi** [comment]
Closing as not repro.
