### ISSUE TITLE
IntelliSense shows enum backing field

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4136]
Reported by Klaus Loeffelmann.

Probably related to https://github.com/dotnet/roslyn/issues/4090, but wanted to call it out in case it wasn't. We're showing the backing field of enums:

![image](https://cloud.githubusercontent.com/assets/1103906/8909863/86f282e2-3438-11e5-8765-81d7f9926031.png)

**Comment by rchande** [comment]
@davkean I think this is also fixed by https://github.com/dotnet/roslyn/pull/4209 (since we no longer accidentally show all shared and instance members off a type).

**Comment by Pilchie** [comment]
Can you add a test for it?

**Comment by DustinCampbell** [comment]
Is this fixed? Does the bug need closing?

**Comment by rchande** [comment]
This is fixed. Can you verify, @davkean?
