### ISSUE TITLE
VB partial type completion is incorrect for generic types when commit with parenthesis

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4137]
Consider the following code:

```VB
Partial Class C(Of T)
End Class

Partial Class $$
```

At the $$, the completion list should show "C(Of T)". When completion this item with a left parenthesis, it should complete to "C(" like other symbol completions. However, it completes as "C(Of T)(". This is a regression from Visual Studio 2013.

**Comment by lorcanmooney** [comment]
I've found a number of other issues with this completion provider while looking into #7213. For example...
```
Partial Class C
    Partial Class $$    ' <--   C will be suggested here
End Class
```
...and...
```
Class Foo(Of T)
    Sub Foo()
    End Sub
End Class

Partial Class $$Foo(Of T)   ' <-- Triggering the completion list will include the namespace in the insertion text

End Class
```
I'll try to fix all of these before, or maybe as part of, #7213.
