### ISSUE TITLE
How can i disable xml document generation in c# project

### ISSUE THREAD

**Issue by endink** [dotnet/roslyn#41388]
**Version Used**: 
Visual studio 2019 16.4.4
**Steps to Reproduce**:

1. add `<GenerateDocumentation>false</GenerateDocumentation>` to a csproj file
2. clieck build
3. document always generated

**Expected Behavior**:
How can i disable xml document generation ?

**Comment by sharwell** [comment]
The property is `GenerateDocumentationFile` 👍
