### ISSUE TITLE
Question - String Interpolation & IDE0071 - Custom ToString()

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#41381]
In a class where there is a custom `ToString()` implementation, when using string-interpolation in any method or property in that class and that calls in the `ToString()` within the interpolated string, you get an `IDE0071` suggestion to simplify the interpolation. 

For example, place this in a class:

```csharp
override string ToString() => "Foobar";

string GetViaInterpolation() => $"Hello {ToString()}";
```

In the above code-block, you will see `IDE0071` on the `ToString()` within the `{}`. 

Now, the problem is that accepting this suggestion turns `ToString()` into `ToString` [all it does is remove the `()`]. 

```csharp
string GetViaInterpolation() => $"Hello {ToString}";
```

Now, this is obviously wrong, because `ToString` is a method and not a property. This produces `CS0428` saying there is no such method group or property in the class [correct!]

The actual suggestion should be to turn `ToString()` into `this`:

```csharp
string GetViaInterpolation() => $"Hello {this}";
```

Can this be fixed somehow?

**Comment by CyrusNajmabadi** [comment]
On it.

**Comment by aybe** [comment]
In the following code it'll suggest to remove ToString:

```
public override string ToString()
{
    return $"{base.ToString()}, {nameof(Flags)}: {Flags}";
}
```
But if you do then you'll get `Cannot use 'base' expression in this context`, so this is a false warning that shouldn't be emitted.

**Comment by CyrusNajmabadi** [comment]
@aybe Can you please file a separate issue?  thanks!

**Comment by aybe** [comment]
https://github.com/dotnet/roslyn/issues/43562

**Comment by aybe** [comment]
@CyrusNajmabadi 

But how come I am still getting these ? I use latest Visual Studio against a Unity project.

Thank you

**Comment by CyrusNajmabadi** [comment]
Because you're using a version of VS that doesn't have hte fix yet :)

**Comment by aybe** [comment]
Okay, I'll wait for the update then 😃
