### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "ERR_AssgReadonly"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#41386]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
A readonly field cannot be assigned to (except in a constructor of the class in which the field is defined or a variable initializer))

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
can the sentence be rephrased as "A readonly field cannot be assigned (...)", as the object the field can not be assigned to does not exist?

**Comment by ryzngard** [comment]
@PDostalek It might be more helpful to reword entirely. "A readonly field cannot be assigned a value (except in a constructor of the class in which the field is defined or a variable initializer)" 

"A readonly field cannot be assigned (...)" still gives the same meaning and is more correct grammatically than the original.

**Comment by PDostalek** [comment]
Many thanks
