### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "DocumentIsOutOfSyncWithDebuggee"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#41387]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The current content of source file '{0}' does not match the built source. Any changes made to this file while debugging won't be applied until its content matches the built source.

File Name:
Features\Core\Portable\xlf\FeaturesResources.xlf

==========================================
Query:
Does "built source" mean "compiled source code"?

Affected IDs:
0; "UnableToReadSourceFileOrPdb"
Unable to read source file '{0}' or the PDB built for the containing project. Any changes made to this file while debugging won't be applied until its content matches the built source.

Q2: Containing what? The source file or PDB?

**Comment by tmat** [comment]
> Does "built source" mean "compiled source code"?

Yes. The source code that was used to compile the assembly.

> Q2: Containing what? The source file or PDB?

We mean the project that contains the source file listed in `'{0}'`. The issue is that we can't read the source file itself, or the PDB that is built for this project.

**Comment by PDostalek** [comment]
Thank you
