### ISSUE TITLE
Ability to port Rule Sets to EditorConfig 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41393]

**Comment by mavasani** [comment]
We implemented this in VS2019 16.5 Preview2. There is also a NuGet package [Microsoft.CodeAnalysis.RulesetToEditorconfigConverter](https://www.nuget.org/packages/Microsoft.CodeAnalysis.RulesetToEditorconfigConverter) that enables the conversion from command line.

I also added documentation for this in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5828/files#diff-a4705fb2096f08b51b83a5701a483c76R129, which is not yet published on docs.microsoft.com, it will be once 16.5 is released.

**Comment by jmarolf** [comment]
@mavasani I assume there is no way to convert automatically from within VS (I can't navigate to the docs link)?

**Comment by mavasani** [comment]
If you open the ruleset file in ruleset editor, you should see an infobar at the top, which allows converting the ruleset to .editorconfig. We also talked about potentially offering a context menu on ruleset files in solution explorer to invoke the conversion and also about having an IDE suggestion in error list with a special context menu item to perform conversion, but nothing else is planned to implemented as of now.

**Comment by mavasani** [comment]
RE: docs link requires you to have permission for that repo. Let me forward you the email with details.

**Comment by stogle** [comment]
I have Visual Studio 16.6.2 and I'm not seeing the info bar when I open the ruleset I'm using in my solution. Under what conditions is it supposed to show?

**Comment by mavasani** [comment]
@stogle It only shows up if the ruleset is not used from any native/C++ project context, as those projects still need ruleset for configuration.
