### ISSUE TITLE
Revisit ApiUsageIncrementalAnalyzerProvider

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#41411]
This analyzer collects API telemetry, which adds some overhead.
Consider collecting the telemetry by other means that do not consume user machine resources.

**Comment by sharwell** [comment]
🔗 This was the root cause of https://developercommunity.visualstudio.com/content/problem/947299/vs2019-164-servicehubroslyncodeanalysisservice32-u.html

**Comment by mavasani** [comment]
I have seen it bunch of times in my performance traces when I see ServiceHub.RoslynCodeAnalysisService burning CPU. I think we should talk with the partner team(s) that uses this telemetry, make it opt-in for now (opted into telemetry + `BackgroundAnalysisScope` is set to `EntireSolution`) and think of an alternate long term approach to collect telemetry without using so much machine resources.

**Comment by mavasani** [comment]
Tagging @jinujoseph @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This type was removed entirely.
