### ISSUE TITLE
IntelliSense foible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41426]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/899638/intellisense-foible.html)._

---
I usually change a 'for' loop's variable's name to be more meaningful than 'i'.

However if you change the 'for' loop's start value at the same time then, inadvertently, press the tab key before removing the original start value assignment, IntelliSense does the following:

```csharp
namespace IntelliSense_foible
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

for (int iIndex=2 = 0; iIndex=2 < length; iIndex=2++)
            {

}
        }
    }
}
```

... to which the compiler objects.

---
#### Visual Studio Feedback System on 2/3/2020, 00:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
