### ISSUE TITLE
'Implement abstract class through field' for parity with interface implementation feature

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#41420]
**Version Used**: VS 16.4.4

```cs
/* 🛠 Implement interface through 'reader'
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ */
class Foo : IDataReader
{
    private readonly IDataReader reader;
}

// No help 😥
class Goo : DbDataReader
{
    private readonly DbDataReader reader;
}
```

Writing delegating member implementations is a soul-crushing chore even when there is only one member. DbDataReader has a lot of members.

(ReSharper has this feature)

💡 Another thing that would be super useful for things like Stream and DbDataReader is to be pushed in the direction of delegating not just abstract members but all virtual members. Otherwise you get e.g. the default base ReadAsync implementation wrapping Read poorly rather than delegating ReadAsync to the field's ReadAsync method. (I don't think ReSharper has this.)

How about:

Implement abstract class through 'fieldname' >
 - All overridable members
 - Only abstract members

**Comment by YairHalberstadt** [comment]
Note that a lot of abstract/virtual members tend to be protected, at which point delegation doesn't work. Should there be a warning in such a case?

**Comment by CyrusNajmabadi** [comment]
This is a good idea.  I don't see anything wrong with at least offering this as an option for someone using the feature.  @jnm2 want to pair on this?

**Comment by jnm2** [comment]
Oh sorry for letting this hang, we've been chatting elsewhere. Working on tests now!

**Comment by jnm2** [comment]
@CyrusNajmabadi I'm used to clicking on the `: [||]Base` to find this fix. Does this sound reasonable?

What about `[||]class Derived : Base`?

**Comment by CyrusNajmabadi** [comment]
In general, this will work since *another* feature ensures we bring this up when on hte same line.

For now, the feature code does't need to change, and the test just needs to reflect the span that the feature says it's explicitly available on.

**Comment by CyrusNajmabadi** [comment]
Also, i would prefer to not change trigger behavior in this PR.  Let's just leave this one for implementing through things.

**Comment by jnm2** [comment]
> In general, this will work since another feature ensures we bring this up when on hte same line.

It's not working in the tests I wrote. Was it meant to?
