### ISSUE TITLE
Generate constructor incorrectly adds null checks for nullable propeties in c#8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41428]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/902752/generate-constructor-incorrectly-adds-null-checks.html)._

---
If you declare an immutable class in c# 8 with explicit nullable references enabled:

```csharp
class Foo
{
  public string Prop1 {get;}
  public string? Prop2 {get;}
}
```

And then choose the quick action to generate a constructor with the "Add null checks" checkbox ticked, it creates a constructor that adds null checks for both Prop1 and Prop2.

When a property is explicitly marked nullable as Prop2 is above, I think the generated constructor shouldn't include null checks for it.

---
#### Visual Studio Feedback System on 2/3/2020, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This seems fairly reasonable to me.  The existing helper is useful for code that cannot describe its intent.  In new NRT-aware code the user has a way to indicate what should/shouldn't be null.  

Open question: in NRT-aware code should we just have "generate constructor" and we just put in the non-null checks autoamtically for non-null params?

**Comment by kendrahavens** [comment]
Design meeting notes:
This is a bug. Adding help wanted label.

**Comment by faso** [comment]
I'd like to work on this, if that's alright

**Comment by CyrusNajmabadi** [comment]
@faso Absolutely!

**Comment by faso** [comment]
Can someone please check if the change in the PR looks alright?

If so, I'll go ahead and start with the tests.

**Comment by jasonmalinowski** [comment]
@kendrahavens @CyrusNajmabadi @sharwell Do you recall if we discussed the library author case which still needs to add null checks for non-C# 8.0 consumers, or consumers that have disabled nullable? I worry I might have been the "this is just a bug" commenter and forgot that this is a feature for _some_ subset of our users. I'll fully admit that subset is perhaps a relative minority and the behavior still looks funky regardless.

To be clear: I'm not _against_ the behavior change. I just don't recall if we explicitly decided to not care or accidentally decided to not care. :smile:

**Comment by CyrusNajmabadi** [comment]
>  or accidentally decided to not care. 😄

I think we accidentally forgot that case.  but that's still ok with me.  i think this is a convenience for the vast majority.  If we hear otherwise, we could always tweak to allow people to get the old behavior (maybe through another fix item on the list)
