### ISSUE TITLE
CS8602 should consider Assert.NotNull in unit tests

### ISSUE THREAD

**Issue by pablocar80** [dotnet/roslyn#41422]
**Version Used**: 
NET Core 3.1

source repository available [here](https://github.com/integrativesoft/lara)

**Steps to Reproduce**:
The following unit test yields the warning that `node` variable in the last line may be null:

```csharp
[Fact]
public void AppendData()
{
    var div = Element.Create("div");
    var builder = new LaraBuilder(div);
    builder.AppendData("a<a");
    var node = div.GetChildAt(0) as TextNode;
    Assert.NotNull(node);
    Assert.Equal("a<a", node.Data);
}
```

**Expected Behavior**:

The line before it tests for `Assert.NotNull` thus thereafter the variable isn't null.

**Actual Behavior**:

The compiler yields a warning that `node` may be null in the last line.

**Comment by sharwell** [comment]
This was fixed in https://github.com/xunit/assert.xunit/pull/36
