### ISSUE TITLE
Regex "{}" triggers an error in highlighting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41425]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/896254/regex-triggers-an-error-in-highlighting.html)._

---
The simple regex

```
private static readonly Regex Example = new Regex("{}");
```

Triggers an error because the highlight expects a digit. But actually this is a valid regex matching "{}" litteraly.

---
#### Visual Studio Feedback System on 1/28/2020, 03:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
INteresting.  this is supposed to work.  checking.

**Comment by CyrusNajmabadi** [comment]
I don't repro this:

![image](https://user-images.githubusercontent.com/4564579/73877011-cfb87080-480c-11ea-8198-911e3da2fb35.png)

Note, if you do add a digit you get a message:

![image](https://user-images.githubusercontent.com/4564579/73877060-de9f2300-480c-11ea-877a-f1918d5ceb85.png)

But this is correct as it exactly matches the .net runtime's behavior:

![image](https://user-images.githubusercontent.com/4564579/73877141-fecee200-480c-11ea-833f-38ef8c40b3de.png)

**Comment by Lyra2108** [comment]
I reported that Bug for VisualStudio and I still cann reproduce it there.

![grafik](https://user-images.githubusercontent.com/2102141/73935937-02806880-48e2-11ea-8575-be822e8d7c36.png)

**Comment by sharwell** [comment]
@Lyra2108 I cannot find a message `'Digit' expected` reported anywhere in Roslyn.
