### ISSUE TITLE
Suggestion to remove type conversion is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41434]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/903299/suggestion-to-remove-type-conversion-is-wrong.html)._

---
In the following code line Visual Studio makes a suggestion to remove the first `CSng` because of conversion redundancy.
`Dim NewPointF As New Drawing.PointF(CSng(Math.Round(100 * 0.2)), CSng(0.2))`
But this is wrong, because in this case `Math.Round` returns a `Double` (which can also be seen when hovering the mouse over `Math.Round`) and this would be a wrong argument for the `PointF`-ctor

---
#### Visual Studio Feedback System on 2/3/2020, 03:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse vb experiences.
