### ISSUE TITLE
Don't recommend auto properties in serializable classes

### ISSUE THREAD

**Issue by uecasm** [dotnet/roslyn#41468]
**Version Used**: 
VS2017 15.9.19

**Steps to Reproduce**:

    [Serializable]
    public class Cat
    {
        private int _Meows;    // IDE0032
        public int Meows
        {
            get => _Meows;
            set => _Meows = value;
        }
    }

**Expected Behavior**:
No warning; changing the name of a private field in a `[Serializable]` class will break the serialization (as this attribute usually means that something like `BinaryFormatter` is being used).

**Actual Behavior**:
IDE0032 C# Use auto property warning and greyed out.

Related: the IDE should offer "suppress this warning" in the action list, which will wrap the line in the appropriate `#pragma warning` lines.  From experience with Resharper, these sorts of code inspection warnings are frequently incorrect at at least one code site, and should be easy to suppress.

**Comment by uecasm** [comment]
Although if the field is marked with `[NonSerialized]` then it could be safely converted to an auto-property (provided that the attribute is retained in `[field:NonSerialized]` form), so IDE0032 could be kept in that case.

**Comment by uecasm** [comment]
An alternative to `#pragma warning` would be to support `SuppressMessageAttribute` on the property or containing class, for example.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/42274
