### ISSUE TITLE
Should not offer "Implement interface" if only "Implement interface explicitly" is legal

### ISSUE THREAD

**Issue by latkin** [dotnet/roslyn#4146]
If signatures in an interface include inaccessible types, it is only legal for a public type to explicitly implement that interface.

I still get a lightbulb suggestion/refactoring to try the (bogus) implicit implementation:

![image](https://cloud.githubusercontent.com/assets/5943573/8915092/c63619b8-3457-11e5-91e9-c5c0c1ef7718.png)

It would be nice if only "Implement interface explicitly" was offered in this scenario.

**Comment by Pilchie** [comment]
Note, this is NOT a regression from VS2013.

An alternative solution would be to force the individual method to be implemented explicitly in this case, as we do if there is a name clash.
