### ISSUE TITLE
Unexpected CS8632 when configuring with nullable instead of Nullable

### ISSUE THREAD

**Issue by patrickklaeren** [dotnet/roslyn#41470]
**Steps to Reproduce**:

Given the following class:
```cs
public class Foo
{
    public string? Bar { get; set; }
}
```

Creating a `Directory.Build.props` file with the following:
```xml
<Project>
  <PropertyGroup>
    <nullable>enable</nullable>
  </PropertyGroup>
</Project>
```
Results in CS8632, a compiler warning that you must use this in a nullable enabled context.

Changing the props file to `Nullable` instead of `nullable` works as expected and removes the warning.

Should this be case sensitive?

Relevant:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L100

**Comment by jcouv** [comment]
It looks like that is the expected behavior with MSBuild and will repro with any build setting (not just `Nullable`).
Let's confirm and, if so, we can close as by-design.
