### ISSUE TITLE
crash C# (Incorrect source)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41481]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/897601/clash-c-incorrect-source.html)._

---
C#プロジェクト(Microsoft .NET Framework Version 4.8.03752)で、  
以下の誤ったソースを記述するとVisual Studio Community 2019(Version 16.4.3)が動作停止することを確認したので報告致します。

```C#:crash
interface A
{
    object A.B{
```

---
#### Visual Studio Feedback System on 1/28/2020, 03:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 2/5/2020, 11:26 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

---
### Original Solutions
(no solutions)

**Comment by gafter** [comment]
This no longer crashes the compiler.  See for example [HERE](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoPABhLwGYACAbxJqZr13sec+3wE4AKAESAeDcAg+wICUAbg5MAviXnESASwB28BADMIAYzg0AgiQbFOAe2AArODpiGAdACE6QA===).  I will add a test to demonstrate that.
