### ISSUE TITLE
Inference, generic constraint and optional parameters

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#4148]
Hi

The following code does not compile:

public static void Foo()
{
    Foo("");
}
public static void Foo<T>(T item) where T : IDisposable
{
}
public static void Foo<T>(T item, string bar = null)
{
}

Because string does not implement IDisposable. 

However, I think that in this particular scenario, the last method Foo should be used.

**Comment by HaloFour** [comment]
Generic constraints aren't considered a part of the signature for overload resolution per the spec, so this behavior is technically correct.  As for whether or not it is appropriate that is a different discussion which would involve proposing changes to the spec.

http://blogs.msdn.com/b/ericlippert/archive/2009/12/10/constraints-are-not-part-of-the-signature.aspx

**Comment by MatthieuMEZIL** [comment]
Ok. 
So I'm closing the issue but I think this is an interesting point to consider for the future.
