### ISSUE TITLE
incorrect nullable decimal prefix increment pattern

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41496]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/898889/incorrect-nullable-decimal-prefix-increment-patter.html)._

---
Prefix incrementing a nullable decimal property evaluates the getter twice.
Once in the call to HasValue and a second time in the call to GetValueOrDefault().
This is inconsistent with the pattern used for other nullable types.
This might be a problem for properties with side effects within the getter.
The same inconsistency happens for nullable decimal indexers and the prefix decrement operator.
Regards,
B

---
#### Visual Studio Feedback System on 2/3/2020, 00:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by agocke** [comment]
```C#
using System;

namespace ConsoleApp1
{
    struct StructA
    {
        public static StructA operator ++(StructA x)
        {
            return default;
        }
    }

    class Program
    {
        public decimal? NullableDecimal
        {
            get
            {
                Console.WriteLine("getter1");
                return 1;
            }
            set
            {
                Console.WriteLine("setter1");
            }
        }

        public StructA? NullableStructA
        {
            get
            {
                Console.WriteLine("getter3");
                return new StructA();
            }
            set
            {
                Console.WriteLine("setter3");
            }
        }

        public decimal? this[int index]
        {
            get
            {
                Console.WriteLine("getter2");
                return 1;
            }
            set
            {
                Console.WriteLine("setter2");
            }
        }

        public StructA? this[int index, int index2]
        {
            get
            {
                Console.WriteLine("getter4");
                return new StructA();
            }
            set
            {
                Console.WriteLine("setter4");
            }
        }

        public void Method()
        {
            ++this.NullableDecimal;
            ++this[0];

            ++this.NullableStructA;
            ++this[0, 0];
        }

        static void Main(string[] args)
        {
            Program p = new Program();
            p.Method();
        }
    }
}
```

attached sample program

**Comment by agocke** [comment]
@jaredpar It's probably worth figuring out

1) if this is legacy behavior
2) if this is correct according to the spec

**Comment by jaredpar** [comment]
This behavior is a deviation between Roslyn and the native compiler but it goes back to the earliest Roslyn versions. Would need a strong justification for changing at this point. Won't Fixing until a substantial reason occurs.
