### ISSUE TITLE
C# Struct Inherited Interface Causes Cycle In Interface Hierarchy

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41501]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/872880/c-struct-inherited-interface-causes-cycle-in-inter.html)._

---
[regression] [worked-in:15.9.18]
When compiling the following code in Visual Studio 2019 (.NET 4.6.1 project)

```
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }

public struct TestStruct : TestStruct.IInnerInterface
    {
        public interface IInnerInterface
        {
        }
    }
}

```
it generates the following compile error:
`CS0529 Inherited interface 'TestStruct.IInnerInterface' causes a cycle in the interface hierarchy of 'TestStruct'`

The code compiles successfully in Visual Studio 2017. 

The error can also be seen in .Net Core 3.1 using the default Roslyn compiler, however by importing the nuget dependency
```
    <ItemGroup>
      <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.3.1" />
    </ItemGroup>
```
to change the version of the compiler to an older version the code can successfully compile.

---
#### Visual Studio Feedback System on 1/2/2020, 10:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 2/6/2020, 07:32 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### David Symmonds on 2/7/2020, 00:16 AM: 

<p>I've been waiting patiently for this to be resolved as this is also breaking my existing code base. The last (automated?) comment is a little disheartening given that I'd assumed breaking changes to existing code bases would be prioritised.</p>

---
### Original Solutions
(no solutions)

**Comment by jeffphilp** [comment]
Will this change be backported to the v3.4 compiler which ships with .NET Core 3.1?

**Comment by AlekseyTs** [comment]
CC @agocke

**Comment by agocke** [comment]
This should come out as an update to the .NET Core 3.1.x SDK, coinciding with the Visual Studio 16.6 Preview 1 release.
