### ISSUE TITLE
Null suppressions that will be fixed by .NET 5 annotations

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#41539]
This issue is meant to cover the null suppression operator (`!`) uses in our code base that will be fixed when we move to the .NET 5 TFM. The APIs in the .NET 5 TFM contain the necessary annotations to let us remove these suppressions.

Specific APIs that we're waiting for the annotation change on:

` `RuntimeHelpers.GetHashCode`

**Comment by RikkiGibson** [comment]
This should probably be closed in the follow up to #66565.
