### ISSUE TITLE
Is there any explanation about CS8521(Pattern-matching is not permitted for pointer types)?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#41536]
My project can't build right now, is there any breaking changes in some version?
Is there any link to explain this?
```
byte* p = null;
bool flag = p is null; //CS8521
```

**Comment by tamlin-mike** [comment]
I found the following table:
https://gist.github.com/thomaslevesque/43e4950a65961e2194e4ce082d64bc31

> CS8521 | Error | Pattern-matching is not permitted for pointer types.

Looks like a compiler regression to me.

Note to Microsoft: That table is something you could learn from.

**Comment by CreateAndInject** [comment]
That link is dead in China.
Any official reply?

**Comment by jmarolf** [comment]
"Pattern-matching is not permitted for pointer types." is the english text for the error message. Its possible there might have been a bug in beta versions of the compiler but I do not think pattern matching was ever allowed on pointers @gafter?

**Comment by CreateAndInject** [comment]
@tmat @gafter Do you know?

**Comment by 333fred** [comment]
This does not reproduce for me on 16.7.
