### ISSUE TITLE
Go To Implementation does not work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41533]
**Version Used**: 
Version 16.6.0 Preview 1.0 [29809.2.master]

Don't have a 16.5 build to figure out if its also busted in it.

**Steps to Reproduce**:

1. Right-click on IFoo and click Go To Implementation

``` C#
  interface IFoo
  {
  }

  class Foo : IFoo
  {

  }
```

**Expected Behavior**:
To navigate to Foo

**Actual Behavior**:
Results window opens with nothing in it

![image](https://user-images.githubusercontent.com/1103906/74123584-6c22ae80-4c23-11ea-8919-9b828388e432.png)

**Comment by tamlin-mike** [comment]
Works in 16.4.4.

**Comment by sharwell** [comment]
@olegtk I am not able to reproduce this when running Roslyn's master or master-vs-deps branch with an experimental instance of 16.5 Preview 2. I'm guessing it could be a problem with the editor instead.

**Comment by jinujoseph** [comment]
@olegtk  looks like related to https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/201771?_a=files&path=%2Fsrc%2FEditor%2FText%2FDef%2FTextUI%2FCommanding%2FCommands%2FGoToImplementationCommandArgs.cs

**Comment by jinujoseph** [comment]
routed to [editor ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1066865)
