### ISSUE TITLE
Back Arrow or backspace key works in *Peek Defnition* window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41548]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/897015/back-arrow-or-backspace-key-works-in-peek-defnitio.html)._

---
It would be nice if back arrow (in upper right corner) or backspace key worked in *Peek Definition* window.

**Example**  
1.  In CloneFixture.cs, I right click and go to implementation of Repository.Clone().
2.  File changes to Repository.cs.
3.  In Repository.Clone() I click *Peek Definition* on class CloneOptions
4.  In CloneOptions, I click *Peek Defnition* on CloneOptions base class FetchOptionsBase

**What I would like to happen**   
*  I click back arrow in upper right corner or hit backspace key and it goes back to CloneOptions *Peek* window

**What actually happens**  
*  The *Peek* window completely closes and the page changes to CloneFixture.cs because that's the file I was in before I went to Repository.cs

---
#### Visual Studio Feedback System on 1/28/2020, 01:19 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.
