### ISSUE TITLE
Treat [Description] attributes as if they were XML <summary> docs.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41549]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/883077/treat-description-attributes-as-if-they-were-xml-d.html)._

---
They are much less verbose and treating them as XML docs would eliminate the need to duplicate the text in [Description] and &lt;summary>. Maybe also add more attributes for the other XML doc tags and phase out XML docs entirely? They aer so wordy!

---
#### Visual Studio Feedback System on 1/14/2020, 00:24 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Design review conclusion: we're unlikely to implement this feature _as stated_ unless one of the designer teams using these attributes came forward with a very specific behavior proposal which is part of a larger experience that many users would benefit from. However, there are short- and medium-term workarounds which may turn out to work very well:

### Analyzer/fix for creating comments

It would be possible to create an analyzer for properties that have a `[Description]` attribute but do not have a `<summary>` documentation, and a code fix that created the `<summary>` by copying the description. This would work very similar to e.g. [SA1609PropertyDocumentationMustHaveValue](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609PropertyDocumentationMustHaveValue.cs)/[SA1609SA1610CodeFixProvider](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/SA1609SA1610CodeFixProvider.cs) which creates a `<value>` element by copying the content of an existing `<summary>` element.

### Source generator for creating comments

If the language adopts a feature that allows for `partial` properties (similar to `partial` methods that we have today), then a source generator could be used to automatically create a partial method declaration with a documentation comment based on the content seen in the `[Description]` attribute. This approach would allow for zero-effort maintenance of the `<summary>` element for teams that prefer to just use `[Description]`.
