### ISSUE TITLE
Be able to toggle warnings from the *editor*configuration; not just per project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41540]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/893813/be-able-to-toggle-warnings-from-the-editorconfigur.html)._

---
It would be nice to be able to enable/disable compiler warnings (and the warnings showed by the static analysis/linting since 2019) from within the editor configuration, not just the *project* configuration. This request started from talking with [user](https://developercommunityapi.westus.cloudapp.azure.com/users/172889/b4b4e961-5cf5-654c-bfb2-c5e2ffa2d62c.html) @VisualStudio on twitter; link to conversation for [context](https://twitter.com/VisualStudio/status/1220077625613455361)
I do not user the projects settings from within visual studio as I work on cross platform stuff that are generated with CMake. Also, there are some warnings that I just never want to see (as these are application of &quot;guidelines&quot; (e.g: CppCoreGuidelines some projects cannot adhere to.)</p> <p> </p>

---
#### Fiona Niu[MSFT] on 1/22/2020, 07:09 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
moved to C++ team
