### ISSUE TITLE
Add the ability to find user changes to Analyser ruleset.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41544]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/902497/add-the-ability-to-find-user-changes-to-analyser-r.html)._

---
I made a change to a rule about unused parameters.  I would like to find it and reset it to the original settings.  It would be nice to be able to see a list of rule changes I have made from the original ruleset, preferably in order of data/time the change was made. I would like to see a log of the changes that would allow users to make changes to the current settings.

---
#### Fiona Niu[MSFT] on 2/3/2020, 07:42 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
Is it not possible to view the changes via sourcecontrol ?
