### ISSUE TITLE
Prefer braces should have another option for not prefering braces iff on one line

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41547]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/899523/prefer-braces-should-have-another-option-for-not-p.html)._

---
Settings option "prefer braces" works does not work well I prefer to not use braces when on a single line. If I set "prefer braces" to "No" with warning then it does nothing.  Please consider one of these two options:

- setting "prefer braces" to "no" with warning should warn if I use braces for a single line statement
- add another option "prefer braces iff on multiline" which prefers braces if and only if a code block contains statements on multiple lines

---
#### Fiona Niu[MSFT] on 2/3/2020, 07:52 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this topic.
