### ISSUE TITLE
Improve readability of inherited code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41541]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/897809/improve-readability-of-inherited-code.html)._

---

Sometimes it can be hard to get an overview of what is going on in a specific class. Especially, when a lot of inheritance is involved. Navigating through the references is possible, but going back and forth through multiple classes can be quite annoying when you are new to the code.

What if all code (excluding frameworks etc.) would be visible in every child class? 

Example of ***current situation***:

![image](https://user-images.githubusercontent.com/1408396/74200879-fca9c080-4c1c-11ea-9fde-1b2a35b4539b.png)

Example of ***new feature***:

![image](https://user-images.githubusercontent.com/1408396/74200866-f1569500-4c1c-11ea-8eaa-f2bca37fd5ff.png)

---
#### Visual Studio Feedback System on 1/28/2020, 01:20 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
