### ISSUE TITLE
Ruleset is still needed with .editorconfig to enable disabled rules

### ISSUE THREAD

**Issue by felixhirt** [dotnet/roslyn#41559]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Issue

There are several analyzers (e.g. CA1725) which are disabled by default. This means i need a ruleset file to enable them to some random severity, after which i can set the severity in the .editorconfig file (if i want to, the same as with all the others). Would it be possible to switch all the analyzers to "enabled by default = true" but set the default severity of the ones you don't want by default to "none"? That way i could simply enable (or disable) them by setting the severity in .editorconfig, as with all the others

**Comment by felixhirt** [comment]
Thanks to all of you for the investigations and explanations. I created the issue in roslyn-analyzers because i thought this behavior in Roslyn was by design (sorry for that).

I agree with @mavasani 's last point, it would be nice to be able to simply enable the analyzers and keep their default severity

**Comment by mavasani** [comment]
Ah, this was actually fixed by #40488. I verified this does not repro with the latest VS2019 preview: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview
