### ISSUE TITLE
Missing assembly binding redirect for Microsoft.VisualStudio.VsInteractiveWindow.dll

### ISSUE THREAD

**Issue by zooba** [dotnet/roslyn#4156]
With the version change for the VsInteractiveWindow.dll, a binding redirect in devenv.exe.config is also needed. Otherwise, anyone depending on the 1.0.0.0 version who doesn't ship in VSU1 (e.g. PTVS) will completely fail to load.

**Comment by davkean** [comment]
Move to interactive - as this is a product bug.

**Comment by ManishJayaswal** [comment]
@tannergooding we need to do this for 1.1 release.

**Comment by zooba** [comment]
I thought this was already done? We've been loading fine against most VSU1 builds even while linking against the DLL from RTM. (The places where we aren't loading fine all seem to be installation issues.)

**Comment by ManishJayaswal** [comment]
closing per @zooba comments
@tannergooding fyi
