### ISSUE TITLE
FindReferencesAsync returns incomplete references list?

### ISSUE THREAD

**Issue by 0x900x90** [dotnet/roslyn#41578]
Hello.

I use FindReferencesAsync to find references to variable declarations. But i get different results with following code.

When i create solution using this code everything works as expected
```
workspace = MSBuildWorkspace.Create();
solution = workspace.OpenSolutionAsync("solution.sln").Result;
project = solution.Projects.First();
```
When i use this code FindReferencesAsync can't find some references.
```
AdhocWorkspace ws = new AdhocWorkspace();
SolutionInfo si = SolutionInfo.Create(SolutionId.CreateNewId(), VersionStamp.Create(), "sol.sln");
solution = ws.AddSolution(si);
project = solution.AddProject("project", "assembly", LanguageNames.CSharp);
solution = project.Solution;
```
![2020-02-11_202616](https://user-images.githubusercontent.com/13762536/74262142-60131b80-4d0d-11ea-88b0-ca9d9a7548df.png)
As you can see on the picture "size" is not renamed in 1st case. i logged returned locations and compared logs.

Some references were found in both cases.
![2020-02-11_203641](https://user-images.githubusercontent.com/13762536/74262687-68b82180-4d0e-11ea-8676-5341f0529200.png)

The difference is only in solution creation code. Everything else is the same.

**Version Used**: 3.1.0 with Visual Studio 2017 Also i tried 3.3.0 version with Unity3D.

**Steps to Reproduce**:
Test project.
https://mega.nz/#!UXQFhSLI!VqXXWTAo3O9K4xsQvmhMoriflmuXuQdL86buBrSze9E
Also i attached main script and test files.
[Form1.zip](https://github.com/dotnet/roslyn/files/4191485/Form1.zip)

**Expected Behavior**:
I expect same result in both cases.
**Actual Behavior**:
![actual](https://user-images.githubusercontent.com/13762536/74326883-3d7c1380-4d9c-11ea-9f33-2576773c2176.png)

**Comment by 0x900x90** [comment]
I have additional information.
I collected all IdentifierNameSyntax nodes with parents of type MemberAccessSyntax.
```
        var idNames = root.DescendantNodes()
          .OfType<IdentifierNameSyntax>()
          .Where(prop => prop.Parent.Kind() == SyntaxKind.SimpleMemberAccessExpression);
```
Then i tried to get SymbolInfo
```
          var symb = model.GetSymbolInfo(id).Symbol;

          if(symb != null)
          {
            var def = SymbolFinder.FindSourceDefinitionAsync(symb, solution).Result;
          }
```
But got null in case of AdhocWorkspace
![2020-02-13_171908](https://user-images.githubusercontent.com/13762536/74444328-c28f2780-4e85-11ea-8916-47cdde6b8886.png)

And then everything went absolutely weird. I removed all using statements except `using System;` from test script.
And missed reference and symbol in both cases.
![2020-02-13_171853](https://user-images.githubusercontent.com/13762536/74444504-041fd280-4e86-11ea-8d18-63e82b0cc78d.png)

Here is new script and 2 sets of test files.

[Form1.zip](https://github.com/dotnet/roslyn/files/4198847/Form1.zip)

**Comment by CyrusNajmabadi** [comment]
does your workspace report any errors/diagnostics?
does the Compilation instance for your project report any diagnostics?

**Comment by CyrusNajmabadi** [comment]
Tagging @jmarolf

**Comment by 0x900x90** [comment]
I am new to Roslyn(2 weeks). I try to create standalone app for renaming identifiers. It works like tests for Roslyn. I create workspace dynamically. In AdhocWorkspace case i add dynamically created project into solution. In MSBuildWorkspace case i open fake solution with associated fake empty project. Then i add source files from input folder and process them. VS is not involved.

**Comment by CyrusNajmabadi** [comment]
> I am new to Roslyn(2 weeks). 

Welcome!  We'll def try to help you through this :)

> How i can check errors in case of using AdhocWorkspace.

do `project.GetCompilationAsync()`  then form the Compilation instance you get there, call `.GetDiagnostics()` to see if there are any errors that might indicate what is causing the problem.

**Comment by 0x900x90** [comment]
The problem is that solution is not real and project is not. I can't compile it. I think i don't need to compile project if i only want to analyze sources? They look fine and in case of using MSBuildWorkspace i get fine result.

**Comment by CyrusNajmabadi** [comment]
> The problem is that solution is not real and project is not

That's fine :)

>  I can't compile it. 

You don't need to actually compile anything.  you just need to get a 'Compilation' object: https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Compilation/Compilation.cs

You can do that from your `project` value inyour example able doing `await project.GetCompilationAsync()`.  And then you can see your diagnostics using `compilation.GetDiagnosticsAsync()`.

**Comment by 0x900x90** [comment]
I understood and allready done. Got many undeclared symbol errors etc. Then i added MetadataReference and looks like now it works as expected.

```
      var Mscorlib = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
      ProjectId prj1Id = ProjectId.CreateNewId();

      var workspace = new AdhocWorkspace();

      solution = workspace.CurrentSolution
       .AddProject(prj1Id, "project", "assembly", LanguageNames.CSharp)
       .AddMetadataReference(prj1Id, Mscorlib);
      project = solution.Projects.First();
```
I'll continue tomorrow.

**Comment by CyrusNajmabadi** [comment]
> Now i just want to understand what was wrong.

Well, as you mentioned... your projects did not have references to things like mscorlib.  So, absent that reference, the code was full of errors and lots of things (like the types of expressins) were not known.  

Hence, find all references couldn't find references since it had no idea what your code meant.

**Comment by CyrusNajmabadi** [comment]
This sounds like this all by design and this was due to an incorrect local setup for creating your workspace.

Now that this has been fixed, i don't think this issue needs to stay around anymore.  Also, i recommend using gitter or discord for things like this.  discord.gg/csharp is a good place to continue stuff.  Just use the `#roslyn` channel there.  Thanks!

**Comment by 0x900x90** [comment]
You gave me good suggestions and pointed in the right direction. Thank you for your help.
