### ISSUE TITLE
GoToAll window: result order is messed up

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#41577]
**Version Used**: 
VS 2019 Version 16.5.0 Preview 2.0
**Steps to Reproduce**:

1. 
create a new winforms app (my test is on .Net Framework 4)
2. 
close all files in VS, sometimes you need to restart VS or open Program.cs and close it again
(this is a little fiddly.)
3. 
hit Ctrl-. (or Ctrl-T) and type "form"

**Expected Behavior**:
Form1.cs should be the first item in the resulting list

**Actual Behavior**:
Form1.designer.cs is the first item in the resulting list

i have multiple issues with a regression of the result quality of the GoToAll-Window, but this one is easiest to repro.

here is a screenshot:
![image](https://user-images.githubusercontent.com/16213022/74259863-e113e800-4cf8-11ea-8637-614f963521f3.png)

**Comment by jinujoseph** [comment]
this should be fixed , need validation

**Comment by vsccarl** [comment]
I'm unable to repro in 16.7 Preview 1

**Comment by jinujoseph** [comment]
@dibarbet resolving this issue 
@AdmiralSnyder let us know if you are still hitting this in the latest release
