### ISSUE TITLE
DiagnosticSuppressor is ignored in FullSolutionAnalysis

### ISSUE THREAD

**Issue by Herrmel** [dotnet/roslyn#41573]
**Version Used**: 3.3.1, 3.4.0

**Steps to Reproduce**:

1. Write a [DiagnosticSuppressor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor)(the Suppressor I wrote is for IDE0051)
2. Enable Full Solution Analysis

**Expected Behavior**:
Suppressor always supresses the Diagnostic.

**Actual Behavior**:
Suppressor only supresses the Diagnostic if the document is open in Visual Studio. When the file is closed the Diagnostic is not suppressed and the Supressormethod `ReportSuppressions` is not called.

**Comment by mavasani** [comment]
@sharwell Likely the same issue that you were seeing?

**Comment by sharwell** [comment]
@mavasani Yes, it sounds the same

**Comment by mavasani** [comment]
@jinujoseph @sharwell I have a fix for this issue, but I am not sure if this meets 16.5 bar. So moving this to 16.6 P1 and will send a PR targeting master. Let me know if we want to take this to 16.5 and I can retarget to 16.5 branch.

**Comment by jinujoseph** [comment]
@mavasani 16.6.preview1 sounds good
