### ISSUE TITLE
Extract members to partial 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41588]
This refactoring helps you move selected type members to another part of a partial type. If necessary, we will make the current type partial, create a new part of this type and a file for it.

**Steps to reproduce:**
The steps below gives a user the ability to make a type partial and move selected members there.  

1. Place cursor on the class name or member name.  

2. Press (Ctrl + .) or (Alt + Enter). 

3. Select Extract Members to Partial  

4. The Extract Members to Partial dialog will open. 
![image](https://user-images.githubusercontent.com/46729679/74289134-17df0380-4ce3-11ea-8b97-28811927414a.png)

5. If the current type is not partial, we will suggest to create a new part. Otherwise a user can choose whether to create a new part or choose one of the existing parts to move the members.  

6. Select type members that should be moved to the new part of a partial type.  

7. To apply the refactoring, click Ok. 

8. If no conflicts are found, the refactoring will be performed immediately.

**Comment by CyrusNajmabadi** [comment]
Closing out as specultive.  If we need to do this due to strong feedback, we should assign to dev/milestone.
