### ISSUE TITLE
VS 2019 suggests turning single-line method statements to expression body methods, even if the statement is wrapped in an #if directive.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41596]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/911731/vs-2019-suggests-turning-single-line-method-statem.html)._

---
VS 2019 suggests turning single-line statements to expression body methods, even if the statement is wrapped in an #if directive.
It also does this automatically if I select "For the whole project" on another suggestion (I'm including a picture on what I mean)

Some code you can use to reproduce this: 
```
// Will show a suggestion to turn this in an expression body method, if that's the prefered code-style on the settings.
protected static string GetPluginPath() {
#if FALSE_STATEMENT1 || FALSE_STATEMENT2 || FALSE_STATEMENT3
		string x = "This doesn't matter";
		return x + ".";
#elif FALSE_STATEMENT4
                string x = "This doesn't matter either";
		return x + ".";
#else
		return null;
#endif
}
```

---
#### Visual Studio Feedback System on 2/10/2020, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MrFelna** [comment]
Still an issue with VS2019 16.8.4
Simple code example - if the suggestion is used the code won't compile when targeting Release
```
// VS2019 will prompt to use expression body
private static void SampleMethod()
{
#if DEBUG
    Console.WriteLine("Invoked SampleMethod!");
#endif
}
```
![image](https://user-images.githubusercontent.com/10829781/107119189-e3fad780-687d-11eb-92ae-5d25f4ac7df0.png)

**Comment by CyrusNajmabadi** [comment]
@MrFelna would you like to contribute a fix here?

**Comment by MrFelna** [comment]
@CyrusNajmabadi - I can have a look, but I have not reviewed the Roslyn code before, nor any compiler code. Do you think this is something someone new to the codebase can work on? Having briefly looked at the `Contributing-Code .md` file, I think it can be worked on as a bug fix.

I found this item from the Developer community and wanted to avoid reporting a duplicate issue.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We do not suggest to convert here.
