### ISSUE TITLE
Provide a way to define nullability of generic parameters used to build a return type

### ISSUE THREAD

**Issue by mbashov** [dotnet/roslyn#41607]
`MaybeNullAttribute` can be used to say that a generic method returns a nullable reference type even if the generic parameter, which is used as the return type, is not nullable, [for example](https://github.com/dotnet/runtime/blob/725968c3c5562866c0a8a416b9a635fa54139f75/src/libraries/System.Linq/src/System/Linq/First.cs#L34):
```csharp
[return: MaybeNull]
TSource FirstOrDefault<TSource>(IEnumerable<TSource> source)
```

Is there a way to similarly annotate a method that has a generic return type built with the method's generic parameter? For example:
```csharp
Task<TSource> FirstOrDefault<TSource>(IAsyncEnumerable<TSource> source)
```
The method should be seen as returning `Task<TSource?>` when `TSource` is a non-nullable reference type.

**Comment by jcouv** [comment]
If `TSource` is constrained to `class` (non-nullable reference type), then you can return `Task<TSource?>` already.

**Comment by mbashov** [comment]
So there is currently no option to do the thing for an unconstrained method?

**Comment by jcouv** [comment]
Not presently. We're working on a proposal to allow such a thing in C# 9 (tracking issue https://github.com/dotnet/roslyn/issues/29146)
