### ISSUE TITLE
Add items from unimported namespaces does not sort items

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41601]
**Version Used**: 
Version 16.6.0 Preview 1.0 [29811.143.master]

But this could repro on 16.5, but I don't have build.

**Steps to Reproduce**:
``` C#
using System;

namespace ConsoleApp189
{
  class Program
  {
    static void Main(string[] args)
    {
      AppliesTo
    }
  }

  class AppliesTo { }
  class AppliesToA { }

}

namespace Another
{
  class AppliesTo { }
  class AppliesToA { }
}

```
**Expected Behavior**:
Order to be in:

AppliesTo
AppliesTo (Another)
AppliesToA
AppliesToA (Another)

**Actual Behavior**:

Order switches between:

AppliesTo (Another)
AppliesTo
AppliesToA (Another)
AppliesToA

AppliesTo (Another)
AppliesToA (Another)
AppliesTo
AppliesToA

![Order](https://user-images.githubusercontent.com/1103906/74301662-debc9700-4da7-11ea-8978-23e10b359c43.gif)

**Comment by davkean** [comment]
This is a pretty annoying regression, the imported type is selected by default and if I commit below the namespace is imported and I get an error about ambigious types.

![image](https://user-images.githubusercontent.com/1103906/74309609-3dd9d600-4dbf-11ea-9d70-69deb90f0a14.png)

**Comment by genlu** [comment]
There seems to be two issues. 
- First is the ordering, unimported items shows before in-scope ones. (but the sorting correct itself if you select a filter)
- Another issue is selecting unimported attribute item, when in attribute context. Also seems this is the case even if expander is not selected.

**Comment by davkean** [comment]
> nother Aissue is selecting unimported attribute item, when in attribute context. Also seems this is the case even if expander is not selected.

I'm not sure I follow that bug? If the order was correct, the right one will be selected, right?

**Comment by genlu** [comment]
We would select in-scope one if both present, then problem here seems to be both in-scope and unimported ones are treated as in-scope (thus you see both even when expander is unselected, and selecting it would show two unimport items)

![image](https://user-images.githubusercontent.com/788783/74392100-f18c9700-4dba-11ea-8d4f-b4af32d802dd.png)

**Comment by davkean** [comment]
Ah, yeah I'm seeing this:

![image](https://user-images.githubusercontent.com/1103906/74392249-9c07c700-4e5a-11ea-8c9f-096bd8b9b18b.png)

**Comment by genlu** [comment]
By the way, the first issue is a regression, only appears since 16.5 preview 2. The second is not.

**Comment by pablotdv** [comment]
How can I disable this feature?

**Comment by jmarolf** [comment]
@pablotdv you can turn this off under Tools->Options->Text Editor->C#->IntelliSense

![image](https://user-images.githubusercontent.com/9797472/82619757-ab9a5880-9b8b-11ea-9553-86888fe17ab0.png)

Would really appreciate any feedback you have on what you do not like
