### ISSUE TITLE
C# lambda parameters not marked by DynamicAttribute

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4160]
```C#
using System;

class C
{
    public int Foo()
    {
        return 1;
    }
}

class Program
{
    static void Main(string[] args)
    {
        Func<dynamic, object> f = x => x.Foo();
        f(new C());
    }
}
```

IL:

```
.method assembly hidebysig instance object 
        '<Main>b__0_0'(object x) cil managed
{
  .maxstack  9 
  ...
}
```

As a result EE doesn't display the parameter as dynamic:
![image](https://cloud.githubusercontent.com/assets/41759/8922408/520e6ea6-3497-11e5-96b3-b0da1e97e0ca.png)

**Comment by mbarbac** [comment]
It also happens that, up to VS2013, when using a dynamic argument in a lambda expression (a delegate), these arguments where marked with DynamicAttribute. For instance:

```C#
Action<dynamic> func = x => x.Whatever();
var pars = func.Method.GetParameters();
foreach(var par in pars) {
   var attrs = par.GetCustomAttributes(typeof(DynamicAttribute), true);
   var isDynamic = attrs.Lenght != 0;
}
´´´

The above code now fails with VS2015 and does not identify that the first parameter is a dynamic one.

**Comment by tmat** [comment]
@mbarbac What is the purpose of the code? Why do you need to know whether the parameter is declared as dynamic?

**Comment by mbarbac** [comment]
I'm using the dynamic lambda expressions to define an arbitrary logic operation the program later needs to act upon. For instance, if I write:

```C#
Func<dynamic, dynamic, object> func = (x, y) => x.Age == y.Years;
```
then I know that whenever this delegate is passed as an argument I'm saying that there shall be the need of identify that there is an 'Age' property that can be conceptually compared to the 'Years' one. I'm not intending to bind these properties with any concrete objects, but rather to express the logic of the operation.

So later my code parses that "dynamic" expression and produces an agnostic representation of its logic, that later I can manipulate as I wish - for instance to translate it into SQL code, into a regular expression tree, etc.

In order this parsing to work I was using the code mentioned before where, up to VS2013, each dynamic argument of the method was decorated with the DynamicAttribute. Now with VS2015 it fails as looks like that the compiler does not decorate the arguments any longer - so there is no way to identify when a given argument was a "dynamic" one or not.

**Comment by tmat** [comment]
How do you "parse" the expression? It doesn't seem you're using an expression tree. Could you point me to the actual code (provided it's open source)?

**Comment by mbarbac** [comment]
Sure thing:
https://github.com/mbarbac/Kerosene.Tools - find DynamicParser
https://github.com/mbarbac/Kerosene.ORM - use cases for DynamicParser

Any guidance in how to identify if a parameter is a dynamic one will be very welcomed!

**Comment by mbarbac** [comment]
Actually... it also fails if when compiling with VS2015 I select Net45 as the target framework... so looks like the compiler is forgetting something?

**Comment by tmat** [comment]
I browsed thru the Kerosene source and seems that all delegates passed to DynamicParser.Parse are of type ```Func<dynamic, object>```. Couldn't you just assume/require that all parameters are dynamic?

It also seems like the feature you'd really want is to support dynamic nodes in Expression Trees. Is that assessment correct?

**Comment by mbarbac** [comment]
1.- Not really: a) this signature inherits from old code and has constrained some interesting evolutions, b) as you can imagine the 'Tools' code is not only used in the 'ORM' project, but also in others where the ability of having dynamic and concrete parameters is a must
2.- Not sure what to answer, if I remember well if I try to obtain the expression tree from a lambda where any argument is a dynamic one I got an exception saying precisely this is not supported.

**Comment by tmat** [comment]
1) Is it really a must? Could you point me to use cases that can't work with all parameters typed to dynamic? I'm just trying to figure out what workaround you could use. We will likely fix this bug in the next update. However, meanwhile I don't see how you can detect the dynamic parameters via Reflection. 

To be clear what DynamicParser is doing is not supported - the C# specification doesn't mention anything about DynamicAttribute and doesn't say parameters are going to be marked by that attribute.
On contrary, it states that “The type dynamic is indistinguishable from object at run-time“. The fact that we happen to emit DynamicAttribute is just an implementation detail. The reason why we do so for parameters is to improve debugging experience. But in theory we could write this information to the PDB instead of using an attribute.

Also consider that neither VB nor F# share the C# concept of "dynamic" type. So your library can only be used from C#. 

2) We might support dynamic expressions inexpression trees in future. Having concrete examples of how customers like you would used them is very useful.

**Comment by mbarbac** [comment]
2.- Glad to help... I have missed this since a long time ago: the ability of capturing an arbitrary logic without needing it to be bounded to a concrete type is really something that would have been there since the beginning.

1a.- Humm.... I'm afraid that I cannot share that code. Say that I have a process that accepts a rule, a dynamic rule implemented as a dynamic lambda expression that can take one or many dynamic arguments along with concrete ones. It receives that rule depending the concrete business scenario being processed, instantiates the appropriate number of DynamicNode.Argument instances, and parses the rule (the lambda) using the concrete arguments given. Then it takes the result of the parsing and investigate what to do next. Not sure if I have explained myself.

1b.- Understood it is not covered by the language specification... but there were plenty of info everywhere explaining what it was for. And it worked as a champ previously. I look forward to see this bug fixed in the next update as you say.

1c.- Wasn't aware of the thing re VB, F#... currently we are only using C# but indeed it is something to be taken into consideration. I guess I'll need to wait till dynamic expression trees are released :(

**Comment by tmat** [comment]
Just curious do you handle cases of lambdas like
```Func<List<dynamic>, ...>```?
That is, dynamic as a generic argument or an element argument of an array, etc.

**Comment by mbarbac** [comment]
Interesting... so far I'm not handling it in the sense of intercepting such scenario... have had not need for it so far: the parser stores in its DynamicArguments property the number of arguments that have been identified as dynamic ones, so I can always construct a lambda with an arbitrary number of dynamic parameters without needing a list of dynamics (yep, there is the 15 limit, but I can hardly hit it in any foreseen future)
