### ISSUE TITLE
/warnaserror:nullable does not affect CS8632 or CS8669

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41610]
**Version Used**: 3.5.0 beta 2

**Steps to Reproduce**:

1. Pass `/warnaserror:nullable` to the compiler.
1. Use nullable type annotations (e.g. the `?` in `object?`) in a `#nullable disable` context.

**Expected Behavior**:

CS8632 (or CS8669 for generated code) is reported as an error.

**Actual Behavior**:

The diagnostic is reported as a warning.

**Comment by jcouv** [comment]
Fixed in 16.6p1
