### ISSUE TITLE
Go to Base should not include Object

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#41614]
In the internal preview builds, go to base will include Object.

![image](https://user-images.githubusercontent.com/611219/74363455-72c63880-4d7f-11ea-8d4a-7f5d7adc2740.png)

**Comment by CyrusNajmabadi** [comment]
Does not repro for me:

![image](https://user-images.githubusercontent.com/4564579/199320199-bcfeac53-a411-40a0-ad8c-75c80ce6c97a.png)
