### ISSUE TITLE
Live analyser generates warning message

### ISSUE THREAD

**Issue by keranbabu** [dotnet/roslyn#4162]
I have created a nuget package for live code analysis utilizing the new extensibility template provided with visual studio 2015RTM. I have no issue with live analysis.

When I click on Run Code Analysis or building the application after enabling the code analysis on build, I am getting a warning message
CA0064: No analysis was performed because the specified rule set could not be loaded or did not contain any managed code analysis rule.

**Comment by srivatsn** [comment]
@mavasani can you take a look here?

**Comment by srivatsn** [comment]
Seems to be a dupe of #4073
