### ISSUE TITLE
Verify the formatter cannot produce empty text changes

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41634]
A user reported the following text changes coming back form the Formatter API:

![image](https://user-images.githubusercontent.com/1408396/74387335-1aa62b00-4dad-11ea-939c-b6f1bf78371b.png)

Some of the changes in this result are empty (replacing an empty span with the empty string). We should verify the formatter does not include these results.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this is an issue we should assign to a person/milestone and fix.
