### ISSUE TITLE
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveDirectives.InitializationAfterReset flakey in CI.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#41633]
Caused spurious failure here: https://github.com/dotnet/roslyn/pull/41556

**Comment by jaredpar** [comment]
Looked back over last 100 builds and this is the only failure of the test

## InitializationAfterReset

### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#518143](https://dev.azure.com/dnceng/public/_build/results?buildId=518143)|#41556|1|
### Configurations
- 1-Integration Debug
