### ISSUE TITLE
is vs !is

### ISSUE THREAD

**Issue by SeriousM** [dotnet/roslyn#41649]
**Version Used**: 
C# 8

**Steps to Reproduce**:

Given are these two code snippets:

first:
```cs
var x = new object();
if (x is null) return;
```

second:
```cs
var x = new object();
if (x !is null) return;
```

Notice the second snippet has a `!is` in it.

The two code snippets compile to the exact same IL output:

```il
IL_0000:  nop         
IL_0001:  newobj      System.Object..ctor
IL_0006:  stloc.0     
IL_0007:  ldloc.0     
IL_0008:  ldnull      
IL_0009:  ceq         
IL_000B:  stloc.1     
IL_000C:  ldloc.1     
IL_000D:  brfalse.s   IL_0011
IL_000F:  br.s        IL_0011
IL_0011:  ret         

get_QueryCancelToken:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery._queryCancelTokenOrigin
IL_0006:  callvirt    System.Lazy<System.Threading.CancellationToken>.get_Value
IL_000B:  ret         
```

*`UserQuery` comes from the usage of LinqPad*

**Expected Behavior**:
To raise an error because `!is` is not a documented feature and the `!` is just ignored, which confuses the reader.

**Actual Behavior**:
`is` and `!is` compiles to the same IL.

**Questions**:
* I would love to see `if (x !is null)` as a shortcut for `if(!(x is null))`. Where can I propose this feature?

**Comment by SeriousM** [comment]
Further analysis gives some insight into this issue:

`x !is null` is actually treated as `x! is null` where `!` is `SuppressNullableWarningExpression`.

The nullable-reference checks are only compiler features which explains why the resulting IL is the exact same.

To me, the syntax should should throw an error if the `!` is prepended to the `is` instead appended to the `x`.

**Comment by jaredpar** [comment]
As @SeriousM has noted this behavior is "By Design". The `!` operator is attached to the previous expression, in this case `x`, not the `is` operator. This is used for suppression of nullable warnings only and hence has no impact on the emitted code.

**Comment by CyrusNajmabadi** [comment]
> To me, the syntax should should throw an error if the ! is prepended to the is instead appended to the x.

@SeriousM this would be a breaking change.  However, if you want the compiler to do this, the easiest way would be to write your own analyzer that looks for this pattern and reports an error for you if it appears.

Cheers!
