### ISSUE TITLE
Large object heap (LOH) allocations in PreviewFactoryService.CreateChangedDocumentPreviewViewAsync

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41653]
**Version Used**: 16.4.4

**Steps to Reproduce**:

🔗 https://developercommunity.visualstudio.com/content/problem/903819/light-bulb-configure-or-supress-issues-menu-is-ver.html

**Expected Behavior**:

`PreviewFactoryService.CreateChangedDocumentPreviewViewAsync` generates a preview without significant LOH allocation pressure.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we need to do this, we should assign to a person/milestone.
