### ISSUE TITLE
Add C# option to auto-show the completion list in argument lists after `(` (etc.) and `, ` (like VB does already)

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#41658]
Today in VB, when you are calling a function and type an open parenthesis (or comma space), the completion list shows automatically, soft selected:

![image](https://user-images.githubusercontent.com/235241/74461432-60adce00-4e43-11ea-8bc6-8c4ba97a0d05.png)

In C# today, the completion list doesn't show up until you type a character or hit Ctrl+Space (or Ctrl+j). This option would make C# behave like VB in this regard.

**Comment by dpoeschl** [comment]
Possible issues:

1. Typing `Foo(<tab>` when you want the <tab> to finish the brace completion & move the caret after the inserted `)`, then this will break when a completion item gets inserted. I don't know how many people do this (or even know you can).

**Comment by genlu** [comment]
@jinujoseph I think this is already comlpeted. Right?

**Comment by jinujoseph** [comment]
@dpoeschl @mikadumont @kendrahavens anything pending here that you are aware of

**Comment by genlu** [comment]
Leave this open in 16.8, to track the task of removing experiment and turn this on by default

**Comment by genlu** [comment]
Closed by https://github.com/dotnet/roslyn/pull/50289
