### ISSUE TITLE
Unused parameter of operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41665]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/911753/unused-parameter-of-operator.html)._

---
```VB
Public Shared Operator <>(left As 数组(Of T), right As 数组(Of T)) As Boolean
	Throw New NotImplementedException()
End Operator
```
IDE suggests to delete the unused parameters. However, the parameters are premised by the operator, so though unused they shouldn't be deleted.

---
#### Visual Studio Feedback System on 2/10/2020, 02:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 Note that the diagnostic is expected for this code. Marked as help wanted to avoid suggesting a code fix for this case.

**Comment by AdamSpeight2008** [comment]
@sharwell  The diagnostic maybe expected, but it should also be aware of the [current language requirement](https://github.com/dotnet/vblang/blob/master/proposals/proposal-DerestrictedOperators.md) of "comparison"  operators having to be defined in complementary pairs.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 my expectation would be that teh user should implement the above as:

```
Public Shared Operator <>(left As 数组(Of T), right As 数组(Of T)) As Boolean
	Return Not Left = Right
End Operator
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change tehse vb experiences.
