### ISSUE TITLE
Bringing up CodeActions *in* Roslyn.sln takes a very long time now.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#41667]
I've been editing LanguageParser.cs a lot, and bringing up lightbulbs has super regressed (like 5-10 seconds).  It's so long that the wait dialog is constantly popping up.  I've noticed a ton of messages in that dialo that it's running VSThrd analyzers.  Is this something new in roslyn?  It seems like it's super expensive and really impacting the ability to dogfood the product.

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph

**Comment by sharwell** [comment]
The only changes on this path is improved messaging pointing out _which_ analyzers are running.

**Comment by jcouv** [comment]
Tagging @jasonmalinowski. This is similar to what I've experienced. 

My anecdotal experience is that code actions take longer than they used to to compute (maybe a month or two ago).
I'm not sure why. It could be that I'm running them on unusually large files (`NullableReferenceTypeTest.cs`, but then that file has not grown that much in that time period) or that we added a lot of analyzers (also seems unlikely... But if so, I would suggest a prioritization mechanism to give a quick answer to common ones).

**Comment by sharwell** [comment]
@CyrusNajmabadi can you submit a performance trace and link it so we can investigate?

**Comment by CyrusNajmabadi** [comment]
Sure!

**Comment by CyrusNajmabadi** [comment]
@sharwell This went through (took several attempts): https://developercommunity.visualstudio.com/content/problem/919089/perf-issue-bringing-up-lightbulbs-for.html

**Comment by sharwell** [comment]
Looks like the primary contributor here is `AbstractSimplifyThisOrMeDiagnosticAnalyzer`. We'll need to work on the performance of that analyzer next.
