### ISSUE TITLE
CS8762 false positive claims null out parameter is possible

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#41673]
**Version Used**: 16.6.0 Preview 1.0 (29812.224.master)

**Steps to Reproduce**:

1. Paste the code in this [sharplab repro](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBECWAhgOYB2A9gM4Au+AxpdgMLnACmAgqYQDYCelfJQDcyNJhwAlNgDMebOrXKlRKDFgCsq5AGJSAVx49CAI3no23M22RiAzJhjom6AN7J0nr54D0f9AA8lPoAtiGEAE58AHwe3l5+PugAogAe1BGEipTo1AAWbOg8+NRsmTyBlGyFdBGyALwARFAAbK4AKgC+jT7RuXwADoUyEeQhuQX9Q+h5+GWRdHl86OQy6IToxPgAbpZTbNhx8eiJgT7BYZExR/GnAQORhOPcIWxN1ISUANbtg2wAkqQZORGtF2pNyBF8FtuBVqH8Vmt8oVtrx9IUoAB2NjAdAjMbrUjoSQABSYAFp8KRtuQvjj0K98qxsAEfA9MiFYkhjr5/PdHs8nm9Gh9vgB5GTtX5DQHA0HSOhsHZsHLIyrVdC1BrNNpdHp9eHTfKEajoITrdAmT6FQ2FVaBdlPOprF7C0U/P6ykG9AA0ZrWwP0pGALLZAq5PJOfKxlGiATo0Qy6NZCf96pqzqarQ63V6mvIhlxJmGBeDZqJattMzmmQiiz4whWyIiAHchIV49EZLwqinoqGYxGeQMoajShIWpbyOQKu0ogBxNjUVoS9piiIANTRbBXkulbAAFPuvblPh6ZUDyH6ANoAOXI1Fvhh4AHUCqQD0m2ABKAC6K30U1j0vAB+U9xT3T1L2/G5vHcblIwSJIAFlCDpdBgjqdAWzYAByLCRzYdl6WBCJMBaAJ2micl2FHelbUoP0TGWFteC+KliEtLIvnQfQBlycgJkKLJqH0Xh9nLFYIlogS8SpXE1WkYIeFNEdyCGCJ4UOBDEPQYDgTA919PIAAZcg6HE+pwPPAFL1UXTPBbWZzE/M9jLMiyKgAQisgwjBgnTEPghz4nwNYD3+ShdzXTdt2i1zvnc8zeG/AKQrg2D0s8d1V2M9ArKMqDgQ83h7Ky+IsVyCJ0TKrLOlsQKQsKi9iuSioCrcorTLa7AACFrX3EDsEXahjIPb9asQ+qkEy44csglrBN859JsjSrux4KptEankTGnCpIui9ctx4dF4ry20vW/fKDS67BIsXUgynofd0AAMje9BPzukbHueuh91wWQqRKfBlHG/KCr+VYD1aAJomuiAIH2L1hqXP6oQBv4gZkEGlA/a76ihoYYZOs6KIRibZvQabOiAA==) into a recent build of VS from master branch.

**Expected Behavior**:

No warnings from the nullable type ref system.

**Actual Behavior**:
`Warning	CS8762	Parameter 'taskOfTTypeInfo' may not have a null value when exiting with 'true'.	`

Observe how CS8762 appears even though the code can be read that it only returns `true` if a non-null value is assigned to the out parameter.
Also notice from the screenshot below *where* the highlighted text is associated with the warning. It's highlighting a local method expression body, which is irrelevant to the out parameter of the containing method that is getting the warning.

![image](https://user-images.githubusercontent.com/3548/74481983-e4ca7a80-4e70-11ea-929d-b8a96cd42c42.png)

This came from https://github.com/AArnott/vs-streamjsonrpc/blob/e16b71155f210d7fa5eb5377b90d3e28c26ce947/src/StreamJsonRpc/JsonRpc.cs#L1490

**Comment by jcouv** [comment]
This is a new warning for enforcement of `[NotNullWhen(...)]` on method bodies. I'll investigate. Thx
