### ISSUE TITLE
Navigation bar frequently does not appear in JavaScript or TypeScript files in Visual Studio

### ISSUE THREAD

**Issue by uniqueiniquity** [dotnet/roslyn#41714]
**Version Used**: 
3.6.0-1.20113.7
**Steps to Reproduce**:

1. Open Visual Studio 2019 and continue without code
2. File -> New File -> JavaScript file
3. 

**Expected Behavior**:
Navigation bar should appear at the top of the editor.

**Actual Behavior**:
No navigation bar appears.

When debugging, seems to be due to the change introduced in #41010.

**Comment by uniqueiniquity** [comment]
cc: @dibarbet

**Comment by dibarbet** [comment]
The issue here is that the document may not be created / part of the correct workspace when this code is hit.  This seems to be a more general issue where we need to add/remove the navbar if the document's workspace registration changes.  Working on the fix now.
