### ISSUE TITLE
Switch behavior change between .Net Core 3.0 and 3.1

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/roslyn#41723]
See the following simple repo which works under .net core 3.1 and .net core 3.0, in 3.0 it worked fine however in 3.1 I need the default case for the switch otherwise compilation fails with the message indicated.

```
namespace SwitchTest
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Diagnostics.Debug.Assert(SwitchTest(true) == 1);
            System.Diagnostics.Debug.Assert(SwitchTest() == 0);
        }

        static int SwitchTest(bool input = false)
        {
            switch (input)
            {
                default://.Net Core 3.1 needs this otherwise "Not all code paths return a value"
                case false: return 0;
                case true: return 1;
            }
        }

    }
}

```

**Comment by jaredpar** [comment]
@gafter

**Comment by gafter** [comment]
It was a bug in .net core 3.0 that this code was accepted (in language versions less than 8.0). See https://github.com/dotnet/roslyn/issues/32806 for the bug report. In language version 7.0 and earlier, the `default` should have been required, however we accidentally permitted this code to compile in .net core 3.0 with language version 7.0 and earlier. See https://github.com/dotnet/roslyn/pull/32818 for the PR which fixed that bug (and caused the symptom you are experiencing).

I recommend you work around the issue by specifying language version 8.0 in your .csproj file. Alternatively, keep the `default` in the switch statement.
