### ISSUE TITLE
CodeLens doesn't show references sometimes.

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#41746]
I can't reproduce this issue with exact steps, but I meet it so many times.
When I click `n references`, the popup is empty : 
![image](https://user-images.githubusercontent.com/2529999/74724333-12e7fa00-5277-11ea-99ee-0097290047f8.png)

This time, I can only use `Find All References (Ctrl+K, R)`

**Comment by JoeRobich** [comment]
Also, reported on developer community as https://developercommunity2.visualstudio.com/t/CodeLens-click-does-not-display-any-refe/862923

May be related to https://github.com/dotnet/roslyn/issues/47606

**Comment by JoeRobich** [comment]
Closing as duplicate of #39615
