### ISSUE TITLE
Navigation partial text matching

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#41751]
**Version Used**: 
Visual Studio 2019

**Steps to Reproduce**:
When using `Go To` or Visual Studio Search include partial text matching instead of natively doing exact text match. 

**Actual Behavior**:
When I want to find lets say a class called `EnrichmentConnectionControllerTest` in a project where I have other classes that are named Enrichment… in VS I need to spell out Enrichment before I can start matching on the later part of the class name. 

**Expected Behavior**:
Instead I would like to type something like EnricCoCon and already have a match, which is a huge time saver.

**Comment by jmarolf** [comment]
I think this already works for Go-To-All, unclear which command was used:

![image](https://user-images.githubusercontent.com/9797472/74775080-cdf99e80-5249-11ea-9dbd-a3a6c7ec4c83.png)

**Comment by CyrusNajmabadi** [comment]
I think they might mean 'find in files'. It's not a bad idea imo. Could route to the editor here
