### ISSUE TITLE
Error while hitting tab during declaring a method

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#4176]
Repro:
1. Open C# interactive and start typing the following code
using System.Collections.Generic;
IEnumerable<int> Foo(int max)
2. After typing max, hit tab

We get the following error:

![capture](https://cloud.githubusercontent.com/assets/9527491/8943010/56d2b974-352d-11e5-9b04-0f57572bbfdb.PNG)

**Comment by amcasey** [comment]
I haven't seen that exception, but I'm intermittently hitting some sort of diagnostics Watson.  I'll investigate.

**Comment by amcasey** [comment]
The diagnostics Watson is unrelated, but I'll fix it anyway. :)

**Comment by amcasey** [comment]
I'm unable to repro the issue.
