### ISSUE TITLE
Deleting input prompt in C# interactive throws an error

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#4177]
Repro:
1. Select the input prompt and hit backspace.

We get the following error.
![capture](https://cloud.githubusercontent.com/assets/9527491/8943211/8f6046f2-352e-11e5-9c42-7a366f9e8778.PNG)

**Comment by ManishJayaswal** [comment]
verify scenario in #4777

**Comment by genlu** [comment]
Should be fixed by this PR https://github.com/dotnet/roslyn/pull/5339
