### ISSUE TITLE
Use Implicit Type does not work for 'ref' locals

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#41780]
**Version Used**: fea95d79e2b61c1d40892c7167ebcbb4e4f6a641

**Steps to Reproduce**:

📝 This is supposed to be covered by `SuggestVarOnRefIntrinsicType`, but the test was incorrectly written and thus did not cover the intended behavior.

```csharp
void Method(ref int x)
{
  ref int y = ref x;
}
```

**Expected Behavior**:

IDE0007 reported for `int`, with a code fix that changes it to `var`.

**Actual Behavior**:

No diagnostic.

**Comment by Sliptory** [comment]
I will take this task

**Comment by Sliptory** [comment]
so that the hint appears, you need to write like this:
`void Method(ref int x)
{
  ref int y = x;
}`

in the test SuggestVarOnRefIntrinsicType also
`static void M()
    {
        ref int s = Ref();
    }
    static ref int Ref() => throw null;`
