### ISSUE TITLE
An already nullable property is warned to be non-nullable.

### ISSUE THREAD

**Issue by Yen-David** [dotnet/roslyn#41792]
**Version Used**: Visual Studio 16.4.5
**Steps to Reproduce**:
`public class C<Y> {[AllowNull, MaybeNull] public Y XY { get; set; } }
`
**Expected Behavior**:
No nullability warning shall be issued.
**Actual Behavior**:
Warning CS8618: Non-nullable property 'XY' is uninitialized. Consider declaring the property as nullable.

**Comment by jaredpar** [comment]
This is by design. The attributes used here affect the invocations of the property. Essentially should null be allowed as a value and can it return a null value. It does not impact our determination of whether or not a property was initialized in the constructor.
