### ISSUE TITLE
in IDE, p2p reference with different target .NET framework doesnt report error when command line compiler does

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4179]
repro solution - in mlang fileserver, go to "hechang\repro_p2p\ConsoleApplication2"

open the solution, and do re-build, you will see type from p2p reference is reported by unknown type. and warning saying target .net framework is different.

in IDE, those type seems bound without an issue, and no errors are produced. it looks like compilation in workspace doesnt care or deal with different target framework correctly.

![image](https://cloud.githubusercontent.com/assets/1333179/8943820/9594cb4e-3531-11e5-9581-916444aa5eb6.png)

![image](https://cloud.githubusercontent.com/assets/1333179/8943853/d50b0612-3531-11e5-8c1f-f56e34430dda.png)

**Comment by Pilchie** [comment]
@heejaechang Can you still repro this?  I couldn't this morning.

**Comment by Pilchie** [comment]
Never mind, we *can* repro it.

**Comment by Pilchie** [comment]
(Note: Had to remove and re-add the P2P ref to repro - maybe the HintPath was wrong initially)

**Comment by heejaechang** [comment]
I looked a bit. it looks like those (target framework mismatch) reference dlls are not given to main compilation in command line build, but those are given for (p2p reference) IDE.

the reason errors from build don't show up in error list is that, the errors reported are something live diagnostic can produce so we ignore those errors from build for opened files assuming it must be already reported by live diagnostic.

current error list behavior is hard to fix in current design since it broke the very basic assumption that all diagnostics that are produced from build can be produced from live analysis (compiler errors) except some specific errors (ex, emit errors) which are explicitly marked as no-live errors.

in this case, build and IDE return completely different set of errors since reference dlls are different.

**Comment by SLaks** [comment]
This also happens for metadata references.
I had a project targeting framework 4.5.2 with a reference to EditorFeatures.Text, and MSBuild failed with errors like "Couldn't find `GetWorkspace()`", but the VS errors window had no errors.

Should I file a separate issue?

**Comment by jasonmalinowski** [comment]
@Pilchie Want to move this over to project-system, or just kill it for good?

**Comment by Pilchie** [comment]
This issue was moved to dotnet/project-system#3168
