### ISSUE TITLE
Revisit project state comparison in EnqueueProjectConfigurationChangeWorkItemAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#41804]
[EnqueueProjectConfigurationChangeWorkItemAsync](https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.cs#L561) compares part of the project state and triggers `ProjectConfigurationChanged` event if some of the project properties differ. It's not clear what properties should be checked here.

@heejaechang's comment:
> when solution crawler first added, it only cared properties that will affect semantic of compilation
    such as metadata references, compilation options and etc
    but as time go by, people wanted some extra thing such as option changes (since it cause analyzer result to be changed) and more.
    some like output file path and etc go added since test explorer needed to rerun thier analyzer when those are changed even if it doesn't affect semantic
    you can make it to re-analyze if project state is changed (anything under project is changed)
    but, it is expansive to reanalyze (since it is re-analyze not only the project but all project that depends on this project transitively)

Since we area already comparing most of the project state it seems that comparing all of it would not be significantly more expensive. 

Besides, we should see if it is actually necessary to re-analyze the projects that depend on the project whose properties changed. Technically, change in properties may change the public surface, which could be visible from another project and cause change in analysis results. Seems like a very rare corner case.

**Comment by tmat** [comment]
FYI @sharwell

**Comment by CyrusNajmabadi** [comment]
Solution crawler was removed.
