### ISSUE TITLE
Add Parameter - Simplify IChangeSignatureOptionsService.GetChangeSignatureOptions

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#41816]

**Comment by dpoeschl** [comment]
https://github.com/dotnet/roslyn/pull/38748/files/98a24127cfc8aecc90d2063559e54193fa6b5f3f#r377955570

**Comment by jasonmalinowski** [comment]
@dpoeschl The simplification here is to get rid of the document/insertPosition parameters that get passed around and just figure those out later when needed?

**Comment by CyrusNajmabadi** [comment]
CLosing out as speculative.
