### ISSUE TITLE
ITypeSymbol.IsTupleType returns a different value for non-generic System.ValueTuple from C# and VB

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#41821]
For the non-generic `System.ValueTuple`, `ITypeSymbol.IsTupleType` returns `true` from the symbol in a C# compilation and `False` for the symbol in a VB compilation

**Comment by cston** [comment]
cc @jcouv

**Comment by jcouv** [comment]
Yes, this is known. The refactoring work was done for C#, but not for VB. The VB work is tracked by https://github.com/dotnet/roslyn/issues/20648

**Comment by gafter** [comment]
Closing as a dup of https://github.com/dotnet/roslyn/issues/20648
