### ISSUE TITLE
[Breaking change] New public abstract API added to a shipped public type AnalyzerConfigOptions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#41823]
Following API was recently added to `AnalyzerConfigOptions`:
https://github.com/dotnet/roslyn/blob/b92b63b9a8f5ba3d942dfc60da6a87cb80106693/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerConfigOptions.cs#L26-L29

This breaks the existing CodeStyle nuget packages on latest Roslyn bits, which has a type `CompilerAnalyzerConfigOptions` which is a sub-type of `AnalyzerConfigOptions`:

```
// error AD0001: Analyzer 'Microsoft.CodeAnalysis.CodeStyle.CSharpFormattingAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Method 'get_Keys' in type 'Microsoft.CodeAnalysis.CompilerAnalyzerConfigOptions' from assembly 'Microsoft.CodeAnalysis.CodeStyle, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.'.
    Exception occurred with following context:
    Compilation: TestProject
    SyntaxTree: Test0.cs
```

We should probably convert this into a virtual API.

**Comment by mavasani** [comment]
Tagging @JoeRobich @jasonmalinowski @agocke

**Comment by mavasani** [comment]
I think we should do the following:

1. Revert the new public API and attempt to work around in the IDE layer, with possibly a temporary workaround (@JoeRobich is this possible)?
2. Create an API proposal and present it to the compiler design team for review.

We might end up shipping this as an intentional breaking change, given `AnalyzerConfigOptions` is a pretty new public API that is likely not used that commonly. Even then, it seems reasonable to go the route of reverting the API, getting compiler and compat team's approval and then go ahead with the change.

**Comment by JoeRobich** [comment]
> * Revert the new public API and attempt to work around in the IDE layer, with possibly a temporary workaround (@JoeRobich is this possible)?
> * Create an API proposal and present it to the compiler design team for review.

1. Reverted in https://github.com/dotnet/roslyn/issues/41823
2. Proposal in https://github.com/dotnet/roslyn/issues/41840

**Comment by mavasani** [comment]
Closing this issue as the breaking change has been reverted. Proposal is tracked in separate issue.
