### ISSUE TITLE
Searching for a type or method in solution explorer shows multiple references

### ISSUE THREAD

**Issue by Anipik** [dotnet/roslyn#41836]
![multipleReferences](https://user-images.githubusercontent.com/10516582/74968810-4e4a0c00-53d0-11ea-8c02-4f8f40c8734e.jpg)

It should just show one entry for the targetFramework we are compiling for, not for all the targetFrameworks. as it will become confusing for projects with 3-4 tfms.

cc @ericstj @davkean @safern @ViktorHofer

**Comment by davkean** [comment]
Moving to Roslyn, they own this.

**Comment by CyrusNajmabadi** [comment]
I don't repro this, i only get one hit, despite these symbols being in multiple TFMs:

![image](https://user-images.githubusercontent.com/4564579/221729782-9d60942a-a6aa-4e31-ab4a-4059ae7570fa.png)
