### ISSUE TITLE
We no longer show possible available namespaces in VB references properties page

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4183]
Filed on behalf of https://social.msdn.microsoft.com/profile/lmkz/.

VS2013 used to show all possible available namespace in the VB references properties page. VS 2015/Roslyn only shows the actual ones you've checked/project-level imported.

VS2013:
![image](https://cloud.githubusercontent.com/assets/1103906/8944741/30846c04-3537-11e5-8aa9-e365c8a4b18d.png)

VS2015:
![image](https://cloud.githubusercontent.com/assets/1103906/8944627/96e99a7e-3536-11e5-93c5-ba1e49240982.png)

**Comment by jasonmalinowski** [comment]
For those following along, the core fix for this change was in other parts of Visual Studio that aren't open source. Pull request #5024 is a fix needed to make all those other changes work well.

**Comment by jasonmalinowski** [comment]
All the parts are now merged, so closing the issue.
