### ISSUE TITLE
Need API for enumerating AnalyzerConfigOptions

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#41840]
Since the naming style rules are not tied to a set of known editorconfig options, The `NamingStylePreferenceEditorConfigStorageLocation` expects to be able to enumerate through the keys of the options to deserialize the preference. The `AnalyzerConfigOptions` API does not provide a way to perform this enumeration.

My proposal is that we add getter for accessing the Keys as an `IEnumerable<string>`

```csharp
public abstract class AnalyzerConfigOptions
{
    ...
    /// <summary>
    /// Enumerates keys of all available options in no specific order.
    /// </summary>
    /// <exception cref="NotImplementedException">Not implemented by the derived type.</exception>
    public virtual IEnumerable<string> Keys
         => throw new NotImplementedException();
    ...
}
```

The property is virtual to avoid a breaking change.

**Comment by tmat** [comment]
Since AnalyzerConfigOptions is public API we can't add a new abstract method. We can add:

```C#
public virtual bool TryGetKeys(out IEnumerable<string> keys) { keys = null; return false; }
```
