### ISSUE TITLE
Text editor project selection always resets in shared source files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41874]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/673732/text-editor-project-selection-always-resets-in-sha.html)._

---
<p>VS 2019 16.3.0 Preview 1 - VS 2019 16.5.0 Preview 2 (still current)</p><p>There are <em>several</em> issues when working with shared source files.</p><p><strong>Text editor project selection always resets in shared source files</strong></p><p>The project selection in the text editor (top left combobox) always resets to the last project selectable as soon as the text area is clicked. Project specific code grayed out due to different <code>DefineConstants</code> in them is not updated at all.</p><p>The problem can be reproduced with the following 3 example projects, which are also attached:</p><ul><li><strong>Sample.Shared</strong> - A shared source project.<br>
It has files with <code>#if LIB_APPLE</code> or <code>#if LIB_BANANA</code> preprocessor directions to provide slightly differing source for the following two libraries:</li><li><strong>Sample.Apple</strong> - defines <code>LIB_APPLE</code> and has reference to the shared project.</li><li><strong>Sample.Banana</strong> - defines  <code>LIB_BANANA</code> and has reference to the shared project.</li></ul><p><strong>Sample.Shared</strong> has the following source file which, for demonstration purposes, defines 3 fruit ripe states:</p>
<pre>namespace Sample.Shared
{
    public enum States
    {
        Green,
        Yellow,
#if LIB_APPLE
        Red
#endif
    }
}
</pre><p>If you open this file in the VS text editor, the top 3 combo boxes allow selection of project (<code>Sample.Apple</code> or <code>Sample.Banana</code>), the current scope and the current member.<br>
As stated in the introduction, the first combobox allows you to select another project (e.g. <code>Sample.Apple</code>) but it always skips back to the last one (e.g. <code>Sample.Banana</code>) when clicking into the text editor. In this case, the <code>Red</code> ripe state is never un-grayed as the selection of <code>Sample.Apple</code> does not even seem to take effect.</p><p>It would be expected that it sticks to the combo box selection and properly reflects the changes in the code file, but it does not.</p><p><strong>&quot;Sync with Active Document&quot; broken for shared source files</strong></p><p>Clicking the Solution Explorer &quot;Sync with Active Document&quot; toolbar button does not actually focus a currently open source file in a shared source project, but instead tries to move to that file in projects <em>referencing</em> the shared source project (in fact the project currently selected in the text editor project selection, which is broken too due to the above). It eventually highlights a completely irrelevant file or folder as it tries to follow the wrong project as far as possibile.</p>

---
#### Visual Studio Feedback System on 8/5/2019, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 10:56 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Ray Koopa on 8/12/2019, 02:05 AM: 

Thank you for the update. I'm checking this issue daily as it is killing my shared projects workflow, together with my other reported shared project issue. :-)
#### Toby Herring on 9/18/2019, 06:56 AM: 

<p>This is broken in 16.2.5, also.  I wanted to bump this so it doesn't get closed as stale, and also see if there are any status updates.</p><p>In my case I have a multi-target code library and two unit test libraries that are sharing code (because R# won't run both sets of tests in the UI with a multi-target test library.)  But I get the same results as the OP in the sample project, whenever I try to switch parent projects to change the framework/defined constants, it flips back when I click off the dropdown.</p>

#### Mark Alicz on 10/7/2019, 07:56 AM: 

<p>This is still a MAJOR issue for me as well.  The only way I am able to get it to work is to create a bug for a specific platform and then try and compile.  Clicking the error brings me into the current project correctly.  Very, Very, Annoying.  Please someone address this ASAP!!</p>

#### Ray Koopa on 12/7/2019, 05:53 AM: 

Just wanting to state the issue is still as current as it is annoying in VS 16.5 Preview 1 :o)
#### Ray Koopa on 2/8/2020, 04:04 AM: 

Is there any update on this issue? Working with shared source projects is still a wreck in VS2019 16.5 Preview 2.<br>Basically most operations needing shared source file paths are broken. The &quot;Sync with Active Document&quot; also cannot jump to an active open shared source document in the Solution Explorer,<br>It is very easy to reproduce, so I do not know why there has been no update on this. If it is low priority, you should no longer recommend people to use shared source projects as they&#39;re a mess :(
#### Mark Alicz on 2/8/2020, 10:42 AM: 

<p>Seriously a response would be nice.  This has forces us to reconsider our entire structure.  Which is a shame since it should be a relatively easy bug to fix....  </p>

#### Ray Koopa on 2/8/2020, 10:44 AM: 

<p>Maybe it gets more traction if you cast an upvote to the issue. I'm still surprised there don't seem to be many other people having stumbled over these issues, seeing the score is still 0.</p>

#### Ray Koopa on 2/19/2020, 00:39 PM: 

This seems to be fixed in VS 16.5 Preview 3!
#### Ray Koopa on 2/19/2020, 03:31 PM: 

But the Solution Explorer Active Document sync bug still exists.

---
### Original Solutions
(no solutions)

**Comment by weitzhandler** [comment]
Same here. 
This issue has been there forever. So annoying.

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this on 17.13.0 Preview 1.0
