### ISSUE TITLE
Ask for "Derived types" from contextual menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41875]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/924050/ask-for-derived-types-from-contextual-menu.html)._

---

![image](https://user-images.githubusercontent.com/1408396/75384871-8c917080-5893-11ea-9628-ee5fc56545a4.png)

<p>Hi,<br>
I think it would be nice to launch the search for derived types from the right click on a class/interface name of an open file. Now there’s “Go To Base” menu item, but I would like to see also something like “Show Derived Types”.<br>
The resulting derived types could be listed as now in the Solution Explorer or in a proper window as for “Go To Base” results.<br>
I just want to reduce the steps to find the derived types with a right-click on the base class.</p><p>Thank you<br>
Regards</p>

---
#### Marco Suardi on 2/20/2020, 08:59 AM: 

<p>Nice feature</p>

#### Visual Studio Feedback System on 2/21/2020, 02:54 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
The **Go To Implementation** does exactly this 👍
