### ISSUE TITLE
IntelliSense should take into account DescriptionAttribute if there is no XML documentation on a code element.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41876]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/923414/intellisense-should-take-into-account-descriptiona.html)._

---
Let's say I have this property.

```
[Description("The footer for the assessment report.")]
public string Footer { get; set; }
```

If I want IntelliSense to give me the description text as a tooltip, I have to duplicate it as an XML comment:

```
///<summary>The footer for the assessment report.</summary>
[Description("The footer for the assessment report.")]
public string Footer { get; set; }
```

This is of course less than ideal... why not use the DescriptionAttribute if no XML documentation exists?

---
#### Visual Studio Feedback System on 2/19/2020, 04:51 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We have no plan to do this.  Xml doc comments are the appropriate way to document code.
