### ISSUE TITLE
Visual enhancement about nano generation operation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41885]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/920493/visual-enhancement-about-nano-generation-operation.html)._

---
Why should I make this suggestion?
This the story: https://developercommunity.visualstudio.com/content/problem/919084/c-reference-failure-but-no-error.html
When the 生成操作(generation operation) is nano. It will lost many IDE function for a code file.
And If you dont know or forgot this, you will spend a long time to find out why my IDE is not working in right way.
First the has reference assembly's types and words must be showed in the 完成列表(Completion list). But this maybe isn't easy to archieve, and can't warn people what the files's generation operation status it is. So remove all the item in the completion list is better. Don't remain a half and remove a half, it's confusing.
So I suggest that when the file is in the view and it generation operation is nano, the top on the code windows can show a red bar with text "The generation operation is nano.". Or change it title or background color is another good choose.
In a word, I hope the UI can show the user what the generation it is, in especial nano.

---
#### Visual Studio Feedback System on 2/19/2020, 04:58 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
@Therzok we're having trouble making sense of this request. Does this ring a bell for you?
