### ISSUE TITLE
How to specify langversion from csi

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#41893]
Is there any way to enable it or it's deliberately unsupported?

Ideally we should only write `csi /langversion:preview` to enable preview features.

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by alrz** [comment]
@tmat I wonder if this doesn't need much work, if so can you give me a pointer on the required change?

**Comment by tmat** [comment]
@alrz I think you just need to move http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,918 to http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,184
