### ISSUE TITLE
Roslyn build/projects should not attempt to install/uninstall extensions by default

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4189]
The Roslyn build attempts to install/uninstall extensions by default, resulting in the following both in the IDE build and command-line build:
```
Error		There was a problem uninstalling the extension with a VSIX identifier of "0b5e8ddb-f12d-4131-a71d-77acc26a798f". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Language Services.	VisualStudioSetup		
Error		There was a problem uninstalling the extension with a VSIX identifier of "21BAC26D-2935-4D0D-A282-AD647E2592B5". You need to use the Programs and Features pane in the Windows Control Panel to remove Roslyn Expression Evaluators.	ExpressionEvaluatorPackage		
Error		There was a problem uninstalling the extension with a VSIX identifier of "1F42C6D0-F876-4AF0-8185-1BEB0A325BB2". You need to use the Programs and Features pane in the Windows Control Panel to remove VisualStudio Interactive Components.	VisualStudioInteractiveWindow	
```	
This doesn't work for those are not using the internal tools for updating the product and should be off by default, and turned on for internal use.

**Comment by davkean** [comment]
This also blocks running on tests as called out on https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging

**Comment by tmat** [comment]
@davkean Can we not install the VSIXes at all while building? It would be much better if we had a separate "deploy" build task that is only run in F5 scenario from VS or when explicitly enabled on command line thru msbuild parameter.

**Comment by jasonmalinowski** [comment]
@tmat: indeed, that would be a much better design. The SDK team though would own such a task; I don't think there's any real way for us to build that without their help.

**Comment by davkean** [comment]
Awesome!
