### ISSUE TITLE
CSharpCompilationOptions - nostdlib & noconfig

### ISSUE THREAD

**Issue by Theoistic** [dotnet/roslyn#41904]
I cant invoke "csc /target:library -out:{buildOutput}{project.Name}.dll /noconfig /nostdlib /r:$WASM_SDK/wasm-bcl/wasm/mscorlib.dll"

using roslyn's CSharpCompilationOptions, it seems that /nostdlib is unavailable within the CompilationOptions.

in the attempt to precompile the library before mono-wasm packaging, since mono, includes its own facades of objects and types, i should be able to compile using roslyn with the provided mono libraries.

is it the aim to provide CompilationOptions with mapped properties to the csc options?

**Comment by svick** [comment]
As far as I can tell, what `/nostdlib` does is that it prevents the automatic inclusion of mscorlib.dll in the compilation's metadata references:

https://github.com/dotnet/roslyn/blob/ca1a68cd5edd5727ec27b584b4dd72f782923aa3/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L1322-L1325

If you're creating the compilation yourself, it means you're also in control of the metadata references, which means you shouldn't need `/nostdlib`.
