### ISSUE TITLE
C# 'var' colored incorrectly when it is a variable name and passed to out parameter

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#4190]
Paste the following code into a C# class body

```
    public void M(out object arg)
    {
        arg = null;
    }

    void Test()
    {
        object var = null;
        M(out var);
    }
```

**Expected**:
"var" in "M(out var)" is colored as a local variable. Regression from VS 2013.

**Actual**:
It is colored as a keyword.

**Comment by Pilchie** [comment]
Assigning to you, since you have a PR out for it.
