### ISSUE TITLE
The "Introduce constant" refactoring can conflict with type names

### ISSUE THREAD

**Issue by Erarndt** [dotnet/roslyn#41911]
**Version Used**: 
VS 16.4.5
.NET Core 3.1

**Steps to Reproduce**:

Consider this code snippet

![image](https://user-images.githubusercontent.com/60519722/75191256-d1d46780-5706-11ea-948c-25630cf5c360.png)

If I introduce a constant for `"C:\SomePath"`, `Path` is chosen as the name for the constant. This conflicts with `Path` in the static call to `GetFullPath()`. I'm then in an inline rename where the name of the type is included.

![image](https://user-images.githubusercontent.com/60519722/75191192-ba957a00-5706-11ea-800a-c95b8509c037.png)

**Expected Behavior**:
Introducing a constant will not cause name conflicts.

**Actual Behavior**:
Introducing a constant conflicts with a type name.

**Comment by Sliptory** [comment]
It seemed to me that it was impossible to name variables in the same way as classes. 🤔

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
