### ISSUE TITLE
[loc][Query][Roslyn] Localizability of  0; "WRN_ParameterConditionallyDisallowsNull"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#41929]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Parameter '{0}' may not have a null value when exiting with '{1}'.

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
Please specify the meaning of the placeholders.

What's the correct meaning?

1) The parameter can't have a null value
2) It's possible that the parameter has a null value

0; "WRN_ParameterConditionallyDisallowsNull"
0; "WRN_ParameterConditionallyDisallowsNull_Title"

**Comment by sharwell** [comment]
@jcouv I believe you added this one?

**Comment by jcouv** [comment]
Here's an example:

```
bool M([NotNullWhen(true)] out string? p)
{
  p = null;
  return true; // Parameter 'p' may not have a null value when exiting with 'true'.
}
```
