### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "WRN_ShouldNotReturn"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#41930]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
A method marked [DoesNotReturn] should not return.

File Name:
Compilers\CSharp\Portable\xlf\CSharpResources.xlf

==========================================
Query:
Does "return" mean "return a value" in this context?

0; "WRN_ShouldNotReturn"
0; "WRN_ShouldNotReturn_Title"

**Comment by YairHalberstadt** [comment]
Return means it should not exit the method normally.

In a non-void method that would be return a value.
In a void method that would mean either it has an explicit reachable return statement, or the end of the method is reachable.

For example these would trigger the error:

```csharp
[DoesNotReturn]
void M(){}

[DoesNotReturn]
void M(){ return; }

[DoesNotReturn]
int M(){ return 5; }
```

But this wouldn't:

```csharp
[DoesNotReturn]
void M() { throw new Exception(); }
```
