### ISSUE TITLE
Rename Roslyn.InteractiveEditorFeatures.dll to ....

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#4195]
Microsoft.CodeAnalysis.InteractiveEditorFeatures.dll

**Comment by KevinH-MS** [comment]
Verified fixed

**Comment by tmat** [comment]
I though we are going to merge this into EditorFeatures

**Comment by KevinH-MS** [comment]
@tmat I don't have plans to do this in the near term.  Are there benefits (besides fewer dlls)?

**Comment by tmat** [comment]
Fewer dlls is good enough reason.
