### ISSUE TITLE
Use MemberNotNull when available

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#41964]
This issue is being used to track places in our code base which can benefit from `MemberNotNull` when it's available in the language and toolset. Both methods which could be annotated with it and uses of `!` that could be removed when it's present should be tagged with this issue.

**Comment by jasonmalinowski** [comment]
Would some sort of "remove !s if MemberNotNull" tool (even if it's a one-off that we don't check in since this may violate "spirit of nullability) be useful?

**Comment by jaredpar** [comment]
@jasonmalinowski yes. I think a more general remove `!` because it's unnecessary tool would also be useful. I believe @sharwell recommended that at some point but my memory is fuzzy and I can't find a reference to it.

**Comment by jasonmalinowski** [comment]
We're tracking that at #34714.
