### ISSUE TITLE
params argument not passed correctly to invoked method when combined with optional argument

### ISSUE THREAD

**Issue by gertjanstulp** [dotnet/roslyn#4197]
When I compile code that uses a combination of optional arguments and the 'params' keyword in one single method an error occurs at runtime. I wrote the following testapp to reproduce the error:

```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        var testClass = new TestClass { Id = 3 };
        // Optional argument first, params argument second: the assert succeeds
        TestMethod(optionalArg: "optionalvalue", args1: testClass.Id);
        // params argument first, optional argument second: the assert fails
        TestMethod(args1: testClass.Id, optionalArg: "optionalvalue");
    }

    public static void TestMethod(string optionalArg = "", params object[] args1)
    {
        Trace.Assert(args1[0] != null);
    }
}

class TestClass
{
    public int Id { get; set; }
}


```

As mentioned in the code-comments, the invocation of the testmethod  fails on the assert when I first specify the params value and then the optional argument. I used ILSpy to decompile the compiled exe and got the following code in the Main method:
 
```c#
private static void Main(string[] args)
{
	TestClass testClass = new TestClass
    {   
        Id = 3
    };
    Program.TestMethod("optionalvalue", new object[]
    {
        testClass.Id
    });
    object obj;
    Program.TestMethod("optionalvalue", new object[]
    {
        obj
    });
    Console.ReadKey();
}
```

As seen in the decompiled code there is another ```obj``` variable declared which is used for the second invocation. This causes the Assert to fail as the ```obj``` variable has no value assigned to it. The issue only occures when TestMethod is invoked with ```testClass.Id```. When I invoke it with a constant value like this: 
```c#
TestMethod(args1: 3, optionalArg: "optionalvalue")
``` 
the assert succeeds.

I tested this with different setups:
- In Debug and Release Mode
- Against .Net 4.5.1, 4.5.2 and 4.6
- Compiled from VS2015 and from the commandline using csc.exe
- On two different machines

Each test resulted in a failing assert on the second invocation. When the code is compiled with the VS2013 compiler the issue does not occur.

**Comment by maliger** [comment]
I got very simmilar issue with params and named parameters, but not optional one.

        class MyClass
        {
            public int x;
            public MyClass(int x)
            {
                this.x = x;
            }
        }
        static int M1(string a, bool b, params MyClass[] c)
        {
            return c[0].x;
        }
        static void Main(string[] args)
        {
            int x = M1(a: "as", c: new MyClass(42), b: true);
            Console.WriteLine(x.ToString());
        }
