### ISSUE TITLE
IDE0004 "Cast is redundant" in switch expression

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [dotnet/roslyn#41985]
**Version Used**: 
<details>
Microsoft Visual Studio Community 2019
Version 16.4.5
VisualStudio.16.Release/16.4.5+29806.167
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

Automatic Versions   2.0.48
Provides tools for managing assembly versions.

Azure App Service Tools v3.0.0   16.4.460.23317
Azure App Service Tools v3.0.0

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.4.19310.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.3.3   Build 193.0.20200215.145801
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.4.19310.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - IronPython support   16.4.19310.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.4.19310.1
Profiling support for Python projects.

TermWindow Extension   1.0
TermWindow Visual Studio Extension Detailed Info

Visual Basic Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
</details>

**Steps to Reproduce**:

The following code is intended to preserve types of each case result, so `object x` can later be type-matched (i.e. `x is int`, `x is float`, `x is double`).

```csharp
var str = "case_1";

object x = str switch
{
    "case_2" => (object)1.3f,
    "case_1" => (object)5,
     _ => (object)25.0d
};
```
**Expected Behavior**:
No IDE suggestion is displayed.

**Actual Behavior**:

All three `(object)` casts are marked as `IDE0004` "Cast is redundant". You can see it greyed out in the screenshot.
![image](https://user-images.githubusercontent.com/8782986/75437920-ad26fc80-595f-11ea-9c8e-5dc1d683f73b.png)

With `(object)` boxing present, the return type of the `switch` expression is `object`. Without it, the return type is a common type for RHS values, which in this case is `double`.  

This snippet better illustrates the difference in `switch` expression returned types.

```csharp
var str = "case_1";

Console.WriteLine((str switch
            {
                "case_2" => 1.3f,
                "case_1" => 5,
                _ => 25.0d
            }).GetType());

Console.WriteLine((str switch
            {
                "case_2" => (object)1.3f,
                "case_1" => (object)5,
                _ => (object)25.0d
            }).GetType());
```

The outputs are:
```
System.Double
System.Int32
```

**Comment by YairHalberstadt** [comment]
Each individual cast is redundant, since you could remove any two of them and it would have the same result.

Once you remove two of the casts, the third cast will no longer trigger the suggestion.

**Comment by Ilia-Kosenkov** [comment]
@YairHalberstadt , Ok, makes sense, I did not check that case. While I would appreciate a more detailed message in the tooltip, not just "Redundant cast" in all cases (which can mislead some people, like myself), I guess there is no real issue here.

Thank you for clarification.

**Comment by YairHalberstadt** [comment]
> While I would appreciate a more detailed message in the tooltip, not just "Redundant cast" in all cases (which can mislead some people, like myself)

The problem is each diagnostic and suggestion is reported seperately.

There is no attempt to try and work out if a diagnostic would not be needed if another code fix was applied, since as you can imagine this is exponentially expensive in the number of code fixes.

Overall the current design is I think the simplest and most predictable.

**Comment by Ilia-Kosenkov** [comment]
@YairHalberstadt, I agree that it is the simplest solution, at least for now.
Thanks again. I am closing the issue.
