### ISSUE TITLE
"Make struct fields writable" needs to list the actual reason

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#41981]
I got the following with no indication as to "why". Needed to read the code of the thing to figure out why it was suggesting this: https://github.com/dotnet/roslyn/blob/c5f5bb705c5eafbc17126ccb6ab653bd0f15a71b/src/Features/CSharp/Portable/MakeStructFieldsWritable/CSharpMakeStructFieldsWritableDiagnosticAnalyzer.cs#L53. The struct assigns "this" outside constructor.

![image](https://user-images.githubusercontent.com/1103906/75422086-e5463380-598f-11ea-93ae-02a32fefec02.png)

**Comment by Sliptory** [comment]
I will take this task

**Comment by davkean** [comment]
Assigned it.

**Comment by Sliptory** [comment]
Is it possible to get a test structure, otherwise I just can’t reproduce this situation. Thanks :)

**Comment by davkean** [comment]
Something like the following should repro:

``` C#
public struct Foo
{
    public readonly int Foo;

    public void Method()
    {
        this = default;
    }
}
```

**Comment by Sliptory** [comment]
#42055 Add PR

**Comment by Sliptory** [comment]
#42099 add clean PR

**Comment by Sliptory** [comment]
![answerTask](https://user-images.githubusercontent.com/22915222/75756648-1339c800-5d42-11ea-9a34-9bf2e4d3700c.jpg)
