### ISSUE TITLE
MetadataAsSource doesn't regenerate files after formatting change

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#4206]
1. Create a new console app.
2. Go to definition on string.
3. Close the generated definition.
4. Change your indenting options to some other indenting (but not tabs being wary of #4019)
5. Go to definition on string again.

_Expected:_ the formatting is updated to your new settings
_Actual:_ the formatting is still using the previous settings

**Comment by CyrusNajmabadi** [comment]
Need info if this is actually a problem for users.  Given how rarely formatting optinos even change, i highly doubt it.
