### ISSUE TITLE
VB Intellisense for predicate includes Func(of ...)

### ISSUE THREAD

**Issue by lmkz** [dotnet/roslyn#4208]
In VS <= 2013, when entering an argument of type Func(of ...) in a function call, Func(of ...) was not shown in the intellisense popup. As such, typing "fu"+tab was usually enough to insert "function". Now Func(of ...) shows in the list, which is never required, and requires an extra keystroke to move to "function".

e.g. type the below in both 2013 and 2015 and observe difference in intellisense list shown:

enumerable.range(0, 10).select(fu

**Comment by jasonmalinowski** [comment]
Reactivating since per the discussion with @rchande and @DustinCampbell we think there's a better fix here.

**Comment by rchande** [comment]
@jasonmalinowski (chosen arbitrarily) please verify
