### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#42092]
@KitPatterson commented on [Thu Feb 27 2020](https://github.com/dotnet/docs/issues/17248)

What does this property mean? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d82018-baca-ba95-f165-1c8c5be8f45b
* Version Independent ID: 4451cff1-8f80-7350-2c09-7e44b9ee8039
* Content: [AdhocWorkspace.CanOpenDocuments Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.adhocworkspace.canopendocuments?view=roslyn-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/AdhocWorkspace.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/AdhocWorkspace.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@BillWagner commented on [Fri Feb 28 2020](https://github.com/dotnet/docs/issues/17248#issuecomment-592528158)

ping @jinujoseph 

Who should I route this toward?

---

@jinujoseph commented on [Fri Feb 28 2020](https://github.com/dotnet/docs/issues/17248#issuecomment-592758190)

Should be roslyn @jasonmalinowski  will you help doc this API

**Comment by jasonmalinowski** [comment]
@BillWagner @KitPatterson PR is out to add XML doc comments. Once that's merged I'm guessing the docs will get auto regenerated? Or do we have to do something else?
