### ISSUE TITLE
VS 16.5.0 Preview 3.0 - IDE0071WithoutSuggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42096]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/926637/vs-1650-preview-30-ide0071withoutsuggestion-1.html)._

---
My error list shows messages with a code of IDE0071WithoutSuggestion. Shouldn't the code be IDE0071? See attached screenshot.

---
#### Visual Studio Feedback System on 2/23/2020, 09:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fannie Wang [MSFT] on 2/25/2020, 01:05 AM: 

<p>Thank you for your feedback! Could you provide a sample project that can exhibit this behavior?</p>

#### bugreporter5367 on 2/28/2020, 08:07 AM: 

Opening the project is enough for me to see the error. No need to build. See attached screenshot.
#### bugreporter5367 on 2/25/2020, 09:03 AM: 

See attached sample project.<br><br>```
#### bugreporter5367 on 2/25/2020, 09:04 AM: 

See attached sample project.<br><br>```<br>using System;<br><br>namespace IDE0071WithoutSuggestion<br>{<br>    public static class Class<br>    {<br>        public static void M()<br>        {<br>            Console.WriteLine($&quot;{(new TimeSpan()).ToString()}&quot;);<br>        }<br>    }<br>}<br>```
#### Fannie Wang [MSFT] on 2/28/2020, 02:23 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/5345/8c9648eb-1a63-6b24-a66b-43ffcbbc2ad3.html" nodeid="5345">@bugreporter5367</a></p><p>How did you create the IDE0071 message?</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/120931-screenshot.png"></p>

#### Visual Studio Feedback System on 3/1/2020, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/2/2020, 10:26 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Does not reproduce on VS2022

![image](https://user-images.githubusercontent.com/10605811/148173703-cdd3fb56-6dc4-4cab-9510-e606d57585c8.png)
