### ISSUE TITLE
IDE0066 should not suggest for ref-returns (Convert switch statement to switch expression)

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#42130]
code to repro:

``` c#
class Foo
{
    int x, y, z; // yes, I know this could be a vector and "job done"
    private ref int GetField(int id)
    {
        switch (id)
        {
            case 0: return ref x;
            case 1: return ref y;
            case 2: return ref z;
            default: throw new ArgumentException(nameof(id));
        }
    }
}
```

IDE0066 suggests changing this to:

``` c#
    private ref int GetField(int id)
    {
        return id switch
        {
            0 => ref x,
            1 => ref y,
            2 => ref z,
            _ => throw new ArgumentException(nameof(id)),
        };
    }
```

which does not compile; you can add a missing `ref` to fix the CS8150 on the `return id switch` line (to `return ref id switch`), but you still get 3xCS1525+CS1073 on the individual cases.

**Comment by alrz** [comment]
I wonder if this should be just a language feature and continue to suggest the refactoring. This already works with conditionals.

**Comment by mgravell** [comment]
@alrz agreed, "it suggests it, and the refactored code compiles and works" would also be a fine outcome :)

**Comment by CyrusNajmabadi** [comment]
@gafter do we have any language feature championed to make ref-switches a thing?  I couldn't find any.

**Comment by gafter** [comment]
No.

**Comment by alrz** [comment]
Isn't this already fixed in https://github.com/dotnet/roslyn/pull/40236?

**Comment by alrz** [comment]
cc @CyrusNajmabadi to verify.

**Comment by CyrusNajmabadi** [comment]
Yup.  Fixed with https://github.com/dotnet/roslyn/pull/40236.
