### ISSUE TITLE
IDE reports a lot of unexpected errors (build actually succeeds) and features like Go To Definition do not work (likely due to the errors).

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#42138]
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.6.0 Preview 1.0 [29826.224.master]

Open Roslyn solution, and build C# compiler, the build succeeds. However, there are a lot of errors in the Error List and red squiggles all over the code (possibly only around types that are defined in Microsoft.CodeAnalysis.dll):
![image](https://user-images.githubusercontent.com/10522107/75808365-d36fe200-5d3b-11ea-839f-e3181fb8cd86.png)

![image](https://user-images.githubusercontent.com/10522107/75808851-9d7f2d80-5d3c-11ea-8174-c5e22b2a9efd.png)

**Comment by AlekseyTs** [comment]
CC @jinujoseph, @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
This is a known dogfood issue with that build, upgrade to the latest builds.
