### ISSUE TITLE
Package Manager Console Depends on Solution Start-up Project

### ISSUE THREAD

**Issue by BrianBu01** [dotnet/roslyn#42137]
**Version Used**: 

VS Professional 2019 v 16.4.5

**Steps to Reproduce**:

1. Select a start up project
2. In Package Manager Console, select a default project different from startup
3. Run a command that depends on building of projects or even code with in such as Scaffold-DbContext.

**Expected Behavior**:

The command runs in context of the default project

**Actual Behavior**:

The command run on the default project but in the context of the start-up project
**Notes**

Not really sure that this is a bug, but it is a confusing coupling between two different concepts.

**Comment by jinujoseph** [comment]
Triage reroute : @davkean is this project system or nuget packge team

**Comment by BrianBu01** [comment]
@davkean Do you have a reference to the ticket in project system or nuget package team?

**Comment by davkean** [comment]
This is not project system, and I'm not aware of how this is supposed to work.

**Comment by BrianBu01** [comment]
@jinujoseph maybe you have a suggestion.

I'd assume Package Manager commands should run in the context of the default project not the startup project would be a solution.

**Comment by davkean** [comment]
@BrianBu01 

http://github.com/nuget/home would be a better place for this issue, I'd move it but we cannot move across organizations.

**Comment by jinujoseph** [comment]
cc @nkolev92 to take a look

**Comment by BrianBu01** [comment]
@davkean I'm confused.  How does Nuget itself have anything to do with the Package Manager in Visual Studio and the context of the solution's startup project?

It's really an integration issue.

**Comment by davkean** [comment]
The Package Manager is owned and lives in https://github.com/NuGet/NuGet.Client and bugs are tracked at https://github.com/NuGet/home.

**Comment by nkolev92** [comment]
I can move the issue, but I don't have permissions to close this one.

**Comment by jinujoseph** [comment]
I can close this once you have a tracking issue your end @nkolev92

**Comment by BrianBu01** [comment]
@nkolev92 can you please provide the new issue, so I can follow it?

**Comment by nkolev92** [comment]
@BrianBu01, the tool I use links it, https://github.com/NuGet/Home/issues/9880. 

This can nwo be closed. 
Thanks @jinujoseph
