### ISSUE TITLE
Need an IDE level API that matches arguments to parameters

### ISSUE THREAD

**Issue by y87feng** [dotnet/roslyn#42149]
Is it possible to have an IDE level API that matches arguments to parameters? Just like Overload Resolution at the compiler level. I did this myself in my code but looks risky and hard to maintain. It would be much better if we could have an API for it.

Here is the link to my code:
https://github.com/dotnet/roslyn/pull/41371#discussion_r383579195

**Comment by y87feng** [comment]
@333fred @gafter

**Comment by 333fred** [comment]
@gafter the basic idea here is to expose some type of overload resolution method on a Compilation. Given a set of argument syntaxes and a set of candidate symbols, choose the one that best matches the candidates, or none if none do. The IDE could potentially implement this themselves, but the likelyhood is that some edge case would be wrong or that we'd introduce something new and the IDE wouldn't know to catch up.

**Comment by y87feng** [comment]
> @gafter the basic idea here is to expose some type of overload resolution method on a Compilation. Given a set of argument syntaxes and a set of candidate symbols, choose the one that best matches the candidates, or none if none do. The IDE could potentially implement this themselves, but the likelyhood is that some edge case would be wrong or that we'd introduce something new and the IDE wouldn't know to catch up.

Yup, actually maybe overload resolution analysis result(e.g. BadArgument) is closer to what I need in this case. Code fixer can analyze code based on the result, and there might be multiple candidates that can fit into the code fix.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal.  in general, the reason we don't just make things public is because it increases maintenance costs and locks down our ability to change things in teh future.  We can open things up, but we have a process that requests need to go through to make sure the appropriate people weigh in and the right API shape is determined and shipped.
