### ISSUE TITLE
Behavior of Visual Studio on Diagnostic with severity Error

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/roslyn#4214]
When running FxCop created a build error because of a violation an option was given to suppress this error using a suppressmessage (or a pragma but that's beyond the scope of this issue).

With Roslyn and the diagnosticanalyzers, an error cannot be suppressed from within visual studio. For a warning this is possible as a 'code fix'. 

What's the idea/decision behind this change? And what is the supposed upgrade path?

![image](https://cloud.githubusercontent.com/assets/4130108/8971623/f572063c-3606-11e5-8309-e22a9b2c884b.png)

Finally, adding the suppressmessage attribute by hand will work even on errors. So if you apply the 'code fix' for a warning to an error, it will still be ignored.

**Comment by srivatsn** [comment]
Yes this is just a not yet implemented feature for roslyn issues. We'll use #4265 to track the work.
