### ISSUE TITLE
AnalyzerConfigSet can return wrong set of Options

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#42154]
While moving dotnet format to the compiler's .editorconfig support our tests hit on an unlikely bug.

AnalyzerConfigSet caches options previously returned based on a key of matched section names. This can return invalid results when there are multiple levels of .editorconfig.

If a file matches sections from the top most .editorconfig and **is not** with or beneath the folder containing the lower .editorconfig, then it's options will be cached by the section names from the top most. If another file matches the sections from the top most .editorconfig and **is** with or beneath the folder containing the lower .editorconfig but fails to match any additional sections, despite the lower .editorconfig being a root .editorconfig the options stored from the previously processed file will be returned.

I believe that the FilePaths of the applicable .editorconfigs should be incorporated into the key used for caching.

**Comment by JoeRobich** [comment]
Thanks @sharwell, This was resolved with https://github.com/dotnet/roslyn/commit/8fea41a41e2fc3c91e1eb775f4de265f7a19b58e

**Comment by agocke** [comment]
Nice, thanks!
