### ISSUE TITLE
Public API analyzer only works in Roslyn.sln if the API file is opened in the editor

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#42168]
**Version Used**: Latest 16.6 dogfood build

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Open any file, say `Workspace.cs` and add a new public API. You should see RS0016 error.
3. Ctrl + Dot to see that public code fix is shown and the preview also shows the correct change
4. Hit enter to attempt to apply the fix

**Expected Behavior**:
Unshipped public API file is changed

**Actual Behavior**:
Unshipped public API file is not changed. If you repeat the above steps with the public API already open in the editor, code fix does work. NOTE: I am unable to repro this behavior with couple other solutions I tried, but it does repro consistently on Roslyn.sln on both my machines.

I debugged this a bit, and it finally comes down the below code: https://github.com/dotnet/roslyn/blob/abd2fb03cfcdc363cc757958a0721ea505e49e95/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs#L1154-L1167

It seems something from the InvisibleEditor code path is causing the scenario to fail, I don't see any exceptions - just the file change does not seem to get saved to disk. I am not sure which component or API does the actual write to disk in invisible editor code path.

**Comment by mavasani** [comment]
Tagging @jasonmalinowski, in case your upcoming PR is fixing anything on this code path.

**Comment by jasonmalinowski** [comment]
@mavasani I guess the changes I had in mind were the ones in https://github.com/dotnet/roslyn/pull/41969/commits/99dc6804885f276e9f79b5b3d4ddf801e74cf7a7 which I guess isn't in that path. Hmm.

**Comment by sharwell** [comment]
This is caused by dotnet/project-system#2160 (failure of the SDK to add `AdditionalFiles` to `AvailableItemName`). I implemented a workaround for dotnet/roslyn in #42521.
