### ISSUE TITLE
Support analyzers that are disabled by default in command line build but enabled in other hosts

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#42166]
### Current state
Today, every analyzer that is installed via NuGet package and marked as enabled by default runs in both command line build and IDE, regardless of the analyzer severity. This is completely reasonable as almost all the analyzers are designed to be warnings by default that can break build. Users have to explicitly install the analyzer NuGet package, so any command line build impact happens as part of user action of installing the analyzer.

### Feature request
We are planning to include .NET5 analyzers and possibly even IDE code style analyzers in the .NET SDK (see [this](https://github.com/dotnet/roslyn/issues/38480#issuecomment-578903218) proposed experience for code style analyzers for details). Only a small selected set of analyzers from the .NET analyzers package can be enabled by default as warnings, and all the code style ones have to be suggestions or hidden. To improve discoverability of analyzers in .NET5 analyzers package and supporting IDE code style suggestions, it is imperative that we support analyzers/descriptors to mark themselves as being disabled by default in command line build, which get enabled by explicit user configuration via .editorconfig. This ensure we can keep delivering value to customers with new analyzers lighting up in IDE as suggestions, without impacting command line build by default to prevent any functional compat or performance issues.

### Proposal
I can think of two potential approaches for implementing this feature in the analyzer driver:

1. Add a new overload to `DiagnosticDescriptor` [constructor](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,81), which takes an additional flag, say `bool isEnabledByDefaultInCommandLine`, apart from the already existing `bool isEnabledByDefault`. I personally don't like this proposal as it unnecessarily muddlles up public API surface for a scenario that is very likely not going to be used by majority of analyzer authors, if any.
2. Add a new custom tag, say `DisabledByDefaultOnCommandLine`, to [WellKnownDiagnosticTags](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/WellKnownDiagnosticTags.cs,03ef56ba68ffca36), and the analyzer driver will ensure that from command line compiler context, it also considers this custom tag in deciding if a particular analyzer/descriptor is disabled.

I personally prefer the second approach as it does not have any significant public API impact, while also allowing us to add support for this scenario. I implemented a prototype for it, and with this functionality enabled, adding a NuGet package reference to the [current candidate .NET5 analyzers package](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.NetAnalyzers), which has bunch of enabled suggestions but no enabled warning, leads to bunch of new CA suggestions in the IDE with absolutely no command line build impact in terms of functionality and performance.

**Comment by mavasani** [comment]
Tag @dotnet/dotnet-analyzers

**Comment by jmarolf** [comment]
I've thought about this and I think this a good idea. We want some simple way for an analyzer author to indicate that something is useful in an IDE context but is not a correctness concern.

The example @mavasani gave for an analyzer like this was "make method static". Someone _could_ fail their build on this analyzer but it most useful _as I'm writing a new method_. These sorts of things feel like refactorings but we've never had a good story for how refactorings are configured (and surfaced to the user) in the same way that analyzers are.

I think adding an API like this is probably the simplest step forward for fixing this problem. But I will add: What if we re-thought how refactorings were discovered and distributed? We've effectively been working around the fact that they are not configurable for years.

**Comment by terrajobst** [comment]
How will this configured by the user? It seems to me that this is something someone might want to be control using their editor config, just like regular severities.

> I can think of two potential approaches for implementing this feature in the analyzer driver:
> 
> 1. Add a new overload to `DiagnosticDescriptor` [constructor](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,81), which takes an additional flag, say `bool isEnabledByDefaultInCommandLine`, apart from the already existing `bool isEnabledByDefault`. I personally don't like this proposal as it unnecessarily muddlles up public API surface for a scenario that is very likely not going to be used by majority of analyzer authors, if any.
> 2. Add a new custom tag, say `DisabledByDefaultOnCommandLine`, to [WellKnownDiagnosticTags](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/WellKnownDiagnosticTags.cs,03ef56ba68ffca36), and the analyzer driver will ensure that from command line compiler context, it also considers this custom tag in deciding if a particular analyzer/descriptor is disabled.

Using the tag seems odd because it seems to be an intrinsic aspect of the diagnostic, rather than of the instance of that diagnostic.

**Comment by mavasani** [comment]
> How will this configured by the user? It seems to me that this is something someone might want to be control using their editor config, just like regular severities.

Enabling end user configuration support for this would be a much bigger work item, and likely need new compiler command line switches and such. The proposal here was aimed at a very simple way at shipping analyzers in the SDK that are not always build breaking warnings, for example performance rules, that light up in the IDE by default without impacting CI whatsoever.

> Using the tag seems odd because it seems to be an intrinsic aspect of the diagnostic, rather than of the instance of that diagnostic.

This is indeed a metadata associated with the the analyzer/specific diagnostic ID. We do not even want to execute an analyzer that is marked disabled on command line, so it will never report any diagnostics at all. Suppressing individual reported diagnostic instances is only supported via source suppression mechanisms (pragmas, suppress message attributes) and I don't think we want to enable any more mechanisms (certainly this issue is not targeted towards that space).

**Comment by terrajobst** [comment]
> This is indeed a metadata associated with the the analyzer/specific diagnostic ID

Gotcha, that makes sense then.

> Enabling end user configuration support for this would be a much bigger work item, and likely need new compiler command line switches and such.

That's what I thought. Would it be easier if we would think of a new severity that isn't enabled on the command line?

**Comment by mavasani** [comment]
> That's what I thought. Would it be easier if we would think of this as a new severity that isn't enabled on the command line?

That is possible, but again it would lead to a much wider change as the new severity needs to be understood by bunch of tooling. Generally, we are extremely resistant to adding more severities to `DiagnosticSeverity` enum and this looks like a very niche scenario for analyzers that want to ship with an SDK, which should be rare.

**Comment by mavasani** [comment]
So apart from the original proposal we seem to have 2 other alternatives:

1. Build on top of compiler feature https://github.com/dotnet/roslyn/issues/42219 and drop in a global editorconfig file to disable all suggestion/hidden diagnostics + props file they passes this global editorconfig file down to the compiler when doing CI builds (can be detected with MSBuild properties)
2. Suggestion from @sharwell to make a breaking change in the compiler to always consider diagnostics which are suggestion/hidden by default to be disabled by default in CI, and only execute them if user has explicit configuration for the ID in editorconfig/ruleset that bumps them to warning/error. We could also tie suggestion diagnostics to `/bl` switch and introduce a new compiler switch that restores the prior semantics if users do care about suggestions on command line.

**Comment by mavasani** [comment]
Tagging @jaredpar @agocke @mikadumont for their views on how to proceed with this issue. Let me give some context in this comment itself so you don't need to read through the whole issue comments.

**Context:** Ability to ship analyzers which are suggestion or hidden diagnostics by default in NuGet packages and/or SDK, such that these analyzers have no performance or functionality impact in CI, i.e. are IDE-only analyzers by default, until user bumps the severity to be a warning/error, at which point they execute in CI

**Possible Approaches:**
1. No compiler change + Analyzer authors must build on top of compiler feature request #42219 and drop in a global editorconfig file to disable all suggestion/hidden diagnostics + props file they passes this global editorconfig file down to the compiler when doing CI builds (can be detected with MSBuild properties)

   **PROS:** No changes to compiler or analyzer driver
   **CONS:** All analyzer authors do not automatically get the performance benefit, and authoring such tooling to insert these files into their analyzer package might be cumbersome to implement for them.

2. New compiler feature to allow analyzer authors to explicitly opt-in their suggestion/hidden analyzers to be disabled by default in CI, while being enabled by default in other hosts. I can think of two potential approaches for implementing this feature in the analyzer driver:
   1. Add a new overload to `DiagnosticDescriptor` [constructor](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,81), which takes an additional flag, say `bool isEnabledByDefaultInCommandLine`, apart from the already existing `bool isEnabledByDefault`. I personally don't like this proposal as it unnecessarily muddlles up public API surface for a scenario that is very likely not going to be used by majority of analyzer authors, if any.
   2. Add a new custom tag, say `DisabledByDefaultOnCommandLine`, to [WellKnownDiagnosticTags](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/WellKnownDiagnosticTags.cs,03ef56ba68ffca36), and the analyzer driver will ensure that from command line compiler context, it also considers this custom tag in deciding if a particular analyzer/descriptor is disabled.

   **PROS:** No changes to core compiler, and trivial functionality add to analyzer driver. Also no breaking changes here as this is an opt-in feature.
   **CONS:** Again, all analyzer authors do not automatically get the performance benefit, though it should be easy for them to opt-in and release a new package.

3. Suggestion from @sharwell to make a breaking change in the compiler to always consider diagnostics which are suggestion/hidden by default to be disabled by default in CI, and only execute them if user has explicit configuration for the ID in editorconfig/ruleset that bumps them to warning/error. We could also tie suggestion diagnostics to /bl switch and introduce a new compiler switch that restores the prior semantics if users do care about suggestions on command line.

   **PROS:** All analyzer authors get automatic performance benefit here. The new behavior also seems more reasonable as people don't really except suggestions in output and default MSBuild verbosity also filters them out. Users who are broken by this change can pass in the new command line switch to restore prior behavior.
   **CONS:** Introduces a breaking change to the compiler as command line compiler output will no longer emit suggestions by default. This will also have an effect on `/errorlog` output as currently suggestions are emitted in error log by default.

Personally, I am fine with any of the three approaches above. I just need us to come to a resolution on this so I can implement the functionality for both new .NET5 SDK analyzers and CodeStyle analyzers.

**Comment by jmarolf** [comment]
I would prefer number 3

**Comment by mavasani** [comment]
Ping @jaredpar @agocke

**Comment by jaredpar** [comment]
I feel strongly that neither the compiler nor the analyzer driver should have any understanding of continuous integration. That concept exists entirely in the layer above the compilation tools. It should be used to drive changes to the compiler pipeline not as an argument to the compiler by which it can change it's behavior.

As much as we use CI in our ecosystem as well as it being popular with customers it is not fundamentally a part of compilation. Nor is it a set of principals which are universally agreed on by our customer base. It's just another system that utilizes the compilation pipeline. Hence the responsibility of customizing the compiler from CI should be driven by the CI layer of our tool chain. 

So given that I'm pretty strongly against (2). I also don't agree that (2) doesn't require changes to the core compiler. At the very least it's new information that the core compiler has to thread down. 

The details of (3) are more vague but it sounds like this will force the notion of CI into the compiler. That seems to be the only way to implement the behavior sketched out there. As such again I'm strongly against this.

My vote is for (1). The compiler team is already implementing the notion of global editor config files. I don't see any problem putting some responsibility on the analyzer authors to properly specify how they want their analyzers to be displayed in the IDE / CI

**Comment by sharwell** [comment]
@jaredpar it was not my intent for option (3) to force the concept of IDE/CI down to the compiler. It _may_ require a change to set the minimum diagnostic severity to report, but then the IDE and MSBuild would be responsible for setting that to the correct values (Hidden and Warning, respectively).

**Comment by mavasani** [comment]
**Update:** We had an offline design discussion on this and came to the following conclusion:

1. Analyzers reporting Hidden diagnostics will always be skipped in build
2. Analyzer reporting Info (Suggestion) diagnostics will be skipped if `/errorlog` has not been specified. This is the only officially supported scenario where we want to log Info diagnostics. The command line compilers do report Info diagnostics on command line today, but these are filtered away by MSBuild and are effectively never visible to users. This makes this a non-breaking scenario in .NET core build environment and an extreme corner case breaking change on desktop (clients relying on info diagnostics from raw csc/vbc output). Note that such clients would still have a workaround to get the prior behavior by enabling `/errorlog`.
