### ISSUE TITLE
IDE0059 False Positive with finally branch

### ISSUE THREAD

**Issue by pix64** [dotnet/roslyn#42197]
**Version Used**: 
VS 2019 16.4.5

**Steps to Reproduce**:

    static void Foo(int val)
    {
        bool flag = false;
        try
        {
            if (!TryFailableOp(val))
            {
                flag = true; // IDE0059: Unnecessary assignment of a value
            }

            // More
        }
        finally
        {
            if (flag) // flag is used here
            {
                DoCleanup();
            }
        }
    }

**Comment by mavasani** [comment]
Verified no repro on VS2022
