### ISSUE TITLE
'Convert to interpolated string' should not nest an existing interpolated string

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#42195]
**Version Used**: VS 16.4.5

```cs
class C
{
    string M(string a, string b)
    {
        // 🛠 Convert to interpolated string
        //                      ↓
        return $"Foo {a} goo: " + b;
    }
}
```

Current result:

```cs
class C
{
    string M(string a, string b)
    {
        return $"{$"Foo {a} goo: "}{b}";
    }
}
```

Expected result:

```cs
class C
{
    string M(string a, string b)
    {
        return $"Foo {a} goo: {b}";
    }
}
```

**Comment by aristid-lavri** [comment]
Hi i want to work on this issue.
Can i have some guideline to begin?

**Comment by CyrusNajmabadi** [comment]
hi @aristid-lavri the code for this would be in: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs

LMK if you need any more help with this :)

**Comment by aristid-lavri** [comment]
hi @CyrusNajmabadi  Thank you 
i will LYK if i need more help :)

**Comment by aristid-lavri** [comment]
hi @CyrusNajmabadi 
here is my solution to solve this issue
in the "CreateInterpolatedString" method we have to add new condition when the piece is not "currentContentIsStringOrCharacterLiteral"
whitch will check if the current piece contain "InterpolatedStringStartToken" at the begining and "InterpolatedStringEndToken" at the end.
if condition is met then we remove the tokens and add the rest of the piece in the content array

LMK if this is a good approach.

**Comment by CyrusNajmabadi** [comment]
Seems reasonable!  Try it out and make a pr :-)

**Comment by aristid-lavri** [comment]
i have those issues when i want to try my change in vs

Unknown argument 'D:\Personnel\Projet\ProjetPersonnel\Contribution'. 
Input files should have the '.vsdconfigxml' extension.	
Microsoft.CodeAnalysis.VisualBasic.ResultProvider	
D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn\src\ExpressionEvaluator
\VisualBasic\Source\ResultProvider\Portable\EXEC	1	



MSB3073	The command ""C:\Users\lavri\.nuget\packages\microsoft.vssdk.debugger.vsdconfigtool
\16.0.2032702\build\vsdconfigtool.exe" 
D:\Personnel\Projet\ProjetPersonnel
\Contribution GitHub\roslyn\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider
\VisualBasicResultProvider.vsdconfigxml "D:\Personnel\Projet\ProjetPersonnel
\Contribution GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis.VisualBasic.ResultProvider
\Debug\netstandard1.3\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.dll" 
"D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn\artifacts
\bin\Microsoft.CodeAnalysis.VisualBasic.ResultProvider\Debug\netstandard1.3
\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.vsdconfig"" 
exited with code -1.	Microsoft.CodeAnalysis.VisualBasic.ResultProvider	
C:\Users\lavri\.nuget\packages\microsoft.vssdk.debugger.vsdconfigtool\16.0.2032702
\build\Microsoft.VSSDK.Debugger.VSDConfigTool.targets	31	



MSB3073	The command ""C:\Users\lavri\.nuget\packages
\16.0.2032702\build\vsdconfigtool.exe" 
D:\Personnel\Projet\ProjetPersonnel
\Contribution GitHub\roslyn\src\ExpressionEvaluator\CSharp\Source\ResultProvider
\CSharpResultProvider.vsdconfigxml "D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub
\roslyn\artifacts\bin\Microsoft.CodeAnalysis.CSharp.ResultProvider\Debug\netstandard1.3
\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll" 
"D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn\artifacts\bin
\Microsoft.CodeAnalysis.CSharp.ResultProvider\Debug\netstandard1.3
\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig"" 
exited with code -1.	Microsoft.CodeAnalysis.CSharp.ResultProvider	
C:\Users\lavri\.nuget\packages\microsoft.vssdk.debugger.vsdconfigtool\16.0.2032702
\build\Microsoft.VSSDK.Debugger.VSDConfigTool.targets	31	



VSSDK1025	Could not add the file 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub
\roslyn\artifacts\bin\Microsoft.CodeAnalysis.CSharp.ResultProvider
\Debug\netstandard1.3\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig' 
to the zip package 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn
\artifacts\VSSetup\Debug\ExpressionEvaluatorPackage.vsix'. 
Could not find file 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn
\artifacts\bin\Microsoft.CodeAnalysis.CSharp.ResultProvider\Debug\netstandard1.3
\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig'.	
ExpressionEvaluatorPackage	
D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn\src\ExpressionEvaluator
\Package\VSSDK	1	


VSSDK1025	Could not add the file 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub
\roslyn\artifacts\VSSetup\Debug\ExpressionEvaluatorPackage.vsix' 
to the zip package 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn
\artifacts\VSSetup\Debug\RoslynDeployment.vsix'. 
Could not find file 'D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn
\artifacts\VSSetup\Debug\ExpressionEvaluatorPackage.vsix'.	
RoslynDeployment	
D:\Personnel\Projet\ProjetPersonnel\Contribution GitHub\roslyn\src\Deployment\VSSDK	1

**Comment by jnm2** [comment]
@aristid-lavri I would lean heavily on tests to try out the change and to do any debugging. F5 should work though to launch VS. Is F5 what is giving you those errors?

**Comment by aristid-lavri** [comment]
@jnm2 yes it is F5

**Comment by aristid-lavri** [comment]
for the tests i have to write my own? or there is an existing one ?

sorry if i ask too many trivia questions

**Comment by aristid-lavri** [comment]
here is the message i get when running test 
System.InvalidOperationException : One document must have a single span annotation

        [WorkItem(42195, "https://github.com/dotnet/roslyn/issues/42195")]
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsConvertToInterpolatedString)]
        public async Task TestConcatenationWithExistingInterpolation()
        {
            await TestInRegularAndScriptAsync(@"
class C
{
    string M(string a, string b)
    {                      
        return $""Foo {a} goo: "" + b;
    }
}",
@"
class C
{
    string M(string a, string b)
    {                      
        return $""Foo {a} goo: {b}"";
    }
}");
        }

**Comment by CyrusNajmabadi** [comment]
hey @aristid-lavri  i would recommend coming to either gitter.im/dotnet/roslyn or discord.gg/csharp (channel #roslyn) for these sorts of questions.  They're much more conducive to back and forth dialog.

**Comment by CyrusNajmabadi** [comment]
For your test, take a look at the other tests in the file, you'll see they either use `$$` or `[| ... |]`.  these are markers to help declaratively specify positions/selections.  try to follow that in your pr.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  We get this now:

![image](https://user-images.githubusercontent.com/4564579/199327093-9dde2857-e4a6-47fe-8c99-dc39d8d7a96e.png)
