### ISSUE TITLE
Suggest using declaration when the only statement outside the using statement has no interactions

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#42194]
I often come upon code that restricted the scope of the using statement as a stylistic choice rather than by necessity. It would be consistent to offer "IDE0063 'using' statement can be simplified" here too.

```cs
class C
{
    bool M()
    {
        using (var foo = new MemoryStream())
        {
            // ...
        }

        return true; // Or any compile-time constant or variable read or throw statement
    }
}
```

Should be treated as though it was identical to the return statement first being moved into the using statement, offering:

```cs
class C
{
    bool M()
    {
        using var foo = new MemoryStream();

        // ...

        return true;
    }
}
```

**Comment by jnm2** [comment]
The rule of thumb to determine whether an operation could interact with the end of the using statement is whether it has the potential to change the timing of code outside the current method so that it executes before disposal happens. That means method calls of any kind (methods, operators, delegate invocation, accessors, etc) are out. Variable writes are out unless you can prove that no other thread could be watching that variable.

Technically speaking that makes `new FooException();` invalid, but more likely it is safe to whitelist the pattern `throw new SomeException(/* anything */);`.

**Comment by sharwell** [comment]
Marking as **help wanted** to support the case where the `using` statement is followed by one or more of the following:

* A return statement
* A constant expression
* Local function definitions
