### ISSUE TITLE
new GlobalSuppressions.cs file is generated when the existing one is in Properties subfolder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42201]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/937290/new-globalsuppressionscs-file-is-generated-when-th.html)._

---
I put my GlobalSuppressions.cs file into the Properties subfolder of the csproj project.

When I wanna add a new suppression, a new GlobalSuppressions.cs file is generated in the project root folder.
This should not happen. the new suppression should be added to the Properties\GlobalSuppressions.cs file

---
#### Visual Studio Feedback System on 3/3/2020, 03:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/37530
