### ISSUE TITLE
Convert Add File Banner refactoring to the new AbstractFileHeaderHelper analysis

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42203]
#41982 implements a new file header analysis helper `AbstractFileHeaderHelper`. The previous **Add File Banner** refactoring needs to be converted to this approach for consistency across multiple features.

1. Convert the current tests for **Add File Banner** to the new test library (which offers stronger guarantees and can better detect changes in behavior)
2. Convert **Add File Banner** to the new `AbstractFileHeaderHelper`, and address any changes in behavior

**Comment by CyrusNajmabadi** [comment]
We also have a few things that check banners i believe.  like sort-usings (which doesn't want to move banners around, even though they're leading trivia), and potentially move/extract-type.  

But i believe all these go through the common helpers.  so if you fix those up, we should be good.

Note: these common helpers are on ISyntaxFacts.  I'm 100% fine if you want to break them into their own special Helper class.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, we should assign a person and milestone and do it.
