### ISSUE TITLE
Pass all analyzer options through AnalyzerConfigOptions

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42200]
Currently IDE analyzers pass options through `AnalyzerConfigOptions` and also through `DocumentOptionSet`. The latter is not allowed to be used by synchronous paths in analyzers. A clean resolution to this involves using `AnalyzerConfigOptions` for both cases:

1. The host analyzer runner creates two instances of `AnalyzerConfigOptionsProvider`. The first provides options that only considers **.editorconfig** files. The second provides options that considers both .editorconfig files and the host's other options sources (e.g. Tools &rarr; Options for Visual Studio).
2. When executing a NuGet-installed analyzer, provide the `AnalyzerConfigOptionsProvider` that only derives options from **.editorconfig**.
3. When executing a VSIX-installed analyzer, provide the `AnalyzerConfigOptionsProvider` that derives options from both **.editorconfig** and the host.
4. Update `AnalyzerHelper.GetOption<T>` to no longer use `GetOptionAsync<T>`, and instead request option values from the `AnalyzerConfigOptionsProvider`, since it will now always be correct for the current analyzer context.

When this is complete, the `AnalyzerHelper.TryGetEditorConfigOption` method can be removed, and all existing uses of it updated to use the new (and improved) `GetOption<T>` method.

Related to #18818

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this we should assign to a person/milestone to do.
