### ISSUE TITLE
Roslyn occasionally parses double values incorrectly

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4221]
The following one-line program fails when compiled with the Roslyn command-line compiler (on x64) and run on x86 due to an underlying bug in double.Parse.

```cs
        System.Diagnostics.Debug.Assert(0.6822871999174 == double.Parse("0.6822871999174"));
```

An incorrect double value is baked into the generated assembly for the left-hand argument of ==.

Because of this issue the output of the compiler depends on whether the compiler is run on x86 or x64, so this is also a determinism issue.

The C# language specification refers to the [IEEE spec](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4610935&tag=1) section 5.12.2, which requires that we convert to the nearest representable double, with round-to-even as a tiebreaker for precise ties, when the input is 20 digits or fewer (and recommends doing so for longer inputs as well). Since this input has fewer than 20 digits, we have no excuse for different results. There are other cases where the compiler produces the wrong floating-point value for numbers with as few as three significant digits (see the test program below).

@jaredpar @DustinCampbell

See also #4149

**Comment by gafter** [comment]
Running the following code on x64 demonstrates that the platform floating-point conversion routines are not monotonic as required by the IEEE spec:

```cs
            Console.WriteLine("{0:G20}  {0:R}", Double.Parse("0.6822871999174000000"));
            Console.WriteLine("{0:G20}  {0:R}", Double.Parse("0.6822871999174000001"));
```

**Comment by gafter** [comment]
A few useful links about floating-point conversion.

- [The IEEE specification](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4610935&tag=1) section 5.12.2 lays out the requirements for scanning double values. Note that the C# language specification says that we should follow the IEEE rules. The worst we are allowed to do is get the precisely correct answer whenever 20 or fewer digits are provided as input; IEEE recommends getting the precisely correct answer for an unbounded number of input digits.
- [A coreclr bug report](https://github.com/dotnet/coreclr/issues/1316) for double.Parse, which the compiler uses to parse double values. Note that this bug demonstrates that we get the wrong answer on x64 when only 17 input digits are provided.
- [An open-source implementation widely believed to be precisely correct for all input lengths.](http://www.netlib.org/fp/dtoa.c). Given the existence of this code we really don't have any excuse for getting it wrong, at least not for the C++ compiler and library function strtod.
- [VS2015's C++ strtod is better than old versions, but still buggy](http://www.exploringbinary.com/visual-c-plus-plus-strtod-still-broken/)
- ["What Every Computer Scientist Should Know About Floating-Point Arithmetic"](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html).

**Comment by AlekseyTs** [comment]
There is a behavior difference between native and Roslyn compiler. A literal 0.6822871999174 is encoded in IL differently.

Roslyn:
```
IL_0001:  ldc.r8     0.68228719991740006
```

Native:
```
IL_0000:  ldc.r8     0.68228719991739994
```

**Comment by gafter** [comment]
Indeed. Since `0.6822871999174` is closer to the precise value represented by the native compiler's output, the native compiler is correct and Roslyn is incorrect here.

**Comment by gafter** [comment]
Here is a test program for some common problematic floating-point numbers. It should be combined with the code from http://jonskeet.uk/csharp/DoubleConverter.cs

```cs
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using System.Globalization;

struct Sample
{
    public double DoubleValue;
    public string StringValue;
    public double CorrectValue;
}
class Program
{
    public static void Main(string[] args)
    {
        var samples = new Sample[] {
            // https://msdn.microsoft.com/en-us/library/kfsatb94(v=vs.110).aspx
            new Sample() { DoubleValue = 0.6822871999174, StringValue = "0.6822871999174", CorrectValue = 0.68228719991739994 },

            // Common problem numbers
            new Sample() { DoubleValue = 2.2250738585072011e-308, StringValue = "2.2250738585072011e-308", CorrectValue = 2.2250738585072009E-308 },
            new Sample() { DoubleValue = 2.2250738585072012e-308, StringValue = "2.2250738585072012e-308", CorrectValue = 2.2250738585072014E-308 },

            // http://www.exploringbinary.com/bigcomp-deciding-truncated-near-halfway-conversions/
            new Sample() { DoubleValue = 1.3694713649464322631e-11, StringValue = "1.3694713649464322631e-11", CorrectValue = 1.3694713649464323E-11 },
            new Sample() { DoubleValue = 9.3170532238714134438e+16, StringValue = "9.3170532238714134438e+16", CorrectValue = 93170532238714128 },

            // a common round-trip problem number
            new Sample() { DoubleValue = 0.84551240822557006, StringValue = "0.84551240822557006", CorrectValue = 0.84551240822557006 },

            // http://www.exploringbinary.com/a-bug-in-the-bigcomp-function-of-david-gays-strtod/
            new Sample() { DoubleValue = 1.8254370818746402660437411213933955878019332885742187, StringValue = "1.8254370818746402660437411213933955878019332885742187", CorrectValue = 1.8254370818746402 },

            // http://www.exploringbinary.com/decimal-to-floating-point-needs-arbitrary-precision
            new Sample() { DoubleValue = 7.8459735791271921e+65, StringValue = "7.8459735791271921e+65", CorrectValue = 7.8459735791271916E+65 },
            new Sample() { DoubleValue = 3.571e+266, StringValue = "3.571e+266", CorrectValue = 3.5710000000000003E+266 },
            new Sample() { DoubleValue = 3.08984926168550152811e-32, StringValue = "3.08984926168550152811e-32", CorrectValue = 3.0898492616855018E-32 },
        };
        foreach (var sample in samples)
        {
            var compiler = sample.DoubleValue;
            //var runtime = double.Parse(sample.StringValue, CultureInfo.InvariantCulture);
            var correct = sample.CorrectValue;
            bool same = compiler.Equals(correct);

            Console.WriteLine("Correct? " + same + (same ? "" : "!!!!!!!!!!!!!!!!!!!!!!!!!!"));
            var lsb = NextDouble(compiler) - compiler;
            if (DoubleConverter.ToExactString(compiler).Length < 160)
            {
                Console.WriteLine("{0} original string", sample.StringValue);
                Console.WriteLine("{0} compiler", DoubleConverter.ToExactString(compiler));
                if (!same) Console.WriteLine("{0} correct", DoubleConverter.ToExactString(correct));
                Console.WriteLine("{0} compiler--", DoubleConverter.ToExactString(compiler - lsb));
                Console.WriteLine("{0} compiler++", DoubleConverter.ToExactString(compiler + lsb));
            }
            Console.WriteLine("{0} original string", sample.StringValue);
            Console.WriteLine("{0:G17} compiler", compiler);
            if (!same) Console.WriteLine("{0:G17} correct", correct);
            Console.WriteLine("{0:G17} compiler--", compiler - lsb);
            Console.WriteLine("{0:G17} compiler++", compiler + lsb);
            Console.WriteLine();
        }

    }

    static double NextDouble(double d)
    {
        ulong bits = (ulong)BitConverter.DoubleToInt64Bits(d);
        return BitConverter.Int64BitsToDouble((long)(bits + 1));
    }
}
```

**Comment by gafter** [comment]
As a test program the body of the loop could be replaced by
```cs
Debug.Assert(sample.DoubleValue.Equals(sample.CorrectValue));
```

**Comment by gafter** [comment]
@AlekseyTs I've added a bunch of difficult inputs to the test program above.

**Comment by leppie** [comment]
Please refer to "Printing Floating-Point Numbers Quickly and Accurately" by Bob Burger (1996). http://www.cs.indiana.edu/~dyb/pubs/FP-Printing-PLDI96.pdf

.NET has always had a problem printing floating point correctly without 'garbage' digits. 

Notably PI should be printed as `3.141592653589793` and not `3.1415926535897931` as .NET does.

**Comment by gafter** [comment]
@leppie this has nothing to do with printing floating-point numbers.

**Comment by leppie** [comment]
@gafter I understand it is a parsing problem, but it is related. It adds confusion to what is expected (a very common problem on SO).

Example: 

`9e-265` is `9e-265`, it does not have to be `9.0000000000000006E-265` 

The reverse holds. `9.0000000000000006E-265` is `9e-265`

**Comment by leppie** [comment]
I have just verified the tests and found one possible issue with the expected value of:

`2.2250738585072011e-308` =>  `2.2250738585072009E-308` 

For the input, the result should be `2.2250738585072014e-308` (tested on Petite Chez 8.4)

The following holds though: `2.225073858507201e-308` =>  `2.2250738585072009E-308` 

The rest are all OK, iow parsing of both the input and expected value results in the same number.

Tests: https://gist.github.com/leppie/0cd7ea1d6e3054699929

**Comment by leppie** [comment]
@gafter: I see the specific problem here now. `double.Parse` is also buggy from my tests (running above on IronScheme). Has that issue been logged on `coreclr`?

**Comment by gafter** [comment]
@leppie Thank you for double-checking my tests! I've corrected the issue you identified.

**Comment by gafter** [comment]
If any of you would care to offer a correct C# implementation of floating-point scanning, we'd use it!

**Comment by gafter** [comment]
Perhaps someone out there knows... perhaps it is a silly question... but we want to scan `float` constants like `5.6e12F` correctly as well. I found David M. Gay's [dtoa.c](http://www.netlib.org/fp/dtoa.c) which I'm thinking of translating to C#... but it only appears to be written to convert to `double`. Is that because it is "easy" to convert to `float` correctly, or do we need to adapt that code to do appropriate IEEE rounding to convert to `float`?

**Comment by leppie** [comment]
@gafter Most cases I have seen, they simply cast down. Porting dtoa.c to C# will be hard though, and much code is redundent due to it's internal support for arb sized integers (we have BigInteger already). 

Another option is to use Clinger's Algorithm R and Bellephoron as per 'How to Read Floating Point Numbers Accurately' (http://www.cesura17.net/~will/professional/research/papers/howtoread.pdf). While not as optimized as dtoa.c, it is not bad from what I can determine.

**Comment by gafter** [comment]
@leppie I'm aiming to scan *all cases* correctly. I'm concerned that there exist some (decimal) numbers that should round up when converted correctly to `float`, but round down when converted correctly to `decimal`, and after rounding to `decimal` the conversion to `float` rounds down because we've lost some trailing bits.

**Comment by leppie** [comment]
@gafter My honest feeling is that this should be handled natively (read C/C++) in the CLR, whether it uses it own implementation, or a platform one. Why duplicate already efficient and/or correct code?

**Comment by gafter** [comment]
Because that code does not exist for us to use yet.

**Comment by leppie** [comment]
@gafter I dont understand what you mean by that.

**Comment by gafter** [comment]
What I mean is that double.Parse is nondeterministic and incorrect today, and its performance requirements may be different from those of the compiler. Also we want the compiler to be deterministic across platforms. So we need a solution that does not rely on the currently buggy BCL. When we solve this, perhaps the code could be taken into the BCL.

**Comment by leppie** [comment]
@gafter Since your concern here seems to only be related to the compiler, any accurate implementation will do, even if it is slow. Porting dtoa.c would certainly be overkill.

**Comment by gafter** [comment]
@leppie Sure, but even in the compiler faster is better.

**Comment by leppie** [comment]
@gafter I would put that number at less than 10000 for all time :) Floating point constants (well at least the arbitrary ones) are not really common, except maybe in precomputed tables, which normally are not even defined beyond 6 decimal digits.

**Comment by gafter** [comment]
@leppie 
You wrote
> I have just verified the tests and found one possible issue with the expected value of:
> 2.2250738585072011e-308 => 2.2250738585072009E-308
> For the input, the result should be 2.2250738585072014e-308 (tested on Petite Chez 8.4)

No, it was right before. We have found a bug in Petite Chez 8.4. Please report it.

**Comment by leppie** [comment]
@garfer :+1: 

I just checked it again, and it does seem like a bug in Petite Chez.

**Comment by leppie** [comment]
@gafter: I have converted this for use in IronScheme (.NET 2, and IntX) and all previously noted tests pass on both versions of the runtime and both bitness! :+1: 

Thanks a lot, hope this makes it into .NET desktop one day.
