### ISSUE TITLE
Port and enable NamingStyleCodeFixProvider in CodeStyle layer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#42218]
`NamingStyleCodeFixProvider` current depends on an `IWorkspaceService`, [ISymbolRenamedCodeActionOperationFactoryWorkspaceService](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/CodeRefactorings/WorkspaceServices/ISymbolRenamedCodeActionOperationFactoryWorkspaceService.cs). See https://github.com/dotnet/roslyn/blob/ace0fdea9733b9b6842495a17873acf6c9bf0d60/src/Features/Core/Portable/CodeFixes/NamingStyle/NamingStyleCodeFixProvider.cs#L133-L142

This prevents it from being ported into a NuGet package. We should remove this dependency to unblock this port.

**Comment by sharwell** [comment]
Can we just use `Renamer`?

**Comment by mavasani** [comment]
Yes, but it seems like that will stop the following code from being invoked: https://github.com/dotnet/roslyn/blob/ace0fdea9733b9b6842495a17873acf6c9bf0d60/src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolRenamedCodeActionOperationFactoryWorkspaceService.cs#L64-L79

We will stop notifying all the `IRefactorNotifyService` implementations, so we need some different mechanism for it.

**Comment by sharwell** [comment]
Essentially every other symbol rename refactoring uses `Renamer`. We should switch this code fix to also use `Renamer`, and if something is broken then we need to fix the public `Renamer` API.

**Comment by mavasani** [comment]
It turns out the code fix does use the Renamer in its primary code action: https://github.com/dotnet/roslyn/blob/ace0fdea9733b9b6842495a17873acf6c9bf0d60/src/Features/Core/Portable/CodeFixes/NamingStyle/NamingStyleCodeFixProvider.cs#L93-L100

It just registers an additional code action `CreateSymbolRenamedOperation` whose purpose is just to invoke the `IRefactorNotifyService` implementations. I think we should likely move the latter functionality to the `Renamer`.

**Comment by ryzngard** [comment]
This will be fixed with #47048
