### ISSUE TITLE
Diagnostic message about auto-property initializers in interfaces could be confusing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42233]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/915469/code-checker-issue-with-editor-error-message-regar.html)._

---
```csharp
public interface TestInterface
    {
        protected string ApiKey { get; set; } = string. Empty;
    }
```
(Error message: Only auto-implemented properties can have initializers)

```csharp
public class TestInterface
    {
        protected string ApiKey { get; set; } = string. Empty;
    }
```
(works fine)

No compilation is required, just the C# language checker, or what you call it, interpreting the code on the fly :)

I suspect that it should instead tell that interfaces cannot have implementation, or something of that sort.

Best regards,
Alexander

---
#### Visual Studio Feedback System on 2/13/2020, 05:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kevinsun-dev** [comment]
Error has been clarified in PR #44860. Thanks for the report!
