### ISSUE TITLE
Unimported Intellisense gives non-generic collections when typing '<'

### ISSUE THREAD

**Issue by NoneGiven** [dotnet/roslyn#42241]
**Version Used**: 

VS 2019
16.5.0 Preview 5.0

**Steps to Reproduce**:

1. Ensure the "Show items from unimported namespaces" IntelliSense setting is enabled.
2. Ensure `System.Collections` and `System.Collections.Generic` are not in your list of usings.
3. Start typing `IEnumerable` as a type name.
4. Type `<`.

**Expected Behavior**:

A using directive for `System.Collections.Generic` is added.

**Actual Behavior**:

A using directive for `System.Collections` is added.

After step 3, the completion list shows the non-generic `IEnumerable` as the first option, so I could understand if `Tab` completion imported that one (although I think you could still argue that the generic should be prioritized since it's used much more). However, when typing `<` rather than `Tab`, it absolutely should import the namespace for the generic `IEnumerable<>`.

**Comment by genlu** [comment]
Looks like a duplication of #36730
