### ISSUE TITLE
considered snapshot testing?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/roslyn#42279]
I was wondering if snapshot testing had been considered as a way of simplifying the way test results are verified in the roslyn codebase?

I did a quick scan through and found several assertion patterns that could benefit 

 * VerifyTypeIL https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDisplayClassOptimisationTests.cs#L41
 * parser tests https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Syntax/Parsing/AsyncParsingTests.cs#L281
 * verifying pdbs https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs#L335

So for each of these snapshot testing would resulting in, for each test, a "verified/approved" file containing a serialized representation of what is being asserted. This has the following benefits:

 * on the first run of the test a proposed approved file is generated, that can then be optionally accepted.
 * no assertion code required. looking through the above scenarios it seems complex assertion is usually either done with a dsl or large strings. this is no longer required with snapshot testing. the approved file for each test is the assertion. 
 * more resilient to change. in the current code base, a small change that effects the compile could result in the assertion code significant number of tests needing to be refactored. with snapshot testing all changed files can be approved with one command line action
 * visualisation of failures. when a test fails, a new proposed file is generated, which can then be diff'd against the current approved file.

With above in mind i created an example project that illustrates snapshot testing using the decompiler feature of ICSharpCode.Decompiler as the serialization mechanism https://github.com/SimonCropp/Verify.ICSharpCode.Decompiler. so you can see a test https://github.com/SimonCropp/Verify.ICSharpCode.Decompiler/blob/master/src/Tests/Tests.cs#L20-L33 and its corresponding verified files https://github.com/SimonCropp/Verify.ICSharpCode.Decompiler/blob/master/src/Tests/Tests.TypeDefinitionUsage.verified.txt (i am trimming the result to make doco easier).

This uses my snapshot project https://github.com/SimonCropp/Verify. But there are other options:

 * https://github.com/approvals/ApprovalTests.Net
 * https://github.com/SwissLife-OSS/Snapshooter
 * https://github.com/theramis/Snapper

Is this something you would like to explore further? I am happy to get on a call to discuss.

**Comment by agocke** [comment]
> So for each of these snapshot testing would resulting in, for each test, a "verified/approved" file containing a serialized representation of what is being asserted. This has the following benefits:

> *  on the first run of the test a proposed approved file is generated, that can then be optionally accepted.

This just seems like it moves the assertion from one file into many. Many of our tests are very short. This would create hundreds or thousands tiny files, vs one file with a hundred 10-line tests.

* no assertion code required. looking through the above scenarios it seems complex assertion is usually either done with a dsl or large strings. this is no longer required with snapshot testing. the approved file for each test is the assertion.

This seems wrong. The parsing tests, for example, assert the shape of the tree post-parsing. You aren't going to remove any assertion, just serialize the syntax tree. Now that creates a dependency on the syntax tree serialization format, in addition to the syntax tree shape.

> * more resilient to change. in the current code base, a small change that effects the compile could result in the assertion code significant number of tests needing to be refactored. with snapshot testing all changed files can be approved with one command line action

This is bad. We explicitly want to see when the IL massively changes, even if the "behavior" is identical. If a change modifies the emitted IL of thousands of tests, that's a test change proportionate to the impact of the product change.

> * visualisation of failures. when a test fails, a new proposed file is generated, which can then be diff'd against the current approved file.

We have test helpers to do the same. For individual tests its probably roughly the same amount of work. If you're changing a lot of tests it's easier to do it your way, but as I mentioned above, changing the baseline for thousands of tests should generally be a big red flag and it should be costly.

**Comment by SimonCropp** [comment]
> This just seems like it moves the assertion from one file into many. Many of our tests are very short. This would create hundreds or thousands tiny files, vs one file with a hundred 10-line tests.

Yes. although it doesnt need to be used for all tests. Also the cost of splitting into a different files has the benefit of significantly reducing the complexity of the assertion code. nothe that the resulting files get nested under the test file. 
![image](https://user-images.githubusercontent.com/122666/76187301-17298680-6229-11ea-8d2d-6fdf3738cea3.png)

So when collapsed you dont see them

![image](https://user-images.githubusercontent.com/122666/76187338-2e687400-6229-11ea-8ad6-f62f9cc3bf82.png)

> This seems wrong. The parsing tests, for example, assert the shape of the tree post-parsing. You aren't going to remove any assertion, just serialize the syntax tree. Now that creates a dependency on the syntax tree serialization format, in addition to the syntax tree shape

you already have a dependency on the syntax tree serialization format. that is how the current decompler code works in roslyn. you serialize to a string using icsharpcode, then compare that to a string in the assertion.

> This is bad. We explicitly want to see when the IL massively changes, even if the "behavior" is identical. If a change modifies the emitted IL of thousands of tests, that's a test change proportionate to the impact of the product change.

It is optional to approve all. you can review as many of the changed files using any diff tool before making the decision to approve them. or you can approve them one by one.

> We have test helpers to do the same.

Note that changes in approved files can be deferred to better tooling: https://github.com/SimonCropp/Verify/blob/master/docs/diff-tool.md. eg here is the experience that can happen when an image has changed https://github.com/SimonCropp/Verify/blob/master/docs/binary.md

**Comment by agocke** [comment]
> you already have a dependency on the syntax tree serialization format. that is how the current decompler code works in roslyn. you serialize to a string using icsharpcode, then compare that to a string in the assertion.

Pretty sure you're misunderstanding how the parsing tests work. They never actually emit anything.

**Comment by agocke** [comment]
That said

> Yes. although it doesnt need to be used for all tests

That's true. I would be open to it for specific tests.

**Comment by SimonCropp** [comment]
when i said "you already have a dependency on the syntax tree serialization format" i was referring to the serialization of IL https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenDisplayClassOptimisationTests.cs#L41 sorry to conflate the terms

**Comment by SimonCropp** [comment]
if this is not something you are interested in then feel free to close
