### ISSUE TITLE
[Regression]Under VB profile, there is no Attach to Process

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4228]
__Tools__ -> __Attach to Process__ menu item was removed in VS 2015 in lieu of the one under Debug. Unfortunately, the VB profile by default hides the one under Debug. This leaves VB profile users no Attach to Process in VS 2015.

We should add Debug -> Attach to Process to the VB profile.

**Comment by MojoDK** [comment]
(I'm using VB) .. How can I get this "Attach to process" back ASAP? Do I really need to deinstall VS2015 and reinstall 2013 to get it back? I use it all the time. Sigh. :(

**Comment by Pilchie** [comment]
You can get it back using the Tools\Customize menu to place the command on a menu or toolbar.

**Comment by MojoDK** [comment]
Thanks!!!!

**Comment by davkean** [comment]
This will be fixed in the next public CTP of Visual Studio 2015 Update 1.

**Comment by davkean** [comment]
This has been merged in.
