### ISSUE TITLE
CS8634: System.Type should match class constraint

### ISSUE THREAD

**Issue by skarllot** [dotnet/roslyn#42289]
**Version Used**: Visual Studio 2019 Version 16.4.5

**Steps to Reproduce**:

```csharp
  public static class Requires
  {
    public static T NotNull<T>(T value, string? parameterName) where T : class
    {
      if (value == null)
        throw new ArgumentNullException(parameterName);
      return value;
    }
  }

// ...

    public void Test(Type type)
    {
        Requires.NotNull(type, nameof(type)); // <-- CS8634
        // ...
    }
```

**Expected Behavior**:
Do not report any issue.

**Actual Behavior**:
`CS8634` reports that `System.Type` does not match class constraint.

**Comment by svick** [comment]
I can't reproduce this in VS 16.4.5 or [on SharpLab](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKFwYgDsBXAG1IEMAjUiAAgkOtt1xQGY6UMA2LtOgCUIAR2IwoEAM64A3rjpdO3PgBU6AOQD2wDWVIAeVQD4AFOrAVSxCABouGAAwB+OgAcKUCgFsIwaBo+EACUdADuABbQ9Oog/Ap08jiKivB0ppbW9AC82XQk5MEJKXTAEVBaYfkQVQCCUADmxL6EuvoAogAeAMYQbsAwWoSmHl6+/lCBvsEA3MVcAOx0mTZzyXQAvrhbeDjodADCcvMcXAAsdKrSwOYIbvTAdyHzSSUlwmIS0gB02m3kpke93sTF8WjggKewVmdAA9LC6AYALRIw4AZQAHDx2Gd5iV4XRvkT5jsNkA=) using the code:

```c#
using System;

#nullable enable

public static class Requires
{
  public static T NotNull<T>(T value, string? parameterName) where T : class
  {
    if (value == null)
      throw new ArgumentNullException(parameterName);
    return value;
  }
}

class C
{
    public void Test(Type type)
    {
        Requires.NotNull(type, nameof(type)); // <-- CS8634
        // ...
    }
}
```

I can make the code produce the following error, [if I change `Type type` to `Type? type`](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKFwYgDsBXAG1IEMAjUiAAgkOtt1xQGY6UMA2LtOgCUIAR2IwoEAM64A3rjpdO3PgBU6AOQD2wDWVIAeVQD4AFOrAVSxCABouGAAwB+OgAcKUCgFsIwaBo+EACUdADuABbQ9Oog/Ap08jiKivB0ppbW9AC82XQk5MEJKXTAEVBaYfkQVQCCUADmxL6EuvoAogAeAMYQbsAwWoSmHl6+/lCBvsEA3MVcAOx0mTZzyXQAvrhbeDjodADCcvMcXAAsdKrSwOYIbhCuwHch80klJcJiEtIAdNpt5FMT3u9iYvi0cCBz2CszoAHo4XQDABaZGHADKAA4eOwzvMSgi6D9ifMdhsgA===):

> warning CS8634: The type 'System.Type?' cannot be used as type parameter 'T' in the generic type or method 'Requires.NotNull<T>(T, string?)'. Nullability of type argument 'System.Type?' doesn't match 'class' constraint.

But I believe this is expected.

Can you provide a small, but complete project that demonstrates the issue? Especially important are any `<Nullable>` in your project file and `#nullable` in your source code. Also, the full error message could help.

**Comment by Joe4evr** [comment]
This is because your `T` input parameter is typed as non-nullable, so converting from `T?` to `T` isn't allowed under NRT rules. You have to add the question mark to the parameter: `T? value`.

**Comment by jcouv** [comment]
@skarllot I'm not able to reproduce this issue. I suspect this was fixed. Would you be able to try again and produce a self-contained snippet or sharplab link if you still see the problem? Thanks

**Comment by skarllot** [comment]
I can't reproduce it anymore. Sorry late reply.
