### ISSUE TITLE
[ENC] VS crash when the whole namespace block containing active statements is deleted

### ISSUE THREAD

**Issue by wschae** [dotnet/roslyn#4230]
1. Create C# App

namespace N
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}

2. F11 to stop at the beginning.

3. Select the whole namespace block (i.e., namespace N { ... }) and delete it

Expected: Rude edit about deleting 'namespace'

Actual: VS crash

**Comment by wschae** [comment]
Similar case:

1. VB - Remove Module Block containing active statements:

Module Module1

    Sub Main()

    End Sub

End Module

2. C# - Remove a class block containing active statements, when no namespace around:

    class Program
    {
        static void Main(string[] args)
        {
        }
    }

**Comment by amcasey** [comment]
Assigning to @drognanar (fyi @tmat).

**Comment by ManishJayaswal** [comment]
@drognanar is this issue fixed.

**Comment by drognanar** [comment]
Yes, it has been fixed already.
