### ISSUE TITLE
Lambda Type Incorrectly Inferred When Written As Expression (But Works As A Statement)

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/roslyn#42314]
The same logical lambda is generating different code depending on if it's written as a statement or an expression. 

Here is the code as an expression lambda.
```
Task rt = Task.Run(() => RestoreDatabase(name, owners, jobGuid));
```
If I mouse over the code, the call is interpreted as `Task.Run<dynamic>(Func<dynamic>)`

However, when written as a statement lambda, there is a different response:
```
Task restoreTask = Task.Run(() =>
            {
                RestoreDatabase(name, owners, jobGuid);
            });
```
This code shows up as Task.Run(Action);

The signature of the called function is `private void RestoreDatabase(string name, List<string> owners, Guid id)`, so I'd expect it to be an Action.

The issue affects more than intellisense. If the call is written as a expression, the Task fails to execute, and generates an exception:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'
   at CallSite.Target(Closure , CallSite , ServerMethods , Object , Object , Guid)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at DbRestorer_ServerApp.ServerMethods.<>c__DisplayClass6_0.<BeginRestoreDatabase>b__0() in
C:\\GitProjects\\DatabaseRestorer\\DbRestorer-ServerApp\\ServerMethods.cs:line 151
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

However, when written as a statement, the code executes as expected. 

The code is targeting ASP.NET Core (3.1).

**Comment by YairHalberstadt** [comment]
This is correct behaviour.
statement bodied lambdas must have a return statement to be treated as func. Your example doesn't have one so is interpreted as an Action. Expression bodied lambdas cant have a return statement, so are target typed to a Func or Action based on context. Here both are possible, and the compiler prefers Func.

**Comment by iUnknwn** [comment]
For clarity, how is Func<dynamic> possible if the called function returns void?

**Comment by iUnknwn** [comment]
Also, if this is expected behavior, is there a way to make this a compiler warning or error at compile time, instead of triggering an exception at runtime? For example, if the compiler can't infer the lambda type, and guessing wrong would cause an error, trigger a warning in the same way we do for an ambiguous cast?

**Comment by CyrusNajmabadi** [comment]
>  is there a way to make this a compiler warning or error at compile time, instead of triggering an exception at runtime

You could write an analyzer to check for this sort of situation.

**Comment by YairHalberstadt** [comment]
It looks like RestoreDatabase returns dynamic or is dynamic or something?

**Comment by iUnknwn** [comment]
@YairHalberstadt No - that's the confusing thing. Here's the entire RestoreDatabase function:

```
        private void RestoreDatabase(string name, List<string> owners, Guid id)
        {
            Logger.Debug($"Attempting restore operation, file: {name}, guid: {id.ToString()}");

            try
            {
                var db = new DatabaseFunctions(name);
                db.RestoreDatabase(owners);
            }
            catch (Exception e)
            {
                Logger.Error(e, $"Database Restore Failed: {e.ToString()}");
            }
        }
```

The function doesn't use dynamic, and never returns anything.

**Comment by YairHalberstadt** [comment]
@iUnknwn 
Can I see the full context in which it's called please?

**Comment by iUnknwn** [comment]
@YairHalberstadt - Certainly. Here's the calling function (written using the statement syntax to ensure it works):

```
        private object BeginRestoreDatabase(dynamic args)
        {

            var name = Request.Query.name;
            var ownersString = Request.Query.owners;

            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(ownersString))
            {
                return Response.AsJson(ResponseBuilder
                    .BuildError("Name and Owners parameters cannot be null/empty.")
                    .Build()
                    );

            }

            // parse the owners field
            var owners = JsonConvert.DeserializeObject<List<string>>(ownersString);

            var jobGuid = Guid.NewGuid();

            Logger.Debug("Starting restore task...");

            // lambda incorrectly interpreted as Func<dynamic> if
            // written in expression form.
            Task restoreTask = Task.Run(() =>
            {
                RestoreDatabase(name, owners, jobGuid);
            });

            lock (activeJobs)
            {
                activeJobs[jobGuid] = restoreTask;
            }

            var resp = ResponseBuilder.BuildSuccess()
                .AddPayload("guid", jobGuid.ToString())
                .Build();

            return Response.AsJson(resp);
        }
```

That in turn is called by NancyFx under ASP.NET Core:

```
        public ServerMethods()
        {
            // note StartRestoreDatabase requires a path (string) and owners (json list) 
            Get("/BeginRestoreDatabase", args => BeginRestoreDatabase(args));

            Get("/CheckCompletion/{guid}", args => CheckCompletion(args));

            Get("/EndRestoreDatabase/{guid}", args => EndRestoreDatabase(args));

            // requires query string: name
            Get("/GetDatabaseNamesFromFile", args => GetDatabaseNamesFromFile(Request.Query.name));

            // get all active jobs
            Get("/GetAllActiveJobs", args => GetAllActiveJobs());
        }

```

I can also provide the file, if that would help.

**Comment by YairHalberstadt** [comment]
@iUnknwn 

A couple of questions about that code:

1. What is the type of Request.Query.name, and Request.Query.owners?
2. As far as I can see the `args` parameter isn't used. Is this correct?

**Comment by iUnknwn** [comment]
@YairHalberstadt 

1. Both Request.Query.name and Request.Query.owners are actually strings, though, since Request.Query is dynamic, and I have owners and name declared as var, they are type dynamic as well.
2. Correct - in NancyFx some components of a request are placed in a dynamic args object (some parts of the URL), and some are placed in the globally-accessible Request object. That's a remnant of an earlier version of the function - it's no longer used.

**Comment by jaredpar** [comment]
I chatted with @iUnknwn offline. One key piece of the puzzle here is the following:

```cs
var name = Request.Query.name;
```

The type of `name` here is `dynamic` that means the eventual call to `RestoreDatabase` is a `dynamic` call, not a traditional method call. Hence the compiler assumes the return type is `dynamic`, not `void`. At that point it's possible to bind to `Func<dynamic>` and then our tie breaking rules come in and we eventually prefer that over `Action`.

**Comment by iUnknwn** [comment]
Thanks again for clearing up the issue. I can confirm that simply changing the declaration of name to be a string solved the problem:

```C#
string name = Request.Query.name;
```

With this change, the lambda is being correctly typed as an action.
