### ISSUE TITLE
When the editor is in "user read-only" mode, users are offered code fixes that do nothing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#4232]
1. File -> New -> WinForms Application
2. F5
3. Open Project.cs

**Expected:** Not to be offered code fixes 
**Actual:** 

![image](https://cloud.githubusercontent.com/assets/1103906/8990506/9caa4888-36a7-11e5-9338-0e735af52c67.png)

Choosing any of the code fixes, results in nothing happening. We shouldn't be offering code fixes when the underlying doc data is user-readonly.

**Comment by miloush** [comment]
Note there is a _Allow editing of read-only files; warn when attempt to save_ setting and also a source control option _Do nothing_ for editing.

Both these features allow for editing read-only files and I would expect the code fixes to be offered (and working) as usual in these cases.

**Comment by davkean** [comment]
Sorry, I should be clear here; there's two concepts of "read-only" with regards to files inside the editor:

1. __File-system read-only__. ie Read-only disk, either set explicitly by someone, or via source control. Code fixes should continue to work when these files are opened.

2. __User read-only__. This is where the user is not allowed to edit the file, due to some state of the IDE, for example, debugging and Edit & Continue is turned off.

I'm only referring to 2., not 1.

**Comment by miloush** [comment]
I see, I suspected the _user-_ part might be a catch. :) Thanks for clarification.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this area.
