### ISSUE TITLE
InvokeSignatureHelp command handler blocking LSP's command handler for TypeScript

### ISSUE THREAD

**Issue by uniqueiniquity** [dotnet/roslyn#42338]
**Version Used**: 
3.600.20.15506
**Steps to Reproduce**:
When implementing TypeScript support for signature help via LSP, it seems like the Roslyn command handler for the InvokeSignatureHelp command is getting in the way of LSP's handler.

**Expected Behavior**:
With no ISignatureHelpProvider exported for TypeScript, LSP's command handler for InvokeSignatureHelp should be invoked.
**Actual Behavior**:
Roslyn's command handler is invoked, no-ops because no provider is found, and LSP's handler is not invoked.

cc @dibarbet

**Comment by dibarbet** [comment]
Under investigation - currently it looks like signature help results are aggregated between roslyn and LSP when invoked via typing.  However, when invoked manually (cntrl + shift + space), only Roslyn is getting invoked.  Discussing with editor on why this difference exists.

**Comment by dibarbet** [comment]
resolved in https://github.com/dotnet/roslyn/pull/43042
