### ISSUE TITLE
What is the correct way to use CSharp ExtractMethod refactoring through command line?

### ISSUE THREAD

**Issue by nainys-cn** [dotnet/roslyn#42335]
**Steps to Reproduce**:

1. Attempted to call _ExtractMethodAsync_ present in [file](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodBase.cs) through the command line on the following code:

```
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    void Test(int a, int b)
    {
          /* Extraction starts */
          a++; 
          b++;
          a += 2;
          /* Extraction ends */
          b += 3;
          a++;
    }
}
```
 
**Expected Behavior**:
(According to Visual Studio 19)

```
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    void Test(int a, int b)
    {
            /* Extraction starts */
            NewMethod(ref a, ref b);
            /* Extraction ends */
            b += 3;
            a++;
    }

    private static void NewMethod(ref int a, ref int b)
    {
            a++;
            b++;
            a += 2;
    }
}
```

**Actual Behavior**:

```
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    void Test(int a, int b)
    {
          /* Extraction starts */
           return NewMethod(ref a, ref b);
          /* Extraction ends */
           b += 3;
           a++;
    }

    private static Void NewMethod(ref Int32 a, ref Int32 b)
    {
           a++;
           b++;
           a += 2;
    }
}
```
Issues with the above refactored program:
1. Return statement in Test method having void return type.
2. Return type of resulting NewMethod is Void(notice the capital V).

**Comment by CatalinAdlerDF** [comment]
That is odd, when I try that extraction from Visual Studio itself, I get this code, which looks fine to me.

```c#
void Test(int a, int b)
    {
        /* Extraction starts */
        NewMethod(ref a, ref b);
        /* Extraction ends */
        b += 3;
        a++;
    }

    private static void NewMethod(ref int a, ref int b)
    {
        a++;
        b++;
        a += 2;
    }
```

I was under the impression that Visual Studio uses Roslyn for the refactoring actions it supports.

How are you invoking the __ExtractMethodAsync __ method?

**Comment by CyrusNajmabadi** [comment]
Note that ExtractMethod is not exposed publicly for external consumption.  So i assume this is a case where reflection is being used?

Based on the type of code being generated, it sounds like the workspace is not being setup in the proper manner.

**Comment by nainys-cn** [comment]
1. Is there a way to use extract method refactoring from a CLI project? An example use-case might be to build some automation over that refactoring.
2. How to properly set up a workspace to make that work?

**Comment by CyrusNajmabadi** [comment]
> Is there a way to use extract method refactoring from a CLI project?

AFAIK, there is no way to do that.  Sorry!
