### ISSUE TITLE
Refactor Metadata as Source code

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#4234]
I was trying to write a testcase in MAStests with the MetadataAsSourceWorkspace options set to a particular value(to emulate a user setting) and it was difficult to set the option.

I ended up writing the testcase in a different area. 

The implementation of MAS also seems a  little unclean hence some rewrites could make the service looks cleaner and easier to test. For instance,
1. The `MetadataAsSourceFileService` directly creates the `MetadataAsSourceWorkspace` now. If it was created by a service then we can create a `TestMetadataAsSourceWorkspace` and customize the workspace to emulate a test setting easily.
2. The `MetadataAsSourceWorkspace` is initialized inside [`GetGeneratedFileAsync`](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs,96). We can initialize the workspace way early, given that we only need the MEFHost services to create the workspace and thereby decoupling the workspace initialization.

**Comment by CyrusNajmabadi** [comment]
Closing this out as the code has changed a bunch (especially for decompilation and sourcelink).  We already have test coverage that covers these, so i don't really think we need a tracking issue on this.
