### ISSUE TITLE
Expose IPropertySymbol.AssociatedField

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#42355]
Same as https://github.com/dotnet/roslyn/issues/40103 which covers IEventSymbol.

The only way to detect the existence of the backing field from a third-party analyzer is to find the field in the parent ITypeSymbol.GetMembers() collection and check its AssociatedSymbol property. This means of locating backing fields would disappear if property backing fields (like event backing fields) were removed from `ITypeSymbol.GetMembers()`.

The ability to remove all backing fields from `ITypeSymbol.GetMembers()` solves a binding cycle problem that is blocking one of the design options for https://github.com/dotnet/csharplang/issues/140. If `IPropertySymbol.AssociatedField` was exposed, it would enable removing all backing fields from GetMembers() rather than just event backing fields. That would enable the preferred syntax for https://github.com/dotnet/csharplang/issues/140.

/cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Note: ths is desirable no matter what.  The current approach consumers need to take today to determine if a prop is an auto-prop is to iterate *all* fields, and see if any of htem have the prop as their `AssociatedSymbol`.  This is really inefficient and unfortunate given that the data is already on the property itself.

**Comment by jnm2** [comment]
I'm far away from this use case. Feel free to reopen if folks come along with the same request.
