### ISSUE TITLE
"Run Code Analysis" duplicates violations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#42350]
**Version Used**: 
Version 16.6.0 Preview 2.0 [29911.137.master]

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 237cce27c979609b92de208e9befaf42814fcf35`
4. `ProjectSystem.sln`
5. Right-click on ProjectSystem.sln and choose Analyzer and Cleanup -> Run Code Analysis

**Expected Behavior**:
Error not be duplicated

**Actual Behavior**:
Every violation is duplicated

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1006	Naming rule violation: The first word, 'Resources', must begin with a lower case character	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\Resource.vb	2441	Active
Error	IDE1006	Naming rule violation: The first word, 'Resources', must begin with a lower case character	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\Resource.vb	2441	Active
Error	IDE1006	Naming rule violation: The first word, 'Resources', must begin with a lower case character	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceComparerForFind.vb	48	Active
Error	IDE1006	Naming rule violation: The first word, 'Resources', must begin with a lower case character	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\ResourceEditor\ResourceComparerForFind.vb	48	Active
```

**Comment by mavasani** [comment]
Thanks for filing the issue @davkean - just to confirm, do you get duplicate issues only with "Run Code Analysis" or also with "Build" and/or live background analysis. I am going to investigate the issues you reported tomorrow. Thanks!

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/41687
