### ISSUE TITLE
"Enforce file header" is not enforced on files that are not open

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#42353]
**Version Used**: 

**Steps to Reproduce**:
Turn on:

![image](https://user-images.githubusercontent.com/1103906/76485203-f8690100-646f-11ea-9888-a1836bdc0f72.png)

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout e640313c10e98894c58b69b1fa38412672405d1e`
4. `ProjectSystem.sln`
5. Open c:\project-system\.editorconfig and change 'file_header_template' to "FooBar" and save

**Expected Behavior**:
Thousands of errors about copyright header to appear in Error List

**Actual Behavior**:
No errors, if you build or open a file you start seeing errors.

**Comment by mavasani** [comment]
I figured out the root cause and will have a fix soon. As a workaround, adding the entry that enables IDE0073 on build via a ruleset file instead of editorconfig file should avoid this issue.
