### ISSUE TITLE
Add VB option to control whether completion auto-shows in completion lists

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#42369]
It currently shows all the time in VB, and prior to us [adding an option](https://github.com/dotnet/roslyn/pull/42035) for C# to do this, it never showed in C#.

So now that C# users get a choice, we could also give that choice to VB customers.

**Comment by dpoeschl** [comment]
While parity would be nice here, I'm not sure we've heard requests for this from VB users.

**Comment by CyrusNajmabadi** [comment]
Closing out as we've heard no requests fro this.
