### ISSUE TITLE
'Suppress or Configure Issues' code action appears with non-configurable IDE0005 diagnostic

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#42375]
Using the latest Int Preview version (29911.183.master), the Suppress and Configure code action appears with IDE0005 (remove unnecessary usings) despite the diagnostic being tagged as non-configurable.

``` C#
using System;
using System.Collections.Generic;
using System.Text;

class Test
{
}
```

The new severity/diagnostic does appear in the error list, but no squiggle appears.

**Comment by allisonchou** [comment]
Tagging @mavasani

**Comment by mavasani** [comment]
@allisonchou It seems that not all the decriptors in the analyzers are marked as not-configurable: http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs,53
