### ISSUE TITLE
MemberNotNull could have a fancier completion experience

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#42377]
With the new [MemberNotNull attribute](https://github.com/dotnet/runtime/issues/31877), you're almost always going to be doing nameof and then a member. It seems like there's a few improvements we could make here:

1. We could autoselect nameof() in this context, since it's likely what you're going to type.
2. We could also directly add nameof(membername) entries for all members as well. This would mean you could type a member name and the nameof could effectively be completed for you.
3. We could potentially filter out the member list to exclude types and a few other things so you see just in-scope members.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
