### ISSUE TITLE
vb indent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42381]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/946011/vb-indent.html)._

---
I would like to be able to override the default indentation for statements with multiple arguments. I prefer the style where the second and subsequent lines default to indenting one tab stop, rather than lining up with the first argument in a method call.

---
#### Visual Studio Feedback System on 3/12/2020, 05:19 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
The Visual Basic formatter is "highly opinionated", where the only real options are the type of indentation (tabs vs. spaces) and the size of hard tabs. At this time, there are no plans to introduce a configurable formatter for this language.
