### ISSUE TITLE
Place using statements at lowest scope

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42382]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/945522/place-using-statements-at-lowest-scope.html)._

---
Under Tools > Text Editor > C#, there are options to place the System namespaces first.  But we should have an option to move the using statements to the lowest scope (which basically means popping them inside the namespace).

This was available in the 2017 Power Tools.... it should be in the full IDE.

---
#### Visual Studio Feedback System on 3/11/2020, 03:33 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This option already exists. See https://github.com/dotnet/roslyn/issues/23586#issuecomment-595620956 for an example.
