### ISSUE TITLE
Automatic ternary conversion for "true-/false-" valued cases

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42380]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/943260/automatic-ternary-conversion-for-true-false-valued.html)._

---
When converting two bool `return`s into a ternary, explicit secondary `false`-valued case should be elided, since the `false` case already yield the `false` value anyway.
```
private bool MyMethod() { if (a) return b; return false; }
private bool MyMethod() { return (a) ? b : false; } // standard
private bool MyMethod() { return (a) && b; } // proposed
```
Same happens with primary `true` in `if (a) return true; return b;`:
`return (a) ? true : b` might as well be `return (a) || b;`.

That tiny request could save me tons of actual work, and make code refactoring a bit more concise. :)

---
#### Visual Studio Feedback System on 3/10/2020, 02:45 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This work was done.  Closing out.
