### ISSUE TITLE
InteractiveWindow.UIThreadOnly.SubmitAsync trims history entries

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4239]
I believe the original intention was to trim off a newline inserted by the window, but it will also trim off any trailing whitespace typed by the user.  We should probably retain the user's input exactly.

**Comment by amcasey** [comment]
FYI @ManishJayaswal

**Comment by ManishJayaswal** [comment]
We don't want to add two consecutive entries in the history that differ only by whitespaces so perhaps we should trim entries all the time before adding it to the history.

**Comment by tmat** [comment]
@ManishJayaswal I don't see much benefit in special casing that. If the user executes a command twice it will be twice in the history. That's ok. cmd.exe has the same behavior.

**Comment by tmat** [comment]
I think we should store the input to history as it was written, without alteration.

**Comment by ManishJayaswal** [comment]
I did not know that cmd.exe has the same behavior. We should do the same.
