### ISSUE TITLE
VS Search method items are missing signature info

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#42391]
**Version Used**: 
16.6 Int Preview

**Steps to Reproduce**:

1. Creates a project with multiple overloads of the same method.
2. Search for said method

**Expected Behavior**:
Items are distinguishable via signature information.

**Actual Behavior**:
Items are missing parameters and other signature info and look identical. Since the LSP code path powers GoTo in VS Online scenarios, this repros there as well.

![image](https://user-images.githubusercontent.com/5387680/76653538-12fdb180-6526-11ea-897d-a49afb777486.png)

**Comment by jinujoseph** [comment]
We need support from LSP protocol for this request.

**Comment by CyrusNajmabadi** [comment]
We are not supporting this search experience.  We support Go-To and AIOSP
