### ISSUE TITLE
.NET\C# Async constructor request\proposal

### ISSUE THREAD

**Issue by Romfos** [dotnet/roslyn#42422]
Hi, 

Nowadays most of API have async implementation and day by day became hard to use it in constructor

What do you think about async consturctors?

I think it will be very useful feature in .NET 5\C# 9 feature for every type of applciation

For example:
```
class Foo 
{
  async Foo(int x)
  {
  }
}

class Bar : Foo 
{
  async Bar(int x) : base(x)
  {
  }
}

Bar bar = await new Bar(1)
ConstuctorTask<Foo> foo = new Foo(1)
```

**Comment by davidfowl** [comment]
See https://github.com/dotnet/csharplang/issues/419

**Comment by CyrusNajmabadi** [comment]
Closing.  This is a dupe of dotnet/csharplang#419
