### ISSUE TITLE
Expose Rolsyn IDE features through LSP

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42427]
Using as the top level feature for tracking all work here.  A lot of this may already have been done, but we can use this to track total completeness.

- [x] Todo comment service
- [ ] Indentation
- [ ] highlighting
- [ ] outlining
- [ ] line separators
- [ ] navigate to
- [ ] comment/uncomment
- [ ] quickinfo
- [ ] brace matching
- [ ] classification

**Comment by tmat** [comment]
Related to TODO comment service: https://github.com/dotnet/roslyn/issues/42188

**Comment by dibarbet** [comment]
Client issue tracking todo comments (external) - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1537470

**Comment by CyrusNajmabadi** [comment]
Closing out as this work has essentially been done.
