### ISSUE TITLE
How to add project nodes automatically? (a question that has been bothering me for a long time) is there any example?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#42439]
I'm using roslyn for dynamic compilation, but I need to add.

```
//console and destop app
< PreserveCompilationContext > true < / PreserveCompilationContext >

//new asp.net core
< PreserveCompilationReferences > true < / PreserveCompilationReferences >

//old asp.net
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
```  

These nodes are in the project file .csproj. 
Is there any way to generate it automatically? Or add it automatically after downloading from nuget.

**Comment by tmeschter** [comment]
@NMSAzulX If you create a NuGet package, you can place those properties in a {PackageName}.props file in the package `build` directory. Any project that ruses the NuGet package will then automatically import the .props file.

There is a little more information about this at https://docs.microsoft.com/en-us/nuget/release-notes/nuget-2.5#automatic-import-of-msbuild-targets-and-props-files.

**Comment by NMSAzulX** [comment]
@tmeschter Thanks~ 
Is there an example? I can't work with the following code :

xxx.props : 
```
<Import>
  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
</Import>
```

**Comment by tmeschter** [comment]
@NMSAzulX Your .props file would need to look like this:

``` xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
</Project>
```

**Comment by NMSAzulX** [comment]
@tmeschter  Thanks,  I found some code.   
I have published four versions nugetpack to experiment in turn. :)

**Comment by NMSAzulX** [comment]
@tmeschter  Hello , Is this right? 
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
      <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>
</Project>
```
![image](https://user-images.githubusercontent.com/16236903/76792373-e4b9f380-67fd-11ea-8d95-5244daa2cacd.png)

**Comment by NMSAzulX** [comment]
I succeeded, but I got a problem. `< PreserveCompilationContext > true < / PreserveCompilationContext >` works in ConsoleApp, but `< PreserveCompilationReferences > true < / PreserveCompilationReferences >` doesn't work in asp.net core3.1.  @tmat @tmeschter

**Comment by NMSAzulX** [comment]
@tmeschter  Hello, Do you know how to solve this problem?

**Comment by tmeschter** [comment]
@NMSAzulX Sorry, but I am not familiar with `PreserveCompilationContext` or `PreserveCompilationReferences`, or how they affect the build. I see you've already opened an issue in the dotnet/aspnetcore repo, and I think that's your best bet.

**Comment by NMSAzulX** [comment]
@tmeschter  OK. Thank you. :)
