### ISSUE TITLE
Expose internal API CodeAction.CodeActionPriority 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#42431]
See https://github.com/dotnet/roslyn/pull/42421/files#r392606860. We have bunch of IDE code fixes that want to register a low priority action. This cannot be done once these are moved to CodeStyle NuGet package as `CodeAction.CodeActionPriority` is an internal API. We may want to expose some way for code actions to declare as being a low priority action, without allowing them to bump themselves to declare as a high priority action.

potential API shape:

```c#
+    public enum CodeActionPriority
+    {
+        Lowest = 0,
+        Low = 1,
+        Default = 2,
+        High = 3,
+    }

    public class CodeAction
    {
+        public CodeActionPriority Priority { get; }
+        protected virtual CodeActionPriority ComputePriority();
    }

+    public enum CodeActionRequestPriority
+    {
+        Lowest = 0,
+        Low = 1,
+        Default = 2,
+        High = 3,
+    }

    public class CodeRefactoringProvider
    {
+        public CodeActionPriority Priority { get; }
+        protected virtual CodeActionPriority ComputePriority();
    }

    public class CodeFixProvider
    {
+        public CodeActionPriority Priority { get; }
+        protected virtual CodeActionPriority ComputePriority();
    }
```

**Comment by CyrusNajmabadi** [comment]
Moving this to next API review. Adding suggestions.

**Comment by 333fred** [comment]
### API Review

* Not exposing high pri for safety of the core system
* Validating inputs, 3 is not an option
    * Is the validation necessary?
    * People who want to replace our high-pri refactorings with their own?
    * Ship as-is with validation, wait for use cases?
    * Clamp instead? Would allow future version to clamp higher without a breaking change.

**Conclusion**: Approved, clamp higher values to highest public value.

**Comment by CyrusNajmabadi** [comment]
I'll do the impl work on this.
