### ISSUE TITLE
Intellisense: Suggested type after new does not include array type

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#42441]
**Version Used**: VS 16.5 preview 3

**Steps to Reproduce**: 

In VS
1. Type `List<int> x  = new `
2. Intellisense suggexts `List<int>`
3. Type `int[] x = new `
4. Intellisense suggests `int`

**Expected Behavior**: Intellisense suggests `int[]`

**Actual Behavior**: Intellisense suggests `int`

**Comment by YairHalberstadt** [comment]
@sharwell 
Why is this by design?

**Comment by CyrusNajmabadi** [comment]
This is by design so that hte user can type `int[] x = new int[some_expr];`.  Basically, we don't want to jump you past the point where you might still want to be adding your own code.
