### ISSUE TITLE
#loaded code is not exposed in the IDE

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4245]
Suppose I have a file test.csx:

```C#
class C { }
```

Then, in the Interactive window I ```#load "test.csx"```.  From then on, ```C``` should be in scope in the Interactive window.  However, it appears that it is only available during compilation.  That is, an expression like ```typeof(C)``` evaluates correctly, but usages of ```C``` are squiggled and ```C``` is never offered by completion.

**Comment by amcasey** [comment]
Part of #3785.

**Comment by amcasey** [comment]
FYI @KevinH-MS

**Comment by amcasey** [comment]
```InteractiveEvaluator.LoadCommandAsync``` appears to depend on ```RemoteExecutionResult.ResolvedPath``` which doesn't seem to be set by any caller.

**Comment by amcasey** [comment]
In ```InteractiveHost.Services.ExecuteFileAsync```, we probably need to pass ```fullPath``` to ```CompleteExecution``` as ```resolvedPath```.

**Comment by KevinH-MS** [comment]
Should be fixed by PR #4346.

**Comment by KevinH-MS** [comment]
Fixed by commit f1702c92cbdb952d8d62e49d11a0f018fe002036

**Comment by amcasey** [comment]
Confirmed that we get completion (etc) for symbols from ```#load```.
