### ISSUE TITLE
Additional tests for native integers

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42452]
Add tests for missing scenarios with native integers:
- Type unification of `I<System.IntPtr>` and `I<nint>`
- Decimal conversions, particularly in expression trees: see uses of `LocalRewriter.DecimalConversionMethod`
- Common type between `nint` and `System.IntPtr`
- When `nint` and `System.IntPtr` are bounds in type inference, which wins?

**Comment by cston** [comment]
- Type unification of `I<System.IntPtr>` and `I<nint>` https://github.com/dotnet/roslyn/pull/48349
- Common type between `nint` and `System.IntPtr` https://github.com/dotnet/roslyn/pull/48266
- When `nint` and `System.IntPtr` are bounds in type inference, which wins? https://github.com/dotnet/roslyn/pull/48266

**Comment by jaredpar** [comment]
Is this still needed?

**Comment by cston** [comment]
The remaining work is the following, which should be covered by https://github.com/dotnet/roslyn/issues/58256:

> - Decimal conversions, particularly in expression trees: see uses of `LocalRewriter.DecimalConversionMethod`
