### ISSUE TITLE
"Use pattern matching" no longer has a Fix All

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#42461]
Version: 
Version 16.6.0 Preview 2.0 [29915.8.master]

![image](https://user-images.githubusercontent.com/1103906/76730886-48b5cb00-67b0-11ea-8048-8590cf255878.png)

**Comment by CyrusNajmabadi** [comment]
This is by design.  This is the version of 'use pattern matching' that is a refactoring (since it has to makeup a fresh name).  This is opposed to other forms that see a name already assigned to the user, and thus can know the better form to fix in bulk.

**Comment by davkean** [comment]
As per Cyrus.
