### ISSUE TITLE
Array index exception occurring at the wrong place with await

### ISSUE THREAD

**Issue by GSPP** [dotnet/roslyn#42464]
It seems that an `IndexOutOfRangeException` can occur in the wrong place when `await` is used on the RHS of an assignment. Normally, the LHS should be evaluated before the RHS. When the RHS contains an `await`, this await is evaluated before the LHS.

        public static void AwaitArraySideEffects()
        {
            async Task M()
            {
                var a = new AwaitArraySideEffectsStruct[10];

                try
                {
                    Console.WriteLine("Testing without await...");
                    a[30].X = F(); //Exception before F()
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }

                Console.WriteLine();

                try
                {
                    Console.WriteLine("Testing with await...");
                    a[30].X = await FASync(); //Exception after F()
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
            }

            int F()
            {
                Console.WriteLine("F");
                return 7;
            }

            async Task<int> FASync()
            {
                Console.WriteLine("FASync");
                return 7;
            }

            M();
        }

Console output:

> Testing without await...
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at x.<<AwaitArraySideEffects>g__M|46_0>d.MoveNext() in x.cs:line 0
> 
> Testing with await...
> FASync
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at x.<<AwaitArraySideEffects>g__M|46_0>d.MoveNext() in x:line 1986

It is my understanding that the two cases should print the same output. In the non-await case, `F` is never called.

An unrelated issue might be that the line number in the first exception is incorrect.

**Version Used**: Visual Studio 2019 16.4.5, .NET 4.8, Release Mode.

**Comment by YairHalberstadt** [comment]
I cant reproduce with the following console application:

```csharp
using System.Threading.Tasks;
using System;

public class AwaitArraySideEffects
{
    public int X {get; set; }
    static async Task Main()
    {
        var a = new AwaitArraySideEffects[10];

        try
        {
            Console.WriteLine("Testing without await...");
            a[30].X = F(); //Exception before F()
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }

        Console.WriteLine();

        try
        {
            Console.WriteLine("Testing with await...");
            a[30].X = await FASync(); //Exception after F()
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    static int F()
    {
        Console.WriteLine("F");
        return 7;
    }

    static async Task<int> FASync()
    {
        Console.WriteLine("FASync");
        return 7;
    }
}
```

Can you please post a valid program displaying this issue?

Thanks

**Comment by svick** [comment]
@YairHalberstadt I can reproduce it by changing the property to a field:

```c#
using System.Threading.Tasks;
using System;

public class AwaitArraySideEffects
{
    public int X;
    static async Task Main()
    {
        var a = new AwaitArraySideEffects[10];

        try
        {
            Console.WriteLine("Testing without await...");
            a[30].X = F(); //Exception before F()
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }

        Console.WriteLine();

        try
        {
            Console.WriteLine("Testing with await...");
            a[30].X = await FASync(); //Exception after F()
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    static int F()
    {
        Console.WriteLine("F");
        return 7;
    }

    static async Task<int> FASync()
    {
        Console.WriteLine("FASync");
        return 7;
    }
}
```

This prints:

```
Testing without await...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AwaitArraySideEffects.Main() in C:\code\tmp\hwapp\Program.cs:line 14

Testing with await...
FASync
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AwaitArraySideEffects.Main() in C:\code\tmp\hwapp\Program.cs:line 26
```

**Comment by GSPP** [comment]
Yes, it must be a field so that the C# compiler uses `ldelema` to obtain a managed point to it, and then mutate the field directly through that pointer.

I came up with this case because I thought: How can a managed pointer be stored across an `await` point? That seems impossible. So I think the fix will have to involve synthesizing a dummy array access just to trigger the range check at the right time.

**Comment by GSPP** [comment]
Is this fixed in Roslyn master? When I look at the decompiled code on sharplab.io it looks to me like it's not fixed.

![image](https://user-images.githubusercontent.com/12032350/80872316-6502be00-8cb1-11ea-93d9-91ab650cf53c.png)

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMBWAbl1xQGZi1CBhQgb10I8/rXc7Zy5cUADmIA2QgFkAFAEpeg1gsWcAbhASEIhALyEAdnADuhAIJGIASximECCAE8AypYAmcAKIAzL3ADGMFBOMAgArgEA2hj4ALqUOMoqhAD0AFQhDokq/ElJJACc0gBEACpwsJb6AOaERtYAFgD2oTDE+QB0nUWy8bkqEBE0se0AGrqEAGJy5CnJHgAefnAADjCWjfqEwHBejQhwk3JZigC+x4J+EDB+9YTSC0ur65tw8/ICfUofn5wF0q89c5cM4Jb65P49VLJKhgpIZIF8BGKP6lcpraq1BptTrtbq9H6cAZDGKjcYofKTUxOBz6PzTWYPFZrDZaLzwTRTd4/EE/S7XW73RZM56EAFIr4E34YQoA/F9HkqEHnSqtTnnHKfFETPHilAAdkIerlgiVsN+ohQYgAPCqAHyU6m0o5mjgavpaqk0vw6l2CfWG43AmFJGSAsEghUcZSwMIBMwWay2ezONyeHz+QLBWOtFjEOgqwgjGYnIA

**Comment by 333fred** [comment]
Sharplab is several months old at this point. It is fixed in master.
