### ISSUE TITLE
Default interface implementations, covariance and lambdas won't play together

### ISSUE THREAD

**Issue by danielearwicker** [dotnet/roslyn#42469]
In .NET Core 3.1, a minimal repro. In a console app put this:

```cs
public interface IThing<out T>
{
    T Get();

    string GetString() => new Func<T, string>(o => o.ToString())(Get());
}

public class Thing<T> : IThing<T>
{
    private readonly T _val;

    public Thing(T val) => _val = val;

    T IThing<T>.Get() => _val;
}

internal class Program
{
    private static void Main(string[] args)
    {
        IThing<string> t = new Thing<string>("hi");

        Console.WriteLine(t.GetString());
    }
}
```

This compiles fine but throws a type loader exception at runtime:

> System.TypeLoadException: 'Could not load type '<>c' from assembly 'BugRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it declares a covariant or contravariant type parameter and is not an interface or delegate.'

I've written `GetString` in a convoluted way just to force use of a lambda. If it is replaced with the equivalent:

```cs
 string GetString() => Get().ToString();
```

then the problem does not occur. The presence of the lambda causes the compiler to generate a hidden class that implicitly depends on the interface's covariant type parameter `out T`, and as the exception says, classes aren't allowed to depend on covariant type params.

**Comment by jaredpar** [comment]
Let's start with compiler, most likely cause here.

**Comment by YairHalberstadt** [comment]
This has been fixed on the master branch:

**Comment by AlekseyTs** [comment]
Looks fixed to me too, the repro code runs as expected in dogfood build of VS. Likely fixed by https://github.com/dotnet/roslyn/pull/39839.
