### ISSUE TITLE
Renaming a function with numerical digits in its name will focus the cursor behind the first one

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42476]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/949230/renaming-a-function-with-numerical-digits-in-its-n.html)._

---
After renaming a function that contains numerical digits in its new name, the cursor will foucs right before the first numerical digit. For instance:

Renaming a function to `Function1` will make the cursor focus between the "n" and the "1", looking like this: Function|1 (| indicates the cursor's position in INS mode).

---
#### Visual Studio Feedback System on 3/15/2020, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The whole name is selected.
