### ISSUE TITLE
Class View shows classes as derived but they are not

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42478]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/948201/class-view-shows-classes-as-derived-but-they-are-n.html)._

---
In the following simple source (the whole project attached):

```
class AttributeDef { };
class AttributeDef_ConditionedBase : public AttributeDef { };
class AttributeDef_Bool : public AttributeDef_ConditionedBase { };
class AttributeDef_Int : public AttributeDef_ConditionedBase { };

class Base { };
class Derived : public Base { };
class Derived2 : public Derived { };
```

Class View shows that `AttributeDef` has derived types `AttributeDef_ConditionedBase` (correct) but also `AttributeDef_Bool`, `AttributeDef_Int` (incorrect). I think it is a bug. Only `AttributeDef_ConditionedBase` should be displayed as derived for `AttributeDef`.

For exactly the same situation with `Base`, `Derived` classes below in the code VS works fine. Class View correctly shows that `Base` has derived only `Derived` and `Derived` has derived `Derived2`.

Please see attached project and screenshot.

---
#### Visual Studio Feedback System on 3/13/2020, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by linette-zyy** [comment]
https://developercommunity.visualstudio.com/content/problem/914518/i-do-not-see-class-class-view-in-window-at-vs2019.html

**Comment by sharwell** [comment]
This turned out to be a C++ issue, so moving back to that team.
