### ISSUE TITLE
Typing over a new code snippet might cause duplication of characters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42477]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/949221/typing-over-a-new-code-snippet-might-cause-duplica.html)._

---
Here’s how you can reproduce this bug:
1. Open a C# project.
2. Find a place in your code where you can insert a “for” command and start typing “for”.
3. Immediatelly after pressing the ‘r’ key tap the ‘tab’ key twice to inswer a new code snippet.
4. Immediatelly after the snippet is inserted, highlight with the whole snippet (or just its first line).
5. Type in some text to replace the snippet and you should see that whatever you’re typing is duplicated.

It might also work with other languages or other kind of snippets but so far I only noticed it happens with the “for” code-snippet.

---
#### Visual Studio Feedback System on 3/15/2020, 07:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing legacy snippet experiences.
