### ISSUE TITLE
Rename tracking dotted border appears in Miscellaneous Files

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#42490]
**Version Used**: 16.5.0 RTW

**Steps to Reproduce**:

1. Open a .cs file outside of a project, so it appears in Miscellaneous Files.
2. Find a class in it, and start changing the name of the class by typing a few letters.

**Actual Behavior**: The dotted border appears around the identifier, indicating that rename tracking is active:

![image](https://user-images.githubusercontent.com/201340/76814818-0e9cf700-67b9-11ea-8fd3-d4ea347bf52d.png)

**Expected Behavior**: It doesn't appear, since it can't be invoked.

We don't let you invoke, but it looks like the state machine is still running.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
