### ISSUE TITLE
Compiler doesn't see that `array?.Length != 0` means array is non-null

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42496]
**Version Used**: 
C# Tools   3.6.0-2.20155.6+3a6e99414ed903c670a8e5c1d1da9c45660f8479

**Steps to Reproduce**:
```C#
#nullable enable
using System;
public class C {
    public void M<T>(T[] array) {
        if (array?.Length != 0)
        {
            int len = array.Length;
        }
    }
}
```
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+BiAdgVwDZ4CGweMABDFsaQLABQAAgEwCM9DAzGc2QMJkBvemRHcuDFGQCyAHgAqAPgAUcgNoBdMoShRCATwCUg4aNMBLAGZkl23XoD8AOgAylAOYAXABZkAhAF4yAAYDE1MRITpw6LIzLA8yUiwyQNt9F3dvAG4w8IBfXIK6PKA===

**Expected Behavior**:
No warnings.

**Actual Behavior**:
`warning CS8602: Dereference of a possibly null reference.` on the `array.Length` access.

cc: @jcouv, @cston

**Comment by stephentoub** [comment]
Oops, ignore this.

**Comment by sharwell** [comment]
For anyone wondering, the `>` and `!=` operators behave very differently in this case. The following two would be equivalent for arrays:

1. `array.Length != 0`
2. `array.Length > 0`

However, when _null_ is involved, we have this:

1. `(int?)null != 0`: **true**
2. `(int?)null > 0`: **false**
