### ISSUE TITLE
Add a fixer for WRN_MissingNonNullTypesContextForAnnotation

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#42509]
Scenario:

```cs
class C
{
    void M(object? obj) // warning CS8632: nullable annotation outside of nullable context
    {
    }
}
```

The possible fixes here include:
- wrap `M` in `#nullable enable/restore` directives
- wrap `C` in `#nullable enable/restore` directives
- add `#nullable enable` at the top of the file (directly before the first using directive)
- add `<Nullable>enable</Nullable>` to the project

**Comment by jcouv** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/30099 ?

**Comment by RikkiGibson** [comment]
sure looks that way :smile: although that issue is phrased in terms of the old attribute approach (pre-`#nullable` directive). Feel free to close if this seems redundant.

**Comment by jcouv** [comment]
I'll close the old issue instead. New one matches new design. Thanks

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
