### ISSUE TITLE
CopyTypeCustomModifiers() should copy NativeIntegerAttribute values

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42500]
`CustomModifierUtils.CopyTypeCustomModifiers()` should copy `NativeIntegerAttribute` values.

See https://github.com/dotnet/roslyn/pull/42419#discussion_r393306528, https://github.com/dotnet/roslyn/pull/42419#issuecomment-599756041.

**Comment by AlekseyTs** [comment]
The assert at the end of the method should also be adjusted:
```
Debug.Assert(resultType.Equals(destinationType, TypeCompareKind.IgnoreCustomModifiersAndArraySizesAndLowerBounds)); // Same object/dynamic, nullability and tuple names as destination type.
```
