### ISSUE TITLE
TestMethodSpansWithAttributes in Emit test fails locally.

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#42528]
After many failed attempts in the past 2 years, I finally succeed to build the Roslyn source code, and I am running the 150 thousand tests now, which is taking too long time because it only utilizes about 30% of the processor power in average! (I am using the high performance power plane and hyper threading on my quad-core processor).
So, my question is: can you add an option to the test settings to choose the max no of running testing threads? I want to raise this no to see it this makes things faster.

Edit: 
The usage drooped to 20% and less in average. Though I can't expand the test nodes that have failed tests (by mouse or by menu command). 
I closed VS, reopened it, and waited long enough, Now I can  Expand the nodes :)
An error happens after a while of running the tests making them hang. The message in VS status bar tells me to look to the output pane, put I find no info about the error there. I have to restart VS to restart the tests.

**Comment by jmarolf** [comment]
@kendrahavens I believe this is a test explorer request

**Comment by VBAndCs** [comment]
@jmarolf 
It is more. It is about all unexpected problem I face when I try to deal with Roslyn source code.
For example, this is one failed test. First I expected that I missed some nuget restoration, when I examined this error, I feel it maybe related to system locals or something. These are the test exception details:

> Microsoft.CodeAnalysis.CSharp.DynamicAnalysis.UnitTests.DynamicAnalysisResourceTests.TestMethodSpansWithAttributes
>    Source: DynamicAnalysisResourceTests.cs line 269
>    Duration: 36 ms
> 
>   Message: 
>     
>     Expected:
>     'C:\myproject\doc1.cs' A3-08-94-55-7C-64-8D-C7-61-7A-11-0B-4B-68-2C-3B-51-C3-C4-58 (SHA1)
>     Actual:
>     'C:\myproject\doc1.cs' C5-E6-91-C6-67-A2-E2-75-24-03-6E-78-30-D3-DB-D3-BB-A2-E9-D2 (SHA1)
>     Differences:
>     ++> 'C:\myproject\doc1.cs' C5-E6-91-C6-67-A2-E2-75-24-03-6E-78-30-D3-DB-D3-BB-A2-E9-D2 (SHA1),
>     --> 'C:\myproject\doc1.cs' A3-08-94-55-7C-64-8D-C7-61-7A-11-0B-4B-68-2C-3B-51-C3-C4-58 (SHA1)
>     
>     Expected: True
>     Actual:   False
>   Stack Trace: 
>     AssertEx.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector, String expectedValueSourcePath, Int32 expectedValueSourceLine) line 232
>     DynamicAnalysisResourceTests.VerifyDocuments(DynamicAnalysisDataReader reader, ImmutableArray`1 documents, String[] expected) line 959
>     DynamicAnalysisResourceTests.TestMethodSpansWithAttributes() line 342
> 

There are other 15,000 failed tests, which I can't check all. Maybe if you helped me fix this, most of the others are fixed too.

**Comment by jmarolf** [comment]
@VBAndCs I would first follow all of [these](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md) instructions. I assume your ran the restore script etc?

**Comment by jmarolf** [comment]
@VBAndCs I would also suggest that if you want to have a more conversation style problem solving session you ask on [gitter](https://gitter.im/dotnet/roslyn?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). I imagine you will make more progress that way.

**Comment by VBAndCs** [comment]
@jmarolf 
I followed the instructions,  built the solution, ran it, and got the second hosted VS environment up and running.
I have win 10 and VS.NET (Community Edition) up to date.
Getting 
> 'C:\myproject\doc1.cs' C5-E6-91-C6-67-A2-E2-75-24-03-6E-78-30-D3-DB-D3-BB-A2-E9-D2 (SHA1)

Instead of 
> 'C:\myproject\doc1.cs' A3-08-94-55-7C-64-8D-C7-61-7A-11-0B-4B-68-2C-3B-51-C3-C4-58 (SHA1)

doesn't seem to be a Nuget problem. It seems encoding problem (My local culture is ar-EG).
I wish someone look at this test.
I will also point to this issue in gitter.
But to be sure, I will run the build.cmd again, retest, and get back to you.

**Comment by VBAndCs** [comment]
Same Results. The failed tests still fail. I am changing my local culture now to en-US to eliminate this possibility.

**Comment by VBAndCs** [comment]
No change :(

**Comment by kendrahavens** [comment]
I've opened the issue on Visual Studio to allow users to specify max number of threads devoted to testing here: https://developercommunity.visualstudio.com/idea/954625/allow-user-to-choose-the-max-number-of-running-tes.html

**Comment by VBAndCs** [comment]
@kendrahavens 
Thanks.

**Comment by jmarolf** [comment]
alright, @VBAndCs I am going to change the title of this issue to be about `TestMethodSpansWithAttributes` test that is failing for you. I do not know much about the emit tests myself but hopefully someone else can assist with this specific issue.

**Comment by jmarolf** [comment]
@jaredpar who owns the emit tests and can look into why they are flaky here?

@VBAndCs If you run `Restorre.cmd && Build.cmd && Test.cmd` this test still fails correct? Just want to narrow down the possible variables.

**Comment by VBAndCs** [comment]
@jmarolf
I don't complete the Test.cmd as it shows some failed errors early, so I switched to the test explorer to see what is going on.
the restore and build are completed, and the project runs and I ran an ASP.NET Core project inside the second/hosted VS. But if this can help, I can send you the restore and build reports if you tell me where are they :). Maybe a small error happened in one package or one build.

**Comment by jmarolf** [comment]
can you please let test.cmd complete and take a look at the html file that is created if tests fail

**Comment by VBAndCs** [comment]
Ok. But this will talk too long. Wait for me :)

**Comment by VBAndCs** [comment]
[Roslyn.Tests.Debug.zip](https://github.com/dotnet/roslyn/files/4359673/Roslyn.Tests.Debug.zip)
@ jmarolf 
These are the test reports. The topic now is not about one failed test but 10,000.

**Comment by jmarolf** [comment]
@VBAndCs wow, there are a lot of different failures here. Thanks for the complete test output. I'll look through these. We have a test run on the Spanish locale to (hopefully) catch any issues with people checking in tests that only work in the en-us locale. At first glance I don't see any common cause to the test failures but there are a lot to look at so stay tuned.

**Comment by VBAndCs** [comment]
Is there a restore report and a build report?
They may reveal the source of test failures.
Also, could these failures relate to some missed workload (VC++ for example?) I have the workloads mentioned in the instructions, but perhaps there are more.

**Comment by jcouv** [comment]
@VBAndCs Is this issue still alive for you, or were you able to find the problem? 
As far as I can tell from our CI data, `TestMethodSpansWithAttributes` hasn't been flaky.

**Comment by jcouv** [comment]
Didn't hear back from @VBAndCs. I'm assuming this was resolved, so I'll close. Feel free to ping if still an issue.
