### ISSUE TITLE
package the source file while dotnet  build/package 

### ISSUE THREAD

**Issue by athinboy** [dotnet/roslyn#42525]
What about to package the source file while dotnet  build/package  ? 
For example ,if the output file is  A.dll/A.exe,  we can package source files to A.src/A.dll.src/A.exe.src ,and nuget can download the  *.src file , so the IDE （ VS or VSCode ） can browse the source code.  
This way is done in Java.

Thanks!

#https://github.com/dotnet/roslyn/issues/24349

**Comment by tmat** [comment]
You can already embed sources in the PDB (set `EmbedAllSources` msbuild property to true)

**Comment by athinboy** [comment]
@tmat 
thanks!
but can you  give me some document link about EmbedAllSources ?
because i can find little documen about EmbedAllSources, and it not work .

https://docs.microsoft.com/en-us/search/?search=EmbedAllSources&category=All&scope=.NET&category=All

https://docs.microsoft.com/en-us/search/?search=EmbedAllSources&scope=VS%20IDE&view=vs-2019

https://github.com/ctaggart/SourceLink/issues/192

Is that right? frankly,i feel is too complex . thanks!

<Project>
  <PropertyGroup>
    <BuildDependsOn>EmbedAllFiles;$(BuildDependsOn)</BuildDependsOn>
  </PropertyGroup>
  <Target Name="EmbedAllFiles">
    <ItemGroup>
      <EmbeddedFiles Include="%(Compile.Identity)" />
    </ItemGroup>
  </Target>
</Project>

**Comment by tmat** [comment]
It's easy:
```xml
 <PropertyGroup>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>
```

https://github.com/dotnet/sourcelink/tree/master/docs#embedallsources

**Comment by athinboy** [comment]
@tmat Thanks!
