### ISSUE TITLE
Allow us to increase the max no of testing threads

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#42527]
After many failed attempts in the past 2 years, I finally succeed to build the Roslyn source code, and I am running the 150 thousand tests now, which is taking too long time because it only utilizes about 30% of the processor power in average! (I am using the high performance power plane and hyper threading on my quad-core processor).
So, my question is: can you add an option to the test settings to choose the max no of running testing threads? I want to raise this no to see it this makes things faster.

**Comment by jmarolf** [comment]
duplicate of #42528

**Comment by VBAndCs** [comment]
Sorry, I don't know how it is published twice!

**Comment by jmarolf** [comment]
No worries :)
