### ISSUE TITLE
Using quick actions to make a method async and then synchronous doesn't fully rename in interface

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#42549]
Found by @mattscheffer  repros in 16.3.7 as well 

1.  Create a new C# console app.
2. Inside Program.cs add a new class with the following:

class Foo
{
public void test1()
{
Console.WriteLine("testing async rename");
}
}

3. Click on foo, and use the quick action to extract interface.
4. Inside Program.cs, add "await" to the start of the Console.WriteLine statement.
5. Use the quick action to make the method async. 
6. At this point, you can notice that test1 was renamed to test1Async and the async keyword was added.
7. Inside the interface, verify that test1 is now test1async as well.
8. Back in program.cs, remove the await keyword from the Console.WriteLine line.
9. Click on test1Async, and use the quick action to make the method synchronous. 

**Expected:**
The async keyword is removed, test1Async is renamed to test1 in both Program.cs and the interface file.

**Actual**: 
Async keyword is removed and test1Async is renamed only in Program.cs. The interface file still has test1Async.cs.

If the method is called inside the same code file rather than an interface, it is renamed correctly when performing the make synchronous action.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback on this issue.
