### ISSUE TITLE
Deprecate public property setters on NotificationOption

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#42550]
See https://github.com/dotnet/roslyn/pull/42323#discussion_r392717268 and https://github.com/dotnet/roslyn/pull/42323#discussion_r393036512 and https://github.com/dotnet/roslyn/pull/42323#discussion_r392718306

**Comment by mavasani** [comment]
Also consider marking public option types as sealed. See https://github.com/dotnet/roslyn/pull/42323#discussion_r392717282

**Comment by sharwell** [comment]
Design review conclusion:

* Deprecate public setters and throw an exception if used
* Remove internal setters
* Seal the types
