### ISSUE TITLE
Symbol completion and target-typed new

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#42556]
Typing `C c = new(` (with no space) stays as-is, but typing `C c = new (` (with the space after `new`) completes to `C c = new C(`.
We should confirm whether or not we want that behavior for scenario with space.

Relates to https://github.com/dotnet/roslyn/issues/28489 (target-typed new feature)

**Comment by devhl-labs** [comment]
This is probably what is causing the bug I'm seeing.  Typing `(p => ...` auto-completes to `(prop => ...`  Driving me crazy!

**Comment by jcouv** [comment]
@devhl-labs That is a different issue, but thanks for reporting it. Very annoying indeed. Opened https://github.com/dotnet/roslyn/issues/47662

**Comment by CyrusNajmabadi** [comment]
Yes.  this behavior is working as intended.  Space should preselect the type, no space should use the implicit object form.
