### ISSUE TITLE
ExplicitType and target-typed new

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#42554]
Should we offer some code style options for making the type explicit or implicit in target-typed new?

For example:
- `C c = new();`
- `M(new())`

Interesting scenarios:
- `(int, int) t = new();` (the refactoring should be blocked to avoid producing illegal code, or made smarter to produce a tuple literal)
-  test existing fixers `UseImplicitType` (for example, List<string> list = new(); should never offer to make the declaration `var`)

Relates to https://github.com/dotnet/roslyn/issues/28489 (target-typed new feature)

**Comment by CyrusNajmabadi** [comment]
This feature was added.  We allow the user to say if htey want implicit creation if the type is apparent.  We haven't got requests beyond that.  Seems like the ecosystem prefers it for things like fields, but not for potentially confusing areas like arguments.
