### ISSUE TITLE
Missing suggestion for generic types on unimported types, like `Collection<>`

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#42561]
**Version Used**: 
Community 2019 Preview - Version 16.6.0 Preview 1.0

**Steps to Reproduce**:
1. Create a new file (*.cs)
2. Make sure you don't import `System.Collections.ObjectModel`
3. Write `var test = `
4. Write `new `
5. (popup with suggestion is shown)
6. Write `Collection`
7. Write `<`

**Expected Behavior**:
Automatic show popup with suggestion

**Actual Behavior**:
No popup is shown

**Code**:
```csharp
using NUnit.Framework;
using System.Linq;

namespace MyTestSpace
{
    [TestFixture]
    public class MyTestClass
    {
        [SetUp]
        public void SetUp()
        {
            var _test = new Collection<||>
        }
    }
}

// cursor is on position ||
```

**Workaround:**
Press `Ctrl + Space` when inside `<>`

**Comment by CyrusNajmabadi** [comment]
@dpoeschl maybe an intellicode area?  this is another 'signature+completion' area.  @jinujoseph ?

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by genlu** [comment]
Looks like there's two issues here:
1. We are not automatically trigger completion inside the brackets after `<` is typed (similar to argument list changed by @dpoeschl )
2. As described in https://github.com/dotnet/roslyn/issues/36730, we might commit a non-generic type when `<` is used as a commit char.

**Comment by CyrusNajmabadi** [comment]
The type is suggested.  Being an imported type, it needs to be selected over the other options.  So closing out:

![image](https://user-images.githubusercontent.com/4564579/199331883-52f8ed70-2f8f-478b-a556-ec1bbfb11824.png)
