### ISSUE TITLE
Error list empty -- with steps to reproduce

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42573]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/952292/error-list-empty-with-steps-to-reproduce.html)._

---
Despite many reports of the same problem and announcements that the problem was fixed, it still exists for me with VS2019 16.5.0. The error list is empty but compiling and debugging fails due to an error.

Steps to reproduce:

- Open VS2019
- Create new solution with "Console App (.NET Framework)" project
- Add to Main(): 

    ```csharp
    string s = null;
    Console.WriteLine(s);
    Console.WriteLine(args);
    ```

- No warnings nor errors should be shown at this point
- Open .csproj file and add to first `<PropertyGroup>` section:

    ```xml
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    ```

- Make sure "Error List" is visible
- Run solution
- You'll see a warning: "There were build errors. Would you like to continue and run the last successful build?"
  *BUT THIS ERROR LIST IS EMPTY!*
- Click no and close VS
- Delete ".vs" folder
- Start VS and run. You'll see same warning and this time there is an according entry in the "Error List"
- Click that entry and wait.
  *ENTRY WILL DISAPPEAR!*
- In "Error List" choose "Build Only" to bring back error

I expect that that the error list entry should not disappear. "Build + Intellisense" should include everything that is shown by "Build Only"

---
#### Visual Studio Feedback System on 3/17/2020, 10:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
@mavasani old issue , i have a feeling this should already be fixed

**Comment by mavasani** [comment]
This is an issue only on net472 and older frameworks. Everything works fine on net5 and newer target frameworks.
