### ISSUE TITLE
Generate Equals and GetHashCode doesn't work for partial classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42574]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/950362/generate-equals-and-gethashcode-doesnt-work-for-pa-1.html)._

---
<p>I use a lot of partial classes to organize my code.</p><p>I often use the ‘Generate Equals and GetHashCode’ feature, both very often it doesn’t work.<br> So I have to go through all my class files trying to find the one that will actually execute.</p><p>Usually the first or last one is the one that actually works.</p>

---
#### Fiona Niu[MSFT] on 3/17/2020, 06:55 PM: 

(private comment, text removed)
#### Visual Studio Feedback System on 3/17/2020, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Left this on the Developer-Community site:

---

Hi Daan,

I was unable to repro this issue. Could you supply a larger repro over at

https://github.com/dotnet/roslyn/issues/42574 that explains what you mean? Ideally it would contain an example of the code you're starting with and how you're trying to invoke the "generate equals and gethashcode" feature.

**Comment by DaanV2** [comment]
Hi Cyrus

I made a video showing the problem, as well as including the test project itself

https://www.youtube.com/watch?v=ZqSZ6dEwX9Q&feature=youtu.be

[PartialAlwaysGoingWrong.zip](https://github.com/dotnet/roslyn/files/4359187/PartialAlwaysGoingWrong.zip)

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Good news.  It repros for me.  Now to find out why :)

**Comment by CyrusNajmabadi** [comment]
Got it.  What a nasty one :)
