### ISSUE TITLE
VS 2019 Intellisence not working for Strong-Named assembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/952341/vs-2019-intellisence-not-working-for-strong-named.html)._

---
We have several VB (.net 3.5) projects that have a strong-named assembly "snk" file.
These "snk" files have been there for over 10 years.
These VB projects are being called from C# (.net 4.6.1) projects as "project references" and NOT file references.
Intellisence is not working from inside the C# code when trying to call the VB code.
The projects will compile and run fine but design time errors will not be reported and Intellisence will not work for any of the VB code from inside the C# code.
If we remove this line **<Assembly: AssemblyKeyFile("vbProject.snk")>** from the VB AssemblyInfo.vb then Intellisence works fine.

This seems to only be a VS 2019 problem. VS 2015 and VS 2017 Intellisence is working fine with the "snk" files.

I can provide sample project if needed.

---
#### James Brooks on 3/17/2020, 06:40 AM: 

<p>These projects are really old.<br>For reference... the header in the proj file has "ToolsVersion=4.0"... that is old<br></p><p>Anyway, It seems that "AssemblyKeyFile / snk" inside the VB AssemblyInfo.vb is no longer supported.</p><p>In VS 2019 do the following:</p><ol><li>Remove "AssemblyKeyFile" from the AssemblyInfo.vb</li><li>Right click on the project and go to "Signing"</li><li>Click on the "Sign the assembly" check box</li><li>Select the "snk" file under "Choose a strong name key file"</li></ol><p>Intellisence will now work fine inside the C# project.</p><p>Under the hood it added the following to the "proj" file:</p><ol><li>&lt;AssemblyOriginatorKeyFile&gt;vbProject.snk&lt;/AssemblyOriginatorKeyFile&gt;</li><li>&lt;SignAssembly&gt;true&lt;/SignAssembly&gt;</li></ol><p>These assemblies have been Strong-Named for 10 years but I'm guessing that VS 2019 is now looking at some other attributes that VS 2017 and lower did not need.<br></p><p>Hopefully VS team can determine why this is now required in the proj files.</p>

#### Visual Studio Feedback System on 3/17/2020, 08:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
@davkean Any idea what's going on here?

**Comment by ImGonaRot** [comment]
@genlu Let me know if you need a sample project to show the issue.

**Comment by genlu** [comment]
@ImGonaRot That would be really helpful. Thanks!

**Comment by davkean** [comment]
@genlu This would be Roslyn, it reads the AssemblyKeyFileAttribute.

**Comment by genlu** [comment]
@ImGonaRot Hey, could you please share a sample project? Thanks!

**Comment by ImGonaRot** [comment]
[TestApp.zip](https://github.com/dotnet/roslyn/files/4469840/TestApp.zip)

Here are the instructions to see the issue.
NOTE: Do not edit any files until you have completed all the steps listed below.

1. Open the TestApp.sln in Visual Studio 2017
2. Open VB.Test.Client.Module1.vb and notice that "AddTwoNumbers" has IntelliSense
3. Open CSharp.Test.Client.Program.cs and notice that "AddTwoNumbers" has IntelliSense.
4. Open VB.Test.Library.AssemblyInfo.vb and notice that there is an "AssemblyKeyFile" assigned.
5. Build the solution in VS 2017
6. Go to the Visual Studio developer prompt and change to the directory where the VB.Test.Library.dll is located
7. Run the following command "sn -Tp VB.Test.Library.dll" and notice that there is a public key / token. This means it was Strongly Named.
8. Open the TestApp.sln in Visual Studio 2019
9. Open VB.Test.Client.Module1.vb and notice that "AddTwoNumbers" has IntelliSense
10. Open CSharp.Test.Client.Program.cs and notice that "AddTwoNumbers" does not have IntelliSense.
11. While inside Visual Studio 2019, right click and go to properties of the VB.Test.Library project.
12. Click on the "Signing" menu item
13. Select the "Sign the assembly" and select the "VB.Test.Library.snk" file
14. Save the project change
15. Open CSharp.Test.Client.Program.cs and notice that "AddTwoNumbers" has IntelliSense.

Here is what I have noticed.
Inside the VB.Test.Library.AssemblyInfo.vb you will notice that the "AssemblyKeyFile" path has "..\..\VB.Test\Library.snk" which is an "invalid" path.
Yet, you can see that the dll was signed by using the SN tool.
Seems that older versions of Visual Studio IntelliSense does not care if the dll was strongly signed but VS 2019 does not work unless the path is correct to the snk file.

Single the dll is signed during compile time, I don't understand why VS IntelliSense should care if the dll is strongly signed during "design" time?
Notice that this is a "project" reference and not a direct "dll" reference.

**Comment by mmiloslavski** [comment]
We have a similar situation except for that we use delay signing. Intellisense does not work if the signing information is moved into project files, like this:

  <PropertyGroup Condition="($(OutputType) == 'WinExe' or $(OutputType) == 'Library') and ($(SuppressSignature)=='false' Or $(SuppressSignature)=='')">
    <SignAssembly>true</SignAssembly>
    <DelaySign>true</DelaySign>         <AssemblyOriginatorKeyFile>..\..\..\..\TeamBuildTypes\Build\SoftwarePublisher.key</AssemblyOriginatorKeyFile>
  </PropertyGroup>
Will our problem be resolved in 16.7 too?

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
