### ISSUE TITLE
[Proposal] Embedded Unit Tests

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#42584]
Embedded Unit Tests
I suggest to attach unit tests to each project to :
- encourage developers to write tests.
- make it easy to navigate to the test to modify it after modifying the method it tests.
- make it easy to run and debug the test after modifying the method it tests.
- This will not affect the exe or the compilation time as I will explain.

This is the idea:
- Add an option in the new project dialog to add embedded tests. I suggest to make it checked by default.
- fore each code file added to the project, create a test class. For example: For a class named Class1.cs automatically add a class named Class1.Test.cs. this will make it a sub item under the class1 in the solution explorer.
- For each unit added to Class1 (method, property, etc), automatically create a test method in Class1.test. For example: For a method called Foo, will have a Foo_Test method.
- If Class one contains an internal class or a struct (asy Class2), a separate test class will be created, named Class1.Class2.test.cs
- This way, every test method is linked to its tested method by naming conventions, so VS can add commands to context  menu and  the solution explorer to navigate between each method pair and run and debug the test from any of them.
- The tests are still viewed in the Test explorer window which still works as usual, but we can add a command to each node in the test window to navigate to the tested method.
- When compiling the project, the test classes will be excluded from the output assembly (exe/dll).
- When testing, the test classes will be compiled in a separate a assembly as if they are in a separate test project that has a ref to the tested project.

Note: 
I sent this to developer community also, because I am not sure who is responsible for unit tests. If you like the idea, please vote fot it there:
https://developercommunity.visualstudio.com/idea/956194/embedded-unit-tests.html

**Comment by YairHalberstadt** [comment]
Firstly, Roslyn isn't the right place for this - developer community sounds better
This sounds like the sort of thing that is
a) Extremely useful for some people, and styles of workflow
b) highly opinionated
As such I think it would make for a great VS extension, but might not belong in the core VS product itself.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.

**Comment by VBAndCs** [comment]
@YairHalberstadt 
Thanks for your positive feedback. 
The 150k tests in Roslyn gave me this idea. I need to navigate from the test to the source, so I thought of some sort of attribute to link them, then askem my self why can't we make rhem closer?

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
Can you add an attribute to link the test method with the tested method, and a context menu command to navigate between them back and forth?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Can you add an attribute to link the test method with the tested method, and a context menu command to navigate between them back and forth?

Sure, i think you could build such a thing. It wouldn't be too hard as an extension author. Good luck!
