### ISSUE TITLE
LanguageServices.CSharp.UnitTests tests are crashing and causing build flakiness

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#42588]
Failing builds: 
- https://dev.azure.com/dnceng/public/_build/results?buildId=563228&view=results

The crash appears to occur on xunit shutdown. The actual log file for the tests indicates that everything succeeded. But xunit is exiting with a failure code and no output.

**Comment by sharwell** [comment]
FatalExecutionEngineError

**Comment by sharwell** [comment]
@jaredpar has this occurred recently?
