### ISSUE TITLE
More consistent naming of Roslyn related OOP services

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#42582]
We are not entirely consistent in naming OOP services. We should standardize on `Roslyn*` for all services using our ServiceHub infrastructure.

Current names:
- `ManagedLanguage.IDE.RemoteHostClient`
- `pythia`
- `CodeLens`
- `roslyn*`
etc.

**Proposal**

- Names should be specific enough to allow easy identification of the owning team.
- Names should not use "remote" or "service" words since these are all remote services.
- Names should use PascalCasing.

**Update for ISB**

- IServiceBroker services need to be defined in namespace to avoid collisions.
- Service namespace for Roslyn is `Microsoft.CodeAnalysis`, so instead of `Roslyn` prefix we'll use `Microsoft.CodeAnalysis.{ServiceName}`. 
- Partner teams should define their own IServiceBroker services in their own namespace without relying on Roslyn remoting infrastructure.

**Comment by tmat** [comment]
Not relevant anymore since we have moved to IServiceBroker.

**Comment by CyrusNajmabadi** [comment]
@tmat  is there anything left to do here?  If so, can you reopen.  But we should assign toa  dev/milestone for this to be done.
