### ISSUE TITLE
Local function scope hiding - Is this an issue with the Roslyn compiler, or is this expected behaviour?

### ISSUE THREAD

**Issue by Kolichikov** [dotnet/roslyn#42597]
**Version Used**: 
Roslyn 3.4
.NET 4.7.2
**Steps to Reproduce**:
Sample code:
```
using System;
public class Program
{
	public static void Main(string[] args){
		int x = 0;
		void foo(){
			int x = 0;
			x = 1;
			Console.WriteLine(x);
		}
		foo();
		Console.WriteLine(x);
	}
}
```
I encountered the issue in Unity first, but taking this to dotnetfiddle, I see that if I use Roslyn 3.4 or .NET Core 3.1, I get 

> 1
> 0

as expected, but using .NET 4.7.2, I get error CS0136:

> A local or parameter named 'x' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

Is Roslyn behaving as expected here? The documentation I found didn't help me understand which one is correct. Are they even supposed to match in the first place?

**Comment by CyrusNajmabadi** [comment]
Roslyn behavior is expected.  We updated the language to allow hiding of local vars when local-functions are involved.  It's likely that that is only for newer langauge-versions though.

**Comment by gafter** [comment]
This is by design.  See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/shadowing-in-nested-functions.md
