### ISSUE TITLE
Discussion: A new type of iterator construct

### ISSUE THREAD

**Issue by mburbea** [dotnet/roslyn#426]
Enumeration using the `foreach` construct in .net is performed via one of 4 ways.
1. Pattern matching. If your object has a method `GetEnumerator()` that returns something that has both a `bool MoveNext()` and a `Current` property, C# will use it. Performance-minded collection writers will implement this mechanism and use a struct to avoid allocation, and avoid the extra indirection and overhead of interface calls.
2. `IEnumerable`, the pre-generics mechanism for iteration One single method that returns an `IEnumerator` that has a `MoveNext` and `Current` . But still necessary when you know you have a collection but you can't specify which type it is over. 
3. `IEnumerable<T>`, the preferred mechanism in .the CLR since .net 2.0. A strongly typed interface returns `IEnumerator<T>` that has a `MoveNext` and a `T Current`. It extends both `IEnumerable` for legacy purposes, and `IDisposable` allowing a user to tie resource life-cycle to iteration. 
4. Be a `T[]`. While an array implements  `IEnumerable<T>`, when you foreach the compiler performs a bit of translation and turns it into a `for(...)` loop. 

However, all approaches have issues. 
1. The Reset method is rarely implemented. IDisposable aspects are rarely used, but still need to be implemented and are called every single time. It'd be nice to be able to opt-in to these features. Even in roslyn they declared an interface without the IDisposable baggage to avoid the extra call overhead.
2. Interface calls have extra overhead, and for every element you need to do 2 interface calls.
3. Pattern matching seems to solve some of the performance annoyance, but only allows you to use `foreach`. It does not work if your object is cast to a dynamic and then asked to be iterated, and does not let you gain access to LINQ. Thus pattern matching is not an instead-of implementing `IEnumerable`, its more like extra work if you care about those allocation.

Now, what we would like to do is get around some of these inefficiencies in a way that going forward can avoid some of these overheads. These are in-addition to, not to completely replace the current status quo. In practice, these will suffer some of the problems of pattern matching but it might be a smaller price to pay.
Hows about this?
Make a `GetIterator` return an abstract class based iterator. The iterator would have a single abstract method on `bool TryGetNext(out T)`. The advantage here is that by making it abstract we avoid the interface overhead. The disadvantage is we are always allocating, and always using virtual dispatch. We have simplified the pattern to only one virtual call though. Since we would have a single abstract class we can implement a conversion to `IEnumerable<T>` and `IEnumerable` which would help solve the consumer issue. (e.g. to add a bridge to LINQ we would just write a .ToEnumerable(), so it'd be like `myNewIntCollection.ToEnumerable().Where(x=>x > 5)...`.
Iteration would be fairly straight forward. If a user implements IDisposable, I think we should call it making the feature more or less opt-in.

``` csharp
foreach(T foo in myCollection){
/* impl go here*/
}
```

Would translate to 

``` csharp
var iterator= myCollection.GetIterator();
using(iterator as IDisposable){
     T temp;
     while(iterator.TryGetNext(out temp)){
           T foo = temp;
           /* impl go here */
     }
}
```

I also thought about the idea of GetIterator returning a `bool delegate Iterator(out T current)`. But it has the same or worse problems. You would always have to allocate a new instance. You can't cache it. Delegate creation isn't cheap and It's hard to make it extensible. You would probably still need to create a class to capture state and manipulate all those methods from it.

I don't think this is perfect, but I think there is some chance to improve the current situation. This is mainly inspired by reading @jaredpar blog post http://blog.paranoidcoding.com/2014/08/19/rethinking-enumerable.html

**Comment by HaloFour** [comment]
Rather than requiring classes why not add this as a second form of pattern matching?

When trying to `foreach` over the result of a variable, the compiler will first look for a method called `GetIterator()`.  This can be an instance method on the type of the variable or an extension method.  The return type can be any `class` or `struct` but it must contain a method that matches the signature `bool TryGetNext(ref T)`.  That is sufficient to support iteration, however if the iterator also implements `IDisposable` the compiler will automatically emit code to attempt to dispose it.

```cs
public struct Range {
    private readonly int Start { get; }
    private readonly int Count { get; }

    public Range(int start, int count) {
        Start = start;
        Count = count;
    }
}

public static class RangeExtensions {
    public static RangeIterator GetIterator(this Range range) {
        return new RangeIterator(range);
    }
}

public struct RangeIterator {
    private readonly int start;
    private readonly int end;
    private int current;

    public RangeIterator(Range range) {
        start = range.Start;
        end = start + range.Count;
        current = start;
    }

    public bool TryGetNext(ref int value) {
        if (current < end) {
            value = current++;
            return true;
        }
        return false;
    }
}
```

You could iterate over it by using the following:

```cs
Range range = new Range(0, 10);
foreach (int value in range) {
    Console.WriteLine(value);
}
```

The compiler would emit the following:

```cs
Range range = new Range(0, 10);
{
    RangeIterator iterator = RangeExtensions.GetIterator(range);
    int value = default(int);
    while (iterator.TryGetNext(ref value)) {
        Console.WriteLine(value);
    }
}
```

Just a thought.

**Comment by mburbea** [comment]
Creating this form as just an alternative pattern isn't a huge benefit, as while it is easier the previous pattern (less cruft to implement) if its simple enough may have both `get_Current` and `MoveNext()` be inlined. Reducing some of the benefit. The benefit of a class is that the compiler could also generate the simpler class if we have a method return an Iteraterable and use `yield return`. 

It still suffers that a user will still need to implement an `IEnumerable<T>` implementation to gain access to LINQ.

**Comment by AdamSpeight2008** [comment]
**Iterator(Of T)**
```
Iterator<T>
  .Go : ()-> MayBe< Iter<T>>
```
**Iter(Of T)**
```
Iter<T>
  .Value : T
  .Next  : MayBe<Iter<T>>
```
Multiple calls of `.Next()` would result in the same `Iter<T>` because of there immutability.

**Usage**
```
var iter = thisIterator.Go()
while( iter != null )
{
  // Do stuff with iter.Value
  iter = iter.Next()
  // iter(old)'s memory space can be reused by this iter
}
```
If the `option<T>` type could be extend then the types would be.
```
type Option<T>
  | None
  | .Value : T

type Iter<T> extends Option<T>|.Value
  | .Next : ()-> Iter<T>
```

**Comment by HaloFour** [comment]
@mburbea This is true.  A base class or interface does give iterator methods something easy to implement and return.  But then you always incur at least an allocation and virtual method calls.  I don't know how you could really solve that without a new keyword that could generate iterator structs.

**Comment by jaredpar** [comment]
This proposal is nice but it's maintaining one of the main inefficiencies of the current enumerator pattern: the forced allocation.  So long as the general case still has an allocation developers will shun methods like LINQ and abstractions over enumerables because it's inherently slower than directly implementing the method.

**Comment by HaloFour** [comment]
At the risk of starting a war I will express that the majority of developers probably don't care about those lost nanoseconds (per iteration), the value of the simplicity of use and maintainability far outweigh the benefit of manually rolling potentially complex enumerable operations.

Of course that's no reason to not pursue ways to improve the situation.  An improved pattern-based approach at least allows for more options for `struct` enumerators but you can't build libraries around that.  It feels like we need something like an interface that can only be implemented by a struct where the compiler and run time could guarantee no allocations and no virtual calls.

**Comment by AdamSpeight2008** [comment]
Refined my version, `Iterator(of T)` is not needed.
```
Inteface Iter<T,R>
  .Value : R
  .Next  : MayBe<Iter<T,R>>
```
The following LINQ implementation of `Where` and `Select`
```
' +------------------------------------------+
' |  LINQ WHERE                              |
' |                                          |
' | foreach x in xs { if f(x) yield x }      |
' +------------------------------------------+

static Where<T>(this it : MayBe<Iter<T,T>>, pred : Func<T,Bool> ) : MayBe<Iter<T,T>>
{
  if( it == None ) { return MayBe.None(); }
  return New WhereIter<T,T>( source, pred );
}

class WhereIter<T> : Iter<T,T>
{
  internal Curr : MayBe<Iter<T>>
  internal pred : Func<T,bool>
  public new( it : MayBe<Iter<T>>, pred : Func<T,bool>  )
  {
    this.f = f ;
    Curr   = WhatNext( it );
  }
  private WhatsNext(state : MayBe<Iter<T>>) : MayBe<Iter<T>>
  {
    while ( (state != None) && !pred( state.Value ) )
    {
      state = state.Next();
    }
    return state;
  } 
  public Value() : T { get: { return Curr.Value; }
  public  Next() : MayBe<Iter<T>> 
  {
    if( Curr == None) { return None }
    returrn New WhereIter<T>( WhatsNext( Curr.Next ) , pred );
  }
}
```
```
' +------------------------------------------+
' |  LINQ SELECT                             |
' |                                          |
' | foreach x in xs{ yield f(x) }            |
' +------------------------------------------+

public static Select<T,R>(this source : MayBe<Iter<T,R>>, selector : Func<T,R> ) : MayBe<Iter<T,R>>
{
  return New SelectIter<T,R>(source, selector);
}

class SelectIter<T,R> : Iter<T,R>
{
  public      Value : R { get: }
  internal selector : Func<T,R>
  internal     curr : MayBe<Iter<T,R>>

  public new ( curr : MayBe<Iter<T,R>> , selector : Func<T,R> )
  {
    this.selector = selector;
    this.curr = curr;
    this.Value = selector( curr.Value );
  }
 
  public Next() : MayBe<Iter<T,R>> 
  {
    if( curr == None ) return None;
    return nre SelectIter<T,R>( curr.Next(), selector );
  }
}
```

Think these could be `struct`

**Comment by deoradh** [comment]
Perhaps invert the pattern?  If the compiler detects that the sequence has (say) ForEach<T>(Action<T>), it inlines the body and further inlines the foreach block with suitable variable transforms.  This also matches certain existing LINQ patterns.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
