### ISSUE TITLE
TableControl should not force synchronous navigation

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42603]
Current VS api for this is: 

```c#
public abstract class TableControlEventProcessorBase : ITableControlEventProcessor {
        public virtual void PreprocessNavigate(ITableEntryHandle entry, TableEntryNavigateEventArgs e);

```

However, teh APIs for navigation with RichNav are async/cancellable.  There's an impedance mismatch here.  async/cancellable makes sense since navigation is inherently IO (and will become more so since this will cross network).

TableControl should support an async-cancellable model for navigation as well for this sort of world.

**Comment by CyrusNajmabadi** [comment]
As per our conversation today.

**Comment by jinujoseph** [comment]
moved to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1087606)
