### ISSUE TITLE
Suppressed diagnostics should be output to the errorlog

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#4261]
Today, when a diagnostic is identified as having been suppressed (based on pragmas or suppressmessage attributes), the compiler filters them out and the GetDiagnostics API doesn't return them at all. This means that any downstream tool cannot do things like auditing suppressions. The compiler API should instead just output them with a field that says the diagnostic was suppressed. This lets the host decide the behavior it wants for suppressed issues - The compiler executable wouldn't print these suppressed issues to the commandline, The errorlist could show a column for suppression state and show the suppressed issues if the user wants to see them. These issues should also be logged to the errorlog when the /errorlog switch is passed in.

**Comment by mavasani** [comment]
This is now checked in.
