### ISSUE TITLE
Source generators: parallelize generation

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#42629]
Generators are currently run in sequence, but for performance it should be possible to run them in parallel as there are explicitly no dependencies between them.

**Comment by CyrusNajmabadi** [comment]
If you do this, please don't do it in-proc as parallel processing can dramatically cause problems for UI-latency-sensitive apps.  All the garbage generated on all threads causes GCs which causes stutters and hangs.  Thanks!

**Comment by dialedin2014** [comment]
I see this is marked as done.  Do incremental generators run each pipeline in parallel?  For example, if I call RegisterSourceOutput three times in IIncrementalGenerator.Initialize, passing in three different IncrementalValuesProviders, will the transforms I define for those run in parallel?
