### ISSUE TITLE
ISnippetInfoService throws when a LSP request is invoked on the C# language server

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#42624]
When I directly open a .razor file and invoke completions, [this](https://github.com/dotnet/roslyn/blob/79770acfe36c099772465093389b013fc83681df/src/VisualStudio/LiveShare/Impl/Client/RemoteLanguageServiceWorkspaceHost.cs#L100-L110) part of the code never runs and causes some necessary services to not be initialized and it throws [here](https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs#L54).

Note: if I open a .cs file before opening a .razor file, everything works.

cc @jasonmalinowski @dibarbet

**Comment by sharwell** [comment]
`AbstractSnippetInfoService` is a MEF-exported type. It _must not_ have thread affinity in the constructor.

**Comment by jinujoseph** [comment]
Looks like there is a workaround. moving this to next milestone

**Comment by dibarbet** [comment]
resolved by https://github.com/dotnet/roslyn/pull/45729
