### ISSUE TITLE
Broken Nuget package Microsoft.VisualStudio.Shell.15.0 

### ISSUE THREAD

**Issue by germandb** [dotnet/roslyn#42623]
**Version Used**: 
Microsoft.Visual.Studio.Shell.15.0 - 16.5.29911.84
**Steps to Reproduce**:

1. Try to install the latest version of Microsoft.VisualStudio.Shell.15.0
  `Install-Package Microsoft.VisualStudio.Shell.15.0 -Version 16.5.299911.84` 

**Expected Behavior**:
The package got installed.
**Actual Behavior**:
Error: _Nu1102: Unable to find package Microsoft.ServiceHub.Framework with version (<= 2.3.56)_

The latest version of  Microsoft.ServiceHub.Framework in nuget.org is 2.1.20

**Comment by CyrusNajmabadi** [comment]
Closing out.  This does not appear to be a Roslyn issue.  Perhaps file this with Nuget, or make a VSFeedback report?
