### ISSUE TITLE
go-to decompiled source should have an option allowing user to opt-out without being prompted again

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42638]
Related to https://github.com/dotnet/roslyn/issues/42613.

People can get flighted into the state where the "navigate to decompiled sources" option is enabled.  And, at some point we may just decide to enalbe this by default for everyone.

In this state, the user experience for goto-def in VS is terrible *if* you just want use metadata-as-source (like I do).  You get prompted *every* *time* if you accept decompilation, and you have to reject it *every* *single* *time*.

We should update the dialog to have three options:

1. Yes, I accept the terms and would like to go to decompiled source.  (same as before).
2. No, i do not accept the terms.  Take me to to the metadata view this time. (same as before).
3. No, i do not ever want to go to decompiled code.  (new.  switches option back to off).

**Comment by sharwell** [comment]
We don't control the UI for this dialog, so it may be difficult to add a button to it. I agree that the third option, if available, should simply turn the feature back off.

**Comment by CyrusNajmabadi** [comment]
> We don't control the UI for this dialog

Who controls the UI for this dialog?  @mikadumont do you know? We can start the conversation with them to fix this broken experience.  Until this can be fixed, i don't think we can flight people into this, or change the default here.

Also, how do we find out how flighting was enabled here?  I think we need to have a conversation with that team asap about the experience being pushed down.

**Comment by CyrusNajmabadi** [comment]
tagging @kendrahavens for visibility as well.

**Comment by YairHalberstadt** [comment]
I also think the UX of the popup is undesirable from the following perspective:

The options are "Yes, I accept the terms", and "No I do not accept the terms".

I feel like accepting the terms is something I do once. I don't want to have to do it every time.

However what I may want every time is a choice between, "I want to see decompiled source", and "I want to see metadata as source".

There should be an setting to toggle between:

I always want to see decompiled
I always want to see metadata as source
Ask every time

**Comment by mikadumont** [comment]
@sharwell can we have the decompiled source view collapse all members by default so it looks the same as the metadata source view: 

Decompiled source view:
![decompiled sources](https://user-images.githubusercontent.com/46729679/77368228-055fdd00-6d19-11ea-97c0-2e562e2b2ceb.png)

Metadata source view:
![metadata-sources](https://user-images.githubusercontent.com/46729679/77368235-07c23700-6d19-11ea-8e5e-8f995e5b5005.png)

@sharwell Today the dialog only shows up once per session. Is it possible to have 2 options:
1. If a user says Yes, I want to go to decompiled sources - connect this setting to the user's account so we dont ask them again. 
2. If the user says No, I do not ever want to go to decompiled sources. (switch option back to off in tools options).

@CyrusNajmabadi if decompiled sources showed the metadata view (collapses members by default) would you still want the option to see metadata sources? And if we remove the blank line?

**Comment by mikadumont** [comment]
Here are the default options we can use for the dialog: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.olemsgbutton?view=visualstudiosdk-2019

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi if decompiled sources showed the metadata view (collapses members by default) would you still want the option to see metadata sources? 

I would have to try it out.  But tentatively i think i would be ok with not using MAS at that point.

**Comment by sharwell** [comment]
@mikadumont Remembering the 'Yes' option is covered by #33323

**Comment by CyrusNajmabadi** [comment]
This was done.
