### ISSUE TITLE
Roslyn can't detect 932 encoding 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#4264]
The encoding detection logic does not properly handle CP 932 (Shift JIS) files where previous compilers could.  This results from a change in the final fallback logic in our encoding detection scheme.  Roslyn will process in order the BOM, the specified code page and finally UTF8.  The native compiler had the same logic but used the active code page as the final fallback instead of UTF8.  The use of the active code page is how 932 encoded files were processed.  

As a work around the code page can be manually specified on the command line:

``` 
$> csc /codepage:932 Program.cs
```

**Comment by AlekseyTs** [comment]
@jaredpar, please verify
