### ISSUE TITLE
Provide a way to suppress diagnostics from the error list.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#4265]
Diagnostics that are reported by FxCop have a context menu item to suppress the issue (this emits the suppressmessage attribute). Roslyn diagnostics have a lightbulb action to do that but there's no way to do this from the error list currently. We should provide a way to perform the suppression from a context menu for the roslyn diagnostics as well.

We should also make sure that we can select multiple issues and run the actions (the equivalent of the fix all for suppressions).

**Comment by hvanbakel** [comment]
Related to #4214

**Comment by hvanbakel** [comment]
@srivatsn keep in mind that #4214 was also about the ability to suppress an error, not just warnings. Like you could do with FxCop.

**Comment by hvanbakel** [comment]
Also, there's no way to do a global suppression now which is required for some rules.

**Comment by srivatsn** [comment]
By global suppression, do you mean suppressing an instance in a separate GlobalSuppressions.cs file or some notion of suppressing a rule for an entire project. A codefix for the former is available from the lightbulb. I suppose you are pointing out that the error list is missing that functionality?

**Comment by hvanbakel** [comment]
Exactly

**Comment by srivatsn** [comment]
A context menu item has been added for suppressing issues from error list.

**Comment by hvanbakel** [comment]
For what it's worth, this is contained within VS2015 Update 1. See
http://blogs.msdn.com/b/visualstudio/archive/2015/11/30/visual-studio-update-1-rtm.aspx

**Comment by hvanbakel** [comment]
@srivatsn A bit of an old issue here, but are there any plans to suppress by using the attribute as opposed to the pragma? The pragmas have the downside of not having a justification and being harder to spot as opposed to the attributes

**Comment by srivatsn** [comment]
In the suppression file it's always attributes. When suppressing in source, the pragmas provide the advantage that the suppression can be very targeted to an individual statement whereas the attribute will have to be a large scope by like the method or type. We used to offer both options but the extra option seemed to just confuse people as there was no guidance and the current way is more prescriptive.

**Comment by hvanbakel** [comment]
Is it possible to have a config switch for this? In existing codebases this is odd as some suppressions will be done using attributes whereas the others will be done using pragmas.

Also, suppressions with attributes can be precise too see this example:
`[SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "2#", Justification = "Needed for struct performance.")]`
That's a method level suppression but it only suppresses the second occurrence

**Comment by srivatsn** [comment]
Please open a separate issue to add a codefix that can add the suppressmessage attribute as well. 

The MessageId field doesn't have any defined semantics. It's upto the rules to make sense of that and in the old FxCop implementation a handful of rules respected that field. In the roslyn analyzer implementation we aren't looking at that field at all (although we should).
