### ISSUE TITLE
Introduce a status column for diagnostics

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#4266]
We've heard of workflows where when an analysis occurs and there are large volumes of issues, there are various reasons to ignore a reported issue:

- The reported issue is a false positive (Tool Noise)
- The reported issue is valid but there's a justification for not fixing it (Wont fix)
- The reported issue is valid but I don't have time to investigate right now (Postponed\Deferred). Selecting all issues and postponing them and ensuring all new issues are fixed is a common workflow.

The proposal here is to do the following:
- Add a state field to the SuppressMessageAttribute
- Report that state for suppressed diagnostics
- Add a column to the error list for the state.
- Provide a context menu to change the state (Related to #4265)

**Comment by michaelcfanning** [comment]
Concepts here break into two pieces:
Workflow state: active, tracking, deferred, won't fix
Investigation state: not investigated, valid issue, false positive

**Comment by mavasani** [comment]
This is now checked in.
