### ISSUE TITLE
IDE0071 suggests simplification for `$"{base.ToString()}"`, but `$"{base}"` generates CS0175.

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/roslyn#42669]
**Version Used**: 
Microsoft Visual Studio Community 2019 Version 16.5.0

**Steps to Reproduce**:

1. In a class override ToString:
`public override string ToString() => $"Test: {base.ToString()}";`
This generates an *IDE0071 Interpolation can be simplified*

2. Simplify the expression using the smart tag. This changes the code to
`public override string ToString() => $"Test: {base}";`
and generates a *CS0175 Use of keyword 'base' is not valid in this context*.

**Expected Behavior**:
Either do not generate IDE0071 **or** do allow `base` in this context.

**Actual Behavior**:
Either raises IDE0071 or CS0175.

**Comment by jnm2** [comment]
It should not report anything if ToString is overridden (making `base.ToString()` distinguishable from `this.ToString()`). If ToString is not overridden (and even if it is shadowed), we could replace with `this`.

**Comment by OJacot-Descombes** [comment]
`this.ToString()` or just `this` would create an endless recursion here. The purpose here, is to extend `base.ToString()`. What is not clear to me is why `base` alone doesn't work, since the string interpolation will call `ToString()` on it automatically. So, I'm not sure whether the problem is with IDE0071 or with CS0175.

**Comment by jnm2** [comment]
Right, this case wouldn't be affected either way if the criterion was whether ToString was overridden in the current class. I think we will go with never suggesting the replacement though even if ToString is not overridden in the current class; `base` was presumably chosen because `this` was not desired.
