### ISSUE TITLE
C# "Replace function with property" refactoring deletes comment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/942212/c-replace-function-with-property-refactoring-delet.html)._

---
Repro:

```
class Cx
{
  int GetFoo() // some vital comment
  {
    return 1;
  }
}
```
Invoke "Replace 'GetFoo' with property".

Expected:
```
class Cx
{
  int Foo => 1;  // some vital comment
}
```
alt.
```
class Cx
{
  // some vital comment
  int Foo => 1;
}
```

Actual:
```
class Cx
{
  int Foo => 1;
}
```

This is a data-loss bug.

---
#### Visual Studio Feedback System on 3/9/2020, 03:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by BrianFreemanAtlanta** [comment]
I could take a stab at this. I've tracked down where the trivia is getting dropped. Trying to determine best route to keep it. For this case the trivia is attached to the child node for the "parameter" node instead of the main syntaxNode. Trying some permutation of DescendentTrivia.

**Comment by BrianFreemanAtlanta** [comment]
For reference it in TPropertyDeclaration SetLeadingTrivia in AbstractReplaceMethodWithPropertyService

**Comment by davidwengier** [comment]
Looks like this was fixed by https://github.com/dotnet/roslyn/pull/48183
