### ISSUE TITLE
C# Code Style - New .editorconfig option 'dotnet_style_prefer_simplified_interpolation' is not shown in UI.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42695]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/957306/c-code-style-new-editorconfig-option-dotnet-style.html)._

---
In VS 2019 16.5 a new .editorconfig option appeared

dotnet_style_prefer_simplified_interpolation

You can see this if you open the VS C# Code Style options window and export to .editorconfig file.

However, this option isn't present in the C# Code Style UI itself.
It is also not documented on any of the doc pages

https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

I assume as all the other code style options are, this should also be.

---
#### Visual Studio Feedback System on 3/22/2020, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@mikadumont for the documentation issue

Marking as **Need Design Review** for the code style options page issue (not all of the options are shown in the options page, since configuration through **.editorconfig** provides a more consistent team experience).

**Comment by allisonchou** [comment]
Notes from today's design meeting (4/13):
We will fix this issue; in the future, we hope to have a better user story for .editorconfig and a more consistent experience between .editorconfig and Tools->Options (see #39414 and #40163).
