### ISSUE TITLE
intellisense cannot handle "extern alias"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42697]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/955352/intellisense-cannot-handle-extern-alias.html)._

---
I am using multiple versions of the same DLL in my code. These DLLs are distinguished using "extern alias" on all older versions, and NO alias (thus "global") on the current version.
When refering to classes from the old DLLs in Intellisense comments with <param> or <see>, Intellisense refers to the current version. So it looks like Intellisense cannot handle "extern alias".
See screenshots.

---
#### Visual Studio Feedback System on 3/19/2020, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### T Knauss on 3/19/2020, 02:36 AM: 

<p>Seems like your bug reporting tool is buggy as well, because it didn't add the images that I attached. At least I can't find them here.</p><p>Next try...</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/123957-extern-alias-definition.png">extern-alias-definition.png</a></p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/123958-intellisense-failure.png">intellisense-failure.png</a></p>

#### Yanghua Zhang[MSFT] on 3/19/2020, 11:30 PM: 

<p>Thank you for your feedback! Can you tell us what language type your project is(C++ or C# or other)? In order for us to investigate this further, could you please provide a sample project to us that can reproduce this issue? We look forward to hearing from you. Thanks!</p>

#### T Knauss on 3/20/2020, 02:20 AM: 

<p>language is C#<br>tested with Visual Studio versions 2015 U3 and latest 2019 (16.4.5).</p><p>You can call yourself lucky, I do have a sample program. This is a reduced version of my larger test program. I have removed all unnecesary parts manually and didn't compile, so I don't know whether it works, but it should. Will be added to the next comment (not public).</p><p>Just hold your cursor above "main()" and you'll see the wrong intellisense comment. It's defined as<br><em>/// This class uses &lt;see cref="CLocationV22"/&gt; and &lt;see cref="CLocationV23"/&gt; and &lt;see cref="CLocationV24"/&gt;.</em></p><p>But instead of<br><em>"This class uses CLocationV22 and CLocationV23 and CLocationV24."</em><br>it shows<br><em>"This class uses CLocationV24 and CLocationV24 and CLocationV24."</em></p><p>When preparing the test program, I saw another, closely related bug: If all referenced DLLs have an alias, then the shown comment is<br><em>"This class uses Schmoll.SwCore.CLocation and Schmoll.SwCore.CLocation and Schmoll.SwCore.CLocation."</em><br>which is correct actually, but useless, because it's the same name of 3 different types. In this case it should add the names of the alias:<br><em>"This class uses swcore_v_0_22_13.Schmoll.SwCore.CLocation and swcore_v_0_23_5.Schmoll.SwCore.CLocation and swcore_v_0_24_9000.Schmoll.SwCore.CLocation."<br></em></p><p>You can test that by<br>- add the alias "swcore_v_0_24_9000" to those 2 DLLs that are global<br>- add "extern alias swcore_v_0_24_9000;" at the top of the program.cs<br>- replace "using CLocationV24 = global::Schmoll.SwCore.CLocation;" by "using CLocationV24 = swcore_v_0_24_9000.Schmoll.SwCore.CLocation;"</p>

#### T Knauss on 3/20/2020, 02:21 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 3/20/2020, 02:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by TobiasKnauss** [comment]
I can only see my screenshots being attached to this issue. If you need the test project which I added to the original ticket in VS developer community, please look there or ask me to upload it here again.

**Comment by CyrusNajmabadi** [comment]
@TobiasKnauss Please upload here again.  Thanks :)

**Comment by TobiasKnauss** [comment]
@CyrusNajmabadi seriously? If you hadn't added that comment but copied the zip from the other source, it would have taken the same time.
Here you are:
[testDLLMultipleVersion.zip](https://github.com/dotnet/roslyn/files/4379802/testDLLMultipleVersion.zip)

**Comment by CyrusNajmabadi** [comment]
@TobiasKnauss you asked... :-)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in extern-alias scenarios.
