### ISSUE TITLE
Enter the command beginning with the character # in C # Interactive to complete the list for normal disappearance

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42700]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/928406/enter-the-command-beginning-with-the-character-in.html)._

---
Reappearance: 
Enter # help in C # Interactive and press Enter. 
(I'm sorry, I can't provide Record, because I tried it twice, but both were saving the record when the timeout occurred, and about this, I've submitted another report) 
Summarize the problem: When using C # Interactive, if you enter a complete command that starts with character #, the completion list appears in the input with the correct settings and the items are not selected. After the input is complete, press EnterKey, when the completion list remains. This is clearly unnatural. 
Please fix to let it disappear normally after pressing EnterKey, thanks!

---
#### Visual Studio Feedback System on 2/24/2020, 06:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
Looks like the same issue as https://github.com/dotnet/roslyn/issues/39299
