### ISSUE TITLE
Generated GetHashCode does not use prime numbers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42701]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/926332/generated-gethashcode-does-not-use-prime-numbers.html)._

---
When using the quick actions to generate GetHashCode the hash code generated does not use prime numbers.
Is this a bug? If not please explain to me why not using prime numbers is ok.

Thank you

---
#### Visual Studio Feedback System on 2/23/2020, 09:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by GrabYourPitchforks** [comment]
There's no requirement that any given `GetHashCode` implementation use prime constants. That said, any hash code calculation routine that we auto-generate should probably use [the `HashCode` type](https://apisof.net/catalog/System.HashCode) if targeting a framework which contains that type.

**Comment by CyrusNajmabadi** [comment]
> That said, any hash code calculation routine that we auto-generate should probably use the HashCode type if targeting a framework which contains that type.

Yes.  We do that.

**Comment by CyrusNajmabadi** [comment]
> There's no requirement that any given GetHashCode implementation use prime constants.

Correct.  The hashing we emit follows the same pattern the C# compiler emits for GetHashCode in anonymous types.

**Comment by CyrusNajmabadi** [comment]
This is all by design :)

**Comment by GrabYourPitchforks** [comment]
Thanks Cyrus for the quick response! :)

FYI to anybody who needs `HashCode.Combine`-like functionality on downlevel runtimes: in a pinch you can use the `ValueTuple<...>` type. The syntax is fairly clean: `return (a, b, c, ...).GetHashCode();`. The implementation of `ValueTuple.GetHashCode` is runtime-dependent, but on modern runtimes it's fairly good.

**Comment by CyrusNajmabadi** [comment]
> FYI to anybody who needs HashCode.Combine-like functionality on downlevel runtimes: in a pinch you can use the ValueTuple<...> type. The syntax is fairly clean: return (a, b, c, ...).GetHashCode();. 

The IDE will also generate that.  Basically we generate in the following order:

1. generate with HashCode.Combine if available.
2. generate with ValueTuple if available.
3. generate with manual math otherwise.

**Comment by CyrusNajmabadi** [comment]
Basically we give you the best idiomatic GetHashCode possible given the platform you're compiling against.
