### ISSUE TITLE
Check variable against multiple values with one operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42723]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/881921/check-variable-against-multiple-values-with-one-op.html)._

---
<pre>//Simple example
int temp = 0;
if ( temp == (0 || 1 || 20))
{

}<br></pre>

---
#### Visual Studio Feedback System on 1/12/2020, 10:51 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is a language request, and should go to csharplang.  That said, i'm going to close this as a dupe as we're adding pattern support here so you can write: `if (temp is 0 or 1 or 20)`
