### ISSUE TITLE
"Use of unassigned local variable" CS0165 issue

### ISSUE THREAD

**Issue by mpmel** [dotnet/roslyn#4272]
I'm getting a complaint in my code using VS 2015 and .Net 4.5.2, and am not quite understanding why.

If I call
```csharp
MyObject o;
if (objects != null && objects.TryGetValue(objectName, out o))
    v.Property= o;
```
then everything is fine. The following two cases however give me an error, and I'm not quite understanding why.

```csharp
MyObject o;
if (objects != null ? objects.TryGetValue(objectName, out o) : false)
    v.Property= o; // <-- error CS0165: Use of Unassigned local variable 'o'
```
and
```csharp
MyObject o;
bool b;
if (objects != null)
    b = objects.TryGetValue(objectName, out o);
else
    b = false;
if (b)
    v.Property = o; // <-- error CS0165: Use of Unassigned local variable 'o'
```
In either of the last 2 cases, I don't see how `o` can be used unless `TryGetValue` is called, which means `o` should be initialized.

Is this a bug? Or I am I missing something?

**Comment by paul1956** [comment]
All the VB examples show an explicate initialization of "o", even though the documentation call value an out or <OutAttribute> and it says the value will be returned with an appropriate default value. VS2013 also required o be initialized or you got the same message. I have also seen code that puts an initial default value in o, but according to the documentation it would be overwritten.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by HaloFour** [comment]
This behavior is expected and exists in previous versions of the compiler as well as Mono.  The analysis for detecting whether the variable is assigned is not sophisticated enough to follow the conditional statements to ensure that the variable is only used in those situations where it has been assigned a value.  It would kind of be nice if it was.

Java does behave similarly as well, the following producing a compile-time error in javac:

```java
String s;
boolean b = true;
if (b) {
    s = "Hello World!";
}
if (b) {
    System.out.println(s); // Error:(36, 32) java: variable s might not have been initialized
}
```

However, in this case if the variable `b` is marked `final` then it does compile successfully.

**Comment by paul1956** [comment]
Even in the simplest case the compiler insists the variable be initialized even though it is defined as <OutAttribute>
        Dim o As New Dictionary(Of Integer, String) From {{1, "Start"}}
        Dim Str As String
        Assert.IsFalse(o.TryGetValue(2, Str))

Warning	BC42030	Variable 'Str' is passed by reference before it has been assigned a value. A null reference exception could result at runtime.

Public Function TryGetValue ( _
	key As TKey, _
	<OutAttribute> ByRef value As TValue _
) As Boolean

**Comment by mpmel** [comment]
I've never used VB much so I don't know all the subtle differences, but it appears that's fine for VB where `TryGetValue` appears to define the 2nd parameter as `ref`, but in C# it is declared as an `out`

so your example in C#

```csharp
var  o = new Dictionary<int, string>{ { 1, "Start" } };
string str;
o.TryGetValue(2, out str);
```

doesn't produce the compiler warning.

In the many years that I have been using C#, I've never come across this scenario so I thought maybe it was something new with Roslyn. It's not the typical way I would write the code, but I was playing around with some of the new language features just trying to see what was possible.

I started with
```charp
MyObject o;
if (objects?.TryGetValue(objectName, out o))
    v.Property= o;
```
Then tried to back out of it with Resharper and got 
```csharp
MyObject o;
if (objects != null ? objects.TryGetValue(objectName, out o) : false)
    v.Property= o; // <-- error CS0165: Use of Unassigned local variable 'o'
```

I couldn't see any execution path where `v.Property` would get set without `TryGetValue` getting called, which guarantees it gets initialized.

Since that's the way it has been and no one has complained or changed it, I guess there's not much else to say, I just found it odd that there were two simple examples where it gave a compile error where I didn't think it should.

**Comment by paul1956** [comment]
For some reason the VB definition is not displaying correctly here. the second parameter is defied as <OutAttribute>

**Comment by jaredpar** [comment]
This behavior is "By Design".  As @HaloFour mentioned the compiler doesn't do this type of advanced flow analysis (linking the boolean to the use of the object).  Instead it just looks at possible code paths and determines if the value has been assigned on all code paths that lead to a specific use.
