### ISSUE TITLE
cycle construction

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42725]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/952323/cycle-construction.html)._

---
<p></p><p>Cycle construction (do while) allows to describe variable in block, but it's invisible outside. So users must describe variable outside of cycle only. Proposal not to tear cycle condition from the body. The only variant now is:<br>&lt;type&gt; varname;<br> do<br>{<br>  ... <br>} while varname …; <br>Proposed to consider correct way:<br>do<br>{&lt;type&gt; varname;<br>  ... <br>} while varname …; <br>because cycle is one operator with variable varname inside. Otherwise it may resemble an mistaken cycle with different variables i in body and i in condition! <br>for (int i&lt;condtion&gt;) = 0; i&lt;condtion&gt; &lt; 5; i&lt;condtion&gt;++)<br>{<br>    Console.WriteLine(i&lt;body&gt;);  <br>}</p>

---
#### Visual Studio Feedback System on 3/17/2020, 10:42 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Language requests should be made at github.com/dotnet/csharplang.  I have informed the vsfeedback filer.
