### ISSUE TITLE
Add more search options in VS.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42728]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/958325/add-more-search-options-in-vsnet.html)._

---
I need to search the project for param names that start with _ . I found no option to do that. So, I am thinking: Why can't we specify the element type/s we want to search for?
Identifiers, literals, keywords, class names, functions names, param names, types… etc
And the blocks we want to search within:
Enums, structs, clusses, methods, properties, Conditions, loops… etc.
This will save tremendous times in searching large solutions.

---
#### Visual Studio Feedback System on 3/23/2020, 03:56 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Feedback for aiosp.  @veler
