### ISSUE TITLE
Reorganize Add Parameter Tests & Helpers

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#42734]
See 
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369930283
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369933245
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369934303
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369935203
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369937127
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369938117
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369938684
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369974010

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
