### ISSUE TITLE
Proposal: IntPtr and UIntPtr Literals

### ISSUE THREAD

**Issue by vcsjones** [dotnet/roslyn#4273]
I propose that literal suffixes for IntPtr and UIntPtr be added. For example:

```
var example1 = 2n;
var example2 = 2un;
var example3 = -1n;
```

Where the literal is equivalent to `new IntPtr(2)`, `new UIntPtr(2)`, and `new IntPtr(-1)` respectively.

The primary need for this is platform invoke. Many Win32 APIs take magic handle values, or null (0n). This would also bring parity to F# which already supports this feature.

**Comment by GSPP** [comment]
Isn't `new IntPtr(2)` or `(IntPtr)2` good enough? Maybe C# needs to support more implicit conversions so that the following works as well:

    IntPtr x = 2;

And the same for method call arguments.

**Comment by vcsjones** [comment]
>Isn't new IntPtr(2) or (IntPtr)2 good enough?

It isn't my favorite, yes it "works". However when you are working with a DllImport that looks like this:

    public bool Foo(IntPtr a, IntPtr b, IntPtr c, IntPtr d, IntPtr e, IntPtr f, IntPtr g);

Or likewise fields on a struct, it still looks a little odd. When you need to pass in IntPtr.Zero to all of them. Sure, I could make that a local, but I've worked with some libraries that probably overused platform dependent integers.

I don't like the implicit conversion, either - I think explicitness is desirable. Suffixes would allow things like this, too:

    var x = 2n;

Instead of

    IntPtr x = 2;

**Comment by axel-habermaier** [comment]
When do you ever explicitly assign an ``IntPtr``? Wouldn't it be enough if ``null`` could be converted to ``IntPtr.Zero``?

**Comment by paulomorgado** [comment]
@axel-habermaier, the point of the discussion is that, the only way to have a native integer is to use an `IntPtr`. Thus, every value is needed.

**Comment by vcsjones** [comment]
>When do you ever explicitly assign an IntPtr? 

Any time you want a native-sized integer, not just for pointers and references.

Any Win32 function that takes a `size_t` would correctly be marshalled as a `UIntPtr`. Consider `memcmp`:

    int memcmp( 
       const void *buf1, 
       const void *buf2, 
       size_t count 
    );

The `count` parameter would be a `UIntPtr`. If you know that you want to compare the first 4 bytes, you would do `(IntPtr)4`. You could also just as much wrap the `memcmp` call with wrappers that take an `int` or a `long`, but that is beside the point.

Also consider that most of the Win32 Process functions take a [pseudo handle](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684868(v=vs.85).aspx) with a value of `-1` to mean "current process".

As a final example, the Win32 function [`CertVerifyCertificateChainPolicy`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa377163(v=vs.85).aspx)'s parameter `pszPolicyOID` is declared as a LPCSTR but is really just native integers cast to that type. So if we wanted to use `CERT_CHAIN_POLICY_SSL` as value for the first parameter, I would use `(IntPtr)4`.

**Comment by HaloFour** [comment]
Yeah, the BCL `IntPtr` and `UIntPtr` names are a little unfortunate.  They really just represent platform native integers and in fact their name in the CLR is `native int`.  They also support the IL arithmetic opcodes, but C# doesn't.

Another relevant conversation:  https://github.com/dotnet/coreclr/issues/963

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
