### ISSUE TITLE
Merge code and document while decompile C# library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42730]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/960369/merge-code-and-document-while-decompile-c-library.html)._

---
Most library in .net framework have documents and can be viewed in VS quickly. But when I decompile the library, the documents disappears. It's inconvenient. Can VS merge them? Or at least provide a simple way to switch bwtween code and document because once I decompile the library, I can never view the document by "Go to definition", except using the "Peek definition" or restarting VS.

---
#### Visual Studio Feedback System on 3/24/2020, 02:34 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
@mikadumont  can you get more info here ? screenshot etc
