### ISSUE TITLE
ExcludeFromCodeCoverage with justification

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42731]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/949272/excludefromcodecoverage-with-justification.html)._

---
I would like to add a justifiation to the `ExcludeFromCodeCoverage` attribute so that this can be queried instead of just being in code
This can then also be shown as a build error when checking for minimal code coverage
e.g.

```csharp
/// <summary>
///     This attribute determines if a property is to be backed up for restore when
///     <see cref="IEditableObject.CancelEdit" /> is called on a <see cref="EditableViewModel" />.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
[ExcludeFromCodeCoverage]//This is just a marker attribute without logic
public class SkipForBackupAttribute : Attribute
{
}
```

---
#### Visual Studio Feedback System on 3/16/2020, 01:21 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/29968. Thanks.
