### ISSUE TITLE
C# Line Pragma Leads to a Different Cursor Placement for Go To Implementation

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/roslyn#42746]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 3.5.0-beta1-19606-04 (d2bd58c6)

**Steps to Reproduce**:

1. Create two files. Add a line pragma in one file, which links to the other file. I've provided a repro-repo (update line pragma absolute file path if you're trying locally):
Repro Repo: https://github.com/TanayParikh/line-pragma-implementation-repro

2. Go to Implementation `CTRL+F12` will go to the start of the line (Column 1) of the implementation, rather than where the implementation actually starts. 

The correct behaviour is exhibited with the line pragma removed, or with Go to Definition.

**Expected Behavior**:
Demo without Line Pragma: https://github.com/TanayParikh/line-pragma-implementation-repro/raw/master/Demo_Without_Line_Pragma.mov

**Actual Behavior**:
Demo with Line Pragma: https://github.com/TanayParikh/line-pragma-implementation-repro/raw/master/Demo_With_Line_Pragma.mov

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
