### ISSUE TITLE
LINQ syntax breaks nullability data flow

### ISSUE THREAD

**Issue by jods4** [dotnet/roslyn#42757]
**Version Used**: 3.5.0

**Steps to Reproduce**:
Consider the typing of those two expressions:
```cs
// Method calls
var names = Enumerable.Range(1, 10).Select(_ => new { Name = (string?)null });
// LINQ
var names = from _ in Enumerable.Range(1, 10) select new { Name = (string?)null };
```
It's different syntax for the same expression, yet Roslyn analyzes the nullability of `Name` in the result differently.

This can be checked by simply hovering over `names` in VS and looking at the type displayed in the tooltip.

Method calls correctly infers a nullable `Name`.

**Expected Behavior**:
LINQ syntax infers the same result as method calls: a nullable `Name`.

**Actual Behavior**:
LINQ syntax looses the nullability information and says `Name` is non-nullable.

---
Thanks to @jnm2 and @CyrusNajmabadi for helping me debug this. ❤️

**Comment by jcouv** [comment]
That's a known issue. All range variables declared inside LINQ syntax are currently considered oblivious and the nested expressions are not analyzed.
Tracked by https://github.com/dotnet/roslyn/issues/29863
I'll go ahead and close as duplicate. Thanks for reporting
