### ISSUE TITLE
Semantic classification is slow binding symbols in large files

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42753]
**Version Used**: 16.6 Preview 1

**Steps to Reproduce**:

Open a large source file (the issue was originally reported in a 40,000+ line WinForms file).

**Expected Behavior**:

Semantic classification is fast:

* It does not start until the semantic model is ready
* It does not need to do any non-trivial work because the semantic model can provide type information throughout the requested span with no delay

**Actual Behavior**:

Semantic classification is slow and uses large amounts of CPU.

:link: https://developercommunity.visualstudio.com/content/problem/957956/vs2019-high-cpu-when-doing-nothing-2.html

The main overhead is these lines, in order of most impact to least:

https://github.com/dotnet/roslyn/blob/114989d2b738f949e6ce0cb3b0af1174acb06c2a/src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs#L60

https://github.com/dotnet/roslyn/blob/114989d2b738f949e6ce0cb3b0af1174acb06c2a/src/Workspaces/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegexPatternDetector.cs#L152

https://github.com/dotnet/roslyn/blob/114989d2b738f949e6ce0cb3b0af1174acb06c2a/src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/OperatorOverloadSyntaxClassifier.cs#L33

https://github.com/dotnet/roslyn/blob/114989d2b738f949e6ce0cb3b0af1174acb06c2a/src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/SyntaxTokenClassifier.cs#L46

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi to investigate

**Comment by CyrusNajmabadi** [comment]
Closing out.  We haven't heard about any more issues here.  If we have a current user scenario with issues we can get traces and look into it.
