### ISSUE TITLE
IDE0044 makes volatile fields readonly, resulting in errors

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42759]
**Version Used**: 
C# Tools   3.6.0-2.20167.1+926207070b0c62d6a76aec4627ec26dee17870bb

**Steps to Reproduce**:
```C#
class Program
{
    private volatile object _obj;

    static void Main() { }
}
```

**Expected Behavior**:
IDE0044 doesn't fire.

**Actual Behavior**:
IDE0044 fires, and running it (e.g. on the whole solution) changes the code to be:
```C#
class Program
{
    private readonly volatile object _obj;

    static void Main() { }
}
```
which results in the error:
```
CS0678	'Program._obj': a field cannot be both volatile and readonly
```

**Comment by sharwell** [comment]
It seems like IDE0044 is still the expected behavior, but the code fix should be updated to not make any changes here. If you don't agree with this, can you provide some more specific examples of why we would not want to keep reporting this diagnostic when there are no writes to the field?

**Comment by stephentoub** [comment]
> but the code fix should be updated to not make any changes here

That's fine.  The problem is the fix creating code that doesn't compile.

**Comment by sharwell** [comment]
I've marked this as help wanted to have the code fix skip this case (should be a very easy change).

**Comment by Youssef1313** [comment]
@sharwell @stephentoub From what I see in #43542, the codefix was updated to **remove** volatile and **add** `readonly`. This behavior doesn't match any of the comments in the issue.
