### ISSUE TITLE
New decompilation prompt makes find refs *UNUSABLE*

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42778]
Gif to give you an idea about how bad this is:

![killme](https://user-images.githubusercontent.com/4564579/77591027-5bb15500-6eac-11ea-840c-46968c79e03f.gif)

**Comment by CyrusNajmabadi** [comment]
Tagging @kendrahavens @mikadumont @sharwell @jinujoseph 

This is unbelievably bad.

**Comment by CyrusNajmabadi** [comment]
this started happening after my last VS upgrade

**Comment by sharwell** [comment]
Duplicate of #42638

**Comment by CyrusNajmabadi** [comment]
i don't thiink this a dupe.  I'm not even saying "goto def".  I'm F8'ing through find-ref results.

**Comment by sharwell** [comment]
@CyrusNajmabadi This is a duplicate. The header items used for grouping the results are definitions from metadata. Cycling through the list attempts to navigate to them.
