### ISSUE TITLE
IntelliCode issues make error list unusable

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42776]
![image](https://user-images.githubusercontent.com/4564579/77587403-0d4c8800-6ea5-11ea-94fd-0e2e0dead223.png)

tagging @kendrahavens @mikadumont 

We need to fix this *asap*.  Who do we contact?

**Comment by CyrusNajmabadi** [comment]
@jinujoseph for visbility.  error list is now useless.  this must be fixes asap.  This started happening after my latest upgrade of VS.

**Comment by jmarolf** [comment]
CC: @markw-t who owns this experience

**Comment by CyrusNajmabadi** [comment]
@jmarolf Already on an email thread with him :)

**Comment by markw-t** [comment]
@pgroene and @gustavosoares are working on it already :-)
