### ISSUE TITLE
TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs unnecessarily asserts netstandard2.0 is selected over net461

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#42772]
[TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs](https://github.com/dotnet/roslyn/blob/7804f3d3edc1b3882d1f6c2f0c3cc076a98286b8/src/Workspaces/MSBuildTest/NetCoreTests.cs#L280) appears to assert that .NET Standard references are _always_ preferred to .NET Framework. But this is [not the case](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). .NET Framework 4.6.1 and .NET Standard 2.0 are considered equally valid targets on the compatibility chart for .NET Core 2.0 and above. It is unclear why we are asserting this behavior.

**Comment by sharwell** [comment]
@jmarolf We found this bug for to welcome you to the team 💯
