### ISSUE TITLE
async intellisense explicit method declaration doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42801]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/961674/async-intellisense-explicit-method-declaration-doe.html)._

---
Task IData

will give me auto complete option of IDataService so I can continue to type Task IDataService.MyMethod().

If I type first start with async:

async Task IData

It shows `<Name>` in the same position in the context menu and does not show IDataService.

---
#### Visual Studio Feedback System on 3/24/2020, 10:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @genlu
