### ISSUE TITLE
Compilations used for cross-language references may not correctly handle source generation

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#42819]
As Cyrus observed in [this comment](https://github.com/dotnet/roslyn/pull/42373#discussion_r398306394) we're not passing the generator driver back and into the compilation used for skeleton references or XML documentation; this is probably bad, but it's also unclear to me why we're really trying a shortcut here versus using any of the other mechanisms we have.

**Comment by CyrusNajmabadi** [comment]
closing out as speculative.
