### ISSUE TITLE
Avoid directly constructing MEF parts in tests

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#42814]
This issue tracks MEF exports that suppress RS0033 (Importing constructor should be [Obsolete]) for cases where the part is directly constructed in test code.

* [ ] CSharpCommandLineParserService
* [ ] GenerationOptionsProvider
* [ ] GlobalOptionService
* [x] RemotableDataServiceFactory
* [ ] TextFactoryService
* [ ] Code fix providers
* [ ] Code refactoring providers
* [ ] Signature help providers

**Comment by Evangelink** [comment]
@sharwell What's the recommended way to avoid the direct construction in tests?

**Comment by CyrusNajmabadi** [comment]
Hey an appropriate mef container and request the type from it.

**Comment by Evangelink** [comment]
@CyrusNajmabadi I am not sure to get what you just explained, any example?

**Comment by CyrusNajmabadi** [comment]
Sure.  in lots of tests you'll have something more like:

https://github.com/dotnet/roslyn/blob/29542b0a669071b34fc84fe679c767409460b34f/src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/AbstractCodeActionOrUserDiagnosticTest_TestAddDocument.cs#L114

Here, instead of instantiating this type directly, we retrieve it using mef from the mef container we have for tests to use.

**Comment by sharwell** [comment]
> Here, instead of instantiating this type directly, we retrieve it using mef from the mef container we have for tests to use.

👍 Yep! This ensures that all test code operating on `ICodeActionEditHandlerService` (from this example) is operating on _the same instance_ of `ICodeActionEditHandlerService`, which is the same behavior the application has at runtime. The analyzers related to MEF construction provide a much stronger relation between test behavior and production code behavior.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this needs to be done, it shuold just be assigned to a person/milestone and done.
