### ISSUE TITLE
combined length of user strings used by the program exceeds allowed limit

### ISSUE THREAD

**Issue by link05** [dotnet/roslyn#42828]
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.5.1

.net Framework version  4.7.0356
**Steps to Reproduce**:

1. I had copy pasted a multi line string of roughly 10 lines (its short, for organizing it i made it multi lined) and caused this issue.

**Expected Behavior**:
Building should had no issue.
**Actual Behavior**:
Got this error and dont know how to fix it.

**Comment by CyrusNajmabadi** [comment]
@link05 Can you please provide your project so we can try to reproduce this?
