### ISSUE TITLE
[loc][Query][Roslyn] Localizability of FeaturesResources.xlf

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#42833]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

File Name Live Page Extended | String Resource ID | Full Source String | Query | Answer Needed
-- | -- | -- | -- | --
Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "Configure_severity_for_all_0_analyzers" | Configure severity for all '{0}'   analyzers | What does the placeholder stand   for? We understood as "Configure severity for all analyzer tools for   '{0}'" for now. Please confirm or advise. |  
EditorFeatures\Core\xlf\EditorFeaturesResources.xlf | 0;   "_0_implemented_members" | '{0}'   implemented members | Would   you please advise what will replace the placeholder?                    [#12574667] |  
Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "Do_not_change_this_code_Put_cleanup_code_in_0_method" | Do not change this code. Put   cleanup code in '{0}' method | Please confirm if the   "code" represents "programming code". Thank you. |

**Comment by mavasani** [comment]
>What does the placeholder stand for? We understood as "Configure severity for all analyzer tools for '{0}'" for now. Please confirm or advise.

The placeholder is actually used for the category of analyzer rules. See section `Set rule severity for a category of analyzer rules:` in https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file

**Comment by mavasani** [comment]
@CyrusNajmabadi probably can help for `_0_implemented_members`?

**Comment by CyrusNajmabadi** [comment]
So `_0_implemented_members` is used when someone goes-to-definition when they're already on a definition.  i.e. they're on:

```c#
class C : IFoo1, IFoo2
{
    public void Foo() { } //<-- goto def on Foo
}

interface IFoo1 { void Foo(); } 
interface IFoo2 { void Foo(); }
```

This is the header we show when we have multiple results.  And, in this case, we woudl say

```
  'C.Foo' implemented members
      IFoo1.Foo
      IFoo2.Foo
```

**Comment by jinujoseph** [comment]
@PDostalek closing this issue as queries has been answered, feel free to ping back if you have more question.

**Comment by PDostalek** [comment]
Would you please check as well ? @jinujoseph 

SRC:Configure {0} code style
Q:What will go into the placeholder? We assumed the name of a code style for now, please advise.

SRC:Do not change this code. Put cleanup code in '{0}' method
Q:Please confirm if the "code" represents "programming code". Thank you.

**Comment by mavasani** [comment]
Please see https://github.com/dotnet/roslyn/issues/42833#issuecomment-607532458 for your question on ‘Configure {0} code style’
