### ISSUE TITLE
Update 'Origin' field in FindAllReferencesHandler once Rich-Nav is completed

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#42847]
The LSP team recently added the new [VSReferenceItem](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FLanguageServer.Protocol.Extensions%2FVSReferenceItem.cs) class to replace the now-obsolete ReferenceGroup class. This class contains the 'Origin' property that is meant to scope results from Rich-Nav. Once Rich-Nav is completed, this property should be filled out in the appropriate areas in the [FindUsagesLSPContext](http://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/CustomProtocol/FindUsagesLSPContext.cs,166) class in Roslyn.
(Work is currently in progress to migrate FindAllReferencesHandler to use VSReferenceItem instead of ReferenceGroup).

**Comment by davidwengier** [comment]
This will be needed for SourceLink support in FAR

**Comment by CyrusNajmabadi** [comment]
Closing out.  We either shoudl do this (and thus assign it a milestone) or accept it's not getting done and not have it just sitting around forever.
