### ISSUE TITLE
Optimize dictionaries keyed by language name

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#42851]
Currently we use various dictionaries when we need to group data by language:
- `ConcurrentDictionary<string, Value>`
- `ImmutableDictionary<string, Value>` 
- `Dictionary<string, Value>`

These dictionaries will usually have 1 or 2 entries (C#, VB), rarely we might also need to store data for other language than C# or VB (although we should mostly not need to track any data for non-Roslyn languages).

We can use the following simple map implementation instead to save memory:

```C#
struct LanguageMap<TValue> where TValue : class
{
   private TValue? _cs;
   private TValue? _vb;
   private (string, TValue)[]? _other; // only if we actually need this

   bool TryGetValue(string languageName, out TValue value)
   {
      return languageName switch 
      {
         LanguageNames.CSharp => _cs,
         LanguageNames.VisualBasic => _vb,
         _ => ... _other ...
      }
   }

   GetOrAdd() ... Interlocked.CompareExchange(ref _cs, factory(), null);
}
```

**Comment by CyrusNajmabadi** [comment]
Don't we have a SmallDictionary that would work well for this as well?  it would only need like two avl nodes in practice right?

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we have cases where this would be worthwhile, we can make those changes, esp. given perf data indicating an issue.
