### ISSUE TITLE
Code cleanup option to remove unused namespaces

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#42856]
Create a code cleanup option to remove unused namespaces.

**Comment by mikadumont** [comment]
Direct customer ask copying here:

>I’d like to be able to run it on an entire solution / project / current file, on demand, not tied just to reference removal. There’s multiple reasons why this could happen
>-	Folks may have copied them from a different cs file and don’t need them all
>-	Some code was refactored away and namespaces weren’t updated, etc 
>-	Accidentally leftover (e.g. from debugging).

>I’ll open cs files and quite often notice that namespaces aren’t being used. Instead of removing these on a file-by-file basis, I’d love to do it on the entire sln.

**Comment by CyrusNajmabadi** [comment]
> I’ll open cs files and quite often notice that namespaces aren’t being used. Instead of removing these on a file-by-file basis, I’d love to do it on the entire sln.

**Comment by mikadumont** [comment]
Closing this since the user meant removing usings and not namespaces.
