### ISSUE TITLE
could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#42865]
**Version Used**: 16.5.1

When I push my commit, I get this error, and I must push more than 10 times to resolve this error:

Git failed with a fatal error.
HttpRequestException encountered.
   ��������ʱ�����
cannot spawn /c/program files (x86)/microsoft visual studio/2019/enterprise/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw32/libexec/git-core/git-askpass.exe: No error
could not read Username for 'https://github.com': terminal prompts disabled

**Comment by CyrusNajmabadi** [comment]
This is not an roslyn issue.  If yo'd like to file an issue about visual studio, please use:

![image](https://user-images.githubusercontent.com/4564579/77831886-116be600-70ef-11ea-88c7-dea3d4f95c90.png)
