### ISSUE TITLE
Forced formatting on property patterns makes them unsuitable in nested-expression locations.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#42861]
For example:

![image](https://user-images.githubusercontent.com/4564579/77813224-36674700-7064-11ea-9136-e7b37bda670f.png)

This is really an unpleasant experience.  Normally i woudl also be able to change the indentation of the property pattern here.  However, because the formatter forces this, you get warnings that your code is non-compliant.

We should follow the same approach we take for collection/object initializer where we do not mandate where you braces go.  

Note: i'm only asking for the above for *nested* expressions like this.  If you have a prop pattern in something conceptually not nested, then it's fine to force.  for example:

```c#
var x = symbol is INamespaceSymbol
{
};
```

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv

**Comment by sharwell** [comment]
Design review conclusion: we should indent the `{ ... }` relative to the first token on the line where the expression starts _if_ the expression is a condition for that statement. Examples:

```
_ = x is T
{ // Not indented relative to reference token
};

if (x is T
    { // Indented relative to reference token
    })
{
}

while (x is T
    { // Indented relative to reference token
    })
{
}

if (something
    && x is T
    { // Not indented relative to reference token
    })
{
}
```

**Comment by CyrusNajmabadi** [comment]
note: iirc at the same meeting we also discussed the formatting/alignment relaxation for `for` loops.  namely that this was acceptable formatting:

```c3
for (int i = ...;
     ...;
     ...)
{
}
```

This is because the alignment aids readability, but doesn't come with the downside of being aligned to a variable width prefix.  i.e. `for (` is always 5 spaces, so there's no conern about things like a rename causing all the alignment to break, like it can when you align parameters like so:

```c#
public void Foo(int i,
                int b,
                int c)
{
}
```

I assume the same conclusion for 'for loops' applies to other prefixed condition statements.  i.e. it should be fine to align like so:

```c#
while (x is T
       { // Aligned with condition of statement
       })
{
}
```

I would want this to be the case.  we have a lot of precedence for 'alignment' of complex, braced, expressions.  We know from our own code and from customer projects that *aligning* the braces (and not jut *indenting* them) is an important facility that we need to be cognizant of.

**Comment by sharwell** [comment]
@CyrusNajmabadi Our discussion crossed to that topic, but it would be a separate issue from this one.

**Comment by CyrusNajmabadi** [comment]
The concepts overlap.  So i think it's relevant to call out here that the above 'design' is not 'set in stone', but is very dependent on the result of htat other conversation.  I didn't see anything in this conversation mentioning that, so i think it's relevant to have this here. :)
