### ISSUE TITLE
Representation of operator true invocation

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/roslyn#4287]
In this code:

```
class C {
    public static bool operator true(C c) { return false; }
    public static bool operator false(C c) { return false; }

    public void M() {
        var c = new C();
        if (c) { // <------------
            int x = 0;
        }
    }
}
```

Is the fact that the marked line invokes operator true somehow represented?
- `SemanticModel.GetSymbolInfo(ifStatement).Symbol` is null
- `SemanticModel.GetSymbolInfo(ifStatement.Condition).Symbol` is the LocalSymbol c
- `SemanticModel.GetTypeInfo(ifStatement.Expression).ConvertedType` is `C`

**Comment by CyrusNajmabadi** [comment]
IOperation should include this information.  That would be the recommended way to get this now.
