### ISSUE TITLE
IDE0071 needs to factor in whether the type implements IFormattable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#42887]
**Version Used**: 
3.6.0-2.20167.1+926207070b0c62d6a76aec4627ec26dee17870bb

**Steps to Reproduce**:
```C#
using System;

class Program
{
    static void Main()
    {
        MyType t = default;
        string s = $"{t.ToString("X")}";
        Console.WriteLine(s);
    }
}

struct MyType
{
    public string ToString(string format) => format;
    public override string ToString() => "hello";
}
```

**Expected Behavior**:
IDE0071 isn't offered, because MyType doesn't implement IFormattable.

**Actual Behavior**:
IDE0071 is offered, and changes the code from `$"{t.ToString("X")}"` to `$"{t:X}"`.  The former was using the `ToString(string)` method, but as the instance doesn't implement IFormattable, the latter will end up just using the `ToString()` overload, changing the meaning of the program.  Before the refactoring, this would output "X", and after, it outputs "hello", as the format string gets ignored.

**Comment by CyrusNajmabadi** [comment]
@jnm2

**Comment by jnm2** [comment]
I thought about this about but obviously didn't think it through. Thanks!
