### ISSUE TITLE
Getting solution

### ISSUE THREAD

**Issue by typicalHuman** [dotnet/roslyn#42891]
I need to get existing solution. I used MSBuildWorkspace, but there're 0 projects in solution, what I can do? (variant with AdhocWorkspace doesn't work too)
`using (var workspace = MSBuildWorkspace.Create())
            {
                var solution = workspace.OpenSolutionAsync(SolutionPath).Result;
            }`

**Comment by CyrusNajmabadi** [comment]
If you listen to `workspace.WorkspaceFailed` do you get notified about any issues?

**Comment by sharwell** [comment]
Duplicate of #41331
