### ISSUE TITLE
CS0649 not suppressed despite SuppressMessageAttribute

### ISSUE THREAD

**Issue by Happypig375** [dotnet/roslyn#42904]
**Version Used**: VS16.5.1

**Steps to Reproduce**:

1. Clone https://github.com/verybadcat/CSharpMath **with submodules**
2. Open `CSharpMath.sln`
3. Open `_Core` folder -> `CSharpMath.Rendering` project -> `_IgnoreTypographyWarnings.cs` file
4. Build solution

**Expected Behavior**: CS0649 is suppressed like other warnings

**Actual Behavior**: `SuppressMessageAttribute` works for other warnings but not CS0649
![image](https://user-images.githubusercontent.com/19922066/77941948-886ecd80-72ed-11ea-9d49-eb52c2703f78.png)

**Comment by jcouv** [comment]
Looking at the compiler source code, I see:
`                // SuppressMessage attributes do not apply to compiler diagnostics.`

I'm not sure where that is documented. I'm adding a note to docs (PR https://github.com/dotnet/dotnet-api-docs/pull/4055) and closing this issue as by-design. Thanks
