### ISSUE TITLE
intellisense does not fire up when typing generic (extension) "<" without having semicolon/valid expression afterwards - e.g. when adding a new line of code between existing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42908]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/967415/intellisense-does-not-fire-up-when-typing-generic.html)._

---
intellisense does not fire up when typing generic (extension) "<" without having semicolon/valid expression afterwards - e.g. when adding a new line of code between existing.

example - does not show intellisense of the generic syntax:

Application.Instance.GetService<|(cursor)> // automatically appearing closing generic greater than symbol
var root = new SqlContext<object>(); // existing line of code..

example - intellisense shows up of the generic syntax:

Application.Instance.GetService<| (cursor); // already typed semicolon - also works if this comment is actually in place - a finalizer to the statement basically
var root = new SqlContext<object>();

---
#### Visual Studio Feedback System on 3/30/2020, 00:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/4564579/222204062-86441255-37ce-4e36-bb93-963f9a69dfea.png)
