### ISSUE TITLE
inline experience to show derived classes/implementations

### ISSUE THREAD

**Issue by SathishRanjan** [dotnet/roslyn#42915]
resharper shows like this

![image](https://user-images.githubusercontent.com/25996766/77957255-d6d19b80-72f0-11ea-91a9-2ee226b881f7.png)

I would love to have inline experience for ctrl+f2
however currently ctrl+F2 show the same as search search in a different window

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @mikadumont @kendrahavens  i wrote this feature a while back (though it showed up in the left gutter-bar next to symobls).  But it didn't ship due to the editor wanting all this stuff to go through the find-refs window.  Should we rethink that?

**Comment by mikadumont** [comment]
I would love to rethink this. @jinujoseph what are your thoughts?

**Comment by CyrusNajmabadi** [comment]
@dpoeschl do you have a screenshot of what my system used to look like?

**Comment by jinujoseph** [comment]
i think we did discuss this with Editor before and there were concerns of icons in the editor margin which interfere with the breakpoint, but I could be wrong here 
ya, I think we should rethink this , David if you can add the screenshot that will be helpful.
@olegtk do you remember anything about the discussion around this.

**Comment by CyrusNajmabadi** [comment]
We could always do this with another gutter.  or just say that you right click on that line to make a BP or something.

**Comment by dpoeschl** [comment]
I'm personally okay with another (optional) margin for this, but I understand arguments against using real estate for that.

I don't have any screenshots from back in the day, but also wanted to tag @sharwell who I think has brought up something similar before.

**Comment by olegtk** [comment]
This is ultimately UX question, I suggest discussing it wih Dante. But yes, vertical margins don't scale and there is strong pushback for adding new ones (we still get negative feedback about LightBulb margin and how it cannot be disabled).
Have you considered using CodeLens to display this data?

**Comment by mikadumont** [comment]
CodeLens is hard to navigate with a keyboard in my opinion. What if we gave users an option to opt out if they find it too distracting?

**Comment by CyrusNajmabadi** [comment]
> Have you considered using CodeLens to display this data?

As someone who turns off codelens immediately due to the vertical impact, i would not want that.

**Comment by CyrusNajmabadi** [comment]
I'm not seeing the issue with a gutter/margin, esp if the user can just right click on it and say "disable".

**Comment by olegtk** [comment]
There is substantial amount of customers who feel equally negatively about horizontal impact of vertical margins.
The trouble with disabling the margin is that it basically disables the feature for a subset of customers, or you need to support another way of displaying the same information. If we let LightBulb margin to be disabled we need an alternative UX for the Ctrl+. command, I addition to margin based LightBulb.

**Comment by CyrusNajmabadi** [comment]
> The trouble with disabling the margin is that it basically disables the feature for a subset of customers, or you need to support another way of displaying the same information.

Why?

That's the first i've heard of such a requirement.  If, for example, i disable "use map mode" for the scroll bar, i don't need some other feature to give me the same functionality of displaying that information.  

If i disable "codelens" i don't have some other feature in the editor to show me the ref count.  Instead, i need to run 'find references'.  The same would hold here.  If you don't want the way to conveniently get at ths info in the editor, you could always just use the existing verbs to do the search and have the results show up in the find-refs window.

Right?

**Comment by olegtk** [comment]
Exactly, in all your examples there is an alternative way of using a feature that is pretty obvious to fall back to. If this is true for this feature, then I agree it makes sense to add a disable-able margin.
But it might be not true for all features though.

But then there is also a context issue with using a margin. All features using vertical margins typically operate in the context of the whole line (LightBulb shows suggestions for all issues on a line, bookmarks, breakpoints are marking a line), and when they don't (breakpoint for a subspan of the line text) they rely on additional visualization (breakpoint text highlighting for example).
What if there are several sources of data on the same line, e.g. "interface IFoo: IBar", do you plan the margin to only indicate implementations of IFoo and not IBar?

**Comment by CyrusNajmabadi** [comment]
> do you plan the margin to only indicate implementations of IFoo and not IBar?

Correct.  This would be more declaration driven.  We could explore doing this for reference points as well.  Perhaps a new sort of local-light-bulb that is triggered with a different key binding?

**Comment by Youssef1313** [comment]
I think this can be closed now? Inheritance margin addresses this request.

**Comment by CyrusNajmabadi** [comment]
Closing out as subsumed by inheritance margin.
