### ISSUE TITLE
Intellisense incorrectly shows Members of Struct which is the parameter of a lambda being passed to a function.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42910]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/967116/intellisense-incorrectly-shows-members-of-struct-w.html)._

---
<p>When passing a lambda with a Nullable Struct as a parameter to function, IntelliSense will incorrectly show Members of Nullable&lt;T&gt; instead of the struct itself after Null Coalescing the parameter.</p><p>See Attachments for an example</p><p>Minimal reproducible example:</p>

```C#
using System;

struct TestStruct
{
    public int TestField;
}

class Program
{
    // When dotting into x? it shows the Members of Nullable<TestStruct> instead of TestStruct
    static void Main(string[] args) => TestMethod1(x => { return x?.});

    static void TestMethod1(Predicate<TestStruct?> predicate) => predicate(null);
}
```
---
#### Visual Studio Feedback System on 3/29/2020, 10:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
@dpoeschl is this already fixed ?

**Comment by dpoeschl** [comment]
Looks fixed to me on latest `master`:

![image](https://user-images.githubusercontent.com/235241/78199229-e7445c00-743f-11ea-88c2-eb11e2e19551.png)

**Comment by dpoeschl** [comment]
This is still broken. I don't know when it broke, but at a minimum it is a regression from Visual Studio 2017.
