### ISSUE TITLE
Convert ternary operator to if statement

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#42921]
Have an option to convert a ternary operator to an if statement.

**Comment by YairHalberstadt** [comment]
@jnm2 were you working on this?

**Comment by jnm2** [comment]
Yes, it got buried. I'm more than happy to move on to the next thing on my list if you're interested. Work was nine months ago (really?) at https://github.com/dotnet/roslyn/compare/master...jnm2:conditional_to_if

**Comment by SomeoneIsWorking** [comment]
This is still not available right?

**Comment by CyrusNajmabadi** [comment]
@SomeoneIsWorking no, this is in our backlog. But it's also something we would accept a contribution on. Thanks!

**Comment by CyrusNajmabadi** [comment]
Going to look at doing this while it's still rainy outside.

**Comment by CyrusNajmabadi** [comment]
@SomeoneIsWorking this has been added now.
