### ISSUE TITLE
Choosing an event changes my code / Select Event changes my code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42927]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/911066/choix-dun-evenement-change-mon-code-select-event-c.html)._

---
I have a datasource powered by an object list.
Compilation of code, functional app

I add an event and my code is replaced by enumerable...
compilation not possible.

Cf Attachment

---
#### Visual Studio Feedback System on 2/10/2020, 01:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/12/2020, 07:27 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Visual Studio Feedback System on 3/30/2020, 11:45 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is an issue with expansion/simplification.  THe user starts with:

![image](https://user-images.githubusercontent.com/4564579/82373330-48b19180-99d2-11ea-8117-39042a3fda74.png)

After inserting an event with the navbar, they end up with:

![image](https://user-images.githubusercontent.com/4564579/82373437-6b43aa80-99d2-11ea-965a-84104a677691.png)


Note: i'm not sure why there's an error in the new code, but that's likely why simplification isn't working.

Also, i don't know why event-insertion would cause complexification anywhere...

**Comment by jasonmalinowski** [comment]
> Also, i don't know why event-insertion would cause complexification anywhere...

Can event insertion trigger adding using statements?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44407
