### ISSUE TITLE
Why does "Microsoft.CodeAnalysis.Scripting.Common" need a fixed version from "Microsoft.CodeAnalysis.Common"?

### ISSUE THREAD

**Issue by StefH** [dotnet/roslyn#42935]
When I look at the NuGet dependencies for:
`Microsoft.CodeAnalysis.Scripting.Common - 3.4.0`, I see this:
![image](https://user-images.githubusercontent.com/249938/78011778-563c8a80-7344-11ea-9f6a-d5917fa5e2b1.png)

Why is an *exact* version 3.4.0 needed ? And not just => 3.4.0 ?

See also
- https://github.com/dotnet/roslyn/issues/31441

**Comment by sharwell** [comment]
The scripting libraries use internal APIs from other layers. There is no guarantee that these will work except when the versions are an exact match. For example:

https://github.com/dotnet/roslyn/blob/75fb12b5cb179a244830647729449e04eab47834/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj#L54

In other words, this dependency _is_ a true version-locked dependency.

**Comment by StefH** [comment]
This design makes using/referencing the `Microsoft.CodeAnalysis.CSharp.Scripting` in another project (like https://www.nuget.org/packages/CS-Script.Core/) impossible because when you use another library like (Microsoft.VisualStudio.Web.CodeGeneration.Design) you cannot install this:

> Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.1: Microsoft.CodeAnalysis.Common (= 3.3.1)
> CS-Script.Core 1.3.1: Microsoft.CodeAnalysis.Common (= 3.4.0)

**Comment by jmarolf** [comment]
You should be able to pick a version that matches the dependency for `Microsoft.VisualStudio.Web.CodeGeneration.Design`. Is that not possible?

**Comment by sharwell** [comment]
> Microsoft.VisualStudio.Web.CodeGeneration.Design
> CS-Script.Core

Neither of these packages has access to the internal APIs. I'm not sure why they would use fixed versions.

**Comment by StefH** [comment]
`CS-Script.Core` uses Microsoft.CodeAnalysis.Scripting.Common 3.4.0 which needs a fixed version Microsoft.CodeAnalysis.Common (= 3.4.0) 

`Microsoft.VisualStudio.Web.CodeGeneration.Design` uses this path:
Microsoft.VisualStudio.Web.CodeGeneration 3.1.1 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 3.1.1 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 3.1.1 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 3.1.1 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 3.1.1 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).
Which ends in using a fixed version 3.3.1

So it's impossible to install these 2 libraries in 1 single project.
Normally when using => 3.3.1, this works out fine.

**Comment by sharwell** [comment]
Have you tried explicitly installing Microsoft.CodeAnalysis.CSharp.Workspaces version 3.4.0 in the same project?

**Comment by StefH** [comment]
This indeed solves the issue (because it's allowed to install a higher version for Microsoft.CodeAnalysis.CSharp.Workspaces)

![image](https://user-images.githubusercontent.com/249938/78040895-5e122400-7370-11ea-895d-abcf3721e7b8.png)
