### ISSUE TITLE
IDE0071 (Interpolation can be simplified) - invalid suggestion on ref structs

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#42936]
**Version Used**: VS 16.5.0

**Steps to Reproduce**:

```c#
ReadOnlySpan<char> span = "test";
var str = $"{span.ToString()}"; // IDE0071 
```

**Expected Behavior**:

Do not suggest IDE0071 since removing `ToString()` is invalid for ref structs.

**Actual Behavior**:

IDE0071 is suggested.

**Comment by CyrusNajmabadi** [comment]
@jnm2 :-)

**Comment by jnm2** [comment]
Noice, will do today at some point
