### ISSUE TITLE
Report error using built-in native integer operators with -langversion:8

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42941]
Report error for `F1 * F1` below:

`csc.exe /t:library /langversion:preview a.cs`
```C#
public class A
{
    public static nint F1;
}
```

`csc.exe /t:library /r:a.dll /langversion:8 b.cs`
```C#
class B : A
{
    static void Main()
    {
        F1 = F1 * F1; // error: nint operator not available
    }
}
```

See https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-03-25.md

**Comment by jcouv** [comment]
@cston Can this be closed?

**Comment by jaredpar** [comment]
Just verified that the behavior still reproduces in the main branch.
