### ISSUE TITLE
In C# interactive window Console.Writeline without an ending ...

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#4295]
semicolon, prints an extra void. If semicolon is put then there is no void printed.

Console.WriteLine ("test")
test
<void>

**Comment by Pilchie** [comment]
I believe this is by design.  If the thing entered is an expression, then Interactive window displays it's value.  If it's a statement, it doesn't.

**Comment by tmat** [comment]
Yes, by design.
