### ISSUE TITLE
"use var" false positive in switch expression

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#42958]
**Version Used**: 16.6 Preview 2

**Steps to Reproduce**:

1. Paste C#:

```C#
class Base { }
class Derived1 : Base { }
class Derived2 : Base { }

class Test
{
    object M()
    {
        Base result = 0 switch
        {
            1 => new Derived1(),
            2 => new Derived2(),
            _ => throw new System.Exception()
        };

        return result;
    }
}
```

2. Turn on all "Prefer 'var'" preferences in Tools | Options | Text Editor | C# | Code Style | General, with severity set to Warning

**Expected Behavior**: No warning about the use of explicit type `Base` in the declaration of `result`

**Actual Behavior**: Warning about the use of `Base` in the declaration of `result`. When you take the fix, it no longer compiles because the switch expression can't find a base type to use.

**Comment by CyrusNajmabadi** [comment]
This was fixed:

![image](https://user-images.githubusercontent.com/4564579/222273760-959aa06d-e740-49a3-9739-05f83a75a22d.png)

You only get 'use implicit type' when safe:

For example:

![image](https://user-images.githubusercontent.com/4564579/222273801-db739cc6-558b-41d0-a2c4-00e8c58e4c9c.png)

![image](https://user-images.githubusercontent.com/4564579/222273824-609ca7f4-59cf-41a3-8167-ef3afafa3bff.png)
