### ISSUE TITLE
Native integer type symbols should implement all interfaces from underlying types

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#42957]
The symbols representing `nint` and `nuint` should implement all of the interfaces implemented by the underlying types `System.IntPtr` and `System.UIntPtr`, with type argument substitution as needed.

For instance if `System.IntPtr` implements `ISerializable, IEquatable<IntPtr>, IComparable<IntPtr>`, then `nint` should implement `ISerializable, IEquatable<nint>, IComparable<nint>`.

See https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-03-25.md#interfaces-on-nint

**Comment by tannergooding** [comment]
Just for reference, also implementing `IComparable`, `IComparable<T>`, and `IFormattable` was reviewed/approved for .NET 5: https://github.com/dotnet/runtime/issues/21943
