### ISSUE TITLE
Compiler Error CS0246 Not Produced in Certain Contexts

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/roslyn#42974]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 3.5.0-beta1-19606-04 (d2bd58c6)

**Steps to Reproduce**:

1. Create a new MVC project. `dotnet new mvc`
2. Open `Program.cs` and add the following to the `Program` class.

```
        private int currentCount = 0;

        private void CS0246_Thrown()
        {
            RenderTree
            Console.WriteLine(Convert.ToString(currentCount++));
        }

        private void CS0246_Not_Thrown()
        {
            RenderTree
        }
```

Repro Repo: https://github.com/TanayParikh/missing-cs0246-error-repro

**Expected Behavior**:
In both methods, the line with `RenderTree` should have the `CS0246` [(namespace could not be found) error](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246). 

**Actual Behavior**:
The first `RenderTree` has that error, the second does not.

Video Demo: https://github.com/TanayParikh/missing-cs0246-error-repro/raw/master/Missing_CS0246_Demo.mov

**Comment by YairHalberstadt** [comment]
This is because they are parsed differently, as the compiler tries to recover from the syntax error using the surrounding context.

The first is parsed as a local declaration statement, and so reports:
> error CS0246: The type or namespace name 'RenderTree' could not be found (are you missing a using directive or an assembly reference?)

The second is parsed as an identifier, and so reports:
> error CS0103: The name 'RenderTree' does not exist in the current context

**Comment by TanayParikh** [comment]
Thanks for the clarification @YairHalberstadt!
