### ISSUE TITLE
Impossible pattern doesn't produce compile time error

### ISSUE THREAD

**Issue by Pzixel** [dotnet/roslyn#42979]
**Version Used**: 
16.5.0
**Steps to Reproduce**:

```cs
using System;
public class C
{
    public static void Main()
    {
        IFoo<uint> result = new Foo<uint>();
        switch (result)
        {
            case Foo<string> _:
                Console.WriteLine("Should be a compile time error");
                break;
        }
    }
}

interface IFoo<T> { }
class Foo<T> : IFoo<T> { }
```

**Expected Behavior**:
`error CS8121: An expression of type 'IFoo<uint>' cannot be handled by a pattern of type 'Foo<string>'`
**Actual Behavior**:
Compilation succeed

**Comment by Pzixel** [comment]
Making `Foo` sealed solves the problem.

**Comment by CyrusNajmabadi** [comment]
TO add more info: the pattern is not impossible.  Here's an example:

```
interface IFoo<T> { }
class Foo<T> : IFoo<T> { }
class Derived : Foo<string>, IFoo<uint> { }
```

As far as the switch is concerned, `result` may be an instance of a type it doesn't know about that does implement this interface and which subclasses this type.  So it's totally possible.  

Once you seal the class, the compiler can know that there can't be this type `Derived` somewhere in the wild that it might be encountering.
