### ISSUE TITLE
Data Leak in Bing-Powered Compiler Help

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/roslyn#4297]
Hello!

The Bing-Powered Compiler help (see links below) will generate URLs to http://bingdev.cloudapp.net which include the original error text. This poses a major data leak, since it 
a) uses HTTP instead of HTTPS, sending the data for the wholer Internet to see, and 
b) includes member names from the code base where the error occurred. 

Since the code base can contain priviledged information, this is a significant roadblock for information sensitive companies, resulting in firewall lockdowns for the bingdev.cloudapp.net or, possibly, the policy of not being allowed to use VS2015 at all.

Please change the generated url to not include information about the local code base. I.e. the information filtering for Bing done by the BingUrl.svc will have to be incorporated into Roslyn.

Best regards, Michael

http://blogs.msdn.com/b/bingdevcenter/archive/2015/07/16/need-compiler-help-bing-in-visual-studio-brings-what-you-need-in-just-one-click.aspx

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Utilities/BrowserHelper.cs

**Comment by raminrahimzada** [comment]
May be offtopic but is this a feature or anything else ?
 
![image](https://user-images.githubusercontent.com/27096288/36933285-3d2a411e-1e8b-11e8-8dfa-7e5c32803f41.png)

**Comment by heejaechang** [comment]
@jinujoseph looks like @raminrahimzada found a bug in http://bingdev.cloudapp.net 

can you let them know about this issue? I don't know their contact.

**Comment by jinujoseph** [comment]
following up
