### ISSUE TITLE
Roslyn doesn't verify variables' nullable states on exits through finally blocks

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#42981]
**Version Used**: 
```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

Compile and run the following code
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;
class C
{
    public static void Main()
    {
        if (!M(true, out var x))
        {
            x.ToString();
        }
    }
    
    public static bool M(bool b, [MaybeNullWhen(true)] out string s)
    {
        s = "";
        try
        {
            if (b)
              return false;
        }
        finally
        {
            s = null;
        }

        return true;
    }
}
```

[sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8BiTdAG3ImHLgAI5NraBYAKAAEAGOjgRgB0AEQCWEAOaYA9rBEBjKAIDCUnHACCTcgE8oIqAG52HAEx0l7AN7s6t3iZM271tnbd0RAMzoAKAIQAsj4wGHBIdFLoMHQAbhAIdAAeAJTJTu50LhkZiQIAKlIAyiEimOI+yUau2QC+6XR11bb1HADMvHwAbHTAUlLkdEG9/T3hANoBENrAcAByFOQA6gAWjMGhyQC6EVEdPFBpTZn1blB0ALx0AERXVdl0Idonzs8ZXr7Ah/cZHADsdJ4IOQoHA7rVXgDSkCdBCst9bGdLmRKGCMo0IX8HqFUQ12DUgA===)

**Expected Behavior**:
Warning for either `return false;` or `s = null;` in the finally block containing `return false;` statement

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by jcouv** [comment]
Good catch.

I think this was fixed already in master (since March 10th, I think it was PR https://github.com/dotnet/runtime/pull/33567).

A more recent [PR](https://github.com/dotnet/roslyn/pull/42827) adds some more tests for such scenario with NotNull.

I'll add one more test for MaybeNullWhen specifically.

``` csharp
        [Fact, WorkItem(42386, "https://github.com/dotnet/roslyn/issues/42386")]
        public void NotNull_EnforceInMethodBody_Warn_TryCatch()
        {
            var source = @"
using System.Diagnostics.CodeAnalysis;
public class C
{
    public static bool TryGetValue([NotNull] out string? s)
    {
        bool b = true;

        try
        {
            if (b)
                return true; // 1
            else
                return false; // 2
        }
        finally
        {
            s = null;
        }
    } // 3
}
```
