### ISSUE TITLE
Generating syntax for `nint` and `nuint` should use those keywords

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#42986]
I'm listing a number of scenarios that are broken in similar ways. Hopefully they can be fixed with a single stone. If not, feel free to split this issue as necessary.

- ExplicitType `var x = (nint)0;` produces `IntPtr` instead of `nint`.
- Same for IntroduceLocal, GenerateImplementation (implementing an interface), GenerateOverride (typing `override` and using completion).
- Same ExtractMethod, ExtractLocalFunction, AddParameter. Those also generate `IntPtr` parameters.
- Haven't tested MetadataAsSource, but it is likely the same.

Relates to https://github.com/dotnet/roslyn/issues/38821

**Comment by CyrusNajmabadi** [comment]
> ExplicitType var x = (nint)0; produces IntPtr instead of nint.

This shouldn't be too hard to fix.  One thing we'll need though is to ensure htat we generate legally based on lang version.  i.e. if you're in a C#8 project, we should generate as IntPtr, right?

**Comment by CyrusNajmabadi** [comment]
@jcouv this should all be in: ITypeSymbolExtensions.GenerateNameSyntax/GenerateTypeSyntax.  

I think if you fix that, you'll get nearly 100% fixup.  The one challenge is generating IntPtr for C#8 and below, and nint for C#9 and above.

**Comment by jcouv** [comment]
> The one challenge is generating IntPtr for C#8 and below, and nint for C#9 and above.

I'm not sure about that. Aren't we okay generating newer syntax (generally)?

> I think if you fix that, you'll get nearly 100% fixup.

Nice. I'll take a look. We probably need to add a compiler API first.

**Comment by CyrusNajmabadi** [comment]
> I'm not sure about that. Aren't we okay generating newer syntax (generally)?

No.  Not downlevel.  When we generate we try to (modulo bugs) to generate the syntax that is legal for that project.

So, for example, when generating .Equals, we dont' use patterns if they're not available.  We dont' use `=> expr bodies` if their not available (even if the user prefers them), etc. etc.

Note: this could likely depending on the impact of the feature.  .Equals/Member-bodies are huge.  so it's really important to get it right.  if `nint` is rarely use, then the need to be 'correct' drops a lot.

**Comment by jasonmalinowski** [comment]
If you're downlevel langver, is it legal to drop back to IntPtr or will the compiler disallow it? Put another way, are nint/nuint unusably "poisioned" in that case?

**Comment by jcouv** [comment]
> are nint/nuint unusably "poisioned" [downlevel]?

If you call a C# 9 API that returns a `nint`, your C# 8 compilation will just see an `IntPtr`.
You can't write `nint` or do nint-ty things (using built-in `nint` operators) on an `IntPtr` in your C# 8 code.

**Comment by jcouv** [comment]
Merged fix into feature branch.
