### ISSUE TITLE
Regression: Linq.Expressions infers correct type but doesn't provide completions

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#42997]
This used to work before and it is now breaking some primary Razor tag helper completion scenarios.

**Version Used**: 
SDK: 3.1.300-preview-015048
VSCode version: 1.43.2
C# extension version: 1.21.16

**Steps to Reproduce**:

1. Create a new console app
2. Open it in VS Code and replace `Program.cs` content with the following content,

```c#
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ModelExpressionTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var obj = new ModelExpression();
            var list = new List<Product>();

            // Hovering over 'arg' shows that it is of type 'Product' but it doesn't show 'MyProperty' in the completion list.
            obj.Create(list, arg => arg.);
            //                         ^ - invoke completions here

            // This works as expected
            obj.Create<Product>(list, arg => arg.);
        }
    }

    class ModelExpression
    {
        public object Create<T>(List<T> list, Expression<Action<T>> expression)
        {
            return null;
        }
    }

    class Product
    {
        public int MyProperty { get; set; }
    }
}

```

3. Invoke completions at the position marked by the comments

**Expected Behavior**:
`MyProperty` is part of the completion list
![image](https://user-images.githubusercontent.com/1579269/78189088-44cbaf00-7426-11ea-95d5-6748a0ba7707.png)

**Actual Behavior**:
No `MyProperty` in completion list
![image](https://user-images.githubusercontent.com/1579269/78189121-51e89e00-7426-11ea-955b-0aa296d49a8c.png)

Note: 
Hovering over `arg` shows that it is inferred to be the correct type (`Product`) but somehow completions don't reflect that,
![image](https://user-images.githubusercontent.com/1579269/78189288-9d9b4780-7426-11ea-8987-f5bd0d2f5520.png)

Also note, this is not VS Code specific. I noticed the same behavior in VS as well.

**Comment by CyrusNajmabadi** [comment]
1. Do you have an overload with different lambda types?
2. can you provide a minimal repro (ideally without razor) demonstrating the problem?

**Comment by ajaybhargavb** [comment]
> Do you have an overload with different lambda types?

No

> can you provide a minimal repro (ideally without razor) demonstrating the problem?

The repro above is not Razor related.

**Comment by CyrusNajmabadi** [comment]
The issue mentions:

> This used to work before and it is now breaking some primary Razor tag helper completion scenarios.

> The repro above is not Razor related.

Can you still provide a more minimal repro case for us to investigate?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Minimal repro:

```c#
using System;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        // Hovering over 'arg' shows that it is of type 'Product' but it doesn't show 'MyProperty' in the completion list.
        Create(new List<Product>(), arg => arg.);
    }

    static void Create<T>(List<T> list, Action<T> expression)
    {
    }
}

class Product
{
    public void MyProperty() { }
}
```

Tagging @dpoeschl who was looking in this area.

**Comment by dpoeschl** [comment]
Confirming that this is still broken in latest `master`.
