### ISSUE TITLE
Interface method Implementation is not placing in correct order

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42993]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/967532/interface-method-implementation-is-not-placing-in.html)._

---
<p>Let say I have the following interface:</p><pre>public interface IEmployeeService
{
        Task&lt;List&lt;EmployeeDetailsViewModel&gt;&gt; GetEmployeeListAsync();
        Task&lt;EmployeeDetailsViewModel&gt; GetEmployeeDetailsAsync(int employeeId);
        Task CreateEmployeeAsync(CreateEmployeeViewModel createEmployeeViewModel);
        Task UpdateEmplyeeAsync(UpdateEmployeeViewModel updateEmployeeViewModel);
        Task DeleteEmployee(int employeeId);    
}</pre><p>Now if I implement the interface with visual studio tool tip it implementing as follow:</p><pre>public class EmployeeService : IEmployeeService
{
        public Task CreateEmployeeAsync(CreateEmployeeViewModel createEmployeeViewModel)
        {
            throw new NotImplementedException();
        }

        public Task DeleteEmployee(int employeeId)
        {
            throw new NotImplementedException();
        }

        public Task&lt;EmployeeDetailsViewModel&gt; GetEmployeeDetailsAsync(int employeeId)
        {
            throw new NotImplementedException();
        }

        public Task&lt;List&lt;EmployeeDetailsViewModel&gt;&gt; GetEmployeeListAsync()
        {
            throw new NotImplementedException();
        }

        public Task UpdateEmplyeeAsync(UpdateEmployeeViewModel updateEmployeeViewModel)
        {
            throw new NotImplementedException();
        }
}

Look at methods order in the interface has been broken in the implantation.</pre>

---
#### Visual Studio Feedback System on 3/30/2020, 00:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
>Look at methods order in the interface has been broken in the implantation.

Interfaces have no required ordering (if they're not COM).  We implement in the order we get back, which is often unrelated to the order that went in.  Note that this has been the behavior since forever, and relates more to a stylistic desire on hte part of the user, not an actual "brokeness" requirement of the language.

**Comment by patrickklaeren** [comment]
It's a bit of a pity this is viewed as stylistic. While there is indeed no _required_ ordering, it makes navigating an implementation a bit more predictable, IMO.

VS behaviour:
![devenv_YhWzN7TcsU](https://user-images.githubusercontent.com/1341180/167088860-698745ae-a707-49f1-aa3c-302a3f0f13a9.gif)

Rider/Resharper behaviour:
![rider64_aseHaFhc7c](https://user-images.githubusercontent.com/1341180/167088894-ad26e509-aea7-4474-804a-f6afd73cbda0.gif)

Given more and more functionality is being reimplemented from Resharper, is there any movement on this?

**Comment by CyrusNajmabadi** [comment]
@patrickklaeren this is on the backlog right now. However, we would likely take a pr on this of you wanted to contribute it. Thanks!

**Comment by janseris** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/5200#issuecomment-1116463596
> This code fix is implemented in Roslyn

When will it be released? I am having this issue as well and seeing it being stale for 3 years is not good.

**Comment by CyrusNajmabadi** [comment]
@janseris see https://github.com/dotnet/roslyn/issues/42993#issuecomment-1119370141

**Comment by janseris** [comment]
@CyrusNajmabadi 
>  we would likely take a pr on this of you wanted to contribute it.
I can't see how a common programmer can develop a Visual Studio feature.

**Comment by CyrusNajmabadi** [comment]
@janseris this is all open source, and we have many community members who contribute fixes all the time :-)

Head over to our discord, meet people and get started. It's a lot of fun!

**Comment by janseris** [comment]
> @janseris this is all open source, and we have many community members who contribute fixes all the time :-)
> 
> Head over to our discord, meet people and get started. It's a lot of fun!

I am sorry. My employer needs me to code our company projects and not Microsoft code. We don't get revenue from Microsoft code while we do get revenue from our company projects.
If I wanted to code for Microsoft, I would sign up for a job in Microsoft.

**Comment by CyrusNajmabadi** [comment]
@janseris.  Sounds good.  If you change your mind at any point, we're here and available to help!  Take care :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback and no interest from community here.
