### ISSUE TITLE
CompilationUnitSyntax.GetReferenceDirectives should return ImmutableArray<T> rather than IList<T>

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#4299]

**Comment by gafter** [comment]
@cston I believe that would be an incompatible API change, no?

**Comment by cston** [comment]
It would be a breaking change. Since ImmutableArray<T> implements IList<T>, it would not necessarily lead to compile errors although there would be subtle differences in behavior. Is GetReferenceDirectives used outside of scripting scenarios though?

**Comment by gafter** [comment]
I don't know how it might be used, but this API is already in VS2015, and this would be a binary breaking change. We'd have to make a pretty compelling case for the change and/or bump the assembly version number, which we avoid doing in an update release. How would you justify the break?

/cc @AnthonyDGreen @kuhlenh @jaredpar
