### ISSUE TITLE
Ability to generate XML file for analyzers on build

### ISSUE THREAD

**Issue by laedit** [dotnet/roslyn#430]
When "Enable Code Analysis on Build" is checked in the "Code Analysis" tab of the project properties, at each build an xml file with the name "<project>.CodeAnalysisLog.xml is generated.

It seems that it contains only the analysis result for FxCop but not for individual parser like [Code Cracker](https://github.com/code-cracker/code-cracker/).

Is it possible to have an xml file by analyzer?
The content could be the informations showed in Visual Studio:
 - Severity
 - Code
 - Description
 - Project
 - File
 - Line
 - Column
 - Category
 - Help link
 - Details

**Comment by giggio** [comment]
I like this idea very much!

**Comment by srivatsn** [comment]
Yes we would like to produce a file. The CodeAnalysisLog.xml is generated by FxCop. I think we should add a switch to the compiler to output results in an xml file and maybe we can wire up VS to produce that file when the "Enable CodeAnalysis on Build" item is checked.

**Comment by giggio** [comment]
That would be awesome!

**Comment by srivatsn** [comment]
This has been implemented as an /errorlog switch.

**Comment by laedit** [comment]
Thanks for the amazing work. :smiley: 
Is this already usable in VS2015 or elsewhere?

**Comment by srivatsn** [comment]
Yes, it is in VS2015. You have to set the <ErrorLog>myLogFile.json</ErrorLog> switch in your project file and that will cause myLogFile.json to be created on a build.

**Comment by laedit** [comment]
Thanks for your answer, but I don't understand: we were talking about an xml file, is that still possible?
For the project file, is it a csproj file or the new json format?
And the "Enable CodeAnalysis on Build" is an option or not at all?

**Comment by srivatsn** [comment]
No we chose to output the results in the [SARIF Format](https://github.com/sarif-standard/sarif-spec) and not XML. The project file I was referring to is the csproj file.

If you have Roslyn analyzers installed to a project, they get run on build automatically - so the "Enable CodeAnalysis on Build" option doesn't mean much. If one wants to disable codeanalysis on build, they would simply remove the analyzers from the project.

**Comment by laedit** [comment]
Ok, thanks for the clarification.
In my csproj I have the analyzers like this:
``` xml
  <ItemGroup>
    <Analyzer Include="..\packages\codecracker.CSharp.1.0.0-rc5\analyzers\dotnet\cs\CodeCracker.Common.dll" />
    <Analyzer Include="..\packages\codecracker.CSharp.1.0.0-rc5\analyzers\dotnet\cs\CodeCracker.CSharp.dll" />
  </ItemGroup>
```
Is it there that I need to add a switch?

**Comment by laedit** [comment]
I haven't realize that it was a simple `<ErrorLog>report.json</ErrorLog>`.
Sorry for bothering and thanks for your help! :smiley:
