### ISSUE TITLE
Any way to get in-memory Assembly MetadataReference ?

### ISSUE THREAD

**Issue by john-cullen** [dotnet/roslyn#43014]
**Version Used**: 3.4.0

Hello,

I'd like to get a reference to an in-memory assembly for use in a CSharpCompilation, but the only API I can find that might allow this is marked as obsolete ( https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.metadatareference.createfromassembly?view=roslyn-dotnet )

Is there another way to accomplish this? The assembly in question does not exist on disk as it's loaded from an encrypted resource for obfuscation purposes.

Thanks,
John

**Comment by CyrusNajmabadi** [comment]
Yes, you can use `CreateFromImage` and give it the bytes of your in-memory assembly.

**Comment by CyrusNajmabadi** [comment]
Note: gitter.im/dotnet/roslyn or dicord.gg/csharp (channel #roslyn) are usually better for filing general questions.  Thanks!
