### ISSUE TITLE
Predict correct location to insert closing brace

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#43016]
If I have a statement bodied `if` where the statement is indented relative to the if (i.e. looks like it's meant to be part of the if) :

```csharp
if (true)
     return "";
```

And I append a `{` after the if:

```csharp
if (true) {
     return "";
```

Or

```csharp
if (true)
{
     return "";
```

Then the editor should work out that the matching closing brace should go after the statement, and should create the following:

```csharp
if (true)
{
     return "";
}
```

Instead of the current:

```csharp
if (true)
{ }
     return "";
```

Similar should apply for `while`, `for`, `foreach`, `using`, etc.

Intellij has this feature, and I find it makes adding multiple statements to an existing if much more smooth.

**EDIT**

The reason why this is really important for me is as follows:

I have an existing if statement which I want to add more statements to:

```csharp
if (true)
     return "";
```

Now I could use ctrl + ., followed by the refactoring to add braces, but it takes a while to teach your muscles to do that. So instead I just start typing it.

So I type:

```csharp
if (true)
{
     return "";
```

but then Visual studio add the closing brace:

```csharp
if (true)
{ }
     return "";
```

At which point I need to break out of the flow I was in to go and delete the closing brace, before continuing what I was doing. This constant minor flow break tends to take its toll, and make me concentrate less on programming, and get distracted more easily.

**Comment by alrz** [comment]
https://github.com/dotnet/roslyn/issues/16949

**Comment by YairHalberstadt** [comment]
Thanks for the link @alrz 

I think this is a really common scenario with me, and significantly impacts my coding flow. I would really appreciate if this was revisited.

**Comment by sharwell** [comment]
Design review conclusion:

We are interested in finding a way to implement this improvement, with particular emphasis on the following two cases:

1. Type <kbd>{</kbd> and press <kbd>Enter</kbd> at the **$$** location:

    ```
    if (true)
    $$    Console.WriteLine("text");
    ```

    to get this:

    ```
    if (true)
    {
        Console.WriteLine("text");
    }
    ```

1. Type <kbd>{</kbd> and press <kbd>Enter</kbd> at the **$$** location:

    ```
    if (true) $$Console.WriteLine("text");
    ```

    to get this:

    ```
    if (true) {
        Console.WriteLine("text");
    }
    ```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
