### ISSUE TITLE
Realize IOperation.ConstantValue on property access

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#43019]
Currently, we're eagerly realizing ConstantValue on IOperation node creation, which can result in `O(n^2)` space usage. We should make this lazy, so that only consumers who actually need to analyze constant values pay the space.

/cc @CyrusNajmabadi @sharwell @AlekseyTs

**Comment by CyrusNajmabadi** [comment]
Note: i believe this is affecting current customers in real world scenarios.  So we may have to consider doing this work earlier than 16.7.
