### ISSUE TITLE
MetadataAsSource should not display certain compiler attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#43028]
- TupleElementNames
- NativeInteger

Should the compiler drop those attributes from the symbols? (if so, we should also hide Dynamic, Nullable, etc)

Found in https://github.com/dotnet/roslyn/pull/42999

**Comment by RikkiGibson** [comment]
related to #42591

**Comment by jcouv** [comment]
Thanks. Closing in favor of existing issue. I'll migrate some information there

**Comment by RikkiGibson** [comment]
Looks like this was meant to be closed, feel free to follow up if that was not the case.
