### ISSUE TITLE
Clean up TemporaryStreamStorage, ITemporaryStorageWithName

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43037]
Tracking TODOs in source:

- `TemporaryTextStorage`
- `TemporaryStreamStorage`
- `ITemporaryStorageWithName`
- `SerializerService.TryWritePortableExecutableReferenceBackedByTemporaryStorageTo`

**Comment by CyrusNajmabadi** [comment]
Closing out.  These were all obsoleted and made into errors to use.
