### ISSUE TITLE
Make ICodeGenerationService and CodeGenerationSymbolFactory public

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#43056]
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/CodeGeneration/ICodeGenerationService.cs

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/CodeGeneration/CodeGenerationSymbolFactory.cs

The API needs to be polished, similar to SyntaxGenerator, and exposed as a new type SymbolGenerator. We also need to remove the duplication between the APIs in SyntaxGenerator and CodeGenerationSymbolFactory that expose similar syntax generation APIs, but latter have more richer options to control the syntax generation.

CodeFixProviders that are blocked from being able to ported to CodeStyle layer due to this functionality:
- [ ] MakeLocalFunctionStaticCodeFixProvider
- [ ] CSharpUseLocalFunctionCodeFixProvider

**Comment by CyrusNajmabadi** [comment]
Closing out.  Both of these fixers were moved down to shared layer.  We instead made these apis shareable.
