### ISSUE TITLE
Move VS integration tests to 16.5.1 machine

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#43054]
The Core-Eng team is attempting to move everyone forward to the 16.5.1 toolset. As such they've created the following queue with that Visual Studio installation: BuildPool.Windows.10.Amd64.VS2019.tmp.Open. At some point next week this toolset will roll forward into the BuildPool.Windows.10.Amd64.VS2019.Open queue (difference is no "tmp"). 

Presently we're using the buildpool.windows.10.amd64.vs2019.pre.open queue for VS integration testing. That won't be immediately impacted by this rollover. But some time in the near future the same transition to 16.5 will occur. Need to scout out the changes and make sure they work with the integration tests before we get rolled forward with the rest of the "pre" queue.

**Comment by jaredpar** [comment]
@sharwell, @JoeRobich @markwilkie

**Comment by JoeRobich** [comment]
closing.
