### ISSUE TITLE
Flaky test - Microsoft.CodeAnalysis.LanguageServer.UnitTests.References.FindAllReferencesHandlerTests.TestFindAllReferencesAsync_MultipleDocuments

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#43063]
https://dev.azure.com/dnceng/public/_build/results?buildId=587847&view=ms.vss-test-web.build-test-results-tab

**Comment by davidwengier** [comment]
Updated results: https://dev.azure.com/dnceng/public/_build/results?buildId=858041&view=ms.vss-test-web.build-test-results-tab
