### ISSUE TITLE
Local function return is confused with primary lambda return in nullability tracker

### ISSUE THREAD

**Issue by glen-nicol** [dotnet/roslyn#43071]
**Version Used**: 
.Net Core SDK 3.1.201 (3.1.3)

**Steps to Reproduce**:
[NullableWarningRepro.zip](https://github.com/dotnet/roslyn/files/4430284/NullableWarningRepro.zip)
run ```dotnet build``` on the project enclosed.

**Expected Behavior**:
No warning to be issued.

**Actual Behavior**:
Program.cs(36,32): warning CS8619: Nullability of reference types in value of type 'string' doesn't match target type 'IEnumerable<string>'.

Looks like it is confusing the return of the local function with the actual return of the lambda. I tried something similar without the lambda and I did not see the warning. So it must be locals in lambdas. Also, this was not occurring in the .net Core SDK 3.1.101.

Sorry if this is not the most appropriate place to report this issue. I saw related issues for that warning here. Such as #37468

**Comment by jcouv** [comment]
That repro uses the compiler from Roslyn 3.5. I was able to repro (with a simplified repro) on 3.5, but not on 3.6 or 3.7.
I'm not sure which of our fixes corrected the problem.
I'll add a test before closing.

```
        [Fact, WorkItem(43071, "https://github.com/dotnet/roslyn/issues/43071")]
        public void LocalFunctionInLambdaWithReturnStatement()
        {
            var source = @"
using System;
using System.Collections.Generic;

public class C<T>
{
    public static C<string> ReproFunction(C<string> collection)
    {
        return collection 
            .SelectMany(allStrings =>
            {
                return new[] { getSomeString(""custard"") };

                string getSomeString(string substring)
                {
                    return substring;
                }
        });
    }
}

public static class Extension
{
    public static C<TResult> SelectMany<TSource, TResult>(this C<TSource> source, Func<TSource, IEnumerable<TResult>> selector)
    {
        throw null!;
    }
}
";
            var comp = CreateNullableCompilation(source);
            comp.VerifyDiagnostics();
        }
```

**Comment by jcouv** [comment]
The test `LocalFunctionInLambdaWithReturnStatement` was added. Closing this issue.
