### ISSUE TITLE
Invalid "use auto property" suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/973665/invalid-use-auto-property-suggestion.html)._

---
VS suggests using an auto-property for this chunk of code:

```
    public sealed class TreeViewResult : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

private readonly List<TreeViewItem> m_items = new List<TreeViewItem>();

public List<TreeViewItem> Items => m_items;

public void AddItem(TreeViewItem item)
        {
            m_items. Add(item);
            NotifiyPropertyChanged(nameof(Items));
        }

private void NotifiyPropertyChanged(string property) => PropertyChanged?. Invoke(this, new PropertyChangedEventArgs(property));
    }
```

Accepting the suggestion results in this broken code:

```
    public sealed class TreeViewResult : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

public List<TreeViewItem> Items { get; } = new List<TreeViewItem>();

public void AddItem(TreeViewItem item)
        {
            Items.Add(item);
            NotifiyPropertyChanged(nameof(Items));
        }

private void NotifiyPropertyChanged(string property) => PropertyChanged?. Invoke(this, new PropertyChangedEventArgs(property));
    }

```

---
#### Visual Studio Feedback System on 4/1/2020, 11:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 4/3/2020, 04:16 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't tell what is actually wrong here.  The 'after' code looks 100% correct.

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out, barring anyone seeing something weird here.  If the filer wants to provide more inf, that would be helpful.

**Comment by DiskCrasher** [comment]
This looks like an invalid report. Too many hours looking at code that day.
