### ISSUE TITLE
Progression nodes on package contentFiles show gibberish

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#43089]
**Version Used**: Version 16.6.0 Preview 3.0 [30001.6.master]

**Steps to Reproduce**:

1. Create a new .NET Core Console App
2. Add `<PackageReference Include="ContentFilesExample" />` (note missing version)
3. Expand content items as they appear in Solution Explorer

**Expected Behavior**:

Added `Content`/`None` items do not have any children.

**Actual Behavior**:

Unexpected items show bits of their contents as child nodes.

![image](https://user-images.githubusercontent.com/350947/78469648-99dd2d00-7766-11ea-853d-d4e65ec26200.png)

The captions on these items come from each file's contents.

---

Note that this behaviour does not occur when the package's version is specified (e.g. `1.0.2`).

The nuspec for the package is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
  <metadata minClientVersion="3.3.0">
    <id>ContentFilesExample</id>
    <version>1.0.2</version>
    <authors>nuget</authors>
    <owners>nuget</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>A content v2 example package.</description>
    <tags>contentv2 contentFiles</tags>
    <dependencies>
      <group targetFramework=".NETStandard1.0">
        <dependency id="NETStandard.Library" version="1.6.0" />
      </group>
    </dependencies>
    <contentFiles>
      <files include="**/images/*.*" buildAction="Content" />
      <files include="**/data.txt" buildAction="Content" />
      <files include="**/tools/*" buildAction="None" copyToOutput="true" flatten="false" />
    </contentFiles>
  </metadata>
</package>
```

**Comment by CyrusNajmabadi** [comment]
Roslyn does not provide progression nodes for not-c# or vb languages. This should probably go to progression team to figure out what's going on here.

**Comment by drewnoakes** [comment]
Something's parsing the file contents as code, pulling out `exit()` as a method definition somehow, and other things as fields. //index shows only four implementations of `IGraphProvider` that could be doing this (I know it's not the dependencies node implementation).

- `Microsoft.AppInsights.GettingStarted.SolutionExplorerProvider`
- `Microsoft.VisualStudio.LanguageServices.CSharp.Progression.CSharpGraphProvider`
- `Microsoft.VisualStudio.LanguageServices.VisualBasic.Progression.VisualBasicGraphProvider`
- `Microsoft.VisualStudio.Progression.CodeProvider`

**Comment by olegtk** [comment]
Are those ancestors of Dependencies node in Solution Explorer? Nuget uses Progression to show content of dependencies.

**Comment by drewnoakes** [comment]
@olegtk

> Are those ancestors of Dependencies node in Solution Explorer?

No these are not related to the Dependencies node.

> Nuget uses Progression to show content of dependencies.

The Dependencies node is populated by the Project System. We are moving away from using progression for performance reasons, so from 16.7 onwards will no longer use progression in the dependencies tree.

**Comment by nkolev92** [comment]
Per @jinujoseph's suggestion, just mentioning that the NuGet.Client does not own that experience either.

**Comment by jinujoseph** [comment]
[routed ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1121639)
