### ISSUE TITLE
csharp_style_var_* not respected when .editorconfig is referenced from a package

### ISSUE THREAD

**Issue by hugoqribeiro** [dotnet/roslyn#43080]
Using Visual Studio 2019 16.4.6.

Consider this sample code:

```
using System;
using System.Collections.Generic;

namespace VarRules2
{
    public static class Program
    {
        public static void Main()
        {
            // 1. csharp_style_var_for_built_in_types

            var i = 10;

            // 2. csharp_style_var_when_type_is_apparent

            var list = new List<string>();

            // 3. no problem

            var x = new
            {
                Value = i
            };

            // 4. csharp_style_var_elsewhere

            var j = Calculate();

            Console.WriteLine("Hello World! i is {0}, list is {1}, x is {2}, j is {3}", i, list.Count, x.Value, j);
            Console.ReadKey();
        }

        private static MyValue Calculate()
        {
            return new MyValue();
        }
    }
}
```

If I add this .editorconfig manually to the project, build fails (as expected) in (1), (2) and (4).

```
root = true

[*]

charset = utf-8-bom
indent_style = space
indent_size = 4
insert_final_newline = false
trim_trailing_whitespace = true

# C# files

[*.cs]

# Avoid var
csharp_style_var_for_built_in_types = false:error
csharp_style_var_when_type_is_apparent = false:error
csharp_style_var_elsewhere = false:error

dotnet_code_quality.null_check_validation_methods = NotNull|NotNullOrEmpty|IsUrl|IsUriAbsolute|IsEmail|IsPhoneNumber

dotnet_diagnostic.CS1998.severity = error

dotnet_diagnostic.CA1508.severity = none
dotnet_diagnostic.CA2007.severity = error

dotnet_diagnostic.VSTHRD002.severity = none
dotnet_diagnostic.VSTHRD100.severity = error
dotnet_diagnostic.VSTHRD110.severity = error
dotnet_diagnostic.VSTHRD200.severity = error
```

Now, I want this .editorconfig to be applied to all our code base, along with a rule set to configure multiple other diagnostics (because I can't configure them correctly in the .editorconfig file).

We add it as a design-time NuGet package that has a .props file like this:

```
<Project>

    <!-- AssemblyInfo and key file -->

    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Primavera.Public.Private.snk</AssemblyOriginatorKeyFile>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    </PropertyGroup>

    <!-- .tfignore -->

    <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)\.tfignore')" >
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\.tfignore" />
    </ItemGroup>

    <!-- .editorconfig -->

    <PropertyGroup>
        <SkipDefaultEditorConfigAsAdditionalFile>true</SkipDefaultEditorConfigAsAdditionalFile>
    </PropertyGroup>
    <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)\.editorconfig')" >
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\.editorconfig" />
    </ItemGroup>

    <!-- Analyzers rule set -->

    <PropertyGroup>
        <Features>IOperation</Features>
        <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)Primavera.Analyzers.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
    
    <!-- Analyzers packages -->

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" />
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="16.5.132" />
    </ItemGroup>

</Project>
```

With this setup neither of the following cause the build to fail, as you would expect:

`csharp_style_var_for_built_in_types`
`csharp_style_var_when_type_is_apparent`
`csharp_style_var_elsewhere`

More:

- `dotnet_code_quality.null_check_validation_methods` is respected.
- Nothing else seams to be respected.

I believe this is related with #38782 and #38042.

This renders both .editorconfig and Analyzers pretty much unusable for company-wide scenarios, which is where CA makes more sense.

The confusion between .editorconfig and rule sets and between .editorconfig and packages is a mess. You really should consider bumping up the priority of this in the backlog.

**Comment by jinujoseph** [comment]
@mavasani  should we dupe this against the feature for editorconfig in shared project ?

**Comment by mavasani** [comment]
I believe this would be covered by https://github.com/dotnet/roslyn/issues/42219

**Comment by mavasani** [comment]
Tag @chsienki 

This should now be supported in VS2019 16.7 or later with  #42703 

1. You need to create a new analyzer config file with a top level entry `is_global = true` and your option settings after that.

2. Then ensure this analyzer config file gets passed to the compiler in the one of the following ways:

   1. via MSBuild:
   ```xml
       <ItemGroup>
         <EditorConfigFiles Include="<%full_path_to_config_file%>" />
       </ItemGroup>
   ```
   2. via command line arguments to csc.exe:
   ```
   /analyzerconfig:<%full_path_to_config_file%>
   ```

**Comment by hugoqribeiro** [comment]
I have tried this in Visual Studio 16.7.2 and still does not work.

The .props file in our NuGet package is as follows:

```
<Project>

    (...)

    <PropertyGroup>
        <SkipDefaultEditorConfigAsAdditionalFile>true</SkipDefaultEditorConfigAsAdditionalFile>
    </PropertyGroup>
    <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)\.editorconfig')" >
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\.editorconfig" />
        <EditorConfigFiles Include="$(MSBuildThisFileDirectory)\.editorconfig" />
    </ItemGroup>

    (...)

<Project>
```

The .editorconfigfile looks like this:

```
# This is the top most editorconfig file

is_global = true
root = true

# All files

[*]

charset = utf-8-bom
indent_style = space
indent_size = 4
insert_final_newline = false
trim_trailing_whitespace = true

# C# files

[*.cs]

#--------------------------------------------------------------------------------------------------
# Language Conventions
# https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions
#--------------------------------------------------------------------------------------------------

# Avoid var
csharp_style_var_for_built_in_types = false:warning
csharp_style_var_when_type_is_apparent = false:warning
csharp_style_var_elsewhere = false:warning

(...)
```

**Comment by mavasani** [comment]
@hugoqribeiro Please follow the steps in the prior comment https://github.com/dotnet/roslyn/issues/43080#issuecomment-634119043. You seem to have few things that are incorrectly setup in your global editorconfig:

1. Remove `root = true`, that has no meaning for a directory agnostic global editorconfig.
2. Remove all the section headers `[*]` and `[*.cs]` and such. Global editorconfig applies as the fallback for entire project and cannot be associated to specific files or folders based on section headers. Putting section headers nullifies those entries from a global config perspective.
3. Also note that global editorconfigs are **only** respected by the C#/VB compiler, not by other parts of the VS editor, so I am not sure if you should be putting formatting/whitespace related settings in it - this is not a normal editorconfig.
4. Consider renaming the global config to something like `global.editorconfig` for clarity that is is not a regular editorconfig file, just a global bag of options for C#/VB compiler.

I would just have the following in the file:
```
is_global = true

#--------------------------------------------------------------------------------------------------
# Language Conventions
# https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions
#--------------------------------------------------------------------------------------------------

# Avoid var
csharp_style_var_for_built_in_types = false:warning
csharp_style_var_when_type_is_apparent = false:warning
csharp_style_var_elsewhere = false:warning

```

**Comment by mavasani** [comment]
Also note that `SkipDefaultEditorConfigAsAdditionalFile` can be removed. You don't need to pass in the global editorconfig as an additional file. Passing .editorconfig files as additional files is a legacy mechanism for a very specific analyzer package (FxCopAnalyzers), see https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#prior-to-vs2019-163-or-using-an-analyzer-package-version-prior-to-33x for details

**Comment by hugoqribeiro** [comment]
@mavasani thank you! That's it!
