### ISSUE TITLE
#region's are no longer initially collapsed the first time a file is opened

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4309]
This is a regression from Visual Studio 2015.

**Comment by CyrusNajmabadi** [comment]
Hrmm.  I'm not sure the best way to actually support this scenario.

Right now what I observe is that we properly persist and restore whatever collapsed outlining spans the user had.  We do not seem to collapse ```#regions``` "the first time".  While this seems like an ok idea, i'm not sure how this was ever supported.  There's no way that I can tell to find out if this is "the first time".  i.e. when we open a file, we can't tell if it's the first time (and we should collapse ```#regions```), or a subsequent load (and we should not force any collapsing).

@jasonmalinowski To you know how we might be able to tell so we can auto-collapse here?

**Comment by jasonmalinowski** [comment]
There's along history of this that @pharring also knows about. We need to update our tagger to return true for [`IOutliningTag.IsDefaultCollapsed`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.text.tagging.ioutliningregiontag.isdefaultcollapsed.aspx), but that only makes sure the data is there. We also need to ensure we're calling PersistOutliningSpans in the right place and time, and making sure that we're actually returning those tags when we need it.

Note there's a performance problem with this we need to mitigate, which is we end up putting parsing and tagging on the hot path of opening a file. @pharring and I did discuss that the interface with the editor we have isn't quite robust enough to mitigate it entirely, so you might need to make tweaks there as well. We also discussed having some heuristics like simply doing a string.Contains("#region") on the C# file before doing parsing and tagging to minimize the performance hit on files that don't contain regions.

**Comment by CyrusNajmabadi** [comment]
I see.

Note: it's unclear to me that the current behavior is actually bad.  It seems like it puts the user in the most control.  We simply don't do anything with the file.  Then if the user collapses, we respect, save and restore that for the future.  

I was personally not a fan of auto-collapsing before.  So i'm wondering if this is behavior worth maintaining.

**Comment by Pilchie** [comment]
Several customers have reported missing it.  I believe we should bring it back.

**Comment by DustinCampbell** [comment]
I wouldn't say it's unreasonable to say we've gotten hate mail about breaking this one. :smile: I think this is just another case of us not using the language like everybody else. There are a lot of customers who want to hide code with ```#region``` and now it stares at them everytime their .suo is blown away. I personally experience this when opening up several of our unit tests. For example, I *just* experienced this opening up CastSimplificationTests.vb. I wanted to get to the VB tests, and had to collapse the region for the C# tests first because it wasn't auto-collapsed. I actually grumbled out loud. :smile:

**Comment by CyrusNajmabadi** [comment]
Sounds good.  I'll see about getting this working again.  Thanks!
