### ISSUE TITLE
Enable EnC of methods containing switch expressions

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43099]
Switch expressions EnC is disabled in 16.3 due to bugs:

- [x] https://github.com/dotnet/roslyn/issues/37232
- [x] https://github.com/dotnet/roslyn/issues/37261
- [x] https://github.com/dotnet/roslyn/issues/37237
- [x] https://github.com/dotnet/roslyn/issues/50301 
- [x] https://github.com/dotnet/roslyn/issues/50321

We need to revisit how closures are emitted for lifted variables declared in the switch expression.

**Comment by davidwengier** [comment]
Currently blocked by https://github.com/dotnet/roslyn/issues/50301
