### ISSUE TITLE
Completion in Interactive Window should not show "Starting Intellisense"

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43096]
Version 16.6.0 Preview 2.0 [29915.30.master]

![image](https://user-images.githubusercontent.com/41759/78518775-4541ae00-7776-11ea-9585-23471a17e274.png)

**Comment by tmat** [comment]
@AmadeusW What controls whether this is shown or not?

**Comment by AmadeusW** [comment]
This is controlled by "Partial Load Mode". @varunguptacode was the PM IIRC
I forwarded you email with details

**Comment by CyrusNajmabadi** [comment]
Roslyn doesn't own this.   This string is added externally.
