### ISSUE TITLE
csc.exe crashes building IQueryable lambda expression with string range operation

### ISSUE THREAD

**Issue by Corey-M** [dotnet/roslyn#43090]
**Version Used**: CSC.exe 3.500.20.15305, Visual Studio 16.5.2

**Steps to Reproduce**:

1. Create empty ASP.NET Core MVC project
2. Add data source that implements `IQueryable<T>` for collections
3. Create a filter such as:

    string filter = "a*";
    IQueryable&lt;Sample&gt; samples = db.Samples.Where(s => s.Name.StartsWith(filter[0..^1]));

4. Build project

**Expected Behavior**:

Compilation or error message.

**Actual Behavior**:

MSB6006 "csc.exe" exited with code -2146232797

No other error details present in output.  Running `dotnet build` produces long list of errors - refer to attached file for sample: [sample build log.txt](https://github.com/dotnet/roslyn/files/4433216/sample.build.log.txt)

Moving the string range operation outside the lambda expression or replacing it with `Substring` operations allows the project to compile without error.

**Comment by RikkiGibson** [comment]
Fixed in VS 16.6. Thanks for reporting.
