### ISSUE TITLE
Add DebuggerHiddenAttribute to BaseMethodWrapper

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#431]
Given this code:
![1](https://cloud.githubusercontent.com/assets/6464209/6163424/1a60f2f8-b247-11e4-94e0-d05b5c575044.jpg)

The Roslyn Call Stack Window shows:
![2](https://cloud.githubusercontent.com/assets/6464209/6163422/16094336-b247-11e4-81f5-76ba5394592c.png)

The old Call Stack Window showed:
![3](https://cloud.githubusercontent.com/assets/6464209/6163421/0e62125c-b247-11e4-850e-9791634c8a51.jpg)

Regarding the “D.<>n__0()” frame, we should be marking these (BaseMethodWrappers) with "DebuggerHiddenAttribute" (so they are omitted from the Call Stack Window).  These methods are an implementation detail that has no pdb information associated with them, and you cannot navigate to their implementation by double-clicking in the Call Stack Window.

**Comment by ManishJayaswal** [comment]
@v-codeel  please verify.
