### ISSUE TITLE
Run Code Analysis doesn't run code analysis, no issues in error list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43109]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/973664/run-code-analysis-doesnt-run-code-analysis-no-issu.html)._

---
[regression] [worked-in:16.4.4]
Analyze | Run Code Analysis | On Solution
no longer works.  It's supposed to run code analysis and put any issues into the Error List.
When I run it the status bar at the bottom says "Code analysis completed for 'SOLUTION NAME'
However, running CA via msbuild shows that my solution does have errors.
The project is open source so you can see for yourself:  https://github.com/OBeautifulCode/OBeautifulCode.CodeGen

---
#### surajg on 4/1/2020, 00:23 PM: 

Also, when VS says its running code analysis, nothing it written to the Output tab.
#### Visual Studio Feedback System on 4/1/2020, 08:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### surajg on 4/2/2020, 02:49 AM: 

Note that I fixed-up the Code Analysis errors so that I could move on.  You&#39;ll have to pull a prior commit to get the code into a state where there are CA errors: https://github.com/OBeautifulCode/OBeautifulCode.CodeGen/commit/e992a6ffeac4ecc2fb496191fbac5101223e6636
#### surajg on 4/2/2020, 10:08 AM: 

This got me unblocked:  https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-run-legacy-code-analysis-manually-for-managed-code?view=vs-2019<br><br>Otherwise I&#39;m pretty sure there&#39;s a bug in VS.  I have the checkbox checked for &quot;Run on build&quot; under Binary analyzers - so legacy code analysis should be running on build, but it&#39;s not.  Or maybe it is, but it doesn&#39;t output the activity to Output nor Error List.

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Starting VS2019 16.5, `Run Code Analysis` command runs source based analyzers, not legacy FxCop, which has been deprecated: https://docs.microsoft.com/visualstudio/code-quality/how-to-run-code-analysis-manually-for-managed-code?view=vs-2019. You can still run legacy analysis by setting the environment variable, as you already noted above.

We are no longer fixing issues with legacy FxCop/Code analysis or enabling commands in VS to execute it by default. Please migrate to source based analyzers by following the steps at https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers?view=vs-2019
