### ISSUE TITLE
In code analyzer: add a suggestion to change expression body property to action method in controller classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43112]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/975719/in-code-analyzer-add-a-suggestion-to-change-expres.html)._

---
I faced an unusual problem when re-creating an example from ASP.NET Core MVC book. I accidentally forgot to put parentheses in expression body controller methods
    
```
public class CustomerController : Controller
{
  public ViewResult Index => View("Results", new Result { ... });
  public ViewResult List => View("Results", new Result { ... });
}
```
This silently turned methods `Index()` and `List()` to properties `Index` and `List`, which I didn't intend to do. This in turn caused all calls to the controller to return 404 error. And although it's completely valid to have properties in controllers, this is much less common than to have action methods. And this kind of error is easy to overlook. I wasted more than an hour trying to debug this error, validating Startup class, routes, my hosts file, etc. Then I showed this error to my friends. I pointed out that the error is _in this piece of code_, and they couldn't find what's wrong.

My suggestion is to add to code analyzers a warning saying something like "_Did you mean to create an action method?_" at least for controller properties of type `IActionResult`.

Thank you in advance.

---
#### Visual Studio Feedback System on 4/3/2020, 01:21 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This shoudl be ported to ASP.Net so they can write an analyzer to detect these.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Can you close this one? I opened it for dotnet/aspnetcore.

**Comment by CyrusNajmabadi** [comment]
Sure!
