### ISSUE TITLE
Implement Edit.NextMethod and Edit.PreviousMethod commands

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4311]
The Edit.NextMethod and Edit.PreviousMethod commands are supported by Visual Basic for navigating between declarations. Unfortunately, these commands were not implemented as part of Project Roslyn. This is a regression from Visual Studio 2013 and we have received significant feedback that we need to bring them back.

**Comment by PhilipKyle** [comment]
Glad to see this issue being addressed! Not having theses shortcuts feels like having fingers cut off :)

**Comment by Pilchie** [comment]
Pulling back to 1.1 to try and finish this off.

**Comment by Pilchie** [comment]
Fixed by #6299

**Comment by PhilipKyle** [comment]
Thanks for taking care of this issue. Any insight on when it will be released?

**Comment by Pilchie** [comment]
It should be part of VS 2015 Update 1 RTM (Not the CTP or RC though)

**Comment by PhilipKyle** [comment]
cool :+1:  and when will that be released? :)

**Comment by Pilchie** [comment]
When it's ready :wink:.  Sorry, that's about as specific as I can be.

**Comment by PhilipKyle** [comment]
Oh, thats okay "dad" :) hahaha.

**Comment by DustinCampbell** [comment]
That's appropriate @phillipkyle, @pilchie is super-old.

**Comment by PhilipKyle** [comment]
@DustinCampbell yep that explains it :older_man:

**Comment by dirkesquire** [comment]
As a ping reminder to people who were experiencing this problem, like I was, I have now installed Visual Studio Update 1, and this seems to be fixed now. Their are two new NextMethod / PreviousMethod menu items in the Edit Menu, and keyboard binding shortcuts now are working as well.

**Comment by PhilipKyle** [comment]
Hello Dirk,

thanks for the reminder. I too have installed the update and the “Next Method” / “Previous Method” Shortcuts are now working albeit not exactly as expected. The Previous Method should jump to the top of the current method. Instead it actually jumps to the start of the previous method… okay okay so it is doing its name justice but it’s still not the same behavior as its predecessors. Maybe the Shortcut should be named “Top of current Method” I dunno. But still, I can live with it the way it is now. You just have to use “Previous Method” “Next Method” to get to the top of the current method.

Thanks!
Philip

Von: Dirk Roeleveld [mailto:notifications@github.com]
Gesendet: Mittwoch, 3. Februar 2016 09:02
An: dotnet/roslyn
Cc: Boone, Philip
Betreff: Re: [roslyn] Implement Edit.NextMethod and Edit.PreviousMethod commands (#4311)


As a ping reminder to people who were experiencing this problem, like I was, I have now installed Visual Studio Update 1, and this seems to be fixed now. Their are two new NextMethod / PreviousMethod menu items in the Edit Menu, and keyboard binding shortcuts now are working as well.
