### ISSUE TITLE
In the ide, be able to jump to top or bottom of loops, if-thens, etc

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43118]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/971127/in-the-ide-be-able-to-jump-to-top-or-bottom-of-loo.html)._

---
<p>I think in c# you can fake this by searching for a bracket symbol, but in VB net it would be useful.</p>

---
#### Visual Studio Feedback System on 3/31/2020, 11:33 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This is a feature request to implement the **Edit.GotoBrace** command (<kbd>Ctrl</kbd>+<kbd>]</kbd>) to support Visual Basic, where block do not use literal brace characters.

**Comment by CyrusNajmabadi** [comment]
Seems reasonable.  It not on a brace in VB, but on a Begin/End block statement, it would seem reasonable to jump to the corresponding sibling.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing these vb experiences.
