### ISSUE TITLE
Open Issues in Extension GetEnumerator

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#43147]
Tracking issue for extension GetEnumerator in `foreach` support (being implemented by @YairHalberstadt):

### LDM Questions

* [x] Should we accept extension `GetEnumerator`/`MoveNext` methods with optional parameters? We don't allow them for non-extension synchronous `foreach`, but we do allow them for asynchronous `foreach`.

### Outstanding Work Items

* [x] IOperation/CFG Support
* [x] Nullable testing

**Comment by YairHalberstadt** [comment]
> Should we accept extension GetEnumerator/MoveNext methods with optional parameters?

My current implementation doesn't accept extension MoveNext methods at all. The only possible use case is when someone has an existing GetEnumerator method which doesn't have a valid MoveNext, but does have a valid Current, and gives enough public access to correctly implement MoveNext. This seems highly unlikely.

**Comment by 333fred** [comment]
> This seems highly unlikely.

Agreed, but I want to confirm :)

**Comment by YairHalberstadt** [comment]
What should the behavior be for an Extension method accepting the first parameter by ref be:

```csharp
public static GetEnumerator(this ref Foo foo) =>...
```

The LDM decided for Deconstructors that this should be an error. See https://github.com/dotnet/csharplang/blob/98043cdc889303d956d540d7ab3bc4f5044a9d3b/meetings/2018/LDM-2018-01-24.md#deconstruct-as-ref-extension-method

I imagine same decision should apply here

**Comment by YairHalberstadt** [comment]
An instance GetEnumerator has to be public meaning this is an error:

```csharp
using System.Collections.Generic;

public class C {
    public void M() {
        foreach(var a in this)
        {
        }
    }
    
    internal IEnumerator<int> GetEnumerator() => throw null;
}
```

I would guess this is to prevent one behavior of foreach in the same assembly, and a different one outside the assembly, e.g. in the following case:

```csharp
using System.Collections.Generic;

public class C : List<int> {
    
    internal IEnumerator<string> GetEnumerator() => throw null;
}
```

Should we relax this for extension GetEnumerator, and say that it just has to be accessible?
It seems arbitrary that an public extension GetEnumerator in an internal class works, but not an internal extension GtEnumerator on a public/internal class. The reasoning for instance methods doesn't apply, since this is inherently the case with extension methods - in different contexts foreach will have different behavior.

Could we relax this for instance methods as well? I don't believe this is possible as it would change the behavior of the example given above.

**Comment by YairHalberstadt** [comment]
From the design notes:

> ### Extension GetEnumerator
> https://github.com/dotnet/roslyn/issues/43147
> 
> *Conclusions:*
> 
> No objections to the proposals as written.

My assumption is those proposals are:

1. Accept extension GetEnumerator/MoveNext methods with optional parameters.
2. Don't accept extension MoveNext.
3. Error for extension method accepting ref.
4. An extension GetEnumerator only has to be accessable, not public.

Am I interpreting the conclusions correctly @333fred?

**Comment by 333fred** [comment]
Yep, that's correct.

**Comment by YairHalberstadt** [comment]
I've done ioperation and nullable support. I'm not sure what else needs doing.

**Comment by 333fred** [comment]
Alright, I'll get the test plan filled in tomorrow and then you can go through and figure out what tests need to be added. We also need to do an IDE test pass, which you can get started on now: https://github.com/dotnet/roslyn/blob/master/docs/wiki/Manual-Testing.md#newlanguagefeaturetesting

**Comment by YairHalberstadt** [comment]
The only thing in IDE which I think will be relevant is testing Find All References, seeing as we add no new constructs, and have no location which we can use to navigate to the extension get enumerator.

The only potential refactoring/code fix that might be useful is a code fix to generate an extension GetEnumerator, but I think that seems of dubious value, and definitely isn't urgent.

I am testing FindAllReferences now.

**Comment by YairHalberstadt** [comment]
I've tested FindAllReferences and can confirm it works

**Comment by YairHalberstadt** [comment]
PR for FindAllReferences test at https://github.com/dotnet/roslyn/pull/45160.
I've also tested it manually in VS

**Comment by 333fred** [comment]
This is complete.
