### ISSUE TITLE
Work scheduler should prefer to complete operations requiring temporary storage

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43143]
**Version Used**: 16.6 Preview 2

In several memory investigations, I have observed situations where a large number of temporary storage stream buffers are held by callback actions of tasks that are scheduled but not yet complete. I believe this occurs during the processing of many `ReadTextAsync` operations:

https://github.com/dotnet/roslyn/blob/9bdb18aec903d4a628f107f749d31e296770c9a1/src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs#L232-L245

It may be possible to reduce virtual memory usage within a 32-bit process by modifying the way operations are scheduled to prefer completing the processing of an already-mapped stream to the creation of a new one. For example, a read delay proportional to the total size of currently mapped views could be used to delay the creation of new views.

#### Known reports

https://developercommunity.visualstudio.com/content/problem/977186/visual-studio-random-crash.html

**Comment by samrueby** [comment]
Is there a way I can coincidentally avoid hitting this? Somehow...having less memory paged-out?

**Comment by sharwell** [comment]
@samrueby we don't currently have a workaround for this. We are working to move a bunch of this processing out of devenv.exe which should avoid the issue, but I'm not sure which release that work will ship in.

**Comment by samrueby** [comment]
Running into this problem frequently, I think part of the problem description might not be completely accurate. That part is "scheduled but not yet complete". Maybe it's just a coincidence, but I feel that a lot of time can pass between the operations that trigger this for me. I think if I perform that operation once, Visual Studio will handle it fine. If I perform that operation twice, Visual Studio will probably handle it fine. But if I do it three or four times- it'll take VS out. The thing is, 20 minutes to an hour could pass before attempt 3 or 4. That would indicate to me that some things that get scheduled, never complete.

Just an observation that may be helpful to this investigation.
