### ISSUE TITLE
Lost underscores on VB

### ISSUE THREAD

**Issue by scascalesageinfoes** [dotnet/roslyn#43141]
Hello

**Version Used**: 
VS2019 COmmunity

**Steps to Reproduce**:
'Before
myString = "ABC" & _
           "DEF"

'After
myString = "ABC" & 
           "DEF"

**Expected Behavior**:
DOnt' remove underscores

**Actual Behavior**:
Ctrl K+ D remove underscores.. and when typing too

More info; https://social.msdn.microsoft.com/Forums/vstudio/en-US/cf6298c5-e720-404d-9e9c-32aee1347b26/prevent-visual-studio-2015-from-removing-line-continuation-characters-in-vbnet-files?forum=vsdebug

**Comment by jrmoreno1** [comment]
I believe this is by design, there is an option for pretty printing, which controls this.

**Comment by scascalesageinfoes** [comment]
More info: https://social.msdn.microsoft.com/Forums/vstudio/en-US/cf6298c5-e720-404d-9e9c-32aee1347b26/prevent-visual-studio-2015-from-removing-line-continuation-characters-in-vbnet-files?forum=vsdebug

**Comment by scascalesageinfoes** [comment]
If i disable Pretty listing i lost amount of formats

**Comment by CyrusNajmabadi** [comment]
Yes.  This is by design.  Pretty-printing in VB is all-or-nothing.  And this was an intentional cleanup as this is redundant information that can be cleaned up.

**Comment by scascalesageinfoes** [comment]
I disable pretty-printing but the real problem is "Ctrl K+ D remove underscores.. and when typing too"

**Comment by jrmoreno1** [comment]
Formatting the document is just another way of saying pretty print.  The IDE isn't a text editor, and never acts as just a text editor.

**Comment by scascalesageinfoes** [comment]
IS there any change to replace pretty-editing with some more advanced?

**Comment by CyrusNajmabadi** [comment]
@scascalesageinfoes what did you have in mind?

**Comment by paul1956** [comment]
@CyrusNajmabadi there is an open issue covering _ formatting https://github.com/dotnet/roslyn/issues/36891 though it might be the opposite of this.
