### ISSUE TITLE
UseExpressionBodyForLambdaCodeStyleProvider needs to be rewritten to decouple analyzer and code fix/refactoring pieces

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#43148]
See https://github.com/dotnet/roslyn/tree/master/src/Features/CSharp/Portable/UseExpressionBodyForLambda

Current implementation has a tight coupling between analyzer, code fix and refactoring and is implemented within the same type. Given that we have CodeStyle analyzers and fixers separated into different projects in the CodeStyle layer, we need to split the implementation into separate types, such that analyzer code does not require any syntax editing. Once that is done, we can move these to the shared layer and include them in CodeStyle NuGet package.

**Comment by CyrusNajmabadi** [comment]
Note: one of the reason for the tight coupling here is how much logic needs to be shared.  i.e. the refactoring shouldn't be shown if the code fix is shown (and vice versa).  And there are subtleties about hidden diagnostics and whatnot.

What we *can* do is pull out a common helper type and hten mix-that-in into our actual analyzer/fix/refactoring to just delegate all responsibility to.  i strongly proposed this a while back, but you closed my proposal ;'(

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
