### ISSUE TITLE
Address issues from review of https://github.com/dotnet/roslyn/pull/43062

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#43155]
The following comments from the review of https://github.com/dotnet/roslyn/pull/43062 should be addressed:
- Move nested `using` directives in `ValueSetFactory.NintValueSet.cs`
- Document `_hasSmall` and `_hasLarge` in the same file.
- unused using directive in `ValueSetFactory.IntTC.cs`

**Comment by RikkiGibson** [comment]
- unused using directive in `ValueSetFactory.IntTC.cs`

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/43421
