### ISSUE TITLE
XML comments do not show up for the array operator

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/roslyn#43164]
Originally reported at https://github.com/OmniSharp/omnisharp-vscode/issues/3434

**Version Used**: I don't know, whatever Visual Studio and VS Code come with.

It seems that XML comments placed on the array operator do not ever show up outside of the source file. The summary shows up when hovering over "this" and parameters in the source file, but not the generated file, and not when it's used.

**Steps to Reproduce**:

Source:
```cs
        /// <summary>
        /// Access matrix elements.
        /// </summary>
        /// <param name="column">The column.</param>
        /// <param name="row">The row.</param>
        public float this[int column, int row] // not shown: the body of this operator
```
Generated "[metadata] File.cs" from "Go to Definition":
```cs
        //
        // Summary:
        //     Access matrix elements.
        //
        // Parameters:
        //   column:
        //     The column.
        //
        //   row:
        //     The row.
        public float this[int column, int row] { get; set; }
```

**Expected Behavior**:

With methods, fields, and classes, if there's a summary, you can hover over them to view it, and it shows up in the intellisense context menu when you are writing code. I would expect to be able to do the same with the array operator.

I can tell that the XML summary is recognized by C# itself in Mono 6.4 because it shows up in the "[metadata]" as shown above, and shows up when viewing the source file with VS Code and this extension and hovering. 

**Actual Behavior**:

For this code snippet, where `b` is an instance of the structure with the above operator:

```cs
b[0, 0] = 5.0f;
```

Nothing shows up when writing code, and I am not able to hover over the `[]` to see the summary, nor can I hover over the numbers to view the parameter documentation.

The only way to see the summary is if you hover over the word `this` in the source file, which is hardly useful since the summary is right there already anyway. Likewise for the parameters.

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/78726959-311dbe00-78e8-11ea-8eac-5e304dcf1148.png)

Shows for me as part of sighelp.

**Comment by CyrusNajmabadi** [comment]
We coudl consider some sort of approach where quick-info could show something here if you're on the `[` or `]` tokens.

**Comment by allisonchou** [comment]
The consensus from today's design meeting (4/13) was to have quick info show up if on the ```[``` or ```]``` tokens.

**Comment by CyrusNajmabadi** [comment]
Closing out as not being important enough.
