### ISSUE TITLE
Feature requests - Constraints heterogeneous collection

### ISSUE THREAD

**Issue by jaider** [dotnet/roslyn#43174]
In short thought this allows to return a list of heterogeneous collection with some type constrains, for example only return a list of string and/or int.
```
        // Before
        IEnumerable<object> GetValues()
        {
            yield return "Age:";
            yield return 75;
        }

        // After
        IEnumerable<string|int> GetValues()
        {
            yield return "Age:";
            yield return 75;
            yield return true; // compile time error
        }
```

**Comment by CyrusNajmabadi** [comment]
Language requests should be made to dotnet/csharplang.  I'm going to close this out.  Note that there's an existing requestion for 'union types' here: https://github.com/dotnet/csharplang/issues/399
