### ISSUE TITLE
[Regression] Full solution analysis does not run when you first open a project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#43179]
**Version Used**: 
Version 16.6.0 Preview 3.0 [30005.27.master]

**Steps to Reproduce**:

1. 

![image](https://user-images.githubusercontent.com/1103906/78744256-79021b00-79a4-11ea-8cd7-e22b0f9d9b72.png)

2. `git clone http://github.com/davkean/project-system` (note that this is my fork)
3. `cd project-system`
4. `git checkout 96d96835ad173d53b9efb30f48e48c53167f316f`
5. `ProjectSystem.sln`
---Wait until all Roslyn work has finished---

**Expected Behavior**:
100s of warnings:

![image](https://user-images.githubusercontent.com/1103906/78744236-6a1b6880-79a4-11ea-8aff-691a3c75fed0.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/1103906/78744104-0a24c200-79a4-11ea-9c22-2942517fffad.png)

**Comment by sharwell** [comment]
I've been observing something similar to this at least for the 16.6 previews, and maybe since 16.5. I believe it may have appeared when the **Background analysis scope** option was added.

**Comment by mavasani** [comment]
Unable to repro this for couple of solutions on 16.9 latest dogfood builds.
