### ISSUE TITLE
C# rename refactoring should suspend updating of Error List

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43187]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/977711/c-rename-refactoring-should-suspend-updating-of-er-1.html)._

---
If you have the Error List open, enabled to display errors, and you rename an identifier (let's say a field) of a type defined in some other file, and used all over the place, the Error List can throw a hissy-fit and display an unbound set of errors for identifier not found, while you are in the middle of the renaming operation.

I could say "Well DUH, I'm renaming it right now!". :-)

Instead I suggest you consider how this should behave during a rename operation.

Since Roslyn don't have (or at least don't use) a system to notify with any granularity greater than "Something in the universe has changed! You must reparse all of it", perhaps the easiest and best solution would be to simply suspend any and all analyzers running during rename operations. I mean, it will have to restart from scratch anyway, once the rename is committed.
I believe that would be the solution that's easiest to implement, understand, and to maintain.

---
#### Visual Studio Feedback System on 4/7/2020, 01:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tamlin-mike** [comment]
@jmarolf (redirecting reply from question @ DC): Rename refactoring by means of Ctrl-RR.

**Comment by jmarolf** [comment]
Thanks @tamlin-mike I assumed you were using the rename command but wanted to check

> Since Roslyn don't have (or at least don't use) a system to notify with any granularity greater than "Something in the universe has changed! You must reparse all of it"

Yeah we do have a way to do this. We should selectively suspend analysis during rename imho. We need to run some semantic analysis to give you live feedback of rename conflicts. But even if we do that we do not need to report diagnostics to the error list

**Comment by tamlin-mike** [comment]
@jmarolf Right you are, I didn't think of conflict checking. I blame that on the shock I got from the Error View. I normally don't have it open, so the amount of red entries might have triggered a partial cognitive shutdown. :-)

Good to know there are already facilities in place to handle this.

**Comment by tamlin-mike** [comment]
Not sure if it's already handled, but in case not; another instance where analyzer suspension could be considered would be while Find+Replace in files is running.

**Comment by CyrusNajmabadi** [comment]
Closing uot due to lack of feedback on this.
