### ISSUE TITLE
Go to definition (F12) doesn't work when a local variable is selected in the editor (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43183]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/957960/go-to-definition-f12-doesnt-work-when-a-local-vari.html)._

---
hi,

F12 (go to definition) doesn't work you have a C# local variable selected in the Visual Studio editor
("Cannot navigate to the symbol under the caret")
(which is technically correct, because the caret is not on the variable, but it's not very helpful)

Especially since F12 does work when you have a class, or a namespace selected in the editor.

Many thanks,
Lambert

---
#### Visual Studio Feedback System on 3/22/2020, 05:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 3/23/2020, 01:11 PM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. If possible please provide a sample code/project where this issue is occurring. Snapshots of the behavior you are seeing will also be helpful.</p>

#### lambertwm on 3/23/2020, 03:03 PM: 

<p>Unfortunately, I am unable to reproduce the problem...</p>

#### lambertwm on 3/25/2020, 09:55 AM: 

I mananged to reproduce the problem by doubleclicking (thus selecting the name of a ) a *class member* in the Visual Studio editor and then press F12 - see screenshot
#### lambertwm on 3/25/2020, 09:57 AM: 

How do I attach a screenshot :(<br>

---
#### Visual Studio Feedback System solved on 3/23/2020, 03:37 PM, 0 votes: 

<p>We are unable to investigate this issue further without the additional information requested.</p>

#### lambertwm on 4/7/2020, 07:43 AM: 

<p>hi, thanks for looking into this. I have had the problem numerous times since reporting the issue. I was wondering: what's the procedure for this? do I have to prove that the problem exists by isolating a repro-case, which allows you to reproduce the problem on your machine? Or maybe is there a way for you to look at the code that gives the error-message and figure out if the error-message can be given incorrectly when the user happens to have selected the entire name of the local variable or the class member when pressing F12? <br><br>Thanks, Lambert</p>

#### lambertwm on 4/8/2020, 02:14 AM: 

(private comment, text removed)
#### lambertwm on 4/8/2020, 02:15 AM: 

<p>PS: why is my last post "private" all of a sudden?</p>

**Comment by sharwell** [comment]
Minimal repro case:

```csharp
class C
{
  int X;

  void M()
  {
    _ = X%2; // Press F12 with caret between X and %
  }
}
```
