### ISSUE TITLE
Should "Add argument name (including trailing arguments)" only be shown when it differs from "Add argument name"

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#43182]
**Version Used**: VS 16.5.3

```cs
class C
{
    void M()
    {
        CalledMethod(
            [||]"Test",
            body: "Test",
            attachmentFilename: "Test");
    }

    void CalledMethod(string subject, string body, string attachmentFilename) { }
}
```

**Expected Behavior**:

"Add argument name (including trailing arguments)" not offered

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/8040367/78802870-5237ea80-798c-11ea-8ece-c1a935c620e9.png)

**Comment by CyrusNajmabadi** [comment]
> Should "Add argument name (including trailing arguments)" only be shown when it differs from "Add argument name"
