### ISSUE TITLE
Code formatting changed when 16.6 Preview 2.1 was installed.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43185]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/977419/code-formatting-changed-when-preview-21-was-instal.html)._

---
I primarily code in C#, so all of the following applies, without limitation, to C#.

I have been following all of the preview releases of VS 2019. When I installed the latest version, the code editor behavior changed in a way that I don't like, and all of the option settings that seem to apply make no difference in the behavior. For example, I am used to typing an "if" statement as follows:

```
if (condition)
{
    Action();
}
```

I enter the "{" immediately after the ")". It is replaced by a space and "{}" with the cursor placed between the braces. I then press "Enter" and the " {}" is replaced with a "newline" and three additional lines:

```
{

}
```

with the cursor on the blank line, indented one tab from the braces. The cursor is between the braces. If I press "Enter",  a "newline" is inserted between the braces

The new behavior is as follows:

When I enter "{", it is replaced by "{}" with no leading space. The cursor is between the braces. When I press "Enter", a "newline" is 
 inserted between the braces. The "}" is aligned below the "if" and the cursor is before the "}".

The same behavior occurs for "{" in pretty much every context. All of these behaviors are deviations from what I have been used to. The "New line options for braces"  are all checked in the "Options" dialog.

I have not knowingly created or edited a ".editorconfig" file, but I noticed in the erlease notes that there is a new feature that allows one to have different configuration settings for each project (or perhaps it was for each solution). The problem could be that, when no ".editorconfig" file is found, the per project configuration settings are being set to an arbitrary set of options and ignore the settings selected in the "Options" dialog.

How do I fix this?

---
#### Ronald Martin on 4/3/2020, 08:19 PM: 

I think I have resolved the problem. I&#39;m not sure if it&#39;s a bug or a feature.<br><br>When I opened my solution,, the Solution Explorer was in file view, rather than solution view. I think that this is intended. It comes down to the landing screen preserving this state, even if you switch to solution view before exiting.<br><br>What I&#39;d really like to know is why the features mentioned in my complaint and many others that I haven&#39;t mentioned, are dependent on this setting. Almost all of Intellisense was affected.<br><br>I&#39;m good for now. I hope this helps someone else.
#### Visual Studio Feedback System on 4/7/2020, 00:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  I don't repro this at all.  And this is very likely to be something we would have heard about from others (including our team) if we broke this.
