### ISSUE TITLE
Pull members up refactor removes async modifier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43198]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/978277/pull-members-up-refactor-removes-async-modifier.html)._

---
Minimal rep case, VS v16.5.2:

```
using System;
using System.Threading.Tasks;

namespace PullUp
{
    internal interface IPullUp { }

internal class PullUp : IPullUp
    {
        internal async Task PullUpAsync()
        {
            await Task.Delay(1000);
        }
    }
}
```
1. Invoke the "Pull members up to base type" refactor on `PullUpAsync`.
2. Accept the selection of member and destination.
3. Accept the notice that `PullUpAsync` will be made public.
4. Refactor creates expected new method on `IPullUp`, but changes implementation in `PullUp` from `internal async` to `public`, making the `await` usage an error.

Is this behaviour intentional?

---
#### Visual Studio Feedback System on 4/7/2020, 00:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 4/8/2020, 10:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
@Cosifne Assigned to you since you have more context on this

**Comment by Cosifne** [comment]
@genlu Sure I can take a look at this issue

**Comment by Cosifne** [comment]
Fix in the above PR
