### ISSUE TITLE
Static field assigned by out parameter in static initializer is treated as uninitialized, results in CS8618

### ISSUE THREAD

**Issue by nagya** [dotnet/roslyn#43215]
**Version Used**: 

.NET Core 3.1.201, C# 8.0

**Steps to Reproduce**:

```csharp
#nullable enable

using System;

namespace ClassLibrary5
{
    public static class Class1<T>
    {
        public static readonly T t;
        public static readonly bool f = Get(out t);

        private static bool Get(out T t)
        {
            t = Activator.CreateInstance<T>();
            return true;
        }
    }
}
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

Class1.cs(9, 34): [CS8618] Non-nullable field 't' is uninitialized. Consider declaring the field as nullable.

**Comment by RikkiGibson** [comment]
This might be fixed by #46441 since we analyze the initializers and pass the resulting state as an initial state when analyzing the constructor. I will try and add a test.
