### ISSUE TITLE
Add source code navigation features for .NET #regions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43227]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/982750/add-source-code-navigation-features-for-net-region.html)._

---
<p>Some code have large &quot;regions&quot; (or embedded regions) and it very hard to know in what region the code you are viewing is.</p> <p>Adding a &quot;region&quot; navigation menu in the little top bar of the source code editor could be very usefull (like navigation for project/class/members)</p><p>I will be easy to know where you are and also easy to navigate quickly to another region of the code.</p>

---
#### Visual Studio Feedback System on 4/9/2020, 02:31 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Potentially related to #35708

**Comment by sharwell** [comment]
🔗 This issue is a subset of experience requested in #36812.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
