### ISSUE TITLE
Conditional return

### ISSUE THREAD

**Issue by deaddog** [dotnet/roslyn#4323]
With the introduction of the `?.`and `?[]` operators, many expressions can be simplified for better readability. Following this train of thought I would love to see the introduction of a conditional return statement.
Say I have an instance of a class `Foo foo = ...` and want to return the result of executing its `bar` method. But first I need to check that the method does not return null:
```csharp
var temp = foo.bar();
if (temp != null)
    return temp;
```
Instead I suggest a conditional return operator that mimics this behaviour:
```csharp
return? foo.bar();
```
Which then returns the expresssion if it is not `null`. This works great with the existing coditional operators, allowing to test if `foo` is `null`:
```csharp
return? foo?.bar();
```

The idea is based on the following which, though I like the options it provides, seems less readable than the above. The idea is simply to allow for checking some value in the object returned by `bar` before returning:
```csharp
return? foo?.bar:.initialized
```
Which translates to the following:
```csharp
var temp = foo.bar();
if (temp.initialized)
    return temp;
```

**Comment by jveselka** [comment]
I have seweral problems with both syntax and use-case.
a) Question mark in other C# null-checking features appear after the thing that is null checked. That hold for both elvis operator and null coalescence operator. Having it after return is confusing, especially when followed by long chain of method calls.
b) Many use-cases are already covered by null coalescence: ```return temp ?? default;```, other use cases are few and probably not worth specific feature
c) This looks like a path to allowing conditional assignment with ```?=``` next and I think that is not the path C# should take.

**Comment by deaddog** [comment]
a) I can definitely see how this is not completely aligned with the syntax of existing operators. I don't know if I find it confusing to have it directly after return (but then again, it was my own suggestion so why would I?) because I read `return? foo?.bar();` as *return the following if it is not null*.
b) I disagree that these are the same use-cases. One is conditional on *what* it returns and the other on *if* it returns.
c) This is kind of a funny thing, because I completely agree with you. This does look like a path to conditional assignment and I agree that it is not the path for C#. I make the distinction between the two because conditional return short-circuits a method and provides a simple way to ensure certain conditions are met whereas conditional assignment makes it harder to known the state of the method.

**Comment by gafter** [comment]
This seems really unlikely as something we'd ever do.

**Comment by MohammadHamdyGhanem** [comment]
@deaddog @Pilchie @zippec @gafter @HaloFour
I was about to ask for the same thing, while I was writing this code:
```
var t = CheckToolStrip(frm.ContextMenuStrip);
if (t != null)
   return t;

t = CheckToolStrip(frm.MainMenuStrip);
if (t != null)
    return t;
```

Which will become:
```
return? CheckToolStrip(frm.ContextMenuStrip);
return? CheckToolStrip(frm.MainMenuStrip);
```

I even want to make it:
`return? CheckToolStrip(frm.ContextMenuStrip) : CheckToolStrip(frm.MainMenuStrip);`
Where we can add more `:`s and return values. The first non-null value will be returned. 
Hope you reconseder this proposal. It is very useful.
