### ISSUE TITLE
A bug in VB.NET syntax checker, which offers a new feature for ExpandoObject!

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#43247]
I was thinking of some ideas to use the `(of T)` syntax to do some new stuff like in https://github.com/dotnet/vblang/issues/528 , when I tried to come up with a syntax to set the type of new keys added to ExpandoObject Like this:
```VB.NET
Dim x as Object = New ExpandoObject()
X.ID(Of Integer) = 3
X.Name(Of string) = "Adam"
```

Just to be surprised that VB.NET accepts this syntax! I ran the code to see how VB understands it, but got a runtime error at the second line:
> Public member 'ID' on type 'ExpandoObject' not found.'

Which is also not the right message to get. I tried this:
```VB.NET
Dim x as Object = New ExpandoObject()
X.ID= 1
X.ID(Of Integer) = 3
X.Name(Of string) = "Adam"
```

And got the same error message at the 3rd line.

So, we have a design time and runtime misbehavior, but I find it excellent, as half of the work I need to do is already done!
Instead of fixing these behaviors, I want to modify the ExpandoObject to save the type offered by the `(Of T)` syntax. This can done by using a Tuple as a value: `(value as object, type as Type)`, and when a new value written to an existing key of that type, expando asserts that the value can be converted to this type, or give a syntax error at design time or an exception at runtime.
I think this is simple, and will be useful, especially if combined with dynamic intelligence to offer the key names from the method content.

**Comment by VBAndCs** [comment]
Note that C# doesn't allow it:
```C#
            dynamic x = new System.Dynamic.ExpandoObject();
            x.ID<int> = 1;
```

It gave the syntax error:
> The property 'ID' cannot be used with type arguments.

**Comment by Youssef1313** [comment]
@VBAndCs  This is completely unrelated to ExpandoObject.

Your suggestion seems to be that the following should be an error:

```vb
Sub S(x As Object)
    x.Id(Of Integer) = 0
End Sub
```

This probably something the compiler team cannot do for backward compatibility. I'm also unsure whether this have some valid usage in VB or not.

**Comment by CyrusNajmabadi** [comment]
Closing out as i don't see anything in the language that would allow this.  If you would like to make a language proposal for this, those can be made at dotnet/vblang.
