### ISSUE TITLE
Code Cleanup formats code that is not in the "Included Fixers" list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43258]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/980503/code-cleanup-formats-code-that-is-not-in-the-inclu.html)._

---
Code Cleanup Profile 1 is configured for "Sort usings" and "Remove unnecessary usings".

When invoked from the "Run Code Cleanup" icon at the bottom of an editor panel, it performs the actions requested, but also reformats code that is not in the using section.

Specifically, I had a block of code that was aligned on assignment symbol (=) on successive lines, all of those statements were reformatted, which obviated my preferred alignments.

I would prefer that the code cleanup actions were limited to those specifically included in the "Included Fixers" list.

Thank you
Craig Pelkie

---
#### Visual Studio Feedback System on 4/7/2020, 07:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The specific question to consider here is whether we should include a separate line item for **Format Document**, which is enabled by default but can be disabled if the user wishes.

**Comment by sharwell** [comment]
During design review, we agreed that:

1. **Format Document** should be listed as an explicit item for Code Cleanup
2. **Format Document** should be enabled in the default profiles, but users should be able to manually disable/exclude it
