### ISSUE TITLE
CS0162 (unreachable code) incorrect code fix suggested

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43257]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/979565/c-cs0162-very-dangerous-destructive-code-fix-sugge.html)._

---
```
public void DEADLY_DANGEROUS_CS0162(List<int> lst)
{
  foreach (var l in lst)
  {
    if (something())
    {
      return DoSomethingElse();
      break; // <-- ONLY the break shall be removed. Instead, the whole inner block gets removed!
    }
  }
}
```

---
#### Visual Studio Feedback System on 4/7/2020, 01:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I was not able to reproduce this issue in 16.6 Preview 2. Only the `break;` statement was removed.

**Comment by CyrusNajmabadi** [comment]
I wasn't able to repro this either.  Also, we don't get CS0162, we get CS0161:

Severity	Code	Description	Project	File	Line

```
Error	CS0161	'C.DEADLY_DANGEROUS_CS0162(List<int>)': not all code paths return a value	ConsoleApp1	C:\Users\cyrus\source\repos\ConsoleApp1\ConsoleApp1\va.cs	11
```

Need more info on this.

**Comment by tamlin-mike** [comment]
Reproduced in VS 16.5.1 + Analyzers 2.9.8.

Good to know it's gone from HEAD. Though, since I have a strong suspicion this was a regression, perhaps a test should be added to make sure it never again creeps in.
