### ISSUE TITLE
Generate constructor not taking into account NRT for type parameters

### ISSUE THREAD

**Issue by faso** [dotnet/roslyn#43273]
**Version Used**: 
Latest

**Steps to Reproduce**:

1. Write a class with a field of type `T?`
2. Generate constructor

**Expected Behavior**:
Constructor should have a parameter of type T?

**Actual Behavior**:
The parameter is of type T

Related to 
https://github.com/dotnet/roslyn/issues/41428
and
https://github.com/dotnet/roslyn/pull/43083

I would like to work on this myself

**Comment by NextTurn** [comment]
Fixed by #44230

**Comment by CyrusNajmabadi** [comment]
Generate constructor seems to be doing the right thing: 

![image](https://user-images.githubusercontent.com/4564579/152654302-8ab4a7dc-8275-47a7-be50-97390b68d6d5.png)
