### ISSUE TITLE
Please update the NuGet packages

### ISSUE THREAD

**Issue by davku** [dotnet/roslyn#4327]
Hello
Since updating the NuGet packages to v1.0.0 I encountered a problem with the constructor of `VisualBasicParseOptions`. Exceptions are thrown if the `kind` parameter does not equal `SourceCodeKind.Regular`. Unfortunately this renders a lot of my code useless. The same code worked in previous versions.

Judging by the source code, it seems that this problem has already been solved, though.

So I'm asking if it would be possible to update the NuGet packages in the near future or when the next update might be scheduled for.

**Comment by ManishJayaswal** [comment]
Yes we will enable this in one of the updates. It was not ready at VS2015 RTM release hence we blocked it.

**Comment by ManishJayaswal** [comment]
This is fixed in latest packages in the myget feed.
