### ISSUE TITLE
Hide Tags from collapsed method signature

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#43285]
This is a VB.NET sample but consider C# also:
```VB.NET
<InlineData("/Test-View.cshtml")>
<InlineData("~/Test-View.CSHTML")>
<InlineData("/Home/Test-View.CSHTML")>
<InlineData("~/Home/Test-View.cshtml")>
<InlineData("~/SHARED/TEST-VIEW.CSHTML")>
Public Sub Foo(pageName As String)

End Sub
```

After collapsing this method, this is the text I see:
`<InlineData("/Test-View.cshtml")><InlineData("~/Test-View.CSHTML")><InlineData("/Home/Test-View.CSHTML")><InlineData("~/Home/Test-View.cshtml")><InlineData("~/SHARED/TEST-VIEW.CSHTML")>Public Sub Foo(pageName As String) ...`

Which is too long unuseful title. I expect to see the method signature only without and attributes.
After collapsing this method, this is the text I see:
`Public Sub Foo(pageName As String) ...`

**Comment by CyrusNajmabadi** [comment]
@sharwell  What do you think? You've been working in this area recently for MAS/Decomp.  Seems reasonable to hide this as it's likely not to be the most relevant info.

**Comment by sharwell** [comment]
Design review conclusion:

* We should update Visual Basic to behave more like C# in the way it collapses to definitions (i.e. only collapse the body of a member, which preserves the visual form of the signature along with its classifications).
* We should update both outliners to allow collapsing attribute blocks. Currently the C# outliner offers this, but only for Metadata as Source views.

**Comment by CyrusNajmabadi** [comment]
> We should update both outliners to allow collapsing attribute blocks. Currently the C# outliner offers this, but only for Metadata as Source views.

**Comment by VBAndCs** [comment]
Here another thing: The following Signature:
```
    <System.Runtime.CompilerServices.Extension()>
    Public Iterator Function GetChildren(ByVal parent As UIElement, ByVal Optional recurse As Boolean = True) As IEnumerable(Of UIElement)

End Function
```

is collapsed to:
`<System.Runtime.CompilerServices.Extension()>Public Iterator Function GetChildren(ByVal parent As UIElement, ByVal Optional recurse As Boolean = True) As IEnumerable(Of UIElement) ...`

I think there are some things to do to short this label:
1.Unqualify `System.Runtime.CompilerServices.Extension()`
2. Erase `ByVal`
3. Erase optional and optional param types and keep the defaults as indication of this is an optional and of the type.

So, the label becomes:
`<Extension>Public Iterator Function GetChildren(parent As UIElement, recurse = True) As IEnumerable(Of UIElement) ...`

And I may take this further, and ask to get red of param names. It is just a  label, and names has no meanings in this moment:

`<Extension>Public Iterator Function GetChildren(UIElement, [Boolean]) As IEnumerable(Of UIElement) ...`

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
