### ISSUE TITLE
Offer 'Convert to conditional expression' between throw and return statements

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#43291]
**Version Used**: 16.5.3

'Convert to switch expression' is offered here but not 'Convert conditional expression':

```cs
class C
{
    int M()
    {
        var index = 42;

        [||]if (index == -1)
        {
            throw new InvalidOperationException("...");
        }

        return index;
    }
}
```

If you change the `throw` statement to a `return` statement, 'Convert conditional expression' shows up as expected.

**Comment by jnm2** [comment]
Haha, you can get around this by changing the `throw` token to a `return` token and invoking the helper, then replacing `(int)` cast with a `throw` token.

**Comment by CyrusNajmabadi** [comment]
i can take this :)
