### ISSUE TITLE
Code Fix provider not being loaded when just added as an Analyzer in the project file

### ISSUE THREAD

**Issue by jakeswenson** [dotnet/roslyn#4330]
Visual studio doesn't seem to be loading my code fix provider in my analyzer assembly when added to the csproj file. However once in install it as a VSIX its loading it twice. (Also possibly another issue given that i have specified an equivalence key.)

FYI @KirillOsenkov @DustinCampbell (conversation start in twitter)

**Comment by jakeswenson** [comment]
Seems like the reason i'm seeing it twice is because the GetHashCode for suggested actions is combining the provider hash code with the equivalence  key hashcode.
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Suggestions/SuggestedAction.cs,304

**Comment by Pilchie** [comment]
Also tagging @mavasani.

**Comment by mavasani** [comment]
Duplicate fix issue is being tracked by https://github.com/dotnet/roslyn/issues/4030

However, this seems weird: _"Visual studio doesn't seem to be loading my code fix provider in my analyzer assembly when added to the csproj file"_ when there is no VSIX installation. A single fix should show up from the fixer in the analyzer reference in csproj file.

**Comment by jakeswenson** [comment]
yes, there sounds like two issues.

1. the equivalence key isn't working (#4030?)
2. even though the analyzer is loaded, the code fix provider in the same assembly is not...

**Comment by jakeswenson** [comment]
@mavasani any ideas as to why my code fix provider would not be loaded even though the analyzer reference is in the csproj? (I didn't use nuget to install it, i manually added it to the csproj.)

It's weird that it loads two code fix providers when the VSIX is installed. (one from the analyzer in the csproj, and the other from the installed VSIX..)

**Comment by CyrusNajmabadi** [comment]
@jakeswenson Are you still having this problem?

**Comment by jakeswenson** [comment]
Hey @CyrusNajmabadi, been a while!
I have no idea if this is still an issue. I can close this issue if you'd like?

**Comment by noamyogev84** [comment]
Sorry to hijack this thread folks 🙏
I can't make my code fix provider to work when I'm creating a simple analyzer and adding it to another project by project reference.
The analyzer works, I see the errors and the diagnostics, but it no way i can make the code fix to work and become visible in the context menu.

Only when I follow the guide to create my analyzer with the template and use the vsix install it's working.
Can someone assist?

**Comment by CyrusNajmabadi** [comment]
Closing out.
