### ISSUE TITLE
Task list not being refreshed with changes (C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43309]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/984841/task-list-not-being-refreshed-with-changes-c.html)._

---
Hi there - I'm having the same problem as in the closed/fixed issue linked below, but for C# instead of C++. (I would not be surprised if this applies to every language.)

Basically, Task List items are not being refreshed in the UI when they change. That includes the line-number position, content, even changing the token.

Interestingly if the line-number changes, double-clicking on the item in the Task List takes you to its _former_ position, or occasionally throws an exception. See attached video for repro (not the exception unfortunately).

Closing the project and re-opening will force the Task List to update.
Deleting the comment and re-inserting it quickly (either by undo or paste) also forces the task list to update.
Deleting the comment and re-typing it slowly, will sometimes only capture the first part of the comment. I inadvertently showed that phenomenon early in the attached video. My TODO item is created, including the hyphen I typed, but not the subsequent text.

https://developercommunity.visualstudio.com/content/problem/596907/todo-position-line-is-not-updated-in-task-list-pan.html

---
#### Michael Loux on 4/9/2020, 09:27 AM: 

<p>Same issue here, also coming from the previous (now-C++-specific) bug.  </p><p>I would like to add to the post, above, that when I delete/insert a TODO, only the task items for the same file are updated.  If you have changes to several files, you will need to do the same workaround for each file in order to get them to refresh.  </p>

#### Hugo Trudel on 4/9/2020, 09:57 AM: 

<p>I hope they will also fix it when the solution contains VB.NET projects since we use both...</p>

#### Visual Studio Feedback System on 4/10/2020, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by gdignard** [comment]
From experimentation, it appears there are common cases where the file is not marked dirty by whatever process populates the task list.

If you modify an existing task comment, nothing happens. This includes modifying the leading token ("TODO").

If you edit an existing task comment, then add a new general (non-Task) comment to the page, nothing happens.

If you edit an existing task comment, nothing happens but if you then add a new task comment, all tasks on the page are refreshed.

Hopefully these additional observations can help track this down!

**Comment by LiterallyTheGreatestDeveloper** [comment]
Tickle tickle.

**Comment by fomrat** [comment]
Irksome. And still present.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44873

**Comment by LiterallyTheGreatestDeveloper** [comment]
Sweet!
