### ISSUE TITLE
[Perf] RemoveUnnecessaryCast analyzer (IDE0004)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#43304]
**Version Used**: Latest

**Steps to Reproduce**:

1. Revert https://github.com/dotnet/roslyn/pull/43303 or explicitly enable [IDE0004](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/IDEDiagnosticIds.cs,14) for Roslyn.sln
 
2. build `src\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj`

**Actual Behavior**:
Build time almost doubles in presence of IDE0004 analyzer. Perf traces shows that almost all the time is coming speculative semantic model queries for conversions:

```

Name | Exc % | Exc | Inc %
-- | -- | -- | --
microsoft.codeanalysis.codestyle!Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`7[System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,Microsoft.CodeAnalysis.CSharp.Conversion].ReplacementChangesSemantics() | 0.0 | 1 | 89.6
microsoft.codeanalysis.csharp!MemberSemanticModel.GetBoundNodes | 0.0 | 5 | 85.1
microsoft.codeanalysis.csharp!MemberSemanticModel.GetBoundNodes | 0.1 | 15 | 85.1
microsoft.codeanalysis.csharp!MemberSemanticModel.GetLowerBoundNode | 0.0 | 1 | 85.0
microsoft.codeanalysis.csharp!MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary | 1.0 | 142 | 85.0
microsoft.codeanalysis.codestyle!Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`7[System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,Microsoft.CodeAnalysis.CSharp.Conversion].ReplacementChangesSemantics(class Microsoft.CodeAnalysis.SyntaxNode,class Microsoft.CodeAnalysis.SyntaxNode,class Microsoft.CodeAnalysis.SyntaxNode,bool) | 0.4 | 58 | 84.0
microsoft.codeanalysis.codestyle!Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`7[System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,Microsoft.CodeAnalysis.CSharp.Conversion].ReplacementChangesSemanticsForNode(class Microsoft.CodeAnalysis.SyntaxNode,class Microsoft.CodeAnalysis.SyntaxNode,class Microsoft.CodeAnalysis.SyntaxNode,class Microsoft.CodeAnalysis.SyntaxNode) | 0.0 | 4 | 83.5
microsoft.codeanalysis.csharp!MemberSemanticModel.GetTypeInfoWorker | 0.1 | 9 | 74.1
microsoft.codeanalysis.csharp.codestyle!SpeculationAnalyzer.ConversionsAreCompatible | 0.0 | 1 | 66.4
microsoft.codeanalysis.codestyle!Microsoft.CodeAnalysis.Shared.Utilities.AbstractSpeculationAnalyzer`7[System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon,Microsoft.CodeAnalysis.CSharp.Conversion].ImplicitConversionsAreCompatible(!0,!0) | 0.0 | 0 | 66.4
microsoft.codeanalysis.csharp!CSharpExtensions.GetConversion | 0.0 | 0 | 66.4
microsoft.codeanalysis.csharp!CSharpSemanticModel.GetConversion | 0.0 | 0 | 66.4

```

**Comment by mavasani** [comment]
Tag @sharwell

**Comment by sharwell** [comment]
This is one of the well-known slow analyzers. Assuming the analysis is currently producing accurate results, there are two areas to investigate:

* Performance for true positives: We can fast-path cases where we know it is safe to remove a cast without going through the full speculative semantic model checks
* Performance for true negatives: We can fast-path cases where we know it is _not_ safe to remove a cast, e.g. #40792

Ideally we can find scenarios that are easy to verify correctness and occur frequently in practice. This minimizes the number of special cases required to reach an acceptable level of performance.

On a side note, the change that made this analyzer move from "a bit slow" to "very slow" is nullable reference types. This feature greatly expanded the amount of work required to incrementally update a speculative semantic model.

**Comment by mavasani** [comment]
Tag @CyrusNajmabadi who is working on a high level cleanup in this space.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Is this still an issue with your re-write?

**Comment by CyrusNajmabadi** [comment]
Going to close out as none of the above metrics apply to the current code.  We may still have an issue, but we need to rerun our perf benchmarks to find out and have up to date info.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I think we need to keep the issue open and re-benchmark.

If there is no perf issues anymore, we should update `EnforceOnBuildValues` and close this issue:

https://github.com/dotnet/roslyn/blob/19bbd4725f7fa9c825d030498235580fcfc4639b/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs#L86

Otherwise, we still need it open to see if it can be improved.
