### ISSUE TITLE
Remove type-forwarders added to avoid breaking TypeScript

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#43313]
See `src\Features\Core\Portable\Diagnostics\Analyzers\DocumentDiagnosticAnalyzer.cs`

**Comment by tmat** [comment]
Switch TypeScript to `VSTypeScriptDiagnosticAnalyzerLanguageService`

**Comment by CyrusNajmabadi** [comment]
Tmat, can this be removed now?
