### ISSUE TITLE
Build Constants

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43315]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/935773/costanti-di-compilazione.html)._

---
[regression] [worked-in:15.9.20]
Conditional compilation does not work. The problem occurs when the string length of the build constants <DefineConstants> exceeds about 200 characters.
For example, if I assign the following string to custom build constants

PROJECT-"ASLASLASLASLASLASL",PROJECT2-"ASLASLASLASLASL",PROJECT3-"ASLASLASLASLASL",PROJECT4-"ASLASLASLAS LASLASLASL,PROJECT5-"ASLASLASLASLASLASL",PROJECT6""ASLASLASLASLASLASL",PROJECT7-"ASLASLASLASLASLASLASL"

in the intellisense the code is disabled
#If PROJECT - "ASLASLASLASLASLASLASL" Then
        Dim a - "test"
If #End

while if I use this string with fewer characters, but with the same number of variables, the code is enabled
PROJECT-"ASL",PROJECT2-"ASL",PROJECT3-"ASL",PROJECT4-"ASL",PROJECT5-"ASL",PROJECT6-"ASL""ASL"
#If PROJECT - "ASL" Then
        Dim a - "test"
If #End

---
#### Visual Studio Feedback System on 3/2/2020, 06:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jared Parsons [MSFT] on 3/27/2020, 09:24 AM: 

<p>Thanks for taking the time to report the issue. Unfortunately there is not enough information here for us to act on. Could you please provide a complete code sample here? Possibly create a small project, zip it up and attach it to the bug?</p>
<p>I’m unable to reproduce this locally. There is no real limit on the length of conditional compilation constants in the compiler nor is there a limit inside the project file for them.</p>

#### Visual Studio Feedback System on 4/7/2020, 07:18 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Massimo Del Sorbo on 4/7/2020, 11:47 PM: 

(private comment, text removed)
#### Massimo Del Sorbo on 4/9/2020, 00:20 AM: 

(private comment, text removed)

---
#### Massimo Del Sorbo solved on 4/7/2020, 11:45 PM, 0 votes: 

<p>I have attached two small web solutions. One with the problem and one without. You can find the problem in Default.aspx.vb. After a build,  one solution works while the other dosen't.</p>

#### Jared Parsons [MSFT] on 4/8/2020, 02:57 PM: 

<p>Thanks for taking the time to provide repro projects. I looked at these locally and I’m not seeing any issues. The TestNotWorks can build successfully on my machine. I had a few problems resolving some types like BundleConfig but was able to work around that. The conditional compilation is also working as I would expect in this configuration.</p>
<p>Is there a specific part of the project that does not compile the way you expect here? I just couldn’t see anything obvious when I was looking through this.</p>

#### Massimo Del Sorbo on 4/9/2020, 00:19 AM: 

(private comment, text removed)

**Comment by mdelsorbo** [comment]
Problem solved with the latest version of Visual Studio
