### ISSUE TITLE
VS2019: Navigating between the intellisense items is slow

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn#43314]
**Version Used**: VS2019 16.5.3 (happened before the update to 16.5.3 too)

**Steps to Reproduce**:

Use the arrow keys to navigate between the intellisense items.

**Expected Behavior**:

Smooth intellisense experience with no delays.

**Actual Behavior**:

Slow intellisense experience due to a delay between the time the arrow key is pressed to the time the item is picked.

Here is a video that tries to demonstrate the issue (hopefully you can tell the difference): 
[2020-04-10 02-40-55.zip](https://github.com/dotnet/roslyn/files/4470748/2020-04-10.02-40-55.zip)

VS2019 on the left.
VS2017 on the top right.
VSCode on the bottom right.

@CyrusNajmabadi @sharwell

**Comment by CyrusNajmabadi** [comment]
@AmadeusW @olegtk This may be due to async-intellisense.  who is the right person on the platform/editor side to take a look?  Thanks!

**Comment by eyalsk** [comment]
To get a sense of the response time maybe it's worth mentioning that I'm spamming the up and down keys but it also happens under normal conditions when I just navigate to an item on the list.

I don't even use the intellisense atm because it's just faster to type everything whole.

**Comment by CyrusNajmabadi** [comment]
Note: @eyalsk is not referring to the time taken for completion to appear.  Rather, that he notices an inconsistent, but noticeable, delay when he presses up/down to move between items in the completion list.  

Is it possible that this itself has now become async (and potentially low pri) and so is now feeling herky/herky instead of instantaneous?

**Comment by olegtk** [comment]
@AmadeusW is the right person to investigate. @eyalsk can you please collect traces per https://github.com/dotnet/roslyn/wiki/Reporting-Visual-Studio-crashes-and-performance-issues

**Comment by eyalsk** [comment]
[General Purpose Trace](https://1drv.ms/u/s!AlC1qiR4jgz3jG1_YzwdBge0JcOW?e=mryYyr).
[GC Only Trace](https://1drv.ms/u/s!AlC1qiR4jgz3jGydAUgQITCyhD4E?e=o7OFJ9).

**Comment by jinujoseph** [comment]
Routed to [editor](https://devdiv.visualstudio.com/DevDiv/_queries/edit/1106096)

**Comment by sharwell** [comment]
@eyalsk this issue is caused when the refresh rate is 100Hz or higher. You can drop the refresh rate as a workaround.

**Comment by eyalsk** [comment]
@sharwell I'll do that for the time being but are you planning to address this in the future? and are you tracking this issue internally?

**Comment by CyrusNajmabadi** [comment]
Yup, the issue is tracked internally.  Jinu linked to it above: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1106096

>  and are you planning to address this in the future?


Unfortunately, no promises about future plans can be made.  My hope though is that this can be fixed for you :)

**Comment by eyalsk** [comment]
@CyrusNajmabadi Thank you. ;)

**Comment by eyalsk** [comment]
@sharwell, @CyrusNajmabadi  Just a note even with lower refresh rate at 60Hz the experience isn't as smooth as in VSCode or VS2017 but it's slightly less noticeable, I'll just keep on typing for the time being.

**Comment by AmadeusW** [comment]
Thank your for reaching out @eyalsk, we are looking into the general slowness and the extra slowness on high refresh displays.

**Comment by OmniAndy** [comment]
This is also happening to me (intellisense dropdown is very sluggish) and I am running at 144hz.

**Comment by btastic** [comment]
I just installed 16.6.2 (coming from a 16.5.x version) and it seems to work fine now. Did you do anything? I couldn't find anything related to this issue in the latest patch notes.

**Comment by Fuewburvpoa** [comment]
@btastic are you sure?
Just installed 16.6.2 and its still lagging on 240hz
Even if i switch to 60hz, it still not as fast/responsive as vs2017

**Comment by CyrusNajmabadi** [comment]
@Fuewburvpoa Please report this issue through visual studio here: 

![image](https://user-images.githubusercontent.com/4564579/84419276-3b508700-abcd-11ea-909b-473f754771ce.png)

This is not a roslyn issue.  Thanks!

**Comment by shtirlitsDva** [comment]
I am on 16.7.6 and have been experiencing slow Intellisense since I bought a 120Hz screen. I can confirm that setting refresh rate to 60Hz speeds up Intellisense.

**Comment by nirhp** [comment]
> 16.7.6 and have been experiencing slow Intellisense since I bought a 120Hz screen

You are right! I have the same issue with 16.7.5 and lowering the refresh rate to 60Hz speeds up Intellisense.

**Comment by CyrusNajmabadi** [comment]
@shtirlitsDva @nirhp please see https://github.com/dotnet/roslyn/issues/43314#issuecomment-642821957

**Comment by Cerlancism** [comment]
https://developercommunity.visualstudio.com/comments/1076792/view.html

It's already report there, and a working workaround is posted there.

**Comment by douglasg14b** [comment]
Moved VS from my 144Hz monitor to my 60Hz monitor and intellisense seems properly snappy now and doesn't lag in the auto-suggested item.

What even is this?

**Comment by star69rem** [comment]
> @eyalsk this issue is caused when the refresh rate is 100Hz or higher. You can drop the refresh rate as a workaround.

Never say anything like that again. Lowering refresh rate is not an option. Why don't you tell them to switch to monochrome color, too? If you ever think about typing something like that again, just close the browser window and start working on an actual fix.
