### ISSUE TITLE
Which team owns resolving symbols to NuGet packages and ensuring things are up to date there?

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#43331]
See this screenshot:

![image](https://user-images.githubusercontent.com/7371750/79189169-b05a4700-7e3e-11ea-9e38-9fab027b3bf9.png)

The "WindowsAzure.*" package set is obsolete. Which team would own ensuring that this tooltip shows the right set of packages?

**Comment by jmarolf** [comment]
This is the right team. @CyrusNajmabadi I assume the index needs to be updated?

**Comment by sujayvsarma** [comment]
I'll let you folks run it and close it when you feel you've done enough then :-)

Stay safe!

**Comment by CyrusNajmabadi** [comment]
@jinujoseph i don't believe the index is being updated any more.  What should we do with the feature?  We either need to get things up to date, or consider removing this if it's going to suggest things that aren't valid anymore.

**Comment by jinujoseph** [comment]
@kendrahavens Can you drive this with Tim and get usage numbers for this feature

**Comment by timheuer** [comment]
@DoRonMotter

**Comment by jmarolf** [comment]
> or consider removing this if it's going to suggest things that aren't valid anymore.

I use this feature _so much_ I really hope we do not do that.

**Comment by sujayvsarma** [comment]
I too vote for the feature to **remain**.

**Reason:** I was one of the requestors for this feature [feature team folks have it on email from me] !!!

**Comment by kendrahavens** [comment]
To share a bit of the internal discussion: yes, only looking at our telemetry on **internal Microsoft users**, there are several thousand on a weekly basis. This puts this at about the 60th most popular codefix out of >400 codefixes.

**Comment by loic-sharma** [comment]
Hello, going forward this index will be updated by the nuget.org team. If you have any problems, please create an issue on our GitHub account: https://github.com/nuget/nugetgallery
