### ISSUE TITLE
SyntaxGenerator.AttributeArgument(...) has no way of specifying which kind of argument it is in C#

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#43354]
**Version Used**: 16.6

See http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Editing/SyntaxGenerator.cs,101b838d04b7ec50 for the lack of this option. I tried using a normal named argument instead, but the Formatter (I think) choked on that later. Perhaps that's the bug instead, but someone who understands the SyntaxGenerator better should decide what's expected here.

**Comment by dpoeschl** [comment]
FYI @CyrusNajmabadi I hit this during AddParameter and generate the wrong type of named arguments in attribute construction because of it. Do you know what the expected solution to this is (is it SyntaxGenerator extension or Formatter/etc. fixing?

**Comment by dpoeschl** [comment]
FYI @ryzngard

**Comment by CyrusNajmabadi** [comment]
Yeah, sounds like a tricky thing here.  We could add an internal overload that allows you to specify which kind you want.  The existing one would just say "nameColon" as the type since that's what it does right now

**Comment by sharwell** [comment]
Here's how I implemented this for a refactoring in dotnet/roslyn-analyzers:

https://github.com/dotnet/roslyn-analyzers/blob/1edc8466e5e4cd0791e58cbac5566991c2f8c506/src/Roslyn.Diagnostics.Analyzers/Core/ImportingConstructorShouldBeObsoleteCodeFixProvider.cs#L220-L232

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
