### ISSUE TITLE
Inconsistent Indexer behavior in derived classes

### ISSUE THREAD

**Issue by giladfrid009** [dotnet/roslyn#43359]
**Version Used**:  .Net Core 3.0 C# 8

**Steps to Reprodude:**

When accessing the indexer of a class with a single value (`foo[1]`) to a class containing both single val indexer and params indexer (`this[int i]`, `this[params int[] idxs]`), the single value indexer is used, yet when a derived class implements the params indexer, and then it accessed by a single value, then the params indexer is accessed, unless the derived class contains **Directly** a **New implementation** of a single value indexer.

There is an inconsistency here and a weird requirement for the direct implementation of both indexers in order to work properly, even if the base class already implements a single value indexer.

**Here is a sample program demonstrating the issue:**
```
using System;
					
public class Program
{
	public static void Main()
	{		
		Console.WriteLine(new BaseClass()[1]);		
		Console.WriteLine(new DerClass1()[1]);	
		Console.WriteLine(new DerClass2()[1]);
	}
}

class BaseClass
{
	public string this[int i] => "base";
}

class DerClass1 : BaseClass
{
	public string this[params int[] idxs] => "der1";
}

class DerClass2 : BaseClass
{
	public new string this[int i] => base[i]; 
	public string this[params int[] idxs] => "der2";
}
```

**Output:**
```
base
der1
base
```

**Expected output:**
```
base
base
base
```

**Comment by 333fred** [comment]
As explained on https://github.com/dotnet/csharplang/issues/3360, this is intended behavior as implemented. Any change would need to be a language change.
