### ISSUE TITLE
Allow merging of rulesets with preexisting .editorconfig files.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/roslyn#43372]
**Version Used**: 
latest version in the latest visual studio 2019 preview.
**Steps to Reproduce**:
There really is not much steps to reproduce, have a ruleset file that sets what analyizer configurations you want, then dump some style settings from vs2019 and save it to the project.
Now when you open the ruleset to edit one, it gives you an option to convert it to a new .editorconfig, but no option to append to it on what parts of it is not already set in the .editorconfig.
In this case I think it is best if the compiler could open that .editorconfig, look for the things in any and all ruleset files to the project, then merge them as a single file deleting the ruleset files.

**Expected Behavior**:
 an option in the compiler that can:
1. look for any *.ruleset file(s).
2. check if an .editorconfig file already exists.
3. if so check and see if that .editorconfig sets all the things in the *.ruleset file(s).
4. if not, merge what is not set in the .editorconfig from that *.ruleset file(s).
5. Delete the *.ruleset file(s).

I wish the compiler would do that and warn saying ``Found ruleset file, replacing it with .editorconfig if it already exists it will be appended to with anything that is in the ruleset that is not in the .editorconfig.`` Would make the move to .editorconfig a whole lot simpler in terms of people going as far as using vs to configure code styles and then dumping their global code styles on their machine to .editorconfig. So I think that the compiler would be best suited for the ``*.ruleset`` -> ``.editorconfig`` move.

**Actual Behavior**:
No absolute way to do this easily or painlessly.

**Comment by jmarolf** [comment]
CC: @mikadumont

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by mavasani** [comment]
Seems like a good feature add.. However, note that this will be useful only for users who are using both rulesets and editorconfig and also have existing rule severity configuration in editorconfig. Otherwise, it should be simple enough for users to just generate a new editorconfig from the new tooling support and then copy paste the contents to the end of their existing editorconfig.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
