### ISSUE TITLE
Roslyn doesn't verify nullability in [DefaultParameterValue] attributes

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#43399]
**Version Used**: 

```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

Compile and run the following program
```cs
using System.Runtime.InteropServices;
class C
{
  static void Main() => new C().M1();
  void M1([Optional][DefaultParameterValue(null)] object s) { s.ToString(); }
}
```

**Expected Behavior**:
Warning for `null` argument of `[DefaultParameterValue(null)]` as its target parameter doesn't allow nulls

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by jcouv** [comment]
Sharplab's QuickInfo shows that the constructor accepts null `DefaultParameterValue(object?)`. Sounds like an API bug.

**Comment by RikkiGibson** [comment]
I think I can solve this at the same time as #40818
