### ISSUE TITLE
Local state still maybe-null after calling local function

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#43403]
``` csharp
#nullable enable

public class C 
{
    public void M() 
    {
        string? s = null;
        ensureInit();
        s.ToString();
        
        void ensureInit()
        {
            if (s is null)
                s = "";
        }
    }
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoAYgDsBXAG2omGrgAI5z7GSTsBmJvJgMJMSAbxJMJfXtgAsTALIAKAJTDikpmPUbJ2fAAYA/EyhMAvEyq0A3OJ0TWUSgjgBJcgEsYK29vtQAOgAVAHsAZRgED3IAcx87ewSdWRZyJxd3LxUkjS17ew8AMyZFUw9TK2plHPyNUwsAIgbfWoBfJPbiVqA==)

@agocke Is this expected?

**Comment by agocke** [comment]
Yup, local functions grab the nullability from outside, but don't change it.
