### ISSUE TITLE
Follow-up verification for unused field ClassificationHelpers.ValueKeyword 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#43407]
`ClassificationHelpers.ValueKeyword` was identified as unused, see https://github.com/dotnet/roslyn/pull/43394#discussion_r409620314. It could likely be a bug that this field is not used. We should either confirm that it is fine to not have this field OR fix this by handling it in code.

**Comment by CyrusNajmabadi** [comment]
This field is gone.
