### ISSUE TITLE
Optimize ObjectWriter.WriteObjectWorker caching

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43401]
ObjectWriter.WriteObjectWorker caches objects that might be reused multiple times. Many of these objects are syntax nodes which only appear once in a tree. We should investigate the effectiveness of caching each type of syntax node, and eliminate caching of nodes that are infrequently reused. Removing these nodes will reduce the size of the resulting cache, and avoid costly LOH allocations.

An initial target might be eliminating the maximum number of cached objects while preserving 90+% of the nodes which get reused.

**Comment by CyrusNajmabadi** [comment]
One thing we coudl look at is if the compiler already sets a bit or something for the green nodes it is already caching.  i.e. both teh C#/VB compilers cache nodes up to a certain depth and potentially with other certain characteristics.  These were already measured to have very good impact on memory use.  So if we can leverage that, we can likely get the same benefits without the cost of trying to remember all nodes.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We shoudl base this on traces we know of and actually assign this a milestone if needs to be done.
