### ISSUE TITLE
Visual Basic iif statement delay evaluation of iif results until necessary

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43417]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/987304/visual-basic-iif-statement-delay-evaluation-of-iif.html)._

---
I have an iif statement where I was trying to check an instance of a class for "Is Nothing" in a statement like

`IIf(x is nothing,"",x.name)`

but the x.name expression is evaluated whether or not x is nothing.

Would it break any syntax to not evaluate the x.name expression until it is known if the value of x is not nothing?

---
#### Visual Studio Feedback System on 4/13/2020, 03:02 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Yes.  This is by design for hte language.  you can use `If(x?.name, "")` to get these semantics.
