### ISSUE TITLE
A paste option for pasting text in the Visual Basic code window as comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43416]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/992411/a-paste-option-for-pasting-text-in-the-visual-basi.html)._

---
A pasted option that would allow the user to copy text from a source and paste it to the code window in Visual Basic, marking each line as a Visual Basic Comment.

For instance a user copies example C# code from a page on the web and wants to paste it into the Visual Basic code window (to keep from having to switch back and forth from the source page to the code window).

example:

```
some lines of code
found on a web site.
This could be several lines
long.
```

When pasted to the Visual Basic code window each line of text would be prepended with an (') to mark it as a comment, such as:

```
'some lines of code
'found on a web site.
'This could be several lines
'long.
```

This would prevent the Code Editor from manipulating and changing the example code when it is pasted.

---
#### Visual Studio Feedback System on 4/15/2020, 11:08 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Design review conclusion: When pasting text inside a comment, subsequent lines of the pasted text should also be commented. The mnemonic requested above would then be typing <kbd>'</kbd>, <kbd>Ctrl</kbd>+<kbd>V</kbd> (start a comment, then paste).

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse experiences.
