### ISSUE TITLE
Keyword and operator Intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43415]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/992450/keyword-and-operator-intellisense.html)._

---
<p>I would find it helpful to get some Intellisense information on various C# keywords and operators. Visual Studio doesn't display any information when hovering over many <a href="https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/" target=_blank>keywords</a> and <a href="https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/" target=_blank>operators</a> in the C# language reference (at least for me, and I haven't found any ways online to make it do so). Brief documentation on each and/or a link to the language reference would help me use these keywords and operators more effectively. Its surprising that classes, methods, variables etc. get a lot of context help displayed, when the structure of the language itself doesn't get any!</p> <p>I know keywords and operators shouldn't be used if they aren't understood by the programmer, but the best place to learn is in the editor, by doing! Think even of a &quot;Hello World&quot; program. There are a few very basic keywords and operators in there that are confusing to a beginner. For an intermediate or experienced programmer, it is still useful to be accurately reminded how the language works, and to be pointed to the language reference for deep details. I imagine Intellisense always popping up for this &quot;basic&quot; stuff might be annoying to experienced programmers---maybe there would be an option to turn it off.</p>

---
#### Visual Studio Feedback System on 4/15/2020, 11:10 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment]
Design meeting decision: We already have "F1 online help" feature (i.e. click F1 with text selected to open help link), which provide similar functionality, w/o showing too much info (which is potentially redundant for most users). We do need to make sure the online help feature provide correct results.
