### ISSUE TITLE
Does Roslyn change the way of compiling an expression that uses Nullable enum?

### ISSUE THREAD

**Issue by thinkriver** [dotnet/roslyn#4342]
The following code prints different results between VS2015 and VS2013:

    namespace ConsoleApplication1
    {
        enum YesNo
        {
            Yes,
            No
        }
    
        class MyType
        {
            public string Name { get; set; }
            public YesNo? YesNo { get; set; }        
        }
    
        class Program
        {
            static void Main(string[] args)
            {
    
                Expression<Func<MyType, bool>> expr = (MyType x) => x.YesNo == YesNo.Yes;
                Console.WriteLine(expr.ToString());
                
                Console.ReadLine();
            }
        }
    
    }

The result from VS2013 (without VS2015 installed) is:

    x => (Convert(x.YesNo) == Convert(Yes))

However the result from VS2015 is:

    x => (Convert(x.YesNo) == Convert(Convert(Yes)))

This difference is currently causing an issue for us. Also a Telerik customer [found the same issue](http://www.telerik.com/forums/net-4-6-enum-in-where-expression)

We are using BLToolkit for data access, the current issue we have is that:

Originally (purely on VS2013), the 

    People.Where(i=>i.YesNo == Yes.Yes)

will be converted into

    x => (Convert(x.YesNo) == Convert(Yes))

and then is converted into
    
    x => x.YesNo == Y

and then eventually is translated into SQL (BLToolKit do the SQL convert)

    select * from Person p
    where p.YesNo = 'Y'

which is a correct result.

However, now, the same query (expression) is translated into

    x => (Convert(x.YesNo) == Convert(Convert(Yes)))

which is converted into 

    x => x.YesNo == Convert(Y)
    then
    x => x.YesNo == 1

then this is translated into SQL (BLToolKit do the SQL convert)

    select * from Person p
    where p.YesNo = '1'

which is unexpected to us.

Is this difference caused by design or is this a bug?

Is this issue caused by .NET Roslyn compiler or .NET 4.6 ?

**Comment by thinkriver** [comment]
We use BLToolkit as our data access. We have found that BLToolkit needs an update to working on the new Roslyn compiler regarding to this issue.

**Comment by MrJul** [comment]
See #3292 for more information

**Comment by gafter** [comment]
Dup of #3292.
