### ISSUE TITLE
Follow up on public api review notes

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#43435]
* ~~`Project.RemoveDocuments`: Everything else in this type uses `IEnumerable<T>`, not `ImmutableArray<T>`. If we could start again from day 1 we might make everything that, but given that everything today uses the former, we should do so here. This applies to the overloads on `Solution` as well.~~
* `Solution.RemoveAdditonalDocuments/RemoveAnalyzerConfigDocuments`: We added these to `Solution`, but not to project, even though that also has the invididual `Remove` methods. We should add them to `Project` as well.

**Comment by jasonmalinowski** [comment]
> Project.RemoveDocuments: Everything else in this type uses IEnumerable<T>, not ImmutableArray<T>. If we could start again from day 1 we might make everything that, but given that everything today uses the former, we should do so here. This applies to the overloads on Solution as well.

So @333fred and @CyrusNajmabadi, it looks like we're already a bit inconsistent here. Solution.AddDocuments (which is already a shipped API) is already taking an ImmutableArray, so when we added RemoveDocuments we were being consistent with _that_. I *can* switch the Remove methods to IEnumerable, but then that just results in a different inconsistency. Is that something we feel is necessary here?

**Comment by jasonmalinowski** [comment]
Also as a reminder any _change_ to a signature here induces a fairly high test cost given we need to take any chance here through VS shiproom.

**Comment by 333fred** [comment]
I think I'd prefer consistency with the symmetric method (AddDocuments) than with the rest of the methods in Solution (which may or may not be related). It would have been good if they were all `ImmutableArray` to start with, but we are where we are.

**Comment by jasonmalinowski** [comment]
@333fred: so in that case, the only item to do then is adding the Project.Remove* methods that match the Solution.Remove* methods? OK if we do that in 16.7 so as to avoid QB process for this?

Tagging @tmat too on the IEnumerable vs. ImmutableArray since he was messing with some of that recently too.

**Comment by 333fred** [comment]
I think that's fine.

**Comment by jasonmalinowski** [comment]
@tmat or @CyrusNajmabadi any concern about fixing just the missing methods, i.e. the second bullet point and not the first?

**Comment by jasonmalinowski** [comment]
Given it's now too late to fix anyways, going with the PR that only fixes the second issue.
