### ISSUE TITLE
Completion offers `nuint` over `null`

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#43439]
**Version Used**: Version 16.7.0 Preview 1.0 [30015.115.master]

**Steps to Reproduce**:

1. Type `object foo = nu`
2. Look at the screen 

**Expected Behavior**:
It would be great if `null` was preselected, either because of target type matching, or, perhaps more selfishly, because my personal muscle memory is hardcoded into the IDE.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/754264/79537426-8ebec100-80c5-11ea-83c2-85d24ed17f7f.png)

**Comment by sharwell** [comment]
If the completion MRU does not contain either `nuint` or `null`, the selection algorithm should treat `null` as having priority over `nuint` with the same precedence that the MRU normally provides.

**Comment by CyrusNajmabadi** [comment]
Have heard about this from more internal customers.  We should def do this.

**Comment by pentp** [comment]
Installed the latest VS 16.7 preview and have been fighting with my muscle memory all day.
Somehow the MRU mechanism isn't reliable here (it depends on some context I guess).

**Comment by davidwengier** [comment]
Now that 16.7 is out, I hit this on Twitch last night so there are at least 3 more people who know about it too :)

**Comment by CyrusNajmabadi** [comment]
Fixing now.
