### ISSUE TITLE
Addition of ILogger-accepting method in MSBuildWorkspace is a source breaking change

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#43437]
1. Have some tool that used MSBuildLocator and then MSBuildWorkspace.OpenSolutionAsync from the same method.
2. Move to a newer version of Roslyn that contains https://github.com/dotnet/roslyn/pull/42319

**Expected:** your code still works
**Actual:** it fails at runtime potentially with some strange failures.

One failure mode I'm seeing is the method that calls MSBuildWorkspace.OpenSolutionAsync triggers a load of ILogger from Microsoft.Build.Framework since that's now the method being chosen by overload resolution. If you are using MSBuildLocator in that same caller, that means it's loaded before your use of MSBuildLocator runs, causing MSBuildLocator to fail or end up with mismatched binaries.

**Comment by jasonmalinowski** [comment]
We had a few ideas for mitigating this:

1. Rename the method that takes an ILogger, so that way you can't accidentally trigger a load unless you really meant to use that overload. That still means you have the gotcha of the MSBuildLocator having to be ran first.
2. Make the ILogger a property; avoids silly overloads but same caveat as before.
3. Switch the property back to a string for the binary logging path, which is easy to use again but does lose the flexibility we were hoping to have here.

**Comment by jmarolf** [comment]
> That still means you have the gotcha of the MSBuildLocator having to be ran first.

You always need to run the `MSBuildLocator` and register and instance before calling `MSBuildWorkspace.Create()`. You mean you will need to add an MSBuild reference if we add the Method in 1?

To me it seems like 1 is the best we can do. `ILogger` being a property doesn't make sense as you can use the `MSBuildWorkspace` to load multiple projects. As has already being pointed out, having it be a string is an unnecessary limitation. I think it makes the most sense as an API to pass the logger in at the `Open*Async` methods. 

```csharp
public async Task<Solution> OpenSolutionAsync(
            string solutionFilePath,
            IProgress<ProjectLoadProgress> progress = null,
            CancellationToken cancellationToken = default)
```

```csharp
 public async Task<Solution> OpenSolutionWithLoggerAsync(
            string solutionFilePath,
            IProgress<ProjectLoadProgress> progress = null,
            ILogger msbuildLogger = null,
            CancellationToken cancellationToken = default)
```

```csharp
public async Task<Project> OpenProjectAsync(
            string projectFilePath,
            IProgress<ProjectLoadProgress> progress = null,
            CancellationToken cancellationToken = default)
```

```csharp
public async Task<Project> OpenProjectWithLoggerAsync(
            string projectFilePath,
            IProgress<ProjectLoadProgress> progress = null,
            ILogger msbuildLogger = null,
            CancellationToken cancellationToken = default)
```

**Comment by jmarolf** [comment]
@sharwell can we add this to the design review so this can get fixed?
