### ISSUE TITLE
Workspace services are not disposed with the workspace

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43442]
When a `Workspace` is disposed, the workspace services it created via `IWorkspaceServiceFactory` instances should be disposed if/when they implement `IDisposable`. Services exported directly from the MEF export provider (as opposed to ones created by a factory) do not need to be disposed with the workspace because they are already disposed when the MEF export provider is disposed.

Found during investigation of #43330.

Related to #43441

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, we should assign to a person/milestone to be done.
