### ISSUE TITLE
TemporaryWorkspace is not disposed after use

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43441]
Currently `TemporaryWorkspace` instances are not disposed after use, which can lead to non-deterministic release of resources used by workspace services.

https://github.com/dotnet/roslyn/blob/9e48ecfa05dc783cc50d2772197a07c84abda6e5/src/Workspaces/Remote/Core/Services/SolutionService.cs#L181-L183

Found during investigation of #43330.

**Comment by CyrusNajmabadi** [comment]
There is no TemporaryWorkspace type anymore, and i looked around, but did not see anything similar to the above code pattern.
