### ISSUE TITLE
Extract Interface should support reusing existing interface (extract additional members)

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#4345]
It should be possible to invoke extract interface where an interface already exists, and add additional members to the existing interface.

There should probably be a combo with a list of interfaces where you can add members and a radio that toggles between "Create new interface" or "Use existing interface".

**Comment by Pilchie** [comment]
I think that there are higher priority, more common refactorings that we should tackle before adding bells and whistles to Extract Interface.  If a Pull Request came along though...

**Comment by KirillOsenkov** [comment]
I agree this is low-pri, I suggest just keep it on the backlog for whenever you (or a kind contributor) will have time for it.

**Comment by CyrusNajmabadi** [comment]
This should be covered by the "pull members up" feature:

![image](https://user-images.githubusercontent.com/4564579/75635364-448f8800-5bca-11ea-9829-1e465c6b43c7.png)

I think the user experience is acceptable here as you can get hte bulk of your members initially, then as you add new ones, you can just quickly shoot of the action to pull it into the interface.
