### ISSUE TITLE
VS.net incorrectly indicates that a cast is redundant when it absolutely isn't

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43458]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/913014/vsnet-incorrectly-indicates-that-a-case-is-redunda.html)._

---
Consider the following:

var priorMonthAmount = pricePerPriorMonth * (decimal)billableDaysInPriorMonth;

Where pricePerPriorMonth is a decimal and billableDaysInPriorMonth is an integer.

If you take off the (decimal) you'll get an integer value back with no decimal places.

Yet VS.net indicates that this case is redundant. It is not and VS.net shouldn't be showing informationals that it's redundant because a more junior developer might take VS.net's word for it and remove it and break code in very hard to detect ways. 

VS.net needs to be smart neough to know this case and not suggest to remove the cast.

---
#### Visual Studio Feedback System on 2/10/2020, 11:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/12/2020, 08:18 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Visual Studio Feedback System on 4/3/2020, 01:44 AM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
@CyrusNajmabadi Do you think your recent cast simplification bug fixes would have handled this false positive?

**Comment by CyrusNajmabadi** [comment]
Not certain, we'd have to check.  For the original person filing, what is the type of `pricePerPriorMonth`?  Thanks!

**Comment by CyrusNajmabadi** [comment]
I don't actually understand the problem here.  VS seems to do what i woudl expect.  A `decimal * (decimal)int` can be simplified to `decimal * int`.   This is even called out in the spec:

https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#binary-numeric-promotions

> Binary numeric promotion occurs for the operands of the predefined +, -, *, /, %, &, |, ^, ==, !=, >, <, >=, and <= binary operators. Binary numeric promotion implicitly converts both operands to a common type which, in case of the non-relational operators, also becomes the result type of the operation. Binary numeric promotion consists of applying the following rules, in the order they appear here:

> If either operand is of type decimal, the other operand is converted to type decimal

So it's redundant to have a `(decimal)` cast here.

**Comment by CyrusNajmabadi** [comment]
Note:

![image](https://user-images.githubusercontent.com/4564579/79615019-962a9e00-80b6-11ea-990c-0eaf4deec526.png)

![image](https://user-images.githubusercontent.com/4564579/79615024-9cb91580-80b6-11ea-8e85-f740f756f779.png)

In both cases you get a decimal back.  It is not accurate that: If you take off the (decimal) you'll get an integer value back with no decimal places.
