### ISSUE TITLE
Consider providing a common base type between ExpressionSyntax and PatternSyntax

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#43453]
IDE has a lot of codepaths that want to treat these uniformly.  i.e. for purposes of things like parenthesization (and the reverse), precedence and the like.  With the introduction of patterns (and the fact that patterns and expression bridge through IsPatternExpression (which bridges from expression to pattern) and ConstantPattern (which bridges from pattern to expression), a lot of our codepaths have gotten very degraded since the only type we can use in common is effectively CSharpSyntaxNode.

This means that we effectively have no guardrails anywhere here, and we have to annotate all these methods with asserts/contracts that we either have a Pattern or Expression.  And it's still easy to potentially fall off when people just blindly pass around something like `.Parent` (which would have previously errored when things were strongly typed, forcing the caller to think about it).

I really don't love ExpressionOrPatternSyntax.  But it would provdie a way for us to be much more strongly typed here and to prevent accidental problems that are easy when everything just takes SyntaxNode.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Would love to hear thoughts from the team here please.

**Comment by jcouv** [comment]
Seems okay to me. Just like `ExpressionSyntax` and `TypeSyntax`.

The C# 7 syntax hierarchy: [SyntaxNodes.txt](https://github.com/dotnet/roslyn/files/4495013/SyntaxNodes.txt)

**Comment by 333fred** [comment]
For `TypeSyntax`, it's a form of `ExpressionSyntax`. Would that mean that `PatternSyntax` would be an `ExpressionSyntax`?

**Comment by AlekseyTs** [comment]
> Would that mean that `PatternSyntax` would be an `ExpressionSyntax`?

I think the proposal is to have them inherit from one base, but not from each other. Seems fine to me.

**Comment by CyrusNajmabadi** [comment]
> For TypeSyntax, it's a form of ExpressionSyntax

Yes, though we didn't have to have done that.  It could have been a bridge type like `TypeExpression:Expression` (i.e. what we do with ConstantPattern)`.  

> I think the proposal is to have them inherit from one base, but not from each other. Seems fine to me.

Yup.  That's my proposal here.  We'd just have:

```c#
class ExpressionOrPatternSyntax { /* nothing */ }
class ExpressoinSyntax : ExpressionOrPatternSyntax { }
class PatternSyntax : ExpressionOrPatternSyntax { }
```

The type just serves to be a much narrower guard to pass along either of these without allowing accidental things like passing along a statement or switch-arm etc. (things that have actually happened while i was writing this :))

**Comment by 333fred** [comment]
Seems fine to me. Just making sure I understood whether we were trying to do the same thing as TypeSyntax, or slightly different.

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/43526
