### ISSUE TITLE
RenameDocument API doesn't handle all naming conventions 

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#43461]
In https://github.com/dotnet/roslyn/pull/41267 the RenameDocument API was introduced, but currently does not handle all naming conventions. 

Specifically noted, it doesn't handle ```Foo`2``` as a naming style. Other class and file matching code likely has this issue as well.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
