### ISSUE TITLE
Need to return SourceRoot Items to for referenced projects

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/roslyn#43476]
**Version Used**: 
Latest

We need to return the `SourceRoot` items calculated by `InitializeSourceRootMappedPaths` so that other tools can access the map outside of the immediate project. No target returns the `SourceRoot` items today.

This was needed to enable Coverlet, and likely other tools to work. Coverlet had to get the `SourceRoot` items for each of the projects referenced by a test project.

@tmat and I worked with @MarcoRossignoli to come up with a solution. To work, we need to either add a new target like this:

```xml
  <Target Name="GetPathMap"
          DependsOnTargets="InitializeSourceRootMappedPaths"
          Returns="@(_LocalTopLevelSourceRoot)"
          Condition="'$(DeterministicSourcePaths)' == 'true'">
    <ItemGroup>
      <_LocalTopLevelSourceRoot Include="@(SourceRoot)" Condition="'%(SourceRoot.NestedRoot)' == ''"/>
    </ItemGroup>
  </Target>  
```

Or return the `SourceRoot`'s from `InitializeSourceRootMappedPaths` directly.

See https://github.com/tonerdo/coverlet/issues/363

**Comment by clairernovotny** [comment]
Can we get this into 3.1.xxx servicing?

**Comment by clairernovotny** [comment]
Ping on servicing?

**Comment by tmat** [comment]
@dsplaisted @jaredpar

**Comment by clairernovotny** [comment]
Jared answered in the PR, master goes to both 5.0.xxx and 3.1.xxx branches, so the answer is yes.
