### ISSUE TITLE
Add `Class View` Option to Code Editor

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#43484]
Suppose we have this class
```C#
namespace x
{
    class Class1
    {
         void foo()
         {
             // some code
         }
     }
}
```
I suggest to add a `Class View` command to the View Menu, to show only the members of the current class in the code editor, without viewing the namespace and class definitions, as they already appear in the upper lists. This will save the left margin and makes lines shorter so most of them can appear on the screen without scrolling, especially when using the zoom menu to magnify the code. So, the above class will be shown as:
```C#
void foo()
{
   // some code
}
```

The editor window can show a button to close the class view, or we can toggle it from the View Menu, so we can modify access modifiers, inheritance and implementation if we want.
Tools/Options window can offer an option to use class view with files that contains only on class/struct.
This will bring the top level code experience to all classes, and encourage writing each class in a single file.
A point to think about: Do we need to add `partial` to the upper lists in the Class View?
Note:
I gave the sample code in C#, but I ask for this in VB too.

**Comment by jinujoseph** [comment]
Related to #24129 and #14143

**Comment by gilfusion** [comment]
VB6 had (and VBA still has) a toggle in the code editor to switch between a full code view and a single method view, using the navigation bar to switch between methods or definitions outside a method. Don't know if that's doable the way C# and VB are structured today.

**Comment by CyrusNajmabadi** [comment]
Closing out.  C# now supports namespace directives as well as namespace blocks.  So teh code can be changed to:

```c#
namespace x;

class Class1
{
     void foo()
     {
         // some code
     }
}
```

Removing that level of indentation.

**Comment by VBAndCs** [comment]
still there is one more indentation level. Why not:
```
namespace x;
class Class1;

void foo( ) {
     // some code
}
```


In fact, modifying view options in the editor is more effective, and can be applied to many languages especially VB.NET not only C#.
