### ISSUE TITLE
C# Syntax Explainer Tool

### ISSUE THREAD

**Issue by aadage** [dotnet/roslyn#43488]
C# has become very complex and it can be difficult to keep up with all of the new features and syntax changes.
Examples
- The question mark is used in many different ways and is part of a number of different operators.
- There are multiple ways to accomplish the same task using different syntax which can make it difficult to read code that uses a different coding style than you do.

When reading code sometimes I have to stop and look up the syntax of the code I am reading in order to understand what it is doing.

Looking up syntax via a web search can be challenging, particularly if you don't know the name of the operator or feature you are trying to understand, which you probably don't or you wouldn't be looking it up.

It would be helpful to have a tool that I could copy and paste code into that would analyze the code and provide an explanation of the syntax being used along with links to the full documentation for each syntactical element or language feature.

This tool could be incorporated into Visual Studio
    Example: Select some code and select a popup option to explain the code syntax.

Need to have an option outside of Visual Studio too for folks using other editors and also for reading code on github or in an article.

**Comment by 333fred** [comment]
I'm going to start by moving this to roslyn and seeing if the IDE team has any ideas.

**Comment by aadage** [comment]
Thank you @orthoxerox! The Explainer output option in the SharpLab tool you linked is exactly what I am looking for.  Having something like this built into Visual Studio would be beneficial as well.

**Comment by dibarbet** [comment]
Design review outcome:  In general this is a large and complex area that we do not have a specific solution for.  This may make sense as part of the education pack, and there is some possibilities for using F1 help on specific language features in the IDE.  @mikadumont to drive investigations here.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is better handled by copilot.  Users can ask it what code means and get decent descriptions.
