### ISSUE TITLE
Analyzer - Best way to find sibling of (executable) statement

### ISSUE THREAD

**Issue by medoni** [dotnet/roslyn#43496]
Question: What is the best way to find the next sibling of an (executable) statement?

```VB
Dim statementSyntax = currentNode.FirstAncestorOrSelf(Of ExecutableStatementSyntax)()
Dim nextStatementSyntax = statementSyntax.???
```

Same in CSharp:
```CS
var statementSyntax = currentNode.FirstAncestorOrSelf<StatementSyntax>();
var nextStatementSyntax = statementSyntax.???
```

thx

**Version Used**: Assembly Microsoft.CodeAnalysis.VisualBasic, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Comment by CyrusNajmabadi** [comment]
Questions can be made over at gitter.im/dotnet/Roslyn, or discord.gg/csharp (#roslyn). Thanks!
