### ISSUE TITLE
Find all references on a class name display duplicate records

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43500]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/745319/find-all-references-on-a-class-name-display-duplic.html)._

---
Invoke "Find All References" on a class name _MyClass_ in line 10
Result: Line 7 is displayed 3 times, one at position 4 and two identical records at position 22
```
namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			MyClass obj = new MyClass(); // Line #7
		}
	}
	public class MyClass // Line #10 Invoke Find All References here
	{
		public MyClass()
		{
		}
	}
}

```

---
#### Visual Studio Feedback System on 9/25/2019, 01:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/7/2019, 00:54 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Dean Jackson on 11/22/2019, 06:03 AM: 

<p>I have the same problem!  (using version 16.3.x).  Yes, the same line (like your #7) is listed 3 times in the results. So, If you really do have 8 references, that will be 24 items in the results list!!</p>

#### Visual Studio Feedback System on 3/31/2020, 05:38 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi - the references are theoretically correct - 2 references to type names and 1 reference to ctor invocation. Do we want to show a single type name reference instead (i.e. do not show it as a type name reference when it is used in context of an object creation expression)?

![FAR_Duplicates](https://user-images.githubusercontent.com/10605811/79766039-4e855b80-82dc-11ea-8964-93de65628e51.png)

**Comment by sharwell** [comment]
This should have been fixed by #34617

**Comment by sharwell** [comment]
Here's the intended design:
https://github.com/dotnet/roslyn/pull/34617#issuecomment-485033099

**Comment by CyrusNajmabadi** [comment]
The current behavior is correct and desirable:

![image](https://user-images.githubusercontent.com/4564579/152654178-5d569269-4647-45aa-a040-e835a50c7c92.png)
