### ISSUE TITLE
Suppressing non-nullable field unitialized with Debug.Assert(field != null) in ctor

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#43523]
Debug.Assert assuming that field is not null after the black box call (InitializeFoo) should be treated the same as writing non-null to that field by the compiler.

**Version Used**: 

Package version: 3.6.0-2.20166.2

**Steps to Reproduce**:

```csharp
#nullable enable
using System;
using System.Diagnostics;
public class C {
    public Object Foo;
    
    public C() // Non-nullable field 'Foo' is uninitialized. Consider declaring field as nullable.
    {
        InitializeFoo(); // same warning with or without it
        Debug.Assert(Foo != null);
    }

    public void InitializeFoo()
    {
        Foo = "not null";
    }
}
```

**Expected Behavior**:

No warnings/errors

**Actual Behavior**:

```
Non-nullable field 'Foo' is uninitialized. Consider declaring field as nullable.
```

cc: @jcouv @stephentoub @buyaa-n

**Comment by CyrusNajmabadi** [comment]
Is `Debug.Assert` annotated in whatever dll you're referencing?  If so, this sounds like  Roslyn issue.  If not, it sounds like an issue with improper annotations.

**Comment by krwq** [comment]
@CyrusNajmabadi yes it's annotated. Fields initialization in ctor are the only thing which complain I noticed so far, I have already used Debug.Asserts to give hints to compiler and they worked fine.

**Comment by tmat** [comment]
I hit this recently as well. Solved it by assigning `null!` to these fields before calling InitializeFoo.

**Comment by stephentoub** [comment]
Here's another form of this that's problematic.  Our real case of this is a bit more complex, but essentially it boils down to this:
```C#
#nullable enable
using System;
public class C {
    private object _value;
    
    public C()
    {
        if (_value is null)
            throw new Exception();
    }
}
```
The compiler should be able to determine that there's no way to exit C's ctor with _value being null, yet it still warns that _value may be uninitialized.

**Comment by jcouv** [comment]
@stephentoub I'll move your latter scenario to https://github.com/dotnet/roslyn/issues/44046
Currently we do different analysis for what we consider "uninitialized", so it doesn't just mean "not null". But maybe we should just align the two.

**Comment by sjb-sjb** [comment]
Here's another example.  A "dereference of a possibly null pointer" is given on the third line at "name.Length;", but if you comment out the Debug.Assert then the error / warning goes away.

        int Example()
        {
            string name = "sdaM";
            Debug.Assert(name != null);
            return name.Length;
        }

It does seem a bit perverse that asserting something is not null causes you to have a 'possibly null' error.

**Comment by RikkiGibson** [comment]
What target framework are you using?

**Comment by sjb-sjb** [comment]
UWP, debug mode
Microsoft.NETCore.Platforms 3.1.0
NETStandard.Library 2.0.3
Windows 1909, build 18363.1016
