### ISSUE TITLE
Numeric promotions

### ISSUE THREAD

**Issue by miniwolf** [dotnet/roslyn#43535]
I started looking into numeric promotions, wrote this code:

```
public static dynamic func(dynamic val1, dynamic val2)
{
    return val1 + val2;
}

public static void Main(string[] args)
{
    var y = (uint)2 + 1;
    var x = func((uint)2, 1);
    Console.WriteLine(y.GetType() == x.GetType());
    Console.WriteLine(x.GetType());
}
```
I compared the result in your language specification: https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#binary-numeric-promotions

> Otherwise, if either operand is of type uint and the other operand is of type sbyte, short, or int, both operands are converted to type long.

This does not seem to hold up in the compile time version, where the result will always be a uint.
In the dynamic case I see this result, and will get a long.

Can someone explain why this is? Is this what I should expect or is this a problem in either dynamic bindings or the compile time static bindings?

**Comment by CyrusNajmabadi** [comment]
> This does not seem to hold up in the compile time version, where the result will always be a uint.
In the dynamic case I see this result, and will get a long.

This is because you're adding a constant value.  If you change to:

```c#

public static void Main(string[] args)
{
    var a = 1;
    var y = (uint)2 + a;
    var x = func((uint)2, 1);
    Console.WriteLine(y.GetType() == x.GetType());
    Console.WriteLine(x.GetType());
}
```

You'll see things change as the compiler doesn't know what teh actual values are and cannot constant fold.
