### ISSUE TITLE
Revisit automatic brace completion tests

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43560]
It's difficult to understand the semantics of `AutomaticBraceCompletionTests`. The following cases should be reviewed, with the test framework documented to keep this clear for future reviews:

1. Cases where a matching closing brace is automatically inserted after an opening brace is typed.
2. Cases where no matching closing brace is inserted, even though the typed character might look like an opening brace in some context. For example, `<` can be a matched brace when used for a generic type, but is not a matched brace when used as a binary or pattern-matching operator.
3. Cases involving multiple levels of nested matching braces.

See also https://github.com/dotnet/roslyn/pull/43522#discussion_r411787861.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to change this we should assign to a person/milestone and make the change
