### ISSUE TITLE
Relax CS8350 when passed ref-parameter are created in the same stack frame

### ISSUE THREAD

**Issue by BrunoZell** [dotnet/roslyn#43591]
**Version Used**:
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.8.03752
C# 8.0

**Prelude**

Currently C# forbids the use of a by-ref paramter together with a stack-allocated `Span<T>` since the span could escape its stack frame. However, when all passed arguments of the function are instantiated in the same stack frame, it could be legal to call it. Here is a real world example I took from a recent StackOverflow question of mine:

**Steps to Reproduce**:

I am using a `SequenceReader<T>` to copy contents from a `ReadOnlySequence<T>` into different `Span<T>`. However, I get a compiler error when I try to encapsulate the copy logic into a separate function and want to call it with a `Span<T>` allocated on the stack.

```csharp
var sequence = new ReadOnlySequence<byte>(new byte[20]); // Source data to copy

Span<byte> heap = new byte[10]; // Target location 1
Span<byte> stack = stackalloc byte[10]; // Target location 2

var reader = new SequenceReader<byte>(sequence);

TryReadInto(ref reader, heap); // This is fine
TryReadInto(ref reader, stack); // Gives compile time error CS8350
```

Since the instance method [`TryCopyTo`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1.trycopyto?view=netcore-3.1) on `SequenceReader<T>` does not advance the reader, I have created a higher level function that takes care of that:

```sharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
static bool TryReadInto(ref SequenceReader<byte> reader, Span<byte> destination)
{
    if (reader.TryCopyTo(destination)) {
        reader.Advance(destination.Length);
        return true;
    }

    return false;
}
```

As long as the destination is heap allocated everything works fine. But when the destination is allocated using `stackalloc` the compiler complains with a _CS8350: This combination of arguments to is disallowed because it may expose variables referenced by parameter outside of their declaration scope_.

When I do not pass the reader as reference that compiler error goes away, but it is required for the reader to be passed as reference since `SequenceReader<T>` [is a mutable struct](https://docs.microsoft.com/en-us/dotnet/standard/io/buffers#sequencereadert-common-problems) and the position is advanced within the function.

**Expected Behavior**:

I get the compiler error. Parameter `reader` could be allocated in an earlier stack frame and as a ref-like struct would be able to have a `Span<T>` as a field. The method body could make the second (stack-allocated) parameter `destination` escape it's own stack frame, thus a function call with both a `ref`-parameter and a stack-allocated `Span<T>` is illegal in C#.

**Actual Behavior**:

**However, am not able to encapsulate my logic then.** When I just inline the function call manually I do not get compiler errors. I guess the compiler sees that the reader is allocated in the same stack frame as the stack-allocated `Span<byte>`. 

Is it possible for the compiler to detect that all parameters of one function call have the same stack frame as origin, or at least allow the stack frame of the calling function to be a legal origin? That way encapsulations like the one described here could be made possible. This would be a big win, especially with the ubiquitous use of `SequenceReader<T>` and extension methods nowadays.

**Comment by jcouv** [comment]
Tagging @gafter (possible relaxation of ref escape validation rules)

**Comment by BrunoZell** [comment]
https://github.com/dotnet/csharplang/issues/1130

**Comment by jaredpar** [comment]
The behavior today is "By Design". This particular problem is generally referred to as the "method arguments must match" rule and I've covered the problem in some detail in the [span safety rules](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.2/span-safety.md#method-arguments-must-match). 

There is no way to relax this given the current span safety rules where all lifetimes are inferred from declarations. Changing this requires that we expand the set of language capabilities such that we can mark certain values as having lifetimes other than the inferred default. For example stating a parameter is not allowed to escape a method. A proposal for how to accomplish that is covered here. 

https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#provide-parameter-does-not-escape-annotations
