### ISSUE TITLE
CS8627 for explicit interface implementation of generic method with class type constraint

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#43619]
**Version Used**: Version 16.7.0 Preview 1.0 [30022.238.master]

**Steps to Reproduce**:

```c#
interface I
{
    T M<T>() where T : class;
}

#nullable enable

public class Works : I
{
    public T? M<T>() where T : class => null;
}

public class Fails : I
{
    T? I.M<T>() where T : class => null;
//  ^^ error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type.
//                   Consider adding a 'class', 'struct', or type constraint.
}
```

[This code on sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB80Dt4IBmEAxnAAQCSAsAFADed5z5AKuQLIA8rAfABQBKcgHcAFogrsQ5AAIAmANx0AvnToBiXAFcMGCMAwU4uA0fW1ZAZjnzyAdQD2CANZRyMmgyYtrbAPycPALC4pJsHrbkALy85Dp6yrRqtHR+CuQAYhCY7p50jLQsAVQAdNx8QqISCFKRGbHxuhhJAPStzAB6neSICM7kAMIAygAcAGzyAOwyAIJNemYUMACeAA4UaxAIEGBwBORg2rDkwBQuuI4iuOQwjqcUEOQAbhAY2svrFAOXuAC0CX0hgotUIklwZFuX1KdHaxXhCOKg0cuCgaAAJohyBB0ei8ABzbHkADkCmJSBJsAQ2hIMHJ5AGqw25BIKKpOXwMOSdCAA===)

**Expected Behavior**:

No compile error for explicit implementation (as with implicit implementation).

**Actual Behavior**:

Explicit implementation won't compile (but implicit implementation will).

**Comment by drewnoakes** [comment]
@jcouv does this look like a NRT bug to you?

**Comment by jcouv** [comment]
Looks like it. I don't see a reason for this behavior. Needs some investigation.

**Comment by AlekseyTs** [comment]
I think this is By Design. For explicit implementation constraints are always inherited from the method being implemented. And that constraint is not non-nullable.  The class constraint on the method is allowed to simply make a distinction between a value type vs. reference type. That is all, it is not meant to supply any nullability information on its own.

**Comment by drewnoakes** [comment]
The original issue has been addressed and no longer reproduces.
