### ISSUE TITLE
Suggestion mode integration tests failures in 16.6 Preview 2.1

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43627]
The following integration tests are failing in 16.6 Preview 2.1. They should be enabled again when the test image is updated to 16.6 Preview 3 or newer.

* CompleteStatementTriggersCompletion
* SpeculativeTInList
* CtrlAltSpace
* CtrlAltSpaceOption

**Comment by jasonmalinowski** [comment]
@sharwell Did we figure out why these broke and are working again or is it not worth the investigation?

**Comment by sharwell** [comment]
We have not been able to reproduce the problem in Preview 3. I don't want to put too much time into this until we rule out just being a transient issue.
