### ISSUE TITLE
IDE0058 doesn't fit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43648]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1000204/ide0058-doesnt-fit.html)._

---
With this short pogramm you can reproduce the problem, that VS2019 shows an IDe0058 warning and if you fix it you get a runtime exception

```csharp
using System.Collections.Generic;
using System.Dynamic;

namespace ConsoleApp1
{
    static class Program
    {
        static void Main()
        {
            List<dynamic> returnValue = new List<dynamic>();

dynamic dynamicVakue = new ExpandoObject();
            dynamicVakue.ColumnNumber = 1;
            dynamicVakue.LowerLimit = "1";

returnValue.Add(dynamicVakue);     // IDE0058 warning
            _ = returnValue.Add(dynamicVakue);   // exception
        }
    }
}
```

I had a similar problem which should be fixed in 16.1 but now this happens with 16.5.4

---
#### Visual Studio Feedback System on 4/22/2020, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
We should not assume that a `dynamic` invocation returns a value.
