### ISSUE TITLE
C# IntelliSense offers visually inconsistent types for generics

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43651]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1005043/c-intellisense-offers-visually-inconsistent-types.html)._

---
Intellisense offers visually inconsistent types for generics. 
For example, after typing in `List<Int64> list=new`, IntelliSense offers `List<long>` instead of `List<Int64>`.  IntelliSense should offer `List<Int64>` for consistency. Of course those types are equivalent, but visual flipflopping between types distracts developers during code reviews and leads to overlooking the actual bugs. Therefore, developers are forced to disregard IntelliSense suggestions and type in the types manually or to perform an additional replacement of suggested types after accepting IntelliSense suggestions. 

The types should be visually consistent on the left and the right sides of each statement.

---
#### Visual Studio Feedback System on 4/23/2020, 10:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
