### ISSUE TITLE
Intellisense incorrectly picking up cast

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43650]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1004427/intellisense-incorrectly-picking-up-cast.html)._

---
[regression] [worked-in:last full version before the one I am on]
I used to think it would be nice if intellisense could recognise the type I was casting an object to instead of having to do the double parenthesis:
(NewType)obj. NewTypeAttribute
instead of
((NewType)obj). NewTypeAttribute

This new version of visual studio still won't compile with the first method, however intellisense seems to be picking it up which is causing confusion and incorrect behavior.  Because now with intelliense you end up having a list of selections that do not apply.

Notice in the video I am attaching how my object has it's own set of attributes, yet when I am trying to cast one of those attributes to an Enum it picks up the Enums attributes instead of the object itself.

---
#### Visual Studio Feedback System on 4/24/2020, 00:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 This issue was caused by the fix for #32547.
