### ISSUE TITLE
Redundant initializion of static field is emitted

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#43652]
**Version Used**: 5.0.100-preview.5.20223.28

**Steps to Reproduce**:

1. csc /o foo.cs
2. disassembly the output

foo.cs
```c#
class C
{
    static object o = new object ();
    static bool b = false;
}
```

**Expected Behavior**:

```
  .method private hidebysig specialname rtspecialname static
          void  .cctor() cil managed
  {
    // Code size       17 (0x11)
    .maxstack  8
    IL_0000:  newobj     instance void [System.Runtime]System.Object::.ctor()
    IL_0005:  stsfld     object C::o
    IL_0010:  ret
  } // end of method C::.cctor
```

**Actual Behavior**:

```
  .method private hidebysig specialname rtspecialname static
          void  .cctor() cil managed
  {
    // Code size       17 (0x11)
    .maxstack  8
    IL_0000:  newobj     instance void [System.Runtime]System.Object::.ctor()
    IL_0005:  stsfld     object C::o
    IL_000a:  ldc.i4.0
    IL_000b:  stsfld     bool C::b
    IL_0010:  ret
  } // end of method C::.cctor
```

**Comment by stephentoub** [comment]
@jcouv, this is relevant to nullable... some of our `= null!`s which weren't supposed to show up in the IL are showing up.

**Comment by RikkiGibson** [comment]
This repros in the 16.1 compiler and the 16.3 compiler as well as the 16.5 and 16.6 compilers. When did we break this?

**Comment by marek-safar** [comment]
I don't think this was ever supported

**Comment by RikkiGibson** [comment]
At a glance it is not obvious why your scenario redundantly initializes the static bool field but this test does not:

https://github.com/dotnet/roslyn/blob/1ba2585e3849e9621575b51ae02d0f948aaedf20/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs#L14698

**Comment by marek-safar** [comment]
It's quite obvious in your test all initializers are removed. Change one of them to a non-default value.

**Comment by RikkiGibson** [comment]
changing any of the initializers to non-default values does cause all of them to get emitted as one might predict. I wonder if this behavior was borne out of convenience or if there is some reason we want to avoid doing the optimization except when *all* initializers are the default value.

**Comment by marek-safar** [comment]
> is some reason we want to avoid doing the optimization

Yes there is a reason as there could be the double initialization of the fields

```c#
    class C
    {
        static object o = Init ();
        static bool b = false;

        static object Init ()
        {
            b = true;
            return default;
        }
    }
```

**Comment by RikkiGibson** [comment]
Great point. I don't think we should attempt to fix this in general. If this feature were really desirable we could try to identify a category of expressions that we are confident won't write to other fields, or we could maybe try to optimize out all the default initializers in-order until we encounter a non-default initializer.

What does concern me about this is that it introduces a little bit of pain for `null!`. We can't just treat the assignment as suppressing the field initialization warning, we are pretty much required to emit something for it.

**Comment by RikkiGibson** [comment]
It feels like the solution to this issue is #37975.

**Comment by RikkiGibson** [comment]
It seems like we could only expand the optimization in cases where the other initializers are known to be free of side effects. This is not an extremely compelling scenario, especially because there exists a simple workaround in source (delete the initializer).

Perhaps if this is producing a bad experience for `null!` we can revisit, but that should probably be solved by introducing a way to suppress the non-nullable field initialization warning without having to introduce a field initializer.

**Comment by marek-safar** [comment]
Perhaps this could be transformed into analyzer warning at least and discourage usage of field initializers to default values

**Comment by jaredpar** [comment]
@marek-safar  agree this would be a good analyzer. Think we should file an issue on roslyn-analyzers as a potential candidate.
