### ISSUE TITLE
Enable FixProvider for convert to interpoated string for Console.WriteLine as well

### ISSUE THREAD

**Issue by nschuessler** [dotnet/roslyn#43656]
I was asked to open this tracking issue:

My original question:

> Hello,
> 
> I am trying to write a FixProvider that can re-write:
> 
> ```
> int one = 1;
> int two = 2
> int three = 3;
> float balance = 23.40;
> 
> Console.WriteLine(“I can count: {2} {1} {0} and have {3:C} in my wallet.”, three, two, one, balance);
> ```
> 
> To
> 
> ```
> int one = 1;
> int two = 2
> int three = 3;
> float balance = 23.40;
> 
> Debug.WriteLine($”I can count: {one} {two} {three} and have {balance:C} in my wallet.”);
> ```
> 
> The problem here is in parsing the format string argument and simulating the behavior of Console.WriteLine and less so much Roslyn / FixProvider problem.
> Is there a better way than re-implementing all the parsing and argument processing logic from Console.WriteLine?

This feature apparently already exists (as the convert to interpolated string) fix provider:
![interpolatedstring](https://user-images.githubusercontent.com/54370830/80247556-1b680280-8623-11ea-8017-202c232590da.jpg)

But @jmarolf writes:
 When I originally wrote that refactoring, the idea was to get it in and see if we got requests for other methods matching the format pattern. In some loggers it is less efficient to do an interpolated string vs. passing in the args whereas the string.format transformation is always safe thing to do. 

And asked me to open an issue to potentially enable it for `Console.WriteLine` as well. Here it is.
Thanks!

**Comment by CyrusNajmabadi** [comment]
one easy way would be to just take the string literal `" whatever {0} you {1} want"` and just jam a `$` in the front, creating `$" whatever {0} you {1} want"`.  Then just have roslyn parse that expression.  It will now produce a parsed interpolated string you can use to determine waht to do with.

**Comment by CyrusNajmabadi** [comment]
Note: gitter.im/dotnet/roslyn or discord.gg/csharp (#roslyn) are better venues for these types of questions.  Thanks! :)

**Comment by jmarolf** [comment]
I wanted this open as a tracking issue for the feature of expanding our own refactoring to support more patterns

**Comment by CyrusNajmabadi** [comment]
@jmarolf Got it.  sorry :)

**Comment by jmarolf** [comment]
no problem :)

Personally, I can't think of any reason we wouldn't offer this refactoring now for common BCL types like `Console.Writeline`

**Comment by CyrusNajmabadi** [comment]
We have this.  Closing out:

![image](https://user-images.githubusercontent.com/4564579/199584157-fbbdcf56-4642-4915-8c44-a200a2338277.png)
