### ISSUE TITLE
Type inference should allow inferring `MaybeDefault` types for types disallowing annotations

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#43653]
**Version Used**: 

```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

```cs
#nullable enable
class C
{
  public T M<T>(T t) 
  {
    t = default;
    var result = M(t); // CS8604: Possible null reference argument
    return result; // no warnings
  }
}
```

**Expected Behavior**:
No warnings for `M(t)`. `Possible null reference return` warning for `return result;`

**Actual Behavior**:
The opposite - no warnings for `return result;`, `possible null reference argument` warning for `M(t)`

**Notes**
Roslyn allows `T = default` assignments for types disallowing annotations because there's no syntax that would allow such assignments as `T?` is illegal for such types.
It should similarly track type arguments inferred for `M` for exactly the same reason as I cannot specify a nullable type argument here explicitly i.e. the following is not legal: `M<T?>(t)`.

Note that unlike `t = default` the resulting state is currently always not annotated i.e. unlike `t` I can return `result` without warnings. Consequently if I want to use `M<T?>(t)` I'm forced to suppress null reference argument warning like this: `M(t!)`. Such suppression removes the warning and since `result` is not considered nullable compiler becomes unable to track `default` state through the program.

The same problem exists with default literals:
```
void M<T>(T t)
{
  Infer(t, default); // warning for 'default'
}

Infer<T>(T t1, T t2) => t1 ?? t2;
```

**Comment by jcouv** [comment]
This will likely be covered by `T??` work. Tracked by https://github.com/dotnet/roslyn/issues/29146

**Comment by jcouv** [comment]
It looks like this was fixed. There is now a warning on the return statement only.

```
#nullable enable
class C
{
  public T M<T>(T t) 
  {
    t = default;
    var result = M(t);
    return result; // warning CS8603: Possible null reference return.
  }
}
```
([sharplab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABAJiwGFiBvYrLEgZiwBUsBZAHlYD4AKdgBcAlFnpY6RBgyFYAvFmAYAZskRCA3BIYA3ZACcsBjAGcNCzv1HbpMkgHZjZjZqwB6d1gDuhmAEsYAHMqAGUADgA2AAYmECwABQB7U1N/dGx4JGcVDBMYAGNsRwA6CQBfYnKgA===))
I'll go ahead and close as fixed. Thanks
