### ISSUE TITLE
Symbol equality should allow distinguishing between native integers and underlying types

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#43657]
`Symbol` equality currently ignores differences between `nint` and `System.IntPtr` and between `nuint` and `System.UIntPtr`.

From the public API, `SymbolEqualityComparer.Default` should treat the types as distinct.

From the internal API, `TypeCompareKind.ConsiderEverything` should treat native integer types and underlying types as distinct, and a new `TypeCompareKind` value should be added to ignore the differences.

**Comment by cston** [comment]
cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
The public behavior makes sense to me. Thanks @cston.
