### ISSUE TITLE
Generate local function code fix

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#43671]
When we have an unbound identifier used for a method argument for a delegate type parameter, we could offer to declare a local function (or even a member method, but I personally find that less useful.)

```cs
// before
void M1(Action<int> a1)
{
}

void M2()
{
    M1(doSomething); // generate local function 'doSomething'?
}


// after
void M1(Action<int> a1)
{
}

void M2()
{
    M1(doSomething);

    void doSomething(int i)
    {
    }
}
```

Parameter names could come from the target delegate type, although granted they won't always be very pleasing parameter names.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
