### ISSUE TITLE
Microsoft.CodeDom.Providers.DotNetCompilerPlatform version 2.0.1 includes System.Net.Http v4.6.24705.1 in bin\rosyln folder which triggers vulnerabilities from Veracode scan

### ISSUE THREAD

**Issue by samjudeh** [dotnet/roslyn#43708]
**Version Used**: 
2.0.1

**Steps to Reproduce**:
1. Include Microsoft.CodeDom.Providers.DotNetCompilerPlatform package to a project. In my case I have a MVC Web App.
2. Build project 
3. Check Roslyn folder under bin
4. Note down the version of the System.NET.Http under Roslyn folder

**Expected Behavior**:
Bin/Roslyn folder should have the version of System.Net.Http.dll without any vulnerabilities.

**Actual Behavior**:
Bin/Roslyn folder have the version of System.Net.Http.dll (4.6.24705.1) with security vulnerabilities. Confirmed with Veracode Scans.

**Comment by sharwell** [comment]
@StephenMolloy where should this issue be moved to?

**Comment by StephenMolloy** [comment]
Here? Microsoft.CodeDom.Providers.DotNetCompilerPlatform does not pull in System.Net.Http. It was included with whatever version of microsoft.net.compilers was targeted in this application. We are getting closer to releasing an update for Microsoft.CodeDom.Providers.DotNetCompilerPlatform that includes a more recent Microsoft.Net.Compilers package. (3.4 or newer?). Maybe that will solve this issue? But Microsoft.CodeDom.Providers.DotNetCompilerPlatform doesn't control what version of System.Net.Http comes with the roslyn compiler package.

**Comment by jmarolf** [comment]
> Microsoft.CodeDom.Providers.DotNetCompilerPlatform doesn't control what version of System.Net.Http comes with the roslyn compiler package

@StephenMolloy `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` includes `System.Net.Http.dll` under `tools\RoslynLatest` but it is unclear to me why it does this. Nothing in the `tools\RoslynLatest` folder requires it and if you look at the `Microsoft.Net.Compilers` package it does not include it either.

@sharwell I assume this issue should be moved to [aspnet/RoslynCodeDomProvider](https://github.com/aspnet/RoslynCodeDomProvider)?

**Comment by StephenMolloy** [comment]
The current `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` package includes versions 1.3.2 and 2.10 of the `Microsoft.Net.Compilers` package. An update in the near future will also include something newer than 3.4. Version 2.10 of `Microsoft.Net.Compilers` does indeed include `System.Net.Http.dll`. I don't know why. We (DotNetCompilerPlatform) just copy the compiler tools folder as it was shipped. As mentioned before, the next update we release will include a package targeting 3.4 or newer which does not ship with System.Net.Http.dll. Projects that target old (pre 4.7.2) frameworks though will still use one of the older versions of Microsoft.Net.Compilers and might still have System.Net.Http.dll copied to their 'bin\roslyn' folder when they compile.

**Comment by jmarolf** [comment]
ah, thanks @StephenMolloy. We could use this bug to track patching `Microsoft.Net.Compilers` version `2.10.0`, but since this is already fixed in upstream versions I would just recommend folks use a newer version of `Microsoft.Net.Compilers`.

I still don't know if this bug should be in this repo. We have a nuget package that has a fix. I would assume we just want to update `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` to consume a newer version right?

either way I'll tag @jaredpar and @agocke who own  `Microsoft.Net.Compilers`

**Comment by agocke** [comment]
Since we have newer versions of the binaries without the HTTP dependency I don't see any reason to update our package.
