### ISSUE TITLE
Some IDE tests from time to time pop up dialogs when executed from command line

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#43709]
Here is one of the examples, I've seen different messages.
![image](https://user-images.githubusercontent.com/10522107/80397390-e77f1e00-886a-11ea-855f-f02263840071.png)

This might be coming from Microsoft.VisualStudio.LanguageServices.UnitTests.dll, but I am not certain.

**Comment by sharwell** [comment]
@dpoeschl do you recognize this?

**Comment by dpoeschl** [comment]
It looks like ChangeSig (and AddParam now too) need to accept an INotificationService instead of getting the service from the workspace.

**Comment by dpoeschl** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/43758
