### ISSUE TITLE
Class View does not show to which TargetFramework it belongs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43712]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1006208/class-view-does-not-show-to-which-targetframework.html)._

---
Observation:
The Class View panel shows each class as many times as there are TargetFrameworks defined in the .csproj file,
However, it is not clear to which TagetFramework the shown classes are valid for. (See attechment: ClassViewPanel.png)
This makes the Class View panel useless.

Expectation:
The Class View panel shows the TargetFramework when applicable, just like the References panel does (See attachment: ReferencesPanel.png)

---
#### Visual Studio Feedback System on 4/26/2020, 02:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This behavior is currently provided by the underlying project system. Before working around the limitations within dotnet/roslyn, we need to know if the project system plans to address the issue at that level.

Blocked pending resolution of dotnet/project-system#6142
