### ISSUE TITLE
Intellisense does not complete on inferred type for lambda expression

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43713]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1007195/intellisense-does-not-complete-on-inferred-type-fo.html)._

---
Consider a method defintion such as follows:

public class Foo
    {
       public void Register<T>(T entity, Expression<Func<T, object>> property) { ... }
    }

Intellisense will suggest property completion if the type is explicitly specified, e.g. this works:

Blah blah = ...;
     foo. Register<Blah>(blah, x => x.<intellisense shows completion>

However, intellisense will *not* suggest completion when the type is inferred (which the compiler definitely allows), e.g. this does not work:

Blah blah = ...;
    foo. Register(blah, x=> x.<intellisense does *not* show completion>

Pretty sure this used to work.

Using Microsoft Visual Studio Enterprise 2019
Version 16.5.4

---
#### Visual Studio Feedback System on 4/26/2020, 01:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davisnw** [comment]
The code samples got mangled in the transition form developer community.

For clarity, it should read:
---------------------------------
Consider a method definition such as follows:

```
public class Foo
{
   public void Register<T>(T entity, Expression<Func<T, object>> property) { ... }
}
```
Intellisense will suggest property completion if the type is explicitly specified, e.g. this works:

```
 Blah blah = ...;
 foo.Register<Blah>(blah, x => x.<intellisense shows completion>
```
However, intellisense will _not_ suggest completion when the type is inferred (which the compiler definitely allows), e.g. this does not work:

```
Blah blah = ...;
foo.Register(blah, x => x.<intellisense does *not* show completion>
```
Pretty sure this used to work.

Using Microsoft Visual Studio Enterprise 2019
Version 16.5.4

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
