### ISSUE TITLE
IWorkspaceProjectContext has no way to rename documents

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#43729]
Currently the only way to rename a document is to do a remove/add. This makes tracking document renames difficult and can result in some odd workarounds if things need to be tracked across these changes. 

This issue tracks coming up with a strategy to fully implement a rename solution.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need a complete rename solution, then we should just do that.
