### ISSUE TITLE
Proposal: ?= lazy initialization operator

### ISSUE THREAD

**Issue by Andriy-Gorbunov** [dotnet/roslyn#4374]
Replace the typical construction
{ return _variable ?? (_variable = new Instance()); }
with
{ return _variable ?= new Instance(); }
This also can be atomical, i. e. prevent double calculating of the right side if two threads try accessing the  field at once.

**Comment by khellang** [comment]
Related to #3415, #3630, #524 and #3251

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
