### ISSUE TITLE
FindReferencesAsync return empty

### ISSUE THREAD

**Issue by srxqds** [dotnet/roslyn#43744]
**Version Used**: 
![image](https://user-images.githubusercontent.com/5187024/80486999-abdd7480-898e-11ea-81d6-db7bc090ea63.png)

**Steps to Reproduce**:
1. define the c# test code:

```c#
using System;

namespace RoslynTest
{
    public class Class1
    {
        public static readonly int[] IntArray = new int[] { 1,2,};

        public readonly int[] IntArray1 = new int[] { 1, 2 };
        
        public static void TestPass(int[] intArray)
        {
            intArray[1] = 2;
            intArray.SetValue(1, 3);
        }

        public static void TestSecond(int[] intArray)
        {
            TestPass(intArray);
            int[] temp = IntArray;
            temp[2] = 2;
            GetIntArray()[2] = 3;
        }

        public static int[] GetIntArray()
        {
            return IntArray;
        }

        public static void TestOutPass(out int[] intArray)
        {
            intArray = new int[] { };
        }

        public static void TestMain()
        {
            IntArray[1] = 5;
            TestPass(IntArray);
            TestSecond(IntArray);
        }
    }
}
```
2.  call **FindReferencesAsync**:
```c#
private static void AnalyzeNode(SyntaxNodeAnalysisContext context)
        {
            // retrieve using syntax node
            var syntax = context.Node as FieldDeclarationSyntax;
            if(syntax != null)
            {
                foreach (var variable in syntax.Declaration.Variables)
                {
                    var fieldSymbol = context.SemanticModel.GetDeclaredSymbol(variable);
                    var referencedSymbols = SymbolFinder.FindReferencesAsync(fieldSymbol, context.GetSolution()).Result;
                    foreach(var ref1 in referencedSymbols)
                    {
                        foreach(var location in ref1.Locations)
                        {

                            int a = 1;
                        }
                    }
                    
                    // Do stuff with the symbol here
                }
                
            }
        }
```
3. return emtpy
![image](https://user-images.githubusercontent.com/5187024/80473528-dde3dc00-8978-11ea-9c15-2b1389f06374.png)

**Expected Behavior**:
return correct datqa

**Actual Behavior**:
return emtpy

what is wrong with it?

who can help me?

**Comment by mavasani** [comment]
@srxqds Analyzers are not allowed to access Workspace APIs. Analyzers work at the level of each compilation, and have no access to symbols outside of a compilation/project. You are attempting an unsupported scenario.

**Comment by jmarolf** [comment]
yea @srxqds, whatever you are doing in `context.GetSolution()` is likely the reason calling none of the workspace apis will work.

As @mavasani says, calling workspace apis from an analyzer is not something we plan to support. Perhaps you could explain what you are trying to accomplish and we could help you find the right approach? There is also the https://gitter.im/dotnet/roslyn forum where I am certain people would be happy to help.

**Comment by srxqds** [comment]
@jmarolf  the **context.GetSoultion()** function is extend function implemented by myself, it can work right.

I want get all possible **location** of modifing **readonly** field content, for example modify the array element value.

how can I do it?
thank you.
@jmarolf  @mavasani

**Comment by srxqds** [comment]
how can I use SymbolFinder.FindReferencesAsync?

```c#
public static ISymbol fieldSymbol; // store the filed by AnalyzeProject
public async Task LoadAnadAnalyzeProject(FileInfo projectFile, AnalyzerReport report) //TODO: Add async suffix
{
var workspace = MSBuildWorkspace.Create();
workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);
        var solution = await workspace.OpenSolutionAsync(projectFile.FullName);

        var analyzers = this.GetAnalyzers();

        await AnalyzeProject(solution, analyzers, report);
        var referencedSymbols = SymbolFinder.FindReferencesAsync(fieldSymbol, solution).Result; //the referenceSymbols is empty
    }
```
I use analyze to find the symbol and then call **SymbolFinder.FindReferencesAsync** return nothing.
