### ISSUE TITLE
[loc][Query][Roslyn] Localizability of

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#43741]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Query: | Answer:
-- | -- | -- | -- | -- | --
49,065 | Compilers\Core\Portable\xlf\CodeAnalysisResources.xlf | 0;   "Single_type_per_generator_0" | Only a single {0} can be   registered per generator. | What does the placeholder stand   for? We assumed a type for now, please confirm or explain. |  
49,082 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "WRN_GeneratorFailedDuringGeneration_Title" | Generator failed to generate   source. | Does "source" mean   "source code" here?. We assume so. Same for string:     Generator '{0}' failed to generate source. It will not contribute to the   output and compilation errors may occur as a result.    0;   "WRN_GeneratorFailedDuringGeneration"     Please, confirm |  
49,205 | tfs.web\lcl\enu\ms.vss-code-web.pr-list-resources.resjson | 0; "RequestInto" | {0} request !{1} into {2} | what do the placeholders mean? |  
49,336 | VisualStudio\Core\Def\xlf\ServicesVSResources.xlf | 0;   "ChangeSignature_NewParameterIndicator" | <new> | Hello, please confirm if this   string can be translated. |  
49,350 | VisualStudio\Core\Def\xlf\ServicesVSResources.xlf | 0;   "ChangeSignature_NewParameterIntroduceTODOVariable" | TODO | Can 'TODO' be translatable? |  
49,372 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0; "period_era" | period/era | Please clarify both   "period" and "era". Thanks. |  
49,375 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "_10ths_of_a_second_description" | The "f" custom format   specifier represents the most significant digit of the seconds fraction; that   is, it represents the tenths of a second in a date and time value.\r\n\r\nIf   the "f" format specifier is used without other format specifiers,   it's interpreted as the "f" standard date and time format   specifier.\r\n\r\nWhen you use "f" format specifiers as part of a   format string supplied to the ParseExact, TryParseExact, ParseExact, or   TryParseExact method, the number of "f" format specifiers indicates   the number of most significant digits of the seconds fraction that must be   present to successfully parse the string. | is  this possibly a typo of "ParseExact or   TryParseExact"? These words appear twice. |

**Comment by CyrusNajmabadi** [comment]
> `0; "period_era"`

See https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#gSpecifier for what this is based on.

> is  this possibly a typo of "ParseExact or TryParseExact"? These words appear twice.

Yup.  That's a problem on our end.  Opened https://github.com/dotnet/roslyn/issues/43750 to track fixing it  Thanks!

**Comment by dpoeschl** [comment]
> ChangeSignature_NewParameterIndicator

This string was removed from the project. I don't see it in https://github.com/dotnet/roslyn/search?q=ChangeSignature_NewParameterIndicator&type=Code.

> ChangeSignature_NewParameterIntroduceTODOVariable -- "Can 'TODO' be translatable?"

Good question. If I remember correctly, @tmeschter and I decided to keep it in the resources file and see if there's any meaningful translations for it. One way to check, in Tools | Options | Environment | Task List, are the entries there localized? For example, in English it appears as:

![image](https://user-images.githubusercontent.com/235241/80533651-d4e01400-8952-11ea-8d1d-3445aed7bbc1.png)

Can someone with loc installed check this?  /cc: @wli3

**Comment by dpoeschl** [comment]
Hey @chsienki, can you take a look at the source generator-related loc questions?

**Comment by chsienki** [comment]
For both the source generator ones, the assumptions are correct.

The placeholder in `Single_type_per_generator_0` represents a type.
The 'source' in `WRN_GeneratorFailedDuringGeneration_Title` refers to source code

**Comment by PDostalek** [comment]
and the last one?  @chsienki 

49,205 | tfs.web\lcl\enu\ms.vss-code-web.pr-list-resources.resjson | 0; "RequestInto" | {0} request !{1} into {2} | what do the placeholders mean? |  
-- | -- | -- | -- | -- | --

**Comment by chsienki** [comment]
Hmm, nothing to do with my change. From the path it doesn't even look to be Roslyn related. @dpoeschl?

**Comment by PDostalek** [comment]
Closing...found issue in the last one. THanks for checking
