### ISSUE TITLE
Tests invalidated by target-typed conditional

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#43763]
The following tests are invalidated by the target-typed conditional expression feature and are skipped in the feature branch `features/target-typing`. Some work will be needed to update the tests (and probably the features) for the presence of the new target-typed conditional expression feature.

- `UseConditionalExpressionForAssignmentTests.TestConversionWithUseVarForAll_CastInsertedToKeepTypeSame_Throw1`
- `UseConditionalExpressionForAssignmentTests.TestConversionWithUseVarForAll_CastInsertedToKeepTypeSame_Throw2`
- `UseConditionalExpressionForReturnTests.TestConversion1_Throw1`
- `UseConditionalExpressionForReturnTests.TestConversion1_Throw2`

**Comment by jasonmalinowski** [comment]
Resolving in favor of #44036 which is also tracking these tests, and is the test number actually mentioned in the skip attributes.
