### ISSUE TITLE
'MSB6006: "csc.exe" exited with code 1' when analyzer ID has whitespaces

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#4376]
1. Create an Analyzer with following code, which just fires a diagnostic on every named type. Note that the analyzer uses an ID which has whitespace characters and a message string with multiple lines.

    ```c#
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public class Analyzer2Analyzer : DiagnosticAnalyzer
    {
        public static readonly DiagnosticDescriptor Descriptor = new DiagnosticDescriptor(
            "My ID",
            @"My Title",
            @"My Message with
            multiple
            new
            lines.",
            "Category",
            DiagnosticSeverity.Error,
            true);

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Descriptor);

        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.NamedType);
        }

        private void AnalyzeSymbol(SymbolAnalysisContext context)
        {
            context.ReportDiagnostic(Diagnostic.Create(Descriptor, context.Symbol.Locations[0]));
        }
    }
    ```

2. Add the analyzer nuget package reference to a C# project and build project (or invoke msbuild from command line console).
**Got:**
    ```
1>------ Rebuild All started: Project: ConsoleApplication33, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code 1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
    ```
Error list also contains the same error.
If you set the output window verbosity to detailed you can see the following:
    ```
1>  Microsoft (R) Visual C# Compiler version 1.1.0.50804
1>  Copyright (C) Microsoft Corporation. All rights reserved.
1>  
1>  Program.cs(9,11,9,18): error My ID: My Message with
1>              multiple
1>              new
1>              lines.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB6006: "csc.exe" exited with code 1.
1>Done executing task "Csc" -- FAILED.
1>Done building target "CoreCompile" in project "ConsoleApplication33.csproj" -- FAILED.
    ```
So, basically the C# compiler reports the diagnostic, but MSBuild parsing logic doesn't work and swallows all the compiler output.

3. Now remove the white space from analyzer ID, i.e. change it to "MyId" and regenerated the analyzer nuget package. Create a new C# project with this nuget package and build it.
**Got:**
    ```
1>------ Rebuild All started: Project: ConsoleApplication34, Configuration: Debug Any CPU ------
1>c:\users\mavasani\documents\visual studio 2015\Projects\ConsoleApplication34\ConsoleApplication34\Program.cs(9,11,9,18): error MyID: My Message with
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
    ```
MSBuild does report the diagnostic, but the message is truncated to have only the first line of the message string.

We need to fix C# and VB MSBuild tasks to parse diagnostics with:

1. ID having any characters including whitespaces, special characters, etc. A 3rd party analyzer can have any ID for their diagnostics.
2. Message with multiple lines and any characters.

**Comment by mavasani** [comment]
If we are really reluctant to fix MSBuild parser, one workaround that I see is having the compiler detect analyzer diagnostics with such invalid ID or messages and report its own special diagnostic that "your compilation has an analyzer which is reporting a diagnostic with invalid ID (or message), you must fix your analyzer"? This way at least the end user knows the analyzer is broken.

**Comment by mavasani** [comment]
FYI: This issue was reported to us via a Support Escalation Engineer, and one of our big customers ran into this as they had analyzer rules with both "ID with whitespaces" and "Message with multiple lines".

**Comment by tmeschter** [comment]
This may be tricky. If the parser currently assumes that the entire error is on one line then it may not be possible to change that--how would it know when to stop?

We may want to take a different approach, and add analyzers that flag "ID with whitespaces" and "Message with multiple lines" as errors or warnings.

**Comment by mavasani** [comment]
Yep, I think that may be a safer fix. We should also write a meta-analyzer that reports an error for analyzer implementations which provide such invalid ID or message.

**Comment by gafter** [comment]
Perhaps we should throw an exception from `DiagnosticDescriptor`'s constructor?

**Comment by mavasani** [comment]
Yes, that sounds a good suggestion Neal. That will automatically ensure we generate analyzer exception diagnostic. That plus writing an analyzer to flag incorrect arguments (to help the analyzer author) should be sufficient.

**Comment by mavasani** [comment]
Verified by the customer who reported this issue.
