### ISSUE TITLE
Invalid CS0165 after Environment.Exit

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#43776]
Tested in a Framework 4.7.2 console application, but probability is high the bug is universal.
```c#
void foo() {
  var smth;
  try { smh = ...; }
  catch (Exception) { Environment.Exit(1); }
  // try using smth here
```
That code results in an erroneous CS0165 "Use of unassigned local variable" compiler error.

The compiler needs to be taught that `Environment.Exit` is an even harder terminator than `return`. While I haven't checked, there might be similar functionality in Thread that would need the same treatment.

Note to any CLR maintainers reading this:
While it could be hacked around at the library level by adding a `NoReturnAttribute`, this really is a lower-level `noreturn` that belongs at the CLR level. For inspiration, see Microsoft C/C++ extension `__declspec(noreturn)`.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/csharplang/issues/538 (Proposal: never/bottom type)

**Comment by sharwell** [comment]
> The compiler needs to be taught that `Environment.Exit` is an even harder terminator than `return`.

This is true for dotnet/runtime, but what if someone provides a different copy of mscorlib that does not exit the application in this call?

**Comment by tamlin-mike** [comment]
>  what if someone provides a different copy of mscorlib that does not exit the application in this call?

From documentation/specification: "Terminates this process and returns an exit code to the operating system."

That question seems lilke asking "What if someone replaces Win32 `TerminateProcess`, or C `exit`?".

That _someone_ has then clearly violated the interface contract, and _all_ bets are off. That now-replaced function might reformat your system drive in an attempt to cover its tracks, but it's still an _absolute_ contract violation.

**Comment by CyrusNajmabadi** [comment]
This does not sound like a roslyn issue.  I'm going to close this out since we have as a lang issue for this sort of thing: https://github.com/dotnet/csharplang/issues/538

If you don't think https://github.com/dotnet/csharplang/issues/538 adequately addresses your need, please open a new issue at dotnet/csharplang with your recommended language change you'd like to see here.

THanks!

**Comment by tamlin-mike** [comment]
@CyrusNajmabadi

From the very description of this project
> The Roslyn .NET **compiler**

From my understanding, **CS** errors are produced by the compiler. I don't see how changing the C# _language_ (by creating a new "never/bottom type") could resolve this DFA bug in this diagnostic. Could you elaborate?

I oppose the closure of this issue as the bug is clearly not resolved.

**Comment by CyrusNajmabadi** [comment]
> From my understanding, CS errors are produced by the compiler. 

The compiler is properly implementing hte language as specified.  If it changed here it would be a deviation from the language spec.  As it is behaving in line with the lang spec, it's not an issue with the compier.

>  I don't see how changing the C# language (by creating a new "never/bottom type") could resolve this DFA bug in this diagnostic. 

Because then the method could be appropriately annotated (i.e. to say "this never returns") and the spec could be updated to state how the DFA algorithm works in the presence of that, and thne the compiler could be brought to be compliant with the updated spec.

> I oppose the closure of this issue as the bug is clearly not resolved.

I outlined the steps you can take if you do not feel that the existing CSharpLang issue adequately would address your use case.  :)

**Comment by tamlin-mike** [comment]
The _language_ doesn't specify the CS0165 diagnostic, does it.

It therefore follows logic that it most certainly doesn't specify that the compiler shoud abort compilation with a bogous diagnostic for well-formed code.

The compiler is the entity adding this diagnostic, and the compiler must (as you correctly have identified) behave as specified by the language.

Since the code is not only well-formed, but also correct, when the compiler issues an **error** diagnostic CS0165 for correct code, you can be goddamned certain the bug is in the compiler and not in the language spec! So please stop trying to sweep this compiler diagnostic bug under the rug - it's preventing production of binary from well-formed code, and that sure as hell is not the purpose of a compiler!

To reiterate:
```c#
public static int Erroneous_CS0165_Broken_DFA_on_explicit_process_termination()
{
  int smth;
  try { smth = 0; }
  catch (Exception) { Environment.Exit(1); }
  return smth; // <- erroneous CS0165
}
```

And just to display another error of the same diagnostic that *certainly* could **never** be solved by modifying already carved-in-stone contracts:
```c#
public static void Erroneous_CS0165_Broken_DFA_2(string optstr)
{
  // Provided documentation for TryParse is correct, 'val' can never be uninitialized if TryParse returns.
  if (optstr == null || !float.TryParse(optstr, out float val))
  {
    // Broken DFA in CS0165 Error diagnostic.
    if (optstr != null) Console.WriteLine("Watch the CS0165 error:  {0}", val);
  }
}
```

These are clear displays of compiler deficiency for this diagnostic.

**Comment by CyrusNajmabadi** [comment]
> The language doesn't specify the CS0165 diagnostic, does it.

The language specifies the rules for what is legal or not.  The compiler implements that, compiling the code, or reporting errors in it based on those rules.

Currently the compiler is implementing those rules as specified in the language specification.

> Since the code is not only well-formed, but also correct

The code is not correct as far as the **C# Language** is concerned.  If you would like the language to change to consdier it correct, that's absolutely fine.  There is a link to an approach that can accomplish this, or you can open a new issue over at dotnet/csharplang if you want :)

>  you can be goddamned certain the bug is in the compiler and not in the language spec! 

There is no bug in either currently.  Teh language spec is defined how it is currently, and the compiler is correctly implementing that specification.  There is a well understood process for making changes here, and that's to update the language accordingly, which will then flow into a particular language-version which the compiler will support in a later rlease.

> So please stop trying to sweep this 

I've swept nothing under the rug.  I'm explaining very simply how this works and what the right process is here for having changes happen :)   

> These are clear displays of compiler deficiency for this diagnostic.

All of these are a correct implementation in the compiler of hte language specificatoin.  again, if you want any changes here  (which is totally reasonable!) then that has to come through changes to the language specification.  This can happen at dotnet/csharplang.  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
> These are clear displays of compiler deficiency for this diagnostic.

To reiterate: based on the rules *of the language*, these variables are not considered definitely assigned.  Those rules are here:  https://github.com/dotnet/csharplang/blob/master/spec/variables.md#precise-rules-for-determining-definite-assignment

Here's something of high relevance:

> "In order to determine that each used variable is definitely assigned, **the compiler must** use a process that is equivalent to the one described in this section."

The language mandates the rules a compiler must follow to be considered a conformant implementation of the language.  Roslyn aims to be a conformant implementation, and so it must follow these rules.

Good news though!  Changing these rules is very possible.  Proposals can be made over at dotnet/csharplang.  They can be triaged and potentially championed by the team, and rolled into the language specification.  At that point, the Roslyn compiler will then adopt the new rules in a future release.

Note: i'm a member of the Language Design team.  If you create a good proposal, it's something i could potentially help drive.  Good luck with things! :)
