### ISSUE TITLE
Event should show as non-nullable where not assignable or invokable

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43773]
**Version Used**: 16.6 Preview 3

**Steps to Reproduce**:

```csharp
#nullable enable

using System;

class First
{
    public event EventHandler? Handler;
}

class Second
{
    public void Method(First first)
    {
        first.Handler += delegate { }; // ← hover over 'Handler'
    }
}
```

**Expected Behavior**:

> EventHandler First.Handler

**Actual Behavior**:

> EventHandler? First.Handler

**Comment by jcouv** [comment]
We have implemented no nullability checking for events yet. That is tracked by https://github.com/dotnet/roslyn/issues/29839

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
