### ISSUE TITLE
autocorrect += operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43786]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/998683/autocorrect-operator.html)._

---
Autocorrect, i.e. insert missing cast when Option Strict is on does not work for += class of operators in vb.net. Would be nice to have.

---
#### Visual Studio Feedback System on 4/20/2020, 08:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse vb experiences.
