### ISSUE TITLE
Custom tokens not displayed in task list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1010242/custom-tokens-not-displayed-in-task-list.html)._

---
Hi,
I've ran into an issue regarding the Task List and custom tokens.

**Issue description**:
Custom tokens are not displayed in task list. The only visible tokens are the default TODO.

**How to reproduce**:
1) Open any c# project.
2) Add some comments with custom task list token, i.e. // WORKAROUND description
3) Go to Tools -> Options -> Environment -> Task List
4) Add your custom token
5) Navigate to task list and your comment is not displayed

**Observed in:**
VS 16.6.0 Preview 4.0.

**Works in:**
VS 16.5.4 - works as expected and described here https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2019.

Sincerely,
Janovsky Roman

---
#### Visual Studio Feedback System on 4/28/2020, 08:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by polomint** [comment]
I am also having this exact issue in Version 16.7.0 Preview 1.0

**Comment by CyrusNajmabadi** [comment]
i likely broke this with the OOP work.  investigating.

**Comment by CyrusNajmabadi** [comment]
Debugging through, it appears as though IOptionService.OptionChanged is not getting fired in OOP.  So the RemoteTodoCommentsIncrementalAnalyzer isn't hearing about the change and isn't reanalyzing anything (or updating the set of tokens to search for).

@mavasani @tmat Not sure enough about the architecture of OOP to know what to do here.  Presumably when we synchronize over the primary solution, and we synchronize options, we should compare those to the existing set and we should issues these notifications.

**Comment by CyrusNajmabadi** [comment]
I also checked, and even when the OOP side reruns, it still gets the old value of this option, even on an up-to-date solution snapshot.  Looking at the options we get:

![image](https://user-images.githubusercontent.com/4564579/82712610-38e9b580-9c3d-11ea-8cfe-63dbb7789c62.png)

this option doesn't show up in the change option list either:

![image](https://user-images.githubusercontent.com/4564579/82712634-4a32c200-9c3d-11ea-8528-269d61196074.png)

so something is very wonky here.  even changed options aren't synchronizing over to oop.

**Comment by mavasani** [comment]
@CyrusNajmabadi Where is the option defined? Note that we only serialize the options defined in Workspaces and Features layer to the OOP side: https://github.com/dotnet/roslyn/blob/287a25a51324f252e61b6f2186e7df60c8a6161b/src/Workspaces/Core/Portable/Options/GlobalOptionService.cs#L79-L85

**Comment by mavasani** [comment]
However, if any option changes then it should generate a solution snapshot with changed options and that should be synced to OOP. So, seems like this should work. Can you check if the solution snapshot with changed options is generated on OOP side?

**Comment by tmat** [comment]
>  Presumably when we synchronize over the primary solution, and we synchronize options, we should compare those to the existing set and we should issues these notifications.

I don't think this would be the right approach as it would require holding on state for functionality. It really shouldn't be needed as any service should only depend on the solution snapshot and nothing else.

**Comment by CyrusNajmabadi** [comment]
> I don't think this would be the right approach as it would require holding on state for functionality. It really shouldn't be needed as all services should only depend on the solution snapshot and nothing else.

The problem is that hte design of the incremental analyzer is that it only reruns things it needs to rerun.

It has a API for reanalyzing when options change, but it requires to know when options have actually changed.  

What do you think should retrigger this analyzer in the OOP side?  Thanks!

**Comment by tmat** [comment]
I think the client pull should trigger it.

**Comment by tmat** [comment]
The same as diagnostics for closed files.

**Comment by CyrusNajmabadi** [comment]
i don't know what that means here.  There is no pulling for todo comments.  They're currently produced and pushed from a BG OOP incremental analyzer.    How do diagnostics know to rerun when some option changes currently?

**Comment by tmat** [comment]
Right now I think it might be done by the SolutionChecksumUpdater. It pushes changes to the remote workspace which triggers workspace changed events. The remote Solution Crawler is hooked to these events and should be rerunning analyzers.

This should however go away once we move to LSP diagnostics, where the client is gonna pull.

**Comment by CyrusNajmabadi** [comment]
> This should however go away once we move to LSP diagnostics, where the client is gonna pull.

Agreed.  We can pull in David Pugh on this as think this is a nice simple area we can test "pulling" of task/diagnostic lists.  This is is a good test area too as this exemplifies why certain change need to force all the data being reacquired.

**Comment by CyrusNajmabadi** [comment]
hey manish, can you see why the option isn't properly serializing over to the OOP side?

**Comment by DerstineBuyagan** [comment]
I'm having the same issue.

**Comment by Uzumaki-Boruto** [comment]
I use VS2019 16.7.0 Preview 2.0 and has same issue, only built in token work

**Comment by CyrusNajmabadi** [comment]
Yes  This will affect everyone on preview bits.  No need to let us continue knowing this :)

**Comment by gdignard** [comment]
Unfortunately, it isn't only the preview bits. 16.6.1 is also doing this.

**Comment by mavasani** [comment]
Investigating..

**Comment by mellevsen** [comment]
Will apparently be fixed in v16.7​ rf. https://github.com/dotnet/roslyn/pull/44873

**Comment by MUJaCHe66** [comment]
Still not fixed Version 16.6.2

**Comment by mavasani** [comment]
Yes, the fix will be in 16.7 Preview 3

**Comment by MUJaCHe66** [comment]
So non preview version not getting a fix ? Any idea when 16.7 Preview 3 will be released.

**Comment by MUJaCHe66** [comment]
Thanks everyone. Working in Version 16.7.0 Preview 3.0. and release was ahead of schedule ;)

**Comment by MUJaCHe66** [comment]
Broken again Version 16.7.0 Preview 6.0.

**Comment by mavasani** [comment]
@MUJaCHe66 I am unable to repro it on latest 16.8 preview. Are you sure you have build after 16.7.0 Preview 3.0?

**Comment by nickchobotar** [comment]
Custom task tokes finally work on VS Version 16.7.0. It did not work before.  Thank you dev team!

**Comment by digitalsigi** [comment]
Still not working in Version 16.7.2

**Comment by CyrusNajmabadi** [comment]
@digitalsigi can you please open a new issue with a repro that demonstrates the problem?  Thanks!

**Comment by jjdenhup** [comment]
I had to delete and re-add the custom task types, and then it worked

**Comment by soolafsen** [comment]
Not working in 16.8 preview 4

**Comment by SezMe** [comment]
At 16.8.2 cannot even add new task type PLUS not showing any custom tasks

**Comment by mavasani** [comment]
@SezMe can you please file a new issue with repro steps?
