### ISSUE TITLE
Test plan for "extended partial methods"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#43795]
Championed issue: dotnet/csharplang#3301
Draft spec: dotnet/csharplang#3417

- [x] accessibility modifiers
  - [x] LangVersion checks
  - [x] require implementation part
  - [x] require equivalent accessibility between signature and implementation parts
- [x] 'out' params
  - [x] require accessibility modifiers
- [x] non-'void' returns
  - [x] require accessibility modifiers
- [x] 'virtual', 'override', 'sealed', 'new' modifiers
  - [x] require accessibility modifiers
  - [x] require equivalent sets of modifiers on both parts
- [x] 'extern' modifier
  - [x] require accessibility modifiers
  - [x] only implementation part can specify it
  - [x] when implementation is 'extern' the definition part has `IsExtern == true`
  - [x] `[DllImport]` can go on either part
- [x] 'async' modifier
  - ~~require accessibility modifiers~~ (`async partial void` methods are already allowed)
  - [x] only implementation part can specify it
  - [x] when implementation is 'async' the definition part has 'IsAsync == true' (?)
    - preserving existing behavior that 'IsAsync == false' on definition.
- [x] nullability attributes
  - [x] When overriding a partial method with nullability attributes, the compiler needs to recognize+require providing the same nullability attributes present on both parts unioned.
  - [x] when overriding a partial DIM
- [x] partial methods that implement interface methods
- [x] entry point with non-'void' return
  - [x] with definition and implementation
  - [x] with only a definition
- [x] call to partial method with 'out' parameter definitely assigns the argument
- [x] ref returns
- [x] calls from outside the containing type
  - [x] from a different type
  - [x] from a different compilation
- [x] Override a method when the base is a constructed type https://github.com/dotnet/roslyn/pull/43582#discussion_r419851963
- [x] different containing type kinds
- [x] SkipLocalsInitAttribute on definition or implementation
- [x] EnumeratorCancellationAttribute on definition or implementation
- [x] include modopt from overridden method https://github.com/333fred/roslyn/blob/test/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs#L5269-L5310
- [x] overridden method has an explicit array size https://github.com/333fred/roslyn/blob/test/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs#L6215-L6481
- [x] 'in' thunk (explicit implementation of interface method due to 'in' param)
- [x] 'virtual partial' in interface
- [x] consume extended partial in VB
- [x] XML docs

IDE side:
- ~~go to implementation~~ (it's not clear what is meant by this--F12 on partial methods in general will go to the implementation part if it exists, and go to implementation will go to the interface part. Since this is a pre-existing behavior for partial methods in the IDE I don't think any work related this belongs in this test plan.)
- [ ] completion for partials #46752

Chunks of the work:
- Most diagnostic checks in #43588 
    - accessibility mods
    - 'out' params
    - extended modifiers (excluding 'async')
- IsExtern/IsAsync behavior

- [x] Pending decision: we should consider allowing or even requiring repetition of nullability attributes across the definition and implementation parts of the method.
    - (rigibson note) I'm dropping this idea after some consideration. :smile: Can revise the behavior later since it is nullable related.

**Comment by ufcpp** [comment]
In Visual Studio 16.7 Preview 2.0, the following invalid code can be compiled.

```cs
partial class C
{
    public static partial int M();
}

partial class C
{
    public static partial void M() { } // void
}

class Program
{
    static void Main()
    {
        _ = C.M(); // throws InvalidProgram
    }
}
```

**Comment by RikkiGibson** [comment]
Closing out since the last remaining item has been spun off into its own issue. /cc @jaredpar

**Comment by RikkiGibson** [comment]
We'd like to add IDE feature buddies as assignees to the feature test plan. Since I am lead to believe you are the buddy for this feature I'm going to add you as an assignee even though the issue is closed @CyrusNajmabadi. /cc @jinujoseph
