### ISSUE TITLE
[C# Interactive] Large 'For loops' causes app to hang

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#4380]
In the C# interactive window, try to run the following

    using System;
    for (int i = 0; i < 1000; i++) Console.WriteLine(i);

C# interactive will hang while executing. Functions are still available, and VS still works like normal, but you are unable to type in the window.  

While it's running, you can also highlight areas of the line, and hit enter to see the following error pop up:
![image](https://cloud.githubusercontent.com/assets/10537189/9119111/c90f6eda-3c29-11e5-9119-03ff757e5a29.png)

Closing the C# interactive window has no effect and it will still be hung if you re-open it.  The only ways to stop it from hanging are to close VS or right click and hit reset. Interestingly, the for loop works correctly after you reset, but breaks again if you close VS.

**Comment by KevinH-MS** [comment]
I'm not sure exactly which commit fixed this, but I tried it on the latest bits, and it doesn't repro.  I tried increasing the iterations to 10,000 and it ran/printed results quickly.  Please re-activate if you're still seeing issues.

**Comment by mattscheffer** [comment]
Yup looks fixed. Thanks!
