### ISSUE TITLE
IInlineRenameLocationSet.Location usage can throw ArgumentNullException

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#43809]
**Version Used**: master

**Steps to Reproduce**:

1. N/A, observed via code reading

**Possible Behavior**: Code throws `NullReferenceException`

**Details**:

[InlineRenameSession](https://github.com/dotnet/roslyn/blob/9625a14e7405d7a3ea1dc77957d5293850b69cc8/src/EditorFeatures/Core.Wpf/InlineRename/InlineRenameSession.cs#L314) calls `ToImmutableArray()` on `inlineRenameLocations.Locations`, which will throw an ArgumentNullException if the passed array is null.

There are implementations like [fsharp](https://github.com/dotnet/roslyn/blob/3ae0f7960da5af20a6b4a163e258934cad6808e5/src/Tools/ExternalAccess/FSharp/Internal/Editor/FSharpEditorInlineRenameService.cs#L90) and [typescript](https://github.com/dotnet/roslyn/blob/47340da1546b1ecb66eea3d490254b0a8f0c41d7/src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptInlineRenameLocationSet.cs#L23) which can return a null value from the `Locations` property leading to this behaviour.

It probably doesn't happen in practice, but would be good to ensure that.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
