### ISSUE TITLE
Flaky Test: Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.MakeStructFieldsWritable.MakeStructFieldsWritableTests.StructDeclaration_MixedFields_MixedAssigmentsInMethods

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#43828]
Failed 6 times in the past 14 days.

```
Context: Fix all in document
content of '/0/Test0.cs' did not match. Diff shown with expected as baseline:
 struct MyStruct
 {
-    public int Value;
+    public readonly int Value;
     public int TestValue;
 
     public MyStruct(int value)
     {
         Value = value;
         TestValue = 100;
     }
 
     public void Test()
     {
         this = new MyStruct(5);
     }
 
     public void Test2()
     {
         TestValue = 0;
     }
 }

Expected: True
Actual:   False
```

**Comment by 333fred** [comment]
@dotnet/roslyn-ide for triage. Disabled by https://github.com/dotnet/roslyn/pull/43829

**Comment by sharwell** [comment]
Changed to Area-Compilers. This is failing because the _compiler_-side analyzer driver is occasionally producing symbol start/end analyzer callbacks in the wrong order.

**Comment by 333fred** [comment]
Example test failure: https://dev.azure.com/dnceng/public/_build/results?buildId=624166&view=ms.vss-test-web.build-test-results-tab&runId=19511222&resultId=100162&paneView=debug

**Comment by mavasani** [comment]
> Changed to Area-Compilers. This is failing because the compiler-side analyzer driver is occasionally producing symbol start/end analyzer callbacks in the wrong order. I observe this reordering approximately 0.2-0.5% of the time with this analyzer.

I will investigate today. It is also likely to be an issue with the test framework. This test never failed before tests for this analyzer were ported to `Microsoft.CodeAnalysis.Testing` library. I would not rule out a test issue.

**Comment by sharwell** [comment]
I would try reverting #42605 locally to see if that was the cause.
