### ISSUE TITLE
SourceGenerator counter proposal

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/roslyn#43826]
In its current form, I probably would not use it. I do not care about `ClassDeclarationSyntax`, per se. Additionally, how is it triggered? Is there an attribute? I need to trigger on class bits, sometimes; but I also need to trigger CG at the assembly level. Then I want to generate at the `CompilationUnitSyntax` level, for bits other than classes, `enum`, etc, etc, etc.

**Comment by sharwell** [comment]
Can you clarify the counter proposal part? I'm having trouble relating the specifics of this request to the features currently available and those on the roadmap.

**Comment by mwpowellhtx** [comment]
@sharwell Hello, the first thing I want to understand is how code is delivered into the build pipeline via this form of CG. As a string? As Roslyn entities?

The next thing I want to understand is the form of that delivery. At a class level? I'd suggest it is more helpful/useful to generate at the module/compilation unit level.

And then, I have requirements to generate code at either the module level or at an assembly level.

After that, it would be interesting to support delivery of `ICollection<CompilationUnit>` versus a single `CompilationUnit`.

**Comment by CyrusNajmabadi** [comment]
@mwpowellhtx it's also not clear to me what you are asking for. It seems like all the time you want to do are possible with the current source generator prototype.

**Comment by chsienki** [comment]
@mwpowellhtx The code is returned from the generator as a string to the Roslyn compiler. Ultimately anything you can add via a new file manually can be added via a source generator.

Is there a specific problem you have that can't be solved with the [current design?](https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.md)
