### ISSUE TITLE
Embedded Resources with multiple dots in name does not get embedded

### ISSUE THREAD

**Issue by ChrisKlug** [dotnet/roslyn#43820]
**Version Used**: 3.1.200

**Steps to Reproduce**:

1. Create a class library
2. Add a file with multiple "." characters in the name. Example: myfile.en.txt
3. Make the file an Embedded Resource

**Expected Behavior**: 
The file is embedded and can be accessed through Assembly.GetManifestResourceStream()

**Actual Behavior**:
File is not embedded. Ate least not to the point where it can be retrieved. And the stream is not available through Assembly.GetManifestResourceNames() either. Renaming the file to myfile-en.txt solves the problem.

**Comment by tmat** [comment]
The resource is embedded. You can use [ILSpy](https://github.com/icsharpcode/ILSpy) to see what name does the build actually use for the resource.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="a.b.c.d.txt"/>
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/41759/80748588-ff100e00-8ad9-11ea-9598-1ee9c1b800f1.png)

**Comment by tmat** [comment]
The reason why `myfile.en.txt` is not included is that msbuild considers it a culture specific resource because it matches `*.{culture-name}.*` pattern. Culture specific resources are not passed to the compiler.

**Comment by ChrisKlug** [comment]
Thanks for the information! 
That naming convention makes total sense, but would have been hard to figure out I think. Not sure if any documentation would have helped, but it's good to know. I guess it was just a "lucky" naming coincidence. I got around it by renaming the file, which makes total sense after your explanation. Changing .en.txt to -en.txt solved it, but I guess for a different reason than I thought.
