### ISSUE TITLE
Roslyn VB Compiler Emits Unsupported IL For x86 Static Constructor

### ISSUE THREAD

**Issue by brantburnett** [dotnet/roslyn#4383]
This morning I discovered what appears to be a bug in the Roslyn VB compiler.  The result of the bug is that a static constructor for a class will fail with InvalidProgramException and the message "JIT Compiler encountered an internal limitation".

I have narrowed this bug down to the following steps to reproduce:

1.  Must be using Visual Basic and Visual Studio 2015.  The bug does not occur when compiled in Visual Studio 2013 with the former version of the compiler.
2.  Application must target x86, or be set to Prefer 32-bit.  (It appears that the x64 JIT works around this optimization problem)
3.  Optimizations must be enabled
4.  Class must have a static constructor which first initializes a Decimal constant, then initializes a Dictionary.
5.  I have replicated this problem so far targeting both .Net 4.5.2 and .Net 4.6.  This includes replicating it on a machine without .Net 4.6 installed.

An example project which demonstrates this error can be found at https://github.com/brantburnett/RoslynVBError.  Be sure to run in Release mode so that optimizations are enabled to see the error.  There is also a C# project included, which demonstrates that it doesn't have the error.

I have narrowed the specific IL error down to an extra "dup" operation before the final "stsfld" operation:

```
.method private specialname rtspecialname static void .cctor() cil managed
{
    .maxstack 4
    L_0000: ldc.i4 0x177
    L_0005: conv.i8 
    L_0006: newobj instance void [mscorlib]System.Decimal::.ctor(int64)
    L_000b: stsfld valuetype [mscorlib]System.Decimal RoslynTest.ClassWithStaticField::DecimalConstant
    L_0010: newobj instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::.ctor()
    L_0015: dup 
    L_0016: ldstr "String1"
    L_001b: ldc.r4 1
    L_0020: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0025: dup 
    L_0026: ldstr "String2"
    L_002b: ldc.r4 2
    L_0030: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0035: dup 
    L_0036: ldstr "String3"
    L_003b: ldc.r4 3
    L_0040: callvirt instance void [mscorlib]System.Collections.Generic.Dictionary`2<string, float32>::Add(!0, !1)
    L_0045: dup 
    L_0046: stsfld class [mscorlib]System.Collections.Generic.Dictionary`2<string, float32> RoslynTest.ClassWithStaticField::DictionaryField
    L_004b: ret 
}
```

If the dup operation is removed, then the JIT error does not occur.

Please let me know if there is any additional information I can provide which will be of assistance.

Thanks,
Brant

**Comment by gafter** [comment]
Can you please identify why you believe this code is incorrect?

**Comment by gafter** [comment]
Oh, I see, it leaves something on the stack at the `ret` instruction. The final `dup` is unnecessary.

Can you please provide the source code for a self-contained repro?

**Comment by brantburnett** [comment]
The working example is found here:

https://github.com/brantburnett/RoslynVBError

The particular class that presents the problem is:

```
Public Class ClassWithStaticField

    Public Const DecimalConstant As Decimal = 375D

    Private Shared ReadOnly DictionaryField As Dictionary(Of String, Single) = New Dictionary(Of String, Single) From {
        {"String1", 1.0F},
        {"String2", 2.0F},
        {"String3", 3.0F}
    }

    Public Shared ReadOnly Property Dictionary As Dictionary(Of String, Single) 
        Get
            Return DictionaryField
        End Get
    End Property

End Class
```

Is that what you need, or do you need something else?

Thanks,
Brant

**Comment by gafter** [comment]
Yes, perfect repro. This program fails when built for `Release` and run with this main program:

```vb
Module Module1
    Sub Main()
        Console.WriteLine(ClassWithStaticField.Dictionary.Keys.FirstOrDefault())
    End Sub
End Module
```
