### ISSUE TITLE
Public Interface Windows.Storage.Streams.IRandomAccessStream cannot be auto implemented

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43830]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/996993/public-interface-windowsstoragestreamsirandomacces.html)._

---
Start a new empty UWP project. Add a new class Class1. Implement Windows.Storage.Streams.IRandomAccessStream. After Enter pressed, VS encounters NullReferenceException.
```VB
Public Class Class1
	Implements Windows.Storage.Streams.IRandomAccessStream'←Press Enter here and VS throws exception
End Class
```
It happens just on this particular interface. Other interfaces just work fine.

---
#### Visual Studio Feedback System on 4/19/2020, 08:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
I can repro this issue in 16.7p1 and prior, however it seems to be fixed in Int Preview as of build 30119.10.master (16.7p2).
I will close this issue for now. However, if you continue to see this issue in 16.7.0 preview 2 or later, please let us know. Thank you!
