### ISSUE TITLE
Generators; seeing CS8055 on generated file

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#43840]
build output:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8055	Cannot emit debug information for a source text without encoding.	PlayClient (net472)	C:\Code\protobuf-net.Grpc\toys\PlayClient\IDuplex.Generated.cs	1	Active

Here `IDuplex.Generated.cs` is the generated output I've added via:

``` c#
context.AddSource($"{service.Identifier}.Generated.cs", SourceText.From(sb.ToString()));
```

which has no mechanism to indicate an encoding.

Repro is here: https://github.com/protobuf-net/protobuf-net.Grpc/pull/85

Note I have some global build props that setup embedded symbol build for "green shields" in nuget package explorer.

Note that the error remains if I remove all of the net472 targets leaving just netcoreapp3.0:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8055	Cannot emit debug information for a source text without encoding.	PlayClient (netcoreapp3.0)	C:\Code\protobuf-net.Grpc\toys\PlayClient\IDuplex.Generated.cs	1	Active

**Comment by chsienki** [comment]
You have to pass an encoding when you create the sourcetext: eg `SourceText.From(sb.ToString(), Encoding.Utf8)`

Agree this is confusing.

**Comment by mgravell** [comment]
Ah. I had based my code on `AugmentingGenerator` from the cookbook, which at the current time: omits this piece. So probably the best thing to do here is: "fix the cookbook" (and other samples)

**Comment by mgravell** [comment]
`AugmentingGenerator` now uses UTF8 via https://github.com/dotnet/roslyn/commit/f5d9e0c17f93ba2dba79c451888b2c8d5d235ac4#diff-bc0b796ab4f15f1f222681a4850c5385 ; closing, thanks @chsienki
