### ISSUE TITLE
VB.Net Brace on new Line Code Style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#43848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1006633/vbnet-brace-on-new-line-code-style.html)._

---
C# has code style options for putting braces on new lines for such things as object initialization and collection initialization. VB apparently gets no such code option even though the code styles for these cases is nearly identical between C# and VB.

For instance, if you go into the Code Style settings for Basic, in the Prefer object initializer, you get the following example:

```
' Prefer:
Dim c = New Customer() With {
    . Age = 21
}

' Over:
Dim c = New Customer()
c.Age = 21
```

I prefer style of having the brace on the new line for anything more than a simple property. IE, in the above example, the default refactor code would generate:

```
Dim c = New Customer() With
{
    . Age = 21,
    . IDNumber = 42
}
```

^ That's my prefered style for anything more than a single property being set. If I only have a single property being set, then I manually collapse to 1 line:

```
Dim c = New Customer() With { . Age = 21 }
```

^ I don't know if you can have the refactor do a single line for single property instances and do the brace on a new line for 2+ properties, but that would be even better.

---
#### Visual Studio Feedback System on 4/26/2020, 04:37 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
The Visual Basic formatter is not configurable aside from selecting Spaces or Tabs for indentation. It may be possible to change the formatting once the formatter extensibility API is available.
