### ISSUE TITLE
Completion list is missing members when typing generic delegate parameter containing IEnumerable<T>

### ISSUE THREAD

**Issue by NoneGiven** [dotnet/roslyn#43847]
The title describes the repro which uses `IEnumerable<T>`, but I imagine any generic type would do the same here.

**Version Used**: 

Visual Studio 2019 16.6.0 Preview 5.0
.NET 3.1 console application

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;

namespace Repro
{
    public class Numbers
    {
        public int Id { get; set; }
        public List<int> Values { get; set; }
    }

    public class Test
    {
        public void TestMethod()
        {
            var numbers = new Numbers();
            GenericSingle(numbers, g => g.Id);
            GenericMultiple(numbers, g => g.Values);
        }

        public U GenericSingle<T, U>(T item, Func<T, U> getter)
        {
            return getter(item);
        }

        public IEnumerable<U> GenericMultiple<T, U>(T item, Func<T, IEnumerable<U>> getter)
        {
            return getter(item);
        }
    }
}
```

1. Observe that the above code is valid and compiles with no errors.
2. Delete the text `.Id` from the `GenericSingle` invocation, then type `.` to trigger completion.
3. Delete the text `.Values` from the `GenericMultiple` invocation, then type `.` to trigger completion.

**Expected Behavior**:

In both steps 2 and 3, the completion list shows the `Id` and `Values` members of the `Numbers` class.

**Actual Behavior**:

The members only appear in the completion list in step 2.

If the type arguments are specified explicitly, then completion works as expected. If also works as expected if `GenericMultiple` is converted to an extension method as below:

```csharp
public static IEnumerable<U> GenericExtension<T, U>(this T item, Func<T, IEnumerable<U>> getter)
{
    return getter(item);
}

// ...

numbers.GenericExtension(g => g.[||] // completion works here
```

**Comment by NoneGiven** [comment]
This was fixed at some point. Doesn't occur in VS 2022 17.4.2 with a .NET 7 console application.

**Comment by CyrusNajmabadi** [comment]
Thanks for the update!
