### ISSUE TITLE
[Feature] Specialize generic code for particular instantiated types

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#4385]
Imagine a method T Foo<T>(T value)

In the body, I want to write something like:
if (value is int)
    return (T)0;

But if I do so I have a compilation error "Cannot convert type 'int' to T" and I cannot use "as" keyword because int is not a class.

So AFAIK, the only way to do it is this:
return (T)(object)0;

But this means using boxing unboxing which is obviously not good.

So I think it would be great to have a special instruction (#if maybe) for this scenario.

**Comment by NaxAlpha** [comment]
This requires support from CLR (.Net framework should be modified internally) then this feature can be added,
![image](https://cloud.githubusercontent.com/assets/11090613/9130247/89525b14-3cfa-11e5-89d3-c78f58bba992.png)

**Comment by mikedn** [comment]
Even if the C# compiler would allow (T)0 the generated code would still be using box/unbox since there's no other way to encode that cast.

Boxing isn't actually required in this case and the JIT compiler could eliminate it. It doesn't do it in this particular case but there are other cases were this already works:

```C#
static T Foo<T>(T value) {
    if (typeof(T) == typeof(int))
        return (T)(object)0;
    return value;
}
```

**Comment by MatthieuMEZIL** [comment]
In fact my idea was more general to the cast. (I should rename the subject BTW)
 
#if typeof(T) == typeof(int)
return 0;
#endif

That's why, as mentioned Mustafa, it implies a CLR change.

**Comment by mikedn** [comment]
That `#if` is exactly what happens today due to JIT optimizations (when T is a value type).

**Comment by MatthieuMEZIL** [comment]
The idea here is to be able to execute a type specific code in a generic method, whatever this specific code is.

**Comment by mikedn** [comment]
So how's that different from
```C#
static T Foo<T>(T value) {
    if (typeof(T) == typeof(int)) {
        // whatever code
    }
    return value;
}
```

**Comment by MatthieuMEZIL** [comment]
The difference is that in whatever code, you cannot use he following code for example:
static T Foo<T>(T value) {
    if (typeof(T) == typeof(int)) {
        value *= 2;
    }
    return value;
}

With what I propose, you should be able to write this:
static T Foo<T>(T value) {
#if (typeof(T) == typeof(int))
        value *= 2;
#endif
    return value;
}

**Comment by mikedn** [comment]
> you cannot use he following code for example

Actually you can:

```C#
static T Foo<T>(T value) {
    if (typeof(T) == typeof(int))
        value = (T)(object)((int)(object)value * 2);
    return value;
}
```

**Comment by MatthieuMEZIL** [comment]
Sure but the idea is to avoid the mess of cast and also to improve (a very little bit) performance avoiding the if statement at runtime.

**Comment by mikedn** [comment]
> Sure but the idea is to avoid the mess of cast 

That makes sense and it doesn't require CLR changes but I don't think this happens often enough to justify such a change in the way variables work. Basically you want some kind of control flow that also changes variable types.

> and also to improve (a very little bit) performance avoiding the if statement at runtime.

There's no `if` statement at runtime, the JIT gets rid of it.

**Comment by sharwell** [comment]
If you need to provide an implementation of `Foo<T>` for a specific `T`, you can (and probably should) put it in a different method. There's still a cast at input and a double-cast at output, but inside the separate method you can operate on the value with its known type.

```
static T Foo<T>(T value)
{
  if (typeof(T) == typeof(int))
    return (T)(object)FooImpl((int)value);

  return value;
}

static int FooImpl(int value)
{
  value *= 2;
  return value;
}
```

**Comment by MatthieuMEZIL** [comment]
@sharwell : In this case, we have the "cast mess" (using object intermediate cast which probably means boxing / unboxing for struct) 
BTW note that in your sample, you have to cast value to object before being able to cast it in int.

**Comment by mikedn** [comment]
> using object intermediate cast which probably means boxing / unboxing for struct

There is no boxing going on in the above example, I already explained this in a previous post.

**Comment by MatthieuMEZIL** [comment]
@mikedn: Ok. I have to say that I don't know but as you wrote "It doesn't do it in this particular case but there are other cases were this already works", I understood that actually there is with current JIT but I probably misunderstood.
Sorry for that

**Comment by mikedn** [comment]
So, boxing does occur in your original example (the one which uses `value is int`) but not in all other examples (all those use `typeof(T) == typeof(int)` instead). Also, boxing doesn't occur because of `(T)(object)0` but because of `value is int`.

Doing conversions via `object` is in general trivial to optimize, there's a `box` `unbox.any<T>` sequence and the JIT compiler can easily get rid of it if the source value type is the same as the destination value type.

Testing if `value` is of a certain type is unfortunately a bit more complicated. `isinst` needs to be used and this requires a reference type. `box` is then used to ensure that the value passed to `isinst` is a reference type, a boxed `int` in your example. And finally, `isinst` doesn't return true or false, it returns null or not null which complicates the test. Currently the JIT compiler has trouble understanding all this and can't eliminate boxing in such situations.

**Comment by MatthieuMEZIL** [comment]
Ok. Thanks for details

**Comment by paulomorgado** [comment]
@MatthieuMEZIL, `#if` is a compile-time construct while `T` will (or will not) be an `int` at run-time.

Although you might not think so, what you're trying to do is dynamic dispatch. You might do it the way @sharwell showed or you might use the `dymanic` "type", but you can't statically define it.

**Comment by aluanhaddad** [comment]
It seems to me that there are several discrete ideas in this proposal. 

Improved compiler optimizations for type arguments when they happen to be value types at runtime. 
Enhanced type inference via flow analysis.
Cleaner syntax for type casts. 

These all seem like could be separate proposals.

**Comment by gafter** [comment]
@aluanhaddad Ignoring the specific syntax, the use case is having generics specialized in source (like you can do in C++). It is true that might be accomplished by a bunch of independent features, but the request is just for the ability to specialize the source.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by gafter** [comment]
See https://github.com/dotnet/csharplang/issues/110 for a feature under consideration that may address the use cases.
