### ISSUE TITLE
[question] How do I let users configure an analyzer?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/roslyn#43874]
As an open source project maintainer, I would like to write Roslyn analyzers that analyze naming conventions.  For example, I personally prefer all database migration classes to start with MyyyyMMddWxyz_DescriptiveNameInCamelCase, and expect yyyyMMddWxyz to match a value supplied in an Attribute targeted to this class:

```c#
[Migration(202005010001, "First database migration")]
public class M202005010001_DescriptiveNameInCamelCase
```

I had found [AddtionalFiles.md](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md), but it's not clear to me from the sample analyzer that AdditionalFiles is the appropriate use for this kind of configuration.  Analyzers have common metadata that make sense to have strongly typed file format for:

* "Dominant" Quick Fix: A dominant quick fix is the quick fix for an analyzer positive warning.  Multiple quick fixes might exist for a given positive warning.  Domination is how you know which one wins out in batch/straight-through processing scenarios and is the easiest option to navigate to in nested context menus.  Naming convention comes from Visual FoxPro, forgive me if there is a better name than dominant.
* Quick Fix Category: Documentation, Maintainability, Layout, Naming, Ordering, Readability, Spacing, Language Enhancements, Build Enhancements
  * Documentation: Things like GhostDoc would plug-in here.
  * Maintainability: Things like inverting if statements to reduce nesting would plug-in here.
  * Layout: Indentation, off-side rules, etc. would go here.
  * Naming: Things like shortening qualified references, configuring camel casing, underscores, or even Hungarian notation if you get your jollies reminiscing about that time you put a Flight Simulator inside Microsoft Excel.
  * Ordering: Do you put private methods before public ones, etc.
  * Readability: Fixes like "Convert to Method Group" and removing redundant parentheses.
  * Spacing: Used to control things like expressions continuing across multiple lines, up to a code point break.
  * Language + Environment Symbiotics (Language Enhancements): If a language sudden gets ability to create a more robust switch statement, consider that to a stack of repetitive if expressions.  This is a bit different from readability in that a Language Enhancement may also help reduce logic errors, such as Modus Ponens errors when editing complex Boolean clauses.  Also referred to as a Symbiotic, based on the seminal computer science work of Joseph Goguen on language as narrative and languages evolving to adapt to their environment and vice versa.
  * Build + Packaging Enhancements: If the .NET SDK enhancement elides the need to specify some Assembly Attribute metadata, suggest moving that logic into the csproj.  Additional benefits would include not altering PE header file metadata through such fixes, to avoid even the tiniest alteration in continuous integration environments apart from code under test.
* Quick Fix Target Expression: Things like accessibility modifier, whether it's a class, property, field, method, constructor, etc.
* Inspection Severity

In addition, it makes sense for such config files to have the concept of Profiles, such as:

* roslyn.Full.config: Full Cleanup
* roslyn.ReformatCode.config: Just reformat the code

Similarly, I was wondering if there was any push to develop an industry standard config file for such settings.  We already have [editor.config](https://editorconfig.org/).  As a brief history lesson and helping others see "the old new thing": ReSharper for years has had capitalized on Microsoft's StyleCop efforts by creating the StyleCop for ReSharper plug-in as part of ReSharper 4.1, built by Howard van Roojen (IIRC).  As part of this plug-in, Microsoft StyleCop would run in the background as you type, using a `settings.stylecop` file.  It would then use a collection of Quick-Fixes and Code Clean-Up Modules to help you easily fix StyleCop code styling violations.

Separately, it would be useful to collect metadata on what people turn on and off - and by having a common format that can be checked into GitHub projects, we can have Microsoft data scientists apply Azure Cloud powers to force to analyze the config data sets across all C# projects.  Years ago, when I built a state-of-the-art hospital billing analysis system, I ran every rule (6000+) through the system nightly and created a Funnel chart to demonstrate the potential gains from automatically fixing a certain class of problems.  Human analysts could then "Like" certain rules or "Dislike" ones they found troublesome, which helped optimize the funnel.  I did not have machine learning back then like we have today, either.  All we had was support vector machines.  Now we have very powerful learning algorithms with massive online scale, and tools like Tableau to slice and dice the data sets for anomalies in scatter plots and L2 metrics useful for tweaking training.

Thank you and have a great day.  Stay [safe and sound](https://www.youtube.com/watch?v=47dtFZ8CFo8), everyone.

**Comment by jzabroski** [comment]
@sharwell This is created in response to your suggestion I create an issue here: https://twitter.com/samharwell/status/1256139834898255872

**Comment by jinujoseph** [comment]
cc @mavasani @sharwell @mikadumont

**Comment by jzabroski** [comment]
Any update on this?  I feel like this likely already exists as documentation, but the sprawl is so large, that unless I spend weeks, I can't find it.

**Comment by jzabroski** [comment]
Jared explained file io is outlawed by his analyzer analyzer. He said 👍


> You can pass in configuration via `/analyzerConfig` or `/additonalText`
