### ISSUE TITLE
Unable to load Roslyn.sln in VS2015

### ISSUE THREAD

**Issue by dhusemann** [dotnet/roslyn#4387]
md cloned respository ran the powershell nuget.

click on rosly.sln as stated,
after about 5 mins 
e:\Users\douglas\Source\Repos\roslyn\src\Compilers\Core\AnalyzerDriver\AnalyzerDriver.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets

e:\Users\douglas\Source\Repos\roslyn\src\Compilers\Core\SharedCollections\SharedCollections.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets

e:\Users\douglas\Source\Repos\roslyn\src\ExpressionEvaluator\VisualBasic\Source\ResultProvider\BasicResultProvider.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.VisualBasic.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.VisualBasic.targets

e:\Users\douglas\Source\Repos\roslyn\src\ExpressionEvaluator\CSharp\Source\ResultProvider\CSharpResultProvider.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets

e:\Users\douglas\Source\Repos\roslyn\src\ExpressionEvaluator\Core\Source\ResultProvider\ResultProvider.shproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets

when I look the files are in the above directly, if I try to put a copy in in the v14/8.1 and reload just get and error message  for roslyn not able to open with the file not found v14.0/8.1/8.1  files are in the 

C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\ directory.

**Comment by Pilchie** [comment]
What OS are you on?  Did you install the Tools for Windows 8.1 checkbox in VS options?

**Comment by dhusemann** [comment]
I am on windows 10,  don't think I did the checkbox for Windows 8.1.

**Comment by Pilchie** [comment]
Sadly, you need it for Shared Projects (which Roslyn uses) to work right now.  Can you go to Control Panel/Programs and Features, Find Visual Studio and Change/Modify it to add the checkbox?

**Comment by dhusemann** [comment]
Will do.  unfortunately real life will interfer for a bit. got to go to work, won't have access to the box to verify until tomorrow.

**Comment by dhusemann** [comment]
this what the issue was closing.

**Comment by naasking** [comment]
I too encountered this error, and I have all the requirements specified here installed. I'm on Windows 7 64-bit, and WindowsXaml\v14.0 doesn't have an 8.1 sub-directory, but an 8.2 sub-directory. I used mklink to create a symbolic link pointing 8.1->8.2, and that enabled me to load all the projects in a freshly installed VS 2015 community edition.

I still can't build though. I receive a FakeSign exited with error 9009 on Microsoft.CodeAnalysis.dll when I try to build using Compilers.sln. I got CodeAnalysis to build on its own by opening the individual project file, then running "powershell .\nuget\NuGetRestore.ps1", then building. If I try to build just the CodeAnalysis project from within Compilers.sln, it restores some nuget packages and the build fails.

**Comment by Pilchie** [comment]
@naasking Does the directory where you have Roslyn cloned have a space in the name?  There is a problem with our build scripts where they don't work if you do.

**Comment by naasking** [comment]
The directory is called "roslyn". Of course the entire path has spaces, ie. C:\Users\[usrename]\Documents\Visual Studio 2015\Projects\roslyn

**Comment by Pilchie** [comment]
Yes, unfortunately, that doesn't work right now :frowning: 

See #3442.

**Comment by naasking** [comment]
Indeed, moving the whole project to C:\ did solve the problem. That seems a bit extreme though, is it not a simple fix?

**Comment by Pilchie** [comment]
It might be, it just hasn't been a high enough priority issue for us to look at yet.

**Comment by SamB** [comment]
Well, I'm getting that same error on Windows 7 even without any spaces.  I'm most puzzled as to why "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" is installed without "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.1\Microsoft.Windows.UI.Xaml.CSharp.targets" also being installed.

In fact, I've just discovered that I *do* have a "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.CSharp.Targets" installed.

**Comment by SamB** [comment]
And now I actually read the whole first paragraph of <https://github.com/dotnet/roslyn/issues/4387#issuecomment-136537550> ...

**Comment by StanBPublic** [comment]
I have similar situation on Win 7. Installed prerequisites,  msbuild /v:m /m Roslyn.sln completed without errors, when opening project in VS several projects failed to load with the same issue (asking for ..8.1.. while I have ..8.2..)

**Comment by Pilchie** [comment]
@StanBPublic : Can you try installing the VS 2015 Update1 RC?  I believe that the issues requiring the Win8.x and Win10 tools to be installed were all addressed as part of Update 1.

**Comment by StanBPublic** [comment]
@Pilchie VS 2015 Update 1 RC solved this problem, thank you. I still have two errors related to "..Output type 'Console Application' is not supported ...", but this is a separate issue.
