### ISSUE TITLE
Override completion modifies unrelated parts of the file

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#43896]
**Version Used**: 3.7.0-1.20222.2+8bb2fa983f2d5c5f773109a1e7f872078afa98e2

**Steps to Reproduce**:

1. Sync Roslyn to https://github.com/dotnet/roslyn/commit/01db6e01a3344f07549130e16656d6c2def05b73, which is from the function-pointers branch.
2. Open Roslyn.sln.
3. Go to one our derived types of SymbolVisitor, like https://github.com/dotnet/roslyn/blob/features/function-pointers/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.RequiresUnsafeModifierVisitor.cs.
4. Inside the class, do "override VisitFunctionPointerSymbol", and commit the override completion.

**Expected Behavior**: It only spits the override completion for that method.

**Actual Behavior**: It does some unrelated diffs: it's adding usings I didn't expect, and some casts were fully qualified in other parts of the file.

**Comment by jasonmalinowski** [comment]
@genlu @CyrusNajmabadi any chance this is fallout from https://github.com/dotnet/roslyn/pull/43173?

**Comment by CyrusNajmabadi** [comment]
Would love example of the diffs. :)

**Comment by jasonmalinowski** [comment]
Will get them Monday probably; right now I have my VS under a debugger trying to file a second bug... 😦

**Comment by jasonmalinowski** [comment]
If I did this in rc\Workspaces\Core\Portable\Shared\Extensions\ITypeSymbolExtensions.UnavailableTypeParameterRemover.cs the full diff was:

![image](https://user-images.githubusercontent.com/201340/80851878-30233800-8bd9-11ea-8239-8c7cd03f61a6.png)

The using System.Diagnostics.CodeAnalysis is due to the incorrect spit of MaybeNull here but I don't know why using Microsoft.CodeAnalysis is being added -- that's implicitly in scope given our namespace, and the cast shouldn't be added either. The cast is immediately faded as unnecessary.

**Comment by CyrusNajmabadi** [comment]
I'm glad you have a repro!  @genlu  can you take a look?

**Comment by genlu** [comment]
@jasonmalinowski Can't repro on 30509.20.main. It still generates the attribute and adds SystemDiagnostics.CodeAnalysis, but no other random changes.

**Comment by jasonmalinowski** [comment]
Actually this was likely a dupe of the expansion/simplification bug around add usings that @CyrusNajmabadi fixed awhile back, I think?

**Comment by CyrusNajmabadi** [comment]
Yes, very likely.

**Comment by genlu** [comment]
OK, closed then. @CyrusNajmabadi Could you please link this to the other bug if you can find it? Thanks
