### ISSUE TITLE
"nameof" expression in lambda expression causes capture 

### ISSUE THREAD

**Issue by RamType0** [dotnet/roslyn#43907]
![image](https://user-images.githubusercontent.com/39725073/80865042-a3a07480-8cc1-11ea-8b3f-88774f148d4e.png)
![image](https://user-images.githubusercontent.com/39725073/80865062-c29f0680-8cc1-11ea-9d8c-290e4acf2ecc.png)

**Comment by alrz** [comment]
I don't think `DataFlowAnalysis.Captured` API should report locals inside nameof? if so the fix would be straightforward.

**Comment by RamType-0** [comment]
> I don't think `DataFlowAnalysis.Captured` API should report locals inside nameof? if so the fix would be straightforward.

AFIK, "captured" means implicit closure class and instance has been created.
Actually, it seems that `nameof` expression never causes capture , so it is inconsistent,it should not be reported.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/222287192-d3047a4a-f532-4191-87a6-02c7fc190a11.png)

![image](https://user-images.githubusercontent.com/4564579/222287233-b539ab81-1c0c-44bd-b5ce-ff33416ae6ba.png)
