### ISSUE TITLE
AssemblyInfo.cs is not a generated file

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#4390]
The batch fixer for our code fixes is not applying changes to **AssemblyInfo.cs** because it thinks it is a generated file. This a problem for two reasons:

1. The file [is not a generated file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCopTester/Properties/AssemblyInfo.cs). It is a normal file created by most of the project templates in Visual Studio.
2. It should not be the job of the `FixAllProvider` to separate generated files from non-generated files. The `DiagnosticAnalyzer` and/or `CodeFixProvider` should bear the responsibility for suppressing messages in generated files. By placing this code in the `FixAllProvider`, the UI indicates a problem was found and an automatic solution is available, but then fails to apply the automatic solution. See #2753 for more information on this.

**Comment by srivatsn** [comment]
We should fix up 1. We can track issue 2 with #2753.
