### ISSUE TITLE
Find all references on a local function finds nothing

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#43904]
For example, there local functions "checkNullability" and "checkConstraintType" in "CheckConstraints" helper in C# compiler. I made several attempts to find all references for both. Only got result for "checkNullability" once, other attempts produced "Search found no results"

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44467, https://github.com/dotnet/roslyn/pull/44265, https://github.com/dotnet/roslyn/pull/44713
