### ISSUE TITLE
Usings shouldn't be dimmed in Interactive

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#4392]
Using statements are dimmed in Interactive and always referred to as "unnecessary." Unused using statements should never be dimmed in Interactive.

**Comment by amcasey** [comment]
Part of #3785.

**Comment by Pilchie** [comment]
Why not? If nothing in the submission uses the using, it should be faded, and the quick fix to remove should work (for the active submission).

**Comment by kuhlenh** [comment]
They are faded even if you use them. Looks like it's part of a bigger issue now though.

**Comment by amcasey** [comment]
@kuhlenh Can you please verify (i.e. confirm that it works as expected and then add the Verified label)?

**Comment by kuhlenh** [comment]
:+1:
