### ISSUE TITLE
Roslyn incorrectly suggests "Remove unnecessary parentheses" on tuples

### ISSUE THREAD

**Issue by xfoxfu** [dotnet/roslyn#43934]
**Version Used**: master (10 Mar 2020)

**Steps to Reproduce**:

Consider the following code:

```c#
using System;
public class C {
    public void M()
    {
        var T = 1;
        var U = 8;
        var N = 9;
        var x = ((N < T), (U > (5 + 0)));
    }
    
    public void M2()
    {
        var T = 1;
        var U = 8;
        var N = 9;
        var x = (N < T, U > (5 + 0));
    }
}
```

The first `M()` is legal, while the second is not. When writing code like `M()`, the compiler will suggest two parentheses removals, for `(N < T)` and `(U > (5 + 0))`. However, after such removal, the code would be parsed as a generic function instantiation, while `T` and `U` are not types, so it emits a compile error. If either pair of parentheses exists, then the code will compile successfully.

For anybody's convenience, here is a playground link: <https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBhDAbwFgAoDCrTFAFgwFkAKASjMqLfcoDcIEMAKhgC8GAIwBuTlwy9+AVREYAHFPIzZfDADklATjUbN/AB5LGjXQB5BzADQZGigHyOArBgDUGAAzN/hpQAvtIYoehYdPTYLKEk6jJygkqSoexJiqKqaTxauqIGORRJZqKWGDYCDi7uXr4BoSGkQUA===>

**Expected Behavior**:

The compiler should not suggest such parentheses removal because it would break the code.

The parentheses of `((N < T), U > (5 + 0))` and `(N < T, (U > (5 + 0)))` cannot be removed.

**Actual Behavior**:

The compiler suggests two parentheses removal, and when executed, the code breaks.

```
    error CS0118: 'T' is a variable but is used like a type
    error CS0118: 'U' is a variable but is used like a type
    error CS0307: The variable 'N' cannot be used with type arguments
```

**Comment by CyrusNajmabadi** [comment]
Cute :)

Did you run into this in practice?  Or were you trying to craft this specific scenario?  Thanks!

**Comment by xfoxfu** [comment]
@CyrusNajmabadi I found this when experimenting with the possible ambiguity of `(foo<a, b>(bar))`.
