### ISSUE TITLE
Stop reporting “hidden” diagnostics in Interactive

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#4393]
If you create a submission that returns an error, it returns "hidden" errors as well.

**Comment by ManishJayaswal** [comment]
![capture](https://cloud.githubusercontent.com/assets/9527491/9149622/202ff066-3d67-11e5-904f-b0b1f8355a78.JPG)

**Comment by ManishJayaswal** [comment]
This does not repro anymore.
