### ISSUE TITLE
VisualBasicCompilation: Missing reference to netstandard for [Object]

### ISSUE THREAD

**Issue by dedale** [dotnet/roslyn#43933]
**Version Used**: 
.NET Standard 2.0
.NET Core App 3.1
Microsoft.CodeAnalysis.VisualBasic 3.5.0

**Steps to Reproduce**:

Code is available at https://github.com/dedale/dotnet_roslyn_issue
Trying to update a .NET Framework 4.5.2 application to .NET Standard 2.0 + .NET Core App 3.1.
Using VisualBasicCompilation to compile user scripts at runtime.

**Expected Behavior**:

Compilation succeeds.

**Actual Behavior**:

Compilation fails:

> error BC30652: Reference required to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' containing the type '[Object]'. Add one to your project.

I have added a reference to object assembly (which is System.Private.Core.Lib).
Error message is misleading since netstandard does not contain Object type.
Works fine with .NET 4.5.2 + MCA.VB 1.3.2 ✔️
Fails with .NET Standard 2.0 + System.CodeDom 4.6.0 + MCA.VB 1.3.2 ❌
Also fails with MCA.VB 3.5.0 ❌

**Comment by jcouv** [comment]
This does not sound like an issue with the compiler/roslyn, but an issue with the references in the project. I would recommend creating a brand new/empty project, verifying that it has can use the `Object` type, and then looking at the resulting project file for inspiration.
