### ISSUE TITLE
Omitting collection type in object initializer results in NullReferenceException

### ISSUE THREAD

**Issue by markvrc** [dotnet/roslyn#43931]
**Version Used**: C# 8.0

**Steps to Reproduce**:

1. 
```
public class MyClass
{
    public Dictionary<int, int> dictionary {get; set;}
}
```
2.
```
var a = new MyClass()
{     
    dictionary = new Dictionary<int, int>
    { 
        {5, 6},
        {7, 8}
    }
}; 
```
3. Omit `new Dictionary<int, int>`

**Expected Behavior**:
The compiler infers the type and everything works the same with less code
**Actual Behavior**:
Nullreference exception is thrown in the constructor.

This is what C# gets generated (based on IL) when you omit "new Dictionary<int, int>" part:

```
MyClass myClass = new MyClass();
myClass.dictionary.Add(5, 6);
myClass.dictionary.Add(7, 8);
```

Same thing with List<T> and probably other collections too.

**Comment by svick** [comment]
This is the correct behavior, it allows you to add values to a collection property where you don't want to or can't set it (e.g. because it has no accessible setter).

[The spec describes this behavior this way:](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#object-initializers)

> A member initializer that specifies a collection initializer after the equals sign is an initialization of an embedded collection. Instead of assigning a new collection to the target field, property or indexer, the elements given in the initializer are added to the collection referenced by the target.

Even if you disagree that this is desirable, changing it now would be a significant breaking change, so I don't think it's going to happen.

**Comment by markvrc** [comment]
Hello @svick 

The problem is that the compiler generated a known to be broken code. Wouldn't it be better to raise a compilation error instead? I agree that it's useful for adding elements to collection properties in sub classes (because this way elements that were added in parent classes stay in the collection), but if this is not the case, why not raise an error?

**Comment by CyrusNajmabadi** [comment]
> The problem is that the compiler generated a known to be broken code.

It's not known to be broken.  Consider this very simple example:

```
class MyClass
{
    public Dictionary<int, int> Dictionary { get; } = new Dictionary<int, int>();
}

// later ...

var a = new MyClass()
{     
    Dictionary = new Dictionary<int, int>
    { 
        {5, 6},
        {7, 8}
    }
}; 
```

This is entirely legal and will run without exceptions.  This is also a very common pattern in many UI libraries that expose collections of elements that callers can add values to.

**Comment by CyrusNajmabadi** [comment]
Closing out as by design.  The compiler is working properly as per the language specification.  If you'd like the language to change you can file an appropriate proposal over at dotnet/csharplang.  Thanks!
