### ISSUE TITLE
[BUG] Catch isn't entered when throwing NullReferenceException in debug mode

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#43948]
**Version Used**: 
Visual Studio 16.5.4

**Steps to Reproduce**:

1.  Create a new Visual Basic Console Application (.NET Framework 4.7.2)
2. Use the following code:

```vb
Module Module1

    Sub Main()
        Try
            Throw New NullReferenceException()
        Catch ex As Exception
            Console.WriteLine(ex.Message)
        End Try
    End Sub

End Module
```

**Expected Behavior**:
Print `Object reference not set to an instance of an object.`

**Actual Behavior**:
The exception is thrown:

![image](https://user-images.githubusercontent.com/31348972/80960093-77434000-8e08-11ea-8149-6f9dd3fc5657.png)

---

**Notes:**

1. The expected behavior happens when running without debugging.
2. I tried some other exceptions, and the expected behavior happens with them. Not sure what is so special about `NullReferenceException`.

**Comment by Youssef1313** [comment]
i tried on .NET Core and C# and can also reproduce the bug.

**Comment by svick** [comment]
Based on the checkbox in the dialog, I think you have "break when thrown" set for `NullReferenceException`. Do you get the behavior you expect if you uncheck it and then try again?

**Comment by Youssef1313** [comment]
@svick, Thanks!
I unchecked it and got the expected behavior. But shouldn't I **always** get the expected behavior?

**Comment by svick** [comment]
No, that's what the checkbox is for: if you want your code to break as soon as it throws, so that you can easily understand what caused the exception (by inspecting the state of the program at that moment).

**Comment by Youssef1313** [comment]
Okay, Thanks!
