### ISSUE TITLE
NonErrorNamedTypeSymbol.IsValueType reports incorrect value for types loaded via references

### ISSUE THREAD

**Issue by kentcb** [dotnet/roslyn#43945]
**Version Used**: 
3.6.0-3.final

**Steps to Reproduce**:

I have attached a full repro, but here is the unit test:

```C#
[Fact]
public async Task something_stinks()
{
    var workspace = new AdhocWorkspace();
    var projectInfo = ProjectInfo.Create(
        ProjectId.CreateNewId(),
        VersionStamp.Create(),
        "AdhocProject",
        "AdhocProject",
        "C#",
        metadataReferences: new[]
        {
            MetadataReference.CreateFromFile(typeof(Unit).Assembly.Location),
        });
    var project = workspace.AddProject(projectInfo);
    var compilation = await project.GetCompilationAsync();

    var typeFromCompiler = typeof(Unit);
    var typeFromCompilation = compilation
        .References
        .Select(compilation.GetAssemblyOrModuleSymbol)
        .OfType<IAssemblySymbol>()
        .Single()
        .GetTypeByMetadataName("System.Reactive.Unit");

    // This succeeds.
    Assert.True(typeFromCompiler.IsValueType);

    // This fails.
    Assert.True(typeFromCompilation.IsValueType);
}
```

Here I've used `System.Reactive.Unit` because that's the type I was loading when I found this issue. I also tried `System.DateTime` (strangely, that works) and also defining my own value type in a separate project (also does not work).

**Expected Behavior**:
`typeFromCompilation.IsValueType` should be `true`.

**Actual Behavior**:
`typeFromCompilation.IsValueType` is `false`.

[repro_roslyn_value_type_issue.zip](https://github.com/dotnet/roslyn/files/4573426/repro_roslyn_value_type_issue.zip)

**Comment by jcouv** [comment]
Took a quick look. The type that return `IsValueType=false` does so because it could not load properly. If you look at the underlying symbol and expand the non-public members, you will see that it has `HasUseSiteError=true` and the diagnostic in `_lazyUseSiteDiagnostic` is "error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'."

**Comment by kentcb** [comment]
@jcouv Thanks, I can confirm. However, now I'm unsure what the correct solution is here as I don't know of a sensible way to resolve netstandard assemblies. Basically the same problem as https://github.com/dotnet/roslyn/issues/34111.
