### ISSUE TITLE
Optimization proposal: Specify capacity for collection initialization for well-known types

### ISSUE THREAD

**Issue by canton7** [dotnet/roslyn#43944]
**Summary**

```cs
var l = new List<int>() { 1, 2, 3, 4, 5 };
```

Could be compiled to (the equivalent of):

```cs
var l = new List<int>(8) { 1, 2, 3, 4, 5 };
```

**Details**

This is a proposal for an optimization where, if the compiler encounters:

1. The creation of one of a number of whitelisted types (an exact match, excluding derived types), and
2. The type has a collection initializer (or an object initializer which sets `Item`, in the case of a `Dictionary`), and
3. The parameterless constructor is currently called, and
4. The collection initializer has 1 or more elements

then the compiler should call that type's constructor which takes a capacity, passing in a suitable capacity.

This is not a proposal for a generalised way of identifying the capacity constructor for an arbitrary type. This is just about optimising a few common types.

**Targeted types**

From a quick scan through the BCL, the commonly-used types which support a collection initializer and have a capacity constructor I could see are:

 - `List<T>`
 - `Dictionary<TKey, TValue>`
 - `HashSet<T>`

I'm probably missing some.

Of these, I think that `List<T>` and `Dictionary<TKey, TValue>` are probably prime candidates. My impression from a small amount ot BigQuery searching is that most people who use a `HashSet<T>` collection initializer are only adding one or two elements, which `HashSet<T>` takes care of already, without incurring unnecessary allocations.

**What capacity to specify**

I can think of the following options for determing the capacity to pass to the capacity constructor:

1. The number of elements in the collection initializer
2. The number of elements in the collection initializer if this is a power of 2, otherwise the next power of 2 (with a suitable minimum capacity)
3. The next power of 2 above the number of elements in the collection initializer (with a suitable minimum capacity)
4. Something more complex

Option 1 is good if the user won't go on to add more elements to the collection: if they do, then they will be hit with an extra allocation (particularly in the case of `List<T>`). For example, `var l = new List<int>() { 1, 2, 3, 4, 5 }; l.Add(6)` would start off with a backing array of size 5, then immediately bump this up to 10 (this isn't quite so bad for `Dictionary<TKey, TValue>`, as it picks a higher prime anyway). We might also end up allocating at different point: normally a `List<T>` has capacities 4, 8, 16, etc: this might change to e.g. 5, 10, 20, etc. This would make the compiler optimisation visible to the user.

Option 2 has the same end result as when this optimization isn't applied: we just skip some of the intermediate allocations. This makes it less likely to be observable to the user, and therefore potentially more attractive. However it assumes knowledge of the internals of the affected types, which might count against it. 

Option 3 is the same as 2, but assumes that the user will go on to add more elements, and so ensures that there's a least 1 element of spare capacity.

Option 4 would probably require investigation into code in the wild to see what approach would yield the best performance: this is probably overkill.

**Why not change the language?**

An obvious suggestion is to propose a language change which lets the compiler identify the capacity constructor of an arbitrary collection type, e.g. using an attribute. This would (quite rightly) be low priority, and would take a long time to get through, if it gets through at all (I'm not convinced it has enough merit to break even after starting at the obligatory -100 points). It would then only apply to runtimes releases after it is implemented.

------------

I'm happy to submit a PR for this, if you decide it's something that you want: I've got a working prototype.

**Comment by CyrusNajmabadi** [comment]
This seems very risky.  For example, there may be code that currently does not allocate that will now allocate because of this.

I don't see any reason to think the initial set of values given to a collection will be the same as it's necessary capacity.    So this may undershoot on existing code and cause unforeseen allocations.  Worse is that i don't see how someone would opt-out of doing this.  :-/

**Comment by CyrusNajmabadi** [comment]
> then the compiler should call that type's constructor which takes a capacity, passing in a suitable capacity.

Having the compiler call a different constructor than the one that was explicitly called seems very surprising (and the definition of a source-breaking change). i.e. recompiling my code shouldn't change the meaning of it or cause different symbols to be called than the one that was explicitly asked for IMO.

**Comment by canton7** [comment]
> This seems very risky. For example, there may be code that currently does not allocate that will now allocate because of this.

I tried to address this in the "What capacity to specify" section -- one proposal is to mirror the allocation strategy of `List<T>`, but skip the intermediate allocations (so `new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8 }` would go straight for allocating a capacity of 8, and skip the allocation of 4).

> Having the compiler call a different constructor than the one that was explicitly called seems very surprising (and the definition of a source-breaking change). i

That's fair!

**Comment by CyrusNajmabadi** [comment]
Subsumed by the collection-literals work: https://github.com/dotnet/csharplang/issues/5354
