### ISSUE TITLE
Only run analyzers in netcoreapp3.1 build

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#43969]
/cc @jaredpar @sharwell
> One thing that came up is the most expensive analyzer is code style. Now that we're multi-targeting we're essentially paying that cost twice: once per target framework. Why not condition that to only run on one TF instead of both? 
>
> The logic already exists to make this distinction with nullable reference types. Essentially we only enable NRT for a specific TF, not both. We could consider hooking into that for the style based analyzers as well.

**Comment by sharwell** [comment]
I see no issue with this for code style analyzers.

We should keep our correctness analyzers in all the builds though.
