### ISSUE TITLE
Intellisense shows members for all types from all overloads with lambda parameter

### ISSUE THREAD

**Issue by tdaniely** [dotnet/roslyn#43966]
**Version Used**: 

Console app target Core 3.1.

Seen in 16.5.4.
Also verified in 16.6 preview 5.

**Steps to Reproduce**:

Check autocomplete on "a" inside the lambda body in this sample.

```csharp
namespace ConsoleApp36
{
    class Foo { public string first; }
    class Bar { public string second; }

    class Program
    {
        static void fubar(Action<Bar> x) { }
        static void fubar(Action<Foo, Bar> x) { }

        static void Main(string[] args)
        {
            fubar((a, b) =>
            {
                a.
            });
        }
    }
}
```

**Expected Behavior**:

Show only members of Foo.

**Actual Behavior**:

Shows members of Foo & Bar.

Tried several variations of this, seems to be related specifically to the overload.
Originally noticed it in plain Generic Host scenario:

```csharp
namespace ConsoleApp36
{
    class Program
    {
        static void Main(string[] args)
        {
            Host.CreateDefaultBuilder()
                .ConfigureServices((ctx, svc) =>
                {
                    svc.AddHostedService<MyService>();
                    ctx.
                })
                .RunConsoleAsync();
        }
    }
}
```

Also tried multiple overloads and more then 2 parameters in lambda, all same parameter position types are merged.

Also, seems this dev community issue is this issue, and was marked as fixed, but it's not fixed.
https://developercommunity.visualstudio.com/content/problem/893896/intellisense-works-incorrect-with-overloaded-metho.html

**Comment by CyrusNajmabadi** [comment]
We likely can take into account teh explicit lambda param count and the delegate param count to filter things better.

**Comment by dpoeschl** [comment]
Thanks @tdaniely for creating a great repro!

**Comment by fantaclaus** [comment]
Any news on this issue?

**Comment by CyrusNajmabadi** [comment]
@fantaclaus no. That's why the issue is still open :-). If you're interested in contributing a fix we would def appreciate that. Thanks!
