### ISSUE TITLE
#reset noconfig is flipped

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4396]
```#reset``` should re-run the initialization script and ```#reset noconfig``` should not.

**Comment by amcasey** [comment]
Part of #3785.

**Comment by amcasey** [comment]
FYI @ManishJayaswal @kuhlenh

**Comment by kuhlenh** [comment]
Not sure if this is related, but if I ```#reset``` my session and reimport my namespaces, I get errors. BUT if I ```#reset``` and then ```#cls``` (using the UI buttons), it works?

![image](https://cloud.githubusercontent.com/assets/1402694/9141926/36475ed2-3cf1-11e5-9abe-859c2c23072d.png)

And now after resetting and clearing:
![image](https://cloud.githubusercontent.com/assets/1402694/9142001/c3b673f2-3cf1-11e5-8deb-15a23eca859f.png)
