### ISSUE TITLE
Source Generators: Why additive only?

### ISSUE THREAD

**Issue by flipchart** [dotnet/roslyn#43976]
I was really hoping for something along the lines of Rust's macro system so that I could remove some runtime updates I do to `Expression`s (via visitors) and replace it with compile time code. Being able to alter the code at the statement level would make C# _sooo_ much more expressive. It could mean a lot of proposed features could be implemented as generators - like record classes.

**Comment by u7pro** [comment]
supporting code rewrite needs more work on area like c# language, visual studio..

you can get more info on https://github.com/dotnet/csharplang/issues/107

**Comment by CyrusNajmabadi** [comment]
Closing out as question has been answered.
