### ISSUE TITLE
Source generators: feedback on SyntaxFactory

### ISSUE THREAD

**Issue by FiniteReality** [dotnet/roslyn#43979]
I'm not currently actually using source generators, but I'm using the SyntaxFactory for C# in a way that builds up to it; and I have a few personal notes of feedback.

Honestly, I feel the current syntax factory is *far* too complex when it comes to generating code in a purely additive manner. I feel it tries to expose all parts of the syntax tree, which is probably necessary in analyzers as they deal with existing source code, which is nuanced by all the whitespace and trivia of real code.

However, when generating code in a purely additive manner, we often don't care about what whitespace goes where; we just care about the abstract details of the code we're generating. (E.g. "this is a class named x with y members", "this is a method x with attributes y, type parameters z, parameters w and body k" and so on.)

As such, I feel a new syntax factory designed specifically for additive source code generation would be a great addition when working with syntax generators, so we remain working with the real Roslyn syntax trees, but have to worry less about whether we passed the correct EndOfDocumentationComment syntax/trivia for example.

**Comment by CyrusNajmabadi** [comment]
> However, when generating code in a purely additive manner, we often don't care about what whitespace goes where;

You shouldn't need to touch whitespace when using SyntaxFactory.  Just use the normal methods, and then call .NormalizeWhitespace at the end to get a parseable tree.

**Comment by chsienki** [comment]
Yep, this is something we're actively looking at. Our main concern is not re-inventing the wheel, and ending up with two parallel ways of creating syntax that must be supported for ever going forward.

**Comment by CyrusNajmabadi** [comment]
> E.g. "this is a class named x with y members"

This should be possible like so:

```
using static SyntaxFactory;
//...

var class = ClassDeclaration("x").AddMembers(
    CreateMember1(),
    CreateMember2()).NormalizeWhitespcae();
```

**Comment by FiniteReality** [comment]
> > However, when generating code in a purely additive manner, we often don't care about what whitespace goes where;
> 
> You shouldn't need to touch whitespace when using SyntaxFactory. Just use the normal methods, and then call .NormalizeWhitespace at the end to get a parseable tree.

This wasn't really the case for me, but I was generating XML comments too, so it's possible they just weren't following the normal "rules" for whitespace.

**Comment by CyrusNajmabadi** [comment]
For an xml comment, just literally make a comment trivia with your text in it.  i.e. just do this:

```
using static SyntaxFactory;
// ...

var myClass = myClass.WithLeadingTrivia(Comment(
@"///<summary>
///</summary>
"));
```

**Comment by chsienki** [comment]
Related to #43821

**Comment by kzu** [comment]
For formatting, I have found the following to be sufficient:

```
var formatted = Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseCompilationUnit(output)
     .NormalizeWhitespace()
     .GetText()
     .ToString();
```

(when generating an entire class)

**Comment by CyrusNajmabadi** [comment]
Closing out.
