### ISSUE TITLE
Pattern Matching in While Loop

### ISSUE THREAD

**Issue by ChayimFriedman2** [dotnet/roslyn#43984]
**Version Used**: 8

**Steps to Reproduce**:
Type the following code and try to compile:

```c#
object o = 8;
while (!(o is int i)) { }
Console.WriteLine(i);
```

**Expected Behavior**: The code will emit a loop that run until `o` is `int`, then converts it to `int` as variable `i`. Just like pattern matching with `if`:

```c#
object o = 8;
if (!(o is int i)) { }
Console.WriteLine(i);
```

**Actual Behavior**: The code isn't compiled and strangely the scope of `i` is inside the loop, instead of outside it.

**Comment by HaloFour** [comment]
This behavior is intentional:  https://github.com/dotnet/roslyn/issues/15529
