### ISSUE TITLE
System.Reflection.Metadata dependency is 'PreRelease'

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#4398]
Our current System.Reflect.Metadata dependency is considered 'PreRelease'. This will need to be updated to a 'Release' version before v1.1 can be released.

Once this issue has been resolved, Setup.proj needs to have Release packaging re-enabled.

**Comment by amcasey** [comment]
Status?

**Comment by tmat** [comment]
In progess.

**Comment by tmat** [comment]
/cc @nguerrera 
So for RC we will still be pre-release 1.1.0.0-beta.
For RTM we change that to 1.1 release.
Is that correct Nick?

**Comment by nguerrera** [comment]
Yes, tonight's will be 1.1.0-beta-NNNNN followed by 1.1.0. The beta build can be considered a release candidate as the API surface has been reviewed and is locked unless something very compelling were to happen during RC.
