### ISSUE TITLE
MAS: COM interface methods should appear in metadata order

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4400]
Seems like MAS is sorting them by name, which is confusing since the metadata order very much matters.

**Comment by Pilchie** [comment]
Yep, this has come up before, but it's been this way since VS2005.

**Comment by tmat** [comment]
@Pilchie And we can't change that because ...?

**Comment by Pilchie** [comment]
We could change it, but we also heard a bunch of people complain when it *was* sorted in Metadata order (original impl in VS2005).  It's one of those cases where either way, a significant number of people are unhappy, so there is no real reason to change.

**Comment by tmat** [comment]
Were all methods sorted in metadata order or just COM interfaces? I understand people wanting non-COM methods sorted alphabetically, I prefer that as well. But changing the order in COM interfaces changes the semantics.
