### ISSUE TITLE
GetOperation(...) returns null for parenthesized expression as argument

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#44008]
If I call `GetOperation(…)` on the argument of an invocation such as  `f(1)`, the result is, as expected, an `IArgumentOperation`; but if the invocation has a parenthesized expression as the argument, i.e., `f((1))`, then `GetOperation(…)` returns null.

I'd think that those 2 constructs are semantically equivalent. Is this a bug?

**Comment by alrz** [comment]
I hit this earlier. Very surprising behaviour besides the fact that we also have IParenthesizedOperation (why?)

**Comment by RikkiGibson** [comment]
Tagging @333fred

**Comment by 333fred** [comment]
This is intended behavior. IParenthesizedOperation is only used for VB parenthesized expressions. For IOperation, the rule is generally that not every SyntaxNode has semantic meaning, and nodes that don't have semantic meaning don't have IOperation representations. Parenthesized expressions are one such node that doesn't have semantic meaning.

**Comment by alrz** [comment]
>IParenthesizedOperation is only used for VB parenthesized expressions.

care to expand on this a little? Does VB parentheses entail semantic meaning?

**Comment by AlekseyTs** [comment]
> Does VB parentheses entail semantic meaning?

Yes it does. It converts an LValue to an RValue. For example, if corresponding parameter is a ```ByRef``` parameter, the parenthesized argument is passed by value.

**Comment by ltcmelo** [comment]
@333fred 

> Parenthesized expressions are one such node that doesn't have semantic meaning.

Why is that? This doesn't seem intuitive, e.g., the semantics of `(42)` is really the same of `42`. Or can you tell me any context in C# where this doesn't hold true?

**Comment by 333fred** [comment]
> Or can you tell me any context in C# where this doesn't hold true?

I cannot. And _that_ is the point: parentheses do not contribute any semantic meaning. You can put them around any expression and the result is exactly the same. The meaning comes from the underlying syntax, not from the parentheses.

**Comment by AlekseyTs** [comment]
> Why is that?

These are VB language rules. A quote from the specification:
"11.4.2 Parenthesized Expressions
A parenthesized expression consists of an expression enclosed in parentheses. **A parenthesized expression is classified as a value**, and the enclosed expression must be classified as a value. A parenthesized expression evaluates to the value of the expression within the parentheses. 
"

>  Or can you tell me any context in C# where this doesn't hold true?

I don't think this is relevant in context of this issue. Languages are different. VB is not C#.

**Comment by ltcmelo** [comment]
@AlekseyTs
I'm talking specifically about C#, not VB.

@333fred
Exactly because of your sentence _... result is exactly the same. The meaning comes from the underlying syntax, not from the parentheses..._, I believe that I should get the same `IOperation` for both with/without the parenthesis.

@CyrusNajmabadi , what's your opinion on this?

**Comment by mavasani** [comment]
@ltcmelo I think what you want is probably https://github.com/dotnet/roslyn/issues/30116
