### ISSUE TITLE
Rename class into var

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44011]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1008967/rename-class-into-var.html)._

---
It is possible to refactor-rename a class into 'var'.
For example you can refactor-rename a class named 'MyClass' into 'var'.

Then you can even refactor-rename 'var' into something else, for example 'MyClass'.

Visual Studio will do this reliably on your complete solution! :)

You might imagine the amount of trouble this will cause!

Please prevent renaming anything from or to 'var'.

---
#### Visual Studio Feedback System on 4/28/2020, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is what we do already:

![image](https://user-images.githubusercontent.com/4564579/81211328-09be1d80-8f88-11ea-9272-60349417cffd.png)
