### ISSUE TITLE
Add API to AddAdditionFile to project from project system

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn#4402]
In DNX project system we need to add project.json file as AdditionalFile to roslyn's Project, however we can not do it since IAnalyzerHost is internal and there no clear way to get its instance if it would be public. We tried with HeeJae to load it via COM from IVsHierarchy site, but unsuccessfully. 

We tried to use reflection and call AddAdditionalFile, it worked, however we can not take it as permanent solution.

Ideally we would like to have an easier way than com, which unblocks this scenario.

**Comment by jasonmalinowski** [comment]
How are you creating projects right now? `IVsIntellisenseProject`?

**Comment by abpiskunov** [comment]
Yes, we create an  IVsIntellisenseProject  per each target framework that Dnx project has.

**Comment by Pilchie** [comment]
DNX project system isn't a thing anymore.
