### ISSUE TITLE
Code Cleanup Fixer - 'Using' placement normalization

### ISSUE THREAD

**Issue by killergege** [dotnet/roslyn#44044]
Add a Code Cleanup fixer to apply `csharp_using_directive_placement` from the editor config file or the 'using' preferences of VS code style configuration.

Right now this rule seem to be applied when VS adds a new using, but it doesn't update the existing ones.
Which means that people with different configuration will generate inconsistent using placements.

A fixer would allow to force that.

**Comment by jmarolf** [comment]
Traditionally usings were not messed with and the editorconfig file was consulted when trying to determine where to place new usings. 

This seems like something work discussing

**Comment by sharwell** [comment]
We would accept a pull request to add "Update using placement" to the list of available fixers in the Code Cleanup feature. The specific name that appears in the available fixers list could be reviewed as part of that pull request, but wouldn't otherwise impact the functionality.

**Comment by weitzhandler** [comment]
#44114
