### ISSUE TITLE
Todo comments are not removed from task list when file is deleted

### ISSUE THREAD

**Issue by uniqueiniquity** [dotnet/roslyn#44062]
**Version Used**: 
3.7.0-1.20230.1
**Steps to Reproduce**:

1.  Add Class.cs to project, include `//TODO: hello`
2. Observe the comment is added to the VS task list
3. Delete Class.cs

**Expected Behavior**:
The comment is removed from the task list.
**Actual Behavior**:
The comment remains in the task list.

It appears that `VisualStudioTodoCommentsService.OnDocumentRemovedAsync` doesn't actually do what it's supposed to?

cc: @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Taking a look.
