### ISSUE TITLE
Source Generators: how to unit test?

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#44075]
I'm trying to quickly iterate on my generator by simply running it from a unit test and inspecting the output.

I was hoping I could just construct a `SourceGeneratorContext` with some fake compilation, additional files and so on, run it, and then inspect what it added to it.

But that's not feasible given its [internal constructor](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/SourceGeneration/SourceGeneratorContext.cs#L25). 

For now, I just added to my generator a method I call from tests instead:

```
internal IDictionary<string, SourceText> Execute(Compilation compilation, IEnumerable<AdditionalText> additionalFiles)
```

**Comment by ufcpp** [comment]
GeneratorDriver

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs#L61

**Comment by jcouv** [comment]
FYI @cartermp @chsienki

**Comment by chsienki** [comment]
Yes, as of today, you can use GeneratorDriver in unit tests. There are some examples in our own tests here: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests/SourceGeneration/GeneratorDriverTests.cs,114

This is an area we're actively working on, and expect to ship templates / shims etc to make it easier to work with in the future

**Comment by chsienki** [comment]
I've added a gist that shows the basics of setting up unit test for generators here: https://gist.github.com/chsienki/2955ed9336d7eb22bcb246840bfeb05c

**Comment by ufcpp** [comment]
A bit offtopic: I tried creating a generator and it works correctly in [VS 16.7 preview 2] but doesn't with `Microsoft.CodeAnalysis.CSharp` v3.7.0-1.final (latest version on nuget.org) because the Extending partial method feature is not supported in M.C.C 3.7.0 yet.

**Comment by davidwengier** [comment]
Any thoughts on allowing access to the added sources from `GeneratorDriver`? I think for some tests it will be nice to validate against the generated code, rather than the resulting final compilation.

If there is a way to do it, I couldn't see an obvious one.

**Comment by RussKie** [comment]
FWIW @davidwengier added a SG to Windows Forms and unit tests for it in https://github.com/dotnet/winforms/pull/4043

**Comment by chsienki** [comment]
Added Unit test instructions to the cookbook at https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#unit-testing-of-generators
