### ISSUE TITLE
[Feature Request] Auto Implemented Interface

### ISSUE THREAD

**Issue by NaxAlpha** [dotnet/roslyn#4407]
Hi,
Sometimes we need interface like IDisposable which when implemented (in VB) inserts some implementation of it self. so sometimes we need interface which has similar implementation for all classes in which it is implemented and also we know that there can only be one inheritance but multiple implementation.
<This will only be applicable to current assembly>
let We have an interface
![image](https://cloud.githubusercontent.com/assets/11090613/9132583/010e35c0-3d0e-11e5-8bcc-c8eae1b288ad.png)
Now we provide its implementation in separate class
![image](https://cloud.githubusercontent.com/assets/11090613/9132603/29bb1ede-3d0e-11e5-9fa2-5752b9108559.png)
When i implement in a class it should do this
![image](https://cloud.githubusercontent.com/assets/11090613/9132636/6503b276-3d0e-11e5-83e9-b1ad721d53e1.png)
I think it should be part of IntelliSense

**Comment by Pilchie** [comment]
Thanks for the suggestion - we'll keep it in mind as we're planning on what features to add next.

**Comment by CyrusNajmabadi** [comment]
This sounds like it would be covered by [DefaultInterfaceMethods](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/default-interface-methods.md)

I don't think this really qualifies as an IDE feature.  Tagging @jasonmalinowski for thoughts here.  My preference is to close this out.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I agree with closing this one out -- Default Interface Methods probably addresses some of the need. If it's a situation where you want the implementation to be a template but still has to get modified, I'm not sure addressing that in the IDE is really the best approach anyways...
