### ISSUE TITLE
Process terminated. InvalidCastException: Unable to cast object of type 'LocalWithInitializer' to type 'SynthesizedLocal'.

### ISSUE THREAD

**Issue by ericwj** [dotnet/roslyn#44074]
**Version Used**: 
C:\Program Files\dotnet\sdk\3.1.300-preview-015135
VS Preview: Version 16.6.0 Preview 6.0 and 5.0
C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66

**Steps to Reproduce**:

I could not reproduce in a small code file.  There is exactly one line with which I can trigger this error at will. There is a detailed stack trace and a descriptive error. The full error is:
* Process terminated. System.InvalidCastException: Unable to cast object of type 'LocalWithInitializer' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedLocal'.

```
public struct S {
    ...
    public IEnumerable<string> GetStrings() {
        ... (some nested switch statements)
        // this is the offending line:
        ref readonly var r= ref GetR(in this);
    }
    // Implementation of GetR; both R and P are structs wrapping a byte
    private ref readonly R GetR(in S @this) => ref Unsafe.As<P, R>(ref @this.P);
}
```

One oddity is that I had the offending line in several switch statements although the resulting variable `r` was not used.

**Expected Behavior**:
The code compiles.

**Actual Behavior**:
The process crashes.

Visual Studio shows in the Build Output:
```
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.exe" exited with code -2146232797.
```
I am lead to believe -2146232797 (0x80131623) is COR_E_FAILFAST due to #5348.

[CscCrashStackTrace.txt](https://github.com/dotnet/roslyn/files/4596942/CscCrashStackTrace.txt)

**Comment by RikkiGibson** [comment]
Is `GetStrings` an iterator method? If that's the case, it's not allowed to use a ref local and the bug is that we are failing to give an error on the declaration of `ref readonly var r`.

**Comment by ericwj** [comment]
Aww yes it is. Well that turned out this way to be an expensive mistake to diagnose.

**Comment by RikkiGibson** [comment]
This sample seems to reproduce the root problem (not diagnosing a 'ref var' inside an iterator):

```cs
using System.Collections.Generic;

public class C {
    public IEnumerable<int> M() {
        yield return 1;
        
        switch (this)
        {
            default:
                ref var x = ref Prop;
                break;
        }
    }
    
    ref int Prop => throw null!;
}
```

**Comment by RikkiGibson** [comment]
This sample reproduces the crash described in the original issue, since we have to keep 'x' alive across a 'yield' boundary.

```cs
using System.Collections.Generic;

public class C {
    public IEnumerable<int> M() {
        switch(this)
        {
            case null:
                ref var x = ref (new int[1])[0];
                yield return 1;
                yield return M1(ref x);
                break;
        }
    }
    
    int M1(ref int x)
    {
        return x;
    }
}
```

**Comment by RikkiGibson** [comment]
Thanks for reporting @ericwj!

**Comment by ericwj** [comment]
Welcome! 

Beware though that the second repro (May 13) isn't what my code looked like; it was like the first. I think my difficulty making a repro was because in the first repro the crash doesn't *always* happen, though it did **always** happen in the larger original project where I came accross this.
