### ISSUE TITLE
Tools - options pages fail to load

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#44085]
master, 30108.40

Advanced, code style, and intellisense pages all fail to load.  The others appear to load.
![tools_options](https://user-images.githubusercontent.com/5749229/81439802-cc8e9280-9123-11ea-8f55-633f3c2521ff.png)

**Comment by mavasani** [comment]
Exception is coming from the shell:

```

System.NotImplementedException: 'Class not registered

>	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.GetPropertyPage(ref System.Guid rguidPage, Microsoft.VisualStudio.Shell.Interop.VSPROPSHEETPAGE[] ppage)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(string verb, object pvaIn, out object pvaOut)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(object parameter)	Unknown
 	PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)	Unknown

```

All the 6 pages highlighted below are broken:

![image](https://user-images.githubusercontent.com/10605811/81447712-0070b480-9132-11ea-9c2d-72a1d6d769ba.png)

**Comment by mavasani** [comment]
NOTE: I tried clean install of latest 16.7 P2 build and got the same issue. We should contact platform team...

**Comment by dibarbet** [comment]
@mavasani @jinujoseph 
Thanks for looking - filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1120903
