### ISSUE TITLE
Consider streamlining flag encoding for native integers 

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44086]
Looking at `NativeIntegerTransformsEncoder`, native int encoding doesn't encode a flag for modreq types, but it does encode a flag for types that are not `IntPtr`. 
This seems a strange middle-ground between the tuple approach (only encode a flag for types that are relevant, ie. ValueTuple) and the dynamic approach (encode a flag for all types, including modreqs).

Tagging @cston @gafter 

Relates to https://github.com/dotnet/roslyn/issues/38821 (test plan for native ints)

**Comment by cston** [comment]
From offline discussion:

The proposal is to encode a `bool` value for each `System.IntPtr` and `System.UIntPtr` only in the type ref, and ignore custom modifiers.

As before, a `NativeIntegerAttribute` is only emitted if the `bool` array contains at least one `true` value, and the parameterless attribute constructor is used if the array has a single value `true`.

```C#
nuint A;                 // [NativeInteger] System.UIntPtr A
(nint, nint) B;          // [NativeInteger] System.ValueTuple<System.IntPtr, System.IntPtr> B
(System.IntPtr, nint) C; // [NativeInteger(new[] { false, true })] System.ValueTuple<System.IntPtr, System.IntPtr> C
```
