### ISSUE TITLE
Incorrect refactor of invoking as extension method on a lambda

### ISSUE THREAD

**Issue by miniBill** [dotnet/roslyn#4409]
Intellisense is incorrectly refactoring to invoke a method using the extension method syntax on a lambda.

MWE follows:

	static class Extensions
	{
		public static void Funny (this Action input)
		{
		}
	}

	static class Other
	{
		static void Broken ()
		{
			Extensions.Funny (() => { });
		}
	}

**Comment by Pilchie** [comment]
Hi,  I'm not quite sure what scenario you mean that IntelliSense is refactoring this for you?  I assume that is the starting code, what is it that you are doing that is causing the wrong thing to happen?

**Comment by Pilchie** [comment]
Unfortunately, I haven't been able to figure out what's going wrong here.
