### ISSUE TITLE
`#line` directive causes odd debugger behavior

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#44123]
**Version Used**: 16.6.5

![image](https://user-images.githubusercontent.com/2371880/81511519-d6a0c480-92ce-11ea-8b25-45624ce0e6ca.png)

See how the instruction pointer is on the class line, not in the body of the main method. /cc @tmat

**Comment by tmat** [comment]
`#line` declares that line 3 is actually line 1. So the sequence point on line 10 is emitted with line number 7. That's where you see it.

**Comment by jcouv** [comment]
Closing as by-design based on answer from Tomas
