### ISSUE TITLE
Snippets: Redundant new line before $end$ at beginning of the line

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#44121]
**Version Used**: 
> Microsoft Visual Studio Community 2019 Preview
> Version 16.6.0 Preview 6.0

**Steps to Reproduce**:

1. Use a snippet with `$end` at beginning of the line, for example, standard `iterator` snippet:
```xml
      <Code Language="CSharp">
        <![CDATA[public $SystemCollectionsGenericIEnumeratorG$<$type$> GetEnumerator() {
  $end$throw new $Exception$();
  yield return default($type$);
}]]>
      </Code>
```
2. Apply a snippet:
```cs
class Class
{
  iterator| // <-- Cursor, Press Tab
}
```
**Expected Behavior**:
Next code shuld be inserted by a snippet:
![image](https://user-images.githubusercontent.com/795200/81508221-97449900-930b-11ea-9125-9960b2bf1983.png)
**Actual Behavior**:
![image](https://user-images.githubusercontent.com/795200/81508189-68c6be00-930b-11ea-8b18-67b77a6e8071.png)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not changing legacy snippets.
