### ISSUE TITLE
Snippets: Filter available snippets by Kind

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#44122]
**Version Used**: 
>Microsoft Visual Studio Community 2019 Preview
>Version 16.6.0 Preview 6.0

**Steps to Reproduce**:

1. Create or use a code snippet with `Kind` attribute defined:
```xml
      <Code Language="CSharp" Kind="method body">
        <![CDATA[if(!$Debugger$.IsAttached) {
  $Debugger$.Launch();
}//if

$end$]]>
```
2. Inside a class declaration start typing a snippet shortcut.

**Expected Behavior**:
Snippet should be available only inside a `method body`, as specified in .snippet file and described in [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019#code-element):

> **Kind** - _Optional_ attribute that specifies the kind of code that the snippet contains. The value can be one of the following:

Value | Description
-- |--
`method body` | Specifies that the code snippet is a method body, and therefore, must be inserted inside a method declaration.
`method decl` | Specifies that the code snippet is a method, and therefore, must be inserted inside a class or module.
`type decl` | Specifies that the code snippet is a type, and therefore, must be inserted inside a class, module, or namespace.
`file` | Specifies that the snippet is a full code file. These code snippets can be inserted alone into a code file, or inside a namespace.
`any` | Specifies that the snippet can be inserted anywhere. This tag is used for code snippets that are context-independent, such as comments.

**Actual Behavior**:
Code snippet available on a "type level":
![image](https://user-images.githubusercontent.com/795200/81508362-5ac56d00-930c-11ea-846d-8fd69b1acd0d.png)

**Comment by jmarolf** [comment]
As per the [docs](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019#attributes) these are the defined values for `Kind` and their meaining.

- `method body`: Specifies that the code snippet is a method body, and therefore, must be inserted inside a method declaration.
- `method decl`: Specifies that the code snippet is a method, and therefore, must be inserted inside a class or module.
- `type decl`: Specifies that the code snippet is a type, and therefore, must be inserted inside a class, module, or namespace.
- `file`: Specifies that the snippet is a full code file. These code snippets can be inserted alone into a code file, or inside a namespace.
- `any`: Specifies that the snippet can be inserted anywhere. This tag is used for code snippets that are context-independent, such as comments.

I think at a minimum we would want to ensure that the snippets service respects these options.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippet experiences.
