### ISSUE TITLE
Enforce formatting of compiler generated code

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44130]
#43998 updates the formatting of generated code to match the form produced by the formatter. We should run **dotnet-format** during the correctness leg to enforce that these files remain formatted if/when changes are made in the future.

Blocked on https://github.com/dotnet/format/issues/670

**Comment by Youssef1313** [comment]
@sharwell This shouldn't be blocked any more. https://github.com/dotnet/format/pull/673

**Comment by sharwell** [comment]
I think this was already implemented in f309d21ac8a6fdfc16838bac77a13cb3b05efea9
