### ISSUE TITLE
Rename/refactor of using alias directive is not applied to references in file, but wait, there's more...

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44135]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1020109/renamerefactor-of-using-alias-directive-is-not-app.html)._

---
This will probably get closed because I'm at a loss for how to find any real detail on this issue.

Behavior is as follows:

A using alias directive exists in the C# file (eg, using MyAlias = Foo.Bar.Baz).
I use the Visual Studio refactor functionality by changing "MyAlias" to "MyRenamedAlias" and type CTL - . - ENTER to apply the rename.
At this point Visual Studio reverts "MyRenamedAlias" to "MyAlias" and no other changes are applied to the file.

Curious.... I try it another way:

I put the cursor in "MyAlias" and type CTL-R-CTL-R to open the refactor dialog.
At this point I notice that Visual Studio doesn't think there are any references to this using alias directive (not true).

So I have a couple of questions:

1. What could be causing VS to believe there are no references? If I add another using alias directive in the same file and reference it, then that one is found perfectly fine, as expected.
2. If VS doesn't find references to an element during a refactor, is it expected that when refactor is applied it reverts your code change?
a. If so, why would this be the expected behavior?
b. If not, what could be going on?

The most frustrating aspect of this is there are no errors, warnings, messages coming up about this so I have no way to dig into what is happening. Might there be some special logging faculties that could be set up to capture these actions?

---
#### Visual Studio Feedback System on 5/6/2020, 09:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
@ryzngard Can you try and followup on this.
Sam mentioned that he was not able to repro this.

**Comment by sharwell** [comment]
I tried to reproduce this using both the lightbulb and <kbd>F2</kbd>, and both renamed the directive and the references to it.

**Comment by CyrusNajmabadi** [comment]
I'm not able to repro either.  Closing out.
