### ISSUE TITLE
Advanced members not showing in completion lists

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44134]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1013568/no-se-muestra-la-propiedad-autogeneratecolumns-en.html)._

---
Cuando escribo código, y se me sugieren propiedades de un DataGridView no aparece AutoGenerateColumns

---
#### Visual Studio Feedback System on 5/4/2020, 01:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Lydia Shi [MSFT] on 5/5/2020, 11:44 PM: 

<p>Hi maria,</p>
<p>Thanks for your feebback. Unfortunately, we can’t reproduce your problem on our side. We created a .Net Framework WInForm project and got below results:</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/133011-autogeneratecolumns.gif"></p>
<p>So do we get the right point of your issue? if not, can you provide more detail information about this issue?</p>
<p>Thanks,<br>
Lydia</p>

#### maria.garbero on 5/5/2020, 11:48 PM: 

(private comment, text removed)
#### Visual Studio Feedback System on 5/7/2020, 11:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The `AutoGenerateColumns` properties is marked as an "advanced" item for IntelliSense. I was not able to find the option to enable these members in completion.

**Comment by genlu** [comment]
Looks like you can't hide advanced members in VB

![image](https://user-images.githubusercontent.com/788783/96918738-9ccc1080-145f-11eb-8dcf-aaa94590b21a.png)

**Comment by genlu** [comment]
@Cosifne Do you want to take a look at this?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
