### ISSUE TITLE
wrong number of references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44138]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1024025/wrong-number-of-references.html)._

---
VS says there are 3 references to a class.  Clicking on the references shows a list containing just 1 reference.  The only refeence is a cshtml file.  Deleting the cshtml file correctly updates the number of references to 0.  Somehow VS is counting references from a cshtml file multiple times.

---
#### Visual Studio Feedback System on 5/8/2020, 08:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm not able to repro this.
