### ISSUE TITLE
Bad link in error message

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44139]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1024910/bad-link-in-error-message.html)._

---
I got a message saying "Visual Studio has suspended some advanced features to improve performance", and next to it there was a "Learn more" link. When I click on it, it takes me to https://docs.microsoft.com/en-us/visualstudio/code-quality/automatic-feature-suspension?view=vs-2015&redirectedfrom=MSDN - note that I'm using the latest version of Visual Studio 2019, but the link says "This article applies to Visual Studio 2015" (note it says 2015 in the url). Please fix the URL.

---
#### Visual Studio Feedback System on 5/11/2020, 01:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
We just need to replace the following link: https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/VisualStudio/Core/Def/Implementation/VirtualMemoryNotificationListener.cs#L38
with new link "https://docs.microsoft.com/visualstudio/code-quality/automatic-feature-suspension"

**Comment by jasonmalinowski** [comment]
Reactivating this bug: we shouldn't have lost the go.microsoft.com link -- usual policy is the code we ship only contains the redirector links so if we have to move the docs we don't break shipped products. Can't we just fix the server side configuration here and revert the change?
