### ISSUE TITLE
Add Classification API which mirrors the proposed LSP Semantic Tokens API

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#44155]
**LSP API**
Possibly the best view of the proposed LSP API is from the vscode languageserver - https://github.com/microsoft/vscode-languageserver-node/blob/aa6592ee4b4e0276a2e7c8974e19dcdf7b0a61f9/protocol/src/protocol.semanticTokens.proposed.ts

The LSP API supports returning token type (classification) for a span of text along with any number of token modifiers (static, declaration, read-only, etc...) which give additional context for the token.

**Proposal**
To better support this scenario, I propose that we enhance our existing classification API to [support compound classifications](https://github.com/dotnet/roslyn/issues/32770). Each classified span would have a single classification and then an array of modifiers that would provide extra context. The existing classification API could simply filter the modifiers from these spans to maintain the current behavior.

**Comment by CyrusNajmabadi** [comment]
Closing out as not needed.
