### ISSUE TITLE
Remove SafeContinueWith helpers

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#44150]
@jasonmalinowski 
> It was originally added to add an implementation of LazyCancellation before the TPL supported that, and also to have a place to catch failing exceptions, I think especially before the framework changed the behavior where a faulted task that wasn't observed it'd fail at finalization, and that wasn't useful either.
Neither world really exists today...

**Comment by sharwell** [comment]
The remaining item to decide on here is uniform exception handling for the code base. Once we make a decision on that, we can implement analyzers to enforce correct asynchronous exception handling and remove these helpers.

**Comment by sharwell** [comment]
Blocked on #29273
