### ISSUE TITLE
Avoid boxing in string interpolation/formatting

### ISSUE THREAD

**Issue by benaadams** [dotnet/roslyn#44168]
#35006 changed roslyn to "Avoid boxing in string concatenation", by adding `.ToString()` to ValueTypes and `?.ToString()` to reference types; so the `string` based rather than `object` based `string.Concat` methods are called.

This should also be done for string interpolation and string formatting.

This came up as follow up issue in https://github.com/dotnet/roslyn/issues/43711 which is a refactoring suggested both by Rosyln analysers (and also R#) to remove `.ToString()` from parameters in interpolated strings.

This produces nicer code to view; however worse performing code that boxes ValueTypes. 

It would be preferable if Roslyn added the `.ToString` during compile, so we get the best of both worlds.

**Comment by canton7** [comment]
Related: #194, #4678, #6669, #6738, #9212.

**Comment by 333fred** [comment]
Interpolated strings in .NET 6 should avoid boxing in most cases, with the only exceptions being when an await expression is used inside an interpolation hole or use in an expression tree.
