### ISSUE TITLE
Analyzer/fixer for unnecessary pragma suppressions for compiler diagnostics

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44177]
Extracted out from https://github.com/dotnet/roslyn/issues/41574#issuecomment-620094604. See the second bullet point about **[Compiler diagnostics]**.

**Comment by jnm2** [comment]
Should this issue cover non-pragma suppressions too (`!`)?

**Comment by mavasani** [comment]
@jnm2 That is tracked with #25372 (compiler) and #34714 (IDE)
