### ISSUE TITLE
Code fix for CS1615 (Remove 'in' keyword)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44187]
**Version Used**: 16.6 Preview 5

**Steps to Reproduce**:

```csharp
void M(int value) => throw null;

void N(int value)
{
  M(in value); // CS1615: Argument 1 may not be passed with the 'in' keyword
}
```

**Expected Behavior**:

A code fix is provided that offers to remove the `in` keyword.

🔗 Related to #23326

**Comment by eugenesmlv** [comment]
I'm working on this one and I'll create a pull request in a couple of days.

**Comment by mikadumont** [comment]
Hey @eugenesmlv, Thanks for contributing! Can I include your name as a contributor for this feature in the Microsoft release notes?

**Comment by eugenesmlv** [comment]
@mikadumont, sure, that would be nice!
