### ISSUE TITLE
Duplicate using directives in Metadata as source

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#44200]
To reproduce:

- Create a new net5.0 console app
- Open the project in VS
- Once the project is loaded "go to definition" on `string` (not using decompilation)

![image](https://user-images.githubusercontent.com/611219/81755315-4c429700-946d-11ea-9558-905b16a46364.png)

**Comment by RussKie** [comment]
For completeness, the same is happening in VS Code (official and preview).

**Comment by CyrusNajmabadi** [comment]
@genlu iirc didn't you change something to change when simplification vs add-import ran?  Could this have caused that?

**Comment by CyrusNajmabadi** [comment]
I'll take a look.

**Comment by genlu** [comment]
The change I made shouldn't cause multiple identical usings being added
