### ISSUE TITLE
Pasting text with quotes into a verbatim string literal should double the quotes

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#44203]
It would be nice if when pasting text from clipboard inside a verbatim string literal, and the text contained quotes, each quote would be escaped to double quote, so as not to break the string literal.

Very useful for pasting multiline text with quotes.

**Comment by CyrusNajmabadi** [comment]
i played around with this but had issues with it.  for example, copy/pasting from a string ends up duplicating when i don't want it.  Maybe that's ok though if undo/esc can get you back to where you would normally be.

**Comment by KirillOsenkov** [comment]
Maybe it should leave alone the ones that are already doubled?

And yes, I’d much rather press Undo once than go and fix each and every one of them when they break the string.

**Comment by CyrusNajmabadi** [comment]
This should work now.
