### ISSUE TITLE
"Insert space between method name and its opening parenthesis" option is not obeyed with generic and operator methods.

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn#4421]
When the "Insert space between method name and its opening parenthesis" option is enabled for the C# text editor, methods with generic parameters and operators are not formatted properly. 
Repro Steps:Enable the "Insert space between method name and its opening parenthesis" option within the C# text editor formatting options. 
Create a source file with the following type defined: 
public class SomeClass 
{ 
public void Generic<T> ( T value ) { } 
public static int operator + ( SomeClass lhs, SomeClass rhs ) { return 0; } 
} 
Request that the document be formatted. Note that there is no space between "+" and "(" or ">" and "(" within the two methods. Non-generic and non-operator methods are formatted properly. 
Impact:Mostly an annoyance, but can also affect source control system if the document is unintentionally reformatted.

**Comment by mattscheffer** [comment]
I'm still seeing this occur with '\<T\>'. The parens and plus marks are correctly spaced however triangle  brackets don't have the extra spacing.

![image](https://cloud.githubusercontent.com/assets/10537189/12526963/b6b9530c-c128-11e5-83d2-cb880fc83200.png)

**Comment by Pilchie** [comment]
I believe this is the expected behavior from VS2013.  I don't think the option has ever controlled a space before the `<` in a generic method.
