### ISSUE TITLE
LanguageServerIndexFormat test 'TestSourceFilePathMappingWithDriveLetters' has unused parameters

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44224]
See https://github.com/dotnet/roslyn/blob/3271dee8262ade238e91fc9a21c5674655bb7b31/src/Features/Lsif/GeneratorTest/CompilerInvocationTests.vb#L62-L81

'from' and 'to' parameters to test method are both unused and are flagged by IDE0060 (identified in https://github.com/dotnet/roslyn/pull/44199)

**Comment by mavasani** [comment]
Tag @jasonmalinowski

**Comment by jasonmalinowski** [comment]
D'oh. Will fix.

**Comment by jasonmalinowski** [comment]
@mavasani Thanks for finding this one -- I had started writing a theory to exhaustively cover a possible bug farm, and never finished the work!
