### ISSUE TITLE
Consider enabling CA2249 (Consider using 'String.Contains' instead of 'String.IndexOf')

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44234]
> Consider using 'String.Contains' instead of 'String.IndexOf'

https://github.com/dotnet/roslyn/blob/a2e5f8733bd61180f908d64f27cc3d00804e76b3/eng/config/rulesets/Shipping.ruleset#L75

**Comment by CyrusNajmabadi** [comment]
Closing out. We should just do this or not. If so, it should just be assigned a milestone.
