### ISSUE TITLE
Consider enabling CA1713 (Events should not have 'Before' or 'After' prefix)

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44235]
> Events should not have 'Before' or 'After' prefix

https://github.com/dotnet/roslyn/blob/a2e5f8733bd61180f908d64f27cc3d00804e76b3/eng/config/rulesets/Shipping.ruleset#L38

**Comment by CyrusNajmabadi** [comment]
Closing out. We should just do this or not. If so, it should just be assigned a milestone.
