### ISSUE TITLE
Proposal: Inferred type for const

### ISSUE THREAD

**Issue by KimTranjan** [dotnet/roslyn#4423]
# Background

Would be great to have a shorter way to define a constant. I think that defining the type is redundant and unnecessary.

``` c#
public const string Subject = "Welcome :)";

internal const decimal planPrice = 10;

const int months = 12;
```
# Solution

Just define your constant without the type.

``` c#
public const Subject = "Welcome :)";

internal const planPrice = 10M;

const months = 12;
```

**Comment by TyreeJackson** [comment]
:+1: I like this idea.  It would also help with vertical alignment of constant names without having to resort to additional spacing:

```cs
const subject         = "Welcome :)";
const planPrice       = 10M;
const months          = 12;
const lastValidDate   = new DateTime(2100, 1, 1);
```

as opposed to:
```cs
const string      subject         = "Welcome :)";
const decimal     planPrice       = 10M;
const int         months          = 12;
const DateTime    lastValidDate   = new DateTime(2100, 1, 1);
```

Although, there is something to be said about being able to scan down a list of constants and easily be able to pick out ones based on type.

**Comment by tpetrina** [comment]
I would love to have this kind of inference in method bodies so I can write
```
const max = Config.MaxParams; // inferred as const Int32
```

**Comment by CyrusNajmabadi** [comment]
I have a PR for this here: https://github.com/dotnet/roslyn/issues/4423

Note: this is about supporting "const var x = ..." in a local scope.  It does not include allowing "const x = ..." or allowing "const var x = " in a field of a class.

**Comment by gafter** [comment]
See #5050 for a prototype of this.

**Comment by gafter** [comment]
@CyrusNajmabadi The original proposal here was clearly intended to cover constant fields (two out of three examples are of that). Yet in your comment and PR it says "this is about supporting const var ... in a local scope". Can you please clarify whether the proposal is intended to support both, or is limited to the situations you have prototyped? If the latter, can you please edit the original proposal?

**Comment by alrz** [comment]
Just to mention,
```cs
from foo ...
from T foo ...
let foo = ...
let T foo = ...
readonly foo = ...
readonly T foo = ...
const foo = ...
const T foo = ...
```
It'll be actually more consistent without `var`.

**Comment by DavidArno** [comment]
I was going to create an issue to request this feature, when I found this one. 

Did this happen with C# 7, and I just missed it? Was it dropped by the language team? Or did it's priority just get pushed down and so it's still on the back burner?

Any updates from @gafter, @CyrusNajmabadi etc would be appreciated.

**Comment by gafter** [comment]
@DavidArno This issue is still on the LDM's list of features to consider for future language versions. We're sorting and prioritizing that list over the next couple of weeks. When it stabilizes I'll publish it.

**Comment by DavidArno** [comment]
@gafter,

That's good to hear. Thanks for the update.

**Comment by gafter** [comment]
This feature request is now tracked at https://github.com/dotnet/csharplang/issues/106. It is championed by @CyrusNajmabadi
