### ISSUE TITLE
VS2015 compiler picks overload differently from VS2010; should be ambiguous?

### ISSUE THREAD

**Issue by rawling** [dotnet/roslyn#4424]
Given the function members

    void Fn(string x = "", string y = "", params object[] p) {}
    void Fn(string x, params object[] p) {}

and the invocation

    Fn("Hello", p: "World");

VS2015 uses the first definition of `Fn` both for IntelliSense and when debugging.

By contrast

 - VS2013 (on a system with VS2015 also installed) uses the first definition of `Fn` when debugging but the second for IntelliSense.
 - VS2010 uses the second definition of `Fn` for IntelliSense and (reportedly) when debugging.

By [my reading of the C# 5 specification](http://stackoverflow.com/a/31884572/215380) both function members are applicable but neither is "better" so the compiler should report the invocation as ambiguous.

(Further, if you remove `p` from both function members and the invocation, both VS2015 and VS2013 pick the second member over the first, which makes me more inclined to believe it should be ambiguous.)

**Comment by sharwell** [comment]
This is the feature in C# 6 known as "better betterness". There is no way to disable the new overload resolution when compiling with Roslyn, even if you change the language version to prevent the compiler from recognizing new language constructs (e.g. `nameof`).

**Comment by rawling** [comment]
Is this according to the C# 6 specification, then? In which case, I look forward to the day it's published...

**Comment by gafter** [comment]
We should investigate to ensure this is intentional.

**Comment by rawling** [comment]
Here's [something similar](http://blog.slaks.net/2014-05-28/exploring-roslyn-part-3-breaking-changes/)  (section `Overload resolution with conflicting ambiguities`) from a year ago; it said that Roslyn would mark the call as ambiguous and thus be a breaking change.

**Comment by gafter** [comment]
@AlekseyTs Could you please investigate to ensure the new behavior is intentional (i.e. either a spec change, or a compatibility fix)?

**Comment by AlekseyTs** [comment]
@gafter Please verify
