### ISSUE TITLE
Intellisense listing members for wrong class inside lambda (VS 2019 16.5.5)

### ISSUE THREAD

**Issue by Nazgutek** [dotnet/roslyn#44248]
**Version Used**: Visual Studio 2019 16.5.5 

**Steps to Reproduce**:

1. Project using Insight.Database
2. 

    public class Header
    {
      public int HeaderId;
      public string Title;
      public IEnumerable<Child> Children { get; set; }
    }

    public class Child
    {
      public int ChildId { get; set; }
      public string ChildName { get; set; }
      public IEnumerable<Grandchild> Grandchildren { get; set; }
    }

    public class Grandchild
    {
      public int GrandchildId { get; set; }
      public string GrandchildName { get; set; }
    }

    public async Task<Header> Get(int headerId, CancellationToken cancellationToken)
    {
      var rawResult = (await (new SqlConnection()).QueryAsync(
        sql: "uspHeaderGet",
        commandType: System.Data.CommandType.StoredProcedure,
        parameters: new { HeaderId = headerId },
        returns: Query
          .Returns(Some<Header>.Records)
          .ThenChildren(Some<Child>.Records)
          .ThenChildren(Some<Grandchild>.Records,
                  parents: header => header.Children,
                  id: child => child.ChildId) // Intellisense lists the members of Header here
        , cancellationToken: cancellationToken)).FirstOrDefault();
      return rawResult;
    }

**Expected Behavior**:
When typing the line

    id: child => child.ChildId) // Intellisense lists the members of Header here

it is expected that after

    id: child => child.

intellisense would list the members of Child

**Actual Behavior**:
When typing the line

    id: child => child.ChildId) // Intellisense lists the members of Header here

at the point of typing:

    id: child => child.

intellisense lists the members of Header

Actually selecting a member of Header, eg HeaderId 

    id: child => child.HeaderId) // Intellisense lists the members of Header here

gives:

Error	CS1061	'Repository.Child' does not contain a definition for 'HeaderId' and no accessible extension method 'HeaderId' accepting a first argument of type 'Repository.Child' could be found (are you missing a using directive or an assembly reference?)

So the compiler and intellisense are in disagreement. The use case for insight means that this line in question should be providing the Id field of the Child so that the Grandchildren can be allocated correctly.

**Comment by Nazgutek** [comment]
I'm well aware of that New SqlConnection(). The code isn't intended to run, merely to compile and to illustrate Intellisense getting the wrong context.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.
