### ISSUE TITLE
Adding AdditionalFiles Through VS Workspace

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4425]
currently when additional files are added to VS workspace, it does added to VS, but that information doesnt propagate into vs workspace.

the reason is, when file is added to VS, it is not controlled on how it is added, so if there is no property saying the added file kind is additional file, VS (msbuild) will not let us know the additional file is added. so at that point, VS and VS workspace is in somewhat inconsistent state. (one can say it is still in consistent state since even though VS added that file, VS doesnt consider it as additional file, and VS workspace doesnt care about a random file belong to VS - but it is certainly confusing to users who just added additional files to workspace since it shows up in VS, but not in VS workspace)

I think we either need to support adding additional file properly (user add additional files, and it shows up in VS and VS Workspace and VS consider the added file as additional file) or Workspace.TryApplyChange should return false or throw an exception saying adding additional file is not supported.

**Comment by tmeschter** [comment]
@heejaechang I don't understand the problem. If the user adds an additional file through the `Workspace`, what exactly changes in the project file, and how does that differ from what you expect?

**Comment by heejaechang** [comment]
@tmeschter simply put, if you do, 

var newsolution = solution.projects...AddAddtionalFile(...);
Assert.True(workspace.TryApplyChange(newSolution));

workspace.CurrentSolution.Projects...AdditionalFiles doesn't contain the additional file you just added.

what current behavior is seems not relevant. since current behavior seems just something happen to be that way rather than explicitly coded to support it.

**Comment by heejaechang** [comment]
ah, here, workspace is VSWorkspace.

**Comment by tmeschter** [comment]
@heejaechang It matters if the project file is actually being modified or not, and if it is being modified, exactly what is changed.

**Comment by heejaechang** [comment]
@tmeschter since we ask project system to add a random file, project system will add the text file. I think it is added as just random text file (<None ...>) which is just a random text file and VS will not let us know about it.

**Comment by heejaechang** [comment]
@tmeschter current flow of interaction is that. (you probably already know but for clarity)

1. users do TryApplyChange
2. Workspace let VS know about the change
3. VS let us know about the change through intellisense build
4. Roslyn project system let VSWorkspace knows about the change
5. users can see the change through workspace.CurrentSolution.

for additional files, when user do /1/, we do /2/ and then things stop there.

**Comment by kabua** [comment]
We have just ran into this issue. We are code generating several classes (across various layers) starting from a DTO class definition. As part of this code generation process, we would like to inject one or more JavaScript files into the SPA layer. 

If we use (AddDocument):

    var newDoc = project.AddDocument("test.js", srcText, folders);
    workspace.TryApplyChanges(newDoc.Project.Solution);

the file ```test.js``` is 1) added to the project but 2) the file is renamed to ```test.cs```, which is a no-go for us.
Note: ```workspace``` is a ```MsBuildWorkspace```.

Next, if we use (AddAdditionalDocument):

    var newDoc = project.AddAdditionalDocument("test.js", srcText, folders)
    workspace.TryApplyChanges(newDoc.Project.Solution);

the file is part of the ```workspace``` but when we open up the solution within VS2015 the file doesn't exist in the solution/project or on disk, this is a major no-go!

Expected results: adding an additional document should: 1) add the file to the file system, 2) be added to the VS2015 project, and without modifying the filename or the extension, 3) VS2015 should treat the file as "Add Existing Item" and wire up this existing item properly.

Even though we love C#, we still have to work with other languages, technologies and file formats.

**Comment by jasonmalinowski** [comment]
@kabua: just to explain the AddDocument behavior: AddDocument is the API for adding files of the same language as the containing project, which is why you're seeing us changing the extension. So AddAdditionalDocument is what you want, if it wasn't for this missing feature.

**Comment by tannergooding** [comment]
FYI. @KevinH-MS, this is related to some of the issues we were seeing with handling Additional Files. I don't think it will solve all our problems though.

**Comment by kabua** [comment]
Are you saying that the ```AddAdditionalDocument``` function is broken? And if it wasn't broken then I would be able to add JavaScript files to the containing project using this function?

**Comment by jasonmalinowski** [comment]
Yes; this bug is the bug tracking it's brokenness.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
