### ISSUE TITLE
Show CodeLens for field

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#44254]
`public string Description = ".....";`

When I modify the value of `Description`, I want to view its history value by git, but there's no CodeLens for field, so I can't view the field history by git.

**Comment by sharwell** [comment]
Duplicate of #23908

**Comment by sharwell** [comment]
@CreateAndInject this is effectively a duplicate of a previous issue. I'm going to widen the title of the other issue so it's clear both apply.
