### ISSUE TITLE
Show actionable diagnostic source in error list

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44252]
Currently analyzers report diagnostics to the error list without indicating the specific analyzer package responsible for the diagnostic. Ideally, the information for the **Source** or **Tool** column would be augmented by:

* For VSIX-installed analyzers: the name of the extension that provided the analyzer
* For NuGet-installed analyzers: the name of the package that provided the analyzer
* For analyzers of an unknown source: the name of the assembly that provided the analyzer

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  IF we need to do this, we should assign to a person/milestone and do it.
