### ISSUE TITLE
Roslyn doesn't verify `[NotNull]` annotation on returns in void methods

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#44258]
**Version Used**: 
```
commit 7b27ca3b7722c5e56910a6cfba837e6a9d352d4f
Author: Tom<C3><A1><C5><A1> Matou<C5><A1>ek <tmat@users.noreply.github.com>
Date:   Mon May 11 19:17:04 2020 -0700

    Fixes PathMap parsing to support all paths (#43706)
```

**Steps to Reproduce**:

Compile and run the following code
```cs
using System.Diagnostics.CodeAnalysis;

class C
{
  public static void Main()
  {
    string? x = null;
    M(ref x);
    x.ToString();
  }
    
  public static void M([NotNull] ref string? s)
  {
    if (s is null) return;

    s.ToString();
  }
}
``` 

**Expected Behavior**:
`CS8777 Parameter 's' must have a non-null value when exiting.` for `return` in `M`

**Actual Behavior**:
No warnings at all in the program above. It crashes at runtime with a `NullReferenceException`

**Notes**
The same for expression-bodied members i.e. no warnings here:
```
public static void M([NotNull] ref string? s) => s?.ToString();
```

The warning appears if you return statement has an expression to return e.g.
```
  public static int M([NotNull] ref string? s)
  {
    if (s is null) return 1;

    s.ToString();
  }
```

I bet this `enforceNotNull` call should be outside of the containing if statement: https://github.com/dotnet/roslyn/blob/7b27ca3b7722c5e56910a6cfba837e6a9d352d4f/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L461

**Comment by jcouv** [comment]
Looks like we fixed this. I see a warning now.

```
#nullable enable
using System.Diagnostics.CodeAnalysis;

class C
{
  public static void Main()
  {
    string? x = null;
    M(ref x);
    x.ToString();
  }
    
  public static void M([NotNull] ref string? s)
  {
    if (s is null) return; // warning CS8777: Parameter 's' must have a non-null value when exiting.

    s.ToString();
  }
}
```
([sharplab](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABABixIEYA6AEQEtkBzGAewGcAXBgYw5oBhNsAwBBPAgCeHBhwDcxYiQBMWQcQDexLJRUqdWbUV27qZAPxYAHlgC8WeEkUnTAWQAUAJwwAzGwCULqY2NAAqbADKXF4MMMweQYYAvoa6hiQAzJRUAGyUACxYngDaAHJsXGWICAC6WD7+5lYcAYbGIQz+HhxYco41AZQA7PJYAPTjWADuyF4wcczqkQAcw+sgWAAKc8gAthhcGF5YAOQcp1h7cNxYABbIAG7YyI5sMAC0TghYj8gIcGw0zuuBw1gYPHiNCUrl0Agi0Vi8USwSwqSIySAA===))

I'll go ahead and close the issue as fixed. Thanks
