### ISSUE TITLE
[C# interactive] Variables get overwritten if you create a variable with the same name

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#4426]
C# shouldn't let you successfully run the following two commands back to back.

    string test = "foo";
    int test = 42;

There should be an error, like in normal C# saying 'A local variable named 'test' is already defined within this scope'.

Instead of the error, the second command overwrites the string version of test, and makes test only equal to 42.

**Comment by tmat** [comment]
If these declarations are in distinct submissions than by design the latter shadows the former.
