### ISSUE TITLE
SkipLocalsInit specification lacks the "unsafe" requirement

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44262]
The specification for SkipLocalsInit doesn't appear to describe the implemented requirement that unsafe be in effect.

**Comment by agocke** [comment]
Actually, it does https://github.com/dotnet/roslyn/blob/master/docs/features/skiplocalsinit.md

> Although SkipLocalsInit does not require unsafe code blocks, it does require the unsafe flag to be passed to the compiler. This is to signal that in some cases code could view unassigned memory, including stackalloc.
