### ISSUE TITLE
delimited comment not honoring EOL convention

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#44282]
**Version Used**: 

VS 16.6.0 Preview 6.0

**Steps to Reproduce**:

similar to https://github.com/dotnet/roslyn/issues/41322

1. add `end_of_line = lf` to `.editorconfig`
2. write multiline comments in C#

**Expected Behavior**:

Line endings in the comments are LF.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/3760955/82005806-4208de80-96a1-11ea-850d-f912d8080f67.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
