### ISSUE TITLE
'introduce local' quick fix break my code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44291]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1010681/introduce-local-quick-fix-break-my-code.html)._

---
C#
I'm trying to use a quick fix for 'introduce local for ...' a string literal, which is an argument to 'LogInformation()' extension method on 'ILogger log' object. I select the string literal, press Alt+Enter, hit Enter, and this code

`log. LogInformation($"info");`

turns into this:
            
```
string message = $"info";
Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(log, message);
```

which gives me this build error: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'LoggerExtensions' exists in both 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

Why should it refactor my code at all? Shouldn't it simply extract the literal into a variable and leave everything else without change? I often see this odd behavior when my code is messed up with unnecessary ugly type casts, extensions methods converting to static method calls and so on. Awful experience. The problem is that I don't even always notice the change, and then having a hard time trying to read my code and to udnerstand it's meaning...

---
#### Visual Studio Feedback System on 4/29/2020, 02:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by artemious7** [comment]
thanks for moving my question to the right place. Waiting to see this get fixed

**Comment by CyrusNajmabadi** [comment]
Hi @artemious7 can you let me know what assembly or package you're referencing that brings in those methods/types/extensions?  thanks!

**Comment by artemious7** [comment]
Here's part of my project file
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ChannelAdam.Serilog.Sinks.MicrosoftExtensionsLoggingLogger" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.11" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6" />
  </ItemGroup>
```

**Comment by CyrusNajmabadi** [comment]
Thanks. I can repro this.  it's definitely an odd case.  The compiler accepts calling the extension method in instance form, but not in static method form.  That breaks our system for fixing and resolving conflicts.  i.e. in order to preserve code meaning, refactorings convert to an internal form that does things like make implicit casts explicit, supply inferred type arguments, and invoke extensions statically.  This work is then undone at the end if it can be done safely. 

In this case, because the static-method-call has an error, we don't undo what we did.  We'll have to figure out why this is an error though as this expansion was previously always thought to be safe.

**Comment by sharwell** [comment]
@CyrusNajmabadi we may need to add a `SymbolAnnotation` when complexifying extension methods and/or leverage it during the simplification process to restore a working state.
