### ISSUE TITLE
Consider removing the rename-dashboard/inline-rename experience

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44297]
Our current experience is very slick, but comes at the cost of high complexity, and a difficult architecture and impl to make work in scenarios like LSP and Nexus.  I propose we keep good parts of what we have today, while jettisoning the rest.

Specifically:

1. we should *keep* the rename-tracking-smart-tag.  This is a fairly simple edit-state-machine that watches edits and offers the rename-smart-tag to just perform a rename immediately when an name change is detected.  
2. we should *keep* all our conflict detection and resolution logic.  This allows users to confidently perform rename without having to worry about semantics changing in common cases.
3. we should *keep* the existing rename entrypoints (like `right-click 'rename'`, `ctrl-r-r`, and `f2`).  
4. when those entrypoints are triggered we should pop up a simple dialog that asks for the new name.  That dialog can potentially do some small amount of immediate validation.  For example, validating that it's on something renameable, and validating that the new name is legal.  The dialog can have the options on it for things like renaming files/overloads.

What we would specifically be removing is the *inline rename + dashboard* experience.   i.e. when you invoke 'rename' today and enter into the inline-editing experience where you can only edit the highlighted span, and there's the dashboard in the upper right telling you how many items will be renamed.

This would remove an enormous amount of complexity we have with things like buffer management + tracking spans, as well as all the complex and duplicative work we're performing today to go and resolve all conflicts.  It also prevents all the complexity we have today of needing to piecemeal send things back/forth over OOP.  We would be able to just remote the final call to do the full rename, and could get the results back to apply to the solution.  This approach would work uniformly for all our hosts.

This would certainly be a takeback for customers.  But i'm honestly not seeing the existing experience providing that much over slickness.  For example, when i use vscode i do not miss this at all.  I don't think i personally ever care or use the information in the dashboard, and i actively dislike how clunky the performance feels for rename in VS over how lightweight and simple it is for vscode.

Bringing to next design meeting.

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph @kendrahavens @mikadumont

**Comment by mikadumont** [comment]
Yes, I am definitely in favor of removing the highlighted span and the dashboard. The new rename dialog can look like the following: 

![image](https://user-images.githubusercontent.com/46729679/82088466-a9755d00-96a6-11ea-8fc1-48ffd1a84205.png)

**Comment by tmat** [comment]
I do not like popping up dialog. It takes away focus from the editor. I think we can achieve the desired simplicity by creating just a single green tracking span for the identifier rename is invoked on.

**Comment by tmat** [comment]
One of the disadvantages of a dialog is that I can't go to another place in the editor and copy & paste name from there without cancelling the dialog and invoking rename again.

**Comment by CyrusNajmabadi** [comment]
We can talk aobut this on monday.  I think your concerns are valid, but i'm not sure the complexity is warranted or viable for the nexus/lsp world.  Or, put another way, i think we can invest in the scenario by having it be provided by the platform through LSP rather than having roslyn own specialized complex logic here.

**Comment by tmat** [comment]
Definitely - i'm not saying we should provide a custom complex logic. I'd like the experience of rename within the editor (no dialog) to be provided by platform.

**Comment by JoeRobich** [comment]
## Design Review Notes

- How will this effect other features that leave the user in a rename experience?
- Replacing the current experience with a modal dialog would block the ability to interact with the editor (scroll looking for updated references or conflicts) during a rename. 
- Check with TypeScript and F# who may be relying on the current experience. 
- We would like to maintain the reference and conflict highlighting in the editor.

Proposal:
- Investigate a VS Code-like inline floating editor. Flight the experience to a subset of preview users and track sentiment about the change (the number of opt-outs or via a survey).

**Comment by CyrusNajmabadi** [comment]
Also, we discussed this more after the meeting ended.  LSP/Nexus already *has* an inline rename experience (though it could likely use some polish).  We can just try flighting users to that to see their reaction.

**Comment by CyrusNajmabadi** [comment]
Closign out.  We've already updated this UI.  If LSP gets a sufficient rename experience we will move to that.
