### ISSUE TITLE
Handle use of VBCore in a conditional breakpoint before it is loaded

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#443]
Reported by @rchande.  I suspect this is related to DevDiv #1112908, but I have not had a chance to verify.

Condition was `item1.DisplayText = "E.Bat"`
Error was `error BC35000: Requested operation is not available because the runtime library function "Microsoft.VisualBasic.CompielrServices.Operators.CompareString is not defined.`

**Comment by amcasey** [comment]
Oh, we probably just aren't handling this error code as one that requires loading of a module.

**Comment by amcasey** [comment]
Yeah, `EvaluationContext.GetMissingAssemblyIdentitiesHelper` just needs to handle `ERRID.ERR_MissingRuntimeHelper`.

**Comment by amcasey** [comment]
@rchande can you please confirm that your issue has been resolved?

**Comment by rchande** [comment]
Verified.
