### ISSUE TITLE
FileTextLoader.LoadTextAndVersionAsync can have multiple outstanding requests for the same document

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44300]
**Version Used**: 16.5.4

🔗 https://developercommunity.visualstudio.com/content/problem/1020481/vs-1654-crashes-after-opening-a-solution.html

The crash dumps for this issue show many threads loading the same file in `FileTextLoader.LoadTextAndVersionAsync`. Each of these threads requires a large buffer to hold the file content, and together they run the process out of memory.

Multiple (concurrent) requests to `TextLoader.LoadTextAsync` for the same document should instead share the same load operation.

**Comment by tmat** [comment]
Do you mean LoadTextAsync should lock while reading the file?

**Comment by sharwell** [comment]
@tmat Not necessarily. I'm looking into this.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.  IF we need to make a change here we should assign to a person/milestone and make the change.
