### ISSUE TITLE
[C# Interactive] Fading is broken

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#4430]
Unused usings and overqualified names no longer fade ( e.g., System.Console.WriteLine)

![image](https://cloud.githubusercontent.com/assets/1402694/9146005/f424d404-3d0d-11e5-9596-c158e629263f.png)

**Comment by amcasey** [comment]
Related to #801.

**Comment by amcasey** [comment]
Part of #3785.

**Comment by amcasey** [comment]
All usings are now considered to be used in interactive, so they should never be grayed out.
Fading of overqualified names works on my box.  Either it was fixed, of the analyzer kicked in after the screenshot was taken (there's a multi-second delay).

**Comment by amcasey** [comment]
@kuhlenh Please verify.

**Comment by kuhlenh** [comment]
:+1:
