### ISSUE TITLE
[Feature request] Show TargetFramwork in the definition view (go to definition)

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#44319]
Hello,

It would be very handy, when the definition view show the `TargetFramwork` of the used library, like
```
Assembly System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, TargetFramwork=netcoreapp3.1
```

**Version Used**: 
Visual Studio 16.6.0 Preview 6

**Steps to Reproduce**:

1. Click on a reference type or value type from a library (Framework, NuGet package, ...)
2. Press `F12`
3. Read the first line 

**Expected Behavior**:
The definition view should have a information about the target. like
```csharp
#region Assembly System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, TargetFramwork=netcoreapp3.1
// C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Runtime.dll
#endregion
```

**Actual Behavior**:
There is no information about the target in the definition view.
```csharp
#region Assembly System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\System.Runtime.dll
#endregion
```
_Yes, in this case the unfold region shows the path of the library and the path contains the TargetFramework, but this is not always in the path name_

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
