### ISSUE TITLE
Function Pointer syntax puts "expected" IsMissing tokens

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#44312]
Currently the parser parses each parameter in the function pointer list as a parameter with a missing parameter name. This token is IsMissing even though it's never expected to be there. It seems this breaks invariants in the formatter because the IsMissing tokens are never formatted around:

https://github.com/dotnet/roslyn/blob/d1a015142d692508cd4284c9366abd2dd1e6af56/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Formatting/Engine/AbstractFormatEngine.cs#L437-L442

**Comment by CyrusNajmabadi** [comment]
Yes.  this is definitely a violation of parse tree expectations.  we should not have missing or skipped tokens/nodes in correctly parsable user code.

**Comment by 333fred** [comment]
This is done.
