### ISSUE TITLE
ServiceHub is crashing a lot in recent builds

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#44335]
**Version Used**: 
Version 16.7.0 Preview 2.0 [30114.165.master]

[B5BDD07E-ManagedLanguage.IDE.RemoteHostClient-14804-tnshvb4q-1.log](https://github.com/dotnet/roslyn/files/4642345/B5BDD07E-ManagedLanguage.IDE.RemoteHostClient-14804-tnshvb4q-1.log)
[B5BDD07E-roslynCodeAnalysis-15464-v01w2jaq-1.log](https://github.com/dotnet/roslyn/files/4642346/B5BDD07E-roslynCodeAnalysis-15464-v01w2jaq-1.log)
[B5BDD07E-roslynRemoteHost-15464-452zatf3-1.log](https://github.com/dotnet/roslyn/files/4642347/B5BDD07E-roslynRemoteHost-15464-452zatf3-1.log)

I've experience a number of crashes in the past few days, attached are the logs.

Here is an example:

```
05/18/2020 14:28:11 AUS Eastern Standard Time: Error : 1 :[devenv:14804] Unexpected exception: System.InvalidOperationException: The operation failed as details for project CommonProjectSystem could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAndAdditionalMessagesAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.<GetPackageSpecsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass8_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)
```

**Comment by CyrusNajmabadi** [comment]
We have a hack to try to deal with that here:

```
            catch (InvalidOperationException e) when (e.StackTrace.Contains("NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync"))
            {
                // NuGet throws an InvalidOperationException if details
                // for the project fail to load. We don't need to report
                // these, and can assume that this will work on a future
                // project change
                // This should be removed with https://github.com/dotnet/roslyn/issues/33187
            }
```

But it likely isn't working since the stack trace changed. We really need a way to be able to call into nuget safely without it just crashing on these sorts of simple calls.  Do you know who might be able to help with that @davkean ?

**Comment by davkean** [comment]
//cc @nkolev92

**Comment by ryzngard** [comment]
@CyrusNajmabadi  don't we report an NFW for this?  Or is it being OOP cause `ReportWithoutCrash` to fail? 

```csharp
           catch (ArgumentException e) when (IsKnownNugetIssue(e))
            {
                // Nuget may throw an ArgumentException when there is something about the project 
                // they do not like/support.
            }
            catch (InvalidOperationException e) when (e.StackTrace.Contains("NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync"))
            {
                // NuGet throws an InvalidOperationException if details
                // for the project fail to load. We don't need to report
                // these, and can assume that this will work on a future
                // project change
                // This should be removed with https://github.com/dotnet/roslyn/issues/33187
            }
            catch (Exception e) when (FatalError.ReportWithoutCrash(e))
            {
            }
```

**Comment by CyrusNajmabadi** [comment]
I think we really just need to fix the exception.  This continued attempt to call this public API and then deal with these exceptions, that we cannot otherwise check for, is just too brittle and difficult.   Literally all we're trying to ask is:

```
IEnumerable<IVsPackageMetadata> GetInstalledPackages(Project project)
```

We need some way to ask this basic question in a resilient, non-throwing fashion.  If that means some sort of `TryGetInstalledPackages(...)` call, so be it.

**Comment by ryzngard** [comment]
@CyrusNajmabadi I agree, just trying to diagnose why we started crashing instead of NFW

**Comment by nkolev92** [comment]
There's really 1 scenario where NuGet would throw that exception and that's when the project has not been nominated yet. 

Similar to some earlier discussions (unfortunately), this all falls under https://github.com/NuGet/Home/issues/9577 and NuGet rewriting all the services to async. 

When that does happen we should design a better contract.

NuGet *will* need some sort of a failure scenario like project not ready/project provided bad NuGet data etc.

Don't want to design that right now, but any feedback is welcome. GetInstalledPackages in particular is getting a lot of scrutiny and we'll need to do it soon.

**Comment by sharwell** [comment]
Reassigning to @CyrusNajmabadi based on recent work on the NuGet API usage
