### ISSUE TITLE
SyntaxEditor.RemoveNode does not remove preceeding blank lines for attribute node removal

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44342]
1. Code fix: https://github.com/dotnet/roslyn/pull/44287/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.projitems&file-filters%5B%5D=.resx&file-filters%5B%5D=.vb#diff-dccac1a37411ddc5b87927bd20a7f3fcR51
2. Test showing the behavior: https://github.com/dotnet/roslyn/pull/44287/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.projitems&file-filters%5B%5D=.resx&file-filters%5B%5D=.vb#r426661162

**Comment by CyrusNajmabadi** [comment]
I'm not certain if this is SyntaxEditor's responsibility, or hte formatter.  Generally, the model here is that this should add elastic trivia around the edit region, and hte formatter should then use those only to tweak up the space between.

**Comment by mavasani** [comment]
Ah, that sounds reasonable. @sharwell?

**Comment by CyrusNajmabadi** [comment]
Closing as due to lack of movement.
