### ISSUE TITLE
Codespaces: go-to-impl doesn't seem to work.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44350]
I opened Roslyn.sln in Codespaces.  I navigated to C:\Users\cyrusn\AppData\Local\Temp\612CA8E9B12E8F6DA8D5CB63808E09D29F0A\6\roslyn\src\EditorFeatures\Core\FindReferences\FindReferencesCommandHandler.cs and tried to do go-to-impl on line 127:

```c#
                    await findUsagesService.FindReferencesAsync(document, caretPosition, context).ConfigureAwait(false);
```

I did the go-to-impl on FindReferencesAsync.  In Codespaces nothing seems to happen.

**Comment by dibarbet** [comment]
Closing as external https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1133651
