### ISSUE TITLE
SuggestedActionSource.TryGetTelemetryId returns false in C#_LSP content type despite providing actions

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#44359]
**Version Used**: 16.7

**Steps to Reproduce**:

1. Connect to Nexus server
2. On client, attempt a refactoring which runs on the server
  * For example introduce local: `Console.ReadLine();` -> `string t = Console.ReadLine();` 
3. Notice an exception in LightBulb telemetry

**Expected Behavior**:

`SuggestedActionSource.TryGetTelemetryId` sets the ID and returns true.
It is expected for entity which produces telemetry items to identify itself.

**Actual Behavior**:

LightBulb telemetry throws an exception because Roslyn [returned false in `SuggestedActionSource.TryGetTelemetryId`](https://github.com/dotnet/roslyn/blob/9625a14e7405d7a3ea1dc77957d5293850b69cc8/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActionsSource.cs#L152).

**Comment by AmadeusW** [comment]
@dibarbet here is Editor PR which avoid throwing exception:
https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/248033
However, we still need Roslyn to identify itself in the C#_LSP content type.

**Comment by dibarbet** [comment]
>  However, we still need Roslyn to identify itself in the C#_LSP content type.

@AmadeusW 2 questions - 
1)  I assume this should be a different guid between C#_LSP and C#?
2)  Is this guid used for anything else, or can I just create a new one and return that for C#_LSP?

**Comment by AmadeusW** [comment]
I think it would be a good idea to create LSP variants for the supported guids: C#, VB, XAML (if applicable). If this turns out to be unnecessary, we will be able to join telemetry results.

**Comment by dibarbet** [comment]
Resolving, now that the content type is C# this is no longer applicable.
