### ISSUE TITLE
Codespaces nav-to is dismissed when VS loses focus

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44353]
This is a regression of teh very intentional change made to nav-to to not do this.  When focus changes, nav-to should stay open and continue searching.

**Comment by CyrusNajmabadi** [comment]
@olegtk do you know who this would be assigned to on platform?

**Comment by olegtk** [comment]
Hmmm, I'm not aware any changes in this area. @jinujoseph  please route this to the editor. Thanks!

**Comment by jinujoseph** [comment]
[routed](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1150737)
