### ISSUE TITLE
Ctrl-comma doesn't prepopulate search query in codespaces

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44351]
Normally, ctrl-comma will bring up navto with teh text under the caret being what is automatically searched for.  This doesn't work in codespaces.  It just brings up:

![image](https://user-images.githubusercontent.com/4564579/82256858-ec843a00-990b-11ea-879b-3e1b502f691b.png)

So you have to retype the symbol name again.

This also does not work even if the identifier is selected.

**Comment by gundermanc** [comment]
Command mapping is being reverted for CloudEnv's. This is now an opt-in under 'Preview Features', but this feedback is top of our list for fixing post-crunch time.

**Comment by jinujoseph** [comment]
Routed to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128693)
