### ISSUE TITLE
Codespaces: symbols not classified properly

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44355]
TYpes and members are not being classified properly.  FOr example:

![image](https://user-images.githubusercontent.com/4564579/82257528-0e31f100-990d-11ea-9a2e-d4a5196cf710.png)

![image](https://user-images.githubusercontent.com/4564579/82257635-3d486280-990d-11ea-999c-5a9149cae645.png)

**Comment by allisonchou** [comment]
Tested - this issue seems to be fixed now with the move of semantic classifications to LSP.
