### ISSUE TITLE
Add analyzer/fixer to recommend switching global suppression target string from legacy FxCop format to Roslyn format

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44362]
[Global suppressions](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#global-level-suppressions) allow suppressing analyzer diagnostics on specific symbols via an attribute that requires a "Target" string argument that encodes the fully qualified name of the symbol. This target can be specified in one of the following formats:

1. Roslyn's [documentation comment ID format](https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#id-string-format), which has a `~` prefix followed by the symbol's documentation comment ID. This is the format of suppressions generated by the code fixes/light bulb in Visual Studio
2. [Legacy FxCop's](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers?view=vs-2019) custom format for post-build FxCopCmd.exe based suppressions.

Roslyn's format is the officially supported and recommended format for global suppression target. Legacy FxCop's format is supported only for backwards compatibility, and recently has shown performance issues in the IDE typing scenarios while attempting to decode the target. See https://developercommunity.visualstudio.com/content/problem/1026087/slow-ide-after-edits.html for an example typing trace dominated by attempting to decode a global suppression in legacy FxCop format.

This issue tracks adding a new analyzer/code fix to detect global suppressions in legacy FxCop format, and offering a code fix to convert them to the Roslyn's format.

**Comment by softworkz** [comment]
This analyzer has a bug. It shouldn't report cases where 

```
Scope = "namespaceanddescendants"
```

because afaik, there doesn't exist a "Roslyn format" for the "Target" attribute in this case.
