### ISSUE TITLE
Completion of unimported members stomps on namespace aliases

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#44366]
**Version Used**: 3.7.0-2.20267.1+3126e7a9753bf09a99e4c4f152b8dfef76862dc5

Sometimes we have a namespace alias at the top of the file to avoid collisions with common names in a file. A good real-world example is https://github.com/dotnet/roslyn/blob/14a785e3640a075b6233d10e4d3746cc86a96ddb/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs#L16. The problem is the unimported namespace completion counts these types as unimported if you don't qualify them with the alias. As a simpler example:

![image](https://user-images.githubusercontent.com/201340/82271267-2e24dd00-992c-11ea-9393-2033950b042e.png)

If you complete this item, it'll add a regular using for "System.Threading.Tasks" which means the original reason for the alias existing is now moot.

**Proposal:** if you're committing an item from an unimported namespace, _and_ there's already an alias for that namespace in the file, instead of adding the using statement we should just commit it with the existing alias.

**Comment by Dreamescaper** [comment]
duplicate: https://github.com/dotnet/roslyn/issues/39785

**Comment by jasonmalinowski** [comment]
Same scenario although opposite proposal: the other bug is suggesting to not include the items, whereas I'm suggesting to still list, but just fix up on commit. @genlu you can decide which you want to implement. :smile:

**Comment by genlu** [comment]
@Cosifne Do you want to give this bug a shot?
