### ISSUE TITLE
"Cast is Redundant" warning mistaken in local functions with default enum values, code fix generates un-compilable code

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#44382]
**Version Used**: 
VS 16.5.4

**Steps to Reproduce**:

The following code shows the problem:
```c#
    enum E : byte { }
    class C { void F() { void f(E e = (E)byte.MaxValue) { } } }
```

Note that in a top-level function, this is not an issue. This only happens specifically in local functions. 

**Expected Behavior**:
No warnings (related to the cast, obviously the minimal code has a whole bunch of other warnings for unused identifiers).

**Actual Behavior**:
Code generates the following warning `IDE0004`:
![image](https://user-images.githubusercontent.com/541998/82345871-c4f0a880-99c3-11ea-824f-7408ca9844d3.png)

As you can see in the proposed code fix, it generates the following error when used:

``` 
error CS1750: A value of type 'byte' cannot be used as a default parameter because there are no standard conversions to type 'E' 
```

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  I'll create a test to validate this and will close this out.

**Comment by myblindy** [comment]
Perfect, thank you!
