### ISSUE TITLE
move analyzer out of Roslyn repository and stop building them from Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4438]
currently we build them and not sign them when we publish those dlls in nuget package. we should either sign them or move them out from Roslyn.

**Comment by tmeschter** [comment]
@heejaechang Which analyzer assemblies, specifically?

We're in the process of moving most, if not all, to dotnet/roslyn-analyzers.

**Comment by heejaechang** [comment]
@tmeschter all of them I think. currently we are building analyzer nuget package in Roslyn but not signing them. this issue is to track to move all those out from roslyn build.

**Comment by genlu** [comment]
@tmeschter I think we can go ahead and remove everything under src/Diagnostics in dontnet/Roslyn, is that right?

**Comment by tmeschter** [comment]
@genlu First we'll want to diff the files in dotnet/roslyn-analyzers against dotnet/roslyn to double-check that no changes have been checked in to the analyzers since they moved. Otherwise, yes, I think we can remove everything under src/Diagnostics now.

**Comment by genlu** [comment]
This issue is closed with https://github.com/dotnet/roslyn/pull/4633

**Comment by heejaechang** [comment]
@genlu @tmeschter please make sure removing diagnostics from signcheckwhitelist.txt from Closed/Tools
