### ISSUE TITLE
Gold bar: AggregateException in SemanticClassificationBufferTaggerProvider

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44395]
**Version Used**: 16.7 Preview 1

**Steps to Reproduce**:

Unknown.

**Actual Behavior**:

```
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationBufferTaggerProvider.Tagger.GetAllTags(NormalizedSnapshotSpanCollection spans, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```

**Comment by Unknown6656** [comment]
I began having the same issues since the update to 16.7-preview4 this week.

**Comment by CyrusNajmabadi** [comment]
We moved semantic classification to OOP, and were recently having the OOP cancellation token issue.  Seems highly likely they're related.  @tmat @mavasani what's the status of the cancellation issue that was found in jsonrpc?

**Comment by tmat** [comment]
https://github.com/microsoft/vs-streamjsonrpc/issues/489

**Comment by tmat** [comment]
@CyrusNajmabadi Unless the log contains
```
Stream disconnected unexpectedly:  RemoteProtocolViolation, 'A response was received without a request having been sent.
```

it's a different issue.

**Comment by sharwell** [comment]
@CyrusNajmabadi the cancellation issue is _only_ present in 16.7 Preview 4 (introduced there, and fixed in 16.7 Preview 5 today).

**Comment by jasonmalinowski** [comment]
I just hit this earlier during dogfooding, and I think I saw it last week too. Do we have any other known causes or should I work to get more logs?

**Comment by sharwell** [comment]
@jasonmalinowski The gold bar occurs when one of the following happens:

1. `ProduceTagsAsync` transitions to the cancelled state but `cancellationToken` is not requesting cancellation
2. `ProduceTagsAsync` transitions to a _failed_ state (instead of cancelled) when `cancellationToken` is requesting cancellation

**Comment by jasonmalinowski** [comment]
@sharwell The failure log showed the aggregate exception was containing a cancellation exception, so if there was a failure it was upstream and something incorrectly converted it to a cancellation. (explicit ContinueWith continuations will also transition to cancelled if the antecedent didn't complete in the way expected, so it's possible there's a failure we're "losing" somewhere.)

**Comment by CyrusNajmabadi** [comment]
I don't see anything in current logs on this.  At one point we had a *bunch* cancellation issues with OOP, but those went away many many months ago when we rewrote the component related to streaming messages and cancellation processing.  I'm going to assume this was a manifestation of that issue.
