### ISSUE TITLE
Invalid keyword suggestions 'and'/'or' may appear after 'global' keyword

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#44396]
**Version Used**: VS 16.7P1 (`'3.7.0-1.20257.3 (4b5650e5)'. Language version: preview`)

**Steps to Reproduce**:

Invoke Intellisense after any `global::`.

```c#
object M(object o)
{
    if (o is null or global::) { }

    return o switch
    {
        global:: => true,
        not global:: => false,
        null when o is not global:: => null
    };
}
```

**Expected Behavior**: The keywords do not appear as they are not valid at that location.

**Actual Behavior**: The keywords "and" and "or" are suggested.

![image](https://user-images.githubusercontent.com/823398/82381347-53981080-9a2a-11ea-9fbd-c5f3b1610923.png)

**Comment by CyrusNajmabadi** [comment]
Taggign @allisonchou
