### ISSUE TITLE
Remove OpenSourceDebug.vsix

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4439]
some dlls in the vsix are not signed. we either need to sign them or get rid of the vsix.

**Comment by davkean** [comment]
@jasonmalinowski Are you working on that?

**Comment by jasonmalinowski** [comment]
@davkean: it's not entirely going away, but what is will change significantly in the next few weeks. You can probably assign this to me. I'll put it in the 1.2 milestone since it doesn't need to be done for 1.1, but I'll probably look at it as soon as 1.1 ships.

**Comment by jasonmalinowski** [comment]
This is now done.
