### ISSUE TITLE
Handle FAR/Inline rename for references in global suppression parameters

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44401]
See skipped tests added in https://github.com/dotnet/roslyn/pull/44368

1. TestTypeReferenceInGlobalSuppressionParameter
2. TestTypeReferenceInGlobalSuppressionParameter_GenericType
3. TestTypeReferenceInGlobalSuppressionTypeParameter_GenericType

Few more cases to handle:
1. Type references in return type
2. Type references in generic type arguments. See https://github.com/dotnet/roslyn/pull/44368#discussion_r430113227

Also add a test for negative cases where user supplied a target string that does not match the documentation ID regex pattern. See https://github.com/dotnet/roslyn/pull/44368#discussion_r430113819

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
