### ISSUE TITLE
determine what to do with .net 2.0 reference mscorlib.dll we build

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4440]
we need to either sign it or give responsibility to other team.

**Comment by tmat** [comment]
We need to sign it then. Note that we don't ship this binary. It's only a reference assembly used for building EEs.

**Comment by davkean** [comment]
Why do we actually build .NET 2.0 mscorlib?

**Comment by tmat** [comment]
We build Expression Evaluator against mscorlib 2.0 public surface.

**Comment by tmat** [comment]
We don't need to sign it. It doesn't ship.
