### ISSUE TITLE
Move DiagnosticAnalyzerService document analysis OOP (refactor)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#44408]
`TryAppendDiagnosticsForSpanAsync`
`GetDiagnosticsForSpanAsync`
`GetDiagnosticsAsync` 

are running diagnostic analyzer in-proc.

Prereq: support for multiple workspaces OOP (primary, preview, etc.)

**Comment by CyrusNajmabadi** [comment]
Note: i think it would be ok to potentially not run analyzers in preview workspace *initially*.  i.e. the benefit we get of moving these OOP far outweighs the benefit of having a squiggle occasionally show up in a preview workspace.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn/pull/45607 implements this refactoring.

Open implementation questions:

1. Do we need to put this change under a flight/experiment? Might not be required if we can get this into 16.8 P1.
2. Do we need to add a user facing option to run open file analysis in-proc? Might be required for analyzers with VS dependencies, this option will unblock use of such analyzers while they are fixed to remove VS dependencies.

**Comment by mavasani** [comment]
@sharwell @vatsalyaagrawal I'd like to bring the open questions mentioned in the last comment to today's design meeting.

**Comment by sharwell** [comment]
> Do we need to add a user facing option to allow running open file analysis in-proc? Might be required for analyzers with VS dependencies, this option will unblock use of such analyzers while they are fixed to remove VS dependencies.

If we have this option, it should apply for all uses of a VSIX-installed analyzer, and not just for open files. Either the analyzer works out-of-process, or it does not. There is no notion of an analyzer that requires in-process execution only for its open document analysis.

**Comment by jmarolf** [comment]
Design Review:
- For 16.7 in-proc still supported. 
- For 16.8 onwards we will not support in proc. 
- For 16.9 we would like to have an answer on how to accomplish same in-proc tasks, but for OOP. 
- Can potentially gold-bar known analyzers that have issues that we might be breaking.
