### ISSUE TITLE
NullReferenceException using CodeSpaces/CloudEnv Code Cleanup in client compliant mode

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#44409]
**Version Used**: 
![image](https://user-images.githubusercontent.com/5387680/82396042-d193f180-9a01-11ea-9095-45738d8e123e.png)

**Steps to Reproduce**:

1. Open a cloud environment with a C# solution in client compliant mode.
2. Open solution.
3. Open a C# file.

**Expected Behavior**:
Code cleanup 'broom' command is not visible because it is not yet supported.

**Actual Behavior**:
Code cleanup command is visible because a Roslyn provider is registered.

Attempts to invoke code cleanup throw a NullReferenceException

```
<entry>
    <record>3313</record>
    <time>2020/05/20 00:58:56.224</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpCodeCleanUpFixer.&lt;FixDocumentAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpCodeCleanUpFixer.&lt;&gt;c__DisplayClass11_0.&lt;&lt;FixTextBufferAsync&gt;g__ApplyFixAsync|0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServices.CSharp.LanguageService.CSharpCodeCleanUpFixer.&lt;FixAsync&gt;d__12.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CodeCleanup.CodeCleanUpCommandHandlerBase.&lt;ExecuteFixer&gt;d__29.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**cc:** @dibarbet, @olegtk.

**Comment by gundermanc** [comment]
Interestingly, I saw this in 'PPE Internal Staging,' but I am not seeing this in 'PPE Internal'. Perhaps the problem here was somehow caused by the failure of the LiveShare LSP server to start.

**Comment by dibarbet** [comment]
@gundermanc as far as I can tell this doesn't throw anymore.  But I'm not exactly sure how to get rid of the broom - for the short term roslyn will be on the client.  I don't know of a way to conditionally export our provider.  I tried returning an empty list of fixers from GetFixers when connected, but the broom still shows.

**Comment by gundermanc** [comment]
Perhaps @crmann1 or @olegtk know of a way.

**Comment by olegtk** [comment]
That's a common editor extensibility issue in Nexus, similar to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1120900. We use the presence of the provider as an indication that a feature is supported, which is poor assumption in Nexus. @davidsh is working on designing a better way.

**Comment by allisonchou** [comment]
@olegtk @davidsh Is there an update on being able to hide these unsupported features (specifically the broom in code cleanup)?

**Comment by olegtk** [comment]
@allisonchou not really, but we can at least disable feature by feature if they are not supported in Nexus. Please file a bug and we can do that.

**Comment by allisonchou** [comment]
@olegtk Thanks! Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1240575.
