### ISSUE TITLE
CS8602 CS8604 analysis are not correct after Visual Studio is upgrated to 16.6.0

### ISSUE THREAD

**Issue by walterlv** [dotnet/roslyn#44411]
**Version Used**: 

Visual Studio 16.6.0

**Steps to Reproduce**:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var foo = GetNotNullObject();

        Task.Run(() => Bar());
        Task.Run(() => Baz());

        void Bar() => VerifyNotNull(foo);
        void Baz() => Console.WriteLine(foo.ToString());
    }

    private static object GetNotNullObject() => new object();

    private static bool VerifyNotNull(object instance) => instance != null;
}
```

Just create such code in Visual Studio 16.6.0 and you'll get the wrong CS8602 and CS8604 warning. Before I upgrade to 16.6.0 (e.g. 16.5.4 ) the analysis works fine.

See the minimal reproduction repo: [walterlv/Walterlv.Issues.CSharpNullableCS8604](https://github.com/walterlv/Walterlv.Issues.CSharpNullableCS8604)

**Expected Behavior**:

The `foo` variable is analyzed as not null.

**Actual Behavior**:

The `foo` variable is analyzed as nullable and there is a warning during the compiling.

![image](https://user-images.githubusercontent.com/9959623/82422928-aa96f780-9ab5-11ea-82e6-ba5cf4a08a7a.png)

**Comment by Kybs0** [comment]
good job

**Comment by mthamil** [comment]
I've run in to this issue as well:
```c#
Func<object> factory = ...
var x = factory();
```
When I pass `x` to other methods later where a non-nullable reference is expected, I get errors.
If I change `var` to an explict `object` declaration, the errors go away.

**Comment by mthamil** [comment]
Seems like this may be the same or a related issue: https://github.com/dotnet/roslyn/issues/41705

**Comment by RikkiGibson** [comment]
One of the warnings in #41689 has the same root cause as this bug. Specifically, the single last warning that is called out in the issue description.
