### ISSUE TITLE
Support block (multil ine) expression in pattern matching

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/roslyn#44414]
**Version Used**: C# 8

At the moment the following is not possible:
```csharp
            return list.Count switch
            {
                0 => null,
                1 => list[0],
                _ => {
                    LogError();
                    return null;
                }
            };
```
I get `Invalid expression term '{'`

The obvious workaround here is defining a quick little private function.

**Comment by CyrusNajmabadi** [comment]
Closing out.  THis is a language request.  Those should go to dotnet/csharplang.  Thanks!
