### ISSUE TITLE
determine whether dlls in the samples need to be signed.

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4442]
we see some of dlls in the samples are not signed. we need to decide whether we want to sign them or not.

**Comment by tmeschter** [comment]
@heejaechang They only need to be signed if we're distributing the binaries (e.g. NuGet, VSIX, installed with VS, etc.).

A bigger question is whether or not we should even keep the samples; many are out of date.

**Comment by heejaechang** [comment]
@tmeschter I think we have vsix (or nuget, can't remember) for samples. are those still needed? not sure who decide what is needed or not.

**Comment by ManishJayaswal** [comment]
@AnthonyDGreen What do you think?

**Comment by davkean** [comment]
We don't ship the samples - so there's no need to sign them.
