### ISSUE TITLE
Improvements to quick action "Generate Property 'xy'"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44424]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1037029/improvements-to-quick-action-generate-property-xy.html)._

---
I have a xunit file with an auto-generated class (Counter) and a missing property (Counter.Name) for this class. My codes looks as following

```
public class CounterTests
{
	[Fact]
	public void HasName()
	{
		var name = "Counter Name";
		var counter = new Counter();

Assert.Equal(name, counter. Name);
	}
}

public class Counter
{
	public Counter()
	{
	}
}
```

counter. Name is underlined in red, because the property is missing. When I use quick action and select "Generate Property 'Counter.Name'" I'd assume it would create a property of type string.
Instead I got `public IEnumerable<char> Name { get; internal set; } `

Since I'm using Assert.Equal() with a string, the Visual Studio Generator should be able to understand that in most cases you want a string property generated and not `IEnumerable<char>`.

---
#### Visual Studio Feedback System on 5/19/2020, 02:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment]
Design meeting notes
The type inference engine should be updated to look at the other parameters to find an overload using types with identity conversions to the parameter.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
