### ISSUE TITLE
IBuildEngine7 is not provided in Microsoft.Build.Framework

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/roslyn#44427]
**Version Used**: 16.5.0

**Steps to Reproduce**:

1. Use 3.6 version of roslyn nuget packages which are using IBuildEngine7 under the hood.

**Expected Behavior**:

MsbuildWorkspace and other roslyn features should work

**Actual Behavior**:

TypeLoadException because IBuildEngine7 is not located in Microsoft.Build.Framework

It's not complicated to test! just install Microsoft.Build.Framework in any project and IBuildEngine6 is the most recent version of IBuildEngine you can find!

**Comment by jmarolf** [comment]
@ysmoradi looking into fixing this but could use some help. Are you referencing _both_ the latest MSBuildWorkspace version and Microsoft.Build.Framework? Can you explain to me why you are doing that?

**Comment by ysmoradi** [comment]
I'm fine with 3.7

**Comment by jmarolf** [comment]
ah, I'll close this as fixed than
