### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpCodeGenerationService.AddMethod should be adjusted to deal with "Top-level statements"

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#44425]
```
        protected override TDeclarationNode AddMethod<TDeclarationNode>(TDeclarationNode destination, IMethodSymbol method, CodeGenerationOptions options, IList<bool> availableIndices)
        {
            // PROTOTYPE(TopLevelStatements): Add handling for top level statements
            if (destination is GlobalStatementSyntax)
            {
                return destination;
            }
```

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by sharwell** [comment]
I'm not sure what the impact here is. I would expect the following two cases to be consolidated:

https://github.com/dotnet/roslyn/blob/fd30767422919dd770a45e952c2c0d61413a7046/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs#L111-L115

https://github.com/dotnet/roslyn/blob/fd30767422919dd770a45e952c2c0d61413a7046/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs#L172-L176

**Comment by CyrusNajmabadi** [comment]
Closing out.  We haven't had a need for this at all.
