### ISSUE TITLE
Diagnostic suppressor no longer suppresses

### ISSUE THREAD

**Issue by nschuessler** [dotnet/roslyn#44444]
**Version Used**: 
16.6 / Roslyn 3.5
**Steps to Reproduce**:

1.  Upgrade to 16.6
2. Open a solution with previous analyzers, suppressor, and visual studio extension
3.  The diagnostics show up even when they should be suppressed.

**Expected Behavior**:

Suppressor implementation should suppress issues to reduce verbosity of errors in the UI.

**Actual Behavior**:

Our extensions released 5/6 and the current ones no longer suppress diagnostics they used to after upgrading to 16.6.  In the debugger, setting a breakpoint on `ReportSuppressions`, it never gets triggered, although the DLL is loaded and breakpoint is indicated as fine.

This is kinda critical in that our analyzers are rolled out to hundreds of people and they will just disable our tools when it starts to annoy them (i.e. in their test code).  Also our IT department is force upgrading everyone to 16.6 so they will all see it shortly.

@mavasani asked me to tag him for this issue.

Is there a way to debug the loading/initialization of the suppressor that extension developers can do themselves?

**Comment by mavasani** [comment]
I will investigate, thanks

**Comment by mavasani** [comment]
@nschuessler Are the suppressors not working just in IDE live analysis or even from command line builds?

**Comment by nschuessler** [comment]
@mavasani  will check and update the thread

**Comment by mavasani** [comment]
@nschuessler Any luck? Did you figure out if this happens only with suppressors in VSIX?

**Comment by nschuessler** [comment]
@mavasani Trying to get a smaller isolated repro that I can share.  But it seems to work on small test cases that I make up.

**Comment by nschuessler** [comment]
Could it be affected by a Warning as error configuration ? Basically when warnings are errors they can't be suppressed anymore?

**Comment by nschuessler** [comment]
The solution that repros treats warnings as errors, and has a `.ruleset` file that does not mention any of my rules.  I believe it is set to make anything not mentioned as an error.
I see that ruleset files are now considered obsolete to be replaced by `.editorconfig` files.

**Comment by mavasani** [comment]
@nschuessler I believe that should not matter. Below are the criteria for analyzer diagnostics that can be suppressed by suppressors: https://github.com/dotnet/roslyn/blob/51b9c3a71ec5bd8de43aa759a520cb753cc01496/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1469-L1479

**Comment by mavasani** [comment]
> The solution that repros treats warnings as errors, and has a .ruleset file that does not mention any of my rules. I believe it is set to make anything not mentioned as an error.

Even if you have a repro with rulesets, please do share - it would likely provide enough data for us to investigate.

**Comment by nschuessler** [comment]
@mavasani Suggested that in 16.6 analyzers have moved out of process (or some work has been done) so it may be a DLL loading issue.  After separating the binary with the suppressor into a standalone binary, we are getting the following:

```

A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.CPR.VisualStudio.Extension.VsixExtension". ---> System.IO.FileNotFoundException: Could not find file 'C:\Repos\bothell\tmp\VS\AnalyzerAssemblyLoader\1627a7c9b9584cc39a2f17fdffe0b1fd\22\extension.vsixmanifest'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)   at System.Xml.XmlTextReaderImpl.FinishInitUriString()   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)   at Microsoft.CPR.VisualStudio.Extension.VsixExtension..ctor(String vsixManifestPath)   at Microsoft.CPR.VisualStudio.Extension.VsixExtension..ctor()   --- End of inner exception stack trace ---   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--
```

Note that path `'C:\Repos\bothell\tmp\` is a redirected TEMP directory that is used when opening the solution from the build window. I tried copying the `extension.vsixmanifest` file to that location, but it appears that directory is cleared upon startup of visual studio so the error re-occurrs.  Tips?

**Comment by nschuessler** [comment]
@mavasani Yeah, that is basically what we did. We pull the suppressor into a nuget package. And consumed the nuget from the VSIX that installs both the suppressor analyzer and the visual studio extension.  The suppressor DLL is an independent binary, but not independent vsix. Does that matter? There may be some dependency we missed though.

Even if we solve all these problems and get the suppressor to load, by moving it out of proc with no initialization, Visual Studio design is basically saying that you cannot access any external data sources to make suppression decisions.  I.e., how do you initialize configuration/auth to connect to azure or an in proc RPC server to get data? How can I get a .json file copied to where the suppressor and find it and open it? How do you debug startup (i.e. set a breakpoint in the constructor of the Suppressor) of the analyzer process?  

We ran into all these problems with the code lense api which suggested an in proc JsonRPC interface to get the data. Same solution or different for analyzers out of proc?

**Comment by sharwell** [comment]
> how do you initialize configuration/auth to connect to azure or an in proc RPC server to get data

Additional files are the only truly supported way to get data into an analyzer. You can set up a build task to extract the information necessary to initialize the analyzer or suppressor and place it into a document, and then add that document to your compilation as an additional file.

**Comment by nschuessler** [comment]
Closing this issue.  We separated out the suppressor into a separate DLL to ensure it had no UI dependencies, and then applied a fix for VSIX / Nuget loading and apart from being forced to always run out of proc (separate issue) it worked in 16.8.
