### ISSUE TITLE
Proposal:  Asynchronous Pattern Pattern Matching

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#4444]
Synchronizing the results of multiple asynchronous operations can be a difficult task, particularly if the behavior depends on which tasks are completed first.  The discussion of pattern matching in C# (proposal #206) got me thinking of asynchronous patterns and how they were addressed in the Microsoft Research project Cω (proposal #1165).  I think that combining the concepts would be an interesting way to provide pattern matching capabilities to asynchronous patterns.

The `match await` keywords are followed by a block containing the different pattern combinations to match.  Each pattern is an asynchronous operation, such as `Task<T>`, although they could be anything that adheres to the awaitable pattern.  For tasks that return a result that result can be matched through the `var` pattern to capture the result, the wildcard pattern to discard the result or any sub-pattern.

Multiple tasks can be awaited as a single pattern.  They can be combined using either the `&` or `|` operators to define that any or all of the tasks must complete in order for the pattern to be considered matched.  Any number of tasks can be joined together into a single composite pattern.

When using the `|` operator `var` or type patterns may be repeated to the same identifier name as long as they are of the same type.  That variable will be assigned only the value of the first task to have completed.

When using the `&` operator there can be any number of `var` or type patterns and all of the matched variables will be assigned.

Here's a conceptual syntax to illustrate the concept:

```cs
public async Task<string> GetDataAsync(string id) {
    Task<string> op1 = ...;
    Task<string> op2 = ...;
    Task<string> op3 = ...;
    Task<string> op4 = ...;
    Task<string> op5 = ...;
    Task<int> op6 = ...;
    Task<object> op7 = ...;
    Task timeout = Task.Delay(1000);

    // awaits until the first of the following asynchronous patterns complete
    // sets the value of finalResult with the value returned by the expression
    // for the matched expression
    string finalResult = match await {
        // await a single task capturing the result
        case op1(var result)
            => $"op1 completed first and the result is: {result}",

        // await a single task discarding the result
        case op2(*)
            => "op2 completed first and I don't care about the result",

        // await either task capturing the first result
        case op3(var result) | op4(var result)
            => $"Either op3 or op4 completed first and that result is: {result}!",

        // await both tasks and capture both results
        case op5(var result) & op6(var number)
            => $"Both op5 and op6 completed first and the results are: {result} and {number}!"

        // await the task and match only if the result is a string
        case op7(string result)
            => $"op6 has completed the the result is a string that is: {result}",

        // await the task that has no result
        case timeout => "Oops, the operation timed out."
    };

    return finalResult;
}
```

Sorry, this is kind of raw.  I wanted to get something down that I could iterate on.  It's quite possible that something like this could be done a lot cleaner through some pattern helper methods, but I think that would still rely on the `switch`/`match` statements to be capable of handling asynchronous patterns in some fundamental form.

**Comment by CyrusNajmabadi** [comment]
I'm not sure this is any cleaner than:

```c#
Task<string> op1 = ...;
    Task<string> op2 = ...;
    Task<string> op3 = ...;
    Task<string> op4 = ...;
    Task<string> op5 = ...;
    Task<int> op6 = ...;
    Task<object> op7 = ...;
    Task timeout = Task.Delay(1000);

    Task op3OrOp4 = Task.WhenAny(op3, op4);
    Task op5AndOp6 = Task.WhenAll(op5, op6);

    await Task.WhenAny(op1, op2, op3OrOp4, op5AndOp6, op7);
    if (op1.Status == RanToCompletion) { return "Op1 completed blah blah blah" }
    ....
```

**Comment by gafter** [comment]
This was explored in #5187 and ultimately dropped.
