### ISSUE TITLE
'new' keyword not suggested after 'a ? expr |'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44443]
**Steps to Reproduce**:

Invoke completion at `$$` in the following top-level statement:

```csharp
a ? expr | $$
```

**Expected Behavior**:

The `new` keyword is offered.

**Actual Behavior**:

The `new` keyword is not offered.

📝 A test for this exists in `NewKeywordRecommenderTests` but is disabled.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
