### ISSUE TITLE
RemoteEndPoint.ConnectPipeAsync needs a backoff algorithm

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44465]
https://github.com/dotnet/roslyn/blob/ed310b2aa13b59f47b5c442eb15ba00eb8f97390/src/Workspaces/Remote/ServiceHub/Shared/RemoteEndPoint.cs#L280-L281

Performance traces show situations where thousands of timeout exception are thrown within this method (one case today had 158/second), with heavy CPU overhead related to updating timer queues.

**Comment by CyrusNajmabadi** [comment]
Tagging @tmat .  It honestly seems weird that we need any of this code.  It's alsnot clear to me why we just don't use pipe.ConnectAsync...

**Comment by tmat** [comment]
We will be able to remote this once this is implemented: https://github.com/dotnet/roslyn/issues/44326

**Comment by sharwell** [comment]
@tmat This appeared in https://developercommunity.visualstudio.com/content/problem/1064841/visual-studio-resharper-with-no-solution-max-out-c.html today

**Comment by tmat** [comment]
Working on it. Requires some significant changes.

**Comment by tmat** [comment]
This API is now obsolete. ISB alternative does not have this issue.
