### ISSUE TITLE
Problems trying to build Roslyn

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4447]
With latest Master, and released version of VS Enterprise 2015, following latest instructions I get the follows 5 warnings and 278626 errors.
The command " "C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Debug\BoundTreeGenerator.exe" C# BoundTree\BoundNodes.xml C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\CSharpCodeAnalysis\Debug\BoundNodes.xml.Generated.cs" exited with code 1.	CSharpCodeAnalysis		
Warning		The command " "C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Debug\\BoundTreeGenerator.exe" VB BoundTree\BoundNodes.xml C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\BoundNodes.xml.Generated.vb" exited with code 1.	BasicCodeAnalysis		
Warning		The command " "C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Debug\\VBSyntaxGenerator.exe" ..\..\Portable\Syntax\Syntax.xml C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicCompilerSyntaxTest\Debug\\Syntax.xml.Generated.vb /test" exited with code 1.	BasicCompilerSyntaxTest		
Warning		The command ""C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Debug\NetFX20\..\VBSyntaxGenerator.exe" ..\..\..\..\..\Compilers\VisualBasic\Portable\Syntax\Syntax.xml C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicResultProvider.NetFX20\Debug\\Syntax.xml.Generated.vb /gettext" exited with code 1.	BasicResultProvider.NetFX20		
Warning		The command ""C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Debug\VBSyntaxGenerator.exe" ..\..\..\..\..\Compilers\VisualBasic\Portable\Syntax\Syntax.xml C:\Users\Paul\Documents\Visual Studio 2015\Projects\roslyn\Binaries\Obj\BasicResultProvider.Portable\Debug\\Syntax.xml.Generated.vb /gettext" exited with code 1.	BasicResultProvider.Portable

**Comment by Pilchie** [comment]
Can you post a build log with Diagnostic Verbosity?

**Comment by paul1956** [comment]
Yes if someone provides directions

**Comment by Pilchie** [comment]
1. In VS, go to Tools\Options\Projects and Solutions\Build and Run and change the "MSBuild project build output verbosity" to Diagnostic.
2. Open the Output Window
3. Post the contents somewhere.

**Comment by paul1956** [comment]
Results from Error Window and Output windows

https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!13015&authkey=!ANostR190PAX5vE&ithint=file%2ctxt

https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!13014&authkey=!ADDvfYZJlxgUPeQ&ithint=file%2ctxt

**Comment by paul1956** [comment]
I realized that the Diagnostic file was missing the beginning, because the output buffer must have a limited size. So now the file above has the output from minimal and the link below has as much output as the buffer will hold.

https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!13018&authkey=!AG6Fp4Su3P35gsQ&ithint=file%2ctxt

**Comment by Pilchie** [comment]
The problem here appears to be related to #3442.  It looks like our invocations of the syntax and bound tree generators don't properly quote their command line arguments, sobuilding doesn't work if you have spaces in the path where you enlist.

**Comment by paul1956** [comment]
Is this something I can fix without renaming a bunch of directories or moving project.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by Pilchie** [comment]
You could take a look at our build tasks and targets to try to fix the bug, but I'm not sure if that's easier than moving the directory where you cloned Roslyn.

**Comment by paul1956** [comment]
After moving to path with no spaces I still get 1299 Errors on build plus.29 warnings about fakeSign,

I have update the file with the Output window set to Detailed (so you get the whole thing)
https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!13014&authkey=!ADDvfYZJlxgUPeQ&ithint=file%2ctxt

Let me know if you want me to post the partial Diagnostic window.

![image](https://cloud.githubusercontent.com/assets/12789369/9213651/ef8846bc-4049-11e5-8927-48d0e07982e0.png)

Severity	Code	Description	Project	File	Line
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\ServicesVisualStudio\Debug\Microsoft.VisualStudio.LanguageServices.dll"" exited with code 1.	ServicesVisualStudio	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\BasicVisualStudio\Debug\Microsoft.VisualStudio.LanguageServices.VisualBasic.dll"" exited with code 1.	BasicVisualStudio	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\CSharpVisualStudio\Debug\Microsoft.VisualStudio.LanguageServices.CSharp.dll"" exited with code 1.	CSharpVisualStudio	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\EditorFeatures\Debug\Microsoft.CodeAnalysis.EditorFeatures.dll"" exited with code 1.	EditorFeatures (EditorFeatures\EditorFeatures)	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\ServicesVisualStudioImpl\Debug\Microsoft.VisualStudio.LanguageServices.Implementation.dll"" exited with code 1.	ServicesVisualStudioImpl	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The command "C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\..\..\packages\FakeSign.0.9.2\tools\FakeSign.exe "C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Obj\SyntaxVisualizerControl\Debug\Roslyn.SyntaxVisualizer.Control.dll"" exited with code 1.	SyntaxVisualizerControl	C:\Users\Paul\Documents\GitHub\roslyn\build\Targets\VSL.Imports.targets	284
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ExpressionCompiler		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicExpressionCompiler		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpExpressionCompiler		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ExpressionCompilerTestUtilities		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicExpressionCompilerTest		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpExpressionCompilerTest		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	ResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	ResultProviderTestUtilities		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	BasicResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	BasicResultProviderTest		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	CSharpResultProvider.Portable		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	CSharpResultProviderTest		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	ResultProvider.NetFX20		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	BasicResultProvider.NetFX20		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Engine.dll' could not be found.	CSharpResultProvider.NetFX20		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	ResultProvider.NetFX20		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	BasicResultProvider.NetFX20		
Warning		The referenced component 'C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll' could not be found.	CSharpResultProvider.NetFX20		
Warning		The referenced component 'Roslyn.Test.Utilities' could not be found.	BasicCompilerEmitTest		
Warning		The referenced component 'System.Collections' could not be found.	CSharpFeatures

**Comment by Pilchie** [comment]
None of those FakeSign issues appear in the log you posted.  However, the root of the problem in that log seems to be 
```
11>  C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ilasm.exe /dll /quiet /mdv:v2.0.50727 "/output:C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll" C:\Users\Paul\Documents\GitHub\roslyn\src\ExpressionEvaluator\Core\Source\Concord\Microsoft.VisualStudio.Debugger.Metadata.NetFX20.il
11>  Could not create output file, error code=0x80070005
11>  
11>  ***** FAILURE ***** 
11>C:\Users\Paul\Documents\GitHub\roslyn\src\ExpressionEvaluator\Core\Source\Concord\Concord.csproj(40,5): error MSB3073: The command "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ilasm.exe /dll /quiet /mdv:v2.0.50727 "/output:C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll" C:\Users\Paul\Documents\GitHub\roslyn\src\ExpressionEvaluator\Core\Source\Concord\Microsoft.VisualStudio.Debugger.Metadata.NetFX20.il" exited with code 1.
```

The error code 0x80070005 is Access Denied.  

Can you verify that the output directory in that command exists and you can write to it?  Do you have  a virus scanner running that could be interfering with disk operations?

**Comment by paul1956** [comment]
I assume "/output:C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll" is the output directory you are referring to and it looks to me like the first " is in the wrong place. Shouldn't it be before the C: as in /output:"C:

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by Pilchie** [comment]
It usually doesn't matter in argument processing on windows.

**Comment by paul1956** [comment]
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll" is read only and I if I try to change it just goes back to read-only. I have check the disk and there is nothing wrong.

 

When I run just the failing command I get access denied but when I run it under an Admin Command Prompt it returns 0x8013141c


CORSEC_E_CONTAINER_NOT_FOUND 

0x8013141c

CA reference to CA definition in same assembly.

 



 

I created a new Azure Visual Studio VM cloned Roslyn with GitHub for Windows and the directory (as shown above) is Read-Only) the same as on Windows 10.

 

Steps to Reproduce build failure

1.       Create New Azure Visual Studio Enterprise 2015 Rel VM or new Windows 10 installation

2.       Open Developer Command Prompt for VS2015

3.       Clone https://github.com/dotnet/roslyn 

4.       Change directory to  <clone dir>  and run  powershell .nuget\NuGetRestore.ps1  

5.       Open Roslyn.sln

6.       ReBuild Solution

Expected

                Build succeeds

Actual

                Build fails though with different errors and warning than on Windows 10.

**Comment by paul1956** [comment]
I also verified I can create Microsoft.VisualStudio.Debugger.Metadata.dll in C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\NetFX20 without issues from Explorer.

**Comment by Pilchie** [comment]
@jaredpar any ideas about the security container stuff?

**Comment by jaredpar** [comment]
Here is the container error:

```
CORSEC_E_CONTAINER_NOT_FOUND
0x8013141c
CA reference to CA definition in same assembly.
```

I believe that indicates an issue with the security chain on the local machine.  This is not my area of expertise though.

**Comment by paul1956** [comment]
I ran Scan Disk and it finds no issue, copied all the files to a NEW USB external drive, same error, can’t built on new Azure VM with VS preinstalled from Microsoft. I am really doubting this is my issue.

 


Severity

Code

Description

Project

File

Line


Error

 

The command "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\ilasm.exe /dll /quiet /mdv:v2.0.50727 "/output:E:\GitHub\roslyn\Binaries\Debug\NetFX20\Microsoft.VisualStudio.Debugger.Metadata.dll" E:\GitHub\roslyn\src\ExpressionEvaluator\Core\Source\Concord\Microsoft.VisualStudio.Debugger.Metadata.NetFX20.il" exited with code 1.

Concord

E:\GitHub\roslyn\src\ExpressionEvaluator\Core\Source\Concord\Concord.csproj

38

**Comment by paul1956** [comment]
The ilasm.exe problem with seems to only happen in Windows 10, the identical command on Windows Server 2012 R2 works as expected. I have tried it from Command Prompt and Admin Command Prompt and it fails on both, also writing to a freshly formatted Flash Drive so I don't really think it is really an access issue.

**Comment by jaredpar** [comment]
@paul1956 I just flattened my box and installed Windows 10 on Friday.  Will be trying out Roslyn on Monday so if this is a win 10 issue it should hopefully repro for me as well and I can track it down.

**Comment by jaredpar** [comment]
@paul1956 tried the build on clean Win10 this morning and it succeeded.  I think there must be something wrong with the certificate store on your box.  That seems to be the only explanation which meets the data we are seeing here.

**Comment by paul1956** [comment]
How do you repair a certificate store?

Why does it only affect this one command?

This command fails even from command prompt and even to a new flash drive. 

 I have no issues building any other applications.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by Pilchie** [comment]
The original issue around spaces in the path affecting FakeSign has been fixed by https://github.com/dotnet/roslyn/commit/1423adecbf377334ad6da40ddeb54ec62c267586.

**Comment by davkean** [comment]
@paul1956 Are you still running into issues?

**Comment by paul1956** [comment]
I gave up until yesterday when I tried with Update-1 and again found issues that I reported under #7226.

**Comment by davkean** [comment]
Going to close this as it looks like the issues you were running into are now resolved. If not, please open new issues.
