### ISSUE TITLE
modify automatic summary Tags template when using '///'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1030312/modify-automatic-summary-tags-template-when-using.html)._

---
Currenltly we have
when I type above function `///`
        
```
/// <summary>
        /// Bies the geometry.
        /// </summary>
        /// <param name="geometry">The geometry.</param>
        /// <param name="construction">The construction.</param>
        /// <param name="panelType">Type of the panel.</param>
        /// <returns>
        ///   <see cref="SAM.Analytical.Panel"/>
        /// </returns>
        public static SAM. Analytical.Panel ByGeometry(object geometry, SAM. Analytical.Construction construction, object panelType = null)
        {
```

would be possible to have ability to modify tempalte what is created?
I would like to add 
`/// <search></search>`

and  add `name=`  in return tag

so I have 

```
/// <summary>
        /// Bies the geometry.
        /// </summary>
        /// <param name="geometry">The geometry.</param>
        /// <param name="construction">The construction.</param>
        /// <param name="panelType">Type of the panel.</param>
        /// <returns name="panel">
        ///   <see cref="SAM.Analytical.Panel"/>
        /// </returns>
        /// <search>ByGeometry,</search>
        public static SAM. Analytical.Panel ByGeometry(object geometry, SAM. Analytical.Construction construction, object panelType = null)
        {
```

this is standard in AEC industry for Revit Dynamo and Rhino Grasshopper users
https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development

---
#### Visual Studio Feedback System on 5/13/2020, 11:34 PM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 5/14/2020, 01:18 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This is an interesting request. There are two things that make the details of this request challenging:

1. The value within `<search>` is not a constant value, so even if we could generate the element it would just be empty
2. The value within the 'name' attribute of `returns` is similar

My suggestion would be creating an analyzer package similar to [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers) which supports the custom elements for this tool. We recently added the ability to implement a completion provider within analyzer packages, so in addition to the analyzers you could create a tool similar to [EWSoftware/ExtendedDocCommentsProvider](https://github.com/EWSoftware/ExtendedDocCommentsProvider) to provide a complete experience for these projects.
