### ISSUE TITLE
Add code snippet "cr" for Console.ReadLine();

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44499]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1038485/add-code-snippet-cr-for-consolereadline.html)._

---
As the counterpart of "cw" for `Console.WriteLine();` I'd suggest to add the code snippet "cr" for `Console.ReadLine();`.
I know that you can define custom code snippets, but this would just complete it.

---
#### Visual Studio Feedback System on 5/20/2020, 02:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by jmarolf** [comment]
related to https://github.com/dotnet/roslyn/issues/56541

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not investing in snippets.
