### ISSUE TITLE
Reduce CS0564 and CS0019's level 降CS0564为警告级别

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44496]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1024554/reduce-cs0564s-level-1.html)._

---
<p>Could CS0564 be reduced to warning level in future versions?</p><p>Any operator(include operator &lt;&lt; and &gt;&gt;) that can be overloaded can give any other meaning in essence.Why do we overload these operators?Because we want to change it's meaning.So,the requirement of overloading &lt;&lt; and &gt;&gt; operator<strong> should be relaxed</strong>.It doesn't have to represent a shift.</p><p>I hope it will relaxed in the future versions and turn CS0564 and CS0019 into a warning level.</p><p>Thanks.&#128522;</p>

---
#### Visual Studio Feedback System on 5/11/2020, 01:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is a language request and needs to be filed over at dotnet/csharplang.
