### ISSUE TITLE
Simplify Fully Qualified Class Name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1029473/simplify-fully-qualified-class-name.html)._

---
From Jetbrains IDE PhpStorm there is a neat function to simplify a fully qualified class name.

Example: Microsoft.IdentityModel.Tokens.TokenValidationParameters

You then right-click on the class name and say "Simplify FQN" and it imports the namespace.
Regarding the previous example, this will result in:

using Microsoft.IdentityModel.Tokens;
TokenValidationParameters

In Visual Studio I'd just deleted the Namespace, then right-click on the class name -> Quick actions and refactorings and then select the option "using Microsoft.IdentityModel.Tokens;"

---
#### Roi Chen [MSFT] on 5/14/2020, 01:42 AM: 

<p>Thank you for taking the time to provide your suggestion.<br>
We will do some preliminary checks to make sure we can proceed further.<br>
We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
