### ISSUE TITLE
Incorrect IDE0007 (Use implicit type "var") for switch expressions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44507]
See https://github.com/dotnet/roslyn/pull/44491#discussion_r428850149. Applying the suggestion to var causes `error CS8506: No best type was found for the switch expression`

**Comment by CyrusNajmabadi** [comment]
Note: we likely need to prioritize this.  THis will hit anyone who has "must use var" set and then uses a switch-expression with type-inference.  

@jinujoseph maybe a good issue for @allisonchou to dive into?

**Comment by sharwell** [comment]
I just hit this while trying to update our code style analyzer package.
