### ISSUE TITLE
NameOf can't be used with anonymous types and Tuples

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#44503]
In both VB and C#, we can't use typeof keyword with members of anonymous type:

```VB.NET
Dim x = New With {.First = NameOf(First)}
```

```C#
var x = new {First = nameof(First)};
```

When hovering over `First` in both languages, the tip shows that it is recognized as a string property, so, why don't you allow using nameof?

The same happens with Tuples:

```VB.NET
Dim x = (First:=NameOf(First), Scnd:=NameOf(Scnd))
```

```C#
var x = (First: nameof(Scnd), Second: nameof(Scnd));
```

**Comment by CyrusNajmabadi** [comment]
Clsoing out.  This appears to be a language request.  Those should go to dotnet/vblang, thanks!

**Comment by VBAndCs** [comment]
I don't have time to double clone that. You should have an option to move it to VB and C#, or do it manually. I reported it, and it is now yours :).
Thanks.
