### ISSUE TITLE
RenameDocumentAsync() should return error when invalid characters.

### ISSUE THREAD

**Issue by ocallesp** [dotnet/roslyn#44515]
`CodeAnalysis.Rename.Renamer.RenameDocumentAsync`(newFileName) should return an error for GetErrors() on the action when newFileName contains invalid characters to avoid renaming symbols.

Remove [this implementation](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Rename/RenamerProjectTreeActionHandler.cs#L191) from dotnet Project System

**Comment by dibarbet** [comment]
Design meeting notes
Talk with project system to get more specific scenario to fix.

**Comment by jasonmalinowski** [comment]
@ryzngard @dibarbet What's the design question here? This seems pretty straightforward to me to just do it...?

**Comment by ryzngard** [comment]
Agreed, this seems pretty straight forward.

**Comment by jasonmalinowski** [comment]
Or at least, if there is need to bring this to the design meeting, it's not obvious to me what the question is. Maybe an implementation will make that obvious.

**Comment by dibarbet** [comment]
@jasonmalinowski from going back to the notes and the recording, there was some confusion on which scenario was problematic.

TryApply/rename should fail with invalid identifier name.  But rename will succeed if symbol rename works but file rename does not.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If this needs to be done it needs to be given to a dev/milestone for this to happen in.
