### ISSUE TITLE
Redundant Cast incorrect for SimpleArguments

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#44516]
**Version Used**: 
VS 16.6 and 16.7 Preview 1
**Steps to Reproduce**:
```VB
Dim X As New Point(CInt(Math.Floor(1.1)), 1)
Dim Y As New Point(CInt(1.1), 1)
```
**Expected Behavior**:
No Cast is Redundant messages
**Actual Behavior**:
Cast is Redundant messages and if you follow suggestion you get error BC30512 Option Strict On disallows implicit conversions from 'Double' to 'Integer'. This happens for all Math functions that return non integers and constants.

**Comment by Youssef1313** [comment]
To me, a good starting point to debug this seem to be from [here](https://github.com/dotnet/roslyn/blob/b61d9d2863eebfc76b032e5f8fcd0a918fb27147/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Utilities/CastAnalyzer.vb#L182)

**Comment by paul1956** [comment]
@Youssef1313 do you happen to know which test hits this code, that information is not easily available in community?
