### ISSUE TITLE
Opening solutions using MSBuildWorkspace mangles Environment.CurrentDirectory

### ISSUE THREAD

**Issue by smoogipoo** [dotnet/roslyn#44517]
**Version Used**: 

```
Microsoft.CodeAnalysis.CSharp.Workspaces: 3.6.0
Microsoft.CodeAnalysis.Workspaces.MSBuild: 3.6.0
Microsoft.CodeAnalysis.CSharp: 3.6.0
```

**Steps to Reproduce**:

1. Open a solution file using `MSBuildWorkspace.Create().OpenSolutionAsync()`.
2. Observe `Environment.CurrentDirectory` getting changed during the load.

```
new Thread(() =>
{
    while (true)
    {
        logger.Add(Environment.CurrentDirectory);
        Thread.Sleep(1);
    }
}).Start();

solution = await MSBuildWorkspace.Create().OpenSolutionAsync(solutionFile);
```

**Expected Behavior**:

`Environment.CurrentDirectory` should not be getting modified.

**Actual Behavior**:

`Environment.CurrentDirectory` changes to each project's directory in sequence. I've added progress during the load, here's the full log:

[dynamic-compilation.log](https://github.com/dotnet/roslyn/files/4666261/dynamic-compilation.log)

---

I'm not sure if this is specifically a Roslyn issue - on a very rudimentary look I can't find any code inside Roslyn that sets the current directory, but this is certainly the target site of our problem.  
It would be preferable if this could be fixed, but if not please advise and we'll look at removing usages of `Environment.CurrentDirectory` from our side instead.

**Comment by jasonmalinowski** [comment]
@rainersigwald MSBuild has to modify Environment.CurrentDirectory for combability when running tasks, I'd think, right?

**Comment by rainersigwald** [comment]
Yes, that's correct. Current working directory is mutable and inheritable and is specified at the project level: MSBuild defaults to project directory, but persists changes when leaving/returning to a project. This is one of the reasons that multithreaded build is not actually multithreaded but multi-_process_.

Roslyn might be able to work around this for API callers by forcing the design-time build out of proc into its own MSBuild.exe process, but that has lots of its own problems, so I don't think I recommend it.
