### ISSUE TITLE
Move Microsoft.CodeAnalysis.EditorFeatures.Cocoa.dll to dotnet/roslyn

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#44511]
The Visual Studio for Mac team has developed a Mac equivalent of Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll, but for the Mac flavor of the editor.

It makes sense to move it to the Roslyn repo so it builds and ships with Roslyn (perhaps in a separate NuGet package).

**Comment by jasonmalinowski** [comment]
@tmat OK to close or do you have other work before you want to call it done?

**Comment by tmat** [comment]
@jasonmalinowski https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/283665 is still pending.
