### ISSUE TITLE
Is there a method or a way in Roslyn to enumerate all assemblies used at compile time by a given C# project

### ISSUE THREAD

**Issue by Tahatoun** [dotnet/roslyn#44528]
I'm developing an application that detects and eliminates useless external references in a given C# project for example a package referenced but not used. For this I need to enumerate all assemblies used either at compile and runtime. For those used at a runtime, I can get names using reflection specifically calling Assembly.GetReferencedAssemblies(). But for those used only at compile-time I think that there is no way to list them without using Roslyn. Have you please any answers to my problematic?

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/44547

**Comment by Gouthamsanditi** [comment]
Hello @Tahatoun. Have you found a solution to enumerate the assemblies used only at compile-time in your C# project, or are you still looking for a solution?
