### ISSUE TITLE
Trying to write a second attribute in VB doesn't show type intellisense

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#44525]
**Version Used**: 3.7.0-2.20271.7+b6cfbdf26a2caa78c01dda64658de30f296fdce8

**Steps to Reproduce**:

1. Try typing a second attribute on a VB method after the first attribute, while it's on it's own line:

**Expected Behavior**: We get type Intellisense.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/201340/82705997-90802500-9c2d-11ea-9292-7bb7f2ceb0ee.png)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and unlikelihood of changing these experiences.
