### ISSUE TITLE
Allow 'uint', 'nuint', and possibly 'nint' for stackalloc lengths

### ISSUE THREAD

**Issue by john-h-k** [dotnet/roslyn#44536]
Apparently here might be the most suitable place for this cc @333fred 

Currently the only supported size operand of a `stackalloc T[size]` is an int. This is frustrating, particularly in interop scenarios where `uint` and `nuint` are your primary types. `stackalloc` takes an unsigned integer in IL anyway, so functionally there will be no difference, and it would be useful

**Comment by 333fred** [comment]
Dup of https://github.com/dotnet/roslyn/issues/44535
