### ISSUE TITLE
Unable to display formatted symbol name with `get_Item` (instead of `get_this`)

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#44544]
Given a method symbol, `methSym`, that is associated to a property indexer, the string directly printed by calling `methSym.Name` is `get_Item`.

This behavior is fine. What is unexpected (please let me know, if I'm missing an API) is that there doesn't seem to exist any option in [`SymbolDisplayFormat`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.symboldisplayformat?view=roslyn-dotnet) such that a call to `methSym.ToDisplayString(format)` yield a name **containing** `get_Item` -- in whatever exact format used. It'd always use the variation with `this`, e.g., `this.get`.

This prevents one from ensuring the same naming style with the same API. 

Again, if I'm missing some flag in `SymbolDisplayFormat`, I'd kindly appreciate if you let me know of it. Related: https://github.com/dotnet/roslyn/issues/27264

**Comment by ltcmelo** [comment]
Hum... it that this isn't just "related" to https://github.com/dotnet/roslyn/issues/27264, it's the same problem; just that the property here is `this`.

In any case, since I don't know the internals of the implementation, I'll leave this open, but if the case is an actual duplicate, I guess this one can be closed...?

**Comment by gafter** [comment]
There is currently no such API. I think it is fine to track this request in #27264.
