### ISSUE TITLE
Is there a way with Roslyn to get compile-time dependencies?

### ISSUE THREAD

**Issue by Tahatoun** [dotnet/roslyn#44547]
I'm developing a project to eliminate useless references in a C#. And I need to detect useless one during the compile-time. I can get the useful one during runtime by inspecting AssemblyRef table using reflection. But be based only in those assemblies presented in AssemblyRef will throw a lot of false positive. for example if we use a static const value presented in a reference,this reference will be considered useless which is not true. So I need also references used at the compile-time. Does Roslyn provide this references for a given project. Please @DustinCampbell and @gafter  I saw your responses in this issue [https://github.com/dotnet/roslyn/issues/625](https://github.com/dotnet/roslyn/issues/625) but I don't know if there is an update.
Thank you in advance

**Comment by gafter** [comment]
@AlekseyTs Can you please answer this?

**Comment by Tahatoun** [comment]
@AlekseyTs  Please can you answer my question? I really need the answer as soon as possible.
Thank you in advance

**Comment by AlekseyTs** [comment]
There is no easy way to get this information today. We have a prototype for an API that returns a set of used assembly references. It is in https://github.com/dotnet/roslyn/tree/features/UsedAssemblyReferences branch. However, at the moment we haven't made a decision when or whether it will become part of the product.
