### ISSUE TITLE
GenerateProperty/Field: consider adjusting behavior for positional records

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44557]
Before:
![image](https://user-images.githubusercontent.com/12466233/82925784-130d2b00-9f33-11ea-93ee-c5d6883096a8.png)

After:
![image](https://user-images.githubusercontent.com/12466233/82925872-320bbd00-9f33-11ea-8b09-535944ccd9c5.png)

Should we offer an option to generate a positional member?

Relates to https://github.com/dotnet/roslyn/issues/40726 (test plan for "records")

**Comment by CyrusNajmabadi** [comment]
This behavior is fine, and we haven't heard from any users about wanting things to be different.  So we'll keep this as is.
