### ISSUE TITLE
VS should offer to simplify null conditional calls

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#44554]
**Version Used**: 16.7 P1

**Steps to Reproduce**:
1. Write code
    ```csharp
    if (x != null)
    {
        x.Y();
    }
    ```
2. Try to invoke refactorings on it

**Expected Behavior**:
A refactoring is offered to turn this into
```csharp
x?.Y();
```

**Actual Behavior**:
No refactoring is offered

**Comment by jmarolf** [comment]
Design Meeting Notes
- would accept a PR for this feature

**Comment by Youssef1313** [comment]
This would be very similar to IDE1005

**Comment by CyrusNajmabadi** [comment]
This is offered:

![image](https://user-images.githubusercontent.com/4564579/199345112-09c91264-3f34-4e2b-905d-89a5915e99ae.png)
