### ISSUE TITLE
FindAllReferences should find usages of positional members

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44559]
Placing your cursor on a declaration of a positional should find usages in construction, property access (probably) and `with` initializers (not yet validated).

Note: we need to clarify whether the declaration of `First` is a parameter or a property (tracked by https://github.com/dotnet/roslyn/issues/44556)

```
data class Person(string First, string Last) // place cursor on "First" and invoke GoToReference
{
    Person(string other) { }
    void M()
    {
        var p = new Person(First: "some", Last: "one"); // expect this usage to be found
        _ = p.First; // also expect this usage to be found

        var p2 = new Person(other: ""); // doing the same thing on declaration of "other" finds this usage
    }
}

```

Relates to https://github.com/dotnet/roslyn/issues/40726 (test plan for "records")

**Comment by jcouv** [comment]
Tagging @CyrusNajmabadi Let's consider for 16.8.

**Comment by sharwell** [comment]
🔗 Also requested in AB#1246910

**Comment by Tragetaschen** [comment]
I wish this had a higher priority.

"Find All References" on the primary constructor parameter doesn't show anything while the same at property usage points back to the primary constructor parameter.

![image](https://user-images.githubusercontent.com/1947968/113122307-c873d380-9213-11eb-825d-5cebda6f9b3d.png)

**Comment by jnm2** [comment]
This is a several-times-a-week confounding event. Not sure there's a workaround other than changing the positional member name and trying to compile so that the compiler points out the usages.

**Comment by cremor** [comment]
I was redirected here from a bug on the Visual Studio Feedback site. I agree that this is very annoying. Could we please get a timeframe for when this will be fixed?

**Comment by CyrusNajmabadi** [comment]
@cremor this is currently on the backlog. So no timeframe can be given. We are trying to work through a compiler api to make this possible.

**Comment by vritant24** [comment]
+1 to this. Just ran into this and faling back to "Find All" string search in VS isn't that nice :/

**Comment by Davidsv** [comment]
From the perspective of a VS user, this appears like a bug when "Find all references" does not find all references. I hope this gets prioritized.

**Comment by cremor** [comment]
Side note: #52663 will be fixed in 17.2

I understand that the two issues are quite distinct from an implementation perspective, but from a user perspective it would be great to have a release that "fixes positional parameters".

**Comment by douglasg14b** [comment]
@sharwell What version is this fixed in? 

Is `next` 17.2?

**Comment by sharwell** [comment]
@douglasg14b I'm pretty sure 17.2, but not sure which preview it will first be included in
