### ISSUE TITLE
Figure out QuickInfo for positional records

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44556]
Some places display parameters and others display properties. This also affects FAR.
We need to clarify the desired behavior.

I would propose that we keep the current behavior (some places are parameters and some are properties), but extend FAR to link both world.

----

There is currently no QuickInfo on declaration:
![image](https://user-images.githubusercontent.com/12466233/82924511-4b136e80-9f31-11ea-9ef6-c9cb757b0763.png)

In construction, we show "parameters":
![image](https://user-images.githubusercontent.com/12466233/82924627-7433ff00-9f31-11ea-9711-eac7d3f79911.png)

But in other usage, we show "properties":
![image](https://user-images.githubusercontent.com/12466233/82924675-86ae3880-9f31-11ea-8785-291ccff13edb.png)

I assume that the `with` expression (after syntax change) will display them as "properties" as well. (I'll verify after latest syntax change)

Relates to https://github.com/dotnet/roslyn/issues/40726 (test plan for "records")

**Comment by sharwell** [comment]
@jcouv Can you move this to the **Next Meeting** column of the design review project when the proposal is ready to be presented?

**Comment by jmarolf** [comment]
Design Meeting Notes:

- Case 1: Show as a parameter
- Case 2: It should show as a property
- Case 3: It should show as a property
- Cascade: yes

**Comment by CyrusNajmabadi** [comment]
Works fine here:

![image](https://user-images.githubusercontent.com/4564579/222295863-1d961c38-92ea-4f47-8fec-301f0805d66f.png)
