### ISSUE TITLE
Rename tracking doesn't work on positional members

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44560]
![image](https://user-images.githubusercontent.com/12466233/82928028-76e52300-9f36-11ea-91a2-b36daf6f5a4f.png)

# Scenario 1 (trigger rename from parameter list in declaration):
```
record Person(string First, string Second); // change `Second` to `Renamed`

// corresponding synthesized code
class Person
{
     public Person(string First, string Second) { this.First = First; this.Second = Second; } // synthesized primary constructor
     string First { get; init; } 
     string Second { get; init; } 
     ...
}

```
Expected:
```
Person p = new Person(First: "", Second: ""); // `Second` should be renamed here (works!)
_ = p.Second; // property `Second` should be renamed too

record Student(string First, string Second, int Id) : Base(First: First, Second: Second); // `Second:` should renamed too, like `Student.Second` should be renamed as well (same property, but good to confirm with IDE design)
```

# Scenario 2 (trigger rename from parameter list in declaration, with user-defined property):
```
record Person(string First, string Second) // `Second` here is just a parameter, no longer refers to property
{
    public string Second { get { ... } init { ... } } = Second /* parameter */;
}
```
Expected:
```
// same changes as in scenario 1
// we should rename the user-defined property as well (need to confirm with IDE design review)
```

# Scenario 3 (trigger from usage site):
```
Person p = new Person(First: "", Second: ""); // trigger the rename from `Second:`
_ = p.Second; // trigger the rename from usage of the property
```
```
record Person(string First, string Second)
{
    public string Second { get { ... } init { ... } } = Second /* parameter */; // trigger rename from property declaration
}
```

# Misc

How do link parameter and property symbols?
1. add a compiler API (for example `.AssociateSymbol`, problematic because of language design and metadata)
2. do it manually (syntax shows that we have "record", you can tell which constructor is primary, allows us to find corresponding properties)

Relates to https://github.com/dotnet/roslyn/issues/40726 (test plan for "records")

**Comment by jinujoseph** [comment]
cc @ryzngard

**Comment by jcouv** [comment]
@ryzngard I suspect we'll need to fix FAR as part of fixing this. Issue for FAR: https://github.com/dotnet/roslyn/issues/44559 (need to cascade various record symbols together)
When you're ready to look at this, ping me and I'll walk you through the records concepts.

**Comment by TahirAhmadov** [comment]
@jcouv the linked https://github.com/dotnet/roslyn/issues/44559 was fixed in February 2022, but unfortunately this is still open...

**Comment by ryzngard** [comment]
Removing myself since I'm no longer on the team (and don't have dedicated time to fix this issue). @Cosifne heads up :) I'll let you decide who this should be assigned to

**Comment by TahirAhmadov** [comment]
@jcouv correct, this issue has not been fixed; I was referring to the dependency issue https://github.com/dotnet/roslyn/issues/44559.

But more importantly I misdirected my "follow up" at you, the reporter, and not @ryzngard, who had been the assignee up until an hour ago. :)

**Comment by Cosifne** [comment]
From the description of the PR, I believe it is fixed in 
https://github.com/dotnet/roslyn/pull/74168

**Comment by Cosifne** [comment]
I tested the build after https://github.com/dotnet/roslyn/pull/74168
All secnario are working
