### ISSUE TITLE
MetadataAsSource: should record types be displayed as records?

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44566]
I don't think that's possible at the moment (record types are not marked as such, they are just regular types).
Tagging @agocke @CyrusNajmabadi  for thought

Note: this should not block 16.7p3 release of records preview, in my opinion.

Tentatively, we could use the unspeakable clone method (`<>Clone`) as a way to detect record type.

Note: for init-only properties, we've [already fixed MetadataAsSource](https://github.com/dotnet/roslyn/pull/44077/files#diff-369b7c280028d6ad679b52f93d3ee849) to print out `init;` accessors.

Relates to https://github.com/dotnet/roslyn/issues/40726 (test plan for "records")

**Comment by CyrusNajmabadi** [comment]
Yes, i would expect this to display as a record in MAS.  Do we have any other cases of signature level features that don't have any impact on the generated code (outside of 'partial')?  

is there a mod-opt we could put on these just to mark things for useful tooling purposes?

**Comment by CyrusNajmabadi** [comment]
btw, how are xml docs going to work for records?  how do you put docs on the properties the record has?

**Comment by jcouv** [comment]
Filed https://github.com/dotnet/roslyn/issues/44571 for xml doc question (thanks!)

**Comment by Youssef1313** [comment]
`NamedTypeGenerator` changes in #50554 has fixed this. I'll add a test to make sure the behavior is completely correct. ie, which record members are shown and which are not.
