### ISSUE TITLE
Reneme class and it's filename from a different file works only when current file has same name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44576]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1048747/reneme-class-and-its-filename-from-a-different-fil.html)._

---
<p>I noticed quite odd behavior of rename class and filename feature in Visual Studio 2019 (16.7preview1 as I wrote this).</p>
<p>Please examine following scenarios<br>
1 - You can rename a file when renaming a class when you have that file open (that’s obvious and this works)<br>
2 - You cannot rename a file when class and file you're renaming matches but you're in a different file (i.e. renaming class&amp;file by renaming constructor usage) - error message is that file name does not mach.<br>
3 - You can rename class it's file from other file only if the file you’re in has same name.</p>
<p>It seems like the actual mechanism of file renaming works but the method for disabling “rename file” checkbox if faulty - it checks for current open file instead checking for name match on the actual file the class is in.</p>

---
#### Visual Studio Feedback System on 5/26/2020, 03:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/26/2020, 01:49 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by miqm** [comment]
@ryzngard has this fix been released in 16.7.0-preview3?

**Comment by ryzngard** [comment]
@miqm it didn't quite make it in to preview 3, but will be in preview 4.

**Comment by miqm** [comment]
works in 16.7-p4 :)
