### ISSUE TITLE
Code that compiles in VS2013 fails with CS0121 in 2015; overloads with different params parameter types

### ISSUE THREAD

**Issue by lassevk** [dotnet/roslyn#4458]
The following code compiles in VS2013 but in VS2015 it produces the following compiler error:

> CS0121: The call is ambiguous between the following methods or properties: 'Test.Test(int, params string[])' and 'Test.Test(int, params Expression<string>[])'

```cs
    using System.Linq.Expressions;

    namespace ConsoleApplication9
    {
        internal class Program
        {
            private static void Main(string[] args)
            {
                var x = new Test(10);
            }
        }

        public class Test
        {
            public Test(int a, params string[] p) { }
            public Test(int a, params Expression<string>[] p) { }
        }
    }
```

In VS2013 the call will be routed to the expression overload (observational fact, not 100% sure that will *always* happen though)

Arguably, this is not good design but it is still a backwards compatibility issue.

**Comment by gafter** [comment]
I don't know what Expression<string> is supposed to represent in this example. Expression's type argument is supposed to be a delegate type. But this issue still exists when using a delegate type

```cs
using System;
using System.Linq.Expressions;

namespace ConsoleApplication10
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var x = new Test(10);
        }
    }

    public class Test
    {
        public Test(int a, params Action[] p) { }
        public Test(int a, params Expression<Action>[] p) { }
    }
}
```

**Comment by gafter** [comment]
@AlekseyTs Can you please investigate?

**Comment by AlekseyTs** [comment]
@lassevk Could you share how did you find this issue? Is there widespread real API that is now cannot be consumed in manner it used to be?

**Comment by lassevk** [comment]
This was found in internal code, not in any public code.

Originally we had a method that created an object used for validation, and it had the following abbreviated signature:

    new Validator(...delegate..., "Property1", "Property2");

The final params string[] parameter was used to tell the system which properties it would listen for, if any of them changed, validation had to be rerun.

When refactoring we quickly discovered that renaming a property did not fix those strings, so a new overload was added:

    new Validator(...delegate..., () => Property1, () => Property2);

The new overload simply had params string[] replaced with params Expression<Func<object>>[], and then the method picked those expressions apart to discover the names of those properties. Refactoring now worked.

After having installed Visual Studio 2015 on my own machine, I changed a batch file that pulled in visual studio command line tools into the command prompt, if it was installed, and a command line build now used Visual Studio 2015 (roslyn) as the compiler, and gave me a few screens of red error messages.

I then discovered that for some reason, one-off validator objects had been created without supplying property names at all, ie. "abusing" the fact that params parameters can be left out. This is likely a bug in the creation of those validators.

The method overloads are borked, we will fix this internally by adding a requisite string parameter and expression parameter in front of the params parameter to enforce the contract that validators need to know which properties they're based on.

I then replicated the problem in a contrived example, hence Expression<Action> which I agree is nonsensical, I apologize for the confusion but as already noted this is not a problem with the Action part, this is just Roslyn being stricter.

In my opinion Roslyn is right, the old code is wrong, ambiguous, but since it compiles in VS2013 I thought I should post the issue in any case, it could be that this is something that warrants fixing, but most likely not.

**Comment by lassevk** [comment]
Though to answer your question in a different way. I would imagine writing a small program that would download all nuget packages and use reflection to pick them apart to see if there are overloads that only differ by params type would be doable, it would at least tell you the to which extent this *might* be a problem.

**Comment by gafter** [comment]
If we do not take a code change to duplicate the native compiler bug in Roslyn, we should instead document the change.

**Comment by AlekseyTs** [comment]
In the interest of the future health of our overload resolution code, we decided to keep the breaking (and correct) behavior. If we get more than this single case, we may want to reevaluate.

**Comment by gafter** [comment]
If we do not take a code change to duplicate the native compiler bug in Roslyn, we should instead document the change.

**Comment by gafter** [comment]
Documented in https://github.com/dotnet/roslyn/pull/4922
