### ISSUE TITLE
x !is int expression

### ISSUE THREAD

**Issue by SomebodyOdd** [dotnet/roslyn#44591]
**Version Used**: 
Master as of [b4e2e1b](https://github.com/dotnet/roslyn/commit/b4e2e1bd1367bc53dca08d999a525b55ac71d552)
(through sharplab.io)
**Steps to Reproduce**:

1. Use "x !is int" expression.

**Expected Behavior**:
This doesn't compile or do compile equivalent to "!(x is int)".
**Actual Behavior**:
It behaves exactly like "x is int".

Is this intended behavior? Visual Studio 16.5.4 C# interactive window produces same result.
![Visual Studio interactive code](https://user-images.githubusercontent.com/19632145/83045981-041b9b00-a04f-11ea-8e95-449774a2d969.png)

**Comment by gafter** [comment]
It compiles as `(x!) is int` just as specified.  There is no `!is` operator.

**Comment by alrz** [comment]
`x! is T` is never useful (no warning to supress). I think this could be a candidate for warning waves to avoid confusion.
