### ISSUE TITLE
Cannot configure auto-import to be the default intellisense behaviour

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1041127/cannot-configure-auto-import-to-be-the-default-int.html)._

---
For example:

```
namespace Test
{
  public class MyClass { }
}
```
```
using Test;
namespace Test2
{
  public class MyOtherClass
  {
    public MyOtherClass(MyClass m) { }
  }
}
```
```
using Test2;
namespace ExampleNamespace
{
  pubic static void Main()
  {
    var myOtherClass = new MyOtherClass(new >
  }
}
```

When the cursor reaches the point marked by > in the above example, intellisense suggests Test.MyClass, rather than MyClass with an auto-import of using Test;

If you were to continue typing "MyClass", the auto import would gain focus in the intellisense window, but it should have been the default - because I'm sure I'm not alone in saying that 99% of the time, we want our namespaces up in our using statments, not in our code.  This leads to accepting the first intellisense suggesion, followed by either a code refactoring to move the namespace to a using statment, or a manual edit, which is tedious bordering on insanity inducing :D

There is also no way I can find to change settings to configure this as the default behaviour (hopfully I'm wrong?).

---
#### Visual Studio Feedback System on 5/21/2020, 02:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
