### ISSUE TITLE
Consider clarifying IsStatementContext and IsGlobalStatementContext

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44599]
Prior to top-level statements, `IsGlobalStatementContext` implied `IsScript`. This is no longer the case, but the behavior of top-level statements is not exactly the same as C# scripts. Currently we have the following:

* `IsStatementContext`: inside the body of an anonymous function or member
* `IsGlobalStatementContext`: a statement at the top level, whether or not the file is a script
* `IsScript`: true for script files; otherwise, false

Various features need to check these in different combinations depending on the applicability of the feature to top-level statements and/or scripts. It may be possible to improve this API so it's clearer at each call site which combination is correct.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
