### ISSUE TITLE
Wrong indenting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44607]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1050808/wrong-indenting-2.html)._

---
<p>Found this problem was reported before, appears to have been reported as fixed.  But it is happening again…   The title info for the original report is:</p>
<p>TITLE:  Wrong indenting<br>
DATE:  Olaf van der Spek reported 12/7/2018, 12:54:20 PM</p>
<p>Problems is effectively the same.   Running VS 2019 v16.6.0.  When you select the editor’s  setting for “Indenting” which can be one of  [NONE|BLOCK|SMART], selecting ‘BLOCK’  the cursor, most of the time, upon present ENTER goes to column 1 on the next line.   Appears “INDENTING is behaving as “NONE” is selected.<br>
Not sure when started, bouncing between VS 2017 and 2019, never have seen the problem in 2017, can’t say it ever worked in 2019 for that matter.</p>

---
#### Visual Studio Feedback System on 5/27/2020, 03:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ZooDoo4U** [comment]
Hope i didn't add confusion,  Adding the comment i left on the "Developer Community"...      

I'm working in a few languages and file types. C#, javascript, html, jsx, css. Normally i turn off *all* auto formatting and will normally fix up the code as desired. First thing i'll do is go in to Tool::Options then Languages and set "Indenting to" "BLOCK". I'm thinking what might be happening, and makes the most sense to me, most everyone leaves all the "Auto Formatting" on and they have "On Enter" reformat, just find it too distracting.

In C# files the intending can be really inconsistent, i've seen it happen a lot, but right now, can't get a good repro, but guarantee i've seen it happen a lot, i'm wondering fiddling with some of the setting investigating I got it working right for a little while in C#. Actually when it happened earlier today in C# that is what prompted me to open this issue. Normally I work 70% in C#, then the other languages.

Javascript/JSX files, this i can repro 100%. Start off with, hope i don't confuse it but will try showing where press enter/tab, for example {ENTER} is where the enter key was pressed.

(New Empty file) Then start typing:

function testMe() {{ENTER}
// Here the cursor will be in column 1. Fair enough one might argue it follows block formatting rules here technically

Now continuing on i'll tab in:
function testMe() {
{TAB}const x = 5;{ENTER}

// Ah now the cursor again is in column 1, expected column 4, or the appropriate tab indent in case you might have started in column 20...

Interesting if using a code snippet for a function in javascript, not sure why but it acts different but the wandering cursor back to column 1 will appear again but not as easy.

funct{TAB}
//will get:
function snippetPlaceHolder ()
{
// Cursor will be in column 1
}

Continuing on...

function snippetPlaceHolder ()
{
{TAB}if(x===3){ENTER}
}

Then here the cursor seeks to the right location under the 'if' but then, adding both the open/closing '{}' then {ENTER}...

function snippetPlaceHolder ()
{
    if(x===3)     // these two lines should be on tab width in.
    {{enter}}    //  appears the formatter here is normalizing lines...
}


The code will end up as:
function snippetPlaceHolder ()
{
    if(x===3)    // again should be the right tab with in...
    {
} // the cursor and the closing brace are both back at column 1...
}

Hope this is clear. Sorry couldn't get the C# repro but i've seen it happen a fair amount :(

**Comment by CyrusNajmabadi** [comment]
@DanielRosenwasser can you port this to TS?  I'm going to close out this issue on the roslyn side as it lacks a suitable repro for us to investigate.  @ZooDoo4U if you can find a C# repro please file a new issue on this repo.  Thanks!
