### ISSUE TITLE
"Suppress warning" actions available but have no effect during build

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#44615]
**Version Used**: Version 16.7.0 Preview 3.0 [30125.18.master]

**Steps to Reproduce**:

1. Kick off a long-running build
1. See error in output, navigate to it in code
1. Forget that the build is running
1. Select one of the "Suppress" options
1. Nothing happens

**Expected Behavior**:

Either the suppress commands are hidden/disabled, or they actually work.

**Actual Behavior**:

Command is available, but invoking it does nothing and there's no feedback as to why.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
