### ISSUE TITLE
Record implementation forbids sealed Equals in base, in contradiction to the spec

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44617]
Regarding the spec sentence

> Record types produce synthesized implementations for the following methods:
> 
> - `object.GetHashCode()` override, unless it is sealed or user provided
> - `object.Equals(object)` override, unless it is sealed or user provided

However, the test `Overrides_01` in https://github.com/dotnet/roslyn/pull/44595 demonstrates that the compiler produces an error rather than omitting the methods.

**Comment by gafter** [comment]
According to the spec at https://github.com/dotnet/csharplang/blob/master/proposals/records.md#members-of-a-record-type it should not be added if there was an inherited member unless the inherited member is `abstract`.

**Comment by agocke** [comment]
Fixed in https://github.com/dotnet/csharplang/pull/3583
