### ISSUE TITLE
Records implementation produces properties that spec says it should not.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44616]
Regarding the spec sentence

> If no concrete (i.e. non-abstract) property with a get accessor and with this name and type is explicitly declared or inherited, it is produced by the compiler as follows

There are a number of tests (like `Inheritance_01`) added in https://github.com/dotnet/roslyn/pull/44595 that demonstrate that the compiler produces properties that the spec says it should not.

**Comment by AlekseyTs** [comment]
@cston Has this issue been addressed?

**Comment by cston** [comment]
Fixed.
