### ISSUE TITLE
Question: Building, Debugging and Testing on macOS

### ISSUE THREAD

**Issue by Ebeid** [dotnet/roslyn#44628]
This is more of a question. Is there a guide to help developers setup an environment for debugging / contributing to Roslyn from macOS ? or the Unix guide is good enough ?

**Comment by jmarolf** [comment]
I would expect the unix guide to work. Please tell us if not so we can update the docs section. We should add a page for macOS users but we currently run all out test against macOS 10.14.

https://github.com/dotnet/roslyn/blob/ffbb9c7e8f7699c3eb24fa559e6bb381f3405605/azure-pipelines.yml#L232-L236

 As long as you have `git` and `curl` installed running `./build.sh --restore` should get you everything you need to develop. If you do not have `curl` installed see this guide [here](http://macappstore.org/curl/) for how to install it.

`./build.sh --build` will build your changes and `./build.sh --test` will run all your tests.

@333fred I assume you have more productivity tips for unix environments that should also work on macOS?

**Comment by JoeRobich** [comment]
One thing to note is that the [./build.sh targets the Compilers.sln](https://github.com/dotnet/roslyn/blob/master/eng/build.sh#L213) since many projects in Roslyn.sln require Windows to build.

**Comment by 333fred** [comment]
Yeah, the setup on Linux/MacOS is pretty straightfoward. We do have a number of vscode tasks that can help ease development, including building particular parts of the environment or running tests in context.
