### ISSUE TITLE
CS8602 in local function when referencing variable declared using var

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44620]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1041770/cs8602-in-local-function-when-referencing-variable.html)._

---
[regression] [worked-in:16.5]
When using a variable in a local function declared in the owning method with the var keyword you get a CS8602 Dereference of possibly null reference if the local function is called in a delegate. In previous versions of VS you did not get a warning in this case. 

If you change var to the real type the warning goes away. 

I'd expect the var keyword to get resolved to a non-null type if the expression is not-null. 

For example:
var foo = "foo";

Here I would assume that the compiler can realize that var is string and not string?. 

The attached example is simplified as much as I could. Where I've run into this the local function is used in a linq expression.

---
#### Visual Studio Feedback System on 5/21/2020, 03:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
Duping against #44411
