### ISSUE TITLE
Move method parameter left or right with a key combination

### ISSUE THREAD

**Issue by alnikola** [dotnet/roslyn#44625]
**Version Used**: 
Version 16.7.0 Preview 3.0 [30126.178.master]
**Expected Behavior**:
Refactoring command moving method parameter left or right with a key combination (e.g. Ctrl+Shift+Alt + (->, <-)
Before:
```C#
public void Do(string a, int b)
```
After:
```C#
public void Do(int b, string a)
```
**Actual Behavior**:
Not implemented

**Comment by jmarolf** [comment]
@alnikola should this also update all the locations that call this method to call in the correct order?

**Comment by alnikola** [comment]
It's nice to have as an option, but not required.

**Comment by CyrusNajmabadi** [comment]
This is subsumed by 'signature change'.  Unlikely we will have special chords here, esp. given no other customer requests.  Just conceptually easier to have a single entrypoint for all the verbs related to signatures.
