### ISSUE TITLE
Move a type's member up or down with a key combination

### ISSUE THREAD

**Issue by alnikola** [dotnet/roslyn#44626]
**Version Used**: 
Version 16.7.0 Preview 3.0 [30126.178.master]
**Expected Behavior**:
Refactoring command moving a type's member up or down with a key combination (e.g. Ctrl+Shift+Alt + (^, v)
```C#
private readonly string _str;
public void DoA() {}
// Some comment
public void DoB() {}
```
After:
```C#
private readonly string _str;
public void DoB() {}
// Some comment
public void DoA() {}
```
**Actual Behavior**:
Not implemented

**Comment by CyrusNajmabadi** [comment]
closing due to lack of feedback.
