### ISSUE TITLE
Change member accessibility level

### ISSUE THREAD

**Issue by alnikola** [dotnet/roslyn#44624]
**Version Used**: 
Version 16.7.0 Preview 3.0 [30126.178.master]
**Expected Behavior**:
Refactoring command changing member accessibility level and optionally renaming it to match the new level naming scheme
Before:
```C#
protected readonly IDataProtector DataProtector;
```
After:
```C#
private readonly IDataProtector _dataProtector;
```
**Actual Behavior**:
Not implemented

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.  Can just be done with completion and the naming fixer.
