### ISSUE TITLE
Add 'default' to generated switch cases

### ISSUE THREAD

**Issue by alnikola** [dotnet/roslyn#44634]
**Version Used**: 
Version 16.7.0 Preview 3.0 [30126.178.master]
**Expected Behavior**:
Add `default` case throwing `NotImplementedException` or `ArgumentOutOfRangeException(nameof(argument))` for generated cases of a switch block

```C#
                switch (affinityResult.Status)
                {
                    case AffinityStatus.OK:
                        break;
                    case AffinityStatus.AffinityDisabled:
                        break;
                    case AffinityStatus.AffinityKeyNotSet:
                        break;
                    case AffinityStatus.AffinityKeyExtractionFailed:
                        break;
                    case AffinityStatus.DestinationNotFound:
                        break;
                    default:
                        throw new NotImplementedException();
                }
```
**Actual Behavior**:
`default` is missing.
```C#
                switch (affinityResult.Status)
                {
                    case AffinityStatus.OK:
                        break;
                    case AffinityStatus.AffinityDisabled:
                        break;
                    case AffinityStatus.AffinityKeyNotSet:
                        break;
                    case AffinityStatus.AffinityKeyExtractionFailed:
                        break;
                    case AffinityStatus.DestinationNotFound:
                        break;
                    // No default case
                }
```

**Comment by CyrusNajmabadi** [comment]
This can be done with our code-refactorings:

![image](https://user-images.githubusercontent.com/4564579/83181554-e8110b80-a0d9-11ea-9a10-91c51c48a184.png)

I think we would likely take a PR that augumented to this to offer to add a throwing version as well.

**Comment by alnikola** [comment]
Got it. However, I'd suggest to generate that empty `default` switch by default when other cases are generated for the developer to clearly see that `default` must be handled. In absence of `default` switch block is not safe since it will just be skipped in case of an unknown value.

**Comment by CyrusNajmabadi** [comment]
> to clearly see that default must be handled. 

Why does `default` need to be handled?

> In absence of default switch block is not safe since it will just be skipped in case of an unknown value.

Why is that `not safe`?

**Comment by CyrusNajmabadi** [comment]
Note: when you use our refactorings to generate the switch cases we do offer all three options of:

![image](https://user-images.githubusercontent.com/4564579/83324785-83aa9500-a21c-11ea-92b1-0795162eb99f.png)

![image](https://user-images.githubusercontent.com/4564579/83324791-8a390c80-a21c-11ea-83ab-993cb19d951c.png)

![image](https://user-images.githubusercontent.com/4564579/83324797-90c78400-a21c-11ea-9a7a-48ed78592ede.png)

So, as a user, you can decide which of these you want.  You can even go back to switchs that are only partially filled and add the remainder of the items after the fact:

![image](https://user-images.githubusercontent.com/4564579/83324814-a9379e80-a21c-11ea-9033-e7557b9ed517.png)


I did notice we regressed this recently, and submitted https://github.com/dotnet/roslyn/pull/44718 to fix it.  You should see this working when 16.7 ships.

**Comment by alnikola** [comment]
> Why does default need to be handled?
> Why is that not safe?

It must be handled to avoid unexpected and potentially dangerous behavior when a new enum value is introduced, but not all the switch blocks get updated. The bigger and older code base the higher chance of such mistake.

## Example

**Before**
```C#
public enum UserType
{
    Regular,
    Admin
}

public class User
{
    public string Name {get;}
    public UserType Type {get;}

    public User(string name, UserType type)
    {
        Name = name;
        Type = type;
    }
}

public class ResourceManager
{
    private readonly IDictionary<object, object> _items;

    public void Update(object key, User user)
    {
        switch(user.Type)
        {
            case UserType.Regular:
                throw new InvalidOperationException("Access denied.");
            case UserType.Adim:
                break;
            // NO default case
        }
        // Actually update resource in a storage
       _items.[key] = value;
    }

    public void Delete(object key, User user)
    {
        switch(user.Type)
        {
            case UserType.Regular:
                throw new InvalidOperationException("Access denied.");
            case UserType.Adim:
                break;
            // NO default case
        }
        // Actually delete resource from a storage
       _items.Remove(key);
    }
}
```

**After**
A new UserType.PowerUser added
```C#
public enum UserType
{
    Regular,
    Admin,
    PowerUser // Can update date, but cannot delete
}

public class User
{
    public string Name {get;}
    public UserType Type {get;}

    public User(string name, UserType type)
    {
        Name = name;
        Type = type;
    }
}

public class ResourceManager
{
    private readonly IDictionary<object, object> _items;

    public void Update(object key, User user)
    {
        switch(user.Type)
        {
            case UserType.Regular:
                throw new InvalidOperationException("Access denied.");
            case UserType.PowerUser
            case UserType.Adim:
                break;
            // NO default case
        }
        // Actually update resource in a storage
       _items.[key] = value;
    }

    public void Delete(object key, User user)
    {
        switch(user.Type)
        {
            case UserType.Regular:
                throw new InvalidOperationException("Access denied.");
            case UserType.Adim:
                break;
            // NO default case, so PowerUser is allowed to proceed
        }
        // Actually delete resource from a storage
       _items.Remove(key);
        // PowerUser deleted an entity. Security breach!
    }
}
```
Similar errors can happen when converting a base type to the enum. In example above, it's possible to assign value 5 to UserType due to a missing validation in User's ctor which will also lead to an undefined behavior.
```C#
new User("ZZZ", (UserType)5);
```

**Comment by CyrusNajmabadi** [comment]
Those are cases where it *may*need to be handled, not that default must be handled or will always be unsafe if not handled.
