### ISSUE TITLE
Inaccurate error message

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#44635]
**Version Used**: 

Visual Studio 2019

**Steps to Reproduce**:

```csharp
public class Program
{
    public Program() { }

    public static void Main()
    {
        using (Program p1 = new Program()) { }
        using Program p2 = new Program();

    }

}
```

**Expected Behavior**:

Two different errors:

1. 'Program': type used in a using **statement** must be implicitly convertible to 'System.IDisposable'.
2. 'Program': type used in a using **declaration** must be implicitly convertible to 'System.IDisposable'.

**Actual Behavior**:

Same error:
'Program': type used in a using **statement** must be implicitly convertible to 'System.IDisposable'.

A using statement is different than a using declaration. So, the error message is misleading.

**Comment by CyrusNajmabadi** [comment]
This doesn't actually seem like it would warrant a different error message.  The error seems totally clear.

**Comment by Youssef1313** [comment]
It'd be better to have accurate error messages. If not two different messages, I suggest the current message changes to:

'{typeName}': type used in a using statement or declaration must be implicitly convertible to 'System.IDisposable'.

**Comment by CyrusNajmabadi** [comment]
> It'd be better to have accurate error messages.

I don't think there's anything really inaccurate about the error message.  There's nothing confusing or strange about it.  From a user's perspective, this is just a using statement.  It's got he using, it's got the variable, it's got the expression initializing it.  It's a using statement.  

Furthermore, the error really has nothing to do with the statement/declaration distinction.  If it did, then i might agree.  It's a general statement (no pun intended) about what requirements `usings` have (i.e. that they require IDisposables).  That's the important bit of the message, and adding additional clutter which doesn't serve to enhance or make the message clearer isn't a good thing.

**Comment by gafter** [comment]
A using declaration is a kind of statement. The diagnostic seems clear to me. Were you actually confused by it?

**Comment by Youssef1313** [comment]
@gafter No, I myself didn't get confused. The thing in my opinion was about the accuracy of the term. I think using statement and using declaration are different based on lang specs.

But as @CyrusNajmabadi stated:

> the error really has nothing to do with the statement/declaration distinction.

that's totally correct, although I still see the inaccurate term is used. But I can agree that using accurate terms won't change the clarity of the message.

So, feel free to close if you prefer keeping it as-is.

**Comment by CyrusNajmabadi** [comment]
No lack of clarity here.  Strict adherence to accuracy with teh spec isn't necessarily valuable for users.  Closing out.  Thanks for the feedback!
