### ISSUE TITLE
[C# Interactive] System namespace loaded by default

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#4465]
At the moment, there are only a few common namespaces loaded into C# Interactive by default. Can System be added to this list? It contains a large portion of commonly used classes and structures.

**Comment by mattscheffer** [comment]
@amcasey @ManishJayaswal

**Comment by amcasey** [comment]
I believe the fix has been inserted.  @mattscheffer, can you please verify?

**Comment by mattscheffer** [comment]
Missed this was closed. Fix has been inserted and using System is default. Thanks!
