### ISSUE TITLE
Dependency not getting copied to bin

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/roslyn#44659]
**Version Used**: 
Visual Studio 2019 16.6.0
**Steps to Reproduce**:

1. Project with folliwing structure:
Proj.Api (net461 WebApi)
Proj.Core (net461 library)
Proj.Adapter (netstandard20 library)

Both Api and Adapter reference Core. Core has no dependencies. 
Api references Adapter and injects an Adapter.Service in startup.
Api has a controller that calls Adapter.Service.Method().

2. Install `System.Configuration.ConfigurationManager` into Adapter using NuGet.
`Adapter.Service.Method()` uses `ConfigurationManager.AppSettings["SomeSetting"]`. (Add SomeSetting to the Web.Config of the Api).
3. Build and run Proj.Api

**Expected Behavior**:
Api should call Adapter and run `Adapter.Service.Method()`.
**Actual Behavior**:
`System.Configuration.ConfigurationManager` isn't copied to the Api/bin directory.
DI throws an exception about `System.Configuration.ConfigurationManager` not being found while trying to instantiate Adapter.Service.

**Comment by Regenhardt** [comment]
Update: Sometimes my local nuget does funny things,  so I tried it in the server (which runs perfectly): Same problem. No `System.Configuration.ConfigurationManager` found in the /bin directory.

**Comment by CyrusNajmabadi** [comment]
Closing as external. This is not related to roslyn.
