### ISSUE TITLE
Interactive Window not persisted as part of window layout

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4466]
1. Open VS
 1. Open interactive window
 1. Close VS
 1. Open VS

Expected: Interactive window is open
Actual: Interactive window is not open

Compare: The command window remains open across restarts.

**Comment by amcasey** [comment]
FYI @tmat

**Comment by amcasey** [comment]
@ManishJayaswal should this be in 1.1(Preview)?

**Comment by ManishJayaswal** [comment]
@amcasey if we can fix this before preview then great but we don't really need feedback to know that this needs to be fixed, hence 1.1 milestone.

**Comment by amcasey** [comment]
@ManishJayaswal My concern is that it will see less use if it keeps disappearing.

**Comment by ManishJayaswal** [comment]
@amcasey fair enough. Moved it to preview.

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn/commit/e604663b467393720d9d1b47b429a04320ca6fb7
