### ISSUE TITLE
Flow Insensitive Analysis performed by GetAnalyzerDiagnsoticAsync() 

### ISSUE THREAD

**Issue by pavanupb** [dotnet/roslyn#44665]
**Version Used**: 
Microsoft.CodeAnalysis 2.10.0
**Steps to Reproduce**:

1. Two different documents are being passed to VerifyCSharpDiagnostic() while unit testing. I am trying to perform an interprocedural test against my analyzer
2. Document 1 contains a call to a function in Document 2
3. Document 1 and Document 2 are added to sources of VerifyCSharpDiagnostic()

**Expected Behavior**:
Document 1 should be analyzed first followed by Document 2
**Actual Behavior**:
Document 2 is analyzed first followed by Document 1.

**Comment by sharwell** [comment]
Can you show an example test that reproduces this?

**Comment by pavanupb** [comment]
Example: Document 1 contains
public void SummaryReuseTest()
        {
            IdentityFuncTest identityFuncTest = new IdentityFuncTest();
            string alias1 = "This is a secret message";
            string alias2 = alias1;
            identityFuncTest.Identity(alias1);
            string alias3 = alias2;
            string alias4 = alias3;        

        }

Document 2 contains 
public void Identity(string parameters)
        {
            string mapped = parameters;
        }
I registered a syntax node action for MethodDeclaration type.

I see that the syntax node action gets hit first with the Identity() of Document 2 then gets hit with SummaryReuseTest() of Document 1.

**Comment by sharwell** [comment]
This behavior is by design. The callbacks are allowed to occur in any order, and are even allowed to occur in parallel.
