### ISSUE TITLE
Determine semantics of empty record parameter list

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44677]
https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L2941

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/47091 (newer, has more details, includes LDM decision)
