### ISSUE TITLE
Don't add synthesized Equals/GetHashCode if base method is sealed

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44678]
https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L2949

https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L3021

https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L3031

IIRC @cston is working on this

**Comment by cston** [comment]
See https://github.com/dotnet/roslyn/issues/44617.

**Comment by RikkiGibson** [comment]
Closing in favor of #44617
