### ISSUE TITLE
Allow reordering of 'data' modifier in type declaration

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44674]
https://github.com/dotnet/roslyn/blob/8769e0b5b4d8338bb3044296d36ebc9c5e3647cf/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L1124

This may be obviated by the change from `data class` -> `record`.

**Comment by jaredpar** [comment]
The syntax is no longer `data class` hence this is not an issue anymore.
