### ISSUE TITLE
Error when more than one declaration of a type has a parameter list

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44676]
https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs#L2926

I assume this refers to a scenario like:
```
partial data class C(int a);
partial data class C(int b);
```

**Comment by RikkiGibson** [comment]
@jaredpar @agocke Is this something we should fix before preview3? Today I think it just takes the last parameter list in lexical order and runs with it. It seems like the other parameter lists do not get bound, which I could imagine resulting in bad behavior down the line (worth manually testing at least?)

**Comment by jaredpar** [comment]
This is fine to fix after preview.

My logic here is that we should focus on issues with correct code for the preview. Basically good code should work. Bad code though if it errors, or produces invalid code, for a preview is okay. We can fix that later.

**Comment by RikkiGibson** [comment]
This was fixed but GitHub is helping us by not auto-resolving any issues when the base branch is not master.
