### ISSUE TITLE
Put primary constructor parameters in scope inside record

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44687]
https://github.com/dotnet/roslyn/blob/891fd421c4488d861c4959bbc91245eb4b118a06/src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs#L257

It looks like the above test should compile without diagnostics because the thing being used is supposed to be the primary constructor parameter, not the corresponding property.

**Comment by gafter** [comment]
The spec at https://github.com/dotnet/csharplang/blob/master/proposals/records-wip.md does not place them in scope where used in this test.

**Comment by RikkiGibson** [comment]
It seems like the spec needs to be modified to honor the decision made in this LDM meeting: https://github.com/dotnet/csharplang/blob/31596564000df032a8c5845a51899f739c6c9bca/meetings/2020/LDM-2020-04-27.md#discussion

Particularly this paragraph:
> Primary constructors work like capturing. The parameters from the primary constructor are visible in the body of the class. In field initializers and possibly a primary constructor body, they are non-capturing, namely that use of the parameter does not capture to any fields. Everywhere else in the class, the parameters are captured and create a private backing field.

**Comment by gafter** [comment]
@RikkiGibson I agree. @agocke expressed his intent to update the spec incrementally as (before) parts of the feature are implemented. I'm calling this out as an implementation that implements something that isn't specified (or that contradicts the current specification). Without a specification it is hard to have confidence that the implementation aligns with the specification.

**Comment by RikkiGibson** [comment]
I believe dotnet/csharplang#3548 addresses the missing spec.

**Comment by RikkiGibson** [comment]
The spec change has been merged and the implementation for this is done. Not sure which PR did this, feel free to link the appropriate PR if desired @AlekseyTs.

**Comment by gafter** [comment]
@RikkiGibson The document https://github.com/dotnet/csharplang/blob/master/proposals/records.md contains no modification to the name lookup rule in https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#simple-names that would support these changes.

**Comment by AlekseyTs** [comment]
@gafter 
> The document https://github.com/dotnet/csharplang/blob/master/proposals/records.md contains no modification to the name lookup rule

Could you elaborate please? Look for a word "scope" in https://github.com/dotnet/csharplang/blob/master/proposals/records.md.

**Comment by gafter** [comment]
@AlekseyTs Can you please identify specifically how that text affects name lookup in the language specification at https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#simple-names? Note that the latter does not refer to any concept called "scope".
