### ISSUE TITLE
Improvements to string autocompletion in method calls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44696]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1056038/improvements-to-string-autocompletion-in-method-ca.html)._

---
For example we have to following code:
```
var name = "Patrick";
Console.WriteLine("");
```

Now I want to print **Hello Patrick**.

Then I'd write
```
var name = "Patrick";
Console.WriteLine($"Hello {name}");
```

1. When I start typing `$"` it should autocomplete the closing quotes and set the cursor inside of it: `$""`

2. Then I want to add a variable and type $"Hello {". It should autocomplete the curved closed bracket and set the cursor in it: `$"Hello {}`

This would be a much smoother experience, and it wouldn't show errors directly because the closing part is missing.

This suggested behaviour is already implemented if you create a new string variable like
```
var name = "Patrick";
var hello = $"Hello {name}";
```

---
#### Visual Studio Feedback System on 5/29/2020, 02:46 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
> When I start typing `$"` it should autocomplete the closing quotes and set the cursor inside of it: `$""`

This is covered by #24376

> Then I want to add a variable and type `$"Hello {"`. It should autocomplete the curved closed bracket and set the cursor in it: `$"Hello {}`

Agreed. This is a bug.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
