### ISSUE TITLE
Add quick action "Introduce and initialize property 'xy'" for regular methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1046879/add-quick-action-introduce-and-initialize-property.html)._

---
Assuming there is the following constructor:

```
public IndexModel(int id)
{

}
```

You can right-click on `id` -> Quick Actions and Refactorings and you get the options
- Introduce and initialize property 'Id
- Introduce and initialize field '_id'

For regular methods, you don't have these options. Since a field is generated with readonly, this makes no sense, but for a property, this can be useful for Factory / Builder classes or if you work with method chaining.
Therefore I'd suggest to add the quick action Introduce and initialize property 'xy'.

Example:
```
public void Build(int id)
{
}
```

Would become
```
public int Id { get; set; }

public void Build(int id)
{
    Id = id;
}
```

---
#### Visual Studio Feedback System on 5/25/2020, 02:41 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
I don't think we would necessarily take this.  The vast majority of method parameters aren't going to be assigned to a field/property, while the vast majority of constructor parameters are.  So this would just end up being *very* noisy for users.

You can just assign to a non-existed field prop like so: `this.id = id`, or `_id = id` or `Id = id`, and we'll offer to suggest the field/prop at that point.
