### ISSUE TITLE
Make an end-to-end test for making a compilation from pdb/pe/sourcelink

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#44703]
With #44373 we're adding compilation options and metadata references to portable PDBs so that a compilation can be reconstructed and be bytewise equal to a PE (with some exceptions around signing and non-deterministic builds) 

This tracks us adding an integration test to verify that we can achieve this, and keep the feature in good health moving forward.

**Comment by clairernovotny** [comment]
Could this test be in the form useful for a global tool to use or would we be duplicating the logic of this test to create that tool/library?

**Comment by tmat** [comment]
We will likely be able to share the core logic.

**Comment by ryzngard** [comment]
@jaredpar @RikkiGibson  I don't think this issue is needed anymore? Wanted to double check before closing.

**Comment by RikkiGibson** [comment]
That's right. I think the Correctness_Rebuild leg more or less represents the resolution of this issue.
