### ISSUE TITLE
Copy&Paste Smart

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44701]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1039741/copypaste-smart.html)._

---
I would really like that if I copy the equal of one assignment and then I paste it in another where I already have it this will not be put for example

```
int i=0;
int j=1;

int i
int j==0;(I detect that you want to make an assignment and correct it)

int i
int j=0;
```

---
#### Visual Studio Feedback System on 5/20/2020, 02:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
If you copy and paste a variable declaration and it exists offer to rename it, if it doesn't exist offer to create it.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
