### ISSUE TITLE
Initonly implementation forbids initialization in a local function

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#44704]
Inside the `features/records` branch, in the test file `InitOnlyMemberTests.cs` we have the test `InLambdaOrLocalFunction_InConstructorOrInit` that shows that the compiler forbids the assignment to an init-only property inside a local function.

```csharp
public class C<T>
{
    public string Property { get; init; }

    C()
    {
        local();
        void local()
        {
            Property = null; // error CS8802: Init-only property or indexer 'C<T>.Property' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.
        }
    }
}
```

However, [the spec](https://raw.githubusercontent.com/dotnet/csharplang/master/proposals/init.md) permits it. Specifically, the spec says

> An instance property containing an `init` accessor is considered settable in the following circumstances:
> 
> - During an object initializer
> - During a `with` expression initializer
> - **Inside an instance constructor of the containing or derived type, on `this` or `base`**
> - Inside the `init` accessor of any property, on `this` or `base`
> - Inside attribute usages with named parameters

[Emphasis mine]

And nothing else in the specification forbids it.

**Comment by jcouv** [comment]
You're correct that there is a mismatch. The reason I disallowed it is because the local function (or lambda) could be captured in a delegate and invoked outside of the designated "initialization" phase.
We can confirm the design with LDM and update the spec (or implementation) if needed.

**Comment by jcouv** [comment]
Updated the spec (local functions and lambdas are outside of init phase).
