### ISSUE TITLE
Incorrect indexer being return by `GetIndexerGroup(...)` ?

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#44719]
Consider this snippet:

```
public class CCC
{
    void Foo()
    {
        string[] arr = null;
        string s = arr[0];
    }
}
```

If I invoke `GetIndexerGroup(node)` where node is `arr[0]` (an `ElementAccessExpressionSyntax`), I get, as the single result in the collection, the indexer property `string.this[int]`.

This seems wrong to me...

I could expect `null` or an “array indexer” (which returns an `string`); but not an string indexer (which returns an `char`). For instance, if I invoke `GetOperation(node)` on that same node, I correctly get a `IArrayElementReferenceOperation`.

**Comment by ltcmelo** [comment]
At the minimum, this behavior reflexes through an inconsistency in the API (well... in my  understanding). The snippet below prints to the console, for the source in [my previous post](https://github.com/dotnet/roslyn/issues/44719#issue-627720598).

```
public override void VisitElementAccessExpression(ElementAccessExpressionSyntax node)
{
    //...
       
    var indexSym = semaModel.GetIndexerGroup(node).First();
    var exactTySym = semaModel.GetTypeInfo(node).Type;
    var convTySym = semaModel.GetTypeInfo(node).ConvertedType;
    if (indexSym is IPropertySymbol propSym
                && propSym.Type != exactTySym
                && propSym.Type != convTySym)
    {
        Console.WriteLine($"this is unexpected: `{propSym.Type}' not in (`{exactTySym}', `{convTySym}')");
    }
}
```

**Comment by svick** [comment]
Isn't that exactly what [the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.csharpextensions.getindexergroup?view=roslyn-dotnet) says this method should do (emphasis mine)?

> Returns the list of accessible, non-hidden indexers that could be invoked **with the given expression as receiver**.

And even if everyone agreed that this makes the API inconsistent, what action are you suggesting here? I don't think the behavior of `GetIndexerGroup` can change, since that would be a breaking change.

**Comment by ltcmelo** [comment]
@svick yes, the documentation is correct; what I claim to be a bug is in the result/implementation: you can't apply `string.this[int]` on `arr[0]` where `arr` is of `string[]` type. In other words, this is a compilation error:

```
string[] arr = null;
char s = arr[0]; // error, not valid for string.this[int]
```

You might be confusing the indexing operation of an array of strings, which returns a `string`, to the indexing operation of an `string`, which returns a `char`.

**Comment by svick** [comment]
@ltcmelo 

I think that the documentation and implementation agree and that there is no bug. The documentation says that if you call `GetIndexerGroup()` on an expression of type `string` (in your case, `arr[0]`), it returns `string.this[int]`, which is what the implementation does. The fact that the expression in question is an indexer expression itself is irrelevant.

Or put differently, that call to `GetIndexerGroup()` is telling you that `arr[0][0]` is a valid expression, but it doesn't tell you anything about the meaning of `arr[0]`.

**Comment by ltcmelo** [comment]
Hum... re-reading the documentation more carefully (and the part you made bold), I guess you're right @svick , thanks for clarifying.

**Comment by svick** [comment]
@ltcmelo I agree that it is inconsistent. But I don't think it's bad enough to warrant doing anything about it, especially since that would likely require some kind of breaking change.

**Comment by ltcmelo** [comment]
@svick one suggestion:

1. add a method called `GetIndexerGroupOnEvaluatedType(...)` (or another more accurate name) with the exact same behaviour of current `GetIndexerGroup(...)`

2. mark `GetIndexerGroup()` as _deprecated_; even if it isn't removed in the short term, at least it will bring attention of users.

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by CyrusNajmabadi** [comment]
I don't see a problem ehre.  The methods are behaving as documented and for their expected use cases.  We're also not going to deprecate or change this.  So i think we can close this out as effectively answered.

**Comment by ltcmelo** [comment]
> I don't see a problem ehre. The methods are behaving as documented and for their expected use cases. We're also not going to deprecate or change this...

@CyrusNajmabadi 

I acknowledge (after clarification by @svick) that the method behaves as documented. Yet, it seems that I'm not the only who think this API is potentially misleading -- so they can continue to fulfill "their expected uses cases", but through a different name.

My question is: you're not going to deprecate this because:

(i) you don't agree that the API isn't good?

(ii) you accept a problem with the API, but, for whatever reason, you don't think this should be renamed?

In the case of (ii), what is criteria to judge whether an API should be deprecated or not?

**Comment by CyrusNajmabadi** [comment]
I'm not going to deprecate it before I don't think there's anything wrong with the existing method.
