### ISSUE TITLE
ParenthesizedExpressionSyntaxExtensions doesn't show in Solution Explorer

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#44723]
**Version Used**: 

Visual Studio 2019

**Steps to Reproduce**:

1. Clone the repository
2. Run `dotnet restore Compilers.sln`
3. Open `Compilers.sln` in Visual Studio
4. Search for `ParenthesizedExpressionSyntaxExtensions` in Solution Explorer

**Expected Behavior**:

The file is found.

**Actual Behavior**:

The file is not found.

**Comment by sharwell** [comment]
@mavasani it looks like the shared projects used by the workspaces layer were not added to **Compilers.sln**. It should be fine to just update **Compilers.slnf** (am sending a PR for this part).

**Comment by mavasani** [comment]
@sharwell We did add the shared projects for workspace and compiler utilities used in Workspaces.csproj to Compilers.sln - otherwise, building Compilers.sln would fail.

**Comment by sharwell** [comment]
The shared projects are not required to be in the solution for command line builds to work. The `<Import>` elements of the project files still work fine.

**Comment by mavasani** [comment]
Ah, got you. Thanks!

**Comment by Youssef1313** [comment]
Closing as it's already fixed. Thanks @sharwell.
