### ISSUE TITLE
Proposal: Add switch for treating nullable-related warnings as errors

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#44721]
**Version Used**: .NET 5 Preview 4

If I want to treat all nullable-related warnings as errors, I have to treat CS8597 to CS8714 which declared in https://github.com/dotnet/roslyn/blob/3c1c0fcb4dcb296758254fef0751111633af22a0/src/Compilers/CSharp/Portable/Errors/ErrorCode.cs#L1639 as error in .csproj file manually, and it's really inconvenient.

I hope that there can have a switch to treat all nullable-related warnings as errors.

For example:
```xml
<PropertyGroup>
  <TreatNullableWarningAsError>true</TreatNullableWarningAsError>
</PropertyGroup>
```

**Comment by jcouv** [comment]
There is already a compiler option to do this: `-warnaserror: nullable` from the [command-line](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/warnaserror-compiler-option).
It should also work by passing "nullable" (in place of a specific diagnostic ID) to the "TreatWarningsAsErrors" msbuild option.

I'll go ahead and close this issue as fixed. Thanks

**Comment by hez2010** [comment]
It works while building the project, but Visual Studio doesn't respect it and still produce warnings.

**Comment by jcouv** [comment]
@hez2010 Indeed. Filed https://github.com/dotnet/roslyn/issues/52407 an issue (`WarningsAsErrors` should be honored in IDE too).

**Comment by hez2010** [comment]
Thanks!
