### ISSUE TITLE
Fix All Preview should break down by projects and files, not just files

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/roslyn#44740]
**Version Used**:  16.6.0

**Steps to Reproduce**:

1.  Select a diagnostic that is multiple projects in a solution
2.  Select Solution wide fix

**Expected Behavior**:
 Documents are separated out into individual projects, Project1, Project2, Project3.  Projects can be disabled or enabled, and this would enable or disable all files in the project
**Actual Behavior**:
Files where the fix can be applied are listed, but not separated.

**Comment by CyrusNajmabadi** [comment]
This is a request for the platform.  @olegtk .
