### ISSUE TITLE
Completion list not available before await line in a C# UWP project

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn#4474]
- create a C# blank windows UWP project
- paste the following code into MainPage.xaml.cs

``` csharp

        Windows.UI.ViewManagement.StatusBar statusBar;
        async System.Threading.Tasks.Task Test()
        {
            statusBar = Windows.UI.ViewManagement.StatusBar.GetForCurrentView();
            // here
            await statusBar.ProgressIndicator.ShowAsync();
        }
```
- open a line under "// here"
- type "statusBar."

**Expected:**
completion list window shows
**Actual:**
no completion list.  Ctrl+J shows nothing either.

**Comment by Pilchie** [comment]
A simpler repro is:

```C#
using System.Threading.Tasks;

class C
{
    Task t;
    async Task M()
    {
        t = GetTask();
        // here
        t.
        await t;
    }

    static Task GetTask() { return null; }
}
```

The problem is that the parser is treating this as a variable declaration of a variable named `t` of type `t.await`.

**Comment by Pilchie** [comment]
I don't think the IDE can reasonably recover in this case.

**Comment by jeremymeng** [comment]
It works in the case where `t` is a local though
```csharp
using System.Threading.Tasks;

class C
{
    async Task M()
    {
        Task t = GetTask();
        // here
        t.
        await t;
    }

    static Task GetTask() { return null; }
}
```

**Comment by Pilchie** [comment]
Yep, because the error in the field case is that `t` is shadowed by the newly declared field.

**Comment by gafter** [comment]
Yes, error recovery could be better here, like never treating `await` as an identifier inside an async method.

**Comment by Pilchie** [comment]
Would that be hard on incremental parsing, because we'd have to crumble the whole method if the modifiers change?

**Comment by gafter** [comment]
@Pilchie We already crumble the whole method if the modifiers change, as

```cs
    await (expression);
```

is a call of a method named `await` in a non-async method, and an await statement in an async method.

**Comment by Pilchie** [comment]
Oh, great. Then never parsing await as an identifier is a great idea. That would also make it classify as a keyword sooner, etc.

**Comment by sharwell** [comment]
@dpoeschl there were a whole bunch of duplicates of this issue (see preceding links)

**Comment by ivanbasov** [comment]
Could not reproduce with current bits 16.0.3.
Here is my sample code:
        ```
public MainPage()
        {
            this.InitializeComponent();
            Windows.UI.ViewManagement.ApplicationView view;
            async System.Threading.Tasks.Task Test()
            {
                view =  Windows.UI.ViewManagement.ApplicationView.GetForCurrentView();
                // here
                view.$$
                await view.TryConsolidateAsync();
            }
        }
```

tried both Ctrl+J and completion on insertion on $$. Both work fine.
