### ISSUE TITLE
"Upgrade this project to C# language version x" quick action does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44753]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1051702/upgrade-this-project-to-c-language-version-x-quick.html)._

---
_Upgrade this project to C# language version x_ quick action in .NET Standard library project does nothing.

Instead I have to manually add <LangVersion>x</LangVersion> to .csproj file.

---
#### Visual Studio Feedback System on 5/27/2020, 01:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
I was unable to reproduce this in 16.8 Preview 3 with a new classlib targeting netstandard 2.0
