### ISSUE TITLE
.NET Foundation Coding Guidelines link from wiki Contributing-Code is broken

### ISSUE THREAD

**Issue by Enderlook** [dotnet/roslyn#44769]
The link https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md posted in https://github.com/dotnet/roslyn/wiki/Contributing-Code#coding-conventions is broken.

**Comment by Youssef1313** [comment]
The correct link should be https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md

I'd also change the provided code sample to use `nameof`, and perhaps indent the code-fence so it looks nicer.

**Comment by Enderlook** [comment]
This links are also broken in another document:

https://github.com/dotnet/roslyn/wiki/FAQ#is-there-a-syntax-tree-visualization-or-tools-to-visually-inspect-a-tree
> Yes there is! Look [here|Syntax Visualizer] for more details about the Syntax Visualizer tool.

https://github.com/dotnet/roslyn/wiki/FAQ#is-there-an-end-to-end-example-on-compiling-a-program-to-il-emit-apis
> See next question, [#How can I capture IL, debug info, and doc comment outputs from a Compilation].

https://github.com/dotnet/roslyn/wiki/FAQ#how-can-i-capture-il-debug-info-and-doc-comment-outputs-from-a-compilation
> See the sample code answer tagged “FAQ(34)” ([installed location information|faq#codefiles]). This sample includes an Execute() method definition, which compiles and executes a binary.
