### ISSUE TITLE
Renamer.RenameSymbolAsync throws an OperationCanceledException

### ISSUE THREAD

**Issue by jquintus** [dotnet/roslyn#4477]
Using the Renamer.RenameSymbolAsync method to rename a namespace fails with an OperationCanceledException.  A full example can be found here:  https://github.com/jquintus/RoslynNamespaceAnalyzer

    private async Task<Solution> FixBadNamespace(Document document, NamespaceDeclarationSyntax namespaceDecl, CancellationToken cancellationToken)
    {
        var newName = GetNamespaceName(document.Project, document.Folders);

        var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
        INamespaceSymbol nsSymbol = semanticModel.GetDeclaredSymbol(namespaceDecl, cancellationToken);
        Solution originalSolution = document.Project.Solution;
        OptionSet optionSet = originalSolution.Workspace.Options;

        var newSolution = await Renamer.RenameSymbolAsync(originalSolution, nsSymbol, newName, optionSet, cancellationToken).ConfigureAwait(false);

        return newSolution;
    }

Thanks

**Comment by CyrusNajmabadi** [comment]
@jquintus I can't repro this.  I certain get cancellation exceptions thrown in this code path.  But only during things like "preview" when we're showing the preview and the user either dismisses the SmartTag, or invokes the action.  

When we actually invoke the smart tag, then I see this code getting executed properly, without any cancellation.

So I think this is all working as intended.
