### ISSUE TITLE
C# switch - code compiles that shouldn't

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/948583/c-switch-code-compiles-that-shouldnt.html)._

---
<p>I've noticed a bug that the C# compiler (both msbuild or Roslyn) are unable to detect uninitialised objects within switch statements in some cases. This causes a code that doesn't make any sense to compile. Also whether the code compiles or not seem to depend on compiler heuristics and result in a very undersiable state. <br><br>Let's have a C# class library:</p><pre>namespace CSharpLibrary
{
    public struct Dummy
    {
        public Dummy(string value)
        {
            Value = value;
        }

public string Value { get; }
    }
}
</pre><p><br><br>And let's have a C# application using the above class library:
</p><pre>using System;
using CSharpLibrary;

namespace CSharpApp
{
    class Program
    {
        static void Main(string[] args)
        {
            switch (true)
            {
                case false:
                    var dummy = new Dummy(&quot;foobar&quot;);
                    break;
                case true:
                    Console.WriteLine($&quot;dummy. Value='{dummy. Value}'&quot;);
                    break;
            }
        }
    }
}

</pre><p></p><p>The code compiles, the <code>dummy</code> variable is defined as a local with the scope of the entire function in the IL, so the <code>case true:</code>  is able to use the default initialised variable, and it prints out </p><pre>dummy. Value=''
</pre><p><br>See the attachment for easy repro: <a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/123071-uninitializedvariabledetectionbugrepro.zip">uninitializedvariabledetectionbugrepro.zip</a><br><br>However if you change <code>Dummy</code> to contain an integer instead of a string, you get the correct compile error. If you define <code>Dummy</code> inside the CSharpApp, instead of in the library you also get the correct behaviour. Using binary dependency instead of source dependency seems to cause a change in some cases whether the compile error appears or not, but not for this particular example code. In some cases Roselyn and msbuild disagree, a code compiles with one, but not the other. <br><br>I've tried this with multiple versions of .NET Framework and .NET Core, the behaviour seems uniform across all those.</p>

---
#### Visual Studio Feedback System on 3/16/2020, 00:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 4/23/2020, 09:26 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by agocke** [comment]
This is a bug which has been preserved for backwards compatibility. It is documented at https://github.com/agocke/roslyn/blob/6e8de8e87db2526f7d64bb15e90347c2fd4cfb3c/docs/compilers/CSharp/Definite%20Assignment.md#definite-assignment-of-structs-across-assemblies
