### ISSUE TITLE
CS7021: You cannot declare namespace in script code

### ISSUE THREAD

**Issue by bchavez** [dotnet/roslyn#4478]
Hello, I couldn't find a Roslyn issue that really got into details about this particular compiler error with `scriptcs`.

For reference, the original issue over at https://github.com/scriptcs/scriptcs/issues/1078

Consider the following:

**Hello.cs**
```
namespace Foo{
    public class Bar{
        public void SayHello(){
          Console.WriteLine("Hello World");
        }
    }
}

var b = new Foo.Bar();
b.SayHello();
```

```
R:\>scriptcs Hello.cs
ERROR: Script compilation failed. [CompilationErrorException] R:\Hello.cs(2,1): 
                            error CS7021: You cannot declare namespace in script code
```

As a developer using `scriptcs`, this basic example **should** work. In my original issue, I quoted **Krzysztof Cwalina & Brad Adams** in *Framework Design Guidelines* to advocate the important issue of consistency which ultimately led to a discussion of being able to use valid compile-able C# code (as it stands today) to be considered just as legitimate code inside a scripting context. See example above.

>....this scripting (Roslyn implementation detail?) effectively blocks us from borrowing and reusing .cs files. For argument's sake, let's guesstimate 99% of the C# code in the wild lives under a namespace (reasonable assumption I hope) ... then why not work with 99% of c# code out of the box?

>What we've done here is effectively force devs to strip out namespaces if they want to reuse any existing C# files (IE: POCOs, domain objects, utility classes, helpers). We now have two copies of implementations to maintain (with namespaces and without namespaces)

>The discontinuity here is painfully obvious if C# classes written inside a .csproj can't be reused individually outside the scope of the standard compiler/IDE (ie: scriptcs).

An extended example:
**Domain.cs**
```
namespace MyProject{
  public class Person{
    public string Name {get;set;}
    public string Id {get;set;}
    public void SayHello(){
      Console.WriteLine("Hello World.");
    }
  }
}
```
**Hello.cs**
```
#load "Domain.cs"

var fred = new MyProject.Person();
fred.SayHello();
```
```
R:\>scriptcs Hello.cs
ERROR: Script compilation failed. [CompilationErrorException] R:\Domain.cs(1,1):
                            error CS7021: You cannot declare namespace in script code
```

**Comment by adamralph** [comment]
From a consumption POV I agree with @bchavez but I sympathise with the tough problems facing implementation.

The primary consideration is that the entire script is wrapped into a class, with the top level script going in the constructor, local variables being lifted into fields, and the top level classes and methods as nested classes and methods on the wrapper class respectively. The issue called out by @bchavez is just one case of this implementation leaking through the scripting abstraction quite easily and having bizarre results. Another is that you can write things like `private static int x = 123;` in the top level script. Private to what? Static as opposed to what?

I've challenged this design before and the only reasons I've been given so far are:

1. local variables need to be fields so that top level methods and nested classes can access them
1. local variables need to be fields so that subsequent submissions can access them during an interactive session
1. top level classes need to be nested on the submission class so that they can be redefined during an interactive session

For me, point 1 is neither here nor there. Other platforms don't allow top level script methods to access local top level variables and they can always be passed as arguments if required.

If, for a moment, we remove interactive from the equation, I believe most of the problems could vanish, i.e. the top level script could be written into a static method on some special class together with the top level methods and the classes could themselves become top level classes and have their own namespaces.

With interactive as a consideration, I don't see any general path out of the problem. I guess it's just something we'll have to live with as we try to fit the square pegs of OO and compilation into the round hole of interactive scripting.

However, in the case of namespaces for classes, perhaps some specialised magic could be done to give the illusion of the namespace, whilst maintaining the nested class restriction.

**Comment by glennblock** [comment]
Thanks for filing this @bchavez

An option would be having the compiler support both script and standard C# classes with #load. It gets messy though as you think through the details.

The references would have to be defined in a sep .csx file. If the compiler sees a namespace then it could assume everything within uses the standard Roslyn compilation path. For this to work you would have to #load potentially multiple .cs files if one .cs depends on classss in another.

**Comment by glennblock** [comment]
I agree with @adamralph that this is a result of the abstraction leaking, but I also understand the constraints.

**Comment by tmat** [comment]
@bchavez "C# classes written inside a .csproj can't be reused individually outside the scope of the standard compiler/IDE". 

The classes can indeed be reused - use #r on the compiled dll. 

Although there are many technical difficulties with allowing namespaces in scripts they were not the only reason behind disallowing namespaces. There were other considerations:

1) It is not a goal of scripting to replace the C# language proper. Once you need to organize code to namespaces and classes your script is getting too big. You are actually writing a library.
2) Rarely you can #load a C# file from a project as is. Most often it has dependencies on other C# files. In common projects these dependencies aren't obvious, so you'd likely end up trying adding one by one until you get the transitive closure. A better way of referencing existing library code is to just #r the library. That's how libraries are meant to be used in the first place.
3) Allowing namespaces would introduce a lot of complexity into the design. We didn't want to add such complexity.

**Comment by bchavez** [comment]
@tmat 

>The classes can indeed be reused - use #r on the compiled dll.

I think ***the whole essence*** of using a *scripting* context is to avoid compiling code into a binary DLL on disk.

Let's not forget the friction binary DLL distribution introduces. Should we distribute a **binary** DLL with our scriptcs project? What if the end-user wants to make a change inside that **binary** DLL? We would also need to distribute the **DLL source + IDE solution files** to rebuild the binary DLL. We'll also need a 5-10GB Visual Studio install to rebuild the binary DLL with the desired changes. I'm starting to wonder why consider using a scripting context then?

* I can't reuse C# files without stripping out the namespaces.
* I'd need to carry around a full-fledged SDK toolset if I want to make any changes to rebuild a DLL.

I think these are real usability / friction issues that devs are going to care about.

>2) Rarely you can #load a C# file from a project as is. Most often it has dependencies on other C# files. 

Usually, POCOs, domain objects, utility classes, helpers classes are cases where code is **most often not dependent** on other C# files.

> 3) Allowing namespaces would introduce a lot of complexity into the design. We didn't want to add such complexity.

To me the design from the get-go should have allowed the namespace scenario. What we have now is fractured set of C# ***language features*** (depending on how your running it) that is basically incompatible with types that live under a namespace which happens to be 99% of C# code out there today.

I'm probably a bit naive here but it seems all the basic infrastructure to get namespaces working is already here:
**WhoAmI.cs**
```
using System.Reflection;

var a = Assembly.GetExecutingAssembly();
Console.WriteLine(a);

foreach( var t in a.GetTypes()){
  Console.WriteLine(t);
}
```
```
R:\>scriptcs WhoAmI.cs
R*9d2ebc5f-65ac-423e-8d79-5d64ba52de9f-#1UD, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Submission#0
```

There is legitimate assembly that namespaced types can live in ... any time Roslyn encounters a `namespace` in a scripting context, tee it off into the dynamic assembly that is already being generated?

Would the Roslyn team accept a pull request if we could get it to work? Or is this an absolute no because everything is already too complicated? Perhaps, is it easier to implement a translation layer inside `scriptcs` that pre-processes namespaced classes before passing them to the compiler: IE: `namespace Foo{ public class Bar{...} } -> public class Foo_Bar{} `?

**Comment by adamralph** [comment]
> There is legitimate assembly that namespaced types can live in ... any time Roslyn encounters a namespace in a scripting context, tee it off into the dynamic assembly that is already being generated?

The problem is that this won't work for the interactive scenario. Or at least, it means you'll be able to define a class with a given name (inc. namespace) just once in a given interactive session. In order to allow redefinition of classes, they need to be nested on the submission class, since a new one is created for each submission.

**Comment by glennblock** [comment]
Brian, the rewriting may be possible with scriptcs if a solid design can be
reached, but it might have some limitations. For example you could change a
namespace to be a public class. But you wouldn''t be able to use a using
statement for that namespace. So the question is would it be worth it.

**Comment by glennblock** [comment]
Also at was mentioned, the transitive closure issue is a problem. To use a
class you would need to load all the dependent classes as well as their
binary references. Using a compiled dll is oh so much easier :-)

**Comment by tmat** [comment]
@bchavez As I said the goal is not to replace C# proper. We may consider adding namespace support in future. Currently we focus on other scenarios. We would not accept PR that adds namespace support since it's not currently on our roadmap.

**Comment by bchavez** [comment]
@tmat What's the process to get C# namespaces on the road-map? :grin: 

Kinda feels like that issue where **I can't lambda's in the Immediate Window** all over again. But hey, at least some 8 years later we got it. :cake:

Not open for a PR, no fix for the foreseeable future. :-1: Tag this under Roslyn's scripting story as `#Limitation-By Design`, `#Leaky-Implementation`, `#is-it-real-coke-or-diet?`.

Any future devs that come across this compiler error, make your voice be heard and remind Microsoft C# namespaces don't work in Roslyn scripting. Hopefully, enough of us will pile on and push to get namespaces on the road map.

In the mean time, there is a work-around. Look at this for a decent alternative: [cs-script](http://www.csscript.net) (and [choco package here](https://chocolatey.org/packages/cs-script)) seems to resolve issues like this. Script C# as ***real*** C#. If you don't need a REPL seems like a good alternative:

**Hello.cs**
```
//css_import Domain.cs

class Script{
  static void Main(){
    var fred = new MyProject.Person();
    fred.SayHello();
  }
}
```

**Domain.cs**
```
using System;

namespace MyProject{
  public class Person{
    public void SayHello(){
      Console.WriteLine("Hello World.");
    }
  }
}
```
```
R:\>cscs Hello.cs
C# Script execution engine. Version 3.9.8.2.
Copyright (C) 2004-2014 Oleg Shilo.

Hello World.
```

:+1: works out of the box, no squiggles from VS. Startup time from the command-line seems faster. ***Mix, match, reuse*** namespaced `*.cs` `.csproj` files and loose `*.cs` scripting files to your heart's delight. Little more verbose having to define a `Main()`  but at least the C# is real.

---

> Or at least, it means you'll be able to define a class with a given name (inc. namespace) just once in a given interactive session.

@adamralph Great point Adam. I think one-time definable namespace limitation is better than where we're at right now where we currently have no support at all... Regardless, maybe not worth much discussion until they're willing to accept a PR for it.

Thanks everyone for your inputs.

A concerned C#/.NET developer,
Brian

**Comment by tmat** [comment]
@bchavez I'm glad you found a project that addresses your scenario. Feel free to use whatever tool works the best for you.
