### ISSUE TITLE
IDE0074 'Use compound assignment' should not be offered for pre-8.0 language versions

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#44793]
**Version Used**: 16.6.0, 16.6.1, 16.7-p1

```cs
class C
{
    void M(object p)
    {
        // ℹ IDE0074 Use compound assignment
        //    ↓↓
        _ = p ?? (p = new object());
    }
}
```

🛠 Use compound assignment:

```cs
class C
{
    void M(object p)
    {
        // ❌ CS8370 Feature 'coalescing assignment' is not available in C# 7.3. Please use
        // language version 8.0 or greater.
        //     ↓↓↓
        _ = (p ??= new object());
    }
}
```

Repros with either of these:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

</Project>
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by CyrusNajmabadi** [comment]
@333fred did you add support for this?

**Comment by 333fred** [comment]
No, I'm not sure who added this refactoring.

**Comment by CyrusNajmabadi** [comment]
ok. i'll find out. thanks!

**Comment by CyrusNajmabadi** [comment]
Wacky.  We literally test for this:

```
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseCompoundAssignment)]
        public async Task TestCoalesceExpressionCSharp8OrGreater()
        {
            await TestInRegularAndScript1Async(
@"public class C
{
    void M(int? a)
    {
        a [||]= a ?? 10;
    }
}",
@"public class C
{
    void M(int? a)
    {
        a ??= 10;
    }
}", new TestParameters(parseOptions: new CSharpParseOptions(LanguageVersion.CSharp8)));
        }

        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseCompoundAssignment)]
        public async Task TestCoalesceExpressionCSharp7()
        {
            await TestMissingAsync(
@"public class C
{
    void M(int? a)
    {
        a [||]= a ?? 10;
    }
}",
    new TestParameters(parseOptions: new CSharpParseOptions(LanguageVersion.CSharp7_3)));
        }
```

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you set the milestone for this to match the one in #44798?

**Comment by HugCoder** [comment]
Sorry if reopening. This issue is still present in 16.8.2. The merged "Only offer 'Use **coalesce** expression' in C#8 and above. #44798" doesn't seem to cover the issue of **compound**. I'm targetting .NET 4.6.2 if that matters.

Thanks for all you work!

**Comment by jnm2** [comment]
@HugCoder Perhaps this is fixed by the fix for #49294?

**Comment by HugCoder** [comment]
@jnm2 I did find that issue as well, but it wasn't targetting the null operator mentioned here. It certainly could be addressing the issue of the null-coalescing assignment operator as well but I'm afraid it's above my league in this topic to say if it does. I'm not sure how specific the fixes for these kind of issues are and just wanted to make sure it wasn't overlooked and viewed as solved in VS 16.8.

**Comment by jnm2** [comment]
@HugCoder I'm not sure what you're asking about. This issue is about `??=` not existing prior to C# 8. `+=` and `-=` did exist prior to C# 8. 

Can you provide a sample line of code and explain why compound assignment operators should not be offered?

**Comment by jnm2** [comment]
This issue is about IDE0074 firing incorrectly for langversion < 8 and was fixed in 16.7.P4.
#49294 is about IDE0054 firing incorrectly in a C# 9 target-typed new initializer and will be fixed in 16.9.P2.

Is your concern that IDE0054 fired incorrectly in a C# 9 target-typed new initializer, specifically recommending `??=`?
Or is there a new element involved such as `with` expressions, or am I misunderstanding?

**Comment by jnm2** [comment]
Incidentally, 16.9.P2 just dropped in the preview channel, so we'll be able to test your concern about whether it was fixed for sure in that pull request in a minute or two :D

**Comment by jnm2** [comment]
No squiggle, so it looks like #49294 was completely fixed:
![image](https://user-images.githubusercontent.com/8040367/101540173-a1944780-396d-11eb-8a47-d8a8b344a059.png)

**Comment by HugCoder** [comment]
@jnm2 Thanks for looking at this. It looks like it might be fixed now, from your test, but just to be clear I'm talking about e.g.
a = a ?? "hello";
wanting through IDE0054 to refactor it to:
a ??= "hello";
![image](https://user-images.githubusercontent.com/6286594/101543541-a7f1e600-39a4-11eb-8a13-5ba22a094240.png)
This is in VS 16.8.2 though, targetting .NET 4.6.1 (C# 7.3).

**Comment by jnm2** [comment]
That's very close to the example I have at the top of this issue which IIRC didn't repro for 16.8.2 for me earlier today with `<LangVersion>7.3</LangVersion>` in my test csproj.

In any case, 16.8.3 doesn't repro this which matches your screenshot:
```cs
class C
{
    void M(string a)
    {
        a = a ?? "hello";
    }
}
```

This makes me think there's something going on with your project that can't be seen from your description so far. E.g. are you multitargeting?
