### ISSUE TITLE
Visual studio 2015 RTM: unable to inspect any field

### ISSUE THREAD

**Issue by mcosmin222** [dotnet/roslyn#4479]
I get this smart error every single time.
I can't even get exception details because of it.

Already tried adding the magic line to the CSPROJ file. Didn't help.

error CS0012: The type 'TaskAwaiter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by Pilchie** [comment]
Where do you get this?  In the error list, or in the watch window/tooltip?

**Comment by mcosmin222** [comment]
In the watch window. 

Also when breaking on exceptions and checking exceptions details in the dialog that pops up.

The project compiles and deploys to device perfectly fine, only debugging seems to be crippled.

**Comment by cston** [comment]
@mcosmin222 Does the error occur only when debugging on the device or also when debugging with the emulator?

**Comment by mcosmin222** [comment]
it is fixed in VS 2015 RC. I got it when debugging in device.

**Comment by cston** [comment]
Adding @kelltrick

**Comment by cston** [comment]
Internal issue # 127346.

**Comment by cston** [comment]
Closing since this is tracked by internal issue # 127346.

**Comment by cston** [comment]
Closing since this is tracked by an internal issue.

**Comment by mcosmin222** [comment]
The issue was back in the release version and update 1 did not fix it.

Whenever I try to inspect fields in an async task/void method, I get various CS0012 errors regarding different assemblies (i.e the assembly in which the type i am trying to inspect resides). It is virtually impossible to do any sort of serious debug in C#/.net in VS 2015. 

Please fix this as soon as possible. My company isn't going to use VS2015 just because of this.

**Comment by cston** [comment]
@mcosmin222 Thanks for following up. Sorry this hasn't been addressed. Is there a simple repro that will hit the issue (e.g.: new _project type_; add ```async void F() { ... }```; call from ...)? Does the issue only repro when debugging on a particular device?

**Comment by cston** [comment]
@mcosmin222 Thanks for following up. Sorry this hasn't been addressed. Is there a simple repro that will hit the issue (e.g.: New Universal project; add ```async void F() { Task.Delay(1); Debugger.Break(); }```; call from `App` constructor)? Does the issue only repro when debugging on a particular device?

**Comment by mcosmin222** [comment]
SOrry for the delay again

It is quite simple really.

Make a windows phone 8.1 runtime app.

Make an async task somewhere

Call the async task from an async void.

Put a breaking point in the async void after the await.

It doesn't always reproduce, but it usually does when I need it the most.
