### ISSUE TITLE
Call Unmanaged Function using function pointers feature in C# 9

### ISSUE THREAD

**Issue by 06needhamt** [dotnet/roslyn#44794]
I was trying out the new function pointers feature in C# 9 and I couldn't work out how to call an unmanaged function pointer from managed code. Is this possible? or do we still need to use P/Invoke wrappers?

**Comment by 06needhamt** [comment]
I managed to get this working using the following code 

```
using System;
using System.Runtime.InteropServices;
public class C {
    [DllImport("MyDll.dll", CallingConvention = CallingConvention.StdCall)]
    public static extern void UnmanagedFunction();
    
    public unsafe void M() {
        delegate*<void> ManagedFunction = &UnmanagedFunction;
        
        UnmanagedFunction();
    }
}
```

**Comment by tannergooding** [comment]
`UnmanagedFunction` may be managed stub method that internally calls the actual function pointer, it isn't necessarily a direct call itself.

If you wanted to directly get the function pointer you might use the [NativeLibrary](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=netcore-3.1) API to:
1. [Load](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.load?view=netcore-3.1) the native library
2. [GetExport](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.getexport?view=netcore-3.1) the function pointer you want

The function pointer is returned as an `IntPtr` so you would need to cast it to the appropriate function pointer, which looks to be: `delegate* stdcall<void>` in this case.

**Comment by 06needhamt** [comment]
Thanks I'll take a look at this as it seems to be a better solution than what I have.

**Comment by 06needhamt** [comment]
Thanks I managed to get it working with @tannergooding's solution.
