### ISSUE TITLE
Finalize the design for the shape of the BaseTypeSyntax in relation to the argument list for records

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#44795]
https://github.com/dotnet/roslyn/pull/44733#discussion_r433449588

It feels like this is a case where a different node derived from `BaseTypeSyntax` would make more sense than adding arguments to `SimpleBaseTypeSyntax`

This anticipated future scenario (adding arguments in the base clause for records) is precisely the reason that `BaseTypeSyntax` was separated from `SimpleBaseTypeSyntax` in the first place.

**Comment by AlekseyTs** [comment]
Also need to figure out SemanticModel behavior. How one gets the constructor symbol vs. the type symbol.

**Comment by gafter** [comment]
The alternative to what is in the PR is as follows:

We add to the existing nodes

```xml
  <AbstractNode Name="BaseTypeSyntax" Base="CSharpSyntaxNode">
    <TypeComment>
      <summary>Provides the base class from which the classes that represent base type syntax nodes are derived. This is an abstract class.</summary>
    </TypeComment>
    <Field Name="Type" Type="TypeSyntax">
    </Field>
  </AbstractNode>

  <Node Name="SimpleBaseTypeSyntax" Base="BaseTypeSyntax">
    <Kind Name="SimpleBaseType"/>
    <Field Name="Type" Type="TypeSyntax" Override="true"/>
  </Node>
```

the following

```xml
  <Node Name="PrimaryConstructorBaseTypeSyntax" Base="BaseTypeSyntax">
    <Kind Name="PrimaryConstructorBaseType"/>
    <Field Name="Type" Type="TypeSyntax" Override="true"/>
    <Field Name="ArgumentList" Type="ArgumentListSyntax"/>
  </Node>
```

**Comment by gafter** [comment]
By contrast, the approach in the PR places `ArgumentList` in `SimpleBaseTypeSyntax`

**Comment by AlekseyTs** [comment]
The API review team settled on the new proposal from above. I.e. new type derived from BaseTypeSyntax. We also decided that SemanticModel.GetSymbolInfo API should return base constructor information for this node. Same for GetMemberGroup API

**Comment by AlekseyTs** [comment]
It turns out GetMemberGroup always returns an empty set for a regular constructor initializer. Will keep its behavior the same for PrimaryConstructorBaseTypeSyntax. If later users request this API working differently (apparently no-one uses it for constructor initializers today), we'll revisit its behavior for all forms of constructor initializers.
