### ISSUE TITLE
Bug: The new managed Expression Evaluator ignores DEBUGPROP_INFO_NOFUNCEVAL

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#448]
In *VS2010 and VS2012*, a consumer could call the debugger API's `IDebugProperty3.EnumChildren` passing in only the `DEBUGPROP_INFO_NAME` flag, to obtain only the names of the expressions,  without incurring the performance cost of the EE actually evaluating their values and performing func-evals. We've built a lot of functionality around this ability. 

In *VS2013*, this ability was broken. I reported it on [Connect ticket 813045] (https://connect.microsoft.com/VisualStudio/feedback/details/813045/bug-in-new-managed-debug-engine-idebugproperty2s-children-are-func-evalled-when-value-was-not-requested), and was offered a workaround of using `DEBUGPROP_INFO_NOFUNCEVAL`, which works.

In *VS2015 CTP5*, both the original approach and the suggested workaround no longer work. 

To reproduce:

1. Run the  [scenario I described](https://connect.microsoft.com/VisualStudio/feedback/details/813045/bug-in-new-managed-debug-engine-idebugproperty2s-children-are-func-evalled-when-value-was-not-requested) in VS2015  instead of VS2013.
2. Apply the workaround suggested by Azeem Khan on the Connect case and re-run the scenario. 
Observe that the workaround doesn't work in VS2015 CTP5.
3. Go into Tools->Options and check the "Use the legacy C# and VB expression evaluators" option. Re-run the scenario and observe that the workaround now works.

**Comment by OmerRaviv** [comment]
This may be of interest to @cston or @amcasey . I think this is a fairly dangerous breaking change - any 3rd party consumers that currently use DEBUGPROP_INFO_NOFUNCEVAL expecting that the flag will protect them from causing potentially harmful side effects in the debuggee will break, as the flag will work fine in VS2013 and lower, but is completely ignored in VS2015.

**Comment by amcasey** [comment]
@OmerRaviv Thanks!  I'm following up with a debugger dev to see if there's a flag we're failing to consume in the Result Provider.

**Comment by pnelsonmsft** [comment]
@OmerRaviv, Thanks for reporting this issue!  This is a bug we are aware of and are fixing.  The fix won't make the next CTP, but it will be fixed by RTM of Visual Studio 2015.
