### ISSUE TITLE
Intellisense does not recognize parameter of locally assigned lambda

### ISSUE THREAD

**Issue by davidroth** [dotnet/roslyn#4480]
In VS2015, Intellisense does not recognize the type of "sender" and "e" of the following lambda expression, if the lambda is assigned to a variable and not passed as a method param.

```csharp
var handler = new TransactionCompletedEventHandler((sender, e) =>
            {
                e. // No completions shown (see screenshot)
            });
```

![image](https://cloud.githubusercontent.com/assets/338856/9197737/433f7874-4037-11e5-8c59-67d066aa769a.png)

As you can see in the screenshot, only a question mark (?) is shown.

**Comment by Pilchie** [comment]
Looks like another case where the compiler doesn't return a type for the parameter.

**Comment by gafter** [comment]
This problem does not occur in the current `master` branch (milestone 2.0). I'll add a unit test to ensure it keeps working.
