### ISSUE TITLE
Precedence of diagnostic severity settings from compilation options, editorconfig and global analyzerconfig

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44804]
Extracted out from https://github.com/dotnet/roslyn/issues/37876#issuecomment-635491398 and https://github.com/dotnet/roslyn/issues/43051#issuecomment-630326648

Currently, diagnostic severity configuration settings can be provided to the compiler in following ways:

1. CompilationOptions.SpecificDiagnosticOptions (populated from command line `/nowarn`, `/warnaserror` and ruleset files)
2. Editoconfig files
3. Global analyzer config files

When there are entries for the same diagnostic ID from multiple sources, following precedence order is followed today:

1. Editorconfig wins over the other two.
2. Global analyzer config diagnostic severity setting wins over SpecificDiagnosticOptions.

This has led to following 2 core issues:
1. Given that global analyzer config files will invariably come from tooling/NuGet packages, it seems wrong for the settings from them to override the user provided command line SpecificDiagnosticOptions. I think we need to implemented Andy's suggestion in https://github.com/dotnet/roslyn/issues/37876#issuecomment-635493331 to address this. This would also lead to some work on the IDE side. For example, all places where we read the ruleset file to generate SpecificDiagnosticOptions would need to now read global analyzer config files (for example [here](http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/RuleSets/IRuleSetFile.cs,afd4c39b90e560c1,references)). I think we need to do this change soon, otherwise it would become a breaking change in future.

2. https://github.com/dotnet/roslyn/issues/43051 shows a side effect of editorconfig settings winning over command line SpecificDiagnosticOptions causing TreatWarningsAsErrors to not work as user expected. Changing this now would likely be a big breaking change, and defeat the original purpose of allowing per-file or directory overrides to project level diagnostic configuration. Do we have any alternatives/workarounds here which can help users?

I think we need to make a final call on the precedence order and call out the supported scenarios and recommended workarounds where required.

**Comment by mavasani** [comment]
Tagging @chsienki @agocke @jaredpar @jasonmalinowski @sharwell

**Comment by mavasani** [comment]
Actually, putting some more thought into this, I think @agocke's [proposal](https://github.com/dotnet/roslyn/issues/37876#issuecomment-635493331) to add global analyzer config options to `CompilationOptions.SpecificDiagnosticOptions` should resolve all the issues here.

- Diagnostic settings from global analyzer config have the least precedence
- https://github.com/dotnet/roslyn/issues/43051 can be resolved by recommending users to move their diagnostic entries from editorconfig to global analyzer config file. Basically, any diagnostic settings that need lesser precedence then command line arguments should be added to global analyzer config file and any per-file or per-directory overrides that must take precedence over command line arguments should go in editorconfig.
- Global analyzer config becomes a complete 1-to-1 replacement for ruleset files, i.e. resolves https://github.com/dotnet/roslyn/issues/38042 and one should never ever need to create a ruleset again.

@chsienki @agocke Can we prioritize this change for 16.7 before we ship the first release with global analyzer config support?

**Comment by agocke** [comment]
I will not have time to work on this for 16.7

**Comment by mavasani** [comment]
I believe @chsienki already has a PR to fix it: https://github.com/dotnet/roslyn/pull/45871. I update the PR description to make this explicit.
