### ISSUE TITLE
[Feature] Primary constructors

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#4481]
Last known mention in the roadmap:

https://roslyn.codeplex.com/wikipage?title=Language%20feature%20status&version=37

Official comment:

https://roslyn.codeplex.com/discussions/568820

> ...primary constructors could grow up to become a full-blown record feature...

Is the latter really a direct expansion of the former?

Looking at *certain* other languages it seems that while related they seem to be separate features:

https://msdn.microsoft.com/en-us/library/dd233192.aspx

https://msdn.microsoft.com/en-us/library/dd233184.aspx

**Comment by HaloFour** [comment]
What really bothered me about primary constructors is this push to try to have them cover virtually every use case for normal constructors.  Most of those use cases made little sense and required bizarre scoping rules and some nasty syntax.

I'd love to see primary constructors return but I think that they need a well defined and strict charter.  I think attaching them to record types makes a lot of sense.  I'd personally be fine if they were permitted for non-record classes as well, but limited to very specific simple scenarios.  If you need more functionality there are always normal constructors.

**Comment by gafter** [comment]
@dsaf The short answer is "yes". Part of the reason that primary constructors were put off was that adding them in C# 6 would have nailed down the semantics, and those semantics would not have included the things we're considering for "records".
