### ISSUE TITLE
Converting nint to void* currently uses the `IntPtr` user-defined operator

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#44810]
The following program:
```csharp
    public void* M(nint x) {
        return (void*)x;
    }
    
    public void* M(nuint x) {
        return (void*)x;
    }
```

Generates the following IL:
```
    .method public hidebysig 
        instance void* M (
            native int x
        ) cil managed 
    {
        .param [1]
            .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = (
                01 00 00 00
            )
        // Method begins at RVA 0x207f
        // Code size 7 (0x7)
        .maxstack 8

        IL_0000: ldarg.1
        IL_0001: call void* [System.Private.CoreLib]System.IntPtr::op_Explicit(native int)
        IL_0006: ret
    } // end of method C::M

    .method public hidebysig 
        instance void* M (
            native uint x
        ) cil managed 
    {
        .param [1]
            .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = (
                01 00 00 00
            )
        // Method begins at RVA 0x2087
        // Code size 7 (0x7)
        .maxstack 8

        IL_0000: ldarg.1
        IL_0001: call void* [System.Private.CoreLib]System.UIntPtr::op_Explicit(native uint)
        IL_0006: ret
    } // end of method C::M
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHAZgAIBXAOyggDM5L9KBhSgb1Mr9ao4ALACpKAWQAUtNLRiUAHgEpuvfupwB2SpOEilCgNxq+AXxOULFVqInTqs+ctUl1G7btEHjr/ud98VoK2Uo6KKjwBblo6et4W/upBNmJSDnLhLm78MZ76RgmkpkA==

I would expect `nint` or `nuint` being converted to/from `void*` to be a nop given it is already of the appropriate size and there is not a `conv` method for converting to a pointer.
Converting `int` or `uint` to `void*` use `conv.i` and `conv.u`, respectively (which converts to a `native int` or `native unsigned int`

**Comment by tannergooding** [comment]
CC. @cston

**Comment by jaredpar** [comment]
Is this a bug or expected behavior? Given that `IntPtr` defines these operators isn't the design that `nint` should be respecting them?

**Comment by tannergooding** [comment]
I thought we were explicitly ignoring user-defined operators because they may have undesired behavior. e.g `IntPtr` also defines `IntPtr operator +(IntPtr, int)` but respecting that defeats the purpose of `nint` as it doesn't respect checked/unchecked contexts.

As from https://github.com/dotnet/csharplang/blob/master/proposals/native-integers.md#type-members,
> The following members of System.IntPtr and System.UIntPtr are explicitly excluded from nint or nuint:
> ```csharp
> // constructors
> // arithmetic operators
> // implicit and explicit conversions
> public static readonly IntPtr Zero; // use 0 instead
> public static int Size { get; }     // use sizeof() instead
> public static IntPtr Add(IntPtr pointer, int offset);
> public static IntPtr Subtract(IntPtr pointer, int offset);
> public int ToInt32();
> public long ToInt64();
> public void* ToPointer();
> ```
