### ISSUE TITLE
A bug in Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [dotnet/roslyn#44813]
https://github.com/dotnet/roslyn/blob/1b75734dee6db086b7705ae37a9035b79232bbb8/eng/docker/Mono/Dockerfile#L21
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential bug above. Is it a bug? we believe that there are 2 rm commands in this line. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by wangluochao902** [comment]
It seems it is allowed to have multiple rm in the same command line, so it is not a bug.

**Comment by jinujoseph** [comment]
cc @chsienki
