### ISSUE TITLE
Unable to rename a variable containing an underscore.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44825]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/598275/unable-to-rename-a-variable-containing-an-undersco.html)._

---
I declare a variable as follows:
Dim AS_Guid As String

I can right-click on the variable name and select &quot;Rename&quot; from the context menu or select the variable and press ctrl+r, ctrl+r to open the rename panel.

In the rename panel, I check the box for &quot;Include Strings&quot;

The variable name is highlighted in green and if I start typing I can rename it.  The problem is that the new variable name is TS_Guid. When I attempt to rename it, I cannot type the &quot;_&quot; underscore. When the &quot;Include Strings&quot; box is checked the underscore character is not available.

---
#### Visual Studio Feedback System on 6/10/2019, 00:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 06:33 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
#### Stevo Woodson solved on 3/28/2020, 11:28 AM, 0 votes: 

<p>I am using Visual Studio Community 2019 (Version 16.4.3), and also having the same issue. When I am renaming, if I check any of the boxes (Include comments, Include strings, Preview changes) before typing an underscore, it prevents me from typing an underscore and the box is unchecked.</p><p><br>The workaround I've found is to type the underscore in the rename first, and then click any needed checkboxes. I was able to confirm that this changed the name in the comments too (including the underscore).</p><p>Hope that helps.</p>

**Comment by CyrusNajmabadi** [comment]
I see what the problem is.  After clicking an item in the rename overlay window in the upper right, there is some sort of focus issue.  So `_` is being eaten by that window.  If you click in the buffer again, you can type the `_`.  Not sure what's up here as i'm not sure how things are supposed to work here, or how wpf/input-capturing works in this case.

@jasonmalinowski @dpoeschl , any ideas?

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me with our new UI.  w00t.
