### ISSUE TITLE
Autocompletion for override keyword in the bottom of razer component works wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44828]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1048763/autocompletion-for-override-keyword-in-the-bottom-40.html)._

---
[regression] [worked-in:16.5]
I have razor component (.razor) with @code section.
I go to bottom of this section, type 'override' and press the space. Intellisense suggests we to choose some methods to overrode. When I choose any (i.e. OnParametersSetAsync) and press Enter or Tab, I get only 'protecte}' or 'public o{' intead of 'override'.
If I press Ctrl+Z and press the space again, the method chosen previously became absent in autocompletion list but any other override autocompletion will work as expected.
By the way, third attempt (undo again, press space again, choose some method) will again act exactly like first one.

There's also partly related minor issue: auto completion use wrong tab settings. In my case it uses two tabs instead of four spaces.

Problem begin on some preview of 16.6 and leaks to current production version.

---
#### Visual Studio Feedback System on 5/25/2020, 11:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as external as razor scenarios are owned by razor team.
