### ISSUE TITLE
Generic overload preferred to specialized overload when it has optional parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44827]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/637884/generic-overload-preferred-to-specialized-overload.html)._

---
Given two methods of the same name accessible from one location in code, one generic and one type-specialized, the generic version is preferred over the specialized version, if the specialized overload has optional parameters.

See the following example:
var result = MyMethod(&quot;abc&quot;);

A specialized version expecting a string should always be preferred over a generic version of &quot;MyMethod&quot;, regardless of whether the string-specialized version can accept additional, optional parameters, since - from the usage - one would expect that an overload expecting specifically a string would be selected over a generic version of the same method.

This deficiency in the C# compiler limits the development of library-code as you - as a developer - need to specifically avoid optional parameters in overloaded methods, where a generic overload exists.

We look forward to the fix to this issue :)

Best regards,
Kenneth Ry Ulrik

---
#### Visual Studio Feedback System on 7/9/2019, 03:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:21 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### KRU on 10/8/2019, 03:25 AM: 

<p>Hi,</p><p>Even if this request has been overlooked by my peers (popularity), it is a rather clear issue and should be a low-hanging fruit, for the development team.</p><p>I would be disappointed to learn that the issue will be scrapped completely, but I agree with the severity that I assigned it myself, but even low-priority issues should be fixed eventually, in my humble opinion.</p><p>Could I have an update on whether unlikely means never, or alternatively, when a fix for this issue might become relevant?</p><p>Thank you.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Yes.  THis is by design and cannot be changed without breaking changes.   Customer can raise proposals on what tehy would like to change in the language over at dotnet/csharplang.
