### ISSUE TITLE
VS LSP: Go to implementation/declaration produces inaccurate/duplicate results

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#44846]
**Version Used**: 16.7.0 Preview 3.0 [30203.137.master]

**Steps to Reproduce**:

![gotoimplementationbug](https://user-images.githubusercontent.com/1579269/83704310-a1824c00-a5c6-11ea-8c7f-7d7416140936.gif)

![image](https://user-images.githubusercontent.com/1579269/83704406-dd1d1600-a5c6-11ea-8258-cd3b0e4ea74c.png)

cc @dibarbet @NTaylorMullen

**Comment by TanayParikh** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/42746?
