### ISSUE TITLE
Autocompletion for Search and Replace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44842]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1057300/autocompletion-for-search-and-replace.html)._

---
Example:
I have  method calls with the argument **Stories**. Now I create a constant and after it, I want to replace all occurrences of **"Stories"** with the new constant **StoryFolder**.

```csharp
private const string StoryFolder = "Stories";

public void TestMethod() {
    Directory.GetFiles("Stories");
    AnotherMethod("Stories");
}
```

Now I select **("Stories"** and press **h** to search and replace it.
Then window on the top right corner shows me:
_("Stories"_
_Replace..._

Now, in the replace field, I type in `Story` and nothing happens. There could be an autocompletion which could offer me **StoryFolder**.
Since this autocompletion is optional, you can simply type the thing in it, what you would do at the moment, so this wouldn't break anything if you don't want to use autocompletion.

---
#### Visual Studio Feedback System on 6/1/2020, 02:51 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
@olegtk routing to you guys.  Up to you if you want your search experiences to light up any language smarts.  Personally, i wouldn't not involve the language, but instead perhaps just have the FindReplace entrypoints just look at the words in the file and offer those as suggestions when typing in the list
