### ISSUE TITLE
Disable auto space addition to +-*/ symbols

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44844]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1061105/question-disable-auto-space-addition-to-symbols.html)._

---
Now, if I type, for example `Matrix[i, 3*i+1] = Math.Pow(Matrix[i, 3*i], 2)` after I add ";" it's transforms to `Matrix[i, 3 * i + 1] = Math.Pow(Matrix[i, 3 * i], 2);` – VS automatically adding spaces to ariphmetical operators. I don't like that. Can I disable auto space addition?

---
#### Visual Studio Feedback System on 6/3/2020, 02:47 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This is controlled by this option:

![image](https://user-images.githubusercontent.com/1408396/83704732-cdea9800-a5c7-11ea-885a-23e0f6c7b517.png)
