### ISSUE TITLE
Add an option to collapse using section automatically

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44843]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1062526/add-an-option-to-collapse-using-section-automatica.html)._

---
<p>Some C# files might have a long list of `using` statements. In this cases the first thing I do after opening the file is collapsing them.</p> <p>It would be great to have an option to do it automatically for all files.</p> <p>Also it might be useful for ES/TS files with `import` statements.</p>

---
#### Roman Koliada on 6/3/2020, 02:08 AM: 

<p>BTW, I believe that's how it's done in Rider.</p>

#### Visual Studio Feedback System on 6/3/2020, 02:47 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by NTaylorMullen** [comment]
## Conclusion & Next Steps: 

Two new options: 
- Collapse usings on file open (on by default) 
- Collapse #regions on file open (on by default) 

**Quirk:** If both options are set and a user has usings wrapped in regions do not auto-close usings so the user doesn't have to expand the group twice.
