### ISSUE TITLE
Create an integration test for applicable refactorings in light bulb under caret

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#44855]
Would *really* like an integration test here.

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/44796#issuecomment-638393431_

Also handle PR review comments from that PR

**Comment by mavasani** [comment]
I attempted https://github.com/mavasani/roslyn/commit/5f81ac14bb1320759bd0f1c1f98b224ab1e461dd as per suggestion in https://github.com/dotnet/roslyn/issues/44594#issuecomment-640971975, but that still invokes the lightbulb in margin. Assigning to @sharwell for assistance.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
