### ISSUE TITLE
I can't build the CSharpSyntaxTree from Roslyn

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44869]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/888817/i-cant-build-the-csharpsyntaxtree-from-roslyn.html)._

---
<p>Hello! I can compile C# programs to EXE using Roslyn:</p><pre>var syntaxTree = CSharpSyntaxTree.ParseText(
    @&quot;
using System;
class Program {
    static void Main(string[] args) {
        Console.WriteLine(1);
    }
}
    &quot;
);

CSharpCompilation compilation = CSharpCompilation.Create(
    &quot;assemblyName&quot;,
    new[] { syntaxTree },
    new[] { MetadataReference.CreateFromFile(typeof(object). Assembly.Location) },
    new CSharpCompilationOptions(OutputKind.ConsoleApplication)
);

using (var exeStream = new FileStream(&quot;.. /.. /program.exe&quot;, FileMode.Create))
using (var pdbStream = new FileStream(&quot;.. /.. /program.pdb&quot;, FileMode.Create))
{
    var emitResult = compilation. Emit(exeStream, pdbStream);
    if (!emitResult.Success)
        foreach (var error in emitResult.Diagnostics)
            Console.WriteLine(error); 
}
</pre><p>But I don't understand how to build the syntax tree? CSharpSyntaxTree, CSharpSyntaxTreeNode are abstract classes and I can't create objects of them. I want to compile my simple language via Roslyn. Of course I can translate the code to C# and compile it but, if it is possible, I want to parse my language, build the syntax tree and use it for compilation</p>

---
#### Visual Studio Feedback System on 1/18/2020, 08:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 2/20/2020, 05:59 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
> But I don't understand how to build the syntax tree?

You can do that in a couple of ways.

1. Calling CSharpSyntaxTree.ParseText like you have.
2. Using SyntaxFactory.XXX to construct nodes

**Comment by CyrusNajmabadi** [comment]
Note: these questions are well suited to gitter.im/dotnet/roslyn or discord.gg/csharp (#roslyn channel).

**Comment by PathogenDavid** [comment]
As Cyrus said, you probably want to use [`SyntaxFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxfactory?view=roslyn-dotnet).

[Roslyn Quoter](http://roslynquoter.azurewebsites.net/) is a neat tool that translates C# code into `SyntaxFactory` calls.

Here's an example of what it generates for your code:

```csharp
CompilationUnit()
.WithUsings(
    SingletonList<UsingDirectiveSyntax>(
        UsingDirective(
            IdentifierName("System"))))
.WithMembers(
    SingletonList<MemberDeclarationSyntax>(
        ClassDeclaration("Program")
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                MethodDeclaration(
                    PredefinedType(
                        Token(SyntaxKind.VoidKeyword)),
                    Identifier("Main"))
                .WithModifiers(
                    TokenList(
                        Token(SyntaxKind.StaticKeyword)))
                .WithParameterList(
                    ParameterList(
                        SingletonSeparatedList<ParameterSyntax>(
                            Parameter(
                                Identifier("args"))
                            .WithType(
                                ArrayType(
                                    PredefinedType(
                                        Token(SyntaxKind.StringKeyword)))
                                .WithRankSpecifiers(
                                    SingletonList<ArrayRankSpecifierSyntax>(
                                        ArrayRankSpecifier(
                                            SingletonSeparatedList<ExpressionSyntax>(
                                                OmittedArraySizeExpression()))))))))
                .WithBody(
                    Block(
                        SingletonList<StatementSyntax>(
                            ExpressionStatement(
                                InvocationExpression(
                                    MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("Console"),
                                        IdentifierName("WriteLine")))
                                .WithArgumentList(
                                    ArgumentList(
                                        SingletonSeparatedList<ArgumentSyntax>(
                                            Argument(
                                                LiteralExpression(
                                                    SyntaxKind.NumericLiteralExpression,
                                                    Literal(1))))))))))))))
.NormalizeWhitespace()
```
