### ISSUE TITLE
Completion interferes with typing range expression.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#44862]
I had this code:

```c#
        private static (string text, string suffix) SplitMemberName(string memberString)
        {
            for (var i = 0; i < memberString.Length; i++)
            {
                if (!SyntaxFacts.IsIdentifierPartCharacter(memberString[i]))
                    return (memberString[0..i], memberString[i]);
            }

            return (memberString, "");
        }
```

Typing it produced:

![image](https://user-images.githubusercontent.com/4564579/83811601-f5e10680-a66e-11ea-8391-07b38803cf7d.png)

So typing the second dot after the `i` resulted in:

![image](https://user-images.githubusercontent.com/4564579/83811629-02655f00-a66f-11ea-965e-431779745cf2.png)

instead of

![image](https://user-images.githubusercontent.com/4564579/83811658-101ae480-a66f-11ea-97e0-04fac05798d2.png)

**Comment by CyrusNajmabadi** [comment]
@allisonchou want to take a look?

**Comment by allisonchou** [comment]
@CyrusNajmabadi yes, sure! I'll look into it.

**Comment by allisonchou** [comment]
According to @genlu, this is likely an Intellicode bug, so reassigning to their team.

**Comment by sharwell** [comment]
Moved to AB#1244362.
