### ISSUE TITLE
Visual Studio won't Auto Complete curly Braces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44887]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1053217/visual-studio-wont-auto-complete-curly-braces.html)._

---
Hello,

I am very new to using Visual Studio and Programming in C#. I have been following a tutorial and have noticed something odd about my Visual Studio and the one in the Video. Every time I want to create something inside a method, say for example a if statement what keeps happenning is the curly braces will not go to a new line. Below is what happens I have hit enter a few times to actually set it up properly.

```
if (true) { }
```

What I want to happen:

```
if (true) 
{
   some code
}
```

I have looked on a lot of different websites. I have tried, Checked and unchecked the following:

- Tools > Options > Text Editor > C# > General > "Automatic brace completion"
- Tools > Options > Text Editor > C# > Code Style > Formatting > "Automatically format block on }"
- Tools > Options > Text Editor > C# > Code Style > Formatting > New Lines > "Checked everything in there"
- Tools > Options > Text Editor > C# > Code Style > Formatting > Wrapping > "Un checked Leave block on single line"
- I reset the settings
- I have updated to the most recent build
- I have even reinstalled Visual Studio
- I also had my friend send me his settings because his is working

All of these I have tried and still nothing. If anyone can help that would be greatly appreciated.

---
#### Visual Studio Feedback System on 5/27/2020, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 6/3/2020, 10:53 AM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Could you please share the details regarding exact sequence of keystrokes are you using, the behavior you are seeing and the behavior you are expecting? Sample projects and snapshots will also be helpful.</p>

#### Wesley Sorrentino on 6/3/2020, 11:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is to support people writing on a single line.  After you write `{`, we'll autocomplete and place you between `{ }`.  Pressing `enter` will give you teh result you want.

**Comment by osman1309** [comment]
Tools -> Options -> Text Editor -> C# -> Code Style -> Formatting> Automatically format block an } The tick is removed and the arrow is called, then the tick is re-entered.
