### ISSUE TITLE
Code Lens doesn't update untill the file is reopened.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44888]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1060693/code-lens-doesnt-update-untill-the-file-is-reopene.html)._

---
[regression] [worked-in:16.5]
I had to refactor some async calls and change them all to synchronous. So I used Code Lens for that - I've seen 5 places in code my async method is called. I clicked on reference link and changed the first reference not to call my async method. So Code Lens should show only 4 references instead of 5. This doesn't happen even if I save the changed file. The only way to make Code Lens show correct number of references is to close the file with Code Lens annotation and reopen it. I believe it worked correctly in previous version of Visual Studio. Of course the project type is Blazor / .NET Core 3.1.

---
#### Visual Studio Feedback System on 6/3/2020, 01:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Can't repro this at all with intpreview or master.  Codelens seems to be updating fine.  Would need more info from the customer on a repro.

**Comment by eusebiu** [comment]
This happens for built in CodeLens (e.g. References). Also, there is no API in the ```IAsyncCodeLensDataPointProvider``` or ```IAsyncCodeLensDataPoint``` to invalidate a datapoint and force the Code Lens data point to refresh the details and the only way to refresh the details is to close and reopen the document.
There should be a way to invalidate the CodeLens from the API perspective - e.g. when text content is updated - and force VS to recompute the details.
In the following pictures, the reference count is 1 (but should be 2 - 1 in interface and 1 in the call) and after reopening the document the references gets to 2.
Before close:
![image](https://github.com/dotnet/roslyn/assets/414589/af0d2c63-c42c-4339-9397-ca4bf59bdcaa)
After close:
![image](https://github.com/dotnet/roslyn/assets/414589/2501b4fd-702a-4a17-a694-d298fb603e1f)
