### ISSUE TITLE
IDE0007 raised when type is not apparent

### ISSUE THREAD

**Issue by manfred-brands** [dotnet/roslyn#44884]
**Version Used**: 
.NET Core SDK 3.1.300

**Steps to Reproduce**:

csharp_style_var_when_type_is_apparent = true:suggestion 

`List<string> listOfUnknownType = enumerable.ToList();`

**Expected Behavior**:
Not raising IDE0007

**Actual Behavior**:
Raises IDE0007.

The method TypeStyleHelper.IsPossibleConversionMethod doesn't take generics into account. The Comment suggests that it is for 'Convert.ToString'. When using 'var' for methods like ToList and ToImmutableList it would not be apparent what kind of list it is. So 'var' should not be used.

**Comment by Youssef1313** [comment]
I haven't tested myself, but did you try to set `csharp_style_var_elsewhere` to `false`?

The config you used (`csharp_style_var_when_type_is_apparent`) is for "when type is apparent", and in the code you posted the type is not apparent.

**Comment by Youssef1313** [comment]
> 
> 
> I haven't tested myself, but did you try to set `csharp_style_var_elsewhere` to `false`?
> 
> The config you used (`csharp_style_var_when_type_is_apparent`) is for "when type is apparent", and in the code you posted the type is not apparent.

I seem to be wrong here. roslyn considers the type as apparent in that case. (See https://github.com/dotnet/roslyn/issues/29657).

**Comment by CyrusNajmabadi** [comment]
This is intentional.  Improvements here are tracked through https://github.com/dotnet/roslyn/issues/29657.  We likely cannot change this specific option as it would break existing codebases.  We might add a new feature in the future.
