### ISSUE TITLE
Rename Not Working in projected C# scenarios (Blazor Code)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44891]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1061540/rename-not-working-in-blazor-code.html)._

---
Hi Team,

Using VS Community 2019 V16.6.0 on Windows 10, when creating and using Blazor WebAssembly App project template, in a Blazor component, I am not seeing the Rename refactoring option when I right click a variable or method name. But rename does work in JavaScript code in the same project.

Reproduce steps:

dotnet/aspnetcore#1. Create a new Blazor WebAssembly App project.

dotnet/aspnetcore#2. Add some codes in .razor file for example Index.razor and includes methods and variables. 

dotnet/aspnetcore#3. move cursor to focus on the method's name or variable, then right-click it, you will not find the "Rename" option in the list.

If this is a potential issue, please fix it.

Thanks.

---
#### Visual Studio Feedback System on 6/3/2020, 00:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Repro:
1. Create a default Blazor app
2. Open Counter.razor
3. right click on `currentCount`
4. See no rename option:
![image](https://user-images.githubusercontent.com/2008729/83907866-f7680880-a71a-11ea-94c4-dbeb60282618.png)

**Comment by iiKuzmychov** [comment]
Why after 2 years it still doesn't work correctly??

**Comment by CyrusNajmabadi** [comment]
@iiKuzmychov this is currently on the backlog.  So this does not take priority over all the other work we have on our plates.  If you'd like to contribute a fix here though, we'd help get that in!

**Comment by CyrusNajmabadi** [comment]
Closing out as this would be handled by razor.
