### ISSUE TITLE
Cannot inherit from abstract parameter-less record

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#44898]
```C#
abstract record A;
record B(object P) : A;
```
```
(2,8): error CS0122: 'A.A()' is inaccessible due to its protection level
```

**Comment by AlekseyTs** [comment]
The binder chain used for the copy constructor is wrong. It is missing the binder for the type. Works fine if B has body, i.e. ends with ```{ }``` instead of ```;```.

**Comment by AlekseyTs** [comment]
The same issue with synthesized parameter-less constructor, non-primary one (when there are no record parameters).
