### ISSUE TITLE
BindWithExpression should handle hiding/overriding Clone

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#44908]
This issue is referenced in source

https://github.com/dotnet/roslyn/blob/f089d871f13fac5f81eda073957f94ab6c5a7f14/src/Compilers/CSharp/Portable/Binder/Binder_WithExpression.cs#L53

note that other PROTOTYPE comments in the method are addressed by #44582

**Comment by jcouv** [comment]
`Clone` is no longer speakable, so cannot be hidden/overriden. Closing

**Comment by RikkiGibson** [comment]
When closing such issues could we please make sure to delete references to the issue in code?

**Comment by jcouv** [comment]
Thanks for catching that. Re-opening until we remove references
