### ISSUE TITLE
Rename conflict resolution adds extra parentheses to a method call

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4490]
In the following code, rename F1 to F2.

```VB
Class A
    Sub F1(e As XElement, b As Integer)

    End Sub
End Class

Class B
    Inherits A

    Sub F2(e As XElement, b As Integer)

    End Sub

    Sub G()
        F1(<foo>bad</foo>, 1)
    End Sub

End Class
```

![image](https://cloud.githubusercontent.com/assets/41759/9210183/a2f5663c-402f-11e5-8134-4c8644fec3a7.png)

Extra parentheses are added around the XML literal.

**Comment by DustinCampbell** [comment]
PR #4609 is out to fix this issue.
