### ISSUE TITLE
Auto-completion is prefers nuint over null

### ISSUE THREAD

**Issue by Fydar** [dotnet/roslyn#44916]
**Version Used**: Visual Studio 2019, 16.7.0 Preview 2.0

The `nuint` keyword (from dotnet/csharplang#435) is being preferred over `null` in auto-completion.

This has created an inconsistent IDE experience across versions. I'm accustomed to entering `nu` + `tab` for `null`.

**Steps to Reproduce**:

1. Create a project using C# 9.0.
2. Start typing an equality comparison, in my case I wrote `if (node == nu`.

    ![autocomplete-to-null](https://user-images.githubusercontent.com/19309165/83949960-f7513100-a81e-11ea-9298-500208efa74a.gif)

**Expected Behavior**:

The first auto-correction result should be `null`.

**Actual Behavior**:

The first auto-correction result is `nuint`.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/44451
