### ISSUE TITLE
ParameterInfo doesn't trigger on record base syntax

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44919]
On `: this(0, 0)`, ParameterInfo and SignatureHelp work fine. Example:
![image](https://user-images.githubusercontent.com/12466233/83951495-96a60200-a7e6-11ea-92a6-c2f015edb93e.png)

But on an argument in record base syntax, they do not trigger or display at all when invoked. Example:
![image](https://user-images.githubusercontent.com/12466233/83951512-b6d5c100-a7e6-11ea-81a3-892fc1325e4a.png)

Not sure whether it's a compiler or IDE problem yet.

The compiler should at least provide a semantic model API to figure out which constructor is used.

Update: This is critical to fix in 16.8, because you get an annoying completion.

Relates to https://github.com/dotnet/roslyn/issues/44904

**Comment by AlekseyTs** [comment]
@jcouv Does the problem still exist?

**Comment by jcouv** [comment]
@AlekseyTs Yes, the problem is still there.
