### ISSUE TITLE
Record types should implement IEquatable<T>

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#44920]
Record types should implement `IEquatable<T>`. The types already synthesize a `public virtual bool Equals(T other)` method.

**Comment by HaloFour** [comment]
Does this mean all structs are going to start implementing `IEquatable<T>` automatically?

**Comment by CyrusNajmabadi** [comment]
Structs are not currently records.  But there are open discussions in LDM with runtime about the future of structs/records.  How IEquatable plays into that is part of these current discussions.

**Comment by cston** [comment]
Implemented in #44994.
