### ISSUE TITLE
Switch expression calls implicit conversion operator for generic class

### ISSUE THREAD

**Issue by KelDazan** [dotnet/roslyn#44937]
**Version Used**: 
Visual studio 16.6.0

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

**Steps to Reproduce**:

Run simulation
```cs
public abstract class Base
{
	public string Name { get; set; }
}

public class DerivedStruct<T> : Base
	where T : struct
{
	public static implicit operator DerivedClass<string>(DerivedStruct<T> derivedStruct) 
		=> new DerivedClass<string>()
		{
			Name = derivedStruct.Name
		};
}

public class DerivedClass<T> : Base
	where T : class
{
}

[TestFixture]
public class SwitchExpressionTest
{
	[Test]
	public void RunTest()
	{
		TypeCode type = Type.GetTypeCode(typeof(DateTime));

		Base result = type switch
		{
			TypeCode.Int32 => new DerivedStruct<int>(),
			TypeCode.DateTime => new DerivedStruct<DateTime>(),
			TypeCode.String => new DerivedClass<string>(),
			_ => throw new NotImplementedException()
		};

		Assert.That(result.GetType(), Is.EqualTo(typeof(DerivedStruct<DateTime>)));
	}
}
```

**Expected Behavior**:
New instance of `DerivedStruct<DateTime>` is casted to `Base` type and stored in `result` variable. 

**Actual Behavior**:
Instance of `DerivedStruct<DateTime>` is converted to `DerivedClass<string>` via implicit operator.

I suspect that my question is very close to this issue: https://github.com/dotnet/roslyn/issues/32094

If i understood this [Roslyn comment](https://github.com/dotnet/roslyn/blob/1d28ff9/src/Compilers/CSharp/Portable/Binder/SwitchBinder.cs#L437-L446
) correctly, such situation is possible for a list of specific governing types. Does generics also fall under this scenario? Or is this another case entirely?

Everything works fine if i:
1) remove the operator
2) add implicit operator in `DerivedClass<T>` to any DerivedStruct
3) explicitly cast to `Base` class inside switch (`TypeCode.String => (Base)new DerivedClass<string>()`). Though VS will give me warning `IDE0004 C# Cast is redundant.`

**Comment by gafter** [comment]
This switch expression has a common type among its arms. That common type is `DerivedClass<string>`. Since it has a common type, all of the expressions of the switch are converted to that common type as part of the evaluation of the switch expression. See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md#switch-expression

**Comment by KelDazan** [comment]
> if such a type exists and the expression in every arm of the switch expression can be implicitly converted to that type.

Actually this was quite unobvious to me, thank you, my mistake.
Another matter - why does VS give suggestion `IDE0066 C# Use 'switch' expression` if the result of statement differs from the result of expression:

```cs
Base result;
switch (Type.GetTypeCode(typeof(DateTime)))
{
    case TypeCode.Int32:
        result = new DerivedStruct<int>();
        break;
    case TypeCode.DateTime:
        result = new DerivedStruct<DateTime>();
        break;
    case TypeCode.String:
        result = new DerivedClass<string>();
        break;
    default:
        throw new NotImplementedException();
}
Assert.That(result.GetType(), Is.EqualTo(typeof(DerivedStruct<DateTime>)));

result = Type.GetTypeCode(typeof(DateTime)) switch
{
    TypeCode.Int32 => new DerivedStruct<int>(),
    TypeCode.DateTime => new DerivedStruct<DateTime>(),
    TypeCode.String => new DerivedClass<string>(),
    _ => throw new NotImplementedException()
};
Assert.That(result.GetType(), Is.EqualTo(typeof(DerivedStruct<DateTime>)));
```

**Comment by CyrusNajmabadi** [comment]
>why does VS give suggestion

Because of a bug. :)
