### ISSUE TITLE
"Go to Base" context menu doesn't work on a constrcutor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#44944]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1065111/go-to-base-context-menu-doesnt-work-on-a-constrcut.html)._

---
In C# if you have a derived class with a constructor that invokes a base constructor:

e.g.
````
class Foo
{
   Foo(string y) { ... }

Foo(int x) { ... }
}

class Bar : Foo
{
   Bar(int x) :  base(x) { ... }
}
````

Selecting the context menu option "Go to base" on the class name works, but selecting it on the declaration of the Bar constructor should take you to the base Foo constructor that is being invoked by the base() call.

---
#### Visual Studio Feedback System on 6/5/2020, 01:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
Design Meeting Notes:
- allow the user to navigate up the "chain" of constructors when running go-to-base
