### ISSUE TITLE
C# FAR not working

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/roslyn#44949]
**Version Used**: (16.7.0 Preview 3.0 [30208.23.master])

**Steps to Reproduce**:

1. Open a C# file
2. Try Find All References on a variable

**Expected Behavior**:
- FAR panel shows up with references

**Actual Behavior**:
- No action

This is on a local (non-liveshare) environment.

**Comment by jinujoseph** [comment]
Tracked [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1137490)

**Comment by allisonchou** [comment]
This should now be fixed as of 30210.20.master.
