### ISSUE TITLE
Make CSharp9 the default language value

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#44962]
Currently `CSharp9` is an alias for preview. 

We need to make it it's own distinct language version before releasing: 

- [x] Attach C# 9 features to `CSharp9` (see [MessageID.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Errors/MessageID.cs#L320-L343))
- [x] Make the default language `CSharp9`
- [x] ~~Remove the default for `.netcoreapp5.0`~~ (No longer applicable)
- [x] Update all tests the refer to preview and make them refer to 9
- [x] Update the `UpgradeProject` fixer tests in the IDE
- [x] Remove the pseudo `CSharp9` constant used in the IDE layer (see #43348 and https://github.com/chsienki/roslyn/commits/remove_pseudo_langver9)
- [ ] Verify end-to-end scenario 
- [x] Remove IDE dropown comment in source as it's no longer applicable

**Comment by jcouv** [comment]
Added an item: Verify end-to-end scenario including LangVer drop-down in IDE.
Thanks

**Comment by sharwell** [comment]
> Verify end-to-end scenario including LangVer drop-down in IDE

Didn't this get removed?

**Comment by jcouv** [comment]
@sharwell It used to be that we had to add every LangVer to project-system. I'm not sure how the drop-down works at this point. Would you know?
 
@chsienki If this was removed or work automatically somehow, then we'll remove the comment (on LangVer test/canary) to remind us to update project-system.

**Comment by sharwell** [comment]
The dropdown has been replaced by a link to a page explaining why there is no more dropdown.

**Comment by chsienki** [comment]
Yeah, it's no longer a selectable option in the IDE as it's set by the target framework. I'll update the list above to note we should remove the comment.

**Comment by jcouv** [comment]
@chsienki FYI, I'm preparing a PR for the compiler change.
