### ISSUE TITLE
EndToEndTests.DeeplyNestedGeneric failed due to StackOverflowException

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#44982]
The release/x86/net472 configuration failed during a test for #43844.
https://dev.azure.com/dnceng/public/_build/results?buildId=677561&view=results

**Comment by sharwell** [comment]
Failed here https://dev.azure.com/dnceng/public/_build/results?buildId=678944&view=results

**Comment by sharwell** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=681585&view=results

**Comment by sharwell** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=682937&view=results

**Comment by sharwell** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=682902&view=results

**Comment by jaredpar** [comment]
@RikkiGibson looks like the test is failing in CI now.
