### ISSUE TITLE
CS8618 should provide fixer for making fields nullable

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#44983]
**Version Used**: 
C# Tools   3.7.0-3.20304.1+7f79df833ab997455f3d894dd56c196596da1b0e

**Steps to Reproduce**:
```C#
#nullable enable
using System;

class Program
{
    private string _value;

    static void Main() => new Program();

    public Program()
    {
    }
}
```

**Expected Behavior**:
When the IDE pops the analyzer dialog for CS8618 and says "Consider declaring the field as nullable" and "Show potential fixes", one of those fixes should be to make the field nullable.

**Actual Behavior**:
No fixer is offered.
![image](https://user-images.githubusercontent.com/2642209/84170308-8a6caf80-aa47-11ea-9409-23d089b08f3f.png)
The only options are to Change signature and Suppress or Configure issues:
![image](https://user-images.githubusercontent.com/2642209/84170367-9c4e5280-aa47-11ea-9a3a-6de27ffb8278.png)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Should this be a bug with the current CodeFixProvider?

https://github.com/dotnet/roslyn/blob/03c34759fc1cbb1771967f27a7e25d79cece69af/src/Features/CSharp/Portable/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs
