### ISSUE TITLE
Expanding nodes in the Watch window becomes extremely slow after some use

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#450]
To reproduce:
1. In VS2015 CTP5, click File->New Project->C# Console Application
2. Hit F10 to start debugging
3. In the Watch window, enter "typeof(object).Assembly.GetTypes()" 
4. Go down each item ([0], [1]. [2]...) and collapse and decollapse each node. Observe that collapsing each node becomes slower and slower as you progress, becoming extremely slow (~1.5-2 seconds) by the time you reach the 20th item in the list.
5. Go into Tools->Options->Debugging and check "Use the legacy C# and VB expression evaluators".
6. Repeat steps 1-4 and observe that the problem no longer reproduces.

**Comment by amcasey** [comment]
Thanks for the report!  We recently discovered that we were having some trouble with the lifetimes of the objects backing those nodes and they were accumulating over time.  The fix should be available in the next public release.

**Comment by ManishJayaswal** [comment]
This was fixed by the debugger team recently.
