### ISSUE TITLE
Require init property for positional record parameter

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#45009]
@cston I understand that we only need to check the existence of the getter for purpose of synthesizing `Deconstruct`, but I wonder if we should more generally reject properties that are not `{get; init; }`.
It seems to me that having a `public int X { get; init; }` is part of the expectation/contract of  `record C(int X) { ... }` whether the property is synthesized or user-defined.

_Originally posted by @jcouv in https://github.com/dotnet/roslyn/pull/44806#discussion_r437748935_

**Comment by RikkiGibson** [comment]
Related question: should record synthesized Deconstruct allow 'ref' properties? Obviously if we go with "yes" on the original issue question then we will also disallow 'ref' properties.

**Comment by jcouv** [comment]
Related question: should we produce an error if a user-defined `Deconstruct` has the wrong return type? (currently an error is produced on whoever ends up deconstructing)

**Comment by AlekseyTs** [comment]
@RikkiGibson Is this issue still relevant, given the current design outlined at https://github.com/dotnet/csharplang/blob/master/proposals/records.md?

**Comment by RikkiGibson** [comment]
No, the design does not seem to include this requirement and I see no reason to introduce the requirement at this point.
