### ISSUE TITLE
Synthesized Deconstruct should report usages of Obsolete properties

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#45010]
Follow up to #44806

_Originally posted by @jcouv in https://github.com/dotnet/roslyn/pull/44806_

**Comment by jcouv** [comment]
We can close this as @AlekseyTs said that synthesized methods don't check for `Obsolete` in a recent PR.

**Comment by RikkiGibson** [comment]
@AlekseyTs did you mention that we do not generally report Obsolete warnings when synthesized methods make calls to Obsolete members? If so we should close this issue as wontfix.
