### ISSUE TITLE
Typo on "New Language Features in C# 6" wiki page

### ISSUE THREAD

**Issue by shanekenney** [dotnet/roslyn#4501]
https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#getter-only-auto-properties

Note the semicolon after the getter auto property for Name:

```
public string Name { get; };
```

From the second code example:

```
public class Customer
{
    public string Name { get; };
    public Customer(string first, string last)
    {
        Name = first + " " + last;
    }
}
```

**Comment by Pilchie** [comment]
Fixed - thanks :smile:
