### ISSUE TITLE
Declaration to suppress backward compatibility

### ISSUE THREAD

**Issue by dimohy** [dotnet/roslyn#45027]
Declaration to suppress backward compatibility

I have been coding C# since C#1.0.
The first C# was a language that was easier to learn compared to other languages.
After a long time, the C# specification adds advanced grammar and modern language grammar, and the newly added grammar coexists with the past.

Some grammars replace existing complex blocks of code. Currently, C# can be used for both.

What I'm suggesting is to force the new grammar added in C# through declarations that suppress backward compatibility, and the old grammar throws an error. It would be great if I could declare this declaration at the top of each CS file. It still maintains backward compatibility when connecting.

#using cs9

Computer languages ​​are very important for maintaining backward compatibility, but there are limitations to actively applying new designs. If you can remove these restrictions on a file-by-file basis, can't you move slowly in the right direction?

Various examples, but still a concept. Please comment if you have any thoughts.

**Comment by CyrusNajmabadi** [comment]
You can do this today just by adding your own analyzer and disallowing constructs you no longer want to use.  :)

**Comment by svick** [comment]
Out of curiosity, what features do you consider to be "old" that would produce an error in the "cs9" mode?

Anonymous methods (e.g. `Action a = delegate { };`) are pretty much the only grammar I can think of that could be treated this way. But they are harmless, it's quite unlikely that using them would introduce a bug, their main problem is that they're too verbose.

Another problematic historical feature that comes to mind is array covariance, but that's a much more subtle feature, with no grammar of its own and it also can't be fully disabled by static analysis.
