### ISSUE TITLE
Equals vs == comparison is somehow wrong for structs

### ISSUE THREAD

**Issue by msedi** [dotnet/roslyn#45030]
### Description

I have a readonly struct RangeDescriptor that holds a range from start to end. If I want the full range, default is handed over.

For that reason I did an override for Equals, == and != to compare against the struct, additionally I needed to compare against default. == and != simply forwards the comparison to Equals.

So if I now model the three different comparisons I have

```
          RangeDescriptorGood good = new RangeDescriptorGood();
          Console.WriteLine("Comparison with ==");
           Console.WriteLine($"Good == default: {good == default}");
            Console.WriteLine($"Good == null: {good == null}");
            Console.WriteLine();

            Console.WriteLine("Comparison with Equals");
            Console.WriteLine($"Good.Equals(default): {good.Equals(default)}");
            Console.WriteLine($"Good.Equals(null): {good.Equals(null)}");
```

As a result I can see

```
Comparison with ==
Good == default: True
Good == null: False

Comparison with Equals
Good.Equals(default): True
Good.Equals(null): True
```

Which is not what I expect. `Equals `returns correctly, whereas == which uses `Equals` internally has a different behavior.

I have provided an example to show the behavior: https://gist.github.com/msedi/04c1e26366e58ac7ceb9e01b18f70dde

### Configuration
.NET Core 3.1 and .NET 5, Windows 10 x64

### Regression?
Currently unknown, this is a new implementation of mine, before it was a class where I compared against null which worked.

**Comment by msedi** [comment]
@SingleAccretion: Sorry for the delay, I was out of office. Thanks for the tip. Although the problem is that I can debug the line of code where it enters the comparison. In my case inside debugging the line I can see a true, when I leave the method and inspect the result of == directly, I can see a false. 

So the question is if there is really something going on in the runtime?

Nevertheless, thanks for the links.

**Comment by SingleAccretion** [comment]
> I can debug the line of code where it enters the comparison

@msedi That is weird. I do not reach any of the breakpoints when I run the following program (.NET Core 3.1, VS 2019 16.6.1, Debug).
````C#
internal class Program
{
    private static void Main(string[] args)
    {
        var s = new S();
        Console.WriteLine(s == null);
    }

    public struct S
    {
        public int Value { get; }

        public override bool Equals(object obj) => obj is S s && Equals(s); //Breakpoint #1
        public bool Equals(S other) => Value == other.Value; //Breakpoint #2

        public static bool operator ==(S left, S right) => left.Equals(right);
        public static bool operator !=(S left, S right) => !(left == right);
    }
}
````
In fact, if I check the machine code, there is only one call present, the one to `Console.WriteLine`:
````ASM
  ; var s = new S();
xor         ecx,ecx  ; Here's our hardcoded false
mov         dword ptr [rbp+20h],ecx ; I think this is how the debugger sees it
  ; Console.WriteLine(s == null);
call        00007FFC33E70FC0
````

**Comment by msedi** [comment]
Interesting. Thanks. I will check again.
