### ISSUE TITLE
Support ISpanMappingService for GoTo Definition/Implementation and rename requests

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#45063]
Currently FAR and CodeLens use the ISpanMappingService to allow Razor to remap its background C# documents back to the original Razor document. See [here](https://github.com/dotnet/roslyn/blob/288ce56e40850be1c36a773b41db3107e5f53deb/src/VisualStudio/Core/Def/Implementation/FindReferences/Entries/AbstractDocumentSpanEntry.cs#L67) and [here](https://github.com/dotnet/roslyn/blob/c1e8715cf86ddcfb86f7daefb79a6c1b496de5a6/src/VisualStudio/Core/Def/Implementation/CodeLens/RemoteCodeLensReferencesService.cs#L144). 

We want Go to definition/implementation and Rename requests to also invoke this API. This will allow the LSP powered Razor editor to provide cross-file navigation in both local and online scenarios.

cc @dibarbet @jasonmalinowski @NTaylorMullen

**Comment by dibarbet** [comment]
accidentally closed.  re-opening for rename support

**Comment by dibarbet** [comment]
resolved by #47104
