### ISSUE TITLE
Synthesized record methods for GetHashCode() and Equals(object) should override methods from System.Object

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#45078]
From the records [spec](https://github.com/dotnet/csharplang/blob/master/proposals/records.md#equality-members):

> `GetHashCode()` and `Equals(object other)` are overrides of the virtual methods in `System.Object`. Any methods on intermediate base classes that would hide those methods are ignored when overriding.

Test that the synthesized overrides generated for a `record` ignore members that hide those virtual methods.

See https://github.com/dotnet/csharplang/pull/3552#discussion_r437835938.

cc @gafter

**Comment by gafter** [comment]
A particularly interesting example would be a base class (record) that declares

```csharp
public virtual new int GetHashCode() => 0;
```

We should ensure that OHI properly notices what implements what, including from metadata.

**Comment by nbalakin** [comment]
Do you accept community contribution for this issue?

**Comment by gafter** [comment]
@nbalakin I suspect the specification might change (to require an error) rather than the implementation. So we're probably not sure what will be implemented to address this yet.

**Comment by AlekseyTs** [comment]
The design has changed. Shadowing is not ignored, but causes an error.
