### ISSUE TITLE
Definite assignment not identified after dynamic call

### ISSUE THREAD

**Issue by rawling** [dotnet/roslyn#4507]
Simplified from [this](http://stackoverflow.com/q/31961411/215380) StackOverflow question.

Given the following code

    decimal a, b;
    var q = decimal.TryParse((dynamic)"10", out a) && decimal.TryParse("15", out b) && a <= b;

VS2015 fails to build with error CS0165: "Use of unassigned local variable 'b'".

If you remove the `dynamic` cast, the project builds.

This reportedly built in VS2013, but does not for me on a system with both 2013 and 2015 installed.

**Comment by rawling** [comment]
Subsequent issue [here](https://github.com/dotnet/roslyn/issues/4509) has been responded to.

**Comment by gafter** [comment]
Dup of #4509
