### ISSUE TITLE
Change Signature: Preview field omits `this` keyword on extension methods

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#45083]
**Version Used**: VS 16.7 P2

**Steps to Reproduce**:

```c#
public static class C
{
    public static void M(this int a) {}
}
```

Invoke 'Change signature' on the method.

**Expected Behavior**: The preview shows the complete signature.

**Actual Behavior**: The preview omits the `this` keyword, even though it is listed in the parameter table.

![image](https://user-images.githubusercontent.com/823398/84426068-e8a1ba00-ac22-11ea-8acb-c6298f622028.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and how minor this is.
