### ISSUE TITLE
Records spec missing scope changes

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#45087]
Although https://github.com/dotnet/csharplang/pull/3548 expresses informally the intent to make some scope changes to the language in support of records, the records specification at https://github.com/dotnet/csharplang/blob/master/proposals/records.md still contains no modification to the name lookup rule in https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#simple-names that would be needed to describe the intended language impact. 

See also #44687. Once the spec is written the compiler would need to be implemented (if there is any mismatch) and tested against the specification.

/cc @AlekseyTs @agocke

**Comment by AlekseyTs** [comment]
This issue is too general to be actionable.

**Comment by jcouv** [comment]
@AlekseyTs The ask is to update the records speclet with the changes from this PR: https://github.com/dotnet/roslyn/pull/44906

**Comment by jcouv** [comment]
From offline discussion, the speclet was already updated to include the information.
