### ISSUE TITLE
cntrl+Q search fails to find symbols in folder view

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#45084]
**Version Used**: 
latest master

**Steps to Reproduce**:

1. Open VS
2. Create a C# console app project and switch to folder view
3. Press Ctrl+Q to focus on search box
4. Try to search symbols (e.g. 'main', 'program')

**Expected Behavior**:
symbols found

**Actual Behavior**:
no symbols found

![SearchSymbolsInFolderView](https://user-images.githubusercontent.com/5749229/84429317-c7b67600-abdc-11ea-87dc-9b22a23c6a99.gif)

**Comment by dibarbet** [comment]
cc @gundermanc

**Comment by jinujoseph** [comment]
Need to be followup to make the API public and brought to design meeting

**Comment by dibarbet** [comment]
This happens because the anycode workspace ( https://devdiv.visualstudio.com/DevDiv/_git/AnyCode?path=%2Fsrc%2FMicrosoft.VisualStudio.Workspace.Extensions.Implementation.VS%2FIntellisense%2FRoslynWorkspaceShim.cs&_a=contents&version=GBmain ) isn't one we use to look for LSP solutions.

Recently we added the LSP workspace registration type - http://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/ILspWorkspaceRegistrationService.cs,24 which allows a workspace to register itself for LSP.

@jasonmalinowski @CyrusNajmabadi any concerns with making this public so that we can update anycode to register itself for LSP?

**Comment by 333fred** [comment]
One immediate question: why would this API be public and the test of the LSP APIs be internal? I don't know why this API would be useful without the rest.

**Comment by CyrusNajmabadi** [comment]
> @jasonmalinowski @CyrusNajmabadi any concerns with making this public so that we can update anycode to register itself for LSP?

I'd say we just doc it as for internal impl only and we reserve the right to change it at any time.

**Comment by CyrusNajmabadi** [comment]
Why is AnyCode using their own workspace at all?

**Comment by gundermanc** [comment]
>Why is AnyCode using their own workspace at all?

The fact this case behaves any different seems to imply fragility in the relationship between AnyCode and Solutions. Perhaps it's worth digging a bit into the delegation of responsibilities here for a broader fix. Esp. given AnyCode's prominent role in Codespaces and LiveShare.

**Comment by CyrusNajmabadi** [comment]
> The fact this case behaves any different seems to imply fragility in the relationship between AnyCode and Solutions. Perhaps it's worth digging a bit into the delegation of responsibilities here for a broader fix. Esp. given AnyCode's prominent role in Codespaces and LiveShare.

AFAICT, a core issue here is the use of URIs to try to identify files.  It's unclear to me how we can know which workspace a file belongs to when LSP makes requests to us in order to delegate properly.

**Comment by jasonmalinowski** [comment]
> I'd say we just doc it as for internal impl only and we reserve the right to change it at any time.

We could do this. (It's also what some VS APIs did which they can now never change because the world depends on it...)

> Why is AnyCode using their own workspace at all?

Partly history since it's implemented outside of Roslyn entirely. But at the same time these do act quite differently than regular VS projects. The APIs we have on VisualStudioWorkspace at least sometimes don't work -- there isn't IVsHierarchies for example, we don't have DTE so we can't apply fixes, etc. And if we wanted to have them using our workspace then we have to make a lot more APIs public than this one. Not that I don't want to do that work, but it opens a different can of worms.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski  That worries me given:

> Esp. given AnyCode's prominent role in Codespaces and LiveShare.

If it's prominent there... but we have all these limitations, isn't that an issue?

**Comment by gundermanc** [comment]
>isn't that an issue?

As it is, several components (namely LiveShare) are fairly omniscient. It might be worth digging a bit to be sure this particular component interaction is something we want to perpetuate long term. FWIW, this is exactly the sort of issue that prompted the in-progress LSP/LiveShare interactions refactor.

>It's unclear to me how we can know which workspace a file belongs to when LSP makes requests to us in order to delegate properly.

Seems like the root problem here is that there are two different workspaces and the expectation of which the server is talking about is controlled by a piece of client-side UX (the folder view button).

We could potentially extend LSP again to contain this info, but from LSP's perspective, we don't know or care about the concept of a workspace.

**Comment by jasonmalinowski** [comment]
> If it's prominent there... but we have all these limitations, isn't that an issue?

@CyrusNajmabadi I guess I should clarify: those "regular" things don't exist so we can't really implement them without AnyCode's help. But AnyCode absolutely can override the methods of a Workspace to handle applying that and opt-in. Does it now? I have no idea.

(This wouldn't be the first time a new experience we're building depends on a feature that didn't get much attention before...)

**Comment by dibarbet** [comment]
Note that anycode's role in codespaces is slightly reduced now as if there is only a single solution the codespace will automatically open in solution view.  

However this isn't a uniquely codespaces issue, the same problem occurs locally when a project is opened in folder view, so making changes in liveshare won't help us.  The anycode workspace should be server side similar to the VS workspace, it just happens to be in a repo that can't access this internal API.

> One immediate question: why would this API be public and the test of the LSP APIs be internal? I don't know why this API would be useful without the rest.

That is a good point and makes me lean towards the suggestion of doc'ing as for internal use only - this would only help anycode (or anyone else who creates a workspace inside VS and wants to provide LSP features on it).

**Comment by CyrusNajmabadi** [comment]
do we still care about anycode?

**Comment by CyrusNajmabadi** [comment]
Anycode is not an investment area anymore.
