### ISSUE TITLE
LINQ Analyzer

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#45092]
Direct customer feedback: 

> VS will never suggest such things. Having such hints improved a lot my knowledge about LINQ statements:

![image](https://user-images.githubusercontent.com/46729679/84216197-a1c68f80-aa7d-11ea-852b-025ba542382c.png)

_Originally posted by @mikadumont in https://github.com/dotnet/roslyn/issues/41392#issuecomment-641663361_

**Comment by alrz** [comment]
Also `!list.Any(p => p.Exists)` => `list.All(p => !p.Exists)`

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/50318
