### ISSUE TITLE
FAQ is useless (2/12/2015)

### ISSUE THREAD

**Issue by GitUID** [dotnet/roslyn#451]
[SDK Preview](http://go.microsoft.com/fwlink/?LinkId=394641) that is vital to [FAQ](https://github.com/dotnet/roslyn/wiki/FAQ) answers is no longer available, making the the majority of the answers useless at the moment.

**Comment by JoshVarty** [comment]
I started writing the markdown to inline the answers within the FAQ, but having the code for both C# and VB .Net made the page absolutely enormous. That being said, I strongly believe the code samples should accompany the questions they answer. Even when the SDK Preview was available, it was a huge pain to navigate back and forth.

I tried to figure out if you could create collapsible sections within GitHub markdown, but it doesn't appear that you can.

I'm thinking about hosting the FAQ independently on my [Learn Roslyn Now](https://joshvarty.wordpress.com/learn-roslyn-now/) series, but I'm not convinced that this will do much good for the project here.

**Comment by ilmax** [comment]
Some news on this?

**Comment by JoshVarty** [comment]
The referenced samples are available on GitHub.

C#: https://github.com/dotnet/roslyn/blob/b6484300dfafb43af0c27e542ec457a7583e1aa8/src/Samples/CSharp/APISampleUnitTests/FAQ.cs

VB: https://github.com/dotnet/roslyn/blob/da4dbf98e894a20fc4234eede11d7c78e559cea1/src/Samples/VisualBasic/APISampleUnitTests/FAQ.vb

However, the formatting has taken a hit as these have been copied from at least three prior homes. The answers are also a little dated and reference IWorkspace and Roslyn.Services.dll. One question "How do I compile some code into a collectible type or DynamicMethod" is missing completely.

I've rehosted the questions alongside the code at: https://joshvarty.wordpress.com/roslynfaq/csharp/

I'll continue to clean up the formatting this weekend and then begin correcting individual answers.

**Comment by davkean** [comment]
@AnthonyDGreen What's the plan around this

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #48](https://github.com/dotnet/roslyn-sdk/issues/48) via [**ZenHub**](https://www.zenhub.com/)
