### ISSUE TITLE
Suggested Improvements for Change Signature

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4510]
1. Add parameter
2. Change modifier
3. Include the return type (and move between out parameter & return type)

Improvements that would mostly benefit an ExtractMethod-->ChangeSignature experience:
4. Rename parameter (easier than renaming one at a time)
5. Combine/decompose parameters (using the context of the source method)

**Comment by allisonchou** [comment]
There has been an ask to consolidate Change Signature feature requests into one issue. Since this enhancement is being tracked by the overarching issue #33977, will close as a dupe.
