### ISSUE TITLE
Lightbulb Code Fix for Missing using not working properly since update to 16.6.2

### ISSUE THREAD

**Issue by 06needhamt** [dotnet/roslyn#45108]
**Version Used**: 
16.6.2 worked fine in 16.6.1

**Steps to Reproduce**:
1. Create A new C# class library using .NET 4.6.2
2. Add a reference to version 6.2.0 of the EntityFramework Package
3. Create a new Empty Class in the project

```csharp
    public class A
    {
        public A()
        {
        }
    }
```

4. Create another class with the code below.

```csharp
    public class AMap : EntityTypeConfiguration<A>
    {
        public AMap()
        {
        }
    }
```

**Expected Behavior**:
Light bulb shows up to add Reference to `System.Data.Entity.ModelConfiguration`

**Actual Behavior**:
No lightbulb or error squiggle shows up

EDIT: I can reproduce this with utilising a class from a different namespace anywhere without the EntityFramework. No lightbulb shows up.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/199346930-5225081f-bd91-45cd-9d57-9ca469e6f72b.png)
