### ISSUE TITLE
Completion does not filter generic type argument from constraint

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#45106]
**Version Used**: 16.7.0 Preview 3.0 [30208.133.master]

**Steps to Reproduce**:

1. Given the following definitions:

```csharp
    public interface ICommand { }
    public class CloseSolution : ICommand { }
    public class OpenSolution : ICommand { }
    public interface ICommandBus
    {
        Task ExecuteAsync<T>(T command) where T : ICommand;
    }
```

2. When completion is shown for `ExecuteAsync<T>`, it does not filter for the (only two above) types that satisfy the constraint:

![image](https://user-images.githubusercontent.com/169707/84504816-f98a1400-ac92-11ea-92c2-d4c6103c6e7f.png)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
