### ISSUE TITLE
Expose '$Main' via WellKnownMemberNames

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#45110]
Currently we hard-coded `$Main` as a symbol name:

https://github.com/dotnet/roslyn/blob/6db6c5e4d592290e215a9b5d290c8ca1f5beabb5/src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs#L699

We should define a constant in `WellKnownMemberNames` for this and reference it from the analyzer.

🔗 Originally requested in https://github.com/dotnet/roslyn/pull/45090#discussion_r439175119

**Comment by AlekseyTs** [comment]
The constant is added, but I wasn't able to change AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs to use it because it looks like src\CodeStyle\Core\Analyzers\Microsoft.CodeAnalysis.CodeStyle.csproj is not building against the latest version of the WellKnownMemberNames type.
