### ISSUE TITLE
Update to System.Collections.Immutable v1.1.37

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4511]

**Comment by tmat** [comment]
FYI @jaredpar

**Comment by tmeschter** [comment]
Don't forget to add binding redirects to csc.exe, vbc.exe, etc. as part of this work.

**Comment by tmat** [comment]
@jasonmalinowski

**Comment by amcasey** [comment]
@tannergooding Did you say that this was done?

**Comment by tannergooding** [comment]
Yes.

**Comment by amcasey** [comment]
@jmarolf, can you please verify?
