### ISSUE TITLE
Change Signature: nullable annotations are ignored when adding NRT parameters

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#45126]
**Version Used**: VS 16.7 P2

**Steps to Reproduce**:

1. Open the Change Signature refactoring in a project with NRT enabled.
2. Add a `string?` parameter.
3. Commit the change.

**Expected Behavior**:

```c#
void M(string? s) { … }
```

**Actual Behavior**:

The parameter is shown without annotations in the dialog's table, and this is reflected in the generated code:

```c#
void M(string s) { … }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
