### ISSUE TITLE
[Analyzer Suggestion] Remove repetetive type in VB

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45166]
Assume we have a class called `Student` and is instantiated like below:

```vb
Dim studentX As Student = New Student(......)
```

It can be simplified to:

```vb
Dim studentX As New Student(......)
```

For a longer class name, it gets much more cleaner with the second case.

The analyzer should be able to do the same with `Using` statement as well.

**Comment by CyrusNajmabadi** [comment]
I believe we would take a community PR on this (gated by a user configurable option).  The option could be enabled by default, with 'hint' severity.
