### ISSUE TITLE
change Roslyn SDK template to include signed version of nuget package

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#4516]
currently, we include unsigned version of nuget package in our Roslyn SDK package. we should change it to signed version.

**Comment by amcasey** [comment]
@jmarolf Is this still true?

**Comment by jmarolf** [comment]
I don't know what this means nuget packages can't be signed.  are their contents unsigned?

**Comment by amcasey** [comment]
@heejaechang is there still work to do here?

**Comment by heejaechang** [comment]
I opened this bug since I am asked to open. and at the time, I think somebody was saying nuget can be signed. if that is not true, then probably we need to close this.

**Comment by amcasey** [comment]
@agocke confirmed that nuget packages can't be signed, so it sounds like there was a miscommunication when the bug was filed (possibly by me).  So, what remains is to confirm that everything in the SDK is signed.  @jmarolf can you please confirm that that is the case and then close this bug?
