### ISSUE TITLE
IntelliSense not completing "InvokeRequired" on "Label"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45161]
**Version Used**: 

Visual Studio 2019 16.5.4

**Steps to Reproduce**:

1. Create a new VB WinForms application
2. Try to access InvokeRequired in any label:

     ![image](https://user-images.githubusercontent.com/31348972/84588481-08ee9600-ae28-11ea-8a4c-d89d52354803.png)

**Expected Behavior**:

IntelliSense shows InvokeRequired in the suggestions list.

**Actual Behavior**:

IntelliSense doesn't show it.

**Comment by CyrusNajmabadi** [comment]
It's marked as:

```c#
        [EditorBrowsable(EditorBrowsableState.Advanced)]
```

So i think it's always filtered from VB.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi , is there any settings that allows it to show?
