### ISSUE TITLE
an fast var idea 

### ISSUE THREAD

**Issue by rainryu** [dotnet/roslyn#45169]
**Version Used**: 
c#8.0
**Steps to Reproduce**:

1. if i want write like this 
     var configurationRoot = configurationBuilder.Build();
2. sometimes im not sure return type ;

**Expected Behavior**:

 i hope i can write like this
 var configurationBuilder.Build()  = configurationRoot ；

**Actual Behavior**:
i write a balbalbl name like xxx first 
   var xxx= configurationBuilder.Build();

then when is write .build, oh i get it and return to xxx,change it to right name  like configurationRoot .

**Comment by svick** [comment]
I like the way ReSharper handles this: it has [a `.var` postfix template](https://www.jetbrains.com/help/resharper/Postfix_Templates.html), which means you write:

```c#
configurationBuilder.Build().var
```

And it turns into:

```c#
var configurationRoot = configurationBuilder.Build();
```

(While also letting you easily change the type and name of the variable.)

**Comment by CyrusNajmabadi** [comment]
You can effectively do this today.  Just write out the expression statement you want:

![image](https://user-images.githubusercontent.com/4564579/84600420-f5462e00-ae2d-11ea-9779-a2c83b088d8c.png)

Then hit ctrl-dot to bring up the lightbulb, and choose "introduce local..."

![image](https://user-images.githubusercontent.com/4564579/84600431-0727d100-ae2e-11ea-85bf-99142b82fa40.png)

After you hit <kbd>enter</kbd>, you will be in a rename session, so you can name the variable whatever you want.

![image](https://user-images.githubusercontent.com/4564579/84600445-1c046480-ae2e-11ea-837f-719c47022605.png)

![image](https://user-images.githubusercontent.com/4564579/84600448-2161af00-ae2e-11ea-830d-aac33f7df544.png)

Cheers!

**Comment by HaloFour** [comment]
I do really like how IntelliJ gives you a quick dropdown of suggested variable names, based on both the members referenced in the expression and on the return type of the value:

![image](https://user-images.githubusercontent.com/10102290/84666624-5255e880-aeef-11ea-99c8-7d4d95caf94d.png)
