### ISSUE TITLE
[Analyzer Suggestion] Remove dollar sign if there's nothing to interpolate

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45172]
For example:

```cs
Console.WriteLine($"Hello, world");
```

should be simplified to:

```cs
Console.WriteLine("Hello, world");
```

**Comment by CyrusNajmabadi** [comment]
I don't this is necessarily a good idea.  People may just have a preferred string form they prefer to use, even if they don't use the features of that string.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi It could be disabled by default and turned on by developers who needs to remove the unnecessary dollar signs?

**Comment by CyrusNajmabadi** [comment]
My position boils down to effectively: too little value for this to be in-box.  i.e. i don't expect many to enable this, and i really don't actually get behind the mindset of going "i should use a `""` string instead of a `$""` one".  I think it would be fine to be in an analyzer package though :)

**Comment by Youssef1313** [comment]
> I think it would be fine to be in an analyzer package though :)

cc: @mavasani on this part.

**Comment by mavasani** [comment]
@Youssef1313 I believe this should be in your own analyzer package.

**Comment by Youssef1313** [comment]
Ok, I'm closing then.
