### ISSUE TITLE
Changing the startup form's name in a VB WinForms app does not update the "Startup form"

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4517]
(Copied from internal bugs 1208184 and 1205013)

1. Create a VB WinForms app.
2. Right click on "Form1" in Solution Explorer and rename it to "Anything"
3. Build the solution

**Expected**: It should build.
**Actual**: There is an error in Application.Designer.vb because OnCreateMainForm() still references "Form1", and the "Application" Property Page still has "Form1" set as the "Startup form"

This is a regression from Visual Studio 2013.

**Comment by Pilchie** [comment]
See also internal bug 1204979
