### ISSUE TITLE
Suggestion: Consider apprehension of StackOverflowException due to stackalloc in loop

### ISSUE THREAD

**Issue by GlassGrass** [dotnet/roslyn#45178]
Though this problem might have existed since long time ago, it gets more serious in current because stackalloc got familier.

This problem may be similar to #24210, but I think a compiler can handle this problem better.

Following code may throw StackOverflowException with conditional on value of `times`. This `stackalloc` looks to allocate buffer on each loop step.

```CSharp
using System;

class Program
{
    const int times = 1000000;

    static void Main(string[] args)
    {
        for(var i = 0; i < times; ++i)
            Foo(stackalloc []{i});
    }

    static void Foo(Span<int> span) {}
}
```

Like this, `stackalloc` in loop can cause SOE depending on loop times. To counter this matter, I suggest either of following solution.

1. just warn if `stackalloc` is used in loop

2. improve generated IL to avoid SOE
   In this way, for example, above code will be compiled into an IL equivalent of the following code.

   ```CSharp
   using System;
   using System.Runtime.CompilerServices;

   class Program
   {
       const int times = 1000000;
   
       static void Main(string[] args)
       {
           Span<int> span = stackalloc int[1];
           for(var i = 0; i < times; ++i)
           {
               Unsafe.InitBlockUnaligned(ref Unsafe.As<int, byte>(ref span[0]), default, (uint)(1 * Unsafe.SizeOf<int>()));
               span[0] = i;
               Foo(span);
           }
       }
   
       static void Foo(Span<int> span) {}
   }
   ```

   NOTE: Sorry, I don't know whether every case can be compiled to appropriate IL or not.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/runtime/issues/33782, https://github.com/dotnet/roslyn-analyzers/pull/3432, which introduced a Roslyn analyzer to flag this very pattern.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/3432 seems to fully address this concern.  Thanks!

**Comment by GlassGrass** [comment]
@GrabYourPitchforks @CyrusNajmabadi I've overlooked the issue, thank you!
