### ISSUE TITLE
EditorConfig highlighting

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45173]
The .editorconfig, when displayed in VS has no highlighting. I believe it would look nicer if it has highlighting, For example, green color for comments.

**Comment by CyrusNajmabadi** [comment]
@olegtk Are you guys tracking work here to improve the editing experience around .editorconfig files?

I'm somewhat considering writing something, but it would be roslyn specific, which seems a shame.

**Comment by olegtk** [comment]
Hmm, there should be some basic colorization support through TextMate (as .editorconfig is basically .ini file format). @Youssef1313, do you get uncolorized text when opening .editorconfig files?|
Unfortunately there are no plans to invest into improving .editorconfig editing experience at the moment. You can try Mads' extension though: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig

**Comment by Youssef1313** [comment]
I'm getting no highlighting at all (without the mentioned extension, I'll try it soon )

**Comment by jinujoseph** [comment]
cc @mikadumont for info

**Comment by Youssef1313** [comment]
It looks like it's fixed with the latest version of Visual Studio. I'm closing this.
