### ISSUE TITLE
Nullability covariance and ImmutableArray

### ISSUE THREAD

**Issue by manfred-brands** [dotnet/roslyn#45185]
**Version:**
.net core 3.1.300 (VS2019 16.6.2)

Can not pass an ImmutableArray<T> to a method accepting ImmutableArray<T?> but can pass that same array to a method accepting IReadOnlyList<T?>. Both operations to me are equivalent. There is no risk of the method called updating its argument.

```
public abstract void MethodAcceptingIReadOnlyList<T>(IReadOnlyList<T?> s)
    where T : class;

public abstract void MethodAcceptingImmutableArray<T>(ImmutableArray<T?> s)
    where T : class;

public void CallSequenceOperation()
{
    MethodAcceptingIReadOnlyList(ImmutableArray.Create(new object()));
    MethodAcceptingImmutableArray(ImmutableArray.Create(new object()));
}
```

**Expected Behavior**:
No warnings.

**Actual Behavior**:
Error CS8620 on the 2nd call.

**Comment by jaredpar** [comment]
This behavior is "By Design". The `IReadOnlyList<T>` example works because the type parameter is covariant hence the nullable conversion is allowed. The `ImmutableArray<T>` though does not have a covariant type parameter hence the conversion is properly disallowed
