### ISSUE TITLE
Interactive Prompt is invalid after async reset.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#4518]
InteractiveWindowTests.CallResetAsyncOnNonUIThread() is failing (both on xUnit 2.0-alpha and xUnit 2.1-beta4 -- it is only showing on xUnit 2.1-beta4 because the assert is being swallowed on xUnit 2.0-alpha).

This appears to be because the async reset from non ui thread creates two instances of the prompt.

**Comment by amcasey** [comment]
A prompt is created on ```LastLineNumber```, which his assumed to be a blank line.  If ```ResetAsync``` is called while the language buffer is blank, the last line will be the initial prompt (i.e. ```LastLineNumber``` will be 0 instead of `).

It's not clear why the assert is being swallowed.

**Comment by amcasey** [comment]
The issue appears to be that the ```InteractiveWindow``` assumes that ```IInteractiveEvaluator.ResetAsync``` will write to the window, which the test implementation does not.  I don't believe we can assume that every implementation will produce output.

**Comment by amcasey** [comment]
I discussed this with @tmat and we agreed that we should probably just remove the prompt and language buffer at the same time as we store uncommitted input.  Then the evaluator can add input or not, as it sees fit.

**Comment by amcasey** [comment]
@ManishJayaswal This is probably the issue you encountered this morning when you tried to add the additional history test.

**Comment by amcasey** [comment]
@tannergooding Can you please verify?
