### ISSUE TITLE
Add refactoring/information for assignment after pattern matching

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#45198]
When the `is` operator is used to match a type, then assigned using a cast or `as` operator, we should suggest that the code can be simplified to using a scope variable. 

```csharp

class MyClass : IMyInterface { }

class Example 
{
    void M()
    {
        var f = new MyClass();
        if (f is IMyInterface)
        { 
            var m = (IMyInterface)f; // or "f  as IMyInterface"
        }
    }
}
```

could be 

```csharp

class MyClass : IMyInterface { }

class Example 
{
    void M()
    {
        var f = new MyClass();
        if (f is IMyInterface m)
        { 
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
We do :)

![image](https://user-images.githubusercontent.com/4564579/84814897-01b1be80-afc7-11ea-9d53-24b54b343ee7.png)

**Comment by ryzngard** [comment]
That's good to know! Reopening to track adding the `as` operator as well.

**Comment by ryzngard** [comment]
![image](https://user-images.githubusercontent.com/475144/84820580-ba2f3080-afce-11ea-910a-7dac8f0b486d.png)

**Comment by CyrusNajmabadi** [comment]
Sure.  Marking as help wanted as i think we woudl take a community PR here.

**Comment by CyrusNajmabadi** [comment]
Note: `is+as` seems much less likely than the idiomatic cases we support today.  i.e. we support the idiomatic `is` case mentioned above and the idiomatic `as` case of:

![image](https://user-images.githubusercontent.com/4564579/84821258-b059fd00-afcf-11ea-8344-e67ff131db51.png)

Mixing is/as is def out of the norm.  But it can't hurt to help here if someone did write that :)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
