### ISSUE TITLE
How to create a UI that is displayed to show code fix?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#4520]
How can I created a UI that is used to display a current version of code and a possible fix then light bulb drop down is opened and a menu item representing a fix is focused?
I want to use the same UI from my light bulb.

I also want to display a fix preview dialog the same as displayed but code fix suggestion.

**Comment by dpoeschl** [comment]
Hi @xperiandri, can you clarify what you're asking for? Are you trying to repurpose our existing lightbulb experience in some other context? Are you trying to modify the existing lightbulb experience for your specific fix? Thanks!

**Comment by Pilchie** [comment]
We can't help here without more information, so closing

**Comment by xperiandri** [comment]
@Pilchie, I want that F# supports analyzers and refactorings like C# and VB do with Roslyn.

**Comment by Pilchie** [comment]
Hi @xperiandri, unfortunately, F# doesn't support Roslyn so it isn't possible to support the same analyzer and refactoring APIs for F#.  However, the *lightbulb* is implemented in the core VS Editor code, and can be used from any language, as can the ability to display error squiggles, populate the error-list, etc.

It would be a lot of work, but a similar experience could be built for F# using existing VS extensiblity.  See for example: ISuggestedActionsSourceProvider, ITaggerProvider, etc.

**Comment by xperiandri** [comment]
I understand.
Yes, Light Bulb is implemented but UI that displays a change made by applying action is not.
So I want to know where is that UI? I want to instantiate is and use in F# editor.

**Comment by Pilchie** [comment]
We mostly host an editor window with the editor diff code running in it.  You can see that code in [`PreviewFactoryService.CreateChangedDocumentPreviewViewAsync`](http://source.roslyn.io/Microsoft.CodeAnalysis.EditorFeatures/R/3611fdb867ffb923.html).  Take a look a few callers up to see where we create containing UIElement.

**Comment by xperiandri** [comment]
Thanks, I will have a look.
