### ISSUE TITLE
Name lookup for top level (local) functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#45208]
The specification for top-level statements https://github.com/dotnet/csharplang/blob/master/proposals/top-level-statements.md does not update the name lookup rules as needed to place local functions in scope.

**Comment by AlekseyTs** [comment]
There is a section https://github.com/dotnet/csharplang/blob/master/proposals/top-level-statements.md#scope-of-top-level-local-variables-and-local-functions that describes the change to lookup rules.

**Comment by gafter** [comment]
That section uses phrases such as 'evaluate the name within the generated entry point method' (but there are no name lookup rules applicable to a synthesized method) and '"regular" evaluation within the global namespace' (but without identifying what part of the specification it is referring to as "regular").

To be precise, the specification should propose a modified set of name lookup rules, but either spelling them out or being precise about the proposed modifications to the existing rules.
