### ISSUE TITLE
do not rename overrides when user selects a suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45218]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1073657/do-not-rename-overrides-when-user-selects-a-sugges.html)._

---
In the editor, do not rename overrides when a user selects a code suggestion.

For instance, if there is an await in a non-async overridden method named ExampleMethod(), VS will suggest making the method async.  It also renames the method ExampleMethodAsync() which then breaks the override.  The suggestion would be handy if it didn't force you to fix names after it's applied.

---
#### Visual Studio Feedback System on 6/11/2020, 02:04 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is what we already do.  We actually 'rename' the method, which fixes up all callsites, as well as renames the symbol up/down the inheritance hierarchy:

![image](https://user-images.githubusercontent.com/4564579/84815234-97e5e480-afc7-11ea-9a20-fc4ff649db3c.png)
