### ISSUE TITLE
Add  method comments for interface implementation quick fix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45215]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1075615/add-method-comments-for-interface-implementation-q.html)._

---
When I do a quick fix to implement an interface on a class, it would be great if methods also have the <inheritdoc /> comment on them since that's the first thing I have to do anyway to fix missing comments.

---
#### Visual Studio Feedback System on 6/15/2020, 02:51 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Clsing out as interface implementations automatically pick up the doc comments of the interface member they're implementing:

![image](https://user-images.githubusercontent.com/4564579/84731521-f7071300-af4d-11ea-9449-3bc60038386a.png)
