### ISSUE TITLE
IDE API Changes from Review

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#45213]
Notes added in https://github.com/dotnet/roslyn/pull/45211

### `SolutionInfo.Create`

Add `EditorBrowsable(Never)` to the backcompat overload.

### `SymbolFinder.Find(Derived(Classes|Interfaces)|Interfaces)Async`

We should reconsider adding multiple overloads, and instead remove the default parameters from the existing overload and introduce a new overload with `transitive` set to `true` to match current behavior.
This is our standard modus operandi for these scenarios.

### `Renamer.RenameDocumentAsync`

Make this and the related structs internal unless we have a partner team ready to consume the API in 16.7. We can make the API public again when someone is ready to consume and validate the API shape.

**Comment by jasonmalinowski** [comment]
@ryzngard One question @CyrusNajmabadi and I had -- for the document renaming APIs, are we consuming those in 16.7 somewhere or did that work slip to 16.8? If it did slip, does it make sense to keep the APIs internal _just in 16.7_ before we lock them accidentally?

**Comment by CyrusNajmabadi** [comment]
@ryzngard I've taken are of the first two issues.  CAn you handle the rename one?

**Comment by ryzngard** [comment]
`Renamer.RenameDocumentAsync` is used by Project-System already https://github.com/dotnet/project-system/pull/6179#event-3372025800

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Good to close then?
