### ISSUE TITLE
Add option to auto-generate XML documentation blocks for methods etc. (like GhostDoc)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45216]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1068004/add-option-to-auto-generate-xml-documentation-for.html)._

---
<p>The suggested way to document your code is XML as described on several Microsoft [1][2]</p><p>Unfortunately there is no integrated way to automatically create this for me. There are extensions for it, like GhostDoc[3][4] (also with a free version) which can create that for you .<br>
It would be better if this feature is integrated in Visual Studio since documentation is very important.</p><p>GhostDoc example:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/140197-0.png"> Image:140197-0.png</a></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/140198-1.png"> Image:140198-1.png</a></p><p>[1] <a href="https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features">https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features</a><br>
[2] <a href="https://docs.microsoft.com/en-us/dotnet/csharp/codedoc">https://docs.microsoft.com/en-us/dotnet/csharp/codedoc</a><br>
[3] <a href="https://submain.com/GhostDoc/">https://submain.com/GhostDoc/</a><br>
[4] <a href="https://www.youtube.com/watch?v=4x4Omm1cL7A">Demo GhostDoc</a></p>

---
#### Visual Studio Feedback System on 6/8/2020, 03:04 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
The supported way to do this is to just hit `///` before a method, which will spit out the following for you:

![image](https://user-images.githubusercontent.com/4564579/84815328-b77d0d00-afc7-11ea-9488-585d146bea37.png)

You can then fill this in as you desire.

**Comment by CyrusNajmabadi** [comment]
Note that several things that ghostdoc does are not behaviors i think are appropraite.  For example, generating trivial documentation that effectively mirrors exactly the name of a function is the *opposite* of what i think should be in docs.  Docs should explain what is non-obvious or not-clear from the actual names of things. 

Similarly, taking the docs from an inherited member and repeating it on the new member is not a good thing.  That's jsut a way for docs to diverge and get out of date.  VS supports and understands `<inheritdoc ...` (and even assumes its there by default for quickinfo scenarios) which is a much more sensible way to approach that use case.

Finally, given the presence of ghostdoc, i woudl say that the space is well covered by existing tools.  If their behavior is what you prefer, then i would recommend just sticking with that :)
