### ISSUE TITLE
`BaseTypeSyntax` for with expressions

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#45212]
As per design review, we will extend `BaseTypeSyntax` with a new concrete node kind for base argument lists, instead of adding an optional list to `SimpleBaseTypeSyntax`. Notes are in https://github.com/dotnet/roslyn/pull/45211.

/cc @jcouv @AlekseyTs @gafter

**Comment by AlekseyTs** [comment]
@333fred Is this a dupe of https://github.com/dotnet/roslyn/issues/44795? Also, how is this related to with expressions?

**Comment by 333fred** [comment]
Ah, I didn't realize we already had a bug open for this.
