### ISSUE TITLE
documentation base class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1069360/documentation-base-class.html)._

---
Hovering functions in derived classes should show documentation of base class when no other documentation is found. Similair to {@inheritDoc}

---
#### Visual Studio Feedback System on 6/8/2020, 11:44 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This was already implemented in #36028 and released in Visual Studio 2019 Update 16.4.

**Comment by sharwell** [comment]
📝 See https://github.com/dotnet/roslyn/issues/7862#issuecomment-570670412 for an example screenshot
