### ISSUE TITLE
What are the minimal needed projects?

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45225]
I find it hard to work with the fully loaded Roslyn.sln, it's too big and Visual Studio becomes very laggy.

Are there any instructions for external contributors for what are the minimal projects need to be loaded for different working areas?

I'm currently working on a PR for an analyzer, I loaded the following:

- EditorFeatures
- Features
- Workspaces

It's working good when writing code, but when I try to run unit tests it fail during the build with the following errors:

![image](https://user-images.githubusercontent.com/31348972/84769264-d6829b80-afd5-11ea-955b-63b57e12c526.png)

And many warnings:

![image](https://user-images.githubusercontent.com/31348972/84769293-e26e5d80-afd5-11ea-826d-713bad1b3376.png)

It'd be helpful for me and other external contributors if information about this is documented somewhere.

I've done  `dotnet restore Roslyn.sln`

```bash
$ dotnet restore Roslyn.sln
  Determining projects to restore...
  All projects are up-to-date for restore.
```

**Comment by CyrusNajmabadi** [comment]
> Are there any instructions for external contributors for what are the minimal projects need to be loaded for different working areas?

No, there is not.  Because it is entirely "feature" dependent.  Currently, do make IDE level cahnges, the entire roslyn.sln system is the narrowest set of projects needed.  Sorry :-/

**Comment by Youssef1313** [comment]
> do make IDE level cahnges

I couldn't get what "IDE level changes" mean or how to make them?

**Comment by CyrusNajmabadi** [comment]
> I couldn't get what "IDE level changes" mean

Effectively: Everything at the workspace layer and higher.  i.e. our workspace features, our language features, our editor features, etc. etc.  

It sits 'above' all the compilation layers, which concern themselves primarily with the compiler or compiler APIs.

**Comment by CyrusNajmabadi** [comment]
Note: i'd recommend general questions go to gitter.im/dotnet/roslyn or discord.gg/csharp (#roslyn channel).  Thanks!
