### ISSUE TITLE
[Analyzer Suggestion] Redundant equality with true

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#45226]
An expression like:

```
bool b = SOME_EXPRESSION == true;
```

Could be simplified to just:

```
bool b = SOME_EXPRESSION
```

Same goes with if statements for sure.

**Comment by CyrusNajmabadi** [comment]
We woudl likely take a contribution here to find and fix these.  It likely can be on by default.

**Comment by aristid-lavri** [comment]
Hi @CyrusNajmabadi can i have more information and starting point to jump in this issue

**Comment by CyrusNajmabadi** [comment]
@aristid-lavri I would recommend coming to discord.gg/csharp (#roslyn) or gitter.im/dotnet/roslyn to get help from the community and team on building analyzers/fixers.  Thanks!

**Comment by louis-z** [comment]
Hey @Youssef1313,

Might I suggest you use [Meziantou.Analyzer](https://github.com/meziantou/Meziantou.Analyzer), as it already offers that rule.
