### ISSUE TITLE
VS 2019 VB.Net Intellisense Missing Advanced Tab and Advanced Entries

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45238]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/608131/vs-2019-vbnet-intellisense-missing-advanced-tab-an.html)._

---
When I want to select an advanced property such as HasItemsEnclosedInQuotes for the TextFieldParser it is not listed.  No advanced tab appears below the list.  Selecting Display advanced properties in Tools-Options doesn't make any difference.

---
#### Visual Studio Feedback System on 6/17/2019, 03:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jinu Joseph [MSFT] on 6/17/2019, 10:23 AM: 

<p>Thanks for the feedback. Would you be able to provide a snippet or image of where exactly you are looking for this tab pls? This will help with our investigation </p>

#### Blair Wang [MSFT] on 7/22/2019, 07:41 AM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Visual Studio Feedback System on 7/30/2019, 01:59 AM: 

Our team is unable to investigate this issue further without the requested information. Please update to the latest version of the product and if the problem still occurs, reply with the requested information. Thank you for sharing feedback on Developer Community.

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
This issue is a request to bring back the "Advanced" tab for intellisense

**Comment by CyrusNajmabadi** [comment]
Yeah, i'm not sure why this is not customizable in VB.  Seems odd, esp as we have all the codepaths setup to support this.  I think it's jsut a matter of the UI and hooking things up.  Marking as help-wanted as i think we'd take a PR for this.
