### ISSUE TITLE
VB Expression tree test fails to compile on Roslyn

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4524]
See http://stackoverflow.com/questions/31835986

This user has a program that uses expression trees. It compiles and works on previous versions, but Roslyn rejects it, complaining

```none
Error BC36534 Expression cannot be converted into an expression tree.
```

**Comment by joelccdev** [comment]
Here is a simple set of classes that reproduce the problem. You will also need Moq and Nunit for the test classes.
    
Interface in main application:

    Public Interface IAddress
        Property City As String
    End Interface

Address class in main application: 

    Public Class Address
        Implements IAddress

        Public Property City As String Implements IAddress.City
    End Class

Customer class in main application:

    Public Class Customer
        Public Property Address As IAddress

        Public Sub DoWork(newValue As String)
            Address.City = newValue
        End Sub
    End Class

And, finally, the test class:

    Imports Moq
    Imports NUnit.Framework
    Imports MainApp

    <TestFixture>
    Public Class CustomerTest
        Private _subject As Customer

        Private _address As Mock(Of IAddress)

        <SetUp>
        Public Sub Setup()
            _subject = New Customer()

            _address = New Mock(Of IAddress)()
            _subject.Address = _address.Object
        End Sub

        <TearDown>
        Public Sub TearDown()
            _subject = Nothing
        End Sub

        <Test>
        Public Sub DoWork_CallWithValue_SetsValue()
            Dim value As String = "Detroit"
            _subject.DoWork(value)

            _address.Verify(Sub(x) x.City = It.Is(Of String)(Function(s) s = value), Times.Once)
        End Sub

        <Test>
        Public Sub DoWork_CallWithNoValue()
            Dim value As String = String.Empty
            _subject.DoWork(value)

            _address.Verify(Sub(x) x.City = It.Is(Of String)(Function(s) String.IsNullOrEmpty(s)), Times.Once)
        End Sub
    End Class

As specified in the first answer to the above question, this may be an intended tightening of the compiler standards to avoid a non-zero failure rate for this unclear code.

**Comment by joelccdev** [comment]
Update: I was able to get these tests working by using `VerifySet` instead of `Verify`. To save you 2 minutes of digging into Moq, the difference between the two is below.

	public void VerifySet(Action<T> setterExpression)
	{
		Mock.VerifySet<T>(this, setterExpression, Times.AtLeastOnce(), null);
	}

	public void Verify(Expression<Action<T>> expression)
	{
		Mock.Verify(this, expression, Times.AtLeastOnce(), null);
	} 

So it comes down to an `Expression<Action<T>>` vs. `Action<T>`.
