### ISSUE TITLE
"Cannot implicitly convert type 'TArg' to 'int'" when TArg must be always int

### ISSUE THREAD

**Issue by IllidanS4** [dotnet/roslyn#45260]
**Version Used**: 16.4.2

**Steps to Reproduce**:

```cs
interface I<T>
{
    T M<TArg>(TArg arg) where TArg : T;
}

class C : I<int>
{
    int I<int>.M<TArg>(TArg arg)
    {
        return arg;
        return (int)arg;
    }
}
```

**Expected Behavior**:
The code should compile without errors. `I<int>.M<TArg>` can only be instantiated with `int` and so both conversions must always succeed (they should be no-op). This code works when `string` is used instead of `int`.

**Actual Behavior**:
First `return`: CS0029	Cannot implicitly convert type 'TArg' to 'int'
Second `return`: CS0030	Cannot convert type 'TArg' to 'int'

**Comment by CyrusNajmabadi** [comment]
This is correct as per the language rules.  Indeed, there's no verifiable cast (as far as i'm aware) at hte runtime level that would allow this.  The way to deal with this is to write:

`return (int)(object)arg;` 

Note that the runtime will not actually box here.  It will properly entirely elide this.

If you wuld like the language to say that the above should be legal, this would need to be moved to dotnet/csharplang.  Thanks!
