### ISSUE TITLE
"ExtractMethodCodeRefactoringProvider encountered an error and has been disabled." Indexing Bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1080682/extractmethodcoderefactoringprovider-encountered-a-28.html)._

---
Basically, I was doing a search and replace with regex expressions, and this bug popped up:

>System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
>Parameter name: end
>   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
>   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetAdjustedSpan(SourceText text,TextSpan textSpan)
>   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetInitialSelectionInfo(SyntaxNode root,SourceText text)
>   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionValidator.GetValidSelectionAsync(<Unknown Parameters>)
>   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
>   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ExtractMethodAsync(<Unknown Parameters>)
>   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionsAsync(<Unknown Parameters>)
>   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
>   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
>   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Visual Studio Feedback System on 6/17/2020, 00:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SylwesterZarebski** [comment]
I've just got the same error. It gives errors when moved (cut & paste) code selection few lines up.

**Comment by akhera99** [comment]
Could not repro, closing.
