### ISSUE TITLE
Positional record constructor invocation highlights the entire declaration

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#45275]
Screenshot:

![image](https://user-images.githubusercontent.com/201340/84968059-73266580-b0ca-11ea-85f2-5f30adb147d3.png)

The highlighting of "string s" isn't right. It makes sense that's what is coming out of the symbol model (and I wouldn't change that), but this is broken for the reference highlighting feature. The challenge of highlighting like this is if you navigate your caret into the declaration point, we'll continue to persist the entire highlight which is strange for editing.

**Comment by CyrusNajmabadi** [comment]
Looks good here:

![image](https://user-images.githubusercontent.com/4564579/222306673-cd35cd32-fa96-4f83-a8e0-3de713e4fbe5.png)
