### ISSUE TITLE
Assertion failure (in debug builds) when compiling async delegates

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#4527]
using System;
    using System.Threading.Tasks;

    namespace RoslynAsyncDelegate
    {
        class Program
        {
            static EventHandler MyEvent;

            static void Main(string[] args)
            {
               MyEvent += async delegate { await Task.Delay(0); };
            }
        }
    }

`name` is `""` at https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs#L27

**Comment by jaredpar** [comment]
Thanks for taking the time to report this!

**Comment by AlekseyTs** [comment]
@gafter Please verify.
