### ISSUE TITLE
Add option to "Implement interface" code fix to add "async" modifier when implementing methods that return Task or Task<T>

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#45287]
The suggestion in #27181 was to **change** the current behaviour of "Implement interface" to add the `async` modifier when the interface method(s) in question return `Task` or `Task<T>`. This was rejected because "as intended", which I strongly disagree with because honestly, how often are you writing methods that return `Task` that aren't going to be using `await`?

Regardless of that, my suggestion to satisfy all parties is to simply add a middle ground via an additional context menu item. The current code fix provides:

> Implement interface
> Implement all members explicitly

I'm suggesting to add a new menu item:

> Implement interface
> **Implement interface as async**
> Implement all members explicitly

that does exactly the same thing as "Implement interface", but simply adds the `async` modifier for implemented methods that return `Task`.

**Comment by IanKemp** [comment]
Alternatively/additionally, this could be a global IDE option.

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by jmarolf** [comment]
Design Meeting Notes
- Add async keyword automatically when the user types "await" and tie it to the completion of unimported types feature

**Comment by sharwell** [comment]
I filed the completion improvements as #45368, which should remove much of the pain points caused by the current behavior. For the request here, we've decided to not add more items to an already-large refactoring menu, but keep in mind the `CodeRefactoringProvider` type is part of the public API so it would be possible to implement this functionality as a separate feature. 😄

**Comment by IanKemp** [comment]
@sharwell Does this mean you are reversing [the decision made in #27181](https://github.com/dotnet/roslyn/issues/27181#issuecomment-424151190)? If so, may I ask for the rationale behind the change in consensus? (Not trying to waste your time, genuinely trying to understand what is different then vs now - is it simply a matter of Task-with-async being the predominant use-case now, when it wasn't ~2 years ago?)

**Comment by jmarolf** [comment]
>Does this mean you are reversing the decision made in #27181?

We almost ended in the same place (there is already a codefix to add the `async` keyword) for the same reasons (add imports is already a very busy place and any additions here need to demonstrate a lot of value).

@sharwell had the insight that now that we add using statements for unimported types through intellisense we could also add the `async` keyword when `await` is completed in intellisense.  This enables the experience to be better (using `await` in Task returning methods does not require any extra steps) without the negatives of over-crowding the implement interface options.
