### ISSUE TITLE
Compiler warning about immutable perf cost inside loops (ex: strings manipulations)

### ISSUE THREAD

**Issue by SBillault2018** [dotnet/roslyn#45282]
**Version Used**: 
- Microsoft Visual Studio Community 2019 Version 16.6.2
- Microsoft .Net Framework Version 4.8.03752

**Steps to Reproduce**:
Create a loop where, for exemple, you call += ' c' or += "str" on an immutable System.String.

**Expected Behavior**:
The compiler hit me on the head with a big stick and warn me about the potential perf cost, and suggest the use of a StringBuilder.

**Actual Behavior**:
The compiler dont say s...it so 80% of us always forget about the perf cost. It would be cool to have a warning or at least aliases like immutableString and mutableString for the cognitive side of things.

**Comment by CyrusNajmabadi** [comment]
Closing out as out of scope or this repo.  You can do this sort of analysis with an analyzer.  You can also consider checking if other analyzer repositories might be interested in this (for example dotnet/roslyn-analyzers).  Thanks!

**Comment by SBillault2018** [comment]
Will do Sir, but I was hoping not to have to use an analyzer for this... :(

**Comment by CyrusNajmabadi** [comment]
It doesn't have to be you :)   but it would have to be somebody.
