### ISSUE TITLE
GoToImplementation Doesn't Work On Interface Instance When Implemented Method Uses Async

### ISSUE THREAD

**Issue by JoshuaKlaser** [dotnet/roslyn#45290]
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.4.5

**Steps to Reproduce**:

1. Create an interface (**eg. IInterfaceExample**) and give it a method that returns a Task (**eg. Task MethodThatIsAsync();**)
2. Create a class that implements the the interface (**eg. ClassExample : IInterfaceExample**). Make sure the interface method implementation uses the `async` keyword (eg. **public async Task MethodThatIsAsync()**).
3. In another class/function, declare an instance of your interface and call the method defined (**eg. IInterfaceExample interfaceInstance = new ClassExample(); await interfaceInstance.MethodThatIsAsync();**)
4. Click/have the cursor on the interface method on your interface instance and run 'Go To Implementation' (Ctrl + F12)

**Expected Behavior**:
The class that inherited the interface should open up and the cursor should now be on the implemented interface method

**Actual Behavior**:
A window appears saying "The symbol has no implementations."

**Comment by CyrusNajmabadi** [comment]
FYI, it's easier to just ` ```c# ` code blocks to give the source examples you mean :)

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me at all.  Goto-impl from either the declaration or use-site takes me to the one impl.

![notimpl](https://user-images.githubusercontent.com/4564579/85044470-86751780-b142-11ea-805d-b527eeeebede.gif)

**Comment by JoshuaKlaser** [comment]
@CyrusNajmabadi. I have tried to repro it again based on your testing and have managed to figure out the missing component of my Steps To Reproduce.

Please have the Interface and the Class that implements interface in a Class Library and the interface instance where we will perform the Go To Implementation in a Console Application.

My settings of the projects are:
Class Library with IInterfaceExample and ClassExample: .NET Standard 2.1

Console App with the interfaceInstance: .NET Core 3.0

**Comment by JoshuaKlaser** [comment]
I have recorded a gif to help show the repro on my side:

![VS_GoToImplementation_Proof](https://user-images.githubusercontent.com/7035048/85077345-665a5c80-b205-11ea-824c-842fb8431027.gif)

**Comment by JoshuaKlaser** [comment]
Made the new issue in case Closed issues are no longer checked.
