### ISSUE TITLE
Implement Interfaces Better

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#45293]
**Version Used**: 
VS2019.06
**Steps to Reproduce**:

1. Create an interface that has properties
2. Create a class that implements the interface
3. Use the "Implement Interface" macro in VS.

**Expected Behavior**:
Properties get implemented like this:
````
public string User_Name_First { get; set; }
````

**Actual Behavior**:
Properties get implemented like this:
````
public string User_Name_First {
            get {
                throw new NotImplementedException();
            }

            set {
                throw new NotImplementedException();
            }
        }
````
And the first thing I have to do is go convert them to public string User_Name_First { get; set; }

**Comment by CyrusNajmabadi** [comment]
This is already supported today:

![image](https://user-images.githubusercontent.com/4564579/85039155-4ad74f00-b13c-11ea-8493-c52e962d8adc.png)

Thanks!
