### ISSUE TITLE
Should not permit default literals in relational patterns

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#45292]
**Version Used**: master

**Steps to Reproduce**:

```cs
    public void M(byte i) {
        _ = i is > default; // compiles
        _ = i is default; // error
    } 
```

**Expected Behavior**:

`A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern '_'`

**Actual Behavior**: No error

**Comment by jaredpar** [comment]
@gafter can u take a look at this?
