### ISSUE TITLE
??= is not colorized as operator

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#45319]
**Version Used**: 
16.6.2

**Steps to Reproduce**:

1.  New C# project

![image](https://user-images.githubusercontent.com/159110/85111786-68450f80-b247-11ea-90aa-041a26a6a203.png)

**Expected Behavior**:

`??=` should be the same color as `=` above.

**Comment by CyrusNajmabadi** [comment]
Does thsi repro with other compound operators?

**Comment by diryboy** [comment]
Looks only `??=` has problem.

![image](https://user-images.githubusercontent.com/159110/85380238-47dec300-b56f-11ea-9eba-b51f8b253dd6.png)
