### ISSUE TITLE
Create efficient equality members for structs

### ISSUE THREAD

**Issue by fschmied** [dotnet/roslyn#4532]
In ``ValueType.Equals`` and ``ValueType.GetHashCode``, the CLR uses Reflection to calculate equality for non-blittable types. This works, but is very inefficient.

I suggest that the C# compiler detect scenarios where this Reflection-based implementation would kick in and that it auto-generate more efficient, semantically equivalent versions of ``Equals`` and ``GetHashCode``.

**Comment by svick** [comment]
I agree that this is something that should be fixed, but I wonder whether the compiler is the right place to do it. Wouldn't it be better if this was fixed in the CLR?

**Comment by fschmied** [comment]
@svick Yes, e.g., the JIT compiler could auto-generate these members just as well. However, I reported it here because I think it's easier (lower threshold) to build this into Roslyn than into the JIT.

Also, there is some overlap with what the compiler already does for anonymous types, so there might be semantics and functionality to be reused. (See also #105 for a feature request to expose this for classes as well.)

**Comment by GSPP** [comment]
Here's the proposal for fixing this in the CLR: https://github.com/dotnet/coreclr/issues/1341
