### ISSUE TITLE
Nullability state of non-local variables should be reset on each yield in async methods

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#45326]
**Version Used**: 
VS 2019 16.7 Int Preview

**Steps to Reproduce**:

1. Create an async method that references a nullable class field.
2. Perform a null check of the nullable class field prior to the first 'await'.
3. Attempt to dereference the nullable class field or pass it as a non-nullable method parameter.

**Expected Behavior**:
As this method is asynchronous and there is heighted risk of race conditions due to interleaved execution of other calls on the same thread (in this case, the UI thread), I'd expect for nullability for class fields and properties to reset each time the method yields so as to reduce the possibility that another method call interleaved with the current one can set the checked variable to null, leading to a null reference exception.

Understandably, the nullability annotations can't catch everything.. and indeed can't guard against the similar case of racing threads accessing the same underlying class field, but as opposed to that scenario, the async issue is present, even in single threaded contexts.

**Actual Behavior**:
No warning is generated because we checked field to see if if was null prior to the first yield in the same method.

![image](https://user-images.githubusercontent.com/5387680/85169711-21442380-b221-11ea-92ac-c9d218ea3ee3.png)

**Comment by Neme12** [comment]
> the async issue is present, even in single threaded contexts

But so is the issue that a can property can return a different value every time, but the compiler assumes it doesn't and usually prefers leniency to not overwhelm the user with warnings on correct code.

**Comment by jaredpar** [comment]
This is "By Design". Within a method body we don’t silently reset the null state of fields. It requires explicitl user code to do that. This is true even in the case of interators, async methods, etc ...
