### ISSUE TITLE
Production of error squiggles in left diff pane regressed in VS 16.7 Preview

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#45329]
_ported from IDE bug:_ https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1143498

**Version Used**: 
16.7 Int Preview

**Steps to reproduce:**
1. Create a C# console app(.NET Framework)
2. Make some error in Program.cs, save.
3. Click "Add to source control", select Git.
4. Change some code in Program.cs, save. 
4. Open Team Explorer -> changes, Right click the changed file -> Compare with Unmodified… to open file with diff mode , make sure in side-by-side mode.
5.Check if the "Scroll Bar" on the left pan have error message points (red dots).

**Expect Result:**
Should show error marker in Diff window left pane on "Scroll Bar" 
Image

![image](https://user-images.githubusercontent.com/5387680/85185501-0be2ef80-b249-11ea-8dc2-8ffaaabb1edc.png)

**Actual Result:**
 Lost error marker in Diff window left pane on "Scroll Bar"
Image

![image](https://user-images.githubusercontent.com/5387680/85185521-19987500-b249-11ea-91ea-ea171f7c0df3.png)

More info:
1.This issue doesn't repro 16.6.0 preview7, 16.5.0,16.4.0
2.This issue can repro 16.7.0 preview 1.0, 16.7.0 preview 2.0,  16.7.0 preview 3.0, 16.7.0 preview 4.0[master-30217.110 ]

**Comment by gundermanc** [comment]
This doesn't seem to be an IDE bug, error squiggles still appear in the left pane with the [VS Spell Check](https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/ErrorList/C%23) extension sample.

**Comment by CyrusNajmabadi** [comment]
Closing out as external this is handled by editor/lsp.
