### ISSUE TITLE
Transitive Closure different implementations? VB vs C#

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#45331]
Looking at optimising `TransitiveClosure(Of T)` in PR #45330 
Only then to realise that this method isn't called by anyone, is `TransitiveClosure` handled differently to CSharp? 

In C# it is used by [DependsOn](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/TypeParameterSymbolExtensions.cs#L23), that has 5 callees, in `ConversionBase.cs`
[Line: 2513](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L2513)
[Line: 2550](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L2550)
[Line: 2825](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L2825)
[Line: 3131](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L3131)
[Line: 3178](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs#L3178)

**Comment by jaredpar** [comment]
Closing as it's unclear what this issue is asking or why we would want to optimize this method. If you believe this method needs to be optimized please provide supporting reasons as to why it should be.
