### ISSUE TITLE
Help referencing Microsoft.CodeAnalysis.CSharp in VS2019 WinForm project targeting Framework 4.0

### ISSUE THREAD

**Issue by tenholde** [dotnet/roslyn#45349]
I have installed the compiler sdk via VS installer on VS2019. I have a Win Form solution based on Framework 4.0. I cannot find a compatible dll to reference that will allow me to use the CodeAnalysis dlls. Can someone help me out here?

**Comment by jaredpar** [comment]
Unfortunately the `Microsoft.CodeAnalysis.*` dlls do not support the `net40` target framework. They require at least `net472` in order to install and run.
