### ISSUE TITLE
Outlining mode no longer works

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1086263/le-mode-plan-ne-fonctionne-plus.html)._

---
When I click on the symbol "-" to reduce a portion of the code it doesn't matter.

I think it started when I uninstalled the reassuming version of Resharper.

This problem is easily reproducible. I open any project and I click "-" outside the code and it doesn't matter.

---
#### Visual Studio Feedback System on 6/22/2020, 02:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 I have not been able to reproduce this issue.
