### ISSUE TITLE
PooledObjects for Stack<T>?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#45350]
Is there a shared pool available for `Stack<T>`?
If so where is it located?

**Comment by CyrusNajmabadi** [comment]
Questions like this are better suited to gitter.im/dotnet/roslyn, or discord.gg (#roslyn channel), thanks!

**Comment by CyrusNajmabadi** [comment]
`ArrayBuilder` is the appropriate pooled entity to use here.
