### ISSUE TITLE
Add Page Number References that actively updates in  '//' comments 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45358]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1084498/add-page-number-references-that-actively-updates-i.html)._

---
Example of basic code with line numbers
------------------------
_22_ | for (int i = 0; i < 5; i++){
_23_ | Console.Write("Hello World!");}
_24_ |

An Example comment:
------------------------------------- 
_75_ | // Look back at line `[23]` and you can see that a message was printed 5 times. 
_76_ | 
_77_ |

By adding a line number as a reference, the comment could act as a hyperlink to code positions in a .  
However, the comment line reference would need to update, as the lines number could change if predecesing code was written.

A problem with currently using line numbers as references to code
-----------------------

_23_ | ThisIsMySwamp();
_24_ |
_25_ |// Get the intruders out of here!
_26_ | GoAwayDonkey();
_27_ | 
_28_ |for (int i = 0; i < 5; i++){
_29_ | Console.Write("Hello World!");}
_30_ |

_75_ | // Look back at line `[23]` and you can see that a message was printed 5 times. 
_76_ | 
_77_ |

Solution
--------------------
The line number in the comments could update with the change in the page. 

_75_ | // Look back at line `[29]` and you can see that a message was printed 5 times. 
_76_ | 
_77_ |

-----
This would help with ViewModels as a single files line numbers tend to be large. 

The code reference could be extended to other files within a solution. 

Example
------------------
_75_ | // Look back at line `[SwampClass, 23]` and you can see that a message was printed 5 times. 
_76_ | 
_77_ |

}

---
#### Visual Studio Feedback System on 6/19/2020, 01:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This seems very niche, and unlikely to be something we would do absent a lot of customer feedback wanting such a thing.  It's very unclear how this could work well, especially given a user could easily mutate the referenced line, potentially adding the portion of interest up/down.  This would trivially lead to these references being incorrect, forcing them to be manually updated.
