### ISSUE TITLE
FindAllReferences doesn't find usages of GetAsyncEnumerator in await foreach

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#45352]
**Version Used**: 16.7 preview 2

**Steps to Reproduce**:

find all references of GetAsyncENumerator in the below code:

```csharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

public class C
{
    public static async Task Main()
    {
        await foreach (var i in new C())
        {
            Console.Write(i);
        }
    }

    public async IAsyncEnumerator<int> GetAsyncEnumerator() => null;
}
```
**Expected Behavior**:
Returns 1 usage in `await foreach` (this happens for `GetEnumerator` and `foreach`)

**Actual Behavior**:
Finds no usages.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
