### ISSUE TITLE
VB typing endif shortcut has changed - EndIfDirectiveTriviaSyntax gets in the way

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45356]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1081007/vb-typing-endif-shortcut-has-changed-endifdirectiv.html)._

---
using VB a great little shortcut I got in the habit of using was typing endif and it would automatically add the space and worked great.

now when I type endif and hit enter it gets changed to the intellisense found item EndIfDirectiveTriviaSyntax
from Microsoft.CodeAnalysis.CSharp.Syntax

I find myself having to fix these multiple times a day after being used to the shortcut that has been there for many years.

this is for .net core 3.1 - visual studio 16.5.2 (may be earlier .net core versions as well)

---
#### Visual Studio Feedback System on 6/18/2020, 00:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by CyrusNajmabadi** [comment]
this is likely because they're referencing C#'s syntax nodes in scope and EndIfDirectiveTriviaSyntax is a direct prefix match, so it gets precedence.  This is unlikely to hit other customers. Only those both using VB *and* referencing Roslyn's C# syntax nodes.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change tehse experiences.
