### ISSUE TITLE
Completing 'await' should automatically add 'async' if missing

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#45368]
📝 Derived from https://github.com/dotnet/roslyn/issues/45287#issuecomment-647774658

* Make sure `await` is presented as a completion item in synchronous methods that return a task-like type
* The completion commit operation for the `await` keyword should automatically add `async` if it is missing from the containing member

**Comment by Youssef1313** [comment]
I want to jump into this and give it a try. Can you provide a starting point to this please? @CyrusNajmabadi @sharwell

**Comment by CyrusNajmabadi** [comment]
I would do this as a special completion provider.  It works create the single `await` completion item. That provider would implement the 'GetTextChange' operation to make both modifications (both the addition of the 'await', and the change to 'async')

**Comment by Youssef1313** [comment]
@sharwell @CyrusNajmabadi I started working on initial implementation for this. But couldn't get it to a working state ;-(
I'm okay if someone wants to take it over or point me to how I can continue working on it.

**Comment by CyrusNajmabadi** [comment]
>  or point me to how I can continue working on it.

I don't have enough information on what is wrong to give any pointers on what to fix. :)
