### ISSUE TITLE
Opening solution through Start Window instead of Windows Shell makes VS slow

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn#45371]
**Version Used**: 16.7.0 Preview 4.0 [30222.8.master]

**Steps to Reproduce**:

1. Open Visual Studio, **pick a solution from Start Window**
1. Wait for all background tasks to finish and task manager shows 0% CPU usage
1. Start PerfView, record trace
1. Do a bunch of typing. For example `return NameOfExistingMethod(nameOfExistingVariable);` over and over again for a minute
1. Stop trace collection

**Steps to get baseline**:

1. Open **the same solution through command prompt**  `devenv path\to\solution.sln`**
1. Wait for all background tasks to finish and task manager shows 0% CPU usage
1. Start PerfView, record trace
1. Do a bunch of typing. For example `return NameOfExistingMethod(nameOfExistingVariable);` over and over again for a minute
1. Stop trace collection

**Expected Behavior**:

When diffing, the traces don't have significant differences

**Actual Behavior**:

When solution is opened from Start Window, there is a significant difference. The difference appears related to getting semantic data in Signature Help as well as performing pattern matching for completion (but this could be a result of performing completion at a different rate)

Notable differences, % inclusive samples after a brief look
* 9% `SemanticModelWorkspaceServiceFactory.SemanticModelService.GetSemanticModel`, through`AbstractSignatureHelpProvider.CreateItemImpl` I see large usage of SemanticModelService
* 9% `SignatureHelp.Controller.Session.ComputeModelInBackgroundAsync`
* 7% `PatternMatcherExtensions.GetFirstMatch` called from `ItemManager.UpdateCompletionListAsync`
* 2% `StreamJsonRpc`
* 2% `CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync`

**Really?**

Yes, we have a few reports of this happening, including [this customer](https://developercommunity.visualstudio.com/comments/1084501/view.html)

**Comment by AmadeusW** [comment]
Microsoft developers may perform their own traces or compare traces at
"\\amadeus\perf\completion slow 202006\solution load\start page steady\StartAhk.etl.zip"
"\\amadeus\perf\completion slow 202006\solution load\windows shell\ShellAhk.etl.zip"

**Comment by CyrusNajmabadi** [comment]
hey @AmadeusW I cannot get to your shares.  Can you put them somewhere public so i can download them?  i.e. google-drive or onedrive?

**Comment by CyrusNajmabadi** [comment]
So i wasn't able to repro this.  Will need the traces to see what's up.

Talked to jason and we're going to take a multi-pronged approach to getting more information here.  We have a strong suspicion the existing 'cache' here likely does more harm than good.  We're going to do RPS experiments with both removing it altogether as well as vastly simplifying it.

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  And the cache in question was rewritten.   We haven't heard anything else about this.  So i'm going to close tihs out.
