### ISSUE TITLE
IDE0032 "Use auto property" leaves behind IDE0003 "Name can be simplified"

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#45385]
**Version Used**: 
16.6.2

**Steps to Reproduce**:
```C#
public class Test
{
    private readonly string serialNumber; // IDE0032
    public Test(string serialNumber) => this.serialNumber = serialNumber;
    public string SerialNumber => serialNumber;
}
```
Run "Use auto proprety" for the `serialNumber` field.

**Expected Behavior**:
The code fixer should remove the `this.` qualifier in the constructor.
```C#
public class Test
{
    public Test(string serialNumber) => SerialNumber = serialNumber;
    public string SerialNumber { get; }
}
```

**Actual Behavior**:
```diff
-    public Test(string serialNumber) => SerialNumber = serialNumber;
+    public Test(string serialNumber) => this.SerialNumber = serialNumber;
```
The `this.` qualifier in the constructor immediately triggers IDE0003 "Name can be simplified".

![image](https://user-images.githubusercontent.com/1947968/85391995-34216580-b54b-11ea-959d-c8143f7dc6d9.png)

**Comment by CyrusNajmabadi** [comment]
This would need the fixer to check the user's current qualification style, and validate that at thsi replacement location that replacing with the non-qualified name won't cause an error.

**Comment by CyrusNajmabadi** [comment]
Closing out due to the high complexity of any fix here, and lack of broader feedback about this issue.
