### ISSUE TITLE
c# 9 is not supported in .net5 preview5.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/roslyn#45380]
**Development env:**
- VS 2019 v16.6.2
- .net5 preview 5 is installed
```
$ dotnet --version
```
>5.0.100-preview.5.20279.10
 
- create a console project with c# 9 enabled. I use `preview` because `9.0` is not available
```xml
 <TargetFramework>net5.0</TargetFramework>
 <LangVersion>preview</LangVersion>
```
 
- Add the next class 
```cs
public class Person
    {
        public string FirstName { get; init; }
        public string LastName { get; init; }
    }
```
Then rebuild from within vs 2019 :

I get a compilation error:
>error CS1014: A get or set accessor expected

Also, `dotnot build ` raise the same error

How to enable c#9 in vs 2019 v16.6.2 and .net5 preview5?

**Comment by jaredpar** [comment]
This is expected as the `init` feature won't make it into `.net5` until a later preview. The code is in our main branch now so it should show up in `preview 7`
