### ISSUE TITLE
Codelens reference links are added to selected field last

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45395]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1078861/codelens-reference-links-are-added-to-selected-fie.html)._

---
When using F12 to "Go to definition" of a field in a model class with a large amount of properties (30+), Codelens adds reference links to the properties starting from the bottom of the file, then stops before the field you went to the definition of, then starts at the top of the file and works its way down.

This means that the property you want to look at gets its Codelens information last. This happens consistently, causing a minor delay in workflow.

---
#### Visual Studio Feedback System on 6/15/2020, 07:43 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Visual Studio Feedback System on 6/16/2020, 02:47 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is outside roslyn.  We don't control the order the tags compute their data in.  Up to @olegtk if you guys want to do anything here.  I imagine this will all be redone with lsp anyways.
