### ISSUE TITLE
[loc][Query][dotnet_roslyn] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn#45419]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50207 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterOmitValue" | <omit> | Is this string localizable?
50606 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterInferValue" | <infer> | Please clarify context. Is it   localizable as a verb?
50666 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_FuncPtrRefMismatch" | Ref mismatch between '{0}' and   function pointer '{1}' | Is ref referred to ref modifier   or is a simple abbreviation of reference?
50678 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_BadFuncPointerArgCount" | Function pointer '{0}' does not   take {1} arguments | What does {1} stand for?     Does it number of arguemnts?
50690 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_AddressOfToNonFunctionPointer" | Cannot convert &method group   '{0}' to non-function pointer type '{1}'. | Would you please confirm   "&" functinos as a hotkey here?
50739 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_CantChangeInitOnlyOnOverride" | '{0}' must match by init-only of   overridden member '{1}' | Please clarify "by   init-only" and confirm that it is localizable

**Comment by 333fred** [comment]
Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer
-- | -- | -- | -- | -- | --
50666 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_FuncPtrRefMismatch" | Ref mismatch between '{0}' and   function pointer '{1}' | Is ref referred to ref modifier   or is a simple abbreviation of reference? | Ref is an abbreviation of reference here
50678 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_BadFuncPointerArgCount" | Function pointer '{0}' does not   take {1} arguments | What does {1} stand for?     Does it number of arguemnts? | Yes, it is the number of arguments
50690 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_AddressOfToNonFunctionPointer" | Cannot convert &method group   '{0}' to non-function pointer type '{1}'. | Would you please confirm   "&" functinos as a hotkey here? | & corresponds to the syntax the user typed

I added an answer column for each of the function pointer questions @PDostalek. Let me know if there's any more clarification needed for these ones.

**Comment by PathogenDavid** [comment]
> Ref is an abbreviation of reference here

Is this correct? ["Ref" in this error is referring to the ref keyword for a reference return value.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKFygZgAJ0iAVOWXAb1yPpOJQwDYiE4AzIgSwDsY5SjADqPGAAsASlwAUASjoNlAXgB8RSQgD2AdyJ8ArgBtjAbiX1LjEq14ChsMZO2GYMzguuqNWvQZNza2tCIkM+KAhOOBIAFiIAWS8cZVoU5QYAEzhjOABzCHgAKiIAHg5ufhhfYQt0jM1hIhUiADIKJ3FpLjqG+nhYZraO0S7Xdx7rAF9cKaA=) I know that technically the `ref` keyword is short for reference, but I don't think that matters in the context of @PDostalek's question since I would assume keywords don't get translated in error messages.

**Comment by 333fred** [comment]
Yes, that's correct. It could be a mismatch between `ref` and `out`, or `in` and `out`. It's not specific to `ref` alone.

**Comment by PDostalek** [comment]
Thank you @333fred

**Comment by PDostalek** [comment]
corrected 


50207 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterOmitValue" | \<omit\> | Is this string localizable?
-- | -- | -- | -- | --
50606 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterInferValue" | \<infer\> | Please clarify context. Is it   localizable as a

**Comment by jcouv** [comment]
Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50739 | Compilers\CSharp\Portable\xlf\CSharpResources.xlf | 0;   "ERR_CantChangeInitOnlyOnOverride" | '{0}' must match by init-only of   overridden member '{1}' | Please clarify "by   init-only" and confirm that it is localizable

"init-only" means that we have a "set" accessor which is restricted to be called during initialization. That accessor is called "init" in the code. Yes, I think we can localize the term.

**Comment by allisonchou** [comment]
@PDostalek Here is the information for the remaining two strings. Thanks for your patience:
Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer
-- | -- | -- | -- | -- | --
50207 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterOmitValue" | \<omit\> | Is this string localizable? | Yes, the string is the verb "omit" contained within two angled brackets, i.e. "\<omit\>"
50606 | Features\Core\Portable\xlf\FeaturesResources.xlf | 0;   "ChangeSignature_NewParameterInferValue" | \<infer\> | Please clarify context. Is it   localizable as a verb? | Yes, the string is the verb "infer" contained within two angled brackets, i.e. "\<infer\>"

**Comment by allisonchou** [comment]
Marking this issue as resolved, but feel free to re-open if there are any additional questions about the strings. @PDostalek

**Comment by PDostalek** [comment]
@allisonchou  What does <infer> stand for?

**Comment by allisonchou** [comment]
@PDostalek We use "infer" here in the context of inferring a value.

**Comment by allisonchou** [comment]
Marking issue once again as resolved, however @PDostalek please let us know if any additional clarifications would be helpful.
