### ISSUE TITLE
Regression: PCLs should have a "debug" tab

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#4542]
Please bring back the "debug" tab under Project>Properties for PCLs. It used to be there in VS2013 but is absent in VS2015.

It's crucial now even more than before.

My scenario: I'm writing an analyzer. I wish to set the Debug tab of this analyzer so that F5 will launch an experimental hive of VS to test it.

Other scenario: I'm writing a NuGet library. Once again I want to use the Debug tab to launch an experimental hive of VS to test it.

**Comment by dpoeschl** [comment]
This might be an Area-IDE thing now. @davkean?

**Comment by dpoeschl** [comment]
Moving to Area-IDE to get a triage opinion of the proper path. /cc: @davkean

**Comment by davkean** [comment]
Assigning to Ravi for the moment as looks like @Pilchie triaged but did not assign.

**Comment by rchande** [comment]
Assigning this to you @davkean, since you said you wanted to fix it.

**Comment by davkean** [comment]
This has been fixed in latest 1.2 builds.
