### ISSUE TITLE
[LSP] Move to textDocument/didChange and friends instead of buffer synchronization

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#45427]
The proper LSP way for the server to hear about document changes is through the textDocument/didOpen, didChange, and didClose events.

We should consider moving to these events to ensure the correct ordering of messages.

At the same time `ExecuteWorkspaceCommandHandler` also needs to be marked as mutating, and tested as appropriate.

**Comment by vatsalyaagrawal** [comment]
@dibarbet please set appropriate milestone for this one.

**Comment by davidwengier** [comment]
Random notes:
* When LSP receives didOpen, fork the solution
* On didChange apply the change to the document in the forked solution
* All LSP methods use the copy of the solution (ie, uses the document with the changes applied)
* We don't need to apply any changes to the real solution, as Live Share buffer sync will catch up
* GetOpenDocumentInCurrentContextWithChanges already does this (of a fashion)
