### ISSUE TITLE
[suggestion] Summary Comments for Class Access Modifiers

### ISSUE THREAD

**Issue by attrib75** [dotnet/roslyn#45432]
It would be useful to have summary comments appear when hovering over access modifiers for a class, to remind us what each access modifier is meant for:

public, private, protected, etc.

Example:
`public class MyClass{}`

Hover over the "public" access modifier --> tooltip shows "The type or member can be accessed by any other code in the same assembly or another assembly that references it."

**Comment by dibarbet** [comment]
Design meeting notes
We think this feature would be too noisy for experienced developers.  There is not enough space in quick info to offer an appropriate explanation and these language features are generally learned relatively quickly.  Additionally, F1 help on the modifier will open the relevant documentation where the it can be explained in detail.

I've filed an additional issue where F1 help for combination modifiers is not working correctly.
https://github.com/dotnet/roslyn/issues/46142
