### ISSUE TITLE
Find references, go to definition on ConditionalWeakTable.GetValue

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#45437]
**Version Used**: 3.7.0-4.20323.4+11e94bdd96f1500f7762b923728e4d322a43bdc7

**Steps to Reproduce**:

1. Go to some use of ConditionalWeakTable.GetValue, for example https://github.com/dotnet/roslyn/blob/2f626aa36002c7c6803c123534d1bebf8e5fbd86/src/Workspaces/Core/Portable/Workspace/Workspace_Registration.cs#L87
2. Invoke Find References on the GetValue.

**Expected Behavior**: It works.

**Actual Behavior**: I'm told there's no references.

**Fun Fact:** go to definition doesn't work either:

```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot navigate to the symbol under the caret.
---------------------------
OK   
---------------------------
```

Oddly I *can* go to other members of ConditionalWeakTable.

**Comment by CyrusNajmabadi** [comment]
Wacky.  I repro this, but cannot explain it either.  Will have to debug through.

**Comment by CyrusNajmabadi** [comment]
So i have found the issue, but i cannot come up with a self-contained repro for it.  

Specifically, consider the following code in a .netcore 3.1 project:

```c#
using System.Runtime.CompilerServices;

class c
{
    private readonly ConditionalWeakTable<string, string>.CreateValueCallback s_get;

    void Goo()
    {
        ConditionalWeakTable<string, string> s = null;
        s.GetValue("", s_get);  //goto-def on GetValue
    }
}
```

Setting a breakpoint here: 

https://github.com/dotnet/roslyn/blob/e02d3e1d871b781812fdde3acdbbbc632f064138/src/EditorFeatures/Core/FindUsages/IDefinitionsAndReferencesFactory.cs#L107

We see we have an IMethodSymbol for: `System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>.GetValue(TKey, System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>.CreateValueCallback)`

However, if we check the following: `((IMethodSymbol)definition).Parameters[1].Type.IsDefinition` we see a result of `false`.  This corresponds to the `ConditionalWeakTable<TKey, TValue>.CreateValueCallback` parameter of `GetValue`.  Effectively, despite this symbol referring to a nested type in generic type instantiated with its own type parameters, it says it is not the definition, even though it it really should be true.  

Note that we don't do anything fancy here to get this IMethodSymbol.  It's just a plain SemanticModel.GetSymbolInfo.

I cannot make out why or what causes us to get teh bogus one back in the IDE.  However, this ends up breaking things later on down the line for us as we end up getting confused between this type, and the equivalent type (except this time with `.IsDefinition == true`).  

I'll need help with this as it's unclear to me what is going on.

**Comment by CyrusNajmabadi** [comment]
@gafter @jcouv Sorry i couldn't find a simple test-repro for this.  In tests it always seems to work properly.  However, reproing with IDE is *really* simple, and seems to demonstrate the problem immediately.  Could def use some help here with this!

**Comment by gafter** [comment]
Per @CyrusNajmabadi This appears to be a difference in the nullability of the original definition and this reference. Both the top-level nullability and the nullability of the type arguments differ (one is oblivious on the Key and top level, the other unannotated).
