### ISSUE TITLE
Missing file header diagnostic squiggles after the first line if it's a directive

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#45443]
**Steps to Reproduce**:

1.  Open up Roslyn.sln.
2. Delete a file header in a file that has a #nullable enable in the top.

**Expected Behavior**: It squiggles the first line.

**Actual Behavior**: It squiggles the blank line between the #nullable and the first real line:

![image](https://user-images.githubusercontent.com/201340/85639845-e128da80-b63e-11ea-98ca-1f4fbc2a64ba.png)

Seems odd to not just always squiggle the top of the file in this case...

**Comment by sharwell** [comment]
It's allowing for the case where the first line is a suppression. If we don't do it this way, then we have to implement semantically-aware processing logic for the trivia at the start of a file.

📝 It's not hard to detect a single line with a pragma suppression for this diagnostic, but it's more complicated to support a `#nullable` directive followed by potentially multiple `#if`, `#region`, and/or `#pragma` directives that eventually lead to a suppression for the header diagnostic.

**Comment by jasonmalinowski** [comment]
> 📝 It's not hard to detect a single line with a pragma suppression for this diagnostic, but it's more complicated to support a #nullable directive followed by potentially multiple #if, #region, and/or #pragma directives that eventually lead to a suppression for the header diagnostic.

I get the complicated case is complicated, but if there aren't any #pragmas or #ifs at all, isn't that enough?

**Comment by sharwell** [comment]
No objection if someone wants to submit improvements here 😄

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
