### ISSUE TITLE
[Bad Code Gen] VB.Net Initialization issues in Visual Studio 2015

### ISSUE THREAD

**Issue by SagarDevanahalli** [dotnet/roslyn#4544]
We see a significant difference in initializing multiple variables in VB .Net applications developed in VS 2013 from VS 2015.

For Example: In below line of code all the variables will be initialized to type Class1 if run on Visual Studio 2013. But when run on Visual Studio 2015 we see only the first variable being initialized and other variables not initialized.

 Friend WithEvents a, b, c As New Class1

Note: Please rebuild the sample application when testing on respective version of Visual Studio.

Please see the attached images .
When debugging in Visual Studio 2013
![vs2013](https://cloud.githubusercontent.com/assets/13787423/9260497/9cd68374-4225-11e5-82ff-14f36732ef5e.PNG)

When debugging in Visual Studio 2015
![vs2015](https://cloud.githubusercontent.com/assets/13787423/9260496/9cd55ec2-4225-11e5-94a0-d1ee59e54450.PNG)

**Comment by gafter** [comment]
`WithEvents` is required to reproduce this issue.

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
