### ISSUE TITLE
Is there an option to make Roslyn Diagnostics traverse the syntax tree in inter-procedural manner? 

### ISSUE THREAD

**Issue by pavanupb** [dotnet/roslyn#45478]
Is there any option available in Roslyn where the analyzer can traverse the syntax tree of the source code in an interprocedural manner?. 
For instance, consider the below program:
```
static void main()
{
     int a = 10;
     int b = 20;
     int result = add(a, b);
     int addResult = result;
     Console.Writeline(addResult);

}
private int add(int x, int y)
{
    return x + y;
}
```

Right now the Roslyn is performing a block code analysis I guess. Is there an option where the Roslyn Diagnostics can traverse the add method first like an interprocedural analysis and then traverse the last two statements of the main method?.

**Comment by CyrusNajmabadi** [comment]
No, there is not.  Sorry!

**Comment by sharwell** [comment]
We do have an flow analysis framework that supports interprocedural analysis as part of [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers).

**Comment by pavanupb** [comment]
Thank you. How can I compile my code using Roslyn SDK that shows all of the diagnostics messages for an entire solution?
