### ISSUE TITLE
`static` local functions cannot capture themselves

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#45486]
```cs
using System;
public class C {
    public static void M() {
        static void local()
        {
            Action a = local; // error CS8422: A static local function cannot contain a reference to 'this' or 'base'.
        }
    }
}
```

**Comment by gafter** [comment]
Seems to work in master:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAI8KBhCgbxIuasu3wDYqAWCgWQAUASgZMW49l2y8ANgHsAxhBn5hY8c0bENOqvlwUIFALwV5SmbgDcFAPS2KiBHIS0AygA5uuXCAoBBPS5zZQoAMwBXADsFGABLOSiKJSiouRhkxJgIOKSjBDgwxDgYuAoYOQoAchgACzioKooXauBoOCqAOnUNAF8eiU4eM0VlXDVtXS1dDXYDI1MQlRt7RwRnVxpPb18AoJGLcOjYhKSUtIyFLJy8igKigtLyypr6xubXKraoDu7JnX6/wogMBQA==

**Comment by 333fred** [comment]
No, I'm saying that it didn't work locally. I'll need to double check.

**Comment by 333fred** [comment]
This is apparently fixed in master.
