### ISSUE TITLE
Parameter name is suggested with number suffix while it should be plain

### ISSUE THREAD

**Issue by miqm** [dotnet/roslyn#45492]
**Version Used**: 16.7-preview3.1

**Steps to Reproduce**:

1.  In class, create method with CancellationToken parameter and name `cancellationToken`
2.  Next, create another method also with CancellationToken, observe suggested name
![image](https://user-images.githubusercontent.com/7921224/85904232-73300f00-b808-11ea-98a3-7d081e02b009.png)
![image](https://user-images.githubusercontent.com/7921224/85904316-af636f80-b808-11ea-8400-1904dbb91190.png)

**Expected Behavior**:
IDE should suggest `cancellationToken` parameter name
IDE should not add suffix number to parameter name. suffix should be added only if we are using same type in same method.

**Actual Behavior**:
IDE suggests `cancellationToken1` parameter name.

**Comment by miqm** [comment]
If it helps, I compiled branch 16.7-preview2 and there it works correctly.

**Comment by miqm** [comment]
I found the reason behind this behaviour. in 4f286bee `SyntaxKind.CompilationUnit` was added to method `IsExecutableBlock` in CSharpSyntaxFacts.cs, see: https://github.com/dotnet/roslyn/pull/44622/files#r446560733
```
That change made following code in GenerateUniqueName method in AbstractSemanticFactsService return compilation unit (previously was null returned):
```
var container = containerOpt ?? location.AncestorsAndSelf().FirstOrDefault(
    a => SyntaxFacts.IsExecutableBlock(a) || SyntaxFacts.IsMethodBody(a));
```

That lead take to name check **all** parameters from **entire** file which resulted in generating suffix.

**Comment by sharwell** [comment]
@miqm Thanks for figuring that out! I'll take a look.

**Comment by sharwell** [comment]
@miqm Your work was _extremely_ helpful. I didn't have any plans to do Roslyn work in the middle of this weekend but you made it so simple _why not_?
