### ISSUE TITLE
[Suggestion] Intellisense to provide "a better" Type suggestion.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#45506]
Think that the intellisense could be a little more intelligent in regarding return type "deduction".

For example lets say we have the following code.
```vbnet
Public Function IsBefore(value As Char, beforeChar As Char)
  Return value < beforeChar
End Function
```
and are looking to make to return type more specific. We type ` As ` and wait for intellisense results to appear.
```vbnet
Public Function IsBefore(value As Char, beforeChar As Char) As 
  Return value < beforeChar
End Function
```
I would like `Boolean` to be first suggestion.

This suggestion is based on the result of the `Return value < beforeChar`, which in this case is `Boolean`.

-------
Should there be multiple return statements in the method,  we return the Dominant Type covering those possible return types.
This could also extended to include "interface methods" the method should implement eg `Implements Example.IsBefore`
```vbnet
Interface Example
  Public Function IsBefore( value As Char, beforeChar As Char) As Boolean
End Interface

Class ExampleObject
  Implements Example

  Public Function IsBefore( value As Char, beforeChar As Char ) As _$_  Implements IExample.IsBefore
     Return value < before
  End Function
End Class
```
```vbnet
Dim dominant_Type = Find_DominanteTypeOf(
			{ Current_Return_Type, 
    	       		  Return_Expressions_Types,
			  Applicable_Interface_Return_Types
                        } )
```

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 we would likely take a PR here if you wanted to contribute one.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this area.
