### ISSUE TITLE
Targeting IDE layer projects to .Net Core

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#45534]
So we can eventually switch Roslyn OOP process in VS to .Net Core version of servicehub

This also include unit tests.

**Comment by genlu** [comment]
https://github.com/dotnet/roslyn/pull/45115 is related to this

**Comment by genlu** [comment]
@sharwell Are you planning to work on those tests projects too?

**Comment by sharwell** [comment]
I am

**Comment by genlu** [comment]
This targeting test utility to Core https://github.com/dotnet/roslyn/pull/45793

**Comment by sharwell** [comment]
Workspace tests: #45813

**Comment by genlu** [comment]
The main remaining task is to refactor IDE unittest at Feature and EditorFeatuer layer to run on coreclr.

**Comment by genlu** [comment]
Keep this in 17.1 since this is used for tracking testonly change

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, assign it to a milestone.
