### ISSUE TITLE
Rough edges when combining Records with System.Text.Json serializers

### ISSUE THREAD

**Issue by joshlang** [dotnet/roslyn#45551]
First.  I love these two awesome things:
- Records
- System.Text.Json

And they should get married.  And marriage should be a frictionless wonderful experience :D  But they're still squabbling a bit.

Consider this:
```
record Test1(int Hello);
...
var s = JsonSerializer.Serialize(new Test1(4)); // { "Hello": 4 }
var t = JsonSerializer.Deserialize<Test1>(s);
```

It explodes!  The deserializer would match `hello` in the constructor, but not `Hello` (by default).  So you get a `InvalidOperationException`.

Possible workarounds (other than specifying json serialization options to ignore case):  
1) Allow some sort of option to disable auto-camelCasing in the auto-generated constructor
2) Use `record Test1(int hello)` instead, and don't fret that the property name isn't PascalCase
3) Don't use the super-awesome terse way of defining a record

Kudo's that you somehow made `class A { public int Hello { get; init; } }` work with JsonSerializer despite no hidden constructors!!

Another thing that'd be sweet:  `record Test1([JsonPropertyName("meow")] int Hello);` or `record Test1([property: JsonPropertyName("meow")] int Hello);`

Whether something gets baked into the language, or we just need to know how to work around these points... It'd probably be helpful for a lot of folks if there was a blog post somewhere titled **"Making C# Records and System.Text.Json serialization work together"**!  Just a thought.

**Comment by joshlang** [comment]
My comments regarding the constructor casing may be out of date.  I was relying on a blog post in May, and it seems some things have changed.

`new Test1(` <-- Intellisense shows the parameter case as 'Hello', not `hello`

The failure text is:  `Each parameter in constructor 'Void .ctor(Int32)' on type 'zzz.Program+Test1' must bind to an object member on deserialization. Each parameter name must be the camel case equivalent of an object member named with the pascal case naming convention`

Which makes me wonder why the json serializer won't match `Hello` (parameter) to `Hello` (json).  

Regardless... Rough edge nonetheless :D

**Comment by CyrusNajmabadi** [comment]
Closing as out of scope for Roslyn.  I would take this up with the team that owns JsonSerializer :)
