### ISSUE TITLE
Remove roslyn-tools, roslyn-analyzers feeds from myget restore dependencies

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#45573]
https://github.com/dotnet/roslyn/blob/master/NuGet.config#L13

    <add key="roslyn-tools" value="https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json" />
    <add key="roslyn-analyzers" value="https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json" />

### Roslyn-tools packages
Missing entirely-

| Package Name | Proposed Feed | Uploaded Feed
| --- | --- | --- |
| ~~Microsoft.CodeAnalysis.Test.Resources.Proprietary~~ | ~~dotnet-eng~~ | dotnet-eng |
| ~~Microsoft.VisualStudio.Progression.CodeSchema~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.Progression.Common~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.CallHierarchy.Package.Definitions~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.Language.CallHierarchy~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.CodeAnalysis.Sdk.UI~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.Progression.Interfaces~~ | ~~vssdk / vs-impl~~ | vs-impl |
| ~~Microsoft.VisualStudio.GraphModel~~ | ~~vssdk / vs-impl~~ | vs-impl |
| RoslynTools.VSIXExpInstaller | dotnet-eng | https://github.com/dotnet/roslyn-tools/issues/793 |
| ~~Microsoft.VisualStudio.Diagnostics.PerformanceProvider~~ | ~~vssdk / vs-impl~~ | vs-impl |

Incorrect version-
| Package Name | Current Version | Best Match Version | Notes |
| --- | --- | --- | --- |
| ~~Microsoft.NETFramework.ReferenceAssemblies~~ | ~~1.0.0-alpha-004~~ | 1.0.0-preview.1 | Upgraded in #45575 |
| ~~Microsoft.VisualStudio.ComponentModelHost~~ | ~~16.0.198-g52de9c2988~~ | 16.0.342-g758a0a97e0 | Upgraded in #45575 |
| ~~Microsoft.MSXML~~ | ~~8.0.0-alpha~~ | 8.0.0 | Upgraded in #45575 |

### Roslyn Testing packages from dotnet/roslyn-sdk
Missing entirely- 
| Package Name | Proposed Feed | Notes |
| --- | --- | --- |
| Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit | .NET Core Tooling Dev | Channel was assigned and a new build is being run to test publishing |
| Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing.XUnit | .NET Core Tooling Dev | |
| Microsoft.CodeAnalysis.VisualBasic.CodeFix.Testing.XUnit | .NET Core Tooling Dev | |
| Microsoft.CodeAnalysis.VisualBasic.CodeRefactoring.Testing.XUnit | .NET Core Tooling Dev | |

Incorrect version-
| Package Name | Current Version | Best Match Version | Notes |
| --- | --- | --- | --- |
| ~~Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers~~ | ~~3.3.0-beta1.20262.5~~ | 3.3.0-beta1.20262.21 | Upgraded in #45575 |
| ~~Roslyn.Diagnostics.Analyzers~~ | ~~3.3.0-beta1.20262.5~~ | 3.3.0-beta1.20262.21 | Upgraded in #45575 |

### vs-editor packages
Missing entirely-
| Package Name | Proposed Feed |
| --- | --- |
| Microsoft.MSXML | |
| Microsoft.VisualStudio.CodingConventions | |

### Questions
1.  Where is the appropriate place for these packages to move to?  Have some suggestions from @tmat in bold.
2.  Can the incorrect version ones just be upgraded?
3.  Roslyn-tools has other packages not needed to restore Roslyn.  Eventually those should be moved, to where?  There's a bunch of other tools packages that don't really fit in any of the existing feeds

**Comment by dibarbet** [comment]
cc @jaredpar @tmat @markwilkie

**Comment by dibarbet** [comment]
cc @mavasani for roslyn analyzers packages

**Comment by tmat** [comment]
roslyn-analyzers already publish to `dotnet5` feed.

```
>darc get-default-channels --source-repo analyzers
(1590) https://github.com/dotnet/roslyn-analyzers @ master -> .NET 5 Dev
```

**Comment by tmat** [comment]
Microsoft.VisualStudio.* packages should go to vssdk or vs-impl feed. Need to check with the VS teams who own these.

**Comment by tmat** [comment]
Incorrect version - we should try to update to the latest available version of the package.

**Comment by mavasani** [comment]
@sharwell for analyzer/fix/refactoring testing related packages.

**Comment by jasonmalinowski** [comment]
Note that the Progression/GraphModel packages we use today are ones we manually created for ourselves because there were never packages from the vssdk. See https://github.com/dotnet/roslyn/tree/master/scripts/GenerateSdkPackages for the background on this. If there's packages we can just upgrade to that'd be best, but just wanted to call out that if anybody is trying to figure out where those packages came from, that's where. :smile:

**Comment by tmat** [comment]
If the packages are still not available then let's start a thread with VS Platform asking them to publish them.

**Comment by jaredpar** [comment]
> If the packages are still not available then let's start a thread with VS Platform asking them to publish them.

Agree. The last conversation we had with them was 3+ years ago. At that time they didn't want the burden of producing the packages themselves but were okay with us doing so for our own purposes. That is how we ended up in this situation. 

It's a different environment now. Our needs are no longer unique. My guess is they'll be more receptive this time to owning this on their end.

**Comment by jasonmalinowski** [comment]
Over the last three years I think practically most of the packages have been produced; even though we haven't ran the generation script in quite some time I've been deleting entries from it as we got official packages for various entries in it. I think what's left may have no owner so we might still have some trouble sorting those bits out though. We'll see.

**Comment by dibarbet** [comment]
The MS.VS.CallHierarchy.Package.Definitions is listed under the compiler area path for ownership - 
https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms-eswm.ownership.ownership-hub#query=Microsoft.VisualStudio.CallHierarchy.Package.Definitions&accounts=Devdiv&projects=DevDiv

Source - https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fcsharp%2FCallHierarchyPackage%2FDef%2FCallHierarchyDef.csproj
@jaredpar is this anything you know about?  We may need to implement publishing for this one (or just continue to manually add it as we have been doing, but to ADO instead)

We are also listed as the owner for MS.VS.CA.Sdk.UI - https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms-eswm.ownership.ownership-hub#query=/src/edev/StaticAnalysis/SDK/UI/Microsoft.VisualStudio.CodeAnalysis.Sdk.UI.csproj&accounts=devdiv&projects=DevDiv&repos=VS
Source - https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fedev%2FStaticAnalysis%2FSDK%2FUI%2FMicrosoft.VisualStudio.CodeAnalysis.Sdk.UI.csproj&version=GBmaster&_a=contents

So we need to take care of that one too I think.

I've emailed the listed owners of the others.

**Comment by JoeRobich** [comment]
The Microsoft.CodeAnalysis.Testing.* packages reside in roslyn-sdk and it doesn't seem to using arcade publishing.

```
darc get-default-channels --source-repo roslyn-sdk
No matching channels were found.
```

**Comment by dibarbet** [comment]
> The Microsoft.CodeAnalysis.Testing.* packages reside in roslyn-sdk and it doesn't seem to using arcade publishing.
> 
> ```
> darc get-default-channels --source-repo roslyn-sdk
> No matching channels were found.
> ```

@mavasani @sharwell do either of you know if this should be configured for arcade publishing?

**Comment by jmarolf** [comment]
We can make it so. Go ahead and file an issue on roslyn-sdk @dibarbet. I can make the change

**Comment by JoeRobich** [comment]
@dibarbet @jmarolf  I updated roslyn-sdk to publish to .NET Core Tooling Dev. Kicked off a new build to test asset publishing.
