### ISSUE TITLE
What about a new a idea of functional Storage to reuse in other project easier

### ISSUE THREAD

**Issue by Barthdry** [dotnet/roslyn#45580]
**Version Used**: 
To store a function created parmanently
**Steps to Reproduce**:

1. forever function("---"){
things write here
}

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
Closing out.  
1. Language requests should go to dotnet/csharplang.
2. this language proposal is far too vague and unclear :)   I cannot actually understand what it's asking for (i.e. what the semantics of that would be, and how it differs from teh methods/lambdas/functions we already have).  

Feel free to open a new issue over at csharplang.  But please expand more on what you're asking for.  Thanks!
