### ISSUE TITLE
[Question] Why the output is CS0165 when using a is Constant pattern.

### ISSUE THREAD

**Issue by InCerryGit** [dotnet/roslyn#45582]
**Steps to Reproduce**:

https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrjQG4CGATogC4CmAzi4gLyIB2bAO6IAKhQDc1GjgCWAM1LsuiWRzGIAxgHt+tNo1GduPPvPoAbDm3LSZNEAHYpMezhAQAnKR16DRrgA6ADFtbXIXGgBfWBi4fDAxLFdcBGQIAAZEUO1MAHM2FglrIriooA==

Given the following C# example:
```C#
using System;
public class C {
    public void M() {
        var test = new T();
        if(test is T converTest == false)
            return;
        Console.WriteLine(converTest.Foo);
    }
}
public class T{
    public string Foo {get;set;}
}
```
The following result is returned:
> CS0165: Use of unassigned local variable 'converTest '

if `converTest` is null, the method return .  why the output is CS0165 when using a is Constant pattern?

**Comment by RikkiGibson** [comment]
This would require a change to the [definite assignment](https://github.com/dotnet/csharplang/blob/master/spec/variables.md#definite-assignment) specification. If you want to see this happen, feel free to search for or open an issue in the csharplang repo.

**Comment by gafter** [comment]
Previously (incorrectly) reported at
- https://github.com/dotnet/roslyn/issues/31469
- https://github.com/dotnet/roslyn/issues/20969
- https://github.com/dotnet/roslyn/issues/17828
- https://github.com/dotnet/roslyn/issues/39721

The fact that people keep asking this question is perhaps evidence that something should be done. But the suggestion to do something belongs in `csharplang`. As it stands the compiler is obeying the specification.

**Comment by RikkiGibson** [comment]
A spec change proposal has been submitted for discussion at https://github.com/dotnet/csharplang/discussions/4240.
