### ISSUE TITLE
Better GFU Insertion Heuristic

### ISSUE THREAD

**Issue by billchi-ms** [dotnet/roslyn#456]
I love the gen from usage stuff, but something it does annoys me rather than delights me.  It inserts the definition IMMEDIATELY after the close curly of the current function.  If I have a comment there, then it pushes the comment away.  When I quickly grab the new function to put it where it belongs in my code's org, I grab the comment mistakenly.  Then later I notice it and have to go put it back.

While we have to employ heuristics in features like this, I'd suggest that EVERYONE puts a newline between function definitions :-).  It seems like a better heuristic would be to go to the beginning of the line after the close curly (checking that indeed the rest of the line is empty, comments, or whitespace), then open a line and insert the new definition.

**Comment by CyrusNajmabadi** [comment]
Haven't heard anything else on this.  Closing this out as unlikely to happen.
