### ISSUE TITLE
Microsoft.CodeAnalysis.Workspaces.Common depends on a very old version of System.Composition

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#45617]
**Version Used**: 
3.6.0-3.20207.2

**Steps to Reproduce**:

1.  Create a .NETStandard2.0 project (EG: following the source generators tutorial)
2.  Reference Microsoft.CodeAnalysis.Workspaces.Common package.
3.  Examine System.Composition version (ether in assets file, or in the references, etc).

**Expected Behavior**:
Depends on latest System.Composition consistent with other dotnet/runtime packages.  1.4.1

**Actual Behavior**:
Depends on very old System.Composition which brings in old 1.x era packages.  Which is inconsistent with other dependencies from same repo.

Bug here: https://github.com/dotnet/roslyn/blob/0a4e696986ed260c38571f81ff59c325275c374e/eng/Versions.props#L73

/cc @kevinwkt

**Comment by nsulikowski** [comment]
The System.Composition dependency is a constant source of headache whenever I upgrade Roslyn. For instance, right now I cannot upgrade from Microsoft.CodeAnalysis 3.7 to 3.8 and from System.Composition 1.4.1 to 5.0 without getting runtime errors (I believe System.Reflection.ReflectionTypeLoadException)

**Comment by sharwell** [comment]
> Depends on latest System.Composition consistent with other dotnet/runtime packages. 1.4.1

The current reference is consistent with the latest builds of Microsoft.VisualStudio.Composition. The version used in Roslyn would not change prior to two things:

1. The version that Microsoft.VisualStudio.Composition depends on is changed
2. Roslyn updates to use a version of Microsoft.VisualStudio.Composition at or newer to where (1) occurs

> For instance, right now I cannot upgrade ... System.Composition 1.4.1 to 5.0 without getting runtime errors ...

This would be a bug for dotnet/runtime. Roslyn isn't doing anything special with regards to the MEF 2 APIs, so we're relying on downstream applications to provide runtime-compatible implementations of these dependencies and it should all work. With that said, I highly recommend using Microsoft.VisualStudio.Composition for creating your MEF compositions, as it offers overwhelming performance and threading benefits relative to just System.Composition.

**Comment by sharwell** [comment]
@nsulikowski You only need to reference Microsoft.VisualStudio.Composition if you are creating composition instances. For example, if you are creating an instance of `AdhocWorkspace`, you can use Microsoft.VisualStudio.Composition as follows:

```csharp
public AdhocWorkspace CreateWorkspace()
{
    var exportProvider = ExportProviderFactory.Value.CreateExportProvider();
    var host = MefHostServices.Create(exportProvider.AsCompositionContext());
    return new AdhocWorkspace(host);
}
```

Where `ExportProviderFactory` is defined here:
https://github.com/dotnet/roslyn-sdk/blob/5e168b02acc176f98a7b394e639c5ea953ec9ad1/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L30-L41

And `AsCompositionContext` is defined here:
https://github.com/dotnet/roslyn-sdk/blob/5e168b02acc176f98a7b394e639c5ea953ec9ad1/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Extensions/ExportProviderExtensions.cs

**Comment by CyrusNajmabadi** [comment]
@sharwell is htere anything we need to do here, or can this be closed out?
