### ISSUE TITLE
Incorrect indentation when pressing Enter key before a space in XML comment

### ISSUE THREAD

**Issue by dg9ngf** [dotnet/roslyn#4562]
In the following C# code with an XML documentation comment:

```C#
    /// <summary>
    /// This is a summary.
    /// <summary>
    void Method()
    {
    }
```

Place the cursor directly after the word "is", right in front of the space character. Then press the Enter key to insert a line break.

The result is this:

```C#
    /// <summary>
    /// This is
   ///  a summary.
    /// <summary>
    void Method()
    {
    }
```

I'm using tabs for indentation, but in the misaligned line 3 spaces are used instead. This also happens if pressing Enter after "a", but not after "This". It never happened in VS 2013 or 2010.

I've already reported this through VS feedback for RC and RTM but couldn't find an issue here. Is it already tracked elsewhere?

**Comment by Pilchie** [comment]
This is #2091 I believe.

**Comment by dg9ngf** [comment]
Damn, you're right, didn't see it in the search results.
