### ISSUE TITLE
"Substring can be simplified" misses basic cases

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#45637]
**Version Used**: 
IDE0057 handles morecomplicated cases of Substring, but not the basic cases.

**Steps to Reproduce**:

``` C#
var value = "Hello World"
value = value.Substring(1);
```

**Expected Behavior**:
A analyzer message, asking me to change above to:

``` C#
var value = "Hello World"
value = value[1...];
```

**Actual Behavior**:
Nothing

**Comment by CyrusNajmabadi** [comment]
Agreed. We can special case this specific member to work in this fashion.  Do you know of other apis that have the same semantics? (i.e. they expose a `Foo(int start)` method that is equiv to `Foo(int start, Length)`?

**Comment by CyrusNajmabadi** [comment]
Adding help-wanted.  We would take a PR for this.

**Comment by AdamSpeight2008** [comment]
It would be cool if when could express "simplifications", via attributes so we could apply transformations without knowing internals of the method. The compiler apply these transforms at compile-time, a bit like constant-folding (turned to 11).
 
```
/// <transformations>
///  <applicable_transformation>
///    <if_requirements_met>
///      <IsArgConstant(nameof(source)) IsNonNull="true" />
///      <IsArgConstant(nameof(index) ) />
///      <IsArgConstant(nameof(count) ) />
///    </if_requirements_met>
///    <then_consider>
///      <result(typeof(char))>
///         <arg(nameof(source)).Index(0)>
///      </result>
///    </then_consider>
///  </applicable_transformation>
/// </transformation>
public String Substring(String source, Int32 index, Int32 count)
{
}
