### ISSUE TITLE
Include implicitly called methods (e.g. an overloaded "ToString()") in the CodeLens reference count

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45631]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1090754/include-implicitly-called-methods-eg-an-overloaded.html)._

---
Related to
https://developercommunity.visualstudio.com/content/problem/848081/codelens-reference-counter-should-not-include-refe.html
https://github.com/dotnet/roslyn/issues/40427
because this issue also address the reference count of methods.

I want CodeLens to count implicitly called methods in the same way as explicitly called methods.

If you write
```
var testObject = new TestClass ();
string text = $"object is {testObject.ToString()}";
```
then the reference count on the TestClass.ToString() is increased by 1.

But if you write
```
var testObject = new TestClass ();
string text = $"object is {testObject}";
```
then ToString() is still called, but the reference count on the TestClass.ToString() is NOT increased.

---
#### Visual Studio Feedback System on 6/27/2020, 11:51 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
I believe the goal is for each of the various implicit syntaxes to support this case (and other related cases like Find All References and Call Hierarchy). Taking this to a design review to confirm before marking this as help wanted.

**Comment by allisonchou** [comment]
**Design meeting notes (7/13):**

- In general: Usage of a C# language feature defined in terms of an API should be treated as a usage of that API in CodeLens or FAR
- For this issue: String interpolation should be treated as a call to ToString() on most derived type we can identify statically

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.  If far ever updates to support thsi so be it. Otherwise, we're not likely to go make this work.
