### ISSUE TITLE
error loading MSBuildWorkspace for projects containing .xaml files 

### ISSUE THREAD

**Issue by ltcmelo** [dotnet/roslyn#45642]
**Version Used**: 3.6.0

I'm unable to correctly `OpenSolutionAsync` through `MSBuildWorkspace` when a project contains **.xaml** files. I get the following load failure:

     Msbuild failed when processing the file 'C:\...\Name.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets: (268, 9): Unknown build error, 'Object reference not set to an instance of an object.'

Which consequently leads to compilation errors like:

    C:\..\MainWindow.xaml.cs(25,13): error CS0103: The name 'InitializeComponent' does not exist in the current context

I've found [this](https://github.com/dotnet/roslyn/issues/2779) and [this](https://github.com/dotnet/roslyn/pull/2982) old issues (from 2015) that look the same as the one I'm facing. These, along with additional resources I've found online, suggest the setting the MSBuild properties `DesignTimeBuild` and `BuildingInsideVisualStudio` to `true` (in the dictionary that's passed to `MSBuildWorkspace.Create` would fix the issue. However, it seems that those properties are already set by default in the newer `MSBuildWorkspace` versions (I'm using **3.6.0**), so they didn't have any effect.

Other things I've tried as well:

- setting `CheckForSystemRuntimeDependency` to `true`;
- setting `ws.LoadMetadataForReferencedProjects`  to `true` (where `ws` is the workspace created).

None of the above helped.

This is a snippet of how the `.csproj` includes the `.xaml` content.

```
<ItemGroup>
    <Compile Include="MainWindow.xaml.cs" />
    ...
</ItemGroup>
<ItemGroup>
    <Page Include="MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <SubType>Designer</SubType>
    </Page>
</ItemGroup>
```

An invocation of msbuild.exe from the command line successfully builds the project.

What's the recommendation to deal with this kind of artefacts in a project? (I'd accept a "unorthodox" way of compiling the hidden `.g.i.cs` files, as long as it's **robust/reliable**).

**Comment by softwaretirol** [comment]
I would be intrested too,.. i could successfully emit an assembly out of a project which is .NET Core based and contains some XAML Files if I am passing "BuildingInsideVisualStudio". 

In this case, the ".g.cs" files are getting generated, but i am missing the resource files with the compiled (B)XAML content? In case I am removing the "BuildingInsideVisualStudio", i got the same exception as @ltcmelo  

```csharp
using var workspace = MSBuildWorkspace.Create(new Dictionary<string, string>()
{
    { "BuildingInsideVisualStudio", "true" }
});
workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);
workspace.LoadMetadataForReferencedProjects = true;
var project = await workspace.OpenProjectAsync(sourceProject, new ConsoleLogger());
var compilation = await project.GetCompilationAsync();
var res = compilation.Emit("Test.exe");
```
