### ISSUE TITLE
Proposal: Support nested extension methods (including defined in static classes nested within generic classes)

### ISSUE THREAD

**Issue by TyreeJackson** [dotnet/roslyn#4565]
# Problem

> CS1109: Extension methods must be defined in a top level static class; _someStaticClass_ is a nested class
# Proposal

Add support for extension methods defined within nested static classes and scoped only to within the nesting classes and its subclass descendants.
# Why

It would be nice to allow the definition of extension methods within nested static classes that are only available within the scope of the nesting class, especially for extending types nested within the base classes of the nesting type.  This would be just more of the syntactical sugar that extension methods already provide except to provide the following additional benefits:
1. they would be scoped only within a class and its subclasses, access modifiers permitting, to help avoid polluting the outer classes/namespaces
2. they would gain access to type parameters that may be defined in nesting classes instead of having to redeclare them on the static class or the static extension method.

The case for the utility of extension methods is already well discussed and defined.  This proposal takes the same advantages of extension methods and scopes it to within a class and its types.
# Note

I'm aware that this was already considered and rejected previously.  I'm submitting this proposal, one, because I could not find another one for this within this issues system and two because of this [SO answer](http://stackoverflow.com/questions/3930335/why-are-extension-methods-only-allowed-in-non-nested-non-generic-static-class#3934737) by Eric Lippert where he said:

> If you have a scenario where extension methods would be useful in non-static, generic, or nested classes then I'm happy to take a look at the scenario. The more real-world scenarios we get, the more likely it is that we'll make a feature in some hypothetical future language that benefits those scenarios.

My real world scenarios all center around the use of generic classes to form parametric boundaries for sharing type parameters.  As scoping is the primary use case for these types of generic classes, one of the features that naturally feels absent is the ability to define extension methods within static classes defined within these parametric boundaries, especially when the boundaries are defined in one assembly, and then derived within another assembly, where new functionality is added to the derived parametric containers and where integrating that new functionality via extension methods onto base types would be extremely useful.

This question has come up before and each time the answer has been, there is not enough interest or real world justification for it.  So here is an issue where hopefully those others who have not given up hope can chime in for this feature.  :-)

**Comment by gafter** [comment]
This is similar to the first item under the "Small but Useful" section of #2136. As such the general idea is already under consideration.

**Comment by TyreeJackson** [comment]
Thanks @gafter for the consideration!

**Comment by phillip-haydon** [comment]
+1

**Comment by gafter** [comment]
The LDM has triaged this as something we would consider doing... but we don't have a champion for it yet.

**Comment by gafter** [comment]
Issue moved to https://github.com/dotnet/csharplang/issues/301
