### ISSUE TITLE
ServiceHub is crashing many times a day

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#45668]
ServiceHub has started crashing many times throughout a day in 16.7 Preview 4 builds.

**Version Used**: 
Version 16.7.0 Preview 4.0 [30301.213.master]

Logs: [CodeAnalysis.zip](https://github.com/dotnet/roslyn/files/4877146/CodeAnalysis.zip)

I have to restart VS so that out of proc features such as Find All References, Go To Definition function.

Here's one example, but I see a tonne of different errors in those logs:
```
07/06/2020 16:35:14 AUS Eastern Standard Time: Error : 1 :[devenv:49108] Unexpected exception: System.InvalidOperationException: We should always be able to resolve a symbol back on the host side:
1 (B "invalidPath" 8 (% 2  1 "C:\roslyn\src\Compilers\Core\Portable\CommandLine\CommandLineParser.cs" 13743 11  1 "C:\roslyn\src\Compilers\Core\Portable\CommandLine\CommandLineParser.cs" 13743 18) 0 0)
   at Microsoft.CodeAnalysis.Remote.SerializableSymbolAndProjectId.<TryRehydrateAsync>d__7.MoveNext()
07/06/2020 16:35:14 AUS Eastern Standard Time: Error : 1 :[devenv:49108] Unexpected exception: System.InvalidOperationException: We should always be able to resolve a symbol back on the host side:
1 (B "invalidPath" 8 (% 2  1 "C:\roslyn\src\Compilers\Core\Portable\CommandLine\CommandLineParser.cs" 13743 11  1 "C:\roslyn\src\Compilers\Core\Portable\CommandLine\CommandLineParser.cs" 13743 18) 0 0)
   at Microsoft.CodeAnalysis.Remote.SerializableSymbolAndProjectId.<TryRehydrateAsync>d__7.MoveNext()
07/06/2020 16:35:14 AUS Eastern Standard Time: Error : 10 :Exception thrown from request "9" for method OnReferenceFoundAsync: System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesServerCallback.<OnReferenceFoundAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindReferencesServerCallback.<OnReferenceFoundAsync>d__13.MoveNext()<---
```

**Comment by davkean** [comment]
Note that symbol it's complaining about "invalidPath" was removed in a branch that was not currently active.

**Comment by CyrusNajmabadi** [comment]
> Note that symbol it's complaining about "invalidPath" was removed in a branch that was not currently active.

That seems bad.  It indicates that OOP and VS are not in sync with their solution snapshots.  @tmat do you know of any issues that would cause that?

**Comment by CyrusNajmabadi** [comment]
Note: i nthe callstack above, it's VS actually throwing the exception because OOP is saying "i found a reference" that VS says it has no clue about.  Given that Dave says that hte symbol being referred to is in a branch that is'nt active, that means the OOP process is pointing at some sort of incorrect and/or stale solution.  That seems very very bad.

**Comment by davkean** [comment]
I changed that symbol in a branch, not sure whether VS or OOP was out of date.

**Comment by CyrusNajmabadi** [comment]
> Note that symbol it's complaining about "invalidPath" was removed in a branch that was not currently active.

So in the above stack, this is a case of hte OOP server attempting to tell VS about a result.  OOP is saying "i found the result 'invalidPath'", and VS is saying "i have no idea what that is".  So, in this case, since that branch isn't active, it sounds like this is a case where VS is correct, and OOP is operating on stale data.

@tmat you mentioend an issue with codelens.  I know they use the FIndRefs apis.  Is it possible that they're doing something wrong with snapshots here?

**Comment by tmat** [comment]
@CyrusNajmabadi The CodeLens issue i fixed is not related to FindRefs.

**Comment by tmat** [comment]
@CyrusNajmabadi I wonder if we call `workspace.CurrentSolution` somewhere multiple times instead of reusing the same solution. Or something of that kind.

**Comment by CyrusNajmabadi** [comment]
The issue with TryRehydrateAsync was fixed with https://github.com/dotnet/roslyn/pull/47343
