### ISSUE TITLE
References to static members in IPropertySubpatternOperation shouldn't have synthesized instance receivers

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#45666]
See IsPattern_BadRecursivePattern_07 unit-test. This violates the principle for the shape of IOperation tree.

See also https://github.com/dotnet/roslyn/pull/45454#pullrequestreview-441861480, https://github.com/dotnet/roslyn/pull/45454#pullrequestreview-441862381 and https://github.com/dotnet/roslyn/pull/45454#pullrequestreview-441862828

**Comment by gafter** [comment]
Dup of https://github.com/dotnet/roslyn/issues/45660
