### ISSUE TITLE
Compilation errors from build not reported in Error window

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4567]
When code fails to build, the errors are not reported in the Error window.

See #4035 for a particular example of this issue.

**Comment by srivatsn** [comment]
This bug tracks the issue whereby the error list doesn't show the diagnostics from emit phase even after a full build. The IDE likely filters this out because it thinks that this diagnostic would be emitted during live analysis.

**Comment by heejaechang** [comment]
basically to fix this properly, we need this
https://github.com/dotnet/roslyn/issues/1400

otherwise, when we do de-duplication, we don't know what diagnostic we can remove and what we need to keep.

**Comment by heejaechang** [comment]
I am closing this bug dup to #1400
