### ISSUE TITLE
Code gets mangled by Edit.MoveSelectedLinesDown command

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1100661/code-gets-mangled-by-editmoveselectedlinesdown-com.html)._

---
VB Code:

```vb
Dim i As Integer

Dim outputTypes = (From s In outputsToUpdate
                                   Group s By sType = s.OutputType Into Group
                                   Select outputs = Group, outputtype = sType)
```

Put the cursor on the `Dim i As Integer` line.

Invoke the **Edit.MoveSelectedLInesDown** command to try and move this line to after the LINQ query.

The word `Case` gets inserted after the word `Select` in the LINQ query, subsequently * up the code.

Sorry.

---
#### Visual Studio Feedback System on 7/2/2020, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to change these vb experiences.
