### ISSUE TITLE
Incorrect redundant cast notification when comparing with Nothing (VB.NET)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45686]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1098788/incorrect-redundant-cast-notification-when-compari.html)._

---
For example, when I write these things:

```
Dim test = CType(0, Integer?) Is Nothing
```
```
Dim test = CStr(0) Is Nothing
```

I am getting a "IDE0004 Cast is redundant." notification.
Removing the cast results into compilation error.

Version of Visual Studio 2019:
16.6.3

Project type:
Console application using .NET Core 3.1

---
#### Visual Studio Feedback System on 7/2/2020, 07:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to change tehse vb experiences.
