### ISSUE TITLE
Indent guides for "else if" with multi-line conditions are in wrong position

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/642838/indent-guides-for-else-if-with-multi-line-conditio.html)._

---
The dotted vertical lines (indent guides) are usually horizontally aligned with the `else` keyword in an `else if`.
But for multi-line conditions the position is aligned with the `if` keyword instead, which is completely wrong.

---
#### Peter Suter on 7/12/2019, 02:26 AM: 

![image](https://user-images.githubusercontent.com/1408396/86617280-dc7ff280-bf6b-11ea-825c-e6ca4fc62bc4.png)

#### Visual Studio Feedback System on 7/15/2019, 00:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/15/2019, 11:56 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### acreveling on 9/5/2019, 08:34 AM: 

<p>I included a screenshot of a js example.</p>

#### Tim Johnson on 9/12/2019, 08:26 PM: 

Issue occurs editing C# code as well.
#### Visual Studio Feedback System on 10/8/2019, 02:21 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Peter Suter on 10/8/2019, 02:36 AM: 

<p>Visual Studio 16.3.2 is still broken.</p>

#### VladisS Pestrikoff on 2/20/2020, 00:36 PM: 

dotted lines do not appear for if-else blocks. Under some &quot;angle&quot; they are visible.
#### VladisS Pestrikoff on 2/20/2020, 00:37 PM: 

c# 16.4.5
#### VladisS Pestrikoff on 2/20/2020, 00:47 PM: 

<p>for me it was wrong #reg position.<br>Its okay.</p>

#### Maryer Ma [MSFT] on 6/23/2020, 11:48 PM: 

<p>Thank you for your feedback! </p><p>we tried it on latest version 16.6.2 but unable to reproduce the “The dotted vertical lines are not aligned with the ‘else keyword’ in an ‘else if’”.  Could you please update to the latest version then check whether the issue reproduce? </p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/143172-white-space.png" style="width: 540px;"></p><p>If your issue still persists, in order to investigate your issue further, can you help to confirm several questions?</p>
<ol>
<li>Can you try to reset all VS settings or repair your VS and then check whether your problem also reproduces or not? (Navigate to Tools-&gt; Import and Export Settings, then select ‘Reset all settings’)</li>
<li>Can you try to create a new simple solution(C# Console App or C++ Console App) and check if your problem also reproduces?</li>
<li>Can you please provide us your vssetting file? (Navigate to Tools-&gt; Import and Export Settings, then select ‘Export selected environment settings’)</li>
</ol>
<p>Please feel free to let us know if you have any doubt. We look forward to hearing from you!</p>

#### peter on 6/24/2020, 01:50 AM: 

<p>Thanks for looking into it.</p><p>Yes, the issue still persists in the latest VS 16.6.2 in a new C# console app.
</p><p>Please  note that the code layout in your screenshot does not match the code  layout where the problem occurs.<br>The problem occurs only when the  if-expression is broken over multiple lines. </p><p>Please add a newline to reproduce the problem. Thanks.</p>

#### Visual Studio Feedback System on 6/27/2020, 07:49 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Maryer Ma [MSFT] on 6/27/2020, 08:31 PM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/233962/VladisSPestrikoff.html">VladisS Pestrikoff</a></p>
<p>Thank you for sharing your feedback! Based on your description so far , It’s not belong to this feedback. Could you create new one feedback to track the issue “dotted lines do not appear for if-else blocks. Under some “angle” they are visible.”?  And in order to investigate your issue further, can you please provide more info with your issue in the new feedback ( Detail repro steps , simple demo project or a repro video)?  We look forward to hearing from you! Thank you!</p>

#### Maryer Ma [MSFT] on 6/28/2020, 00:41 AM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/127172/peter.html">peter</a><br>
Thanks for your feedback! We appreciate you taking the time to report this problem. We have reported a bug to our engineer and they will investigate this issue. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it. Thank you for helping us build a better Visual Studio!</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I need some guidance on this.

I think the following is the part responsible for calculating the span of the dotted line?

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/CSharp/Portable/Structure/Providers/BlockSyntaxStructureProvider.cs#L80-L85

but here, the start is always going to be on the "if". Does this span gets updated somewhere?

**Comment by Youssef1313** [comment]
Also related to https://github.com/dotnet/roslyn/issues/30300
