### ISSUE TITLE
Using `.WithProjectName()` only followed by `MSBuildWorkspace.TryApplyChanges(newSolution)` does not update `Workspace.CurrentSolution`

### ISSUE THREAD

**Issue by kassemsandarusi** [dotnet/roslyn#45710]
**Version Used**: Microsoft.CodeAnalysis.Workspaces Version 3.6.0

**Steps to Reproduce**:

1. LoadSolution via `var solution = workspace.OpenSolutionAsync()`
2. Get any project id via `var projectId = solution.ProjectIds.First();`
3. Change project name via `var newSolution = solution.WithProjectName(projectId, "TestChangePleaseIgnore")`
4. Apply changes `workspace.TryApplyChanges(newSolution)`

**Expected Behavior**:

1. The newly created solution should have a changed project name.
1. The Workspace object's current solution should be set to the new solution.

**Actual Behavior**:

1. The newly created solution correctly has a changed project name. ✔️ 
1. The Workspace object's current solution is **NOT** set to the new solution. ❌ 

Side Note:

I get that MSBuildWorkspace does not support persisting solution file changes, but at the very least shouldn't the Workspace object update.

**Comment by sharwell** [comment]
The first step here is figuring out two things:

1. Is `TryApplyChanges` returning true or false?
2. What is the root cause for why the behavior (2) is occuring?

**Comment by kassemsandarusi** [comment]
@sharwell  It's returning true. But it's worth noting the apply changes code will return true if no changes need to be made. I debugged through and:

1. The BranchIds are different for the old solution and new solution, so its not short-circuiting and returning true near there. There are a non-zero amount of ProjectChanges as well.

**Comment by kassemsandarusi** [comment]
@sharwell So looking a little further I _think_ I see the issue. Basically `OnProjectNameChanged` is the event that likely needs to be called for the base `Workspace` item to be updated. It doesn't seem like that is invoked anywhere. In the `TestWorkspace` class I see it being referenced in `ApplyProjectChanges`. It's not in the corresponding `MSBuildWorkspace`.

So:

1. MSBuildWorkspace.ApplyProjectChanges is not invoking the underlying events.
2. What's the reason for delegating the responsibility of invoking this event to the children of `Workspace` as opposed to `Workspace` itself invoking it.?

**Comment by kassemsandarusi** [comment]
Perhaps updating the `ApplyProjectChanges` of the `Workspace` class to have a code block like:

```
csharp

protected virtual void ApplyProjectChanges(ProjectChanges projectChanges)
...
if (projectChanges.OldProject.Name != projectChanges.NewProject.Name) {
  this.ApplyProjectNameChanged(oldProject.Id, newProject.Name); // this doesn't exist yet.
}
...

protected virtual void ApplyProjectNameChange(ProjectId projectId, string name) {
  this.OnProjectNameChanged(projectId, name);

```

**Comment by kassemsandarusi** [comment]
I noticed that there's quite a few potential changes that aren't really captured.

- ProjectName
- ProjectFilePath (this one is interesting, it seems coupled to ProjectName)
- AssemblyName
- OutputFilePath
- OutputRefFilePath
- DefaultNamespace

Additionally, it seems like none of those are really supported in the `ApplyChangesKind`.

**Comment by kassemsandarusi** [comment]
Okay, I created a little sample PR that does the suggested change. The test I made works, let me make sure without the change the test works.

**Comment by kassemsandarusi** [comment]
Updated the PR with notes

**Comment by kassemsandarusi** [comment]
@jasonmalinowski is there a reason #37755 stalled out, besides inactivity from the external contributor? That PR looks very similar in spirit to this PR.

**Comment by jasonmalinowski** [comment]
Actually I think that's stalled on me. It probably makes sense though to start building off of that and just update it additionally for project rename, and then we'd take both at once?

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement on https://github.com/dotnet/roslyn/pull/46021.
