### ISSUE TITLE
Do not trim trivia in Code fix IDE0059 "Remove unnecessary assignment"

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#45711]
Issue reported as part of: https://github.com/dotnet/roslyn/issues/45421

Trailing comments are deleted with IDE0059 "Remove unnecessary assignment".

**Comment by CyrusNajmabadi** [comment]
Adding 'help wanted'.  This would be a nice and simple issue for someone interested in roslyn to get started with.

**Comment by BrianFreemanAtlanta** [comment]
I will take a look at this and see what I can come up with.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
