### ISSUE TITLE
Intellisense Suggestion / Autocomplete preferences are not retained by the editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45725]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1095026/intellisense-suggestion-autocomplete-preferences-a.html)._

---
The option **Edit** | **Intellisense** | **Toggle Completion Mode** toggles Intellisense between auto-completion mode and suggestion mode.

Visual Studio defaults to auto-completion mode. In this mode if you type the name of a function that you are about to write, and that function happens to have a similar name to a function that already exists, then the editor replaces the name of the function you typed with the name of the similar function. This behaviour introduces bugs into your code, it makes assumptions about the order in which you write functions that are unsafe. Because this issue has bitten me in the past I always disable auto-completion, but I keep finding that auto-complete keeps getting switched back on.

I eventually realised that it wasn't because I was accidentally pressing CTRL+ALT+SPACE to toggle the mode - rather that the setting to turn auto-complete off does not survive a shutdown of Visual Studio. It does not save the setting, it always switches auto-complete mode back on when you restart Visual Studio.

Other settings in the **Edit** menu are retained over restarts of the editor - for example, visible whitespace and line numbers. I think that the toggle between Intellisense's auto-complete and suggestion modes should also be preserved, the user's preferences should be honoured and not ignored.

I tried to add a screen recording but the recording did not capture the autocomplete. To reproduce create a new C# .Net Framework client libary project and paste this class:

```
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public void AddManyPrefixes()
        {
            ;
        }

public void AddOne()
        {
            // Type here

}
    }
}
```
In AddOne() type the line:
```
AddPrefix();
```
The editor will change it to ```AddManyPrefixes()```. If I didn't notice then it would be calling the existing function and not the new function I'm about to write.

Now either press CTRL+ALT+SPACE or toggle completion mode via the menu, erase the line you entered and type it again. This time the editor accepts what you typed without alteration.

Delete the line you entered and restart Visual Studio. Note that the icon on the toolbar indicating that suggestion mode has been enabled is not lit. Note also that when you reload the class above and type ```AddPrefix()``` the editor replaces the text you entered with the text ```AddManyPrefixes()```.

---
#### Visual Studio Feedback System on 6/29/2020, 11:36 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Moving this one back to the internal editor team.

**Comment by AmadeusW** [comment]
In Visual Studio 16.9, go to Tools, Options, Text Editor, Advanced and set Default IntelliSense completion mode to "Last used"
![image](https://user-images.githubusercontent.com/1673956/108782713-f2edb500-7520-11eb-9ab1-4088c7059573.png)
This will preserve the last setting you choose with Ctrl+Alt+Space.
You can also set it to "Tab only" so that VS always boots such that `AddPrefix` will not get replaced with `AddManyPrefixes`
