### ISSUE TITLE
Make code action ordering logic uniform between local and LSP experiences

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#45726]
See https://github.com/dotnet/roslyn/pull/45572#discussion_r450050296

Extract out the code action ordering logic in SuggestedActionSource to one location, and have it used in both the local and LSP experiences.

**Comment by CyrusNajmabadi** [comment]
Note: this is important that we do.  We have hte concept of things like action priority.  If we do not do this, low pri stuff will show up improperly above high pri stuff.  Simialrly, we have refactorigns (like rename) that show up above fixes.  We need to preserve that.

**Comment by vatsalyaagrawal** [comment]
@allisonchou  please set appropriate milestone for this one.

**Comment by allisonchou** [comment]
Fixed by #46082.
