### ISSUE TITLE
Convert string to int automatically

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45737]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1100243/konwertowanie-strong-na-int-automatycznie.html)._

---
<p>I would like Visual Studio to convert string to int and vice versa automatically</p><p>e.g. I have a &quot;label&quot; and wants to change its text to int in the code and in each &quot;method&quot; shows me an error although all the code is correct. That's why I want Visual Studio to do this automatically (C#)</p><p></p><p></p>

---
#### Visual Studio Feedback System on 7/2/2020, 10:37 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Language requests need to happen at dotnet/csharplang.  Closing out.  Will also say that there is practically no chance that C# would ever adopt a system that enables automatic coercion between strings and ints.  It's very much against the philosophy of the language here.
