### ISSUE TITLE
Allow a positional record to inherit another positional record?

### ISSUE THREAD

**Issue by AlseinX** [dotnet/roslyn#45748]
```csharp
record Foo(int a);
record Bar(int a, int b) : Foo(a);
```
In the current preview version of C# 9.0, it causes error CS1729.
But I do believe this code making sense.
the `a` in `Bar` should be a `new` member that hides the `a` in `Foo`

**Comment by RikkiGibson** [comment]
I can't reproduce this in VS 16.7 Preview 3.1. I also have [.NET 5 SDK Preview 6](https://dotnet.microsoft.com/download/dotnet/5.0) installed which could be affecting behavior at least during the build.

**Comment by AlseinX** [comment]
I tried building it with dotnet cli and it works properly.
It was omnisharp on vscode that gave incorrect analysis.
