### ISSUE TITLE
Compiler warning CS8618: How can I get around it.

### ISSUE THREAD

**Issue by FStapenhorst** [dotnet/roslyn#45745]
**Net Standard 2.1**: 

**Steps to Reproduce**:
See following code:
```
public class Class1
{
  public string MyProperty { get; set; }
  public string MyProperty2 { get; set; }
  public string MyProperty3 { get; set; }

  public Class1() //Warning CS8618
  {
    Init();
  }

  public Class1(string myproperty2) //Warning CS8618
  {
    Init();
    MyProperty2 = myproperty2;
  }

  private void Init()
  {
    MyProperty = "";
    MyProperty2 = "";
    MyProperty3 = "";
  }
}
```

Is there a way to tell the compiler that the Init() function takes care of initializing the properties?

**Comment by RikkiGibson** [comment]
In your scenario you may consider applying `[MemberNotNull(nameof(MyProperty), nameof(MyProperty2), nameof(MyProperty3)]` to your `Init()` method.

**Comment by FStapenhorst** [comment]
Thank you!

I did this:
```
[MemberNotNull(nameof(MyProperty), nameof(MyProperty2), nameof(MyProperty3))]       
private void Init()
{   
  MyProperty = "";
  MyProperty2 = "";
  MyProperty3 = "";
}
```
But nor I get error CS0246 - it doesn't recognize the MemberNotNull attribute. Do I need any additional reference?

**Comment by RikkiGibson** [comment]
The attribute seems to be only present in .NET 5, and requires `<LangVersion>preview</LangVersion>`. It will be part of C# 9 once that officially ships.

You can declare the attribute internally in your project (not officially supported):

```cs
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = true)]
    internal sealed class MemberNotNullAttribute : Attribute
    {
        public MemberNotNullAttribute(params string[] members) { }
        public MemberNotNullAttribute(string member) { }
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, AllowMultiple = true)]
    internal sealed class MemberNotNullWhenAttribute : Attribute
    {
        public MemberNotNullWhenAttribute(bool when, params string[] members) { }
        public MemberNotNullWhenAttribute(bool when, string member) { }
    }
}
```

You can also use`= null!` initializers on your properties instead, which are expected to be elided in codegen in Release mode. This has the effect of just suppressing the CS8618 (uninitialized non-nullable member) warnings.

```cs
public class Class1
{
  public string MyProperty { get; set; } = null!;
  public string MyProperty2 { get; set; } = null!;
  public string MyProperty3 { get; set; } = null!;
}
```

**Comment by FStapenhorst** [comment]
I installed .NET Runtime 5.0.0-preview.6.20305.6 and added the following in my csproj file:
```
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
```
But still 
`[MemberNotNull(nameof(MyProperty), nameof(MyProperty2), nameof(MyProperty3))] `
is unknown.
Maybe it is not yet in the latest preview.
I'll stick with `= null!;` for now

**Comment by RikkiGibson** [comment]
Closing out since the question appears to have been addressed. Feel free to follow up here if needed. Thanks!
