### ISSUE TITLE
IDE0060 incorrectly reported for the GetInstance method of ICustomMarshaler implementation

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#45743]
**Version Used**: 

**Steps to Reproduce**:

1. Implement a custom marshaler (`ICustomMarshaler`)
2. Define the [`GetInstance` method](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.icustommarshaler?view=netcore-3.1#implementing-the-getinstance-method) of the custom marshaler, but don't use the string parameter

**Expected Behavior**:

IDE0060 is not reported.

**Actual Behavior**:

IDE0060 is reported, saying the required parameter can be removed.

**Comment by Youssef1313** [comment]
Opened an analyzer suggestion to warn for missing/incorrect GetInstance method.
