### ISSUE TITLE
Parsing bug in recursive patterns

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#45757]
When parsing
```csharp
class Program
{
    public D P1 { get; set; }
    void M()
    {
        _ = this is Program { P1: (1,  }
    }
}
class D
{
    public int P2 { get; set; }
}
```
the parser drops some tokens; we end up with
```csharp
class Program
{
    public D P1 { get; set; }
    void M()
    {
        _ = this is Program { P1: (1}
    }
}
class D
{
    public int P2 { get; set; }
}
```
(note hte missing comma/space after `(1`) which can cause an assertion error.

The test `PropertiesInRecursivePattern_PositionalInFirstProperty_AfterComma` is skipped because of this.

**Comment by CyrusNajmabadi** [comment]
Also crashing with something similar in: PositionalPatternSecondPosition.  There, the code is:

```c#
using System;


class C
{
  void F()
  {
    i is (1,   }
}
```

So very likely crashing for the same reason.
