### ISSUE TITLE
EnC not working with auto-generated assembly version; is a bit perplexing

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#4575]
This bug report was first made on a forum (registration required): http://forums.somethingawful.com/showthread.php?threadid=3644791&pagenumber=92#post448956284

REPRO:

1. Start with a bog-standard ASP.NET Web Form (derived from a base class that ultimately derives from Page), with some business object members:
![pic1](https://cloud.githubusercontent.com/assets/3316258/9289308/40d1c326-4320-11e5-925f-f923f337ee60.png)

2. Then EnC the Page_Load method, for example I added a `dummy if (true) { }` below there. The method is barely 20 lines long and contains nothing fancy; no LINQ or lambda expressions or anything.  Boom, all the member fields are broken now and you will get NullRef exceptions when trying to access them. Looking at them in Watch reveals a really strange error:
![pic2](http://i.imgur.com/FTP6jZF.png)

3. After some further digging it appears the fields have somehow been duplicated during the EnC recompile, quite rightfully confusing both debugger and runtime:
![pic3](http://i.imgur.com/S63BZ7d.png)

The user who reported this bug dug into the matter and wrote this:

*Turns out if you use an auto-generated assembly version number EnC breaks member references to types defined in that assembly.* So here's some minimal repro code for a console project:

```
// Program.cs

using EnCClassLibrary;

namespace EditAndContinueConsoleTest
{
    class Program
    {
        static SomeClass someClass;

        static void Main(string[] args)
        {
            someClass = new SomeClass(); 
            someClass.SomeProperty = 1; // Step until here, EnC below, continue execution --> will throw NullReferenceException

            if (true) { } // EnC this to false (or whatever - specifics don't matter, just trigger EnC)
        }
    }
}
```

And the console app references "EnCClassLibrary" (doesn't matter if via project or assembly reference), which is made up like this:

```
// AssemblyInfo.cs
...
[assembly: AssemblyVersion("1.0.*")]
...
```

```
// SomeClass.cs

namespace EnCClassLibrary
{
    public class SomeClass
    {
        public int SomeProperty { get; set; }

        public SomeClass()
        {

        }
    }
}
```

BUG SUGGESTIONS:

This is very undiscoverable error message. At the least, I'd hope the error message could change to give a purple squiggle with "EnC isn't supported with auto-generated assembly versions". But at best, I'd hope that EnC could always stick to the same assembly version.

**Comment by gafter** [comment]
See #4575 for the related compiler issue.
See #4580 for the related IDE issue.
This bug is for the edit-and-continue issue.

**Comment by ManishJayaswal** [comment]
@tmat moved to 1.2

**Comment by OndrejPetrzilka** [comment]
I have exactly same issue (duplicated fields, null ref exception after EnC), but it's not related to auto-generated version (checked all projects in solution).

It happens only when `<useLegacyJit enabled="1" />`
Should I create separate issue, what info do you need?

**Comment by ManishJayaswal** [comment]
We have had more reports of this issue affecting folks. See internal bugs 155260 and 174050

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/d43d4780d54276738fe970897e4cf1cd1c58059d

**Comment by mavasani** [comment]
@tmat @ManishJayaswal Was this fix made post Update2 - We have quite a few Watson hits for this in Dev14 Update2 and Dev15 Preview.

**Comment by mavasani** [comment]
I have reactivated internal bug 202017, which is showing the Watson hits.

**Comment by ManishJayaswal** [comment]
Yes I thought this was fixed in U2. @tmat ?

**Comment by tmat** [comment]
Yes, it was fixed in U2.

**Comment by mavasani** [comment]
@tmat see VSO bug 202017 - We have Watson reports for this crash in both Dev14 Update2 and Dev15 Preview.
