### ISSUE TITLE
Incorrect suggestion to use discard pattern breaks compilation

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#45768]
**Version Used**: 
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1
VisualStudio.16.Preview/16.7.0-pre.3.1+30223.230
Microsoft .NET Framework
Version 4.8.03752
```

**Steps to Reproduce**:

```cs
static class Program
{
  public static void Main()
  {
    switch ("".Length)
    {
      case var i when "".Length switch { var y => y > 0 }:
      {
        break;
      }
    }
  }
}
```

**Expected Behavior**:
The suggestion to remove the variable `i` doesn't break compilation

**Actual Behavior**:
The code is not compileable after the "fix"
![image](https://user-images.githubusercontent.com/5566206/86851877-63dc7b80-c0bc-11ea-9c7c-9e54c1c2dfb3.png)
```
static class Program
{
  public static void Main()
  {
    switch ("".Length)
    {
      case _ when "".Length switch { var y => y > 0 }:
      {
        break;
      }
    }
  }
}
```
```
Error CS0103: The name '_' does not exist in the current context (12, 12)
```

**Comment by CyrusNajmabadi** [comment]
Interesting.  Is this intentional @gafter?  Are discards not allowed here?

**Comment by gafter** [comment]
Yes, a discard is not allowed as the pattern of a switch statement. There are two reasons. First, there might already be a constant named `_` in scope and we don't want to change the meaning of that. Second, there is already the `default` switch case label for that purpose.

The correct fix to offer here is to replace `var i` with `var _`.

**Comment by CyrusNajmabadi** [comment]
Great, thanks.  Tagging @mavasani .
