### ISSUE TITLE
"Generate class" suggestion should prefer namespaces over classes for multiply-qualified names

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#4577]
Look at this:
<img width="618" alt="namespace-generate" src="https://cloud.githubusercontent.com/assets/3316258/9289437/cf5c6b06-4324-11e5-9664-c0c38503e9b8.png">

I think it's a safe bet that the final part of this qualified name is a class, and everything before it is a namespace. Therefore I want it to suggest to generate "MyClass" in a namespace called "MyCompany.MyProduct.Area". (I don't know what the filename conventions are, but if namespace MyCompany doesn't already exist in the solution, then I'd expect it to go in a folder called "MyCompany" in a file called "MyProduct.Area"...)

I don't like the current behavior where it suggests to generate a class called "MyProduct" (which indeed fails to even fix the squiggle in my code).

**Comment by paul1956** [comment]
This raises a question, is there a way for the refactoring function to view the file system to make sure that the proposed file doesn't already exist and do the checks proposed above to put the new file in the correct place? I need to know where to start looking for the solution before I can use functions in System.IO.

**Comment by Pilchie** [comment]
I'm going to move this to 1.2 based on the discussion in the PR.  Let's make sure it feels right instead of rushing it into 1.1.

**Comment by CyrusNajmabadi** [comment]
Closing out as we're not chnaging these vb experiences.
