### ISSUE TITLE
Null-conditional operator and CS0165

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/roslyn#45776]
I don't understand why I get an error if I use `?.` but not if I use `!= null` in the example below. 

**Version Used**: 

Visual Studio 16.6.3, .NET Core 3.1 Console Application

**Steps to Reproduce**:

```
using System.Collections.Generic;

namespace RoslynTest
{
	class Program
	{
		class SomeClass
		{
			public Dictionary<string, string> SomeProperty { get; } = new Dictionary<string, string>();
		}

		static SomeClass? MyProperty { get; }

		static void Main(string[] args)
		{
			{
				// Doesn:t work
				if (MyProperty?.SomeProperty.TryGetValue("key", out var value) == true)
				{
					//Error CS0165  Use of unassigned local variable 'value'  RoslynTest C:\Users\h165\source\repos\RoslynTest\RoslynTest\Program.cs 21  Active
					value.ToString();
				}


				// Works
				if (MyProperty != null && MyProperty.SomeProperty.TryGetValue("key", out var value2))
				{
					//no error
					value.ToString();
				}
			}
		}
	}
}
```

**Expected Behavior**:

No errors

**Actual Behavior**:

CS0165

**Comment by RikkiGibson** [comment]
This is definite assignment analysis working as specified. Please see https://github.com/dotnet/roslyn/issues/45582#issuecomment-652648965 and consider searching for or filing an issue at https://github.com/dotnet/csharplang if you wish to propose a change to the specification.
