### ISSUE TITLE
Decrease indent incorrect with block comments and * vertical lines

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1104106/decrease-indent-incorrect-with-block-comments-and.html)._

---
[regression]
- Make sure the "Insert * at the start of new lines when writing /* */ comments" setting is on.
- Create an indented block comment with multiple lines.
- The comment is created in this format.  There is a leading space automatically added to the second and third lines so the asterisks line up.
```
[tab]/* First line
[tab] * second line
[tab] */
```
- Select the comment and decrease the line indent.  You'd expect it to remove one tab from each, resulting in this:
```
/* First line
 * second line
 */
```
- Instead it removes the leading space from the second and third lines, resulting in this:
```
/* First line
[tab]* second line
[tab]*/
```
- Under Text Editor > C# > Tabs I have it set to Indenting: Block and Keep Tabs.  Tab Size and Indent Size are both set to 4.  This is under Visual Studio 16.6.3.

---
#### Feedback Bot on 7/7/2020, 01:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you route to editor?

**Comment by olegtk** [comment]
I reactivated https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1152568 and routed it to the editor, feel free to close this issue.

**Comment by CyrusNajmabadi** [comment]
Thanks.  Closing!
