### ISSUE TITLE
Compilation of source with auto-generated version is non-deterministic

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4578]
```C#
[assembly: System.Reflection.AssemblyVersion("1.0.*")]
```

The compiler generates the version based on the current time:

```C#
// src\Compilers\Core\Portable\VersionHelper.cs:
...
            if (hasWildcard)
            {
                int seconds = ((int)(DateTime.Now.TimeOfDay.TotalSeconds)) / 2;
                if (seconds > (int)maxValue)
                {
                    version = null;
                    return false;
                }
                values[3] = (ushort)seconds;

                if (elements.Length == 3)
                {
                    TimeSpan days = DateTime.Today - new DateTime(2000, 1, 1);
...
```

**Comment by tmat** [comment]
@gafter Not sure what we can do about this, other then report an error that it's not supported in deterministic builds.

**Comment by tmat** [comment]
See also #4580. I propose deprecating this feature (auto-generated) version.

**Comment by gafter** [comment]
See also #4575.

**Comment by gafter** [comment]
@tmat Yes, I agree. Probably the way to deprecate it is to produce a warning whenever the feature is used, but continue to support it?

**Comment by gafter** [comment]
Our conclusion is that we want to report a diagnostic (not sure warning or error) when this feature is used along with `/feature:deterministic`.

**Comment by TyOverby** [comment]
The only time we have `allowWildcard: true` is [on line 2076 of SourceAssemblySymbol.cs](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Source/SourceAssemblySymbol.cs,2076).  Would it be sufficient to check right there and see if we are running in "deterministic mode"?

**Comment by gafter** [comment]
@TyOverby I think we want to allow a wildcard but produce a warning in deterministic mode.

**Comment by tmat** [comment]
@gafter Why not just report an error? It's not gonna work as user expects, so to avoid confusion it seems better to report an error.

**Comment by gafter** [comment]
@tmat sounds good to me. So to @TyOverby's question, we could probably just change `allowWildcard: true` to something like `allowWildcard: !deterministicMode`.
