### ISSUE TITLE
Introduce local refactoring generates incorrect code

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#45790]
**Version Used**:  

.NET Core SDK 3.1.301

**Steps to Reproduce**:

This is the code I wanted to refactor to uplift the two array lookups into a temporary variable:

```c#
                if (lineCharacterIndex > 0)
                    lines[verticalOffset + lineIndex] =
                        lines[verticalOffset + lineIndex][..(lineCharacterIndex - 1)] +
                        lines[verticalOffset + lineIndex][lineCharacterIndex--..];
```

**Expected Behavior**:

I expected something similar to the following code to be generated:

```c#
                if (lineCharacterIndex > 0)
                {
                    var line = lines[verticalOffset + lineIndex];
                    lines[verticalOffset + lineIndex] = line[..(lineCharacterIndex - 1)] + line[lineCharacterIndex--..];
                }
```

**Actual Behavior**:

Instead, the generated code was more similar to this (variable name aside):

```c#
                if (lineCharacterIndex > 0)
                {
                    var line = lines[verticalOffset + lineIndex];
                    line = line[..(lineCharacterIndex - 1)] + line[lineCharacterIndex--..];
                }
```

This is incorrect because it no longer updates the initial array, it updates the temporary variable. Uplifting temporary variables shouldn't also uplift setting them.

Actual screenshot of the refactor result:

![image](https://user-images.githubusercontent.com/541998/86950841-b2bafd00-c11e-11ea-9d6c-747fd4fe21c4.png)

**Comment by RikkiGibson** [comment]
It feels like the refactoring could be fixed to produce something like

```cs
ref var line = ref lines[...];
line = ...
```

**Comment by myblindy** [comment]
True, I had forgotten about `ref` variables. I'll use that manually right now, in fact!

**Comment by myblindy** [comment]
Never mind, you can't use `ref` with properties and indexers, and `lines` is a list. That's very disappointing to see.

**Comment by RikkiGibson** [comment]
If the type isn't a built-in like Array, it needs an indexer that returns by-ref a la `Span<T>`: https://docs.microsoft.com/en-us/dotnet/api/system.span-1.item?view=netcore-3.1

**Comment by CyrusNajmabadi** [comment]
The refactoring is working as intended.  You asked to update all potential matches, so we updated all potential matches.  That semantics cahnged here is *expected* as it is almost never possible to introduce a local for an expression without changing semantics in some way (i.e. order of ops changes).  

The IDE behavior here looks appropriate to me.  The only thing i would change is augment it so that if the variable is written, and that variable was an indexer/ref, that you get a warning that semantics may change.

**Comment by myblindy** [comment]
> That semantics cahnged [sic] here is expected

I don't think that is true, this refactoring should never (and does not, with the exception listed above) change the semantics of the code.

> that you get a warning that semantics may change

Personally I'd prefer it to not change setters, but is there precedent for this? I don't think I've seen a refactor option show a warning like you say.

**Comment by CyrusNajmabadi** [comment]
> I don't think that is true, this refactoring should never (and does not, with the exception listed above) change the semantics of the code.

This refactoring almost *always* changes teh semantics of code.  The amount of cases where it does not is *super small*.  It's the minority case in fact.

**Comment by CyrusNajmabadi** [comment]
> Personally I'd prefer it to not change setters, but is there precedent for this? I don't think I've seen a refactor option show a warning like you say.

Yes, there's lots of precedent for this.  As many of our refactorings may change meaning, if we have higher confidence that htat change might be problematic, we warn.  

> Personally I'd prefer it to not change setters

We don't tend to follow such an approach.  Because that just leads to people going "i don't get why this feature isn't offered, something is broken".  We prefer to give people the tools to allow them to make large changes quickly, with teh caveat that additional steps may be required at times.

**Comment by RikkiGibson** [comment]
> The only thing i would change is augment it so that if the variable is written, and that variable was an indexer/ref, that you get a warning that semantics may change.

Sounds good, thanks!

**Comment by myblindy** [comment]
> "i don't get why this feature isn't offered, something is broken"

Well, something is broken right now. Run a simple variable uplift and your code no longer does anything because the assignment disappears into the void.

> This refactoring almost always changes teh [sic] semantics of code. The amount of cases where it does not is super small. It's the minority case in fact.

Could you give me an example of this that's not a pathological case like uplifting a `++` expression? I can't believe the majority of the uses of this specific refactor option changes the semantics of the code without some kind of proof to back it up. 

In fact, since you're defending this feature, could you give me one use case where uplifting a variable for the setter ever makes sense, or is useful? Because no matter how you look at it, where previously the correct setter was called, after this it will no longer be called.

**Comment by CyrusNajmabadi** [comment]
Note: even your 'expected' behavior changes semantics.  i.e.:

```c#
                if (lineCharacterIndex > 0)
                {
                    var line = lines[verticalOffset + lineIndex];
                    lines[verticalOffset + lineIndex] = line[..(lineCharacterIndex - 1)] + line[lineCharacterIndex--..];
                }
```

does not have the same semantics as before.  For example, if indexing into that collection does anything observable, it will now no longer produce the same results as before.

**Comment by CyrusNajmabadi** [comment]
> Well, something is broken right now.

**Comment by myblindy** [comment]
Well, feel free to close this issue if it's working as intended and all you got from this is that I want, and I quote, "manual steps". For the record I very strongly disagree with every single thing you said about this particular refactor option.

**Comment by CyrusNajmabadi** [comment]
> Could you give me an example of this

Yes, trivially:

```c#
Foo(expr1, expr2)
```

If you introduce a local for expr2, you change sematnics because it now executes before expr1.

```c#
Foo(expr1);
Foo(expr1);
```

If you introduce a local for all occurrences of `expr1`, then you change semantics because now the second computation doesn't happen after the first call to `Foo`.


```c#
var v = expr1 + expr1
```

If you introduce a local for all occurences of `expr1` you can change semantics if `expr1` had any observable impact on the system.

**Comment by CyrusNajmabadi** [comment]
> For the record I very strongly disagree with every single thing you said about this particular refactor option.

So you would *not* want us to warn here if semantics may change?  Personally, i'm very amenable to that change to allow users to continue taking advantage of the large speedups that can come from bulk changes, while still making them aware that they may need to more carefully review teh impact of the change.

**Comment by myblindy** [comment]
Those are all pretty big ifs, as opposed to changing assigning to the correct setter being changed to an essential no-op 100% of the time.

**Comment by CyrusNajmabadi** [comment]
> and all you got from this is that I want, and I quote, "manual steps".

I am simply having a discussion taht is explaining the current reasoning and the thought process that goes into making these decisions.  We very well may make the changes that you have asked for.  But that doesn't mean it will be done without thoroughly examining the problem space here.

In this case, i both see the concern on your part, but i also see that some of your perception here stems from a difference in opinion about what is acceptable in one of these tools.  For example, if we strictly took an approach that `this refactoring should never ... change the semantics of the code`.  If we followed that approach, tehn you would find that you wouldn't even be offered the refactoring here *at all*, which i think is not what you would want.

**Comment by CyrusNajmabadi** [comment]
@myblindy As i have stated numerous times at this point: this is why i am open to making a change here.  I am simply explaining the current situation and why it is likely not acceptable to take an approach of "this tool is not allowed to make semantic changes at all"

**Comment by myblindy** [comment]
> If we followed that approach, tehn you would find that you wouldn't even be offered the refactoring here at all, which i think is not what you would want.

I can see the theoretical problem you're trying to work around here, but it is not the case that I wouldn't be offered the refactoring here at all, because my specific use case doesn't do anything observable in its index getter (as most uses of this shouldn't, isn't this one of the cornerstones of .Net?)

There is exactly one semantic change that breaks after running this, and it's related to the setter.

**Comment by CyrusNajmabadi** [comment]
> Those are all pretty big ifs

Those are not big ifs at all.  All teh code changes above do happen in practice, and are trivial to run into.  It's a big if to assume that there will be no semantic changes for all of them.  i.e. that a call to some random method won't end up exactly having an impact on the computations you are performing. 

But we do make those assumptions.  Because, if we didn't, you'd find that the tool was virtually unusable.  Note that this is not a hypothetical.  Very early on when we started with refactorings, we tried teh approach of "no semantic changes allowed", and it turned out we ended up shipping several tools that people could effectively not use *at all*.  i.e. they literally would say "hey... i wanted to use this but it didn't appear".  We'd tehn show how semantics would change, and would always hear back "sure... but i'm ok with that.  i really just want to be able to use the feature, and i'd prefer to have it, with that chance, versus jsut not having it in all these cases."

**Comment by CyrusNajmabadi** [comment]
> because my specific use case doesn't do anything observable in its index getter

There is no way for any part of the system to know that.  Indexers can and do change semantics.

Note: let's use anotehr simple example based off of your code:

```c#
Foo(lines[verticalOffset + lineIndex]);
Bar(lines[verticalOffset + lineIndex]);
```

If a user said "i want to replace *all* occurrences of `lines[verticalOffset + lineIndex]` with a local" then i bet you that 99 out of a hundred users would expect to get:

```c#
var line = lines[verticalOffset + lineIndex];
Foo(line);
Bar(line);
```

But that could certainly change semantics.  And yet, almost all users would be ok with that, and would say: yes... i get it... but in my domain i felt these were semantically independent, so i felt it was ok to bulk change all.

**Comment by RikkiGibson** [comment]
The compiler doesn't assume that the `this[int].get` accessor on `System.Collections.Generic.List<T>` is side-effect-free. It knows nothing about the implementation. We may decide to adjust some assumptions within this refactoring about which semantic changes are more or less likely to cause undesired effects, and conventions about how properties/indexers "typically" work might be part of that.

**Comment by CyrusNajmabadi** [comment]
> There is exactly one semantic change that breaks after running this, and it's related to the setter.

Again, this is why i've said i'm extremely amenable to having this feature warn in this case to make it more apparent that something might be changing.

**Comment by CyrusNajmabadi** [comment]
> It knows nothing about the implementation

**Comment by myblindy** [comment]
Okay, let's try this approach. Can you give me one example where refactoring a setter is useful and intended? Because if you can't come up with one, all this discussion about semantics change in general is pretty moot.

**Comment by CyrusNajmabadi** [comment]
@myblindy Yes.  Taking your example, i say to myself: actually, i don't want to update the list.  I want to perform a set of changes all on this independent variable (hence why i introduced a local for it), and at the *end* i will go and update the list (perhaps by directly setting, perhaps using some other mechanism).

I introduce locals entirely so i can try to operate on the local value instead of the storage value in some other location.  In other words, i refactor this to decouple me from directly setting in place as i do the work.

**Comment by CyrusNajmabadi** [comment]
Note: this is gettign a bit into a free-form discussion.  It can def stay here if you'd like.  But i recommend gitter.im/dotnet/roslyn and discord.gg/csharp (#roslyn) for this style of conversation.  THat way it can be more direct and synchronous, instead of the async nature of github.

**Comment by myblindy** [comment]
> actually, i don't want to update the list

Okay well, I guess my problem here isn't that it's a bug, I just disagree with the initial design of this entire refactoring option. I can't imagine ever using "extract variable" to not update the list I was previously updating, I use it to cache the value instead of repeatedly indexing into an array or calculating an expensive expression.

**Comment by CyrusNajmabadi** [comment]
i get that. :)

**Comment by CyrusNajmabadi** [comment]
@myblindy Would you be interested in contributing the change here?  Marking this up as help-wanted.

**Comment by myblindy** [comment]
Which change specifically?

**Comment by myblindy** [comment]
Debugging through this refactoring, I found this chunk of code:

```c#
                // Even though we're creating a variable, we still ask if we can be replaced with an
                // RValue and not an LValue.  This is because introduction of a local adds a *new* LValue
                // location, and we want to ensure that any writes will still happen to the *original*
                // LValue location.  i.e. if you have: "a[1] = b" then you don't want to change that to
                // "var c = a[1]; c = b", as that write is no longer happening into the right LValue.
                //
                // In essence, this says "i can be replaced with an expression as long as I'm not being
                // written to".
```

It sounds like more and more of a bug to me that it refactors the code as it does.

**Comment by CyrusNajmabadi** [comment]
See: https://github.com/dotnet/roslyn/issues/45790#issuecomment-655703811

**Comment by dibarbet** [comment]
Design meeting notes
We'll accept the PR for this issue once it's approved.
