### ISSUE TITLE
Generate constructor from field misses 'unsafe' if it's a pointer type

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#45808]
Write the two fields in the first part of this screenshot, select them and invoke to generate the constructor below:

![image](https://user-images.githubusercontent.com/201340/86976340-12b99f80-c12f-11ea-81df-5520d102b2ac.png)

This should mark the constructor 'unsafe' if the class itself is not unsafe.

**Comment by CyrusNajmabadi** [comment]
That's odd.   We have the RequiresUnsafeModifierVisitor for this purpose.  And it was updated to understand function pointers.  Must have forgotten to call that for gen-constructor.

**Comment by jasonmalinowski** [comment]
A quick glance is yes, we didn't call it in the generate constructor path.
