### ISSUE TITLE
Projects with auto-generated assembly version numbers have unstable assembly identity

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4580]
Currently the compiler produces assembly symbols with non-deterministic version number if a wildcard * is used in AssemblyVersion attribute, e.g. ```[AssemblyVersion("1.0.*")]``` every time a source assembly symbol is created for the compilation. The current time is used to generate the version. 

For example, as the user types in the IDE new assembly symbols are created with new version numbers. This causes issues with EnC and potentially other components that consume assembly identity of such assembly symbols (see #4575).

**Comment by gafter** [comment]
Since #4575 already reports the compiler issue, I am untagging Area-Compilers from this issue.

**Comment by Pilchie** [comment]
What else do you propose the *compiler* should do (since the IDE does no processing of this attribute)?

Also, is there a specific issue that this results in?

**Comment by tmat** [comment]
#4575

**Comment by tmat** [comment]
At least the generated version can be passed from one compilation to another when created thru With* methods. The IDE can reset it every time the user builds. The version can also be passed as a parameter to command line compiler so that the result of the build is consistent with IDE. Not syaing that all this has to be implemented. Just throwing some ideas out there.

**Comment by tmat** [comment]
@Pilchie Also we should author FxCop rule saying that this is features is obsolete.

**Comment by Pilchie** [comment]
What is the user impact of not changing any of this, given that this has not been the default since VS2003?

**Comment by tmat** [comment]
@Pilchie A few reasons: In future we want to use deterministic compilation to speed up builds. This feature explicitly prevents that. So we should guide users to stop using it.

Previously we haven't exposed compilation APIs. I find the following behavior odd:
```
var c1 = Compilation.Create(... "[AssemblyVersion(*)]" ...);
var id1 = c1.AssemblyIdentity;

Thread.Sleep(random time);

c2 = c1.WithReference(...);
var id2 = c2.AssemblyIdentity;

id1 != id2 or id1 == id2 depending on the sleep time
```

**Comment by Pilchie** [comment]
Static analysis needs to be a separate bug to the IDE.

For the IDE, there is no way to do this through the API at the moment.

**Comment by Pilchie** [comment]
I still haven't seen any evidence that a sufficient number of people use this to warrant doing anything here.

**Comment by tmat** [comment]
At least we should remove the comment from default AssemblyInfo.cs template:

```
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
```

**Comment by tmat** [comment]
https://github.com/search?l=csharp&p=2&q=AssemblyVersion&ref=searchresults&type=Code&utf8=%E2%9C%93

If you go thru the results * is actually used in many cases :(

**Comment by gafter** [comment]
Why don't we just turn `*` into `42`? That is deterministic, and random, too!

**Comment by tmat** [comment]
@gafter I think all they care is that 2 subsequent builds produce different versions.

**Comment by tmat** [comment]
... and they are "lucky" our compiler doesn't build their project in sub-second time.

**Comment by gafter** [comment]
@tmat We don't have a "ensure the compiler is nondeterministic" flag.

**Comment by paul1956** [comment]
I have been following this discussing and need to comment. Until someone explains a better way to update version numbers for the main application, I use this feature for all the apps I write. It removed the possibility that I forgot to update the version before releasing to beta customers. I have seen other apps use T4 templates to do this but information on how to update version numbers before release is very confusing and overly complicated compared to

[assembly: AssemblyVersion("1.0.*"), unfortunately as far as I can tell this does not work to update the manifest in VSIX projects.

**Comment by tmat** [comment]
@paul1956 Would this help you https://github.com/dotnet/roslyn/issues/636 ?

**Comment by paul1956** [comment]
I don't see how, changing it on some command line I don't know how to get and won't remember to anyway to, doesn't seem to help. I simply want the version to change every time one of the files in the build changes. If nothing changes the version shouldn't change. I have no need for time stamping, I would love 1.1.1, 1.1.2. 1.1.3. and I will control the first two digits. When I programed for a living (in the pre-PC age) the source control system did the auto incrementing, for a while it was manual they I found // [assembly: AssemblyVersion("1.0.*")] and have been using it for a few year. The difficulty is when I rebuild the version changes, so it is difficult t know if my users have the same version I do.

**Comment by gafter** [comment]
Perhaps we could deal with the version number the same way we deal with the GUID and timestamp in deterministic mode - make it depend on a hash of the (rest of the) contents of the generated assembly.

**Comment by tmat** [comment]
@paul1956 Paul, do you need specifically the version to be changed every build or do you just need to get some kind of ID from the DLL/EXE that changes if there were any changes in the source? Suppose that you could retrieve such ID from the file and you could also trace back to the original source in source control. Would that address your scenario?

@gafter We can't. The assembly identity has to be known upfront - it's part of symbol info: AssemblySymbol.AssemblyIdentity. We don't want to emit the assembly just to find out its identity. It would also be desirable for the version to be increasing.

**Comment by paul1956** [comment]
I just want to be able to do this
        Dim versionInfo As Version = Assembly.GetExecutingAssembly().GetName().Version
        Version.Text = versionInfo.ToString()
On the splash and about screens, without manually editing and I would prefer it to NOT change when the source doesn't change.

**Comment by tmat** [comment]
@paul1956 I'm curious though why does it need to be the version? What if the version didn't change (unless you update the major or minor, the build and revision would be 0 always) but you had other ID (GUID) that would change only if the sources changed?

**Comment by paul1956** [comment]
Users are familiar with version, when I release a new version I do manually update the major or minor version, but people testing might to using an internal version where I rely on the additional digits. I deploy through the Azure cloud and users can pick up internal or only stable/released versions so I count on the version changing when the source changes and then they report an issue I want to be able to know what they are running without asking for a GUID that would have to be accessible to them. Do an About on Visual Studio 2015 and you see a variety of different versioning schemes for the various components, it would be nice to support one of them by default, Azure and Office Tools, possibly others seem to use the current one.

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079
Architecture and Modeling Tools   00322-80000-00000-AA013
LightSwitch for Visual Studio 2015   00322-80000-00000-AA013
Visual Basic 2015   00322-80000-00000-AA013
Visual C# 2015   00322-80000-00000-AA013
Visual C++ 2015   00322-80000-00000-AA013
Visual F# 2015 RC   00322-80000-00000-AA013
Microsoft Visual F# 2015 RC
Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA013
Application Insights Tools for Visual Studio Package   1.0
ASP.NET and Web Tools   14.0.20711.0
ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
Common Azure Tools   1.5
GenerateUnitTest   1.0
GitHub.VisualStudio   1.0
Microsoft Azure HDInsight HQL Service   2.0.2200.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.2200.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30728.1602
Microsoft Code Digger   0.9
Microsoft.Pex.VisualStudio   1.0
NuGet Package Manager   3.0.0
Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
PreEmptive Analytics Visualizer   1.2
SQL Server Data Tools   14.0.50730.0
Syntax Visualizer   1.0
VisualStudio Tools for Universal Windows Apps   14.0.23121.00 D14OOB
Workflow Manager Tools 1.0   1.0

**Comment by 0x53A** [comment]
I think the assembly version being unstable if you use * is an explicit goal and not an unwanted side-effect of many.

Some other parts of commonly-used build-chains depend on
1) The assembly version number changing each build, and
2) Later versions having a higher number.

For example, in many cases the version of the setup (MSI) is extracted from the assembly version. If the version does no longer change, it would not be recognized as an upgrade. Should the version be lower, it would be detected as an downgrade, and probably disabled.

Also, if you look around the internet, many sources depend on the exact scheme used, they extract the assembly version and back-calculate the build-time.

I'm just a random person on the internet, but I would propose to keep the current behavior for the x.* schema.

Don't get me wrong, I actually see the benefit in this whole determinism project, I just think that changing the current behavior would break a lot of current projects.

If a user wants a fixed version number, they can either hard-code it (remove the *) or remove it and use the new proposed command-line parameter.

**Comment by tmat** [comment]
@x53A Thanks for your feedback. I assumed that the properties 1) and 2) are crucial. I wasn't aware of tools that reverse-engineer the time stamp from the build number. That's very brittle.

We certainly don't want to break existing scenarios that are important to our customers. Considering this feature "obsolete" would not mean it's going away any time soon. It would mean new features (like deterministic build) might not be compatible with it. The deterministic build specifically is by definition not compatible with auto-generated versions.

**Comment by KirillOsenkov** [comment]
Could we generate a version that is a SHA hash?

**Comment by tmat** [comment]
@KirillOsenkov No. It's not increasing. Also it would likely affect perf.

**Comment by davidroth** [comment]
Just wanted to add that auto-generated assembly version numbers are required by the winforms designer to work properly when using custom IExtenderProvider`s.

If you do not use auto generated assembly versions, properties from custom IExtenderProviders are lost after recompilation of the project/solution (random).

There was a connect issue describing the issue, but unfortunately the link is down now:
https://connect.microsoft.com/VisualStudio/feedback/details/322887/vs2008-forms-designer-does-not-load-iextenderprovider-properties-after-a-build

**Comment by Pilchie** [comment]
@tmat - I still haven't heard what is broken in the IDE, and what you'd like to propose to do to fix it.
