### ISSUE TITLE
Invalid initializer member declarator

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#4581]
I'm not quite sure if this was a valid syntax in the previous compiler, but I think I had used this syntax already in the past.

The question is if it was even in the previous compiler not allowed, why?
In the current Visual Studio 2015 compiler it is not valid!

```csharp
public class Program
{
    public void Main(string[] args)
    {
        var collection = new MyCollection
        {
            MyProperty = "42",

            / / does not compile!!! ("Invalid initializer member declarator")
            new MyItem
            {
                MyProperty = 42
            }
        };
    }
}

public class MyCollection
    : IEnumerable<MyItem>
{
    public String MyProperty { get; set; }

    public void Add(MyItem @myItem)
    {
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator<MyItem> IEnumerable<MyItem>.GetEnumerator()
    {
        throw new NotImplementedException();
    }
}

public class MyItem
{
    public int MyProperty { get; set; }
}
```

**Comment by svick** [comment]
I don't think it was ever allowed. If you look at §7.6.10 *The new operator* of the C# 5 spec, the grammar is:

<dl>
<dt>object-creation-expression:</dt>
<dd><code>new</code>   <em>type</em>   <code>(</code>   <em>argument-list</em><sub>opt</sub>   <code>)</code>   <em>object-or-collection-initializer</em><sub>opt</sub> </dd>
<dd><code>new</code>   <em>type</em>   <em>object-or-collection-initializer</em></dd>
<dt>object-or-collection-initializer:</dt>
<dd><em>object-initializer</em></dd>
<dd><em>collection-initializer</em></dd>
</dl>

So you can use object initializer *or* collection initializer, but not both at the same time.

If I were to guess why, I think it's because collections with settable properties are not common. Do you have a specific use case where this pattern makes sense?

**Comment by biqas** [comment]
@svick 
Maybe the example was misleading, because I choose the name "MyCollection". Here the same example but modified. (I also looked up if I had used something similar in the past, and the case was I ended up to write for each relevant property a collection initializer and to distinguish them a wrapper class.)

```csharp
public class Program
{
    public void Main(string[] args)
    {
		var entityA = new EntityA
		{
			MyProperty = "42",

            new EntityB
			{
				MyProperty = 42
			},

			new EntityB
			{
				MyProperty = 1
			}
		};
    }
}

public class EntityA
	: IEnumerable<EntityB>
{
	public String MyProperty { get; set; }

	private IList<EntityB> _EntityBRelations = new List<EntityB>();

	public IEnumerable<EntityB> EntityBRelations
	{
		get { return this._EntityBRelations; }
	}

	public void Add(EntityB @myItem)
	{
		this._EntityBRelations.Add(@myItem);
    }

	IEnumerator IEnumerable.GetEnumerator()
	{
		throw new NotImplementedException();
	}

	IEnumerator<EntityB> IEnumerable<EntityB>.GetEnumerator()
	{
		throw new NotImplementedException();
	}
}

public class EntityB
{
	public int MyProperty { get; set; }
}
```

**Comment by svick** [comment]
I think that example is still way too generic. Your code is still just a type that's both a collection and an entity, but it doesn't say anything about *why* would you want to design it that way (instead of the more common design of entity that contains a collection, not being a collection itself).

 Could you give a specific example where you would use this? (Without any placeholders like `MyEntity` or `EntityA`).

**Comment by biqas** [comment]
@svick 

If this is helping you to answer the where question: EnityA => Person EntityB = Address.

```csharp
public class Program
{
    public void Main(string[] args)
    {
		var person = new Person
		{
			Name = "Alice",

            new Address
			{
				Street = "Some street",
				City   = "Some city"
			},

			new Address
			{
				Street = "Some other street",
				City   = "Some other city"
			}
		};

			// Of course it is only syntactic sugar,
			// but I can not see any reason why the above should not be possible or limited
			// only to object initializer or collection initializer?!
		person = new Person
		{
			Name = "Alice"
		};

		person.Add(
			new Address
			{
				Street = "Some street",
				City   = "Some city"
			});

		person.Add(
			new Address
			{
				Street = "Some other street",
				City   = "Some other city"
			});
		}
}

public class Person
	: IEnumerable<Address>
{
	public String Name { get; set; }

	private IList<Address> _Addresses = new List<Address>();

	public IEnumerable<Address> Addresses
		{
		get { return this._Addresses; }
	}

	public void Add(Address @myItem)
	{
		this._Addresses.Add(@myItem);
    }
}

public class Address
{
	public String Street { get; set; }

	public String City { get; set; }
}
```

The why question is it does not feel currently uniformed from a data flow perspective.
You wanted to create an instance and have all data given, but the creation process feels disconnected if you have to use in such cases method chaining afterwards to create full initialized instance.

```csharp
person = new Person
{
	Name = "Alice"
};

person.Add(
	new Address
	{
		Street = "Some street",
		City   = "Some city"
	});

person.Add(
	new Address
	{
		Street = "Some other street",
		City   = "Some other city"
	});
```

**Comment by svick** [comment]
That's exactly why I asked for a specific example: I don't think a person should be a collection of addresses. That's not a good design, and I don't see any reason for adding language features that only support bad design.

**Comment by biqas** [comment]
Please first explain what you mean with bad design? And it has nothing to do with supporting design features which should backed into language!

**Comment by svick** [comment]
You're modeling the real world, and in the real world, it's not that person *is* a collection of addresses, instead, person *has* a collection of addresses. For example `foreach (var address in person)` doesn't make much sense to me, but `foreach(var address in person.Addresses)` feels completely natural to me.

Other points are about possible changes to the code: If a person also has a collection of phone numbers, will it also implement `IEnumerable<PhoneNumber>`? What if you want to separate postal addresses and billing addresses? You can't implement the same interface twice.

Okay, those are some drawbacks. What are the advantages? Err, I don't see any (maybe you do?). Thus I conclude that it's a bad design.

And if you want a feature included included in the language, you need to make a strong case for it, saying that it should be included is not enough.

**Comment by biqas** [comment]
@svick 
After considering lot of code what I have written in the past and how the language (C#) is designed I'm now also convinced that mixing both (object-initializer and collection-initializer) wouldn't be a good idea.
