### ISSUE TITLE
Add "make anonymous function static" code fix

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#45832]
Related to #39606 

We currently have a "make local function static" code fix which works by analyzing data flow in the local function and simply proposing to add a 'static' modifier if nothing is captured. It seems reasonable to do the same thing for static lambdas and anonymous methods.

```cs
M($$x => x + 1); // before
M(static x => x + 1); // after

M($$delegate (int x) { return x + 1; }); // before
M(static delegate (int x) { return x + 1; }); // after
```

**Comment by CyrusNajmabadi** [comment]
Yes.  though this would def be off by default.  It would be incredibly noisy otherwise, and would do a disservice to lambdas (which really want to be brief most of hte time).  Some users may want this, but we would want them to opt-into this.
