### ISSUE TITLE
Harden ObjectReader/ObjectWriter against invalid data

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#45839]
Currently various exceptions (e.g. ArgumentOutOfRangeException, InvalidOperationException, etc.) might be thrown when the reader encounters bad data or the writer encounters data it can't serialize.

Instead, a specific exception (e.g. `InvalidDataException`) should be uniformly thrown in all cases.

**Comment by CyrusNajmabadi** [comment]
I don't actually see any exceptions here (except for unreachable blocks).  Closing out for now.
