### ISSUE TITLE
Performance issue on disposing a solution in VSMac

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#45833]
**Version Used**: 
3.7.0-4.20351.7

**Steps to Reproduce**:

1. Open a big solution and start profiling
2. Close the solution
3. Stop profiling

**Expected Behavior**:
Closing should be near instant

**Actual Behavior**:
The IDE hangs for a few seconds.

Perf trace:
https://gist.github.com/Therzok/2dc2d6eaeb91ab98fe360d65a411869b

Seems like we have two really heavy calls done here, `Microsoft.CodeAnalysis.Diagnostics.AbstractHostDiagnosticUpdateSource.ClearAnalyzerReferenceDiagnostics - 5817ms` and `Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.GetAnalyzerTypeNameMap 2027ms` which do IO and cause FileSystemWatcher disposal to take a long time, due to it causing a synchronization with kernel data structures.

**Comment by Therzok** [comment]
@jinujoseph please take a look here!

**Comment by Therzok** [comment]
Seems like the code has changed a bit since we forked. Investigating on our side

**Comment by davidwengier** [comment]
Looking at the trace it seems like `ClearAnalyzerReferenceDiagnostics` is causing the analyzers to load, which obviously is unnecessary when the intention is to clear diagnostics from them, so changing that method to no-op if the analyzers haven't been loaded seems like a sensible fix.

@Therzok Does that analysis make sense to you? It's not clear to me if this issue coming up is a regression for you or not, is it possible that your code around initialization might have changed?

**Comment by Therzok** [comment]
Also created a PR on our side to match current code in master. https://github.com/xamarin/vsmac/pull/1939

**Comment by Therzok** [comment]
There have been some changes on the roslyn side which changed the behaviour on VisualStudioAnalyzer and we've lagged behind on that - i.e. Roslyn no longer does file watching.

The fix to not load if not loaded is welcome anyhow!

**Comment by davidwengier** [comment]
Closing this as VS for Mac has been updated, and #43008 will fix the problem once and for all.
