### ISSUE TITLE
Inline of temporary string-interpolation variable gives duplicate parentheses

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#4583]
Here's my code:
```vb
        Dim s1 = $"hello"
        Dim s2 = AscW(s1)
```
If I try to inline the temporary variable `s1`, it generates duplicate parentheses:
![inline-interpolate](https://cloud.githubusercontent.com/assets/3316258/9292021/f3f139c6-4395-11e5-9119-bde01688f7dc.png)

I think it shouldn't! It should only generate one pair of parentheses! 

(The problem appears limited to string interpolation expressions. It doesn't happen with normal strings.)

**Comment by tmat** [comment]
Seems related to https://github.com/dotnet/roslyn/issues/4490.

**Comment by AdamSpeight2008** [comment]
The extra parentheses could be advantageous, if the interpolation string had any arg-holes in it.

**Comment by DustinCampbell** [comment]
PR #4595 is out to fix this issue. @tmat, it doesn't appear to be the same as #4490.

**Comment by DustinCampbell** [comment]
PR is merged.
