### ISSUE TITLE
Remove empty column in Change Signature UI

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#45838]
Eventually we want to remove this empty column in the Change Signature UI:

![image](https://user-images.githubusercontent.com/235241/84189779-b0e01a00-aa4a-11ea-9bdd-2e2fac8f20b7.png)

In doing this, we will also want to modify the code to focus at a datarow level by default (currently it is cell level by default), and allow users using Narrator to go to individual data cells if desired, similar to how Error List and Test Explorer behave today.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
