### ISSUE TITLE
Add telemetry to check punctuation color after Roslyn package writes enhanced color to the registry.

### ISSUE THREAD

**Issue by hjihong** [dotnet/roslyn#45852]
Related to black braces showing up in dark theme. 

Ask is to add telemetry on Roslyn's side after writing enhanced colors to the registry checking if punctuation color (+ others) is what it should be relative to the background. 

This was done in the Editor by calculating the contrast between the background of the view and the text and flagging anything with a contrast under 3.0. 

@JoeRobich

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
