### ISSUE TITLE
C# intellisense always suggests type keywords, even when it proabably shouldn't

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#4585]
If I declare a variable using class library type names, intellisense suggestions always seem to prefer type keywords when available. For example if I type `List<Int32> list = new`, the intellisense popup will suggest `List<int>`.

There are a couple of editor settings around which style to prefer, but this particular scenario doesn't seem to be covered by either. Maybe intellisense should honour the setting for "declaring locals, parameters and members" and/or when the assignment is _near_ the declaration (for some reasonable definition of _near_) it could infer the correct value from the declaration?

**Comment by CyrusNajmabadi** [comment]
Intellisense is following the rules specified in editor config around builtin types.  We think it's fine if we continue following that, even if the local code deviates from editor config.  We'd need a lot of feedback indicating this needs special handling to make any changes here.
