### ISSUE TITLE
Automatically add missing using directives 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#45853]
Direct customer ask copying here:

> When copying and pasting types to a file the using directives should automatically get added rather than having to add them manually: 
![image](https://user-images.githubusercontent.com/46729679/87100341-0736a900-c201-11ea-8a06-76df1142da35.png)

**Comment by CyrusNajmabadi** [comment]
I'm very hesitant about that.  It may take a fast operation and make it extremely slow.  Today we already have a feature that lsitens for paste and proffers *Asynchronously* the lightbulb that will adding usings if the user wants to do that.  That model both serves this need, and doesn't cause undue delays for users trying to do normal activities.

Note: thsi perf concern is not a hypothetical.  Pasting in VB is commonly extremely slow as we do code-cleanup autoamtically on that text. This may mean unbounded work as we construction compilations and the like.

**Comment by allisonchou** [comment]
**Conclusion from design meeting (7/13)**:
Our current idea is to timebox this feature (~0.5s). If allotted time is exceeded, we will still offer the feature as a lightbulb item with high priority, i.e. first or second item in list.

**Comment by ryzngard** [comment]
This feature is done at this point. #49442 tracks us adding an async version which we believe we could enable by default.
