### ISSUE TITLE
Refactoring actions in Visual Studio 2019 don't take C# namespace aliases into account

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#45868]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1106422/refactoring-actions-in-visual-studio-2019-dont-tak.html)._

---
How to reproduce :
- declare a namespace alias in a C# file, eg. `using GDI = System.Drawing;`.
- declare an interface with a member that uses a type from the GDI namespace.
- create another code unit, declare the same namespace alias and write a class that implements the interface.
- use the "Implement interface" refactoring action: the generated members won't be using the existing namespace aliases, instead they will add a "using" statement for that namespace again, and if any existing type in the code unit collides with that new namespace, they will get fully qualified.

Expected behavior:
- Visual Studio should generate new members using any existing namespace alias at maximum (eg. if an alias for namespace ALIAS = A.B is declared, and the generated code needs to quality type A.B.C.MyType, it should use ALIAS. C.MyType).

This behavior can be seen with any code generating action (override a member, add a new member, etc.).

---
#### Feedback Bot on 7/8/2020, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment]
Design meeting outcome - we should update the system to reuse the using alias if present instead of creating a new using statement.

@CyrusNajmabadi could you add the proposal details on where to make the change and mark for help wanted once done?

**Comment by CyrusNajmabadi** [comment]
The idea here would be update hte part of hte 'add import for new syntax' algorithm that decides if a `using` is already there or not.  It should consider these aliases as effectively introducing those `using`s.  That will cause us to not add the simple `using`.  

Note: when this is done, we should validate tehse features to ensure that they still simplify the type-names to use the existing alias.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
