### ISSUE TITLE
Emphasize text for nullable flow state in quick info

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#45888]
From https://github.com/dotnet/csharplang/issues/3662#issuecomment-656854906 

> I think even the normal "May be null/not null here" display isn't emphasized strongly enough relative to the nullable type displayed first. Could "not null" be bold when the type is nullable, or always?
> 
> ![image](https://user-images.githubusercontent.com/8040367/87191610-c4d5a080-c2c2-11ea-96e8-2f1bf0c7cd7b.png)
> 
> Conversely, could "may be null" be bold when the type is non-nullable, or always?
> 
> ![image](https://user-images.githubusercontent.com/8040367/87191699-ee8ec780-c2c2-11ea-99ec-b33ce3efbaed.png)

**Comment by jnm2** [comment]
The example in the first screenshot is the one I trip over several times a week. The second example would be pretty rare because there would be a warning in code.

**Comment by LWChris** [comment]
In the referenced issue, it was discussed whether both messages should have the significant part in bold, or only one of them to have them visually distinct not by the content but also their appearance.

Personally, I'd also prefer if you made only one state bold.

To summarize the discussion, which I agree with, it is hard to decide which of those two should get to be bold:

**Pro "may be null":** Technically, _may be null_ is the more "dangerous" case. It is supposedly rarely the case that code expects some variable to be null and fails if it is not. So "is not null" is not critical, "may be null" might be critical information.

**Pro "is not noll":** On the other hand, if you use a nullable variable in a way that could produce NPE, you will already see a warning from the flow analysis. Therefore, visual aid for the "may be null" context has already been provided, and the "not null" information is the one you are actually _only_ "informed" about from that tool tip, and not by any other visual markers.

I'd like to add that if you cannot decide on which to make bold and therefore stick with making some part bold for both, expect the user to first/only read the bold part. The goal is to make only the information bold.

Therefore, opposed to suggested:

> 's' **is not null** here.

> 's' **may be null** here.

I recommend to go for:

> 's' **is not** null here.

> 's' **may** be null here.

Plus, if that should ever be added:

> 's' **is** null here.

![image](https://user-images.githubusercontent.com/475144/87202934-6acede00-c2b6-11ea-979b-7dfb4ca79796.png)

"may be null" is a slight understatement here 😄

**Comment by dibarbet** [comment]
Design meeting notes
No change at this time – future usability studies will consider emphasis to make it easier to work with this feature.

**Comment by ryzngard** [comment]
Closing as won't fix for now based on design review
