### ISSUE TITLE
Simplify Function Pointer Space Formatting Rules

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#45897]
We can simplify the check for function pointer calling convention identifiers by using the new node types, but that code will depend on types that do not exist in the CodeStyle layer. This should be simplified when we have access.

See: https://github.com/dotnet/roslyn/pull/45684#discussion_r451066787.

**Comment by vatsalyaagrawal** [comment]
@sharwell

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do something here, we cna assign to a person/milestone to have it actually be done.
