### ISSUE TITLE
RenameTestHelpers.CreateWorkspaceWithWaiter ignores TestHost parameter value

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#45890]
See https://github.com/dotnet/roslyn/pull/45847/commits/6e0b6778e3fa44441c5cd1d6297bb3708a4be3be#diff-c759cadb9248072b9d4a9e40bb7f8df9R113

We should either remove or respect the parameter

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.  If this needs to be done it needs to be assigned to a developer.
