### ISSUE TITLE
Should /warnversion affect /warn?  (e.g. override the /warn value)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#45906]
When the user sets the /warnversion flag, should that change or affect the value of the /w (/warn) flag, which currently ranges from 0-4?

/cc @jcouv @jmarolf

**Comment by jmarolf** [comment]
previous designs wanted to remove `/w`/`/warn` altogether and just say that `/warnversion` is the new thing. 

I personally thing we should keep `/warn` and `/warnversion` for backcompat though I will admit I do not know which warnings are issued if you pass 0, 1, 2, 3, or 4 to `/warn`

**Comment by gafter** [comment]
We've dropped `/warnversion`. There is only `/warn` now. A value of 5 indicates the first warning wave.
