### ISSUE TITLE
Move to new async API for nuget package querying/installation.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#45901]
Nuget team has produced their API and is ready for it to be consumed.  More info at:

https://github.com/NuGet/NuGet.Client/pull/3469 and
https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.VisualStudio.Contracts

They believe their bits are in intpreview already and should be in 16.7p4 very shortly.  We should update our code to use that asap as the existing IVsPackageXXX apis are a huge source of UI delays in vs.

**Comment by vatsalyaagrawal** [comment]
@CyrusNajmabadi 16.7.P4 has closed. Are we planning this for 16.7?

**Comment by CyrusNajmabadi** [comment]
no.  i meant 16.8

**Comment by zivkan** [comment]
The contracts package is now available on nuget.org: https://www.nuget.org/packages/NuGet.VisualStudio.Contracts/
