### ISSUE TITLE
FxCop CA2235 is unaware of [NonSerialized] attribute

### ISSUE THREAD

**Issue by RalfKoban** [dotnet/roslyn#4591]
Hello,

using "Microsoft.CodeAnalysis.FxCopAnalyzers" v1.0.1, I get a false positive for rule CA2235.
My field has the [NonSerialized] applied, but it still reports a violation of CA2235:

        [NonSerialized]
        //// ReSharper disable once MemberCanBePrivate.Global
        //// ReSharper disable once UnassignedField.Global
        public Action<string> SomeAction;

Best regards,
Ralf

**Comment by srivatsn** [comment]
Moved the issue to roslyn-analyzers repo - https://github.com/dotnet/roslyn-analyzers/issues/279
