### ISSUE TITLE
Incorrect "Cast is redundant" for constant patterns where the constant is an explicit cast from a numeric literal

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#45925]
**Version Used**: 16.7-p3.1

There should be no diagnostics here. Any change results in different runtime behavior.

`_` denotes a faded span.

```cs
class C
{
    bool M(object obj)
    {
        // IDE0004: Cast is redundant
        //                 ______     ______     _______     _______     ________     ______     _______
        return obj is 0 or (uint)0 or (long)0 or (ulong)0 or (short)0 or (ushort)0 or (byte)0 or (sbyte)0 or (float)0
        //      ________     _________     __________________
             or (double)0 or (decimal)0 or (AttributeTargets)0;
    }
}
```

(All but short, ushort, byte, and sbyte would normally be written using numeric literal suffixes rather than explicit casts.)

**Comment by vatsalyaagrawal** [comment]
@CyrusNajmabadi FYI

**Comment by LeroyK** [comment]
I ran into this as well with a [var pattern](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#var-pattern). Analyzer incorrectly suggests to remove ``(ushort)`` in this example:
```c#
public ushort CastIsNotRedundant()
{
    if ((ushort)0 is var result) { }
    return result;
}
```

**Comment by RikkiGibson** [comment]
Similarly, the following sample gives a "redundant cast" diagnostic whose removal results in a compile error. Found when looking at #49740


[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHAZgAJ9KBhSgb1MpeoBZKBZACgGMALCAkq8AlI2aspaAGaVu3NADsYo3pTRRKAHkoByfZQD2wgHwBeSgAYAHgStXRkqSyYkXrAL7PK3kp6A)

```cs
void M(char c) {
    if ((int)c is < ' ' or >= 0x100) // (int) syntax has a "Cast is redundant." diagnostic.
    {
    }
}
```

**Comment by alrz** [comment]
I suspect it's because there's always a conversion to `int` in `char` comparison operators even for `==`. Discovered in https://github.com/dotnet/roslyn/pull/49757. 

```cs
(int)c is 100   // not redundant
(int)c is < ' ' // def redundant

c == 100 // c implicitly converts to int
c == 'a' // c implicitly converts to int still

```
