### ISSUE TITLE
Cast to nint has different semantics for constants vs. run-time

### ISSUE THREAD

**Issue by dgrunwald** [dotnet/roslyn#45929]
**Version Used**: VS2019 16.7.0 Preview 3.1

**Steps to Reproduce**:

```
    public static void Main()
    {
        const long a = long.MaxValue;
        long b = long.MaxValue;
        nint x = (nint)a;
        nint y = (nint)b;
        Console.WriteLine($"x={x}, y={y}");
    }
```

**Expected Behavior**:
Both `x` and `y` should have the same value: -1 on 32-bit run-times; 9223372036854775807 on 64-bit run-times.

**Actual Behavior**:
Output is: `x=-1, y=9223372036854775807`
The value is truncated to 32-bit or 64-bits depending on whether the cast operand is a compile-time constant.

I think the compiler should never use overflow for `nint` during constant-folding (not for casts, and also not for arithmetic in explicitly-unchecked contexts); instead deferring any overflowing operations until run-time.

**Comment by cston** [comment]
Thanks for reporting @dgrunwald. This issue has been fixed in https://github.com/dotnet/roslyn/pull/45581.
