### ISSUE TITLE
Remove and Sort Usings converts leading whitespace

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#45931]
**Version Used**: 

Visual Studio 2019 v16.6.2 among many

**Steps to Reproduce**:

1. Create or open a file that uses tab-based indentation and has superflous usings
2. Run the "Remove and Sort Usings" command

**Expected Behavior**:

The code still has tab-based indentation

**Actual Behavior**:

The first line within a `namespace` declaration has been converted to spaces-based indentation.

---

I've put together a couple failing unit tests [on a branch here](https://github.com/yaakov-h/roslyn/commit/386fba1abe4b0b9bea4ffe5a4b717e321b042cba), though I've looked through the relevant code and have no idea how to fix this, at least not without breaking other things.

It seems that the code cleanup service also runs any changed code through the formatter, which reformats to spaces since there's no overriding configuration (such as a `.editorconfig`).

This is particularly annoying for me as many projects I work with use third-party Roslyn Analyzers, one of which enforces tab-based indentation. Removing and sorting usings in an otherwise perfectly-valid source file now triggers an analyzer failure (which gets promoted to a build error) purely because code that was not part of the edit operation comes along for a ride with the `Formatter`.

**Comment by CyrusNajmabadi** [comment]
> This is particularly annoying for me as many projects I work with use third-party Roslyn Analyzers, one of which enforces tab-based indentation.

Why not provide an editorconfig tab option for that project?

**Comment by yaakov-h** [comment]
Purely because I have a lot of projects that predate editorconfig, and applying our standard editorconfig file to all those projects is not a high priority.

Also in one of those projects another team has added a root editorconfig into a deep subfolder (I suspect they didn't quite understand what they were doing) and that will probably take quite a bit of time to rectify.

I also have some projects that use spaces and some that use tabs, and I dont want to have to keep flipping VS's settings between them either.

**Comment by CyrusNajmabadi** [comment]
Does this repro if you have an editorconfig that specifies tabs?

**Comment by yaakov-h** [comment]
I can't repro anymore in VS2022 v17.3.6, even without an editorconfig.

**Comment by CyrusNajmabadi** [comment]
Closing out then :-)
