### ISSUE TITLE
Use IOpenDocumentService instead of IVsUIShellOpenDocument + RDT

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#45954]
In many cases we use [IVsUIShellOpenDocument.OpenDocumentViaProject](http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,1036) + then retrieving the text buffer from the RDT to open documents at a particular location.

The editor is introducing a new service broker service (IOpenDocumentService) that we can use to greatly simplify the action of opening a file at a particular location.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we want to do this, we shoudl assign to an actual milestone to get it done.
