### ISSUE TITLE
NotNullIfNotNull does not work for properties

### ISSUE THREAD

**Issue by mladedav** [dotnet/roslyn#45984]
**Version Used**:  Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core (I was unable to google where I can get roslyn version if this is not it)

**Steps to Reproduce**:

```
class Program
    {
        public object? First;

        [NotNullIfNotNull(nameof(First))]
        public object? Second => First;

        static void Main(string[] args)
        {
            var n = new Program();

            if (n.First is null) throw new ArgumentNullException();

            object f = n.First;
            object s = n.Second; // warning CS8600: Converting null literal or possible null value to non-nullable type.
        }
    }
```
**Expected Behavior**:
Neither `object f = n.First;` or `object s = n.Second;` gives out warning because first was explicitly checked and second has an attribute that it is null if first is not null.

**Actual Behavior**:
`object s = n.Second;` gives warning that I am assigning possible null value to a non-nullable variable.

**Related issues**:
Same attribute for operators
https://github.com/dotnet/roslyn/issues/39802

**Comment by jcouv** [comment]
This behavior is by-design. The NotNullIfNotNull attribute is designed to tie the nullability of output values to that of input value in a signature, not to tie the nullability of one member to that of another.
I'll go ahead and close as by-design.

**Comment by DrkWzrd** [comment]
> This behavior is by-design. The NotNullIfNotNull attribute is designed to tie the nullability of output values to that of input value in a signature, not to tie the nullability of one member to that of another. I'll go ahead and close as by-design.

If that is the case, why is `NotNullIfNotNull` allowed in properties (`System.AttributeTargets.Property`)? Can you post an example where this AttributeTarget is needed?
