### ISSUE TITLE
IRefactoringHelpersService.GetRelaventNodesAsync<MemberDeclarationSyntax> Behavior Change With Caret On Attributes

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#45987]
The current behavior of IRefactoringHelpersService.GetRelevantNodesAsync<MemberDeclarationSyntax> works such that caret position before the first attribute will return the method, and care position before or after any other attribute will not. For example

```c#
[||][Attribute1] // <-- caret with [||] will get "MyMethod" declaration as relevant node
[||][Attribute2] // <-- caret with [||] will NOT get "MyMethod" declaration as relevant node
[Attribute3][||] // <-- caret with [||] will NOT get "MyMethod" declaration as relevant node
void MyMethod()
{
}
```

My proposal is that we change this such that the caret being outside of any attribute will still count the method (or other member declaration) as a relevant node. The motivation is for "Pull Members Up" and "Extract Superclass" features that would trigger on member level.

With new behavior
```c#
[||][Attribute1] // <-- caret with [||] will get "MyMethod" declaration as relevant node
[||][Attribute2] // <-- caret with [||] will get "MyMethod" declaration as relevant node
[Attribute3][||] // <-- caret with [||] will get "MyMethod" declaration as relevant node
[Attribute4[||]] // <-- caret with [||] will NOT get "MyMethod" declaration as relevant node
[[||]Attribute5] // <-- caret with [||] will NOT get "MyMethod" declaration as relavent node
[Attri[||]bute6] // <-- care with [||] will NOT get "MyMethod" declaration as relavent node
void MyMethod()
{
}
```

*NOTE* Since this implementation is not public, change will also need to be made in [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/blob/e0578cd7e5644a6a4c5bc3d8476aa31d1650b6a2/src/Utilities/Refactoring/AbstractRefactoringHelpers%603.cs#L25)

**Comment by CyrusNajmabadi** [comment]
> will return the method, and care position before or after any other attribute will not.

Slight refinement.  "Following any attribute on hte same line as it, as long as it is on a preceding line from the member".

**Comment by CyrusNajmabadi** [comment]
Open question:

`[Foo]$$[Bar]`  Woudl this count?    Or only `$$[Foo][Bar]` or `[Foo][Bar]$$`

?

Note: i do not think of these questions is a syntax-tree focused manner, or a whitespace-insensitive manner.  This is a *very* whitespace sensitive heuristic.  So while 

```
[Foo]$$
[Bar]
```

makes sense to me (since hte user may have just hit up/down on the line), having a location *between* attributes on the same lien does not necessarily make sense to me.

**Comment by CyrusNajmabadi** [comment]
Note: i also don't feel strongly.  It's just that if you're here, might as well check all the permutations :)

**Comment by ryzngard** [comment]
>Open question:
> `[Foo]$$[Bar]` Would this count? Or only `$$[Foo][Bar]` or `[Foo][Bar]$$` ?

I think it's fine that `[Foo]$$[Bar]` works just because of how uncommon putting attributes on the same line is.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  IF we want to make a change here we should assign to a dev/milestone and just do it.
