### ISSUE TITLE
Revert JsonRpc cancellation suppression workaround

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#45980]
We removed cancellation support due to an issue in JsonRpc: https://github.com/microsoft/vs-streamjsonrpc/issues/489
Once this issue is fixed, make all RPC invocations cancelable again.

**Comment by jinujoseph** [comment]
microsoft/vs-streamjsonrpc#489 fixed the issue and we did not had to take the workaround hence closing this issue
