### ISSUE TITLE
Code generation options [Ctrl + .]  generates duplicate options

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#4599]
1. Copy code shown below.
2. Press Ctrl+. on Constants line
3. Note how there are 3 options that are exactly the same

```C#
public class MyClass
{
    public void MyMethod()
    {
        DoSomething(Constants.VALUE1, Constants.VALUE2, Constants.VALUE3);
    }

    public void DoSomething(string value1, string value2, string value3)
    { }
}
```

![attachfilehandler](https://cloud.githubusercontent.com/assets/9797472/9316023/82c58c7c-44e7-11e5-826e-4257e4b2bf53.png)

**Comment by Pilchie** [comment]
Tagging @DustinCampbell  and @CyrusNajmabadi since they have been thinking about the multiple issues per line experience lately too. See also #5384

**Comment by CyrusNajmabadi** [comment]
This seems by design-ish.  one way to mitigate this would be to make it so that ctrl-<dot> doesn't bring up all the options on the line, but instead only brings up the options nearest to the caret.

**Comment by CyrusNajmabadi** [comment]
I mean, if you'd had 

```
DoSomething(Foo.a, Bar.b)
```

Then we would expect to see optoins for "Generate Foo" and "Generate Bar".

--

That said, i suppose there's room for simple filtering at the UI level. i.e. don't bother even showing multiple results if they literally have the exact same title.

**Comment by Pilchie** [comment]
How does this look now - do we need to do more here?

**Comment by CyrusNajmabadi** [comment]
I think we've done enough here at this point.  I would still like ctrl-<dot> to only bring up what's closest to the caret, but i think that should be tracked separately.
