### ISSUE TITLE
"Generate GetHashCode()" is using System.HashCode when it's not available

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#45995]
This issue https://github.com/dotnet/roslyn/issues/42978, but for VB.

**Version Used**: 

**Steps to Reproduce**:

``` VB

            Public Overrides Function GetHashCode() As Integer
                Dim hashCode = 870297925
                hashCode = hashCode * -1521134295 + MyBase.GetHashCode()
                hashCode = hashCode * -1521134295 + IsEquivalentToSubMain.GetHashCode()
                Return hashCode
            End Function
```

**Expected Behavior**:

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1103906/87496410-dccc6c00-c696-11ea-91c5-98f6393ba82e.png)

**Comment by sharwell** [comment]
💭 The fix for #42978 should have also applied to this issue (it was made in language-agnostic code)

**Comment by davkean** [comment]
If I go to definition, it navigates to:

![image](https://user-images.githubusercontent.com/1103906/87616741-22ea0400-c759-11ea-9a20-e21df34689c0.png)

I get the following errors:

```
Error	BC30390	'HashCode.Public Shared Overloads Function Combine(Of T1, T2)(value1 As T1, value2 As T2) As Integer' is not accessible in this context because it is 'Public'.	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\PropPages\WPF\ApplicationPropPageVBWPF.vb	943	Active
Error	BC30389	'System.HashCode' is not accessible in this context because it is 'Friend'.	Microsoft.VisualStudio.Editors	C:\project-system\src\Microsoft.VisualStudio.Editors\PropPages\WPF\ApplicationPropPageVBWPF.vb	943	Active

```

That first error is weird and don't understand it.

**Comment by davkean** [comment]
That first is probably a compile bug in the error.

**Comment by CyrusNajmabadi** [comment]
Yup, that's bad.  we should def be doing an accessibility check here

**Comment by sharwell** [comment]
We actually "are" doing an accessibility check, but I guess it's broken?

https://github.com/dotnet/roslyn/blob/4a877e62831c956ef597a120931a3cf84a0c9cdc/src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/AbstractGenerateEqualsAndGetHashCodeService.cs#L150-L151

**Comment by CyrusNajmabadi** [comment]
This is the lightbulb.  so i think the issue is here: https://github.com/dotnet/roslyn/blob/master/src/Analyzers/Core/Analyzers/UseSystemHashCode/UseSystemHashCodeDiagnosticAnalyzer.cs.  Specifically, right here: https://github.com/dotnet/roslyn/blob/4a877e62831c956ef597a120931a3cf84a0c9cdc/src/Analyzers/Core/Analyzers/UseSystemHashCode/Analyzer.cs#L47
