### ISSUE TITLE
Object Browser question

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#45992]
Reported from internal customer Roy Williams (COSINE)

I am using it to look at Sarif.Sdk which is produced by 1ES and I see:
 
public SarifLogger(string outputFilePath, Microsoft.CodeAnalysis.Sarif.Writers.LoggingOptions loggingOptions = 1, Microsoft.CodeAnalysis.Sarif.OptionallyEmittedData dataToInsert = 0, Microsoft.CodeAnalysis.Sarif.OptionallyEmittedData dataToRemove = 0, Microsoft.CodeAnalysis.Sarif.Tool tool = null, Microsoft.CodeAnalysis.Sarif.Run run = null, System.Collections.Generic.IEnumerable<string> analysisTargets = null = null, System.Collections.Generic.IEnumerable<string> invocationTokensToRedact = **null = null**, System.Collections.Generic.IEnumerable<string> invocationPropertiesToLog = **null = null**, string defaultFileEncoding = null)

I don’t understand the = null = null annotations.  Is this a known bug?

**Comment by jinujoseph** [comment]
from @olegtk 
“System.Collections.Generic.IEnumerable<string> analysisTargets = null = null,”

Looks like a bug, not a special kind of annotation. Object Browser has a provider model so for managed assemblies member signatures are provided by Roslyn, likely the bug is somewhere here: https://github.com/dotnet/roslyn/blob/d5f93d4e5a8456648e0ee7d4e734c0c5e3dbe13b/src/VisualStudio/CSharp/Impl/ObjectBrowser/DescriptionBuilder.cs#L443

**Comment by CyrusNajmabadi** [comment]
Closing out as object-browser is in maintenance mode and we don't intend to do further work on it (absent a rewrite/reimplementation).
