### ISSUE TITLE
Nested call to non-existent ctor gives nonsensical quick fix

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#4600]
Source:
```C#
class X {
	X(string x) {
	new X(new string());
	}
}
```
The quick fix in the middle line will offer to create `X(string)`, even though that (a) already exists and (b) has nothing to do with the original error.

In other scenarios (I'm not sure exactly why), it generated a parameterless ctor with `:base()`.

Even worse:

```C#
abstract class Y {
    class X : Y {
        void M() { new X(new string()); }
    }
}
```
Quick fix generates 
```C#
public X() : base() {
}
```

**Comment by jmarolf** [comment]
@slaks moving your bug from [codeplex](http://roslyn.codeplex.com/workitem/384) to github

**Comment by dpoeschl** [comment]
Notes: The first case above doesn't repro anymore. The second case only occurs when X is *both* nested inside and inherits from Y.

**Comment by jmarolf** [comment]
Second case no longer repos
