### ISSUE TITLE
Encapsulate field doesn't resolve local variable conflicts

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1111525/encapsulate-field-doesnt-resolve-local-variable-co.html)._

---
With Microsoft.CodeAnalysis.FxCopAnalyzers 3.0.0

Create a new C# class library project with the following content:

```csharp
public abstract class Base
{
    protected Base(object logger)
    {
        _logger = logger;
    }

protected readonly object _logger;
}

public class Derived : Base
{
    public Derived() : base(new object())
    {
    }

public object Logger => _logger;
}
```

The analyzer reports "CA1051 Do not declare visible instance fields" for the `_logger` field in `Base`.
Use the lightbulb fixer to "Encapsulate field '_logger' (and use property)"

Note now that the code compiles with an error because it chooses the name `logger` for the backing field (even though I have my naming preference for private fields set to camel case with leading underscore) and that conflicts with the parameter name in Base's constructor. (Note, though that I do get "CS1717 Assignment made to same variable" as a warning, thankfully).

Expect:
The field name should not be touched. It should honor my naming preferences for private fields.
Bonus points for noticing that it could be an auto-property and eliminate the private field altogether.

---
#### Feedback Bot on 7/13/2020, 08:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedbakc.
