### ISSUE TITLE
Quick fix suggestion to create a constant from a constant is useless

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46007]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1103905/quick-fix-suggestion-to-create-a-constant-from-a-c.html)._

---
I see quick fix suggestions on this line:

const string HEAD_END = "</head>";

it suggests me to fix into this:

const string V = "</head>";
    const string HEAD_END = V;

which is a useless fix

---
#### Feedback Bot on 7/6/2020, 10:51 AM: 

We have converted this feedback item from idea to problem. This change was done to better reflect the feedback's nature.
#### Hongying Wang [MSFT] on 7/6/2020, 07:11 PM: 

<p>Thank you for your feedback! What we want to confirm with you is whether your project is C++ or C# or other languages. We look forward to hearing from you!</p>

#### Artemious on 7/11/2020, 00:08 AM: 

<p>My project is C#</p>

#### Feedback Bot on 7/12/2020, 07:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is by design.  User may be extracting out/duplicating a different constant, and they then intend to change the value of the exisitng one.
