### ISSUE TITLE
IDE0071 suggested for call to shadowing ToString method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46011]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1111981/ide0071-suggested-for-call-to-shadowing-tostring-m.html)._

---
Calls to a shadowed `ToString` in a string interpolation are reported as superfluous; removing them results in a call to the virtual `object. ToString` instead of the shadowing method.

public class A
    {
        public new string ToString()
        {
            return "Shadow";
        }

public static void Main(string[] args)
        {
            Console.WriteLine($"{new A(). ToString()}");
        }
    }

---
#### Feedback Bot on 7/14/2020, 01:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Tagging @jnm2 .
