### ISSUE TITLE
Generate class omits final newline

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#4602]
In the 4/3 End User Preview, the Generate Class feature omits the trailing newline in generated files.

**Steps to reproduce**
1. Add the following field to a class
`SomeUndefinedType foo;`
2. Invoke the **View.ShowSmartTag** action on the line where the field is defined (by default Alt+Shift+F10 or Ctrl+.)
3. Select **Generate class for 'SomeUndefinedType' in '[namespace]' (in new file).**

**Expected behavior**
The generated file ends with a trailing newline.

**Actual behavior**
The generated file ends with a `}` character that is not followed by a newline.

**Comment by jmarolf** [comment]
@sharwell Ported from [codeplex](http://roslyn.codeplex.com/workitem/195) issue

**Comment by rchande** [comment]
Assigning to Kasey.

**Comment by dpoeschl** [comment]
Note: In Dev12, files added by GenerateType *did* contain a newline at the end.

**Comment by dpoeschl** [comment]
@sharwell Hey Sam, we're discussing this in the office and were wondering what prompted you to file the bug in the first place. What made you notice the lack of a newline after the close curly brace? Thanks!

**Comment by davkean** [comment]
Here's a uservoice item: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8298222-add-new-line-at-the-end-file-on-save.

**Comment by dpoeschl** [comment]
This appears to need more discussion. /cc: @CyrusNajmabadi 

Sending back to triage to make a final ruling.

**Comment by sharwell** [comment]
@dpoeschl 

> What made you notice the lack of a newline after the close curly brace? Thanks!

Git diff makes an ugly message. Also we have an analyzer that reports a warning when files don't end with a new line.

**Comment by Pilchie** [comment]
Note - we think the right fix here in the long term would be for the editor team to address this for all languages based on a `.editorconfig` setting.

However, in the short term, this could be fixed in Roslyn in the formatting engine, with a option for whether to have the trailing newline or not.

**Comment by CyrusNajmabadi** [comment]
I don't repro this if your editorconfig says to use a newline.  That's the way we want to handle this going forward.
