### ISSUE TITLE
Failing HighlightRefsMultipleSubmisionsVerifyRenameTags tests

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#46027]
The move of integration tests running on 16.7 Preview 2 to 16.7 Preview 3.1 has caused a few new test failures.

- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnUnsubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpWhenInvokedOnSubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnTypesWhenInvokedOnUnsubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnTypesWhenInvokedOnSubmittedText

- [ ] Skip tests (https://github.com/dotnet/roslyn/pull/46028)
- [ ] Fix and unskip tests ()

**Comment by CyrusNajmabadi** [comment]
Incomparable!
