### ISSUE TITLE
Need a way to insert debug information for Source Generated methods

### ISSUE THREAD

**Issue by joelpryde** [dotnet/roslyn#46032]
**Version Used**: 
NET 5.0 Preview 2

**Steps to Reproduce**:
1. Generate partial class and method with sourcegen.
2. Emit source in source files alongside original source files.
3. Attempt to debug emitted source in a variety of IDEs.

**Expected Behavior**:
(Well, in this case _hoped_ behavior)
Able to set breakpoints in emitted source files and hit them.

**Actual Behavior**:
No breakpoints hit.

None of this is too surprising as the source is getting emitted into the compilation as raw text.  I can get around this limitation by littering my emitted source with #line directives that point back to the emitted source files, but this is pretty unwieldy.  It would be very nice if there was an IDE that let me add additional sequence points to the source I am emitting.  This could come in the form of an additional API for adding source as a syntax tree (with necessary metadata to create debug info) instead of a string or as a utility that would take an existing syntax tree and auto-generate versions with #line info and without.  Manually doing this is fairly error prone though and seems like oft-desired functionality.

**Comment by CyrusNajmabadi** [comment]
Because SourceGenerator generated files are just normal files, it should generate normal debug information.  I imagine the core problem is simply that we haven't hooked things up so you can set breakpoints in teh generated file.  @jasonmalinowski ?

**Comment by jasonmalinowski** [comment]
Tagging @chsienki as well.

I'm confused @joelpryde by your step 1 and step 2: is this using the new source generator feature, or are you implementing your own thing (say in MSBuild) that's writing to files yourself?

**Comment by mjsabby** [comment]
Maybe it needs embedding of the C# files in the PDB ...

**Comment by jasonmalinowski** [comment]
And perhaps yes either way @mjsabby is indeed correct: if you enable source embedding into the PDB then it will work. In regards to the source generator _feature_ this is also a known gap that we're not always doing that well, and that the IDE should also be able to work even if you have that off. We're working on fixing that.

**Comment by joelpryde** [comment]
Hey @jasonmalinowski, what I'm currently doing is the following (all inside of my source generator):
1. Generate new source and emit into compilation with `context.AddSource`.
2. Use System.IO.File to write out the same file to the file system.

I'm doing this for my own sanity of being able to see the generated source, but also so I can put breakpoints in the written file and debug across a number of IDEs (VS, Riders, etc.).  This works, but only if I litter #line directives pointing the source I emitted with AddSource back to the files written out.

My understanding is that IDEs will eventually be source generator aware and make all of this unnecessary.  My understanding is that this is largely still to come (and may not help me with other IDEs regardless).

Hope that makes some sense.  Please let me know if there is an easier way to go about this.
I will also say - in general - source generators have been a joy to use.  Such a powerful new feature.

**Comment by joelpryde** [comment]
It does indeed look like `/embed` works for debugging source with both Rider and VS!  Can't believe I did not know about that compiler flag until now.  I'm not entirely sure how the source will be initially discoverable other than stepping into source generated code or putting a breakpoint in a method called from generated code.  I can look into that though.
My original ask would still be handy for redirecting debug information to files on disk, but it looks like `/embed` should get me most of the way there.  Many thanks!
