### ISSUE TITLE
Roslyn analyzer templates don't correctly package NuGet packages if project name contains a period

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#4603]
1. Install the Roslyn SDK.
2. Create a new code NuGet + VSIX analyzer project called Cat.Cat.
3. Try to build.

*Expected:* it works
*Actual:* you get a build error like "The "GetAssemblyIdentity" task's outputs could not be retrieved from the "Assemblies" parameter. The name "Cat.CatAssemblyInfo" contains an invalid character "."."

This is filed on behalf of @AlessandroDelSole.

**Comment by jasonmalinowski** [comment]
The workaround is to update the project. Open the project file directly, and find these lines:

```xml
  <Target Name="AfterBuild">
    <GetAssemblyIdentity AssemblyFiles="$(OutDir)\$(AssemblyName).dll">
      <Output TaskParameter="Assemblies" ItemName="Cat.CatAssemblyInfo" />
    </GetAssemblyIdentity>
    <Exec Command="&quot;$(SolutionDir)packages\NuGet.CommandLine.2.8.5\tools\NuGet.exe&quot; pack Diagnostic.nuspec -NoPackageAnalysis -Version %(Cat.CatAssemblyInfo.Version) -OutputDirectory ." WorkingDirectory="$(OutDir)" LogStandardErrorAsError="true" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
  </Target>
```

There are two uses of "Cat.CatAssemblyInfo". Delete the dot within there. On the `<Exec>` line, the dot before "Version" is correct.

**Comment by jmarolf** [comment]
This has been fixed internally.  I'll reply back here when I can give you a VSIX to test.
