### ISSUE TITLE
incorrect replace with conditional when one side is default

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#46039]
**Version Used**: VS 16.7.0 preview 3.0

**Steps to Reproduce**:

write the following:

```csharp
public class C
{
    public int M(bool b) {
        if (b) return default;
        else throw null;
    }
}
```

Visual studio suggests refactoring this to:

```csharp
public class C
{
    public int M(bool b) {
        return b ? default : throw null;
    }
}
```

Which fails to compile with:

> error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'default' and '<throw expression>'

**Comment by RikkiGibson** [comment]
I suspect the code produced by the refactoring will be valid once target typed conditional #43186 is available. This seems like an interesting scenario to test @gafter.

**Comment by YairHalberstadt** [comment]
This works on the target typed conditional branch on sharplab. Closing.
