### ISSUE TITLE
Opening multiple split C# editors crashes VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46047]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1116222/opening-multiple-split-c-editors-crashes-vs.html)._

---
[regression] [worked-in:Earlier builds of 16.8.0 Preview 1.0]
1. Open a solution with C# in Visual Studio (16.8.0 Preview 1.0, latest IntPreview build)
1a. as a note, my projects are ASP .NET Core 3.1, if that helps
2. Open multiple .cs files
3. Split editor panes, i.e. snap out an editor window, create SxS windows
4. Keep opening C# editors, also try snapping out more editors

**Expected:** VS continues to function normally
**Actual:** after opening and interacting with a few editor tabs, Visual Studio will crash

As a general note, the latest 16.7/16.8 IntPreviews have significantly regressed basic features of Visual Studio. I have already reported issues with essential features of the editor and language service. Now, with this bug, Visual Studio is unusable for my dev work.

---
#### Feedback Bot on 7/16/2020, 10:02 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
```
Event Time (UTC): 7/16/2020 3:51:21 PM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.RemoveUnnecessarySuppressions.AbstractRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer.<AnalyzeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisExecutor.<GetSemanticDiagnosticsAsync>d__11.MoveNext()
```
