### ISSUE TITLE
C# snippet completion does not work above using directives

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4606]
(Copied from internal issue 1180645)
1. Create an C# file containing only 
   
   ``` C#
   <leave one line blank>
   using System;
   ```
2. On the blank line, type "if"

Expected: Snippet completion should kick in, with "if" in the list.
Actual: No snippet completion, only "extern" and "using" offered.

A more realistic use case is a custom "copyright" snippet that inserts a copyright comment.

This fails because the position in question does not satisfy any of the [required contexts](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/SnippetCompletionProvider.cs,100)

**Comment by dpoeschl** [comment]
Note that the snippet expands appropriately, it's just not shown in completion (which of course is enough to break the &lt;tab&gt;&lt;tab&gt; muscle memory). Typing **shortcut&lt;esc&gt;&lt;tab&gt;** can serve as a workaround, but it's definitely worth getting &lt;tab&gt;&lt;tab&gt; working here.

**Comment by dpoeschl** [comment]
Enumerating unacceptable snippet contexts sounds much simpler than enumerating the acceptable contexts.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about this being an issue.  Moving to a new snippet experience entirely.  Need info to justify fixing this.
