### ISSUE TITLE
Useless error message for failed source generator

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#46084]
**Version Used**:  dotnet sdk 5.0.100-preview.6.20318.15

**Steps to Reproduce**:

I'm running a project referencing a source generator on the command line via dotnet build.

It displays the warning:

> CSC : warning CS8785: Generator 'ContainerSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. 

But does not explain why it failed to generate source.

**Comment by YairHalberstadt** [comment]
It appears like there is a catch all in GeneratorDriver which produces this diagnostic:

https://github.com/dotnet/roslyn/blob/ee23aef2b0443df5f7f187ff59907df1a3618ee4/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs#L114-L117

This should probably log the exception that was thrown @chsienki?

**Comment by chsienki** [comment]
Yeah, its on the board to fix :) https://github.com/dotnet/roslyn/projects/54#card-41652943

**Comment by YairHalberstadt** [comment]
Great!

Can I just suggest that this should be really high priority? It's really hard to develop a source generator when you cant even tell what went wrong :-)

**Comment by YairHalberstadt** [comment]
For now I'm doing the following as a workaround:

```csharp
        public void Execute(SourceGeneratorContext context)
        {
            try
            {
                ExecuteInternal(context);
            }
            catch (Exception e)
            {
                //This is temporary till https://github.com/dotnet/roslyn/issues/46084 is fixed
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "SI0000",
                        "An exception was thrown by the StrongInject generator",
                        "An exception was thrown by the StrongInject generator: '{0}'",
                        "StrongInject",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None,
                    e.ToString()));
            }
        }

        //By not inlining we make sure we can catch assembly loading errors when jitting this method
        [MethodImpl(MethodImplOptions.NoInlining)]
        private void ExecuteInternal(SourceGeneratorContext context)
        {
            ...
        }
```

**Comment by chsienki** [comment]
This was implemented as part of https://github.com/dotnet/roslyn/pull/46804

**Comment by afcruzs** [comment]
Hey @chsienki is it possible to make the build fail on this case? I'd love that to make sure these stuff do not go unnoticed and then avoid undefined behavior when this isn't compiled. For example, i'm auto generating test classes via source generator, if this fails the class doesn't get compile and then vstest cannot find the class later, everything "works" except the test is never found :D
