### ISSUE TITLE
Change Signature "Preview Changes" not shown when invoked from lightbulb

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4608]
(Copied from internal bug 977290)
1.       Launch VS;
2.       Create a C# console application;
3.       Open file “Program.cs”;
4.       Add code “void Testing(int i, double d) { }” in class Program;
5.       Click on method “Testing” ;
6.       Invoke “Refactorings” (Alt + .), then click “Change signature” ;
7.       In “Change Signature” dialog  make some changes , check “Preview reference changes” and click “OK”.

Note: It works when Change Signature is invoked from the command.

Another example
[Repro Gif](https://microsoft-my.sharepoint.com/:i:/p/v-rodudi/EZSsaj7t-qJCv4O9cgXC_N0BBAuNR96-FyE0Y65qaMqeMw?e=4qqhYl)

**Comment by davidwengier** [comment]
Ran into this today. Since the original repro GIF is a 404:
![PreviewChangesDoesNothing](https://user-images.githubusercontent.com/754264/89245778-f1c06d80-d64c-11ea-83de-3c688a7ce65d.gif)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
