### ISSUE TITLE
pressing ctrl j to join lines deletes too much from the first line creating problem code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46090]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1116307/pressing-ctrl-j-to-join-lines-deletes-too-much-fro.html)._

```csharp
{
    ....
    var foobar = new foobar
    {
        foo = "foobar"
    };
}

public class foobar
{
    public string foo;
}
```

in the above selecting the lines from var until the ';' and then doing a join results in a missing "r"
```csharp
{
    ....
    var foobar = new fooba { foo = "foobar" };
}

public class foobar
{
    public string foo;
}
```

#### Feedback Bot on 7/17/2020, 01:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't believe roslyn does anything here.  @olegtk Is 'ctrl-j' a core editor feature?

**Comment by olegtk** [comment]
Yes, we added join lines command in 16.6. It's not Ctrl+J by default, but I guess the customer remapped it. I reactivated original feedback ticked and moved it to the editor, feel free to close this issue.

**Comment by CyrusNajmabadi** [comment]
Thanks!
