### ISSUE TITLE
Disable RenameTracking while a snippet session is active

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4611]
(Copied from internal bug 1122588)

In a C# class, type "prop&lt;tab&gt;&lt;tab&gt;", then &lt;tab&gt; to the property's name and change it to "Name".

**Expected**: No RenameTracking outline/lightbulb item.
**Actual**: RenameTracking outline/lightbulb item.

**Comment by CyrusNajmabadi** [comment]
Closing out as not-repro.
