### ISSUE TITLE
Breaking change and spec violation for code using underscore to refer to single lambda parameter

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#46117]
**Version Used**: 16.6.4, [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgAwAEhAjAHQAymAdgI4DcAsAFAeEBMpAwhwDeHUqPIAWUgFkAFAEoRY4ezGrSAenWlAMuT8AysQrEAzKQAqACzil6EMNYDkAfQekAJgHs4UGx5ik4AA9MWFIGUhgrUgBjAFcEBDh6f2iPZKCYRTUNLWy8/ILSQGTCLLUAUXpY+wQIYAAbOCoAJQh6AHM4GWIkUgo5Kj04BuiYGSdSAF5SJyozDz0YBAY2+Tk2FTEAXw5t9iA===) shows it on master

There's a lot of code out there like this:

```cs
using System.Linq;

class C
{
    void M()
    {
        // ❌ CS0103 The name '_' does not exist in the current context
        //                                ↓
        Enumerable.Range(0, 1).Select(_ = _.ToString());
    }
}
```

This doesn't follow the spec in https://github.com/dotnet/csharplang/blob/master/proposals/lambda-discard-parameters.md#detailed-design:

> Note: if a single parameter is named `_` then it is a regular parameter for backwards compatibility reasons.

**Comment by Joe4evr** [comment]
CC: @jcouv This should be covered by the test plan #38820
> * [x]  that a single `_` is not a discard parameter (ie. is in scope and can be read from) (see `DiscardParameters_NotADiscardWhenSingleUnderscore`)

**Comment by jcouv** [comment]
I'm confused. There is no lambda in the example. Did you mean `.Select(_ => _.ToString())` with a `=>`?

**Comment by jnm2** [comment]
Oh my, I'm so sorry! Wow 😆
