### ISSUE TITLE
Delegates cannot use 'var' keyword in switch expressions

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/roslyn#46128]
**Version Used**: 
VS 16.6.4

**Steps to Reproduce**:

1. Type code
```csharp
private void Handler(object sender, EventArgs e)
{
    Action<object, EventArgs> a = xxx switch
    {
        0 => (sender, e) => f1(sender, e),
        1 => (sender, e) => f2(sender, e),
        _ => throw new SwitchExpressionException()
    };

    a(sender, e);
}
```

2. IDE0007 suggests we use the keyword `var` to replace with the explicit type but delegate types should be typed explicitly.

**Expected Behavior**:
Any reports about using keyword `var` cannot be suggested here.

**Actual Behavior**:
IDE0007 suggests.

**Comment by CyrusNajmabadi** [comment]
@allisonchou did you fix this already?  Or was that another switch issue?

**Comment by allisonchou** [comment]
@CyrusNajmabadi, Yep, this should be fixed via #44581. (Also confirmed just now through testing this case with a recent Int Preview.)

Will close out the issue.

**Comment by CyrusNajmabadi** [comment]
great!  Do you think we have adequate test coverage in teh product already?  If so, nothing else to do here.  If not, could you create a test so this doesn't regress?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Looking at your PR, i don't see it testing a delegate type. i think it would be a good idea to have a dedicated test for that as they're often special.  Can you add one @allisonchou ?

**Comment by allisonchou** [comment]
@CyrusNajmabadi sure thing! I'll get out a PR by today with an applicable test.
