### ISSUE TITLE
Convert For Each to LINQ not working in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46134]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1108715/convert-for-each-to-linq-not-working-in-vb.html)._

---
This is for current production version of VS2019 16.6.3. 

The Quick Action "Convert For Each To LINQ" does not display as is expected according to this reference:
https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019

---
#### Feedback Bot on 7/10/2020, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by 06needhamt** [comment]
I'm sure that it could be extended to VB relatively easily.

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be changing these experiences.
