### ISSUE TITLE
Compiler exception triggered by Null Propagation Operator in combination with Conditional attribute

### ISSUE THREAD

**Issue by wmrutten** [dotnet/roslyn#4615]
Using the Null Propagation Operator (introduced in C# 6) to call a method that is decorated with the Conditional attribute triggers an exception in the compiler if the condition is false (i.e. if the specified compiler constant has not been defined).

Example:

    class Program
    {
        static void Main(string[] args)
        {
            TestClass obj = null;
            obj?.Test();
        }
    }

    class TestClass
    {
        [Conditional("DUMMY")]
        public void Test() { }
    }

The same issue has also been submitted to Microsoft Connect:
https://connect.microsoft.com/VisualStudio/feedback/details/1682845

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
