### ISSUE TITLE
VB Code inside Roslyn can't use latest VB features

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#46157]
**Version Used**: 
VS Version 16.7.0 Preview 4.0
Roslyn Master 7/20/2020
**Steps to Reproduce**:
Open any VB File on insert _ ' Test on any line before a space, example below
![image](https://user-images.githubusercontent.com/12789369/88011914-6633d200-cacd-11ea-9430-bbefff7ff36c.png)

**Expected Behavior**:
No error
**Actual Behavior**:
Error BC37306
This does not happen on other VB projects

**Comment by jmarolf** [comment]
Looks like we'd want to change this to be `16`

https://github.com/dotnet/roslyn/blob/f2c37426851df7ea6a9fa77137960cc40a9d9dd7/eng/targets/Settings.props#L173

**Comment by paul1956** [comment]
I will fix and add test @davkean

**Comment by davkean** [comment]
@jmarolf That's version number is for this repostory, not for VB projects in general.

**Comment by davkean** [comment]
@paul1956 Wasn't the problem that VB WinForms applications also didn't get 16.0?

**Comment by paul1956** [comment]
VB16 is the default for any version of VS that could support Core5, Roslyn Overrides that and sets it to 15.5. There were features added to 15.8 which was never released as a public version and 2 features added to 16. With the change in #46170 Roslyn supports VB features post 15.5, there is some code/setting in #3352 that expect VB16.

**Comment by davkean** [comment]
Oh I'm confused. I thought this comment (and why I was tagged) was in reference to https://github.com/dotnet/winforms/pull/3352. 

Now I don't understand why I'm tagged in this bug?

**Comment by paul1956** [comment]
@davkean it is, you asked for a bug to be filed and I did. With this fix you don't need to specify LangVersion in dotnet/winforms#3352.

**Comment by davkean** [comment]
I'm extremely confused. Above and the PR is talking about using 16.0 version of VB inside the Roslyn code base itself. The WinForms bug is baout

**Comment by paul1956** [comment]
@davkean I think I now understand the confusion, in Roslyn Settings.props sets LangVersion to 15.5, if the same things is happening in WinForms that would be a separate bug.  Code outside Roslyn or code that just uses the default settings on a project in Visual Studio gets VB16 without doing anything when running on VS2017, no Language Version needs to be specified in vbproj file. If any code in Roslyn wants to use any feature added after 15.5 (there are at least 3) then this fix is needed.

**Comment by CyrusNajmabadi** [comment]
Thanks @paul1956 !
