### ISSUE TITLE
Checksum calculation depends on temporary storage

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#46166]
Currently our checksum calculation uses `ObjectWriter` to serialize objects to a stream, and then calculates a hash for the stream contents. For objects written by reference (e.g. `ITemporaryStorageWithName`), this results in a checksum value that depends on the _storage location_ of the objects, as opposed to depending on the _content_ of the objects.

📝 This issue has existed for a while, but was discovered when ObjectWriter keep alive support was added. See https://github.com/dotnet/roslyn/pull/45953#discussion_r454562468.

⚠️ The "obvious" solution here is disabling keep alive support for checksum calculation. However, this may result is larger memory allocations during checksum calculation which could impact product performance metrics.

**Comment by CyrusNajmabadi** [comment]
Closing out as thing don't work this way anymore.
