### ISSUE TITLE
Reproducible VS crash when writing a foreach statement with tuple type inference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46165]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1117216/reproducible-vs-crash-when-writing-a-foreach-state.html)._

---
When typing the following start of a line of C# code, VS crashes reproducibly (bold is what I type, italic has been added by auto closing of braces):

**foreach ((var i, i**_))_

As soon as I enter the second 'i', VS stopps responding and crashes a few seconds after. I tried this at multiple locations in the code. The result remained the same.

---
#### Feedback Bot on 7/19/2020, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
This crash is also present in VS 2017.
