### ISSUE TITLE
RuleSetEventHandler has potentially buggy/dead code around old and new ruleset paths

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46168]
See https://github.com/dotnet/roslyn/pull/45989/commits/ded0e4a71e3781178010fc6533001979d59679a8#diff-6ec9914571b4bd3ad6e2dd07d693576eR189

It seems quite a bit of cleanup can be done in this file when we remove all unused parameters and value assignments

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
