### ISSUE TITLE
Code style settings

### ISSUE THREAD

**Issue by Novakov** [dotnet/roslyn#4616]
There are different code style: some people like to place private before fields, others don't. Sometimes every field begins with `_` or `m_`.

With Roslyn it is easy to write tools that will help developers by generating some code (like initialize field from ctor parameter). 

The problem is that these tools assume style which may not be the same as style used in project, so every refactoring/code fix will require additional work to adjust code to desired style (for example: add `private` modifier and `_` prefix after generating field from ctor parameter) which is, at least, annoying. 

From perspective of developers, it will be great if code style settings could be defined apart from any specific extension, so 3rd party refactorings will simply use defined style to generate code.

**Comment by sharwell** [comment]
Related to #7064
