### ISSUE TITLE
Remove SDK work around when upgrading to .NET 5 P7

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#46182]
Had to introduce a workaround in our build for the following SDK issue. The work around is labeled with this issue and can be removed when we upgrade to P7.

https://github.com/dotnet/sdk/issues/11862

**Comment by RikkiGibson** [comment]
I wasn't able to find any references to this issue in the current source tree. I assume this has already been addressed. Feel free to follow up if I was mistaken.
