### ISSUE TITLE
Use Refactorings and Analyzers infrastructure by another language

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#4618]
If to implement a language specific assemblies for another language
For example `Microsoft.CodeAnalysis.FSharp` and `Microsoft.CodeAnalysis.FSharp.Workspaces`
Will Refactorings and Analyzers infrastructure work for that language?

**Comment by gafter** [comment]
No, it won't.

**Comment by xperiandri** [comment]
Cool! Do you have any advice about how to do this?
Maybe where to start, which source files to look first.

**Comment by gafter** [comment]
`Microsoft.CodeAnalysis.CSharp` implements the code analysis APIs for clients using the C# language, and also has a bunch of C#-specific APIs.

`Workspace` is the name of an API. We put the CSharp-specific implementations in a CSharp namespace, and the same for VB.

It took us a bunch of really smart software engineers working on it full-time for a few years to get to the point we are today. My advice would be to do the same.

**Comment by xperiandri** [comment]
I understand that it is a bunch of work of the best engineers.
So I don't need all the stuff.
I want to understand how much effort is to implement a minimum.
Minimum for me is ability to run 1 simplest refactoring.

**Comment by gafter** [comment]
I suggest you write a simple refactoring and use the debugger to single-step through it as it operates to get a feel for how much code is involved.

**Comment by xperiandri** [comment]
Can I do this with disabling Just My Code or I need to compile Roslyn and use my compiled version?

**Comment by paul1956** [comment]
I would love if someone could document exactly how to "use the debugger to single-step through it as it operates". I have created a refactoring as a separate VSIX project, and getting it to find symbols and source is beyond me.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by gafter** [comment]
I suggest you get Roslyn source and build it. Find some refactoring unit test that applies some fix. Then run the test and single-step in it. You may need to install TestDriven.NET to get the ability to run a single test under the debugger. Navigate to the source of the test, set a breakpoint on its first statement, right-click, and select "Test With -> Debugger"

**Comment by paul1956** [comment]
The problem lies in the fact that I can't successful build Roslyn Master from GitHub, either on Windows 10 or Azure VM Visual Studio Enterprise Rel image. Different errors on both OSs reported in other issues, plus all my refactorings are written in VB.

**Comment by gafter** [comment]
After installing VS2015, and getting a fresh repo, try

```none
.\cibuild
```

in a shell.

**Comment by paul1956** [comment]
Got latest Master
..\cibuild
and I got the following errors.

C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Services.UnitTests.d
ll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Services.UnitTests.d
ll.config
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Services.UnitTests.p
db
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Services.VisualBasic
.UnitTests.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Services.VisualBasic
.UnitTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Con
trol.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Con
trol.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Con
trol.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Dgm
lHelper.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Dgm
lHelper.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.SyntaxVisualizer.Dgm
lHelper.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.PdbUtilities.dl
l
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.PdbUtilities.pd
b
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.Deskt
op.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.Deskt
op.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.dll.c
onfig
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.FX45.
dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.FX45.
pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.Test.Utilities.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualBasic.Interact
iveEditorFeatures.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualBasic.Interact
iveEditorFeatures.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
Repl.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
Repl.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
Repl.pkgdef
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
Repl.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
UnitTests.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
UnitTests.dll.config
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.CSharp.
UnitTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Diagnos
ticsWindow.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Diagnos
ticsWindow.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Diagnos
ticsWindow.pkgdef
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Diagnos
ticsWindow.vsix
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tive.Setup.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tive.Setup.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tive.Setup.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveComponents.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveComponents.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveComponents.vsix
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveServices.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveServices.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Interac
tiveServices.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Service
s.UnitTests.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Service
s.UnitTests.dll.config
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Service
s.UnitTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.d
ll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.I
nteractive.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.I
nteractive.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.I
nteractive.vsix
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.I
nteractive.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.p
db
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.p
kgdef
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.v
six
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.Setup.x
ml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.VisualB
asic.Repl.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.VisualB
asic.Repl.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.VisualB
asic.Repl.pkgdef
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\Roslyn.VisualStudio.VisualB
asic.Repl.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\RunTests.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\RunTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\stdole.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Collections.Immutabl
e.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Collections.Immutabl
e.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Attribut
edModel.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Attribut
edModel.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Conventi
on.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Conventi
on.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Hosting.
dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Hosting.
xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Runtime.
dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.Runtime.
xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.TypedPar
ts.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Composition.TypedPar
ts.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.IO.FileSystem.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.IO.FileSystem.Primit
ives.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Reflection.Metadata.
dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Reflection.Metadata.
pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Reflection.Metadata.
xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.Co
mmon.props
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.dl
l
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.pd
b
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.Un
itTests.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.Un
itTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.Analyzers.xm
l
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.CSharp.Analy
zers.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.CSharp.Analy
zers.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.CSharp.Analy
zers.props
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.CSharp.Analy
zers.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.Common.props
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.UnitTests.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.UnitTests.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.Analyzers.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.CSharp.Analyzers.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.CSharp.Analyzers.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.CSharp.Analyzers.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.VisualBasic.Analyzers.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.VisualBasic.Analyzers.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.InteropServi
ces.VisualBasic.Analyzers.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.VisualBasic.
Analyzers.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.VisualBasic.
Analyzers.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.VisualBasic.
Analyzers.props
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\System.Runtime.VisualBasic.
Analyzers.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.exe.config
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.rsp
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.vshost.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.vshost.exe.manifest
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc2.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc2.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbc2.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBCSCompiler.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBCSCompiler.exe.config
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBCSCompiler.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBCSCompiler.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBErrorFactsGenerator.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBErrorFactsGenerator.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbi.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbi.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbi.vshost.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbi.vshost.exe.manifest
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\vbi.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBSyntaxGenerator.exe
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBSyntaxGenerator.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBSyntaxGenerator.vshost.ex
e
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VBSyntaxGenerator.vshost.ex
e.manifest
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj140.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj2.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj2.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj80.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VSLangProj80.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\VsWebSite.Interop.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.abstractions.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.abstractions.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.assert.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.assert.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.assert.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.core.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.core.pdb
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.core.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.execution.desktop.dll

C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.extensions.dll
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.extensions.xml
C:\Users\Paul\Documents\GitHub\roslyn\Binaries\Debug\xunit.xml
      590 file(s) moved.

C:\Users\Paul\Documents\GitHub\roslyn>msbuild /v:m /t:Clean build/Toolset.sln /p
:Configuration=Debug
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\Paul\Documents\GitHub\roslyn\build\Toolset.sln.metaproj : error MSB412
6: The specified solution configuration "Debug|MCD" is invalid. Please specify
a valid solution configuration using the Configuration and Platform properties
(e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or
 leave those properties blank to use the default solution configuration. [C:\Us
ers\Paul\Documents\GitHub\roslyn\build\Toolset.sln]

C:\Users\Paul\Documents\GitHub\roslyn>taskkill /F /IM vbcscompiler.exe
ERROR: The process "vbcscompiler.exe" not found.

C:\Users\Paul\Documents\GitHub\roslyn>msbuild /v:m /m /p:BootstrapBuildPath=C:\U
sers\Paul\Documents\GitHub\roslyn\\Binaries\Bootstrap BuildAndTest.proj /p:Confi
guration=Debug
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

  Installing 'xunit.runners 2.0.0-alpha-build2576'.
  Successfully installed 'xunit.runners 2.0.0-alpha-build2576'.
  All packages listed in packages.config are already installed.
  Installing 'xunit.extensions 1.9.2'.
  Installing 'Moq 4.2.1402.2112'.
  Successfully installed 'xunit.extensions 1.9.2'.
  Successfully installed 'Moq 4.2.1402.2112'.
  Installing 'xunit 1.9.2'.
  Successfully installed 'xunit 1.9.2'.
  All packages listed in packages.config are already installed.
C:\Users\Paul\Documents\GitHub\roslyn\Roslyn.sln.metaproj : error MSB4126: The
specified solution configuration "Debug|MCD" is invalid. Please specify a valid
 solution configuration using the Configuration and Platform properties (e.g. M
SBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave
those properties blank to use the default solution configuration. [C:\Users\Pau
l\Documents\GitHub\roslyn\Roslyn.sln]

C:\Users\Paul\Documents\GitHub\roslyn>if ERRORLEVEL 1 (
taskkill /F /IM vbcscompiler.exe
 echo Build failed
 exit /b 1
)
ERROR: The process "vbcscompiler.exe" not found.
Build failed

C:\Users\Paul\Documents\GitHub\roslyn>

**Comment by xperiandri** [comment]
@paul1956, could you rewrite your message with code quotes so that it was not so long?

**Comment by xperiandri** [comment]
@gafter, do we need to build it only the way `.\cibuild` and not in Visual Studio?
So do I need to connect my build of Roslyn to new separate instance of Visual Studio 2015 (instructions in this repo) to be able to step through?

**Comment by paul1956** [comment]
@xperiandri if you tell me how

I think the actual error is
C:\Users\Paul\Documents\GitHub\roslyn>taskkill /F /IM vbcscompiler.exe
 ERROR: The process "vbcscompiler.exe" not found.

**Comment by xperiandri** [comment]
Just put it into triple ` at the beginning and at the end.
[Examples\Code](https://guides.github.com/features/mastering-markdown/)

So I just fetched all, checked out master and did what @gafter suggested and it build.

**Comment by paul1956** [comment]
Using Visual GitHub I did a "discard all changes" followed by a .\cibuild on Windows 10 and got the following errors, doing the exact same thing on a New Microsoft Azure VM with VS 2015 Enterprise preinstalled worked as expected and this was the first time it worked for me..
![capture](https://cloud.githubusercontent.com/assets/12789369/9382409/62bbee98-46f5-11e5-9921-ac6db008988c.JPG)

**Comment by xperiandri** [comment]
Checkout origin\master

**Comment by gafter** [comment]
@paul1956 Please create a new issue for your build problems. We're too far afield of the original question for us to treat it as the same issue. In addition, the OP was indeed able to build following my instructions.

**Comment by xperiandri** [comment]
So...
@gafter, do we need to build it only the way  .\cibuild  and not in Visual Studio?
Do I need to connect my build of Roslyn to new separate instance of Visual Studio 2015 (instructions in this repo) to be able to step through?

**Comment by gafter** [comment]
@xperiandri I wasn't trying to exhaustively list all of the ways you might build Roslyn, but rather provide a single way that should work consistently. After building this way you should be able to open Roslyn.sln in VS2015 and start running/stepping through it.

**Comment by xperiandri** [comment]
Good, thanks.

**Comment by xperiandri** [comment]
@gafter, which project do I need to run?
Do I need to open complete Roslyn solution or I can take smaller solution for my purposes?

**Comment by gafter** [comment]
I suggest making or finding a unit test that tests something you want to trace, and debugging through a run of the unit test.

I use the full Roslyn solution, but I expect you could use one of the smaller ones.

**Comment by xperiandri** [comment]
Got releases/2015
cibuild
Then added xunit.runner.visualstudio NuGet to CSharpEditorServicesTest

'
------ Discover test started ------
NUnit Adapter 3.0.2.0 discovering tests is started
NUnit failed to load C:\Users\Андрій\Dev\Microsoft\roslyn\Binaries\Debug\Roslyn.Services.Editor.CSharp.UnitTests.dll
NUnit Adapter 3.0.2.0 discovering test is finished
[xUnit.net 00:00:00.9755246] Skipping: Roslyn.Services.Editor.CSharp.UnitTests (could not find dependent assembly 'Microsoft.CodeAnalysis, Version=42.42.42')
========== Discover test finished: 0 found (0:00:06,8190734) ==========
'

What is wrong?
@gafter, how do you run tests from within Visual Studio?

**Comment by xperiandri** [comment]
<img width="305" alt="xunit" src="https://cloud.githubusercontent.com/assets/2365592/9558234/ebbd2142-4deb-11e5-8c2f-d9fe42091c03.png">
