### ISSUE TITLE
Use MEF v2 for request handlers so we can use content type

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#46195]
Brought up in https://github.com/dotnet/roslyn/pull/46149 - we should be able to export request handlers for a content type rather than adding the language name property (since the LSP server is exported for content type).

**Comment by CyrusNajmabadi** [comment]
@dibarbet anything left to do here?

**Comment by dibarbet** [comment]
Closing - I don't think using content type here actually benefits us at this point.  It's not exactly the right abstraction we want.
