### ISSUE TITLE
Naming rule for optional prefix

### ISSUE THREAD

**Issue by Shayan-To** [dotnet/roslyn#46205]
I want my private field to be either `camelCase` or `_BeginWithUnderscorePascalCase`. Can that be done?

If not, I want them to be either `PascalCase` or `_BeginWithUnderscorePascalCase`. But I couldn't manage that. It either gives me errors about unexpected prefixes, or about missing ones.

**Comment by Shayan-To** [comment]
Any reply?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
