### ISSUE TITLE
.NET Core app can't handle .NET 4.7.2 projects with old-style csproj

### ISSUE THREAD

**Issue by markrendle** [dotnet/roslyn#46228]
**Version Used**: Microsoft.CodeAnalysis.Workspaces.MSBuild 3.6.0 in a .NET Core 3.1 application

**Steps to Reproduce**:

1. Use `MSBuildLocator` to register VS2019.6 MSBuild
2. Load a solution containing a .NET 4.7.2 (WCF) project with `MSBuildWorkspace`
3. Get an `INamedTypeSymbol` for a type in the project
4. Get the `AttributeData` for the symbol

**Expected Behavior**:

I hoped that `MSBuildWorkspace` would successfully load the solution and provide full semantic models.

**Actual Behavior**:

The solution loads but the semantic models are broken. All BCL types are of `ErrorTypeSymbol`.

The `WorkspaceDiagnosticEventArgs` argument from the `WorkspaceFailed` event contains this message:

```
Msbuild failed when processing the file 'D:\ReCode\Samples\Hotel\Hotel\Hotel.csproj' with message: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets: (1489, 5): 
The "AssignProjectConfiguration" task could not be instantiated from 
"Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Method not found: 'Byte[] System.AppDomainSetup.GetConfigurationBytes()'.
```

This is the code the app is trying to work with:

```csharp
namespace Hotel
{
    [ServiceContract]
    public interface IHotelService
    {
        [OperationContract]
        IList<Room> GetAvailableRooms(DateTimeOffset checkInDate, DateTimeOffset checkOutDate);

        [OperationContract]
        Room GetRoom(int number);

        [OperationContract]
        Room[] GetRooms(int[] numbers);

        [OperationContract]
        IEnumerable<Room> AllRooms();
    }
}
```

I can get the `INamedTypeSymbol` for `IHotelService` OK, but the symbol for `ServiceContract` from `GetAttributes()` is not resolved correctly.

Is there a workaround to get this to work, or might it start working in .NET 5 perhaps?

**Comment by jmarolf** [comment]
A few questions:

1. Are you a .NET Core app trying to load a .NET Framework project?
2. Did you register a worspace failed event handler like below? If so what does it output?
```csharp
// Print message for WorkspaceFailed event to help diagnosing project load failures.
workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);
```

**Comment by markrendle** [comment]
@jmarolf 

1. Yes, it's an ASP.NET Core 3.1 app
2. I included the output from the `WorkspaceFailed` event above.

```
Msbuild failed when processing the file 'D:\ReCode\Samples\Hotel\Hotel\Hotel.csproj' with message: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets: (1489, 5): 
The "AssignProjectConfiguration" task could not be instantiated from 
"Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Method not found: 'Byte[] System.AppDomainSetup.GetConfigurationBytes()'.
```

Also, when I get the `Compilation` diagnostics from the actual project, it includes all the messages about not being able to resolve `System.Object` and suchlike.

**Comment by jmarolf** [comment]
So here's what is happening:
1.  your ASP.NET Core 3.1 app is calling into MSBuildWorkspace to load the project
2.  MSBuildWorkspace uses msbuild to try and resolve a compilation (hence the name) but does so inside your .NET Core App
3. The `Microsoft.Common.CurrentVersion.targets` file attempts to load the `AssignProjectConfiguration` from a dl that was built against .NET Framework into you .NET Core app
4. Loading framework dlls into core is something that _might_ work but in this case it has a dependency on a framework type that does not exist in .NET Core

MSBuild is rather complex and part of its design is that you can load arbitrary tasks from a dll. If you are a .NET Core app and attempt to load a .NET Framework dll things will fail more often than not.

If the app that loads the project file was .NET Framework I would expect things to succeed.

**Comment by markrendle** [comment]
@jmarolf OK, that makes sense I guess. Thanks.
