### ISSUE TITLE
Null check in positional pattern is disregarded

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#46223]
**Version Used**: 16.6.5, master on [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AxAHYCuANuRMOXAARzHW0CwAUOwAIBMdAwuwDe7OqLqZiMOgFkAFBJgB+OgA8AlCLHC2Y3XU4B2OrIAs3JKrV0oAd0wwAxgAtNeutrdvZAfQtlKVgC8AHx0ZkiunqIA9NH8AMoAHABs3ACcdAByFFQ09GgQ5KT0MLgADvSQuHTA9P7kAHSRUbFRgMmEzZ4+Ft5BoSoNAGqFxRE6ngC+ANyRE+wTQA)

There should be no warning:

```cs
#nullable enable

class C
{
    int M(int? x)
    {
        return (42, x) switch
        {
            (_, null) => 42,
            // ⚠ CS8629 Nullable value type may be null.
            //        ↓
            (_, _) => x.Value,
        };
    }
}
```

The same null check, but no longer inside a positional pattern, correctly not warning:

```cs
#nullable enable

class C
{
    int M(int? x)
    {
        return x switch
        {
            null => 42,
            _ => x.Value,
        };
    }
}
```

**Comment by jcouv** [comment]
FYI @gafter

**Comment by alrz** [comment]
```cs
#nullable enable

class C
{
    int M(int? x)
    {
        return (42, x) switch
        {
            (_, not null) => x.Value,
            _ => 0,
        };
    }
}
```
Relates to https://github.com/dotnet/roslyn/issues/44534

**Comment by gafter** [comment]
This is by design. The tuple expression makes a copy of x, and that copy is what is being switched upon. We don't track the relationship between x and that copy of x. That is, we don't track the fact that when one is null (or not null), the other must also be so.

**Comment by jnm2** [comment]
Wouldn't tracking this be a desirable state to be in? Thinking about pattern matching in terms of copies in the implementation isn't intuitive.

**Comment by gafter** [comment]
@jnm2 If you have a language proposal, please make it in `csharplang`.
