### ISSUE TITLE
Why do all formatting errors have code IDE0055?

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#46243]
The `.editorconfig` formatting rules allow quite a varied (and increasing) number of configuration options as to exactly how code should be formatted.  It seems quite likely that one would want to have different warning levels for the various different formatting issues, and sometimes want to outright suppress some by setting their severity to 'none'.  However this can't be done as long as they all throw up the code IDE0055.  Why not have different error codes for the different formatting issues to allow more fine-grained control?

**Comment by CyrusNajmabadi** [comment]
> Why not have different error codes for the different formatting issues to allow more fine-grained control?

Because the formatter has no concept of associating formatting operations with specific errors/rules.  So there's no way for an the analyzer to say "this code is wrongly formatted because of this particular formatting rule, thus i will give this particular error id".

**Comment by jez9999** [comment]
Right, but why not introduce the ability for the formatter to have that concept and throw up different codes based on the different rules?

**Comment by CyrusNajmabadi** [comment]
Likely because it would add a lot of complexity.  There are probably many many locations in the formatting engine that do not necessarily break down on this fashion, or which are governed by a complex set of interactions of many subpieces of it.  It's also unclear what the performance implications of this would be as the formatter is very perf sensitive and we have to be careful to not regress that.

**Comment by jmarolf** [comment]
CC: @mikadumont fyi

**Comment by sharwell** [comment]
The current formatter rules architecture makes it essentially impossible to provide this. The implementation behaves more like a constraint solver than a set of distinct style validators.

**Comment by marcospgp** [comment]
If you're signaling an error, you must know what caused the signaling, no? You would know which constraint was crossed?

**Comment by JoeRobich** [comment]
The application of formatting rules is separate from the generation of these diagnostics. These diagnostics are produced by fully formatting the document in memory, diff'ing against the current document, and producing diagnostics at each changed span. Currently there is no link between the changed span and which rule or rules modified it.

**Comment by marcospgp** [comment]
I am a bit lost as to what rule is being broken here:

![image](https://user-images.githubusercontent.com/3464445/127402026-c99f228e-57b6-4ed6-819d-4ba42650e792.png)

It seems if I move the comments to the same line as the previous statement the error no longer appears:

![image](https://user-images.githubusercontent.com/3464445/127402096-8dabbc3c-f1d5-4763-a45c-c058ea72bf86.png)

I have tried changed around various space, indentation, even experimental rules, to no avail. Any help is super appreciated.

**Comment by CyrusNajmabadi** [comment]
Can you provide a repro project for us to look at?

**Comment by marcospgp** [comment]
@CyrusNajmabadi I just sent you an invite to the repo where this is happening. Please let me know if I should invite anyone else!

**Comment by marcospgp** [comment]
I managed to filter the issue down to `indent_style = tab` in my `.editorconfig`. If I change it to `space`, the comments no longer cause the errors to be reported.

Surprised to not see any reference of this (pretty basic) issue on the web. Maybe using tabs for indentation is not a popular configuration?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I just sent you an invite to the repo where this is happening. Please let me know if I should invite anyone else!

hrmm... i'm not sure i got it.  Can you link me to the repo?  Thanks!

**Comment by marcospgp** [comment]
@CyrusNajmabadi This is the repo: https://github.com/marcospgp/dead-drive

**Comment by marcospgp** [comment]
@CyrusNajmabadi Did you manage to access the repo?

**Comment by marcospgp** [comment]
@CyrusNajmabadi still unable to use tabs for indentation 🙂

**Comment by sharwell** [comment]
> still unable to use tabs for indentation

@marcospgp Can you file a new issue for this? It's unrelated to the current issue, which is no longer being updated.
