### ISSUE TITLE
With expressions for generic types

### ISSUE THREAD

**Issue by MCGPPeters** [dotnet/roslyn#46249]
``` c#
public abstract record R
{
   ...
}

public record S : R
{
   ...
}

public abstract class C<T> where T : R
{
   ... when doing a 'with' expression here for any type S, it will not work, since R is considered to be a class
}
```

Is there any workaround? Or would you need a 'record' generic type constraint?

**Comment by jcouv** [comment]
Tagging @AlekseyTs to advise.

I agree this should work. The question is how to fix up the language [spec](https://github.com/dotnet/csharplang/blob/master/proposals/records.md#with-expression) to justify it.

Maybe we spec it as a [method invocation](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#method-invocations) of `receiver.<Clone>$()` with some additional validation (expected return type, no extension method, zero parameters)?

From an implementation perspective, it would look like what we do for `Deconstruct` methods (see `MakeDeconstructInvocationExpression`), where we use `BindMethodGroupInvocation` and then validate the method that was found.

**Comment by AlekseyTs** [comment]
I do not think we need to do anything with the spec, T is a record given the type constraint. The bind method simply should be adjusted to look for the clone method in EffectiveBaseClass when the receiver is a type parameter.

**Comment by jcouv** [comment]
Another related scenario is using `with` on a type parameter constrained to an interface. We'll clarify expectations with LDM.

```
record R;

interface I
{
    int Property { get; set; }
}

class C
{
     void M<T>(T t) where T : R, I
     {
         _ = t with { Property = 42 } ; // should this work?
     }
}
```
