### ISSUE TITLE
Navigate directly to method in class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46267]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1111988/navigate-directly-to-method-in-class.html)._

---
I use quick navigate a lot. It problably is one of the most used features in Visual Studio.

There is just one thing missing. If I want to navigate to a (static) method in a class. I need to navigate first to the class before I before the needed options are availible in a short list.

When I try no navigate directly, the order just isn't working the way I like. In the sceenshot I've highligted the methods I would have expected first.

---
#### Feedback Bot on 7/15/2020, 00:57 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
The picture:

![image](https://user-images.githubusercontent.com/4564579/88337462-9fe22400-cceb-11ea-945f-16e10ac871ba.png)

We should just fix thsi.  That's an exact match on all dimensions, so it should beat an inexact match.
