### ISSUE TITLE
Improve navigational features in VS2019 class diagram

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1102607/improve-navigational-features-in-vs2019-class-diag.html)._

---
<p>The class diagram for VS2019 is okay, but it's not that useful. Currently, it's just a static diagram that you print out and hang up on a wall. I can't imagine a more useless tool if regulated to just that. It really should be used as a *navigational aide* between the diagram and code (C#).</p> <p>It seems like you understand this, but you only offer one navigation: double-clicking on a class, field, method or property in the class diagram navigates to the code. Here are some suggestions:</p><p>1) In a code buffer, right-click on the text for a class, field, method, or property symbol, and pop-up a context menu where you offer &quot;go to symbol in class diagram&quot;. This should select the object in the class diagram, center it, resize the view to the symbol in the diagram. If the object is collapsed, then expand it.</p> <p>2) Note, navigating from a symbol in the class diagram should navigate to the named symbol, select it, just as &quot;go to declaration&quot; in a code buffer navigates to the symbol and selects it. It should not go to the beginning of the declaration. Do not be inconsistent.</p> <p>3) &quot;Find&quot; (Control-F) for a class diagram should be supported. Once &quot;found&quot;, you need to provide a way to center and scale the viewport to the focus in the class diagram.</p> <p>--Ken</p><p></p>

---
#### Feedback Bot on 7/6/2020, 02:01 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
I don't believe class-diagram is supported or maintained.  @jinujoseph do you know what team is responsible for this component currently?

**Comment by mikadumont** [comment]
I found their area path. I will go ahead and close this and route it in azdo
