### ISSUE TITLE
Explicit cast options in intellisense in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46266]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1119860/explicit-cast-options-in-intellisense-in-c.html)._

---
<p>It would be good to see explicit cast options in intellisense next to methods, properties, etc. For example:</p><p>I type:</p><pre>var x = 22;
var ux = x.</pre> <p>Then intellisense would present options: (UInt32), (byte)...</p> <p>After selecting (byte) option, then (byte) would be inserted before expression and dot would be removed.</p> <pre>var x = 22;
var ux = (byte)x</pre><p>Another example:</p><pre>var xDoc = XDocument.Load(...); <br>var created = xDoc.RootElement.Attribute(&quot;create&quot;).</pre> <p>and intellisense would provide options: (int), (DateTime), (string), etc.</p> <p><strong>Reasoning</strong></p><p>XAttribute and XElement provide explicit cast operators to read values from XML, e.g. numbers, date and time. And casting is the most correct way to read those values, because they conform to XML Schema standard. However, lot of people don't know this feature and they use int. Parse or similar. New intellisense option would make it more visible that there is another approach.</p>

---
#### Feedback Bot on 7/20/2020, 10:39 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Yes, i think we shoudl consider doing this.

**Comment by CyrusNajmabadi** [comment]
Mini speclet:

1. Given a `<dot>` invoked off of an expression of type T.  
2. Examine all the members on T and it's base types.
3. For accessible instance indexers, add `this[arg-types]` to the list.  hitting `<tab>` should insert `[]` with teh caret between teh braces, and should remove the `<dot>`.   Hitting undo should return you to `expr.`
4. for accessible conversions that are applicable to this type, add `(conversion-type)` to the list.  hitting `<tab>` should add the `(conversion)` cast before the expression, and remove the `<dot>`.

We hopefully do not have to special case teh primitive types.  ideally the language model exposes the above in their symbol table.  If not, we may have to hardcode this in.

Open questions.  Do we support operators?  We could do so like so:
5. for accessible binary operators that this expr applies to the LHS, add `operator op(...)` to the list.  hitting `<tab>` should add `op` after the expression, and remove the `<dot>`
6. the same should hold for prefix/postfix unary ops.

**Comment by CyrusNajmabadi** [comment]
We are interested in pursuing this.  We would also take a community PR here.  Our expectation though is that this will likely need a few iterations of experimentation to let the team decide if this feels ok or not.  A few important points:

1. we likely should have the conversions/indexers/operators placed at the bottom of completion to not bog down the normal list or make the normal list of of identifiers harder to scan.
2. we should not change teh commit characters for normal completion.  So if a user types `.(` that should still commit an existing preselected item.
3. We shoud only support user-defined conversions in the list, ncluding the representation-changing conversions on primitive language types (i.e. long->int).  We should not present normal reference conversions in the list.  i.e. `o.` should not list ever reference conversion from object to every other type out there.
