### ISSUE TITLE
Add an option to disable Visual Studio Event Handler suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46275]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1107924/add-an-option-to-disable-visual-studio-event-handl.html)._

---
<p>I found that when I am trying to attach an event handler and I type += VS2019 will offer an event handler name and (Press TAB to insert). I'd like to turn this off, but I cannot find any setting in intellisense to configure it.</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/145523-vs-event-handler1.png"> Image:145523-vs-event-handler1.png</a></p><p><a href="https://i.stack.imgur.com/1OEBg.png"><a> Image:https: i.stack.imgur.com=</a><a> Image:https: i.stack.imgur.com=</a></a></p><p>What setting controls this behavior? I'd like to disable it.</p><p></p><p>If the option to disable it doesn't exist, please add it.</p>

---
#### Feedback Bot on 7/9/2020, 11:16 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jmarolf** [comment]
Design Review:
- Won't Fix
