### ISSUE TITLE
In foreach loops, automatically (in debug) add variables that would give iteration # and total iterations planned

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46272]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1117708/in-foreach-loops-automatically-in-debug-add-variab.html)._

---
<p>foreach(var whatever in whateverlist)</p><p>Give me something that I can use inside this foreach that tells me the total # of items I'm iterating over and the # iteration I'm on.</p> <p>I could use it like this: Console.WriteLine($&quot;{currItemNumber}/{currTotalItems}&quot;); or something like that.</p>

---
#### Feedback Bot on 7/19/2020, 11:30 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Not something roslyn would provide.
