### ISSUE TITLE
Improve "Add file banner"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46277]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1110839/improve-add-file-banner.html)._

---
I use as file banner in VB.NET projects fragment (one for the whole project) that looks like

```
REM Product name

REM (c) Autor Year
```

Function "Add file banner" recognize as file banner only first comment and empty line after.
I presume that more logical behavior is to recognize as file banner all comments and empty lines, I mean lines before first line that contains XML-comment (`''' <summary>`, etc), attribute (`<Serializable>`, etc) or statement (`Class`, `Module`, etc).

---
#### Feedback Bot on 7/13/2020, 10:49 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out.  There doesn't appear to be enough feedback indicating this is a pattern worth supporting on our end.
