### ISSUE TITLE
Button or link to show overloads of method.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46271]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1117748/button-or-link-to-show-overloads-of-method.html)._

---
<p>Hi, Is there any chance for visual studio to make the + 〇 overloads clickable or someother way to simply show the overloads. At least I think it should be able to do by some mouse click.</p><p></p><p><a href="https://stackoverflow.com/questions/9891656/visual-studio-how-to-show-overloads-in-intellisense">https://stackoverflow.com/questions/9891656/visual-studio-how-to-show-overloads-in-intellisense</a></p><p>And I think the shortcut for this is really hard to remember and type.</p>

---
#### Feedback Bot on 7/19/2020, 11:30 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
@CyrusNajmabadi @sharwell @jasonmalinowski let me know your thoughts on the following options: 

Option 1 - Incorporate arrow functionality to quick info to view overloads:

![image](https://user-images.githubusercontent.com/46729679/89353978-7969a480-d66c-11ea-886a-30f5a991b4ef.png)

Option 2 - Remove the +1 and insert a link in quick info:

![image](https://user-images.githubusercontent.com/46729679/89354249-3bb94b80-d66d-11ea-90a8-b763e79b9bae.png)

Clicking the link opens signature help: 

![image](https://user-images.githubusercontent.com/46729679/89354322-60152800-d66d-11ea-96d6-e04fed819d7c.png)

**Comment by CyrusNajmabadi** [comment]
strong preference toward: 

![image](https://user-images.githubusercontent.com/4564579/89354574-07925a80-d66e-11ea-8bf3-efe4d5d0c889.png)


(though, i woudl just have the arrows at the start to look similar to sighelp).

**Comment by mikadumont** [comment]
@CyrusNajmabadi yeah may as well have it be the same.

**Comment by jmarolf** [comment]
I think option 1 is the smallest change we could make. Would like to try that and see what the reception is.

**Comment by jasonmalinowski** [comment]
For the second option what I had in mind was still keep the (+1 overloads) text, just make that clickable. That way you're not losing the info if you didn't need it.

**Comment by CyrusNajmabadi** [comment]
So... in terms of impl... couldn't we just do this:

1. if the user hovers over a symbol that has overlaods (i.e. method/index/generics/etc.)... then we:
2. just pop up sig help, just without a particular 'parameter' selected.

Woudln't this just give the experience we want?  i.e. we'd have the signatures with the up/down items as before.  we'd just show normal symbol information under that, and not information about any particular parameter...

The only difference (i guess) is if up/down keystrokes are captured here.  But i'm not certain it's a bad thing if they were captured.  if it was a bad thing, we coudl easily change our controller to capture up/down for normal sig help, but not capture for quick-info-sig-help.

This seems super easy to prototype and try out.  

Thoughts?

**Comment by mikadumont** [comment]
Proposal: 

If the user hovers over a symbol that has overlaods (i.e. method/index/generics/etc.)... then we:
Show signature help, just without a particular 'parameter' selected.

![image](https://user-images.githubusercontent.com/46729679/94624001-5fae9d00-026a-11eb-8c1d-95b673f6ccae.png)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
