### ISSUE TITLE
IntelliSense: Delegate Auto Complete

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46278]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1119627/intellisense-delegate-auto-complete.html)._

---
Say I've defined a delegate:

```c#
public delegate bool Condition(int x);
```

Would it be possible to add IntelliSense so that this:

```c#
delegate Condition
```

gets extended to this:

```c#
delegate (int x)
```

Or maybe something like `adlgt` for anonymous delegate? 
```c#
adlgt Condition
```

---
#### Feedback Bot on 7/20/2020, 08:00 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
It's very unlikely we would do this given that anonymous-methods were effective a C# 2.0 feature that we entirely regret and replaced soon after with lambdas.  Specialized support for that feature isn't something we invest in.
