### ISSUE TITLE
ViewModel violates DRY; here is the fix!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1110273/viewmodel-violates-dry-here-is-the-fix.html)._

---
I might have defined a field as a string in my Model; my ViewModel will then also define that field as a string.  The names and data types will be identical.

What if I want to change the datatype or name of that field?  I would need to change it in TWO places; therefore, I repeated myself.  Why do I need to define it twice (once in the Model, once in the ViewModel)?  Because of the risk of overposting.  Still; we repeated ourselves!  We have more than one source of truth; that is, we've defined this exact same field twice (same exact name, same exact datatype).  This is bad.  It could lead to mapping errors, and is not fun code to write.

I suggest; a ViewModel class gets new attributes.  It can inherit from your Model; and expose properties of the model directly.  This would be the first and only class to support multiple inheritance.  I'm open to other methods of exposing Model attributes, if anyone has ideas!

Example:

**Model**

```
public class Student
{
    public int ID { get; set; }
    public string LastName { get; set; }
    public string FirstMidName { get; set; }
    public DateTime EnrollmentDate { get; set; }
    public string Secret { get; set; }
    public string SomeOtherSecret { get; set; }    
}

public class SuperHero
{
    public Color CapeColor { get; set; }
}
```

**ViewModel**

```
namespace ContosoUniversity.Models
{
    public class StudentVM: Student, SuperHero
    {
        public Student.ID;
        public Student.LastName;
        public Student.FirstMidName;
        public Student.EnrollmentDate;        
        public SuperHero.CapeColor;
    }
}
```

That is better, it solves our quandry, but still it's wordy.  How about this?
**ViewModel**

```
namespace ContosoUniversity.Models
{
    public class StudentVM: Student, SuperHero
    {
        public Student.* Not {Secret, SomeOtherSecret};
        public SuperHero.*;
    }
}
```

This approach has risks; if we add attributes to the Model that we don't wish to expose, we have to exclude them in the ViewModel when * is being used to expose all attributes of the Model.

An added benefit is that instead of finding out we have a problem at runtime in mapping the ViewModel to the Model after changing only the Model:

```
	entry. CurrentValues.SetValues(StudentVM);
```

... we find out right away that the Model changed, which automatically changed the ViewModel, and now we might even get a Razor error saying the field is gone, or whatever the case may be.

With that enhancement; now we don't repeat ourselves, we have one source of the truth, we have less wordy ViewModels that are way more enjoyable to code, we aren't at risk of over-posting, and life is great!

Code well and be excellent to each other!
:)

---
#### Feedback Bot on 7/12/2020, 08:48 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### tranqwhl on 7/13/2020, 08:51 AM: 

I have another idea that doesn&#39;t use multiple inheritance for the viewmodel; the ViewModel class takes a constructor that is as many Models as you like:<br><br>namespace ContosoUniversity.Models<br>{<br>public class StudentVM: ViewModel(Student, SuperHero)<br>{<br>public Student.* Not {Secret, SomeOtherSecret};<br>public SuperHero.*;<br>}<br>}

**Comment by sharwell** [comment]
My general recommendation is to not use separate Model and ViewModel unless needed. The MVVM approach is able to solve certain issues (e.g. complexity in very large controls), but it comes with other costs (notably a negative impact on portability and increased testing complexity). If the benefits provided by MVVM are not outweighing the costs, in might not be the right time to use it.

**Comment by CyrusNajmabadi** [comment]
This looks to be a language request.  Those should be discussions over at dotnet/csharplang.  Thanks!
