### ISSUE TITLE
Object Intellisense Completion for Init-Only Classes

### ISSUE THREAD

**Issue by svengeance** [dotnet/roslyn#46297]
With the advent of init in C# 9.0, we have an opportunity here to enhance the workflow for developers.

Currently, code-completion for classes leaves you hanging at the end of the completed class name, with no parens or initialization brackets.

For a class which contains init members and a parameterless constructor, I think it is a very safe assumption that the intent of that class **is** to have all of its properties init'd via property initialization, as opposed to the extreme scenario of an empty constructor doing all of the initialization.

Given that supposition, it would be rather convenient if autocompleting classes of this nature brought your cursor to the beginning of object initialization. 

Demonstration
-------------------------
```cs
public class Puppy
{
    public int Age { get; init; }
    public string Name { get; init; }
}
```
**Prior behavior**
```cs
var pup = new Pu // User auto-completes
var pup = new Puppy // Cursor is placed here
```

**Proposed Behavior**
```cs
var pup = new Pu // User auto-completes
var pup = new Puppy 
{
    // Cursor is placed here
};
```

In my opinion the intent for this is explicitly expressed with parameterless init, and I imagine **most** code will follow this outcome.

Thanks for your time.

**Comment by sharwell** [comment]
I propose making this the **Smart Break Line** behavior for this construct. Will update following design review meeting.

**Comment by jmarolf** [comment]
Design Meeting Conclusion:
- Wait for more feedback on init properties as the feature rolls out in C# 9
- @sharwell to write up a detailed proposal regarding improved Smart Break Line behavior

**Comment by 333fred** [comment]
Personally, I'd wait on doing this until C# has required properties. At that point, if you complete a constructor and know that you must set some things via object initialization, doing this would be appropriate. I'm not sure if it's quite so appropriate when there are no properties that are required to be complete.d

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
