### ISSUE TITLE
ConvertTupleToStruct tests should be explicit about metadata references

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46291]
Tracks skipped tests `ConvertTupleToStructTests`

**Comment by CyrusNajmabadi** [comment]
Yup.  Will take care of this asap.

**Comment by tmat** [comment]
I think VB tests `AddMissingImports_Extension_Await` and `AddMissingImports_Extension_Await_Overload` might have the same problem.

**Comment by sharwell** [comment]
Converting these to the new test framework will resolve the problem.
