### ISSUE TITLE
Problem with C# diff edit representation returned by SyntaxTree.GetChanges()

### ISSUE THREAD

**Issue by theoy** [dotnet/roslyn#463]
See the testcase SyntaxDiffingTests.TestQualifyWithThis(...) added in Pull Request #457.

For the referenced testcase, it returns 2 changes - with an add followed by delete.

This causes downstream pieces to consider this as conflicting edits, even though they are not.

/cc @mavasani

**Comment by mavasani** [comment]
Re-open to track the new unit test failure from #2289
