### ISSUE TITLE
Improve CS1503 message for function pointer

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#46312]
**Version Used**:

https://github.com/dotnet/roslyn/commit/6202837974b663ac253945cbd060a18b8a0d16c1

**Steps to Reproduce**:

Compile the following code with `csc -langversion:9.0`

```c#
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

unsafe class C 
{
    void M()
    {
        IntPtr kernel32Handle = NativeLibrary.Load("kernel32");
        IntPtr func = NativeLibrary.GetExport(kernel32Handle, "GetCurrentProcessorNumber");
        
        // Caller((delegate* unmanaged<uint>)func); // works
        Caller2((delegate* unmanaged<uint>)func); // gives unfriendly error
    }
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private uint Caller(delegate* unmanaged<uint> funcPtr) => funcPtr();
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private uint Caller2(delegate*<uint> funcPtr) => funcPtr();
}
```

**Expected Behavior**:

```sh
    error CS1503: Argument 1: cannot convert from 'delegate unmanaged*<uint>' to 'delegate*<uint>'
```

**Actual Behavior**:

```sh
    error CS1503: Argument 1: cannot convert from 'delegate*<uint>' to 'delegate*<uint>'
```

**Online Demo**
[https://sharplab.io/#v2:EYL...](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRjgOwMYwJYD2mqADgXpjBAsgDQwhTIC2APgAIBMAjALABQ7AAwACdtwB0AJSz5mECQGECzEngA21AMrUAbnmwoA3AOFjJMynnkSAkpWoESOhPsPIT/AVmRRIYzhFFEQEAbwERSLEAFhEAWQAKAEoIqPD+KMyRexgABRgEEQBrakwIdQBmTgAJKEwAE00RAF4RADlYPF0IABk8YAQoBABPCR6CKHqEgCIShDLKzmmkzyyonPzCjBwW9s7uvoGh0YBxCBgAUQAPMgQYBLmFqtqGzVoRabOYRUQkSlyEAR3MgCAg2nBmMBqMtVmsQhk4QB6RFBKDqTQIBIJerlCAAc1gEAAVCIsMw6lA8RB6gAeOAUGAAPiS22wKxEyJEAHdQUVkKk1oo0RjOFicZoCVQSWSKVTafTKMzWezOXiuihSZgwAg8BBXsMRNRAQgBSIAL6m00AbTi5wAFgR6rZVOoEraYA6nS6APIkfBEZASNoEezqCgUPFJAC6ppIOt0hNJDNR6Oo2NxkuJmvJmEp1LpDMZIlZmySLSLJYKyVhkWt7s9zpIrvrjsb6l9/swgeDofDmEjMYRkTjXUTCpgKZF6YlhKJBcVxaw2FL5cXOE21YEZqAA===)

**Comment by 333fred** [comment]
This will be fixed when we update the public api.

**Comment by am11** [comment]
Thanks for the quick fix @333fred! 🎉
The aforementioned sharplab link now shows the desired exception message:

```sh
error CS1503: Argument 1: cannot convert from 'delegate* unmanaged<uint>' to 'delegate*<uint>'
```
