### ISSUE TITLE
Operator '^' cannot be applied to operands of type 'ulong' and 'bool'

### ISSUE THREAD

**Issue by Symbai** [dotnet/roslyn#46332]
**Version Used**: Visual Studio 2019 Community Preview 5.0

**Steps to Reproduce**:

```
ulong val1 = 0L;
ulong val2 = 0L;
if (val1 ^ val2 >= ulong.MaxValue) { } // <--- exception
if ((val1 ^ val2) >= ulong.MaxValue) { } // <--- no error
```

Exception: `Operator '^' cannot be applied to operands of type 'ulong' and 'bool'` When adding additional braces around the math operation the exception goes away:

**Expected Behavior**:
It should work without the additional braces

**Actual Behavior**:
Its marked as error and won't compile until I add additional braces around the math operation. This is XOR exclusively, other operators such as `*` `/` `+` `-` work as expected without requiring these additional braces.

**Comment by CyrusNajmabadi** [comment]
`^` (xor) has lower precedence than `>=`. See https://docs.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation?view=vs-2019 for more information.
