### ISSUE TITLE
Suggestion on the zh-Hans translation of warning CS8602 message

### ISSUE THREAD

**Issue by CXuesong** [dotnet/roslyn#46331]
**Version Used**: 
```
> csc -version
3.7.0-5.20366.7 (a303c0d8)
```

**Steps to Reproduce**:
Let compiler emit CS8602 (Dereference of a possibly null reference) warning in zh-CN locale.

**Expected Behavior**:
I expect to see something like this
> warning CS8602: **解引用**可能出现空引用。

**Actual Behavior**:
The error message is as follows
> warning CS8602: **取消引用**可能出现的空引用。

c.f. [wd:Q5261748](https://www.wikidata.org/wiki/Q5261748)

I have a more general question: what is the recommended approach to provide suggestion on the error message localization? I didn't find them in this repo so I can only put it here so far.

**Comment by jcouv** [comment]
Tagging @BillWagner @jmarolf for localization question.

**Comment by jmarolf** [comment]
Tagging @wli3 who is our loc champ

**Comment by wli3** [comment]
@janbaltus could you look into this?

**Comment by cristianosuzuki77** [comment]
Feedback added to our log. In future, please tag myself as well.

**Comment by jaredpar** [comment]
@cristianosuzuki77 any updates here?

**Comment by cristianosuzuki77** [comment]
解引用可能出现空引用  was resolved and it appears in the last PR below.
https://github.com/dotnet/roslyn/pull/48462/files#diff-92d494f9f81a046ffa0f8d4a0062e124704ec6c2bdbddd0daf061bdc72e1bbc8

![image](https://user-images.githubusercontent.com/18152472/96752851-e5ae9700-1383-11eb-993e-eca75a8d649b.png)

 

https://github.com/cristianosuzuki77/roslyn/blob/5a1e4f6bdf2e05e10861d3aafe56f503cd14994a/src/Compilers/CSharp/Portable/xlf/CSharpResources.zh-Hans.xlf

@wli3 fyi

**Comment by cristianosuzuki77** [comment]
@wli3 let me know if you need anything else. The last test-pass did include this fix as well.
