### ISSUE TITLE
IDE error when accidentally combining a For-Loop with an Enumeration and a minus sign

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46350]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1125487/ide-error-when-accidentally-combining-a-for-loop-w.html)._

---
An IDE error occurs in VisualBasicConvertForToForEachCodeRefactoringProvider when I write:

```
Private Sub Foo()
	Dim Bar = {1, 2, 3}
	For i = 0 To Bar
End Sub
```
and add a minus sign after the Bar, because I forgot to write Bar.Count()

So, the following code raises an error in the mentioned provider.

```
Private Sub Foo()
	Dim Bar = {1, 2, 3}
	For i = 0 To Bar -
End Sub
```

Copy and paste won't show the problem, you have to type the minus sign.

---
#### Feedback Bot on 7/26/2020, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't get any error.
