### ISSUE TITLE
Compiler Crashes when awaiting in the clause of an if statement.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#4638]
Simple repro:

```C#
using System;
using System.Threading.Tasks;

namespace AsyncConditionalBug
{
    class Program
    {
        static void Main(string[] args)
        {
            DoSomething(Tuple.Create(1.ToString(), Guid.NewGuid())).Wait();
        }

        public static async Task DoSomething(Tuple<string, Guid> item)
        {
            if (item.Item2 != null || await IsValid(item.Item2))
            {
                throw new Exception("Not Valid!");
            };
        }

        private static async Task<bool> IsValid(Guid id)
        {
            return false;
        }
    }
}
```

**Comment by VSadov** [comment]
Same as internal issues 1205966 and 1203204 watson crash bucket

**Comment by AdamSpeight2008** [comment]
Try adding parenthesis to the condition
 `(item.Item2 != null) || (await IsValid(item.Item2)))` (thus a potential operator precedence issue)
try the non-short cutting version.
`item.Item2 != null | await IsValid(item.Item2))` (potential issue with the short-circuiting)

**Comment by VSadov** [comment]
It appears to have the same root cause as https://github.com/dotnet/roslyn/issues/4628
Await spiller tries to assign into the left operand of || , but in this case the left operand happens to be a literal "false" since an instance of Guid, being a value type, is known to never be null.

At the later stage, codegen is forced to emit an assignment into a literal "false" which does not make any sense and codegen performs fail-fast.
