### ISSUE TITLE
Debugging in liveshare hits fatal error

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#46403]
Debugging generally seems to work correctly, but when running in debug mode, a fatal exception is thrown:
![exception](https://user-images.githubusercontent.com/5749229/88742102-2042c380-d0f6-11ea-9d34-23ea1fb62729.png)

cc @tmat

**Comment by jinujoseph** [comment]
This should be fixed as part of move to C#_LSP

**Comment by dibarbet** [comment]
resolved in https://github.com/dotnet/roslyn/pull/46370
