### ISSUE TITLE
Cntrl+Q search takes 2-3 seconds longer than navigate to for searching

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#46428]
Some possible causes -

1.  Navigate to communicates with the OOP using message pack serialization whereas cntrl+Q (powered by LSP running in the OOP) is using json serialization.
2.  Navigate to passes in a list of priority documents based on the ones that [are open or visible](http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/NavigateTo/NavigateToItemProvider.Searcher.cs,f23433afcca85fc6) and searches those first.  The LSP workspace symbols request does not pass that information.  @tmat do you happen to know if this information is present in the servicehub process?  It seems like it shouldn't be as it depends on the workspace.
A possible solution here would be to listen to didOpen and didClose LSP requests and have the OOP LSP server track the open documents.

cc @gundermanc

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out for now as inherent to the system.  Now that you've moved to just having a single system for NavTo for LSP/normal I'm not sure what roslyn can do here to make anything better.
