### ISSUE TITLE
Inconsistent nullable feature status for WinUI3 projects

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#46420]
**Version Used**: 
Visual Studio 16.7 Preview 6
.NET SDK 5.0.100 Preview 7
WinUI 3 Preview 2

**Steps to Reproduce**:

1. Create a new WinUI(.NET 5) project from template. https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop
Building the package project requires workaround for this VS version, but building the main .NET project will success.
2. Add `<Nullable>enable</Nullable>` in `csproj`.
The compiler will complain about that field `m_Window` of class `App` is not initialized, as expected.
3. Add nullable annotation onto the field declaration, making it become `private Window? m_Window;`. Then compile the project again.

**Expected Behavior**:
No warning about nullability present.

**Actual Behavior**:
The IDE IntelliSense warning goes away. But there will be `warning CS8632: you can only use nullable annotations in #nullable enable context` in **IDE output window**. The warning does not go into **IDE error list window**.

**Other Information**:
I haven't confirmed whether it's caused by WinUI or CsWinRT. But I can confirm that it doesn't apply to WPF (.NET5).

**Comment by cartermp** [comment]
In theory this should work because WinUI3 project stargeting net5 are SDK-style projects.

**Comment by huoyaoyuan** [comment]
It only repros when there's `.xaml` (probably requires generating `.xaml.g.cs`) added to the project.

**Comment by huoyaoyuan** [comment]
Opened https://github.com/dotnet/msbuild/issues/6088 . This is an external issue.
