### ISSUE TITLE
Initonly attributes can be modified after initialization if the receiver is of type dynamic

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#46448]
There is a big loophole in the safety of initonly members, at least as currently implemented. @jnicholes reported at https://github.com/dotnet/csharplang/issues/39#issuecomment-666012974

> I think I may have stumbled into unintended behavior of init-only properties. The following code sample demonstrates that an init-only property can be modified after initialization by casting the containing object as dynamic. It also demonstrates that this behavior is not the same for private setters or read only properties. Is this intended? I would have expected the code to compile but I would also have expected a runtime error similar to both the read only property and the private setter property.

He goes on to give code that shows that the language's safety guarantees around initonly are violated by the implementation.

**Comment by gafter** [comment]
See also https://github.com/dotnet/runtime/issues/40118

**Comment by cston** [comment]
This should be handled in the C# dynamic binder. See https://github.com/dotnet/runtime/issues/40118.

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/runtime/pull/41293.
