### ISSUE TITLE
Invalid 'Cast is redundant' Inspection Inside Format String

### ISSUE THREAD

**Issue by MrKWatkins** [dotnet/roslyn#4646]
The following test case will pass in Visual Studio 2015:

    var colourString = $"Colour value: {(int) ConsoleColor.Red}";

    Assert.Equal("Colour value: 12", colourString);

However I get an invalid Roslyn inspection come up on the cast to int:

![invalidinspection](https://cloud.githubusercontent.com/assets/345796/9354902/2fb91e5a-466c-11e5-80aa-96d1ddf7ca8b.png)

If I go ahead with that inspection and remove the cast then my code will break as the `ConsoleColor.Red.ToString()` will be used instead, giving `colourString` the value `"Colour value: Red"` instead.

**Comment by Pilchie** [comment]
This is the same issue as #4037
