### ISSUE TITLE
DiagnosticService reports duplicate diagnostics

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#46463]
Tracks skipped tests in:
- `Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Squiggles.ErrorTagGeneratedForWarningAsError`
- `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.SuggestionTags.SuggestionTagProducerTests`
- `Microsoft.CodeAnalysis.Editor.UnitTests.Preview.PreviewWorkspaceTests` 
- `Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.DiagnosticsClassificationTaggerProviderTests`

The test used to depend on `DefaultDiagnosticAnalyzerService` - this implementation of diagnostic incremental analyzer provider appears to work well, but it's not the one that is used by the product. The real one is `DiagnosticService`, which when used will fail the test. 

Since `DiagnosticService` specifies list of workspace kinds for which it is activated and this set does not include `Test` workspace the test does not use it. Instead, the test fell back to `DefaultDiagnosticAnalyzerService`.

We are now using WorkspaceKind.Host for this test which revealed the incorrect behavior.

**Comment by mavasani** [comment]
@tmat Is your change that skips these tests merged?

**Comment by tmat** [comment]
Not yet. You can emulate by setting the workspace kind to `Host` when creating workspace in these tests. That should do.

**Comment by mavasani** [comment]
Seems @sharwell has a fix already..
