### ISSUE TITLE
intellisense #define suggestions are nonsense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46473]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1132015/intellisense-define-suggestions-are-nonsense.html)._

---
If I type `#define` in a C# file, Intellisense makes the following suggestions:
```
#define region
```
```
#define if
```
```
#define if (true)
	{

}
```
(Yes, that last suggestion includes actual tab characters.)

The first two are just nonsense (while it's legal C# to use `region` and `if` as preprocessor symbols, it's at best very strange style), while the last one isn't even valid C# code.

---
#### Feedback Bot on 7/31/2020, 00:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is occurring because snippet completion items are shown in this context, and pressing <kbd>Tab</kbd> completes the snippet. I'm not sure is much we can do to improve the scenario given the limited ability to declare applicable contexts for snippets.

**Comment by jinujoseph** [comment]
**Design meeting Notes** 

This might be good to have but doesn't stand out as a priority at the moment. The conclusion was to create a single tracking [issue ](https://github.com/dotnet/roslyn/issues/46842)at Roslyn and collect all feedbacks related to snippets and when we have enough evidence that this needs investments then we can discuss this with platform team and make progress.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are nto investing in these legacy snippet experiences.
