### ISSUE TITLE
How to perform definite assignment for methods marked SkipLocalsInit

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#46488]
Methods under the attribute SkipLocalsInit do not clear the frame's locals before running the code.

This interacts poorly with https://github.com/dotnet/roslyn/issues/30194

It has been suggested that for such methods we should run the strong version of definite assignment, treating even private variables in other assemblies as significant.

Once a decision is made about what we should do, this issue should be edited to describe that decision and the compiler should be adjusted to implement it.

**Comment by gafter** [comment]
The latest decision is recorded in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-20.md#private-fields-in-structs-with-skiplocalsinit and requires we run the strong version of analysis when the method is marked `SkipLocalsInit`.

**Comment by 333fred** [comment]
Current behavior has shipped in C# 9 for some time now, we won't be making any more changes.

**Comment by gafter** [comment]
Are you asserting that the documented behavior is what is implemented?

**Comment by 333fred** [comment]
No, I'm asserting that we never went and changed it when we first did warning waves, and it would now be a breaking change to do so.
