### ISSUE TITLE
SyntaxNode.WithAdditionalAnnotations should throw if node is unsupported

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#46481]
From this PR comment thread: https://github.com/dotnet/roslyn-analyzers/pull/3931/files#r463767153

The `roslyn-analyzers` repo has [this extension method](https://github.com/dotnet/roslyn-analyzers/blob/998a93ee83ce253cb307880c5d4b37048e4a4483/src/Utilities/Workspaces/SyntaxNodeExtensions.cs#L27-L35), which assumes any `SyntaxNode` will be able to set its imports annotation flag. I was hoping it would work when invoking a method, but it doesn't. @sharwell explained that this only works for Types.

So as @mavasani suggested in the comment, the method should throw if the user attempts to add an imports annotation to a `SyntaxNode` that is not a Type, instead of silently ignoring it.

**Comment by sharwell** [comment]
The imports annotation is a hint to the simplifier. The code fix is free to use it or not use it, and a future release could account for more scenarios. Stronger argument checks would make it more difficult for projects to conditionally use new features when available (i.e. Light up scenarios).

**Comment by CyrusNajmabadi** [comment]
This isn't possible to do.  WithAdditionalAnnotations has no clue what is/isn't supported.  Annotations can be used for any purpose by any client.
