### ISSUE TITLE
"Pull members up to base type" should allow specifying which partial declaration to move the member to

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46483]
When pulling a member up to a partial base type, there is some thought required to decide which partial declaration the member belongs in. There might be some ways to try and improve the heuristics for which declaration is chosen, but it might also make sense to add an entry to the lightbulb menu for each partial declaration. The filename+source location of the declaration could perhaps be included in the entry.

![image](https://user-images.githubusercontent.com/5833655/89076383-0511c700-d335-11ea-9e85-3cd2b416053f.png)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack fo feedback.
