### ISSUE TITLE
Add file header at a folder, project, and solution level from the right click menu in Solution Explorer

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#46487]
Direct customer ask copying here:
> I would love to see a feature like right click on a folder to add file headers to all files in the folder.

**Comment by sharwell** [comment]
Design review conclusion:

1. Add "Apply file header preferences" to the set of available Code Cleanup actions (where Code Cleanup is already available through Solution Explorer)
2. Enable (1) as part of the default Code Cleanup profile
3. File a separate feature request to create a refactoring that generates a `file_header_template` from the comment at the top of a source file if it is not already present in **.editorconfig**
4. Update #21227 to indicate that a simplified Code Cleanup profile that includes (1) would be good to use automatically after creating a source file from a template
