### ISSUE TITLE
Right-click UI gesture on a project/sln to run the adjust namespace analyzerAdjust namespaces

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#46486]
Related customer request copying here:

>When detecting mismatched namespaces have the ability to adjust the namespace on a project or solution level by right clicking on the solution or project within the solution explorer.

**Comment by mikadumont** [comment]
Direct customer request copying here: 

>  I would love to see a feature like right click on a folder to adjust all namespaces to match the directory structure and we need for XAML files to be adjusted as well.

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by jinujoseph** [comment]
Duplicate of #14340

**Comment by jinujoseph** [comment]
Talking to @mikadumont clarified that this is asking for a UI element where you can right-click on a project/sln to run the adjust namespace analyzer which needs to convert our sync namespace refactoring to be a analyzer https://github.com/dotnet/roslyn/issues/33877

**Comment by mikadumont** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/37453
