### ISSUE TITLE
Lots of intellisense in new MVC project

### ISSUE THREAD

**Issue by MojoDK** [dotnet/roslyn#4648]
(Using vb.net in VS2015 Pro)

When I create a new MVC project and not change a single code, I get 55 intellisense errors and intellisense does not work. :(

![2015-08-19_17-17-23](https://cloud.githubusercontent.com/assets/1185948/9360388/3c628338-4696-11e5-90ab-399796347a08.png)

I've tried repair and start in safe mode - didn't help.

Any idea?

**Comment by Pilchie** [comment]
Can you share one of the created projects with us? Also, what is the default file encoding of your computer?

**Comment by MojoDK** [comment]
Well in my desparation I uninstalled VS2015 and reinstalled ... now I don't have "web" projects anymore. I'm about to pull the last hair outta my head :( :( :( ... I've tried to install with "Select all", I've tried repair (it took 1½ hour on a super fast pc) - damn I hate VS2015 right now. Now I'm trying to uninstall and installing to another drive. I'm spending more time here at work getting VS2015 to work - than actually working. Sry for my frustrations! :(

**Comment by Pilchie** [comment]
At this point, there isn't much for us to go on.  Please let us know if you can get more information to help us track this down though.

**Comment by MojoDK** [comment]
Hi again,

Spent 3 hours on phone with MS VS support and via remote access the finally got the "web" projects folder working - don't ask me how. Man did she have problems with VS2015 installation dialog - that thing is totally messed up. 

Now we're back to my original post - still tons of intellisense errors. 

I'm expecting a call from MS tomorrow and hopefully they will sort it out.

**Comment by MojoDK** [comment]
Ok - status update....

I've been on phone with MS for 6 hours and they finally fixed it.

They manually deleted all VS 14 user settings from registry and all VS 14 settings from user profile. That did the trick. They were not able to tell what caused it.

An uninstall of VS2015 doesn't delete those user settings, so you have to do it manually. IMO VS 2015 uninstall should ask if it should remove user settings too. An uninstall should be able to remove everything and not leave anything behind.

**Comment by Pilchie** [comment]
Well, devenv /resetuserdata does that, but there are good reasons not to do it on uninstall.
