### ISSUE TITLE
Gold Bar Error thrown when renaming file multiple times

### ISSUE THREAD

**Issue by 06needhamt** [dotnet/roslyn#46496]
**Version Used**: 
VS 2019 16.6.3

**Steps to Reproduce**:

1. Create a new .Net Core console application
2. Add a new class
3. Rename the file for the added class clicking yes to renaming the code unit

**Expected Behavior**:
The file and code unit are renamed successfully.

**Actual Behavior**:
Gold bar error is shown producing the attached log file
[VsProjectFault_a5ac869e-674e-413c-bcd2-f4c6e3ca76cd.failure.txt](https://github.com/dotnet/roslyn/files/5011100/VsProjectFault_a5ac869e-674e-413c-bcd2-f4c6e3ca76cd.failure.txt)

NOTE: this issue does not occur for me every time but only once every 10 or so renames of the same file and code unit.

**Comment by CyrusNajmabadi** [comment]
@ryzngard was this what you were fixing?

**Comment by ryzngard** [comment]
@CyrusNajmabadi  no this looks different

**Comment by CyrusNajmabadi** [comment]
Closing out as i can't repro this and i don't see prism hits for this  now.
