### ISSUE TITLE
Rules with a NotConfigurable tag shouldnt be configurable from the Solution Explorer

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#465]
Rules that have a [NotConfigurable](http://source.roslyn.io/#Microsoft.CodeAnalysis/Diagnostic/WellKnownDiagnosticTags.cs,207e57dd0b96bd4b,references) tag are not configurable today from the ruleset editor and are suppression doesn't work for them .We shouldn't allow them to be configurable from the Solution explorer as well.

**Comment by tmeschter** [comment]
Assigning to @jmarolf for verification.
