### ISSUE TITLE
More completions for generics arguments

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#46503]
Right now if when I typed to  
`public class {
     List<int> i = new
}`
then the completion will suggest me to hit Tab and insert `new List<int>`

However, I can't get help of this when I am using Immutable types. 
When I typed
`public class {
     ImmutableArray<int> i = ImmutableArray.Create
}`
VS doesn't auto fill the generics for me. And I need to fill the type manually. What I am feeling it VS will only do maybe for the constructor.

I suggest VS should enhance the experience here. At least it should support some common used types (Like the Immutable types)

**Comment by Cosifne** [comment]
An additional supplement. What I want to do in my original example is I want to create an empty array. (therefore I can't omit the generics)

**Comment by CyrusNajmabadi** [comment]
I'm on the fence here.  Normally `ImmutableArray.Create` is *not* used with type arguments.  Instead, it infers them from parameters.  For your case where "I want to create an empty array", the idiomatic form is `= ImmutableArray<int>.Empty`.  

It's perhaps the case that we should offer *that item* in the list.  i.e. if we're in a place where we can infer a type, and we see that that type itself exposes a static singleton, we could put those singletons in teh list for easy access.  I would not be opposed to that.

**Comment by Cosifne** [comment]
@CyrusNajmabadi 
Yes, ImmutableArray<int>.Empty is the case I feel could have a better support

**Comment by jasonmalinowski** [comment]
We discussed this in our design meeting and concluded that we didn't want to specifically hard-code ImmutableArray patterns, but we do need to do something here. A heuristic that was proposed was we:

1. Show a completion list that filters to static methods that matches by return type, and
2. Have a heuristic that if the thing on your left is `SomeClassName<T> `and there's also a non-generic SomeClassName, to also go looking through those for static methods as well.

Rule 2 covers the common case where static factory methods for `ImmutableArray<T>` are on ImmutableArray to allow for type inference.

@sharwell volunteered to make the precise proposal for this.

**Comment by sharwell** [comment]
There are two cases we looked at specifically in the context of target-typed completion:

1. Static fields or properties of the type
    * `ImmutableArray<int>.Empty` produces a value of type `ImmutableArray<int>`
2. Static generic methods of a non-generic type with the same name, where the generic method arguments match the generic type arguments
    * `ImmutableArray.Create<int>()` produces a value of type `ImmutableArray<int>`
    * `KeyValuePair.Create<TKey, TValue>` produce a value of type `KeyValuePair<TKey, TValue>`

When the first case is identified, we can either put the fully-qualified member in the completion list, or we can put the constructed generic type in the completion list for easy use of `.` to complete it with generic arguments. For the second case, we only need to fill generic method arguments when completing the generic method. We should consider avoiding generic method arguments if all overloads for the method require parameters that would support type inference, or somehow automatically remove them if it turns out to be unnecessary.

**Comment by CyrusNajmabadi** [comment]
From teh design meeting.  We generally think that target typed completion should see the type being target typed.  If that type (generic or not) contains statics members that return values whoe type is complimentary (i.e. is the same type, or has an (implicit/identity?) conversion to the type), then we should show those members in the list.

So, for example, if did:

```
CSharpParseOptions o = 
```

Then `CSharpParseOptions.Default` would be in the list.  This would allow easy typing of `Default` to just get to that member easily.

**Comment by Cosifne** [comment]
Another point from the design meeting:
Do we want fully qualified member in the completion, or we put the type and require user to hit dot?
We want to both.

**Comment by CyrusNajmabadi** [comment]
We support the `ImmutableArray<int>.Empty` case now.  We do not want to add generics for `.Create` as you may be using inference.  So closing this out as we're in the state we want now.
