### ISSUE TITLE
Code editor goes wild when entering a regex

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46507]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1109780/code-editor-goes-wild-when-entering-a-regex.html)._

---
When entering a regular expression as argument to the Regex.IsMatch method, the editor goes wild and I end up having totally different content in the document than what I had typed. I can't explain it in words, so you'll have to look at my recording.

---
#### Feedback Bot on 7/13/2020, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 7/13/2020, 11:53 AM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Could you please provide a video of the behavior you are seeing.</p>

#### Yves Goergen on 7/17/2020, 02:03 PM: 

<p>You already have that video, do you? I mean, I hope you didn't lose it when I sent it to you, because I don't have a copy of it. I thought I was recording a video and all other relevant events when that recording indicator was on. I have the impression that the feedback system is a fake. Or that your hard disks have holes, where that data is stored.</p><p>Please ask again when you verified that you have lost that feedback data. Then I'll see how I can create a screen recording with other software that's more reliable than yours.</p>

#### Feedback Bot on 7/23/2020, 00:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sam Harwell [MSFT] on 7/23/2020, 00:05 PM: 

<p>Hi @<a target='_blank' href="https://developercommunity.visualstudio.com/users/6401/YvesGoergen.html">Yves Goergen</a>,</p>
<p>Unfortunately, the default recording mode for submitting feedback captures extensive performance information, but it doesn’t record a screen video of the sequence (it just has a couple screenshots spaced several seconds apart). One of my peers suggested using <a target='_blank' href="https://recordscreen.io/">https://recordscreen.io/</a> to capture a video of the screen to help us better understand the behavior you experienced. Once we have the video, we will use the video and the performance data to understand the root cause of the problem and hopefully find a quick fix.</p>
<p>Thank you,<br>
Sam Harwell</p>

#### Yves Goergen on 8/2/2020, 07:35 AM: 

<p>Here's the recording:https://ygoe.de/s/d6hc9H7S1rbqClb1</p><p>This is what I typed there: [A-Z]</p><p>After the dash (-) I entered Ctrl+Z to undo the last automatic step of the editor that caused that mess.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The starting expression is the following:

```csharp
private static readonly Regex domainRegex =
    new Regex(@"^(?:(?!-)[A-Za-z0-9-]+(?<!-)\.)+[A-Za-z0-9]{2,}$");
```

Before the first `[` character, the user attempted to type `[A-Z]`. After typing `[A-`, the resulting text in the editor was:


```csharp
private static readonly Regex domainRegex =
    new Regex(@"^(?:(?!-)[--[]][A-Za-z0-9-]+(?<!-)\.)+[A-Za-z0-9]{2,}$");
```

**Comment by CyrusNajmabadi** [comment]
Weird, i don't repro this at all:

![regex](https://user-images.githubusercontent.com/4564579/89234781-96857100-d5a1-11ea-9dee-9077947c1b8b.gif)

**Comment by CyrusNajmabadi** [comment]
they're not even getting our completion lists.  so i have no idea what is even interfering with their typing here.  maybe another extension?

**Comment by sharwell** [comment]
The behavior I observed matches the behavior shown by @CyrusNajmabadi.

**Comment by ygoe** [comment]
I'll try to test it with fewer extensions. What was that trick again to start Visual Studio without extensions?

**Comment by jmarolf** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/reference/safemode-devenv-exe?view=vs-2019

**Comment by ygoe** [comment]
I can't open my project in safe mode. It says "migration required" in the solution explorer. It works in the normal environment.
