### ISSUE TITLE
Expand #line to support columns

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#46526]
## The problem

The current restrictions of the `#line` pragma don't bode well for embedded languages. For instance in Razor the core "transition into C#" mechanism has various implications on the `#line` pragma's lacking support of a column. For instance, lets consider:

```Razor
@DateTime.Now
```

At runtime this renders:
```C#
#line 1 "Foo.razor"

Write(DateTime.Now);

#line default
```

At design time this renders:
```C#
#line 1 "Foo.razor"

__o = DateTime.Now;

#line default
```

Now consider the implications of this at debug & edit time.

1. Errors. Any error that maps to `DateTime.Now` is instantly misaligned because `@DateTime.Now` exists at the front of the line.
2. Breakpoints. Any breakpoint can't possibly understand how to bind to the original language document properly without understanding the difference in columns.

------------------------------

## Suggestion:

- Allow line pragmas to provide a column & exist in the middle of expressions/statements and work properly at error/debug time ([they currently don't](https://github.com/dotnet/roslyn/issues/43432)):
```Razor
<p>The current time is: @DateTime.Now</p>
```
```C#
Write(
#line 1 25 "Foo.razor"
DateTime.Now
#line default
);
```

- OR allow a column, mapped offset and length to enable unmapped code to exist in the line pragma:
```Razor
<p>The current time is: @DateTime.Now</p>
```
```C#
#line 1 25 6 12 "Foo.razor"
Write(DateTime.Now);
#line default
```

/cc @tmat

**Comment by tmat** [comment]
Would it be possible for Razor to emit indented code like so?

```C#
__o = 
#line 1 "Foo.razor"
    DateTime.Now
#line default
;
```

then it could control the column precisely.

**Comment by NTaylorMullen** [comment]
> then it could control the column precisely.

Yup we could and actually do in some Blazor scenarios; however, it ends up resulting in pieces not being debuggable: https://github.com/dotnet/roslyn/issues/43432 which is why we haven't done it everywhere

😢

**Comment by tmat** [comment]
Yeah, I see. So the problem is really the placements of the sequence points if `#line` is in the middle of a statement. I guess we have two options in the compiler how to handle that - either we implement column mapping syntax or we change the handling of the `#line` directive when in the middle a statement. The former seems cleaner since the latter is gonna likely have a bunch of odd corner cases.

**Comment by tmat** [comment]
@gafter FYI

**Comment by tmat** [comment]
I'm working on a proposal for adding column to `#line` directive.
