### ISSUE TITLE
Enable end-to-end testing for "variance safety for static interface members" feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#46533]
Once we are able to test against runtime that includes fix for https://github.com/dotnet/runtime/issues/39612, the PROTOTYPE comments  and associated conditional compilation should be removed from https://github.com/dotnet/roslyn/blob/features/VarianceSafetyForStaticMembers/src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs.
Then the feature branch should be merged into master. The only reason for the variance safety for static interface members" feature to still be in the feature branch is that blocking bug in runtime.

**Comment by AlekseyTs** [comment]
CC @jaredpar This is a work item tracking completion of the work for the "variance safety for static interface members" feature.

**Comment by jaredpar** [comment]
As a part of the merge I need to make sure to clean up the following pattern in the tests

```cs
#if false   // PROTOTYPE: enable this branch once https://github.com/dotnet/runtime/issues/39612 is fixed
```

**Comment by AlekseyTs** [comment]
The required runtime is still not available. The conditional compilation remains in the tests, but "PROTOTYPE" is replaced with links to this issue. We should enable tests once runtime is available.
