### ISSUE TITLE
Feature: Containing Type column in references window might include namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46535]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1117066/feature-containing-type-column-in-references-windo.html)._

---
I'm working on game development. I changed my name conventions lately using namespaces more extensively. So I have an Audio module, then a Manager class : Audio.Manager. Same with UI. Manager, Game.Manager, etc. When looking for item references, the Containing Type column only shows the class name, Manager, so I can't say which of the managers is it. Although I could use the Path column, it's too long to be practical.

---
#### Feedback Bot on 7/20/2020, 03:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/20/2020, 10:00 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
This is a feature request to add a new "Containing Namespace" column in FAR window, we recently added "Containing Type" and "Containing Member" columns.

**Comment by ryzngard** [comment]
Design Review Conclusion: We would take this as a PR. Namespace should not be fully qualified, similar to containing type or containing member. Will need LSP work if this goes through, @dibarbet  is there a good way to track the LSP need for this?

**Comment by dibarbet** [comment]
@ryzngard once we have the column, we can file an issue on DevDiv\VS Core\Extensibility\Common Language Server Protocol

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
