### ISSUE TITLE
Display region name in the navigation breadcrumbs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46567]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1135105/display-region-name-in-the-navigation-breadcrumbs.html)._

---
I am a regular user of regions in my code, so I need to see the region in which the method I am examining lives in the breadcrumbs area on top of each file.

---
#### Feedback Bot on 8/4/2020, 03:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
