### ISSUE TITLE
Icorrectly suggesting IDE0032 "Use auto property" for readonly fields

### ISSUE THREAD

**Issue by neoaisac** [dotnet/roslyn#46587]
**Version Used**: 

Visual Studio 2019 16.6.4

**Steps to Reproduce**:

```
private readonly IServices _services;

public IServices Services => _services;
```

**Expected Behavior**:

Should not suggest IDE0032.

When suggested change is executed, the code above changes to:

```
public IServices Services { get; private set; }
```

However, the auto-property's `private set` accessor does not make its value equivalent to the `readonly`. It can still be modified internally in the scope of the class, instead of just in the constructor, making this a non-equivalent repalcement.

**Actual Behavior**:

Suggests IDE0032.

**Comment by CyrusNajmabadi** [comment]
We should still offer here.  however, on versions of C# that support it, we should just produce `public IServices Services { get; }` instead.

**Comment by neoaisac** [comment]
In that case maybe offer that only on versions of C# that support it. Offering it on other versions causes the false feeling that one and the other are equivalent, but they are not.

Also, in case of using C# 9 which is coming in with the init-only properties and the `init` keyword, maybe best to suggest `public IServices Services { get; init set; }`, which by the definition of the feature would be truly equivalent.

**Comment by huoyaoyuan** [comment]
> maybe best to suggest `public IServices Services { get; init set; }`, which by the definition of the feature would be truly equivalent.

The behavior of `{ get; }` is the same with `readonly`. `{ get; init; }` is slightly more relaxed.

**Comment by Youssef1313** [comment]
I can't reproduce.

![image](https://user-images.githubusercontent.com/31348972/95769180-c6df3f00-0cb7-11eb-8b52-8d35ce76315d.png)

**Comment by davidwengier** [comment]
We already have test coverage for this.
