### ISSUE TITLE
Need a warning when implicit ToString occurs (without implementation)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46606]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1043678/need-a-warning-when-implicit-tostring-occurs-witho.html)._

---
ToString casting can be misleading, everybody in project may understand it differently for many different classes.

I should have an option not to use implicit ToString casting in design time. I would like to see warning "Need ToString implementation".

There are many not intuitive castings like       $"{object}"     or     "s" + object      that give unexpected results then.

Visual Studio Extension called SneakyToString does it... there are some bugs there and I would prefer to have it built in.

p.s.
I like the concept for ToString only for internal and debugging purposes...

---
#### Feedback Bot on 5/22/2020, 01:11 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Usr can accomplish this by writing an analyzer (esp. by examining IOperation).
