### ISSUE TITLE
Improve Intellisense for <see langword=""/>

### ISSUE THREAD

**Issue by mdro-bk** [dotnet/roslyn#46618]
**Version Used**: 
Visual Studio 16.6.5
.Net Framework 4.8.03752
.Net Core 3.1.302

Currently Intellisense always completes `<see` as `<see cref=""/>`. This makes the other VS-supported options (langword and href) cumbersome to type (made worse for langword by #24092 if Intellisense is in completion mode).
For langword you can alternatively type the keyword and press ctrl+space, but that has very poor discoverability - I only learned about it just now while searching for existing issues.

I'd prefer `<se` to only complete to `<see ` and then immediately offer the completions `cref=""/>`, `href=""/>` and `langword=""/>`. Unfortunately that was declined in #11489 to preserve the muscle memory from the time before the introduction of langword.
If this decision stays I would suggest to put two `<see>` entries into the top-level xmldoc completion list:

1. The current `<see cref=""/>` completion, more accurately labeled as `see cref`/`see cref=""`/something like that. It will be highlighted by default to preserve muscle memory
2. The generic two-step `<see ` completion (labeled `see` or `see...`).

This would make the other `<see>` variants more discoverable and accessible with only one extra arrow-up or arrow-down keystroke.

## Alternative ##

Since it's only one item more, you could directly add `<see cref=""/>`, `<see href=""/>` and `<see langword=""/>` to the top-level completion list.
However, this only makes sense if we won't ever want more variants.

**Comment by sharwell** [comment]
We can't make this change since it breaks some very common experiences (this behavior was part of #17970, but we rewrote it in #21479 to remove this specific behavior). _However_, you don't actually need to type `<see` to get langword completion. For most keywords, you can just type the keyword followed by Ctrl+Space (e.g. `null` <kbd>Ctrl</kbd>+<kbd>Space</kbd>).

**Comment by mdro-bk** [comment]
> We can't make this change since it breaks some very common experiences (this behavior was part of #17970, but we rewrote it in #21479 to remove this specific behavior).

How does adding a generalised `<see` completion option in addition to the existing `<see cref=""` break the experience if `<see cref=""` **remains selected by default**? Even `<seealso` would stay in its place one step below if `<see` is added above:
```
<se |
+------------+
|   see      |
|-> see cref |
|   seealso  |
+------------+
```

>_However_, you don't actually need to type `<see` to get langword completion. For most keywords, you can just type the keyword followed by Ctrl+Space (e.g. `null` Ctrl+Space).

This is only a solution for langword, but not for href.
Also, langword and href have zero discoverability currently: no completion offered, no documentation.
I only discovered langword a few months ago through someone else's code online, and href and ctrl+space completion while searching for existing issues.
