### ISSUE TITLE
Cannot Install Generated PreRelease Nuget Packages Because of Missing .NET 5 Preview 8 Dependencies

### ISSUE THREAD

**Issue by 7enderhead** [dotnet/roslyn#46617]
**Version Used**: forked from Master, commit  81c5d71a65daa74343241b3ad9c25b6fc372096e

**Steps to Reproduce**:

1. run restore and build
2. try to use the generated nuget packages from `[...]\roslyn\artifacts\packages\Debug\PreRelease` (version 3.8.0-dev.final) in a solution (upgrading from existent 3.7.0-2.final)

**Expected Behavior**:
- upgrade works

**Actual Behavior**:
- upgrade fails, because the PreRelease package has dotnet 5 preview 8 dependencies, but only preview 7 is installed 
```
Install failed (project: [...], package: Microsoft.CodeAnalysis v3.8.0-dev.final)
Unable to resolve dependencies. 'System.Collections.Immutable 5.0.0-preview.7.20364.11' is not compatible with
'Microsoft.CodeAnalysis.Common 3.8.0-dev.final constraint: System.Collections.Immutable (>= 5.0.0-preview.8.20371.14)'.
```
```
$ dotnet --version
5.0.100-preview.7.20366.6
```

**Comment by 7enderhead** [comment]
I also could not find a readily installable preview 8 version of dotnet 5.

**Comment by svick** [comment]
If you need just the packages, you can get them by adding a "daily builds" feed using NuGet.config [as described here](https://github.com/dotnet/installer#installers-and-binaries).

**Comment by 7enderhead** [comment]
@svick : Thanks, adding `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json` for .NET 5 daily builds did the trick!
