### ISSUE TITLE
IntelliSense: Hovering the '.' before a method presents the first overload in the method group instead of the overload actually being used

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46624]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1137517/intellisense-hovering-the-before-a-method-presents.html)._

---
```csharp
new StringBuilder(). Append(0)
```
Hovering over the `.` preceding `Append` shows `StringBuilder StringBuilder.Append(bool value) (+ 23 overloads)`, whereas hovering over `Append` shows `StringBuilder StringBuilder.Append(int value) (+ 23 overloads)`.
The expectated behavior is that hovering over the `.` should be equivalent to hovering over the method name.

---
#### Fiona Niu[MSFT] on 8/5/2020, 11:43 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide a more detailed description of the issue to help us better understand this scenario? Does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use(C# or C++ console)? It would be very helpful if you can provide a screenshot of this issue. Thanks for your help!</p>
<p>We look forward to hearing from you!</p>

#### Aaron Schiff on 8/6/2020, 09:52 AM: 

(private comment, text removed)
#### Feedback Bot on 8/6/2020, 09:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ts2do** [comment]
Here's the followup comment that's missing above. I'm not sure how it ended up being a private comment.

> I can see for C# in .NET Core, .NET Framework, and .NET Standard projects. It looks like it's presented as the first method from metadata sorted alphabetically for .NET Core and .NET Standard, but the first method from metadata sorted positionally for .NET Framework (that is, it shows up as `Append(char value, int repeatCount)` when hovering the `.`). Let me know if any of this needs additional clarification. Thanks.

**Comment by jinujoseph** [comment]
cc @genlu
