### ISSUE TITLE
Remove top empty line after Remove and Sort Usings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46625]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1139960/remove-top-empty-line-after-remove-and-sort-usings.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
We have the following situation.
```
using Namespace1;

using Namespace2;

namespace Namespace3
{
	public class Foobar
	{
             ...
	}
}
```

Namespace1 is not used. Namespace2 is used. When using Remove and Sort Usings, we have
```
<- empty line
using Namespace2;

namespace Namespace3
{
	public class Foobar
	{
             ...
	}
}
```

And you have to manually remove the top empty line.

---
#### Feedback Bot on 8/6/2020, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jeremyliseismic** [comment]
is there any update?
I have same issue in Microsoft Visual Studio Enterprise 2019 Version 16.9.6

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I get:

![image](https://user-images.githubusercontent.com/4564579/198359907-f0743d54-ebd8-4895-a1d9-50a22acac41e.png)
