### ISSUE TITLE
Search members in Intelli Sense by summary comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46628]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1124832/search-members-in-intelli-sense-by-summary-comment.html)._

---
<p>I want to find necessary function by writing some key words or phrase from description of needed function. This need in cases, when I dont remember the name of function, but I know what it must do.</p> <p>For examle: I want to produce sequence from two sequences. But I dont remember the function name. Needed function called &quot;Zip&quot;. This function has description with my wishes. <br><a href="https://i.stack.imgur.com/Z3X0s.png"><a> Image:https: i.stack.imgur.com=</a></a></p><p>Only what I can is to search my wishes using the sources, like Google, StackOverflow and so on. I think that Visual Studio has all opportunities to find function using only its description.</p> <p>But I dont know how to do this. It would be cool to find all the functions contain needed request in description and I could choose the fitting in my case.</p>

---
#### Feedback Bot on 7/26/2020, 06:50 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is likely subsumed by copilot and other indexing system.s
