### ISSUE TITLE
Suggest to import namespaces for generated event handlers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46631]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1118141/suggest-to-import-namespaces-for-generated-event-h.html)._

---
<p>When I write the code to attach an event handler, VS suggests to generate a new method. If the new method uses a class that lies in a &quot;foreign&quot; namespace, VS does not add them as import, but rather generates a fully qualified signature as to not change imports. I'd appreciate if VS had an option to generate the simple signature, and immediately open the suggestion bulb that asks me whether I want to import the namespace or use the qualified class name, as if I had written the code myself.</p>

---
#### Feedback Bot on 7/19/2020, 11:30 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by LWChris** [comment]
Hi @jinujoseph,

what does it mean when a request is in "Backlog" and also "Small Fixes InQueue"?

**Comment by jinujoseph** [comment]
"Backlog" -> not in immediate priority list 
"Small Fixes InQueue" -> assumed to be not a significant amt of work

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
