### ISSUE TITLE
C# array of tuples type inferrence error when nullable int

### ISSUE THREAD

**Issue by Kungitoo** [dotnet/roslyn#46638]
**Version Used**:  Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 1.0
VisualStudio.16.Preview/16.8.0-pre.1.0+30404.54
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

VS 16.8.9 Preview 1.0
C# Tools   3.8.0-1.20378.6+226c0c3f392232b3dd7ecd527f1fd00f0f86d7e4
.NET Core 3.1

**Steps to Reproduce**:

1. Write code:

            (string, bool, string, int?)[] columns = new[]
            {
                ("name", false, null, null),
                ("I26", true, "YR1", 2019)
            };

**Expected Behavior**: No errors

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/6378638/89677135-25b9be00-d8ed-11ea-877f-cc75d3fbdc5f.png)

BUT when I add a type to the second tuple:

            (string, bool, string, int?)[] columns = new[]
            {
                ("name", false, null, null),
                ("I26", true, "YR1", (int?)2019)
            };

It compiles

**Comment by CyrusNajmabadi** [comment]
This is by design. An implicit array (`new[]{•••}`), determines it's types from it's elements. In this case, with just one element there is not enough information to determine what `null` means. 

If you'd like the language to change here, a proposal will need to be filed at csharplang.
