### ISSUE TITLE
C# Interactive 32bit in 64bit VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46636]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1134338/c-interactive-32bit-in-64bit-vs.html)._

---
<p>I would like to have the ability to choose from 32-bit or 64-bit c# interactive window / view when using 64 bit Visual studio. If this is somehow already possible, please let me know how.</p>

---
#### Feedback Bot on 8/4/2020, 02:44 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by sharwell** [comment]
This should be possible already:

To load 32-bit interactive window:

```
#reset 32
```


To load 64-bit interactive window:

```
#reset 64
```

**Comment by trdsolutions** [comment]
Thanks! I did not know that, great news! :-D

**Comment by tmat** [comment]
Also available in the latest version is `#reset core`, which restarts it on .NET Core.

**Comment by lrizvi** [comment]
Greetings,

#reset 32 does not appear to be working on the latest version of dotnet interactive in a jupyter notebook. Has the directive been replaced? I receive the error CS1024: Preprocessor directive expected.

Is there an alternate way to use C# interactively in 32-bit? I am trying to reference and use a 32-bit DLL via an #r directive Thanks you!
