### ISSUE TITLE
Show/Hide member attributes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1125506/showhide-member-attributes.html)._

---
<p>Hi,</p><p>Any chance we can get the option to show/hide member attributes?<br>I make extensive use of DataAnnotations. The downside is that even the simplest models look as in the following screenshot. Now, just imagine the models that contain several properties.<br><br>There is already an extension to show/hide documentation comments. I'm attaching the screenshots as an example. It would be awesome if we can get something similar for the attributes.</p><p></p><p>Kind Regards,</p><p>Fati Iseni</p><p></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/148101-loginuimodel.png"> Image:148101-loginuimodel.png</a></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/148102-showcomments.png"> Image:148102-showcomments.png</a></p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/148103-hidecomments.png"> Image:148103-hidecomments.png</a></p><p></p><p></p>

---
#### Feedback Bot on 7/26/2020, 06:50 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Mads Kristensen [MSFT] on 7/27/2020, 10:06 AM: 

<p>This is now available in the free <a target='_blank' href="https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Tweaks" target="_blank">Tweaks extension</a></p>

**Comment by PeterMadsenDLI** [comment]
Could we please get this feature as a **global setting** of at least **hide/show al**l on a pr. file option? The ability to hide/show annotations for a given meber/property is fine, but a hide/show all feature would be really usefull. I often annotate DTO-classes and it would by really usefull to be able to hide all the annotations to get a simple view af all the properties - the annotations make it hard to read the basic properties...

**Comment by CyrusNajmabadi** [comment]
Unlikely to do this.
