### ISSUE TITLE
Additional outlining options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1133446/additional-outlining-options.html)._

---
<p>Hello,<br><br>I'd like to give a few suggestions about outlining options in Visual Studio. I think the outlining capabilities directly contribute to the overall productivity, and currently we have no much options.<br>The &quot;Ctrl+M,L&quot; (Toggle all outlining) option is great for expanding everything, and definitely we should have that in the future. But, not very functional for collapsing stuff. If you toggle and collapse, since it's recursive,  you'll end up as in the following state (Picture1). Quite frankly, I don't know how the community organizes their code, but in my case I almost never want to see my code in this state.<br><br>I'd suggest the following option:<br>- Expand-collapse for attributes (available in Tweaks extension): this option should expand/collapse only the attributes (Picture2)<br>- Expand-collapse for regions: this should work only for the region (Picture3)<br><br>If we want more general rule of this, that probably might be : collapse everything recursively inside class content. I can't find a case where this might cause issues for the community! But, once again, the community might have different preferences.</p><p>Thank you,</p><p>Fati Iseni</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/149234-picture1.png"> Image:149234-picture1.png</a></p><p></p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/149231-picture2.png"> Image:149231-picture2.png</a></p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/149232-picture3.png"> Image:149232-picture3.png</a></p>

---
#### Feedback Bot on 8/3/2020, 03:19 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
