### ISSUE TITLE
VS, build system and Roslyn (Zip) read-only VFS support for C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46635]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1137179/vs-build-system-and-roslyn-zip-read-only-vfs-suppo.html)._

---
In some scenarios you can end up with literally millions of source files, where over 99% is 3rd party code, or generated code, that you will never modify. Such filesystem pollution can be a problem. If you are running on Windows a quite severe problem, since NTFS... well, let's not go there, you all know (or should know) how bad that is.

Since there's approximately zero percent chance Microsoft would ever (be able to, even if it wanted, which it don't) implement fast hierarchical filesystem-mounting support, with filesystems optimized for various kinds of payloads, that is a dead end.

A fully user-mode and portable way to handle this problem could be to add read-only VFS support for msbuild/dotnet/VS. While researching this idea, I came across two different implementations for VSCode, so it's clearly not an unwanted feature.

While zip is inferior in just about every concievable way to other archive formats, it can be created and handled by tools on just about any operating system on the planet. It'd also still be far superior to general filesystem (such as, and especially, NTFS) for these scenarios, with the added benefit .NET already contains all the code to handle zip archives.

If you use the archive format only, without compression (a.k.a. -z0), you get multiple benefits from such a design, while still allowing such archives to reside in "chunking" SCM's (such as git) where they can be updated without incurring the otherwise massive size-explosion you could experience with compressed archives (where each revision would effectively become a whole new BLOB).

Such a design would reduce resource consumption on multiple levels, meaning less wasted RAM, disk, CPU, electricity, and in the end money.

- Memory pressure. For the curious at Microsoft, ask anyone on the Cc team how well it handles a million small files, or how large the allocation granularity is for cache data, or someone on the Ob team how much the overhead would be if trying to open a million files.

- Cache- and CPU-friendly. NT's Cc obviously works better with a large data stream than a million small ones. Since the data is uncompressed, there's no decompression-overhead on read.

- CPU. No more round-trips to kmode and back to open a file, or iterate files. This benefit becomes even larger if you are using an Intel CPU, where the Meltdown and Spectre mitigations are in effect; I have seen figures as large as 60% performance hit due to Intel's cheating.

- Disk space. The disk space savings can be significant, and that's without even mentioning how much fragmentation can be reduced (again, for the curious, ask someone on the NTFS team and see them uneasily study their shoes while trying to downplay the impact).

- OS file handles. There would be exactly one file handle per consumer to the archive containing such a collection of files. This translates to increase in speed, and reduction of OS resource consumption.

- MSBuild dependency checking. It could f.ex. know (with 100% certainty) that any file within such an archive is unmodified while the archive is open (or even the archive date is unmodified); all files within such an archive would effectively be one single lookup, instead of one million lookups (and a minimum of one million context switches).

- Roslyn speedups. This could allow for **massive** optimization for Roslyn, if it gets support to recognize such read-only mounted source trees. It could f.ex. replace the file references (currently stored as UCS-2 string representations of GUID's, I believe, i.e. a minimum of 66 bytes instead of 16 -- each) with a single DWORD containing archive # and file index #.

Please note that this could benefit not only Microsoft's customers, but also Microsoft's own developers and therefore Microsoft itself.

Anyway, you now have the idea. Do with as you please.

---
#### Feedback Bot on 8/6/2020, 00:57 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Roslyn already abstracts the file system logic to account for the possibility of loading from alternative locations. Moving this request back to the platform.
