### ISSUE TITLE
C# 9 Analyzer: Flag suspect pattern usages

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#46637]
C# 9 is going to introduce new pattern matching syntax around `or`, `and`, and `not`. There are inevitably going to end up confusing people, and I can already see the flood of questions on the C# discord about "Why does the && not do what I told it to do here?". Some examples where this can fall down:

```cs
switch ((bool?)false)
{
    case true || false: break; // Does not handle false, because false || true is a constant expression!
	case null: break;
}

if (o is 1 || true) {} // Always enters this if
```

We should consider having a rule to flag these types of suspect cases and offer to rewrite them using `or` patterns, much like we do for `!is` today. The basic rules for such an analyzer (I think) have 2 forms:

Form 1: Pattern expressions

These are things inside a pattern, such as in a case block or nested inside some other pattern. This is the much simpler case:
1. If you encounter a `||`, offer to change it to an `or`. If you encounter an `&&`, offer to change it to an `and`.

Inside a pattern, this can almost never go wrong, as everything has to be constant, or the compiler will error anyway. There are cases when you could legitimately use `||` and `&&` inside a pattern (if, say, you were composing a single boolean check out of multiple `#if`-set flags), but these cases are few, far between, confusing to the reader, and I would argue should have a warning suppression.

Form 2: Trailing `is` expression constants

These are much harder to detect and implement, and false positives are much more likely, but I think at least offering an `info` diagnostic and a refactoring would be useful. A implementation of this rule might be:

1. See an `is` expression.
2. Walk to the next node past the pattern (and trivia) of the expression. If that is not a logical operator (either `&&` or `||`), goto step 5.
3. Walk to the next sub-expression, the expression on the right of this logical operator.
4. Check the constant value of this expression. If there is no constant value, goto step 5. If there is, add the expression to a list of constants to add to the pattern, and whether it was an `and` or an `or`. Go to step 2.
5. If no constants were found, end. Otherwise, gather the list of constants and their conjunctions, and rewrite the pattern use `and`s and `or`s instead of `&&` and `||`.

Finally, we should consider having a refactoring going the other direction, particularly for non-constants. For example, if I write `if (a is nonConstant1 or nonConstant2)`, I'd get an error. A refactoring to convert that to `if (a == nonConstant1 || a == nonConstant2)` would be useful. For this idea, also consider saving `a` to a temp if it's something like a method call, as that's what the pattern form will do. Perhaps offer 2 refactorings, one that will save and one that will not.

Both of these refactorings might change the semantics of the code, so it's important to call that out. But I believe that new users will end up being confused by the different syntaxes here, and we should try to help them.

**Comment by sharwell** [comment]
I moved this back to dotnet/roslyn, since this is a language-based rule as opposed to an API-based rule. The IDExxxx rules are the same as the CAxxxxx rules in terms of their ability to run in CI.

**Comment by jasonmalinowski** [comment]
We discussed this in our design meeting and concluded that the analyzer is absolutely useful, so we should just figure out where the analyzer goes. We didn't think it belonged into roslyn-analyzers, as at this point that repository is mostly used for analyzers that validate the specific uses of certain APIs are correct. We discussed whether it's worth making changes to the style analyzers, because we could then count these as 'style' issues where the parenthesis weren't placed correctly, but concluded that style analzyers aren't really the best place to flag _correctness_ issues -- even if somebody has style warnings turned off they'd want to know their code isn't doing what they think.

Ultimately we didn't have an answer why these warnings shouldn't just be emitted by the compiler, enabled by an appropriate warning wave, and figured we should start that conversation to determine if that makes sense. @mavasani or @sharwell who wants to drive that?

**Comment by jmarolf** [comment]
@333fred is there a reason this can't be part of a warning wave in the compiler?

**Comment by 333fred** [comment]
It might be possible. However, a few issues with this come to mind immediately:

1. We generally tend to view compiler warnings as "This code is technically correct, but 99% of the time this is not what you want." I'm not sure either of these warnings would meet that bar, particularly the after-`is` check.
2. It seems likely that, in order to implement the fixers for these issues, the IDE is going to have to reimplement the entire analysis again in order to construct the rewritten `or`/`and` blocks.
3. Warning waves is an opt-in, new project scenario. Some people will adopt them in previous-framework projects, of course, but I wouldn't want these IDE-assistance features gated behind the warn level.

@gafter, did you have thoughts on this proposal, and whether they would make good compiler-level warnings?

**Comment by jmarolf** [comment]
This feels like 1 to me and since we set a default warning wave based upon TFM the hope is that most users would be opted in here.

**Comment by CyrusNajmabadi** [comment]
So these patterns have been out a while, and we haven't actually gotten signals indicating people are having these sorts of problems with them.  As such, i'm going to close this out.
