### ISSUE TITLE
Improve NormalizeWhitespace for multi block lambdas

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#46656]
**Version Used**:
I'm linking:

```xml
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.7.0-4.final" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.0-beta1.final" PrivateAssets="all" />
```

**Steps to Reproduce**:

Call NormalizeWhitespace() on the following csharp code:
```csharp
class C
{
     void M()
     {
           M1(() => {});
     }
     void M1(Action a){}
}
```

**Expected Behavior**:
Normalizes to:

```csharp
class C
{
     void M()
     {
           M1(() => 
           {
           });
     }

     void M1(Action a)
     {
     }

}
```

**Actual Behavior**:

```csharp
class C
{
     void M()
     {
           M1(() =>
           {
           }

           );
     }

     void M1(Action a)
     {
     }

}
```

I'm happy to fix this myself if this is the sort of breaking change you're prepared to take.

**Comment by CyrusNajmabadi** [comment]
We'd take a PR here.  While we wouldn't normally want unnecessarily disruptive changes in the default formatter, this is an example of clearly broken behavior that is fine to improve on.
