### ISSUE TITLE
[C# 9.0]  "Use pattern matching" should fix negative pattern to use "is not" syntax

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46699]
Similar to  https://github.com/dotnet/roslyn/issues/46698, except "Use pattern matching" should fix negative pattern it has already generated in previous versions.

**Version Used**: 
Version 16.8.0 Preview 2.0 [30404.163.master] with C# 9.0

**Steps to Reproduce**:

``` C#
            if (!(current is string value))
            {

            }
```

**Expected Behavior**:
"Use pattern matching" (or someother code fix) suggests:

``` C#
            if (current is not string value)
            {

            }
```

**Comment by lindexi** [comment]
It is not a string, but what is the value ?
