### ISSUE TITLE
[Analyzer Suggestion] Use IsNot operator instead of Not .... Is

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46706]
**Brief description:**

Use `IsNot` operator instead of `Not ... Is`

**Languages applicable:**

Visual Basic

**Code example that the analyzer should report:**

```vb
Public Sub MySub(s As String)
    If Not s Is Nothing Then ' This should be fixed to: "If s IsNot Nothing Then"
        Console.WriteLine(s)
    Else
        Throw New ArgumentNullException(NameOf(s))
    End If
End Sub
```

**Additional information:**

Using `IsNot` operator is much more readable than "Not ... Is".

**Comment by sharwell** [comment]
We should include this case in the same analyzer that implements #46798

**Comment by CyrusNajmabadi** [comment]
There's very little to share here.  I would just write a new analyzer/fixer.  I think it woudl be fine to have a community contribution here for that.
