### ISSUE TITLE
[C# 9.0] "Use implicit type" incorrectly tries to fix target-typed new expressions

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46701]
**Version Used**: 
Version 16.8.0 Preview 2.0 [30404.163.master] with C# 9.0

**Steps to Reproduce**:

``` C#
List<string> values = new();

```

**Expected Behavior**:
"Use implicit type" to not suggest anything

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1103906/89858901-12f00380-dbe3-11ea-96a6-83e9e6bccbdd.png)

**Comment by CyrusNajmabadi** [comment]
@ryzngard were you fixing this?

**Comment by ryzngard** [comment]
I was fixing nullability, not target typed new

**Comment by davidwengier** [comment]
I fixed this in #46469
