### ISSUE TITLE
Autocomplete list contains "and"/"or" in member access after tuple discard

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#46711]
**Version Used**: VS 16.8 Preview 1

**Steps to Reproduce**:

```c#
void M()
{
    _ = (0, 0) switch
    {
        (_, int.$$) => throw null
    };
}
```

Invoke the autocomplete list at the marked location.

**Expected Behavior**: Only the member of the type are included in the autocomplete list.

**Actual Behavior**: The autocomplete list contains the type's members, as well as `and` and `or`.

![image](https://user-images.githubusercontent.com/823398/89921403-f01f1880-dbfd-11ea-9cc4-1d43f88b8f1d.png)

**Comment by Youssef1313** [comment]
Similar to https://github.com/dotnet/roslyn/issues/51431, but the difference is that this one is for switch expressions, while the other is for switch statement.

**Comment by CyrusNajmabadi** [comment]
Fixed.  Have verified:

![image](https://user-images.githubusercontent.com/4564579/153944688-672339ea-0b29-4032-b310-9af7720afc61.png)
