### ISSUE TITLE
StreamJsonRpc that ships for interactive host needs an upgrade

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#46719]
The StreamJsonRpc that's used for the Interactive Host is still at v2.4.34, which shipped with 16.6 and is missing reliability fixes we've made since then.

In 16.8, please upgrade to at least the latest v2.5 release, if not v2.6 which ships in 16.8.

You can read the release notes for [StreamJsonRpc](https://github.com/microsoft/vs-streamjsonrpc/releases) and [Nerdbank.Streams](https://github.com/AArnott/Nerdbank.Streams/releases) to get a feel for what the immediate window is missing.

**Comment by CyrusNajmabadi** [comment]
is this still needed @tmat ?

**Comment by tmat** [comment]
We are now using the same version as Roslyn.
