### ISSUE TITLE
Implement interface feature does not order correctly

### ISSUE THREAD

**Issue by Ravenheart** [dotnet/roslyn#4671]
Greetings, a little bug in the way that the "Implement interface" feature works in VS2015 with roslyn vs older VisualStudio versions.

```
    public interface ITestInterface
    {
        void MethodC();
        void MethodB();
        void MethodA();
    }

    public class TestClass : ITestInterface
    {
    }
```

Roslyn:

```
    public class TestClass : ITestInterface
    {
        public void MethodA()
        {
            throw new NotImplementedException();
        }

        public void MethodB()
        {
            throw new NotImplementedException();
        }

        public void MethodC()
        {
            throw new NotImplementedException();
        }
    }
```

Older VisualStudios

```
    public class TestClass : ITestInterface
    {
        public void MethodC()
        {
            throw new NotImplementedException();
        }

        public void MethodB()
        {
            throw new NotImplementedException();
        }

        public void MethodA()
        {
            throw new NotImplementedException();
        }
    }
```

In old VS versions the implemented methods/properties/etc would keep the order in which they were declared in the interface, in VS2015/roslyn it orders them alphabetically and does not keep the original order.

**Comment by Pilchie** [comment]
Not sure what the right thing to do here is.

**Comment by Ravenheart** [comment]
If possible have it respect the order in which they were declared in the interface, its just a minor annoyance because you have to re-order the implemented methods/members after it auto implements them.

**Comment by DustinCampbell** [comment]
We've received additional requests to fix this through Visual Studio feedback. Let's try to get this fixed for 1.3.

**Comment by Pilchie** [comment]
Note that #15404 now does this for `ComImport` interfaces.

**Comment by CyrusNajmabadi** [comment]
This was already addressed with: https://github.com/dotnet/roslyn/pull/15396   You can now opt-out of our auto-ordering and can choose:

![image](https://cloud.githubusercontent.com/assets/4564579/22093446/940f55e0-ddba-11e6-9b3a-66f188723622.png)

If you check this, you will get:

```c#
public class TestClass : ITestInterface
{
    public void MethodC()
    {
        throw new NotImplementedException();
    }

    public void MethodB()
    {
        throw new NotImplementedException();
    }

    public void MethodA()
    {
        throw new NotImplementedException();
    }
}
```

**Comment by verelpode** [comment]
As @CyrusNajmabadi said, if you set the option to `"at the end"`, it does eliminate the undesired alphabetical re-ordering.  Great, thanks.  However, should this option be renamed or split with a **separate** "alphabetical" tickbox?  Sorry if I'm being picky, but it seems very non-obvious that this "at the end" option controls whether it does alphabetical re-ordering or not.  For a long time, I was repeatedly irritated by the alphabetical re-ordering and I only found out today that "at the end" solves the problem.

When you set the option to `"with other members of the same kind"`, then it sorts them alphabetically, but why must it use alphabetical sorting with that option?  I think it would be possible to **separately** enable or disable alphabetical sorting regardless of whether `"with other members of the same kind"` versus `"at the end"` is chosen.  Alphabetical is actually a separate issue but currently it is confusingly mixed into an option that actually controls placement.  

_Placement and ordering are actually separate issues,_ but currently they are confusingly combined into one option called `"When inserting properties, events and methods, place them: ..."`.     Notice how the current option explicitly says **"place them"** but currently it controls not only placement but also ordering and that's confusing.   I'm saying that **placement and ordering should be separate options**.  I hope my explanation is understandable.

Re the default behavior, I think the default should be to generate the methods/members in the same order as defined in the interface (or inherited abstract class).  Whenever people write an interface, they usually write the methods/members in a meaningful order, and related members are often grouped together.

For example, if an interface contains properties "IsPositiveValue" and "IsNegativeValue" and a method "InvertSign", then these 3 members are related and are placed together like this:

```
interface MyExampleInterface
{
	// Members for getting or changing sign of a number.
	bool IsPositiveValue { get; }
	bool IsNegativeValue { get; }
	void InvertSign();
	
	// Members for math operations.
	void Add();
	void Subtract();
	...
	...
	
	// Miscellaneous members.
	bool IsNotBlahBlah { get; }
	bool IsEmpty { get };
	...
}
```

If the "Implement interface" (or "Implement Abstract Class") command generates the members in alphabetical order as follows, the meaningful ordering is lost.  As you can see following, members unrelated to the topic of "number sign" are inserted in-between.  
* InvertSign
* IsEmpty 
* IsNegativeValue 
* IsNotBlahBlah 
* IsPositiveValue

**Comment by CyrusNajmabadi** [comment]
>  Great, thanks. However, should this option be renamed or split with a separate "alphabetical" tickbox? Sorry if I'm being picky, 

Enh... at some point you don't want to overload with options.  I think the current experience is fine.  There's been zero additional feedback on this, so i'd prefer to just leave as is.

**Comment by verelpode** [comment]
Fair enough.  Other issues are more important.  I just wish I had discovered the meaning of "at the end" earlier, before I manually did what could have been done automatically, for a bunch of classes.

**Comment by dsherret** [comment]
Very annoying behaviour. Interface members are often ordered by semantics, so when auto-implementing an interface, it making it alphabetical means I then need to manually change the order back to what I had in the interface. For example:

```cs
public interface IAction
{
    Task Pre();
    Task Main();
    Task Post();
}

public class MyAction : IAction
{
    public Task Main()
    {
        throw new NotImplementedException();
    }

    public Task Post()
    {
        throw new NotImplementedException();
    }

    public Task Pre()
    {
        throw new NotImplementedException();
    }
}
```

TypeScript's auto-implement interface gets this right:

```ts
interface IAction
{
    pre(): Promise<void>;
    main(): Promise<void>;
    post(): Promise<void>;
}

class MyAction implements IAction {
  pre(): Promise<void> {
    throw new Error("Method not implemented.");
  }
  main(): Promise<void> {
    throw new Error("Method not implemented.");
  }
  post(): Promise<void> {
    throw new Error("Method not implemented.");
  }
}
```

If Roslyn just ordered by what the dev wrote then the output order could be easily adjusted by the dev.

**Comment by CyrusNajmabadi** [comment]
We dummy bother doing anything like this as methods are not guaranteed any  order in metadata. 

This is not the same as in TS where order is significant and is maintained. 

As long as yours is not guaranteed by the compiler or the runtime, we intend for the feature to work this way.

**Comment by dsherret** [comment]
Apologies, I just realized the "at the end" setting does the behaviour I want. I agree with the feedback that it's not very obvious 😅
