### ISSUE TITLE
Use the new MemberNotNullAttribute on IsInSource to indicate that SourceTree will not be null when it's true

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46729]
💡 Remove this assertion, and use the new member not null attribute on `IsInSource` to indicate that `SourceTree` will not be null when it's true. See #46529 for an example of these attributes (you can either copy that change to define them, or wait for it to merge).

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/46409_

**Comment by mavasani** [comment]
Not sure if we want to track this separately, or as a part of #41964. Tagging @jcouv. Feel free to close this out as a dupe if appropriate.

**Comment by jasonmalinowski** [comment]
@mavasani which IsInSource? I already annotated this one here: https://github.com/dotnet/roslyn/blob/885d56ef4f192100c0b48eae8e6a91188badfe71/src/Compilers/Core/Portable/Diagnostic/Location.cs#L33

**Comment by mavasani** [comment]
@jasonmalinowski Thanks. Let me close this issue and fix my PR then :-)

**Comment by jasonmalinowski** [comment]
@mavasani Yeah, that was the only one I did because it was just too useful to not have. :-)
