### ISSUE TITLE
Add RPS typing test for repo with editorconfig at repo root

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46721]
We don't seem to have any RPS validation for typing in a solution with an editorconfig at repo root - it seems like we recently had a typing regression sneak in where squiggles/error list refresh is delayed by 20+ seconds for a decently big solution with an .editorconfig at repo root. Given that this is expected to be the most common setup for all the latest/modern repos, we should add such a test OR convert some existing test to have an .editorconfig at repo root.

**Comment by mavasani** [comment]
Tag @genlu @dotnet/roslyn-infrastructure

**Comment by mavasani** [comment]
@genlu if this is a dupe of other tracking work item, please resolve appropriately. I think we ought to prioritize this though..

**Comment by genlu** [comment]
We do have plan to add unofficial RPS test for our team, if this is what you have in mind, then great. Otherwise, if you are talking about official RPS, we might need to discuss a bit more. 
Either way, we can use this issue to track that work.

**Comment by mavasani** [comment]
@genlu Any kind of perf test is fine.
