### ISSUE TITLE
ClassExpressionSyntax .WithModifiers() Broken

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#4673]
If you start with this code:

    namespace ConsoleApplication1
    {
        /// <summary>
        /// My XML doc for MyClass...
        /// </summary>
        class MyClass
        {
        }
    }

And take the ClassExpressionSyntax given by it and add an access modifier, like so:

    private Task<Solution> AddModifier(Document document, SyntaxNode root, SyntaxNode statement, Accessibility accessibility)
    {
        SyntaxNode newStatement = null;
        var accessModifierTokens = SyntaxFactory.TokenList(AccessModifiers(accessibility));

        if (statement is ClassDeclarationSyntax)
        {
            var classExpression = (ClassDeclarationSyntax) statement;

            var newClass = classExpression.WithModifiers(accessModifierTokens.AddRange(classExpression.Modifiers));
            newStatement = statement.ReplaceNode(statement, newClass);
        }
        // ...

        var newRoot = newStatement == null ? root : root.ReplaceNode(statement, newStatement);
        return Task.FromResult(document.WithSyntaxRoot(newRoot).Project.Solution);
    }

You get this uncompilable code:

    namespace ConsoleApplication1
    {
        internal
        /// <summary>
        /// My XML doc for MyClass...
        /// </summary>
        class MyClass
        {
        }
    }

I would expect it would produce this:

    namespace ConsoleApplication1
    {
        /// <summary>
        /// My XML doc for MyClass...
        /// </summary>
        internal class MyClass
        {
        }
    }

The rest of the code I'm using can be seen here: https://github.com/Vannevelj/VSDiagnostics/tree/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Diagnostics/General/ExplicitAccessModifiers

**Comment by pdelvo** [comment]
roslyn is doing the right thing. it adds a modifier before the class keyword (that has the documentation as its leading trivia). Adding a modifier is a little bit more complicated. Have a look at this: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/8bfe6ab4d80b174c0e8cec6966e5fdbf5cd0fe4b/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DeclarationModifiersHelper.cs

**Comment by Hosch250** [comment]
OK, thanks for the update.  I found this roundabout code works:

    var newClass =
        classExpression
            .WithoutLeadingTrivia()
            .WithModifiers(accessModifierTokens.AddRange(classExpression.Modifiers))
            .WithLeadingTrivia(classExpression.GetLeadingTrivia());

**Comment by mattwar** [comment]
You'll probably want to do it this way:

```
var classWithoutTrivia = classExpression.WithoutLeadingTrivia()
var newClass = classWithoutTrivia
                          .WithModifiers(accessModifierTokens.AddRange(classWithoutTrivia.Modifiers))
                          .WithLeadingTrivia(classExpression.GetLeadingTrivia());
```

because the first modifier is probably also going to have the leading trivia attached to it too.

You can also use the SyntaxGenerator class in Microsoft.CodeAnalysis.Editing namespace to change the modifiers on the class.  It will do the trivia negotiation for you and gauarantee the modifiers are all in correct order.

**Comment by Hosch250** [comment]
@mattwar Thank you so much.  That is definitely the right way to do it - I was able to remove over 10 if-statements determining type!
