### ISSUE TITLE
Inadequate proposal for removing a conversion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46756]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1144907/inadequate-proposal-for-removing-a-conversion.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I have the following VB.NET code:

```
  Private Sub Foo()
    Dim Bar = "1"
    Select Case CInt(Bar)
      Case 1
      Case 2
      Case 3
    End Select
  End Sub
```
IntelliSense remarks that the conversion to an int is redundant. But this is obviously wrong because of the following cases, which distinct between different int values.

---
#### Feedback Bot on 8/11/2020, 03:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be changing behavior in this area.
