### ISSUE TITLE
Signature completion for extended partial methods

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#46752]
Related to #43795

**Version Used**: 226c0c3

**Steps to Reproduce**:

```cs
partial class Program
{
    public static partial int M1();

    partial void M2();

    partial $$ // cursor here
}
```

**Expected Behavior**:
Completion list shows options for M1 as well as M2

**Actual Behavior**:
Completion list only shows an option for M2

![image](https://user-images.githubusercontent.com/5833655/90024696-05319100-dc6a-11ea-826b-43eb35b0926d.png)

Most likely the change needs to be made in [`PartialMethodCompletionProvider`](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Completion/CompletionProviders/PartialMethodCompletionProvider.cs).

**Comment by RikkiGibson** [comment]
FYI @CyrusNajmabadi I think we are out of time to do this in 16.8, so punting to 16.9.

**Comment by CyrusNajmabadi** [comment]
Uh... Doesn't this work already? :-)

**Comment by RikkiGibson** [comment]
No.

**Comment by CyrusNajmabadi** [comment]
I see:

![image](https://user-images.githubusercontent.com/4564579/95095215-a1629c00-06df-11eb-8551-b758e029f170.png)

**Comment by RikkiGibson** [comment]
Looks like you did it in #47764 :) Thanks! I just didn't see the changed behavior, perhaps because it hasn't gotten into public preview yet.
