### ISSUE TITLE
Missing using when Move To "class.cs" Quick-Action 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46757]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1146327/missing-using-when-move-to-classcs-quick-action.html)._

---
When using the Move To Quick-Action to move a class into a seperate file the line

using System.Linq; 

is often not added to the new file and must be added manually afterwards.
The System.Linq seem to be the only using missing in my experience.

This problem have existed in VS for months, maybe even years.

This is however not always the case.
By moving the following code to a seperate file the System.Linq will be MISSING in the new file:

    public class MyClass2
    {
        public List<string> Mylist;
        public List<string> GetList
        {
            get { return GetList.ToList(); }
        }
    }

If you try to move the following, however, the System.Linq using IS ADDED to new file:

    public class MyClass
    {
        public void Test()
        {
            List<string> list = new List<string>();
            List<string> newList= list. ToList();
        }
    }

---
#### Feedback Bot on 8/12/2020, 01:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
Cannot repro.

Roslyn version: https://github.com/dotnet/roslyn/commit/d4cbcb54a3351d642ca589767dc1b205c4ab0363
Implicit usings: disabled.

`Program.cs` before:
```cs
using System.Collections.Generic;
using System.Linq;

class Program
{

}

public class MyClass2
{
    public List<string> Mylist;
    public List<string> GetList
    {
        get { return GetList.ToList(); }
    }
}
```

`Program.cs` after executing action "Move type to MyClass2.cs":
```cs
class Program
{

}
```

`MyClass2.cs`:
```cs
using System.Collections.Generic;
using System.Linq;

public class MyClass2
{
    public List<string> Mylist;
    public List<string> GetList
    {
        get { return GetList.ToList(); }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me either.
