### ISSUE TITLE
GitHub Wiki updated, but not the docs folder

### ISSUE THREAD

**Issue by andrew-boyarshin** [dotnet/roslyn#46753]
[/docs/wiki/NuGet-packages.md](https://github.com/dotnet/roslyn/blob/master/docs/wiki/NuGet-packages.md) is missing the latest change of [NuGet-packages](https://github.com/dotnet/roslyn/wiki/NuGet-packages) wiki page (AzDO NuGet feed link). NuGet package references <https://aka.ms/roslyn-packages> which redirects to `docs/`, but it is out-of-date.

**Comment by RikkiGibson** [comment]
@jmarolf Can we address this by deleting the wiki pages which have been copied over to the docs folder and making any necessary updates in-repo? Or possibly changing the wiki pages content to just link to the corresponding in-repo document

**Comment by jmarolf** [comment]
yeah, I'll kick this can again. We need to just delete the wiki

@sharwell and @jasonmalinowski who has the definitive list of aka.ms links that point to the wiki? who do I talk to to get the updated?

**Comment by jasonmalinowski** [comment]
There might be a way to query the system; I don't know. That said, I do like the wiki for random things that don't really need to flow with the code. I like the docs folder too, but I guess personally I'm not outright wanting to reduce to one...

**Comment by jmarolf** [comment]
Wiki is perpetually out of date and externals are unable to contribute fixes. I see no benefit to the wiki. Last time I asked to delete the wiki folks told me there were links in official docs to the wiki. If this is not true that I propose we just delete it.

**Comment by RikkiGibson** [comment]
official docs are mostly backed by a set of well-known git repos. @BillWagner is it possible for us to track down and replace any Roslyn wiki links in official docs with the new in-repo links? I imagine it is just a matter of pulling down certain repos, running a find->replace, and sending a PR?

**Comment by BillWagner** [comment]
@RikkiGibson Any links to the roslyn wiki would be one of these two repos:

- [.NET conceptual docs](https://github.com/dotnet/docs)
- [.NET Roslyn API docs](https://github.com/dotnet/roslyn-api-docs)

I did a quick check, and I didn't see any mention. In time, I want to repurpose some of the tutorials and walkthroughs that are in the wiki and publish them. These would be for the roslyn analyzers, code fixes, and refactorings.

I have a fork of the wiki, so I will still be able to do that.

**Comment by jmarolf** [comment]
@BillWagner  everything in the wiki should be in https://github.com/dotnet/roslyn/tree/master/docs/wiki. If there are no external references to our wiki I propose we remove it. @jasonmalinowski any objections?

**Comment by jasonmalinowski** [comment]
Did we check aka.ms and fwlink? Because that's what got broken last time.

I also still wish we were leaving some pages in the wiki in the first place, but that's my take. 😦

**Comment by BillWagner** [comment]
> Did we check aka.ms and fwlink?

I did not.

**Comment by PathogenDavid** [comment]
It might be more trouble than it's worth, but has anyone investigated using automation to automatically sync the docs/wiki/ folder to the the wiki? I'm no fan of GitHub Wikis, but even if there's no official documentation linking to it there's inevitably going to be blog posts and StackOverflow answers that do.

**Comment by jmarolf** [comment]
the wiki has been removed there should now only be once source of info on this topice
