### ISSUE TITLE
Show items from unimported namespaces shows types that are invalid given signature constraints

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#46768]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 1.0
VisualStudio.16.Preview/16.8.0-pre.1.0+30404.54

**Steps to Reproduce**:

Given an API like:

```csharp
interface IMessageBus
{
   IDisposable Subscribe<TEvent>() where TEvent : IEventMessage;
   ValueTask ExecuteAsync(IActionMessage action, CancellationToken cancellation = default);
}
```

With the option turned on, the completion will be populated with all available types in both cases:

```csharp
IMessageBus bus = ...;

var subs = bus.Subscribe<[WONG COMPLETION HERE]>

await bus.ExecuteAsync(new [WRONG COMPLETION HERE])
```

In the first case, it will show types that do now satisfy the `where TEvent : IEventMessage` generic constraint. In the second case, it will show types that do not implement the interface required in the method argument signature.

This makes the feature much less useful than it could otherwise be, since it's quite noisy and does not help discovering the actual available types to fulfill the API parameters.

**Comment by CyrusNajmabadi** [comment]
> await bus.ExecuteAsync(new [WRONG COMPLETION HERE])

For that, there is no concept of 'correct' completion.  after all, you could easily write: `new SomeOtherType().DoSomething.That() + Finally().Results(in, your, arg, type)`.

For

> var subs = bus.Subscribe<[WONG COMPLETION HERE]>

We could potentially introduce some sort of filtering, if we can ensure the perf cost of that is acceptable.

**Comment by kzu** [comment]
Fair enough on point 1. Plz consider allowing completion providers to cleanup the list in case they "know more" about the intended usage pattern devised by the library/analyzer author ;)

**Comment by CyrusNajmabadi** [comment]
>Plz consider allowing completion providers to cleanup the list in case they "know more" about the intended usage pattern devised by the library/analyzer author 

I'm not sure how that would work. Can you expand on your thoughts here?  Thanks!

**Comment by kzu** [comment]
Dunno, maybe the completion provider gets a callback to also filter completions, in addition to providing completions? But that would likely need to be able to be opted out from a badly written one, so maybe allow disabling completion providers by name or some identifier? Just like you can disable analyzes if you really don't want their behavior (and granularly too).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback/movement.
