### ISSUE TITLE
Fixing IDE0008 adds several tabs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46779]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1142193/fixing-ide0008-adds-several-tabs.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
When trying to fix an IDE0008 VS adds several tabs to "fix"  the issue. Even the preview knows that's wrong (see video)

![image](https://user-images.githubusercontent.com/1408396/90075326-f2db4580-dcb1-11ea-9edb-30f4edca26b5.png)

---
#### Feedback Bot on 8/10/2020, 02:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/12/2020, 09:39 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The code fix for IDE0008 should not be altering trivia, even if the formatter would.

**Comment by kblok** [comment]
Reporter here ✋🏼 In case you need more info.

**Comment by CyrusNajmabadi** [comment]
@kblok i can't repro this.  can you supply a repro?
