### ISSUE TITLE
Editorconfig severity changes not respected

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46784]
**Version Used**: Latest 16.8 P2 dogfood build

**Steps to Reproduce**:

1. Create a new C# class library project with below source code and verify `IDE0051` reported for `M`:
```csharp
class C
{
    void M() { }
}
```

2. Add an .editorconfig manually file at root of the project with following contents:
```ini
[*.cs]

dotnet_diagnostic.IDE0051.severity = warning
```

3. Switch back to the source file and see the diagnostics/squiggles on `M`

**Expected Behavior**:
IDE0051 warning in error list and a squiggle for the same in the editor

**Actual Behavior**:
IDE0051 is still a message and there is no squiggle.

4. Keep editing the source file, say renaming `M` to `M2`, renaming the containing type, adding more code, etc.

**Expected Behavior**:
.editorconfig `dotnet_diagnostic` should take effect at least after doing some source code edits.

**Actual Behavior**:
IDE0051 is still a message and there is no squiggle. The diagnostic correctly gets updated to say `M2` instead of `M`, so diagnostics are not stale - just the fact that new editorconfig settings are not being applied at all. Only way to get these applied are to close and re-open/reload the project.

**Comment by mavasani** [comment]
I verified that issue started happening after https://github.com/dotnet/roslyn/pull/44331. It does not repro on 16.8 P2 builds prior to that change getting merged. @jasonmalinowski can you take a look? I'll try to work on an integration test to repro this behavior.

**Comment by sharwell** [comment]
I observed this as well when testing from the master branch.

**Comment by mavasani** [comment]
I was able to write an integration test for this regression: https://github.com/dotnet/roslyn/pull/46794
