### ISSUE TITLE
"error CS0535: x does not implement interface member y" only thrown if using Nullable reference types

### ISSUE THREAD

**Issue by sidney-pauly** [dotnet/roslyn#46788]
### Description
While working with generic interfaces and default implementing the I encountered a very strange bug. Consider the following combination of interfaces and classes:
```
namespace A
{

    public interface CustomKeyType
    {

    }

    public interface MyReadonlyInterface<T>
    {
        IReadOnlyDictionary<CustomKeyType, T> Nested { get; }
    }

    public interface MyDefaultImplementingInterface<T> : MyReadonlyInterface<T>
    {
        IReadOnlyDictionary<CustomKeyType, T> MyReadonlyInterface<T>.Nested => _Nested;

        protected Dictionary<CustomKeyType, T> _Nested { get; set; }
    }
}
```

And   

Important for reproducing the error: Implement this in another package:

```
namespace B
{

    public class SpecificClass : MyDefaultImplementingInterface<string>
    {
        Dictionary<CustomKeyType, string> MyDefaultImplementingInterface<string>._Nested { get; set; } = new Dictionary<CustomKeyType, string>();
    }

}
```

Quick explanation: A read-only interface with a dictionary is introduced. The read and write interface is built on top and default implements the read-only property. A class is built which implements the full interface but narrows down the generic type to string.   

#### Now the wired part:   
If you compile this code with .net standard 2.1 with a standard .csproj configuration it works fine. If you enable nullable reference types (`<Nullable>enable</Nullable>`) a compiler error appears:   
`SpecificClass.cs(8,34,8,72): error CS0535: 'SpecificClass' does not implement interface member 'MyGenericInterface<string>.Nested'`

On its own, it seems like an issue with the nullable system and how it is used here, but the wired thing is that you can get it to compile by changing one of the following: 
- Put `SpecificClass` in the same package
- Use a value type as the Dictionary key (e. g. string)
- Implement a property directly (e.g. `T Nested {get; set;}` instead of `Dictionary<key, T> Nested {get; set}`
- Change nullable enable to false only in package A   

#### Note:   
- Not narrowing down the generic in the implementing class does not change the behaviour
- Changing the access modifier of the Nested property to `public `does not change the behaviour
- The error is only produced when actually compiling, the Language Server with in VS2019 does not complain about the error.

### Configuration

- .net standard 2.1
- Win 10
- Debug | Any CPU
- Nullable>enable</Nullable>

The .csproj of project A should look like this:
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
```

### Workaround
You can reimplement the Nested property in the inherited class, but this does defeat the purpose of default implemented properties.

#### Edits:
16.08 20:06: Spelling

**Comment by RikkiGibson** [comment]
Is this something you fixed @cston?

**Comment by cston** [comment]
@sidney-pauly, thanks for reporting and providing a repro. This issue has been fixed recently in https://github.com/dotnet/roslyn/pull/47251.
