### ISSUE TITLE
Offer to upgrade `!(x is Y y)` to `x is not Y y` in C#9

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#46798]

**Comment by sharwell** [comment]
📝 This analyzer and fix should also support the `IsNot` keyword for Visual Basic (#46706)

**Comment by CyrusNajmabadi** [comment]
enhhhhhhhhhh :)  i'm ok with that coming in a separate feature.

**Comment by CyrusNajmabadi** [comment]
> 📝 This analyzer and fix should also support the IsNot keyword for Visual Basic (#46706)

Ok, i'll do it :)
