### ISSUE TITLE
Add inline parameter name hint support for the narrator

### ISSUE THREAD

**Issue by akhera99** [dotnet/roslyn#46797]

**Comment by CyrusNajmabadi** [comment]
@akhera99 do we still need this?  Is this an accessibility requirement?

**Comment by akhera99** [comment]
> @akhera99 do we still need this? Is this an accessibility requirement?

I have a PR out for it right now testing it actually. Still need to discuss what we intend for the narrator to say.
https://github.com/dotnet/roslyn/pull/64281/files

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
