### ISSUE TITLE
Go-to impl with symbols in multi-targetting projects still not working for async

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#46818]
Using Visual Studio 16.7.0.  After the fix submitted for #43479 this issue still exists, with implementations of async interface methods across projects using different frameworks.

Create a .NET Core console project.  Add a new class library project to the solution and reference it from the console project.  Ensure the .NET Core console project uses framework `netcoreapp3.1` and the class library uses framework `netstandard2.1`.  Add this interface and implementation to the class library:

```
    public interface IStringCreator {
        Task<string> CreateStringAsync();
    }
    public class StringCreator : IStringCreator {
        public async Task<string> CreateStringAsync() {
            return "Another hello world - async!";
        }
    }
```

Make `Main` async and add this code:

```
    IStringCreator strCreator = new StringCreator();
    var result = await strCreator.CreateStringAsync();
```

Navigate the cursor over `CreateStringAsync` and hit ctrl+F12 to go to implementation.  Visual Studio says the symbol has no implementations, but should find the implementation.  It does if the class library uses `netcoreapp3.1`.

**Comment by sharwell** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This appears to be talking abou a different issue.  This is not a multi-targetting case.  i.e. we don't have a project with linked files targetting different frrameworks.  This is more of a cross-targetting case.  I'll look into this though to see if i can figure out what's breaking this.  It may have to do with Task<>.
