### ISSUE TITLE
New rule proposal: simplify explicit type qualification by introducing using directive

### ISSUE THREAD

**Issue by prlcutting** [dotnet/roslyn#46825]
Code is sometimes unnecessarily verbose due to explicit type qualification, e.g.:

```csharp
var now = System.DateTime.Now;  // Bad - explicit namespace qualification
```

Could be simplified to this:

```csharp
using System;

var now = DateTime.Now;  // Good - terse due to added using directive
```

This example isn't too egregious of course since it's just the `System` namespace which is pretty terse, however, some examples are very long and ugly which detrimentally impacts code readability.

I would like to see a rule added that would detect these occurrences and emit a warning.  Severity should be configurable of course through .editorconfig, but propose defaulting to "Suggestion".  A corresponding quick-fix that offered to simplify usage by introducing the appropriate `using` directive would be very helpful.

This request comes with the obvious caveat that there are instances where explicit type qualification is necessary to avoid ambiguity between two or more types with the same name, but in different namespaces.  In these situations, the warning should not be emitted.

**Comment by miloush** [comment]
How do you suggest namespace aliases to be handled?

```C#
using Sys = System;

var now = Sys.DateTime.Now; // God or Bad?

now = global::System.DateTime.Now; // Good or Bad?
```

If I was not to turn such feature off, I would want to be able to specify exceptions for types or namespaces. Sometimes fully qualified type is used on purpose to make it clear it's exceptional or not to pollute the intellisense.

> [when resolving ambiguity] ambiguity should not be emitted

I am afraid this might be a bit harder problem than you envision, as you need to check not only the type that is fully qualified, but also every other type in the code with every type in the namespace you are considering using (as the conflict can arise elsewhere).

**Comment by prlcutting** [comment]
I think namespace aliasing is a very conscious and deliberate decision on the part of the developer, so by default the analyzer should skip them in the warning reporting process.

Usage of `global::` to reference the global namespace is a rare occurrence in user authored code, and is likely a very deliberate decision if encountered.  I think a reasonable default behavior would be to have the analyzer ignore these in the warning reporting process too.

I'm aware that `::global` is commonly used in auto-generated code.  In fact, more generally, full type qualification is perhaps more common in auto-generated code, so a sensible default would be to ignore evaluation of this rule for auto-generated files (those marked with the `<auto-generated/>` tag).

To the extent that any of these "default" behaviors could be customized through additional settings in .editorconfig would of course be beneficial in providing additional flexibility/configuration.  And to that point, I agree with you that it may be desirable to provide exceptions for specific namespaces.

Even if none of this configuration was offered in an initial release, you would still have the option of suppressing the warning if it didn't fit your code base, which would be equivalent to the status quo behavior of today (i.e., without the rule).

**Comment by CyrusNajmabadi** [comment]
The work would be predicated on an implementation/algorithm that coud actually make this determination safely and efficiently.  First, we have to make totally sure that removing the namespace qualification will result in the same name (complex, but doable) and that adding the `using` won't change any meaning (complex, but doable).  Second, we have to do the above in a reasonable amount of time (tough).

If that can be demonstrated, i woudl be amenable to such a rule.

**Comment by prlcutting** [comment]
That sounds good and pragmatic to me.  Thanks for considering this proposal.  I think it would be a useful addition to the Roslyn analyzers that would improve code quality/readability/maintainability and one that the community would appreciate.

**Comment by genlu** [comment]
Design meeting notes:

We don't want this as analyzer/codefix. Implement as refactoring instead #47595
