### ISSUE TITLE
CSharpAsAndNullCheckTests.FixAllInDocument1_CSharp9 appears multiple times and sometimes fails

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#46821]
Relates to PR https://github.com/dotnet/roslyn/pull/46645

![image](https://user-images.githubusercontent.com/12466233/90260306-2cba6200-de00-11ea-9767-e82921c8f06a.png)

**Comment by jcouv** [comment]
FYI @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
It appears multiple times because we have tests linked into two test projects.  Why does it fail in one of them?  This is likely a real product bug fwiw.

**Comment by jcouv** [comment]
Is one project with CODE_STYLE and the other without? I think that could explain the difference.

**Comment by alrz** [comment]
```diff
-        if (o is not string a)
+        if (!(o is string a))
```
Is it possible that langversion is not properly set in one of projects?

**Comment by CyrusNajmabadi** [comment]
The code stle layer doesn't have access to new Roslyn apis. So it will have different behavior. Just sign the issue to me and I can fix this up. Thanks!
