### ISSUE TITLE
CS0017 (multiple entry point) isn't always emitted

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46831]
The following code emits CS0017 correctly:

```csharp
    public class C
    {
        public static void Main() { }
        public static void Main(string[] args) { }
    }
```

However, the following code **doesn't** emit CS0017, which I believe should be emitted.

```csharp
    public class C
    {
        public static async Task Main() { }
        public static void Main(string[] args) { }
    }
```

**Comment by RikkiGibson** [comment]
Is this error elided for compat reasons? An `async Task Main() { }` could have been around from before the async Main feature was shipped, thus in old compilers it's not a candidate for the entry point but in new compilers it is.

If that is the case, this seems like a perfect candidate for a warning wave.

**Comment by Youssef1313** [comment]
> A `static async Task Main() { }` could have been around from before the async Main feature was shipped

@RikkiGibson, I think that's the case. The async main feature started in C# 7.1. So, there is no reason for this error to exist before C# 7.1.

I'm trying to playaround this in my PR. I may ask for help with the PR soon, specially that I'm not writing the code in Visual Studio as I can't open the solution on my poor machine.
