### ISSUE TITLE
Refactor: Resolve namespaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46833]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1147793/refactor-resolve-namespaces.html)._

---
[severity:I'm frustrated, but able to complete my work] [regression] [worked-in:16.7.0]
After updating to 16.7.0 I have noticed that trying a resolve namespaces will only provide the fully qualified names, and not attempt to import the using statement as it did previously. See screenshot. However, if I Ctl-Space it will import the namespace, which is the workaround I'm using at the moment. I've never used that before, so not sure if this is new or I just stumbled upon this as an alternative.

![image](https://user-images.githubusercontent.com/1408396/90278121-bb88a800-de1b-11ea-8cc4-715a549fc6bf.png)

---
#### Feedback Bot on 8/12/2020, 10:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/14/2020, 09:45 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this at all.  Would need a repro project showing this happening to be able to investigate.
