### ISSUE TITLE
Analyzer driver violates analyzer action semantics for Operation block actions in presence of cancellation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46859]
Analyzer action semantics are documented here: https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md
When a cancellation occurs in OperationBlockEndAction, analyzer driver seems to re-attempt to execute the nested operation actions for the same operation blocks. This violates the ordering semantics that all OperationAction callbacks for an operation block have to be invoked prior to OperationBlockEndAction. Additionally, duplicate callbacks for the same operation can also lead to analyzer state corruption. The best approach here seems to be that we discard the current compilation whenever a cancellation occurs during analyzer execution, but we need to confirm the performance characteristics of both build time and IDE analyzer execution with such a change.
This was identified https://github.com/dotnet/roslyn-analyzers/pull/3917#issuecomment-674477914

**Comment by mavasani** [comment]
As per discussion with @sharwell, this is by design:

>If an analyzer callback throws operation cancelled exception ,it is known to have cancelled its work without side effects. An action which throws OperationCancelledException after cancellation is requested is considered to have not been invoked, i.e. if work resumes for analyzing the same compilation, then another call needs to be made for this callback. Analyzers are responsible for ensuring cancelled callbacks do not have side effects. Once a side effect has been applied by the analyzer callback, the callback should ensure that the remainder of the operation is not cancelled, otherwise state corruption could occur.

**Comment by dotpaul** [comment]
Is this design documented somewhere for analyzer authors?

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md has the overall semantics, but it is missing information about cancellation that @sharwell cited above. Let me create a separate issue to update the docs.
