### ISSUE TITLE
Probably incorrect implementation for IsEntryPoint method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46869]
https://github.com/dotnet/roslyn/blob/e2ed258971baeb8dfb368724af1cbbf3f7932285/src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs#L698

```csharp
            private bool IsEntryPoint(IMethodSymbol methodSymbol)
                => (methodSymbol.Name == WellKnownMemberNames.EntryPointMethodName || methodSymbol.Name == "<Main>$") &&  // https://github.com/dotnet/roslyn/issues/45110 Switch to using WellKnownMemberNames.TopLevelStatementsEntryPointMethodName
                                                                                                                          // once src\CodeStyle\Core\Analyzers\Microsoft.CodeAnalysis.CodeStyle.csproj is able to use the latest version of the type.
                   methodSymbol.IsStatic &&
                   (methodSymbol.ReturnsVoid ||
                    methodSymbol.ReturnType.SpecialType == SpecialType.System_Int32 ||
                    methodSymbol.ReturnType.OriginalDefinition.Equals(_taskType) ||
                    methodSymbol.ReturnType.OriginalDefinition.Equals(_genericTaskType));
```

Cases that can fail this:

- if the method take an argument other than `string[]`
- if the method return a `Task<OtherTypeThanInt>`
- if the method returns a `Task` but isn't marked with async.
- if the method is async but language version is < 7.1 (the first version that supported async Main).

I also think that if the symbol name is `"<Main>$"`, we can return true directly without check the other cases.

**Comment by CyrusNajmabadi** [comment]
It's not really meant to be correct.  It's meant to be a cheap heuristic that prevents bad behavior from known important cases.
