### ISSUE TITLE
Extract base class lightbulb menu option when cursor is on a class or a member is highlighted to create a new base class

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#46875]
Steps to extract base class

1. Place cursor on the class name in the editor or highlight a member.

2. Press (Ctrl + .) or (Alt + Enter).

3. Select Extract Base Class.

4. The Extract base class dialog will open similar to the Pull members up dialog. But in this dialog you can specify a name for the base/parent class and where it should be placed – in a new file or in the same file as the original type. 

5. You can then choose the members to pull up and make/keep individual members abstract by selecting the checkbox in the Make Abstract column next to them.

**Comment by ryzngard** [comment]
Open Question:  Given the following code, where does each of the features allow you to invoke? 

```csharp
class MyClass : IMyClass
{
    private bool _myPrivateField;
    public string MyName { get; set; }
}
```

## Current Design

### Extract Interface 

* Inside `class MyClass : IMyClass`  via lightbulb
* Anywhere in the code via shortcut/toolbar (`ctrl+r, ctrl+i`) 

### Extract/Pull To Base Class

* Inside `class MyClass : IMyClass` via lightbulb
* Inside `public string MyName { get; set; }` 
* Inside `private bool _myPrivateField;`

### Pull Members Up

* Inside `public string MyName { get; set; }` 
* Inside `private bool _myPrivateField;`

**Comment by mikadumont** [comment]
I believe the design should be as follows: 

```
class MyClass
{
    private bool _myPrivateField;
    public string MyName { get; set; }
}
```

When caret is on a class name show the following options in the lightbulb menu: 

- Extract interface 
- Extract base class (we should rename the lightbulb menu option for `Pull members up to new base..` to `Extract base class`)

When caret is on a member and there isnt an interface or base class yet show the following options in the lightbulb menu: 

- Extract interface 
- Extract base class (we should rename the lightbulb menu option for `Pull members up to new base..` to `Extract base class`)

When caret is on a member and there is an interface or base class show the following options in the lightbulb menu: 

- Extract interface 
- Extract base class 
- Pull members up (we should have only one Pull members up option and one dialog for both base class and interface)
![image](https://user-images.githubusercontent.com/46729679/90826093-bda4a800-e2ee-11ea-912f-4c32b58211f0.png)

**Comment by CyrusNajmabadi** [comment]
> we should rename the lightbulb menu option for "Pull members up to new base..." to "Extract base class")

I personally disagree. But i'd be happy to discuss it more :)

**Comment by ryzngard** [comment]
> > we should rename the lightbulb menu option for "Pull members up to new base..." to "Extract base class")
> 
> I personally disagree. But i'd be happy to discuss it more :)

I think this is good because we can push for consistency in wording. 

Extract <something> = make a new thing.

* Extract Method => Make a new method in current context
* Extract Interface => Make a new interface based on members of the current class
* Extract Base Class => Make a new base class based on members of the current class 

Pull <something> = move to an existing thing
* Pull members to class => move members up the type hierarchy
* Pull members to interface => Move contract definition into interface (somewhat odd to say, but still fits I think)

**Comment by ryzngard** [comment]
Design Review Notes: 

"Extract Base Class" terminology makes sense. 

Refactorings should follow these rules: 

* Should be able to be invoked on type declaration
* Should be able to be invoked on member
* Should be able to be on blank line in type declaration but not inside member
* Should be able to highlight multiple members 

Menu options should be grouped together, and show below "Generate Overrides...". Have consistent order

**Comment by CyrusNajmabadi** [comment]
There's potentially *one* other place we might want to consider (but totally optional for hte future):

```
class D : $$B
{
}
```

here, we could offer `pull member(s) up to 'B'`.

**Comment by CyrusNajmabadi** [comment]
> Menu options should be grouped together, and show below "Generate Overrides...". Have consistent order

I'd say they should show below all items in the list related to updating *this* type.  so taht means showing below these two as well:

![image](https://user-images.githubusercontent.com/4564579/91097275-3d46b580-e614-11ea-89af-431ad54dc078.png)
