### ISSUE TITLE
"Reset ... Interactive from Project", "Execute in Interactive" and "Copy to Interactive" need to be wired up...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#4688]
Filing an issue so we don't lose details...

"Reset ... Interactive from Project" has been disabled with commit 45d46eca5863f09271c8c24f2c32322a31235764

We currently have an implementation of the other two commands in http://source.roslyn.io/#Microsoft.CodeAnalysis.InteractiveEditorFeatures/Extensibility/Interactive/InteractiveCommandHandler.cs,e6a8a331804f3ddb

However, there's no way to invoke the command when text is selected in a code file...

We need to:
- Add the commands to a VSCT file (https://github.com/dotnet/roslyn/blob/36136352eb98d3b9be02bcca044ff76a94c5c725/src/InteractiveWindow/VisualStudio/InteractiveWindow.vsct)
- Implement IOleCommandTarget.QueryStatus (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractOleCommandTarget.Query.cs,2153d9fb2692892a)
- Implement IOleCommandTarget.Exec (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractOleCommandTarget.Execute.cs,6414fb2e3c4bd78e)

**Comment by davkean** [comment]
Note that VS CSharpSendToInteractive is currently disabled due to this.

**Comment by ManishJayaswal** [comment]
@drognanar FYI

**Comment by ManishJayaswal** [comment]
@drognanar can this be closed now?
