### ISSUE TITLE
Analyzer reports unused constructor for MEF components.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#46887]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1149523/analyzer-reports-unused-constructor-for-mef-compon.html)._

---
Create a class with an `Export` attribute and a private constructor with an `ImportingConstructor` attribute on it.  This denotes a MEF component that will invoke the private ctor instead of the default (parameterless) one.  However, the VS code analyzer still "dims" the ctor and reports it as unused.

```csharp
    [Export(ExportContractNames.ProjectTreeProviders.PhysicalViewRootGraft, typeof(IProjectTreeProvider))]
    internal class GlobalDesignerProjectTreeProvider : ProjectTreeProviderBase
    {
        [ImportingConstructor]
        private GlobalDesignerProjectTreeProvider(
            IProjectThreadingService threadingService,
            UnconfiguredProject project)
            : base(threadingService, project, configuredProjectExportsRequired: true)
        {
        }
```

---
#### Mila Zhou [MSFT] on 8/13/2020, 11:06 PM: 

<p>Could you please tell me what type of project you are? Web or others? Some screenshots will be better.</p>

#### Feedback Bot on 8/17/2020, 02:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/17/2020, 09:33 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### kirk solved on 8/14/2020, 06:48 AM, 0 votes: 

<p>It probably happens in any C# scenario, but the one above is a C# class library project targeting .NET 4.7.</p>

**Comment by sharwell** [comment]
Are we sure the MEF case is handled? I would have expected `ImportingConstructorAttribute` to be included here:
https://github.com/dotnet/roslyn/blob/e69b451b362312c18602beadd5c8b9e93833140d/src/Analyzers/Core/Analyzers/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs#L92

**Comment by mavasani** [comment]
Ah probably I misremembered then... thanks

**Comment by sharwell** [comment]
I lean towards marking this By Design. The diagnostic will not be reported if the constructor is made public.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback here.
