### ISSUE TITLE
Don't show "Reset C# Interactive from Project" command for now...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#4689]
We're not targeting this scenario for Milestone 1.1, so we should disable the command for now (also, it doesn't work well in current builds...you cannot type after the reset...).

**Comment by colonelchlorine** [comment]
Is this ever coming back? Right now I can't figure out how to start using my project in C# Interactive.

**Comment by KevinH-MS** [comment]
Yes (and hopefully soon).  We're just trying to figure out what all commands and integration we want with the project first.

In the meantime, I know it's a bit of a hassle, but you can work around by:

1.  Building your project
2.  Copying the output binary path from the Output Window
3.  ```#r "...paste your path here..."```

**Comment by kdbanman** [comment]
Just registering interest in this issue.  Starting C# Interactive using my project in a convenient way would be nice.

**Comment by wadebee** [comment]
Adding my interest as well. C# interactive is 80% useless without the ability to iteratively modify and then test those changes within the context of the project you are working on.

**Comment by colonelchlorine** [comment]
Wadebee, if you follow Kevin's response it works nicely. Not the bee's knees, but still pretty great.

**Comment by KevinH-MS** [comment]
FYI, there *is* someone working on getting this included for the next update.  @drognanar, is there an open issue that folks can track for this (if not, I'll reopen this and assign to you).

**Comment by wadebee** [comment]
@colonelchlorine - In my use-case I am using C# Interactive to build new functionality within an existing project. Kevin's workaround requires the following for every iterative change: 
- Rebuild project
- Reset C#Interactive
- ClearScreen
- #r "[myWorkingDirectory/]MyProject.dlll" 
- using MyNamespace.MySubNamespace (1 or more)

At this point I am better off just stubbing out some pseudo unit tests and interacting with those. This is definitely not the bee's knees but I am glad to hear a rescue team is working it ;)
