### ISSUE TITLE
VB.NET class libraries requires consumers to contain references to all types that are publically exposed

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4690]
Description: If a VB.NET class library exposes types it has brought in through a reference that has been added to that project, 
any consumers of that class library are now required to add a reference to that assembly as well, regardless of whatever they consume that API or not. 

This is a regression from VS 2013. 

Repro Steps:I have a created a GitHub repro of the bug for your convenience at: https://github.com/SimonGustavsson/VS2015VBBug 
It's very simple indeed, the only modifications made to the standard template is: 
ClassLibrary1 
- Added references to System.Windows.Forms 
- Added two subs to Class1, one that takes a System.String as an argument, and one that takes a System.Windows.Forms.Form as an argument. 
ConsoleApplication1 
- Added project reference to ClassLibrary1 (type of references irrelevant) 
- Instantiated Class1 defined in ClassLibrary1 
- Called the overload of Class1.Test that takes a string. 

What follows is an error saying ConsoleApplication1 has to contain a reference to System.Windows.Forms. 
Note that ConsoleApplication is not using the overload that takes a System.Windows.Forms.Form, 
so it should *not* have to contain a reference to System.Windows.Forms. 

Impact:It is currently preventing us from migrating to VS 2015 as it breaks the build of essentially all of our projects.

Migrated from TFS/DevDiv 1204504

**Comment by gafter** [comment]
You are indeed referencing `Class1.Test(Form)`, by naming its method group and asking the compiler to perform overload resolution on it. VS2013 erroneously ignored some members during overload resolution if it could not resolve their types. Consequently VS2013 overload resolution behavior would change depending on the set of references available. We have fixed that bug in VS2015, and therefore require you to provide any references necessary for the compiler to perform overload resolution.

**Comment by gafter** [comment]
@SimonGustavsson This is your issue. Please review.

**Comment by SimonGustavsson** [comment]
Hey gafter
Thanks for looking into this for me.

Just for clarity, I'm fairly certain this "bug" (lets call it a feature!) has been present since at least VS 2010, probably even older than that, though I don't currently have the time to verify that.

This feature is specific to VB, and doesn't occur in C#. So in the spirit of getting the languages to an equal level, I do agree with the decision to fix it. Just figured I'd log the issue in case it was an oversight or something.

**Comment by gafter** [comment]
@SimonGustavsson You're welcome. This issue is probably in every version of the VB.net compiler before VS2015, when we rewrote the compiler from scratch.
