### ISSUE TITLE
Completion doesn't switch to suggestion mode in ImmutableArray.SingleOrDefault

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#46927]
**Version Used**: fa5e52a11698fd420cb9572d1f650687eddae5d4

![image](https://user-images.githubusercontent.com/201340/90556583-06712b00-e14e-11ea-99ed-3e1cea2456ee.png)

For some reason, if you call SingleOrDefault() it doesn't go into suggestion mode when you try typing a lambda, so you can't type the name of a lambda parameter.

**Comment by genlu** [comment]
@jasonmalinowski can't repro using 30508.10.main. Could you please confirm if it's fixed or not?

**Comment by jasonmalinowski** [comment]
@genlu: still reproduces for me on 30509.20.main. I used a .NET Core console application if that matters for some odd reason...

**Comment by genlu** [comment]
Hmm, this is what I see in 20509.20.main with a.netcore consoleapp...
![SuggestionMode](https://user-images.githubusercontent.com/788783/92783359-8e67e080-f35a-11ea-8fc5-00c2c878b2cd.gif)
