### ISSUE TITLE
Enhance analyzer action semantics doc for information about handling cancellation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#46933]
As per discussion with @sharwell, this is by design:

>If an analyzer callback throws operation cancelled exception ,it is known to have cancelled its work without side effects. An action which throws OperationCancelledException after cancellation is requested is considered to have not been invoked, i.e. if work resumes for analyzing the same compilation, then another call needs to be made for this callback. Analyzers are responsible for ensuring cancelled callbacks do not have side effects. Once a side effect has been applied by the analyzer callback, the callback should ensure that the remainder of the operation is not cancelled, otherwise state corruption could occur.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/46859#issuecomment-675594444_

**Comment by mavasani** [comment]
@dotpaul

**Comment by dotpaul** [comment]
Might also be nice to document behavior when an analyzer callback throws other exceptions as well.

**Comment by mavasani** [comment]
We decided that a better approach here is to change the IDE analyzer execution to not operate in presence of cancellation, instead use fresh CompilationWithAnalyzers instance. We already implemented this in https://github.com/dotnet/roslyn/pull/47150, so analyzer authors can ignore state corruption or duplicate callbacks in presence of cancellation for all practical purposes.
