### ISSUE TITLE
Add CodeStyleOption for space after attributes in parameter list

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#46932]
From developer community - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128059

> When I write code like:
>
> ```csharp
> public void Foo([In]int a)
> {
> }
> ```
> 
> And then format the code.
>
> I will get the following result in Visual Studio 16.6:
>
> ```csharp
> public void Foo([In] int a)
> {
> }
>```
>
> But in earlier version, I will get different result:
>
> ```csharp
> public void Foo([In]int a)
> {
> }
> ```
> 
> Earlier version doesn’t change the space between attribute and method parameter. But 16.6 does, which may cause codes change.
>
> I think this behavior should be same in different versions or i can control this behavior with an option.

This change in behavior was intentional and made in https://github.com/dotnet/roslyn/pull/42466.

The Proposal is to add a `csharp_space_after_attributes_in_parameter_list` CodeStyleOption to control formatting this space.

**Comment by CyrusNajmabadi** [comment]
Yeah, i believe we had a design meeting on this.  We explicitly and intentionally pushed for this to have the new format, and for thsi to be nonconfigurable.  Like many parts of roslyn formatting.  This is all-or-nothing as long as you use the formatter.

**Comment by ryzngard** [comment]
Design Review: This is a deviation from the intentional design and should be considered as part of the need for a formatting API  #31691
