### ISSUE TITLE
VSIX-installed suppressors do not load when project has Nuget-installed analyzers

### ISSUE THREAD

**Issue by kykwo** [dotnet/roslyn#46942]
**Version Used**: 16.7 / Roslyn 3.6

**Steps to Reproduce**:

1. Install an extension with analyzers and another with suppressors.
2. Open a project that has other analyzers (e.g. StyleCop) installed via Nuget. 

**Expected Behavior**: VSIX-installed suppressors should suppress issues for all projects.

**Actual Behavior**: VSIX-installed suppressors do not suppress. They do work when opening a project with no Nuget-installed analyzers. 

**Context** 
We have two extensions: 1) one that has analyzers, and 2) one that has suppressors that suppress diagnostics from the first extension. We are finding that suppressors do not load when opening a project that has Nuget-installed analyzers, but otherwise work fine. 

@sharwell said this might be an oversight from adhering to a separate, expected functionality: VSIX-installed suppressors cannot suppress diagnostics reported by a NuGet-installed analyzer. 

From what I understand there is no existing test case covering the scenario described in this issue. What is the current state of VSIX-installed suppressors? Is this an area that might be covered in the future?

**Comment by sharwell** [comment]
VSIX-installed suppressors should be able to suppress diagnostics reported by VSIX-installed analyzers. It's important that they _not_ be able to suppress diagnostics reported by the compiler or by NuGet-installed analyzers.

**Comment by kykwo** [comment]
I found code in the Roslyn repo that could possibly be the root cause. 

The method `ShouldIncludeHostAnalyzer()` in `SkippedHostAnalyzersInfo.cs` determines whether the host (VSIX) analyzer should be included. It does this by going through the analyzer's supported diagnostics, seeing if there's at least one that's not reported by project (Nuget) analyzers. However `DiagnosticSuppressor` is a special type of `DiagnosticAnalyzer` and do not have any supported diagnostics. Since `var descriptors = analyzerInfoCache.GetDiagnosticDescriptors(hostAnalyzer);` returns an empty collection we never go in the foreach loop where `shouldInclude` is set to true.

The reason VSIX suppressors work when there's no project/Nuget analyzers is because of line 73 in `SkippedHostAnalyzersInfo.cs` (`if (projectAnalyzerIds.Count == 0) { return Empty; }`), which is before `ShouldIncludeHostAnalyzer()` gets called. So if there are no project/Nuget analyzers installed, we include all VSIX analyzers.

Please correct me if I misunderstood the logic.

**Comment by nschuessler** [comment]
Have an [active PR](https://github.com/dotnet/roslyn/pull/47486) for this issue.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/47486
