### ISSUE TITLE
NullReferenceException in NullableWalker.VisitConditionalOperatorCore

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/roslyn#46954]
**Version Used**:
Visual Studio 16.8.0 Preview 1
Targeting .NET 5.0.100-preview.7.20366.6

**Steps to Reproduce**:

1. Clone and open solution found [here](https://github.com/JakenVeina/Battleship.NET/tree/dotnet-roslyn-issue-46954).
2. Open file "Battleship.NET.Avalonia\Gamespace\Running\RunningGamespaceBoardTileViewModel.cs"
3. Select and copy code segment from Line 42 Character 44 to Line 57 Character 90. [Screenshot](https://media.discordapp.net/attachments/401165307475132416/745503014672138314/unknown.png)
4. Paste code segment at Line 33 Character 57. [Screenshot](https://media.discordapp.net/attachments/401165307475132416/745503088382574663/unknown.png)
5. Observe VS crash

**Expected Behavior**:
VS does not crash while attempting to copy and paste code.

**Actual Behavior**:
VS crashes due to a `NullReferenceException` from `Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitConditionalOperatorCore`

[Full stack trace](https://paste.mod.gg/yovubopuca.sql) (actually, not full, Windows Event Viewer doesn't capture the whole thing).

**Comment by jcouv** [comment]
Notes from investigation (will update):
- I'm able to repro even with latest compiler bits. Using a debug version (`.\Build.cmd -Configuration Debug -deployExtensions -launch` to deploy debug compiler) is convenient as it pops up the assertion prompt (offering to attach a debugger).
- We're getting into `VisitConditionalOperatorCore` with `node.Type` being null. This means we hit the assertion in debug mode, and crash/NRE in release mode.

**Comment by jcouv** [comment]
@gafter I've added a simple test above which allows unconverted conditional nodes to reach NullableWalker when determining the return type (with nullability) of an unbound lambda. 
Maybe we can chat that week to confirm if it's the right approach to fix this, but I'm thinking we'll just need to handle such nodes in NullableWalker (adding logic to `VisitConversion` in particular).
