### ISSUE TITLE
Making "readonly" keyword available also in functions not only Constructor

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/roslyn#46951]
## Background and Motivation

The Idea is to enable the safety and explicit expression this keyword already gives to types beyond constructor initialization. 
As known, alot of Frameworks have a _not-constructor-based-Initialization_ API which will doesnt allow the benefit of a readonly field to be declared in such functions, for example in Unity3D:

I would like to be able to say:

## Usage Examples

```
readonly int initialSpeed;

void Awake/Start()
{
     initialSpeed = ComputeSpeed(param1, param2 ...);   ------------------> doesnt work!
   //All init code here.. 
}

public <CLASSNAME>()
{
    initialSpeed = ComputeSpeed(param1, param2 ...);   ------------------> Works ofc!
}
```

But you cant use constructors in unity3D for init code so it would be really awesome to allow the use of readonly anywhere FOR 1 TIME, so the moment the compiler recognizes an init to a readonly field, every other attempt from the developer to reinit this field somewhere else should be denied.

I would love to hear from you guys about this 👍 

Best regards

**Comment by CyrusNajmabadi** [comment]
Language discussion happens at dotnet/csharplang.  Thanks!
