### ISSUE TITLE
Analysis results are forever out of date

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#46952]
**Version Used**: 

Version 16.8.0 Preview 3.0 [30418.142.main]

![image](https://user-images.githubusercontent.com/1103906/90590652-72be5e00-e224-11ea-8af0-4479c24163ae.png)

**Steps to Reproduce**:

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 5f7ca174b`
4. `ProjectSystem.sln`
5.  Right-click on Solution and choose Analysis -> Run Code Analysis on Solution 
-- Get 48 messsages --
6. Double-click on the first message

Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0084	Use 'IsNot' expression	Microsoft.VisualStudio.AppDesigner	C:\project-system\src\Microsoft.VisualStudio.AppDesigner\PropPageDesigner\PropPageDesignerView.vb	1248	Active

7.  CTRL+. and choose the following:

![image](https://user-images.githubusercontent.com/1103906/90590717-9c778500-e224-11ea-9fd7-942aff47466b.png)

8. Wait for titlebar of _Error List..._ to turn into just _Error List_

**Expected Behavior**:
No "Use 'IsNot' expression" messages

**Actual Behavior**:
All the "Use 'IsNot' expression' messages stick around until you double-click to navigate to one and then it disappears.

**Comment by CyrusNajmabadi** [comment]
Closing as these components were entirely rewritten for LSP.
