### ISSUE TITLE
Issue with `!_CSharpKeyword`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#46988]
Both the not operator and null-forgiving operator have the same F1 help keyword. That causes the dotnet/docs repository to have the exact same f1 keyword in two articles. And unfortunately, pressing F1 in any `!` always redirects to the null-forgiving article. I think Roslyn should provide different f1 keywords so dotnet/docs can be updated to have different f1 keywords too.

cc: @BillWagner @gewarren

**Comment by Youssef1313** [comment]
My suggestion to fix this would be:

- Keep `!_CSharpKeyword` as is for the "logical not" operator.
- Change the null-forgiving from `!_CSharpKeyword` to `Null-Forgiving_CSharpKeyword` (or something similar).

@davidwengier What do you think?

**Comment by davidwengier** [comment]
Your proposal makes sense to me :+1:

Out of an abundance of caution I'd probably just use `nullForgiving_CSharpKeyword` since the service seems to have issues with the minus sign in other cases, and ultimately the actual F1 keywords are implementation details anyway.

**Comment by Youssef1313** [comment]
@davidwengier I'll work on it and avoid the minus sign, but actually, the problem seems to be something other than that.

- https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(await_CSharpKeyword);k(DevLang-csharp)&rd=true (Works)
- https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(-_CSharpKeyword);k(DevLang-csharp)&rd=true (Started working suddenly after it had been not working for a very long time)
- https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(+_CSharpKeyword);k(DevLang-csharp)&rd=true (Stopped working, although there is an article with this f1 in dotnet/docs)
