### ISSUE TITLE
[Feedback] Cannot reference libraries be in folders containing the minus symbol ( - ). Worked in VS2013

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4698]
Apparently referenced libs cannot be in folders containing the minus symbol ( - ), in VS2013 and below this was OK.

Migrated from TFS/DevDiv 1210397

**Comment by jaredpar** [comment]
I was unable to reproduce this bug.  I was able to reference DLLs in a folder that had dashes in it with the current and RTM bits.
