### ISSUE TITLE
Automatic 'async' Addition

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#46993]
Let's say I have this method:
```
public Task DoWork(){

}
```

When I go into the body of the method and type:
```
await DoOtherWork();
```

It should automatically change my method signature to be:
```
public async Task DoWork() 
```

**Comment by CyrusNajmabadi** [comment]
Note: i think the request here is just that if the user types 'await' that we automatically make the method async.  It's an interesting idea, but i'm hesitant about those sorts of aggressive changes happening (esp. when the method signature might not be in sight).  I think the ability to use the lightbulk is def a 'good enough' solution to this problem space.
