### ISSUE TITLE
Bring Back Function View like the old VB6 used to have, that is a valuable feature.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47005]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1145235/bring-back-function-view-like-the-old-vb6-used-to.html)._

---
Bring Back Function View like the old VB6 used to have, that is a valuable feature.

---
#### Feedback Bot on 8/11/2020, 03:37 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Feedback Bot on 8/12/2020, 01:14 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by Cosifne** [comment]
Design meeting conclusion:
1. We will not bring the old behavior back. VB.Net is not VB 6.
2. We have the intension to have a different 'focus mode' for PM to design. This mode will bring the benefits of the old feature in a more modern way.

**Comment by CyrusNajmabadi** [comment]
3. we may also consider a "collapse all but this method" option to outlining.
