### ISSUE TITLE
a wizard to convert C# code to nullable reference types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1142448/a-wizard-to-convert-c-code-to-nullable-reference-t.html)._

---
<p>When I start the wizard, I can choose its scope: method, class, file, project, solution.</p><p>The wizard:</p><ol>
<li>automatically makes all changes deemed acceptable according to my prefs for the wizard</li><li>leads me through the rest of the cases;
for each case, the wizard gives me one or more suggested refactorings. I can pick one, modify it, and commit it. I can also follow doc links relevant to the case.</li></ol><ul>
<li>The wizard inserts/removes/modifies #nullable directives as necessary along the way.</li><li>When the wizard is done, there are no #nullable directives in the code.</li><li>At any point, I can stop the wizard, and none of the resulting code changes will be causing errors or warnings.</li><li>I can start the wizard again if it was stopped.
Each inserted or modified #nullable directive is indented by a settable amount; 80 columns for me, so they don't clutter the code.</li></ul><p>Also reported as a <a href="https://youtrack.jetbrains.com/issue/RSRP-480592" target=_blank>Resharper issue</a>.</p>

---
#### Feedback Bot on 8/10/2020, 00:53 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by daveyostcom** [comment]
I am the original poster.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and extremely large cost to implement such a feature.
