### ISSUE TITLE
Tooltip Comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1151529/tooltip-comments.html)._

---
It would be awesome if I could create a custom tooltip for selections of code that would mirror comment functionality. For example, instead of a HUGE comment section consuming the bulk of a section of code (either several // lines or a /* */ block, for example), it would be cool if I could just highlight my function's name, right-click, and select "Comment" and the comments are easily accessible but not a burden to the code. Maybe even create a "Comment" section in the "Properties" pane or something. Anything but what it is now. I think we can evolve a little here...

---
#### Feedback Bot on 8/17/2020, 01:22 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This request reminds me of https://medium.com/feenk/code-comments-as-live-wikis-in-ides-1c7b593749f5.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and general large scope/complexity of request.
