### ISSUE TITLE
Convert to interpolated string \  Fix all occurrences in: Document | Project | Solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47004]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1144799/convert-to-interpolated-string-fix-all-occurrences.html)._

---
<p>In <strong>.NET</strong> when press <strong>(Ctrl + .)</strong> on something like: </p><pre>&quot;xx-&quot; + this. Name</pre><p>Please add <strong>Fix all occurrences in: Document | Project | Solution, because this affects code readability and runtime performance.</strong></p>

---
#### Feedback Bot on 8/12/2020, 01:14 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by ryzngard** [comment]
Design Review: This fits nicely with a fix all for refactorings need. #32461
