### ISSUE TITLE
Inline parameter hints should show for type parameters

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#47014]
Sometimes in Roslyn we have a bunch of code with a bunch of type parameters, like:

https://github.com/dotnet/roslyn/blob/13873cc646d9499f25e72c7aa1b0a9c668a0d013/src/Workspaces/CSharp/Portable/SemanticModelReuse/CSharpSemanticModelReuseLanguageService.cs#L22-L27

In these cases, it'd be nice if the type parameter names were displayed.

**Comment by jasonmalinowski** [comment]
Moving this to 16.9 as we'll have to figure out some design thoughts for this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
