### ISSUE TITLE
Typing should be allowed before the inline parameter hint

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#47016]
Version 16.8.0 Preview 3.0 [30420.52.main]

See the following gif -
![parameterhints](https://user-images.githubusercontent.com/5749229/90831516-c4381d00-e2f8-11ea-8e37-0eb4e1f56bdc.gif)

Here I wanted to add a parameter before the existing parameter.  Ideally, I wanted to put my cursor and type in between the ( and the inline hint instead of typing after the hint and having the typed characters move back to the other side of the hint.

**Comment by CyrusNajmabadi** [comment]
Seeing if @olegtk wants to take this.  This seems to be a general issue with inline-text-marker-tags.  It does feel like it would be nice if hte editor allowed for the concept of teh caret moving to either side of it.  But it's not something roslyn can itself control.
