### ISSUE TITLE
source generators conflict with razor files

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/roslyn#47027]
**Version Used**: 

dotnet: 5.0.100-preview.7.20366.6

**Steps to Reproduce**:

1. Create a source generator that unconditionally generates some code, e.g. the attribute in the `AutoNotify` example
2. Create a consuming project of type Microsoft.NET.Sdk.Razor (class library for blazor)
3. Add at least one `.razor` component to the consuming project
4. Observe that generated source code is not available
5. Remove all `.razor` files
6. Observe that the generated source code is available now

Note that the contents of the razor file do not matter at all.

**Expected Behavior**:

The SG should produce code regardless of the presence of .razor files or not

**Actual Behavior**:

When at least one .razor file is present, the SG doesn't seem to run.

A repo that shows this bug is available here: https://github.com/stefanloerwald/experiment-api-group-generator:
- Project ApiGroupGenerator includes the SG
- Project Tests_ApiGroupGenerator includes unit tests for the SG (demonstrating among other things that the SG does run as expected)
- Project IntegrationTest should compile without error, but since a .razor file is present, it doesn't. Remove the razor file to see that it works without it.

**Comment by stefanloerwald** [comment]
The example repo was moved. The state of the project mentioned in the bug report can be found here: https://github.com/excubo-ag/Generators.Grouping/commit/9c5ed28d83ab7a05c0e7169b4b70a34dbc945e48 .

**Comment by chsienki** [comment]
I beleive this is the same problem as https://github.com/dotnet/roslyn/issues/44210 / https://github.com/dotnet/aspnetcore/issues/24526

**Comment by jaredpar** [comment]
Closing as a dupe (almost certaintly the same issue)
