### ISSUE TITLE
Inline variable declaration produces invalid code when part of a collection initializer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47041]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1154910/code-cleanup-remove-unnecessary-cast-works-incorre.html)._

---
[severity:I'm frustrated, but able to complete my work]
See git diff on "Capture.png" after code cleanup run. 

bla bla bla bla bla bla to achieve 100 characters long

---
#### Feedback Bot on 8/19/2020, 09:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
This is actually caused by the Inline Variable Declaration refactoring when used in a collection initializer:
![image](https://user-images.githubusercontent.com/754264/93724232-94768080-fbe8-11ea-8648-1b3194b8af86.png)
