### ISSUE TITLE
RenameDocument does not fire IVSRefactorNotify or dismiss rename tracking

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#47048]
The new RenameDocumentAsync API regresses behavior by not handling IVSRefactorNotify or dismissing rename tracking. 

These actions should happen on `Workspace.TryApplyChanges` from the solution produced by the API

**Comment by ryzngard** [comment]
Rename tracking dismiss will be tracked as #44469 and fixed separately. Using this issue only for IVSRefactorNotify

**Comment by CyrusNajmabadi** [comment]
> The new RenameDocumentAsync API regresses behavior by not handling IVSRefactorNotify or dismissing rename tracking.

FWIW, i'm 100% ok with this.  IVsRefactorNotify is an awful API taht i would like us to get off of.  For our new async rename entrypoints, i don't think we should use it.  And features that need this information need to modernize to something better.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  No movement on this in 4 years means we don't need this.
