### ISSUE TITLE
No intellisense for record types if they're declared at the end of a top level program

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47042]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1155735/no-intellisense-for-record-types-if-theyre-declare.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
The following code block compiles:

```
using System;

var p = new Person("Filip", 33);

record Person(string Name, int Age);
```

However if I write `new Pers....` above the record declaration there is no intellisense.

If I move the record declaration to the top I get intellisense but the top level statement no longer compiles.

---
#### Feedback Bot on 8/20/2020, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jcouv** [comment]
Let's confirm whether this is an IDE or compiler (parsing) issue.

**Comment by YairHalberstadt** [comment]
I cannot reproduce in VS 16.8 preview 2, or sharplab

**Comment by sharwell** [comment]
I've observed similar cases in the past where declarations after the caret sometimes get included in completion and sometimes do not. It's particularly common for fields of a class when the project has a code style that places fields at the end of type declarations. The long-term fix is ensuring IntelliSense retains information from the most recent (syntactically) valid compilation unit if it fails to produce a sensible incremental syntax tree. It's possible this representation suggests more members than are actually present, but at least it doesn't randomly drop them.

**Comment by Youssef1313** [comment]
I think this is a parsing issue

https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzguATEBqAPjAUwHcACAJQFgAoagJwIGMB7WjcgClgRIEkBKANxA===

There is no RecordDeclarationSyntax in the tree here.

**Comment by CyrusNajmabadi** [comment]
Yes.  This is a pretty unpleasant parsing scenario.  One thing that's weird is that 'new' is getting parsed out here as if it was a modifier of some top level member.  However, no top level members can be 'new' afaict.  So we should use `new` as a strong signal that this is a top level object creation instead.

**Comment by Rekkonnect** [comment]
Now `new` is parsed within an object creation expression, however the problem persists. `record ...` is being treated as part of the argument list of the constructor, with lots of missing tokens and errors. `record` should be a hard indicator that a type declaration begins after a missing opening paren.

**Comment by CyrusNajmabadi** [comment]
CLosing out due to lack of feedback.  This is a rare enough scenario that we can just live with this.
