### ISSUE TITLE
Split CS8509 into unhandled named and unnamed enum values

### ISSUE THREAD

**Issue by dextercd** [dotnet/roslyn#47066]
**Brief description:**

CS8509 is a warning you get when a switch expression doesn't have a pattern for certain enum values. You get the same warning when the enum value is named as when the value is unnamed (via a cast like `(EnumType)9`). 

This means that even when every named enum value has been handled you still get a warning. This encourages programmers to add a pattern that handles every case (often times this case simply throws an exception i.e. `_ => throw new ..`).

But that means that when you add a new named value to your enum you won't get a warning since it has already been handled (incorrectly) by the catch-all pattern.

My suggestion:

If instead you get a different warning depending on whether or not the unhandled enum value is named or unnamed, people could decide for themselves how they would like to approach this issue by enabling/disabling the appropriate warning.

**Languages applicable:**

C#, I'm not sure if VB has switch expressions.

**Code example that the analyzer should report:**

With this enum:

```cs
public enum Operation
{
    Plus,
    Minus,
    Multiply,
}
```

this code:

```cs
public static string OperationToString(Operation op)
{
    return op switch
    {
        Operation.Plus => "+",
        Operation.Minus => "-",
        // Note!: Operation.Multiply has not been handled by accident
    };
}
```

and this code:

```cs
public static string OperationToString(Operation op)
{
    return op switch
    {
        Operation.Plus => "+",
        Operation.Minus => "-",
        Operation.Multiply => "*",
        // Note!: Every named enum value has been handled
    };
}
```

should be reported with different warnings.

**Additional information:**

I expect neither warning to trigger when you add a catch-all pattern. This means that when you intend for your switch expression to handle every named value you would generally not add a catch-all pattern so that you get an alert on those switch expressions when you add a new named enum value.

I think the [Flags] attribute should cause *unnamed* enum values that can be created by using `bitwise or` on *named* enum values should also be considered named for the purposes of these warning.

**Comment by vixark** [comment]
I think the current implementation of this doesn't work well.

If you supress CS8524 in .editorconfig (the warning that promts you to add the discard pattern) you end up supressing it for all switches, including the ones that doesn't have enums. Having this rule avaliable for those cases (not enums) is as important as CS8509 for enums switches. A better approach would be to separate CS8524 in two different warnings: one for enums and other for not enums, or simply don't apply ever CS8524 to enums and leave only CS8509 for them.

**Comment by dextercd** [comment]
@vixark I think there's a better chance of getting this addressed if you open a new issue.

**Comment by jbrantlyatolo** [comment]
@vixark Could you provide an example of a non-enum switch where CS8524 is warned? I briefly tried coming up with one and was unable to.

**Comment by vixark** [comment]
> @vixark Could you provide an example of a non-enum switch where CS8524 is warned? I briefly tried coming up with one and was unable to.

Apparently they fixed it.

Now if I supress CS8524 in .editorconfig it doesn't show up in code like this:

```
                    var age = 45;
                    var ageGroup = age switch {
                        18 => "Young",
                        45 => "Average",
                        80 => "Old", 
                    };
```

Only CS8509 shows up that is the same warning that shows up when you have a switch with enum values and you are missing one of the values.

This change begs the question. What is the use of CS8524 with this new behaviour of CS8509. Is it only for the cases where the underlaying value (int) could be different  than the values in the enum?  Seems like more trouble and complication that what it actually solves. It seems like it isn't needed at all since CS8509 works fine for enums and other types.

**Comment by gafter** [comment]
> This change begs the question, what is the use of CS8524 with this new behavior of CS8509?

The two warnings, together, let you know if your switch expression might, possibly, not handle some input.

CS8509 alone lets you know if your switch expression might, possibly, not handle some input where enum values only take on declared values.

If you're only interested in the latter and not the former, you should suppress CS8524.  However, if you use [flag enums](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-5.0) you are probably interested in the former.

**Comment by vixark** [comment]
> > This change begs the question, what is the use of CS8524 with this new behavior of CS8509?
> 
> ... if you use [flag enums](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-5.0) you are probably interested in the former.

Thank you for your reply Neal! It makes sense now.

**Comment by SymboLinker** [comment]
Very nice to have found this issue. I've added the following rules to my `.editorconfig`:

```
dotnet_diagnostic.CS8509.severity=error
dotnet_diagnostic.CS8524.severity=none
```
and love the result.
