### ISSUE TITLE
Allow records with empty or no parameter list to give base type arguments

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#47091]
From LDM 8/24/2020 (https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-08-24.md#base-calls-on-parameterless-records):

A. `record Derived : Base(0) { }`
B. `record Derived() : Base(0) { }`
Decision: yes to both

**Comment by AlekseyTs** [comment]
https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-08-24.md#base-calls-on-parameterless-records

**Comment by AlekseyTs** [comment]
On the internal e-mail thread we decided to drop support for ```record Derived : Base(0) { }```. Record declarations without parameter list, but with base arguments will not be supported in C# 9.
