### ISSUE TITLE
Master build is broken locally due to missing CombinatorialRangeAttribute

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#47101]
**Version Used**: f6edf2868c49ec9d3d494c26cd6ad9f710355d2a

**Steps to Reproduce**:

1. `git clean -xdf` and kill all dotnet.exe/VBCSCompiler.exe tasks
2. `git fetch upstream master && git checkout --track upstream/master`
3. `.\Build.cmd -restore`

**Expected Behavior**: Builds successfully

**Actual Behavior**: 

```console
C:\Users\rikki\src\roslyn\src\VisualStudio\Core\Test\ProjectSystemShim\VisualStudioProjectTests\MetadataToProjectRefere
nceConversionTests.vb(117,77): error BC30002: Type 'CombinatorialRange' is not defined. [C:\Users\rikki\src\roslyn\src\
VisualStudio\Core\Test\Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj]
C:\Users\rikki\src\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs(295,103): er
ror CS0246: The type or namespace name 'CombinatorialRangeAttribute' could not be found (are you missing a using direct
ive or an assembly reference?) [C:\Users\rikki\src\roslyn\src\VisualStudio\CSharp\Test\Microsoft.VisualStudio.LanguageS
ervices.CSharp.UnitTests.csproj]
C:\Users\rikki\src\roslyn\src\VisualStudio\CSharp\Test\PersistentStorage\AbstractPersistentStorageTests.cs(295,103): er
ror CS0246: The type or namespace name 'CombinatorialRange' could not be found (are you missing a using directive or an
 assembly reference?) [C:\Users\rikki\src\roslyn\src\VisualStudio\CSharp\Test\Microsoft.VisualStudio.LanguageServices.C
Sharp.UnitTests.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:01:26.95
Build failed.
```

**Comment by sharwell** [comment]
This attribute is included here:
https://github.com/dotnet/roslyn/blob/72d7d0af9fc04f107d17a041d360e9b90c2fc98a/src/Test/Utilities/Portable/Roslyn.Test.Utilities.csproj#L83

and imported here:
https://github.com/dotnet/roslyn/blob/f6edf2868c49ec9d3d494c26cd6ad9f710355d2a/src/VisualStudio/Core/Test/Microsoft.VisualStudio.LanguageServices.UnitTests.vbproj#L75

**Comment by RikkiGibson** [comment]
I'll see if clearing my nuget cache resolves the problem

**Comment by RikkiGibson** [comment]
Thanks @sharwell, seems my NuGet cache was bad, just deleting the xunit.combinatorial folder resolved the problem
