### ISSUE TITLE
Incorrect "Remove unused parameter" for record

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#47142]
**Version Used**: 
VS16.8 preview 2

**Steps to Reproduce**:

```C#
    record A(int X);

    record B(int X, int Y /* Unexpected IDE0060 */) : A(X);

    class C
    {
        void Func(B b)
        {
            Use(b.Y);
        }

        private void Use(int i)
        {
        }
    }

```

**Expected Behavior**:
Should not suggest removing `int Y` near the comment

**Actual Behavior**:

**Comment by RikkiGibson** [comment]
Is this a bug in data flow analysis? We implicitly assign the parameter `Y` to the backing field for the property `Y`. Maybe we never have a bound tree for it and thus nothing to analyze.

It feels like the investigation should begin in the IDE analyzer so assigning to IDE team.

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi
