### ISSUE TITLE
Add documentation explaining warning suppression precendence

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#47154]
In https://github.com/dotnet/roslyn/pull/45871 we introduced another level of warning suppression via global analyzer configs; we now have five levels of suppression:

1. Warning level
2. Syntax tree level
3. Compilation level
4. Global analyzer level
5. Global warning level

We should write a document in this repo (perhaps in https://github.com/dotnet/roslyn/tree/master/docs/analyzers), or on docs.microsoft.com that explains how the precedence is interpreted and how they interact with each other.

**Comment by Youssef1313** [comment]
@gewarren, You may want to consider this for the new fundamentals section.

**Comment by mavasani** [comment]
This has been done now: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#precedence
