### ISSUE TITLE
Debugger doesn't recognize usings in current context

### ISSUE THREAD

**Issue by FUR10N** [dotnet/roslyn#4715]
This happens intermittently and has been since VS2013 (~90% repro rate).

When I'm at a breakpoint, none of the usings in the current context are recognized by the debugger. I can't hover over static fields or use watches/immediate window. I have to fully qualify everything.

Sometimes it does work, but I have no idea what causes it to fail. I've tried a new computer and fresh installs of visual studio.

http://stackoverflow.com/questions/31569493/visual-studio-debugger-doesnt-recognize-any-usings

**Comment by ManishJayaswal** [comment]
@FUR10N I am not able to repro this in VS2015. Can you share a small repro ( even if it only repros 90% of the time) with us?

**Comment by FUR10N** [comment]
@ManishJayaswal I think I've finally been able to narrow down the cause! A lot of our projects use [Fody](https://github.com/Fody/Fody) (the IL weaver).

The addition of the targets import seems to be the cause:
`<Import Project="..\..\packages\Fody.1.29.3\build\dotnet\Fody.targets" Condition="Exists('..\..\packages\Fody.1.29.3\build\dotnet\Fody.targets')" />
  `

If I remove that, then the debugger gets access to the usings correctly (100% repro).

To fully reproduce:
1. Make a new project (I used a Universal Windows 8.1 Blank App)
2. Add the Fody package through Nuget.
3. Add any Fody weaver (I used BasicFodyAddin.Fody)

I'm guessing the post build step from Fody is what breaks debugging here. I don't know if it is a bug in Visual Studio or just some less-than-supported interaction from Fody due to DLL re-writing.

**Comment by ManishJayaswal** [comment]
@FUR10N thanks! We will try to repro and investigate.

**Comment by ManishJayaswal** [comment]
@FUR10N debugging or rewritten IL is not officially supported but we will try to investigate. Have you reported this issue to Fody?

**Comment by FUR10N** [comment]
Sorry, forgot to look earlier since I only just found the connection to Fody. They have an existing ticket tracking the issue https://github.com/Fody/Fody/issues/130.

I'm now thinking it's just an issue with Fody or Cecil (but I don't really know enough about it to say for sure). I also don't know why it should effect assemblies I'm not re-writing (like the one that contains `Environment.TickCount`; anyway we can just close this ticket unless you guys want to investigate that interaction more.

Thanks for the response @ManishJayaswal
