### ISSUE TITLE
IDE0041 shows inaccurate title

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47163]
![image](https://user-images.githubusercontent.com/31348972/91355015-da107b00-e7ed-11ea-8a3f-53189f1b86e0.png)

The title says: "Use 'is null' check". It neither uses the new C# 9 "is not null", or "is null"

**Comment by CyrusNajmabadi** [comment]
Does the right hting now:

![image](https://user-images.githubusercontent.com/4564579/153943962-fe041649-0953-49dc-b3ba-67c9a7cf83e5.png)
