### ISSUE TITLE
Severity applied via bulk configuration should be reflected in analyzer icon and properties in Visual Studio UI

### ISSUE THREAD

**Issue by bordecal** [dotnet/roslyn#47160]
**Version Used**: 
Visual Studio 16.7.2

**Steps to Reproduce**:

1. Create a solution with an `.editorconfig` file and a project configured to use at least one Roslyn analyzer package that contains bulk configurable rule(s).
2. Add a bulk configuration for error severity to `.editorconfig` that should change the effective severity of at least one rule (e.g.: `dotnet_analyzer_diagnostic.severity = error` or `dotnet_analyzer_diagnostic.category-<some category>.severity = error`).
3.  Save the `.editorconfig` file.
4.  Examine a rule (e.g.: CA1820) whose severity should have been adjusted under the `Dependencies\Analyzers` node of the project in the Visual Studio solution explorer.

**Expected Behavior**:
The rule icon should reflect the severity applied via bulk configuration, as should the "Effective severity" item in the diagnostic properties sheet, as it is when a rule is configured using a rule-specific `.editorconfig` entry (e.g.: `dotnet_diagnostic.CA1820.severity = error`).

![image](https://user-images.githubusercontent.com/6350017/91342868-a7dd2a00-e7a9-11ea-8e5c-c95659f02b43.png)

**Actual Behavior**:
Neither the rule icon nor the effective severity property display change to reflect the severity applied via bulk configuration.

![image](https://user-images.githubusercontent.com/6350017/91342954-cc390680-e7a9-11ea-9e75-9c85c80d4dc6.png)

**Additional Notes**:
This issue seems to hint that the logic used to determine effective severity is not fully shared between the execution engine and the UI.  While the current UI behaviour is inconvenient, any mismatches between applied and displayed severity will potentially become much more problematic when/if the `.editorconfig` editor UI (#40365) becomes available.  If the current discrepancy is indeed the result of a lack of centralized logic for determining effective severity, might it make sense to invest in centralizing the logic that so users can feel confident in the information provided to them by the eventual editor?

**Comment by mavasani** [comment]
@bordecal Nice points, thanks. I will work on fixing this inconsistency.

**Comment by bordecal** [comment]
@mavasani  Thank you!
