### ISSUE TITLE
Only base positional Record parameters shown as used

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#47174]
**Version Used**: visual studio 16.8 preview 2

**Steps to Reproduce**:

```csharp
    public record Base(int I) { }
    public record Derived(string S) : Base(42) { }
```

**Expected Behavior**:
both `I` and `S` are shown as used.

**Actual Behavior**:
IDE0060:
Remove unused parameter 'S' if it is not part of a shipped public API

**Comment by jcouv** [comment]
Closing as duplicate of https://github.com/dotnet/roslyn/issues/47142

**Comment by jcouv** [comment]
Ah, my bad. Different issue (misread IDE1006 and IDE0060). Re-opened.
