### ISSUE TITLE
Wrong property value obtained by member access operator in C# in .NET Core

### ISSUE THREAD

**Issue by Alvin-Seville** [dotnet/roslyn#47181]
**Version Used**: .NET Core 3.1

**Steps to Reproduce**:
Here the code which is executed with .NET Core 3.1:
```C#
using System;

public unsafe class MainClass
{
  public struct Node
  {
    public int Value { get; internal set; }
    public Node* Next { get; internal set; }

    public Node(int value, Node* next)
    {
      Value = value;
      Next = next;
    }

    public override string ToString()
    {
      return Value.ToString();
    }
  }

  public static Node* Create(int value, Node* next)
  {
    Node node = new Node(value, next);
    return &node;
  }

  public static void Main (string[] args)
  {
    Node* node = Create(1, null);
    Console.WriteLine(node->Value);
  }
}
```

**Expected Behavior**:
1 in output.

**Actual Behavior**:
Output is some random number.

![image](https://user-images.githubusercontent.com/42812113/91408743-f6221580-e809-11ea-85f6-2d6d18a8b697.png)

I've checked it out in [Repl.it](https://repl.it/@AlvinSeville19/NET-Example-Unmanaged-Stack) (with Mono) and got expected output - 1 that is different from .NET Core one.

What's going on? I'm learning using unmanaged code in C# and it is confusing.

**Comment by CyrusNajmabadi** [comment]
You make a node on the stack, and then return a pointer to it.  Your stack goes away when `Create` returns, leaving the pointer pointing at... well... somewhere.  This is undefined behavior and you cannot expect any particular result to be returned.

**Comment by Alvin-Seville** [comment]
@CyrusNajmabadi, thanks for the answer. Could you tell me how to fix my code?

**Comment by Youssef1313** [comment]
@Alvin-Seville I think you can try returning tge node itself instead of a pointer.
and anyway, I wouldn't use unsafe code without a good reason.

**Comment by CyrusNajmabadi** [comment]
I would change Node to be a class, and I would remove the pointer part. :-)
