### ISSUE TITLE
Renaming to an identifier with an underscore only shows the underscore in the Preview Changes window

### ISSUE THREAD

**Issue by Vannevelj** [dotnet/roslyn#4718]
I have an analyzer that changes private fields to the form `_lowerCamelCase`. When you perform a batch fix, it shows up in the window like this:

![renamewindow](https://cloud.githubusercontent.com/assets/2777107/9414668/90601374-483a-11e5-961b-06e833bbf4fb.PNG)

Obviously I would like for this to show the actual variable name (`_state`) rather than just the underscore. When you look at the tooltip you can see that it only selects the underscore.

![renamepopup](https://cloud.githubusercontent.com/assets/2777107/9414707/d5dc661e-483a-11e5-9413-8117c1b7e17c.png)

**Comment by Pilchie** [comment]
This is #3792

**Comment by Vannevelj** [comment]
Ah, I guess I didn't search well enough. This one can be closed then.
