### ISSUE TITLE
Implement Interface through member adds extra casts

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#472]
Ported from TFS WorkItem: **1105750** and [http://roslyn.codeplex.com/workitem/482](http://roslyn.codeplex.com/workitem/482)

SSL reported:

Source:
```
sealed class X : IComparer{
X x;
}
```
Quick fix:
```
public int Compare(object x, object y) {
return ((IComparer)this.x).Compare(x, y);
}
```

Why do you add the cast, even when there is no explicit implementation?
The cast is highlighted as unnecessary (only when the class is sealed)

**Comment by DustinCampbell** [comment]
I bet we never updated this fix to use the simplifier API.

**Comment by shyamnamboodiripad** [comment]
@jmarolf could you please verify this?
