### ISSUE TITLE
About Visual Studio 2019 version 16.6.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47201]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1111836/about-visual-studio-2019-version-1663.html)._

---
<p>Return the text color of class and function like the previous version, this all white text is very confusing!</p>

---
#### Feedback Bot on 7/13/2020, 10:50 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Dante Gagne [MSFT] on 7/17/2020, 02:33 PM: 

<p>Thank you for your feedback. Can you share a bit more information with us? What language are you using? What color theme in Visual Studio (Dark? Light?)? I’m not completely sure what you’re referring to and that information would make it easier to help with your suggestion.</p>

#### Feedback Bot on 7/29/2020, 03:08 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.
#### Trần Tấn Phước Hồ on 7/29/2020, 03:28 AM: 

(private comment, text removed)
#### Dante Gagne [MSFT] on 8/21/2020, 09:44 AM: 

(private comment, text removed)
#### Dante Gagne [MSFT] on 8/21/2020, 09:45 AM: 

<p>Thanks @<a target='_blank' href="https://developercommunity.visualstudio.com/users/268665/amattano.html">a_mattano</a>. I’ve routed this over to the C# team for their response.</p>

**Comment by mikadumont** [comment]
@JoeRobich

**Comment by JoeRobich** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/47320. We simplified and removed a faulty heuristic which was setting the configured ColorScheme to VS2017.
