### ISSUE TITLE
Completion can be triggered in Metadata as Source and Generated Source files

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#47207]
If you open either a Metadata as Source file or a file from a source generator, you can trigger the completion list:

![image](https://user-images.githubusercontent.com/201340/91501111-cad70f00-e879-11ea-95da-80b6facd1a52.png)

**Comment by jasonmalinowski** [comment]
Moving this to 16.9 just because it's also happening in Metadata as Source, and we never noticed that for years. :smile:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback of this actually being an issue.
