### ISSUE TITLE
Update IntelliSense tooltips to show actual type of alias

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47200]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1163451/update-intellisense-tooltips-to-show-actual-type-o.html)._

---
```csharp
namespace Foo
{
    public class Bar
    {
        public int Quux { get; set; }
    }
}

using Corge = Foo.Bar;

var grault = new Corge();
grault. Quux = 42;
```

Hovering over `grault` in the above snippet will show "Corge"; it would be more useful if it showed the actual type name behind the alias, with an annotation to indicate that it's an alias, i.e. something like "(alias) Foo.Bar" (much like the way that extension methods are annotated).

Similarly, hovering over `Quux` in the line `grault. Quux = 42;` will show "int Corge.Quux". Again it would be more useful to rather display "int (alias) Foo.Bar.Quux".

This could even be a configurable setting in Tools > Options.

---
#### Feedback Bot on 8/27/2020, 02:57 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by JoeRobich** [comment]
At this week's design meeting, it was decided it would be obvious to show when hovering over the alias identifier, but that we would need a proposal for how to handle other cases of QuickInfo before moving forward.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
