### ISSUE TITLE
Diagnostics in razor files are mapped incorrectly

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#47214]
Currently using 16.8preview 2 with latest roslyn master bits

Moving diagnostics to OOP breaks diagnostics in razor files (when using the non-LSP powered razor editor).  The cause of the issue is the following:
https://github.com/dotnet/roslyn/blob/31ebe4954e5455e630acb1e8445ecb742c678753/src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs#L470-L475

In the OOP scenario, the IWorkspaceVenusSpanMappingService is not present.  This makes sense as it needs access to the buffers to map between the primary and secondary buffers - https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioVenusSpanMappingService.cs#L148 and so likely cannot be available OOP.

This can be easily repro'd.  Create a .net framework MVC razor application and replace the text in Index.cshtml with
```
<a onerror="foo(@aaaa, @bbbb, @ccccc)"></a>
<script>
    var # = goo(@dddd, @ffff)
</script>
```

Use the "Use 64-bit process for code analysis" checkbox - when unchecked (running inproc) the service is not null and returns the correct line mappings:
![cshtml_working](https://user-images.githubusercontent.com/5749229/91502581-44243100-e87d-11ea-8e10-d9c375abb29b.png)

When checked (running oop), the service is null in the OOP process and the line mappings are incorrect
![cshtml_broken](https://user-images.githubusercontent.com/5749229/91502607-53a37a00-e87d-11ea-9124-64eaed3115be.png)

It seems like the mappings need to be calculated in the in-proc portion.

**Comment by mavasani** [comment]
@dibarbet Would it be possible to write a unit test/integration test for this? I'll work towards fixing this, but I can't guaranteed me/someone else will break this again soon :-)

**Comment by dibarbet** [comment]
I was looking at it yesterday afternoon.
For integration tests it's a little difficult as I think I would have to introduce razor projects into the integration test stuff.  Unit tests are a little difficult as well as I would need to setup the projection buffers.  @jasonmalinowski do you know if there is a place where we setup projection buffers in unit tests that I could re-use?

**Comment by mavasani** [comment]
Thanks, I have create a PR with product fix: https://github.com/dotnet/roslyn/pull/47253. Let me know if you'd like me to open a test issue to track adding some tests in this space.

**Comment by dibarbet** [comment]
@mavasani filed https://github.com/dotnet/roslyn/issues/47254 for me
