### ISSUE TITLE
[loc][query] translation question.

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn#47219]
String Resource ID | 0; "Name_is_not_a_valid_0_identifier"
-- | --
Source String | Name is not a valid {0} identifier.
Subtenant | dotnet_roslyn
Source Control Link |  
Filename | VisualStudio\Core\Def\xlf\ServicesVSResources.xlf
Question | Please clarify the placeholder.

**Comment by jmarolf** [comment]
> Please clarify the placeholder.

It is the name of the programming language for which this name is not a valid identifier.

Examples would be

- `Name is not a valid C# identifier.`
- `Name is not a valid Visual Basic identifier.`
