### ISSUE TITLE
Source generated files should show the read only lock icon in the tab

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#47215]

**Comment by jasonmalinowski** [comment]
Comment from @davidwengier on how this is done elsewhere: https://github.com/dotnet/roslyn/pull/46949#discussion_r479585978

**Comment by davkean** [comment]
Here's what we do with project content items: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/PackageContentProjectTreePropertiesProvider.cs#L14. 

CPS has a built in way to automatically open these as "read-only".

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
