### ISSUE TITLE
Metadata as Source files and source generated files let you copy the file path to the temporary file

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#47210]
We should disable Copy Full Path and Open Containing Folder.

**Comment by CyrusNajmabadi** [comment]
fwiw, i often find behavior like that super aggravating.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi What do you mean? Do you have a scenario for keeping the commands?

**Comment by CyrusNajmabadi** [comment]
there have been several times when i've navigated or copied these.  for example, for use in other tools.  i don't like when my toolsm make me copy the text out of this, put into a new file that i have to save, just to use it with something else.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
