### ISSUE TITLE
Field doesn't need to be volatile

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47225]
IDE0044 suggests the field to be readonly, which can't be used together with volatile.

https://github.com/dotnet/roslyn/blob/3dc15320d76662294a8544522340823b371efc5c/src/Scripting/CoreTestUtilities/ObjectFormatterFixtures/MockDesktopSpinLock.cs#L18

It seems reasonable that volatile can be omitted. The field is only set in the constructor. How can multiple threads modify it?

**Comment by huoyaoyuan** [comment]
Already fixed by #43542 .

**Comment by Youssef1313** [comment]
@huoyaoyuan the diagnostic is produced in #48277
Is it because an old version is used in the repository?
