### ISSUE TITLE
Unexpected CS8602 in nested lambda expression

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/roslyn#47226]
**Version Used**: 

5.0.100-preview.8.20417.9

**Steps to Reproduce**:

Build the following (simplified) program using `dotnet build`, targeting `net5.0`:

```c#
#nullable enable
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine(Func(() => "Bla")()());
        }

        private static Func<Func<string?>> Func(Func<string> c)
        {
            return () => c switch
            {
                 {} s => () => s(), // <== warning CS8602: Dereference of a possibly null reference.
                _ => () => null
            };
        }
    }
}

```
**Expected Behavior**:

No warning, since there is no way `s` can be `null`.

**Actual Behavior**:

"warning CS8602: Dereference of a possibly null reference." at the line indicated

**Comment by EamonNerbonne** [comment]
(this is a regression, there's no warning in stable)

**Comment by RikkiGibson** [comment]
This no longer reproduces in [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFAACATAIxVWlhxQAOEAxkQMID2aKPwIBBdu0aUA3lULzCASzTwEpLITqb6AdjkLZlBccLsEigG4R42gGyaALIQCyEZQApq9AAwBtALqEEAgA5lAAlPomhIbR0V4AnJ4ArO7u4YQAvAB8hABEAEK4eeHp6eEA3FEmAL5MRnFmltZEXvbUyQA8Hd0+APzZuR0pvd65XJEN0bFxxtQ6hOlZ44RQAO6KMFwAFtWzM7Nx0jWry4sZOavpADSEAPR3hJ2ZmYRrwWjKIYS8AMoAHLZvLQQIQACKIOAAM0haB4hH4UKCpn4UCginwAE9CJgcIQENDYTwAHR7Q7yAD6ZyWl1xWDJ0RqVSmtWqdUoNSAA=).
