### ISSUE TITLE
[Question] What's the proper way to get KindText for a SyntaxNode

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47238]
The approach I know to do that is call `.Kind()` extension method, then call `.ToString()`.
The problem with that is there are 2 `Kind` extension method, one for C# and one for VB.

Is there other way instead of checking the language first, then call the appropriate .Kind method given that I want the Text at the end?

If there is no way currently, consider this issue as an API proposal.

**Comment by Youssef1313** [comment]
Probably this is what I want:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxNodeOrToken.cs#L73

But it's private.

**Comment by CyrusNajmabadi** [comment]
There is no way to do this.  At the common layer the Kind is just an int.  To get the appropriate name (which is language specific) you need each language's view over that int, mapping it to the requisite enum value.

**Comment by Youssef1313** [comment]
Isn't exposing KindText in SyntaxNodeOrToken just fixes that?

**Comment by CyrusNajmabadi** [comment]
That would involve a public API change.  The "proper way" to get this information today is to make the .Kind() call at the VB/C# layer and ToString that.

**Comment by CyrusNajmabadi** [comment]
If you would like to drive this as a proposal, i would recommend opening it as a separate issue :)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Thanks. I opened a separate issue.
