### ISSUE TITLE
Duplicate code fixes offered for IDE0082 (convert typeof to nameof)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47236]
**Version Used**: Latest 16.8 dogfood build

![image](https://user-images.githubusercontent.com/10605811/91592431-68325180-e913-11ea-8543-6a0bc6193ee7.png)

**Comment by Youssef1313** [comment]
The resource with the value `Convert 'GetType' to 'NameOf'` is only used in the VB code fix provider. Very strange to see this title offered for C#.

**Comment by jmarolf** [comment]
I believe this can only happen in a shared project. @mavasani was that the use case where you encountered this?

**Comment by Youssef1313** [comment]
@jmarolf Sounds that this is the case.
The image in issue seems to be from https://github.com/dotnet/roslyn-analyzers/blob/6dea9b867e32607bc02f958efe46d4b2d1220e45/src/Utilities/Compiler/WordParser.cs, which is indeed part of a shared project. https://github.com/dotnet/roslyn-analyzers/blob/6dea9b867e32607bc02f958efe46d4b2d1220e45/src/Utilities/Compiler/Analyzer.Utilities.shproj

**Comment by mavasani** [comment]
I am no longer able to repro the issue in `WordParser.cs` file above. I changed the `nameof(WordParser)` in that file to `typeof(WordParser).Name`  and see the diagnostic, but only see a single code fix being offered.

**Comment by jmarolf** [comment]
Same here: 

![image](https://user-images.githubusercontent.com/9797472/93266976-c8bced80-f75f-11ea-8d94-957d7551187e.png)
