### ISSUE TITLE
Visual Studio crashes

### ISSUE THREAD

**Issue by sergeyQx** [dotnet/roslyn#47230]
**Version Used**: 
Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 2.0

**Steps to Reproduce**:

1. Add the attached file to a newly created C# project
2. open the file
3. type { in line 152 just before the existing brace

**Expected Behavior**:
Brace appears in the editor

**Actual Behavior**:
Visual Studio crashes

**Comment by sergeyQx** [comment]
The attachment
[repro.zip](https://github.com/dotnet/roslyn/files/5142061/repro.zip)

**Comment by sergeyQx** [comment]
Stacktrace of the crash:

Microsoft.VisualStudio.LanguageServices.dll!Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception exception)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 273	C#
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken) Line 208	C#
 	[Resuming Async Method]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParameterList(out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken open, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SeparatedSyntaxListBuilder<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ParameterSyntax> nodes, out Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken close, Microsoft.CodeAnalysis.CSharp.SyntaxKind openKind, Microsoft.CodeAnalysis.CSharp.SyntaxKind closeKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseParenthesizedParameterList()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeListSyntax> attributes, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder modifiers, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeSyntax type, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.TypeParameterListSyntax typeParameterList)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatementCore(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken openBrace, ref Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.NamespaceBodyBuilder body, ref Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder initialBadNodes, Microsoft.CodeAnalysis.CSharp.SyntaxKind parentKind)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax>(System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> parseFunc, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.CompilationUnitSyntax> createEmptyNodeFunc)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(Microsoft.CodeAnalysis.Text.SourceText newText, System.Collections.Generic.IReadOnlyList<Microsoft.CodeAnalysis.Text.TextChangeRange> changes)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(Microsoft.CodeAnalysis.Text.SourceText newText)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(Microsoft.CodeAnalysis.TextAndVersion newTextAndVersion, Microsoft.CodeAnalysis.TreeAndVersion oldTreeAndVersion, System.Threading.CancellationToken cancellationToken) Line 247	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TreeAndVersion> oldTreeSource, Roslyn.Utilities.ValueSource<Microsoft.CodeAnalysis.TextAndVersion> newTextSource, System.Threading.CancellationToken cancellationToken) Line 206	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.CreateLazyIncrementallyParsedTree.AnonymousMethod__0(System.Threading.CancellationToken c) Line 191	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.StartAsynchronousComputation(Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.AsynchronousComputationToStart computationToStart, Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.Request requestToCompleteSynchronously, System.Threading.CancellationToken callerCancellationToken) Line 399	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.TreeAndVersion>.GetValueAsync(System.Threading.CancellationToken cancellationToken) Line 358	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken) Line 633	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Document.GetSyntaxTreeAsync(System.Threading.CancellationToken cancellationToken) Line 195	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Host.BackgroundParser.ParseDocumentAsync.AnonymousMethod__0()	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskQueue.ScheduleTaskInProgress.AnonymousMethod__0(System.Threading.Tasks.Task _) Line 115	C#
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task<Microsoft.CodeAnalysis.SyntaxTree>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown

**Comment by davidwengier** [comment]
This doesn't repro for me on 16.8 Preview 2.1, or newer internal builds.

**Comment by sergeyQx** [comment]
I have reproed this in 16.8.0 Preview 2.1
Have you used the exact repro steps I provided including calling ReSharper action? 
Is there any diagnostics I can enable to provide you with more info?

**Comment by sergeyQx** [comment]
I also removed the comment with the repro solution as it contains my customer code. He gave his consent to share it with Microsoft team only.

**Comment by davidwengier** [comment]
@sergeyQx What ReSharper action? I was following the steps in the first post, of adding the file to a new project, and typing a brace on line 152. If there are other steps, or a smaller repro project can be created, or perhaps even a screenshot/recording of how to repro I would very much appreciate the info.

**Comment by sergeyQx** [comment]
Looks like somet text was lost when the issue was transfered here.

Here are the steps to reproduce:

    install ReSharper into Visual Studio (I used the most recent preview)
    open the solution from the archive
    open EntityBase.cs
    navigate to line 210: public int DirtyChangesCount { get; internal set; }
    set cursor on DirtyChangesCount and apply suggested action "To property with changed notification" from the lightbulb menu

**Comment by sergeyQx** [comment]
Ouch It looks like there are 2 different issue with the same stacktrace. The one I've provided the repro steps from is recently reported.

**Comment by davidwengier** [comment]
Can you link to the other issue you reported? I don't have the solution from the archive, just one file, and of course that doesn't compile so, so I'm not sure if I'll be able to repro the issue even after installing Resharper, as it probably won't offer the same completions.

Ideally a minimal project that can be shared, where the issue repros, would be the best path forward.

**Comment by davidwengier** [comment]
I'm a Microsoft person, so if it's attached to that feedback issue I should be able to access it without issue :)

**Comment by sergeyQx** [comment]
I do not see any visibility restriction here. I guess any other person will be able to see it if I attach it to the comment.
