### ISSUE TITLE
Move to Next or Previous Highlighted Reference hotkeys work unreliable in C# editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47235]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1163962/move-to-next-or-previous-highlighted-reference-hot.html)._

---
In C# code editor when the caret is sitting on an identifier, pressing to "Ctrl+Shift+Up" or "Ctrl+Shift+Down" usually moves the caret to a next or a previous reference.

But when the caret is not sitting on a identifier it flies away to somewhere else. In fact it goes to the Navigation Bar upwards or to the Issue Bar downwards, but it looks exactly like the caret has just disappeared and you don't understand what's happened. So you have to waste the time for investigation and getting the caret back.

It's very annoying behaviour, especially when IntelliSense is a bit slow and is not recognizing the text as an identifier at the moment. 

I suggest to assign this behavior to another hotkeys to keep the "Ctrl+Shift+Up" and "Ctrl+Shift+Down" hotkeys always do the only job and do it reliable.

---
#### Feedback Bot on 8/27/2020, 02:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
@davidwengier can you check if you can repro this

**Comment by davidwengier** [comment]
This still repros.

**Comment by davidwengier** [comment]
Moved the internal bug to the editor team, we're doing everything right here.
