### ISSUE TITLE
Possible documentation bug in naming conventions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47243]
https://github.com/dotnet/roslyn/blob/fa7eeddaf2052dcfee4c75c68f9039c723245737/src/EditorFeatures/CSharpTest/Diagnostics/NamingStyles/EditorConfigNamingStyleParserTests.cs#L289

https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019

The doc states:

> The following list shows the allowable values, and you can specify multiple values by separating them with a comma.
>
> - * (use this value to specify all symbols)
> - namespace
> - class
> - struct
> - interface
> - enum
> - property
> - method
> - field
> - event
> - delegate
> - parameter
> - type_parameter
> - local
> - **local_function**

However, from the code above, it seems like the correct value is **local_functions**, not **local_function**.

**Comment by sharwell** [comment]
I believe `local_function` is correct:

https://github.com/dotnet/roslyn/blob/a8d63c614ee85146079fe96b701c742228963657/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs#L131-L133

**Comment by Youssef1313** [comment]
@sharwell Then that line I referenced of the unit test should be wrong?

**Comment by sharwell** [comment]
That part is a name key. It can be any identifier, including `local_functions`. The part that matters is the value, which is `"local_function"` on the right.

**Comment by Youssef1313** [comment]
@sharwell Ahh, I mixed things. Thought this list is for what comes after `dotnet_naming_symbols.` not the `=` :smile:
Sorry for that.

**Comment by sharwell** [comment]
No problem!
