### ISSUE TITLE
[API Proposal] Expose KindText in SyntaxNodeOrToken

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47247]
I think it's useful to expose the private property `KindText` to be public:

https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/Core/Portable/Syntax/SyntaxNodeOrToken.cs#L73-L89

It will make things much much easier to get the KindText without worrying about the language and having to handle the same thing twice.

Related to #47238

**Comment by Youssef1313** [comment]
I (after two years :smile) am not much convinced that #47238 has enough motivation for this change.

If someone agrees this shouldn't be publicly exposed, feel free to close.

**Comment by CyrusNajmabadi** [comment]
Closing out.
