### ISSUE TITLE
CI doesn't validate changes pushed to master

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47261]
Ok, I think I don't know the terminologies very well. But here is the thing:

1. Two PRs,  "A" and "B", are created from master.
1. PR "B" got merged to master.
1. The branch of PR "A" builds successfully on its own. But it won't build successfully when merged with master because of changes introduced in PR "B". However, the CI passes for PR "A", and errors are only discovered after merging to master.

I think that's what happened with https://github.com/dotnet/roslyn/pull/47222 and https://github.com/dotnet/roslyn/pull/46949 (the branch of #47222 doesn't have the new file created in #46949)

The CI passed with #47222, but the master has build error after merging it. (see https://github.com/dotnet/roslyn/commit/fd0e8520a8c01977e21772bd825526cb41e88a41)

If my analysis is correct, you may consider updating the CI to somehow build the result of merging the PR with master.

**Comment by sharwell** [comment]
This is a timing issue. If the build for A starts before B gets merged, its results can be stale even though success is reported.

**Comment by Youssef1313** [comment]
@sharwell Ah I see. Thanks a lot!
