### ISSUE TITLE
/warn should not accept values greater than the max level supported

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#47279]
[The current design](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Warnversion%20Warning%20Waves.md) suggests to use `9999` or basically any arbitrary value greater than maximum supported level to denote "latest".

This has a consequence of depending directly on the current compiler version and the fact that any value could be used might get confusing.

For instance `7` means "latest" up until the warn level 8 is introduced.

Following `/langversion` I suggest using an explicit input like `latest` for cases maximum level of warning waves is preferred.

**Comment by alrz** [comment]
One possible argument here is that we want an older compiler "just work" with any warn level and possibly fewer produced warnings. But I really don't think that's a good scenario to support when we consider how confusing it could get.

**Comment by NextTurn** [comment]
There is now [`<AnalysisLevel>latest</AnalysisLevel>`](https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/).

**Comment by alrz** [comment]
Yeah I think that is what I'm looking for. Thanks.
