### ISSUE TITLE
Diagnostic for conflicting constructor declarations refer to the conflicting member as '.ctor'

### ISSUE THREAD

**Issue by reflectronic** [dotnet/roslyn#47272]
**Version Used**: 3.7.0-6.20418.4 (9b878f99)

**Steps to Reproduce**:
Define a type with conflicting constructor signatures:
```cs
public class C
{
    public C() { }
    public C() { }
}
```
**Expected Behavior**:
An error which says "Type 'C' already defines a constructor with the same parameter types"

**Actual Behavior**:
error CS0111: Type 'C' already defines a member called '.ctor' with the same parameter types

This compiler diagnostic seems to have been referring to the conflicting member as '.ctor' for a while now. Before that, I believe it would have referred to the conflicting member as 'C'.
Ideally, I think the error message should directly say that there are conflicting *constructors*, since constructors do not naturally have their own name. Regardless, referring to the member as '.ctor' is confusing and should be changed.

**Comment by Youssef1313** [comment]
I think the fix should be straight forward here. I'll work on it.

**Comment by Youssef1313** [comment]
@333fred the fix should be done for both instance constructors (`.ctor`) and static constructors (`..ctor`) right?

**Comment by RikkiGibson** [comment]
it feels like the point where we give CS0111 diagnostics should be adjusted to use a more appropriate method of converting the symbol to string. It shouldn't be necessary to directly check if the symbol is a constructor or static constructor for example.

**Comment by RikkiGibson** [comment]
There might be a minimal SymbolDisplayOptions or something like that which should be used in order to minimize test churn when making this change.

**Comment by Youssef1313** [comment]
@RikkiGibson The fix I worked on was to introduce two separate new errors. Because, the part "with the same parameter types" isn't applicable to static ctors.
So, even if we converted the symbol to a more neat form other than ".ctor" and ".cctor", the message won't be great.
