### ISSUE TITLE
Code fix 'convert to method' can generate invalid code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47287]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1167701/code-fix-convert-to-method-can-generate-invalid-co.html)._

---
When converting a local function, which has one or more optional parameters AND references one or more local variables, to a method, the result will be invalid in the following situations:
- If the local function is invoked without specifying a value for all optional parameters.
- If the local function assigns to one of the local variables.

Example for first case:
```
void TestMethod()
{
    var message = "hello world";

void ShowMessage(bool debugOnly = false)
    {
#if ! DEBUG
        if (!debugOnly)
#endif
        {
            Console.WriteLine(message);
        }
    }

ShowMessage();
}
```

This gets turned into:
```
        void TestMethod()
        {
            var message = "hello world";

ShowMessage(message); // ERROR CS1503
        }

private static void ShowMessage(bool debugOnly = false, string message = null)
        {
#if ! DEBUG
            if (!debugOnly)
#endif
            {
                Console.WriteLine(message);
            }
        }
```

Example for the second case:
```
        void TestMethod()
        {
            var message = "hello world";

void ChangeMessage(string newMessage = null)
            {
                message = newMessage;
            }

ChangeMessage("HELLO WORLD");
        }
```

This gets turned into:
```
        void TestMethod()
        {
            var message = "hello world";

ChangeMessage("HELLO WORLD", ref message);
        }

private static void ChangeMessage(string newMessage = null, ref string message) // ERROR CS1737
        {
            message = newMessage;
        }
```

---
#### Feedback Bot on 8/31/2020, 00:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
