### ISSUE TITLE
The compiler should include the URL in the command line output

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#47310]
For diagnostics that have a URL (e.g. the new obsolete attribute or custom analyzers) the compiler should include the URL when printing messages. This is especially useful on the command line or when troubleshooting CI failures.

We just got more customer feedback (from internal teams) that they didn't find the IDE's rendition of the URL discoverable, which I previously raised as well (#42103). Adding the URL to the message would be helpful, especially for messages that can't be localizable (such as the obsolete attributes).

/cc @jeffhandley @GrabYourPitchforks

**Comment by jaredpar** [comment]
What URL are you speaking about here?

**Comment by GrabYourPitchforks** [comment]
The optional URL that's associated with the `ObsoleteAttribute`. See for instance:

https://github.com/dotnet/runtime/blob/407f8f7a4ea707b94a6a8b8fef19e47f9033e898/src/libraries/System.Threading.Thread/ref/System.Threading.Thread.cs#L53-L54

**Comment by Youssef1313** [comment]
I may take this one.
But just to make sure I'm getting things correctly, is the fix like the following:

1. If UrlFormat is null or empty, keep the current behavior.
1. Otherwise, use a new error/warning message that shows the extra information using `string.Format(UrlFormat, DiagnosticId)`.

**Comment by terrajobst** [comment]
It's not just about the URL of `ObsoleteAttribute`, it should apply to any diagnostic raised by analyzers as well, as they have a [URL property too](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/DiagnosticDescriptor.cs,4a0a00cc5df1dbb4,references).
