### ISSUE TITLE
Navigating back and forth between documents quickly NullRefs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#47322]
**Version Used**: 
Version 16.8.0 Preview 3.0 [30431.102.main]

**Steps to Reproduce**:

1.  No repro, but it happens a few times a day when I quickly switch between documents using Back and Forth on my mouse

**Expected Behavior**:

```
System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.<GetSuggestedActionCategoriesAsync>d__35.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.<CallExtensionPointAsync>d__36`1.MoveNext() 

--- End of stack trace from previous location where exception was thrown ---    
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```

**Comment by ryzngard** [comment]
@jinujoseph  we should consider this for 16.8. I filed an internal bug with tracking details for telemetry https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1197657

**Comment by davidwengier** [comment]
Just hit this under the debugger. The specific exception is that `_owner` is null, but the real issue is that something is holding on to a disposed instance.

**Comment by davidwengier** [comment]
I've moved the internal bug to the editor team, as looking at the code it seems the editor owns the lifetime of these. Will leave this open for you to decide what to do @ryzngard as it would certainly be possible to work around the NRE, if you think the hits are high enough to warrant it.

Dump here if it helps: \\mlangfs1\public\dawengie\NullRefInSuggestedActionsSource.zip

**Comment by AmadeusW** [comment]
I created a [PR on the Editor end](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/273164). When `ITextView` closes, 
1. we won't make any new requests, and 
2. we will cancel the cancellation token passed to existing requests. 

However, this won't fully eliminate the race condition:
Suppose `ITextView` gets closed after calling `GetSuggestedActionCategoriesAsync` and therefore `ISuggestedActionsSource` will get disposed in the middle of handling the request. 
I believe that Roslyn will need to either 

1. catch exception when the source is disposed,
2. implement locking, or
3. hope that this race condition is rare enough that we won't need to do anything. After all, Editor catches exceptions thrown by `ISuggestedActionsSource`s.

**Comment by CyrusNajmabadi** [comment]
I don't see how it's ok to dispose an object you have passed to some other clients and are waiting on responses for. Shouldn't disposal happen angry all these running operations complete?

**Comment by davidwengier** [comment]
Closing this as the internal PR linked above is complete.
