### ISSUE TITLE
When the CodeAnalysis service hub disappears the IDE becomes unusable with no indication of what went wrong

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#47323]
**Version Used**: 
Version 16.8.0 Preview 3.0 [30431.102.main]
Logs: [61651F3E-ManagedLanguage.IDE.RemoteHostClient-34884-z51jey5n-1.zip](https://github.com/dotnet/roslyn/files/5154135/61651F3E-ManagedLanguage.IDE.RemoteHostClient-34884-z51jey5n-1.zip)

My Visual Studio become pretty usable and I had no idea what was wrong, things I experienced:

1) Errors stopped being populated in the Error List

2) Compilers errors from build never appeared in the Error List under either Build or IntelliSense (perhaps Roslyn should tell project-system this by throwing from IVsLanguageServiceBuildErrorReporter2 so it can at least populate these)

3) Find all References started returning no results
![image](https://user-images.githubusercontent.com/1103906/91798665-c2f7e000-ec68-11ea-8ee7-746e41589101.png)

4) Test Window became unusable

![image](https://user-images.githubusercontent.com/1103906/91798651-ba070e80-ec68-11ea-81d4-721bbd2d6801.png)

I tried reloading the solution and it didn't resolve the problem. I work on Visual Studio and didn't make the connection between above and the service hub process disappearing until after I reached out to the IDE team.

**Comment by tmat** [comment]
We have fixed multiple issues in OOP infra. Pelase reopen if this issue occurs again.
