### ISSUE TITLE
Analyzers should be invoked only in a single phase when compiling Razor projects

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#47350]
### Analyzer

**Diagnostic ID**: RS0016: `Symbol '{0}' is not part of the declared API.`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

Razor projects have a two phase compile, where a project is compiled once, then that is used to generate more code, and then compiled again with the new code.  The problem is that some of the generated code is public, and the analyzers seems to run both times.  This means that the analyzer either reports errors during the first phase (because the baseline include API from the second phase), or the second phase (because it doesn't).

Additionally, the VS experience doesn't offer to generate any of the API from that generated public API.

### Steps To Reproduce

1. Make a new ASP.NET Core Web Application project of the "Web Application" variety.
2. 

### Expected behavior
Can generate a baseline for the API generated from the razor file, and have it work.

### Actual behavior
Errors about either missing APIs, or too many APIs.

## Additional context
 Affecting dotnet/aspnetcore's ability to capture our public api using the analyzer in https://github.com/dotnet/aspnetcore/pull/25386.

**Comment by mavasani** [comment]
@Pilchie so I believe the fix here needs to go into Razor targets files - during the first phase of the compile, you should explicitly disable diagnostic analyzers by setting `RunAnalyzers` MSBuild property to `true`. This will skip diagnostic analyzers, while still executing source generators. The second phase with final compilation will respect user's setting for `RunAnalyzers` to decide whether or not analyzers are executed.
Another very targeted workaround would be to just disable the public API rules using/generating an editorconfig file in the folder where generated source files are generated.

**Comment by Pilchie** [comment]
@pranavkm - should we move this aspnetcore to adjust the targets?

**Comment by mavasani** [comment]
Moved to https://github.com/dotnet/aspnetcore/issues/25703
