### ISSUE TITLE
Rename record results in extremely odd behavior

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#47357]
**Version Used**: VS 16.8 preview 2

**Steps to Reproduce**:

When renaming a record in visual studio, it replaces the parameter list with a duplicate of the record name:

![rename-record](https://user-images.githubusercontent.com/29174528/91938108-0b141280-ecfc-11ea-980d-257a9d45a9fe.gif)

**Comment by huoyaoyuan** [comment]
Also hit this in 16.8P1. Forgot to open an issue for this.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Who is doing the ide test pass for records?

**Comment by CyrusNajmabadi** [comment]
Current issue is that the .Location for record constructors is a bit surprising.  (it's the span of the `(bool IsAsync)` parameter list).  @AlekseyTs has volunteered to put the .Location in a more friendly and consistent span of the type's .Identifier token.  When that goes through this should either just work, or will be much easier to address on the IDE side.
