### ISSUE TITLE
Stepping through Roslyn while Debugging VSIX

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4736]
Now that I am able to build Roslyn, I am trying to figure out how to step through my application as it calls Roslyn. I have tried disabling "Just My Code", pointing Symbol Server at ..\Roslyn\Binaries\debug. Then from one instance of Visual Studio I start debugging, a second instance of Visual Studio opens, I open a test application that uses my refactoring. In the original VS instance I set breakpoint to a line where I call into Roslyn (specifically Project.AddDocument). When I hit the breakpoint, I select "step into" and VS happily does a step over. If I set a function Breakpoint at AddDocument, I break with a screen as shown below, it does not show what breakpoint was hit, what source is not available and there is no option to browse to source. 
![capture](https://cloud.githubusercontent.com/assets/12789369/9423164/d88c6e30-486d-11e5-8393-c87173dede00.JPG)

If I am going about this completely wrong, please point to correct instructions.

**Comment by diryboy** [comment]
#1781 ?

**Comment by paul1956** [comment]
I don't think it is the same issue, but correct me if I am wrong. I really don't want to debug Roslyn, I want to debug my VSIX that calls into Roslyn DLL's. I have been getting less than helpful errors mostly in the forms of ex{"OperatorToken"} where OperatorToken changes. I understand the usability issue is being addressed in 1.1 but I still want to be able to source step into Roslyn like I can into .Net.

**Comment by diryboy** [comment]
OK, not the same issue. I guess this need release PDBs from MS?

**Comment by paul1956** [comment]
By building Roslyn I have the PDBs, that is why I built it. I have also pointed to MS symbol servers (3) but neither is sufficient.

**Comment by diryboy** [comment]
I meant the original PDBs that were built along with the DLLs deployed to the VS2015 product. Self built PDBs may not match the DLLs, but not sure if the matching checks could be ignored.

**Comment by paul1956** [comment]
I could build the PDBs to match, but I don't see how to connect them with Visual Studio. I have pointed VS (options/debugging/source) to the location I built Roslyn with DEBUG but

**Comment by diryboy** [comment]
The Roslyn DLLs loaded by VS currently are release version under the Private Assemblies within VS installation folder. So maybe you should try building the release PDBs?

**Comment by paul1956** [comment]
I have built them, the PDBs are under Roslyn/debug... which is where I point the symbol server but there is a connection still missing.

The Roslyn libraries are installed through NuGet and when I hit a break inside them, VS does not look for the source or allow me to browse for them.

**Comment by davkean** [comment]
You're basically hitting two different issues here:

1) We don't publish private symbols for Roslyn that enable you to step through RTM source.

2) We don't let you build roslyn for yourself, deploy to Visual Studio and step through this code.


1) is being tracked by https://github.com/dotnet/roslyn/issues/1524
2) is being tracked by https://github.com/dotnet/roslyn/issues/1781.
