### ISSUE TITLE
Goto and labels don't work in interactive/scripts

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#4737]
```C#
Label: ; 
goto Label;
```

```
error CS0159: No such label 'Label' within the scope of the goto statement
```

See test ```TopLevelLabel```.

Related internal bug: 522569

- Labels should be scoped to the containing script/submission (i.e. cross-submission and cross-file gotos are not allowed).
- Goto should work just like it works in method bodies.
- Principle: Copy & paste from regular C# method should work.

**Comment by ManishJayaswal** [comment]
may be a dupe of #3712
