### ISSUE TITLE
[Feature Request]: Highlight TODO comments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47376]
It would be nice if TODO comments are highlighted in a different color. If this is accepted, I'll be glad to implement this, but will need a starting point on how this should be done.

**Comment by sharwell** [comment]
Duplicate of #25619

**Comment by Youssef1313** [comment]
@sharwell The other issue is closed, is this tracked internally?

**Comment by sharwell** [comment]
Yes there is an internal tracking bug.

/cc @olegtk for another report of this feature request
