### ISSUE TITLE
Brace completion on target-typed-new introduces a new line

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#47381]
I intend to type `C c = new() { ... };` but a newline gets introduced, which is pretty annoying.

![target-typed-new-completion](https://user-images.githubusercontent.com/12466233/92012450-4e24b480-ed01-11ea-9478-5186a212b780.gif)

Relates to https://github.com/dotnet/roslyn/issues/46397

**Comment by alrz** [comment]
Yup. The PR is up https://github.com/dotnet/roslyn/pull/47383, need feedback on test coverage.

**Comment by BillWagner** [comment]
Related: I'm not getting intellisense on init-only properties inside the brackets.  Example:

```csharp
    public class WeatherStation
    {
        public string Location { get; init; }
        // etc.
    }
```

Start typing:

```csharp
WeatherStation station = new () { Locati
```

Intellisense doesn't suggest `Location` as a completion.
