### ISSUE TITLE
[Question] csproj's DefineConstants

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47385]
https://github.com/dotnet/roslyn/blob/2f510ce51a222f618e85a5084683ea41d1a70db2/src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.UnitTestUtilities.csproj#L8

https://github.com/dotnet/roslyn/blob/5d8e2beae1da0c2d789d92b57cac9ff900aa529f/src/ExpressionEvaluator/Core/Source/ResultProvider/NetFX20/ResultProvider.NetFX20.csproj#L8

Are both `,` and `;` supported? or one of the above is buggy?

To me, it seems like the `,` is buggy.

See https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Microsoft.NET.Build.Tasks/CompilationOptionsConverter.cs#L20

**Comment by sharwell** [comment]
Both are supported. `,` is documented as correct, but `;` is more common in practice. I prefer to use the documented separator, but best policy here is to leave them as they are found.
