### ISSUE TITLE
Find All References does not find implicitly typed usage

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47393]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1169933/find-all-references-does-not-find-implicitly-typed.html)._

---
When using Find All References on a type (specifically a class), my expectation is that this will list all code where the type is used. If the type is used implicitly, by being inferred by the compiler, Find All References will not list that usage.

For example, either of the below will be listed:

```
EntityClass entity = dbContext.Entities.FirstOrDefault(e => e.Id == 1);
var entity = dbContext.Entities.FirstOrDefault<EntityClass>(e => e.Id == 1);
```

but this will not be listed:

```
var entity = dbContext.Entities.FirstOrDefault(e => e.Id == 1);
```

From a functional point of view, this is not a distinction I make when I want to Find All References to a type. I want to see where the type is used, not where the name is typed out explicitly.

---
#### Feedback Bot on 9/1/2020, 07:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is currently the design of FindReferences.  There are no known approaches we can take here that can provide results while also meeting our objectives around performance of the feature.

**Comment by jhv2017kam** [comment]
This is also a problem for implicit used default constructor

    // implicit constructor calls not listed in Find All References result
    namespace WinFormsApp1
    {
        class Base
        {
            public Base() // Find All References
            {
            }
        }

        class DerivedExplicit: Base
        {
            public DerivedExplicit() : base() // listed as reference
            {
            }
        }

        class DerivedImplicit1 : Base
        {
            public DerivedImplicit1() // NOT listed as reference
            {
            }
        }

        class DerivedImplicit2 : Base // NOT listed as reference
        {
        }
    }
