### ISSUE TITLE
Interface extension method not found by VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47394]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170704/interface-extension-method-not-found-by-vs.html)._

---
[severity:Other]
Hi

It's legal in c# to define an extension method for an interface. A class implementing this interface must be able to call that method. Strangely, this works properly for `this. CallExtensionMethod()`, but VS displays an error for `CallExtensionMethod()`, i.e. when `this` gets omitted. 

See code below for a better explanation: 

```
using System;

namespace InterfaceExtensionMethodProblem {

public interface ISample {}

public static class ISampleExtension {
    public static string GetSomething(this ISample sample) {
      return sample. GetHashCode(). ToString();
    }
  }

public class Sample: ISample {
    public Sample() {
      this. GetSomething(); //ok
      GetSomething(); //shows error
    }
  }
}
```

---
#### Feedback Bot on 9/2/2020, 00:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This behavior is *probably* correct. Extension methods are meant to be called on an instance of their first parameter, which in this case is `this`. An alternative to call the extension method in this case will be `ISampleExtension.GetSomething(this);` (which is uncommon to be used in C#, but it's valid).

**Comment by CyrusNajmabadi** [comment]
Closing out as this behavior is correct as per the language specification.  Extension methods are only found when accessed off of an explicit receiver.  i.e. `foo.Extension()`.  an implicit receiver (like an implicit `this`) does not count.

Customer can propose a language change at dotnet/csharplang if they would like that behavior to be supported.
