### ISSUE TITLE
VS2019 doesn’t want to respect my solution’s .editorconfig’s C# tab settings when it auto formats code

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#47396]
Direct customer ask copying here: 

>o	It uses spaces still. Even after I configured the C# Text Editor settings to use tabs as well
o	I generated the .editorconfig initially using the IntelliCode generator, then changed the indent style to tabs
o	When I type the ‘}’ character and it ends up auto formatting to try and place my cursor in between the {} on a empty line. I have to Ctrl Z to get out of the auto formatting
o	When I use refactoring suggestions, like converting a switch statement to a pattern matching statement, all the converted code is using spaces
o	If I format document/selection, VS correctly uses tabs
o	This almost feels like a passive aggressive way to try and convert me to spaces. Do not want 😊

**Comment by kornman00** [comment]
Here is another example of VS2019 not only ignoring my .editorconfig, on top of it also formating using \n, when the entire file is \r\n (as can be seen at the bottom, from the document I have open behind this window). If I were to apply this "fix formatting"* then I'd have MIXED line endings, which I would only get a warning and fix prompt the NEXT time I opened the document

* I'm not sure what formatting it wants to fix besides prefixing my return statement with spaces instead of tabs

![image](https://user-images.githubusercontent.com/1270047/92200156-f0da5180-ee2d-11ea-8c0a-006c19ce8438.png)

**Comment by sharwell** [comment]
> ... I'd have MIXED line endings ...

@kornman00 This is a different issue. See #47382.

**Comment by kornman00** [comment]
> @kornman00 can you provide us with a way to reproduce this? Thanks!

@CyrusNajmabadi Thanks, I can work on trying to setup a minimal project to repro later this week.

However, I think I have narrowed down the issue. Initially, I created a solution level .editorconfig file which was "initially inferred by Visual Studio IntelliCode" (and also configured it to `root=true`). This generated the following, which I switched to my tab settings:
```
[*.cs]

#Core editorconfig formatting - indentation

indent_style = tabs
tab_width = 4
```
What do I mean by "solution level"? The sln itself references it ("Solution Items"), and it lives at the root level next to the .sln file. The two projects in the sln are in subfolders.

However, after adding a catch all to the top of the file to always use tabs _everywhere_, Code Style stopped using spaces
```
[*]
indent_style = tabs
tab_width = 4
```

So, it would _seem_ that maybe the editorconfig settings that Code Style is pulling from is not narrowed to the file extension of the file being edited?

Hope this helps in the meantime

**Comment by kornman00** [comment]
...however, it would appear whatever formats expanding `///` to an autogenerated xmldoc is NOT covered by that catch all. And there would appear to be other cases where this is not worked around by the catch all `[*]`.
Typing `public void Foo() {` results in the closing `}` automatically being added and my cursor being placed `{ /*here*/ }`. Then pressing enter:
```C#
		public void Foo()
        {

        }
```
The lines with the bracket have spaces. the declaration line retains the tabs, while the cursor is placed within the body and virtually indented with tabs.

**Comment by CyrusNajmabadi** [comment]
@kornman00 if you can provide a repro snapshot somewhere (i.e. a git repo), along with repro steps, that would be helpful.
