### ISSUE TITLE
Simplifier.ReduceAsync lacks overload that accepts a SyntaxTree

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#474]
Ported from TFS WorkItem: **1079548**

------------------------------

***@aarnott** reported:*

When using the syntax tree API to generate code, at the conclusion of code generation I want to simplify the generated code using the Simplifier. But this requires a Document. I have no Document because the generated code will be added to the project later (by the project system). I do have a Workspace. 

Why is there no API for Simplifier.ReduceAsync(SyntaxTree, Workspace) ?

<br>

I could create a Document and reduce that, but that's lossy and inefficient. (bug 1079550)

<br>
<blockquote style="margin-right: 0px;" dir="ltr">

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> emittedTree = </span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">SyntaxFactory</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.CompilationUnit()</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">.WithUsings(</span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">SyntaxFactory</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.List(inputFileLevelUsingDirectives))</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">.WithMembers(</span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">SyntaxFactory</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.List(emittedMembers))</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">.WithLeadingTrivia(</span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">SyntaxFactory</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.Comment(GeneratedByAToolPreamble));</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: green; font-family: Consolas; font-size: 10pt;">// Format the tree to get reasonably good whitespace.</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> formattedTree = </span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">Formatter</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.Format(emittedTree, workspace, workspace.Options);</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: green; font-family: Consolas; font-size: 10pt;">// Reduce the document to get rid of unnecessary fully-qualified type names that just hurt readability.</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> formattedText = formattedTree.GetText();</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> document = inputDocument.Project.AddDocument(</span><span style="color: rgb(163, 21, 21); font-family: Consolas; font-size: 10pt;">"generated.cs"</span><span style="color: black; font-family: Consolas; font-size: 10pt;">, formattedText);</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> annotatedDocument = document</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">.WithSyntaxRoot((</span><span style="color: blue; font-family: Consolas; font-size: 10pt;">await</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> document.GetSyntaxRootAsync())</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">.WithAdditionalAnnotations(</span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">Simplifier</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.Annotation)); </span><span style="color: green; font-family: Consolas; font-size: 10pt;">// allow simplification of the entire document</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> reducedDocument = </span><span style="color: blue; font-family: Consolas; font-size: 10pt;">await</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> </span><span style="color: rgb(43, 145, 175); font-family: Consolas; font-size: 10pt;">Simplifier</span><span style="color: black; font-family: Consolas; font-size: 10pt;">.ReduceAsync(annotatedDocument);</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: green; font-family: Consolas; font-size: 10pt;">// Now render as a complete string, as necessary by our single file generator.</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: blue; font-family: Consolas; font-size: 10pt;">var</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> reducedDocumentText = </span><span style="color: blue; font-family: Consolas; font-size: 10pt;">await</span><span style="color: black; font-family: Consolas; font-size: 10pt;"> reducedDocument.GetTextAsync();</span><span style='color: black; font-family: "Calibri",sans-serif;'></span>

<span style="color: black; font-family: Consolas; font-size: 10pt;">generated = reducedDocumentText.ToString();</span>

------------------------------
@srivatsn commented:

As we're rethinking this API let's consider this overload as well.

------------------------------

**Comment by mattwar** [comment]
Simplification needs access to symbols, so it requires a semantic model that comes from a document.
