### ISSUE TITLE
Cannot resolve dependencies for latest packages on MyGet

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#4741]
I'm trying to install the latest version of Microsoft.CodeAnalysis.Common from the [roslyn-nightly MyGet](https://www.myget.org/gallery/roslyn-nightly), which is currently 1.1.0-beta1-20150822-02.

The problem is that it depends on version 1.1.0-beta1-20150822-02 of Microsoft.CodeAnalysis.Analyzers, which is not available at the MyGet, the latest version of that package is 1.1.0-beta1-20150812-01.

The output from Package Manager is:

> Attempting to gather dependencies information for package 'Microsoft.CodeAnalysis.Common.1.1.0-beta1-20150822-02' with respect to project 'MyProject', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Microsoft.CodeAnalysis.Common.1.1.0-beta1-20150822-02' with DependencyBehavior 'Lowest'
Unable to find a version of 'Microsoft.CodeAnalysis.Analyzers' that is compatible with 'Microsoft.CodeAnalysis.Common 1.1.0-beta1-20150822-02 constraint: Microsoft.CodeAnalysis.Analyzers (= 1.1.0-beta1-20150822-02)'.

If I try to install version 1.1.0-beta1-20150812-01 of Microsoft.CodeAnalysis.Common instead, everything works fine.

So this wouldn't be a big problem itself, but as far as I can tell, this means that there is no version of Microsoft.CodeAnalysis.Scripting.CSharp that I can install, since the oldest version of that package that is available is 1.1.0-beta1-20150814-01.

**Comment by emimull** [comment]
Same problem here. Also, I tried using I attempted to use Microsoft.CodeAnalysis.Scripting.CSharp v1.1.0-beta1-20150812-01 and everything resolves correctly. However, when running a very simple console app utilizing the package in question, it will complain about the assemblies System.Collections.Immutable and System.Runtime being incorrect or not found.

The newest Roslyn package failing is probably due to Microsoft.CodeAnalysis.Analyzers nightly package being 1 week old (has somehow failed its build), and the other packages have not.

**Comment by svick** [comment]
@emimull How did you manage to do that? I don't see that in the list of available versions. And when I try to do it manually, I get an error:

```
PM> Install-Package Microsoft.CodeAnalysis.Scripting.CSharp -Version 1.1.0-beta1-20150812-01
Attempting to gather dependencies information for package 'Microsoft.CodeAnalysis.Scripting.CSharp.1.1.0-beta1-20150812-01' with respect to project 'MyProject', targeting '.NETFramework,Version=v4.6'
Install-Package : Package 'Microsoft.CodeAnalysis.Scripting.CSharp' is not foundAt line:1 char:1
+ Install-Package Microsoft.CodeAnalysis.Scripting.CSharp -Version 1.1.0-beta1-201 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by emimull** [comment]
@svick I forgot to mention that I did this maybe 4 days ago when the package was still available. Sorry for the confusion.

**Comment by pjmagee** [comment]
I'm getting the same problem. I've been wanting to check out the new scripting api and some extension methods related to the semantic model etc and they're only in the nightly builds but when I try to get the package from `myget/F/roslyn-nighty/` it fails to resolve dependency `'System.Reflection.Metadata (> 1.1.0-alpha-00012).`

:+1:

**Comment by svick** [comment]
@pjmagee I believe you need [the .Net Core MyGet](https://www.myget.org/gallery/dotnet-core) for that.

**Comment by jerhon** [comment]
I'm also having problems resolving 

Microsoft.AnalyzerPowerPack
Microsoft.CodeAnalysis.Analyzers 
Microsoft.CodeAnalysis.FxCopAnalyzers 
System.Runtime.Analyzers 
System.Runtime.InteropServices.Analyzers 

Haven't been updated on myget in 2 weeks now.

https://www.myget.org/gallery/roslyn-nightly

**Comment by svick** [comment]
It looks like #4783 fixed this.
