### ISSUE TITLE
No documents in projects

### ISSUE THREAD

**Issue by Thaval** [dotnet/roslyn#47419]
**Version Used**: 
3.7 (Microsoft.CodeAnalysis)
**Steps to Reproduce**:

1. Create a solution
2. Add some projects  (.NET Core: Console, WPF, XUnit Test) to it and some CSharp/XAML files to the projects
3. Create another project into the solution and load the complete solution using roslyn
4. Iterate over projects and check the HasDocument and DocumentIds.
5. Verify the HasDocument = false and DocumentsIds.Count() = 0.

Code used to open solution:

        public async Task<Solution> OpenSolution(string path)
        {
            MSBuildWorkspace workSpace = MSBuildWorkspace.Create();
            Solution solution = await workSpace.OpenSolutionAsync(path);
            return solution;
        }

**Expected Behavior**:
All XAML/CS files should be recognized. All other files like config, images, etc should also be accessible.
`solution.Projects.All(x => x.HasDocuments);` //should evaluate to true

**Actual Behavior**:
No documents found.
`solution.Projects.All(x => x.HasDocuments);` //evaluates to false

Edit:
After printing the diagnotics of the workspace, I come across the following error message:

> The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.
or
> The SDK 'Microsoft.NET.Sdk' specified could not be found. 

based on the project type. Well, on some github repos and stackoverflow pages, I found that you should set MsBuildSdkPath to the location of the .NET Core SDK. Wellllll.... although it doesn't make any sense, I did it, but it didn't work for me.

**Comment by BhaaLseN** [comment]
I usually see this when I create a .NET Core project and attempt to analyze a .NET Framework project (mainly ones that contains WPF projects). But from your description it seems to be the same result for different inputs (which in the end likely have a similar cause I'm guessing).

Is your other solution in step 3. also .NET Core?

**Comment by Thaval** [comment]
> I usually see this when I create a .NET Core project and attempt to analyze a .NET Framework project (mainly ones that contains WPF projects). But from your description it seems to be the same result for different inputs (which in the end likely have a similar cause I'm guessing).

I added a .NET Framework project to check if it can be loaded or not. The diagnostics tell me:

MSBuild-Error "C:\Users\davaa\source\repos\Davaaron.WPFManager\Davaaron.WPFManager.NETFramework\Davaaron.WPFManager.NETFramework.csproj"
The imported project "C:\Users\davaaron\source\repos\Davaaron.WPFManager\Davaaron.RoslynWrapper\bin\Debug\netcoreapp3.1\Microsoft.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Users\davaaron\source\repos\Davaaron.WPFManager\Davaaron.RoslynWrapper\bin\Debug\netcoreapp3.1\Microsoft.CSharp.targets" is correct, and that the file exists on disk.  C:\Users\davaaron\source\repos\Davaaron.WPFManager\Davaaron.WPFManager.NETFramework\Davaaron.WPFManager.NETFramework.csproj.

The diagnotics for the .NET Core project is only complaining that the Sdk could not be found.


> Is your other solution in step 3. also .NET Core?

Yes, the console application which runs roslyn to inspect the other projects within the solution is also a .NET Core project.

**Comment by Thaval** [comment]
Maybe an easy way to solve this issue is by let the developer pass in the SDK path in code? I got the feeling Roslyn is looking for the SDK in the bin/Debug folder. Now I'm copying all expected/missing file to the Debug folder. I hope I will remember not to clean the solution.

**Comment by jasonmalinowski** [comment]
Closing out older bugs here: I'm guessing this was due to either MSBuildLocator not being used (the sample code doesn't show it) or a .NET Framework app was being used to analyzer a .NET Core project or vice versa. Neither of those are now problems with the latest 4.9 packages so I'll assume this is fixed with those.
