### ISSUE TITLE
Object initializer block for `with` statement on record is not indented correctly in an expression-bodied method

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47438]
**Version Used**: 

Visual Studio 16.8.0 Preview 2.1
.NET SDK 5.0.100-preview.8.20417.9
Compiler version: '3.8.0-2.20418.7 (0276b9b7)'. Language version: 9.0.

**Steps to Reproduce**:

1. Write an expression-bodied member that uses `with` on a record type:

```csharp
public static class Test
{
    public static MyRecord WithNameSuffix(this MyRecord record, string nameSuffix)
        => record with
        {
            Name = record.Name + nameSuffix
        };
}
```

2. Let the document auto-format or you manually invoke it by running Code Cleanup or with Edit > Advanced > Format Document

**Expected Behavior**:

The indentation remains the same as the code snippet is written above.

**Actual Behavior**:

The initializer block is indented one less than it should be:

![image](https://user-images.githubusercontent.com/278957/92180470-b613f180-ee0c-11ea-8b1e-cd84bfad5268.png)

Note that it works as expected for normal block-bodied methods. Also demonstrated is that is works as expected with a switch expression.

This might be related to #47442, but I'm filing it separately since they're two different language features.

**Comment by CyrusNajmabadi** [comment]
@jcouv I would consider this necessary for 16.8

**Comment by PathogenDavid** [comment]
Thanks for fixing this, @jcouv !
