### ISSUE TITLE
StackOverflowException on self reference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47435]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1096900/stackoverflowexception-on-self-reference.html)._

---
I made a silly error and was surprised that the compiler didn't catch it.  I self-referenced a class and it crashed with a StackOverflowException.  It was actually kinda hard to find because the class doesn't get instantiated until you're deep in my system.

```
public class ClassA : IClassA
{
    public ClassA(IClassA naughty)
    {
    }
}
```

In the constructor I had a request for the same class's interface.  So, when DI started it created an endless instantiation loop.  This is a request to have the build engine be a better programmer than I am.
Thanks,
Joel

---
#### Feedback Bot on 7/1/2020, 01:02 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by PathogenDavid** [comment]
This isn't something that's a problem from a language perspective, it's a problem with whatever dependency injection framework Joel is using.

**Comment by RikkiGibson** [comment]
It feels like this would have to be solved by an analyzer that ships alongside the dependency injection framework in use.

**Comment by CyrusNajmabadi** [comment]
Closing out as this isn't part of roslyn.
