### ISSUE TITLE
Need new Editor Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47434]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/965027/need-new-editor-error.html)._

---
In C#, the compiler allows and builds :        
       
```
public string Override() {  return Name + " : " + StartTime; }
```
in a object that has a Name string property and StartTime datetime property.
Here is what someone on my team should have coded:

```
public override string ToString() { return Name + " : " + StartTime;  }

```

Can you give an error at edit time and prevent compiling?

---
#### Feedback Bot on 3/26/2020, 07:30 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by PathogenDavid** [comment]
There's nothing illegal about having a method named `Override`. The compiler can't guess that the developer actually meant to override `ToString`.

**Comment by CyrusNajmabadi** [comment]
> Can you give an error at edit time and prevent compiling?

No.  That code is totally legal, and there's nothing wrong with calling a method 'Override'.  I can't see anything even undesirable or wrong about it.  I'm not sure what rule we could even have that woudl flag this sort of case.
