### ISSUE TITLE
Intellisense does not work within a with initializer block when the record is a generic type

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47430]
**Version Used**:

Visual Studio 16.8.0 Preview 2.1
.NET SDK 5.0.100-preview.8.20417.9
Compiler version: '3.8.0-2.20418.7 (0276b9b7)'. Language version: 9.0.

**Steps to Reproduce**:

With the following code with the cursor at `$$`, invoke Intellisense:

```csharp
public abstract record MyRecord
{
    public string Name { get; init; }
}

public static class Test
{
    public static TRecord WithNameSuffix<TRecord>(this TRecord record, string nameSuffix)
        where TRecord : MyRecord
        => record with
        {
            $$
        };
}
```

**Expected Behavior**:

Intellisense suggests the `Name` property.

**Actual Behavior**:

Intellisense gets confused and gives generic results:

![image](https://user-images.githubusercontent.com/278957/92179342-1e150880-ee0a-11ea-98e1-b30771c8dae2.png)

**Comment by PathogenDavid** [comment]
When the record is not a generic type, it works fine:

![image](https://user-images.githubusercontent.com/278957/92179558-849a2680-ee0a-11ea-9319-23e16d7db83e.png)

(`AnotherProperty` only exists so that Intellisense shows the dropdown. Without it, Intellisense inserts `Name` since it's the only candidate.)

**Comment by CyrusNajmabadi** [comment]
I don't repro this in preview 4:

![image](https://user-images.githubusercontent.com/4564579/93136303-87a9d800-f690-11ea-9b4a-a99a98c905f0.png)

Will add a test to ensure this behavior doesn't regress.

**Comment by PathogenDavid** [comment]
Can confirm with preview 3, thanks Cyrus!
