### ISSUE TITLE
Allow Signature Help API documentation's URL to be clickable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47437]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/883579/allow-api-documentations-url-to-be-clickable.html)._

---
<p>An image would explain it better here:</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/113587-read.png"> Image:113587-read.png</a><br>I would like to be able to click on that link on the function's documentation.</p>

---
#### Feedback Bot on 1/14/2020, 00:24 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This is a request for _Signature Help_ to support hyperlink navigation for `<see href>` and `<a href>`, the same way that _Quick Info_ already does.

**Comment by CyrusNajmabadi** [comment]
@sharwell do we own that UI, or is it platform?  We can redirect if it's the latter.
