### ISSUE TITLE
Unobtrusive Inline Parameter Name Hints (like Rider)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47444]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1016703/unobtrusive-inline-parameter-name-hints-like-rider.html)._

---
<p>Would be great to have unobtrusive inline parameter name hints shown in VS as an alternative to C# named parameters (which are too obtrusive and create clutter). Would be great if these could be turned on for all function calls apart from single parameter function calls (where parameter name/purpose is usually implicit from function name). This would actually be better than Rider where inline parameter name hints are only supported for certain parameter types. NB: I am not requesting any source code changes, just hints that are inline (see <a href="https://twitter.com/resharper/status/1067419330965635072">https://twitter.com/resharper/status/1067419330965635072</a>).</p>

---
#### Feedback Bot on 5/6/2020, 05:04 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by PathogenDavid** [comment]
This was recently added and can be activating in Visual Studio 2019 preview by going to Tools > Options > Text Editor > C# > Advanced > Editor Help and enabling "Display inline parameter name hints (experimental)":

![image](https://user-images.githubusercontent.com/278957/92181868-e4470080-ee0f-11ea-909e-be419ef640e7.png)

**Comment by CyrusNajmabadi** [comment]
Feature is now available
