### ISSUE TITLE
Go to Implementation should show containing type for nested types

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#47447]
**Version Used**: 
Version 16.8.0 Preview 3.0 [30427.284.main]

**Steps to Reproduce**:

Invoke "Go To Implementation" on `NestedType` and `M`.

```C#
abstract class C
{
    public abstract class NestedBase { }

    public abstract void M();
}

class D : C
{
    public class Nested : NestedBase { }

    public override void M() { }
}

class E : C
{
    public class Nested : NestedBase { }

    public override void M() { }
}
```

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/92187579-03915e00-ee0f-11ea-9057-81f75ef11086.png)

![image](https://user-images.githubusercontent.com/41759/92187585-08eea880-ee0f-11ea-83ff-0e0fb419d1c0.png)

**Expected Behavior**:

In both cases the containing type should be part of the displayed name. It's missing from nested types.

**Comment by CyrusNajmabadi** [comment]
Interesting idea.  I think we currently defer to SymbolDisplay on this.  So we'd need some way for it to know to include this information here when spitting out the declaration text for a symbol (i.e. how it looks in decl for, not in reference form).
