### ISSUE TITLE
Mark `public` modifier on interface methods as unnecessary

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#47448]
**Version Used**: 
Version 16.8.0 Preview 3.0 [30427.284.main]

**Steps to Reproduce**:

```C#
interface I
{
    public void F();
}
```

**Expected Behavior**:

`public` is marked as unnecessary.

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
we acutally have a setting for this: dotnet_style_require_accessibility_modifiers:for_non_interface_members.

We created the setting with the knowledge that DIM was coming, but i don't think it was ever hooked up to work.  We should df impl it.  If the value is not set to 'always' we should def also fade out.
