### ISSUE TITLE
Object initializer block for target-typed new is not indented correctly in an expression-bodied method

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47442]
**Version Used**: 

Visual Studio 16.8.0 Preview 2.1
.NET SDK 5.0.100-preview.8.20417.9
Compiler version: '3.8.0-2.20418.7 (0276b9b7)'. Language version: 9.0.

**Steps to Reproduce**:

1. Write an expression-bodied member that uses target-typed new and an object initializer:

```csharp
public class Person
{
    public string Name { get; set; }

    public static Person Create(string name)
        => new()
        {
            Name = name
        };
}
```

2. Let the document auto-format or you manually invoke it by running Code Cleanup or with Edit > Advanced > Format Document

**Expected Behavior**:

The indentation remains the same as the code snippet is written above.

**Actual Behavior**:

The initializer block is indented one less than it should be:

![image](https://user-images.githubusercontent.com/278957/92180891-b06adb80-ee0d-11ea-89d2-e52293076c60.png)

Note that it works as expected for normal block-bodied methods and for expression-bodied methods using traditional new syntax.

This might be related to #47438, but I'm filing it separately since they're two different language features.

**Comment by CyrusNajmabadi** [comment]
@jcouv

**Comment by jcouv** [comment]
This should be fixed via https://github.com/dotnet/roslyn/pull/47383 (thanks @alrz)

**Comment by jcouv** [comment]
Hum, I misread. This may not be fixed by that PR. Keeping the issue open.

**Comment by PathogenDavid** [comment]
If it does, I don't think it's doing so intentionally. Definitely glad to see those two issues fixed though!

**Comment by PathogenDavid** [comment]
Thanks @alrz!
