### ISSUE TITLE
Convert to Full Property with option for Backing Variable or MyBase

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/899217/convert-to-full-property-with-option-for-backing-v.html)._

---
Visual Basic 2019
When converting to Full Property give the user a choice of using the MyBase property or a separate Backing Variable.

```
Public Property Font as Font
```
Convert to

```
Public Property Font as Font
    Get
        Return MyBase.Font
    End Get
    Set
        MyBase.Font = Value
    End Set
End Property
```
vs

```
Private _Font as Font

Public Property Font as Font
    Get
        Return _Font
    End Get
    Set
        _Font = Value
    End Set
End Property
```

---
### Original Comments
(no comments)

**Comment by CyrusNajmabadi** [comment]
This seems like a very rare case, and likely not something we need to update this feature for.

**Comment by sharwell** [comment]
I don't understand the difference here. Are the semantics between these two forms identical? If not, which of the proposed output forms has the same semantics as the original code?
