### ISSUE TITLE
Generic null propagation 

### ISSUE THREAD

**Issue by rwdd** [dotnet/roslyn#4747]
It would be nice to have a generic version of the null propagation operator.
Actually we will write something like <code>(variableOfTypeA as TypeB)?.PropertyOfTypeB</code>
What about writeing <code>variableOfTypeA&lt;TypeB&gt;?.PropertyOfTypeB</code>?

**Comment by tpetrina** [comment]
You can always use extension method .As<Type>() to achieve the same chaining.

**Comment by dsaf** [comment]
> ```csharp
variableOfTypeA<TypeB>

It will always be ambiguous with generic types. Also the use case is something that should be happening very rarely.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
