### ISSUE TITLE
ArgumentException when manually invoking tests for specific DLL

### ISSUE THREAD

**Issue by Eyas** [dotnet/roslyn#4748]
I followed the instructions on the contribution guide in building tests:

    msbuild /v:m /m BuildAndTest.proj /p:PublicBuild=true /p:DeployExtension=false

And at some point I also decide re-build a more specific project

    msbuild /v:m /m src\EditorFeatures\CSharpTest\CSharpEditorServicesTest.csproj /p:PublicBuild=true /p:DeployExtension=false

(which actually ended up deploying the rest of the DLLs)

And invoked xunit directly on the DLL I am interested in testing:

    packages\xunit.runners.2.0.0-alpha-build2576\tools\xunit.console.x86.exe Binaries\Debug\Roslyn.Services.Editor.CSharp.UnitTests.dll -noshadow

```
xUnit.net console test runner (32-bit .NET 4.0.30319.42000)
Copyright (C) 2014 Outercurve Foundation.

Starting: Roslyn.Services.Editor.CSharp.UnitTests.dll
.... lots of skips ....

   System.ArgumentException [FATAL]
      Ambiguous method named TestEquivalenceKey in type Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateMethod.GenerateMethodTests+GenerateConversionTest
      Stack Trace:
            at Xunit.Sdk.Executor.RunTests..ctor(Executor executor, String _type, List`1 _methods, Object _handler)
Finished: Roslyn.Services.Editor.CSharp.UnitTests.dll

=== TEST EXECUTION SUMMARY ===
   Roslyn.Services.Editor.CSharp.UnitTests.dll  Total: 11580, Failed: 0, Skipped: 43
```

The `ArgumentException` is not being reported in the test summary. Its also unclear if this error always happens but is failed to be reported in the `BuildAndTest` target, or if it only happens when targeting a specific DLL.

**Comment by davkean** [comment]
Thanks, this was resolved in https://github.com/dotnet/roslyn/pull/5441
