### ISSUE TITLE
Incorrect diff when fix causes conflicts / warning annotations

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#475]
Ported from TFS WorkItem: **1047032**

---

**Repro Steps:**

Inline local ii below -

&nbsp;
<FONT size=2 face=Consolas><FONT size=2 face=Consolas>

</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>static</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>void</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> Main(</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>string</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>[] args)

{

</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>int</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> ii = 0;

foo(</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>ref</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> ii);

</FONT></FONT><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas>Console</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>.Write(ii);

}

</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>private</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>static</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>void</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> foo(</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>ref</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>int</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> ii)

{

</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>throw</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>new</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas><FONT color=#2b91af size=2 face=Consolas>NotImplementedException</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>();

}
</FONT></FONT>

&nbsp;

<IMG src="http://vstfdevdiv:8080/DevDiv2/WorkItemTracking/v1.0/AttachFileHandler.ashx?FileNameGUID=88bc6945-ec5a-4a6d-b635-1128d3e8443a&amp;FileName=tmp16ED.png" width=633><BR><BR>

&nbsp;

Note that the above preview has a bug. The line "int ii = 0" is being shown as added even though it is unchanged.

&nbsp;

We will encounter this bug in most cases where there is a conflict. Unfortunately, the fix for this is not easy.

&nbsp;

The problem here is as follows -

We select a set of spans to project in the left and right buffer - the selected spans include the changed lines plus some surrounding context (1 line near the change). In this case we would select the lines "Console.Write(ii);" in the left buffer and "Console.Write(0)" in the right buffer as the changed lines.

&nbsp;

Because this change involves a conflict, we also include the line "foo(ref ii);" as a conflicting line in the right buffer (we can&nbsp;do this because we have already annotated the conflicting node i.e. the box-ed ii above&nbsp;in the new syntax tree - so we just find the line containing the conflict and include it as a changed line). When we do this the line int ii = 0 which is one line above this gets included in the right buffer as surrounding context.

&nbsp;

However, we can't include the same line in the left buffer because corresponding syntax tree has no conflict annotations and we currently don't have a way to correlate the node that has a conflict with the corresponding node in the&nbsp;original (left tree). This means that the line int ii = 0 only gets included in the right buffer and it gets highlighted as an added line.

---

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/152574090-81a7994c-22dc-4c2f-b9cd-5c23a74524d6.png)
