### ISSUE TITLE
IDE1006 thinks positional parameters on records are parameters and properties

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#47508]
When defining a record with positional parameters, IDE1006 will tell you to format names as properties, and then tell you to format them back to parameters.

```
record Foo(int MyInt);
```

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/754264/92356820-1915c900-f12a-11ea-8811-d0549a8b1ce5.png)
and then
![image](https://user-images.githubusercontent.com/754264/92356857-26cb4e80-f12a-11ea-9474-96f558526530.png)

**Expected Behavior**:
My proposal is that IDE1006 simply ignores parameters of record declarations as their usage matches property semantics.

**Comment by powercode** [comment]
I am still seeing this on vs 16.10.0 preview 1.
```xml 
    <TargetFramework>net5.0</TargetFramework>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>preview</AnalysisLevel>
```

**Comment by davidwengier** [comment]
@powercode Could you include a screenshot or sample code for exactly where you are seeing the diagnostic? Are you referencing the analyzers directly via Nuget packages or anything?
