### ISSUE TITLE
Green build shows as "had test failures"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47505]
See https://github.com/dotnet/roslyn/pull/47489/commits

The commit with message "Add WRN_EqualityWithNaN_Title"

![image](https://user-images.githubusercontent.com/31348972/92336484-82052e80-f0a1-11ea-9428-44c07216e70c.png)

How can that happen??

---

https://github.com/dotnet/roslyn/runs/1078127022

![image](https://user-images.githubusercontent.com/31348972/92336500-99dcb280-f0a1-11ea-97e7-b11d8bde010c.png)

The failing test is: TestCutDismissesCompletion

---

https://dev.azure.com/dnceng/public/_build/results?buildId=803639&view=ms.vss-test-web.build-test-results-tab

![image](https://user-images.githubusercontent.com/31348972/92336511-cbee1480-f0a1-11ea-934b-37511facdcc6.png)

---

**Comment by sharwell** [comment]
Someone (likely me) clicked **Rerun failed jobs**, and the test passed on retry.

**Comment by Youssef1313** [comment]
@sharwell Thanks for the extremely fast answer!
I wasn't aware that rerunning failed jobs keep the failures visible.
