### ISSUE TITLE
Remove the three unnecessary using statements from the c# new class template

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/773358/remove-the-three-unnecessary-using-statements-from.html)._

---
<p>When creating a new c# class this is what happens by default:</p><p>- Ctrl+Shift+A - to create a new class<br>- Roslyn &amp; Intellisense kick in, automagically parse my new class and pop up a light bulb telling me to remove the three unused using statements.</p> <p>- I hit Ctrl+R, G to remove them.</p> <p>- I go to the default new c# class template and remove the using statements to stop this happening again.</p> <p><br></p><p>Could you consider tweaking the c# new class template so it doesn't include three unnecessary using statements that are just going to trigger Visual Studio intellisense wizardry anyway?</p>

---
#### Jane Wu [MSFT] on 10/11/2019, 07:59 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by mikadumont** [comment]
We should consider removing the unused usings in the default C# class template now that completion for unimported types is in.

**Comment by JoeRobich** [comment]
In this week's design meeting, it was decided that this behavior is by design and that unused using directives can be removed with codecleanup at the users discretion.

**Comment by mpawelski** [comment]
@JoeRobich 
I think this should be reconsidered.
The "new class" template should not include default usings when `<ImplicitUsings>enable</ImplicitUsings>` is set on project level (which is the default in "new project" template) because this usings are available anyway in every file!
