### ISSUE TITLE
cref output in the public API reference isn't expected

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47504]
https://github.com/dotnet/roslyn/blob/045d179400db88a2b3431b80fb5e84b76a59cad8/src/Compilers/Core/Portable/SpecialType.cs#L117-L120

Note: the behavior is correct here. But probably isn't what was intended to appear. So, this is a request to update the documentation rather than saying that doc comment output is wrong.

`cref="float"` was probably intended to appear as "float". But it appears as System.Single, which kind of useless as it's just the same member name. I know it's very clear that float is the same as System.Single. But I believe the original author of these comment was intending this to appear as "float".

**Comment by sharwell** [comment]
I lean towards keeping the current form. It's not the _text_ that is beneficial, but rather the hyperlink it produces to [`System.Single`](https://docs.microsoft.com/en-us/dotnet/api/system.single).

**Comment by Youssef1313** [comment]
Why not make it `<see langword="float">`? It seems (a little bit) more informative IMO.

**Comment by sharwell** [comment]
`<see langword>` will highlight as a keyword, but not be hyperlinked to the actual type. The current reference is more accurate since this enum member refers to a specific type regardless of the manner in which a language refers to that type.

**Comment by CyrusNajmabadi** [comment]
> But it appears as System.Single, which kind of useless as it's just the same member name

I don't think that's useless :-).  It's what I would expect.
