### ISSUE TITLE
Source generators and nullable reference types, how to combine?

### ISSUE THREAD

**Issue by lsoft** [dotnet/roslyn#47512]
At the moment, source generators must have the following target:

```
    <TargetFramework>netstandard2.0</TargetFramework>
```
This target makes nullable reference types infeasible. Targets `netstandard2.1` or `net5` makes the generator broken:

```
CSC : warning CS8032: An instance of analyzer ... cannot be created ... Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```
(`Version` and `PublicKeyToken` are different with `net5`)

So, is there a way to use nullable reference types in source generators? 

(Sorry if I place this issue at the incorrect repository)

Thank you!

**Comment by PathogenDavid** [comment]
It's not a supported scenario, but I'd probably use [this workaround](https://www.meziantou.net/how-to-use-nullable-reference-types-in-dotnet-standard-2-0-and-dotnet-.htm) from @meziantou

**Comment by lsoft** [comment]
This is a viable option prior to the release of net5. Thank you @PathogenDavid!


But I would like to know if this issue will somehow  be fixed in the release? There is not much time left until net5 release and I could do without the workaround if the issue goes away. Otherwise I have to apply the workaround. Very low information about source generators and its roadmap are available (of course because of its preview state).

Sorry if I rush the things and thanks again!

**Comment by sharwell** [comment]
> But I would like to know if this issue will somehow be fixed in the release? 

There are no plans at this time to officially support source generators written against any target other than netstandard2.0.
