### ISSUE TITLE
IDE0066 produces (arguably) less readable code for enums when changing to switch expression using or patterns

### ISSUE THREAD

**Issue by alexrp** [dotnet/roslyn#47521]
**Version Used**: VS Code (`ms-dotnettools.csharp` 1.23.2, `omnisharp` 1.37.2-beta.2) + .NET 5 Preview 8

**Steps to Reproduce**:

```csharp
enum E
{
    A,
    B,
    C,
    D,
    E,
    F,
}

class C
{
    static E Foo(E e)
    {
        switch (e)
        {
            case E.A:
            case E.B:
            case E.C:
            case E.D:
                return E.E;
            default:
                return E.F;
        }
    }
}
```

`IDE0066` will be suggested on the `switch` statement.

**Actual Behavior**:

```csharp
    static E Foo(E e)
    {
        return e switch
        {
            E.A or E.B or E.C or E.D => E.E,
            _ => E.F,
        };
    }
```

You can see how this quickly gets out of hand for `switch` statements that are handling 30+ values in the non-`default` arm and where the names are not contrived. For some perspective, one example of this suggestion triggering in real code:

```csharp
                public override bool CanParse(SyntaxToken token)
                {
                    switch (token.Kind)
                    {
                        case SyntaxTokenKind.MultiplicativeOperator:
                        case SyntaxTokenKind.AdditiveOperator:
                        case SyntaxTokenKind.ShiftOperator:
                        case SyntaxTokenKind.BitwiseOperator:
                        case SyntaxTokenKind.Hash:
                        case SyntaxTokenKind.OpenParen:
                        case SyntaxTokenKind.OpenBracket:
                        case SyntaxTokenKind.OpenBrace:
                        case SyntaxTokenKind.AssertKeyword:
                        case SyntaxTokenKind.BreakKeyword:
                        case SyntaxTokenKind.CondKeyword:
                        case SyntaxTokenKind.ExcKeyword:
                        case SyntaxTokenKind.FnKeyword:
                        case SyntaxTokenKind.ForKeyword:
                        case SyntaxTokenKind.FreezeKeyword:
                        case SyntaxTokenKind.IfKeyword:
                        case SyntaxTokenKind.LetKeyword:
                        case SyntaxTokenKind.LoopKeyword:
                        case SyntaxTokenKind.MatchKeyword:
                        case SyntaxTokenKind.MutKeyword:
                        case SyntaxTokenKind.NotKeyword:
                        case SyntaxTokenKind.RaiseKeyword:
                        case SyntaxTokenKind.RecKeyword:
                        case SyntaxTokenKind.RecvKeyword:
                        case SyntaxTokenKind.ReturnKeyword:
                        case SyntaxTokenKind.TryKeyword:
                        case SyntaxTokenKind.UseKeyword:
                        case SyntaxTokenKind.WhileKeyword:
                        case SyntaxTokenKind.ModuleIdentifier:
                        case SyntaxTokenKind.ValueIdentifier:
                        case SyntaxTokenKind.NilLiteral:
                        case SyntaxTokenKind.BooleanLiteral:
                        case SyntaxTokenKind.AtomLiteral:
                        case SyntaxTokenKind.IntegerLiteral:
                        case SyntaxTokenKind.RealLiteral:
                        case SyntaxTokenKind.StringLiteral:
                            return true;
                        default:
                            return false;
                    }
                }
```

The readability of this code is certainly not improved by applying the transformation above.

(I have several other similar cases in this same code base.)

**Expected Behavior**:

There are a lot of factors to consider here and I see multiple possible solutions, but I have no idea which is more practical. All I can say for sure is that in all of the cases where I've run into this suggestion, the readability of the code is worsened. Obviously the general suggestion to use `switch` expressions is great, but when it involves `enum`s in patterns like this, the suggestion is not helpful.

**Comment by Youssef1313** [comment]
My proposal would be to add an editorconfig option for this rule to set the max number of allowed cases, and the suggestion is just omitted if the number of cases exceeds the configured number.

The default value for this option could probably be zero which means no limit (i.e. the current behavior).

**Comment by CyrusNajmabadi** [comment]
Tagging @alrz   I think this could be addressed just with a formatting change. I don't think we need any sort of editorconfig setting here.

**Comment by mavasani** [comment]
# Design Meeting Notes

- IDE suggestion to use patterns for a large switch statement/expression makes the code unreadable
- Do we need an editorconfig option? Likely not.
- This might just be a bug fix where we preserve formatting and have the `or` parts on new line if original code had the cases on different lines
- We can consider applying a wrapping heuristic if we want to limit number of characters on a single line before we wrap to next line - 120 chars is our chosen default limit for similar heuristic at other places

**Conclusion:** Fix the formatting, and considering implementing a wrapping heuristic based on a chosen threshold.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
