### ISSUE TITLE
Object initializer completion should include readonly properties have WinRT projected Add methods

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4754]
Create a C# UWP app.

In App.xaml.cs type:

``` C#
            var stackPanel = new StackPanel()
            {
                Children =
                {
                    new TextBlock { Text = "Hi" }
                }
            };
```

The `Children` property won't show in completion because the IDE doesn't know about it's add method, but the compiler accepts it.

**Comment by rchande** [comment]
Please verify, @Pilchie.

**Comment by Pilchie** [comment]
Back to you, since it appears that #4976 wasn't merged.

**Comment by rchande** [comment]
Okay, @Pilchie let's try that again.
