### ISSUE TITLE
Extension methods with EditorBrowsable(Never) defined in a referenced assembly show up in VS intellisense

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#47551]
**Version Used**: VS 16.7.3

**Steps to Reproduce**:

1. Create a library project with a public extension method. Put `[EditorBrowsable(EditorBrowsableState.Never)]` on it.
2. Build the project.
3. Create a second library project and reference the `bin/Debug` assembly that was created by building the first project.
4. See the never-browsable extension method showing up in intellisense for the second library project where it offers to autocomplete extension methods that are in an unimported namespace.

**Expected Behavior**: The extension methods should stop polluting intellisense. They can't be removed without causing binary-breaking changes and they should remain extension methods so that code that used them gets the obsoletion message rather than a "method does not exist" compiler error.

**Actual Behavior**: The extension methods did not stop polluting intellisense.

**Comment by Youssef1313** [comment]
Related existing test:

https://github.com/dotnet/roslyn/blob/894972542b1756efe24811c08420f98ad502ea93/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs#L4282-L4316

**Comment by jnm2** [comment]
Thanks, that was quite fast! Will the fixed version be 16.8.x?

**Comment by genlu** [comment]
>Thanks, that was quite fast! Will the fixed version be 16.8.x?

Yes.
