### ISSUE TITLE
SyntaxFactory.TypeCref(type) delves into comments and includes comment

### ISSUE THREAD

**Issue by RalfKoban** [dotnet/roslyn#47550]
**Version Used**: 3.6

**Steps to Reproduce**:

1. Parse following snippet:
```
internal interface IFactory
{
    /// <summary>
    /// Blah <see cref=""Xyz""/> blah.
    /// </summary>
    /// <returns></returns>
    IXyz Create();
}
```

2. Let you give the `MethodDeclarationSyntax` for the given method, then access its `ReturnType` property to get the `TypeSyntax` for.
3. Create a `TypeCrefSyntax` via `SyntaxFactory.TypeCref(type)` (where `type` is the returned `TypeSyntax` from above).
4. Create a `XmlCrefAttributeSyntax`, as in following snippet:
```
var attribute = SyntaxFactory.XmlCrefAttribute(syntax);
var result = attribute.ToString();
``` 
5. Inspect `result`.

**Expected Behavior**:
`result` should be `cref="IXyz"`

**Actual Behavior**:
`result` is `cref="    /// <summary>
    /// Blah <see cref="Xyz"/> blah.
    /// </summary>
    /// <returns></returns>
    IXyz"`

**Comment by sharwell** [comment]
This is the expected behavior of the APIs, since the `TypeSyntax` passed to `TypeCref` in step (3) explicitly was a syntax node containing additional trivia. The trivia will need to be removed from the `TypeSyntax` before calling `TypeCref`.

**Comment by RalfKoban** [comment]
OK, thanks for the clarification.
