### ISSUE TITLE
Find All References returns sometimes returns zero results

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#47577]
**Version Used**: 
Version 16.8.0 Preview 4.0 [30507.17.main]

I sometimes get into a state maybe a few times a day where Find All References returns zero results multiple times in a row. If I search a minute later than it returns results. Its very frustrating, as I need to fall back to CodeLens to get the results.

Trace: [internalshare]\public\davkean\Roslyn\47577.zip.

**Comment by sharwell** [comment]
> [internalshare]\\public\\davkean\\Roslyn\\47577.zip

Are you able to file a feedback ticket for this attachment?

**Comment by CyrusNajmabadi** [comment]
Haven't gotten more feedback on this.  My guess is it relates to particular crashes which we've fixed.   Closing out for now.
