### ISSUE TITLE
Add an error or warning for empty top level statements in c# 9

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47599]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1170352/add-an-error-or-warning-for-empty-top-level-statem.html)._

---
[regression] [worked-in:16.7.2 with Net 5.0 Preview 7]
Using c# 9 and got bitten by top level statements.  Main was being bypassed because I had a single file, out of many, with a line like:

using System;; 

Note the extra semi-colon.   Compiler was detecting this as a top level statement and ignoring my main() function.  The warning was on Main, so I had to check each file.  An error or warning for empty top level statements would have eased my burden greatly, allowing me to zero in on the offending punctuation.  Thanks!

---
#### Feedback Bot on 9/2/2020, 01:32 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This error was added.
