### ISSUE TITLE
Quick Action to remove namespace prefix

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47595]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1178139/quick-action-to-remove-namespace-prefix.html)._

---
I'd like to propose a new feature.

When you write code to create a new object, and the relevant class isn't in a namespace currently being imported, Visual Studio helpfully suggests adding the fully-qualified class name.

As an example, I'm working with an HttpClient object, and would like to add an Authorization header. I start typing:

```csharp
client. DefaultRequestHeaders.Authorization = new Auth
```

Visual Studio now helpfully offers to auto-complete the statement for me, because it already knows the type of the Authorization property. The result is this:

```csharp
client. DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue
```

That's fine as an intermediary step, and I can now complete my code:

```csharp
client. DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
```

I would, however, like to simplify my code to this:

```csharp
client. DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
```

I can do this by moving my cursor around to delete the namespace prefix, and then use the Quick Action to add the appropriate using directive.

I would like to propose a new Quick Action to remove the namespace prefix, so that I don't have to move my cursor around.

---
#### Dada Huo [MSFT] on 9/9/2020, 03:02 AM: 

<p>Does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use? It would be very helpful if you can provide a screenshot of this issue. Thanks for your help!</p>

#### Mark Seemann on 9/9/2020, 05:04 AM: 

(private comment, text removed)
#### Mark Seemann on 9/9/2020, 05:08 AM: 

<p>I've shared screen shots and further explanations, but despite my selection of <em>Viewable by All</em>, it's marked as <em>private</em>. How can I change that?</p>

#### Dada Huo [MSFT] on 9/9/2020, 08:03 PM: 

<p>Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by genlu** [comment]
Design meeting note:

Add two separate CodeActions, "Fix one" and "Fix all in current doc".

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.

**Comment by ploeh** [comment]
> Closing due to lack of feedback.

Were you awaiting _feedback?_ Which feedback?

**Comment by CyrusNajmabadi** [comment]
Feedback from other users indicating this is something we want to invest in.
