### ISSUE TITLE
Introduce local refactoring shouldn't be suggested for locals

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47600]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1169103/introduce-local-refactoring-shouldnt-be-suggested.html)._

---
This is a very minor annoyance... but the "introduce local" refactoring doesn't make sense for an expression that is just a local variable. I'm currently getting the suggestion to replace

```
bool hasExample = ...;
if(hasExample) ...
```

with

```
bool hasExample = ...;
var hasExample1 = hasExample;
if (hasExample1) ...
```

Maybe I'm wrong, but I'm having trouble seeing how that could ever be useful.

---
#### Feedback Bot on 9/1/2020, 02:00 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
this was actualy explicitly done based on customer requests.  I too found it odd.  However, some people do like to have the local and then invoke this feature to create a fresh one they can operate on distinct from the usage.
