### ISSUE TITLE
Add an option to generate new class with fields

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47605]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1176624/add-an-option-to-generate-new-class-with-fields.html)._

---
For example, I type:

var v = new MyClass
			{
				a = 1,
				b = "b",
			};

and then I invoke Quick Action on MyClass

The Intellisense proposes the only choice to generate a class with auto properties.

internal class MyClass
	{
		public int a { get; set; }
		public string b { get; set; }
	}

It would be good if I had an option to generate a class with fields as well. 

Like this:

internal class MyClass
	{
		public int a;
		public string b;
	}

---
#### Feedback Bot on 9/8/2020, 02:28 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment]
Design meeting notes:

For generate class, check naming style config for both field and non-field members. Generate field if matches field option but not non-field option. Otherwise, generate property.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
