### ISSUE TITLE
Type pattern in switch expression involving generic type with non-keyword type parameters causes syntax error

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47614]
**Version Used**: Compiler version: '3.8.0-4.20460.4 (64f2392e)'. Language version: preview.

**Steps to Reproduce**:

Compile this code: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwCMAsAFBWEDMABCfQCpyxUDeV9PjDhpAAz0AsgAoA9sABWcAMYx6EgJTde6gLwA+JfSgB3TDDkALNep5dKFm4yH1t9AEQBlGAkwA7AOZOk52x4BYgcdJ2C/AMDggB4vGB1HJwBBOSMJTzjPBMjrQN5YqVkFRLDCmXkc/zz8u2IYgEls0gA2UudYpphWrVzaoNJ61lh28MGY4aqo2wB9UOcAVU8Aa08JfU8naZ4AXwBuKh2qIA))

```csharp
using System;

public class Test
{
    public string M(object o)
        => o switch
        {
            string => "String",
            Action => "Action",
            Action<int> => "Aciton<int>",
            Action<object> => "Action<object>",
            Action<Int16> => "Action<Int16>", // <-- Syntax Errors
            Action<Test> => "Action<Test>", // <-- Syntax Errors
            _ => "Unknown"
        };
}
```

**Expected Behavior**: Compiles without errors

**Actual Behavior**: The lines marked have errors associated with them:

```
Line 12: error CS1001: Identifier expected
Line 12: error CS1003: Syntax error, '=>' expected
Line 12: error CS1525: Invalid expression term ','
Line 13: error CS1001: Identifier expected
Line 13: error CS1003: Syntax error, '=>' expected
Line 13: error CS1525: Invalid expression term ','
```

-------------

This does not happen with the equivalent switch statement: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwCMAsAFBWEDMABCfQCpyxUDeV9PjDhpAAz0AsgAoA9sABWcAMYx6EgJTdeXSry30oAd0ww5AC3qTVm7Tw2XLc6HEZCQamzcIB2egCIAyjASYAHYA5l4A3C6u9HZQDgLEzhZR2h7e8eGRrjFxpMQAPEEwAHyJyZapXgCCcgYSgQWBxRlJUdmO+VKyCiWZZRXVtfWd8k0RLVn27XkAko2kAGw9432eVTUwdTNzi81l0ZPxeaywS3ta/eubx6O9lgAmcNgQAK4ANqi3URUAqoEA1oEJLpArsbABfSIQyhQoA))

```csharp
using System;

public class Test
{
    public string M(object o)
    {
        switch (o)
        {
            case string:
                return "String";
            case Action:
                return "Action";
            case Action<int>:
                return "Aciton<int>";
            case Action<object>:
                return "Aciton<object>";
            case Action<Int16>:
                return "Aciton<Int16>";
            case Action<Test>:
                return "Aciton<Test>";
            default:
                return "Unknown";
        }
    }
}
```

**Comment by PathogenDavid** [comment]
I almost forgot to mention, this does not happen with declaration patterns with/without a discard: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwCMAsAFBWEDMABCfQCpyxUDeV9PjDhpAAz0AsgAoA9sABWcAMYx6EgJTde6gLwA+JfSgB3TDDkALNep5dKFm4yH1t9AEQBlGAkwA7AOZOk52x4BYgcdJ2C/AMDggB4vGB1HJwBBOSMJTzjPBMjrQN5YqVkFRLDCmXkc/zz8u2IYgEls0gA2HQB9UOdYpphWrVzaoNJ61lgdCAVMDLHFJNjZgeqh+k6kgFVPAGtPCX1PJyjeAF8AbipjqiA===))

```csharp
using System;

public class Test
{
    public string M(object o)
        => o switch
        {
            string => "String",
            Action => "Action",
            Action<int> => "Aciton<int>",
            Action<object> => "Action<object>",
            Action<Int16> _ => "Action<Int16>",
            Action<Test> actionTest => "Action<Test>",
            _ => "Unknown"
        };
}
```

Although a well-meaning but unhelpful (and somewhat misleadingly labeled) code fix offers to remove the variable declaration:

![image](https://user-images.githubusercontent.com/278957/92846943-3b1f7d80-f3ae-11ea-8728-0caa3102bf87.png)

**Comment by gafter** [comment]
See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/patterns3.md#change-to-7542-grammar-ambiguities for the spec change needed to support this.

**Comment by PathogenDavid** [comment]
Thanks for the fix @gafter, works great!
