### ISSUE TITLE
[C# 9.0] Remove unnecessary cast doesn't know about target typing ? and ??

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#47620]
**Version Used**: 
Version 16.8.0 Preview 4.0 [30509.233.main]

**Steps to Reproduce**:

1. Make sure you are targeting C# 9.0

``` C#
                Func<string, bool>? isEvaluatedItemSpec = true
                    ? evaluation.After.Items.ContainsKey
                    : (Func<string, bool>?)null;
```

**Expected Behavior**:
Remove unnecessary cast

**Actual Behavior**:
Nothing

**Comment by CyrusNajmabadi** [comment]
I don't think the compiler exposes any APIs to let us know what the target-typing type is.  We'd likely need that in order to be able to suggest something here.  Tagging @jcouv

**Comment by jcouv** [comment]
It looks like there is no target-typing in this example (does it break with `var` declaration type?).
If the cast in the ternary is using the same type as the declaration type, then I think it can be removed.

**Comment by svick** [comment]
@jcouv It does require target typing if you want to remove the cast.

Consider this code:

```c#
void M(Dictionary<string, object> items)
{
    Func<string, bool>? isEvaluatedItemSpec = true
        ? items.ContainsKey
        : null;
}
```

[This does not compile on C# 8.0](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMAWAbl1wGIA7AVwBtGBDAI0YkIlvc6rxpCAYVwBvXISnFShALIAKACIwAxsBgB7XlAQAeEvgA0hTWwBWEdQD5CMYBAC2AZwCUk6RJzSfxAKwGGMaEbJqajNYA/HbOAKJgLIz0LA4AJgCSDo4AygAOVoQAvITAUPQQHr6+0fZOzgB0wtrALDC0zgDSEAiVVdIghAzMlN7SAL64Y0A=), but [works fine on C# 9.0](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgEwCMAsAFCEAMABIaQCwDcVVAxAHYCuANnwjA+cOnC5CR7asToBhKgG8qdVQyZ0AsgAoAIpgDGMTAHsJCXAB5GNJHRPAAVnCMA+OpnhgoAShVrlSjVghgBWa1JbOmATEz5XAH4PKABRNAg+Hgh4ABMASS8AZQAHFzoAXjoYBB44fxCQpM84bwA6OTMYCEwuKABpOFx6hrUQOl4BNiC1AF8qGaA=).

**Comment by jcouv** [comment]
@svick Haha, yes, I got that, but that's not what the code __is__ in the proposed scenario.

**Comment by davkean** [comment]
I don't follow?

**Comment by jcouv** [comment]
@davkean In the scenario with the cast removed, target-typing comes into play and the compiler already exposes APIs to reveal that (looking at `.Type` versus `.ConvertedType`). Anyways, it's not the scenario at hand.
In the scenario with the cast present, target-typing doesn't come into play, so I don't understand what API related to target-typing @CyrusNajmabadi is asking for. The knowledge that a target-type exists (but wasn't used) comes from the context (a local declaration with a type), which does not require special help from the compiler. That's why I'm proposing that the analyzer can flag the cast for removing by looking at the type of the cast and the type of the declaration type.

**Comment by CyrusNajmabadi** [comment]
> The knowledge that a target-type exists (but wasn't used) comes from the context (a local declaration with a type), which does not require special help from the compiler

The problem here is knowing if this is a context where a target type can be provided. I.e. the variable case is simple and obvious, but what if we allow this in the future:

`Func<x,y>[] f = new[] { a.ContainsKey, (Func<x,y>)null };`

I want to be and to ask the questions to know what target your is actually being applied to the expression (if it would need to be applied). 

That can get complex quickly, esp given things like switch expressions and whatnot

**Comment by jcouv** [comment]
@CyrusNajmabadi I don't think that the concept, "what target type is actually being applied to the expression", exists unless target-typing actually took place.

Consider `A x1 = b ? x2 : (b ? x3 : x4);` and we'd like to ask what is the "target-type for `x4`" in a case where `x4` did not actually get target-typed.
In this example, would the answer be the type of `x2` or `A`? We don't know without knowing the type of `x4`. If the answer depends on the type of `x4`, this wouldn't help us decide if a cast in `x4` can be removed. Target-typing is a process which I don't think can be summarized with a "target-type" that the expression is subject to...

**Comment by CyrusNajmabadi** [comment]
This is why having an api would be good :-).  It would help define what the actual question is that can be answered. We could then likely use that to drive the feature :-)

**Comment by CyrusNajmabadi** [comment]
Julien and i discussed this and we don't see a good way to really expose thsi type of question from the compiler.  The core issue is that we're effectively askign the compiler to answer how it *would* have gone through a complex process *if* the tree were not the same as it actually is.

we tentatively think though this can be solved on the IDE side.  teh basic idea is this:

when we have this sort of cast (i.e. a cast in a location where target typing could be involved), and we currently do not think it can be removed:

1. make a speculative semantic model with the body/statement containing that cast replaced with one that doesn't contain the cast.
2. ask that speculative model for the TypeInfo for the newly uncasted node.  
3. check the 'ConvertedType' of that node is the same as the original casted type.

If this is all the case, we should be able to remove the cast.  By being speculative this can hopefully also be fast enough to not cause a large hit.

**Comment by CyrusNajmabadi** [comment]
Target typing cases of interest:

```
int i = ...
a ? b : c
x ?? y
expr switch { }
```

**Comment by gafter** [comment]
`??` is not target-typed.

**Comment by CyrusNajmabadi** [comment]
good to know neal!  any other target typing cases we should be aware of?  Thanks!

**Comment by CyrusNajmabadi** [comment]
This works for me now:

![image](https://user-images.githubusercontent.com/4564579/199353344-f51dabf5-c903-4614-824a-848537f9116b.png)
