### ISSUE TITLE
Find References should identify 'new()' generic constraint as a use of parameterless constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1179015/codelense-missing-reference.html)._

---
When i have a class with a public parameterized and parameterless constructor, codelens says it has 0 references for the parameterless constructor. Although the parameterless constructor is used. 

When i remove the parameterless constructor and try to compile, the compiler will say:

must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 

Ofcourse the compiler is right. The method that is called requires a parameterless constuctor, becuase it has a 'new()' requirement.

I'm almost certain that codelens must be able to detect the usage.

Regards,
Jeroen van Driel

---
#### Feedback Bot on 9/10/2020, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to the high complexity cost to get this.
