### ISSUE TITLE
Nullable analysis doesn't handle XOR

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47630]
**Version Used**: 

master

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4DEAdgK4A2tEwtcABHJY8wLABQvAAgCYAjLwEBmFkJYBhXgG9eLZVMn8ALCwCyACn7CADAH4W2TAlhIphk1DgBjAPaUCASiUrFPFT5Y4WOmYWMH5QLDT0LAB6LHZOLqHhdLTu3r7KXunp/oHmsIkRKR5ZnsUlvvoAnDpxzgQAdAAy7ADmMAAWrgDcZSUAvr0qA2nKw31AA=

```csharp
#nullable enable

using System;

public class C
{
    public void M(string? first, string? second)
    {
        if (first is null ^ second is null)
        {
            if (first is null)
            {
                Console.WriteLine(second.Length);
            }
        }
    }
}
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

warning CS8602: Dereference of a possibly null reference.

**Comment by Youssef1313** [comment]
The same happens when using the definition of XOR using `&&` and `||`:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4DEAdgK4A2tEwtcABHJY8wLABQvAAgCYAjLwEBmFkJYBhXgG9eLZVMn8ALCwCyACn7CADAH4W2TAlhIphk1DgBjAPaUCASiUrFPFT5Y4WOjpmFjB+UCw09CwAZNEsdk4uYRGOoZG0riykpB6+vkHmsMmUqRF0tDFxCc4ExeWu7t55LF7Nvv4FIXX0jW0+rX15+gCcOtUuAHQAMuwA5jAAFq4A3Ll9AL5rPptNyjvrQA

```csharp
#nullable enable

using System;

public class C
{
    public void M(string? first, string? second)
    {
        if ((first is null && second is not null) ||
            (first is not null && second is null))
        {
            if (first is null)
            {
                Console.WriteLine(second.Length);
            }
        }
    }
}
```

**Comment by RikkiGibson** [comment]
This is by-design. See https://github.com/dotnet/roslyn/issues/36927#issuecomment-508595947 for more context.
