### ISSUE TITLE
Intellisense too quick to insert `=> throw new NotImplementedException()`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47634]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1180625/intellisense-too-quick-to-insert-throw-new-notimpl.html)._

---
[severity:It bothers me. A fix would be nice]
When overriding an abstract method, Visual Studio 16.8.0 Preview 2.1 is too quick to jump in and insert `=> throw new NotImplementedException()`.

```
public abstract class Base
{
    public abstract void Test();
}

public class Child : Base
{
    public override void Test
}
```

When you type ` (` following `Test`, Intellisense will jump in and turn the line into:

```
public override void Test() => throw new NotImplementedException();
```

You then need to manually remove `=> throw new NotImplementedException()` before continuing to write the rest of the method declaration and body.

Intellisense should not be adding `throw new NotImplementedException` to any methods which I'm currently in the process of writing.

---
#### Feedback Bot on 9/10/2020, 08:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
