### ISSUE TITLE
Code fixes cannot change source encoding alone

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#4767]
## Background

The differencing algorithm currently ignores content changes due to changes in the encoding of a `SourceText` for a document. This is causing a multitude of problem for the implementation of StyleCop Analyzers' rule SA1412 (Store files as UTF-8).

The analyzer and code fix were originally implemented in DotNetAnalyzers/StyleCopAnalyzers#1151. Since Roslyn would not show treat a document as changed if the only change was encoding, we were forced to work around the issue by creating a code fix which _removes_ the original document and _adds_ a new document with the same name but a new encoding. While this "works" to some extent, the user experience is particularly terrible. In addition to the preview appearing as though the document were simply deleted, the following bugs have been filed:
- DotNetAnalyzers/StyleCopAnalyzers#1169: SA1412 code fix does not work properly on linked files
- DotNetAnalyzers/StyleCopAnalyzers#1239: SA1412 code fix does not preserve DependentUpon solution items
## Desired solution

We would like to be able to create a code fix that uses `document.WithText` to transform the document:

``` csharp
internal static async Task<Document> GetTransformedDocumentAsync(Document document, CancellationToken cancellationToken)
{
    SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
    return document.WithText(SourceText.From(text.ToString(), Encoding.UTF8));
}
```

An even better solution would be the addition of a `WithEncoding` method for `SourceText`:

``` csharp
internal static async Task<Document> GetTransformedDocumentAsync(Document document, CancellationToken cancellationToken)
{
    SourceText text = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
    return document.WithText(text.WithEncoding(Encoding.UTF8));
}
```

**Comment by CyrusNajmabadi** [comment]
CLosing out as speculative.  If we want to do this, we should just assign to a milestone and do it.
