### ISSUE TITLE
LSP OnTypeFormatting request doesn't work properly for \n

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#47691]
**Version Used**: 16.8.0 Preview 4.0 [30510.80.main]

**Steps to Reproduce**:

Example, (pipe is request location)
```C#
if (true) {
|}
```
1. Send an LSP onTypeFormatting request to the C# language server for the above scenario. (Trigger character `\n`)

**Expected Behavior**:
Returns edits to make the code look like below,
```C#
if (true)
{
    |
}
```

**Actual Behavior**:
No edits returned

Note: onTypeFormatting works fine for `;` and `}` trigger characters

Tracking issue on Razor: https://github.com/dotnet/aspnetcore/issues/23753

**Comment by ajaybhargavb** [comment]
cc @jinujoseph @dibarbet

**Comment by NTaylorMullen** [comment]
Other newline scenarios include hitting "enter" inside of a comment as mentioned by: https://github.com/dotnet/aspnetcore/issues/26752

**Comment by ajaybhargavb** [comment]
@dibarbet, can this now be closed given that you merged https://github.com/dotnet/roslyn/pull/48468?

**Comment by dibarbet** [comment]
yep closed in #48468
