### ISSUE TITLE
InlineParameterNameHints: add support for record base type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#47696]
Currently, we don't offer parameter name hints on those two in the following example. 

```
        Public Class CSharpInlineParameterNameHintsTests
...
            <WpfFact, Trait(Traits.Feature, Traits.Features.InlineParameterNameHints)>
            Public Async Function TestRecordBaseType() As Task
                Dim input =
                <Workspace>
                    <Project Language="C#" CommonReferences="true">
                        <Document>
record Base(int Alice, int Bob);
record Derived(int Other) : Base({|Alice: 2|}, {|Bob: 2|});
                    </Document>
                    </Project>
                </Workspace>

                Await VerifyParamHints(input)
            End Function
```

This is because `ArgumentSyntaxExtensions.DetermineParameter` does not support `PrimaryConstructorBaseTypeSyntax`.

**Comment by Youssef1313** [comment]
@jcouv Do you want to support ObjectCreationExpressionSyntax and ConstructorInitializerSyntax as well? They doesn't seem to be currently supported.

**Comment by jcouv** [comment]
Yes, I assume we'll want to do all those construction and initialization syntaxes together. I suspect there may already be an issue for tracking support on pre-records syntax.
Tagging @akhera99 @CyrusNajmabadi @mikadumont to confirm plan/desire.
