### ISSUE TITLE
CS1061 CodeFix should suggest to add using for generic extension method when non-generic method with same name present

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#47698]
**Version Used**: 
VS2019 16.8 P3

**Steps to Reproduce**:

1. Add `Microsoft.Extensions.DependencyInjection` nuget package.
2. Create file with code:
```csharp
using System;

public class TestClass
{
    public TestClass(IServiceProvider serviceProvider)
    {
        serviceProvider.$$GetService<TestService>();
    }
}

public class TestService { }
```
3. Invoke bulb menu on $$.

**Expected Behavior**:
`using Microsoft.Extensions.DependencyInjection;` codefix is present.

**Actual Behavior**:
No codefix present.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
