### ISSUE TITLE
Use IThreadingCOntext.DisposalToken in ExternalErrorDiagnosticUpdateSource

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47694]
aside, all these cancellationtoken.none's are unfortuante.  you should be able to use IThreadingCOntext (which you will have, or can easily import), and use .DisposalToken instead.  This has the *awesome* aspect that when the Roslyn pakcage is closed, all this work is canceled.

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/47689#discussion_r488276360_

**Comment by CyrusNajmabadi** [comment]
This type is going away with pull diagnostics.
