### ISSUE TITLE
Analyzer cannot detect callee methods in primary constructors

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#47700]
**Version Used**: 
VS 16.7.3

**Steps to Reproduce**:

1. Write code like:
```csharp
public sealed record R(A a, B b) : S(Method(a, b))
{
    private static C Method(A a, B b) => ...
}

public abstract record S(C c);
```

2. IDE0051 (Private member {0} is unused) raised and the callee (`Method`) is faded out, and suggests we should remove the method. 

**Expected Behavior**:
No suggestions raised.

**Actual Behavior**:
IDE0051 raised.

**Comment by jinujoseph** [comment]
cc @mavasani

**Comment by mavasani** [comment]
Cannot repro this on 16.8 Preview4 dogfood builds:

```csharp
namespace N
{
    sealed record R(A a, B b) : S(Method(a, b))
    {
        // Used and not faded.
        private static C Method(A a, B b) => new C();
    }

    sealed record R2(A a, B b) : S(new C())
    {
        // Unused and faded.
        private static C Method(A a, B b) => new C();
    }

    abstract record S(C c);

    class A { }
    class B { }
    class C { }
}
```

![image](https://user-images.githubusercontent.com/10605811/93278245-f9f5e780-f778-11ea-8bf8-d97bf8fc424f.png)
