### ISSUE TITLE
Records: events should not be allowed in records

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#47703]
Records are container for data. Currently, not only events are allowed. they contribute to value equality which I don't think that would make much sense.

**Comment by jinujoseph** [comment]
cc @jcouv , @CyrusNajmabadi

**Comment by jcouv** [comment]
Tagging @cston @AlekseyTs for thoughts.

**Comment by AlekseyTs** [comment]
One can always avoid declaring events in records, none are added automatically. We should get confirmation from LDM if we want to make changes around events.

**Comment by jcouv** [comment]
Started thread

**Comment by alrz** [comment]
>One can always avoid declaring events in records, none are added automatically

If that's the argument, *at least* we should exclude those from value equality. Personally I think they should be outright illegal. If you need an event beside your data, just define separate types. That's not a "record" responsibility to enable all that.

**Comment by jcouv** [comment]
From quick discussion with Mads, this is similar to struct equality. We'll leave as-is. There are scenarios where it is useful to allow, despite many questionable scenarios as well.

**Comment by alrz** [comment]
@jcouv

> There are scenarios where it is useful to allow

Sure but I'm thinking actually checking equality on those events is a little bit annoying - we probably need to redefine Equals to exclude events every time.
