### ISSUE TITLE
IDE needs way to tell if INAmedTypeSymbol is a record.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#47713]
We have lots of features that want to know if something is a record.  For example, 'Metadata as source' wants to know, as does classification.  Currently, the only approach that is available is to clone this helper:

https://github.com/dotnet/roslyn/blob/5d719960bfcd3605462590e2fa9a8708f69f150c/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs#L712-L767

Copying something this complex is pretty brittle and unpleasant for such a basic question.  We would like this to actually be codified in some way (and avialable for source/pe symbols).  We're ok with *not* introducing a new TypeKind.  However, it would be nice to have something like a `bool IsRecord` on ITypeSymbol (or INAmedTypeSymbol).

**Comment by jinujoseph** [comment]
cc @jcouv

**Comment by jcouv** [comment]
Was this solved with a `.IsRecord` API recently?

**Comment by CyrusNajmabadi** [comment]
Yup.  closing out.  Thanks!
