### ISSUE TITLE
How to block terminate application

### ISSUE THREAD

**Issue by dimkadv2** [dotnet/roslyn#47730]
Hi!

I need to block terminate app (windows service),

i try using next code:

```c#        
public void Configure(IApplicationBuilder app, IHostApplicationLifetime appLifetime)
{
    appLifetime.ApplicationStopping.Register(async () => await OnStopping(app));
    .....
}


private async Task OnStopping(IApplicationBuilder app)
{
    var processingService = app.ApplicationServices.GetRequiredService<ProcessingEventBus>();
    while (processingService.ExistTasks())
    {
           await Task.Delay(TimeSpan.FromSeconds(5));
    }
}
```

But all object inherited from IDisposable called Dispose method.

How do I defer standard completion until the method processingService.ExistTasks() return false?

Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is not a roslyn question.  See https://github.com/dotnet/roslyn#questions to get some links to other communities where you could try to ask this question.
