### ISSUE TITLE
Target-typed Regex initialization doesn't syntax highlight the regular expression

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#47743]
**Version Used**: 
Version 16.8.0 Preview 3.0

**Steps to Reproduce**:

        public static readonly Regex ResistanceImageRegex = new(@"^\$\((.*)ResistanceImage\)$");

**Expected Behavior**:

I would expect it to be syntax highlighted like it is when I use the explicit constructor, instead of relying on target typed construction:

![image](https://user-images.githubusercontent.com/541998/93357792-b5b52680-f80e-11ea-94ac-ec8336c5862c.png)

**Actual Behavior**:

As seen above, target-typing doesn't syntax highlight the regular expression.

**Comment by CyrusNajmabadi** [comment]
Yup.  Seems reasonable.  Thanks for the report :)
