### ISSUE TITLE
Warn when CodeStyle nuget package is older than what comes with the SDK

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#47753]
Per the commeent here https://github.com/dotnet/roslyn/issues/46516#issuecomment-692942031

If the user installs the codeStyle nuget packages and they are older what comes from the SDK we will issue a warning to uninstall them. Otherwise we will use the nuget packages over the SDK packages.

**Comment by mavasani** [comment]
Thanks @jmarolf

**Comment by mavasani** [comment]
@jmarolf A bigger feedback that is coming frequently is users installing newer CodeStyle package and then attempting to work in older version of VS (say different members of team are on prior VS), and hitting analyzer load exceptions due to lower version of MS.CA.dll on earlier VS. I am wondering if we can detect this case and report a user friendly warning.

**Comment by jmarolf** [comment]
@chsienki and @RikkiGibson  how difficult do you both think it would be to add a better error message here? I assume this would be an additional case here: https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs where we say: `The Compiler being used is not new enough to load this analyzer, the compiler being used is version X and it must be at least Y` .

I have been hearing this feedback from other analyzer/generator authors. I recently helped implement this shameful hack: https://github.com/CommunityToolkit/dotnet/blob/main/CommunityToolkit.Mvvm/CommunityToolkit.Mvvm.targets#L20-L31.

I think we could just check what version the analyzer was built against with SRM but this might make the analyzer load logic too complex.

**Comment by RikkiGibson** [comment]
I think we might be able to `GetReferencedAssemblies` on the assembly that had the problem and figure out which compiler it was trying to reference. Then if we just observe that it is referencing a newer version than what the host is actually running we give a specific error.

**Comment by CyrusNajmabadi** [comment]
Closign due to lack of feedback.

**Comment by RikkiGibson** [comment]
It looks like #61261 solves a similar problem (host version is older than the referenced version from when the analyzer was built)
