### ISSUE TITLE
Add tests for Error list build/intellisense diagnostic components

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47758]
Identified in https://github.com/dotnet/roslyn/pull/47689#pullrequestreview-489944605

> i don't know a good way to do it. but this def feels like an area where we would benefit from some sort of mock-build testing system so thatyou could run a ton of different build notification cases and validate the sstate of querying the system here.

> put another way: i don't know how i would be able to necessarily come in and change this and validate that things weren't broken.

**Comment by CyrusNajmabadi** [comment]
Closing this out as we are removing error list entirely (VSClient to power the UI using LSP).
