### ISSUE TITLE
Need a better NuGet validation process

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#4775]
The bug described in #4774 details a hole in our NuGet validation process.  It is not verifying the packages produced in our build are installable by end users.  Had it been in place this bug could have been avoided.  

Our validation should be updated to ensure all produced NuGets can be installed using only:
- Packages produced from the build 
- Packages from nuget.org (and possibly myget).

**Comment by amcasey** [comment]
There are some additional notes in internal bug 161523.  In particular, consider leveraging https://github.com/ericstj/buildtools/tree/packageInfra/src/Microsoft.DotNet.Build.Tasks.Packaging/src.

**Comment by shyamnamboodiripad** [comment]
@amcasey The above link appears to be broken...

**Comment by amcasey** [comment]
@shyamnamboodiripad GH returns 404 for permission issues.  I'd try asking @ericstj.

**Comment by ericstj** [comment]
I deleted that branch, it's now in buildtools: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/ValidatePackage.cs

**Comment by jasonmalinowski** [comment]
#15422 is tracking us moving to proper integration test, since that brings other goodness too.
