### ISSUE TITLE
Adding analyzer to analyze its own project in which it is created?

### ISSUE THREAD

**Issue by DasOhmoff** [dotnet/roslyn#47759]
Hello, thank you for your help.

Imagine the following scenario: I create a project called "AnalyzerProject" in which a analyzer gets defined.
Is it possible to use this very same analyzer to analyze the very same project?
So that this analyzer that gets build analyzes the project "AnalyzerProject"?

If so, how can I make this happen?
I have three projects in my solution, a analyzer project (net standard 2.0), a code fixes project (net standard 2.0), a package project (which combines both, and is also net standard 2.0), and a vsix project (so that I can test the analyzer by starting another visual studio instance. This one is a net472 project). I am sure you know what I mean. How can I make it happen so that all these 4 projects inside my solution are analyzed by the analyzer that is defined inside the projects themselves?

**Comment by mavasani** [comment]
@DasOhmoff You can add a package reference to an older/published version of AnalyzerProject NuGet package to the project itself. This will ensure the already published version of the analyzer packages runs on your AnalyzerProject. You would then publish a new analyzer package with your changes, and upgrade your package reference to the latest version to get later changes.

**Comment by DasOhmoff** [comment]
Ah I see, is there no way to automatically apply new changes on the fly?
For example by somehow referencing the dll files of the analyzer?
So that I don't have to publish my changes every time I change some minor things.

**Comment by DasOhmoff** [comment]
Thank you!
