### ISSUE TITLE
Functional and Performance issues in detecting compilation end analyzers in IDE

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#47754]
# Context
When running analyzers in IDE background analysis, we need to know if an analyzer has compilation end diagnostics or not. This is required because in the default open file analysis mode, we only run analyzers on open files, and do not run compilation end actions. Hence, the compilation end analyzers are essentially build-only analyzers - these are executed when user invokes an explicit build inside VS, but not during live analysis. Knowing if a diagnostic ID/analyzer is a compilation end analyzer is required to correctly de-dupe build and live diagnostics in error list.

# Issues with current approach to determine IsCompilationEndAnalyzer

1. We currently use a very error prone and fragile approach to determine if an analyzer is a compilation end analyzer: https://github.com/dotnet/roslyn/blob/87f4c9dfc033d81d162249ab4831367f9796bb69/src/Workspaces/Core/Portable/Diagnostics/DiagnosticAnalyzerInfoCache_CompilationEnd.cs#L41-L65
2. This approach needs us to fetch compilation for the project. This was found to be very expensive and primary bottleneck in updating the error list after a build (https://github.com/dotnet/roslyn/pull/47689), as we need to de-dupe build and live diagnostics and categorize build-only diagnostics. Given we have very few compilation end analyzers, it is unfortunate that we are taking such a big performance hit for this determining logic.

# Alternate approaches

We need to identify a more correct, declarative way to identify compilation end diagnostics.  The only way this can be done is if there is a way that analyzer authors can mark their DiagnosticDescriptors as compilation end ones. This will remove all the reliability and performance issues with the current approach.

We have few possible ways to address this. However, we cannot introduce any breaking diagnostic analyzer API changes here.
1. New API: Add a new DiagnosticDescriptor ctor overload that takes an additional boolean parameter, say `bool isCompilationEnd`, and expose a corresponding boolean property off DiagnosticDescriptor
2. Custom tag: Require analyzer authors to specify a special custom tag string to identify compilation end descriptors.

(1) looks to be the more cleaner approach but has following big drawbacks:
   1. Forces analyzer authors to build with a newer Microsoft.CodeAnalysis package, which prevents the package from working against all the previous VS/compiler versions. This is not acceptable approach for large number of analyzer authors - especiall @sharwell has been against such force upgrades in the past.
   2. There is no use case of this flag/property in command line build case, it will only be used for IDE scenarios, so I find it less convincing that needs a new analyzer API.

(2) is a very simple solution, requiring no new API to be added by us and analyzer authors can stay on existing Microsoft.CodeAnalysis package.

**NOTE:** Any change here would introduce a breaking change for existing analyzer packages with compilation end analyzers. I think that is acceptable given:
1. We have very few compilation end analyzers today
2. Diagnostics reported from compilation end analyzers do not support code fixes, again for performance reasons
3. There is a very simple fix from analyzer author side to fix this break and release an updated package
4. We can write a meta-analayzer that flags analyzers registering compilation end actions, but not passing this new custom tag/bool parameter.

**Comment by mavasani** [comment]
Tagging @jasonmalinowski - I would like to bring this up to IDE design meeting today.

**Comment by mavasani** [comment]
# Design Meeting Notes
- We need to know if an analyzer is an compilation end analyzer to know how to dedupe errors from the command build.
- To do this we essentially run the analyzers and see if they register a compilation end action, and if so use that.
- We now hold this a cache but it's not great.
- Question: why do we need to do this if we're moving OOP?
- What does the break look like? The user will only see diagnostics in the output window. This is because we don't know the diagnostics are compilation end only, and so we'll be deferring to always showing the IDE computed diagnostics. Those won't exist, so we won't show anything.

**Conclusion**: Using a custom tag for this is fine, but let's add a heuristic that even if a descriptor doesn't say it's CompilationEnd-only, once we see a compilation end action registered we know it must be an out of date analyzer. We can give a warning telling the user to assume that, and also change the filtering logic to act as if the descriptor was originally marked as CompilationEnd only. That way we may limit the break, or at least help users move forward.

**Comment by sharwell** [comment]
@mavasani before committing to one approach, let's take a second look at this next week and see if we can identify any other approximations that could work for us

**Comment by mavasani** [comment]
>  identify any other approximations that could work for us

@sharwell Do you have any specific non-heuristic based approach in mind for this? @jasonmalinowski @CyrusNajmabadi  correctly pointed out during the meeting that analyzer might be doing any sorts of runtime checks guarding the registration of compilation end actions, so the only definitive way to know an analyzer/diagnostic is a compilation end one is for the author themselves to declaratively state. Otherwise, we are just pushing the can of worms down the road, and this might come back to bite us again in future, just like the current heuristic is causing performance issues. Overall consensus was the number of compilation end analyzers are so less, that a breaking change here + IDE diagnostic would soften its impact and get us out of this mess.

**Comment by mavasani** [comment]
Also note that we are trying to get this into 16.8 along with other error list perf/functional improvements (https://github.com/dotnet/roslyn/pull/47689), so we can request users which have given feedback in this space to try out 16.8 without us worrying about them hitting this very issue and concluding that error list is stale, as opposed to just slow in refreshing.

**Comment by mavasani** [comment]
@sharwell Marked this for today's meeting based on your request.

**Comment by mavasani** [comment]
@sharwell Do you have any alternate proposals here? Unfortunately, this missed the 16.8 release, but I would like to fix this up asap in 16.9 cycle.
