### ISSUE TITLE
Provide a toggle (either on/off, or hold) to enable/disable inline hints.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#47765]
Inline hints provide a lot of value in understanding code.  But not everyone wants them on all the time.  Unfortunately, the only mechanism available to disable and enable them is to navigate all the way to:

![image](https://user-images.githubusercontent.com/4564579/93397530-a514a880-f82e-11ea-9577-804d41e77e61.png)

and toggle that value.  This very much interferes with the flow of coding, and is far too unpleasant to do when one just wants to quickly 'peek' at that information for a short period of time, and then go back to just normal text editing.

We propose an always available toggle for the user to be able to quickly enable/disable hints.  Taht toggle should go on the intellisense toolbar:

![image](https://user-images.githubusercontent.com/4564579/93397618-cf666600-f82e-11ea-81f2-1a40d8f31b6e.png)

There should be a keybinding for thsi as well (ideally *extremely easy to chord*) to allow one to quickly get in and out of this mode.

Alternatively, we might consider having this not necessarily be a toggle, but rather a keyboard chord one could hold to see the hints, and then let go when done.  It's unclear if this would be preferable, or if people would want the toggle/untoggle approach more.

**Comment by PathogenDavid** [comment]
> Alternatively, we might consider having this not necessarily be a toggle, but rather a keyboard chord one could hold to see the hints, and then let go when done. It's unclear if this would be preferable, or if people would want the toggle/untoggle approach more.

I actually really like the idea of being able to bind both. I can see myself binding things so press+hold of F13 shows the hints and pressing Ctrl+F13 toggles them.

**Comment by CyrusNajmabadi** [comment]
Toggle has been done.  We're going to have that be the model going forward for the forseeable future.

**Comment by kapsiR** [comment]
I assume the toggle and the keyboard shortcuts has been introduced with `v16.9`?  
I can't find any option in `v16.8` for that, am I right?

**Comment by CyrusNajmabadi** [comment]
That's right

**Comment by luisfco** [comment]
Toggle / Shortcut (Alt+F1, as specified in the Options Dialog) is not working in VS2019 (v16.11.9), neither VS2022 (v17.0.4)
