### ISSUE TITLE
Records: default public properties

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#47781]
This has been mentioned before but I would like to clear up the argument against it.

That is already the case with positional auto props - they are public by default. so if you want to redefine it for any reason, you shouldn't be required to spell it out unless you want some other accessibility. I think that is important especially since all props are incorporated in value equality.

**Comment by alrz** [comment]
I think this all make more sense now that we have a `record` declaration rather than just a modified `class`.

**Comment by alrz** [comment]
Pretty sure this has been considered and rejected.

@jcouv Can you weigh in on this one just to clarify? Since this is a breaking change I doubt it would make sense as a language feature request at this point.

**Comment by jcouv** [comment]
Yes there was a pretty extensive discussion of what the defaults should be inside records ;-) You may want to look back at LDM notes.
We didn't want to penalize nominal records (ie. with empty constructor) compared to positional records (ie. with primary constructor). We also didn't want to scramble default compares to existing code, or confuse fields with properties. 
So there is still a plan for `data` properties (`data` being a shorthand for `public` and `{get; init;}`).

**Comment by alrz** [comment]
Thanks! (I almost forgot about data properties..)
