### ISSUE TITLE
IDE options to control the sorting of fields and properties

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#4778]
**Steps to Reproduce**
1. Create a WPF Application
2. Open MainWindow.xaml.cs
3. Type the following: `string field;`

``` csharp
    public partial class MainWindow : Window
    {
        string field;

        public MainWindow()
        {
            InitializeComponent();
        }
    }
```
1. Press Ctrl+.
2. Select "Encapsulate field: 'field' (usages reference field)" and press Enter

**Expected**
Behaviour in VS2013

**Actual**
1. Field is generated at the bottom of the class declaration (sometimes it is generated in the correct location though.. right below the field declaration)
2. Unnecessary new lines are added to the getter/setter
![image](https://cloud.githubusercontent.com/assets/10136526/9474820/b7704a8a-4b17-11e5-9f6e-d34adb4e66ef.png)

**Comment by Pilchie** [comment]
The newlines are also tracked by http://connect.microsoft.com/VisualStudio/feedback/details/1617595/incorrectly-formats-source-code-when-using-the-encapsulate-field-command.

The property placement may be by design, but we should understand the difference.

**Comment by rchande** [comment]
The newline aspect of this is tracked by #84.

**Comment by rchande** [comment]
Generally, Roslyn inserts properties after constructors, as controlled by the [CSharpDeclarationComparer](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CodeGeneration/CSharpDeclarationComparer.cs,9313cfb95e4608a9). We'll use this bug to track adding options to modify that sort order.

**Comment by galastur** [comment]
Really annoying all those extra lines when generating the get/set for a property...please let us have it as it was with VS 2013 !!!

**Comment by Pilchie** [comment]
Note - when implementing, it would probably be a good idea to re-use the idea of Symbol Specification from naming styles to define this ordering.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  The fields go in teh right place, and the property formatting is correct.

**Comment by RudeySH** [comment]
Why was this issue closed? In 2015, @rchande said:
> We'll use this bug to track adding options to modify that sort order.

This has led to other issues about sorting/ordering/organizing being closed as a duplicate of this one. Namely #28797 and #47451.

But now this issue has been closed with no mention of any of this.
