### ISSUE TITLE
ToString() prints overridden record property twice

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#47797]
```C#
abstract record A
{
    public virtual int P { get; set; }
}
record B : A
{
    public override int P { get; set; }
}
class Program
{
    static void Main()
    {
        System.Console.WriteLine(new B() { P = 2 }.ToString());
    }
}
```
Result:
```
B { P = 2, P = 2 }
```
See [sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8JhYEIBjGAAgTgoHsEdqBBAWACgBvL6/6gAEAzNQBuASwQx0EADbUJmGgAVq3agHM4MANzUoO/QF8upznUbNqAIWog2XXpwFDRDMYgQSccRcuo1DW09AyNqc3NBACYhAEYAdic+AUE4gDYhABZqAFkIJQAKAEoU/mdXVzSAOjSATkLMOAB3WxL1QOoAXmpY42qAFQYAZRhvTE0S4t0yiLMgA)

**Comment by cston** [comment]
cc @jcouv

**Comment by Youssef1313** [comment]
I think the problem is in:

https://github.com/dotnet/roslyn/blob/62d0895a32f89e3c484c1fd066fdb96fd78d9774/src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs#L109-#L110

Should be:

```diff
-                    .WhereAsArray(m => m.DeclaredAccessibility == Accessibility.Public && (m.Kind is SymbolKind.Field or SymbolKind.Property));
+                    .WhereAsArray(m => !m.IsOverride && m.DeclaredAccessibility == Accessibility.Public && (m.Kind is SymbolKind.Field or SymbolKind.Property));
```
