### ISSUE TITLE
Intellisense should autofill template of method parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47792]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1160974/intellisense-should-autofill-template-of-method-pa.html)._

---
Visual Studio can display intellisense for methods in C#.  It would be a nice feature to have it auto-complete the selected overload so a user can fill in the required values.

**Expected Action**

Select the method desired as shown in the screenshot.  I choose on auto-actions 'autocomplete' or 'prefill arguments' and then VS types out for me the following with named parameters:

`MyMethodWithLotsOfParms( CountToProcess:<int>, baseNamingConvention:<string>, continueOnError:<bool>, outputDir:<FileInfo>)`

Then I could optionally tab through variables in my local scope that match, or just fill in the blanks.

---
#### Feedback Bot on 8/25/2020, 01:37 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Mika Dumont [MSFT] on 8/27/2020, 11:55 AM: 

<p>Hi Stephen, </p><p>Thank you for taking the time to provide this feedback. We recently added <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2019#editor-help" target="_blank">inline parameter name hints</a> which you will need to turn on in Tools &gt; Options &gt; Text editor &gt; C# &gt; Advanced and select Display inline parameter name hints (experimental). Let me know if this helps or if you still feel the experience is incomplete. </p>

#### Feedback Bot on 9/9/2020, 01:21 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.

**Comment by CyrusNajmabadi** [comment]
There was no response from the customer, and this scenarios is covered by the work we did recently to have inline-parameter-hints.  So closing this out.
