### ISSUE TITLE
Building VB.NET project can report errors with invalid paths when the file path contains a number within parentheses

### ISSUE THREAD

**Issue by adambiser** [dotnet/roslyn#47790]
**Version Used**: 
VS 2019 v16.7.3
Recently repaired to see whether that fixed the issue.  It did not.

**Steps to Reproduce**:
1. Create a new VB.NET project in a path that contains a number within parentheses.  ie: E:\VBProject (x64)\BadErrorPath
2. Write a line of code that has an error in it.  ie: asdf
3. Verify that the Error List window shows the Line, Col, Path, and Source columns.
4. Close the code window.
5. Build the project.

**Expected Behavior**:
Expected the Error List to show the correct path, line, and column for the error.
Expected to be able to double-click the build error line to open the file with the error, positioned to the error line.

**Actual Behavior**:
I get two errors,  The one from the **Build** source says line 1, column 1 and has a bad path.  Double-clicking it does nothing.

The whole build output is below and in it I see:
**E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4)**: error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.

It looks like the (x64) from the path is tricking error reporting into placing the column number in those parentheses rather than after the line number in (4).

1>------ Build started: Project: BadErrorPath, Configuration: Debug Any CPU ------
1>Build started 9/17/2020 1:25:21 PM.
1>GenerateBindingRedirects:
1>  No suggested binding redirects from ResolveAssemblyReferences.
1>CoreResGen:
1>  No resources are out of date with respect to their source files. Skipping resource generation.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\vbc.exe /noconfig {Snipped long line}
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn
1>E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4): error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.
1>
1>Build FAILED.
1>
1>"E:\VBProject (x64)\BadErrorPath\BadErrorPath.vbproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
1>(CoreCompile target) -> 
1>  E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4): error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.04

**Comment by RikkiGibson** [comment]
Is this a regression from a previous version of VS?

**Comment by adambiser** [comment]
I have not tried VB.NET in versions of VS since 2008.  VS 2008 handled things correctly.

**Comment by adambiser** [comment]
The unexpected behavior/incorrect paths in error list for Build errors also occurs in:
VS 2017 v15.9.27
VS 2015 v14.0.25431.01 Update 3
VS 2012 

The problem seems to be originating in VBC.  I'm not very familiar with the code, but I dug around and see this:
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Vbc.cs#L695
The code finds the first end parenthesis in the error string and adds "," + column at it.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler is this something we would take a fix for?

**Comment by 333fred** [comment]
I believe so.
