### ISSUE TITLE
Refactor a local variable to a class member/property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/911311/refactor-a-local-variable-to-a-class-memberpropert.html)._

---
One of the things I frequently do as part of refactoring is migrating a local variable to class level and vice versa. I think having a suggested refactor and automatically refactoring would be a great addition

---
#### Feedback Bot on 2/10/2020, 02:35 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Related to #30466

**Comment by sharwell** [comment]
📝 I find "promote to containing scope" the more common goal for refactoring a local variable declaration.

**Comment by vatsalyaagrawal** [comment]
Design meeting notes: We like the idea of split declaration and initialization and initially we will like to make it match to what happens for generate variable when you don't have a type listed. So it would be split declaration and initialization and give options for placement.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
