### ISSUE TITLE
AbstractSimplificationService.ReduceAsync calls Task.WaitAll

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#478]
Async methods should not unnecessarily block threads (UI thread or otherwise). This method delegates to a synchronous Reduce method which calls Task.WaitAll. 

It appears Task.WaitAll takes a CancellationToken whereas Task.WhenAll does not offer that option. I see Roslyn is passing in a CancellationToken so that may be why WaitAll was chosen. However there are better ways to combine cancellation and async code. 

I'll prepare a pull request for this fix.

Ported from https://roslyn.codeplex.com/workitem/471

**Comment by heejaechang** [comment]
Andrew already sent PR for this.

**Comment by srivatsn** [comment]
Yes, assigning to you to review and merge that PR (since you've already starting looking at the PR).
