### ISSUE TITLE
Copying property values from one object (source) to another one or more objects that may or may not be related to the source object

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#47809]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1184054/copying-property-values-from-one-object-source-to.html)._

---
<p>I think the Visual Studio IDE should have a <b><em>feature that generates the applicable code for copying property values from one object (source) to another one or more objects that may or may not be related to the source object, on a property by property basis</em></b> (i.e. anotherObject.Property1 = sourceObject.Property1; and this could involve properties that don't necessarily have same property names nor same classes).</p> <p></p><p><strong><em>My reason for this</em></strong> is that when I intend to copy values from one object to another, I most likely also want to modify some of the values of the properties I intend to copy over as I assign them to the recipient properties. So, none of the answers provided so far help me to the fullest. For example, I may want to save something to the database or to do some additional logic to validate or verify some data during the copying. So, for this, only the traditional property by property basis gives me room for that.</p> <p></p><p>So, if the IDE (e.g. Visual Studio) can have a way to generate the code, it could be really useful. <strong><em>A downside I see</em></strong> is, depending on the number of properties involved, the code can get really long and could resultantly increase the size of the software or class library.</p>

---
#### Feedback Bot on 9/15/2020, 03:08 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
I believe the language intends to approach the high-level problem here via `with` expressions in C# 10 (or later), and the IDE intends to eventually support target-typed completion in more scenarios. If a more completion solution is desired within the context of a known set of APIs, we also have the CodeRefactoringProvider and CompletionProvider extension points that could be leveraged in an independent solution.

**Comment by CyrusNajmabadi** [comment]
CLosing out as this is more a lang feature.
