### ISSUE TITLE
Discussion: Scope of pattern variables, and tuple decomposition

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#4781]
I’m doing a draft reimplementation of pattern matching (#206) now, and trying to figure out the right scoping of pattern variables. I had expected to use whatever we came up with for declaration expressions when those were under development, but it turns out that doesn’t make sense in many situations. For example, given the statement

```cs
M(x is int i ? i : 12);
```

There is no point in the variable `i` being in scope outside this statement, as it won’t be *definitely assigned* anywhere else. My current thinking is that a pattern variable introduced in an expression would be limited in scope to the nearest enclosing statement, with the single exception that a pattern variable introduced in the condition of an `if` statement would not be in scope in the `else` clause.

For a field initializer, the scope would be limited to that declaration. For an expression-bodied property or method, limited to that declaration. For a ctor-initializer, limited to that ctor-initializer. The scope of a pattern variable introduced in a catch clause is the catch block.

For decomposing a tuple (#347), I anticipate introducing a separate statement form, something like

```cs
pattern := expression ;
```

For example

```cs
var tuple = (12, "foo");
(int x, string y) := tuple;
```

This has the same semantics as the expression

```cs
expression is pattern
```

With the exceptions that
- It is a statement form, not an expression form;
- The compiler must be able to prove that the match always succeeds (otherwise it is a compile-time error); and
- Variables introduced in the pattern remain in scope within the enclosing block

I welcome feedback and comments on this while is it fresh on the drawing board.
@MadsTorgersen @ljw1004 @semihokur @AnthonyDGreen @terrajobst @jaredpar @Pilchie @mattwar @stephentoub @vancem

**Comment by svick** [comment]
What's the reasoning behind using `:=`? Wouldn't just `=` (e.g. `(int x, string y) = tuple;`) work?

Or is it meant to differentiate between pattern decomposition and normal assignment?

Also does this mean that (using examples from #206) `Polar(var R, *) := Cartesian(3, 4);` would work? Because that would be awesome.

**Comment by gafter** [comment]
@svick You're suggesting an assignment expression inside an expression-statement, but the left-hand-side isn't an lvalue, the assignment itself doesn't appear to have a well-defined type, and the left-hand-side appears to be a type expression rather than a valid syntactic form for an (lvalue) expression.

No, `Polar(var R, *) := Cartesian(3, 4);` would not work because that decomposition could fail (and therefore the compiler cannot prove it will succeed).

**Comment by MgSam** [comment]
Speaking purely from a usability perspective, adding `:=` to the language just to deconstruct tuples seems odd and likely confusing. You would almost certainly have to add a compiler error/warning for the extremely common case when people type `(int x, string y) = tuple;`- at which point one would ask why isn't that the default anyway. 

I understand it doesn't behave like a normal assignment, but it should still re-use the same `=` operator.

**Comment by dsaf** [comment]
Looking at current version of the language, this is similar to ```foreach```. Reusing ```for```'s variable is a bad practice. Passing a variable into ```using``` is also not recommended.

Keeping things local reduces cognitive load. Even in current C# I sometime use curly brackets to make a local variable even more local:

```csharp
public float BigCalculationThatShouldntBeSplit() 
{
    float result = 0;

    {
        float variableWithSomeMeaning = 0;
        //first leg of calculation
    }

    {
        float variableWithOtherMeaning = 0;
       //second leg of calculation
    }
 
    return result;
}
```

**Comment by dsaf** [comment]
@MgSam 
> Speaking purely from a usability perspective, adding := to the language just to deconstruct tuples seems odd and likely confusing.

What if it will be allowed to define custom operators like in F# and then ```:=``` *simply* becomes a variadic generic extension operator on the new ```ValueTuple<>``` type?

**Comment by gafter** [comment]
There is also the question of how to handle the scoping of pattern variables appearing in the various parts of a query expression.

**Comment by MgSam** [comment]
@dsaf Adding custom operators seems outside the scope of the discussion on pattern matching.  It also hasn't even been seriously considered for C# 7.0 at this point so I don't think any proposal should incorporate that. 

@gafter I think some more examples on how the proposed scoping rules would behave (especially in contrast to the discarded declaration expressions proposal) would be helpful.

**Comment by gafter** [comment]
@MgSam It is very simple - the variable simply would not be in scope outside the immediately enclosing statement.

```cs
M(x is int i ? i : 12); // i is scoped to this statement
Console.WriteLine(i); // error: i not found
```

In an if statement, it isn't even available in the else clause

```cs
if (x is int i)
{
    // int i is in scope
}
else (if x is string i) // int i not in scope here, so we can reuse the name
{
    // string i is in scope
}
```

**Comment by HaloFour** [comment]
@gafter 

Paren in the wrong spot there?

I recall the argument that erupted from the scoping of declaration expressions.  I was under the impression that was part of the reason that the feature was dropped/postponed.

**Comment by AdamSpeight2008** [comment]
`:=` is used in named parameters, so to be consistent the `identifier` should be on the left of `:=`

**Comment by gafter** [comment]
@HaloFour The scoping rules for declaration expressions didn't make sense for pattern matching. That was part of the reason we put the feature off. I'm trying to restart the discussion in the context of pattern matching.

**Comment by gafter** [comment]
@AdamSpeight2008 There is no identifier in the syntax for the decomposition operator.

**Comment by AdamSpeight2008** [comment]
>  There is also the question of how to handle the scoping of pattern variables appearing in the various parts of a query expression. 

They are different variables, but have the same name, since it gets expanded out into function calls.

`( x:= , y:= , z:= ) = someTuple`

**Comment by gafter** [comment]
@AdamSpeight2008 I think you're talking about range variables, which have nothing to do with the current discussion.

**Comment by AdamSpeight2008** [comment]
@gafter 

`M(x is int i ? i : 12); // i is scoped to this statement`
This looks messy and confusing. 
`x is int`  a boolean expression
`i ? i : 12` a inline condition
How can that work? I'd be spending more of my time trying to understand the syntax, rather doing work.

It needs to be a lot clearer, in its intent.

For example
```C#
case ( int, int ) into x, y when ( ( x > 0 ) && ( y > 0 ) ) :
  // foo
```
This checks the types, decomposes the value into variable named x and y (both of type int).
Then checks the values of them (a guard expression). If it evaluates to true then it proceed to run the code after `// foo`

**Comment by gafter** [comment]
@AdamSpeight2008 
> I'd be spending more of my time trying to understand the syntax, rather doing work.

Yes, when you start seeing a new syntax you have to take time to learn it instead of forging ahead without understanding. Hopefully you would not have to learn a new syntax every time you see it for the rest of your life.

The syntax you propose does not extend naturally to recursive pattern matching. I have no idea how it would be used in a method call per the original example. It also detaches the type names used to declare the pattern variables from the appearance of the pattern variables, making the syntax more difficult to comprehend, especially as the use cases get more complex.

**Comment by dsaf** [comment]
@AdamSpeight2008 In my opinion the syntax is as clear as it gets. But I guess you will be able to use the expression form of the ```switch``` to achieve the type of readability you are looking for:

```csharp
M(switch(x) {
    case int i:
        return i;
    default:
        return 12;});
```

**Comment by gafter** [comment]
@dsaf We are not going to hijack the `return` statement that way. Perhaps

```cs
M(match(x) 
```

**Comment by AdamSpeight2008** [comment]
In Nemerle is would be something like
```c#
M( match(x)
   { 
     | ( int ) into i => i;
     | _ => 12;
   } )
```

@dsaf  The syntax is ambiguous in terms of possible meaning.
 `if (x is int i)`  it looks like a syntax error. eg a missing operator; maybe `==`
 Why isn't `i` a boolean? Since the type signature is   `(obj,int)->bool`.

**Comment by gafter** [comment]
@AdamSpeight2008 
> it looks like a syntax error

Every new feature uses syntax that used to be an error. That's how we manage to extend the language without changing the meaning of existing programs.

**Comment by mikedn** [comment]
@gafter 
>My current thinking is that a pattern variable introduced in an expression would be limited in scope to the nearest enclosing statement, with the single exception that a pattern variable introduced in the condition of an  if  statement would not be in scope in the  else  clause.

If the opposite is done and `i` is introduced in the enclosing scope then I suppose the following would fail to compile:

```C#
M(x is int i ? i : 12); 
M(x is int i ? i : 12); 
```
Or would the second statement attempt to use the existing `i`?

If not then I'm sure that there will be cases where it would be useful to have `i` declared in the enclosing scope but most of the time it would be highly annoying as you have to come up with new variable names for every such statement. So, short of using special syntax to select where `i` is declared (and having that would be quite weird IMO), the current scoping choice looks good to me.

**Comment by gafter** [comment]
@mikedn No, it won't reuse an existing variable. If there is already a variable of that name in scope it is an error

> If not then I'm sure that there will be cases where it would be useful to have i declared in the enclosing scope

Such cases are rare, as the variable is only definitely assigned when true for the `is`-expression. Here is one realistic case:

```cs
if (!(o is int i)) throw new ArgumentException("o");
// now i is definitely assigned
```

The proposed scoping rules don't make this legal. On the plus side, they *do* make this legal:

```cs
if (o is string s) { /* code using string s */ }
else if (o is Something s) { /* code using Something s */ }
```

**Comment by whoisj** [comment]
Just so those of us with a slower uptake understand this.

This `(x is int i ? i : 12)` is functionally identical to this `var i = x is int ? i : 12`, ignoring current type issues?

**Comment by HaloFour** [comment]
@whoisj 

Sorta.  If I read this right the variable `i` would be out of scope outside of the expression, so you'd have to assign the result to another variable with a different name.  Since the example is passing it as a parameter to a method called `M` that is not really a concern.  Other than that you're right, the `x is int i` expression returns a `bool` so it can be used with `?:` and the variable `i` would be in scope for the remainder of that expression.

**Comment by gafter** [comment]
@whoisj Sort of. If former only assigns the value of `x` to `i` if `x` is an `int`, otherwise it leaves `i` unassigned. Your example sometimes assigns `12` to `i`. Also the former is an expression and yours is a statement.

**Comment by HaloFour** [comment]
@gafter Would it be safe to assume that the same rules apply as with `if` statements that `i` would not be in scope in the "else" portion of the ternary expression?  Or would it be in scope but considered unassigned?  Would something like the following be possible?

```cs
object x = ...;
object y = ...;

int z = (x is int i ? i : y is int i ? i : 23);
```

**Comment by gafter** [comment]
@HaloFour Current plans are that it will be in scope but not definitely assigned.

**Comment by MgSam** [comment]
@gafter It seems to me that the issue with the scoping rules you propose is the same as discussed in the original declaration expressions proposal. Its probably desirable either now or in a future version to have more general declaration expressions, so how would these rules affect that feature?

You run into this problem:
``` C#
var dict = new Dictionary<string, string>();
var success = dict.TryGetValue("foo", out var result);
//result is now not in scope? 
```

Of course there are probably ways to fix this: Special-case dec expressions on out parameters? Special tuple syntax for out parameters? Deprecate methods with out parameters once tuples become available?

**Comment by paulomorgado** [comment]
@MgSam, the way I see is like this:

1. The scoping variables in declaration expressions and pattern variables is the same.
    1. block;
    2. `if`/`while`/whatever statement
    3. etc.
2. However, there are cases where the pattern variable is definitely not definitely assign.
    1. So, for not polluting the variable space with variables that are always not definitely assigned, they become out of scope.

Here is an example of both:

    if (x is int i)
    {
        // i is definitely assigned!
    }
    else
    {
        // i is definitely not assigned, so it si out of scope to allow another variable named i.
    }
    
    if (int.Parse(s, out i))
    {
        // i is definitely assigned!
    }
    else
    {
        // i is definitely assigned! ==0
    }

**Comment by AdamSpeight2008** [comment]
If the are similar in scoping why not combine the syntax?

`If( x is int out i)`

Makes is little easier to understand the you're outputting some value to `i`.

**Comment by gafter** [comment]
@AdamSpeight2008 We don't use the `out` syntax for every language construct that assigns a value. That is for parameter passing.

**Comment by AdamSpeight2008** [comment]
@gafter but you are parameter passing. You're passing out the resultant type cast.
Essential it is a Try Method, hence the association to declaration expression.
```c#
static bool @is<T>(this object x , out T o )
{
  bool s = x is T;
  o = s ? (T)x : default(T);
  return s;
}
```
Usage
```c#
M( x.Is<int>( out i ) ? i : 12 )
```
```vb
M( If(x.Is<int>( out i ), i, 12) )
```
Is easier to scan and comprehend, it terms of existing concepts with C# and VB
Does not have the jarring break, of within a boolean expression aspect of a inline conditional expression a magic declaration appearing.
`( _this_part _? ( _true_expr_ ) : ( _false_expr_ )  )`
Let's fill it in.
`( ( x is int ) ? ( _true_expr_ ) : (  _false_expr_  ) )`
 Now if we include declaration from the resultant cast
`( ( x is int ) i ? ( _true_expr_ ) : ( _false_expr_ ) )`
it doesn't make sense in terms of it being expression.
Whereas using the function calls ( extension method) and using declaration expressions does.
`( ( x.Is<T>(out i) ) ? ( _true_expr_ ) : ( _false_expr_ ) )`

**Comment by gafter** [comment]
@AdamSpeight2008 There is no method, and there is no parameter. Your method (if it were possible to write that) simulates this language construct for only the simplest, non-recursive cases.

**Comment by AdamSpeight2008** [comment]
It is possible to write (LinqPad)
```c#
void Main()
{
  object o = 1;
  int x;
  bool b= o.@is<int>(out x );
  x.Dump();
}
static  class exts
{
// Define other methods and classes here
static public bool @is<T>(this object i, out T o)
{
  bool s = i is T;
  o = s ? (T)i : default(T);
  return s;
}
}
```

According to the example you've provided so far, the following is permitted.
```c#
var b = x is int i;
```


@gafter Provide some recursive examples then. :trollface:

**Comment by gafter** [comment]
@AdamSpeight2008 See section 8.4 of #206 for some recursive examples.

Your `@is` method performs the dynamic type conversion twice.

**Comment by AdamSpeight2008** [comment]
@gafter 
 The recursive pattern you suggest, doesn't indicate how knows each part of the pattern match
is referring to the `.Left` and `.Right` properties on the object..
Or that you are match ng against types *( or more abstractly the structure of object)* and not against object values.

If we modify the syntax to include `match type` expression. we can also do away with the `return`, only requiring a `return` if it block. Like lamda functions.
```c#
Expr Simplify(Expr e)
{
  match type (e) 
  {
    case Mult var m:
      match type ( m.left, m.right )
      {
        // assumming the Const implements operator [=]
        case (Const var k, _ ) when (k = 0): Const(0);
        case ( _ ,Const var k) when (k = 0): Const(0);
        case (Const var k, _ ) when (k = 1): Simplify( m.R );
        case ( _ ,Const var k) when (k = 1): Simplify( m.L );
        case (Const var l, Const var r)    : Const(l*r);
        default: m;
      }
    case Add var a:
      match type ( a.left, a.right )
      { 
        case (Const var k, _ ) when (k = 0): Simplify(r);
        case ( _ ,Const var k) when (k = 0): Simplify(l);
        case (Const var l, Const var r)    : Const(l+r);
        default: a;
      }
    case Neg var n:
      match type ( n.Value )
      {
        case Const var k: Const(-k);
        default: n;
      }a
    default: e;
  }
}
```

**Comment by paulomorgado** [comment]
@AdamSpeight2008, an `out` parameter is always definitely assigned and a pattern variable isn't. Your proposed syntax would bring a huge confusion to the understanding of `out`.

**Comment by AdamSpeight2008** [comment]
@paulomorgado
 but the parameter variable is only ever going to be defined (and thus definitely assigned ) in the `true` case. In the `false` case it is not even defined.

```vb
Select Case True
  Case TypeOf x Is String out s
    ' s is defined here eg;= Dim  s As String = DirectCaset(s,String)
    When (s IsNot Nothing) AndAlso ( s.Length > 0 ):
      ' Do stuff
  Case TypeOf x Is Integer out i
    ' i is defined here eg;= Dim i As Integer = DirectCast(i,Integer)
    Select Case i
      Case Is < 0: ' Negative
      Case Is = 0: ' Zero
      Case Is > 0: ' Positive
    End Select 
  Case Else
    Throw New Exception
 End Select
```

**Comment by paulomorgado** [comment]
Yes, @AdamSpeight2008. But that's not what happens with `out` parameters.

**Comment by AdamSpeight2008** [comment]
@paulomorgado I said it is "essentially" a Try Method, which has `out parameters`. so it makes sense to have behave similarly both in syntax and semantics.

In c# you could get away with `obj is T var x`.

In vb `TypeOf obj Is T Dim x` looks weird, but `TypeOf obj Is T out X` doesn't

Having similar syntax in both languages eg `obj Is T out x` and `TypeOf obj Is T out x` makes sense for those who both languages.

**Comment by paulomorgado** [comment]
@AdamSpeight2008, I'm going to stay away of VB, out of respect for those that write it. Because, for me, it is a read-only language.

But I'm aware that declarations is an area where the two languages have their differences and, even being just a reader, I would find very odd and hard to read if, just for a particular feature, that difference would not be there. Even worst if it makes it just plain wrong for one of the languages (C#).

I really don't know how I can make it more obvious that this has nothing similar (not even "essentially") to a Try method because, in C#, the out parameter is definitely assigned and with this feature it isn't.

Also, function arguments/parameters can be just input, just output or input and output. For that reason, a modifier is need to tell which is it. As the "normal" case is just input, this case has an "invisible modifier".

In this feature there's only one case. There's no doubt which one is it - just output. Adding to that the differences in definitely assignment.

**Comment by orthoxerox** [comment]
I agree that `M(x is int i ? i : 12);` is a very weird syntax. Am I correct that `M` is actually a method and we're doing pattern matching on value `x`? Then `x is int i` introduces variable `i`, sets it to the value of `x` if it's an `int` and returns `true` or returns `false` otherwise? And finally we use the `?:` operator to pass either `i` or 12 to `M`?

Oof.

First of all, why didn't we write `M(x as int ?? 12)`. Yes, this avoids pattern matching, so it can't work as an example, but is much clearer and shows that pattern matching is not necessary.

Second, do we really need this kind of pattern matching? IMO, writing `if (x is int) {` should automatically treat `x` as `int` inside the scope of the condition (perverted existing code might be broken if it violates LSP (i.e. both types implement the same method non-virtually), but a warning might be written for that), removing another use case for this operator. Only switch statements would remain, and I don't think they require any weird operator combinations like this one.

In general, I am against language constructs that introduce new or mutate existing variables and return useful values at the same time, so `M(x is int i ? i : 12)` is as horrible as `while (x = *p++)`.

**Comment by HaloFour** [comment]
@orthoxerox 

> First of all, why didn't we write `M(x as int ?? 12)`.

Well, as you mention, it isn't a demonstration of pattern matching.  The actual expression is not that important when it comes to the discussion of scoping the result(s).  The other issue is that C# doesn't currently permit `as` with value types and there is no proposal to expand that.  I assume that the type of the result of `x as int` would have to be `int?` particularly for `??` to then work?

**Comment by AdamSpeight2008** [comment]
@gafter 
Is this valid statement `var res = obj Is int var x;`*minus the debate over var / out*

----

Suppose the *clause* had it own scope. So variable can be defined and are in scope,within the *clause* and subsequently.inherited by the body of the true.
Eg
 ```c#
var res = obj Is int var x;
// x is defined and definitely assigned a value (default(Int)) in this case.
```
and
```c#
// x is not defined
if( obj is int var x)
{
// x is defined with value (int)obj
}
/// x is not defined
```
----
what about this case.
```c#
( (obj is int out x) & (x >= 0) )
```
Wouldn't `x` need to be defined in both cases and be assigned a value? 
Otherwise you have the situation of `unassigned >= 0` and not in the other.

**Comment by orthoxerox** [comment]
@HaloFour 
Yes, my bad, the expression should be `M(x as int? ?? 12)`.

**Comment by HaloFour** [comment]
@orthoxerox `Nullable<T>` is still a struct, and `x is int?` is still false if `x` is an `int`.  You'd need `M(x is int ? (int)x : 12)`

**Comment by orthoxerox** [comment]
@HaloFour nope,

```csharp
	static class Program
	{	
		static void M(int i)
		{
			Console.WriteLine(i);
		}
		
		static void N(object o)
		{
			M(o as int? ?? -1);
		}
	
		public static void Main(string[] args)
		{
			object a = new object();
			int b = 2;
			object c = null;
			int? d = null;
			int? e = 5;
			object f = 6
			
			N(a);
			N(b);
			N(c);
			N(d);
			N(e);
			N(f);
			
			Console.ReadKey(true);
		}
	}
```

actually prints

```
-1
2
-1
-1
5
6
```

**Comment by HaloFour** [comment]
@orthoxerox That's right, there are different boxing/unboxing rules for `Nullable<T>`.  Either way, the important bit of this conversation is regarding the scope of those parameters, not necessarily which pattern is being matched.  Type checking is just a simple pattern.

**Comment by orthoxerox** [comment]
@HaloFour  And that's why I questioned allowing universal use of pattern matching's `is` operator, since there's no compelling use case where it is superior to existing language features outside of actual pattern matching.

**Comment by MrJul** [comment]
@orthoxerox I don't think the point of this issue is to question pattern matching. If you don't see its use, just don't use it :)

For more complex cases, it becomes superior IMHO:
```
M(something is Point(int x, int y) ? x * y : 12)
```
VS
```
var point = something as Point?;
M(point != null ? point.Value.X * point.Value.Y : 12)
```

And it really shines in a switch construct, as seen in the proposal.

**Comment by HaloFour** [comment]
Might be an argument to use a new keyword like `match` instead of `is`, but that probably belongs under #206.

**Comment by MrJul** [comment]
@gafter 
> `if (!(o is int i)) throw new ArgumentException("o");`
> The proposed scoping rules don't make this legal.

I think this could be solved by allowing to match into an existing variable:
```
int i;
if (!(o is int into i)) throw new ArgumentException("o");
// i is definitely assigned here.
```

(Please don't focus on the chosen syntax (`into`): I simply want to discuss using existing variables with pattern matching, even if it won't be the main use case).

**Comment by orthoxerox** [comment]
@MrJul I didn't say pattern matching was bad, it's very good where it belongs, inside switches. Your more complex example could be rewritten using my proposal to autocast variables inside `if`s:

```c#
if (something is Point)
    M(something.X * something.Y);
else
    M(12);
```

or actually using switch:

```c#
switch (something) {
    case Point(int x, int y):
        M(x, y);
        break;
    default:
        M(12);
        break;
}
```

The only use for a compound `is+as` operator the new `is` is is the need to get a downcast variable inside the switch, since it has no case-level scopes, e.g.

```c#
switch (token) {
    case Literal litToken:
        return litToken.ParseValue(); //can't use token automatically cast as Literal here
    ...
}
```

And this is once again a special case.

**Comment by HaloFour** [comment]
@MrJul Not a bad idea but I can see how it might be awkward.  With the other forms of pattern matching I think it would be a little clearer, the type specific syntax above it would be a little weird.

```cs
object o = ...;
int x;
if (o is Point(out x, var y)) { } // reuse x, declare y
```

**Comment by gafter** [comment]
@AdamSpeight2008 
> The recursive pattern you suggest, doesn't indicate how knows each part of the pattern match
is referring to the .Left and .Right properties on the object..
Or that you are match ng against types ( or more abstractly the structure of object) and not against object values.

I suggest you read the *whole* specification for the details, not just the example. Or try [the prototype](https://github.com/semihokur/pattern-matching-csharp). I'm working on reintegrating the prototype into Roslyn now, so it will be easier to experiment.

**Comment by alrz** [comment]
could `KeyValuePair<,>` be treated as a tuple and make this possible?

    foreach ((var key, var value) in dictionary)
    {

    }

**Comment by gafter** [comment]
@alrz Treating `KeyValuePair` as a tuple doesn't get that behavior. We'd have to change the `foreach` statement to do decomposition.

**Comment by alrz** [comment]
@gafter in F#, patterns (which do the decomposition) are everywhere, as in `let pattern = expression in ...` , `fun pattern -> expression` and `for pattern in enumerable-expression -> ...` but still you can't have `for key,value in dicitonary` where `dictionary` is a `Dictionary<,>` because `KeyValuePair<,>` is not a tuple.

**Comment by gafter** [comment]
@alrz If we had started with pattern matching we might have decomposition everywhere too. But we didn't so we don't.

**Comment by whoisj** [comment]
> Treating KeyValuePair as a tuple doesn't get that behavior. We'd have to change the foreach statement to do decomposition.

Can't you just add an `implicit` conversion to the `KeyValuePair` type?

**Comment by alrz** [comment]
@whoisj it would be a good idea but C# doesn't support generic operators like

    public static implicit operator (TKey,TValue)<TKey,TValue>(KeyValuePair<TKey,TValue> p)
        => (p.Key,p.Value);

which can be  another feature request. also read the latest comments on #98.

**Comment by gafter** [comment]
@alrz If declared inside the `KeyValuePair` struct, this conversion operator would not have to be generic.

```cs
public static implicit operator (TKey,TValue)(KeyValuePair<TKey,TValue> p) => (p.Key,p.Value);
```

However, that still would not cause the `foreach` loop to perform decomposition.

**Comment by Eyas** [comment]
@gafter Since we are talking about an entirely new feature anyways (pattern matching/decomposition), what would be the best place to talk about the possibilities of decomposition in a `foreach` loop? Or has it been discussed and determined to be impractical due to some deep language/compat change that the team is not willing to make?

**Comment by whoisj** [comment]
> @whoisj, what would be the gain in doing that? Do you want the tuple or the tuple items?

Cleaner code, which expresses intent and not so much boiler plate.

> @whoisj it would be a good idea but C# doesn't support generic operators

Touche.

**Comment by gafter** [comment]
@Eyas This is a fine place to discuss it, or in the tuple issue (#347). I'm just pointing out that you won't get it "for free" even if you get both tuples and a decomposition statement.

**Comment by alrz** [comment]
@gafter since `foreach` loop uses the assignment statement `var current = enumerator.Current;` I think it could.

**Comment by gafter** [comment]
@alrz Assignment and decomposition are different. For example, the pattern `object o` only matches a non-null value, but an assignment to it always succeeds. Since the elements that a `foreach` loop operates over may contain `null`, it must continue to use assignment (not decomposition) semantics.

**Comment by KrisVandermotten** [comment]
I really dislike the idea the the if branch and the else branch of an if statement do not live in the same scope.

In C# 6, the statement

    if ( expr )
    {
        statement1;
    }
    else
    {
        statement2;
    }

can always legally be transformed into

    if ( ! ( expr ) )
    {
        statement2;
    }
    else
    {
        statement1;
    }

no matter wat expr, statement1 of statement2 really are.

Under the proposed scoping rules, that would no longer be the case.

That looks very weird to me.

Like many others, I like to test my inputs as soon as possible, throwing an exception when they are wrong, afterwards writing the code processing them when they are ok. So I would like to be able to write something like:

    if (!(x is int i))
    {
         throw new Exception("...")
    }
    else
    {
        // use i
    }

The alternative today works, but requires a redundant cast:

    if (!(x is int))
    {
         throw new Exception("...")
    }
    else
    {
        int i = (int) x;
        // use i
    }

**Comment by alrz** [comment]
@gafter thanks for explanation. but will tuples continue to use the underlying reference type `System.Tuple` (which is also used by F# and as discussed [here](http://stackoverflow.com/a/5856728) it wasn't a good decision)? otherwise, being `null` wouldn't be the problem.

**Comment by gafter** [comment]
@alrz No, tuples are likely to be value types. But since the semantics of the `foreach` loop will continue to use assignment semantics, that won't make any different for that use case.

**Comment by gafter** [comment]
@KrisVandermotten We are discussing a decomposition statement, something like

`let Pattern = expression;`

in which the match must be statically verifiable (the compiler can prove it always succeeds), and variables from the pattern are introduced into the enclosing scope. If the match can fail you'd use this form:

`let Pattern = expression else statement`

In either form there is an optional `where expression` clause after the expression.

This is perfect for the early error detection cases. Your example would be written

```cs
let int i = x else throw new Exception("...");
```
