### ISSUE TITLE
Generating overrides doesn't add the [AllowNull] attribute on properties

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#47828]
**Version Used**:  `3.8.0-3.20458.6 (b446afd3)`. Language version: 9.0. VS 16.8.0 Preview 3.0

**Steps to Reproduce**:

````
#nullable enable
class Demo : System.IO.TextWriter
{
    override NewLine // let VS generate the code using Tab
}
````

**Expected Behavior**:

It should generate the following code to match the original signature (https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs#L119-L133)

````
[AllowNull]
public override string NewLine
{
    get => base.NewLine;
    set => base.NewLine = value;
}
````

**Actual Behavior**:

It doesn't add the `[AllowNull]` attribute, so the compiler reports the warning CS8765

````
public override string NewLine { get => base.NewLine; set => base.NewLine = value; }
````

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
