### ISSUE TITLE
Generate operation blocks for implicit code

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#47829]
Currently callbacks aren't triggered for implicit operations, for example auto properties, or primary constructors of records, which means operation based analyzers can't reason about that code.

This causes issues like https://github.com/dotnet/roslyn/issues/47142 and https://github.com/dotnet/roslyn/issues/46132 and would provide an easy way to provide additional analysis like https://github.com/dotnet/roslyn/issues/47666.

There are also workarounds like having Remove Unused Parameters simply ignore all record primary constructors out of hand, that would be unnecessary.

**Comment by jcouv** [comment]
@AlekseyTs to confirm desired design and as FYI.

**Comment by AlekseyTs** [comment]
This is 'By Design', implicit code doesn't have associated IOperation nodes
