### ISSUE TITLE
Unreported unused private field

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#47823]
**Version Used**: 

Version 16.8.0 Preview 4.0 [30514.8.main]

**Steps to Reproduce**:

Checkout dotnet/roslyn @ ed2982191a7db2358ae97231b995e792b0eb9a6a. Build. 

**Expected Behavior**:

```
src\EditorFeatures\Core\FindUsages\AbstractFindUsagesService.cs(13,44): warning IDE0052: Private member 'AbstractFindUsagesService._threadingContext' can be removed as the value assigned to it is never read.
```

**Actual Behavior**:

No diagnostic.

**Comment by CyrusNajmabadi** [comment]
Closing out as this was rewritten.
