### ISSUE TITLE
[Generators] Generators run in the context of the IDE don't copy their dependencies

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/roslyn#47824]
**Version Used**: 16.8 Pre 3

**Steps to Reproduce**:

1. Create an analyzer that depends on an additional assembly
2. Build and use the analyzer

**Expected Behavior**:

The IDE and intellisense pick up the changes.

**Actual Behavior**:

The analyzer fails to load properly because of a missing DLL, because the IDE moves the analyzer assembly to a temporary location, without the dependency. (e.g.  `file:///C:\Users\xx\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\8737209f7d6e4328a4b6095c319d8520\1\Uno.Core.dll`)

**Comment by sharwell** [comment]
An example of this can be seen in #47275. You need the `GetDependencyTargetPaths` target hooked up to provide the dependencies to the project system.
