### ISSUE TITLE
VB consumer of a C# record

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47843]
Defining a function called "Clone" in a C# record generates `error CS8859: Members named 'Clone' are disallowed in records.`. However, a lower case "clone" is allowed.

Given that VB is case insensitive, I *think* it should produce the following error - or another similar error (haven't tested though):

https://github.com/dotnet/roslyn/blob/f4f3aa7ce76f187713d121fff2c57fca98d955e1/src/Compilers/VisualBasic/Portable/Errors/Errors.vb#L966

Is this behavior desired? or should "Clone" be completely disallowed (case insensitively), to make sure it's always callable from VB code?

**Comment by CyrusNajmabadi** [comment]
c# is not case sensitive.  Having a lower case `clone` member is fine.  C# does not prevent people from writing types that are not consumable from other .net languages with different semantics from it.

**Comment by Youssef1313** [comment]
What about an analyzer that says for example.

> Members '{0}' and '{1}' differs only in casing. They can't be consumed from Visual Basic.

That would be much more general than record's Clone.

**Comment by CyrusNajmabadi** [comment]
I don't see why we'd need that analyzer or write it now.  This has always been the way the language has worked.  If someone wants such an analyzer for their code, i imagine they can write it.  It may already be available in StyleCop or some other analyzer lib.

**Comment by CyrusNajmabadi** [comment]
It looks like https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1708?view=vs-2019 already exists.  I'm going to close this out as covered by this external tool.

**Comment by CyrusNajmabadi** [comment]
If you want, i can port this to roslyn-analyzers as this may fall under their bucket for that rule.

**Comment by Youssef1313** [comment]
yea I think this analyzer may be extended.
