### ISSUE TITLE
MissingFieldException on record types with consts

### ISSUE THREAD

**Issue by nordseth** [dotnet/roslyn#47867]
### Description

A record type with a public const field, throws _MissingFieldException_ when calling _ToString()_

```
public record RecordTypeWithConst(int Id, string Value)
{
    public const string SomeString = "1234";
}
```

I would expect the ToString() method to ignore the the const.

### Configuration

Visual studio 16.8.0 preview 3.0, with dotnet 5.0 rc 1 on windows 10.

### Other information

threw exception: 
System.MissingFieldException: Field not found: 'RecordTypeWithConst.SomeString'.

Stack Trace: 
    RecordTypeWithConst.PrintMembers(StringBuilder builder)
    RecordTypeWithConst.ToString()

**Comment by Youssef1313** [comment]
I can repro without even calling `.ToString()`. However, the stack trace for some reason shows ToString is being called and shows PrintMembers at the top of the stack.

[SharpLab repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8A3CBAAgoF5zM4B3cgJQAoBKAbgFgAoXgAQDMlOAGMA9ghzN2vAN69yS8kPITMscgEtMMcgGFyNAAzceAXyA).

**Comment by Youssef1313** [comment]
An observation:

|OutputKind|Calling just `new R()`|Calling `.ToString()` after `new R()`|SharpLab repro|
|-----------|----------------------|---------------------------------|----------------|
| Debug     |MissingFieldException| Trivially, the same MissingFieldException|[Repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABARgDoyBOACgCIAhOAMwHsE4ACAYxnboCUAbgCwAKABuEBJxkBeTpjgB3TgCUaw8WUqladAILN4M3vy1jtAZllxu7HOs3iA3uM4fOxG/cyxOAJaYMJwAwpwKAAyiYgC+QA)|
|Release   |Runs without exception|MissingFieldException happens|[Repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AECMAdAQJwAUARAEJwBmA9gnAAQDGMjFAlANwCwAKABuEBMzEBeZpjgB3ZgCUyvQQHpVzAKqZW9MGDiYYzGAAsWDADaX6sgJaYA5ifrMocFnAAerOAAcYO3pMNVUEQgAVegBlGAQHR2V+AQJifHIKAEFaeDF2ThUBQVwAZnE4XQQAE0VlQQBvQWZm5lK2YNhmB2MAYWYpAAZkgF8gA===)|
