### ISSUE TITLE
The dotted line aligned with curly braces won't show on records

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/roslyn#47889]
**Version Used**: 
VS 16.7.3

**Steps to Reproduce**:

Normal classes:
![](https://ftp.bmp.ovh/imgs/2020/09/04017b3512871dbf.png)

```csharp
public sealed class FileCounter
{
    // ...
}
```

![](https://ftp.bmp.ovh/imgs/2020/09/e4f9b199272f9c03.png)

```csharp
public sealed record FileCounterResult(int Property1, bool Property2)
{
    // ...
}
```

**Expected Behavior**:
Both two types of statements, the dotted line should show.

**Actual Behavior**:
As the pictures above, when wrote `class`es, the dotted lines show, while `record`s don't show dotted lines.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/47894
