### ISSUE TITLE
[Quick fix] Suggest " use 'foreach' instead of 'for' " , when a for contains 'in' keyword

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#47886]
Hello,

it would be nice, when roslyn would suggest
`use 'foreach' instead of 'for'`

on a `for` that contains the `in` keyword, like
```cs
for(var singleKey in subKeys)
{

}
```

Currently it only suggest
* `convert to for`
* `use explicit type`

<img width="396" alt="2020-09-21 13_46_48-RegExtSearchMockup - Microsoft Visual Studio Preview" src="https://user-images.githubusercontent.com/17874713/93763106-25615200-fc11-11ea-8c0e-2ec37977a2b1.png">

**Comment by CyrusNajmabadi** [comment]
I'm not really a fan of code actions that don't substantively speed up the experience.  i.e. you're already on the error.  Fixing it is only typing 3 chars.  Intellisense is also pretty much just as fst, as you can hit ctrl-space, then select `foreach` and complete:

![image](https://user-images.githubusercontent.com/4564579/93799071-7c582e80-fbf3-11ea-953d-177b9951aa4e.png)

It does not feel like this warrants a dedicate fix.
