### ISSUE TITLE
How to tell the analyzer to ignore generated code?

### ISSUE THREAD

**Issue by DasOhmoff** [dotnet/roslyn#47884]
Hello, I wrote a custom code analyzer and it runs on my solution code, but it also runs on generated code.
For example when `AssemblyInfo.cs` files get generated, my analyzer also analyzes these files and throws warnings inside of them. How can I tell my custom analyzer to not analyze generated code?

I know I could add something like this into my `.editorconfig`:
```
[*.{AssemblyAttributes.cs,AssemblyInfo.cs}]
generated_code = true
dotnet_diagnostic.***.severity = none
...
```
But is there a better way to do it?

**Comment by Youssef1313** [comment]
You can do that using `ConfigureGeneratedCodeAnalysis` on the `AnalysisContext` (that is the parameter of the `Initialize` method)

**Comment by DasOhmoff** [comment]
Thank you, this is exactly what I needed!
