### ISSUE TITLE
Support multiple runtimes (.NET Framework and .NET Core) in Interactive Window

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#4788]
We need to distinguish between environment definition (32bit vs 64bit, Desktop/CoreCLR, which version of CoreCLR, etc.) and initialization script.

I propose following:

1)  #reset noinit
Resets to the most recently used environment without running initialization script (using “noinit” instead of “noconfig” since it’s a better name).
2)  #reset
Resets to the most recently used environment and runs the default initialization script (if any).
3)  #reset noinit “environment”
Resets to the specified environment without running initialization script.
4)  #reset “environment”
Resets to the specified environment and runs the default initialization script.

The #reset command prints out info about the environment being loaded.

Environment is a file name or a path. If an extension isn’t specified we append extension “.json”. If the path is relative we search in some predefined folder in user home directory and then in the installation directory in the interactive host.
The .json file will describe the environment in JSON format. I think we should move away from .rsp file for REPL initialization since it’s not flexible enough.

``` json
dnx32.json
{
  "host": 
  { 
    "package": "DNX.4.0.0-beta-23109"
    "platform": "x86"
    "loader": "dnx.exe"
  }
}

clr64.json
{
  "host": "InteractiveHost64.exe"
}

default.json
{
  "host": "InteractiveHost32.exe"
}
```

An optional initialization script is of the same name but with .csx/.vbx extension. For example:

dnx32.csx:

``` C#
#load “dnx_common.csx”
```

dnx64.csx

``` C#
#load “dnx_common.csx”
```

dnx_common.csx:

``` C#
#r “System.Runtime”
#r “System.Threading.Tasks”
...
```

Sample session:

``` C#
> #reset default
Loading CLR (32bit), initializing with “default.csx”. 

> #reset
Loading CLR (32bit), initializing with “clr32.csx”.

> #reset noinit
Loading CLR (32bit).

> #reset dnx32
Loading DNX v4.0.0-beta-23109 (32bit), initializing with “dnx32.csx”.

> #reset “C:\MyEnvironment.json” noinit
Loading DNX v5.0.0-custom-build-foo (64bit).

> #reset
Loading DNX v5.0.0-custom-build-foo (64bit), initializing with “C:\MyEnvironment.csx”.
```

**Comment by tmat** [comment]
Consider reading environment init scripts and config from user home dir.

**Comment by tmat** [comment]
We are gonna use the Core CLR that are found using VS process environment variables.
