### ISSUE TITLE
Anonymous function that captures no outer variables is not static

### ISSUE THREAD

**Issue by Sb87** [dotnet/roslyn#4793]
In VS2013, an anonymous function that captures no outer variables is compiled as a static method. In VS2015, it is non-static. This is a breaking change for our code. Test case:

    using System;
    using System.Linq.Expressions;

    namespace AnonymousMethodStaticTest
    {
      class Program
      {
        static void Main(string[] args)
        {
          Console.WriteLine("Testing method");
          CallAction(Method);

          Console.WriteLine("Testing anonymous function");
          Action action = () => { };
          CallAction(action);
        }

        static void Method()
        {
        }

        static void CallAction(Action action)
        {
          Console.WriteLine(action.Method.IsStatic);

          try
          {
            Expression callExpression = Expression.Call(action.Method);
          }
          catch
          {
            Console.WriteLine("Exception occurred because action.Method.IsStatic == false");
          }
        }
      }
    }

In VS2013, this produces:
> Testing method
> True
> Testing anonymous function
> True

In VS2015, this produces:
> Testing method
> True
> Testing anonymous function
> False
> Exception occurred because action.Method.IsStatic == false

Expected: VS2015 output should match VS2013 output.

**Comment by mikedn** [comment]
The C# specification doesn't say whether the methods generated from lambda expressions are static or not, code which assumes either is wrong.

**Comment by Sb87** [comment]
It is true the spec doesn't mandate the implementation details of this feature. However, I was curious whether the Rosyln team values backward compatibility enough to fix this case, or at least document it.

**Comment by MrJul** [comment]
They shouldn't documente it, or it implicitly becomes a contract, which was never the case: it's only an implementation detail you shouldn't rely on.

Regarding the change, it was likely done for performance reasons, as seen in [this StackOverflow answer](http://stackoverflow.com/a/30901679/183367).

**Comment by mikedn** [comment]
Well, they should not document the current behavior but they should document the change in behavior. Currently, one of the [places](https://msdn.microsoft.com/en-us/library/hh678682.aspx) where you would hope to find a list of such breaking changes wasn't updated for VS2015.

**Comment by ltrzesniewski** [comment]
I also had an issue with my weak events implementation. I make sure the event handlers are static as a sanity check, and I'd rather keep that in place for memory leak prevention.

My workaround was to check if the delegate's target is `null` or if its type is named `<>c`.
That's *pretty* ugly, but it seems to be reliable *so far*.

Here's some test code in case you're interested:

```C#
internal class Test
{
    private int _dummy;
    private static int _dummyStatic;

    public void Run()
    {
        ExpectStatic((Action)StaticMethod, true);
        ExpectStatic(GetStatic(), true);

        ExpectStatic(GetInstance(), false);
        ExpectStatic(GetClosure(), false);

        Console.WriteLine("OK");
    }

    public static void ExpectStatic(Delegate action, bool shouldBeStatic)
    {
        var isStatic = action.Target == null || action.Target.GetType().Name == "<>c";

        if (isStatic != shouldBeStatic)
            throw new InvalidOperationException();
    }

    private static void StaticMethod()
    {
        ++_dummyStatic;
    }

    private Action GetStatic()
    {
        return () => ++_dummyStatic;
    }

    private Action GetInstance()
    {
        return () => ++_dummy;
    }

    private Action GetClosure()
    {
        var dummy = 0;
        return () => ++dummy;
    }
}
```

**Comment by tmat** [comment]
@ltrzesniewski Please, don't rely on names of compiler-generated methods. We might change them in future.

**Comment by ltrzesniewski** [comment]
@tmat I'm aware of that, but I needed a quick way to fix existing code, and I'm not happy about this workaround either. 
Is there a better solution to quickly detect if a lambda captures anything?

**Comment by tmat** [comment]
@ltrzesniewski I assume your goal is to avoid bugs in your code, correct? If so, I'd recommend a solution that detects the issues while you are typing code as well as while your project is built. With Roslyn and VS 2015 we provide a supported framework for writing such detection logic in form of custom analyzers that plug into the compilers.

See https://github.com/dotnet/roslyn/blob/master/docs/samples/csharp-diag.pdf for a sample and feel free to contact us should you have any questions.

**Comment by ltrzesniewski** [comment]
@tmat Thanks for the suggestion - that's a *much* better solution. I supposed writing a Roslyn analyzer was possible for this, but I wasn't aware you could distribute them with NuGet, and force the compiler to emit an error. I'll certainly look into it.

I'll leave the check as-is for now (at least until I figure out how to write the diagnostic) - it's in our internal code, and if you rename `<>c` one day or change the mechanism it'll fail unit tests on our build server. That's how I noticed the change in the first place.

**Comment by gafter** [comment]
We'll add a note about this change to https://github.com/dotnet/roslyn/tree/master/docs/compilers .

**Comment by tibel** [comment]
It seems that this issue was reported already:
https://roslyn.codeplex.com/workitem/246

I think the suggestion of @tmat (create a Roslyn analyzer) is the way to go.

This is what came into my mind:
``` C#
void Method1([EmptyCapture] Action<int> action) { }

Method1(i => { }); // OK
Method1(SomeClass.StaticMethod); // OK

int captured_variable;
Method1(i => { captured_variable = i; }); // ERROR
Method1(someInstance.InstanceMethod); // ERROR
```

**Comment by steffenloesch** [comment]
Is there a 'supported' run-time check that can be done with VS2015, to see if a delegated created by a lambda is static in the sense that it captures no outer variables? I'm looking for the equivalent of @ltrzesniewski 's `ExpectStatic` above, but one that is not as brittle.

Background: The Analyzer solution described @tmat above is nice, but it also has its drawbacks. For example, it is harder to implement (compared to the run-time check `delegate.Target == null` with VS2013), especially if you're working with an existing codebase that uses the run-time check.

**Comment by tmat** [comment]
@steffenloesch What would exactly be the purpose of such checking?

**Comment by tmat** [comment]
BTW, it's true that writing an analyzer is more work. However, it only needs to be written once and everyone can then use it.

**Comment by steffenloesch** [comment]
@tmat Sometimes it makes sense to restrict APIs to static delegates, that do not hold a reference to an object, and thereby don't get in the way of garbage collection. That seems to be the case for @ltrzesniewski 's project above, for the project described [here](http://roslyn.codeplex.com/workitem/246), and it is the case for the project that I'm currently working on. In that sense, any lambda that can be made a static method by just giving it a name, should count as static, and it would be nice to keep a run-time check for that.

An `IsStatic` method for delegates also only needs to be written once, can then be reused by everyone ;-) Don't get me wrong, I'm very much in favor of checking as much as possible at compile-time, but sometimes a run-time check makes more sense. In our case, I'm thinking of scenarios where you get passed a delegate from an external source to whose source code you don't have access to.

**Comment by steffenloesch** [comment]
Follow-up question: Are 'static' lambdas and 'static' anonymous methods (in the sense that they can be converted to static methods by giving them a name) the only cases for which the type of a delegate target is compiler-generated? If that's the case, then we could do something like this for a run-time check: 
```c#
public static bool IsStatic(Delegate del)
{
    return del.Target == null ||
        del.Target.GetType().GetCustomAttributes().OfType<CompilerGeneratedAttribute>().Any();
}
```
It's doing the right thing for all of my examples. This solution seems a bit more stable under compiler changes than checking the name of the generated type.

**Comment by tmat** [comment]
@steffenloesch I would not rely on that. 

The best thing I can think of is to reflect over the type and look for instance fields. But I would still prefer the analyzer :)

**Comment by gafter** [comment]
This is documented at https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CodeGen%20Differences.md

>

**Comment by tibel** [comment]
This request was created after roslyn release and simply states:
- it would be great to have runtime info that a lambda does not capture context
- it would be great to have a roslyn analyzer to check that a lambda does not capture context at compile time

@gafter We knew that already. Can you explain why you closed this feature request? Pointing to the documentation is not a reason.

**Comment by gafter** [comment]
Because the Roslyn repo is not the place to request new analyzers. The question is answered.

**Comment by steffenloesch** [comment]
I wasn't aware of that documentation, thanks for pointing it out @gafter.

While an analyzer would be nice, I still think that it would be better to have a run-time property on delegates that tells you if the delegate has an empty capture or not. I think an analyzer for that would not catch all scenarios in which such a property would be helpful. Is this the right place to post a feature request for that?

**Comment by svick** [comment]
@steffenloesch I don't see how would that work. A delegate doesn't know anything about lambdas or captured variables.

Also, different languages emit lambdas differently (I believe F# uses its own approach).

**Comment by steffenloesch** [comment]
@svick Yes, a delegate could come from an instance method or static method too, for those the convention could be that the result of the 'empty capture property' is always false, or alternatively the result of `delegate.Target == null`. Capture-wise, delegates coming from anonymous methods should be treated the same way as delegates coming from lambdas. How you would implement that all is a different question. It might be complicated (and not worth it, not up to me to judge...), but a simple approach could be to have an additional boolean field. The compiler (for any language) certainly has enough knowledge at the point when it emits the IL for the delegate in question.

**Comment by OndrejPetrzilka** [comment]
I'm would prefer test similar to this:

`handler.Target.GetType().HasAttribute<CompilerGeneratedClosure>()`

It can be attribute, it can be member/flag of `CompilerGeneratedAttribute`, it doesn't really matter as long as it can be checked. On Debug, I use similar test as mentioned above to detect when I accidentally pass closure instead of anonymous function.

**Comment by rjamesnw** [comment]
As of C# 6, lambdas now default to instance methods, and will never be static.

This causes issues now with using lambdas when creating static MethodInfos for calls to expression methods such as Expression.Convert(Expression, typeof({SomeType}), conversionMethodInfo);

So then, what is the new way of doing this? I tried to use the "static" modifier with lambdas and it doesn't work.

**Comment by svick** [comment]
@rjamesnw Why are you using `Expression.Convert` along with `MethodInfo` from a lambda? Could you switch either to `Expression.Invoke`/`Expression.Call` or to using an actual `static` method for the `MethodInfo`?

**Comment by rjamesnw** [comment]
It's complicated,  lol. It was code from over a year ago I'm trying to fix now.  I'm already calling Expressiom.Call(), and "self" needs to be converted to another type. This is now the new way I have it working:

```
public override DynamicMetaObject BindSetMember(SetMemberBinder binder, DynamicMetaObject value)
        {
            if (!_Handle.IsObjectType) throw new InvalidOperationException(InternalHandle._NOT_AN_OBJECT_ERRORMSG);

            var isHandleBase = typeof(IHandleBased).IsAssignableFrom(value.RuntimeType);

            Expression[] args = new Expression[isHandleBase ? 3 : 5];
            MethodInfo methodInfo;

            // ... create parameters for the call expression to set a value given a property name ...

            args[0] = Expression.Constant(binder.Name);

            if (isHandleBase) // (if the interface is implemented, then we need a converter to detect and pull out the handle value)
            {
                Func<object, InternalHandle> handleParamConversion
                    = obj => (obj is IHandleBased) ? ((IHandleBased)obj).InternalHandle
                        : _Engine != null ? _Engine.CreateValue(obj)
                        : InternalHandle.Empty;

                var convertParameter = Expression.Call(
                    Expression.Constant(handleParamConversion.Target),
                    handleParamConversion.Method,
                    Expression.Convert(value.Expression, typeof(object)));

                args[1] = convertParameter;
                args[2] = Expression.Constant(V8PropertyAttributes.None);

                methodInfo = ((Func<string, InternalHandle, V8PropertyAttributes, bool>)_Handle.SetProperty).Method;
            }
            else // (no interface is implemented, so default to just 'object')
            {
                args[1] = Expression.Convert(value.Expression, typeof(object));
                args[2] = Expression.Constant(null, typeof(string));
                args[3] = Expression.Constant(null, typeof(Nullable<bool>));
                args[4] = Expression.Constant(null, typeof(Nullable<ScriptMemberSecurity>));
                methodInfo = ((Func<string, object, string, bool?, ScriptMemberSecurity?, bool>)_Handle.SetProperty).Method;
            }

            Func<object, InternalHandle> conversionDelegate = _ConvertObjectToHandle;
            Expression self = Expression.Convert(Expression, typeof(InternalHandle), conversionDelegate.Method);

            Expression methodCall = Expression.Call(self, methodInfo, args);

            BindingRestrictions restrictions = Restrictions.Merge(value.Restrictions);

            return new DynamicMetaObject(Expression.Convert(methodCall, binder.ReturnType), restrictions);
        }

    (and in the class)
    static InternalHandle _ConvertObjectToHandle(object obj) => (obj as IHandleBased)?.InternalHandle ?? InternalHandle.Empty;
```
