### ISSUE TITLE
Intellisense does not suggest Equals, GetHashCode, or ToString as suggestions for override on records

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#47941]
**Version Used**:

* Visual Studio 2019 16.8.0 Preview 3.1
* Compiler version: '3.8.0-4.20472.6 (1e60b393)'. Language version: preview.
* ,NET SDK 5.0.100-rc.1.20452.10

**Steps to Reproduce**:

Given the following code with the cursor at the location of `$$`, invoke Intellisense (IE: Ctrl+Space)

```csharp
abstract record RecordA // This record is only present so that Intellisense shows *something* for the override suggestions
{
    public abstract void Test1();
    public abstract void Test2();
}

record RecordB : RecordA
{
    override $$
}
```

**Expected Behavior**:

Intellisense suggests `Equals`, `GetHashCode`, `Test1`, `Test2`, and `ToString` as possible methods to override. Same as if classes were used instead:

![image](https://user-images.githubusercontent.com/278957/93911083-8f3c3300-fcc7-11ea-80ec-b4093496c6f3.png)

**Actual Behavior**:

Only `Test1` and `Test2` are suggested despite being able to override the other three:

![image](https://user-images.githubusercontent.com/278957/93911119-9d8a4f00-fcc7-11ea-9ac4-56a5d6974ff9.png)

-------------

This presumably because the compiler already thinks they're overridden since the synthetic methods are overriding them, but this breaks muscle memory for overriding methods when you want to override them manually.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/f9fed067fb225a039d70ddfdbc604a96ab3ab253/src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.ItemGetter.cs#L129-L144

Probably `GetOverridableMembers` isn't working as expected? Will need to debug

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by Youssef1313** [comment]
This should have been fixed with #47954

**Comment by PathogenDavid** [comment]
Can confirm this was fixed by #47954, thanks @CyrusNajmabadi!

Unfortunately it had an unintended side-effect, the unspeakable `<Clone>$` method is suggested now:

![image](https://user-images.githubusercontent.com/278957/94013829-42606700-fd70-11ea-93fb-e6c6cccac09d.png)

**Comment by PathogenDavid** [comment]
This only happens when the record extends another record:

![image](https://user-images.githubusercontent.com/278957/94013973-80f62180-fd70-11ea-98a4-205117d5bf25.png)

**Comment by PathogenDavid** [comment]
Created #47973 to track this new issue. Closing this one since it was fixed.

**Comment by albahari** [comment]
This appears to be broken again. While is suggests members such as Test1() and Test2() in the override list, it no longer suggests GetHashCode() or ToString(), which can be legally overridden in records.

**Comment by CyrusNajmabadi** [comment]
@albahari I don't repro this:

![image](https://user-images.githubusercontent.com/4564579/96278841-da75f880-0f8a-11eb-9471-4604dca20cc5.png)

![image](https://user-images.githubusercontent.com/4564579/96278890-e792e780-0f8a-11eb-9226-bbafbe339b26.png)

If you have a repro for this, please open a new issue with the code where you're seeing htis.

**Comment by sharwell** [comment]
@albahari Note that this is first fixed in 16.9 Preview 1, which is not yet publicly available.

**Comment by albahari** [comment]
Seems you're on top of it. Although, looking at that listing, you probably don't want Equals(object? obj) in there, although that's a very minor issue.

**Comment by PathogenDavid** [comment]
> you probably don't want Equals(object? obj) in there

That's covered by https://github.com/dotnet/roslyn/issues/48640
