### ISSUE TITLE
TypeKind enum documentation does not indicate the value for records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47946]
https://github.com/dotnet/roslyn/blob/438047c55d476191fc5cb3df5f02925418139f1d/src/Compilers/Core/Portable/Symbols/TypeKind.cs#L9-L88

`TypeKind` doesn't contain a member called "Record". If this falls under TypeKind.Class, the documentation should reflect this. Otherwise, there should be a remarks section on `TypeKind` enum to clarify what's the case with records.

**Comment by PathogenDavid** [comment]
This is sort-of a duplicate of https://github.com/dotnet/roslyn/issues/47713

**Comment by Youssef1313** [comment]
@PathogenDavid That depends on how #47713 will be fixed :smile:

If it's fixed by introducing a new `TypeKind` for `Record`, it'll be a duplicate.

Otherwise, it's still a documentation problem if `Record` falls under `TypeKind.Class` but the documentation doesn't say that.

**Comment by Youssef1313** [comment]
Closing per discussion in #52191.
