### ISSUE TITLE
Refactoring: Generate record default GetHashCode and Equals methods

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#47969]
In case you want to exclude or change a single member from equality we need to fully redefine GetHashCode and Equals on records.

An IDE feature could generate the default impl so it can be further modified by user.

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi for info

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
