### ISSUE TITLE
"IDE0041 Null check can be simplified" ignores generic type constraint when deciding between 'is null' and '== null'.

### ISSUE THREAD

**Issue by DoktorDemento** [dotnet/roslyn#47972]
**Steps to Reproduce**:

1. Define a class with an overridden `==` operator:
```csharp
public class Example
{
    public static bool operator ==(Example left, Example right) => true;
    public static bool operator !=(Example left, Example right) => !(left == right);
    public override bool Equals(object obj) => true;
    public override int GetHashCode() => 0;
}
```

2. Define a null-checking method, with a generic parameter constrained to the `Example` class:
```csharp
public static bool IsNull<T>(T arg) where T : Example
{
    return ReferenceEquals(arg, null);
}
```

3. Apply the IDE0041 suggested fix to it.

**Expected Behaviour**:

The fix should use `is null`, as it does if the method is not generic and the argument is typed as `Example`:
```csharp
public static bool IsNull(Example arg)
{
    return arg is null;
}
```
'Compiling' the C# using SharpLab shows that this is interpreted as `(object)arg == null`, which avoids using the overridden `==` operator.

**Actual Behaviour**

```csharp
public static bool IsNull<T>(T arg) where T : Example
{
    return arg == null;
}
```
The fix uses `== null`, which is a call to the overridden `==` operator and not equivalent (especially in this slightly contrived case) to `ReferenceEquals(arg, null)`.

**Comment by huoyaoyuan** [comment]
This is an interesting mixture of two facts.

First, unconstrained generic type supports `is null` from C# 8, but the analyzer isn't updated for that.
Then, the base class constraint is mis-recognized as no reference type constraint.
