### ISSUE TITLE
Source generators doesn't work without useful diagnostics

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#47980]
## Repro steps

1. `git clone https://github.com/Youssef1313/SourceGeneratorTest`
2. `cd SourceGeneratorTest`
3. `cd HelloWorld`
4. `dotnet build`
5. You should see the following warning:

   ```
   CSC : warning CS8032: An instance of analyzer MyGenerator.MyGenerator cannot be created from D:\Important To Me\Programming\C# Projects\SourceGeneratorTest\MyGenerator\bin\Debug\netstandard2.0\MyGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..
   ```

6. Re-run `dotnet build` again. The above warning doesn't show again. The source generator also doesn't seem to run.

## Expected Behavior

Expecting to see a compile-error since the generator intentionally generates invalid code. But the generator doesn't seem to run at all.

I don't know what's wrong so that the generator didn't execute. There is no diagnostics to clarify this.

## Summary

This issue is for 2 reasons:

- Getting support on what I'm missing to get source generator work.
- If applicable, supply a diagnostic that will help other developers who may have the same mistake as mine.

**Comment by Youssef1313** [comment]
I changed LangVersion to preview in `MyGenerator.csproj`, and also added the following to `MyGenerator.csproj`:

```
  <PropertyGroup>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json ;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
  </PropertyGroup>
```

But it's still not working.

**Comment by Youssef1313** [comment]
@chsienki Could you have a look please?

**Comment by chsienki** [comment]
@Youssef1313 It looks like a version mismatch between the generator and the runtime you're using. The newer 3.8.0 version of SourceGenerators (`GeneratorExecutionContext`) only works on .net5 rc1 and higher. What version do you get for `dotnet --version`?

The reason it doesn't occur a second time is because from MSBuilds perspective the project is up to date: it built successfully, albeit with warnings. Doing a rebuild will show the error again.

**Comment by Youssef1313** [comment]
@chsienki Thanks. I'll try with RC1 and get back with the results.

If this scenario could still be common in stable releases of .NET (e.g. a later version in future that may be supported in .NET 6 but not .NET 5), I'd love to see a warning for this.

But if this incompatible versions happen only during previews, drop my warning suggestion.

**Comment by sharwell** [comment]
> The reason it doesn't occur a second time is because from MSBuilds perspective the project is up to date: it built successfully, albeit with warnings. Doing a rebuild will show the error again.

See also https://github.com/dotnet/msbuild/issues/3046

**Comment by chsienki** [comment]
@Youssef1313 We're not expecting to take any further breaking changes going forward, so you should be good.

**Comment by Youssef1313** [comment]
@chsienki Thanks for helping. It worked after installing rc1, so I'm closing.
