### ISSUE TITLE
Target typed new - bug with constructor reference counting

### ISSUE THREAD

**Issue by SirIntruder** [dotnet/roslyn#47987]
**Version Used**: 
VS 16.8 latest

**Steps to Reproduce**:
Bug can be reproduced in a minimal console project. Just add code like this:
![2020-09-23_22-44-51](https://user-images.githubusercontent.com/5102661/94067956-da9d3100-fdee-11ea-9fa9-daed944a1400.png)

Bug triggers if some class "Foo" has any field initializer with target typed new syntax, like "Bar bar1 = new();" in the example. 

This field initializer somehow messes up reference counting in the "Foo" constructor body, so all of the constructor references are counted twice (one for new, one for identifier name, check highlights in the screenshot).  

Double counting ceases immediately after field initializer "Bar bar1 = new();" is replaced with the old syntax "Bar bar = new Bar();"

**Comment by CyrusNajmabadi** [comment]
@jcouv ?

**Comment by jcouv** [comment]
FYI @alrz 
I'll take a look at this later next week.

**Comment by eriawan** [comment]
This is a strange bug. I can always reproduce this on 16.8.0 preview 3.
It seems there's a difference in semantic when facing `new();` and `new Bar();`.

**Comment by alrz** [comment]
Indeed. Looks like `new Bar()` counts as two references *only* if there is a `new()` usage.

**Comment by CyrusNajmabadi** [comment]
@alrz can you ping me when you have a chance through gitter/discord/etc?  thanks!

**Comment by Youssef1313** [comment]
I'll work on this.
