### ISSUE TITLE
Change signature - Add parameter colorizes preview incorrectly

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#47986]
Adding a parameter in the change signature dialog may cause incorrect preview colors. For example, in the screenshot below, S is a struct but the added parameter is colorized like a class:

![changesigpreview](https://user-images.githubusercontent.com/16968319/94055816-51581100-fd92-11ea-899d-c679a03f1a75.png)

**Comment by CyrusNajmabadi** [comment]
CLosing as we are not investing in these one-off UI experiences.
