### ISSUE TITLE
IDE0032 fixer should strip readonly keyword from properties

### ISSUE THREAD

**Issue by Naine** [dotnet/roslyn#47999]
The code fix provider for IDE0032 (use auto-property) produces invalid code when faced with C# 8 readonly instance members.

**Version Used**: 3.7.0-6.20459.4 (7ee7c540), Visual Studio 16.7.4

**Steps to Reproduce**:

1. Minimal reproduction:

```csharp
struct IDE0032
{
    private int x;
    public readonly int X => x;
    public void SetX(int value) => x = value; // ensures the produced auto-property is settable
}
```

2. IDE0032 will be reported on `x`. Apply the "Use auto property" code fix.

**Expected Behavior**:

```csharp
struct IDE0032
{
    public int X { get; private set; }
    public void SetX(int value) => X = value;
}
```

**Actual Behavior**:

```csharp
struct IDE0032
{
    public readonly int X { get; private set; } // CS8659: Auto-implemented property 'IDE0032.X' cannot be marked 'readonly' because it has a 'set' accessor.
    public void SetX(int value) => X = value;
}
```

**Comment by louis-z** [comment]
I'd like to take a stab at fixing this.

**Comment by CyrusNajmabadi** [comment]
@louis-z go for it! :-)
