### ISSUE TITLE
SyntaxGenerator.GetStatements returns 0 for expression-bodied member

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#48009]
**Version Used**: 

**Steps to Reproduce**:

https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/ConfigureGeneratedCodeAnalysisFix.cs#L68

**Expected Behavior**: Returns 1 statement.

**Actual Behavior**: Returns 0 statement.

**Comment by CyrusNajmabadi** [comment]
This is by design. There is literally no statement to return. :-)

**Comment by Evangelink** [comment]
@CyrusNajmabadi So what's the recommended way to retrieve the method statement for a code-fix? Are you forced to always rely on a c# specific implementation?

**Comment by CyrusNajmabadi** [comment]
You can use `GetExpression` to get that.  Cheers!

**Comment by Evangelink** [comment]
I saw this but it returns `null` for the `MethodDeclarationSyntax` node...

**Comment by CyrusNajmabadi** [comment]
I can't explain that given: https://github.com/dotnet/roslyn/blob/050d32d8eeabe34653f8bf35da0fa07bb06eb067/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L2227-L2232

Can you debug through to see why this isn't giving you an appropriate node?

**Comment by Evangelink** [comment]
That sucks that step into doesn't get to the roslyn source code... I'll try to create a test case directly from roslyn source code.

![image](https://user-images.githubusercontent.com/11340282/94204147-02f56000-fec1-11ea-8f8d-d061c2415cf4.png)

**Comment by CyrusNajmabadi** [comment]
Ah, i see the issue.  That functionality was added in https://github.com/dotnet/roslyn/pull/45913/files#diff-934b9f5484d144dfc441ebbef66604f4R2233 .  So until that flows out into a new release, you won't get that behavior.  For now, you'll have to go back to syntax.

**Comment by Evangelink** [comment]
Oh I see, I got fooled by the version. Thanks for digging into it!
