### ISSUE TITLE
WRN_GeneratorFailedDuringGeneration isn't helpful without a StackTrace

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48008]
I currently have a source generator that fails with:

```csharp
CSC : warning CS8785: Generator 'MySourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.'
```

I think providing a StackTrace will be very useful.

**Comment by RikkiGibson** [comment]
Tagging @chsienki

**Comment by jaredpar** [comment]
@chsienki @mavasani 

Is there a reason we don't include the stack trace of the exception in the diagnostics for source generators or analyzers?

**Comment by chsienki** [comment]
@jaredpar Its twofold: 

1. We're supposed to show the stack trace on the 'expand' part of the error in VS, but for whatever reason that doesn't work.
2. Exceptions aren't serializable. That means that we have to 'realize' the exception when it occurs (not when we report it) and means we can't correctly localize the values in it, like for other errors.

https://github.com/dotnet/roslyn/issues/46939 is tracking addressing this.

**Comment by mavasani** [comment]
I believe @sharwell added this support for analyzers with https://github.com/dotnet/roslyn/pull/35871. I think I recall the exception being available in logs only when using MSBuild's diagnostic or detailed verbosity, but Sam would know for sure.

**Comment by mavasani** [comment]
> We're supposed to show the stack trace on the 'expand' part of the error in VS, but for whatever reason that doesn't work.

@chsienki Note that this specific functionality only ever worked for diagnostics from intellisense as for the build diagnostics case we do not have exception stack in the build output.

**Comment by sharwell** [comment]
The exception for analyzers is always available, but csc.exe doesn't use the MSBuild APIs that support multi-line messages so it truncates the message in practice.

**Comment by jaredpar** [comment]
Given the current state of technology what do we tell users to do when they hit this problem and want to know why their source generators don't work? 

> The exception for analyzers is always available, but csc.exe doesn't use the MSBuild APIs that support multi-line messages so it truncates the message in practice.

Can we get some more information on this?

**Comment by jaredpar** [comment]
@sharwell 

> Can we get some more information on this?

**Comment by agocke** [comment]
Still regularly hitting this when working with previews. Unfortunately exception messages like the following are not really helpful: `Exception was of type 'ArgumentNullException' with message 'Value cannot be null. (Parameter 'format')'`

**Comment by sharwell** [comment]
> @sharwell
> 
> > Can we get some more information on this?

I'm not sure exactly why it behaves the way it does. If you open the binlog, you can see the full multi-line exception message. However, if you just build on the command line with minimal verbosity it only shows the first line.

**Comment by AbstractionsAs** [comment]
@sharwell How do you get the full exception from the binlog? I only get the short one there as well..

**Comment by sharwell** [comment]
`WRN_GeneratorFailedDuringGeneration` doesn't currently emit the stack trace. It would need to be updated the same way I updated analyzers in #35871. It's a fairly easy code change, but the tests can be very difficult to update.

**Comment by xakep139** [comment]
Folks, were there any updates on that issue?

**Comment by sharwell** [comment]
@xakep139 We don't currently have the resources to work on resolving this, but if someone submitted a pull request to implement the behavior described in https://github.com/dotnet/roslyn/issues/48008#issuecomment-1341131212 it would significantly improve the timeline for delivering this fix. 😄

**Comment by sharwell** [comment]
## Workaround

It turns out the exception _is_ printed in the "description" field of the diagnostic. This field isn't printed as part of a normal build, but if you enable SARIF output it will be included in that. You can add the following command line argument to your build:

```
/p:ErrorLog=compiler-diagnostics.sarif
```

The output file **compiler-diagnostics.sarif** will contain the text "Generator threw the following exception" followed by the exception and stack trace.
