### ISSUE TITLE
Analyzer for possible wrong Roslyn API usage, and improve exception

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48010]
I had the following code fragment:

```csharp
var statements = new SyntaxList<StatementSyntax>();
statements = statements.Add(SyntaxFactory.ReturnStatement(SyntaxFactory.LiteralExpression(SyntaxKind.TrueKeyword)));
```

It throws ArgumentOfRangeException, which was a bit unclear to me.

Suggestions:

1. Improve the exception thrown.
2. Add an analyzer to point to this mistake. I was only saved by @KirillOsenkov's RoslynQuoter to know that I should have used `SyntaxKind.TrueLiteralExpression`

I also think using:

```
statements.Add(SyntaxFactory.ReturnStatement(SyntaxFactory.LiteralExpression(SyntaxKind.TrueKeyword)));
```

is a candidate for another analyzer too. (the above line does nothing, it creates a new list which is just thrown away and not used)

**Comment by jinujoseph** [comment]
@mavasani should we move this to roslyn-analyzer repo

**Comment by mavasani** [comment]
> should we move this to roslyn-analyzer repo

I think we should keep this issue here itself. We do not have any analyzers helping correct usage of Syntax Generator/Factory APIs, but instead rely on Roslyn API itself generating good exceptions, i.e. basically `Improve the exception thrown.` request here.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and high cost of impl.
