### ISSUE TITLE
When invoking a method: optionally automatically fill in argument names & create local variables for them.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48019]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1195790/when-invoking-a-method-optionally-automatically-fi.html)._

---
<p>As the architecture in our code-bases develops, we find that method-calls are getting larger.</p> <p>Initially we had simple methods like</p><pre>someObject.SomeMethod(int someNumber, double someDouble);</pre> <p>Now we can have 20 or 30 arguments in a method call.</p> <p>So we then have to fill in numerous argument-names by hand and create local variables for them all.</p> <p>This is laborious and can easily be automated.</p> <p>I would really like it if there was some hotkey or lightbulb option for <strong>&quot;Fill in method arguments &amp; create local variables&quot;</strong>.</p> <p>So I would type</p><pre>someObject.SomeMethod(); // fails to compile, as no arguments given</pre><p>and then when the hotkey/lightbulb was used it would expand to:</p><pre>// variables created
string someString = ; // no value given, so it won't compile until completed
int someInteger = ; // ditto
double someDouble = ; // ditto
...
decimal theLastArgumment ; // ditto - maybe the 30th argument variable

// method now has arguments in place
someObject.SomeMethod(someString, someInteger, someDouble, ... , theLastArgument);</pre> <p>This would save us lots of time and enable us to focus on business logic rather than boilerplate.</p> <p>I suspect it would be quite easy, too.</p> <p>How about it?</p>

---
#### Feedback Bot on 9/24/2020, 00:19 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment]
What if this method has more than one overload?

**Comment by mbhvl** [comment]
> What if this method has more than one overload?

Offer a choice, as VS already does in other contexts.

**Comment by sharwell** [comment]
This is closely related to #12363 (it proposes another way to implement the same high-level request)

**Comment by mbhvl** [comment]
I'd love to learn how to contribute to Roslyn.  Is this task simple enough for a newbie?

**Comment by CyrusNajmabadi** [comment]
@mbhvl It would likely depend on the complexity of hte design being proposed here.  This would not be a 'small tweak', but would really need a fleshed out design that woudl then be implemented.  Because this impacts intellisense (a core scenario) and how it completes, it would really need a lot of thought going into how this would work and how to make sure it did not interfere with existing scenarios.

**Comment by mbhvl** [comment]
@CyrusNajmabadi how would I go about learning about this & assessing if my skills are up to the job?

**Comment by CyrusNajmabadi** [comment]
Closing out as we do not plan to do this and hter ehas been no movement.
