### ISSUE TITLE
Improve IntelliSense function parameter completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48021]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1191074/improve-intellisense-function-parameter-completion.html)._

---
Given a function declaration in C#:
```C#
internal static extern bool GetExitCodeProcess(IntPtr process, out uint exitCode);
```
I'm writing a wrapper:
```C#
public static bool GetExitCodeProcess(IntPtr process, out uint exitCode) =>
	Imports.GetExitCodeProcess(process, |);
```
At that point IntelliSense correctly guesses that I want to use `exitCode` so I press enter to accept the suggestion. Then the result is
```C#
public static bool GetExitCodeProcess(IntPtr process, out uint exitCode) =>
	Imports.GetExitCodeProcess(process, exitCode);
```
however that would result in compile error because the parameter is missing the `out` keyword.

My suggestion would be to improve IntelliSense to include the out keyword in it's suggestions (ex. it would suggest "out exitCode") OR to make it automatically add the out keyword (and "ref" and "in") when a function parameter suggestion is accepted because it's mandatory as per the function declaration and not adding it will always result in error.

---
#### Feedback Bot on 9/21/2020, 03:47 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
