### ISSUE TITLE
Move method to partial

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48026]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/704651/split-class-to-partial-classes-and-make-them-in-a.html)._

---
Add function to Code refactoring. The function is like:
split class to partial classes and make them in a folder.
Just like the Winform partial classes.
Form1.cs/Form1.Designer.cs are in a folder
we need this function sometimes, especially when we create many tabpages,
we want to split the Main class(like Form1.cs) to Form1.tabPage1.cs, Form1.tabPage2.cs, ...

---
#### Jane Wu [MSFT] on 8/22/2019, 02:21 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by mikadumont** [comment]
1. Offer to move a method to a partial class if it already exists
2. Create a new partial class if one does not already exist

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to do this.
