### ISSUE TITLE
Add `?` mark on generic types when marked `MayBeNullAttribute`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48023]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1189836/add-mark-on-generic-types-when-marked-maybenullatt.html)._

---
Sometimes we may use the method `T FirstOrDefault<T>(this IEnumerable<T>, Predicate<T>)`. However, the generic type `T` may be `null` when the list doesn't contain any elements satisfied the condition specified as a parameter of type `Predicate<T>`.

If we marked the return value `MayBeNullAttribute` to specify the return value may be null, the tooltip will add a may-be-null suffix symbol `?` following with the type. In this way we can get the nullability of the type more clearly.

For example, if the signature of the method `FirstOrDefault` is like:
```csharp
[return: MayBeNull]
T FirstOrDefault<T>(IEnumerable<T> @this, Predicate<T> condition);
```

We can see the symbol `?` when we call this method. The display result will be like the code as the attachment file DisplayInfo.png.

In addition, if the generic-typed argument is marked `MayBeNullAttribute`, `MayBeNullWhenAttribute` or `NotNullWhenAttribute`, the argument should also be marked `?` suffix symbol, because we can't tell the nullability of these parameters for sure.

> I'm so sorry that I don't know how to append pictures here.

Thanks!

---
#### Dada Huo [MSFT] on 9/18/2020, 03:24 AM: 

<p>Just double confirm with you, what language is used to describe this question? Is the screenshot you provided in debugger status?</p>

#### 齐天 张 on 9/18/2020, 05:26 PM: 

<p>C#... :)</p><p>Yep, this screenshot is in debugger status.</p>

#### Dada Huo [MSFT] on 9/20/2020, 06:59 PM: 

<p>Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by MaStr11** [comment]
If `[MabeNull]` is applied to a property, it could be solved by modifying the SymbolDisplayVisitor here:
https://github.com/dotnet/roslyn/blob/e87b92ea72fe2330343737070b4814a406e4bb2f/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Members.cs#L146-L146

The `symbol.Type` could be *annotated* like so:

```CS
// Add NullableAnnotation.Annotated to the property type if GetFlowAnalysisAnnotations suggest so
// This adds the ? behind the type.
var symbolType = symbol.GetSymbol<PropertySymbol>()
                       .GetFlowAnalysisAnnotations() == FlowAnalysisAnnotations.MaybeNull
                   ? symbol.Type.WithNullableAnnotation(CodeAnalysis.NullableAnnotation.Annotated)
                   : symbol.Type;
symbolType.Accept(this.NotFirstVisitor);
```

Some comparable logic needs to be placed in `VisitMethod` and `VisitParameter` to capture all cases. Before creating a PR for that I wanted to know if this is the right approach.

The screenshot below demonstrates, that the approach above is doing the job.
![image](https://user-images.githubusercontent.com/24472128/104351228-6dc8b680-5505-11eb-860e-430e4ed1f2c3.png)

**Comment by MaStr11** [comment]
I created a raft PR with the solution from above. Am I on the right track? It would be nice to get feedback.

**Comment by jcouv** [comment]
From discussion between IDE and compiler team, we're recommending considering an analyzer/fixer to help users migrate their code to the more concise syntax (issue https://github.com/dotnet/roslyn/issues/50819) and displaying nullability annotations to QuickInfo (tracked by https://github.com/dotnet/roslyn/issues/38358). Both proposals need to be confirmed with the IDE design team.

I'll go ahead and close this issue. We want to keep fidelity in the compiler APIs and the information display, rather than display things in a different way than they are. See discussion in PR https://github.com/dotnet/roslyn/pull/50527.
Thanks
