### ISSUE TITLE
fix formatting suggestion for cast

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48020]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1191660/fix-formatting-suggestion-for-cast.html)._

---
I set IDE0055 as a warning in .editorconfig because I don't want any formatting issues in my project. It works fine except for one case. It suggests me to add space inside cast, which is something that I totally don't want to do. There is no way to set my preferences to not get this formatting suggestion. Please provide a way how to disable suggestion for inserting space after opening ( and before closing ).

---
#### Feedback Bot on 9/21/2020, 03:47 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
You can update the `csharp_space_between_parentheses` option in **.editorconfig** to _not_ include the value `type_casts`. At that point, the formatter should remove the spaces.
