### ISSUE TITLE
Add a reference to System.Linq automatically when LINQ is used

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48025]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1035070/add-a-reference-to-systemlinq-automatically-when-l.html)._

---
VS2019 has brought in an extremely helpful feature; if you use an item (for example an attribute) that's in a non-referenced namespace, the approprtiate 'using' statement is automatically added.

It would be great if VS could automatically add 'using System.Linq' In a similar fashion, if you start to write a Linq statement.

---
#### Feedback Bot on 5/18/2020, 03:46 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
We do already have:

![image](https://user-images.githubusercontent.com/4564579/94192182-6f417680-fe63-11ea-9362-3ed4621c33e3.png)

I think the main request here is adding this automatically if someone types `from`.  However, i'm wary on doing that as the user may not want to use `System.Linq` but some other linq provider (i.e. IQueryable).

**Comment by CyrusNajmabadi** [comment]
CLosing out as we have sufficient support here.
