### ISSUE TITLE
PrintMembers produces unnecessary casts and calls to .ToString()

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48036]
If the printable member is of type `String`, the generated code casts it to object first. Then, `Append` method calls `.ToString()` on it in runtime:

```csharp
        public StringBuilder Append(object? value) => (value == null) ? this : Append(value.ToString());
```

This creates extra unneeded steps.

The current behavior calls `.ToString` on value types, and casts to `object` for reference types. Why not just pass the member as is?

**Comment by Youssef1313** [comment]
1. For value types, it's explained in LDM-2020-08-24:

    > **Should we call `ToString` prior to `StringBuilder.Append` on value types**
    >
    > The concern with directly calling Append without ToString on the value being passed is that for non-primitive struct types, this will cause the struct to be boxed, and the behavior of Append is to immediately call ToString and pass to the string overload.
    >
    > **Conclusion.**
    >
    > Do it.

    The point of this is said to be for non-primitive struct types. But currently, `ToString` is called on primitive struct types like `int`, etc.

2. For reference types, I don't get the reason of the cast.

**Comment by CyrusNajmabadi** [comment]
I think the reverse needs to be shown.  You're advocating extra complexity in the compiler. What is the data that shows that that is important?  It's ToString.  Casting a reference type to `object` is very likely not going to be an issue. 

In practice, every ref is going to call through that same overload, which is always going to convert to inject and then call ToString on the object. So this keeps things simple.
