### ISSUE TITLE
[Request] Improve "Code Lens - Dock Popup" result window

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#48048]
Hello, when I open "Code Lens"
![2020-09-25 11_52_25-](https://user-images.githubusercontent.com/17874713/94253464-a5dfc580-ff25-11ea-8a27-f3b8be6008fd.png)

and then I click on "Dock popup", I get this **minimalist** window
![2020-09-25 11_48_47-PowerCalculator](https://user-images.githubusercontent.com/17874713/94253184-39fd5d00-ff25-11ea-8204-76f8495b28a9.png)

I would be nice, when we can get the same window that we become when we click on `Find all references`
![2020-09-25 11_49_22-PowerCalculator](https://user-images.githubusercontent.com/17874713/94253191-3bc72080-ff25-11ea-9547-1126ec998662.png)

**Comment by jinujoseph** [comment]
@olegtk does it belongs to platform ?

**Comment by olegtk** [comment]
Yes. @TobiasSekan, can you clarify your suggestion please: would you prefer docked CodeLens window to be the same as Find All Referenced window or you want to see Find All References window content in CodeLens popup?

**Comment by TobiasSekan** [comment]
Hello,
IMHO I would prefer `docked CodeLens window to be the same as Find All Referenced window `

but I think for the most users it would be enough to give the `docked Code Lens window` more and more power, like
* Columns (file, containing member, ...)
* Different `Group by`
* Search in `Code Lens`
* ...

<img width="883" alt="2020-10-06 20_46_19-PowerToys - Microsoft Visual Studio Preview" src="https://user-images.githubusercontent.com/17874713/95246657-14b9fa00-0815-11eb-8e01-77cc15193166.png">

**Comment by olegtk** [comment]
Good suggestion. Find All References has evolved recently, but CodeLens stayed the same. @jinujoseph please route it to the editor. It won't make 16.9 feature planning, but we will consider it for future releases. Thanks!

**Comment by jinujoseph** [comment]
Routed to [platform](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1226273)
