### ISSUE TITLE
Restore.cmd should produce Restore.binlog

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#48057]
When building on a clean machine from cmd via Restore.cmd I want to see Restore.binlog in `artifacts\log\Debug`.

I"ve added -binaryLog to Restore.cmd but I see `Build.binlog` being hardcoded in a few places. The Build.binlog from the build overwrites the Build.binlog from Restore. We should have both.

I don't know which one of these locations needs to be updated to produce either Restore.binlog or Build.binlog depending on which phase is building:
![image](https://user-images.githubusercontent.com/679326/94307410-95c9e500-ff29-11ea-9f65-b91d582c3cee.png)

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by JoeRobich** [comment]
@KirillOsenkov We could take the suggestion from @tmat in [this comment ](https://github.com/dotnet/arcade/issues/5436#issuecomment-626028381). We could update the "eng\build.sh" and "eng\build.cmd" to invoke MSBuild twice. Once isolated to the restore and pass Restore.binlog as the log name. Then a second time to perform the build and other duties with Build.binlog as the log name.

**Comment by KirillOsenkov** [comment]
Whatever works best, as long as we have a binlog to investigate Restore.

**Comment by KirillOsenkov** [comment]
Note the comment about performance, having two phases shouldn’t be longer than a single phase.

**Comment by tmat** [comment]
> Whatever works best, as long as we have a binlog to investigate Restore.

We do have binlog for Restore. It's in Build.binlog. It contains all build phases.

**Comment by KirillOsenkov** [comment]
@tmat in my script I call Restore.cmd and then Build.cmd separately:

```
call Restore.cmd
set PATH=J:\s\.dotnet;%PATH%
call Build.cmd -binaryLog
```

Is this not how I'm supposed to be doing this? When I call just Restore.cmd I see no binlog anywhere.

**Comment by tmat** [comment]
> Is this not how I'm supposed to be doing this? When I call just Restore.cmd I see no binlog anywhere.

No, that's not how you should do this. Call `build -r`.

**Comment by tmat** [comment]
That said, we should include `-r` in build by default.

**Comment by KirillOsenkov** [comment]
@tmat so what's the purpose of Restore.cmd if I shouldn't be calling it? Whatever it's use is, when run independently it needs a binlog. If it's not used, let's delete it?

**Comment by tmat** [comment]
Build.ps1 has multiple switches that enable/disable various build phases (restore, build, test, pack, sign, etc.). Build.ps1 is meant to be executed once per build for which you want to see binlog. It runs all specified phases as a single MSBuild invocation and thus produces a single binlog (Build.binlog).

`(Restore|Build|Test).cmd` are just shortcuts that enable the specific phase. You can certainly run Restore.cmd and then Build.cmd if you don't care about binlog for restore.

**Comment by KirillOsenkov** [comment]
I guess this is what this bug is about: Restore.cmd should pass -binaryLog to Build.ps1 and specify a different name for the binlog (e.g. Restore.binlog) so it doesn't clash with Build.binlog.

Is this syntax supported? `Restore.cmd -binaryLog`? I'm OK with passing -binaryLog myself, as long as it's forwarded to Build.ps1.

Additionally, is something like this supported? `Build.ps1 -binaryLog:Restore.binlog` Would be nice if Build.ps1 allowed to customize the name of the binlog. Right now I don't think it does?

**Comment by tmat** [comment]
No it's not supported. Why are you not just calling `build -r` if your want to build and restore?

**Comment by tmat** [comment]
Do you want separate binlogs for restore and the rest of the build?

**Comment by KirillOsenkov** [comment]
As I said, I didn't know build -r will be sufficient. We can close this. I'm still not sure why not just delete Restore.cmd as it probably causes more confusion than adding value.
