### ISSUE TITLE
Supported API warning doesn't work on overloads

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#48058]
**Version Used**: 
VisualStudio.16.IntPreview/16.8.0-pre.4.0+30525.21.main
C# Tools   3.8.0-4.20464.1+56f747b362e15a0763bad5ce4702a9b7c8949d7e

**Steps to Reproduce**:

1. dotnet new lib
2. make it cross-target: `<TargetFrameworks>netstandard2.0;net5.0</TargetFrameworks>`
3. Open in VS.
4. Try to use `ThreadPool.ThreadCount` and observe intellisense tooltip.  It's correctly flagged as not supported on `netstandard2.0`
![image](https://user-images.githubusercontent.com/8918108/94308783-e2aebb00-ff2b-11ea-8bd2-64bf40860911.png)
5. Try to use `ThreadPool.QueueUserWorkItem<TState>` and observe tooltip.

**Expected Behavior**:
Similarly to `ThreadCount` this overload of `QueueUserWorkItem` should be flagged.

**Actual Behavior**:
No warning  
![image](https://user-images.githubusercontent.com/8918108/94308910-18ec3a80-ff2c-11ea-8721-2b72cd608111.png)

![image](https://user-images.githubusercontent.com/8918108/94308887-0eca3c00-ff2c-11ea-8763-b2d5722005a5.png)

Build results in error:

Severity | Code | Description | Project | File | Line | Suppression State
-|-|-|-|-|-|-
Error | CS1501 | No overload for method 'QueueUserWorkItem' takes 3 arguments | nslib (netstandard2.0) | C:\scratch\nslib\Class1.cs | 10 | Active

Repro project:
[nslib.zip](https://github.com/dotnet/roslyn/files/5284998/nslib.zip)

**Comment by jinujoseph** [comment]
cc @genlu for info

**Comment by genlu** [comment]
FYI @vivlimmsft, it seems intellicode provided items doesn't show supported framework info.

**Comment by vivlimmsft** [comment]
Thanks, I'll follow up in email.

**Comment by Cosifne** [comment]
@mikadumont : Follow up with UI to ask if it is good to add the yellow triangle and list of other info. Like if the TFM. And where should we put the info, should it be placed before the parameter descriptio or after the method description.

@genlu : Looks to the signature help part and get a purposal. (We want to show all the availiale items for TFMs, and show warning if it is not available for a certain TFM)

**Comment by Cosifne** [comment]
I won't move this to complete because we didn't have an actual purpose for this issue in today's design meeting

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  IF this is needed, we should get an official partner request specifying whne this needs to be done by, and we should assign to a dev/milestone to get it done in.
