### ISSUE TITLE
Generate Method code fix in an await foreach context creates an IEnumerable<> method instead of an IAsyncEnumerable<> method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48064]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1196083/generate-method-code-fix-in-an-await-foreach-conte.html)._

---
[severity:Other]
When I'm in this code context:
`await foreach (var item in _someInterface.GetItems())`
The GetItems() method does not currently exists in the interface so I get the codefix to add it. But executing it creates an IEnumerable returning method, instead of the expected IAsyncEnumerable:
`IEnumerable<object> GetItems()`

It should have created this:
`IAsyncEnumerable<object> GetItems()`

---
#### Feedback Bot on 9/23/2020, 08:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
I'll work on this one.
