### ISSUE TITLE
Drop "Core" from a VS error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48062]
> The project file cannot be opened. Version 5.0.100-rc.1.20452.10 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

I think the ".NET Core SDK" should be only ".NET SDK". Not sure if this change should be only for >= 5.0 or all sdks.

**Comment by PathogenDavid** [comment]
This is something handled by [dotnet/sdk](https://github.com/dotnet/sdk) and appears to have been fixed in https://github.com/dotnet/sdk/pull/11287

I would assume the reason you saw the old branding is that non-preview Visual Studio still uses the old SDK resolver.

**Comment by Youssef1313** [comment]
Yes I'm not using Preview. I'll close. Thanks for pointing to where this is handled and to the PR that fixed it.
