### ISSUE TITLE
Function pointer invocation has "None" IOperation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48082]
**Version Used**: 

master

**Steps to Reproduce**:

```csharp
public class C {
    public unsafe void M(delegate*<string, int, void> ptr) {
        ptr("a", 1);
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGSAmIDUAfAAQGYACAgJhIGESBvAWACgSWzSBXAOyggDM4yAFhIBZABSY4AGzgBzCPABUAHgIBGAAxISAS04YhAPhIAHGAgCUdJq1unzYgEQRH2tRYDcN1gF8mPoA)

**Expected Behavior**:

InvocationExpression has a suitable operation.

**Actual Behavior**:

InvocationExpression has "None" operation.

**Comment by mavasani** [comment]
This is a not yet implemented compiler feature. Tagging @333fred

**Comment by 333fred** [comment]
The work here is that we need a design for an operation interface for function pointer invocations. It will need to be similar to IInvocationOperation, but some of the things in IInvocationOperation don't apply to function pointers (IsVirtual, for example)

**Comment by bernd5** [comment]
Why not simply return `false` for "IsVirtual" in case of function pointer invocations?

**Comment by bernd5** [comment]
See API-Proposal: https://github.com/dotnet/roslyn/issues/57195
See Implementation: #57191
