### ISSUE TITLE
cannot override records's Equals

### ISSUE THREAD

**Issue by kofifus** [dotnet/roslyn#48088]
**Version Used**: 16.8.0 Preview 2.1 `<TargetFramework>net5.0</TargetFramework><LangVersion>preview</LangVersion> <Nullable>enable</Nullable>`

**Steps to Reproduce**:

```
public record C {
    public override bool Equals(object o) => false;
}
```

**Expected Behavior**:

successful compilation

**Actual Behavior**:

> error CS0111: Type 'C' already defines a member called 'Equals' with the same parameter types

(note that I can override `GetHashCode` without error)

**Motivation**:

I use a lot of records where all members are strongly immutable with value semantics. 
In this case I can guarantee that `GetHashCode` will always return the same value. I then want to cache this value and use it to shortcut `Equality` which can give huge speed gains. I tried to create a common base class for such records to inherit from like this:

```
public record RecBase  {  
  private int? _cachedHashCode = null;

  public override bool Equals(object obj) {
    if (obj is not RecBase o) return false;
    if (_cachedHashCode is null) _cachedHashCode = GetHashCode();
    if (o._cachedHashCode is null) o._cachedHashCode = o.GetHashCode();
    if (_cachedHashCode!=o._cachedHashCode) return false; // optimization, hash codes different -> not equal
    return object.Equals(this, o);
  }
}

public record MyImmutableRecordWithValueSemantics  : RecBase {  
  ... lots of members ..
}
```

But I get the error above.

**Comment by Youssef1313** [comment]
The error is expected and intentional. You need to define `Equals(C other)` instead of `Equals(object other)`.

**Comment by kofifus** [comment]
Thanks @Youssef1313 !

If I define Equals(C other) I lose access to the compiler generated Equals (one of the main benefits of records) which means I cannot generalize this useful pattern which is a real shame !

What is the reasoning for this ? is it in the standard ?

**Comment by Youssef1313** [comment]
@kofifus The generated `Equals(object)` already depends on `Equals(C)`. It just does the following:

```csharp
    public override bool Equals(object obj)
    {
        return Equals(obj as C);
    }
```

So if you moved your code to Equals(C other), you get the same behavior for `Equals(object)`.

**Comment by kofifus** [comment]
again - if I move my code to `Equals(C other)` I lose access to the member by member auto generated Equals and will have to write/maintain it myself

**Comment by Youssef1313** [comment]
@kofifus Probably what you want to do is achievable by a source generator (i.e. you put a special attribute on these records, and the source generator re-defines Equals for you, so you don't have to write it yourself for large number of members). You can re-open to get an official answer/reply from the compiler team.
