### ISSUE TITLE
Test coverage: ERR_InvalidFunctionPointerCallingConvention is not tested

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48080]
Searching through the repo for ERR_InvalidFunctionPointerCallingConvention at the time of writing this doesn't give any single test results:

https://github.com/dotnet/roslyn/search?q=ERR_InvalidFunctionPointerCallingConvention

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/blob/2bb65c8479ed6339487ecac4cd9131d9e8508e7e/src/Compilers/CSharp/Portable/Symbols/FunctionPointers/FunctionPointerMethodSymbol.cs#L162
We _could_ test this one by manually constructing a bad tree, adding it to the compilation, and then getting the diagnostics. We'd accept a pr, but I do consider it an edge case.

As to the other one, not sure why github search isn't showing the tests. They exist: https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs#L3230

**Comment by Youssef1313** [comment]
@333fred Thanks. Should I keep this open for ERR_InvalidFunctionPointerCallingConvention?

I'll update the title to not include the other error that's already tested.

**Comment by 333fred** [comment]
> @333fred Thanks. Should I keep this open for ERR_InvalidFunctionPointerCallingConvention?

If you think this is something you'd address, sure. Otherwise, I'm not certain it's worth the open bug.

**Comment by Youssef1313** [comment]
I'm not sure how to do it. I'll close given that it's an edge case.
