### ISSUE TITLE
IDE0004 - Incorrect "Redundant cast" when not casting would cause sign extension

### ISSUE THREAD

**Issue by TouchMonkey** [dotnet/roslyn#4810]
Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079
Installed Version: Enterprise
Language: C#

Quick action suggests the cast to uint is redundant in the following function, except not having the cast to uint will cause the int to be sign-extended to long instead of zero-extended.

        public static long ToLong(int high, int low)
        {
            return (((long)high) << 32) | (uint)low;
        }

![vs ide0004 bug](https://cloud.githubusercontent.com/assets/8552197/9500205/1d892b54-4bf2-11e5-9943-dfd3f130fc05.png)

**Comment by Pilchie** [comment]
I believe @DustinCampbell already fixed this as part of #4643

**Comment by DustinCampbell** [comment]
Yeah, this is precisely the scenario that I fixed. This is working now and will be fixed in Update 1. Below is a screenshot of it working properly.

![image](https://cloud.githubusercontent.com/assets/116161/9509126/f15b20d6-4c10-11e5-988a-76a42f7d9988.png)

**Comment by DustinCampbell** [comment]
Note #4531 is the original bug that was fixed.
