### ISSUE TITLE
T? is not allowed as a type pattern

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#48112]
**Version Used**: master

**Steps to Reproduce**:

```cs
using System;
public class C {
    void M(object g) {
        _ = g is Nullable<int>; // ok
        _ = g is int?; // ok
        _ = g switch { Nullable<int> => 0 }; // CS8116
        _ = g switch { int? => 0 }; // syntax error
        switch (g) { case Nullable<int>: break; } // CS8116
        switch (g) { case int?: break; } // syntax error  
    }
}
```

**Expected Behavior**: either

- No error in all cases
- CS8116 for `int?` type patterns as well.

**Comment by Youssef1313** [comment]
@alrz The issue seems more deeper than this.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKBoEtMYB+AAgA8WBeFzdAGz4BuGgGEAdAFkAFGwCUw2tWIBmFsXIA2NaRYiaAbxotja1eq3EALC2kB7YACs4AYxgsA5rKMnD1E/7VyAE4pdxY6KBYAOX4+CGA+OAAeBhgAPnlvAMCQsIjwxiZMv2yc0PDI1OL/AF8aGqA

**Comment by HaloFour** [comment]
`Nullable<T>` doesn't work like other structs.  IIRC, it's not possible to have a boxed `Nullable<T>`, you either get `T` or `null`.  So it's not possible for an `object` to be `Nullable<T>` and the test will always fail.  You should always test for the underlying value type instead.

**Comment by Youssef1313** [comment]
@HaloFour Then I'd expect CS0184 warning.

**Comment by HaloFour** [comment]
@Youssef1313 

Why should the compiler permit it at all if it's not possible?  The error message states pretty clearly why you can't match against an NVT and what you should do instead.

**Comment by Youssef1313** [comment]
@HaloFour I wasn't clear enough. I meant for the case where the compiler currently allows it. Like in [this SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKBoEtMYB+AAgA8WBeFzdAGz4BuGgGEAdAFkAFGwCUw2tWIBmFsXIA2NaRYiaAbxotja1eq3EALC2kB7YACs4AYxgsA5rKMnD1E/7VyAE4pdxY6KBYAOX4+CGA+OAAeBhgAPnlvAMCQsIjwxiZMv2yc0PDI1OL/AF8aGqA) sample.

**Comment by HaloFour** [comment]
@Youssef1313 

Oh, yes, I'd agree, it should be added as a warning wave if it is not currently.  Note that SharpLab does not run in "strict" mode so you might need to check elsewhere.

**Comment by alrz** [comment]
So if `is int?` and `is int` are identical this could be actually by design. I don't think adjusting parser would make sense to accept a redundant `?`.

**Comment by HaloFour** [comment]
Actually I take that back, it does seem that `isinst Nullable<T>` will match a boxed T, but only if it's not null.  So this is a language limitation, and probably because it's pointless to match an `int?` if the pattern can only succeed if the operand is `int`?

**Comment by sharwell** [comment]
I see two areas for improvement:

1. Report CS8116 for use of `int?` when the same would be reported for `Nullable<int>`
2. Add a code fix for this error to change `int?` to `int`

**Comment by alrz** [comment]
>Add a code fix for this error to change int? to int

Rider does fade out `?` in that expression and suggest to remove. In order for this to work I think the parser needs to be adjusted so we have the correct node in place.

**Comment by gafter** [comment]
```c#
        _ = g is Nullable<int>; // ok
        _ = g is int?; // ok
```

These are not pattern-matching operations. This is the old is-type operator. It would be a breaking change to make this kind of long-accepted code an error.
