### ISSUE TITLE
TypeLoadException when pointer is used as member of Records

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#48115]
**Version Used**: 
master(sharplab)

**Steps to Reproduce**:
`public unsafe record Test1(int* x);`

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMSAmIDUAfAAQCYBGAWAChKA7CMOKABwgGM4ACAkgOgCUBXajACW9bgGEA9mEbCANogDKiAG7C2UAN7F2ASSgBRAB7wEtOburCYmgL63KBAMztBUCADMOCOC0kJMdgAVBhgSAAphIQAqdiMASgBuIA===

**Expected Behavior**:
It's just an test, not sure what's the expected behavior.
Maybe report compile error, or emit an valid IL.

**Actual Behavior**:
System.TypeLoadException: The generic type 'System.Collections.Generic.EqualityComparer`1' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

Seems `EqualityComparer<int*>.Default` is not vaild.

**Comment by PathogenDavid** [comment]
> Seems `EqualityComparer<int*>.Default` is not vaild.

That's because you can't use pointer types as generic type arguments. The spec should probably be updated to use `EqualityComparer<IntPtr>` for pointer types.

If you find yourself blocked by this in a real scenario, you can work around it by explicitly overriding `Equals` and `GetHashCode`, IE:

```csharp
public unsafe record Test1(int* x)
{
    public virtual bool Equals(Test1 other)
        => this.x == other.x;

    public override int GetHashCode()
        => ((IntPtr)x).GetHashCode();
}
```

**Comment by Youssef1313** [comment]
If the implementation is updated to use HashCode.Combine (see https://github.com/dotnet/roslyn/issues/47514), we wouldn't probably have this issue. With the current design, the problem does seem to be in the following line:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.Lowered.cs#L286

**Comment by jaredpar** [comment]
Don't think this is a case we anticipated when designing records. @Youssef1313 analysis of the problem is correct though. 

At the least we need to do one of the following:
1. Change our code gen strategy to account for pointer types
1. Disallow pointers in primary ctors of records

Following up with LDM to see which approach we should take but leaning towards 2.

**Comment by PathogenDavid** [comment]
> 2\. Disallow pointers in primary ctors of records

[This issue isn't exclusive to primary constructors.](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgAQCuAdlBAGZx4JwDGA9ggCZ4BKAsAFADenefeuPAEsiMAFR4AHgG5OAX05A=)

**Comment by jaredpar** [comment]
True. I should have said "record members"

**Comment by jcouv** [comment]
From LDM 10/26/2020, we're going to block this scenario for now. I'll open a follow-up proposal in csharplang.
