### ISSUE TITLE
Usings should be able to bind to declarations from previous submissions

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4811]
```
> class Foo { }
> using F = Foo;
```

This case would be affected *if* it were legal (which it's not).
```
> namespace N { public class Foo { } }
> using N;
```

**Comment by amcasey** [comment]
Was internal bug 528258.

**Comment by amcasey** [comment]
Was internal bug 528436.

**Comment by amcasey** [comment]
See also internal bug 528258: the semantic model *does* consider previous submissions when binding usings, so it may disagree with the batch compiler.

**Comment by amcasey** [comment]
Since you can't declare namespaces in script/interactive code, only using aliases are affected.

**Comment by amcasey** [comment]
@ManishJayaswal Since only using aliases are affected, I don't believe this meets the preview bar.

**Comment by ManishJayaswal** [comment]
@amcasey sounds good.

**Comment by amcasey** [comment]
It is also impossible to alias a type declared in the same compilation.

**Comment by amcasey** [comment]
The root of the problem seems to be that ```Binder.LookupMembersInSubmissions``` unconditionally considers the imports of all submissions (including the current one), ignoring the ```Imports``` passed into the binder.

**Comment by amcasey** [comment]
Consider mining https://github.com/amcasey/roslyn/tree/AbandonedGH4811.

**Comment by amcasey** [comment]
We had hoped we could fix this later, but it's not additive.  Specifically, it changes the binding rules for using.  ```using F = Foo;``` could go from referring to ```Foo``` in a referenced assembly to referring to ```Foo``` in a previous submission.  Such rebindings break back-compat.

**Comment by amcasey** [comment]
@genlu Can you please verify this?
