### ISSUE TITLE
Support init accessors in CSharpConvertAutoPropertyToFullPropertyCodeRefactoringProvider

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48133]
Currently only get; set; are supported.

https://github.com/dotnet/roslyn/blob/f6c95ab082171ef9a9f2c6114b003eea1df11842/src/Features/CSharp/Portable/ConvertAutoPropertyToFullProperty/CSharpConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs#L70-L73

**Comment by louis-z** [comment]
I'd like to take a crack at it.
