### ISSUE TITLE
public enum DeclarationKind must have an InitAccessor member

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48136]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.declarationkind?view=roslyn-dotnet

The current enum members include GetAccessor, SetAccessor, but not InitAccessor.

**Comment by sharwell** [comment]
Why not just use `SetAccessor`?

**Comment by Youssef1313** [comment]
@sharwell Did you mean that SyntaxGenerator.GetDeclarationKind(SyntaxNode) method should return "DeclarationKind.SetAccessor" for both set and init declarations?
I think they need to be treated differently as they're 3 different accessors.

**Comment by Youssef1313** [comment]
Also, SyntaxGenerator currently have GetSetAccessorStatements, and GetGetAccessorStatements. A new method GetInitAccessorStatements should be considered.

**Comment by sharwell** [comment]
Isn't an `init` accessor just a `set` accessor with use-site restrictions?

**Comment by Youssef1313** [comment]
@sharwell Yes, it's even compiled to `set_PropName`, but I think that's from a *semantics*.
The enumeration is involved in usage with SyntaxGenerator, so I think if they are separated, that will give consumers more flexibility to do what they want.

**Comment by CyrusNajmabadi** [comment]
> Isn't an init accessor just a set accessor with use-site restrictions?

Yes.  And my understanding is that that's how the compiler is exposing this info.

**Comment by Youssef1313** [comment]
I'm okay if you agree that both should fall into DeclarationKind.SetAccessor. I'll open a PR

**Comment by sharwell** [comment]
I could end up going either way. I can see advantages and disadvantages to both approaches.

**Comment by Youssef1313** [comment]
Does this method need to account for init as well?

https://github.com/dotnet/roslyn/blob/06c4312d67b3295b72bac48fbd6459f26cbb0cc0/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L2535-L2539

I think it currently doesn't. I can put that in #48137 as well

**Comment by CyrusNajmabadi** [comment]
i think it's challenign to answer some of these without having clear cases of where consumers use this so we can judge what their expectations would be .

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Is this discussable in a design meeting? or the issue needs to get some comments from consumers to decide?

**Comment by CyrusNajmabadi** [comment]
We would likely need comments from consumers here.

**Comment by Youssef1313** [comment]
DeclarationKind enum now contains "RecordClass" member, which is kind of syntactic sugar of a "class" with extra synthesized members.

Given that, I think it makes sense to do that with "init" vs "set" since it's a similar case.

@sharwell @CyrusNajmabadi What are your thoughts?

**Comment by Youssef1313** [comment]
Also note that `GetDeclarationKind` will currently return `None` for init accessors. So if InitAccessor is going to be rejected as a member of the enum, then GetDeclarationKind should be adjusted to return SetAccessor instead of None:

https://github.com/dotnet/roslyn/blob/90ff6db2c2f44a1c2501cd71440d9115439360e6/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs#L2047-L2057

**Comment by sharwell** [comment]
> DeclarationKind enum now contains "RecordClass" member

This seems unfortunate. Do we know when it was added?

**Comment by Youssef1313** [comment]
Hmmm, from the discussion in https://github.com/dotnet/roslyn/issues/10094, it seems that you're indeed correct. "RecordClass" shouldn't have been added at all. But removing it is a breaking change :/

Now the question is: 

- Should we take a breaking change to keep things consistent?
- Should `GetDeclarationKind` return `DeclarationKind.None` or `DeclarationKind.SetAccessor` for init declarations?

**Comment by sharwell** [comment]
It might not be to late to mark `RecordClass` Obsolete with the message "This value is not used".

**Comment by Youssef1313** [comment]
@sharwell Should I open a PR or wait until other team members agree?

**Comment by sharwell** [comment]
You could open a draft PR to frame the discussion
