### ISSUE TITLE
Missing nullability warnings after invocation of extension methods with [AllowNull] this parameter

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#48134]
**Version Used**: 
```
Branch master (26 Sep 2020)
Latest commit 3e38d76 by CyrusNajmabadi:
Merge pull request #48002 from CyrusNajmabadi/implicitCreation

Use implicit object creation in the IDE layers.
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;

class Test
{
  public static void Main()
  {
      string? s = null;
      s.AllowNullExtension();
      s.ToString(); // no warnings, runtime crash
  }
}

public static class Extension
{
   public static void AllowNullExtension([AllowNull] this string p) { }
}
```

**Expected Behavior**:
Warning for `s.ToString()`

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Comment by PathogenDavid** [comment]
Worth noting that this is not specific to extension methods, [it happens with normal methods too](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4DEAdgK4A2tEwtcABHJY8wLABQAAgAYWfAIwA6ACKYIAc0oB7WJgDGUMQGF5BOAEEOtXFExQA3L158ATCwAqcWLwDevFq+GXLLt855u/wkQEAfhYoFgBeFhp6M19/VwBRAA94SiN5SjEdenkAdwA5Olpk1PTKAAooAEpY+Nc1G3kAZRgETEoZcpqWAHoeqPkWXIgESnaZKCQWBGpKGEwwVmUEaAALL1cAX15tngsAZgCANncWEvYypw3hQ9ETvgAWFmzaPML6c7TMDPKAbRe3kUALoBIQAByqLEcLF2myAA).

**Comment by RikkiGibson** [comment]
This appears to be a corollary of #48605 and would likely be solved at the same time
