### ISSUE TITLE
Prevent potential cycles binding constraint types

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#48154]
Prevent potential cycles when binding constraint types.

For example, catch use of `TypeWithAnnotations.Type` when `BinderFlags.IgnoreNullableContext` is set (see https://github.com/dotnet/roslyn/pull/47968, https://github.com/dotnet/roslyn/pull/47968/commits/f9061da0a0960cf3ce3d74599937753a3e43fbd3).

**Comment by jaredpar** [comment]
@AlekseyTs can we close this out now after your PR?

**Comment by AlekseyTs** [comment]
Should be addressed in https://github.com/dotnet/roslyn/pull/49261.
