### ISSUE TITLE
Improve test coverage for IsMemberDeclaration method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48163]
I don't think it's a good idea to update this one without knowing the change it introduce.

This **whole** method isn't covered in the tests. See how https://github.com/dotnet/roslyn/pull/48158 is green.

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn/pull/48137#discussion_r496854587_

**Comment by Youssef1313** [comment]
After figuring out what this method affects, we need to decide whether to update it with init accessor or not.

**Comment by Youssef1313** [comment]
I could get test failures in #48158 by the last commit in it. But still, doesn't cover everything in the method.

**Comment by sharwell** [comment]
This is in reference to the following method:

https://github.com/Youssef1313/roslyn/blob/7d5f6f4f745c2e525e558f896eb2d8803a31da25/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs#L1287-L1329
