### ISSUE TITLE
Passed by reference before it has been assigned a value

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#48160]
``` vb.net
Dim foo as MyObj
MyFUnction( foo )
```

> Variable 'foo' is passed by reference before it has been assigned a value. A null reference exception could occur at runtime.

It should also offer code-fix  `assign default value (Nothing)`

**Result:**

```
Dim foo As MyObj = Nothing
MyFUnction( foo )
```

**Comment by CyrusNajmabadi** [comment]
Need info to determine if this is important enough to warrant any investmnet here.

**Comment by AdamSpeight2008** [comment]
It's a just would be nice to have code-fix for the warning, maybe make it an "up for grabs"

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 are you interested in contributing something here?

i'm generally feel pretty meh on this as a fix that just adds two tokens is really not much better than just using completion to write it out by hand.

**Comment by CyrusNajmabadi** [comment]
Unlikely to add feature given no feedback and VB space.  closing out.
