### ISSUE TITLE
Deeply nested delegates with Nullable=enabled causes the compiler to be really slow.

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#48174]
**Version Used**: 
SDK version 5.0.100-rc.2.20477.2
**Steps to Reproduce**:

1. Clone https://github.com/pranavkm/repro.git and checkout the `nullable` branch
2. Run `dotnet build`

Without `Nullable=Enabled`, the project compiles in about a second. With `Nullable=Enabled`, the project takes about 32 seconds to compile. 

This is a simplified repro from code generated by Blazor. We've also heard reports of this with shallower call stacks that appear multiple times affecting build times but I do not have a concrete reproduction of this.

**Comment by sharwell** [comment]
@jaredpar see: https://github.com/pranavkm/repro/blob/0970c67b7b166488145402f833f63ac27e452629/Class1.cs

**Comment by RikkiGibson** [comment]
A few questions:

1. Does this generated code require meaningful nullable diagnostics? For example, if we completely dodged nullable flow analysis when using `#nullable enable annotations`, and simply emitted the declared nullability of everything, would Blazor be able to adopt that pattern and solve their perf problem in practice?

2. Can we skip nullable lambda return inference when the return type of the target delegate is not a reference type (or can never be a reference type after substitution?)

**Comment by pranavkm** [comment]
@RikkiGibson the scenario I
In the example listed above, the nested delegates are code generated, so we generally don't care about nullability analysis there.  We do want the analysis to work inside the body of the delegate since that's code users have written and they would expect the same sort of analysis you would get if they were writing regular C#. I'm much more concerned about the slowness users have reported in code that does not involve such comical levels of nesting.

**Comment by pranavkm** [comment]
@RikkiGibson what version of VS \ SDK would this fix land in?

**Comment by RikkiGibson** [comment]
16.9 preview 2.

Depending on how badly people are impacted by the issue, we could consider backporting to 16.8. For example, do "mainline" blazor scenarios have minutes added to the compile time when the user adopts nullable? I imagine that meets some kind of bar? /cc @jaredpar
