### ISSUE TITLE
XML doc comments should continue to insert slashes even when the auto-generate XML doc comments option is unchecked

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4817]
This is an intentional change in behavior from Visual Studio 2013.

In VS 2013, the "Text Editor->C#->Advanced-> Generate XML documentation comments for ///" not only controls generation of XML doc comments on ///, but also whether or not /// is inserted on ENTER. This should be changed so that the option only controls generation when typing ///, but insertion of /// within an existing XML doc comment still works.

Mentioning @dpoeschl, since he and I discussed this change and decided it's better overall.

**Comment by dpoeschl** [comment]
Once the user has added actual doc comments, we don't have a good reason to prevent the auto-insertion of ```///``` on enter. Dustin mentioned that this option was probably added to prevent codespit when typing block-style comment headers like:
```
////////////////////////////////////////////////////
////////////////// Hello World /////////////////////
////////////////////////////////////////////////////
```

And auto generating the ```///``` on enter (or open line below / open line after) within *existing* doc comments will not interrupt that pattern.
