### ISSUE TITLE
Analyzer leaks the compiler generated class name for top-level statements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48171]
![image](https://user-images.githubusercontent.com/31348972/94623103-bee4cf80-02b3-11eb-9839-50959ebd5051.png)

I'm not sure if this behavior is okay or not.

**Comment by CyrusNajmabadi** [comment]
It's not ok.  We shouldn't be offering any of those generate field/prop features here.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Oh yes they don't make sense here and shouldn't be offered at all.

**Comment by Youssef1313** [comment]
By a quick look:

https://github.com/dotnet/roslyn/blob/c7dba0828cd1ee78fb0f37ae264e187f24aa9456/src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.State.cs#L137-L140

The implementation here looks good. Is the compiler *incorrectly* returning `false` for `IsImplicitClass`? Will need to debug and confirm.
