### ISSUE TITLE
Feature request: Convert to interpolated string code refactoring

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48219]
Currently, there is a code refactoring to convert to verbatim string.

![image](https://user-images.githubusercontent.com/31348972/94851030-1e63ec00-0428-11eb-8340-579c73c98ea9.png)

Another possible code refactoring (should only be offered when the string contains `{` and `}` is to convert to interpolated string.

## Example

I wanted something like this while working with unit tests in roslyn and roslyn-analyzer codebases. So, here is an example. Suppose there is an existing unit test like the following

```csharp
[Fact]
public void TestSomething()
{
    var code = @"
namespace Mynamespace
{
    public class Program
    {
        public static void Main() {Console.WriteLine();}
    }
}";
}
```

For some reason, I want to update the unit test to:

```csharp
[Theory]
[InlineData("")]
[InlineData("string[] args")]
public void TestSomething(string mainArgs)
{
    var code = $@"
namespace Mynamespace
{{
    public class Program
    {{
        public static void Main({mainArgs}) {{Console.WriteLine();}}
    }}
}}";
}
```

It would be *much* easier to make this update if the IDE can offer a refactoring that converts the original code to the following:

```csharp
var code = $@"
namespace Mynamespace
{{
    public class Program
    {{
        public static void Main() {{}}
    }}
}}";
```

**Comment by sharwell** [comment]
I want this _all the time_.

**Comment by louis-z** [comment]
If there's no rush, I'd be willing to take a stab at it. I too would love to have this.

**Comment by Youssef1313** [comment]
@louis-z I think you can go for it. You may find existing implementations useful:

- https://github.com/dotnet/roslyn/tree/master/src/Features/Core/Portable/ConvertToInterpolatedString
- https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/ConvertToInterpolatedString/CSharpConvertPlaceholderToInterpolatedStringRefactoringProvider.cs
- https://github.com/dotnet/roslyn/blob/master/src/Features/VisualBasic/Portable/ConvertToInterpolatedString/VisualBasicConvertPlaceholderToInterpolatedStringRefactoringProvider.vb

I'm not sure if it's better to extend the existing implementation for the case in this issue, or create a new one.

@CyrusNajmabadi Do you have any preference?

**Comment by louis-z** [comment]
I came up with a new implementation, based on [AbstractConvertConcatenationToInterpolatedStringRefactoringProvider](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs) and its derived classes (thanks @Youssef1313 for pointing me in the right direction 😉). I will submit a PR shortly.

**Comment by davidwengier** [comment]
It's not clear to me exactly what the intentions are for this. If I wrote `string s = "Today is {DateTime.Now}";` then I would expect a "Convert to interpolated string" refactoring to _not_ escape the braces.

**Comment by Youssef1313** [comment]
> It's not clear to me exactly what the intentions are for this. If I wrote `string s = "Today is {DateTime.Now}";` then I would hope that a "Convert to interpolated string" refactoring would _not_ escape the braces, to help in situations where the `$` was forgotten.

This is reasonable. But there is already a CA rule suggestion that will handle the case where a `$` token is forgotten (it's not implemented yet).
To make the intent clear, the codefix may use "Convert to interpolated string and escape braces".

**Comment by CyrusNajmabadi** [comment]
To me, i think the intent is clear enough :)  we don't try to overly explain exactly every nuance. I think we just try to do what most would expect with reasonably simple text :)

**Comment by alenros** [comment]
If it makes any difference, I came here exactly because I expected "Convert to interpolated string" to do just that, precisely because I wanted it since I kept forgetting to add a $.
