### ISSUE TITLE
Nullability not being respected by implicit operator

### ISSUE THREAD

**Issue by JordanGreissman** [dotnet/roslyn#48248]
**Version Used**: 
C#8, VS16.7.5

**Steps to Reproduce**:
```c#
class ConvertedString
{
    public static implicit operator ConvertedString?(string? str) => str != null ? new ConvertedString() : null;
}

class Program
{
    public static void Main(string[] args)
    {
       ConvertedString fromString = "test"; // warning
       Console.WriteLine(fromString);
    }
}
```

**Expected Behavior**:
Code compiles without warning

**Actual Behavior**:
CS8600: Converting null literal or possible null value to non-nullable type

**Comment by RikkiGibson** [comment]
Here it is recommended to use [NotNullIfNotNullAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullifnotnullattribute?view=netcore-3.1). Note that VS 16.8 is required to get the proper behavior in this scenario.

```cs
#nullable enable
using System;
using System.Diagnostics.CodeAnalysis;

class ConvertedString
{
    [return: NotNullIfNotNull("str")]
    public static implicit operator ConvertedString?(string? str) => str != null ? new ConvertedString() : null;
}

class Program
{
    public static void Main(string[] args)
    {
       ConvertedString fromString = "test"; // ok
       Console.WriteLine(fromString);
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAJgEZGmAGCptgOgAiASwgBzXAHtYwgMZR+AYUko4AQRqEAnlGFQA3I04sKy3ADdE8FAGUYCYbjGMA3owoeKAbSYB2EBQAcpIwgUSEAJIAZsGh4QAUAESwCIkAlAC67p5MAMy8bABsFMJgAA6EcsIwFJJliBAwkgimkhZWcLb2jmIA/PF8XL0UKWkUALwAfCP2FACE4xQExBTDuHAA7q3tCNZ2Dk7xYwHLhIYMAL5GzCZ8vq7ZHnkFxUwALBQAshCOA2xcXgyFAgCDEUDSjwobgYnlhZksu06+x6FCiCEkYGRTgmFES8FgiX0FAA9MTagBrSE5NgATniaIxWLEaXOsKulyAA=)
