### ISSUE TITLE
C# refactorings for string building

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48278]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1203061/c-refactorings-for-string-building.html)._

---
<p>Given a line like<br><br>string foo = &quot;Hello &quot;  + bar + &quot;!&quot;; <br><br>there should be suggested refactorings like<br><br>string foo = $&quot;Hello {bar}!&quot;; <br><br>and<br><br>string foo = string. Format(&quot;Hello {0}!, bar); <br><br>And the reverse refactorings should be available as well. This is a feature in Resharper: https://www.jetbrains.com/help/resharper/Code_Analysis__String_Formatting_Methods.html#formatting</p>

---
#### Mila Zhou[MSFT] on 9/28/2020, 11:09 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
We already have **Convert to Interpolated String** (the first suggested refactoring), but not the others. We'll discuss the additions in Design Review.

Thanks! 😄

**Comment by dibarbet** [comment]
Design review:
After discussion among those present in the review, we couldn't come up with a compelling use case for the reverse refactorings.  We'd rather not add refactorings for edge cases that are rarely used as they add noise to the lightbulb menu.  These analyzers should be relatively easy to write in a separate library if so desired.
