### ISSUE TITLE
#endregion improvement: close region at end region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48283]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1200788/endregion-improvement-close-region-at-end-region.html)._

---
It would be helpful to be able to close a region at the #endregion code, for large regions., instead of having to scroll back, where the matching #region tag is easy overlooked. At the same time it would be helpful to be able to open a region in a way that the view automatically moves to the region near the #endregion tag.

---
#### Mila Zhou[MSFT] on 9/27/2020, 00:31 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out.  The ctrl-] shortcut can be used used to easily jump between regions.
