### ISSUE TITLE
Please add the "hacktoberfest" topic.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/roslyn#48285]
I want to make a contribution to this repository but I also want it to count against my contributions for [2020's Hacktoberfest](https://hacktoberfest.digitalocean.com/). But for this to happen, [the repository must have the `hacktoberfest` topic](https://github.com/digitalocean/hacktoberfest/pull/596).

**Comment by jinujoseph** [comment]
This has been done
