### ISSUE TITLE
Compiler shouldn't allow extension method called "Clone" on records.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48287]
Currently, the following code compiles without errors:

```csharp
public record S;

public static class Extensions
{
    public static S Clone(this S s)
    {
        _ = s;
        return new S();
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8kAmIA1AD4ACAzAAQJwDGA9ggdQMoDcAsAFC9XVyARgBsggEzUAogA94AOyiZGi3gG9e1LYJrCxbagGEANirgAKGAAtMUdtSgBKTdo09tH6gH1qAXgfc7p5a5ADs1PJwAO7s5o6BHgC+vMk8QA==).

**Comment by CyrusNajmabadi** [comment]
Closing out as i do not see any language rules we've specified that would disallow this.  If you would like to propose a language rule here, please open a discussion over at dotnet/csharplang.  Thanks :)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I just came across https://github.com/dotnet/roslyn/issues/40726 and found:

> - [x] Clone extension method allowed? (no)

![image](https://user-images.githubusercontent.com/31348972/96190747-02da0480-0f43-11eb-950f-2c6da30d6aeb.png)


Did that meant records shouldn't indeed have Clone extension methods? Why it has a check mark while it doesn't seem to be done yet?

cc: @jcouv

**Comment by jcouv** [comment]
This was checked because the question was resolved ("no"). That test plan tracks the C# 9 work for records.

**Comment by Youssef1313** [comment]
@jcouv They're [currently allowed](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNGAfAAgZgAQJwDGA9ggCZ4BKA3ALABQjueWAjAGysBMeAogA94AOygBLEqMYBvRnnmt87LlTwBhADaS4AChgALMVGoEAlHgC8APjzC4Ad2o7T9BgF8gA=). Is there any work/tracking issue to disallow it?

**Comment by CyrusNajmabadi** [comment]
What we we decided is that when looking up the Clone method we wouldn't bind to extension methods.  It's not that you can't write the extension method.  It's just that the compiler won't use it.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi There is probably something I'm misunderstanding. I see that currently it's being used:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4DcIIAERAvIZnAO6EBKAFAJQDcAsAFAIB0AwgDYD2FRqzbsAAgGZicAMb8EAE1ojxUsQEYAbITEAmQgFEAHvExQAloKjsA3u0IOdarbUJ9BcOjAAW5qK4QGe0c7NkdwnXVODQBOOgAiY1MLQXjmYIidAHZyKlphDMIAX3YioA=

I'm also not sure how to use the existing Clone? I can't normally call it:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4DcIIASYLwYHZwDuGASgBQCUA3ALABQCAdAMIA2A9gZbXfQAIBmLHADG7BABNSVIA==
