### ISSUE TITLE
Conditional operator does not work in interpolated strings

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#4829]
string test = $"{flag?'a':'b'}";

triggers

    error CS1003: Syntax error, ':' expected

on the place where the colon is (which is a bit confusing) and `error CS1733: Expected expression`.

When numbers are used, like

    string test = $"{true ? 4:1}";

the autoformatting and syntax coloring give a hint that the colon is treated as format specifier.

Enclosing the expression in parenthesis seems to be a good workaround.

**Comment by ltrzesniewski** [comment]
You just have to add parentheses:

```C#
string test = $"{(flag ? 'a':'b')}";
```

**Comment by miloush** [comment]
Yes, that's what I noted as a workaround. However, it looks like a bug. The intention is clear and so is the operator syntax. If anything else, it shouldn't say a colon is expected when there is a colon.

**Comment by ltrzesniewski** [comment]
@miloush Oops, sorry, I didn't see your last sentence.

**Comment by HaloFour** [comment]
@miloush The message could be a little clearer but I believe it is intentional (trying to remember [all](http://roslyn.codeplex.com/discussions/540869) [of](http://roslyn.codeplex.com/discussions/570614) [the](http://roslyn.codeplex.com/discussions/570292) debate on the subject from CodePlex).  The `:` can be used with interpolation to provide a format specifier, just like with composite formatting:

```cs
int i = 123;
string s = $"{i:00000}";
Debug.Assert(s == "00123");
```

**Comment by miloush** [comment]
Quick search on those discussions didn't suggest the conditional operator has been brought up.
Moreover, the lexical grammar you referenced seems to allow colon in balanced-text-part but not in the interpolation-format-part, which - if I understand correctly - should favour the conditional expression, while the current behavior suggests that all colons after the first one are treated as format specifier.

**Comment by gafter** [comment]
This is as pre the current draft specification, which will be published in the full language spec.

Use parens as suggested.
