### ISSUE TITLE
TypeSymbol.cs and TypeSymbol.vb are out-of-sync

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48291]
https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs#L32-L36

https://github.com/dotnet/roslyn/blob/69c3537456ebe29fdee0a4371eef63e67a2b4e95/src/Compilers/VisualBasic/Portable/Symbols/TypeSymbol.vb#L25-L29

These comments says that they must be in sync.

However, the C# version includes a public method `IsTupleTypeOfCardinality`, while the VB version doesn't.

I don't know what is the exact problem if they're out of sync. But opening the issue based on the comments and how "strong" they are.

**Comment by 333fred** [comment]
`IsTupleTypeOfCardinality` should be made internal. It's effectively internal already, as it's in an internal type and not implementing a public interface method. But it would be good to fix that.
