### ISSUE TITLE
Generate overrides doesn't work correctly for simple records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48295]
```
namespace ConsoleApp20
{
    public record A
    {
        public virtual void OverrideMe() { }
    }

    public record B$$ : A;
}
```

Invoke <kbd>Ctrl</kbd>+<kbd>.</kbd> on `$$` and choose Generate overrides, check "OverrideMe" from the dialog.

## Expected behavior

Remove the semicolon and use `{ }`, and place the overridden method in braces.

## Actual behavior

```
namespace ConsoleApp20
{
    public record A
    {
        public virtual void OverrideMe() { }
    }

    public record B : A public override void OverrideMe()
    {
        base.OverrideMe();
    };
}
```

**Comment by Youssef1313** [comment]
Same with implementing interface:

![image](https://user-images.githubusercontent.com/31348972/95003992-bbb84f00-05e5-11eb-8b34-907d81c3eaf1.png)

**Comment by jcouv** [comment]
Thanks for reporting this. I have a fix in progress.

**Comment by Youssef1313** [comment]
@jcouv That was too fast! Thanks for working on it.
