### ISSUE TITLE
"Tidy invocation" refactorings

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#483]
I'd like some refactorings to clean up invocations. Things like
- Move all parameters to separate lines
- Move all parameters to same line
- Remove all (possible) parameter names
- Add all parameter names

**Comment by CyrusNajmabadi** [comment]
The first two were added already.  Not seeing enough demand for the latter two to warrant this issue.

**Comment by sharwell** [comment]
The fourth option also exists as a refactoring. A new issue could be filed to address unnecessary explicit named arguments if someone wants to propose specifics for how it would behave.
