### ISSUE TITLE
Generated IEquatable<> code for records with collection property should compare structurally.

### ISSUE THREAD

**Issue by xtofs** [dotnet/roslyn#48304]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/467f6acb07ad34105a9e5d3405ec8fdd1701fc86

**Steps to Reproduce**:
Given
```csharp
public record Foo( string Name, IEnumerable<int> Items) {}
```

The following code produces false and false.
```csharp
    var a = new Foo("a", new int[] { 1, 2 });
    var b = new Foo("a", new int[] { 1, 2 });
        
    Console.WriteLine(a.Equals(b));
    Console.WriteLine(a == b);
```

Whereas the following code produces true and true.

```csharp
    var coll = new int[] { 1, 2 };
    var a = new Foo("a", coll);
    var b = new Foo("a", coll);

    Console.WriteLine(a.Equals(b));
    Console.WriteLine(a == b);
```

The generated equality comparer for the record uses `EqualityComparer<IEnumerable<int>>.Default`  to compare the Items collection which is just checking for reference equality .

**Expected Behavior**:

The generated `IEquatable<Foo>.Equals` override should compare structurally to be consistent with other types of properties.

**Actual Behavior**:

Records with collection properties should compare the collection structurally.

**Comment by CyrusNajmabadi** [comment]
Closing out as the compiler is behaving exactly as specified as per the LDM decicions here.  If you'd like this behavior to change, it would need a change in the language specification which can happen at dotnet/csharplang.  Note though that htis was again explicit on our part.  If you want collections compared structurally, you can do that by overriding .Equals and explicitly providing the behavior you want.
