### ISSUE TITLE
CA2213 triggers when using null propagation operator

### ISSUE THREAD

**Issue by rwdd** [dotnet/roslyn#4830]
if my code looks like 
<code>
                     if (this.session != null)
                    {
                        this.session.Dispose();
                    } 
</code> everything is fine.
But if i write
<code>
                    this.session?.Dispose();
</code> 
i will get an error.

**Comment by srivatsn** [comment]
Is this happening with Microsoft.FxCopAnalyzers nuget package? Or is this just with the regular codeanalysis rule in VS?

**Comment by rwdd** [comment]
We do not use FxCopAnalyzers package. We only use "Mircrosoft Managed Recommedned Rules".
Use these two classe to reproduce the issue.

public class DisposableA : IDisposable
{
    private bool disposedValue;

    public void Dispose()
    {
        this.Dispose(true);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!this.disposedValue)
        {
            if (disposing)
            {
            }

            this.disposedValue = true;
        }
    }
}

public partial class DisposableB : IDisposable
{
    private readonly DisposableA disposableA;

    public DisposableB()
    {
        this.disposableA = new DisposableA();
    }
}

public partial class DisposableB
{
    private bool disposedValue;

    public void Dispose()
    {
        this.Dispose(true);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!this.disposedValue)
        {
            if (disposing)
            {
                this.disposableA?.Dispose();
            }

            this.disposedValue = true;
        }
    }
}

**Comment by srivatsn** [comment]
Can you try if installing the [FxCopAnalyzers package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/1.0.1) to see if that fixes the issue for you? The FxCopAnalyzers package reimplements some of the CA rules using roslyn and that's where we are making changes.

**Comment by rwdd** [comment]
The current stable version 1.0.1 does not fix that problem. The current beta does not work on.

**Comment by lgolding** [comment]
We are now tracking this issue in the Rosyln Analyzers repo: https://github.com/dotnet/roslyn-analyzers/issues/291.

We will fix this in the FxCopAnalyzers NuGet package (not in FxCop).
