### ISSUE TITLE
Function pointer calling convention keywords should be classified

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/roslyn#48324]
**Version Used**: 
VS 16.7.5

**Steps to Reproduce**:

Type code
```csharp
delegate* managed<void> ptr
```

**Expected Behavior**:
All calling convention keywords (`managed` here) should be colorized.

**Actual Behavior**:
They are in default color.

**Comment by sharwell** [comment]
@333fred please let @JoeRobich know what this is supposed to do and we can get it implemented for 16.9

**Comment by jasonmalinowski** [comment]
They're keywords. This works in 16.8; the bug report is against 16.7 and we likely hadn't gotten any of it working there.

**Comment by jasonmalinowski** [comment]
@Sunnie-Shine: this should be working in the latest 16.8 Previews if you want to give those a shot. There's a bunch of other fixes there too you'll want as that's the first real version that has IDE support.

**Comment by Sunnie-Shine** [comment]
@jasonmalinowski Thank you! I'm sorry for this issue :(
