### ISSUE TITLE
[LSP] Loading two solutions in the same session faults LSP

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48320]
**Version Used**: 
Version 16.9.0 Preview 1.0 [30604.13.main]

**Steps to Reproduce**:

1. Load one solution
2. Load another

**Expected Behavior**:
Load successfully

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1103906/95045545-fd541180-072d-11eb-8a12-bf9181d2d062.png)

**Comment by davkean** [comment]
I cannot find the logs for this. ActivityLog is empty.

**Comment by dibarbet** [comment]
I couldn't personally repro this, and per email thread it is resolved externally by https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/277206

Resolving this issue, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1198844 tracks the fix.
