### ISSUE TITLE
Visual indicator for deprecated code

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#48330]
Direct customer ask copying here: 
>Strike through deprecated functions/methods similar to VSCode:
![image](https://user-images.githubusercontent.com/46729679/95106586-8d259b80-06ed-11eb-8ace-7f0cc32040d9.png)

(Twitter comment: https://twitter.com/jeffreypriebe/status/1311831025136279552)

Since the compiler/runtime folks did the work for warnings for deprecated APIs. We can have a visual indicator that lets users know when their code is deprecated.

**Comment by sharwell** [comment]
Duplicate of #26488

**Comment by mikadumont** [comment]
relates to #26488

**Comment by CyrusNajmabadi** [comment]
Closing as dupe.
