### ISSUE TITLE
C# 9 records do not fold like classes do

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48334]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1208525/c-9-records-do-not-fold-like-classes-do.html)._

---
[severity:It bothers me. A fix would be nice]
Paste the following code into Visual Studio:

```csharp
public record A
{
}

public class B
{
}
```

Visual Studio will let me fold/collapse the class `B` into a single line, but I am unable to fold/collapse the record `A`.

---
#### Feedback Bot on 10/4/2020, 09:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This is already fixed in #47894

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/47894
