### ISSUE TITLE
SymbolFinder.FindCallersAsync doesn't include references from libraries

### ISSUE THREAD

**Issue by GaryStonerock** [dotnet/roslyn#4833]
Is there a way to find callers to a method that are in the projects in a solution AND their referenced libraries?  The problem I'm trying to solve requires to search referenced libraries as well as the projects within a solution.

**Comment by Pilchie** [comment]
Unforuntely, no.  Roslyn does not do any analysis of the IL within referenced libraries, it just imports the metadata.  Consider also, that at least for most of the Microsoft provided reference assemblies, there *is* no implementation present in the copy passed to the compiler.

**Comment by GaryStonerock** [comment]
I'm using v1.0.0 of the roslyn apis.  

Also worth noting, it appears SymbolFinder.FindImplementationsAsync includes referenced libraries.

Is there a reason for the inconsistent behavior across the SymbolFinder api?  Not sure if this is a bug or if I should be using the API differently?
