### ISSUE TITLE
removing unused usings when compile errors present

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48337]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1198662/removing-unused-usings-when-compile-errors-present.html)._

🔗 [AB#1219172](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1219172)
🔗 [AB#1349846](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1349846)

---
Removing 'unused usings' should be limited to when the project compiles. If the project/file has compilation errors, then VS falsely detects the imports as unused and removes them. To fix this, I have to open the file in a different editor and put them back.
'Unused' should only be determined when everything compiles.

---
#### Feedback Bot on 9/24/2020, 10:43 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @JoeRobich

**Comment by CyrusNajmabadi** [comment]
In general we do not stop people from using our features just because code isn't compiling.  If we had something which ran automatically, it would likely not want to run in the presence of errors.  However, if the user wants to explicitly run things, that's fine.

**Comment by dibarbet** [comment]
Design meeting notes:
We should make unused usings work similarly to how the analyzer for unused parameters works - if there are errors in the file then it will not translate the compiler diagnostic into an IDE diagnostic.  In such instances we do not know if the usings are actually unused.
This will result in no fading, no code fix for removal, and the organize and remove command will not remove usings when errors are present.  If the current file builds, there will not be a change in behavior.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of broad feedback here.
