### ISSUE TITLE
Question: Participate in Hacktoberfest?

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [dotnet/roslyn#48344]
Hacktoberfest is going on this month. They have changed the rules to an "opt-in" policy by adding Hacktoberfest top to the repository. Here is a link - [Hacktoberfest Update](https://hacktoberfest.digitalocean.com/hacktoberfest-update). It's a good way to get new contributors.

**Comment by sharwell** [comment]
Duplicate of #48285
