### ISSUE TITLE
Incorrect Solution snapshot used for diagnostic analysis

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48351]
Repro:
1) Working in Roslyn.sln (branch EncOOP-vs-deps, commit 7e40628e5f873ff23d37d28bf881c77085230b5e).
2) Attaching to another VS
3) 683 errors reported in the error list. These errors do not correspond to the actual state of the solution.

Memory dump and list of errors in:
\\mlangfs1\public\tomat\Bugs\wrong-snapshot

**Comment by tmat** [comment]
@jasonmalinowski @jinujoseph Can we prioritize this issue? I keep hitting it.

**Comment by jasonmalinowski** [comment]
@tmat Hmm, these diagnostics are coming from OOP now, right? So we need a dump of that process? Looking at this dump I don't see anything wrong with it, but my ability to dig deep is being hampered by the debugger itself.

Right now we're investigating a case where OOP seems to be having something going bad with processing edits, so it's possible this is a downstream symptom of that.

**Comment by tmat** [comment]
We shouldn't need OOP process dump, assuming that solution snapshot is synchronized correctly between devenv and OOP.
EnC currently runs in-proc and sees the same diagnostics.

**Comment by jasonmalinowski** [comment]
@tmat Ah I was thinking Edit and Continue had already moved OOP. Are you still seeing repros?

**Comment by tmat** [comment]
It is still in-proc. Yes, I am seeing this every now and then.

**Comment by jasonmalinowski** [comment]
@tmat At this point should we just close this?
