### ISSUE TITLE
ImplementNofityPropertyChanged.sln sample does not load

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#4837]
When I try to load APISampleUnitTests.sln directly in VS 2015 Enterprise Rel the load fails with 

```
C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj : error  : The imported project "C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\Tools\Microsoft.CodeAnalysis.Toolset.Open\Targets\VSL.Settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj
```

There is no tools directory under src\Samples\VisualBasic,

I get same error for ConvertToAutoPropertyVB.sln,ImplementNotifyPropertyChanged.sln (which also has several other issues), and MakeConstVB.vbproj.

**Comment by davkean** [comment]
I've been unable to repro all of the issues, except the ImplementNofityPropertyChanged.sln problem.

It appears that this ImplementNofityPropertyChanged.sln is referring to a project (UnitTestFramework.csproj) that does not exist:

```
D:\roslyn\src\Samples\Shared\UnitTestFramework\Impl\UnitTestFramework.csproj : error  : The project file 'D:\roslyn\src\Samples\Shared\UnitTestFramework\Impl\UnitTestFramework.csproj' has been moved, renamed or is not on your computer.
```

**Comment by paul1956** [comment]
Where does "D:\" come from?

I am only running the VB project/solution, why is C# involved?

**Comment by davkean** [comment]
I just copied and pasted the error from my box. My source is on D:\, hence why the error mentions D:\.

The unittestframework project helpers to help test the code fix. It's written in C#.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #76](https://github.com/dotnet/roslyn-sdk/issues/76) via [**ZenHub**](https://www.zenhub.com/)
