### ISSUE TITLE
Code cleanup support for third party analyzers

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#48383]
Configure code cleanup should show every third party analyzer fixer if a user has that third party analyzer package installed (StyleCop). This includes the .NET 5 SDK analyzers:

![image](https://user-images.githubusercontent.com/46729679/95273465-05788380-07f8-11eb-958d-fef869d27e92.png)

**Comment by mikadumont** [comment]
This relates to https://github.com/dotnet/roslyn/issues/40163

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback, investment in this area, and high complexity of design to support this.
