### ISSUE TITLE
Display discard values when debugging

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#48408]
We should try showing discarded values in the debugger if we can. (debugger-discards branch)
Note: F# doesn't show discards while debugging.
Should we also expose them in EE in some way?

Follow-up from https://github.com/dotnet/roslyn/issues/38820 (test plan for lambda discards)

**Comment by alrz** [comment]
There's some info at https://github.com/dotnet/roslyn/issues/29739

**Comment by jcouv** [comment]
Oops, didn't realize we had an issue already. Closing as dupe of https://github.com/dotnet/roslyn/issues/29739 :-)
