### ISSUE TITLE
VB has non-deterministic output when anonymous types differ in case 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#48417]
Consider the following VB code 

```vb
' Module1.vb
Module Module1
  Sub Method()
    Console.WriteLine(New With { .X = 42 })
  End Sub
End Module
```

```vb
' Module2.vb
Module Module2
  Sub Method()
    Console.WriteLine(New With { .x = 42 })
  End Sub
End Module
```

The output of this program is non-deterministic. Because VB is case insensitive under the hood here only a single anonymous type object is created. The casing of the field representing `X` here will be determined by the first use of the anonymous type. Given that our files are bound in parallel if we have an anonymous type that differs by only case of the properties in different files then which we emit as the field name is non-deterministic. 

This commit exposed the issue in our code base: 

https://github.com/dotnet/roslyn/commit/b15b40c592ed8ed09af7200d73cbdd5108b8f306

This changed the casing of the second property in the anonymous type to be `span` where it used to be `Span`. That conflicts with the anonymous type in [AbstractReferenceHighligtingTests.vb](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Test2/ReferenceHighlighting/AbstractReferenceHighlightingTests.vb#L60) which uses `Span`. Since that commit we've seen several failures of the determinism leg and when diffing the string table it appears that the primary difference is the casing of the `span` field in the string table.

**Comment by jaredpar** [comment]
@AlekseyTs i'm not quite sure what the best fix is going to be here. Think we need to find some way to pick the "best" definition here but I don't have any intuition as to what that would be. Also would like to ensure you agree with the analysis here.

**Comment by AlekseyTs** [comment]
I think we are ordering anonymous type templates to emit them in deterministic order. If I remember correctly, they are ordered based on lexical order of the first usage. If we are not picking casing of property names in the same order, I think we should. I will have to take a closer look at the current implementation to provide more details, but I think we can solve this problem.
