### ISSUE TITLE
[LSP] Enable push or pull diagnostics but not both

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#48414]
Clients can now indicate if they support pull diagnostics as per https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/279454 so we should check for that, and send push diagnostics as a fallback.

Probably should wait for https://github.com/dotnet/roslyn/pull/48328 to be in to avoid conflicts, or target that branch.

**Comment by CyrusNajmabadi** [comment]
This has been done.
