### ISSUE TITLE
Add F1 help service for codestyle options in .editorconfig

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48433]
Tracking issue for F1 service for codestyle options?
See https://github.com/dotnet/docs/pull/20892#discussion_r499620992

I tried to give it a look. Here is the IHelpContextService interface.

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/VisualStudio/Core/Def/Implementation/F1Help/IHelpContextService.cs

Its method receives a `Microsoft.CodeAnalysis.Document`, which AFAIK is for C# and VB only. However, the .editorconfig file is in `ini` format.

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn/issues/48392#issuecomment-704962152_

**Comment by PathogenDavid** [comment]
This seems out-of-scope for Roslyn to me and should probably be handled by something like https://github.com/madskristensen/EditorConfigLanguage

The extension already shows basic help in a tooltip:

![image](https://user-images.githubusercontent.com/278957/95587870-47781400-0a08-11eb-8f33-083a4a781cb5.png)

It has F1 support, but it seems it needs to be updated. In the previous screenshot, it tries to link to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019#parentheses but that page no longer has details about the individual rules. (It should probably go [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0047-ide0048#dotnet_style_parentheses_in_relational_binary_operators) instead.)

**Comment by Youssef1313** [comment]
I'd personally prefer if this doesn't require any extensions. Also it should work in a different way than what the extension currently does.

Simply, the extension needs to be updated with links **every** time a new option is added. This isn't how the F1 service is supposed to work.

The F1 service relies on an f1_keywords YML metadata that exist in docs.

**Comment by PathogenDavid** [comment]
> I'd personally prefer if this doesn't require any extensions.

It'd be nice, but editorconfig isn't a .NET-specific thing. I'd worry it'd hamper the ability for built-in Visual Studio editorconfig language support to expand to cover other non-C#/VB domain-specific properties if this is something hampered in Roslyn.

> Simply, the extension needs to be updated with links **every** time a new option is added.

That'd be nice, but new options aren't added all that frequently. Is all the effort of implementing this worth it to avoid updating a JSON file once a year? This feels like a solution in search of a problem.

**Comment by Youssef1313** [comment]
> It'd be nice, but editorconfig isn't a .NET-specific thing. I'd worry it'd hamper the ability for built-in Visual Studio editorconfig language support to expand to cover other non-C#/VB domain-specific properties if this is something hampered in Roslyn.

For that I think we can just allow the service to work **only** when the editorconfig option falls under a `[*.cs]` or [*.vb]`?

**Comment by jmarolf** [comment]
Unfortunately this is outside of roslyns control :(
