### ISSUE TITLE
GeneratedMSBuildEditorConfig.editorconfig added to project root

### ISSUE THREAD

**Issue by Bouke** [dotnet/roslyn#48430]
https://github.com/dotnet/roslyn/pull/43617 introduced generation of editor files. Those should be written to `obj\debug\` (or whatever `IntermediateOutputPath` is pointing to. However for one of my projects it is generating the file in the project's root. 

Setting `IntermediateOutputPath` explicitly to ``obj\debug\`` generates the file in the specified folder.

I've added the following to my csproj:
```
    <Target Name="IOP" BeforeTargets="CoreCompile">
        <Message Text="🔍 IOP: '$(IntermediateOutputPath)'" Importance="High" />
    </Target>
```

This prints the following:
```
1>  🔍 IOP: 'obj\x64\Debug\'
```

**Version Used**: Visual Studio 2019 (16.7.5)

**Steps to Reproduce**:
1. Build project.

**Expected Behavior**:
No file changes in folders beside ``bin\`` and ``obj\``.

**Actual Behavior**:
New file in project's root: `PROJECTNAME.GeneratedMSBuildEditorConfig.editorconfig`

**Comment by jasonmalinowski** [comment]
(note there's a second report of this happening at https://stackoverflow.com/questions/64241729/new-generated-generatedmsbuildeditorconfig-file-since-recent-upgrade/64249123)

**Comment by chsienki** [comment]
@Bouke We would expect the generated file to be emitted under the `$(IntermediateOutputPath)`, but it's possible the targets are being included in a non-expected order. 

Would you be able to capture a binary log of your build that we could inspect to understand why this is occurring? (https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) 

In the interim as a workaround you can set the generated file output path explicitly with `    <GeneratedMSBuildEditorConfigFile >$(IntermediateOutputPath)$(MSBuildProjectName).GeneratedMSBuildEditorConfig.editorconfig</GeneratedMSBuildEditorConfigFile>`
 or disable the generated file entirely by setting `<GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile>`

**Comment by Bouke** [comment]
I can provide a binary log for internal use; where can I send it?

**Comment by jasonmalinowski** [comment]
Easiest option is probably to file a feedback ticket on https://developercommunity.visualstudio.com/ which gives you a way to upload files privately. Put a link here to your feedback item so we can link them back up.

**Comment by Bouke** [comment]
I've posted the feedback/binary log here: https://developercommunity.visualstudio.com/content/problem/1216427/generatedmsbuildeditorconfigeditorconfig-added-to.html.
