### ISSUE TITLE
Records: Current behavior doesn't match spec when re-defining Deconstruct method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48440]
**Version Used**: 

master

**Steps to Reproduce**:

```csharp
public record C
{
    public static void Deconstruct()
    {
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACBcDGB7BAEwwGEBYAKAG9KM6N0GBGANgYBYMARXPAO1gIArjhgAKAJS16NCvQwBfSgqA=).

**Expected Behavior**:

Based on the [spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records), an error is expected:

> It is an error if the explicit declaration does not match the expected signature or accessibility, or is static.

**Actual Behavior**:

No error.

Not sure if it's a spec issue or compiler issue.

Note: The compiler produces an error when there is actually some arguments like the following:

```csharp
public record C(string X)
{
    public static void Deconstruct(out string x)
    {
        x = "";
    }
}

namespace System.Runtime.CompilerServices{public class IsExternalInit{}}
```

---

I also expect the following to have an error based on the current spec:

```
public record C(string X)
{
    public void Deconstruct(out int x)
    {
        x = 0;
    }
}

namespace System.Runtime.CompilerServices{public class IsExternalInit{}}
```

**Comment by RikkiGibson** [comment]
> I also expect the following to have an error based on the current spec:

Could you please clarify why an error would be produced in this case?

**Comment by Youssef1313** [comment]
> > I also expect the following to have an error based on the current spec:
> 
> Could you please clarify why an error would be produced in this case?

For the same reason as the first case, the spec says:

> It is an error if the explicit declaration does not match the expected signature or accessibility, or is static.

The signature of the redefinition isn't the expected one (int vs string)

**Comment by RikkiGibson** [comment]
Thanks, I didn't squint hard enough at it 😄 

My feeling at a glance of this is that we should modify the spec to only require expected `static`-ness, `virtual`-ness, parameter ref kinds, etc. on the Deconstruct whose signature matches the expected member for overriding purposes. e.g.:

```cs
record Rec(int X)
{
    public void Deconstruct(out int x) { ... } // ok
    public void Deconstruct(ref int x) { ... } // error
    public static void Deconstruct(out int x) { ... } // error
    private void Deconstruct(out int x) { ... } // error
    public virtual void Deconstruct(out int x) { } // error

    public void Deconstruct(out string x) { ... } // ok
    public void Deconstruct(ref string x) { ... } // ok
    public static void Deconstruct(out string x) { ... } // ok
    private void Deconstruct(out string x) { ... } // ok
}

abstract record Rec(int X)
{
    public abstract void Deconstruct(out int x); // error
}
```

We would need to fix the implementation either way.

Tagging @dotnet/roslyn-compiler for thoughts. I do not know whether we must do this in 16.8, or if we can do it in 16.9, or make it a warning wave in .NET 6, etc.

**Comment by jaredpar** [comment]
> My feeling at a glance of this is that we should modify the spec to only require expected static-ness, virtual-ness, parameter ref kinds, etc.

The spec already explicitly mentions `static`. It mention matching on signature which is a term that generally encompasses items like ref kinds. Wouldn't hurt to be more specific though. I'm unsure if the omission of `virtual` was a deliberate decision or not. If it was deliberate it may help to be explicit that it's allowed. 

@jcouv and @AlekseyTs are best to answer this.

**Comment by jcouv** [comment]
I'm not sure how to best phrase the spec. @AlekseyTs may have an idea.
You can have a user-defined `Deconstruct` that doesn't interfere with a generated one (ie. could have those two overloads in source) or also has the correct accessibility, return type, and static-ness. 
`Deconstruct` methods are errors when they prevent us from generating a method but are not proper to use instead of the one we'd generate.

**Comment by AlekseyTs** [comment]
I think the specification is quite clear: "A **positional record with at least one parameter** synthesizes a public void-returning instance method called Deconstruct with an out parameter declaration for each parameter of the primary constructor declaration." And entire that section is about that Deconstruct method. It doesn't say anything about any other Deconstruct methods and there are no special rules for them in records.
