### ISSUE TITLE
Move to type to another file even if there is only one type in that file

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#48445]
Dialogue to look similar to Move to namespace and have an option to remove source file: 

![movefile](https://user-images.githubusercontent.com/46729679/61253239-277a7780-a715-11e9-9545-5d21d2484095.png)

Once you select Ok the namespace and type will then get moved to the destination file and if the remove source file is checked the source file will get deleted.

**Comment by mikadumont** [comment]
Relates to https://github.com/dotnet/roslyn/issues/37243

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
