### ISSUE TITLE
Consider making IIndentationService public

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/roslyn#48452]
Razor LSP formatting heavily depends on this service to provide correct C# formatting. Because this is internal, we are currently using [reflection](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs#L121) to access this API but we would super appreciate it if this can be made public.

cc @jasonmalinowski @jinujoseph 

Note: Razor already has an `ExternalAccess.Razor` layer in Roslyn to help with this but based on my conversation with @jasonmalinowski, we plan to go with that approach if making this public isn't going to happen for a while.

**Comment by Youssef1313** [comment]
It may be considered to be an `InternalsVisibleTo` instead of public.

**Comment by CyrusNajmabadi** [comment]
We do expose this publicly by using the ISmartIndentProvider interface.  Can you not use that API?

**Comment by ajaybhargavb** [comment]
> We do expose this publicly by using the ISmartIndentProvider interface. Can you not use that API?

I didn't know those were the same. But we still can't because Razor language server doesn't use MEF :(

**Comment by sharwell** [comment]
> Razor already has an ExternalAccess.Razor layer in Roslyn to help with this

This is the way to go if you aren't using MEF.

**Comment by CyrusNajmabadi** [comment]
>  But we still can't because Razor language server doesn't use MEF :(

Does vs offer no way to get at these types not through mef?  @jasonmalinowski ?

**Comment by jasonmalinowski** [comment]
The issue wouldn't be MEF as much as the ISmartIndentProvider API also requires them to be composing in the editor and using those APIs too, which seems a bit overkill. @ajaybhargavb: even the workspace APIs use MEF under the covers, so you've been using it whether you realized or not. :smile:

**Comment by CyrusNajmabadi** [comment]
Note: i don't actually have anything against this idea.  Previously, this would have been a bad idea as there wasn't one indentation-service, and trying to answer the 'what is the indenation here?' question was nearly impossible.  We did unify this into a pure-data API with a reasonable signature.

My only concern here would be how young this API is and if we would lock ourselves into having to support it when we might want to change it in the near future.  For example, the API is currently synchronous, and we may want to make this async (and force callers to decide what their own blocking logic shoudl be).  Once this is public, that becomes much more difficult.

**Comment by jasonmalinowski** [comment]
@ajaybhargavb Based on what you found about how the indentation service wasn't meeting needs, is this something we should just close?

**Comment by ajaybhargavb** [comment]
@jasonmalinowski, I haven't had the chance to investigate further after our last discussion. I'll confirm in a few days.
