### ISSUE TITLE
More IDE adoption to records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48464]
Record's identifier names aren't currently colored. I believe they should have some colorization.

This is mainly because there is no classification for records, see the following code segment:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs#L344-L352

---

**Side node:**

The VB parallel code throws an exception for unknow values (while the C# code just returns null). If the C# code was throwing an exception, this would have been caught much earlier. I strongly feel that thrown an exception is very helpful here.

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/VisualBasic/Portable/Classification/ClassificationHelpers.vb#L305-L318

---

Do we want to have the same color for records identifiers? or a new color?

Available options:

- We can use the existing class classification for records and get the same color.
- We can create a new classification for records and still be using the same color. (This is identical to the first option from end-user perspective)
- We can create a new classification for records and use a new color.

The third option is is be blocked on #47713 due to:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/Core/Portable/Classification/ClassificationExtensions.cs#L9-L21

I can submit a PR to fix this when the team settles on one of the above options.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Classification for records is already being handled by @allisonchou  in https://github.com/dotnet/roslyn/pull/47960
