### ISSUE TITLE
NotNullWhenAttribute for when the return value is not a boolean

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#48463]
When you have a method that returns a boolean and has a nullable `out` parameter, it is possible to add the nullable attribute `NotNullWhen` to the `out` parameter to specify the case where it won't be `null`, depending on the value of the boolean return type.

Would it make sense to have a `NotNullWhen` attribute for return values with different data types?

For example, let's say you have a method that returns an enum that describes the result of an operation, and only on one particular case (the "success" case), the `out` parameter will not be `null`:

```cs
enum OperationResult
{
    Success,
    ErrorA,
    ErrorB
}

OperationResult TryMethod([NotNullWhen(returnValue: OperationResult.Success)] out MyType? obj)
{
    obj = null;
    if (/* Error condition A*/)
    {
        return OperationResult.ErrorA;
    }
    else if (/* Error condition B*/)
    {
        return OperationResult.ErrorB;
    }
    obj = new MyType();
    return OperationResult.Success;
}
```

Since it could also be possible to have two or more enum values that are considered "success" cases, the `NotNullWhen` attribute could take an array of values:

```cs
enum OperationResult
{
    SuccessA,
    SuccessB,
    ErrorA,
    ErrorB
}


OperationResult TryMethod(
    [NotNullWhen(returnValue: new OperationResult[] { OperationResult.SuccessA, OperationResult.SuccessB} )]
    out MyType? obj)
{
    obj = null;
    if (/* Error condition A */)
    {
        return OperationResult.ErrorA;
    }
    else if (/* Error condition B */)
    {
        return OperationResult.ErrorB;
    }
    else if (/* Success condition A */)
    {
        obj = GetMyTypeForSuccessA();
        return OperationResult.SuccessA;
    }
    else // Success condition B
    {
        obj = GetMyTypeForSuccessB();
        return OperationResult.SuccessB;
    }
}
```

**Comment by huoyaoyuan** [comment]
This should increase the difficulty of state tracking in compiler.
There are type theory for you for some complex analysis. But, it may cost a lot in compiler implementation.

In this case, if you shape the API with discriminated union, the compiler work could be much simpler.

The biggest reason for `NotNullWhen(true)` is that the pattern is already widely used in BCL. Otherwise, reshaping the API could be acceptable.

**Comment by carlossanlop** [comment]
The proposed attribute can have a different name. It does not need to share the name with the existing attribute for boolean. That may help simplify the problem.

**Comment by huoyaoyuan** [comment]
> That may help simplify the problem.

No. Tracking enum should be more complex than tracking boolean.

**Comment by jcouv** [comment]
As other have commented above, this would require a big overhaul of the compiler's analysis infrastructure, which is geared towards either unconditional (State) or binary conditional states (StateWhenTrue/WhenFalse). We'd have to track multiple states for the different enum values.
I'll go ahead and close this as by-design. Thanks
