### ISSUE TITLE
Lock contention in ProjectCacheService.CacheObjectIfCachingEnabledForKey causes high CPU usage and slow Find All References

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/599631/find-all-references-slow-and-high-cpu-usage.html)._

---
Find All References is super slow and VS is using a ton of resources

---
#### Feedback Bot on 6/10/2019, 04:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/10/2019, 10:42 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

#### Sean McManus [MSFT] on 3/3/2020, 02:35 PM: 

<p>What programming language are you using?</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Marked up-for-grabs to give this method a lock-free fast path:

https://github.com/dotnet/roslyn/blob/59e4c0a28bdd7187d78d93969a7f95b5291a7448/src/Features/Core/Portable/Workspace/ProjectCacheService.cs#L87-L105

**Comment by CyrusNajmabadi** [comment]
Alternatively, remove this and replace with something specific to any services that potentially need this.  For FAR, i'm surprised we would need such a thing as far is designed to get hte compilation/semantic model it needs up front prior to calling into all the finders to process it.    there should be a cleaner design here that can work well.

**Comment by sharwell** [comment]
I believe the caller here was caching syntax trees (GetRoot or something like that).

**Comment by CyrusNajmabadi** [comment]
Yeah, far is designed to process a document at a time. So I think we just want to have a design whereby we do delay computing this until one part of the search needs it. But we then cache until the remainder of the work on that document finishes.

**Comment by sharwell** [comment]
I wouldn't rule out the possibility of parallel operations. This was difficult in the past due to memory limits of a 32-bit process, but we no longer have that constraint. I'll try to take a look in the coming week.

**Comment by CyrusNajmabadi** [comment]
Oh, we are parallel here (now that we're out of proc).  The general idea though is that we shouldn't need a cache.  instead, the operations that work on a document can all run at the same time, using the same data.

**Comment by CyrusNajmabadi** [comment]
This type is gone.
