### ISSUE TITLE
Reorder parameters dialog incorrectly lists default value for struct as "null"

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#4849]
``` C#
struct MyStruct
{

}

class Foo
{
    void foo(int x, MyStruct s = default(MyStruct))
    {

    }
}
```

With the above code, invoke reorder parameters on "foo". Observe that the default value of "s" is listed as "null". It should be default(MyStruct).

**Comment by Giftednewt** [comment]
@rchande I took a brief look and this is happening because it's displaying the const value from the symbol and not the text from the syntax tree.

**Comment by Giftednewt** [comment]
@rchande After further investigation it doesn't look like it'll be possible to get back to the syntax tree without adding references to the specific language projects and then implementing conditional logic for the different languages, which I think would be a bad idea. However, it looks possible that by using the semantic model and the IOperation interfaces that it might be achievable in a language agnostic way.

I note that IOperation has been disabled in master, but I could submit a fix targetting future if you think that using the semantic model and IOperation would be the preferred way to go. Or maybe you have some other suggestions?
