### ISSUE TITLE
VB.NET Editor removes thousands separators from single and double literals

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#48492]
Write:
`Dim x = 123_456_784.0F`
As soon as you leave the line, it will converted to:
`Dim x = 123456784.0F`

**Comment by VBAndCs** [comment]
It happens with decimals too. Try:
`Dim x = 123_456_784D`
Note that the separators will be kept just if you removed the `D`.

**Comment by Youssef1313** [comment]
The underscores doesn't seem to exist in the generated syntax tree. This could be the reason why the underscores was dropped. Looks like a parser issue to me.

**Comment by VBAndCs** [comment]
@Youssef1313
Nice work. Thanks.
