### ISSUE TITLE
Methods with Tuple on their signatures won't work when added to GlobalSuppressions.cs

### ISSUE THREAD

**Issue by AlfredoMS** [dotnet/roslyn#48495]
### Analyzer

Any

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

VS2019 Version 16.7.5

### Describe the bug

If there is an error flag and I want to add it to the GlobalSupressions file, it won't work when tuples are present in the signature, either the return value or a parameter.

### Steps To Reproduce

`
public async Task<(bool status, ErrorCode errorCode)> SaveMessageByCorrelatedAppointment(string appointmentId, AppointmentResponse appointmentResponse)
`

Contains several errors flag by the analyzer, when added to the suppresions files it adds the entry:

`[assembly: SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Foo.Bar.Utils.AppointmentDocDbController.SaveMessageByCorrelatedAppointment(System.String,Foo.Common.Models.AppointmentResponse)~System.Threading.Tasks.Task{System.ValueTuple{System.Boolean,Kobe.Api.ErrorCode}}")]`

### Expected behavior

Line is not flagged after being added to suppressions file. Build should be succesful

### Actual behavior

when running the analyzer again, or trying to build, two things happen. First, the error is still flagged by the analyzer. Second, the GlobalSuppressions.cs file now has the error
`IDE0076 Invalid global or missing target for 'SuppressMessageAttribute'`

## Additional context

This also happens if the tuple is not the return value but a parameter.

**Comment by svick** [comment]
I believe my PR https://github.com/dotnet/roslyn/pull/48359 fixes this and I have added a test verifying that.
