### ISSUE TITLE
Unable to add breakpoint to property init member

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#48504]
**Version Used**: Version 16.9.0 Preview 1.0 [30607.183.main]

**Steps to Reproduce**:

```c#
class C
{
    public string? Foo
    {
        get;
        init;
    }
}
```

1. Put caret on `init`
1. Press <kbd>F9</kbd> to add a breakpoint

**Expected Behavior**:

Breakpoint is added to `init`.

**Actual Behavior**:

Breakpoint is added to `get`.

**Comment by Youssef1313** [comment]
The problem could be in:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/CSharp/Portable/EditAndContinue/BreakpointSpans.cs#L209-L213

But not sure.
