### ISSUE TITLE
IDE0038 C# Use pattern matching in LINQ Expression

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48520]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1210213/ide0038-c-use-pattern-matching-in-linq-expression.html)._

---
[severity:It bothers me. A fix would be nice]
Visual Studio suggests converting this expression:

```
Expression<Func<ConsumedReward, string>> converter = x => x.Reward is VoucherReward ? (((VoucherReward)x.Reward). VoucherCode) : null;
```

to this Expression:

```
Expression<Func<ConsumedReward, string>> converter = x => x.Reward is VoucherReward reward ? (reward. VoucherCode) : null;
```

The Problem is, that "An expression tree may not contain an 'is' pattern-matching operator"

---
#### Feedback Bot on 10/8/2020, 08:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by svick** [comment]
This is a subset of https://github.com/dotnet/csharplang/discussions/158.

**Comment by magnusbakken** [comment]
dotnet/csharplang#158 would be great, but might it be possible to stop the spurious suggestion in the meantime? I don't know how hard it is for an analyzer to detect if a piece of code under investigation is inside an expression tree?

**Comment by mrudat** [comment]
It would possibly be sufficient (but possibly expensive?) to sanity-check that the suggested edit doesn't contain any (new) errors? 

Ideally, a suggested, but erroneous edit that gets squashed due to sanity-check would get automatically reported as something to get a proper fix later.

**Comment by CyrusNajmabadi** [comment]
I don't get any suggestion for that here:

![image](https://user-images.githubusercontent.com/4564579/199588583-32e85cbb-b93c-4f37-883d-ea96ed3ddc23.png)
