### ISSUE TITLE
Source generators: no way to get Compilation from generated source code

### ISSUE THREAD

**Issue by lsoft** [dotnet/roslyn#48522]
My source generator needs to have access to the symbols from the source code passed to previous invocation of `AddSource`. Looks like there is no way to obtain that now.

```csharp
    [Generator]
    public class SGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var c2_before = context.Compilation.GetTypeByMetadataName("ConsoleApp13.SecondClass");  //null here

            context.AddSource(
                "1.cs",
                SourceText.From($@"
namespace ConsoleApp13
{{
    public class SecondClass {{ }}
}}
"
, Encoding.UTF8)
                );

            var c2_after = context.Compilation.GetTypeByMetadataName("ConsoleApp13.SecondClass"); //null here
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            
        }
    }

```

Could I ask to add this feature? :)

if I'm allowed to suggest the way, I guess a new method `public readonly struct GeneratorExecutionContext { public Compilation Compile(); }` would be fine. Programmer will be able to compile his/her intermediate sources to the Compilation at the time he wants/needs and have full access to its symbols. `GeneratorExecutionContext.Compilation` will always contains only the user supplied code (no changes here). However, any option will suit me :)

Thank you guys for your work!

**Comment by Youssef1313** [comment]
Until this is fixed, you can use the following as a *workaround*:

1. Refactor the source passed to `SourceText.From` into a constant or a variable (as appropriate).
2. Call `context.AddSource("1.cs", SourceText.From(yourVariableOrConstant, Encoding.UTF8));
3. Do the following to get a new compilation with your added source:

    ```csharp
    ParseOptions options = ((CSharpCompilation)context.Compilation).SyntaxTrees[0].Options;
    SyntaxTree sourceTree = CSharpSyntaxTree.ParseText(yourVariableOrConstant, (CSharpParseOptions)options);
    Compilation compilation = context.Compilation.AddSyntaxTrees(sourceTree);
    ```

4. To get the symbol, use the compilation introduced in the previous step:

    ```csharp
    var c2_after = compilation.GetTypeByMetadataName("ConsoleApp13.SecondClass");
    ```


When the issue is fixed, you can get back to your original code

**Comment by jaredpar** [comment]
``` cs
var c2_after = context.Compilation.GetTypeByMetadataName("ConsoleApp13.SecondClass"); //null here
```

This returning `null` is expected. The `Compilation` objects are all immutable hence given this is the initial `Compilation` that you are passed initially it does not have the source and hence will not return the new object. In order to get a symbol here you'd need to create a new `Compilation` that had the additional source. 

Can u elaborate a bit on why you need the symbol here? This is the first we've heard of this. It's possible there is a better route to achieve what you need here. 

@chsienki

**Comment by Youssef1313** [comment]
> This is the first we've heard of this. It's possible there is a better route to achieve what you need here.

@jaredpar Not really the first. The same thing was wanted by [this sample](https://github.com/dotnet/roslyn-sdk/blob/d7d6a76464f4f5a14a0ac7ec00384b372be19d80/samples/CSharp/SourceGenerators/SourceGeneratorSamples/AutoNotifyGenerator.cs#L45-L48) in dotnet/roslyn-sdk.

Added symbols are needed in nearly every source generator that generates something based on an attribute. I'll need the added attribute symbol to compare it with applied attributes in the original source.

**Comment by chsienki** [comment]
Currently there is no way to reference the symbols you add automatically. As @Youssef1313 notes, you can see in the AutoNotify sample that you need to create a new compilation that contains the generated attribute/class.

We're working on some designs that would allow you to provide certain sources upfront, which can then be referenced in the compilation provided during the execution phase. These are future designs though, so for now the correct option is to create a new compilation.

**Comment by lsoft** [comment]
@Youssef1313 @jaredpar @chsienki thanks for replies! I will probably use this workaround.


@jaredpar 

> The Compilation objects are all immutable

I know. Because of that I suggest to add a new method than returns `Compilation`, not `void`. Also, a new method is better than modifying `AddSource`, because it'll give us more flexible and performance.


> Can u elaborate a bit on why you need the symbol here? This is the first we've heard of this. It's possible there is a better route to achieve what you need here.

Sure. Imagine that I have a program with `class A {  }`, and I need a source generator that creates a new class like `class B { public B(A a) {...} }`. I.e. class produced by generator takes 'normal' class as its dependency. At this time everything is OK, I have access to the symbol `A` and able to produce `B` with comfort))

Let's make the situation complex a bit. Imagine that I need a source generator that can generate a chain of classes, i.e.

```
// these classes are 'normal' classes from the application
class A1 {}
class A2 {}

//the following are produced by generator:
class B { public B(A1 a1) {...} }
class C { public C(B b, A2 a2) {...} }
```

As you can see, when I produce `B` I'm using **symbols**, but when I progress to produce `C` I need a new algo that working with *something* else (sources?), because I haven't symbols for `B`. So I need **2 algorithms** to complete one task.

(this example is not a theoretical construction, I need it in practice already. I can add details if it required)

The most important thing I would like to emphasize: **This need will always appear if you need to process both 'normal' classes and generated ones with one algorithm. From my point of view this is not a very rare need as it might seem at first glance.**

@chsienki 

> we're working on some designs that would allow you to provide certain sources upfront, which can then be referenced in the compilation provided during the execution phase

If I understand you correctly you're talking about some 'constant', predefined code. Unfortunately that design won't help me...


Could I ask your team to discuss this proposal and make the resolution?

**Comment by lsoft** [comment]
That workaround is a viable option for me, but it means that the same generated code will be compiled twice. It's ok for workaround, but not the best for the production. As we can see at the dotnet/roslyn-sdk this need has already been recognized at Microsoft. I hope your team gives a green light to this proposal))

Again, thanks for your comments!

**Comment by jaredpar** [comment]
I'm still unclear why you need symbols here though. In this case you're generating source hence why do you need a symbol in order to write text?

**Comment by Youssef1313** [comment]
@jaredpar To generate source based on a specific attribute that is added in the start of generation process.

**Comment by jaredpar** [comment]
Presumably the generator understands it added the attribute though. It seems much simpler to record that and use that information to make subsequent code generation decisions instead of creating intermediate `Compilation` and querying for symbols. 

The reason for pressing on this is getting symbols is not free. Generators which depend on creating N different intermediate symbols to generate a final source file are going to be slower than ones that use the single `Compilation` that we provide. Particularly when you consider scenarios where a compilation has more than one generator associated with it. 

Making it easy to create intermediate `Compilation` here is essentially feeding into a design pattern that can negatively impact performance.

**Comment by Youssef1313** [comment]
@jaredpar I couldnt get the alternative you're describing. I think if the sample in roslyn-sdk is updated to the solution that performs better, it will be very helpful.

**Comment by jaredpar** [comment]
Based on what you described my understanding is there is a single generator here, it is adding an attribute to a class and wants to change later generation behavior based on that attribute. Rather than query the compilation here for the attribute the generator should just note that it added this attribute.

**Comment by Youssef1313** [comment]
> it is adding an attribute to a class

The source generator adds the attribute definition itself, and doesn't apply it to anything.
The source generator consumer can then add the attribute to some declarations, and the source generator is looking for those declarations where the developer has applied the attribute.

To know what declarations have the attribute, I should get the attribute symbol. But because the attribute symbol is added by the generator, it's not included in the initial compilation.

**Comment by jaredpar** [comment]
I'm not sure how better to state my point here but I feel like we're missing something in our communication here. 

The generator is in total control of all of the contents that it is adding to the compilation. If the generator adds an attribute and wants to later take advantage of that then it can record that as part of it's generation process. If the generator wants to know which types have the attribute then it can also record that as it emits the types. Basically the generator can keep a record of the types and combinations it's generated and then access that to make later generation decisions. If the generator defaults to constantly creating `Compilation` and querying them it's adding  work that can likely be done much more efficiently with some internal book keeping.

**Comment by Youssef1313** [comment]
> Basically the generator can keep a record of the types and combinations it's generated and then access that to make later generation decisions.

Let's focus specifically on this part. If the generator defined an attribute, how it can access it *without* creating a new compilation? I don't see an obvious way to do that.

The sample in roslyn-sdk states the same. So basically, if that's wrong, then the sample needs to be updated.

**Comment by lsoft** [comment]
@jaredpar Thanks for the discussion, I hope I didn't take too much of your time. 

> I'm still unclear why you need symbols here though.

My task is different from that of Youssef1313. Let me describe my actual task. Maybe it will become clearer.

I recognized that source generators are very helpful to write a new-generation DI container with very good (probably - the best) performance. (please don't laugh, this is a very interesting project :) )

So, I have

```csharp
public interface IA { }
public class A : IA {  public A(string arg0, int arg1) { ... } }
```

And I need to generate the body of DI container (a work for my source generator):

```csharp
public class DIContainer
{
    public IA Get() => new A(hardcodedarg0, hardcodedarg1);
}
```
(too simple to be a real DI container, but enough to understand my need)


So, at this point I have an algorithm 1

### Algorithm 1

incoming: interface symbol and class symbol (for example: IA, A)
Step 1. Generate syntax `public IA Get() => new A(hardcodedarg0, hardcodedarg1);` based on incoming symbols
End of algorithm.


So far so good. Then I want to implement a new feature: `ToFactory`; I have the following:

```csharp
public class A  {  public A(string arg0, int arg1) { ... } }

public interface IAFactory { A CreateA(int arg1); }

```

The task is to generate `AFactory`, after that - to generate `new AFactory(...)` clause. I have an algorithm 2:

### Algorithm 2

incoming: symbols (A, IAFactory)
Step 1. Generate the factory's body:
```csharp
public partial class AFactory : IAFactory
{
     private readonly string _arg0;

     public AFactory(string arg0) { _arg0 = arg0; }

     public A CreateA(int arg1) {  return new A(_arg0, arg1);   }
}
```

Step 2. Generate syntax `public IAFactory Get() => new AFactory(hardcodedarg0);` based on `IAFactory` symbol **and information about `AFactory` with _different_ structure** (I have no symbols for `AFactory`, but I know everything about it of course).
End of algorithm.



At this point, imagine we have access to the intermediate compilation, so I'm able to switch to algorithm 3.

### Algorithm 3

Step 1. Generate the factory's body (as previous).
Step 2. Obtain an intermediate compilation with new symbols (`AFactory`).
Step 3. Invoke Algorithm 1 with these symbols.
End of algorithm.

Implementation `ToFactory` with algo 3 is simpler that with algo 2. But (you're right) is slower too. I don't like algo 2 because I must implement 2 different algos for one goal.

> why do you need a symbol in order to write text?

I need symbols because I need to know about full names of the types, constructors, its arguments, explicit values, etc... For example, it's impossible to write `new` clause without knowledge about constructors.

> can negatively impact performance

Your statement about performance issues is fully clear for me. I totally agree with that. But we can mitigate this effect by 
1. **do not** perform additional compilation in `AddSource` method
2. adding additional method `Compilation PerformIntermediateCompilation();`

Correct?

In my case: user of DI container typically creates more that 1 factory, so I'm able to make design with only 1 additional compilation: generate bodies of all factories -> perform the compilation -> generate `new` clauses based on new symbols. Looks acceptable for me...

Let me add one more point to the performance aspect.
As everyone knows, the code produced by generators is very different from the code written by a programmer. Probably it would be great if Microsoft releases a document with recommendation and best practices about using source generators.
I see at least 3 section of that document:

-------------------------------------------------------------------------------------------------------------------
Section 1. Recommendations related with dotnet/runtime
1. Avoid to create a superclasses that implements a lot of interfaces, because (in some cases) casting is O(n) operation (https://github.com/dotnet/runtime/issues/43199)
2. ...

Section 2. Recommendations related with dotnet/roslyn
1. Avoid to create a class with a lot of members (https://github.com/dotnet/roslyn/issues/18631#issuecomment-354681896), split this class into few classes if it possible.
2. ...

Section 3. General recommendations
1. Avoid to invoke `PerformIntermediateCompilation` if it possible, because `PerformIntermediateCompilation` makes your generator slower etc etc
2. ...
-------------------------------------------------------------------------------------------------------------------

With this document we can reduce performance issues and allow the community to generate better code in their generators.

To be clear: I do not insist on this feature and just ask you to discuss it inside your team. Source generators is a very great feature! Thanks for it.

**Comment by jaredpar** [comment]
> Let's focus specifically on this part. If the generator defined an attribute, how it can access it without creating a new compilation?

It can't access the attribute without creating a new `Compilation`. My point though is what value exists in accessing that symbol? What can you do with it? A source generator can only do two operations:

1. Generate code 
1. Generate diagnostics

There is no need for the symbol to generate further code that can't be done instead by simple book keeping.

**Comment by Youssef1313** [comment]
> My point though is what value exists in accessing that symbol? What can you do with it?

I need the symbol to compare it with existing attributes. To be more specific about my scenario (which is different than the OP scenario - but both needs the same thing):

1. My source generator adds the following source:

    ```csharp
    public static readonly string AttributeSourceCode = @"using System;
    namespace Generator
    {
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
        public sealed class PrintMembersAttribute : Attribute
        {
            public bool ShouldInclude { get; set; } = true;
        }
    }
    ";
    ```

2. The generator consumer should apply the attribute to fields/properties based on his needs.

3. The generator should generate source based based on **where** the attribute in step 1 is added in the source.

4. To achieve the previous step, I need to do something similar to:

    ```csharp
    everyCandidateSymbolInSource.GetAttributes().FirstOrDefault(attr => SymbolEqualityComparer.Default.Equals(theAddedAttributeInStepOne, attr.AttributeClass)
    ```


As I mentioned previously, the AutoNotify sample in dotnet/roslyn-sdk repository does similar thing. If this is not the correct way to approach this scenario, the sample should be updated with the recommended practice.

**Comment by chsienki** [comment]
@Youssef1313 this is the correct way to do this today. As I said, specifically for this attribute kind of case we have some ideas about how to improve it in the future, but until we add any new APIs the sample shows the current best practice.

@lsoft In terms of your proposed API, it doesn't really buy you anything. We could make `AddSource` return an updated compilation, but we wouldn't be able to share it with any of the other generators, as that would 'leak' generation state between the generators, and we explicitly run them in an undefined order. And in the case you *dont* need the returned compilation, we'd just be doing unnecessary work.  Given that you can still achieve the same thing by adding it to the compilation yourself, I suspect we're unlikely to add such an API.

You can always create an extension method if you want to emulate having such an API:

```csharp
public static class ContextExtension
{
    public static Compilation AddSourceAndGetCompilation(ref this GeneratorExecutionContext context, string name, SourceText text)
    {
        context.AddSource(name, text);
        return context.Compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(text, (CSharpParseOptions)context.ParseOptions));
    }
}
```

And use it like:
```csharp
context.AddSourceAndGetCompilation("hintName", SourceText.From(generatedCode, Encoding.UTF8));
```

**Comment by lsoft** [comment]
> I suspect we're unlikely to add such an API.

I'm completely fine with it. My needs are solved with the workaround suggested by @Youssef1313 and you.  


Thanks for the helpful discussion!

**Comment by Youssef1313** [comment]
@chsienki Was it considered to find a way to ship a class in a source generator project and make it normally consumable? i.e. the attribute definition isn't added while the generation process, but existing in the original compilation?

A workaround that comes to my mind (not yet tested) is to force consumers to have 2 package reference (one containing the source generator, and the other containing the attribute only).

**Comment by chsienki** [comment]
@Youssef1313 Yep, you can absolutely do this. You have two options:

- Ship a runtime library, and a parallel generator library:
  - Have the classes you need in the runtime lib
  - Make the runtime NuGet depend on the generator NuGet

- Use the same assembly for both runtime and generation:
  - If you're using `ProjectReference` you can set   `ReferenceOutputAssembly="true"` to also reference the assembly
  - If using NuGet you just package it in both the analyzers and ref folder

One thing to consider is the complexity of the runtime code though. Ultimately you're forcing a user to ship another assembly in their application: if you're only using the attributes at compile time, then it's a completely redundant dependency. This really only makes sense when you have some runtime logic that the generator automatically hooks up to.

**Comment by kzu** [comment]
I might also add that if the attribute is entirely static (as is shown in the sample by @Youssef1313, it could simply be a contentFile in the nuget that packs the analyzer/source generator. This way, it will always be present by the time the generator runs.

IMHO, much simpler and equally effective (and mostly hidden from consumers too, since you can [hide the file from the solution explorer](https://til.cazzulino.com/dotnet/hide-contentfiles-from-your-nuget-packages))
