### ISSUE TITLE
Remove unnecessary cast changes the code behavior

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48521]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1210214/remove-unnecessary-cast-changes-the-code-behavior.html)._

---
[severity:It bothers me. A fix would be nice]
I had a small piece of code that converts a char to a 2-digit hex number:

private static string FormatChar(char c)
		{
			return $"{(int)c:X2}";
		}

This works as expected and converts the char 'z' to "7A".

After I run Code Cleanup or use the suggestion to "Remove unnecessary cast", the code changes to:

private static string FormatChar(char c)
		{
			return $"{c:X2}";
		}

but returns a different result: char 'z' will be converted to "z".

---
#### Feedback Bot on 10/8/2020, 08:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/45700.
