### ISSUE TITLE
Add documentation for Regex and Json diagnostic analyzer (RE0001, JSON001, JSON002)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#48530]
https://github.com/dotnet/roslyn/blob/04481d230843e11e010c1c25bb8f132389eccdba/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/AbstractRegexDiagnosticAnalyzer.cs#L22

1. Follow the steps at [Contribute docs for 'IDExxxx' rules](https://docs.microsoft.com/contribute/dotnet/dotnet-contribute-code-analysis#contribute-docs-for-idexxxx-rules) to add documentation for `RE0001` to [dotnet\docs](https://github.com/dotnet/docs) repo.

2. Remove the workaround in `DiagnosticHelper.GetHelpLinkForDiagnosticId` for `RE0001`

**Comment by Youssef1313** [comment]
The test for checking help links may be unskipped after documenting this. See https://github.com/dotnet/roslyn/pull/51690

**Comment by mavasani** [comment]
Closing as duplicate of https://github.com/dotnet/roslyn/issues/65771
