### ISSUE TITLE
Comment splitting doesn't account for manual comment splitting

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#48547]
**Version Used**: 4ed9289

**Steps to Reproduce**:

Press <kbd>Enter</kbd> at the `$$` location.

```csharp
// This is a$$// split comment
```

**Expected Behavior**:

```csharp
// This is a
// split comment
```

**Actual Behavior**:

```csharp
// This is a
// // split comment
```

**Comment by sharwell** [comment]
@CyrusNajmabadi This is a regression introduced by #48217. We should fix it before the feature ships to the public in 16.9 Preview 1.

**Comment by Youssef1313** [comment]
Also consider `// This is a$$/* split comment*/`

**Comment by sharwell** [comment]
@Youssef1313 that's going to be a much less frequent case. The form I posted is what many people will already be doing prior to the new feature.
