### ISSUE TITLE
Make `IDocumentationCommentSnippetService` public

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#48559]
Today, `IDocumentationCommentSnippetService` is internal, in the EditorFeatures layer, which means external developers (such as omnisharp) cannot take advantage of auto-generating doc comments. https://github.com/dotnet/roslyn/pull/48558 moves the service down to the features layer, but we should also consider making it public.

**Comment by CyrusNajmabadi** [comment]
Needs to go through API review.
