### ISSUE TITLE
Unintuitive diagnostic when missing `>` in type argument list

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#48566]
**Version Used**: 941dc7e91c835e4f230a8274e0aab2b0fb51ac93

**Steps to Reproduce**:

```cs
using System.Collections.Immutable;

public class C {
    public void M(ImmutableArray<int arr) {
    }
}
```

**Expected Behavior**: Syntax errors, and perhaps some binding errors about e.g. unexpected number of type arguments, or 'arr' is not a type, or any number of things depending on how we happen to do error recovery in this scenario.

**Actual Behavior**:
```
    error CS1003: Syntax error, ',' expected
    error CS1003: Syntax error, '>' expected
    error CS1001: Identifier expected
    error CS0308: The non-generic type 'ImmutableArray' cannot be used with type arguments
    error CS0246: The type or namespace name 'arr' could not be found (are you missing a using directive or an assembly reference?)
```

I think the only error of concern in the actual output is `error CS0308: The non-generic type 'ImmutableArray' cannot be used with type arguments`. It feels like it would be better if we gave `error CS0305: Using the generic type 'ImmutableArray<T>' requires 1 type arguments`.

**Comment by CyrusNajmabadi** [comment]
This is a type-only location (i.e. not a place where expressions can go).  So we can likely improve error recovery here *enormously*.  What's likely going wrong is that the parser consumes 'int' and hten doesn't know what to do.  It can either finish the argument list, or think it has a missing comma nd continue.  It's taking the latter approach.  Tha'ts what we'd want for `Dictionary<int string> foo`, but not this case.  We should attempt to look forward a bit to determine which is the better recovery path to take here.
