### ISSUE TITLE
IDE0063 code fixer deletes comments nearby using statement or curly braces

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn#48586]
**Version Used**: Visual Studio 2019 Version 16.7.5

**Steps to Reproduce**: 
1.  Write a following code, which has an `IDE0063 'using' statement can be simplified`:
```cs
using System;
using System.IO;

class C
{
    static void Main()
    {
        using (var s = new MemoryStream()) // foo
        { // bar
            Console.WriteLine(s.CanRead); // Only this comment remains.
        } // baz
    }
}
```
2. Apply  the `Use simple 'using' statement`

**Expected Behavior**:
All comments remain like this:
```cs
using System;
using System.IO;

class C
{
    static void Main()
    {
        using var s = new MemoryStream(); // foo
        // bar
        Console.WriteLine(s.CanRead); // Only this comment remains.
        // baz
    }
}
```

**Actual Behavior**:
"foo", "bar", "baz" comments are deleted:
```cs
using System;
using System.IO;

class C
{
    static void Main()
    {
        using var s = new MemoryStream();
        Console.WriteLine(s.CanRead); // Only this comment remains.
    }
}
```

**Comment by CyrusNajmabadi** [comment]
We would take a targetted PR that updated things to have this behavior.

**Comment by louis-z** [comment]
I can take a look at it.

**Comment by louis-z** [comment]
> **Expected Behavior**:
> All comments remain like this:
> 
> ```cs
> using System;
> using System.IO;
> 
> class C
> {
>     static void Main()
>     {
>         using var s = new MemoryStream(); // foo
>         // bar
>         Console.WriteLine(s.CanRead); // Only this comment remains.
>         // baz
>     }
> }
> ```

Ok, so I managed to resolve the issue, but instead I get aligned comments as follows:

```cs
using System;
using System.IO;

class C
{
    static void Main()
    {
        using var s = new MemoryStream(); // foo
                                          // bar
        Console.WriteLine(s.CanRead); // Only this comment remains.
                                      // baz
    }
}
```

If that sounds acceptable, I'll gladly submit a PR.
