### ISSUE TITLE
Cannot use `ptr is null` for `T* where T : unmanaged`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#48591]
`is null` and `is not null` are allowed for `int*` but not `T* where T : unmanaged`.

```C#
class Program
{
    unsafe static void F1(nint i)
    {
        int* p = (int*)i;
        _ = p == null;
        _ = p != null;
        _ = p is null;
        _ = p is not null;
    }

    unsafe static void F2<T>(nint i) where T : unmanaged
    {
        T* p = (T*)i;
        _ = p == null;
        _ = p != null;
        _ = p is null;     // error CS0037: Cannot convert null to 'T*' because it is a non-nullable value type
        _ = p is not null; // error CS0037: Cannot convert null to 'T*' because it is a non-nullable value type
    }
}
```

**Comment by cston** [comment]
See https://github.com/dotnet/roslyn/pull/48585#discussion_r504771996

**Comment by 333fred** [comment]
This appears to be working, will add a test to cover: https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMACdBGAdgFgAoAb1OyuwFcYBnCAMwFNc8A2XAFmwDE8AChiwALtigBKStQolqCiTFEAqbAAdsAXmyCxKyVADcMxdgD62jdp0waAG3sn5Zi1c0BCWw6enFlnU0oemw7R2dXN0CJEJgAe3Ew3xcqAF9SPzpGVnYudF4+TAAeABUAPmExCUlsAHcACxYAJzYS7BBaGEgYCABzFgQ/OUiStU0dQVHDCNcA6y1vcL8FOc9F5MjVmNCfI0UAen3sZqa4puwAYQBlAAYbgGYCDouIGHjxAGM4mAA3ZsSfNhRHFsAByUag7DAFgfCA0ehsKDiYLYCChb4AWiSEGA9jYPwg9hobFEAE91CxltQtij3jtwthDscmqdztc7o9nq86V9fv96fYgSDwSpIdDYfDEciQmj4jAsT4cXjsASiSTyZSUth0iRUkA=.
