### ISSUE TITLE
Support textDocument/foldingRange for C# LSP

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#48600]
Razor's C#'s support is driven by C#'s LSP range of support. Razor [recently got an issue](https://github.com/dotnet/aspnetcore/issues/26893) from a customer indicating that they wanted C# folding range support for `#region` tags. After a brief conversation with @dibarbet it looks like this support is currently driven by the VS client. This issue encompasses moving that support from client to server.

**Comment by NTaylorMullen** [comment]
One interesting thing to consider with this issue is how local & LSP server folding ranges interoperate. Aka, if you still have your client side folding range provider going and you also have your server going what happens? In Razor we'll especially need to consider this because we have multiple languages where some are powered by TextMate and some by the LSP requests

**Comment by dibarbet** [comment]
I would expect that we would not do outlining client side if we provide them via LSP (so that would mean in codespaces for C# files and razor can also call the LSP server to retrieve them for razor documents).  How you join those with ones provided by textmate on razor files I can't say, but there shouldn't be conflicts in the normal c# case

**Comment by NTaylorMullen** [comment]
> I would expect that we would not do outlining client side if we provide them via LSP (so that would mean in codespaces for C# files and razor can also call the LSP server to retrieve them for razor documents). How you join those with ones provided by textmate on razor files I can't say, but there shouldn't be conflicts in the normal c# case

Ah, fair enough, that sounds like a great plan!
