### ISSUE TITLE
Making roslyn run in single-thread mode

### ISSUE THREAD

**Issue by roterdam** [dotnet/roslyn#4860]
Roslyn will sometimes use all my cores and disturb other process on my machine.

Is it possible to use configuration to make Roslyn use only one thread?

**Comment by gafter** [comment]
Are you asking about the compiler specifically?

**Comment by roterdam** [comment]
Yes.

**Comment by gafter** [comment]
Use the command-line flag `/parallel-` or `/p-`. I believe you can place that in the standard `.rsp` files where the compilers are installed.

**Comment by gafter** [comment]
Please let me know whether or not that addresses your issue.

**Comment by roterdam** [comment]
This does, thank you.
