### ISSUE TITLE
Allow FixAll to continue working on other violations when it crashes

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48607]
I came across a scenario where I've **lots** of some rule violations, which has a codefix. The codefix had a bug that makes it crash on a very certain case. When I attempt to do a Fix all in solution, it doesn't fix any, while it *could* fix some.

I think it's much better experience if some violations are skipped and some are fixed, rather than skipping all of them.

**Comment by CyrusNajmabadi** [comment]
> I think it's much better experience if some violations are skipped and some are fixed, rather than skipping all of them.

I honestly don't agree.  Crashing is bad.  It feels very wonky and potentially bad to just try to limp through this and end up in some inconsistent state.  I would much rather have us do nothing than do some partial amount of work that may leave you in a completely unknown and inconsistent state.

In other words, there's no reason to think that partially applying a fix-all leaves you in any sort of good state.  If a crash happens, it's better to not have done anything then to lave the user in that intermediary state.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi That's reasonable. But probably not everyone will want this behavior.
I would suggest that a dialogbox is shown saying "'{0}' codefix has crashed. Do you want to continue fixing other violations"?
Then the user has to make the choice.

**Comment by ryanbrandenburg** [comment]
**Design Meeting Notes**: We should improve the error messages here both so that users can file better bugs and so they have the chance to work-around whatever fix is going off the rails.

**Comment by sharwell** [comment]
I filed #49672 for improving the error messaging.
