### ISSUE TITLE
Ctrl+Q and GoTo in CodeSpaces doesn't start until the user opens a file

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#48609]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 main
Version 16.9.0 Preview 1.0 [30612.38.main]

**Steps to Reproduce**:

1. Connect to a C# CodeSpace instance
2. Open a solution
3. Without opening any files, focus Ctrl+Q or GoTo and Search for a symbol.

**Expected Behavior**:
Symbol results should appear (might take a few seconds).

**Actual Behavior**:
Only file results are visible.

Doesn't appear to repro in the local Roslyn scenario or with C++ in Nexus.

**Comment by CyrusNajmabadi** [comment]
Sounds like a platform issue.

**Comment by gundermanc** [comment]
>Sounds like a platform issue.

File path search provider lights up correctly on the server side and its results appear on the client, so it's not a problem with the search brokered service that remotes items in both experiences.

The next culprit would be the LSP client, though the C++ version of this feature works fine in CodeSpaces, so it seems unlikely to be LSP related.

Remaining possibly at-fault components are:

- LiveShare: I'm not aware of anything LS does special here, but my C++ scenario is an 'open folder' vs. a 'solution', so that's a possible contributing factor.
- Roslyn: in the local scenario, Roslyn is explicitly loading itself via ILanguageClientBroker.LoadAsync() on package load, because our LSP client cannot activate LSP servers just by virtue of a file type being in the solution, due to a Visual Studio project system limitation. My guess is that this LoadAsync() path doesn't exist or doesn't get called in CodeSpaces scenarios.
