### ISSUE TITLE
Report compiler issue

### ISSUE THREAD

**Issue by hdu7** [dotnet/roslyn#48610]
# Report a .net core compiler issue
# Description:
I have an object, and that object has an property GSMPortID, and I use 'if else' to update property GSMPortID, since the conversationChannel is not null, it should never run into the block of 'else,' but code run into 'else' block at the line of 356

![Capture](https://user-images.githubusercontent.com/67653788/93603767-76174780-f992-11ea-84fc-465e160ec98a.PNG)

**Comment by CyrusNajmabadi** [comment]
you'd have to provide a repro program where this happens.
