### ISSUE TITLE
[Question] Why isn't this optimized by the compiler?

### ISSUE THREAD

**Issue by JustNrik** [dotnet/roslyn#48613]
```cs
public class Foo
{
    public int Value { get; } = 1;

    public Foo()
    {
        Value = 2;
    }
}
```
IL Gen of the ctor:

```
    .method public hidebysig specialname rtspecialname 
        instance void .ctor () cil managed 
    {
        // Method begins at RVA 0x2058
        // Code size 21 (0x15)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: ldc.i4.1
        IL_0002: stfld int32 Foo::'<Value>k__BackingField'
        IL_0007: ldarg.0
        IL_0008: call instance void [System.Private.CoreLib]System.Object::.ctor()
        IL_000d: ldarg.0
        IL_000e: ldc.i4.2
        IL_000f: stfld int32 Foo::'<Value>k__BackingField'
        IL_0014: ret
    } // end of method Foo::.ctor
```

It sets the backing field twice, same happens in the jit asm, I'm curious to know why isn't this optimized?

**Comment by jaredpar** [comment]
It's a question of priorities. In this specific, extremely narrow, case yes the compiler could reasonably remove the redundant set. At the same time there are two issues with this:

1. This is only the case in this very specific narrow example. If there is practically any other code before the `Value = 2` statement, any other initializers, `base` calls, etc ... then the optimization cannot be performed 
1. This is essentially saying "why don't we optimize bad code" where as traditionally we'd think of this as "maybe we should add an analyzer to spot bad coding patterns"

Essentially this specific case could be optimized but it's very narrow and not worth the cost o doing so.
