### ISSUE TITLE
How do I retreive C# "value" keyword from the syntax?

### ISSUE THREAD

**Issue by per-samuelsson** [dotnet/roslyn#4861]
Hi,

Whats the story with the C# **value** keyword? Seems just impossible to access to from the public API? Is it because its contextual?

I do find it hidden in the implementation (most specifically in [ParameterSymbol](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/ParameterSymbol.cs#L20)), but nowhere in the public API's?

As an example, I would have expected it in `SyntaxKind`, along with the other keywords (i.e. something like `SyntaxKind.ValueKeyword`).

**Comment by gafter** [comment]
It isn't a keyword. Its just an identifier.

**Comment by per-samuelsson** [comment]
Thanks for answering!

> It isn't a keyword. Its just an identifier.

According to [this C# reference](https://msdn.microsoft.com/en-us/library/a1khb4f8.aspx), it's a keyword.

> The contextual keyword value ...

But fine, I can live with your answer I guess. I just think its a small detail that could be added to the API, keyword or not. Consider tools that are creating properties on the fly (based on CodeAnalysis). For such it would be handy to access that word, since it in fact do have a certain meaning.

**Comment by per-samuelsson** [comment]
Out of curiosity, I had to go to the spec. :sweat_smile: 

From Ecma-334, C# specification:

> The following identifiers have special meaning in the syntactic grammar, but they are **not keywords**: add (§17.7), alias (§16.3), get (§17.6.2), global (§16.7), partial (§17.1.4), remove (§17.7), set (§17.6.2), **value** (§17.6.2, §17.7.2), where (§25.7), and yield (§15.14). For convenience and clarity, these identifiers appear as terminals in the syntactic grammar; however, they are identifiers. [Note: As a result, unlike keywords, these identifiers can be written with a @ prefix and can contain unicode-escape-sequences. end note]

So the page I referenced is obv wrong.

**Comment by gafter** [comment]
No, it is correct that it is a *contextual keyword*, but not a *keyword*. Roslyn's syntactic model only contains explicit support for contextual keywords for which the context is syntactic. That is why the syntactic model doesn't tell you about the contextual keywords `var` and `value`. In any case all of the contextual keywords are identifiers.

**Comment by per-samuelsson** [comment]
Thanks for taking the time to elaborate on that, @gafter. Makes total sense when laid out like that.

**Comment by ddrdoubled** [comment]
Sorry to open this up again, but I think since then a `SyntaxKind.VarKeyword` has been added if I am not mistaken. Is there any reason to leave `value` still out? Because when I look on the list above all other contextual keywords have been added, or not?

**Comment by CyrusNajmabadi** [comment]
>  Because when I look on the list above all other contextual keywords have been added, or not?

They have not been.  Similar to `value`, neither `unmanaged` nor `dynamic` are kinds.  They're really just keywords.  `var` is unfortunate, but c'est la vie.

**Comment by ddrdoubled** [comment]
```
/// <summary>Represents <see langword="unmanaged"/>.</summary>
        UnmanagedKeyword = 8446,
```

**Comment by CyrusNajmabadi** [comment]
Oh, `managed` became a contextual keyword with function-pointers.  

> I would like just to understand why some and not the other ones?

Because it's an actual strongly typed token when placed in another construct.  e.g. the FunctionPointerCallingConventionSyntax actually has a specifier which is either `managed` or `unmanaged`.  It's not like this can be any identifier, and that these two identifiers then have special semantic meaning.  It can only be those two identifiers *in that context*.

But `value` is not some sort of special construct.  It is literally just an identifier, and it's treated as such in the language at the syntactic level (unlike `unmanaged`).  Similar to `dynamic`, it has no impact/meaning syntactically *regardless* of context.  It's only semantically that it gains meaning.  So there's no syntax-kind because it's not special at the syntax level.

`var` is honestly the bizarre one.  We messed that up IMO.

**Comment by ddrdoubled** [comment]
ok understood, but that also means, that implementing it to support it in the `SyntaxFactory` should be rather small task, I am just trying to find a better way than doing this:
```
IdentifierName("value")
```
and i would prefer instead this:
```
IdentifierName(Token(SyntaxKind.ValueKeyword))
```
this would still result in an `IdentifierToken` for `value` but it would be consistent with other IdentifierToken generation

**Comment by CyrusNajmabadi** [comment]
> I am just trying to find a better way than doing this:

This is what our own parser (and higher layer) do, so i don't see the problem with that code :)

As all this sytnax is immutable.  you can also just do this once, like so:

```c#
private static readonly IdentifierNameSyntax ValueIdentifierName = IdentifierName("value");
```

And then just reference `ValueIdentifierName` everywhere.
