### ISSUE TITLE
EnC: Support records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#48630]
https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs#L1573

Currently, TryGetDisplayNameImpl will return `null` for records. It will then throw an exception in:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/CSharp/Portable/EditAndContinue/CSharpEditAndContinueAnalyzer.cs#L1570-L1571

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/51926. Closing.
