### ISSUE TITLE
EnC: Adding/updating/removing attribute on local function, its return type or parameter should be rude edit

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48636]
**Version Used**: 
Version 16.9.0 Preview 1.0 [30614.203.main]

It is currently rude edit to add/update/remove attributes on any member/parameter/return value, so for consistency we should report this rude edit on local function attributes as well.

Once support changing attributes we should remove the rude edit for local functions as well. Runtime support is required for such feature, so the rude edit would stay for .NET Framework apps.

**Comment by lambdageek** [comment]
This includes compiler generated attributes like changing a `ref` arguments to `in`?  or changing `object` to `object?` ?

**Comment by tmat** [comment]
Both updates are currently treated as rude edits. Since the actual signature does not change we should consider allowing these changes.
