### ISSUE TITLE
Records type definition identifier is not classified correctly

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48643]
**Version Used**: 

Version 16.9.0 Preview 1.0 [30614.203.main]
**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/41759/96177414-b65edc80-0ee2-11eb-9adc-edfdb68f61b0.png)

**Expected Behavior**:

The color of X in the class definition and C in the record definition is the same.

**Comment by CyrusNajmabadi** [comment]
@allisonchou you have the PR for this right?

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/pull/47960

**Comment by allisonchou** [comment]
Yep, this should be resolved by #47960 which is just waiting for insertion into VS main.
