### ISSUE TITLE
ENHANCEMENT REQUEST:  Smarter Memory Management via the Compiler and Variable tracking

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#4864]
Hi Roslyn Team:
I have bumped into this issue a number of times on different projects and I'm sure that other .NET developers are running into the same thing without even knowing it.

In .NET, the CLR uses reference counting so that garbage collection knows that, when an item's references equals equals zero, it can be garbage collected.  This works, but there is an optimization that can be implemented to decrease memory usage even more:

I have seen code like this many times:
```javascript
private static void DoProcess() {
  var Data = Load_a_ton_of_data();
  var Result = Process_a_ton_of_data(Data);
  Do_a_long_running_task(Result);
}
```

Using reference counting, the memory for Data will stay allocated for the entire length of the Do_a_long_running_task method because of the reference to Data.  However, by us looking at the code, we know that Data is never used again and can be explicitly deallocated as soon as Result is called.  To get around that, often times we just do something like this in our code:

```javascript
private static void DoProcess() {
  var Data = Load_a_ton_of_data();
  var Result = Process_a_ton_of_data(Data);
  Data = null; //Now I'm doing my own memory management.
  Do_a_long_running_task(Result);
}
```

However, that defeats the point of having memory management.

I suggest enhancing the C# and VB.NET compilers to keep track of reference variables within methods and explicitly null them out after their last use.

Also, if the object implements IDisposable, that would be a good time to dispose of it as well.

**Comment by svick** [comment]
> In .NET, the CLR uses reference counting

No, it does not. The CLR uses [tracing GC](https://en.wikipedia.org/wiki/Tracing_garbage_collection).

> the memory for Data will stay allocated for the entire length of the Do_a_long_running_task method because of the reference to Data

It won't, at least not necessarily. The .Net GC is smart enough to know that while `Do_a_long_running_task` is executing, `Data` can no longer be accessed. So if a garbage collection (of the right [generation](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_.28ephemeral_GC.29)) happens during that time, `Data` will be collected.

> if the object implements IDisposable, that would be a good time to dispose of it as well

No, it would not. `IDisposable` is for *deterministic* cleanup. If you really need something like this (and it's very likely that you don't), use a finalizer.

**Comment by HaloFour** [comment]
@svick

GC is smart enough to know that it could collect `Data` while `Do_a_long_running_task` is executing if `Data = null` is omitted?

**Comment by svick** [comment]
@HaloFour As far as I know, yes, it is (at least in Release mode).
