### ISSUE TITLE
Generic casting problem

### ISSUE THREAD

**Issue by NichUK** [dotnet/roslyn#48656]
### Description

I wasn't sure whether to post this here, or if it belonged elsewhere for the language or VS teams... If I'm in the wrong place, please let me know where I should post it!

When running the code snippet below, I would expect it to compile without the necessity of the double cast on line 44. 
With it, it seems to compile and run just fine.

VS 16.8.0 Preview 3.2, 
NetStandard 2.1
tried both C#7 and 8

```
using NUnit.Framework;

namespace Generic.Test
{
    public interface IPersistable
    {
    }

    public interface IPersistable<TDto> : IPersistable where TDto : PersistableBase
    {
        string Name { get; set; }
        TDto ToDto();
    }

    public interface IDto
    {
        T FromDto<T>() where T : IPersistable, new();
    }

    public abstract class PersistableBase : IDto
    {
        public abstract T FromDto<T>() where T : IPersistable, new();
    }

    public class Thing : IPersistable<ThingDto>
    {
        public string Name { get; set; }

        public ThingDto ToDto()
        {
            return new ThingDto()
            {
                Name = Name,
            };
        }
    }

    public class ThingDto : PersistableBase
    {
        public string Name { get; set; }
        public override T FromDto<T>()
        {
            // this seems wrong - surely it should compile without going via IPersistable cast
            return (T)(IPersistable)new Thing()
            {
                Name = Name
            };
        }
    }

    public class GenericTests
    {
        [Test]
        public void ShouldCreateADtoFromAThing()
        {
            var thing = new Thing()
            {
                Name = "Nich"
            };

            var dto = thing.ToDto();
            Assert.That(dto, Is.Not.Null);

            var convertedThing = dto.FromDto<Thing>();
            Assert.That(convertedThing, Is.Not.Null);
            Assert.That(convertedThing, Is.TypeOf<Thing>());
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out as this is as per the language specification.  There is no conversion from your type to that type parameter.  However, the language does allow conversions from interfaces to and from these different types.   You can see all the rules on conversions here: https://github.com/dotnet/csharplang/blob/master/spec/conversions.md

**Comment by NichUK** [comment]
Thanks @jkotas and @CyrusNajmabadi.
Looking at it again this morning, now you've pointed it out, I kinda see the wrinkle caused by the layer of generic interface inside the concrete type. Thank you again for the speedy response.
