### ISSUE TITLE
MethodSymbol.Parameters missing Names for AttributeSyntax

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#48655]
**Version Used**: 
Microsoft.CodeAnalysis 3.8.0-4.final
**Steps to Reproduce**:
GetSymbolInfo for an C# Attribute 
```VB
Dim possibleMethodInfo As SymbolInfo = _mSemanticModel.GetSymbolInfo(CType(node.Parent, CSS.AttributeSyntax))
```
Get CandidateSymbols
```
Dim method As IMethodSymbol = CType(possibleMethodInfo.CandidateSymbols(0), IMethodSymbol)
```

**Expected Behavior**:
Parameters gets Name and Type as it is shown in Underlying
![image](https://user-images.githubusercontent.com/12789369/96199781-208c7700-0f0d-11eb-8eca-a9e449cfe587.png)

**Actual Behavior**:
Only Type is available from Parameters
![image](https://user-images.githubusercontent.com/12789369/96199662-e28f5300-0f0c-11eb-96a9-cd0c4a7d04f8.png)

Internally Roslyn uses (symbol as Symbols.PublicModel.MethodSymbol)?.UnderlyingMethodSymbol to get a symbol that can be used to get symbol.Name. but contrary to the name PublicModel.MethodSymbol is not public.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  can you please create a test project that demonstrates this?  If necessary, plz upload to github and provide a link to that here.
