### ISSUE TITLE
VS has stopped reporting background compiler diagnostics

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48667]
**Version Used**: 
Version 16.9.0 Preview 1.0 [30615.81.main]

Visual Studio has stopped reporting background compiler diagnostics, including syntax and semantic errors. It continues to report analyzer violations, but no compiler warnings/errors. If I restart VS the problem persists for the same project. If I can create a new project, then I cannot reproduce this.

This breaks any code fixes that rely on this, including implement interface, resolve usings, etc.

**Steps to Reproduce**:

You can see below that Task and the invalid code should have an error reported.

![image](https://user-images.githubusercontent.com/1103906/96221870-03bc7600-0fd7-11eb-96b9-510535a65a6d.png)

**Comment by davkean** [comment]
Deleting my .vs folder resolved the issue, attached is the bad .vs folder:
[vs.zip](https://github.com/dotnet/roslyn/files/5389691/vs.zip)

**Comment by Youssef1313** [comment]
I'm not sure, but looks like the attached bad `.vs` folder doesn't contain `DesignTimeBuild` folder under `\ProjectSystem\v16`. This *may* be the problem.

**Comment by mavasani** [comment]
@davkean Can you also upload the the repro project corresponding to the bad .vs folder that you provided? That would make investigation easier. Note that I wasn't able to repro this on any new or existing solutions, even after upgrading to today's internal dogfood build `Version 16.9.0 Preview 1.0 [30616.7.main]`

**Comment by davkean** [comment]
@mavasani This is just project-system.

I removed the DesignTimeBuild folder due to size and it will unrelated to the issue, this solely contains a cache of design-time build data.

**Comment by davkean** [comment]
I ran into this again, needed to delete .vs folder to progress.

**Comment by jinujoseph** [comment]
cc @shyamnamboodiripad to see the attached vs.zip file

**Comment by davkean** [comment]
I'm experiencing two symptoms:

1) It stops reporting diagnostics, and I need to delete the .vs folder for them to come back.
2) It stops reporting diagnostics, and if I switch documents, this causes them to come back.

I'm not so sure this has to do with the Test infrastructure, as I hit it multiple times in a row with zero logs in ServiceHub directory complaining about Test analyzer.

**Comment by davkean** [comment]
More information:

- I've confirmed that Live analyzer diagnostics are still being reported

**Comment by davkean** [comment]
I reported a trace here: https://developercommunity.visualstudio.com/content/problem/1226498/compiler-diagnostics-are-not-being-reported.html.

**Comment by davkean** [comment]
https://twitter.com/thenickrandolph/status/1323055771936911360 looks similar.

**Comment by CyrusNajmabadi** [comment]
I am hitting something that looks like this in CodeSpaces.  Within a few seconds to a minute of just basic typing in a file consisting of nothing but:

```c#
class C
{
   static void Main(string[] args)
   {
   }
}
```

then diagnostics just completely gets wedged.

**Comment by davkean** [comment]
I've hit this again and this time recorded the situation with full service hub logging turned on: https://developercommunity2.visualstudio.com/t/Compiler-diagnostics-are-not-being-repor/1256420.

**Comment by tmat** [comment]
@davkean We have fixed several issues in OOP infra. Are you still seeing this?

**Comment by davkean** [comment]
No, but I haven't written code in ~2 months.

**Comment by CyrusNajmabadi** [comment]
Closing out as these components were entirely rewritten/replaced for lsp.
