### ISSUE TITLE
Infinite suggested action never ends.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48679]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1223055/infinite-suggested-action-never-ends.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:Visual Studio Community 16.7.6]
Hello,

This happens on visual studio preview 16.8.4 preview 4. I'm using Windows 10 professional 64 bits.
After creating a unit testing and attempting to use the "suggested action" to add a reference to one of my projects, the action never finishes.
This is a .NET Core console application for  .NET 5.0 RC1

---
#### Feedback Bot on 10/15/2020, 08:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by thomaslevesque** [comment]
I'm seeing the same problem in 16.8.0 Preview 6.0. Is this fixed in the next release?

**Comment by thomaslevesque** [comment]
> ![image](https://user-images.githubusercontent.com/1864281/99239283-21117980-27fb-11eb-81cf-270d912aa88c.png)

Was this supposed to fix the problem? It's still not working in 16.8.1 RTM...

**Comment by CyrusNajmabadi** [comment]
@thomaslevesque that pr has not been merged: https://github.com/dotnet/roslyn/pull/48680

**Comment by thomaslevesque** [comment]
@CyrusNajmabadi ah, I see, thanks.

Any ETA? It's a pretty important feature that's completely broken in 16.8...

**Comment by CyrusNajmabadi** [comment]
No ETA as of yet.  We have to figure out how to fix it first.

**Comment by kovacpetar** [comment]
This issue should be reopened as it still affects VS version 16.8.3
As a reference please see comments [here](https://developercommunity2.visualstudio.com/t/Infinite-suggested-action-never-ends/1223055?viewtype=all)

**Comment by CyrusNajmabadi** [comment]
> This issue should be reopened as it still affects VS version 16.8.3

@kovacpetar the issue has been fixed in the 16.9p2 milestone.

**Comment by asjensse** [comment]
Should it not be kept open until it's in an actual version available to us users?

**Comment by sharwell** [comment]
@asjensse Unfortunately, GitHub does not support tracking issue states with that granularity. The [original feedback ticket](https://developercommunity.visualstudio.com/content/problem/1223055/infinite-suggested-action-never-ends.html) is kept in a "resolved but still open" state until the fix appears in a non-preview release.

**Comment by qtbui159** [comment]
When will 16.9 be released? This bug is really annoying 😓

**Comment by dnxit** [comment]
at least till the end of Covid we'll have to face this issue as well 🤣
