### ISSUE TITLE
Format selection at top of VB file throws InvalidOperationException

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#48676]
**Version Used**: 4ed928935

**Steps to Reproduce**:

Run the **Format Selection** command with the following selection:

```vb

[|
|]

' Top of file
```

**Expected Behavior**:

No changes

**Actual Behavior**:

Gold bar with InvalidOperationException due to accessing `default(int?).Value` here:

https://github.com/dotnet/roslyn/blob/77efd6e1feab8b69bca84b6eeeb762615140b29b/src/EditorFeatures/Core/Shared/Utilities/CommonFormattingHelpers.cs#L33

**Comment by sharwell** [comment]
@CyrusNajmabadi @jasonmalinowski do you happen to know where tests for this feature are?

**Comment by CyrusNajmabadi** [comment]
No clue.  @heejaechang might.  Right now the formatting tests are scattered around a few areas, and i'm not sure which particular feature-layer they operate at.

The only test i can find in all of roslyn that even uses FormatSelectionCommandArgs is TestBugfix_608438.  So we may literally only have one test here.
