### ISSUE TITLE
Incorrect IL for optimized struct assignment

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/roslyn#48688]
**Version Used**: 

Microsoft (R) Visual C# Compiler version 3.8.0-2.20410.4 (2c664a69)

**Steps to Reproduce**:

Compile [this test](https://github.com/dotnet/runtime/blob/master/src/tests/JIT/RyuJIT/rCopyProp1.cs) with and without optimization.

Behavior of this program will vary depending on whether IL is optimized or not. Key point is the change of of `s = S(v)` into `S.ctor(&s, v)` -- this is an invalid optimization.

**Expected Behavior**:

Same behavior whether IL is optimized or not.

**Actual Behavior**:

Test passes if IL not optimized, fails if optimized.

**Comment by jaredpar** [comment]
@cston fyi

**Comment by cston** [comment]
It looks like the underlying issue has existed for sometime: the test fails when compiled with and without optimizations with C# 3.8.0 and with C# 2.10.

**Comment by cston** [comment]
From [ECMA-335](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/), it seems the optimization is allowed (emphasis added):

> **I.12.1.6.2.1 Initializing instances of value types**
> 
> There are three options for initializing the home of a value type instance. You can zero it by loading the address of the home (see Table I.8: Address and Type of Home Locations) and using the initobj instruction (for local variables this is also accomplished by setting the localsinit bit in the method’s header). **You can call a user-defined constructor by loading the address of the home (see Table I.8: Address and Type of Home Locations) and then calling the constructor directly.** Or you can copy an existing instance into the home, as described in §I.12.1.6.2.2. 

The C# compiler only calls the constructor directly when the value type target is on the stack and the constructor arguments are not passed by reference (see [EmitExpression.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L2106-L2120)). In `unsafe` code, the effect of this optimization may be observable though, as in this bug repro.

@AndyAyersMS, is the IL generated by the C# compiler incorrect, or do you feel the compiler should avoid this optimization in these cases?

**Comment by AndyAyersMS** [comment]
It seems like a grey area. If the highlighted bit of I.12.1.6.2.1 applies broadly then the seemingly the C# compiler could always use the direct invocation route regardless of how args are passed; but that's not what happens. So clearly some other considerations apply. #15715 refers to a C# language spec stating there are more specific C# level requirements here.

> You can call ....

I think the "can" here is not prescriptive. It is just enumerating the ways a value type can be initialized, not telling you how to get a sensible result from initialization.

All that being said, given that the C# compiler's behavior here hasn't changed in quite a while, and this doesn't seem to have tripped anyone up, I'd say leaving things as is is also reasonable.
