### ISSUE TITLE
[VB.NET] Debug Mode doesn't support With blocks

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#48681]
In this code sample:
```VB.NET
    Class Foo
        Public Value As Integer
    End Class

    Sub main()
        Dim x As New Foo
        With x
            .Value = 1  ' Add a breakpoint here
        End With
    End Sub
```

If you run the code and break at the `sub main`, you will get no tip when hovering over `Value`, and if you try to show its value in the quick watch window, or add it to the Watch Window, you will see this message:
```
error BC30157: Leading '.' or '!' can only appear inside a 'With' statement.
```

In my app, I deleted the With Statement, and used normal code, so I can debug it. This is one of the reasons that prevented me from using With in VB.NET. We had to use it in VB6 though, since there was no chain calls. In VB.NET, the lack of debugeer support makes it useless.

**Comment by CyrusNajmabadi** [comment]
@VBAndCs would you be interested in contributing a fix here?

**Comment by Youssef1313** [comment]
Adding `.Value` in the watch window **should** produce an error. To me, that seems like the correct behavior.
However, hovering over `Value` should work.

**Comment by VBAndCs** [comment]
@Youssef1313  
I disagree. This command can add the `[object].Value` to the watch window, by getting the `[object]` from With Statement.

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
If I have time, I will inform you.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change thie behavior.
