### ISSUE TITLE
Source.Roslyn.IO is down? 

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#4869]
I see this error on home page and no searches seem to work.

~~~
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
~~~

**Comment by RichiCoder1** [comment]
Specifically the website it's self is up, but `solutionexplorer.html` is 404-ing. Looks like what ever is generating the documentation from the code is failing.

**Comment by dpoeschl** [comment]
Working again now.
