### ISSUE TITLE
MSBuild task should surface informational diagnostics

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#4871]
This arose out of the discussion of #3707.

If an analyzer reports a diagnostic with a severity of "Info" it will show up in the output, but the MSBuild task will not pick it up; it only looks for errors and warnings. The task should be updated to pick up and report info diagnostics as well.

@srivatsn @mavasani FYI

**Comment by lgolding** [comment]
@jaredpar @agocke @mavasani 

Per #3707, we agree that this should be fixed. The fix would be in the MSBuild tasks that scan the compiler output and decide what to emit into the MSBuild output. Assigning to Area-Compilers.

**Comment by agocke** [comment]
@lgolding Despite the fact that the build task is part of the compiler assemblies, I believe this is still a diagnostics story, which falls under the Analyzers area.

**Comment by srivatsn** [comment]
It's less important now since AD0001 is a warning. Showing info by default in MSBuild might be too noisy otherwise.
