### ISSUE TITLE
Compiler message for CS0077 is wrong (German)

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#48724]
**Version Used**: 
Latest master

**Steps to Reproduce**:
```CS
var x = 1 as byte;
```
**Expected Behavior**:
The German error message should read:
`CS0077: Der as-Operator muss mit einem Referenztyp oder einem Nullable-Typ verwendet werden ("byte" ist ein Non-Nullable-Werttyp).`
**Actual Behavior**:
`CS0077: Der as-Operator muss mit einem Referenztyp oder einem Non-Nullable-Typ verwendet werden ("byte" ist ein Non-Nullable-Werttyp).`

**More info**

There is a misleading "Non-Nullable-Typ" in the error message. It should be "Nullable-Typ". Given the [documentation for CS0077](https://docs.microsoft.com/de-DE/dotnet/csharp/misc/cs0077) (which is correct) it should even read:
`Der as-Operator muss mit einem Referenztyp oder einem Typ, der NULL-Werte zulässt, verwendet werden. ("byte" ist ein Werttyp, der keine NULL-Werte zulässt.)`

The English message reads:
`The as operator must be used with a reference type or nullable type ('int' is a non-nullable value type).`

**References**
English doc:
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0077

German doc is correct:
https://docs.microsoft.com/de-DE/dotnet/csharp/misc/cs0077

**Comment by CyrusNajmabadi** [comment]
@tmeschter Can you take this?  can external people (or MS devs) just make a safe loc change like this?  Or does this need to go to the loc team for them to update things on their end?

Thanks!

**Comment by tmeschter** [comment]
Generally we loop in the Loc team so they can update their master copy of the translation; if we just update the .xlf on our side we risk the fix being reverted in the future.

Looping in @wli3 as he is now the Globalization tenet owner for Roslyn.

**Comment by wli3** [comment]
@CyrusNajmabadi I cannot find the xlf file of the message, could you point me to it?

@cristianosuzuki77 could you correct the translation with the loc team

**Comment by cristianosuzuki77** [comment]
Feedback added 325647
File is src\Compilers\CSharp\Portable\xlf\CSharpResources.de.xlf

**Comment by wli3** [comment]
@cristianosuzuki77 so it will be corrected the next loc pass? if so we can close this issue now

**Comment by cristianosuzuki77** [comment]
yes, it will be added in the next loc pass.

**Comment by Youssef1313** [comment]
@MaStr11 Looks like this is now fixed?

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/CSharp/Portable/xlf/CSharpResources.de.xlf#L3329-L3333

**Comment by MaStr11** [comment]
@Youssef1313 Confirmed. The error message is fixed. Thanks.
