### ISSUE TITLE
Cannot Create New Code Fix Project

### ISSUE THREAD

**Issue by ajvnd** [dotnet/roslyn#48739]
**Visual Studio 2019 16.7.6**

**Steps to Reproduce**:

choose File > New > Project... to display the New Project dialog.
Under Visual C# > Extensibility, choose Analyzer with code fix (.NET Standard).

**Expected Behavior**:
create new code fix project

**Actual Behavior**:
error dialog : the path is not of a legal form code

**Comment by sharwell** [comment]
Duplicate of dotnet/roslyn-sdk#583
