### ISSUE TITLE
Error in displaying array of some type in class member xml description.

### ISSUE THREAD

**Issue by anreton** [dotnet/roslyn#48769]
**Version Used**: 
Visual Studio 2019 16.7.6

**Steps to Reproduce**:

1. Write example code
```csharp
/// <summary>
/// Computes the hash value for the specified <see cref="Byte[]"/>.
/// </summary>
/// <param name="buffer">
/// The input to compute the hash code for.
/// </param>
/// <returns>
/// The computed hash code.
/// </returns>
protected abstract byte[] ComputeHash(byte[] buffer);
```
2. Check description of this method either on hover or in the ObjectBrowser.
3. We have an error `byte` instead of `byte[]`

**Expected Behavior**:
We have  `byte[]` in method description.

**Actual Behavior**:
We have an error `byte` instead of `byte[]` in method description.

**Comment by sharwell** [comment]
`byte[]` is not a type that can be referenced directly by a `cref` element, because it doesn't have a source definition anywhere. If you enable XML documentation output, you will see CS1584 reported:

> Warning CS1584 XML comment has syntactically incorrect cref attribute 'byte[]'
