### ISSUE TITLE
Build Validator: Output kind should not be hardcoded

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#48775]
[Link to conversation](https://github.com/dotnet/roslyn/pull/45593#discussion_r499891244)

Resolution should be that the output kind is read in as part of the assembly that is being build by build validator.

**Comment by ryzngard** [comment]
@jaredpar @RikkiGibson I have a few issues I filed on the initial implementation of BuildValidator. I'm not sure they apply anymore: 

This one, #48774, and #48773. 

Do we need to continue to track these? If not I'll go ahead and close them

**Comment by RikkiGibson** [comment]
Fixed by #52340

**Comment by RikkiGibson** [comment]
Thanks for bringing these issues to our attention @ryzngard :)
