### ISSUE TITLE
[C# 9.0] Record type definitions don't get syntax highlighting

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48786]
**Version Used**: 

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1103906/96539624-40de7c00-12e7-11eb-9557-1991166e91fe.png)

**Expected Behavior**:
SpecialWebFolder to be green and match delegates, types, enums, etc

**Actual Behavior**:
SpecialWebFolder is not green

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/46985.  PR is out to fix this right now :)
