### ISSUE TITLE
Defining Equals for a record gives null ref exception when used in derived record

### ISSUE THREAD

**Issue by essennell** [dotnet/roslyn#48791]
**Version Used**: 
5.0.100-rc.2.20479.15 command line

**Steps to Reproduce**:
public record Base(int val)  
{ 
        public virtual bool Equals(Base? other)
            => val == other.val;
}
public record Child(Base other) : Base(other) { }

var b = new Base(0);
var d = new Child(b);

b.Equals(d); 

**Expected Behavior**:
Should be false. Equals should not throw.

**Actual Behavior**:
Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.

Removing the virtual Equals method from Base causes the expected behaviour.

**Comment by Youssef1313** [comment]
I don't see why the expected behavior should be false?
I think it should be true, and that's what I'm getting:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4GJPoA2hEwhcABHJqeQLABQjAbhAhcBQLwWZwDuFAELQ4ACgAMASgDcLNhQAm3XgIoBhABYBLQorHBZjRgAEAjADpzATgMWAogEd0EQlDGKpRpgxMBmCgQ4AGMAewRlEShxbUwYClZCKUYAb0YKDIp/BO0EGBdCDlDQwqcC9yi4AH4KUJhNRGSGTJbuAD4E124eOoaEC0S5BgBfY18AoLCIjR09MUra+saKEGFRMV7llIpRnxowOCgABwhgynMLACUsGG0Di3VQsCPdRABlRGZtM6gUkwAmCgASSg9gAHvAEDRCEDMNoYClhsMgA==

**Comment by essennell** [comment]
Ok, looks like latest master build doesn't throw. I'm using a dotnet downloaded from MS public download. However, Base and Child should definitely have different EqualityContract since neither one overrides it. Should therefore compare "false", or have I misunderstood EqualityContract?

**Comment by Youssef1313** [comment]
@essennell You gave your own definition of Equals, which doesn't account for EqualityContract.

**Comment by Youssef1313** [comment]
I could reproduce the issue when I used `d.Equals(b)`, but haven't yet looked whether the exception is reasonable or not.

**Comment by essennell** [comment]
Equals should never throw.
I'll look more into EqualityContract and what else needs to be customized, but 1st impression is records don't really bring much to the table.

**Comment by Youssef1313** [comment]
I think the reason you're getting an exception is your own definition of Equals. You should check for null before accessing `val`.

Here is how it went:

```
    [System.Runtime.CompilerServices.NullableContext(2)]
    public sealed override bool Equals(Base other)
    {
        return Equals((object)other); // This was called first.
    }

    [System.Runtime.CompilerServices.NullableContext(2)]
    public override bool Equals(object obj)
    {
        return Equals(obj as Child); // Secondly, this was called. Note that obj isn't of type Child. Hence, null is passed.
    }

    [System.Runtime.CompilerServices.NullableContext(2)]
    public virtual bool Equals(Child other)
    {
        if (base.Equals(other)) // Null was passed to base.Equals(...), which is your own implementation that doesn't account for null.
        {
            return EqualityComparer<Base>.Default.Equals(<other>k__BackingField, other.<other>k__BackingField);
        }
        return false;
    }
```

I think you don't need to pay much attention to the above generated methods. Just fix the implementation to account for null.

If you still don't think this behavior is desired, you need to wait for an official reply from the compiler team.

**Comment by essennell** [comment]
Ah yes records are *references*! Thank you. I'll still check out the
contract side because I think comparing true is, er, false 😊

Thanks Youssef
Steve
