### ISSUE TITLE
Nullable state does not flow through else-if

### ISSUE THREAD

**Issue by BrunoZell** [dotnet/roslyn#48827]
**Version Used**: 
.NET SDK `5.0.100-rc.2.20479.15`
Microsoft Visual Studio Community 2019 Version 16.8.0 Preview 5.0

**Steps to Reproduce**:

Compile following code for framework `net5.0` with SDK `5.0.100-rc.2.20479.15`:

```csharp
namespace NullableBug
{
    public static class Program
    {
        public class AreaState
        {
            public int Phase { get; set; }
        }

        public static void Main()
        {
            var state = default(AreaState?);

            if (state is null)
            {

            }
            else if (state?.Phase == 1)
            {

            }
            else if (state.Phase == 2) // CS8682: Dereference of a possibly null reference on 'state'
            {

            }
        }
    }
}
```
**Expected Behavior**:

No nullable warning to occur.

**Actual Behavior**:

Program.cs(22,22): warning CS8602: Dereference of a possibly null reference.

When changing the middle `if`-condition to `state.Phase == 1` the code is compiled without any warnings.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue but the compiler is behaving as expected here. The use of the `?.` is an indication from the user that they expect that the value `state` can contain a `null` value here and as such we update the state to "maybe null". The previous state the value has no impact on this decision.
