### ISSUE TITLE
GeneratedMSBuildEditorConfig.editorconfig added to project root

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48826]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/GeneratedMSBuildEditorConfigeditorconfi/1216427)._

---
[severity:It's more difficult to complete my work] [regression]
https://github.com/dotnet/roslyn/pull/43617 introduced generation of editor files. Those should be written to `obj\debug\` (or whatever `IntermediateOutputPath` is pointing to. However for one of my projects it is generating the file in the project's root. 

Setting `IntermediateOutputPath` explicitly to ``obj\debug\`` generates the file in the specified folder.

I've added the following to my csproj:
```
    <Target Name="IOP" BeforeTargets="CoreCompile">
        <Message Text=" IOP: '$(IntermediateOutputPath)'" Importance="High" />
    </Target>
```

This prints the following:
```
1>   IOP: 'obj\x64\Debug\'
```

**Version Used**: Visual Studio 2019 (16.7.5)

**Steps to Reproduce**:
1. Build project.

**Expected Behavior**:
No file changes in folders beside ``bin\`` and ``obj\``.

**Actual Behavior**:
New file in project's root: `PROJECTNAME. GeneratedMSBuildEditorConfig.editorconfig`

---
#### Bouke Haarsma on 10/12/2020, 08:07 AM: 

<p>See also: https://github.com/dotnet/roslyn/issues/48430</p>

#### Feedback Bot on 10/12/2020, 07:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/21/2020, 03:41 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
@chsienki

**Comment by mavasani** [comment]
Ah, seems like @jasonmalinowski explicitly requested the feedback ticket in https://github.com/dotnet/roslyn/issues/48430#issuecomment-706287446. 

@jasonmalinowski @chsienki do we want to close this issue in favor of #48430?

**Comment by jasonmalinowski** [comment]
@mavasani Yes, and repoint the feedback ticket accordingly. :smile:

**Comment by jasonmalinowski** [comment]
TBH I'd also say the feedback ticket may need to be active -- right now there's an open question of whether this is going to require fixing in 16.8 or not; having a place people can upvote would be good.

**Comment by mavasani** [comment]
Alright, let me re-open the feedback ticket and assign it to @chsienki
