### ISSUE TITLE
SourceGenerators Long Path issue when building in VS

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/roslyn#48833]
**Version Used**: 16.8 Pre 5

**Steps to Reproduce**:

1. Create a generator with a long Assembly name, as well as a long fully qualified type.
2. Enable `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>`
3. Invoke `AddSource` with a moderately long hint name

**Expected Behavior**:

The build succeeds.

**Actual Behavior**:

The build fails, with path not found errors:
```
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.AppBarToggleButtonTemplateSettings_892f7fb8a70845bc5cfdefb26909807b.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.AppBarToggleButtonTemplateSettings_892f7fb8a70845bc5cfdefb26909807b.cs'.'
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBarTemplateSettings_fc658f50f11a93d78689575c9a0644da.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBarTemplateSettings_fc658f50f11a93d78689575c9a0644da.cs'.'
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.JumpListItemBackgroundConverter_81521af6864e463b90b98badc45aeba8.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.JumpListItemBackgroundConverter_81521af6864e463b90b98badc45aeba8.cs'.'
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.JumpListItemForegroundConverter_037b2e9cefb89e703e2ce466a65eb701.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.JumpListItemForegroundConverter_037b2e9cefb89e703e2ce466a65eb701.cs'.'
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.MenuFlyoutPresenterTemplateSettings_78f02c38e8764658e444668ca35732de.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Windows.UI.Xaml.Controls.Primitives.MenuFlyoutPresenterTemplateSettings_78f02c38e8764658e444668ca35732de.cs'.'
8>CSC : error CS0016: Could not write to output file 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Microsoft.UI.Xaml.Controls.Primitives.CornerRadiusToThicknessConverter_0eaacd22f27b2d8bf4217b4b102d3c21.cs' -- 'Could not find a part of the path 'C:\s\XXXXXXXX\uno\src\Uno.UI\obj\Debug\MonoAndroid10.0\generated\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.DependencyObject.DependencyObjectGenerator\Microsoft.UI.Xaml.Controls.Primitives.CornerRadiusToThicknessConverter_0eaacd22f27b2d8bf4217b4b102d3c21.cs'.'
```

For the record, the leading part of the file (e.g. `Microsoft.UI.Xaml.Controls.Primitives` can be removed on the generator's side), but the assembly name and qualified path name cannot.

Also if it can help, to alleviate this problem, in Uno.SourceGeneration, the generated file path format is `g\DependencyObjectGenerator\[hintname]_[hash].g.cs`. It does not address all problems, but minimal enough to be understandable.

## Workaround

Enabling [LongPath globally](https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/net-4-6-2-and-long-paths-on-windows-10#enabling-win32-long-path-support) fixes the issue.

Use the `<CompilerGeneratedFilesOutputPath>` msbuild property to output the generated files to a shorter path on disk.

**Comment by jaredpar** [comment]
When we were doing the design of the generated file names I at least was not considering issues around `MAX_PATH` here. At a glance I wonder if we'd be okay dropping the assembly qualification. Yeah that does present the chance we end up with a conflict between generators of the same type in different assemblies but that seems a bit out there. Or maybe we find a way to make this more configurable. 

Will discuss with @chsienki next week.

**Comment by canton7** [comment]
Can you incorporate all of that info into the hash that's being appended to the filename?

**Comment by chsienki** [comment]
Interesting. We originally dropped the fully qualified assembly name because we were seeing long path name issues (which can lead to collisions in a small number of cases: https://github.com/dotnet/roslyn/issues/47990). 

The original intent behind the design was a desire to make it obvious to the user which generator was specifically providing the files. It's obvious when you only have one or two generators, but can be difficult to track down when running many of them. 

A hash is an obvious way to solve the long path problem, but then makes it harder for the user to know where the file itself came from. This is especially true in the IDE itself, where hitting F12 and getting some randomly named `...{hash}.cs` isn't great. I think we're going to want to think through the design of this further before making any changes.

**Comment by canton7** [comment]
I see. I'm not sure I'd think to check the full path if I opened source generated file in VS. Can you add a "This file was generated by a source generator" comment to the top of SG'd files perhaps? You could include more info there, such as the name/version of the SG, the full hint used by the SG, etc. That doesn't help someone browsing the file system if course, but IMO might be a better IDE experience.

**Comment by jeromelaban** [comment]
@chsienki having worked like this for a while (with the hash and generator name), the only times I'm looking manually in the folder is when I'm looking for a file that I cannot reach from the UI (e.g. when a generated file's code is only invoked from another generated file). In which case, the generator Name (not full name) and file hint name is generally sufficient.

**Comment by jaredpar** [comment]
After some consideration I believe this behavior is by design. It's important to keep the assembly qualification here and shortening it makes it harder for the customer to understand where there files are. The recommendation to the customer in cases like this is to enable long paths or move the build into a shorter root directory path.

**Comment by Timovzl** [comment]
In case it helps anyone, here is how I'm using a stable hash code of the namespace to disambiguate type names. In the common case where a type is the first occurrence of its name, I'm omitting the hash code, since it's much prettier to have just the type name.

I've chosen FNV-1a as the fast, stable, low-collision hashing algorithm, based on [this post](https://softwareengineering.stackexchange.com/a/145633/213637).

The implementation shown here acts as a base class for concrete source generators, although a different setup would work just as well.

```cs
/// <summary>
/// <para>
/// Helps avoid issues with duplicate type names.
/// </para>
/// <para>
/// Stores stable string hash codes concatenated with separators: one for each namespace encountered for a { generator, type } pair.
/// </para>
/// </summary>
private static ConcurrentDictionary<string, string> NamespacesByGeneratorAndTypeName { get; } = new ConcurrentDictionary<string, string>();

protected static void AddSource(SourceProductionContext context, string sourceText, string typeName, string containingNamespace,
	[CallerFilePath] string? callerFilePath = null)
{
	var sourceName = $"{typeName}.g.cs";

	// Create a unique key per { generator, type } pair, to help us disambiguate types with the same name,
	// separately per source generator (with callerFilePath identifying the generator)
	var uniqueKey = callerFilePath is null
		? typeName
		: $"{Path.GetFileNameWithoutExtension(callerFilePath)}:{typeName}";

	// Since name collisions should be rare, we will use a simple concatenation of the hash codes
	var stableNamespaceHashCode = containingNamespace.GetStableStringHashCode32();
	var hashCodesForTypeName = NamespacesByGeneratorAndTypeName.AddOrUpdate(
		key: uniqueKey,
		addValue: stableNamespaceHashCode,
		updateValueFactory: (key, namespaceHashCodeConcatenation) =>
			namespaceHashCodeConcatenation.Contains(stableNamespaceHashCode)
				? namespaceHashCodeConcatenation
				: $"{namespaceHashCodeConcatenation}-{stableNamespaceHashCode}");

	// If the type was not the first to have this name, then it must include a hash code of its namespace
	// Note that directly including namespaces in file names would create hard-to-read names and risk oversized paths
	if (!hashCodesForTypeName.StartsWith(stableNamespaceHashCode))
		sourceName = $"{typeName}-{stableNamespaceHashCode}.g.cs";

	context.AddSource(sourceName, SourceText.From(sourceText, Encoding.UTF8));
}

public static string GetStableStringHashCode32(this string source)
{
	var hashCode = source.GetStableHashCode32();

	Span<byte> bytes = stackalloc byte[8];

	for (var i = 0; i < 4; i++)
		bytes[i] = (byte)(hashCode >> 8 * i);

	var chars = new char[13];
	ToBase32Chars8(bytes, chars.AsSpan());
	var result = new string(chars, 0, 7);

	return result;
}

public static string GetStableStringHashCode64(this string source)
{
	var hashCode = source.GetStableHashCode64();

	Span<byte> bytes = stackalloc byte[8];

	for (var i = 0; i < 8; i++)
		bytes[i] = (byte)(hashCode >> 8 * i);

	var chars = new char[13];
	ToBase32Chars8(bytes, chars.AsSpan());
	var result = new string(chars);

	return result;
}
```
