### ISSUE TITLE
Make it easy to edit refactoring option from the Editor,

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48843]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1211108/make-it-easy-to-edit-refactoring-option-from-the-e.html)._

---
<p>As a developer refactoring is everything, and time spent away from the editor searching for a config is wasted time. One way to optimize facactoring and time spent making cool stuff, is a better way to update refactoring/style to match the style you use in your team/project. An example is how properties are written, should they be internal, public or..... <br><br>Example:<br>By default if you have an instance of a type and define a new property by its usage and click &quot;CTRL + .&quot; you get the option to add as new property. You can also see a preview of the change. Here I noticed that the default for a property is &quot;SomeProp{ get; internal set; }&quot;. In this specific case I wanted to simply remove the &quot;internal&quot; and make it default public. <br><br>To change this I went to the Tools -&gt; options menu and started searching.... Already here I want away from the work I was doing and had a big context switch. <br><br>My suggestion is to make it easier and faster to change formatting like this. From the refactoring context menu, it should be possible to navigate directly to the formatting of a refactoring option and change it. Just as preview change, there should be a &quot;edit refactoring...&quot; shortcut right in the editor. <br><br>This would save a ton of time and just make vs an even greator editor.<br></p>

---
#### Feedback Bot on 10/9/2020, 00:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
