### ISSUE TITLE
A way to prevent "items from unimported namespaces" from suggesting extension methods with the "this" parameter of type "object" or extension methods  from unimported namespaces not defined in this solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48845]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/A-way-to-prevent-items-from-unimported-/1227168?preview=true)._

---
<p>I like the &quot;items from unimported namespaces&quot; suggestions. I like extension methods EXCEPT when the &quot;this&quot; parameter is of type &quot;object&quot;. I am using a NuGet package that has irrelevant extension methods with the parameter (this object obj) in namespaces that I never use, and now &quot;items from unimported namespaces&quot; suggests these extension methods for every object and I don't like that. <br><br>It would be nice to have a way to prevent &quot;items from unimported namespaces&quot; from suggesting extension methods with the &quot;this&quot; parameter of type &quot;object&quot; from other packages, while still suggesting extension methods defined in this solution with the &quot;this&quot; parameter of any other type, and without affecting the behaviour for items from namespaces that have already been imported.<br> <br>Some ideas for doing this:</p><ul><li>An option in Tools &gt; Options &gt; Text Editor &gt; C# &gt; Intellisense for &quot;show extension methods from unimported namespaces&quot; and a sub-option for &quot;show extension methods not defined in this solution from unimported namespaces&quot; </li></ul><ul><li>An option  in Tools &gt; Options &gt; Text Editor &gt; C# &gt; Intellisense for &quot;show extension methods from unimported namespaces&quot;  and a sub-option for &quot;show extension methods for type &quot;object&quot; from unimported namespaces&quot;</li></ul><ul><li>Something in .editorconfig containing namespaces to be excluded from &quot;items from unimported namespaces&quot; </li></ul><ul><li>Something in .editorconfig containing method signatures (allowing the &quot;this&quot; modifier)  to be excluded from &quot;items from unimported namespaces&quot; </li></ul><p>Or maybe some other way.</p>

---
#### Feedback Bot on 10/20/2020, 11:54 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing duet o lack of feedback.
