### ISSUE TITLE
C# document viewing using regions and smart comments.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48846]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1224057/c-document-viewing-using-regions-and-smart-comment.html)._

---
Hello,

(1)
I have many #regions to split *.cs document. 
What about to view the document using tabs where each tab is one region.
And of course switching to the normal view and back - toggle both views. 

(2)
It would be nice to have emphasized comments. 
If it was possible to change font name and/or font size just for comment only.
For source code it would not be good idea. But who knows. 

Best regards,

Aleš Grmela

---
#### Feedback Bot on 10/19/2020, 00:30 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @olegtk  for info

**Comment by olegtk** [comment]
Great idea! As this is not C# specific please suggest a feature via https://developercommunity.visualstudio.com. It's better to track votes and this is how VS in general tracks suggestions. Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing as external.
