### ISSUE TITLE
Configure background code analysis per severity.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48849]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1212395/configure-background-code-analysis-per-severity.html)._

---
<p>Building on top of https://github.com/dotnet/roslyn/issues/38429 it would be useful if this could be set per severity in some way. <br>Scenario is:<br></p><ul><li>Mixed codebase of legacy and new code (Isn't it always!)</li> <li>CI always runs full analysis.</li> <li>New code is set to TreatWarningsAsErrors.</li> <li>Both old and new have analysers applied so that we can see and fix violations as we go along.</li> <li>Majority of warnings in older code have been fixed, but there are 100s of suggestions.</li> <li>VS set to open documents only.</li> <li>During development we may close files that have been edited/refactored that now cause violations before we notice in the error log, full solution build then works in VS, but when pushed to CI it then fails, causing delays, context switching etc.</li></ul> <p>It would be really useful if the background analysis could be configured per severity, or up to a severity. This would then allow us to set it to only flag warnings and above during full analysis and everything else for open documents. <br><br>I understand that the current setting is probably targeted at performance of running a full analysis, so maybe this is something that deserves a separate filter setting e.g. &quot;Show [severity dropdown] and above for full solution&quot; or &quot;Only show [severity dropdown] and below for open documents&quot;</p><p>Thanks</p><p>Euan</p><ul><li></li></ul>

---
#### Feedback Bot on 10/9/2020, 01:52 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
@mavasani for info

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
