### ISSUE TITLE
collapse regions from bottom

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48842]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1216897/collapse-regions-from-bottom.html)._

---
Sometimes there are regions containing many code lines: it would be nice to have the "plus" symbol also on the #endregion part in order to collapse the region from the bottom

---
#### Feedback Bot on 10/12/2020, 11:21 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
@olegtk does platform own this ?

**Comment by olegtk** [comment]
@jinujoseph yes
