### ISSUE TITLE
Proposal: Improved type aliases 

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#4884]
Currently we can define type aliases as follow
`using Cache = System.Collections.Generic.Dictionary<string, string>;`
but it does not support generic types and needs to be written with full namespaces
`using Cache<T> = Dictionary<string, T>;`
and also it is only in the file scope.

In the context of DDD, it would be a useful feature to have generic and universal type aliases so we can write methods and extension methods for specific yet simple types like
`using EmailAddress = string;`

**Comment by HaloFour** [comment]
Duplicate combining #58, #104, #116, #2044 and #3993.

**Comment by gafter** [comment]
Looks a great deal like #3993.
