### ISSUE TITLE
Auto complete the parenthesis when trying to wrap type

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#48852]
In this example, When I enter '('
![image](https://user-images.githubusercontent.com/24360909/96915852-9d62a800-145b-11eb-9f93-f1be926e2584.png)
It would be great if VS could put the ')' automatically after '1'.

This is useful when I am removing the async modifier for a method, because it is needed to change the return value from `return 1;` to `return Task.FromResult(1);`

**Comment by CyrusNajmabadi** [comment]
Would need a little more design into how this works for more complex scenarios.  But overall, i'm not opposed to this.

**Comment by jinujoseph** [comment]
related to https://github.com/dotnet/roslyn/issues/12363

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we want to do this we should create a design and give it a real milestone.
