### ISSUE TITLE
Reset settings Visual Studio 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48863]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Reset-settings-Visual-Studio/602468)._

---
I found issue https://github.com/dotnet/roslyn/issues/36104 but I realized that it's not exactly what my problem is. The problem for me is that I modified some settings in Visual Studio about my C# code style preferences. These changes are linked to my account so even reinstal of Visual Studio is not way of resetting them. I want to reset all of them to default state (for example change my preference of using `var` instead of `int` with error severity back to default). When I reset all settings, these are unchanged even after reload of Visual Studio. There is no way of resetting all code style preferences to default. Please support that option.

---
#### Feedback Bot on 6/12/2019, 00:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/13/2019, 03:24 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 12/31/2019, 09:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/16/2020, 05:46 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from anywhere else.  perhaps a VS options corruption issue.
