### ISSUE TITLE
Ctrl+Q search does not return items on first search, early in session

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#48860]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 main
Version 16.9.0 Preview 2.0 [30621.279.main]

**Steps to Reproduce**:

1. Open an existing C# console app in classic VS session
2. Immediately focus ctrl+Q and search 'main'
3. Wait

**Expected Behavior**:
Should find 'Main()' symbol return.

**Actual Behavior**:
Main() is not found, unless you wait a few seconds, and change your query again. This does not repro in C++ and appears to be some sort of race with solution load where the Roslyn OOP returns no results.

Ported from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1236631

**Comment by gundermanc** [comment]
@dibarbet FYI

**Comment by CyrusNajmabadi** [comment]
While VS is loading, we are set to return immediately without any results.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/blob/e2e303acb1fab9c8c4f811035091d436bd36a67b/src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemProvider.Searcher.cs#L96-L102

**Comment by gundermanc** [comment]
>While VS is loading, we are set to return immediately without any results.

This seems sub-optimal:

- User performed an explicit search action, seeing 'no results found' is misleading.
- This causes intermittent failures in VS Search End to End tests.

Is this related to #48609? Both seem to have regressed around the same time.

**Comment by CyrusNajmabadi** [comment]
> User performed an explicit search action, seeing 'no results found' is misleading.

I think the concern was that showing partial results was more confusing. And if we do this search, we greatly slowdown startup as we have to sync everything over to oop and we cause a ton of cpu and memory which churns the solution as were trying to load

**Comment by dibarbet** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1273256 to track support for an incomplete property

**Comment by CyrusNajmabadi** [comment]
This is superseded by aiosp which does allow us to tell you the search results are incomplete.
