### ISSUE TITLE
Inserting using statement using Ctrl+.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48864]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Inserting-using-statement-using-Ctrl/820597)._

---
When you have a list of using statements inside the namespace declaration documented with a comment and you insert a new using statement using the "Ctrl+." feature, if the new statement is inserted at the top of the existing using statements, it will be inserted before the comment.

Using the following example:

namespace Fred.Bloggs
    {
        // Using statements
        using Newtonsoft.Json;

Inserting "using System;" results in:

namespace Fred.Bloggs
    {
        using System;
        // Using statements.
        using Newtonsoft.Json;

If you continue inserting using statements using the same mechanism without manually fixing the problem, all using statements that get inserted before (in this case) the "using Newtonsoft.Json;" statement, will also be inserted before the comment.

Inserting "using System.Diagnostics;" results in:

namespace Fred.Bloggs
    {
        using System;
        using System.Diagnostics;
        // Using statements.
        using Newtonsoft.Json;

I gave it a very quick check and the same problem does not seem to occur if the using statements are outside the namespace declaration.

This is a really minor, but, for me, annoying little bug.

---
#### Feedback Bot on 11/14/2019, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/15/2019, 02:44 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 3/31/2020, 05:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 4/23/2020, 09:24 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 I'm guessing #9218 is what makes this behave differently inside and outside namespaces.

**Comment by CyrusNajmabadi** [comment]
This is by design based on our general thoughts on comments and what they belong to.  In this case there is a fundamental ambiguity in what this `// comment` means.  i.e. "does it belong to the using-block, or this single-using".  We generally do not think of standalone comments as applying a block of things.  However, in very explicit and specific cases we have made that decision for patterns that are vastly adopted in the ecosystem (like the banner of a file).

So i would say this is just 'by design'.  To put some clarity on this, imagine the user had:

```c#
namespace X
{
    // We need newtonsoft for blah blah
    using Newtonsoft.Json;
}
```

If we now add `using System;` it would be bad to convert hte above to:

```c#
namespace X
{
    // We need newtonsoft for blah blah
    using System;
    using Newtonsoft.Json;
}
```

Instead, we should keep:

```c#
namespace X
{
    using System;
    // We need newtonsoft for blah blah
    using Newtonsoft.Json;
}
```

As either approach might be correct on a per case basis, our default seems sensible and consistent here.
