### ISSUE TITLE
Bad quick action suggestion for method with annotations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48878]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Bad-quick-action-suggestion-for-method-w/1226493?preview=true)._

---
[severity:Other]
Visual Studio suggests that a Method can be turned into a Property but ignores the fact that properties don't support annotations, making the convertion a breaking change. Example in ASP.NET Core 3.1:

[HttpGet("[action]")]
    public IActionResult Test()
    {
        return Ok();
    }

Is suggested to be turned into:

[HttpGet("[action]")]
    public IActionResult Test => Ok();

Which breaks the expected functionality and won't even compile as, as mentioned, properties don't support annotations.

---
#### Feedback Bot on 10/20/2020, 01:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We don't suggest this.  We allow this as a quic refactoring *if* this is what you want to do.  Our features are not meant to only allow a 100% safe transformation.  They're there so you can quickly get from A-Z, traveling through A, B, C, D, ... along the way efficiently.  In this case, not having the feature available would be very confusing to users who would expect this to always be available for cases like this.
