### ISSUE TITLE
Completion tests fail after updating Editor to 16.8.181

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#48870]
See test results https://dev.azure.com/dnceng/public/_build/results?buildId=863202&view=ms.vss-test-web.build-test-results-tab&runId=27649786&resultId=166437&paneView=debug for https://github.com/dotnet/roslyn/pull/48866.

Blocking move of EditorFeatures.Cocoa to Roslyn

**Comment by sharwell** [comment]
Can we not downgrade the EditorFeatures.Cocoa reference, and allow consuming parties to use something newer?

**Comment by tmat** [comment]
EditorFeatures.Cocoa depends on Microsoft.VisualStudio.Text.UI.Cocoa and the lowest available version of that package is 16.8.181.

**Comment by genlu** [comment]
Seems the common theme of failed tests involves moving cursor before initial trigger char. I tried to debug and it seems this is handled by editor. Chatting with @AmadeusW offline to confirm

**Comment by genlu** [comment]
Fix in VS is here, should be available soon
https://devdiv.visualstudio.com/DevDiv/_git/d9dc88ef-476f-4add-967b-f7ddd47f4b71/pullrequest/285872
