### ISSUE TITLE
Method parameter incorrectly shown as unused

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48879]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Method-parameter-incorrectly-shown-as-un/1230468?preview=true)._

---
[severity:It bothers me. A fix would be nice]
The parameter 'ViewSchedule element' is grayed out and tooltip indicates that it can be removed.  This is incorrect, because if it is removed, then the 3 references in the method will show as 'does not exist in the current context'.  Tooltip indicates IDE0060.

---
#### Feedback Bot on 10/22/2020, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is the user case:

![image](https://user-images.githubusercontent.com/4564579/97033754-aebdba00-1518-11eb-9075-50799694a46b.png)

@mavasani Seems to be an issue with `nameof`.  I'm guessing the IOp tree doesn't represent this in a way that is amenable to the unused variable analysis?

**Comment by Youssef1313** [comment]
While the parameter does seem to be used, it's effectively unused/unneeded. You can directly use `nameof(ViewSchedule.BodyTextTypeId)`, etc.

**Comment by mavasani** [comment]
Yes, this is by design. The suggestion message also clarifies the same thing which @Youssef1313 mentioned above:

![image](https://user-images.githubusercontent.com/10605811/103920819-95afb880-50c6-11eb-8f6c-1d9d6a756bd1.png)
