### ISSUE TITLE
"Use auto property" Quick Action (when applied to whole document) does not refactor the last property when there is more than one being refactored

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48890]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Use-auto-property-Quick-Action-when-app/927411)._

---
Create a public class. Add several public fields. Use Ctrl+R, Ctrl+E on each of the fields to encapsulate them using properties. Then Perform the "Use auto property" Quick Action on one of the fields and apply it to the whole document -- it will apply it to all your encapsulated fields EXCEPT the last one.

---
#### Feedback Bot on 2/23/2020, 09:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/27/2020, 02:54 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 4/3/2020, 01:43 AM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Christian Hornung on 9/7/2020, 03:37 AM: 

I have the same issue in version 16.7.2. And it is not always the last property which is not fixed. It seems to have something to do with the data type of the properties and sometimes it is more than one property that is not fixed.<br><br>E.g. I can reproduce it with the following C# code in a new C# console app project (.NET Framework 4.8), where the quick action does not fix both the &quot;Quux&quot; and &quot;Bug&quot; properties:<br><br>```<br>		private readonly int foo;<br>		private readonly int bar;<br>		private readonly int baz;<br>		private readonly int quux;<br>		private readonly long asdf;<br>		private readonly object bug;<br><br>		public int Foo =&gt; this.foo;<br>		public int Bar =&gt; this.bar;<br>		public int Baz =&gt; this.baz;<br>		public int Quux =&gt; this.quux;<br>		public long Asdf =&gt; this.asdf;<br>		public object Bug =&gt; this.bug;<br>```<br><br>I am also attatching a recording of this.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
