### ISSUE TITLE
CodeFix for CS0621 adds wrong modifier

### ISSUE THREAD

**Issue by b-straub** [dotnet/roslyn#48899]
**Version Used**: 

Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 5.0

C# Tools   3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

**Steps to Reproduce**:

1. 

Add a simple class

`
abstract class TestClass
{
    abstract string Test { get; }
}
`

2. 

Request code fixes
3. 

Execute CodeFix "Add accessibility modifiers"

**Expected Behavior**:

internal or public modifier will be added

**Actual Behavior**:

private modifier will be added, thus the error persists

**Comment by huoyaoyuan** [comment]
The codefix is **for IDE0040, not CS0621**. Code fixes for code style do run under error, and preserve the error as-is.

@jinujoseph Could you re-triage this as by-design, or a feature request? Resolving CS0621 should be introduced as a new code fix.

**Comment by CyrusNajmabadi** [comment]
I think we could detect this and make it so that we do as more sensible job here
