### ISSUE TITLE
Exception/completion awareness with using/IDisposable

### ISSUE THREAD

**Issue by ygoe** [dotnet/roslyn#4890]
I am proposing a new feature for the C# language.

Today, the `using` statement can be used with an instance that implements `IDisposable` to free resources at the end of the scope, even if an exception was thrown. The following code:

```
using (var disposable = new Disposable())
{
    // ...
}
```

Translates to something like this:

```
var disposable = new Disposable();
try
{
    // ...
}
finally
{
    disposable.Dispose();
}
```

This is fine for dumb resources that only need to be freed after use. But smarter resources also need to know how the scope they were used in was left. Was there an exception thrown? Was the scope left prematurely otherwise? Or did it run to completion just normal?

One example are database transactions. Take the `TransactionScope` class for example: It requires the `Complete` method called if all went well. If the scope did not run to the end, the transaction is rolled back automatically. We need to write that extra `Complete` line today, but apart from that it's still fine. The problem gets much worse with nested transaction scopes. If every scope either runs to the end or throws an exception, all parent scopes will likely cancel as well. But if a developer doesn't care and just `return`s without an exception, the rest of the parent scope will happily continue to run. But since the transaction has already ended, all changes are now permanent (this is unexpected), and the problem can only be detected in the parent scope's `Dispose` (when the known transaction is anything but active anymore), when it's too late.

The inner scope should be able to determine whether an exception was thrown, and if not, be able to throw one itself to also stop the parent scopes within a `try` block somewhere.

Another example is logging. I'm using a logging framework that supports retained logging. Every potentially interesting trace line can be put in a buffer. If everything goes well, the buffer can be cleared. But if an exception occurs later (or generally anything non-retained is logged), I still have the trace buffer of what has happened the moment before. Obviously, this buffer must not be cleared in a `Dispose` method _inside_ a `try` block, or the buffer is gone before the exception logging could use it.

When I connect that retained logging with something like Entity Framework's context to log certain areas of it in my code, I need the `IDisposable` pattern as well to attach and detach the log method for that scope only.

Here's a proposed language feature: Extend the `using` statement to recognise another interface besides `IDisposable`, for now called `ISmartDisposable`.

```
using (var context = new MyContext())
using (var logScope = new LogScope(context))
{
    // ...
}
```

Translates to:

```
using (var context = new MyContext())   // as usual
{
    var logScope = new LogScope(context);
    try
    {
        // ...
        logScope.Complete();   // TransactionScope compatibility :)
    }
    catch (Exception ex)
    {
        logScope.Error(ex);
        throw;
    }
    finally
    {
        logScope.Dispose();   // IDisposable compatibility :)
    }
}
```

The `ISmartDisposable` interface extends `IDisposable` by two more methods.
- `Complete` is called when the body of the `using` block has run to completion. This could save us from the extra explicit line we need for any kind of transaction classes today.
- `Error(Exception)` is called when an exception was thrown in the body of the `using` block. The exception is rethrown after the method was called. The `Error` method can instead decide to throw a different exception, possibly keeping the original exception as `InnerException`. Logging could be done here as well.
- `Dispose` is still called in the `finally` block as usual. The disposable object may remember whether `Complete` or `Error` was called before that and decide what to do. If neither of them was called, it might throw a new exception to make the parent scope more aware of a problem that was not raised properly in the nested scope.

This new feature requires 1) the interface itself in the BCL, and 2) compiler support to generate the above code.

Here is an example implementation of that interface for my EF logging. The static `FL` class is from the used logging framework [FieldLog](http://unclassified.software/source/fieldlog).

```
class EntityErrorLogger : ISmartDisposable
{
    private DbContext context;
    private bool isCompleted;

    public EntityErrorLogger(DbContext context)
    {
        this.context = context;
        // Start logging to the buffer now
        context.Database.Log = MyLog;
    }

    public void Complete()
    {
        // Clear the log buffer, we don't need it anymore
        FL.ClearRetained();
    }

    public void Error(Exception ex)
    {
        // We could log the exception here or leave it to the parent try block.
        // Any non-retained log method first writes the retained buffer to the log.
        // In no case the ClearRetained method must be called now.
        FL.Error(ex);
        // Nothing else to do now
    }

    public void Dispose()
    {
        // Be sure to stop logging at the end of the scope
        context.Database.Log = null;
    }

    private void MyLog(string message)
    {
        // Not shown: a bit of filtering
        // Remember that message but don't write it to the log immediately.
        // We'll only write it when an error occured.
        FL.LogRetained(message);
    }
}
```

And here's an example of a reliable `DbTransactionScope` class that can be nested over multiple public methods, each requiring a transaction, but that might also call each other:

```
class DbTransactionScope : ISmartDisposable
{
    private DbTransaction transaction;
    private bool isPrimary;
    private bool isExceptionThrown;
    private bool isDisposed;

    public DbTransactionScope(DbConnection conn)
    {
        if (conn.CurrentTransaction == null)
        {
            // Topmost scope
            transaction = conn.BeginTransaction();
            isPrimary = true;
        }
        else
        {
            // Nested scope
            transaction = conn.CurrentTransaction;
        }
    }

    public void Complete()
    {
        if (isPrimary)
        {
            // Do actual commit in the top level only
            transaction.Commit();
        }
        // No other actions required later
        isDisposed = true;
    }

    public void Error(Exception ex)
    {
        // Exception noticed, don't throw one later
        isExceptionThrown = true;
    }

    public void Dispose()
    {
        // Only do something if still necessary
        if (!isDisposed)
        {
            // Always rollback the transaction immediately if indicated,
            // don't wait for parent scope's Dispose
            transaction.Rollback();
            isDisposed = true;
            if (!isExceptionThrown)
            {
                // Make the parent scope aware of the problem
                throw new SomeException("The transaction has aborted.");
            }
        }
    }
}
```

Both of these examples come from a current project I'm working on. While I could implement the transaction scope, it doesn't have that extra reliability to throw a new exception yet. I don't think I can write the logging scope class at all with C# 5/6 as it would be too complicated to use.

This new language feature is meant to reduce often repeated code and increase reliability with a once-validated class that has a smarter cleanup behaviour. It increases the expressiveness of the language, making developers more productive. I'm aware that this also increases the language's complexity, but isn't that the case with every new feature, especially those that take away work from the developer?

**Comment by Steffen-M** [comment]
We had a similar requirement and solved it, translated to your example, like that:

    static class LogUtils
    {
        public static void Logged(MyContext context, Action<MyContext> action)
        {
            var logScope = new LogScope(context);
            try
            {
                action(context);
                logScope.Complete();
            }
            catch (Exception ex)
            {
                logScope.Error(ex);
                throw;
            }
            finally
            {
                logScope.Dispose();
            }
        }
    }

    static class MyAapp
    {
        static void Main()
        {
            using (var context = new MyContext())   // as usual
            {
                LogUtils.Logged(context, c =>
                {
                    // ...
                });
            }
        }
    }

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by ygoe** [comment]
@gafter Does that mean all issues here are closed and everybody should create theirs again in the new location?

**Comment by gafter** [comment]
No, you should only create a new issue if you still think there is something that the language design group should do.

See also #18002 for a general discussion of closing and/or moving language issues out of this repo.

**Comment by ygoe** [comment]
Thanks for the pointer, it would have been useful in your previous comment already. I haven't found such information in the new repo's docs.
