### ISSUE TITLE
Show inline parameter name doesn't show when literals are followed by null-forgiving operator

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48910]
**Version Used**: 

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1103906/97131249-be970180-1797-11eb-9847-d186051f0429.png)

**Expected Behavior**:
Parameter hints for every single argument above

**Actual Behavior**:
Parameter hints only show for raw null

**Comment by CyrusNajmabadi** [comment]
Seems reasonable.  Technically they're not literals.  But since this is practically like 'trivia' it would be reasonable to show these when that option is set.
