### ISSUE TITLE
Intellisense suggests using auto-property for struct field (IDE0032)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48918]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-suggests-using-auto-propert/1232274?preview=true)._

---
Intellisense suggests using an auto property for a struct field when an explicit backing field is being used to avoid unnecessarily copying the struct. In this example, it suggests changing `Data` to an auto-property. This would cause the struct to be copied when `Data` instead of `_data` is accessed in the getter for `Bar`.

```
public class Foo
{
    private ReadOnlyMemory<byte> _data;
    public ReadOnlyMemory<byte Data => _data;
    public byte Bar => _data. Span[42];
}
```

---
#### kjkrum on 10/24/2020, 11:42 PM: 

<p>Here’s a fiddle demonstrating why the suggestion is wrong and potentially changes the behavior of a program: <a target='_blank' href="https://dotnetfiddle.net/sm5IAr">https://dotnetfiddle.net/sm5IAr</a></p>

#### Feedback Bot on 10/25/2020, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
**Design Meeting Notes**
The micro-performance considerations of the projects in the context of a particular JIT are not within the scope of our code style refactoring. customer should be able to disable this diagnostic suppressor or disable it

**Comment by CyrusNajmabadi** [comment]
Hrmm.. This should work.  If the struct is mutable, and the field is not readonly, then we normally disallow this.

**Comment by CyrusNajmabadi** [comment]
I just checked the .net fiddle case.  We don't appear to offer the fix here.  Will check the ROM case.

**Comment by CyrusNajmabadi** [comment]
I'm not seeing a problem here.  Can you show an example where we offer this feature *and* change semantics?

**Comment by kjkrum** [comment]
I can no longer even reproduce my original complaint. VS 16.8.2 no longer suggests making `Foo._data` an auto-property. Instead, it suggests making it `readonly`. It does not suggest making it an auto-property after making it `readonly` (and restarting VS) although the option to do so is still there if I press alt-enter on it.

**Comment by CyrusNajmabadi** [comment]
> although the option to do so is still there if I press alt-enter on it.

The option would be there. This is completely reasonable code to make into a property.

**Comment by kjkrum** [comment]
I withdraw the suggestion that this is a correctness issue. I can't contrive a scenario where accepting the suggestion changes the semantics.
