### ISSUE TITLE
Warn on pointer comparison between function pointers

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#48919]
From discussion in LDM 10/26/2020, this is something we want to warn on, as it is not a reliable comparison.

**Comment by PathogenDavid** [comment]
Is this because the function pointer of a managed function changes between before and after tiered JIT or something else?

**Comment by 333fred** [comment]
I don't remember the exact details of why, @jkotas do you have a more complete explanation? I just remember you told me that doing so is bad :).

**Comment by jkotas** [comment]
Taking address of the same method twice is not guaranteed to produce same pointer.

**Comment by jkotas** [comment]
> Is this because the function pointer of a managed function changes between before and after tiered JIT or something else?

Yes, this is one of the underlying reasons why it may change.
