### ISSUE TITLE
Nullcheck for an element inside a array should turn off the warning for this element

### ISSUE THREAD

**Issue by maSchoeller** [dotnet/roslyn#48945]
**Version Used**: 
.NET SDK 5.0.100-rc.2.20479.15

**Steps to Reproduce**:
1. new project
2. code snippet

```csharp
string?[] data = new string?[1];
//data[0]= "test";
if (data[0] is not null)
{
    string a = data[0];
}
if (data[0] != null)
{
    string a = data[0];
}
```
Same with two dimensional
```csharp
string?[,] data = new string?[1,1];
//data[0,0] = "test";
if (data[0,0] is not null)
{
    string a = data[0,0];
}
if (data[0,0] != null)
{
    string a = data[0,0];
}
//------------------------
string?[][] data = new string?[1][];
data[0] = new string[1];
//data[0] = new string?[1];
//data[0][0] = "test";
if (data[0][0] is not null)
{
    string a = data[0][0];
}
if (data[0][0] != null)
{
    string a = data[0][0];
}
```

**Expected Behavior**:
Rsolyn should know `data[0]` is not null inside the if statement.

**Actual Behavior**:
Visual Studio 2019 Preview
Version 16.8.0 Preview 5.0
![image](https://user-images.githubusercontent.com/56505280/97296569-23faf900-1851-11eb-8fe3-5bf5fe47a152.png)

Visual Studio Code 
version 1.50
Visual Studio Code - Insiders
version 1.51
![image](https://user-images.githubusercontent.com/56505280/97294931-f57c1e80-184e-11eb-9914-101e703b45cf.png)

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue but unfortunately this behavior is by design. The compiler does not track the flow state for array elements, instead their state is always based on the type of the array. 

https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types-specification.md#element-access

The more idiomatic approach here is the following 

```cs
if (data[0] is {} a)
{
  Console.WriteLine(a);
}
```

**Comment by maSchoeller** [comment]
Thanks for the quick response. 
Doesn't seem quite so intuitive to me, but I can understand the decision after some thought:D
