### ISSUE TITLE
Inline type hints insert themselves into inline out declarations

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#48941]
**Version Used**: 
Version 16.9.0 Preview 2.0 [30620.202.main]

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1103906/97266071-eb244980-187b-11eb-9632-4885c61d94e5.png)

**Expected Behavior**:

**Actual Behavior**:

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by sharwell** [comment]
This was fixed by #48763

**Comment by davkean** [comment]
@sharwell Are you sure? The test case is missing: https://github.com/dotnet/roslyn/pull/48763/files#diff-2748a0e4eb251c30bf82c1bc987d78faf0f87f374bfd9f528fc5d58d20383faeR282.

**Comment by sharwell** [comment]
No, I misread your example as `out var fullPath`, but what you have is `out string fullPath`. Assigning to @CyrusNajmabadi to add a test and fix if it isn't already.
