### ISSUE TITLE
An exception of type DirectoryNotFound has been encountered when navigating to a generated file

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#48958]
**Version Used**: 
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 5.0
VisualStudio.16.Preview/16.8.0-pre.5.0+30615.102
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:
Try to navigate to a generated file that will result in a very long file name
for a real-world example try https://github.com/YairHalberstadt/stronginject and navigate to `StrongInject.Extensions.DependencyInjection.Tests.ServiceCollectionExtensionTests.Container.generated.cs` which will result in a path like this: `C:\Users\username\AppData\Local\Temp\VisualStudioSourceGeneratedDocuments\d119adfa-f1ba-4f69-8f79-3e92c47af9d7\StrongInject\StrongInject.Generator.SourceGenerator\StrongInject.Extensions.DependencyInjection.Tests.ServiceCollectionExtensionTests.Container.generated.cs`

**Expected Behavior**:
VS navigates to the generated file

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/5566206/97359965-9ea63180-18ae-11eb-94a8-6720c753e4cd.png)

```
Could not find a part of the path 'C:\Users\username\AppData\Local\Temp\VisualStudioSourceGeneratedDocuments\d119adfa-f1ba-4f69-8f79-3e92c47af9d7\StrongInject\StrongInject.Generator.SourceGenerator\StrongInject.Extensions.DependencyInjection.Tests.ServiceCollectionExtensionTests.Container.generated.cs'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)   at System.IO.File.WriteAllText(String path, String contents)   at Microsoft.VisualStudio.LanguageServices.Implementation.SourceGeneratedFileManager.NavigateToSourceGeneratedFile(Project project, ISourceGenerator generator, String generatedSourceHintName, TextSpan sourceSpan)   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioSymbolNavigationService.TryNavigateToSymbol(ISymbol symbol, Project project, OptionSet options, CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.<>c.<TryNavigateToMetadataSymbol>b__6_0(ISymbol symbol, Project project, ISymbolNavigationService service)   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryNavigateToMetadataSymbol(Workspace workspace, String symbolKey, Func`4 action)   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryNavigateToMetadataSymbol(Workspace workspace, String symbolKey)   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryNavigateTo(Workspace workspace, Boolean showInPreviewTab, Boolean activateTab)   at Microsoft.CodeAnalysis.Editor.Host.IStreamingFindUsagesPresenterExtensions.<TryNavigateToOrPresentItemsAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)   at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionHelpers.TryGoToDefinition(ISymbol symbol, Solution solution, IThreadingContext threadingContext, IStreamingFindUsagesPresenter streamingPresenter, CancellationToken cancellationToken, Boolean thirdPartyNavigationAllowed)   at Microsoft.CodeAnalysis.Editor.GoToDefinition.AbstractGoToDefinitionService.TryGoToDefinition(Document document, Int32 position, CancellationToken cancellationToken)   at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.TryExecuteCommand(Document document, Int32 caretPosition, IGoToDefinitionService goToDefinitionService, CommandExecutionContext context)   at Microsoft.CodeAnalysis.Editor.GoToDefinition.GoToDefinitionCommandHandler.ExecuteCommand(GoToDefinitionCommandArgs args, CommandExecutionContext context)   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<ExecuteStartingAtIndex>b__0()   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```

**Notes**
The path from https://github.com/YairHalberstadt/stronginject is 259 symbols + your username length which requires `LongPathsEnabled` registry key. But even with this flag Visual Studio will throw an exception instead of navigating to this file.
Interestingly Visual Studio correctly handles long file path when debugging. I tried up to ~330 symbols paths for generated files in `%temp%\.vsdbgsrc\...` and they worked correctly

**Comment by jasonmalinowski** [comment]
There should be some help here with https://github.com/dotnet/roslyn/pull/49059:

"VisualStudioSourceGeneratedDocuments\d119adfa-f1ba-4f69-8f79-3e92c47af9d7\StrongInject\StrongInject.Generator.SourceGenerator"

part is shorter now. It looks like in your case it should save approximately 31 characters. @TessenR in your case with your username would that have been enough? (you trimmed the user name in your example which is totally fine but want to make sure there isn't a surprise there)

**Comment by jasonmalinowski** [comment]
And I did chat with the VS core editor team and there definitely wasn't any confidence that we support stuff greater than MAX_PATH; if it's working in some cases (and that's just not because the debugger is cloning it into a shorter file name) that's intriguing though!

**Comment by TessenR** [comment]
@jasonmalinowski Yes in my case the resulting name will be shorter than MAX_PATH after the change although it seems somewhat brittle as there's no length limit on the generated file name

By the way I tried to reproduce the long path in `%temp%\.vsdbgsrc\...` folder and it seems that I was mistaken. Probably I debugged and old source without re-running my source generator after updating the generated file name.

The latest preview shows this error when I try to debug a file with a very long name:
![image](https://user-images.githubusercontent.com/5566206/98830376-688ab500-244b-11eb-8e6c-8e8f2e17edea.png)

**Comment by jasonmalinowski** [comment]
> although it seems somewhat brittle as there's no length limit on the generated file name

Agreed it's brittle, I don't have a better answer, or at least not one that will come in the near term. There's a huge amount of VS legacy code that hard-codes MAX_PATH now (I just grepped for it and it's making me terribly sad), so even setting the LongPathsEnabled flag won't help much. The fact we're also generating a file name is currently working around some other shell limitations that we are looking to clean up, so that'll help further. It's possible that once we get that working we'll have _enough_ working to make the MAX_PATH issue moot.

Practically though we can't really give a clear length limit in the API, since for the temp files there's always the possibility somebody's username is really long or they've redirected %TEMP% somewhere. And since we also support a mode where you can write out the files to disk during build, then the limit up to MAX_PATH depends on your repository root directory too.

**Comment by jasonmalinowski** [comment]
Another change in https://github.com/dotnet/roslyn/pull/49673 reduced the path down a bit further, so at this point there's not much I can do without a larger architectural change here. I'm going to close this as "good enough" for now.

To people from the future who might stumble on this bug: if you do hit this, please poke this issue. I'm hoping this isn't widespread enough to be worth prioritizing this versus other issues, but if there's a lot of pokes maybe we'll have to do something else.
