### ISSUE TITLE
Don't cast when converting foreach loop to for loop unless necessary

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#48950]
**Version Used**: VS 16.8 preview 5

**Steps to Reproduce**:

```csharp
foreach (var x in new string[10])
{}
```

Run "Convert to 'for'" refactoring

**Expected Behavior**:

```csharp
var array = new string[10];
for (var i = 0; i < array.Length; i++)
{
    var x = array[i];
}
```

**Actual Behavior**:

```csharp
var array = new string[10];
for (var i = 0; i < array.Length; i++)
{
    var x = (string?)array[i];
}
```

**Comment by huoyaoyuan** [comment]
This should be an NRT issue. The codefix decides `string` inconsistent with `string?`.

**Comment by huoyaoyuan** [comment]
Well, it looks like the issue happens in lower layer.

The codefix generates full-qualified form `global::System.String?s =(global::System.String?)(array[i]);`, and let the simplifier to get appropriate form. The simplifier just doesn't remove the cast.

This only happens under `ImplicitTypeEverywhere`.

**Comment by huoyaoyuan** [comment]
Something interesting related: https://github.com/dotnet/csharplang/discussions/2575#discussioncomment-114110
Casting from non-nullable to nullable isn't really a nop for compiler.
