### ISSUE TITLE
No Justification info in sarif 2.1.

### ISSUE THREAD

**Issue by LLLXXXCCC** [dotnet/roslyn#48972]
**Version Used**: 3.400.19.50406

**Steps to Reproduce**:

1. Suppress the rule by putting `[SuppressMessage("Microsoft.NetCore.Analyzers", "CA5386:DoNotUseDeprecatedSecurityProtocols", Justification = "Some reasons.")]` in the code.
2. csc.exe /Some other arguments /errorlog:"D:\a\b\c\sarif.RB.json,version=2"

**Expected Behavior**: 
1. Get a sarif.RB.json file whose version is 2.1.
2. The expected JSON is like 
`{
  "$schema": "http://json.schemastore.org/sarif-2.1.0",
  "version": "2.1.0",
  "runs": [
    {
      "results": [
        {
          "ruleId": "CA5386",
          "ruleIndex": 0,
          "level": "warning",
          "message": {
            "text": "Avoid hardcoding SecurityProtocolType Tls12, and instead use SecurityProtocolType.SystemDefault to allow the operating system to choose the best Transport Layer Security protocol to use."
          },
          "suppressions": [
            {
              "kind": "inSource",
              "justification": "Some reasons."
            }
          ],
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/Users/linche/source/repos/ConsoleApp51/ConsoleApp51/Program.cs"
                },
                "region": {
                  "startLine": 26,
                  "startColumn": 52,
                  "endLine": 26,
                  "endColumn": 78
                }
              }
            }
          ],
          "properties": {
            "warningLevel": 1
          }
        }
      ]
    }
  ]
}`

**Actual Behavior**:
1. The version is right.
2. However, the 'justification' property is missing.
Here's the part of roslyn/src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs,
`if (diagnostic.IsSuppressed)
            {
                _writer.WriteArrayStart("suppressions");
                _writer.WriteObjectStart(); // suppression
                _writer.Write("kind", "inSource");
                _writer.WriteObjectEnd(); // suppression
                _writer.WriteArrayEnd();
            }`
Looks like only the 'kind' property was put under the 'suppression' object. According the standard schema of sarif 2.1, the 'justification' property should be there.
Here's the result Sarif file produced by the command above.
`{
  "$schema": "http://json.schemastore.org/sarif-2.1.0",
  "version": "2.1.0",
  "runs": [
    {
      "results": [
        {
          "ruleId": "CA5386",
          "ruleIndex": 0,
          "level": "warning",
          "message": {
            "text": "Avoid hardcoding SecurityProtocolType Tls12, and instead use SecurityProtocolType.SystemDefault to allow the operating system to choose the best Transport Layer Security protocol to use."
          },
          "suppressions": [
            {
              "kind": "inSource"
            }
          ],
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/a/b/c/Program.cs"
                },
                "region": {
                  "startLine": 26,
                  "startColumn": 52,
                  "endLine": 26,
                  "endColumn": 78
                }
              }
            }
          ],
          "properties": {
            "warningLevel": 1
          }
        }
      ]
    }
  ]
}`

**Comment by jaredpar** [comment]
Can u describe a bit more what you are expecting to see here?

Sarif was done mostly by an external team and while we reviewed and signed off on the change the Sarif spec is not our speciality. It's not clear what  your asking for here.

**Comment by LLLXXXCCC** [comment]
Hi @jaredpar , thanks for response, the description was updated.
The thing is that the SARIF file produced by Roslyn doesn't match the schema of SARIF spec. Here's the link of SARIF 2 schema: https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127930.

**Comment by jaredpar** [comment]
Looking at the spec 

> A suppression object MAY contain a property named justification whose value is a user-supplied string that explains why the result was suppressed.

Sounds like the justification property is optional here, not required. Hence I don't believe we're failing to match the spec here. Instead it seems like there are optional parts we're not taking advantage of. Correct?

**Comment by LLLXXXCCC** [comment]
1. The justification property is optional. To my understand, it means the result SARIF file contains the justification property or not depends on whether users offer it when using the SuppressMessageAttribute.
2. You mean Roslyn doesn't produce the justification property in the SARIF 2. Is there any argument I can integrate with csc.exe to get the justification property?

**Comment by Cyassin** [comment]
Hey @jaredpar - I'm also having concerns with this missing for an internal project of mine.  Hoping I can provide some context into why this is important for consumers of the SARIF file export.

As you are probably aware a SuppressMessage can be used in .NET code to suppress what might normally be a warning or build error. A justification message is an optional parameter to this, but this really depends on the companies internal coding practices - I think its smart to explain why you've suppressed something (for the next developer to understand).

We have our own internal roslyn analyzers for providing strict guardrails on what you can/can't do when developing our products. Obviously there are instances where you need exceptions to this rule, and we ask our developers to Suppress it with a justification, which then goes through a manual review/acceptance process by the security team etc.

The internal project I am working on takes the SARIF file and sends it to a tool we developed that has a GUI and presents the findings in a nice layer for visibility, reporting etc. (Similar to SonarQube).

With our review process for suppressed items - after all what's the point in having guard rails if people aren't following them. These reviewers are engineers but have to look at a code base of 20+ products and 20+ million lines of code. I'm sure as a reviewer you don't want to be manually crawling for the suppress messages in the code for each item by manually digging up the code etc. just to see an empty suppress message - or something that is gibberish. 

If the SARIF files contained that suppress justification, it can instantly go to the reporting tool so reviewers can straight away see the messages, or automatically flag empty justifications etc. SARIF helps us have data on issues in our code for better visibility/analysis etc. without needing direct access to the code, it makes complete sense to know why somethings been suppressed.

Without this currently, our GUI built from the data just basically says "Suppressed" but without context and has been a problem for consumers of our internal tool (a dev team of 300). My only current solution is to write a parser that takes the code and extracts the justifications manually and maps them - Just seems like duplicated effort on our Ci/Cd pipelines.

**Comment by Cyassin** [comment]
Hey @jaredpar can we get this re-opened? I'm hoping my comment earlier was enough requested information to keep this open. 

This issue won't have a lot of support as there is probably few companies writing their own reporting tools for their analyzer data, but this would be in my opinion a big problem for any in the future who want to do so. For helping orgs improve the quality of their code we should be making analyzers as easy as possible to adopt and having appropriate reporting data is an important part of this.

**Comment by jaredpar** [comment]
@Cyassin yes reopened.

We recently added some automation around our "Need More Info" labels. Going forward your comment would've removed the label but we couldn't set the automation to apply it retroactively.

**Comment by Cyassin** [comment]
> @Cyassin yes reopened.
> 
> We recently added some automation around our "Need More Info" labels. Going forward your comment would've removed the label but we couldn't set the automation to apply it retroactively.

@jaredpar awesome - no worries at all. Much appreciated!

**Comment by LLLXXXCCC** [comment]
My fault, forgot to close this ticket. Actually, I already created a PR in 2020 and added the justification info. https://github.com/dotnet/roslyn/pull/49202
