### ISSUE TITLE
C# Interactive: "#reset core" and "#help": are not discoverable

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#48984]
I had no idea either of these existed (`#reset core` or `#help`).

As an example of how _undiscoverable_ these are, check out [this feedback ticket](https://developercommunity2.visualstudio.com/t/Make-shCsh-shInteractivesh-us/746242?entry=problem) which has +12 votes asking for .NET Core support, which *you already have* but folks can't find it.

**Comment by weitzhandler** [comment]
Ideally .NET Core 5 and C# 9, if available.
Thanks for posting these issues @AArnott.

**Comment by tmat** [comment]
The feedback was filed before we had the feature though.

**Comment by tmat** [comment]
While I agree with `#reset core` can be improved, I don't agree with `#help` not being discoverable. The REPL literally tells you to use it to get help:

![image](https://user-images.githubusercontent.com/41759/97495107-8113af00-1924-11eb-81af-c1926b42e701.png)

**Comment by weitzhandler** [comment]
Not sure if related, but talking about REPL UX and productivity, the shortcut <kbd>Ctrl</kbd>+<kbd>E</kbd>,<kbd>E</kbd> auto selects text in editor and opens it in the REPL. When no text is selected it copies the current line in the REPL. To me, this is most of the time just annoying because I just want to open the REPL and type stuff in there. AFAIK, there is no direct shortcut to just open the REPL without input.

**Comment by tmat** [comment]
@weitzhandler Thanks for the feedback. Would you mind filing a separate issue? @mikadumont for finding some key binding we could use. F# interactive has `Ctrl+Alt+F`.

**Comment by weitzhandler** [comment]
@tmat sorry for polluting this discussion then. Should I file the issue here or on DevCommunity?

**Comment by tmat** [comment]
@weitzhandler Here.

**Comment by weitzhandler** [comment]
https://github.com/dotnet/roslyn/issues/49017.
Deleting previous unrelated comments to clean up this thread.

**Comment by GF-Huang** [comment]
How to make it use core default?

**Comment by tmat** [comment]
@GF-Huang It can't be set to default currently.
