### ISSUE TITLE
GenerateTypeCodeFixProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48982]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/GenerateTypeCodeFixProvider-encountered-/1229022?preview=true)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Version 16.8.0 Preview 4.0]
Error encountered on first use of today's VS update. Using VS 2019 Community Preview, Version 16.8.0 Preview 5.0

---
#### Mila Zhou[MSFT] on 10/21/2020, 07:55 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario?</p>
<p>We look forward to hearing from you!</p>

####  on 10/22/2020, 05:53 AM: 

<p>Problem occurred once, spontaneously.  Unable to reproduce or record.  Suggest review of log submitted with problem.</p>

#### Feedback Bot on 10/22/2020, 11:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/23/2020, 09:40 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by JoeRobich** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/48962

**Comment by MagicAndre1981** [comment]
when will this be fixed? 16.9? I also got it today in 16.8

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/100393937-34d59080-2ff0-11eb-85b5-30f599e6ca95.png)
