### ISSUE TITLE
Quick Info for suppressions does not work for compiler warning numbers

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#49008]
**Version Used**: 1a8a5724a

**Steps to Reproduce**:

```
#pragma warning disable CS0252
#pragma warning disable 0252
#pragma warning disable 252
```

**Expected Behavior**:

Hovering over any of the three warning IDs or numbers shows the Quick Info for CS0252.

**Actual Behavior**:

Quick Info only works when the full ID is specified (the first example line).

**Comment by MaStr11** [comment]
FYI: The PR that introduced quick info for `#pragma warning` was #46817. Should I take a look?
