### ISSUE TITLE
[loc][query] help with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn#49002]
String Resource ID | 0; "Inline_0"
Source String | Inline '{0}'
Filename | Features\Core\Portable\xlf\FeaturesResources.xlf
Question | Is "Inline" a verb in this context". What will {0} be replaced with

**Comment by cristianosuzuki77** [comment]
vcq 302911

**Comment by Cosifne** [comment]
@cristianosuzuki77 
It is similar to this https://github.com/dotnet/roslyn/issues/49060
It will be "Inline Bar". And inline is a verb here
