### ISSUE TITLE
Automatically fix curly quotes copy paste

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#49018]
**Brief description:**
Automatically detect and replace curly quote with straight quotes. User reported commonly needing to copy/paste quotes and then go back and fix errors.

![image](https://user-images.githubusercontent.com/8293542/97511848-4a01c580-1945-11eb-9055-4915b0c4bf50.png)

**Languages applicable:**
Specifically requested for C#.

**Additional information:**

Related to https://github.com/dotnet/roslyn/issues/31869

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
