### ISSUE TITLE
Memberlookup of types from generic constraints

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49014]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1208436/memberlookup-of-types-from-generic-constraints.html)._

---
```
//CS0704 - No memberlookup in typeparameter possible
interface IA<T> where T : IB {
    T.IC Value ( );
    }
interface IB {
    interface IC { }
}
```
intellisense already knows T.IC

---
#### Feedback Bot on 10/5/2020, 04:15 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue but the behavior here is "By Design". Type parameters cannot be used for `static` member lookup. 

> A type parameter cannot be used in a member access (Member access) or type name (Namespace and type names) to identify a static member or a nested type.

https://github.com/dotnet/csharplang/blob/master/spec/types.md#type-parameters
