### ISSUE TITLE
Confusion about optional parameter constructors in C# specification v5

### ISSUE THREAD

**Issue by arkoc** [dotnet/roslyn#4901]
In C# 5 Language Specification 

Section 1.6.7:
List<T> class table: label of constructor with optional parameter is "Constructors".

Section 1.6.7.1:
>Instance constructors can be overloaded. For example, the List class declares two instance constructors, one with no parameters and one that takes an int parameter.

But compiled IL for this code doesn't contain 2 constructors.
Optional parameters, no matter if used on methods or constructors, do not introduce additional overloads. Instead, optional parameters are marked with [opt], and whenever you call it without that parameter value specified that optional value will be included in your compiled code.

**Comment by HaloFour** [comment]
Comparing it to the C# 3.0 spec it looks like that sample code for a `List<T>` class was updated to demonstrate optional parameters where it used to have two separate constructors, but the mention about constructor overloading was not updated.

**Comment by gafter** [comment]
It looks like this is fixed in the ECMA draft.
