### ISSUE TITLE
EnC: Allow adding/removing/updating attributes

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#49012]
Allow all custom attributes on .NET Core.
Allow specific (nullability) custom attributes on .NET Framework.

- [ ] Debugger needs to trigger an event that notifies Reflection to invalidate caches in the debuggee - via func-eval.
   The event has well-known full name with specific signature. It may be declared in any assembly and have any accessibility. Design with BCL.

**Comment by lambdageek** [comment]
Not sure about this.  Some attributes are meaningful to the runtime.  (for example `OffsetAttribute` on a struct with explicit layout).

**Comment by tmat** [comment]
@lambdageek Yes, we would need to exclude those. Not that these attributes are not real custom attributes. They are emitted as metadata flags.

**Comment by lambdageek** [comment]
@tmat it's not just pseudo custom attributes.  It's also things like `UnmanagedCallersOnlyAttribute` and `SuppressGCTransitionAttribute`.

**Comment by tmat** [comment]
I see. We'll probably need to have a list of special ones.
