### ISSUE TITLE
Provide Constructor Refactoring Using Tuple Syntax

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49037]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1038496/provide-constructor-refactoring-using-tuple-syntax.html)._

---
1.  Create a class with multiple properties, like this:
```
public class LotsOfData
{
	public Guid GuidValue { get; }
	public int IntData { get; }
	public string StringValue { get; }
}
```
2. Select the _Generate constructor..._ refactoring, and keep the default selections.
3. The resulting constructor looks like this:
```
public class LotsOfData
{
	public LotsOfData(Guid guidValue, int intData, string stringValue)
	{
		this. GuidValue = guidValue;
		this. IntData = intData;
		this. StringValue = stringValue;
	}

public Guid GuidValue { get; }
	public int IntData { get; }
	public string StringValue { get; }
}
```
What I'd love to have is an option to generate the constructor using tuples for initialization:
```
public class LotsOfData
{
	public LotsOfData(Guid guidValue, int intData, string stringValue)
	{
		(this. GuidValue, this. IntData, this. StringValue) =
			(guidValue, intData, stringValue); 
	}

public Guid GuidValue { get; }
	public int IntData { get; }
	public string StringValue { get; }
}
```
From what I understand about this approach, it has the same perf characteristics. It's also a little more succinct, which I like, and it allows me to use an expression-bodied constructor (which removes the curly braces for the constructor).

---
#### Feedback Bot on 5/20/2020, 02:43 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
