### ISSUE TITLE
how to compile a '.NETCoreApp,v5.0'  class lib using Roslyn?

### ISSUE THREAD

**Issue by timiil** [dotnet/roslyn#49030]
i am trying to compile a  '.NETCoreApp,v5.0'  class lib using Roslyn, using the flowing code which in a .NET 5 console app :

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp; 
using Microsoft.CodeAnalysis.Emit;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

namespace RoslynIssueRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            string codeToCompile =
                @"
                using System;

                namespace RoslynCompileSample
                {
                    public class Writer
                    {
                        public void Execute()
                        {
                            Console.WriteLine(""Freshly compiled code execution done!"");
                        }
                    }
                }";

            var refPaths = new[] {
                typeof(System.Object).GetTypeInfo().Assembly.Location,
                typeof(Console).GetTypeInfo().Assembly.Location,
                Path.Combine(Path.GetDirectoryName(typeof(System.Runtime.GCSettings).GetTypeInfo().Assembly.Location), "System.Runtime.dll"),                                
            };


            royslynCompileAndExecute(codeToCompile, refPaths);
        }        
        
        private static void royslynCompileAndExecute(string codeToCompile, string[] refPaths)
        {
            Console.WriteLine("Let's compile!");

            Console.WriteLine("Parsing the code into the SyntaxTree");
            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(codeToCompile);

            string assemblyName = Path.GetRandomFileName();
            
            MetadataReference[] references = refPaths.Select(r => MetadataReference.CreateFromFile(r)).ToArray();

            Console.WriteLine("Adding the following references");
            foreach (var r in refPaths)
                Console.WriteLine("\t" + r);

            Console.WriteLine("Compiling ...");
            CSharpCompilation compilation = CSharpCompilation.Create(
                assemblyName,
                syntaxTrees: new[] { syntaxTree },                
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            using (var ms = new MemoryStream())
            {
                EmitResult result = compilation.Emit(ms);

                if (!result.Success)
                {
                    Console.WriteLine("Compilation failed!");
                    IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                        diagnostic.IsWarningAsError ||
                        diagnostic.Severity == DiagnosticSeverity.Error);

                    foreach (Diagnostic diagnostic in failures)
                    {
                        Console.Error.WriteLine("\t{0}: {1}", diagnostic.Id, diagnostic.GetMessage());
                    }
                }
                else
                {
                    Console.WriteLine("Compilation successful! Now instantiating and executing the code ...");
                    ms.Seek(0, SeekOrigin.Begin);

                    File.WriteAllBytes("tmp.dll", ms.ToArray());
                    //Assembly assembly = AssemblyLoadContext.Default.LoadFromStream(ms);
                    Assembly assembly = Assembly.LoadFrom("tmp.dll");
                    var type = assembly.GetType("RoslynCompileSample.Writer");
                    var instance = assembly.CreateInstance("RoslynCompileSample.Writer");
                    var meth = type.GetMember("Execute").First() as MethodInfo;
                    meth.Invoke(instance, null);
                }
            }
        }       
        
    }
}

```

the code can complie the 'tmp.dll' but the dll is JUST .NET FRAMEWORK 4.0, any idea to make the output dll come to .NET 5 ??

**Comment by PathogenDavid** [comment]
What makes you think it's targeting .NET Framework 4? You're referencing assemblies from the .NET 5 BCL.

If you're looking in something like ILSpy, I believe it just displays what [`TargetFrameworkAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.targetframeworkattribute) says and assumes .NET Framework 4 what it's missing.

Normally that attribute is [automatically added by MSBuild](https://github.com/dotnet/msbuild/blob/c10f34c4e00644e06120cb87f323c330f29a1e89/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3327-L3369), so if you want it you need to add it manually. For example:

```csharp
[assembly: TargetFramework(".NETCoreApp,Version=v5.0", FrameworkDisplayName = "")]
```

However I'm pretty sure it's purely informational, I don't think specifying it affects anything functionality-wise.

If you want to see the attribute that gets generated for your projects, you can view it by looking for the generated file in the intermediate directory. (EG: `obj\Debug\net5.0\win-x64\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs`)

**Comment by timiil** [comment]
> What makes you think it's targeting .NET Framework 4? You're referencing assemblies from the .NET 5 BCL.
> 
> If you're looking in something like ILSpy, I believe it just displays what [`TargetFrameworkAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.targetframeworkattribute) says and assumes .NET Framework 4 what it's missing.
> 
> Normally that attribute is [automatically added by MSBuild](https://github.com/dotnet/msbuild/blob/c10f34c4e00644e06120cb87f323c330f29a1e89/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3327-L3369), so if you want it you need to add it manually. For example:
> 
> ```cs
> [assembly: TargetFramework(".NETCoreApp,Version=v5.0", FrameworkDisplayName = "")]
> ```
> 
> However I'm pretty sure it's purely informational, I don't think specifying it affects anything functionality-wise.
> 
> If you want to see the attribute that gets generated for your projects, you can view it by looking for the generated file in the intermediate directory. (EG: `obj\Debug\net5.0\win-x64\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs`)

thanks you very muchmuch for clearly the info.  yes I really check the dll using by ILSpy

**Comment by PathogenDavid** [comment]
No problem, glad I could help!

**Comment by jaredpar** [comment]
Closing as it appears the issue is resolved.
