### ISSUE TITLE
Can't rename inaccessible member

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#4904]
If you try to rename the ref, you get an error dialog ("cannot rename").  If you rename the def, it considers the ref to have an unresolvable conflict and doesn't update.

``` C#
class C
{
    static void Main(string[] args)
    {
        D.field = 8; // rename ref
    }
}
 
class D
{
    private static int field; // rename def
} 
```

**Comment by amcasey** [comment]
FYI @dpoeschl

**Comment by amcasey** [comment]
Motivation: I see that ```_field``` is inaccessible and I want to rename it to ```Field```.

**Comment by Pilchie** [comment]
Similar to #3584.  We need to think about better heuristics for rename in error cases.
