### ISSUE TITLE
In VB.NET, add hover-over property values within With/EndWith blocks when debugging

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49043]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/420273/in-vbnet-add-hover-over-property-values-within-wit.html)._

---
<p>So for instance, </p><pre>        With objectWithManyProps
            .Prop1 = &quot;a&quot;
            .Prop2 = &quot;b&quot;
            .Prop3 = &quot;c&quot;
        End With</pre><p class="">... currently, hovering over the .Prop1, .Prop2 etc does not popup the value.  This leads to developers avoiding using the With/End With construct, instead adding clutter by repeating the object name - and using less meaningful object names in order to keep them short - for the sake of debuggability.  </p><p class="">It would be far better if hovering over the .Prop1 etc popped up the value when debugging. </p>
</pre>

---
#### Jane Wu [MSFT] on 1/6/2019, 06:31 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Fourth Level on 3/21/2019, 09:53 AM: 

<p>I notice this has not been implemented yet in VS2019 RC3.  Are there any plans to include it as a feature?  It would be a substantial enhancement for debugging VB code while maintaining readability.</p>

#### Kathleen Dollard [MSFT] on 12/1/2019, 03:07 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by paul1956** [comment]
This issue should be combined with "[VB.NET] Debug Mode doesn't support With blocks #48681", it is two solutions to address the same underlying problem.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to be changing these experiences.
