### ISSUE TITLE
Plan of Record for evolving the enforcement of code style in the SDK

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#49044]
## Behavior in .NET 5

In .NET 5 we ship in the following state by default.
- **Command line build**: Code style analysis is disabled, by default, for all .NET projects on command-line builds.
- **Visual Studio**: Code style analysis is enabled, by default, for all .NET projects inside Visual Studio 

If the use sets the `EnforceCodeStyleInBuild` property in their project file to `true` as shown below:

```xml
<PropertyGroup>
  <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
</PropertyGroup>
```

Then the user gets the following experience:

- **Command line build**: Code style analysis is enabled for all .NET projects on command-line builds.
- **Visual Studio**: Code style analysis is enabled, by default, for all .NET projects inside Visual Studio 

**We are communicating that this option is _experimental_ because we do not currently have a plan of record for how to evolve code style rules in the SDK**

## Approaches Taken in .NET Analyzers

- Tied new warnings to release "waves" so users can decide when to change the set of warnings they get.
- Always attempt to ship the latest analyzers in both release vehicles (both the SDK and Visual Studio) and let VS loading logic pick whichever one is newer

## Open Questions

- How do we ensure that new code style rules that are introduced do not break users? Do we want to re-use the `AnalysisLevel` msbuild property or invent a new system?
- How do we rationalize stlye rules across different shipping mechanisms? Do we believe the approach taken for .NET Analyzers is sufficient for code style?

**Comment by jmarolf** [comment]
cc: @mikadumont and @mavasani

**Comment by mavasani** [comment]
> How do we ensure that new code style rules that are introduced do not break users? Do we want to re-use the AnalysisLevel msbuild property or invent a new system?

One point to note here: Code style rules will never be warnings/errors by default, so cannot introduce breaking changes. Only scenario where they can be potential breaking changes are if users set `dotnet_analyzer_diagnostics.category-Style.severity = warning`, but that setting is specifically meant for agressive adoption and shows intent to get all new rules as breaking changes by default, so I would not worry about it. Does this give us confidence that we do not need any such property?

> How do we rationalize stlye rules across different shipping mechanisms? Do we believe the approach taken for .NET Analyzers is sufficient for code style?

Yep, this seems to be the core open question. Current VS de-dupe implementation of VSIX and NuGet analyzers ensure that any new code style rules added in Roslyn/VS that have not made their way into .NET SDK will still show up as IDE-only code styles, until they eventually make it into .NET SDK. So, the only remaining issue is the _optimal cadence_ of bug fixes to existing rules (that have already shipped in the SDK) to make it from Roslyn/VS into the SDK. As soon as user sets `EnforceCodeStyleInBuild = true`, the analyzer version from the SDK runs both in VS and CI, so faster cadence of delivering bug fixes needs faster cadence of insertions of CodeStyle assemblies into .NET SDK. IMO, this insertion cadence is the only real known open question in this space.

**Comment by jmarolf** [comment]
> but that setting is specifically meant for aggressive adoption and shows intent to get all new rules as breaking changes by default, so I would not worry about it. 

I would still expect that we are not allowed to change behavior here. Do we think there is fundamentally a different bar for code style enforcement vs. other analysis rules? If a user says they want a code style rule to be and error and changes nothing but the version of the SDK they use is it ok to break their build?

**Comment by jmarolf** [comment]
## Goals

- Code style in enforceable in both the IDE and on the commandline in the exactly the same way
- New Code Style rules can be shipped to Visual Studio users each point release (i.e. VS 16.8, 16.9, 16.x)

## Proposed behavior:

We align the version of code-style analyzer that ship in the .NET SDK and VS

- We dual-insert code style analyzers so that, for each release of Visual Studio an .NET SDK is also included that contains the latest code stylerules

## Engineering Implications

- today the .NET SDK does ship a new version with each VS point release but these typically only include critical bug fixes. We would need approval from the SDK team to ship feature updates in these SDK releases.
- The schedules for the .NET SDK and Visual studio do not exactly alight (but roughly do) so, worst case, code style PRs would need to be merged earler than normal

**Comment by jmarolf** [comment]
this is now complete
