### ISSUE TITLE
Bulk configure analyzer diagnostics doesn't work

### ISSUE THREAD

**Issue by anreton** [dotnet/roslyn#49052]
**Version Used**: 
Visual Studio 16.7.7

https://github.com/dotnet/roslyn/pull/38886

**Steps to Reproduce**:

1. Install Analyzers:
  1.1. Roslynator
https://www.nuget.org/packages/Roslynator.Analyzers/
https://www.nuget.org/packages/Roslynator.Formatting.Analyzers
  1.2. Microsoft Code Analysis
https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers
  1.3. SonarLint
https://www.nuget.org/packages/SonarAnalyzer.CSharp/
  1.4. StyleCop
https://www.nuget.org/packages/StyleCop.Analyzers/
2. Create .editorconfig with bulk configure analyzer diagnostics
`dotnet_analyzer_diagnostic.severity = warning`
3. Violate at least one of the rules of any analyzers.

**Expected Behavior**:
All warnings from any installed analyzers should be generated for each rule violation covered by the bulk configuration.

**Actual Behavior**:
Only StyleCop warnings (with SA prefix) generated for each rule violation.

**Comment by mavasani** [comment]
@anreton Can you please paste your entire editorconfig? Do you have the `[*.cs]` section header for the bulk configuration entry?

**Comment by mavasani** [comment]
Also can you please confirm whether you see this behavior on command line build, build inside VS or for intellisense diagnostics while typing (or a combination of these)?

**Comment by anreton** [comment]
@mavasani, thank you for your quick response. Please look at the repository (master branch) - https://github.com/anreton/Anreton.RabbitMq

I set manually the warning severity for all analyzer rules in an .editorconfig file (current state in master branch). And I have 1220 warnings and 1 suggestions from all analyzers (Roslynator - RCS prefix, StyleCop - SA prefix, SolarLint - S prefix, FxCopAnalyzers - CA prefix).

Then I replace the manual configuration of the analyzers (clear section **#### Analyzers Rules ####** in an .editorconfig file) with bulk configure analyzer diagnostics:
`dotnet_analyzer_diagnostic.severity = warning`
And I have 415 warnings and 0 suggestions. And only from StyleCop analyzer (with SA prefix) and few from FxCopAnalyzers (with CA prefix).

And I have the [*.cs] section header. And I see this behavior on build inside VS (in output window the situation is the same).

**Comment by anreton** [comment]
Hmm, could this behavior depend on the fact that `Enabled by default` is false? (using a separate analyzer RCS1198 as an example)

![image](https://user-images.githubusercontent.com/28877846/98157296-34af0d00-1eea-11eb-9726-c12380ed1992.png)

After adding bulk configure analyzer diagnostics
`dotnet_analyzer_diagnostic.severity = warning`
![image](https://user-images.githubusercontent.com/28877846/98157597-98d1d100-1eea-11eb-920a-084729a5894c.png)

**Comment by anreton** [comment]
Oh, my fault, my inattention ... (((

![image](https://user-images.githubusercontent.com/28877846/98158129-8015eb00-1eeb-11eb-990c-6321dbc3b636.png)

https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file

**Comment by mavasani** [comment]
Thanks @anreton - what you possible want is the feature request mentioned in https://github.com/dotnet/roslyn/issues/47046#issuecomment-678474546?

**Comment by anreton** [comment]
@mavasani, definitely, I think feature request from comment (https://github.com/dotnet/roslyn/issues/47046#issuecomment-678474546) sounds reasonable and useful.

We can see that there are scenarios where setting a value to `dotnet_analyzer_diagnostic.severity` simply doesn't help. Accordingly, if there is an option _to allow specifying a new configuration entry kind to explicitly apply to disabled by default analyzers_, the above scenarios will also be covered.

The only question is the complexity of the implementation and the impact on the rest of the parts.

**Comment by anreton** [comment]
@mavasani, I think we can close this issue and mark it as a duplicate of https://github.com/dotnet/roslyn/issues/47046.
