### ISSUE TITLE
[loc] Update comments in XLF

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn#49058]
String Resource ID | 0; "Using_directives_must_be_placed_outside_of_a_namespace_declaration"
-- | --
Source String | Using directives must be placed inside of a namespace declaration
Filename | Analyzers\CSharp\Analyzers\xlf\CSharpAnalyzersResources.[language].xlf
Question | is the note about "using" in this string still valid? If so the source string must be changed to  be "using" lowered to match with the note  {Locked="using"}. The string in the "locked" statement is case-sensitive.

**Comment by cristianosuzuki77** [comment]
vcq 326041

**Comment by cristianosuzuki77** [comment]
@crsuzukimsft

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.
