### ISSUE TITLE
EditAndContinueWorkspaceServiceTests.GetDocumentTextChangesAsync is flaky

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#49065]
Flaky failure of https://github.com/dotnet/roslyn/blob/d613476f7ea7719ec68ad28025fa0f41ed29563c/src/EditorFeatures/Test/EditAndContinue/EditAndContinueWorkspaceServiceTests.cs#L2187

```
Expected:
[17..17) '
',
[64..65) '9',
[98..99) '',
[133..133) '0'
Actual:
[17..17) '
',
[35..103) '',
[132..133) '9',
[137..137) '    System.Console.WriteLine();
System.Console.WriteLine(30);
'
Differences:
[17..17) '
',
++> [35..103) '',
++> [132..133) '9',
++> [137..137) '    System.Console.WriteLine();
System.Console.WriteLine(30);
',
--> [64..65) '9',
--> [98..99) '',
--> [133..133) '0'

Expected: True
Actual:   False
```

https://dev.azure.com/dnceng/public/_build/results?buildId=870738&view=ms.vss-test-web.build-test-results-tab&runId=27859898&resultId=164030&paneView=debug

**Comment by jasonmalinowski** [comment]
FYI to @tmat -- I guess our tree diffing is somehow non-deterministic?

**Comment by tmat** [comment]
I saw this happen before, but only a couple of times. The diffing is deterministic. I have no ide why this can possibly fail :(

**Comment by tmat** [comment]
BTW, all this test does is call SourceText.GetTextChanges(oldText) - there is no complex diffing going on.
https://github.com/dotnet/roslyn/blob/d613476f7ea7719ec68ad28025fa0f41ed29563c/src/Features/Core/Portable/EditAndContinue/EditAndContinueWorkspaceService.cs#L278

**Comment by jasonmalinowski** [comment]
@tmat: it calls the tree diff first, and only if that returns no changes it then calls the text diff. So I guess it's actually the tree differ that's non-deterministic...?

**Comment by jasonmalinowski** [comment]
(a quick glance through the differ doesn't find anything obvious like us enumerating some structure that might sort by object.GetHashCode() or anything that might be impacted by weak syntax nodes or anything...)

**Comment by CyrusNajmabadi** [comment]
Closing out as this test doesn't seem to exist.
