### ISSUE TITLE
Microsoft.NET.Sdk.Web could not be found

### ISSUE THREAD

**Issue by Thaval** [dotnet/roslyn#49063]
**Version Used**: 4.0 
Windows 10

**Steps to Reproduce**:

1. Install SDK and runtimes from https://dotnet.microsoft.com/download/dotnet-core/3.1
2. Install VS19 and add ASP.NET Web-Dev and .NET Core-Dev workloads
3. Create a new .NET Framework solution and install roslyn in that project
4. Create a new dummy .NET Core web api solution in another place (the project file *.csproj should have a "Microsoft.NET.Sdk.Web" entry at the top)
5. From the first .NET Framework solution, load the .NET Core solution and iterate over the projects and syntax trees

A partial list of packages I installed.
![image](https://user-images.githubusercontent.com/22428095/97645821-3e4df600-1a4e-11eb-979c-98b1b79bce8e.png)

**Expected Behavior**:

I expect that I can see all documents and syntax trees but they are empty. As I'm integrating a lot of nugets, I wonder what's the problem... it work on my working machine but not on my private machine. 

**Actual Behavior**:

The compilation does not work, therefore there are no documents within the project object and I can't do anything with it. 

If you need any further information, please let me know. I absolutely have no clue what could cause this issue.

**Comment by JoeRobich** [comment]
@Thaval I have a little experience using MSBuild Locator and MSBuildWorkspace to load .NET Core projects, so maybe I can help. Can you answer a few questions to help narrow down what is going on?

- Did you use the .msi installer to install the .NET Core SDK or did you download the zipped binaries?
- Does it work if you run `dotnet restore` on the .NET Core Web API project before trying to open?
- What are the reported workspace diagnostics (`msbuildWorkspace.Diagnostics`) after you try to open the Web API project?
- What versions of Visual Studio do you have installed?
- What MSBuild instance is the locator loading?

**Comment by Thaval** [comment]
Hi, 

sorry for the late kick-in! 
I used the *.exe to install the dotnet sdks. dotnet restore was successfully run before trying to open the solutions/projects.
However, I made it finally, but don't ask me how I did it!
I guess I solved it by downloading more sdks (which are used by the opened that I tried to open) and do a reboot. It "suddenly" worked out.
