### ISSUE TITLE
Switch Statement to Expression Drops a bunch of cases

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#49067]
**Version Used**: Version 16.8.0 Preview 6.0

**Steps to Reproduce**:

1. Navigate to https://github.com/dotnet/roslyn/blob/master/src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs#L87
2. Invoke the switch statement to expression refactoring

**Expected Behavior**:

All cases handled in the resulting switch expression.

**Actual Behavior**:

Only `ClassPublic` is handled.
![image](https://user-images.githubusercontent.com/2371880/97665924-d1c8fc00-1a39-11eb-99db-bcba13efa96f.png)

**Comment by Youssef1313** [comment]
Duplicate of #48829

**Comment by 333fred** [comment]
Ah, thanks.
