### ISSUE TITLE
[Loc] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn#49060]
String Resource ID | 0; "Inline_and_keep_0"
-- | --
Source String | Inline and keep '{0}'
Filename | Features\Core\Portable\xlf\FeaturesResources.xlf
Question | What will {0} be replaced with? Is "Inline" a verb in this context"

**Comment by cristianosuzuki77** [comment]
vcq 328632

**Comment by Cosifne** [comment]
> vcq 328632

@cristianosuzuki77 
{0} will be replaced by a method name.
