### ISSUE TITLE
Long time before error list populates

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn#49076]
Rero steps:
1. Clone https://github.com/GuOrg/Gu.Units/tree/fc83bc2a1fdab5b8cfd1bf1dfd37a0420f8ce493
2. Open visual studio
3. Rebuild and wait for warnings to show up.

I did not time it but it felt like over a minute.
I probably clicked rebuild out of habit even if it was a first build. Don't think it affects performance.
The project is pretty small and there were 862 warnings.

**Comment by CyrusNajmabadi** [comment]
@mavasani can you ptal?

**Comment by sharwell** [comment]
@JohanLarsson This is fixed in 16.9 Preview 1 or Preview 2. @mavasani can clarify exactly when this was implemented.

**Comment by mavasani** [comment]
Verified repros on 16.7 - error list update takes close to a minute after build complete
Verified no repro on 16.8 P6 - error list updated within few seconds of build complete
Verified no repro on 16.9 P2 (internal dogfood build) - error list updated immediately on build complete

**Comment by JohanLarsson** [comment]
This makes me very happy!

**Comment by mavasani** [comment]
Thanks @JohanLarsson - please let us know if you hit it again in 16.8 or later. We certainly want to improve the error list refresh experience, especially after build.

**Comment by JohanLarsson** [comment]
Another time snappy refresh is good is when fixing a warning. Full refresh is not needed then but nice if the warning goes away. Earlier today warnings were sticky so I closed Visual Studio and did git
