### ISSUE TITLE
No completion when using pattern matching on an enum

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#49072]
**Version Used**: Version 16.8.0 Preview 5.0

**Steps to Reproduce**:

Type a `.` at the `$$`:

```cs
namespace N
{
	enum RankedMusicians
	{
		BillyJoel,
		EveryoneElse
	}

	class C
	{
		void M(RankedMusicians m)
		{
			if (m is RankedMusicians.$$
		}
	}
}
```
**Expected Behavior**:
Completion for the enum pops up

**Actual Behavior**:
Nothin'

**Comment by davidwengier** [comment]
Nice try, bot.

**Comment by CyrusNajmabadi** [comment]
This would be in the CSharpTypeInferenceService if anyone wants to take a look.
