### ISSUE TITLE
"Add parameters to constructor" refactoring doesn't work with expression-bodied constructor

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#49112]
**Version Used**:  VS 2019 Version 16.8.0 Preview 6.0

Consider the following code:

```c#
class C
{
    int x;
    int y;

    public C(int x) => this.x = x;
}
```

If I select the "Add parameters to 'C(int)'" refactoring on `y`, it produces the following code:

```c#
class C
{
    int x;
    int y;

    public C(int x, int y) => this.x = x;
}
```

Notice that this does not actually assign the value of the introduced parameter `y` to the field `y`. I think it should do that, by turning the expression body of the constructor into a statement body.

If the constructor has a statement body, the refactoring works fine. I.e. it turns this code:

```c#
class C
{
    int x;
    int y;

    public C(int x)
    {
        this.x = x;
    }
}
```

Into this code:

```c#
class C
{
    int x;
    int y;

    public C(int x, int y)
    {
        this.x = x;
        this.y = y;
    }
}
```

**Comment by Youssef1313** [comment]
I suspect this is a more general issue in CSharpCodeGenerationService (specifically AddStatementsToMemberDeclaration). Haven't debugged so not 100% sure. But commenting in case it's useful for someone when working on this.

**Comment by CyrusNajmabadi** [comment]
Or we can have it do a tuple assignment to preserve the expression body. There can also be a feature to group/ungroup these sorts of assignments

**Comment by svick** [comment]
@CyrusNajmabadi That's also an option, though it's not one I would personally prefer. Is there an `.editorconfig` setting for tuple assignment in constructors? If not, should there be? The refactoring could then choose what to do based on that setting.

**Comment by Youssef1313** [comment]
Even if we would go with preserving the expression body, I believe `CSharpCodeGenerationService` would still need the fix. Other codefixes may have the same sort of bug if they rely on `CSharpCodeGenerationService`.

**Comment by svick** [comment]
Curiously, if you do it the other way around, it works. E.g. if you have this code:

```c#
class C
{
    int x;

    public C(int x, int y) => this.x = x;
}
```

Then invoking "Create and assign field 'y'" produces:

```c#
class C
{
    int x;
    private readonly int y;

    public C(int x, int y)
    {
        this.x = x;
        this.y = y;
    }
}
```

I think the behavior of these two refactorings should be consistent.
