### ISSUE TITLE
NuGet packages still contain Apache 2.0 license

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#49119]
https://github.com/dotnet/roslyn/pull/41112 changed the license of Roslyn from Apache 2.0 to MIT.

However, NuGet packages contain a file called `ThirdPartyNotices.rtf` which states Roslyn is still licensed under Apache 2.0. This notice is incorrect as far as I can tell. This isn't something easily noticeable, but it *is* there.

For example, if you [manually download Microsoft.Net.Compilers.Toolset](https://www.nuget.org/api/v2/package/Microsoft.Net.Compilers.Toolset/3.8.0-5.final) and inspect its contents, you can see the Apache license:

![Screenshot of NuGet Package Explorer with ThirdPartyNotices.rtf opened showing the Apache license](https://user-images.githubusercontent.com/278957/97840262-53729100-1ca9-11eb-826c-58c4f5a2332b.png)

This file comes from [src/NuGet/ThirdPartyNotices.rtf](https://github.com/dotnet/roslyn/blob/a6f654bb03596c2c3392bb16f082cc1615fac425/src/NuGet/ThirdPartyNotices.rtf).

Fixing this should be as simple as updating that file. However I refrained from creating a PR since I would imagine lawyers wouldn't want third party contributors changing legal notices.

**Comment by JoeRobich** [comment]
@PathogenDavid Thanks for filing! This is fixed in our 3.8.0 release packages.

**Comment by PathogenDavid** [comment]
@JoeRobich No problem, thanks for getting things sorted!
