### ISSUE TITLE
Make `IWorkspaceStatusService.IsFullyLoadedAsync` synchronous

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#49114]
Follow up from https://github.com/dotnet/roslyn/pull/48215

This pattern is used in a couple of places to make checking if a solution is fully loaded easier:
https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Classification/SemanticClassificationUtilities.cs#L168-L174

Lets just formalize that pattern and make the property synchronous.

/cc @sharwell

**Comment by CyrusNajmabadi** [comment]
@sharwell can we do this now?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.  if we need to do this, please assign to a milestone.
