### ISSUE TITLE
Support metadata items in Ctrl+T in some way

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#49122]
This feature request is based on my workflow.

When writing application code, I often inspect the available API before consuming it. Currently it may be done by:
- Go to object explorer. The experience is not good, because it searches very slow, and doesn't have good interaction with text editor.
- Type the name somewhere in the code, get the completion from IntelliSense, then F12 to it. This creates temporary editing to my code.

The capacities I wanted from this feature:
- Go to the same representation of F12.
- Can be toggled on or off. The Ctrl+T panel already supports this.
- Can tell me difference across frameworks when multi-targeting.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and scale/complexity of feature.
