### ISSUE TITLE
Initialization in another file cannot be detected by nullability checking

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#49121]
**Version Used**: 
VS 16.8 Preview 6

**Steps to Reproduce**:

Type code
```csharp
// File 1
#nullable enable

public partial class C
{
    public static readonly int[] List;
}
```
```csharp
// File 2
partial class C
{
    static C()
    {
        List = new[] { 3, 8, 1, 6, 5, 4, 7, 2, 9 };
    }
}
```

**Expected Behavior**:
Any usages for `List` don't bring compiler warning CS8618.

**Actual Behavior**:
CS8618 raised.

Screenshots:
![](https://ftp.bmp.ovh/imgs/2020/11/b52e10da080f914d.png)

![](https://ftp.bmp.ovh/imgs/2020/11/ce79c8ad075934cf.png)

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue. Unfortunately I cannot reproduce this behavior. I created a simple repro application, targeted `net5.0`, and build produced no warnings (as expected).
