### ISSUE TITLE
IDE classification for record constructor is wroing

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#49147]
**Version Used**: 
Visual Studio 16.8 Preview 6.0

**Steps to Reproduce**:

See the screenshot:
![image](https://user-images.githubusercontent.com/5644458/97937342-5fe60f00-1db9-11eb-9527-bdad41a125e3.png)

**Expected Behavior**:
Record constructor having the same color of record type definition.

**Actual Behavior**:
Having the color of struct definition.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/47960
