### ISSUE TITLE
NormalizeWhitespace ignores ObjectInitializerSyntax

### ISSUE THREAD

**Issue by jhgbrt** [dotnet/roslyn#49152]
When parsing a code fragment like this:

```
    var p = new MyClass { SomeProperty = "SomeValue" };
```
And subsequently formatting it using `NormalizeWhitespace`, I expected the output to be like this:
```
    var p = new MyClass 
    {
        SomeProperty = "SomeValue"
    };
```
Instead I got:
```
    var p = new MyClass{SomeProperty = "SomeValue"}
```
so all whitespace got removed.

The unit test below demonstrates the issue. 

```
        [Fact]
        public void ObjectInitializerShouldBeProperlyFormatted()
        {
            var input = "var p = new MyClass { SomeProperty = \"SomeValue\" }";

            var result = CSharpSyntaxTree.ParseText(input)
                .GetRoot()
                .NormalizeWhitespace()
                .ToFullString();

            var expected = "var p = new MyClass\r\n" +
                "{\r\n" +
                "    SomeProperty = \"SomeValue\"\r\n" +
                "}";

            Assert.Equal(expected, result);
        }
```

**Version Used**: 
3.8.0-5.final

**Comment by CyrusNajmabadi** [comment]
I don't believe whitespace normalization has any special rules for collection/initializers.  The purpose is just to get the code parsable, with minimal opinion/complexity.  Not to fit any particular style like this.

**Comment by jhgbrt** [comment]
seems strange to me, since pretty much everything else is formatted according to a certain style...

**Comment by CyrusNajmabadi** [comment]
> seems strange to me, since pretty much everything else is formatted according to a that style...

I mean, that's true... by definition :)

In this case though, the style is just: "on one line" :)
