### ISSUE TITLE
Paramref completion has extra items and doesn't show automatically

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4917]
Copy/paste C#:

``` C#
class C
{
    /// <summary>
    /// 
    /// </summary>
    void M(int xyz) { }
}
```

On the blank doc comment line, type **&lt;paramref**, press **TAB**, and then type **x**.

**Expected**: Completion list should show, offering parameter names.
**Actual**: No completion list shown.

Now, hit Ctrl+j to show the full completion list.

**Expected**: Only parameter names, or things that could legally go there.
**Actual**: Parameter names show, but so do "see", "seealso", "!--", and "![CDATA["

**Comment by CyrusNajmabadi** [comment]
I get:

![image](https://user-images.githubusercontent.com/4564579/217119721-615b875a-45ae-4a09-9e59-ec3c25e08da4.png)

And:

![image](https://user-images.githubusercontent.com/4564579/217119758-433f4d60-d8a0-4a54-b1e3-ecd5e99196d4.png)


which seems correct here.
