### ISSUE TITLE
IDE: Intellisense - Press Tab to get out of closing quote/bracket

### ISSUE THREAD

**Issue by RandomEngy** [dotnet/roslyn#49172]
**Brief description:**

I'd like to be able to press <kbd>Tab</kbd> to get out of closing `"`, `)`, `]` and `}`. This is faster than moving my hands off of home row to hit the arrow keys, or hitting <kbd>Shift+"</kbd>, <kbd>Shift+)</kbd>, <kbd>Shift+]</kbd>, or <kbd>Shift+]</kbd> depending on which character I need to type over.

If I need to get past a few of them, it's easy to just hit <kbd>Tab</kbd> a few times. And I've never needed to actually insert a `Tab` in any of these cases.

[Resharper just implemented this feature](https://youtrack.jetbrains.com/issue/RSRP-213067), but a few years too late as I am no longer using it.

**Languages applicable:**

C#

**Example:**

If the cursor is |:
`var array = new SomeClass[this.SomeFunction(new SomeOther("text|"))];`

Pressing <kbd>Tab</kbd> once would move the cursor outside the closing `"`. Pressing again would move it outside the first `)`. Pressing it again would move it outside the second `)`. Pressing again would move outside the `]`.

**Comment by sharwell** [comment]
The IDE already supports <kbd>Tab</kbd> today for type-over in the scenarios listed above, but it's a rarely used feature that doesn't seem to provide significant value over other features that can make better use of the <kbd>Tab</kbd> key. Does it work to just type <kbd>;</kbd> or <kbd>Shift</kbd>+<kbd>Enter</kbd>?

**Comment by RandomEngy** [comment]
This is not about autocomplete. It's about moving the cursor. If you take a look at my example, you have the cursor at the end of a string, where there is no sensible autocomplete action to fire. If I press <kbd>Tab</kbd> there, it just inserts a tab into the editor. I would rather it move the cursor past one character to the right. If I press <kbd>;</kbd> it inserts a `;` into the string. If I press <kbd>Shift</kbd>+<kbd>Enter</kbd> it makes a newline and moves the cursor there.

The example I posted in my original post shows where it would be beneficial.

**Comment by sharwell** [comment]
If I type exactly the following:

`_ = ToString(ToString("`

Followed by <kbd>Tab</kbd>, <kbd>Tab</kbd>, <kbd>Tab</kbd>, I get the following code, with the caret position marked by `$$`:

```
_ = ToString(ToString(""))$$
```

**Comment by sharwell** [comment]
⚠️ Note that the use of <kbd>Tab</kbd> in this context is incompatible with proposal https://github.com/dotnet/roslyn/issues/12363#issuecomment-602865938. While a Visual Studio extension could implement full support for <kbd>Tab</kbd> in the above cases (even when not inside a brace matching session), users with that extension would have limited ability to use the upcoming features.

**Comment by RandomEngy** [comment]
Apologies! I didn't realize this had already been done. I had just tested by clicking to put the cursor there and pressing Tab. If I've been typing, it does indeed work.
