### ISSUE TITLE
Warning when there is a struct constructor with default parameters

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/roslyn#49180]
The following code compiles without any warnings or errors. The compiler correctly generates IL and uses `initobj` to initialize a struct, but there is a constructor with a default parameter. So it seems like it should be invoked:

```csharp
public class Program {
    public static void Main() => new TestStruct().Value.ToString();
}

public struct TestStruct
{
    public TestStruct(string value = "default") => Value = value;
    public string Value { get; }
}
```

```
    .method public hidebysig static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 21 (0x15)
        .maxstack 2
        .locals init (
            [0] valuetype TestStruct
        )

        IL_0000: ldloca.s 0
        IL_0002: dup
        IL_0003: initobj TestStruct
        IL_0009: call instance string TestStruct::get_Value()
        IL_000e: callvirt instance string [mscorlib]System.Object::ToString()
        IL_0013: pop
        IL_0014: ret
    } // end of method Program::Main
```

If the type is changed to be a `class`, then the constructor with the default parameter is invoked:

```csharp
public class TestStruct
{
    public TestStruct(string value = "default") => Value = value;
    public string Value { get; }
}
```

```
    .method public hidebysig static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 22 (0x16)
        .maxstack 8

        IL_0000: ldstr "default"
        IL_0005: newobj instance void TestStruct::.ctor(string)
        IL_000a: call instance string TestStruct::get_Value()
        IL_000f: callvirt instance string [mscorlib]System.Object::ToString()
        IL_0014: pop
        IL_0015: ret
    } // end of method Program::Main
```

Makes sense to generate a warning or even an error to remove inconsistency between class and structure instantiations.

**Comment by sharwell** [comment]
The `struct` has two constructors:

```csharp
public struct TestStruct
{
    public TestStruct() { } // this one generated by the compiler
    public TestStruct(string value = "default") => Value = value;
    public string Value { get; }
}
```

A class with the same two constructors will be constructed in the same way as the structure.

**Comment by canton7** [comment]
I suppose it might make sense to raise a warning if:

1. There is an (explicit or implicit) parameteress constructor, and
2. There's another constructor, which has a single parameter, which has a default value

In this case, I think the default value is pointless and might indicate user error.

**Comment by jaredpar** [comment]
Closing as the compiler is operating as the language design intends here and that this seems like an unlikely candidate for a warning wave.
