### ISSUE TITLE
SyntaxGenerator.MethodDeclaration should support generating abstract/extern methods

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49192]
The `SyntaxGenerator.MethodDeclaration` method *always* produces a statement block for the method, even when `null` is passed in. This makes it impossible to generate `abstract` or `extern` methods where a method block would be invalid C# syntax.

**Comment by CyrusNajmabadi** [comment]
Would def take a PR on this.

**Comment by Youssef1313** [comment]
@AArnott I think you may cast the result `SyntaxNode` to `MethodDeclarationSyntax` and call `WithSemicolonToken` on that.

Otherwise that would be a breaking change on this public API.

**Comment by AArnott** [comment]
Yes, I used the workaround @Youssef1313 said for a couple missing features in the `SyntaxGenerator`. 
I think this can be done without a breaking change through an overload, or introduction of a sentinel BlockSyntax instance that signifies "no block".

**Comment by CyrusNajmabadi** [comment]
I would just consider this a bug in SyntaxGenerator.  Abstract members should not generate bodies (esp. if passed 'null' as the body). :)

**Comment by Youssef1313** [comment]
@AArnott I was recently looking into SyntaxGenerator bugs and taking a look at this one now. But.. it seems the behavior is already correct (for abstract) for tooo long, and is tested here

https://github.com/dotnet/roslyn/blob/46119cbbf9f39b7b70b82106a59d0ad80aae674a/src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs#L826-L828

There might be a bug with extern, but I'd like to know how did you see a bad behavior for abstract.

**Comment by AArnott** [comment]
I'm afraid it's too long ago for me to remember details. Thanks for looking into this.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Got any idea how this can happen?

**Comment by Youssef1313** [comment]
@kinkeadian25 You might be interested in this one. I can't find a scenario where it fails for `abstract`, but it seems we can at least fix it for `extern`.

**Comment by CyrusNajmabadi** [comment]
CLosing out due to lack of movement and response.
