### ISSUE TITLE
Public Roslyn CI asks me to log in

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#49190]
Certain pages on the public Roslyn CI asks me to log in. For example: https://dev.azure.com/dnceng/public/_build?definitionId=15&_a=summary  I can still see the page, but I can't interact with it due to the login prompt. Attempting to dismiss the prompt redirects me to a page either indicating I'm not authorized or asking me to log in with my Microsoft corporate account.

![image](https://user-images.githubusercontent.com/278957/98243073-0ace0880-1f33-11eb-89ee-9f2e5c321adb.png)

![image](https://user-images.githubusercontent.com/278957/98243338-64cece00-1f33-11eb-812a-b2ddd0ffba48.png)

Here's that diagnostic info in case it helps debug things:

```
11/5/2020 12:48:51 PM (UTC)
47c1e37f-2b1a-444d-8a43-246308b45ff5
```

The offending request appears to be some Azure DevOps API request to `https://dev.azure.com/dnceng/_apis/Settings/Entries/me/pipelines/runs/insights/15`

This password prompt makes it so third parties realistically can't navigate to the results of individual builds from the Azure DevOps interface.

**Comment by PathogenDavid** [comment]
Perhaps related, the status badges in the readme are currently all broken too:

![image](https://user-images.githubusercontent.com/278957/98244196-a613ad80-1f34-11eb-9922-93e78e0c8df5.png)

**Comment by RikkiGibson** [comment]
Do you know if this behavior started recently?

**Comment by PathogenDavid** [comment]
The status badges started pretty recently (like within the last week), but I never reported it when I initially noticed it because I figured it was some temporary service outage or something. (Although I have the same password issue on the runtime repo and its status badge is fine, so these are probably unrelated.)

------------

I'm pretty sure the password issue is pretty recent too, but I can't really think of the last time I tried to browse the list of runs so it's hard to say. (I do think I would've reported it if it had happened in that specific case. I do know it's worked in the past.)

It's also worth noting that I can't view the pipeline associated with a run. (IE: The button in the screenshot below.)

![image](https://user-images.githubusercontent.com/278957/98341566-a5caef00-1fd4-11eb-88bf-2ace49b4678e.png)

At first I thought maybe this was because this button was taking me to the pipeline editor (based on the URL: `https://dnceng.visualstudio.com/public/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=686&branch=master`) but when you're on a DevOps setup where you have contributor access it explicitly changes to "Edit Pipeline" so I think it's supposed to work:

![image](https://user-images.githubusercontent.com/278957/98341850-20940a00-1fd5-11eb-98f3-1dfc7cfac6f7.png)

---------

After some investigation, I've found that both of these password prompts are also happening on my pretty basic Azure DevOps test project. So I'm inclined to think this is probably actually an Azure DevOps problem rather than a permissions issue with the dnceng public project.

(If you want to witness the issues yourself, [go here](https://dev.azure.com/PathogenPlayground/AzureDevOpsTest/_build/results?buildId=1&view=results) and try viewing the runs list or the pipeline definition.)

**Comment by PathogenDavid** [comment]
Another permissions quirk I noticed, all of the avatars in the pipelines view are broken:

![image](https://user-images.githubusercontent.com/278957/98343174-0f4bfd00-1fd7-11eb-8b94-c8bb179332c6.png)

Poking at them with the browser dev tools reveals it's trying to get me to authenticate for them too. Obviously that one isn't important at all, but maybe it gives a hint to what permission is messed up. (Whether it's messed up by dnceng or Azure DevOps.)

**Comment by PathogenDavid** [comment]
It seems that with the minor exception of the view pipeline button, all of the above issues were fixed at some point in the past few months, so I'm going to close this issue.

@JoeRobich If you had something additional you wanted to investigate relating to this feel free to reopen.

(And if you did something to fix it and forgot to mention it then thanks a lot for fixing it! 💜)
