### ISSUE TITLE
Partial records miss their names in 'Find all references' window

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#49206]
**Version Used**: 
VS 16.8 Preview 6

**Steps to Reproduce**:

1. Type code
```csharp
// File 1
public partial record R(int A, double B, float C);
```
```csharp
// File 2
partial record R
{
     public void Deconstruct(out int a, out double b) => (a, b) = (A, B);
}
```

2. Click name `R`, and press F12 (or choose 'Find all references').

**Expected Behavior**:
The name will be displayed well.

**Actual Behavior**:
Actually, two references is shown below:
* `public partial record R(int A, double B, float C)`
* `partial record`
The second one misses the name `R`.

**Screenshots:**
![](https://ftp.bmp.ovh/imgs/2020/11/025f62383bfad06d.png)

**Comment by Youssef1313** [comment]
@allisonchou Did your PR #47960 handle this?

**Comment by JoeRobich** [comment]
This is fixed in master with Allison's PR
![image](https://user-images.githubusercontent.com/611219/98405370-041dbf00-2021-11eb-97ff-f11adaa3907a.png)

**Comment by SunnieShine** [comment]
@JoeRobich Thank you. Should I close this issue?

**Comment by CyrusNajmabadi** [comment]
Yup.  Closing.  Thanks for the report!
