### ISSUE TITLE
Offer 'ToDictionary' instead of inserting explicit cast

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49208]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-suggested-solutions-are-no/1244596?preview=true)._

---
[severity:It's more difficult to complete my work]
The problem:

If I were to have this Dictionary code in a Windows forms app

__Dictionary< byte, int > _byInDic = new Dictionary< byte, int >__

...

__byInDic = _byInDic.OrderBy( kvp1 => kvp1. Key );__

Intellisense provides an error message about implicit type conversion unavailability and provides a suggested solution as follows:

__byInDic = ( Dictionary< byte, int > )_byInDic.OrderBy( kvp1 => kvp1. Key );__

_**THIS DOES NOT WORK AND WILL THROW AN EXCEPTION.**_
Given that the IDE is well aware this does not work and has a **detailed** error message for this issue, because the correct format is

_ _byInDic = _byInDic.OrderBy( kvp1 => kvp1. Key ). ToDictionary( kvp => kvp. Key, kvp => kvp. Value );__

**Why do you suggest solutions you _KNOW_ do not work through intellisense?**
How is that helpful? You would save substantial amounts of time on both your own end and the end of developers using your IDE if, instead of suggesting solutions that are not solutions, you instead suggested ACTUAL solutions...

The solution : 

Don't fight errors with errors

---
#### Feedback Bot on 11/4/2020, 10:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as not likely to invest here.
