### ISSUE TITLE
Renaming C# in Codespaces does not apply to impacted Razor files closed or open.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#49216]
**Version Used**: 
![image](https://user-images.githubusercontent.com/2008729/98417228-6bde0500-2035-11eb-9fdb-1639ddf93134.png)

**Steps to Reproduce**:

1. Create codespaces for https://github.com/NTaylorMullen/ASPNETProjects.git
2. Open BlazorServer/Data/WeatherForecast.cs
3. Rename the property `TemperatureC` -> `TemperatureCelsius`

**Expected Behavior**:
FetchData.razor has its `TemperatureC` reference updated.

**Actual Behavior**:
FetchData.razor is untouched.

/cc @dibarbet 

**Note**: Doesn't matter if the file is open or not. If the rename originates from Razor everything applies correctly.

**Comment by dibarbet** [comment]
@NTaylorMullen looks like somewhere the mapping is going wrong as we're returning the generated file
```json
{
        "textDocument": {
          "uri": "file:///C:/Users/dabarbet/AppData/Local/Temp/ED5980A9A78ED9CE7B56F28C521D28B0F2B8/2/ASPNETProjects/BlazorServer/Pages/FetchData.razor.g.cs"
        },
        "edits": [
          {
            "range": {
              "start": {
                "line": 161,
                "character": 34
              },
              "end": {
                "line": 161,
                "character": 46
              }
            },
            "newText": "TemperatureCel"
          }
        ]
}
```

Looking some more to figure out why the mapping isn't happening
