### ISSUE TITLE
Proposal: Allow attributes on lambda expression and its parameters

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#4921]
Since lambda expressions are implemented as regular methods, I don't see why there is no support for attributes on them like

```
Foo.Bar([MethodAttribute]([ParameterAttribute]IBaz x) => ...);
```

which would be useful in case of fluent APIs.

**Comment by svick** [comment]
Do you have a specific situation where this would be useful?

**Comment by alrz** [comment]
@svick in fluent APIs which help with readability and conciseness of the code, this inability would be a annoying limitation. for example, in a mocking library you may want to have additional attributes to the mocked methods "on the fly". also, in a fluent API e.g. for model creation -a project that I've been working on- you may want to add additional metadata on lambda parameters which really helps the readability and simplicity of the final code.

**Comment by bkoelman** [comment]
I would welcome this very much as well, because it enables better support for [nullability annotations](https://www.jetbrains.com/resharper/help/Code_Analysis__Code_Annotations.html).

**Comment by gafter** [comment]
@stephentoub Please move this to the csharplang repo if you still want it to be considered championed by you.

**Comment by stephentoub** [comment]
Will do

**Comment by stephentoub** [comment]
@gafter, I've submitted a proposal in the csharplang repo here:
https://github.com/dotnet/csharplang/pull/375
