### ISSUE TITLE
Recursive property pattern allows reference to same property multiple times.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#49210]
Example:

```c#
void M(string s)
{
    if (s is { Length: 0, Length: var v })
    {
    }
}
```

This honestly feels strange to me and potentially a bug oversight.  If a bug/oversight, not sure if it can be fixed due to the breaking chnage.  However, we should def look into this to determine if this is intentional/desirable and at least doc appropriately.

**Comment by jaredpar** [comment]
This just feels like a natural, albeit quirky, fallout of the property pattern feature. The specification makes no mention of properties only being matched once. It just says they are matched in an undefined order and if any return `false` then the expression returns false. 

> At runtime, the expression is tested against T. If this fails then the property pattern match fails and the result is false. If it succeeds, then each property_subpattern field or property is read and its value matched against its corresponding pattern. The result of the whole match is false only if the result of any of these is false. The order in which subpatterns are matched is not specified, and a failed match may not match all subpatterns at runtime. If the match succeeds and the simple_designation of the property_pattern is a single_variable_designation, it defines a variable of type T that is assigned the matched value.

Quick experimentation shows that all of the behaviors I would expect here are actually happening 

```c#
// Error no string can match this
if (s is { Length: 0, Length: 5 }) { 

}

// Generates the appropriate check
if (s is { Length: > 0, Length: < 42} ) {
  ...
}
```

Not sure there is much to doc here unless we want to change the spec to explicitly state that duplicate property matches are legal.
