### ISSUE TITLE
Incorrect namespace in Features core layer

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#49239]
- [x] `https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/Core/Portable/ConvertAnonymousTypeToClass/AbstractConvertAnonymousTypeToClassCodeRefactoringProvider.cs#L27` (Done)

    This is the language-agnostic layer, namespaces shouldn't contain "CSharp" or "VisualBasic".

    Noted that while looking at the VB-specific code.

- [x] `https://github.com/dotnet/roslyn/blob/03c34759fc1cbb1771967f27a7e25d79cece69af/src/Features/VisualBasic/Portable/ConvertAnonymousTypeToClass/VisualBasicConvertAnonymousTypeToClassCodeRefactoringProvider.vb#L8` (Done)

- [x] `https://github.com/dotnet/roslyn/blob/87bd913b9edb92dec0b2ec2f3bdac48b263610bb/src/Features/Core/Portable/Completion/Providers/AbstractPreprocessorCompletionProvider.cs#L15-L17` (Done)

- [ ] This one is very confusing:

    https://github.com/dotnet/roslyn/blob/39e53e1a9c15935e972782e630d57f912bd1e768/src/EditorFeatures/Core/Implementation/InlineRename/VisualBasicEditorInlineRenameService.cs#L11-L14

    - Namespace: `CSharp`
    - Implementation: `VisualBasic`
    -Layer: language-agnostic

**Comment by Rupeshkoushik** [comment]
hi ,I'm interested i this issue can you suggest me ways to get started

**Comment by Youssef1313** [comment]
@Rupeshkoushik I think you only need to update the two lines referenced in the issue, in addition to adding a using statement for the new namespace name in https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs

**Comment by Youssef1313** [comment]
Also applies to:

https://github.com/dotnet/roslyn/blob/87bd913b9edb92dec0b2ec2f3bdac48b263610bb/src/Features/Core/Portable/Completion/Providers/AbstractPreprocessorCompletionProvider.cs#L15-L17

**Comment by CyrusNajmabadi** [comment]
VisualBasicEditorInlineRenameService  seems to be fine now.  Closing out.
