### ISSUE TITLE
`is null` check on `Span<T>` not supported

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#49230]
Very similar to: https://github.com/dotnet/corefx/pull/25257

The following code will not compile. If I use `== null`, it will compile.

```csharp
public void SendData(Span<byte> data)
{
    if (data is null)
    {
        throw new ArgumentNullException($"{nameof(data)} cannot be null");
    }
}
```

Error:

```console
D:\git\iot\src\devices\Ssd1351\Ssd1351.cs(239,25): error CS0150: A constant value is expected [D:\git\iot\src\devices\Ssd1351\Ssd1351.csproj]
```

**Comment by CyrusNajmabadi** [comment]
I would think this would be by-design. Span is a value type. So it can't ever be tested against null in a pattern.  It does, however overload operator== , so you can do the rest using that form. 

Can you clarify why you think this would work?  If we believe it would be good to support this, it could always be done through a language change request.

**Comment by richlander** [comment]
I agree. It's more a question on the scenarios where we expect `is` and `==` to be legal alternatives, and how these fundamental patterns (like checking for initialized data) applies to value types. In fact, I was a little surprised to see this null check for the exact reason you say -- `Span<T>` is a value type and cannot be boxed.

**Comment by CyrusNajmabadi** [comment]
> In fact, I was a little surprised to see this null check for the exact reason you say -- Span<T> is a value type and cannot be boxed.

It can't be boxed but you're also running into some interesting corners of the language.  The problem stems from the fact that `Span<T>` defines this operator:

```c
public static implicit operator Span<T>(T[]? array)
```

So, when you write:  `if (mySpan == null)`.   What is actually happening with that null is that it is being converted to a Span through that implicit operator.  In other words:  `if (mySpan == Span<T>.ImplicitCreate(null))`.  This, then reduces to: `if (Span<T>.EqualsEquals(mySpan, Span<T>.ImplicitCreate(null)))`

This would happen with any value type that has these types of operators/conversions.  There's nothing really special about Span here.  As above not supporting `is` is by-design.  And supporting `==` doesn't come through the language, but through the conversions that Span<T> itself exposes.

**Comment by richlander** [comment]
Makes sense. Thanks for the taking the time to explain. Feel free to close.

**Comment by CyrusNajmabadi** [comment]
sounds good.
