### ISSUE TITLE
SDK Analyzers Configuration Enhancements

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#49250]
- [x] **MSBuild based configuration**: Enable end users to easily enable/disable different well-known and recommended SDK analyzer buckets based on their preferences via MSBuild properties which can be changed on MSBuild/compiler command line. This feature would need to be baked into the SDK.

- [x] **Hybrid configuration**: Ship the underlying well-known and recommended configuration files that are used for 1. within the SDK. End users would enable analyzer buckets with MSBuild properties defined in 1. above + use their repo specific editorconfig/ruleset files to override specific values as required. Configuration file checked into the repo would not have an entry for every single rule, but builds on top of well-known files shipped in the SDK.

- [ ] **Fully non-MSBuild based configuration**: Allow users to easily fetch the well-known and recommended configuration files locally, editing them as required and check these into the repo. The configuration is much more explicit as the repo has a configuration file with an entry for every single rule.

- [x] **Support fully external configuration workflow**: Create an option for users who want to enable analyzers only in CI via GitHub actions. Relates to https://github.com/dotnet/roslyn/issues/48147. The external configuration files, such as yaml files used by a github action, would use the above SDK configuration features to enable right set of analyzer buckets.

**Comment by huoyaoyuan** [comment]
Repost my comment from https://github.com/dotnet/roslyn-analyzers/issues/4400#issuecomment-721083663 :

Tried to use globalconfig, and I'm getting the following diagnostics:
Since I've set `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`, it complains about duplicated severity items in `.globalconfig` and SDK provided `AnalysisLevel_5_AllEnabledByDefault.editorconfig`. This doesn't happen with `.editorconfig`, where local defined value gets preferred.

**Comment by mavasani** [comment]
@huoyaoyuan Thanks. Your scenario can be addressed when @chsienki implements https://github.com/dotnet/roslyn/issues/48634 as we need to differentiate between SDK provided global config and user provided global config and prefer the latter.

**Comment by mavasani** [comment]
## Proposal

### MSBuild based configuration enhancements

> **MSBuild based configuration**: Enable end users to easily enable/disable different well-known and recommended SDK analyzer buckets based on their preferences via MSBuild properties which can be changed on MSBuild/compiler command line. This feature would need to be baked into the SDK.

1. **Enhance [AnalysisMode](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysismode) MSBuild property to add more configuration knobs** 
   - Current values for this property:

   | Value | Meaning |
   |-|-|
   | `Default` | Default mode, where certain rules are enabled as build warnings, certain rules are enabled as Visual Studio IDE suggestions, and the remainder are disabled. |
   | `AllEnabledByDefault` | Aggressive or opt-out mode, where all rules are enabled by default as build warnings. You can selectively [opt out](../../fundamentals/code-analysis/configuration-options.md) of individual rules to disable them. |
   | `AllDisabledByDefault` | Conservative or opt-in mode, where all rules are disabled by default. You can selectively [opt into](../../fundamentals/code-analysis/configuration-options.md) individual rules to enable them. |

   - Additional new values proposed for this property:

   | Value | Meaning |
   |-|-|
   | `MinimumRecommended` | More aggressive mode than the `Default` mode, where certain additional recommended rules (which are Visual Studio IDE suggestions by default) are also enabled as build warnings. |
   | `Recommended` | More aggressive mode than the `MinimumRecommended` mode, where certain additional recommended rules (which are Visual Studio IDE refactorings/silent by default) are also enabled as build warnings. |

   Users will get intellisense while editing MSBuild project files for new property values:
![image](https://user-images.githubusercontent.com/10605811/99856655-49241400-2b3e-11eb-89f0-483f23c3af55.png)

2. **Add new category specific `AnalysisModeXXX` MSBuild properties, such as `AnalysisModeSecurity`, `AnalysisModePerformance`, etc.** Each of these properties can take the same 5 property values and semantics as `AnalysisMode` property above, so users can customize each category set separately.
   - These properties will override the `AnalysisMode` setting for each category.
   - Categories for which the corresponding `AnalysisModeXXX` property is not set default to `AnalysisMode` property value.
   - Users will get intellisense while editing MSBuild project files for new properties: 
![image](https://user-images.githubusercontent.com/10605811/99856553-0cf0b380-2b3e-11eb-9910-a3e4cd6d7312.png)

   For example, users can set security rules to `AllEnabledByDefault`, performance rules to `Recommended`, globalization rules to `AllDisabledByDefault` and rest of the rules to `MinumumRecommended` by setting the `AnalysisMode` property to `MinumumRecommended`.

### Non-MSBuild based configuration support

> **Fully non-MSBuild based configuration**: Allow users to easily fetch the well-known and recommended configuration files locally, editing them as required and check these into the repo. The configuration is much more explicit as the repo has a configuration file with an entry for every single rule.

The above SDK MSBuild properties and their values will be implemented via generating and embedding different well-known and recommended [configuration files](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files) into the SDK.
   - Users that prefer explicit configuration files checked into their repo can copy over these configuration files with an entry per-rule directly to the root of their repo and edit/maintain as appropriate.
   - Additionally, if required, we can consider publishing these SDK embedded configuration file to a specific directory on roslyn-analyzers repo OR on a separate repo, as appropriate. However, I hope this is not required as we will be shipping this within the SDK itself, and would be easily accessible to users.

**Comment by jmarolf** [comment]
I guess I don't get what problem this is trying to solve. What can users not do today that they need this for?

**Comment by mavasani** [comment]
> What can users not do today that they need this for?

There is no easy way to enable recommended set of analyzers for external customers. The analyzers enabled by default in the SDK are an extremely conservative set which have lot of restrictions and hard requirements and very API centric correctness analyzers that are most critical for .NET runtime team. For example, there are no security or performance analyzers enabled by default and likely we will have none of those enabled by default in future either. Now if a customer wants a simple switch, toggle or build pipeline task to enable say all recommended security analyzers or performance analyzers, we have no public way to do so. Internally, the security C&E have a security analyzers build task that teams can add to their Azure build pipelines and enable all recommended security analyzers, with potential customizations. We would like to have something very similar, but also enforceable from the SDK itself, not just a Azure build task or a Github action.

**Comment by jmarolf** [comment]
My question is mostly: do we need a new property? Couldn’t just add this functionality analysis levels so someone could put `<AnalysisLevel>preview-all</AnalysisLevel>` or some similar mechanism.

Effectively my proposal is to allow user to simply opt into categories in the analysis level property where the additional values are separated by a `-` character. 

Value | AnalysisLevel Syntax
-- | --
Default | `<AnalysisLevel>5</AnalysisLevel>`
MinumumRecommended | `<AnalysisLevel>5-minumum</AnalysisLevel>`
Recommended | `<AnalysisLevel>5-recommended</AnalysisLevel>`
AllEnabledByDefault | `<AnalysisLevel>5-all</AnalysisLevel>`
AllDisabledByDefault | `<AnalysisLevel>5-none</AnalysisLevel>`




| Value | Meaning
|-- | --|
|\<nothing specified>| Default mode where all CodeStyle analyzers are enabled as IDE only suggestions or refactorings. None of them are enabled as build warnings.
| -minumum | More aggressive mode than the Default mode, where certain IDE code style suggestions that are highly recommended for build enforcement (for example, file header analyzer) are enabled as build warnings.
| -recommended | More aggressive mode than the MinumumRecommended mode, where more IDE code style rules are as build warnings.
| -all| Aggressive or opt-out mode, where all CodeStyle rules are enabled by default as build warnings. You can selectively opt out of individual rules to disable them in IDE and/or build.
| -none | Conservative or opt-in mode, where all CodeStyle rules are disabled by default. You can selectively opt into individual rules to enable them in IDE and/or build.

Why I propose this: 
- We don't have to teach users yet another msbuild property
- the design is consistent (`AnalysisLevel` opts folks into a default set of warnings but editorconfig can override that)
- We already have a place where we can expose this property in the project property pages.


I also assume that we want to give ourselves the design flexibility to add more categories to these in the future?

**Comment by mavasani** [comment]
> My question is mostly: do we need a new property?

So, we already have the [AnalysisMode](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysismode) property that ships with .NET 5.0 SDK itself. I believe your suggestion is to deprecate that property and instead combine its existing and new values into AnalysisLevel property, which sounds fine to me. I do believe we still need new category specific properties, such as `AnalysisLevelSecurity`, `AnalysisLevelPerformance`, `AnalysisLevelStyle`, etc., so users can customize each category set differently. For example, I can very well see customers who want to bump up the analysis level to `5-all` for security, reliability and/or performance, but go easy on other categories like style with `5-minumum` and outright disable some categories like globalization with `5-none`.

**Comment by mavasani** [comment]
The only remaining open question for me is that we still need to extend the AnalysisLevel enhancement proposal to allow per-category configuration. I can see at least 2 approaches to do this:

1) Define new AnalysisLevelXXX property names, such as AnalysisLevelSecurity, AnalysisLevelPerformance, AnalysisLevelStyle, etc. so that user can configure per-category analysis level and/or rule enabling buckets using the exact same property values as AnalysisLevel.

```xml
<AnalysisLevel>5-minimum</AnalysisLevel>
<AnalysisLevelSecurity>latest-all</ AnalysisLevelSecurity >
<AnalysisLevelPerformance>preview-recommended</AnalysisLevelPerformance>
<AnalysisLevelGlobalization>5-none</AnalysisLevelGlobalization>
```

OR

2) Allow list of compound values for AnalysisLevel, with some well-known separator, say a semi-colon.

```xml
<AnalysisLevel>5-minimum; security=latest-all; performance=preview-recommended; globalization=5-none</AnalysisLevel>
```

I initially thought (1) might give a better end user experience as intellisense in MSBuild project file will list all the AnalysisLevel property names as a contiguous list. However, (2) might better suit our philosophy of using a single AnalysisLevel property to define the configuration buckets for enabled rules and the separated list syntax is not very difficult to read or remember + it also matches our existing property value format for properties such as NoWarn, WarningsAsErrors, etc. which takes a separated list. I am now slightly tending towards (2), but either is fine.

**Comment by mavasani** [comment]
## Update

We decided that for category-specific AnalysisLevel support we will go with option (1) mentioned in above comment https://github.com/dotnet/roslyn/issues/49250#issuecomment-738376719:

```xml
<AnalysisLevel>5-minimum</AnalysisLevel>
<AnalysisLevelSecurity>latest-all</ AnalysisLevelSecurity >
<AnalysisLevelPerformance>preview-recommended</AnalysisLevelPerformance>
<AnalysisLevelGlobalization>5-none</AnalysisLevelGlobalization>
```

**Comment by maxild** [comment]
Are there any links to recommended explicit config files (as mentioned last in https://github.com/dotnet/roslyn/issues/49250#issuecomment-731455224)?

**Comment by mavasani** [comment]
@maxild Yes, these are currently only part of the NuGet package - you can go into the `build\configs` directory of `Microsoft.CodeAnalysis.NetAnalyzers` NuGet package. Eventually, they will also be available in the SDK, but that will first happen with .NET 6.0 SDK.

**Comment by maxild** [comment]
Thanks. In `5.0.3` of `Microsoft.CodeAnalysis.NetAnalyzers` I see a a lot of *.editorconfig (actually global analyzer files; `is_global=true`) resources in the nupkg. 

Example:

```ini
# NOTE: Requires **VS2019 16.7** or later

# 'Design' Rules from '5.0' release with 'Recommended' analysis mode
# Description: 'Design' Rules with enabled-by-default state from '5.0' release with 'Recommended' analysis mode. Rules that are first released in a version later than '5.0' are disabled.

is_global = true

global_level = -1


# CA1000: Do not declare static members on generic types
dotnet_diagnostic.CA1000.severity = warning

# CA1001: Types that own disposable fields should be disposable
dotnet_diagnostic.CA1001.severity = warning

# etc........

```

I guess I can use those files as templates/examples of MS's perception of "best-practice profiles" when designing `.editorconfig` based (analyzer) configuration. Are there any recommended explicit rules planned for IDExxx code style rules (kind of like with `gofmt`) or is this feature only for CAxxxx code quality rules (I also verifies that `Microsoft.CodeAnalysis.CSharp.CodeStyle` doesn't seem to have embedded rulesets/globalconfig/editorconfig files)?

**Comment by mavasani** [comment]
> I guess I can use those files as templates/examples of MS's perception of "best-practice profiles" when designing .editorconfig based (analyzer) configuration.

That is correct

> Are there any recommended explicit rules planned for IDExxx code style rules (kind of like with gofmt) or is this feature only for CAxxxx code quality rules (I also verified that Microsoft.CodeAnalysis.CSharp.CodeStyle doesn't seem to have embedded rulesets/globalconfig/editorconfig files)?

Similar feature was added for CodeStyle packages very recently. Can you try the latest pre-release package?

**Comment by maxild** [comment]
I did download and inspect `microsoft.codeanalysis.csharp.codestyle.3.9.0-2.final.nupkg` from nuget.org. Do I need to access (if I can have access) to your CI feed?

**Comment by maxild** [comment]
@mavasani  After digging deeper on GH I found https://github.com/mavasani/roslyn/blob/master/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs in your fork

This seems like the data that drives the generation for IDExxxx rule config?

**Comment by mavasani** [comment]
@maxild Seems the package with this feature is not yet published on nuget. `3.9.0-3.final` should have it. You can also get the CI builds from this feed: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.CodeAnalysis.CSharp.CodeStyle&protocolType=NuGet

> This seems like the data that drives the generation for IDExxxx rule config?

That is correct.

> Will this also be configured via AnalysisMode/AnalysisLevel as decribed in #49250 (comment)?

Yes - the idea is for users to set these MSBuild properties and bulk enable bucket of rules as build warnings.

**Comment by maxild** [comment]
Should I be able to align 

`Default` 
`AllEnabledByDefault`
`AllDisabledByDefault`
`MinimumRecommended`
`Recommended`

with the C# enum values

`Never`
`WhenExplicitlyEnabled`
`Recommended`
`HighlyRecommended`

Or is build enforcement something different?

**Comment by maxild** [comment]
Perfect the latest prerelease you den had the config in the right spot :smile:

![Capture](https://user-images.githubusercontent.com/46108/104638986-2a0db280-56a7-11eb-8873-6fb64b55da04.PNG)

**Comment by mavasani** [comment]
@maxild Hopefully the below mapping shows how the EnforceOnBuildValues are aligned with AnalysisMode values: https://github.com/dotnet/roslyn/blob/d01860827df9d0e473b30767789407237fd4e877/src/CodeStyle/Tools/Program.cs#L160-L188

**Comment by maxild** [comment]
Then 'All', 'Default', 'Minimum', 'None', `Recommended` correspond to anyhing documented where?

**Comment by mavasani** [comment]
> Then 'All', 'Default', 'Minimum', 'None', Recommended correspond to anyhing documented where?

They will eventually be documented here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode

**Comment by maxild** [comment]
Ah `AnalysisMode` from the switch you send...Thanks

**Comment by maxild** [comment]
Is it correct that .net 5 sdk uses https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle/3.8.0 and .net6 sdk is moving and using the linked nuget from 'azure packages'?

**Comment by mavasani** [comment]
> Is it correct that .net 5 sdk uses https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle/3.8.0

Yes, that is correct.

> and .net6 sdk is moving and using the linked nuget from 'azure packages'?

We basically have periodic insertions from Roslyn repo to .NET SDK repo to insert newer CodeStyle packages into the SDK. @jmarolf can probably give more clarity on timelines and which version of CodeStyle package we can expect to ship with .net6 SDK

**Comment by maxild** [comment]
Yeah sometimes I wish I could figure more stuff out by only executing `dotnet --info` (compiler, msbuild, nuget etc versions). The SDK is a massive system. And sometimes I have to compare 5.0.102 to 16.8.4 etc....not easy. Anyway...

@mavasani I have one final question, that I asked you some days ago, on a closed issue. Let me see if I can find it (it's about global analyzer config files). But thanks for all your kind help. It has really help me solve some issues I had with understanding how to approach the setup of source code (static) analysis that work across all IDEs (vs2019, vscode, rider).

**Comment by maxild** [comment]
@mavasani https://github.com/dotnet/roslyn/issues/43051#issuecomment-758862927

**Comment by mavasani** [comment]
This is now complete.
