### ISSUE TITLE
Partial Method generate error

### ISSUE THREAD

**Issue by yika-aixi** [dotnet/roslyn#49266]
**Ver: Microsoft.CodeAnalysis.Analyzers.1.0.0-rc2**: 

![image](https://user-images.githubusercontent.com/22412994/98710002-15b6ec00-23be-11eb-9112-6cdde2ecd251.png)

```c#

void test()
{
    var workspace = new AdhocWorkspace();
    var generator = SyntaxGenerator.GetGenerator(workspace, LanguageNames.CSharp);

    actionMethod            = (MethodDeclarationSyntax) generator.MethodDeclaration(mName, modifiers: DeclarationModifiers.Partial);
    actionMethod = actionMethod.WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
}

```

**Comment by yika-aixi** [comment]
I temporarily used `SyntaxFactory.MethodDeclaration` to create a partial method
```c#
actionMethod = SyntaxFactory.MethodDeclaration(SyntaxFactory.ParseTypeName( "void"), mName);
actionMethod = actionMethod.WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
```

![image](https://user-images.githubusercontent.com/22412994/98714360-be1b7f00-23c3-11eb-8524-504f1ae35f9f.png)

**Comment by CyrusNajmabadi** [comment]
This is by design.  You first made a method-declaration.  By default you get one with a body like `void Foo() { }`.  You then added a semicolon to it.  So you get `void Foo() { } ;`.  If you want the body to be gone you need to call `WithBody(null)`.

**Comment by yika-aixi** [comment]
@CyrusNajmabadi Oh, thanks

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
