### ISSUE TITLE
Possible memory leak in Roslyn static analyzers

### ISSUE THREAD

**Issue by arturl** [dotnet/roslyn#49270]
**Version Used**: 

We're using Roslyn static analysis packages version 3.3.1:

Microsoft.CodeAnalysis.FxCopAnalyzers
Microsoft.NetFramework.Analyzers
Microsoft.CodeQuality.Analyzers
Microsoft.CodeAnalysis.VersionCheckAnalyzer

Also Microsoft.Internal.Analyzers version 2.6.9

C# compiler version 3.7.0-6.20459.4, Visual Studio 16.7.5

**Steps to Reproduce**:

We noticed that when the above assemblies are included memory consumption in VBCSCompiler goes up to 4GB after which the process crashes. The issue repros consistently but is a part of a big solution and I don't have a small self-contained repro case that I can share here. 

**What I'm looking for**:

- Confirm if this is a known issue, and if yes suggest any workarounds
- Details on what additional information I can provide to help you investigate. (Sample solution, crash dump etc.)

**Comment by sharwell** [comment]
Hi @arturl,

This type of issue needs to be tracked through our internal feedback system. Here are the steps for filing a report for this type of issue:

> Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.
>
> Based on the information provided so far, the most likely scenario to follow is for "Crashes". Please take a look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#crashes

Please feel free to mention me and/or link to this issue in your report, to ensure it gets routed straight to our team.
