### ISSUE TITLE
Pattern variable not assigned on false branch of `is not`

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#49272]
Consider this code:

```c#

M(new C());

void M(C c) {
  if (c is not C ci) return;
  System.Console.WriteLine(ci.ToString());
}

class C {}

```

This will throw a `NullReferenceException`. The issue appears to be that we are simply assigning `ci` on the wrong branch here.

**Comment by Youssef1313** [comment]
Is that a duplicate of #49262?

**Comment by jaredpar** [comment]
@Youssef1313 yes it's a dupe. Missed it cause I'm just looking at the "untriaged" label and it appears the label bot is down right now.
