### ISSUE TITLE
Cannot implement generic interface

### ISSUE THREAD

**Issue by RandalP** [dotnet/roslyn#49274]
**Version Used**: 
5.0.100

**Steps to Reproduce**:
I have previously reported a problem declaring a generic interface with a nullable enum in Visual Studio for Mac. https://developercommunity.visualstudio.com/content/problem/1152046/cs8627-enum-cannot-be-used-as-a-nullable-type-in-g.html

That issue was fixed, but it is not seem to be possible to create a class that implements the interface. The attached project demonstrates the bug.

[NullableEnum.zip](https://github.com/dotnet/roslyn/files/5520438/NullableEnum.zip)

e.g.

```
#nullable enable // Allow nullable reference types

namespace A
{    public interface IFieldWithEnum<T> where T : System.Enum
    {
        T? Value { get; }
    }

    public enum EnumType1
    {
        One,
        Two
    }

    public class FieldWithMetaEnum1A : IFieldWithEnum<EnumType1>
    {
        public EnumType1? Value { get; }
    }
}

```

1. run "dotnet build" for this project

**Expected Behavior**:
Compiles without error

**Actual Behavior**:

Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/randal/Projects/NullableEnum/NullableEnum.cs(23,44): error CS0738: 'FieldWithMetaEnum1B' does not implement interface member 'IFieldWithEnum<EnumType1>.Value'. 'FieldWithMetaEnum1B.Value' cannot implement 'IFieldWithEnum<EnumType1>.Value' because it does not have the matching return type of 'EnumType1'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]
/Users/randal/Projects/NullableEnum/NullableEnum.cs(34,44): error CS0738: 'FieldWithMetaEnum2B' does not implement interface member 'IFieldWithEnum<EnumType2>.Value'. 'FieldWithMetaEnum2B.Value' cannot implement 'IFieldWithEnum<EnumType2>.Value' because it does not have the matching return type of 'EnumType2'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]
/Users/randal/Projects/NullableEnum/NullableEnum.cs(16,40): error CS0738: 'FieldWithMetaEnum1A' does not implement interface member 'IFieldWithEnum<EnumType1>.Value'. 'FieldWithMetaEnum1A.Value' cannot implement 'IFieldWithEnum<EnumType1>.Value' because it does not have the matching return type of 'EnumType1'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]
/Users/randal/Projects/NullableEnum/NullableEnum.cs(52,40): error CS0738: 'FieldWithMetaEnum1C' does not implement interface member 'IFieldWithEnum<EnumType1>.Value'. 'FieldWithMetaEnum1C.Value' cannot implement 'IFieldWithEnum<EnumType1>.Value' because it does not have the matching return type of 'EnumType1'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]
/Users/randal/Projects/NullableEnum/NullableEnum.cs(62,40): error CS0738: 'FieldWithMetaEnum3C' does not implement interface member 'IFieldWithEnum<EnumType3>.Value'. 'FieldWithMetaEnum3C.Value' cannot implement 'IFieldWithEnum<EnumType3>.Value' because it does not have the matching return type of 'EnumType3'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]
/Users/randal/Projects/NullableEnum/NullableEnum.cs(57,40): error CS0738: 'FieldWithMetaEnum2C' does not implement interface member 'IFieldWithEnum<EnumType2>.Value'. 'FieldWithMetaEnum2C.Value' cannot implement 'IFieldWithEnum<EnumType2>.Value' because it does not have the matching return type of 'EnumType2'. [/Users/randal/Projects/NullableEnum/NullableEnum.csproj]

**Comment by jaredpar** [comment]
The interface here uses `T?` as the return. This is not constrained to be a value type as `System.Enum` is not a value type. This means it does not create a `Nullable<T>` but rather is a nullable annotation on a type parameter. When the actual `enum` value is used as the type parameter the annotation is dropped hence the correct implementation is

```c#
    public class FieldWithMetaEnum1A : IFieldWithEnum<EnumType1>
    {
        public EnumType1 Value { get; }
    }
```

If the intent here was to force the generic arguments to be `enum` values then you need to combine `struct` and the `System.Enum` constraint. At that point the existing interface implementation will compile. 

```c#
    public interface IFieldWithEnum<T> where T : struct, System.Enum
    {
        T? Value { get; }
    }
```
