### ISSUE TITLE
Cache Semantic Models

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#49289]
We should use the caching semantic model provider with a custom provider to ensure that generators asking for the same semantic model don't get different instances.

**Comment by CyrusNajmabadi** [comment]
> We should use the caching semantic model provider with a custom provider to ensure that generators asking for the same semantic model don't get different instances.

Could you clarify this a bit. There's nothing ensuring generators will process semantic models in the same order (or that different generators will even use the same semantic model).

We have to be careful to not hold onto semantic models 'just in case' someone will use it in the future.  We have experience attempting that in the past, and it goes *very* badly.  SemanticModels can use a *ton* of memory.  And the point of a SemanticModel is exactly to be the value that a *host* can choose to hold onto and release to ensure they are in control fo memory usage.

Any sort of cache needs to be something that isn't implicit.

--

Note: if we do want to cache based on semantic model, a better approach is likely to just have a callback based approach for generators where clients say what they care about, and then we grab the data and call into all the interested parties.
