### ISSUE TITLE
Publish Microsoft.CodeAnalysis* 3.8.0 on nuget.org

### ISSUE THREAD

**Issue by LeroyK** [dotnet/roslyn#49281]
Visual Studio 16.8 includes version 3.800.20.51918 of Microsoft.CodeAnalysis*. The latest version on nuget.org is 3.800.20.51507 (3.8.0-5.final), which is a pre-release version.

When will 3.8.0 be released on nuget.org?

**Comment by sergey-litvinov** [comment]
Yes please. any updates when the final package would be released?

**Comment by JoeRobich** [comment]
Packages will be published this week. We had been relying on a few prerelease .NET 5 packages which meant we were unable to publish release packages of our own. Now that .NET 5 is released we are updating those packages (https://github.com/dotnet/roslyn/pull/49265) and will be spinning a new build to publish release packages.

**Comment by JoeRobich** [comment]
Packages have been built and sent for vendor validation. We will publish once we hear everything is passing.

**Comment by JoeRobich** [comment]
Closing as packages have been published. Thanks for opening the issue @LeroyK
