### ISSUE TITLE
The reference and the reference count refers to the method name and not the method of the object

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49288]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The-reference-and-the-reference-count-re/1248955?preview=true)._

---
PLease refer to the screen shot
! [image.png] (https://aka.ms/dc/image?name=B7ed70c396d4c402d91e3298813e268f3637405786012071813_20201110-121536-image.png&tid=7ed70c396d4c402d91e3298813e268f3637405786012071813)
Clearly the reference EBSTypes should not be linked to the ToString() of the SyncMajorInfo object. It is sometime useful to see where this is used and the 'rename' should also impact only the variable of that object and not doing a blind text replace.

---
#### Feedback Bot on 11/10/2020, 00:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### C. Hannosset on 11/10/2020, 01:50 AM: 

<p>“The reference and the reference count refers to the method name and not the method of the object”<br>
Well obviously it does indeed, but reference count to the method name only and not the method of the object is not very helpful in some cases. This is then not a ‘bug’ but could this be shifted for an improvement? I am sure this will be welcomed.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I believe the rename behavior is already correct. The CodeLens references may benefit from limiting the coalescing to only include definitions from base and derived types, and filter references are statically known to not be resolvable to the current overload.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/51637.  CodeLens was updated as part of that as well.
