### ISSUE TITLE
Record operator parameter names are 'r1' and 'r2' rather than 'left' and 'right'

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#49300]
![image](https://user-images.githubusercontent.com/8040367/98877729-2b282680-244f-11eb-842f-4a5ee0d7969d.png)

According to https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-parameters#naming-operator-overload-parameters, the standard names are `left` and `right`. Roslyn IDE fixes currently generate operators with these names as well.

**Comment by RikkiGibson** [comment]
This feels like something that's easy to fix, and because labels can't be used for operator arguments, it's not a source breaking change.
