### ISSUE TITLE
No best type was found for the switch expression when null-coalescing operator is appended

### ISSUE THREAD

**Issue by ThomasMader** [dotnet/roslyn#49309]
**Version Used**: 

Master Branch
Latest commit 2f8aa1f by David Wengier:
Correctly use langword for this and base keywords (#49232)

**Steps to Reproduce**:

The following code produces "error CS8506: No best type was found for the switch expression." for the switch expression in the "incorrect" method because the compiler can't get the best type because it seems to be distracted by the null-coalescing operator added in that method compared to the version in the "correct" method.
To me this looks like a bug.

```
using System;

namespace ConsoleApp1
{
    interface IHandler { }
    public class BaseHandler { }
    public class MyHandler1: BaseHandler, IHandler { }
    public class MyHandler2: BaseHandler, IHandler { }

    class Program
    {
        private BaseHandler correct()
        {
            var key = "myhandler1";

            return key switch
            {
                "myhandler1" => new MyHandler1(),
                "myhandler2" => new MyHandler2(),
                "" => null,
                _ => throw new NotImplementedException()
            };
        }
        
        private BaseHandler incorrect()
        {
            var key = "myhandler1";

            return key switch
            {
                "myhandler1" => new MyHandler1(),
                "myhandler2" => new MyHandler2(),
                "" => null,
                _ => throw new NotImplementedException()
            } ??
            throw new NullReferenceException();
        }
        
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by alrz** [comment]
In order for that to work the operator `??` needs to be target-typed which is not (and won't be, the feature was explicitly considered and discarded).

I'd suggest capture the result in a variable and do it separately.
```cs
BaseHandler result = key switch {..};
return result ?? throw ...;
```
or just add `"" => throw ...;` instead of `"" => null` arm. from the code I think that would be the same.

**Comment by jaredpar** [comment]
Agree with @alrz that the compiler is behaving correctly here. Once the `switch` expression is embedded inside a `??` it is no longer subject to target typing.
