### ISSUE TITLE
LSP client sometimes fails to activate the C# language server with "The language server has not yet shutdown"

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#49301]
Error: The language server has not yet shutdown.

Stack:
["Roslyn.Utilities.Contract.Fail(String)","Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.AbstractInProcLanguageClient.ActivateAsync(CancellationToken)","Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()","Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()","System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)","System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)","Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__89.MoveNext()"]

It appears we're getting called for activation when there is already an active server running.

**Comment by dibarbet** [comment]
@davidwengier was this resolved by https://github.com/dotnet/roslyn/pull/49594

**Comment by davidwengier** [comment]
Yes, I would think so.
