### ISSUE TITLE
New line after with operator (records)

### ISSUE THREAD

**Issue by mdschweda** [dotnet/roslyn#49312]
**Version Used**: 

Visual Studio 16.8.0
.NET 5.0.100

🔗 Also reported as [AB#1276814](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1276814)

**Steps to Reproduce**:

1. Disable insertion of new lines before open braces. [`.editorconfig` generated by VS](https://github.com/dotnet/roslyn/files/5530636/default.editorconfig.txt)
2. Type `myRecord = myRecord with {`

**Expected Behavior**:

Curly brace stays on the same line

**Actual Behavior**:

Code gets formatted:

```csharp
myRecord = myRecord with
{
}
```

**Related issues**

#45780 #36913

**Comment by sharwell** [comment]
The expected behavior for this is defined by https://github.com/dotnet/roslyn/issues/36913#issuecomment-546015089

**Comment by Youssef1313** [comment]
@sharwell Does #49730 fixes this?

**Comment by Youssef1313** [comment]
Ping @sharwell to confirm if this can be closed.

**Comment by sharwell** [comment]
Fixed by #50274
