### ISSUE TITLE
Analyzer breakpoints are only hit in Initialize method, not in any of the registered actions

### ISSUE THREAD

**Issue by LeroyK** [dotnet/roslyn#49318]
**Version Used**: 
VS2019 16.8

**Steps to Reproduce**:
1. Create default Analyzer project
2. Debug VSIX project
3. Set breakpoints at ``Initialize()`` and ``AnalyzeSymbol()`` in the Analyzer
4. Open a project in the experimental VS instance

**Expected Behavior**:
All breakpoints should be hit, like it did in VS2019 16.7.x

**Actual Behavior**:
Only the breakpoint in ``Initialize()`` is hit, but none are hit in any of the registered analysis actions.

**Comment by JohanLarsson** [comment]
Did you solve this problem?

**Comment by LeroyK** [comment]
@JohanLarsson I thought I did, but I am currently only able to hit breakpoints in an analyzer if I also have a code fix provider for a supported diagnostic in that analyzer.

**Comment by sharwell** [comment]
This change is by design. For most debugging/testing purposes, we recommend writing a debugging tests using Microsoft.CodeAnalysis.Testing. If you need to debug inside Visual Studio, you'll need to turn off the 64-bit code analysis process to prevent the analyzer from running in a separate project where the debugger does not have visibility.

![image](https://user-images.githubusercontent.com/1408396/103227883-545c2380-48e4-11eb-86c3-a897226f9932.png)

**Comment by tiago-lqt** [comment]
This change totally breaks debugging experience for analyzers created with a new sample, in particular new developers experience and expectations.

Can this option be enabled by default on the Roslyn instance, or maybe with some flag on the VSIX debug project?

**Comment by CyrusNajmabadi** [comment]
> Can this option be enabled by default on the Roslyn instance,

I don't think so no.  As much as possible, we want the debugging experience to be debugging the true way that VS is behaving.  That means actually debugging the multi-process nature of it.  

> This change totally breaks debugging experience for analyzers created with a new sample

I strongly recommend going the path that Sam mentions.  It will be much much easier to debug and you'll get good tests out of it as well.  There's a *ton* going on in VS that this will help isolate you from.
