### ISSUE TITLE
Fade and offer to remove unnecessary casts in C# 9 target-typed conditional expressions

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#49317]
**Version Used**: 16.8.0

Tons of existing code today has an explicit cast on one or the other arm of a conditional expression to either the nullable value type or to a common base type. Right now there is no fix-all available for this, and it's not always possible to tell quickly by eyeballing the code whether the cast is still necessary in C# 9 in a given scenario. Please extend IDE1004 to be aware of the C# 9 feature.

`_` denotes a faded span.

```cs
class C
{
    int? M(bool cond)
    {
        //            ______ ℹ IDE0004 Type cast is redundant
        return cond ? (int?)null : 1;
    }
}
```

💡 Remove unnecessary cast:

```cs
class C
{
    int? M(bool cond)
    {
        return cond ? null : 1;
    }
}
```

**Comment by MaStr11** [comment]
This is already fixed in the latest master:
![image](https://user-images.githubusercontent.com/24472128/99084356-1f5f7000-25c7-11eb-9361-e28a748fcee8.png)

I think the relevant commit that added support was 9809f735c300e14f8351b062eb6df3f9f44331f5

**Comment by jnm2** [comment]
Thanks!
