### ISSUE TITLE
New Setting for pausing debugger to keep code screen from switching

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49321]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/896465/new-setting-for-pausing-debugger-to-keep-code-scre.html)._

---
<p>For this feature, let me explain the situation.  I have a C# WinForms program with two forms, the main form FrmMain and another form opened from FrmMain called FrmOther.</p> <p>Now lets say I have the C# WinForms program running that I am testing my code for FrmOther.  I see something is not right and I switch from the running program over to VS to look at the code for FrmOther to see why it is not behaving correctly.</p> <p>When I locate the problem and want to make an easy change to the code, I click on the pause button to pause debugging to make the change.  Except just when I begin to type VS switches me from the code for FrmOther to the code for FrmMain where execution was waiting for the user of the program to do something.  Fine, but very jarring and annoying.  I just want to do a quick change, now my mind is on closing the FrmMain code screen instead of making my easy change to FrmOther.</p> <p>I would like an Option in VS to not switch screens to the execution point when the pause button is pressed.  Keep the default functionality the same, unless the option is changed in the Options screen in VS.</p> <p>Thank you!</p> <p>Rob Mark</p>

---
#### Feedback Bot on 1/28/2020, 01:20 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Needs to be moved to debugger.

**Comment by jinujoseph** [comment]
The community feedback has been routed to debugger team
