### ISSUE TITLE
Clear empty lines.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49322]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Clear-empty-lines/1232159?preview=true)._

---
<p>I'd like a feature to clear excessive empty lines.</p> <p>Consider the following code:</p><pre>var items = new List&lt;Item&gt;();
 &lt;---Empty Line
for (int i=0; i&lt;10;i++)
{
 &lt;--- Empty Line 
 &lt;--- Empty Line
 &lt;--- Empty Line
    items. Add(new Item { Id = Guid.NewGuid() });
}
</pre><p>Clearing excessive lines would yield the following result:</p><pre>var items = new List&lt;Item&gt;();
 &lt;---Empty Line
for (int i=0; i&lt;10;i++)
{
    items. Add(new Item { Id = Guid.NewGuid() });
}
</pre>

---
#### Feedback Bot on 10/26/2020, 00:31 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by PhilParisot** [comment]
Any news on this?

**Comment by CyrusNajmabadi** [comment]
@PhilParisot the request is on the backlog.

**Comment by CyrusNajmabadi** [comment]
Handled by:

![Image](https://github.com/user-attachments/assets/e6f803a1-4b19-4984-900c-da5ee25eb272)
