### ISSUE TITLE
[LSP] In liveshare, the Razor C# throws on didOpen/didChange and immediately shuts down

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#49329]
In latest main (e.g. 30711.80 main) start a liveshare session on a c# only project (use the /Log parameter).  Join the liveshare session on the client and open a file.  Wait a bit and you should see a gold bar on the host with exception:
```
System.InvalidOperationException: The language server has not yet shutdown.   at Roslyn.Utilities.Contract.Fail(String message)   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.AbstractInProcLanguageClient.ActivateAsync(CancellationToken token)   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<OnRpcDisconnected>d__92.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```
for `Razor C# Language Server Client`.  

After digging in the logs, it looks like the razor c# language server client is being initialized, receives a didOpen/didChange, then immediately shutsdown with `An error occured processing a mutating request and the solution is in an invalid state. Check LSP client logs for any error information.`  The client then tries to initialize again which I believe leads to the gold bar
![image](https://user-images.githubusercontent.com/5749229/98993277-16956e00-24e3-11eb-9660-a48975098194.png)

However since didChange and didOpen are notifications, we do not have any logs with the exception.

These are the contents of the didChange and didOpen messages
didOpen:
```
{
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///C:/Users/dabarbet/source/repos/ConsoleApp6/ConsoleApp6/Class2.cs",
      "languageId": "CSharp",
      "version": 2,
      "text": "class C\r\n{\r\n    void M()\r\n    {\r\n        if (true)\r\n        {\r\n\r\n        }\r\n    }\r\n}\r\n\r\nclass B\r\n{\r\n    public void SOmething()\r\n    {\r\n\r\n    }\r\n\r\n    private int DO()\r\n    {\r\n        return 1\r\n    }\r\n}\r\n"
    }
  }
}
```

didChange:
```
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 3,
      "uri": "file:///C:/Users/dabarbet/source/repos/ConsoleApp6/ConsoleApp6/Class2.cs"
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 20,
            "character": 16
          },
          "end": {
            "line": 20,
            "character": 16
          }
        },
        "rangeLength": 0,
        "text": "2"
      }
    ]
  }
}
```

**Comment by dibarbet** [comment]
This may be the cause of https://github.com/dotnet/roslyn/issues/49301

**Comment by dibarbet** [comment]
FYI @davidwengier this looks like an error in text sync

**Comment by davidwengier** [comment]
This is failing a contract check in our `didChange` handler, in that the document is not present in the request context. Looks like the Razor client is sending didChange requests, even though the document is not a razor document. 

That `logMessage` in the screenshot above is the server shutting down after the `didChange`.

I don't _think_ this is us.

**Comment by davidwengier** [comment]
Looks like this is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1106064 which should now be solvable using a `RunOnContext` attribute, but that attribute isn't in any package we reference. I'm following up with the live share team.

**Comment by davidwengier** [comment]
This is blocked on https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/288066 being merged, and a package available.
