### ISSUE TITLE
Bug using "Fix all occurrences" preview dialog

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49358]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Bug-using-Fix-all-occurrences-preview-/1254653?preview=true)._

---
[severity:It's more difficult to complete my work]
When I choose to replace a series of multiple lines with explicit types by the "var" keyword, all lines shown as just 1 (concatenated) option in the dialog.

I cannot check or uncheck individual lines.

![image](https://user-images.githubusercontent.com/1408396/99104740-3cc81600-2596-11eb-9345-5620a7c1fc25.png)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @mikadumont @mavasani

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in the preview changes dialog.
