### ISSUE TITLE
CS8634: Unable to infer correct type

### ISSUE THREAD

**Issue by lellid** [dotnet/roslyn#49388]
Version: VS16.8.1

**Steps to Reproduce**:

Consider the following code:

```
#nullable enable
public class Foo
    {
        // At the end of this call, myChild is always not null
        static void ChildCopyToMemberOrCreateNew<T>([AllowNull][NotNull] ref T myChild, [AllowNull] T fromAnotherChild, Func<T> createNew) where T : class
        {
            if (fromAnotherChild is not null)
            {
                myChild = fromAnotherChild; 
            }
            else
            {
                myChild = createNew();
            }
        }

        private object _member;
        public Foo()
        {
            ChildCopyToMemberOrCreateNew(ref _member, null, () => new object());
        }
    }
```

**Expected Behavior**:

This code should compile without a warning (in fact it did compile without a warning up to .NET 5 Preview 7).

**Actual Behavior**:

The call to `ChildCopyToMemberOrCreateNew` has a warning CS8634: The type 'object?' cannot be used as type parameter 'T' ...

By forcing object as type argument:

 `ChildCopyToMemberOrCreateNew<object>(ref _member, null, () => new object());`

the warning disappears, however, my feeling is that 'object' should be automatically inferred by the compiler here.

**Comment by huoyaoyuan** [comment]
What happens if you change the nullable signatures to:
```csharp
private object? _member;
ChildCopyToMemberOrCreateNew<T>([NotNull] ref T? myChild, T? fromAnotherChild, Func<T> createNew);
```

**Comment by lellid** [comment]
Yes, with that, it works (and even works with `private object _member;`). Thank's!

**Comment by Joe4evr** [comment]
Please close if nothing is needed anymore.
