### ISSUE TITLE
Microsoft.CodeAnalysis.EditorFeatures.Text package references package versions not available on Nuget

### ISSUE THREAD

**Issue by gjeltema** [dotnet/roslyn#49398]
The [Microsoft.CodeAnalysis.EditorFeatures.Text](https://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures.Text/) package version 3.8.0 (latest version released 4 days ago) has dependencies on v.16.8.39 of the following packages:
 - Microsoft.VisualStudio.CoreUtility
 - Microsoft.VisualStudio.Text.Data
 - Microsoft.VisualStudio.Text.Logic

The latest available version for all 3 packages is 16.6.255, released 5 months ago.

Thus when attempting to update the Microsoft.VisualStudio.LanguageServices package to v.3.8.0 that has a dependency on this package, the update fails and is rolled back.

**Comment by gjeltema** [comment]
Update on this:

The 3 packages that Microsoft.CodeAnalysis.EditorFeatures.Text are dependent on that are causing this issue just had a new version uploaded less than a day ago, v16.8.239.  This is still a lower version than the v.16.8.39 that Microsoft.CodeAnalysis.EditorFeatures.Text requires, and so the issue still remains.

**Comment by JoeRobich** [comment]
@gjeltema Sorry about the delay in getting all the packages published. The v16.8.239 packages are a higher version than the needed v16.8.39 depenedencies and should satisfy NuGet and MSBuild. I tested locally and everything seemed to work for me. 

If you are still having issues and the Package Manager is giving you an error or warning, could you please share it with me?

**Comment by gjeltema** [comment]
@JoeRobich Yes it works just fine, though the NU1603 warnings due to the packages not having the exact version would be nice to be rid of, but it's not blocking me in any way.  Thanks for getting the updated packages out!

Also, despite having degrees in engineering and computer science, I've apparently forgotten how to do arithmetic and realize that 239 > 39, so my apologies for the my last comment being incorrect.

Thanks again!
