### ISSUE TITLE
Re-add support for "Surround generated code with #region" option

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4939]
We never implemented this option as part of Roslyn, because it was off by default, and we were waiting for a more full-fledged organization and style system.

We should consider bringing it back.

(From Send-A-Smile item, internal bug 1177667)

**Comment by nithinbandaru1** [comment]
Any update on this feature coming back??

Seems like a very important feature for me because my Interfaces are big and have been grouped based on certain similarities and that improves a lot of readability.

Also, can someone point out if there is an extension available that has this feature?

**Comment by CyrusNajmabadi** [comment]
Closing out as unplanned.
