### ISSUE TITLE
The ToString() implementation of record types throws StackOverflowException for two way reference

### ISSUE THREAD

**Issue by IustinMicu** [dotnet/roslyn#49396]
### Description

Calling the `ToString()` method on a `record` that has a two way reference with another record throws a `StackOverflowException`.

Example having a two way reference between `Person` and `Car` records:

```C#
public record Person(Guid Id, string Name, Car Car);
public record Car(string Id, Person Owner);

var person = new Person
{
    Id = Guid.NewGuid(),
    Name = "Iustin",
    Car = new Car()
};

person.Car.Owner = person;

// This throws StackOverflowException
Console.WriteLine(person.ToString());
```
This scenario is valid and using `classes` works fine in any .NET version, including in `.net5.0`.

### Configuration

.NET version: `.net 5.0`
OS: `Windows 10`
Architecture: `x64`

### Other information

This is a screenshot demonstrating the source code above, the exception being thrown and the Stack Trace:

![Record recursive reference](https://user-images.githubusercontent.com/22785067/99240764-a00baf80-2805-11eb-9db1-307d620eeb6d.png)

**Comment by CyrusNajmabadi** [comment]
As mentioned above, this is by design. If you have a recursive record, you'll have to decide how you want these functions to behave and implement them that way yourself :-)

**Comment by IustinMicu** [comment]
Ok this is the actual design, but can you please change or improve it?

Right now it doesn't seem like a good design.
I can't believe that nobody tested this before.. or that it was accepted this way. For example Entity Framework uses two way references a lot and this bug will have a big impact. The actual program will run but when the user will debug and inspect an object it will automatically call the `ToString()` method and will crush the process. A very nice experience! 😄 

Anyway, I don't know the builtins of records or classes so sorry if I propose something that's not appropriate but from a developer perspective this is what I suggest:

*1. Best solution:*
The `ToString()` implementation for records should behave the same as it does for classes. From the user's perspective there should be no difference.

If this is not possible, please let me know why. I am happy to learn more about it.

*2. An improvement to the actual design:*
The compiler should generate a warning when it detects a recursive record and let the user know that it must override the `ToString()` method.
Same way it says that a certain block of code becomes unreachable. So something between a warning and an error, because this is quite important and actually breaks the program at runtime.

I think this is very doable and it's way better than simply receiving a StackOverflowException that will never make someone think that they have to override the `ToString()` method. It will only lead people here, posting issues and seeking answers/fixes. 😆

**Comment by CyrusNajmabadi** [comment]
> I can't believe that nobody tested this before.. 

It was tested.  As specified, this is the intended behavior.

>  For example Entity Framework uses two way references a lot and this bug will have a big impact.

in that case, if you are using such records with EF, you should provide an appropriate impl here that handles this case.  Handling what should happen here is domain specific, so you'll need to decide what behavior is correct here.

> The ToString() implementation for records should behave the same as it does for classes. 

This would break existing code.  It cannot be done.

> but can you please change or improve it?

Changes to the language need to go through dotnet/csharplang.  Feel free to open a discussion there with a proposal on how you think this should work.

Thanks! :)

**Comment by IustinMicu** [comment]
Alright, Thanks. 👍 
I`ll go there, but what about the compiler warning?
Can that be done?

**Comment by CyrusNajmabadi** [comment]
> I`ll go there, but what about the compiler warning?

In general, no.  That would be a breaking change.  Consider all hte people who have 'warn as errors' on.  Their code would now fail to compile.

That said, you could def write an analyzer for your own code (or make a nuget that made it available for others).

**Comment by IustinMicu** [comment]
Ok, although I am sure anyone would be happier if their code doesn't compile until it's fixed rather than crashing at runtime 😉 
Thanks for your replies!

**Comment by IustinMicu** [comment]
Just want to add one more thing here for anyone that runs into the same issue and reaches here.

> **For now the best solution for cyclic data structures is to use classes.**

**Comment by CyrusNajmabadi** [comment]
> Just want to add one more thing here for anyone that runs into the same issue and reaches here.

This is not true.  Cyclic records are fine.  You just need to be explicit about how you want the cycle to be broken.  You could even deal with this with an attribute and have a source-generator emit the code you want here.

**Comment by CyrusNajmabadi** [comment]
> Ok, although I am sure anyone would be happier if their code doesn't compile until it's fixed

Understood. As i said above, this is what an analyzer can provide.

**Comment by kyanha** [comment]
Why does the generated code not have a "this object has been visited in this ToString() method" poisoned pill?

**Comment by CyrusNajmabadi** [comment]
> Why does the generated code not have a "this object has been visited in this ToString() method" poisoned pill?

1. it would be costly. 
2. how would that poison pill work?  if it was a reference identity check, that wouldn't work for struct records.  if it was a value check... well, how would you check value equality, without checking all the fields, which would lead to the same issue.
