### ISSUE TITLE
Visual Studio Suggests Logic Breaking Change

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49406]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-Suggests-Logic-Breaking-Ch/1256254?preview=true)._

---
Just updated my Visual Studio to Version 16.9.0 Preview 1.0.
In one of my apps it is making the following suggestion:
Severity	Code	Description	Project	File	Line	Suppression State
Message	IDE0059	Unnecessary assignment of a value to 'newWidth'

The problem is making that change would break the logic, as it is suggesting to remove a multiplication assignment, which doesn't make sense why it is suggesting it.
I have extracted just the part of my code that makes the unnecessary suggestion.

private static void Test(int width, int height)
        {
            float maxWidth = width;
            float maxHeight = height;
            float imageWidth = width;
            float imageHeight = height;
            float percentage = maxWidth / imageWidth;
            float newWidth = imageWidth * percentage;
            float newHeight = imageHeight * percentage;

if (newHeight > maxHeight)
            {
                percentage = maxHeight / newHeight;

newWidth *= percentage;
                newHeight *= percentage;
            }
        }

Attached is a screenshot of a simple app I created to reproduce the issue.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This seems to be by-design. The user is writing new values into a local variable, but then they're not reading those values.  So these writes are unnecessary and can be removed:

![Uploading image.png…]()
