### ISSUE TITLE
VB: Pretty listing no longer removes leading zeros

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4941]
1. Type a line like `Dim myInteger As Int32 = 0060`
2. Press Enter

_Expected_
Pretty listing should remove the leading 00.

**Comment by Giftednewt** [comment]
Looks like this is also broken for Hex and Oct values as well. I'd like to take a look into fixing this.

**Comment by Pilchie** [comment]
That would be great!  The [`ReduceTokensCodeCleanupProvider`](http://source.roslyn.io/Microsoft.CodeAnalysis.VisualBasic.Workspaces/R/3ba4b82d4fd8661e.html) is probably the place to start.

**Comment by Giftednewt** [comment]
@Pilchie Thanks for the heads up. PR coming your way

**Comment by dpen2000** [comment]
This issue should probably be closed now

**Comment by CyrusNajmabadi** [comment]
Closing out as fixed.
