### ISSUE TITLE
Incorrect CS8602 (Dereference of a possibly null reference) warning

### ISSUE THREAD

**Issue by CyberSinh** [dotnet/roslyn#49423]
**Version Used**: 
.NET 5.0 in Visual Studio 16.8.1

**Steps to Reproduce**:

```cs
public class Nullable
   {
      public Exception? Error { get; private set; }
      public bool IsSuccess => true;
      public bool IsFailure => Error != null;

      public string? Status
      {
         get
         {
            if (IsFailure) // if IsFailure == true, Error cannot be null !
               return Error.Message; // CS8602 on "Error"

            if (IsSuccess)
               return "OK";

            return null;
         }
      }

      public void Do()
      {
         object? progress = new object();
         bool canReportProgress = progress != null;
         if (canReportProgress)
            progress.GetHashCode(); // CS8602 on "progress", idem for local variable
      }
   }
```
The C# compiler doesn't seem to be smart enough to be aware of basic non null checking saved in variable or returned by a property.

**Expected Behavior**:
No CS8602 warning.

**Actual Behavior**:
CS8602 warnings (Dereference of a possibly null reference). I would like to avoid the ugly null-forgiveness (!) operator.

**Comment by huoyaoyuan** [comment]
You should mark `[MemberNotNull(nameof(Error))]` on `IsFailure`.

> The C# compiler doesn't seem to be smart enough to be aware of basic non null checking saved in variable or returned by a property.

This is intentional. Looking into other members can make the analysis excessive.

**Comment by CyberSinh** [comment]
Hi,

If I put the attribute on the `Error` member, I get another warning:

```cs
[MemberNotNull(nameof(Error))]
public bool IsFailure => Error != null; //CS8774: 'Error' must have null-null value
```

Concerning the storage of the non nullabilty in a local variable, does the only viable solution is to use the null-forgiveness operator?

Thanks.

**Comment by AmrAlSayed0** [comment]
```MemberNotNull``` is only applied when a method or property is _guaranteed_ to initialize the field or property ```Error``` like a method called ```EnsureErrorIsInitialized()```. If it only checks that the field or property is initialized then you have to use ```MemberNotNullWhen```.

**Comment by huoyaoyuan** [comment]
Yes. I mistyped it. It should be `[MemberNotNullWhen]`.

**Comment by CyberSinh** [comment]
Thanks !

The attribute `[MemberNotNullWhen]` works as expected.

```cs
[MemberNotNullWhen(true, nameof(Error))]
public bool IsFailure => Error != null;
```

Concerning the storage of the non nullabilty in a local variable, I understand I have no better option than using the null-forgiveness operator:

```cs
public void Do()
{
    object? progress = new object();
    bool canReportProgress = progress != null;
     if (canReportProgress)
        progress!.GetHashCode(); // use ! operator on 'progress'
}
```

**Comment by huoyaoyuan** [comment]
The pattern storing null check result into a boolean isn't suggested as I know.

Patterns I've seen:

Do the work inside an `if` block, or use `if (x == null) return;`.

Does the null check for every time. If the object is a local variable or parameter, doing null check will be super fast (nearly the same to reading from boolean).

**Comment by CyberSinh** [comment]
In my real code the `canReportProgress` is more than just null checking null eg.: 
`bool canReportProgress = progress != null && hasSomethingToReport;`
