### ISSUE TITLE
C# Interactive can't use Ctrl+.

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#49432]
**VS2019 16.8.1**
![image](https://user-images.githubusercontent.com/12094247/99359062-72983200-28e9-11eb-8a65-ba39f5280931.png)

in `16.6` (in my memory), it can use Ctrl+. to prompt add the namespace. the new version is disappointing.

**Comment by tmat** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/50476
