### ISSUE TITLE
VS2015 crashes when searching for class contained in Web Site project

### ISSUE THREAD

**Issue by tomasr** [dotnet/roslyn#4943]
__Scenario__: Searching for a type name in Solution Explorer in a large solution containing one Web Site project. If type specified is in the Web Site, Visual Studio 2015 will crash due to unhandled exception.

__Cause__: An ArgumentNullException is raised when attempting to construct a System.Uri object with a null argument:

``System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString, UriKind uriKind)```

This is invoked from GraphNodeIdCreation.GetIdForDocument():

```        
        public static GraphNodeId GetIdForDocument(Document document)
        {
            return
                GraphNodeId.GetNested(
                    GraphNodeId.GetPartial(CodeGraphNodeIdName.Assembly, new Uri(>>>document.Project.FilePath<<<, UriKind.RelativeOrAbsolute)),
                    GraphNodeId.GetPartial(CodeGraphNodeIdName.File, new Uri(document.FilePath, UriKind.RelativeOrAbsolute)));
        }
```

The exception happens because for this type, document.Project.FilePath will be null:

![image](https://cloud.githubusercontent.com/assets/16179/9622832/14b0f618-50fe-11e5-8349-402de853a625.png)

**Comment by tomasr** [comment]
Should mention I've got dumps of both the ArgumentNullException and the resulting AggregateException that causes the crash, if they are needed.

**Comment by Pilchie** [comment]
Isn't this the issue addressed by #4526?

**Comment by tomasr** [comment]
Description looks pretty similar. Searched for a corresponding issue but couldn't find it before, sorry!

Can't tell if the actual changes in there actually prevent the issue entirely.... wouldn't it result in the files being ignored for the search, or am I misreading what the change does?

**Comment by brettfo** [comment]
@Pilchie: Yes, this is the same issue.

@tomasr: You're correct in that PR #4526 ignores projects with a null `FilePath` from the search and that will prevent the crash by ensuring that such projects never get a progression node in the Solution Explorer which means we'll never call `GetIdForDocument()`.

**Comment by tomasr** [comment]
@brettfo Confused a bit.... are you saying your fix only prevents some UI stuff from happening, but the files are still actually searched, or are the files excluded from the search at all?

**Comment by brettfo** [comment]
Projects with a null `FilePath` (and the project's documents) aren't searched at all and this makes us consistent with VS2013.  I mention it in one of the comments to that PR but I don't know how to deep-link directly to the comment on GitHub.

**Comment by tomasr** [comment]
@brettfo I'm further confused then.... maybe I'm not getting how the whole thing works, but for what is worth, running the exact same search on the same solution that crashes VS2015, works fine *and* returns results in VS2013, including the files that are part of the "Web Site" project.

What am I missing? Is this related to the concept of "progression queries" (whatever that is?)

**Comment by Pilchie** [comment]
Where in the "Web Site" project?  In the .aspx, .aspx.cs, or files in App_Code?

**Comment by tomasr** [comment]
@Pilchie Both, actually....

**Comment by tomasr** [comment]
OK, so to be clear, this specific search only returns file names, rather than type names in VS2013, maybe that's where the confusion arises (which is strange, because it ignores types with that name even in regular class library projects).

**Comment by brettfo** [comment]
@tomasr I'm still a bit confused about the behavior you're seeing in VS2013 vs VS2015.  If you get the time could you create a sample solution and zip/email it to me at brettfo@microsoft.com?  Could you also give me an example of what you're searching for in the Solution Explorer?  It's kind of a big ask but I think it would make it easier for me to fix the discrepancy.  PR #4526 will fix the crash you've been seeing, but I want to make sure we preserve the same behavior, too.
