### ISSUE TITLE
Add metadata to copy inside the editor

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#49442]
When copying code from inside the editor, we should add metadata so that if the code is also pasted in the editor we can avoid recalculating things. The target of this feature is to reduce work that "add usings on paste" will have to do if we know what usings are needed ahead of time.

**Comment by CyrusNajmabadi** [comment]
@ryzngard do we need this?  I thought you did something smart now to help with perf here?  or am i mistaken?

**Comment by ryzngard** [comment]
@CyrusNajmabadi still needed to improve perf. There are other fixes we've done but this would be a good win

**Comment by CyrusNajmabadi** [comment]
Sounds good.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
