### ISSUE TITLE
c# 8 switch statement not “smart” enogh

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49455]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/726961/c-8-switch-statement-not-smart-enogh.html)._

---
<p>The c# compiler should be smart enough to compile the following code:</p> <pre>bool? isSomething = strSomething switch
{
    &quot;I&quot; =&gt; true,
    &quot;D&quot; =&gt; false,
    _   =&gt; null,
};
</pre><p>Without me having to cast the null to get it to work:</p><pre>_   =&gt; (bool?) null,
</pre>

---
#### Jane Wu [MSFT] on 9/8/2019, 11:57 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This is legal in C# 9.
