### ISSUE TITLE
VB 'For' Code Snippet does not TAB to the next field properly

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4946]
The problem is that the completion list appears showing the keyword "Each":

![image](https://cloud.githubusercontent.com/assets/116161/9635151/d9167faa-5149-11e5-8a00-c9c62f66e17f.png)

So, TAB completes "Each" instead of moving to the next field. In Visual Studio 2013, the completion list simply didn't appear here.

**Comment by dpoeschl** [comment]
@DustinCampbell Additionally, the unnecessary presence of Rename Tracking in your screenshot is tracked by #4611, so there's more reason to make a general "IsSnippetEditingHappeningRightNow" API.
