### ISSUE TITLE
SetAccessibility extension method of DocumentEditor does not separate class keyword with a whitespace trivia  

### ISSUE THREAD

**Issue by SENya1990** [dotnet/roslyn#49461]
Hi. 
I'm trying to rewrite the accessibility of a `MemberDeclarationSyntax` node in a standalone console analyzer. I'm trying to do it for multiple nodes in the solution therefore I use 'SolutionEditor' and 'DocumentEditor' for the syntax tree editing.
Unfortunately I encountered an issue - when I call `documentEditor.SetAccessibility(node, Accessibility.Internal)`extension method of `DocumentEditor` it incorrectly rewrites the accessibility for nodes similar to the following class declaration:
```csharp
public class MyType { }
```
I get the following:
```csharp
internalclass MyType { }
```

**Version Used**: 
I use Roslyn 3.8.0 with .net core 3.1. Here are my nuget packages:
```
<ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.6" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="3.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.8.0" />
  </ItemGroup>
```
**Steps to Reproduce**:

1. Create a public class like this:
```csharp
public class MyType { }
```
2.  Get its syntax tree node and a document editor for it
3. Call `documentEditor.SetAccessibility(node, Accessibility.Internal)`

**Expected Behavior**:
The modified syntax tree looks like this:
```csharp
internal class MyType { }
```

**Actual Behavior**:
The syntax tree looks like this:
```csharp
internalclass MyType { }
```

I checked the syntax generator from the `SyntaxGenerator` property of the `DocumentEditor` object and it has the same problem (which is expected since the extension method uses generator internally). It seems to me that the problem is that the generation does not copy trailing trivia from the last token in modifiers list of the declaration and does not produce any whitespace trivia as well. I was able to create a workaround for this problem with a manual creation of the node's modifiers token list with replaced accessibility and additional whitespace trivia created for the last token. The `documentEditor.ReplaceNode` worked for me.

**Comment by CyrusNajmabadi** [comment]
This is by design.  You'll have to pass the node through the formatter to get the appropriate output.  The factory/generator methods don't do this.  They just create the raw nodes and create a raw tree.

**Comment by SENya1990** [comment]
@CyrusNajmabadi  I don't see how this is by design. The resulting syntax tree is incorrect, Imho it's not a format problem. 
`internalclass` is not a correct syntax tree, so this is not a matter of broken indentation.

**Comment by SENya1990** [comment]
@CyrusNajmabadi There is a strange label added to this issue because it is unrelated to the IDE. 
I did a check with the `Formatter.Format` and verified that the syntax tree is corrected. However, I disagree that it is correct behavior of the `SyntaxGenerator` class. I looked through the documentation for it. Nowhere is stated the demand to always format your output. Moreover, nowhere is stated that the `SyntaxGenerator` can produce invalid syntax trees:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.syntaxgenerator?view=roslyn-dotnet
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.syntaxgenerator.withaccessibility?view=roslyn-dotnet#Microsoft_CodeAnalysis_Editing_SyntaxGenerator_WithAccessibility_Microsoft_CodeAnalysis_SyntaxNode_Microsoft_CodeAnalysis_Accessibility_
Of course I know nothing about internal design decisions, so I will really appreciate if you provide me a link to some design document where such decisions are stated to avoid further confusion in the future. 
I also strongly disagree with a design where syntax generator's output can be invalid syntax tree and you need to pass it to the formatter to make it correct:
1. Like I said I couldn't find any reference to such decisions in the official documentation. On the contrary the documentation states that syntax generator will honor existing formatting options:
> The trees generated by this API will try to respect user preferences when possible. For example, generating MemberAccessExpression(SyntaxNode, String) will be done in a way such that "this." or "Me." will be simplified according to user preference if any ReduceAsync(Document, OptionSet, CancellationToken) overload is called.

It also correlates with my previous experience with the syntax generator. To me it seems that the documentation implies that the generator produces the correct trees with user settings honored.
2. Passing the output of the generator to formatter breaks my existing indentation. It makes it much harder to keep it. In my opinion this completely breaks the purpose of using the high level language agnostic API. Could you please provide an example of correct usage of Formatter which doesn't make code more complex and doesn't ruin the existing indentation at the same time if you disagree with this point.
3. Why does the syntax generator keeps trivia in other places but breaks it in this precise place? It looks more like a bug to me.
4. It will certainly will decrease client code performance to call formatter on every output of the syntax generator. On the other hand fixing this behavior won't severely affect the performance. I managed to made a workaround myself and it is much better that trying to apply format to the node. 
5. Trying to format the output node in many cases will ruin existing Git history.

Could you please discuss this issue with some team member responsible for the syntax generator like @jasonmalinowski (find author from the Github) before dismissing it as a design decision?

**Comment by CyrusNajmabadi** [comment]
> There is a strange label added to this issue because it is unrelated to the IDE.

Becausr the ide team owns this api

**Comment by CyrusNajmabadi** [comment]
> Could you please discuss this issue with some team member responsible for the syntax generator l

I am that team member.

**Comment by CyrusNajmabadi** [comment]
> The resulting syntax tree is incorrect, 

It is correct as per our design of this component. This component does not format. It only generates the tree structure *without* trivia. It is a separation of concerns and we expect the formatter to handle whitespace.

**Comment by CyrusNajmabadi** [comment]
> The trees generated by this API will try to respect user preferences when possible. For example, 

This is in reference (possibly implied) to code actions. In code actions were always run the final document through a series of passes (like formatting/reducing/etc.). So if you use code generated by SyntaxGenerator, it will properly work there. However, if you are not going through code actions, you will need to manage this yourself

**Comment by CyrusNajmabadi** [comment]
> Why does the syntax generator keeps trivia in other places but breaks it in this precise place? It looks more like a bug to me.

There is a difference with the generator operating on existing code vs generating new code.  When generating anything new it will not make any Whitespace decisions

**Comment by CyrusNajmabadi** [comment]
This is the helper we call:

https://github.com/dotnet/roslyn/blob/bd7a354037987e6895b80989d4adabba5860fda2/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs#L268

So you should just make the formatter call like we do there :-)

Good luck!

**Comment by SENya1990** [comment]
>Because the ide team owns this api :-)

Thanks for the clarification

> This is in reference (possibly implied) to code actions. In code actions were always run the final document through a series of passes (like formatting/reducing/etc.). So if you use code generated by SyntaxGenerator, it will properly work there. However, if you are not going through code actions, you will need to manage this yourself

I couldn't find any statement in the documentation that there is a difference in behavior of API depending on the context where the API is called. There is also no such statements in at least some of the books (I can't say that I have read all of them) dedicated to Roslyn like "Roslyn Succinctly":
https://www.syncfusion.com/ebooks/roslyn
The clarification of the actual behavior cost me a lot of time and the behavior was completely unexpected.

>There is a difference with the generator operating on existing code vs generating new code. When generating anything new it will not make any Whitespace decisions

I strongly disagree on this point. You change declared accessibility of the node. It's not a replacement of provided syntax node with a new one. The input is not even a syntax token list. It is unexpected that it would work incorrectly. The public API documentation also doesn't mention any need for a call to the formatter. 

>This is the helper we call:
roslyn/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs
Line 268 in bd7a354
 Document document, CancellationToken cancellationToken) 
So you should just make the formatter call like we do there :-)

Thanks for the link. However, I have some questions for this helper. Does syntax generator annotates generated nodes himself or I should somehow retrieve them and annotate them manually with `Formatter.Annotation`? 
The same goes for  `SyntaxAnnotation.ElasticAnnotation` and all other types of annotation. In the latter case it will be really inconvenient to do it manually. On the other hand I don't want to format the whole document, my analyzer works on a large legacy code base with big code files where format is broken sometimes due to the historic reasons. I don't want to change the Git history for them. 
I also have a strong concern about performance. It is strange to have a requirement to do several awaited calls to formatters just to change accessibility of some existing member declaration node.  I think it will be a noticeable decrease on a large solution. Still I haven't done any profiling yet so it's just a concern.

I still have unanswered question. Where it is stated that `SyntaxGenerator` can generate incorrect syntax trees and you have to always apply formatter on them. I can't find it in the official documentation to which I posted links in my previous post. I can't see it in guides, in books, etc. I won't say that I have seen every guide, blog post or book with the description for the correct usage of `SyntaxGenerator` in Roslyn but I saw a lot of them. I have also looked at the comments in the source code. And nowhere it was stated that:
- Nowhere it was stated that `SyntaxGenerator` can generate invalid syntax tree and syntax nodes generated by `SyntaxGenerator` must be passed to the formatter. This also applies to the higher level syntax editors which use `SyntaxGenerator` internally like `DocumentEditor` or `SymbolEditor`. And the tree is not always incorrect but sometimes depending on what was generated.
- Except when you work inside the `CodeAction` context because the results will be formatted with formatter anyway. However this is also not always true since I may want to add extra analysis and changes on the generated code or just log/print the generated code and the generated code still isn't formatted. 

If there is some detailed document where these facts were stated please share a link to it with me. 
The official documentation for this API does not state a lot of things. You can say that I just misunderstood the documentation because it never stated that the generated syntax tree will be valid:-) But it is strange for a public API documentation to omit the fact that the result may be inconsistent and requires further processing (which isn't described)

**Comment by CyrusNajmabadi** [comment]
> I couldn't find any statement in the documentation that there is a difference in behavior of API depending on the context where the API is called. 

Hence the "possibly implied".  :)

**Comment by CyrusNajmabadi** [comment]
> I strongly disagree on this point. 

Ok.  As mentioned, this is the expected design.  It was how i intended this to work when i wrote all of this, and it's how the rest of this type works.  I get that you don't like it.  But that doesn't change things here.

> The public API documentation also doesn't mention any need for a call to the formatter.

Our public documentation is definitely lacking in some areas.  It would be worthwhile to improve things here.  When i get time in the future i will try to get to this.  Or, if you would to contribute such a PR, we would take it.

**Comment by CyrusNajmabadi** [comment]
> Thanks for the link. However, I have some questions for this helper. Does syntax generator annotates generated nodes himself or I should somehow retrieve them and annotate them manually with Formatter.Annotation?

The generator uses the normal SyntaxFactory (provided by teh compiler, which also doesn't put in whitespace trivia).  The new elements will have the SyntaxAnnotation.ElasticAnnotation attached to them.  So it's this line that will format these portions:

https://github.com/dotnet/roslyn/blob/8fe41a011a0b21ec26df08a3cabc3f35e7273a11/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs#L280-L281

**Comment by CyrusNajmabadi** [comment]
> I also have a strong concern about performance. It is strange to have a requirement to do several awaited calls to formatters just to change accessibility of some existing member declaration node. I think it will be a noticeable decrease on a large solution. Still I haven't done any profiling yet so it's just a concern.

This is what Roslyn does in all cases.  

If this turns out to be too slow, then you an always just add the token, fully formatted, yourself.  The idea of these helpers is that you use them together and it takes care of it for you.  In general, performance should be fine.   If it isn't, you can always do it manually.

**Comment by CyrusNajmabadi** [comment]
> I still have unanswered question. Where it is stated that SyntaxGenerator can generate incorrect syntax trees and you have to always apply formatter on them

I am stating it right here.  It is hte design of these roslyn systems.  They do not bother with trivia.  We created the entire concept of ElasticTrivia/ElasticAnnotation around this idea.  If you (or components you call) use the standard factory methods, you get elastic trivia, and the intent there is that a formatter will then take care of it for you.

This has been the design of roslyn (and these other components) for the last 10 years.

**Comment by CyrusNajmabadi** [comment]
It is documented here: 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxfactory.elasticmarker?view=roslyn-dotnet#Microsoft_CodeAnalysis_CSharp_SyntaxFactory_ElasticMarker

**Comment by SENya1990** [comment]
@CyrusNajmabadi thanks a lot!

>I am stating it right here. It is hte design of these roslyn systems. They do not bother with trivia. We created the entire concept of ElasticTrivia/ElasticAnnotation around this idea.

So, the `ElasticAnnotation` is like a marker for new nodes? I found one thing strange though. When I was verifying that the formatter solves the issue with access declaration I marked my node with `Formatter.Annotation` and also passed the annotation as argument to the formatter. But the node still was corrected. Does formatter always look for the `ElasticAnnotation` and format nodes with it?

>Note: i cannot speak to why the books you've read have not mentioned this. This is part and parcel of all our generation APIs. if you write SyntaxFactory.ClassDeclaration("Foo") you will get classFoo{} without any whitespace. If you want, you can manually set the whitespace to whatever you want. Or you can pass the syntax node through a formatter to get it to a state where it will properly parse.

How I wish this elastic trivia mechanism was described somewhere! I have even tried to google some docs right now using my new knowledge but still no luck at all. It seems this API is used mostly inside `CodeAction`s. I haven't encountered any problems myself when I used Roslyn inside code fixes. 

> It is documented here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxfactory.elasticmarker?view=roslyn-dotnet#Microsoft_CodeAnalysis_CSharp_SyntaxFactory_ElasticMarker

This documentation is a joke. It is very short and vague with no details of what APIs are included in syntax formatting. It provides literally nothing about the necessity to call formatter manually. There is no example at all. And it is not referenced by any of the syntax generating APIs documentation.  
I have two questions now:

1. Will the helper method in `CodeAction` you shared with me be published as a part of the public API?
2. 
>Our public documentation is definitely lacking in some areas. It would be worthwhile to improve things here. When i get time in the future i will try to get to this. Or, if you would to contribute such a PR, we would take it.

How can I create a PR for the documentation?  Where should I start? Should there be a corresponding issue on GitHub?

**Comment by CyrusNajmabadi** [comment]
> So, the ElasticAnnotation is like a marker for new nodes?

Yup!  Or, more explicitly: a marker on tokens when trivia isn't *explicitly* provided.  

> I found one thing strange though. When I was verifying that the formatter solves the issue with access declaration I marked my node with Formatter.Annotation and also passed the annotation as argument to the formatter. But the node still was corrected. Does formatter always look for the ElasticAnnotation and format nodes with it?

I'm not sure i undrestand exactly what you're saying here.  Since you marked the node with Formatter.Annotation, and then passed that annotation in... i would expect the entire node to eb formatted.  Did i misread your question?

**Comment by CyrusNajmabadi** [comment]
> Will the helper method in CodeAction you shared with me be published as a part of the public API?

Nope :)

It's just a series of transformations though, so you can do exactly the same thing without needing anything explicitly published.

**Comment by CyrusNajmabadi** [comment]
> This documentation is a joke. 

Fair enough.  I don't deny that documentation around roslyn is weak.  Primarily we all just have completely full plates, so investing time into documentation is challenging.

**Comment by SENya1990** [comment]
>I'm not sure i undrestand exactly what you're saying here. Since you marked the node with Formatter.Annotation, and then passed that annotation in... i would expect the entire node to eb formatted. Did i misread your question?

So the formatter **always** replaces elastic trivia wherever it finds it on a marked node even if the node isn't marked with `ElasticAnnotation`? I get it now

**Comment by CyrusNajmabadi** [comment]
> How can I create a PR for the documentation? 

Just create a PR that edits these files and beefs up the documentation for teh appropriate symbols.

> Should there be a corresponding issue on GitHub? 

You wouldn't need an issue.

--

Before writing a ton of docs though, you might want to open a PR that shows a sample of what you would be adding/changing.  We could then give feedback on if this was the right direction, and how you could then expand it out appropriately.

**Comment by CyrusNajmabadi** [comment]
> So the formatter always replaces elastic trivia wherever it finds it on a marked node even if the node isn't marked with ElasticAnnotation? I get it now

Not exactly.  I would say that in your scenario it's more like:

1. You put a formatter.annotation on the whole node.  this is telling the formatter: format the entire span of hte node.
2. the formatter will definitely touch whitespace between tokens in that span, regardless of what trivia is there.

So, if you had `class    C...` and you put the formatter annotation on that class decl and then formatted it, you'd get `class C...`.

If you don't have the formatter annotation, and you ask to only format the formatter annotation... i *think* (but would have to verify) that nothing would happen.

**Comment by SENya1990** [comment]
Yes, I understand now that replacement of the elastic trivia does not depend on the annotations of the node. It is part of the formatting process and will work for every node found by the formatter.

**Comment by SENya1990** [comment]
I still have more questions regarding the PR:
- Are there any guides like the documentation guide? Any conventions?
- Who should be added as a reviewer to the PR?

**Comment by CyrusNajmabadi** [comment]
> Are there any guides like the documentation guide? Any conventions?

Not really :)

> Who should be added as a reviewer to the PR?

Our bot will automatically add the right people :)
