### ISSUE TITLE
Consider making Operation.ChildOperations public

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#49475]
We'll shortly introduce a new internal method on `Operation`, `ChildOperations`, which uses a struct enumerable/enumerator to avoid allocations. We use it for `OperationWalker` internally, but that doesn't help consumers who want to use `Children` themselves. We should consider deprecating `Children` and making `ChildOperations` public for others to use as well.

**Comment by CyrusNajmabadi** [comment]
Yes please :)   Allocations bad.  especially for basic navigation over our trees.  Thanks! :)

**Comment by 333fred** [comment]
## API Proposal:

```cs
namespace Microsoft.CodeAnalysis
{
    [NonDefaultable]
    public readonly struct ChildOperationEnumerable : IEnumerable<IOperation>
    {
        internal ChildOperationEnumerable(Operation operation);

        public Enumerator GetEnumerator();
        public ImmutableArray<IOperation> ToImmutableArray();

        IEnumerator<IOperation> IEnumerable<IOperation>.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator();

        [NonDefaultable]
        public struct Enumerator : IEnumerator<IOperation>
        {
            internal Enumerator(Operation operation);
            public IOperation Current { get; }
            public bool MoveNext();

            void IEnumerator.Reset();
            object? IEnumerator.Current;
            void IDisposable.Dispose();
        }
    }
}
```

### Open Questions

1. Should we expose an indexer and Length property?
2. Is the current name appropriate? (Answer will be driven by 1)

**Comment by CyrusNajmabadi** [comment]
>Should we expose an indexer and Length property?

If reasonably close to O(1).  yes.  If you did that though, please rename to ChildOperationList.

**Comment by 333fred** [comment]
> > Should we expose an indexer and Length property?
> 
> If reasonably close to O(1). yes. If you did that though, please rename to ChildOperationList.

We'll discuss in the design discussion this afternoon, but at a guess no, it would not be reasonably close to `O(1)`.

**Comment by CyrusNajmabadi** [comment]
Then i would not expose it.  Those members strongly imply it's ok to random access without perf cliffs.  importantly, i should feel safe doing something like:

```c#
for (var i = 1; i < list.Length - 1; i++)
        DoSomething(list[i]);
```

if that's not the case, we're setting up a footgun IMO.

**Comment by 333fred** [comment]
## Notes from API Review

* Rename to `OperationChildrenCollection`
* Implement `IReadOnlyCollection`, meaning `Count`. Document that the collection is ordered, but random access is not provided.
* Add Linq methods from `ChildSyntaxList` that do not depend on indexes:
    * Any
    * First
    * Last
    * Reverse

**Comment by 333fred** [comment]
Followup question for API review: with the nested type, we're looking at `IOperation.ChildCollection.Reversed.Enumerator` as the most nested type here. That is a pretty deep hierarchy, do we want to reconsider `OperationChildrenCollection` as the top-level name? Or should we name the reversed collection `IOperation.ChildCollectionReversed`? This is less nested, but breaks with how `SyntaxNodeList` and co work.

**Comment by CyrusNajmabadi** [comment]
I would miror SyntaxNode.  it's served us well, and the naming/hierarchy there hasn't ever been a problem AFAICT.  I'd prefer consistency given that.

**Comment by 333fred** [comment]
> I would miror SyntaxNode. it's served us well, and the naming/hierarchy there hasn't ever been a problem AFAICT. I'd prefer consistency given that.

Mirror as in `OperationChildrenCollection`, or mirror the structure but keep it a nested type of `IOperation`?

**Comment by CyrusNajmabadi** [comment]
The latter.

**Comment by 333fred** [comment]
## API Review

* We're fine with the nesting level.

**Comment by cston** [comment]
> >Should we expose an indexer and Length property?
>
> If reasonably close to O(1).  yes.  If you did that though, please rename to ChildOperationList.  

Based on the existing implementations of the enumerators (implementations of `IOperation Operation.GetCurrent(int slot, int index)`), it looks like indexing would be O(1).

Could we expose `ChildOperations` as `IReadOnlyList<IOperation>`?

**Comment by 333fred** [comment]
Indexing is not O(1). Even the first or last element cannot be fetched in O(1) time.

**Comment by 333fred** [comment]
For example, index 3 could correspond to (1, 2) or (0, 3) or (3, 0). The only way to determine is by enumerating.

**Comment by cston** [comment]
It looks like calculating the element from the index requires comparing against a fixed number of offsets in each case. For instance:
```csharp
internal sealed class VariableDeclarationOperation : Operation
{
    internal IOperation GetChild(int index)
    {
        if (index < IgnoredDimensions.Length) return IgnoredDimensions[index];
        index -= IgnoredDimensions.Length;
        if (index < Declarators.Length) return Declarators[index];
        index -= Declarators.Length;
        if (index == 0 && Initializer != null) return Initializer;
        throw new IndexOutOfRangeException();
    }
}
```
And the `Enumerator` type would be implemented with an `int _currentIndex` only.

**Comment by 333fred** [comment]
That is only true when the type does not have an array in the children list, such as happens for the various loop operations. It is not possible to implement this in O(1).

**Comment by cston** [comment]
> That is only true when the type does not have an array in the children list

The example of `VariableDeclarationOperation` has two arrays in the child list. Sorry if I'm overlooking something obvious.

**Comment by 333fred** [comment]
I suppose we could do that, but it's still not O(1). In the case where there are single IOperation children, we have to check every one for null. It's still O(n) in the worst case, and O(k) in the average case.

**Comment by cston** [comment]
> but it's still not O(1)

Wouldn't the implementation get the child element in constant time?

**Comment by 333fred** [comment]
No. Consider an IOperation with multiple single element child nodes. Every element us checked for null. So to get index 0, you first have to check 0 for null, and if it's null you then check 1, and so on. That's why the current implementation uses both slot and index in slot, otherwise determining Current skills require essentially re-enumerating every time.

**Comment by cston** [comment]
> Consider an IOperation with multiple single element child nodes. Every element us checked for null.

Yes, but for any given `IOperation` type, the number of single element child nodes is known at compile-time since each is a field on the containing class. Checking a small fixed number of fields would be minimal overhead.

**Comment by 333fred** [comment]
We'll bring this back to discussion to see if we want to expose an indexer, with the caveat that while it's technically O(1) by strict big-o notation semantics, the implementation would essentially have to re-enumerate every slot.

**Comment by 333fred** [comment]
## Review Notes

Significant discussion was had on what consistency principles we wanted to have here:

* We have existing `SyntaxList` APIs that expose indexers with similar performance characteristics. It would be valuable to have existing knowledge of our API shapes carry over to this API. At the same time, we're not getting requests for the ability to index a child collection of IOperation nodes, and every new piece of code adds maintenance work.
* Our existing public `List`-suffixed nodes implement `IReadOnlyList`.
* If we go with a minimal API now, but later want to add indexer and list implementations to it, some of the members of the design group would regret a non-list suffixed name, and some would not.

We decided to compromise by naming the type `OperationList`, but _not_ implementing an indexer on it at this time. If we get requests for an indexer later, we can add it then.
