### ISSUE TITLE
Add option to allow Go to Definition (F12) to navigate to the object browser for symbols located in metadata

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4947]
In Visual Studio 2015, we added the Metadata as Source feature for Visual Basic that had been in C# for several years. This allows some newer features (like Inline Peek) to show code for symbols defined in metadata. However, this means that F12 no longer goes to the Object Browser as it did in Visual Studio 2013. Since users want to control this behavior, we should add an option.

**Comment by paul1956** [comment]
While you are in there it would be fantastic if F12 too you to Roslyn reference source as well, or even a local copy of Roslyn source.

**Comment by Pilchie** [comment]
Pulling back into 1.1, based on the fact @DustinCampbell already has this partially implemented.

**Comment by DustinCampbell** [comment]
This is now fixed for VS 2015 Update 1. There is an option that you will be able to check on the Text Editor->Basic->Advanced page to bring this behavior back.
