### ISSUE TITLE
Nullability tracking regression in VS 16.8.1

### ISSUE THREAD

**Issue by cnshenj** [dotnet/roslyn#49472]
**Version Used**: Visual Studio 16.8.1

**Steps to Reproduce**:
Visual Studio 16.7.6 does NOT have this issue. So, it must be a regression in Visual Studio 16.8.1.

```cs
var d1 = new Dictionary<string, string?>();
var d2 = d1.ToDictionary(kv => kv.Key, kv => kv.Value);
```

**Expected Behavior**:
`kv.Value` should be annotated as "'Value' may be null here" in tooltip.
`d2` should be of type `Dictionary<string, string?>`.

**Actual Behavior**:
`kv.Value` is annotated as "'Value' is not null here" in tooltip.
`d2` is of type `Dictionary<string, string>` (nullability of `TValue` is removed).

**Comment by RikkiGibson** [comment]
For some reason we are inferring a `string` type argument for `TElement` in the below method, when we should be inferring `string?`:

```cs
// Summary:
//     Creates a System.Collections.Generic.Dictionary`2 from an System.Collections.Generic.IEnumerable`1
//     according to specified key selector and element selector functions.
public static Dictionary<TKey, TElement> ToDictionary<TSource, TKey, TElement>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector);
```

This repros in 16.8.1, but [doesn't repro in master](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AxAHYCuANuRMOXAARzHW0CwAUOwAIAMdnAjABYA3F14CAdABlMxAI6iObTgGY+AJjoBhOgG92dQ3zWdBdALIAKAJR6DRh2ggI6AE350AvHWJwA7nQAIpgAxjCYAPZMCLgAPALcSHz83AD8AHw2ig6Ozm6a3u4SACoRwWGR0biWANZoXul0dRIA0nC4SXUNTWgSAGoQ5KRwJREAyjAIsgDmNtbZRgC+7ItAA==) (16.9 preview 2) for some reason. I actually have no idea what might have fixed this.. @cston @jcouv in case you happen to know what change would have fixed this scenario recently.
