### ISSUE TITLE
Cannot set background of XML Doc Comment CREFs, param names or param refs

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#4948]
The issue here is that these are now classified as they would be outside of XML doc comments -- as user types and identifiers. However, they really need to inherit their background color somehow from the XML doc comments.

![image](https://cloud.githubusercontent.com/assets/116161/9636843/8481ed22-5152-11e5-86ee-a2f9e4613349.png)

**Comment by Pilchie** [comment]
Is this possible to fix without support from the editor?

**Comment by CyrusNajmabadi** [comment]
Closing out as we  haven't heard from users that this is a concern.
