### ISSUE TITLE
Computations of top-level semantic versions for a project has multiple issues

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#49489]
We've discovered looking at the code that:

1. ~~It doesn't recompute it if files are added/removed.~~ (Edit: turns out the top-level version isn't recomputed, but the other project version is included.)
2. There are other cases (not identified) it doesn't update if a syntax tree does change top-level structure, which contributed to #49413. Due to code inspection I suspect that could happen if you updated a file on disk when it's closed with an older modified stamp, amongst other issues.

The conclusion is the code is unnecessary complex, and needs a rewrite.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
