### ISSUE TITLE
Survey: Repo contribution experience, Fall 2020

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/roslyn#49484]
We normally focus on how to improve the product, but we’re also turning our focus to improving the open source project. Periodically we are running a survey to collect feedback on your experience working with our repos. We did one back in May, and as its been about 6 months, its about time for another. We’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. 

Survey

Thank you for your time!

**Comment by PathogenDavid** [comment]
@samsp-msft Should this issue be pinned like it was on other repos?

**Comment by Barthdry** [comment]
Yes

**Comment by samsp-msft** [comment]
The survey is now closed. Thank you to everyone who provided feedback. I have removed the link from the first post.

**Comment by Youssef1313** [comment]
@samsp-msft The issue is still pinned. I think it can be unpinned now?

**Comment by samsp-msft** [comment]
> @samsp-msft Sam Spencer FTE The issue is still pinned. I think it can be unpinned now?

Thanks
