### ISSUE TITLE
Introduce local variable doesn't work for all cases

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#49496]
There isn't an option for `introduce local variable` for the following scenario: 

![image](https://user-images.githubusercontent.com/46729679/99701201-fcaadc80-2a48-11eb-99ef-b578500eaaa2.png)

Unless I make it into an interpolated string:

![image](https://user-images.githubusercontent.com/46729679/99701319-26fc9a00-2a49-11eb-9008-0085d5a169cd.png)

**Comment by CyrusNajmabadi** [comment]
Yes.  That's intentional. It's a constant, so we offer to introduce a constant.  We don't offer both constants and variables here because it would just be so cluttered.  i.e. we already have 4 options offered.  Offering 8 would just be overkill.

**Comment by CyrusNajmabadi** [comment]
I don't know.  I use this a fair amount.  I start with code that just has values built in, and i then just go and take all the values and make a constant out of it that is referenced in all these locations.

Why can't this just be "introduce constant" and then "change constant to variable" if we think that occurs?

**Comment by sharwell** [comment]
> Why can't this just be "introduce constant" and then "change constant to variable" if we think that occurs?

The proposal to start with a local and then promote to constant follows the strategy of "things local to current code are more likely to be the current intent than things that apply to broader scopes".

**Comment by CyrusNajmabadi** [comment]
>  "things local to current code are more likely to be the current intent than things that apply to broader scopes". 

Sure.  I think it's fine to flip so that we generate local constants over class constants.  However, i would still prefer we stick with generating constants, and then just let the user remove the const if they don't actually want a constant.  

> The proposal here also ensures that "expressions" are generally treated in a consistent manner, so the user doesn't need to worry themselves about details of the language specification in order to predict what the light bulb will show.

I can see that argument.  I'm not firmly opposed to it.  I just have a biased feeling that it's more common to want these to just be constants, which then are sometimes converted to variables than to have variables that are converted to constants.  

That said, if we make these variables by default *and* we have an analzyer mentioning the local can be a constant, that would be nice.

**Comment by sharwell** [comment]
> mentioning the local can be a constant

In my experience, local constants don't offer much over local variables aside from getting in the way with naming style diagnostics. Even in cases where a local could be a constant, I would prefer the IDE not bother me about it.

**Comment by CyrusNajmabadi** [comment]
> In my experience, local constants don't offer much over local variables aside from getting in the way with naming style diagnostics. Even in cases where a local could be a constant, 

This must come down to preference.  I far prefer it as i can tell it's meant to actually be a constant and that i know it will not cahnge later on.  If we had readonly-locals, i'd more more amenable to this being just a variable.  However, it's far less cognitive burden to see a constant as it means i can grok it right there and know i don't have to consider any sort of data flow in my head as i'm examining things.

**Comment by ryanbrandenburg** [comment]
Design meeting conclusion: [Do as suggested here](https://github.com/dotnet/roslyn/issues/49496#issuecomment-730558667), but also file a follow-up to suggest marking things as constant where possible.

Special validation is needed where the compiler requires a constant.

**Comment by sharwell** [comment]
I filed #49675 for the proposed **Make Variable Constant** analyzer.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
