### ISSUE TITLE
Peek doesn't translate line/column for projection buffers

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#4949]
Originally reported by @slaks on [CodePlex](http://roslyn.codeplex.com/workitem/431):

If I hit Alt+F12 on any local variable defined within a Razor CSHTML file, the peek window will take the line number within the internal C# buffer, and show that line number in the outer CSHTML, showing the wrong line.
You need to translate line numbers into the outer projection buffer in this scenario.
`CreateDocumentPeekResult()` looks like the right place to do this; it should probably try to query the workspace for the text container and check if it's a projection buffer.

**Comment by CyrusNajmabadi** [comment]
Projection scenarios are not being worked on anymore.  we support those scenarios through razor + LSP.
