### ISSUE TITLE
CSharpCompilation - error CS0012: The type 'Object' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by Mun1z** [dotnet/roslyn#49498]
Migrating a solution from .NET Core 3.1 to .NET 5.0 fail on CSharpCompilation emit. I was able to reproduce the problem with a minimal project as described on the steps bellow.

**Version Used**: Microsoft.CodeAnalysis.CSharp (3.8.0)

**Steps to Reproduce**:

1. Create a C# DotNetCore (Console Application)
2. Change TFM to .NET 5.0
3. Add the following class on ConsoleApp1

```csharp
 class Program
    {
        static void Main(string[] args)
        {
            string testClass = "" +
                "using System;" +
                "public class TesteClass" +
                "{" +
                    "public TesteClass()" +
                    "{" +
                        "var obj = new Object();" +
                        "Console.WriteLine(obj);" +
                    "}" +
                "}";

            var references = new List<MetadataReference>
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Console).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(System.Runtime.AssemblyTargetedPatchBandAttribute).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo).Assembly.Location),
                };

            var compilation = CSharpCompilation.Create(Guid.NewGuid().ToString() + ".dll")
                .WithOptions(new CSharpCompilationOptions(Microsoft.CodeAnalysis.OutputKind.DynamicallyLinkedLibrary))
                .AddReferences(references)
                .AddSyntaxTrees(CSharpSyntaxTree.ParseText(testClass));

            var eResult = compilation.Emit("test.dll");

            Console.ReadLine();
        }
    }
```

**Expected Behavior**:
Success: true, same result as dotnet core 3.1

**Actual Behavior**:
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
![error_roslyn_dotnet5](https://user-images.githubusercontent.com/17263249/99710210-0818fa80-2a7f-11eb-8a4a-c1092a1fc9cc.png)

**Comment by robertsabo0** [comment]
I have the same problem

**Comment by jaredpar** [comment]
This behavior is "By Design". The problem here is that the technique you are using here to add references is using implementation assemblies, not reference assemblies. The stability of APIs in implementation assemblies is not guaranteed over time. The solution here is to reference the reference assemblies in the project. 

Unfortunately it's not as easy to reference them, they don't have the handy `typeof(object).Assembly.Location` expression. It requires a bit of work to package them with your application to be usable. The following project has a base implementation of packaging these references that you can look at for an approach here. 

https://github.com/jaredpar/roslyn-codedom

**Comment by robertsabo0** [comment]
Yes, it solved. 
Thank you

**Comment by tkw-devs** [comment]
@robertsabo0 - how did you solve it?

**Comment by Mun1z** [comment]
@tkw-devs you can solve using this marked code: 

![image](https://user-images.githubusercontent.com/17263249/100386558-796b2700-3004-11eb-9831-32a7e32d429a.png)

**Comment by tkw-devs** [comment]
@tkw-devs - got it 👍 I manage to solve it! Thx!

**Comment by Mun1z** [comment]
@jaredpar The example I gave works perfectly in the .net core, when upgrading to .net 5 it stops working, having to be implemented the way it was done, I still think it should work as it did before, imagine there each dotnet version as previous things stop working and you have to rewrite again?

**Comment by robertsabo0** [comment]
@tkw-devs  I downloaded the repository on link that @jaredpar sent: https://github.com/jaredpar/roslyn-codedom

Here, you have powershell script named: Generate.ps1 .
I edited it to add .NET 5.0 
At about line 100, calls of Add-TargetFramework looks like this:

```
Add-TargetFramework "NetCoreApp31" 'Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1' 
Add-TargetFramework "Net50" 'Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0' 
Add-TargetFramework "NetStandard20" 'netstandard.library\2.0.0\build\netstandard2.0\ref'
```

After running script, I included that project to my solution as dependency and to all references collection when compiling I added Net50.All

I hope I helped you :)

**Comment by SteveStrong** [comment]
this is works  the key is:

            Assembly.GetEntryAssembly().GetReferencedAssemblies()
                .ToList()
                .ForEach(a => references.Add(MetadataReference.CreateFromFile(Assembly.Load(a).Location)));

**Comment by jaredpar** [comment]
@Mun1z 

> The example I gave works perfectly in the .net core, when upgrading to .net 5 it stops working, having to be implemented the way it was done, I still think it should work as it did before, imagine there each dotnet version as previous things stop working and you have to rewrite again?

The problem here is that your sample referenced the implementation assemblies and that is officially not supported by the runtime team. The are free to refactor the implementation assemblies as they choose. In this case that resulted in a new assembly that you're not referencing here that is necessary for a successful compilation in .NET 5. 

To be clear this is not something the compiler controls. The compiler is working with the inputs its given here and in this case there aren't sufficient references for us to run a compilation.

**Comment by WizardBrony** [comment]
@jaredpar What is the accepted way to obtain dotnet reference assemblies? Referencing `Microsoft.NETCore.App.Ref` like you do in your app does not work:

```
Error	NU1213	The package Microsoft.NETCore.App.Ref 3.1.0 has a package type DotnetPlatform that is incompatible with this project. 	Roslyn.CodeDom
```

**Comment by jaredpar** [comment]
> What is the accepted way to obtain dotnet reference assemblies? 

The method in the roslyn-codedom repo is the accepted way of doing things. This is how for instance pretty much all of the C# compiler tests run. The process of packaging up the reference assemblies is more complex (we support a lot of different TF and weird ref assembly cases). The roslyn-codedom repo was meant as a way of taking our weird complex system and simplifying it for the common case.

**Comment by jaredpar** [comment]
The discussion in this thread finally prompted me to turn roslyn-codedom into something that was more productized. 

https://github.com/jaredpar/basic-reference-assemblies

This repository now builds easy to use reference assembly DLLs. The README.md has a lot of details but in short using the [NuPkg](https://www.nuget.org/packages/Basic.Reference.Assemblies/) defined there you can create in memory compilations like so:

```c#
var code = @"
using System;
static class Program
{
    static void Main()
    {
        var tuple = (Part1: ""hello"", Part2: ""world"");
        Console.WriteLine($""{tuple.Part1} {tuple.Part2}"");
    }
}
";

var compilation = CSharpCompilation
    .Create(
        "HelloWorld.dll",
        new[] { CSharpSyntaxTree.ParseText(code) },
        references: ReferenceAssemblies.Net50);

using var fileStream = new FileStream(@"p:\temp\helloworld.exe", FileMode.Create, FileAccess.ReadWrite);
var emitResults = compilation.Emit(fileStream);
```

**Comment by janmechtel** [comment]
I'm trying to port a project to .net5.0 that is:

> using Microsoft.Office.Core;
> using Microsoft.Office.Interop.Word;

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'CustomXMLParts' is defined in an assembly that is not referenced. You must add a reference to assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.	DynamicsTransformer	C:\Projects\Upgrades\UpgradeTools.DynamicsTransformer\DynamicsTransformer\Program.cs	277	Active

```

This issue is the only thing I found that seems to be related.

Am I on the right track here at all?

**Comment by janmechtel** [comment]
Sorry for bothering. Seems like i found a way. 

When adding the references in the new project via Dependencies > Add COM Reference they showed up in .csproj like this:

```
    <COMReference Include="Microsoft.Office.Word.dll">
      <VersionMinor>7</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>00020905-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
    <COMReference Include="Microsoft.Office.Core.dll">
      <VersionMinor>8</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>2df8d04c-5bfa-101b-bde5-00aa0044de52</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
```

I went to copy them from the .net 4.7.2 .csproj like this:
```

     <COMReference Include="Microsoft.Office.Core">
      <Guid>{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>8</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Interop.Word">
      <Guid>{00020905-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>8</VersionMajor>
      <VersionMinor>7</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
```

I don't understand the difference, but it seems to work

**Comment by dev-oups** [comment]
For information you may deactivate implicit usings to make it work.
