### ISSUE TITLE
edit and continue with unsafe code fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/862918/edit-and-continue-with-unsafe-code-fails.html)._

---
<p>Not sure what can be done here as the words &quot;unsafe&quot; are literally everywhere in my code. There are many times when unsafe code is needed as c# doesn't have an easy way to serialize and serialize structs at the byte level (very important feature for writing fast memory efficient code) Also indexing based on the size of structs is super easy for me for some reason (not sure if I'm unique in this regard or I'm just a strange duck) so please fix unsafe edit and continue or better:</p><p></p><p>Alternatively: provide a native .net method of serializing and deserializing binary data at the byte level, similar to C style. Also include unions so I can just grab the byte array. Provide warning based on architecture of the system as well. </p>

---
#### Feedback Bot on 12/19/2019, 11:12 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by kendrahavens** [comment]
Related to https://github.com/dotnet/roslyn/issues/48628

cc @tmat
