### ISSUE TITLE
[LSP] Client fails to restart server with "The language server has not yet shutdown"

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#49528]
When we get a fatal error in the queue, we shutdown the server.  However, when the LSP client attempts to restart us, we then fail to restart with 
```
System.InvalidOperationException: The language server has not yet shutdown.at Roslyn.Utilities.Contract.Fail(String message)at 
Microsoft.VisualStudio.LanguageServices.Implementation.LanguageClient.AbstractInProcLanguageClient.ActivateAsync(CancellationToken token)at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)at 
Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<OnRpcDisconnected>d__92.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   
Razor C# Language Server Client 
```

![image](https://user-images.githubusercontent.com/5749229/99851862-b0d56180-2b34-11eb-8e4d-393bf45b2243.png)

It seems like there can be a race condition where the LSP client thinks the connection is disposed, but we still think we're running
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs#L100

**Comment by dibarbet** [comment]
If we hit the running = true check, that means _shuttingDown must be false - https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs#L100

I wonder if we're throwing another exception somewhere that causes the streamjsonrpc connection to be disposed of?

**Comment by dibarbet** [comment]
One thing to check here is if the restart triggers new document didOpen requests

**Comment by davidwengier** [comment]
In the case of an error, we do the shutdown in a background task, so in theory that might not have completed when the new client is being activated, but after changing that, so that activation waits for previous shutdown to finish, I still managed to get this to occur once. Unfortunately getting it to occur under a debugger is proving difficult.

**Comment by davidwengier** [comment]
> One thing to check here is if the restart triggers new document didOpen requests for razor documents as well

That looks like where its failing, when the server sends the initial set of didOpen calls. Still trying to track down what happens next.

**Comment by NTaylorMullen** [comment]
```C#
if (error)
    Debugger.Launch();
```

Is your friend 😄

**Comment by davidwengier** [comment]
This was addressed by better error handling, and is less frequent with platform changes to better honour content type.
