### ISSUE TITLE
Source Generators: generated file appears empty after re-opening the solution

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49521]
**Version Used**: VS 16.9.0 Preview 2 (30713.195.main)

**Steps to Reproduce**:

1. Open a solution that includes use of a Source Generator
2. Use Go To Definition on a reference to generated code to open the generated file.
3. Leave the generated document open, but close the solution.
4. Re-open the solution.

**Expected Behavior**:

The generated document re-opens with the same content.

**Actual Behavior**:

The generated document window re-opens but is empty. 
Repeating step 2 above opens a _new_ generated file window that has the content in it, leaving the empty generated file window still open beside it.

**Comment by stephentoub** [comment]
Hitting this as well...

**Comment by CyrusNajmabadi** [comment]
Closing as these systems were entirely rewritten since then.
