### ISSUE TITLE
Navigate to source code and it says no implementation

### ISSUE THREAD

**Issue by shukuma97045** [dotnet/roslyn#49522]
**Version Used**: 

**Steps to Reproduce**:

1. Two projects in same solution, One project using file from another project
2.  When I click ctrl+f12 it says no implementation
3.  I even enabled  "navigate to decompile sources" in case not present (by going to Tools > Options > C# > Advanced

**Expected Behavior**: Should have shown me decompiled code

**Actual Behavior**: Saying no implementation

**Comment by sharwell** [comment]
This issue occurs because **Go To Implementation** does not support navigating to symbols that cannot be overridden. For situations like this (e.g. a reference to a constructor), it likely makes sense to have it automatically behave like **Go To Definition** instead.
