### ISSUE TITLE
Analyzer nodes aren't expanding properly

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#49524]
@paulomorgado shared the solution internally to test with.

**Comment by mavasani** [comment]
This seems to repro with all SDK style projects, but the node expands fine with legacy csproj style projects. I suspect this is a regression in project-system repo? Also tagging @drewnoakes

**Comment by jasonmalinowski** [comment]
@mavasani We figure I broke this when I did the refactoring of that part of the code to remove the other project.

**Comment by mavasani** [comment]
Ah, got it. Thanks.
