### ISSUE TITLE
Documentation: C#9 language features and netstandard2.0

### ISSUE THREAD

**Issue by ptr1120** [dotnet/roslyn#49538]
I did not find any documentation about which of the new C#9 language features are supported in a library that targets netstandard2.0.
My questions:
1. Records (https://github.com/dotnet/csharplang/issues/39): are currently working with netstandard 2.0, is this a supported feature?
2.  Covariant Returns (https://github.com/dotnet/csharplang/issues/49), are currently not working, any chance to get this working with netstandard 2.0?

Thank you and best regards!

**Comment by PathogenDavid** [comment]
Officially speaking, [C#9 is only officially supported on .NET 5](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version).

> 2\. Covariant Returns ([dotnet/csharplang#49](https://github.com/dotnet/csharplang/issues/49)), are currently not working, any chance to get this working with netstandard 2.0?

Covariant returns require support from the runtime, so they will never work on .NET Standard 2.0

----------

That being said, as you've noticed some feature work just fine. @Sergio0694 Has a nice [write-up of what works on unsupported runtimes](https://medium.com/@SergioPedri/enabling-and-using-c-9-features-on-older-and-unsupported-runtimes-ce384d8debb). (Some features require a small amount of work on your part to make them work.)

**Comment by ptr1120** [comment]
Thank you very much.

**Comment by PathogenDavid** [comment]
No problem!
