### ISSUE TITLE
Source Generators: Documents with generated content doesn't permit code fix execution

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49533]
**Version Used**: VS 16.9 (30718.196.main)

**Steps to Reproduce**:

When using the `Microsoft.CodeAnalysis.PublicApiAnalyzers` analyzer in a project in combination with a source generator that produces public members, we get RS0016 warnings about public API that "is not part of the declared API."
Normally I'd fix this by navigating to that symbol and using a Code Fix provided by the PublicApiAnalyzers to add the necessary lines to the PublicAPI.Unshipped.txt file.

**Expected Behavior**:

The code fix is offered and can be executed.

**Actual Behavior**:

But (presumably because the generated code document is readonly) the code fixes are not available. While that may make sense from a "you can't change this doc anyway" perspective, it makes adding new lines to PublicAPI.Unshipped.txt very tedious.

**Comment by CyrusNajmabadi** [comment]
This shoudl likely go to https://github.com/DotNetAnalyzers/PublicApiAnalyzer.  They will need to be updated to analyze these files.

**Comment by AArnott** [comment]
@CyrusNajmabadi they _do_ analyze the files. That's not the problem. The problem is roslyn won't show me code fixes in the generated file so I can fix those diagnostics.

**Comment by CyrusNajmabadi** [comment]
Ah, gotcha.  Yeah, that makes sense.

**Comment by jasonmalinowski** [comment]
Yeah, this is due to the work that generated files still open in as Miscellaneous Files. Once that's fixed we expect this to work.

**Comment by jasonmalinowski** [comment]
Closing this in favor of primary tracking bug #50676.

**Comment by jasonmalinowski** [comment]
Reopening since this one is going to require some more work than is being tracked by the original bug.
