### ISSUE TITLE
Failure to sign roslyn generated assembly

### ISSUE THREAD

**Issue by Illeris** [dotnet/roslyn#4953]
Issue: siging dynamic generated assembly fails. Code statement:

CSharpCompilationOptions compilationOptions = new CSharpCompilationOptions(Microsoft.CodeAnalysis.OutputKind.DynamicallyLinkedLibrary).WithCryptoKeyFile(String.IsNullOrEmpty(ca.AssemblySigningFile) ? null : ca.AssemblySigningFile);

ca.AssemblySigningFile : full path name to .snk key file

Result of compilation.Emit contains error: Error signing output with public key from file '<pathname>\demokey.snk' -- Assembly signing not supported. : error CS7027: Error signing output with public key from file '<pathname>\demokey.snk' -- Assembly signing not supported.

**Comment by jaredpar** [comment]
Thanks for reporting!  

Can you give us a bit more information here?  For example are you running this on Windows or say Linux?

**Comment by tmat** [comment]
Do you set CompilationOptions.StrongNameProvider to an instance of DesktopStrongNameProvider?

**Comment by AlekseyTs** [comment]
@Illeris Please provide a complete sample code that demonstrates the issue and answer the questions above. If we don't hear from you within next several days, we will close the issue. Thanks.

**Comment by jaredpar** [comment]
@Illeris closing this issue because at this time we don't have enough information to proceed with an investigation or fix.
