### ISSUE TITLE
IDE0062: Make local function static codefix not working with top-level statements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#49539]
**Version Used**:

master

**Steps to Reproduce**:

1. Apply the codefix for IDE0062 in a full C# program, the static keyword is added as expected. [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKF+gAhQwHZcBvXA6otNKmynGlojATgAoAJOAGz4B7TgEoRAblwNWbAAwFeA4SIIBeAHwEARIqEAaAgHdBCPgBMAhFsnMaAX1x2gA=).
2. Apply the codefix for IDE0062 in a top-level statement program, the codefix does nothing. [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKFyjATgAoAJOAGwoHtiBKOgbl3wwAYACcq2ujgXgB8HAETcaAGg4B3aggoATAIQjGQA==).

**Expected Behavior**:

The `static` code fix is added.

**Actual Behavior**:

I'm not sure whether the codefix crashes or not (SharpLab doesn't show IDE crashes AFAIK, I haven't tried in Visual Studio yet).

**Comment by DoctorKrolic** [comment]
On latest `main` no longer reproducible:
![2ly6v9Vlhe](https://user-images.githubusercontent.com/70431552/198674759-26159eb6-f0f8-4a3a-a0df-3866bd2e2b5c.png)
