### ISSUE TITLE
ToolBar lost when reopen Visual Studio

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#49546]
Every time I add `Text Editor`, when I close and reopen VS, it's lost!
I know I should `Send FeedBack` in the Help menu in VS, but if that, I can't know the progress of my issue.
Why VS team resolve issue so slow? Many issue I report more than 2 years!!!

![image](https://user-images.githubusercontent.com/2529999/99884369-c2b82100-2c68-11eb-85a4-c1543e07c1ef.png)

**Comment by CyrusNajmabadi** [comment]
Closing this out as this is unrelated to roslyn

> I know I should Send FeedBack in the Help menu in VS, but if that, I can't know the progress of my issue.

You can see the status of your reports issues. If you have any issues retired on this, I can help you try to get traction. Please link me to the issue over you file it.
