### ISSUE TITLE
Nullable reference type checking ignores [Optional][DefaultParameterValue(null)]

### ISSUE THREAD

**Issue by voroninp** [dotnet/roslyn#49567]
With enabled nullable types:

```CSharp
#nullable enable
void Foo(object param = null) {}
```
I get the warning from the compiler: > Cannot convert `null` literal to non-nullable reference type.
However, if I change signature to this:

```CSharp
#nullable enable
void Foo([Optional, DefaultParameterValue(null)] object param ) {}
```
Compiler is totally fine with this. 

P.S. I've discovered this issue for the case of caller member name which requires default value:
```CSharp
[CallerMemberName, DisallowNull, Optional, DefaultParameterValue(null)] string memberName
```

**Comment by CyrusNajmabadi** [comment]
Moving to roslyn as this sounds like more of an anlayzer/compiler choice rather than lang decision.

**Comment by RikkiGibson** [comment]
The [above scenarios](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8DEA7AVwwwmAzgAI49TyBYAKEYAEAGC5gRgDoARNCAHM8Ae1hoAxlG4BhEQBM4AQRoYAnlDRQA3C3ZduAJQJ4YaMHFkiwAB0yIAyogBukuDr0cex0+csBJU0QRGycEVwl3XSYGZgBmDgAmChkKAG9GCiyOABYKADEREQAKTOzygG0AeRszEVUkCl44ADMIIhgABQgECAt4BAA1CAwCOGLCYgBKAF0y8qyRYAArOAkYChsevqn59L2AX0Y95jzCkUTShgXsipkR8gQAWTgwYEQAOT64Rv4oB5EAHcPkQMI0anUGk1Wu0MF1tv1EMNRuNJhhZntylx2BY3p9vrtrtkMkSskcGAcgA) work now, so I'll close this out.

> 
> 
> > Because this is not a `ref` parameter or a generic type, DisallowNull is the wrong thing to use.
> 
> Sounds like this should be a warning then :)

This is tracked by #36073. I would be interested to see a proposal for precisely what usages of nullability attributes should produce warnings. I think it would probably help steer people onto the right path.

> 
> 
> `[CallerMemberName] string memberName = null!` is preferable. It emits different IL because DisallowNull is not present (it would be redundant).

Note that there isn't a guarantee that the CallerMemberName will be substituted by the compiler in all scenarios. In some scenarios involving implicit code, the explicit default value (null in this case) will be used instead.
