### ISSUE TITLE
Doc comment auto-inserted in verbatim strings with preceding tag

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#49564]
```cs
@"/// <summary>
  ///$$"
```

Pressing enter in the `$$` location results in this:

```cs
@"/// <summary>
  ///
  /// $$"
```

I was expecting just a newline, as I'm in a verbatim string.

🔗 [AB#1453939](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1453939)

**Comment by 333fred** [comment]
Also note that this requires multiple `///` lines:

```cs
@"///$$
";
```
Does not result in a newline with `///` in it, but
```cs
@"///
///$$
```
does.

**Comment by ryanbrandenburg** [comment]
Design Meeting Notes: We agreed that this is a bug that we should fix.
