### ISSUE TITLE
Rename does not work for record members

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#49562]
**Version Used**: 

Renaming a record member always results in a conflict on every usage of it.

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/1103906/99927412-699bda80-2d99-11eb-8937-dd39babe9f74.png)

**Expected Behavior**:
No conflicts

**Actual Behavior**:
Conflicts on every usage of the record member

**Comment by jinujoseph** [comment]
Duplicate of #44560
