### ISSUE TITLE
Productivity feature: Add logger to class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Productivity-feature:-Add-logger-to-clas/1262231?preview=true)._

---
<p>Dear Visual Studio team,</p><p>thanks for the great product you are making.</p> <p>I would like to suggest a feature which would integrate well with .NET 5.0, dependency injection and general code quality - the ability to complement a constructor and class with ILogger, for example, from this:

```csharp
public class MyClass
{
  public MyClass(){} 
}
```

to this:

```csharp
using Microsoft.Extensions.Logging; 
using Microsoft.Extensions.Logging.Abstractions;

public class MyClass
{ 
   public MyClass(ILogger<MyClass>? logger = null)
   {
     if(logger != null)
     {
       _logger = logger;
     }
   } 

   private readonly ILogger _logger = NullLogger.Instance;
}
```

The logger parameter in constructor should always be the last one.</p> <p>This feature requires the following nuget: Microsoft.Extensions.Logging.Abstractions</p>

---
#### Feedback Bot on 11/19/2020, 07:26 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @mavasani can you point the user to extensibility info on how they can create there own refactoring
