### ISSUE TITLE
Produce compile warning when returning task inside using block without await

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49573]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/731785/produce-compile-warning-when-returning-task-inside.html)._

---
<p>The following code will cause all sorts of errors as the database context is possibly disposed before the FirstOrDefaultAsync has finished:</p> <p>public Task&lt;Customer&gt; GetCustomerAsync(long id)</p> <p>{</p><p>  using (var db = new MyDBContext())</p><p>  {</p><p>    return db. Customers.FirstOrDefaultAsync(c =&gt; c.Id == id);</p> <p>  }</p><p>}</p><p>This can be fixed by using async:</p><p>public async Task&lt;Customer&gt; GetCustomerAsync(long id)</p><p>{</p><p>  using (var db = new MyDBContext())</p><p>  {</p><p>    return await db. Customers.FirstOrDefaultAsync(c =&gt; c.Id == id);</p> <p>  }</p><p>}</p><p>But this pattern must be implemented by the programmer, being aware that the non-async version may fail.</p> <p>This is not unique to DBContext objects. Anything - file io, network, etc. should have a compile warning, maybe even an error, if the IDisposable in the using block has a method call that returns a Task and does not use an await.</p> <p>Please let me know if you have any questions. Thank you for taking the time to read.</p>

---
#### Jane Wu [MSFT] on 9/11/2019, 11:42 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Jeff Johnson on 3/4/2020, 09:50 AM: 

<p>This should produce the warning regardless of whether a return statement is used</p>

**Comment by jaredpar** [comment]
The compiler is operating as intended here and issuing a warning for this scenario would be a major back compat breaking change.
