### ISSUE TITLE
Generate override ToString() method to concatenate fields together

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49578]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/649110/generate-override-tostring-method-to-concatenate-f.html)._

---
<p>Generate override ToString() method to concatenate fields together for he POCO class in Visual Studio, like return $&quot;PropertyA={var}, PropertyB={var}&quot; as what Eclipse has.</p>

---
#### Jane Wu [MSFT] on 7/17/2019, 02:34 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by CyrusNajmabadi** [comment]
This can just be done with a record.
