### ISSUE TITLE
Analyzer test tries to load xUnit into app domain when executed in 64 bit.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#4959]
The unit test [`Microsoft.CodeAnalysis.UnitTests.AnalyzerFileReferenceTests.TestAnalyzerLoading_Error()`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,b04fd584904390af) fails in 64 bit because the assembly `xunit.dll` cannot be found.  The failing test is identical to [`TestAnalyzerLoading()`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,196491df9b713bdb) which passes except for the different calls to `TestSuccess()` vs. `TestTypeLoadException()` which in turn both subscribe to the `AnalyzerFileReference.AnalyzerLoadFailed` event.  In the `TestSuccess()` case [here](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,67), the event is never fired when the test behaves as expected, but in `TestTypeLoadException()` [here](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,67), the event **is** fired when the test behaves as expected, and the current theory is that the 64 bit app domain isn't using the [`RemoteAssert`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,c835ffe2520b5e62) object from the first app domain (which eventually calls `Assert.True()` in `xunit.dll`), but is instead loading its own causing the attempted load of `xunit.dll`.

FYI @amcasey @tannergooding

**Comment by tannergooding** [comment]
FYI @tmat, @KevinH-MS

**Comment by brettfo** [comment]
When this issue is fixed, the temporary workaround introduced by PR #4960 and merged to `master` as commit 20d0c5ecfdbe1e5da2802093cbb3ac73230a6fb9 should be reverted.

**Comment by davkean** [comment]
Dropping infrastructure as this a product test, adding Analyzers.
