### ISSUE TITLE
BUG: Incorect code-gen for local methods along with generics and dynamic

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#49599]
**Version Used**: VS Pro 16.8.2 (targeting .NET Core 3.1 or .NET 5)

**Steps to Reproduce**:
Compile and run:
```C#
public class Program
{
    static void Main()
    {
        Local1<object>();

        static void Local1<T>()
        {
            Local3();

            static int Local2(dynamic n) => (int)n;
        }

        static int Local3() => (int)(dynamic)4;
    }
}
```

**Expected Behavior**:
Program runs successfully.

**Actual Behavior**:
Fails with: System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format.'.

Program runs successfully when at least one of following is true:
- Generic parameter T is removed.
- Definition of Local2 is removed.
- Definition of Local2 is placed next to definition of Local3.
- Definition of Local3 is placed next to definition of Local2.
- Local2 does not take 'dynamic' as param.
- Local3 does not use 'dynamic'.

**Comment by kindermannhubert** [comment]
Probably same issue but without nested local methods - also fails with BadImageFormatException:
```C#
public class Program
{
    static void Main()
    {
        Local1();

        static int Local2<T>(dynamic n) => (int)n;
        static int Local1() => (int)(dynamic)4;
    }
}
```
Program runs successfully when at least one of following is true:
- Local1 is defined before Local2. (interesting!)
- Generic parameter T is removed.
- Local1 or Local2 is made non-local (=defined in Program).
- Local1 or Local2 does not use 'dynamic'.

**Comment by RikkiGibson** [comment]
Possibly related to #44720, but since it reproduces in situations where only 'static' local functions are used, it seems unlikely..?
