### ISSUE TITLE
There seems to be some errors in this target-typed conditional expression

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49598]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/There-seems-to-be-some-errors-in-this-ta/1260582?preview=true)._

---
[regression] [worked-in:16.8.1]
! [image.png] (https://aka.ms/dc/image?name=B0a4a46ea7d464f0096e4ecec621df50c637413446758633028_20201119-100435-image.png&tid=0a4a46ea7d464f0096e4ecec621df50c637413446758633028)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            short? a = 1;

var b = true;

var c1 = a ?? (b ? 4: 1);

var c2 = a ?? (true ? 4 : 1);

var c3 = a ?? (false ? 4 : 1);
        }
    }
}
```

---
#### Feedback Bot on 11/18/2020, 10:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jaredpar** [comment]
The issue here is that the first conditional is now gating on `langVersion:9` but has actually been legal since essentially C# 1.0. Need to fix the tie to langVersion here.

**Comment by jaredpar** [comment]
@cston FYI

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/50755.
