### ISSUE TITLE
SourceGenerator documentation incorrectly describes generator output.

### ISSUE THREAD

**Issue by dansiegel** [dotnet/roslyn#49619]
As described at DotNetConf the Source Generators are not emitting the output files by default and would require you to add:
https://youtu.be/3YwwdoRg2F4?t=223

```xml
<PropertyGroup>
  <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
```

According to the docs however this property should be true by default rather than something you need to know to explicitly enable. The property itself is actually not mentioned anywhere in this document.
https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.md#output-files

```
By default, generated texts will be persisted to a GeneratedFiles/{GeneratorAssemblyName} sub-folder within
CommandLineArguments.OutputDirectory. The fileNameHint from GeneratorExecutionContext.AddSource will be 
used to create a unique name, with appropriate collision renaming applied if required. For instance, on Windows 
a call to AddSource("MyCode", ...); from MyGenerator.dll for a C# project might be persisted as 
obj/debug/GeneratedFiles/MyGenerator.dll/MyCode.cs.
```

**Comment by jaredpar** [comment]
Agree that this property should be included in our feature doc but the default of not emitting them is correct here. This was designed to require explicit user opt-in.

**Comment by dansiegel** [comment]
I don't particularly have a problem with the emitting vs not emitting... Emitting is more useful while writing the generators than while consuming them... the important thing is to ensure that the documentation is in sync with the actual behavior :)

**Comment by chsienki** [comment]
Yes, the feature doc is somewhat out of date with the actual implementation. It's on my radar to get it up to date, as well as more importantly get a concise version and examples onto docs.ms

**Comment by chsienki** [comment]
Tracked by #50474
