### ISSUE TITLE
#reset core broken after .NET 5 install

### ISSUE THREAD

**Issue by donnyv** [dotnet/roslyn#49618]
Tried loading core by doing #reset core in the C# interactive window and got this.
![image](https://user-images.githubusercontent.com/2224189/100245327-ee0b6c00-2f05-11eb-9ed1-fd5ece9ec5f3.png)

**Comment by tmat** [comment]
Is `System.IO.Pipelines.dll` not present in `%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\InteractiveHost\Core'?

**Comment by donnyv** [comment]
@tmat It is not in there.

**Comment by tmat** [comment]
That would explain. Seems like something went wrong with the installer. A workaround should be to fetch this file from a package on NuGet.org and copy it there.
