### ISSUE TITLE
The new ! postfix operator generates incorrect warnings

### ISSUE THREAD

**Issue by triple-vee** [dotnet/roslyn#49620]
**Brief description:**
The ! postfix operator to suppress null checking generates a formatting warning/error. Here is example code:

            await _subscriber?.StopAsync(cancellationToken) !;

If you remove the space you get a warning. With the space you get a warning.

Describe your suggestion here.

Account for ! postfix operator.

Is your analyzer C# only? VB Only? Or Both?

C#

A small code snippet that describes a case that the analyzer should report.

            await _subscriber?.StopAsync(cancellationToken) !;

Any more additional information you would like to add.

I don't think any documentation is needed. It should just silently pass.

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by CyrusNajmabadi** [comment]
> If you remove the space you get a warning.

What warning to you get if you don't have a space?
