### ISSUE TITLE
IsImplictlyDeclared returns false for record ctor

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#49634]
**Version Used**: Latest with VS 2019 Preview

**Steps to Reproduce**:

I would expect the method symbol for the following record to have the property `IsImplictlyDeclared` returning `true` but it currently returns `false`.

```csharp
public record Person(string Name, int Age = 0);
```

**Comment by CyrusNajmabadi** [comment]
WHich method symbol in particular?  Thanks!

**Comment by Youssef1313** [comment]
@CyrusNajmabadi The synthesized record ctor I believe. See https://github.com/dotnet/roslyn-analyzers/issues/4462

**Comment by Evangelink** [comment]
Yes exactly.

**Comment by AlekseyTs** [comment]
It is not implicitly declared, there is a syntax for it - the argument list.

**Comment by Evangelink** [comment]
@AlekseyTs For me it's somehow implicitly declared. How do you tell apart:

```csharp
public record Product
{
        public string Name { get; init; }
        public int CategoryId { get; init; }

        public Product(string name, int categoryId) 
          => (Name, CategoryId) = (name, categoryId);
}
```

and

```csharp
public record Product(string Name, int CategoryId = 0);
```

On one of the analyzer, we detect the second case as if the parameters are unused and from the ctor `IMethodSymbol` I can't tell apart the 2 constructions.

When comparing the 2 constructs I would say that the second one is implicitly declared compared to the first one hence this ticket.

I am fine if you think it's ok as-is but I am really interested in knowing how can I distinguish the 2 to be able to fix the FP in the analyzer.

**Comment by AlekseyTs** [comment]
> I am really interested in knowing how can I distinguish the 2

If syntactic form of the declaration is important, I would say you should check that rather than trying compare a property that tells you nothing about the syntactic form. Symbol has DeclaryngSyntaxReferences property.

**Comment by CyrusNajmabadi** [comment]
Yeah.  We had this conversation on the team, and we decided it was explicitly declared.  There is a literal parameter list here.  And that is what explicitly calls out what the constructor will be.

Note: i can see it both ways.  However, we did discuss this and htis was by design for the team.

**Comment by Evangelink** [comment]
I can also see it both ways, I would have voted for considering it implicit because you only declare the signature and not the body but I probably don't have a full picture as you have. Besides as you stated, it was discussed and a decision was made.

At least with this issue it is somehow documented for others :)

**Comment by Evangelink** [comment]
@AlekseyTs Sorry but on the ctor symbol of this record, the `DeclaringSyntaxReferences` returns something, the same is true for the parameters symbols. So I am back to square 1. 

The only solution I have found is to look at the type of the declaring syntax. In case of a record with a ctor I get a `ConstructorDeclarationSyntax` and for the line declaration I get `RecordDeclarationSyntax`. But that forces me to complexify the analyzer to rely on syntax.

I think there should be some way to tell from the symbol without the need to rely to the syntax.

**Comment by AlekseyTs** [comment]
> I think there should be some way to tell from the symbol without the need to rely to the syntax.

I don't think I agree with your point of view here. Symbols are supposed to work and provide consistent view across many different sources. Source, metadata, etc. If an analyzer depends on syntax, I.e. can analyze only methods with a body in source, then, in my opinion, it should check that the method has a body in source (not try to detect what it cannot handle, but detect what it can handle instead) and syntax is the way to do that. This approach, for example, will make it more robust against the future changes in the language.

**Comment by AlekseyTs** [comment]
BTW, the ```IsImplitlyDeclared``` property was never advertised as something that can be used to detect if a method has a body in source.

**Comment by CyrusNajmabadi** [comment]
FYI, i agree with @AlekseyTs on this.  We had the same discussion on the team and the consensus what that the current approach was the more consistent one with how we've implemented this api in teh past.

> But that forces me to complexify the analyzer to rely on syntax.

Avoiding syntax-checks in analyzers is not a goal of the ISymbol api.  They are intended to be used in concert.  Fundamentally, you are asking a syntactic question.  From a symbolic perspective there would be no difference.  So since you only care about how it was declared in syntax, asking syntax taht question makes sense to me.
