### ISSUE TITLE
Source Generators: all generated documents are empty when generator produces more than one document

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49642]
When my source generator adds just one document using `context.AddSource`, Visual Studio can navigate to that generated document using Go to Definition on a user source file.

But when my source generator calls `context.AddSource` more than once, compilation succeeds but Go to Definition always opens an empty document (with the right filename).

VS version: 16.9 preview 3 (30727.24.main)

**Comment by AArnott** [comment]
This evidently doesn't repro 100% of the time.

**Comment by jasonmalinowski** [comment]
Fixed by #49625 and we're currently working on getting it backported to Preview 2 as well.
