### ISSUE TITLE
Is it possible to mark a member of a parameter as null/not null after a function returns?

### ISSUE THREAD

**Issue by Pilchard123** [dotnet/roslyn#49640]
If I have a function `bool ValidateString(string? input)`, then I can annotate it to indicate that if the return is `true` then `input` is not null:
```csharp
public static bool ValidateString([NotNullWhen(true)] string? input)
```
Is it possible to do that (or something similar) for a member of a parameter? `MemberNotNullWhen` looks a bit like what I'm after, but I don't think it can be applied to parameters. I'm thinking something along the lines of
```csharp
public class AClass { string? NullableString {get;set;}}
public static bool ValidateObject([ParameterMemberNotNullWhen(true, nameof(AClass.NullableString))] AClass input)
```
So then I could write
```csharp
public class AClass
{
    public string? NullableString { get; set; }
}

public static bool ValidateObject([ParameterMemberNotNullWhen(true, nameof(AClass.NullableString))] AClass input)
{
    return input.NullableString is not null;
}

static void Main(string[] _)
{
    var foo = new AClass();
    if (ValidateObject(foo))
    {
        Console.WriteLine(foo.NullableString.Length); // CS8602 Dereference of a possibly null reference.
    }
    Console.ReadLine();
}
```
without getting a warning about `foo.NullableString.Length`.

I don't know how feasible something like that would be, given that the member could change value on each read - but then again I don't imagine that's a particularly common scenario, and I guess you'd just not use such an annotation if that's how the member behaved.

**Comment by Pilchard123** [comment]
Edited the User/EmailAddress example so it isn't quite so simple to fix with a temp for emailAddress. Changes in post above.

**Comment by jaredpar** [comment]
At the moment no there is no way to do this. The closest attribute that exists to this is `MemberNotNull` however the design of that was explicitly limited to it controlling members of the type where the attribute annotation occurs. It cannot control members on other types. 

It could be extended to do this but that is a language decision vs. a compiler one. If you want to help push a design for this or suggest it as a feature please file an issue at dotnet/csharplang.

**Comment by Pilchard123** [comment]
Thanks :) I'll have go at writing it up a bit more formally and put it over there.
