### ISSUE TITLE
Inline type hints should show for target-typed new expressions

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#49657]
In variable initialization expressions, the type of the rhs expression new() is obvious and visible because it's the type of the variable (and thus can be read by looking to the left, usually).

In method arguments, this is not the case. To see the type, the caret needs to go to the parameter and the parameter hint info tooltip needs to be invoked (when using the keyboard).

I think it would be nice if the type was displayed as a type hint, optionally always, but specifically when hitting Alt-F1.

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi
