### ISSUE TITLE
The <see> xml doc tag doesn't create a link in Object Browser

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49651]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The--xml-doc-tag-doesnt-create-a-link-i/1265474)._

---
<see> doesn't create a link:
```
    /// <summary>
    /// foo
    /// See <see cref="MainPage"/> for more 
    /// </summary>
    class sadface {}
```

---
#### Feedback Bot on 11/23/2020, 00:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Maryer Ma [MSFT] on 11/24/2020, 01:55 AM: 

<p>Thank you for your feedback! Based on your description so far, we were unable to reproduce it on 16.8.2. If we misunderstood your question, could you please correct us? In order to investigate your issue further, can you help to confirm several questions?</p>
<ol>
<li>Are you installed other extensions in your machine? (Such as Resharper? Could you try to uninstall other extensions and then check whether your issue also reproduces or not?)</li>
<li>Can you try to reset all VS settings(Navigate to Tools-&gt; Import and Export Settings, then select ‘Reset all settings’) or repair your VS and then check whether your problem also reproduces or not?</li>
<li>Can you please provide more info with your issue (Detail repro steps, simply project or repro video)?<br>
Please feel free to let us know if you have any doubt. We look forward to hearing from you!</li>
</ol>

#### Alexander Sklar on 11/28/2020, 08:06 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We are not investing in object browser.
