### ISSUE TITLE
Incorrect Auto Completion

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/roslyn#49656]
When trying to type 
```cs
e.HasIndex(p => ...)
```

Auto completes to 
```cs
e.HasIndex(prop => ...)
```

I'm running VS 16.8.2. The target framework for this project is netcoreapp 3.1. The language version is 8.0.

**Comment by jinujoseph** [comment]
cc @alrz

**Comment by sharwell** [comment]
📝 I removed the link to #47662 because this issue is not related to target-typed new.

**Comment by genlu** [comment]
@devhl-labs I couldn't repro this locally.  Could you please provide a more detailed repro? A sample project would be great. Thanks!

**Comment by devhl-labs** [comment]
https://github.com/devhl-labs/IncorrectAutoCompletion

**Comment by genlu** [comment]
@devhl-labs Thanks!

**Comment by devhl-labs** [comment]
When will we see the fix in Visual Studio?

**Comment by CyrusNajmabadi** [comment]
@devhl-labs From https://github.com/dotnet/roslyn/pull/49773 you can see it will be here:

![image](https://user-images.githubusercontent.com/4564579/102755369-23e41a80-4323-11eb-87ff-b427139888f7.png)
