### ISSUE TITLE
Popup font size for collapsed JavaScript is much smaller than for collapsed CSS & HTML

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Popup-font-size-for-collapsed-JavaScript/1270445)._

---
<p>[severity:It’s more difficult to complete my work]<br>
My editor font (font name, size) and editor zoom percent, are all the same for HTML/CSS and for JavaScript, so why is the popup font size for JavaScript much smaller?  It’s hard for me to read the JavaScript popup. See picture below.</p><p><a href="https://developercommunity2.visualstudio.com/storage/attachments/165025-vs-tinyjavascriptfont.png"> Image:165025-vs-tinyjavascriptfont.png</a></p><p></p>

---
#### Feedback Bot on 11/26/2020, 06:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/30/2020, 10:20 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by uniqueiniquity** [comment]
Looks like the [`BlockTagState`](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/Structure/BlockTagState.cs) hardcodes the zoom.
This impacts C# outlining in Razor files as well, in that the C# hints are similarly mismatched to the HTML hints.

**Comment by sharwell** [comment]
> Looks like the BlockTagState hardcodes the zoom.

It certainly appears this is the cause of the smaller text, which also appears to be intentional. I'm going to tentatively mark it as By Design, but leave it open in case we want to consider a change of some sort.

**Comment by CyrusNajmabadi** [comment]
By design.
