### ISSUE TITLE
Intellicode Global Find/Replace

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#49665]
I love the intellicode quick refactorings.
I love how I can apply them individually or to an entire file.

I would love it if I could do a global find/replace so that I can refactor old patterns into new ones everywhere.

**Comment by markw-t** [comment]
@TonyValenti thanks for raising this. Just to make sure we are talking about the same features, when you refer to IntelliCode quick refactorings, do you mean [IntellICode suggestions](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-suggestions), to which we recently added the ability to [apply-all in a document](https://devblogs.microsoft.com/visualstudio/making-repeated-edits-easier-with-intellicode-suggestions/)? 

I would love to chat in more detail about the potential find/replace experience you are looking for and the sort of scenarios you imagine using it in.   If you can spare some time for an in-person discussion drop me a line at mwthomas at microsoft dot com?

Thanks!
Mark

**Comment by markw-t** [comment]
Following our offline chat @TonyValenti it'd be good to move this to the [IntelliCode repo](https://aka.ms/vsicissues) so we can track it there?
