### ISSUE TITLE
Proposal: Allow single-line namespace directives

### ISSUE THREAD

**Issue by ssg** [dotnet/roslyn#4968]
Problem: namespace scoping braces almost always apply to the whole file yet increase indentation unnecessarily, making the code harder to read than necessary.

Solution: allow source-level single-line namespace declarations. Instead of

    using System;
    namespace Acme.Tools
    {
        public class VeryUseful
        {
             public int FirstMethod()
             {
                 // first line of code starts 12-spaces in
             }
        }
    }

Change namespace directive to:

    using System;
    namespace Acme.Tools; // applies to the whole source file - can't be repeated in the source or mixed with scoped namespace directive

    public class VeryUseful
    {
         public int FirstMethod()
         {
             // first line of code starts 8-spaces in --- better readability
         }
    }

Old behavior will still be supported and new editors/IDEs/authors will take advantage of this. This is not a solution by itself but it certainly helps.

**Comment by RichiCoder1** [comment]
I believe this is a duplicate of https://github.com/dotnet/roslyn/issues/595

**Comment by ssg** [comment]
It is the duplicate #595  weird I tried searching it many times. Thanks!

**Comment by RichiCoder1** [comment]
All good. I only found it so quickly because I remembered vaguely the issue name :)
