### ISSUE TITLE
Runaway memory consumption with build 16.8.0+126527ff1

### ISSUE THREAD

**Issue by ngelotte** [dotnet/roslyn#49686]
### Issue Description
When I am trying to build my project which build just fine on .net Core 3.1 after upgrading visual studio I am getting runaway memory usage. It happens when I run build from visual studio 16.8.2 or using dotnet build. Also, the same problem is occurring on the build agent in azure dev ops. 

### Steps to Reproduce
I can try to collect any logging you need  but I don't know what is unique about my project that is causing this problem. 

### Expected Behavior
Build should complete.

### Actual Behavior
Build never finishes but eventually crashes as the machine is starved of memory.

### Analysis
One of the web projects in the solution succeeds but the second one does not. It does not create any console records but just starts and then the memory start climbing. 

### Versions & Configurations
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

### Attach a binlog
As the process does not complete I have not be able to capture any binlogs. I tried but there is no output.

**Comment by sharwell** [comment]
@cston this is the nullability walker issue you have been tracking

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/49765.

**Comment by cston** [comment]
@ngelotte, thanks for reporting this issue.

**Comment by ngelotte** [comment]
No problem. Let me know if you have a dev build or a release build that I can test with to verify that it is fixed.
Thanks,
Nick

**Comment by cston** [comment]
@ngelotte, sorry for not responding sooner. https://github.com/dotnet/roslyn/pull/49765 was included in 16.8.3.

**Comment by ngelotte** [comment]
I upgraded to 16.8.3 and I can build successfully now. Thanks for resolving this.
