### ISSUE TITLE
Tool or fixer to convert POCO-style class to record

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#49682]
I've been hand-converting POCO-style classes to records. It's not hard, but it is mindless. It would be great if there was an automated way to convert classes to records, including the `///` comments. Is there such a tool? Is there any plans to build one?

For my case, the scenario is nullable reference types. Most POCOs just have a default parameter-less constructor, and then object initializers or property assignment are used to configure the instances. That pattern doesn't play nicely with NRTs. Since you have to do something, I've started converting POCOs to records to satisfy this problem.

**Comment by jinujoseph** [comment]
POCO = Plain old C# object :-)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63654.
