### ISSUE TITLE
IDE0019 automatic fix generates invalid code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49683]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/IDE0019-automatic-fix-generates-invalid-/1264510?preview=true)._

---
[severity:It bothers me. A fix would be nice]
The screenshots show before/after implementation of the IDE0019 code fix.
The issue is that the fix does not consider the scope block outside of the first if-block, resulting in an undefined variable in a new scope after the fix.

---
#### Feedback Bot on 11/23/2020, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/30/2020, 04:05 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue was reported in 16.7.4 on code that looks roughly like this:

```
private void Test(bool path, object value)
{
    string value2 = value as string;
    if (path)
    {
        if (value2 == null)
        {
            Console.WriteLine("A");
        }
    }
    else
        if (value2 != null)
            Console.WriteLine("B");
}
```

IDE0019 was getting reported on the declaration of `value2`.

I am not able to reproduce this in e9fd4dc7, but I was not able to determine if/when it was fixed.

**Comment by CyrusNajmabadi** [comment]
No longer reproes.  Code has moved around a lot and i couldnt' find a clear fixed point.  Howeer, the existing code strongly checks for a tighter pattern than what is shown is above.
