### ISSUE TITLE
Roslyn Semantic Model for Static Constructors does not Match C# Language Spec

### ISSUE THREAD

**Issue by cptjazz** [dotnet/roslyn#4969]
## Abstract

It seems to me, that the semantic model of Roslyn and the ECMA-334 differ when it comes to static constructors.
Please clarify.

## Roslyn and Static Constructors

Roslyn seems to implicitly add a static constructor to a class containing static fields, even if no static constructor was defined in the textual representation of the program. Try the following example. We parse and analyse three classes, the class `OtherStruct` contains a static field but no static constructor. The class `StructWithCCtor` contains a static constructor.

```C#
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoslynTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(
                @"
public class SomeStruct
{
  public void MyMethod(object o) { }
}

public class OtherStruct 
{ 
  public static readonly string Field = " + "\"Test\"" + @";
  
  public void MyOtherMethod(object o) { }
}

public class StructWithCCtor
{
  static StructWithCCtor() { }

  public void YetAnotherMethod(object o) { }
}
");

            var asts = new[] {syntaxTree};
            var compilation = CSharpCompilation.Create("MyCompilation", asts, new MetadataReference[0]);
            
            var model = compilation.GetSemanticModel(syntaxTree);
            
            var allStructSymbols = syntaxTree.GetRoot()
                .DescendantNodes()
                .OfType<ClassDeclarationSyntax>()
                .Select(x => model.GetDeclaredSymbol(x));

            foreach (var symbol in allStructSymbols)
            {
                Console.WriteLine(
                    $"Class '{symbol.Name}' static constructor count = {symbol.StaticConstructors.Length}");
            }
        }
    }
}
```

The program outputs:

> Class 'SomeStruct' static constructor count = 0
> Class 'OtherStruct' static constructor count = 1
> Class 'StructWithCCtor' static constructor count = 1

The static constructor for `OtherStruct` is unexpected, but one _could_ argue that adding an empty static constructor is a valid program transformation as it does not introduce different behaviour.

## What is the Problem?

ECMA-334 §17.4.5.1 describes static field initialization:
> If a static constructor (§17.11) exists in the class, execution of the static field initializers occurs immediately prior to executing that static constructor. Otherwise, the static field initializers are executed at an implementation-dependent time prior to the first use of a static field of that class.

That means it _does_ make a difference if we add an empty static constructor.
Try the following example first in *Debug configuration* and then in *Release configuration*. The Debug configuration outputs two initialisation lines---as expected. In the Release configuration some optimisation kicks in, and the "implementation-dependent time" can be noticed: it only outputs the line for `MyClassWithCCtor`.

```C#
using System;

namespace RoslynTest
{
    public class TracerClass
    {
        public TracerClass(string s)
        {
            Console.WriteLine($"{s} was created");
        }
    }

    public class MyClass
    {
        public static readonly TracerClass X = new TracerClass("X in MyClass");
    }

    public class MyClassWithCCtor
    {
        public static readonly TracerClass Y = new TracerClass("Y in MyClassWithCCtor");

        static MyClassWithCCtor() { }
    }

    public class TestProgram
    {
        public static void Main(string[] args)
        {
            var x = new MyClass();
            var y = new MyClassWithCCtor();
        } 
    }
}
```

## The Actual Question
Is the behaviour of Roslyn intended? If so, why does the *semantic* model have different semantics than the language?

**Comment by MrJul** [comment]
Fields initializers without an explicit static constructor *are* compiled to a static constructor (and the class is marked with `beforefieldinit`, as you noted). So Roslyn is correct, and that's not the only symbol created by the compiler you'll find in the semantic model.

If you want to disambiguate between an user-written constructor and a compiler-generated one, use `IsImplicitlyDeclared`.

That said, the spec is respected: the input produces the correct output, I don't really see what an intermediate representation of the code has to do with the specification.

**Comment by gafter** [comment]
@cptjazz Does @MrJul's response answer your question?

**Comment by cptjazz** [comment]
Thank you for the response.
I was not aware that Roslyn distinguishes between implicitly and explicitly implemented cctors.
It is now clear to me how this case is handled and I was able to get my code analyser right.

Thanks for the fast help!
