### ISSUE TITLE
SymbolEqualityComparer.IncludeNullability when is it equal?

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/roslyn#49699]
I'm not sure I understand the following centens:

> Compares two ISymbol instances, considering their nullability

Does this means `int?` and `int` will be equals even through the first is `Nullable<Int32>` and the second is `Int32`.
Or does it will distinct `string?` and `string` which would normally be equals?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8025f2b8-13c6-0fbe-a04b-a5bef15866f4
* Version Independent ID: 8b793d4e-0ea1-e644-e382-7b129bb914cd
* Content: [SymbolEqualityComparer.IncludeNullability Field (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.symbolequalitycomparer.includenullability?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/SymbolEqualityComparer.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/SymbolEqualityComparer.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Moved from [dotnet/docs](https://github.com/dotnet/docs). This should be fixed in the `///` comments.
