### ISSUE TITLE
Solution-wide code fixes take around two minutes to collect no matter which fix it is

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Solution-wide-code-fixes-take-around-two/1272947)._

---
[severity:It bothers me. A fix would be nice]
Most solution-wide code fixes take a couple of minutes to gather when you click "Fix all occurrences in... Solution." It seems like it takes the same amount of time no matter what the code fix is. It's unpleasantly long.

Two or three *seconds* would fit my expectations better since all the occurrences have been collected already and are showing in the Error List window.

If I select "Fix all occurrences in... Document," my stopwatch says it takes 20 seconds to find the one occurrence in a 170-line file.

---
#### jnm2 on 11/30/2020, 03:02 PM: 

<p>My “two minutes” is actually 1m11s when I use a stopwatch. “Fix all in document” and “…project” both take 20 seconds on my stopwatch in a 170-line file.</p>

#### Feedback Bot on 11/30/2020, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/1/2020, 00:04 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Working on a fix...
