### ISSUE TITLE
Generic extension method call as method group fails

### ISSUE THREAD

**Issue by dvas-dubna** [dotnet/roslyn#4970]
Copy and paste this code:
```csharp
public interface IDetail<T>
{

}

public interface IMaster<T>
{

}

public class MyClass
{
    public void method()
    {
        Principal aPrincipal = new Principal();
        aPrincipal.Permissions.Foreach(aPrincipal.RemoveDetail); 
    }
}

public class Permission : IDetail<Principal>
{

}

public class Principal : IMaster<Permission>
{
    public virtual IEnumerable<Permission> Permissions { get; }
}

public static class Class
{
    public static void RemoveDetail<TMaster, TChild>(this TMaster master, TChild child)
        where TMaster : class, IMaster<TChild>
        where TChild : class, IDetail<TMaster>
    {

    }

    public static void Foreach<T>(this IEnumerable<T> source, Action<T> action)
    {

    }
}
```
`aPrincipal.Permissions.Foreach(aPrincipal.RemoveDetail); ` is a method group call converted from lambda expression call `aPrincipal.Permissions.Foreach(x => aPrincipal.RemoveDetail(x));`
Both worked fine in VS'13 and earlier but in VS'15 method group call fails on compilation saying
>'Principal' does not contain a definition for 'RemoveDetail' and no extension method 'RemoveDetail' accepting a first argument of type 'Principal' could be found (are you missing a using directive or an assembly reference?)

However if we remove `where TMaster : class, IMaster<TChild>` constraint from method signature it works.

**Comment by gafter** [comment]
We should **investigate** this for 1.1.

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
