### ISSUE TITLE
VB.Net editor fails to use variables in for text width in String interpolation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49712]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VBNet-editor-fails-to-use-variables-in-/1265067)._

---
[severity:It bothers me. A fix would be nice]
I tried a piece of code that works perfectly in C# but not in VB.Net
C# version
! [image.png] (https://aka.ms/dc/image?name=Ba041939db5224da98d2a608d2caa8396637416755140267327_20201122-225832-image.png&tid=a041939db5224da98d2a608d2caa8396637416755140267327)
VB.net version using PadLeft(), you will notice that Visual Studio gives me a tip to simplify the usage of PadLeft()
! [image.png] (https://aka.ms/dc/image?name=B89a9aff59ed14810b0b1a5137a2f5af1637416757412823911_20201122-230219-image.png&tid=89a9aff59ed14810b0b1a5137a2f5af1637416757412823911)
when I follow its advice, I get a compiler error. Somehow the editor forces a "0" before the usage of the constant in the interpolated string

! [image.png] (https://aka.ms/dc/image?name=B0214be849f984f999e4ba253777f93e1637416759153851472_20201122-230513-image.png&tid=0214be849f984f999e4ba253777f93e1637416759153851472)
So it seems the VB.net editor does not comprehend using constants or variables in this place. Please check.

---
#### Feedback Bot on 11/22/2020, 08:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/30/2020, 04:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
> VB.net version using PadLeft(), you will notice that Visual Studio gives me a tip to simplify the usage of PadLeft()
> When I follow its advice, I get a compiler error. Somehow the editor forces a "0" before the usage of the constant in the interpolated string

Seems like a VisualBasic bug in IDE0071 - Interpolation can be simplified. Tagging @jnm2.
