### ISSUE TITLE
insert space within parentheses of expression not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49715]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/insert-space-within-parentheses-of-expre/1218368)._

---
[severity:It bothers me. A fix would be nice]
Hello,

This issue bothers me long time ago!
The option "Insert space within parentheses of expression" not working.
I HATE to see var z = ( x * y ) - ( ( y - x ) * 3 ), but I can't turn it off!

Could you please fix this issue for me?
Thank you so much,
Huy Nguyen

---
#### Feedback Bot on 10/13/2020, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2020, 10:22 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
@sharwell is this a formatting feature request/bug?

**Comment by PathogenDavid** [comment]
I'm wondering if they have an editorconfig they don't know about. Visual Studio doesn't make it especially obvious when an editorconfig is overriding your preferences.

**Comment by sharwell** [comment]
@mavasani we already have a code style option to support this, so either it's not working as expected or the configuration is being overridden by a **.editorconfig**.

**Comment by jmarolf** [comment]
![formatting_expression](https://user-images.githubusercontent.com/9797472/105105225-833f6280-5a68-11eb-8760-b9694d89dad8.gif)

 I am unable to reproduce this. If original filer can add more information about what causes this I would be delighted to investigate.

**Comment by egonguyen** [comment]
Hello,

Could you please help me to turn this function off (insert space within parentheses of expression) by configs below.
I don't know what configuration to do that.
(my project is using a .editorconfig file)

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019#spacing
# Space preferences
csharp_space_after_cast = false
csharp_space_after_colon_in_inheritance_clause = true
csharp_space_after_comma = true
csharp_space_after_dot = false
csharp_space_after_keywords_in_control_flow_statements = true
csharp_space_after_semicolon_in_for_statement = true
csharp_space_around_binary_operators = before_and_after
csharp_space_around_declaration_statements = false
csharp_space_before_colon_in_inheritance_clause = true
csharp_space_before_comma = false
csharp_space_before_dot = false
csharp_space_before_open_square_brackets = false
csharp_space_before_semicolon_in_for_statement = false
csharp_space_between_empty_square_brackets = false
csharp_space_between_method_call_empty_parameter_list_parentheses = false
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_call_parameter_list_parentheses = false
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false
csharp_space_between_method_declaration_name_and_open_parenthesis = false
csharp_space_between_method_declaration_parameter_list_parentheses = false
csharp_space_between_parentheses = false
csharp_space_between_square_brackets = false

Thank you so much.
