### ISSUE TITLE
DocumentationCommentId.GetXXX should ignore whitespaces

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#49726]
**Brief description:**

It might be good to even open a Roslyn compiler feature request to enhance the following public APIs on `DocumentationCommentId` to ignore redundant whitespaces:

1. [DocumentationCommentId.GetSymbolsForDeclarationId](https://github.com/dotnet/roslyn/blob/d66c12164c0da3841f86b165872ea1b55942c575/src/Compilers/Core/Portable/DocumentationCommentId.cs#L82-L85)
2. [DocumentationCommentId.GetFirstSymbolForDeclarationId](https://github.com/dotnet/roslyn/blob/d66c12164c0da3841f86b165872ea1b55942c575/src/Compilers/Core/Portable/DocumentationCommentId.cs#L133-L136)
3. [DocumentationCommentId.GetSymbolsForReferenceId](https://github.com/dotnet/roslyn/blob/d66c12164c0da3841f86b165872ea1b55942c575/src/Compilers/Core/Portable/DocumentationCommentId.cs#L160-L163)
4. [DocumentationCommentId.GetFirstSymbolForReferenceId](https://github.com/dotnet/roslyn/blob/d66c12164c0da3841f86b165872ea1b55942c575/src/Compilers/Core/Portable/DocumentationCommentId.cs#L216-L219)

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/issues/4473#issuecomment-736628318_

**Languages applicable:**

I think it should apply to both.

**Code example that the analyzer should report:**

The following example doesn't work:
`M:System.Threading.Tasks.Task.Delay(System.Int32, System.Threading.CancellationToken)`
While this one works:
`M:System.Threading.Tasks.Task.Delay(System.Int32,System.Threading.CancellationToken)`

**Comment by Youssef1313** [comment]
@Evangelink Should spaces be **completely** ignored? or only after commas?

**Comment by Evangelink** [comment]
I am not sure if there are cases where the space are meaningful in the ID definitions, reading the doc I could not really find any example where it would be. Best would be to be able to see specs or get confirmation from someone in the roslyn team if there is any case where it would make sense not to get rid of the spaces.

**Comment by Youssef1313** [comment]
@Evangelink ignoring all spaces would lead to something like `M:System.Threading.Tasks.Task.Delay(System.Int32,System.Threading.Canc   el l ationToken)` being accepted, which feels odd I think. I'll give another look for another approach and also only ignore spaces that comes after a comma.

**Comment by mavasani** [comment]
@Evangelink @Youssef1313 We should first get a confirmation from @dotnet/roslyn-compiler team if they feel this is an acceptable change.

**Comment by sharwell** [comment]
My preference would be to require the input have the correct form (i.e. the current behavior is correct; there is no symbol with a documentation comment ID with a space in that location).

**Comment by 333fred** [comment]
Looking at the linked bug, I'm not certain that this is a good change. Spaces are just one of several ways that a doc comment id could be bad: it could refer to a non-existent member, for example. Meanwhile, doc comment ids do not specify that spaces should be accepted, and implementing the ability to accept them in one context just means that any other context that does not accept them will be broken in this same way when something that works for roslyn is used somewhere else. I think the better solution is to implement validation in the analyzer, which will provide a better experience for all issues, not just extraneous whitespaces.

**Comment by 333fred** [comment]
I'm going to close this as by-design. If someone else from @dotnet/roslyn-compiler wants to reconsider, we can reopen then.
