### ISSUE TITLE
Solution Explorer "Derived Types" missing some derived types

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#4973]
1. Open Roslyn.sln in VS.
2. Navigate to [PreviewWorkspace](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Preview/PreviewWorkspace.cs,aa6ee406a52b5a53,references) type node in Solution Explorer.
3. Right click and choose "Derived Types"

**Expected**: It should find [```PreviewDialogWorkspace : PreviewWorkspace```](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Preview/PreviewUpdater.PreviewDialogWorkspace.cs,4b37df9c924a4540)
**Actual**: No derived types found.

**Comment by dpoeschl** [comment]
FYI @brettfo

**Comment by brettfo** [comment]
As a note to myself, @amcasey was seeing similar behavior when searching for types that implement `IDocumentSupportsSuggestionsService`; not all types were showing up.

**Comment by Pilchie** [comment]
This was also the case for `Microsoft.CodeAnalysis.Editor.UnitTests.QuickInfo.AbstractSemanticQuickInfoSourceTests. (@amcasey again)

**Comment by DustinCampbell** [comment]
Is #7164 awaiting anything here? Looks like this is ready to go?

**Comment by brettfo** [comment]
@DustinCampbell: The last time I looked at this I was seeing some issues around detecting an assembly's strong naming.  I'll rebase onto a current SHA and see if that's still a problem.

**Comment by brettfo** [comment]
@DustinCampbell: Thanks for the heads up; the signing issues have been resolved and I've updated the PR against a current SHA.

**Comment by Pilchie** [comment]
Closing, since this was fixed in stabilization by #9056.
