### ISSUE TITLE
NormalizeWhitespace corrupts, invalidates xml doc comments when xml tags have namespaces

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49732]
**Version Used**: Microsoft.CodeAnalysis.CSharp 3.8.0

**Steps to Reproduce**:

Use `ParseLeadingTrivia` on a string such as this:

```cs
/// <returns>
/// If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>.
/// </returns>
```

Then use`NormalizeWhitespace` on the overall `CompilationUnitSyntax`.

**Expected Behavior**:

A C# file with a valid xml doc comment

**Actual Behavior**:

I end up with xml in the generated .cs file such as this::

```cs
/// <returns>
/// If this method succeeds, it returns <b xmlns: loc = "http://microsoft.com/wdcml/l10n">S_OK</b>.
/// </returns>
```

Note the added space between `xmlns:` and `loc`. This is enough to break xml parsing and causes the C# lang svc to altogether throw out the entire leading trivia so that no xml doc comment for that member shows up in Intellisense.

Now, of course we can ask why the namespaced tag. It's an artifact of the scraping we're doing of other documentation in order to apply it to APIs for showing up in Intellisense. We want to clean these up over time. But in the meantime, I think we can all agree that `NormalizeWhitespace` should not introduce parsing errors.

**Comment by Youssef1313** [comment]
This should be handled here:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L390-L393

**Comment by sharwell** [comment]
Moving back to compilers, as this regards `NormalizeWhitespace` as opposed to the formatter APIs.
