### ISSUE TITLE
Avoid sharing NullableWalker state between containing method and lambdas and local functions

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#49745]
When analyzing a method in `NullableWalker`, avoid sharing `_variableTypes` and `_variableSlots` between that method and any lambdas or local functions. If there are many nested functions, as there might be in generated code, adding entries in the tables for the containing method for parameters and local functions from the nested functions can significantly increase the amount of state that needs to be tracked.

See https://github.com/dotnet/roslyn/issues/49686.

cc @RikkiGibson

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/49765.

**Comment by RikkiGibson** [comment]
Is this issue meant to track the work to improve the data design for nullable analysis of nested functions?

**Comment by cston** [comment]
> Is this issue meant to track the work to improve the data design for nullable analysis of nested functions?

Yes.
