### ISSUE TITLE
rename refactoring synchronization breaks after a few deletions

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/roslyn#49742]
**Version Used**: This is with SDK 5.0.100

**Steps to Reproduce**:

1. Use a long variable name multiple times in a method, e.g.
```cs
public void Foo()
{
   var this_is_an_unusually_long_variable_name = new object();
   if (this_is_an_unusually_long_variable_name == null)
   {
      this_is_an_unusually_long_variable_name = new object();
   }
   this_is_an_unusually_long_variable_name = null;
   this_is_an_unusually_long_variable_name = new object();
   this_is_an_unusually_long_variable_name = null;
   // this is all rather pointless. I just use the variable a few times, that's the only point of it.
}
```
2. Rename-refactor the variable name to something more sensible by deleting characters one at a time
3. At about the fifth deletion, the synchronization between all variable usages breaks and only the one at the current cursor position gets renamed. All the others now are not named the same.

**Expected Behavior**:

Synchronization should remain no matter how many characters are deleted.

**Actual Behavior**:

Synchronization breaks.

**Comment by stefanloerwald** [comment]
It's even difficult for me to reproduce it... Here's the closest to the problem I can share without breaking confidentiality:
```cs
    public class Bar
    {
        public async Task Baz<T1, T2>()
        {
            var hello_this_is_a_long_variable_name = await default(IAReallyLongLongNameOfAnApi).GetAsync<T1, T2>();
            if (hello_this_is_a_long_variable_name == null)
            {
                return;
            }
            if (hello_this_is_a_long_variable_name != null)
            {
                await foo.DoSomethingAsync(hello_this_is_a_long_variable_name);
                await bar.DoSomethingAsync(hello_this_is_a_long_variable_name, "");
            }
        }
    }
```

**Comment by CyrusNajmabadi** [comment]
Closing as this was fixed.
