### ISSUE TITLE
Only run nullable analysis on methods defined in a nullable-enabled context

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#49746]
Avoid running `NullableWalker` on methods that are not in a nullable-enabled context.

See https://github.com/dotnet/roslyn/issues/49686.

cc @333fred, @RikkiGibson

**Comment by RikkiGibson** [comment]
Methods which do not have `#nullable enable warnings` context at any point should not be analyzed by NullableWalker.

Importantly, this means that generated code which has a `#nullable enable annotations` directive should not be analyzed by NullableWalker. When we make this change we should make sure to provide guidance to generator authors that such a directive, and not a plain `#nullable enable` directive, is the best way for a production code generator to provide nullability info to consumers.

**Comment by cston** [comment]
Fixed in #49953.
