### ISSUE TITLE
error CS0266 after pattern matching

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49740]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/error-CS0266-after-pattern-matching/1273585)._

---
I had this line:
```
if (ch < ' ' || ch >= 0x100)
```
After "Use pattern matching" (IDE0078) refactoring it changed to:

```
if (ch is < ' ' or >= 0x100)
```
I got error CS0266: Cannot implicitly convert type 'int' to 'char'. An explicit conversion exists (are you missing a cast?)

---
#### Feedback Bot on 12/1/2020, 06:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@alrz ?

**Comment by alrz** [comment]
Sniped.
