### ISSUE TITLE
The type of C# 9 function pointer invocation operation is None

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn#49751]
**Version Used**: 3.8.0

**Steps to Reproduce**:

1.
```
static readonly delegate* unmanaged<int> pointerBasedFactory;
static int CreatePointerBasedFactory() => pointerBasedFactory();
```
2. Get `IOperation` for `pointerBasedFactory()`

**Expected Behavior**:
`IOperation.Kind` should be `Invocation` or some other sensible value

**Actual Behavior**:
`IOperation.Kind` is `OperationKind.None`

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/48082
