### ISSUE TITLE
csc takes far too long to compile 47MB of source code

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#49769]
**Version Used**: csc /version: 3.9.0-2.20574.26 (e9fd4dc7)

**Steps to Reproduce**:

Unzip and compile [the attached source code](https://microsoft-my.sharepoint.com/:u:/p/andarno/Ee0CUIQgJ4JJmfrkwnN1t80BhrJuqtKB9RGpxHTFzKFNGQ?e=KzqdRY) as a library.

**Expected Behavior**:

Compiler should take ~1 minute to compile.

**Actual Behavior**:

Compiler takes much longer. (it's been running for 35 minutes at 100% CPU on a 16 Core 4GHz machine, and still going)

[ETL trace](https://microsoft-my.sharepoint.com/:u:/p/andarno/EZz9iCZebAZGoG7k2FUy2aUBajqTyafhOWngEL8qg1xJYA?e=3sOW4Q)

**Comment by sharwell** [comment]
This issue is occurring due to an O(n²) (or possibly worse) algorithm in the analyzer driver.

The following code attempts to get the symbol for a namespace:

https://github.com/dotnet/roslyn/blob/793e757500b311071d09ecf92af967a45090d5f2/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L1363-L1364

This ends up calling into this code, which loops over every location where a part of the namespace is defined:

https://github.com/dotnet/roslyn/blob/793e757500b311071d09ecf92af967a45090d5f2/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L1799-L1801

**Comment by mavasani** [comment]
@sharwell Your above note points to issue/optimization in the compiler code, but does not point to any specific piece in analyzer driver that needs optimization. Are you suggesting this needs a fix in semantic model code or analyzer driver? If the latter, can you please provide additional details?

**Comment by sharwell** [comment]
@mavasani The fix could go in either location:

* The semantic model could be updated to avoid looking at all namespace parts when obtaining the symbol
* The analyzer driver could be updated to avoid calling `GetDeclaredNamespace(NamespaceDeclarationSyntax)` for each `NamespaceDeclarationSyntax`

**Comment by sharwell** [comment]
I'm working on a benchmark for `GetNamespaceSymbol`. So far, I'm a bit surprised that the penalty for the call doesn't appear to be affected much:

```
|             Method | Count |  File |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------- |------ |------ |---------:|----------:|----------:|------:|------:|------:|----------:|
| GetNamespaceSymbol |     2 | First | 1.883 ms | 0.0517 ms | 0.1518 ms |     - |     - |     - |     600 B |
| GetNamespaceSymbol |     2 |  Last | 1.702 ms | 0.0226 ms | 0.0176 ms |     - |     - |     - |     596 B |
| GetNamespaceSymbol |    10 | First | 1.667 ms | 0.0244 ms | 0.0204 ms |     - |     - |     - |     604 B |
| GetNamespaceSymbol |    10 |  Last | 1.721 ms | 0.0246 ms | 0.0230 ms |     - |     - |     - |     604 B |
| GetNamespaceSymbol |   100 | First | 1.696 ms | 0.0212 ms | 0.0177 ms |     - |     - |     - |     612 B |
| GetNamespaceSymbol |   100 |  Last | 1.924 ms | 0.0533 ms | 0.1530 ms |     - |     - |     - |     612 B |
| GetNamespaceSymbol |  1000 | First | 1.972 ms | 0.0734 ms | 0.2153 ms |     - |     - |     - |     620 B |
| GetNamespaceSymbol |  1000 |  Last | 1.986 ms | 0.0481 ms | 0.1372 ms |     - |     - |     - |     612 B |
| GetNamespaceSymbol | 10000 | First | 1.709 ms | 0.0310 ms | 0.0259 ms |     - |     - |     - |     624 B |
| GetNamespaceSymbol | 10000 |  Last | 3.810 ms | 0.1260 ms | 0.3716 ms |     - |     - |     - |     631 B |
```
