### ISSUE TITLE
Quick Info should clearly separate the remarks from the summary in the rendering when a remarks tag is present

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49772]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Quick-Info-should-clearly-separate-the-r/1094354)._

---
In the current rendering, it is currently impossible to tell the difference between these XML comments:
/// &lt;summary&gt;
/// Line 1.
/// &lt;para/&gt;Line 2.
/// &lt;/summary&gt;

and these XML comments:
/// &lt;summary&gt;
/// Line 1.
/// &lt;/summary&gt;
/// &lt;remarks&gt;
/// Line 2.
/// &lt;/remarks&gt;

My suggestion: when a &lt;remarks&gt; tag is present, use a &quot;Remarks:&quot; separator line in the rendering, similar to the &quot;Returns:&quot; separator line used when a &lt;returns&gt; tag is present.

Current version is 8.6.5 (build 23).

---
#### Feedback Bot on 6/29/2020, 02:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/30/2020, 02:25 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### May Lei [MSFT] on 11/3/2020, 03:48 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ? If yes or not, please feel free to let us know.</p>

#### Feedback Bot on 11/10/2020, 10:27 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### didier.prgomet on 11/21/2020, 05:46 AM: 

<p>Hello May Lei,</p><p>I've recently installed v8.8 (build 2913) and then v8.8.1 (build 37) and Quick Info still renders a &lt;remarks&gt; section just like a &lt;summary&gt; section, so you still can't tell where the &lt;summary&gt; section ends and where the &lt;remarks&gt; section starts, which is not welcome, as they provide different kinds of information.</p><p>Note that this issue is also present in Visual Studio 2019 (on Windows). I've double checked this in v16.7.7.</p><p>My suggestion remains the same: when a &lt;remarks&gt; tag is present, use a "Remarks:" separator line in the rendering, similar to the "Returns:" separator line used when a &lt;returns&gt; tag is present.</p><p>Best regards,</p><p>Didier Prgomet</p>

#### Feedback Bot on 12/3/2020, 01:38 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This was considered as part of https://github.com/dotnet/roslyn/pull/42135#issuecomment-594539136, and we decided to include the designator for `<returns>` but treat `<remarks>` as just a separated paragraph.
