### ISSUE TITLE
Name IntelliSense is showing by default

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#49791]
**Version Used**: 30730.222.main

**Steps to Reproduce**: 

1.	Clone my repo (https://devdiv.visualstudio.com/DefaultCollection/Personal/_git/dpugh)
2.	Open the TimeTravelEditing project.
3.	Within that project, open SnapshotManager.cs.
4.	Insert a blank line before line 27.
5.	On the (new) line 27, type _rootPath<space> You may get completion for the initial _rootPath (which you can dismiss or accept via tab/space).

**Expected Behavior**:
No IntelliSense is shown.

**Actual Behavior**:
The variable name completion will appear as soon as you type the space (and, if you used space to accept the 1st completion, then you’ll immediately get the 2nd).

![image](https://user-images.githubusercontent.com/201340/101204209-bc3e8780-3620-11eb-8ebf-1d00c8266fc7.png)

**Comment by jasonmalinowski** [comment]
@dpugh reached out via email on this: as best I can tell the completion list contents are expected -- technically in that case you could be declaring a variable. The odd part is it's auto-triggering.

**Comment by genlu** [comment]
Not sure what the expect behavior is here. As @jasonmalinowski mentioned, it's possible _rootPath is a type you want to declare lter (via refactoring, see screenshot below), and this might be the best guess given the context. Also, since it's in suggestion mode, it shouldn't cause disruption to your typing.

![image](https://user-images.githubusercontent.com/788783/108890559-95aa4000-75c2-11eb-9036-a30adcf57460.png)

**Comment by CyrusNajmabadi** [comment]
> technically in that case you could be declaring a variable. The odd part is it's auto-triggering.

In the case of an *unbound* identifier that is *also not Capitalized* i think we shoudl suppress and not consider this a name completion scenario.  It seems highly unlikely that this would ever be what the user wanted.

Note: if the lowercase identifier does bind to a type, then we can of course proceed.  Or, if the name is capitalized, that strongly indicates it may be a type without an appropriate using.  However, unbound *and* lowercase is a strong enough signal that this is *not* a type to me.

**Comment by CyrusNajmabadi** [comment]
@genlu if this is cheap to do, could you make such a change?

**Comment by sharwell** [comment]
@CyrusNajmabadi I'm not sure it makes sense to penalize teams just for using a different naming convention here.

**Comment by CyrusNajmabadi** [comment]
It does.  We've talked about this in LDM.  Lowercase type names are not a viable naming strategy.  Our own anlysis of the ecosystem is that it's literally the 0.0001% case (or less).  We shouldn't harm the 99.999% case for that literal single case out there.

**Comment by genlu** [comment]
@CyrusNajmabadi We sure can add a check to avoid showing completion in case the identifier doesn't bound to a type. However, given we are in suggestion mode here, I don't really see current behavior as a problem. I mean, what are you gonna type in the example above after typing a whitespace?

**Comment by CyrusNajmabadi** [comment]
> However, given we are in suggestion mode here, I don't really see current behavior as a problem

It's somewhat problematic to me because it's a very noisy scenario, and the completion list popping up and the disappearing is distracting (i've noticed it myself).  It's not very high pri.  But i think it would be nice to do.

**Comment by jasonmalinowski** [comment]
Regarding the question about naming conventions: how hard is it to ask our naming convention code whether the name matches the defined convention, if there is one? If it's not trivial then I'm totally OK with @CyrusNajmabadi's proposed heuristic, but I would have hoped our naming conventions code made things like this easy in the first place.

**Comment by CyrusNajmabadi** [comment]
Sure.  we can ask naming conventions as well.  but honestly... come on guys.  Lowercase naming convention on types?  It's a non-scenario.  We're not the compiler here trying to have to maintain support for all pathological cases.
