### ISSUE TITLE
[Proposal] Compile time inheritance aka includes for reducing code duplication

### ISSUE THREAD

**Issue by AqlaSolutions** [dotnet/roslyn#4980]
Very often we have the same properties for entity on multiple application layers so we have to copy them here and there or break layering and access underlying entities directly. What if we could specify a single source for such cases?

I would like to have a possibility to keep members in one place. And the same for structs!

Example:

    class UserDataMinReadOnly
    {
        public virtual int Id { get; protected set; }

        public virtual string Nickname { get; protected set; }
    }

    class UserDataMin
        includes UserDataMinReadOnly
    {
        // protected to public change!
        public virtual int Id { get; set; }

        public virtual string Nickname { get; set; }
    }

    class UserDataExtension
    {
        public virtual string GameCenterId { get; set; }

        public virtual long? FacebookId { get; set; }

        public virtual int TotalPlayTimeS { get; set; }

        public virtual int HighestDamageDealt { get; set; }

        public string Country { get; set; }
    }

    class UserDbEntity // should not have nested objects except relational references
        includes UserDataMin, UserDataExtension
    {
    }

    class UserShortInfoDbEntity // should not have nested objects except relational references
        includes UserDataMin
    {
        public virtual int Score { get; set; }
    }

    class UserLogicLayer // we don't want to allow users write directly to db entities
        //includes UserDataMinReadOnly
    {
        void Initialize()
        {
            // Id = ...
        }

        void RegisterFacebook(long facebookId)
        {
            // ...
        }
    }

    [NetworkEvent] // what if nested objects can't be serialized?
    class NetworkUserDataEvent : NetworkEvent
        includes UserDataMinReadOnly
    {
         public override byte EventCode => 0;
    }

When compiling included members should be statically copied to their destination classes.

So, what do you think?

**Comment by AqlaSolutions** [comment]
May be "includable" types should be especially marked with attribute or keyword in order to be allowed for inclusion.

**Comment by gafter** [comment]
This is a dup of #60, admittedly using completely different words.
