### ISSUE TITLE
Visual Basic. Net Compiler Crashed while compiling to application

### ISSUE THREAD

**Issue by Barthdry** [dotnet/roslyn#49810]
**Version Used**: 
**Visual Studio 2019 (16.8.2)**
After debugging and running the project in visual basic. net. I added an icon and pressed compile to application. The Vb compiler has failed to create a application and crashes

**Expected Behavior**:
To Compile to Application.
**Actual Behavior**:
Crashing of the compiler

**Comment by Youssef1313** [comment]
Can you provide a repro project?

**Comment by Barthdry** [comment]
Not yet put into github

**Comment by jaredpar** [comment]
Can you provide us a copy of the crash dump then? Or possible a file that you think is responsible for the crash?

As written there is nothing we can do about this bug report because we don't have anything to look at. If you can help us out here we'd love to fix this problem.

**Comment by jaredpar** [comment]
Closing due to lack of more information.
