### ISSUE TITLE
[Proposed feature] Improve optional parameter default value supporting implicit

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#4982]
Using the following class:
class C
{
    public static implicit operator C(int i)
    {
        return null;
    }
}

I would like to be able to use this method:
void Foo(C c = 0)
{
}

Currently I have the following error:
Error CS1750    A value of type 'int' cannot be used as a default parameter because there are no standard conversions to type 'C'

**Comment by paulomorgado** [comment]
Aren't optional arguments default values constants? Is it a constant if an implicit conversion is involved?

**Comment by MatthieuMEZIL** [comment]
@paulomorgado : Yes default values must be constants but even if an implicit conversion is involved, I guess 0 is still a constant and caller can use 0. So it might be possible IMHO.

**Comment by tmat** [comment]
We would likely need a new attribute that encodes the value of 0. The default value encoded in metadata for the parameter would need to be null to match the type of the parameter.

**Comment by paulomorgado** [comment]
But @MatthieuMEZIL, according to your code, the default value of the parameter would be `null`.

**Comment by MatthieuMEZIL** [comment]
@paulomorgado in this stupid example yes but I would like to use a more interesting implicit using a new C.

@tmat To do what I'm asking for, I think C# compiler needs to be able to use 0 in metadata even if the parameter is not numeric (if there is an implicit int conversion).

**Comment by tmat** [comment]
@MatthieuMEZIL That would not be CLS compliant:

"Type [of the constant] shall match exactly the declared type of the Param, Field, or Property identified by Parent (in the case where the parent is an enum, it shall match exactly the underlying type of that enum). [CLS]"

Doing this might break some tools that don't expect the type to be different.

**Comment by paulomorgado** [comment]
Frankly, @MatthieuMEZIL, what you are asking for has been on the C# from the very beginning. It's called method overloading:

    void Foo()
    {
        Foo(0);
    }

    void Foo(C c)
    {
        // ...
    }

An implicit or explicit conversion is a run time concept and you are asking the compiler to do it at compile time. What if the conversion is based on the thread culture? How can that be hardcoded in the call site?

**Comment by MatthieuMEZIL** [comment]
@paulomorgado : It's more complex than this. I'm working on a framework refactoring task and I want to transform an enum to a class without breaking callers. (My team assume that developers don't use reflection on this enum or Enum class and if so it's acceptable to break them).
S
ome callers use an int as default enum parameter value.
So except if you know how to add overloads on million of code that we don't host, overloads won't be very useful IMHO...

**Comment by HaloFour** [comment]
@MatthieuMEZIL Such a change is by definition a breaking change as the contract for the method will be different.  Any implicit conversion, even if it were possible, would need to be done in the callers, not the callee, but any existing compiled code would still be pushing the enum value onto the stack and attempting to call this function.  Either your callers are going to have to change/recompiled  or you'll have to keep the enum around, define a new class and define overloads or an implicit conversion.  Your use case doesn't seem very compelling for a new language feature, especially one that violates CLS and the metadata expectations for the optional parameter value.

**Comment by MatthieuMEZIL** [comment]
@HaloFour : It won't happen in my case because I work in a very special scenario where I'm just using the C# compiler. Sorry to not be more explicit BTW.

**Comment by paulomorgado** [comment]
You already know my opionon on this, @MatthieuMEZIL. If you are running into trouble because you are using optional arguments instead of overloads, then you deserve that trouble. :smile:

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
