### ISSUE TITLE
Error list errors (examples: CS0006 or XDG0062) opens the browser to bingdev.cloudapp.net but edge blocks it as "not private"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49829]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-list-errors-examples:-CS0006-or-X/1278425)._

---
[severity:It's more difficult to complete my work]
Error list errors open the browser to a URL that Edge considers "not private" so it shows errors

! [image.png] (https://aka.ms/dc/image?name=B3652131e4edd4bf68952208bb7fc9b2f637427017307413798_20201204-100210-image.png&tid=3652131e4edd4bf68952208bb7fc9b2f637427017307413798)

---
#### Feedback Bot on 12/6/2020, 11:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
There are 2 issues here:

1. `bingdev.cloudapp.net` is having an expired certificate.
2. The compiler diagnostic doesn't use the F1 service.

The second one was already fixed.
But the first issue is still valid as the bindev link would still be used in some scenarios. But it's external (unless Bing has a new link/API to use)

**Comment by jinujoseph** [comment]
There is a external issue filed for this and should be fixed soon

**Comment by jasonmalinowski** [comment]
The bingdev.cloudapp.net issue has already been mitigated so that should be fine again.
