### ISSUE TITLE
Why does DiagnosticAnalyzer.RegisterSymbolStartAction(...) not accept SymbolKind array?

### ISSUE THREAD

**Issue by Denis535** [dotnet/roslyn#49857]
I'm learing `DiagnosticAnalyzer` and I wonder one thing: why does `RegisterSymbolStartAction` not accept `SymbolKind` array but `RegisterSymbolAction` does?

What if I want to subscribe to `SymbolKind.NamedType`, `SymbolKind.Field`, `SymbolKind.Property`, `SymbolKind.Method` events? Now I'm forced to write `RegisterSymbolStartAction` for each `SymbolKind`.

```
context.RegisterSymbolStartAction( OnSymbol_Start, SymbolKind.NamedType );
context.RegisterSymbolStartAction( OnSymbol_Start, SymbolKind.Field );
context.RegisterSymbolStartAction( OnSymbol_Start, SymbolKind.Property );
context.RegisterSymbolStartAction( OnSymbol_Start, SymbolKind.Method );
context.RegisterSymbolAction( OnSymbol, SymbolKind.NamedType, SymbolKind.Field, SymbolKind.Property, SymbolKind.Method );
```

This is probably the dumbest question but I I really wonder :)

_I can assume that this is because `SymbolKind.NamedType` is parent syntax node and it's enough to process all child nodes.
But what if I want to process only some child nodes?_

**Comment by CyrusNajmabadi** [comment]
The purpose of symbol actions is to analyze symbol *declarations*.  i.e. to analyze the declaration of a property, or a class, etc. etc.

There is no equivalent for things like 'arrays' or 'pointers' and whatnot.  They are not declared in the same way.  Rather, they are referenced at particular points in the code.  i.e. there's no declaration point for `string[]`.  Instead, there are N references of that type throughout hte codebase.

These concepts are not complimentary and not something this api is intended to support.
