### ISSUE TITLE
The IDE should generate code at the cursor's position and not at the end of the file

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/roslyn#49858]
**Version Used**: 16.8.2

**Steps to Reproduce**:

```csharp
public abstract class FooBar
    {
        public abstract void Foo();
    }


    public class FooBarImpl : FooBar
    {
        // Some comments

       // PLACE THE CURSOR BELOW THIS LINE

        //public override string ToString()
        //{
        //    return base.ToString();
        //}

        // Some other comments
    }
```

Place the cursor right after the comment 'PLACE THE CURSOR BELOW THIS LINE', then press 'Alt + Enter' (or 'Alt + .' to invoke the quick actions menu. Select 'Generate overrides...' and select only 'Foo' method (it doesn't matter actually, this is just an example).

**Expected Behavior**:

The generated code should be produced at the position of the cursor.

**Actual Behavior**:
The generated code is produced at the end of the file.

Another bonus issue: if the class has at least one overridden method, 'Alt + Enter' stops suggesting 'Generate overrides...' menu at all!

**Comment by CyrusNajmabadi** [comment]
This would be challenging to support based on the current way this API is shaped.  Please include me in the design meeting for this.

**Comment by Cosifne** [comment]
Design meeting notes:
If the cursor is on the identifier, follow our existing rules.
If invoked the inside the type decaration and it is a valid position, use that position

**Comment by SergeyTeplyakov** [comment]
Great news! Thanks a lot!
