### ISSUE TITLE
Provide code-fix for IDE0060

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#49868]
**Brief description:**

Rule [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801) was deprecated in favor of `IDE0060` (see https://github.com/dotnet/roslyn-analyzers/issues/4498). But `IDE0060` doesn't currently provide a code-fix.

We could offer one based on the one from `CA1801`.

cc @mavasani

**Comment by Youssef1313** [comment]
The codefix should consider https://github.com/dotnet/roslyn-analyzers/issues/4697#issuecomment-761010571

**Comment by CyrusNajmabadi** [comment]
Closing out due to costs and lack of broad feedback.
