### ISSUE TITLE
Warning when a notnull generic type is assigned a `default` literal.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#49866]
There are 2 questions opened here:

- I think the compiler should not allow the use of `default` for a generic type with only the `notnull` constraint as it does not prevent the use of a reference type for which `default` is `null`. Where can I create this ticket? `dotnet/runtime`? `dotnet/roslyn`? other?

- ~~Get rid of the optional value and force the caller to pass a value.~~ (unrelated to roslyn)

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn-analyzers/issues/4350#issuecomment-741837940_

**Comment by Youssef1313** [comment]
[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQZAbhAgAQAeNAvDZnAO40DCAPLoQAwA+ABQBKANxkyuAMw0CXbgBVBNNgAtEcGkpogWAexiZ0AG1NkA3mRq35czsN0wmNACZwAZhDMxRNu2tSOxCaAEtPGmEXMKgWM1N/YNCUvgBOYQAiTCMTcxoYAE8AB21qAHN0MDhMGLi80wBCTIkA2wBfMk7SIA).

cc: @Evangelink to confirm the scenario provided in the above SharpLab.

**Comment by RikkiGibson** [comment]
Looks like the SharpLab doesn't include `#nullable enable` directive, which is necessary to produce the diagnostic.

**Comment by Youssef1313** [comment]
@RikkiGibson Yep that's why I edited my previous comment.

The exact scenario from roslyn-analyzers is [here](https://github.com/dotnet/roslyn-analyzers/blob/2e6b79b402e2b7ee21831fb3693ee5b3b7ebe471/src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs#L521)

Nullable context is enabled, but no diagnostic on line 521. (There is a nullable warning a few lines later - but I expect both lines to have a diagnostic)

**Comment by Evangelink** [comment]
I am surprised because on `SharpLab` the issue is on the `= default` while in the analyzer the issue in on the assignation of the property.

**Comment by RikkiGibson** [comment]
Behavior was changed recently, at one point we handled `T t = default` in some cases by not giving a diagnostic and instead updating the default state of the parameter. Updating the compiler should result in behavior where we give a warning on the parameter default value, and not at the use site of the parameter within the method body.

**Comment by Evangelink** [comment]
Ok so in this case the issue can probably be closed.
