### ISSUE TITLE
Feature: Allow formatted content in description window

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#49867]
It would be nice to allow some light formatting (bold/italic/underline) in description areas:
![image](https://user-images.githubusercontent.com/4821/101535810-08a20400-394e-11eb-8edd-137afff1a9a5.png)

**Comment by Cosifne** [comment]
Design meeting notes:
Get more examples, how people would use it if we have the feature/ wait for feedback.

**Comment by ryzngard** [comment]
@mavasani  to follow up on how easy this is to implement. Maybe use localizable string.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement and investment in this area.
