### ISSUE TITLE
Untrusted Execution

### ISSUE THREAD

**Issue by discoderpin** [dotnet/roslyn#49889]
I want users in my community to be able to create their own scripts but want to restrict the amount they can do. I don't want them to have the ability to view, create or delete files on the server for obvious reasons. How have you all secured roslyn to a point it can be used by possible untrusted users?

**Comment by canton7** [comment]
(Note: this should probably be a discussion)

https://sharplab.io uses https://github.com/ashmind/Unbreakable (which is something the author of SharpLab wrote). https://dotnetfiddle.net has done something else (less restrictive), but I'm not sure there are any docs on *what*.

Personally, if I were doing this, I'd be looking to run scripts in a separate process, and use systemd capabilities to lock down what it's allowed to do, including: chrooting it, locking down `CapabilityBoundingSet`, `SystemCallFilter`, network access, adding resource limits, etc etc. Even then I'd be nervous: things like Rowhammer are likely still possible.
