### ISSUE TITLE
Suggested primary constructor parameter names should be pascal-cased

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#49896]
**Version Used**: 16.8.3

Since these become property names, camel-cased names should not be suggested.

![image](https://user-images.githubusercontent.com/8040367/101715195-008ab700-3a69-11eb-97bd-657231668e47.png)

**Comment by Youssef1313** [comment]
Duplicate of #48310

**Comment by jnm2** [comment]
Lol, thanks! My search failed.
