### ISSUE TITLE
Filtering reference assembly

### ISSUE THREAD

**Issue by iSazonov** [dotnet/roslyn#49908]
Sometimes developers have to create public types for internal using only.

Is it possible to exclude an public type from reference assembly? By assigning an attribute?

**Comment by Youssef1313** [comment]
Why not declare it `internal`? and if needed to be used in other internal projects, they can be made available to them through `InternalsVisibleTo`.

**Comment by iSazonov** [comment]
In PowerShell repo we have namespaces with names ended `Internal`. Such name explicitly indicates that all types there is not for public use by third-party developers but sometimes the types are defined as public. It is PowerShell specific. (It seems even .Net Runtime has similar types).
I know today MSFT PowerShell team has to use an internal script to create SDK reference assembly. It is not good for an open source project.
I believe it would be great to have a possibility explicitly point that we want to have in a reference assembly.
