### ISSUE TITLE
Callback References

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49928]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Callback-References/1267420)._

---
<p>Dear developers,</p><p>I've recently been using Visual Studio a lot and I really like it. I also use software from JetBrains a lot, where I saw a really useful feature (in Rider) of being able to see callback references. So, would it be possible to make such a feature in Visual Studio, so that it behaves in a same way as method references?</p> <p>I would really appreciate it.</p> <p>Best regards,</p><p>Georgy Gunkin</p><p>PS: By callbacks I mean subscriptions to Action types.</p>

---
#### Georgy Gunkin on 11/24/2020, 05:15 AM: 

<p>By the way, the link for the same feature in Rider is here:</p><p>https://www.jetbrains.com/help/rider/Code_Analysis__Call_Tracking.html?_ga=2.95690076.1919668493.1606209557-2130323899.1606209557</p>

#### Feedback Bot on 11/24/2020, 10:10 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Can you clarify how this differs from the current **Right Click** &rarr; **View Call Hierarchy** command?
