### ISSUE TITLE
Typing a semicolon inside a broken string in a parameter list inserts semicolon at the end of the method call

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#49929]
(Not 100% sure if this is a Roslyn thing or a Visual Studio thing.)

**Version Used**:

Compiler version: '3.8.0-5.20604.10 (9ed4b774)'. Language version: 9.0.

Visual Studio 2019 16.8.3

**Steps to Reproduce**:

1. (May not be necessary, but it's partially responsible for why I ended up in this situation.) Disable "Automatic brace completion" under Tools > Options > Text Editor > C# > General
2. Given the following code with the cursor at the location of the `$$`, type `;`

```
class Class1
{
    public void Test(string s)
    { }

    public void Test2()
    {
        Test
        (
            "Hi$$
        );
    }
}
```

(Sorry for no syntax highlighting, the GitHub syntax highlighting barfs since this isn't valid syntax.)

**Expected Behavior**:

The semicolon is inserted, resulting in the following:

```
class Class1
{
    public void Test(string s)
    { }

    public void Test2()
    {
        Test
        (
            "Hi;$$
        );
    }
}
```

**Actual Behavior**:

The cursor is moved to the end and the semicolon is inserted there instead:

```c
class Class1
{
    public void Test(string s)
    { }

    public void Test2()
    {
        Test
        (
            "Hi
        );$$ ;
    }
}
```

------

Side note: Is there a way to disable this feature? I'd greatly prefer Visual Studio let me type the invalid syntax instead of trying to guess what I meant. (~~Should it be tied to the automatic brace completion setting? It seems to me it's meant to compliment that.~~[It's intentionally separate](https://github.com/dotnet/roslyn/pull/30743#discussion_r231886932).)

**Comment by Youssef1313** [comment]
Looks like this is the complete statement command handler.

**Comment by PathogenDavid** [comment]
@Youssef1313 Nice sleuthing!

The main issue is this `<` check for the end of the range assumes there's an ending `"` on the string, but in this case there isn't one.

https://github.com/dotnet/roslyn/blob/3d4efeaf9fd24940b7cddea028a1d3776c4849ea/src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs#L319

I wrote some tests to reproduce the issue: (Including one for chars)

```csharp
        [WorkItem(49929, "https://github.com/dotnet/roslyn/issues/49929")]
        [WpfFact, Trait(Traits.Feature, Traits.Features.CompleteStatement)]
        public void DontComplete_StringAsMethodArgument_EndOfBrokenLiteral()
        {
            var code = @"
            Foo(""  $$
);
";

            VerifyNoSpecialSemicolonHandling(code);
        }

        [WorkItem(49929, "https://github.com/dotnet/roslyn/issues/49929")]
        [WpfFact, Trait(Traits.Feature, Traits.Features.CompleteStatement)]
        public void DontComplete_ChasAsMethodArgument_EndOfBrokenLiteral()
        {
            var code = @"
            Foo(' $$
);
";

            VerifyNoSpecialSemicolonHandling(code);
        }
```

(I also wrote a similar test for verbatim strings, but they aren't affected. I'd assume this is because they encompass the newline whereas the others don't.)

Changing the range check to use `<=`  instead does fix these tests, but unsurprisingly breaks several others where the ending `"` is present.

It's not immediately clear to me what the "proper" fix is here. Presumably there's a way to check if the `SyntaxNode` represents a broken string, but I'd have to dig into it further.
