### ISSUE TITLE
[QUERY] How Do I Change "Fonts and Colours" for Pointers? : Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49931]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/QUERY-How-Do-I-Change-Fonts-and-Colou/1271355)._

---
Problem
I want to change the font and colours specifically when there is a pointer ie. int foo**=&goo

However, the options are limited in Visual Studio 2019.

How do I go about doing that?

Thank you very much.

---
#### Feedback Bot on 11/29/2020, 11:24 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by JoeRobich** [comment]
It is unclear what the user is wanting to be colored differently. Type names are classified by type (class, record, struct, interface, etc...). Instance names are classified by their role (parameter, local, field, property...)

With function pointers we have operators such as `*` and `&` which could be classified differently. We also have the Calling Convention Specifier ("managed", "unmanaged") and the Calling Convention ("Cdecl", "Stdcall", "Thiscall", "Fastcall", etc...) that could also be new classifications.

**Comment by CyrusNajmabadi** [comment]
Closing out as 'need more info' until the original filer can clarify things.
