### ISSUE TITLE
Select the first member !!!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49930]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1041511/select-the-first-member.html)._

---
When one chooses a class from the bar, one is advised to choose a member of that class, and if not, VS waits for you to choose.

Please.... once a class is chosed, select the first member and move the selection to that member, automatically. Do not wait for another mouse choice.

Can you see the advantage for users? You have not done it yet. Maybe you do not get it. If not, let me know and I will explain the obvious.

---
#### Feedback Bot on 5/21/2020, 02:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Mika Dumont [MSFT] on 11/23/2020, 04:12 PM: 

<p>Thanks for taking the time to provide this feedback. Do you mind sharing an example/screenshot?</p>

#### Feedback Bot on 12/1/2020, 07:33 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.

**Comment by sharwell** [comment]
From what I can tell, the requested behavior is exactly what the IDE currently does. Can you provide more information (ideally with screenshots) showing the requested change?
