### ISSUE TITLE
C# Source Generators: offer list of generated source files in Solution Explorer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#49932]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-Source-Generators:-offer-list-of-gene/1264329?preview=true)._

---
When a project contains code generated by the new C# 9 Source Generators feature, the only way to navigate to and read the generated code appears to be by using a code navigation command such as Go to Definition. But discovery of what types were generated in order to reference them in the first place would be greatly aided by having a "Generated Code" folder in Solution Explorer under the project node that lists all the generated files, perhaps each under a folder named after the generator that produced it.

---
#### Feedback Bot on 11/23/2020, 01:05 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
@jasonmalinowski  can you map the PR to this
