### ISSUE TITLE
[Query] How to embed just few sources (not all of them) to *.pdb

### ISSUE THREAD

**Issue by o-lek** [dotnet/roslyn#49957]
As far as I know, it's possible to embed all the sources of my project to *.pdb file, placing 
`<EmbedAllSources>true</EmbedAllSources>` 
tag to the *.csproj file. Is there a way to embed just few source files, not all of them ?

**Comment by alpencolt** [comment]
Does the tag `EmbedAllSources` stable and will not be changed in future release. This feature introduced few years ago (https://github.com/dotnet/roslyn/issues/12625) but not documented on MSDN.

cc @jkotas
