### ISSUE TITLE
ArgumentOutOfRangeException during emit of SyntaxGenerator.ArrayTypeExpression

### ISSUE THREAD

**Issue by hermann-noll** [dotnet/roslyn#49960]
**Version Used**:
3.8.0 and 3.9.0.-2.final

**Steps to Reproduce**:

1. Create syntax tree with `SyntaxGenerator`
2. Include an array type expression (e.g. `s.ArrayTypeExpression(s.TypeExpression(SpecialType.System_Int32))`
3. Emit said syntax tree

**Expected Behavior**:
A correctly compiled assembly

**Actual Behavior**: 
An exception is thrown during the call to `Emit` of type `ArgumentOutOfRangeException` (full stack trace is included in [the gist](https://gist.github.com/hermann-noll/265f2a6a7880364e814e7420c6452434)).

**Comments**:
This seems to throw for at least every array of primitives, but only if `SyntaxGenerator.ArrayTypeExpression` is used. An equivalent version using only `SyntaxFactory` (generated using roslynquoter) does not throw. 

I have attached a full reproduction program along with the complete stacktrace [as gist](https://gist.github.com/hermann-noll/265f2a6a7880364e814e7420c6452434)

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue, unfortunately this is not considered a bug. 

The compiler APIs for analysis and emit do not support arbitrarily constructed `SyntaxTree` values. Instead they only support `SyntaxTree` values which are created via the parser. Essentially `SyntaxTree` that represent valid C# code as defined by the parser. 

If the same bug persists with the tree round tripped through the parser (`SyntaxTree.ToString()` then fed through the parser) then that would definitely be a bug we needed to fix here.
