### ISSUE TITLE
Source Generators: EmitCompilerGeneratedFiles bug if CompilerGeneratedFilesOutputPath contains space

### ISSUE THREAD

**Issue by Reinhard-S** [dotnet/roslyn#49981]
Source generator does not emit files if solution path contains spaces or special characters.

**Version Used**: 
```
Microsoft.CodeAnalysis.Analyzers: 3.3.2
Microsoft.CodeAnalysis.CSharp: 3.8.0
OS: Windows 10.0.19042
IDE: Visual Studio Prof 2019 16.8.3
```

**Steps to Reproduce**:
1. Create a new solution and provide a name that includes a space, e.g.:
`    C:\Users\reinhard\source\repos\Blazor Playground\BlazorTest`
2. Add a new source generator project (e.g. one of the templates) and refer to it from the .csproj project file:
```
<ItemGroup>
  <ProjectReference
    Include="..\BlazorTest.CommonDataModel.CodeGenerator\BlazorTest.CodeGenerator.csproj" 
    OutputItemType="Analyzer"
    ReferenceOutputAssembly="false" />
</ItemGroup>
```
3. Enable "emitting compiler generated files" in the project files and specify the output path:
```
<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\SourceGeneratorFiles</CompilerGeneratedFilesOutputPath>
```

**Expected Behavior**:
Source files should be emitted even if spaces and other special characters are contained in the path.

**Actual Behavior**:
Root folder is being created but subfolders and files are missing.

**Workaround**:
Unload solution or close IDE, rename folders removing all spaces from the path, reopen solution and build all projects.

**Additional (failing) Tests**:
Additionally the below tests have been conducted, unfortunately all of them fail as well.

Test 1: Specifying a fixed path:
```
<CompilerGeneratedFilesOutputPath>C:\Users\reinhard\source\repos\Blazor Playground\BlazorTest\SourceGeneratorFiles</CompilerGeneratedFilesOutputPath>
```
Test 2: Use quotes:
```
<CompilerGeneratedFilesOutputPath>"C:\Users\reinhard\source\repos\Blazor Playground\BlazorTest\SourceGeneratorFiles"</CompilerGeneratedFilesOutputPath>
```
Test 3: Use XML escape char:
```
<CompilerGeneratedFilesOutputPath>C:\Users\reinhard\source\repos\Blazor\\u0020\Playground\BlazorTest\SourceGeneratorFiles</CompilerGeneratedFilesOutputPath>
```

**Comment by chsienki** [comment]
This seems to be caused by a mismatch in argument handling between directly on the command line + via response files. 

I've verified the code works as expected when passing the argument directly, but we seem to incorrectly parse it when it's written out to an RSP file (i.e. when using the build server).

**Comment by Reinhard-S** [comment]
Thank you for the fix! 👍
