### ISSUE TITLE
Simplifier removes trivia when eliminating 'this.' uses. 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#50]
Consider the following code:

``` csharp
class C1
{
    int _field;

    void M()
    {
        this. /* comment1 */ _field /* comment 2 */ = 0;
    }
}
```

If the `MemerAccessExpressionSyntax` for the field access is tagged with `Simplifier.Annotation` and the result run through the `Simplifier` the code will be transformed into.

``` csharp
class C1
{
    int _field;

    void M()
    {
        _field /* comment 2 */ = 0;
    }
}
```

Notice that `/* comment 1 */` has been removed.  That seems like a bug.  Removing non-comment trivia seems acceptable here but removing comments is potentially removing valuable documentation during the act of simplification.  At the least it seems like there should be an option to prevent this from happening.

**Comment by shyamnamboodiripad** [comment]
@jaredpar The particular issue mentioned in this bug should be fixed - however, other cases exist where simplifier won't preserve trivia. I have logged  #2142 to track these cases.

**Comment by lgolding** [comment]
It no longer removes the comment but it does add a line break. This is probably the right behavior per formatting conventions:

````cs    
public class Class1
{
    int _field;

    void M()
    {
        /* comment1 */
        _field /* comment 2 */ = 0;
    }
}
````

**Comment by lgolding** [comment]
Verified as fixed.
