### ISSUE TITLE
C# autocomplete uses full namespace rather than alias from using statement

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#5002]
__Steps to Reproduce__
1. Copy the code below.
2. Complete the line `v = new ` with autocomplete.
```csharp
using MSG = Microsoft.Structures.Geometry3d;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            MSG.Vector v = new
        }
    }
}

namespace Microsoft.Structures.Geometry3d
{
    class Vector
    {
    }
}
```
__Expected__
`MSG.Vector v = new MSG.Vector();`
__Actual__
`MSG.Vector v = new Microsoft.Structures.Geometry3d.Vector();`

EDIT: The "Actual" used to say "MSG.Structures.Geometry3d.Vector", but the actual displayed/inserted text is "Microsoft.Structures.Geometry3d.Vector"

**Comment by rchande** [comment]
The IDE is calling SymbolDisplay.ToMinimalDisplayString on `M.S.G.Vector` after `new` to decide to decide what to show in the completion list. It appears that SymbolDisplay doesn't attempt to use aliases when minimally qualifying. @jaredpar is that something the compiler would be interested in adding?

**Comment by dpoeschl** [comment]
Tagging compiler team to get input on which layer(s) should be involved here. @dotnet/roslyn-compiler

**Comment by agocke** [comment]
Technically, the method doesn't specify what is meant by "minimal", but I think including aliases is a reasonable and expected interpretation.

**Comment by CyrusNajmabadi** [comment]
This is definitely a bug.  Both the code for namespaces and named type specify that they want aliases if you are minifying:

![image](https://cloud.githubusercontent.com/assets/4564579/12729915/f2a12d4c-c8dd-11e5-86ab-484fcca4c980.png)
![image](https://cloud.githubusercontent.com/assets/4564579/12729926/fb87d370-c8dd-11e5-8817-f51462cad903.png)

We need to debug through to find out why this isn't working.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi Can we move this to the Compiler Area then?

**Comment by rchande** [comment]
@dotnet/roslyn-compiler Moving this to the compiler since it appears to be a bug in SymbolDisplay.
