### ISSUE TITLE
Add telemetry for Insert Full Method Call

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#50033]
* [ ] Report when `AbstractSnippetFunctionArgumentValue` fails in the call to `GetFieldSpan` (snippet fields should always exist for parameters)
* [ ] Report when `AbstractSnippetFunctionArgumentValue` fails to resolve a `SymbolKey` to an `IParameterSymbol`

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need this we should just assign a person/milestone and do it.
