### ISSUE TITLE
There should be a way to know where a CodeFix/Refactoring provider came from when it crashes.

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5004]
Right now you get a yellow rectangle at the top of the screen that lists the name of the provider without enough information to report issues to anyone. It would help to know which VSIX it came from. Also it is possible that multiple providers will provider the same functionality and it would be nice to know which one I am using.

**Comment by shyamnamboodiripad** [comment]
Iirc, we had discussed including provider info (perhaps at the top of the preview pane for the fix / when hovering over a fix in the menu with the mouse) but made a call to postpone this post v1.

This may potentially involve some work in the VS IDE's light bulb UI (depending on how we decide to implement this)..

**Comment by paul1956** [comment]
This is fixed in current VS with stack trace
