### ISSUE TITLE
Explore having the compiler itself issue a diagnostic for unnecessary casts.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#50043]
Currently, the IDE is responsible for the feature 'remove unnecessary cast'.  This feature itself is enormously complex and has been a very large source of errors for the IDE.  Looking just at issues with a false IDE0004 reported, we have more than 60 (and that doesn't count bug reports where the user doesn't mention the specific IDE error code).

The code has always been problematic (especially as it is written as a blacklist instead of a whitelist).  This causes us to often aggressively assume a cast is safe to remove, which can have disastrous implications for a program.  It is also extremely hard to maintain as the compiler/lang adds more advanced features in this area.  In particular, both conditional expressions and target typing have proven to cause huge amount of headaches here as hte IDE attempts to bring our analyzer up to snuff with those advanced, often non-local, lang features.  I'm fairly certain that even with all our patches that we've put in so far, we still likely have dozens of issues with the language rior to C#9 and likely dozens introduced post that.

From talking with @333fred we have a supposition that this feature would be a lot simpler, and saner, if placed into the compiler itself.  Similar to the `Remove unused usings` analysis that was done years ago, we can leverage the compiler's rich understanding of the code (including a *complete* bound semantic tree) to do a much more precise and accurate assessment of if a cast is unnecessary.  The compiler would then just issue a hidden diagnostic which the IDE layer would light up on to both fade out hte cast, and offer the fix.  (Or, there could literally be a 'IsCastUnnecessary' helper on SemanticModel).

While this is likely a very facile analysis, we think the general idea would be to effectively examine the before and after bound trees for a cast (i.e. one with the cast in it, and one with it not there).  The compiler would then whitelist tree changes which were proven to be non-impactful.  For example, given:

`object o = (object)someString;`

this cast would be unnecessary as the trees before and after would effectively be the same (with an implicitly written implicit-reference conversion, versus an explicit one).

Note though that the cases can get very complex as the presence of conversions can affect many parts of compiler analysis (for example, overload resolution).  However, this complexity is precisely why IDE would prefer that this be in the compiler, as otherwise the same analysis that the compiler normally does now needs to be redone (often poorly) at our layer.

There is no great rush on this.  But it would be very nice to be able to have this be done.  Esp. if there are interested compiler devs willing to at least explore this idea and measure the viability of it.  Fortunately, the IDE has a large amount of tests (roughly 600+ in this area) documenting many of complex cases that we've often been tripped up by.    The tests are split into two test suites:

RemoveUnnecessaryCastTests and
CastSimplificationTests

**Comment by CyrusNajmabadi** [comment]
Tagging @333fred  and @jaredpar

**Comment by Youssef1313** [comment]
That would fix https://github.com/dotnet/roslyn/issues/52990 as well.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/issues/53698 as well.

**Comment by CyrusNajmabadi** [comment]
@jaredpar  is there any way to get any eyes on this?  Issues here continue to mount up, and we're finding it pretty much impossible to track the language especially as it gets more and more complex (especially in the space of things like natural types and target typing).  This was always very much a hack on the IDE side to try to reimplement the compiler rules on conversions, and despite many efforts to try to keep it updated, we still find that it is woefully inadequate.  This is problematic as:

1. this is one of our highest used analyzers.
2. it really has the potentially to break user code badly when it goes wrong. 

We're in a rock and hard place here as we probably should disable this until we can replace it with something more robust, however that will likely lead to a lot of customer frustration given the high value and use of this feature.

Thoughts on how we might be able to move forward on this and take it out of the backlog?

**Comment by jaredpar** [comment]
Similar to other IDE requests about moving code down into the Compiler layer, this needs to wait until after Dev17 RTM. We are booked solid through the remainder of Dev17. 

This is an issue I brought up in the team meeting a few weeks ago to think about for our future work plans.

**Comment by Youssef1313** [comment]
Note when/if this is implemented:

Cast from method group to object shouldn't be marked as unnecessary. The compiler allows it but will produce a warning with https://github.com/dotnet/roslyn/issues/55923. So this might need to be special-cased.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Since the analyzer logic was re-written, should this get closed now?

for my last comment, this is still a bug that I'll file separately.

**Comment by CyrusNajmabadi** [comment]
Yes.  this should close out.  Thanks!
