### ISSUE TITLE
VS 2017 C# redundant assignment suggestion not shown

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50059]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-2017-C-redundant-assignment-suggesti/1290807)._

---
[severity:It's more difficult to complete my work]
According to [this document](https://docs.microsoft.com/en-us/visualstudio/ide/reference/unused-values-parameters?view=vs-2017) a redundant assignment should fade out the variable with the unused assignment. This doesn't seem to be working for me.
I am trying with this simple code:
```c#
int myVar = 0;
myVar = 50;
int otherVar = myVar;
```
I am expecting that `myVar` would fade out in `int myVar = 0;` with a redundant assignment warning as shown in the documentation, but this is not happening. Do I need to turn on some special setting?

If instead I only have:
```c#
int myVar = 0;
```
Then `myVar` is underlined as expected with a squiggly green line, and the message "The variable 'myVar' is assigned but its value is never used".

Why is it not working in the first case?

I am using Visual Studio 2017 Professional. Version 15.9.30.

---
#### Feedback Bot on 12/16/2020, 10:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This does'nt repro for me.  We get the expected behavior:

![image](https://user-images.githubusercontent.com/4564579/153516351-43ea61cf-cd3b-4cef-98e3-f79ed1796ba3.png)

![image](https://user-images.githubusercontent.com/4564579/153516361-1a1877f4-3d3a-499a-a94e-2d9a349ae6a3.png)
