### ISSUE TITLE
CS8852: Init-only property cannot be assigned to in an 'init' accessor if accessing it requires a cast (e.g. an explicitly implemented interface type)

### ISSUE THREAD

**Issue by ericwj** [dotnet/roslyn#50053]
**Version Used**: 
`Using "Csc" task from assembly "C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll".`

**Steps to Reproduce**:

Try to compile this.

```C#
public interface ISomething { int Property { get; init; } }
public record BaseType : ISomething { int ISomething.Property { get; init; } }
public record DerivedType : BaseType {
    public int SomethingElse {
        get => ((ISomething)this).Property;
        init => ((ISomething)this).Property = value;
    }
}
```

**Expected Behavior**:
Compiles.

**Actual Behavior**:
`error CS8852: Init-only property or indexer 'ISomething.Property' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.`

**Comment by Vinby** [comment]
Same problem bugs me out. Is it intentional? if so why?

**Comment by jaredpar** [comment]
In the cases the cast is an identity preserving conversion on `this` the cast should be allowed here.

**Comment by jcouv** [comment]
LDM confirmed that this is by-design. If a base type needs to expose something to initialize, it should expose APIs to do so.

**Comment by ericwj** [comment]
What API? Can't do this through an interface since that introduces public API to circumvent the init-only-ness. Awkward.

**Comment by jcouv** [comment]
Simply using a public interface implementation would do it:
```
public interface ISomething { int Property { get; init; } }
public record BaseType : ISomething { int Property { get; init; } }
```

Note there is an similar problem that's already existing with a private implementation with `set` or `init` property:
```
public record BaseType : ISomething { int ISomething.Property { get; set; } }

new BaseType() { ... can't set property ... }
```

**Comment by ViIvanov** [comment]
> What API? Can't do this through an interface since that introduces public API to circumvent the init-only-ness. Awkward.

I think it could be something like [this](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACAlgO3ggMwgGM4MBJAZQHsw4YALXAcwwG8BYAKA2zwwAKCagAdEMAJ7sMzegG4+WGAoC+3NV27oMCOMWoIAJhgBC0OABUJYjCAo06jFt048MI4fGLxjuGBgd6JhxmIVFxKTYZeUVlDA1ebl4/e1oglgA6MLEESXYk3mj/AF4APgC0pxDsiLkC5JwlDDKKx2DQ4Ry84owANwgAGwBXODq3DQ0tTF19IwwAEUQsXrhDKxs7MyhLazgXAu0UwKrmAFEB7fy3XlkS8uP2mtyJMcLY5vvKx86I5r7BkaveLqIA):
```cs
public interface ISomething {
  int Property { get; init; }
}

public record BaseType : ISomething
{
  protected int SomethingProperty { get; init; }
  
  int ISomething.Property {
    get => SomethingProperty;
    init => SomethingProperty = value;
  }
}

public record DerivedType : BaseType
{
  public int SomethingElse {
    get => SomethingProperty;
    init => SomethingProperty = value;
  }
}
```

**Comment by ericwj** [comment]
I find at the very least the error message very confusing. It is also very weird to me that this works, but not the original code in the issue, with the only difference being that I don't want `Property` to be visible without the cast to `ISomething`:

```cs
public interface ISomething { int Property { get; init; } }
public record BaseType : ISomething { public int Property { get; init; } }
public record DerivedType : BaseType {
    public int SomethingElse {
        get => Property;
        init => Property = value;
    }
}
```
