### ISSUE TITLE
Enhance the Remove Unused References feature

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#50054]
- [x] Analyze references for multitargeting project to ensure they are unused in all target frameworks
- [ ] Implement undo/redo support (With help from Project System team https://github.com/dotnet/project-system/issues/6795)
- [ ] Remove unused using directives
- [ ] Implement solution level analysis. Contemplate how changes to transitive dependencies between project references should bubble up.
- [ ] Move to dedicated API for getting project reference heirarchy
- [ ] Work with NuGet team to incorporate package version mismatch checking
- [ ] Provide option for preferring Transitive references over Direct references.
- [ ] Add disclaimer about runtime references (reflection loaded)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
