### ISSUE TITLE
There is a conflict between the options for Pitch Settings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50061]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-的格式设置，对“间距设置”的选项间存在冲突的问题/1285038)._

---
[severity:It's more difficult to complete my work]
When the Ignore Spaces in Declaration statement option is checked, the Settings In Parenthesis Spacing option is three options:
1. Insert a space in front of the opening brackets
2. Insert a space in empty square brackets
3. Insert a space in square brackets

Control of the code format is invalid.

These three items can be set normally when Ignore Spaces in Declared Statement is not checked.

See figure below:
! [image.png] (https://aka.ms/dc/image?name=B8f7f8431f07448f3ab3a496b559f9fd0637432549028868220_20201211-114141-image.png&tid=8f7f8431f07448f3ab3a496b559f9fd0637432549028868220)

---
#### Feedback Bot on 12/10/2020, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/11/2020, 09:57 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro an issue here with these options.
