### ISSUE TITLE
"Show procedure lines" draws too many lines

### ISSUE THREAD

**Issue by conniey** [dotnet/roslyn#5007]
__Steps to Reproduce__
1. Copy code from [ScalaClient.vb](https://gist.github.com/conniey/65eddc1c3c30b0f075cf)
2. Collapse and expand different regions

__Expected__
Like the left image (VS2013)
__Actual__
Too many procedure lines are drawn which make the code unreadable. (The code is just a small example. Internal feedback 405279 and 405115 have better representations.)

![procedurelines](https://cloud.githubusercontent.com/assets/10136526/9680600/b3d35fa6-52ac-11e5-8574-b30e08274712.png)

**Comment by Pilchie** [comment]
One of the main issues here is that we show the line separators even when the region is collapsed.
