### ISSUE TITLE
Code Path - "Unreachable code detected" rule ignores #if .. #endif

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#5008]
Consider the following example method:

```c#
public static bool IsTestingOnPremises(this HtmlHelper helper)
{
#if !DEBUG
    return false;
#endif
    return Request.ContextWrapper.IsLocalhost || Request.ContextWrapper.IsDemoApp;
}
```

In VS2015, a squiggly appears under the second `return` suggesting "Unreachable code detected". It seems like the code analyzer ignores the preprocessor directives when calculating the code paths.

Ideally, those should not be ignored and probably `#if` should be interpreted as a regular branch for such scenarios.

**Comment by gafter** [comment]
You need to use an #else. For the purposes of reachability analysis, preprocessor directives do not exist.
