### ISSUE TITLE
xmlDocCommentAttributeValue classification type not applied

### ISSUE THREAD

**Issue by NejcBW** [dotnet/roslyn#50091]
**Version Used**: 3.9.0-2.20570.24

**Steps to Reproduce**: 

1. Create a new C# XML Doc Comment with an arbitrary supported attribute.
2. Use a tool to anayse classification types.
3. Verify the classification type of the attribute value.

**Expected Behavior**: the classification type of the attribute should be **xmlDocCommentAttributeValue**

**Actual Behavior**: the classification type corresponds to the type of the field/property/... that the attribute is pointing to in the code outside of the XML Doc Comment scope (e.g. "parameter" in the example illustrated below)

I am tagging here @CyrusNajmabadi since he has recently taken care of a very similar issue in #48094.

![Attribute value](https://user-images.githubusercontent.com/49614740/102819339-91e81a80-43d3-11eb-9c24-77b83bcd46b5.jpg)

Thanks a lot!
Nejc

**Comment by CyrusNajmabadi** [comment]
CLosing out due to lack of feedback on this.
