### ISSUE TITLE
IsVBKeyword extension method has wrong case values.

### ISSUE THREAD

**Issue by maboivin** [dotnet/roslyn#50095]
There are 2 lines in the IsVBKeyword extension method that cannot be reached because the case value is not lowercase.

First case is ["goTo"](https://github.com/dotnet/roslyn/blob/97192cead1c3035e0ff708238dfb2e83554328aa/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs#L2051).
Second case is ["paramArray"](https://github.com/dotnet/roslyn/blob/97192cead1c3035e0ff708238dfb2e83554328aa/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs#L2093).

Also, according to the [documentation](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/keywords/), it seems to be missing this one:
- NameOf

The issue is extremely easy to fix and may not be a high priority.

**Comment by CyrusNajmabadi** [comment]
Hi @maboivin Feel free to submit a PR here :)

**Comment by paul1956** [comment]
@CyrusNajmabadi Can I just add it to another PR or does it need to be separate?

**Comment by CyrusNajmabadi** [comment]
I don't see why it would be part of another pr. So please just file an independent one. Thanks!

**Comment by AdamSpeight2008** [comment]
Isn't `NameOf` a contextual keyword?

**Comment by 333fred** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/50098.
