### ISSUE TITLE
Proposal: Attributes on expression-bodied properties

### ISSUE THREAD

**Issue by angelsl** [dotnet/roslyn#5010]
Right now if I want to have an attribute on a get-only property I need to use the old syntax:

``` csharp
[Attribute()] // targets property
public T Property {
    [Attribute()] // targets get method
    get { return ...; }
}
```

It would be nice to be able to do this:

``` csharp
[Attribute()] // targets property
[method: Attribute()] // targets get method, currently unsupported
public T Property => ...;
```

**Comment by HaloFour** [comment]
You'd probably need to use the `method` attribute target so that the target is not ambiguous:

```cs
[Attribute()] // targets the property itself
[method: Attribute()] // targets the getter method
public T Property => ...;
```

This is currently not supported and the C# compiler warns that the attribute will be ignored.

**Comment by angelsl** [comment]
@HaloFour, thanks, I wasn't aware that properties were represented in IL and not just syntactic sugar.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.
