### ISSUE TITLE
Roslyn + MSBuild + VS19 fails to build 

### ISSUE THREAD

**Issue by Thaval** [dotnet/roslyn#50115]
This roslyn + MSBuild integration is driving me crazy... insanity. And sorry for being so direct.
I created a NET 48 console application which references a lot of Microsoft.Build and Microsoft.CodeAnalysis nuget references. The job is to load a solution and get all projects, easy task imho.
So I created another project, a NET 48 WPF project to be clear, which references the console application and use the "SolutionReader" class I created.
However, after failing reading a solution for no reasons (amount of projects = 0), As I'm not new to Microsoft, I knew they have some troubles with their nuget dependencies, so I started to add Microsoft.Build and Microsoft.CodeAnalysis nugets even to the WPF project. I needed to set "ExlucdeAssets=runtime" to the Microsoft.Build* packages because Visual Studio was complaining.
Now when I run the WPF application again and try to load a solution, is says that it cannot load Microsoft.Build.Locator because one of its dependencies could not be loaded (why don't give the nuget all the dependencies it's based on?!).
The only package missing is "Microsoft.Build.Runtime". However, as soon as I add this package, VS19 goes crazy. It cannot build the WPF project anymore and best thing: it doesn't output anymore why the build failed.

When I remove the "Microsoft.Build.Runtime", the project still does not compile. I have to restart the whole computer!

So what hell is going on here? Has somebody a clue?

**Comment by jmarolf** [comment]
> However, after failing reading a solution for no reasons (amount of projects = 0),

I assume you attached to the `WorkspaceFailed` and gave a progress reporter like below and nothing was returned?

```cs
using (var workspace = MSBuildWorkspace.Create())
{
    workspace.WorkspaceFailed += (o, e) => Console.WriteLine(e.Diagnostic.Message);
    var solution = await workspace.OpenSolutionAsync(solutionPath, new LoadingProgressReporter());
}

private class LoadingProgressReporter: IProgress<ProjectLoadProgress>
{
    public void Report(ProjectLoadProgress loadProgress)
    {
        var projectDisplay = Path.GetFileName(loadProgress.FilePath);
        if (loadProgress.TargetFramework != null)
        {
            projectDisplay += $" ({loadProgress.TargetFramework})";
        }

        Console.WriteLine($"{loadProgress.Operation,-15} {loadProgress.ElapsedTime,-15:m\\:ss\\.fffffff} {projectDisplay}");
    }
}
```

> so I started to add Microsoft.Build and Microsoft.CodeAnalysis nugets even to the WPF project. I needed to set "ExlucdeAssets=runtime" to the Microsoft.Build* packages because Visual Studio was complaining.

By default, we encourage you to not take any direct dependencies on `Microsoft.Build.*` and instead use the msbuild locator class to locate and register an msbuild installation. Otherwise you are responsible for not only deploying all msbuild assemblies but all necessary default targets and props files. This does not make sense for most applications. You need to ensure that this code is called by your application before any msbuild workspace types are created.

```cs
var instance = MSBuildLocator.QueryVisualStudioInstances().First();
MSBuildLocator.RegisterInstance(instance);
```

> When I remove the "Microsoft.Build.Runtime", the project still does not compile. I have to restart the whole computer!

Can you give the specific compile errors you are seeing? It would also be helpful if you could share your code.

**Comment by Thaval** [comment]
Meatime, the compile error is gone. There are so many dependencies that I just often run into situations where I say "Oh, it suddenly works. Why? Dunno. Didn't change a thing." I guess that's a huge disadvantage when working on multiple projects simultaneously: loosing track of what's going on under the hood.
