### ISSUE TITLE
Source Generator fails unless the generator source code is modified.

### ISSUE THREAD

**Issue by trampster** [dotnet/roslyn#50116]
CSC : warning CS8785: Generator 'JsonGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. [/home/daniel/Work/JsonSG/UnitTests/UnitTests.csproj

If I then go to my generator project (JsonSG.Generator) and make a whitespace change then it will work.

I'm running in vscode on linux using .net 5 preview 7 from the snap package. (I would use preview 8 but the snap package does not seem to be available yet)

My Source code is here: https://github.com/trampster/JsonSG

**Comment by jaredpar** [comment]
Closing due to lack of response for the stack trace of the issue. If you can get a copy of the stack trace, or provide a repro we can look at, please add it to the issue and we will reactive and take a look.
