### ISSUE TITLE
'Go to definition' on a tuple element name should not navigate to metadata for ValueTuple.ItemN

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#50119]
**Version Used**: 16.8.3

If you press F12 to go to definition for `SomeMember`, and `bar` happens to be a tuple, you get taken to a source view that decompiles `ValueTuple<...>` from metadata even though I think this can't be useful and wasn't what was expected.

```cs
Foo(bar.SomeMember);
```

What I'm looking for is "where is the SomeMember name coming from," and sometimes, "where is the SomeMember value coming from." Here's an example of what I would expect:

```cs
var bar = GetBarFromSomewhereElse();
Foo(bar.SomeMember);
```

I would expect the navigation and selection to land here, even if it's in another file or in source generated from metadata, showing where the name came from. (Specifically: the name token which, if changed, would cause `bar.SomeMember` to stop compiling. In this way it's a logical extension of navigating to the definition of a member on e.g. a class.)

```cs
(int [|SomeMember|], int SomeOtherMember) GetBarFromSomewhereElse() => ...
```

When I go to definition on a default `ItemN` tuple element name, it's because I want to go to the place where I can create a custom name for it. (Or if in metadata, the place that shows me which library is responsible for not having defined a name.) Just like how going to definition on `SomeMember` would take me to the place where I can edit that name. In that case, I think it would be most useful to end up here:

```cs
(int[||], int) GetBarFromSomewhereElse() => ...
```

**Comment by jnm2** [comment]
A more realistic example:

```cs
void M(IReadOnlyCollection<Foo> foos)
{
    var calculationsByFooIndex = (
        from foo in foos
        select (
            CalculationA: new SomeCalculation(),
            CalculationB: new AnotherCalculation())).ToList();

    var crossFooCalculation = new ComplexCalculation(calculationsByFooIndex.Select(c => c.Something));
    
    foreach (var (foo, calculations) in foos.Zip(calculationsByFooIndex))
    {
        // F12 on 'CalculationA' on the next line should navigate to and select 'CalculationA' above. That is where you
        // would go to change the name, and that is where you would go as a step in navigating to SomeCalculation.
        _ = calculations.CalculationA[foo.SomeDate];
    }
}

**Comment by CyrusNajmabadi** [comment]
Yes.  I will try to fix this.

**Comment by CyrusNajmabadi** [comment]
Looks like all thse examples work as itnended.  if you do end up with a case where we go to metadata, lmk.  It's eitehr a bug... or possibly a case where the compiler couldn't really figure out what was going on.  But we can def look into that.

**Comment by jnm2** [comment]
I'm sorry, this afflicts ReSharper not Roslyn and I didn't realize that was possible.

**Comment by jnm2** [comment]
Followup at https://github.com/dotnet/roslyn/issues/51940 for actual Roslyn behavior.
