### ISSUE TITLE
Fix for IDE0059 "unnecessary assignment" results in extra IL local

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/roslyn#50124]
**Version Used**: Visual Studio 2019 v16.9.0-pre.2.0

**Steps to Reproduce**:

```csharp
public class C {
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    public void M(int a, out int b) {
        b = a;
    }
    public void A() {
        M(0, out int v);
        M(v, out v); // IDE0059
    }
    public void B() {
        M(0, out int v);
        M(v, out _);
    }
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACBmAAhwCYCBhAgbwFgAoAhggbRwEYA6AJQFcA7GNGDjsyAezAAHTIgDKiAG5oAxnCjsAsnBgALUQBMAkpIwAKNlz4ChI8VIyyFy1Rq27DxgPISBo3moByoga8GGi8YQDmAJQAunSMRIQ4ACwE6iZhMAQQSASi3FmZBMBRVPEJjMAEALzZANzlDAC+jYlEqQCCJqU09BUM6QAMufmF/ATyUQ19/enyIwUTUwQA9CsEBgAiAKKDgwCsAJytLTNtKQQAQt1lZwlDC2NZk9P9AybzeYsA+lMndE0gA===

**Comment by CyrusNajmabadi** [comment]
Seems by design to me. The fix is working properly. It's up to the compiler of they'd want to optimize this in some way.

**Comment by jaredpar** [comment]
Agree this is "By Design". The compiler won't consider the slot for `v` to be re-usable here as `v` is still an active local at that point in the method (by scoping rules).
