### ISSUE TITLE
Idea: project/package level code snippet

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#50125]
Code snippets are always useful. However, the old snippets shipped with Visual Studio are only suitable for some old programming models.

A project is likely to contain it's own pattern, and worth to be a code snippet. It will be very useful and flexible if the IDE can load code snippet for project.

.NET SDK and nuget packages should be also provide snippets with them.

Legacy snippets should be hidden when using new SDK.

**Comment by CyrusNajmabadi** [comment]
Closing as we not investing in snippet scenarios.   We think copilot is likely the better path here
