### ISSUE TITLE
NRE in SignatureHelpParameter

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50135]
**Version Used**: 

master

**Steps to Reproduce**:

It happened once in SharpLab, but I couldn't reproduce it again.

![image](https://user-images.githubusercontent.com/31348972/103156484-9c2e5e00-47b1-11eb-8b86-649d4731914d.png)

The line where the crash happened is:

https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Features/Core/Portable/SignatureHelp/SignatureHelpParameter.cs#L156

**Comment by Youssef1313** [comment]
Found a constant repro steps:

1. Start with the following code.

```csharp
public class C
{
    private int a, b;

    public C() => (a, b) $$
}
```

2. At the position of `$$`, start writing ` = (x, y);`.

3. You'll see the crash while typing.

**Comment by sharwell** [comment]
Yes, this is correct. `documentationFactory` is _always_ null at that location (I found this bug while enabling nullable reference types in these files but never completed the work to submit a PR).
