### ISSUE TITLE
CodeLens doesn't count up the usage on custom method GetPinnableReference

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#50131]
**Version Used**: 
VS 16.9 Preview 2

**Steps to Reproduce**:

Type code such as:

```csharp
using System;

var sudokuGrid = new SudokuGrid();
unsafe
{
    fixed (short* ptr = sudokuGrid) // Here used `GetPinnableReference`.
        Console.WriteLine(*ptr);
}

public unsafe struct SudokuGrid
{
    private fixed short _masks[81];
    
    public readonly ref readonly short GetPinnableReference() => ref _masks[0];
}
```

**Expected Behavior**:

There's 1 reference on the method `SudokuGrid.GetPinnableReference` usage.

**Actual Behavior**:
CodeLens shows that this method isn't called by any other methods (i.e. 0 references) no matter what valid signature I changed:

* `readonly ref readonly short GetPinnableReference`
* `ref short GetPinnableReference`
* `ref readonly short GetPinnableReference`

**Comment by Youssef1313** [comment]
The fix might be similar to what was done for `Deconstruct` method, https://github.com/dotnet/roslyn/pull/22934

**Comment by Youssef1313** [comment]
Also relates to https://github.com/dotnet/roslyn/issues/25610

**Comment by SunnieShine** [comment]
Sorry for dupe. I'll close this one.
