### ISSUE TITLE
FormatAsync introduces extra newlines

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50130]
I can't work out what format whitespace is doing on this one. Consider this code:

```cs
class Test
{
    void M()
    {
        Console.WriteLine("Test");
        var x = 1 
        
    }
}
```

There is a space after the `1`, and there are 8 spaces on the next line. If I call `FormatAsync` with bounds of `[72..90)`, I get back a document formatted like this:

```cs
class Test
{
    void M()
    {
        Console.WriteLine("Test");
        var x = 1


    }
}
```

Note the extra newline inserted, and also the changes outside the range requested like https://github.com/dotnet/roslyn/issues/50129. This seems specific to scenarios involving code that does not end with a `;`, as I don't see it for scenarios like `var x = ; `.

**Comment by CyrusNajmabadi** [comment]
Calling formatting on syntactically invalid code is generally undefined.  We effectively "do our best" here, but can totally screw things up.  Note: in this case, i would not expect the span between `1` and `}` to be touched as it would span a missing token.  However, there are likely many complex rules at play here and something else may be overriding that.

I'm not sure what hte scenario is here though.  How did it arise that you are calling FormatAsync with this code?

**Comment by 333fred** [comment]
As indicated in https://github.com/dotnet/roslyn/issues/50129#issuecomment-751142554, we call format when the user hits enter.

**Comment by CyrusNajmabadi** [comment]
format on enter isn't a supported C# feature.  You can see that here: https://github.com/dotnet/roslyn/blob/18d8e7c9a135e0b042a079823d9ef95c63b84b33/src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs#L50

:)

Explicitly  *100%* not supported by the team :)

**Comment by CyrusNajmabadi** [comment]
The places we support automatic formatting are very explicit and can be found here:

https://github.com/dotnet/roslyn/blob/18d8e7c9a135e0b042a079823d9ef95c63b84b33/src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs#L47-L49

and here:

https://github.com/dotnet/roslyn/blob/18d8e7c9a135e0b042a079823d9ef95c63b84b33/src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs#L52-L100

**Comment by CyrusNajmabadi** [comment]
Note: i would not be calling Formatter.FormatAsync directly.  This is an example of a 'low level raw API'.  the intent here would be to use IEditorFormattingService which, as the name suggests, provides the expected behavior for a particular editor host. :)

**Comment by sharwell** [comment]
Support for formatting on return for C# was permanently removed in https://github.com/dotnet/roslyn/pull/33983. I don't believe anything in this issue is actionable from the IDE side.
