### ISSUE TITLE
IDE0054 Use compound assignment is offered for "with" initialization expression

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/roslyn#50133]
**Version Used**: 
Visual Studio Community 2019 16.8.3
.NET 5.0.101

**Steps to Reproduce**:
Write the following code:
```cs
public record MyRecord
{
    public int MyValue { get; init; }

    public MyRecord IncrementValue()
        => this with
        {
            MyValue = MyValue + 1
        };
}
```

**Expected Behavior**:
Suggestion IDE0054 should not be offered on line 8, since the result is not actually valid syntax.

**Actual Behavior**:
Suggestion IDE0054 is offered on line 8.

![image](https://user-images.githubusercontent.com/26645431/103148360-7c9d2400-4724-11eb-9efc-1aadd559c09e.png)

This is similar to #49303, but applies to `with` expressions instead of `new()` expressions.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/49303

That PR also demonstrates that this fixes `with` expressions with tests here: https://github.com/dotnet/roslyn/pull/49303/files#diff-0b50e80bbbc74fe61a5e5fc7ad38c8f0ab70a77e4ddc5a6bb394a3ee5ab26678R821
