### ISSUE TITLE
[Source generator] Can't add dependency to generator

### ISSUE THREAD

**Issue by alexanderuv** [dotnet/roslyn#50148]
**Version Used**: dotnet 5.0 (on macOS)

**Steps to Reproduce**:

1. Create a solution with two projects. One of them will host the source generator, the other will get its source generated.
2. Add a dependency (in my case, YamlDotNet 9.1.0)
3. Configure source generator and target project to depend on it 
3. try `dotnet build`

**Expected Behavior**:
The sources are generated in target project.

**Actual Behavior**:
I get an error while building the source generator project:
```
CSC : warning CS8785: Generator 'XYZCodeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'YamlDotNet, Version=9.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
```
And target project fails to compile due to the missing class...

**Comment by PathogenDavid** [comment]
See https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145 and https://github.com/dotnet/roslyn/issues/49075

The short version is that dependencies aren't automatically made available to source generators (or analyzers.) You must either:

* Do some extra work so the compiler loads them
  * (This is the easiest but has issues if multiple analyzers/source generators reference the same assembly.)
* Merge them into your source generator using ILMerge
* Petition the developer of your dependency to provide a source NuGet package. (Or a dual binary+source package like @xoofx did for Scriban: https://github.com/scriban/scriban/pull/281)
  * Barring that, you might also consider embedding the source of your dependency directly using a Git submodule or something similar.

**Comment by alexanderuv** [comment]
Thanks for the clear explanation @PathogenDavid ! 
This seems like a very obvious limitation though. In order to generate code, people might very well rely on external data which might need additional dependencies to process. Without dependencies you're basically restricted to whatever is provided by the framework itself (at least it provides JSON 🙂 )

**Comment by PathogenDavid** [comment]
No problem! And for sure, things could definitely stand to be simpler. It's actually a pretty complicated problem to solve properly though. (Largely due to the fact that Roslyn still has to be able to run under .NET Framework to support Visual Studio.)

**Comment by jaredpar** [comment]
Closing as the linked issues / discussion are where we're discussing this issue.
