### ISSUE TITLE
In memory compilation fails to compile nested struct but works in VS2019

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/roslyn#50159]
**Version Used**: `Microsoft.CodeAnalysis, Version=3.9.0.0`

**Steps to Reproduce**:

```csharp
public struct S1
{
    public struct S1_D1_F1
    {
        public uint uint32_1;
        public sbyte sbyte_2;
    }
    public S1.S1_D1_F1 s1_s1_d1_f1_1;
}

class TestClass {}
```

I built a syntax tree to produce above code. It compiles using VS2019, but if I use `CompilationUnit.Emit()`, it fails to compile and gives compilation errors.

**Expected Behavior**: 

Code compiles using `CompilationUnit.Emit()`.

**Actual Behavior**:

Throws following errors:

```
error CS0246: The type or namespace name 'S1.S1_D1_F1' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by svick** [comment]
Can you share the full code that reproduces this issue?

**Comment by kunalspathak** [comment]
I am trying to generate a C# program using roslyn APIs and above code is the produced code. Unfortunately, the project that I am working on is large and I cannot share, however, here are few things I tried.

I created a `CompilationUnit` from the syntax tree that I produced programmatically and then I do this:
```csharp
SyntaxTree tree = ... // tree produced programmatically
var cc = CSharpCompilation.Create("HelloWorld", 
                new SyntaxTree[] { tree },
                references,
                new CSharpCompilationOptions(
                    OutputKind.DynamicallyLinkedLibrary,
                    concurrentBuild: false,
                    optimizationLevel: OptimizationLevel.Debug));

using (var ms = new MemoryStream())
{
  result = cc.Emit(ms);  // this doesn't work
}
```
This one produces the compilation error I mentioned above.

However, if I generate code out of the tree and re-parse it, I don't see the errors anymore:

```csharp
SyntaxTree tree = ... // tree produced programmatically
tree = SyntaxTree.ParseText(tree.ToFullString());
var cc = ...
...
...
result  = cc.Emit(ms);  // this works
```

I tried to use `IsEquivalentTo()` and it returns `false` but I am not sure what is different.

```csharp
SyntaxTree tree = ... // tree produced programmatically
SyntaxTree parsedTree = SyntaxTree.ParseText(tree.ToFullString());

tree.IsEquivalentTo(parsedTree) // returns false
```

I tried do `parsedTree.GetChanges(tree)`, but I don't see any changes. Any idea what could be wrong?

**Comment by svick** [comment]
Roslyn doesn't handle syntax trees that *look* like they are correct, but actually have different structure, that could be the issue here. Can you try cutting down the code that generates the syntax tree into a form that can be posted here, while still reproducing the error? Or you could try using `IsEquivalentTo()` recursively on subtrees, in order to locate the difference.

**Comment by CyrusNajmabadi** [comment]
> SyntaxTree tree = ... // tree produced programmatically

Can you suply the code that does the `...` part?

**Comment by kunalspathak** [comment]
Actually I figured out the problem. Thanks @svick for the suggestion of recursive comparing the tree. Turns out that the tree I was generating for `public S1.S1_D1_F1 s1_s1_d1_f1_1;` was:

```csharp
VariableDeclarator(Identifier("S1.S1_D1_F1"))
```

instead of

```csharp
VariableDeclarator(QualifiedName(IdentifierName("S1"), IdentifierName("S1_D1_F1")))
```
