### ISSUE TITLE
Source generator fails with Microsoft.CodeAnalysis, Version=3.8.0.0 load error

### ISSUE THREAD

**Issue by BertanAygun** [dotnet/roslyn#50153]
**Version Used**: 
Microsoft.CodeAnalysis.CSharp package version ="3.8.0"
Dotnet version: 5.0.1
Dotnet-SDK: 5.0.101

Package references:
		<PackageReference Update="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
		<PackageReference Update="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" />   

**Steps to Reproduce**:

1. Created a source generator project based on the sample in the repo (targeting netstandard2.0)
2. Created a netstandard2.0 library project referencing the source generator project
3. Do "dotnet build" on the 2nd project which results in (omitted paths, names):

CSC : warning CS8032: An instance of analyzer cannot be created from : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. 

The same failure also repros in VS 16.9 Preview 2 (public release) and also when trying to use generators from a project targeting net472

**Expected Behavior**:
The warning doesn't appear and generators load successfully.

**Comment by sharwell** [comment]
Can you verify via a binlog the specific version of csc used for this build? I'm particularly interested to know if the global.json and/or PackageReference has overridden the defaults.

**Comment by BertanAygun** [comment]
@sharwell, after going through logs again I realized there was a props file setting Microsoft.Net.Compilers.Toolset package version to 3.6.0 causing a mismatch. Aligning everything to 3.8.0 is working now including net472 target. 

I wonder if there is a build target that can be added to CodeAnalysis package to provide a more descriptive warning in such cases.

**Comment by sharwell** [comment]
Note that Microsoft.Net.Compilers.Toolset is not an officially supported package (at least last I heard), so build issues that occur only when it is referenced are not typically considered bugs.

/cc @chsienki @jaredpar
