### ISSUE TITLE
Inline Parameter hints in multiple opened documents appear and disappear at different times

### ISSUE THREAD

**Issue by vritant24** [dotnet/roslyn#50174]
**Version Used**: 
Version 16.9.0 Preview 3.0 [30830.8.main]

**Steps to Reproduce**:

1. Have two C# documents open side by side in Visual Studio
2. To show inline parameter hints, with focus in one of the documents, press and hold `Alt+F1`
3. to remove hints, release keypress

**Expected Behavior**:
All hints show up at the same time in step 2.
All hints go away instantly in step 3

**Actual Behavior**:
The focused document shows and removes the hints instantly, the other document lags behind by 4-10 seconds,

**Comment by CyrusNajmabadi** [comment]
Interesting.  In general, we heavily delay tagging of non-focused documents to alleviate CPU hits and allow the focused doc to be unhindered.  This is an interesting case though as the user may:

1. want to see the info in all visible docs
2. be distracted by the speed differential

Not sure how easy this would be to fix given how this is likely baked into the async infrastructure.  I'll see if i can do anything here.

**Comment by vritant24** [comment]
Ah delaying updates on non-focused documents makes sense.
Although, in this case where there is a temporary action that's causing a UI change, the lag is really jarring.

If it isn't feasible to cause an instantaneous update on all visible documents, what about showing inline parameters only in the focused document? As a user, that would be my preference over the current behavior. 
Showing inline parameters on all visible documents could be opt in with the expected delay of updates since it's possible that a user may not mind that.

**Comment by CyrusNajmabadi** [comment]
> Although, in this case where there is a temporary action that's causing a UI change, the lag is really jarring.

Agreed.

> what about showing inline parameters only in the focused document? 

Definitely something that could be reasonable!  Depending on how costly/complex it is to make the timing match, we may go with that approach to reduce the jarring-ness.

**Comment by CyrusNajmabadi** [comment]
@akhera99 did you fix this?

**Comment by akhera99** [comment]
> @akhera99 did you fix this?

I do not believe so unless the behavior as changed from other fixes. I will see if it still repros

**Comment by CyrusNajmabadi** [comment]
Haven't heard about this being an issue for customers.  Existing behavior is acceptable.  Going to close out.  Note: this behavior will be controlled by lsp in the future as well.
