### ISSUE TITLE
IDE0049 diagnostic not present when EnforceCodeStyleInBuild set

### ISSUE THREAD

**Issue by mberginbh** [dotnet/roslyn#50173]
**Version Used**: 

5.0.101

**Steps to Reproduce**:

_test.csproj_

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
```

_.editorconfig_

```
[*]
dotnet_diagnostic.IDE0049.severity = error
dotnet_style_predefined_type_for_locals_parameters_members = true:error
dotnet_style_predefined_type_for_member_access = true:error
```

_Program.cs_

```cs
using System;
Console.WriteLine(Int32.MaxValue); // IDE0049
```
**Expected Behavior**:

`dotnet build` fails with IDE0049 diagnostic because https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enable-on-build

**Actual Behavior**:

Build succeeds - no diagnostic.

**Comment by mberginbh** [comment]
Does this mean there are certain rules which cannot be enabled with `EnforceCodeStyleInBuild`?

https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs#L101

**Comment by mavasani** [comment]
Yes, simplify type name analyzer has not been ported to CodeStyle NuGet package due to known perf issues.

**Comment by mberginbh** [comment]
Thanks for the clarification. _CodeStyle NuGet package_ also is the same thing that's built into the SDK right?

**Comment by mavasani** [comment]
Yes, that is correct. Basically this analyzer is not yet ready for build time enforcement.
