### ISSUE TITLE
Proposal: Returning flat enumerables within an IEnumerable<T> function.

### ISSUE THREAD

**Issue by adamhewitt627** [dotnet/roslyn#5018]
I've personally done something like this in several cases:

```C#
public IEnumerable<string> SayHello(string[] names)
{
    yield return "Hello everyone!";
    yield return "Welcome to: "
    foreach (var n in names)
    {
        yield return names;
    }
}
```

While it's a contrived example, my point is having a `foreach` whose sole purpose is to flatten the return of an enumerable. I propose something like:

```C#
yield returnall names;
```

**Comment by SolalPirelli** [comment]
Duplicate of #15, I believe.

**Comment by benjamingr** [comment]
Yes, a duplicate. This is like JavaScript's `yield*` or Python's `yield from`.

**Comment by adamhewitt627** [comment]
So it is. I tried looking for that, but didn't think about it in context of recursion and was excited to share my "new" idea. Thanks anyway!
