### ISSUE TITLE
Too early closure in Release mode

### ISSUE THREAD

**Issue by xanatos** [dotnet/roslyn#50213]
With Visual Studio 16.8.3 (unclear exactly what version of C# compiler) and with the site Sharplab (using the master branch 31 dec 2020 of Roslyn) an object supporting a closure can be instantiated too early in Release mode (the generated IL code seems to be correct in Debug mode):

I link a [SharpLab](https://sharplab.io/#v2:D4AQDABCCMB0DCB7ANsgpgYwC4EtEDsBnBAjAVwCcK18sBuAWAChmQBmCHWtCgMwEMMaCAEkA8gAdcBQgDFBWRBQCeAHgAqAPmYBvZhAMR1EeNX5Y0AChiRCWCgEpGTAL7NWHEACYIAWWXwyPyEhBqS0kTaTHpMhlAcSPjkVDRYACI42Hj4/CqqNgA0RuHZhJoQAPoYggAWwgC8EPhoAO4mpJTUtBlZBLlqhcVSpZqWTvqG7KIlMvLYSmrqM5GVAvMqEI34ZKjOEwZTS8MyEADiaFjW0JA5ALZoDvsQMXFxOLwQlgCEVbVosOoVOcsAA1fjIMhWO5oIqIMhYIYRQgQRDHIgOR6xV4GF7Y142Jr8e4+LZEtDOPGvVFIzaVaoYOqwYFiCgAQQAJuzLNCigAPTblCprRQqBBmCzcsleDEUvFuLHYp5xAD0yogaUwiFu91oECwNRwyPeSsMyoAVCaDO9Pj96YzAcpgWCIVCybD4YjSii0YRpZjKbjKQdroTibTobKg96kSS6X8mRcWRyuTyIPz6oLhQsxWhzK7iTLLRB5ZSzcr3Ar8QB2aOlSPF5jyoA) with the whole code.

The code is:

    public TOptions Get(string name)
    {
        if (!_cache.TryGetValue(name, out TOptions options))
        {
            string name2 = name;
            options = _cache.GetOrAdd(name, x => _factory.Create(name2));
        }
        
        // Decomment this if
        /*
        if (!_cache.TryGetValue(name, out TOptions options2))
        {
            string name2 = name;
            options2 = _cache.GetOrAdd(name, x => _factory.Create(name2));
        }
        */

        return options;
    }

If the second _if_ is commented, in Debug mode this code is generated (correct):

    public TOptions Get(string name)
    {
        TOptions value;
        if (!_cache.TryGetValue(name, out value))
        {
            <>c__DisplayClass2_0 <>c__DisplayClass2_ = new <>c__DisplayClass2_0();
            <>c__DisplayClass2_.<>4__this = this;
            <>c__DisplayClass2_.name2 = name;
            return _cache.GetOrAdd(name, new Func<string, TOptions>(<>c__DisplayClass2_.<Get>b__0));
        }
        return value;
    }

while in Release mode this code is generated:

    public TOptions Get(string name)
    {
        <>c__DisplayClass2_0 <>c__DisplayClass2_ = new <>c__DisplayClass2_0();
        <>c__DisplayClass2_.<>4__this = this;
        TOptions value;
        if (!_cache.TryGetValue(name, out value))
        {
            <>c__DisplayClass2_.name2 = name;
            return _cache.GetOrAdd(name, new Func<string, TOptions>(<>c__DisplayClass2_.<Get>b__0));
        }
        return value;
    }

Here the _<>c__DisplayClass2_0_ is instantiated too early, and this instantiation will be useless if the code doesn't enter the _if_.

Note that if we decomment the second _if_, then both Debug and Release mode will generate the "correct" code (instantiating the _<>c__DisplayClass2_0_ only inside the _if_ s)

**Comment by jaredpar** [comment]
Thanks for taking the time to file this. This behavior though is by design / known limitation of current design. 

True the compiler could be more efficient here in this specific case. However implementing this style of optimization for the general case has been discussed a number of times and deemed to not be worth the implementation complexity of doing so.
