### ISSUE TITLE
Make IEditorFormattingService public

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50221]
We should consider making `IEditorFormattingService` public under the Features layer. Today, this component is internal in the EditorFeatures layer, and used via IVT by both F# and TS, and used by our on LSP implementation. In order to facilitate making LSP depend only on the Features layer, I've created a PR (https://github.com/dotnet/roslyn/pull/50222) to move the implementation into the Features layer, but due to the afformentioned IVTs, it will require coordination to make sure we don't break the VS build. I'd like us to consider, at the same time, making this a public interface as it exists today, which both removes one of our many IVTs and would allow omnisharp to take advantage of the same formatting that we have in VS.

@sharwell @CyrusNajmabadi I'd like to bring this to the IDE design review, could you please schedule it whenever it fits?

**Comment by sharwell** [comment]
If you just move the types, you can add a type forwarder to avoid breaking consumers. Also any consumers using restricted IVT proxies will not break if you leave the proxies in the current location.

**Comment by 333fred** [comment]
> If you just move the types

The namespace is changing as well. And even if I just moved the types, I'd still like to bring this for consideration :).

**Comment by CyrusNajmabadi** [comment]
Is this still needed @333fred ?

**Comment by 333fred** [comment]
Well, I'm not sure what service replaced `IEditorFormattingService` (as it appears to have been removed), but if it's not public, I would still like it to be so that O# can take advantage of it.

**Comment by CyrusNajmabadi** [comment]
Closing as this type doesn't exist anymore.
