### ISSUE TITLE
Loosen expression-body analyzer when there is a comment before the return

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#50229]
**Version Used**: 16.9.0 Preview 2.0

**Steps to Reproduce**:

```csharp
public ICollection<TValue> Values
{
	get
	{
		// "Values" might be accessed during dispose.
		//Debug.Assert(!IsDisposed);
		return _coreAnalysisData.Values;
	}
}
```

**Expected Behavior**:

No issue

**Actual Behavior**:
```csharp
 public ICollection<TValue> Values =>
    // "Values" might be accessed during dispose.
	//Debug.Assert(!IsDisposed);
    _coreAnalysisData.Values;
```

See https://github.com/dotnet/roslyn-analyzers/pull/4641/files#r551430100

**Comment by CyrusNajmabadi** [comment]
This is tri-state feature.  there is: `false`, `true` and `when_on_single_line`.  If you don't want the diagnostic here, use the last one.
