### ISSUE TITLE
Why is IDE0076 part of miscellaneous and not unnecessary code

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#50230]
I was looking for `IDE0076` rule on the official documentation and was surprised it was classified under "Miscellaneous rules" and not under "Unnecessary code rules". Would it be possible to change this?

**Comment by Youssef1313** [comment]
I'm not sure what determines the "Sub-category" part. But I see `isUnnecessary` for the descriptor is already true:

> https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryAttributeSuppressionsDiagnosticAnalyzer.cs#L27-L34

**Comment by Evangelink** [comment]
@Youssef1313 I'd say that the `isUnnecessary: true` is used to define whether the diagnostic is shown as fading-out the code.

**Comment by mavasani** [comment]
@Evangelink The unnecessary/fading here was primarily added for getting user's attention. It can be argued that we should use a better mechanism for highlighting invalid unnecessary code, as compared to just plain dead code. However, we are going to live with this for now unless we get more feedback.

**Comment by Youssef1313** [comment]
@mavasani I'm not getting how this relates to the fact that IDE0076 is documented as misc, not unnecessary?
What are the factors that determines the documented sub-category? How IDE0076 (documented as miscellaneous) is different than IDE0079 (documented as unnecessary)?

**Comment by mavasani** [comment]
@Youssef1313 The core difference is that `IDE0076` is flagging a correctness issue - you have code which is invalid, and hence rendering it unnecessary. `IDE0079` on the other hand is purely dead code.

**Comment by Youssef1313** [comment]
I don't get the difference. Both rules report unnecessary suppressions. One reports the `#pragma` syntax and the other reports the attribute syntax. But semantically I see both are equivalent.

**Comment by mavasani** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0076 - the underlying issue is correctness issue whose fix involves fixing the invalud Target or Scope string for the suppress message attribute.

Underlying issue for IDE0079 is just dead code, whose fix involves removal of the unnecessary suppression.

**Comment by Youssef1313** [comment]
Oh I thought IDE0076 is unnecessary attribute removal. That makes sense. Thanks.
