### ISSUE TITLE
A snippet of incorrect code causes internal error or crashes VS2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50232]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/A-snippet-of-incorrect-code-causes-inter/1296249)._

---
[severity:It bothers me. A fix would be nice]
Adding the following method to a console application either causes a number of internal error notifications to appear or crashes VS2019 entirely:

```
public static int GetValue(Color color)
{
    const int red = Color.Red.ToArgb();
    return color. ToArgb() switch
    {
        red => 1
    };
}
```

Tested with:
- VS2019 Community 16.9.0 Preview 2.0 (causes internal error notifications)
- VS2019 Enterprise 16.8.3 (causes a crash)

---
#### Feedback Bot on 12/24/2020, 06:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Looks like a regression, there is no crash in an older branch, but there is on master:

![image](https://user-images.githubusercontent.com/31348972/103625084-1cd42380-4f43-11eb-8c23-9817d380e369.png)

---

![image](https://user-images.githubusercontent.com/31348972/103625108-28274f00-4f43-11eb-8076-2fbdf398ad1f.png)

**Comment by AlekseyTs** [comment]
@cston Could you add a link to the WorkItem that was converted to this issue at the beginning of description above?
