### ISSUE TITLE
Is it possible to read the checksumalgorithm from a managed pdb?

### ISSUE THREAD

**Issue by eddynaka** [dotnet/roslyn#50235]
Hi,

reading this blog post: https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/march/visual-studio-hashing-source-code-files-with-visual-studio-to-assure-file-integrity, I saw a reference for DiaSymReader to read the pdb and check if the checksumalgorithm is SHA256 or not.

Looking at the interface and trying the package I couldn't figure it out.

I also saw that it is recommended to move the Metadatareader, but, I'm trying to read non-portable pdbs.

So, I would like to check if that is possible and if you have an example for that.

Thank you!

**Comment by tmat** [comment]
You can find a sample code in https://github.com/dotnet/symreader-converter/blob/master/src/Microsoft.DiaSymReader.Converter.Xml/PdbToXml.cs.
This tool prints information from Windows (or Portable) PDB to an XML file.

**Comment by jaredpar** [comment]
Please let us know if the link @tmat listed does not answer this for you
