### ISSUE TITLE
'Change signature...' no longer preselects the parameter the caret was on

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#50241]
**Version Used**: 16.8.3 and 16.9.P2

The 'Change signature...' fix used to initialize the selection in the dialog to whichever parameter the caret was on when the light bulb was invoked.

```cs
class C
{
    void M(
        int a,
        int b,
        int c[||])
    {
    }
}
```

This is now broken:

![image](https://user-images.githubusercontent.com/8040367/103587494-61b17900-4eb5-11eb-99e0-22f8a4d9d8e5.png)

/cc @jcouv because of https://twitter.com/jcouv/status/1257778736063102977

**Comment by jcouv** [comment]
I'd noticed this stopped working (at least in some cases). Not sure what happened. Thanks @allisonchou for the fix!
