### ISSUE TITLE
VB GetClassifiedSpansAsync returns additional out of order Spans

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#50248]
**Version Used**: 
3.8
**Steps to Reproduce**:

When running code below an additional overlapping Span was added at the end of type "string - escape character"
```
Dim document As Document = document = project.AddDocument("name.vb", "test1 = "Simple""Test"")
Dim text As SourceText = document.GetTextAsync().Result
Dim classifiedSpans As List(Of ClassifiedSpan) = Classifier.GetClassifiedSpansAsync(document, TextSpan.FromBounds(0, text.Length))
```
The logic in RemoveAdditiveSpans to call ClassificationTypeNames.AdditiveTypeNames.Contains(span.ClassificationType) to remove additive type names does not contain any VB names. "string - escape character" is a new VB additive name. 
**Expected Behavior**:

I previously got 3 spans, now I am getting 4
Either Additive Names should not be in VB or ClassificationTypeNames.AdditiveTypeNames should contain VB names to filter out. There may be other VB additive Types similar to what exist in C# I did not check.
**Actual Behavior**:
"test1 = "Simple""Test"" is classified as having 4 spans (it previously had 3) and the 4th is span 15-17 of type "string - escape character" which overlaps with the third span.

**Comment by CyrusNajmabadi** [comment]
This is by design. We added classification of sub ranges of strings.

**Comment by paul1956** [comment]
@CyrusNajmabadi wouldn't you then expect 5 ordered ranges
```
test1
=
"Simple
""
Test"
```
Not
```
test1
=
"Simple "" Test"
""
```

**Comment by CyrusNajmabadi** [comment]
No. They're produced by different subsystems, and we still want to classify the full spans for consumers that use that info.

**Comment by paul1956** [comment]
@CyrusNajmabadi I have been consuming the API for years recently, I am getting new out of order items. That seems like a breaking change.

**Comment by CyrusNajmabadi** [comment]
>@CyrusNajmabadi I have been consuming the API for years.

We don't guarantee that these APIs will continue to return the exact same results over time.  Things like classification are all subject to change as, well, we've added new classifications :)

> Where can I find documentation on what was changed

I don't believe we have documented this at all.

> Does the full span always appear first 

I don't believe there would be any guarantee of that.

>  and if I see an overlapping span either ignore it or split the previous span and use the newer classification?

How you want to handle this is ultimately up to you.  I would not presume though that there will be any guaranteed ordering here.  Can you not just collect all the spans and then post process them as you see fit?
