### ISSUE TITLE
Codelens doesn't display information on source-generated code

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/roslyn#50252]
I have a collection of interfaces and classes that I source-generate with a roslyn SG to reduce repetitive code for a set of APIs. I regularly try to identify unused methods in my code base, so I often use CodeLens to see all the usages of e.g. a method. I can navigate to source in Visual Studio, but the reverse doesn't seem possible.
CodeLens seems to be generally unavailable on generated code. The feature "Find all references" also doesn't show any results, regardless of whether the selected method is used or not.
Please consider adding support for this, as it would improve my workflow considerably (as a workaround, I have to copy the generated code into a file and disable generation).

**Comment by jasonmalinowski** [comment]
Going to close this in favor of https://github.com/dotnet/roslyn/issues/50676; it's a core infastructure change that will fix a bunch of other features too, so no reason to track it on a feature-by-feature basis.

**Comment by jasonmalinowski** [comment]
Going to reopen this one since this is also going to require a CodeLens-specific fix.

**Comment by jasonmalinowski** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/53043.
