### ISSUE TITLE
SyntaxGenerator.MemberAccessExpression wraps result in parenthesis when a nullability modifier is detected

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#50260]
## Version Used

3.3.1 (latest used in dotnet/roslyn-analyzers)

## Steps to Reproduce

Having a method invocation whose instance is using a nullability bang, substitute the invocation with a different method overload, preserving nullability modifiers.

See PR: https://github.com/dotnet/roslyn-analyzers/pull/4664/files

Code fixer file: `PreferStreamAsyncMemoryOverloads.Fixer.cs`

## Expected Behavior

Consider this code:

```cs
#nullable enable
using System;
using System.IO;
using System.Threading.Tasks;
public class C
{
    async ValueTask M(Stream? stream, byte[]? buffer)
    {
        await stream!.WriteAsync(buffer!, offset: 0, count: buffer!.Length).ConfigureAwait(false);
    }
}
```

The expectation is that CA1835 would preserve the nullability modifiers after changing the overload:

```cs
#nullable enable
using System;
using System.IO;
using System.Threading.Tasks;
public class C
{
    async ValueTask M(Stream? stream, byte[]? buffer)
    {
        await stream!.WriteAsync(buffer!.AsMemory(start: 0, length: buffer!.Length)).ConfigureAwait(false);
    }
}
```

## Actual Behavior

What's currently happening is that `generator.MemberAccessExpression` unexpectedly wraps the nullable node with unnecessary parenthesis:

```cs
#nullable enable
using System;
using System.IO;
using System.Threading.Tasks;
public class C
{
    async ValueTask M(Stream? stream, byte[]? buffer)
    {
        await (stream!).WriteAsync((buffer!).AsMemory(start: 0, length: buffer!.Length)).ConfigureAwait(false);
    }
}
```

Interestingly, the `buffer!.Length` argument is left untouched (no parenthesis added), presumably because the actual object is `Length`, which does not have nullability modifiers.

Fortunately, this unexpected behavior does not cause a build break, but the parenthesis were not there in the first place, and are not necessary, so `MemberAccessExpression` should not have added them.

**Comment by CyrusNajmabadi** [comment]
To anyone who wants to fix this:

1. SyntaxGenerator.MemberAccess will *always* add the parens.  That is normal.  *However*:
2. We have a cleanup pass that wants to remove these parentheses later if they're not necessary. This is hte code that needs to be updated.

**Comment by V0ldek** [comment]
So the relevant cleanup pass code that @CyrusNajmabadi mentioned is in `Microsoft.CodeAnalysis.CSharp.Extensions.ParenthesizedExpressionSyntaxExtensions.CanRemoveParentheses` that determines whether it is safe to remove parantheses from a given expression. At first glance it apperas sufficient to just add an explicit case for the bang pattern:

```
// (x!) -> x!
if (expression.IsKind(SyntaxKind.SuppressNullableWarningExpression))
{
    return true;
}
```

But, is it always safe to remove parans from a bang operator expression for _any_ operand? It obviously works if the banged expression is just a simple or dotted name, but maybe there is a case where semantics change? Maybe the correct course of action would be to extract the operand, paranthesise it artificially and run the `CanRemoveParentheses` check recursivelly, under the assumption that it is safe to remove parans from around a bang operator expression if the expression without the bang would be safe?

**Comment by Youssef1313** [comment]
This might already have been fixed.

![image](https://user-images.githubusercontent.com/31348972/208050803-49ae58fd-6a6e-4d50-8e0b-0dca4511c7e1.png)

**Comment by Youssef1313** [comment]
Yes. Apparently, I updated the Roslyn version that is used for tests in https://github.com/dotnet/roslyn-analyzers/pull/5967 and related tests no longer have the extra parentheses.

@CyrusNajmabadi This can be closed.

**Comment by CyrusNajmabadi** [comment]
Thanks. Closing out
