### ISSUE TITLE
[Regression] Preview changes dialog for FixAll does not show correct diffs when unchecking changes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#50262]
**Version Used**: Version 16.9.0 Preview 3.0 [30904.5.main]

**Steps to Reproduce**: Invoke a FixAll in Project/Solution for any code fix

**Expected Behavior**:
Unchecking the checkbox for any change in the Preview changes dialog should show the original code prior to fix in the preview

16.8.3 has expected behavior:
![PreviewChangesDialog_16_8_3](https://user-images.githubusercontent.com/10605811/103693207-c3bdbd00-4f4d-11eb-816a-7911004f8085.gif)

**Actual Behavior**:
Unchecking the checkbox for any change in the Preview changes dialog still shows the fixed code (fortunately applying the fix does the right thing, so the regression is just in the Preview changes dialog)

16.9.x has regressed behavior:
![PreviewChangesDialog_16_9_Dogfood](https://user-images.githubusercontent.com/10605811/103693216-c91b0780-4f4d-11eb-8d08-59277e9550fa.gif)

**Comment by mavasani** [comment]
@jasonmalinowski This likely regressed with https://github.com/dotnet/roslyn/pull/49797

**Comment by jasonmalinowski** [comment]
@mavasani Yeah, that was probably me. :smile:

**Comment by mavasani** [comment]
NOTE: I felt this highly affected my FixAll review experience. When there are multiple complex edits in a FixAll operation, previous experience allowed me to quickly confirm the change in each edit, this is no longer possible.
