### ISSUE TITLE
CamelCase awareness in expand/shrink selection

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50279]
Direct customer ask copying here: 

> I can’t get expand/shrink selection to function properly. It seems it’s not camelCase aware, so that if I have a variable myCamelCaseVariable and use the keyboard shortcut to select the first part of it, it immediately selects the entire variable, not the part of it the caret is placed in. I see the same symptom when navigating code with Ctrl + left/right arrow, the caret just jumps past entire variables, and not within the individual parts. Is it possible to configure the VS2019 editor to become camelCase aware?

> One more: when I have the cursor inside a string literal, e.g. in the middle of "string" in the literal "This is a string" and use the shortcut for “Expand selection”, the entire string, including the quotation marks, is selected. I would like the single word I’m situated in to be selected first, then I’d click the shortcut once more if I want the entire contents of the string to be selected, then a third time if I also want to include the quotation marks.

**Comment by CyrusNajmabadi** [comment]
While i agree with much of this, we would likely need optoins for this as changing the default behavior would be bad for many users.  This part in particular:

> when navigating code with Ctrl + left/right arrow, the caret just jumps past entire variables, and not within the individual parts

This is definitely expected behavior, and it would likely be bad to change this.  We could have an option though to request this style of navigation for users that wanted that.

**Comment by mikadumont** [comment]
I agree to add an option in the editor for these behaviors.

**Comment by CyrusNajmabadi** [comment]
This should be handled by editor.  Tagging @olegtk .
