### ISSUE TITLE
Generation of constructors doesn't work as expected 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50280]
Direct customer ask copying here:

> Generation of constructors don’t work as expected in VS for example I have multiple members that needs to be initialized in construction, VS generates multiple constructors with each member instead of one constructor with all members.

**Comment by CyrusNajmabadi** [comment]
I don't know what this means.  We have this already:

![image](https://user-images.githubusercontent.com/4564579/103808358-b4ea0f80-500c-11eb-8c8e-da26e8ae3d4a.png)

![image](https://user-images.githubusercontent.com/4564579/103808362-b9aec380-500c-11eb-8537-91bfdcfeabd5.png)

![image](https://user-images.githubusercontent.com/4564579/103808372-be737780-500c-11eb-83b9-ac4c1e626182.png)
