### ISSUE TITLE
Implement missing methods from interface generates them in random location

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50281]
Direct customer ask copying here: 

> Implement missing methods from interface generates them in random location, in resharper new method in the interface was generated after the last method in the interface.

**Comment by CyrusNajmabadi** [comment]
This is already effectively supported:

![image](https://user-images.githubusercontent.com/4564579/103808555-009cb900-500d-11eb-89c9-76ae4c692000.png)

The current approach isn't random.  It keeps the type grouped by member kind (i.e. keeping properties togehter, and methods together, etc.).  But you can ask for that not to happen.
