### ISSUE TITLE
Autocomplete to classes doesn't work until I write the full name

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50282]
Direct customer ask copying here: 

> Autocomplete to classes in the references or other projects in the Sln doesn’t work until I write the full name.

**Comment by CyrusNajmabadi** [comment]
Didn't @genlu add this exact feature?

**Comment by genlu** [comment]
As long as it's referenced (either as PE or project ref) in the proj file, it should show up as "unimported". Could you check with the customer to get some details on their ask? Also it sounds like by "write the full name" they are referring to the AddImport codefix instead of completion?

**Comment by mikadumont** [comment]
> As long as it's referenced (either as PE or project ref) in the proj file, it should show up as "unimported". Could you check with the customer to get some details on their ask? Also it sounds like by "write the full name" they are referring to the AddImport codefix instead of completion?

I will check with the customer. Thanks @genlu.
