### ISSUE TITLE
16.9 Public API Followup

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50297]
* [x] ~~Potentially add `TextDocumentKind.SourceGeneratedDocument`. We're adding a new `Document` subclass for source-generated documents, but we currently haven't added a new `TextDocumentKind` for the class. @jasonmalinowski will investigate whether adding a new kind will be more harmful or helpful to customers and follow up on whether we should add a new kind, make `SourceGeneratedDocument` a separate type deriving from `TextDocument`, or some combination of both/neither.~~ (Transferred to #50912)
* [x] `SourceGeneratedDocument.SourceGenerator`: this is being used to power the solution explorer view in VS today, but we don't want to return an `ISourceGenerator` directly. It will complicate implementation if we want to move source generators OOP, as the assembly will also have to be loaded in VS and we'll have to marshall instances across OOP. We'd also be exposing the generators to consumers who might then call methods on the generator, but they really shouldn't be doing so. We'll make this into a opaque type that we can modify the internals of without breaking consumers. Assigned to @jasonmalinowski.
* [x] `SymbolDisplayPartKind.RecordName`: This should be renamed to `RecordClassName`, for consistency when we add record structs to C#. @333fred will rename this.
* [x] `ClassificationTypeNames.RecordName`: This should likely also be renamed to `RecordClassName`, but @CyrusNajmabadi should first make sure that we would not instead combine classifications (ie classify as both `RecordName` and `ClassName`). FYI to @JoeRobich, O# will need to update when this is merged.
* [x] `DeclarationKind.Record`: This is used for the syntax generator. We should check to see whether we would want both `Record` and `RecordClass`, to allow generating either `record` or `record class`, but as that would likely be controlled by editorconfig, we should likely just rename and have the one enum element. @CyrusNajmabadi will look at this as well.
* [x] Can we avoid publicly exposing `FixAllContext.WithDocument`, `FixAllContext.WithProject`, and `FixAllContext.WithDocument`? @CyrusNajmabadi and @mavasani will look at this.

**Comment by CyrusNajmabadi** [comment]
> ClassificationTypeNames.RecordName: This should likely also be renamed to RecordClassName, but @CyrusNajmabadi should first make sure that we would not instead combine classifications (ie classify as both RecordName and ClassName). FYI to @JoeRobich, O# will need to update when this is merged.

Let's go with RecordClassName.

**Comment by jasonmalinowski** [comment]
For the second checkbox, https://github.com/dotnet/roslyn/pull/50547 at least hides the API so we don't ship in a bad state. The tracking bug linked will track making a proper API.

**Comment by CyrusNajmabadi** [comment]
For `ClassificationTypeNames.RecordName` i think we should rename to `ClassificationTypeNames.RecordClassName` and then add `ClassificationTypeNames.RecordStructName` when appropriate.  

For `DeclarationKind.Record` that should be `DeclarationKind.ClassRecord`.

Did you want me to make those changes @333fred , or was someone else going to?  I'd def like to load balance here.

**Comment by 333fred** [comment]
@CyrusNajmabadi `DeclarationKind.ClassRecord` or `DeclarationKind.RecordClass`?

**Comment by CyrusNajmabadi** [comment]
@333fred  what si the syntax going to be `public record class` or `public class record`?  whichever we pick is what the kind should match.

**Comment by 333fred** [comment]
I expect `RecordClass`

**Comment by jasonmalinowski** [comment]
I'm breaking out the first bullet point to https://github.com/dotnet/roslyn/issues/50912; in that case the code that would be likely broken is not new code, so making a change now vs. 16.10 isn't that much different; if anything trying such a change early in 16.10 gives us more time to find the potential fallout.

**Comment by 333fred** [comment]
All 16.9 issues are now addressed, closing out.
