### ISSUE TITLE
Some rules doesn't have correct help link

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50302]
**Version Used**: 

https://github.com/dotnet/roslyn/pull/50278/commits/29f7328867c68615c42dade4d2eecb193902fea1

**Steps to Reproduce**:

In https://github.com/dotnet/roslyn/pull/50278/commits/29f7328867c68615c42dade4d2eecb193902fea1, run `dotnet test --filter "FullyQualifiedName~CSharp_VerifyIDECodeStyleOptionsAreConfigurable"` in `src\EditorFeatures\Test`

The result is:

```
  Error Message:
   Invalid help link for IDE0001
```

The issue is simply in:

https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L48-L54

**Comment by Youssef1313** [comment]
Same issue for IDE0002 and IDE0049

**Comment by Youssef1313** [comment]
For IDE0001 and IDE0002 doesn't have the corresponding EnforceOnBuild value.

Tagging @mavasani.

**Comment by mavasani** [comment]
Thanks @Youssef1313 - this seems to be a good justification to ban DiagnosticDescriptor ctor even in Features folder in the repo, unless you are planning to add test validation for all IDE analyzers to have a help link. I am fine with doing both these changes actually.
