### ISSUE TITLE
PreferBuiltInOrFrameworkTypeDiagnosticId is used in two analyzers

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50307]
Why is this needed here? there is already a separate analyzer for this:

https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Features/Core/Portable/PreferFrameworkType/PreferFrameworkTypeDiagnosticAnalyzerBase.cs#L12

Both are even using the same ID.

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn/pull/50305#discussion_r553377655_

**Comment by Youssef1313** [comment]
Tagging @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I'm honestly not undestanding the question.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi The same diagnostic id is used in two different analyzers: SimplifyTypeNames and PreferFrameworkType

https://github.com/dotnet/roslyn/blob/20cd3aae8c2079b857e43e718afa34c508edd3c8/src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L59-L66

https://github.com/dotnet/roslyn/blob/20cd3aae8c2079b857e43e718afa34c508edd3c8/src/Features/Core/Portable/PreferFrameworkType/PreferFrameworkTypeDiagnosticAnalyzerBase.cs#L12-L25

Shouldn't only the PreferFrameworkType analyzer be responsible for reporting IDE0049?

**Comment by CyrusNajmabadi** [comment]
Seems reasonable.  What happens if you make that change?

**Comment by Youssef1313** [comment]
> Seems reasonable. What happens if you make that change?

I haven't yet tried. I'll try to give a look soon.

**Comment by Youssef1313** [comment]
Not a bug, sorry!

One analyzer goes from framework types to built-in, and the other goes in the opposite direction. Closing out.
Sorry for the mis-information
