### ISSUE TITLE
Disruption from "breaking" NullableReferenceType changes in Visual Studio updates

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#50309]
Apologies in advance if this is filed in the wrong place.

**Version Used**: 

Various recent VS versions (up to and including 16.8.3), C#8.

**Steps to Reproduce**:

We have a large number of C# projects whose setups include:
```
<LangVersion>8.0</LangVersion>
<Nullable>enable</Nullable>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```

This is desirable because we want to leverage nullable reference types and we want the build to fail when those typings are violated.

However, our experience has been that each new Visual Studio update seems to introduce or slightly change when nullable reference errors are emitted. Sometimes these seem to be bugs as in https://github.com/dotnet/roslyn/issues/50286 and https://github.com/dotnet/roslyn/issues/50311; other times it is clear that the compiler is getting "smarter" about detecting real issues or allowing things that should have been valid all along.

The problem is that these new errors start firing on existing code even when the language version is fixed in the csproj. As a result, we frequently have issues where developers write code that builds on their machines but fails to build on others' machines, or where things build successfully locally but fail to build on our CI server whose MSBuild is slightly older (but still supports C#8). In other cases, updating VS leads to new errors in a codebase that previously compiled.

**Expected Behavior**:

Locking in the language version should allow for consistent compilation of the same code across machines (barring the rare compiler bug). Maybe there is another setting to guarantee this that I'm missing?

**Actual Behavior**:

Compiler updates frequently break compilation of existing code.

**Comment by canton7** [comment]
If you're not aware, you can fix the SDK version in [global.json file](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x).

**Comment by madelson** [comment]
@canton7 I was not aware. That might be exactly what I'm looking for to resolve this.

**Comment by jaredpar** [comment]
I'm sorry that this has caused a bit of friction for your team. However this is expectation is that the warnings around nullable reference types is that they will evolve during the [nullable rollout phase](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/#the-nullable-rollout-phase) for .NET. 

Nullable reference types is too big of a feature to get to 100% completeness in the language, SDK and library ecosystem in a single release. Instead the expectation is that it would take a few releases to complete the feature. During the time where the feature is being rolled out we would adjust the rules for nullable warnings based on feedback from customers and scenarios that were negatively impacting their ability to adopt them. 

The overwhelming majority of changes have been to reduce the number of places where nullable warnings are emitted (compiler can better detect when `null` values won't occur). However there have been a few times where we deliberately inserted new warnings where we felt the benefit was significant. 

Going forward though the amount of churn here is expected to be slowing down significantly. There will still be work done on nullable reference types but our core scenarios are pretty firmly established now, new work is pretty much exclusively focused on reducing warnings for commonly reported cases.  New warnings are treated with an ever raising bar for acceptance. 

> Locking in the language version should allow for consistent compilation of the same code across machines (barring the rare compiler bug). 

The purpose of the language version flag is not to fix compiler analysis at given version but rather to prevent code from using features defined in a higher version of the language. For example if you set language version to 7.2 the compiler will warn whenever you attempt to use nullable reference types. Setting it to 8.0 allows the use of nullable reference types but it does not guarantee the exact same analysis as produced by the 8.0 compiler.

**Comment by madelson** [comment]
Thanks for the context @jaredpar this is good to know. 

> Going forward though the amount of churn here is expected to be slowing down significantly. There will still be work done on nullable reference types but our core scenarios are pretty firmly established now, new work is pretty much exclusively focused on reducing warnings for commonly reported cases. New warnings are treated with an ever raising bar for acceptance.

I'm particularly glad to hear this!
