### ISSUE TITLE
Cant get documents inside of a projec that I loaded with a solution

### ISSUE THREAD

**Issue by UmutUz** [dotnet/roslyn#50319]
### Issue Description

Loading a solution with OpenSolutionAsync then getting those projects and then the source files (.cs) inside those projects doesn't work. I can load the solution and read out every project inside of it. But when I get to the part to get all the names/filepaths of the source files, there are none. project.HasDocuments; gives false back too, so MSBuild cant find anything inside those projects. There are also no error codes. Tried to use the diagnostics verbosity which was recommended on the microsoft site, still nothing in the terminal
### Steps to Reproduce

string sln = path;

                MSBuildWorkspace workspace = MSBuildWorkspace.Create();
                Solution solution = await workspace.OpenSolutionAsync(sln);  //Workspace und Solution laden

                foreach (var projectId in solution.ProjectIds)
                {
                    var project = solution.GetProject(projectId);
                    
                    MessageBox.Show(projectId.ToString());
                    
                    bool test = project.HasDocuments;

                    foreach (var documentId in project.DocumentIds)
                    {
                        Document document = project.GetDocument(documentId);
                        ...
}
### Expected Behavior

Getting all documents name/filepath inside of a project.
### Actual Behavior

Project has no documents nor documentIds or anything related to that.
### Ask us questions

I have absolutely no clue, I am a complete noob and honestly what I expect is the same think that happened in this tutorial video if it helps, its at the very beginning (actually the first thing the dude does): https://www.youtube.com/watch?v=Du3YaPuy6pY
If anyone can help, I would appreciate it.

**Comment by UmutUz** [comment]
> This is an issue with a Roslyn API, not MSBuild itself. Moving to the Roslyn repo.

Well, I COMPLETELY forgot about this and since then somehow made it work. Problem was .netcore. Needed to use .net framework. I feel god awful for being so stupid. Sorry for wasting time :/ For whatever reason tho even in .net Framework MSBuild and Roslyn struggle with each other. Anyway thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out.  Sorry for any troubles you had!
