### ISSUE TITLE
Go To All to have more accurate results at the top

### ISSUE THREAD

**Issue by mika1490** [dotnet/roslyn#50314]
Direct customer ask copying here: 

> I’m looking for a class (not file) called “DependencyContainerCreator” in namespace “X”. ReSharper (Search Everywhere): I type “depe” and can find it immediately as 2nd entry whereas Visual Studio (Go To All): I type “depe” and the result is at the end of the visible list.

**Comment by CyrusNajmabadi** [comment]
Can the customer show what other results they get?  `depe` should be a `case insensitive prefix` match.  That's one of the top types of matches we get, beaten only by exact matches, or case sensitive prefix matches.

Without more information, this isn't really actionable.

**Comment by jinujoseph** [comment]
@mika1490 to followup with customer

**Comment by mikadumont** [comment]
> @mika1490 to followup with customer

I went over the customer's example with @CyrusNajmabadi and this work seems to be platform specific.
