### ISSUE TITLE
VS 16.9 Preview 2 - csc exited with code -2146232797

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50316]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1262855

_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-169-Preview-2---csc-exited-with-code/1302276)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9 preview 1]
Issue has started occurring since updating VS 16.9 Preview 1 to VS 16.9 Preview 2. There's a particular project that fails to build, resulting only in the error message below.

I'm hoping that the diagnostic data available from the "recording" I did is sufficient to investigate the issue because unfortunately the problematic project is part of a very large solution with a lot of dependencies, so it would not be feasible for me to provide it.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.exe" exited with code -2146232797.

I do however have a stack-trace from the Windows Event Viewer of the csc.exe process throwing a .NET Runtime error, that may help explaining why csc.exe crashed, attached as 'csc-stacktrace.txt'.

---
#### Feedback Bot on 1/5/2021, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fred Silberberg [MSFT] on 1/7/2021, 01:11 PM: 

<p>It appears that the upload on the heap dump didn’t start @<a target='_blank' href="https://developercommunity2.visualstudio.com/users/241769/johanrensenbrink.html">johan.rensenbrink</a>. I’ll try and see if I can reproduce it from just the stack, but in the meantime can you please try:</p>
<ol>
<li>Open VS 16.9 P2 again and leave it open for a bit. Theoretically, you should see a DiagnosticsCollector process start up, and/or you should see network traffic uploading the heap dump.</li>
<li>If you do not, please check C:\Users\AppData\Local\Temp\Microsoft\VSFeedbackCollector\VSFeedback_Collector_ or %LOCALAPPDATA%\CrashDumps for a heap dump, and attach them as a reply to this thread. Make sure to set the comment as private to Microsoft only.</li>
<li>If you don’t have the heap dump anymore, let me know and we figure something else out.</li>
</ol>

#### Fred Silberberg on 1/7/2021, 01:46 PM: 

<p>Actually, I believe I was able to reproduce this bug just from that stack. I’m going to move this to the dotnet/roslyn repo for further tracking.</p>

---
### Original Solutions
(no solutions)

**Comment by 333fred** [comment]
```cs
using System.Collections.Generic;
using System.Linq;

var c = new C();
var test = from i in c[1]
           select i;

public class C {
    public IEnumerable<int> this[int i1, object o = null]
    {
        get => null;
        set {}
    }
}
```

**Comment by AlekseyTs** [comment]
@333fred Could you please include the link to the original DevDiv work item that was ported to GitHub to create this issue.

**Comment by 333fred** [comment]
> @333fred Could you please include the link to the original DevDiv work item that was ported to GitHub to create this issue.

The first line of this issue has the link.

**Comment by AlekseyTs** [comment]
>> Could you please include the link to the original DevDiv work item that was ported to GitHub to create this issue.

>The first line of this issue has the link.

I am talking about a link like ```https://devdiv.visualstudio.com/DevDiv/_workitems/edit/<nnnnn>```. It doesn't look like the first link on the issue goes there.

**Comment by 333fred** [comment]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1262855
