### ISSUE TITLE
Foreach snippet carat position request

### ISSUE THREAD

**Issue by mika1490** [dotnet/roslyn#50332]
Direct customer ask copying here: 

>I have to hit Tab twice for snippets. Resharper only requires one Tab.
 
![image](https://user-images.githubusercontent.com/19830282/104041950-a75c9300-518e-11eb-958c-573f8fe04fb8.png)

> The first carat position in the foreach snippet is over ‘var’. Resharper puts the carat over the enumerable, and uses the name typed to help name the iteration variable.

> The Intellisense in the ‘var’ portion doesn’t suggest using the explicit class type.

> And pressing Tab in a snippet never moves the carat inside the body. For example, in the ‘for’ snippet, pressing Tab will only move the caret back and forth between the iterator variable and the end condition, never inside the curly braces.

**Comment by sharwell** [comment]
Marking as help wanted: we would like to provide this feature behind an option.

* The option should be disabled by default
* The option should be automatically set to enabled when the user selects the **ReSharper (Visual Studio)** keyboard mapping scheme under **Tools &rarr; Options... &rarr; Environment &rarr; Keyboard**
* The option should be automatically set to enabled by the gold bar that offers to fix keyboard mappings after ReSharper is disabled

**Comment by CyrusNajmabadi** [comment]
Closing out due ot lack of feedback.
