### ISSUE TITLE
Cref's should not require fully qualified names for record types

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#50330]
**Version Used**: VS 16.9 P3 (30907.158.main)

**Steps to Reproduce**:

```cs
using System;

/// <summary>
/// Something with a <see cref="String"/> instance.
/// </summary>
record CacheContext(String RelativePathBase);
```

Or see [Sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgEwCMAsAFDUD09ABADxQCuYkCAngHx2MBlAPZg4MABZoAdgHMGAdzQSGEZlDhwGAYwRwAZgF4ARAJgJpMo7R4NpsCFK1wAdP1rNabDhG58qurSEEbAYAYQgtcThQoSl4AA8YAApTc1kGACU4DAgYNAA3OAAFXPEAIWg4AEoAbmogA=)

**Expected Behavior**:

No compiler warnings.

**Actual Behavior**:

A compiler warning:

> warning CS1574: XML comment has cref attribute 'String' that could not be resolved

**Comment by AArnott** [comment]
This bug is very peculiar. In the most trivial case given above the bug repros. It also repros here in failing to bind the `cref` that is imported via `using`:

```cs
namespace Microsoft.VisualStudio.Cache
{
    using System.Collections.Generic;
    using Microsoft.VisualStudio.Cache;
    using Microsoft.VisualStudio.RpcContracts.Caching;

    /// <summary>
    /// Context that parameterizes an initialized <see cref="CacheService"/> instance.
    /// </summary>
    public record CacheContext(string? RelativePathBase, IReadOnlyDictionary<string, string?> Dimensions);
}
```

But if I move the `using` directives *outside the namespace block*, suddenly binding happens and the warning goes away:

```cs
using System.Collections.Generic;
using Microsoft.VisualStudio.Cache;
using Microsoft.VisualStudio.RpcContracts.Caching;

namespace Microsoft.VisualStudio.Cache
{
    /// <summary>
    /// Context that parameterizes an initialized <see cref="CacheService"/> instance.
    /// </summary>
    public record CacheContext(string? RelativePathBase, IReadOnlyDictionary<string, string?> Dimensions);
}
```

And for whatever reason, no namespace at all also binds successfully, in spite of the trivial case in the issue description not declaring a namespace either:

```cs
using System.Collections.Generic;
using Microsoft.VisualStudio.Cache;
using Microsoft.VisualStudio.RpcContracts.Caching;

/// <summary>
/// Context that parameterizes an initialized <see cref="CacheService"/> instance.
/// </summary>
public record CacheContext(string? RelativePathBase, IReadOnlyDictionary<string, string?> Dimensions);
```

**Comment by jaredpar** [comment]
Yet another reason to prefer `string` over `String` 😉 

Thanks for reporting. We'll take a look. @jcouv is doing some work in this area for parameter binding.

**Comment by Youssef1313** [comment]
I'm not able to write a failing test for this:

Wrote the following and it passes.

```csharp
        [Fact]
        public void OnRecord()
        {
            var source = @"
using System;

/// <summary>
/// Something with a <see cref=""String""/> instance.
/// </summary>
record CacheContext(String RelativePathBase);
";
            var comp = CreateCompilation(source, parseOptions: TestOptions.RegularWithDocumentationComments, targetFramework: TargetFramework.StandardLatest);
            comp.VerifyDiagnostics();
        }
```

But the `main` branch in SharpLab is showing a warning, so the bug is still there 👀

**Comment by Youssef1313** [comment]
Hmm, changing the target framework to `TargetFramework.NetCoreApp` makes a failing test as expected.

**Comment by Youssef1313** [comment]
One thing I noted while debugging (may or may not be relevant):

https://github.com/dotnet/roslyn/blob/f7c308ccb0658bce207059b51d1da6f55841c0f8/src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs#L88

The binder chain here when the comment is placed on a class is:

```
{Microsoft.CodeAnalysis.CSharp.WithCrefTypeParametersBinder}
{Microsoft.CodeAnalysis.CSharp.Binder}
{Microsoft.CodeAnalysis.CSharp.InContainerBinder} (NamedType)
{Microsoft.CodeAnalysis.CSharp.InContainerBinder} (Global namespace)
{Microsoft.CodeAnalysis.CSharp.WithExternAndUsingAliasesBinder.FromSyntax}
{Microsoft.CodeAnalysis.CSharp.WithUsingNamespacesAndTypesBinder.FromSyntax}  --> This is the binder that does the job.
{Microsoft.CodeAnalysis.CSharp.BuckStopsHereBinder}
```

For records:

```
{Microsoft.CodeAnalysis.CSharp.WithCrefTypeParametersBinder}
{Microsoft.CodeAnalysis.CSharp.Binder}
{Microsoft.CodeAnalysis.CSharp.InContainerBinder} (global namespace)
{Microsoft.CodeAnalysis.CSharp.WithExternAliasesBinder.FromSyntax}
{Microsoft.CodeAnalysis.CSharp.BuckStopsHereBinder}
```

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Compilers/CSharp/Portable/Binder/BinderFactory.BinderFactoryVisitor.cs#L1300-L1306

Issue is typeDeclSyntax.OpenBraceToken.SpanStart. There is no open brace token here.
