### ISSUE TITLE
snippets for `else` to automatically add a new line

### ISSUE THREAD

**Issue by mika1490** [dotnet/roslyn#50335]
Direct customer ask copying here: 

> ‘else’ blocks aren’t formatted to add a new line when created:

![image](https://user-images.githubusercontent.com/19830282/104043572-da078b00-5190-11eb-87bd-6ff1741fd033.png)

**Comment by sharwell** [comment]
I'm not able to reproduce this. I tested all of the following:

1. Typing `else` followed by <kbd>Tab</kbd>, <kbd>Tab</kbd> (snippet)
2. Typing `else` followed by <kbd>{</kbd>, <kbd>}</kbd>
3. Typing `else` followed by <kbd>{</kbd>, <kbd>Enter</kbd>
4. Manually entering the scenario above, and selecting `[|else { }|]` followed by **Edit &rarr; Advanced &rarr; Format Selection**

**Comment by Youssef1313** [comment]
@sharwell Probably the original reporter meant a new line before the `else`?
