### ISSUE TITLE
Parameter info disappears when pressing down or up in multi-line method invocation

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50336]
Direct customer ask copying here: 

> Parameter info disappears when I press down or up in multi-line method invocation and hides the actual values of parameters.

> Actual values hidden, can't read what errorText is now: 
![image](https://user-images.githubusercontent.com/46729679/104047452-84ce7800-5196-11eb-8312-43cbb14d0207.png)

> After I press "down" the window disappears: 
![image](https://user-images.githubusercontent.com/46729679/104047509-9748b180-5196-11eb-9dab-8fa8c3b1e311.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback.
