### ISSUE TITLE
IntelliSense for LINQ function to suggest predicates

### ISSUE THREAD

**Issue by mika1490** [dotnet/roslyn#50333]
Direct customer ask copying here: 

> Intellisense for a Linq function is counter-productive. There are no suggestions for predicates. Typing something like “r =>” yields “ref =>”.

> Resharper example:
![image](https://user-images.githubusercontent.com/19830282/104042329-37024180-518f-11eb-8b25-a18aec1b3744.png)

> VS Example: 
![image](https://user-images.githubusercontent.com/19830282/104042350-3ec1e600-518f-11eb-856d-8fba6f46f2bb.png)

**Comment by CyrusNajmabadi** [comment]
> Intellisense for a Linq function is counter-productive. There are no suggestions for predicates. Typing something like “r =>” yields “ref =>”.

I don't repro this:

![image](https://user-images.githubusercontent.com/4564579/153516071-d7e9c5e9-82ff-4230-a78e-f1aff2d81988.png)

Furthermore, we do give help on the predicate like so:

![image](https://user-images.githubusercontent.com/4564579/153516113-cb5d3848-46b3-4f53-ad74-adb405baf328.png)

It's just that we do this through sighelp and not completion (which is sensible to me IMO).
