### ISSUE TITLE
Add namespace information when hovering over extension method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50340]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-namespace-information-when-hovering-/1302868)._

---
When I hover my mouse over an extension method, popup with method summary and signature is displayed (see image). It would be even more useful to also see the extension class name (not only the class that method is extending) and its namespace.

---
#### Feedback Bot on 1/6/2021, 09:45 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
In design review to decide how the namespace should appear in the popup

**Comment by ryzngard** [comment]
Design: We don't want to make this change without clear understanding of compelling cases. As it stands, we believe the design benefits most cases. We are interested in hearing more cases where this would be useful and will reconsider if new information arises.
