### ISSUE TITLE
Merge "Edit and Continue Debugging" into one "Update Code"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50342]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Merge-Edit-and-Continue-Debugging-into/1271465)._

---
<p>Repetitively pausing the debugging process before editing the code then continuing afterwards can personally decrease productivity especially for frequent small changes. The &quot;Edit and Continue Debugging&quot; feature would hopefully be more useful when merged into a single-click &quot;Update Code&quot; button. For example, the process will be paused at the end of the current code block (at the &quot;}&quot;, to avoid accidentally editing active statements) then the code will be updated followed by the continuation of the process.</p>

---
#### Feedback Bot on 11/29/2020, 11:24 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Dmitry Lyalin [MSFT] on 12/11/2020, 01:47 PM: 

<p>Thank you for your suggestion. This is timely as we are actively investigating improvements to the user experience in this area and hope to have more to say sometime early next year.</p>

**Comment by jinujoseph** [comment]
cc @tmat

**Comment by tmat** [comment]
I should be be achieved via https://github.com/dotnet/roslyn/issues/49004.
