### ISSUE TITLE
Support syntax highlighting, IntelliSense, and compile errors in code that is commented out using #if

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50341]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Support-syntax-highlighting-IntelliSens/1292209)._

---
C# and VB.NET have an `#if` directive which causes code to be conditionally compiled depending on flags set on the compiler, such as `DEBUG`. My problem is that code in these blocks does not have syntax highlighting or IntelliSense unless the condition being tested is true, and even compile errors in these blocks are ignored. This can lead to problems down the road when it comes to deploy the code - for instance, if you're coding in debug mode, you'll have to switch to release mode to see the other code paths. Therefore I think these features (syntax highlighting, IntelliSense, and compile errors) should be enabled for code in these blocks at all times. I know it's grayed out to indicate that it won't run in the current configuration, but maybe it could be marked in some other way, for instance with a gray background?

---
#### Feedback Bot on 12/20/2020, 10:06 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is intentionally out of scope. It's been considered but the costs far outweigh the benefits.
