### ISSUE TITLE
No live analysis/intellisense diagnostics for source-generator outputs

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#50357]
Repro:
1. in `Compilers.sln`, open `Syntax.xml` for C# and add a new syntax node (duplicate an existing one and change its name)
2. in the Error List, there should be diagnostics because the added public APIs for the new syntax node have not been recorded, but there are not.
3. from the command-line, invoke `build.cmd -runAnalyzers` and the public API diagnostics are correctly produced

Similarly, if you enable nullability tracking (add `#nullable enable` at the top of the shipped public API file), the diagnostics to record the annotation are produced from the command-line, but not in the IDE (see PR https://github.com/dotnet/roslyn/pull/41000).

FYI @jasonmalinowski

**Comment by Youssef1313** [comment]
Isn't this related to roslyn-analyzers repo where the PublicApiAnalyzers are implemented? or the PublicApiAnalyzers needs some APIs from the compiler first?

**Comment by jcouv** [comment]
It is possible that the issue is with the analyzer, I'm not sure. But I suspect the issue is with the IDE because the analyzer does produce the diagnostics correctly when it is run from the command-line.

**Comment by jcouv** [comment]
@jinujoseph @mavasani Would it be possible to schedule this in a release?
This will affect the workflow of the compiler team (ie. hard to work with syntax.xml changes) and is blocking a PR to start tracking nullabilities in public APIs.
Thanks

**Comment by mavasani** [comment]
@jcouv @jasonmalinowski This does not seem specific to analyzers. For example, if in the step 1 in the repro you use an invalid identifier, say with whitespaces, and open the source generated file in the editor, you see no compiler errors in IDE, but you see them on build. Seems like live diagnostics and background analysis are not hooked up for source generated documents.

**Comment by jasonmalinowski** [comment]
Ah, right, we haven't wired that up yet. I was having trouble deciphering the repro steps to figure out what was going on by the description alone. @mavasani that sounds correct.

**Comment by alrz** [comment]
What's thr workaround for this? Typing?

**Comment by jcouv** [comment]
@alrz For a feature branch, I would recommend suppressing the publicAPI warnings via editorconfig. Make sure to PROTOTYPE that as a reminder to undo it when possible.
That said, for the record structs PR, I did make publicAPI changes by hand for syntax. I wouldn't recommend it...

**Comment by alrz** [comment]
>I did make publicAPI changes by hand for syntax. I wouldn't recommend it...

oh no 🙂

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski can you clarify what the status is of this?

**Comment by jcouv** [comment]
We now have a workaround allowing to run the publicAPI fixer effectively (thanks to those who made it work). Documented the steps in the ["contributing" document](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md#running-the-publicapi-fixer).
