### ISSUE TITLE
GoTo doesn't list source-generated symbols

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#50352]
Repro: From `Compilers.sln` hit `CTRL+.` to invoke `GoTo` and type the name of a syntax node that is exclusively declared in source-generated source (for example, `NullableDirectiveTriviaSyntax`).

The type isn't found (but should).

This should also work when adding new types via `syntax.xml`.

FYI @jasonmalinowski @chsienki

**Comment by jasonmalinowski** [comment]
Duplicate of #49581.
