### ISSUE TITLE
CS0121

### ISSUE THREAD

**Issue by sungam3r** [dotnet/roslyn#50360]
`Error	CS0121	The call is ambiguous between the following methods or properties: 'Lexer.Lex(string, int)' and 'Lexer.Lex(ReadOnlyMemory<char>, int)'`

on line 
```c#
 var token = new Lexer().Lex(null);
```

`Lexer` struct:

```c#
 public struct Lexer
    {
        internal Token Lex(string source, int start = 0) => ...

        public Token Lex(ReadOnlyMemory<char> source, int start = 0)
        {
           ...
        }
    }
```

I don't understand this error as `ReadOnlyMemory<T>` is `struct`.

roslyn version
3.8.0-5.20604.10 (9ed4b774)

**Comment by CyrusNajmabadi** [comment]
`ReadOnlyMemory` has this implicit operator:

`public static implicit operator ReadOnlyMemory<T>(T[] array)`

This is probably what is causing the ambiguity.  Checking with @jaredpar though as it seems unfortunate for this not to work.  My gut wants the implicit-reference conversion to be better than the implicit-user-defined conversion.  But my guess is there's nothing to make that happen.

**Comment by sungam3r** [comment]
Yeah, already found implicit operator myself.

**Comment by jaredpar** [comment]
As @CyrusNajmabadi noted this behavior is "By Design". The `null` value converts equally well to `string` and `ReadOnlyMemory<char>` due to it's implicit operator from `T[]` hence the call is ambiguous.
