### ISSUE TITLE
Set-up AbstractCSharpCompletionProviderTests to be able to use ReferenceAssemblies

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50368]
`ReferenceAssemblies.Net.Net50` should already be available to tests, but I'm not sure `AbstractCSharpCompletionProviderTests` is set up to use it. Such a change should probably be a separate pull request.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/50212#discussion_r554626605_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
