### ISSUE TITLE
AbstractCodeModelService.Rename can result in deadlock when renaming a file from Solution Explorer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#50379]
The following code blocks the UI thread without following the required JTF patterns for Visual Studio:

https://github.com/dotnet/roslyn/blob/97663e71724a900575258de6f4ee2f940742afb0/src/VisualStudio/Core/Impl/CodeModel/AbstractCodeModelService.cs#L492

This results in a deadlock because RenameSymbolAsync runs code out-of-process:

https://github.com/dotnet/roslyn/blob/97663e71724a900575258de6f4ee2f940742afb0/src/Workspaces/Core/Portable/Rename/Renamer.cs#L132

And running code out-of-process has an unknown UI thread dependency (possibly related to package loads and/or `GetServiceAsync`).

**Comment by CyrusNajmabadi** [comment]
Would be thrilled to just Remove support for this :)

**Comment by sharwell** [comment]
This is actively blocking Apex test scenarios, so it's a priority fix for 16.9 or 16.10.

**Comment by sharwell** [comment]
🔗 AB#1220281
