### ISSUE TITLE
Packages on myget are not available

### ISSUE THREAD

**Issue by afilatov-st** [dotnet/roslyn#50383]
**Version Used**: 

3.6.0.x

**Steps to Reproduce**:

1. Add "https://dotnet.myget.org/F/roslyn/api/v3/index.json" as a feed to Nuget config

**Expected Behavior**:

Feed was accessible prior to 1/11/2021

**Actual Behavior**:

Feed became inaccessible without any notices

**Comment by JoeRobich** [comment]
@afilatov-st Sorry for the change. Builds that were once available on myget are not available from the "myget-legacy" Azure Artifact feed. See https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=myget-legacy&package=Microsoft.CodeAnalysis&protocolType=NuGet&version=3.6.0-beta1-20105-01&view=versions

You can add this feed to your NuGet.config - "https://pkgs.dev.azure.com/dnceng/public/_packaging/myget-legacy/nuget/v3/index.json"
