### ISSUE TITLE
Local methods should support Xml comments

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#50399]
**Version Used**: 
VS 2019 Version 16.9.0 Preview 2.0

**Steps to Reproduce**:

1. write a method with a local method
2. write /// above the local method
3. nothing happens, and if you write ///<summary>something</summary>, that isn't provided in the mouseover of the local method

**Expected Behavior**:
Xml comments work for local methods and regular methods

**Actual Behavior**:
xml comments only work for regular methods.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Compilers/CSharp/Portable/Compiler/UnprocessedDocumentationCommentFinder.cs#L63-L73

In the above code, there is no check for `LocalFunctionStatementSyntax` (it doesn't inherit from `BaseMethodDeclarationSyntax`)

**Comment by jaredpar** [comment]
This behavior is "By Design. Local functions do not support XML comments at this time. There was discussion about adding this support but ultimately we decided not to. These aren't externally accessible hence adding doc comments for them is of limited value.
