### ISSUE TITLE
Analyzers run on inappropriate project

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#5039]
From the build output below, we see StyleCop.Analyzer warnings produced for this project, but this project does not reference StyleCop.Analyzers and thus shouldn't get any of its warnings.

7>------ Build started: Project: Microsoft.VisualStudio.SLNX, Configuration: Debug Any CPU ------
7>C:\Users\andarno\git\SLNX\src\Microsoft.VisualStudio.SLNX\Properties\AssemblyInfo.cs(1,1,1,1): warning SA1652: Enable XML documentation output
7>C:\Users\andarno.nuget\packages\MicroBuild\1.0.61-rc-g96d483ea96\build\AssemblyInfoCopyright.Desktop.cs(1,1,1,1): warning SA1652: Enable XML documentation output
7>  Microsoft.VisualStudio.SLNX -> 
7>  Microsoft.VisualStudio.SLNX -> 
7>  Creating VSIX Container...
7>  Microsoft.VisualStudio.SLNX -> C:\Users\andarno\git\SLNX\bin\Debug\Microsoft.VisualStudio.SLNX.vsix

Other projects in the solution (that are referenced by this project) _do_ reference StyleCop.Analyzers.

Repro:

git clone https://mseng.visualstudio.com/DefaultCollection/VSIDEProj/_git/VSIDEProj.SLNX slnx
cd slnx
git checkout 9b737de59e
cd src
nuget restore  (nuget v3 required)
cd Microsoft.VisualStudio.SLNX
MSBuild

This repros at the command line and in the IDE.

**Comment by heejaechang** [comment]
give the bug to IDE team. it looks like it is a bug in project system (msbuild) where it resolves @(Analyzer) variable in the target file to some set of analyzers when project.json doesn't actually have those information for the project.

**Comment by Pilchie** [comment]
In project.json, references are applied transitively through P2P references.  Analyzers follow the same pattern, since we expect a lot of analyzers to apply to the uses of the libraries that are in the same package, so this is actually our design right now.

**Comment by Pilchie** [comment]
Tagging @jmarolf too.

**Comment by AArnott** [comment]
@Pilchie Is this only transitive across *P2P* refs, or does it also apply across nuget package references? I certainly should be able to use StyleCop.Analyzers on one project without forcing all my consumers to also use it.

**Comment by Pilchie** [comment]
Interesting.  Yes, it's currently across nuget package references too.  @yishaigalatzer @davidfowl This looks like a case where we need dev dependencies in project.json :-/

**Comment by sharwell** [comment]
Yikes.

**Comment by yishaigalatzer** [comment]
@Pilchie this is your call here, analyzers are a top level concern rather than a reference, and you can choose which ones you want to propagate

**Comment by jmarolf** [comment]
I think we can all agree that we don't *want* analyzers to propagate outside the project they are referenced.  Ideally we want this to work like it does in the non project.json scenarios.

**Comment by Pilchie** [comment]
That's not entirely true actually.  I talked in person @yishaigalatzer and @davidfowl about this on Friday afternoon.  We really want to be able to annotate dependency types in project.json: "build-only" (doesn't flow, uses compiler runtime for TFM), "desgin-time" (flows and uses compiler runtime for TFM), etc.

One thing we didn't talk about was timeline though...

**Comment by AArnott** [comment]
I agree some dependencies should propagate and others shouldn't. In packages.config, they never propagate across P2P references though, so it is a surprise that it does for project.json, but in the interest of the Project K world where NuGet package dependencies are swappable for source code dependencies I guess that makes some amount of sense.
So ya, I support a project.json design that would allow developmentOnly dependencies to be identified. But don't we already have this? Consider: the .nuspec file already has a developmentDependency tag in it, and for StyleCop.Analyzers this is set to true. But the MSBuild task that resolves NuGet dependencies and allows them to propagate across P2P references is not respecting it. 
So if you want NuGet dependencies to propagate by default, that's fine. That's roughly what the old packages.config behavior was (if you squint a little). So perhaps the fix for this is to simply fix the MSBuild task (that I believe the ML team owns) to respect the existing attribute in the expanded package's .nuspec file.

**Comment by Pilchie** [comment]
That may be a short term fix. Longer term @davidfowl suggests that it isn't nodes in the package graph that you want annotated, but rather edges. That means it would end up being something the *consumer* of the package controls, not the producer.

Regardless, clearly this issue should be re-opened

**Comment by AArnott** [comment]
I think edges and nodes are both useful to be able to annotate. 

**The case for nodes identifying themselves as developmentDependencies**

1. StyleCop.Analyzers, for example, can make a clear case that it should never propagate. It's clearly a decision of the author of that particular project for code cleanliness.
2. Code generation packages (for example, that add support to convert .resx to embeddable resources and generate .cs files for easy access from that project). These too, have no business ever propagating.

** The case for edges identifying as developmentOnly dependency **

1. Roslyn's own analyzers may want to propagate by default, so that if I write a library that wraps the Microsoft.CodeAnalysis packages and someone consumes mine, it not only brings down Roslyn packages but their analyzers too. But if my package's consumption of Roslyn is merely a hidden implementation detail, then there is no reason to add Roslyn's analyzers to consumers of *my* package. 
2. In the packages.config world, I sometimes list packages that I don't directly consume in my own nupkg's lib folder, but rather its *tools* folder. For example, if I were writing a code generation package that uses Roslyn, the dependency on Roslyn would be from my package's tools folder. My package *may* not even have a lib folder. In this case, I need Roslyn DLLs to ship in my package's tool folder but I don't want every one of my package's consumers to add references to Roslyn DLLs themselves.

Every one of these cases are real, in particular for my own projects.

**Comment by Pilchie** [comment]
Moving to 1.2, as I don't think this can be fixed by roslyn without additional information in the project.lock.json file.

**Comment by jasonmalinowski** [comment]
@yishaigalatzer, @emgarten, I know some stuff snuck in with NuGet 3.3 to help some scenarios around things flowing or not flowing. Do they help this scenario?

**Comment by emgarten** [comment]
Referencing the dependency package with ``"suppressParent": "all"`` in your project.json file will stop it from flowing to parent projects.

Include/exclude has a flag for analyzers and by default it is set to not allow it to flow to parent projects, however NuGet isn't aware of analyzers in packages yet and doesn't write them to the lock file. They are read directly from the package without NuGet's help, so it can't fully control them *yet*.

https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

**Comment by jasonmalinowski** [comment]
So do I need to update the build task then? How should that work?

**Comment by davidfowl** [comment]
The lock file will be updated with the relevant information on restore so the build task shouldn't require changes (AFAIK)

**Comment by jasonmalinowski** [comment]
@Emgarten, @davidfowl: so I have nothing further to do here?

**Comment by DustinCampbell** [comment]
@jasonmalinowski, any update? Have we verified the NuGet work?

**Comment by jasonmalinowski** [comment]
Closing since this dates back to project.json days.

**Comment by davidfowl** [comment]
😬
