### ISSUE TITLE
Transition F# and TS to IFindDefinitionService

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50391]
https://github.com/dotnet/roslyn/pull/50132 is the first part of removing the LSP's implementation of find definition's dependency on EditorFeatures. It introduces a new interface at the Features layer, IFindDefinitionService, that LSP will prefer over IGoToDefinitionService when available. However, both F# and TS will need to consume this new interface before we can fully break the dependency. This tracks that removal.

**Comment by windowslering** [comment]
@333fred hi fred. for visual basic 2008. little consultation

**Comment by CyrusNajmabadi** [comment]
tagging @cartermp  and @DanielRosenwasser @mikadumont .  See https://github.com/dotnet/roslyn/pull/50132 as well.

**Comment by davidwengier** [comment]
VS for Mac uses IGoToDefinitionSymbolService too, for F#: https://github.com/xamarin/vsmac/blob/main/main/external/fsharpbinding/FSharp/Internal/Editor/FSharpGoToDefinitionService.cs

/cc @KirillOsenkov

**Comment by cartermp** [comment]
The VSMac implementation should be identical to what we do in VS.

For F#, we implement both members in the `IFSharpGoToDefinitionService`

* `FindDefinitionsAsync` - for Peek Definition
* `TryGoToDefinition` - for Go to Definition

Am I right in expecting that we'll need to now implement two interfaces, and the new one will have `FindDefinitionsAsync` to support Peek Definition?

**Comment by DanielRosenwasser** [comment]
@uniqueiniquity not sure if this is related to the last issue

**Comment by 333fred** [comment]
> Am I right in expecting that we'll need to now implement two interfaces, and the new one will have FindDefinitionsAsync to support Peek Definition?

Correct. The new method is nearly identical to the previous one, except that we're taking the opportunity to return `ImmutableArray<INavigationItem>` instead of `IEnumerable<INavigationItem>`, as we would want to do if we eventually make this public. My PR already adds the FSharp external access version for you to implement.

**Comment by uniqueiniquity** [comment]
We're tracking this on our end as part of VS Sprint 183.

**Comment by 333fred** [comment]
The non-breaking change has been merged in.

**Comment by uniqueiniquity** [comment]
@333fred Finally getting around to this. Do we need to export an implementation of the new interface if our implementation of `FindDefinitionsAsync` was already no-op-ing?

**Comment by CyrusNajmabadi** [comment]
Yes please.  It will allow us to remove the old interface method entirely once you're off of it.

**Comment by CyrusNajmabadi** [comment]
@uniqueiniquity you don't need to do anything here.  As long as:

1. you are not *explicitly* implementing the old IGoToDefinitionService.FindDefinitionsAsync API.
2. you promise not to implement hte old IGoToDefinitionService.FindDefinitionsAsync API in any fashion at this point.  If you want to implement this, you'll use the new IFindDefinitionService.FindDefinitionsAsync instead.

That will allow us to safely remove the method without any binary conflicts with you.

**Comment by uniqueiniquity** [comment]
I'll go ahead and remove our explicit interface implementation now.
I'm not worried about implementing it in the future - we have our own `IPeekableItemSourceProvider` implementation, and I can't imagine any reason we'd actively drop that in favor of a Roslyn implementation.

**Comment by uniqueiniquity** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/303994

**Comment by uniqueiniquity** [comment]
The TS change is in, we usually insert on Tuesdays.

**Comment by CyrusNajmabadi** [comment]
thanks!  @cartermp no rush, but if someone can squeeze in the work on this, that would be nice.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi @davidwengier Any idea how much progress we've made on this? I see the TypeScript side was merged but unsure about the F# side?

**Comment by davidwengier** [comment]
I haven't done anything to VS Mac, I usually just wait for things to break then fix them :)

**Comment by jasonmalinowski** [comment]
Actually if I understand the code, I think you wouldn't get broken -- IGoToDefinitionService would still stay around for a bit, or at least there's a very big unrelated amount of work to clean that up.
