### ISSUE TITLE
Multiple enumerations of IEnumerable Warning

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50408]
Analyzer warning for multiple enumerations of an IEnumerable<T>.

![image](https://user-images.githubusercontent.com/46729679/104379285-1fec8800-54de-11eb-80c4-2820e58f2c96.png)

Other example: 

``` 
IEnumerable<string> cards = GetCards();
foreach (var card in cards)
    Console.WriteLine("Added " + card);
var allCards= new StringBuilder();
foreach (var card in cards)
    allCards.Append(card + " ");
``` 
Assuming that GetCards() returns an IEnumerable<string>, this is enumerating the collection twice in the two foreach statements. 

The code fix can convert the sequence to an array or a list at variable initialization:

```
List<string> cards = GetCards().ToList();
```

**Comment by Youssef1313** [comment]
This may fit more in roslyn-analyzers for performance analyzers.

**Comment by mikadumont** [comment]
> This may fit more in roslyn-analyzers for performance analyzers.

Yes, placing it here initially so we can go over it in our design meeting.

**Comment by sharwell** [comment]
@mavasani should we move this to roslyn-analyzers for triage there?

**Comment by mavasani** [comment]
@sharwell We already have https://github.com/dotnet/roslyn-analyzers/issues/3133, so seems this can be closed as a duplicate.

**Comment by sharwell** [comment]
Duplicate of dotnet/roslyn-analyzers#3133
