### ISSUE TITLE
Convert to Interpolated string should consider the context

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#50400]
**Version Used**: 
VS 2019, Version 16.9.0 Preview 2.0

**Steps to Reproduce**:

1. in the code `var someString = String.Format("something {0}", "else");`
2. put the caret into `"something"`, hit `ctrl-.`
3. observer, that only the conversion to `String.Format($"something {"else"}");` is offered, rather than offering to remove the `String.Format` as well

**Expected Behavior**:
@sharwell wrote this on discord:
> There are two conceptually different refactorings. 
> (1) One of them converts a string literal to an identical string literal with a different syntax, 
> (2) while the other converts a string.Format invocation to an interpolated string. You're seeing the first here. 
> I would **also expect to see the second**, but perhaps it's only triggered from a different location.

**Actual Behavior**:
only the inner refactoring is offered.

**Comment by CyrusNajmabadi** [comment]
I get the expected result:

![image](https://user-images.githubusercontent.com/4564579/199613869-79872cb7-9175-4871-b1ce-e2d5403807ab.png)
