### ISSUE TITLE
Is error BC30512 expected or is this a bug, recommend fix yields wrong result

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5040]
I get error BC30512  Option Strict On disallows implicit conversions from 'UnitTest19.ENdataType?' to 'UnitTest19.ENdataType'

If expected how do I declare 'ENdataType?", the recommend CType fix produces the wrong value.
```
<TestClass()> Public Class UnitTest19
    Public Enum ENdataType
        dtIDTYPE = 0
        dtGUIDTYPE = 1
        dtDATETIMETYPE = 5
    End Enum
    Private Class Test
        Public Property Endata As ENdataType
        Public Function returnEnData() As ENdataType
            Return returnEnData
        End Function
    End Class
    <TestMethod()> Public Sub T19_TestContracts()
        Dim x As New Test
        Dim y As ENdataType = ENdataType.dtDATETIMETYPE
        ' y = 5
        y = x?.Endata ' Error BC30512
        y = CType((x?.Endata), ENdataType) ' Recommended Fix
        ' y = 0 expected 5
        y = ENdataType.dtDATETIMETYPE
        y = CType((x?.returnEnData), ENdataType)
        ' y = 0 expected 5
    End Sub
End Class```

**Comment by gafter** [comment]
Marking milestone 1.1 to answer the first question and/or redispatch the issue for the second question.

**Comment by paul1956** [comment]
@gafter from your answer the warning is wrong and it will be fixed in 1.1 or am I misunderstanding.

If I want the Ctype issue addressed I need to open another issue, correct?

**Comment by gafter** [comment]
What I mean is that we should answer whether the warning is wrong or not in the 1.1 timeframe. Essentially I am scheduling the question to be answered. Once we know the answer to that we can decide what needs to be done next.

**Comment by paul1956** [comment]
Thanks completely misunderstood. I assume you are tracking the BC30512 elsewhere so I will close this issue. If I need to open a separate issue on CType let me know.

**Comment by gafter** [comment]
No, we are not tracking the question/issue about the diagnostic elsewhere.

**Comment by AlekseyTs** [comment]
When I compile the code above with ```Option Strict On```, I get the following error:
```
error BC30512: Option Strict On disallows implicit conversions from 'UnitTest19.ENdataType?' to 'UnitTest19.ENdataType'.

        y = x?.Endata ' Error BC30512
            ~~~~~~~~~
```
The error is correct, result type of ```x?.Endata``` is ```ENdataType?```, which cannot be implicitly converted to ```ENdataType``` when ```Option Strict On```. 

Behavior of CType is correct as well because ```x.Endata``` is never assigned an explicit value, so it stays equal to 0.

I am not sure there is a value in using conditional access followed by CType in this scenario. Consider making ```y``` nullable, or stop using conditional access.
