### ISSUE TITLE
[LSP] Make cache handlers synchronous

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#50418]
As Taylor pointed out in a [comment](https://github.com/dotnet/aspnetcore-tooling/pull/2926#discussion_r556120678), our caching handlers (semantic tokens, completion, FAR) are asynchronous when they don't need to be. To simplify the code, it might be good to switch to computing everything synchronously.

**Comment by allisonchou** [comment]
After conversation in https://github.com/dotnet/roslyn/pull/50423, it seems like there isn't a clear consensus on whether this would be useful. I will close out the issue for now, and re-open it if it's determined we want to take the linked PR.

**Comment by NTaylorMullen** [comment]
Reopening because it's needed for completion resolve cache lookups.

**Comment by allisonchou** [comment]
Closing as this is resolved in @NTaylorMullen's PR https://github.com/dotnet/roslyn/pull/52123.

**Comment by NTaylorMullen** [comment]
> Closing as this is resolved in @NTaylorMullen's PR #52123.

Let the record state I was a thief and stole @allisonchou's changes!
