### ISSUE TITLE
Issue with HTML links in interpolated Strings

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5041]
![image](https://cloud.githubusercontent.com/assets/12789369/9702386/43ab3cee-540f-11e5-9206-6b4dee5fe471.png)

Two issues
1) the editor offers to take you to the link "https://code-cracker.github.io/diagnostics/{diagnosticId.ToDiagnosticId().Replace(" without understanding the "{" and what is inside it.
2) The IDE thinks the " inside the {} is the end of the HTML string for colorization
```
        Dim x as string = $"http://yyy.com/diagnostics/{diagnosticId.ToDiagnosticId().Replace("VB", "BV")}.html"
```
The following is correctly colorized
```
        Dim y As String = $"{diagnosticId.ToDiagnosticId().Replace("VB", "BV")}.html"
```

**Comment by Pilchie** [comment]
Tagging @markw-t, @olegtk

The HTML link classifier is just a plain text extension that uses a regex to match.  It doesn't know that it's actually an interpolated string.

**Comment by olegtk** [comment]
Yeah, @Pilchie is correct. We have an internal bug tracking this, but so far we haven't committed into fixing this due to low user demand. Please file a bug via "send a frown" if you care about it.
