### ISSUE TITLE
[Discuss] break inside of a match expression

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#5042]
`break` inside of a `switch` block exits that block.
Since the predominant style is lambda-style expressions, and `break` doesn't quite make sense.

What should `break` do inside of a `match`?
 1. exit the match.   (just like  `switch`)
 2. exit the enclosing block (not the `match` )
 3. Add `exit ...` & `continue ..` syntax of VB?
eg
```c#
select case ( ... )
{
  case ... : 
    while ( ... )
    {
      foo = match ( ... )
            {
              |: ... => exit while; // Executes code from point after the enclosing while block.
              |: ... => exit select; // Executes code from point after the enclosing select block.
              |: ... => continue while; // Execution continues at the enclosing while.
              |: ... => continue select; // Execution continues at the enclosing select.
              |: => null;
            }
    }
}
```

**Comment by gafter** [comment]
I cannot tell which match-expression proposal this is a question about.

**Comment by AdamSpeight2008** [comment]
@gafter Does it matter, which proposal? It's not a specify `match expression` proposal but a discussion of the meaning of `break` with them.
* Yours proposes it maintaining `switch` semantics. 
* Mine and @HaloFour it `break`'s surrounding scope and not `match`'s scope
* I suggest introducing `exit ...` and `continue ...` into c#
* Use lambda expression's meaning
```c#
( ... ) => break;
```

**Comment by gafter** [comment]
@AdamSpeight2008 If this doesn't relate to this project, or any proposed part of it, there is not much point having the discussion here. If this relates to a specific proposal, please have the discussion on that proposal's issue.
