### ISSUE TITLE
Visual Basic compiler should compile a class that implements IEnumerable(Of T) successfully.

### ISSUE THREAD

**Issue by lpperras** [dotnet/roslyn#50422]
When trying to compile a class that implements IEnumerable(Of T), the roslyn compiler returns three errors, where there should be none. The exact same code compiles fine when calling vbc.exe or when using Visual Studio.

I am getting the issues running this simple C# programs that tries to compile a VB.NET assembly:
```
	var compilerOptions = new VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, optimizationLevel: OptimizationLevel.Release);
	var syntaxTree = VisualBasicSyntaxTree.ParseText(@"Imports System
Imports System.Collections.Generic

Public Class Test(Of T)
    Implements IEnumerable(Of T)

    Public Function GetEnumerator() As IEnumerator(Of T) Implements IEnumerable(Of T).GetEnumerator
        Throw New NotImplementedException()
    End Function

    Private Function IEnumerable_GetEnumerator() As IEnumerator Implements IEnumerable.GetEnumerator
        Throw New NotImplementedException()
    End Function
End Class");
	var compiler =
		VisualBasicCompilation.Create("VB", options: compilerOptions)
			.AddSyntaxTrees(syntaxTree)
			.AddReferences(MetadataReference.CreateFromFile(typeof(string).Assembly.Location), MetadataReference.CreateFromFile(Assembly.ReflectionOnlyLoad("System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089").Location));

	using (var outputStream = new MemoryStream())
	{
		var result = compiler.Emit(outputStream);
		Console.WriteLine(result.Success);
	}
```

I expect the result to be a success and not contains errors. The three errors are the following:

- error BC32042: Too few type arguments to 'IEnumerator(Of Out T)'.
- error BC32042: Too few type arguments to 'IEnumerable(Of Out T)'.
- error BC30149: Class 'Test' must implement 'Function GetEnumerator() As IEnumerator' for interface 'IEnumerable'.

I might be missing something obvious since I am not used to VB.NET but can't explain why the same code compiles fine in VS but not using Roslyn.

**Comment by svick** [comment]
You're missing `Imports System.Collections`. Maybe vbc and VS add that automatically?

**Comment by lpperras** [comment]
Wow thank you, I feel bad now. It looks like it is importing it by default, so that's why it was behaving differently. Thanks for pointing this out, I appreciate.
