### ISSUE TITLE
CodeFix for CA1801 / in the future for IDE0060 doesn't respect formatting

### ISSUE THREAD

**Issue by petrroll** [dotnet/roslyn#50429]
**Notes:**
Filed here instead of Analysers repo due to it being sunseted in NetAnalysers and discussion at #49868

**Version Used**: 

Microsoft.CodeAnalysis.FxCopAnalyzers :: 3.3.2

**Steps to Reproduce**:

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        object a = new();
        object b = new();

        MethodWithUnused(
            a, b
            );
    }

    private static void MethodWithUnused(object a, object b) => Console.WriteLine($"{b}");
}
```

**Expected Behavior**:
CodeFix on parameter `object a` results in callsite:
```
        MethodWithUnused(
            b
            );
```

**Actual Behavior**:
CodeFix on parameter `object a` results in callsite:
```
        MethodWithUnused(
b
            );
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we have not heard broader feedback on this.
