### ISSUE TITLE
Ctrl+Q search results are duplicated

### ISSUE THREAD

**Issue by uniqueiniquity** [dotnet/roslyn#50437]
**Version Used**: 
3.9.0-4.21061.8
**Steps to Reproduce**:

1. Create a new .NET 5 Console App on host instance
2. Start live share session and connect from guest instance
3. On the guest instance, type Main in the Ctrl+Q search

**Expected Behavior**:
One entry for the `Main` method appears
**Actual Behavior**:
Sometimes, two such entries appear, then one disappears after ~2 seconds

This may be fairly low pri because the results do eventually dedupe, but I think it's worth filing because I'd like to understand _why_ it's deduping and it might cause flaky integration tests for y'all.

**Comment by uniqueiniquity** [comment]
cc: @dibarbet

**Comment by uniqueiniquity** [comment]
Also, cc: @gundermanc, who might have insight into why the `ILanguageClient` with `DisableUserExperience` _sometimes_ gets invoked.

**Comment by gundermanc** [comment]
I don't have much context here, Miguel from LSP might know more.

**Comment by CyrusNajmabadi** [comment]
This would be part of aiosp.  @veler
