### ISSUE TITLE
With Source Generator, exception when building in Dockerfile

### ISSUE THREAD

**Issue by drano** [dotnet/roslyn#50445]
My project is building correctly with Visual Studio 2019, but when I compile in docker using image "mcr.microsoft.com/dotnet/sdk:5.0-alpine", then I have some errors:

`CSC : warning CS8785: Generator 'XXXGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NotSupportedException' with message 'Specified method is not supported.' `

**Comment by jaredpar** [comment]
@drano 

In order to make progress here we'll need to figure out which source generator is involved here. Do you happen to know what the XXXGenerator is? If not can you provide a binary log of the build that we can look into to see where that is coming from?

**Comment by drano** [comment]
XXXGenerator is a custom generator using Microsoft.CodeAnalysis.CSharp 3.8.0
Can I get binary log ?

**Comment by jaredpar** [comment]
@drano 

> XXXGenerator is a custom generator using Microsoft.CodeAnalysis.CSharp 3.8.0

Is this a generator you own? Based on the error the error is almost certainly in this generator. It's throwing an exception and that is what the compiler is reporting here. 

> How I get binary log ?

Use the `/bl` switch in your build command. For example `dotnet build /bl`. That will produce a file called msbuild.binlog that we can look at to hopefully see a bit more detail on the exception here.

**Comment by drano** [comment]
msbuild.binlog attached

[msbuild.zip](https://github.com/dotnet/roslyn/files/5821144/msbuild.zip)

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/48008

**Comment by jaredpar** [comment]
Letting #48008 drive
