### ISSUE TITLE
 Severity changes made from Solution Explorer go into invalid section in global analyzerconfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50444]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Severity-changes-made-from-Solution-Expl/1306771)._

---
[severity:Other]
Our repro steps:
1. Create a NuGet package with dependencies on code analysis packages, e.g. from a csproj with this:
```
<ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="3.8.0-1.20330.5" />
        <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" />
</ItemGroup>
```
In our case the package includes a stylecop.json file.
2. Create a project within a standalone solution.
3. Add a .globalconfig (a global analyzer config file) and a root .editorconfig in the solution folder.
4. Add a dependency on the NuGet package created above.
5. In the Solution Window, open the Analyzers section and change the severity for any rules covered by one of the included analyzers.

Expected: An entry is created in either the root .editorconfig file or in a newly created .editorconfig file in the project folder
Actual: An entry is created in the .globalconfig file, under a section. This is an invalid entry because sections aren't valid in .globalconfig files.
Workaround: If an .editorconfig file is placed in the project folder the rule will be added to it.

---
#### Feedback Bot on 1/12/2021, 00:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/13/2021, 01:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
[ConfigurationUpdater](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs) needs to be updated to handle global configs property - currently it assumes all AnalyzerConfigDocuments for a project are regular editorconfigs, which is no longer true with global configs in picture.
