### ISSUE TITLE
"Convert to for" code fix produces invalid cast using "var"

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#50469]
```csharp
var items = new[] { new { x = 1 } };

foreach (var item in items)
{
}
```

Attempting to apply the "Convert to for" code fix results in:

```csharp
var items = new[] { new { x = 1 } };

for (int i = 0; i < items.Length; i++)
{
    var item = (var)items[i];
}
```

where the `(var)` cast is invalid.

**Comment by DoctorKrolic** [comment]
This is not currently reproducible (checked on https://github.com/dotnet/roslyn/commit/4472b0e711536b04e3de7d2fc851553142def580):
![devenv_O0r9AQF86B](https://user-images.githubusercontent.com/70431552/157238586-6e2809ec-f53f-447c-93b1-681322b0c44c.gif)
_Verified, that results are the same for top level statements_

So the issue should be closed and moved to "Completed" section
