### ISSUE TITLE
MS.CA.Scripting.CSharp MyGet package does not depend on MS.CA.CSharp

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#5046]
I installed the Microsoft.CodeAnalysis.Scripting.CSharp package (version 1.1.0-beta1-20150905-01) from [the Roslyn Nightly MyGet](https://www.myget.org/gallery/roslyn-nightly) but got an error about Microsoft.CodeAnalysis.CSharp assembly missing.

It looks like the MS.CA.Scripting.CSharp package does not depend on the MS.CA.CSharp package, even though it is necessary for it to work correctly.

**Comment by ManishJayaswal** [comment]
@tannergooding can you please take a look at this?

**Comment by tannergooding** [comment]
Investigating.

**Comment by tannergooding** [comment]
@svick. This should be fixed with tonight's build (which will hopefully be on MyGet by 9:00PM tonight).

**Comment by svick** [comment]
@tannergooding Yeah, it seems to work now, thanks.
