### ISSUE TITLE
API Request: Adding custom items to IntelliSense

### ISSUE THREAD

**Issue by Novakov** [dotnet/roslyn#5047]
I was thinking about implementing postfix templates for C# using Roslyn (like https://github.com/controlflow/resharper-postfix). At first API exposed by Visual Studio (https://msdn.microsoft.com/en-us/library/ee372314.aspx) looked promising but it appeared to be independent from IntelliSense that Roslyn provides:
![image](https://cloud.githubusercontent.com/assets/420393/9705720/8b67518e-54ce-11e5-8288-2f9ebf1b0b10.png)

After going through roslyn's source code it looks to me that ability to provide custom `CompletionListProvider` instance via MEF (for now they are hardcoded) will allow to add custom items   to IntelliSense.

**Comment by Pilchie** [comment]
This is something @DustinCampbell is already looking at.

**Comment by sharwell** [comment]
:+1: I would love to get rid of the craziness in [Sandcastle Help File Builder's IntelliSense implementation](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/SandcastleBuilderPackage/IntelliSense). The RoslynHacks folder in there shows the extra work we had to do just for Roslyn.

**Comment by Pilchie** [comment]
At long last, I think this is actually fixed inhttps://github.com/dotnet/roslyn/pull/8170.
