### ISSUE TITLE
IDE Code Style Analyzer to remove empty lines

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#50471]
I know StyleCop already does this but should this be a default IDE Code Style analyzer or apart of Visual Studio's document format tools?

Here is the initial code:

![image](https://user-images.githubusercontent.com/46729679/104623128-e7b48900-5646-11eb-9461-229d2fc00420.png)

I would expect code cleanup or VS format to remove the empty lines like so:

![image](https://user-images.githubusercontent.com/46729679/104623209-fef37680-5646-11eb-8b06-f04ddaf1e180.png)

**Comment by CyrusNajmabadi** [comment]
I have a pr out that adds this feature. We just need a design meeting to get it accepted.

**Comment by CyrusNajmabadi** [comment]
This was added.
