### ISSUE TITLE
"vbc.exe" error code -2146232797 when a Derived Class has a Shared method that handles an event from a Shared WithEvents variable in its Base Class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50472]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1263908

_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/vbcexe-error-code--2146232797-when-a-/1305265)._

---
[severity:I'm unable to use this version]
Visual Studio produces the following error when compiling an application where a Derived Class has a Shared method that handles an event from a Shared WithEvents variable in its Base Class:

>error MSB6006: "vbc.exe" exited with code -2146232797.

The following is a sample module, in a Visual Basic .NET Framework Console application, that produces the error:

```
Module Module1
    Sub Main()
    End Sub
End Module

Public Class DerivedClass
    Inherits BaseClass

    Private Shared Sub Handler() Handles EventHost.SomeEvent
    End Sub
End Class

Public MustInherit Class BaseClass
    Protected Shared WithEvents EventHost As EventHost
End Class

Public Class EventHost
    Public Event SomeEvent()
End Class
```

---
#### Feedback Bot on 1/10/2021, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/14/2021, 09:08 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
The scenario shouldn't compile. Event hook-up for `Handles` in derived types is implemented by overriding `WithEvents` property. There is no way to declare an overridable shared property and overriding it in the derived class. Therefore, there is no way to perform the hook-up.
Native compiler reports a bunch of confusing errors at location that doesn't exist, but doesn't crash:
```
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
.vb(16707566) : error BC30043: 'MyBase' is valid only within an instance method.
```
