### ISSUE TITLE
NullableWalker should ignore locals of primitive value types such as 'int'

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#50473]
`NullableWalker` should avoid tracking state for locals of primitive value types such as `int`, to reduce overhead.

See `EmitErrorTests.CS0204_ERR_TooManyLocals()` for instance, which includes many `int` locals.

**Comment by jaredpar** [comment]
Optimistically putting in 16.9 but fine with moving it to 16.10

**Comment by RikkiGibson** [comment]
Can/should we do this for all unmanaged struct types?

**Comment by jaredpar** [comment]
That would match my expectation.

**Comment by jaredpar** [comment]
Think we have to special case `struct` that have a `Nullable<T>` though.

**Comment by RikkiGibson** [comment]
I'm still hoping to pitch the concept of specially tracking structs which contain nullable types. It might be convenient to implement this at that time.

**Comment by jaredpar** [comment]
Makes sense. I don't think this is critical for 17.0 so moved to 17.1 to give you time to discuss with the proposed struct + nullable types change.

**Comment by jaredpar** [comment]
Closing as it's been two years and haven't seen a need for this yet.
