### ISSUE TITLE
Snippets still broken, 2 year bug still a problem.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Snippets-still-broken-2-year-bug-still-/1296876)._

---
[severity:It bothers me. A fix would be nice]
This had been reported once before and to date this has still not been fixed.

I use snippets to add my comment formating, and this used to work at one point and somewhere it broke either in VS 2017, but 100% broken in VS 2019.

I have the following snippet

```xml
<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <Title>My Comment</Title>
      <Author>Andrew Scott</Author>
      <Description>Adds my Custom Comment</Description>
      <Shortcut>comm</Shortcut>
    </Header>
    <Snippet>
      <Code Language="CSharp">
<! [CDATA[//--------------------------------------------------------------------------------------------------------------------------------------------------------
//
//--------------------------------------------------------------------------------------------------------------------------------------------------------]]>
      </Code>
    </Snippet>
  </CodeSnippet>
</CodeSnippets>

```

What I am trying to get my snippet to do, is look like this once activate.

```csharp
    //--------------------------------------------------------------------------------------------------------------------------------------------------------
    //
    //--------------------------------------------------------------------------------------------------------------------------------------------------------
    private void OnTickCallback(object sender, ElapsedEventArgs e)
    {
        Counter -= 1;
        Debug.Log("Tick.........");
        UpdateText();
    }

```

However, it comes out like this instead.

```csharp
    //--------------------------------------------------------------------------------------------------------------------------------------------------------
        //
        //--------------------------------------------------------------------------------------------------------------------------------------------------------
    private void OnTickCallback(object sender, ElapsedEventArgs e)
    {
        Counter -= 1;
        Debug.Log("Tick.........");
        UpdateText();
    }

```

---
#### Andrew Scott on 12/27/2020, 05:23 PM: 

(private comment, text removed)
#### Feedback Bot on 12/27/2020, 06:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by cyberangel67** [comment]
No idea why this was closed on the Visual Studio support and has been added to Roslyn instead, would it be because Roslyn is used under the hood for Visual Studio?

**Comment by CyrusNajmabadi** [comment]
@cyberangel67 yes

**Comment by cyberangel67** [comment]
Well, fingers crossed it is finally fixed, this has been an issue that came from VS 2017, I just never used it much and in VS 2015 I never had an issue with it.

**Comment by sharwell** [comment]
This is a bug either in the indenter or in the formatter as it applies to snippet insertion.

**Comment by cyberangel67** [comment]
Any reason this is still not fixed in VS 2019?

And why it is also broken in VS 2022?

**Comment by CyrusNajmabadi** [comment]
@cyberangel67 It's on the backlog.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippet experiences.
