### ISSUE TITLE
if a project starts with a number and you create a new class the namespace is incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50492]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/if-a-project-starts-with-a-number-and-yo/1308836)._

---
[severity:It bothers me. A fix would be nice]
When creating a project with a number at the front it creates all namespaces with a "_" as prefix. But when creating a new class from the project explorer VS2019 omits the "_" and creates an invalid namespace.

---
#### Feedback Bot on 1/14/2021, 00:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
