### ISSUE TITLE
"Extract local function" generates broken code when applied to base constructor calls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Extract-local-function-generates-broke/1295410)._

---
[severity:It bothers me. A fix would be nice]
When code inside a `base` call in a constructor is highlighted, the "Extract local function" refactoring option is displayed. However, applying this refactor generates code that does not compile, since the generated `static` local function cannot be called from the base constructor initializer.

Sample

```
    public abstract class SomeBaseClass
    {
        private readonly int value;

public SomeBaseClass(int value) =>
            this.value = value;
    }

public sealed class SomeInheritedClass : SomeBaseClass
    {
        public SomeInheritedClass()
            : base("123456". Length)
        {
        }
    }
```

When the `"123456". Length` code is selected and quick actions is activated, the "Extract Local Function" option appears:

! [image.png] (https://aka.ms/dc/image?name=B668565d1389147c1b0fc08d886321fd6637443499191782568_20201223-165157-image.png&tid=668565d1389147c1b0fc08d886321fd6637443499191782568)

After applying the refactoring, this is the generated code:

```
    public sealed class SomeInheritedClass : SomeBaseClass
    {
        public SomeInheritedClass()
            : base(GetLength())
        {
            static int GetLength()
            {
                return "123456". Length;
            }
        }
    }
```

Which fails to compile due to multiple errors:

- Error	CS8321	The local function 'GetLength' is declared but never used	
! [image.png] (https://aka.ms/dc/image?name=B870e76cf981548a2b1a9df17f6ef3e9b637443501085368287_20201223-165507-image.png&tid=870e76cf981548a2b1a9df17f6ef3e9b637443501085368287)

- Error	CS0103	The name 'GetLength' does not exist in the current context	
! [image.png] (https://aka.ms/dc/image?name=Baf5181ee5e634dbca0894f768a85ea5e637443500744836074_20201223-165432-image.png&tid=af5181ee5e634dbca0894f768a85ea5e637443500744836074)

---
#### Feedback Bot on 12/23/2020, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Notes:
1. we have a language feature that may allow this to be legal in the future.
2. this is an interesting case as the user may be wanting to make a series of changes here.  i.e. perhaps they want to refactor this to compte in the body using a local function.  So it still seems nice to have this, though we should consider the priority of this tool versus normal extract-method (which will produce a more viable result).

**Comment by sharwell** [comment]
Marking as help wanted to disable this refactoring at this location until such time as the language includes static local functions from the body in scope for the `base(...)` invocation.

**Comment by CyrusNajmabadi** [comment]
@ryzngard  i think you may be working on a fix for something similar?

**Comment by ryzngard** [comment]
@CyrusNajmabadi yup, the linked PR

**Comment by CyrusNajmabadi** [comment]
@ryzngard wdym?

![image](https://user-images.githubusercontent.com/4564579/199623017-493dadc2-1c26-4b7f-bf38-8217e8034958.png)

**Comment by CyrusNajmabadi** [comment]
Oh, i see.  it's here:

![image](https://user-images.githubusercontent.com/4564579/199623047-3bc61500-7dad-412f-9fd8-db80a807a61c.png)

:)

Didn't know about taht.
