### ISSUE TITLE
Can not load roslyn-master\src\Samples\CSharp\Samples.sln

### ISSUE THREAD

**Issue by dongliu3** [dotnet/roslyn#505]
I am using Visual Studio  2015 CTP. There are a lot of error in the solution.
I can not load Microsoft.CodeAnalysis because when I run 
PM> Install-Package Microsoft.CodeAnalysis -Pre
Attempting to resolve dependency 'Microsoft.CodeAnalysis.CSharp.Workspaces (= 1.0.0.0-beta2)'.
Attempting to resolve dependency 'Microsoft.CodeAnalysis.CSharp (= 1.0.0.0-beta2)'.
Attempting to resolve dependency 'Microsoft.CodeAnalysis.Common (= 1.0.0.0-beta2)'.
Attempting to resolve dependency 'System.Collections.Immutable (= 1.1.32-beta)'.
Install-Package : Already referencing a newer version of 'System.Collections.Immutable'.
At line:1 char:1
+ Install-Package Microsoft.CodeAnalysis -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by davkean** [comment]
@dongliu3 You're running against some old bits, can you try against recent bits and see if you are still running into issues? If so, feel free to reopen or create a new issue.
