### ISSUE TITLE
.NET 5.0.2 release links to non-existant pages

### ISSUE THREAD

**Issue by grantborthwick** [dotnet/roslyn#50502]
Release [5.0.2](https://github.com/dotnet/roslyn/releases/tag/v3.8.0) has the following links that don't exist:
  * Release Notes - https://github.com/dotnet/core/blob/master/release-notes/5.0/*preview*/5.0.2.md
    * This should likely be https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.2/5.0.2.md
  * Install Instructions - https://github.com/dotnet/core/blob/master/release-notes/5.0/*preview*/5.0.2-install-instructions.md
    * This should likely be https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.2/5.0.2-install-instructions.md

**Comment by grantborthwick** [comment]
There's a similar issue against dotnet/core - https://github.com/dotnet/core/issues/5854

**Comment by Youssef1313** [comment]
Tagging @rbhanda

A similar issue: https://github.com/dotnet/winforms/issues/4471

**Comment by rbhanda** [comment]
I have resolved this issue for both the repos.
