### ISSUE TITLE
Convert tuple does not change camelCase element names to PascalCase field names

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#50505]
**Version Used**: 
Version 16.9.0 Preview 3.0 [30904.5.main]

**Steps to Reproduce**:

```C#
    class Program
    {
        static (int a, int b) s_field;  // invoke convert tuple to type here

        static void Main(string[] args)
        {
            Console.WriteLine($"{s_field.a} {s_field.b}");
        }
    }
```

**Expected Behavior**:

```C#
class Program
    {
        static NewStruct s_field;

        static void Main(string[] args)
        {
            Console.WriteLine($"{s_field.A} {s_field.B}");
        }
    }

    internal struct NewStruct
    {
        public int A;
        public int B;

        public NewStruct(int a, int b)
        {
            A = a;
            B = b;
        }

        ...
    }
```

**Actual Behavior**:
```C#
class Program
    {
        static NewStruct s_field; 

        static void Main(string[] args)
        {
            Console.WriteLine($"{s_field.a} {s_field.b}");
        }
    }

    internal struct NewStruct
    {
        public int a;
        public int b;

        public NewStruct(int a, int b)
        {
            this.a = a;
            this.b = b;
        }

        ...
    }
```

**Comment by CyrusNajmabadi** [comment]
this was intentional.  to match tuple semantics exactly, these are emitted as fields, not properties.  Being fields, they are named appropriately.  If there is a desire to change things to properties, then 'encapsulate field' can be used.

Note: i am amenable to 'convert to struct' having an option to 'use properties' instead of defaulting to fields (with the potential that that may break something).

**Comment by tmat** [comment]
Public fields should also be PascalCased.

**Comment by CyrusNajmabadi** [comment]
I'm not strongly opposed to that.  If someone does implement htis, the main issue will be about how to make the naming change.  We don't have any facility for bulk renaming.  Doing that efficiently is non-trivial.

**Comment by sharwell** [comment]
Blocked on #14115

**Comment by CyrusNajmabadi** [comment]
Closing as not planned.
