### ISSUE TITLE
Code Cleanup execution doesn't honor .editorconfig rules

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50504]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Code-Cleanup-execution-doesnt-honor-ed/1296870)._

---
[severity:It's more difficult to complete my work]
I have an .editorconfig file in every project I work on, and I'm trusting it to format my code using Code Cleanup button at the bottom of the CS code editor when I open the solution with the configuration it has, so I don't have to configure VS differently for every solution I work on.
I had it running correctly before, after setting Code Cleanup to use all fixers in Code cleanup configuration. 
I repeat, that worked before,  I don't know when it stopped working.

---
#### Feedback Bot on 12/27/2020, 06:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by TheReaLee** [comment]
Any updates on this @mavasani?
