### ISSUE TITLE
string "kind" is passed as exception message

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50523]
https://github.com/dotnet/roslyn/blob/1cca63b5d8ea170f8d8e88e1574aa3ebe354c23b/src/Compilers/CSharp/Portable/Syntax/TypeDeclarationSyntax.cs#L118

This should be `throw new ArgumentException(ADescriptiveMessageFromResources, nameof(kind));`

**Comment by jcouv** [comment]
I don't see the problem with this `throw` statement. We have many such instances of `ArgumentException` with just an argument name.

**Comment by Youssef1313** [comment]
@jcouv The argument name should be the second argument to ArgumentException. While the first one should be a message. Especially that this is a public API.

I believe there is a CA rule for this, it may be disabled for the repo.

**Comment by petrspelos** [comment]
Heya, this has been addressed in d6a3c916a919aa39d6647a42d0a0dcc149450f20 and can be closed. ☺️
