### ISSUE TITLE
IDE0018 C# Variable declaration can be inlined shown when variable declaration cannot be inlined

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50530]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/IDE0018-C-Variable-declaration-can-be-i/1310816)._

---
[severity:It bothers me. A fix would be nice]
VS 2019 propose me a "IDE0018	Variable declaration can be inlined	".
But the code change is wrong.
The code before:
>					var balanceInNormandy = 0m;
							var balanceInParis = 0m;
							var newQuantity = await paris. MarketPlace.NormalizeQuantity(this._symbol, Math.Min(this. MaxOrderQuoteAmount / bidPrice, res. Quantity));
							newQuantity = await normandy. MarketPlace.NormalizeQuantity(this._symbol, newQuantity);
							// On vérifie si on a assez de fond
							bool enoughtBalanceInNormandy = false;
							if ((await normandy. MarketPlace.GetSellLiveSocketBalancesAsync). TryGetValue(this._pair. Base, out balanceInNormandy))
							{
								if (balanceInNormandy * bidPrice > this. MinBalanceAvailableQuoteAmount)
		
The code after:
>							var balanceInNormandy = 0m;
							var balanceInParis = 0m;
							var newQuantity = await paris. MarketPlace.NormalizeQuantity(this._symbol, Math.Min(this. MaxOrderQuoteAmount / bidPrice, res. Quantity));
							newQuantity = await normandy. MarketPlace.NormalizeQuantity(this._symbol, newQuantity);
							// On vérifie si on a assez de fond
							bool enoughtBalanceInNormandy = false;
							if ((await normandy. MarketPlace.GetSellLiveSocketBalancesAsync). TryGetValue(this._pair. Base, out balanceInNormandy))
							{
								if (0m * bidPrice > this. MinBalanceAvailableQuoteAmount)

Its look like the fact that the call tp TryGetValue with an out parameter change the value of the parameter is not correctly handle.

---
#### Feedback Bot on 1/14/2021, 07:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Unclear what the issue is here.
