### ISSUE TITLE
Redundant usings (IDE0005) warning/error cannot be triggered using 'dotnet build'

### ISSUE THREAD

**Issue by maxild** [dotnet/roslyn#50533]
**Version Used**:

sdk-5.0.102 built-in `Microsoft.CodeAnalysis.CSharp.CodeStyle` (3.8.0)

**Steps to Reproduce**:

I have a public gh repo test case (very little code)

Offending source
https://github.com/maxild/SourceCodeAnalysisSpike/blob/a27692be112aeaa3b00201489e728e6c2cdf34dc/src/Program.cs#L5-L6

correct csproj props for enforcing code styles in build
https://github.com/maxild/SourceCodeAnalysisSpike/blob/a27692be112aeaa3b00201489e728e6c2cdf34dc/src/SourceCodeAnalysisSpike.csproj#L8-L9

correct editorconfig
https://github.com/maxild/SourceCodeAnalysisSpike/blob/a27692be112aeaa3b00201489e728e6c2cdf34dc/.editorconfig#L64-L65

correct build command (https://github.com/dotnet/roslyn/issues/43051#issuecomment-760466584)
https://github.com/maxild/SourceCodeAnalysisSpike/blob/a27692be112aeaa3b00201489e728e6c2cdf34dc/build.ps1

**Expected Behavior**:

See errors after CLI build. 

**Actual Behavior**:

The CLI build succeeds. Not even warnings are reported.

**Related Issues**

Possibly a dup of #33558 (Just thought many more IDxxxx rules could be raised as warnings on CLI build using .NET 5 sdk?)

**Comment by mavasani** [comment]
@maxild Have you enabled xml doc comments on the project? See the Note section at https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0005 for details.

**Comment by maxild** [comment]
@mavasani I missed that, my mistake. Sry. It builds with the expected number of IDE0005 warnings, as expected now (after having suppressed CS1591:smile:)
