### ISSUE TITLE
Region collapse/expand does not work properly on C# source code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50532]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Region-collapseexpand-does-not-work-pro/1307678)._

---
[severity:It's more difficult to complete my work] [regression]
On opening a C# file regions lack +/- buttons to expand collapse them.
I can expand the region by double clicking on it. It makes +/- to show up, but the expanded region stays +.
Switching the focus away from VS studio Window also bring +/- buttons back and region markers. It also makes expanded region
For this reason it is not possible to take a snapshot.
I just realized that simply waiting for about 5 seconds also make region markers and +/- buttons appear.
Then collapse the region. The - sign does not turn into a +..
Expand another region. It makes the previous region - to become +.

---
#### Feedback Bot on 1/12/2021, 09:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dmitri Smirnov [MSFT] on 1/14/2021, 04:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @olegtk pleae port to editor.
