### ISSUE TITLE
[Discussion] VB.net Pattern-Matching Syntax

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#5054]
I propose that for pattern-matching support in VB.net, that we extend the capabilities of the `Select Case` 

* **Guards**  

> `When` *boolean-expression*
Conditionally match against the pattern. If the pattern matches and guard is true then execution this pattern's code block.

* **Select Case Expression**  
Permit the `Select Case` as an expression / function.  
 Return values are scoped to the `Select Case Expression`, and not the enclosing scope.

**example 0**
```vb.net
Dim foo =  Select Case x
             Case Is < 0 : Return "Negative"
             Case 0      : Return "Zero"
             Case 1      : Return "Single"
             Case Else
               Return "More than 1"
             End Select
```

**example 1**
```vb.net
Function Foo( x As Integer) As String
  Return Select Case x
           Case Is < 0 : Return "Negative"
           Case 0      : Return "Zero"
           Case 1      : Return "Single"
           Case Else
             Return "More than 1"
           End Select
End Function
```
**Note:** If the first `Return` wasn't included ~~then then return value *(in this example)* would be `Nothing`, irrespective of what the **select case expression** actually returned
*Effectively think of it as calling a function and ignoring the returned value*~~
**Correction**
It would be the statement form of `select case`.

----------
### grammar  

> *match-block* := 
   **Select Case (** *parameters* **)**
    *selection-block?*
 *default-block*
 **End Select**
>
*selection-block* := *match-selection**
*match-selection* := **Case** *patterning selection-code*
*selection-code* := *.....*  
*patterning* := *patterns-guard* | *pattern-guards*   
*default-block* := *default-guards* *default-match*
*default-head* := **Case Else**
*default-guard* := *default-head* *guard* *selection-code*
*default-guards* := *default-guard**
*default-match* := *default-head selection-code*
>
*pattern :=* **(** *pattern-expr* **)**
*guard* := **When (** *predicate* **)**
>
*pattern-guard* := **(** *pattern guard* **)**
*patterns* := **(** *pattern* (**,** *pattern* ) * **)**
*patterns-guard* := *patterns guard* 
*patterns-guards* := **(** *pattern-guard* ( **,** *pattern-guard* ) * **)**  

----------
### *pattern-expr* :-  
> *pattern-expr* := *simple* | *range* | *relative* | *wild-card* |  *typemask* | *recursive* 
> *simple* := *literal*
> *range* := *literal-numeric* **To** *literal-numeric*
> *relative* := **Is** *expr*
> *typemask* := **(** *identifier* **=** *expr0* **As** *type-identifier* **)**
> *wild-card* := *
> *recursive* := .....

### *selection-code* :-  
This section is the code to execute should the pattern match and the guard predicate is true.

----------

### Example

```vb.net
Function Simplify( e As Expr ) As Expr
  Return _ 
    Select( e )
      Case Add(l,r):
        Return Select Case (l,r)
                 Case (Const(0),*): Return Const(r)
                 Case (*,Const(0)): Return Const(l)
                 Case (Const(a),Const(b)): Return Const(a+b) 
                 Case Else: Return Add(Simplify(l),Simplify(r))
               End Select
       Case Mul(l,r):
         Return Select Case (l,r) 
                  Case (Const(0),*), (*,Const(0)) 
                    Return Const(0)
                  Case (Const(1),*): Return Const(r)
                  Case (*,Const(1)): Return Const(l)
                  Case (Const(a),Const(b)): Return Const(a*b)
                  Case Else: Return Mul(Simplify(l),Simplify(r))
               End Select
       Case Sub(l,r):
         Return Select Case (l,r)
                  Case (Const(0),*): Return Const(-l)
                  Case (Const(a),Const(b)): Return Const(a-b)
                  Case Else: Return Sub(Simplify(l),Simplify(r))
                End Select
       Case Div(l,r):
         Return Select Case (l,r)
                  Case (*,Const(0)): Return ERR_DivideByZero
                  Case (*,Const(1)): Return Simplify(l)
                  Case (Const(a),Const(b)): Return Const(a/b)
                  Case Else: Return Div(Simplify(l),Simplify(r));
                End Select
       Case Else
         Return e
       End Select
  End Select
End Function
```

**Comment by HaloFour** [comment]
The one big problem I see with this is that `Return` within a `Case` already means to return from the enclosing method.  You'd change the semantics of the statement entirely just by omitting the `Dim i = ` from your first example, and since it's perfectly legal to just discard the result of an expression that would be doubly-confusing.

**Comment by gafter** [comment]
It seems strange to go to all this trouble to work on a complex compound statement/expression thing without even specifying the simplest pattern-matching form (corresponding to the current C# `is` proposal).

I do not think we would want a new expression form in which subexpressions could include control statements (especially those that interact with enclosing statements). If we did want to add support for statements in expressions, pattern matching is a very strange place to introduce them, and @HaloFour 's comment explains some of the simple problems you're ignoring in your attempt. I plan to extend the existing `Select Case` for the statement form, and I expect some kind of `Match` expression will be specified with a simple expression on each case branch.

**Comment by AdamSpeight2008** [comment]
> @gafter **wrote:**
>It seems strange to go to all this trouble to work on a complex compound statement/expression thing without even specifying the simplest pattern-matching form (corresponding to the current C#  is  proposal).

I did specify it. `Is` has a currently existing meaning in `Case`'s 
> Is ] comparisonoperator expression

We shouldn't as use it to mean something completely different. 
So I chose to use declaration syntax, as the *identified value* will like be with the *section-code*

typemask := **(** *identifier* **=** *expr0* **As** *type-identifier* **)**
wild-card := *
recursive := .....

mmm
> @gafter **wrote:**
> I do not think we would want a new expression form in which subexpressions could include control statements (especially those that interact with enclosing statements)

I don't see and issue with allowing them. the value of the **target** could be
* the default value for the type like a `.TryParse`, with the additional condition that the variable must declared with type be it can be used as a "match expression" target.
* maintain the variable's existing initialisation state and value
* the target is an `Option(Of T)` with a value of `Option.None`

------

All lot of the issues are, we are trying to shoehorn in functional concepts into the language (C# and VB.net). Yet not have the basic primitives of functional languages. 
* `Func<T>` where T can be `Void`, instead we have disconnected type `Action<>`
* No option or maybe type, that support but `Class` and `Structure` types.
* Everything is a function

**Comment by gafter** [comment]
The code `Select Case (l,r)` appears to be used in your example but is not allowed by your grammar.

The patterh `Const(0)` appears to be used as a pattern in your example but is not allowed by your grammar.

You don't appear to give any syntax form for pattern-matching that could be used in an `If` statement.

**Comment by AdamSpeight2008** [comment]
@gafter 
>You don't appear to give any syntax form for pattern-matching that could be used in an  If  statement.

Why would I want that ? I've got a pattern-matching match expression.

> The code  Select Case (l,r)  appears to be used in your example but is not allowed by your grammar.

*parameters*'s definition I've yet to define.

**Comment by gafter** [comment]
>>You don't appear to give any syntax form for pattern-matching that could be used in an  If  statement.

>Why would I want that ? I've got a pattern-matching match expression.

I see more `If` statements in VB code than I do `Select`, so I suspect there is a reason that people prefer it. You might want to write a simple example of a pattern match in the condition of a VB `While` loop to see why something like C#'s `is` pattern-matching operator is useful.

>*parameters*'s definition I've yet to define. 

Ah. I'll ignore this issue until you've completed it, then.

**Comment by AdamSpeight2008** [comment]
Since it being used as an expression I can return True or False. 
```vb
IF (SELECT CASE obj
      CASE Int32 : Return True
      CASE ELSE
        Return False
    END SELECT ) Then 

End If
     
```
Thus it can be use where a *boolean -expression* is expected
*i know that looks like cack*

**Comment by AdamSpeight2008** [comment]
This topic focuses only the structural appearance of a pattern-matching construct. 
The specific implementation of `match-arg` and `pattern-block` will be discuss in a separate issue.

> Select-Match-Expr := **Select Match (** *match-arg?* **)** *asType* *match-body* *match-foot*
Match-Args        := *match-arg* (**,** match-args )?
Match-Arg := *to-be-discussed*
AsType := **As** *typeIdentifier*
Match-Body :-  *match-cases?* *guared-defaults?* *match-default*
Match-Foot :- **End Select**
Mathe-Cases :-  *match-case* (**,** match-cases )?
Match-Head :- **Case**
Match-Case :- *match-head* *patterning* *guard?* *match-code*
Match-Code :- *expression*
Guard := **When (** *predicate* **)**
Predicate :- *boolean-expression**
Patterning :- *pattern* (**,** patterning )?
Pattern :- **(** *pattern-block* *guard?* **)**
Guarded-Defaults :- *guarded-default*&#42;
Guarded-Default :- *match-head* **Else** *guard* *match-code*
Match-Default :- *match-head* **Else** *match-code*
 Pattern-Block :- *to-be-discussed*

```vb
Dim result = Select Match( e As Expr ) As Expr
               Case MUL(Const(0),*),     MUL(*,Const(0))      : Return Const(0)
               Case MUL(Const(1),x:= *), MUL(x:= *, Const(1)) : Return Simplify(x)
               Case MUL(Const(x:= *), Const(y:= *))           : Return Const(x*y)
               Case Else
                 Return e
             End Select
```

A possible alternative would be;-
> Select-Match-Expr := **Select Function (** *match-arg?* **)** *asType* *match-body* *match-foot*

So that it looks like a function (or lambda) and thus the contextual meaning of 'Return', is return from the localised scoping of this "pattern-match" expression / function.

```vb
Dim result = Select Function( e As Expr ) As Expr
               Case MUL(Const(0),*),     MUL(*,Const(0))      : Return Const(0)
               Case MUL(Const(1),x:= *), MUL(x:= *, Const(1)) : Return Simplify(x)
               Case MUL(Const(x:= *), Const(y:= *))           : Return Const(x*y)
               Case Else
                 Return e
             End Select
```

**Comment by AdamSpeight2008** [comment]
It would allow `pattern-matching` `select function` to be used inside `Select Case` (switch in c#). Or vis-versa.

```vb
Select Case x
  Case 0
    myvar = Select Function ( myObj )
              Case  ( o As Int)
                Return "Foo"
              Case Else
                Return "Bar"
            End Select
  Case 1
    myvar = "Baz"
  Case Else
    myvar = "WTF"
End Select
```
