### ISSUE TITLE
Improve error message when operator overload resolution fails

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50557]
```csharp
using System;

S s;
Console.WriteLine(s == default);

public struct S { }
```

## Expected Behavior:

> error CS0019: Operator '==' cannot be applied to operands of type 'S' and 'S'

## Actual Behavior:

> error CS0019: Operator '==' cannot be applied to operands of type 'S' and 'default'

**Comment by svick** [comment]
There is nothing that says `default` in that code has to mean `default(S)`. For example, [the following code works just fine](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKFwZQAIBnAblxQwE4AKYwgXgcIBMI4BDAVwBtgBKcnhwoAzCWBQuAY2CF8uAN65CqwmPUYAbIQBGAe309C+gA7QOwfVCY0ixADSEYAOzkx+jAHyFOPYhBCaurilDoGRibmUJbWAIQMdiROru6eDD6SXIG4AL5AA==):

```c#
using System;

S s;
Console.WriteLine(s == default);

public struct S
{
    public static bool operator==(S s, int i) => false;
    public static bool operator!=(S s, int i) => true;
}
```

But here, the `default` means `default(int)`.

So I think the existing error message is accurate, and changing it as you suggested would make things worse.

**Comment by Youssef1313** [comment]
> For example, the following code works just fine:

I missed this case. Thanks.
