### ISSUE TITLE
REQUEST:  LINQify foreach

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#5055]
Hi All,
I would like to suggest that the ForEach statement be enhanced to support syntax similar to the following:

foreach(var item in collection where item != null && item < 10 orderby item.Index desc) {
//Body of loop
}

this would be the same as writing:

foreach (var item in (from item in collection where item != null && item < 10 orderby item.Index desc select item)){
//Body of loop
}

**Comment by dsaf** [comment]
#1938 with different syntax.
