### ISSUE TITLE
Change Signature window show value instead of used constants for defaults

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#50561]
**Version Used**: 

Microsoft Visual Studio Community 2019 Preview
Version 16.9.0 Preview 2.0
VisualStudio.16.Preview/16.9.0-pre.2.0+30803.129

**Steps to Reproduce**:

1. Method or constructor
2. Parameter of value types (e.g. `ushort`)
3. Parameter have default value, but a constant (e.g. `ushort.MaxValue`)
4. `Alt+Enter`
5. Choose "Change Signature"

**Expected Behavior**:
Change Signature Window should show used constants for default values instead of the value itself.

**Actual Behavior**:
![2021-01-16 21_37_22-PowerToys - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/104822612-2b281680-5844-11eb-88e1-52052cca06a2.png)

**Comment by CyrusNajmabadi** [comment]
Closing otu due to lack of broader feedback on this.
