### ISSUE TITLE
Emit more compact IL for floating point constants

### ISSUE THREAD

**Issue by jfd16** [dotnet/roslyn#50571]
It is possible to generate more compact IL for floating-point constant values, like what is currently done for `long` and `ulong`.

* For float and double constants representing integer values for which single-byte `ldc.i4.*` instructions are available, emit that instruction followed by `conv.r4` or `conv.r8`.
* For float and double constants representing integer values in [-128, 127], emit `ldc.i4.s` followed by `conv.r4`/`conv.r8`.
* For double constants whose values are representable as 32-bit signed or unsigned integers, emit `ldc.i4` followed by `conv.r8`/`conv.r.un`. (Don't do this for floats as that would increase code size)
* For double constants whose values are representable as single-precision floats (that is, `(double)(float)value == value` is true), emit `ldc.r4`. (No need for `conv.r8` as that conversion is implicit in IL)

Note that negative zero should not be considered to be "representable as an integer" for this purpose.

I suppose that the CLR JIT compiler would optimize the conversions away, but someone should investigate if this may cause any runtime performance penalty.

**Comment by CyrusNajmabadi** [comment]
What would the benifit of this be?  @tannergooding for thoughts.

**Comment by tannergooding** [comment]
> What would the benifit of this be

Floating point constants are 1 instruction taking `5 bytes` or `9 bytes`, respectively, in IL today. This would change it to 2 instructions taking `2 bytes` for `-1`, or `[0, 8]` and `3` bytes for values for values `[-128, 127]`.
This would help reduce the number of IL bytes a method takes and could possibly help with inlining heuristics or other scenarios.

The drawbacks are namely that this isn't a pattern that really exists today outside of inside the JIT inlining a method and so the JIT (or other tooling) may not actually handle it well.
It may also be that most usages of `float`/`double` aren't integers between `[-128, 127]` and so the real world size reductions might be minimal.

If there wasn't any drawbacks in the JIT, then this should be "safe" for any integer where the absolute value is less than 2^24 and 2^53, respectively.
Above this range, powers of two are exactly representable as are certain other integers.
There is likewise some subset of `double` constants that could be represented as a `float` and then safely upcast to `double` via `conv.r8` without loss of precision.

In any case, someone from the JIT team would probably need to chime in on whether they think this is worthwhile.

**Comment by CyrusNajmabadi** [comment]
I'd love an actual analysis of what total percent savings we would get on real world assemblies. :-)

**Comment by huoyaoyuan** [comment]
> It may also be that most usages of `float`/`double` aren't integers between `[-128, 127]`

Somehow doubtful.

https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFMDeqmJ2WAJgPYCuARhAKaYCyAFFXY5gG4CUmAXgB8PTAHpMcANyoAvkA===

Multiplying or dividing by a small constant integer is common. But it won't contribute a lot.

**Comment by jaredpar** [comment]
In order to take a change like this we need to validate a few items:

1. The change is a performance win. A change that produces less or smaller IL does not necessarily produce faster programs. In fact it can slow them down. The JIT is often keyed to common IL patterns emitted by the compiler. That means there are cases where swapping to more 'efficient' IL causes perf regressions because it removes JIT optimizations. 
2. The change is going to be significantly impactful. Need to see for instance what type of size reduction we'd get if we applied to runtime, aspnetcore and likely machine learning. If we wouldn't see substantial wins there I can't see this being worth the cost of implementing / maintaining.
