### ISSUE TITLE
Completion of property patterns doesn't add the colon

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50570]
![image](https://user-images.githubusercontent.com/31348972/104852816-af8e9e00-5905-11eb-930b-42ca30f05056.png)

IntelliSense shows the colon, however, the auto completion doesn't add it.

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by sharwell** [comment]
Note: Make sure if the commit character is <kbd>:</kbd>, only one `:` is added. Also, this change should apply to property patterns but should _not_ apply to arguments is calls.

**Comment by genlu** [comment]
There's prior requests similar to this, for example #32204. I feel this particular case of pattern matching might be different and completing with ":" does make more sense here IMO. However I'm more inclined to keep things consistent. Thoughts? @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
> However I'm more inclined to keep things consistent. Thoughts? 

I'm inclined to keep things consistent, unless htere's a super compelling case made.  Thanks! :)

**Comment by Youssef1313** [comment]
I can see the reason why named arguments completion don't add the colon. But I don't think this is the case with C# 9.
Are there any cases where the user don't want the colon?

**Comment by genlu** [comment]
> Are there any cases where the user don't want the colon?

As I said above, I agree with you it makes sense to add colon if we only focus on this single scenario. However, considering all other cases where completion items contain ":" suffix but commit doesn't add it, maintaining a consistent commit behavior would be more important, especially considering ":" is a commit char so the number of keystroke with or without auto-append the ":" would be the same.

**Comment by sharwell** [comment]
I'm one of the users who hit the underlying issue in #32204 daily. I can't think of a way for the same situation to occur when working with patterns. It's easy enough to just type `:` as the completion character, so a change here maybe isn't required, but it also isn't likely to cause problems.

With that said, if we end up implementing collection patterns _using braces_, it's possible we end up in a bad situation again. Hard to be sure.

**Comment by Youssef1313** [comment]
Would it be good to make that an option in Visual Studio (disabled by default), which applies to both named parameters and property patterns (or two separate options)?

That is, if the user explicitly enabled it, the colon is inserted automatically. Probably as an experimental feature in the beginning and monitor user usage and feedback of it.

**Comment by sharwell** [comment]
@Youssef1313 There is no need for an option here. It would just make the code more complicated for a user savings of 0 typed characters.

**Comment by Youssef1313** [comment]
> @Youssef1313 There is no need for an option here. It would just make the code more complicated for a user savings of 0 typed characters.

While, as a user, the current behavior doesn't seem to be ideal. I also understand that adding an option is unnecessary maintenance cost.

So that gets us back to whether the patterns should be consistent with named arguments or not.

Once the team agrees on a decision on this, the issue can be fixed or closed.

**Comment by ryzngard** [comment]
Design Review: We would accept this change for pattern matching. All instances require a `:` syntax from the language, so inserting makes sense.

**Comment by Youssef1313** [comment]
I think this is no longer valid. One can have `.` like `obj is { P1.P2.P3: /*...*/ }`

Should this be closed?

**Comment by CyrusNajmabadi** [comment]
We could still have the colon.  But not insert it of the user completes with `dot`.  @sharwell thoughts?  Should we close?  Or refine the proposal here?

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of response.
