### ISSUE TITLE
Rename refactoring erroneously changes named arguments of target-typed new expressions

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#50589]
**Version Used**: 16.8.4, 16.9.P2

Invoke renaming:

```cs
class C
{
    C(int foo) { }

    C M()
    {
        var [||]foo = 1;
        return new(foo: 2);
    }
}
```

The named argument is changed along with the variable name:

![image](https://user-images.githubusercontent.com/8040367/104976136-808e3000-59ca-11eb-94df-5d9244573454.png)

This is not the case if you stop using target-typed new:

![image](https://user-images.githubusercontent.com/8040367/104976203-a7e4fd00-59ca-11eb-8739-9e2a4abe518c.png)

**Comment by CyrusNajmabadi** [comment]
Problem at the FAR level:

![Uploading image.png…]()
