### ISSUE TITLE
"Add missing using directives on paste" option cannot be checked

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#50587]
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 main
Version 16.9.0 Preview 4.0 [30917.14.main]

**Steps to Reproduce**:

1.  Tools -> Options -> Text Editor -> C# -> Advanced
2. Check the option

![Option](https://user-images.githubusercontent.com/1103906/104973128-f1276200-5a47-11eb-954d-15504d4fa451.gif)

**Expected Behavior**:
For the option to be checked

**Actual Behavior**:
The option is not checked

Once in this state you can't uncheck it.

**Comment by CyrusNajmabadi** [comment]
@ryzngard can you ptal?

**Comment by ryzngard** [comment]
Looking
