### ISSUE TITLE
Enhanced Debugging Support

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#5059]
Oftentimes, I find myself needing to check the values returned in methods with signatures like `GetFoo()`.  Would it be possible to allow us to manually activate such methods (essentially, any non-void method without a parameter) and view the result, similar to the way we can manually run other threads to view updated list results, etc.?

**Comment by svick** [comment]
How is this different from the existing Watch window?

**Comment by ManishJayaswal** [comment]
@Hosch250  have you tried using $ReturnValue1 in watch or immediate window?

**Comment by Hosch250** [comment]
@ManishJayaswal No, I haven't.  I will definitely check that out as soon as possible.
