### ISSUE TITLE
Is it possible to customize the behavior of string interpolation without the `FormattableString` allocation?

### ISSUE THREAD

**Issue by justinvp** [dotnet/roslyn#506]
With the current string interpolation design, is it possible to customize the behavior of the string format without the `FormattableString` allocation?

The canonical example is formatting with the invariant culture:

```c#
FormattableString.Invariant($"{{ lat = {latitude}; lon = {longitude} }}");
```

This allocates `FormattableString` and an `object[]` for the arguments, and any arguments that are values types are boxed.

Is there a way to reduce any of these allocations with the current design of the language feature?

**Comment by HaloFour** [comment]
@justinvp Last I checked `FormattableString` itself is a `struct` so that's one allocation down.  How exactly would the individual arguments be stored if not boxed in an array?

**Comment by justinvp** [comment]
AFAIK, `FormattableString` is a class. See https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/FormattableString.cs

**Comment by HaloFour** [comment]
@justinvp Ah, perhaps it switched.  I poked at one of the later threads on CodePlex which still showed it as a `struct`, but those design docs changed so many times it was impossible to keep up.

**Comment by gafter** [comment]
You can actually provide your own implementation of FormattableString and its factory. I don't know how you're going to get an arbitrary number of arguments into a struct, though.

**Comment by justinvp** [comment]
@gafter How would I provide my own implementation of `FormattableString` and factory? Is it possible to have my factory use a custom `struct` rather than having to allocate a `FormattableString`?

**Comment by gafter** [comment]
@justinvp Declare FormattableString as a struct in your own code. Make sure to put it in the right namespace.

**Comment by justinvp** [comment]
@gafter Why isn't the built-in `FormattableString` a `struct`?

**Comment by gafter** [comment]
@justinvp We wanted to allow specialized subclasses that store, for example, 1, 2, or 3 arguments without allocating an array. That is not done in the current version but we expect to do that.

**Comment by gafter** [comment]
@justinvp The compiler uses a class called FormattableStringFactory to create the instances using a static factory method Create which is selected by overload resolution. You'll have to provide the factory as well.

**Comment by justinvp** [comment]
> We wanted to allow specialized subclasses that store, for example, 1, 2, or 3 arguments without allocating an array.

That sounds awesome! But in that case you're avoiding the array allocation but still have a `FormattableString` allocation.

**Comment by gafter** [comment]
@justinvp If you'd like to take a crack at whatever optimizations you have in mind for avoiding allocations, I expect the folks over at https://github.com/dotnet/coreclr/ would be happy to consider your pull request.

**Comment by justinvp** [comment]
@gafter Is there an up-to-date spec (or even just a draft) available for C# string interpolation feature that you could point me to? I'm just trying to understand what the language expects/allows. Thanks!

**Comment by gafter** [comment]
I suggest looking over on roslyn.codeplex.com. We're working on integrating the latest changes into the whole C# language spec, but it isn't in a form we can share right now.

**Comment by justinvp** [comment]
@gafter I found https://roslyn.codeplex.com/discussions/570614, but it seems to be out of date (it says `FormattableString` is a `struct` and doesn't mention `FormattableStringFactory`)

**Comment by gafter** [comment]
`FormattableStringFactory` was added to enable overload resolution to select one or another implementation. As you note, there are no public docs describing the currently implemented (open-source) design.
