### ISSUE TITLE
License mismatch in VbMyTemplateText.vb and project root

### ISSUE THREAD

**Issue by sergeyQx** [dotnet/roslyn#50604]
First line of VbMyTemplateText.vb https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Symbols/EmbeddedSymbols/VbMyTemplateText.vb reads "Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information." while the License.txt at project root is MIT https://github.com/dotnet/roslyn/blob/master/License.txt which was introduced by the commit https://github.com/dotnet/roslyn/commit/0d04884c243978cdd609e219fdb63cb58ebec69d to fix the issue https://github.com/dotnet/roslyn/issues/37797

**Expected Behavior**:
Apache 2.0 should be replaced with MIT in VbMyTemplateText.vb and other files

**Actual Behavior**:
There is Apache 2.0 still

**Comment by Youssef1313** [comment]
This specific file was fixed in https://github.com/dotnet/roslyn/pull/41268.
