### ISSUE TITLE
"Option Text" Causes Visual Studio 2017 and 2019 To Crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50610]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1259354

_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Option-Text-Causes-Visual-Studio-2017-/1292132)._

---
[severity:It bothers me. A fix would be nice]
**Issue:**
Adding the line "Option Text" as the first line in a VB.NET code file causes Visual Studio 2017 and 2019 to crash. I realize that code line should be "Option Compare Text" but the crash is bothersome.

**To reproduce the issue:**
1. Create a new Console App (.NET Framework) with VB.NET using Visual Studio 2017 or 2019.
2. Insert a new line above `Module Module1`.
3. Type `Option Text` at the start of the newly inserted line. Visual Studio crashes.

**Expected behavior:**
Visual Studio should show a red, squiggly line under some, or all, of "Option Text".

_The screenshot shows the keystrokes up to the last "t" in "Option Text". Typing the last "t" crashes Visual Studio on my machine._

---
#### Mila Zhou[MSFT] on 12/20/2020, 10:23 PM: 

<p>Thank you for taking the time to log this issue!</p>
<p>In order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool – <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed">full instructions</a><br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a> , you can get tips on how to provide clear and simple reproducible steps.</p>
<p>Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>
<p>We look forward to hearing from you!</p>

#### Feedback Bot on 12/29/2020, 06:58 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Feedback Bot on 1/14/2021, 11:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/19/2021, 07:39 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Feedback Bot solved on 1/13/2021, 06:02 PM, 0 votes: 

We are unable to investigate this issue further without the additional information requested. If you are able to provide more information, you can request the issue being reactivate below. See our [guidelines](https://aka.ms/vsfeedbackguidelines) for further information about our process.

#### Bill Besancenez on 1/14/2021, 07:22 AM: 

<p>This is very simple to reproduce.</p>
<ol>
<li>Create a new Console App (.NET Framework) with <a target='_blank' href="http://VB.NET">VB.NET</a> using Visual Studio 2017 or 2019. This creates a new console app with one code file, “Module1.vb”. That file is open in the editor and looks like this:</li>
</ol>
<pre><code><span class="hljs-attr">Module</span> <span class="hljs-string">Module1</span>

    <span class="hljs-attr">Sub</span> <span class="hljs-string">Main()</span>

    <span class="hljs-attr">End</span> <span class="hljs-string">Sub</span>

<span class="hljs-attr">End</span> <span class="hljs-string">Module</span>
</code></pre>
<ol start="2">
<li>Type “Option Text” above the first line.</li>
</ol>
<pre><code><span class="hljs-attr">Option</span> <span class="hljs-string">Text</span>

<span class="hljs-attr">Module</span> <span class="hljs-string">Module1</span>

    <span class="hljs-attr">Sub</span> <span class="hljs-string">Main()</span>

    <span class="hljs-attr">End</span> <span class="hljs-string">Sub</span>

<span class="hljs-attr">End</span> <span class="hljs-string">Module</span>
</code></pre>
<ol start="3">
<li>When you press the last “t” in “Text” Visual Studio will hang, crash and restart.</li>
</ol>

**Comment by AlekseyTs** [comment]
```
        <Fact>
        Public Sub SyntaxError_01()
            Dim compilation = CreateCompilation(
<compilation name="GetSemanticInfo">
    <file name="a.vb">
Option Text
    </file>
</compilation>)

            compilation.AssertTheseDiagnostics(
<expected>
</expected>)

            Dim tree = compilation.SyntaxTrees.Single()
            Dim model = compilation.GetSemanticModel(tree)
            Dim root = tree.GetRoot()
            For i As Integer = 0 To root.Span.End
                model.GetEnclosingSymbol(i)
            Next
        End Sub
```
