### ISSUE TITLE
Program using Roslyn Compiler works in 4.8 but not in net5

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/roslyn#50612]
I've a program wich uses Roslyn to compile user code at runtime.

This Program uses some nugets wich are only netstandard1.4

The program works as expected in Net4.8
In netcore5 in need to add MetadataReferences to "netstandard" and "System.Runtime" via string to get it to work.
Is there another way?

See following Code:

    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.Emit;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;

    namespace CompilerTest
    {
        class Program
        {
            static void Main(string[] args)
            {
                var code = @"
    using System;

    namespace CompilerTest
    {
        class Test
        {
            BetterWin32Errors.Win32Error bb;
        }
    }
    ";
            
                SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(code, new CSharpParseOptions(kind: SourceCodeKind.Regular, languageVersion: LanguageVersion.Latest));
                string assemblyName = Path.GetRandomFileName();

                var references = new List<MetadataReference>()
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(BetterWin32Errors.Win32Error).Assembly.Location),
                    //MetadataReference.CreateFromFile(Assembly.Load("netstandard").Location),
                    //MetadataReference.CreateFromFile(Assembly.Load("System.Runtime").Location)
                };

                var compilation = CSharpCompilation.Create(
                    assemblyName,
                    syntaxTrees: new[] { syntaxTree },
                    references: references,
                    options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                        optimizationLevel: OptimizationLevel.Debug));

                using (var ms = new MemoryStream())
                {
                    EmitResult result = compilation.Emit(ms);

                    if (!result.Success)
                    {
                        IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                            diagnostic.IsWarningAsError ||
                            diagnostic.Severity == DiagnosticSeverity.Error);

                        var compilerErrors = failures.Select(x => x.ToString());

                        Console.WriteLine("Compile Errors: " + compilerErrors);
                    }
                    else
                    {
                        Console.WriteLine("Compile Okay");
                    }
                    Console.ReadLine();
                }
            }
        }
    }

if you uncomment the lines:

                    //MetadataReference.CreateFromFile(Assembly.Load("netstandard").Location),
                    //MetadataReference.CreateFromFile(Assembly.Load("System.Runtime").Location)

it also works in netcore.

If not you get the Exception of the missing references.

**Comment by jogibear9988** [comment]
@ericstj at first thanks for the information.

maybe we find a good solution / best practice how to solve this.

**Comment by jogibear9988** [comment]
@ericstj does it mean i need the sdk for all versions i possible use dll's of, or do I only need the sdk from the runtime i run against?
So if I use a dll compiled for net3.1 and I use net5, do I also need net3.1 sdk?

**Comment by jogibear9988** [comment]
I've had a similiar issue on a frok of the vs texttemplating engine from mono (with some patches) https://github.com/jogibear9988/SubSonic.Core.TextTemplating
most of my templates referenced some net4x/netstandard dlls, so to make the work on netcore i need to add additional assembly directives. Would be nice if there is an easier solution.

**Comment by ericstj** [comment]
@tmat @jaredpar can you provide a best-practice recommendation for replicating MSBuild's auto-reference functionality?  Should folks include everything in the framework, or can they implement a resolver of sorts that adds things as needed.

**Comment by tmat** [comment]
We don't have anything really convenient, just this: https://github.com/dotnet/roslyn/blob/master/docs/wiki/Runtime-code-generation-using-Roslyn-compilations-in-.NET-Core-App.md#compile-against-reference-contract-assemblies

**Comment by jogibear9988** [comment]
If I use the last approach in this document:

      Alternatively, projects that use .NET SDK can set PreserveCompilationContext build property to true. Publishing such project will copy reference assemblies for the framework the project targets to a refs sub-directory of the publish directory.

Do I then need to reference the dll's in the refs folder or will the compiler find&load them automaticaly?

**Comment by tmat** [comment]
You'll need to reference them.

**Comment by jaredpar** [comment]
I did start a prototype project to make building in memory `Compilation` objects a bit easier:

https://github.com/jaredpar/roslyn-codedom

The project essentially grabs all the `netcoreapp3.1` reference assemblies, embeds them as resources in a DLL, and then adds a few extension methods to `Compilation` to make it easy to use. 

``` c#
Compilation compilation = ...;
compilation = compilation.WithFrameworkReferences(TargetFramework.NetCoreApp31)
```

It may be a good starting point for the work you are doing.
