### ISSUE TITLE
Please make the code for IsManagedType public

### ISSUE THREAD

**Issue by mike-barnett** [dotnet/roslyn#5063]
I need to know if a type is a managed type or not. (I’m doing some code generation and only non-managed types can be used in fixed statements.) I’ve found the code in the Roslyn codebase, but it is all internal. Is there some reason to not expose this? Seems like a question clients should be able to ask. Certainly this client does!

Thanks!

**Comment by mike-barnett** [comment]
My concrete scenario is that we are using Roslyn for dynamic code generation for Trill, which is Microsoft's next-generation streaming query processing engine. It already powers Azure Stream Analytics and is used by many groups within in the company. It is crucial for Trill's performance that we generate custom operators for each query. These operators must be efficient: that is why Trill is 2 to 4 *orders of magnitude* faster than any other streaming engine. It is so fast that it is comparable with the world's fastest relational query engines. (Details can be found in http://research.microsoft.com/apps/pubs/default.aspx?id=231690.) As part of the generated operators, we need to generate "fixed" statements that pin pointers to some data. For this to be correct, the type of the pointer must **not** be a managed type. Thus, I really need to know if I can generate a fixed statement. Please let me know if you'd like more details.

**Comment by RichiCoder1** [comment]
Echoing here that there a few cases that this would be simple similar too, but far less sophisticated than, @mike-Barnett's needs

**Comment by CyrusNajmabadi** [comment]
This will need to go through an API review.  Haven't heard anything in 8 years, so closing out.
