### ISSUE TITLE
Support nested calls during an active argument completion session

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#50637]
Follow-up to #49916.

* Handle cases where argument completion applies to an outer call, but not to an inner call. For example, this would occur if the user starts an argument completion session, and then types `3.ToString()` for one of the arguments _without_ pressing <kbd>Tab</kbd>, <kbd>Tab</kbd>.
* Handle cases where argument completion session itself is nested. This is similar to above, but occurs if `3.ToString()` is inserted using Insert Full Method Call instead of just typing `()`.

Related to:

* https://github.com/dotnet/roslyn/pull/49916#discussion_r550697568

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
