### ISSUE TITLE
No type inference on var

### ISSUE THREAD

**Issue by mkrueger** [dotnet/roslyn#5064]
Forwarded from https://bugzilla.xamarin.com/show_bug.cgi?id=33743

```C#
using System;

enum E
{
    E1,
    E2
}

class A
{
    public E P { get; set; }
}

class X
{
    public static void Main()
    {
        A a = null;

        var g = a?.P & E.E2; // Hover over var it shows Nullable<T> instead of actual type
    }
}
```

**Comment by gafter** [comment]
Assigning to IDE for evaluation. Is this an IDE issue or a compiler API issue?

**Comment by mkrueger** [comment]
no it's no API issue - but that relies on the symbol information I get from 'var'. So it's a resolver issue.
The symbol info says Nullable<T> :). But y at the end it lands on IDE level and is user visible.

**Comment by Pilchie** [comment]
The IDE correctly says `Nullable<T>` with instantiation information at the bottom of the tooltip.  However, we could do a better job and simplify down to `E?`, which is what is shown if hover over `g`.

**Comment by mkrueger** [comment]
ok didn't read the tooltip fully :)
