### ISSUE TITLE
.editorconfig doesn't match files if {} pattern includes only single entry

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/editorconfig-doesnt-match-files-if--/1311456)._

---
[severity:It bothers me. A fix would be nice]
EditorConfig doesn't match files when only single element is provided for `{s1,s2,s3}` pattern without a comma. E.g.:
```
[*.csproj] # Works
[*. {csproj,}] # Works
[*.csproj] # Works
[*. {csproj}] # Doesn't work
```

.. leading to a profoundly confusing (even though looking back understandable) user experience. 

Apologies if this issue should go to Roslyn repo / to editorconfig repo but.

---

PS: EditorConfig in general is awesome! Thanks for it <3.

---
#### Jiri Hruska [MSFT] on 1/15/2021, 08:30 AM: 

<p>Hi Petr,</p>
<p>you can start here, that’s the 3rd-party component we use for matching those patterns:<br>
<a target='_blank' href="https://github.com/SLaks/Minimatch/blob/c3ad9090e54179c36f64bc6d89663ee939db576f/Minimatch/Minimatcher.cs#L384">https://github.com/SLaks/Minimatch/blob/c3ad9090e54179c36f64bc6d89663ee939db576f/Minimatch/Minimatcher.cs#L384</a></p>
<p>Based on that code, the decision to leave single terms in curly braces seems intentional.<br>
Presumably to allow inclusion of the literal characters, e.g. <code>&quot;*.{{a,b}}&quot;</code> → <code>[&quot;*.{a}&quot;, &quot;*.{b}&quot;]</code></p>
<p>This seems to be the case regardless of whether <code>Option.AllowWindowsPaths</code> is set or not.</p>

#### Feedback Bot on 1/17/2021, 05:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jaredpar** [comment]
@mavasani, @chsienki 

At a glance this looks like a bug but I'm unsure if there is a subtle reason why this wouldn't be allowed. Can you all clarify here?

**Comment by chsienki** [comment]
The spec https://editorconfig-specification.readthedocs.io/ is kind of vague on this point, it just says 

> any of the strings given (separated by commas, can be nested)

Which, _seems_ like it should probably support a single entry, but isn't clearly defined. I'll take a look at the parser and see what we're doing.

**Comment by chsienki** [comment]
Yeah in our internal grammar we claim to be able to match a single entry, so just looks like a straight bug in our parser implemenation: 

            // An editorconfig section name is a language for recognizing file paths
            // defined by the following grammar:
            //
            // <path> ::= <path-list>
            // <path-list> ::= <path-item> | <path-item> <path-list>
            // <path-item> ::= "*"  | "**" | "?" | <char> | <choice> | <range>
            // <char> ::= any unicode character
            // <choice> ::= "{" <choice-list> "}"
            // <choice-list> ::= <path-list> | <path-list> "," <choice-list>
            // <range> ::= "{" <integer> ".." <integer> "}"
            // <integer> ::= "-" <digit-list> | <digit-list>
            // <digit-list> ::= <digit> | <digit> <digit-list>
            // <digit> ::= 0-9

**Comment by Youssef1313** [comment]
The behavior you're describing doesn't reflect the actual behavior. The issue states that:

```ini
[*.csproj] # Works
[*. {csproj,}] # Works
[*.csproj] # Works
[*. {csproj}] # Doesn't work
```

However, the second one doesn't work, and this is expected because you have an extra space after the dot.

**Comment by yirkha** [comment]
@Youssef1313 The extra spaces are just some weird behavior of the vsfeedback bot which transplanted the report here to GitHub. It looks fine in the original submission at https://developercommunity2.visualstudio.com/t/editorconfig-doesnt-match-files-if--/1311456

On another note, is this really related to Roslyn at all? The .editorconfig, the internal grammar mentioned above, everything is used only by the analyzer afaics. But I think the original problem report was about what VS IDE does (@petrroll?). So maybe there is nothing to be done here (especially if the Roslyn implementation behaves as expected).

**Comment by Youssef1313** [comment]
> The extra spaces are just some weird behavior of the vsfeedback bot which transplanted the report here to GitHub. It looks fine in the original submission at https://developercommunity2.visualstudio.com/t/editorconfig-doesnt-match-files-if--/1311456

Oh I see. Then I can't reproduce the issue. All the following worked when I tried them:

```
[*.cs]
[*.{cs}]
[*.{cs,}]
```

Also note, the reported issue says `csproj`, which I'm not sure if it will work.
@petrroll  Do you a repro project?

**Comment by petrroll** [comment]
This was indeed about what VS IDE does. And nope, unfortunately, I no longer have repro. Vaguely remember it being very consistent ever for the most minimal repro (i.e. single file project).

**Comment by Jack-Edwards** [comment]
I was able to reproduce this issue today.  You can refer to this PR for the before/after: https://github.com/BetterCallSodium/BetterCallSodium/pull/1

Prior to the PR, my default VS setting of `indent_size = 3` was taking precedence over `indent_size = 4` set in the .editorconfig.

Creating a new `foo.cs` class in the `BetterCallSodium.Tests` project is sufficient see the issue in action.

**Comment by Youssef1313** [comment]
@Jack-Edwards It looks like your issue is a bit different. It happens only for projects that don't have source files yet. Once you add a file and try to add a second one, things work correctly.

Can you confirm if that's what you see and open a new issue? Thanks!

**Comment by Youssef1313** [comment]
@Jack-Edwards I opened a new issue #63334 to investigate.
