### ISSUE TITLE
[Loc] Assistance with translations

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/roslyn#50656]
. | .
-- | --
String Resource ID | 0; "in_0_1_2"
Source String | in {0} ({1} - {2})
Filename | Features\Core\Portable\xlf\FeaturesResources.xlf
Question | Please let us know what placeholders refer clearly.

**Comment by crsuzukimsft** [comment]
vcq 359655

**Comment by cristianosuzuki77** [comment]
@jinujoseph cordial ping.

**Comment by JoeRobich** [comment]
https://github.com/dotnet/roslyn/blob/db85868ec914996d706a7793a2b93c0cf7c4cd8c/src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.SearchResult.cs#L60

{0} is a type name ("MyClass")
{1} is a code file name ("Code.cs")
{2} is a project name ("MyProject")
