### ISSUE TITLE
Allow user-defined positional members to be fields

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#50667]
LDM decision: https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-10-05.md#changing-the-member-type-of-a-primary-constructor-parameter

Because this change affects back compat (see example below), we want to patch C# 9 while we can instead of waiting for C# 10.

```csharp
public record Base
{
    public int Field;
}
public record Derived(int Field) : Base;
```

**Comment by Youssef1313** [comment]
@jcouv Probably missing inheritance in your example? or is it something I'm misunderstanding?

**Comment by jcouv** [comment]
Haha, indeed ;-) Fixed the example

**Comment by jcouv** [comment]
I thought I'd repro'd this scenario in sharplab, but turns out this scenario is presently an error. So we can just address this as part of C# 10 work :-)

[sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAzAAgTgGMB7BFfAIWjgFgAoAb0fzfz3wEsA7GfAGJc4AGxQBuRgF9GnImQr4AIoi4A3OCgAUvfkNEoAlPhDVakhgHpL+RAnL4AwgGUAHK4BsH0wCUS5SjA4MGBEfAByGig4ADp9MXD8MABXWHxQ/AhCOAgUCGAROG4eWAgeYiKAB3tKxBgAT3xSADN8BtqI3USYUiSIGGIAC3xK0iguGC5SHggREYgECCD4BAj4lHCYoA)
```
public record Base
{
    public int Field;
}
public record Derived(int Field) : Base;
// error CS8866: Record member 'Base.Field' must be a readable instance property of type 'int' to match positional parameter 'Field'.
```

Tagging @AlekseyTs @cston FYI
