### ISSUE TITLE
Quick Watch trims expressions containing strings with //

### ISSUE THREAD

**Issue by Suchiman** [dotnet/roslyn#5067]
Open Quick Watch and enter an expression like
![2015-09-08_16-16-32](https://cloud.githubusercontent.com/assets/7110884/9737072/2ba69d4a-5645-11e5-842b-8ab4c6b0c01d.png)

Press enter
![2015-09-08_16-16-52](https://cloud.githubusercontent.com/assets/7110884/9737086/3cd06f6a-5645-11e5-9f59-07fd079f76d9.png)

The expression is correctly evaluated but then cut off starting with `//` inside the string.
It can be even simpler reproduced by just entering `"//"`, it will be trimmed to `"` then

**Comment by ManishJayaswal** [comment]
This probably has nothing to do with Roslyn. I will pass this over to debugger team. 
@Suchiman would you mind opening a connect issue on it at http://connect.microsoft.com/VisualStudio

**Comment by ManishJayaswal** [comment]
Create an internal bug on debugger. @Suchiman please still file the connect issue so that you can track this. Internal bug number is 144991.

**Comment by sharwell** [comment]
Debugger team responded that this is likely a bug in the result provider.

**Comment by Suchiman** [comment]
Reproduces in 15.9.21 but does no longer reproduce as of 16.6p1
