### ISSUE TITLE
Get current solution as variable, without giving its solution path

### ISSUE THREAD

**Issue by tilenzalar** [dotnet/roslyn#50687]
As title says it would be great to get current solution as variable without giving its path.
The code used now with given path:
`var workspace=MSBuildWorkspace.Create();
var solution = workspace.OpenSolutionAsync(currentSolutionPath).Result;
...`
So the goal is to omit the need of currentSolutionPath

**Comment by CyrusNajmabadi** [comment]
It's unclear to me how that would work.  What would teh MSBuildWorkspace be opening then?
