### ISSUE TITLE
Badly formatted label in "Preview Changes" dialog UI

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#50681]
Attempting to suppress a diagnostic across the project I saw this:

![image](https://user-images.githubusercontent.com/350947/105443711-7d43be80-5cc0-11eb-9f80-87a3e2c6f922.png)

- There should at least be a space between "File" and "CA2201"
- The first character should be capitalised
- It is a confusing label. It reads like it's suppressing something in a file called CA2201. Perhaps it should read:
   > Fix all occurrences of CA2201 in suppression file(s)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in preview changes.
