### ISSUE TITLE
IDE0083 looks only for declaration patterns

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50690]
https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpUseNotPatternDiagnosticAnalyzer.cs#L64-L77

The above implementation will produce a diagnostic for `!(x is Y y) ` but not for `!(x is Y)`. Both can use `is not` and should have diagnostic.

**Comment by reacheight** [comment]
Seems like this analyzer and corresponding code fix should also handle binary is-expressions with types (`!(x is string)`) and constants (`!(x is null)`). If that's ok I'd like to work on this.
