### ISSUE TITLE
Completion doesn't include locals declared in previous submission

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5069]
Try typing the code below and notice that the completion list that pops up when the highlighted text below is typed does not contain the variable “number” which was declared in the previous line.
```
> int number = 10;
> int n1 = num          
```

Was internal issue 531487

**Comment by amcasey** [comment]
Locals from the current submission are also not offered (i.e. hit shift-enter between the two statements above).

**Comment by amcasey** [comment]
Confirmed that it works for locals and fields within (user-defined) classes.

**Comment by amcasey** [comment]
Confirmed that types from previous submissions *are* offered.

**Comment by amcasey** [comment]
Guess: ```number``` and ```n1``` are both instances fields so completion is hiding ```number```.

**Comment by amcasey** [comment]
It's returned by ```SemanticModel.LookupSymbols```, so my hypothesis is looking good.

**Comment by amcasey** [comment]
It's not returned by ```SemanticModel.LookupSymbols```.

**Comment by amcasey** [comment]
The ```CSharpRecommendationService``` is calling ```LookupStaticMember```, which excludes instance fields.

**Comment by amcasey** [comment]
```SyntaxNodeExtensions.IsInStaticContext``` returns true for all field declarations.  It needs to make an exception for top-level field declarations.

**Comment by amcasey** [comment]
@KevinH-MS can you please verify?

**Comment by KevinH-MS** [comment]
Looks good
