### ISSUE TITLE
VS crashes if you switch a target framework in .csproj

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#50691]
**Version Used**: 
```
Microsoft Visual Studio Professional 2019 Preview
Version 16.9.0 Preview 3.0
VisualStudio.16.Preview/16.9.0-pre.3.0+30914.41
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:

1. Open the attached project in VS 16.9.0 Preview 3 
2. Uncomment `<TargetFramework>net472</TargetFramework>` line and comment out `<TargetFramework>netcoreapp3.1</TargetFramework>`
3. Save the changes (for some reason the crash didn't happen on my machine until I saved this)
4. Switch the commented target framework lines a couple of times (you can use ctrl+z / ctrl+y for that) since the crash doesn't happen always but it seems close to ~30% on my machine i.e. switching it just a couple of times usually crash VS

**Expected Behavior**:
VS doesn't crash

**Actual Behavior**:
VS freezes and stops responding

![vsfreezecrash](https://user-images.githubusercontent.com/5566206/105491515-71a7c600-5cc7-11eb-837c-3df0d502ce36.gif)

**Notes**
The release version of VS didn't crash when I tried to reproduce the behavior there, however it reported an exception. Not sure if it's related though
```
  <entry>
    <record>1237</record>
    <time>2021/01/22 12:29:29.458</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified SnapshotPoint is on a different ITextSnapshot than this SnapshotPoint.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotPoint.CompareTo(SnapshotPoint other)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.CaretAdornmentLayer.RedrawCarets()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.CaretAdornmentLayer.OnLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
  <entry>
    <record>1238</record>
    <time>2021/01/22 12:29:29.509</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The specified SnapshotPoint is on a different ITextSnapshot than this SnapshotPoint.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotPoint.CompareTo(SnapshotPoint other)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.CaretAdornmentLayer.RedrawCarets()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.UI.CaretAdornmentLayer.OnLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

[ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/5855675/ConsoleApp1.zip)

**Comment by sharwell** [comment]
To review this performance feedback, we would need it submitted through the Report a Problem tool in Visual Studio. Here is the reply I give for requesting this performance information:

> Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.
>
> Based on the information provided so far, the most likely scenario to follow is for "Slowness and High CPU Issues". Please look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#slowness-and-high-cpu-issues
