### ISSUE TITLE
Missing NuGet depedency "Microsoft.Composition"

### ISSUE THREAD

**Issue by dfkeenan** [dotnet/roslyn#507]
Hi,

It seems some of the assemblies have a dependency on the nuget package "Microsoft.Composition" but it is not listed as a dependency and you have to install it yourself.

Cheers.
dfkeenan

**Comment by Pilchie** [comment]
What build are you using?  I thought I fixed this, but maybe it’s not in a public set of nuget packages yet?

**Comment by dfkeenan** [comment]
i just installed package Microsoft.CodeAnalysis 1.0.0.0-beta2 from NuGet.Org.  According to NuGet manager it's the latest version.

**Comment by Pilchie** [comment]
Just followed up that the change didn't make the last public build, but should be in the next one.  (also, @balajikris fixed it, not me).

**Comment by Pilchie** [comment]
To bump this, the dependency should be there in the "rc1" packages that work with VS 2015 CTP 6.
