### ISSUE TITLE
Avoid converting line to string in TextLineExtension helpers

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#50706]
The following helpers operate on TextLine by converting it to string first:
- `GetFirstNonWhitespaceOffset`
- `GetFirstNonWhitespacePosition`
- `GetLeadingWhitespace`

The following `StringExtensions` are also called on line converted to a string in some call sites:
- `GetFirstNonWhitespaceOffset`
- `GetLastNonWhitespaceOffset`
- `GetLeadingWhitespace`

These can all avoid the string allocation indexing into the underlying `SourceText` directly.

Also, `GetFirst*` methods should follow `IndexOf` pattern (be renamed to `IndexOfXxx` and return -1 instead of returning `int?`.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
