### ISSUE TITLE
False CS8603: Possible null reference return in switch expression when earlier pattern checks for null

### ISSUE THREAD

**Issue by richardcox13** [dotnet/roslyn#50729]
```
dotnet --version
5.0.200-preview.20614.14
```

**Steps to Reproduce**:

NullableCheck.csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

Program.cs:
```
using static System.Console;

class Program {
    static void Main(string[] args) {
        WriteLine("null => " + Format(null));
        WriteLine("\"one\" => " + Format("one"));
    }

    static string Format(object? obj)
        => obj switch {
            null => "null",
            _ => obj.ToString()
        };
}
```

**Expected Behavior**:

No warnings.

**Actual Behavior**:

E:\Projects\_Tests\NullableCheck\Program.cs(10,12): warning CS8603: Possible null reference return. [E:\Projects\_Tests\NullableCheck\NullableCheck.csproj]

**Notes**

The first branch of the switch expression (line 11 of Program.cs) has already handled the null case, so on line 12 `obj` cannot be null. 

It is perhaps significate that a non-null assertion – changing line 12 to `_ => obj!.ToString()` – leaves the warning in place.

**Comment by richardcox13** [comment]
Note also seen when `global.json` sets the SDK version to 5.0.100.

(Didn't get the working in 3.1.)

**Comment by PathogenDavid** [comment]
> It is perhaps significate that a non-null assertion – changing line 12 to `_ => obj!.ToString()` – leaves the warning in place.

Oddly enough null-forgiving the whole expression leaves the warning too. ([SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwGIA7AV11wENhcYACGY62gWACgABABjo4EYkvPgDoAwhGIBnCLQDc7dhwBMQgOx0A3uzo6hgjijoBZStmIAKflwDaAXTqUoAc0kBKTdt1eA6lGwYYABkzGHMAIjIKOgBeAD46MLoAajoAMWgAW0oMc0jcV1d5Ni8fPwDg4lCwgB0wiRhamPjElPSoLJy6yrCCoq8AXwVi3X59Ph42jvMIYAArGDAMAH46GdnXTxKmumm5ukkAd38wAAsPYa2vPO2I8lwwtE3LnQB9bbXhABUIAGUMP2ITnMGwuJX6rgAhEV+kA===))

```csharp
#nullable enable
using static System.Console;

class Program {
    static void Main(string[] args) {
        WriteLine("null => " + Format(null));
        WriteLine("\"one\" => " + Format("one"));
    }

    static string Format(object? obj)
        => (obj switch {
            null => "null",
            _ => obj.ToString()
        })!;
}
```

**Comment by Youssef1313** [comment]
The warning is correct. `ToString` return is annotated as nullable. See https://github.com/dotnet/runtime/issues/1318

However, it feels really odd that the suppression in @PathogenDavid comment keeps the warning.

**Comment by richardcox13** [comment]
I – concurrently worked that out – but that was hard because the warning was marking the whole switch expression (that needs a separate issue when I have time).

Closing.
