### ISSUE TITLE
Auto-format inserts space between tuple type and pointer star

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#50723]
**Version Used**:

Compiler version: '3.8.0-5.20604.10 (9ed4b774)'. Language version: 9.0.

Visual Studio 16.8.4

Also reproduced with Compiler version: '3.9.0-3.21056.4 (e5eb71d6)'. Language version: 9.0. 

Visual Studio 16.9.0 Preview 32.

**Steps to Reproduce**:

1. Given the following:

```csharp
public unsafe static class Program
{
    public static void Main(string[] args)
    {
        int* intPointer = null;
        (int, int)* intIntPointer = null;
    }
}
```

2. Invoke automatic code formatting (IE: Using Code Cleanup, Edit -> Advanced -> Format Document, retyping the semicolon, etc.)

**Expected Behavior**:

Nothing changes as the code is well-formed. 

**Actual Behavior**:

A space is inserted between the tuple type and the pointer `*`:

```csharp
public unsafe static class Program
{
    public static void Main(string[] args)
    {
        int* intPointer = null;
        (int, int) * intIntPointer = null;
        //        ^_______________This space was added
    }
}
```

------------

I've reproduced this with a completely vanilla Visual Studio environment (Default settings, no extensions, no EditorConfig), so I don't think it's a weird setting I accidentally configured somewhere. [Here's my .editorconfig though](https://github.com/InfectedLibraries/Biohazrd/blob/c55d7c5748be0152d4d91cd17d9b62640c5d4058/.editorconfig) if it's needed.

**Comment by Youssef1313** [comment]
I'll work on this.

**Comment by PathogenDavid** [comment]
Thanks for getting that fixed and merged, @Youssef1313 and @CyrusNajmabadi!
