### ISSUE TITLE
Add IsPartial to IMethodSymbol

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#50736]
Currently `IMethodSymbol` has `PartialDefinitionPart` and `PartialImplementationPart` properties, but there's no way I can find that allows checking if the method is partial (aside from checking the syntax tree). There's an internal `SymbolExtensions.IsPartialMethod` method.

This is useful for generators, where we want to implicitly implement all the partial methods of a class.

**Comment by RikkiGibson** [comment]
I believe that if either PartialDefinitionPart or PartialImplementationPart are non-null you can assume the method is partial.

Somewhat related to #47727

**Comment by aelij** [comment]
@RikkiGibson that only works if the partial method has an implementation. And in my scenario - it hasn't been generated yet.

```cs
var t = SyntaxFactory.ParseSyntaxTree("partial class C { partial void M(); }");
var c = CSharpCompilation.Create("x", new[] { t });
var m = c.GetTypeByMetadataName("C").GetMembers()[0] as IMethodSymbol;
m.PartialDefinitionPart == null || m.PartialImplementationPart == null // false
```

**Comment by RikkiGibson** [comment]
Oops, you're right, in practice it is necessary for source generators to go to syntax currently if the goal is to detect a partial method with no implementation part.

**Comment by aelij** [comment]
Can I submit a PR to add this property? It already exists, it's just a matter of making it public.

https://github.com/dotnet/roslyn/blob/0a39566fae0541423aa4c7ad3e0cae584f5dcd5c/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs#L501

https://github.com/dotnet/roslyn/blob/0a39566fae0541423aa4c7ad3e0cae584f5dcd5c/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMethodSymbol.vb#L693

**Comment by CyrusNajmabadi** [comment]
I believe it's intentional to not expose this. It's a syntactic only concept. There is no difference at the symbolic level. 

Going to source should be extremely easy here. It's that not viable?

**Comment by aelij** [comment]
If it's syntactic only, then why do we have `PartialDefinitionPart` and `PartialImplementationPart` in the semantic model? As each part is represented by a separate symbol, the API seems incomplete IMO.

Regarding going to the syntax node - I was a bit concerned with perf. This seems more costly than checking a flag on the symbol:

```cs
public static bool IsPartial(this IMethodSymbol methodSymbol) =>
      methodSymbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is MethodDeclarationSyntax methodDeclarationSyntax &&
      methodDeclarationSyntax.Modifiers.Any(s => s.IsKind(SyntaxKind.PartialKeyword));
```

**Comment by CyrusNajmabadi** [comment]
> then why do we have PartialDefinitionPart and PartialImplementationPart in the semantic model

Because that is the symbolic side of them.  There are two distinct symbols here, and there is a relation between them.

The part about if the syntax actually has the IsPartial modifier is just a syntactic check.

**Comment by CyrusNajmabadi** [comment]
> ```methodDeclarationSyntax.Modifiers.Any(s => s.IsKind(SyntaxKind.PartialKeyword));```

Can just do:

```methodDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);```

**Comment by CyrusNajmabadi** [comment]
> This seems more costly than checking a flag on the symbol:

It probably would be.  Whether that matters in practice remains to be seen :)

**Comment by jaredpar** [comment]
Closing as @CyrusNajmabadi is correct that this is a syntactic concept and this is why it's missing from the symbol API.

**Comment by ltcmelo** [comment]
Hi @CyrusNajmabadi  and @jaredpar could we re-open this issue but with a slightly different suggestion?

I understand your explanation for not having an "is partial" API for `IMethodSymbol`, as `partial` is a syntactic matter. Yet:

- an API to check whether a method originated from a declaration that is `partial` still is worth to have it (at least, from the standpoint of source-based static analysis tools); in fact, I do have an extension method to provide this info, but an official API would avoid people reimplementing the functionality.

- there are already existing API within the symbols API which refer to syntactic concepts… perhaps the best example is `DeclaringSyntaxReferences`. 

My suggestion would be something like `IMethodSymbol.HasPartialDeclaration`.

**Comment by aelij** [comment]
@ltcmelo [IMethodSymbol.IsPartialDefinition](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.imethodsymbol.ispartialdefinition?view=roslyn-dotnet-4.0.1#Microsoft_CodeAnalysis_IMethodSymbol_IsPartialDefinition) was added in v4.
