### ISSUE TITLE
Changes preview pane for IntelliCode should have a horizontal scroll bar for long lines

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50739]
The preview pane for code fix providers have a horizontal scroll bar for long lines, but IntelliCode changes doesn't.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph need to port this to wherever intellicode bugs go. 

@Youssef1313 can you provide a screenshot?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I'm trying to make repeated changes in long lines to get IntelliCode suggesting anything, but it doesn't :(
I forgot to keep a screenshot from this behavior when it occurred. But I hope reviewing the UI elements by the appropriate team be easy enough. Meanwhile, I'll post a screenshot whenever I encounter IntelliCode suggestion in a long line.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Here it is

![image](https://user-images.githubusercontent.com/31348972/105642933-6904ea80-5e95-11eb-948d-657c55f1709d.png)

**Comment by jinujoseph** [comment]
Thanks @Youssef1313 moved the issue to Intellicode team (tracked [internally](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1269385 ))
