### ISSUE TITLE
Parse-Error: new-line in string interpolation expressions

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#50742]
**Version Used**: 16.9.0 Preview 3

**Sample Code**:

[Link](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWACgiBnOFAYzgAIAFAewEtU4iBvI6r6zAZmuY0AGgG5O3PgJbUAmmMLdq4rpPoA3AKaJEjACYaeuAAzUAKvQDK5ZgHMAFAEpqAXgB81ACQAiO2yEBfGGo2GX8HL3l/IiJJHGoAQQAHRPZohQlsbGVg7MVMXABOO294uiYWEGDUDQB3MsE2JXTFFu4hF2pcINzW7hkO7Cbe6n9/Lwd5RSjCfyA=)
```CSharp
using System;

struct Point
{
    public int X;
    public int Y;
    
    public override string ToString() => $"({X}, {Y})";
}

public class App
{

    public static void Main()
    {
        Console.WriteLine($"A Point: {new Point{ 
              X = 1, 
              Y = 2 
        }}");
    }
}
```

**Expected Behavior**:
According to [csharplang ](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/spec/expressions.md#interpolated-strings) every expression is allowed in an interpolation. So expressions with New-Line trivia should compile.

**Actual Behavior**:
Code does not compile, just with removing the new lines.

**Comment by CyrusNajmabadi** [comment]
You need to use `$@""`

Normal `$""` strings do not allow newlines in them.

**Comment by bernd5** [comment]
The new line does not appear in the string itself! It is inside a regular expression.

**Comment by CyrusNajmabadi** [comment]
> The new line does not appear in the string itself! It is inside a normal expression.

Yes. I understand that :-)

This is how we designed the language to work. The string literal start/end is discovered first, then internally parsed. Fur these strings, the end can't be found as they are supposed to be in a single line, but a new line is encountered before the end is reached. 

> @ would dissallow escaping / change escaping rules.

Yes. That is true. 

> Of course we could use verbatim interpolated strings here, string.operator+, local variables or simply string.Format.

Yes.

**Comment by bernd5** [comment]
Is it defined in the spec that expressions with newline trivia are dissallowed here?

A resulting bug is a call to `aSyntaxTree.NormalizeWhitespace()` with long interpolation expressions becomes invalid just because 
this function produces nice formatted code which is unfortunately not valid anymore. NormalizeWhitespace inserts new lines here.
I would say NormalizeWhitespace() is not buggy here, it is the interpolated string parsing!

What's about comments, those are "real trivia" - but a multiline comment would break an interpolated strings, too.

**Comment by CyrusNajmabadi** [comment]
> NormalizeWhitespace inserts new lines here.

That is a bug.

**Comment by CyrusNajmabadi** [comment]
Please see the conversation in https://github.com/dotnet/csharplang/discussions/1409 for a better understanding of what's going on here.

**Comment by bernd5** [comment]
I understand the problem with the colon handling. But I think the issue with new lines is easy.

Coudn't we change the call at: [Lexer-Source](https://github.com/dotnet/roslyn/blob/aee3b3b065b1fad99681e012000873f3c4992c2a/src/Compilers/CSharp/Portable/Parser/Lexer_StringLiteral.cs#L532)

To `IsAtEnd(true)`.

New lines are allowed in those "holes".

**Comment by bernd5** [comment]
New lines in verbatim-string-expressions in suche "holes" are already working [see](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQZuhAnABQAkARACpywAEA3mzbro2YXwMAlAF8RAbiA=):

```
using System;

Console.WriteLine($"Test { (@$"
12")}");
```

**Comment by bernd5** [comment]
I fixed the code but it is still over-complicated and bug-prone.

One example.
The old implementation allowed:
```
using System;

Console.WriteLine($"Test { **@$**"
12"}");
```

But it rejected:
```
using System;

Console.WriteLine($"Test { **$@**"
12"}");
```

**Comment by CyrusNajmabadi** [comment]
>New lines in nested-interpolated-verbatim-string-expressions in suche "holes" are already working

yes.  this is as expected.

**Comment by bernd5** [comment]
Implemented via https://github.com/dotnet/roslyn/pull/56853
