### ISSUE TITLE
In 16.9, the new VB and C# feature of starting a new line with comments marker is broken.  

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/roslyn#50756]
**16.9 Preview 3**: 

**Steps to Reproduce**:

1. Create any C#/VB .NET Console application in 16.9
2. Type "//" if it is C# , " ' " if it is VB and add some comment and press enter.

**Expected Behavior**:
The New Line should start with the comment marker as per the new feature introduced in 16.9. 
**Actual Behavior**:
New Line doesn't start with the comment notation.

**Comment by Youssef1313** [comment]
I think the feature was implemented to continue comment in next line only if you press enter in the middle of a comment, not the end of it.

Tagging @CyrusNajmabadi who implemented this feature to confirm.

**Comment by CyrusNajmabadi** [comment]
> I think the feature was implemented to continue comment in next line only if you press enter in the middle of a comment, not the end of it.

Yes.  That's the intention of the feature.  The goals were:
1.  to not interfere with people who have completed their comment and want to code on the next line
2. to ensure that typing <enter> in teh middle of a comment doesn't have broken behavior like today

**Comment by sharwell** [comment]
I'm going to resolve _this_ issue as By Design. With that in mind, if someone has a proposal for a new behavior that still addresses the concerns from https://github.com/dotnet/roslyn/issues/50756#issuecomment-767086288 please feel free to create a new issue with that request.
