### ISSUE TITLE
Issue with Expression.Call in Roslyn

### ISSUE THREAD

**Issue by mikekberg** [dotnet/roslyn#5075]
The following code will compile and run in Visual Studio 2013 but throws an exception in Visual Studio 2015. It looks to be an issue with the IL Roslyn is spitting out

```
    class MyClass
    {

        public static Dictionary<string, Func<string, string, string>> FuncMap;

        static MyClass()
        {
            FuncMap = new Dictionary<string, Func<string, string, string>>();

            FuncMap.Add("testing", (x,y) => x + " " + y);
        }

        public string Foo()
        {
            MethodInfo func = FuncMap["testing"].Method;

            var t = Expression.Lambda<Func<string>>(Expression.Call(func, new Expression[]
            {
                Expression.Constant("testing"),
                Expression.Constant("testing 2")
            })).Compile();

            return t();
        }
    }

    class Program
    {

        static void Main(string[] args)
        {
            var inst = new MyClass();

            Console.WriteLine(inst.Foo());
        }
    }
```

**Comment by tmat** [comment]
Your code is incorrect. It needs to check if the delegate represents an instance method and if so pass in Delegate.Target as the receiver.

Consider testing it with following code (in VS 2013):
```C#
string space = " ";
FuncMap.Add("testing", (x, y) => x + space + y);
```

**Comment by gafter** [comment]
What @tmat said. The language spec does not promise a lambda will ever be a static method, and your code appears to assume it is. That has changed since the previous version of the compiler.

See https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CodeGen%20Differences.md for some details.

**Comment by tmat** [comment]
I'd also suggest using ```Expression.Invoke``` instead of ```Expression.Call```. The former accepts an expression whose value is a delegate and handles all the different kinds of delegates for you.

**Comment by mycall** [comment]
Is there a way to force a lambda to be static, some compiler setting?

**Comment by gafter** [comment]
@mycall No, we do not have options for fine-tuning the IL produced by the compiler.
