### ISSUE TITLE
Proposal: Comment continuation in next line

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50757]
Related to: https://github.com/dotnet/roslyn/issues/50756#issuecomment-767090567

The proposal builds on top of https://github.com/dotnet/roslyn/issues/15406

Simply said, when `max_line_length` option for `.editorconfig` is implemented, the IDE could move to the next line automatically (without explicitly formatting the document or pressing enter) when a space is encountered and the current length exceeds `max_line_length`.

@sharwell @CyrusNajmabadi for thoughts.

**Comment by CyrusNajmabadi** [comment]
I think teh 'rewrap' extension has covered this space *very* well.  I would not want to reimplement what is already covered very effectively by a rich and well supported extension.

**Comment by Youssef1313** [comment]
I didn't knew about this extension, and maybe there are many who don't know/use the extension who can see this useful to be supported built-in with Visual Studio.

**Comment by CyrusNajmabadi** [comment]
I view this in a similar way to spellchecking.  There is so much effort and skill invested in tehse extensions, we'd basically be spending ages trying to just replicate all the incredibly variety of cases they already handle with skill.

I think extension knowledge and searching is appropriate.  Roslyn should not be the one stop shop for every bit of functionality out there.  When there is a really good 3rd party solution, it should be embraced.  Note: vscode have pushed this model extremely successfully.

**Comment by Youssef1313** [comment]
Sounds reasonable.
