### ISSUE TITLE
IDE0060 shows a warning for MSTest v2 extension methods that do not use the "this" parameter

### ISSUE THREAD

**Issue by airbreather** [dotnet/roslyn#50761]
#36085 was closed as "by-design", which I agree with in the general case.

That said, I propose making targeted exceptions to IDE0060 for extension methods where the first parameter is one of the following types, as there is documentation that guides users to making extension methods on these types that will very likely not use the first parameter:
1. `Microsoft.VisualStudio.TestTools.UnitTesting.Assert`
    - Documentation for `Assert.That` explicitly recommends doing things this way:
    - https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.that?view=mstest-net-1.3.2
1. `Microsoft.VisualStudio.TestTools.UnitTesting.CollectionAssert`
    - Documentation for `CollectionAssert.That` explicitly recommends doing things this way:
    - https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.collectionassert.that?view=mstest-net-1.3.2
1. `Microsoft.VisualStudio.TestTools.UnitTesting.StringAssert`
    - Documentation for `StringAssert.That` explicitly recommends doing things this way:
    - https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.stringassert.that?view=mstest-net-1.3.2

**Comment by CyrusNajmabadi** [comment]
Why not create Diagnostic suppressor for these apis since they are behaving strangely?

**Comment by airbreather** [comment]
> Diagnostic suppressor for these apis

This is the first I've heard about this concept.  Is the idea that the MSTestv2 team would be able to write something on their own so that consumers of their packages on NuGet don't have to manually suppress IDE0060 on their own, without having to special-case such APIs in the actual IDE0060 analyzer itself?

If that's the case, then that sounds perfect.  Could this issue be transferred to https://github.com/microsoft/testfx as-is, or should I just open a copy in there?

**Comment by sharwell** [comment]
@airbreather Yes, that's correct. The MSTest project would provide a `DiagnosticSuppressor` analyzer that knows to suppress IDE0060 in contexts where it does not make sense for users of their APIs.
