### ISSUE TITLE
Add "IsManaged" API on C# types if there is enough demand.

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#5077]
Language has concept of managed type - roughly types that might be reference types themselves or may contain references. 
The most common use of this info is that the language does not allow pointers like T* if T happens to be a managed type.

Compiler knows internally whether any given type is considered "managed" or not since it needs this information for error checking. The question is whether there is enough potential value for this to be a public property.

**Comment by agocke** [comment]
There was already an issue for this: https://github.com/dotnet/roslyn/issues/5063

**Comment by VSadov** [comment]
dupe of #5063
