### ISSUE TITLE
Intellisense does not suggest record keyword when creating a record nested in another

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#50783]
**Version Used**: Visual Studio 16.8.4 Compiler version: '3.8.0-5.20604.10 (9ed4b774)'. Language version: 9.0.

Also: Visual Studio 16.9.0 Preview 3.0 Compiler version: '3.9.0-3.21056.4 (e5eb71d6)'. Language version: 9.0.

**Steps to Reproduce**:

Given the following code, invoke Intellisense at the location of `$$`:

```csharp
record ParentClass
{
    public record$$
}
```

**Expected Behavior**: The `record` keyword is suggested

**Actual Behavior**: The `record` keyword is not suggested

Attempting to type a space causes `DbDataRecord` to be automatically accepted, which is undesirable.

![image](https://user-images.githubusercontent.com/278957/105850218-1287d100-5fa7-11eb-88f8-23c842a83689.png)

-------------

This seems to only happen when the containing type is a record, it works as expected when the containing type is a class:

![image](https://user-images.githubusercontent.com/278957/105850278-259aa100-5fa7-11eb-8b3b-27730e7cb694.png)

**Comment by Youssef1313** [comment]
It could be because:

https://github.com/dotnet/roslyn/blob/59158723a40c441f878902579ef28a4eb3273373/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs#L663-L669
