### ISSUE TITLE
Add automatically the public keyword when new class is created.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50797]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-automatically-the-public-keyword-whe/1318547)._

---
When creating new Class , I think it's better to add the public keyword, generally this keyword will not be erased.

---
#### Feedback Bot on 1/25/2021, 00:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
There has been some feedback in the past asking for an option to configure this behavior. Not sure how we would do it without it being overwhelming.

**Comment by sharwell** [comment]
We would automatically add the `internal` keyword here as part of adhering to code style on documentation creation.

**Comment by sharwell** [comment]
Marking **help wanted** to include access modifiers code fix as part of the document creation cleanup process. See https://github.com/dotnet/roslyn/pull/46744 for an example of how some other rules were added to this process recently.
