### ISSUE TITLE
Consider if it is appropriate to use Enumerable.Repeat to implement DefaultLowerBounds function in src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#5080]
In code review for PR #5060 @gafter asked if we should use ```Enumerable.Repeat``` to implement DefaultLowerBounds, which is currently implemented as follows:
```
private static IEnumerable<int> DefaultLowerBounds(int rank)
{
    for (int i = 0; i < rank; ++i)
        yield return 0;
}
```

**Comment by leppie** [comment]
Is this issue more about removing (generated) iterators in favour of LINQ to reduce code size? (Specifically when closure classes are not generated?)

**Comment by AlekseyTs** [comment]
I think @gafter 's motivation is a code simplification, but I could be wrong.

**Comment by leppie** [comment]
It would have been nice if `Sizes.Cast<ulong>()` would work instead of `GetSizes`, but it fails...
