### ISSUE TITLE
Why not remove delegate BeginInvoke method, since it is not platform supported on .NET 5?

### ISSUE THREAD

**Issue by zhyy2008z** [dotnet/roslyn#50826]
Why reserve the delegate BeginInvoke method? Is anyone can help?

Related issues:
[https://github.com/dotnet/runtime/issues/47510](https://github.com/dotnet/runtime/issues/47510)
[https://github.com/dotnet/runtime/issues/16312](https://github.com/dotnet/runtime/issues/16312)

**Comment by ygra** [comment]
Roslyn _can_ be used to compile programs for .NET Framework, right?

**Comment by zhyy2008z** [comment]
Can it be judged based on the target?

**Comment by huoyaoyuan** [comment]
Roslyn doesn't change its behavior based on the target. It only fails if the target doesn't contains required special types.

**Comment by jnm2** [comment]
@huoyaoyuan It does fail based on target framework when you use DIMs.

**Comment by huoyaoyuan** [comment]
@jnm2 It fails because it can't find the special member of DIM feature. It doesn't have more knowledge to the framework.

**Comment by jnm2** [comment]
What member is that?
Also, the same style of metadata detection could work for this proposal.

**Comment by huoyaoyuan** [comment]
`System.Runtime.CompilerServices.CovariantReturnsOfClasses`, the constant

**Comment by huoyaoyuan** [comment]
While, it does change behavior for attribute specified, for example `SkipLocalsInitAttribute`. There can be an attribute to adjust delegate compilation.

**Comment by zhyy2008z** [comment]
Manually specified or can be specified by  target?

**Comment by huoyaoyuan** [comment]
Generally, the team won't doing removal automatically to avoid breaking people without knowledge.

**Comment by zhyy2008z** [comment]
Obsolete first, then remove it after years.
