### ISSUE TITLE
How to retrieve the binder for a BoundCall in a local rewriter ?

### ISSUE THREAD

**Issue by RobertvanderHulst** [dotnet/roslyn#50823]
I have a question regarding recent changes in the Roslyn code:
In the past when you were inside a LocalRewriter and you were inspecting a BoundCall node, there was an property BinderOpt which returned the binder for that Call.
I need to collect the list of locals that are "visible" when the call is made. In the past I could walk upward using Binder.Next until I arrived at the InMethodBinder from which I could take the Locals and Parameters and then have a complete list of all the locals visible when the Call is made.
In the current (release/dev16.10) build there is no BinderOpt property anymore.
I tried to use _compilation.GetBinder() and passed it the syntax node for the BoundCall but that does not return the blockbinder for the call but it returns the InMethodBinder for the method where this call is defined.
I tried to add the BinderOpt property myself, but since the BoundCall objects are often updated I also had to change the generated code for Update() to copy the BinderOpt property to the new call object. That is not ideal...
What is the recommended way to retrieve the BlockBinder where a BoundCall is made inside the LocalRewriter?

**Comment by Youssef1313** [comment]
Could be related to https://github.com/dotnet/roslyn/pull/50105
cc: @333fred

**Comment by 333fred** [comment]
@RobertvanderHulst what are you actually trying to do? Binders are internal implementation details of roslyn, they're not available for public consumption. The binders we had on various BoundNodes were for, lack of better phrasing, a shortcut we took to enable IOperation. We've since refactored to remove that shortcut.

Note: I'm going to close this as it's not an issue. Feel free to keep responding. Or, feel free to log on to the C# community discord at https://discord.gg/csharp, and come talk to us in the roslyn channel. It might be easier to have this type of discussion on a real-time chat platform, rather than in an issue.

**Comment by RobertvanderHulst** [comment]
@333fred We have created a new compiler (X#) based on the Roslyn sourcecode. See https://github.com/X-Sharp/XSharpDev for our repo. 
For one particular part of the language we need to "expose" local variables from the current context to a runtime function. To do that we are looping through the local variables and we are generating a method call in the runtime that registers the local name and its value in a table in the runtime. I know that this is VERY ugly but to support FoxPro we have to do this....
We detect that this is needed when the function is marked with a special attribute.
We could probably also do this in the Binder. But in the local rewrite there is a factory available that helps to create local symbols etc.
The code that does this is in https://github.com/X-Sharp/XSharpDev/blob/master/XSharp/src/Compiler/XSharpCodeAnalysis/LocalRewriter/LocalRewriter_Call.cs in the method  XsAdjustBoundCall().
For now I have added the BinderOpt field to the BoundCall object again and I am saving the binder in our version of the BindInvocationExpression().
I am not asking you to put the BinderOpt back into BoundCall, but what the best way is to get the local variables that are available in a certain context.

**Comment by 333fred** [comment]
I would suggest that you probably want to add a field to `BoundCall` that contains all the locals and populate that during initial binding. Either that, or keep track of the available locals through the local rewriter. You might be able to do that by, whenever you enter a `BoundBlock` or anything else that contains a local, recording that, like we do in the IOperation factories.

**Comment by RobertvanderHulst** [comment]
@333fred Thanks for the suggestion. I'll add a property to the SyntaxNode. We have our own version of this node anyway. And then I can indeed collect the symbols in the binder and rewrite the call in the localrewriter. I'll have a look at the IOperation factories.
