### ISSUE TITLE
Navigation cannot be cancelled when more than one definition is present

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#50834]
**Version Used**: 352639e2

**Steps to Reproduce**:

Attempt to navigate to a partial symbol with multiple parts while the solution is loading.

**Expected Behavior**:

Navigation can be cancelled.

**Actual Behavior**:

Navigation cannot be cancelled during this region of the operation:

https://github.com/dotnet/roslyn/blob/58b8b424051527599277accddba7b324eb89a61d/src/EditorFeatures/Core/Host/IStreamingFindReferencesPresenter.cs#L102-L118

⚠️ Cancelling on each pass of the loop is not sufficient here. The cancellation token must be available in the implementation of `OnDefinitionFoundAsync`, which appears to mean it needs to be tied to the cancellation token in `context`.

**Comment by CyrusNajmabadi** [comment]
@sharwell based on the dump, we're hanging here:

```
                using (Logger.LogBlock(FunctionId, KeyValueLogMessage.Create(LogType.UserAction), userCancellationToken))
                {
                    messageToShow = _threadingContext.JoinableTaskFactory.Run(() =>
                        NavigateToOrPresentResultsAsync(document, caretPosition, service, userCancellationToken));
                }
```

No other threads are doing anything of interest.  Do you know what can cause JTF.Run to just hang?
