### ISSUE TITLE
Suggestion: Allow renaming classes/methods from the Solution Explorer.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5084]
_(Based on feedback from internal customer bug 101348)_

Given that the Solution Explorer can be used to navigate through syntactic elements like classes and methods, invoking rename from here is also a desirable scenario.

**Comment by shaggygi** [comment]
I like this idea.

**Comment by CyrusNajmabadi** [comment]
Tagging @huguesv if they want to move forward on this.  This would come through progression and involve notifying us somehow.
