### ISSUE TITLE
Usage of explicit operator is not found

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#50850]
**Version Used**: 16.9.P3

Because of this, I had to use breakpoints to work out where we had code that was calling an explicit operator.

Just checked, also repros with `_ = (int)new AWrapperType();`.

![image](https://user-images.githubusercontent.com/8040367/106080588-5e409480-60e5-11eb-837a-d1422be8cc01.png)

```cs
using System;

_ = (float)new AWrapperType();

struct AWrapperType
{
    public static explicit operator int(AWrapperType value)
    {
        Console.WriteLine("Definitely used");
        return 42;
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Note: thsi particular case is nearly impossible for us to support (there's both an explicit and implicit conversion involved).  But we can attempt to sovle the case where there is just an explicit conversion.  Working on that now.

**Comment by jnm2** [comment]
Impossible because it would have to wait for semantic analysis to complete in order to see the implicit conversions?

**Comment by CyrusNajmabadi** [comment]
> Impossible because it would have to wait for semantic analysis to complete in order to see the implicit conversions?

'Impossible' because find-refs doesn't use semantics to determine where results can be found.  It uses syntax.  So things that end up implicitly references (lke the float->int conversion here) have no representation in our system for finding things.

**Comment by jnm2** [comment]
Affordances are made for locating implicitly-called GetAwaiter/GetEnumerator/etc, I thought? It seems possible (but difficult and low-pri) to see "this is an operator" and recognize that results could be found anywhere.

**Comment by CyrusNajmabadi** [comment]
>  and recognize that results could be found anywhere.

This is the problem.  If they can be found anywhere, they have to be searched for anywhere, and that *will* take a long time (and still needs support).  things like GetEnumerator can be scoped down extremely narrowly to: just check `foreach` calls (whihc are normally 1:10,000 (or less) of a codebase.  It's the scale that's a problem here.

**Comment by jnm2** [comment]
Would be nice to have a `¯\_(ツ)_/¯` entry show up underneath to underscore the fact that there could be stuff it's not showing you. I'm used to being able to use this kind of search to find out if there are any usages remaining.

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/30210.

**Comment by CyrusNajmabadi** [comment]
Find all refs works on explicit conversions now.
