### ISSUE TITLE
Find References results coming from source generated files don't show classification

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#50878]
This was noticed by @sharwell.

**Comment by sharwell** [comment]
FAR shows highlighting, but when you click to navigate to that file it doesn't show highlighting for items defined in other files.

**Comment by sharwell** [comment]
I'll get a screenshot...

**Comment by jasonmalinowski** [comment]
@sharwell: oh, got it. So the entries in the FAR list is fine, at least?

**Comment by jasonmalinowski** [comment]
Then this is a dupe of #50676.
