### ISSUE TITLE
SymbolKey incorrectly matches delegates

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#50890]
**Version Used**: 
Version 16.9.0 Preview 4.0 [30920.304.main]

**Steps to Reproduce**:

```C#
var symbolKey = SymbolKey.Create(newSymbol, cancellationToken);
var oldSymbolResolution = symbolKey.Value.Resolve(oldCompilation, ignoreAssemblyKey: true, cancellationToken);
```

Where `newSymbol` is symbol for `delegate void D(int x);`, `oldCompilation` contains the same delegate qualified name but different signature: `delegate void D(int x);`.

**Expected Behavior**:
The resolution fails.

**Actual Behavior**:
The resolution succeeds and returns the delegate whose signature does not match the original.

**Comment by CyrusNajmabadi** [comment]
From an offline discussoin, this is actually correct.  You can distinguish delegates in .net only by signature.  in other words, thisis not allowed:

```c#
delegate void D(int i);
delegate void D(int i, int j);
```

As such, you don't need or want to re-resolve the delegate using the signature, just the name and arity is sufficient.  

This does mean you might resolve the first delegate to the second in the even of a compilation change.  But that's ok and is in line with how you might resolve a class to the same named class but with a new method in it across compilation edits.
