### ISSUE TITLE
Microsoft.VisualStudio.ImageCatalog is blocking moving to net5.0

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#50893]
From https://github.com/dotnet/roslyn/issues/50822#issuecomment-769023318

`Microsoft.VisualStudio.ImageCatalog` adds a superfluous framework reference to WPF on netcoreapp3.1, which prevents EditorFeatures (non-WPF) to move. .NET 5 SDK disallows WPF reference on neutral platform and only allows on Windows.
The implementation of the package doesn't require WPF or Windows at all.

Please contact them to remove the reference. The issue is present on latest package 16.9.30927.236.

This is blocking anything beyond `EditorFeatures`. Workaround is viable but not transitively, it must be allied to every project.

**Comment by jinujoseph** [comment]
@olegtk does it belong to editor side ?

**Comment by olegtk** [comment]
@jinujoseph IDE Experience

**Comment by CyrusNajmabadi** [comment]
Not sure what is needed from us here.
