### ISSUE TITLE
Investigate supporting both `CompletionChange.TextChange` and `CompletionChange.TextChanges`

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#50905]
We deprecated `TextChanges` in favor of `TextChange` because it worked better for VS in several scenarios. However, other editors (particularly LSP scenarios) break the changes up into a main text edit and a series of additional text edits. For these cases, the original version, with the changes broken up, was significantly more ergonomic. We should consider undeprecating the `TextChanges` version and providing both, potentially controlled by an option when resolving the change to better support these scenarios.

Another small, related change would be to put a bit on `CompletionItem` to advertise whether a change is "complicated" or not, ie whether it's just going to be an insert of the display text or if there's more to calculate. Today, external users such as Omnisharp use private reflection to get access to the provider name to make this determination, which isn't ideal.

**Comment by 333fred** [comment]
@CyrusNajmabadi I was playing around with this today in O#, and what I'm seeing is not what I was expecting. Given this input:

```cs
using System;
public class Base
{
    public abstract string Prop { get; set; }
}
public class Derived : Base
{
    override $$
}
```

I was expecting to see 2 changes in the result, something like:

1. `public ` before the `override`
2. `bool Prop { get => throw new NotImplementedException()$0; set => throw new NotImplementedException(); \\}` at the current cursor location.

Instead, what I'm seeing is a `TextChanges` array of length 1, with just `public override bool Prop { get => throw new NotImplementedException()$0; set => throw new NotImplementedException(); \\}`.

**Comment by 333fred** [comment]
Import completion _does_ do what I was expecting here, fwiw.

**Comment by CyrusNajmabadi** [comment]
this is expected from my perspective.  the feature computed a single atomic change that replaces eixsting code with the new code.  This sort of 'diff' would need to be done by someone consuming the data :)
