### ISSUE TITLE
Clarify testing recommendations for source generators

### ISSUE THREAD

**Issue by captainsafia** [dotnet/roslyn#50902]
As a developer trying to write unit tests for source generators, the existing docs lead me astray.

- The Source Generators Cookbook describes an outdated approached for testing source generators: https://github.com/dotnet/roslyn/blob/master/docs/features/source-generators.cookbook.md#unit-testing-of-generators
- The testing package (https://github.com/dotnet/roslyn-sdk/tree/master/src/Microsoft.CodeAnalysis.Testing) doesn't reference the new `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing` which is the recommended approach.

Some things that would help:

- Updating the sample in the cookboook.
- Making the `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing` more discoverable.

**Comment by Youssef1313** [comment]
@captainsafia The readme of the testing package was recently updated. So we need to update roslyn cookbook only.

**Comment by tonyhallett** [comment]
[Roslyn testing of CSharpSourceGeneratorTest](https://github.com/dotnet/roslyn-sdk/blob/d16bce93b36d078682776b93d5435287b038783f/tests/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.SourceGenerators.Testing.UnitTests/SourceGeneratorValidationTests.cs)

**Comment by AraHaan** [comment]
I feel that this unit testing stuff is missing things like ``VisualBasicSourceGeneratorTest`` (only for testing the source generator bailouts when run under an ``VisualBasicCompilation``. However some source generators do special generating for VB though.

**Comment by Youssef1313** [comment]
@AraHaan Is this a feedback about the testing framework? In this case, it should go to dotnet/roslyn-sdk repository.

**Comment by AraHaan** [comment]
I wonder why the repository that holds that testing framework not named ``roslyn-testingframework``? At first I thought it was a cleaver way to pack roslyn into an .NET SDK that can be installed as a nuget package that then adds packagereferences all of the roslyn stuff at first thought for analyzers/sourcegenerators to depend on that over explicitly adding those packagereferences themselves.

But then again I see why not do such a thing and bundle that within the .NET SDK as part of the work to add templates for analyzers/sourcegenerators which would make it all more cooler and easier to set it all up as then everything one could ever possibly need from roslyn could get referenced for them.

**Comment by Youssef1313** [comment]
@AraHaan It's not only for the testing framework.
