### ISSUE TITLE
Make Analyzer work against net5.0/netstandard2.1

### ISSUE THREAD

**Issue by andresrsanchez** [dotnet/roslyn#50914]
**Version Used**:  Default Analyzer project template

**Steps to Reproduce**:

1. Create new analyzer based on VS "Analyzer with Code Fix (.NET Standard)"
2. Update solution projects to target net5.0 or netstandard2.1
3. Run VSIX and check that default analyzer doesn't show up any message related to types with lowercase letters.
4. Downgrade analyzer/codefix to netstandard2.0
5. Run VSIX and check that default analyzer now works properly

I want to change the default target framework because I depend on some third party library compile against netstandard2.1/net5.0

Thanks!

**Comment by Youssef1313** [comment]
This is probably a known limitation. See https://github.com/dotnet/roslyn/issues/44251 for more details.

**Comment by huoyaoyuan** [comment]
This should not be possible now, because they are still loaded in Visual Studio which runs on .NET Framework.

**Comment by andresrsanchez** [comment]
Got it, thanks!!!
