### ISSUE TITLE
Investigate if a separate kind for a SourceGeneratedDocument makes sense

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#50912]
Broken out as a separate item for https://github.com/dotnet/roslyn/issues/50297:

> Potentially add TextDocumentKind.SourceGeneratedDocument. We're adding a new Document subclass for source-generated documents, but we currently haven't added a new TextDocumentKind for the class. @jasonmalinowski will investigate whether adding a new kind will be more harmful or helpful to customers and follow up on whether we should add a new kind, make SourceGeneratedDocument a separate type deriving from TextDocument, or some combination of both/neither.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
