### ISSUE TITLE
IDE0057  suggestion is less readable

### ISSUE THREAD

**Issue by StingyJack** [dotnet/roslyn#50918]
**Version Used**: 
netcoreapp3.1

**Steps to Reproduce**:

Have the following very simple code, that anyone who has worked with other common programming languages can look at and understand whats going to happen to `cookieValue`.
```
const int BEARER_LENGTH = 7;
cookieValue = cookieValue.Substring(BEARER_LENGTH);
```
VS complains and says "Substring can be simplified"

**Expected Behavior**:

I dont expect VS to report any problem with using a properly descriptive function named `Substring()`. The code is perfectly readable. 

**Actual Behavior**:

It suggests that I use this code instead, which does not inform the reader as to what is happening to the `cookieValue`.  Its less readable.
It has no intellisense or other completion support, has no hover tooltip help, and has red squiggles like a compiler error until I finish typing the closing `]`. 
```
const int BEARER_LENGTH = 7;
cookieValue = cookieValue[BEARER_LENGTH..];
```

Why is there a suggestion being made to change code to be less readable and that does not have some other tangible tradeoff benefit to it like improved performance?

**Comment by CyrusNajmabadi** [comment]
> Why is there a suggestion being made

The new code is considered more idiomatic as the language has a built-in pattern to support slicing strings.

> I dont expect VS to report any problem 

You can easily disable (or change the severity level) of the suggestion here:

![image](https://user-images.githubusercontent.com/4564579/106369913-3d0cbd80-630a-11eb-86de-22899e43928d.png)

**Comment by StingyJack** [comment]
A range operator makes sense when dealing with array types. A string is not an array type, and the idiomatic way to get part of a string has always been Substring. Even when explaining the new syntax it will be referred to as "Substring".  What is considered idiomatic is not something that can be dictated, it's determined by popular use like any other expression.  

This setting should not apply to strings, or at least have a separate control lever for them. Can that be considered?

Also, does MSFT have any publicly available tools that can be used to manage editorconfig files in 1300 GH repos to publish updates like this?

**Comment by CyrusNajmabadi** [comment]
> A range operator makes sense when dealing with array types

It makes sense on sliceable types. Strings are sliceable. That's why we support ranges and indexes on them. 

>  What is considered idiomatic is not something that can be dictated, 

Yes it can. We created the language and this was an intentional decision. It's exactly why we support these operators on strings. 

> This setting should not apply to strings,

I disagree. It should apply to all types it applies to. 

> at least have a separate control lever for them.

Yes. You can write a diagnostic suppressor to disable diagnostics for cases you don't like. 

> Also, does MSFT have any publicly available tools that can be used to manage editorconfig files in 1300 GH repos to publish updates like this?

I'm not sure what the question is asking. Can you clarify.

**Comment by StingyJack** [comment]
From our differing viewpoints I think its safe to say that this rule and codefix are subjective. "More readable" to me is going to involve using words in my native language, not symbols or specific shorthand.  It means something else to you. For me that would have been enough difference to not enable this as a default.

Trying to dictate something as being idiomatic is like trying to force a figure of speech or expression you just invented on everyone else (like "Its raining ukuleles and dulcimers"). Maybe you or a few people think its cool and use that expression, but its overall popularity and usage is going to be what makes it generally understood and part of idiomatic English. 

> I'm not sure what the question is asking. Can you clarify.

my org has 1300 repos on GitHub. To change this means possibly 1300 editorconfig files to update. Its actually far less than that number but its still a lot to have to update manually, so I was asking if you knew of any publicly available tools for managing this kind of thing across repos in an org.

**Comment by CyrusNajmabadi** [comment]
> Trying to dictate something as being idiomatic

It is literally idiomatic. It's using the idioms the language natively supports for slicing. 

I get that you don't find it now readable. That's fine. Just disable the suggestion :-)

**Comment by CyrusNajmabadi** [comment]
> my org has 1300 repos on GitHub. To change this means possibly 1300 editorconfig files to update. 

I would just write a little script to do this.
