### ISSUE TITLE
Existence of a using static changes the compiled code

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#50916]
**Version Used**: 

master

**Steps to Reproduce**:

Compare [SharpLab 1](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAGQEsA7ARwG4BYAKBuIjDigAcIBjODAVShIHMAyjAgxCbAPoBZAJ6xE0mgG8aGVVkw4AbBgCixAK6MEEYABs4VamqwAmLNgDsKtcqvW1WrABYMkiCQAKHDQAbQBdDAgEPigASmd3DFdExIA3KIwADwwAXl0DIxNzXAAlCGI+OAC0ABoMbDR4txSU3ABBKAAFKIhTc1MA2NwAFQB7NoRjaUHLFoBfBIwF6mWgA==) with [SharpLab 2](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAGQEsA7ARwG4BYAKBuIjDigAcIBjODAVShIHMAyjAgxCbAPoBZAJ6xE0mgG8aGVRgD069FmwA2DAFFiAV0YIIwADZwq1NVgBMOgOwq1yu/bU59KACwYkhAkABQ4aADaALoYEAh8UACUbl4YHqmpAG5xGAAeuRgAvIYmZhbWuABKEMR8cCFoADQY2GjJnhkZuACCUAAKcRCW1pYhibgAKgD23Qjm0mO2nQC+KRir1BtAA===).

- Without a using static, `ToArray` refers to `ParallelEnumerable.ToArray`.
- With using static, `ToArray` refers to `Enumerable.ToArray`

I don't know if this is a bug or not. I'm reporting based on [this SO question](https://stackoverflow.com/questions/65972505/using-static-kills-asparallel).

**Comment by huoyaoyuan** [comment]
Overload precedence? It is reasonable to be Using static imported > on the exact type > on base type, the the behavior is expected for this order.

**Comment by Youssef1313** [comment]
@huoyaoyuan Thanks. This is by design then?

Can you point to where in the specs this is mentioned?

Thanks again!

**Comment by huoyaoyuan** [comment]
Documented in [Extension Method Invocation](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#extension-method-invocations):

> If types `Ci` imported by *using_static_declarations* and directly declared in namespaces imported by *using_namespace_directives* in the given namespace or compilation unit directly contain eligible extension methods `Mj`, then the set of those extension methods is the candidate set.

This should mean that using inside namespace has priority over using outside namespace?

**Comment by Youssef1313** [comment]
Thanks for pointing to this. I'm going to close. Thanks for clarification.
