### ISSUE TITLE
Variable swapping using C# tuples should work without lowering to ValueTuple, so that ref structs can be swapped

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#50924]
**Version Used**: 16.9.P3

It looks like an intermediate representation that the Roslyn compiler uses for C# tuples requires variable swapping syntax to be realized using the `ValueTuple<T1, T2>` type. This means that you can't use the syntax to swap variables of ref struct types.

```cs
class C
{
    void M()
    {
        var currentBuffer = new SomeBuffer();
        var lastBuffer = new SomeBuffer();

        for (var frameIndex = 0; frameIndex < 10; frameIndex++)
        {
            // (This part draws to currentBuffer and diffs with lastBuffer)

            // ...

            // ❌ CS0306 The type 'SomeBuffer' may not be used as a type argument
            // ❌ CS0306 The type 'SomeBuffer' may not be used as a type argument
            //                             ↓↓↓↓↓↓↓↓↓↓  ↓↓↓↓↓↓↓↓↓↓↓↓↓
            (currentBuffer, lastBuffer) = (lastBuffer, currentBuffer);
        }
    }
}

ref struct SomeBuffer { }
```

**Comment by jnm2** [comment]
Also, it looks like there is an opportunity for better IL codegen with optimizations enabled.

Sharplab: [using tuple syntax](https://sharplab.io/#v2:C4LglgNgPgAgTAAgMIFgBQBvdCcJgFgQFkAKASm1yzV1oQDcBDAJwQGMBXZ5gUwDtgAIQ4AzET1YBeBHx4B3BAGUA9gFsewsRPIBuSnQYsEERgGcho8VJnylajZe1k9afXRHLWJJqxHNG6gCSfAAmPAAeCNIADDoIfgE8wWGRADwIAIyx8f5BoREA1AUUNAYI1GV0APRVCCQAKgAWYKYIAA4swAgh/nKtwMrsXLwCmlYIjKHdYGKtcmDAjcZmFlrMJW6VNQgAdHvom2XbgDLkyIrRAMzRAGwITTwIwACebQ8A5CrqYxJvCKqMTxkyi6ACMHhxTDwQhNWoxHi8HiwAOYcdQCQ4GE5nS43O6NB7PV4ID72b7MX7/QF8YEIMEICFQmETeFE5Go/jADHVWqVXl8hCAZMIhcKRTgReKRVzaCRONwOWSADTLcxkshROomFWOZhK2UjVZWZxcgC+blNaHN6HMzA4bC6nwca3KCGNQA=), [using a temp local](https://sharplab.io/#v2:C4LglgNgPgAgTAAgMIFgBQBvdCcJgFgQFkAKASm1yzV1oQDcBDAJwQGMBXZ5gUwDtgAIQ4AzET1YBeBHx4B3BAGUA9gFsewsRPIBuSnQYsEERgGcho8VJnylajZe1k9afXRHLWJJqxHNG6gCSfAAmPAAeCNIADDoIfgE8wWGRADwIAIyx8f5BoREA1AUUNAYI1GV0APRVCCQAKgAWYKYIAA4swAgh/nKtwMrsXLwCmlYIjKHdYGKtcmDAjcZmFlrMJW6VNQgAdHvom2U+NuGr49Im5mMSLpW0l2cSUUPc/I/Mt3c4nK+jjtayU7XD6HHAAXzcELQUPQ5mYHDYXRU6mB5QQYKAA==)

```diff
-// Code size 36 (0x24)
+// Code size 34 (0x22)
 .maxstack 2
 .locals init (
     [0] valuetype SomeBuffer currentBuffer,
     [1] valuetype SomeBuffer lastBuffer,
     [2] int32 frameIndex,
-    [3] valuetype SomeBuffer
 )
 
 ldloca.s 0
 initobj SomeBuffer
 ldloca.s 1
 initobj SomeBuffer
 ldc.i4.0
 stloc.2
 // sequence point: hidden
 br.s LOOP_HEAD
 // loop start
     IL_0014: ldloc.1
     ldloc.0
-    stloc.3
-    stloc.0
-    ldloc.3
     stloc.1
+    stloc.0
     ldloc.2
     ldc.i4.1
     add
     stloc.2
 
     LOOP_HEAD: ldloc.2
     ldc.i4.s 10
     blt.s IL_0014
 // end loop
 
 ret
 ```

**Comment by huoyaoyuan** [comment]
Swapping may also be allowed in absent of `ValueTuple` type.

**Comment by alrz** [comment]
>without lowering to ValueTuple

It already does that whenever it can, but the binder always check for valid type arguments in ValueTupe.

**Comment by jaredpar** [comment]
This behavior is "By Design". 

The RHS of the operation here is defined as creating a `ValueTuple` and those do not support a number of types including `ref struct`, `pointer` , `function pointers`, etc ... During the design we decided that the implementation of `ValueTuple` was assumed to be side effect free. That meant the compiler could omit references to it during codegen if it didn't strictly need the type. That doesn't change that the semantics of the operation are still defined in terms of `ValueTuple` here. 

The extra temporaries generated are covered by #50784.

**Comment by jnm2** [comment]
@jaredpar Where is an appropriate venue to propose a change to the design?

**Comment by CyrusNajmabadi** [comment]
@jnm2 I would make a lang proposal on csharplang.  I'm not *exactly* certain how the proposal woudl be shaped.  But maybe it would be just about calling out that if there is a tuple assignment, and it's to storage locations, that those storage locations don't have any particular restrictiosn on them over what a normal assignmetn would have.
