### ISSUE TITLE
IDE0044 suggests making field readonly when generated code writes to it

### ISSUE THREAD

**Issue by sid-6581** [dotnet/roslyn#50925]
**Version Used**: 

Visual Studio 16.8.4

**Steps to Reproduce**:

Given the following program and source generator:

```cs
namespace ConsoleApp
{
    [TestGenerator]
    public sealed partial class Test
    {
        private int _value;
    }

    public static class Program
    {
        public static void Main()
            => _ = new Test { Value = 1 };
    }
}
```

```cs
namespace SourceGenerator
{
    [Generator]
    internal class TestGenerator : ISourceGenerator
    {
        private const string AttributeText = @"
using System;
[AttributeUsage(AttributeTargets.Class)]
internal sealed class TestGeneratorAttribute : Attribute
{
}
";

        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("TestGeneratorAttribute.g.cs", SourceText.From(AttributeText, Encoding.UTF8));

            if (context.SyntaxReceiver is not TypeSyntaxReceiver)
                return;

            context.AddSource("TestGenerator.g.cs", @"
namespace ConsoleApp
{
    partial class Test
    {
        public int Value
        {
            get => _value;
            set => _value = value;
        }
    }
}
");
        }

        public void Initialize(GeneratorInitializationContext context)
            => context.RegisterForSyntaxNotifications(() => new TypeSyntaxReceiver());

        private sealed class TypeSyntaxReceiver : ISyntaxReceiver
        {
            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
            }
        }
    }
}
```

**Expected Behavior**:

Expect no IDE0044 for `_value`, since the generated code has a property that uses it as a backing field.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/28602336/106394451-4c4f4200-63c2-11eb-9c60-957cf232d294.png)

Applying the suggested fix and adding `readonly` results in CS0191 (a readonly field cannot be assigned to.)

Adding `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` in the program's `csproj` also makes IDE0044 show up in the build output, not just in the IDE.

**Comment by huoyaoyuan** [comment]
This is caused by analyzer doesn't have view of content from generator? Or it does have view but misbehaved?

**Comment by mavasani** [comment]
This seems to be due to the fact that our IDE code style analyzers explicitly request for not getting callbacks for generated code: https://github.com/dotnet/roslyn/blob/81c70ba8a741b1d9f93edce114fe5e6bd1ebc99c/src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs#L70-L71

We need to modify the `MakeFieldReadOnlyAnalyzer` to instead invoke `context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze);` in the `Initialize` method, likely by just introducing a virtual property in `AbstractBuiltInCodeStyleDiagnosticAnalyzer` as follows:

```csharp
        // Code style analyzers should not run on generated code, unless explicitly overridden and requested by the analyzer.
        protected virtual GeneratedCodeAnalysisFlags GeneratedCodeAnalysisFlags => GeneratedCodeAnalysisFlags.None;

        public sealed override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags);
...

```

and overriding it in `MakeFieldReadOnlyAnalyzer` to return `GeneratedCodeAnalysisFlags.Analyze`
