### ISSUE TITLE
Pattern matching with a type pattern expression and `not` keyword results in incorrect null value

### ISSUE THREAD

**Issue by jduncanator** [dotnet/roslyn#50921]
**Version Used**: 

.NET Runtime Version: 5.0.2
Roslyn Version: 3.8.0-5.20562.2

**Steps to Reproduce**:

The following code prints `true` when it should print `false`. The value of `x` after the pattern expression is evaluated should be assigned to the variable `y`.

```cs
var x = new Test();

if(x is not Test y)
{
    return;
}

Console.WriteLine(y == null); // Prints 'True'
```

This appears to be the result of a compiler optimisation, where the compiler can infer the type of `x` being constant at compile time, and emitting an optimised code path. If we change the declaration of `x` to be of type `object`, the compiler no longer applies this optimisation, and we get the expected value of `false`:

```cs
object x = new Test();

if(x is not Test y)
{
    return;
}

Console.WriteLine(y == null); // Prints 'False'
```

Interestingly, this behaviour only occurs when using C# 9's new `not` keyword, using the C# 8 way of pattern matching here results in the correct behaviour, printing `false`:

```cs

var x = new Test();

if(!(x is Test y))
{
    return;
}

Console.WriteLine(y == null); // Prints 'False'
```

It should be noted that current versions of Visual Studio suggest replacing the above implementation with the broken implementation, which has different behaviour and breaks existing code. This is a bigger issue when automatically applying VS formatting suggestions across an entire project or repository, where one would expect the changes to have identical behaviour.

Let me know if this is the incorrect place to report this issue. I believe it's a compiler issue (looking at the code generated from each of the 3 examples), so have opened it here. Feel free to update the title of the issue as well, I couldn't find a concise way of conferring the issue.

Thanks to @gdkchan for initially pointing out this odd behaviour they were seeing.

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/49369. I cannot reproduce with latest master.

**Comment by jduncanator** [comment]
Thanks @Youssef1313, indeed it looks like it's been fixed!
