### ISSUE TITLE
Enum values with omitted type name should use the enum color

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#50926]
**Brief description:**

This proposal is about having VS use the color for enum types to colorize enum values too when the type is omitted (eg. when you have `using static MyEnum` in the file). Right now enum values are just white, so at a glance it's impossible to tell they're enum values and not some local field/property. C++ does the same as well and colorizes enum values in scope, which makes it very easy to understand what's going on when glancing at a code snippet. Here's an example:

![image](https://user-images.githubusercontent.com/10199417/106398480-3d44b000-6413-11eb-80fb-a0c00327a062.png)

**Languages applicable:**

C#

**Visible changes:**

Consider this simple snippet where I'm invoking a `Test(AllocationMode allocationMode)` method:

![image](https://user-images.githubusercontent.com/10199417/106398498-65ccaa00-6413-11eb-9f9c-fb0fa0cca30e.png)

It's impossible to easily understand that that `Default` is actually an enum value and not eg. a local property.
With the proposed change, the snippet above would become this instead:

![image](https://user-images.githubusercontent.com/10199417/106398507-7715b680-6413-11eb-8046-b844a5dde354.png)

**Comment by CyrusNajmabadi** [comment]
I would just set this color instead:

![image](https://user-images.githubusercontent.com/4564579/106399904-43656d00-63d0-11eb-849a-671de5baa7bc.png)

That should be supported regardless of if the member is qualified or not.

**Comment by Sergio0694** [comment]
Ah, love it, had missed that setting, thanks Cyrus! 😄

![image](https://user-images.githubusercontent.com/10199417/106400274-9d405400-641d-11eb-855f-ff945bfec574.png)

Will leave this open as I think there's value in making this a default, given that C++ does the same with the default VS theme.
But feel free to close this issue if this is not something the team would be interested in doing.
Really happy it was this easy to manually set though! 🎉

**Comment by CyrusNajmabadi** [comment]
I'm going to close it out as i don't think it's appropriate.  We color the items based on what it is.  An enum member is an enum member regardless of how it it used.  Just because it wasn't qualified doesn't mean we should color it as if it's a type (as opposed to a member).  I actually think that that is *misleading* as it will look like you're referencing a type not a member of hte type.  

Thanks thought!
