### ISSUE TITLE
Reference showing in different place.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50939]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Reference-showing-in-different-place/1324841)._

---
[severity:Other]

![image](https://user-images.githubusercontent.com/1408396/106497697-3a79a780-6473-11eb-9013-846fd96cbb34.png)

I think you will be fix this issue in further version.

Thanks @MS team

---
#### Feedback Bot on 1/31/2021, 07:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
It looks like the CodeLens placement is wrong when word wrap is enabled.

**Comment by jinujoseph** [comment]
@olegtk do you know if this is on editor or Roslyn end ?

**Comment by olegtk** [comment]
If it only reproduces when word wrap is enabled, then route it to the editor. Thanks!

**Comment by Youssef1313** [comment]
I'm unable to reproduce whether word wrap is enabled or not. :(
