### ISSUE TITLE
C#: IntelliSense don't show Enum values after "is" keyword

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50936]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C:-IntelliSense-dont-show-Enum-values-/1322245)._

---
[severity:It bothers me. A fix would be nice]
IntelliSense have a different behavior with the "is" keyword than the "==" operator when using Enum type.

Example:
MyClass.MyEnumProperty == MyEnum.ValueOne <--- Works as intended

MyClass.MyEnumProperty is MyEnum. <--- Here IntelliSense stop working and don't show anything even through it did recommand the "MyEnum" type.

---
#### Feedback Bot on 1/27/2021, 05:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
@genlu  can you check if this happens in latest build

**Comment by genlu** [comment]
Looks like this is fixed
![image](https://user-images.githubusercontent.com/788783/108904872-e24a4700-75d3-11eb-862a-c7b36af28470.png)

**Comment by CyrusNajmabadi** [comment]
@genlu can we make sure we have tests here, including after things like `foo is Enum.V1 or ...` ?  thanks!

**Comment by genlu** [comment]
Sure
