### ISSUE TITLE
Variable named 'from' can not be used in LINQ Query syntax

### ISSUE THREAD

**Issue by usikpavel** [dotnet/roslyn#50935]
**Version Used**: NET 5, Visual Studio Community 2019 Version 16.8.0

**Steps to Reproduce**:

Compile the following method:

```
    public static IEnumerable<int> Test(IEnumerable<int> integers, int from, int to)
      => (from i in integers
          where i >= from && i < to
          select i);
```
**Expected Behavior**:
No errors

**Actual Behavior**:
The code above is compiling with an `error CS1525: Invalid expression term '&&'`

** Workaround **
Rename variable `from` to something like `iFrom` to avoid a compiler to treat it like a LINQ keyword `from`.

**Comment by CyrusNajmabadi** [comment]
Yes.  this is how the language was spec'ed.  Teh compiler is behaving as expected here.

**Comment by CyrusNajmabadi** [comment]
> ** Workaround **

you should be able to do `@from` here i  believe.
