### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp has a hidden dependency on Microsoft.DiaSymReader.Native.*.dll

### ISSUE THREAD

**Issue by belkiss** [dotnet/roslyn#50945]
Hello!

**Version Used**:  `Microsoft.CodeAnalysis.CSharp` nuget package version `3.8.0`

**Steps to Reproduce**:

1. Add a dependency to Microsoft.CodeAnalysis.CSharp
2. Use runtime compilation, for instance I'm doing
```csharp
EmitResult result = compilation.Emit(
    dllStream,
    pdbStream,
    options: new EmitOptions(
        debugInformationFormat: Util.IsRunningOnUnix() ? DebugInformationFormat.PortablePdb : DebugInformationFormat.Pdb,
        pdbFilePath: pdbFilePath
    )
);
```
3. Note that when running the app on windows through a debugger (in my case visual studio), a (caught) exception can be seen in the log:
```
Exception thrown: 'System.DllNotFoundException' in Microsoft.CodeAnalysis.dll
Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Expected Behavior**:
No exception thrown.

**Actual Behavior**:
The application doesn't crash, but this exception is printed.

Thanks!

**Comment by jaredpar** [comment]
Thanks for reporting this issue unfortunately this behavior is "By Design". 

The decision was made to not package the native PDB reader by default with Microsoft.CodeAnalysis. That would force it into scenarios where it wasn't necessary, like Unix or when consumers are using portable PDBs. Instead in the cases where consumers wanted to continue using the native PDB format they should add a reference to [Microsoft.DiaSymReader.Native](https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/16.9.0-beta1.21055.5)

**Comment by tmat** [comment]
@belkiss I'd recommend using `DebugInformationFormat.PortablePdbPdb` on all platforms. The Windows PDB format is obsolete.

**Comment by belkiss** [comment]
Heya!
Thank you for your precisions @jaredpa, much appreciated, and I understand the reasoning. I used to add the reference to the DIA but for some reason the copy of the DLL stopped occuring when I switched my project to the new csproj file format.

And thanks for your suggestion @tmat, unfortunately for some reason on windows, if I use `PortablePdb` then the callstack resolving code that I have at https://github.com/ubisoft/Sharpmake/blob/6cd9cd9c7304f68f10ac5ded03e1b1453699e4f7/Sharpmake/Util.cs#L1253 doesn't seem to contain the filenames for the methods that come from files compiled at runtime, which is something that my app definitely need. Note that this only occur if the executable has been built from a different machine. If I build the app locally, then the filenames are there :(

**Comment by belkiss** [comment]
Nevermind the issue with the StackTrace resolving seems to be caused by one of our internal tools!

`PortablePdb` works perfectly!

All's well, thanks again! Cheers :)

**Comment by tmat** [comment]
Glad it works for you.

**Comment by tmat** [comment]
Just in case you have issues with .NET Framework applications not displaying source locations in stack traces, make sure the right settings are present in their App.config file - see https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.1-4.7.2#stack-traces-obtained-when-using-portable-pdbs-now-include-source-file-and-line-information-if-requested
