### ISSUE TITLE
[LSP] Specify text edits instead of insert text for completion items

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#50964]
In order to make sure the applicable to span is set correctly, we should always be sending text edits instead of insert text from completion.

@AmadeusW should we continue to rely on the behavior of overriding textedits?  That way we don't need to send all textedits for all completion items upfront.

Additionally if we're cleaning stuff here, we should see what other duplication in the list we can remove

Razor will need to respond to these changes to re-map text edits.

**Comment by NTaylorMullen** [comment]
One concern to keep in mind is in regards to performance. Reason being is that we'll be going from:
```
{
...
insertText: DateTime
...
}
```

To:

```
{
...
textEdit: {
    range: {
        start: {
             line: 0,
             charcter: 1
         },
        end: {
             line: 0,
             charcter: 10
         }
    },
    newText: DateTime
}
...
}
```

Given the platform re-serializes bits 4+x per request in remote scenarios this could get expensive. Some pieces that will improve this performance:
1. LSP Platform refactor. They'll hopefully be able to reduce the serialization round trips to 2-3x
2. Optimized completion list serialization at the platform layer. Don't serialize things we don't need to & caching of json payload bits

Ultimately it probably makes sense to put this work behind a feature flag for a time being to properly analyze the impact.

**Comment by dibarbet** [comment]
@NTaylorMullen IIRC the editor allows us to specify textedits on resolve.  If we can do that, we shouldn't need to worry about serialization costs too much.  Otherwise though it will definitely be problematic

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen IIRC the editor allows us to specify textedits on resolve. If we can do that, we shouldn't need to worry about serialization costs too much

That's what they were talking about in the LSP sync-up meeting today. It's a spec violation to allow changes of textEdit because it modifies the applicableToSpan which influences things like filtering / sorting criteria.

**Comment by allisonchou** [comment]
Since it sounds like there may be perf issues here, I'll take Taylor's suggestion of putting this behind a feature flag when implementing.

**Comment by NTaylorMullen** [comment]
> Since it sounds like there may be perf issues here, I'll take Taylor's suggestion of putting this behind a feature flag when implementing.

If I have time this sprint I'll work on implementing an "OptimizedTextEdit" at the protocol layer to limit its impact
