### ISSUE TITLE
Needs Review: Proposal: Emitting compiler details

### ISSUE THREAD

**Issue by nschuessler** [dotnet/roslyn#50978]
Problem:

It is quite difficult (nearly impossible) to map the symbols in the generated IL back to the original code in an automated way.  In particular the the frame names coming from data collected in PerfView. 

You can get part of the way with using RegExs to clean the mangled names to try and map back but this solution would have to be repeated by every customer that needs to do it, and would break every time there are subtle compiler changes. Also, for cases like anonymous delegates, once the compiler process exits, all chances of correlating back to the original code are lost.

Q: Why does it need to be an automated way?
A: Because when you have millions of lines of code in a product, it becomes difficult to inspect mangled symbol names and find the code for each issue found. Also having this automated would allow big productivity increases in doing automated code fixes for defects found in production.

Proposed solution:

The most reliable way to extract the metadata information that is in the generated IL at compile time when the original source context is available so that a mapping file can be output on the lowered code (i.e. the code blocks that perfview may identify).
The table would roughly contain:
- module name (assembly.dll)
- source symbol name (which triggered the code block)
- source file path
- source starting line number
- source symbol metadata name
- emitted symbol name
- emitted symbol metadata name

For synthesized names (such as rewritten `async Task` methods), IAsyncEnumerable, delegates, contributions from generators each case would have to be investigated.

This data could then be matched against perfview output to find the module/class/method that triggered the output.

It seems that an extensibility mechanism similar to analyzers where `MethodCompiler` puts events into a queue and the class like `AnalyzerDriver` for the emit queue would be a consistent solution.

i.e.  The benefits:
1) Crashes in the extensions would not affect compilation
2) Extensions would not slow the performance of the core emitting tasks

Comments?

I don't see any viable alternatives.

**Comment by jaredpar** [comment]
> It is quite difficult (nearly impossible) to map the symbols in the generated IL back to the original code in an automated way

This is a non-goal of the compiler. 

> Also, for cases like anonymous delegates, once the compiler process exits, all chances of correlating back to the original code are lost.

I don't agree with this statement. Consider the set of existing decompilation tools that exist today. They do an excellent job of connecting the IL back to the original source and symbols that the user wrote. This goes against the statement that all chances are lost at doing this. 

> Because when you have millions of lines of code in a product, it becomes difficult to inspect mangled symbol names and find the code for each issue found. 

It is not the job of the DLL to map instructions back to code, that is the job of the PDB. The PDB contains all the necessary information to do this (consider this is how all debugging works). 

> I don't see any viable alternatives.

I'm still uncertain of both what problem you are trying to solve and what exactly the proposal is here. 

It seems you're attempting to map frame names back to the code that produced them. If so I don't see how any compiler changes are necessary here. There are a host of tools which today are successful at mapping back frame names to the code that produced them (see any decompiler for examples).

**Comment by tmat** [comment]
Roslyn's debugger components perform various mappings like the ones requested - this is essential for EnC. It is definitely possible using information in the DLL and the PDB. Unfortunately, the code is currently all internal. It'd definitely be interesting to make it a public API that does not leak implementation details out (so that we allow the compiler to change how code is emitted) but still provides high-level metadata to source mapping APIs.

I'm not sure however when/if we are going to be able to expose such APIs any time soon due to our priorities.

**Comment by nschuessler** [comment]
Thanks for the comments.  It seems the problem is more difficult because we don't have the PDBs available in production.

So the best I can hope for seems to be exporting:
1) The PDB  name & signature (so I can find it outside the data center)
2) Binary signature info (so I can find it outside the data center)
3) Method name (from IL)
4) IL offset of current stack address

**Comment by tmat** [comment]
I'm not sure I understand the scenario. Are you performing the analysis in prod? I thought you would just collect perf traces there and then analyze them elsewhere. As long as your build pipeline publishes PDBs to a symbol server the analysis tool should be able to fetch them from there based on the debug information present in the DLLs.

**Comment by nschuessler** [comment]
We do not copy ETL traces out of production. We extract minimal performance metrics and extract (timestamp, FrameName, InclusiveTime, ExclusiveTime), CallStack.  That's about it.  Thus if we could the additional items (other than item 3 -- FrameName) deeper analysis could happen outside of prod.

**Comment by tmat** [comment]
Still, you only need the mapping to source at the end of the pipeline - not in prod, where you could fetch the PDBs from a symbol server. Correct?

**Comment by nschuessler** [comment]
Correct. However, I was thinking of pre-"extracting" the information from the PDB during build when we have (source, output, PDB) all available at the same time.  And if you are doing it during build, then my question is, why not do it on the first pass when you are compiling vs, re-opening all the files (PDB, binary) and potentially the source file (to run an analyzer on it).

**Comment by tmat** [comment]
DLLs and Portable PDBs are very compact representations, so I am not sure what you'd gain by inventing another format where to store a subset of the information already stored in the DLLs and PDBs.

**Comment by nschuessler** [comment]
That may be the case, however, I need to do a lookup through the data quickly.  I.e.  I need a mapping from `Microsoft.CodeAnalysys.xxx.Compliation.CompileAsync` to any perf information we have as fast as possible (10 seconds or less).  A web service call to dig through a PDB would not be that fast right?

**Comment by tmat** [comment]
Digging thru Portable PDB is fast (definitely avoid using Windows PDBs). You can also implement some caching strategy at the web service entry point.

**Comment by tmat** [comment]
If you find reading data from PDB actually the bottleneck then yes, you could precalculate some data during build. But then you would just move the digging thru PDB logic as a post-build step in your CI.

**Comment by nschuessler** [comment]
Does the PDB contain data for code blobs that are not in the original code? i.e. `async Task` methods with the .MoveNext() and name mangling?

**Comment by tmat** [comment]
Mapping of mangled synthesized names to the source names can be done without the PDB. The information is encoded in the names of the members and in some cases in custom attributes (such as `StateMachineAttribute`).

Rather then adding another extensibility point into Emit I believe it'd be better if Roslyn provided public APIs that would give you the ability to map from mangled names back to source names of the symbol. It would be much easier to implement.

The PDB contains some [extra information](https://github.com/dotnet/runtime/blob/master/docs/design/specs/PortablePdb-Metadata.md) such as source file path, source starting line number that you list above.

**Comment by nschuessler** [comment]
Any hit how to use `System.Reflection.Metadata` to get the method name and signature from the PDB file?

```
public IEnumerable<IDictionary<string, string>> GetMethodDebugInformation()
{
    foreach (MethodDebugInformationHandle handle in _metaData.MethodDebugInformation)
    {
        Dictionary<string, string> properties = new Dictionary<string, string>();

        MethodDebugInformation entry = _metaData.GetMethodDebugInformation(handle);

        Document document = _metaData.GetDocument(entry.Document);

        properties["documentName"] = _metaData.GetString(document.Name);

        StandaloneSignature signature = _metaData.GetStandaloneSignature(entry.LocalSignature);

        foreach (SequencePoint sp in entry.GetSequencePoints())
        {
            Console.WriteLine($"Start: {sp.StartLine}, End {sp.EndLine}");
        }

        yield return properties;
    }
```
