### ISSUE TITLE
CS8805: Program using top-level statements must be an executable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50979]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/CS8805:-Program-using-top-level-statemen/1279318)._

---
[severity:It bothers me. A fix would be nice]
Not so much a bug. It would have been nice to add the file and line at which the top-level statement causing the error occurred:
          **CS8805: Program using top-level statements must be an executable**

We have several hundred files with in library.   One file accidentally had a double semi-colon after a using statement.
example:  using ourNamespace;;

took me several hours to figure it out.

---
#### Feedback Bot on 12/7/2020, 01:17 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Stephen Friedl on 1/24/2021, 07:37 PM: 

<p>+1; this is a <em><strong>completely</strong></em> unactionable error message and I would have never figured it out on my own.</p>

**Comment by CyrusNajmabadi** [comment]
@jcouv this is a good point.  Perhaps the error should point at the first statement that made the compiler think there were top level statements.

**Comment by jcouv** [comment]
FYI @AlekseyTs

**Comment by JimInNC** [comment]
SimonRev: Thank you for the fix!  I switched down to 8.0 and lo-and-behold it showed me the filename and line # where I had the extra semi-colon.  Thanks!!
