### ISSUE TITLE
CA1001 Fixer generates incorrect code

### ISSUE THREAD

**Issue by vbjay** [dotnet/roslyn#5097]
![image](https://cloud.githubusercontent.com/assets/3629489/9752565/f91a693e-567f-11e5-9979-101d1cc04365.png)
As you can see.  When you run the fixer with a class that already implements an interface, it adds a 
```VB
, IDisposable
```
line to the code file.  The only problem is that the Implements statement does not allow multiple lines unless the "," is on the end of the line like this

```VB
 Implements IExporter,
            IDisposable
```

**Comment by balajikris** [comment]
Isn't this coming from [roslyn-analyzers/src/FxCop/System.Runtime.Analyzers/Core/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.Fixer.cs](https://github.com/dotnet/roslyn-analyzers/blob/262fa8584a5b8a9c1a106d758fae9e1ef9b579e6/src/FxCop/System.Runtime.Analyzers/Core/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.Fixer.cs) ?

I didn't know we (IDE team) owned this repo :smiley:

**Comment by vbjay** [comment]
The url of the nuget package project site pointed me here. Sorry if it
isn't the right place.

**Comment by balajikris** [comment]
@vbjay No worries. There still might be something to sort out here, I'm not entirely sure either.. Either the issue goes to https://github.com/dotnet/roslyn-analyzers/issues and the nuget package is updated correctly :smile:

**Comment by balajikris** [comment]
@vbjay I'd like to clarify that my first comment was a question for @Pilchie.. :)

**Comment by Pilchie** [comment]
Yes, we should move the bug over to the new repo not that we've moved the code over there (and file a bug to update the links).

**Comment by Pilchie** [comment]
I misread this as the standard implement interface fix.

**Comment by Pilchie** [comment]
Oops, wrong Matt :)
