### ISSUE TITLE
Ignore intellisense and "add items from unimported namespace" in lambda before the arrow.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#50981]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Ignore-intellisense-and-add-items-from-/1318071)._

---
For example, typing: 

```
someCollection.FirstOrDefault(x => x.Id == targetId)
```

always results in importing `System.Security.Cryptography.X509Certificates` when entering the space after `x`.

---
#### Feedback Bot on 1/25/2021, 00:09 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment]
This is likely fixed by https://github.com/dotnet/roslyn/pull/47857, however, I found a selection issue with deletion trigger, will use this to track that
