### ISSUE TITLE
README Azure badges shows as unknown

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#51005]
![image](https://user-images.githubusercontent.com/31348972/106926143-76ce3180-6719-11eb-96aa-341132a454d5.png)

The relevant script for generating this part of README:

https://github.com/dotnet/roslyn/blob/master/scripts/generate-badges.ps1

**Comment by RikkiGibson** [comment]
For example, `Windows_Desktop_Unit_Tests#debug_32` should probably change to something like [`Test_Windows_Desktop_Debug_32`](https://dev.azure.com/dnceng/public/_build/results?buildId=983736&view=logs&j=8f5cd3ce-d9d6-5116-f2f3-35d51d8e0134). Seems like the script does some string manipulation that I don't know the significance of off the cuff, though.

The table should also include new entries for the standalone build jobs such as [`Build_Windows_Debug`](https://dev.azure.com/dnceng/public/_build/results?buildId=983736&view=logs&j=b2bb0dc1-9cbd-51f0-af1d-56de48e14afe)
