### ISSUE TITLE
[Loc] Help with translation

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/roslyn#51015]
String Resource ID | 0; "FEATURE_InitOnlySettersUsage"
-- | --
Source String | assigning to or passing 'ByRef' properties with init-only setters
Subtenant | dotnet_roslyn
Source Control Link |  
Filename | Compilers\VisualBasic\Portable\xlf\VBResources.xlf
Question | Is this string complete? Interpreted as standalone string for now, otherwise please advise.

**Comment by crsuzukimsft** [comment]
vcq 366538

**Comment by Youssef1313** [comment]
cc: @AlekseyTs

**Comment by Youssef1313** [comment]
@crsuzukimsft I gave this a look. It appears that it's not the "full string". This resource will be embedded in another statement. For example "Visual Basic 16 does not support assigning to or passing 'ByRef' properties with init-only setters."

**Comment by AlekseyTs** [comment]
That is correct. The string is going to replace placeholder in ERR_LanguageVersion string. For example: "BC36716: Visual Basic 16 does not support **assigning to or passing 'ByRef' properties with init-only setters**."

**Comment by jaredpar** [comment]
@crsuzukimsft do you have enough info to fix the translation now?

**Comment by crsuzukimsft** [comment]
Thanks!
