### ISSUE TITLE
CLR: automatic boxed value pooling for small types (bool and bool?)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51026]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/CLR:-automatic-boxed-value-pooling-for-s/1323998)._

---
Please take a look on example:

```
var obj1 = (object)true;
var obj2 = (object)true;
Console.WriteLine(ReferenceEquals(obj1, obj2));
```

Currently this code produces `false` (.NET 5.0) signifying that for single `true` Boolean value two boxed objects were created. However in real code it is very beneficial to have pooled objects for small types like `bool` and `bool?`. Sample scenario:

```
// There are millions of 'obj' instances.

...

var annotations = obj. Annotations;

bool? value = (bool?) annotations[key];
if (value == null)
{
   value = SlowCalculationFunction();

// Cache the value for future re-use.
   annotations[key] = value;
}

// Use a calculated 'value' here.
```

What I suggest is that the following code would produce `true`:

```
var obj1 = (object)true;
var obj2 = (object)true;
Console.WriteLine(ReferenceEquals(obj1, obj2));
```

This would allow to achieve a significant memory preservation for some boxed primitive value types.

---
#### Feedback Bot on 1/28/2021, 10:46 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This would break any program that depended on reference equality not being there for boxed value types.  Definitely cannot do.
