### ISSUE TITLE
IntelliSense reporting errors for old c# version 5 and version 6 when build is configured to c# version 7.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51023]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/IntelliSense-reporting-errors-for-old-c/1329262)._

---
[severity:It's more difficult to complete my work]
Trying to use pattern matching in Visual Studio 2019 Pro with c# version 7.3.
The build is configured to use c# 7.3 and builds without errors.
IntelliSense is reporting errors as if it is configured for c#5 but I cannot find a way to change this.

26 @foreach (EntityModel linkedComponent in Model.linkedComponentList)
27 {
28    switch (**linkedComponent**)
29    {
30        case **ProseArticle p**:
31            break;
32
33       default: break;
34     }
35 }

**IntelliSence c# 5 error**
Error	CS8026	Feature 'pattern matching' is not available in C# 5. Please use language version 7.0 or greater.	3_Areas_NetApp_Views_Entity_ProseGroupPlus.cshtml	C:\Users\millc\Source\Repos\netappdotcom\dotcom-be\NetApp.WebApplication\Areas\NetApp\Views\Entity\ProseGroupPlus.cshtml	30	Active
**IntelliSence c# 6 error**
Error	CS0151	A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type in C# 6 and earlier.	3_Areas_NetApp_Views_Entity_ProseGroupPlus.cshtml	C:\Users\millc\Source\Repos\netappdotcom\dotcom-be\NetApp.WebApplication\Areas\NetApp\Views\Entity\ProseGroupPlus.cshtml	28	Active

---
#### Feedback Bot on 2/3/2021, 10:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue. 

The language version is likely being set to a lower version by an item in your project file. Can you post the contents of the project file here, or look for the `<LangVersion>` entry in it?
