### ISSUE TITLE
Should "Mismatched assemblies" MSB3274 be an error instead of a warning?

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#5103]
@Pilchie @jasonmalinowski 

This issue was raised in #5001. We have split that issue in two:
* #5001 tracks the problem that the diagnostic does not show up in the error list.
* This issue tracks the question of whether the diagnostic should be a warning or an error.

**Comment by Pilchie** [comment]
This is a question for msbuild, not us.

**Comment by lgolding** [comment]
I have reported this issue to the MSBuild team. I will let you know their response.

**Comment by rainersigwald** [comment]
MSBuild issue is https://github.com/Microsoft/msbuild/issues/828, if anyone finds this issue first.
