### ISSUE TITLE
C# project's GoToDefinition sets target framework incorrectly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51031]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/C-projects-GoToDefinition-sets-target-/1330927)._

---
[severity:It bothers me. A fix would be nice]
Project A is an SDK project targeting netcoreapp3.1. It references ProjectB that has <TargetFrameworks>net472;netcoreapp3.1</TargetFrameworks>.
Project A calls a method in a class in Project B. When I go to definition of that method, the right file opens; however, all the text is grayed out. That is because the class has #if ! NETFRAMEWORK around its content and the

---
#### Feedback Bot on 2/4/2021, 10:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  We seem to go to the right doc in the right config.
