### ISSUE TITLE
Unexpected definitive assignment error

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#51043]
**Version Used**: 16.9.0 Preview 3

**Steps to Reproduce**:

Compile the following [Code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4EtMwAECcU6ANjANwCwAUPkSWZQEy132OEQfcwB7AMIALOAGMA1oQC8hACzsuAM0IAKACLCxUtYNETJSQgPRNSFGAEpCAMlvELlWXMVX6hTz1mEAjBzhyKDhCXFVNbUM9SKljU3MWGFYbe0dE1hdCAGYAVnc6L285JTpA4I8vCB8sjnooAHdcGHERdQh8gG8Kz3FoEN8QbsLCAAFfADoxgE41ZksrDmGvYBIISUWvXuDCVkGCpdGJ6dmnJIWhwpW4NY3PABM4ZQhLPYPCGBEEAXrCTDgfsbjACiAA9xHAAA4wXACTBqABE8POdAAvvR6MABAJyIQtAZdNxkCYzKECIQQZ0hiCfIpbqMAOzvDBwDgooA===):

```CSharp
int result;
int result2;

int a;
int toCheck = 42;
if (DoCheck(toCheck, out result) && result == 42)
    a = 1;
else if (DoCheck(toCheck, out result2) && result2 == 35)
    a = 2;
else
    a = 3;

switch (a)
{
    case 1:
        System.Console.WriteLine(result);
        break;
    case 2:
        System.Console.WriteLine(result2);
        break;
    default:
        throw new System.Exception("");
}

bool DoCheck(int r, out int x)
{
    x = 42;
    return true;
}
```

**Expected Behavior**:
No error

**Actual Behavior**:
error CS0165: Use of unassigned local variable 'result2'

It is not seen in this case that case 2 is only possible if `DoCheck` was called returned `true` and the value of `result2` was 35.
But I understand very much that it is impossible to catch every case.

**Comment by CyrusNajmabadi** [comment]
Correct. The compiler is behaving exactly as the langauge specifies.  If you have a proposal for how you'd like definite-assignment to be updated to understand this, you'll need to make that proposal over at dotnet/csharplang.  Note: i recommend you start with a discussion over there first.
