### ISSUE TITLE
Cannot set build action to AdditionalFiles in Visual Studio

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#5104]
Currently `AdditionalFiles` is not exposed to the IDE using an `AvailableItemName` item. As a result, attempts to set the **Build Action** to `AdditionalFiles` in the Properties window of Visual Studio will fail. Therefore, the only way to set this build action is to unload the file and manually edit the affected item(s).

This can be resolved by creating an `AvailableItemName` item for `AdditionalFiles`, similar to [this code for the C# target for ANTLR 4](https://github.com/sharwell/antlr4cs/blob/b26ce4d0321cba3661f2f4b316cf97e479ef70fc/runtime/CSharp/Antlr4BuildTasks/Antlr4.net40.targets#L78-L82).

**Comment by mavasani** [comment]
Fixed with an internal change - should be part of next Update

**Comment by mavasani** [comment]
@srivatsn Can you please verify the fix?

**Comment by svick** [comment]
Was this supposed to be fixed in VS 2015 Update 2? Because that's the version I have and I still can't set `AdditionalFiles` from the Properties window.

**Comment by mavasani** [comment]
Seems like the patch authoring for Update2 didn't include Microsoft.CodeAnalysis.Targets. Can you add the following item group to `<%PROGRAM_FILES%\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.Targets` on your machine OR your msbuild project file:

```
  <ItemGroup>
    <AvailableItemName Include="AdditionalFiles" />
  </ItemGroup>
```

**Comment by svick** [comment]
@mavasani Yeah, that does fix the issue for me. Thanks.
