### ISSUE TITLE
Public API to remove unused using directives - missing documentation?

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#51059]
Currently I'm looking for a public API to remove unused using directives.
I found only this "hacky" solution on [stackoverflow](https://stackoverflow.com/questions/44058243/how-can-i-detect-unused-imports-in-a-script-rather-than-a-document-with-roslyn).

In code I found this class: [CSharpRemoveUnnecessaryImportsCodeFixProvider](https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryImports/CSharpRemoveUnnecessaryImportsCodeFixProvider.cs)
But how can I use it?

**Comment by CyrusNajmabadi** [comment]
> Currently I'm looking for a public API to remove unused using directives.

There is no public API for this afaict.  Sorry!

**Comment by CyrusNajmabadi** [comment]
> In code I found this class: CSharpRemoveUnnecessaryImportsCodeFixProvider
But how can I use it?

this is a code fix.  WHich gets exposed through VS's 'suggested action' system.  If you wanted to call into that code actino, that woudl be possibly by querying for suggested-actions, finding the one of interest and then invoking it.  But i would not recommend this as it will likely have several negative effects to the VS UI experience.

--

What you can consider doign is getting the diagnostics the compiler emits to tell us when a 'using' is unused.  And you can then remove those usings with whatever rewrite code you are running.
