### ISSUE TITLE
Debugger shows wrong variable in local function

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#51056]
[Update] Simplified repro: in the following program, set a breakpoint as indicated and run to the breakpoint.
When you inspect `string` parameter `x` of the local function, the debugger instead displays `int` parameter `x` of the containing method.

![image](https://user-images.githubusercontent.com/12466233/107154827-d569fa00-6929-11eb-9fd0-25bf7d41fbf7.png)
The EE test finds an `int` value, rather than a `string` value, which is the problem...

There is a similar problem (EE crash) with variables in local functions that  shadow variables from outer scopes.

I have tests in change https://github.com/jcouv/roslyn/commit/51ab74520d67cd71dfc3e7b046161b680649a847#diff-fa32e027426c7813abc749d453ea346b19fa6b27fe93ff7e7b9725ec0a0069fa which capture the *expected* behavior, but which currently fail. Those can be re-used.

Repro:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        new Program().M(42);
    }

    void M(int x)
    {
        local(string.Empty);
        local2();

        void local(string x)
        {
            GetValue(out var something);
            Console.WriteLine(x); // set breakpoint here and inspect `x` (should display a `string`, not an `int`)
        }

        void local2()
        {
            Console.Write(x);
        }
    }

    void GetValue(out (int a, int b) x)
    {
        x = (42, 43);
    }
}
```

**Comment by tmat** [comment]
I don't think we ever added support to EE or tested local functions. EE supports C# 6 at this point.

**Comment by jcouv** [comment]
I think EE supports local functions already. I see specific code for captured variables and also we have dedicated tests in `roslyn\src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\LocalFunctionTests.cs`

**Comment by tmat** [comment]
Not completely. E.g. you can't call local function from watch/immediate window and there might be other things that do not work. The above class contains 5 tests - seems a bit low.

**Comment by jcouv** [comment]
@tmat I looked at this a bit, but you're right that this is more feature work than bug fix. I'll let the EE team drive this. 
I have some tests that can be a useful starting point (see link in description).

**Comment by jcouv** [comment]
Tagging @tmat @jinujoseph for re-triage

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this issue.
