### ISSUE TITLE
Ensure that yellow-bars shown for crashes in ambiently triggered scenarios only show up once.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#51076]
We should still continue to show the yellow-bar for explicitly invoked scenarios to help ensure the user knows things went wrong and that they won't be getting results.

**Comment by tmat** [comment]
How do you define "once"?

**Comment by sharwell** [comment]
Once per feature per session is the easiest definition.

**Comment by CyrusNajmabadi** [comment]
Will open a PR.  But what i'm thinking is:

If we are going to show hte yellow bar for OOP messages, we keep track if we've already reported the message for that component.  If so, we suppress reporting it again.  This will only be for our oop messages as those are also the ones that have no ability to do things like say "re-enable this feature".   Effectively, because tehre is nothing the user can do, we really only need to show them once per feature in the session.

**Comment by CyrusNajmabadi** [comment]
Working on this now.

**Comment by tmat** [comment]
Not necessarily. Some features may fail only on certain inputs. Say GTD on some symbol crashes, while on any other symbol it will work fine. We do not disable the feature once it crashes today, so you don't need to restart VS to to invoke GTD again. If we show the error once, then it works and then it does nothing, that's not a good experience.

**Comment by tmat** [comment]
I think it would be better if we only deduplicate messages currently being displayed. But that'd likely need to be done by the platform, who owns the gold bar.

**Comment by CyrusNajmabadi** [comment]
>  If we show the error once, then it works and then it does nothing, that's not a good experience. 

Taht's a good point.  We can raise this internally.
