### ISSUE TITLE
Simplify service name specification in ServiceHubService 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#51073]
Before we moved to brokered services the ServiceHubService item's Identity and factory ClassName metadata were unrelated and thus both needed to be specified:

```xml
  <ServiceHubService Include="roslynRemoteHost" ClassName="Microsoft.CodeAnalysis.Remote.RemoteHostService" />
```

However, brokered services have a naming pattern that's significant for the functionality. The Identity has to be `Microsoft.VisualStudio.LanguageServices.{simple-name}` where `IRemote{simple-name}Service` is the remote interface implementing the service. We can therefore simplify the specification to only list the `simple-name` and infer both VS service name and the factory ClassName from it.

Instead of 

```xml
<ServiceHubService Include="Microsoft.VisualStudio.LanguageServices.NavigationBarItem" ClassName="Microsoft.CodeAnalysis.Remote.RemoteNavigationBarItemService+Factory" IsBrokered="true" />
```

we would only write

```xml
<ServiceHubService Include="NavigationBarItem" IsBrokered="true" />
```

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  IF we need to make this change, we should assign to dev/milestone to be done.
