### ISSUE TITLE
Action closure captures unnecessary local variable

### ISSUE THREAD

**Issue by luithefirst** [dotnet/roslyn#51088]
I've found a piece of code in my application that causes a memory leak. From my point, it looks like there is an Action that incorrectly captures a local variable. Here is the smallest example I could find that still produces the issue:

```
public class DataHandler
{
    Action m_callback;
    bool m_callbackEnqueued = false;

    public DataHandler(byte[] data, bool makeAction2)
    {
        m_callback = new Action(() =>
        {
            m_callbackEnqueued = false;
        });

        if (makeAction2)
        {
            var ax = new Action(() =>
            {
                Console.WriteLine("Data: " + data.Length);
            });
            ax();
        }
    }
}

static void Main(string[] args)
{
    var dataHandlers = new List<DataHandler>(10000);
    for (int i = 0; i < 10000; i++)
    {
        var temp = new byte[10000000];
        dataHandlers.Add(new DataHandler(temp, false));
        Thread.Sleep(10);
        GC.Collect();
        Console.WriteLine("Data Created: " + (dataHandlers.Count * 10) + "MB");
    }
}
```

When inspecting the callback created in the constructor of the DataHandler in the debugger it holds '(at)data', while I would expect it to hold a reference to 'this'. 

![image](https://user-images.githubusercontent.com/8556777/107337798-1a716600-6abb-11eb-9025-e2b787bc2fac.png)

When the code that creates the second action, that is guarded by `makeAction2`, is removed, the `_target` of the first Action will be as expected.

I can reproduce this issue by creating a console application with target net48, netcoreapp3.1 or net50. Running it will result in "Out of Memory" after a minute or so. CAUTION: Might crash other applications!

I've installed Visual Studio 2019 16.8.4, NET Core SDK 5.0.102, 3.1.200, and Framework 4.8.03761

My workaround is to create the first action in a helper function, but I suspect that this is a bug and should not be necessary. I would be interested in your insight on this. Thanks!

**Comment by luithefirst** [comment]
Thank you for your answer! Even with your explanation, I still have difficulties compiling the scenario properly in my head.

So why does the second Action affect what is captured by the first? "data" is always part of the local scope of where the first Action is defined. The first action only needs "this" and I'm not sure in what scope it can be thought of living. When I inspect the first Action after the second is removed, I only see a DataHandler and not anything else captured. So why is the local variable "data" not captured when the second Action is removed or replaced by the "Console.WriteLine" that still uses the "data" variable? Does this mean that the declaration of the second Action also puts something in addition to the constructor scope and embeds something that pins "data" so it is then also included in the first Action?

For me, this is kind of would make using actions a bad practice in certain cases, if I think of large procedures where such things might be overlooked. Do you think there is potential for improvement and making closures "tighter"?

**Comment by PathogenDavid** [comment]
> So why does the second Action affect what is captured by the first?

The two lambdas end up sharing the same display class in your example, [it's more obvious when you look at what the compiler actually generates](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMA6AFQAsE4IATASwDsBzAblwOIwBYOdOAZmJpCAEQgwIACQhM6AG0S4A3rkIbuosAH0AxhAULgEPQGt+mwsAD2NhYV0GjJ8wFEmARwCucX3UIAXkIAM0MoOH51TRRhCSlZeSUEAApgAE94AG0AXUI6SQgAGms7B0gzOABBPRgGGyY0AEpojTUcKysnQ2NTMyDCJjgAdy0UlKaggD5WzvbOhcd9HtczDx8/OADgsIUIy0WAXyaojsWGEMIUiura+saWs4X2gGILwhgEX0IAeh/Ccg2FgsJQfSgMKAfGyEKDDBgwPSUKGEADK8AADpQ4EwAOSQgBuiCg91Is0WhHxEAQhAgAA8BkNRiQ0ONJoEZk9yYR5lyFiQAJwpABE8QgIEIQsIAGp8oVSAAZbEsGCUE5ko5qnAvOB7ODqhYZbJ5BQ2ZyigYFKQHXmU6l0hkjMYTab6uau8kC4Wi8WSmUms1yxWsFWa3kaY78bXyC7uzR0ibWzqHWbJnCpzhoQSqWaxbgANmIPEIAFkIMwUiR8LkaQgWFBHlYeQtbbKEnJFESHaN5RCYAAeUWJDsIKYpDD4Cf4UOLEI2akpZgwQgMAb4NjLwh9wjjyfrhhSqUNxZNrkt+BgdFd6yZOBZHeTic5RPky0ydvJKCkKp0OgpRniQoh2SFJz3REpdgiJpp15KgaHoUgUSUOB0THKdn0WABxABhUgsPsJRagTWMNE9EVCkILC4PgOgfWlK5XyAolcJsbwmCXAAqbcpzooViwAISFaCkxTXBDiAA===).

As for why they share a display class, I couldn't tell you for sure. The C# spec doesn't really describe how capturing will be implemented, just how it needs to behave. If I had to guess, the intent here is to avoid the extra allocation for the case where two display classes would've been used. Also if more than one lambda used the same local, [sharing a display class is how they share that local](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMA6AFQAsE4IATASwDsBzAblwOIwBYOdOAZmJpCAEQgwIACQhM6AG0S4A3rkIbuosAH0AxhAULgEPQGt+mwsAD2NhYV0GjJ8wFEmARwCucX3UIAXkIAM0MoOH51TRRhCSlZeSUEAApgAE94AG0AXUI6SQgAGms7B0gzOABBPRgGGyY0AEpojTUcKytmGEIGIMJ8S06NJ0NjUzN+pjgAdy0UlKaggD5Wzvbh4dGXCY8fPzgA4LCFCKHNmIwAThSGAGo7pvPOgF8n3DWukMIUiura+qNFodTbtADEDG+MAQvkIAHo4YRyDYWCwlIQYJQGFAMTZCFAZgwYHpKLjCABleAAB0ocCYAHIcQA3RBQQGkT6bJkQBCECAADyms3mixWnOGGwumxINwARPEICBCLLCHd8oVSAAZOksTHvEFSzoy24PfWGjRvfhguCnODizoZbJ5BQ2ZwK/oFKTPC7c3kCoVzEhoBZLQKrA1SyXmy5yhVKlVql1ujXa1h673m433R4Z4aW3DW+SQ+1WAWLXOEF5rKs4GucNCCVRrWLcABsxB4hAAshBmCkSPhcnyECwoMCrFHOr71Qk5IpWQHCJrsTAADwKxLzhDLFIYfD7/BmzYhGy825MHp9YKDXqEVeEPcHti9U32yc+nkYuBgKmLx1wLJHwPfccgrKxPRkOdkigUgqjoOgUmmOYNygxAUngH8ShOCImiPQ0qBoehSHJJQ4CpXdDzAzQAHEAGFSFo+wlFqcsSxjFJ5UKQhaMI+A6HjVUfggzdoIYmxvAvQgACoH0PQTZS7AAhWU8NeatcBeIA).

**Comment by luithefirst** [comment]
> The two lambdas end up sharing the same display class in your example, [it's more obvious when you look at what the compiler actually generates](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQBgAIUMA6AFQAsE4IATASwDsBzAblwOIwBYOdOAZmJpCAEQgwIACQhM6AG0S4A3rkIbuosAH0AxhAULgEPQGt+mwsAD2NhYV0GjJ8wFEmARwCucX3UIAXkIAM0MoOH51TRRhCSlZeSUEAApgAE94AG0AXUI6SQgAGms7B0gzOABBPRgGGyY0AEpojTUcKysnQ2NTMyDCJjgAdy0UlKaggD5WzvbOhcd9HtczDx8/OADgsIUIy0WAXyaojsWGEMIUiura+saWs4X2gGILwhgEX0IAeh/Ccg2FgsJQfSgMKAfGyEKDDBgwPSUKGEADK8AADpQ4EwAOSQgBuiCg91Is0WhHxEAQhAgAA8BkNRiQ0ONJoEZk9yYR5lyFiQAJwpABE8QgIEIQsIAGp8oVSAAZbEsGCUE5ko5qnAvOB7ODqhYZbJ5BQ2ZyigYFKQHXmU6l0hkjMYTab6uau8kC4Wi8WSmUms1yxWsFWa3kaY78bXyC7uzR0ibWzqHWbJnCpzhoQSqWaxbgANmIPEIAFkIMwUiR8LkaQgWFBHlYeQtbbKEnJFESHaN5RCYAAeUWJDsIKYpDD4Cf4UOLEI2akpZgwQgMAb4NjLwh9wjjyfrhhSqUNxZNrkt+BgdFd6yZOBZHeTic5RPky0ydvJKCkKp0OgpRniQoh2SFJz3REpdgiJpp15KgaHoUgUSUOB0THKdn0WABxABhUgsPsJRagTWMNE9EVCkILC4PgOgfWlK5XyAolcJsbwmCXAAqbcpzooViwAISFaCkxTXBDiAA===).

That's interesting and clearly shows what is happening, thanks! I also don't know a lot of how the compiler handles this, it would be interesting if this is the default behavior or an optimization that results in this. I assume that a lot of thought has been put into the behavior, but hope that this scenario can help to further improve this.

**Comment by jaredpar** [comment]
>  I assume that a lot of thought has been put into the behavior, but hope that this scenario can help to further improve this.

There is a balance here. The compiler can either 

1. Allocate two display classes which means that the scenario results in four allocations (two delegates, two display classes) instead of three (two delegates, one display class)
2. Allocate one display class which means the scenario results in three allocations (two delegates, one display) but has the downside that each of the delegates hold onto the combined state of the display class

In general the compiler will choose the scenario that results in less allocations which is what is happening here.

**Comment by luithefirst** [comment]
@jaredpar Thank you for the summary!

When looking for more information, I found this pull request: https://github.com/dotnet/roslyn/pull/32092, and assume that this is the optimization you are talking about.
