### ISSUE TITLE
Enable EmbedUntrackedSources throughout Roslyn

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#51099]
In order to rebuild Roslyn, we need to be able to access sources generated at build time, such as AssemblyInfo.cs, as well as sources produced by source generators like CSharpSyntaxGenerator.

---

- [ ] Once we update to Arcade 6 we should remove our workaround that sets EmbedUntrackedSources to false: https://github.com/dotnet/roslyn/pull/51353#discussion_r580760118

---

This is a temporary change correct? The idea being that when we are done with this effort that we will be adding this to `Directory.Build.props`? If so are we tracking that in an issue, comment, etc ...?

_Originally posted by @jaredpar in https://github.com/dotnet/roslyn/pull/50968#discussion_r572486869_

**Comment by clairernovotny** [comment]
Does Roslyn use Arcade? I'd expect `EmbedUntrackedSources` to be enabled by default by the top-level Arcade SDK.

**Comment by jaredpar** [comment]
We do use Arcade but we don't use Arcade 5 because it's not LTS. We are still on Arcade 1 (might have been called 3) because it's the only available LTS.

**Comment by RikkiGibson** [comment]
> We are still on Arcade 1 (might have been called 3)

Arcade 1.x is what ships in the .NET 3 Eng channel. https://github.com/dotnet/arcade/blob/release/3.x/eng/Versions.props
Arcade 5.x ships in the .NET 5 channel. https://github.com/dotnet/arcade/blob/release/5.0/eng/Versions.props

I imagine the Arcade maintainers decided to make the version align with the .NET version starting with .NET 5.

**Comment by RikkiGibson** [comment]
Depends on #51647
