### ISSUE TITLE
C# Breaking change diagnosing constraint on static type as type arg in dynamic invocation

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#511]
While fixing #345, I discovered that we had a breaking change. The following code passes the native compiler but fails to compile in Roslyn.

```cs
static class S {}
class C
{
    static unsafe void M()
    {
        dynamic d1 = 123;
        d1.N<S>(); // The dev11 compiler does not diagnose this
    }
    static void Main() {}
}
```

Although the language spec requires a diagnostic here, perhaps Roslyn should also let this pass.

Whichever we do, this should be documented in the compiler spec.

**Comment by gafter** [comment]
Hey compat council: @AnthonyDGreen @DustinCampbell @ljw1004 @MadsTorgersen @gafter @srivatsn @theoy 

We should decide what to do here. FYI I already have a fix prepared as the reversion to dev11 behavior is a natural consequence of my change for #345.

**Comment by AlekseyTs** [comment]
@gafter, do consider this issue addressed?

**Comment by gafter** [comment]
I believe Roslyn is compatible with the native compiler in this area now due to checkin #513, that there is a test for this, and that this is also documented in the compiler spec section of the docs. I didn't realize the bug was not closed. I assigned this to you for verification, please.

**Comment by gafter** [comment]
Closing, as this is fixed. Just needs verification.

**Comment by AlekseyTs** [comment]
Verified
