### ISSUE TITLE
LSP - Validate documents exist in the workspace for text sync handlers

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#51113]
At the moment the text sync handlers don't use the Roslyn workspace or solution at all, for perf reasons, but we should add validation to ensure that the document being tracked is at least known to Roslyn, otherwise we're unnecessarily storing text data.

This should not be done until the platform has fixed the issues around server restarts, or it could just introduce more of them.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this we need to just assign to an appropriate David + milestone and do it :)
