### ISSUE TITLE
Readme.md: https://aka.ms/roslyn-ide-in-progress points to milestone 16.8

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#51118]
https://aka.ms/roslyn-ide-in-progress and https://aka.ms/roslyn-compiler-in-progress used in the readme section [See if your issue is already being worked on!](https://github.com/dotnet/roslyn/blob/master/README.md#see-if-your-issue-is-already-being-worked-on-add-your-own-votes-using-the--reaction) are pointing to milestone 16.8 but should point to milestone 16.9:

**Actual**
https://github.com/dotnet/roslyn/issues?q=sort%3Areactions-%2B1-desc+label%3ABug+is%3Aopen+label%3AArea-IDE+-label%3A%22help+wanted%22+milestone%3A16.8

**Expected**
https://github.com/dotnet/roslyn/issues?q=sort%3Areactions-%2B1-desc+label%3ABug+is%3Aopen+label%3AArea-IDE+-label%3A%22help+wanted%22+milestone%3A16.9

**Comment by JoeRobich** [comment]
@mikadumont @jmarolf who own these links.

**Comment by jmarolf** [comment]
Thanks @MaStr11! I've updated the links!
