### ISSUE TITLE
Update strongly-typed record Equals method

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#51136]
We need to add a short-circuit in the strongly-typed `Equals` method we generate for record equality to ensure that, if the same instance is being compared for equality, we immediately return true. See https://github.com/dotnet/csharplang/issues/39#issuecomment-678097433 for a benchmark of the perf consequences of this. /cc @jcouv.

**Comment by Youssef1313** [comment]
Opened #51149 to address this.
