### ISSUE TITLE
Unit test DebuggerProxy_FrameworkTypes_IEnumerable fails on Mac OS Big Sur v11.2.1

### ISSUE THREAD

**Issue by haacked** [dotnet/roslyn#51132]
**Version Used**: Latest from the `master` branch. Commit: a7db2a1e0c6db4750ce5f24b8c64b7b23d94b2f0

**Steps to Reproduce**:

1. `git clone https://github.com/dotnet/roslyn && cd roslyn`
2. `./build.sh --restore && ./build.sh --build && ./build.sh --test`

**Expected Behavior**:

All the unit tests pass.

**Actual Behavior**:

```
Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests.DebuggerProxy_FrameworkTypes_IEnumerable5ms
Error:
Assert.Equal() Failure
                                 ↓ (pos 24)
Expected: ···erable.RangeIterator(Count = 10)
Actual:   ···erable.RangeIterator { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 }
                                 ↑ (pos 24)

Stack trace:
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests.DebuggerProxy_FrameworkTypes_IEnumerable() in /Users/haacked/dev/third-party/roslyn/src/Scripting/CSharpTest/ObjectFormatterTests.cs:line 451
```

**Comment by davidwengier** [comment]
Thanks for the report.

Looks like our MacOS build is running on Mojave (10.14). Will see if I can follow up on that. I'm not seeing the failure locally on Catalina (10.15) but am seeing a _lot_ of other failures so suspect my machine is not in a great state.

**Comment by tmat** [comment]
I think we should replace this test with a couple of tests that use custom types that have the same debugger attribute as the types returned from `Enumerable.Range` on core and desktop fx. In other word, remove the dependency on the implementation details of `Enumerable.Range`.
