### ISSUE TITLE
SQLitePCL.Batteries_V2.Init() call is throwing exception we don't handle

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#51144]
Seen while debugging:

![image](https://user-images.githubusercontent.com/201340/107594756-91942080-6bc7-11eb-9a08-10830ba038ed.png)

It's throwing a FileNotFound. That catch block is _not_ taken; we eat the exception higher up. If nothing else this means TryInitializeLibraries() is throwing rather than returning a boolean.

Did we upgrade and not correctly deploy it? @CyrusNajmabadi?

**Comment by Youssef1313** [comment]
Why you don't catch and log all regardless of the exception type?

**Comment by NealCallaghan** [comment]
I'm seeing the same sort of file not found exception when using microsoft.data.sqlclient https://github.com/dotnet/roslyn/issues/51054

**Comment by jasonmalinowski** [comment]
@NealCallaghan: that's unrelated.

**Comment by NealCallaghan** [comment]
@jasonmalinowski I'm not so sure, different files and assembles but the exception type and message are exactly the same. FileNotFound could not load file or assembly.

These both happen only in generators, when used in regular runtime code these exceptions don't occur.

There is something going on with generators and referencing assemblies.

**Comment by NealCallaghan** [comment]
@jasonmalinowski I would be interested in seeing the stack trace from the exception.

**Comment by jasonmalinowski** [comment]
The case for this bug has nothing to do with generators; Roslyn uses SQLite as a caching engine and an upgrade went wrong.

**Comment by NealCallaghan** [comment]
@jasonmalinowski I'm sorry I didn't know that. Thank you for sharing.

**Comment by jasonmalinowski** [comment]
@NealCallaghan Not a problem! I just didn't want you getting excited that when we closed this to expect your issue was fixed too.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/51167
