### ISSUE TITLE
Quick action to refactoring Interpolation string to string.Format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51156]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Quick-action-make-Interpolation-string-t/1320533)._

---
<p>this feature is very required for the localization.<br>
Interpolation string cannot work well with localization.<br>
some time we need to wite “key:{0},value:{1}” with string.Format.</p>

---
### Original Comments
(no comments)

**Comment by sharwell** [comment]
It's not clear how the interpolated string is not working with localization. Can you provide a more specific example showing something `string.Format` can do but interpolated string cannot?

**Comment by Flithor** [comment]
uh... well.. `((FormattableString)$"abcd{obj.prop}").GetArguments()` is works well...
