### ISSUE TITLE
C# compiler allows specifying .pack directive with explicit layout control

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/roslyn#51151]
According to the ECMA CLI Spec:

> The .pack directive shall not be supplied for any type with explicit layout control.

[ECMA-335](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf)

**Version Used**: .NET 5.0.2

**Steps to Reproduce**:

Compile the following C# class:

```c#
[StructLayout(LayoutKind.Explicit, Pack = 2)]
public class C
{
    [FieldOffset(0)] public int I;
}
```

**Expected Behavior**:

Either a compile-time error (similar to the error when specifying a `FieldOffsetAttribute` with any `LayoutKind` besides `Explicit`), or IL that doesn't supply the `.pack` directive.

**Actual Behavior**:

No error, and IL that specifies both a `.pack` directive and explicit layout control:

```
.class public explicit ansi beforefieldinit
  C
    extends [System.Runtime]System.Object
{
  .pack 2
  .size 0

  .field [0] public int32 I
...
```

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue. 

That does indeed appear to violate the ECMA 335 spec. In practice though the CLR appears capable of loading the construct. Further this has compiled all the way back to the native C# compiler. Changing the diagnostics at this point would be a pretty significant breaking change as such going to mark this "Won't Fix".
