### ISSUE TITLE
Add compiler flag to implicitly put source generated files in an unsafe context.

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#51154]
A lot of source generators read user written code in order to generate new code.

For example, an EqualityGenerating SourceGenerator would read this:

```csharp
[GenerateEquals]
public partial class A
{
    private int field;
}
```

and generate this:

```csharp
public partial class A
{
    public override bool Equals(object other) => other is A a && field = a.field;
}
```

This causes problems if the user written type requires an unsafe context, e.g:

```csharp
[GenerateEquals]
public partial class A
{
    unsafe private int* field;
}
```

The generated code for this will fail to compile since it's not in an unsafe context:

```csharp
public partial class A
{
    public override bool Equals(object other) => other is A a && field == a.field;
}
```

This means that either every source generator will have to handle such cases themselves (which is unlikely to happen since unsafe is rare), or unsafe types will simply not be able to benefit from source generators.

Perhaps a solution will be to provide a compiler flag in  which all source generated files are considered to be entirely in an unsafe context.

**Comment by YairHalberstadt** [comment]
In my particular use case `StrongInject` would be capable of handling unsafe types without much extra code. However that would require marking all generated classes as unsafe. Detecting when this is required and marking the class unsafe  is more effort than the likelihood of users needing this warrants, and always marking the generated class as unsafe may frighten regular users ("why is my IOC container using unsafe code?"). This means that I just wont bother supporting unsafe code, which is a shame, given that other than creating an unsafe context it's really not much effort at all.

**Comment by jaredpar** [comment]
This is an idea that we discussed and ultimately rejected for source generators. There are a number of customers out there which have strong restrictions on whether or not their applications can include `unsafe` code. The compiler has long guaranteed that this cannot happen unless the compiler is explicitly passed the `/unsafe` flag. Allowing the source generator to do this would break that and it's not something we can realistically do. 

The path forward for this type of source generator is to raise a diagnostic if the project does not have `/unsafe` enabled and ask the customer to do so

**Comment by YairHalberstadt** [comment]
@jaredpar I think you misunderstood the request.

It's a request for the user of a SourceGenerator to say: even though the source generator didn't mark their generated classes as unsafe, treat them as though they were marked as such.

**Comment by HaloFour** [comment]
Couldn't the source generator determine that it required an unsafe context and emit unsafe members?

**Comment by YairHalberstadt** [comment]
@HaloFour 

They certainly could. I expect that the vast majority won't, and since plenty of source generators would just happen to work with unsafe types, although the cost for each source generator is small, the total cost might be high.

**Comment by HaloFour** [comment]
@YairHalberstadt 

I'm curious how many of those source generators would be emitting actual unsafe code and of those source generators that weren't designed specifically to handle unsafe code how many of them are emitting legal code.  IMO I think dealing with unsafe is something that a source generator should probably explicitly opt-in to do.  It's very possible that a lot of source generators will not be written to consider unsafe code, but I think that's more a statement as to how uncommon unsafe code is.

**Comment by CyrusNajmabadi** [comment]
Reactivating.  This is a request for some way to determine if generated members need to add the `unsafe` *modifier*, not the `/unsafe` flag.

**Comment by sharwell** [comment]
This is the kind of scenario that would benefit from a targeted sample. The sample doesn't need to do anything interesting (and probably shouldn't to keep things focused), but should present the various options for correctly handling unsafe code in a source generator.

**Comment by sharwell** [comment]
> It's a request for the user of a SourceGenerator to say: even though the source generator didn't mark their generated classes as unsafe, treat them as though they were marked as such.

This is unnecessary. A source generator that potentially needs `unsafe` members can just mark _every_ generated member as `unsafe`.

**Comment by sharwell** [comment]
I propose that a source generator could account for this case in code generation scenarios as follows:

* If `CSharpCompilationOptions.AllowUnsafe` is true, generate each member with the `unsafe` modifier
* If `CSharpCompilationOptions.AllowUnsafe` is false, generate each member without the `unsafe` modifier

If the above is not sufficient, can you provide a more detailed scenario showing the reason it would not work?

**Comment by YairHalberstadt** [comment]
@sharwell 

For StrongInject I could do that. But the disadvantage of regular users seeing the code and going: "this uses unsafe - why?" isn't worth the advantage of supporting unsafe for those users who might need it.

This is however coming from the other perspective.

A reasonable percentage of normal source generators will just happen to work for unsafe code (assuming that the generated code is marked unsafe). Of those that wouldn't, you would probably get a compiler error, rather than something blowing up at runtime. However only a tiny percentage will actually mark their classes as unsafe.

As such by having a way for a user to say: ignore unsafe contexts, let's just see if this source generator happens to work when I write unsafe code will open up a large number of source generators to working for users who write unsafe code.

**Comment by sharwell** [comment]
> But the disadvantage of regular users seeing the code and going: "this uses unsafe - why?" isn't worth the advantage of supporting unsafe for those users who might need it.

The original proposal above does not address this case (it hides the `unsafe` modifier even in cases where it was needed).

> As such by having a way for a user to say: ignore unsafe contexts, let's just see if this source generator happens to work when I write unsafe code will open up a large number of source generators to working for users who write unsafe code.

If a source generator produces code that requires an `unsafe` modifier but did not provide it, a reasonable assumption is the code did not correctly handle the semantics of the unsafe operation and suppressing the compiler error would lead directly to a runtime error (likely difficult to reproduce and potentially a security bug).
