### ISSUE TITLE
Edit.ParameterInfo should display Generics bounds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51157]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/EditParameterInfo-should-display-Generi/1325878)._

---
I would expect the tooltip of Edit.ParameterInfo to display `where ` bounds if any, but it does not.

For instance,
```csharp
class Lib 
{
        static T[] EnumValues<T>() where T: Enum
        {
            return (T[])Enum.GetValues(typeof(T));
        }
}
```

When typing `EnumValues(` and triggering Edit.ParameterInfo, the tooltip content is `T[] Lib.EnumValues<T>()` while it could be the more precise `T[] Lib.EnumValues<T>() where T: Enum `

---
#### Feedback Bot on 6/17/2019, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jinu Joseph [MSFT] on 6/23/2019, 11:51 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 8/7/2019, 06:34 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .
#### Nathan Moreau [MSFT] on 8/8/2019, 01:55 AM: 

<p>this likely won't solve itself.</p>

#### Feedback Bot on 2/1/2021, 00:37 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
