### ISSUE TITLE
"Go to all" with unix-style paths

### ISSUE THREAD

**Issue by MartyIX** [dotnet/roslyn#51165]
**Version Used**: MSVS 2019 preview 4, community version

**Steps to Reproduce**:

1. Press `ctrl + ,` to open "Go to all"
2. Copy file path from Github where paths are in form "folder/subfolder/file.cs"

**Expected Behavior**:

File `file.cs` is suggested as it is found.

**Actual Behavior**:

File `file.cs` is not found. However, when I change forward slashes to backward slashes. The file is found correctly.

**Comment by CyrusNajmabadi** [comment]
@olegtk can you please route to editor (or whoever owns nav bar searching for file paths)?  thanks!

**Comment by olegtk** [comment]
I don't actually know how to route GitHub issues, @jinujoseph please route it (and if you like show me how so I won't bother you every time). Thanks!

**Comment by jinujoseph** [comment]
routed to [editor](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1278032)

**Comment by v-zhuye** [comment]
Hi @MartyIX, I cannot reproduce this problem with below steps, can you help to correct me if I misunderstand this problem or miss any important steps?

**Reproduce Steps:**
1. Launch VS.
2. Press 'Ctrl+,' to invoke 'Go to All'.
3. Paste below are path in the search box.
https://github.com/aspnet/samples/blob/master/samples/aspnetcore/blazor/FlightFinder/FlightFinder.Server/Controllers/AirportsController.cs

**Actual Result:**
File 'AirportsController.cs' is not found. When I change the area path to https://github.com\aspnet\samples\blob\master\samples\aspnetcore\blazor\FlightFinder\FlightFinder.Server\Controllers\AirportsController.cs, the file is still not found.

**More info:**
If I clone the repository and open FlightFinder.sln, then search 'FlightFinder.Server/Controllers/AirportsController.cs', file 'AirportsController.cs' is suggested as it is found.

**Comment by MartyIX** [comment]
@v-zhuye: You are right. I can't repro the issue anymore. Sorry for wasting your time.

However, the following images show that 'Go to All' behaves slightly differently for different path separators:

![image](https://user-images.githubusercontent.com/203266/108492067-fe34ac80-72a4-11eb-86d3-fe94aba48c8e.png)

![image](https://user-images.githubusercontent.com/203266/108492122-10164f80-72a5-11eb-92c1-fb2ac3800d64.png)

I'm not sure whether it is by design or not.

**Comment by MartyIX** [comment]
This shows the original issue:

![image](https://user-images.githubusercontent.com/203266/108625487-82289900-744b-11eb-96f5-345775a71343.png)
![image](https://user-images.githubusercontent.com/203266/108625510-98cef000-744b-11eb-8596-f8f56bd1870c.png)

**Comment by MartyIX** [comment]
@v-zhuye Does this help?

**Comment by olegtk** [comment]
@gundermanc

**Comment by v-zhuye** [comment]
@MartyIX Yes it helps, thank you for your patience and providing screenshots.

**Comment by MartyIX** [comment]
@v-zhuye Hi Juliet, is there any progress on this issue? Or anything I can help with? I encounter the issue daily :-)

**Comment by olegtk** [comment]
@MartyIX can you please check if the issue is fixed in 17.0 Preview3 that was just released? We made a lot of improvements to GoTo, mostly for perf, but this one is likely fixed too. Thanks!

**Comment by MartyIX** [comment]
@olegtk Yes, I use 17.0 Preview3 every day and unfortunately, it is still not fixed.

**Comment by olegtk** [comment]
@gundermanc (this is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1278032)

**Comment by gundermanc** [comment]
@olegtk I haven't taken a look at this yet but it looks like it's marked 17.0 Preview 4.

**Comment by MartyIX** [comment]
@gundermanc I use 17.0 (and even 17.1 Preview) every day and unfortunately, it is still not fixed.

**Comment by MartyIX** [comment]
Just FYI, 17.3 Preview still behaves the same. :(

**Comment by olegtk** [comment]
Still active issue, sorry. I suggest you file it through Help/Send Feedback/Report a Problem - that would create publicly visible feedback ticket and allow other users to vote on it too.
