### ISSUE TITLE
Move type to file duplicates assembly level attributes

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#51164]
**Version Used**:  16.9.0 P3

**Steps to Reproduce**:

```C#
using System.Reflection;

[assembly: AssemblyCulture("")]

namespace TestNS
{
    public class TestClassA { }
    public class TestClassB { }
}
```

Execute _Move type to TestClassB.cs_ refactoring on `TestClassB`.

**Expected Behavior**: The _TestClassB.cs_ to not have any assembly level attributes.

**Actual Behavior**: The attribute is now duplicated in both files.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/55900
