### ISSUE TITLE
[SUGGESTION] Wiki-style Reference Links in Comments : Microsoft Visual Studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51160]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SUGGESTION-Wiki-style-Reference-Links-/1303728)._

---
Dear VS Developers,

**PROBLEM**
Too many comments clog up the code.

**SOLUTION**
Wikipedia style reference links.

Is it possible to add links in the comments so that other developers could just link to the comments?

If you refer to the example below, I am suggesting that [1][2][3] would jump to the respective [1][2][3] comments below, similar to Wikipedia.

At the moment, it's just text.

This suggestion can also integrate with a comment overlay for code review in the future.

You can change [1][2][3] to [Alice][Bob][Charles] to see their specific comments on code

```cpp
#include <iostream>

class A
{
private:
	int m_x;
public:
	A(int x) 
		: m_x(x)
	{
		if (x <= 0)
			throw 1;
	}
};

class B : public A
{
public:
	B(int x) try //[1]
		: A( x )
	{}

catch(...) //[2][3]
	{
		std::cerr << "Exception caught\n";
	}
};

int main()
{
	try
	{
		B b(0);
	}
	catch (int)
	{
		std::cout << "Oops\n";
	}
}

//[1] “try” keyword before the member initializer list.
//This indicates that everything after that point(until the end of the function) should be considered inside of the try block.

//[2] Associated catch block is at the SAME indentation as the entire function.
//Any exception thrown between the try keyword and the end of the function body will be eligible to be caught here.

//[3] Throw or rethrow an exception.
//Unlike normal catch blocks, which allow you to either resolve an exception, throw a new exception, 
//or rethrow an existing exception, with function - level try blocks, you must throw or rethrow an exception.
//If you do not explicitly throw a new exception, or rethrow the current exception(using the throw keyword by itself), 
//the exception will be implicitly rethrown up the stack.
```
---
### Original Comments
(no comments)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
