### ISSUE TITLE
Requests for the "inline parameter name hints" feature

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51161]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Requests-for-the-inline-parameter-name-/1304226)._

---
I really like the "inline parameter name hints" experimental feature, and I see that there are some additional features coming for it (great).
Here are a couple of suggestions from my POV:
1. To encourage clarity of code, allow the hint itself to be double-clicked, to insert the corresponding hint in as an actual named parameter. This way, users who want their code to be readable outside of the VS editor can easily insert those parameter names.
2. Allow methods to specify an attribute [NoParameterHint("v", "x")] to prevent the hint from showing where it's obvious. It would be an extra filter in cases where API developers have taken the time to indicate this hint is not required.
3. Put in a placeholder hint that's just `:` where the hint is filtered-out/unnecessary. That small amount of real-estate would allow users to hover and see the same information that's shown on the hint (parameter type/name/description), without using Ctrl-Shift-Space to see the parameter definition. _It would also allow double-click insertion per point 1 above._

---
#### Feedback Bot on 1/7/2021, 11:14 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### David McCarter on 2/2/2021, 09:47 AM: 

<p>I agree with Jerry. My biggest suggestion is to make it easy to have VS auto-add the parameter names if a well-named variable isn’t used. Like this:</p>
<p><img src="https://aka.ms/dc/image?name=Bbd6cbd91ffe84d2da078cdd7441c8c39637478847923503716_Screen_Grab2.jpg&amp;tid=bd6cbd91ffe84d2da078cdd7441c8c39637478847923503716" alt="Screen Grab2.jpg"></p>
<p>Should just turn into this:</p>
<p><img src="https://aka.ms/dc/image?name=B3a6674b0d7104384968ece46c700392a637478848129522642_Screen_Grab3.jpg&amp;tid=3a6674b0d7104384968ece46c700392a637478848129522642" alt="Screen Grab3.jpg"></p>
<p>This should also apply to Attributes too.</p>

**Comment by Youssef1313** [comment]
Copying the images that doesn't render in this GitHub issue:

![image](https://user-images.githubusercontent.com/31348972/107683043-c678a400-6ca9-11eb-8206-9693254e4e07.png)

---

![image](https://user-images.githubusercontent.com/31348972/107683056-cbd5ee80-6ca9-11eb-9e42-ed885e2af83b.png)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
We already support a code action to insert named params.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi the request is to execute that code action by clicking the inline hint.

**Comment by CyrusNajmabadi** [comment]
I understand :)  I'm saying that i don't think we necessarily need that as we already have a feature to do this.

**Comment by CyrusNajmabadi** [comment]
We added this thanks to @akhera99 .  Closing out.
