### ISSUE TITLE
Add quick commented out code block removal

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51179]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-quick-commented-out-code-block-remov/1325353)._

---
It would be good to be able to remove commented out lines of code in classes. This could have rules such as if there are over x number of lines or if they are not prefixed with something, but the ability to remove blocks of old code without deleting it would be great

---
#### Feedback Bot on 1/31/2021, 10:44 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
On Design meeting to evaluate the prioritization of this feature and general feedback on it

**Comment by ryzngard** [comment]
Design Discussion: This is a complex feature without a clear definition of what "commented code" would mean. As of now this does not meet the bar for consideration.
