### ISSUE TITLE
Review if root children can be asserted to be labelled in statement syntax comparisons

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#51174]
See [this comment thread](https://github.com/dotnet/roslyn/pull/51086#discussion_r574003127):

> @tmat yesterday
> ```
> Debug.Assert(HasLabel(node));
> ```
> 
> When is this not true? It'd odd because I'd think the tree diffing alg is only operating on labeled nodes and this should only be called from the alg.

> @davidwengier 17 hours ago
> Same reason as #51021 (comment), essentially there is no assumption/assertion that the root children are labelled for statement syntax.
> 
> Could add the _compareStatementSyntax to the assert if you'd prefer?

 
> @tmat 1 hour ago 
> Yes, I think we should apply the same assertion for statement level. LMK if anything fails doing so.

> @davidwengier 11 seconds ago
> Oops, sorry, missed this. Will file a follow up, there are lots of tests that fail with this assertion, but we can possibly move the check to CSharpEditAndContinueAnalyzer and have it only provide root children that are labelled.

**Comment by davidwengier** [comment]
Looked at this, and I don't think this is worth fixing. Take the following example:

```
F(a => G(b => H(c => I(d))));
```

When analyzing the body for the lambda with parameter `a`, it has one child which is an InvocationExpression, which is unlabelled, so would fail the assert. If we change `CSharpEditAndContinueAnalyzer.ComputeBodyMatch` to not specify unlabelled child nodes, then it would specify no child nodes so that won't work as we need to descend into child nodes to see the lambda with parameter `b`.

We could change the analyzer to descend into children until it sees at least one labelled child, and then pass that child and all of its labelled siblings in as root children, I'm just not sure its worth it, when the comparer is already descending anyway.

Thoughts @tmat?

**Comment by tmat** [comment]
Make sense, then perhaps let's remove the HasChild requirement for top-level as well.

**Comment by tmat** [comment]
The parent checking assert also does not work for statement level? That would be odd.

**Comment by davidwengier** [comment]
This is being done as part of further combining the comparers for #51169
