### ISSUE TITLE
[LSP] Cache completion request context

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51182]
Similar to what [Razor is doing](https://github.com/dotnet/aspnetcore-tooling/commit/11d092cc53c4cb15980f36e1b2e8a2c3e61fa335#diff-3fced932af243ffa3d83efddd293f672d7f6d322551a041de65807de4c53b1bdR14), we should consider caching the request context in LSP completion to reduce the size of the data payload. This should hopefully make completion performance faster.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
