### ISSUE TITLE
Invoking rename tracking fix on VS for Mac gives error

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#51194]
@davidwengier saw this while doing some testing:

![image](https://user-images.githubusercontent.com/201340/107809373-d632cf80-6d1f-11eb-9d72-9177f4611df4.png)

That string comes from Roslyn here:

https://github.com/dotnet/roslyn/blob/7d3f07cc2a4c96c217f32b214f7ccbdc91759196/src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.RenameTrackingCodeAction.cs#L82-L83

**Comment by davidwengier** [comment]
Repro steps were to load a large project (eg, VS for Mac or OrchardCore were two I tried) and change the name of a class and execute the rename code action.

**Comment by CyrusNajmabadi** [comment]
Closing out as vs4mac is not a thing anymore.
