### ISSUE TITLE
.globalconfig doesn't follow the correct precedence

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#51225]
**Version Used**: 

Compiler version: '3.9.0-4.21071.28 (b3145437)'. Language version: 9.0.

**Steps to Reproduce**:

1. Create a csproj with following contet:

    ```xml
    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <RootNamespace>repro_4732</RootNamespace>
      </PropertyGroup>

    </Project>
    ```

2. Add a code to Program.cs that violates CA1309, for example:

    ```csharp
    using System;

    namespace repro
    {
        public class Class1
        {
            public bool Equals(string a, string b)
            {
                return string.Equals(a, b);
            }
        }
    }
    ```

3. Create a `.globalconfig` file with the following content:

    ```ini
    is_global = true

    dotnet_analyzer_diagnostic.category-Globalization.severity = warning
    dotnet_diagnostic.CA1309.severity = suggestion
    ```

**Expected Behavior**:

No warnings. The `.globalconfig` files should follow the same precedence rules as `.editorconfig` files.

**Actual Behavior**:

> warning CA1309: Use ordinal string comparison

**Additional information**:

This doesn't reproduce with `.editorconfig`.

FYI @mavasani

**Comment by mavasani** [comment]
@chsienki
