### ISSUE TITLE
New line setting for C# "with" expression is missing

### ISSUE THREAD

**Issue by Xenoage** [dotnet/roslyn#51229]
In "Tools -> Options -> Text Editor -> C# -> Code Style -> Formatting -> New Lines -> New line options for braces" there is no checkbox for "Place open brace on new line for with expression", and no other settings seems to apply for this scenario:

Visual Studio now formats the with expression as follows.

```c#
var newRecord = oldRecord with
{
    Prop = 1
};
```

What I'd like to see is:

```c#
var newRecord = oldRecord with {
    Prop = 1
};
```

**Comment by Youssef1313** [comment]
This should have been already fixed with https://github.com/dotnet/roslyn/pull/50274.

The fix should be available in a next release.
