### ISSUE TITLE
Granular Source Generator APIs

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#51257]
In Roslyn 3.10 we're aiming to ship a preview of a more granular source generator API that will allow for better IDE performance by breaking the generation up into multiple, independent 'steps'.

We will use this issue as an umbrella to track overall progress on those APIs and their current status.

Doc: https://github.com/dotnet/roslyn/pull/52847 ?

**Comment by maxkoshevoi** [comment]
As mentioned here: https://github.com/dotnet/roslyn/pull/52847#discussion_r618900898
Why not call `IncrementalValueSourceExtensions.Filter` `Where`?
