### ISSUE TITLE
Quick Actions inserting static for using directive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Quick-Actions-inserting-static-for-using/1338794)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.9 Preview 3]
When using "Quick Actions" to fully qualify a Type in a using alias directive it has started incorrectly inserting the word "static" 

example 

we type 
`using ContactPointTasks				= Task<IMessagingContactPoint[]>`
and navigate to Task and choose to fully qualify Task.

It incorrectly inserts a static on top of fully qualifying and produces the below code which results in "**Error	CS8085	A 'using static' directive cannot be used to declare an alias**	" 

`using static ContactPointTasks				= System.Threading.Tasks.Task<IMessagingContactPoint[]>`

instead of 

`using ContactPointTasks				= System.Threading.Tasks.Task<IMessagingContactPoint[]>`

---
#### Feedback Bot on 2/14/2021, 04:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
In general, i'm not a big fan of a quick action just to insert a word.  We already have an easy way to insert a word: just use 'completion'.  Quick actions are beneficial when the effort to expend doing it manually is higher, or there is a need to do a lot of it.  That would not be the case here.  Indeed, it's a bit of a weird situation to end up.  You would only have this by fully typing out `using x = SomeType;` and you didn't write `static`.  But since you're right there, just fixing things up would be trivial.

**Comment by DeRiderConsultingServices** [comment]
> In general, i'm not a big fan of a quick action just to insert a word. We already have an easy way to insert a word: just use 'completion'. Quick actions are beneficial when the effort to expend doing it manually is higher, or there is a need to do a lot of it. That would not be the case here. Indeed, it's a bit of a weird situation to end up. You would only have this by fully typing out `using x = SomeType;` and you didn't write `static`. But since you're right there, just fixing things up would be trivial.

Could you please re-read the OP. 

The bug is going from using Alias = NotFullyQualifiedType 
Quick Action of Fully Qualify Type (something already implemented) fully qualifies it and then ALSO IS NOW incorrectly inserting the word "static" generating non-compiling code.

**Comment by CyrusNajmabadi** [comment]
Gotcha :)  Thanks i misread.
