### ISSUE TITLE
Typing to the left of the continuation '.' in Repl inserts text backwards...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5130]
1.  Open C# Interactive
2.  Press Shift + Enter
3.  Hit left arrow twice (move cursor before the '.') **<- You shouldn't be able to do this!**
4.  Type "abc"

**RESULTS:**
![capture](https://cloud.githubusercontent.com/assets/6464209/9797608/e9a53fd8-57b0-11e5-81f7-372e047206b8.PNG)

**Comment by tmat** [comment]
Re 3) - why shouldn't you be able to do that? It's an editor buffer, you should be able to freely move the caret anywhere in it. Otherwise how would you select text including prompts?

When the user starts typing in read-only region we should move the caret to the closest read-write region.

**Comment by KevinH-MS** [comment]
I see.  I guess I expect prompt margin. :smile:

Anyway, I guess that's not the design.  Trying this will a normal ```>``` prompt, I see that you can move the cursor, but typing doesn't insert any text.  We should at least do that.

**Comment by tmat** [comment]
The design is to move the caret to the closes read-write region :)

**Comment by genlu** [comment]
Fixed by https://github.com/dotnet/roslyn/issues/5339
