### ISSUE TITLE
Implement Interface handles nullability incorrectly for structs in generic interfaces

### ISSUE THREAD

**Issue by magnusbakken** [dotnet/roslyn#51305]
**Version Used**:
Visual Studio 16.8.3

**Steps to Reproduce**:
Add the following code to a file in an empty project:

    public struct S { }

    public class C : IEqualityComparer<S>
    {

    }

Now use the Implement Interface feature on IEqualityComparer.

**Expected Behavior**:

I would expect the generated method signatures to be simply:

    public class C : IEqualityComparer<S>
    {
        public bool Equals(S x, S y) => throw new System.NotImplementedException();
        public int GetHashCode(S obj) => throw new System.NotImplementedException();
    }

**Actual Behavior**:
The behavior differs depending on the target framework of the containing project. Nullable=enable does not seem to be relevant.

For net5.0 the output is as follows:

    public class C : IEqualityComparer<S>
    {
        public bool Equals(S? x, S? y) => throw new System.NotImplementedException();
        public int GetHashCode([DisallowNull] S obj) => throw new System.NotImplementedException();
    }

For netcoreapp3.1 it looks like this:

    public class C : IEqualityComparer<S>
    {
        public bool Equals([AllowNull] S x, [AllowNull] S y) => throw new System.NotImplementedException();
        public int GetHashCode([DisallowNull] S obj) => throw new System.NotImplementedException();
    }

And for 4.8 it does what I would expect all of them to do:

    public class C : IEqualityComparer<S>
    {
        public bool Equals(S x, S y) => throw new System.NotImplementedException();
        public int GetHashCode(S obj) => throw new System.NotImplementedException();
    }

The net5.0 version doesn't even compile, because `bool Equals(S?, S?)` can't implement `bool Equals(S, S)`. The netcoreapp3.1 version compiles, but the [AllowNull] and [DisallowNull] attributes seem unnecessary.

** Demonstration **
![equality-comparer-analyzer-problem](https://user-images.githubusercontent.com/284189/108356796-e0a40c00-71ec-11eb-86c9-147c5b382efe.gif)

**Comment by magnusbakken** [comment]
I've discovered that this a duplicate of #49019, which is already fixed, so I'll close.

**Comment by jasonmalinowski** [comment]
@magnusbakken The fix associated with that bug would have been present in 16.8.3 though, so something else is up?

**Comment by magnusbakken** [comment]
Okay, maybe. I actually tried to write a test case in ImplementInterfaceTests.cs on the master branch and I couldn't reproduce it there. I think this test case that was added for #49019 is the exact same thing as what I have: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs#L8756

**Comment by magnusbakken** [comment]
I've upgraded to VS 16.9, and tested this again. The output when targeting .NET 5 with Nullable=enable is now

    public class C : IEqualityComparer<S>
    {
        public bool Equals(S x, S y) => throw new System.NotImplementedException();
        public int GetHashCode([DisallowNull] S obj) => throw new System.NotImplementedException();
    }

...which at least compiles. I'm not sure I understand why it's putting DisallowNull on GetHashCode but not AllowNull on Equals, but I guess it doesn't do any harm.

**Comment by CyrusNajmabadi** [comment]
> ...which at least compiles. I'm not sure I understand why it's putting DisallowNull on GetHashCode but not AllowNull on Equals, but I guess it doesn't do any harm.

The reason for this is just that that's the nature of the API:

![image](https://user-images.githubusercontent.com/4564579/153507570-ecf3fbe1-f091-4364-ae86-70e1beeead17.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as fixed.
