### ISSUE TITLE
Where does Intellisense get its data when targeting more than one framework

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/roslyn#51311]
I've updated my class library project from targeting .NET Standard 2.0 to now targeting both .NET Standard 2.0 and .NET 5.0. This seems to be working as expected.

However, Intellisense appears to have chosen to get its information from the .NET Standard 2.0. For example, where `ToString()` now returns `string?`, Intellisense shows it returns type `string`. Further, if I choose *Go To Definition* for a framework method, it shows me the signature for the method in .NET Standard. If I change my project so that I target *only* .NET 5.0, then Intellisense shows me the .NET 5.0 information.

Is there any way to tell Intellisense to instead show me the information from .NET 5.0 when I'm targeting multiple frameworks?

**Comment by Youssef1313** [comment]
@SoftCircuits You can find a drop-down near the top-left which has the project name followed by a parentheses containing the target framework. You can change it from there.

In addition to that, you'll be warned when you use an API that's not available in all TFMs, like the following:

![image](https://user-images.githubusercontent.com/31348972/108414866-6a77c780-7235-11eb-8474-2686169cdfe1.png)

**Comment by SoftCircuits** [comment]
@Youssef1313 : Thanks! I completely missed that. Although, I did find out Intellisense will default to whichever framework is listed first in your `<TargetFrameworks>` element.

**Comment by Youssef1313** [comment]
Yes I think the first will be the default, which you can change when necessary.
