### ISSUE TITLE
Adding Semicolon to end of line causes the whole line to jump to the left

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51314]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Adding-Semicolon-to-end-of-line-causes-t/1338476)._

---
[severity:It bothers me. A fix would be nice]
While writing code on VS 2019 I have been plagued with an issue for a long time. When writing a line of code and adding a semicolon to the end of that line it causes the entire block of code to jump out of format. I've gone looking through the settings to try and fix it with no luck. Any help is appreciated. Pictures attached for illustration of the problem.

*Format is Fine*

![image](https://user-images.githubusercontent.com/1408396/108410866-cbbf7c80-71dc-11eb-95b4-e297c81923fb.png)

*After adding Semicolon*

![image](https://user-images.githubusercontent.com/1408396/108410884-d24df400-71dc-11eb-8ce2-de2934988e1b.png)

---
#### Feedback Bot on 2/13/2021, 04:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/17/2021, 10:19 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I have not been able to reproduce this so far.

**Comment by Youssef1313** [comment]
Could this behavior result from a bad configuration of indent_size in editorconfig and/or other VS setting?

**Comment by Youssef1313** [comment]
I could reproduce with incorrect settings:

![image](https://user-images.githubusercontent.com/31348972/109110410-bfd53c80-773f-11eb-83a0-9059af6978e3.png)

Can't think of other reason to cause this.

**Comment by sharwell** [comment]
Based on the comment from @Youssef1313 , this appears to be related to #50063 and #43189. The formatter should be using the opening `{` of `Random()` as the base token for indentation, _even if that token is placed incorrectly_.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and niche scenario.
