### ISSUE TITLE
Sort usings command doesn't support #if preprocessor directive

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51339]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Sort-usings-command-doesnt-support-if-/1341873)._

---
[severity:It's more difficult to complete my work]

Visual Studio doesn't sort my usings when there's a using inside an #if directive. I want to sort the non-conditional usings, and don't care that much about the ordering of the usings inside the #if.

```
using B;
using A;

#if NETFRAMEWORK

using C;

#endif
```

Expected outcome:
```
using A;
using B;

#if NETFRAMEWORK

using C;

#endif
```

Actual outcome:
(nothing changed).

Note that there are similar reports about "Remove and Sort Usings" (e.g. https://github.com/dotnet/roslyn/issues/24084) where Visual Studio removes `using`s that are only used conditionally and the suggested workaround is to move those usings inside an `#if`-directive. When following that workaround one runs into this issue where "Sort Usings" stops working because of those `#if`-directives.

---
#### Feedback Bot on 2/18/2021, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Related to #44103

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
