### ISSUE TITLE
IntelliSense not suggesting available extension method

### ISSUE THREAD

**Issue by jbevain** [dotnet/roslyn#51356]
**Version Used**: 

Verified on:

3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c

**Steps to Reproduce**:

1. `dotnet new classlib -f netstandard2.0`
2.

Change code to:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

namespace Library
{
    public class Client
    {
        public Client(Socket socket)
        {
            
        }
    }
}
```

3. In the `Client` constructor, input `socket.ConnectA`

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/79284/108578800-d3644b80-72d8-11eb-8d9c-b71ac9dca1b1.png)

IntelliSense doesn't suggest the task based `ConnectAsync` extension methods. Note that the necessary namespace is imported.

However, if you just use it by passing the proper arguments, the code compiles and Visual Studio is happy to resolve the extension method.

![image](https://user-images.githubusercontent.com/79284/108545722-025ccc00-729d-11eb-9d2a-32a430ed5839.png)

**Expected Behavior**:

IntelliSense lists and displays the task based ConnectAsync extension methods.

**Comment by genlu** [comment]
So tooltip correctly included the extension methods, but signature help and completion don't. Investigating 

![image](https://user-images.githubusercontent.com/788783/108791990-24707b80-7535-11eb-932e-78d3d08c1297.png)

**Comment by genlu** [comment]
Ah, this is why it's not shown in completion, it's set to `EditorBrowsable.Never`. So it's actually a bug for quickinfo to not respect this attribute.

![image](https://user-images.githubusercontent.com/788783/108795698-c98e5280-753b-11eb-8c81-18855b0c4c4a.png)

**Comment by genlu** [comment]
@jbevain Closed as by design. If you want them to show in VS, you have to request a change to the value of EditorBrowsableState with corefx team.

**Comment by jbevain** [comment]
@genlu thanks for the quick sanity check. Completely forgot to check that before filing, thank you!
