### ISSUE TITLE
Infinite loop in SuppressMessageAttributeState.Resolve

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#51386]
**Version Used**: Microsoft.CodeAnalysis.dll 3.700.20.51401

**Steps to Reproduce**:

1. Feed it (indirectly, by `GlobalSuppressions.cs`) something like `[assembly: SuppressMessage("Performance", "RCS1242:Do not pass non-read-only struct by read-only reference.", Justification = "Idiotic", Scope = "namespace", Target = "abcdef")]`. Unknown if the actual source code analyzed needs to be malformed or not, but in this case it is.
2. Get the subject code invoked somehow.
3. Watch as it never terminates that eternal `while (true)`.

**Expected Behavior**:
Terminating that loop, preferrably before the sun burns out.

**Actual Behavior**:
Not terminating that loop (until the CPU burns out) while this+other threads combined consumes 90% CPU (across all cores, where one could speculate it might only be the slowness of IPC preventing it from reaching 100%).

<details>
<summary>Call-stack</summary>
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.TargetSymbolResolver.Resolve(out bool resolvedWithDocCommentIdFormat) Line 95	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ResolveTargetSymbols(Microsoft.CodeAnalysis.Compilation compilation, string target, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.TargetScope scope) Line 340	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.DecodeGlobalSuppressMessageAttributes(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.GlobalSuppressions globalSuppressions, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.AttributeData> attributes) Line 315	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.DecodeGlobalSuppressMessageAttributes(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.GlobalSuppressions globalSuppressions) Line 287	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.DecodeGlobalSuppressMessageAttributes() Line 238	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.IsDiagnosticSuppressed(Microsoft.CodeAnalysis.Diagnostic diagnostic, System.Func<Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.SemanticModel> getSemanticModel, out Microsoft.CodeAnalysis.Diagnostics.SuppressMessageInfo info) Line 148	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState.ApplySourceSuppressions(Microsoft.CodeAnalysis.Diagnostic diagnostic, System.Func<Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.SemanticModel> getSemanticModel, Microsoft.CodeAnalysis.ISymbol symbolOpt) Line 113	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.FilterDiagnosticsSuppressedInSource(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic> diagnostics, Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.Diagnostics.SuppressMessageAttributeState suppressMessageState, System.Func<Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.SemanticModel> getSemanticModel) Line 899	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.FilterDiagnosticsSuppressedInSourceOrByAnalyzers(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic> diagnostics, Microsoft.CodeAnalysis.Compilation compilation) Line 865	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalysisResultBuilder.ApplySuppressionsAndStoreAnalysisResult(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Compilation compilation, System.Func<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerActionCounts> getAnalyzerActionCounts, bool fullAnalysisResultForAnalyzersInScope) Line 87	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken) Line 950	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync.AnonymousMethod__1() Line 787	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 980	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 928	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#
 	[Native to Managed Transition]	
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
</details>

As food for thought, maybe infinite loops like that could require slightly more careful code-review, test-cases and testing procedures. Just an idea.

**Comment by jmarolf** [comment]
@mavasani I think you looked at this code most recenty?

**Comment by jasonmalinowski** [comment]
@mavasani Any idea if we fixed something like this at some point? Also, who actually owns this code between IDE and Compiler?

**Comment by mavasani** [comment]
Yes, should be fixed with https://github.com/dotnet/roslyn/pull/47748
