### ISSUE TITLE
Don't look up completion properties using hardcoded strings

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51396]
See https://github.com/dotnet/roslyn/pull/51166/files#r579447709.
In #51166, support was added for override and partial method completions in LSP. The current approach involves looking up information in the completion item's properties via hardcoded strings. This approach is very fragile and we should find an alternate solution.

**Comment by CyrusNajmabadi** [comment]
Note: it's fine for an indvidual completion provider to look up properties it knows it has stored.  This is a correct utilization of the property bag.  What is not ok is external consumers taking a dependency on the property bag contents.  THis will not work and breaks the encapsulation of the completion provider.
