### ISSUE TITLE
Assignment via 'is not' should also work if the type of the assigned variable is the same type as the checked variable 

### ISSUE THREAD

**Issue by JankoR2** [dotnet/roslyn#51391]
**Version Used**: VS 16.8.5 (latest stable), C#9, tested with Net 5.0 and NetFramework 4.5

**Brief description**:
Assignment via the 'is not' pattern matching does not work as intended in the following case:

```csharp

class A { }
...
var a = new A();

// example1
if (a is not A converted1)
{ }
else
{
    // expected not null, but is null
    Console.WriteLine(converted1);
}
```

Here are two examples very similar to the top example. But they work as expected.
```csharp
// example2: works as expected when writing "!(... is ...)" instead of "... is not ...".
if (!(a is A converted2))
{ }
else
{
    // works, is not null
    Console.WriteLine(converted2);
}

// example3: works as expected when using a different type.
if (a is not object converted3)
{ }
else
{
    // works, is not null
    Console.WriteLine(converted3);
}
```

If this is not a bug but the expected behavior, then IntelliSense must not suggested to convert example2 to example1.

**Comment by Youssef1313** [comment]
I think this was fixed in https://github.com/dotnet/roslyn/pull/49369

**Comment by JankoR2** [comment]
thanks
