### ISSUE TITLE
Renaming Namespaces across dots

### ISSUE THREAD

**Issue by mohdali** [dotnet/roslyn#51408]
**Version Used**: 
Visual Studio 2019
**Steps to Reproduce**:
1. Rename a namespace by making changes across the name space dots (e.g. add new level, rename multiple levels)
2. Check the quick actions provided by the IDE

**Expected Behavior**:
To have an option in the quick actions to rename the whole namespace across the project. This option was available in earlier versions of VS for this case.
**Actual Behavior**:
Quick actions only provide an option to "Move content to namespace" which only affects the current file.

**Comment by jinujoseph** [comment]
Duplicate of #3583
