### ISSUE TITLE
Refactoring that converts a Class to a Record

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#51412]
Direct customer ask copying here:

> Is there a refactoring that allows me to easily refactor a class to a record?

**Comment by MithrilMan** [comment]
we'd need a refactor to also allow to convert the record syntax with implicit constructor
`public record MyRecord(int MyProperty)`
to
```
public record MyRecord {
   public int MyProperty { get; init; }
}
```

that's useful when your record get more complex that having an inline declaration isn't much readable and/or proper comment has to be written for such properties

**Comment by CyrusNajmabadi** [comment]
@mikadumont We'd strongly need to know what this means.  It's highly likely that almost any class woudl change meaning when moved to a record.  So we'd need to define the set of cases we felt was ok for this conversion to happen and when it was not ok.

**Comment by jmarolf** [comment]
I would love for something to convert a tuple to a record but I agree with @CyrusNajmabadi that a class to a record would need to have some definition like "This class only contains properties"

**Comment by CyrusNajmabadi** [comment]
> I would love for something to convert a tuple to a record

Tuple to 'struct record' is def something we'll be doing :)

**Comment by CyrusNajmabadi** [comment]
> that a class to a record would need to have some definition like "This class only contains properties"

Right.  Except that this would not change semantics because Records have == and Equals and whatnot.  We could look to see if the class had those, and then remove them.  But that could change semantics too :)
