### ISSUE TITLE
Quick Info should respect EditorBrowsableState

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#51416]
From https://github.com/dotnet/roslyn/issues/51356#issuecomment-783803832.

When evaluating the set of overloads to present in Quick Info, the initial set should not include any items which are filtered from completion due to the use of `EditorBrowsableAttribute`. If the reference actually binds to one of these overloads, that overload should be added back to the set (since it will be the primary item presented).

📝 This change only has a visual impact on the `(+ 5 overloads)` portion of the Quick Info pop-up.

**Comment by genlu** [comment]
> If the reference actually binds to one of these overloads, that overload should be added back to the set

We should also consider showing the EditorBrowsable state for the displayed overload in this case, which might help avoid confusion.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
