### ISSUE TITLE
Moving a record to its own file doesn't create necessary using directives and breaks code

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#51438]
**Version Used**: 

**Steps to Reproduce**:

1. Create a new .NET 5 class library
2. Replace `Program.cs` with this code:

```c#
using System;
using System.Text.RegularExpressions;

namespace ClassLibrary39
{
    record R(Regex Regex, Uri uri);

    public class Class1
    {
    }
}
```

3. Invoke _Move type to R.cs_ on the record.

**Expected Behavior**:

Record is created with using directives so that `Regex` and `Uri` are resolved.

```c#
// R.cs
using System;
using System.Text.RegularExpressions;
namespace ClassLibrary39
{
    internal sealed record R(Regex Regex, Uri uri);
}
```

**Actual Behavior**:

Type is moved to file without usings, so symbols are unresolved and code does not compile.

```c#
// R.cs
namespace ClassLibrary39
{
    internal sealed record R(Regex Regex, Uri uri);
}
```

---

Not sure if it's expected, but it would be nice if the usings in `Program.cs` were removed as well. They're left as unused after the refactoring occurs.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/51284
