### ISSUE TITLE
"and" and "or" keywords are provided during switch enum completion in unexpected situations

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#51431]
1. Create a new console app
2. Paste in the following content
```C#
var foo = Foo.First;
switch (foo)
{
    case Foo.
}

public enum Foo
{
    First,
    Second
}

```
3. Invoke completion after `Foo.` as shown in the screenshot:

![image](https://user-images.githubusercontent.com/2008729/108926764-ea19e380-75f3-11eb-8367-20fbd1ecde28.png)

**Comment by Youssef1313** [comment]
Probably related to:

https://github.com/dotnet/roslyn/blob/6171900dad45fa49de23911557d70905460d5514/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs#L1485-L1508
