### ISSUE TITLE
[LSP] Remove completion feature flag and enable returning TextEdits by default

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#51439]
#51166 added a feature flag to LSP completion that enables returning TextEdits instead of InsertText. Once the team has tried this out and assessed its impact on performance, we should remove the feature flag and return TextEdits by default (provided it has acceptable performance).

**Comment by allisonchou** [comment]
Moving to 17.0 to allow more time for feature flag testing and to do benchmark work.

**Comment by dibarbet** [comment]
Flag has been removed and we now return text edits by default in https://github.com/dotnet/roslyn/pull/60466
