### ISSUE TITLE
Need release notes for VS2019 16.8.6

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#51441]
no release notes in here: [https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)

**Comment by jmarolf** [comment]
See the note [here](https://developercommunity.visualstudio.com/t/No-Release-Notes-for-version-1686/1346863#T-N1348338). The VS publishing team is looking at this. I would follow that developer community issue if you want up-to-date information
