### ISSUE TITLE
Range indexer does not show usages of the underlying method.

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#51443]
**Version Used**:  VS16.8.3 / .net 5 compiler

**Steps to Reproduce**:

Add the following code:

```cs
var substring = "12345"[1..3];
var subarray = new[] { 1, 2, 3, 4, 5 }[1..3];
```

Try to use the "Find all References" feature to find usages of `string.Substring()` / `RuntimeHelpers.GetSubArray()`.

**Expected Behavior**:

Finding usages of the underlying methods should show the lines that use the range indexer.

**Actual Behavior**:

Usages are not shown.

**Comment by jinujoseph** [comment]
Duplicate of #41310
