### ISSUE TITLE
CallerFilePathAttribute does not set path in default base constructor without explicit base() call

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/roslyn#51442]
An argument decorated with [CallerFilePath] in a default constructor that is called implicitly by a derived class is left at its default value (not set to the file path). It works if that constructor is called explicitly via `: base()`.

**Version Used**:

.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.21079.7
 Commit:    580b1c3770

Microsoft (R) Visual C# Compiler version 3.9.0-4.21104.8 (2fc92d84)

**Steps to Reproduce**:

Run the following program as a console EXE:

```
    class Program
    {
        static void Main(string[] args)
        {
            new DerivedClass();
        }
    }

    class BaseClass
    {
        //[MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)] // doesn't help
        public BaseClass([CallerFilePath] string callerFilePath = "[not provided]")
        {
            System.Console.WriteLine("BaseClass callerFilePath = " + callerFilePath);
        }
    }

    class DerivedClass : BaseClass
    {
        public DerivedClass([CallerFilePath] string callerFilePath = "[not provided]")
            // works if you uncomment this:
            // : base()
        {
            System.Console.WriteLine("DerivedClass callerFilePath = " + callerFilePath);
        }
    }
```

**Expected Behavior**:

> BaseClass callerFilePath = ...\CallerFilePathTest\Program.cs
> DerivedClass callerFilePath = ...\CallerFilePathTest\Program.cs

**Actual Behavior**:

> BaseClass callerFilePath = [not provided]
> DerivedClass callerFilePath = ...\CallerFilePathTest\Program.cs

**Comment by RikkiGibson** [comment]
Could you please let us know if this is a regression from previous versions of the compiler, for example, when building with .NET Core 3.1.

**Comment by loop-evgeny** [comment]
I don't believe so. If I change the proj file to have `<TargetFramework>netcoreapp3.0</TargetFramework>` and create a global.json with

```
{
  "sdk": {
    "version": "3.0.100"
  }
}
```

I get the same results.

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue but unfortunately it is "By Design". From the C# spec

> Caller information is only substituted when a function is explicitly invoked in source code. Implicit invocations such as implicit parent constructor calls do not have a source location and will not substitute caller information

Essentially the function must be explicitly used for caller info to be inserted by the compiler.

**Comment by loop-evgeny** [comment]
I see. Yes, that is unfortunate, because I'd say it's quite counter-intuitive design. I don't get the reasoning behind it.

I understand why there might be no caller source file if the entire constructor was compiler-generated, but when there is an explicit constructor, and it implicitly calls the base constructor from the user's point of view that's the same as explicitly calling "base". (ReSharper even warns that the `: base()` call is redundant.) The caller source file is obviously the one that declares the constructor - would any user would expect otherwise? 

If the design cannot be changed then it would be good to at least document this "gotcha" on https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerfilepathattribute?view=net-5.0
