### ISSUE TITLE
Target-typed numeric literal regression from 16.8.6 to 16.9.P5

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#51450]
**Version Used**: 16.9.P5

This error is not present on 16.8.6, but it is present on 16.9.P5 where it causes an application to no longer compile:

```cs
class C
{
    ushort M(ushort p, bool cond)
    {
        // ❌ CS0266 Cannot implicitly convert type 'int' to 'ushort'. An explicit conversion exists (are you missing a
        // cast?)
        //     ↓↓↓↓↓↓↓↓↓↓↓↓
        return cond ? p : 0;
    }
}
```

**Comment by 333fred** [comment]
@cston?

**Comment by cston** [comment]
The error in 16.9P5 is expected. The expression was treated as target-typed unintentionally in 16.8.

A target-typed conditional expression conversion should only be used when there is no common type between the sub-expressions - see [conditional-expression-conversion](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/target-typed-conditional-expression.md#conditional-expression-conversion).

See https://github.com/dotnet/roslyn/pull/50755.

**Comment by jnm2** [comment]
If I remember right, either Roslyn or ReSharper greyed out the `(ushort)` cast and it got removed in a cleanup PR along with a lot of other casts that the IDE called unnecessary. We might not be the only folks with a production application that did something similar in the 16.8 timeframe and will experience build failures upon updating Visual Studio and build machines.

**Comment by jaredpar** [comment]
> We might not be the only folks with a production application who did something similar in the 16.8 timeframe and who will experience build failures upon updating Visual Studio and build machines.

Understood but at the same time it's a bug we decided to fix. This feature is brand new, it's the first update and we found and corrected a bug in the implementation. Consider also that the bug we fixed was causing pre-existing code to fail to compile. So either way: code will be broken here. 

> As always, is there room for the design to change to accommodate this? Or is this kind of target typing something the C# team thinks they will never do?

It's worth discussing in csharplang. At the same time though we added this restriction because it actually creates other compat problems with overload resolution (IIRC).

**Comment by jnm2** [comment]
That makes sense. I'm not sure I'll bring it up at csharplang if it inherently creates compat problems with preexisting code.

**Comment by tannergooding** [comment]
I hit this as well as I had code that was doing `uint x = cond ? 64 : 256` and `ulong y = cond ? Int32Constant1 : Int32Constant2;`

Had to change it back to `uint x = cond ? 64u : 256u` and `ulong y = cond ? (ulong)Int32Constant1 : (ulong)Int32Constant2` 😢

**Comment by jnm2** [comment]
Yeah. I've hit this in two repos now.

**Comment by MaxHayman** [comment]
This is quite disappointing. I rejoiced the day that I could remove all these unnecessary casts.

@jaredpar 

> consider also that the bug we fixed was causing pre-existing code to fail to compile

Hmm I never noticed anything breaking when this was introduced, any examples?

**Comment by cston** [comment]
@MaxHayman, https://github.com/dotnet/roslyn/pull/50755 gives a couple of examples where existing code was affected.

In the example below: with 16.7, the method returns an `int`; with 16.8 the method returns a `short`; and with 16.8 and `-langversion:8`, an error is reported:
```csharp
static object F2(bool b, short? a)
{
    // 16.7                : int
    // 16.8                : short
    // 16.8 -langversion:8 : error 'target-typed conditional expression' is not available
    return a ?? (b ? 1 : 2);
}
```
