### ISSUE TITLE
Consider expanding comment continuation to include cases with trailing // on following lines

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#51462]
I find myself writing extra crazy long comments all the time and this is one scenario I'd love to be handled by "comment continuation". Aka the ability to pre-add another `//` depending on where you enter a newline.

![j7ONpZmqD4](https://user-images.githubusercontent.com/2008729/109086139-e2c00c00-76bf-11eb-86bc-1dd6fb09c09c.gif)

The idea would be if you were in the middle of a comment block (denoted by a comment on the line after where you hit enter) that entering a newline would result in an additional `//` being added on your behalf.

I'd expect the content to be the following after hitting "enter":
```C#
// First Line
// |
//
// Other comments
```

**Comment by CyrusNajmabadi** [comment]
I think this would be reasonable.

**Comment by CyrusNajmabadi** [comment]
Closing as we haven't heard feedback on this
