### ISSUE TITLE
Test plan for "improved definite assignment"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#51463]
Championed issue: https://github.com/dotnet/csharplang/issues/4465
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/improved-definite-assignment.md#specification

- [x] definite assignment and nullability improvements for `??`
  - `<null-conditional> ?? expr_second`
- [x] definite assignment and nullability improvements for `? :`
  - `expr_cond ? expr_true : expr_false` can result in conditional state
- [x] definite assignment and nullability improvements for `==`
  - `<null-conditional> == <null-constant>`
  - `<null-conditional> == <not-null>`
  - `expr == <constant-true>`
  - `expr == <constant-false>`
  - corresponding rules for `!=`
  - predefined vs. user-defined `==` operators
  - DataFlowsOut API needs tests to demonstrate that the usage of `Meet()` between `==`/`!=` operands is sound
- [x] definite assignment and nullability improvements for `is`
  - `<null-conditional> is <not-null-only-matching-pattern>`
  - `<null-conditional> is <null-only-matching-pattern>`
  - `<null-conditional> is <true-only-matching-pattern>`
  - `<null-conditional> is <false-only-matching-pattern>`
- true, false operators

Needs some discussion:
- [ ] definite assignment and nullability improvements for `switch`
- [ ] definite assignment and nullability improvements for relational operators (`>`, ...)

## Productivity
- [ ] change `x != null && x?.TryGetValue(out y)` to `x?.TryGetValue(out y) == true`

**Comment by RikkiGibson** [comment]
We concluded that before feature merge, we will just get the nullable 'is' PR (#53311) merged, then another PR to ensure test coverage for the implemented aspects of the feature.

We intend to do the 'switch' and '<=' aspects in PRs to main after the feature is merged before shipping C# 10.

**Comment by jcouv** [comment]
I think we can close this now. Thanks
