### ISSUE TITLE
Reconcile SyntaxEditor and SyntaxGenerator

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5147]
1. The latter is an ILanguageService, but the former is not. 
2. The latter can be acquired with SyntaxGenerator.GetGenerator(node/document/root), but the former cannot.  

Something feels weird here.  I would have expected more commonality here.  Right now they feel oddly different.

**Comment by Pilchie** [comment]
We can't remove the existing apis, but we could possibly hide them from IntelliSense and offer a more consistent way to access these.

**Comment by CyrusNajmabadi** [comment]
@Pilchie  agreed.  Or just provide a union of the APIs.  That way you can use either approach with either API.

**Comment by CyrusNajmabadi** [comment]
Boo on closing this :)
