### ISSUE TITLE
Allow trigger Regeneration of Source Generated code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51483]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Allow-trigger-Regeneration-of-Source-Gen/1337121)._

---
when looking at code generated by a source generator inside VS, sometimes the code doesnt update automatically if the generator code changes,  having a 'regenerate' button on the 'Cannot modify' message would allow a user to manually override Visual Studios triggering of the analyser. The image attached is using a source generator in an solution project, a change has been made to the generator, and the change has not been reflected in the used code.

! [SG.png] (https://aka.ms/dc/image?name=B14ed239c4e2a42c2a5fff209f61ffa9c637486330002464803_SG.png&tid=14ed239c4e2a42c2a5fff209f61ffa9c637486330002464803)

---
#### Feedback Bot on 2/14/2021, 09:45 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by Youssef1313** [comment]
@chsienki Does the compiler provides an API that IDE can use to do this without a complete compilation?

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We should not have band-aid features to make up for bugs.  We need to just fix the bugs.
