### ISSUE TITLE
Please comment on the decompiled code, VS tool options in the C-Advanced-support navigation to the decompiled source (experiment)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51484]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/请给反编译的代码加上注释，VS工具选项中C-高级-支持导航到反编译源实验/1278951)._

---
(regression) (worked-in:VS2019 16.8.2)
![image](https://user-images.githubusercontent.com/46729679/109191005-8e15a300-774a-11eb-81ae-f9cfe87c7283.png)

![image](https://user-images.githubusercontent.com/46729679/109191046-9a99fb80-774a-11eb-9b52-a4f2ae930fe3.png)

It's a good idea to follow ILSpy and have settings options that allow all code to expand at the same time as the compilation time and navigate to the code that is currently going to the definition.

---
#### Feedback Bot on 12/7/2020, 01:18 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
They are asking for comments in decompiled source. The first screenshot is the tooltip shown in source. The second is the decompiled code, which shows no doc comments, and they would like to have comments show up in the same language as VS.

**Comment by CyrusNajmabadi** [comment]
Closing out as we have not received feedback on this.  Decompiled code is also handled outside of roslyn.
