### ISSUE TITLE
Add possibility to Extract Function to Lambda Function with Refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51486]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-possibility-to-Extract-Function-to-L/1337887)._

---
In Visual Studio one can use "Quick Actions and Refactoring" to Extract a Function. Either Above or Below current function, either as Member or Free function.
I think it might be very usefull to add the possibility to extract to a Lambda Function also. Either in-place, or at top of function (so within Function).
So one can use the Lambda function as a Nested Function.

---
#### Feedback Bot on 2/14/2021, 10:13 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment]
Can you provide an example to understand the scenario better ?
