### ISSUE TITLE
When refactoring and extracting an interface one should copy the comments and annotations with it

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51485]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/When-refactoring-and-extracting-an-inter/1344649)._

---
Hi,

When refactoring a class one can use the extract interface helper function that will copy properties and methods from a class and add it to a new interface. It would be nice to copy the documentation on the class being refactored with it.

One could have a checkbox to select "Copy documentation" to maintain backward compatibility if desired

---
### Original Comments
(no comments)

**Comment by allisonchou** [comment]
**Design meeting notes (3/22):** We will add a checkbox for this in the extract interface UI (and other related UIs) which will be checked by default.

**Comment by CyrusNajmabadi** [comment]
Closing out due  to lack of feedback on this topic.
