### ISSUE TITLE
Cannot implement interface method with nullability annotation when struct constraint is added

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn#51490]
The following code does not compile:

```c#
interface IMyInterface<T>
{
    void Foo(T? value);
}

class MyClass2<T> : IMyInterface<T> where T : struct
{
    public void Foo(T? value) => throw new NotImplementedException();
}
```

Note that constraining T to `class` instead of `struct` in the implementing class does compile.

**Comment by CyrusNajmabadi** [comment]
You would implement this interface like so:

```c#
using System;

interface IMyInterface<T>
{
    void Foo(T? value);
}

class MyClass2<T> : IMyInterface<T> where T : struct
{
    public void Foo(T value) => throw new NotImplementedException();
}
```

`T?` in the interface means `allowed to be default` not `allowed to be null`.  So, in the `T:struct` case, `T` is the right type to use here.

**Comment by roji** [comment]
Thanks for the quick response.
