### ISSUE TITLE
GenerateMethodTests.GenerateConversionTest.TestEquivalenceKey fails on features/local-functions branch

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5149]
The test appears to be checking for a generate-method fix in a class that only provides fixes for conversions.

**Comment by CyrusNajmabadi** [comment]
@gafter is this an issue at all?  Local functions were merged in, and i don't see any issues with those tests.  Nothing seems skipped either.  So my guess is that this can be closed.

**Comment by gafter** [comment]
I think the branch is no longer in use. @agocke ?

**Comment by agocke** [comment]
Yup this is a dead branch. We can delete it
