### ISSUE TITLE
We should have some unit tests that test EditorFeatures.Cocoa

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#51491]
Right now we have no unit test coverage of EditorFeatures.Cocoa at all. We should probably have some coverage. I can think of two options:

1. The fancy option: refactor our EditorFeatures tests to somehow test against Wpf when running on Windows, and Cocoa when running on a Mac. Obviously some tests are going to be platform specific, but a huge number of tests just use ITextView and thus we could test the behavior on both sides.
2. The quick option: just add a few tests for important features so we don't entirely break them by a refactoring gone bad.

**Comment by RikkiGibson** [comment]
It sounds like part of the work here is just to get a Mac CI environment with Mono spun up, and part of the work is to modify the tests to behave differently when run on a Mac.

**Comment by jasonmalinowski** [comment]
Yep, this is going to require some amount of refactoring of our tests. (Precisely how much is an open question but I've got a few implementation ideas.)

**Comment by CyrusNajmabadi** [comment]
Closing as vs4mac is gone and this is speculative.
