### ISSUE TITLE
Using an object initializer for a using declaration should create a warning

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51513]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-an-object-initializer-for-a-using-/1348467)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Before using declarations were added]
When used together they can create readability problems. At first look, this code was read as the inner using block does nothing and can be removed.  This is not the case.

An example of a using block with a using declaration nested in it. 
``` csharp
            using (var stringContent = new StringContent(JsonConvert.SerializeObject(data), System.Text.Encoding.UTF8, "application/json"))
            {
                using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(SomeConfigProperty))
                {
                    Content = stringContent
                };

request. Headers.Add(...
//          ... etc
```
Some kind of IDE_NNN_ rule or other check should be in place to warn when these are both used for the same object.

FWIW, I probably would have just stacked the using blocks in this case and avoided the harder to read option above, but sometimes the usings are not going to be immedately next to each other.

``` csharp
            using (var stringContent = new StringContent(JsonConvert.SerializeObject(data), System.Text.Encoding.UTF8, "application/json"))
            using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(SomeConfigProperty))
            {
                request. Content = stringContent;
//     ... etc
```

---
#### Feedback Bot on 2/24/2021, 09:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StingyJack** [comment]
@vsfeedback - why didnt you tag me on this?

**Comment by allisonchou** [comment]
**Design meeting notes (3/22):** We will wait for more feedback from users before implementing this.
For now, if a user desires this functionality, writing an individual analyzer would be an option.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback.  A custom analyzer is the appropriate user driven way forward here.
