### ISSUE TITLE
Optional ParameterInfo is lost at runtime for local functions

### ISSUE THREAD

**Issue by halter73** [dotnet/roslyn#51518]
**Version Used**: 

master (24 Feb 2021) on sharplab.io

**Steps to Reproduce**:

View [this sharplab.io snippet](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAI8KBhCgbxIuasuwBYKBZACgEoGTFsI4UAKnFgAZAPYBjCABts+XDwCWAOxgUIFALwVcfIcOaNiZlgF9TZu8K4QADirU83AHi0wAfHwlYLjgYAAsZFDc+AG4HFidXVR4PVW9tf0CYWQVlVRi7W0sWO3IqTkzgsIi3DW1dAyMTIvMCuxK2TgSagBE4RTgAcwh4XTkYdRlNJuELYULrIA=) and observe that this:

```C#
using System;
public class C {
    public void M() {
        void TestLocalAction(int a = 2)
        {
        }
        
        MapAction((Action<int>)TestMethodAction);
        MapAction((Action<int>)TestLocalAction);
    }
    
    public void TestMethodAction(int a = 2)
    {
    }
    
    public void MapAction(Delegate action)
    {
    }
}
```

results in this:

```C#
// ...
public class C
{
    public void M()
    {
        MapAction(new Action<int>(TestMethodAction));
        MapAction(new Action<int>(<M>g__TestLocalAction|0_0));
    }

    public void TestMethodAction(int a = 2)
    {
    }

    public void MapAction(Delegate action)
    {
    }

    [CompilerGenerated]
    internal static void <M>g__TestLocalAction|0_0(int a)
    {
    }
}
```

And that `<M>g__TestLocalAction|0_0` does not have a default value unlike `TestMethodAction`.

**Expected Behavior**:

`<M>g__TestLocalAction|0_0` should have `int a = 2` in its parameter list.

**Actual Behavior**:

`<M>g__TestLocalAction|0_0` does not have `int a = 2` in its parameter lists. This becomes a problem for `MapAction` if it wants to call `TestLocalAction` with the default parameter value. `Delegate.Method.GetParameters()[0].HasDefaultValue` ends up returning false instead of true.

Thanks @Kahbazi for finding this! https://github.com/dotnet/aspnetcore/pull/30434/files#r583502436

**Comment by Youssef1313** [comment]
@jaredpar Is the breaking change here okay?

**Comment by jaredpar** [comment]
Yes. There are a  few changes we are taking in this area of making sure that emitted closures / local functions better represent the attributes that were initially placed on them. It's in support of scenarios like `MapAction`.
