### ISSUE TITLE
Add verbose logging to help isolate race conditions in errorlist

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn#51521]
Customers have reported that at times diagnostics that stick around, even once customer has fixed them. i.e. even after doing a full (successful) build. This scenario usually happens when customers attempt a series of quick edits/changes/refactorings. Potentially there is a race condition somewhere. This leads to confusion.

At this point we do not have a repro, thus it is very difficult to isolate the issue at hand. We can potentially add additional logging that customers can enable when they hit this issue. Hopefully additional logging will help us address this bug.

**Comment by Youssef1313** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/51549
