### ISSUE TITLE
Unnecessary boxing in SyntaxToken.Value

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#51524]
These return values:

https://github.com/dotnet/roslyn/blob/b1ef0b3d0674737f9e60a701fcace2b75883e1f6/src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxToken.cs#L287-L290

Should be using these boxes:

https://github.com/dotnet/roslyn/blob/b1ef0b3d0674737f9e60a701fcace2b75883e1f6/src/Compilers/Core/Portable/Collections/Boxes.cs#L11-L12

**Comment by RikkiGibson** [comment]
Does the runtime not use a shared box of some kind for booleans?

**Comment by sharwell** [comment]
I'm not sure about .NET 5.0 or .NET 6.0, but this box was showing up in a performance trace of a net472 build.

**Comment by svick** [comment]
@RikkiGibson I don't think it can, from https://github.com/dotnet/runtime/issues/7079#issuecomment-546050757 by Neal Gafter:

> Boxing is required in the C# language specification and in the CLR specification to allocate a new object instance. This is trivially observable in user code. So the proposed "optimization" would violate both specifications.

**Comment by Youssef1313** [comment]
I opened #51546 to fix this.
(Note: VB side is already using Boxes
