### ISSUE TITLE
PDBs should include information about extern aliases

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#51523]
Several Roslyn projects don't rebuild with diagnostics like the following:

`C:\Users\rikki\src\roslyn\src\Test\PdbUtilities\Reader\CustomDebugInfoUtilities.cs(7,14): error CS0430: The extern alias 'DSR' was not specified in a /reference option`

It looks like extern aliases aren't included in the PDB compilation options. This should be fixed for 16.10.

**Comment by tmat** [comment]
They should be included:
Spec: https://github.com/dotnet/runtime/blob/master/docs/design/specs/PortablePdb-Metadata.md#compilation-metadata-references-c-and-vb-compilers
Impl: http://sourceroslyn.io/#Microsoft.CodeAnalysis/PEWriter/MetadataWriter.PortablePdb.cs,939

**Comment by RikkiGibson** [comment]
Awesome, it looks like we are probably just dropping them on the floor in the rebuilder. That's an easier fix. :)
