### ISSUE TITLE
Definite Assignment allowing local function to access variable before declaration

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#51544]
```cs
M();
string s;

void M()
{
    s = "";
}
```

`M()` is called before `s` is declared and uses `s`, but this code compiles successfully. It should not.

**Comment by RikkiGibson** [comment]
This is by-design. Please see https://github.com/dotnet/roslyn/issues/24644#issuecomment-363249614.

The "use before declaration" check on local variables is strictly lexical. So if the usage appears later on in syntax than the declaration, it's allowed.

**Comment by 333fred** [comment]
This is depressing, but ok.
