### ISSUE TITLE
Error list sometimes hides warnings for minutes after building the solution, and the warning count doesn't match

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#51549]
**Version Used**: 16.8.6

I used https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/8466e251ebbae6b6ef06886035df1f979e3d6840/IDisposableAnalyzers.sln for all these screenshots.

Opening the solution after `git clean -xdf`, VS shows 22 warnings, 35 messages:

![image](https://user-images.githubusercontent.com/8040367/109429086-02a94580-79c8-11eb-9bf6-6543ab3f02e9.png)

After 'Build Solution', VS shows 1 warning, 18 messages. Sometimes this doesn't happen until the third time I build the solution, so maybe it's correlated to something other than "Build Solution":

![image](https://user-images.githubusercontent.com/8040367/109429099-0d63da80-79c8-11eb-8b25-9fdadb85c522.png)

If I reopen VS but I don't `git clean -xdf`, I get a middle subset; 6 warnings, 15 messages:

![image](https://user-images.githubusercontent.com/8040367/109429163-5ae04780-79c8-11eb-9d30-94d057cad944.png)

Then after three minutes of leaving VS open and idle, they all come back but the Error List count doesn't match!

![image](https://user-images.githubusercontent.com/8040367/109429188-78adac80-79c8-11eb-82c1-7cfd12a9d8b4.png)

## Visual Studio settings

![image](https://user-images.githubusercontent.com/8040367/109429222-a2ff6a00-79c8-11eb-83d8-4ca880e54930.png)

![image](https://user-images.githubusercontent.com/8040367/109429216-99760200-79c8-11eb-824e-3f68660346cc.png)

**Comment by JohanLarsson** [comment]
I used the same commit.

After git clean -fxd and open and waiting one minute I get:
![image](https://user-images.githubusercontent.com/1640096/109429479-2be3c900-79fc-11eb-8050-9c960823271b.png)

After build I get:
![image](https://user-images.githubusercontent.com/1640096/109429657-29ce3a00-79fd-11eb-83e9-93e6254fdbd2.png)

**Comment by JohanLarsson** [comment]
Closed Visual Studio and git clean -fxd and opened the sln again.

After a minute I get, for a while there were over 100 errors but they went away
![image](https://user-images.githubusercontent.com/1640096/109429863-89791500-79fe-11eb-8e6c-606572934ac2.png)

After build and waited two minutes
![image](https://user-images.githubusercontent.com/1640096/109430063-91858480-79ff-11eb-88ce-fb1143713872.png)

**Comment by CyrusNajmabadi** [comment]
@manish.  A reliable repro!

**Comment by CyrusNajmabadi** [comment]
Thanks everyone!

**Comment by mavasani** [comment]
I am unable to repro this on Version 16.10.0 Preview 2.0 [31131.29.main] (internal dogfood build). Steps tried:

1. Open VS and ensure `Background Analysis Scope` is set to `Entire Solution`. Close VS.
2. `git clone https://github.com/DotNetAnalyzers/IDisposableAnalyzers/`
3. `cd IDisposableAnalyzers`
4. `git checkout 8466e251ebbae6b6e`
5. `git clean -xdf`
6. `IDisposableAnalyzers.sln`
7. Wait for error list to become stable, i.e. `Error List...` changes to `Error List`
8. Verify `21 warnings` and `121 messages` from background analysis
9. Build Solution
10. Error list will momentarily go empty (we clean the error list near the start of each build) and then start populating warnings from the build, i.e. go to `21 warnings` and `0 messages`. The error list will still show as unstable, i.e. `Error List...`, while background analysis executes in background. After some time, it become stable, i.e. `Error List...` changes to `Error List` and it shows `21 warnings` and `121 messages`
11. Repeat Build a few times - error list still shows `21 warnings` and `121 messages` every time
12. Perform Rebuild a couple of times and wait for error list to become stable. `21 warnings` and `121 messages` every time
13. Close VS
14. git clean -xdf`
15. `IDisposableAnalyzers.sln`
16. Wait for error list to become stable and verify `21 warnings` and `121 messages`

**Comment by jnm2** [comment]
Would grouping in the error list make a difference?

Is there anything we can do to collect information next time we see this?

**Comment by mavasani** [comment]
> Would grouping in the error list make a difference?

Let me try that out as well.

> Is there anything we can do to collect information next time we see this?

We are hoping that https://github.com/dotnet/roslyn/issues/51521 will enable such information collection. Once we have that in place, I'll post the required steps here.

**Comment by mavasani** [comment]
This is now a pretty old issue. Kindly re-open if you are still running into any of these issues on VS2022. Thanks!
