### ISSUE TITLE
Nullable NotNullWhen(true) not work

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#51547]
**Version Used**: 
`VS2019 16.8.6`
`.NET 5`

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/4510984/109418417-3c4b7200-7a03-11eb-8be8-dc38275a37df.png)

![image](https://user-images.githubusercontent.com/4510984/109418470-7e74b380-7a03-11eb-831d-125ed023ef1b.png)

**Expected Behavior**:
No `CS8602` waring.

**Actual Behavior**:
 `CS8602` waring.

**Comment by Youssef1313** [comment]
This appears to be by design based on https://github.com/dotnet/roslyn/issues/39749.

@RikkiGibson Do you know if any existing proposal to enhance analysis in such cases?

**Comment by jaredpar** [comment]
As noted this is "By Design". In general the nullable analysis engine does not read through `bool` values in this way. 

@Youssef1313 there are a couple of suggestions on csharplang that we allow this but not a comprehensive proposal.
