### ISSUE TITLE
Add link to a wiki-page to Jenkins job status summary that lists possible test commands

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5155]
It would be useful to add a link to 
![x](https://cloud.githubusercontent.com/assets/41759/9807124/7592731a-5803-11e5-8747-862cfbdac296.png)
that lists commands like

• ‘test unit please’
• ‘test eta please’
• ‘test vsi please’

and perhaps additional details around CI.

**Comment by dpoeschl** [comment]
Yes, I'm looking around for the right command to re-run a particular test right now and stumbled on this bug.

A "rerun" (or whatever) button next to each Details button would help, too. :smile:
