### ISSUE TITLE
Improve Performance of ToString() for Record Types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51568]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Improve-Performance-of-ToString-for-Re/1337296)._

---
Looking at the PrintMembers method for record types, performance could be increased by using constants for " = " and ", ". Property names could be constants too. Also, look into possibly using StringBuilder from a object pool.

[NullableContext(1)]
protected virtual bool PrintMembers(StringBuilder builder)
{
    builder. Append("Addresses");
    builder. Append(" = ");
    builder. Append(this. Addresses);
    builder. Append(", ");
    builder. Append("BornOn");
    builder. Append(" = ");
    builder. Append(this. BornOn.ToString());
    builder. Append(", ");
    builder. Append("CellPhone");
    builder. Append(" = ");
    builder. Append(this. CellPhone);
    builder. Append(", ");
    builder. Append("Email");
    builder. Append(" = ");
    builder. Append(this. Email);
    builder. Append(", ");
    builder. Append("FirstName");
    builder. Append(" = ");
    builder. Append(this. FirstName);
    builder. Append(", ");
    builder. Append("HomePhone");
    builder. Append(" = ");
    builder. Append(this. HomePhone);
    builder. Append(", ");
    builder. Append("Id");
    builder. Append(" = ");
    builder. Append(this. Id);
    builder. Append(", ");
    builder. Append("LastName");
    builder. Append(" = ");
    builder. Append(this. LastName);
    return true;
}

---
#### Feedback Bot on 2/14/2021, 09:52 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
> Looking at the PrintMembers method for record types, performance could be increased by using constants for

That is what will happen.  String literals are constants and will be pulled from the dll's string table.
