### ISSUE TITLE
Implement interface code fix does not include default interface methods

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#51560]
**Version Used**: 

Microsoft Visual Studio Community 2019
Version 16.8.6
VisualStudio.16.Release/16.8.6+31019.35
Microsoft .NET Framework
Version 4.8.04084

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Steps to Reproduce**:

1. Given the following interface:

```csharp
    public interface IDefault
    {
        void Do();
        int Value => 5;
    }
```

2. And the following class definition:

```csharp
    public class Default : IDefault
    {
    }
```

3. When triggering the code fix to implement the interface, the following is offered:

![image](https://user-images.githubusercontent.com/169707/109531649-f17b3a00-7a96-11eb-92f4-c290dec1033d.png)

**Expected Behavior**:

The `Value` property, despite having a default implementation, should be offered when creating a brand-new class that desires to implement the interface. Perhaps it could be offered as a separate code fix ("Implement default methods", say).

**Actual Behavior**:

There is no way to automatically implement *all* members of an interface, regardless of whether they have a default implementation or not.

**Comment by sharwell** [comment]
I believe the current implementation is correct. Members with a default implementation are often unnecessarily tedious to implement for the same end result.

**Comment by kzu** [comment]
Yeah, makes sense. Perhaps an additional code fix to implement them if desired by the user, would be enough.

**Comment by sharwell** [comment]
In design review, we generally felt that the current behavior best matched the intent of these two refactorings, particularly in regard to the consistent behavior between Implement Interface and Implement Abstract Class. However, we also saw how tedious it is today to implement the default members defined in an interface. We'd like to find a way to update the **Generate overrides...** refactoring (also shown in the screenshot above) by modifying the dialog to include default interface members in some clear fashion:

![image](https://user-images.githubusercontent.com/1408396/109566146-4e2b2480-7a98-11eb-8009-8f4ee13637ff.png)

**Comment by kzu** [comment]
Yeah, something like that would be awesome :tada:

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback about this area.
