### ISSUE TITLE
Intellisense: move nested class to separate file creates duplicate of surrounding class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51564]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense:-move-nested-class-to-separ/1351442)._

---
[severity:It bothers me. A fix would be nice]
In VB.Net (. NET-Framework 4.7.2) I have the following code:
```
Public Class Foo
	Private Bazz As Integer

Public Class Bar
	End Class
End Class
```
Intellisense makes a proposal to move Bar into a separate file. If I agree, Bazz will be duplicated. Especially annoying, if Bar is in a form-file: everything in this file (except Bar) will be copied into the new file, which leads to massive complaints about double definitions.

---
#### Feedback Bot on 2/28/2021, 09:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
The bug should be around the following:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeEditor.cs#L206

**Comment by Youssef1313** [comment]
I opened #51723 to fix that.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change these experiences.
