### ISSUE TITLE
[future] Add tests for expression evaluator interaction with local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5157]
Please add tests for the interaction of the expression evaluator and local functions.

That testing effort is likely to uncover work items for the feature.

**Comment by jcouv** [comment]
@cston The milestone should be updated. I'll let you triage as appropriate. Thanks

**Comment by Pilchie** [comment]
@jinujoseph can you re-triage? This was in the 2.0 milestone.

**Comment by cston** [comment]
Tests were added for locals and captured variables in local functions in #18415. Currently, local functions cannot be invoked from the EE, see #16951, and corresponding tests are needed.

**Comment by ivanbasov** [comment]
Thank you, @cston! Let us keep track #16951 and close this one because tests required are already there.
