### ISSUE TITLE
Certain VB rebuilds fail only in CI

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#51598]
sample failure:

https://dev.azure.com/dnceng/public/_build/results?buildId=1019441&view=logs&j=85c53086-d585-50b3-ae0b-d040c710cd82&t=594baf59-7399-559c-703e-f627c7cd2311

It appears we can't resolve the version of Microsoft.VisualBasic.dll that we want in CI, but we can resolve it locally. I do not currently know why this is happening.

**Comment by jmarolf** [comment]
:'(

**Comment by RikkiGibson** [comment]
This is loosely related to #51647

**Comment by RikkiGibson** [comment]
The exclusion list doesn't seem to contain many VB projects at this point so I think we probably fixed this issue.

https://github.com/dotnet/roslyn/blob/8e2e6b6efbb1969f3f5fe67dfaa2bcba8a37c0a7/eng/test-rebuild.ps1#L43-L63
