### ISSUE TITLE
>CLS Missing from Immediate Window

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5160]
Many commands from VS 2013 are missing, the one I care the most about is Clear Window

```
>CLS
```

![image](https://cloud.githubusercontent.com/assets/12789369/9810975/3389ad00-5829-11e5-8f3c-f79aac5bec02.png)

**Comment by tmat** [comment]
As a workaround you can right-click and use "Clear All"

![image](https://cloud.githubusercontent.com/assets/41759/9820462/10ddd0a2-5869-11e5-98e2-8722aa49782a.png)

**Comment by tmat** [comment]
What other commands would you like to see back?

**Comment by paul1956** [comment]
CLS is the only one I use but while investigating I compared the lists and noticed lots were missing. Right click was was not obvious in this case but it works. If this was the new scripting window I might have a different answer.

**Comment by tmat** [comment]
The plan is to unify the experience between Interactive Window and Immediate Window in future. In Interactive Window the "clear all" command is "#cls" (all commands have '#' prefix). 

We could add #cls to Immediate Window before we unify the windows, which is a much bigger work item, to ease the transition.

**Comment by paul1956** [comment]
With #CLS I would have still opened the issue unless you documented the change in what's new. So just documenting the existing change is less work and equally good.

**Comment by tmat** [comment]
Fair enough.

**Comment by paul1956** [comment]
This should be closed since there are several ways to do this is VS 2017
