### ISSUE TITLE
GoToDefinition on `var` in var pattern doesn't navigate to type

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#51615]
It is possible to use GoToDefinition on `var` in local declarations, out variables and deconstructions.
But it doesn't work on a var pattern:
```
string M() { }

void M2()
{
  if (M() is var$$ x && x.Length > 0) // GoToDefinition on `var` should go to definition of `string` type
  {
  }
}
```

Looking at compiler test `SwitchExpression_10`, I think that `GetDeclaredSymbol` and `GetTypeInfo` work on var patterns, so I suspect this is an IDE problem.

**Comment by Youssef1313** [comment]
One difference to note is that `var` in patterns is parsed as `VarKeyword`. While in local declarations it's parsed as `IdentifierToken`.

**Comment by Youssef1313** [comment]
Actually a similar issue exists for:

```csharp
            foreach (var (k, v) in new Dictionary<int, int>())
            {

            }
```

My above comment may be irrelevant.

**Comment by Youssef1313** [comment]
I'm not able to debug currently.

But I see the following method is used by SymbolFinder:

```csharp
        public bool IsBindableToken(SyntaxToken token)
        {
            if (this.IsWord(token) || this.IsLiteral(token) || this.IsOperator(token))
            {
                switch ((SyntaxKind)token.RawKind)
                {
                    case SyntaxKind.DelegateKeyword:
                    case SyntaxKind.VoidKeyword:
                        return false;
                }
 
                return true;
            }
 
            // In the order by clause a comma might be bound to ThenBy or ThenByDescending
            if (token.Kind() == SyntaxKind.CommaToken && token.Parent.IsKind(SyntaxKind.OrderByClause))
            {
                return true;
            }
 
            return false;
        }
```

I suspect that it returns true for `var` when it's IdentifierToken, but not when it's VarKeyword.

**Comment by Youssef1313** [comment]
@jcouv I opened #51620 in an attempt to fix this.
