### ISSUE TITLE
Compiler warnings (Like CS8019) triggers on generated code

### ISSUE THREAD

**Issue by vbfox** [dotnet/roslyn#5162]
I'm trying to enable all possible warnings as error by default but `CS8019` can't be enabled due to generated code that can't be ignored :( (My example is `CS8019` but i'm sure that i'll find a few more as none of the compiler warnings seem to check for generated code)

It's can even be enabled as a warning as otherwise it flood the error list with non-actionable lines.

For example `GenerateTargetFrameworkMonikerAttribute` generated files trigger it :

```raw
C:\Users\jroncagl\AppData\Local\Temp\.NETFramework,Version=v4.5.1.AssemblyAttributes.cs(2,1)
: warning CS8019: Unnecessary using directive. [c:\Code\test.csproj]
```

But winforms `*.Designer.cs` or WPF `*.g.cs` files also generate it.

The warning is generated in [`CSharpCompilation.cs` method `ReportUnusedImports`](https://github.com/dotnet/roslyn/blob/f1702c92cbdb952d8d62e49d11a0f018fe002036/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L1701).

Suggestion
----------

I would suggest that the compiler (And IDE as the analyzers also run here) exclude by default generated files (With a documentation of how this distinction is made) from all warning and errors that wouldn't fail the build (Coming from analyzers or from the compiler provided diagnostics).

Related
----------

This issue is related to a few others :
* *Exclude files or folder from running through the analyzers* #3705 : It would be an ugly hack to have to use manual ignores for files generated in temp folder, and even if it would work for `*.Designer.cs` files it would mean that every .NET developer need to copy paste the same ignores in all projects.
* *Light bulb code fix doesn't work on generated files* #2753 : Is a related issue where the `FixAllProvider` patched this problem after the fact and created discrepencies
* *Expose a public API to tell whether Document/SyntaxTree is likely a generated file* #4530 : As the analyzer runner doesn't handle it all analyzers need to duplicate the code handling it.

**Note**: `IDE0005` is a little bit better as it seem to ignore WPF generated files due to `<auto-generated>` markers, but still doesn't ignore `.NETFramework,Version=v4.5.1.AssemblyAttributes.cs` or `*.Designer.cs`.

**Comment by lgolding** [comment]
We will track the work for this in #3705. I will add a note to #3705 noting your feedback on the solutions proposed in that issue.

**Comment by BGrojer** [comment]
Is there any known workaround regarding that issue (with VS 2015 - Update2)?

**Comment by shaunluttin** [comment]
This is a solid workaround: http://stackoverflow.com/a/35553079/1108891

**Comment by LaBrassBanda** [comment]
This Workaround is only applicable to the AssemblyAttributes.cs file. It is not working for .g.cs files in general. So, still there is a need for ignoring These files.

**Comment by Gav-Brown** [comment]
Related to #24976 and thus still an issue?
