### ISSUE TITLE
Microsoft.CodeAnalysis.EditorFeatures.Cocoa needs to embed PDBs in its nuget package

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#51621]
Need to ensure that EditorFeatures.Cocoa is including PDBs in the package, at least. Ideally for VS Mac if we can embed the PDBs and embed all sources, that would be even better.

**Comment by davidwengier** [comment]
It doesn't look like there is anything to do here.. the PDBs are embedded and source link is enabled 😕 
![image](https://user-images.githubusercontent.com/754264/109921283-bafc2400-7d0f-11eb-9bc1-b2bda84702f7.png)

FYI @KirillOsenkov

**Comment by KirillOsenkov** [comment]
Thanks! Not sure what went wrong when I was debugging, but nice to know this is working. Thanks for checking!

**Comment by Therzok** [comment]
Are they embedded pdbs?

I'm trying to debug Workspaces.dll, and I get this:
```
Resolved pending breakpoint for 'Microsoft.CodeAnalysis.SQLite.v2.Interop.SqlConnection.Create(Microsoft.CodeAnalysis.Host.IPersistentStorageFaultInjector, string)' to [0x0](no debug symbols).
```

**Comment by KirillOsenkov** [comment]
Certainly looks like embedded pdbs... but I feel like something is still fishy here. Does our debugger not load these symbols?

**Comment by KirillOsenkov** [comment]
The pdbs we're seeing are not embedded:

![image](https://user-images.githubusercontent.com/679326/110054220-930cc080-7d0f-11eb-90fc-262bd23c5eed.png)

Let's investigate further.

**Comment by jmarolf** [comment]
I am confused, what is missing? looking at the nuget package from [here](https://www.nuget.org/packages/Microsoft.CodeAnalysis.EditorFeatures.Cocoa/3.9.0-5.21120.8) there are both pdbs and embedded source information.

![image](https://user-images.githubusercontent.com/9797472/110060889-7bd3d000-7d1b-11eb-8139-2b535d058ebf.png)

Is there an internal package that is not _not_ embedding source and _not_ including the pdb?

**Comment by KirillOsenkov** [comment]
No, the packages that are being inserted into VSMac have the pdb on the side, but we want it embedded because this solves two big headaches for us. Minimize file handles and deploy to output not working for pdbs.

**Comment by jmarolf** [comment]
hmm, it seems an explicit decition was made to not do this so as to not bloat binary size for end users: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L29-L42

**Comment by tmat** [comment]
Correct. We ship no VS/Roslyn/dotnet binaries with embedded PDB. I don't see why this would be an exception.

**Comment by KirillOsenkov** [comment]
Not saying we should change the Windows binaries or NuGets. Just talking about VSMac. We have valid, real reasons to strongly prefer embedded pdbs. Will need to think more about it.

**Comment by jmarolf** [comment]
I see, so the ask is to have a separate signed build for VSMac that has all the pdbs embedded? I assume you just consume the .NET Framework 4.7.2 dependencies?

**Comment by KirillOsenkov** [comment]
Not yet, we'll need to think what this means. @davidwengier the NuGets that we insert into VSMac - how are they built? Are those the same that are published for Windows as well? If so, we wouldn't want to change them to embedded because we don't want to change it for Windows. On the other hand, having a separate build just for VSMac seems wasteful. But before that, I'd like to resolve the confusion because half the sources show that the pdbs are external, the other say that they are embedded, and I'm confused. The NuGets I have in my cache on Mac have external pdbs, but you guys keep pointing me to the embedded pdbs. Is Cocoa a special case already? But why not on my machine?

**Comment by davidwengier** [comment]
The packages inserted in VS Mac are the same ones that are inserted into VS Windows, from the same signed build. Also we only insert _after_ the packages have been inserted into VS Windows so we never get into a situation where the two products have different bits.

A separate signed build could still achieve that, but I agree it seems overkill. Though of course, not being able to debug is a pretty big annoyance, but perhaps mitigated somewhat by some of the new plans to publish packages specifically for VS Mac validation, as that could presumably have a different configuration.

**Comment by KirillOsenkov** [comment]
So @davidwengier how is it that you were showing me a screenshot with embedded pdbs? Sorry I don’t want to be annoying, I just want to understand how it all works.

**Comment by davidwengier** [comment]
Oh, I should have mentioned, sorry. My screenshot is fully explained by Jon's link: Nuget Package Explorer was crashing for me when I tried to open a package from a feed, so I was not loading the actual package that VS Mac uses, I was using a locally built one.

**Comment by jmarolf** [comment]
Right, the rules are:

## Official build:
- Build standalone Portable PDBs to reduce the size of the binaries.
- Convert Portable PDBs to Windows PDBs and publish the converted PDBs to Symbol Store to allow WinDBG, Watson and other tools to find symbol format they understand.
## PR validation build:
- Embed PDBs to make it easier to debug crash dumps captured on the CI machine.
## Local Developer build:
- Embed PDBs to be consistent with PR validation build.

**Comment by KirillOsenkov** [comment]
I see, that explains it, thanks.

**Comment by KirillOsenkov** [comment]
@Therzok what are your thoughts? Shall we fix copying pdbs to output and ship external pdbs in VSMac?

**Comment by Therzok** [comment]
@KirillOsenkov We already did that until recently, migrating to SDK projects broke copying PDBs. There's a PR already up for it.

**Comment by tmat** [comment]
> We have valid, real reasons to strongly prefer embedded pdbs.

What are those reasons? Does VS Mac debugger not support symbol servers?

**Comment by KirillOsenkov** [comment]
Macs by default have a limited number of open file handles per process (256). We can increase that to 2048 but even then every open file costs a file handle. You can read more about `ulimit`. Not the end of the world but we’ve been trying to embed where it makes sense to be frugal. Still we periodically run out of handles.

**Comment by KirillOsenkov** [comment]
I think we can close this issue now.
