### ISSUE TITLE
Green highlight over entire C# document

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#51626]
The last few days of dogfooding have occasionally shown an entire .cs file turn yellowish-green till I move the caret:

![image](https://user-images.githubusercontent.com/3548/109829299-9d896600-7bfa-11eb-8bf8-29837704c1dd.png)

No idea why.

VS 16.10 Preview 2 (31101.237.main)

Original text:

```cs
using System;
using System.IO;
using YamlDotNet.RepresentationModel;

var mappingNode = new YamlMappingNode(
    new YamlScalarNode("NULL"), new YamlScalarNode("value"),
    new YamlScalarNode("e"), new YamlScalarNode("NULL")
    );
var doc = new YamlDocument(mappingNode);
var stream = new YamlStream(doc);
var sb = new StringWriter();
stream.Save(sb);

Console.WriteLine(sb);

var readStream = new YamlStream();
readStream.Load(new StringReader(sb.ToString()));
var readDoc = readStream.Documents[0];
YamlNode value = ((YamlMappingNode)readDoc.RootNode)["e"];
Console.WriteLine(((YamlScalarNode)value).Value); // expect "value"
```

**Comment by Youssef1313** [comment]
@AArnott Do you have any repro steps for this?

**Comment by AArnott** [comment]
Not precisely. The simplest case is the single document project above. When it happens, it seems to be when I click around and then wait several seconds (it doesn't happen immediately). Maybe it was after I click with a comment, I don't recall.

**Comment by jinujoseph** [comment]
@AArnott is it possible to get us a heapdump to look at ?

**Comment by AArnott** [comment]
Yes. It just happened again: [dump file](https://microsoft-my.sharepoint.com/:u:/p/andarno/EdraJwIjkfZBmWT-m3zgAVYBZvQOjvUZDvwmjM-WHlG6cA?e=Tt7CZw)

**Comment by AArnott** [comment]
Have a repro:

In a source file with this:

```cs

unsafe
{
        uint resumeHandle = 0;
        uint preferredMaximum = 65536;
        DHCP_IP_ARRAY* enumInfo = stackalloc DHCP_IP_ARRAY[0];
        var result = PInvoke.DhcpEnumSubnets("10.130.224.11",
                                            ref resumeHandle,
                                            preferredMaximum,
                                            ref enumInfo,
                                            out var elementsRead,
                                            out var elementsTotal);
}
```

Type into the first line: `using M` and the whole thing turns green:
![image](https://user-images.githubusercontent.com/3548/116492139-c162d400-a858-11eb-9912-e4826c1a176b.png)


Repro: [CsWin32Sandbox.zip](https://github.com/dotnet/roslyn/files/6395792/CsWin32Sandbox.zip)

**Comment by Youssef1313** [comment]
Just hit this!

![image](https://user-images.githubusercontent.com/31348972/122600695-7737eb00-d070-11eb-9ef0-3a5e0bdf01d8.png)

**Comment by JoeRobich** [comment]
Hmm. Wonder if that is the highlight definition tag being misapplied..
![image](https://user-images.githubusercontent.com/611219/122601247-d7ee0600-d025-11eb-9f56-885fa2707946.png)

**Comment by Youssef1313** [comment]
Here is a seemingly consistent repro for me:

![gifgreen](https://user-images.githubusercontent.com/31348972/122688366-21a04180-d21c-11eb-9557-2b7e2baf22ac.gif)

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Immutable;
using System.Linq;

var comp = CSharpCompilation.Create(null, null, new[] { MetadataReference.CreateFromFile(typeof(Console).Assembly.Location) });

var dummyTree = SyntaxFactory.ParseSyntaxTree("using System;");

var compClone = comp.AddSyntaxTrees(dummyTree);

var @namespace = compClone.GetSemanticModel(dummyTree).GetSymbolInfo(dummyTree.GetCompilationUnitRoot().Usings.First().Name).Symb;

Console.Read();

```

**Comment by Youssef1313** [comment]
@JoeRobich Confirmed the issue goes away when I disable "Highlight references to symbol under cursor"

**Comment by CyrusNajmabadi** [comment]
Looks to be related to 'simple programs'

**Comment by AArnott** [comment]
What is this about not providing additional information? What info was requested? Shouldn't this issue be reactivated?

**Comment by CyrusNajmabadi** [comment]
@AArnott i haven't seen this.  have you hit this recently?

**Comment by AArnott** [comment]
I have not.

**Comment by CyrusNajmabadi** [comment]
Closing out then :)
