### ISSUE TITLE
Spurious CS8620 in SDK 5.0.200 (post VS 16.9 update) for nullable enum parameters with non-null default values.

### ISSUE THREAD

**Issue by EamonNerbonne** [dotnet/roslyn#51622]
**Version Used**: 
SDK Version: 5.0.200
**Steps to Reproduce**:

Program.cs:
```C#
#nullable enable
using System;
Bla();    //CS8620: Argument of type 'int' cannot be used for parameter 'x' of
            //type 'DayOfWeek?' in 'void Bla(DayOfWeek? x = 1)' due to
            //differences in the nullability of reference types.

static void Bla(DayOfWeek? x = DayOfWeek.Monday) { }
```
project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Expected Behavior**:
Compiles and runs without warning.

**Actual Behavior**:

warning CS8620: Argument of type 'int' cannot be used for parameter 'x' of type 'DayOfWeek?' in 'void Bla(DayOfWeek? x = 1)' due to differences in the nullability of reference types.

**Comment by jaredpar** [comment]
@RikkiGibson can u take a quick look at this?

**Comment by EamonNerbonne** [comment]
Incidentally, this is a regression; worked fine on whatever the last stable version included in VS was.

**Comment by RikkiGibson** [comment]
It looks like this only occurs when the enum type is from metadata.
