### ISSUE TITLE
Source Generator doesn't execute with package version 3.9.0 and SDK 5.0.100

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/roslyn#51630]
**Version Used**: 

I had build failures, because my source generator didn't run after updating to https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/3.9.0 and https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/3.9.0, because I didn't also update the SDK to 5.0.200.

**Steps to Reproduce**:

1. The failing build can be seen [here as a GH workflow](https://github.com/excubo-ag/Generators.Blazor/runs/2022208190?check_suite_focus=true), based on https://github.com/excubo-ag/Generators.Blazor/commit/9540630e6aab830a00725e7bf7b29bf93ed8f1ac
2. Update to SDK 5.0.200
3. With this, the build succeeded, see [here, the subsequent GH workflow](https://github.com/excubo-ag/Generators.Blazor/runs/2022554105?check_suite_focus=true), based on https://github.com/excubo-ag/Generators.Blazor/commit/0e13b62762cf72eb6db9c2a409e45dcc62fcdf50

**Expected Behavior**:

The SG should execute as before.

**Actual Behavior**:

The SG worked fine with v3.8.0 for both packages. Updating to v3.9.0 did result in build failures in the project that utilizes the SG. Even if SDK 5.0.200 is a requirement for that package, I would expect a descriptive error message rather than silent failure. The only reason this wasn't a silent failure is an integration test project. The SG project itself compiles, but using it fails..

**Comment by Youssef1313** [comment]
Closely related to https://github.com/dotnet/roslyn/issues/51478. However, this one asks for an error message instead of this being documented.

FYI @jmarolf

**Comment by jmarolf** [comment]
I'll use https://github.com/dotnet/roslyn/issues/51478 to track this.
