### ISSUE TITLE
Proposal: Null-conditional Assignment (Lazy Initialization Operator)

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5163]
Currenty (no concurrency check):
```
public Foo Foo => _foo ?? (_foo = new Foo());
```
Null-conditional Assignment:
```
public Foo Foo => _foo ?= new Foo();
```
This can be implemented in a way that properly use the `System.Threading.LazyInitializer` class.

**Comment by HaloFour** [comment]
Dupe of #3366.

**Comment by alrz** [comment]
@HaloFour Sorry I didn't see it, since it's closed. They didn't mention `LazyInitializer ` though, Nor the use case I suggested here.

**Comment by HaloFour** [comment]
Well there is #3630 specifically for lazy initialization using a decorator on property signatures.  Using the operator syntax makes it feel like it is much more general purpose.  The fact that it could be used to emulate lazy behaviors in properties I don't think matters much, and if it would behave differently than a null assignment in that context I think that would make it confusing.

**Comment by alrz** [comment]
@HaloFour Lazy initialization is not bounded to properties. you still want to use it in other places. what about a private field? It *is* general purpose. you can use them everywhere for initializing members. and it just works — thread safely.

**Comment by alrz** [comment]
This is neatly covered by replace/original feature.
```cs
public sealed class Foo {
  [Lazy]
  public object Value => GetShit();
}

partial class Foo {
  object mValue;
  replace int Value => mValue?? (mValue= original);
}
```
Thread safety and other stuff is up to the code gen provider.
