### ISSUE TITLE
"Go to all" and "Go to types" don't work for records

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51672]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Go-to-all-and-Go-to-types-dont-work/1252528?preview=true)._

---
[severity:It bothers me. A fix would be nice]
If I declare a record type, and enter the type's name in "Go to all" or "Go to types", it isn't found.

---
#### Feedback Bot on 11/11/2020, 11:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Maryer Ma [MSFT] on 11/12/2020, 02:22 AM: 

<p>Thank you for your feedback! Based on your description so far, we were unable to reproduce it on 16.8.0. If we misunderstood your question, could you please correct us? In order to investigate your issue further, can you help to confirm several questions?</p>
<ol>
<li>Which project type and language you use?</li>
<li>Are you installed other extensions in your machine? (Such as Resharper? Could you try to uninstall other extensions and then check whether your issue also reproduces or not?)</li>
<li>Can you try to create a new simple solution(C# Console App or C++ Console App) and check if your problem also reproduces?</li>
<li>Can you try to reset all VS settings(Navigate to Tools-&gt; Import and Export Settings, then select ‘Reset all settings’) or repair your VS and then check whether your problem also reproduces or not?</li>
<li>Can you please provide more info with your issue (Detail repro steps, simply project or repro video)?<br>
Please feel free to let us know if you have any doubt. We look forward to hearing from you!</li>
</ol>

#### Thomas LEVESQUE on 11/12/2020, 06:24 AM: 

<ol>
<li>.NET 5.0 , C#. Project type doesn’t seem to matter (I noticed it in an <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core app, but also reproduced it in a console app)</li>
<li>Just what came out of the box (fresh install).</li>
<li>Yes, I reproduce it in a new solution.</li>
<li>Like I said, it’s a fresh install. And I saw it on 2 different machines, so I don’t think it’s an installation issue.</li>
<li>See attached solution (<a target='_blank' href="https://aka.ms/dc/file?name=B3a147c2bf4674ec5b5c0bb648e9a6b7b637407876528640092_ConsoleApp1.zip&amp;tid=3a147c2bf4674ec5b5c0bb648e9a6b7b637407876528640092">ConsoleApp1.zip</a>). There is a <code>PersonClass</code> class and a <code>PersonRecord</code> record. If you open Go to all, and type <code>t Person</code>, only <code>PersonClass</code> appears, not <code>PersonRecord</code></li>
</ol>

#### Maryer Ma [MSFT] on 11/17/2020, 00:23 AM: 

<p>@<a target='_blank' href="https://developercommunity2.visualstudio.com/users/49178/ThomasLEVESQUE.html">Thomas LEVESQUE</a><br>
Thank you for replied. We tried the attached solution you provided, and found there is only one type ( PersonClass ) in the solution, so it only can search the one. It’s expected behavior. If we misunderstood your question, could you please correct us?  Please feel free to let us know if you have any doubt. We look forward to hearing from you!<br>
<img src="https://aka.ms/dc/image?name=Bec022622b329477eb2a14df708476b98637411986116286412_gotoall.png&amp;tid=ec022622b329477eb2a14df708476b98637411986116286412" alt="gotoall.png"></p>
<p><img src="https://aka.ms/dc/image?name=B4c9b92493257475b95da7af22d6bbe2d637411984364579374_gotoall.gif&amp;tid=4c9b92493257475b95da7af22d6bbe2d637411984364579374" alt="gotoall.gif"></p>

#### Thomas LEVESQUE on 11/19/2020, 01:09 AM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=265364">Maryer Ma [MSFT]</a></p>
<blockquote>
<p>We tried the attached solution you provided, and found there is only one type ( PersonClass ) in the solution, so it only can search the one</p>
</blockquote>
<p>PersonRecord is also a type. <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types">Record types are a new feature in C# 9</a>.<br>
The fact that it appears as a method in the solution explorer is also a bug (probably related)</p>

#### Feedback Bot on 11/25/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/30/2020, 04:01 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### microsoft on 1/14/2021, 08:57 AM: 

<p>PLEASE fix this. This is really annoying. I am using the CQRS architecture and I use command classes for every action. These are implemented with the new C# record features, but when I use CTRL-T and enter the command name (= record name), I can't find them anymore. This is very confusing!</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Daniel Berghold on 3/3/2021, 08:57 AM: 

<p>Dear Microsoft, this bug is also causing a lot of confusion in our team! Team members are using CTRL-T to jump to DTOs or command objects but can’t find them and are confused therefore… Please consider fixing it.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Hmm, I recall fixing something like this. I also couldn't reproduce in 16.9.

**Comment by CyrusNajmabadi** [comment]
the `t Name` form doesn't seem to work for records.

**Comment by Youssef1313** [comment]
@CyrusNajmbadai 

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Features/Core/Portable/NavigateTo/NavigateToItemKind.cs#L14

A check for this might be missing somewhere (probably in the internal implementation)

**Comment by Youssef1313** [comment]
I dug a bit in this and I think it's indeed an internal implementation.

The `Kinds` of this filter `Microsoft.VisualStudio.PlatformUI.NavigateToSession.NavigateToSearchOperation.FilterParameters` doesn't contain record. I think I can workaround this in Roslyn, but better to fix the root issue:

![image](https://user-images.githubusercontent.com/31348972/110146056-c9674000-7de2-11eb-8a5a-5fc2af5cd78d.png)

 @jinujoseph Would you be able to route this to the correct team

**Comment by jinujoseph** [comment]
cc @olegtk for info and attention

**Comment by olegtk** [comment]
Route it to the Editor, @jinujoseph. Thanks!

**Comment by Youssef1313** [comment]
@olegtk Any update on this? Note that record structs will be needed as well.

**Comment by CyrusNajmabadi** [comment]
I'm not sure we need platform/editor to do anything here. We can just bucket record classes and structs under classes and structs for purposes of inter operating here.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Alright, I'm going to look at this alternative.

**Comment by olegtk** [comment]
I haven't seen it on the editor triage, did you route it? But you can also just go ahead and send PR to VS-Platform repo adding Record to https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FProductivity%2FNavigateTo%2FDef%2FNavigateTo%2FNavigateToItemKind.cs&_a=contents&version=GBmain
