### ISSUE TITLE
Could not infer type of the Select after a typeof and hence no intellisense in the IDE

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#5169]
Split bug 1 of 2 from #4918

``` C#
using System.Linq;
using System.Text;

public static class LazyToStringExtension
{
    public static string LazyToString<T>(this T obj) where T : class
    {
        StringBuilder sb = new StringBuilder();
        typeof(T)
            .GetProperties(System.Reflection.BindingFlags.Public)
            .Select(x => x$$)
    }
}
```

With caret at `$$`, type period `.`

At [CSharpRecommendationService.GetSymbolsOffOfExpression](https://github.com/dotnet/roslyn/blob/a53f7c1e13e4d722ba10c6ad1a9b5b340138ecff/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs#L352-L359): 

```
the expression is `identifier x`. 
leftHandBinding is `empty`. [call to `GetSymbolInfo`]
container is `ErrorType`. [call to `GetTypeInfo`]
normalSymbols are `empty`. [call to `GetBestOrAllSymbols`]
```

**Expected**:  Intellisense, quickinfo, Goto definition, Find references work at caret position where the user will type `.GetValue(obj)`

**Actual**: no features work here.

Can the compiler team take a look at why we couldn't bind here?

**Comment by jaredpar** [comment]
This is fixed now with @gafter work on type inference in lambdas.
