### ISSUE TITLE
Print DiagnosticIds in the Report Analyzer Format

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [dotnet/roslyn#51695]
Hello.

This new feature suggestion is related to the [Report Analyzer Format](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Report%20Analyzer%20Format.md), which can be obtained by running the build with the `/v:d /p:reportanalyzer=true` parameters.

In SonarSource, we often ask to our users to share verbose logs with `/p:ReportAnalyzer` to generate the report with time spent by each analyzer.

One problem we have is that in the output, the analyzer class name is written, and it's not easy to map this to the supported diagnosticId(s). When providing support, it is useful to know the diagnosticId(s), too.

We would like to ask if there is a recommended way to include the rule ID in the `/p:ReportAnalyzer` logs, or if it would be feasible to be done on the Roslyn side. We are aware the multiple DiagnosticIds can be assigned to an Analyzer, and this feature would need to handle this scenario as well.

ACTUAL:
```
  Time (s)    %   Analyzer
     1.352   87   SonarAnalyzer.CSharp, Version=8.19.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244
     0.110    7      SonarAnalyzer.Rules.CSharp.UnusedReturnValue
     0.039    2      SonarAnalyzer.Rules.CSharp.UnusedPrivateMember
```
EXPECTED:
```
  Time (s)    %   Analyzer
     1.352   87   SonarAnalyzer.CSharp, Version=8.19.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244
     0.110    7      SonarAnalyzer.Rules.CSharp.UnusedReturnValue (S3241)
     0.039    2      SonarAnalyzer.Rules.CSharp.UnusedPrivateMember (S1144, S4487)
```
In the above example, the analyzer `UnusedReturnValue` has only one diagnosticId, whereas the `UnusedPrivateMember` analyzer has two diagnosticIds.

Thanks.

**Comment by Youssef1313** [comment]
I opened a PR to add this. But not sure if the team will want to do this or not.

**Comment by jmarolf** [comment]
This seems like a good idea to me. @sharwell and @mavasani any objections?

**Comment by sharwell** [comment]
No, it's the primary annoyance with https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/452
