### ISSUE TITLE
IDE0078 codefix produces incorrect code

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#51693]
![image](https://user-images.githubusercontent.com/31348972/110137835-f531f800-7dd9-11eb-8e04-6394e7fa6739.png)

The fixed code should be `type is INamedSymbol { EnumUnderlyingType: not null } namedTypeSymbol`

**Note:** I think this can change semantics for overridden equality operators.

**Comment by CyrusNajmabadi** [comment]
@alrz ?

**Comment by alrz** [comment]
Thanks for tagging me. I will look at these at once when I can.

**Comment by alrz** [comment]
We never modify an existing pattern in this codefix. We should consider doing that (similar to the wip refactoring feature), since it's already an expensive analysis, I think perf impact would be acceptable.
