### ISSUE TITLE
Test plan for parameterless struct constructors

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#51698]
Proposal: [parameterless-struct-constructors.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-10.0/parameterless-struct-constructors.md)
Branch: [features/struct-ctors](https://github.com/dotnet/roslyn/tree/features/struct-ctors)

- [x] `-langversion`:
  - [x] for parameterless ctor (see `PublicParameterlessConstructor`)
  - [x] for field initializers (see `FieldInitializers_01`)
- [x] `public` and non-`public` ctors declared in source (see `PublicParameterlessConstructor` vs. `NonPublicParameterlessConstructor_01`)
- [ ] `extern` and `unsafe` are valid ctor modifiers
- [ ] `: this()` and `: base()` initializers:
  - [ ] `: base()` initializer disallowed
  - [x] `: this()` initializer allowed from other ctors (see `ThisInitializer_01`)
  - [x] `: this(arg0, ...)` initializer allowed from parameterless ctor (see `ThisInitializer_02`)
- [x] `record struct` parameterless ctor must include `: this(arg0, ...)` (see `TypeDeclaration_ParameterlessConstructor_OtherConstructors`)
- [ ] `default` ignores parameterless ctor
- [x] `new()` invokes parameterless ctor:
  - [x] from `new S()` and `new S { ... }` (see `PublicParameterlessConstructor`)
  - [x] from `new S()` and `new S { ... }` in expression tree (see `ExpressionTrees`)
  - [x] from `new T()` with `where T : struct` and `where T : new()` (see `PublicParameterlessConstructor`)
- [x] all fields assigned:
  - [x] all fields have initializers if any have initializers and no ctors (see `FieldInitializers_01` and `FieldInitializers_02`)
  - [x] all fields have initializers or are explicitly assigned in each explicit ctor (see `FieldInitializers_01` and `FieldInitializers_02`)
- [x] field initializers and initialization order with:
  - [x] no constructors (see `FieldInitializers_None`)
  - [x] explicit parameterless ctor (see `FieldInitializers_None`)
  - [x] explicit ctor with parameters (see `FieldInitializers_None`)
  - [x] explicit ctor with `: this()` initializer with/without parameterless ctor (see `ThisInitializer_03`)
  - [x] explicit parameterless ctor with `: this(arg0, ...)` initializer (see `ThisInitializer_03`)
- [x] field initializers and initialization order on `record struct` with cases above and: (see `TypeDeclaration_ParameterlessConstructor_Initializers`)
  - [ ] no `()`
  - [ ] `()`
  - [ ] `(arg0, ...)`
- [x] nullability analysis (initial state of fields in ctor bodies) for field initializer cases above (see `NullableAnalysis_*`)
- [x] error for `new S()` in parameter default value if `S` has parameterless ctor (see `ParameterDefaultValues_*`)
- [ ] analyzer checks runtime capability and warns for `new T()` with `where T : struct` or `where T : new()` on desktop framework: [dotnet/roslyn-analyzers/issues/5272](https://github.com/dotnet/roslyn-analyzers/issues/5272)

**Comment by tmat** [comment]
- [ ] EnC analyzer needs to be updated
