### ISSUE TITLE
VS 16.9 Const Numbers not Implicitly Castable

### ISSUE THREAD

**Issue by Noggog** [dotnet/roslyn#51697]
Hey all!

Downloaded the newest VS 16.9, which comes with the SDK upgrade I imagine as well.

Some code that had been compiling and in production for months is now failing to compile.  (I know of one instance that was committed in Dec 2020, and is now failing to compile as of yesterday /w the 16.9 update).  This is a minimal recreation of it:
```cs
public class TestClass
{
    private byte _someByte;

    public bool SomePublicBool
    {
        get => _someByte > 0;
        set => _someByte = value ? 1 : 0;
    }
}
```

The `_someByte = value ? 1 : 0` line fails, with the message "Cannot implicitly convert type 'int' to 'byte'."

Is this a new more strict compiler rule that now requires me to cast a hardcoded numeric value?  Before it was smart enough to realize I'm assigning to a `byte`, and so my hardcoded values should be seen as `byte` without the need for an explicit cast.

Seems odd to have a seemingly regressive backwards incompatible change like this.

**Comment by jmarolf** [comment]
@jaredpar isn't this by-design?

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/roslyn/issues/51597.

**Comment by Noggog** [comment]
Does look to be a duplicate. Sorry about that!
