### ISSUE TITLE
False positive IDE0078

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#51691]
I don't see how this can be written by using pattern matching. And the suggested codefix is invalid.

![image](https://user-images.githubusercontent.com/31348972/110134230-d5003a00-7dd5-11eb-8220-8e9075d65c86.png)

Another similar case:

![image](https://user-images.githubusercontent.com/31348972/110134756-6b346000-7dd6-11eb-8d9e-1add2444b916.png)

Also:

![image](https://user-images.githubusercontent.com/31348972/110136127-ffeb8d80-7dd7-11eb-8176-49ba29d45851.png)

**Comment by CyrusNajmabadi** [comment]
@alrz ?
