### ISSUE TITLE
SA1313 analyzer throws InvalidCastException

### ISSUE THREAD

**Issue by pdelvo** [dotnet/roslyn#5171]
SA1313 throws an exception on the following code:
```csharp
Action<int> foo = _ => { };
```

with stack trace
```
   bei StyleCop.Analyzers.NamingRules.SA1313ParameterNamesMustBeginWithLowerCaseLetter.NameMatchesAbstraction(ParameterSyntax syntax, SemanticModel semanticModel) in SA1313ParameterNamesMustBeginWithLowerCaseLetter.cs:Zeile 94.
```

because syntax.Parent is a SimpleLambdaExpressionSyntax and not a ParameterListSyntax

**Comment by sharwell** [comment]
Duplicate of DotNetAnalyzers/StyleCopAnalyzers#1442 :expressionless: and fixed in the latest release.
