### ISSUE TITLE
Proposal: "with" expressions for record types

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5172]
This is a proposed enhancement to the proposal for _records_ in #206.

A new expression form is proposed:

> _primary-expression_:
> &nbsp;&nbsp;&nbsp;&nbsp;_with-expression_:
> _with-expression_:
> &nbsp;&nbsp;&nbsp;&nbsp;_primary-expression_ `with` `{` _with-initializer-list_ `}`
> _with-initializer-list_:
> &nbsp;&nbsp;&nbsp;&nbsp;_with-initializer_
> &nbsp;&nbsp;&nbsp;&nbsp;_with-initializer_ `,` _with-initializer-list_
> _with-initializer_:
> &nbsp;&nbsp;&nbsp;&nbsp;_identifier_ `=` _expression_

The token `with` is a new context-sensitive keyword.
### Semantics

The _with-expression_ is translated into a primary constructor invocation that copies members from the _primary-expression_ on the left-hand-side into constructor's parameters, but with some of those replaced by values from the initializer list. Because it depends on the presence of a primary constructor, this is only defined for record types (#206).

(This needs to be described in more detail, including specifying that the left-hand-side expression is evaluated once, the constraints on its type, that identifiers in a _with-intiializer_ bind to a property (or field) of that type, and that the correspondence between constructor parameters and properties are used according to the spec for _records_. Similarly it needs to give definite assignment rules, order of evaluation, etc.)
### Example:

``` cs
class Person(string FirstName, string LastName);
...
    Person p = new Person(FirstName: "Neil", LastName: "Gafter");
    Person q = p with { FirstName = "Neal" };
```

The latter is translated into

``` cs
    Person q = new Person(FirstName: "Neal", LastName: p.LastName);
```

To be clear, the `Person` declaration's expansion includes the following:

``` cs
class Person
{
    public string FirstName { get; }
    public string LastName { get; }
    public Person(string FirstName, string LastName)
        { this.FirstName = FirstName; this.LastName = LastName; }
    // as well as other members not relevant to this issue
}
```

Because the semantics of this new expression form require a language-defined mapping between constructor arguments and properties of the type, and a _primary_ constructor, it is only defined for record types as specified in #206. Expanding this construct to other types may be the subject of a separate proposal.

**Comment by gafter** [comment]
@MadsTorgersen I believe you were interested in extending this to a pattern-based construct.

**Comment by diryboy** [comment]
Nice.

**Comment by Eyas** [comment]
Why not define a compiler-generated/language-specified similar to

```cs
Point With(int? X = null, int? Y = null, int? Z = null) =>
    new Point(X ?? this.x, Y ?? this.y, Z ?? this.z);
```

Nullable isn't quite right as it requires value types, but I wonder why the language needs to be extended here. Methods and named parameters seem to be quite enough here:

```cs
class Point(int X, int Y, int Z);
...
    Point p = ...;
    Point q = p.With(Y: 2 );
```

**Comment by gafter** [comment]
@Eyas How would that work when the type is a nullable or reference type? You say that it isn't quite right, but what do you have in mind that *is* quite right?

**Comment by Eyas** [comment]
Not quite there yet; rather wondering why something like this wasn't pursued. Is there something about extending the language with a brand-new construct that is actually good/needed here? Or was there something explicit about how a method-like approach is unworkable?

How I saw it, worse comes to worse, the compiler could treat a `RecordType.With(...)` as syntactic sugar and transform it exactly as you proposed.

**Comment by diryboy** [comment]
@Eyas Isn't it more efficient for compiler to pass the members directly than performing checks for every member?

**Comment by gafter** [comment]
@Eyas Doing it without additional language support may be possible but extremely awkward. One approach is to define an `Optional` type with an implicit conversion

```cs
public struct Optional<T>
{
    public readonly bool HasValue;
    public readonly T ValueOrDefault;
    public static readonly Default = default(Optional<T>);
    public static implicit operator Optional<T>(T value) { ... }
    /// and a constructor too...
}
```

Now you can define `With` as follows

```cs
    public Point With(Optional<XType> X = default(Optional<XType>), ...) { ... }
```

Here are some of the disadvantages
- You now have a public type `Optional<T>`, and some of these fields can be of type `Optional<Something>`, which makes the meaning all the more confusing.
- The implementation of this `With` method must necessarily be much slower than the proposed `with` language construct because it is doing at runtime what the proposal does at compile-time.
- The syntax is not very pretty.

Plus, you still have to wire it into the language if you want the language to produce these `With` methods for you, so you're not reducing the concept count by much.

On the other hand, with the proposed `with` feature, you probably want to have some way for programmers to enable the feature for non-record types. Thus my comment to @MadsTorgersen above.

**Comment by Eyas** [comment]
@gafter That's very fair. I had thought of the `Optional` solution, but agree its not worth pursuing for this purpose (might be for the CoreFX folks).

What I floated in my previous post was whether a `.With(...)` can be a 'reserved' method for record types that desugars into a constructor call with no runtime checks at compile time. Upon sleeping on it, I don't think I'm a fan of this either, anymore.

**Comment by MgSam** [comment]
I'm glad there's finally a formal proposal for `with`, as it is sorely needed when working with immutable types. That being said, I don't like tying the feature to record types/primary constructors. Why shouldn't I be able to automatically define a `with` operator for any type? I frequently have classes that I want a copy constructor for, and it's a pain to write and to maintain.

I think auto-implementation of `with`, `ToString`, `HashCode`, and `Equals` is orthogonal to record types. Yes, they're certainly desirable for record types, but I might want these things for any type, or I might want them for only certain properties of a type. 

I think the autoimplementation should be triggered by a separate keyword, and there should even be a way of annotating which properties should participate in the autogeneration of these identity-type methods. 

Currently when you add new properties to a class you likely have to go to 5 different places and make updates and hope you didn't forget one or else your type's sense of identity will get out of whack. While having auto-implementation of these methods for records will help we could do better by making the feature more general and more widely applicable.

**Comment by gafter** [comment]
@MgSam: My note to @MadsTorgersen was to trigger his work on extending support for the `with` operator to "other types" by basing it on some kind of programming pattern or convention.

The `with` operator needs some kind of language-based indication of which constructor it should use, and some language-based indication of the mapping between the constructor parameters and the properties. Those are precisely the things that the primary constructor syntax provides, and it can be used "for any type," and the primary constructor can be written to provide values for only "certain properties of a type".

I can believe that some other syntax might provide all of the things needed for the `with` operator, and yet be applicable to scenarios that are somehow not served well by the primary constructor syntax. I look forward to what @MadsTorgersen or anyone else comes up with.

**Comment by ghord** [comment]
How about requiring the type to have method of the form:
```
Type With<PropertyName>(PropertyType value);
```
So that we can use with keyword even with interfaces like this:

```
public interface IJob
{
    DateTimeOffset Start { get; }
    DateTimeOffset End { get; }
    IJob WithStart(DateTimeOffset start);
    IJob WithEnd(DateTimeOffset end);
}

public class Job : IJob
{
    public Job(DateTimeOffset start, DateTimeOffset end)
    {
        Start = start;
        End = end;
    }
    public DateTimeOffset Start { get; }
    public DateTimeOffset End { get; }
    public IJob WithStart(DateTimeOffset start)  => new Job(start, End);
    public IJob WithEnd(DateTimeOffset end) => new Job(Start, end);
}
```
And use it like this:
```
   var job = GetJob(); //returns some IJob
   var job2 = job with { Start = DateTimeOffset.Now }; // cals job.WithStart(DateTimeOffset.Now)
```

**Comment by HaloFour** [comment]
@ghord That would be interesting.  Would there be specific requirements on the return type of the method?  Let's say in your example `GetJob()` actually returned a `Job` and not an `IJob`, could you use `with` in that case?  What if `Job` defined additional `With` methods?  Could they be used in the `with` initialization as long as they were before `Start` and `End`?

**Comment by gafter** [comment]
@ghord Once you do that, there isn't a lot of added value in the language construct over using the APIs directly. It is much less efficient than the proposal, as it would cause an allocation and copy for each property being modified.

**Comment by ghord** [comment]
@gafter You are right, it doesn't make much sense to cause unnecessary allocations in this case.

How about using @Eyas construct with slight modification:
```C#
Point With(int X = default(int), int Y = default(int), int Z = default(int)) =>
    new Point(X, Y, Z);
```

And allowing compiler to replace default values in optional parameter with values from properties of source object? This technique is already used in caller attributes after all.

**Comment by HaloFour** [comment]
@ghord Or a `with` operator?

```cs
public static operator Point with(int X, int Y) => new Point(X, Y);
```

Then the compilers could look for a convention of a static method called `op_with` and map the public properties/fields to the parameter names.

```cs
Point p2 = p1 with { Y = 2 };
// equivalent to
Point p2 = Point.op_with(X: p1.X, Y: 2);
```

**Comment by Eyas** [comment]
But in both these cases, how do you tell the compiler what values to substitute for the default values? There needs to be a new language construct there. Counting on the names being the same seems hacky. Counting on some special treatment of ` = default(X)` also seems weird.

Perhaps a language construct such as:

```cs
Point With(int X = somekeyword(this.X), int Y = somekeyword(this.Y) ) =>
    new Point(X, Y);
```

Where `somekeyword`, whatever it is, has special compiler treatment, and lets the compiler know to substitute with `p.X`/etc. for any missing param..

**Comment by HaloFour** [comment]
@Eyas I mention having the compiler match the parameter names to the members of the source instance.  Do you not think that is sufficient?

Whether it's a normal method, an operator (static method) or a constructor such a mechanism would need to exist to let the compiler know what the default value should be for any non-specified property.  In my opinion the parameter names is probably sufficient, although an attribute that spells out the name of the member to override may be useful.  I don't think a further language construct is really that necessary.

**Comment by Eyas** [comment]
@HaloFour I did miss that. Matching names seems a bit weird. Does C# do anything like this elsewhere? What happens if someone defines a `with` operator that takes a parameter that does not match a property name. Does it become a required parameter? Or is that a compile-time error?

**Comment by HaloFour** [comment]
@Eyas Literally typing that now.  :smile: 

I think the bigger question about custom "withers" is how to deal with parameters that don't match to members (though whatever mechanism).  Would that be allowed?  Would the consumer be required to supply those parameters?

Also, if using a non-constructor, what if the return type is different?  Could a "wither" perhaps with a non-matched parameter be used to construct a different type?

```cs
public class Point {
    ...
    public static operator Line with(int X, int Y, Point Destination) => new Line(new Point(X, Y), destination);
}
///
Point point = new Point(2, 2);
Line line = point with { Destination = new Point(4, 4) };
```

**Comment by RichiCoder1** [comment]
I'm in the camp that says `With` should be restricted to returning it's parent type, with no exceptions. I would agree with @gafter that if we let `With` take additional parameters, at that point is it really that much better then simply calling the Api directly?

**Comment by HaloFour** [comment]
@RichiCoder1

I'd probably agree.  Even any interesting use cases where such flexibility could be useful are probably just a hair away from being a form of abuse.

I also like the idea that if a custom "wither" is an operator that the compiler can enforce that the return type is appropriate and that all of the properties can be matched.  That way someone can catch that the "wither" isn't valid before it potentially breaks code that attempts to consume it.

```cs
public class Point {
    public readonly int X { get; }
    public readonly int Y { get; }
    public readonly int Z { get; }

    public Point(int x, int y, int z) {
        this.X = y; this.Y = y; this.Z = z;
    }

    // good
    public static Point operator with(int X, int Y, int Z) => new Point(X, Y, Z);

    // compiler error, wrong return type
    public static Location operator with(int X, int Y, int Z) => new Location(); 
    // compiler error, Foo is not a property of Point
    public static Point operator with(int X, int Y, int Z, int Foo) => new Point(X, Y, Z);

    // compiler error, Z is not a parameter?
    // or should withers with fewer parameters be permitted to facilitate versioning?
    public static Point operator with(int X, int Y) => new Point(X, Y);
}
```

**Comment by RichiCoder1** [comment]
@HaloFour Agreed. Would love to see it just be an operator.

**Comment by alrz** [comment]
I want to propose the `new` keyword to doing so, indicating that it creates a new instance.
```
var p = new p { Y = 2 };
```
and reserve the `with` keyword for re-initializing the same instance, as discussed in #5365:
```
var p = with p { Y = 2 };
```

**Comment by gafter** [comment]
@alrz Your proposal would allow

```cs
new new Point(1, 2) { Y = 2 } { X = 1 }
```

(in this case, `p` is the expression `new Point(1, 2) { Y = 2 }`)

It would also render the following ambiguous:

```cs
new Point(1, 2) { Y = 2 }
```

Is `Point(1, 2)` a method invocation or an object creation expression? Under your proposal it is ambiguous.

Many of the language changes we're pursuing now are intended to support programming with *values* as an alternative to programming through *mutation* of existing variables. Your proposal is at cross-purposes with that.

**Comment by alrz** [comment]
@gafter Alright, that settles it.
but what about the re-initialization syntax? it has nothing to do with new immutable constructs in the langauge, it rather makes life easier for existing codes that actually use these patterns that relyed on mutation (like factory method) .

Are you saying that C#'s going to be fully functional and make mutation obsolete?

**Comment by gafter** [comment]
We're not going to make anything in the language obsolete. But our effort is currently focused on making *safer* things *easier* to do. Mutation is not one of the safer things we're trying to make easier right now.

**Comment by gordanr** [comment]
Very nice proposal @gafter. 

Some thoughts regarding readability in Fluent API.
Both with and without parentheses is valid.
```
var obj1 = (new Test() { PropI = 4, PropS = "Str" }).Method1().Method2();
var obj2 = new Test() { PropI = 4, PropS = "Str" }.Method1().Method2();
```
What about "with" expressions? Do we need parentheses?
```
(obj with { PropI = 5, PropS = "Strn" }).Method1().Method2();
obj with { PropI = 5, PropS = "Strn" }.Method1().Method2(); 
```
It is not so useful, but can we chain "with" expressions? Probably yes.
```
obj with { PropI = 5, PropS = "Str2" };
obj with { PropI = 5} with { PropS = "Str2"};
```

**Comment by gafter** [comment]
@gordanr Since a *with-expression* is syntactically a *primary-expression*, you don't need parens to dot off them, and you can chain with expressions without parens.

**Comment by gafter** [comment]
We discussed this in the LDM today and noted that they don't work "properly" with inheritance. For example, given

```cs
class Person(string Name);
class Student(string Name, int Grade) : Person(name);
```

if you then

```cs
Person me = new Student("Neil", 12);
// correct the spelling of my name
me = me with { Name = "Neal"; }
```

The resulting object is an instance of `Person`, not an instance of `Student`. It has been decapitated!

To address this we need record types to generate a virtual `With` factory method. More in a moment...

**Comment by HaloFour** [comment]
What does this mean for custom "withers"?  Would the `with` expression work via convention as long as the compiler could resolve a `With` method, potentially even as extension methods?  Perhaps added validation on the arguments/properties and return type?

Kind of stinks that there would be additional boilerplate required in order to create these methods properly.  It would still be nice if it could be supported through a form of operator.  As operators are really just a convention is there anything that explicitly forbids instance operators?

:spaghetti: :

```cs
public class Point {
    private readonly int X { get; }
    private readonly int Y { get; }

    public Point(int x, int y) {
        this.X = x;
        this.Y = y;
    }

    // validates that return type matches current type and that parameters match accessible properties
    public Point operator with(int X, int Y) => new Point(X, Y);
    // equivalent to
    public virtual Point With(int X, int Y) => new Point(X, y);
}

public class Point3D : Point {
    private readonly int Z { get; }

    public Point3D(int x, int y, int z) : base(x, y) {
        this.Z = z;
    }

    public Point3D operator with(int X, int Y, int Z) => new Point3D(X, Y, Z);
    // equivalent to
    public sealed override Point With(int X, int Y) => With(X, Y, this.Z);
    public virtual Point3D With(int X, int Y, int Z) => new Point3D(X, Y, Z); 
}
```

**Comment by gafter** [comment]
The `with` language feature, as here designed, requires (1) a language-defined primary constructor, (2) a language-defined correspondence between properties and the primary constructor parameters, and (3) a language-defined correspondence between these and the `with` method parameters.

A record declaration as in #206 will give you those things. Since you don't get those things outside of a record declaration, I think this feature is linked to records *and* in that case the compiler might as well provide the `with` method implementation. As you get deeper in the inheritance hierarchy, implementing these `with` methods becomes a pain. For example, after two levels of inheritance the derived class will have to provide three method implementations.

@MadsTorgersen is looking at making something like the `with` feature more pattern-based, and we've been discussing it for the past couple of weeks. But we don't have a specific proposal to present yet.

**Comment by gafter** [comment]
It isn’t clear that the compiler has enough information to implement `With` methods in the face of inheritance. For example, given:

```cs
class Rectangle(int Width, int Height);
```

which has the compiler-generated method

```cs
public virtual Rectangle With((int Width, int Height) => new Rectangle(Width, Height);
```

and the derived class

```cs
class Square(int Side) : Rectangle(Side, Side);
```

How would the compiler implement the override of `Rectangle.With` in the class `Square`?

I think one reasonable policy is to require the `With` methods in record types, and by default the compiler provides non-virtual implementations. But users may provide their own implementations, which in some cases might be virtual.

**Comment by diryboy** [comment]
If the compiler cannot determine what to generate within the overriding `With` method, and user does not provide one, just generate `throw new InvalidOperationException();`, and issue a compiler warning about this.

**Comment by gafter** [comment]
@diryboy what are the rules the spec will require the compiler to use to figure out what to generate?

**Comment by diryboy** [comment]
The most simple case, inherited type only adds new property, where the original property values are only just passed to the base class constructor for the same property. The `Person` & `Student` case:
```c#
    public override Person With( string Name ) => new Student(Name, this.Grade);
```

Otherwise generally we can utilize the extended `is` operator,  the `Rectangle` & `Square` case would be:
```C#
    public override Rectangle With( int Width, int Height )
    {
        int side;
        if ( base.With(Width, Height) is Square(out side) )
            return new Square(side);
        else
            throw new InvalidOperationException();
    }
```

But consider the following case
```C#
class D1( int X );
class D2( int Y ) : D1(F(Y));

// Generated With methods for D2
    public override D1 With( int X ) => throw new NotImplementedException();
    public virtual D2 With( int Y ) => new D2(Y); // ops, ambiguous overloads introduced
```

Not sure those were all cases, though.

**Comment by gafter** [comment]
I think having the compiler deeply check the semantics of the base invocation clause, and the implementation of properties of corresponding names in the base and derived types, is too complex. Also, I hesitate to add a language construct in such a way that it would cause runtime errors in normal usage.

**Comment by diryboy** [comment]
Agree.

New case, if combine Rectangle/Square and Person/Student
```C#
class A( int X );
class B( int Y, int Z ) : A(Y);
```
What should happen if we execute the following code?
```C#
var b = new B(1, 2);
b = b with { X = 1, Z = 3 };
```

**Comment by gafter** [comment]
Yes, in both cases it is an error to try to `with` properties not declared in the parameter list of the static type of the left-hand-side.

**Comment by diryboy** [comment]
In the second case `b`'s static type is `A`, so `X` is in the parameter list.

**Comment by gafter** [comment]
@diryboy I didn't see that. So in the former case it is a compile-time error "X not a parameter of B". In the latter case you get back a new `A`.

**Comment by diryboy** [comment]
@gafter Isn't that decapitated `b`? As it was constructed with `new B(1, 2)`.

**Comment by gafter** [comment]
@diryboy Indeed, it is decapitated. I think we should allow you to override the underlying factory methods if you want another behavior, as there is no universally reasonable default.

**Comment by diryboy** [comment]
@gafter I see

**Comment by alrz** [comment]
@gafter 

I want to suggest some modifications regarding `with` expression decapitation and record type inheritance (or ADTs).

First of all, I think it would be nice to be able to not repeat every single property of base record types in derived record types if they are nested:

```cs
public class Person(string Name) {
    public class Student(int Grade);
}
```

- A constructor for each type will be generated with each property in the inward order.
- The implicitly base class is the enclosing type (this just works in presence of parameter list).
- Same rules apply to nested classes within nested classes.

The same syntax would work for ADTs:
```cs
public abstract sealed class Option<T>() {
    public sealed class Some(T Value);
    public sealed class None();
}
```
Note: I think having a `using static` for ADTs is not practical (as you [said](https://github.com/dotnet/roslyn/issues/6400#issuecomment-152239471)) in case of a generic ADT.

Also, I think overriding `With` method for records would be confusing (for me, at least). It would be nice to specify the target type (if it's other than static type of the object) in `with` expression:
````cs
Person me = new Student("Neil", 12);
me = me with Student { Name = "Neal" };
```
I think this will be more explicit and self-contained solution to this problem.

**Comment by gafter** [comment]
@alrz I like your suggestion of (optionally?) adding the type to the syntax for `with`. That helps a lot with the decapitation issue.

Your suggestion for inheritance with works well if records are always just aggregates of data that accumulate values down the type hierarchy. It doesn't work well when you step outside that box. For example

```cs
class Rectangle(double Width, double Height);
class Square(double Side) : Rectangle(Side, Side);
```

or

```cs
class Person(string FirstName, string LastName);
class Teacher(string Name) : Person("Professor", Name); // all teachers are named "Professor"
```

In these cases we cannot give any reasonable meaning to `s with Square { Width = 1, Height = 2 }` or `t with Teacher { FirstName = "Poindexter" }`. In the current proposal these would not be allowed, because the properties being "assigned" are not declared in the header of the named type.

One option would be to decide that the aggregation thing is the sweet spot and not try to support more general inheritance like these two examples. That's an issue we're debating right now.

**Comment by alrz** [comment]
@gafter Yes, actually these all work until you don't explicitly specify the base class (in the nested records) and accept the defaults. Then the constructor and `With` overrides would be generated for you. In case of specifying the base class all those assumptions are gone and `s with Square { Width = 1, Height = 2 }` or `t with Teacher { FirstName = "Poindexter" }` wouldn't be permitted and you would declare your own `With` overrides. I think in "normal" cases when you want to declare an ADT tree, mandatory base classes are additional noises and in deep trees would be even confusing.

**Comment by gafter** [comment]
@alrz Maybe. That is a way to bring the two views together.  It does feel a little strange requiring the nesting to match the inheritance hierarchy - or rather, causing the nesting to have so much additional meaning.

**Comment by alrz** [comment]
@gafter Nesting already has additional meaning in the proposed ADT syntax right? Or the whole record syntax which depends on the presence of the parameter list `()`. So I think this can be taken a step further and make it easier (and safer) to declare ADTs or record types. Basically, this makes it consistent between ADT and record type syntax and the difference is just bound to `abstract sealed` modifier, as you can see in my examples.

**Comment by gafter** [comment]
@alrz The only proposed meaning of nesting is a way of saying "here are all the subclasses". But it wasn't intended to modify the meaning of nesting, which already exists today and has meaning.

For example, I sometimes like to move a type into another type when it is used only there or is closely related. It would be strange if that refactoring changes the parameter list of its constructor (and its base class). I also find it strange that the nested type's constructor has some parameters that are implicitly declared, even though some are explicitly declared. It makes it confusing what the scope of those parameters are. It is also strange that adding a base type (that is the same as the implicit base type) changes the signature of the constructor.

It all feels a bit too magical.

**Comment by alrz** [comment]
@gafter 
> I also find it strange that the nested type's constructor has some parameters that are implicitly declared

Actually, I see the parameter list as property declarations of the record type, not constructor parameters, although they can be mixed together like `class Point(int x : X, int y : Y)` still, if the types are nested, that wouldn't be confusing, because all parameter are declared in one place.

But about refactoring thing you're right; while nested record classes or ADTs *could have* a special meaning. If that feels a bit too magical I think the presence of parameter list (which could be empty like `()`) to declare a record type is not a bit not too magical. The original proposal which suggests a specific keyword like `record class` or my suggestion `case class` could prevent the magic.

**Comment by gafter** [comment]
> still, if the types are nested, that wouldn't be confusing, because all the parameters are declared in one place

"Parameters declared in one place" to me means means between parens and with commas between them. In your proposed alternative they can be arbitrarily far apart, even implicit. The magic to which I object is a parameter list (parameters declared between parens with commas between them) changing its meaning (with implicit additional parameters) when the type is moved into a nested position. Adding keywords like `record` doesn't make that magic any less objectionable.

To be clear, a parameter declaration (on a base class, today) declares precisely one parameter of precisely one constructor of precisely one class. In your proposal it declares an arbitrarily large number of constructor parameters of a number of constructors of a number of types. I prefer a one-to-one correspondence between declarations and things declared, though the record syntax does stretch that slightly to enable the parameter *and* property to be co-declared.

**Comment by alrz** [comment]
To me, the **whole**
```
public class Person(string Name) {
    public class Student(int Grade);
}
```
is the record type declaration, while you argument that record types should be declared individually. In fact, in
```
public abstract sealed class Option<T>() {
    class Some(T Value);
    class None();
}
```
you are declaring the whole `Option<T>` ADT in one `class` because it doesn't make sense to declare them in various files.

For example, in F# both records and discriminated unions are declared in one go, but the limitation is that you can't extend them. While C# is going to make it possible, it introduces a lot more things to be explicitly specified. I did even propose that `public sealed` could be implicit because the whole construct represents one *ADT hierarchy* so some magic along the way could be permitted for the sake of simplicity and yet it doesn't sacrifice any possibility like F# does.

Just imagine what [this](https://github.com/tgjones/mini-c/blob/master/src/MiniC.Compiler/Ast.fs) could have been in C#.

**Comment by gafter** [comment]
@alrz 
> I did even propose that `public sealed` could be implicit

I don't get it. Are you suggesting the "primary constructor" syntax only be allowed for ADTs that form a closed hierarchy? Or would there be some other syntax for record types that are not part of an ADT?

**Comment by alrz** [comment]
@gafter I'm suggesting that access modifier and `sealed` could be implicit for nested types of ADT which are not base class for any other types.
```cs
internal abstract sealed class A() {
  // internal, inherited from A
  abstract class B() {
    // internal, inherited from B
    class C() { 
      // internal sealed, inherited from C
      class D();
    }
  }
}
```
nothing to do with primary constructors. Though implicit base class could work with both ADTs and nested record types.

**Comment by gafter** [comment]
```cs
public abstract sealed class A() {
  // public, inherited from A
  abstract case class B() {
    // public, inherited from B
    case class C() { 
      // public sealed, inherited from C
      case class D();
    }
  }
}
```

Ohhhkay... but what if I didn't want it to be derived? The normal way to not derive from something is to not place it in your base clause... but that's exactly what you have done and given the opposite meaning.

**Comment by alrz** [comment]
> what if I didn't want it to be derived?

remove the `case` modifier?

**Comment by gafter** [comment]
So `case` as a modifier means inherit from the enclosing type and add extra parameters to the constructor and pass them through to the base constructor? That appears to have nothing whatsoever to do with any existing meaning `case` has in C# or English.

**Comment by alrz** [comment]
lol. ok what does a parameter list has to do with generated `is` operator, `With` method and all that jazz? I'm saying that this would be a way to declare a record type hierarchy so the compiler would generate the class structure which is not explicit but it makes sense together. F# do a lot more of this by the way.

**Comment by gafter** [comment]
@alrz My current thinking is that there is no `With` method - we just call the constructor. And there is no generated `operator is` - we just use the properties. Only if those are explicitly declared do we pay any attention to them, and I don't think we actually need a `With` method. As with `struct` types, we need to define some meaning for `Equals` and `GetHashCode` and `ToString`, and we have a reasonable story for those, but there are no strange user-declared parameters for them that could possibly be accessed in user code.

**Comment by alrz** [comment]
@gafter Well, it seems that the design is greatly revamped! Unfortunately, I'm bound to the facts that I'm aware of. Anyway, I don't see any magic here, it's just a more concise syntax for declaring record type hierarchies. That's it.

**Comment by Phrohdoh** [comment]
Why is this proposed?
I assume someone sees it as necessary, but I don't.

If you want to create one object that has values equivalent to others why not be explicit?

I don't see why C# should grow a new construct like this when
`    Person q = new Person(FirstName: "Neal", LastName: p.LastName);`
is perfectly fine and valid.

There are numerous ways to get this result without introducing something new to the language.

**Comment by HaloFour** [comment]
@Phrohdoh

If `Person` had a lot of properties that would become verbose boilerplate very quickly.

**Comment by gafter** [comment]
@Phrohdoh The Roslyn syntax trees are auto-generated in part so we can add lots of "With" methods. Adding this feature to records means we would not need to.

**Comment by MgSam** [comment]
@Phrohdoh Try doing that for a type that has 20 properties. And make sure you don't forget any, or else you'll have a super-subtle bug that you'll have to track down at runtime.

**Comment by alrz** [comment]
I think the point is to preserve immutability while you're altering properties' values, which, therefore, without a dedicated language construct, becomes cumbersome and error prone and eventually misses the point.

**Comment by kintar0** [comment]
The with-expression will come in handy especially when you are dealing with composed records. Consider the following records:
```csharp
public class HumanName(string First, string Last)
public class HumanAddress(string Street, string City, string State)
public class Person(HumanName Name, HumanAddress Address)

var name = new HumanName( "John" , "Smith" )
var address = new HumanAddress( "A Street" , "Los Angeles" , "California" )
var john = new Person(name, address) 
```
Will it be possible to write
```csharp
var movedJohn = john with { Name.Last = "Doe", Address.Street = "Another Street" }
```
to change the properties in deeper levels? 

When working with immutable classes, changing properties that are not on the 'first level' were one of my main reasons to switch back to mutable classes. The number of With.... methods you need to provide grows pretty fast, especially when you think about adding them on every level.

**Comment by gafter** [comment]
@kintar0 As currently specified, you would have to

```cs
var movedJohn = john with {
    Name = john.Name with { Last = "Doe" },
    Address = john.Address with { Street = "Another Street" } }
```

**Comment by alrz** [comment]
Since all of the parameters are optional, calling the `With` method without args behaves like `Clone`,
```cs
var clone = obj.With(); // weird
```


PS: This issue is seriously outdated.

**Comment by bbarry** [comment]
What if there were simply pairs of optional parameters required on the wither:

```
public partial class Point
{
    public virtual Point With(
        [Wither("wX")] int X = 0, bool wX = false, 
        [Wither("wY")] int Y = 0, bool wY = false
        ) => new Point(xX ? X : this.X, wY ? Y : this.Y);
}
```

the syntax (C#Next):

```
var p2 = p1 with { X = 0 };
```

compiles the same as (C#6):

```
var p2 = p1.With(wX: true, X: 0);
```

This pattern could be done with extension methods:

```
public static class PointExtensions
{
    public static Point With(this Point @this,
        [Wither("wX")] int X = 0, bool wX = false, 
        [Wither("wY")] int Y = 0, bool wY = false
        ) => new Point(xX ? X : this.X, wY ? Y : this.Y);
}
```

It avoids decapitation (as much as method calls do today):

```
public partial class LimitedPoint : Point
{
    public override Point With(
        [Wither("wX")] int X = 0, bool wX = false, 
        [Wither("wY")] int Y = 0, bool wY = false
        ) => new LimitedPoint (xX ? X : this.X, wY ? Y : this.Y);
}
```

And it doesn't require any new syntax on the declaration side (though a syntax might be useful; it could be done separately). Nor does it require a new `Optional<T>` type.

**Comment by gafter** [comment]
We are not likely to do this. However, @MadsTorgersen has volunteered to champion "pattern-based `with` expressions"; see https://github.com/dotnet/csharplang/issues/162 and the records proposal at https://github.com/dotnet/csharplang/blob/master/proposals/records.md .
