### ISSUE TITLE
embedded using declaration doesn't work for CryptoStream/StreamWriter

### ISSUE THREAD

**Issue by dighexode** [dotnet/roslyn#51738]
**Version Used**: .net core 3.1, webapi

**Steps to Reproduce**:

1. When I was using traditional "embedded using statement", the code below works well. It encrypted the plainText variable successfully.
`

           string plainText = "123";
            byte[] encrypted = null;
            byte[][] keys = KeyHelper.GetHashKeys("230DK49FK59EK");
            var aesAlg = new AesCryptoServiceProvider { Key = keys[0], IV = keys[1] };

            // Create an encryptor to perform the stream transform.
            var encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

            // Create the streams used for encryption.
            using (var msEncrypt = new MemoryStream())
            {
                using (var csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                {
                    using (var swEncrypt = new StreamWriter(csEncrypt))
                    {
                        //Write all data to the stream.
                        swEncrypt.Write(plainText);
                    }

                    encrypted = msEncrypt.ToArray();
                }
            }

            // Return the encrypted bytes from the memory stream.
            return Convert.ToBase64String(encrypted);`
2. When I change all the 3 "using statement" to "using declarations", it doesn't work, return empty string.
`

           string plainText = "123";
            byte[] encrypted = null;
            byte[][] keys = KeyHelper.GetHashKeys("230DK49FK59EK");
            var aesAlg = new AesCryptoServiceProvider { Key = keys[0], IV = keys[1] };

            // Create an encryptor to perform the stream transform.
            var encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

            // Create the streams used for encryption.
            using var msEncrypt = new MemoryStream();
            using var csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write);
            using var swEncrypt = new StreamWriter(csEncrypt);
            //Write all data to the stream.
            swEncrypt.Write(plainText);

            encrypted = msEncrypt.ToArray();

            // Return the encrypted bytes from the memory stream.
            return Convert.ToBase64String(encrypted);`
3. For the 2nd code, if I change the 3rd "using declaration" to be "using statement", it works.
`

           string plainText = "123";
            byte[] encrypted = null;
            byte[][] keys = KeyHelper.GetHashKeys("230DK49FK59EK");
            var aesAlg = new AesCryptoServiceProvider { Key = keys[0], IV = keys[1] };

            // Create an encryptor to perform the stream transform.
            var encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

            // Create the streams used for encryption.
            using var msEncrypt = new MemoryStream();
            using var csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write);
            using (var swEncrypt = new StreamWriter(csEncrypt))
            {
                //Write all data to the stream.
                swEncrypt.Write(plainText);
            }

            encrypted = msEncrypt.ToArray();

            // Return the encrypted bytes from the memory stream.
            return Convert.ToBase64String(encrypted);`
4. Here's the GetHashKeys function I was using:
`

           var result = new byte[2][];
            var enc = Encoding.UTF8;

            using (SHA256 sha2 = new SHA256CryptoServiceProvider())
            {
                var rawKey = enc.GetBytes(key);
                var rawIV = enc.GetBytes(key);

                var hashKey = sha2.ComputeHash(rawKey);
                var hashIV = sha2.ComputeHash(rawIV);

                Array.Resize(ref hashIV, 16);

                result[0] = hashKey;
                result[1] = hashIV;
            }

            return result;`
**Expected Behavior**: 2nd code should have same behavior with 1st code.

**Actual Behavior**: 2nd code is returning empty string.

Can you please tell me why? I'm not sure if this is a bug. And I'm not sure if I should post the question in here or in dotnet/runtime, because it might not be a compiler issue, or StreamWriter's issue. If I posted in wrong board, please tell me.

**Comment by jaredpar** [comment]
Thanks for taking the time to file but this behavior is "By Design".  The key is understanding the effects that happen before the following statement is executed 

```c#
  encrypted = msEncrypt.ToArray();
```

In the original code sample the following is before it 

```c#
             using (var swEncrypt = new StreamWriter(csEncrypt))
             {
                 //Write all data to the stream.
                 swEncrypt.Write(plainText);
             }
```

This means that `swEncryt` is disposed before the `ToArray` call occurs. Part of the `Dispose` of this member flushes the underlying `Stream` and hence the data is fully present in `msEncrypt`. 

Now let's see the second example 

```c#
     using var swEncrypt = new StreamWriter(csEncrypt);
     //Write all data to the stream.
     swEncrypt.Write(plainText);
```

This is a `using declaration` and hence the `Dispose` does not happen until the end of the scope in which the variable was declared. That means it happens much later than the `ToArray` call so the `Flush` hasn't happened and the underlying `Stream` is empty here.
