### ISSUE TITLE
Proposal: Forward reference for local functions

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5173]
We would like to change the definite assignment rules for *local functions* (#259 and #2930) to allow a local function to be invoked before its point of declaration if all variables that are read before being assigned in the local function are definitely assigned at the point of invocation.

This would make it possible to have two mutually recursive local functions declared side-by-side.

We would also remove the requirement that a local function declaration statement be *reachable*, as executing that declaration now has no meaning.

**Comment by gafter** [comment]
This and #5168 have some unfortunate complicated interactions. It is much simpler to do one or the other.

**Comment by orthoxerox** [comment]
I prefer this one to be implemented, since it will allow me to declare local functions after the return statement. It's a big pita in PL/SQL, where the arguments and the function body can be separated by several screens worth of nested functions.

**Comment by jaredpar** [comment]
This is now implemented.
