### ISSUE TITLE
[Proposal] IGenericSymbol interface; generalize INamedTypeSymbol and IMethodSymbol generic functionality

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#51745]
There is currently no method to reliably get the arity, type parameters/arguments and original generic symbol of a symbol without explicitly checking for whether it's `INamedTypeSymbol` or `IMethodSymbol`. This defeats the purpose of the API; which should be properly abstracted.

In my case at least, where my analyzer is about generic types and methods, I've had to make extensions to provide that capability.

# Proposed API

New interface:
```csharp
interface IGenericSymbol : ISymbol
{
    bool IsGeneric { get; }
    int Arity { get; }
    ImmutableArray<ITypeParameterSymbol> TypeParameters { get; }
    ImmutableArray<ITypeSymbol> TypeArguments { get; }
    IGenericSymbol ConstructedFrom { get; }
}
```

Changes to existing APIs:
```csharp
interface INamedTypeSymbol : IGenericSymbol, ITypeSymbol
{
    // Everything else remains the same
}
```
```csharp
interface IMethodSymbol : IGenericSymbol
{
    // Everything else remains the same
}
```

Likewise this could offer the ability to add a `DeclaringSymbol` property in `ITypeParameterSymbol` that returns a `IGenericSymbol`. The API would look like this:

```csharp
interface ITypeParameterSymbol : // ...
{
    IGenericSymbol DeclaringSymbol { get; }
    // Everything else remains the same
}
```

Note: the `DeclaringSymbol` could also be named `DeclaringGenericSymbol`.

**Comment by CyrusNajmabadi** [comment]
We don't generally model things in Roslyn with multi-inheritance.

**Comment by AlFasGD** [comment]
The reason being I assume performance during compilation?

Also, this new API only has the drawback to use multi-inheritance in only one type, `INamedTypeSymbol`.

**Comment by jaredpar** [comment]
Thanks for the suggestion but at this time we don't think it's the right path forward: 

1. We generally don't model with multi-inheritance here 
2. The API can't reasonably cover every possible use case but instead focuses to cover the major ones and ensure the proper building blocks are in place for the rest. 
3. This interface would need conditional implementation (why should a non-generic symbol have an implementation for `IGenericSymbol`?).
