### ISSUE TITLE
Three errors when using switch pattern matching inside multi-valued return statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51744]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Three-errors-when-using-switch-pattern-m/1359273)._

---
[severity:It's more difficult to complete my work]
I'm trying to use the new switch statement pattern-matching from inside a method that return multiple value via the new Tuple construction. Whenever I type "switch {" I got the following error:

>'CSharpNameTupleElementCodeRefactoringProvider' encountered an error and has been disabled

along with

>'CSharpConvertTupleToStructCodeRefactoringProvider' encountered an error and has been disabled

and

>'IntroduceVariableCodeRefactoringProvider' encountered an error and has been disabled

This is the code that causes the issue:

```
public (double, ResponseCode, string) Classify(string[] statements)
        {
            double prediction;
            Uri? uri;
            (prediction, uri) = IsUriSentizationCommand(statements);

return (prediction, prediction switch { <= .24 => ResponseCode.NotIdentified, >.24 and <= .50 => ResponseCode.PartiallyIdentified, _ => ResponseCode.Identified }, "");
        }
```

---
#### Feedback Bot on 3/7/2021, 06:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
@cston Should this be closed?
