### ISSUE TITLE
vb.net auto-format wrongfully removes continuation underscores

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51743]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vbnet-auto-format-wrongfully-removes-co/1357571)._

---
[severity:It's more difficult to complete my work]
As soon as I save a file with the following code

```
Dim probing = cfg_cur _
         . <configuration> _
         . <runtime> _
         . Descendants(XNamespace.Get("urn:schemas-microsoft-com:asm.v1") + "probing") _
         . FirstOrDefault()
```

It becomes this.

```
Dim probing = cfg_cur _
	. <configuration>
. <runtime>
. Descendants(XNamespace.Get("urn:schemas-microsoft-com:asm.v1") + "probing") _
	. FirstOrDefault()
```

Notice how there are now missing underscores. Also, the compiler now reports `error BC30157: Leading '.' or '!' can only appear inside a 'With' statement.`

---
#### Feedback Bot on 3/4/2021, 06:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to change these experiences.
