### ISSUE TITLE
Completion don't provide property target in record parameter 

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#51756]
**Version Used**: 
VS 16.9.0

**Steps to Reproduce**:

```csharp
public record R([/*here*/] string M);

// modifying attribute target:
public record R([/*here*/ SomeAttribute] string M);

// adding attribute:
public record R([/*here*/ string M);
```

**Expected Behavior**:
Contextual keyword `property` provided.

**Actual Behavior**:
No contextual keyword `property` provided.

**Comment by Youssef1313** [comment]
Thanks for reporting @huoyaoyuan. I'll open a PR to address this.
