### ISSUE TITLE
GetDocumentationCommentXml does return nothing

### ISSUE THREAD

**Issue by andreas-soroko** [dotnet/roslyn#51769]
Hey, 

i am not 100% sure it this is the correct repo, so if its wrong - sorry.
i wrote a source generator that generates some classes and interfaces based on a base interface and wanted also to take over the documentation.
that is working fine if i use project references, but when i have a nuget reference not. example below. 

```csharp
/// Assembly: Service.Interface

[MetaInformation(Version = 1)]
public interface IApi 
{
    /// <summary>
    /// Test method with a comment
    /// </summary>
    /// <param name="id">param id comment</param>
    /// <param name="name">param name comment</param>
    /// <returns>return comment</returns>
    /// <exception cref="Exception">exception comment</exception>
    Task ExampleCall(Guid id, string name);
}
```

```csharp
/// Assembly: Service

[GenerateSecureFacade]
public interface IApiFacade : IApi
{
}
```
so, did i miss something? 
thank you in advance for your help!

Note: 
- `GenerateSecureFacade`: generates a class with some special validation
- this works if i am using project references
   - `<ProjectReference Include="...." OutputItemType="Analyzer" ReferenceOutputAssembly="false" />`
- if i am using a nuget package (build & packed as analyzer)
   - generation works but `GetDocumentationCommentXml()` returns nothing (xml documentation enabled and included, goto definition on `IApi` shows me the documentation)

**Version Used**: 
Microsoft.CodeAnalysis.Analyzers: 3.3.2
Microsoft.CodeAnalysis.CSharp.Workspaces: 3.8.0

**Expected Behavior**:
GetDocumentationCommentXml returns the associated documentation

**Actual Behavior**:
GetDocumentationCommentXml returns empty

**Comment by svick** [comment]
Can you share a small solution that reproduces the issue?

**Comment by andreas-soroko** [comment]
Contains 2 interfaces
- `NotWorkingExample`
- `WorkingExample`

`WorkingExample` inherits just an interfaces from a project reference
`NotWorkingExample` inherits from `ILoggerProvider` ( xml documentation was copied per target before build - see csproj)

output:
(yep, not formatted but i hope for demo purpose okay ;) )

```csharp
namespace Test 
{
    public interface INewWorkingExample 
    {
        
        /* <member name="M:Test.Interfaces.IApi.Example(System.Guid)">
    <summary>
    example description
    </summary>
    <param name="id">example param</param>
    <returns>example return description</returns>
</member>
 */
        System.Threading.Tasks.Task Example(System.Guid id);

    }
}
```

```csharp
namespace Test 
{
    public interface INewNotWorkingExample 
    {
        
        // no documentation found
        Microsoft.Extensions.Logging.ILogger CreateLogger(string categoryName);
        
        // no documentation found
        void Dispose();

    }
}
```

and yes, the xml file is there
<img width="491" alt="image" src="https://user-images.githubusercontent.com/47380084/110642156-09e40680-81b3-11eb-8e16-265b5bbe6f9c.png">

( in my personal project is the documentation file directly next to dll, don't no if its matter ) 

[SourceGeneratorExample.zip](https://github.com/dotnet/roslyn/files/6116426/SourceGeneratorExample.zip)

**Comment by andreas-soroko** [comment]
just created a workaround ( its working for me ) 

```csharp
var baseDocu = symbol.GetDocumentationCommentXml();
if (!string.IsNullOrWhiteSpace(baseDocu)) { return baseDocu; }

var provider = _xmlReaderProviders.GetOrAdd(
    symbol.ContainingAssembly,
    assembly =>
    {
        var metadataReference = compilation.GetMetadataReference(assembly);
        if (metadataReference is null) { return null; }

        var propInfo = _metadataFilePathGetter.GetOrAdd(metadataReference.GetType(), reference => reference.GetProperty("FilePath"));
        var path = propInfo?.GetValue(metadataReference)?.ToString()?.Replace(".dll", ".xml");

        if (string.IsNullOrEmpty(path)) { return null; }
        if (!File.Exists(path)) { return null; }

        return new XmlReaderProvider(path);
    }
);
```

just modified the original one a bit
```csharp
public class XmlReaderProvider
{
    private readonly string _filePath;
    private static readonly XmlReaderSettings _xmlSettings = new()
    {
        DtdProcessing = DtdProcessing.Prohibit,
    };
    private Dictionary<string, string> _docComments;

    public XmlReaderProvider(string filePath)

    {
        _filePath = filePath;
    }

    private Stream GetSourceStream() =>
        new FileStream(_filePath, FileMode.Open, FileAccess.Read);

    private XDocument GetXDocument()
    {
        using var stream = GetSourceStream();
        using var xmlReader = XmlReader.Create(stream, _xmlSettings);
        return XDocument.Load(xmlReader);
    }

    public string GetDocumentationForSymbol(string documentationMemberId)
    {
        if (_docComments == null)
        {
            try
            {
                var comments = new Dictionary<string, string>();

                var doc = GetXDocument();
                foreach (var e in doc.Descendants("member"))
                {
                    if (e.Attribute("name") != null)
                    {
                        using var reader = e.CreateReader();
                        reader.MoveToContent();
                        comments[e.Attribute("name").Value] = reader.ReadInnerXml();
                    }
                }

                _docComments = comments;
            }
            catch (Exception)
            {
                _docComments = new Dictionary<string, string>();
            }
        }

        return _docComments.TryGetValue(documentationMemberId, out var docComment) ? docComment : "";
    }
}
```

**Comment by jaredpar** [comment]
> GetDocumentationCommentXml returns empty

This is the intended behavior during compilation for any symbols that come from metadata. The compiler uses the `NullDocumentationProvider` when creating `MetadataImageReference`. That is because the XML doc files are explicitly not a tracked input to compilation and hence cannot be used by the compiler, analyzers or source generators.  If you want to use these files then you need to be passing them as additional files to the compilation and parsing them that way.

>     private Stream GetSourceStream() => new FileStream(_filePath, FileMode.Open, FileAccess.Read);

Please do not do explicit I/O in a source generator. This violates all of our rules about how compilations should work and can have very negative impacts on the IDE. 

At some point in the future we may end up banning source generators that attempt to do manual I/O.

**Comment by andreas-soroko** [comment]
hey @jaredpar,

thank you for your answer.

> That is because the XML doc files are explicitly not a tracked input to compilation and hence cannot be used by the compiler, analyzers or source generators.

as you can see, it could be used in a source generator when the file would be loaded. so the argument is not really valid.

i tried it by my self in a unit test with 

```csharp
var externalAssembly = typeof(IMyExternalInterface).GetTypeInfo().Assembly;
MetadataReference.CreateFromFile(
    externalAssembly.Location,
    documentation: XmlDocumentationProvider.CreateFromFile(externalAssembly.Location.Replace(".dll", ".xml"))
),
```
an everything is working fine, so i don't get it, why this behaviour is not wanted.

> If you want to use these files then you need to be passing them as additional files to the compilation and parsing them that way.

great, but they do also loading the files with a FileStream... so....
[AdditionalTextFile.cs](https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/Core/Portable/AdditionalTextFile.cs#L39)
[CommonCompiler.cs](https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L381)

i want to use this in over 20 projects, so this would be a kind of noise to add the additional files in every project.
so i just don't get it, the files are there, they just need to be loaded with 1 additional line of code

**Comment by jaredpar** [comment]
> as you can see, it could be used in a source generator when the file would be loaded. so the argument is not really valid.

Disagree. My statement is a correct analysis of how the compilation process works. Documentation comment files are not tracked inputs into the compiler. Any attempt to read them from disk is going to violate assumptions of the compiler + MSBuild and produce undefined results. 

> i tried it by my self in a unit test with

Yes because you are directly doing IO in the generator which is violating principals of our compilation. The `Compilation` type, and all the anaylzers and generators loaded into it, explicitly do not perform IO as a part of their operation. The IO is all done ahead of time, moved into immutable data structures and those are what is used in the compilation. 

> an everything is working fine, so i don't get it, why this behaviour is not wanted.

A core tenant of `Compilation`, and really most of the compiler data structures, is that they are both immutable and I/O free. The hosts take hard dependencies on this being true. For example the IDE host assumes it can call into the compiler APIs on UI threads and not have IO take place. Generators / analyzers which attempt to do their own IO explicitly break this model. 

Further you are violating basic build principals here. The XML docs are **not** tracked as inputs to the compilation by default. Hence if a user changes an XML doc then rebuild is not guaranteed to take place as MSBuild doesn't consider it an input to build. That means builds including this pattern are fundamentally less reliable than ones that do not. 

> i want to use this in over 20 projects, so this would be a kind of noise to add the additional files in every project.
so i just don't get it, the files are there, they just need to be loaded with 1 additional line of code

I've elaborated on the reasons here and happy to explain further. 

I do want to re-iterate we have strongly considered hard blocking analyzers / generators that do custom I/O because it violates our model so strongly and potentially introduces major performance problems to VS.

**Comment by sharwell** [comment]
> I do want to re-iterate we have strongly considered hard blocking analyzers / generators that do custom I/O because it violates our model so strongly and potentially introduces major performance problems to VS.

Going one step further, I'll add that the only reason we don't currently block them is we don't have a good way to do so without a performance penalty. If/when someone presents an approach which allows us to block file I/O in analyzer callbacks without making analyzers slower, it would be applied in short order.

**Comment by andreas-soroko** [comment]
Thanks for the clarification and your patience! 

> Yes because you are directly doing IO in the generator which is violating principals of our compilation.

Not directly, when the xml is given to the `MetadataReference.CreateFromFile` i can just use `GetDocumentationCommentXml`. Unless that falls within the scope for you too. 

But I understood and will look for another solution.

**Comment by sharwell** [comment]
`MetadataReference.CreateFromFile` would fall into the category of unexpected file I/O outside the compiler's view, which can have undefined results on the invoking compilation process.

**Comment by jaredpar** [comment]
> MetadataReference.CreateFromFile would fall into the category of unexpected file I/O outside the compiler's view, which can have undefined results on the invoking compilation process.

Exactly. It is I/O that is not tracked by the compiler or MSBuild and that violates the basic assumptions outlined above which can in turn impact correctness.

**Comment by andreas-soroko** [comment]
Does some of you have maybe an idea regarding to this: 

I am now using `AdditionalFiles` the generated the classes and the comments are there, this is fine.
But I have now a really strange behaviour and could find any solution for. 

On the 1. Rebuild _(bin folder deleted)_ on the project _(who is using the SourceGenerator with `GenerateDocumentationFile` true)_ the xml file does NOT contain the comments (but the class does) from the generated class, I have to rebuild a second time and then the comments appears. 

With my (I/O based) solution, it works every time on the first try. I didn't get i, some ideas what I am doing wrong?
