### ISSUE TITLE
Inconsistent C# tuple formatting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51777]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inconsistent-C-tuple-formatting/1361135)._

---
[severity:It bothers me. A fix would be nice]
Consider the following auto-formatted C# code:

```
var foo = (false, false) switch // no bonus space here
{
    (false, false ) => 0, // bonus space here
    (true, false ) => 1,  // bonus space here
    _ => 2
};
```

Visual Studio incorrectly (as far as I know) adds spaces before the closing parenthesis for the tuples inside the switch expression, but not for the tuple being switched.

---
#### Feedback Bot on 3/8/2021, 06:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
I can't reproduce the behavior described here.

**Comment by CyrusNajmabadi** [comment]
Can't repro either.
