### ISSUE TITLE
The comments in AnalysisContext do not match interface methods

### ISSUE THREAD

**Issue by neeraj9** [dotnet/roslyn#51771]
It is not clear (from comment and methods available), whether "completion of parsing a code document" maps to compilation start or anything else which is missing. I am new to this ecosystem so it was not very obvious to me at least in the beginning.

[1] https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L281

**Comment by mavasani** [comment]
Hi @neeraj9, `CompilationStartAction` is guaranteed to the very first analyzer action callback, if analyzer registers a callback for compilation start. The comment on the action mentions that analyzer can register other nested actions on the compilation start analysis context. For example, analyzer can invoke `compilationStartAnalysisContext.RegisterSyntaxTreeAction(...)` to get callbacks for each parsed syntax tree/code document. You can find more details over here: https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Analyzer%20Actions%20Semantics.md
