### ISSUE TITLE
Getting a message that a new .editorconfig was found and asking if I want to add it to the solution, but i already have one as part of the solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51785]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Getting-a-message-that-a-new-editorconf/1321172)._

---
[severity:It bothers me. A fix would be nice]
I edited a csproj file to add some missing package references and other project items and after saving I got the gold bar asking about the editorconfig that was just "found" and did i want to add it.  I already have an editorconfig as part of the solution.  See screenshot

---
#### Feedback Bot on 1/26/2021, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dylan Zhu [MSFT] on 1/28/2021, 01:32 AM: 

<p>Hi  Andrew Stanton, is the new one same with the existing one? You can backup the existing one, then click "Yes", and check it.</p>

#### Andrew Stanton on 1/28/2021, 09:18 AM: 

<p>I dont know what you mean.  VS should not be asking me the question in the first place because there is already an editorconfig in the repo root, adjacent to the sln file, and is referenced in the solution as an existing item.</p>

#### Feedback Bot on 1/31/2021, 11:25 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/55382
