### ISSUE TITLE
IntelliSense (partially) not working for SG generated files

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#51799]
**Version Used**: VS 16.10 Preview 1

**Steps to Reproduce**:

1. Clone [ComputeSharp](https://github.com/Sergio0694/ComputeSharp)
2. Open the solution, build `ComputeSharp.Sample.Local` (or any other sample except the `.NuGet` one)
3. Expand Dependencies > Analyzers > ComputeSharp.SourceGenerators
4. Look at any of the generated files from any of the generators: IntelliSense is disabled for most types

**Expected Behavior**:
IntelliSense should work for all types as usual.

**Actual Behavior**:
IntelliSense is not running except for a few types from the BCL.
Most types are displayed in white, CTRL + click doesn't work, hover doesn't display info, etc.
Some methods are displayed in white too instead of yellow, and IntelliSense is off for them too.

**Screenshot**:
![image](https://user-images.githubusercontent.com/10199417/110831327-69691180-829a-11eb-9188-47354503c1fc.png)

**Comment by huoyaoyuan** [comment]
The generated file is categorized as Misc file in IDE. It should be categorized under the project.

**Comment by jasonmalinowski** [comment]
Yep, dupe of #50676. (And I'm literally working on fixing this right now, so the fix is coming!)

**Comment by Sergio0694** [comment]
Oh, whoops, my bad - I did check for similar issues but I just missed that one! Glad to hear a fix is already in the works, that's great! I'll close this issue then since it's a duplicate, thanks! 😄

**Comment by jasonmalinowski** [comment]
@Sergio0694: not a problem! And my personal motto is I'm always happy to close duplicates rather than have somebody not file a bug because they thought it was a known one. I just feel bad for the time you had to waste writing up a good bug report... :frowning:

**Comment by sharwell** [comment]
Duplicate of #50676
