### ISSUE TITLE
Log functions for VSTelemetryLogger do not report telemetry

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#51790]
https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/Telemetry/VSTelemetryLogger.cs Log function currently doesn't upload telemetry for all calls to Log, instead it relies on the message being passed as a dictionary to add telemetry. This is misleading for log calls, we should figure out a way to handle this or expose specific log levels. 

cc: @tmat  

```csharp
public void Log(FunctionId functionId, LogMessage logMessage)
{
    // This check is false for all Log(FunctionId, string) calls
    if (!(logMessage is KeyValueLogMessage kvLogMessage))
    {
        return;
    }

    try
    {
        // guard us from exception thrown by telemetry
        if (!kvLogMessage.ContainsProperty)
        {
            _session.PostEvent(functionId.GetEventName());
            return;
        }

        var telemetryEvent = CreateTelemetryEvent(functionId, kvLogMessage);
        _session.PostEvent(telemetryEvent);
    }
    catch
    {
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, it needs to go to a dev/milestone to be done.
