### ISSUE TITLE
FullyQualifyTests.TestOrdering does not pass

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#51817]
This test was missing a `Fact` attribute. When added, the test was failing.

https://github.com/dotnet/roslyn/blob/27913e0ff1564c82672aaff25a7621e882fa2386/src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb#L56-L83

**Comment by Youssef1313** [comment]
Probably due to missing span here?

https://github.com/dotnet/roslyn/blob/27913e0ff1564c82672aaff25a7621e882fa2386/src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb#L74
