### ISSUE TITLE
Devirtualize interfaces where it can be proven to be safe.

### ISSUE THREAD

**Issue by redknightlois** [dotnet/roslyn#5181]
This is a branch of the discussion happening at https://github.com/dotnet/coreclr/issues/1532 . The issue there originally aimed at the JIT devirtualization of generics calls but there are potential optimizations that can happen at the compiler level. 

Using a similar example, let's say that you have the following code:
```
ICall instance = new ConcreteClass();
instance.Execute();
```
If the instance is not assigned elsewhere a different compatible type different than ConcreteClass via
- a parent class return on method
- assignment via construction of different type.
- assignment via return value of method.
Then it can be proven safe to just rewrite it as:
```
ConcreteClass instance = new ConcreteClass();
instance.Execute();
```
That will ensure the most efficient call happens on each call site.

While it can be argued that is what var is for, that approach can also work for sections of the code as the compiler can reason and force the proper call when such things happen.

**Comment by mikedn** [comment]
I don't think this optimization belongs in the C# compiler because it would be quite a bit more limited than what the JIT can do. For example, one legitimate reason to write such code is to access an explicitly implemented interface member but in that case the C# compiler can't perform the optimization because the member isn't accessible.

**Comment by redknightlois** [comment]
Not entirely true. The compiler could reason about the flow of execution at levels the JIT will never be able to. Therefore, it can hint the JIT to do a better local devirtualization job too. The question that remains is how pervasive is this type of optimization in real-life projects ( a required analysis before  consider to put this feature request on the backlog ).

**Comment by mikedn** [comment]
> The compiler could reason about the flow of execution at levels the JIT will never be able to. 

Why? Because the C# compiler has more time at its disposal than the JIT compiler?

>  Therefore, it can hint the JIT to do a better local devirtualization job too.

How? Presumably you suggest extending the IL with hints or other features?

**Comment by redknightlois** [comment]
The C# will have far more information (and can be argued more time too). It's easy to see when you focus on global optimizations. 

Example: 
A private readonly interface which whose instance is constructed by a method call which always return the same concrete type. No reason why the compiler wouldnt substitute the interface for the concrete type if it is safe globally (inside the class). 

That would be deemed very difficult to be done at the JIT level without doing global analysis. On the other hand, the compiler emitting a concrete class will allow the JIT to write far more efficient code. At the cost of essentially zero for the JIT.

**Comment by mikedn** [comment]
> The C# compiler will have far more information (and can be argued more time too).

OK, so this is about having time after all. The C# compiler actually has less information than the JIT compiler as it cannot see code outside the compiled assembly. The JIT compiler can, the only thing that prevents it from doing such global analysis is the lack of time.

**Comment by redknightlois** [comment]
Exactly, the compiler may have less information than the JIT but in the practical sense --as you noted--  the JIT is not allowed the time to do such advanced analysis anyways. Which for all practical purposes implies that the C# compiler have more information.

**Comment by agocke** [comment]
This is the kind of thing I would do in .NET Native, not in the C# compiler.

Also, it's probably not safe due to .NET Remoting.

**Comment by gafter** [comment]
We are unlikely to do this in the forseeable future. Any effort to devirtualize calls would be focused on the jit.
