### ISSUE TITLE
VS grey out the whole expression when using extra parentheses

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51813]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-grey-out-the-whole-expression-when-us/1354230)._

---
When having extra parentheses, the whole expression is greyed out. This usually represent useless code (useless usings, useless suppressions, etc.).
In this case, I think that only the extra parentheses should be greyed out instead of the whole expression.

![image](https://user-images.githubusercontent.com/1408396/111395270-aefe5380-8679-11eb-86e5-92cdbe008270.png)

---
#### Feedback Bot on 3/2/2021, 10:45 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This does not repro for me.  We only fade the outer parens.  We should never fade the inner parens.

![image](https://user-images.githubusercontent.com/4564579/153487262-aa31e7e8-52b1-4454-b365-8148c64f1d7f.png)
