### ISSUE TITLE
Editor suggestion: if i type "Container.Resolve<IMyInterface(" autocorrect/complete it as "Container.Resolve<IMyInterface>("

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51814]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Editor-suggestion:-if-i-type-Container/1340733)._

---
Just like the title says.
There already are some cases where the editor notice you typed ";" and then jumps the cursor at the end of a statement instead of typing the ; exactly where the cursor was.

I often find myself in writing code that uses generics and it would be nice if the editor notices that a "(" character has no place in a generic parameter type list.

it would be handy if I could type:
  `var x = new List<string(`
and have the editor immediately correct it as:
  `var x = new List<string>( | ); `   

_(i am using the "|" character to show where I would like the cursor to be placed after  code completion being performed)_

another handy thing would be

`var x = new List<string;`

being autocorrected as

`var x = new List<string>();|`

Thank you for your time

---
#### Feedback Bot on 2/17/2021, 11:17 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment]
cc @Cosifne

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
