### ISSUE TITLE
Documentation comments should be validated at compile time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Documentation-comments-should-be-validat/1348982)._

---
[severity:It bothers me. A fix would be nice]
Intellisense is now supported for documentation comments ///. However, there is no way to validate these at compile time.
It would be nice if we could make the compile fail if a referenced property / parameter / exception etc was renamed / removed etc.

---
#### Feedback Bot on 2/25/2021, 00:54 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by huoyaoyuan** [comment]
It will be validated only when 'generate documentation file' is turned on.
