### ISSUE TITLE
C# Editor, Convert to Hex refactoring unexpected limitations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51821]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Editor-Convert-to-Hex-refactoring-un/1353082)._

---
If you have a list of f.ex. decimal integers, you should be able to transform them en-masse using both multi-select and box-select, both by having the cursors/carets either just touch or be inside the numbers (just like it works today for one-at-a-time) and having selections of the whole numbers (again, just like it works today for one-at-a-time), in addition to the current behavior of doing it one-by-one.

Rationale:
Since Visual Studio is so horribly, horribly slow, doing this one-by-one can easily take five-ten seconds _per entry_. If you have a tiny list of even just eight entries, this can balloon to rage-inducing levels of frustration just waiting for that ¤#&%#% refactoring list to pop up.

Workaround:
We have started throwing Visual Stuido out the window for even simple text-transform editing tasks like this, running a separate Notepad++ instance and then copy & paste text back and forth.

Surely it can't be Microsofts intention to provide - what should be the worlds premiere Windows code IDE - something so inherently primitive and dysfunctional as this. Can it?

---
#### Feedback Bot on 9/28/2019, 09:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/30/2019, 00:21 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/31/2019, 07:15 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/2/2021, 00:49 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment]
> Since Visual Studio is so horribly, horribly slow

I suggest that you try to disable CodeLens and see if it gets any better.

**Comment by CyrusNajmabadi** [comment]
Please file a trace when VS is slow using the instructions here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md 

That way we can figure out hte perf issue.

**Comment by jinujoseph** [comment]
In design meeting to discuss how to apply multiple refactoring.
Related to #32461
