### ISSUE TITLE
EnvDTE.CodeProperty.Access throws an exception for VB properties without explicit access modifier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51840]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EnvDTECodePropertyAccess-throws-an-exc/1365115)._

---
I'm enumerating the properties of a class with DTE and getting their accessibility with `CodeProperty.Access`. However, this property throws a COMException for a Visual Basic property that has no explicit access modifier and is not auto-implemented.
Let's have the following VB class:

```
Public Class TestClass

Property Prop1 As String
        Get
        End Get
        Set(value As String)
        End Set
    End Property

Property Prop2 As String

Public Property Prop3 As String
        Get
        End Get
        Set(value As String)
        End Set
    End Property

End Class
```

Getting CodeProperty.Access for Prop1 will throw the exception. On the other hand, Prop2 which is auto-implemented, correctly returns `vsCMAccess.vsCMAccessPublic`. Similarly Prop3 is OK because the Public is explicitly defined.
The expected behavior for Prop1 is to return `vsCMAccessPublic` or `vsCMAccessDefault`.

---
#### Feedback Bot on 3/10/2021, 11:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@jasonmalinowski do you know what the expected behavior here is?

**Comment by jasonmalinowski** [comment]
@sharwell Whatever Dev12 did.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to touch codemodel.
