### ISSUE TITLE
ctrl+shift+down stops at ++

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ctrlshiftdown-stops-at-/1367153)._

---
I use keyboard shortcuts ctrl+shift+down and ctrl+shift+up to search all occurrences of a variable in one C# file. The problem is that it does not work at increments or decrements. 
Example:
```
int count;
count=1;
count++;
count=2;
count--;
count=3;
```
It works if I am pressing the keyboard shortcut quickly. But it does not work if I am doing it more slowly. If I wait 1 second before pressing the shortcut, then it stops at ++ and selects some icon on the bottom tool bar.

---
#### Feedback Bot on 3/11/2021, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
It looks like the the associativity of the highlight references feature only looks at the caret _position_. It might be better to prefer left association if the caret position is at the end of a non-empty selection.
