### ISSUE TITLE
Build failed, MSB6006: csc.dll exited with code 139 on Ubuntu ARM64

### ISSUE THREAD

**Issue by Frederisk** [dotnet/roslyn#51861]
**Version Info**: 

dotnet:
```
# dotnet --version
6.0.100-preview.2.21155.3
```

from: https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.2-linux-arm64-alpine-binaries

system:
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
# uname -a
Linux localhost 3.18.137-g72a7a64494e #1 SMP PREEMPT Fri Sep 27 18:40:34 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

I installed the SDK on `/usr/share/dotnet`, All operations (including installation and building) are executed as `root`.

**Steps to Reproduce**:

```
# mkdir /root/net
# cd /root/net
# dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /root/net/net.csproj...
  Determining projects to restore...
  Restored /root/net/net.csproj (in 377 ms).
Restore succeeded.
# dotnet build
Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/usr/share/dotnet/sdk/6.0.100-preview.2.21155.3/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.dll" exited with code 139. [/root/net/net.csproj]

Build FAILED.

/usr/share/dotnet/sdk/6.0.100-preview.2.21155.3/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "csc.dll" exited with code 139. [/root/net/net.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:26.58
```

**Comment by Frederisk** [comment]
** Binlog**:

```
# dotnet build /bl
```

Then got `[msbuild.binlog](https://cogfwacnz10-my.sharepoint.com/:u:/g/personal/frederisk_databomb_cc/EUrfWAyrw2NAmoZEToCR4cEBGOB7EW-GDFVxeLVw_KojpA?e=Sifynu)`.

**Comment by jaredpar** [comment]
Unfortunately the binlog doesn't contain any information about the crash here. Can you try running with `/v:diag` instead and post that log output here? Hopefully that will contain the stack trace of the crash for us to look at.

**Comment by Frederisk** [comment]
Ran `dotnet build -v:diag | tee ./diag.log` and got [this log file](https://cogfwacnz10-my.sharepoint.com/:u:/g/personal/frederisk_databomb_cc/ETc2RtNC9Z5NqL0nSY3bDDABqJgOPhvlXmRi0DjQKkJEHw?e=BXN5nI).

**Comment by NicoleWang001** [comment]
Also repro with .NET Core 2.1.523 and 2.1.815(runtime 2.1.27)
```
root@315e94406d69:~/myconsole# dotnet build
Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 774.53 ms for /root/myconsole/myconsole.csproj.
/root/mytest/sdk/2.1.815/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/root/myconsole/myconsole.csproj]

Build FAILED.

/root/mytest/sdk/2.1.815/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6006: "csc.dll" exited with code 139. [/root/myconsole/myconsole.csproj]
    0 Warning(s)
    1 Error(s)
```
Here is the log file,
[diag.log](https://github.com/dotnet/roslyn/files/6170129/diag.log)

**Comment by jaredpar** [comment]
Unfortunately the diagnostic logs aren't giving us any info to track down the issue with. Can you post the core dump from the crash or try running the csc.dll directly to see what the diagnostics it prints out are? 

> dotnet exec /usr/share/dotnet/sdk/6.0.100-preview.2.21155.3/Roslyn/bincore/csc.dll

**Comment by Frederisk** [comment]
I'm not sure if my commands are wrong, I am not familiar with `dotnet exec`.
```
# dotnet exec /usr/share/dotnet/sdk/6.0.100-preview.2.21155.3/Roslyn/bincore/csc.dll
Microsoft (R) Visual C# Compiler version 3.10.0-2.21153.36 (8e7913ca)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```
Then I tried to add `-out` option:
```
# dotnet exec /usr/share/dotnet/sdk/6.0.100-preview.2.21155.3/Roslyn/bincore/csc.dll -out:csc.log
Microsoft (R) Visual C# Compiler version 3.10.0-2.21153.36 (8e7913ca)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
error CS5001: Program does not contain a static 'Main' method suitable for an entry point
```
I have no idea about it.

**Comment by jaredpar** [comment]
Interesting. I had assumed it was essentially just a crash in the runtime starting up the compiler. Based on the errors though the compiler is making some headway before it crashes. 

Trying to figure out a way for us to debug this. Don't have easy access to an ARM64 device at the moment.

**Comment by Frederisk** [comment]
This device is private and does not have a fixed IP address, so it is difficult for me to provide remote control permissions for the device.

But you may be able to test it with an Android device with an ARM64 CPU. Here is a simple way to build an Ubuntu environment in Android, and hope it will be useful for you:

- Download and install [Termux](https://play.google.com/store/apps/details?id=com.termux) from Google Play.
- Open it and run `pkg update && pkg upgrade -y` to get package update.
- Then there is a project named ubuntu-on-termux, [install it](https://github.com/MFDGaming/ubuntu-in-termux#installation-steps) and start ubuntu.

After that, you can try to operate on it.
