### ISSUE TITLE
why not C# only  ,  without vb

### ISSUE THREAD

**Issue by icetech233** [dotnet/roslyn#51869]
why not C# only  ,  without vb

no people use vb  !!!!!!!!!!

**Comment by Youssef1313** [comment]
You might not be using VB, but others do. There are actually some complaints for OmniSharp because it doesn't support VB.

It shouldn't harm you if Roslyn supports both.

**Comment by CyrusNajmabadi** [comment]
Closing out. Vb has many users and is still used in many companies and projects.
