### ISSUE TITLE
#error version directive should show language version instead of preview or latest

### ISSUE THREAD

**Issue by binki** [dotnet/roslyn#51879]
**Version Used**: latest master (https://sharplab.io/ as of 2021-03-15).

**Steps to Reproduce**:

1. Write `#error version`.

**Expected Behavior**:

For the “Language version” to show something like `9.0` or `9.1`.

**Actual Behavior**:

The “Language version” is listed as `latest` or `preview`.

The point of this compiler directive is to figure out what the effective language version is. I can already see `/langversion:latest` in the build log. Telling me what parameter was passed doesn’t help me. I am interested in what that is being interpreted as. The interpretation should be clearer and not require me to look up the supported versions and preview features by the compiler version itself.

**Comment by binki** [comment]
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGY4rUgTgAoAiQHg3AQffoEoBuCogYgFNkyAPbIABADcBAZyhCYxIA==

**Comment by Youssef1313** [comment]
Preview should **not** show any specific version because it's not equivalent to any. For latest, default, and latest major, I think it makes sense to show it. Probably between parentheses like `latest (9.0)`.

**Comment by Youssef1313** [comment]
I opened #51880 in case the compilers team wants to show the effective version.

**Comment by binki** [comment]
I understand that preview might be special. However, could it at least show some information to give a general baseline idea to the user, like `9.0+vnext-preview` (not sure how to say that). That would let you know that, even if it is preview of the next version and there could be regressions, one could at least expect to be able to use the language features newly introduced into 9.0, which I think would be helpful.
