### ISSUE TITLE
VisualBasicMakeMethodAsynchronousCodeFixProvider "Make Async Function" doesn't correct code most of the time 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51888]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VisualBasicMakeMethodAsynchronousCodeFix/1369192)._

---
1) intellisense suggest to make this function "async" (this is correct)
! [image.png] (https://aka.ms/dc/image?name=B67551605c51b4bdca51ce234bf7ff401637512566901597022_20210313-192449-image.png&tid=67551605c51b4bdca51ce234bf7ff401637512566901597022)
2) but when the code is corrected, the "Async" keyword is put on the wrong line (it's even worse when there is comments and attributes before the function)
! [image.png] (https://aka.ms/dc/image?name=B25724237031441d385b5d794f265235f637512567591883509_20210313-192558-image.png&tid=25724237031441d385b5d794f265235f637512567591883509)

---
#### Feedback Bot on 3/14/2021, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/15/2021, 10:01 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Input:

```vb
Function Example() As String
    Await Task.Delay(1)
End Function
```

Expected result:

```vb
Async Function ExampleAsync() As Task(Of String)
    Await Task.Delay(1)
End Function
```

Actual result:

```vb
Async
            Function ExampleAsync() As Task(Of String)
    Await Task.Delay(1)
End Function
```

**Comment by Youssef1313** [comment]
A similar issue is being fixed in https://github.com/dotnet/roslyn/pull/51721.

This may help if someone wants to get his first contribution.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
