### ISSUE TITLE
FAQ still refers to preview and many of links don't go anywhere or to the wrong place

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5188]
Found at https://github.com/dotnet/roslyn/wiki/FAQ

Instructions don't match current Roslyn and the link to the FAQ files doesn't exist.
 #%installdir%{CSharp|VisualBasic}\APISampleUnitTests{CS|VB}\faq.{cs|vb}".

I did find the Solution file at roslyn\src\Samples\VisualBasic\APISampleUnitTests.FAQ.VB. along with a solution file.APISampleUnitTestsVB.sln but the load failed with

```
C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj : error  : The imported project "C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\Tools\Microsoft.CodeAnalysis.Toolset.Open\Targets\VSL.Settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj
```

**Comment by jmarolf** [comment]
The project should be loading the targets file located [here](https://github.com/dotnet/roslyn/blob/master/build/Targets/VSL.Settings.targets) (C:\Users\Paul\Documents\GitHub\repos\roslyn\build\Targets\VSL.Settings.targets fore you).

Is [this](https://github.com/dotnet/roslyn/blob/master/src/Samples/VisualBasic/APISampleUnitTests/APISampleUnitTestsVB.vbproj#L93) line the same in your APISampleUnitTestsVB.vbproj file?

**Comment by paul1956** [comment]
No the line is what is in my original message. Except with substituation variables. It is going to a sub directory of src/samples/VisualBasic

**Comment by jmarolf** [comment]
@paul1956 I suggest pulling the latest changes into your enlistment then.  
From command prompt in C:\Users\Paul\Documents\GitHub\repos\roslyn execute the command `git pull`

**Comment by paul1956** [comment]
After Git Pull
```
C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj : error  : The imported project "C:\Users\Paul\Documents\GitHub\repos\roslyn\build\Targets\VSL.Settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.vbproj
```
Looking at the file APISampleUnitTestsVB.vbproj it is identical to the one on my machine

I am loading the file C:\Users\Paul\Documents\GitHub\repos\roslyn\src\Samples\VisualBasic\APISampleUnitTests\APISampleUnitTestsVB.sln it looks like this file expects to be loaded from the parent directory.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #42](https://github.com/dotnet/roslyn-sdk/issues/42) via [**ZenHub**](https://www.zenhub.com/)
