### ISSUE TITLE
Visual Basic Extensibility Analyzer with Code Fix (NuGet + VSIX) doesn't build every time

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5189]
It always works first time after starting VB, after that sometime it builds without error, other times it get two errors. Both errors are on line 235

```
<Exec Command="&quot;$(SolutionDir)packages\NuGet.CommandLine.2.8.5\tools\NuGet.exe&quot; pack Diagnostic.nuspec -NoPackageAnalysis -Version %(Pure_Visual_Basic_RefactoringAssemblyInfo.Version) -OutputDirectory ." WorkingDirectory="$(OutDir)" LogStandardErrorAsError="true" ConsoleToMSBuild="true">
```

```
The system cannot find the path specified
The command ""C:\Users\Paul\Documents\Visual Studio 2015\Projects\Pure Visual Basic Refactoring\packages\NuGet.CommandLine.2.8.5\tools\NuGet.exe" pack Diagnostic.nuspec -NoPackageAnalysis -Version 1.0.5732.37058 -OutputDirectory ." exited with code 3.
```

If I unload the portable class and reload it, everything works ONCE.

**Comment by jmarolf** [comment]
What console output do you get if you run 
```
"C:\Users\Paul\Documents\Visual Studio 2015\Projects\Pure Visual Basic Refactoring\packages\NuGet.CommandLine.2.8.5\tools\NuGet.exe" pack Diagnostic.nuspec -NoPackageAnalysis -Version 1.0.5732.37058 -OutputDirectory .
```
from the output directory for your project?

**Comment by paul1956** [comment]
@jmmarolf do you mean from a Windows Command Prompt or is there some way to run from within VS. I will not be back on computer for 10 hours but will try then. What is strange is it always works the first time the project is loaded and then fails until the project is reloaded (even without exiting VS).

**Comment by jmarolf** [comment]
@paul1956 right, from a command prompt.  Curious to know the actual nuget error message.

**Comment by paul1956** [comment]
```
C:\Users\Paul\Documents\Visual Studio 2015\Projects\Pure Visual Basic Refactorin
g\Pure Visual Basic Refactoring\Pure_Visual_Basic_Refactoring\bin\Debug>"C:\User
s\Paul\Documents\Visual Studio 2015\Projects\Pure Visual Basic Refactoring\packa
ges\NuGet.CommandLine.2.8.5\tools\NuGet.exe" pack Diagnostic.nuspec -NoPackageAn
alysis -Version 1.0.5732.37058 -OutputDirectory .
The system cannot find the path specified.
```
The packages directory is at
```
C:\Users\Paul\Documents\Visual Studio 2015\Projects\Pure Visual Basic Refactoring
```
This does not explain why sometimes it works and others it fails. If the path is wrong it should never work.

**Comment by paul1956** [comment]
I noticed that there is a "\" missing in the path NuGet.CommandLine.2.8.5 should be NuGet.CommandLine\2.8.5 but that does not explain why it works after unloading the project and then reloading.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #43](https://github.com/dotnet/roslyn-sdk/issues/43) via [**ZenHub**](https://www.zenhub.com/)
