### ISSUE TITLE
Async lambda weird behaviour

### ISSUE THREAD

**Issue by IhnatKlimchuk** [dotnet/roslyn#51909]
**Version Used**: 
Microsoft (R) Visual C# Interactive Compiler version 3.8.0-5.20567.16 ()

**Steps to Reproduce**:

1. > var test = new int[] { 100, 10000 };
2. > await Task.WhenAll(test.Select(async t => await Task.Delay(t))); //executed
3. > await Task.WhenAll(test.Select(async t => { return await Task.Delay(t); })); //error CS4029: Cannot return an expression of type 'void'

**Expected Behavior**:
Lines 2 and 3 results the same.

**Actual Behavior**:
Line 2 executed while line 3 failed

**Comment by huoyaoyuan** [comment]
There's nothing wierd. Just remove the `return` since it's a void expression.
Void expression can be used in `=>`, but not in `return`.

**Comment by IhnatKlimchuk** [comment]
@huoyaoyuan question is not why 3 line fails, but why 2 line runs? More example here:
```
var sw = new Stopwatch();
sw.Start();
var olala = (new int[] { 100, 10000 }).Select(async t => await Task.Delay(t)).ToList();
sw.Stop();
var result = sw.ElapsedMilliseconds;
```
//result == 4, means task was not awaited

**Comment by huoyaoyuan** [comment]
The type of `async x => await y;` is `Func<int, Task>` while the type of y is `Task`, and the type of `await y` is `void`. The type of the lambda is `Task` over return type.

**Comment by IhnatKlimchuk** [comment]
Should `async x => await Task.Delay(x)` be `Action<int>` same as `async x => { return await Task.Delay(x); }`. Otherwise `async x => await Task.Delay(x)` is equal to `x => Task.Delay(x)` means `async/await` is ignored and at least info message should appear or error during build.

**Comment by huoyaoyuan** [comment]
> Otherwise `async x => await Task.Delay(x)` is equal to `x => Task.Delay(x)`

Yes, they are identical in result, with a little behavior difference about exception and debugging. The latter is often used as a optimization for the former.

**Comment by IhnatKlimchuk** [comment]
>Yes, they are identical in result 

I expect that fair state machine resulting in `Action<int>` should be better here. I assume that `async/await` is dropped because of expression compiling optimization, please correct me if I'm wrong.

**Comment by huoyaoyuan** [comment]
You are misunderstanding `await`. In fact `expr.Wait()` is closest to what you expect.

**Comment by IhnatKlimchuk** [comment]
I expect to avoid expression usage with `async/await` in such case and use delegate. As mentioned code is misleading:
```
var sw = new Stopwatch();
sw.Start();
var olala = (new int[] { 100, 10000 }).Select(async t => await Task.Delay(t)).ToList();
sw.Stop();
var result = sw.ElapsedMilliseconds;
```

**Comment by huoyaoyuan** [comment]
Async lambda isn't misleading. An `await` means that the **outer task** will wait for the **inner task**, and you now neet to await **outer task** (the task returned by the lambda) to get both task completed. In this case you are throwing away the outer tasks from Select.

**Comment by jmarolf** [comment]
The compiler is operating per the language specification here. If there is something you want changed, I would file a suggestion on http://github.com/dotnet/csharplang
