### ISSUE TITLE
CA1801 was deprecated by IDE0060, but IDE0060 is not ignoring _ in VB parameters 

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#51931]
**Version Used**: 
16.9.2
**Steps to Reproduce**:

Private Function AddSyntaxTrees(_syntaxTrees As IEnumerable(Of SyntaxTree)) As VisualBasicScriptCompilation
    Throw New NotImplementedException()
End Function

**Expected Behavior**:
no IDE0060 shows up for _systaxTree
CA1801 ignore VB names that started with _ and was replaced with IDE0060 which does not ignore names starting with _
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1801?view=vs-2019
![image](https://user-images.githubusercontent.com/12789369/111442065-345b2580-86c5-11eb-931d-0a377db7300b.png)

**Actual Behavior**:
IDE0060 shows up for _systaxTree

**Comment by Youssef1313** [comment]
Aren't both ignoring parameters starting with `_` only if followed by number(s)/integer?

**Comment by paul1956** [comment]
@Youssef1313 while the examples for CA1801 show _ and _0, the description don't say it has to be only a number and for IDE0060 there is no mention of any Discards. As shown below _0 with words is not ignored. I am fine closing this and opening a bug against the documentation of IDE0060 if the rule is _ followed by ONLY a number suppresses IDE0060.
![Capture](https://user-images.githubusercontent.com/12789369/111450383-8dc75280-86cd-11eb-8c60-7218070f793c.PNG)

**Comment by Youssef1313** [comment]
Looking at implementation of CA1801 it tries to parse what comes after the `_` as `uint`. The same is done for `IDE0060`.

You can open an issue against dotnet/docs to be more clear.
For this issue, you *may* keep it open as a feature request until someone from the team reviews it and decides whether they want this behavior or not.

/cc @sharwell @CyrusNajmabadi
