### ISSUE TITLE
Cannot call protected constructors in inheriting classes

### ISSUE THREAD

**Issue by Sellorio** [dotnet/roslyn#51949]
**Version Used**: 

The version included in Visual Studio 2019 Enterprise 16.9.0

**Steps to Reproduce**:

1. Create a base class in code called `BaseClass` (for example) with a protected constructor. This class should *not* be abstract.
2. Create an inheriting class in code called `InheritingClass` (for example) which inherits from `BaseClass`.
3. Create a method in code in the `InheritingClass` and with code intended to instantiate `BaseClass` (e.g. `var instance = new BaseClass()`).

**Expected Behavior**:

Compilation succeeds.

I would expect the behaviour of calling a constructor to align with the behaviour of calling a method with the same visibility.

**Actual Behavior**:

Compilation fails with error CS0122: "'BaseClass.BaseClass()' is inaccessible due to its protection level."

**Comment by CyrusNajmabadi** [comment]
AFAICT, this behavior is by design and as per spec.  As roslyn is properly implementing the spec here, there's no actual issue.  I see there is an open discussion about this on csharplang.  CHanges would need to happen there in order for a change to have to happen to the compiler.  Thanks!

**Comment by Sellorio** [comment]
Can you provide a source for this part of the spec?

**Comment by CyrusNajmabadi** [comment]
> The instance constructor to invoke is determined using the overload resolution rules of Overload resolution. The set of candidate instance constructors consists of all accessible instance constructors declared in T which are applicable with respect to A (Applicable function member). 

https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#object-creation-expressions

> When a protected instance member is accessed outside the program text of the class in which it is declared, and when a protected internal instance member is accessed outside the program text of the program in which it is declared, the access must take place within a class declaration that derives from the class in which it is declared.

The spec also calls out the special exception to this, which is of course:

> In addition to these forms of access, a derived class can access a protected instance constructor of a base class in a constructor_initializer (Constructor initializers).
