### ISSUE TITLE
When generating a method that starts with "Is" use "bool" as the return type if we can't infer anything better.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5195]

**Comment by Pilchie** [comment]
Could also include a number of other prefixes: `Should`, `Has`, etc.

**Comment by CyrusNajmabadi** [comment]
Agreed.

**Comment by mattwar** [comment]
What about other languages?

**Comment by CyrusNajmabadi** [comment]
We'll use the same system we have today and we'll infer 'object.

**Comment by mattwar** [comment]
What about ICanHaz?

**Comment by CyrusNajmabadi** [comment]
This is how it works today:

![image](https://user-images.githubusercontent.com/4564579/216710741-77ba407b-1ec6-480d-ba74-ba8475e1c0df.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/15327.
