### ISSUE TITLE
Better tooling support to debug source generators (breakpoints)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#51962]
## Overview

Since I started using source generators (which again, are brilliant!), I find the debugging experience particularly clunky. Not sure if I'm using the wrong approach here, but more or less my workflow to investigate crashes in my source generators is this:

- I notice that one of my generator isn't working (or see it log a diagnostic for an exception)
- I add a `Debugger.Launch();` call at the first line of the `Execute` method in that source generator
- I rebuild the source generator project
- I rebuild the project using the source generator
- VS shows the popup about an unhandled exception (ie. `Debugger.Launch();`)
- I click "Ok" to debug it into VS, which switches to the debugger and breaks in the source generator
- From there I happily go about actually investigating the exception

Now, this is somewhat clunky but overall not the worst, and it works fine. The issue though is that since Roslyn just tries to run the generator all the time, once you add that line you basically start having VS open the popup "an exception was thrown, launch a debugger?" every 2 seconds, forever. You basically can't work anymore as that window keeps popping up constantly: you have to delete that line, rebuild the generator, clean the other project and then it stops. If you close VS and reopen it, that popup starts showing up every 2 seconds again unless you've also cleaned the solution (since the compiled generator references is cached by VS.

The main issue is that if you just try to add a breakpoint into your source generator, and then rebuild the project using it, that breakpoint will just never actually be hit, despite Roslyn running the shader just fine. Same for using the "Exceptions Settings" window, even if you check an exception to have VS break on it, that doesn't work for a source generator.

## Proposal

Would it be possible to just have breakpoints work from source generators? 😄

As in, so that if you set one and rebuild a project referencing the generator, the breakpoint would just be hit as expected. Then after that you could just remove it and go about your day. Since the generated assembly wouldn't be changed (no more `Debugger.Launch()` call), that isssue with VS just spamming those popups would go away as well.

**Comment by jmarolf** [comment]
CC: @jasonmalinowski and @chsienki

we are working something like this to improve the experience here: https://github.com/dotnet/roslyn-sdk/pull/738 that should make it into Visual Studio 16.10 Preview 2. The intent is that you just set a break point and start debugging as you describe.

Chris has also built https://github.com/chsienki/Kittitas which I hope to leverage so we can make debugging source generators for developers on linux an easy thing to accomplish.

**Comment by Sergio0694** [comment]
That's awesome, glad to hear this is already in the works and coming soon!
Being able to just use breakpoints will make debugging SGs **so much** better and less frustrating! 🥳

**Comment by chsienki** [comment]
This is now supported via generator debugging the roslyn sdk.

**Comment by Sergio0694** [comment]
Just double checking I'm not getting something wrong, I'm not sure I'm follow what the suggested approach is here.

> "that should make it into Visual Studio 16.10 Preview 2. The intent is that you just set a break point and start debugging as you describe."

I'm using VS2022 Preview 3, and just trying to add a breakpoint into a generator and then building a project consuming the generator doesn't actually seem to be working, the breakpoint is never hit and enabled. I still have to add a `Debugger.Launch()` call in my `Execute` method in the generator, then rebuild the generator, then rebuild the consuming project, then click OK in the popup from VS saying an exception was hit, and finally I can enter debug mode at my breakpoint 🤔

**Comment by jasonmalinowski** [comment]
@Sergio0694 There's a bit of setup you do -- you set the _generator_ project as the thing being debugged and you pick one of your other projects in the project properties. There's some documentation here: http://stevetalkscode.co.uk/debug-source-generators-with-vs2019-1610

@chsienki Did we write docs anywhere for this?

**Comment by Sergio0694** [comment]
Just to circle back on this - I realize the issue has been closed as completely but the debugging situation still seems not ideal. I can't find any official docs on MS Docs to debug source generators, and even just reading that blog post the setup seems clunky enough (extra VS workload needed, have to edit the .csproj, then edit the properties, etc.) that I find myself still just literally adding a `Debugger.Launch()` call in my generator, and then just do that. Like, if you add that line then you can literally just debug the generator normally when you build a project consuming it, and you don't need any additional workload or project property to get that to work. Could we just get better tooling for this? As in, would it be possible to just have some "Debug generator" option that would let you pick a project referencing the generator, build that, and just automatically launch the debugger when the generator is launched? That would seem like a much much better UX for generator authors 🙂

As in, the same steps are already possible (and I use them all the time), so it'd just be about providing better tooling for it?
