### ISSUE TITLE
Compiler memory consumption when having Source Generator Analyzer

### ISSUE THREAD

**Issue by kevin-lambert** [dotnet/roslyn#51965]
**Version Used**: .NET SDK 5.0.201 (Windows) / .NET SDK 5.0.102 (Linux-RHEL)

**Steps to Reproduce**:

1. Create a Source Generator project which adds generated classes from CSV files
2. Use this project in another one as Analyer (NuGet or ProjectReference)
3. Compile

**Expected Behavior**:

Both projects compiles successfully, no error

**Actual Behavior**:

The project using Source Generator as Analyzer takes huge amount of RAM, as soon as it exits Execute() method.

On debug, just before exiting Generator:
![image](https://user-images.githubusercontent.com/80917184/111677203-47820880-881f-11eb-93bb-3019f7a4a312.png)

~10 seconds after:
![image](https://user-images.githubusercontent.com/80917184/111677408-7bf5c480-881f-11eb-8172-ba67d427a3b6.png)

On our CI server (Linux RHEL), (where there is less memory), csc executable exits with code 137

**Additional Informations**

- This behavior only happens on large generated cs files -- I'm trying to translate at compile time these CSV ([NOS-Fichiers_Publics.zip](https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics.zip)).
- If the computer has enough RAM, the project compiles successfuly, having à ~9Mb .dll
- Example of generated file
```
namespace Common.NOS.TRE
{
    public partial record AccessibiliteLieu(string Code, string LibelleAdapte, string LibelleCourt, string LibelleLong, System.DateTime DateValid, System.DateTime? DateFin, System.DateTime DateMaJ)
    {
        public const string OID = "1.2.250.1.213.3.3.3";
        public const string Type = "TRE";
        public const string FullName = "TRE_R202-AccessibiliteLieu";

        public static readonly System.Collections.Generic.IDictionary<string, AccessibiliteLieu> Elements = new System.Collections.Generic.Dictionary<string, AccessibiliteLieu>
        {

            { "1", new AccessibiliteLieu("1", "Accessible", "ACC", "Accessible", new System.DateTime(2015, 03, 25, 00, 00, 00, System.DateTimeKind.Utc), null, new System.DateTime(2015, 03, 25, 00, 00, 00, System.DateTimeKind.Utc)) },
// ...
        };
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I'm not certain what can be done here.  If there is a large generated file, then teh compiler will need memory to compile it.  Instead of generating source for this, why not just embed this in a resource that your program can read the values out of when it runs?

**Comment by CyrusNajmabadi** [comment]
In other words, this doesn't seem to be a source generator issue.  I imagine this would be an issue if you just handgenerated such a file and attempted to compile it.  You likely wouldn't have enough memory on your CI machine to do so.

**Comment by jmarolf** [comment]
a source generator is arbitrary code, we cannot stop it from allocating. What would the fix look like at the compiler layer? This should be addressed in the source generator itself.
