### ISSUE TITLE
Doc comment continuation shouldn't do work when /// are in string literal

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#51982]
Hit <kbd>Enter</kbd> at the specified location. It should go to the new line with indentation matching "var code ..." instead of adding `///` at the very beginning of the line.

```csharp
            var code = @"/// <returns>
/// If this method succeeds, it returns <b xmlns:loc=""http://microsoft.com/wdcml/l10n"">S_OK</b>.
/// </returns>";$$
```

cc @CyrusNajmabadi

**Comment by Youssef1313** [comment]
![doc-comment-cont](https://user-images.githubusercontent.com/31348972/111752308-35937a80-889e-11eb-8020-29b34d51c117.gif)

**Comment by Youssef1313** [comment]
Do we expect the feature to work if I press enter **inside** the string literal, but not outside? or **never** if the `///` is inside string literal?

**Comment by CyrusNajmabadi** [comment]
`///` in a string literal should have no impact.

**Comment by joshlang** [comment]
Actually, I just found the opposite while playing with source generators.  It was useful!

[Example at the bottom](https://github.com/joshlang/Cosmogenesis/blob/master/Cosmogenesis.Generator/Writers/PartitionCreateWriter.cs)

I was pleasantly surprised by this bug!  Typing code within a string is annoying, but at least `/// <summary>` dropped the `///` onto the next line for me.

I'd understand if you nuke it... but... hey, at least it worked for me!

**Comment by sharwell** [comment]
Duplicate of #49564
