### ISSUE TITLE
Building C# Project using MSBuild with Nullable enabled causes the compiler to crash

### ISSUE THREAD

**Issue by GeirGrusom** [dotnet/roslyn#51987]
**Version Used**: 

Visual Studio 16.9.0
Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)

**Steps to Reproduce**:

1.  Build a specific C# project. Don't really know what specifically causes the issue because the error report doesn't indicate line number or even file that causes the error.

**Expected Behavior**:

Build succeeds

**Actual Behavior**:

 error MSB6006: "csc.exe" exited with code -2146232797
 
 This issue only presents when using MSBuild and when `<Nullable>enable</Nullable>` is in the project file.
 
 [error.txt](https://github.com/dotnet/roslyn/files/6171263/error.txt)

The error is an IndexOutOfBounds error in the following file:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.SnapshotManager.cs#L66

If there some way I can get some additional information on what exactly is failing? The stack trace makes it look like the null analyzer is getting lost in analyzing the null value of a return expression but that doesn't really narrow it down much. I see that CodeLense also crashes in Visual Studio because of this.

**Comment by Youssef1313** [comment]
Thanks for reporting @GeirGrusom. This looks like a duplicate of https://github.com/dotnet/roslyn/issues/51739 which got fixed by https://github.com/dotnet/roslyn/pull/51851.

See https://github.com/dotnet/roslyn/issues/51739#issuecomment-797748770 for a workaround until the fix is released.

**Comment by GeirGrusom** [comment]
Oh, great! I searched for the stack trace but nothing came up.

Currently we just disabled nullable but when the cause is caused by deep nesting then I know exactly what code is the culprit.

I'll try to run the fix and verify that it solves the issue. Thanks!
