### ISSUE TITLE
"Information Loss" caused by use of `default` in SyntaxNode-Update methods

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#51997]
**Version Used**: 16.10.0 Preview 1.0

**Steps to Reproduce**:

1. call of LocalDeclarationStatementSyntax.Update-Method 

**Expected Behavior**:
No loose of "UsingKeyword".

**Actual Behavior**:
UsingKeyword is set to `null`

See the following discussion:
https://github.com/dotnet/roslyn/discussions/51986

**Comment by RikkiGibson** [comment]
The issue is specifically that `default` is passed as an argument in `Update` methods:

https://github.com/dotnet/roslyn/blob/dafd1b8ea9ce2e6d1c298230d8b37dc5ff4d3970/src/Compilers/CSharp/Portable/Syntax/LocalDeclarationStatementSyntax.cs#L11-L12

**Comment by bernd5** [comment]
Thanks for point that out.
Most `Update` methods are generated but there are some nodes which have custom Update methods.
In my eyes the usage of `default` should be avoided even if the node does not really support the property (e.g. attributes which are introduced because of the inheritance hierarchy).

One sample is: CheckedStatementSyntax

**Comment by bernd5** [comment]
see: PR
