### ISSUE TITLE
MSBuildWorkspace creates documents with wrong checksum algorithm

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#51993]
Currently MSBuildWorkspace uses FileTextLoader as a text loader for created documents. This loader in turn uses TextFactoryService (the only ITextFactoryService implementation we implement) to create SourceText. Although MSBuildWorkspace knows the checksum algorithm from command line parameters it doesn't pass the correponding SourceHashAlgorithm anywhere. 

MSBuildWorkspace is used by dotnet watch to hydrate solution used for Hot Reload. The solution snapshot needs to be captured - all source code must be read from disk when dotnet watch starts. The EnC service also needs to validate that content hashes of the documents in the solution match the hashes in the PDB. If the checksum algorithm of the document SourceText doesn't match the one the compiler used the EnC service can't reuse the already existing SourceText of the document. It needs to create a new one, read the content of the file and calculate the checksum. This results in reading 
each file twice. We could avoid that by updating the SourceTexts in the solution, but that results in a convoluted API: an API that should operate on an immutable solution snapshot now needs to mutate it (return a new one).

**Proposal**
We should add SourceHashAlgorithm parameter to ITextFactoryService.CreateText methods and pass it through.

**Comment by jmarolf** [comment]
@tmat sounds reasonable to me

**Comment by jasonmalinowski** [comment]
Sounds reasonable to me -- do we get this right though in the IDE? I can imagine we don't either.

**Comment by tmat** [comment]
We don't

**Comment by jasonmalinowski** [comment]
@tmat What's the impact of this? Does this break the experience out of the box or does somebody need to configure something special?

**Comment by tmat** [comment]
Perf concern.
