### ISSUE TITLE
Incorrect IDE0052 when using compiler directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51992]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-IDE0052-when-using-compiler-di/1373051)._

---
[severity:It bothers me. A fix would be nice]
If you have a code sample like below, the SomeInt variable will be marked with IDE0052, in debug configurations. 

```
//a private variable that is set from multiple places
private int SomeInt;

#if DEBUG
    //take a shortcut that does not use SomeInt
# else
   //actual production code that use SomeInt
#endif
```

---
#### Feedback Bot on 3/17/2021, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
The variable should be declared in such an preprocessor block as well. Thanks!

**Comment by Nils-Berghs** [comment]
@CyrusNajmabadi no declaring the variable inside the prepcocessor block is not possible/not a solution: The variable is SET in multiple locations (outside of the directives), but the variable is ONLY USED (GET) inside the 'else' clause.

**Comment by CyrusNajmabadi** [comment]
The variable should be declared in a preprocessor block that matches the different use patterns. So you may have two declarations of it, each slightly different based on how it is used in each config.

**Comment by Nils-Berghs** [comment]
@CyrusNajmabadi I repeat '_declaring the variable inside the prepocessor block is not possible/not a solution_'.

A more elaborate example to explain '_The variable is SET in multiple locations (outside of the directives), but the variable is ONLY USED (GET) inside the 'else' clause_'
`
// declare variable
private int SomeInt;
...
// at some point, in some function, set the variable
SomeInt = 7
...
// at some point, in some other function, set the variable, 
SomeInt = 10
...
// at some point in some other function use the variable
#if DEBUG
    //take a shortcut that does not use SomeInt
# else
   DoSomething(SomeInt); //this is the only usage of some int
#endif

`
How would declaring the variables inside a prepocessor block help me? The only solution I see is to wrap every set of SomeInt inside a preprocessor block, but that would be a maintenance nightmare (if I ever wanted to use the variable in the Debug configuratin after all). It would also make the code a lot harder to read/understand, especially if we add multiple of these variables...

**Comment by sharwell** [comment]
@Nils-Berghs You can assign the value to a discard:

```patch
 #if DEBUG
     //take a shortcut that does not use SomeInt
+    _ = SomeInt; // Intentionally not used on this path
 #else
    DoSomething(SomeInt); //this is the only usage of some int
 #endif
```

**Comment by CyrusNajmabadi** [comment]
The best way would be to simply use the varaible in the debug branch in some way.  For example, you could assign it to a discard like so `_ = SomeInt;`.  This would silence the issue.  Alternatively, just suppress the suggestion that is being reported.
