### ISSUE TITLE
Intellisense fills in (Of for things that can be inferred resulting in the developer having to then remove the Of!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#51991]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-fills-in-Of-for-things-tha/1369935)._

---
[regression] [worked-in:2015]
Intellisense on LINQ statements (and other things that use generic types) prompt (Of.

For example, if I am typing OrderBy and use intellisense it fills in:
`. OrderBy(Of`

This is somewhat useless as I always then find myself backspacing the Of and replacing it with Function(x).
VS never used to do this; and this can simply be inferred so shouldn't do this!

---
#### Feedback Bot on 3/15/2021, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Vs has done this for vb for as long as roslyn had existed, and definitely prior to that. 

If you hit tab, we will commit this. If you hit open paren we will not emit the `of`.
