### ISSUE TITLE
Adding semicolon inbetween property name and { get; set; } invalidates rest of the document (excess errors)

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#52]
**Repro:**  

``` C#
public class Class
{
    public int MyProperty; { get; set; }

    // Pretty much anything here causes an error
}
```

Note the `;` after `MyProperty` and before `{ get; set; }`

**Expected:**  
Rest of document not being invalidated and an error that points to the property.

**Notes:**  

When generating code for Razor there have been some cases of users adding semicolons after `@inject` statements resulting in the entire document being invalidated (tons of errors) after

**Comment by paulomorgado** [comment]
Although the intention might have been to declare a property, `public int MyProperty;` is a valid field declaration.

That makes the `{` invalid no matter what comes next.

**Comment by NTaylorMullen** [comment]
@paulomorgado of course, but invalidating the entire remaining document seems way overkill. You still need to balance the `{`, the error should only encompass the balancing of the curly braces.

**Comment by theoy** [comment]
Interesting error recovery case :)

**Comment by paulomorgado** [comment]
I'm curious. How would you recover from that error, @NTaylorMullen?

**Comment by NTaylorMullen** [comment]
@paulomorgado `{ get; set; }` is invalid C# by itself. Whatever is encapsulated inside of the `{...}` should be handled as an individual error and not affect code past it.

If a user were to type: `{ get; set;` without the ending `}` then it'd be a different situation because there'd be unbalanced curly braces; therefore, it may make sense to invalidate the rest of the document in that case.

To sum it all up, if you encounter any variation of `{ get; set; }` without a corresponding property name/type the recovery is to find the next piece of valid standalone C# and mark the previous `{ ... }` as errored code. 

I'm not entirely familiar with the parsing logic/behavior done in Roslyn so I apologize for not being able to go more into familiar detail but that is how we would do it in Razor.
