### ISSUE TITLE
Possible missing compiler error on inherited constraint

### ISSUE THREAD

**Issue by MrJul** [dotnet/roslyn#520]
The following code compiles fine under both the old compiler and Roslyn:
```
class C<T1> where T1 : class {
	class D<T2> where T2 : struct, T1 { }
}
```

I would expect it to be an error, since a type has to be both a `struct` and a `class` to satisfy the `T2` constraint.

Note: this is still handy, I'm currently abusing it to create a [compiler-enforced enum constraint](http://stackoverflow.com/a/28527552/183367).

**Comment by RevensofT** [comment]
Hi @MrJul  ,
What's an error you expect  for when `structure` is a `class` that inherit from `System.ValueType` ?
`Dim Example As New C(Of System.ValueType).D(Of System.IntPtr)`

**Comment by MrJul** [comment]
Closing, the spec specifies this very case explicitly.
