### ISSUE TITLE
Refactoring to implement explicitly an interface can generate invalid code

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#52019]
**Version Used**:  VS 16.10.0 Preview 1.0 - Roslyn 3.10.0-1.21125.6 (93b8af2b)'. Language version: 9.0

**Steps to Reproduce**:

````c#
interface IRepro
{
    void A<T>() where T : class;
}

class Repro : IRepro
{
    public void A<T>() where T : class // Convert to explicit implementation
    {
    }
}
````

![image](https://user-images.githubusercontent.com/509220/111881686-183adb00-8988-11eb-88db-48c565a0c7a9.png)

**Expected Behavior**:

It removes the generic constraint, so the code compile

```
void IRepro.A<T>()
```

**Actual Behavior**:

````
void IRepro.A<T>() where T : class // doesn't compile
````

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me.  Closing out.
