### ISSUE TITLE
Test plan for "virtual statics in interfaces"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52011]
Spec: https://github.com/dotnet/csharplang/issues/4436

- [ ] Add RuntimeFeature constant and logic (issue https://github.com/dotnet/runtime/issues/49905)
- [ ] Flag RuntimeFeature constant with preview flag

**Comment by 333fred** [comment]
@AlekseyTs is there anything left to do for this? I thought you already added the flow flag.

**Comment by AlekseyTs** [comment]
@jcouv Is this a dupe of https://github.com/dotnet/roslyn/issues/52221?

**Comment by AlekseyTs** [comment]
> I thought you already added the flag.

Runtime team took care of this.

**Comment by jcouv** [comment]
Ah, makes sense. Closing as dupe of https://github.com/dotnet/roslyn/issues/52221
