### ISSUE TITLE
Test plan for "sealed record ToString"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52031]
Proposal: https://github.com/dotnet/csharplang/issues/4174

Scenarios:
- [x] verify execution of `ToString` on derived record
- [x] LangVer

Tagging @thomaslevesque

**Comment by jnm2** [comment]
Should this issue or the feature status document be updated now that https://github.com/dotnet/roslyn/pull/52029 is merged?

**Comment by jcouv** [comment]
Indeed. Closing since the feature was reviewed and merged.

**Comment by jcouv** [comment]
The status document will be updated shortly: https://github.com/dotnet/roslyn/pull/52575
