### ISSUE TITLE
Avoid boxing in LiveTableDataSource TableEntriesSnapshot.TryGetValue

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#5203]
I noticed a 'busy' hang working with Roslyn that was due to the error list populating (with over 200,000 errors).
From a profile, 20% of the allocations were boxed GUIDs from the following frame:
```microsoft.visualstudio.languageservices!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable+LiveTableDataSource+TableEntriesFactory+TableEntriesSnapshot.TryGetValue(int32,class System.String,class System.Object&)```

It looks like the only Guid there is the ProjectGuid (and, maybe Guid.Empty). Suggest: Store the ProjectGuid as an object (or ```Strongbox<Guid>```) so it can be boxed just once. (My assumption is that TryGetValue is called very frequently when updating the error list)

After the Guids, I also notice that 8% of allocations were of type ```Microsoft.VisualStudio.Shell.TableManager.ErrorRank``` from the same callstack. Since there are only a few well-known values, I suggest we create a small array of boxed values for them.

**Comment by heejaechang** [comment]
thank you @pharring. yes. I should have done that.

**Comment by heejaechang** [comment]
https://github.com/heejaechang/roslyn/commit/88f2b8aa74a5f664e63f0b40811876ffe2629f3a

fix is part of other change since I have been making a big change around the same code area. but this commit itself should be small and distinct enough to be code review separately.

**Comment by heejaechang** [comment]
@pharring can you take a look?

**Comment by pharring** [comment]
Looks good. The ConcurrentDictionary was more than I expected, but it should at least address the allocation part of the performance issue.
