### ISSUE TITLE
VS 2019 16.9.2 - StreamJsonRpc.RemoteInvocationException: Failed to start host 'desktopClr$RoslynCodeAnalysisService'

### ISSUE THREAD

**Issue by theMickster** [dotnet/roslyn#52058]
**Version 16.9.2**: 

**Steps to Reproduce**:

1. Updated Visual Studio Enterprise and Professional to 16.9.2.
2. Open a solution that has xUnit test projects
3. Receive error. 

I can build the solution & individual projects without issue. However, Visual Studio prompts me that a critcal service is not running and that I should restart Visual Studio.

**Expected Behavior**:

**Actual Behavior**:
[VisualStudioError001.txt](https://github.com/dotnet/roslyn/files/6185261/VisualStudioError001.txt)
[VS2019_TestExplorerException.txt](https://github.com/dotnet/roslyn/files/6185262/VS2019_TestExplorerException.txt)

**Comment by jinujoseph** [comment]
@theMickster is the issue is still repo'ing for you can you pls file a ticket using VSfeedback https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio

**Comment by theMickster** [comment]
Hello @jinujoseph 

I cannot submit telemetry data because it is not allowed due to my employers secure government environment.  After attempting repair after repair and several re-installations of Visual Studio which resulted in every more problems and hard errors, the helpdesk actually had to re-image my workstation. I appreciate your help, but you can close this issue unless you've got some ideas about how you could improve the product for 16.10. 

Best,
Mick

**Comment by jinujoseph** [comment]
@theMickster Sorry to hear about your experience. I will keep an eye on the issues to see if we see a similar pattern reported by anyone, else it would be hard to detect what might be going wrong and redirect the issue to the right team.
Thanks for understanding.
