### ISSUE TITLE
Proposal: Memoization (Cached Functions)

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5205]
Currently one would define
```C#
static Func<T, TResult> Memoize<T, TResult>(Func<T, TResult> f) {
    var cache = new Dictionary<T, TResult>();
    return arg => {
        TResult result;
        return cache.TryGetValue(arg, out result) ? 
            result : cache[arg] = f(arg);
    };
}
```
to create cached version of a method based on its argument.
```
Fun<int,bool> CachedIsPrime = Memoize<int,bool>(n => { ... });
```
But this just works for a single parameter function.

It would be great to be able to write
```C#
public static pure bool IsPrime(int n) { ... }  // or
public static cached bool IsPrime(int n) { ... } 
```

**Comment by Eyas** [comment]
I'm unsure if the right thing to do in the *language*.

A tangentially related change is how Roslyn no longer allocates a `Dictionary` for long switch statements. You'll also be adding a hidden dependence on System.Collections.dll for .NET Core, I believe (?),

I took a crack at implementing that as a helper class, [`LazyFunc`](https://github.com/Eyas/Ibra/blob/master/IbraLib/src/Ibra.Lazy/LazyFunc.cs#L53), similar to C#'s `Lazy`, addressing the recursive case where you'd want *some* recursion (e.g. in the case of `fib(n)`) to work, but others to be illegal without a `StackOverflowException`. This might be interesting to suggest in [/dotnet/CoreFX](/dotnet/corefx/), but a single helper function or library also seem like good places.

I'm not convinced a language construct is good for anything other than brevity; and I'm not sure this is beneficial/common enough to warrant it. Especially with the issues mentioned above.

**Comment by bbarry** [comment]
This Memoize function is not thread safe.

The following process can be done in code today with IL rewriters such as https://github.com/Fody/Fody:

Input:

    [Cached]
    public int MyPureFunction(int a, int b, int c) { 
        //method body
    }

Output:

    [Cached]
    [AttributeProcessed] 
    public int MyPureFunction(int a, int b, int c) { 
        return __cache_MyPureFunction.GetOrAdd(Tuple.Create(a, b, c), __wrap_MyPureFunction);
    }

    ConcurrentDictionary<Tuple<int, int, int>, int> __cache_MyPureFunction = 
        new ConcurrentDictionary<Tuple<int, int, int>, int>();

    private int __wrap_MyPureFunction(Tuple<int, int, int> args) {
        //this could be skipped but having it allows the method body to be completely unchanged
        return __impl_MyPureFunction(args.Item1, args.Item2, args.Item3);
    }

    private int __impl_MyPureFunction(int a, int b, int c) { 
        //method body
    }

**Comment by alrz** [comment]
why borhter.
