### ISSUE TITLE
[Discussion] Argument spreading via the new value tuples?

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#5206]
Since their proposed syntactic sugar already looks so much like an argument list, would it be possible to automatically spread the value tuples across the argument list?

``` c#
(double, double) InterquartileRange(IEnumerable<double> data) { ... }
double Width(double left, double right) { ... }

...

var w = Width(InterquartileRange(sample)); 
```

Open questions:

Do we need a spread operator? Most good symbols are already taken for other purposes (I am partial to `~` myself), but without it we might run into a problem:

``` c#
double Width(double left, double right) { ... }
double Width(ValueTuple<double, double> interval) { ... } //Oh no, which one will the compiler choose?
```

Does partial spreading make sense? If we have an `int foo(int, int, int)` and a `ValueTuple<int, int> bar`, can we call it via `foo(~bar, 42)`?

Does it make sense to support it for the record classes? I don't think so personally, since you will break your code as soon as you turn your record class into a regular one.

**Comment by ashmind** [comment]
Would be nice to have this together with some keyword for arguments-as-a-tuple, so we could do this:
```csharp
public override void M(X x, Y y, Z z) {
    DoSomething();
    base.M(...arguments); // using '...' from ES6
}
```

**Comment by iDaN5x** [comment]
I think that including a spreading operator with the introduction of tuples makes sense.
It could have been nice `*` would be available to use, as it is the "splat" operator in Ruby, Python and more. The tilda (`~`) symbol is a nice alternative though.

Partial spreading sounds like bad idea to me as it might be confusing to read, especially When working on code that was not originally written by you.

When encountering a line as: `Foo.bar(~bakedPotatoTuple, 5)`
you would probably have to check the function signature to see wtf the last argument is all about.

Even worse - partial spreading could potentially allow: `Foo.bar(~tuple1, 5, ~tuple2)`
which can lead to a massive increase in the suicide rate along the IT industry.

Something I would like to suggest the following syntax:
```
(int x, double d) SomeFunc() { ... }

void OtherFunc() {
    ...
    foo, bar ~= SomeFunc();
}
```

This could allow us to quickly and easily spread the tupple into it's ingredients.

**Comment by Richiban** [comment]
Great idea! I remember when I first learned F# (years ago now) it kind blew my mind that not only could I call a function like this:

`foo("Johnny", 5)`

but also like this: 

```
let args = "Johnny", 5
foo args
```

Whilst we're on the subject, I'd appreciate (perhaps in some future release) that the language obviates the need to double-parenthesize tuples if used as a single argument to a function. 

In the current VS preview, if I define a function as this:

```public void Foo(int a, int b) { ... }```

Then I can call it like this:

```Foo(a: 4, b: 5)```

But if I define the function like this: 

```public void Foo((int a, int b) args)```

which, if you're used to functional languages, is the same thing then I must call it like this:

```Foo((a: 4, b: 5))```

I know that C# doesn't want to completely abstract away the existence of tuples in methods the way F# does, but that double set of parentheses still feels so awkward...

**Comment by jcouv** [comment]
I'll go ahead and close this discussion. Please move or re-open on csharplang for discussion (if there isn't one already). 
Let me know if you need help doing that (I use the ZenHub extension for that purpose). Thanks
