### ISSUE TITLE
.net core memory leak with CodeAnalysis.Scripting

### ISSUE THREAD

**Issue by yoda07** [dotnet/roslyn#52076]
**Version Used**: 
dotnet core 5.0.201
**Steps to Reproduce**:

I found a memory leak problem in my project, after debugging it with looking into DMP file now I am sure the problem is with an object named List\<Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader+AssemblyIdentityAndLocation> (below is the object with problems). The highlight row in the picture says it detects there is a loop. But I am not sure where the class InteractiveAssemblyLoader is used. Did anyone encounter the same problem? Thanks!

![image](https://user-images.githubusercontent.com/1408396/112204634-1d3e9b00-8bd1-11eb-940f-23b3d9d94e88.png)

**Comment by yoda07** [comment]
With a further look into the diagnostics report from dotMemory, I found that this object is consisted of a list of string of every dependency my project is using. And for every request comes in, this object is appended with duplicate items. 
![image](https://user-images.githubusercontent.com/77533415/112242623-330e9780-8c87-11eb-8d22-b690a4433b58.png) As shown in the image, item `InteractiveAssemblyLoader+AssemblyIdentityAndLocation` has many duplicate object which refers to a dll file path of my project. And as I can observe, eachtime I send a request, 8 more duplicate objects will be appended, 
but I have made everything relate to Rosyln singleton or static. Can anyone help with this please

**Comment by jmarolf** [comment]
@tmat I believe this is by-design correct? We hold onto state from previous submissions

**Comment by yoda07** [comment]
@jmarolf I have fixed it. Seems like the method `ScriptState.ContinueWithAsync` will reload the assembly every time it is called. So I store the returned delegate and invoke them when I need to use them.
