### ISSUE TITLE
Equivalence key shouldn't be null

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52074]
The custom code actions, for example, this one:

https://github.com/dotnet/roslyn/blob/1cca63b5d8ea170f8d8e88e1574aa3ebe354c23b/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/CustomCodeActions.cs#L26-L38

makes it very easy to miss passing equivalenceKey. I think the optional parameter should be required.

**Comment by Youssef1313** [comment]
From doc comment:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs#L39-L53

> - Two code actions are treated as equivalent if they have equal non-null <see cref="EquivalenceKey"/> values

This means an action with null equivalence key will never be considered equivalent to any other code action.

> Additionally, a Fix All operation will apply only code actions that are equivalent to the original code action.

This means an action with null equivalence key won't work with FixAll.

This is confusing because the following test passes:

https://github.com/dotnet/roslyn/blob/a6bf13f010e1b93989524170393c7d6a867288e7/src/Analyzers/VisualBasic/Tests/RemoveUnnecessaryByVal/RemoveUnnecessaryByValTests.vb#L94-L109

while the code fix provider is using null equivalence key.

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Analyzers/VisualBasic/CodeFixes/RemoveUnnecessaryByVal/VisualBasicRemoveUnnecessaryByValCodeFixProvider.vb#L49-L55

**Comment by Youssef1313** [comment]
@sharwell Can you please take a look? Is equivalence key should always be non-null? and how it affects fix all?
I tried ByVal analyzer in the IDE and FixAll appears to be working, seemingly to contradict the documentation above.

**Comment by sharwell** [comment]
Two code actions which both use null for the equivalence key are considered the same for fix all.

Yes, it's desirable to use a non-null, non-localized string for these (at least internally).

**Comment by Youssef1313** [comment]
> Two code actions which both use null for the equivalence key are considered the same for fix all.

So the documentation comment is out-of-date? - or they are considered equal only for fix all, but not some other scenarios?

I'll look into removing the optional parameter and make sure all callers pass the equivalence key.
