### ISSUE TITLE
The `using` keyword is offered between two extern alias directives even though its illegal there.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#52097]
The following unit-tests fail:
```csharp
        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
        public async Task TestBetweenExtern()
        {
            await VerifyAbsenceAsync(SourceCodeKind.Regular,
@"extern alias Goo;
$$
extern alias Goo;");
        }

        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
        public async Task TestBetweenExternAfterGlobal()
        {
            await VerifyAbsenceAsync(SourceCodeKind.Regular,
@"extern alias Goo;
global $$
extern alias Goo;");
        }
```

**Comment by AlekseyTs** [comment]
CC @CyrusNajmabadi

**Comment by sharwell** [comment]
This is almost certainly by design. Typing scenarios are based on top-down approaches, so content existing only after the caret cannot invalidate something that would otherwise be valid at the caret location.

**Comment by sharwell** [comment]
I guess I should say the behavior of `TestBetweenExtern` would be by design. The behavior of `TestBetweenExternAfterGlobal` is not necessarily by design, but would this ever be expected in practice?

**Comment by AlekseyTs** [comment]
> I guess I should say the behavior of TestBetweenExtern would be by design.

I would be fine with that, I guess. However, just FYI, we explicitly not offer the keyword before an `extern alias` directive, i.e. when the first ```extern alias Goo;``` is removed from the tests.

**Comment by CyrusNajmabadi** [comment]
We're ok with this behavior.  extern-aliases are in teh "don't care unless it's a crash" category for the IDE.
