### ISSUE TITLE
Debug Thrown Exceptions of Roslyn Analyser / Code Refactoring

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#521]
When debugging a codefix (for example) it launches an Experimental instance of VS. 
Should you're codefix throw an exception the VS doesn't go back in to the original instance of VS.
This would be very useful to aid in debugging the issue.

Instead it crashes the VS(Experimental) and find some notion of the error, you have to go looking in the ActivityLog.xml

If the VS(original) was used, and a debug breakpoint was at the line where the exception happened.
If the  contents of the variable was also available as well.

ie Have the debugger attached to the DLL(s) of you  codefix.

**Comment by jmarolf** [comment]
> VS doesn't go back in to the original instance of VS

Don't know what you mean here.  If you launch an experimental Visual Studio instance with your analyzer/codefix installed as a VSIX (the default way debugging is set up in the templates) your "original" instance of Visual Studio (the one attached for debugging) will catch exceptions thrown by your codefix or analyzer.  If the debugger is not catching exceptions thrown by the process its attached to, thats a bug.

>Instead it crashes the VS(Experimental) and find some notion of the error, you have to go looking in the ActivityLog.xml

Currently we have a one-strike-and-you're-out policy regarding codefixes and analyzers throwing exceptions. If you throw an unhandled exception, we catch it and disable the throwing codefix/analyzer.    I'm working on issue #268 so the user has the option to keep the codefix/analyzer running if they want. It should never be able to bring down Visual Studio, could you please file a bug on this?

>Have the debugger attached to the DLL(s) of you codefix.

We have a test project that you could debug if you wanted to debug without launching a new Visual Studio process, but I admit this is not ideal. Perhaps we could come up with a more general console application that you could pass files into?  What do you think?

**Comment by AdamSpeight2008** [comment]
The VS(original)'s debugger is attached as it is possible to set a breakpoint and step-through my code.

If my code causes an exception to be thrown *(highly likely I wrote it)*, it should  go back to VS(original), and highlight the section of your code at the point the exception was thrown. Like a crash dump, since it as access to the source.
> Perhaps we could come up with a more general console application that you could pass files into? What do you think? 
Good, or a simple VS Isolated shell, or a way put the Experimental instance into isolated test mode, which just the minimum required to tryout your analyser etc

**Comment by srivatsn** [comment]
Since we handle the exception in the codefix engine (to turn off the fixer), the original VS wouldn't see this exception as unhandled and wouldn't know to stop. If you, however, turn on first chance exceptions, you should see that the original VS stops at your line of code in the fixer.
