### ISSUE TITLE
Is nint/nuint operator expected be work with Expression?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#52102]
**Version Used**: 3.10.0-1.21125.6 (93b8af2b)

**Steps to Reproduce**:
```cs
Expression<Func<nint, nint>> b = (a) => a + 1;
```

**Expected Behavior**:
Not sure

**Actual Behavior**:
Now roslyn is able to compile that with no warn, but runtime not supported it(tested with net6.0 preview2), and get `System.InvalidOperationException: The binary operator Xxxxx is not defined for the types 'System.IntPtr' and 'System.IntPtr'.`(also for nuint, `Nullable<nint>`, `Nullable<nuint>`)
It that something by design?

**Comment by jmarolf** [comment]
The Expression compiler has not been updated in quite some time and has not kept pace with the C# language. @jaredpar I believe this is by design?

**Comment by jaredpar** [comment]
Correct this is by design, these are not supported in expression trees.
