### ISSUE TITLE
Please expose an API for detecting assembly-agnostic attributes and modifier types

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52119]
All attributes and modreq/modopt types recognized by the compiler are recognized regardless of visibility and regardless of which assembly defines them or how many references define their own. This is true to such an extent that the compiler even synthesizes internal attributes for NullableAttribute (see on [SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4GIB2BXZyCGwyApgATGaEkCwAUHQAIBMpAwnQN52k+kMCMABgD8pALIAKAJSkAvAD5SOPAG46AXzpA==)) and IsByRefLikeAttribute.

Other community analyzers take a similar approach, defining internal source attributes in the project that consumes the analyzer, and recognizing the attributes by full metadata name without regard to visibility or assembly, just as the compiler does with its attributes.

The same thing happens with non-attribute types like the `IsExternalInit` type used as a modreq to tell whether an accessor is `init` or `set`. The compiler doesn't care how many assemblies define it or what visibility it has, when it comes to the question of whether a particular modreq is `IsExternalInit`.

Besides attribute types and modifier types, I'm not sure if the compiler treats other types in an assembly-agnostic way. For instance, it would be interesting to know if `await` is just as happy with an internal INotifyCompletion declared by a different assembly when there is a separate public INotifyCompletion visible from the BCL.

I'm thinking that `bool INamedTypeSymbol.HasMetadataName(string metadataName)` could be both zero-alloc and user-friendly, but I'm happy so long as the semantics are right (visibility and containing assembly is not factored in to the answer).

On top of that, please include an analyzer that warns if you are using Compilation.Get(Best)TypeByMetadataName + default symbol equality to answer questions about attributes and modifier types that are known to be assembly-agnostic. This is a pitfall because it will return factually incorrect answers.

**Comment by 333fred** [comment]
Going to close this out as missing a usecase.

**Comment by jnm2** [comment]
Thanks for looking! Yes, and I no longer remember what I was working on at the time.
