### ISSUE TITLE
Bug when using to using statement

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/roslyn#52116]
### Description

Visual Studio gave me a code hint to convert my `using` into a using declaration. This resulted in `ToString` on my `StringBuilder` returning `""`.

```cs
using System.Text;
using System.Xml;
using System.Xml.Linq;

public class Program
{
    public static void Main()
    {
        var html = "<article><h2>Hello!</h2></article>";
        var sb = new StringBuilder();

        using (var writer = XmlWriter.Create(sb))
        {
            XDocument.Parse(html).Save(writer);
        }

        System.Console.WriteLine(sb.ToString());
    }
}
```

This returns:

    <?xml version="1.0" encoding="utf-16"?><article><h2>Hello!</h2></article>

After converting the `using` into a using statement:
```cs
using System.Text;
using System.Xml;
using System.Xml.Linq;

public class Program
{
    public static void Main()
    {
        var html = "<article><h2>Hello!</h2></article>";
        var sb = new StringBuilder();

        using var writer = XmlWriter.Create(sb);
        XDocument.Parse(html).Save(writer);

        System.Console.WriteLine(sb.ToString());
    }
}
```

It returns empty.

### Configuration

- .NET 5
- Windows 10
- x86-64

**Comment by CyrusNajmabadi** [comment]
Closing as no repro. The behavior as Steven describes is how the feature has worked from the beginning.

**Comment by vanillajonathan** [comment]
@stephentoub, @CyrusNajmabadi 
But Visual Studio tells suggest to convert to a using statement in this code.

```cs
        public string GetString()
        {
            var sb = new StringBuilder();
            var svg = GetString();
            var document = XDocument.Parse(svg);

            // Convert to using statement breaks this
            using (var writer = XmlWriter.Create(sb))
            {
                document.Save(writer);
            }

            return sb.ToString();
        }
```

**Comment by stephentoub** [comment]
What version of Visual Studio are you using?

Can you show a screenshot of it offering that suggestion on this code?

**Comment by vanillajonathan** [comment]
Visual Studio 2019, version 16.9.2.

![image](https://user-images.githubusercontent.com/10222521/112493738-b82aa700-8d82-11eb-92e8-50c1f5475077.png)

![image](https://user-images.githubusercontent.com/10222521/112493913-db555680-8d82-11eb-8dc1-84f2757fb86c.png)

```cs
using System.Text;
using System.Xml;
using System.Xml.Linq;

namespace Example
{
    class Class1
    {
        public string GetString()
        {
            var sb = new StringBuilder();
            var document = XDocument.Parse("<article><h2>Hello!</h2></article>");

            // Convert to using statement breaks this
            using (var writer = XmlWriter.Create(sb))
            {
                document.Save(writer);
            }

            return sb.ToString();
        }
    }
}
```

**Comment by stephentoub** [comment]
Are you using Resharper?  I believe it's providing that "Convert to 'using' declaration", not Visual Studio's built-in analyzers.

**Comment by stephentoub** [comment]
In fact, it looks exactly like this bug reported to JetBrains:
https://resharper-support.jetbrains.com/hc/en-us/community/posts/360009408379-Incorrect-suggestion-to-Convert-to-using-declaration

**Comment by vanillajonathan** [comment]
Oh my bad, yes I am using ReSharper and I believe this is the bug I've encountered.
