### ISSUE TITLE
PrintMembers() seems to be culture dependent

### ISSUE THREAD

**Issue by simonziegler** [dotnet/roslyn#52125]
I am serializing a Dictionary for an HTTP call. The server and client cannot be guaranteed to have the same culture. I have a composite dictionary key of similar to `MyKey`:

```
public enum MyEnum { This, That, TheOther }

public record MyKey
{
    public MyEnum Value { get; init; }
    public DateTime Date1 { get; init; }
    public DateTime Date2 { get; init; }
}
```

My server (running in an Ubuntu container in an azure web app) seems to be running with an en-US culture, and the key gets serialized with a string from `PrintMembers()` representing e.g. today's date of 24 March 2020 starting with "03/24/2021 ...".

My client happens to be in the UK and cannot interpret this date.

Suggestion: should `PrintMembers()` use an invariant culture?

**Comment by CyrusNajmabadi** [comment]
I think this is intended.  We just call .ToString on all members.

> My client happens to be in the UK and cannot interpret this date.

These strings are not intended for interpretation.  Just convenience for things like debugging.  Logic should not be built that attempts to backwards infer anything from these.  Instead, any code that wants to display a record in a context where thsi is relevant should build an appropriate mechanism to display the record itself.

**Comment by simonziegler** [comment]
Thanks for the response and understood. One last suggestion, if you were to use the [round trip "O" format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier), the string would be predictable for anybody who did want to use it for something more than just display.
