### ISSUE TITLE
Complete statement command doesn't work inside `typeof`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52137]
![completecommand](https://user-images.githubusercontent.com/31348972/112462003-3d08c700-8d69-11eb-9c65-07574219451b.gif)

**Comment by bernd5** [comment]
Can you provide a reproducible sample with detailed error information?

**Comment by Youssef1313** [comment]
It's not really an "error", but just a feature doesn't work in the case of `typeof`. The GIF in the issue shows when the feature works with a function, and when it doesn't work with typeof. It also seems to be expected based on the feature's code:

https://github.com/dotnet/roslyn/blob/e90f87ca48259367112f73c46f01ccda5a3339f5/src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs#L173-L181

**Comment by Youssef1313** [comment]
@jinujoseph The bot didn't put either an "untriaged" label nor an "Area-*" (IDE) label.

**Comment by jinujoseph** [comment]
thanks for pointing it out @Youssef1313.
@jaredpar for info on bot missing out the label
