### ISSUE TITLE
Update the csi basic command-line REPL

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#5214]

**Comment by tmat** [comment]
@kuhlenh Does https://github.com/dotnet/roslyn/issues/5214 resolve this issue, or is there some more  work (other than what's captured in other issues)?

**Comment by kuhlenh** [comment]
@tmat I think you linked to the wrong thing, but yes your work should have resolved this!

**Comment by ManishJayaswal** [comment]
@kuhlenh  I am closing this. Please reactivate if there is more to be done here.
