### ISSUE TITLE
Operator conversion completion does not show if followed by `var` statement

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#52155]
![image](https://i.imgur.com/JDePTIi.gif)

**Comment by Youssef1313** [comment]
cc: @MaStr11

**Comment by MaStr11** [comment]
This is a known issue. It was first mentioned here https://github.com/dotnet/roslyn/pull/47511#discussion_r494392309 and is already covered by a test case. @CyrusNajmabadi This was discovered before you moved the logic to `IRecommendationService` and I was expecting, that the `IRecommendationService` would handle such cases properly. Do you have an idea why this wasn't resolved after you moved the logic to `IRecommendationService`?

**Comment by CyrusNajmabadi** [comment]
No clue. Will have to debug through to find out.

**Comment by MaStr11** [comment]
This code path needs to be called, to solve the issue:

https://github.com/dotnet/roslyn/blob/4ab21f1b9b6125c783531ab7a0d2479efd5fe306/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs#L250

**Comment by MaStr11** [comment]
@CyrusNajmabadi I found the problem and created a PR #52189
