### ISSUE TITLE
C# LSP doesn't support operator conversion completion.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#52154]
1. Enable C# LSP Experimental editor in VS:
![image](https://user-images.githubusercontent.com/2008729/112552196-a3004900-8d7f-11eb-9171-3c6fa43b5823.png)
2. In any C# file type:
```C#
var abc = 123;
abc.
```
3. You'll get:
![image](https://user-images.githubusercontent.com/2008729/112552244-b7444600-8d7f-11eb-8d21-401261f75aab.png)
4. Complete any of the operator conversions at the end.

**Expected:**
![image](https://user-images.githubusercontent.com/2008729/112552494-2883f900-8d80-11eb-89e8-56c41e7a1f22.png)

**Actual:**
Without the experimental completion support in C#:
![image](https://user-images.githubusercontent.com/2008729/112552295-c88d5280-8d7f-11eb-9cdb-16215430fb87.png)

With:
![image](https://user-images.githubusercontent.com/2008729/112552317-d3e07e00-8d7f-11eb-8656-90b868510b8f.png)

**Comment by CyrusNajmabadi** [comment]
this is not on on @MaStr11 .  This is an issue on the LSP side :)

**Comment by MaStr11** [comment]
But even without the flag (*Without the experimental completion support in C#:*) the completion result is wrong and unexpected. The given example should produce the expected outcome given this test:
https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ConversionCompletionProviderTests.cs#L358-L391

Note: It seems, we don't have completion tests for built-in conversion. We do only test the completion offering and completion for lifted conversions:

Completion offering for built-in conversions:
https://github.com/dotnet/roslyn/blob/549954146946988e16a1fd49fd079ab4282f883c/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ConversionCompletionProviderTests.cs#L1084

Lifted completion:
https://github.com/dotnet/roslyn/blob/549954146946988e16a1fd49fd079ab4282f883c/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ConversionCompletionProviderTests.cs#L1147

**Comment by dibarbet** [comment]
seems to be working in 17.12 (and VSCode).
