### ISSUE TITLE
Loop invariant can be hoisted in CompletionServiceWithProviders

### ISSUE THREAD

**Issue by m08pvv** [dotnet/roslyn#52165]
[On line 304](https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs#L304) we can see a condition that can be checked once outside the foreach.
It seems that there is no reason to keep it inside the loop because it compares values that mustn't be changed during the enumeration (moreover, I suspect that they mustn't be changed during the whole execution of `GetCompletionsWithAvailabilityOfExpandedItemsAsync`

If it's ok, I can create a PR (or anyone else can do it).

**Comment by Youssef1313** [comment]
I think you can open a PR and wait for a feedback on it. As far as I know, PRs are more preferred than issues for small fixes.

**Comment by RikkiGibson** [comment]
Can this issue be closed?

**Comment by m08pvv** [comment]
Fixed in [PR 52168](https://github.com/dotnet/roslyn/pull/52168)
