### ISSUE TITLE
Expose a public API for creating source suppressed diagnostics

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#5217]
https://github.com/dotnet/roslyn/pull/5152 adds support for retaining diagnostics suppressed in source (pragma/disable directives OR SuppressMessageAttribute) in the error list. Theoretically, only the compiler layer needs to mark a diagnostic as a source suppressed diagnostic. However, the IDE layer needs to round trip diagnostics between `Diagnostic` and `DiagnosticData` type and hence needs ability to create source suppressed diagnostics. However, adding a new `Diagnostic.Create` overload just for this flag, when none of the analyzer authors would (or infact should) create source suppressed diagnostics, seems an overkill.

We should discuss this at the next diagnostics design meeting.

/cc @lgolding

**Comment by mavasani** [comment]
New overload for Diagnostic.Create was approved by the design team and has been checked in.

**Comment by heejaechang** [comment]
related to https://github.com/dotnet/roslyn/issues/2304
