### ISSUE TITLE
Cross Project Add Using Broken For Types Generated By Source Generators 

### ISSUE THREAD

**Issue by adstep** [dotnet/roslyn#52184]
**Version Used**: 
16.9.2

**Steps to Reproduce**:

1. Create Two Projects (`Proj1`, `Proj2`) w/ `Proj1` being a project reference of `Proj2`
2. Run Source Generator on Proj1 Generating interface `MyInterface`
3. Go to project 2 and try and use `MyInterface`. 

Hit this behavior with a Test project depending on the auto generated type from another project. Can work around by manually adding the namespace of the source generated type.

**Expected Behavior**:
Intellisense should prompt to add appropriate namespace.

**Actual Behavior**:
Doesn't prompt to add namespace.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Any chance you fixed this with your recent work cleaning some of this up?

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this.
