### ISSUE TITLE
BinaryExpressionSyntax WithOperatorToken(SyntaxToken) method

### ISSUE THREAD

**Issue by Hosch250** [dotnet/roslyn#5219]
The `BinaryExpressionSyntax` `WithOperatorToken(SyntaxToken)` method in C# just takes an operator and updates the binary expression it is part of, like this:

    var newOperatorToken = SyntaxFactory.Token(SyntaxKind.LessThanEqualsToken);
    var newExpression = expression.WithOperatorToken(newOperatorToken);

This will return a new `BinaryExpressionSyntax` with the new operator; however, it does not update the expression `Kind`.  This means that I can have an expression of kind `LessThanExpression` and change the operator to a greater-than operator, but the expression kind will not change to a `GreaterThanExpression`.

The Visual Basic version of the same thing does not work because it [checks that the type of the binary expression is the same as the operator](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.VisualBasic/Syntax.xml.Generated.vb#109682), where as [the C# version just checks that it is a valid type](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs#71151).  This prevents me from assigning a greater-than operator to a `LessThanExpression`; however, there is now no simple way to change the operators on binary expressions.  As an example, if I have the less-than binary expression `fizz < buzz`, I cannot call:

    var newOperatorToken = SyntaxFactory.Token(SyntaxKind.LessThanEqualsToken);
    var newExpression = expression.WithOperatorToken(newOperatorToken);

to get `fizz <= buzz` because `Update()` is called internally with the `LessThanExpression` kind, rather than `LessThanEqualsExpression` kind, which is incompatible with the less-than-or-equals operator.

These methods should probably work the same way since they have the same name.  This means that either the C# version should not allow us to change the expression kind by changing the operator token, or that the Visual Basic version should allow us to, and they both should update the expression kind when the operator is changed.

### Warning: These links may hang your browser

This is the code for the [C# method](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs#48958).

This is the code for the [Visual Basic method](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.VisualBasic/Syntax.xml.Generated.vb#28386).

**Comment by gafter** [comment]
This is the intended behavior of these. If you need a new node with a different kind, you need to construct it with the desired kind. These methods are intended to allow you to replace the token for the purpose of changing the attached trivia.

The syntax trees are not supposed to enforce the syntax of the language. That is the purpose of the parser. It is not a problem that the VB syntax nodes are more strict in not allowing you to produce inconsistent trees.
