### ISSUE TITLE
Build fails with empty error list but shows error CS8805 at the CLI

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52190]
**Version Used**: 16.10.P1

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

```cs
using System;

Console.WriteLine("Hello world");
```

![image](https://user-images.githubusercontent.com/8040367/112725938-25f4e100-8ef1-11eb-80fa-1f52000c11f1.png)

`dotnet build`:

> CSC : error CS8805: Program using top-level statements must be an executable.

**Comment by Youssef1313** [comment]
I couldn't reproduce in 16.9 (haven't tried 16.10)

**Comment by jnm2** [comment]
I can't repro today in either 16.9 or 16.10. Guess this can't be actionable.
