### ISSUE TITLE
Conversion completion: Null conditional access leaves ? behind

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#52215]
**Version Used**: 
Main at cb6cf9c7

**Steps to Reproduce**:

Example derived from `Theory` `ExplicitUserDefinedConversionIsAppliedForDifferentExpressions` https://github.com/dotnet/roslyn/blob/f52afd963b21a472d78d5fe17fec8e65fbd10f74/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ConversionCompletionProviderTests.cs#L433
```CS
namespace N
{
    public class Black
    {
        public White White { get; }
        public static explicit operator White(Black _) => new White();
    }
    public class White
    {
        public Black Black { get; }
        public static explicit operator Black(White _) => new Black();
    }
    
    public class Program
    {
        public static void Main()
        {
            var white = new White();
            white?.Bl$$;
        }
    }
}
```
**Expected Behavior**:
Conversion completion removes the conditional access
```CS
((Black)white)$$
```
or the conditional access stays:
```CS
((Black)white)?.$$
```

**Actual Behavior**:
The dot is removed, but the question mark is not.
```CS
((Black)white)?$$
```

**Further hints**

The actual behavior is right for indexer:
```CS
  c?.$$ // becomes
  c?[$$]
```

Operator handling is also fine (removes `?.`).
```CS
  c?.$$ // becomes
  c + $$
```

/CC @CyrusNajmabadi

**Comment by MaStr11** [comment]
Understood. But what about leaving the question mark and the dot? That way the completion would be more consistent and less surprising (It was at least surprising to me).

**Comment by CyrusNajmabadi** [comment]
> Understood. But what about leaving the question mark and the dot?

I tried that and didn't like it.  Because the point of the dot wasn't for the dot itself, it was for inserting the conversion.  once the conversion is inserted, then i want to take the next step with that casted/converted item.  So i can do whatever i need there (invoke, operation, etc.) including dotting again *if* sensible :)

**Comment by MaStr11** [comment]
Closed as *By design*.
