### ISSUE TITLE
Improve Preview Changes experience

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5222]
The Visual Studio 2015 implementation of the Preview Changes dialog is mostly a recreation of the experience from Visual Studio 2013. Should we consider improving upon this experience? Some possibilities:
1. Integrate a proper diff view
2. Construct a broader preview experience that allows navigation, find refs, etc.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is far out of the scope of responsibility for Roslyn.  Editor/Platform can decide if htey want to invest in such a space, and determine what that means for individual languages.
