### ISSUE TITLE
Allow parameterless constructors in record structs

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52240]
[This issue is referenced in source]

When the "record structs" feature gets merged with the "parameterless struct constructor" feature, we may need to make some adjustments to record structs.

Some scenarios are interesting:
```
record struct S1(); // is this allowed?
```
```
_ = new S2(); // what is executed?
record struct S2(int I)
{
   int Field = M(I);
   static int M(int i) => i;
}
```
```
record struct S3
{
  int Field = 3; // is this allowed?
}
```
```
record struct S4()
{
  int Field = 3; // is this allowed?
}
```

**Comment by SteveDunn** [comment]
Hi - is this in .NET 6 preview 6?

**Comment by jcouv** [comment]
No, it barely missed .NET 6 preview 7. It'll be in the following preview.

**Comment by SteveDunn** [comment]
I'm ideally looking for the succinctness of records, the memory traits of value-type primitives, and constraits that mean no invalid types can be created.  https://dunnhq.com/posts/2021/primitive-obsession/

**Comment by jcouv** [comment]
Update: it did make it into .NET 6 preview 7 after all (and VS 2022 preview 3).
