### ISSUE TITLE
Formatting Bug for Simplify LINQ Expression

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#52283]
**Version Used**: 
Visual Studio 2019 16.10 Preview 1

Selecting the `Simplify LINQ expression` code fix: 
![image](https://user-images.githubusercontent.com/46729679/113081251-2ad5c100-918d-11eb-9244-49c8f32b9998.png)

Currently doesn't apply proper formatting: 
![image](https://user-images.githubusercontent.com/46729679/113081106-e9ddac80-918c-11eb-97e1-d959a5e7d293.png)

**Comment by jmarolf** [comment]
related to https://github.com/dotnet/roslyn/issues/53464
