### ISSUE TITLE
Complete statement command enhancement

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52299]
I think the most annoying behavior for this command (which I personally don't actually hit :smile:) is when typing a semicolon by mistake. I think the command shouldn't do its work if the statement already ends in a semicolon, in which case, it's more likely the user typed a semicolon by mistake. It'll be less distractive if the semicolon was typed where the cursor is, so the user simply press backspace and type whatever character he meant.

cc: @davidwengier since I believe this command was annoying you.

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by Youssef1313** [comment]
Actually, this looks like the above was the intended design, there is a private method for checking the existence of semicolon:

https://github.com/dotnet/roslyn/blob/b586d049478f1ce96355a091ad82863ca83a8ac9/src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs#L357

But it's not used.

**Comment by sharwell** [comment]
I would certainly not object if someone modified the behavior to overtype an existing semicolon that already exists at the target location...
