### ISSUE TITLE
Simplify new expression (IDE0090) inappropriately raised for ASP.NET MVC 6 project.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52301]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Simplify-new-expression-IDE0090-inappr/1385846)._

---
[regression]
Issues such as IDE0090: 'new' expression can be simplified are inappropriately raised because C# 9 isn't supported by .NET Frameworks projects.

---
#### Feedback Bot on 3/30/2021, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
The analyzer already handles the language version:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Analyzers/CSharp/Analyzers/UseImplicitObjectCreation/CSharpUseImplicitObjectCreationDiagnosticAnalyzer.cs#L42-L44

Not sure what the issue is.

**Comment by ryzngard** [comment]
Unsure. It could be that the langversion is set to 9 but full framework doesn't support 'new()'. I didn't think it was framework dependent though...

**Comment by CyrusNajmabadi** [comment]
What error is the user actually seeing?

**Comment by ryzngard** [comment]
`Issues such as IDE0090: 'new' expression can be simplified are inappropriately raised because C# 9 isn't supported by .NET Frameworks projects`

Which could indicate that user does not expect new() to work. Probably worth clarifying in the original issue in case the user doesn't use GitHub

**Comment by CyrusNajmabadi** [comment]
Yeah, this doesn't really make sense.  Closing out for now absent more data and esp. as we haven't heard anything else on this.
