### ISSUE TITLE
IDE0066 code fix should support unconditional preprocessor directives

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#52307]
Currently, the code fix for IDE0066 does not support any scenario where a switch statement includes preprocessor directives. This should be expanded in two ways:

1. The code fix should work in the presence of _unconditional_ preprocessor directives (e.g. `#pragma warning`)
2. The code fix should work in the presence of _conditional_ preprocessor directives (e.g. `#if`, `#else`) provided the region established by the directive starts before the `switch` keyword and ends after the final `}` token
3. (harder) The code fix should work in the presence of _conditional_ preprocessor directives for any case where there is no _disabled_ region between the `switch` keyword and the final `}` token

This is a polishing follow-up for #52303

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
