### ISSUE TITLE
[Expression Evaluator] C# FunctionResolver resolves async methods to async kickoff method, which does not have debug info.

### ISSUE THREAD

**Issue by chuckries** [dotnet/roslyn#52313]
**Version Used**: 
```
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.10.0 Preview 2.0 [31131.29.main]
```

**Steps to Reproduce**:

1. Create a new C# console app with the following code
```
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!"); // bp here
            await DoSomethingAsync();
        }

        static async Task DoSomethingAsync()
        {
            await Task.Delay(100);
        }
```
2. Set a breakpoint on the commented line and F5
3. When you hit the breakpoint, open the Debugger Breakpoints Window (Debug -> Windows -> Breakpoints)
4. From breakpoints window, New -> Function Breakpoint
5. Type "DoSomethingAsync" and click Ok
6. The function breakpoint should bind, F5 to continue the process
7. Debugger stops on function bp.

**Expected Behavior**:
The source file for the async method is shown

**Actual Behavior**:
"Source Not Available" page is shown.

**Root Cause** 
The issue here is that roslyn's FunctionResolver correctly resolves the name directly to the async kickoff method of the same name and returns the corresponding DkmClrInstructionAddress. This is not, however, the location where we actually want to stop for async methods. The async kickoff method has no debug info associated with in the pdb/metadata, and the debugger cannot display a source file for it. 

When setting a file/line breakpoint on the beginning of an async method, the location is resolved to an instruction address within the MoveNext method of the async state machine. Ideally, the FunctionResolver would resolve the name to this same location. **It should not resolve to IL offset 0 of the MoveNext method, otherwise this function bp would be hit every time the async method is resumed.** It should be resolved to the IL offset of the first instruction of the first branch of the MoveNext method.

**Comment by chuckries** [comment]
cc @gregg-miskelly @tmat @plnelson @cston

**Comment by r-ramesh** [comment]
This issue has been fixed on the debugger side with https://devdiv.visualstudio.com/DevDiv/_git/Concord/pullrequest/394606 .

@jinujoseph This issue can be closed.
