### ISSUE TITLE
CompletionItem.IsComplexTextEdit does not return true for import completion

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#52331]
The description of `IsComplexTextEdit` says that it should return true for items that have perf-impacting resolutions. I would expect import completions to fall into this category due to the need to calculate imports, but currently that property is only set for `MemberInsertingCompletionItem`s, aka override and partial completion.

**Comment by CyrusNajmabadi** [comment]
Import addition does'nt have perf affecting resolution.  All it needs was computed during creation of the item.  Overrive/PArtial completion is more expensive as it has to do a lot of complex work at the time of insertion. :)

**Comment by 333fred** [comment]
I'll be honest, I'm not buying that. There's a _lot_ of logic in `GetChangeAsync` for import completion:

https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractImportCompletionProvider.cs#L112-L209

**Comment by 333fred** [comment]
To be clear, I'm hoping to use this property as the heuristic for doing async completion in O# (which we had previously discussed). But as it doesn't return true for import completion, I can't rely on just the flag.

**Comment by CyrusNajmabadi** [comment]
You can check if there are multiple text changes in the item.  If so, do the async completion :)

         -- Cyrus

**Comment by 333fred** [comment]
> You can check if there are multiple text changes in the item.

In order to do that, I need to resolve the completion item. That's what I'm trying to avoid.
