### ISSUE TITLE
Ban GetTypeByMetadataName and use a caching mechanism

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52334]
See https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/WellKnownTypeProvider.cs. I believe this can improve the performance significantly. Also even consider make it a public API so analyzer authors don't have to implement their own caching mechanism.

@sharwell for thoughts.

**Comment by sharwell** [comment]
> I believe this can improve the performance significantly.

I haven't seen evidence that this would produce a meaningful _performance_ improvement. The main advantage for moving to a new API is addressing the semantics problems (#43341, #52118, #32280, #52037, ...).

**Comment by Youssef1313** [comment]
> Internally, GetTypeByMetadataName already uses caches.

Wasn't aware it already does caching.

---

> The additional caching in other approaches is just a necessary side effect of the change in semantics.

I don't quite understand this nor understand why roslyn-analyzers repo does its own caching. But since this isn't actually a product issue, I'm going to close.
