### ISSUE TITLE
Major duplication of loc strings

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#52343]
I'm not sure when it happened, but a ton of our loc strings are now duplicated.  For example:

```
  <data name="Prefer_coalesce_expression" xml:space="preserve">
    <value>Prefer coalesce expression</value>
  </data>
```

Exists now both in EditorFeatures and VSServices.  

This is majorly confusing and a maintenance nightmare.  We need to unify all these strings.

**Comment by CyrusNajmabadi** [comment]
@jmarolf This seems to have been introduced with https://github.com/dotnet/roslyn/commit/faf7c13acd548e6b9fc913f2349c3c07030cb113.  Can you please take a look and remove the duplication?

**Comment by CyrusNajmabadi** [comment]
@jmarolf can we get eyes on this.  This is affecting contributers and leading to problems like loc-string drift.  We need to eliminate the dupes here.

**Comment by jmarolf** [comment]
yep on my list to take care of this week

**Comment by CyrusNajmabadi** [comment]
@jmarolf Can you please address this soon.
