### ISSUE TITLE
16.10 API Review feedback

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#52353]
* [ ] @jasonmalinowski will investigate just using `Tags` instead of `CustomTags` in `CodeAction`
* [x] @CyrusNajmabadi will make `IPersistentStorageService.GetStorageAsync`'s `CancellationToken` optional, to fit our general API pattern. https://github.com/dotnet/roslyn/pull/52426
* [x] @sharwell will make `OptionSet`'s constructor protected (https://github.com/dotnet/roslyn/pull/52359). https://github.com/dotnet/roslyn-analyzers/issues/4991 has been filed for the public api analyzer bug here.

**Comment by jasonmalinowski** [comment]
@JoeRobich is doing the last bit now.

**Comment by JoeRobich** [comment]
https://github.com/dotnet/roslyn/pull/52879 is open for using `Tags` instead of `CustomTags`

**Comment by JoeRobich** [comment]
Scratch that earlier PR. https://github.com/dotnet/roslyn/pull/53008 is going to make CustomTags internal for 16.10.

**Comment by Youssef1313** [comment]
@333fred Is everything here fixed now?

#53008 has made CustomTags internal.

**Comment by 333fred** [comment]
@JoeRobich anything else that needs following up on? If not, this can be closed out.

**Comment by JoeRobich** [comment]
Nope, we've resolved the issue. Let us close this out.
