### ISSUE TITLE
'Add null check' should import the System namespace

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52383]
**Version Used**: 16.9.3

This leads to me going back to ReSharper for this command.

```cs
class C
{
    void M(string [||]p)
    {
    }
}
```

💡 Add null check (actual):

```cs
class C
{
    void M(string p)
    {
        if (p is null)
        {
            throw new System.ArgumentNullException(nameof(p));
        }
    }
}
```

💡 Add null check (expected):

```cs
using System;

class C
{
    void M(string p)
    {
        if (p is null)
        {
            throw new ArgumentNullException(nameof(p));
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I think it woudl be very reasonable for us to do something better here.  First, if the user has `csharp_prefer_braces=always`, we keep the current form.  However, if they do not, we should opt toward the more lightweight: `if (p is null) throw new ArgumentNullException(nameof(p));`

THere are often many of these in a row, and requiring multiple lines for such a recognizable and symettric pattern is overkill.

**Comment by CyrusNajmabadi** [comment]
Yes.  We should do this.  The user is explicitly trying to add argument checks.  So it's reasonable to pull in 'SYstem'.  This is not the same as 'NotImplementedException' where some users will immediately remove those lines and then not want System to have been added.

**Comment by AraHaan** [comment]
TBH I would have it instead be where if the user tells their editorconfig if:
- null checks should import the namespace(s) they need.
- if the null checks should fully qualify it instead (some projects expect it to always be fully qualified for some reason however).

**Comment by CyrusNajmabadi** [comment]
I think teh case of some projects not importing `System` is narrow enough that we don't need an option for it.

**Comment by Youssef1313** [comment]
Opened #52392
