### ISSUE TITLE
[Bug report] Passing in a combination of flags directly as method parameter causes PEVerify to fail

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/roslyn#5238]
I am not yet sure what the impact is of this invalid IL and if it might be PEVerify being wrong. By default I run PEVerify for all libraries created (I use Fody for this, but you can also run PEVerify manually). It seems that the libraries had errors while being verified.

To use PEVerify, use the following steps:

1. Go to *C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools*
2. Shift + right click on the directory => *Open command window here*
3. Use the following command:

```
PEverify “[path to assembly]”
```

## Problem description

To reproduce, use the following steps:
1. Create a new blank universal windows store app
2. Add this method to *MainPage.xaml.cs*

```
public void InvalidIlMethod()
{
    var field = typeof(MainPage).GetField("_testingField", BindingFlags.Instance | BindingFlags.Public);
}
```

3. When verifying the generated IL by the compiler, this error shows up:

```
[IL]: Error: [C:\Source\Research\UniversalBindingFlags\UniversalBindingFlags\bin\Debug\UniversalBindingFlags.dll: BindingFlagsPoC.MainPage::InvalidIlMethod][offset 0x00000012] Unable to resolve token.
```

## Possible workaround

To fix this, replace the generated method by this one:

```
public void ValidIlMethod()
{
    var bindingFlags = BindingFlags.Instance | BindingFlags.Public;
    var field = typeof(MainPage).GetField("_testingField", bindingFlags);
}
```

Now PEVerify will correctly verify the assembly.

**Comment by AlekseyTs** [comment]
@GeertvanHorrik I am not able to reproduce the PEVerify error. Could you post IL for InvalidIlMethod and ValidIlMethod methods?

**Comment by GeertvanHorrik** [comment]
I can't repro at the moment. The only thing I updated recently was "Tools for UAP" in VS2015.

**Comment by GeertvanHorrik** [comment]
Pfew, I can reproduce in a class library (Universal App Platform) using AnyCPU. Here is the IL:

```
.method public hidebysig instance void InvalidIlMethod() cil managed
{
    .maxstack 3
    .locals init (
        [0] class [System.Reflection]System.Reflection.FieldInfo info)
    L_0000: nop 
    L_0001: ldtoken ClassLibrary2.Class1
    L_0006: call class [System.Runtime]System.Type [System.Runtime]System.Type::GetTypeFromHandle(valuetype [System.Runtime]System.RuntimeTypeHandle)
    L_000b: ldstr "testingField"
    L_0010: ldc.i4.s 20
    L_0012: call class [System.Reflection]System.Reflection.FieldInfo [System.Reflection.TypeExtensions]System.Reflection.TypeExtensions::GetField(class [System.Runtime]System.Type, string, valuetype [System.Reflection.TypeExtensions]System.Reflection.BindingFlags)
    L_0017: stloc.0 
    L_0018: ret 
}
```

Here is the result:

![image](https://cloud.githubusercontent.com/assets/1246444/10013297/8b4339ea-6110-11e5-81ee-5b8da9ee128e.png)

**Comment by AlekseyTs** [comment]
@GeertvanHorrik Thank you. Could you also post IL for the ValidIlMethod, preferably included into the same library that fails PEVerify.

**Comment by GeertvanHorrik** [comment]
Coming up in 2 minutes!

**Comment by GeertvanHorrik** [comment]
### Valid C#

```
public void ValidIlMethod()
{
    var flags = BindingFlags.Instance | BindingFlags.Public;
    var field = typeof(Class1).GetField("testingField", flags);
}
```

### Valid IL

```
.method public hidebysig instance void ValidIlMethod() cil managed
{
    .maxstack 3
    .locals init (
        [0] valuetype [System.Reflection.TypeExtensions]System.Reflection.BindingFlags flags,
        [1] class [System.Reflection]System.Reflection.FieldInfo info)
    L_0000: nop 
    L_0001: ldc.i4.s 20
    L_0003: stloc.0 
    L_0004: ldtoken ClassLibrary2.Class1
    L_0009: call class [System.Runtime]System.Type [System.Runtime]System.Type::GetTypeFromHandle(valuetype [System.Runtime]System.RuntimeTypeHandle)
    L_000e: ldstr "testingField"
    L_0013: ldloc.0 
    L_0014: call class [System.Reflection]System.Reflection.FieldInfo [System.Reflection.TypeExtensions]System.Reflection.TypeExtensions::GetField(class [System.Runtime]System.Type, string, valuetype [System.Reflection.TypeExtensions]System.Reflection.BindingFlags)
    L_0019: stloc.1 
    L_001a: ret 
}
```

**Comment by AlekseyTs** [comment]
I do not see any difference in terms of referring to the GetField method, both methods even use the same tokens to refer to GetField. Looks like an issue with the PEVerify tool.

**Comment by AlekseyTs** [comment]
Opened https://github.com/dotnet/coreclr/issues/1674 for CoreClr.
