### ISSUE TITLE
'Add null checks for all parameters' uses IsNullOrEmpty instead of `is null`

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#52398]
**Version Used**: 16.9.3

This is inconsistent with the behavior of 'Add null check' and is not what I expect "add null checks" to mean. I often want to add argument checks on public methods to match the nullability annotations to conform to [CA1062](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062), but I can't blindly assume that it's okay to throw for empty strings.

💡 Add null checks for all parameters:

```cs
using System;

class C
{
    void M(string first, string second)
    {
        if (string.IsNullOrEmpty(first))
        {
            throw new ArgumentException($"'{nameof(first)}' cannot be null or empty.", nameof(first));
        }

        if (string.IsNullOrEmpty(second))
        {
            throw new ArgumentException($"'{nameof(second)}' cannot be null or empty.", nameof(second));
        }
    }
}
```

Expected: `first is null`, `second is null`

**Comment by Youssef1313** [comment]
This appears to be intentional:

https://github.com/dotnet/roslyn/blob/150ee54a4df9c4bc5312e359c60e466c8d7eabb9/src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs#L147-L156

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/20986#issuecomment-507889583 for reference.

**Comment by jnm2** [comment]
Thanks for that context. I don't think it changes this:

> I can't blindly assume that it's okay to throw for empty strings.

The net result of not having a choice in the matter is that I go to ReSharper's equivalent which does what I expect and doesn't require cleanup afterwards.

**Comment by CyrusNajmabadi** [comment]
It's both an explicit design decisino, but also not super great.  In the case of strings, we could just consider doing this:

```
add null check
add null or empty check
add null or whitespace check
```

In the case of multiple string arguments we could have:

```
For this argument
  add null check
  add null or empty check
  add null or whitespace check
For all string arguments
  add null check
  add null or empty check
  add null or whitespace check
```

And if you start on a non-string, then we just add a null check.  It's what you asked for, and it does seem reasonable.

**Comment by Youssef1313** [comment]
@jinujoseph I believe that @CyrusNajmabadi comment above is suggesting an enhancement to this refactoring, which needs to be addressed. Should this be reopened?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  This is one of those cases where we don't want to overload with knobs, but where any default choice may not align with some customers' needs.  Given no other reports, going ot close out.
