### ISSUE TITLE
IDE0078 refactoring "loses" a variable

### ISSUE THREAD

**Issue by medo64** [dotnet/roslyn#52397]
**Version Used**: 

Microsoft Visual Studio Community 2019 Version 16.9.3

**Steps to Reproduce**:

1. Create project with a class inhering another class

2. In subclassed code, create 'if' referring to local variable/property and one from the base class, e.g.:

    if ((CipherMode == CipherMode.CBC) && (IV != null)) {
        return;
    }

3. Use quick action for 'Use pattern matching'

**Expected Behavior**:

    if ((CipherMode is CipherMode.CBC) && (IV is not null)) {
        return;
    }

**Actual Behavior**:

    if (IV is CipherMode.CBC and not null) {
        return;
    }

This is not an equivalent refactoring as local variable/property is not even checked and inherited property is used for both comparisons.

Example project attached.
[TestCS0078.zip](https://github.com/dotnet/roslyn/files/6253152/TestCS0078.zip)

**Comment by Youssef1313** [comment]
cc: @alrz @CyrusNajmabadi

**Comment by MaStr11** [comment]
The issue is not caused by inheritance. Minimal repo is:

```CS
using System;

public class C
{
    public int I { get; }
    
    // Property must be of a any reference type except 'object'
    // to trigger UsePatternCombinatorsDiagnosticId (CSharpUsePatternCombinatorsDiagnosticAnalyzer)
    public EventArgs Property { get; } 

    public void M()
    {
        // Null check must follow the first condition, otherwise UsePatternCombinators is not triggered
        if (I == 1 && Property != null)
        {
        }
    }
}
```
