### ISSUE TITLE
Error List and code squiggles do not honor project's `WarningsAsErrors=nullable` setting

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52407]
Repro:
- create a C# project and add `<WarningsAsErrors>nullable</WarningsAsErrors>`
- put some code with a nullable diagnostic (such as `#nullable enable` followed by `string s = null;`)
- build the project: the Output window correctly shows an error
- the Error List only shows a warning, but we'd expect an error 

![image](https://user-images.githubusercontent.com/12466233/113498435-c59e0a80-94c1-11eb-9a3d-a2e60fc750b0.png)
![image](https://user-images.githubusercontent.com/12466233/113498451-d6e71700-94c1-11eb-98ac-2734e2c5e7d8.png)
![image](https://user-images.githubusercontent.com/12466233/113498460-e5cdc980-94c1-11eb-9ab6-cc2ce8b1159d.png)

**Comment by Youssef1313** [comment]
This looks very relevant to me:

https://github.com/dotnet/roslyn/blob/1cca63b5d8ea170f8d8e88e1574aa3ebe354c23b/src/VisualStudio/CSharp/Impl/ProjectSystemShim/CSharpProjectShim.OptionsProcessor.cs#L103-L107

`ParseWarningCodes` knows nothing about "nullable". It assumes that values in `WarningsAsErrors` are only diagnostic IDs.

**Comment by jcouv** [comment]
@Youssef1313 Thanks for the pointers.
`ParseWarningCodes` passes values it doesn't understand through, so it should work with "nullable".
When I add `Debugger.Launch()` to `ComputeCompilationOptionsWithHostValues` (in `CSharpProjectShim.OptionsProcessor.cs`) it doesn't seem to get hit by my local repro.

That said, there is indeed a problem with `CompilationOptions.SpecificDiagnosticOptions` (it should understand diagnostic ID "nullable" but doesn't). Filed https://github.com/dotnet/roslyn/issues/52414
But fixing that compiler API doesn't seem to fix the IDE behavior in my local test.

One more observation: `<WarningsAsErrors>8600</WarningsAsErrors>` produces one red squiggle as expected, but `<WarningsAsErrors>8600,nullable</WarningsAsErrors>` produces none (only warnings).

**Comment by RikkiGibson** [comment]
I believe there exists a GitHub issue already for the bug where passing the diagnostic ID `"nullable"` via certain compilation APIs doesn't expand into the whole set of nullable diagnostics as expected. @mavasani gave us a detailed description at the time of where the fix should be made. I can't seem to find that issue now.

> Even stranger, `<WarningsAsErrors>1,nullable,2</WarningsAsErrors>` produces 2 red squiggles as expected.

Could be an instance of #38371.

**Comment by Youssef1313** [comment]
Thanks @jcouv @RikkiGibson. I'm interested to fix that if @mavasani still remembers where was the issue. I wasn't able to figure that out.

**Comment by mavasani** [comment]
@Youssef1313 please see https://github.com/dotnet/roslyn/issues/49392#issuecomment-729663008

**Comment by Youssef1313** [comment]
@mavasani Thanks for the pointer. Wondering why this is not an issue when the error number is used?

https://github.com/dotnet/roslyn/blob/a163778013dba0ad5efb32df5374584b0795b53a/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L2000

When the given id is parsable as a number, it's converted to "CSxxxx". But this logic exists in CSharpCommandLineParser.

However, the IDE error list correctly shows it as an error if I used `<WarningsAsErrors>8600</WarningsAsErrors>`

![image](https://user-images.githubusercontent.com/31348972/113606517-6a4a5480-9648-11eb-984d-845c134fbce5.png)

![image](https://user-images.githubusercontent.com/31348972/113606550-759d8000-9648-11eb-97a6-e0a7ed7d706a.png)

**Comment by mavasani** [comment]
@Youssef1313 The core issue here is that the special value `nullable` for `WarningsAsErrors` is not correct mapped to IDs that need escalating from warning to error. Using individual ID (with or without CS prefix) in the `WarningsAsErrors` will always work.

**Comment by Youssef1313** [comment]
In that case, why the following is needed?

https://github.com/dotnet/roslyn/blob/a163778013dba0ad5efb32df5374584b0795b53a/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L2000

**Comment by jcouv** [comment]
@mavasani I didn't understand the proposed explanation. How do we explain why `<WarningsAsErrors>1,nullable,2</WarningsAsErrors>` works, but `<WarningsAsErrors>nullable</WarningsAsErrors>` does not?

**Comment by Youssef1313** [comment]
My attempt in #52420 didn't work.

**Comment by RikkiGibson** [comment]
> @mavasani I didn't understand the proposed explanation. How do we explain why `<WarningsAsErrors>1,nullable,2</WarningsAsErrors>` works, but `<WarningsAsErrors>nullable</WarningsAsErrors>` does not?

This specific behavior is likely explained by #38371, *but* there is also a separate issue which makes it so the diagnostic ID `nullable` doesn't get expanded into the full set of nullable diagnostics via all the APIs which allow you to give a custom severity for a diagnostic in a compilation.

**Comment by jcouv** [comment]
Debugged the issue with @RikkiGibson and confirmed this is a symptom of https://github.com/dotnet/roslyn/issues/38371.
When `ProjectOptionsProcessor.SetCommandLine` is called with the new command-line arguments to pass to the compiler, the order of arguments seems shuffled. Any minor change to the diagnostics listed in `WarningsAsErrors` will affect it.
The order matters because there is a `warnaserror-` and then `warnaserror+:....`. Depending which comes first, the compiler produces different diagnostics.


```
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectOptionsProcessor.SetCommandLine(System.Collections.Immutable.ImmutableArray<string> arguments) Line 111	C#
 	Microsoft.VisualStudio.LanguageServices.Implementation.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.SetOptions(System.Collections.Immutable.ImmutableArray<string> arguments) Line 147	C#
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.ApplyChangesToWorkspaceContext.ProcessOptions(Microsoft.VisualStudio.ProjectSystem.Properties.IProjectRuleSnapshot snapshot)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.ApplyChangesToWorkspaceContext.ApplyProjectBuildAsync(Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate> update, Microsoft.VisualStudio.ProjectSystem.LanguageServices.ContextState state, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.ApplyProjectChangesUnderLockAsync(Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject project, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate subscription)> update, bool evaluation, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.OnProjectChangedAsync.AnonymousMethod__0(System.Threading.CancellationToken ct)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob<Microsoft.VisualStudio.Threading.EmptyStruct>(System.Func<System.Threading.Tasks.Task> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTask job)	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(System.Func<System.Threading.Tasks.Task> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions, System.Delegate entrypointOverride)	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.ReentrantSemaphore.ExecuteCoreAsync(System.Func<System.Threading.Tasks.Task> semaphoreUser)	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(System.Func<System.Threading.Tasks.Task> operation, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task> action, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.OnProjectChangedAsync(Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject project, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate subscription)> update, bool evaluation)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Managed.dll!Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.InitializeCoreAsync.AnonymousMethod__15_1(Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)> e)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimAsync<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)>>.ProcessInputAsync(Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)> input)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)>>.ProcessInputQueueAsync(Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)>>.InputDataBuffer inputQueue)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim<Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<(Microsoft.VisualStudio.ProjectSystem.ConfiguredProject, Microsoft.VisualStudio.ProjectSystem.IProjectSubscriptionUpdate)>>.System.Threading.Tasks.Dataflow.ITargetBlock<TInput>.OfferMessage.AnonymousMethod__2_0(object s)	Unknown
```
