### ISSUE TITLE
Move IValueTrackingService implementation to OOP

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#52435]
This tracks making the value tracking service OOP and handling any threading concerns with the service layer. 

https://github.com/dotnet/roslyn/pull/52361#discussion_r608090013

**Comment by CyrusNajmabadi** [comment]
@vatsalyaagrawal This is likely necessary for thsi feature.  Though it's not as critical as for InheritanceMargin.  The primary difference is that hte latter will run automatically, while this feature runs on demand when teh user interacts with it.  however, in its current form it will be extremely expensive in large projects, and should switch to a pure OOP model where oop does *all* the heavy work, and the only things returend back are the minimal POCO types needed to populate teh UI.
