### ISSUE TITLE
Add support for record structs in CodeLens

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52430]
We'll need something like https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d/pullrequest/279270 (from issue https://github.com/dotnet/roslyn/issues/47445) for record structs.

Relates to test plan for record structs: https://github.com/dotnet/roslyn/issues/51199

**Comment by jcouv** [comment]
@CyrusNajmabadi You'd fixed CodeLens for records (see links in OP). Do we need to do anything more along the same lines for record structs?

**Comment by CyrusNajmabadi** [comment]
I don't believe so.  The 

```
        public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
            => VisitTypeDeclaration(node);
```

case should handle record structs.

**Comment by jcouv** [comment]
Awesome. I'll go ahead and close this then.
