### ISSUE TITLE
GoToTypes does not list record types

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52460]
There was some work done to support this scenario in https://github.com/dotnet/roslyn/pull/48116 (in 16.9), but for some reason it still doesn't work in the IDE.

I have this type defined:
![image](https://user-images.githubusercontent.com/12466233/113819755-9c35e680-972e-11eb-85fa-1efbceb0e46d.png)

But GoToTypes does not list it:
![image](https://user-images.githubusercontent.com/12466233/113819702-858f8f80-972e-11eb-92dd-ce3d0790b3e9.png)

Record structs have the same problem. Tracked by test plan https://github.com/dotnet/roslyn/issues/51199

FYI @CyrusNajmabadi

**Comment by Youssef1313** [comment]
This is a known issue that suspected to need editor support.

See https://github.com/dotnet/roslyn/issues/51672

**Comment by jcouv** [comment]
Thanks!
Closing as duplicate of https://github.com/dotnet/roslyn/issues/51672
