### ISSUE TITLE
Editor config options not populated correctly for elements with special characters

### ISSUE THREAD

**Issue by captainsafia** [dotnet/roslyn#52469]
**Version Used**: 
3.10.0-3.21206.28

**Steps to Reproduce**:

1.  Create a new mvc project using `dotnet new mvc -o TestFileNames`.
2.  `rename Views/Home/Index.cshtml Views/Home/{Index}.cshtml`
3.  `rename Views/Shared/Error.cshtml Views/Shared/#Error.cshtml`
4. `dotnet build`

**Expected Behavior**:

Compilations resolves correctly and we can resolve `CompilerVisibleProperties` correctly.

**Actual Behavior**:

The correct properties aren't resolved when using `AnalyzerConfigOptions` in the generator and you get the following compiler warnings.

```
CSC : warning InvalidGlobalSectionName: Global analyzer config section name '/Users/captainsafia/Verifications/TestFilesNames/Views/Home/{Index}.cshtml' is invalid as it is not an absolute path. Section will be ignored. Section was declared in file: '/Users/captainsafia/Verifications/TestFilesNames/obj/Debug/net6.0/TestFilesNames.GeneratedMSBuildEditorConfig.editorconfig' [/Users/captainsafia/Verifications/TestFilesNames/TestFilesNames.csproj]
CSC : warning RSG002: TargetPath not specified for additional file: /Users/captainsafia/Verifications/TestFilesNames/Views/Home/{Index}.cshtml. [/Users/captainsafia/Verifications/TestFilesNames/TestFilesNames.csproj]
CSC : warning RSG002: TargetPath not specified for additional file: /Users/captainsafia/Verifications/TestFilesNames/Views/Shared/#Error.cshtml. [/Users/captainsafia/Verifications/TestFilesNames/TestFilesNames.csproj]
```

The issue around the "#" in the filename is likely related to the issues around parsing characters that are considered comments in the editor config.

The issue with the "{" and "}" characters seems strange though. I haven't been able to find anything related to it in the issues.

Is there a workaround that can be employed in the meantime?

**Comment by Youssef1313** [comment]
@sharwell Might be related to the breaking change you were proposing.

**Comment by Youssef1313** [comment]
Actually it might be simpler. The issue in `TestFileNames.GeneratedMSBuildEditorConfig.editorconfig` is that those braces and hash needs to be escaped with a `\`.

I tried on a simple console app something like:


```ini
[\{Program\}.cs]

dotnet_diagnostic.IDE0055.severity = error
```

and it works.

**Comment by Youssef1313** [comment]
It's a combination of both my comments. The path is involved in two places:

- Section matching, which would be solved by escaping the hash or braces in `GenerateMSBuildEditorConfig.cs`.
- Property matching, which cannot be solved without the breaking change @sharwell was suggesting (#51625).

Or to be more accurate, the curly brace issue might get resolved by only fixing section matching. However, the `#` will require the breaking change.

Here is a part of the generated editorconfig:


```ini
[D:/dotnet/issue-52469/TestFileNames/Views/Home/{Index}.cshtml] ###The braces here needs to be escaped.
build_metadata.AdditionalFiles.TargetPath = Views\Home\{Index}.cshtml 
build_metadata.AdditionalFiles.GeneratedOutputFullPath = D:\dotnet\issue-52469\TestFileNames\obj\Debug\net6.0\Razor\Views\Home\{Index}.cshtml.g.cs ###The braces here doesn't require anything (most likely)
build_metadata.AdditionalFiles.GeneratedDeclarationFullPath = 
build_metadata.AdditionalFiles.CssScope = 

[D:/dotnet/issue-52469/TestFileNames/Views/Shared/#Error.cshtml] ###The hash here should have been escaped.
build_metadata.AdditionalFiles.TargetPath = Views\Shared\#Error.cshtml
build_metadata.AdditionalFiles.GeneratedOutputFullPath = D:\dotnet\issue-52469\TestFileNames\obj\Debug\net6.0\Razor\Views\Shared\#Error.cshtml.g.cs ###The hash here will be considered a comment. This requires the breaking change to be fixed.
build_metadata.AdditionalFiles.GeneratedDeclarationFullPath = 
build_metadata.AdditionalFiles.CssScope = 
```

**Comment by captainsafia** [comment]
Thanks for chiming in, @Youssef1313! I'd come to the same conclusion and was tinkering with making some workarounds to get around this in the Razor source generator.

With regard to the strings in the section matching, I wasn't able to get to a sensible workaround for this.

I was able to put in some workaround to encode the properties that are passed in. I implemented a new `EncodeRazorInputItems` task that took the contents of `_RazorAdditionalFiles` and encoded them. I tried two different methods:

- Encoding the values as base64 strings
- Escaping the values using `Regex.Escape`

Doing this resolves the "TargetPath not specified for additional file" which means that it was able to correctly resolve the property from `AnalyzerConfigOptions`. But then I ran into the following warning:

```
CSC : warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName of the added source file must be unique within a generator. (Parameter 'hintName')' [/Users/captainsafia/Verifications/TestFilesNames/TestFilesNames.csproj]
```

In the Razor source generator, we derive the `hintName` for generated source texts from the `AdditionalFiles.TargetPath` property. But there's no duplicate values in the editor config and our transformation is pretty straightforward.

After digging into this further, I observed some strangeness with the way `AnalyzerConfigOptions` seems to behave when values are encoded this way.

Let's say we have an app structure that looks like this:

```
├── Views
│   ├── #Shared
│   │   ├── Error.cshtml
│   │   ├── _Layout.cshtml
│   │   └── _ValidationScriptsPartial.cshtml
│   ├── Home
│   │   ├── Index.cshtml
│   │   └── Privacy.cshtml
│   ├── _ViewImports.cshtml
│   └── _ViewStart.cshtml
├── appsettings.Development.jso
```

And an MSBuild task that encodes the `TargetPath` value using:

```chsarp
var targetPath = Convert.ToBase64String(Encoding.ASCII.GetBytes(input.GetMetadata("TargetPath")));
```

Debugging into the code that uses `AnalyzerConfigOptions` with the above changes I'm observing the following.

`context.AdditionalFiles` seems to have the correct set of `AdditionalFiles`.

![image](https://user-images.githubusercontent.com/1857993/114066755-ea430b00-9850-11eb-845d-06da45abcff2.png)

It resolves the `TargetPath` for the `Error.cshtml` file:

![image](https://user-images.githubusercontent.com/1857993/114071197-b7e7dc80-9855-11eb-9867-06023c888f3b.png)

But then it resolves the same value for the `Layout.cshtml` file:

![image](https://user-images.githubusercontent.com/1857993/114071323-d6e66e80-9855-11eb-8173-40aeb8b0c35b.png)

And all the other `AdditionalFiles` under the `#Shared` directory. However, the correct values are resolved for the other `AdditionalFiles`.

![image](https://user-images.githubusercontent.com/1857993/114071503-0ac19400-9856-11eb-9ab2-f1918ed20c75.png)

I suspect that this is probably related to the section parsing issue mentioned above. However, I don't see a sensible way to get around that.

* I tried encoding the `ItemSpec` but it looks like MSBuild decodes it before it gets written to the .editorconfig.
* I tried base64-encoding the `ItemSpec` but that's not a viable option because it really borks things up.

Are there any other workarounds to this issue? It seems like the bug where sections in the editorconfig file are totally borked if there is a special issue is a bigger problem than needing to encode individual properties.

**Comment by jaredpar** [comment]
@captainsafia did the PR completely fix this issue? If so can I close it out?

**Comment by captainsafia** [comment]
@jaredpar It addressed the issue around special characters in section names. Shenanigans still ensue if special characters are used in property values but that's tracked in plenty of other issues.

As a heads up, the workaround we've employed in the Razor source generator for that is encoding the values before they are written to the editor config file then decoding them inside the Razor source generator.

But yes, this can be closed now.
