### ISSUE TITLE
Quick Info doesn't display newly written XML comments

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#5246]
1. Create new C# -> Console Application 
2. Add an XML comment to Main
3. Refer to Main within Main
4. Hover over Main

Expected: For the XML comment to be displayed
Actual: No text is displayed

I can repro this across references between classes - it doesn't need to be reference in the same class. 

![image](https://cloud.githubusercontent.com/assets/1103906/9885028/ee3495d6-5b97-11e5-911d-718ea15b7074.png)

Close Program.cs and reopen shows the correct info:

![image](https://cloud.githubusercontent.com/assets/1103906/9885113/5e7c75c0-5b98-11e5-8939-c48ceddd8a5c.png)

**Comment by Pilchie** [comment]
This is because we treat edits to comments as "non-important" and we don't build a new `Compilation` in that case.

**Comment by CyrusNajmabadi** [comment]
This doesn' repro anymore.  We def no longer have hte concept of "This is because we treat edits to comments as "non-important" "
