### ISSUE TITLE
Null ref exception in `DocumentEditor.GetChangedDocument`

### ISSUE THREAD

**Issue by lsoft** [dotnet/roslyn#52463]
**Version Used**: 
3.8  (I can't use newer version since I target to VS 16.8)

**Steps to Reproduce**:

I have an VSIX that performs a massive changes in the documents. Sometimes I noticed the following error:

![изображение](https://user-images.githubusercontent.com/5988558/113886153-1dda5280-97c9-11eb-958c-fa71f89ad811.png)

Unfortunately I have nothing to add more, because I don't know how to investigate it further.

**Expected Behavior**:

Do not fail? Fail with meaningful message?

**Actual Behavior**:

Null ref exception.

**Comment by CyrusNajmabadi** [comment]
I don't see how we could not fall here. The best write message we could give would be: you're trying to insert a nodes before a node that does not exist.

**Comment by lsoft** [comment]
@CyrusNajmabadi  in that case should DocumentEditor fail at `Insert*` method?

**Comment by lsoft** [comment]
oh I've attached a wrong image :) I had another image where document editor fails in `GetChangedDocument`. I close it until I get that error again.
