### ISSUE TITLE
Lock ordering deadlock in TableDataSource

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#52478]
🔗 This is the root cause of [AB#1296045](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1296045)

The following code takes two locks in order:

https://github.com/dotnet/roslyn/blob/275f4c790945c73ca308716ba56c224a95e13ca9/src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableDataSource.cs#L200-L205

https://github.com/dotnet/roslyn/blob/275f4c790945c73ca308716ba56c224a95e13ca9/src/VisualStudio/Core/Def/Implementation/TableDataSource/TableEntriesFactory.cs#L84

The following code takes the same two locks in opposite order:

https://github.com/dotnet/roslyn/blob/275f4c790945c73ca308716ba56c224a95e13ca9/src/VisualStudio/Core/Def/Implementation/TableDataSource/TableEntriesFactory.cs#L48-L56

https://github.com/dotnet/roslyn/blob/275f4c790945c73ca308716ba56c224a95e13ca9/src/VisualStudio/Core/Def/Implementation/TableDataSource/AbstractTableDataSource.cs#L295

**Comment by lindexi** [comment]
See https://developercommunity.visualstudio.com/t/VisualStudio-no-response-when-debugging/1377004

**Comment by CyrusNajmabadi** [comment]
@heejaechang Do you have any idea what the right thing is to do here.  I'm afraid i don't know much about how the table-data-source is structured.

**Comment by CyrusNajmabadi** [comment]
Will be addressed once we move to pull diagnostics.

**Comment by CyrusNajmabadi** [comment]
Closing as these types were removed.
