### ISSUE TITLE
Visual Studio is Busy: Navigation Bars

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52482]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-is-Busy:-Navigation-Bars/1380705)._

---
[regression] [worked-in:16.9]
Visual studio is locked and will not unlock, despite there being a "Cancel" button.  Pressing the cancel does nothing.  So I guess that makes that two bugs in one. :P

![](https://i.imgur.com/Y4swUbM.png)

---
#### Feedback Bot on 3/24/2021, 08:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/5/2021, 09:35 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This bug is occurring because the following line fails to use the cancellation token provided as an argument:
https://github.com/dotnet/roslyn/blob/98530991561773ac1fbc2c511f40eab211a11790/src/EditorFeatures/Core/Implementation/NavigationBar/NavigationBarController.cs#L398

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski this is, afaict, just how nav bars work.  It has a 'i will synchronously block' aspect to its design.  My personal preference is that it never has this and should be async through and through.  But i don't know enough about how this all works to feel confident to make that change.  @jasonmalinowski  do you believe it needs to work this way?

**Comment by CyrusNajmabadi** [comment]
> The code then deadlocks when performing a blocking wait on a task with a UI thread dependency:

Why does the model task have a UI dependency in the first place :(   None of this system makes much sense to me.  It feels like it should just be asynchronously doing everything.  And if you open the navbars we just give you whatever we have at that point.

**Comment by CyrusNajmabadi** [comment]
In the meantime, should we switch to a JTF call here to at least unblock things.

**Comment by CyrusNajmabadi** [comment]
I'll talk to @jasonmalinowski  about this tomorrow.

**Comment by sharwell** [comment]
I'm not certain a JTF wait here would resolve the issue. Let's go over the findings tomorrow.

**Comment by jasonmalinowski** [comment]
> But i don't know enough about how this all works to feel confident to make that change. @jasonmalinowski do you believe it needs to work this way?

So the handing of the "this item was selected" code is a synchronous entrypoint from the editor; it absolutely _should_ be async but that would require redoing the APIs and the editor implementation. We absolutely should do that, but it's not something we can do on just our side.

> This bug is occurring because the following line fails to use the cancellation token provided as an argument

Passing the token would have meant that if the user selected something, and then hit cancel, we'd potentially end up navigating but then the bar wouldn't end up showing the actual item as selected. The root cause is the model update should be fast; we should focus on that.

**Comment by sharwell** [comment]
> we'd potentially end up navigating but then the bar wouldn't end up showing the actual item as selected.

This would be fine, assuming it would automatically resolve the next time the caret position changed.
