### ISSUE TITLE
await is not waiting in some cases...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5248]
The call indicated below does not seem to be waiting on the result:

![capture](https://cloud.githubusercontent.com/assets/6464209/9886800/0cc05568-5ba1-11e5-8fb0-b091f482bdd5.png)

I expect the project count to be > zero.

**Comment by KevinH-MS** [comment]
More info...it may not be the waiting mechanism that's broken.  I tried assigning the ```Task<Solution>``` to a variable and calling ```Wait()``` explicitly.  That didn't work either.

Perhaps there's an Exception that's being lost in the background?

**Comment by amcasey** [comment]
I'm guessing it's not working because the language-specific workspace DLLs aren't loaded.

**Comment by amcasey** [comment]
Actually, it works on my box even without that.  Please reactivate if you're still having problems.
