### ISSUE TITLE
Display enum underlying type on mouse hover (intellisense)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52490]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Display-enum-underlying-type-on-mouse-ho/1384709)._

---
when you hover over an enum field type in a class - the intellisense popup should display the enum underlying type (eg int, uint, byte etc)
! [vs1. PNG](https://aka.ms/dc/image?name=Bc1092fb1bb544c2fa12cf40819fd466b637526463352845734_vs1.PNG&tid=c1092fb1bb544c2fa12cf40819fd466b637526463352845734)

---
#### Feedback Bot on 3/29/2021, 11:55 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by dibarbet** [comment]
Design meeting conclusion:
We would take this for the non-default cases (i.e. everything other than the case where enum extends int).
