### ISSUE TITLE
Consider C# Using Directives options when copying and pasting types and "usings" automatically added

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Consider-C-Using-Directives-options-whe/1370646)._

---
Microsoft Visual Studio Community 2019 Version 16.9.1

C# Using Directives "Separate using directive groups" option is enable.

When copying and pasting types to a new file "using" directives will now automatically get added. But without empty line between groups.

Expected:
! [image.png] (https://aka.ms/dc/image?name=Be32c8de3886f4188aae941257524e4a0637514388299026830_20210316-000027-image.png&tid=e32c8de3886f4188aae941257524e4a0637514388299026830)

Actual:
! [image.png] (https://aka.ms/dc/image?name=B97c3d0bb2a034ea7bd90b718f086c2b0637514388415774031_20210316-000039-image.png&tid=97c3d0bb2a034ea7bd90b718f086c2b0637514388415774031)

---
#### Feedback Bot on 3/15/2021, 11:56 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
@ryzngard

**Comment by ryzngard** [comment]
@mikadumont am I missing something? The expected and actual look the same to me

**Comment by anreton** [comment]
@ryzngard, yep, it's my mistake when I posted this issue.

My Using options:
![image](https://user-images.githubusercontent.com/28877846/114614995-d7479500-9cad-11eb-9d52-983e06388fae.png)

Expected result:
![image](https://user-images.githubusercontent.com/28877846/114615129-f7775400-9cad-11eb-8d06-5abff23c7f65.png)

Actual result:
![image](https://user-images.githubusercontent.com/28877846/114615158-01995280-9cae-11eb-81db-973853c1cd92.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
