### ISSUE TITLE
Improved Commenting of LINQ lines

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52496]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Improved-Commenting-of-LINQ-lines/1359761)._

---
Using VB, consider this example LINQ:

```
cvsWebSites.Source = From ws In ocWebSites
		     Join wsc In ocWebSiteCategories On ws. WebSiteID Equals wsc. WebsiteID
		     Where wsc. CategoryID = swc. CategoryID
```
When I comment out the first line, the second and third lines are not automatically commented.  They should be.

So my suggestion is that when the coder comments the first line of a multi-line LINQ statement, all of the LINQ should automatically be commented out.

---
#### Feedback Bot on 3/8/2021, 00:28 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to be investing in this area.
