### ISSUE TITLE
Collapse all top-level methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52493]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Collapse-all-top-level-methods/1389853)._

---
Given the following `Program.cs`, using top-level statements.

```csharp

Foo();
Bar();

static void Foo()
{
   // ...
}

static void Bar()
{
  // ...
}
```

It would be useful to have a shortcut to collapse all top-level methods at the same time.

`CTRL+M+O` is the shortcut I generally use, but apparently it doesn't work with these top-level methods.

---
#### Feedback Bot on 4/6/2021, 01:23 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Collapse to definitions (the shortcut already mentioned) is expected to work for this. Marking help wanted.
