### ISSUE TITLE
Renaming a parameter on a copied&pasted method renames also the parameters in the body of the original method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52497]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming-a-parameter-on-a-copiedpasted-/1366750)._

---
Say I have a class with a method I want to copy, to create a similar one but with a different parameter, for example change `someText` to an `int` called `someInteger`. When I copy and paste, I have this:

```
class MyClass
{
    /// <summary>Blah.</summary>
    /// <param name="someText">Blah.</param>
    void SomeMethod(string someText) => Console.WriteLine(someText);

/// <summary>Blah.</summary>
    /// <param name="someText">Blah.</param>
    void SomeMethod(string someText) => Console.WriteLine(someText);
}
```

If now I rename `someText` to `someInteger`, Visual Studio also renames the parameter in the body and doc comments of the first method, so I get this:

```
class MyClass
{
    /// <summary>Blah.</summary>
    /// <param name="someInteger">Blah.</param>
    void SomeMethod(string someText) => Console.WriteLine(someInteger);

/// <summary>Blah.</summary>
    /// <param name="someInteger">Blah.</param>
    void SomeMethod(string someInteger) => Console.WriteLine(someInteger);
}
```

It seems to consider those to be the same parameter on both methods regardless of scope (in fact, not only for renaming, but also when highlighting them and finding its references).

The workaround is to first change the parameter type, and only then rename it.

Not sure if it's related somehow to this: https://developercommunity.visualstudio.com/idea/595929/rename-variables-in-scope-of-current-function-para.html

---
#### Feedback Bot on 1/28/2020, 04:29 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/5/2020, 09:29 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 2/27/2020, 05:41 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/11/2021, 11:26 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by ryzngard** [comment]
Marking as needs design review. We've had a few requests where copy+paste code, then rename results in behavior the user did not want. I understand _why_ these changes are happening, but wonder if we should have a way to help mitigate them?

**Comment by CyrusNajmabadi** [comment]
Closing out as we havne't heard about this issue broadly.
