### ISSUE TITLE
Intellisense: do not auto expand new ()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52494]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense:-do-not-auto-expand-new-/1368509)._

---
Please do not auto expand the new operator after typing '(', that misses the whole point:
I want write
MyClass d = new ();
not 
MyClass d = new MyClass();

---
#### Feedback Bot on 3/14/2021, 10:56 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This is especially a problem for users who set this option:

https://github.com/dotnet/roslyn/blob/e3d735e5daadcad05fc32a1f41618defaca1ea5e/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs#L141-L146

We should avoid completing the type name as text when typing `(` if all of the following conditions are met:

1. The user is working in C# 9 or newer
2. The user has not set `csharp_style_implicit_object_creation_when_type_is_apparent` to false
3. The user has not typed any characters as part of the selected completion item
4. The selected completion item is the same item that would be inferred with target-typed new
5. The user triggers completion by one of the following commit characters: <kbd>(</kbd>, <kbd>;</kbd>, <kbd>.</kbd>

**Comment by CyrusNajmabadi** [comment]
Closing out as by design and lack of feedback.  If you type `new(` you get the desired `new()`.  If you type `new<Space>` we complete out the name.  This allows for both styles of results.
