### ISSUE TITLE
XML Settings from . EditorConfig should also be in EditorConfig (.NET)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52509]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/XML-Settings-from-EditorConfig-should-a/1302950)._

---
The new analyser features using editorconfig are great.
one thing I notice I get either C# or XML when choosing a template (https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019)

I believe that the xml idents should also be part of the .NET variant.
Especially formatting for any of the many proj extensions (like csproj) Build.Props/Targets are common place in most projects. So style rules (tabs, spaces, idents like in the 'plain' template) should be present.

Let me know what you think

---
#### Feedback Bot on 1/6/2021, 09:45 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by kaylumah** [comment]
Not sure which extensions this should cover, but I can imagine
- csproj
- vbproj
- deployproj
- sfproj
- *.targets
- *.props

and of course *.xml it self
Let me know if I missed any of the common extensions that are XML based

**Comment by Youssef1313** [comment]
Do you mean that `[*.xml]` should also match csproj, targets, props, etc?
I personally don't feel like it's a good/correct behavior. But let's see what the IDE team thinks.

**Comment by kaylumah** [comment]
@Youssef1313 not sure if XML should also be included.

At the very least the XML style files should match what visual studio does by default?

In my current editor config I have

```
[*.xml]
indent_style = space

# Change indent and spacing for proj files to match VisualStudio
[*.{csproj,sfproj, deployproj}]
indent_style = space
indent_size = 2
```

Where at least the XML bit comes from
![image](https://user-images.githubusercontent.com/8428126/114148040-a831cc00-9919-11eb-87db-26b7d8f6b860.png)

(which generates)
```
# To learn more about .editorconfig see https://aka.ms/editorconfigdocs

# All files
[*]
indent_style = space

# Xml files
[*.xml]
indent_size = 2
```

The reason this is important is that formatting and indenting cross IDE should be the same for these files.

To be honest not sure why one would use the "default"  template, I mostly require language specific template anyway and then include stuff for xml.

I think, but correct me if I am wrong, that csproj uses two spaces for identation.

**Comment by Youssef1313** [comment]
> I think, but correct me if I am wrong, that csproj uses two spaces for identation.

This is correct.

If I understand the issue correctly, I think it's not in Roslyn, but dotnet/templates. Specifically, in [*TemplateConstants.cs*](https://github.com/dotnet/templates/blob/main/src/Tools/Microsoft.VisualStudio.Templates.Editorconfig.Wizard/TemplateConstants.cs).

**Comment by kaylumah** [comment]
@yochu-msft I agree, think it ended up here since my original issue was the new rosyln editor config options that triggered me to compare the docs vs the VS generated ones.

Thanks for fixing, imo makes for a better experience cross platform / cross IDE :-)

**Comment by kaylumah** [comment]
@jmarolf / @Youssef1313 now that this has been merged is there anything I need to do to use this? Or is it waiting for the next update of visual studio?

**Comment by Youssef1313** [comment]
@kaylumah Should be in a update. I'm not sure which version will have this update though. Possibly @jmarolf knows.
