### ISSUE TITLE
IntelliSense in class constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-in-class-constructor/1359803)._

---
IntelliSense could be smart enough to predict that when someone is typing `myval= myval` in class constructor  it should be interpreted as `MyVal = myVal`. At this point of code writing it is already known to IntelliSense that `MyVal` is a property of the class and `myVal` is an constructor argument. So it is should be easy to guess correct `MyVal = myVal` code.

! [image.png] (https://aka.ms/dc/image?name=B0de4a2e73ded4046980799bd6ce18ff0637506931432220595_20210307-065223-image.png&tid=0de4a2e73ded4046980799bd6ce18ff0637506931432220595)

---
#### Feedback Bot on 3/8/2021, 00:28 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
@MarkWilsonThomas as well for this.

**Comment by kubaszostak** [comment]
![vs-auto-complete](https://user-images.githubusercontent.com/4609437/188268797-6c6f369b-0c25-4b3b-9978-de4928f0239e.gif)

**Comment by CyrusNajmabadi** [comment]
This is covered by intellicode/copilot.
