### ISSUE TITLE
Visual indication that method arguments that are not accessed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52502]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-indication-that-method-arguments-/1375194)._

---
Currently if you declare a method with arguments and do not access an argument within the method there are no visual hints to let you know that this is happening.  It would be nice if in that situation, any method argument that is not accessed would fade (or some other visual indicator was used to achieve the same thing).

---
#### Feedback Bot on 3/18/2021, 11:52 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is already done.  We fade out the parameter and tell you it's unused:

![image](https://user-images.githubusercontent.com/4564579/114096525-af060380-9873-11eb-98ad-69a956f98152.png)

![image](https://user-images.githubusercontent.com/4564579/114096579-c34a0080-9873-11eb-9467-c3e93ffe4ea7.png)
