### ISSUE TITLE
IntelliSense should complete undeclared variables that are referenced

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52505]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-should-complete-undeclared-/1368725)._

---
Let's say I write some code using an undeclared variable:

```csharp
var mass = 100;
var momentum = mass * velocity;
```

This has a compile error: the `velocity` variable is not declared.

I have an idea: what if Visual Studio were to complete such variables? So if I start typing:

```
var vel
```

then it should see that I have an undeclared variable `velocity` and fill in the rest!

---
#### Feedback Bot on 3/14/2021, 11:37 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is a good idea.  I wrote this at one point.  @MarkWilsonThomas.  Could this be something prose helps with?

**Comment by sharwell** [comment]
This definitely seems like something the name suggester could include.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
