### ISSUE TITLE
Inheritance margin must not serialize symbols from OOP to host.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#52526]
The current design of inheritance margin uses the FAR helpers that call into OOP, but which return symbols on the host side.  This is very problematic from a perf perspective as symbol serialization is extremely expensive.  In normal scenarios it will cause compilations to be built on the host that aren't htere, which can also cause extreme perf hits through things like skeleton assembly building.  

Features that depend on finding and operating on references must not work this way.  They should instead call to OOP to do the work, and then only serialize over the minimal amount of data needed just to drive the UI on the VS side.  IN a case like inheritance margin, this would be the text strings, possible classification, locations to navigate to, and glyphs (and things like that).  This vastly decreases the costs and means it's only in OOP where we're keeping around these large graphs of heavy objects.

Note: this is a ship-blocker for 'inheritance margin'.

**Comment by CyrusNajmabadi** [comment]
Tagging @vatsalyaagrawal for visibility here.

**Comment by sharwell** [comment]
It is also acceptable to use things like SymbolKey, provided they are only converted back to symbols via a separate call to OOP and/or for explicit actions, e.g. resolving exactly one symbol that is the target of a navigation from the glyph's menu.

But if possible we should avoid this altogether.
