### ISSUE TITLE
Add WRN_PartialMethodTypeDifference to warning wave

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52520]
#47879 indicates that this should have been added in 16.9, but it was missed.

Related to #47841 and #47879

@jaredpar @cston Can this be added now to warning level 5 or is it too late? I don't know what your policy is for adding new warnings to warning waves.

**Comment by jaredpar** [comment]
At this point it would need to be in a new warning wave. The current wave is essentially locked.

Not a huge deal though. We're doing a new wave with ever language version so it can just tack into the new one.

**Comment by RikkiGibson** [comment]
To be clear, this is something we'd now like to do in wave 6, right?

**Comment by Youssef1313** [comment]
> To be clear, this is something we'd now like to do in wave 6, right?

Yes.

@jaredpar Is this something that can go into features/compiler branch now?

**Comment by Youssef1313** [comment]
Closing. Fixed in #53352
