### ISSUE TITLE
Diagnostics from Source Generators do not respect suppression

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#52527]
Diagnostics produced by source generators do not respect the `/warnAsError` or `/noWarn` compiler flags.

**Comment by geeknoid** [comment]
A couple more related points:

- "#pragma warning dissable" has no impact on warnings produced by a source generator, the warnings are always presented to the user.

- On the flip side, source generator warnings don't seem to be visible to the VS IDE. The same "#pragma warning disable" statement which has no effect on disabling a source generator warning ends up being underlined by VS and flagged as a superfluous suppression. So the IDE isn't treating the warning from the source generator has being present, so it thinks the suppression is for naught.
-
