### ISSUE TITLE
Make cancellation handling command handlers more robust

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#52528]
https://github.com/dotnet/roslyn/pull/52514 fixes an issue where Roslyn does not handle cancellation correctly in command handlers. However, this approach is fragile as each command handler will need to remember to catch any potential cancellation exceptions after the next handler has been called.

We should instead consider coming up with a more robust approach, such as an abstract handler that each command handler implements that deals with catching the exceptions.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
