### ISSUE TITLE
Remove unnecessary cast changes overload resolution 

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#52524]
Given a case like:

```c#
ValueTask<object?> v = new((object?)null);
```

Then "remove unnecessary cast" says that `(object?)` is unnecessary and can be removed.  However, if you do this, overload resolution switches from calling the `ValueTask(object?)` constructor to teh `ValueTask(Task<object?> task)` constructor.  First, we shouldn't offer this if necessary for overload resolution.  Second, it's not quite clear to me why passing `null` here isn't ambiguous to the compiler as there seem to be too applicable overloads.

This woudl be fixed with https://github.com/dotnet/roslyn/issues/50043

Tagging @jaredpar  for visibility on both issues.  First, it would be really great if we could get eyes on https://github.com/dotnet/roslyn/issues/50043.  Second, it seems very weird here that `new(null)` even compiles here.

**Comment by jaredpar** [comment]
> Second, it seems very weird here that new(null) even compiles here.

This makes sense to me. There are two constructors to choose from: `ValueTask(object)` and `ValueTask(Task<object>)`. Both are valid for `new(null)` but the latter is the "better" candidate hence it's chosen.

**Comment by CyrusNajmabadi** [comment]
> but the latter is the "better" candidate hence it's chosen.

I'm curious why 'null' is a better match for Task than it is for object.  That's the part that isn't making sense currently.

**Comment by jaredpar** [comment]
It's not that `null` is better, is that that the `Task` overload is a better candidate. It has a more derived parameter type.

**Comment by CyrusNajmabadi** [comment]
> It has a more derived parameter type.
