### ISSUE TITLE
Suggest names for matching parameters from overloads

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#52534]
The naming suggestions for parameters should include names appearing for matching types in overloads. For example, the following parameters are all representing the same data, but appearing with three different names:

`sessionName`:

https://github.com/dotnet/roslyn/blob/550923308902260062579a2397bec5d9dd277802/src/Compilers/Shared/BuildClient.cs#L212

`sessionKey`:

https://github.com/dotnet/roslyn/blob/550923308902260062579a2397bec5d9dd277802/src/Compilers/Shared/BuildClient.cs#L272

`pipeName`:

https://github.com/dotnet/roslyn/blob/550923308902260062579a2397bec5d9dd277802/src/Compilers/Shared/BuildClient.cs#L284

Suggesting parameter names from overloads according to matching types (while accounting for the Async Pattern and Template Method Pattern naming conventions) would help avoid these mismatches.

Related to #52505

**Comment by davidwengier** [comment]
Reassigning to match the assignment of the PR
