### ISSUE TITLE
ResGen doesn't recognize ".NETPortable,Version=v5.0" TFM and generates non-portable code

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5254]
Repro:
1) Add a new resource string to ScriptingResources.resx in project Scripting and build
```
src\Scripting\Core\ScriptingResources.Designer.cs(42,196,42,204): error CS1061: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
```

2) Open ScriptingResources.resx designer:
"Could not resolve mscorlib for target framework '.NETPortable,Version=v5.0'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted"

**Comment by davkean** [comment]
This is known internally, and has been fixed in recent builds. The next update of Visual Studio will include the fix.

**Comment by dzmitry-lahoda** [comment]
You may get to this page with old, but updated(seems with issues) install of VS Professional 2015 Update 3, even if VS 2017 installed on system and .NET Core SDK.  I have downloaded dotnet-standard-support-vs2015-2.0.0-win-x86.msi from somewhere, install. Things started to work.
