### ISSUE TITLE
Array of nullable generic parameter has unexpected default value

### ISSUE THREAD

**Issue by Lancelotbronner** [dotnet/roslyn#52542]
I have the following structure:
```
class MyClass<T> {
  public T? array;

  MyClass() {
    array = new T?[1];
  }
}

struct MyStruct {
  string fields;
}
```

Now let's say I do the following:
```
MyClass<MyStruct> instance = new();
Console.WriteLine(instance.array[0] is null);
```

I would expect to see `True` however what I get is `False`. The array initializes itself with a bunch of empty structs while I would expect a bunch of `null`.

**Comment by CyrusNajmabadi** [comment]
You need to do:

```c#
class MyClass<T> where T : struct {
  public T? array;

  MyClass() {
    array = new T?[1];
  }
}
```

Without the `T : struct` constraint, `T?` means: "can be default(T)".  `default(MyStruct)` is not nullable, so it can't be null.  With the `T : struct` constraint means `can be Nullable<T>` so it can be null.

**Comment by Lancelotbronner** [comment]
But what if I need T to be either a reference or value type? I thought that was the whole point of nullable?

**Comment by CyrusNajmabadi** [comment]
> But what if I need T to be either a reference or value type? 

Then you do just `Foo<T>` with no constraints.  An uncosntrained type parameter can be a reference or value type. 

> I thought that was the whole point of nullable?

I don't know that means here.  The point of "nullable value types" was to allow one to represent a null state for any value type without high overhead.  The point of "nullalbe reference types" was to allow annotating your reference type usages to avoid null ref exceptions.

**Comment by Lancelotbronner** [comment]
Oh thank you that makes more sense, I just expected it to work more like Swift’s optionals.

I instead made my own Optional<T> which had the behavior I was looking for.

Thank you for your explanations!
