### ISSUE TITLE
Eroor

### ISSUE THREAD

**Issue by akramHossain49119** [dotnet/roslyn#52540]
Why show this error?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'object' does not contain a definition for 'Wait' and no accessible extension method 'Wait' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)

**Comment by Youssef1313** [comment]
It's hard to help without a code that has this problem. But it seems you're trying to access `Task.Wait` method (or any other Wait method), but your object isn't of the correct type. You may need to cast it to the type if it's guaranteed that it will be of that type. Or if this object was returned by some method, you may have the return type of that method incorrect.
