### ISSUE TITLE
Ctrl-Alt-Up/-Down not working

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5257]
The command works, but the keybinding doesn't.  Something upstream is probably eating it.

**Comment by tmat** [comment]
I'm not sure this is an issue. The binding that should work is Alt+UpArrow and Alt+DownArrow. Perhaps we should even make Ctrl+Alt+UpArrow not work, so that it can be used for other feature in future w/o breaking users.

**Comment by sharwell** [comment]
:question: What command(s) are expected to be associated with these bindings?

**Comment by amcasey** [comment]
Search history items that share a prefix with the current input.

**Comment by amcasey** [comment]
It turns out that Remote Desktop eats that key combination.
