### ISSUE TITLE
Missing compiler generated switch expression arm in/from ISwitchExpressionOperation

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#52577]
**Version Used**: 16.10.0 Preview 1.0

**Steps to Reproduce**:
[Compile](https://dotnetfiddle.net/g3msrW):
```CSharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

var tree = ParseSyntaxTree(@"
	
	var x = X.A;
	
	var xText = x switch {
		X.A => 1,
		X.B => 2,
	};
						   
	public enum X {
		A, B
	}
");


var refApis = AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic).Select(a => MetadataReference.CreateFromFile(a.Location));
var com = CSharpCompilation.Create("something", new []{ tree }, refApis );
var model = com.GetSemanticModel(tree);

var switchExpr = tree.GetRoot().DescendantNodes().OfType<SwitchExpressionSyntax>().First();

var switchExprOp = (ISwitchExpressionOperation)model.GetOperation(switchExpr);

//---only two arms are returned:
Console.WriteLine($"expected: {3}");
Console.WriteLine($"actual {switchExprOp.Arms.Count()}");

//SwitchExpressionArm warning is issued
Console.WriteLine();
Console.WriteLine("Diagnostics");
Console.WriteLine("---------");
foreach(var d in com.GetDiagnostics())
{
  Console.WriteLine(d);	
}
```

**Expected Behavior**:
All arms (in this case 3), including the generated "SwitchExpressionException" - arm should be returned from `ISwitchExpressionOperation`

And if you look at the lowered code, you can see that such an arm is created ([link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4DcIIAQA8MF4MAaAdAIIDcAsAFACQ1NamWAKnFjHthlAO4CWMAMYALDAG96NYiTwA+DAEYANJOIAhORgBMK2gF9KtGseMYz9AAIBmDHAB2AVzCFxkkkoxr6eoA=))

**Actual Behavior**:
Only the user defined arms are returned.

**Comment by CyrusNajmabadi** [comment]
Tagging @333fred

**Comment by 333fred** [comment]
I don't really think I'd expect to get the compiler-generated arm here. We don't generally return these types of nodes from IOperation. @bernd5 what is the actual use case here?

**Comment by CyrusNajmabadi** [comment]
Don't we?  This feels like how VB has some implicit return statements it returns from funcs and whatnot.  I would have genuinely thought we woudl ahve this IsImplicit arm in teh tree.  But perhaps that's much further down in lowering.  Instead of exposing the arm, could we expose if hte compiler did think it was exhaustive, or if it had to generate a fallback case (while not actually exposing the ops for that case)?

**Comment by bernd5** [comment]
I'd like to write rewriter which converts switch expressions back to switch statements. To do so I need to know if I have to add an artitificial default case in the switch statement.

> if it had to generate a fallback case
That would be sufficient for me.

Before I just had a look at the diagnostics - but there seems to be some new diagnostic-Ids and I generally dislike this diagnostic approach.

I have read (somewhere) that the introduction of the IOperation API was motivated by allowing users to look at the "lowered code". But later it was changed to "allow a language neutral perspective" of the code (e.g. to share code between CSharp and VB).
I could imagine that [IsImplicit](https://docs.microsoft.com/de-de/dotnet/api/microsoft.codeanalysis.ioperation.isimplicit?view=roslyn-dotnet) is a relict from the initial motivation.

**Comment by 333fred** [comment]
> I have read (somewhere) that the introduction of the IOperation API was motivated by allowing users a deeper look at the "lowered code". But later it was changed to "allow a language neutral perspective" of the code (e.g. to share code between CSharp and VB). I could imagine that IsImplicit is a relict from the initial motivation.

Neither is true. IOperation is designed to allow users to inspect the _semantics_ of the code, without having to consider syntactic-only constructs such as parentheses.

I wouldn't be opposed to a flag on the switch expression operation to indicate whether it was exhaustive, as that's a piece of semantic info. I know that in the CFG, we will generate the code for throwing in an invalid case, but we do a number of lowering-type operations in CFG so it feels appropriate there, while it doesn't feel particularly appropriate in the initial tree to me.

@AlekseyTs, do you have thoughts on this?

**Comment by bernd5** [comment]
What means "CFG"?

**Comment by CyrusNajmabadi** [comment]
Control-Flow-Graph.

**Comment by AlekseyTs** [comment]
> I wouldn't be opposed to a flag on the switch expression operation to indicate whether it was exhaustive, as that's a piece of semantic info.

Sounds reasonable to me.

**Comment by bernd5** [comment]
I had a look at the implementation - it looks quite easy to extend. But I'm not sure how the new property should be named - e.g. `ReportedNotExhaustive` or simply `IsNotExhaustive`.
The most complex part seems to me the tests - quite impressive how it is realized.

**Comment by 333fred** [comment]
I would prefer `IsExhaustive`, which returns true if the switch expression is exhaustive. If you're interested in contributing @bernd5 I'd be happy to help you work through the necessary tests. Generally, you'll want to take these steps:

1. Update the test visualizer to print the property: https://github.com/dotnet/roslyn/blob/main/src/Compilers/Test/Core/Compilation/OperationTreeVerifier.cs#L1944. A comma after the number of arms with `IsExhaustive: value` should be fine.
2. Run all the `IOperation`, `Semantic`, and `Emit` unit tests, and update any baselines.

I expect that we should have test examples of both exhaustive and non exhaustive switch expressions. If we don't have examples of both, then you'd want to add an additional test or two for the ones we don't have (but again, I expect we do).

**Comment by bernd5** [comment]
I could create a PR but in those test is not just valid code. For invalid code `IsExhaustive` could be either true or false.

**Comment by bernd5** [comment]
@333fred Could you have a look at the PR linked to this issue?

**Comment by 333fred** [comment]
Still needs to be triaged by review.

**Comment by 333fred** [comment]
# API Diff:

```diff
namespace Microsoft.CodeAnalysis.Operations
{
    public interface ISwitchExpressionOperation
    {
+       public bool IsExhaustive { get; }
    }
}
```

**Comment by 333fred** [comment]
## API Review

* Naming seems fine as long as the documentation about nullable implications is good.
