### ISSUE TITLE
Introduce Variable codeaction has text truncation logic that should be removed

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#5258]
Porting internal bug 129568.

Editor team has changed the LightBulb functionality so that it truncates LightBulb menu item's text at a certain length. It also replaces newlines, carriage returns, and tab characters with spaces.

[IntroduceVariable](https://github.com/dotnet/roslyn/blob/7755b1632509f7fc9c6f494c99711dae8d700499/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.AbstractIntroduceVariableCodeAction.cs#L79) does some truncation that is no longer required, so it should be removed (to maintain consistency).

**Comment by dpoeschl** [comment]
The existence of this truncation would prevent any custom screenreading/hover behaviors implemented by the lightbulb. +UserFriendly

**Comment by dpoeschl** [comment]
This is not a regression from RTM and hinders all users equally (screenreaders aren't at *more* of a disadvantage than visual readers), so there's no need to push this for 1.1. But it's something I'd like to see cleaned up, so let's consider this for 1.2.
