### ISSUE TITLE
Roslyn documentation comment IDs for explicit interface implementation members do not match those in shipping BCL documentation XML

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/roslyn#52599]
**Version Used**: 

16.10p1

**Steps to Reproduce**:

Define an explicit interface implementation property/method for a generic interface taking more than 1 type parameter, and add XML doc comments.  Ex:

```c#
internal class ImplementsIDictionary<TKey, TValue> : IDictionary<TKey, TValue>
{
    /// <summary>foo</summary>
    ICollection<TKey> IDictionary<TKey, TValue>.Keys => default;

    ...
}
```

**Expected Behavior**:

The shipping BCL docs escape `.` to `#`, `<` to `{`, `>` to `}`, and `,` to `@` in the method name portion of the documentation ID.  The following example is from the .NET Core 3.1 docs, which matches the xml shipping with NETStandard and NetFX.  Note the `@` between `TKey` and `TValue` in the property name:

```xml
<member name="P:System.Collections.Concurrent.ConcurrentDictionary`2.System#Collections#Generic#IReadOnlyDictionary{TKey@TValue}#Keys">
  <summary>Gets a collection containing the keys in the <see cref="T:System.Collections.Generic.Dictionary`2" />.</summary>
  <returns>A collection containing the keys in the <see cref="T:System.Collections.Generic.Dictionary`2" />.</returns>
</member>
```

**Actual Behavior**:

Roslyn escapes `.`, `<`, and `>`, but does not escape the `,`.  Ex:

```xml
<member name="P:ImplementsIDicitionary`2.System#Collections#Generic#IDictionary{TKey,TValue}#Keys">
    <summary>foo</summary>
</member>
```

I am unsure which of these is correct, but I would assume the comma should really be escaped as it is in the shipping documentation.  In either case, they should match.

**Comment by jaredpar** [comment]
@sharwell any thoughts here? I'm not sure which is correct here: docs or our implementation.

**Comment by sharwell** [comment]
The IDE never renders these, and I'm not sure it matters for documentation generation. Seems like changing the syntax now could break global suppressions.

**Comment by jaredpar** [comment]
That's a good point about the breaking changes here. Not sure it's realistic for us to change that at this point because of that.

**Comment by saucecontrol** [comment]
To give a bit of context here, this came up as an issue with my tool that post-processes `<inheritdoc />` to replace it with the actual inherited docs.  Being unable to find comprehensive documentation for the documentation ID rules, I built my own rules by running through the shipping XML from the framework and ensuring that I could match every XML type and member back to its corresponding type/member in the ref assemblies.

This was the escaping rule I backed into from that exercise:

https://github.com/saucecontrol/InheritDoc/blob/bd2f9dd1ddd776c27d24cbab8793e75a2e39367f/src/InheritDoc/CecilExtensions.cs#L196

vs what's in Roslyn:

https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Compilers/CSharp/Portable/DocumentationComments/DocumentationCommentIDVisitor.PartVisitor.cs#L281

This leads to an inability to match '<inheritdoc />' from an implementing member back to the BCL docs, as reported in https://github.com/saucecontrol/InheritDoc/issues/5

**Comment by saucecontrol** [comment]
Oops, this got closed while I was typing a reply.  Can you explain more about why a change would be breaking?

**Comment by sharwell** [comment]
Roslyn uses documentation IDs for matching global suppressions, e.g. the `Target` value [here](https://github.com/ArgiDou/MicrosoftAzureTrainingKit/blob/dd119b81abfc9444a351d74cfc9908fb1e460389/HOLs/HOL-WebServiceAndIdentity/Source/Ex1-UsingWIFandWCF/End/RelyingParty/GlobalSuppressions.cs#L11):

```csharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Microsoft.Security",
    "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands",
    Scope = "member",
    Target = "RelyingParty.AzureLocalStorageTraceListener.#GetLogDirectory()")]
```

Changing the syntax could cause the compiler to start issuing new build warnings inside explicit interface implementations.

**Comment by saucecontrol** [comment]
Thanks, @sharwell.  Yeah, I think I'll have to generate a list of match candidates on my side instead of a single ID.  Appreciate the update.
