### ISSUE TITLE
Pull member up does silly things if you don't select a base type

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#52591]
**Version Used**: Version 16.10.0 Preview 1.0

**Steps to Reproduce**:

1. Go to a member in a derived class.
2. Invoke pull member up, the option that shows a dialog.
3. Do _not_ choose a base type from the base type list.

**Expected Behavior**: either the base type is selected automatically, or the failure to select something prevents me from clicking OK.

**Actual Behavior**: the method is duplicated in the current class.

**Comment by Youssef1313** [comment]
The original intent was to disable the ok button for this case.

https://github.com/dotnet/roslyn/blob/299d55d2b5d7602cae875816e9d13b3483d3fcdb/src/VisualStudio/Core/Def/Implementation/PullMemberUp/MainDialog/PullMemberUpDialogViewModel.cs#L90
