### ISSUE TITLE
Roslyn plugin does not work for vs2019 16.3.2

### ISSUE THREAD

**Issue by XiaoYaoHui** [dotnet/roslyn#52596]
**Version Used**: VS2019 16.3.2

**Steps to Reproduce**:

1. Roslyn plugin does not work
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
This lacks enough information to be actionable

**Comment by Youssef1313** [comment]
My guess would be that @XiaoYaoHui is trying to use 3.9.x CodeAnalysis packages in older Visual Studio version (16.3.2), which AFAIK isn't supported. To use 3.9.x, you need Visual Studio 16.9+.
