### ISSUE TITLE
Binary layout schemas and transformations on IL-Level

### ISSUE THREAD

**Issue by biqas** [dotnet/roslyn#526]
Suggestion is to support binary layout in IL.

There is already a project from Microsoft where concepts can be taken from:
https://microsoft.github.io/bond/manual/bond_cpp.html#about

So for example to have the ability to describe the desired binary representation of a class.
(This is not from bond project)

```CSharp
.class public ansi auto MyClass extends [mscorlib]System.Object
{
    .field public int32 A
}
```

could be expressed like that

```CSharp
[Verion: 1]
.class public ansi auto MyClass extends [mscorlib]System.Object
{
    [Order: 0] 
    [Verion: 1]
    [Bit Used: 0XXXXXXX0] // 0: Not for use; // X: Can be used with 0 or 1; 1: Can be used only with 1.
    .field public int32 A
    // it is semantically an int32 but uses a lower byte foot print.

    [Order: 1] 
    [Verion: 1]
    [Bit Used: X] // 0: Not for use; // X: Can be used with 0 or 1; 1: Can be used only with 1.
    .field public int32 A
    // it is semantically a boolean but uses only one bit.
}
```

So there could be also some new kind of "newobj" call, which takes binary layout in account.
And if such IL-Code can be separated from the rest, it could be also used as shared IL-Code among  threads or process in a read-only or write-only manner. If you think of embedded devices where shared data is nothing unusual.

Binary-Layout description on IL-Level would share the same model across all IL-Based supported languages.

Its complicated to explain, but if you read all the documentation in the bond project
https://microsoft.github.io/bond/manual/bond_cs.html
you will see that also have a language (IDL) between and compile to specific languages there is still a lot of overhead which can be eliminated, at least within IL-Language supported Languages.

**Comment by gafter** [comment]
This is a proposal for a change to the CLR/IL specification. Is there a language proposal that this would support?

**Comment by gafter** [comment]
As this is a CLI spec request, it is out of place in the Roslyn project. Please reopen if you have a corresponding language proposal.

**Comment by gafter** [comment]
Perhaps the dotnet/clrcore project would be a better match.
