### ISSUE TITLE
Inconsistent CS8620 (differences in nullability of reference types)

### ISSUE THREAD

**Issue by betty-crokker** [dotnet/roslyn#52602]
**Version Used**: 
Visual Studio 16.9.3

**Steps to Reproduce**:

    public class JustAnEnum
    {
        public enum E
        {
            Blue,
            Red
        }

    }

    class Test
    {
        enum E
        {
            Yes,
            No
        }

        void Local(E? e = E.Yes)
        {
            Debug.WriteLine("Local(" + e + ")");
        }

        void Remote(JustAnEnum.E? e = JustAnEnum.E.Red)
        {
            Debug.WriteLine("Remote(" + e + ")");
        }

        public void Call()
        {
            // This line has no warnings
            Local();

            // This line has warning CS8620
            // Argument of type 'int' cannot be used for parameter 'e' of type 'JustAnEnum.E?' in 
            // 'void Test.Remote(E? e = 1)' due to differences in the nullability of reference types
            Remote();
        }
    }

**Expected Behavior**:
Giving a nullable enum parameter a non-null default value should never report CS8620

**Actual Behavior**:
E? e = E.Red does report CS8620 when the enum is defined in a different class

**Comment by RikkiGibson** [comment]
Thank you for reporting the issue. This looks like a dupe of #51622 which was fixed in 16.10.

**Comment by betty-crokker** [comment]
Agreed; also see https://github.com/dotnet/roslyn/pull/51631
