### ISSUE TITLE
[LSP] Server should handle URIs with escaped colons

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#52606]
The default System.URI class does not convert file paths with escaped colons to a valid windows path, see https://github.com/microsoft/vscode/issues/58985#issuecomment-423588474 .  This is problematic when the URI sent by the client is escaped as we can't find the matching document.  We need to work around this issue on the server.

For example, https://github.com/OmniSharp/omnisharp-roslyn/blob/6836fadb9c35a88d4695276d14302336a460b841/src/OmniSharp.LanguageServerProtocol/Helpers.cs#L70-L82

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.  If this is needed, please assign to a milestone.
