### ISSUE TITLE
Breaking change in ITypeSymbol.ToString() after update .net sdk from 5.0.201 to 5.0.202

### ISSUE THREAD

**Issue by Gambero81** [dotnet/roslyn#52623]
with .net sdk 5.0.201 if i get the type of a TypeSymbol object with:

```
...
var typeInfo = semanticModel.GetTypeInfo(identifierNameSyntax);
var typeString = typeInfo.Type.ToString();
```
it return the full qualified type name.

after update to .net sdk 5.0.202

for some types it return only the last name of the type.

Example:

instead of `System.Colletions.Generic.List` it return only `List`
instead of `System.Threading.Tasks.Task` it return only `Task`

it's a known breaking change?
How to get the full type name?

Thanks

**Comment by Youssef1313** [comment]
@Gambero81 Can you check whether the returned type is `IErrorTypeSymbol` or not?

**Comment by Gambero81** [comment]
@Youssef1313 i can confirm, if i check `type.Kind` it return `ErrorType`.

What's wrong?

**Comment by Youssef1313** [comment]
You might be missing some reference in the compilation. Can you check `compilation.GetDiagnostics()`?

It would also help if you can share a complete code snippet which causes this issue.

**Comment by Gambero81** [comment]
@Youssef1313 i found the issue!

It was caused by 2 packages in my analisys app: `NuGet.Frameworks` and `NuGet.ProjectModel`
the version of this packages was 5.9.0 and caused the issue with the newer `.net sdk 5.0.202` shipped with the last visual studio update.

Updating this libraries to the last version (5.9.1) solve the issue.

So i have a question:

The use of roslyn framework is stricted related to the visual studio version?

I would like to create a NuGet package with my code analysis application, this package will reference some `NuGet.Frameworks` and `NuGet.ProjectModel` module version, so it not will work well in future release of vs who require newer version of this modules? how can be solved this?

Thanks

**Comment by Youssef1313** [comment]
> The use of roslyn framework is stricted related to the visual studio version?

AFAIK, Yes. See https://github.com/dotnet/roslyn/issues/51478.
