### ISSUE TITLE
Codelens doesn't count references for `operator <`

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#52654]
**Version Used**: 
VS 16.10 Preview 2

**Steps to Reproduce**:

```csharp
using System;

C a = new(), b = new();
_ = a == b;
_ = a != b;
_ = a > b;
_ = a >= b;
_ = a < b;
_ = a <= b;

public sealed class C
{
    public static bool operator ==(C left, C right) => throw new NotImplementedException();
    public static bool operator !=(C left, C right) => throw new NotImplementedException();
    public static bool operator >(C left, C right) => throw new NotImplementedException();
    public static bool operator >=(C left, C right) => throw new NotImplementedException();
    public static bool operator <(C left, C right) => throw new NotImplementedException();
    public static bool operator <=(C left, C right) => throw new NotImplementedException();
}
```

Then you will found that only `operator <` shows "0 references", while others all "1 reference".

![](https://user-images.githubusercontent.com/23616315/114844422-60c1a900-9e0d-11eb-8b6b-7ac5d10d9d6d.png)

**Expected Behavior**:

`operator <` will also count the references.

**Actual Behavior**:

`operator <` doesn't count.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/bcd6eee255b1dc5e5d3ed9d5c56c5022eabc74a1/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs#L346

This method doesn't seem to handle SyntaxKind.LessThanToken, but handles all others. So this looks like it.
