### ISSUE TITLE
Make the SolutionFile class public 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#5266]
Filed on behalf of LSergey (http://connect.microsoft.com/VisualStudio/feedbackdetail/view/952541/make-the-solutionfile-class-public)

It would be nice to have an ability to parse solution files without loading projects.

**Comment by Pilchie** [comment]
Actually, in VS2015 we now use an API exposed by MSBuild for solution file parsing. See http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces.Desktop/R/ed6242ba72813b8d.html.
