### ISSUE TITLE
Uncomment not working for XML comment lines in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52681]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Uncomment-not-working-for-XML-comment-li/1396019)._

---
[severity:It bothers me. A fix would be nice]
When uncommenting XML comment style lines in a C# file (starting with 3 slashes /// ) then only 2 slashes are removed.
For example:
		
```
		/// <summary>
		/// Prevents a default instance of the <see cref="ConfigurationHandler" /> class from being created.
		/// </summary>
		private ConfigurationHandler() {}
```
leaves me with:
```
	/ <summary>
	/ Prevents a default instance of the <see cref="ConfigurationHandler" /> class from being created.
	/ </summary>
	private ConfigurationHandler() {}
```

Which is totally useless.

To repro: insert XML style comments to any method, select the lines with 3 slashes, press Ctrl+K, Ctrl+U (or select "uncomment lines" from Edit/Advanced)

---
#### Feedback Bot on 4/12/2021, 07:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I've marked this as **Need Proposal** prior to design review. The behavior of removing all three `/` would be equally meaningless, as the contents of an XML comment are not valid code.

**Comment by CyrusNajmabadi** [comment]
I agree with @sharwell here.  It's not clear when or why this would actually come up, or what the desired behavior would need to be.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of reasonable design and feedback.
