### ISSUE TITLE
Named Editorconfig rules are no longer working with `EnforceCodeStyleInBuild`.

### ISSUE THREAD

**Issue by irontoby** [dotnet/roslyn#52682]
**Version Used**: .NET SDK 5.0.201

**Steps to Reproduce**:
1. Create a project with `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>`
2. Create the following class with multiple code isssues:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public class Foo
{
    private int _age;
    private static DateTime _time = DateTime.Now;

    void Method1(object value)
    {
        int i;
        int.TryParse("1", out i);

        if (value is string)
        {
            var str = (string)value;
            Console.WriteLine(str);
        }
        else if (value is int)
        {
            i = (int)value;
        }

        i = default(int);

        (int Length, int Width) GetSize()
        {
            return (10, 20);
        }

        var size = GetSize();
        Console.WriteLine($"{size.Length} x {size.Width}");
    }

    static public DateTime Method2()
    {
        return _time;
    }

    public Int32 Age
    {
        get => _age;
        set => _age = value;
    }
}
```
3. Create an `.editorconfig` in the same folder with the following contents:
```
[*.cs]
csharp_style_inlined_variable_declaration = true:warning
csharp_style_pattern_matching_over_is_with_cast_check = true:warning
dotnet_style_prefer_auto_properties = true:warning
csharp_prefer_simple_default_expression = true:warning
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:warning
dotnet_style_require_accessibility_modifiers = for_non_interface_members:warning
csharp_style_deconstructed_variable_declaration = true:warning
dotnet_style_readonly_field = true:warning
dotnet_style_predefined_type_for_locals_parameters_members = true:warning
```
4. Run `dotnet clean && dotnet build`. Observe that **no warnings** are reported.
5. Replace the `.editorconfig` with the following contents, using analyzer IDs instead of named options:
```
[*.cs]
dotnet_diagnostic.IDE0018.severity = warning # csharp_style_inlined_variable_declaration
dotnet_diagnostic.IDE0020.severity = warning # csharp_style_pattern_matching_over_is_with_cast_check
dotnet_diagnostic.IDE0032.severity = warning # dotnet_style_prefer_auto_properties
dotnet_diagnostic.IDE0034.severity = warning # csharp_prefer_simple_default_expression
dotnet_diagnostic.IDE0036.severity = warning # csharp_preferred_modifier_order
dotnet_diagnostic.IDE0038.severity = warning # csharp_style_pattern_matching_over_is_with_cast_check
dotnet_diagnostic.IDE0040.severity = warning # dotnet_style_require_accessibility_modifiers
dotnet_diagnostic.IDE0042.severity = warning # csharp_style_deconstructed_variable_declaration
dotnet_diagnostic.IDE0044.severity = warning # dotnet_style_readonly_field
dotnet_diagnostic.IDE0049.severity = warning # dotnet_style_predefined_type_for_locals_parameters_members
```
6. Run `dotnet clean && dotnet build`. Observe that **9 warnings** are reported.

**Expected Behavior**:
Warnings are reported for all rules specified in `.editorconfig`, whether referenced by name or ID.

**Actual Behavior**:
Warnings are only reported for rules specified by ID.

These were working correctly previously; I'm not sure when they stopped working. Verified on Windows and Linux. (Rule IDE0038 is no longer working in either case.)

**Comment by Youssef1313** [comment]
This was an intended change I think.
@mavasani for more info

**Comment by mavasani** [comment]
The behavior in step 4 above has always been the same. The compiler/command line build only understands the dotnet_diagnostic based editorconfig entries for severity configuration. “:severity” based named entries never worked on command line builds and the compiler team doesn’t intend to support them either. See the “notes” section in https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules for details.

**Comment by irontoby** [comment]
@mavasani thanks for the feedback. I'm very confused as to what's going on here; I was absolutely getting warnings from `dotnet build` on these previously because I ran a script to disable existing warnings on our codebase using `#pragma` directives, based on the `dotnet build` output. There are definitely warnings such as `IDE0044` and `IDE0049` included in those, and we've never had the `dotnet_diagnostic` entries previously.

I'm guessing I must have enabled them in some other manner. It's disappointing to hear that support for the named entries won't be coming to the command line compiler, but I'll go ahead and close the ticket since you're saying it's working as intended. Thanks for clarifying.

**Comment by pi3k14** [comment]
> The compiler/command line build only understands the dotnet_diagnostic based editorconfig entries for severity configuration. “:severity” based named entries never worked on command line builds and the compiler team doesn’t intend to support them either. See the “notes” section in https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules for details.

@mavasani  How is that relevant?
naming-rules are rules for how you name classes etc. in your code
