### ISSUE TITLE
SyntaxFactory.AreEquivalent reports equivalence on differently formatted interpolated strings

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#5271]
`SyntaxFactory.AreEquivalent` returns `true` when the following two nodes are passed to it: 
`$"{Value:0.0}"` and `$"{Value:0.00}"`

**Comment by AdamSpeight2008** [comment]
Wouldn't it require knowledge of the value (of `value`) at compile-time?
The compiler would also need to the meaning of every possible `formatstring` for every possible type.

**Comment by sharwell** [comment]
@AdamSpeight2008 I think what @tvsonar is saying is that the two nodes *currently* return true, but they shouldn't for the reason you stated. Without knowing the type of `Value` along with the semantics of the format strings for that type, there is no way we could know that two different format strings produce equivalent output in all scenarios (locales, etc.).

**Comment by AdamSpeight2008** [comment]
@sharwell @tvsonar It could be that they are considered equivalent on a syntax node structure level? eg The actuals values don't matter, just so long as they're have the same structure.

**Comment by tvsonar** [comment]
@sharwell Exactly.
@AdamSpeight2008 I don't think these should be considered equivalent on syntax level. Syntactically the two expressions are different, because their interpolation format clauses are different. So in my opinion the `SyntaxFactory.AreEquivalent` should return `false`.

**Comment by gafter** [comment]
I an not able to repro this. @tvsonar are you still experiencing this on VS2015 Update 1, or a recent version of Roslyn?

**Comment by tvsonar** [comment]
@gafter No, I can't reproduce it either anymore with Update 1. It would be nice to know though when/where the problem was fixed.
