### ISSUE TITLE
VS intellisense bad sorting

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#52721]
Sorry I don't know what the correct place for put this issue.

VS2019 16.9.4
I really hate this sorting, how to disable it, and return back to legacy style?
![image](https://user-images.githubusercontent.com/12094247/115192634-a5a35380-a11d-11eb-8a84-f861732e9526.png)

**Comment by CyrusNajmabadi** [comment]
Can you supply a repro for this?  Thanks!

**Comment by ahdung** [comment]
I think you can reappear it in any c# project:
1. type `string.Format`
2. put the caret in `Format` or edge
3. press `ctrl + j`
4. You will see `Format` is above `Empty`

![image](https://user-images.githubusercontent.com/12094247/115201613-1cdde500-a128-11eb-8dc1-6653ae8aea33.png)

**Comment by huoyaoyuan** [comment]
This is IntelliCode. You can turn off IntelliCode completion for this.

**Comment by ahdung** [comment]
@huoyaoyuan Yah I try to disable IntelliCode, it just hide the star items, order still no change.

**Comment by CyrusNajmabadi** [comment]
It appears to just be ordering the item you already wrote at the top.  A normal completion list won't demonstrate this behavior.  @genlu Not sure if something changed here.  But it also seems fairly minor.

**Comment by ahdung** [comment]
@CyrusNajmabadi Yes it is, this issue makes coding difficult in some scenarios. for example:
I wrote this code:
![image](https://user-images.githubusercontent.com/12094247/115328139-afcb5d80-a1c2-11eb-8917-9756674f13b2.png)

then I copy `foo.B1 = 3;` to a new line, and want modify `B1` to the next property:
![image](https://user-images.githubusercontent.com/12094247/115327766-1734dd80-a1c2-11eb-84cc-89912c6cc3b9.png)

As you can see, I can’t easily see which item is next to `B1`.

**Comment by ahdung** [comment]
and I found something, if put caret to start, the order is well:
![image](https://user-images.githubusercontent.com/12094247/115328319-020c7e80-a1c3-11eb-96e7-82f73c18d37c.png)

This is the sorting I want.

**Comment by ahdung** [comment]
@CyrusNajmabadi This issue was not introduced in recent version, it existed for a long time in my memory, I guess since VS upgrade to 2019, in 2017 no this issue. I just busy to forgot submit.

**Comment by jmarolf** [comment]
Under Tools->Options I disabled all intellicode features
![image](https://user-images.githubusercontent.com/9797472/115330716-786c9a80-a149-11eb-8756-8b8b5c085080.png)
 and get this
![image](https://user-images.githubusercontent.com/9797472/115330741-84585c80-a149-11eb-8978-b4fd27e7f30e.png)

@ahdung how did you disable intellicode?

**Comment by ahdung** [comment]
@jmarolf I disable extension and restart VS.
![image](https://user-images.githubusercontent.com/12094247/115331680-ec01bc80-a1c8-11eb-9663-684d7ccbc98c.png)

Seems your result still has problem. BTW your icon little weird

**Comment by jmarolf** [comment]
>  BTW your icon little weird

I am on a preview build that has opted into new icons let me re-try in a non-preview build

**Comment by jmarolf** [comment]
> @jmarolf I disable extension and restart VS.

This will not work Intellicode appears in the extension menu but cannt successfully be uninstalled from there.

**Comment by ahdung** [comment]
But your way also not work, the `Format` still at top. so I think it's not about IntelliCode.

**Comment by ahdung** [comment]
BTW please don't remove legacy icons, the new icons is not pretty IMO.

**Comment by jmarolf** [comment]
wait I am just now getting it. You do not want _the word your cursor is on_ to appear in the list? 

the list should appear in alphabetical order if there is nothing typed
![image](https://user-images.githubusercontent.com/9797472/115332632-0ac26d80-a14d-11eb-8a44-789534759939.png)

but as soon as you commit a suggestion an invoke completion the word is going to be on top
![image](https://user-images.githubusercontent.com/9797472/115332685-2a599600-a14d-11eb-9e2a-676a9bb6fd7f.png)

you want intellisense to act as it does in the first screen shot?

**Comment by ahdung** [comment]
YES

**Comment by jmarolf** [comment]
Got it, in VS 2013 you couldn't re-trigger completion with typing but if I bring it up manually it only selects the word instead of sorting it to the top:

![image](https://user-images.githubusercontent.com/9797472/115335514-37c54f00-a152-11eb-8532-b465b06118e0.png)

**Comment by ahdung** [comment]
VS2017 also normal.
![image](https://user-images.githubusercontent.com/12094247/115337527-b6ae9c00-a1d3-11eb-85c4-6311f7667ff8.png)

**Comment by CyrusNajmabadi** [comment]
I'm not certain what is causing this item to be at the top of the list. I can't think of any good reason for it to be moved. Anyone know what might have changed this?

**Comment by jmarolf** [comment]
Presumably a platform change @gundermanc ?

**Comment by CyrusNajmabadi** [comment]
It coudl be on the Roslyn side too.  Though i can't think of any work we would have done that would have affected this.  @genlu Can you ptal to see if we're the ones doing this (and why), or if our sort is fine and this is happening outside of our control?

**Comment by genlu** [comment]
The sorting behavior was changed as part of this https://github.com/dotnet/roslyn/pull/38499

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
