### ISSUE TITLE
CS8751 when using ref struct System.Index

### ISSUE THREAD

**Issue by bysdxt** [dotnet/roslyn#52724]
**Version Used**: 
.net 5.0.202
**Steps to Reproduce**:

1. new console app
2.  code:
```cs
#pragma warning disable CS0436
using System;
namespace System {
    public readonly ref struct Index {
        public Index(int value, bool fromEnd = false) {
        }
    }
}
namespace ConsoleApp1 {
    interface I<T> {
        ref readonly T this[Index index] { get; }
    }
    class Program {
        static ref readonly T f<T>(I<T> i) {
            return ref i[new Index(1, true)];
        }
        static ref readonly T h<T>(I<T> i) {
            return ref i[^1];
        }
        static void Main(string[] args) {
            Console.WriteLine("Hello World!");
        }
    }
}

```
3. dotnet build

**Expected Behavior**:
Build succeeded
**Actual Behavior**:
Build FAILED.
Program.cs(18,26): error CS8751: Internal error in the C# compiler. 
Program.cs(18,24): error CS8347: Cannot use a result of 'I<T>.this[Index]' in this context because it may expose variables referenced by parameter 'index' outside of their declaration scope

It is ok that uses ```public readonly struct Index``` instead of ```public readonly ref struct Index```
[Program.zip](https://github.com/dotnet/roslyn/files/6334444/Program.zip)

**Comment by jcouv** [comment]
Note: one thing that is curious is that `^1` and `new Index(1, true)` yield different behaviors.
