### ISSUE TITLE
Make sure XmlDocCommentCompletionProvider works with records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#52738]
As a follow-up to https://github.com/dotnet/roslyn/pull/52737

Also when reordering parameters, such as what currently happens with methods:

https://github.com/dotnet/roslyn/blob/91571a3bb038e05e7bf2ab87510273a1017faed0/src/EditorFeatures/CSharpTest/ReorderParameters/ReorderParametersTests.cs#L427-L455

@jcouv, This may require parallel record structs work.

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by Youssef1313** [comment]
I'm working on this.
