### ISSUE TITLE
Unify SettingsUpdateHelper and ConfigurationUpdater implementation

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#52735]

**Comment by mavasani** [comment]
RE: Are there tests for ConfigurationUpdater?

There are no direct unit tests for this compoment, but it is thorough tested from the unit tests for Configure Severity and Configure Option lightbulb actions: https://github.com/dotnet/roslyn/tree/main/src/EditorFeatures/CSharpTest/Diagnostics/Configuration

**Comment by jmarolf** [comment]
Should ensure that we normalize the way line endings are added as part of this. I like @Youssef1313's suggested behavior here: https://github.com/dotnet/roslyn/pull/58075#discussion_r761348136

**Comment by jmarolf** [comment]
related to https://github.com/dotnet/roslyn/issues/54556

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
