### ISSUE TITLE
Support searching for Roslyn in Tools→Options

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#52730]
**Version Used**: 748a289bd

**Steps to Reproduce**:

1. Open **Tools &rarr; Options...**
2. In the search box, type `Roslyn`

**Expected Behavior**:

The tree filters to options relevant for Roslyn.

**Actual Behavior**:

The tree is completely empty.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need o do this we should assign to a person/milestone and do it.
