### ISSUE TITLE
Snippet loses focus when class is auto imported

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52741]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Snippet-loses-focus-when-class-is-auto-i/1397313)._

---
When i use a snippet like propfull and the type namespase is not allready imported, when I press Enter to accept InteliSense suggestion, after auto import happens the field loses focus so I cannot use Tab to move to the second parameter (property name).

---
#### Feedback Bot on 4/14/2021, 00:32 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Feedback Bot on 4/19/2021, 09:35 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippet scenarios.
