### ISSUE TITLE
EnC - Need a way to determine if a class already has a lambda helper class

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#52759]
In #49010, there are multiple capabilities that a runtime can support for Edit and Continue. Two of these are `AddDefinitionToExistingType` and `NewTypeDefinition`.

When the user adds a lambda to a method the resulting IL change that needs to be applied could be adding a definition to an existing type, if there is already another lambda defined anywhere in the class, or a new type definition, if the new lambda is the first one in the class. Unfortunately we have no way of determining this right now so we simply have to check for both capabilities.

It is expected this will limit what a user can do in Mono.

This issue is referenced in source.

**Consider**: When determining the exact capabilities is complex we could check based on the results of EmitDifference (and possibly amend the results to allow these checks). This would allow for precise validation, but we would only report potential rude edits once the user triggers "Apply" (i.e. not as they are typing).

**Consoder**: Avoid sharing static closure types across methods when emitting EnC deltas (we can always include generation number in the type name).

Related: https://github.com/dotnet/roslyn/issues/66680

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, just asssign to dev/milestone for it to eb done.
