### ISSUE TITLE
Generate-Member items are inconsistent

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5275]
![image](https://cloud.githubusercontent.com/assets/4564579/9911845/f95cd10a-5c58-11e5-931d-d7296d404d1d.png)

Why:
1. generate field '_parameter' in 'Rewriter'
2. generate read-only field 'Rewriter._parameter'

?

I'm not sure why the type needs to be specified in the first place.  But, if it does, then we should at least be consistent with the phrasing of both of these.

**Comment by Pilchie** [comment]
In triage, we decided that we should:
1. Drop the context type if the member is going to be generated into the current type.
2. For cases where the member will be generated into a different type (say off a local), we use use "Generate *member* 'unboundType' in 'ContextType'" form.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This has been resolved and we're consistent:

![image](https://user-images.githubusercontent.com/4564579/76677320-188ce300-658a-11ea-8c61-b3ef11dc9a63.png)
