### ISSUE TITLE
Compiler server fails for command line arguments over 1MiB

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#52761]
**Version Used**: Microsoft (R) Visual C# Compiler version 3.10.0-3.21215.6 (748a289b)

🔗 This contributes to [AB#1293790](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1293790)

**Steps to Reproduce**:

1. Add files until the command line exceeds 1MiB
2. Build the project

**Expected Behavior**:

The project builds with the compiler server.

**Actual Behavior**:

```
CompilerServer: server failed - server rejected the request 'Error writing build request: Specified argument was out of the range of valid values.
Parameter name: Request is over 1MB in length'
```

**Comment by jaredpar** [comment]
The 1MB limit here is arbitrary, we can extend it.

**Comment by akoconx** [comment]
Building on macOS with over 5MB causes this issue, not on Windows 11 though.

**Comment by akoconx** [comment]
Some older packages caused the problem and in the end clearing nuget helped using following command:
dotnet nuget locals all --clear
