### ISSUE TITLE
EnC: adding PrintMembers method to record in nullable-disabled context changes some attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52786]
Repro: see `Records_AddWellKnownMember` but remove the `#nullable enable` from both sources.
The synthesized `PrintMembers` has an annotation on the parameter, but the user-defined `PrintMembers` after the change has no annotation, so EnC produces an extra row for an attribute (a `NullableContext` attribute).

This should probably be blocked with a rude edit for now, until EnC adds support for attribute changes.

Tagging @tmat @davidwengier as FYI.

Relates to https://github.com/dotnet/roslyn/pull/52762#discussion_r617013922

**Comment by davidwengier** [comment]
So the synthesized parts of a record are always nullable aware? I think that would mean we'd be reporting rude edits quite a bit, since having nullable enabled is not yet the default.

Given that the attributes have no runtime impact anyway, I wonder if we can just ignore them instead?

**Comment by jcouv** [comment]
Ignoring nullability attributes would make sense too.

**Comment by davidwengier** [comment]
Going to close this. EnC no longer reports rude edits when nullability differs, so this works as expected. No rude edits, and extra attributes being emitted are supported anyway.
