### ISSUE TITLE
Extract Method not available for expression inside of expression body

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#528]
Ported from TFS WorkItem: **1124733**

1. paste the following C# code:

``` C#
class T
{
    int m;
    int M1() => 1 + 2 + 3 + m;
    int M2()
    {
        return 1 + 2 + 3 + m;
}
```
2. select "2 + 3 + m" then press Ctrl+[DOT]

**Expected**:
Extract Method quick action

**Actual**:
No quick actions available here.

**Comment by Pilchie** [comment]
This also affects introduce local, if you select the "1", instead of a selection that requires the selection to be extended.

**Comment by balajikris** [comment]
@Pilchie we could only extract to fields from inside expression bodied members, not locals. correct ?

**Comment by Pilchie** [comment]
Well, for bonus points we could convert the expression bodied member into a normal one if the user introduces a local.

**Comment by balajikris** [comment]
sounds great. :+1:
