### ISSUE TITLE
Go to definition in mixed C# and C++/CLI project does not go to source

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52806]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Go-to-definition-in-mixed-C-and-CCLI-/946016)._

---
I have a solution which contains
 - a C# project (console app)
 - a C++/CLI dll

When I ctrl-click an item imported from the C++ project in C# I am taken to the decompiled source from metadata, not the actual source. Debugging into the source works fine, as well as intellisense. It is just the "go to definition" that is not working.

Is there some recommended setup to get the code navigation to work or is it simply not supported?

Thanks

---
#### Feedback Bot on 3/12/2020, 02:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 3/17/2020, 11:38 PM: 

<p>Thank you for your feedback and taking the time to reach out to us.<br>
According to your description, I tried to test it and got the same result as yours. This issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

---
#### Vatsan Madhavan [MSFT] solved on 3/31/2020, 10:45 AM, 1 votes: 

<p>This affects a couple of .NET Framework assemblies (PresentationCore.dll, System.Printing.dll for e.g.) and .NET Core assemblies (DirectWriteForwarder.dll, System.Printing.dll). </p>

**Comment by CyrusNajmabadi** [comment]
> Is there some recommended setup to get the code navigation to work or is it simply not supported?

This can be supported if C++ plugs into the roslyn mechanism for allowing 'third party navigation'.  I'm looking for someone on C++ to pull into the discussion to see if they want to add support for this.

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonb01 on this.  We defer to IVsSymbolicNavigationNotify for this sort of thing.  So when we're about to navigate, we call QueryNavigateToSymbol.  If some party in VS (lke C++) says: "yup, that can navigate to this file/line" then we defer to that.

So it's mostly up to you guys if you want to add support for this.

Note that currently this is a COM/non-cancellable call.  So it's pretty hard to do well as the receiver has to be able to very quickly determine if it can navigate to the symbol without blocking the UI indefinitely.  I would def prefer we move to at least a cancellable form, as well as a non-STA approach if possible here.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is on C++ to support.

**Comment by emmenlau** [comment]
Dear @CyrusNajmabadi where would this issue need to be raised, to be better fitting?

**Comment by CyrusNajmabadi** [comment]
I would file it using visual studio. It will go to developercommunity and get routed properly.

**Comment by emmenlau** [comment]
Could you kindly help me with this? Upstream Developer Community considers this here to be the place to report this problem! But you consider it to be out of scope. Who is correct? Could you kindly request in https://developercommunity.visualstudio.com/t/Intellisense-does-not-navigate-from-C-t/10878849 that the issue would be redirected to the *correct* place?

**Comment by CyrusNajmabadi** [comment]
Thanks.  I reactivated the devcom issue :)

**Comment by emmenlau** [comment]
Awesome! Thanks!
