### ISSUE TITLE
Find All References doesn't show matching declarations that use "var"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52804]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Find-All-References-doesnt-show-matchin/846398)._

---
When using **Find All References** on a class, the results only include places where the actual class name is used. If you use `var` to declare a variable, the reference is not shown. This prevents finding what are technically references to the class, and is inconsistent with the editor highlighting. Consider the following example code:

```
namespace DemoApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var test = getX();
            var b = 7;
            var test2 = test;
        }

        static X getX() => new X();
    }

    class X { }
}
```

In the Visual Studio code editor, if I put my cursor on any occurance of `X`, all other occurances will be highlighted, *including* the `var` in front of the `test` and `test2` variables. Similarly, if I put my cursor on the `var` in front of `test2`, the `var` in front of `test` will be highlighted, as well as all occurances of `X`. This makes sense, because the `var` is being inferred as `X`. Thus, it would follow that if I right-click on `var` in front of `test` and choose **Find All References** I should get similar results -- not so! It does indeed interpret the action as "Find all 'X' references", but it only shows the `class X ...` and `static X ...`  lines; the `var test ...` and `var test2 ...` lines are not found.

If you make heavy use of `var`, this can result in it being much more difficult to find references to classes or other types.

---
#### Feedback Bot on 12/6/2019, 02:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 12/10/2019, 06:22 PM: 

<p>Thank you for your feedback.<br>
When we use “Find All References”, the Editor will show where explicit data types are referenced. The var keyword instructs the compiler to infer the type of the variable from the expression on the right side of the initialization statement. It is a implicitly type. So it just shows the “static X…” where the X is explicitly referenced.<br>
BTW, you could add “int c = 9”, then right-click “var” in front of b, it will just show “int c=9”</p><p><img src="https://aka.ms/dc/file?name=B7ffadb4945ac44179287d1314a6499d5637494370596469229_vs19editor.png&tid=7ffadb4945ac44179287d1314a6499d5637494370596469229"></p>

#### Caleb Martin on 12/10/2019, 09:04 PM: 

<p>I'm a bit confused... this is marked as "Need More Info", but the comment from <a rel="user" href="https://vsf-prod.westus.cloudapp.azure.com/users/53868/b85f0162-6f78-6997-a3da-4e461c50361e.html" nodeid="53868">@Sara Liu [MSFT]</a> does not seem to be a request for info, but rather repeating my description of the problem with an additional example. Do you need more information from me? If so, what?</p>

#### Sara Liu [MSFT] on 12/11/2019, 11:30 PM: 

<p>Hi Martin, sorry for any puzzled. Usually, we add a reply when will change the status to "Need More Info" that seems like waiting for response comes from the customer :)</p><p>For this, since the "var" is a implicitly type and that the compiler determines and assigns the most appropriate type, seems the Find All References not apply for it.</p>

#### Feedback Bot on 12/24/2019, 07:07 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Caleb Martin on 12/24/2019, 09:25 PM: 

<p>What information is lacking? I feel like my initial writeup was plenty of information, and <a rel="user" href="https://vsf-prod.westus.cloudapp.azure.com/users/53868/b85f0162-6f78-6997-a3da-4e461c50361e.html" nodeid="53868">@Sara Liu [MSFT]</a>'s response seemed to indicate that no additional information was needed from me.</p>

#### Sara Liu [MSFT] on 12/25/2019, 00:26 AM: 

<p>This issue has been escalated for further investigation, if there is any process, I will inform you immediately.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is working as expected.  We don't show implicit references to types in FindReferences.  Here's another example of that:

```
TakeX(getX());
```

A FAR on 'X' will not show that location (even though it also creates a temporary of type X to pass into the other method).  

We consider references things like the places that would need to update if you actually did something like rename the type name.  In these cases, the name is never specified, so there is no actual 'reference' to the type there.  It's just an ephemeral thing that flows along with the values and is not stated.

--

This would also not be something we could efficiently implement.  If implicit references need to be found, we would have to bind *all* 'var's in the entire solution to see if it was a match.  This would increase the cost of finding these types by orders of magnitude.

**Comment by taiji123** [comment]
Sorry @CyrusNajmabadi but this part of your response doesn't seem to make much sense: "If implicit references need to be found, we would have to bind all 'var's in the entire solution to see if it was a match."

I say this because when you execute FAR command _on the 'var'-declared variable itself_, the inferred type _is_, in fact, recognized correctly and the list of references is reported correctly, as it would against any other (explicitly declared) variable of that type.  (With the notable exception, of course, of that same 'var' variable declaration, on which the command was executed -- which is the problem defined in this ticket.)

It would seem that the design/implementation of that feature could, and should, be adjusted to reflect implicitly-delated variables.  Otherwise, if anyone uses 'var' anywhere, those are hidden and that makes the FAR command so wrong that it's nearly useless.

This ticket should be reopened!

**Comment by CyrusNajmabadi** [comment]
> I say this because when you execute FAR command on the 'var'-declared variable itself, the inferred type is, in fact, recognized correctly 

Yes.  That is one reference.  Find-Refs would need to bind thousands to millions of cases.  It is completely different.  Even if it's 0.1 seconds to do that, this could add absolutely massive costs to the find-refs experience.

> It would seem that the design/implementation of that feature could, and should, be adjusted to reflect implicitly-delated variables.
