### ISSUE TITLE
Reduce typing delay caused by import completion

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#52814]
The idea came up during the discussion of LSP completion perf for large item count (#52813 for more details). We'd like to experiment this in local scenarios as well, since limiting the length of completion list would likely be beneficial for local completion performance.

**Comment by genlu** [comment]
I made an attempt to show fewer (unimported) items in the completion list, but turns out it doesn't really have much impact on perf. While we can reduce the allocation during a completion session (by not creating VS CompletionItems), we still need all the items in the form of Roslyn CompletionItemsm and we still need to sort and select from this complete list every time user typed a character.

Given the goal is to minimize UI delay during typing while still provide unimported item in as many scenarios as possible, I think it'd make sense to make some tweaks the proposal here. Instead of always showing a capped list, we'd let CompeltionSource return a full list including all unimported items if they can be calculated quickly, otherwise, we flag the result as incomplete and return w/o those unimported items (while letting the calculation to continue in background,). Next time user types something, Editor will ask CompletionSource again, then we will check the background task and return them if completed. This way, import completion will not block showing of completion list or commit if the computation takes long, while still have the chance to be shown to the user each time they type (w/o additional user actions, like selecting the expander button)

**Comment by genlu** [comment]
@jinujoseph is there a 17.2p1 milestone?

**Comment by jinujoseph** [comment]
@genlu ... yes main is targetting 17.2.p1

**Comment by genlu** [comment]
This was completed in 17.3
