### ISSUE TITLE
Report warnings from nullable analysis of lambda expressions with attributes

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#52827]
Report warnings from nullable analysis of lambda expressions and lambda parameters with attributes: `[AllowNull]`, `[DisallowNull]`, `[MaybeNull]`, `[MaybeNullWhen]`, `[NotNull]`, `[NotNullWhen]`, and `[DoesNotReturn]`.

Relates to "lambda improvements" feature ([test plan](https://github.com/dotnet/roslyn/issues/52192))

**Comment by jcouv** [comment]
Resolved in 17.0p5
