### ISSUE TITLE
Add portable-pdb UI to Visual Studio

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5285]
UI:

![image](https://cloud.githubusercontent.com/assets/41759/9916847/61493b7c-5c73-11e5-98e0-a4f427533225.png)

**Comment by tmat** [comment]
@jaredpar

**Comment by tmat** [comment]
We should also remove "pdb-only" from the UI as there is no difference between it and "full". Renaming "full" to "non-portable" (or some better word) would be good.

**Comment by jaredpar** [comment]
The #6459 bug now tracks this and several other items.
