### ISSUE TITLE
request compiler optimization about casting

### ISSUE THREAD

**Issue by rootflood** [dotnet/roslyn#52889]
**Brief description:**

when a class is inherit and i'm sure will use parent but not sure use child that may have some sort of casting
fo example:
```C#
public class clsA
{
    public int A_Value;
}

public class clsB : clsA
{
    public int B_Value;
}
        
public class C {
    static void Main(bool ineed_A)
    {
        clsA x;
        if (ineed_A)
        {
            x = new clsA();
        }
        else
        {
            x = new clsB();
        }
        
        x.A_Value = 12;

        if (ineed_A)
        {
            x.A_Value = 12;
        }
        else
        {
            ((clsB)x).B_Value = 15; // casting
        }

    }
}
```

this is possible to ignore casting with two variables:
```C#
public class clsA
{
    public int A_Value;
}

public class clsB : clsA
{
    public int B_Value;
}
        
public class C {
    static void Main(bool ineed_A)
    {
        clsA x1;
        clsB x2=null;
        
        if (ineed_A)
        {
            x1 = new clsA();   
        }
        else
        {
            x2 = new clsB();
            x1 = x2;   
        }
        x1.A_Value = 12;

        if (ineed_A)
        {
            x1.A_Value = 12;   
        }
        else
        {
            x2.B_Value = 15; // no casting    
        }
    }
}
```

but i think a developers likes to write first example because of readability and maintainability of code, so i have optimization request if this is possible.

**Languages applicable:**
C#

**Comment by CyrusNajmabadi** [comment]
You'd is a language request. A discussion should be opened at csharplang instead.

**Comment by rootflood** [comment]
@CyrusNajmabadi i haven't no idea about C#, my request is just about optimization on C# compiler not C# language so is that related to csharplang?

**Comment by CyrusNajmabadi** [comment]
Yes. The compiler implements the language. So if you want the compiler to allow something, the language needs to be changed to make it legal.

**Comment by rootflood** [comment]
based on DotNetBenchmark the optimization is not valuable.
https://github.com/dotnet/csharplang/discussions/4691#discussioncomment-654520

Closed as not valuable.

**Comment by rootflood** [comment]
Reopened as result is failed.

https://github.com/dotnet/csharplang/discussions/4691#discussioncomment-654591

**Comment by rootflood** [comment]
i didn't know the "as" operator is faster than castclass https://www.codeproject.com/Articles/8052/Type-casting-impact-over-execution-performance-in
so my problem cloud fix with that:

```C#
public class clsA
{
    public int A_Value;
}

public class clsB : clsA
{
    public int B_Value;
}

public class C {
    static void Main(bool ineed_A)
    {
        clsA x;
        if (ineed_A)
        {
            x = new clsA();
        }
        else
        {
            x = new clsB();
        }

        x.A_Value = 12;

        if (ineed_A)
        {
            x.A_Value = 12;
        }
        else
        {
            ((clsB)x).B_Value = 15; // casting is slow so don't
            (x as clsB).B_Value = 15; // fast and speed is very close to no casting
        }

    }
}
```

so problem can be fixed with change in the code
Closed as a fixable code.
