### ISSUE TITLE
SyntaxKind check from base doesn't flow to derived nodes

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#52905]
For instance:

The base `SwitchLabelSyntax` defines:

https://github.com/dotnet/roslyn/blob/62528a6843dc5b21b1a7d399bae814868456e823/src/Compilers/CSharp/Portable/Syntax/Syntax.xml#L2798-L2799

But it's not mentioned in `DefaultSwitchLabelSyntax`:

https://github.com/dotnet/roslyn/blob/62528a6843dc5b21b1a7d399bae814868456e823/src/Compilers/CSharp/Portable/Syntax/Syntax.xml#L2865

Therefore there's no check in the factory:

https://github.com/dotnet/roslyn/blob/62528a6843dc5b21b1a7d399bae814868456e823/src/Compilers/CSharp/Portable/Generated/CSharpSyntaxGenerator/CSharpSyntaxGenerator.SourceGenerator/Syntax.xml.Main.Generated.cs#L4403-L4407

Discovered while doing extended prop patterns.

**Comment by alrz** [comment]
@CyrusNajmabadi Is this right?

**Comment by CyrusNajmabadi** [comment]
looks wrong to me.
