### ISSUE TITLE
A defaultable generic type is not accepted in an override method.

### ISSUE THREAD

**Issue by Takym** [dotnet/roslyn#52903]
**Version Used**: C# 9.0, .NET 5.0, Visual Studio 16.9.4

**Steps to Reproduce**:

1. Make an abstract class like below:
```csharp
public abstract class ClassA
{
	protected abstract void Method<T>(T? valueIn);
}
```
2. Make a class that derived from `ClassA` like below:
```csharp
public class ClassB : ClassA
{
	protected override void Method<T>(T? valueIn)
	{
		// some code...
	}
}
```

**Expected Behavior**:
These codes should pass compilation.

**Actual Behavior**:
The compiler fails with the error code CS0453, CS0534, and CS0115.

**Additional Context**:
The code below passes compilation with warning CS8765:
```csharp
public class ClassB : ClassA
{
	protected override void Method<T>(T valueIn)
	{
		// some code...
	}
}
```

**Comment by Takym** [comment]
This bug also occurs in here pattern:
```csharp
public class ClassA
{
	public virtual void Method<T>(T? valueIn)
	{
		// some code...
	}
}

public sealed class ClassB : ClassA
{
	public override void Method<T>(T? valueIn)
	{
		base.Method(valueIn);

		// some code...
	}
}
```

**Comment by ufcpp** [comment]
see: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md#default-constraint

```cs
public class ClassB : ClassA
{
    protected override void Method<T>(T? valueIn)
        where T : default
    {
    }
}
```

**Comment by jcouv** [comment]
This behavior is expected. For an unconstrained type parameter `T`, `T?` is clearly `T` with an annotation in the declaration, but it could mean that or `System.Nullable<T>` in an override. But the type needs to be determined before the overridden method is found. The solution is to specify `where T : default` on the override, to make it clear that this is `T` with an annotation, and not `System.Nullable<T>` (which is the default interpretation).
Closing as by-design.

**Comment by RikkiGibson** [comment]
Issue #46458 tracks improving the diagnostics in this scenario.
