### ISSUE TITLE
Code Action menu takes too long to show up

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#52952]
It may be because some extensions that do extensive analysis on entry but that shouldn't block built-in analyzers.

One possible solution is to show menu items as they complete.

Also if one item is immediately selected, there shouldn't be a wait to calculate the fix diff (i.e. it should be cancelled)

Relates to https://github.com/dotnet/roslyn/issues/42050

**Comment by Youssef1313** [comment]
> One possible solution is to show menu items as they complete.

Tagging @CyrusNajmabadi since he discussed this with someone on Discord a while ago. But I don't recall what was your concerns about this.

**Comment by CyrusNajmabadi** [comment]
Yes.  We are discussing this space internally.  One thing we may likely do is have priority classes here.   So high pri items are computed faster.

**Comment by jinujoseph** [comment]
cc @olegtk  for info

**Comment by CyrusNajmabadi** [comment]
@olegtk are we at a good point that we can start collaborating on a better experience here?  Thanks!

**Comment by olegtk** [comment]
@AmadeusW

**Comment by CyrusNajmabadi** [comment]
Closing as stale.  We already have priority groups here.
