### ISSUE TITLE
nuget restore failure

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#5296]
When running step 3 in the [`building, testing, and debugging`](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging) wiki page, I get dozens of errors spewed to the console that are all roughly the same.  

Here is an example:

```
C:\Users\Ty\Documents\Visual Studio 2015\Projects\roslyn\build\Targets\VSL.Sett
ings.targets(35,5): error MSB3073: The command "C:\Users\Ty\Documents\Visual St
udio 2015\Projects\roslyn\build\Targets\..\..\nuget.exe restore C:\Users\Ty\Doc
uments\Visual Studio 2015\Projects\roslyn\build\Targets\..\..\build\ToolsetPack
ages\project.json" exited with code 9009. [C:\Users\Ty\Documents\Visual Studio
2015\Projects\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.cspro
j]
```

**Comment by gafter** [comment]
Did you install VS's Windows 10 tools?

**Comment by TyOverby** [comment]
> Did you install VS's Windows 10 tools?

Yep

**Comment by TyOverby** [comment]
Update: 

I seem to have installed the VS Windows 10 tools (when I run the installer again, it says that it is already installed), but visual studio says differently.

When I tried to make a "windows universal" app, it said that I was missing an SDK.  I was linked to [http://go.microsoft.com/fwlink/?prd=12514&pver=14.0&sbp=PlatformSDKMissing&plcid=0x409&o1=UAP,%20Version=10.0.0.0](http://go.microsoft.com/fwlink/?prd=12514&pver=14.0&sbp=PlatformSDKMissing&plcid=0x409&o1=UAP,%20Version=10.0.0.0) which if you click on it, you'll see is completely unhelpful because it redirects to "microsoft.com".

**Comment by weltkante** [comment]
Had the same problem, could not create/open universal application projects even though the SDK was installed.

A few days ago a Windows 10 Tools update (10.0.10240) came to my VS notification center and I updated that. I also installed the emulators (even though I only develop for desktop).

One of these two have fixed it, I now can open universal projects. So you may try installing the emulators if you haven't and see if it fixes your problem.

**Comment by davkean** [comment]
@TyOverby You still running into issues around this? I've made sure the instructions reflect current guidance. I cannot repro this and its probably stale, feel free to reopen if you are still running into issues.

**Comment by TyOverby** [comment]
Ok.  It's been a while since I tried at home.  Once we lose our dependence on Windows 10 tools, I'll try again, because I think visual studio was the culprit here.
