### ISSUE TITLE
IDE0063 does not keep line breaks and indents correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#52970]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0063-does-not-keep-line-breaks-and-in/1404759)._

---
[severity:I'm unable to use this version]
When converting a block using statement to a simple using statement, Visual Studio delete next line break.
[using.png] (https://aka.ms/dc/file?name=B457d03b0d3d441e99acfe730f34e4737637546476486574335_using.png&tid=457d03b0d3d441e99acfe730f34e4737637546476486574335)

Also, the indentation of the code in the block may be incorrect after conversion. I'm not sure what the conditions are for this to happen.

---
#### Feedback Bot on 4/21/2021, 06:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/27/2021, 10:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
### Initial code

```csharp
using (var stream = new FileStream()) {
    stream.CopyTo(null);
}
```

### Expected result

```csharp
using var stream = new FileStream();
stream.CopyTo(null);
```

### Actual result

```csharp
using var stream = new FileStream()) stream.CopyTo(null);
```
