### ISSUE TITLE
Misleading "unreachable code" warning reported for script submission "return;"

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#5297]
Use ```var c = CSharpCompilation.CreateSubmission(...);``` to create a compilation for ```return;```. ```c.GetDiagnostics()``` includes ```(1,1): warning CS0162: Unreachable code detected```.

**Comment by ManishJayaswal** [comment]
Does not impact interactive window scenario.

**Comment by amcasey** [comment]
I think this was fixed as part of the top-level-return work.  Please reactivate if that's not the case.
