### ISSUE TITLE
C# LSP can't provide diagnostics for Razor files in .NET 6 Preview4+

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#52980]
**Version Used**: VSMain

**Steps to Reproduce**:

1. Download latest .NET 6 Preview4 SDK
2. Use VSMain latest
3. Create a new Blazor Server App .NET 6
4. Open FetchData.razor
5. Make a C# error and wait (none will appear):

**Expected Behavior**:
You get an error, and one that can be resolved after fixing it.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2008729/116324450-04e41200-a775-11eb-9421-1b62271f3135.png)

And any new errors/attempts to fix errors get ignored.

## Notes

@jasonmalinowski @CyrusNajmabadi and I investigated the issue and here's what we found:
1. C# LSP creates request handlers which operate on various flavors of the C# solution. For EnC there was recently a change to [migrate diagnostic understanding to the source generated enabled solution](https://github.com/dotnet/roslyn/pull/52537). These changes weren't reflected on the LSP front when creating `RequestContext`'s / handlers.
2. SourceGenerators generate content in relative file paths whereas LSP speaks absolute FilePaths. Meaning, even if the above was fixed looking up an LSP Uri/filepath wouldn't actually locate a SourceGenerated file due to the path mismatch.
3. (This is longer leaded) We can fix the first two issues via code changes in Roslyn but the third is a fundamental design issue related to the Razor compilers dual generated output modes.

Investigatory Razor issue: https://github.com/dotnet/aspnetcore/issues/32188

**Comment by tmat** [comment]
Re [2]: suggestions that would address this were made in #51998. Another [suggestion in a comment] on this issue would also imo result in more consistent compiler/msbuild interface regarding the directory to place generated files under (https://github.com/dotnet/roslyn/issues/51998#issuecomment-804232378)

**Comment by NTaylorMullen** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/53027
