### ISSUE TITLE
IDE0079 doesn't show up in VS

### ISSUE THREAD

**Issue by geeknoid** [dotnet/roslyn#52984]
**Version Used**: 

Using VS 16.9.4

**Steps to Reproduce**:

1. Create a project using the Microsoft.Analysis.CSharp.CodeStyle and Microsoft.Analysis.CodeStyle analyzers
2. Look at the project dependencies and expand the analyzer nodes to see all diagnostics they support
3. IDE0079 is not shown.

**Expected Behavior**:

All diagnostics produced by the analyzer should be displayed.

**Actual Behavior**:

The diagnostic is not displayed, while other diagnostics are.

I discovered this as I wrote a tool that needs to iterate available diagnostics. I then wrote some code that produced IDE0079 and was surprised not to see this diagnostic in my tool's output. I then checked VS and found that VS also doesn't show the diagnostic. But the diagnostic is reported by the IDE.

![image](https://user-images.githubusercontent.com/22780957/116329946-47abe700-a781-11eb-8472-17f60805664d.png)

**Comment by CyrusNajmabadi** [comment]
i believe this analyzer is special (and is in effect a meta-analyzer).  For example, we wouldn't want to eb able to suppress the diagnostic saying that a diagnotic was unnecessary.    tagging @mavasani to confirm if this behavior is intentional.

**Comment by mavasani** [comment]
This is a known limitation. IDE0079 is a special IDE only analyzer that needs to know diagnostics reported from rest of the analyzers to operate. As there is no compiler support for such an analyzer, it has been implemented as an IDE only concept. We did have a work item tracking potentially adding compiler support for such special analysis, but that is unlikely to be taken forward.

**Comment by geeknoid** [comment]
Oh, so I can't have this fail my CI build? Too bad.

The fact it's not showing up in the normal places is confusing. The fact it is implemented in a special way doesn't seem like it should affect whether it is made visible in the VS UI (so folks can configure it).

**Comment by sharwell** [comment]
It's fine for this diagnostic not to show up in the build, but if we special-case it for IDE scenarios we should also special-case it for the Analyzers node.

**Comment by jinujoseph** [comment]
Assigning to @jmarolf as polish work to editorconfig integration

**Comment by Youssef1313** [comment]
I think not showing it in Analyzers node is the correct behavior. It's more confusing if I see IDE0079 in Analyzers node for the CodeStyle package but the analyzer isn't exported in that package.

I'd expect to see a "Features (IDE-only)" node under analyzers.
If CodeStyle package is referenced or EnforceCodeStyleInBuild is enabled, the new "Features" node should exclude analyzers common between CodeStyle and Features.

@mavasani @jmarolf @sharwell Thoughts?

**Comment by CyrusNajmabadi** [comment]
@jmarolf can we close this out?  or does this need to stay?

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of response.
