### ISSUE TITLE
Roslyn incorrectly marks cast as redundant when boxing value-type values

### ISSUE THREAD

**Issue by Washi1337** [dotnet/roslyn#52990]
**Version Used**: 
Tested on both:
- Visual Studio 2019 Community 16.9.4
- Sharplab set on `main (27 Apr 2021)`

**Steps to Reproduce**:

1. Create a new Console project.
2. Paste in the following code:
```csharp
using System;

// Notice result type is always System.Int32, Roslyn compiles this using conv.i1.
static object Test1(int x, int y) => y switch 
{
    0 => x,
    1 => (sbyte) x,
    _ => throw new ArgumentOutOfRangeException()
};

// Notice Roslyn saying cast is redundant here, but Roslyn compiles this using box, which
// results in different behaviour, and thus the cast is not redundant.
static object Test2(int x, int y) => y switch 
{
    0 => (object) x, 
    1 => (sbyte) x,
    _ => throw new ArgumentOutOfRangeException()
};

Console.WriteLine(Test1(0, 1).GetType());
Console.WriteLine(Test2(0, 1).GetType());
```

**Expected Behavior**:
No suggestions regarding type casts as introducing the cast results in different behaviour.

**Actual Behavior**:
Roslyn reports the cast to object is redundant, but doing so results in different behaviour in the end.

![unknown](https://user-images.githubusercontent.com/3613449/116433641-fe739a00-a849-11eb-800f-451a0b30f47e.png)

Repro in sharplab [here](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKEIHpiACAOQHsEoBjAUzICcGBnAVxQTIQE8ADkyhsyEFAHcIfURhwA6AJIwEAZixwyAJSpsUfGGTpUwA1O14ALEWQwAGI1RgA3eVAWE5ANjJVgAKwY6HgAVdgQcAApYHgAPTRiyPgBKMgBeAD4ksjYJKAQ6SzJCAG9CMgqyB0yyePLKnHSsyLZgPgQGVLqCSrIAfSarZioJMhgGUYBBZgBzDjAGFQB5DgQlgDMtCBgZhgBRWMYBWidI5MIAXwBuQhJyalpGbV19QzZpWBmjCDYeG1YACYcGAA7Y8SwMViaYCrZ56AyOUzmUQIayyBzAKjxMgSayFO4sdhcBCiWBkAFQdbrSGLHjABiWCDOKBUDjMTTbAFWDgoiHfX5kGwwGiEoEgsHyTw4Hx+QLBMhhX5YaIqWoJVUpQZ8HJ5ApFUr1CrVZqyoIILqaQ1kRo1FptDoWq0DGqo4ajcZTWbzWkrNabba7A5HE4wM6XG5EAhyACckUVEUidk0OGS8gA4gwECFBAwzskIzG4+FlUnramM1mc3mrkA) to showcase that it indeed results in different behaviour.

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/50043 and https://github.com/dotnet/roslyn/issues/52524.

**Comment by CyrusNajmabadi** [comment]
@jcouv

**Comment by jaredpar** [comment]
Duping to ##50043
