### ISSUE TITLE
SyntaxFactory.NameOfExpression(...) should have an overload that doesn't require "nameof" as first argument

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#53]
I'm generating code that includes nameof expressions and was very surprised that SyntaxFactory.NameOfExpression took two parameters: "nameof" itself, and then the expression that goes in as the argument of 'nameof'. Since the nameof expression is always going to be "nameof", should there be an overload of this method that will specify this automatically?

**Comment by mattwar** [comment]
Yes.

**Comment by sharwell** [comment]
:+1:

**Comment by jaredpar** [comment]
There is no longer a `NameOfExpressionSyntax` element.  Instead that expression is represented as an `InvocationSyntaxExpression`.  Here is the commit which made this change. 

36bdd5390f8184df51451b21afeac56f35f1a854
