### ISSUE TITLE
Changes to additional files sometimes don't lead to diagnostic re-computation in IDE

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#530]
Repro steps:
1) Open Roslyn.sln in RoslynDev hive after building Roslyn
2) Open PublicAPI.txt file from Workspaces.Desktop project
3) Open FileTextLoader.cs and wait for few minutes (so that its diagnostics are computed)
4) Delete the 4 entries for FileTextLoader at the top of PublicAPI.txt
5) Verify that squiggles show up in FileTextLoader for RS0016
6) Go back to PublicAPI.txt and undo the changes in step (4)

Expected: Squiggles in FileTextLoader.cs go away.
Actual: Squiggles in FileTextLoader.cs never go away

**Comment by srivatsn** [comment]
I have a bug tracking this internally reported by @tmeschter. I'll resolve that and use this item to track the issue.

**Comment by mavasani** [comment]
@srivatsn probably someone else should verify the fix? I did add a test that failed prior to this change though..

**Comment by srivatsn** [comment]
Yes I'll verify it. Thanks
