### ISSUE TITLE
It looks like LocalRewriter.VisitInterpolatedString method assumes that overload resolution necessary picks a Format method that returns string 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#53005]
```
                var stringType = node.Type;
                result = _factory.StaticCall(stringType, "Format", expressions.ToImmutableAndFree(),
                    allowUnexpandedForm: false // if an interpolation expression is the null literal, it should not match a params parameter.
                    );
```

**Comment by 333fred** [comment]
@AlekseyTs can you clarify the part that is assuming that `string.Format` returns a `string`? It looks we already have tests for when `string.Format` returns an incorrect type: https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs#L1029-L1058. Later on in lowering, we attempt to convert the result to the expected type of the node, which should cover this case.

**Comment by AlekseyTs** [comment]
@333fred Thank you for confirming that wrong return type is handled.
