### ISSUE TITLE
Inline Temporary Variable generates invalid code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Inline-Temporary-Variable-generates-inva/1329454)._

---
[severity:It bothers me. A fix would be nice]
See the screen shots.

I am getting a Message IDE0059, so I go to the code and choose the Refactor "Inline Temporary Variable" and the preview for the code it's going to generate would be completely wrong.

---
#### Feedback Bot on 2/3/2021, 07:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/5/2021, 00:17 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
### Steps to reproduce

```csharp
private static void Entry()
{
    string value = null;
    value = "";
    string value2 = Method(value);
}

private static string Method(string x)
{
    return x;
}
```

1. Place the caret on the definition of `value`
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd>
3. Invoke **Inline temporary variable**

### Expected result

There is no refactoring presented, since the value `null` is never used.

### Actual result

```csharp
private static void Entry()
{
    string value = null;
    value = "";
    string value2 = Method(null);
}

private static string Method(string x)
{
    return x;
}
```

**Comment by Youssef1313** [comment]
Related: https://github.com/dotnet/roslyn/issues/36788

**Comment by CyrusNajmabadi** [comment]
This is intended behavior based on requests that we still allow the refactoring in cases like these. The refactoring will also show a message in the ui stating that we can't inline the value everywhere so it will be necessary to manually fixup things afterwards.

**Comment by sharwell** [comment]
> This is intended behavior based on requests that we still allow the refactoring in cases like these.

I have no objection to keeping the refactoring in some cases that have ambiguous interpretations. However, this is not one of those situations: the value `null` is never used, so we should not be trying to insert it.

**Comment by CyrusNajmabadi** [comment]
As mentioned in other issues, I think we should consider just renaming this feature. I have never liked the term 'inline temporary'. I think it should be: 'replace usages with declaration value' or '... With initial value' to be clearer about what is going on.

**Comment by sharwell** [comment]
> The intent of the feature was always to take the initial value and to insert that in place of the variable at all rvalue locations.

This might have been the way it was implemented, but it doesn't make sense from a feature or code flow perspective. Given we are actively working on tools to make the current feature work with an understanding of the code flow rules of the language, it would be preferable to use that instead of just ignoring the language rules and inserting random values for variables.

**Comment by CyrusNajmabadi** [comment]
i woudl nto be opposed to potentially inlining the last full write to the varaible, if the same value is provided along all codepaths prior to the read.  What would you have us do in cases where tehre is no single value though?

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of movement.
