### ISSUE TITLE
GenerateOverride should sometimes add `where T : default` constraint

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#53012]
As the screenshot below illustrates, if you start with a virtual method `void M<T>(T? t)` and generate an override for it in some other type, the generated override doesn't have any type parameter constraints, but that results in compilation errors.
We should generate a `where T : default` constraint, which tells the compiler that `T?` in the override doesn't mean `System.Nullable<T>`.

![image](https://user-images.githubusercontent.com/12466233/116503945-1f4ce700-a86c-11eb-94dd-debf4a56b85f.png)

**Comment by Youssef1313** [comment]
Not sure if https://github.com/dotnet/roslyn/issues/53003 is a duplicate.

**Comment by Youssef1313** [comment]
Working on this.
