### ISSUE TITLE
Implicit type is Nullable when creating a new Dictionary instance with initializer

### ISSUE THREAD

**Issue by sereGkaluv** [dotnet/roslyn#53016]
**Version Used**: 
.NET SDK (gemäß "global.json"):
 Version:   5.0.201
 Commit:    a09bd5c86c

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

**Steps to Reproduce**:

1.  Create a new Dictionary with initializers using implicit type:
``var example = new Dictionary<string, string>
{
     { "key": "value" }
}``

**Expected Behavior**:
`var example` should be of type `Dictionary<string, string>`

**Actual Behavior**:
`var example` is of type `Dictionary<string, string>?`

**Workaround**:
1. Use of explicit typing solves the issue:
``Dictionary<string, string> example = new ()
{
     { "key": "value" }
}``

**Comment by huoyaoyuan** [comment]
This is by design. `var` is always inferred as nullable type with non-nullable state. This is for compatibility of:
```csharp
var xxx = new X();
xxx = null;
```

**Comment by ThomasMader** [comment]
Wouldn't it be better to turn it around and make the non nullable case the default because it gives more guarantees?
If the nullable is really wanted in some cases an escape could be provided like this I imagine:

`var? xxx = new X();`

But since this is how it is currently I guess the ship to change that has already sailed but I would still be interested in knowing if there might be other reasons I don't currently see.

**Comment by huoyaoyuan** [comment]
`var?` was discussed in the language design. I didn't recall the actual design note, but generally they decided to track the state of each variable at each position. This can cover more scenarios than `var?`, and solves this scenario for free.

**Comment by Youssef1313** [comment]
> I didn't recall the actual design note

https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-12-18.md#var

**Comment by RikkiGibson** [comment]
Thanks for filing the issue. As @huoyaoyuan and @Youssef1313 have indicated the observed behavior is by design.
