### ISSUE TITLE
Source Generators: Allow access to code formatting based on .editorconfig

### ISSUE THREAD

**Issue by canton7** [dotnet/roslyn#53020]
I'm writing a source generator, where I'm adding properties and fields to a user-defined class.

I'd like the names of those properties/fields to respect any [naming rules](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules) the user has set up in their .editorconfig: whether they should be pascal case / camel case / etc, start with a particular prefix, and so on. I'm aware that I can add `// <auto-generated/>` to the top of a SG'd file to squash any style-related warnings, but the concern is more that the user is going to be interacting with these generated members, and I'd like them to follow the user's preferred style where possible.

I can certainly use MSBuild properties / analyzer config properties to let the user specify this stuff for my SG in a way that my SG can consume, but this feels like I'm re-inventing things that .editorconfig already does, plus it's extra work for the user.

Ideally, I'd like an API to format a particular code snippet in accordance with the user's naming rules, and return the changes made (as I'll need to generate further code which refers to those corrected names). Unfortunately, all of the APIs related to .editorconfig naming styles are up at the IDE layer, and so are out of bounds for SGs.

@CyrusNajmabadi [suggested](https://gitter.im/dotnet/roslyn?at=608ad0cdbdc0bc32e6269a3e) that I open an issue here and tag @jaredpar and @333fred.

Thank you!

**Comment by mgravell** [comment]
Related, and "seconded": https://stackoverflow.com/questions/67351269/can-a-roslyn-source-generator-discover-the-ides-spacing-etc-preferences

**Comment by mgravell** [comment]
Just to cross-link a section from this [related answer](https://stackoverflow.com/a/67373722/23354) from the post above:

> My suggestion would be until we build in support for this, just don't worry about it, and feel free to direct user complaints to this or the bug.

**Comment by jinujoseph** [comment]
cc @jasonmalinowski for info

**Comment by CyrusNajmabadi** [comment]
We are not likely to do this.
