### ISSUE TITLE
OutVariableArgumentProvider does not support type style preferences

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#53056]
Identified by @Youssef1313 in https://github.com/dotnet/roslyn/pull/53049#discussion_r623641440. The following test shows the expected behavior:

https://github.com/dotnet/roslyn/blob/2f464cb8b6fb5258772f87c8b2e8e8c1861f9859/src/EditorFeatures/CSharpTest/Completion/ArgumentProviders/OutVariableArgumentProviderTests.cs#L82-L112

**Comment by Youssef1313** [comment]
@sharwell @jinujoseph This wasn't labeled. Can you label it for better tracking?

**Comment by sharwell** [comment]
Help wanted, but blocked on #53049

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
