### ISSUE TITLE
Improve sig info, error message formatting when working with complex generic code

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#53061]
Working with types that combine generics and tuples is cumbersome. The IDE does not help much at all.

```C#
using var _ = PooledDictionary<string, ArrayBuilder<(ManagedActiveStatementDebugInfo info, SourceFileSpan span, int ordinal)>>.GetInstance(out var updatedSpansByDocumentPath);

var x = updatedSpansByDocumentPath.ToImmutableDictionary(
     keySelector: 
```

Can we structure the signatures better using line breaks and indentation?

Sig info:
![image](https://user-images.githubusercontent.com/41759/116741619-33e3c900-a9ab-11eb-970f-92689046955d.png)

Hover:
![image](https://user-images.githubusercontent.com/41759/116742542-59bd9d80-a9ac-11eb-81ac-4b8dc7f35e8b.png)

Types in diagnostic not colorized and the error is hard to read with the long type names in the middle of the error message:
![image](https://user-images.githubusercontent.com/41759/116742724-a43f1a00-a9ac-11eb-884c-c96ccec146d9.png)

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/29949.

**Comment by jinujoseph** [comment]
Need a proposal before bringing to design meeting

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi You fixed this issue in https://github.com/dotnet/roslyn/pull/56025, so it should be closed now

**Comment by CyrusNajmabadi** [comment]
Works for me. Thanks!
