### ISSUE TITLE
Optimize the codegen of lambdas to the same as local functions so that JIT can inline them

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#53079]
**Version Used**: .NET 6.0 Preview 3

Currently a lambda cannot be inline by RyuJIT, but a local function can. Optimizing the codegen to the same way as local functions can really help with performance.

**Steps to Reproduce**:

Test code:
```csharp
using System;

namespace InlineTest
{
    public class Program
    {
        public static void Main()
        {
            var number = new Random().Next();
            LocalFunction(number);
            LocalLambda(number);
        }

        public static void LocalFunction(int number)
        {
            bool Pred() => number > 5;
            Console.WriteLine(Pred());
        }
        
        public static void LocalLambda(int number)
        {
            Func<bool> Pred = () => number > 5;
            Console.WriteLine(Pred());
        }
    }
}
```

RyuJIT asm with `TieredCompilation=false`:
```asm
; LocalFunction(number);
mov     esi,eax
cmp     esi,5
setg    cl
movzx   ecx,cl
call    System.Console.WriteLine(Boolean)

; LocalLambda(number);
mov     ecx,esi
call    InlineTest.Program.LocalLambda(Int32)
```

Same result between static lambda and static local function.

Roslyn codegen diff:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQhAdgIYC2MAzgA6lgwAEAksQDYCWxMAKtQC6EA3oUZjGGAMwSsEnAHZR4kQXFqZWJesYrt2gG6kojYgFdywGMYC8JmAHdGAJVLEAJhHIAKAJQA6ADkYBH5fAG4tPTEAGQgwUjYMAFZ+DghiLzMLKx8I1SjxWPi2aIpgN1JM80soXMi1AF9CevEpOSQJFEYihOTU9K8ufhNqnJaxXQKxYAgINkYABVg3X0ZrAD4R7ONNpLypsQwcAE4vJZgVnzr87Sab9XGJaSOOjC6ekrKKweJhrJqfI9JlNkgAeGZzTbnNxrRirDZbGqMXb7A5HU7Q3zXKJ3RqEBpAA

**Comment by alrz** [comment]
`Func<bool> Pred = () => number > 5;`

This explicitly creates a delegate type. I don't think after this point runtime has any information to inline it.

**Comment by hez2010** [comment]
> I don't think after this point runtime has any information to inline it.

But if Roslyn can compile lambdas to local functions directly, runtime will be able to inline it.

**Comment by alrz** [comment]
Actually that's what the compiler do but it's immediately converted to the delegate type you specified.

```cs
bool lambda() => number > 5;
Func<bool> Pred = lambda;
Console.WriteLine(Pred());
```
It may be possible to eliminate the variable in this particular case, but I don't think the spec allows to skip delegate allocations. And even if it does it rarely helps. There's no point to allocate a delegate and immediately call it.

**Comment by CyrusNajmabadi** [comment]
This is currently required by the language.  It is required (and observable) that a new delegate instance is created.  So we can't change codegen here without breaking that.  This is one of the reasons that local functions were created in the first place.  Because it allows the compiler to generate this sort of pattern because it doesn't have to abide by the existing rules around lambdas.

**Comment by bernd5** [comment]
@CyrusNajmabadi how is it observable?

**Comment by CyrusNajmabadi** [comment]
@bernd5 you could literally store the delegate and then do a reference equality check against the next instance you see. The spec currently requires these be distinct instances and this would change that. It's easily possible code has been written that depends on the old behavior.

**Comment by bernd5** [comment]
@CyrusNajmabadi thanks for your answer.
