### ISSUE TITLE
Re-architect how settings work in Roslyn

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53096]
@Pilchie 
1: would require us to re-architect how settings work in roslyn so there are not three places.  Should we file a bug around this?
2: filed issue https://github.com/dotnet/roslyn/issues/16599

_Originally posted by @jmarolf in https://github.com/dotnet/roslyn/issues/16512#issuecomment-273614834_

**Comment by Youssef1313** [comment]
Related to: https://github.com/dotnet/roslyn/issues/53095.

**Comment by sharwell** [comment]
@Youssef1313 Source generation and/or custom analyzers could be viable for this, but we'd need to start with a clear design for the in-scope goals.

**Comment by CyrusNajmabadi** [comment]
This issue is too vague to be actionable.
