### ISSUE TITLE
Change signature should cascade record's primary constructor parameter changes

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53091]
See skipped test added in https://github.com/dotnet/roslyn/pull/53052 (https://github.com/dotnet/roslyn/pull/53052/commits/df2d61598101338cac8b42aa5068167730460787#diff-48198499e945c2b46e3c7e43e1f5652afefdc92104c37359da4ae6a3603ff627R415-R434)

**Comment by CyrusNajmabadi** [comment]
CLosing out due to lack of broader feedback on this topic.
