### ISSUE TITLE
Respect `visual_basic_style_prefer_simplified_object_creation` by simplification/reduction

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53094]
Should `visual_basic_style_prefer_simplified_object_creation` be respected by `VisualBasicVariableDeclaratorReducer`:

https://github.com/dotnet/roslyn/blob/bc98ed946162622c7564607d276c06928033464e/src/Workspaces/VisualBasic/Portable/Simplification/Reducers/VisualBasicVariableDeclaratorReducer.vb#L45

When/if this is done, [IDE0140](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0140) docs page could be updated to mention that this option is respected in some situations (the update could be similar to https://github.com/dotnet/docs/pull/22516).

**Comment by CyrusNajmabadi** [comment]
Yes.  it would be fine to respect this.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I assume closing the issue meant "it's fine to respect the option, but not necessary given zero customer feedback about that", is that right?

**Comment by CyrusNajmabadi** [comment]
Yup!
