### ISSUE TITLE
[scriptcs] Extensibility around DirectiveParser

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#531]
In scriptcs we like to have custom directives such as `#load` or anything really that a user plugs in (i.e. `#gist` or `#http`).

However the directive parser treats them as errors because it operates entirely around a switch statement https://github.com/dotnet/roslyn/blob/03e30451ce7eb518e364b5806c524623424103e4/src/Compilers/CSharp/Portable/Parser/DirectiveParser.cs#L44

Would be nice if we could provide a whitelist of allowed directives to the parser, or if that's not viable, at least be able to suppress these errors from the parse options object (perhaps this is already possible now - but I can't find a way to do it; in that case I would really appreciate some guidance).

**Comment by filipw** [comment]
here's the problem illustarted in a screenshot - Roslyn thinks #load is a bogus language construct
![screenshot 2015-02-15 19 07 49](https://cloud.githubusercontent.com/assets/1710369/6646743/491777d2-c9c8-11e4-8b38-cb938b449ef9.png)

**Comment by tmat** [comment]
We will support #load in the language. 

I don't think we want to let the user extend the language via custom directives. Why do you need  directives like #gist, #http as apposed to exposing the same functionality via (top-level) method calls? 

What is the semantics of #gist and #thhp?

**Comment by RichiCoder1** [comment]
Both `#gist` and `#http` are essentially `#load`, except with the restriction that they have a valid URI for identifying their resource, and the resource is in a valid format such that it can be loaded as a cs(x) file like `#load`. Or at least that's my understanding. `#gist` especially could be odd since it's structured in a very specific way, and could have multiple "files".

How could a top-level method imitate this behavior?

**Comment by tmat** [comment]
If they are variations of #load or #r they should just be #load and #r. The host is free to interpret the argument of these directives as necessary. 
For example, 
```#r "Foo.2.5.1.nuget"``` can add metadata references from the specified nuget package. 
```#load "https://whatever"``` can download the target file
```#load "gist://RichiCoder1/6a20333202a3003e5d36"``` can download a gist.
etc.

**Comment by glennblock** [comment]
@tmat that's an interesting idea. 

scriptcs however currently does allow custom directives and this is deliberate. It is one of our core extensibility points / allows scriptcs to be more useful for specific scenarios.

**Comment by glennblock** [comment]
Plugging in custom directives is an opt-in thing. You basically have to install a global module that contains the handler for those directives. Because it is opt-in, we see no harm in supporting it. It allows people to experiment with ideas that could potentially feed into the platform in the future.

**Comment by filipw** [comment]
absolutely, I don't think a built in `#load ` can cover every conceivable scenario, even when extensible. Just from the top of my head, for example - what if the HTTP call pulling the code requires basic authentication credentials? What if the `#load` requires a custom media type to be requested from the server? What if I want some code to be pulled from a custom DB connection? I know a lot of people use custom directives for validation purposes - being able to introduce different semantics of preprocessor directives allows you to introduce custom logic when it comes to validating which assemblies are allowed to be loaded into your script execution context. There are many more examples like these.

Now, you mention an extensible or customizable `#load` and `#r` as a potential way to cover all of these scenarios - but I think this is a slippery slope. Why? How do I determine what would the behavior of a the directive be in my environment? Will I need to run the script do discover it? How do I know that executing my script in different environments will yield the same results? Is a `#load` on my machine equal to `#load` on yours? These can lead to potentially disastrous problems in script executions.

Finally, we need to draw a boundary between scriptcs value proposition and the actual semantics of the Roslyn scripting model. Think of scriptcs as a superset of the lower level scripting experience offered by the Roslyn scripting APIs. All we ask for in this case is a way for the Roslyn language services to not fall apart given some of the specifics of the scriptcs experience (such as, in this case custom directives) - whether it is via whitelisting, custom compilation options, replacing some internal services, or through error suppression, or any other way.

**Comment by filipw** [comment]
ah one more thing - we discussed some time ago  it might be necessary to use comments to indicate custom directives - so stuff like `\\#foo`

This will surely solve the problem here, but ideally if there was some way to support a custom directive it would be the best :smile: 

kind of like right now you are able to pass in pre processor symbol names to `CSharpParseOptions`.

**Comment by ManishJayaswal** [comment]
We want to have one dialect of C# script and should not be providing extension points to extend to Language.

**Comment by RichiCoder1** [comment]
@ManishJayaswal @tmat Is the `#load` extensibility still going to present?

**Comment by ManishJayaswal** [comment]
@RichiCoder1 we do expect to have an implementation of #load which will let you load other scripts.

**Comment by tmat** [comment]
@RichiCoder1 Yes, the language doesn't specify the meaning of the #load argument. It's up to the host to interpret it. We'll provide guidelines for the hosts and default implementation, so that it's easy to write host-agnostic scripts.

**Comment by RichiCoder1** [comment]
Awesome! Can't wait to see it :)

**Comment by tmat** [comment]
The extension point is actually already there ;) 

http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,3c3038cbfa59e230,references

**Comment by tmat** [comment]
And in ScriptOptions when using Scripting APIs:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/ScriptOptions.cs,b3eba6cc62935754,references

**Comment by RichiCoder1** [comment]
Good to know.
