### ISSUE TITLE
Can anyone contribute a different language?

### ISSUE THREAD

**Issue by spoiledsport** [dotnet/roslyn#53100]
I am trying to find out if there is any possibility to contribute another language : java. I have ported some of the C# syntax tree components, but would love to see this move forward somewhat. Is that an accepted commit? If there a process to add a new language?

**Comment by Youssef1313** [comment]
If you mean to add a Java compiler inside Roslyn, unfortunately, I don't think this would be accepted. However, I think you can do that in your own fork, or even start it as a new project (you may find [Minsk playlist](https://www.youtube.com/playlist?list=PLRAdsfhKI4OWNOSfS7EUu5GRAVmze1t2y) useful for that - Here is the [GitHub repository](https://github.com/terrajobst/minsk) for Minsk too).
