### ISSUE TITLE
Hot Reload fails with .NET MAUI (Android emulator scenario)

### ISSUE THREAD

**Issue by LyalinDotCom** [dotnet/roslyn#53111]
Using the test project we discussed in the meeting .NET Hot Reload fails for any edits when running our project against an Android emulator. I am not saying its Android emulator specific even but that's just a key test case that is failing right now.

By failing I mean any edit (even a plain text string change in a regular method) will show the rude edit dialog. No errors appear in the error window, output and there are no squiggles so I am at a loss to what is going on.

**Comment by tmat** [comment]
Fixed by https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/342411
