### ISSUE TITLE
Quick Info for <code> XML doc tag should not remove CDATA block

### ISSUE THREAD

**Issue by PeterMacej** [dotnet/roslyn#53135]
**Quick Info strips out CDATA block completely.**

The &lt;code&gt;XML doc elements often contain a CDATA block so it's not necessary to escape special XML characters, such as &lt;, &gt; and &amp;. However, these blocks are completely ignored in Quick Info.

**Code example:**

``` C#
/// <summary>
/// The code example:
/// <code><![CDATA[
/// if (i < 5 && i > 0)
/// {
///     var list = new List<string>();
/// }
/// ]]>
/// </code>
/// This was the example.
/// </summary>
public void Method1()

```

**Actual result**

![obrázok](https://user-images.githubusercontent.com/10990713/116974347-4c5f2680-acbe-11eb-95ad-ace03be25590.png)

**Expected result**
Quick info shows the contents of CDATA.

This is related to #37503

**Comment by Youssef1313** [comment]
May or may not be related to https://github.com/dotnet/roslyn/issues/22431
