### ISSUE TITLE
Import and export window shows a magic number "201"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53149]
Tools > Imports and export settings > Export selected environment settings:

![image](https://user-images.githubusercontent.com/31348972/117068851-13f63180-ad2c-11eb-9377-0eeefb219cee.png)

Not sure if it's roslyn-related. Feel free to close and route to the appropriate team if it's not in Roslyn.

**Comment by huoyaoyuan** [comment]
It should be missing resource string in VS. VS uses x0x numbers for identifying them.

**Comment by Youssef1313** [comment]
So this is an internal implementation right? @jinujoseph Can you route this to the correct team? Thanks.

**Comment by jinujoseph** [comment]
following up to find the right owner for this.

**Comment by jinujoseph** [comment]
[Routed ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1323515)to azure data lake team
