### ISSUE TITLE
Roslyn cannot understand nullability assign with control flow

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#53176]
**Version Used**: 
March 3 2021

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4GIB2BXANliwtwAEcaeBAsAFAACATAIxXUDMhdhAwoQN5WH9tW1ACyEAsgApgAe2lZCAYwCUPPgPXV6ABgD8hCIQC8hTDgDca9fwCWAM0ITllq70pX3+o4QBE3i248AX2d1EIE7BycA91cPK00tQmAvCH844OjCDMCgA===

```cs
#nullable enable
using System;
public class C {
    public void M(bool c) {
        string? a = null;
        if (c)
        {
            a = "";
        }
        
        if (c)
        {
            string b = a; // warning CS8600: Converting null literal or possible null value to non-nullable type.
        }
    }
}
```

**Expected Behavior**:
No warning

**Actual Behavior**:
Warning

**Comment by RikkiGibson** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/36927#issuecomment-508595947

**Comment by jaredpar** [comment]
This behavior is "By Design". The compiler does not track the nullable state of variables in relationship to other variables. That is it looks only at the behavior of `a` here when deciding if it's nullable or not, it does not consider how `c` is related to it.
