### ISSUE TITLE
Suppress warrning for next line only

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53186]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suppress-warrning-for-next-line-only/1400736)._

---
C++ can suppress warnings for the next line only, which saves me from re-enabling the warning later. C# could use this.

---
#### null on 4/19/2021, 04:57 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jaredpar** [comment]
Closing as this needs a lot more information to be actionable. For example what does "next line" mean here? Does it mean the next statement, next physical line, etc ... Also what would the syntax be for such a change? 

To move this forward we would need a more complete proposal and likely this is a better fit for the csharplang repository as it's language design impacting.

**Comment by brunom** [comment]
Hi Jared, thanks for taking a look at my suggestion. I'm not sure where to report it. I initially did as VStudio feedback and it was moved here.

Regarding the syntax, I'm not an expert.  I just use it in C++ and miss it in C#. Maybe the C++ syntax could serve as a starting point.
