### ISSUE TITLE
Flaky test: CSharpGenerateTypeDialog.CSharpToBasic

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53194]
See https://github.com/dotnet/roslyn/pull/53110#issuecomment-832902575.

Note: I believe I also met this test failing once before, so the above comment isn't the first time.

**Comment by Youssef1313** [comment]
@jaredpar Anything needed here to get runfoaapp tracking this?

**Comment by sharwell** [comment]
For some reason, the lightbulb expanded before compiler errors were calculated:
![image](https://user-images.githubusercontent.com/1408396/117208829-6fff9b00-adaa-11eb-81be-e62ec871529d.png)

**Comment by sharwell** [comment]
Only one failure in the past 30 days, which occurred because the light bulb did not appear at all.

**Comment by CyrusNajmabadi** [comment]
Closing out as this has not failed in ages and is not skipped.
