### ISSUE TITLE
Suggested "Use coalesce expression" results in broken code

### ISSUE THREAD

**Issue by gjschoneveld** [dotnet/roslyn#53190]
**Version Used**: 
Visual Studio Version 16.9.4

**Steps to Reproduce**:
1. Create a console project and enter the following code:
```
namespace TestSimplification
{
    class Program
    {
        class A { }
        class B { }

        static void Main(string[] args)
        {
            var a = new A();
            var b = new B();

            // IDE0029: Null check can be simplified
            object x = a != null ? a : b;
        }
    }
}
```
2. Hover your mouse above the first a in the line with 'object x = ...'
3. Click the "Use coalesce expression"
4. The line is replaced with:
```
object x = a ?? b;
```

**Expected Behavior**:
Line transformed in working code. Or no suggestion to improve it.

**Actual Behavior**:
CS0019: Operator '??' cannot be applied to operands of type 'Program.A' and 'Program.B'

**Comment by CyrusNajmabadi** [comment]
@jcouv  @jaredpar is this intended?  does target typing only work for `?:` and not `??` as well?

**Comment by CyrusNajmabadi** [comment]
If so, is there some api we can use to determine that this will be an issue?  calling into the spculative semantic model here is ok.  Thanks!

**Comment by RikkiGibson** [comment]
>  does target typing only work for ?: and not ?? as well?

Correct. `??` doesn't have target typing.

**Comment by CyrusNajmabadi** [comment]
> Correct. ?? doesn't have target typing.

Ick.  Well that's unfortunate.  @RikkiGibson is there a way we can tell if target typing was used, and if it would not valid in this sort of case?  Is there an API the compiler exposes for this?

**Comment by RikkiGibson** [comment]
If you want to know if a `?:` expression was target typed, I believe you can get its conversion and check `Conversion.IsConditionalExpression`.

I'm not sure what the best way is for something more general purpose.. e.g. speculatively binding a `??` and realize it won't convert, so don't offer the refactoring, for example.

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson thanks!  that sounds like what we need.  I'll see if that's sufficient fo ra fix here.  THanks! :)
