### ISSUE TITLE
Avoid multiple new lines has odd interaction

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#53191]
**Version Used**: Version 16.10.0 Preview 3.0 [31303.14.main]

**Steps to Reproduce**:

1.  Add multiple new lines to trigger suggestion
2.  Place cursor in second line

**Expected Behavior**:
Ctrl+. opens lightbulb suggestion
Hovering and clicking lightbulb icon opens lightbulb menu

**Actual Behavior**:
Lightbulb menu is not opened when invoked from a cursor on the second line where green squiggle is.

![MultiNewlines-subtitles](https://user-images.githubusercontent.com/8293542/117197011-1a23f680-ad9c-11eb-859e-5d948949120d.gif)

**Comment by jmarolf** [comment]
@CyrusNajmabadi can we expand the selection scope here?

**Comment by CyrusNajmabadi** [comment]
I cannot repro this @kendrahavens can you supply teh code you were running, and show which diagnostic you're actually getting.  The way this feature *should* work is that you just get the diagnostic squiggle on the first blank line.  So this:

![image](https://user-images.githubusercontent.com/4564579/118201683-de78d480-b40c-11eb-9001-3f8d04c22b55.png)

So i have no clue where the second squiggle is coming from.  Maybe a different tool?

**Comment by kendrahavens** [comment]
Oof, that's weird. In a brand new project I'm also not getting the second squiggle. My machine may have PM-disease. I'll close unless I can get a minimal repro. Thanks for checking, Cyrus!
