### ISSUE TITLE
WPF app fails to Hot Reload after a change in a method with odd "does not exist in current context" error

### ISSUE THREAD

**Issue by LyalinDotCom** [dotnet/roslyn#53216]
1. Clone repo: https://github.com/Microsoft/WPF-Samples
2. Update global.json file to match your .NET version (I targeted a .NET 6 preview)
3. Open solution under: WPF-Samples\Sample Applications\WPF Application Samples.sln
4. Build the solution. It should build okay, some projects didn't load for me but that wasn't an issue
5. Set startup solution as PhotoViewerDemo
6. Click on a picture in the app to open the popup with just one photo in it
7. Open PhotoViewer.cs, change BlackAndWhite method, make a simple change that should be supported
8. Apply changes

**This is what I got:**

Error	CS0103	The name 'ViewedPhoto' does not exist in the current context	PhotoViewerDemo	C:\src\WPF-Samples\Sample Applications\PhotoViewerDemo\PhotoViewer.cs	59	Active

This is not expected, the line of code with ViewedPhoto wasn't even something that I changed and it does exist.

![image](https://user-images.githubusercontent.com/2363526/117240691-44020b00-ade6-11eb-97ef-9c6e95a10198.png)

**Comment by davidwengier** [comment]
This doesn't repro for me on Version 16.10.0 Preview 3.0 (public), using .NET 6.0.100-preview.3.21202.5, under F5.

@LyalinDotCom Is this a 100% repro? Can you share more details? Perhaps a recording?

**Comment by davidwengier** [comment]
Closing this out, feel free to reopen if it re-surfaces.
