### ISSUE TITLE
Iron out inconsistent usages and use simplified overloads in NewLineUserSettingFormattingRule

### ISSUE THREAD

**Issue by mrahhal** [dotnet/roslyn#53218]
In the [NewLineUserSettingFormattingRule.cs](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs) file.

- `.Kind() == x` vs `.IsKind(x)`: should use `.IsKind()` for consistency
https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs#L202
https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs#L193
- Use `.IsKind(x, y, ...)` overload when we're matching many kinds
https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs#L131-L133
https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs#L320-L323

Other instances might exist.

References:
https://github.com/dotnet/roslyn/pull/53110#discussion_r626583276
https://github.com/dotnet/roslyn/pull/53110#discussion_r626584273

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/pull/51823.

FYI @sharwell
