### ISSUE TITLE
String interpolation simplification error

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/roslyn#53228]
Simplifying the below string using intellisense

`{line.PadRight(28 - myString.Length)}`

produces 

`{line,28 - myString.Length}`

with a compile error of `A constant value is expected.`

**Comment by CyrusNajmabadi** [comment]
@jnm2 did you already fix this?

**Comment by CyrusNajmabadi** [comment]
I feel like this was fixed with https://github.com/dotnet/roslyn/pull/42249.  Checking.

**Comment by jnm2** [comment]
IIRC my fix was to VB and it was that VB doesn't allow all constants, only literals.

**Comment by CyrusNajmabadi** [comment]
Yeah.  This no longer repros.  And report is from more than a year ago.  Closing out.

**Comment by CyrusNajmabadi** [comment]
Duplicate of https://github.com/dotnet/roslyn/pull/42249
