### ISSUE TITLE
Inline parameter hints overlap with the debugger continue icon

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#53233]
![image](https://user-images.githubusercontent.com/24360909/117360668-eca77d80-ae6d-11eb-9877-85f795211334.png)

So the little green triangle just stands with the parameter. It would be great if we leave enough space for it

**Comment by CyrusNajmabadi** [comment]
i'm trying to figure out why that green triangle is there.  what is it 'continuing' to?  Why is it in the middle of the expression?  Might need to be routed to debugger. @jinujoseph ?

**Comment by jinujoseph** [comment]
in discussion with debugger team
