### ISSUE TITLE
how to emit only metadata?

### ISSUE THREAD

**Issue by roterdam** [dotnet/roslyn#5324]
Is it possible to emit only metadata? Will it be cheaper if somehow possible? In a scenario I have I only care about metadata and not really the code.

Is it even possible? By that I mean is type-checking the only pre requisite for metadata?

**Comment by bkoelman** [comment]
I believe you can. 

See [this file](https://github.com/bkoelman/ResharperCodeContractNullabilityFxCop/blob/master/src/FxCopUnitTestRunner/AssemblyUnderTest.cs) for an example; just pass in `" "` (string with a single space) as source code, and it creates an assembly on disk for you.

**Comment by MrJul** [comment]
I think you're looking for #2184, yet to be implemented.

**Comment by gafter** [comment]
There is an API to do this, but it is not possible from the command-line yet. More details to follow...

**Comment by gafter** [comment]
See https://github.com/dotnet/roslyn/blob/2f2629ba3e26128a15f6df9b667475a160fa5f9d/src/Compilers/Core/Portable/Emit/EmitOptions.cs#L15-L18

Closing as answered (for the API) and dup of #2184 (for the command-line).
