### ISSUE TITLE
Microsoft.CodeAnalysis.Common v.1.1.1 causes duplicate references in MSI project

### ISSUE THREAD

**Issue by SlavaB** [dotnet/roslyn#53297]
**Version Used**:  Microsoft.CodeAnalysis.Common v.1.1.1
**Steps to Reproduce**:

1. Build the attached solution.
2. Refresh the Dependendcies of the Installer project.
3. You can observe the duplicating references (see attached image). This issue prevents build a workable MSI. The setup raises error 2727.
![image](https://user-images.githubusercontent.com/1452852/117659212-56909180-b1a4-11eb-9440-3128ded26c12.png)

**Expected Behavior**: References in the Installer project should not be duplicated. And target MSI should work.

**Actual Behavior**: References in the Installer project are duplicated. The built setup raises error 2727.

[CodeAnalysis.zip](https://github.com/dotnet/roslyn/files/6452050/CodeAnalysis.zip)

**Comment by jinujoseph** [comment]
cc @JoeRobich
