### ISSUE TITLE
Unable to disambiguate files with same name in "Fix all occurrences" dialog

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#53293]
**Version Used**: 

**Steps to Reproduce**:

Invoke a solution-wide fix that touches multiple files having the same name but in different folders.

In my case, I was adding missing APIs to the API files, and because my project multi-targets with different API surfaces per framework, I have multiple instances of these analyzer files in different folders. This is a recommended pattern for the analyzer.

It would be very helpful to see the path, as that path includes the target framework.

**Expected Behavior**:

Able to disambiguate each occurrence of a file in the UI.

**Actual Behavior**:

There's no indication of which project or folder a file is in, so I have to guess:

![image](https://user-images.githubusercontent.com/350947/117595591-947dbd80-b184-11eb-852d-1e0de2628005.png)

**Comment by JoeRobich** [comment]
Proposal from Design Meeting: 
Do not fully truncate the file names that are ambiguous. Leave enough of the path to disambiguate.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in the preview chnages dialog.
