### ISSUE TITLE
Swapping with tuple deconstruction compiles to inferior IL code compared to using a temporary variable

### ISSUE THREAD

**Issue by hamarb123** [dotnet/roslyn#53300]
### Description
Swapping / reordering variables compiles to slower IL code when using tuple destruction than a temporary variable.
I tested this in Release mode.

The following C# code
```cs
int x = 1;
int y = 2;
int z = 3;
(x, y)=(y, x);
Console.WriteLine((x,y,z)); //this line is to stop compiling out the variables
```
should be equivalent in IL output to
```cs
int x = 1;
int y = 2;
int z = 3;
int temp = x;
x = y;
y = temp;
Console.WriteLine((x,y,z)); //this line is to stop compiling out the variables
```
, but the first compiles to:
```il
// Code size       31 (0x1f)
.maxstack  3
.locals init (int32 V_0,
         int32 V_1,
         int32 V_2,
         int32 V_3)
ldc.i4.1
stloc.0
ldc.i4.2
stloc.1
ldc.i4.3
stloc.2
ldloc.1
ldloc.0
stloc.3
stloc.0
ldloc.3
stloc.1
ldloc.0
ldloc.1
ldloc.2
newobj     instance void valuetype [System.Runtime]System.ValueTuple`3<int32,int32,int32>::.ctor(!0,
                                                                                                           !1,
                                                                                                           !2)
box        valuetype [System.Runtime]System.ValueTuple`3<int32,int32,int32>
call       void [System.Console]System.Console::WriteLine(object)
ret
```

and the second compiles to
```
// Code size       29 (0x1d)
.maxstack  3
.locals init (int32 V_0,
         int32 V_1,
         int32 V_2)
ldc.i4.1
stloc.0
ldc.i4.2
stloc.1
ldc.i4.3
stloc.2
ldloc.0
ldloc.1
stloc.0
stloc.1
ldloc.0
ldloc.1
ldloc.2
newobj     instance void valuetype [System.Runtime]System.ValueTuple`3<int32,int32,int32>::.ctor(!0,
                                                                                                           !1,
                                                                                                           !2)
box        valuetype [System.Runtime]System.ValueTuple`3<int32,int32,int32>
call       void [System.Console]System.Console::WriteLine(object)
ret
```

With the essential code being for (1):
```
ldloc.1
ldloc.0
stloc.3
stloc.0
ldloc.3
stloc.1
```
, and for (2):
```
ldloc.0
ldloc.1
stloc.0
stloc.1
```

I did test this on .NET 5 locally, but also on an online .NET 6 compiler at https://sharplab.io/, which uses a very recent version.
I also imagine that a similar thing happens for other variants, such as:
```cs
(x, y) = (x, x);
(x, y, z, w) = (w, y, z, x);
```
etc.
Surely these destruction assignments should be as simple as `ld` all of the variables, and then `st` them all (as long as there's not too many).
Interestingly, the tuple destruction code essentially uses a temporary variable in IL, whereas the temporary variable code eliminates it.
Not sure if this belongs on roslyn or on here.

**Comment by Neme12** [comment]
@Wraith2 
> If you check the JIT asm on sharplab you'll find they have the same output.

The JIT does optimize it for `int`:
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQAwAIDKAFhAE4AOAMhMAHQBKArjAlGAKYDcAsAFC8DaAKSgIA4mxhsSUAMYAKBAE8ybAPYAzObAQBKHQF1emACy4AKmxQIAjAB4zAPjkk2687nVQSVuLhduzXAAbVF1eAG9eXGj3BDYwMlwAXg8vK24eGNTvBGTg0IyskKs8uISMgF9eAWExCSlZBWU1TW09Qx4Tc0sEACZ7J393TxzfIcDisJ5IzJi5Sd8Rqx08uSWEX0mdSqA=
but not for other types: https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQAwAIDKAFhAE4AOAMhMAHQBKArjAlGAKYDcAsAFC8DaAKSgIA4mxhsSUAMYAKBAE8ybAPYAzOZgCMNACIQEbACqs2ASnMBdXpgAsuY2xQJtAHmMA+OSTbrHuOpQJC5wuL7+xrgANqgI5rwA3ry4qQFGYGS4ALyBwS7cPGl5IQg5MXGFxbEu5RlkhQC+vALCYhJSsgrKapo6+oYmZpY2PPaOzggATB7eEQFBpWHzUTXxSSlpcmthiy7m5XJ7CGFr5k1AA

**Comment by Neme12** [comment]
@Joe4evr 
> While that may be reasonable for you to assume, the only responsibility the compiler has is producing _correct_ IL. Producing _optimized_ IL would require much more analysis, most of which can't be done if you're compiling something like a class library (no entry point).

Yes, the only responsibility the compiler has is product correct IL, which means that this isn't a bug, but it's still a reasonable feature request and improvement, especially given the big focus on performance in today's .NET. Also, this would just be a small local optimization to eliminate a local, nothing to do with interprocedural optimization, so your comment about a class library and entry points is irrelevant.

**Comment by stephentoub** [comment]
> JIT performs optimization for x64

That type is 64 bits. Try one that's larger.

**Comment by hamarb123** [comment]
I'd also like to say that in terms of inlining, tuple destruction can be a turn off sometimes.
The shortest version of the method (where you just ld all the destinations and values, and then just st them all - I will elaborate below), which I would think would also be the simplest to implement, generates the smallest code IL Code, and equivalent JIT code to the longer form (which has the better JIT). It also allows the .maxstack 8 tiny header optimisation for swapping 2 things.
[https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEBLDAfAASQAI...](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEBLDAfAASQAIB9AWACgBvK4+4gOjAFcBnAFwgFtjsA7TgEN+YGMQBuEbABNiAbQDKAT04xujAEot+HbNxgBdFWo3bd+mIwDCPAA64YURU4nYxbG/dxC9EfpowGEIIvtj+bACCHBxQ2MAsHDAgIMxcUAAUAhwAzABMAJTEALzEGXQMlQAMAIzEVVX1ABz1jQ2tHQ0V9AXdTKycPHyCHCJiktJySqpJZjp6BsYz6lrzll7cDhhOLlBuHqsWBrabYcC42BzK0bHxicmpYOkZRaXllJXVde21HQCsKHqeWINRIfwA7MRwcCkHVwY0UOIkAAzYhIcQoP5Qpp9SpIHJorHwqGApAATjRqPRxABaJa0MpUMh4IJtT6vQ+DGY7C4vAEwlE4iksgUJlmhwWRjFKwAItghABzfgQTjuTwymAJBUKoTAbY3OIJJIpNLQDISIQYFgwK52cTTUwSyxLR1yxXK1VgdWalja3X6mKG+4Aeg1WoVAgVAFkIDIYGxXmVcQxfj9gT82pnWuy+owABZCNh54iWhXQS553hVBANBpNBqA4PB4iKAASkRquYkTnqICqfb7VAAvlQqMxgmw2MQ7HELUkS4kICXBNhiAByAA8MZkLG2AD411RaJQh8Qm8QYPw5BBUWAJ1Ot7HdzA96PKOPC1OZ9g5+IhIvlzYVdN23Z8Dz6GAECSK8p3kbg2EgKAMHiF1xQAeWAAArGAniPYcz2bS9r1ve9iEfHd9zfD9J2nWdfD/ACRCAktgE4KAhCeYg2BgS0YDkYAYGRaBBOwIIZAES51w3AAFKAIAVdjuD3AASQ9OXoSDoJkWDpTmI4pWWDQMOw3CaFzAZeWGAVxmFKZdKdRZ7PMSUNi2HZXHceNXMcKAAHFLyceiZANO5jUeZ5E3eT4U2+LMunU4gOUqc8oxtPNYzYXMDA4dK5G/X9iDzWRNVUbAFS40Y9DAYhk3oWypKjIQBBUtckwS6L6DYyN5EMEsoAVTL2oYIoCAJPpjw6gjiFSnLY2IASI0EEsOGITQADVInqBA8iqP4qlqqbbDjLjsAAL3EOoMmrGoko6ggsRxIb6AIFA30mgBJAAZUha37YhYA4PpT3PIjiBvYhstyqTZPkxSWpSECmv4Fq3q5SG5s/dQ9WUQriuAUryuEKqaqeiYRU3LckZUvcFVIUgABV4w4Go8CqH7WqiyaGAtK0bWUO1RUMhyDMdXyWFkAAyYhkWwKBODQA7Kh561bXtJy1kcoWxcl4gJ0B0mRrGhKJo6lK0rmhb+WW1aNq2naAQO88jvEIDzuIPJISuhAamAW7ovu92DsYDAIDAS0pwklbOa5hQql65W+YFh1xWc517O1mQDo5A6vp+2sQF1mQhH6xh9tJ3PaxqAuMBkCAsMFx1U810Xxcz8vvtrJAC84EOwFLnOO4acFq6Lkuy4+weqiaEfi4VRhO3bvOqjJEe68whuU41kXxQzgel+SCq143lYm+3lZd8XhoahyGeS4Xie85qFAR97/vL9qP5u64evk5PrfUPPq3PeV8hAFwBkDKaoNwbozkJuGGCkhBKVUgjDclNmrKRpnTRmnAWZsyqGpLK5s5CY24NjXGcZ8ZAUJpVdwJNJr1Qpo1dBmCGZMzyKzUgNQOaK25paFW/M1ZC1PgAjQGcpYyzlhwBWpMlZ8MToIxu/906tylnrLOxBRp0IYCbaKZtZr8RgItKcvgbabWrDtcEYBHbNmdidN2eQKRexqDIP2nwA55CDr3cOwxJLRy5vIOOkg5Gq2PnpSUIjGAZ2kTHeg8gajx2CQI0JwsIkX0mtnd+DRb5z3Hh1CuV9V4/3VvpVJQDMldwqq/XJ0V8lVGHoXWe89gF1kKevX+YS05azKQ/WsMgv6v3vnkyeB8a6NMGTUyeyIX6hzfj02of1BhFKEUorpshmk1E/g0se6yKk1wGes+piy2nFPCcotZ78ahgDATaCBIMrxg1RDA6GckEFILXCgtByMMG01YZwdhbMuGo3oIwJ5JCyFFQoQTCqYRqoHQYagphXyWHYNyBwrhbUYlBN5iE9pKSzkyHEbLeWPC6qJKTiczpLcdZqINhoo2lQdGfD0VDS2S0THrTMdtKoQhHqTSdrGF2Z1xB5CxE4skrjKgB0es0rJWyckyqrnKppmS8itOScI/FMr6mjLvjK6eSrqmfFqSvQuR9cUatWW3OZVQD5HPVSsqlVqhmPxvofJZiiSmaoufq8BCVgaEXudAohzzYaIPhiARhVNvlYKZjkNFBCTyQMDSRT8ZF4Fw2Um+IAA=)

Elaboration on what IL code I propose gets emitted:
For code like (a, b, c, ...) = (d, e, f, ...) the following code would be emitted:
Load a's storage
Load d
Load b's storage
Load e
Load c's storage
Load f
...
Store to c
Store to b
Store to a
This method should also work when one address is in multiple positions due to how it's ordered, so no special checking if they're the same address would be needed.

For a field on the left (a):
Load a's storage - load the object for an instance field on a class, or the address for an instance field on a value type, or none for a static field.
Store to a - stfld or stsfld

For a pointer or byref on the left (a):
Load a's storage - load the value (value being the pointer or byref) itself
Store to a - stind or appropriate short form

For a local variable (a):
Load a's storage - none
Store to a - stloc

And for things on the right, it is just the standard way of loading them onto the stack.
