### ISSUE TITLE
Expose 'debug-determinism' flag (or something similar) so that tooling can determine if the compiler is confident it would return the same result.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#53302]
The initial IDE use case here is directly supporting the `toolState` LSIF parameter: https://github.com/microsoft/lsif-node/blob/dbaeumer/117/protocol/src/protocol.ts#L348..L360

This parameter allows higher level aggregating entities (like LSIF) to know that the tooling feels that something has changed (or not) and thus if the computation should be performed again or should be recomputed.

**Comment by jaredpar** [comment]
@333fred what is the process for getting an API review slot for this? Need some time to write out the API but will make sure to do so before the meting.

**Comment by jaredpar** [comment]
Sorry, I forgot about this when I filed my proposal #57162. That one is fleshed out and has the convo going around it so going to close this one in favor of it.
