### ISSUE TITLE
`nint` is not allowed in operators defined on `IntPtr`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#53306]
While prototyping the [generic math](https://github.com/dotnet/designs/pull/205) feature which uses the [static abstracts in interfaces](https://github.com/dotnet/csharplang/blob/main/proposals/static-abstracts-in-interfaces.md) feature, I attempted to implement `IAdditionOperators` on `IntPtr`.

However, defining `nint operator +(nint left, nint right)` currently fails with:
> CS0563: One of the parameters of a binary operator must be the containing type

![image](https://user-images.githubusercontent.com/10487869/117724366-7e79f800-b198-11eb-9b98-940041191841.png)

I suspect that some handling is missing here.

**Comment by Youssef1313** [comment]
I'm looking into this.

**Comment by jcouv** [comment]
Assigned to @cston for triage and thoughts. Chuck, note that a WIP PR was linked above.

**Comment by cston** [comment]
This issue is being discussed. Moving to C#11 milestone.
