### ISSUE TITLE
Lightbulb Diff Preview doesn't ensure alignment of diff segments

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5333]
When producing a diff, we find all of the diff segments and insert "..." between them, but we do not then ensure the resulting diff view treats those "..."s as alignment points in their diff algorithm. So, the "..."s themselves can be reinterpreted as added/removed/edited, when they only exist to split the diff up into regions.

![image](https://cloud.githubusercontent.com/assets/4213867/9966886/20d3710c-5df4-11e5-90e9-a340b61cce98.png)

**Comment by dpoeschl** [comment]
(Saw this case while debugging #4251 with @balajikris)

**Comment by CyrusNajmabadi** [comment]
Have not heard about this from any other sources.  Closing out as practically no chance this is changing after 8+ years.
