### ISSUE TITLE
Inaccurate CS8602 warning generated on nullable enabled project after a conditional statement

### ISSUE THREAD

**Issue by stcmz** [dotnet/roslyn#53333]
Modify a .net core project file by adding the line below to enable nullable annotation and warning.
```
<Nullable>enable</Nullable>
```

In any cs code file, such a function below will cause a CS8602 on line 5.
```
1    void Test(string s)
2    {
3        if (s != null)
4            Console.WriteLine("not null");
5        Console.WriteLine(s.Length);
6    }
```

The warning message is: "Dereference of a possibly null reference."

The parameter `s` is not nullable so the warning should be on line 3 instead of line 5.

**Comment by canton7** [comment]
IIRC this is by design.

The compiler assumes that you know more than it does. If you test `s != null`, the compiler assumes that you know what you're talking about and that the variable can be null at that point, and updates the nullable state of that variable to "maybe-null".

**Comment by CyrusNajmabadi** [comment]
@canton7 Is 100% correct here.
