### ISSUE TITLE
Improve text changes algorithm for Razor scenarios

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#53346]
Roslyn currently does not compute TextChanges accurately for Razor, which has resulted in bugs such as https://github.com/dotnet/aspnetcore/issues/31369. We can temporarily bypass most issues via a minimal rename hack [see: #53347], but we will need Razor to define a set of rules and guidelines regarding what a valid TextChange looks like, and then Roslyn will need to implement an algorithm based on these guidelines.

Razor side issue: https://github.com/dotnet/aspnetcore/issues/32607

**Comment by jinujoseph** [comment]
cc @sharwell has some insight on this

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
