### ISSUE TITLE
Analysis is run for rule that is disabled

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [dotnet/roslyn#53355]
Microsoft.CodeAnalysis.CSharp: 3.8.0-5.final

**Steps to Reproduce**:

1. Disable rule in ruleset
2. Enable the same rule in editorconfig
3. Verify that both the initialization and all registered actions are executed

**Expected Behavior**:
Not to run the initialization and the registered actions as the rule is disabled.
**Actual Behavior**:
The initialization and registered actions get executed and the reported issues do not end up in the build results.

**Comment by Youssef1313** [comment]
From [Configuration files for code analysis](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#severity-options):

> - Severity options can also be specified with a [Ruleset](/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules) file. However, rulesets files are deprecated in favor of EditorConfig and global AnalyzerConfig files. It's recommended that you [convert ruleset files to an equivalent EditorConfig file](/visualstudio/code-quality/use-roslyn-analyzers#convert-an-existing-ruleset-file-to-editorconfig-file). Precedence for conflicting severity entries from a ruleset file and EditorConfig or global AnalyzerConfig files is _undefined_.
