### ISSUE TITLE
Use Auto Property doesn't format getter properly

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#5335]
```C#
class C
{
    private readonly int _x;

    public C(int x)
    {
        _x = x;
    }

    public int X
    {
        get { return _x; }
    }
}
```

Apply "Use auto property":

```C#
class C
{
    public C(int x)
    {
        X = x;
    }

    public int X
    {
        get; }
}
```

**Comment by balajikris** [comment]
In this case, should it produce accessors in a single line if "C# -> Formatting -> Wrapping -> Leave block on single line" is checked (which is the default option anyway).  Just a clarification on the expected output here.

Should it look like this:
```C#
public int X { get; }
```

**Comment by DustinCampbell** [comment]
Yeah, I think so.

**Comment by Pilchie** [comment]
Moving to 1.2, since Convert to Auto Property not enabled.
