### ISSUE TITLE
Sporadic failures in AbstractPersistentStorageTests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#53362]
Hitting some failures in `AbstractPersistentStorageTests`. It's no ta single failure but instead roughly the same stack trace spread out across a number of tests. The rough stack is the following 

```
[xUnit.net 00:00:27.63]     Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.CloudCachePersistentStorageTests.TestReadChecksumProducesLastWrittenChecksum1 [FAIL]
  Failed Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.CloudCachePersistentStorageTests.TestReadChecksumProducesLastWrittenChecksum1 [1 s]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<TestReadChecksumProducesLastWrittenChecksum1>d__42.MoveNext() in /_/src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs:line 392
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.UnitTests.WorkspaceServices.AbstractPersistentStorageTests.<TestReadChecksumProducesLastWrittenChecksum1>d__42.MoveNext() in /_/src/VisualStudio/CSharp/Test/PersistentStorage/AbstractPersistentStorageTests.cs:line 392
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:39.47]     Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.CodeModel.FileCodeFunctionTests.Overloads_Count [SKIP]
  Skipped Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.CodeModel.FileCodeFunctionTests.Overloads_Count [1 ms]
[xUnit.net 00:01:41.67]     Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Interactive.Commands.InteractiveCommandHandlerTests.TestExecuteInInteractiveWithDefines [SKIP]
  Skipped Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Interactive.Commands.InteractiveCommandHandlerTests.TestExecuteInInteractiveWithDefines [1 ms]
Results File: C:\h\w\AD0F09A7\w\A60208F7\e\Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.dll_net472_x86_test_results.xml
```

Example build:
- https://dev.azure.com/dnceng/public/_build/results?buildId=1133858
- [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-roslyn-refs-heads-release-dev1611-vs-de10f10da90f04b83b2/Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.dll/console.c6d2a73a.log?%3Fsv%3D2019-07-07%26se%3D2021-06-01T01%253A22%253A08Z%26sr%3Dc%26sp%3Drl%26sig%3D%252Br4Ik102okqw8tvg0R8FwbPecAG5FvdE6Jq%252BcpJNx10%253D)

|Build|Kind|Start Time|
|---|---|---|
[1128675](https://dev.azure.com/dnceng/public/_build/results?buildId=1128675)|Rolling|2021-08-05|
[1133858](https://dev.azure.com/dnceng/public/_build/results?buildId=1133858)|Rolling|2021-12-05|

**Comment by CyrusNajmabadi** [comment]
@AArnott  Do you know what might be up here?

We updated to the latest nerdbank APIs and now are seeing errors in our persistence tets

In this case, the test is doing:
​
```    
            await using (var storage = await GetStorageAsync(solution))
            {​​​​​
                Assert.True(await storage.WriteStreamAsync(streamName1, EncodeString(GetData1(Size.Small)), checksum: s_checksum1));
                Assert.True(await storage.WriteStreamAsync(streamName1, EncodeString(GetData1(Size.Small)), checksum: null));
            }​​​​​
            await using (var storage = await GetStorageAsync(solution))
            {​​​​​
                Assert.False(await storage.ChecksumMatchesAsync(streamName1, s_checksum1));
            }​​​​​
```

So despite writing to the same stream twice, with an actual, and then 'null' checksum.  when we go to check if the checksum matches the original value, it says it does (despite it being replaced with a 'null' checksum).

**Comment by CyrusNajmabadi** [comment]
The way we check if a checksum matches is to do this:

```
        private async Task<bool> ChecksumMatchesAsync(string name, Checksum checksum, CacheContainerKey? containerKey, CancellationToken cancellationToken)
        {
            // If we failed to get a container key (for example, because the client is referencing a file not under the
            // solution folder) then we can't proceed.
            if (containerKey == null)
                return false;

            using var bytes = s_byteArrayPool.GetPooledObject();
            checksum.WriteTo(bytes.Object);

            return await _cacheService.CheckExistsAsync(new CacheItemKey(containerKey.Value, name) { Version = bytes.Object }, cancellationToken).ConfigureAwait(false);
        }
```

Is it possible there's some sort of race in the cache service that means that CheckExistsAsync will find the old object, even though it should have been overwritten with the second WriteStreamAsync?

**Comment by AArnott** [comment]
[`ICacheService.SetItemAsync`](https://dev.azure.com/devdiv/DevDiv/_git/VS.CloudCache/?path=src/Microsoft.VisualStudio.Cache/CacheService.cs&version=GC81717a677856d54d508163bfc4b89dc9c08e1f63&lineStyle=plain&line=214&lineEnd=214&lineStartColumn=31&lineEndColumn=31) only completes its returned task after writing has been committed.
[`ICacheService.CheckExistsAsync`](https://dev.azure.com/devdiv/DevDiv/_git/VS.CloudCache/?path=src/Microsoft.VisualStudio.Cache/CacheService.cs&version=GC81717a677856d54d508163bfc4b89dc9c08e1f63&lineStyle=plain&line=129&lineEnd=129&lineStartColumn=39&lineEndColumn=39) has no cache of its own, and always has to obtain that read scheduler's time to read the db before returning the result.

However I see [here](https://dev.azure.com/devdiv/DevDiv/_git/VS.CloudCache/?path=src/Microsoft.VisualStudio.Cache/SQLite/Schema.cs&version=GC81717a677856d54d508163bfc4b89dc9c08e1f63&lineStyle=plain&line=114&lineEnd=118&lineStartColumn=1&lineEndColumn=1) that we only initialize the version (aka checksum) column when the checksum is non-null. So I suspect the issue here may be a stale value is retained by the `sqlite3_stmt` object that we reuse, so we effectively are re-applying a stale value. I will investigate.

**Comment by AArnott** [comment]
A targeted test to prove whether this is a problem fails to repro the issue. And we are calling `sqlite3_clear_bindings` after every use of the statement so presumably no lingering state should exist from a prior use anyway. 
I could give you a private build of a "fix" for this problem to see if it helps, but that may only help if the tests fail frequently enough that you can be pretty confident the fix actually did something, since I think it won't.

How does `WriteStreamAsync` work? Any chance it completes before the cache service does?

**Comment by AArnott** [comment]
I wonder what nerdbank.streams you upgraded from and to, so I can speculate on how that might have destabilized this.

**Comment by CyrusNajmabadi** [comment]
our wrapper over you is very thin. you can see it here: https://github.com/dotnet/roslyn/blob/main-vs-deps/src/VisualStudio/Core/Def/Storage/CloudCachePersistentStorage.cs#L179

lmk if anything looks innappropriate.

**Comment by CyrusNajmabadi** [comment]
> I wonder what nerdbank.streams you upgraded from and to

https://github.com/dotnet/roslyn/pull/52428/files#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67L183

from 2.6.81 to 2.7.62-alpha

**Comment by AArnott** [comment]
I can't see anything between those two versions that seems likely to cause a problem here. And your wrapper is thin. 
How easy is this to repro on a local dev box?

**Comment by CyrusNajmabadi** [comment]
> How easy is this to repro on a local dev box?

i've never seen it on my local dev box.  But Jared seems to indicate that it is happening somewhat regularly on CI :-/

**Comment by jaredpar** [comment]
Yeah it's happening about once a day in CI right now.

**Comment by AArnott** [comment]
Ok, got a repro! It depends on the cache being flushed to disk between the two write operations.

**Comment by jaredpar** [comment]
Should add we could change that particular `Assert` so that the next time it hits in the future we get a heap dump for the situation. Flipping an individual assert that way is pretty straight forward in our infra.

**Comment by AArnott** [comment]
BTW do you need this fix in anything older than 17.0?

**Comment by CyrusNajmabadi** [comment]
Ideally, we could get it for 16.10p4  Thanks!

         -- Cyrus

**Comment by AArnott** [comment]
What is the user impact of the bug (assuming they are in your flight group that consume it)? It seems we would return more cache hits, which would be a good thing, right? Is this just a test stability issue then?

**Comment by CyrusNajmabadi** [comment]
That's more of a question for you I suppose :)   If checksum answers aren't necessarily accurate, how might that affect things?  In this case it seems like it could it lead to us thinking data was up to date, and not recomputing data, leading to using cached data that didn't correspond to user source.  That could potentially cause invariant breakages while might cause crashes.

**Comment by AArnott** [comment]
> That's more of a question for you I suppose

I can explain what happens at the cache level.
A cache hit never means your data is current or that you don't have to do other work. It just means we have a value for you that matches the criteria you gave us. If you omit the checksum we'll give you the last value you wrote. If you give us a checksum and we have a match for it, we'll return that too. It just happens that this bug means we effectively record *two* cached values for a given key and you can get to the older one if you know the checksum for it. And if you're asking for it with the checksum, doesn't that imply it has the data to match what you need?

But for a 16.10 preview 4 bug, we'll have to explain how this negatively impacts the customer. I can't imagine how this would hurt the customer. Can you? It's a roslyn scenario and I'm not familiar with how you use your checksums. 

I have the fix ready to go into 16.10, and a PR to send it to 17.0 right now that is just waiting on a code review. If I can get a customer impact statement, I'll send it through for QB approval for 16.10.

**Comment by CyrusNajmabadi** [comment]
here's the important question i need answered:  if i ask for teh value *without* the checksum, could i get the older value? Or will i get the more current value?

**Comment by AArnott** [comment]
Always the current value.

**Comment by CyrusNajmabadi** [comment]
>I have the fix ready to go into 16.10, and a PR to send it to 17.0 right now that is just waiting on a code review.

I think it's fine for this to go into 17.0.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/324993

**Comment by AArnott** [comment]
@CyrusNajmabadi  Your unit tests will continue to show this erratic behavior till you reference the newer version, won't they? They won't pick up the VS inserted version automatically, I suspect.

**Comment by CyrusNajmabadi** [comment]
ah ok.  good point.  i'll open pr to move to this.

**Comment by CyrusNajmabadi** [comment]
This has been fixed.
