### ISSUE TITLE
CS1069: The type name 'Queue<>' could not be found in the namespace 'System.Collections.Generic'.

### ISSUE THREAD

**Issue by arniwesth** [dotnet/roslyn#53366]
**Version=3.9.0.0**

**Environment**
VS Code dev container: mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-5.0

I am compiling code dynamically using `CSharpCompilation.Create`, similar to this [post](https://laurentkempe.com/2019/02/18/dynamically-compile-and-run-code-using-dotNET-Core-3.0/) which I adapted my code from. But I am getting

```
CS1069: The type name 'Queue<>' could not be found in the namespace 'System.Collections.Generic'. 
This type has been forwarded to assembly 'System.Collections, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
```
and this
```
CS0012: The type 'List<>' is defined in an assembly that is not referenced. You must add a reference to 
assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```
as error messages from compilation result.  

The dynamically compiled code consist of 100's of source files. I have so far not been able to reproduce this with a simple example. Even trying to eg compile just one of the files that cause this issue works fine.

**Comment by huoyaoyuan** [comment]
In this case, you'd better to share (an abstraction of) your project file.

Since `System.Collections` are referenced by SDK by default, I suspect you are using legacy project file. If the project is .NET Framework, you can consider to move to SDK style project.

**Comment by arniwesth** [comment]
I should have specify that this happens when I compile code dynamically using `CSharpCompilation.Create`, similar to this [post](https://laurentkempe.com/2019/02/18/dynamically-compile-and-run-code-using-dotNET-Core-3.0/) which I adapted my code from. I've updated my initial post to reflect this.

**Comment by Youssef1313** [comment]
@arniwesth You're most likely missing some reference assemblies. See https://github.com/dotnet/docs/issues/12317.

**Comment by arniwesth** [comment]
This seems to be a lot more subtle than a missing reference. I created a new project that calls the same code that generates dynamic compiled code using `CSharpCompilation` - and the it worked . Then I did a lot of changes to the original project trying to narrow down the difference. But then I tried running the new project I had just created - and now I get same errors again...
Cleaning the projects don't help.

**Comment by jaredpar** [comment]
Can you provide some more information on how you are creating the `CSharpCompilation` object, particularly how are you passing the references? The problem is almost certainly that you are using the incorrect set of references here and that is leading to the problem.

**Comment by ClayBullet** [comment]
I find the error. In my case the System reference was missed and cannot load properly System.Collections.Generic.Queue<T>
