### ISSUE TITLE
disabling access modifier type checking in roslyn?

### ISSUE THREAD

**Issue by roterdam** [dotnet/roslyn#5337]
Is it possible to disable access modifier type checking in roslyn?

Will it fail at MSIL level if roslyn just passes it through? I know it can affect semantics of programs that use reflection, but if one doesn't it shouldn't matter right?

**Comment by jaredpar** [comment]
At an API level accessibility can be ignored by specifying the `ignoreAccessibility` parameter.  This allows code to run binding and analysis as if everything was `public`.  

There is no way to run a full compilation with such a setting though.  If one did exist there are scenarios where it would fail at runtime in the CLR.
