### ISSUE TITLE
Strange 'Generate method' code fix behavior

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#5338]
Observed in Visual Studio 2015 RTM.

Given the following code:

``` csharp
private static readonly ConcurrentDictionary<Type, Func<JToken, object>> _deserializeHelpers =
    new ConcurrentDictionary<Type, Func<JToken, object>>();

private static object DeserializeObject(JToken token, Type type)
{
    _deserializeHelpers.GetOrAdd(type, key => CreateDeserializeDelegate(key));
}
```

On the line containing the call to `GetOrAdd`, press <kbd>Ctrl</kbd>+<kbd>.</kbd> and invoke the Generate method code fix.
### Expected result

_Either_ of the following options:

``` csharp
// Option 1
private static Func<JToken, object> CreateDeserializeDelegate(Type key)
{
    throw new NotImplementedException();
}

// Option 2
private static object CreateDeserializeDelegate(JToken key)
{
    throw new NotImplementedException();
}
```
### Actual result

``` csharp
private static Func<JToken, object> CreateDeserializeDelegate(JToken key)
{
    throw new NotImplementedException();
}
```

**Comment by lgolding** [comment]
@Pilchie Fixers are done by IDE team, right?

**Comment by Pilchie** [comment]
Yes.

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this in our latest builds.  I've added a test case for this here: https://github.com/dotnet/roslyn/pull/5682

Which seems to show the correct behavior.  Let me know if you have any issues with me closing this.  Thanks!

**Comment by Neme12** [comment]
@CyrusNajmabadi the test you added shows the behavior marked as **Actual result**, not **Expected result**

**Comment by Neme12** [comment]
@sharwell Can you please reopen this (if I understand this correctly)?

**Comment by Neme12** [comment]
@jinujoseph Can you please reopen this?

**Comment by Neme12** [comment]
@jinujoseph I originally marked my PR as fixing this, but my fix was incorrect, so I removed it from that PR and won't be fixing this (at least not that PR, it already fixes a bunch of other issues). I'm sorry for the confusion. Would you please remove the '"Working" tag? Thanks.

**Comment by CyrusNajmabadi** [comment]
We properly generate option-1 now.  Closing out:

![image](https://user-images.githubusercontent.com/4564579/198711701-62794576-96c2-4b98-a3ec-d32996956512.png)
