### ISSUE TITLE
The "Use Auto Property" quick action is not displayed on classes with [Serializable] attribute

### ISSUE THREAD

**Issue by alexvaccaro** [dotnet/roslyn#53387]
**Version Used**:  
VS 2019 16.8.6
Tested on projects targeting .Net 4.6.1 and .Net Core 3.1.

**Steps to Reproduce**:

1. Create a new class
2. Add a property with a backing field
3. Expand the light bulb quick actions menu on the newly created property and confirm the option "Use Auto Property" is listed
4. Decorate the class with the [Serializable] attribute
5. Expand the light bulb quick actions menu on the property and the option "Use Auto Property" is no longer listed

**Expected Behavior**:
The "Use Auto Property" quick action should be displayed irrespective on whether the class is being decorated with the [Serializable] attribute or not

**Actual Behavior**:
The "Use Auto Property" quick action is not displayed on classes with [Serializable] attribute

**Comment by Youssef1313** [comment]
The current behavior is intentional. See https://github.com/dotnet/roslyn/issues/34783.
