### ISSUE TITLE
Solution Explorer search is much slower than Visual Studio search

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53385]
![image](https://user-images.githubusercontent.com/31348972/118098204-e7997f80-b3d3-11eb-9bf0-9e15af8a9ea1.png)

This 100% reproduces for me. Visual Studio search bar finds files much much faster than searching in Solution Explorer.

If Solution Explorer search needs to do some extra work, it could do the cheap work first and display partial results.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @olegtk  to route to platform.  However, i'm fairly certain this is a well known issue that we're tracking already.  @olegtk to confirm.

**Comment by olegtk** [comment]
Unfortunately SolExp search is using completely different implementation (Progression graph), but yes, please route it to the platform, we need this input to prioritize future work.

**Comment by jinujoseph** [comment]
Tracked internal [here ](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1308215)
