### ISSUE TITLE
Use Automatic Feature Suspension to protect against known issues

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/roslyn#53398]
**Brief description:**

[Automatic Feature Suspension](https://docs.microsoft.com/en-us/visualstudio/code-quality/automatic-feature-suspension?view=vs-2019) guards against bad experiences with Roslyn. When a user has limited memory, it prioritizes their experience by disabling some advanced features.

This guard can be expanded to cover other known scenarios. Issues relating to high CPU usage, long task execution, or analyzers that aren't built to run concurrently.

**Comment by CyrusNajmabadi** [comment]
We already do this.  Not clear waht else would need to be done.
