### ISSUE TITLE
Order of mdarray's dimensions in IL

### ISSUE THREAD

**Issue by am11** [dotnet/roslyn#53405]
**Version Used**: 
3.9.0-6.21160.10 (59eedc33)

**Steps to Reproduce**:

Roslyn tends to flip the dimensions of multidimensional arrays in IL. e.g. `int[,,,][,][,,][] foo = new int[4,3,2,1][,][,,][]` produces:

```
newobj instance void int32[][0..., 0..., 0...][0..., 0...][0..., 0..., 0..., 0...]::.ctor(int32, int32, int32, int32)
```

compared to F#'s fsc, which preserves the order and generates:
```
valuetype [System.Private.CoreLib]System.Int32[0..., 0..., 0..., 0...][0..., 0...][0..., 0..., 0...][] get_foo ()
```

**Expected Behavior**:

The order is preserved in IL like fsc, so the type reported by `typeof(int[,,,][,][,,][])` is `System.Int32[,,,][,][,,][]`.

**Actual Behavior**:

The order is flipped in the IL and the type reported by `typeof(int[,,,][,][,,][])` is `System.Int32[][,,][,][,,,]`.

**Comment by CyrusNajmabadi** [comment]
Reading the spec, this seems to be entirely by design.  See https://github.com/dotnet/csharplang/blob/main/spec/arrays.md:

```
The element type of an array type is the type that results from deleting the leftmost rank_specifier:

An array type of the form T[R] is an array with rank R and a non-array element type T.
An array type of the form T[R][R1]...[Rn] is an array with rank R and an element type T[R1]...[Rn].

In effect, the rank_specifiers are read from left to right before the final non-array element type.
The type int[][,,][,] is a single-dimensional array of three-dimensional arrays of two-dimensional arrays of int.
```

**Comment by am11** [comment]
I am not sure which part of spec is implying that it is ok to flip the dimensions?

cc @MichalStrehovsky, fyi, I found it in a custom serializer for jagged arrays (for sparse data sets from flatbuffers), essentially `Type.GetType("System.Int32[][,,][,][,,,]") == typeof(int[][,,][,][,,,])` was evaluating to `false`. I had to monkeypatch the encoded types by decoding them and flipping the dimensions. It is very csharp-specific behavior as mentioned above.

**Comment by MichalStrehovsky** [comment]
Eric Lippert has a blog on this: https://ericlippert.com/2009/08/17/arrays-of-arrays/

**Comment by CyrusNajmabadi** [comment]
> It is very csharp-specific behavior as mentioned above.

Yes.  That's what is said :)  This is how C# works.

> was evaluating to false

The C# grammar spec is unrelated to the grammar that Type.GetType accepts.  You cannot assume that these will hold true (for practically anything).  You'll have to translate between the two if you want to get that equality statement to hold.
