### ISSUE TITLE
Spaces missing in single-line dictionary initializers

### ISSUE THREAD

**Issue by breyed** [dotnet/roslyn#5340]
When Visual Studio auto-formats indexer-style C# dictionary initializers with multiple pairs on the same line, it fails to insert a space after the opening brace and separating commas.

For example, type:

    var a = new Dictionary<int,int>{[1]=2,[3]=4};

Auto-format the document. The result is:

    var a = new Dictionary<int, int> {[1] = 2,[3] = 4 };

The result should be:

    var a = new Dictionary<int, int> { [1] = 2, [3] = 4 };

**Comment by gafter** [comment]
Not sure where the relevant code is. IDE?

**Comment by breyed** [comment]
This issue occurs in the Visual Studio 2015 C# editor. Does that answer your question?

**Comment by gafter** [comment]
My question is for the Roslyn implementors: where is the misbehaving code, and which team should this be assigned to?

**Comment by Pilchie** [comment]
Is this a dupe of #4280? Does the fix for that address the space after the ",".

**Comment by DustinCampbell** [comment]
Yup. I can verify that this is working now.
