### ISSUE TITLE
Doc clarification question: When should an analyzer free resources acquired at compilation start action?

### ISSUE THREAD

**Issue by realvizu** [dotnet/roslyn#53439]
The doc at https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Analyzer%20Actions%20Semantics.md says that "it is possible for a compilation start action to run without its corresponding compilation end actions ever running for a given compilation, [...] Therefore, end actions cannot be relied upon to free resources acquired by start actions."

So my question is: what is the recommended way to freeing up resources used by an analyzer for the scope of a compilation (like a   per-compilation cache)?

**Comment by CyrusNajmabadi** [comment]
> So my question is: what is the recommended way to freeing up resources used by an analyzer for the scope of a compilation (like a per-compilation cache)?

Registration should happen like so:

```c#
context.RegisterCompilationStartAction(csaContext =>
{
    var perCompilationCache = ...;
    csaContext.RegisterXXX(xxxContext =>
    {
        // can use perCompilationCache here
    });
});
```

Using this sort of pattern means your caches will be let go of once the analysis engine has finished doing all the work it has set out to do.  All your lambdas will be dropped, which means all the state you may have built up in them can just get GCed naturally.

**Comment by realvizu** [comment]
Great, thanks!
