### ISSUE TITLE
When building, could not load System.Runtime

### ISSUE THREAD

**Issue by martinrhan** [dotnet/roslyn#53446]
**Version Used**: v3.9.0

**Steps to Reproduce**:
1. Create a solusion with a console application, then add a class library project. Both projects are .NET 5.

2. Install NuGet package `Microsoft.CodeAnalysis.CSharp.Workspaces` for both projects.

3. In the class library project, write following code:
```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ClassLibrary {
    [Generator]
    public class MySourceGenerator : ISourceGenerator {
        public void Execute(GeneratorExecutionContext context) {
            context.AddSource("myGeneratedFile.cs", SourceText.From(@"
namespace GeneratedNamespace
{
    public class GeneratedClass
    {
        public static void GeneratedMethod()
        {
            // generated code
        }
    }
}", Encoding.UTF8));
        }

        public void Initialize(GeneratorInitializationContext context) {
        }
    }
}
```
4. In the Main method of console application, write following code:
```
            GeneratedNamespace.GeneratedClass.GeneratedMethod();
```
5. In the .csproj of the console application, add following code:
```
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary_ExperimentalSourceGenerator\ClassLibrary_ExperimentalSourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
```
6. Build solusion.

**Expected Behavior**: There should be nothing happening and everything works well.

**Actual Behavior**:

Recieved following error:    
CS0103     
The name 'GeneratedNamespace' does not exist in the current context
ConsoleApp1	D:\OneDrive\VS Solutions\ConsoleApp1\Program.cs

And following warning:    
CS8032    
An instance of analyzer ClassLibrary.MySourceGenerator cannot be created from D:\OneDrive\VS Solutions\ClassLibrary_ExperimentalSourceGenerator\bin\Debug\net5.0\ClassLibrary_ExperimentalSourceGenerator.dll: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. System cannot find the file specified.

**Comment by Youssef1313** [comment]
Source generators and analyzers should target .NET Standard. This is a limitation because they can run in a .NET Core environment (`dotnet` command line tool), or in Visual Studio (.NET Framework).

**Comment by raffaeler** [comment]
@Youssef1313 this is a huge problem due to [this](https://github.com/dotnet/roslyn/issues/43903) requirement.
Basically the generator must reference all the projects that are needed by the generated code.
Since the generator needs to be nestandard2.0, this implies that all the dependencies must be nestandard2.0, which is a huge limitation.

One of the two constraints should be removed asap, IMO.

**Comment by jaredpar** [comment]
> Since the generator needs to be nestandard2.0, this implies that all the dependencies must be nestandard2.0, which is a huge limitation.

This is not likely to change any time soon. I've written up a bit of detail here on why source generators must target `netstandard2.0`. 

https://github.com/dotnet/roslyn/issues/53193#issuecomment-879189255

> Basically the generator must reference all the projects that are needed by the generated code.

That should not be the case. Generators must reference all of the projects needed to generate the code but they do not need to reference the projects used in the generated code.
