### ISSUE TITLE
C# refactor "Create and assign remaining as properties" ignores base class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53455]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-refactor-Create-and-assign-remaining/1423904)._

---
[severity:I'm unable to use this version]
If you have a constructor for a C# class that has a base class, and some properties that appear as constructor arguments are already defined as properties on the base class, when you use the refactoring "Create and assign remaining as properties", it ignores those already defined on the base class and creates new ones in the derived class. e.g.

````
    public class Foo
    {
        public Foo(int prop1)
        {
            Prop1 = prop1;
        }

public int Prop1 { get; }
    }

public class Bar : Foo
    {
        public Bar(int prop1, int prop2) :base(prop1)
        {

}
    }
````

If you use "Create and assign remaining as properties" on the constructor of Bar it should only add Prop2 to Bar, but instead it adds Prop1 and Prop2.

Same applies when using fields instead of properties.

---
#### Feedback Bot on 5/16/2021, 08:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Interesting.  I think we could add some heuristics to detect this and do better here.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
