### ISSUE TITLE
During typing in VS the source generator runs and contains all syntax trees in the project instead of the ones we changed

### ISSUE THREAD

**Issue by zbesevic** [dotnet/roslyn#53452]
**Version Used**: 
.NET 5 SDK 5.0.103
Microsoft.CodeAnalysis 3.8.0

The Compilation object in GeneratorExecutionContext contains all syntax trees in the project instead of only the objects we changed during typing (only for compile during typing) which slows down typing performance in VS. As I need around 500 classes to generate code for I get around 7000 because it always takes everything and I filter this 7000 to get the 500 which is slow and kills typing performance.

**Steps to Reproduce**:

1. Add a simple source generator for a project which has more than one source code file
2. As an example add a field or write something to a class in the project for which we have a source generator

**Expected Behavior**:
The Compilation should only contain the syntax tree for the file changed (incremental build)

**Actual Behavior**:
The compilation contains all syntax trees in the project

**Comment by Youssef1313** [comment]
This is currently by design. There is a proposal that considers the performance impact, see https://github.com/dotnet/roslyn/issues/51497.

**Comment by jaredpar** [comment]
As @Youssef1313 mentioned this is "By Design". The `Compilation` must necessarily always contain all of the `SyntaxTree` otherwise the resulting `SemanticModel` would result in lots of errors. The Source Generator V2 design makes it so that the processing required in the IDE is incremental and reduces the overall load for typing scenarios.

**Comment by zeljkobesevic** [comment]
> As [@Youssef1313](https://github.com/Youssef1313) mentioned this is "By Design". The `Compilation` must necessarily always contain all of the `SyntaxTree` otherwise the resulting `SemanticModel` would result in lots of errors. The Source Generator V2 design makes it so that the processing required in the IDE is incremental and reduces the overall load for typing scenarios.

The issue is gone without upgrading to incremental source generator. Could this be fixed in newer sdk(compiler?)? Now we are on .net8
