### ISSUE TITLE
Task List is showing all items twice

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53456]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Task-List-is-showing-all-items-twice/1424132)._

---
[severity:It bothers me. A fix would be nice]
All of my tasks with TODO (or Todo) are showing up twice in the task list, which is very annoying. I'm guessing this is because there are two default tokens (TODO and todo) but I cannot remove one to test it. Another alternate fix may be to only return one TODO per line (or provide the user with an option to do so).

---
#### Feedback Bot on 5/16/2021, 07:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
This no longer repros on latest VS2022 17.0 release build. Please re-open if you are still seeing this.
