### ISSUE TITLE
[Loc] Loc rule needs update

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/roslyn#53483]
For the file "src\Features\Core\Portable\xlf\FeaturesResources.xlf" , the resource _10ths_of_a_second_description have an invalid comment-rule:  <note>{Locked="ParseExact"}{Locked="TryParseExact"}{Locked="f"}</note>
This rule as-is locks all f in the string, not only "f".
Could you add it as {Locked="ParseExact"}{Locked="TryParseExact"}{Locked=""f""} ?

**Comment by JoeRobich** [comment]
@crsuzukimsft Is there a particular release branch you would like this change in? Or is our dev17 preview 2 branch sufficient?
