### ISSUE TITLE
Use proper title  for inheritance margin

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#53489]
Originally discuss with @sharwell  and @CyrusNajmabadi 
![image](https://user-images.githubusercontent.com/24360909/118695743-60c51800-b7c2-11eb-8a7a-78788e68ee8e.png)
We should use the correct compiler words like
'Based types', 'Implemented interfaces' and 'Derived types' instead of the platform side terminology. (which is confusing)

In additional to that 
![image](https://user-images.githubusercontent.com/24360909/118696095-c6b19f80-b7c2-11eb-8062-cf4e192213d4.png)
The title here is reversed.

Also, we should show the header regardless of how many group are in the margin

**Comment by sharwell** [comment]
@Cosifne do you have a list of the headers we show today? If I have the list, I can write a complete description for which ones should be shown in which cases.

**Comment by sharwell** [comment]
For classes and structures, ideally we would have three headers:

* Headers for classes and structures
    * `I↑` Implemented interfaces
    * `O↑` Base types
    * `O↓` Derived types
* Headers for interfaces
    * `I↑` Implemented interfaces
    * `I↓` Implementing types
* Headers for members of a class or structure
    * `I↑` Implemented members
    * `O↑` Overridden members
    * `O↓` Overriding members
* Headers for members of an interface
    * `I↓` Implementing members

**Comment by Cosifne** [comment]
@sharwell 
There are only 4 headers
https://github.com/dotnet/roslyn/blob/065d50c8c76303a7bbd9cf1dc43acd420393fa54/src/VisualStudio/Core/Def/ServicesVSResources.resx#L1732

**Comment by CyrusNajmabadi** [comment]
I might change `Headers for interfaces: Implemented interfaces` to `Headers for interface: Inherited interfaces`.  But otherwise, it looks great to me.

**Comment by sharwell** [comment]
@CyrusNajmabadi updated the table with that suggestion

**Comment by CyrusNajmabadi** [comment]
(you updated the wrong string).  the original for class/struct was ok :)

**Comment by sharwell** [comment]
🤦‍♂️

**Comment by CyrusNajmabadi** [comment]
lgtm.  Note for @genlu .  If `Inherited interfaces` is hard to put in due to how the code is structured, it's fine for that to be `Implemented interfaces`

**Comment by sharwell** [comment]
You mean @Cosifne ?

**Comment by CyrusNajmabadi** [comment]
Yes.  Sorry.  I am talking to too many people today :(

**Comment by mikadumont** [comment]
> I believe this is the full set of potential headers. Groups with no elements should be omitted (and also not show the header).
> 
> * Headers for classes and structures
>   
>   * `I↑` Implemented interfaces
>   * `O↑` Base types
>   * `O↓` Derived types
> * Headers for interfaces
>   
>   * `I↑` Inherited interfaces
>   * `I↓` Implementing types
> * Headers for members of a class or structure
>   
>   * `I↑` Implemented members
>   * `O↑` Overridden members
>   * `O↓` Overriding members
> * Headers for members of an interface
>   
>   * `I↓` Implementing members

These names are essentially the opposite of the icon moniker names and what we initially designed. Why are we changing it?

**Comment by CyrusNajmabadi** [comment]
The names name sense to me. The arrow points in the direction you are going (either up or down the inheritance hierarchy), and the name tells you what you will encounter in that direction. 

For example: Overridden members

First, We're going up the hierarchy to find these, so it makes sense to have an up arrow.  Second, the symbols were hitting are the members that were overridden.
