### ISSUE TITLE
A warning is produced when `csharp_style_expression_bodied_* = when_on_single_line` is used

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53482]
Part of my editorconfig:

```ini
# Default severity for analyzer diagnostics with category 'Style'
dotnet_analyzer_diagnostic.category-Style.severity = warning

# IDE0022: Use block body for methods
csharp_style_expression_bodied_methods = when_on_single_line

# IDE0021: Use block body for constructors
csharp_style_expression_bodied_constructors = when_on_single_line
```

The following code generates a warning:

```csharp
    internal class LocalLinkValidator : ILinkValidator
    {
        private readonly string _baseDirectory;

        // Warning on the following line:
        public LocalLinkValidator(string baseDirectory) => _baseDirectory = baseDirectory;
    }
```

It's not clear to me why there is a warning? I'm using an expression bodied member when on single line per editorconfig.

**Comment by AraHaan** [comment]
> Part of my editorconfig:
> 
> ```ini
> # Default severity for analyzer diagnostics with category 'Style'
> dotnet_analyzer_diagnostic.category-Style.severity = warning
> 
> # IDE0022: Use block body for methods
> csharp_style_expression_bodied_methods = when_on_single_line
> 
> # IDE0021: Use block body for constructors
> csharp_style_expression_bodied_constructors = when_on_single_line
> ```
> 
> The following code generates a warning:
> 
> ```cs
>     internal class LocalLinkValidator : ILinkValidator
>     {
>         private readonly string _baseDirectory;
> 
>         // Warning on the following line:
>         public LocalLinkValidator(string baseDirectory) => _baseDirectory = baseDirectory;
>     }
> ```
> 
> It's not clear to me why there is a warning? I'm using an expression bodied member when on single line per editorconfig.

That is because your editorconfig file configured it to warn when the body is of a single line, did you mean to make it to when it's not a single line?

**Comment by Youssef1313** [comment]
@AraHaan I think `csharp_style_expression_bodied_methods = when_on_single_line` should mean that this is the style I want. Not the style I would like to be warned for.

But adding @CyrusNajmabadi to confirm.
