### ISSUE TITLE
Distinguish linked files in quick info

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5349]
Since GTD doesn't change the navbar to show you which project the declaration is in, it would be nice if Quick Info showed some sort of disambiguating information (perhaps the project name).

**Comment by amcasey** [comment]
Relevant section of my PR: https://github.com/dotnet/roslyn/pull/5346/files#r39911256

**Comment by amcasey** [comment]
FYI @dpoeschl.  Let me know if you need more context.

**Comment by dpoeschl** [comment]
Thanks for filing this. Recommending for UpForGrabs.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about this from anyone else.  Need info to give us confidence this is worth investment.
