### ISSUE TITLE
Issue changes two items on the same "line" using Replace

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5350]
I am trying to move end of line comments to the previous line.

Original:
```
 Dim I as Integer = 1 ' Initialize 1
```
Desired
```
' Initialize 1
Dim I as Integer = 1
```
With the line below the trailing trivia gets replaced but the Leading Trivia is unchanged
```
        Dim newRoot As SyntaxNode = root.ReplaceNode(node.WithTrailingTrivia, node.WithTrailingTrivia(Trailing)).ReplaceToken(FirstTokenOnLine, NewFirstToken)
```
When I try reversing the order of the Replace, the leading trivia is correct but the training trivia is unchanged.
```
        Dim newRoot As SyntaxNode = root.ReplaceToken(FirstTokenOnLine, NewFirstToken).ReplaceNode(node.WithTrailingTrivia, node.WithTrailingTrivia(Trailing))
```
I have also tried to do them sequentially but the second change is ignored with no errors and Result = True
```
        'Dim newRoot As SyntaxNode = root.ReplaceNode(node.WithTrailingTrivia, node.WithTrailingTrivia(Trailing))
        Dim newRoot1 As SyntaxNode = newRoot .ReplaceToken(FirstTokenOnLine, NewFirstToken)
        Dim Result As Boolean = newRoot.Equals(newRoot1)
```

**Comment by brettfo** [comment]
First, I'd like to apologize for us taking so long to get back to you on this; we should have been more proactive and will try to do so in the future.

Looking at your sample code above it appears that you need to add a call to `.WithLeadingTrivia()` to re-add the comment that was originally stripped off.  Without seeing all of your code I can't say for certain, but you'll likely need something like this:

``` VB
Dim comment = node.GetTrailingTrivia() ' this will contain the "' Initialize I" comment
Dim newStatement = node.WithTrailingTrivia().WithLeadingTrivia(comment) ' this strips off the comment and re-adds it as leading trivia
Dim newRoot As SyntaxNode = root.ReplaceNode(node, newStatement)
```
