### ISSUE TITLE
if else code does not skip lines when pressing enter button

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/if-else-kodundaki-else-if-kodunun-enter-/1424524)._

🔗 [AB#1329480](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1329480)

---
[severity:It's more difficult to complete my work]
Langue Turkish;

if else kodunu kullanırken son parantezin ' } ' yanına else yazıp parantez açıp enter düğmesine basınca else satır atlıyor ama son parantezin ' } ' yanına else if yazıp parantez açıp enter düğmesine basınca satır atlamıyor.

Örnek;
static void Main(string[] args)
        {

Console.WriteLine("Hello World!");
            int number = Convert.ToInt32(Console.ReadLine());

if (number == 1)
            {
                Console.WriteLine("nfıosbhfıosg ");
            **}
            else 
           {

}**

Sorunun Olduğu Örnek;
static void Main(string[] args)
        {

Console.WriteLine("Hello World!");
            int number = Convert.ToInt32(Console.ReadLine());

if (number == 1)
            {
                Console.WriteLine("yaz");
            **}else if (number == 2) 
            { 

}**

![image](https://user-images.githubusercontent.com/1408396/118840978-b827be80-b87c-11eb-880b-4b314183e391.png)

---
#### Feedback Bot on 5/16/2021, 11:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/17/2021, 09:56 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
### Steps to reproduce

1. Type `if (true) {`
2. Press <kbd>Enter</kbd>
3. Type `}`
4. Type `else {`
5. Press <kbd>Enter</kbd>

### Expected results

After step 1:

```csharp
if (true) {$$ }
```

After step 2:

```csharp
if (true)
{
    $$
}
```

After step 3:

```csharp
if (true)
{
}$$
```

After step 4:

```csharp
if (true)
{
}else {$$ }
```

After step 5:

```csharp
if (true)
{
}
else
{
    $$
}
```

### Actual results

✔ After step 1:

```csharp
if (true) {$$ }
```

✔ After step 2:

```csharp
if (true)
{
    $$
}
```

✔ After step 3:

```csharp
if (true)
{
}$$
```

✔ After step 4:

```csharp
if (true)
{
}else {$$ }
```

❌ After step 5:

```csharp
if (true)
{
}else
{
    $$
}
```

### Variations

If you change Step 4 to "Type `els {`" (the `e` is omitted from typing and filled in by completion instead), the completion action will automatically move `else` to the next line leaving this result after step 4:

```csharp
if (true)
{
}
else {$$ }
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
