### ISSUE TITLE
ServiceHub.RoslynCodeAnalysisService.exe - high memory usage

### ISSUE THREAD

**Issue by ChrisonSimtian** [dotnet/roslyn#53528]
Hey,

I've installed the latest Visual Studio 2019 preview 4 this week and noticed that about 10-15 minutes after I load my solutions (~50-70 projects) the memory usage for this process goes up and up to over 10GB

From time to time VS warns me that "Visual Studio IntelliCode 2.2.1462.13379" is causing performance issues and asks me to turn it off.

I got a workaround for now, restarting VS every time it hits the memory cap... but would be nice to see this fixed in the next preview version :-)

**Comment by sharwell** [comment]
This needs to be filed using the Report a Problem tool so we can investigate it. Here's the standard information we would request for the scenario:

> Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.
>
> Based on the information provided so far, the most likely scenario to follow is for "Slowness and High CPU Issues". Please look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#slowness-and-high-cpu-issues
