### ISSUE TITLE
Automatic reload of .editorconfig when it is updated

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53556]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-reload-of-editorconfig-when-i/1427292)._

---
Currently, when a change is made to the .editorconfig file the solution has to be reloaded in order for the change to be recognised.
This is unhelpful in situations where as a developer I need to make changes to the analyser rules as I have to reload the entire solution just for them to show.

Having the functionality to automatically reload the .editorconfig, or a keybind to force an update when changes are made would lead to a much better user experience.

---
#### Feedback Bot on 5/19/2021, 11:47 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
> Currently, when a change is made to the .editorconfig file the solution has to be reloaded in order for the change to be recognised.

This is unexpected, and doesn't match the behavior we are observing. Can you provide detailed steps to reproduce this issue, including the expected result and actual result?

**Comment by HugoRoss** [comment]
Same here. Since maybe 2 years, the automatic reload does not work anymore, one has to close and re-open Visual Studio for it to recognize the ."editorconfig" change. I can confirm that it used to work but never in VS2022 and it stopped working in VS2019.

**Comment by CodePagesNet** [comment]
I am also observing that Visual Studio must be restarted in order for .editorconfig changes to take effect.
