### ISSUE TITLE
[Proposal] Automatic Semicolon Insertion in C#

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/roslyn#5355]
This might be a bit controversial :). But is there any good reason why there is no ASI in C#? I am curious if rules for ECMA Script http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf chapter 11.9 could also work in C#?

From practical point of view code without semicolons in Javascript/Typescript looks leaner and it is possible to write thousands of lines of code without using single semicolon (not counting `for (;;)` )

**Comment by HaloFour** [comment]
1. There is no value in it but a ton of effort would be required.
1. The language was not designed for it thus this change would introduce ambiguities.
1. C# shouldn't borrow [bad ideas](http://archive.oreilly.com/pub/a/javascript/excerpts/javascript-good-parts/awful-parts.html) from horribly designed languages (to be fair, *very* quickly hacked together languages due to stupid management-imposed deadlines, but the end result is the same).

To quote what was already said on this subject from CodePlex:

> Let’s put aside the discussion on whether we want to do this for a moment. Obviously there is a long discussion to be had there.

> Suppose we were to do this:

> C# was not designed to have the semicolon delimiter be optional, so unlike Visual Basic or Python there would be cases where this introduces ambiguity in the code's meaning. The correct thing to do here would be to have the compiler identify ambiguous cases and show a warning. Unfortunately nearly everyone compiles with warnings as errors, so this would essentially be a breaking change. It’s not that C# never introduces breaking changes, but when we do the break needs to be mitigated as much as possible and the potential benefit needs to be huge relative to the size of the break.

> My point is: even if we all collectively agreed to make the semicolon delimiter optional, the risk of breaking existing code or the expense of mitigating that risk is significant enough to cause us to rethink things. That doesn't mean it can't be done, just that doing it is going to be expensive. In my opinion, even if we had consensus and everyone wanted to do this, the bang-for-your-buck would not be significant enough compared to other potential features.

**Comment by dsaf** [comment]
> This might be a bit controversial :).
And the third time to be brought up.

How can this be a good idea:
![image](https://cloud.githubusercontent.com/assets/3845650/9976389/7045af0c-5eda-11e5-99a7-303a83c0d240.png)

**Comment by mkosieradzki** [comment]
@HaloFour Can you please link discussion from codeplex? I am unable to find it by its fragments. But it is definitely worth to be able to track previous discussion on the same issue.
@dsaf scenario you have mentioned:`return a + b` is really awful in javascript. It will not be the case in C#, because either function is void and `return a + b;` makes no sense or function is non-void and `return;` makes no sense

Second case is perfectly reasonable.

**Comment by HaloFour** [comment]
[Remove requirement for semicolon (;) at end of line](http://roslyn.codeplex.com/discussions/571190)
[Implicit Semicolon?](http://roslyn.codeplex.com/discussions/567407)

It's also come up a couple of times embedded in other issues/discussions.

You can't make the semicolon implicit without adding some form of significant whitespace, which will change the semantics of existing code.  The following would become ambiguous:

```cs
for (int i = 0; i < 10; i++)
a += b;
```

In my opinion it doesn't make sense to change the syntax of C# to match that of another language just for the sake of doing so.  Adoption of features from other languages is one thing, but making C# smell like JavaScript, Scala or Python syntactically adds nothing to C#.

**Comment by dsaf** [comment]
Also search for "semicolon" in the mega-thread #2136.

**Comment by mkosieradzki** [comment]
@HaloFour @dsaf Thanks guys for referencing those threads.

**Comment by eyalsk** [comment]
I'm not using semicolons in JavaScript anymore because the code looks much cleaner but I really don't want to see C# look like JavaScript, in C# these semicolons are consistent you either can add them or you can't I don't like the option in-between these two extremes very much.

**Comment by diryboy** [comment]
One day I wrote the following code in javascript
```javascript
return
{
  a: 0
}
```
And I was toasted.

No, please.

**Comment by paulomorgado** [comment]
Coding style matters because it reflects the best practices for each language.

In JavaScript, one should write code with opening curly braces on the line of the statement blog belongs to:

    return {
        a: 0
    };

That solves @diryboy's problem. But I wouldn't touch @eyalsk's JavaScrpt code even with a 10 foot pole.

**Comment by dsaf** [comment]
@paulomorgado 
Coding style reflects the personal preferences of language creators :). This is how C# handles it:

https://www.jetbrains.com/resharper/webhelp60/Reference__Options__Languages__CSharp__Formatting_Style__Braces_Layout.html

http://stackoverflow.com/questions/3048800/how-can-i-set-visual-studio-to-use-kr-style-bracketing

IMHO that's not @diryboy 's problem, it's a bug in the language design. The language should decide whether it has significant whitespace or not.

**Comment by eyalsk** [comment]
@paulomorgado so don't use NPM please because they are doing that too! why semicolons are so precious to you? my code is well covered with tests so how come semicolons make such a difference to you?

**Comment by dsaf** [comment]
@eyalsk Unit tests are merely a workaround for a lacking type system (even in C#). The more can be handed over to static analysis the better. That's why Roslyn rocks.

**Comment by eyalsk** [comment]
@dsaf Yeah, I was one of the first people to use CodeContracts when it was published, I know about that but @paulomorgado was speaking about my JavaScript code due to lack of semicolons.

If you understand ASI and you make sure your code is properly linted and you do your tests properly there's no need for semicolons, again, when we're speaking about JavaScript.

**Comment by JoergWMittag** [comment]
*Iff* you want to do this, Scala's Semicolon Inference might be a lot better role model than ECMAScript's Automatic Semicolon Insertion.

However, please note:

Even though
* Scala's syntax is simpler than ECMAScript's (and also C#'s)
* Scala was designed from the get-go for Semicolon Inference
* Scala got to learn from ECMAScript
* Scala was much more carefully designed

there are *still* cases where Semicolon Inference can surprise you, if you don't follow the official Scala style guide.

**Comment by ltlombardi** [comment]
Swift does this very well for me.
