### ISSUE TITLE
Removed CodeAnalysisRuleSet from csproj file, opening Active Ruleset finds another ruleset file at a higher directory level and opens it

### ISSUE THREAD

**Issue by sonsaw-ms** [dotnet/roslyn#53552]
**Version Used**: 

**Steps to Reproduce**:
I have a solution with many projects.
For a few projects, I was using a different ruleset file (A.ruleset), configured in each projects .csproj file via the CodeAnalysisRuleSet property.
I wanted to migrate to editorconfig as every time I open up the .ruleset file, I see a banner that highly recommends moving away from rulesets to editorconfig. So, I click the banner, save the new editorconfig. Remove CodeAnalysisRuleSet from each of the project (I care about), delete the ruleset file (A.ruleset).
When I go back into Project -> References -> Anaylzers -> set rule severity, I see another ruleset file located at a higher level in the solution hierarchy (B.ruleset) is being picked up and updated with any new rules configuration changes I make. How can I get my project to not look at any ruleset files at all? Why this new ruleset file getting picked up in my project where I have not even specified any ruleset file via CodeAnalysisRuleSet?

**Expected Behavior**:
Ruleset files should not be picked up as there is no CodeAnalysisRuleSet in the project.
**Actual Behavior**:
A ruleset file at a higher level in solution hierarchy is picked up

**Comment by mavasani** [comment]
Ruleset files are deprecated in favor of .editorconfig files starting 16.5. They are only supported for backwards compatibility. It is recommended that you migrate from ruleset to editorconfig following the documentation here: https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#convert-an-existing-ruleset-file-to-editorconfig-file
