### ISSUE TITLE
Resurrect(?) ability to expand/collapse to specific outline level

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53555]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Resurrect-ability-to-expandcollapse-/1411583)._

---
I'm sure that I remember being able to expand or collapse outlines to a _specific level_. I've been a fan of ReSharper for many years, so it's possible that this was something they added to Visual Studio once upon a time.

I like being able to partition code using `#region` and `#pragma region`, but the first step in navigating is usually to collapse things to a high-level outline. I usually have to drill down a level or two before I get the kind of "table of contents" view that I need (**Collapse to definitions** often collapses a whole file down to a single 'class' line, requiring that I then expand -- so not that useful).

This used to be a simple matter of hitting `Ctrl+<something>`, `1` through `9`, which would collapse or expand everything to the specified level. I went looking for that recently and discovered that it appears to be gone (I looked in **Tools** >**Customize**>**Commands**>**View**, but it's not there).

This is something I'd be using very frequently if it were still available. Can it be brought back (or implemented, if it was previously a 3rd-party thing)?

---
#### Feedback Bot on 5/2/2021, 01:53 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Moved to right team. closing this as external
