### ISSUE TITLE
Migrate the Code Analysis page to the new Project Properties UI

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#53567]
# Legacy projects

![image](https://user-images.githubusercontent.com/350947/118741223-24acb880-b891-11eb-9958-abf721c63ac7.png)

- "Run on build" controls `<RunCodeAnalysis>` (per configuration)
- "Suppress results from generated code" controls `<CodeAnalysisIgnoreGeneratedCode>` (per configuration)
- "Active rules" controls `<CodeAnalysisRuleSet>` (per configuration)

# SDK-style projects

![image](https://user-images.githubusercontent.com/350947/118740583-9421a880-b88f-11eb-97a2-22e0aeca4b4d.png)

- "Run on build" controls `<RunAnalyzersDuringBuild>`
- "Run on live analysis" controls `<RunAnalyzersDuringLiveAnalysis>` in the `.user` file
- "Enforce CodeStyle on build (experimental)" controls `<EnforceCodeStyleInBuild>`
- "Enable .NET Analyzers" controls `<EnableNETAnalyzers>`
- "Analysis level" controls `<AnalysisLevel>`
- Hyperlinks can be ported as-is

We need to investigate when these properties should be applied. They are not necessarily always applicable.

**Comment by jmarolf** [comment]
completed with https://github.com/dotnet/project-system/pull/7538
