### ISSUE TITLE
Suggestion: have option in Model.LookupSymbols to limit returns

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5357]
Right now LookupSymbols ether looks up everything associated with my Solution including all the DLL's I reference or I think I can limit it to one NameSpace. What is really needed it a way to limit it to one solution without looking at included libraries.

**Comment by CyrusNajmabadi** [comment]
This would need to go through an API proposal. 

in general though, it would be trivial to just filter out anything you don't care about.  The compiler APIs are extremely fast here as well (as they have to operate in the millisecond range to be fast enough for intellisense).

> or I think I can limit it to one NameSpace. 

Note: if you want to limit to one namespace, you can just ask for the children of that namespace.
