### ISSUE TITLE
Code Fix Error in Visual Studio

### ISSUE THREAD

**Issue by View12138** [dotnet/roslyn#53574]
### Description
When I return the `Anonymous type` in a method whose return type is `void`, the code fix suggests that I fix the method's return type to `var`. However, the contextual keyword 'var' may only appear within a local variable declaration (Compiler Error CS0825).
Please fix it.

### Configuration

version .NET5 in Visual Studio 16.9
OS: Windows 10 (x64)
### Regression?

1. Create a Simple Console Application in Visual Studio. 
```
public void Method()
{
    return new { A = 0, B = 1 };
}
```
2. use code fix(Alt+Enter)

**Comment by CyrusNajmabadi** [comment]
Yes. We should use 'object' here instead.

**Comment by View12138** [comment]
😊 Thanks. Of course I know how to use it. And I think it's a very minor bug with Code Fix in Roslyn Analyzer, although it doesn't affect the code running.

**Comment by Youssef1313** [comment]
There are two issues here:

1. `GenerateTypeSyntax` in the codefix is passed with no arguments (so default value of `allowVar` is true.

2. After fixing that and passing `allowVar` = false, here comes the second issue:

    https://github.com/dotnet/roslyn/blob/3a64531ddd727a5d54a6571144891bacb208efb2/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.cs#L44-L49

**Comment by CyrusNajmabadi** [comment]
If `allowVar` is false there, we should probably just generate `object`.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi found out this will regress other features (thanks to test coverage). Specifically, generate variable and introduce variable.

```diff
  Failed Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings.IntroduceVariable.IntroduceVariableTests.TestAnonymousTypeBody [43 ms]
  Error Message:
   Actual and expected values differ. Expected shown in baseline of diff:
 class Program
 {
     void Main()
     {
-        var p = new { A = 0 };
+        object p = new { A = 0 };
         var a = p;
     }
 }
```

```diff
  Failed Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.GenerateVariable.GenerateVariableTests.TestGenerateFromAssign2 [54 ms]
  Error Message:
   Actual and expected values differ. Expected shown in baseline of diff:
 class Program
 {
     void Main()
     {
-        var undefined = new { P = "1" };
+        object undefined = new { P = "1" };
     }
 }
```

I think we'd need to special-case this in the refactoring itself.

**Comment by CyrusNajmabadi** [comment]
> Specifically, generate variable and introduce variable.

Why are these passing allowVar=false?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi They use the default value which is `true`. So we probably first need to check why `var` is normally not produced when `allowVar` is true (which may be related to code style settings for implicit vs explicit type usage).

But actually for anonymous type, we'd want to use `var` for variables regardless code style settings, because anonymous types can't be expressed by explicit type (other than object or dynamic - which is different than `var`, so it's not a matter of style here).

- First thing to do is to confirm that `allowVar` isn't producing `var` due to code style settings because I'm not sure about that.
    - And if that's the case, then I'd be expecting this refactoring to even be buggy for things other than anonymous types?

**Comment by CyrusNajmabadi** [comment]
All that sounds reasonable :)  let me know how it goes.
