### ISSUE TITLE
[Responsiveness] CommandLineArguments.Parse substrings every argument twice causing lots of unneeded allocations (1% - 5%) during solution load

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#53570]
**Version Used**: 
17.0.0 Preview 1.0 [31313.406.main]

**Steps to Reproduce**:

CommandLineArguments.Parse is called _a lot_ during solution open by both Roslyn and the project system.

[Trace](https://microsoft-my.sharepoint.com/personal/paulv_microsoft_com/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly9taWNyb3NvZnQtbXkuc2hhcmVwb2ludC5jb20vOmY6L3AvcGF1bHYvRXRUY1d3X0FBb1pLc29WMVl5ajdUV2NCNEtIU1hkRWs1TTktd2JKMUhKWXpGQT9ydGltZT1wdGpQZlBFYjJVZw&id=%2Fpersonal%2Fpaulv%5Fmicrosoft%5Fcom%2FDocuments%2Fscale%2Ftraces%2F17%2E0%2E0%20Preview%201%2E0%20%5B31313%2E406%2Emain%5D%2Forchardcore%2Drc2%2FSolution%5F001%5F0156%5FGeneral%5Fnocache)

![image](https://user-images.githubusercontent.com/1103906/119065792-ab909b00-ba21-11eb-9bf1-89c20302a767.png)

This code double-parses every option twice just to find the ruleset option: https://github.com/dotnet/roslyn/blob/31103b6174bc95de900fe3f2fa05b3b2dff66437/src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs#L143-L146

**Comment by davkean** [comment]
@jinujoseph @jaredpar Can we please assign this out? This item is being tracked by the Dev17 perf workstream.

**Comment by davkean** [comment]
In solution open [trace](https://microsoft.sharepoint.com/:f:/t/VSIDEPerformance/EgX6IU5cp5pBqPyjRyW8l4QBbAKCq2YhUqSdO58YhaxhEw?e=dz8yor) of 936 projects, command-line parsing on these two paths is responsible for 5.3% or 1.5 GB of allocations:

![image](https://user-images.githubusercontent.com/1103906/123739396-f091d200-d8e9-11eb-994f-ea9bc6914ae9.png)

**Comment by jaredpar** [comment]
Been hacking on this today and made some improvements here. Created a couple of benchmarks for 

1. Compiling Microsoft.CodeAnalysis.CSharp
2. Compiling a simple razor project

The results

Before

|                         Method |       Mean |    Error |   StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|------------------------------- |-----------:|---------:|---------:|---------:|--------:|------:|----------:|
| ParseCSharpCompilerCommandLine | 1,127.3 us | 20.52 us | 24.42 us | 250.0000 | 80.0781 |     - |    876 KB |
|  ParseRazorCompilerCommandLine |   486.1 us |  7.19 us |  6.38 us | 350.0977 | 56.6406 |     - |    571 KB |

After

|                         Method |     Mean |   Error |  StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|------------------------------- |---------:|--------:|--------:|---------:|--------:|------:|----------:|
| ParseCSharpCompilerCommandLine | 630.3 us | 8.54 us | 7.57 us | 147.4609 | 14.6484 |     - |    223 KB |
|  ParseRazorCompilerCommandLine | 232.4 us | 0.73 us | 0.61 us |  86.1816 | 14.1602 |     - |    149 KB |

Possible I can take this a bit lower in a few places but think I've fixed all the low hanging fruit here.

**Comment by davkean** [comment]
Nice!
