### ISSUE TITLE
[Responsiveness] CSharpFormattingOptions2 static constructor consumed 3% of UI thread during solution open

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#53572]
**Version Used**: 
17.0.0 Preview 1.0 [31313.406.main]

**Steps to Reproduce**:

[Trace](https://microsoft-my.sharepoint.com/personal/paulv_microsoft_com/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly9taWNyb3NvZnQtbXkuc2hhcmVwb2ludC5jb20vOmY6L3AvcGF1bHYvRXRUY1d3X0FBb1pLc29WMVl5ajdUV2NCNEtIU1hkRWs1TTktd2JKMUhKWXpGQT9ydGltZT1wdGpQZlBFYjJVZw&id=%2Fpersonal%2Fpaulv%5Fmicrosoft%5Fcom%2FDocuments%2Fscale%2Ftraces%2F17%2E0%2E0%20Preview%201%2E0%20%5B31313%2E406%2Emain%5D%2Forchardcore%2Drc2%2FSolution%5F003%5F0468%5FGeneral%5Fnocache)

![image](https://user-images.githubusercontent.com/1103906/119070959-455d4580-ba2c-11eb-811a-6c2cb0e85a81.png)

Between the first unresponsiveness on the UI thread between 2,010.503 and 35,394.503, CSharpFormattingOptions2 static constructor consumed 3% of the UI thread, or 550ms.

I see some JIT'ing in there, but otherwise, the trace doesn't have enough information to make this actionable, and it will need to be specifically looked at.

**Comment by sharwell** [comment]
I'm not able to access the linked trace.

**Comment by davkean** [comment]
@sharwell  Can you ping @panopticoncentral to get access to it?

**Comment by davkean** [comment]
I saw this in another trace and we captured and this looks almost entirely JIT and NGEN fixups, I'm guessing the code is very large and the overhead of this is quite large. It would be nice not to pay for this on the UI thread.

**Comment by sharwell** [comment]
Is there an overview document for strategies to avoid JIT/NGEN on the UI thread?

**Comment by CyrusNajmabadi** [comment]
I would love to hear about this as well :-)

**Comment by sharwell** [comment]
520ms (95%) is JIT, and 339ms is JIT in System.Collections.Immutable. Considering the complexity of optprof as it relates to .NET Framework and we already have a replacement approach targeting future .NET Core releases, I'm going to mark this one as blocked / wontfix.

**Comment by CyrusNajmabadi** [comment]
> and we already have a replacement approach targeting future .NET Core releases,

Can you give a little more information on this bit.  I'm not sure i'm aware of what you're referring to.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Gotcha.  Thanks!
