### ISSUE TITLE
[Responsiveness] AlwaysActiveLanguageClientEventListener.StartListening consumed 5% of the UI thread during solution open

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#53573]
**Version Used**: 
17.0.0 Preview 1.0 [31313.406.main]

**Steps to Reproduce**:

[Trace](https://microsoft-my.sharepoint.com/personal/paulv_microsoft_com/_layouts/15/onedrive.aspx?originalPath=aHR0cHM6Ly9taWNyb3NvZnQtbXkuc2hhcmVwb2ludC5jb20vOmY6L3AvcGF1bHYvRXRUY1d3X0FBb1pLc29WMVl5ajdUV2NCNEtIU1hkRWs1TTktd2JKMUhKWXpGQT9ydGltZT1wdGpQZlBFYjJVZw&id=%2Fpersonal%2Fpaulv%5Fmicrosoft%5Fcom%2FDocuments%2Fscale%2Ftraces%2F17%2E0%2E0%20Preview%201%2E0%20%5B31313%2E406%2Emain%5D%2Forchardcore%2Drc2%2FSolution%5F003%5F0468%5FGeneral%5Fnocache)

![image](https://user-images.githubusercontent.com/1103906/119071690-9d487c00-ba2d-11eb-8eb5-48c2614cf9dc.png)

Between the first unresponsiveness on the UI thread between 2,010.503 and 35,394.503, AlwaysActiveLanguageClientEventListener.StartListening consumes 5% of the UI thread starting up what appears to be LSP and MEF initialization.

**Comment by CyrusNajmabadi** [comment]
@davkean the link to the trace didn't seem to work.  can you resend?

**Comment by davkean** [comment]
@panopticoncentral  Can you give access to @CyrusNajmabadi?

**Comment by davkean** [comment]
Thanks!
