### ISSUE TITLE
CS0181

### ISSUE THREAD

**Issue by msa-combination** [dotnet/roslyn#53588]
**Version Used**: 
5.0

**Steps to Reproduce**:

```csharp
   class CustomAttribute : Attribute
    {
        public CustomAttribute(DateTime param)
        {
        }
    }

    class Class1
    {
        [Custom(DateTime.Now)]
        void Method()
        {
        }
    }
```
**Expected Behavior**:

Error CS0181 reported and documentation about that

**Actual Behavior**:

Missing documentation

**Comment by Youssef1313** [comment]
@msa-combination It's not clear to me why you'd expect CS0180 here?

CS0180 says:

> '{0}' cannot be both extern and abstract

https://github.com/dotnet/roslyn/blob/144951b936a7f05e0245afe8ca9eb179607aaa0d/src/Compilers/CSharp/Portable/Errors/ErrorCode.cs#L157-L158

So I believe CS0181 is the correct diagnostic here.

The documentation issue is tracked by https://github.com/dotnet/docs/issues/24002.

**Comment by jaredpar** [comment]
Closing as the documentation portion is tracked by dotnet/docs#24002.
