### ISSUE TITLE
Obsolete/remove SyntaxKind.DataKeyword API

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53589]
## Background and Motivation

In early development of records, SyntaxKind.DataKeyword was added, and it was unintentionally leftover.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.CSharp
{
    public enum SyntaxKind : ushort
    {
-       DataKeyword = 8441,
    }
}
```

or

```diff
namespace Microsoft.CodeAnalysis.CSharp
{
    public enum SyntaxKind : ushort
    {
+       [Obsolete("This SyntaxKind is not used.")]
        DataKeyword = 8441,
    }
}
```

or do it two steps, obsolete, then remove in a later version.

## Usage Examples

N/A

## Alternative Designs

N/A

## Risks

Deletion of this API has very low risk. First, it's expected that very very few will be using it. Anyone who is using it has already a broken code.

The only code I found on GitHub using grep.app is:

https://github.com/JosefPihrt/Roslynator/blob/2ffa83ac7155ccf546833abefafcb1607af52df3/src/Tests/CSharp.Tests/SyntaxKindTests.cs#L535

cc @333fred

**Comment by 333fred** [comment]
Compat council considered this. We should remove the SyntaxKind, leaving the spot open. Our standard practice in roslyn is to leave a comment that the spot is open for future use.
