### ISSUE TITLE
16.10 - Somtimes I see "Object reference is not set to an instance of a object" when i try to save a edited file

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#53583]
**Version Used**: 
```
Microsoft Visual Studio Community 2019 Preview
Version 16.10.0 Preview 4.0
VisualStudio.16.Preview/16.10.0-pre.4.0+31313.381
Microsoft .NET Framework
Version 4.8.04084
```

Since the first 16.10 preview version
I get sometimes a "Object reference is not set to an instance of a object"
when i try to save a edited file.

There a no yellow banner with more information.
The current workaround (for me) is to restart Visual Studio and try it again, but all files changes are lost.

**Steps to Reproduce**:

1.  Open a file
2.  Edit the file
3. Save the file

**Expected Behavior**:
No error

**Actual Behavior**:
![2021-05-21 08_45_52-](https://user-images.githubusercontent.com/17874713/119094218-0a99e400-ba11-11eb-9ed3-a43d290c9fc4.png)

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue :)    It will have to be reported through https://developercommunity.visualstudio.com/home

Sorry!

**Comment by TobiasSekan** [comment]
@CyrusNajmabadi 
Okay , thanks for info :-)
