### ISSUE TITLE
Weird Formatter behaviour when formatting multidimensional arrays

### ISSUE THREAD

**Issue by HellBrick** [dotnet/roslyn#5358]
Let's jump right to the code:
```csharp
private void FormatterWeirdnessExample()
{
	AdhocWorkspace workspace = new AdhocWorkspace();
	workspace.Options = workspace.Options
		.WithChangedOption( CSharpFormattingOptions.SpaceAfterComma, true )
		.WithChangedOption( CSharpFormattingOptions.SpaceBetweenEmptySquareBrackets, false )
		.WithChangedOption( CSharpFormattingOptions.SpaceWithinSquareBrackets, true );

	SyntaxTree tree = CSharpSyntaxTree.ParseText( "int[ , ] array = new int[ 1, 1 ];" );
	SyntaxNode root = tree.GetRoot();
	Debug.WriteLine( root );

	IList<TextChange> changes = Formatter.GetFormattedTextChanges( root, workspace );
	foreach ( var change in changes )
		Debug.WriteLine( change );

	SyntaxNode formatted = Formatter.Format( root, workspace );
	Debug.WriteLine( formatted );
}
```

And here's the output:
```
int[ , ] array = new int[ 1, 1 ];
TextChange: { [4..5), "" }
TextChange: { [6..7), "" }
TextChange: { [7..7), " " }
int[, ] array = new int[ 1, 1 ];
```

First of all, the result of `Formatter.Format` looks kind of strange. I expected to get either the spaces both before and after the comma (`int[ , ]`) or no spaces around the comma at all (`int[,]`), but getting just the space after looks unexpected (and probably a bit ugly).

Second, the contradicting changes (`TextChange: { [6..7), "" }` and `TextChange: { [7..7), " " }`) are very confusing. That's actually how I stumbled upon this issue: I was writing an analyzer that checks if the document violates the formatting rules, so I used `GetFormattedTextChanges()` to detect the possible formatting changes. But apparently it's possible for the text changes to negate each other so the `Format()` method doesn't actually change anything. I don't know if it's a bug or a feature, but it definitely makes using `GetFormattedTextChanges()` a lot more difficult.

**Comment by diryboy** [comment]
> SpaceWithinSquareBrackets, true

So the result should be `int[ , ] ...`?

It's interesting because it looks like a conflict when `SpaceWithinSquareBrackets, false` and `SpaceAfterComma, true` but actually not.

**Comment by HellBrick** [comment]
> So the result should be `int[ , ]` ...?

That's a tricky corner case, but I'd prefer `int[ , ]` here. Or, to be more precise, I think `SpaceBetweenEmptySquareBrackets` shouldn't consider this its jurisdiction and the behaviour should be controlled by `SpaceWithinSquareBrackets`

**Comment by Pilchie** [comment]
We should just look at what VS2013 does for the various combinations of these options.

**Comment by diryboy** [comment]
In VS2013, `[,]` is not treated as empty, and always add/remove spaces no matter what `SpaceAfterComma` is.

**Comment by diryboy** [comment]
Interesting, in VS2015, regardless what `SpaceAfterComma` is
`[, ]` when `SpaceBetweenEmptySquareBrackets, false` & `SpaceWithinSquareBrackets, true`
`[ ,]` when `SpaceBetweenEmptySquareBrackets, true` & `SpaceWithinSquareBrackets, false`
`[ , ]` when `SpaceBetweenEmptySquareBrackets, true` & `SpaceWithinSquareBrackets, true`
