### ISSUE TITLE
Cannot use nameof operator when parameter nameof exist

### ISSUE THREAD

**Issue by YvvkiRika** [dotnet/roslyn#53586]
**Version Used**: 
Latest

**Steps to Reproduce**:
```cs
string Method(string nameof) 
{
  return nameof(nameof);
}
```
or
```cs
string Method(string @nameof) 
{
  return nameof(@nameof);
}
```

**Expected Behavior**:
Returns a string: "nameof"

**Actual Behavior**:
CS0149: Method name expected

**Comment by Youssef1313** [comment]
@smol-rika This is currently not allowed per language specification, but there is a proposal (https://github.com/dotnet/csharplang/issues/373) to allow it.

**Comment by smol-rika** [comment]
@Youssef1313 It's more of a bug rather than a proposal.

![image](https://user-images.githubusercontent.com/69618058/119108102-0b9b3780-ba4a-11eb-8ec0-2ed3999fc58f.png)

At least make the compiler throws an error when trying to name the parameter `nameof`.

**Comment by Youssef1313** [comment]
Hmm, I might be incorrect, but I think `Method1` should contain an error prior the proposal.

@jcouv Was the implementation of the proposal (or part of it) implemented in `main`?

**Comment by jcouv** [comment]
@Youssef1313 I don't think this scenario would be affected by the proposal https://github.com/dotnet/csharplang/issues/373. That proposal is to allow `nameof(parameter)` in the attributes on the method. 
For example: `[NotNullIfNotNull(nameof(parameter))]`.

**Comment by Youssef1313** [comment]
@jcouv Ahh, what I was saying 😄 Certainly I'm incorrect (feeling dump actually).

However, the current behavior is still by design @yvvki.

Quoting the relevant part of spec:

> Grammatically speaking, the *named_entity* operand is always an expression. Because `nameof` is not a reserved keyword, a nameof expression is always syntactically ambiguous with an invocation of the simple name `nameof`. For compatibility reasons, if a name lookup (Simple names) of the name `nameof` succeeds, the expression is treated as an *invocation_expression* -- regardless of whether the invocation is legal. Otherwise it is a *nameof_expression*.

See https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#nameof-expressions
