### ISSUE TITLE
When using "Convert to Full Property" the generated filed isn't kept together the property definition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-using-Convert-to-Full-Property-th/1427413)._

---
Microsoft Visual Studio Professional 2019 Version 16.9.5 + Vb.Net

When using "Converto to full property" Visual studio tries to keep all the fields in a block near the top of the class definition instead of keeping the fields just before the property definition.
When there are fields already defined in the class the newly generated field is put right under the first field over the property we are converting to full, this is probably an unwanted behavior.

To clarify see this example:
```
Class Test
	Private _Gino As Object
	Public Property Gino
		Get
			Return _Gino
		End Get
		Set
			_Gino = Value
		End Set
	End Property

Private _Pino As Object
	Property Pino
		Get
			Return _Pino
		End Get
		Set
			_Pino = Value
		End Set
	End Property

Property Rino As Object

End Class
```

Using "Converto to full property" on Rino property, the result is as follows:

```
Class Test
	Private _Gino As Object
	Public Property Gino
		Get
			Return _Gino
		End Get
		Set
			_Gino = Value
		End Set
	End Property

Private _Pino As Object
	Private _Rino As Object '<-- this should go up (near the top of the class) or down (near the property definition)

Property Pino
		Get
			Return _Pino
		End Get
		Set
			_Pino = Value
		End Set
	End Property

Property Rino As Object
		Get
			Return _Rino
		End Get
		Set
			_Rino = Value
		End Set
	End Property
End Class
```

When there are multiple fields already defined within the properties it becomes very annoying.

There should be an option to allow the user decide to keep the fields on the top of the class (the real top) alltogether or to keep them near the single property definition.

Thank you.
Matteo

---
#### Feedback Bot on 5/19/2021, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to be chanding these experiences.
