### ISSUE TITLE
Code fix preview window scrollbar doesn't respect scroll location if you mouse scroll

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#5360]
Repro:
1. Create a large interface
2. Implement said interface on a class
3. CTRL+. and and hover over Implement interface to see preview
4. Use Mouse+wheel to scroll window

Expected: For the scrollbar of preview window to respect actual scroll position
Actual: It doesn't move

![image](https://cloud.githubusercontent.com/assets/1103906/9981936/31ed1550-5f80-11e5-91ff-597d9a7623b8.png)

**Comment by dpoeschl** [comment]
Moving the scrollbar manually actually scrolls the [PreviewScrollViewer](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/PreviewPane/PreviewPane.xaml,104), but mouse-based scrolling is getting consumed by some other control in this case. I tried to see if the [previewElement](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/PreviewPane/PreviewPane.xaml.cs,8a07bb790f52c6d6,references) itself (constructed from the ```IWpfDifferenceViewer```) was consuming the events, but didn't see anything obvious there. Maybe some more deeply nested part of the ```IWpfDifferenceViewer``` is handling the scrolling...

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and investment here.  We expect preview to be picked up by the platform.
