### ISSUE TITLE
Incremental Source Generators should support multiple output types

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#53608]
Currently, incremental generators can only support a single output type (source). 

We should add more types of output such as 
- Artifacts
- Embedded Resources
- Additional Files

We also need a way for the driver host to specify which kind of outputs it should run for (IDE doesn't run artifacts for instance).

**Comment by PathogenDavid** [comment]
@chsienki I'm probably blind, but can you point me towards the APIs added for this? There's no PR linked to this issue and I can't find any recently merged that correspond to it.

**Comment by chsienki** [comment]
@PathogenDavid This issue was tracking the ability to provide multiple types, not necessarily implementing the listed things. The change to support multiple types was introduced with https://github.com/dotnet/roslyn/pull/54798. We currently only support source + implementation only outputs, but the infrastructure to add more types in now in place.

**Comment by PathogenDavid** [comment]
@chsienki Ah, that makes sense. Thanks for the clarification!

Safe to assume implementing the listed things is not currently scheduled then?
