### ISSUE TITLE
CSharpSyntaxGenerator does not support adding interface members with a default implementation

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#53605]
**Version Used**: 3.9.0-3.final. The failing code is in `main` at https://github.com/dotnet/roslyn/blob/17facfacf5fce15abf1280e5de3e25ad46dca6bd/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L771-L796

**Steps to Reproduce**:

1. Given a  `SyntaxGenerator` named `generator` as part of a code-fix running in C#, an `IMethodSymbol` named `method`, and a `SyntaxNode` named `declaration` that represents an `interface`,  run the following snippet:

```csharp

SyntaxNode methodDecl = generator.MethodDeclaration(method);
methodDecl = generator.WithModifiers(methodDecl, generator.GetModifiers(declaration).WithIsAbstract(false));
methodDecl = generator.WithStatements(methodDecl, generator.ThrowStatement(generator.NullLiteralExpression()));
declaration = generator.AddMembers(declaration, methodDecl);
```

**Expected Behavior**:

The generated code in `declaration` will have a method based on `method` that has the following body:

```csharp
{
    throw null;
}
```

**Actual Behavior**:

The generated code will have an interface member declaration with no body.

Based on the code in Roslyn linked above, this bug will be hit for properties, indexers, and event declarations as well.

This is blocking providing the code fixes as part of https://github.com/dotnet/runtime/issues/41529

**Comment by CyrusNajmabadi** [comment]
This is about SyntaxGenerator not SourceGenerator.

**Comment by jkoritzinsky** [comment]
Sorry about that. Fixed the content of the issue since you already fixed the title.

**Comment by jinujoseph** [comment]
Assigning to Cyrus to review the API

**Comment by CyrusNajmabadi** [comment]
This is challenging as we've always supported generating interface members by taking a normal member and just adding it to an interface.  We toss things like the bodies in this case.  So it's very likely that code exists that depends on that behavior.  So it could be extremely problematic to change that now.  

It's not clear what a viable approach would be here except maybe to allow AddMembers to specify some new behaviors here that can be opted into.

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of feedback, and this not blockign anyone currently.
