### ISSUE TITLE
[16.9] Misisng new line on new class file via QuickAction

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#53616]
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.9.6
VisualStudio.16.Release/16.9.6+31313.79
Microsoft .NET Framework
Version 4.8.04084

**Steps to Reproduce**:

1. Make sure `Edit -> Advanced -> View white space` is active.
2.  Write a line with a property with a unknown type, like `public Test MyTest { get; set; }`
3. Open the `QuickAction` and click on `Generate class "Test" in new file`
4. Open the new generate file `Test.cs`

**Expected Behavior**:
The new file `Test.cs`  should have a new line at the end of the file.

**Actual Behavior**:
The new file `Test.cs`  have no new line at the end of the file.

**Additional Info**
A new generated file via the `Project Explorer` have always a new line at the end of the file.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
