### ISSUE TITLE
New IOperation: IAttributeOperation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53618]
## Background and Motivation

Currently, an attribute has a "None" operation. See https://github.com/dotnet/roslyn/issues/18198.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Operations
{
+    public interface IAttributeOperation : IOperation
+    {
+        /// <summary>
+        /// The arguments passed to the attribute constructor.
+        /// </summary>
+        ImmutableArray<IArgumentOperation> Arguments { get; }
+
+        /// <summary>
+        /// The named arguments of the given attribute.
+        /// </summary>
+        ImmutableArray<ISimpleAssignmentOperation> NamedArguments { get; }
+    }
}
```

---

**Updated proposal based on API review outcome:**

```diff
namespace Microsoft.CodeAnalysis.Operations
{
+    public interface IAttributeOperation : IOperation
+    {
+        /// <summary>
+        /// The operation representing the attribute. This is either an IObjectCreationOperation or IInvalidOperation.
+        /// </summary>
+        IOperation Operation { get; }
+    }
}
```

## Usage Examples

```csharp
public void M(SemanticModel model, AttributeSyntax attribute)
{
    var operation = model.GetOperation(attribute);
    if (operation is IAttributeOperation attributeOperation)
    {
        // Do something with attributeOperation.Arguments or attributeOperation.NamedArguments
    }
}
```

One possible real use case is https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Resources/CSharpMarkAssembliesWithNeutralResourcesLanguage.cs, which currently registers a syntax action for AttributeSyntax nodes.

https://github.com/dotnet/roslyn/blob/main/src/Analyzers/CSharp/Analyzers/RemoveUnnecessarySuppressions/CSharpRemoveUnnecessaryAttributeSuppressionsDiagnosticAnalyzer.cs is possible to benefit from this too, and potentially other 3rd party analyzers as well.

## Alternative Designs

N/A

## Risks

Nothing I can see.

**Comment by Youssef1313** [comment]
Tagging @mavasani, in case you have suggestions for APIs other than Arguments and NamedArguments

**Comment by 333fred** [comment]
## API Review

* We'll defer giving information about the attribute target (ie, the field/method/property/etc the attribute is applied to) to future feedback. It's not a cheap thing to track because we don't track it today, and we'd prefer users to move from Symbols -> Operations, not the other way around.
* Should have a single `IOperation` child instead, which either be an `IObjectCreationOperation` for success cases, or some form of `IInvalidOperation` for invalid cases where a constructor wasn't bound.

**Comment by Youssef1313** [comment]
@333fred How IObjectCreationOperation is going to fit initializing attribute members? e.g:

```csharp
using System;

public class MyAttribute : Attribute
{
    public int Prop1 { get; set; }

    public MyAttribute(int ctorArg) {}
}

[My(0, Prop1 = 1)]
public class C {}
```

**Comment by Youssef1313** [comment]
> * Should have a single `IOperation` child instead, which either be an `IObjectCreationOperation` for success cases, or some form of `IInvalidOperation` for invalid cases where a constructor wasn't bound.

@333fred Any advantage to having a generic `IOperation` that could either be object creation or invalid over a nullable object creation operation? IMO a nullable `IObjectCreationOperation` is better. What do you think?

I'll update the proposal once it's decided which way this should go.

**Comment by 333fred** [comment]
> @333fred Any advantage to having a generic `IOperation` that could either be object creation or invalid over a nullable object creation operation?

A nullable object creation cannot represent the scenario.

**Comment by Youssef1313** [comment]
> > @333fred Any advantage to having a generic `IOperation` that could either be object creation or invalid over a nullable object creation operation?
> 
> A nullable object creation cannot represent the scenario.

I don't get why it cannot. We just use `null` instead of IInvalidOperation. But I updated the proposal anyway to reflect the API review outcome. Is it ready to implement?

**Comment by 333fred** [comment]
> I don't get why it cannot. We can just use `null` instead of IInvalidOperation.

The invalid operation will contain information. For example, maybe that's the only use of some constant value. In general, we need to fully represent the tree in both success and bad scenarios, dropping arguments is not acceptable. 

With the change, the proposal looks good, though I think we'll likely bikeshed on the name.

**Comment by chsienki** [comment]
# Notes

## Breaks users of existing work arounds
Today any user who wants to do this must workaround by looking for `Operation.None`. This will break those users as they need to remove their workarounds. We think this is ok; generally anything with `None` is just a placeholder, and we are ok with breaking those.

## Should we have the Target?
We may want to have the target operation that this attribute applies to. In general you can just use `Parent` as the attribute should be a child of the thing it is applied to. The separate interface gives us an option to add it later if we determine it needed.

**Comment by CyrusNajmabadi** [comment]
This woudl be very nice to have.  I just ran into this myself in the IDE side and had to give up using IOp and switch back to semantic model because of this.

**Comment by CyrusNajmabadi** [comment]
Note: i think the attribute-argument node itself shoudl still map to an IOp (just like with a normal argument node).

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Yup it will be `IArgumentOperation`. I have made a small progress on this couple of months ago and I had forgotten it. I'll see if I can continue working on it and get a PR ready.

**Comment by Youssef1313** [comment]
> * Should have a single `IOperation` child instead, which either be an `IObjectCreationOperation` for success cases, or some form of `IInvalidOperation` for invalid cases where a constructor wasn't bound.

@333fred This alternative proposal is problematic since the "single `IOperation` child" and its parent (the `IAttributeOperation`) will have the same syntax node. A syntax node can't have multiple `IOperation`s (unless we mark one of them as implicit).

https://github.com/dotnet/roslyn/blob/12c430ead949e17caaf610222444f777ced766cb/src/Compilers/Core/Portable/Operations/OperationMapBuilder.cs#L63-L72

**Comment by 333fred** [comment]
> unless we mark one of them as implicit

Yep, that is what will need to happen. The IAttributeOperation will be implicit.

**Comment by Youssef1313** [comment]
@333fred I think it should be the other way around? It looks like `GetOperation` returns the non-implicit operation when given a syntax node with multiple operations. We want `GetOperation` to return `IAttributeOperation`, so it shouldn't be implicit. Anything I'm missing?

**Comment by 333fred** [comment]
It would be a breaking change.

**Comment by Youssef1313** [comment]
@333fred I'm not sure what you mean. Introducing a new `IOperation` for attributes will always be a breaking change regardless. It was noted in https://github.com/dotnet/roslyn/issues/53618#issuecomment-881115567 that the breaking is okay.

**Comment by 333fred** [comment]
@Youssef1313 can you share the exact syntax nodes being talked about here?

**Comment by 333fred** [comment]
I understand. I want to understand what the tree is here, and what nodes each element in the tree corresponds to.

**Comment by Youssef1313** [comment]
@333fred There are couple of tests in #59369

**Comment by 333fred** [comment]
Alright, looking over the tests, I do agree that the object creation should be implicit, while the attribute operation itself should be the explicit node.
