### ISSUE TITLE
Can't build Roslyn

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/roslyn#53629]
**Version Used**: main

**Steps to Reproduce**:

- clone roslyn (I'm running ubuntu).
- run `./restore.sh`

I saw a whole lot of errors that looked like this:

```
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.net.build.extensions/index.json'.
  Network is unreachable (pkgs.dev.azure.com:443)
    Network is unreachable
```

It wasn't just that package - it was a whole bunch of packages.

When I navigate to that url I get:

```json
{
  "$id": "1",
  "innerException": null,
  "message": "Can't find the package 'microsoft.net.build.extensions' in feed 'dotnet-tools'.",
  "typeName": "Microsoft.VisualStudio.Services.NuGet.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.NuGet.WebApi",
  "typeKey": "PackageNotFoundException",
  "errorCode": 0,
  "eventId": 3000
}
```

**Comment by Youssef1313** [comment]
Not sure if running `nuget locals http-cache -clear` can help here. May you try this?

**Comment by Youssef1313** [comment]
fwiw, this package is in `dotnet-public` feed.

https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/microsoft.net.build.extensions/index.json

**Comment by YairHalberstadt** [comment]
> nuget locals http-cache -clear

It didn't work :-(

**Comment by Youssef1313** [comment]
I'm not sure what may be going on then. But it seems like you're not alone. https://github.com/dotnet/arcade/issues/7379 (It doesn't have extra information though).

**Comment by JoeRobich** [comment]
@YairHalberstadt Sorry you ran into issue restoring. Are you still seeing this issue?

**Comment by JoeRobich** [comment]
I am going to close this issue. Please reopen it if you are still experiencing issues building.
