### ISSUE TITLE
Warn on readonly SpinLock fields

### ISSUE THREAD

**Issue by JC3** [dotnet/roslyn#53620]
**Brief description:**

Would like to see Roslyn warn if you've got a `System.Threading.SpinLock` in a `readonly` field, as the lock will not function correctly in this case, and the exceptions that are thrown can be difficult to interpret ([for example](https://stackoverflow.com/a/11225279/616460)). 

I think this'd be a good one to catch.

**Languages applicable:**

I'm only familiar with C#.

**Code example that the analyzer should report:**

    readonly SpinLock someLock;
    // presence of initializer at declaration point does not matter.

Where the suggested fix is to remove the `readonly` attribute.

**Comment by Youssef1313** [comment]
Looks like a candidate for CAxxxx about runtime API usage (I don't personally think it's a warning wave candidate).

**Comment by Youssef1313** [comment]
This is already a candidate. See https://github.com/dotnet/runtime/issues/33773.

**Comment by JC3** [comment]
> Looks like a candidate for CAxxxx about runtime API usage (I don't personally think it's a warning wave candidate).

That makes way more sense than what I said.

**Comment by sharwell** [comment]
Duplicate of dotnet/runtime#33773.

**Comment by RRQM** [comment]
I hope to include this in the analyzer. I believe that when SpinLock is set to readonly, even during compilation, giving an error is not an exaggeration.
