### ISSUE TITLE
`SyntaxGenerator.WithModifiers` inserts `NotOverridable` instead of `NotInheritable`

### ISSUE THREAD

**Issue by NewellClark** [dotnet/roslyn#53627]
**Version Used**: 
6.0.100-preview.3.21202.5

**Steps to Reproduce**:

1. Create an analyzer with this `Initialize` method:
```csharp
public override void Initialize(AnalysisContext context)
{
    context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
    context.EnableConcurrentExecution();
    context.RegisterCompilationStartAction(OnCompilationStart);

    context.RegisterSymbolAction(context =>
    {
        var type = (INamedTypeSymbol)context.Symbol;
        context.ReportDiagnostic(type.CreateDiagnostic(Rule));
    }, SymbolKind.NamedType);
}
```

2. Create a fixer with this `RegisterCodeFixAsync` method:
```csharp
public override async Task RegisterCodeFixesAsync(CodeFixContext context)
{
    var document = context.Document;
    var codeAction = CodeAction.Create(
        "Seal class",
        async token =>
        {
            var editor = await DocumentEditor.CreateAsync(document, token).ConfigureAwait(false);
            var root = await document.GetSyntaxRootAsync(token).ConfigureAwait(false);
            var oldNode = root.FindNode(context.Span);
            var newNode = editor.Generator.WithModifiers(
                oldNode,
                editor.Generator.GetModifiers(oldNode).WithIsSealed(true));
            editor.ReplaceNode(oldNode, newNode);

            return editor.GetChangedDocument();
        },
        "Seal class");
    context.RegisterCodeFix(codeAction, context.Diagnostics);
}
```
3. Run it against this code:
```vb
Public Class UnsealedClass
End Class
```

**Expected Behavior**:
```vb
Public NotInheritable Class Foo
End Class
```
**Actual Behavior**:
```vb
Public NotOverridable Class Foo
End Class
```

**Comment by Youssef1313** [comment]
By looking into the code, this was *intended* to be handled by:

https://github.com/dotnet/roslyn/blob/efb98fcc5dd8b378b7c3e3833761ce7c7cadd0ba/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2526-L2532

Have to dig to see why it's not working as expected.

**Comment by Youssef1313** [comment]
@NewellClark Just as a workaround, if you found yourself on a "ClassStatement", "StructureStatement", "EnumStatement", etc.., Get the parent first (i.e, "ClassBlock", "StructureBlock", "EnumBlock", etc..)

This unfortunately will most likely require you to have the codefix as an abstract class with language-specific implementations.

**Comment by NewellClark** [comment]
@Youssef1313 yeah that's what I'm doing at the moment. It's irritating, but not blocking.

**Comment by Youssef1313** [comment]
@NewellClark It looks like this may be tackled without language-specific implementations.

https://github.com/dotnet/roslyn-analyzers/blob/88430922768299105ef997c20150796c41641bf2/src/Utilities/Workspaces/SyntaxGeneratorExtensions.cs#L437-L457
