### ISSUE TITLE
Review potential code paths that may or may not need to handle record structs

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53631]
The order of this list is from things I'm more confident about to things I'm less confident about.

- [x] Add accessibility modifiers analyzer - PR: https://github.com/dotnet/roslyn/pull/53633
 https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Analyzers/CSharp/Analyzers/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs#L58

---

- [x] Handle readonly for symbol display - PR #53634
https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs#L672-L677

---

- [x] Does CSharpUseAutoPropertyAnalyzer needs to handle record structs?
https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Analyzers/CSharp/Analyzers/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs#L56
[jcouv:] Fixed by https://github.com/dotnet/roslyn/pull/56474
---

- [x] Might want to handle for this extension (parameter wrapping depends on this extension, and also doc comments - see https://github.com/dotnet/roslyn/pull/52737) - PR #53640
https://github.com/dotnet/roslyn/blob/bc98ed946162622c7564607d276c06928033464e/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs#L260

---
---

- [x] Can we reach the following line with a record struct? (add a test if we can) (may be fixed in https://github.com/dotnet/roslyn/pull/53597).
https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Compilers/CSharp/Portable/Binder/BinderFactory.cs#L163

---

- [x] Does this need to handle record structs? I'm not aware of how this work tbh.
https://github.com/dotnet/roslyn/blob/4f5f3e8f529487ef2b79dfb7f6c8f2c17dd17fb8/src/Compilers/CSharp/Portable/Compilation/MethodBodySemanticModel.cs#L105
[jcouv:] I don't think this needs to be updated. The only tests affected by this case relate to record base types (`BaseArguments_15` for example), which are not relevant to record structs.
---

**Comment by Youssef1313** [comment]
@jcouv. Feel free to move the appropriate parts of this issue to the test plan and close the issue, or keep it open and link it from the test plan. I'm fine either way.

**Comment by jcouv** [comment]
It's fine to keep as an issue. Thanks for digging those up.
Linking to test plan https://github.com/dotnet/roslyn/issues/51199

**Comment by jcouv** [comment]
All bullets were addressed. Closing
