### ISSUE TITLE
Sub-optimal codegen for ??= statements

### ISSUE THREAD

**Issue by AbeniMatteo** [dotnet/roslyn#53644]
**Version Used**: 
main@17facfacf5fce15abf1280e5de3e25ad46dca6bd

**Description**:
`??=` statements are treated as expressions and are lowered using temp variables that will never be used.
These temp variables are only required for expressions like `var a = b ?? (c ??= d)` where the "result" of `c ??= d` can be used by `b ?? ...`.

**Steps to Reproduce**:
Compile (debug and release results are the same):
```cs
public class C {
    public void ValueToNullable(int? a, int b) {
        a ??= b;
    }
    
    public void NullableToNullable(int? a, int? b) {
        a ??= b;
    }
    
    public void TypeToType(object a, object b) {
        a ??= b;
    }
}
```

**Expected Behavior**:
```cs
public class C
{
    public void ValueToNullable(Nullable<int> a, int b)
    {
        if (!a.HasValue)
            a = b;
    }

    public void NullableToNullable(Nullable<int> a, Nullable<int> b)
    {
        if (!a.HasValue)
            a = b;
    }

    public void TypeToType(object a, object b)
    {
        if (a == null)
            a = b;
    }
}
```

**Actual Behavior**:
Decompiled:
```cs
public class C
{
    public void ValueToNullable(Nullable<int> a, int b)
    {
        int valueOrDefault = a.GetValueOrDefault();
        if (!a.HasValue)
        {
            valueOrDefault = b;
            a = valueOrDefault;
        }
    }

    public void NullableToNullable(Nullable<int> a, Nullable<int> b)
    {
        Nullable<int> num = a;
        if (!num.HasValue)
            a = b;
    }

    public void TypeToType(object a, object b)
    {
        if (a == null)
            a = b;
    }
}
```

**Comment by Youssef1313** [comment]
I believe the usage of a temporary variable was done initially to prevent double-evaluation of an expression with possible side-effects. However, this isn't true when the value of the expression is unused (the expression can be evaluated only once).

What do you think @333fred?

**Comment by Youssef1313** [comment]
Very related to https://github.com/dotnet/roslyn/issues/36548.

**Comment by 333fred** [comment]
The design is very intentional, because it mimics the behavior of null-coalescing on nullable value types. While we could potentially optimize when used as a statement rather than as a value, I don't believe it's worth it. The JIT is likely able to eliminate the dead stores, so unless there's a benchmarkable difference in runtime performance we'll keep this as is.
