### ISSUE TITLE
Navigation bar is broken for partial classes

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#53646]
Open Roslyn solution and navigate between different partial declarations of BoundAttribute class.

Observed:
- In src\Compilers\CSharp\Portable\BoundTree\BoundExpression.cs, ExpressionSymbol is the only member in the navigation bar.
- In src\Compilers\CSharp\Portable\BoundTree\Expression.cs, Children  is the only member in the navigation bar. At some point I saw more members, but selecting ExpressionSymbol didn't havigate anywhere.
- src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs, more members are in the navigation bar, but ExpressionSymbol and Children are not among them.

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I can definitely repro something weird going on here.  Investigating.
