### ISSUE TITLE
Show complexity classes in the editor

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#53647]
It can be hard for developers to easily know what the complexity class of their code is. It would be nice to show something in the IDE for this for at least the common LINQ operators. 

Implementation would likely rely on annotations in the framework to inform what the complexity of apis are with the IDE stitching the calculations together.

Related discussion: https://github.com/dotnet/runtime/issues/53142

**Comment by genlu** [comment]
Design meeting conclusion:
@jmarolf will talk to runtime team and ask then to provide better documentation in this area first

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of known design.
