### ISSUE TITLE
CSharpSyntaxGenerator.WithAccessorDeclarations doesn't support events.

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#53649]
**Version Used**: 3.9.0-final, but also present in main at https://github.com/dotnet/roslyn/blob/f986fa9a3d7933ac6cd484afab38019f75a52c1f/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L383-L395

**Steps to Reproduce**:

1.  Have an `IEventSymbol` named `evt`, and a `CSharpSyntaxGenerator` named `generator`.
2.  Run the following code snippet:
```csharp
                SyntaxNode eventDecl = generator.CustomEventDeclaration(evt);
                eventDecl = generator.WithModifiers(eventDecl, generator.GetModifiers(declaration).WithIsAbstract(false));

                eventDecl = generator.WithAccessorDeclarations(
                    eventDecl,
                    new[]
                    {
                        generator.WithStatements(generator.GetAccessor(eventDecl, DeclarationKind.AddAccessor), generator.ThrowStatement(generator.NullLiteralExpression())),
                        generator.WithStatements(generator.GetAccessor(eventDecl, DeclarationKind.RemoveAccessor), generator.ThrowStatement(generator.NullLiteralExpression())),
                    });
```

In my scenario, `evt` represents an abstract event declared on an interface, so I can't pass in the accessor bodies into `CustomEventDeclaration` while using the overload that takes an `IEventSymbol` since the `CSharpSyntaxGenerator` silently ignores the bodies.

**Expected Behavior**: The `eventDecl` node at the end of the snippet should have add and remove accessors with the following body:

```csharp
{
    throw null;
}
```

**Actual Behavior**:  The `eventDecl` node has accessors with empty bodies.

**Comment by CyrusNajmabadi** [comment]
This is by design.  The way to specify this with custom events is to supply the addAccessorStatements and removeAccessorStatements  with:

```c#
        public abstract SyntaxNode CustomEventDeclaration(
            string name,
            SyntaxNode type,
            Accessibility accessibility = Accessibility.NotApplicable,
            DeclarationModifiers modifiers = default,
            IEnumerable<SyntaxNode> parameters = null,
            IEnumerable<SyntaxNode> addAccessorStatements = null,
            IEnumerable<SyntaxNode> removeAccessorStatements = null);
```

**Comment by jkoritzinsky** [comment]
Using that API doesn't work for adding event implementations to interfaces using the Default Interface Members feature.

**Comment by CyrusNajmabadi** [comment]
> Using that API doesn't work for adding event implementations to interfaces using the Default Interface Members feature.

Can you clarify what the issue is there?  Note: i don't believe we have support for generating DIM members at all with any of the SyntaxGenerator space.

**Comment by CyrusNajmabadi** [comment]
@jkoritzinsky Can you open up a separate issue for the different problem you're seeing?  I'd like to not muddy this one.  Thanks!

**Comment by jkoritzinsky** [comment]
I think it should be covered by https://github.com/dotnet/roslyn/issues/53605

**Comment by CyrusNajmabadi** [comment]
Agreed.
