### ISSUE TITLE
Need support for ServerGC on .Net 6 Servicehub host

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#53654]
This requires some changes to ServiceHub's VSIX generator

**Comment by tmat** [comment]
@sharwell Do we need to have ServerGC/non-server GC when we switch to .NET Core? Can't we pick just one?

**Comment by genlu** [comment]
this is implemented as part of #53571.

**Comment by genlu** [comment]
Reopen this since the serverGC host isn't working correctly today. Tracking bug in Servicehub
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1354882
