### ISSUE TITLE
Investigate rarely applied quick actions

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#53659]
Investigate the following code fixes that are applied less than 20% of the time that they are shown. 

- [ ] Generate Type (with the dialog)
- [ ] Generate Parameter
- [ ] Generate Equals & Get Hash Code From Members
- [ ] Add Missing imports on paste
- [ ] Add Import (Install NuGet package)
- [ ] Generate local
- [ ] Add Debugger Display
- [ ] Introduce Variable all occurrences 
- [ ] Top level suppression 
- [ ] Convert AutoProperty to Full property
- [ ] Fully Quality 
- [ ] Convert Numeric Literal 
- [ ] Wrap items 
- [ ] Extract Class with Dialog 
- [ ] Use Expression body for lambda 
- [ ] Pull Members up
- [ ] Encapsulate Field
- [ ] Implement Interface with Dispose Pattern 
- [ ] Generate default constructor 
- [ ] Add Constructor parameters form members
- [ ] Generate Type 
- [ ] Generate overrides with dialog
- [ ] Change Signature
- [ ] Alias Ambiguous Type 
- [ ] Replace property with methods 
- [ ] Move declaration near reference 
- [ ] Sync namespace move file
- [ ] Use type
- [ ] Extract interface
- [ ] Initialize parameter 
- [ ] Add await
- [ ] Generate default constructors 
- [ ] Inline Temporary 
- [ ] Introduce using statement
- [ ] Use expression body
- [ ] Generate constructor from members 
- [ ] Use named arguments 
- [ ] Replace method with property
- [ ] invert conditional 
- [ ] Introduce variable for expression
- [ ] Move type to namespace
- [ ] Add accessibility modifiers 
- [ ] Generate variable 
- [ ] Invert logical 
- [ ] Move items to Namespace

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
