### ISSUE TITLE
'??=' Syntax Bug to show 'IDE0060' message

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#53660]
**Version Used**: VS 2019, NET Framework 4.8

**Steps to Reproduce**:

1. Define a method that the parameter 'option' is nullable.
2. The method code: 'option ??= new Option();'
3. Then, 'Error List' window shows 'IDE0060'.

**Expected Behavior**:
Don't tell this, because it's valid code with C# 8.0+.

**Actual Behavior**:
Showing Message: IDE0060, Remove unused parameter 'option' if it is not part of a shipped public API.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/124905953-25ec9d00-e019-11eb-9047-82502bd11d77.png)
![image](https://user-images.githubusercontent.com/23723575/124906159-58969580-e019-11eb-95fb-a07c7a21b7d2.png)
![image](https://user-images.githubusercontent.com/23723575/124906534-be831d00-e019-11eb-8cda-4d0b72b0cd9f.png)

So, It's not first warning that show the probelm.

**Comment by ufcpp** [comment]
see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

**Comment by kelicto** [comment]
> see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

My language version: 8.0. It's a bug!

**Comment by CyrusNajmabadi** [comment]
@mavasani an issue with unused variable analysis?  Are we missing a case in the tree for op-assignments?

**Comment by mavasani** [comment]
Yes, seems like a bug.

**Comment by mavasani** [comment]
Thank you @DoctorKrolic! Closing..
