### ISSUE TITLE
Pressing Enter after generating a snippet goes to the wrong location

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5366]
Ported from internal bug 145284

1. Type if followed by <tab><tab> to generate an if block 
2. Don't type anything, but click somewhere else in the source code 
3. Press Enter 

**Expected**: The snippet session is complete and the Enter inserts a newline where the caret was positioned.
**Actual**: The cursor is moved back inside the generated if block, to the snippet's ```$end$``` position.

We should only honor the ```$end$``` location if the caret position is within a snippet field (or maybe within the larger snippet span, we should check the exact Visual Studio 2013 behavior).

**Comment by dpoeschl** [comment]
We don't currently know anything about the snippet field locations, so we'd have to do some XML parsing on our side to figure out whether to move or leave the caret when we call [EndCurrentExpansion](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.textmanager.interop.ivsexpansionsession.endcurrentexpansion(v=vs.100).aspx).

**Comment by dpoeschl** [comment]
@Pilchie Should we consider moving to 1.2?

**Comment by balajikris** [comment]
Also look at internal bug 114668 (vs-feedback item 384486) while closing the bug. Essentially the repro there is typing code instead of Enter at step 3 in the repro listed above.

**Comment by diryboy** [comment]
Ah, also hit this, it's annoying. The session should dismiss if user typed anything outside of the field, but not when cursor moved, in case it moves back.
