### ISSUE TITLE
VS2019 16.10.0 C# code style "Refactoring Only" not work as expected

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#53673]
**Version Used**: 
VS2019 16.10.0

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/4510984/119538529-c6666500-bdbd-11eb-9b6b-cda21356c366.png)

![image](https://user-images.githubusercontent.com/4510984/119538689-f01f8c00-bdbd-11eb-8dae-f0e0e1d7b1c9.png)

![image](https://user-images.githubusercontent.com/4510984/119538743-fe6da800-bdbd-11eb-9f98-97158abe7d01.png)

-------------------

![image](https://user-images.githubusercontent.com/4510984/119539045-52788c80-bdbe-11eb-9efc-7ff1e335307d.png)

![image](https://user-images.githubusercontent.com/4510984/119539127-6fad5b00-bdbe-11eb-89a2-668e1efb2cb3.png)

![image](https://user-images.githubusercontent.com/4510984/119539146-750aa580-bdbe-11eb-90d7-4aeae623a58c.png)

**Expected Behavior**:
Works like 16.9.x only show when I trigger refactoring, no dots under codes.

**Actual Behavior**:
It works like "Suggestion", there are 3 dots under codes.

**Comment by jmarolf** [comment]
@mavasani what was the history here? I thought we always showed the "three dots"  for refactorings? was there any change here?

**Comment by GF-Huang** [comment]
> @mavasani what was the history here? I thought we always showed the "three dots" for refactorings? was there any change here?

Same settings in 16.9, no "three" dots here.

![image](https://user-images.githubusercontent.com/4510984/120558387-f4891c00-c431-11eb-8b67-e06b67c41f18.png)

**Comment by CyrusNajmabadi** [comment]
> I thought we always showed the "three dots" for refactorings? 

Nope.  `three dots` corresponds to `suggestion`.  `refactoring` has no indication in the text editor code itself (outside of the screwdriver in the left gutter).

**Comment by GF-Huang** [comment]
Is it fixed in `16.10.1`?

**Comment by CyrusNajmabadi** [comment]
@GF-Huang Do you have a repro for this?  If so, can you link to it (including any editorconfig files you may have). A GitHub link to a particular repo/commit would be helpful here.

**Comment by GF-Huang** [comment]
Can't you reproduce this issue?

**Comment by CyrusNajmabadi** [comment]
I cannot no. So something about my setup is different than yours. If you can apply a repro (ideally as requested above in https://github.com/dotnet/roslyn/issues/53673#issuecomment-857015082). That would be great. Thanks!

**Comment by GF-Huang** [comment]
God, when I create a new solution and project, the issue does not appear.

**Comment by CyrusNajmabadi** [comment]
Can you link us to your repo and a commit where it does appear?  It sounds like you have an editorconfig there that is overriding vs.

**Comment by GF-Huang** [comment]
I remove the `*.csproj.cs` and `.vs` folder, then generate a `.editorconfig` from default setting, the issue disappeared. But I found a bug of `.editorconfig` editor, look at the follow.

https://user-images.githubusercontent.com/4510984/121285804-8cdf3f00-c911-11eb-8c0a-bf9ea2604419.mp4

**Comment by GF-Huang** [comment]
@CyrusNajmabadi  I know how to reproduce, you need create a WPF project, and open a `xaml` file at less once.


https://user-images.githubusercontent.com/4510984/121357104-1586cb00-c964-11eb-8fa1-c0e0acc33c47.mp4

**Comment by GF-Huang** [comment]
@CyrusNajmabadi Did you reproduce it now?

**Comment by GF-Huang** [comment]
16.10.2 issue still.

**Comment by CyrusNajmabadi** [comment]
No. We haven't been able to repro this. As per the above instructions:

> Can you link us to your repo and a commit where it does appear? It sounds like you have an editorconfig there that is overriding vs.

**Comment by GF-Huang** [comment]
[CodeStyleDemo.zip](https://github.com/dotnet/roslyn/files/6662777/CodeStyleDemo.zip)

**Comment by GF-Huang** [comment]
16.10.3 still not fix.

**Comment by GF-Huang** [comment]
Anybody know this issue progress? A few months passed.

**Comment by CyrusNajmabadi** [comment]
@GF-Huang there has been no progress on this.

**Comment by GF-Huang** [comment]
I had try uninstall VS2019 then install the latest version(16.11.3), but the issue still. It's not only effect one project or solution, all my project are effected include new project created by 16.11.3. And I had try install the English language pack of VS, issue still.

**Comment by CyrusNajmabadi** [comment]
We've not been able to repro this.  We'd need a project that shows this happening in the latest vs previews.
