### ISSUE TITLE
Compiler can't load an analyzer where a binding redirect may be needed

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#53672]
In https://github.com/microsoft/CsWin32/discussions/218, we had a report of a source generator that was failing to load in Omnisharp. Debugging revealed it the analyzer depends on System.Text.Json, and the NuGet package there depends on assembly version 4.1.3 of System.Numerics.Vectors. However, another dependency brings in 4.1.4 of System.Numerics.Vectors, which in a normal app would be resolved with a binding redirect at runtime. Since https://github.com/microsoft/CsWin32/issues/261 was fixed, the analyzer does package 4.1.4.

For our command line compilers, right now it works out that this analyzer will load, only because System.Numerics.Vectors 4.1.4 happens to be a dependency of the compiler and thus a direct is in place for it. But that's somewhat an implementation detail and could change. For Omnisharp however, it doesn't have a redirect and thus won't load. And there's no practical way to package both 4.1.3 and 4.1.4 versions of the dependency in the same NuGet package to work around the issues.

Discussing with @jaredpar it seems the best resolution here is to change our assembly loading rules a bit. When we load an analyzer, we require _exact matches_ of dependencies [here](https://github.com/dotnet/roslyn/blob/ac284e677662baaf9274eeb5dba45d2300ade0d6/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs#L188); changing that to allow an "or higher" would mean we'd be effectively doing a binding redirect at runtime, which would resolve these issues.

Omnisharp currently has a copy/paste of the analyzer assembly loading code in it's repo; once we have the compiler change in hand we should update that copy. Since we have an External Access shim, I'd propose we simply make an API for them to fetch the implementation Roslyn has and they can reuse that directly.

**Comment by AArnott** [comment]
Another variant of the problem:

```
git clone https://github.com/dotnet/Nerdbank.GitVersioning.git
cd Nerdbank.GitVersioning
git checkout 69c33ed0be29de36e9fbd3188b55d0cd165d578a
.\init.ps1 -InstallLocality repo
dotnet build src\Nerdbank.GitVersioning
```

Fails with:

> CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileLoadException' with message 'Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)' [D:\a\1\s\src\NerdBank.GitVersioning\NerdBank.GitVersioning.csproj]

For the System.Text.Json failure, it only repros when I have the .NETCoreApp3.1 runtime installed. Even though I'm using the 5.0 SDK, the compiler runs in a .NET Core 3.1 runtime process when it's available, and that's where it fails. Probably because assemblies that ship with the runtime won't be loaded from the app directory (or from the list of analyzer assemblies in my case) unless the .deps.json file tells the runtime to do so.
When I remove the .NET Core 3.1 runtime, the SDK compiler is forced to use the 5.0 runtime, and it works. You can try this yourself after reproing the problem by removing the `obj\tools\.dotnet\shared\Microsoft.NETCore.App\3.1.16` directory.

But I need the .NET Core 3.1 runtime for this repo/pipeline because I run tests on it.

**Comment by jaredpar** [comment]
> Even though I'm using the 5.0 SDK, the compiler runs in a .NET Core 3.1 runtime process when it's available, and that's where it fails.

That is unexpected. Are you using the stock compiler that comes with the SDK or are you overriding it via say Microsoft.Net.Compilers? Don't believe you're doing the latter but that behavior is unexpected and it's one explanation for why you may be seeing it.

**Comment by AArnott** [comment]
Ah yes, in fact [I was referencing the `Microsoft.Net.Compilers.Toolset` package](https://github.com/dotnet/Nerdbank.GitVersioning/blob/92faaf73de1249249a241509b97cb7542883ceef/src/Directory.Build.props#L27). 
I guess I should update that version too.

**Comment by jasonmalinowski** [comment]
Assigning this to myself since we're going to address this in an IDE-only change.
