### ISSUE TITLE
Is there a way to skip the analysis for a configured list of documents (code files)?

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [dotnet/roslyn#53671]
For various reasons (not necessary related to generated code) the users might want to avoid running the analyzers for a given set of files. This could be an actual list or a pattern to match. 

Is there an API in the framework to achieve this?

On `sonar-dotnet` we want to improve the way we handle the user configured [sonar.exclusions](https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/) and having support for this in the Roslyn API would really help. I imagine that other analyzers would also benefit from this.

**Comment by AraHaan** [comment]
Usually to make files as excluded one must add these to the top of a file:

new style exclusion comment: ```cs
// <autogenerated/>
```
old style exclusion comment:

```cs
// <auto-generated></auto-generated>
```

There is possibly yet another one I am not aware of atm as well too.

**Comment by Youssef1313** [comment]
Why not using .editorconfig for that? For example, in roslyn, CA1822 is disabled for one specific directory only:

https://github.com/dotnet/roslyn/blob/23d354127e9293a2a02d59bae81a0b309a02ea4a/.editorconfig#L275

**Comment by costin-zaharia-sonarsource** [comment]
Thanks @AraHaan and @Youssef1313. These are definitely solutions to consider. 

We were interested though if there is a programmatic way to do this from the analyzer in order to not require any  changes in the projects being analyzed.

**Comment by sharwell** [comment]
The configuration for this is described under [Exclude generated code](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#exclude-generated-code).

**Comment by mavasani** [comment]
Closing this as the question has been answered by Sam
