### ISSUE TITLE
Ignore "Space after method name" option in Razor.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#537]
See https://connect.microsoft.com/VisualStudio/feedback/details/877217/c-formatting-breaking-razor, but basically we should ignore this option if the file is a .cshtml file, since putting the space there breaks the Razor parser.

**Comment by rynowak** [comment]
Is there a way that we can configure this when we create the buffer? We know that this setting breaks us.

**Comment by CyrusNajmabadi** [comment]
What about that setting breaks razor?  I can't read that site because it just reports: 
Microsoft Connect Has Been Retired

**Comment by rynowak** [comment]
```
<span>Hello, @GetMessage()</span>

@functions {
    private string GetMessage() => "world!";
```

This will write `<span>Hello, world!</span>` to the output stream.

If you auto-format and it changes the text to:
```
<span>Hello, @GetMessage  ()</span>

@functions {
    private string GetMessage() => "world!";
```

This will codegen code like:
```
writer.Write("<span>Hello, ");
writer.Write(GetMessage); // Notice the method group, not the method call
writer.Write("()</span>");
```
while will result in a diagnostic.

Implicit expressions, like `@GetMessage()` are whitespace-sensitive.

**Comment by CyrusNajmabadi** [comment]
> Implicit expressions, like @GetMessage() are whitespace-sensitive.

That seems strange, given that C# is not.  Is there reason it would be bad to not include the whitespace after the method-name to the following open paren?

The reason i ask is that this seems like a very leaky abstraction.  C# is contained in some language, but now need to know that legal syntax in it is illegal in that container.  It seems like it would be nicer to just have that container know what is legal C# and adjust its scanning/containment logic accordingly.  Is that possible?

**Comment by rynowak** [comment]
> That seems strange, given that C# is not. Is there reason it would be bad to not include the whitespace after the method-name to the following open paren?

This would change the meaning of existing code, often in a way that makes working code no longer valid.

Consider a case like:
```
<span>you should read this message: @Message (Important)</span>
```

Implicit expressions break a lot of the rules of traditional language design.

**Comment by CyrusNajmabadi** [comment]
Interesting.  Is there a full specification stating the syntactic forms that razor looks for?  It would be helpful for knowing if there are other cases that the language would have to know about.

**Comment by rynowak** [comment]
The alternative here would be for someone to have deep knowledge about the context of an edit applied during formatting, so we can transform `@Foo.Bar()` into `@(Foo.Bar ())`.

I think that'd be ideal... but we're a long way off from being able to implement something like this. We could stop people's pain if we could configure this on a per-buffer basis.

**Comment by CyrusNajmabadi** [comment]
Closing out as razor is handled externally now.
