### ISSUE TITLE
'Contract' methods should take CallerLineNumber

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#53706]
We occasionally get contract failures that are hard to diagnose. This can happen when a method contains multiple contract calls and it's unclear which fired in a bug report or yellowbar. If we include the line number, this can help out a lot to identify the problematic case.

**Comment by tmat** [comment]
Why don't we have a stack trace with line numbers?

**Comment by tmat** [comment]
I think the exception info should have stack trace with IL offset. We should be able to match the IL offset to line number via PDB.

**Comment by CyrusNajmabadi** [comment]
I think the problem there is the extra manual steps that needs. Having the message just state the line number means being able to instantly jump to the right place. It's purely additive and doesn't prevent the other approach

**Comment by tmat** [comment]
Sure, I'm just slightly concerned about bloating the generated IL.

**Comment by sharwell** [comment]
> Sure, I'm just slightly concerned about bloating the generated IL.

We can let RPS be the gauge here. Once a PR is submitted, we can manually run RPS on the PR to validate it before merging.
