### ISSUE TITLE
VS2019 16.10 crazy syntax error wavy line

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#53717]
**Version Used**: 
VS2019 16.10.0

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/4510984/119800209-61bb1f80-bf0f-11eb-9035-a051fa846a24.png)

![image](https://user-images.githubusercontent.com/4510984/119800599-83b4a200-bf0f-11eb-90d2-901eaf884b63.png)

**Expected Behavior and Actual Behavior**:

![image](https://user-images.githubusercontent.com/4510984/119800745-a3e46100-bf0f-11eb-8595-a2799eb2dccb.png)

**Comment by Youssef1313** [comment]
I've experienced a similar behavior before. But for me, it only happens when the solution isn't fully loaded yet. Waiting a little bit until the solution is fully loaded fixes it.

**Comment by GF-Huang** [comment]
> I've experienced a similar behavior before. But for me, it only happens when the solution isn't fully loaded yet. Waiting a little bit until the solution is fully loaded fixes it.

This issue duration 2 days, not this problem.

**Comment by Youssef1313** [comment]
@mavasani Would https://github.com/dotnet/roslyn/pull/53053 help here?

Meanwhile, @GF-Huang Can you enable **Tools** → **Options** → **C#** → **Advanced** → **Enable file logging for diagnostics (logged in '%Temp%\Roslyn' folder)**

**Comment by GF-Huang** [comment]
Nothing special was found in the log.

![image](https://user-images.githubusercontent.com/4510984/119818245-8ae4ab80-bf21-11eb-83c8-505ef173fa2e.png)

**Comment by Youssef1313** [comment]
@mavasani Would you be able to assist here?

**Comment by mavasani** [comment]
This should be fixed in latest VS2022 17.0 release builds: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes
