### ISSUE TITLE
Regex highlighting doesn't highlight double quotes as in other verbatim strings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53714]
![image](https://user-images.githubusercontent.com/31348972/119772718-e8481080-bebf-11eb-8247-88f0114f8a30.png)

Double quotes in verbatim string should get highlighted in both situations.

**Comment by CyrusNajmabadi** [comment]
There's a tension here.  THis is a regex pattern.  So we're using regex classification.  In regex, a quote is just a raw text character to match.  So it's appropriately classified as regex text.  I think the need for that overrides the desire to distinguish c# string escapes.  

Note: the same holds true for non-verbatim strings and using `\` escapes.

**Comment by Youssef1313** [comment]
Alright. Closing as by design.
