### ISSUE TITLE
Fix results in non-compiling code

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5372]
Suppose an assembly defining type `A.B.C` is referenced with `/r:E=Assembly.dll`.  If the referencing assembly attempts to use `C` without qualification, the following fixes are offered:
1. Add `using A.B`
2. Change to `A.B.C`

Neither of these will result in compiling code.  Either these fixes should be suppressed or we should offer:
1. Add `using E::A.B` (and, depending on context, `extern alias E;`)
2. Change to `E::A.B.C` (and add, depending on context, `extern alias E;`)

**Comment by amcasey** [comment]
FYI @jmarolf

**Comment by CyrusNajmabadi** [comment]
IDE policy is effectively "do not crash in the presence of extern aliases". We really don't do *any* additional investment as they are used so rarely by customers as to be practically irrelevant.
