### ISSUE TITLE
Visual studio should recognize and perform intellisense for all types of construction

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53724]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-should-recognize-and-perfo/1424332)._

---
Currently, it is cool I can do this in VS:
auto x = Foo{y};
If I f12 on Foo, VS knows this is contextual and rather than jumping to Foo, it gives me Foo::Foo(Y) constructor;

what's missing is the other forms of construction:
Foo x{y};
Foo x = y;

It would be cool if these are supported. For example F12 on the curly brace jumps to constructor call. F12 on assignment operator during copy-construction jumps to copy/converting constructor

---
#### Feedback Bot on 5/17/2021, 01:22 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by svick** [comment]
The code in the question looks like C++, which is not handled by Roslyn. So I think this was incorrectly moved here. cc: @mikadumont

**Comment by jinujoseph** [comment]
closed as external
