### ISSUE TITLE
Doc comment <see...> should support method params

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53728]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Doc-comment--should-support-method-param/1393904)._

---
I often use /// XML document comments for methods (and others) in C# code. In the comments/descriptions I often want to reference the method's parameters, but the  tag doesn't seem to support the method's parameter names (Visual Studio 2017).

I think this would be a very nice addition.

The most important aspect of this is that when refactoring so that parameter names are changed, the references inside the document comments would be included if they were using . This is not the case when written in "plaintext", potentially resulting in comments with outdated parameter names.

---
#### Feedback Bot on 4/8/2021, 11:51 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by Youssef1313** [comment]
I think this requires a language change, and would probably need a detailed proposal at dotnet/csharplang.

**Comment by PathogenDavid** [comment]
Unless you're wanting to refer to a different method's parameters, this is already possible with [the `paramref` tag](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/paramref).
