### ISSUE TITLE
Go To Implementation (and other search results)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53737]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-To-Implementation-and-other-search-r/1417388)._

---
When using "Go To Implementation" (and any other search) it would be very very nice to have subclasses (and interfaces or methods,...) structured by type of implementation. I mean Listing all by name is not the best way to find the result you need (even when group by project). For isntance, you click "Go To implementation" on an interface and you get a list of 100 subclasses. You need to find  an abstract class in the middle of that list. Not very easy. A treeview (wont work well for interfaces)  or something similar to organize the search results for better navigation is a must! A simple solution would be a column with result type. Interface, abstract class, class, struct ,method ,property, enum, etc... 

Thanks!

---
#### Feedback Bot on 5/10/2021, 11:02 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
