### ISSUE TITLE
Include and suggest Microsoft.Data.SqlClient in Visual Studio Intellisense suggestion list

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53736]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Include-and-suggest-MicrosoftDataSqlCl/1426003)._

---
Hi Team,

I'm coming from SqlClient driver team and would like to make a feature request as per: https://github.com/dotnet/SqlClient/issues/1063

Please suggest right direction to go from here.

Regards,
Cheena

---
#### Feedback Bot on 5/18/2021, 08:29 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
@CyrusNajmabadi and @jinujoseph on updating the NuGet package list.

**Comment by CyrusNajmabadi** [comment]
This shoudl be routed to @loic-sharma i believe.

**Comment by CyrusNajmabadi** [comment]
Reactivating.  Even with internal team updating index, this will take a little work on our side.

**Comment by loic-sharma** [comment]
@CyrusNajmabadi, we've updated the index. You should now be able to update Roslyn to recommend Microsoft.Data.SqlClient.

**Comment by JRahnama** [comment]
@CyrusNajmabadi what is the update on your end? Can we close this issue?

**Comment by CyrusNajmabadi** [comment]
@JRahnama see comment here: https://github.com/dotnet/SqlClient/issues/1063#issuecomment-1235805775  

i'm not sure how, absent us just special casing this package (which i'm loath to do) that we would know this is important enough to show he user.

**Comment by CyrusNajmabadi** [comment]
Actually, i think we coudl say there is a cutoff point after which we assume it's important enough.  Let me try that out now.

**Comment by sharwell** [comment]
I lean towards special-casing this package as part of the index generation, not as part of the index consumption.

**Comment by JRahnama** [comment]
@CyrusNajmabadi @sharwell, thanks a lot for the update.
