### ISSUE TITLE
Enum completion prevention of "Color Color" ambiguity

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5373]
**User Scenario**

In a WPF control with a nested control named `subControl`, type `subControl.Visibility = Visibility.Hidden` in the .xaml.cs file. Because `Visibility` is the name of an Enum and also a property of the outer control, completion after `Visibility.` contains enum members _and_ static/instance members of the Visibility property. 

Typing the same thing in Visual Studio 2013 prevents this problem by fully qualifying `Visibility` as `System.Windows.Visibility` when completed, removing the subsequent ambiguity.

**Standalone (non-WPF) Repro**

Copy/paste the following C# code:

``` C#
namespace S
{
    class C
    {
        Fail Fail;
        Pass Passes;

        void M()
        {
            C c = new C();
            c.Passes = Pass.A; // Completion offers "Pass" and then "A", as expected.
            c.Fail = Fail.A; // Completion offers "Fail" and then { "A", "CompareTo", "Equals", etc. }
                            // In VS2013, "Fail" on the RHS would complete as "S.FAIL" to prevent this.
        }
    }

    enum Fail { A };
    enum Pass { A };
}
```

When typing the `A` part of `c.Fail = Fail.A`, the completion list appears to contain both members of the Fail enum AND static/instance members of the Fail field.

Visual Studio 2013 attempts to detect and prevent this scenario in advance by completing `Fail` as `S.Fail`, which then causes only the enum members to be listed (as desired). If completion is invoked on an already-typed `Fail.`, then the behavior matches that of Visual Studio 2015. 

Applying the same fix in Visual Studio 2015 would be awkward because the `S.` qualification would immediately be marked as unnecessary. Perhaps there's some other way we can address this scenario.

**Comment by dpoeschl** [comment]
FYI: @rchande because we were just discussing this.

**Comment by Pilchie** [comment]
The old codebase had a special case where we would hide any inherited static members when displaying completion on an enum type, since people normally call them through Enum anyways.

**Comment by CyrusNajmabadi** [comment]
Looking at the behavior, what we do seems totally Fine.  Closing out as we haven't heard about any issues on this from any other customers.
