### ISSUE TITLE
Getting Diagnostics is slower on 64-bit

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#53743]
Seeing the persistent storage service taking more time to serialize things in 64-bit

| Name | Base | Test | Delta | Responsibility % | Overweight % | Interest Level |
|--|--|--|--|--|--|--|
microsoft.visualstudio.shell.framework!Microsoft.VisualStudio.Shell.TableManager.TableEntryExtensions.TryGetValue(class Microsoft.VisualStudio.Shell.TableManager.ITableEntry,class System.String,!!0&,!!0) | 669.0 | 27598.0 | 26929.0 | 6.28 | 11929.78 | 4 
microsoft.visualstudio.shell.framework!Microsoft.VisualStudio.Shell.TableManager.TableEntryExtensions.TryGetValue(class Microsoft.VisualStudio.Shell.TableManager.ITableEntry,class System.String,!!0&) | 1344.0 | 23925.0 | 22581.0 | 5.26 | 4979.46 | 4 
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.Host.AbstractPersistentStorage.ReadStreamAsync(Microsoft.CodeAnalysis.Document, System.String, System.Threading.CancellationToken) | 28553.0 | 50814.0 | 22261.0 | 5.19 | 231.06 | 4 
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService+PersistentStorageReferenceCountedDisposableWrapper.ReadStreamAsync(Microsoft.CodeAnalysis.Document, System.String, System.Threading.CancellationToken) | 28665.0 | 50911.0 | 22246.0 | 5.19 | 230.01 | 4 
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.SQLite.Interop.NativeMethods.sqlite3_step(Microsoft.CodeAnalysis.SQLite.Interop.SafeSqliteStatementHandle) | 964.0 | 16462.0 | 15498.0 | 3.61 | 4764.72 | 3 
nerdbank.streams.ni!Nerdbank.Streams.PipeExtensions+<>c__DisplayClass20_0+<b__2>d.MoveNext() | 7352.0 | 17029.0 | 9677.0 | 2.26 | 390.10 | 3 
system.collections.immutable.ni!System.Collections.Immutable.ImmutableDictionary`2[System.__Canon,System.__Canon].TryGetValue(System.__Canon, System.__Canon ByRef) | 16578.0 | 30080.0 | 13502.0 | 3.15 | 241.38 | 3 
mscorlib.ni!System.Collections.Concurrent.ConcurrentDictionary`2[System.__Canon,System.__Canon].GetOrAdd(System.__Canon, System.Func`2) | 19893.0 | 32802.0 | 12909.0 | 3.01 | 192.32 | 3 
system.collections.immutable.ni!System.Collections.Immutable.ImmutableDictionary`2[System.__Canon,System.__Canon].TryGetValue(System.__Canon, MutationInput, System.__Canon ByRef) | 15041.0 | 24074.0 | 9033.0 | 2.11 | 177.99 | 3 
microsoft.codeanalysis.workspaces.ni!Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer.DeserializeAsync(Microsoft.CodeAnalysis.Host.IPersistentStorageService, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.TextDocument, System.String, System.Threading.CancellationToken) | 38579.0 | 58638.0 | 20059.0 | 4.68 | 154.10 | 3 
microsoft.codeanalysis.features.ni!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+ProjectState.DeserializeDiagnosticsAsync(Microsoft.CodeAnalysis.Host.IPersistentStorageService, Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.TextDocument, System.Object, System.String, System.Threading.CancellationToken) | 39540.0 | 59599.0 | 20059.0 | 4.68 | 150.35 | 3 
microsoft.codeanalysis.features.ni!Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer+ProjectState+d__22.MoveNext() | 47520.0 | 65398.0 | 17878.0 | 4.17 | 111.50 | 3 

traces can be found here: \\mlangfs1\public\jmarolf\diagnosticsPerfTraces

**Comment by sharwell** [comment]
I haven't seen the traces yet, but this might be fixed by #53503

**Comment by jasonmalinowski** [comment]
@sharwell Why would that impact Dev17 differently though?

**Comment by sharwell** [comment]
I meant to make that reply on a different thread (one talking about large object heap)

**Comment by sharwell** [comment]
It depends on where the time is spent. If the overhead of a new task increases slightly, the overhead of millions might be noticable.

**Comment by CyrusNajmabadi** [comment]
Hrmm... I can't read the traces.  I get the following exceptions.

```
Generating output file C:\Users\cyrusn\AppData\Local\Temp\PerfView\regression.etl_f18b93a6.etl
Completed: Opening regression.etl.zip   (Elapsed Time: 226.162 sec)
Exception Occurred: System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at Microsoft.Diagnostics.Tracing.ZippedETLReader.UnpackArchive() in C:\github\perfview\src\TraceEvent\ZippedETL.cs:line 519
   at PerfView.CommandProcessor.UnZipIfNecessary(String& inputFileName, TextWriter log, Boolean unpackInCache, Boolean wprConventions, Boolean unpackInSeparateDirectory) in C:\github\perfview\src\PerfView\CommandProcessor.cs:line 1680
   at PerfView.ETLPerfViewData.GetTraceLog(TextWriter log, Action`3 onLostEvents) in C:\github\perfview\src\PerfView\PerfViewData.cs:line 7456
   at PerfView.ETLPerfViewData.OpenImpl(Window parentWindow, StatusBar worker) in C:\github\perfview\src\PerfView\PerfViewData.cs:line 6936
   at PerfView.PerfViewFile.<>c__DisplayClass13_0.<Open>b__0() in C:\github\perfview\src\PerfView\PerfViewData.cs:line 508
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0() in C:\github\perfview\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 254
An exceptional condition occurred, see log for details.
```

**Comment by CyrusNajmabadi** [comment]
@mavasani do you know why we are even serializaing/deserializing diagnostics here?  I can't really gauge why that woudl be something we would need to do (esp. on 64 bit).

**Comment by CyrusNajmabadi** [comment]
This should be fixed with https://github.com/dotnet/roslyn/pull/53792.
