### ISSUE TITLE
LSP and VS difference in GoToDefinition

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#53755]
Currently the LSP GoToDefinitionHandler uses `IFindDefinitionService.FindDefinitionsAsync`, while VS uses `IGoToDefinitionService.TryGoToDefinition`. There are a number of behavior differences between the implementations of these methods: one example is that go-to-def on a partial method will always go to the partial implementation in VS, but in LSP it will go to either the partial definition or implementation, whichever FindSymbols returns first. There are likely quite a few other behavioral differences, and we should extract the helpers that `IGoToDefinitionService` uses to find the current symbol to a helper that `IFindDefinitionService` can use as well to standardize behavior.

**Comment by 333fred** [comment]
Another difference is in namespace symbols: VS filters them out [here](https://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/FindUsages/IDefinitionsAndReferencesFactory.cs,137), but `IFindDefinitionService` returns their location.

**Comment by dibarbet** [comment]
This has since been resolved and LSP uses the INavigableItemsService (same as VS peek) and re-uses the same go to definition helpers.
