### ISSUE TITLE
Adding Visual Studio Menu Item in VB to VSIX Solution causes 381 Warnings (Errors after Build)

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn#5375]
Steps to Reproduce
```
Create new Visual Basic Analyzer with Code Fix (NuGet + VSIX)
From VSIX project add New Item...
Extensibility/Custom Command called "CustomCommand"
Not required but helps see the issue set the following options
    Option Explicit Off
    Option Strict Off
    Option Infer On
Build Solution
```
Several files are added and you get 381 warnings for the ComandComand.vb and CustomCommandPackage.vb files.The warnings are "Type or namespace definition or end-of-line expected", "Newline in Comment", "Type Expected" , "Too many characters in character literal"., "Comma Expected". None of which make any sense in a VB file. If I included these files in a C# project and rename them to .cs I get the exact same errors. The errors make no sense for a .VB file. 

There is no code that I have written involved in this issue.
When I compile the 381 warnings turn to 381 Errors.

**Comment by paul1956** [comment]
I have upload the complete project https://onedrive.live.com/redir?resid=5BF2F69E9B9FA722!13530&authkey=!AL9V-1Om3RvM01Q&ithint=file%2czip, the only code is what is automatically created by Visual Studio following the directions above.

**Comment by lgolding** [comment]
@Pilchie is this in your are?

**Comment by Pilchie** [comment]
We own the analyzer template, but not the Visual Studio Menu Item template.  I'll follow up internally with the VS SDK team and report back here.

**Comment by paul1956** [comment]
The template is VB, but somehow something in the Visual Studio reporting errors identical to what the C# compiler would report if I tried in VB code. Also Visual Studio source window shows no warnings or errors, only the Error Windows and all the Errors start with error CSxxxx.

**Comment by Pilchie** [comment]
Yep, I noticed that the project file imports Microsoft.Csharp.targets instead of Microsoft.VisualBasic.targets. Maybe the template updated it incorrectly.

**Comment by paul1956** [comment]
Changing CSharp to Visual on project imports statement has no impact

**Comment by jmarolf** [comment]
@paul1956 You will need edit the vbproj file directly.  I am testing a fix for this now.

**Comment by paul1956** [comment]
@jmmarolf no issue editing the file that is how I found the CSharp line.

**Comment by jmarolf** [comment]
You changed
```XML
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
```
To:
```XML
<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />
```

And it didn't change the errors when you built?

**Comment by paul1956** [comment]
No I changed the 
    <Reference Include="Microsoft.CSharp" />
To
    <Reference Include="Microsoft.VisualBasic" />
which did nothing but your fix, fixed most of the issues. The only issues I am seeing are a implicit variables from the Template while my project sets Option Explicit ON. It seems like something that the templates should honor but I can easily fix. Thanks for your help.

**Comment by paul1956** [comment]
@jmarolf making the changes above fill all compiler errors and the project builds but the code gets an error when I try to run it. Again none of my code just the default VXIX Project and the command button.
![image](https://cloud.githubusercontent.com/assets/12789369/10096492/dddd1550-6326-11e5-941b-03ddf2a87266.png)
```
624	ERROR	System.ComponentModel.Composition.ImportCardinalityMismatchException: Duplicate EditorFormatDefinition exports with identical name attributes exist. Duplicate name is UnderlineClassificationFormatProPack			Editor or Editor Extension
```
This only happens in the Test copy of Visual Studio when I start it from the empty Analyzer project with none of my code, except the fixes you outline above.

**Comment by paul1956** [comment]
After changing the two instances of CSharp to VisualBasic and the fixes listed above the solution builds with no errors but when I run the application I get an error on load.
```
621	ERROR	System.ComponentModel.Composition.ImportCardinalityMismatchException: Duplicate EditorFormatDefinition exports with identical name attributes exist. Duplicate name is UnderlineClassificationFormatProPack			Editor or Editor Extension
```
This error is not present in the Analyzer.sln version of Visual Studio only the one that gets run when I hit F5. Again none of my code except for the changes to get the solution to build.

**Comment by jasonmalinowski** [comment]
@paul1956: that appears to be an issue with some extensions. Per [this discussion](https://visualstudiogallery.msdn.microsoft.com/5d01e3bd-6433-47f2-9c6d-a9da52d172cc) it looks like there's an incompatibility if you have that and also the Pro Power Tools installed. Check for updates for both.

**Comment by paul1956** [comment]
@jasonmalinowski I do not have either of the two extensions (Pro Power Tools or Developer Assistant)  installed because I previously ran into the issue discussed above, This issue was also verified on a clean install (Microsoft Azure VM with Visual Studio Enterprise RTM) and by MSDN Jack-Zhai. I also have all updates to Visual Studio, NuGet packages and Extensions. Adding a Command Button to a VB VSIX project always causes this issue and extensions are not involved.

**Comment by jasonmalinowski** [comment]
@paul1956: now I'm confused....which issue? The duplicate format definition one?

**Comment by paul1956** [comment]
@jasonmalinowski the duplicate format issue was covered by a different issue. The issue here is about bad code generated by command menu template.

**Comment by jasonmalinowski** [comment]
Oh, so this is an issue in the VS SDK templates, not the Roslyn templates? We'll need to route this to the right people then.

**Comment by paul1956** [comment]
I added a menu button from the VS extensibility menu. Not sure where that comes from.

**Comment by jasonmalinowski** [comment]
@Pilchie: did you follow up with the VS SDK team for the other issue being discussed here? At this point I think all the Roslyn issues are fixed.

**Comment by Pilchie** [comment]
@paul1956: Did you mean `Option Strict`, when you said `Option Explicit` above?  `Option Explicit` is the default, and I don't see any warnings?  What about `Option Infer`?

**Comment by paul1956** [comment]
Two issues
1) the extensibility add custom for VB puts in 2 CSharp entries that should say VisualBasic
2) the code added does not explicitly type the variables in code that is included. 
I always use Option Explicit On, Option infer off Option strict On so once VB is actually looking at the code I get errors and warnings.
