### ISSUE TITLE
[ArPow] Run source-build leg in official builds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/roslyn#53764]
This is required in order to publish the Microsoft.SourceBuild.Intermediate.roslyn NuGet package so that it can be referenced by downstream dependent repos that participate in source-build.

[ArPow CI onboarding](https://github.com/dotnet/source-build/blob/main/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md) describes what Arcade templates exist to support this.

**Comment by RikkiGibson** [comment]
Is this referring to the same thing as the source build leg that we already run in [roslyn-ci](https://dev.azure.com/dnceng/public/_build?definitionId=15)?

**Comment by MichaelSimons** [comment]
Yes, the source build leg that is run in PR validation should get run in the internal ci / official builds and the resulting Microsoft.SourceBuild.Intermediate NuGet package needs to get published to BAR.  The source-build template should handle all of this.

**Comment by JoeRobich** [comment]
@MichaelSimons Does this build give you what you need? If so then we can move forward with PR #54009

**Comment by JoeRobich** [comment]
@MichaelSimons It helps if I link to the build - https://dev.azure.com/dnceng/internal/_build/results?buildId=1182202&view=results

**Comment by MichaelSimons** [comment]
Yep that looks correct, thanks.  The only thing to verify with a full build is that the Microsoft.SourceBuild.Intermediate.roslyn.<version>.nupkg that gets produced in the source-build leg gets published to BAR.

**Comment by JoeRobich** [comment]
Reopening until we confirmed publishing

**Comment by MichaelSimons** [comment]
I verified the Microsoft.SourceBuild.Intermediate.roslyn..nupkg is now getting published to BAR by the official builds.  Thanks @JoeRobich
