### ISSUE TITLE
VB shift operator bug 

### ISSUE THREAD

**Issue by GW-Lab** [dotnet/roslyn#53779]
**Version Used**: 
Version Used: VS/VB 16.11 preview 1 NET Framework 4.8

**Steps to Reproduce**:

1. Dim crc as UInt16 = 32768
2. Dim crcTmp = crc << 1
3. Set breakpoint (see picture: VB code)
4. Run the app
5. Inspect crcTmp variable

**Expected Behavior**:
The value of crcTmp = 65536

**Actual Behavior**:
The value of crcTmp = 0 (see picture VB code)

Note)
I busy converting -:( ALL my VB apps to C# and discovered a differents with VS/C# 16.11 preview 1 NET Framework 4.8

C# has the **Expected Behavior**:
The value of crcTmp = 65536 (see picture: C# code)

![Left-Shift-VB](https://user-images.githubusercontent.com/49092462/120100156-7e3d9e80-c13f-11eb-9c8d-6cc119299adc.png)
![Left-Shift-C#](https://user-images.githubusercontent.com/49092462/120100157-80076200-c13f-11eb-8de4-e3994962f47c.png)

**Comment by Youssef1313** [comment]
I think the compiler is following the spec here:

https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#shift-operators

https://github.com/dotnet/vblang/blob/main/spec/expressions.md#shift-operators

For VB:

>  The type of the right operand must be implicitly convertible to Integer and is not used in determining the result type of the operation.

This doesn't seem to be the case with C# where binary operator overload resolution is applied.

Tagging @AlekseyTs to confirm.

**Comment by GW-Lab** [comment]
Ok and thanks for the (fast) reaction.
