### ISSUE TITLE
Quick info in IntelliSense strips whitespaces from <code> blocks

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#53782]
**Version Used**: Visual Studio 16.11 Preview 1 (using the .NET 6 SDK Preview 4)

**Steps to Reproduce**:

1. Use this code snippet:
```csharp
class Foo
{
    /// <summary>
    /// This is a test:
    /// <code>
    /// while (Foo())
    /// {
    ///     Bar();
    /// }
    /// 
    /// Baz();
    /// </code>
    /// </summary>
    void Bar()
    {
    }
}
```
2. Hover on `Bar`
3. The following appears in the IntelliSense quick info tooltip:

![image](https://user-images.githubusercontent.com/10199417/120109942-e30eee00-c16b-11eb-943b-df06047bc7fa.png)

**Expected Behavior**:
The code inside that \<code> block should preserve the original formatting/spacing/newlines, etc.
Interestingly enough, this works fine when viewing the same XML docs through the .NET API browser.

**Actual Behavior**:
All whitespace characters are lost and the code is just weirdly formatted on a single line.

**Comment by Youssef1313** [comment]
Already being fixed in https://github.com/dotnet/roslyn/pull/53140 :)

**Comment by Sergio0694** [comment]
Ah, my bad, I had seen https://github.com/dotnet/roslyn/issues/53135 but somehow missed https://github.com/dotnet/roslyn/issues/37503 when looking for pre-existing issues 😅
Great work on putting up a PR to fix all of them @Youssef1313!
Will close this one as it's a duplicate anyway 🙂

**Comment by sharwell** [comment]
Duplicate of #37503
