### ISSUE TITLE
Incorrect syntax error squiggle in interactive window

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/roslyn#53787]
**Version Used**: 
`VS2019 16.10`
`Microsoft (R) Visual C# 交互窗口编译器版本 3.10.0-4.21269.26 ()`

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/4510984/120127597-6410c880-c1f2-11eb-8caa-40972ce845c3.png)

**Expected Behavior**:
No red wave line under correct syntax.

**Actual Behavior**:
Red wave line under correct syntax.

**Comment by Youssef1313** [comment]
Looks like you want to use [this overload](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=net-5.0#System_String_Split_System_String___System_StringSplitOptions_), but forgot to pass `StringSplitOptions`?

**Comment by Youssef1313** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/6917?

**Comment by GF-Huang** [comment]
Maybe.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
