### ISSUE TITLE
Inline hints settings not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inline-hints-settings-not-working/1435694)._

---
[severity:I'm unable to use this version]
Settings are not stored (see attachment)
While testing the setting I get a lot of issues with the latest 16.10 update.
Try to remove the settings in the last devenv.exe. And stopped and restarted devenv.
Settings off during shutdown of devenv and off during restart. But it's displayed in the IDE (so it look like the feature is ON).

---
#### Feedback Bot on 5/30/2021, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vemund Halvorsen on 5/31/2021, 01:25 AM: 

(private comment, text removed)
#### Vemund Halvorsen on 5/31/2021, 01:35 AM: 

(private comment, text removed)
#### Vemund Halvorsen on 5/31/2021, 01:37 AM: 

(private comment, text removed)
#### Vemund Halvorsen on 5/31/2021, 05:10 AM: 

<p>Looks like it’s better after updating ReSharper to 2021.1.3. Not seen the issue for some hours now…</p>

---
### Original Solutions
(no solutions)

**Comment by mikadumont** [comment]
@CyrusNajmabadi @jinujoseph based on feedback from Twitter: https://twitter.com/vemundh/status/1399279034832412677?s=21

**Comment by CyrusNajmabadi** [comment]
Customer reports the issue is fine. Might be a resharper issue:

> Looks like it’s better after updating ReSharper to 2021.1.3. Not seen the issue for some hours now…
