### ISSUE TITLE
Compiling multiple version output 'Process Access' Bug.

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#53805]
**Version Used**: 
Visual Studio 2019.
**Steps to Reproduce**:
1. Some project reference same cs files.
2. Sets different path for output.
3. Rebuilds the solution.

**Expected Behavior**:
'The process cannot access the file 'xxx.dll' because it is being used by another process.'
**Actual Behavior**:
I hope it can auto compiling, don't compile error.

![image](https://user-images.githubusercontent.com/23723575/120272991-78cb8a00-c2e0-11eb-8145-ca28eb8c903f.png)

**Comment by kelicto** [comment]
To solve the problem, I have to compile every main project, then maybe rebuild solution. It's very terrible.

**Comment by kelicto** [comment]
In addition to this bug, you can see that I add two 'PublicData' projects to store DB and UI resource strings. If I define them on themselves, will tell me 'resources' exception when compiles them.

**Comment by Clockwork-Muse** [comment]
... do you have "Actual" (what it does now) and "Expected" (what you think should happen) switched?

**Comment by kelicto** [comment]
You can try. I think that resource consumption due to parallel compilation.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/120769290-8dfa2000-c54f-11eb-9d8f-551e2e5e8869.png)
It's very bad experience. I have to compile main project of each version.

**Comment by jaredpar** [comment]
This is more likely to be an issue in the project / msbuild files than the compiler. Or possibly part of Visual Studio holding onto the file location that the compiler is writing to. Can you provide a binlog of the build when the error occurs? That will help us track down where the double write is occurring and route the issue appropriately.

**Comment by kelicto** [comment]
The demo project is very easy to build. Just reference some different versions of dll file. Now, I deleted them, the solution contains some simple version projects.
