### ISSUE TITLE
I stopped reading after you defined using source code as input as outside the scope of your model

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [dotnet/roslyn#53809]
## Proposed API

Consider using an XSLT style input->transformation->output model, with the output constrained to an abstract syntax tree.

Then you can take source code as input, or any declarative input source, and transform it into an AST. Even if the input source is source code.

As such, you can do things like mixing in aspects and even potentially doing domain specific language things.

I'm biased maybe, because it's the model I've used for years. Code generation is sort of my thing.

## Usage Examples

I don't want to constrain your model or make it too much like mine so I won't provide usage examples or propose specific changes here. I'll leave that to you.

## Alternative Designs

I've described an alternative using something like XSLT. I do something similar wherein I take a declarative input source in a well defined format, and some named arguments, and produce an output AST or sometimes directly source code, using a transformation model.

It's only as complicated as your input and output. It's flexible enough to handle most cases. It doesn't define "too much", and it provides enough definition that you could easily design an API for it, like

```Ast Generate(Stream input,IDictionary<string,object> arguments);```
or
```Generate(Stream input,IDictionary<string,object> arguments,Stream output);```

## Risks

Doing this would require you to rework your entire model.

**Comment by CyrusNajmabadi** [comment]
This is doable already. Take whatever input you want and just generate c# code. Source generators already make this easy as well. Roslyn will then take all that secondary ast and generate the 3rd ast (IL).

**Comment by codewitch-honey-crisis** [comment]
Fair enough. Then I don’t understand the point of your model other than to make it impossible to generate certain kinds of code. Sent from Mail for Windows 10 From: CyrusNajmabadiSent: Tuesday, June 1, 2021 7:27 AMTo: dotnet/roslynCc: honey the codewitch; AuthorSubject: Re: [dotnet/roslyn] I stopped reading after you defined using source code as input as outside the scope of your model (#53809) This is doable already. Take whatever input you want and just generate c# code. Source generators already make this easy as well. Roslyn will then take all that secondary ast and generate the 3rd ast (IL).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CyrusNajmabadi** [comment]
@codewitch-honey-crisis Can you edit your post to make it readable?  Your client seem to have not used markdown here.  Thanks!

**Comment by jmarolf** [comment]
> Then I don’t understand the point of your model other than to make it impossible to generate certain kinds of code. 

I admit I am confused by what you are trying to do and what is not working. You expect the input to be source and then you transform that input. In what context? A Source Generator or a standalone tool?

**Comment by codewitch-honey-crisis** [comment]
Hi, Let me see if I can take a step back. Here’s my issue with your entire project – and I did go back and read it – - there’s no rationale section, essentially. I don’t know what problem you are trying to solve. All it appears you are doing is constraining an existing model for generating, but you’re doing so by adding a bunch of boilerplate stuff in order to enforce that constraint of the existing source generation facilities. Why? What happened to KISS? And what happened to streamlined? Since your part of a large company, and your suggestions, and “best practices” get adopted by people, forgive me I guess, for putting a higher standard on the things you produce than most other projects on github, of which most could probably use a rationale section. But in this case, it’s important, because Microsoft is important in the field. Maybe I’m just missing something. I feel like I must be, because I cannot wrap my head around why this project even exists. Why narrow the scope of existing facilities, adding extra code to do so? What is the upside of the extra work and lack of flexibility that the “Source Generation Cookbook” provides? /design-hat   Sent from Mail for Windows 10 From: Jonathon MarolfSent: Tuesday, June 1, 2021 2:13 PMTo: dotnet/roslynCc: honey the codewitch; MentionSubject: Re: [dotnet/roslyn] I stopped reading after you defined using source code as input as outside the scope of your model (#53809) Then I don’t understand the point of your model other than to make it impossible to generate certain kinds of code.I admit I am confused by what you are trying to do and what is not working. You expect the input to be source and then you transform that input. In what context? A Source Generator or a standalone tool?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CyrusNajmabadi** [comment]
@codewitch-honey-crisis Please edit your github posts to remove all your email client goo.  THanks :)

**Comment by CyrusNajmabadi** [comment]
>  I don’t know what problem you are trying to solve. 

This is the C# and VB compiler project.  We are solving the problem of needing to have official compilers for that language .

We are also the C#, VB, F#, and TS/JS VS-IDE integration projects.  We are solving the problem of those languages both needing to integrate with Visual Studio *and* having some of those languages expose actual analysis APIs for plugins to use to interact with source code in the context of a rich IDE.

> I feel like I must be, because I cannot wrap my head around why this project even exists.

If it didn't exist, there wouldn't be official compilers for C# and VB.  Nor would it be possible to edit C#, VB (And the other languages mentioned) in VS in an official manner.

**Comment by CyrusNajmabadi** [comment]
> there’s no rationale section, essentially. 

We make it very clear waht this project is for on the main page:

> Roslyn is the open-source implementation of both the C# and Visual Basic compilers with an API surface for building code analysis tools.

**Comment by CyrusNajmabadi** [comment]
@codewitch-honey-crisis Can you edit your title?  Currently it's a bit nonsensical and unclear as to what the issue is or what you're asking for.  As mentioned a couple of times, Roslyn fully supports: "wherein [you] take a declarative input source in a well defined format, and some named arguments, and produce an output AST or sometimes directly source code, using a transformation model."

Given that this is already supported, it's not really clear what you're asking for here or what we could do different for your needs.  

--

The only thing i can glean out here is that perhaps you want this 'transformation' to itself be done with some sort of specialized language (like xslt).  In our opinion that is unnecessary.  We allow completely arbitrary code to run to specify your transforms.  This is necessary as in practice there is a huge amoutn of flexibility needed here (consider the types of transforms involved in compiling C# itself).  However, if someone wanted to *layer* an xslt like system on top of the flexible system we have, they woudl certainly be able to do so.  We would be unlikely to provide such a thing ourselves though as i don't see it being sufficiently valuable or powerful enough to meet the needs of enough customers.
