### ISSUE TITLE
Update EnqueueWorkItemAsync to operate on DocumentId

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#53816]
This method operates on a `Document`. Creation of the `Document` in the caller is responsible for 13% of allocations (373MB) in a 1 minute performance trace collected by @CyrusNajmabadi. Since there are no implementations of `IWorkCoordinatorPriorityService` in this repository, and the document is otherwise only used to access its `DocumentId`, the code should be refactored to operate on `DocumentId` instead of `Document`.

https://github.com/dotnet/roslyn/blob/1bf0e0d42c1bcda518c908ba993ec31cd9b671ad/src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.SemanticChangeProcessor.cs#L397-L409

**Comment by CyrusNajmabadi** [comment]
We aren't anywhere near close to being able to move to pull diagnostics currently.  For example, when we tried we saw diagnostics start taking 20+ seconds to even appear.  So we need an interim solution to address perf problems we're seeing in dev17.

**Comment by tmat** [comment]
Then we should fix the pull diagnostics instead of spending time on fixing solution crawler.

**Comment by tmat** [comment]
But if the fix is simpler then sure, why not.
