### ISSUE TITLE
Visual Basic does not support "Surround-With" snippets

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53836]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-Funciona-Rodear-con/1425917)._

🔗 [AB#889119](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/889119)

---
Hello, I'm working with Microsoft Visual Studio Community 2019 Version 16.5.4 and I want to use the Surround-con option, but I don't get that option, I tried crtl+k,crtl+s but I only get the message "This key combination is linked to the surround command", in the context menu (right click) I do not see the option and also not in the menu intellisense , 
how can you fix and enable that feature?
Thank you

---
#### Feedback Bot on 5/18/2021, 07:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/2/2021, 09:41 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by kevonh** [comment]
I am also experiencing this in Visual Studio 2022 preview (64-bit) version 17.0.0 preview 7 for razor files

Ctrl K + Ctrl S does not work, same error message in a .razor file. I just want "Surround With" div

**Comment by JoatmonX** [comment]
Same issues with Visual Studio 2019  16.11.13.  Is there any movement on this?

**Comment by fomrat** [comment]
Using VS 2022 and switched for a project from C# to VB. I thought I was losing my mind. Why would Surround With be missing for VB when Snippets are available?

**Comment by PeterAdam** [comment]
Same issue with VS 2022 Community 17.6.4

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in these legacy snippet experiences.
