### ISSUE TITLE
Lightbulb menu invoked between type members should offer to implement missing members

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#53848]
If a type does not provide all interface members or abstract members, then it should be possible to position the caret where you want them to be inserted, invoke the lightbulb, and generate them at that point.

![image](https://user-images.githubusercontent.com/350947/120643109-18437500-c4b9-11eb-8ecf-5f44dae11e91.png)

One way to achieve this would be to add missing members to the 'Generate overrides' dialog:

![image](https://user-images.githubusercontent.com/350947/120643437-8425dd80-c4b9-11eb-94c4-a0df73c3ed04.png)

The currently approach is to navigate to the interface/base class (where the error is displayed) and invoke the lightbulb there. The members are then generated somewhere else, and you have to move them to where you want them.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
