### ISSUE TITLE
Add miscellaneous files and metadata as source workspaces into LSP

### ISSUE THREAD

**Issue by nohwnd** [dotnet/roslyn#53852]
Have a miscellaneous files workspace by default, where if we receive a didOpen for URI not present in any of the explicitly registered workspaces, we create a document for it in this LSP misc files workspace. Then LSP requests would use that workspace's forked solution for requests. When the solution is opened and the file moves to a registered workspace's solution, we would prefer the document from the registered workspace over the misc workspace. This would avoid having every implementer need to handle single file scenarios.

**Comment by dibarbet** [comment]
resolved in https://github.com/dotnet/roslyn/pull/56314
