### ISSUE TITLE
'Null check can be simplified' is offered on method group access and produces invalid code

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#53860]
**Version Used**: 16.10.0

```cs
using System;
using System.Collections.Generic;

class C
{
    // ℹ IDE0031 Null check can be simplified
    //                            ↓
    Action<int> M(List<int> p) => p is null ? null : p.Add;
}
```

💡 Use null propagation:

```cs
using System;
using System.Collections.Generic;

class C
{
    // ❌ CS0023 Operator '?' cannot be applied to operand of type 'method group'
    //                             ↓
    Action<int> M(List<int> p) => p?.Add;
}
```

**Comment by RikkiGibson** [comment]
Is this CS0023 diagnostic expected based on the specification? https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#null-conditional-operator

**Comment by CyrusNajmabadi** [comment]
It's a pity of the language does not allow this.

**Comment by jnm2** [comment]
My use case for this was placing `(obj as IDisposable)?.Dispose` in an `Action?` field. I'd prefer this syntax, but it doesn't come up a lot.
