### ISSUE TITLE
Feature "Fade out unused" can't be disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53872]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Fade-out-unused-cant-be-disab/1402629)._

---
[severity:It bothers me. A fix would be nice] [regression]
After some update, I can't disable the feature "Fade out unused using". I already tried enabling, saving, closing VS, and opening disabling again..
! [image.png] (https://aka.ms/dc/image?name=B60b03c76747d4ac79cb8fd6e556fa5fc637544647761036418_20210419-183157-image.png&tid=60b03c76747d4ac79cb8fd6e556fa5fc637544647761036418)

---
#### Feedback Bot on 4/19/2021, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/21/2021, 09:35 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback.
