### ISSUE TITLE
TODO List empty after movingfrom VB Express 2015 to VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53882]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TODO-List-empty-after-movingfrom-VB-Expr/1440686)._

---
[severity:It's more difficult to complete my work]
After moving my Projects from VB Express 2015 to VS 2019 (Visual Basic) the Task List is empty.
After opening the Settings for Task List the 3 buttons on the right side are greyed out.
As a test, I added new "'TODO description" to the code, nothing happened (still empty list).
It is also impossible to add new tokens to the list.
My environment: MacBook Pro running Parallels 16.5.0, Win 10 Home 19042.985, VS Community 2019 16.10.0

What I have to do, to get the complete TODO List back again?
The only option, so far, seems to go back to VB Express 2015.

---
#### Feedback Bot on 6/3/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
> After moving my Projects from VB Express 2015 to VS 2019 (Visual Basic) the Task List is empty.

Note that the task list is updated in the background. Items might not appear immediately, but in 16.10 and newer they should eventually appear.

> After opening the Settings for Task List the 3 buttons on the right side are greyed out.

Can you provide a screenshot showing what you are attempting to do here?
