### ISSUE TITLE
Broaden enforcement of PROTOTYPE markers to all source folders

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#53888]
From discussion with @sharwell, there's interest to use this convention for projects outside of the Compiler.

The compiler team uses such markers (upper-case) to track work-in-progress in feature branches.
But we have to address/remove/replace those markers before merging a feature in `main` branch.
The `main` branch enforces that `PROTOTYPE` markers don't appear in `src/Compilers` `cs`, `vb` and `xml` files.

**Comment by genlu** [comment]
Design meeting conclusion: 
Yes, we want to expand this to then entire Roslyn codebase.

**Comment by jcouv** [comment]
Thanks. I'll go ahead with the change (PR https://github.com/dotnet/roslyn/pull/53886).
Note that I'll keep the existing rule (we only check for "PROTOTYPE" in all-caps).

**Comment by sharwell** [comment]
> Note that I'll keep the existing rule (we only check for "PROTOTYPE" in all-caps).

Yes, this was the conclusion in design review.

**Comment by jcouv** [comment]
Change is merged. Closing this tracking issue.
