### ISSUE TITLE
Implement string concatenation in loops via manipulating a StringBuilder instead of emitting String.Concat()

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5388]
At the moment, addition assignment operator for strings compiles into a `String.Concat()` call like this:
```C#
string result = string.Empty;
for(int i = 0; i < 1000; ++i)
   result += i.ToString();
```
->
```C#
string result = string.Empty;
for(int i = 0; i < 1000; ++i)
   result = String.Concat(result, i.ToString());
```
This leads to allocating a new string every time in the loop which may not be desired. I propose using a `StringBuilder` instead, wherever a `+=` operator appears in a loop (ideally in a optimized build) — providing more readable code beside of taking advantage of a pre-allocated buffer.
So the code above would be compiled to:
```C#
StringBuilder sb = new StringBuilder(string.Empty);
for(int i = 0; i < 1000; ++i)
   sb.Append(i.ToString());
string result = sb.ToString();
```

**Comment by dpoeschl** [comment]
@alrz This could be implemented as a diagnostic/fixer or a refactoring at the source code level if you're  interested in taking that route.

**Comment by yunuskiran** [comment]
@alrz did you test this codes performance. StringBuilder is faster than other.

**Comment by svick** [comment]
* If the loop is executed very few times (including zero), using `StringBuilder` is likely going to be more expensive. Is this approach the best option? Or could e.g. allocating the `StringBuilder` on the first iteration of the loop be more efficient?
* If the intermediate `string`s are actually used, using `StringBuilder` is probably going to be worse. Does it make sense to have a special case for this?
* Are there other cases where special cases could make sense? E.g. converting `result += ", " + i;` to `sb.Append(", "); sb.Append(i);`?

**Comment by yunuskiran** [comment]
@svick look at that. It is Turkish but you must look photo
http://scantekin.blogspot.com.tr/2014/08/c-string-birlestirmede-performans.html

**Comment by gafter** [comment]
We [would not do this as a compiler feature](https://www.youtube.com/watch?v=5XZ_5B5mJS0). However, it is an interesting scenario for a possible analyzer that could offer a fix. Please reopen a request for such a fixer if that is what you want.

**Comment by mattwarren** [comment]
I wanted to see what the actual difference in performance is, so I wrote the following [BenchmarkDotNet](https://github.com/PerfDotNet/BenchmarkDotNet) benchmark:

``` csharp
public class Framework_StringConcatVsStringBuilder
{
    [Params(1, 2, 3, 4, 5, 10, 100, 1000)]
    public int Loops;

    [Benchmark]
    public string StringConcat()
    {
        string result = string.Empty;
        for (int i = 0; i < Loops; ++i)
            result = string.Concat(result, i.ToString());
        return result;
    }

    [Benchmark]
    public string StringBuilder()
    {
        StringBuilder sb = new StringBuilder(string.Empty);
        for (int i = 0; i < Loops; ++i)
            sb.Append(i.ToString());
        return sb.ToString();
    }
}
```

And I got the results below, as @svick  says `StringBuilder` is more expensive for a small amount of loops (up to 3), but gives better performance as the # of loops increases.

```ini
BenchmarkDotNet=v0.7.7.0
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.0, Arch=64-bit  [RyuJIT]
Type=Framework_StringConcatVsStringBuilder  Mode=Throughput  Platform=HostPlatform  Jit=HostJit  .NET=HostFramework  
```

        Method | Loops |         AvrTime |        StdDev |          op/s |
-------------- |------ |---------------- |-------------- |-------------- |
  StringConcat |     1 |      44.7689 ns |     0.6986 ns | 22,336,917.28 |
  StringConcat |     2 |     104.1912 ns |     2.0270 ns |  9,597,739.44 |
  StringConcat |     3 |     182.5704 ns |     3.7191 ns |  5,477,342.99 |
  StringConcat |     4 |     256.2060 ns |     4.4468 ns |  3,903,110.87 |
  StringConcat |     5 |     323.4776 ns |     3.6641 ns |  3,091,403.90 |
  StringConcat |    10 |     670.3224 ns |    15.2415 ns |  1,491,820.08 |
  StringConcat |   100 |   8,740.6192 ns |   145.2037 ns |    114,408.38 |
  StringConcat |  1000 | 265,068.7377 ns | 1,792.2982 ns |      3,772.61 |
 StringBuilder |     1 |      77.3413 ns |     2.4428 ns | 12,929,709.70 |
 StringBuilder |     2 |     122.8922 ns |     1.0127 ns |  8,137,212.92 |
 StringBuilder |     3 |     179.1184 ns |     2.1769 ns |  5,582,901.15 |
 StringBuilder |     4 |     219.3030 ns |     1.7239 ns |  4,559,901.78 |
 StringBuilder |     5 |     265.7168 ns |     1.7573 ns |  3,763,404.59 |
 StringBuilder |    10 |     489.7956 ns |    11.8433 ns |  2,041,668.14 |
 StringBuilder |   100 |   5,126.1015 ns |   104.2758 ns |    195,080.03 |
 StringBuilder |  1000 |  52,910.5900 ns | 1,664.9696 ns |     18,899.81 |

**Comment by yunuskiran** [comment]
I sad :P, because i solve that problem before with stringbuilder.
