### ISSUE TITLE
PackageRegistration.pkgdef has non-localized strings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#53894]
https://github.com/dotnet/roslyn/blob/faf7c13acd548e6b9fc913f2349c3c07030cb113/src/VisualStudio/Core/Def/PackageRegistration.pkgdef#L17

https://github.com/dotnet/roslyn/blob/faf7c13acd548e6b9fc913f2349c3c07030cb113/src/VisualStudio/Core/Def/PackageRegistration.pkgdef#L23

Other `PackageRegistration.pkgdef`s are using localizable strings, e.g:

https://github.com/dotnet/roslyn/blob/faf7c13acd548e6b9fc913f2349c3c07030cb113/src/VisualStudio/CSharp/Impl/PackageRegistration.pkgdef#L44

**Comment by JoeRobich** [comment]
These strings are limited to the IntPreview and int.main internal channels and are not intended for release builds. Localization would be a requirement if we wanted to ship these feature flags. @dibarbet Is there any plan to ship the LSP feature flags in a public release?

**Comment by dibarbet** [comment]
Yep this is expected to be internal only.  There's no plan to ship these specific feature flags, any LSP rollout will be done feature by feature under their own flags.  Going to close out the issue.
