### ISSUE TITLE
Simplified If(bool? == true) to if(bool?)

### ISSUE THREAD

**Issue by Flithor** [dotnet/roslyn#53908]
Does not affect the code of false and null.

Just tired on `bool? == true`.

**Comment by CyrusNajmabadi** [comment]
@Flithor can you clarify what you're asking for?

**Comment by huoyaoyuan** [comment]
You are requiring `bool?` to be valid in `if` and implies `== true`.

This was already explicitly denied because there are also plenty usages of `!= false`. We don't think there's precede between the two cases.

**Comment by huoyaoyuan** [comment]
Another reason is that we've also denied `if(x != null)` and `if(x != 0)` which are common in C. We would never consider allowing non-bools in `if`, or at least regular `if`.

**Comment by huoyaoyuan** [comment]
I am also tired of converting `bool?` to `bool` sometimes. My desired solution is that whenever you press space after a `bool?` expression, there's completion for `?? true` and `?? false` provided. @CyrusNajmabadi Is this design attractive? It may be provided by roslyn.

**Comment by CyrusNajmabadi** [comment]
> My desired solution is that whenever you press space after a bool? expression, there's completion for ?? true and ?? false provided. @CyrusNajmabadi Is this design attractive? It may be provided by roslyn.

I would be fine with such a thing added to intellisense.

**Comment by sharwell** [comment]
Design review conclusion:

We should only add something to the list (e.g. `?? true` or `!= false`) if we believe that the presented form is the easiest to read. The discussion centered around reader's (and specifically a C# user with ~6 months' experience) ability to correctly interpret the semantics regarding a null value.

It is my personal opinion that an education effort could allow `?? true` and `?? false` to be the recommended forms by encouraging people to read `?? true` as "null is truthy" and `?? false` as "null is falsey". Users coming from JavaScript background would be most likely to reason about this, but it's not clear that average C# users would be able to understand `a ?? true` as easily as they can understand `a == null || a.Value`.

I believe the final conclusion is we are not ready to proceed with a change for this issue at this time. However, a team desiring this feature could implement `CompletionProvider` in an analyzer package to provide this functionality in a specific project.
