### ISSUE TITLE
Tooltips on switch case labels should display type information/XmlDoc instead of the less useful "this is a label"

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#53909]
**Version Used**:  Visual Studio 2019 Community 16.10

**Steps to Reproduce**:

1. Create a switch statement with any enum type.
2. Hover over any enum member case
3. Wait for the tooltip

**Expected Behavior**:
A useful tooltip presenting the enum member's full name and documentation is displayed. Like it was in previous versions of Visual Studio 2019... this change seems to have happened fairly recently.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/344204/120997127-3f36cb00-c787-11eb-8650-d89826166988.png)

I don't mind having this kind of "label" tooltip for goto case/default statements, however, please do not hide the enum member information. Thanks!

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski you fixed this right?

**Comment by jasonmalinowski** [comment]
Yep, this was fixed in #53338. @siegfriedpammer the fix will be in 16.11.
