### ISSUE TITLE
Generated XML doc from cref causes failed reference properties

### ISSUE THREAD

**Issue by erichiller** [dotnet/roslyn#53912]
**Version Used**: 

5.0.6

**Steps to Reproduce**:

1. Ensure Documentation Generation is on in *.csproj
2. Create one record with a simple property, and another type (`class`, `record`, whatever) that references it.

```cs
namespace NamespaceA {

/// <summary>
/// A sample record type
/// </summary>
/// <param name="Prop1">
/// A property
/// </param>
public record LinkDestinationRecord (
    string Prop1
);

public class LinkingClass {
    /// <inheritdoc cref="LinkDestinationRecord.Prop1">
    public string Prop1A { get; init; }
}

}
```
3. Build/generate documentation
4. (open up the generated documentation `<Assembly>.xml`)

**Expected Behavior**:

```xml
<inheritdoc cref="P:NamespaceA.LinkDestinationRecord.Prop1" />
```

**Actual Behavior**:

```xml
<inheritdoc cref="!:LinkDestinationRecord.Prop1" />
```

Note that the `inheritdoc cref` link being intra or inter namespace does not seem to affect the outcome.

For example with `class` property `inheritdoc`, it works as expected, eg:

```cs
namespace NamespaceB {

class LinkedToClass
    /// <summary>
    /// some text
    /// </summary>
    public string Prop2 { get; set; }
}

public class LinkingClass {
    /// <inheritdoc cref="LinkedToClass.Prop2">
    public string Prop2A { get; init; }
}

}
```

(I suspect it is something to do with how the shorthand `record` definition uses `<param>` rather than `member`)

**Comment by Youssef1313** [comment]
The following test passes:

```csharp
        [Fact]
        public void Test53912()
        {
            var source = @"
namespace NamespaceA
{
    /// <summary>
    /// A sample record type
    /// </summary>
    /// <param name=""Prop1"">
    /// A property
    /// </param>
    public record LinkDestinationRecord(string Prop1);
    
    /// <summary>
    /// Simple class.
    /// </summary>
    public class LinkingClass
    {
        /// <inheritdoc cref=""LinkDestinationRecord.Prop1"" />
        public string Prop1A { get; init; }
    }
}
";
            var comp = CreateCompilationUtil(source);

            var actual = GetDocumentationCommentText(comp);
            var expected = (@"<?xml version=""1.0""?>
<doc>
    <assembly>
        <name>Test</name>
    </assembly>
    <members>
        <member name=""T:NamespaceA.LinkDestinationRecord"">
            <summary>
            A sample record type
            </summary>
            <param name=""Prop1"">
            A property
            </param>
        </member>
        <member name=""M:NamespaceA.LinkDestinationRecord.#ctor(System.String)"">
            <summary>
            A sample record type
            </summary>
            <param name=""Prop1"">
            A property
            </param>
        </member>
        <member name=""T:NamespaceA.LinkingClass"">
            <summary>
            Simple class.
            </summary>
        </member>
        <member name=""P:NamespaceA.LinkingClass.Prop1A"">
            <inheritdoc cref=""P:NamespaceA.LinkDestinationRecord.Prop1"" />
        </member>
    </members>
</doc>");
            Assert.Equal(expected, actual);
        }
```

However, I suspect inheritdoc won't work the way you want since the property you specify doesn't have documentation comment. i.e, when you use `<param ...`, this doesn't add docs to the generated property. It only documents the parameter. On the other hand, inheritdoc cref will refer to the property, not the parameter.

See https://github.com/dotnet/roslyn/issues/52663#issuecomment-822735133 for related discussion.

FYI @jcouv, another report that seems to expect `param` to apply to the property as well.

**Comment by jcouv** [comment]
Note to self: also test `<seealso cref="..."`

**Comment by jcouv** [comment]
Added the unittest that verifies that we output `P:` rather than `!:`.
The issue with synthesized positional properties not automatically copying doc from positional parameters is separate and is tracked by https://github.com/dotnet/roslyn/issues/52663 (aiming to address in 17.1)
