### ISSUE TITLE
Lambda attributes + expression trees = missing metadata

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#53910]
**Version Used**: 

main branch, 07.06.2021

**Steps to Reproduce**:

Compile the following code:
```
using System;
using System.Linq.Expressions;

Expression<Func<int, int>> e = [A] ([A] x) => x;

class A : Attribute { }
```

**Expected Behavior**:

Compiler error "Expression tree lambdas can't have attributes"

**Actual Behavior**:

Successful compilation, attributes are missing in metadata (since there is no method compiled from expression tree lambda).

**Comment by RikkiGibson** [comment]
@cston
