### ISSUE TITLE
Implement interface fixer is not offered for an operator declared in an interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#53927]
Start with.
```
interface I3
{
    static abstract int operator -(I3 x);
}

class Test31 : I3
{
}
```

Observed:
"Implement interface" fixer is not offered for Test31.

If there are non-operator members to implement, the fixer is offered, but it doesn't spit out implementation (implicit or explicit) for operators. 

Same experience with conversion operators.

**Comment by AlekseyTs** [comment]
CC @jasonmalinowski

**Comment by Youssef1313** [comment]
@AlekseyTs What should be the expected result here? I wasn't able to implement this interface without errors.

```csharp
interface ITest
{
    static abstract int operator -(ITest x);
}

class C : ITest
{
    // CS0562: The parameter of a unary operator must be the containing type
    public static int operator -(ITest x)
    {
        throw new System.NotImplementedException();
    }
}

class C2 : ITest
{
    // CS0535: 'C2' does not implement interface member 'ITest.operator -(ITest)'
    public static int operator -(C2 x)
    {
        throw new System.NotImplementedException();
    }
}
```

**Comment by AlekseyTs** [comment]
> What should be the expected result here? I wasn't able to implement this interface without errors.

For an implicit implementation we should meet requirements for declaration in an interface and in class. For example like so:
```
interface I1<T> where T : I1<T>
{
    abstract static int operator -(T x);
}

class C1 : I1<C1>
{
    public static int operator -(C1 x) => default;
}
```

Basically, the declaration in the interface should have the shape that allows implicit implementations to meet their signature requirements.

**Comment by Youssef1313** [comment]
@AlekseyTs I mean for the non-generic interface (the example in the original issue)

**Comment by AlekseyTs** [comment]
> I mean for the non-generic interface (the example in the original issue)

The behavior for the original example is expected.

**Comment by CyrusNajmabadi** [comment]
In the original example how does one implement the interface?

**Comment by AlekseyTs** [comment]
> In the original example how does one implement the interface?

The operator can be implemented explicitly.

**Comment by CyrusNajmabadi** [comment]
I see. What are the rules to determine this?  We'll need to implement that in the ide side to how that this will need an explicit impl. Thanks!

**Comment by CyrusNajmabadi** [comment]
Ah, I see. @Youssef1313 is this enough information for you?  If not, I can help assist here. Thanks!

**Comment by AlekseyTs** [comment]
CC @sharwell
