### ISSUE TITLE
Implement interface fixer doesn't spit out `static` modifier implementations of static members

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#53925]
Start with:
```
interface I3
{
    static abstract void M1();
}

class Test31 : I3
{
}

class Test32 : I3
{
}
```

Use "Implement interface implicitly" for Test31 and "Implement interface explicitly" for Test32.

Observed:
```
class Test31 : I3
{
    public void M1()
    {
        throw new NotImplementedException();
    }
}

class Test32 : I3
{
    void I3.M1()
    {
        throw new NotImplementedException();
    }
}
```

Expected:
```
class Test31 : I3
{
    public static void M1()
    {
        throw new NotImplementedException();
    }
}

class Test32 : I3
{
    static void I3.M1()
    {
        throw new NotImplementedException();
    }
}
```

**Comment by AlekseyTs** [comment]
CC @jasonmalinowski

**Comment by Youssef1313** [comment]
I'm looking into this.

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by Youssef1313** [comment]
Addressed in #53939, with a bug that I'll be fixing in #53941

**Comment by AlekseyTs** [comment]
It looks like the "implement interface explicitly" option doesn't spit out static modifier for static events and properties.

**Comment by AlekseyTs** [comment]
CC @Youssef1313

**Comment by sharwell** [comment]
> It looks like the "implement interface explicitly" option doesn't spit out static modifier for static events and properties.

Let's file a separate issue for this. I don't want to change the milestone which remains correct for the items listed originally above.
