### ISSUE TITLE
Snippets permanently disabled after launching Interactive Window

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5393]
In https://github.com/dotnet/roslyn/commit/c7c55e3487782d5aad37daf484322c9a8b299355, we used ```InternalFeatureOnOffOptions.Snippets``` as a way for the ```InteractiveWorkspace``` to disable snippets, but changing this option to false for the ```InteractiveWorkspace``` causes that false value to be persisted, and it spreads to all workspaces (```InternalFeatureOnOffOptions``` were never meant to be per-workspace).

We should switch the ```InteractiveWorkspace``` back to using the default options, and include ```WorkspaceKind``` checks (and TODO comments) everywhere ```InternalFeatureOnOffOptions.Snippets``` is checked.

**Comment by amcasey** [comment]
This was really @dpoeschl's fix, so I'm "qualified" to verify it.
