### ISSUE TITLE
Intellisense compoud assignment suggestion incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53969]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-compoud-assignment-suggesti/1444349)._

---
[severity:Other]
For this code Intellisense suggest to use compound assignment, but it changes the behavior of the code.
Original code:

```
            bool alwaysTrue = true;
            int pkOrder = 0;
            int? current = null;
            for (int i = 0; i < 10; i++)
            {
                current = alwaysTrue == true ? pkOrder = pkOrder + 1 : null;
                Console.WriteLine(current);
            }
```

Results the following output:
1
2
3
4
5
6
7
8
9
10

Intellisense suggestion for this:

```
            bool alwaysTrue = true;
            int pkOrder = 0;
            int? current = null;
            for (int i = 0; i < 10; i++)
            {
                current = alwaysTrue == true ? pkOrder++ : null;
                Console.WriteLine(current);
            }
```

Results:

0
1
2
3
4
5
6
7
8
9

---
#### Feedback Bot on 6/8/2021, 06:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
Maybe if the result of the assignment is used then the refactoring should give `++expr`, and otherwise should give `expr++` for readability.

**Comment by CyrusNajmabadi** [comment]
the above code makes me cry :)   But i liek @RikkiGibson 's suggestion.

**Comment by banditoth** [comment]
> 
> 
> the above code makes me cry :) But i liek @RikkiGibson 's suggestion.

Made for demonstration purposes ;)
