### ISSUE TITLE
BugSection.Compiler and FeatrureSection.IDE have their filters swapped around

### ISSUE THREAD

**Issue by En3Tho** [dotnet/roslyn#53962]
Dunno where to report it but..
![image](https://user-images.githubusercontent.com/37334640/121307694-ec851c80-c908-11eb-8afb-a83f5f3b2951.png)

Finding a bug section:

Compiler:
Url: https://aka.ms/roslyn-compiler-bugs-help-wanted
Leads to GitHub filter:
sort:reactions-+1-desc is:open label:"help wanted"  label:"Feature Request" label:Area-IDE no:assignee 
Should be:
sort:reactions-+1-desc is:open label:"help wanted" label:Area-Compilers  label:Bug no:assignee 

Finding a feature section:

IDE:
Url: https://aka.ms/roslyn-ide-feature-help-wanted
Leads to GitHub filter:
sort:reactions-+1-desc is:open label:"help wanted" label:Area-Compilers  label:Bug no:assignee 
Should be:
sort:reactions-+1-desc is:open label:"help wanted"  label:"Feature Request" label:Area-IDE no:assignee

**Comment by Youssef1313** [comment]
@jmarolf Do you have access to update these links?

**Comment by jmarolf** [comment]
I've updated the links thanks for the ping!
