### ISSUE TITLE
Procedure View

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#53967]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/362598/procedure-view.html)._

---
<p>“Procedure View” one of the most useful feature of VB6 IDE which is missing in VS.net IDE ever since ver 2002. I wise to see this feature so that developer can concentrate on one function/procedure when developing/debugging complex code. It is really distracting to see entire source code when just one critical function/proc is being worked on. This feature will be really productive for many developers. </p><p>Developers have asked this feature on “UserVoice” but some how voice is not begin heard by VS team.</p>

---
#### Fiona Niu[MSFT] on 10/21/2018, 07:38 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>
#### Kendra Havens [MSFT] on 2/12/2019, 04:28 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input.</p>

#### marco cantu on 12/4/2019, 05:56 AM: 

<p>have a new about this problem? Single procedure view it's very important, someone know some workaround, i have tried Code Connect but it's working only for C# user</p>

**Comment by CyrusNajmabadi** [comment]
Bringing to next design meeting.  one thing we could consider woudl be if there were an outlining comamnd that collapsed all *other outlining except for the thing the user is currently in.

**Comment by tlcsys** [comment]
Hi
Has there being any Development on this Topic
as someone with Mild autism having a Clear screen to work on with no Distractions is very important to me and my Colleges

**Comment by CyrusNajmabadi** [comment]
@tlcsys there has been no development on the topic. I'd recommend just collapsing all members and expanding the one of interest you're working on.  That's the closest that is available right now.
