### ISSUE TITLE
Ensure `ScanType()` and `ParseType()` recognize `delegate*<...>?`

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#53973]
> The behavior of ScanType() is different today from ParseType() for this case, making it difficult to recover from cases such as `delegate*<void>? () => x`.

I'm not opposed to making the behavior of ParseType be the same here, parsing into an invalid nullable type.

_Originally posted by @333fred in https://github.com/dotnet/roslyn/pull/53827#discussion_r648529599_

**Comment by Youssef1313** [comment]
@cston I think this was fixed by @adamperlin in #62104.
