### ISSUE TITLE
Feature request - Embed source in PDB

### ISSUE THREAD

**Issue by noahfalk** [dotnet/roslyn#5397]
The PDB format has long had the capability to include the full text of source files, but most compilers have not made use of it. I would like to add an optional command line argument to the compiler to use this PDB feature.

Including the source gives the developer a way to transmit his code to anyone debugging it without requiring auxiliary mechanisms such as source control servers or saving source files on known file shares. Although it makes the PDB larger, in some cases this size gain might be preferable to overhead configuring those alternate mechanisms. Here are a few cases I imagine it might be useful:
1) During the build, source code is auto-generated and then compiled. This auto-generated source does not exist on source control server and is often not preserved as a build artifact. Even if it is preserved, it can't be indexed on a symbol server making acquisition difficult at debug time. (This is my particular case)
2) A company is OK from an IP standpoint to release source for some of their projects, but their source control system is behind a firewall. Their IT security policies prevent giving any external access to the source control system, which prevents typical usage of source server. They already provide PDBs to customers, and by including source in the PDBs the customer's debugging experience improves with minimal additional work.
3) An Open Source project is doing all their development on GitHub and they current use source server to distribute source, but they don't like additional configuration necessary in VS to enable it. By distributing the source in the PDB they eliminate this additional configuration.

From my quick experiments, the work to enable such a feature is not very much. This is a simple prototype I've been working on to get a quick idea of the scope:
https://github.com/noahfalk/roslyn/commit/e4e20bfe08d11e378998e1346af376bb0c8f782e

To the best of my knowledge Visual Studio Debugger doesn't currently automatically use source embedded in PDBs, but I would collaborate with both teams to enable the debugging experience together with the compiler experience.

Please let me know what are the useful next steps. Thanks!

**Comment by RichiCoder1** [comment]
I presume PPDB support would also be desirable?

**Comment by noahfalk** [comment]
For my particular scenario it doesn't matter but it is easy to imagine other potential consumers of the feature would enjoy PPDB support.

I am working with the build process for .Net Native, the PDB produced by csc will consumed by the NUTC compiler and transformed into a C++ style PDB before the build is complete (I would do work to ensure the source information in the csc produced PDB was transferred to the NUTC produced PDB as we do with other PDB data).

**Comment by roterdam** [comment]
this would be a great feature to add, if not to the compiler at least open the hook to do it publically without messing with internals.

**Comment by nguerrera** [comment]
As discussed with tmat and others, I will be looking at this. Self-assigning.

**Comment by nguerrera** [comment]
I've cherry-picked @noahfalk's prototype on to the future branch and will build from there: https://github.com/dotnet/roslyn/compare/future...nguerrera:embed-source-in-pdb

**Comment by nguerrera** [comment]
#12625 tracks design proposal for this.

**Comment by nguerrera** [comment]
Closing as #13707 tracks the only remaining work (Windows PDB support). Full support for this in VB and C# for portable PDBs is in.
