### ISSUE TITLE
Opening OrchardCore Roslyn does lots of IO

### ISSUE THREAD

**Issue by drognanar** [dotnet/roslyn#53980]
**Version Used**: 31404.224.d17.0

**Steps to Reproduce**: 

1. Start collecting a PerfView trace
2. Clone OrchardCore

Roslyn's checksum computations end up using 85% of the IO.

![image001](https://user-images.githubusercontent.com/3418274/121437323-65748a80-c982-11eb-8699-1937a3b02267.png)

Looking at the trace it seems that checksums for some files are computed multiple times. For instance according to PerfView CodeAnalysis.CSharp.dll incurs 80MB reads, even though it's a 5MB file.

I got the full trace here: `\\mlangfs1\public\arturs\snappy\OrchardNavigate.etl.zip`

**Comment by CyrusNajmabadi** [comment]
tagging @sharwell .  We definitely need to read these files in no matter what.  However, it definitely is fishy that we are reading things in that many times.  From Sam's own investigations we're seeing some files be read upwards of 50 times.  So something is going heavily wrong here causing huge amount of excess work to be done that is impacting other components.

**Comment by sharwell** [comment]
Note that the observed impact is much less than would be suggested by the File I/O stacks. The Disk time stacks show that _all_ reads of these assemblies are coming from memory caches and not from the disk itself.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement on this.
