### ISSUE TITLE
Stale rename entries in the lightbulb menu

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#540]
Ported from TFS WorkItem: **1125186**

------------------------------

**Repro Steps:**

**Affected Branch:**&nbsp;vspro_1
 **Affected Build:**&nbsp;22611
 **Affected Product Language:** 
 
**Steps to reproduce:**

1. paste the following code<div>
  </div><div><div>&nbsp; &nbsp; &nbsp; &nbsp; int M3(int x) { return x; }</div></div><div>
  </div><div>

2. change "x" in "return x;" to "xrenamed", note that the rectangle around xrenamed indicating the rename tracking</div><div>

3. press [ESC], note that the rectangle is gone</div><div>

4. Ctrl+[DOT]</div><div>

5. Select either rename option.</div><div><div>
</div><div>**Expected**:</div><div>x renamed to y,</div><div>or rename options shouldn't appear if the tracking is gone.</div><div>
</div><div>**Actual**:</div></div><div>Nothing happened.</div>

------------------------------

**Revisions:**

1) Created By Jeremy Meng (2/13/2015 10:54:57 AM)

------------------------------

**Comment by dpoeschl** [comment]
This is a case where we'd really like to stop providing the underlying diagnostic but we aren't actually changing the solution in any way. We're considering ways of forcing a diagnostic/lightbulb refresh for this situation.

**Comment by dpoeschl** [comment]
@jeremymeng - Assigning to you for verification. If you don't have time to verify, let me know and I'll assign it to somebody else. Thanks!

**Comment by jeremymeng** [comment]
Looks good.
