### ISSUE TITLE
Interface type is not offered in completion list while typing declaration of an explicit implementation for a static member

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54005]
```
interface I1
{

    static abstract void M1();
}

class C1 : I1
{
    static void 
}
```

Press 'space' after ```static void``` in C1. 

Observed:
No completion list offering ```I1``` for explicit implementation.

Expected:
```I1``` is offered as it is done for instance members.

Note, properties, events, operators and conversions are affected as well.

**Comment by CyrusNajmabadi** [comment]
We woudl take a targeted community pr here.
