### ISSUE TITLE
"Find All References" doesn't work on explicit implementation of conversion operator.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54023]
```
interface I4<T> where T : I4<T>
{
    abstract static int operator +(T x);
}

class C4_2 : I4<C4_2>
{

    // Explicit implementation
    static int I4<C4_2>.operator +(C4_2 x) => default;
}

interface I5<T> where T : I5<T>
{
    abstract static implicit operator int(T x);
}

class C5_2 : I5<C5_2>
{

    // Explicit implementation
    static implicit I5<C5_2>.operator int(C5_2 x) => default;
}
```

Observed:
I couldn't find a way to get "Find All References" working on ```static implicit I5<C5_2>.operator int(C5_2 x)```.

Expected:
Works as expected on a `+` token in ```static int I4<C4_2>.operator +(C4_2 x)```, finds the declaration and the call sites. Expect to be able to do something similar with conversion operator.

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by sharwell** [comment]
@Cosifne if FAR does not work for _normal_ conversion operators, we probably don't need to prioritize making it work just for these (i.e. group it with the higher level requests like #30210, #50850).

**Comment by CyrusNajmabadi** [comment]
We don't support implicit conversions in far as there is no efficient way in the compiler to find them. We do support explicit conversions and operators (and those should be supported for static abstracts.

**Comment by Cosifne** [comment]
For operators:
![image](https://user-images.githubusercontent.com/24360909/122300470-34c9af00-ceb4-11eb-839e-0aca077863b7.png)

It should be fixed by this PR https://github.com/dotnet/roslyn/pull/54056

**Comment by Cosifne** [comment]
For conversion, if I call FAR, this would give all the usages
![image](https://user-images.githubusercontent.com/24360909/122301236-3e9fe200-ceb5-11eb-8cbb-6c7178feb2e1.png)

But you can't do this for conversion operator (line 122):
![image](https://user-images.githubusercontent.com/24360909/122301298-5d9e7400-ceb5-11eb-9944-4c1deb9754d5.png)
It will find all the reference for 'int' type

**Comment by Cosifne** [comment]
🙁
Completely lose Internet yesterday when I wrote posts.

For customized type conversion:
Invoke FAR results:
![image](https://user-images.githubusercontent.com/24360909/122448983-364db280-cf5a-11eb-9c3c-ae08f906eef2.png)
![image](https://user-images.githubusercontent.com/24360909/122449484-bc69f900-cf5a-11eb-9c8b-3da29de8f18f.png)
![image](https://user-images.githubusercontent.com/24360909/122449858-3306f680-cf5b-11eb-88e0-cbd708399f73.png)
