### ISSUE TITLE
Couldn't find a way to "Go To Definition" from an implicit/explicit implementation of a conversion operator

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54024]
```
interface I5<T> where T : I5<T>
{
    abstract static implicit operator int(T x);
}

class C5_1 : I5<C5_1>
{
    // Implicit implementation
    public static implicit operator int(C5_1 x) => default;
}

class C5_2 : I5<C5_2>
{

    // Explicit implementation
    static implicit I5<C5_2>.operator int(C5_2 x) => default;
}
```

I couldn't find a way to "Go To Definition" from an implicit/explicit implementation of a conversion operator. This works for methods/properties/events from member name in implementation. It also works for non-conversion operators from an operator token. It feels like there should be a way to do the same for an implementation of a conversion operator.

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by sharwell** [comment]
@Cosifne does this work with inheritance margin at least?

**Comment by Cosifne** [comment]
Inheritance Margin works
![Fix](https://user-images.githubusercontent.com/24360909/122437379-8161c880-cf4e-11eb-9843-5d4b8898259a.gif)
