### ISSUE TITLE
Proposal: Expression Alternative for Statements

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5402]
Following the proposals #254, #3718, #5154, #5143 and others, it would be a good idea to have an expression alternative for other constructs as well.
### Syntax
>*expression:*
&emsp;...
&emsp;*if-expression*
&emsp;*try-expression*
&emsp;*iterator-expression*
&emsp;*using-expression*

**Note:** It is not proposed that these be added to the set of syntax forms allowed as an *expression-statement*.

>*if-expression:*
&emsp;`if` `(` *boolean-expression* `)` *expression*

Note that *if-expression* cannot return and `else` expression seems redundant because of the existing ternary operator.

>*try-expression:*
&emsp;`try` *expression*

*try-expression* returns a `null` in case of an exception, so you can use null-coalescing operator.

>*iterator-expression:*
&emsp;*foreach-expression*
&emsp;*for-expression*
&emsp;*while-expression*
&emsp;*do-expression*

>*foreach-expression:*
&emsp;`foreach` `(` *local-variable-type* *identifier* `in` *expression* `)` *expression*

>*for-expression:*
&emsp;`for`   `(`   *for-initializer*<sub>opt</sub>   `;`   *for-condition*<sub>opt</sub>`;`   *for-iterator*<sub>opt</sub>`)`  *expression*

>*while-expression:*
&emsp;`while`   `(`   *boolean-expression*   `)` *expression*

>*do-expression:*
&emsp;`do` *expression*   `while`   `(`   *boolean-expression*   `)`

Note that *iterator-expression* cannot return values unless it's used in expression-bodied iterators.

>*using-expression:*
&emsp;`using`   `(`    *resource-acquisition*   `)` *expression*

Additional syntaxes to be used with statement expressions including:
>*anonymous-method-expression:*
&emsp;...
&emsp;`delegate` `=>` *expression*

>*accessor-body:*
&emsp;...
&emsp;`=>` *expression* `;`

Some of the general *expressions* mentioned above should be narrowed to prevent polluted code.

**Comment by gafter** [comment]
This seems more like a concept than a proposal.

**Comment by aluanhaddad** [comment]
I find this proposal strange because you mention immutability as the motivation but several of your examples explicitly involve mutable state.
Also, many of the examples themselves seem redundant with existing language features.
For example:
```C#
// foreach, conditional —  basically list.Where(...).Select(...);
var result = foreach(var item in list) => if(item.Condition) => new Foo(item);
```
Why would you want this at all? Why not just write
```C#
var result = from item in list if item.Condition select new Foo(item);
```
which is both more readable and more concise.

**Comment by alrz** [comment]
@aluanhaddad As I said, loop expressions can be easily written in terms of LINQ methods/expressions. But for `using` and `try catch` you have to define a separate method. For example in a `match` expression what if you want to use a `using` or `try catch` in the case body? This can be easy done with an expression alternative. Again, Ix (from Rx) have methods like `Using` and `Catch` for this purpose and you can create your data flow with them but only if you are working with an `IEnumerable<>`. Besides, while it seems redundant, it helps to avoid the need for defining a new method where you just need an expression instead of a statement.
About braces, same pattern is used by lambda expressions; if there are braces you have a block body otherwise it have to be an expression. And yes it would be translated to an implicitly defined and implicitly invoked anonymous function because the value should be created somewhere. so the above translates to:
```
static IEnumerable<int> F() {
    for(var i = 1; i <= 10; ++i) { 
        var item = i.ToString();
        yield return item;
    }
}

...

var result = F();
```
Which is nice, because you don't need to define a method wherever you just want a value and need to use a `for`, `foearch`, `using` or `try catch`.
My inspiration for this proposal is from F# where [everything is an expression](http://fsharpforfunandprofit.com/posts/expressions-vs-statements/) even assignments e.g. `let val = value in expression`.

**Comment by aluanhaddad** [comment]
I think you are conflating yield in F# with yield return in C#.

**Comment by alrz** [comment]
@aluanhaddad by some means, but this is how you define iterator methods in C# right?

**Comment by alrz** [comment]
@aluanhaddad by some means, but this is how you define iterator methods in C# right? conflation as a bad thing you mean? :)

**Comment by alrz** [comment]
@gafter @aluanhaddad I just figured out my mistake about loop expressions: they cannot return values unless they are in iterators. So there would be no implicitly defined and implicitly invoked anonymous function. Please review the new specification.

**Comment by gafter** [comment]
What is *expression-or-block*? If it supports a *block*, what is it's value and type?

**Comment by alrz** [comment]
@gafter It follows *anonymous-function-body* rules. so if it supposed to return a value, one may use `return` statement.
```cs
Action f = () => if(condition) => this.Method();
Action f = () => if(condition) => { this.Method(); };
Func<int> g = () => if(condition) => this.MethodReturningInt();
Func<int> g = () => if(condition) => { return this.MethodReturningInt(); };
```
The lambda expression body remains in the expression context.

**Comment by alrz** [comment]
@gafter It follows *anonymous-function-body* rules. so if it supposed to return a value, one may use `return` statement.
```cs
Action f = () => try => this.VoidMethod() catch => this.VoidMethod();
Action f = () => try => { this.VoidMethod(); } catch => { this.VoidMethod(); };
Func<int> g  = () => try => this.IntMethod() catch => this.IntMethod();
Func<int> g = () => try => { return this.IntMethod() } catch => { return this.IntMethod(); }
```
The lambda expression body remains in the expression context in all cases.

**Comment by aluanhaddad** [comment]
@alrz I see, but I think it would make more sense for this proposal to allow loops to return values but to disallow iterators in loop expression block bodies. I was pointing out that the return type didn't make sense. It would have been something like ```IEnumerable<IEnumerable<int>>```. 

That said, I do not think any of this is a good idea. Initially I found the exception handling capabilities of this proposal to be compelling, but after seeing these examples,
```C#
Action f = () => try => this.VoidMethod() catch => this.VoidMethod();

Func<int> g = () => try => this.IntMethod() catch => this.IntMethod();
```
I think it could well encourage overgeneralized exception handling for the sake of brevity.

**Comment by alrz** [comment]
@aluanhaddad 
>I think it could well encourage overgeneralized exception handling for the sake of brevity.

You think checked exceptions in Java (as the opposite case) *encourage* developers to really catch the exceptions or explicitly bubble them up with `throws`? On the contrary, in Java using a general `catch` is more common than C#. Just because Java forces to explicitly handle the exceptions doesn't mean that people really do!

I think this totally depends on developers, if that is not the case, a general `catch` should have never been introduced to the language, "because it encourages to overgeneralized expetion handling", right?

>allow loops to return values but to disallow iterators in loop expression block bodies. What I was pointing out that the return type didn't make sense. It would have been something like IEnumerable<IEnumerable<int>>.

I didn't quite get that, can you give an example?

**Comment by aluanhaddad** [comment]
@alrz It is not about checked vs unchecked exception, it is about having catch clauses that catch everything. I'm not saying ```catch {...}``` is never appropriate, but it often masks errors. 

> I didn't quite get that, can you give an example?

You originally posted this example:

```C#
IEnumerable<int> result = for(var i = 1; i <= 10; ++i) => i;
```
and this example:
```C#
IEnumerable<string> result = for(var i = 1; i <= 10; ++i) => { 
        var item = i.ToString();
        yield return item;
};
```
But for the two examples to make any sense together, one of them is wrong.
Either the result type of the first is ```int```, or the result type of the second is ```IEnumerable<IEnumerable<string>>```, or the yield keyword should have been omitted.

**Comment by alrz** [comment]
> the result type of the first is `int`

That would not make sense. Because `i` is not a single `int`, it will evaluate several times with different values. same goes with the second example. I figured this out when I realized that `for` expressions like that can be used only within lists or sequence expressions in F# not the function body. Actually I trimmed list comprehensions from #5865 because the same arguments about `for` expressions returning values goes "why don't we use LINQ instead?" And that's correct. LINQ already covered this. Examples you mentioned are equivalent to `[for i = 1 to 10 do yield i]` and `[ for i = 1 to 10 do let item = i.ToString() in yield item ]` in F# which both return a `list`.

**Comment by aluanhaddad** [comment]
What part of the original proposal was also black expressions. Beef and Booker suggested that you could use an iterator body as a block expression body meaning that the body which as you say would be evaluated several times, would evaluate to a new iterator for each iteration of the loop. So the second example would have been an a loop which produced multiple iterators hence the type of the loop as an expression.

**Comment by alrz** [comment]
@aluanhaddad now I see what you're talking about. Anyway, I gave up that syntax because it will be confusing and complicated to implement.

**Comment by alrz** [comment]
@gafter As @GSPP pointed out, it totally makes sense to have `switch` expressions (actually it *was* part of this proposal, but I have been excluded it in favor of `match`). This makes introducing `match` expressions totally unnecessary.

I updated the original post, however, I wasn't sure about precedence of these expressions so I just omitted augmented existing rules for now.

**Comment by gafter** [comment]
Do you have semantic rules in mind for this? e.g. what is the type of an *if-expression* or an iterator expression? Which statements are allowed in a *block-expression*, and which are not? What are the semantics of statements embedded in a *block-expression*? What are the precedence rules?

It appears that this would make the language terribly ambiguous, for example

```cs
if (e) { M(); } // expression or statement?
.ToString(); // Oh, it was an expression. Is .ToString applied to the whole if expression or the block?
```

**Comment by alrz** [comment]
@gafter
>It appears that this would make the language terribly ambiguous

It wasn't, with previous syntax with the `=>` operator, since you removed it from `match` for the reason that "it doesn't really relate in any way to a method body" I did it here too. As it turns out, I should not.
>what is the type of an if-expression

*if-expression* would be `void` or `never`. the use case for this is in `void`-returning methods like
```cs
Array.ForEach(array, item => if(item % 2 == 0) Console.WriteLine(item))
```
>Which statements are allowed in a block-expression, and which are not?

*statement-list* implies that any statement would be allowed in a *block-expression* because, the point is to allow non-expression statements or ones that haven't an expression alternative can be used there. I don't think that it would be a good idea to have an expression form for like *any* statement that exist in the language (or is it?).
>What are the precedence rules?

As I said, I wasn't sure about precedences, you made `match` a `relational-expression` I didn't know the reason so I just decided to don't make any decision on this matter.

> Is `.ToString` applied to the whole if expression or the block?

First, *if-expression* doesn't return any value, so you can't do that. The following
```
{ M(); }.ToString();
```
is very similar to an object initializer. since `new Foo { ...  }.ToString()` is possible, then dot operator has a lower precedence than *block-expression*.

**Comment by gafter** [comment]
I don't get it. How is an *if-expression* any more convenient than an *if-statement*?

**Comment by alrz** [comment]
@gafter the purpose is to keep the procedure in the expression context. that's all. `break` and `continue` would be a problem, but `return` depends on your [comment in #5154](https://github.com/dotnet/roslyn/issues/5154#issuecomment-147490977). Will we ever need to `return` from an expression at all?

**Comment by gafter** [comment]
@alrz There are other ways to "return from an expression" - for example, `goto` the last expression in a block - but hijacking the meaning of `return` in an expression prevents writing APIs that act as user-defined control constructs. Unfortunately the fact that you use `{}` for *block-expression* makes a statement lambda (which necessarily hijacks `return`) and an expression lambda (which need not hijack `return`) indistinguishable.

**Comment by alrz** [comment]
@gafter 
>for example, `goto` the last expression in a block

I don't understand. you mean from outside of the block (expression block?)? Is that possible while label is not in the scope? 

about expression lambdas, well, there are two options left;
- Allow *expression-block* only in contexts that it would make sense, like other expression statements. (basically *expression-or-block* in the previous syntax)
- Use a different syntax for block-like expressions, e.g. something like C++ style comma operator but with a semicolon (cause comma would be ambigious with tuples) see [#3718 comment](  https://github.com/dotnet/roslyn/issues/3718#issuecomment-116186501). I don't like this though.

btw, there is a "expression block" in scala and it works. What I'm missing here? This is kind of problems that you were trying to solve by choosing parens for `match` or it's just a preference?

**Comment by gafter** [comment]
What I meant is that you can "return early" from inside a block by using a `goto` to its final expression.

Indeed, there is an expression-block in Scala and it does *not* hijack the meaning of `return`.

We already toyed with block-expressions in C# 6 and the syntax we came up with was `(` *statements* *expression* `)` but in our prototype we restricted the statements to either a local declaration statement or an expression-statement. There is no need for a "statement separator" in this syntax as statements already come with their own terminators.

**Comment by alrz** [comment]
that wouldn't be possible because *goto-statement* is not part of *expression-statement*.
>syntax we came up with was `(` *statements expression* `)`
this is just great, and it's consistent with *parenthesised-expression*.  I love to see this in the next version along with `match`. More I think about parenthesised `match` it makes more sense. but the fact that `match` will often break into multiple lines, gives it a SQLish look IMO.

**Comment by alrz** [comment]
@gafter *switch-expression* and *block-expression* aside, what about a colon instead of `=>` in expression statements? If this doesn't help with ambiguity problem neither, then this will not going to happen.

**Comment by gafter** [comment]
@alrz Re
> that wouldn't be possible because *goto-statement* is not part of *expression-statement*.

It could be extended by relaxing the set of statement forms allowed within it.

**Comment by alrz** [comment]
@gafter since the syntax you have mentioned were well designed enough I have removed *expression-block* from the suggestion. So there would be no `return` in this grammar.

**Comment by gafter** [comment]
You introduced *conjunctive-pattern* and *disjunctive-pattern*, but those productions aren't used anywhere. If you intend them to be examples of *pattern*, then your grammar is ambiguous.

**Comment by alrz** [comment]
@gafter  I just wanted to show how would multiple-case `switch` work. They're not part of this proposal actually. But how is that ambiguous?

**Comment by gafter** [comment]
`x is I1 and x is I2 or x is I3`

Is this a conjunction of a disjunction or vice versa? Your grammar is ambiguous.

**Comment by alrz** [comment]
@gafter Yes, I just figured out. Fixed.

**Comment by gafter** [comment]
@alrz I still don't see *conjunctive-pattern* or *disjunctive-pattern* used in (the right-hand-side of) any syntactic productions, so I don't see how they can be used in a program, or what their precedence would be.

**Comment by alrz** [comment]
@gafter It is defined under *pattern* so it would be used in `match`, `switch` or with `is` operator.

**Comment by alrz** [comment]
I think it doesn't need a `:` or anything, because the point is to be able to use `if`, `using`, etc in the expression context, (like `switch` expression sections), so they are just some additional production rules under *expression*.

**Comment by lachbaer** [comment]
Instead of using `delegate => expression;` one should use the corresponding llambda expression, as that's what they are for. Not introducing a new (500th) way to define delegates and anonymous functions will keep the language cleaner and nicer.
```C#
static Action Foo;
static Func<int, int> Bar;
static void Main(string[] args)
{
    Foo = () => Console.WriteLine("Foo Lambda");
    Foo();
    Foo = delegate { Console.WriteLine("Foo Delegate"); };
    Foo();
    // next one is the (by me declined) proposal:
    Foo = delegate => Console.WriteLine("Why would this statement really help?");
    Foo();

    Bar = (x) => x;
    Console.WriteLine("Bar Lambda: " + Bar(5).ToString());

    Bar = delegate(int x) { return x; };
    Console.WriteLine("Bar Delegate: " + Bar(5).ToString());

    Console.ReadLine();
}
```

**Comment by alrz** [comment]
Closing in favor of dedicated issues for each subject in this proposal.

**Comment by masaeedu** [comment]
@gafter Is there an issue or design discussion tracking the "block expressions" you mentioned earlier? My  primary use case is the ability to wrap void returning expressions into a larger `Unit` returning expression, which currently doesn't seem to be possible in the language.

**Comment by alrz** [comment]
@masaeedu #6182
