### ISSUE TITLE
Assigning a string value open quote diagnostic improvements

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54031]
Direct customer ask copying here:

> If you are working with strings and you want to assign a string value to a variable and enter an open “ (quote) without a closing quote, the red squiggles underline every line of code from that point to the end of the module. Every collapsed procedure and region are expanded. I do have the options set to add the closing quote. However, the closing quote isn’t always added. I would think that this compiler error could look for the next closing } curly bracket in code for C# or the next ‘End Sub’, ‘End Function’, or just ‘End’ key words in code and stop the red squiggly lines underling code at that point.

**Comment by CyrusNajmabadi** [comment]
This is genuinely how VB works.  If you have an open quote it consumes all the way up to the next close quote.  This is one of the core reasons we do have quote-completion as a thing to help ensrue that the user is less likely to be in this state.

Note: this is not an issue for C# as `"` only consumes up to the end of the line as per the language itself.
