### ISSUE TITLE
[Proposal] Custom literals for string-based objects.

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#5403]
A string literal or a raw string literal can be prepended by an identifier:
```c#
var element = xml@"<foo>
    <bar/>
</foo>";
var pattern = r"^[[:alpha:]]+$";
```

This is automatically rewritten to a class constructor or a static function invocation that has a matching attribute:

```c#
[StringLiteral("r")]
public class Regex
{
    public Regex(string pattern) //A constructor that can accept a single string argument is required.
    { ... }

    [StringLiteral("ri")] [EditorBrowsable(EditorBrowsableState.Never)]
    public static Regex CreateIgnoreCase(string pattern)
    { ... }
}
```

If there are two `StringLiteral` attributes with the same parameter in scope, it is a compilation error.

Potential use cases: simplifying the syntax for regexes, constant byte arrays or UTF-8 encoded strings. If compile-time metaprogramming is ever implemented in C#, the same syntax can be reused for safe XML literals, like in VB.

**Comment by alrz** [comment]
Dup of #4971

**Comment by dsaf** [comment]
Actually, it's a duplicate of #263. #4971 was a duplicate of a duplicate. I am pretty sure we will see more of these.

**Comment by alrz** [comment]
@dsaf yeah, I just mentioned the head pointer ;)

**Comment by gafter** [comment]
You can already do this using an extension method:

```cs
var element = @"<foo>
    <bar/>
</foo>".Xml();
var pattern = "^[[:alpha:]]+$".Regex();
```
