### ISSUE TITLE
  Roslyn/MSBUILD fails when using the dynamic keyword with Linq

### ISSUE THREAD

**Issue by LinoBarreca** [dotnet/roslyn#5404]
Situation:
menus is an IEnumerable<object> coming from a LINQ expression.
members of "menus" can be of type MenuItem OR ToolStripMenuItem.
in both cases, every member of menus has a "Visible" property.

If I write
```
menus.OfType<MenuItem>().ForEach(m => m.Visible = false);
menus.OfType<ToolStripMenuItem>().ForEach(m => m.Visible = false);
```
everything works fine.

If (to avoid unnecessary cycles/casts) I write instead
```menus.ForEach(m => ((dynamic)m).Visible = false);```
I get no error in Visual Studio (in the errors window) but during build I get
"error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' "
![2015-07-22_165526](https://cloud.githubusercontent.com/assets/897723/10041108/026e2c7e-61e2-11e5-948d-0cf13acdb117.png)

Sorry for the duplicate, I already posted that here ( https://connect.microsoft.com/VisualStudio/feedback/details/1577525/roslyn-msbuild-fails-when-using-the-dynamic-keyword ) but I got no reply after two months.

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue.  

Can you check your project to see if it has a reference to Microsoft.CSharp.dll?  That error should only occur if that particular reference is missing.  When that reference is present the error should not occur.

**Comment by jaredpar** [comment]
Closing for now.  Please ping back if you have the time to answer my question above.

**Comment by LinoBarreca** [comment]
Hey Jared!
Sorry for the misunderstanding but I replied you the same exact day...I don't know what happened honestly (luckily it was my mistake, maybe I closed the tab before completing the post, I honestly don't know)..anyway...I apologize.
A few days ago I confirmed that adding the reference you suggested the build error doesn't happen any more...but shouldn't that reference be added automatically? I never had that reference in the project when I first created it and I never (directly) needed it.
If a particular reference is required by the compiler for some language features that reference must be added at build time like Visual Basic does with Microsoft.VisualBasic.dll.
VB projects don't directly reference Microsoft.VisualBasic.dll, nevertheless the built assembly does.
It should happen the same with Microsoft.CSharp.dll if that library is mandatory for the compiler to work properly.

**Comment by jaredpar** [comment]
> A few days ago I confirmed that adding the reference you suggested the build error doesn't happen any more...but shouldn't that reference be added automatically?

Most new project templates in Visual Studio include this reference by default.  I'm not quite sure what happened in this case but likely that either the original template didn't have it or it was manually removed afterwards (possibly because it was determined to be unused at that time).

**Comment by LinoBarreca** [comment]
I don't mean actual project templates which may have been updated to include the reference. I created the project with vs 2002 years ago and I don't remember I ever had that reference (but maybe I'm wrong and someone in the team removed it, we can investigate on TFS).
Anyway that's a wrong approach. Actually if a Visual Basic project doesn't contain a reference to Microsoft.VisualBasic.dll the built assembly DOES because it's mandatory for the compiler to work properly. It should happen the same with C#. You can't break build for a (missing, mandatory, internal) reference. Not with a weird error message. Not based on how the programmer uses the word "dynamic".
Either you realize you are missing the reference at build time (and add it silently to the built assembly like you already do with VB) or modify the error message like "A reference to Microsoft.CSharp.dll is needed" leaving to the user the burden to do it.
Every approach has its positive and negative sides (for example the latter might require approval/checkout/modify/checkin/revision) but for sure you shouldn't halt build like you do now.

**Comment by jaredpar** [comment]
>  modify the error message like "A reference to Microsoft.CSharp.dll is needed" leaving to the user the burden to do it.

That error message would be incorrect though.  The C# compiler, unlike the VB one, doesn't have any special knowledge of Microsoft.CSharp.dll.  The compiler instead only has special knowledge of the types it needs in order to compile uses of `dynamic`.   The types involved can come from any DLL in the reference set.
