### ISSUE TITLE
Target typing should work while performing record nondestructive mutation.

### ISSUE THREAD

**Issue by HobbsCode** [dotnet/roslyn#54054]
**Version Used**: 
.NET 5

**Steps to Reproduce**:
[SharpLab](https://sharplab.io/#v2:D4AQTAjAsAULIGYAEAnApgYwPYoCZIAU0UBnLAOyVgG8qYkGlEmIAGJAOQEMBbNJagHM0AFwDcSAJblJ4gL6M6c2PGTgWAdhqNYi8GDqLquxYyKkKSLgBtJGfgF4k5NAHdCxMuQAUASiSusgAWApy8jkgARDZ2aJFIchIA9ElIAPIA0iamHhaUAEZY+UhOLq5+AcGh3HwlUYX58YlIKUgAoigoOEgAwgDKABwaAKwALNmmE3oQAJzeMfa+YlOMILPeDUsTCrByQA)

```
public record Person 
{ 
    public string Name {get; init;}    
}

public class Program
{   
    public static void Main() 
    {
        Person alice = new Person() with { Name = "alice" }; // OK
        Person bob = new() with { Name = "bob" }; // Error CS8754
        
        Console.WriteLine(alice);
        Console.WriteLine(bob);
    } 
}
```

**Expected Behavior**:
The program should compile without error. 

**Actual Behavior**:
The compiler rejects the initialization of variable 'bob' with CS8754.

**Comment by CyrusNajmabadi** [comment]
I'm not getting the value here.  if Person is a record, this would already work and woudl be shorter and clearer:

```c#
Person bob = new() { Name = "bob" };
```
