### ISSUE TITLE
IDE0130 shows as a warning in IntelliSense only

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54058]
**Version Used**: 

16.10.0

**Steps to Reproduce**:

https://github.com/dotnet/roslyn-analyzers/commit/ab7019ee000e20e0b822f6fca7d64eef4e09995d

Open `TestForEmptyStringsUsingStringLengthTests.cs`

**Expected Behavior**:

No warning. IDE analyzers are not warning by default, and it seems that roslyn-analyzers doesn't change the severity of this analyzer.

**Actual Behavior**:

- command-line builds show no warning (CI passes in roslyn-analyzers)
- IDE shows warning

Selecting IntelliSense only in error list:

![image](https://user-images.githubusercontent.com/31348972/121771736-8f3fd400-cb71-11eb-9ac1-7ced6c40c060.png)

---

Selecting Build only in error list:

![image](https://user-images.githubusercontent.com/31348972/121771738-94048800-cb71-11eb-8bbd-285c72b31c06.png)

---

**Additional information**:

From a previous discussion with @mavasani, IDE analyzers with code-style rules should use the `CreateDiagnostic` overload that takes an explicit severity.

The analyzer doesn't seem to do that:

https://github.com/dotnet/roslyn/blob/cb7113437ea012446c09a69951b2f5910411edba/src/Analyzers/Core/Analyzers/MatchFolderAndNamespace/AbstractMatchFolderAndNamespaceDiagnosticAnalyzer.cs#L70

This *may* be the issue, I'm not sure.

**Comment by sharwell** [comment]
> and it seems that roslyn-analyzers doesn't change the severity of this analyzer

Note that analyzers that do not configure a severity will obtain the severity from the Tools&rarr;Options value specified. Can you verify that none of the Code Style options are set to Warning in Tools&rarr;Options?

**Comment by Youssef1313** [comment]
@sharwell I'm not able to find thing related to this analyzer in Tools → Options.

**Comment by sharwell** [comment]
The warning is enabled via a category configuration:
https://github.com/dotnet/roslyn-analyzers/blob/ab7019ee000e20e0b822f6fca7d64eef4e09995d/.editorconfig#L189-L193

**Comment by Youssef1313** [comment]
@sharwell Why CI isn't failing then 😨

**Comment by sharwell** [comment]
CI only fails if the analyzer is part of the code style package used in CI. If IDE0130 was introduced later, the CI would not know about it and the IDE will execute one it knows about from the default installation.

**Comment by sharwell** [comment]
See #18818 for details. In this scenario, IDE0130 is behaving like diagnostic _A_ or _C_ from this:

> :memo: The comparison is performed on individual diagnostic IDs in order to support several scenarios expected to arise over time:
> 
> * A VSIX-installed analyzer supports diagnostics *A*, *B*, and *C*. Diagnostic *B* is later provided through NuGet to allow its use during command-line builds. Both packages should be used, where results of *B* are displayed only from the NuGet-installed analyzer while *A* and *C* continue to be displayed from the VSIX-installed analyzer.

**Comment by Youssef1313** [comment]
Makes sense!
Thanks for clarifying.
