### ISSUE TITLE
extern alias and source generators

### ISSUE THREAD

**Issue by kant2002** [dotnet/roslyn#54073]
I try to generate source code based on interfaces with same from different assemblies. I alias these assemblies in the project settings. 

I try to read aliases for assembly name using `GeneratorExecutionContext.Compilation.References`. 
That works fine.
I also use alias of assembly in the name of the generated file. When I emit file to disk, name of the file generated correctly. But Visual Studio cannot read alias and assume that all references assigned to the global alias. Also source code displayed in the VS cannot read alias of the assembly and thus this produce ton of warnings.

Right now problem IMO is that Semantic model does not have concept of alias for the assembly where type originates, or maybe   alias should be part of `INamedTypeSymbol`.

**Comment by jaredpar** [comment]
Not quite sure what the error is here. Can you elaborate more on what is going wrong in Visual Studio, what errors you see, etc ...?

**Comment by kant2002** [comment]
I see the difference between code generated in VS and actual code which is used by compiler when class name or filename has `extern alias` name which I get using `GeneratorExecutionContext.Compilation.References[0].Properties.Alias` for example.

**Comment by kant2002** [comment]
From this project https://github.com/kant2002/winformscominterop in case you think that would be practical.

1. This is what VS think for file `WinFormsComInterop_PrimitivesIStreamVtbl_primitives_Interop_Ole32_IStream.cs`. `primitives` and `global` is derived from name of alias.
![image](https://user-images.githubusercontent.com/4257079/121907228-acc99500-cd4d-11eb-8a7d-b0ac5b84a50e.png)

2. This is usage of generated code. You see red squiggles, because VS look at in-memory data.
![image](https://user-images.githubusercontent.com/4257079/121907055-84419b00-cd4d-11eb-871c-2c7cf2b06864.png)

3. this is files which actually produced by this Source Generator
![image](https://user-images.githubusercontent.com/4257079/121907561-fb772f00-cd4d-11eb-9681-24139621c28c.png)

4. Content of `WinFormsComInterop_PrimitivesIStreamVtbl_primitives_Interop_Ole32_IStream.cs`. Notice that `Primitives` properly appended to file name, and thus squiggles from pic 2 does not produce compilation warning.
![image](https://user-images.githubusercontent.com/4257079/121907626-0b8f0e80-cd4e-11eb-90dc-b2db7e85c7e8.png)

**Comment by kant2002** [comment]
I have VS 16.10.1 just for reference.

**Comment by jaredpar** [comment]
Is the issue then that you're seeing squiggles in the IDE then but build is succeeding?

**Comment by kant2002** [comment]
Yes.

**Comment by jasonmalinowski** [comment]
@kant2002: just so I follow better, the concern is that the generator _when running inside Visual Studio_ isn't getting the extern aliases applied correctly, which the generator is consuming? Or put another way, for the regular build, you're seeing a 'primitives' alias for the reference which you mirror into the type names, but for the IDE side of things you're not seeing it so the type names generate differently, and you then have a bunch of red squiggles because the expected types aren't there?

**Comment by kant2002** [comment]
I think problem a bit different.
When code generation run inside VS, assembly alias set for `ProjectReference` does not passed to source generator. 
https://github.com/kant2002/WinFormsComInterop/blob/0b2edf8bb8c6f1a1586f63f1d4b8ac18ab21bf45/WinFormsComInterop/WinFormsComInterop.csproj#L30-L33
I access that alias using `GeneratorExecutionContext.Compilation.References[0].Properties.Alias`.

Metadata about project incorrectly passed to a source generator, thus difference between VS and MSBuild.

**Comment by jasonmalinowski** [comment]
@kant2002 I think we are saying the same thing, so makes sense; we can investigate from here.
