### ISSUE TITLE
‎Guides to block structure don't shut down in all languages‎ 16.10.1 и 16.11.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54078]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Направляющие-для-структуры-блоков-не-от/1447489)._

---
Направляющие для структуры блоков, не отключаются, не смотря на то, что они выключены, сейчас изменение этих свойств не дает никакого эффекта! Это произошло после обновления на версию 16.10.1, я установил 16.11.0 PREVIEW и тут тоже самое!

Направляющие я всегда отключаю как и многое другое, так как они потребляют слишком много ресурсов процессора, при работе с большими файлами исходного кода, каково было мое удивление, когда они вдруг появились и начали доставлять мне неудобства) А у вас по прежнему нету возможности отката, к предыдущей версии в которой все работало, походу придется вернутся в 2017 студию) Когда уже будет возможность устанавливать хотя бы последние версии, которые продолжают использоваться по тем или иным причинам?) Почему мне нужно откатится сразу в 2017 студию, а не просто на предыдущую версию?) Обновление сырое, проблемное, почему нет возможности установить версию 16.9 в которой все работало?)

---
#### Feedback Bot on 6/10/2021, 07:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 6/11/2021, 11:46 AM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Please disable all third party extensions and try again. If the problem persists please share a sample code that can help us reproduce the issue.</p>

#### Wholemy on 6/11/2021, 06:39 PM: 

(private comment, text removed)
#### Wholemy on 6/11/2021, 07:42 PM: 

(private comment, text removed)
#### Wholemy on 6/11/2021, 08:12 PM: 

(private comment, text removed)
#### Wholemy on 6/11/2021, 08:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Summary of this issue is these two options are no longer observed (regression introduced in c337aead326a96751c2be4aeca4652c2b8015b20)

![image](https://user-images.githubusercontent.com/1408396/121930292-11a5d080-ccf7-11eb-9c16-50ee6920a827.png)

**Comment by Wholemy** [comment]
Я вижу что файл до этого не использовался, раз в версии 16.9 не было этой проблемы) Я просто не вижу причин, по которым мог бы перестать работать этот код, если перед этим код не менялся) В связи с чем изменилась логика?) Что привело к этому изменению?) Ну вам конечно виднее, просто хотелось бы понять почему именно такое решение в данном случае?) Почему именно в версии 16.10 это случилось, а не раньше?) Извините, если что не так понимаю, я пытаюсь понять откуда происходит эта проблема)

**Comment by sharwell** [comment]
> ‎I can see that the file has not been used before, since version 16.9 did not have this problem) I just don't see any reason why this code could stop working if the code didn't change before that) What led to this change?) Well, you know more, just want to understand why this decision in this case?) Why did it happen in 16.10 and not before?) Sorry, if I don't understand it, I'm trying to figure out where this problem comes from).‎

This behavior was a regression introduced in commit c337aea, which first appeared in the 16.10 release. I have submitted #54079 to fix the issue, and will update the milestone once I know the specific release where a fix will ship.

**Comment by Wholemy** [comment]
Спасибо, теперь я спокоен) Удачи)
