### ISSUE TITLE
"IDE0090: 'new' expression can be simplified" changes the behavior for Nullable<T>

### ISSUE THREAD

**Issue by ajtribick** [dotnet/roslyn#54081]
**Version Used**: 

Compiler version: '3.10.0-4.21269.26 (02984771). Language version 9.0.

**Steps to Reproduce**:

```C#
int? x = new int?(); // sets x to null
int? y = new();      // sets y to 0
System.Console.WriteLine($"x = {x}");
System.Console.WriteLine($"y = {y}");
```

**Expected Behavior**:

~~In my opinion, the least surprising option would be to have the second line should behave the same way as the first, i.e. `y` should be initialized to `null` in the above program, although the C# 9 spec implies that the current behavior is correct.~~

If these cases are intended to produce different results, then the IDE0090 suggestion should not be shown.

**Actual Behavior**:

The first line (setting `x`) receives a suggestion "IDE0090: 'new' expression can be simplified" - applying this suggestion changes the behavior of the program as `x` ends up being initialized to 0.

Output:

```
x = 
y = 0
```

**Comment by Youssef1313** [comment]
Related to (but probably *not* a duplicate): https://github.com/dotnet/roslyn/issues/50735.

**Comment by ajtribick** [comment]
Looking at this again, I think the main point of confusion is for parameterless constructors. Considering, e.g.

```C#
SomeStruct? x = new(foo, bar);
```

the second line being a call to `new SomeStruct(foo, bar)` is fairly obvious, whereas

```C#
SomeStruct? x = new();
```

is less obvious that it is calling `new SomeStruct()` rather than `new SomeStruct?()`. For clarity, it might be worth adding the opposite of the current suggestion: in cases where target-typed parameterless new is used on a nullable value type, suggest a less ambiguous form, e.g. `new SomeStruct()` or `default(SomeStruct)`.
