### ISSUE TITLE
Non spec-conformant eval order for System.Index Expression

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#54085]
**Version Used**: https://github.com/dotnet/roslyn/commit/7475a4a86589e1fd9733e67e20b4ea5778ecd228

**Steps to Reproduce**:
Compile the following code:
```csharp
using System;

class CollectionX
{
    private int[] _array = new[] { 1, 2, 3 };

    public int Length
    {
        get
        {
            Console.WriteLine("Length ");
            return _array.Length;
        }
    }

    public ref int this[int index]
    {
        get
        {
            Console.WriteLine("Indexer get");
            return ref _array[index];
        }
    }
}

static class SideEffect
{
    static CollectionX Get()
    {
        Console.WriteLine("Get ");
        return new CollectionX();
    }
    static int GetIdx()
    {
        Console.WriteLine("GetIdx ");
        return 1;
    }

    public static void Main()
    {
        int i2 =  Get()[Index.FromEnd(GetIdx())];
        Console.WriteLine(i2);
    }
}
```

**Expected Behavior**:
It should [print](https://dotnetfiddle.net/du5MLd) as described in [spec](https://github.com/dotnet/csharplang/blob/22a8d8976ee245da0390e8a4e63f2e029ff99f14/proposals/csharp-8.0/ranges.md):

```
Get 
GetIdx 
Length 
Indexer get
3
```

From spec:
> Otherwise, it will be translated as expr.GetOffset(receiver.Length)

so `expr` should be evaluated first, then `receiver.Length`

**Actual Behavior**:
It prints actually:
```
Get 
Length 
GetIdx 
Indexer get
3
```

**Comment by jaredpar** [comment]
@agocke this does seem to be a bug based on the spec as we're evaluating the `Length` before the indexer expression here. Can you confirm?

**Comment by agocke** [comment]
Yup looks like a bug to me.

**Comment by bernd5** [comment]
Any progress here?
