### ISSUE TITLE
Method call unnamed argument code fix

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54080]
Direct customer ask copying here:

>I added a new parameter to the function call and received this error:

 
![image](https://user-images.githubusercontent.com/46729679/121932107-55013e80-ccf9-11eb-959e-c6fb7d4d8cf6.png)

> It expects the parameter to be named, just like mappingFile parameter. ReSharper knows to propose such fix, but VS doesn’t.

> Those are the only options I got:

 
![image](https://user-images.githubusercontent.com/46729679/121932167-65191e00-ccf9-11eb-9e04-f60a10efb25d.png)

> Would really be nice if such functionality would be added to VS.

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/23326.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
