### ISSUE TITLE
Investigate performance impact of UseAutoPropertyAnalyzer...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5408]
We're seeing huge regressions in RPS since this was introduced (and possibly in upstream perf testing).  @rchande @CyrusNajmabadi @kevinh-ms need to sync on how we need to test this before re-enabling.

**Comment by KevinH-MS** [comment]
@CyrusNajmabadi I'm moving this to 1.2 since this isn't getting re-enabled for 1.1.

**Comment by mavasani** [comment]
Assigning to @KevinH-MS to verify if the regression still holds on latest bits. Please re-assign to me if it still the case.

**Comment by CyrusNajmabadi** [comment]
@KevinH-MS Any update on this?  I'd still really like to be able to reenable this feature :)

**Comment by mavasani** [comment]
I verified there were VM regressions with this analyzer enable. We should try to re-enable this again once @heejaechang replaces the IDE diagnostic engine with the v2 out of proc engine.

**Comment by KevinH-MS** [comment]
Thanks @mavasani !

**Comment by mavasani** [comment]
@basoundr You can probably mark this as verified once we have rolling perf results tomorrow.

**Comment by basoundr** [comment]
@mavasani sounds good
