### ISSUE TITLE
Add code style to sort members by accessibility 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54097]
Direct customer ask copying here: 

> Add a code style option to order members by accessibility similar to StyleCop.

**Comment by Youssef1313** [comment]
This feature could reuse CSharpDeclarationComparer.

**Comment by jmarolf** [comment]
possible related to 
- https://github.com/dotnet/roslyn/issues/35708
- https://github.com/dotnet/roslyn/issues/36812

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:

1. We do not have a good UX for customers to configure the sort order.
2. We can provide basic support with editorconfig.

Conclusion: Need customer development to understand priority of this feature..

**Comment by CyrusNajmabadi** [comment]
Not likely to do this.
