### ISSUE TITLE
IntelliSense completion options when pressing backspace

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54106]
Direct customer quote copying here:

> Autocompletion options for when you backspace, when you write again, the autocompletion options do not reappear. For example, if I have two variables called "handLeft" and "handRight", and I start writing "hand", I'm going to have both options. However, if I type "handL", then backspace to "hand", I don't have any completion available.

**Comment by CyrusNajmabadi** [comment]
Note: this is so that users can quickly go edit (through deletion) many pieces of code rapidly.  we don't want delete to being up the completion list, capturing the caret and causing frustration.  This was tried and received too much negative feedback.  However, we could have an option here, just as long as it's opt-in, and not opt-out.

**Comment by mikadumont** [comment]
Direct customer feedback copying here:

> After accepting an autocompletion suggestion, erasing part of the code and begin to type again, suggestions does not pop up. Kind of annoying if you accidentally accepted Debug.Write(), but wanted Debug.WriteLine() and have to either type it manually or backspace all the way to the ‘.’ to get suggestions to pop up again.

**Comment by CyrusNajmabadi** [comment]
you don't need to do that though.  just hut ctrl-space or ctrl-j and they'll pop up again after `Write` :)

**Comment by mikadumont** [comment]
> you don't need to do that though. just hut ctrl-space or ctrl-j and they'll pop up again after `Write` :)

Will follow up with them to try that.

**Comment by jinujoseph** [comment]
cc @genlu

**Comment by mikadumont** [comment]
Related customer feedback copying here: 

> The suggested text doesn't reappear when you start editing text. In order to get suggested text again, you have to delete the word and start again.

**Comment by CyrusNajmabadi** [comment]
So i'm very skeptical about this item.  About the only mechanism that could work woudl be to add an option for this.  However, in order for an option to work, the customers would have to find and enable them.  However, based on the fact that the customers don't know how to bring up completion anyways, i'm skeptical that then they would know how to find and enable such options.

**Comment by CyrusNajmabadi** [comment]
What if we had an intellicode feature that noticed you backspacing, then starting completion again just to select something that you could have brought up directly?  It could tell the user "instead of fully deleting and retyping, just hit ctrl-j".

**Comment by mikadumont** [comment]
I like the IntelliCode option. Sam also suggested in the design meeting today to use telemetry to drive some sort of inline tip so if a user rarely uses ctrl+space to bring up completion then we should give them a hint to use it. Also I was not aware that we have a Tools Option setting to bring up completion on backspace: `show completion when a character is deleted` so I will be syncing with UX  to figure out ways to make our options + shortcuts more discoverable.

**Comment by mikadumont** [comment]
I met with UX and a possible solution can be to add a tipping service that we can pop up after a certain number of interactions similar to what IntelliCode does for Find/Replace:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/46729679/127353050-6cddb958-317a-4de7-b28e-ab232d2b647c.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
