### ISSUE TITLE
Roslyn components should support versioning

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#54108]
Today, roslyn components have an implicit minimum API version that they support: the version of the `Microsoft.CodeAnalysis*.dll`s that they were compiled against. Any attempt to load a component into an earlier version will result in a missing reference error. 

~~In order to support graceful fallback, we should remove this restriction, by doing 'run time' binding redirects for the `Microsoft.CodeAnalysis*.dll`s, which will allow newer components to be loaded into older compilers.~~

~~When combined with a version attribute, we can allow authors to provide multiple implementations of a component that silently switch depending on the compiler version used to the load the component.~~

The above approach seems too fragile. It might be possible to get it to work, but instead we should start by allowing authors to multi-target their components.

We'll need an 'axis' to pivot on at authoring time, and a value to select against at consumption time. We decided the Roslyn version itself makes the most sense, as the APIs are listed on docs.microsoft.com as being available in a given version, and there is no need for the user to try and map to e.g. a specific SDK.

The current plan is to provide authoring and consumption targets that make this easy to do correctly. Over time we'll aim to get NuGet itself updated to support the feature in-box and remove the need for the targets.

**Comment by chsienki** [comment]
Closed via dotnet/sdk#20355 

We'll open a new issue to address the authoring side of things, for now you need to manually build the package.

**Comment by KalleOlaviNiemitalo** [comment]
In which repository will you open the issue?
