### ISSUE TITLE
IntelliSense not suggesting correct variable

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54107]
Direct customer quote copying here: 

> I’m trying to write a simple If statement, and I’m trying to use a local variable called howMany. No matter how much I type,  intellisense will not suggest the variable howMany. I press [Cntrl] + [spacebar] for suggestions and you can see it says there are no suggestions. Once I finish typing out the entire variable name VS is happy, and the red squiggly goes way, indicating it knows the variable is good. 

![image](https://user-images.githubusercontent.com/46729679/122086759-db308a00-cdb8-11eb-9be8-735a126dcbe9.png)

Here is the repo with the sample code - https://dev.azure.com/ChalkLogic/_git/VisualStudio-Intellisense-Woe

**Comment by Youssef1313** [comment]
I can reproduce this. The weird thing is that it doesn't reproduce with `==` or `>`. Only reproducible with `<`.

![howMany](https://user-images.githubusercontent.com/31348972/122093322-4145fd00-ce0b-11eb-94fe-caebd589e49f.gif)

**Comment by CyrusNajmabadi** [comment]
My guess is that it relates to our code to detect and handle generic expressions as they're being typed.

**Comment by pawchen** [comment]
I found that after removing `using System.Linq;`  the variable shows. I guess the `Count<T>` extension method caused intellisense to only show suggestions for `T`.

**Comment by Rekkonnect** [comment]
Fixed by #70122
Please confirm @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Sounds good
