### ISSUE TITLE
SourceGenerator run multiple times

### ISSUE THREAD

**Issue by aktxyz** [dotnet/roslyn#54101]
I have a net5 project that references a source generator in a netstandard2.0 project.

I have added some file based logging to try figure out more about how things are running, this logging records the processname/pid inside the ```Execute()``` method.

When I build inside of visual studio, I see my source generator ```Execute()``` method run 3 times with the following ```Process.GetCurrentProcess().ProcessName``` values ...

- ProcessName = ```csc```
- ProcessName = ```devenv```
- ProcessName = ```ServiceHub.RoslynCodeAnalysisService```

When I build via dotnet build, I see my source generator Execute() method run 4 times ...

- ProcessName = ```dotnet```
- ProcessName = ```devenv```
- ProcessName = ```ServiceHub.RoslynCodeAnalysisService```
- ProcessName = ```ServiceHub.RoslynCodeAnalysisService```

The reason I went thru all this is because the ONLY time the source generator runs to completion is when run by the ```csc``` process.  The rest all fail with a ```System.Text.Json``` reference exception .  If I remove that dependency and the code that relies on in from the source generator, then it always runs fine.

```
$Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
```

Any explanation on the multiple runs? and why the ```System.Text.Json``` reference only runs under ```csc```?

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/54100, https://github.com/dotnet/roslyn/issues/45535

**Comment by jaredpar** [comment]
The referenced issues are essentially the primary discussion for this problem.
