### ISSUE TITLE
[Performance] Large amount of contention in VisualStudioWorkspaceImpl.ApplyBatchChangeToWorkspace (1.2% CPU of solution open) 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#54138]
**Version Used**: 
17.0.0 Preview 1.0 [31401.12.main]

[Trace](https://microsoft.sharepoint.com/:f:/t/VSIDEPerformance/Etm7IDAYTSpIn9CAQYfXgYUBuUMciQ4xUku3e1KWZtLspw?e=YOQ2sB) (1404 projects)

There's such a large amount of contention in  VisualStudioWorkspaceImpl.ApplyBatchChangeToWorkspace that overhead of calling Monitor.Enter itself (not the blocking wait) is 1.2% of all CPU:

![image](https://user-images.githubusercontent.com/1103906/122178819-46b64c80-ceca-11eb-8eea-b0ca5febfac6.png)

**Comment by sharwell** [comment]
Copied from #54135:

> @davkean The project system is instructing the workspace to apply changes (inherently an ordered operation) in parallel on _50 threads_. Can you move the calls to `ApplyProjectChangesUnderLockAsync` (specifically when invoked by OnProjectChangedAsync) from the normal thread pool task scheduler to a scheduler that restricts concurrency?
> 
> Removing locks in VisualStudioWorkspaceImpl will be difficult, but if we consider a change in that direction here is a list of the locks most impacting this scenario:
> ![image](https://user-images.githubusercontent.com/1408396/122421464-3d1bfb80-cf41-11eb-9327-eb18b8982a18.png)

**Comment by davkean** [comment]
@sharwell Agree, closing in lieu of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1370097/.
