### ISSUE TITLE
[Performance] ConvertMetadataReferencesToProjectReferences_NoLock spends larges amounts of CPU opening a solution (5.2% CPU of solution open)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#54134]
**Version Used**: 
17.0.0 Preview 1.0 [31401.12.main]

[Trace](https://microsoft.sharepoint.com/:f:/t/VSIDEPerformance/Etm7IDAYTSpIn9CAQYfXgYUBuUMciQ4xUku3e1KWZtLspw?e=YOQ2sB) (1404 projects)

**Steps to Reproduce**:

5% of CPU used while opening the above solution is spent in ConvertMetadataReferencesToProjectReferences_NoLock.

![image](https://user-images.githubusercontent.com/1103906/122176788-53d23c00-cec8-11eb-927a-3de5448c0f13.png)

/cc @jasonmalinowski @CyrusNajmabadi

**Comment by sharwell** [comment]
It seems like one good way to optimize this is using an interning cache for file paths that appear in metadata references passed to `ProjectInfo.Create`. This would allow the use of reference equality in the above hot path instead of case-insensitive string comparison.

**Comment by davkean** [comment]
I've opened https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1370146 in lieu of this one so that division queries pick it up.
