### ISSUE TITLE
expose /reportanalyzer option in Visual Studio

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#54148]
The /reportanalyzer flag is a useful diagnostic tool in terms of identifying performance problems in builds that are analyzer related. Adding this to an existing commandline can produce a binary log detailing exactly how much time an analyzer spent in the build. Unfortunately this command-line only option is impossible for users to discover. It would be ideal if it were integrated into the Visual Studio UI in some way

**Comment by jmarolf** [comment]
## Design Review

**Discussion:**
 - Brief discussion on this topic. One of the main problems is that there is no built-in mechanism to show a binary log in Visual Studio today, a pre-requisite for this feature. The VSIX that ships in dotnet/project-system-tools has a binary log viewer built in but there is a concern about the additional friction of asking customers to install additional tools in order to diagnose performance problems 

**Conclusion:**
 - Prototype in project-system-tools to start

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of design/feedback.
