### ISSUE TITLE
[Performance] GetRemoteSupportedProjectLanguages consumes a large amount of time (3% of solution open)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#54162]
**Version Used**: 
17.0.0 Preview 1.0 [31401.12.main]

[Trace](https://microsoft.sharepoint.com/:f:/t/VSIDEPerformance/Etm7IDAYTSpIn9CAQYfXgYUBuUMciQ4xUku3e1KWZtLspw?e=YOQ2sB) (1404 projects)

**Steps to Reproduce**:

2% of solution open time in the above trace is spent in GetRemoteSupportedProjectLanguages which walks the entire solution for every created or changed project.

![image](https://user-images.githubusercontent.com/1103906/122330030-c5b48f00-cf75-11eb-8e7a-4a2e551fa30f.png)

**Comment by CyrusNajmabadi** [comment]
It seems pretty crazy to me that literally just walking a collection and doing some string checks accounts for so much time.  Do we ahve better performing immutable collections that we can depend on?

**Comment by sharwell** [comment]
Duplicate of #53769

**Comment by davkean** [comment]
@CyrusNajmabadi This is a O (n^2) operation which occurs over and over again.

**Comment by sharwell** [comment]
@davkean The operation here is O(n), which is then repeated.

**Comment by davkean** [comment]
This O(n) operation is repeated for every project in the solution.
