### ISSUE TITLE
Code generator erroneous intellisense error

### ISSUE THREAD

**Issue by tonyhallett** [dotnet/roslyn#54175]
Visual Studio 16.9.1
Code analysis 3.9.0 ( I had issues with 3.10.0 )

**Steps to Reproduce**:

Generate extension method using code generator

**Expected Behavior**:

No intellisense error

**Actual Behavior**:

Intellisense error - "does not contain a definition for...."

https://user-images.githubusercontent.com/11292998/122447832-0f17d500-cf9c-11eb-83c0-300f7a315287.mp4

This error is intermittent.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of reports of this since this time.
