### ISSUE TITLE
Switch Expression new() behavior defective

### ISSUE THREAD

**Issue by michaelcheers** [dotnet/roslyn#54193]
Duplicate searched the following: https://github.com/dotnet/roslyn/issues?q=is%3Aissue+in%3Atitle+switch+new+is%3Aclosed+

**Version Used**: latest

**Steps to Reproduce**:

```cs
public struct A {public int n;}	

	public static A ToA (object o) =>
		o switch
		{
			int n => new A(){n = n} // Works
		};
	
	public static A ToA_ (object o) =>
		o switch
		{
			int n => new() // Works
		};
	
	public static A ToA__ (object o) =>
		o switch
		{
			int n => new (){n = n} // Doesn't work :(
		};

```

**Error:** `The name 'n' does not exist in the current context`

https://dotnetfiddle.net/lpERQx

**Comment by jaredpar** [comment]
That's an interesting behavior as it appears that the local `n` is not recognized as in scope in the last example.

**Comment by jcouv** [comment]
FYI @alrz

**Comment by alrz** [comment]
Looks like we're binding with the wrong binder but I'm not sure why this only happens for a switch.
