### ISSUE TITLE
IOperation Tree in syntax visualizer is blank

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#54194]
**Version Used**: 
Version 16.11.0 Preview 3.0 [31416.256.d16.11]
I am using Light theme.

![image](https://user-images.githubusercontent.com/24360909/122483059-96f2e480-cf86-11eb-9e61-6dce492db5f5.png)

Why do I need to select then see the operation?

**Comment by Youssef1313** [comment]
Does this Belong to dotnet/roslyn-sdk?
