### ISSUE TITLE
Not offered enum preselection inside an enum if the expression contains more than one OR (|)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#5419]
Given the following:

``` C#
    [Flags]
    internal enum ProjectTreeWriterOptions 
    {
        None,
        Tags,
        FilePath,
        Capabilities,
        Visibility,
        AllProperties = FilePath | Visibility | $$
    }
```

I'm not offered preselection at the selected location. If I type the same thing at an argument to a method, I _am_ offered preselection.

**Comment by davkean** [comment]
Hmm, can't figure out logic here, I'm not offerred preselection in the following:

``` C#
AllProperties  = FilePath ^ ProjectTreeWriterOptions.Visibility ^ $$
AllProperties  = FilePath & ProjectTreeWriterOptions.Visibility | $$
AllProperties  = FilePath & ProjectTreeWriterOptions.Visibility ^ $$
```
But _am_ offered preselection in the following:
``` C#
AllProperties = FilePath | ProjectTreeWriterOptions.Visibility & $$
AllProperties = FilePath ^ ProjectTreeWriterOptions.Visibility & $$
```

**Comment by Pilchie** [comment]
This is likely an issue with whether the Type Inference service handles these specific syntactic constructs.

**Comment by CyrusNajmabadi** [comment]
I've debugged through this and it does not appear to be an issue in the TypeInferenceService.  It looks like an issue in the SemanticModel.  

In the original example:

```c#
AllProperties = FilePath | Visibility | $$
```

We ask the SemanticModel what the TypeInfo and SymbolInfo are for ```FilePath | Visibility```.  The SemanticModel returns back "Int32" for the TypeInfo's Type (and ConvertedType).  And the SymbolInfo is ```System.Int32 System.Int32.op_BitwiseOr(System.Int32 left, System.Int32 right)```.

This seems wrong, and goes against this part of the language specification:

> 7.11.2 Enumeration logical operators
Every enumeration type E implicitly provides the following predefined logical operators:  
E operator &(E x, E y);
E operator |(E x, E y);
E operator ^(E x, E y);

Based on the language spec, I think that the type of this expression should be the enum type.  And the symbol should be something like: ```ProjectTreeWriterOptions ProjectTreeWriterOptions.op_BitwiseOr(ProjectTreeWriterOptions left, ProjectTreeWriterOptions right)```.

@gafter What do you think?  Should this be assigned over to someone on the compiler side?

**Comment by gafter** [comment]
@CyrusNajmabadi you are right. Assigning to the compiler team.

**Comment by TyOverby** [comment]
> Spec 14.3: "Within an enum member initializer, values of other enum members are always treated as having the type of their underlying type"

Sounds like this isn't a spec violation as it occurs inside the enum member initializer.  However, I agree that this is not very user-friendly.

**Comment by CyrusNajmabadi** [comment]
Back to me to figure out what to do here.

**Comment by CyrusNajmabadi** [comment]
Giving to Ravi as this is in completion.
