### ISSUE TITLE
XmlSeeAlsoElement uses 'cref' instead of 'href'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#54201]
The following method generates a `cref` attribute, but it should generate an `href` attribute:

https://github.com/dotnet/roslyn/blob/3c1ec210ef3941dd8aed96397a1ace4a2cbe2fb9/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs#L711-L720

**Comment by Youssef1313** [comment]
Note: There is an overload that explicitly takes `CrefSyntax` 😕

**Comment by sharwell** [comment]
Yes, this is the overload specifically for creating an `href`.
