### ISSUE TITLE
Rename of class name dialog box issue

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54207]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-of-class-name-dialog-box-issue/1447943)._

---
Right click on class name and select rename option. rename dialog box will cover all class editor section so that unable to rename the class

---
#### Feedback Bot on 12/2/2020, 00:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/2/2020, 09:37 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/22/2021, 11:51 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Timothy Elmer on 4/18/2021, 08:31 PM: 

<p>This is an issue when working with a smaller (e.g., split) window. Typing in an editor I can’t see isn’t optimal UX.</p>
<p>Resizing the window is a workaround - at least for me - but that shouldn’t be necessary. Automatically relocating the dialog within the parent editor so that it <em>doesn’t</em> overlap the selected text would be ideal, but allowing the user to move it would also work.</p>
<p>Trying to rename a class:<br>
<img src="https://aka.ms/dc/image?name=Bb7d701b0446445489712262a948c6d0a637543995965911959_20210418-202636-image.png&amp;tid=b7d701b0446445489712262a948c6d0a637543995965911959" alt="image.png"></p>

#### Feedback Bot on 6/10/2021, 11:20 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by ryzngard** [comment]
Duping to our design discussion to help track this: #57715
