### ISSUE TITLE
Compound Assignment Operator does not highlight

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54208]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Compound-Assignment-Operator-does-not-hi/1448026)._

---
[severity:It's more difficult to complete my work]
So, 
Basically unless other people "report" this problem in enough time Microsoft assumes that nobody cares.
I would gather instead that most people aren't used to the new operator and when it suggests the change from "x = x ?? y" to "x ?? = y", they simply have the intellisense "fix" the code for them and it moves on, 
and they are none the wiser that it never updated the syntax highlighting.

As a developer, I don't spend my time trolling the "bug reports" on MSDN developer community in order to make sure that Microsoft fixes flaws in their software, because I have my own job to do. 
I would bet there are quite a few flaws out here that I would totally agree need to be fixed, but most of us don't have the time to make sure we find them and vote on them, and only waiting 35 days 
for it to be flagged is a bit lame.  Especially, when this is also a fix that could be implemented in probably 30 seconds, by simply adding the ?? = pattern to the existing list of "operator" patterns for 
the Syntax Highlighting engine.  

I really want to use this operator but I WON'T until it highlights correctly.  Having poorly highlighted operators, identifiers, keywords, etc. really slows down code evaluation and debugging 
because our eyes are expecting one color and getting another, so in order to find where this is, or understand what it's doing, i'm seeing "identfier identifier identifier" instead of "identifier operator identifier".
Makes a difference.

Thanks
Sean

---
#### Feedback Bot on 11/17/2020, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/18/2020, 10:07 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Feedback Bot on 6/11/2021, 00:11 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/45999
