### ISSUE TITLE
Ambiguous interface members error (CS0229): Please provide code fixer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54210]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ambiguous-interface-members-error-CS022/1451367)._

---
[severity:It bothers me. A fix would be nice]
Using the example from the docs for CS0229: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0229?f1url=%3FappId%3Droslyn%26k%3Dk(CS0229)
There is a (deliberate) error in the sample code, on the line:

x.Count = 1;  // CS0229

Right-clicking on the red-squiggle-underlined `Count` property could provide two options for code fixes to resolve the ambiguity, as the comments suggest:

// ((IList)x). Count = 1;  
        // ((ICounter)x). Count = 1;

---
#### Feedback Bot on 6/10/2021, 11:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
