### ISSUE TITLE
IntelliSense suggestions not type aware

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54211]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-suggestions-not-type-aware/1439935)._

---
RE: this twitter thread: https://twitter.com/mika_dumont/status/1272384372302209024

When filling out function arguments to call an existing function or on the right hand side of the assignment operator I would expect suggestions to be sorted more usefully. Either by type or objects that have a member matching the desired type.

Presently, all IntelliCode suggestions in scope are presented in alphabetical order in the two scenarios mentioned above.

I previously had Visual Studio 2017 installed, but explicitly uninstalled it before installing VS 2019 via vs_Community.exe (June 9th, 2020)

I'd be happy to answer any further questions.

Thanks for looking at this,

James Felton

---
#### Feedback Bot on 6/15/2020, 07:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/22/2020, 05:05 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.
#### Feedback Bot on 6/23/2020, 00:03 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 7/23/2020, 06:33 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 6/2/2021, 07:58 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to broad scope and lack of design.
