### ISSUE TITLE
Extend Quick actions, Replacements and IntelliSense actions scope to "namespace"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extend-Quick-actions-Replacements-and-I/1362961)._

---
When applying any of the quick actions, IntelliSense actions or find/replace actions or even refactoring actions, one has the option to apply them to a selection, the document, the project or the solution. 
I propose to expand this to "namespace", as often I want to apply an action to all classes in a certain namespace only (for example suppressing a certain warning, or applying an editor action).

---
#### Feedback Bot on 3/9/2021, 10:48 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Related to #30375

**Comment by Hefaistos68** [comment]
"Current member" ( #30375) is implemented for replace dialog in 17.5, not seeing any change for quick/intellisense actions though.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
