### ISSUE TITLE
Visual Studio :: Autoformat of the code as a table

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54214]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-::-Autoformat-of-the-code-/1447434)._

---
In Visual Studio my code looks not very well ...
There are more than this example than that ... Switch-Case
Method's that are equal

```
private List<DBKeyValue> m_KVList = new List<DBKeyValue>() {
		new DBKeyValue("RefObjLocation", DBKeyValue.ValueTyp.VARCHAR ),
		new DBKeyValue("Street",  DBKeyValue.ValueTyp.TinyText),
		new DBKeyValue("StreetNo", DBKeyValue.ValueTyp.TinyText),
		new DBKeyValue("Postcode", DBKeyValue.ValueTyp.TinyText),
		new DBKeyValue("City", DBKeyValue.ValueTyp.TinyText),
};
```

BETTER:

```
private List<DBKeyValue> m_KVList = new List<DBKeyValue>() {
	new DBKeyValue("RefObjLocation", DBKeyValue.ValueTyp.VARCHAR ),
	new DBKeyValue("Street"        , DBKeyValue.ValueTyp.TinyText),
	new DBKeyValue("StreetNo"      , DBKeyValue.ValueTyp.TinyText),
	new DBKeyValue("Postcode"      , DBKeyValue.ValueTyp.TinyText),
	new DBKeyValue("City"          , DBKeyValue.ValueTyp.TinyText),
};
```
NEXT EXAMPLE:
			
```
public string RefObjLocation { set { Find("RefObjLocation")?. CSValue_Set(value); } get { return (string)Find("RefObjLocation")?. CSValue_Get(); } }
public string Street { set { Find("Street")?. CSValue_Set(value); } get { return (string)Find("Street")?. CSValue_Get(); } }
public string StreetNo { set { Find("StreetNo")?. CSValue_Set(value); } get { return (string)Find("StreetNo")?. CSValue_Get(); } }
public string Postcode { set { Find("Postcode")?. CSValue_Set(value); } get { return (string)Find("Postcode")?. CSValue_Get(); } }
public string City { set { Find("City")?. CSValue_Set(value); } get { return (string)Find("City")?. CSValue_Get(); } }
```
BETTER

```
public string RefObjLocation { set { Find("RefObjLocation")?. CSValue_Set(value); } get { return (string)Find("RefObjLocation")?. CSValue_Get(); } }
public string Street         { set { Find("Street"        )?. CSValue_Set(value); } get { return (string)Find("Street"        )?. CSValue_Get(); } }
public string StreetNo       { set { Find("StreetNo"      )?. CSValue_Set(value); } get { return (string)Find("StreetNo"      )?. CSValue_Get(); } }
public string Postcode       { set { Find("Postcode"      )?. CSValue_Set(value); } get { return (string)Find("Postcode"      )?. CSValue_Get(); } }
public string City           { set { Find("City"          )?. CSValue_Set(value); } get { return (string)Find("City"          )?. CSValue_Get(); } }
```

---
#### Dada Huo [MSFT] on 6/10/2021, 07:39 PM: 

<p>Thank you for your feedback!</p>
<p>Does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use? It would be very helpful if you could provide some screenshots of this issue. Thanks for your help!</p>

#### frank.kastrup on 6/10/2021, 10:24 PM: 

<p>Hi,<br>
That is a feature wish.<br>
The existing “Automatic Code Formating” works normaly very well. I use it and i like it. I can only switch it off or on - compleately.</p>
<p>Some code is not well-done styled. I call it Table-View. “Same Thinks in the same Column”<br>
The Strings, Comma, Brackets are lined together …</p>
<p>possible Solution i can see:<br>
A) Switch it PARTLY off - “Automatic Code Formating”<br>
B) “Automatic Code Formating” - should see that Code below/upper look’s nearly equal</p>

#### Dada Huo [MSFT] on 6/10/2021, 11:09 PM: 

<p>Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jinujoseph** [comment]
Duplicate #36859
