### ISSUE TITLE
Making sure all unit tests actually run.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5422]
While investigating a problem with PR #5328 today with @amcasey and @jmarolf, we found that the `AddAwaitTests` had a `public void Test()` method in them, and the existence of this method causes xUnit to ignore all tests from the entire containing type, without issuing a test failure. On commandline xUnit runs, you can see a `System.ArgumentException [FATAL]` with the following description, but still the suite reports no failures in the end:

``````
```Ambiguous method named Test in type Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.Async.AddAwaitTests```
``````

Can we find a way of preventing this thing in the future? An analyzer that checks for `Test()` methods in types containing `[Fact]` attributed methods? Or a change to build process that makes the xUnit run more verbose and checks for the above error message?

**Comment by amcasey** [comment]
FYI @tannergooding

**Comment by amcasey** [comment]
@dpoeschl Is there a particular commit one could check out to repro the issue?

**Comment by dpoeschl** [comment]
@amcasey This is the last commit before @jmarolf checked in the rename away from ```Test()```: https://github.com/dotnet/roslyn/commit/dd396a80d64ee47ff2d984d7582ef1a013ddf159

Running xUnit on ```Roslyn.Services.Editor.CSharp.UnitTests.dll``` from the command line will show the error I mentioned above, and no tests under AddAwaitTests will actually be run.

**Comment by dpoeschl** [comment]
The exception & message above are *only* output to stderr by default. They aren't printed to standard out or to a specified xml output file (the skipped type isn't mentioned whatsoever). 

Also, the problem appears to be more widespread. Just noticed this one:

``` Ambiguous method named TestEquivalenceKey in type Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.GenerateMethod.GenerateMethodTests+GenerateConversionTest```

I'll do a pass now to manually sift out all the existing skipped types while we work on an automated approach to catching this.

FYI: @tannergooding

**Comment by dpoeschl** [comment]
The ```GenerateMethodTests+GenerateConversionTest``` class was the only other one in the test suite with this problem, so I have PR #5441 out to re-enable them (if tests pass).

**Comment by amcasey** [comment]
@dpoeschl Is there more to do here?

**Comment by davkean** [comment]
Yeah, I think we change RunTests to catch this in the open - have it fail if anything is written to stderr by xunit-runner.

**Comment by jasonmalinowski** [comment]
xunit analyzers catch this for us now.
