### ISSUE TITLE
IntelliSense snippet for move and copy constructors and assignment operators

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54224]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-snippet-for-move-and-copy-c/1448525)._

---
IntelliSense has a snippet "ctor", which creates a void constructor for class, but it would be nice to have a snippet for ALL constructors/assignment operators and destructor - void ctor, move/copy ctor, move/copy assign, dtor.
You would type something like "ctorall" withing class Test and get:

```
class Test {
public:
	Test() = default;
	Test(const Test& other) = default;
	Test& operator=(const Test& other) = default;
	Test(Test&& other) noexcept = default;
	Test& operator=(Test&& other) noexcept = default;
	~Test() = default;
};
```

It's sometimes a little bit of a hassle to write all those by hand, a snippet would be nice - if there's one for void ctor, why not make another one for all of them?

---
#### Feedback Bot on 6/14/2021, 07:05 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is a c++ suggestion. Not a c# one
