### ISSUE TITLE
typeof().Name to nameof analyzer should ignore void type

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#54233]
**Version Used**:  3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

**Steps to Reproduce**:

```cs
var voidTypeName = typeof(void).Name;
```

**Expected Behavior**:
no errors from analyzers

**Actual Behavior**:
`IDE0082: typeof can be converted to nameof`
resulting in
```cs
// CS0673: System.Void cannot be used from C# -- use typeof(void) to get the void type object
var voidTypeName = nameof(void);
```

Related to #45806, #18284

**Comment by CyrusNajmabadi** [comment]
@jnm2

**Comment by jnm2** [comment]
@CyrusNajmabadi I wasn't involved with the implementation of this one

**Comment by CyrusNajmabadi** [comment]
@jnm2 apologies!  I totally thought this was yours. :-)

**Comment by RikkiGibson** [comment]
is it not possible to just make `nameof(void)` legal?

**Comment by CyrusNajmabadi** [comment]
> is it not possible to just make nameof(void) legal?

i'd be pretty opposed to that as we don't support things like `nameof(int)` or any other special types.  Furthermore, it's unclear what result that should make.  previously `nameof(X)` was always just going to give you the constant value `"X"`.  Now you get something unrelated to what's in the parens.

**Comment by jnm2** [comment]
`nameof(SomeTypeAlias)` returns `"SomeTypeAlias"`, and I would assume that if keywords were supported, they would be like aliases. I don't understand what the use case would be to allow predefined type keywords though.
