### ISSUE TITLE
Need a way to reopen issue

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#5424]
I reported #5413 and it was considered duplicate which I don't, but I cannot reopen it. It would be nice to be able to do so.

**Comment by dpoeschl** [comment]
This is a request for GitHub itself, or for us to write something into @dotnet-bot (or similar) that lets you type "reopen this" or some other command to cause the bot would reopen it on your behalf.

One of the problems is that just reopening it might not be enough to get the issue noticed. If it's in an old milestone that isn't part of any current triage process, then it might go undetected for quite a while. Reopening via bot could potentially remove all labels & milestones, which would guarantee a retriage. I'm going to move this to Area-Infrastructure to discuss our options here. I've also reopened #5413 for you.

**Comment by jaredpar** [comment]
@diryboy unfortunately there isn't a way we can give users the ability to reopen bugs (or even label them) without also making them full contributors to the project.  If the granularity existed I think it's something we would definitely consider adding (it would be really nice if users for example were allowed to label bugs).  Right now though there just aren't any options available for us.

Leaving a comment, as you did, is the best way to handle this right now.  I just hadn't gotten to that email before you opened this issue :frowning:

**Comment by diryboy** [comment]
Thank you @dpoeschl and @jaredpar, I didn't know this was the limitation of GitHub.

**Comment by dpoeschl** [comment]
Reopening so the infrastructure team can discuss whether we'd like to set up anything here to get around the GitHub limitations.

**Comment by davkean** [comment]
I don't think we're going to realistically do anything above and beyond Github's limitations here. Free to comment on existing bug or open a new bug and we can reopen. You can send feedback to github around this issue at support@github.com.
