### ISSUE TITLE
[Feature request] When generating `summary` add `<exception>` for every exception thrown in a method

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/roslyn#54245]
This is related to Visual Studio (moved here from https://github.com/dotnet/csharplang/discussions/4850).

**Idea**
When user types `///` above a method, `summary` comment is generated with place for method and parameter descriptions.
Suggestion is to also automatically add place for `exception` description (if the method explicitly throws some exception(s)). 

**Motivation**
It's useful to see what exceptions can be thrown from a method and for what reason, but most developers don't even know that it's possible to communicate that information to method's consumer.
This will familiarize developers with existence of [`<exception>`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/exception) tag and facilitate it's adoption. So far it's mostly used by framework methods (that's how I found out that it exists).

**Comment by jinujoseph** [comment]
Related to #15573
