### ISSUE TITLE
It looks like ERRWRN_NextAvailable got assigned an arbitrary large number, leaving a big gap of unused values 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54269]
```
        ' // AVAILABLE                             42600 - 49998
        ERRWRN_NextAvailable = 42600
```

Note that recently the number was not payed attention to, new warnings were added by incrementing previous values. So, it is not clear what was the intent behind changing ERRWRN_NextAvailable and leaving a big gap. Was the intent to actually prevent the reuse of values, or was the intent to move the value far enough to avoid adjusting it every time a new warning is added? Probably should clarify what a dev is supposed to do there.

**Comment by AlekseyTs** [comment]
@agocke It looks like you made the change. Could you please clarify the intent?

**Comment by agocke** [comment]
The latter was the intent. I think at this particular time there was some difficulty with merging a bunch of features simultaneously and updating this value was becoming tricky with merge conflicts.

**Comment by jaredpar** [comment]
Closing as seems like a valid reason. Please let me know if you disagree here.
