### ISSUE TITLE
Multiline Comments in C# violate LF line ending of file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54261]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Multiline-Comments-in-C-violate-LF-line/1455105)._

---
[severity:It's more difficult to complete my work]
When editing a file with LF line endings, visual studio correctly appends an LF when you hit the enter key.
However, when you start a multiline comment by typing /* and then hit enter to extend the multiline comment, Visual Studio always inserts a CRLF.

Naturally this causes the editor to complain the next time the file is saved and reopened that the file has mixed line endings.

---
#### Feedback Bot on 6/20/2021, 11:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is similar to #23143, but this issue applies to block comments.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Maybe code that was using Environment instead of the editor options here?
