### ISSUE TITLE
Somehow ERR_MultipleAnalyzerConfigsInSameDir got declared in warnings range for VB

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#54267]
```
        WRN_AttributeNotSupportedInVB = 42381
        ERR_MultipleAnalyzerConfigsInSameDir = 42500
        WRN_GeneratorFailedDuringInitialization = 42501
```

**Comment by chsienki** [comment]
I see, I didn't realize that the `ERR_` and `WRN_` were explicitly separated in VB.

@jaredpar I think its ok to change the number? As its an error, code will already not compile and you can't suppress it so changing it shouldn't have any observable effect (except for our tests). Thoughts?

**Comment by jaredpar** [comment]
Agree that changing the error code is probably the best approach here. 

At the same time may want to add a test that fails if we ever accidentally do this again. Hopefully it's the only case where we have two names with the same number :smile:
