### ISSUE TITLE
Add accessibility to generate ctor intent

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#54288]
Support accessibility here - https://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/ExternalAccess/IntelliCode/Api/IIntentSourceProvider.cs,38

in the form of "Accessibility": "<[one of these](https://sourceroslyn.io/#Microsoft.CodeAnalysis/Symbols/Accessibility.cs,96ec9a52e8b1305b)>"

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative, and that we do not seem to be investing in intents anymore.
