### ISSUE TITLE
Remove DebuggerMetadataExtensions class, once newer version of debugger is integrated to Roslyn

### ISSUE THREAD

**Issue by ericfe-ms** [dotnet/roslyn#5428]
The class Microsoft.VisualStudio.Debugger.Metadata.DebuggerMetadataExtensions is a temporary stub until the expression evaluator consumes the VS 2015 Update 1 version of Microsoft.VisualStudio.Debugger.Metadata.dll.  Once the references are updated, this class should be removed.

**Comment by amcasey** [comment]
@KevinH-MS This work depends on internal bug 131134, so I've assigned it to you.

**Comment by ManishJayaswal** [comment]
this is fixed.
