### ISSUE TITLE
"Rename" doesn't rename the type in a comment if I have check "Include Comments"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54294]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Rename-doesnt-rename-the-type-in-a-co/1322773)._

---
I have a class and would like to rename it. The rename tool doesn't rename the class in a xml comment if I check "Include Comments"
![image](https://user-images.githubusercontent.com/475144/130129210-51904981-aafb-4334-8de7-de5d1e4a9c86.png)

And example:

```
class Example
{
    /// <summary>
    /// Creates an instance of <see cref="Example"/>
    /// </summary>
   public Example()
   {
   }
}
```
I want to rename Example. It can successfully identify and rename the one in the comment. But if I check "Include comments", it cannot rename the one in the comment.

---
#### Feedback Bot on 1/27/2021, 10:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Seven Liu [MSFT] on 1/28/2021, 00:05 AM: 

<p>Hi Maoliang Huang,<br>
Thank you for your feedback! To investigate the issue further, could you give us a detailed repro steps? It would be appreciated if you can share us related video. Looking forward to your reply, thanks!</p>

#### Maoliang Huang [MSFT] on 1/28/2021, 09:47 AM: 

<p>I attached a repro project. It’s just the template C# library (.Net core 3.1).<br>
<a target='_blank' href="https://aka.ms/dc/file?name=Bb2eec17502c8453cb92da5f5f255ed84637474526988484462_ClassLibrary1.zip&amp;tid=b2eec17502c8453cb92da5f5f255ed84637474526988484462">ClassLibrary1.zip</a></p>
<p>This is the recording of what happens. Starting at around 15 seconds, I try to rename “ClassLibrary1” to “Example” and then check “Include Comments”. You’ll see there is an unresolved issue in the same configuration UI and the name in the xml comments is changed back to “ClassLibrary1”.</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bc3f4b88e0fed43cda8c84089b33a1176637474527186861584_2021-01-28_09-00-06.mp4&amp;tid=c3f4b88e0fed43cda8c84089b33a1176637474527186861584">2021-01-28 09-00-06.mp4</a></p>

#### Feedback Bot on 1/28/2021, 06:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/29/2021, 09:22 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 5/11/2021, 01:04 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Repro steps from example code:

```csharp
class Example
{
    /// <summary>
    /// Creates an instance of <see cref="Example"/>
    /// </summary>
   public Example()
   {
   }
}
```



1. Invoke rename on class `Example`
2. Rename to `Other`
3. Check the "Include in comments" checkbox

Expected: 

No change, rename still works

Actual: 

Conflicts noted
