### ISSUE TITLE
Please add a VB test for using nameof(X) inside the initializing expression for X

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#543]
At the suggesting of @AlekseyTs it would be nice to have a test that verifies that issue #40 is not a problem in VB.

**Comment by gafter** [comment]
@AlekseyTs this is the issue for the test you requested.

**Comment by gafter** [comment]
@AlekseyTs Can you please verify the fix?

**Comment by AlekseyTs** [comment]
Verified
