### ISSUE TITLE
unable to remove indent guides

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54305]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/unable-to-remove-indent-guides/1438078)._

---
[regression] [worked-in:16.9.5]
Hi.
I just updated to Visual Studio 2019 v16.10.
I unchecked the two options under "Block Structure Guides" in C# options.
The indent guides are always visible.

Thanks.

---
#### Feedback Bot on 6/1/2021, 06:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/2/2021, 09:41 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### William Sade de Paiva on 6/22/2021, 04:05 AM: 

<p>Hi Joey.</p>
<p>Thanks for the fast reply.<br>
Ok, It worked now.</p>
<p>“But”, before v16.10, it was not necessary to set this configuration.<br>
Even in VS 2017, it was not necessary either.</p>
<p>It is not the first time Visual Studio 2019 changes its behaviour after an update.</p>
<p>Regards, William</p>

#### trusomeg@gmail.com on 6/22/2021, 01:15 PM: 

<p>Workaround provided doesn’t solve the problem - options under “Block Structure Guides” in C# still doesn’t work. Also it’s misleading, because section with “settings that control whether code constructs such as if blocks are collapsible” is called Outlining, while we are talking about structure indent guides.</p>
<p>The issue is about setting called “Show structure guide lines” in Tools &gt; Options &gt; Text Editor &gt; General. It ignores both options under “Block Structure Guides” in C#, making them irrelevant. So, you can either have both types of indent guides or none, which is a bug.</p>

---
#### Joey Robichaud [MSFT] solved on 6/21/2021, 00:04 PM, 0 votes: 

<p>Hi William,</p>
<p>The settings you disabled control whether code constructs such as <code>if</code> blocks are collapsible in your code. You will need to disable the “Show structure guide lines” in <code>Tools &gt; Options &gt; Text Editor &gt; General</code> to disable the indent guides.</p>
<p><img src="https://aka.ms/dc/image?name=Bd070e584780e4f7e9fc9a4f0895babd4637598989673185767_20210621-120246-image.png&amp;tid=d070e584780e4f7e9fc9a4f0895babd4637598989673185767" alt="image.png"></p>

**Comment by JoeRobich** [comment]
This issue was resolved by https://github.com/dotnet/roslyn/pull/54079. It will be in Visual Studio 16.11 Preview 3.
