### ISSUE TITLE
Enable deterministic mode by default

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#5431]
The compiler should have determinism enabled by default.

This issue is filed so that I have an issue number to include in my TODO comments.

**Comment by gafter** [comment]
I suspect this is marked "Blocked" as we do not have a spec that allows us to put anything other than the build time in the assembly's timestamp field, and we are working separately on such a spec.

**Comment by TyOverby** [comment]
> JaredPar: 
> We’d like to have it one by default but it breaks compat with a number of tools.  Hoping to fix all those and make it on by default for new projects going forward sometime in Dev15.

**Comment by gafter** [comment]
Not sure why this is closed. We're still hoping to do this, no?

**Comment by TyOverby** [comment]
I don't know where the discussion went, but I remember having a conversation with Jared + others about why this wouldn't work.  

@jaredpar: do you remember what happened in that other thread?

**Comment by jaredpar** [comment]
@TyOverby a couple of issues that come to mind:

1. Determinism is incompatible with using `*` in assembly version strings.  The standard template for many project types generate such code hence determinism would likely cause compilation errors in a large number of projects. 
2. The use of a deterministic or 0 timestamp was shown to cause errors in other tools.  I think this is a temporal issue though, hopefully in time (a short one) this becomes a non-issue and we can change. 

Neither of these are deal breakers by any means.  I'm actually quite hopeful that we could switch the default for new projects to deterministic in Dev 15.  It would require some changes to our project templates though.  But that's a small issue.

**Comment by paul1956** [comment]
using * in assembly version Is an incredibly useful feature and is used in many customer projects, what is going to be the alternative? It seems to me a way to ignore that field or add some kind of checksum to assembly that causes the comparison of two runs to be the same even when assembly version changes is needed. I am not sure but I think OneClick deploy relies on assembly version for updates.

**Comment by gafter** [comment]
@paul1956 We're not going to stop supporting * in the assembly version - it will continue to change the version number. That feature and determinism are mutually exclusive.

**Comment by paul1956** [comment]
@gafter thanks that was not clear from some of the discussion.

**Comment by jaredpar** [comment]
There is currently not a reasonable path forward for this to happen.  Closing this out.  Can revisit if circumstances change in the future.

**Comment by ascott18** [comment]
This was already effectively implemented at the SDK level 6 months ago in https://github.com/dotnet/sdk/issues/1

**Comment by jaredpar** [comment]
@ascott18 indeed.  In large part because it's very difficult to do at the compiler layer.  SDK was a new arena and hence didn't have the compat concerns.  So we were able to do it by defalut there.
