### ISSUE TITLE
Verify accuracy of TupleElementNames tests for Implement Interface

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#54325]
Can someone from the @dotnet/roslyn-compiler team verify that we are testing Implement Interface with an accurate representation of `TupleElementNames` metadata?

https://github.com/dotnet/roslyn/blob/51c367a5c3b2e51026bd0dc459bbb9cba6e09d3b/src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs#L289-L316

💭 It seems like if we apply `TupleElementNames` manually, the test should be written with `ValueTuple<int, int>` syntax instead of `(int a, int b)` syntax.

🔗 Observed during review in https://github.com/dotnet/roslyn/pull/54310#discussion_r656661205

**Comment by Youssef1313** [comment]
@sharwell Is Area-Compilers intentional here? I interpret the issue as a problem in IDE test.

**Comment by sharwell** [comment]
Yes, this one is a verification request for the compiler team (to make sure we are testing the correct thing).

**Comment by jaredpar** [comment]
>  It seems like if we apply TupleElementNames manually, the test should be written with ValueTuple<int, int> syntax instead of (int a, int b) syntax.

I'm not sure what the ask is here. Both of these are cases that the compiler needs to understand (users can legally do both so we have to have a response to each of the scenarios). It depends on what the IDE intent is here and what scenario you are trying to exercise.

@jcouv

**Comment by CyrusNajmabadi** [comment]
I don't think there's any compiler info needed here.  This is also not a priority scenario for IDE if a user manually supplies these attributes.
