### ISSUE TITLE
ctor code snippet in a static class creates a non-static constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54322]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ctor-code-snippet-in-a-static-class-crea/1447223)._

---
A ctor code snippet in a static class creates a non-static constructor

```
namespace OsmCoreLib.Model
{
    internal static class Logging
    {
        public static object ProcessGridEntry { get; internal set; }

ctor // Press tab here

}
}
```
becomes

```
namespace OsmCoreLib.Model
{
    internal static class Logging
    {
        public static object ProcessGridEntry { get; internal set; }

public Logging()
        {

}

}
}
```

---
#### Feedback Bot on 6/11/2021, 03:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippet scenarios.
