### ISSUE TITLE
Implement interface produces incorrect code for manual use of DefaultParameterValue and Optional

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#54326]
Two Implement Interface tests reveal broken code when `DefaultParameterValue` and `Optional` are used:

https://github.com/dotnet/roslyn/blob/51c367a5c3b2e51026bd0dc459bbb9cba6e09d3b/src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs#L5111-L5171

> 🐛 this code generation is not correct. I'm guess the result we want is:
> 
> ```
>     public void Goo(int x = 1, int[,] y = null)
> ```

_Originally posted by @sharwell in [#54310 (comment)](https://github.com/dotnet/roslyn/pull/54310#discussion_r656664174)_

**Comment by CyrusNajmabadi** [comment]
Closing out as not a priority for us. Manual application of these attributes is a not an important scenario.
