### ISSUE TITLE
Implement interface abstractly should not apply to static members

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#54328]
Implementations of static abstract members in an interface cannot be abstract themselves. Implement Interface Abstractly should perform one of the following actions instead:

1. Omit `static abstract` members declared in the interface (they can be implemented by a subsequent "Implement remaining members" action).
2. Include implementations for `static abstract` members, but give them an implementation instead of marking them abstract.

**Comment by Youssef1313** [comment]
Doing that in #53941.
