### ISSUE TITLE
Support for getting values from dynamic with default in case value doesn't exist

### ISSUE THREAD

**Issue by carlos-sarmiento** [dotnet/roslyn#5433]
When working with dynamic objects in many languages, there is a construct that allows you to get the value of a property and if said property doesn't exist, return a default value.

It would be very useful to provide a similar method/syntax when working with dynamic in .NET to check if the a requested property exists and if it does not, return a default value. This would be particularly useful with the `?.` syntax to chain long searches in dynamic structures.

The syntax could be:

```
public class SomeClass
{
    public object ValidProperty { get; set; }
}

dynamic t = new SomeClass() { 
    ValidProperty = "someValue",
};

Console.WriteLine(t.Get("validProperty", "doesn't exist")); // Prints 'someValue'
Console.WriteLine(t.Get("invalidProperty", "doesn't exist")); // Prints 'doesn't exist'
```

The case of chaining these calls is interesting. This would be a very effective syntax for exploring object graphs in which properties might not exist at some arbitrary level.

```
var someResult = t.Get("ValidProperty", null)?.Get("InternalProperty", null) ?? "default";
```

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
