### ISSUE TITLE
"Pull Member Up" factors readonly members, causing initialization errors in the derived class

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#54343]
**Steps to Reproduce**:

Similar to #46010 in setup, but produces a different problem.

Create a new C# class library
Add two classes:

Base.cs

```csharp
using System;

class Base
{
}
```
Derived.cs

```csharp
using System;

class Derived : Base
{
    public Derived() =>  Endpoint = new Uri("http://localhost");
    public readonly Uri Endpoint; // also produces an error with: public Uri Endpoint { get; }
}
```
Click on the member declaration of `Endpoint` and use the quick actions menu to select "Pull 'Endpoint' up to 'Base'". 
**Expected Behavior**:
- (Most likely) Refactor shouldn't include readonly members if they are initialized elsewhere (i.e. constructor)
- (possibly) Refactoring a readonly member which is initialized in a constructor should refactor the base constructor to include the initialization as well
- (probably not) Refactoring a readonly member removes the readonly property (or equivalently adds `set;`)

**Actual Behavior**:
- When using readonly: Derived.cs doesn't compile with error "CS0191: A readonly field cannot be assigned to (except in a constructor or init-only setter of the type in which the field is defined or a variable initializer)"
-  When using `{ get; }`: Derived.cs doesn't compile with error "CS0200: Property or indexer 'Base.Endpoint` cannot be assigned to -- it is read only

**Comment by CyrusNajmabadi** [comment]
We can also support the refactoring, but put error annotations on all the locations there will be a problem, so the user can tell there is an issue in the preview window.

We've also considered some other way of making it more apparent that there might be a problem in the lightbulb, but nothing has come of that yet.

**Comment by jinujoseph** [comment]
@Cosifne

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
