### ISSUE TITLE
Move Roslyn gold bar notifications to the Output Window

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#54362]
For release builds we should move the gold bar notification to the output window to let the user know when they're in a degraded state.

**Comment by sharwell** [comment]
Recent integration test screenshots suggest that error states can be added here:

![image](https://user-images.githubusercontent.com/1408396/123298497-6999bf80-d4cd-11eb-81ed-bdb7efbc3f36.png)

I would be fine with relocating the error state to this pop-up provided we also silently roll features over from out-of-process execution to in-process execution (where they are more likely to work).

**Comment by mikadumont** [comment]
That is one option that the platform mentioned. I can look at telemetry to see how many people click on that to view what's going on - I'm assume its low.

**Comment by sharwell** [comment]
Output window would be the same way, but also less clear that an error exists.

**Comment by tmat** [comment]
>  silently roll features over from out-of-process execution to in-process execution 

We explicitly decided not to do that in past. I don't see why a feature would likely work in-proc if it fails oop.

**Comment by tmat** [comment]
Output window does not have the option to add more actions that the user can take. For example, in info-bar we could add a button that opens an existing VS Feedback ticket for the failure that might list some workarounds. I guess we could print that as a link to the output window, but seems odd.

**Comment by mikadumont** [comment]
I think we can add a link to these if we decide to use the same UX that loading uses for our errors:
![image](https://user-images.githubusercontent.com/46729679/123307208-12005180-d4d7-11eb-8cd5-050af32e094e.png)

**Comment by tmat** [comment]
I wouldn't be against moving it to that UI.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, this shoudl go to a dev/milestone to be done.
