### ISSUE TITLE
Redundant cast is not redundant!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54388]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Redundant-cast-is-not-redundant/1458757)._

---
Following code got refactored by removing redundant casts in the solution:
... = new((decimal)-1)
This class has 2 constructors. One for decimal and one for double. Without the explicit cast to one of both the compiler don't know which constructor to choose.

---
#### Feedback Bot on 6/24/2021, 00:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Related to https://github.com/dotnet/roslyn/issues/50043
Possibly dupe of https://github.com/dotnet/roslyn/issues/52524
