### ISSUE TITLE
Adding curly braces using Smart Break Line does not work for switch,case command.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54387]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-curly-braces-using-CtrlEnter-doe/1458665)._

---
Adding curly braces using <kbd>Shift</kbd>+<kbd>Enter</kbd> work well for `if`, `for`, `foreach` and other similar command but it does not work for `switch`, `case` command.

---
#### Aleš Grmela on 6/23/2021, 07:43 AM: 

<p>There is an error in my contribution.<br>
It is Shift+Enter to add curly braces instead of Ctrl+Enter.</p>

#### Feedback Bot on 6/23/2021, 07:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Aren't the braces mandatory for switch case? "Add braces" that you see in quick actions menu is a codefix for [IDE0011](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011), which is a code-style option to enforce braces (it's a suggestion/refactoring by default). `switch` is different, the braces are actually enforced by the "compiler" (syntax-wise). Am I missing anything?

cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I think they're talking about the 'smart enter' feature which can add braces for you :)

**Comment by sharwell** [comment]
📝 This _should_ insert braces for `switch`, but should just move to the next line without braces for `case`.

**Comment by Cosifne** [comment]
I think what the user means is SwitchExpression.
We have unit test covers the SwitchStatement case https://github.com/dotnet/roslyn/blob/b57c1f89c1483da8704cde7b535a20fd029748db/src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLineEnderTests.cs#L2687
