### ISSUE TITLE
Autocomplete of summary fails when cursor is placed in multiple spots.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54391]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Autocomplete-of-summary-fails-when-curso/1458984)._

---
[severity:It bothers me. A fix would be nice]
I place cursor at the end of multiple properties and press enter to get lots of new lines, everything is great. I then press /// to autogenerate the summary snippet and the snippet only completes at the first cursor location

example:

```csharp
    /// <summary>
    /// Temperature 
    /// </summary>
    public decimal TempSetPoint { get; set; }
    ///
    public decimal TempRampRate { get; set; }
    ///
    public decimal HumiditySetPoint { get; set; }
    ///
    public decimal HumidityRampRate { get; set; }
    ///
    public decimal JumpStep { get; set; }
    ///
    public decimal JumpCount { get; set; }
    ///
```

---
#### Feedback Bot on 6/24/2021, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I would be ok with supporting this, as long as the fix is reasonably simple.
