### ISSUE TITLE
Primary record constructor's declaring syntax reference should be the parameter list, not the record declaration node

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#54403]
**Version Used**: 
4.0.0-2.21322.49

**Steps to Reproduce**:

```C#
record C(int X);
```

```C#
var syntax = primaryConstructorSymbol.DeclaringSyntaxReferences.First().GetSyntax();
var symbol = semanticModel.GetDeclaredSymbol(syntax, cancellationToken);
```

**Expected Behavior**:

`syntax` is `ParameterListSyntax`
`symbol` is `primaryConstructorSymbol`

In general, I'd expect the above code to roundtrip for all symbols.

**Actual Behavior**:

`syntax` is `RecordDeclarationSyntax`
`symbol` is `INamedTypeSymbol` of the record

**Comment by tmat** [comment]
@AlekseyTs 

/cc @davidwengier

**Comment by CyrusNajmabadi** [comment]
I think we started there, but found it has undesirable impact on a few features (maybe things like highlight refs?  Not sure right now). You might want to try changing that and see what ide features break.

**Comment by tmat** [comment]
Why not fix those features though? The invariant above seems important. Given a `RecordDeclarationSyntax` I can't determine whether the origin was the record type symbol or its constructor.

**Comment by CyrusNajmabadi** [comment]
1. Primarily because these were all features that exist all language neutral layer. So no ability to go back to syntax. 
2. The same could apply to this specific feature :-)
3. We already had precedence I believe for shared declaring reference for symbol and type. Other constructors could already hit this. So it didn't feel strange here to continue down that line.

**Comment by tmat** [comment]
[1] I don't follow. You're saying "no ability" to go back to syntax, but DeclaringSyntaxReferences go back to syntax.
[2] Yes, I can wrap all usages of the API in EnC and fix it there. Not great though.
[3] What are other examples?

**Comment by CyrusNajmabadi** [comment]
As I mentioned, it's been a while. I cannot discuss this topic with confidence without knowing the details of the features that were affected by this. 

> What are other examples?

I believe things like other constructors (like the ones we generate), potentially things like accessors, or property value parameters, etc.

**Comment by CyrusNajmabadi** [comment]
Also, I may be misremembering Locations vs DeclaringSyntaxReferences. We'd have to investigate this to see if this only applies to one of these and not the other.

**Comment by tmat** [comment]
> I believe things like other constructors (like the ones we generate), potentially things like accessors, or property value parameters, etc.

AFAIK all of these are implicitly declared so they don't have any DeclaringSyntaxReferences .

**Comment by CyrusNajmabadi** [comment]
I could be mistaken, but I think they all have them :-)

**Comment by tmat** [comment]
I guess that's possible, I'll need to double check - I am mostly concerned about explicitly declared symbols.

**Comment by AlekseyTs** [comment]
The declaration node should encapsulate all bits of syntax that correspond to the symbol, parameter list simply doesn't meet this requirement. The closest parent node that does is the record declaration.
