### ISSUE TITLE
Switch Case Label containing an enum value fails Find All References

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54407]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Switch-Case-Label-containing-an-enum-val/1450728)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:VS2017 not sure the version number]
In a project that has an enum type used in various places, and there's a switch that uses that enum, if you highlight the enum value in that switch case, then right click, click "Find All References" does not find any of the references. This used to work in VS2017, but is not working in VS2019 16.10.0, very obnoxious.

Given that there's multiple uses of SomeEnum.THING throughout the project, if you highlight "THING" in the switch below and do a Find All References on it, it does not work. It incorrectly tries to find references for "case SomeEnum.THING:" and returns no results. It is impossible to search for the enum value's uses from that location without deleting text or leaving that file. I do not want to search for the case label unless I highlight the whole line.

switch(someEnumValue) {
case SomeEnum.THING:
     //...
     break;
}

---
#### Feedback Bot on 6/16/2021, 01:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Juliet Zhu [MSFT] on 6/16/2021, 02:05 AM: 

<p>Thanks for your feedback! We appreciate you taking the time to report this problem. We have reported a bug to our engineer and they will investigate this issue. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved. Thank you for helping us build a better Visual Studio!</p>

#### Christian Hornung on 6/23/2021, 02:57 AM: 

<p>I also find this annoying. I think this behavior has changed quite recently, probably with version 16.10.0.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
I think this was fixed in #53338 (fix will be in 16.11).

@jasonmalinowski Can you please confirm and close?

**Comment by jasonmalinowski** [comment]
Yep, that sounds exactly like what was fixed; thanks for tagging it.
