### ISSUE TITLE
CDATA code blocks are not rendered

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#54417]
**Version Used**: 16.10.2, 17.0.0-p1.1

CDATA is advertised by IntelliSense which is nice, but the IDE gives up if it is used:

```cs
/// <summary>
/// <code><![CDATA[
/// var list = new List<int>();
/// ]]></code>
/// </summary>
class C { }
```

![image](https://user-images.githubusercontent.com/8040367/123516089-61c25280-d668-11eb-991f-9f41cfa5ea4b.png)

Since CDATA isn't working, code blocks must be XML-escaped which is hard to maintain:

```cs
/// <summary>
/// <code>
/// var list = new List&lt;int>();
/// </code>
/// </summary>
class C { }
```

![image](https://user-images.githubusercontent.com/8040367/123516060-37709500-d668-11eb-9e7f-568d24e66485.png)

If you use `new List<int>()`:

![image](https://user-images.githubusercontent.com/8040367/123516068-435c5700-d668-11eb-83e4-aff71e3e5bb6.png)

**Comment by Youssef1313** [comment]
@jnm2 This was fixed in https://github.com/dotnet/roslyn/pull/53140 (16.11).

**Comment by jnm2** [comment]
Legend! Thank you!

Duplicate of #53135.
