### ISSUE TITLE
Valid XML doc elements are not shown in IntelliSense

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#54415]
**Version Used**: 16.10.2, 17.0.0-p1.1

Things I've noticed that are missing (there may be others):

- `<b>` and `<strong>`
- `<i>` and `<em>`
- `<u>`
- `<a>`
- `<br/>`
- `<tt>`

These are of general interest to anyone writing XML docs, but they are undiscoverable and missing from all the Microsoft docs pages too.

![image](https://user-images.githubusercontent.com/8040367/123515603-0db66e80-d666-11eb-8caf-174dee8f382b.png)

![image](https://user-images.githubusercontent.com/8040367/123515739-b06eed00-d666-11eb-8803-90621a52fd46.png)

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/37505.
