### ISSUE TITLE
Record structs: emit `readonly` modifier for synthesized members

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#54419]
**Version Used**: 

main branch 26.06.2021

**Steps to Reproduce**:

Compile the following code:
```c#
public record struct A(int P) {
  public readonly void ReadOnlyMethod() {
    ToString(); // CS8656
    PrintMembers(null); // CS8656
    Equals(this); // CS8656
    Deconstruct(out _); // CS8656
    GetHashCode(); // CS8656
  }
}
```

**Expected Behavior**:

No compiler warning produced.

**Actual Behavior**:

Warnings like:
> CS8656: Call to non-readonly member 'A.ToString()' from a 'readonly' member results in an implicit copy of 'this'.

**Comment by RikkiGibson** [comment]
We discussed this internally and decided we do want to make the change to make the synthesized record members `readonly` when possible. I drafted a spec change in dotnet/csharplang#4890.

**Comment by RikkiGibson** [comment]
tagging @Youssef1313 just in case you find this issue interesting.
