### ISSUE TITLE
cannot implicitly convert type bool (System.Runtime) to bool (mscorlib)

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#5442]
I have an empty .NET .4.5.2 project, using VS2013. Latest .NET 4.5.2 developer pack installed.
Installed `Microsoft.CodeAnalysis.Workspaces.Common` package.

The following code causes intellisense to break on `SupportsSyntaxTree`:

```
            var workspace = MSBuildWorkspace.Create(new Dictionary<string, string> { { "CheckForSystemRuntimeDependency", "true" } });
            var solution = await workspace.OpenSolutionAsync(path);

            foreach (ProjectId projectId in solution.ProjectIds)
            {
                var project = solution.GetProject(projectId);
                foreach (var documentId in project.DocumentIds)
                {
                    Document document = solution.GetDocument(documentId);
                    if (document.SupportsSyntaxTree)
                    {
                        //do stuff
                    }
                }
            }
```

<img width="1504" alt="screenshot 2015-09-25 12 07 18" src="https://cloud.githubusercontent.com/assets/1710369/10098223/ec5325e4-637f-11e5-9639-d6d0eae412a7.png">

Also `var` is not working for example `var projectId in solution.ProjectIds` causes `projectId` to be treated as `???` by intellisense.

The solution builds, but language services are all broken.

**Comment by filipw** [comment]
BTW, .NET 4.6 is also installed on that machine, and switching the project to .NET 4.6 makes all the problems go away

**Comment by Pilchie** [comment]
This is a known issue in VS2013 with desktop projects referencing PCL projects.  The facade assemblies are automatically added to compilation, but not to the IDE.

This is fixed in VS2015.

**Comment by filipw** [comment]
so you are saying that it's not possible to have a desktop project referencing Roslyn packages (cause that means PCLs) and targeting < .NET 4.6 in VS2013? That sounds like a pretty big deal

**Comment by Pilchie** [comment]
There is an msbuild property that can be set to force the expansion.  Note that this doesn't just affect use of Roslyn though, it affects *all* PCLs in VS2013.  You can often get away with it because the IDE in VS2013 wasn't as good at reporting errors, but it's definitely annoying.

Try adding `<_HasReferenceToSystemRuntime>true</_HasReferenceToSystemRuntime>` to the project that referencing a PCL and see if that fixes it.

**Comment by Pilchie** [comment]
@filipw Is this still an issue?  Did the workaround work for VS2013?

**Comment by filipw** [comment]
ah sorry, my bad for not updating the issue - indeed the workaround solved it
