### ISSUE TITLE
using static and instance method ambiguity

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5443]
In the code below, while the IntelliSence shows the `BitConverter.ToString` method and `Object.ToString` is not even a static method and also they accept different parameters, compiler produces the following error, which doesn't make sense.
```C#
using static System.BitConverter;
class Program {
    static void Main(string[] args) {
        ToString(new byte[0]);  // CS1501
    }
}
```
Even if there was a static member method with the same name in the scope, I would suggest the `::` operator to disambiguate it. 
```C#
using static System.Console;
class Program {
    static void WriteLine(string input) => ::WriteLine($"--{input}"); // Console.WriteLine
    static void Main(string[] args) => WriteLine("Log"); // Program.WriteLine
}
```

**Comment by svick** [comment]
I think case 1 of #250 would solve the ambiguity.

**Comment by gafter** [comment]
Indeed, this is an example of #250.
