### ISSUE TITLE
[Responsiveness] ChecksumCollection.FindAsync excessively allocates during solution open (1.8%/765 MB during solution open)

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#54436]
**Version Used**: 
Version: 17.0.0 Preview 2.0 [31422.448.main]

[Trace](https://microsoft.sharepoint.com/teams/VSIDEPerformance/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FVSIDEPerformance%2FShared%20Documents%2FGeneral%2FTraces%2F17%2E0%2E0%20Preview%202%2E0%20%5B31422%2E448%2Emain%5D%2FSolution%5F006%5F0936%5FGeneral%5Fnocache&p=true&originalPath=aHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC5jb20vOmY6L3QvVlNJREVQZXJmb3JtYW5jZS9Fa0MyekJXblE0RkZvYUJSdGp5WmRIVUJGTXhzNzU4bnRYRDd1NHhhZDBhaDRnP3J0aW1lPWtuck1wX0E1MlVn) (936 projects Orchard Core hybrid)

Can we unroll LINQ and see if we can avoid boxing the enumerators?

**Callees:**
![image](https://user-images.githubusercontent.com/1103906/123582234-d2ac6a80-d820-11eb-988b-3311ba85a0a5.png)

**Callers:**
![image](https://user-images.githubusercontent.com/1103906/123582375-08515380-d821-11eb-95a9-8528c08c70f2.png)

**Comment by sharwell** [comment]
Already fixed by https://github.com/dotnet/roslyn/pull/53959

**Comment by davkean** [comment]
@sharwell This is based on 17.0.0 Preview 2.0 [31422.448.main], what build will this get into?

**Comment by sharwell** [comment]
I'm not sure what 31422.448.main is, but if you have a commit hash from Help&rarr;About I can verify that the fix was not yet included for the test.

**Comment by davkean** [comment]
I only have a trace unfortunately.
