### ISSUE TITLE
EnC - More attribute edit tests

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#54430]
Looks like I missed tests for some things, so need to add some (and fix anything if they fail, obv)

* Need syntax editing tests for:
	* Events: https://github.com/dotnet/roslyn/pull/54787
* Need emit tests for:
	* Events: https://github.com/dotnet/roslyn/pull/54787
	* Method parameters: https://github.com/dotnet/roslyn/pull/54835
	* Method return types: https://github.com/dotnet/roslyn/pull/55099
	* Delegates: https://github.com/dotnet/roslyn/pull/55881
	* Delegate parameters: https://github.com/dotnet/roslyn/pull/55099
	* Delegate return types: https://github.com/dotnet/roslyn/pull/55099
	* Properties: https://github.com/dotnet/roslyn/pull/55881
	* Fields: https://github.com/dotnet/roslyn/pull/55881
	* Types: https://github.com/dotnet/roslyn/pull/55881
	* Generic Types: N/A, not supported
	* Enum members: https://github.com/dotnet/roslyn/pull/55881

**Comment by tmat** [comment]
We should have tests for attribute updates on all kinds of symbols. Our tests are grouped by symbol kind and each test group should test modifier and attribute edits.
