### ISSUE TITLE
C# XML Doc Auto-completion Breaks For Enum Members

### ISSUE THREAD

**Issue by ericmutta** [dotnet/roslyn#54448]
**Version Used**: 

Visual Studio 2019 Community v16.10.0

**Steps to Reproduce**:

Start with an enum type like this:

```csharp
  public enum ETypeCode: byte
  {
     Byte
    ,UInt16
  }
```

**Note how the comma separating the `Byte` member from the `UInt16` member is actually placed _before_ the `UInt16` member rather than _after_ the `Byte` member.**

Now if you type `///` in a line above the `Byte` member, auto-complete kicks in and you get a `<summary>` tag as expected:

![image](https://user-images.githubusercontent.com/20465797/123692964-21c5c000-d860-11eb-8ed0-00184ba18734.png)

But if you try to add documentation to the `UInt16` member which has a comma before it, **auto-complete gets thrown off and does nothing**: you type `///` and that's all you get (no `<summary>` tag is automatically inserted):

![image](https://user-images.githubusercontent.com/20465797/123693419-b16b6e80-d860-11eb-89c2-53dd1344b6b3.png)

I can confirm that the comma is to blame because when you move it so that it appears _after_ the `Byte` enum member, auto-complete works again everywhere:

![image](https://user-images.githubusercontent.com/20465797/123693906-5128fc80-d861-11eb-972d-c3e505d8d942.png)

**Expected Behavior**:

XML doc auto-completion should work regardless of comma placement between enum members (sometimes its useful to place the comma before an enum member so you can easily comment it out and the C# syntax happily permits this style).

**Actual Behavior**:

XML doc auto-completion only works for enum members that have a comma after them (as shown above in the repro steps).

**Comment by Youssef1313** [comment]
I think the current IDE behavior is correct. Documentation comments must be placed on a valid language element (i.e, the enum member).
Placing it before the comma is not valid from the language perspective (I believe the compiler should produce a warning for it if you have `<GenerateDocumentationFile>true</GenerateDocumentationFile>`

**Comment by CyrusNajmabadi** [comment]
@Youssef1313  Is correct.  The IDE is operating here as expected per the language.  The comments would not be in a valid location if the comma came after them, and the compiler would reject thsi.

We woudl only support this in the IDE *if* the language gets an update that makes the above forms legal.  That would first have to go through dotnet/csharplang first though as an accepted and implemented proposal.  Thanks!

**Comment by ericmutta** [comment]
@Youssef1313 @CyrusNajmabadi many thanks for following up and for the clarification about how the compiler "sees" the comma (vs how I was parsing it in my head) :+1:
