### ISSUE TITLE
Why can't see the generated .cs file in 'Analyzers'?

### ISSUE THREAD

**Issue by Li7ye** [dotnet/roslyn#54460]
**Version Used**: 
3.80
**Steps to Reproduce**:

I try to generate this file as below:

![image](https://user-images.githubusercontent.com/42088918/123779557-e16c4d80-d904-11eb-8bb7-3e79b2ae823c.png)

But I can't see this file in 'MyCodeGenerator':

![image](https://user-images.githubusercontent.com/42088918/123779781-1d9fae00-d905-11eb-8ba5-6491db4d8e64.png)

However, I can find out 'SpeakerHelper' in assembly:

![image](https://user-images.githubusercontent.com/42088918/123780033-593a7800-d905-11eb-8198-b7637fd8a523.png)

**Comment by huoyaoyuan** [comment]
Restart IDE may helps. Currently code generator works perfectly after building and restarting IDE.

**Comment by Li7ye** [comment]
@huoyaoyuan ,After restarting IDE it can work, thanks.
