### ISSUE TITLE
Improve condition logic with conditional access expression

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#54467]
If the expression is myDictionnary.TryGetValue(key, out T value) == true ? value : value2, compilation succeeds. 
However, if I use myDictionnary?.TryGetValue(key, out T value) == true ? value : value2, compilation fails with the following error:
CS0165 Use of unassigned local variable 'value'.
I believe the logic here could be improved, supporting conditional access expression, to avoid this error.

**Comment by Youssef1313** [comment]
I believe this is already implemented for C# 10. Proposal: https://github.com/dotnet/csharplang/issues/4465

**Comment by RikkiGibson** [comment]
Thanks for filing the issue. This was fixed by #54004. Shipping in dev17 preview 2.
