### ISSUE TITLE
Investigate C# formatting implications of new #line pragmas

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#54469]
In C# 10 we're working on [Improved #line pragmas](https://github.com/dotnet/csharplang/issues/4747). Pre-existing line pragmas influence tooling in many different facets. One of which we've noticed in generated files is at format time what happens?

With the enhanced line pragmas being created we may need to update our C# formatting engine to better understand the new form of line pragmas to ensure things don't break down.

**Comment by jcouv** [comment]
Linking to test plan for new `#line` feature: https://github.com/dotnet/roslyn/issues/54509

**Comment by jcouv** [comment]
Chatted with Taylor to confirm expectations for this issue.
Some background: Two editors (one is projection-based if flag pictured below is disabled, one is new editor in dev17.0p2). New code generation (using new `#line` directives) will be worked on by Safia in dev17.0p3.

Will coordinate with Safia to do some validation and route any issues we find then (depending on whether compiler, IDE or Razor problem) then.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12466233/125120387-3f3c2a80-e0a7-11eb-8215-27f26a782d8d.png)

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Can we close this issue now?

Yup!
