### ISSUE TITLE
EditorConfig UI doesn't reflect the correct current setting

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54495]
**Version Used**: 

16.10.2

**Steps to Reproduce**:

```ini
# Default severity for analyzer diagnostics with category 'Style'
dotnet_analyzer_diagnostic.category-Style.severity = warning
```

**Expected Behavior**:

Most code-styles are shown with "warning" severity

**Actual Behavior**:

Nothing in code-style tab shows as warning.

**Comment by Youssef1313** [comment]
cc @jmarolf

**Comment by Youssef1313** [comment]
Overlaps with https://github.com/dotnet/roslyn/issues/52388.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/56124

**Comment by Youssef1313** [comment]
@jmarolf Can you please elaborate more on how #56124 is related? #56124 has fixed issues where the UI doesn't show at all.
