### ISSUE TITLE
IDE Feature Request: Local functions in Go-To-All

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#54519]
**Brief description:**

When I to Go-To-All (particularly in a single file) I'd like to see local function symbols there as well. I'll often see a comment I need to address in a code review and want to go to that exact function, but have to then find the outer function because the local function symbol doesn't appear.

**Languages applicable:**

C#

**Comment by CyrusNajmabadi** [comment]
I'm not certain why local functions would be different from locals here.  Both/eitehr seem reasonable here.

**Comment by sharwell** [comment]
Duplicate of #39083

**Comment by 333fred** [comment]
Thanks Sam. My search-fu wasn't up to snuff.

> I'm not certain why local functions would be different from locals here. Both/eitehr seem reasonable here.

Locals _might_ make it a bit too cluttered, but that's definitely something we can experiment with.
