### ISSUE TITLE
.editorconfig directive dotnet_sort_system_directives_first = false is not respected

### ISSUE THREAD

**Issue by claudia-ca** [dotnet/roslyn#54513]
Version Used: VS Professional 2019, Version 16.10.3

Steps to Reproduce:

1. Create sln with 2 projects (i.e. EditorConfigTester and TestLibrary)
2. Add TestLibrary as a reference to EditorConfigTester and add something to a class in EditorConfigTester from TestLibrary so its namespace is needed 
3. Move the TestLibrary directive to the top of the file, above the default System directives
4. Also use something from System, so one of these directives remains after cleanup too

Example:
```
using TestLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EditorConfigTest
{
    public class Main
    {
        private TestClass _testClass = new TestClass();

        public void Method( string parameter )
        {
            var content = parameter.Select( c => c );
        }
    }
}
```
5. Add .editorconfig file with the following content:
```
# Remove the line below if you want to inherit .editorconfig settings from higher directories
root = true

# C# files
[*.cs]

# Organize usings
dotnet_sort_system_directives_first = false
dotnet_separate_import_directive_groups = true
```
6. Run code cleanup ( Ctrl+K,Ctrl+E)

Expected Behavior:
Separate groups are created, but System directives NOT moved to top

Actual Behavior:
Separate groups are created, but System directives ARE moved to top

Note: 
- Even when 'dotnet_separate_import_directive_groups' is left out and no groups are created, the System directives are being placed on top.
- Might be since 16.8.0: when creating new classes from templates, the directives now are also always sorted this way even though we don't want this
- Related settings in Tools>Options>Text Editor > C# > Advanced > "Using Directives" are also turned off (i.e. "place system directives first when sorting usings" and "separate using directive groups")

**Comment by Youssef1313** [comment]
I think the way `dotnet_sort_system_directives_first` works is:

- If true, all `System` using are sorted first, followed by other `usings`.
- If false, this doesn't mean to keep `System` last. It just orders alphabetically. So `System` will still come before `TestProject`. If the namespace was `ATestProject` instead of `TestProject`, then the expected behavior here is `ATestProject` is kept at the top.

**Comment by claudia-ca** [comment]
Ahh, you're right..can we disable the alphabetical sorting through the editorconfig?

**Comment by sharwell** [comment]
> Ahh, you're right..can we disable the alphabetical sorting through the editorconfig?

No, but if you are running code cleanup you can remove Sort Using Directives from the list of items cleaned up in the profile.
