### ISSUE TITLE
Editor config not honoured in latest version

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54524]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Editor-config-not-honoured-in-latest-ver/1464659)._

---
[severity:I'm unable to use this version] [regression] [worked-in:not sure]
Upgraded VS to Version 16.10.3 and my editor config is no longer honored.
! [image.png] (https://aka.ms/dc/image?name=B24ef4dfa86a347d9af658f6734f2be22637606497141669317_20210630-143513-image.png&tid=24ef4dfa86a347d9af658f6734f2be22637606497141669317)
! [image.png] (https://aka.ms/dc/image?name=B02572c25f759456ca1f07a8c564663a4637606497499142027_20210630-143550-image.png&tid=02572c25f759456ca1f07a8c564663a4637606497499142027)
! [image.png] (https://aka.ms/dc/image?name=B863d0382729041b3aa6f3756ea6e2d42637606497730703272_20210630-143613-image.png&tid=863d0382729041b3aa6f3756ea6e2d42637606497730703272)

---
#### Feedback Bot on 6/30/2021, 08:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/1/2021, 07:50 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is a known editor bug. Moving to the correct team and closing here.
