### ISSUE TITLE
Formatting of C# code uses 2 spaces even when settings has 4 spaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54529]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Formatting-of-C-code-uses-2-spaces-even/1445013)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.9]
I have this setting for C#, where tabs should create 8 spaces:

! [image.png] (https://aka.ms/dc/image?name=Ba10f966fb9ff47d98eb9844d8b8cc3fd637587993146747634_20210609-093458-image.png&tid=a10f966fb9ff47d98eb9844d8b8cc3fd637587993146747634)

But when I press tab key in the editor, it creates 2 spaces only instead of 8 spaces, as this picture shows:

! [image.png] (https://aka.ms/dc/image?name=B7dcd10fa3ff04694ab2f0da067d0ecd8637587994509264584_20210609-093728-image.png&tid=7dcd10fa3ff04694ab2f0da067d0ecd8637587994509264584)

---
#### Feedback Bot on 6/8/2021, 08:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/9/2021, 09:53 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Need a repro for this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response/repro.
