### ISSUE TITLE
.editorconfig regressions in Visual Studio v16.10

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54526]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/editorconfig-regressions-in-Visual-Stud/1450548)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.9.x]
1. Configure severity for analyzers from editor context menu doesn't work.

2. No convenient facility to view .editorconfig in plain text (.csproj files are opened in text mode by default, GUI editor is opened only when Properties is selected in Solution Explorer context menu).

3. New GUI editor edits .editorconfig with formatting which differs from "Configure severity for analyzers" item (when it work).

4. No ability to select "none" severity for analyzers rules in GUI editor.

---
#### Feedback Bot on 6/16/2021, 01:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Maxim Marinchenko on 6/16/2021, 01:44 AM: 

<p>I can see that some of these issues are already covered on GitHub.</p>
<p>1 may be related to 7 at <a target='_blank' href="https://github.com/dotnet/roslyn/issues/53171">https://github.com/dotnet/roslyn/issues/53171</a></p>
<p>2 is covered at <a target='_blank' href="https://github.com/dotnet/roslyn/issues/53120">https://github.com/dotnet/roslyn/issues/53120</a></p>
<p>3 covered at <a target='_blank' href="https://github.com/dotnet/roslyn/issues/52720">https://github.com/dotnet/roslyn/issues/52720</a> and <a target='_blank' href="https://github.com/dotnet/roslyn/issues/53833">https://github.com/dotnet/roslyn/issues/53833</a></p>
<p>I didn’t find any github issue for point 4.</p>

#### Feedback Bot on 6/16/2021, 09:58 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
these are all being tracked in separate issues

**Comment by majorregal** [comment]
Is this a joke? The github issue says it's continued in the Developer Community ticket and the ticket refers back to this issue.
