### ISSUE TITLE
Automatic namespace import aborts snippet functionality

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54528]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Automatic-namespace-import-aborts-snippe/1207642)._

---
[severity:It bothers me. A fix would be nice]
**VS Version**
Microsoft Visual Studio Professional 2019
Version 16.7.3

**Short description**
Visual Studio recently started automatically adding using statements when autocompleting types outside of the current using list. However, if this process triggers when you are trying  to apply a snippet, the namespace import cancels the snippet-mode in the editor. Leaving your snippet half way applied.

**Steps to reproduce**
Given the following code sample:

```
using System;

namespace Test
{
    public class Class1
    {
        
}
}
```
Try to apply the C# standard `propfull` snippet. At the `type` position use intellisense to autocomplete `StringBuilder`. When you press `TAB` to go to the field name of the snippet the `System.Text`  namespace is added to the using list. This cancels the snippet and leaves the editor in the following state:

```
using System;
using System.Text;

namespace Test
{
    public class Class1
    {
        private StringBuilder myVar;

public int MyProperty
        {
            get { return myVar; }
            set { myVar = value; }
        }
    }
}
```
Notice how the namespace is added, the `private` field got the correct type however the `public` property did not. Furthermore, snippet-mode is cancels and leaves the cursor at the `myVar` position, unable to continue the snippet.

**Expected result**
1. The snippet should change the type of the `public` property as well.
2. Snippet mode should not be cancelled, allowing for automatic rename of the `private` field and `public` property after autocompleting the type.

---
#### Feedback Bot on 10/2/2020, 06:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/2/2020, 09:43 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/19/2021, 00:07 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippet experiences.
