### ISSUE TITLE
Typo in .editorconfig screen

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54533]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Typo-in-editorconfig-screen/1440773)._

---
[severity:It bothers me. A fix would be nice]
When editing an .editorconfig file, I found this drop-down:

! [image.png] (https://aka.ms/dc/image?name=Bfc69a54423db4cd6b943f0b89e693fae637583338358385062_20210603-191713-image.png&tid=fc69a54423db4cd6b943f0b89e693fae637583338358385062)

While English is not my first language, I am pretty sure that word should be spelled Carriage. Google seems to agree with me :)

This is, of course, a very low priority issue; it's just that typos bug me something fierce.

---
#### Feedback Bot on 6/3/2021, 07:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/4/2021, 09:41 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This was already fixed in https://github.com/dotnet/roslyn/pull/53327
