### ISSUE TITLE
[Question] View from metadata

### ISSUE THREAD

**Issue by jcs090218** [dotnet/roslyn#54543]
Not sure if this is the right place to ask.

In VS2019, when you hit f12 then you get to see a well nicely displayed window like the screenshot below.

![Image 2](https://user-images.githubusercontent.com/8685505/124165238-20043280-dad4-11eb-8619-d5d9f3b77cc6.png)

I am trying to port this feature to other editor (Emacs). Is there a way so I could get this nicely displayed content by calling some sort of commands through terminal? Or other way that I can get the information I need to recreate similar content? 

Any help would be appreciated! I miss this feature from other editors!😭

**Comment by CyrusNajmabadi** [comment]
The code for this is here: https://github.com/dotnet/roslyn/tree/main/src/Features/Core/Portable/MetadataAsSource
