### ISSUE TITLE
[LSP] Semantic tokens: Document null when first opening a Razor file

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#54547]
When a Razor file is opened, Roslyn at first is unable to find the Razor document, i.e. `context.Document` is null. However, the problem eventually resolves itself after a period of time. We should determine the core issue and implement a long-term solution.

**Comment by allisonchou** [comment]
@dibarbet have you seen this one recently? I haven't seen it in a while so I'm wondering if it might be resolved now.

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of movement here.  IF this is an issue, please assign to dev/milestone to fix.  If this is razor, please move to them.
