### ISSUE TITLE
EditorConfig UI shows localized analyzer rule titles in english VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54557]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EditorConfig-UI-shows-localized-analyzer/1446606)._

---
[severity:It's more difficult to complete my work]
The new EditorConfig UI that was added in Visual Studio version 16.10 shows some analyzer rule titles in a localized language (German for me - maybe because my Windows is in German), although my Visual Studio is in English (and no other language pack is installed for VS).

It seems like only analyzer rules are affected. Formatting and code style rules are all in english.
Also, it seems like only CAxxxx analyzer rules are affected. Other analyzer rule titles are in english.

---
#### Feedback Bot on 6/10/2021, 01:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 6/10/2021, 10:58 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
@jmarolf

**Comment by BhaaLseN** [comment]
Related: #53834
