### ISSUE TITLE
ErrorLogger need to be a public API

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#5456]
http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/ErrorLogger.cs,f724fbca034fb970

With SARIF being the standard format for issues, I think having a ErrorLogger which knows how to translate to that format will be quite handy.

**Comment by jinujoseph** [comment]
While we are fixing that can we add an API to take a collection of diagnostics..
ErrorLogger.LogDiagnostic ( ImmutableArray<Diagnostic> ...

**Comment by CyrusNajmabadi** [comment]
@mavasani can this be closed out?

**Comment by mavasani** [comment]
Yes, there is no known scenario for this API to be public
