### ISSUE TITLE
collapsed xml comments should it render tag vs.net 2019?

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/roslyn#54587]
**Version Used**: 
Visual 2019 16.10 and 
Visual Studio 2019 Version 16.11.0 Preview 2.0

**Steps to Reproduce**:

1. Create a console application (.net 5.0)
2. Go to `program.cs` on top of `class Main` add `///`
3. The summary is generated add some text then collapse it

**Expected Behavior**:
I thought there shouldn't be the `/// <summary` tag in the collapsed text region, similar to how the `#region` currently works
Perhaps there could be a different way to indicate xml docs vs regions vs normal comments when collapsed?

**Actual Behavior**:
It is showing the `/// <summary>` tag 
![image](https://user-images.githubusercontent.com/296247/124346112-65ce1180-dc20-11eb-8ec5-699f477b3c2c.png)

Furthermore when I hover over the collapsed text I see the tags being rendered
![image](https://user-images.githubusercontent.com/296247/124346143-9615b000-dc20-11eb-83f5-24347fccd7ad.png)

I'm not sure what could be causing this, if it's a setting or an extension. I did try `devenv /safemode` and had the same experience

**Comment by CyrusNajmabadi** [comment]
Both of these have been our behavior for roughly 20 years.  In collapsed view we effectively linearize the content so you can see what's going on, like so:

![image](https://user-images.githubusercontent.com/4564579/124361916-a9a42500-dbe6-11eb-902b-ddf3bd294e77.png)

And when you hover, all we're doing is showing you the contents of the folded section (which of course includes the slashes.

Both of these are currently operating as expected, and we'd need a strong reason to change this IMO given the history here.

**Comment by dotnetshadow** [comment]
cheers thanks for clearing it up, I must of been confused with another product 👍
