### ISSUE TITLE
Please consider making scripts semantically identical to simple programs

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#54598]
Currently, scripts is a hard special case all over the compiler codebase, for instance, we create fields instead of locals for pattern variables. I'd expect a great simplification in the implementation if we unify the two, unless spec explicitly requires this of course.

**Comment by jaredpar** [comment]
This was discussed at length a few years back and we dedicated a couple of LDM meetings to the subject. Unfortunately the conclusion was that we couldn't really reconcile the two different dialects at this point without massive breaking changes (likely to scripting). As such we decided to move forward with the top level statements feature and leave scripting as it is.

**Comment by tmat** [comment]
It's not just breaking changes though - the differences are essential for REPL. E.g. top-level script variables must be emitted as fields in order to be accessible from the subsequence submissions.

**Comment by alrz** [comment]
@tmat 

>top-level script variables must be emitted as fields in order to be accessible from subsequent submissions.

Does the Immediate Window works the same way? If not, how this is different?

**Comment by tmat** [comment]
It does not work in the same way. Immediate Window uses debugger to interpret the generated IL. The debugger can inspect memory of the process it is attached to. Even so the semantics are not quite the same. Also, not all IL can be interpreted.
