### ISSUE TITLE
Format on Paste inserts two blank lines for every line of /// doc comments when newlines are only \r

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#546]
Ported from TFS WorkItem: **829954**

---

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR>

**Note**: Yes, this sounds obscure, but this happens if you copy/paste code with doc comments through OneNote.

<BR>**Steps to reproduce:**<BR><BR>1. Save the attached file to your local machine.
1. Create a new C# project and add that file to it.
2. Open the file. You'll see something like this, but copy/pasting from here won't reproduce the issue - use the file:

&nbsp;
public class B<BR>{<BR>&nbsp;&nbsp;&nbsp; /// &lt;param name="x"&gt;&lt;/param&gt;<BR>&nbsp;&nbsp;&nbsp; /// &lt;param name="y"&gt;&lt;/param&gt;<BR>&nbsp;&nbsp;&nbsp; public virtual int M(int x, string y)<BR>&nbsp;&nbsp;&nbsp; {<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return 1;<BR>&nbsp;&nbsp;&nbsp; }<BR>}

&nbsp;
1. Copy the contents of the file and paste it back into the editor.

&nbsp;

**Expected**: You see the same code that you copied pasted back in.

**Actual**: A bunch of blank lines are inserted before doc comments.

&nbsp;

public class B<BR>{

&nbsp;

&nbsp;

&nbsp;

<BR>&nbsp;&nbsp;&nbsp; /// &lt;param name="x"&gt;&lt;/param&gt;<BR>&nbsp;&nbsp;&nbsp; /// &lt;param name="y"&gt;&lt;/param&gt;<BR>&nbsp;&nbsp;&nbsp; public virtual int M(int x, string y)<BR>&nbsp;&nbsp;&nbsp; {<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return 1;<BR>&nbsp;&nbsp;&nbsp; }<BR>}

---

**Revisions:**

1) Created By David Poeschl (11/21/2013 7:55:36 PM)

---

**Comment by alexsorokoletov** [comment]
> would be somewhere in Workspaces\CSharpWorkspaces\Formatting\Rules
@Pilchie

**Comment by CyrusNajmabadi** [comment]
Have not heard about thsi being an issue for anyone else in  8 years.  Feels like we can close out.
