### ISSUE TITLE
Code fixes for IL-class errors (.NET publish trimming errors) are applied multiple times

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn#54602]
**Version Used**: 

Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 1.1
.NET SDK 6.0.100-preview.5.21302.13

**Steps to Reproduce**:

1. Write some C# code that uses reflection and generates trimming-related warnings such as IL2026.
2. Attempt to apply the code fixes, either ones that suppress the message or the ones that applies `RequiresUnreferencedCodeAttribute`

**Expected Behavior**:

Exactly one new attribute is attached to my method by the code-fix, as displayed by the preview:

![image](https://user-images.githubusercontent.com/426009/124385477-32bb7900-dd19-11eb-8988-7530f463db34.png)

**Actual Behavior**:

Multiple new attributes (as many as four) get attached to my method:

![image](https://user-images.githubusercontent.com/426009/124385496-41a22b80-dd19-11eb-9da8-ae7bcd69d5bf.png)

**Comment by sharwell** [comment]
@agocke do you know who owns this code fix? It needs to be updated to use a custom `FixAllProvider`.

**Comment by Youssef1313** [comment]
PR implemented the codefix: https://github.com/mono/linker/pull/2015

**Comment by agocke** [comment]
@sharwell I'm kinda confused about this code. I looked into the FixAll provider and it looks like it's supposed to merge identical changes. Moreover, I can't seem to replicate this behavior in unit tests. Any ideas about how I should replicate this problem using the Roslyn SDK?
