### ISSUE TITLE
Instance reference and static constructor highlighted at the same time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54637]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Instance-reference-and-static-constructo/1467924)._

---
Highlighting &quot;this&quot; in class also highlights static constructor, don't think that makes sense

---
#### Feedback Bot on 7/5/2021, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
