### ISSUE TITLE
Creating compilations for projects with 'ReferenceOutputAssembly' fails

### ISSUE THREAD

**Issue by steffenloesch** [dotnet/roslyn#5464]
I'm trying to open a MsBuild project

``` c#
var msWorkspace = MSBuildWorkspace.Create();
var project = msWorkspace.OpenProjectAsync(@"C:\MyProject\MyProject.csproj").Result;
var compilation = project.GetCompilationAsync().Result;
```

where the csproj file has a reference like this:

``` xml
<ProjectReference Include="..\MyOtherProject\MyOtherProject.csproj">
      <Project>{AE7D5046-6A7E-4782-B3F2-71386E2818E0}</Project>
      <Name>MyOtherProject</Name>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
</ProjectReference>
```

When I do that, GetCompilationAsync throws the following exception

```
Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation.
Parameter name: references[0]
```

If I remove the ReferenceOutputAssembly line, everything works fine.

**Comment by mattwar** [comment]
I cannot repro this using current Roslyn or 1.0 bits.  

Possibly there is something else going on?

**Comment by steffenloesch** [comment]
Yes there might be something else going on, as the project that I'm trying to open is part of a fairly complex solution (not open source unfortunately). The problem is certainly references like the one above, because if I comment out "<ReferenceOutputAssembly>false</ReferenceOutputAssembly>", the project opens. However, I tried to find a minimal repro with a toy project, and failed so far. Are there any know issues in Roslyn 1.0 that result in the exception above, and that can be avoided by not using  "<ReferenceOutputAssembly>false</ReferenceOutputAssembly>"?

**Comment by mattwar** [comment]
The error message occurs because we use the compiler command-line API to translate metadata reference file paths to actual MetadataReference instances.  The command-line API creates UnresolvedMetadataReference's for file paths that don't point to anything on disk.  The exception occurs when we later try to create a compilation using one of these special kinds of references.  

It is possible to have MSBuildWorkspace ignore these unresolved references and not cause the exception.  However, it is unclear how/why the references are getting to this code in the first place.

**Comment by steffenloesch** [comment]
Thanks for the explanation! How can I enable the 'ignore unresolved references' option for MSBuildWorkspace?

**Comment by DustinCampbell** [comment]
@mattwar -- just wanted to ping about the last question @steffenloesch had:

> How can I enable the 'ignore unresolved references' option for MSBuildWorkspace?

**Comment by mattwar** [comment]
I didn't mean there was a feature to cause the workspace to ignore these, I meant it was possible to change the workspace to ignore them; possibly have it log a diagnostic when it happens.
