### ISSUE TITLE
Optimize [0..pos] lowering

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#54659]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/f32db1d1dc8bb41581582491e1f121c5ba2b8fca

**Steps to Reproduce**:
```C#
using System;
public class C {
    public Span<char> M1(Span<Char> s, int pos) => s[0..pos];
    public Span<char> M2(Span<Char> s, int pos) => s.Slice(0, pos);
}
```

**Expected Behavior**:
Identical IL produced for M1 and M2.

**Actual Behavior**:
The compiler emits more complicated code to precompute `pos - 0`, even though that's just `pos`, and in doing so to preserve order of evaluation saves things off into additional locals.
```C#
public class C
{
    public Span<char> M1(Span<char> s, int pos)
    {
        Span<char> span = s;
        int num = 0;
        int length = pos - num;
        return span.Slice(num, length);
    }

    public Span<char> M2(Span<char> s, int pos)
    {
        return s.Slice(0, pos);
    }
}
```

`[0..something]` is very common as part of parsing, e.g. find a separator in a span and then take the slice of everything up until that separator.  It'd be nice if `[0..pos]` syntax could be used without a tax.

And even if we didn't want to special case `0`, surely we could special-case `[..pos]` where no lower bound is provided and the compiler infers `0`, but even then we get a subtraction:
```C#
    public Span<char> M1(Span<char> s, int pos)
    {
        Span<char> span = s;
        int length = pos - 0;
        return span.Slice(0, length);
    }
```

(Note the JIT today gets close to unwinding them to both be the same asm, but not quite.)

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/43598

**Comment by stephentoub** [comment]
Heh, I forgot I opened that.   At least I'm consistent :)

**Comment by RikkiGibson** [comment]
I think I get what the problem is, but I found the issue description a little confusing because the identifier `pos` is used in the "steps to reproduce" when maybe the identifier `end` was meant to be used.

**Comment by stephentoub** [comment]
Fixed the copy/paste error

**Comment by jaredpar** [comment]
Let's use #43598 as the primary issue here as these are very related and likely we'd fix both at the same time. Will add this case to it.
