### ISSUE TITLE
Re-enable rich nav on PRs once perf issue is fixed

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#54666]
>I think it would be best to just disable completely on PRs and perhaps keep an eye on it for rolling builds so that we can see if the regression gets fixed.

I'm fine with disabling as well, can we file an issue assigned to richnav, and have them re-enable it on PRs once the regression is fixed?

_Originally posted by @dibarbet in https://github.com/dotnet/roslyn/issues/54662#issuecomment-875847652_

Tracking issue for RichNav (internal only): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1353111

**Comment by mavasani** [comment]
I believe this has been done.
