### ISSUE TITLE
Well-known type members' descriptors initialization code quality

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#54668]
I have noticed that the code behind storing the information about well-known type members specifically is a massive hard-coded byte array that introduces large difficulty maintaining. Are there any considerations for its improvements? If so, I've already got a branch underway, just asking if such a change would interest anyone.

The specific file in question is `src\Compilers\Core\Portable\WellKnownMembers.cs`.

**Comment by Youssef1313** [comment]
I think if you already have made a change, just open a PR.

**Comment by AlFasGD** [comment]
It's the 400+ members that I will have to manually recode using the new API. That, or develop some tool to do that, which could result in issues. I asked beforehand to know whether it would be worth getting that task done.

**Comment by Youssef1313** [comment]
@AlFasGD Oh I thought you already made the change in a local branch. I think you could describe the exact change you plan to do in the issue (possibly with an example for **one** of those 400+ members), so the compiler team can decide whether it's okay for them or not.

**Comment by AlFasGD** [comment]
I have pushed a branch that now also includes an example for the API, which is [AlFasGD:well-known-member-refurbish](https://github.com/AlFasGD/roslyn/tree/well-known-member-refurbish). I believe it should be converted into a PR for feedback.

**Comment by jaredpar** [comment]
I'd push back on the premise here. What is difficult about maintaining this array? The basic structure here has been in place since the start of the Roslyn project, and the overall structure was the same in the native C# / VB compilers. It does take a few minutes to get your head around initially but overall it's a proven approach to dealing with the problems here. 

Don't think we'd be willing to take stylistic changes here (change for the sake of change). If there is a tangible benefit here to the changes I'd be interested in hearing that (perf, size, etc ...)

**Comment by AlFasGD** [comment]
It wouldn't be bad if it weren't for the case of needing to add a new well-known type member. In that case, there are two cases, copying an old member's information and making the necessary changes, or dealing with learning how the system won't break if it's a signature not often encountered.

Regarding the changes' effect, with what I designed I was taking performance in mind, and from my hypothesis it won't be noticeable. Surely, a raw array initialization is much quicker than initializing hundreds of class instances and individual arrays. But in real-world performance, especially when that code will only be executed once, it barely hits. The new changes attempt to respect performance as much as possible while offering a more elegant solution to how the code looks.

That being said, the giant array solution greatly helps performance compared to the smaller ones, so it would be nicer if the actual solution is to directly update it rather than construct it from chunks. However, I wanted to avoid depending on order of elements and make the elements' indices more explicit outside of comments.

In another note, the memory stream reading solution still exists and the generated bytes still follow that pattern. I could not tell whether it must remain the way it is, or if changes are allowed depending on the needs for that.

**Comment by RikkiGibson** [comment]
I found it pretty tedious to successfully add an entry to WellKnownMember, so I'd at least be open to reviewing something which improves the maintainability of it.

**Comment by jaredpar** [comment]
I agree it can be tedious but this feels like refactor for the sake of refactoring here. It's not solving a problem that we regularly run into. Generally we say no to those changes because of the unnecessary churn (and merge problems it creates).

**Comment by AlFasGD** [comment]
While that indeed might be the case, I would consider it as a nice-to-have instead of a pure no, if available.
