### ISSUE TITLE
Renaming issue with type preview enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54661]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming-issue-with-type-preview-enabled/1466940)._

---
[severity:It's more difficult to complete my work]
Really like the new feature that previews the type of implicit variables and anonymous objects inline.
A problem occurs when renaming them though - the cursor gets reset to the beginning of the name of the object after each key stroke because the type preview is refreshing.

[renaming-issue.mp4](https://user-images.githubusercontent.com/475144/124801094-4af2ea00-df0b-11eb-927c-edef18b25388.mp4)

---
#### Feedback Bot on 7/4/2021, 08:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We no longer interfere with typing.
