### ISSUE TITLE
Proposal: Labeled Modifiers

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5467]
Labeled access modifiers from C++ not only keep member signatures concise, but also, **encourage to group methods by access modifier** which is currently done by `#region Public Methods` and so on.
```C#
public class Foo {
    readonly:
    // private fields ...
}
public static class Extensions {
    public static: 
    // extension method definitions...
}
```
This provides with more focused and readable code since it is guaranteed that methods under a specific access modifier label have a specific purpose, e.g. internal stuff, static helpers, etc.

**Comment by svick** [comment]
On the other hand, this would make it harder to figure out on first glance which modifiers apply to a method.

Also, I don't think that something like "internal stuff" is a *purpose*, it's more of a technical detail. 

My personal style is to group members by their relationship (e.g. a `private static` method would be near a `public` method that calls it). So I don't think making the language more confusing for everyone is worth saving typing for some people.

**Comment by alrz** [comment]
@svick 
>I don't think that something like "internal stuff" is a purpose, it's more of a technical detail.

I'm not a native English speaker, sorry about that. I had same problem to conceiving `private protected` while it would make sense for a native speaker.

Your arguments are valid. However, I'm not telling that it could be replaced with the current syntax, as it should be backward compatible. You can continue to use your personal style (before you define any labeled access modifier) and keep this for situations like extension methods or static classes which almost all of the methods have the same access modifier.

**Comment by gafter** [comment]
It seems very unlikely that we'd ever do this.

**Comment by alrz** [comment]
@gafter why is that?

**Comment by gafter** [comment]
It is a pretty significant change with little, if any, value. Note that the first example has a modifier that is not an access modifier, so any actual proposal would likely be more complex than the title would imply.
