### ISSUE TITLE
Semantic tokens edits handler returns incorrect deltas

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#54671]
**Version Used**: 
Visual Studio 16.10 Int Preview
Visual Studio 17.0 Int Preview

**Steps to Reproduce**:

- Create a simple C# app like this:

![image](https://user-images.githubusercontent.com/5387680/124840329-90c9a580-df3f-11eb-9409-c99a37722f1e.png)

- Enable the 'experimental C#/VB editor' Preview Feature
![image](https://user-images.githubusercontent.com/5387680/124840171-37617680-df3f-11eb-81e8-01817d57c3cf.png)

- Repeated type SPACE, then BACKSPACE, quickly at ---> fo|r (...

**Expected Behavior**:

Colors are updated asynchronously and catch up with any edits the user makes.

**Actual Behavior**:

- Various tokens can end up off by one.
- Large edits can end up with significant color corruption, such as off-by-entire-word in several places.
- Cases that don't have _visible_ impact, the LSP client is recovering by detecting tokens past the end of the line and doing an expensive re-request/re-draw of the entire view.

![image](https://user-images.githubusercontent.com/5387680/124840448-d9815e80-df3f-11eb-8a66-b33ffcfee582.png)

**Net Impact**

- Local: shouldn't really be impacted, because this feature flag is not enabled locally.
- LiveShare guest: isn't _currently_ impacted because of [a hack I put in place](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FTagger%2FSemanticTokensDocumentClassificationTagger.cs&version=GBdevelop&line=251&lineEnd=261&lineStartColumn=1&lineEndColumn=14&lineStyle=plain&_a=contents) to work around a similar versioning issue in LiveShare. A prototype of the fix exists but was never funded to be fixed.
- ASP.NET Razor: making edits to lines containing C# can corrupt Razor document token positions. There's at least one feedback ticket about this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1349853
- Looks like this is a missed case of #45427

**Comment by gundermanc** [comment]
#45427 introduced [a _textDocument/didChange_ handler](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs#L43) that maintains a snapshot of the document, as referenced by client requests.

I believe the fix is to translate the spans to the text version backed by [GetTrackedDocumentSourceText](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/RequestContext.cs#L226) or similar to get your results against that document version (i.e.: whatever the Roslyn LSP equivalent of _span.TranslateTo()_ is) in all of the [SemanticTokensHandlers](https://github.com/dotnet/roslyn/tree/main/src/Features/LanguageServer/Protocol/Handler/SemanticTokens), most importantly, in the [SemanticTokensEdits]() handler.

**cc:** @allisonchou, @ryanbrandenburg

**Comment by dibarbet** [comment]
> I believe the fix is to translate the spans to the text version backed by [GetTrackedDocumentSourceText](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/RequestContext.cs#L226) or similar to get your results against that document version (i.e.: whatever the Roslyn LSP equivalent of _span.TranslateTo()_ is) in all of the [SemanticTokensHandlers](https://github.com/dotnet/roslyn/tree/main/src/Features/LanguageServer/Protocol/Handler/SemanticTokens), most importantly, in the SemanticTokensEdits handler.

The document passed into the edits handler ([as part of the context](https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs,49)) should already be the 'LSP snapshot' created via didChange events.  The LSP handler doesn't even have access to any other document, unless it goes back to the workspace.

Not ruling out bugs though in creating that snapshot though

**Comment by gundermanc** [comment]
Another possibility is that the deltas we're receiving are just invalid. Here's a more minimal repro:

```csharp
fo |r (int i =0;/*comment*/;i++)
{
}
```

Press BACKSPACE and...

![image](https://user-images.githubusercontent.com/5387680/124845894-89f55f80-df4c-11eb-81f0-2adc50983ca1.png)

The messages sent from the client were:

### textDocument/semanticTokens

```json
{
  "jsonrpc": "2.0",
  "id": 10,
  "result": {
    "resultId": "4",
    "data": [
      0, 0, 2, 8, 0,

      0, 3, 1, 30, 0,

      0, 2, 1, 36, 0,

      0, 1, 3, 15, 0,

      0, 4, 1, 7, 0,

      0, 1, 1, 21, 0,

      0, 1, 1, 19, 0,

      0, 1, 1, 36, 0,

      0, 1, 11, 17, 0,

      0, 11, 1, 36, 0,

      0, 1, 1, 8, 0,

      0, 1, 2, 21, 0,

      0, 2, 1, 36, 0,

      1, 0, 1, 36, 0,

      1, 0, 1, 36, 0
    ]
  }
}
```

###textDocument/didChange

```json
{
  "traceparent": "00-92532aee3f2bdc4886e1fc07db3d4999-fe2edd273cffd64c-01",
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "textDocument": {
      "version": 2,
      "uri": "file:///C:/Users/chgund/source/repos/ConsoleApp15/ConsoleApp15/Program.cs"
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 2
          },
          "end": {
            "line": 0,
            "character": 3
          }
        },
        "rangeLength": 1,
        "text": ""
      }
    ]
  }
}
```

###textDocument/semanticTokens/edits

```json
{
  "jsonrpc": "2.0",
  "id": 16,
  "result": {
    "resultId": "5",
    "edits": [
      {
        "start": 0,
        "deleteCount": 10,
        "data": [
          0, 0, 3, 23, 0,

          0, 4, 1, 36, 0
        ]
      },
      {
        "start": 10,
        "deleteCount": 5,
        "data": []
      },
      {
        "start": 15,
        "deleteCount": 0,
        "data": [
          0, 4, 1, 29, 0
        ]
      },
      {
        "start": 20,
        "deleteCount": 5,
        "data": []
      },
      {
        "start": 45,
        "deleteCount": 0,
        "data": [
          0, 1, 1, 29,0
        ]
      },
      {
        "start": 50,
        "deleteCount": 5,
        "data": []
      }
    ],
    "partialResultToken": null
  }
}
```

**Comment by allisonchou** [comment]
@gundermanc I'm pretty sure I tracked down the cause of this, although unfortunately it doesn't seem to be a simple fix. The tl;dr version is[ we currently only consider two `EditKinds`](https://github.com/dotnet/roslyn/blob/ad857217f389d6e6e46ae697be87967df9121d6f/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs#L129) in our Roslyn algorithm, `EditKind.Insert` and `EditKind.Delete`. It turns out in some cases we also need to consider `EditKind.Update`. I believe the change won't be trivial as it will likely involve changing significant parts of the edit logic, but I'm working on it.

**Comment by gundermanc** [comment]
Thanks for the update! Let me know if I can do anything to help.

**Comment by Mike-E-angelo** [comment]
Would it be possible to get confirmation on this issue if it made it into Preview 4?  It was referenced as a "pending fix" in [this issue](https://youtrack.jetbrains.com/issue/RSRP-486030#focus=Comments-27-5201750.0-0) but based on the timeline of the merge it would seem this is in Preview 4 already, [which is experiencing weird coloring issues with Razor files](https://developercommunity.visualstudio.com/t/razor-editor-resulting-in-weird-coloring/1531777?).

**Comment by gundermanc** [comment]
@Mike-E-angelo thank you for following up on this issue. To clarify, there are a few distinct factors contributing to this issue:

- This Roslyn issue: was fixed in Preview 4, but in the process seems to have uncovered a latent VS language server protocol client issue.

- The underlying IDE issue: in language server semantic tokens, there's an issue where the colorization data can be inadvertently modified during application of a color delta. If the deltas from the LSP server line up just right, colors will appear at the wrong spot. This requires a very specific sequence of edits to occur to repro, and a very specific pattern of deltas, so it didn't show up frequently until now, now that the Roslyn issue is fixed.

The second issue is fixed pending release (post-Preview 4) and may solve the related Developer Community issue: https://developercommunity.visualstudio.com/t/razor-editor-resulting-in-weird-coloring/1531777.

Until then, the work-around of disabling the Razor LSP Editor, posted by JetBrains, should alleviate the symptoms of the issue.

If you can share a consistent minimal repro, in the form of a file and one or more specific edits known to trigger the issue, I can verify it is fixed for you too.

**Comment by Mike-E-angelo** [comment]
Great!  Thank you for your thorough and detailed reply, @gundermanc.  The coloring seems bizarrely random, but it does occur with frequency. I will see if I can track down an easily reproducible set of conditions for you to test/verify. 👍
