### ISSUE TITLE
GenerateEnumMemberCodeFixProvider does not apply if enum type name matches a property name

### ISSUE THREAD

**Issue by afscrome** [dotnet/roslyn#5468]
Consider the following code:

``` csharp
enum Colour { Blue, Green }
class Sample1
{
    //CS106 'Colour' does not contain a definition for 'Red' and no extension method 'Red' accepting a first argument of type 'MyEnum' could be found(are you missing a using directive or an assembly reference?)
    Colour Colour => Colour.Red;

    void Method()
    {
        //CS106 again
        if(Colour == Colour.Red) { }
    }
}
```

I'd expect the GenerateEnumMemberCodeFixProvider to be applicable to the two instances of `Colour.Red`, however it's not.  It seems that because the property name matches the type name of the enumeration, Roslyn reports error CS106 rather than CS0117, so the code fix isn't applicable.  If you change the `Colour` property name to something other than the Enum's type name (e.g. `Colour2`), then the code fix is applicable. 

What's unclear to me is what the expected behaviour should be? Should the two instances of `Colour.Red` report error CS0117 (which the code fix will respond to correctly), or should the code fix handle error CS1061?

**Comment by Pilchie** [comment]
Given that the VS2013 compiler also reported CS1061, I think we should update the code fix to handle CS0117 to handle "Color Color" cases.

**Comment by afscrome** [comment]
@Pilchie Can you clarify - you say "update the code fix to handle **CS0117**"?  Did you mean to say **CS1061** instead?

**Comment by Pilchie** [comment]
Doh,  Yes of course.
