### ISSUE TITLE
Data ASTs?

### ISSUE THREAD

**Issue by Mike-EEE** [dotnet/roslyn#5469]
Hello Roslyn Community. :)

I am curious if I can get a question answered here along with a feature request heard.  I recently found out that Roslyn only supports C# and VB.NET, which was surprising to me.  My thought was that a .NET AST was an .NET AST so all languages are supported.  Guess I am too ambitious/naive in my thinking. :)  I am curious if I can get a pointer to the direction of what languages are planned to be supported in the future.

Additionally, I am also curious about another feature of Roslyn.  An extension, if you will.  I (and others) would like to see the notion of a "code" AST be extended to a "data" AST.  That is, I think it would be very valuable to be able to load in a data file (say, a JSON file) and then have its contents parsed into an AST -- a Data AST.

Once that is possible, then there is a lot of valuable things you can do.  First and foremost, you can use that AST to create a new AST that can be viewed and edited in another format, such as XML or even XAML.

The value of this is that developers would be able to load in any data format and then view/edit it in the format that they prefer.  When the file is then saved, it is saved based on the format that the file was originally loaded.

I am throwing this out there for discussion and wanted to see what others think of this.  There are several really good discussions out there that sort of highlight the need for this.  Here are a few:
https://github.com/Microsoft/msbuild/issues/16
https://github.com/aspnet/Announcements/issues/24

Additionally, I have also created a vote on UserVoice that speaks to this need, as well (and mention the discussions above).  You can see it has some number of votes and shows that I am not the only one who would like to see something like this:
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/9347001-improve-reboot-visual-studio-project-system

Thank you for any consideration/feedback!

**Comment by jmarolf** [comment]
> I recently found out that Roslyn only supports C# and VB.NET, which was surprising to me. My thought was that a .NET AST was an .NET AST so all languages are supported.

Implementing a syntax tree is not the only part of being a Roslyn language.  You also need to support thousands of other APIs around your symbol model.  For simplicity, Roslyn was only designed with VB and C# in mind for its initial release.  Other languages are always possible, but Roslyn was not designed to be a universal compiler infrastructure.  It was designed to be a great C# and VB compiler.  As its open source there should be no reason others can't implement Roslyn APIs for whatever language they prefer.

> I (and others) would like to see the notion of a "code" AST be extended to a "data" AST. That is, I think it would be very valuable to be able to load in a data file (say, a JSON file) and then have its contents parsed into an AST -- a Data AST.

There are many serialization formats out there, JSON, XML, and YAML to name a few.  Are you saying you want these to be treated as Roslyn languages?

**Comment by Michael-DST** [comment]
>  It was designed to be a great C# and VB compiler.

And it is!  Mission quite accomplished.  So much so it is now inspiring other new implementations/possibilities for it. :)

> Are you saying you want these to be treated as Roslyn languages?

Yes, that is the request/ask here.  It's a small jump (considering) from a full-blown language syntax tree to describing a data syntax tree, is it not?  That is my initiali impression, but I didn't write the thing, haha.

I think this would be an incredible (and innovative) step in development around data files.  Essentially, this would allow Visual Studio (or a tool/extension of it) to load in any (supported) data file, and then be able to manage it in memory in new and compelling ways.  

For instance, Visual Studio could then take the Data AST and render it in another format altogether -- one to the preference/setting of the developer.  This would allow a team to use a decided/"preferred" format (e.g., json) and individual developers would be able to view/edit the same files in *their* preferred format (e.g. xaml/xml).  When the file is saved back to disk, it is saved as the format that it was originally opened in and checked back into source control as such (if necessary).  The developer works in a format they prefer, and the team has files in a format they prefer.  Everyone wins. :)

Hopefully that makes sense.  I am actually writing a blog post (and introducing a new UserVoice vote) around this very idea and will update this thread when I post it to provide additional context around this, hopefully in another day or so.

**Comment by jmarolf** [comment]
>Essentially, this would allow Visual Studio (or a tool/extension of it) to load in any (supported) data file, and then be able to manage it in memory in new and compelling ways.

There is significant complexity in say taking VB code and displaying it as C# or vice-versa.  It is not unsolvable, but even in the case of Roslyn, which was designed to have a common syntax tree, there would need to be a lot of special casing.  I would think it would be a lot of work to write and maintain many translators.  Have a common "AST" doesn't really solve any of the difficult representation problems.

**Comment by Michael-DST** [comment]
> Have a common "AST" doesn't really solve any of the difficult representation problems.

I didn't say it would be easy. :)  I am wanting to solve a very difficult and emerging problem with software development (and if you have been on any project that has argued around the "right" data format to use, you know how strong and real of a problem it is!).  I am sensing that Roslyn might be able to assist with a possible solution. I could be wrong, that's why I wanted to start a discussion here.

Maybe Roslyn needs an Extension API? :)

**Comment by Michael-DST** [comment]
OK, it took a little longer as expected (as it always does), but here is the blog post:
http://blog.developers.win/2015/10/data-asts-and-data-views/

Additionally, there is another similarly cool feature I think Roslyn could help with, and that is Code Views:
http://blog.developers.win/2015/10/roslyn-powered-code-views/

Both of these have UserVoice votes mentioned in the articles to Visual Studio UserVoice votes.  Any feedback (or votes!) would be greatly appreciated!

**Comment by CyrusNajmabadi** [comment]
Hi @Mike-EEE, this is out of scope for the goals of the Roslyn project.  Roslyn does not aim to, and is not working on, a general platform for either compilers or .net languages.  It is very focused on both being just a good analysis/feature system for VB and C# and to work with the greater IDE ecosystem through projects like [lsif](https://github.com/microsoft/language-server-protocol/blob/master/indexFormat/specification.md) and [lsp](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/)

Thanks!

**Comment by Mike-EEE** [comment]
In agreement, @CyrusNajmabadi.  While it is focused on these things, it's also an incredible source of developer creativity and inspiration, which is why it got me to post this in the first place. 😆  

This is one of those things where I wouldn't have done it unless I learned not to do it from having done it, if that makes any sort of sense. 😁

**Comment by Mike-EEE** [comment]
> This is one of those things where I wouldn't have done it unless I learned not to do it from having done it, if that makes any sort of sense. 😁

Incidentally, this is also the perpetual story of my life. 😏
