### ISSUE TITLE
In Quick Info, types in type parameter constraint clauses are not simplified

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#547]
Ported from TFS WorkItem: **981839**

---

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Copy/Paste C#:

&nbsp;

<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: gray"><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Collections</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Generic</SPAN><SPAN style="COLOR: black">;</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN><SPAN style="COLOR: black">&lt;</SPAN><SPAN style="COLOR: #2b91af">T</SPAN><SPAN style="COLOR: black">,</SPAN> <SPAN style="COLOR: #2b91af">U</SPAN><SPAN style="COLOR: black">&gt;</SPAN> <SPAN style="COLOR: blue">where</SPAN> <SPAN style="COLOR: #2b91af">T</SPAN> <SPAN style="COLOR: black">:</SPAN> <SPAN style="COLOR: blue">struct</SPAN> <SPAN style="COLOR: blue">where</SPAN> <SPAN style="COLOR: #2b91af">U</SPAN> <SPAN style="COLOR: black">:</SPAN> <SPAN style="COLOR: #2b91af">List</SPAN><SPAN style="COLOR: black">&lt;</SPAN><SPAN style="COLOR: #2b91af">T</SPAN><SPAN style="COLOR: black">&gt;</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">M</SPAN><SPAN style="COLOR: black">()</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: blue">var</SPAN> <SPAN style="COLOR: black">x</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: blue">new</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN><SPAN style="COLOR: black">&lt;</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">,</SPAN> <SPAN style="COLOR: #2b91af">List</SPAN><SPAN style="COLOR: black">&lt;</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">&gt;&gt;();</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE></SPAN></PRE>

&nbsp;
1. Hover on **var**

****&nbsp;

**Expected**: "List&lt;T&gt;" is shown in two places (in constraint clause and in description of U below).

&nbsp;

**Actual**: In the constraint clause, it is listed as "System.Collections.Generic.List&lt;T&gt;"

---

**Revisions:**

1) Created By David Poeschl (7/8/2014 2:45:49 PM)
2) Screenshot added by jcouv
---

![image](https://user-images.githubusercontent.com/12466233/41944855-edc2b8d4-795e-11e8-9c1d-94aa324f281c.png)

**Comment by alexsorokoletov** [comment]
>src\EditorFeatures\CSharp\QuickInfo\SemanticQuickInfoProvider.cs is probably a good place to start
@Pilchie

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of feedback.
