### ISSUE TITLE
Using class as NameSpace bug

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#54708]
**Version Used**: 
Visual Studio 2019; .NET Framework 4.8; C# 8.0

Reference: 
![image](https://user-images.githubusercontent.com/23723575/125045324-7292af80-e0cf-11eb-888d-9b5c3a11120c.png)

**Comment by PathogenDavid** [comment]
This is [expected as per spec](https://github.com/dotnet/csharplang/blob/7e863bee4a12d8a7b049e2fd43b7cd1ba4ca0b3e/spec/namespaces.md#using-alias-directives):

> Just like regular members, names introduced by *using_alias_directives* are hidden by similarly named members in nested scopes.

The namespace `Grid` is hiding your using alias.

----------------

You can workaround this by moving the using alias inside the namespace scope, for example: ([SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmANDCAnJgD4D0HABACoAW6ZNwDu6IkW6YCMUQQQBrEAFgAUFwACABm4BpApmTEI3ALzcNARgB0AYQNGiEANxq1mKAFsUeKAGMTAFkATwA5Lx9/CGt9Q2NrAHV+UgA3XDUAbzVuHO4uPkFhMQkVVVyLHVjHE3MrOwdjV1Vs3I0AZgsAJgtLAHYWnKyy8tbOzoGRoZHpvQanRJocABksCAAKACIACQgJAno5BCIyAEINgEomme4AXwm71QegA))

```csharp
// This will not work:
//using Konsole = System.Console;

namespace MyNamespace.Konsole.Whatever
{
    // This will:
    using Konsole = System.Console;

    public class Program
    {
        public static void Main()
        {
            Konsole.WriteLine("Hello, world!");
        }
    }
}
```

**Comment by kelicto** [comment]
I think you should understand my intentions. I know that using alias to solve it, but it's not good idea.

1. The namespace of 'Grid' is very long as method parameter.
2. 'Wall' class can be used as a namespace.

@PathogenDavid

**Comment by kelicto** [comment]
The problem is easy to ignore. I think compiler should give us more friendly message.

**Comment by kelicto** [comment]
> This is [expected as per spec](https://github.com/dotnet/csharplang/blob/7e863bee4a12d8a7b049e2fd43b7cd1ba4ca0b3e/spec/namespaces.md#using-alias-directives):
> 
> > Just like regular members, names introduced by _using_alias_directives_ are hidden by similarly named members in nested scopes.
> 
> The namespace `Grid` is hiding your using alias.
> 
> See also: #21753 #35007
> 
> You can workaround this by moving the using alias inside the namespace scope, for example: ([SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmANDCAnJgD4D0HABACoAW6ZNwDu6IkW6YCMUQQQBrEAFgAUFwACABm4BpApmTEI3ALzcNARgB0AYQNGiEANxq1mKAFsUeKAGMTAFkATwA5Lx9/CGt9Q2NrAHV+UgA3XDUAbzVuHO4uPkFhMQkVVVyLHVjHE3MrOwdjV1Vs3I0AZgsAJgtLAHYWnKyy8tbOzoGRoZHpvQanRJocABksCAAKACIACQgJAno5BCIyAEINgEomme4AXwm71QegA))
> 
> ```cs
> // This will not work:
> //using Konsole = System.Console;
> 
> namespace MyNamespace.Konsole.Whatever
> {
>     // This will:
>     using Konsole = System.Console;
> 
>     public class Program
>     {
>         public static void Main()
>         {
>             Konsole.WriteLine("Hello, world!");
>         }
>     }
> }
> ```

It's a good idea. I know the reason. But, the problem is easy to ignore. I think compiler should give us some friendly message. :)
