### ISSUE TITLE
Proposal idea: opt-in visibility access modifiers

### ISSUE THREAD

**Issue by jvlppm** [dotnet/roslyn#5470]
# Proposal idea: Ability to create custom additional access modifiers

## Motivation:
When you are developing an API, you want to make
things as simple as possible, but at the same time,
make it flexible so it can be extended.

With this proposal idea you could hide the inner
workings of your API, but at the same time,
allow them to be used in an opt-in manner by a
"power-user" (someone extending your API, probably).

## Method visibility

Methods could be exposed by anyone who "uses" the custom modifier.

### Public method sample

```csharp
class Button {
	expose modifier Controller;

	public Controller void FireClicked() {
		...
	}
}

// Case 1, normal access
class ButtonRenderer {
	Button button;
	
	void TouchReleased(Touch touch) {
		button.FireClicked(); // Error, method is not acessible (as if it was private)
	}
}

// Case 2, class uses the modifier
class ButtonRenderer uses Button.Controller {
	Button button;
	
	void TouchReleased(Touch touch) {
		button.FireClicked(); // OK: Method normally visible
	}
}

// Case 3, method uses the modifier
class ButtonRenderer {
	Button button;
	
	void TouchReleased(Touch touch) uses Button.Controller {
		button.FireClicked(); // OK: Method normally visible
	}
	
	void TouchCancelled(Touch touch) {
		button.FireClicked(); // Error: Method is not acessible (requires Button.Controller)
	}
}

```
Syntax could be changed, but this is the idea.

Currently the method FireClicked would be set with
the 'internal' modifier, but this would prevent
anyone, from an external assembly, to access it.
(Someone could be trying to extend your renderer,
but FireClicked would not be visible unfortunatelly).

A custom modifier on a protected member would also work,
and it would not bypass any other modifier.

### Protected method sample

```csharp
class Button {
	expose modifier Controller;

	protected Controller void FireClicked() {
		...
	}
}

class ButtonRenderer uses Button.Controller {
	Button button;
	
	void TouchReleased(Touch touch) {
		button.FireClicked(); // Error: method is not acessible
	}
}

class CustomButton : Button {
	override protected Controller void FireClicked() {
		// Error: method is not acessible,
		// and cannot be overwritten
	}
}

class CustomButton : Button uses Button.Controller {
	override protected Controller void FireClicked() {
		... // OK
	}
}
```

## Exposing classes

An entire class could be exposed by modifiers
that were declared at the assembly level

#### Assembly 1 (AssemblyName: SampleUI)
```csharp
expose modifier TouchAPI;

namespace Sample.UI {
	public TouchAPI class TouchController {
		public Point ConvertPosition(View view, Touch touch) {
			...
		}
	}
	
	public class Button {
		public TouchAPI TouchController controller;
	}
}
```

#### Assembly 2
```csharp
// Now Button.controller is visible
// Also the class TouchController
uses SampleUI.TouchAPI;

namespace Sample.UI { // Same namespace not required
	public TouchAPI class CustomTouchController : TouchController {
		public override Point ConvertPosition(View view, Touch touch) {
			...
		}
	}
	
	public CustomButton : Button {
		public CustomButton() {
			controller = new CustomTouchController();
		}
	}
}
```

### Wrap-up access

```csharp
public int attribute; // Public
public CustomModifier int attribute; // Public to those using CustomModifier, otherwise private.
```

The same principle works for protected.

Comments?
Can anyone see usage for this?

**Comment by gafter** [comment]
You can already do this using "privately implemented" interfaces. Why isn't that sufficient to address the use cases?

**Comment by jvlppm** [comment]
It works... but,
- you have to cast the other object to have access to its members, making it cumbersome
- if the other object stops implementing the interface, you will have no compiler errors with the casts
- you cannot hide an entire class

with my idea you have something like a named-'internal' or scope that you can easily opt in.

Something like [InternalsVisibleTo("assembly")] would also work,
 but in a way that the extension would declare
[ViewInternalsOf("assembly")]

But with the modifiers it would be easy to select what and how it would be exposed.

**Comment by GSPP** [comment]
Sometimes this is done by exposing a property that returns a handle to more advanced functions. The RavenDB session does that AFAIK.

**Comment by gafter** [comment]
@jvlppm if the interface is in the base list of the class, you can convert with a simple assignment; no cast is needed.

**Comment by gafter** [comment]
The existing language features appear sufficient to express the intent of this request (either implement an interface, or have a property that returns the semi-private API).

**Comment by jvlppm** [comment]
Yes, I never said it was not possible.
The proposed alternatives (existing language features) are:

# Implicitly implement interfaces to hide the method:
 - Downside 1: You have to create an interface to control which method to expose / hide
 - Downside 2: The interface have to mimic your method signature, so, you have to change both the interface and your class if you want to update your method signature.
 - Downside 3: You need to cast your object to use those methods, or create a temporary variable (with the interface type), that is actually the same object that you had before, but with some methods exposed.
 - Downside 4: If the original object stops implementing the interface, and you did use cast, your cast will compile normally but will fail at runtime. 

# Create a property to expose advanced features
 - Downside:  If you want to hide or expose a method you need to change how your class is structured, so its not as straightforward.

Proposed idea: Simply mark your method with a new custom access modifier.

But I do accept a won't fix anyway, if it is not worth it.

**Comment by jvlppm** [comment]
And what about expanding this idea, to allow you to override the default access modifier, something like a friend access.

It could be declared as:

```csharp
class Sample {
    expose overriding modifier Controller;
    private Controller void Notify() {
    }
}

class Usage {
    private void Test() uses Sample.Controller {
        new Sample().Notify(); // OK
    }
}
```

Could this be worth it?
(internal only works on the same assembly)
(syntax don't have to be like this)
