### ISSUE TITLE
CompleteStatementCommandHandler should work with yield return

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54709]
**Version Used**: 

main

**Steps to Reproduce**:

```csharp
        private static IEnumerable<int> M()
        {
            yield return GetNumber($$)
        }

```

Type `;` in place of `$$`

**Expected Behavior**:

Complete statement works.

**Actual Behavior**:

It doesn't.

Fix is straightforward here:

https://github.com/dotnet/roslyn/blob/7e53c4612ad6778f277de5aa3e97beab1eb061f3/src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs#L330

**Comment by jinujoseph** [comment]
cc @sharwell
