### ISSUE TITLE
Compiler is preferring using the default interpolated string handler over string.Concat

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#54702]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/1119ab9dfe3beb00b57ddef19674b956e7861d7d

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmAPgMSZxEnBEQAEEmUHEALAAoAAIAmAIwjRAZi4SuAYS4BvEV00L5oyQAYuAWQAUug1AA0C/V2ABKLgF4AfFwAkAIlVQAvmuA+HgDcIj4iInwAtih4UADG3LoAdABKcNjo0UlKBJF46JwIAMq4AG7oCcgi6sJaXADayQCCMNTowHA4AKrIULQQLW0dOKaSSYM0wxAAKlAI/TDI2STIyFz01uOtk50zcwtLRdRwcTBWTWwEAO6GrDDoeJxOXGBQRMgQVgCSmAAWuOgcGRnq93hA7ABdDRaORcD5vcgKcRcH44fDEUhkI40TC0AASUEwZEKE3auy4IE2pKm0M0NTqdVhqNwhBIQOxdAJRJJ2zJIwcqi4YVqWmFdUaY2pux6fQgoy2Q12s3mEEWSQACnMoNE0edLjc7g8no4Xm8Pt8/gCgSCzeCoSLNLD4ZxgYpmei2eQObiucTcE15nBotgpTgKVTeTSHWpaQymdgWRj2W0fYS/QgA7Qg7wYKG5WYuPts9gBULY4z5O7WZjvfi0yTA8Hc5HdsZYghtWszPUIYXGznkKWxQzHTp9D2uJni4s1FwFrOYL8ENcuCw2EEhWXo8PNBLUul7lkcnkCrgSghypUklWk16U3Xuf6Wzh7RWuEgwHDjqcuAARCCvHcN6eli96+oUsb0iOXB4DQpSkO+0BkAQmBEAAnlwBDAAAVhAP4APpkEGkRoSE0Z1LB6DwWGSBQMhqEYVgMBcIRxFoeqNCRICVEQGR0HaH+AFQEBCYejWYH1rgxhMVwRCArgbwADK8LQi5WDJYAEAgkSwECOQHqWi7Llcq6sEQG47nG8j/oBRAwMB4k4g+6bSdgsnyR2RDKbialcBpWk6a05D6dgVjJF8ABiAWwBxBDlGQuAAPwwcu8W4IZS4rmu5lbvxsI2cJdkOcmTngVJMlyWiSkqb5/nabpwUEAeYVjJF0UwLFaUIMlsFxegCUIC1SRFLEmAADxxL8cyuFg3FvAAQnAYCQAgGXGaZ665dBsKiAALJOeB4LwZCKR5byjAY8FEHA4KzpZb57QdR1ElF9VBWQ8opEhADyDEjYSE1TQgrhXTdQ7ljCOj7U0h3Ha9gVAp9P1/aNgPTVwoOfH5blvOgtCYE2zx6C1ejJZpb3PNl4PkZDCjQ7DL3tUCY3TM4xjTBjbxg3dEOjnTT1w0z5As2zHOYyTZPtdTeVQwLjNvczrPs5z11YzJuP4020vbbLMPPWQ8MNWQIvK+L2PMRrBM5hLLxSzzNN849euCwr5DGFhuGnMlZvq3Jms5kTNvk4FlNmdrI47fT+uG+9F3e1zt2CkZWVmRZvMCU7DMG0LH1mPHqvqTjftW25JrE9YpO2xTJpU/bMuYaUuA0AlFdcNMBC1sYa0p5t920wW7e1k0RJKJwcxdwumUmdlafbqEQA==
```C#
public class C
{
    public string M(string a, string b) => $"{a} {b}";
}
```

**Expected Behavior**:
The compiler should emit string.Concat when there's a good overload available, so the above should be lowered to the equivalent of:
```C#
public class C
{
    public string M(string a, string b) => string.Concat(a, " ", b);
}
```

**Actual Behavior**:
The compiler is lowering this to use the default interpolated string handler, equivalent to:
```C#
public string M(string a, string b)
{
    var h = new DefaultInterpolatedStringHandler(1, 2);
    h.AppendFormatted(a);
    h.AppendLiteral(" ");
    h.AppendFormatted(b);
    return h.ToStringAndClear();
}
```
This will manifest as a performance regression.

cc: @333fred

**Comment by 333fred** [comment]
This was intentional, because we didn't want to make any hardcoded assumptions about what overloads of string.Concat exist that don't require a params array. I suppose we could make another change here, but I'm slightly concerned by level of complexity of these rules.

**Comment by stephentoub** [comment]
It's a significant deoptimization. We should fix this.

**Comment by stephentoub** [comment]
For reference:

|  Method |     Mean |
|-------- |---------:|
|  Concat | 16.00 ns |
| Handler | 41.50 ns |

```C#
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Program
{
    public static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

    private string _a = "hello";
    private string _b = "world";

    [Benchmark]
    public string Concat() => string.Concat(_a, " ", _b);

    [Benchmark]
    public string Handler()
    {
        var handler = new DefaultInterpolatedStringHandler(1, 2);
        handler.AppendFormatted(_a);
        handler.AppendLiteral(" ");
        handler.AppendFormatted(_b);
        return handler.ToStringAndClear();
    }
}
```

**Comment by 333fred** [comment]
@stephentoub to make sure I'm understanding, what are the rules you'd like to see for when to use `string.Concat`? Only when it doesn't involve a params array? In all cases, no matter if it's a params array or not?

**Comment by stephentoub** [comment]
Thanks for asking.  From my perspective, ideally we'd only use these overloads:
```C#
string.Concat(string, string)
string.Concat(string, string, string)
string.Concat(string, string, string, string)
string.Concat(ReadOnlySpan<char>, ReadOnlySpan<char>)
string.Concat(ReadOnlySpan<char>, ReadOnlySpan<char>, ReadOnlySpan<char>)
string.Concat(ReadOnlySpan<char>, ReadOnlySpan<char>, ReadOnlySpan<char>, ReadOnlySpan<char>)
```
with the first three being the most important and the latter three being nice-to-have.  I'd be fine either hardcoding the list of valid target overloads, or coming up with a heuristic, e.g. "using the overload wouldn't incur a params array allocation or boxing".

**Comment by 333fred** [comment]
The ROS<char> version is significantly more involved than the string variant, so I'm going to leave those off for now, as those will require much more extensive changes to lowering.

**Comment by stephentoub** [comment]
Sounds good
