### ISSUE TITLE
Ternaries involving interpolated strings producing object locals and string casts

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#54705]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/1119ab9dfe3beb00b57ddef19674b956e7861d7d

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmAPgAIBMAjALABQjAzAAQs+AYT4BvLn0kD+WGHwCyrABTACxPsAA0fWToCUEqeM5TTA1gAY+yPgF4NfAPx8AJACJR6AL5u+IPm5uANyGZgIA7NYAdAAyEJi0MAAWISZSXlwZnFyYUAC2KHhQAMYQ5lEASnDY6AVRQgR5eOhEuADKuABu6KXIXMamANqMrFEAgjDU6MBwOACqyFC0EBNTMzhKI+OTNOsQACpQCMswyPUkyDb05au7swdHJ2dt1HDFMNpjREQEAO7ycCIMHQeFadj4YCgRGQEG0AElMElcOgcGRwZDoRA9ABdULSazQVpowQInD4YikMgvGgJAASUEwZFaCFu03ufhuOzZODxAzC+NJuEIJFR1Lo9MZzNZeyUejEfCypkVUmGo2l9wWSwgmzVXL2h2OEFOUQACkd8kbcJ9vn8AUCQWD7BiYfDEcjUeioTCcXjeASoeQBMw+ILySLyGK6Qymbgxsc4AVsOqcBytsmILy8aY/aHhZTI7QJTGWfHEzB0zqrI8E/EYHLRAqs1Ic9ghRTRVMo5LY6XaxWigh8jYRhZBti+NWy8h6420mE/SOx3w47Qa9gbA2TvLkgg/nxMICiEEFbOlXjVZVqsC6g0mi12l0eigorn2xHO4Xo1K9fdcXP8UgYDWK87x8AAIhAkKAjAr7hlSH5Fsymb/tm/AQVBQKwfmCFfrgSi6EQKK4FCcQJMk2i6GABAIHksCog0V4zjue4Ht8x7KvOaGQVA0FYR2NKft2CD4dgfCEWSJHxIkSQUaJVE0XR5AMdg2hbHCABi1G0TAJq7t0ZC4HweB6egBkIExSS7r8+6HuxTaSH66E8ZhrZhthAmIXhBFEYORCkdJslyPJ2n0QQV6qaMGlabAukEPphnGXFplWuUbRFJgAA8xRJEcAB8OiYCi6BQgAQnAYCQOZ26WSxtmnvyC4ACzLngeDxGQMQ+VClZ8J0UJwFi8ocWYTUtW1jKaQpkzkDqlTQGQADymBEAAnmlDJZTlCD5X1RADTOw2oQIzVjK17WTSFM1bBU81Lat62ZdleW9f1sIFXIULoLQmBluCFgRVYwWwOCrFEAd9n4owJ1nRN0XTWQGX7LlSj7C9e2DQ2h3NvwUNjedcOoojyOo7tA0AxCcPgyh2PHXjsNTYTSMo2jZPvROhHfWWVP8pD0PjWQF2KQjTMk69gXs19P21uTQN1kNEOjad/OC/DSgEMAABWECgaTb26J9nO1n9MtwyDh7cw1ON8/jDNXZYLMY3wzHWaDdnUw5Vt0wLBN21YuviwbUuifY/3mIDpv2KDFucXwcW4DQBlh3w+wEAWsrVVZNlsfVMcjsnqcfmMjJCK0Rzpw2ztZ0eOezl4QA
```C#
public class C
{
    public int M1(bool b, int i)
    {
        string s = b ? $"{i}" : "";
        return s.Length;
    }
}
```

**Expected Behavior**:
Produces the equivalent of:
```C#
    public int M1(bool b, int i)
    {
        string obj;
        if (!b)
        {
            obj = "";
        }
        else
        {
            DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(0, 1);
            defaultInterpolatedStringHandler.AppendFormatted(i);
            obj = defaultInterpolatedStringHandler.ToStringAndClear();
        }
        return obj.Length;
    }
```

**Actual Behavior**:
But it instead produces the equivalent of:
```C#
    public int M1(bool b, int i)
    {
        object obj;
        if (!b)
        {
            obj = "";
        }
        else
        {
            DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(0, 1);
            defaultInterpolatedStringHandler.AppendFormatted(i);
            obj = defaultInterpolatedStringHandler.ToStringAndClear();
        }
        return ((string)obj).Length;
    }
```

cc: @333fred

**Comment by 333fred** [comment]
This is a bug in the decompiler. Examining the IL shows no casts occurring and no object locals.

**Comment by stephentoub** [comment]
Thanks.
