### ISSUE TITLE
Interpolated string handler lowering isn't unescaping {{ and }}

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#54703]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/1119ab9dfe3beb00b57ddef19674b956e7861d7d

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQEsB2MIIA4D2ANrBACarIwJYDmAPgMSZxEnBEQAEEmUHEALAAoAAIAmAIwjRAZi4SuAYREBvEV00L5oyQAYuAWQAUWGF3QBKLgF4AfFwAkAIlWquq9AF8uXr84BuES8RET4AWxQ8KABjbl0AOgAlOGx0SISlAnC8dE4EAGVcADd0OOQ1DS0AbUSAQRhqdGA4HABVZChaCAamlpxjesaafogAFSgEbphkTJJkZC56BUkE3pHW8cnp2YLqOBiYABouOrYCAHdDVhh0PE5bLjAoImQIE4BJTAALXHQcMiPZ6vCCWAC6VU0ci4bxe5AU4i4Xxw+GIpDIexomFoAAkoJgyPl1s1NlwQCs1sMSThIR5aVptEjsLhCCQAZi6HiCUSqaNjNZ3CFhAyhQzaqtiaMOl0IIMJbzNhMphAZgkAAqTKCRFEnM5ES7XIi3e7cGxPF5vT4/P4AoEW0EQ4VaaGwziAxTIllo9lNbFcwm4OpTOCRbCS0nkoZ9Ta09ROhlQ+Se1Fs8gcv34gMIIO0EO8GDhga6AzbPPYAW+enOpPMlPo9O4zNE4OhgsKgbRBBaxbF6pgril1vICuihOJlZ6PunFv5xbuaYeLgwb4IS5cFhsAK+SvxndixIpNIZLI5PK4IoIUrlBLJ1n132N7mB9sQR0M6FIMAw/aHLgAEQgZ4blvb00wff18ljKtNDwGhilILgkCgMgCEwIgAE8uAIYAACsIF/AB9MgQ3CdCgl3BlYPQeCcEQ6AULQzCzC4IiSPQtUaHCf5qIgcix3HACgKNEDUwxcCm1wUxsC4Ih/lwF4ABleFoZcTmYsACAQcJYABLJUhgCtl1XC511YIgt1HMdoUEqBgNrO8fSxR8syk8xZJRRTlNUixpI0rSdPIPTsBORIPgAMU07SYA4ghSjIXAAH4uFg2L0HihBDJXNcN3Mvd+OswDbOE+zQLEpyIMk5j3PkoglOxbz1MigKyCC44KXCprotXOLEuS7q0twELVgKaJMAAHhib5JgcLBuJeAAhOAwEgDLFyM7KzIs6DGVEAAWU48DwXgyAUuSuyIOUDHgog4FBRdLITaE9oOo6CQi/zGnIOVknogB5RiRvxCapoQBxrtukdtqe/a6kO473qigFvqSP6AdG4Hpq4cH3h88wXnQWhMFbR49CGvQkr8qLHhyyGKOrBQYbht7OoBMaxjsYwxixl4IfuqGdEZ16yAR5q2Y5rnsbJinOtp/idsF+GWfIMXOe5m6ceY/HCdbWX8oFl7FY+1n2dVyXcYHWTtfzKWnhlvm6fHZ7YaFkXPrIYxsLww4krNzXLaJ/MSZtynYGpszdas/XncNxGvuLH2ebu9x1pMnKtod+WDeZo24/0BP1bU6StYD6SzVJidpY+sO2Ajx75Fi3AaHiicuDGAgG35NastTza8sjlu24bOoCSUThJk75Pu9Mzc+53LwgA==
```C#
public class C
{
    public string M(int i) => $"{{ {i} }}";
}
```

**Expected Behavior**:
This should produce the equivalent of `"{ " + i + " }"`.

**Actual Behavior**:
Instead it's producing the equivalent of `"{{ " + i + " }}"`.

This is a behavioral regression.

cc: @333fred

**Comment by 333fred** [comment]
It is not the job of the C# compiler to do escaping here. This is the equivalent of `string.Format("{{ {0} }}", i)`. The AppendLiteral call should be the thing handling the escape of the {{, just like string.Format would do. If we need interpolated strings to be doing the same escape rules in the compiler that string.Format does, I'm _extremely_ concerned by this as it is not part of the specification for the feature and goes well beyond the standard handling we have in the compiler here.

**Comment by stephentoub** [comment]
I completely disagree.  A key tenet of this feature is the compiler is already parsing the strings at compile-time and emitting the literals to be appended so no parsing is required at run-time.  The C# compiler needs to do the escaping.

**Comment by 333fred** [comment]
I'll send an email to LDM to get approval for a spec change here and get a PR out to change this while we wait for approval.
