### ISSUE TITLE
Source Generator cannot be created

### ISSUE THREAD

**Issue by alexrosenfeld10** [dotnet/roslyn#54710]
# Please note

This **does not happen** when running on Linux. The same exact project compiles and runs normally in any linux environment, but fails on Windows and macOS. This problem started seemingly spontaneously, and has been replicated on various `dotnet` SDK versions (including `5.0.204`, `5.0.203`, and `5.0.202`).

I have also checked out old commits in my repo that are known to have compiled on macOS and Windows in the past, and they now show the same issue. This suggests something that has changed in the NuGet packages themselves, or some other external factor.

I have also posted about this here: https://stackoverflow.com/questions/68273070/c-sharp-source-generator-cannot-be-created

**Version Used**: 
```xml
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.10.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" PrivateAssets="all" />
```

**Steps to Reproduce**:

1. Reference a source generation package like so:
```xml
    <ItemGroup>
        <ProjectReference Include="..\My.Company.ReportingModel.Generators\My.Company.ReportingModel.Generators.csproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <OutputItemType>Analyzer</OutputItemType>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="../../models/*.yaml;../../models/*.yml" />
    </ItemGroup>
```

2. Run `dotnet build`.

**Expected Behavior**:

The solution builds normally.

**Actual Behavior**:

```
Build FAILED

CSC : warning CS8032: An instance of analyzer My.Company.Generators.ReportingV2Generator cannot be created from /Users/work/dev/git/reporting-model/src/My.Company.Generators/bin/Debug/netstandard2.1/My.Company.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/Users/work/dev/git/reporting-model/src/My.Team.Models.ReportingV2/My.Team.Models.ReportingV2.csproj]

/Users/work/dev/git/reporting-model/src/My.Company.Api/SmokeTests/Tests/ContentAskExpertSmokeTest.cs(7,20): error CS0234: The type or namespace name 'Models' does not exist in the namespace 'My.Team' (are you missing an assembly reference?) [/Users/work/dev/git/reporting-model/src/My.Company.Api/My.Company.Api.csproj]
... Many more of the above "type or namespace" errors
```

**Comment by jaredpar** [comment]
Can you grab binary logs for both the builds that are succeeding and failing? Comparing them should give us an idea on what is going on here. To get a binary log just add the `/bl` option to the `dotnet build` command.

@chsienki

**Comment by alexrosenfeld10** [comment]
@jaredpar certainly.. thanks for the quick reply!! Coming right up.

**Comment by alexrosenfeld10** [comment]
Hey Jared, is there any more secure channel I can share this with you on? I can open a support ticket if need be

**Comment by alexrosenfeld10** [comment]
@jaredpar GitHub doesn't allow me to attach that file type here. Is there some other channel I can share it with you on? Happy to open a support ticket if need be.

I poked around the log myself and didn't find tons, but you will probably find more than I will. 

I would imagine you'll also ask for the logs of the succeeding build on Linux, which I am also happy to provide.

**Comment by sharwell** [comment]
@alexrosenfeld10 Change the extension from binlog to zip and it should work.

**Comment by sharwell** [comment]
@alexrosenfeld10 Keep in mind the binlog will contain all environment variables and a bunch of other data specific to your machine. I recommend submitting a feedback ticket through the Report a Problem tool (covered by Microsoft data privacy policy) instead of posting it here (public).

**Comment by alexrosenfeld10** [comment]
Thanks @sharwell . I did check that I don't have any env vars I'm worried about.

I'll open something up there, thanks for linking! You updated it literally while I was about to ask.

**Comment by alexrosenfeld10** [comment]
Thing is, this isn't a problem with VS. It's a general problem with source generators, and can be replicated outside of the IDE in a CLI setting alone.

**Comment by sharwell** [comment]
That's fine. We can link the internal report to this issue.

**Comment by alexrosenfeld10** [comment]
Ok. @sharwell I don't have Visual Studio, I use Rider / CLI... So, instead I opened one on https://my.visualstudio.com/GetHelp - the case number is 2107090040003568

**Comment by alexrosenfeld10** [comment]
unfortunately there was no way to attach a file on that case. Let me know how best to proceed here!

**Comment by jaredpar** [comment]
You can try opening a feedback issue directly and uploading there https://developercommunity.visualstudio.com/report?entry=suggestion&space=8

**Comment by alexrosenfeld10** [comment]
I tried signing in there and I get the following:

<img width="1180" alt="Screen Shot 2021-07-09 at 12 38 45 PM" src="https://user-images.githubusercontent.com/12940966/125110481-9b587c00-e0b2-11eb-98e5-51ae2f7dd479.png">

**Comment by alexrosenfeld10** [comment]
After a few tries it started working. Submitting one now...

**Comment by alexrosenfeld10** [comment]
Here's the link:

https://developercommunity.visualstudio.com/t/C-Source-Generator-cannot-be-created/1471907?entry=myfeedback&space=8

Is this private? My colleague is able to view the link without even signing in. I would just like to share these logs in a secure channel...

**Comment by sharwell** [comment]
The issue is public, but the attachment(s) are not.

**Comment by alexrosenfeld10** [comment]
got it. Uploaded as private to microsoft. Thanks. That's the failing build btw, let me know if you need the successful linux build

**Comment by alexrosenfeld10** [comment]
@sharwell @jaredpar Someone from Visual Studio support wrote to me in email about the ticket, indicating that it's opened in the wrong place. I took a guess at your Microsoft email addresses and sent on a reply. Thanks for continuing to investigate here!

**Comment by chsienki** [comment]
@alexrosenfeld10 thanks for the bin logs, super helpful. 

The error on the failure case is that the generator is dependent on `Microsoft.CodeAnalysis.dll` version `3.10`, and `3.10` only shipped in `5.0.300`. It appears that your success case is using SDK `5.0.300` but the failure case is using `5.0.204`.

You have two options to fix this:
- If you're not using any of the features introduced in `3.10` for source generators, you can lower the `Microsoft.CodeAnalysis` nuget package target to `3.9`
- Ensure that all builds are using at least `5.0.300` version of the SDK

Let me know if that fixes the build for you.

**Comment by alexrosenfeld10** [comment]
@chsienki @jaredpar @sharwell thanks a bunch! That's super helpful. This worked for me, I'm back up and running.

I use https://github.com/isen-ng/homebrew-dotnet-sdk-versions and I `brew upgrade` frequently, it seems like that tap hasn't published the newer .net 5 versions in a while. I use it to manage multiple versions (installing newer 5's uninstalls my 3's). Seems like I'll have to just deal with that for now.

You've all been helpful, thanks again.

**Comment by alexrosenfeld10** [comment]
Just curious, perhaps there's some release note I missed. Seems a bit invasive to change what binaries get shipped like this. Regardless, I'm all set now so I'll close this out.

**Comment by jaredpar** [comment]
Situation we could possibly make better when we implement #54108

**Comment by hammypants** [comment]
Still getting bit by this, and this issue was not the most straightforward to find.

Could this be annotated somewhere close to https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview ?

**Comment by sharwell** [comment]
@alexrosenfeld10 The following line from the original post is concerning as well:

> An instance of analyzer My.Company.Generators.ReportingV2Generator cannot be created from [...]/netstandard2.1/My.Company.Generators.dll

Source generators are required to target netstandard2.0. Generators targeting netstandard2.1 are not supported and are likely to not work.

**Comment by sharwell** [comment]
@hammypants @wisamidris7 This issue was fixed by #61252. If you continue having problems, it would be best to file a new issue.

**Comment by sharwell** [comment]
Duplicate of #61252

**Comment by alexrosenfeld10** [comment]
@sharwell Yeah I was tinkering around with what works / doesn't work for source generators at the time. Glad to hear the error messages and fine tuning of versions is in place!
