### ISSUE TITLE
What is the expected behavior of PEMethodSymbol.IsOverridable in Visual Basic?

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#54730]
🔗 This question is part of investigating DTS issue [AB#1352060](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1352060)

This question concerns the following code:

https://github.com/dotnet/roslyn/blob/cc047fb182d179d8e015c07cf08be38fb016607b/src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEMethodSymbol.vb#L802-L814

It appears the above implementation will interpret the following code as indicated in the comments:

```vb
Public Class A
  ' This method IS overridable because it is Virtual and NewSlot
  Public Overridable Sub M()
  End Sub
End Class

Public Class B
  Inherits A

  ' This method is NOT overridable because it is not NewSlot and the containing type has a non-null base type
  Public Overrides Sub M()
  End Sub
End Class
```

The behavior for `B.M()` differs from the same behavior for method symbols declared in source, so it's not clear if the behavior is intentional.

**Comment by cston** [comment]
> The behavior for B.M() differs from the same behavior for method symbols declared in source, so it's not clear if the behavior is intentional.

It looks like the value of `IMethodSymbol.IsOverridable` is consistent regardless of whether the types are defined in source or metadata. That is `IsOverridable` returns `True` for `A.M` and `False` for `B.M` from source and from metadata.

**Comment by sharwell** [comment]
The Visual Basic behavior seems consistent with the C# behavior:

```cs
public class A
{
    public virtual void M() { }
}

public class B : A
{
    public override void M() { }
}
```

**Comment by sharwell** [comment]
Resolving the compiler side as **By Design**.
