### ISSUE TITLE
[CA2016] Forward the CancellationToken to the method or pass 'CancellationToken.None' doesn't use the right overload for instance methods.

### ISSUE THREAD

**Issue by Kiritsu** [dotnet/roslyn#54743]
**Version Used**: 

6.0.100-preview.5.21302.13

**Steps to Reproduce**:

1. Create a class with two asynchronous methods with the same parameters and both return a Task, but the second one is generic and returns the `Task<T>`: 

```cs
public class Test
{
    private readonly HttpClient _client = new();

    public Task GetAsync(string param1, CancellationToken token = default)
    {
        return _client.GetAsync(param1, token);
    }

    public async Task<T> GetAsync<T>(string param1, CancellationToken token = default)
    {
        var response = await _client.GetAsync(param1, token);
        var stream = await response.Content.ReadAsStreamAsync(token);
        return await JsonSerializer.DeserializeAsync<T>(stream, cancellationToken: token);
    }
}
```

2. In an inner class, create a method that takes a `CancellationToken`, call the method `Test#GetAsync<T>()` without passing the CancellationToken.

```
public static Task<Program> GetAsync(string url, CancellationToken token)
{
    return Test.GetAsync<Program>(url);
}
```

3. See the analyzer giving such suggestion: 

![P410Yy19s3](https://user-images.githubusercontent.com/22667054/125159616-cc9b7f80-e178-11eb-9273-0fa9cd6d8318.png)

**Expected Behavior**:

![u0SNmsQcee](https://user-images.githubusercontent.com/22667054/125159634-ea68e480-e178-11eb-9bdf-280a6e4f93ef.png)

**Actual Behavior**:

The generic is gone.

**Important Details**:

As noticed on the `Expected Behavior` part, when the methods in the class `Test` are static, the analyser works well.

**Comment by Youssef1313** [comment]
This repository doesn't contain CAxxxx analyzers. Those rules are in dotnet/roslyn-analyzers repository. Also it looks like this was fixed in https://github.com/dotnet/roslyn-analyzers/pull/4974.

**Comment by Kiritsu** [comment]
> Those rules are in dotnet/roslyn-analyzers repository

That explains why I failed to find it in the repo, sorry and tyvm for the answer!
