### ISSUE TITLE
More dyamic (and powerful) optional parameters

### ISSUE THREAD

**Issue by hughbe** [dotnet/roslyn#5474]
Optional parameters are great for removing code bloat. They also simplify the ease of using and writing code.

Currently, optional parameters must be a compile-time constant. This is, what seems to me, to be an arbitrary restriction that results in extra code. 

Take the example below:

``` csharp
public Data(byte[] data, DataType dataType = DataType.Other)
{
    Construct(dataType, null, data, null);
}
```

This does not compile, because "the default value for 'dataType' must be a compile-time constant".
Here, DataType is a static member of a class. There are reasons for encapsulating DataType as a class instead of an enum (which would work in this example). 

This results in the following two options for this method, both creating unnecessary code bloat and possibly even complications when maintaining this code in the future:

1: Defining two methods

``` csharp
public Data(byte[] data) : this(data, DataType.Other) 
{
}

public Data(byte[] data, DataType dataType = DataType.Other)
{
    Construct(dataType, null, data, null);
}
```

2: Setting a default value that we check for and replace (e.g. null)

``` csharp
public Data(byte[] data, DataType dataType = null)
{
    if (dataType == null) 
    {
        dataType = DataType.Other;
    }
    Construct(dataType, null, data, null);
}
```

We should consider removing this restriction on optional parameters to continue C# 6's legacy of writing more powerful dynamic code with less bloat.

I'm fairly sure that this feature would not require very much work on the part of the compiler team, but please correct me if I'm wrong.

**Comment by svick** [comment]
What exactly are you suggesting? To allow any expression as the default value? In that case, when is the expression evaluated? Every time the method is called, or is there some caching involved?

**Comment by tpetrina** [comment]
C++ has constexpr now which allows for compile time expression evaluation. Maybe something like that can be used here.
Why not have both options available through custom attribute?

**Comment by hughbe** [comment]
I'm suggesting adding any expression as the default value. For example, this should work code, but it doesn't.
```csharp
public void foo(string bar = Environment.MachineName)
{
     //Use the variable bar
}

**Comment by HaloFour** [comment]
@hughbe The limitations for default parameter values are inherited from the CLR which dictates that the default values must be constants that are embedded in the assembly metadata.  The types supported by that metadata is quite limited and C# already supports the entire breadth.  In order for the C# compiler to support anything beyond that would require the compiler to deviate from how default parameters work across .NET.  One such possibility would be to emit an overload method automatically, but that would lead to potentially confusing differences in the metadata where `void foo(int bar = 0)` would be one method but `void bar(string baz = string.Empty)` would be two methods.

**Comment by aluanhaddad** [comment]
@tpetrina ```constxpr``` functions in C++ require that the function body can be evaluated at compile time. This proposal suggest System.Environment.MachineName as a default value for an optional argument. This value is by definition something which must be computed at runtime. Anyway I think expanding optional parameters is a bad idea.
