### ISSUE TITLE
Unecessary box on generic class constraint

### ISSUE THREAD

**Issue by IAmTheCShark** [dotnet/roslyn#54753]
According to https://sharplab.io/ the following method generates the following IL (Release)
```
    public bool M<T>(T value) where T : class {
        return value is null;
    }
```
```
    .method public hidebysig 
        instance bool M<class T> (
            !!T 'value'
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 10 (0xa)
        .maxstack 8

        IL_0000: ldarg.1
        IL_0001: box !!T
        IL_0006: ldnull
        IL_0007: ceq
        IL_0009: ret
    } // end of method C::M
```

Note the `IL_0001: box !!T` instruction.

I believe this is unecessary due to the class-constraint and can be removed.
Using Reflection.Emit, i created a method without this box instrcution and it seems to work fine.

**Comment by svick** [comment]
Removing the `box` instruction creates unverifiable code:

> [IL]: Error: [C::M[T]][offset 0x00000002][found (unboxed) 'T'] Non-compatible types on the stack.

Considering that [the generated machine code for this method does not do any boxing](https://sharplab.io/#v2:C4LghgzgtgPgAgJgAQGECwAoA3ppekBGA9kQDZICyAPACoB8AFDUgG5ikCuApgJRIDuACy4AnLkmYgkiJDgz4F0gOyt23JAEsISAHYdSpANy58AXxN4LhEuQoMiBAFZcAxsCRE+AXjqUqD5zdGT2MMUyA===), I don't see a reason to change anything here.

**Comment by IAmTheCShark** [comment]
> Removing the `box` instruction creates unverifiable code:
> 
> > [IL]: Error: [C::M[T]][offset 0x00000002][found (unboxed) 'T'] Non-compatible types on the stack.
> 
> Considering that [the generated machine code for this method does not do any boxing](https://sharplab.io/#v2:C4LghgzgtgPgAgJgAQGECwAoA3ppekBGA9kQDZICyAPACoB8AFDUgG5ikCuApgJRIDuACy4AnLkmYgkiJDgz4F0gOyt23JAEsISAHYdSpANy58AXxN4LhEuQoMiBAFZcAxsCRE+AXjqUqD5zdGT2MMUyA===), I don't see a reason to change anything here.

Interesting, so i guess Reflection.Emit doesn't care then. Ok, thank you for the clarification.
