### ISSUE TITLE
AssemblyInfo's using conflicting with C# 10's global usings

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/roslyn#54752]
I target netstandard 2.0 which generates `AssemblyInfo.cs`. It has `using`s in it, but because I added a global using for System in my project, it complains about the file having it

<details><summary><b>Screenshot</b></summary>
<img src="https://user-images.githubusercontent.com/31178401/125191362-a34b2400-e24a-11eb-9a16-8d633df4c7ec.png"/>
</details>

How should we approach this? Maybe I'm missing something?

SDK Version: 6.0.100-preview.7.21360.1

**Comment by Youssef1313** [comment]
See the last bit of this [LDM](https://github.com/dotnet/csharplang/blob/70fc3eb70379d5618ca9d2ae2dc897e02b92b678/meetings/2021/LDM-2021-06-21.md#email-decision-duplicate-global-using-warnings):

> ### Email Decision: Duplicate global using warnings
>
> Some early feedback on global usings has suggested that duplicated using warnings can be painful, particularly if a global using and
> a non-global using are duplicated. Code generation can very easily run into this scenario, and it doesn't have an easy resolution.
> After discussion, we decided to remove the duplicated using warning for when a global using directive or a regular using directive are
> duplicated. The compiler will still issue a hidden diagnostic to inform the IDE and analyzers, but there will be no user-facing warning
> by default. We will still error when the same alias is defined more than once, even if the alias refers to the same type, as we feel
that aliases are more like declarations and we believe declarations should be intentional.
>
> #### Conclusion
>
> Duplicate using warning is removed when a global using is duplicated by another using (global or otherwise).

**Comment by WhiteBlackGoose** [comment]
Thanks, is it done yet?

**Comment by Youssef1313** [comment]
@WhiteBlackGoose Probably it's https://github.com/dotnet/roslyn/pull/54220?

**Comment by WhiteBlackGoose** [comment]
Thanks. Seems like that the SDK hasn't got an update with that merge yet, that's why I'm still facing it.
