### ISSUE TITLE
[Source Generator] Syntax highlighting partially broken by SyntaxReceiver

### ISSUE THREAD

**Issue by Veilenus** [dotnet/roslyn#54768]
I wanted to get into Roslyn Source Generators and had some fun with the [SourceGeneratorTemplate](https://github.com/davidwengier/SourceGeneratorTemplate), just to get started. After a short while I noticed a problem I was not able to fix: Visual Studio's syntax highlighting seems partially broken by the generator, particularly by registering an `ISyntaxReceiver` (or `ISyntaxContextReceiver` which produces the same bug). Removing the `SyntaxReceiver` brings back the expected syntax highlighting, but renders my generator useless.

My demo generator's purpose is to generate a class (`GeneratedClass`) with a single method that returns the number of members of an inspected class (`UserClass`). The original "SourceGeneratorTemplate" has been stripped down in order to provide a minimal reproducible example.

I'm not sure whether this is a bug within Roslyn, Visual Studio or something else entirely. Please excuse me if this issue doesn't belong here. This is just my best guess.

**Version Used**: 
- Visual C# Compiler version 3.10.0-4.21318.11 (7ceb6331)
- Visual Studio Enterprise 2019 16.10.3

**Steps to Reproduce**:

1.  Download and build the following solution: [SyntaxHighlightingBug.zip](https://github.com/dotnet/roslyn/files/6801952/SyntaxHighlightingBug.zip).
2. Restart Visual Studio to wire up the source generator (as is documented).
3. Add an arbitrary member to `UserClass`.
4. Open `Program.cs` and modify code. Type in some syntax errors and remove them. Keep an eye on the syntax highlighting.

**Expected Behavior**:
- Classes, instances thereof and their respective members should be highlighted accordingly, at a minimum after removing all syntax errors.

**Actual Behavior**:
- Classes that are defined in the same project that references the source generator are not highlighted reliably. It's a hit and miss, even after removing all syntax errors.
![highlighting bug](https://user-images.githubusercontent.com/67912689/125301577-673bc000-e32b-11eb-8b5b-2ca3aa46ed60.gif)

**Comment by huoyaoyuan** [comment]
I'm also observing this after adding SG to my project, and did not test the detailed repro condition.

**Comment by sharwell** [comment]
@Veilenus I see that **SourceGenerator.csproj** has the following:

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.10.0" />
```

This isn't the right package reference for a source generator. Can you try changing it to the following and let us know if the problem still occurs?

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.10.0" PrivateAssets="all" />
```

**Comment by Veilenus** [comment]
Hi Sam, thank you very much for your assistance, it's much appreciated! I've replaced the wrong package reference with the once suggested and the source generator's project file now looks as follows:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.10.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
```
I did also clean and rebuild the solution and restart Visual Studio several times after changing the package references. **Unfortunately, the problem still occurs.** The observed behavior is pretty much the same as depicted in the gif above.

**Comment by Veilenus** [comment]
Update: Upgrading to Visual Studio Enterprise 2022 17.0.0 seems to have solved the problem for me.
