### ISSUE TITLE
variables not shown in completion items after list.Count < 

### ISSUE THREAD

**Issue by pawchen** [dotnet/roslyn#54765]
**Version Used**: 16.11.0 Preview 2.0

**Steps to Reproduce**:

```C#
using System.Linq;

var b = 0;
List<int> a;
if (a.Count < $$
```

**Expected Behavior**: `b` should be included in the completion list.

**Actual Behavior**: `b` is not shown

I guess the `Count<T>` extension method in `System.Linq` caused intellisense to only show completion items for `T`

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/54107.

**Comment by pawchen** [comment]
Thanks, I'll close this one.
