### ISSUE TITLE
TestHostDocument doesn't support multiple positions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54762]
https://github.com/dotnet/roslyn/blob/67dafdb5a37b96be2422fa72494dddf9f4f6f954/src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs#L783-L784

https://github.com/dotnet/roslyn/blob/67dafdb5a37b96be2422fa72494dddf9f4f6f954/src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs#L797-L798

Instead of `GetPositionAndSpans`, I want to use `GetPositionsAndSpans`, but `TestHostDocument` doesn't accept multiple positions. This blocks adding a test for https://github.com/dotnet/roslyn/pull/54741.

@sharwell

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this is needed for some pr, then just make the change in that pr to support this.

Also, we tend to just support this by having many `[||]` markers int he code.  Or something like `{|caret:|}` Would want to know why that's not ok here)
