### ISSUE TITLE
Proposal: Builder method prototypes syntactical pattern

### ISSUE THREAD

**Issue by JesperTreetop** [dotnet/roslyn#5476]
More and more often, builders or builder-like methods are used to accumulate state or configuration in objects. For code clarity reasons, it is desirable to have batch methods, similar to `AddRange`, but unless the method for the single only takes one value (where `params` is sufficient), providing a batch method means packaging up the parameters in an object or dropping down into `object[]` and sorting out the parameters yourself, something which is rarely ever done. Essentially, you fall off the cliff of C#'s type system's static typing, because there's no syntax to describe the method usage pattern.

For example, given this method:

``` C#
public void AddHandler<T>(string key, Action<T> handler) { ... }
```

there's no way of defining a variadic "Range"/batch method:

``` C#
public void AddHandlers(/* ??? */) { ... }
```

Both macros and a beefier type system have been proposed in the past, but they would be huge investments and require significant design and prototyping work. However, the C# design team has talked about liking the idea of metaprogramming and wanting the community to feel around for a good approach more than wanting to impose one. So here's a proposal in that vein.

I am proposing **builder method prototypes** to solve this localized class of problem. They are a syntactical pattern, [somehow](http://star.psy.ohio-state.edu/coglab/Miracle.html) exposed in library metadata (if public) and used by the compiler to rewrite a single invocation into multiple invocations, similar to a more flexible version of collection initializers.

For example, a builder method prototype could be defined as such:

``` C#
public builder AddHandlers(using AddHandler<>...);
```

allowing this code:

``` C#
AddHandlers({"x", (string str) => Console.WriteLine($"handled x case: {str}")},
            {"y", (int num) => => Console.WriteLine($"handled y case: {num}")});
```

to be translated by the compiler into this code:

``` C#
AddHandler<string>("x", (string str) => Console.WriteLine($"handled x case: {str}"));
AddHandler<int>("y", (int num) => => Console.WriteLine($"handled y case: {num}"));
```

Another use, without generics, is:

``` C#
public builder AppendRange(using Append...);

public void Append(string str) { .. }
public void Append(string str, int startIndex, int length) { .. }

AppendRange({"x"}, {"1234256789", 3, 2});

// translated into

Append("x");
Append("1234256789", 3, 2);
```

And another use:

``` C#
public builder RegisterGenericHandlers(using RegisterGenericHandler<>...);
// providing T here would lock the pattern matching to a single T

public void RegisterGenericHandler<T>(Action<T> t);

StringHandler strh;
IntHandler inth;
DecimalHandler dech;
RegisterGenericHandlers({strh}, {inth}, {dech});
// this would have been impossible with RegisterGenericHandlers<T>(params Action<T> ts)
// because the T would not have agreed for every use.
```

Each "invocation group" is delimited with curly braces, mapping to the individual calls like the groups in collection initializers map to pattern-matched `Add` calls. This is to avoid costly resolution and disambiguation of the parameter list - mostly for the programmer for reasons of clarity. As with collection initializers, the braces can be left out for a single invocation.

The `builder` keyword signifies a builder method prototype. No method `AddHandlers` is ever exposed in metadata, but the prototype is exposed for consumers of this library. As such, the prototype never has an implementation and does not show up in reflection. It is a compile-time construct, albeit one whose scraps are left around for library consumers, like `ExtensionAttribute` for extension methods.

The `using` keyword signifies a method group, constrained wholly or partially or entirely unconstrained by generics.

The `builder` keyword appears instead and in place of a return type. Every invocation group inside a builder invocation must agree on a compatible return type, using logic similar to the ternary operator, except also allowing `void`. If no return type is found, a compiler error is issued.

The return type of a builder depends partly on its use and partly on the methods; it can be `void` or a common type.

``` C#

public builder Builder(using SpecificMethod...);

// expansion if the return types of all the SpecificMethod methods are void
x.Builder({"a"}, {"b"}, { 42 }, {"c"};

x.SpecificMethod("a");
x.SpecificMethod("b");
x.SpecificMethod(42);
x.SpecificMethod("c");

// expansion if the return types of all the SpecificMethod methods are any other types
var finalResult = x.Builder({"a"}, {"b"}, { 42 }, {"c"};

var __firstResult = x.SpecificMethod("a");
var __secondResult = __firstResult.SpecificMethod("b");
var __thirdResult = __secondResult.SpecificMethod(42);
var finalResult = __thirdResult.SpecificMethod("c");
// the names of any of the __-variables being unmentionable, per usual
```

The return type, if not `void`, is assumed to behave and have the semantics of an accumulated-style builder. This will be deliberately incompatible with methods that return entirely different values. Chaining those methods would be the wrong thing in the first place, and this proposal does not intend to make that the right thing.

In general, the answer to any question is "how does collection initializers do it"? For example, extension methods are in scope to satisfy the method group, since they are to satisfy the search for an Add method in a collection initializer, even though the expression is not of the form `*something*.Add`. Since methods can be anticipated to be added for compatibility, this sounds like a useful default.

One last part that I'm still unsure about is a small extension allowing prefix matching of the method group combined with named parameters. This could be very useful. For example, both "withers" and "configurers" could be made eminently compatible.

``` C#
public builder WithRange(using With*...);
// ending with star meaning:
// consider all the methods starting with "With",
// match the particular method not just from the types but also the parameter names
// any ambiguity is a compile-time error

var ratherMoreHoopyFrood = immutablePerson.WithRange({firstName:"Arthur"}, {lastName:"Dent"}, {strag:false});
```

Withers may benefit from separate optimizations for other reasons, though - this is just a syntactical proposal.

**Comment by dsaf** [comment]
> Both macros and a beefier type system have been proposed in the past, but they would be huge investments and require significant design and prototyping work. ... I am proposing builder method prototypes to solve this localized class of problem...

I would prefer to see *use-site variance* / *call site covariance* instead of a tactical workaround.

http://stackoverflow.com/questions/19283349/c-sharp-generics-wildcards

https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Use-site_variance_annotations_.28Wildcards.29

**Comment by gafter** [comment]
@dsaf As the original proponent and primary implementer for use-site variance in Java, based on my experience I would not impose that complexity on a language again.

**Comment by dsaf** [comment]
@gafter was it complex to implement or complex to use?

**Comment by gafter** [comment]
Very complex and confusing to use. APIs must be written to allow clients to take advantage of it, and then all clients of those APIs are forced to deal with the complexity.

**Comment by JesperTreetop** [comment]
At least this proposal would be a layer on top that you could choose to use, and you could add the layer to other people's code.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
