### ISSUE TITLE
Color classification viewer for VS

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#54776]
Currently in VS in order to tell which Classification is being applied to a particular piece of text you need to either already know or have a good guess which of the items on the long list would apply in that case or do some trial and error on the classification by changing colors and seeing which one affects the given text.

A better way to handle these User Customization (and even VS extension developer scenarios) might be to have a "Classification Viewer", which allows you to hover over a piece of text and see the name of the Classification (and hopefully its source) . VSCode has something like this in its `Developer: Inspect Editor Tokens and Scopes` feature

CC @mikadumont

**Comment by JoeRobich** [comment]
a VS extension exists that helps with this issue https://marketplace.visualstudio.com/items?itemName=ryzngard.carnation-colorpicker

**Comment by jinujoseph** [comment]
This would be a platform feature @mikadumont

**Comment by CyrusNajmabadi** [comment]
Closing as there is an extension for this and this is better served as a platform feature.
