### ISSUE TITLE
SkipAnalyzers=true has no effect on the XamlPreCompile target and still results in analyzer warnings.

### ISSUE THREAD

**Issue by jlaanstra** [dotnet/roslyn#54774]
**Version Used**: VS 2019 Update 10.3

**Steps to Reproduce**:

1. Create a new WinUI 3 project with a xaml file in it.
2. Add some code that gets flagged by analyzer.
3. Add ```<SkipAnalyzers>true</SkipAnalyzers>```

**Expected Behavior**:
No warnings from analyzers.

**Actual Behavior**:
Warnings from analyzers show up.

This is most likely because the _ComputeSkipAnalyzers targets runs before CoreCompile but not before XamlPreCompile.

**Comment by jaredpar** [comment]
@chsienki is this a bug we should move over to WPF?

**Comment by jlaanstra** [comment]
https://github.com/dotnet/sdk/issues/17890 seems related as it has similar problems of a target not running before XamlPreCompile.
