### ISSUE TITLE
[Regression] Resolve using no longer shows up in certain contexts

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#54783]
**Version Used**: 
Version 17.0.0 Preview 3.0 [31509.305.main]

**Steps to Reproduce**:

1. CTRL+. at $
``` C#
using System;

namespace ConsoleApp202
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        private static Task<string>$
    }
}

```
**Expected Behavior**:
VS 2017:
![image](https://user-images.githubusercontent.com/1103906/125368344-62bfe780-e3bd-11eb-8b9c-e2e1c737ccdb.png)

VS 2019:
![image](https://user-images.githubusercontent.com/1103906/125368517-b7fbf900-e3bd-11eb-91c0-0435c0578912.png)

**Actual Behavior**:
VS 2022:
![image](https://user-images.githubusercontent.com/1103906/125368377-6eaba980-e3bd-11eb-8d4f-60f921b37f88.png)

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  this was due to async lightbulb change ?

**Comment by CyrusNajmabadi** [comment]
Yes.  this was fixed with https://github.com/dotnet/roslyn/pull/54771
