### ISSUE TITLE
Suggestion to upgrade to C# 9 is hiding true error

### ISSUE THREAD

**Issue by adegeo** [dotnet/roslyn#54793]
**Version Used**:
- _SDK:_ 6.0.100-preview.4.21255.9
- _PROJECT:_ NET 3.1

**Steps to Reproduce**:

```csharp
using System;

namespace ConsoleApp6
{
    class Program
    {
        static void Main(string[] args)
        {
            bool check1 = false;
            bool check2 = true;
            int value1 = 1;
            int value2 = 2;

            // ERROR HERE. These should be (int?)null instead of null
            TestMe(check1 ? null : value1, check2 ? null : value2);
        }

        static void TestMe(int? value1, int? value2)
        {

        }
    }
}

```

**Expected Behavior**:

The true error should be revealed:

> error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between '<null>' and 'int'

**Actual Behavior**:

Error is covered by a suggestion to upgrade to C# 9

> error CS8370: Feature 'target-typed conditional expression' is not available in C# 7.3. Please use language version 9.0 or greater.

**Comment by RikkiGibson** [comment]
Maybe instead of a generic LangVersion diagnostic we could provide a diagnostic that prompts an upgrade but also includes information on why a "best common type" couldn't be found for the conditional expression.

**Comment by adegeo** [comment]
@RikkiGibson My original project was multitargeting, so I couldn't upgrade because I was building a nuget package that had binaries for NET 3.1/Standard 2.1/NET 5

**Comment by RikkiGibson** [comment]
I was thinking of something like the following:

`Type of conditional expression cannot be determined because there is no implicit conversion between '<null>' and 'string'. To use a target-typed conversion, upgrade to language version 9.0 or greater.`

**Comment by RikkiGibson** [comment]
If a target-typed conditional expression conversion is used we can assume that there was no best common type. So I think we might be able to just grab the natural types of the conditional expression arms, feed them into the diagnostic and get the behavior we want.
