### ISSUE TITLE
MSBuildWorkspace.OpenProjectAsync cannot locate Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by kfertitta** [dotnet/roslyn#54796]
**Version Used**:   4.0.0-1.final

**Steps to Reproduce**:

1.   Create a minimal Roslyn console app with the following code:

```
        static async Task Main(string[] args)
        {
            using (var workspace = MSBuildWorkspace.Create())
            {
                var project = await workspace.OpenProjectAsync(... filePath...);

                var diagnostics = workspace.Diagnostics;
           }
        }
```

and the following project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="16.10.0" />
    <PackageReference Include="Microsoft.Build.Framework" Version="16.10.0" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="16.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.0.0-1.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.0.0-1.final" />
  </ItemGroup>
  
</Project>
```

2.  Create a C# class library project with a single source file in it with a single empty class and a project file like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

</Project>
```

3.   Use the C# class library project file as the parameter to `OpenProjectAsync`.

4.   Build and run.

**Expected Behavior**:
The `OpenProjectAsync` call should successfully open the project without any diagnostics reported.

**Actual Behavior**:
After invoking `OpenProjectAsync`, the workspace reports a diagnostic:
"The SDK 'Microsoft.NET.Sdk' specified could not be found."

The test VM where this repros is a Win10 machine with Dev 17 Preview 1.1.  Checking the installed SDKs, reports the following:

```
C:\Users\Kirk\Documents\Visual Studio 2022\Projects>dotnet --list-sdks
6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
```

This same arrangement works fine on a VS2019 test VM which reports the following SDKs installed:
```
C:\Users\Kirk\Documents\Visual Studio 2019\Projects>dotnet --list-sdks
5.0.301 [C:\Program Files\dotnet\sdk]
```

**Comment by JoeRobich** [comment]
@kfertitta Will this tool be run on a machine with VS or VS Build Tools installed? If so, I would recommend using [MSBuildLocator](https://www.nuget.org/packages/Microsoft.Build.Locator/) to load the Build assemblies.

Program.cs
```csharp
        static async Task Main(string[] args)
        {
            MSBuildLocator.RegisterDefaults();
            using (var workspace = MSBuildWorkspace.Create())
            {
                var project = await workspace.OpenProjectAsync(... filePath...);

                var diagnostics = workspace.Diagnostics;
           }
        }
```

Need to add a package reference for MSBuildLocator and update the Microsoft.Build dependencies so that they are not deployed and instead resolved at runtime.

console.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="16.10.0" ExcludeAssets="Runtime" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Framework" Version="16.10.0" ExcludeAssets="Runtime" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="16.10.0" ExcludeAssets="Runtime" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.4.1" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.0.0-1.final" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.0.0-1.final" />
  </ItemGroup>
  
</Project>
```

**Comment by kfertitta** [comment]
Thanks @JoeRobich  for the quick reply.  Indeed, our tooling is a large VS extension, so the "real" code will obviously always be running within a full VS install.  Using the `MSBuildLocator` as you suggested does make the above example work, so thank you for that.  It's odd that it isn't required in Dev16 or Dev15, however.

Given that this needs to work within our VS extension, is this still the right approach?  I suspect if I blindly add a `PackageReference` to `Microsoft.Build.Locator` to my VSIX, then it will fail to load when I run my VSIX unless I actually deploy it with my extension.  That sorta feels "wrong".

**Comment by JoeRobich** [comment]
@kfertitta I can't really speak to what the difference could be. The MSBuildWorkspace simply uses the MSBuild instance that is loaded into memory and the environment variables that are configured to load projects. 

If you choose to add a reference to Microsoft.Build.Locator, you will certainly want to deploy the locator assembly with your VSIX. The locator package will take care of loading the Microsoft.Build assemblies for you from the existing MSBuild install, that is why they are not needed in your deployment. This snippet from the MSBuildLocator repo may explain the benefits better

> ...it's generally not enough to be able to load some MSBuild project: you want your application to be able to load the .csproj, .vbproj, .fsproj, .sqlproj, .ccproj and other project types that you can build in Visual Studio (or Visual Studio Build Tools) or with the .NET SDK. To do that, you need more than just MSBuild's assemblies--you must also have access to all of the SDKs and build logic that are imported into those projects.
>
> That additional build logic is distributed with Visual Studio, with Visual Studio extensions, or as part of the .NET SDK. So to correctly load projects, you need to load them in the context of one of those MSBuild installations.

**Comment by kfertitta** [comment]
Thanks @JoeRobich .  Makes sense.  I'll integrate the `MSBuildLocator` with our VSIX and give it a go.

**Comment by kfertitta** [comment]
@JoeRobich Seems I can't get in "early" enough during the loading process, which I sorta would expect running within VS itself.  Here's the exception thrown when `RegisterDefaults` is called:

```
Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
This dependency arises from when a method is just-in-time compiled, so if it breaks even if the reference to a Microsoft.Build type has not been executed.
For more details, see aka.ms/RegisterMSBuildLocator
Loaded MSBuild assemblies: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by JoeRobich** [comment]
@kfertitta Ah, that makes sense. I didn't think about how you are running inside VS and how it would already have loaded MSBuild for you. I don't think you need MSBuildLocator at all for your extension. Are you still running into this issue with locating the SDK?

**Comment by JoeRobich** [comment]
@kfertitta Please let us know if this is still an issue for you. Thanks

**Comment by kfertitta** [comment]
Hi @JoeRobich 

Thanks very much for the follow-up and really sorry for the delayed reply.  Been out for a while.

Indeed, we've managed to get this working now -- not sure if something changed, but we've charged ahead.

I'll close this out.

Thanks for your help.
