### ISSUE TITLE
IFieldSymbol is missing API to retrieve fixed-sized buffer size

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#54799]
```C#
struct S { public unsafe fixed byte Buffer[123]; }
```

Get `123` from a symbol that represents field `Buffer`.

**Comment by 333fred** [comment]
The proposal here would be to expose https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Symbols/FieldSymbol.cs#L104-L110, which currently exists on `FieldSymbol` but not on `IFieldSymbol`. As we already have `IFieldSymbol.IsFixedSizeBuffer` publicly exposed, I think that it would be fine to just expose this API as-is with no further changes.

**Comment by 333fred** [comment]
## API Review

Approved.
