### ISSUE TITLE
C#: VS Uncomment selection command doesn't work if character sequence "/*" is found in a triple slash comment

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#548]
Ported from TFS WorkItem: **999122**

------------------------------

**Repro Steps:**

**Affected Branch:** WPT<BR>**Affected Build:** 21916.00<BR><BR>**Steps to reproduce:**<BR><BR>1. Put the follwing in a C# class:
<FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>

///</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>&lt;include</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>file='doc\Control.uex'</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>path='docs/doc[@for="Control.RtlTranslateAlignment1"]/*'</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>/&gt;

///</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>&lt;devdoc&gt;

///</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>&lt;para&gt;</FONT></FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>[To be supplied.]</FONT></FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>&lt;/para&gt;

///</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT color=#000000 size=2 face=Consolas> </FONT></FONT><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas><FONT color=#808080 size=2 face=Consolas>&lt;/devdoc&gt;
</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>

</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>protected</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>void</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> RtlTranslateAlignment2()

{

</FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>//int x = 0;
</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>

}

</FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>/* Hello world */
</FONT></FONT></FONT>

&nbsp;

2. Select the line with "//int x = 0;

3. Edit\Advanced\Uncomment Selection

&nbsp;

EXPECTED: Line is uncommented

ACTUAL: Line is uncommented, but "/*" is removed from the triple slash comment line with the include tag, and the closing "*/" is removed after "Hello World".&nbsp; Code no longer compiles.

**Comment by srivatsn** [comment]
Tagging @dsplaisted who created the TFS bug.

**Comment by alexsorokoletov** [comment]
>uncomment selection is currently only textual and needs to be made syntactic to fix that.
@Pilchie

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/5000
