### ISSUE TITLE
Warn when "attribute-dependent" types are used in 'typeof'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#54804]
Currently the 'typeof' operator gives an error when certain types which can't round-trip are used as arguments. For example, `dynamic` or `string?`.

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4GIYFcA2OLA4CmABETAcQLABQtAAgAwn0CMALANy20D6JAXhIwiAdwDaAXRIBvWiQUkALgE8ADkQD2AMwAUm4ACsiAYyUBKOCQD01kpoDW8xao07dCFRTBQTlm3ZEAE5BmkEkAMIAyqwAnABsAEwgJAAqABakrlra9hpBEEphJCYQMDCaSiTApFgAzkQI9jDKmSSe3r7K6kTOCtnubIwA/P62ZCHF0QAc8QDMsSkZWT06ecGFxaXlldW1DU2aLRDCuPiEpEFE2sHkJisafd1uegAyUHVKADwdED4mAD4xnYKhNQkEngM3h9vkNhkCrONQcFwZDVnpdLAqhArFjquZzAFhJowWFaABfThAA==)
```cs
#nullable enable

using System.Collections.Generic;

_ = new[] {
    typeof(object), // ok
    typeof(dynamic), // error CS1962: The typeof operator cannot be used on the dynamic type
    typeof(string?), // error CS8639: The typeof operator cannot be used on a nullable reference type
    typeof(List<dynamic>), // no error
    typeof(List<string?>), // no error
    typeof((int a, int b)) // no error
};
```

It feels like the lines marked `no error` should be errors because the types in use can't round trip. Since it's not practical to add new errors to existing code, these scenarios should probably be handled in a warning wave.

Generic attribute type arguments have a similar issue where they can't round-trip types which require extra attributes. It feels like the same restriction should be applied there, but perhaps as an error since it's a new feature. #54778

**Comment by cston** [comment]
Also:
```csharp
_ = typeof(nint); // no error
```

**Comment by jaredpar** [comment]
FYI: this ended up causing a couple hundred warnings in dotnet/runtime when they took a new compiler due to `typeof(nint)` / `typeof(nuint)` usage. Making me reconsider how far we went with this warning.

**Comment by RikkiGibson** [comment]
It occurs to me that the diagnostic message could be more useful. For example, it could suggest the underlying type to use instead.

**Comment by RikkiGibson** [comment]
Similar to dotnet/runtime#64654, I'd like to implement this in the compiler but also ship a code fixer somewhere for it.
