### ISSUE TITLE
Lightbulb actions take a really long time to appear in LSP Editor

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#54809]
**Version Used**: 
Visual Studio 2022 Int Preview

**Steps to Reproduce**:

1. Enable the Preview LSP editor.
2. Open a large C# solution, such as Editor.sln.
3. Invoke Ctrl+. (lightbulb) on a using.

**Expected Behavior**:
Lightbulb actions appear in a second or two.

**Actual Behavior**:
Lightbulb actions can take 5-10 seconds to appear.

Note that because this is the LSP editor specifically, it probably only really impacts customers via LiveShare guest.

**cc: ** @dibarbet

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of reports.  We can track perf through normal LSP dashboards and traces.
