### ISSUE TITLE
Quick info in C# interactive no longer appears

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54816]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-info-in-C-interactive-no-longer-a/1472887)._

---
[regression] [worked-in:16.9]
After upgrading to a certain version of VS 2019, the Quick Info in C# Interactive window no longer appeared.
Please see whether this is a bug.

---
#### Mila Zhou[MSFT] on 7/12/2021, 07:47 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen?  It would be very helpful if you could provide some screenshots of this problem.</p>
<p>We look forward to hearing from you!</p>

#### WMJ on 7/13/2021, 02:24 AM: 

<ol>
<li>Open VS 2019.</li>
<li>Open C# Interactive view.</li>
<li>Type “Console.WriteLine” in the windowpane.</li>
<li>Move the mouse over “WriteLine”.</li>
<li>Nothing appears.</li>
</ol>
<p>Expected result: Quick Info displaying documentation for method “WriteLine”.</p>

#### Feedback Bot on 7/13/2021, 04:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
It seems quick info works fine in 17.1
![image](https://user-images.githubusercontent.com/788783/141522032-c18403ea-3c17-4937-8984-8b200a9889b4.png)

**Comment by wmjordan** [comment]
It was working on VS 2022, but not on **VS 2019**.

**Comment by genlu** [comment]
@wmjordan Unfortunately, we are unable to ship a fix for this issue in VS 2019. At this point, only fix for critical bugs (e.g. security, reliability, etc.) will meet the bar for a servicing release.

**Comment by wmjordan** [comment]
Thank you for the explanation. Well, I accept it.
