### ISSUE TITLE
VB 2019 no longer supports XML intellisense in literals

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54815]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VB-2019-no-longer-supports-XML-intellise/1295129)._

---
[severity:It's more difficult to complete my work]
After reopening an older project where I use XML with the System.Xml namespace (XDocument, XElement) the intellisense for XML elements is no longer working. Before, this part of code was written with VS 2015 and when I wrote "myDocument.**

---
#### Feedback Bot on 12/23/2020, 06:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/22/2021, 11:51 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Xiaolin Zhang [MSFT] on 6/15/2021, 01:41 AM: 

<p>Thank you for taking the time to log this issue!<br>
Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ? If so, in order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool. For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed</a>.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a> , you can get tips on how to provide clear and simple reproducible steps.<br>
We look forward to hearing from you!</p>

#### Patrick Simons on 6/15/2021, 05:37 AM: 

<p>With VS 16.10.1 it still doesn’t work.</p>
<p>I use this:</p>
<pre><code>Friend Function SetNamespace(ByVal source As XDocument, ByVal xNamespace As XNamespace) As XDocument
        ' cfr. https://ludwigstuyck.wordpress.com/2009/03/31/modifying-namespace-in-xml-document-programmatically/

        For Each xElement As XElement In source.Descendants()
            ' First make sure that the xmlns-attribute is changed
            xElement.SetAttributeValue("xmlns", xNamespace.NamespaceName)
            ' Then also prefix the name of the element <span class="hljs-keyword">with</span> the namespace
            xElement.Name = xNamespace + xElement.Name.LocalName
        <span class="hljs-keyword">Next</span>
        <span class="hljs-keyword">Return</span> <span class="hljs-keyword">source</span>
    <span class="hljs-keyword">End</span> <span class="hljs-keyword">Function</span>
</code></pre>
<p>In the main function (simplified):</p>
<pre><code><span class="hljs-attr">Dim</span> <span class="hljs-string">docMyStat As XDocument = XDocument.Load(srcPathFile)</span>
<span class="hljs-attr">Dim</span> <span class="hljs-string">schemaMyStats As New XmlSchemaSet()</span>
<span class="hljs-attr">...</span>
<span class="hljs-meta">docMyStat.Validate(schemaMyStats,</span> <span class="hljs-string">Nothing)</span>
<span class="hljs-attr">...</span>
<span class="hljs-attr">docMyStat</span> = <span class="hljs-string">SetNamespace(docMyStat, "https://tempuri.org/mySample.xsd")</span>
<span class="hljs-attr">Dim</span> <span class="hljs-string">sClientID As String = docMyStat.&lt;Document&gt;.@ClientID</span>
<span class="hljs-attr">Dim</span> <span class="hljs-string">sBuId As String = docMyStat.&lt;Document&gt;.&lt;BU_List&gt;.&lt;BU&gt;.@BuId</span>
</code></pre>
<p>So in the editor editing “docMyStat.&lt;Document&gt;.&lt;BU_List&gt;.&lt;BU&gt;.@BuId”, typing one of the dots doesn’t open an intellisense pop-up.</p>
<p>Patrick</p>

#### Xiaolin Zhang [MSFT] on 6/16/2021, 02:13 AM: 

<p>I’m glad to hear from you. According to your feedback, I suggest you update to version 16.10.2, because fixed. ASPX / ASCX files where users may see include IntelliSense or experience slow performance has been fixed in version 16.10.2</p>

#### Patrick Simons on 6/16/2021, 04:46 AM: 

<p>Hi Xiaolin,</p>
<p>I tried 16.10.2 - still the same problem.</p>
<p>normal behavior on a sample class: after typing the dot, a pop-up opens with two member properties PosNr and ShiftNr:<br>
<img src="https://aka.ms/dc/image?name=B851c1ae88af842fb93f90de7a5964592637594401976617810_20210616-133636-image.png&amp;tid=851c1ae88af842fb93f90de7a5964592637594401976617810" alt="image.png"></p>
<p>Taking this example:<br>
<img src="https://aka.ms/dc/image?name=Bf88c079c58f8489aa97ff9e10f3a262e637594399396633334_20210616-133219-image.png&amp;tid=f88c079c58f8489aa97ff9e10f3a262e637594399396633334" alt="image.png"></p>
<p>the XML-Intellisense doesn’t work, the member &lt;Document&gt; does not appear in the pop-up windows:<br>
<img src="https://aka.ms/dc/image?name=B603d11fe17cc40e4852f120155cfd8c2637594403478348131_20210616-133906-image.png&amp;tid=603d11fe17cc40e4852f120155cfd8c2637594403478348131" alt="image.png"></p>
<p>This worked in VB 2015.</p>
<p>Thanks,<br>
Patrick</p>

#### Feedback Bot on 7/13/2021, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We are not planning on bringing this back.  It was a known thing pulled from roslyn.
