### ISSUE TITLE
Microsoft.CodeAnalysis is missing from 6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\codestyle

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn#54829]
Recently I started getting thousands of build warnings to the effect of:

```
warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer 
cannot be created from C:\Development\winforms\.dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll 
: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The system cannot find the file specified.
```

![image](https://user-images.githubusercontent.com/4403806/122498423-708a8300-d032-11eb-8684-723b518676b9.png)

To reproduce 
1. clone the latest https://github.com/dotnet/winforms/
2. `.\start-vs.cmd`
3. F5

**Comment by marcpopMSFT** [comment]
not sure if roslyn or roslyn-analyzers repo.

**Comment by JoeRobich** [comment]
@RussKie Are you using VS2019 when you see the errors? It is possibly related to #53707.

**Comment by RussKie** [comment]
I may have been... On Dev17 now, and I don't think I've seen these again.

**Comment by RussKie** [comment]
Reopen if see them again
