### ISSUE TITLE
Memory usage of roslyn

### ISSUE THREAD

**Issue by overeemm** [dotnet/roslyn#5482]
I'm using the following snippet to produce dll's from in-memory strings (representing C# files). 

    CSharpCompilation compilation = CSharpCompilation.Create(assemblyName,
        syntaxTrees: trees,
        references: references,
        options: new CSharpCompilationOptions(
          OutputKind.DynamicallyLinkedLibrary,
          optimizationLevel: OptimizationLevel.Debug
          )
        );

      EmitResult result = compilation.Emit(outputDllPath, pdbPath: $"{Path.ChangeExtension(outputDllPath, "pdb")}");

After this code has run, I use the memory profiler (the vs2015 one) to look at the heap. I see that lot's of Roslyn related files are sticking around (mainly objects from Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.*).

Is there a way to prevent this? And should I try to prevent this, or is there caching involved that improves the speed of compiling? I've done some testing with doing the parsing and compiling in a separate appdomain for every dll. This helps in garbage collection, but it seems wrong.

**Comment by KevinH-MS** [comment]
I do not *believe* there are any static caches in the compiler that would result in this behavior.

It seems most likely that your program is holding on to his “trees” object or the  “compilation” object that is getting created.  If you null those out after calling Emit, I would expect things to get GC’ed eventually.

**Comment by overeemm** [comment]
Could be that it is indeed a problem in our code. We have moved to smaller assemblies (and thus allowing us to release objects faster), and that also seems to help with GC. Thanks for the clarification.

**Comment by KevinH-MS** [comment]
Closing this issue per comments (assume this has been resolved satisfactorily)...if you have any new info that seems to imply a "leak" in Emit please re-activate.
