### ISSUE TITLE
🥳 🎉 [Complete] Requiring the use of VS 2022 for Roslyn development

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#54830]
**UPDATE 7/22:** https://github.com/dotnet/roslyn/pull/55030 has been merged and VS 2022 must now be used to develop with Roslyn.

### Roslyn development will soon require VS 2022
Now that Visual Studio 2022 Preview 1 and Preview 2 are publicly available, we are planning to soon require the use of VS 2022 for Roslyn development.

This transition will likely occur in the coming days, and we will update here when the transition is complete. Please let us know if you have any questions or concerns.

**Comment by JoeRobich** [comment]
Change will go into effect when https://github.com/dotnet/roslyn/pull/55030 is merged.

**Comment by JoeRobich** [comment]
Closing as this has been up for a month.
