### ISSUE TITLE
Speakable names for top-level statements

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#54877]
We'll treat this as a bug (not a language feature) and document the breaking change.

Top-level statements will be emitted into a type named `Program`:
```
partial class Program
{
    public static ... <Main>$(...)
    {
        /* top-level statements */
    }
}
```

https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-07-12.md#speakable-names-for-top-level-statements

Motivating scenario from ASP.NET:
```
//Test Application (xunit for example):
[Fact] 
public async Task HelloWorld()
{
    var webApplicationFactory = new WebApplicationFactory<Program>(); // type -> assembly -> entry point
    var content = await webApplicationFactory.Client.GetStringAsync(http://localhost/);
    Assert.Equal("Hello World", content);
}
```

**Comment by Youssef1313** [comment]
@jcouv What would be the way to know if a given symbol is top-level program class or main method? ie, how to fix the following for roslyn-analyzers:

https://github.com/dotnet/roslyn-analyzers/blob/add78e1c50327ba1524277890359d7af12974a0d/src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs#L708-L719

https://github.com/dotnet/roslyn-analyzers/blob/add78e1c50327ba1524277890359d7af12974a0d/src/Utilities/Compiler/Extensions/INamedTypeSymbolExtensions.cs#L276-L285

**Comment by jcouv** [comment]
@Youssef1313 Thanks for calling out this `roslyn-analyzers` scenario. 
We've only taken a cursory glance with Chuck as to how we'd like implement this change. `Program` would be a regular `NamedTypeSymbol` (instead of a `SimpleProgramNamedTypeSymbol`), but the synthesized entry point would remain a `SynthesizedSimpleProgramEntryPointSymbol`
So `IsTopLevelStatementsEntryPointMethod` and `IsTopLevelStatementsEntryPointType` would be easy to implement internally, but we'll have to see how to keep them working off of public APIs...

Looking at the `roslyn-analyzers` scenario specifically:
- avoid uninstantiated internal classes: we currently have a `IsEntryPoint` extension method in the `Workspaces` layer (which currently relies on `WellKnownMemberNames.TopLevelStatementsEntryPointMethodName`). Maybe a public API from the compiler for this would make sense.
- review unused parameters: a public `IsEntryPoint` API would also help for this. Additionally, the parameters of the synthesized entry point have `IsImplicitlyDeclared`, which may be another sensible signal to exclude them from that analysis.

**Comment by jcouv** [comment]
@Youssef1313 LDM revised the decision to use a speakable method name (`Main`), so the entrypoint for top-level statements is still  recognizable by it's name (`Program.<Main>$`).
So far, IDE and EnC scenarios were easy to update for that. Let me know if that's okay for the roslyn-analyzer scenarios you pointed out. Thanks

**Comment by jcouv** [comment]
For ` IsTopLevelStatementsEntryPointType` in roslyn-analyzers, the check could be tightened a bit by checking whether the `Program` type has a `<Main>$`.

**Comment by Youssef1313** [comment]
Thanks @jcouv. Keeping the unspeakable name for entry-point makes it a lot easier to fix that!
