### ISSUE TITLE
"Object reference not set to an instance of an object" when renaming file which contains __arglist.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54872]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Object-reference-not-set-to-an-instance-/845776)._

---
VS 2019 (16.4.0)
1) Put the following code in `Class1.cs`:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary12
{
    public class Class1
    {
        private static void PrintReversedString(string input)
        {
            // selection start
            var a = 1;
            var charsRenamedNewName = input. ToCharArray(). ToArray(). ToArray(). ToArray(). ToArray(). ToArray(). ToArray()
                . ToArray(). ToArray()
                . ToArray(). ToArray(). ToArray(). ToArray(). ToArray(). ToArray(). ToArray(). ToArray();
            Array.Reverse(charsRenamedNewName);
            // selection end
            var reversed = new string(charsRenamedNewName);
            Console.WriteLine(reversed);
        }
    }
    public interface IChangeSignatureSimple
    {
        //int Foo(int @int, bool someBool);
        string Foo2(string s, __arglist);
        string Foo3(string s);
    }
}
```
2) Invoke Rename in `Class1.cs` in Solution Explorer.
3) Set some name.

**Actual result:**
"Object reference not set to an instance of an object" dialog is shown.

---
#### Feedback Bot on 12/6/2019, 00:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/9/2020, 06:40 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 2/5/2020, 09:24 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.  Seems to work fine in latest builds.
