### ISSUE TITLE
Strange completion behavior at beginning of identifier

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5487]
With name ```original``` in scope, type ```or```.  Completion appears.  Move to beginning of identifier with arrow keys and type ```!``` (i.e. oops, I meant to negate the expression).

I'm not sure what the expected result is, but the actual result is ```original!or```.

**Comment by amcasey** [comment]
FYI @rchande

**Comment by DanielRosenwasser** [comment]
Looks similar to https://github.com/Microsoft/TypeScript/issues/4873 (and potentially https://github.com/Microsoft/TypeScript/issues/3700).

**Comment by dpoeschl** [comment]
I just hit this too. I typed an argument, hit Ctrl+LEFT to go to the beginning of the word, and then space to add a space, but instead completion fired and duplicated my argument.

**Comment by diryboy** [comment]
+1
