### ISSUE TITLE
Refactor - Extract method does not work correctly with simple using statement

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54882]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Refactor---Extract-method-does-not-work-/1317350)._

---
[severity:It bothers me. A fix would be nice]
Visual studio version: 16.8.4

Performing the 'Extract method' refactor where it contains a simple using statement does not work as expected.

1. It returns the constructed instance even though it is not used elsewhere
which means:
2. The using statement gets lost

The code in the example is a simple as I could make it to demonstrate the problem. Simply perform the 'Extract method' refactor on each block to see the issues.

```csharp
// Doesn't work correctly
using var timerSimple = new Timer(Callback);
timerSimple.Change(100, 10);

// Does work correctly
using (var timerStandard = new Timer(Callback))
   timerStandard.Change(100, 10);
```
---
#### Feedback Bot on 1/22/2021, 03:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/22/2021, 10:22 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 5/11/2021, 01:04 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
