### ISSUE TITLE
Extract method doesn't have parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54885]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Extract-method-doesnt-have-parameter/1287587)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.7]
Select code in the editor
Refactor the code by using Extract method
The new method is missing the required parameter(s) required by the extracted code.

```c#
    class B
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public bool IsComplete { get; set; }
    }
    class C
    {
        public B B { get; set; }

        public static bool IsSomething(C c)
        {
            // Extract this to a new method. New method is missing parameter
            return (string.IsNullOrWhiteSpace(c.B.Name) ||
                    string.IsNullOrWhiteSpace(c.B.Value)) &&
                    c.B.IsComplete;
        }
    }
```
---
#### Feedback Bot on 12/14/2020, 09:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/16/2020, 09:38 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/22/2021, 11:50 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
I'm unable to reproduce this in the latest 

![aebbcbd1-02b2-4a82-9764-53350661f7c0](https://user-images.githubusercontent.com/475144/199146525-4771005c-6abd-4c45-a15f-2eda51979382.gif)


Please feel free to reopen and ping me if you have another repro.
