### ISSUE TITLE
Move to namespace screws up document formatting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54889]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Move-to-namespace-screws-up-document-for/1287418)._

---
If I wanted to use Format document, I'd do that. Takes me two keystrokes. Please just don't format document when moving a type to a namespace.

---
#### Fiona Niu[MSFT] on 12/14/2020, 11:47 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario?<br>
Additionally, if there are any relevant screenshots or files that help explain your issue, please attach those as well.</p>
<p>We look forward to hearing from you!</p>

#### Eric on 12/17/2020, 02:51 PM: 

<p>What I experienced is for example:</p>
<ul>
<li>I have <code>Class1.cs</code> in the root of the project, in the namespace <code>Dotnet5.Library</code>.</li>
<li>I right click the project and Add, New Folder with name <code>NewFolder</code>.</li>
<li>I drag <code>Class1.cs</code> to <code>NewFolder</code> in solution explorer.</li>
<li>I open <code>Class1.cs</code> by double-clicking it.</li>
<li>I move the caret to <code>Class1</code> and <code>Ctrl+.</code>, <code>Move to namespace...</code> (sometimes I actually get <code>Move to namespace Dotnet5.Libary.NewFolder</code>, but now I have to add <code>.NewFolder</code> to what is suggested, why doesn’t it consistently provide this convenience?)</li>
<li>I confirm.</li>
</ul>
<p>I now find e.g. declarations that were outlined before I started this action are no longer outlined, braces have been moved, etc. I can undo that, but that also undoes the move to namespace action. Now I have to pick the least painful of three bad options: do the move to namespace manually, or fix the formatting myself, or unwillingly accept my formatting got screwed up and mock Microsoft for it.</p>
<p>Format document, or format selection are <code>Ctrl+E, D</code> and <code>Ctrl+E, F</code> by default. Two keystrokes which I should have to type myself to format the document. Like I said I asked for move to namespace, not to have my formatting screwed up.</p>
<p>As an example, albeit a very limited one which isn’t quite representative of the pain that the automatic format document can introduce, here is <code>Class1.cs</code> before and after the move to namespace action.</p>
<p>Before:</p>
<pre><code><span class="hljs-keyword">using</span> System;

<span class="hljs-keyword">namespace</span> <span class="hljs-title">Dotnet5.Library</span>
{
	<span class="hljs-keyword">public</span> <span class="hljs-keyword">class</span> <span class="hljs-title">Class1</span>
	{
		<span class="hljs-keyword">public</span> <span class="hljs-keyword">const</span> <span class="hljs-keyword">string</span> ShortName		= <span class="hljs-string">""</span>;
		<span class="hljs-keyword">public</span> <span class="hljs-keyword">const</span> <span class="hljs-keyword">string</span> VeryLongName	= <span class="hljs-string">""</span>;
		<span class="hljs-function"><span class="hljs-keyword">public</span> <span class="hljs-keyword">string</span> <span class="hljs-title">GetString</span>(<span class="hljs-params"></span>)</span>
		{
			<span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> NotImplementedException();
		}
	}
}
</code></pre>
<p>After:</p>
<pre><code><span class="hljs-keyword">using</span> System;

<span class="hljs-keyword">namespace</span> <span class="hljs-title">Dotnet5.Library.NewFolder</span>
{
	<span class="hljs-keyword">public</span> <span class="hljs-keyword">class</span> <span class="hljs-title">Class1</span>
	{
		<span class="hljs-keyword">public</span> <span class="hljs-keyword">const</span> <span class="hljs-keyword">string</span> ShortName = <span class="hljs-string">""</span>;
		<span class="hljs-keyword">public</span> <span class="hljs-keyword">const</span> <span class="hljs-keyword">string</span> VeryLongName = <span class="hljs-string">""</span>;
		<span class="hljs-function"><span class="hljs-keyword">public</span> <span class="hljs-keyword">string</span> <span class="hljs-title">GetString</span>(<span class="hljs-params"></span>)</span> {
			<span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> NotImplementedException();
		}
	}
}
</code></pre>
<p>Obviously, someone elses Visual Studio, or my Visual Studio in another solution, with another <code>.editorconfig</code>, might make other formatting changes. The point is that I don’t get why those are being made in the first place. All that I asked for imho is for Visual Studio to add <code>.NewFolder</code> to the namespace in <code>Class1.cs</code> and - most importantly - to find references to this <code>Class1</code> and fix the namespace imports for these references intelligently.</p>

#### Feedback Bot on 12/18/2020, 00:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/18/2020, 09:25 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 3/22/2021, 11:51 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Specifically want to call out this case noted in the bug:

### Before
```csharp
using System;

namespace Dotnet5.Library
{
	public class Class1
	{
		public const string ShortName		= "";
		public const string VeryLongName 	= "";
		public string GetString()
		{
			throw new NotImplementedException();
		}
	}
}
```
### After
```csharp
using System;

namespace Dotnet5.Library.NewFolder
{
	public class Class1
	{
		public const string ShortName = "";
		public const string VeryLongName = "";
		public string GetString() {
			throw new NotImplementedException();
		}
	}
}
```

Some of the changes are enforced due to style decisions. Do we intend to also update spacing around the const declarations, which were aligned by the user to begin with? Looks like a potential formatter issue.

**Comment by dibarbet** [comment]
Design review outcome: In general we do have a preference to not apply formatting changes that were not fundamental to the fix/refactoring.  Where it is simple to update fixes/refactorings to not requireformatting, we would accept PRs to update them.

In particular this issue may just be a bug.  Might need to remove a formatting annotation on this refactoring.  Additionally needs investigation on if the simplifier / complexifier is able to keep previous trivia on a node when the round trip does not result in a different node.

**Comment by jbennink** [comment]
I just had this happen with "Change namespace to match folder structure".  I'm running 17.5.1 and both formatting was affected as well as VS wants to change Explicit variables to use var instead. As  The Issue states, please don't change anything more than I ask. Now a refactoring of namespaces also includes explicit variables => var changes.
