### ISSUE TITLE
`Convert to record struct` should not partially duplicate record's features

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/roslyn#54897]
I'm not sure why this was done, but don't we want to use record structs in the "native" way, without generating half of its functional for no reason?

<details><summary><b>Screenshot</b></summary>

![image](https://user-images.githubusercontent.com/31178401/126046295-da8f0b6f-4eea-4d7c-bca1-313b0443e2ee.png)

</details>

Instead, I did expect something like this:

```cs
var a = (X: 3, Y: 4, Z: 5);
```
->
```cs
var a = new NewStruct(3, 4, 5);

internal record struct NewStruct(int X, int Y, int Z);
```

**Comment by CyrusNajmabadi** [comment]
Yup.  Seems reasonable.  :)

**Comment by CyrusNajmabadi** [comment]
Ah, we actually do support this.  However, in this case the issue is the abnormal use of PascalCased member names for the tuples.  We'd have to special case how we generate in that situation as well.

**Comment by WhiteBlackGoose** [comment]
I recently started using PascalCased tuples exactly because now they look more close to anonymous record structs than some collection of local variables. So I expect a logical deanonymysation. By the way, if the issue is very easily fixable, I can *try* to fix it

**Comment by CyrusNajmabadi** [comment]
Note: the design of tuples is very much that htey're equivalent to a list of parameters.  So PascalCasing is def odd :)  

> By the way, if the issue is very easily fixable, I can try to fix it

It should be fairly easy to fix.  The code for this is here: https://github.com/dotnet/roslyn/blob/7ffb9182186852204f1e6e32fc62c2d8c863c08b/src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs#L925

We likely just want to change this such that if the original tuple element names all match the final field names, that we also consider that 'good enough' to make a primary constructor for.

**Comment by WhiteBlackGoose** [comment]
By the way, it gives a wrong suggestion for camelCase too. This time it leaves `x` and `y` camelCase as records' props.
![image](https://user-images.githubusercontent.com/31178401/127458115-6eeae69c-6fd4-4f1f-be44-e8d952778f89.png)

Is it by design? @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Yes, that was by design. That way any code that was consuming the tuple would continue to consume the record. If we changed the names, we'd have to find and update all the references.

**Comment by WhiteBlackGoose** [comment]
@CyrusNajmabadi but if you replace all uses of the tuple, why do you add implicit operators from/to a tuple?

**Comment by CyrusNajmabadi** [comment]
As you can see in the feature, we replace the tuples within a requested scope.  The user may still bridge the record to a tuple across that scope's boundary.
