### ISSUE TITLE
Metadata as source on types with embedded interop can show `object` in interfaces list.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#5489]
**REPRO:**
In a C# project add a reference to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.ExtensionManager.Implementation.dll` and add the following method to a class:

``` C#
void M()
{
    Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService ems;
}
```

And invoke go-to-definition on the `ExtensionManagerService` symbol.

**RESULT:**
The interfaces listed appear as `IVsExtensionManager, INotifyPropertyChanged, object, SVsExtensionManager, object, ...`.

Ultimately this is because the `IVsExtensionManagerPrivate` symbol could not be fully resolved.  I spent some time debugging into this and the problem arises in the method [`CreateSimpleTypeSyntax()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs,9b7a342b6bab90df,references) where the `INamedTypeSymbol` for the `IVsExtensionManagerPrivate` interface is a [`NoPiaMissingCannonicalTypeSymbol`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/NoPiaMissingCanonicalTypeSymbol.cs,e14c17738d7cec72) which is an error type and it's `Name` property is empty.  The fix is likely to expose `NoPiaMissingCannonicalTypeSymbol` to the `CSharpWorkspace` project where this can be checked for and its `FullTypeName` property used via `symbol.FullTypeName.ToIdentifierName()`.

**Comment by Pilchie** [comment]
I don't think it would be worth adding public APIs to error symbols to address this issue.
