### ISSUE TITLE
`using static` type couldn't resolve extension methods without extension call

### ISSUE THREAD

**Issue by naminodarie** [dotnet/roslyn#54893]
**Version Used**: 

Microsoft Visual Studio Community 2019
Version 16.10.1

**Steps to Reproduce**:

below code

```C#
using static Methods;

Methods.Func(0);
Func(0);
Methods.Extension(0);
0.Extension();
Extension(0); // Compilation error, CS0103

static class Methods
{
    public static void Func(int num) { }
    public static void Extension(this int num) { }
}
```

**Expected Behavior**:

no error

**Actual Behavior**:

error CS0103: The name 'Extension' does not exist in the current context

![image](https://user-images.githubusercontent.com/32071278/126034048-31385f33-09a8-465f-97fd-311c33700e5d.png)

**Comment by svick** [comment]
This behaves exactly as [documented](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static#remarks) and [specified](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces#using-static-directives), so this is the intended behavior. [The explanation for this from a Language Design Meeting is:](https://github.com/dotnet/csharplang/blob/3c8559f/meetings/2014/LDM-2014-02-10.md#extension-methods)

> On the other hand, extension methods are designed to be used as such: you only call them as static methods to disambiguate. So it seems wrong if they are allowed to pollute the top-level namespace as static methods. On the _other_ other hand, this would be the first place in the language where an extension method wouldn’t be treated like a static method.
> 
> #### Conclusion
> We will import extension methods as extension methods, but not as static methods. This seems to hit the best usability point.

**Comment by naminodarie** [comment]
> This behaves exactly as documented and specified, so this is the intended behavior.

I understand.
