### ISSUE TITLE
IDE not highlighting class being inherited in VB and marking its namespace as unnecessary using

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#54907]
**Version Used**: 

16.10.3

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/31348972/126079718-1fe99e5f-e4f9-491c-b6be-2ed2b5d780df.png)

I'm only hitting this while working with Roslyn.sln.

Also note that removing the namespace fails the build, but the IDE doesn't show the error in error list. It only shows in build output after an explicit build. This also affects other things like add using quick actions, implement abstract class, or codefix tied to a specific compiler error.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I think this is something to prioritize if reproducible. Please take a look.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these scenarios.
