### ISSUE TITLE
VS crashes typing in lambda

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#5491]
**Repro machine configuration**
VS 2015 Update 1
VSUVSCore 23318.00

**Repro steps**

1. Create a new Visual C# file (this does not have to be in the context of a C# project)
1. Replace the contents of the file with the code shown below.
1. In the second `AddRange` statement, type `p => ` in as the argument to the `Select` extension method.
1. By the time you press the spacebar as part of the lambda, VS crashes.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

public class Class1
{
    public static object[][] TestCases
    {
        get
        {
            string[] projects = new[]
            {
                "Basic40",
                "Basic452",
                "Basic46",
                "Basic50Portable",
                "BasicProfile143",
                "BasicProfile151",
            };
            var testCases = new List<object[]>();
            testCases.AddRange(projects.Select(p => new object[] { p, true }));
            testCases.AddRange(projects.Select());
            return testCases.ToArray();
        }
    }
}
```

**Comment by balajikris** [comment]
Note: Have to look at the stack to be sure, but the IDE fixed a crash in lambda recently.

**Comment by balajikris** [comment]
I no longer see the crash with bits from 09/26.

**Comment by balajikris** [comment]
This is likely #5255 #5126 ?

**Comment by Pilchie** [comment]
Yes.  Sounds like a dupe.
