### ISSUE TITLE
F2 Rename `Apply` is inconsistent

### ISSUE THREAD

**Issue by kzrnm** [dotnet/roslyn#54918]
**Version Used**: 

- Microsoft Visual Studio Community 2019 Version 16.10.3
- Microsoft Visual Studio Community 2022 Preview Version 17.0.0 Preview 2.0

**Steps to Reproduce**:

1. Create a project like below.
2. Open `Project/RenameFile.csproj`.
3. Focus `Program` in Source/Program.cs
4. Press F2 `Rename`
5. Check `Rename symbol's file`
6. Rename class name
7. Do
    - Press Enter key
    - Click `Apply` button

**Expected Behavior**:

After pressing Enter key or clicking `Apply` button, an error will be thrown.

**Actual Behavior**:

After clicking `Apply` button, an error will be thrown.
After pressing Enter key, a line break will be added.

https://user-images.githubusercontent.com/32071278/126186490-660ee62a-4194-412a-a682-5818bd577584.mp4

----

**file tree**

```
.
├── Project
│   └── RenameFile.csproj
└── Source
    └── Program.cs
```

**Project/RenameFile.csproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Source/Program.cs" />
  </ItemGroup>
</Project>
```

**Source/Program.cs**

```C#
class Program { }
```

**Comment by ryzngard** [comment]
This is not fixed by #54918 but is improved
