### ISSUE TITLE
C# is auto-completing braces even though settings is: Off

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54920]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-is-auto-completing-braces-even-though/1466714)._

---
[severity:It bothers me. A fix would be nice] [regression]
when I write:
   if (a == 1) return;
   else
   {
   }

then the IDE will automatically add braces to:

if (a == 1)
   {
      return;
   }
   else
   {
   }

even though I never asked for it. This is new. 
It happens automatically even though brace-completion is off in VS options.
It is unclear which VS option disables this globally because it happens automatically. Maybe you should write something to the output window.
Please don't make C# into Visual Basic 6 or PyCharm.

Thanks!

---
#### Feedback Bot on 7/1/2021, 11:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/4/2021, 07:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by davidwengier** [comment]
I suspect this is a case of the user accidentally invoking smart line break, as I have automatic brace completion turned off and can't reproduce this, and haven't seen it. @sharwell do we have an existing issue tracking that?

**Comment by davidwengier** [comment]
More information about what is happening here, including a workaround (rebinding a keyboard shortcut) can be found in this similar issue: https://github.com/dotnet/roslyn/issues/53453#issuecomment-845206040
