### ISSUE TITLE
Default XML comment for overriden properties/methods should be inherited.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54927]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Default-XML-comment-for-overriden-proper/1454658)._

---
Add option to set default generated XML comments for inherited members as

`/// <inheritdoc />`

instead of

```
/// <summary>
/// 
/// </summary>
```

---
#### Feedback Bot on 6/20/2021, 06:57 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Currently the IDE does default to `<inheritdoc/>` when no comment is added. The user only needs to add an explicit documentation comment for cases where documentation is _not_ inherited. Based on this, it should not be necessary to add this option.

I'm tentatively marking this as **Won't Fix**, but I'll take it to a design review meeting with the team before closing it with a final resolution.

See also dotnet/sdk#20858

**Comment by NTaylorMullen** [comment]
### Design Meeting Notes

- **Proposal:** Do nothing
	- Reason: If you don't have any XML comments to begin with the default doc comment is /// <inheritdoc />
	- Questions:
		- Does GneerateFXDoc respect the default of inheritdoc for overridden properties/methods
		- Does the analyzer that complains about docs know about the inheritdoc details?
			- It's actually a compiler error that complains about lacking / incorrect documentation BUT it can be suppressed with 3 nowarns: 1573, 1591, 1712
			- Compiler does not know about the inheritdoc default
- **Conclusion:** Create an analyzer code fix that's tied to 1591 where it suggests to add explicit inheritdocs

**Comment by Youssef1313** [comment]
@sharwell The conclusion says:

> Create an analyzer code fix that's tied to 1591 where it suggests to add explicit inheritdocs

Shouldn't this be kept open to track that?

**Comment by sharwell** [comment]
@Youssef1313 I'm working on filing the follow-up issue(s) now actually 😄
