### ISSUE TITLE
Expand code snippets to interact with the existing class definition so we can easily add standard features to many classes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54924]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Expand-code-snippets-to-interact-with-th/1453334)._

---
If code snippets were aware of the class that they were being applied to, we could setup variables to control not only where the additional code is added but also to what.

For example, a code snippet could be created called AddFooInterface.  This snippet would have a section for usings, a section for the constructor, a section to append to the class definition, and control areas to ensure that the interface was implemented in a similar area for each class.

So we could go from

using system;

public class MyFunkyClass:MyBaseClass
{
    public MyFunkyClass()
    {
    }

public void ExistingComplexWorkThatIDoNotWantToRecreate()
    {
    }
}

to

using system;
using MyNamespace;

public class MyFunkyClass:MyBaseClass,IMyInterface
{
    //IMyInterface fields
    private bool _thisIsCool = true;

public MyFunkyClass(bool isThisCool):base(isThisCool)
    {
        _thisIsCool = isThisCool;
    }

public void ExistingComplexWorkThatIDoNotWantToRecreate()
    {
    }
  
//IMyInterface members
    public bool IsThisCool()
    {
        return _thisIsCool;
    }
}

using something like this

<?xml version="1.0" encoding="utf-8" ?>
<CodeSnippets  xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
	<CodeSnippet Format="1.0.0">
		<Header>
			<Title>AddFooInterface</Title>
			<Shortcut>afi</Shortcut>
			<Description>Example of possible XML</Description>
			<Author>Chris Fricke</Author>
			<SnippetTypes>
				<SnippetType>Append</SnippetType>
			</SnippetTypes>
		</Header>
		<Snippet>
			<Code Language="csharp"><! [CDATA[public $$top$$//IMyInterface fields
    private bool _thisIsCool = true;$$/top$$
$$bottom$$//IMyInterface members
    public bool IsThisCool()
    {
        _return _thisIsCool;
    }
$$/bottom$$
$$constructorParameter$$bool isThisCool$$/constructorParameter$$
$$constructorInherit$$:base(isThisCool)$$/constructorInherit$$
$$constructorMethod[top]$$_thisIsCool = isThisCool;$$/constructorMethod$$
]]>
			</Code>
		</Snippet>
	</CodeSnippet>
</CodeSnippets>

---
#### Feedback Bot on 6/17/2021, 07:40 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This could fairly trivially be done as a https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.coderefactorings.coderefactoringprovider?view=roslyn-dotnet-3.10.0
