### ISSUE TITLE
Remove unused methodes via CodeCleaner

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54931]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-unused-methodes-via-CodeCleaner/1457264)._

---
Would love to remove unused methodes via the CodeCleaner, especially for C#. Since we can remove unused fields and propertys, removing dead methodes would be an awesome addition.

---
#### Feedback Bot on 6/22/2021, 07:31 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
