### ISSUE TITLE
VB.net collapsible comment blocks inside procedure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54930]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VBnet-collapsible-comment-blocks-inside/1454995)._

---
would love to have the comment blocks to be collapsible when inside a function/sub, currently comment blocks are only collapsible if they are outside a function/sub.

---
#### Feedback Bot on 6/20/2021, 07:55 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be making changes to these experiences.
