### ISSUE TITLE
New quick action: Move code to partial class file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54949]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/New-quick-action:-Move-code-to-partial-c/1470252)._

---
Add a new quick action to move selected code to partial class file(Create new, or move to a exsited file)

---
#### Feedback Bot on 7/7/2021, 07:38 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
Move static member to another type can help with this if we expand it beyond static but we it wouldn’t be for a partial class – this should probably be a new refactoring that we should just add.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
