### ISSUE TITLE
Add quick action accelerator keys

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54951]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-quick-action-accelerator-keys/1430260)._

---
Accelerator keys appear on drop-down menus - you can get them on the main menus by pressing alt, then various menu items get a little underscore for the key you can press to activate that menu item. Example of existing accelerators in VS:

! [accel.png] (https://aka.ms/dc/image?name=Ba9c11186793846cc8567b284515ca234637574438043718422_accel.png&tid=a9c11186793846cc8567b284515ca234637574438043718422)

So pressing Alt, D, l in that order would click the "Relaunch Performance Profiler" menu item.

The the quick code actions dropdown menu has no such accelerators, and it can end up with many refactorings/fixes especially when we take full advantage of roslyn, for example:

! [quick ac.png] (https://aka.ms/dc/image?name=B5ff1891c69ac46e2a6d554ae33fb01c4637574439246537290_quick_ac.png&tid=5ff1891c69ac46e2a6d554ae33fb01c4637574439246537290)

I don't believe there is a way to turn on accelerator keys for this menu - please correct me if there is a way.

Using this menu using the mouse/arrow keys is very cumbersome, because it can get very full as mentioned.

Please can we add accelerator keys to this menu.  The menu is dynamic and can have actions coming from user defined code-fixes (e.g. roslynator), so I think the accelerators should be auto-generated e.g. the first unused key for unquoted word first-letters (that's a fast nanoseconds algorithm, can be run on menu opening without harm).

Thanks!

---
#### Feedback Bot on 5/25/2021, 01:18 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by tiesmaster** [comment]
This is one of the key things missing from using CodeFixes or Refactorings. Having any kind of "accelerator" support in the menu, like the well-known mnemonics, or even just an index from 1 - N to select the given entry by number would help really a lot (something to perhaps just have disabled by default, and possible to enable via an option).

**Comment by jmarolf** [comment]
@CyrusNajmabadi I assume we would need some work done on the VS Platform side for this to be possible, right?

**Comment by CyrusNajmabadi** [comment]
Closing as external.  Platform/editor owns this.
