### ISSUE TITLE
Please provide a "Developer Mode" toggle that makes code analyzer cache invalidated every build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#54952]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-provide-a-Developer-Mode-toggle/1416092)._

---
It's very annoying having to restart Visual Studio every time I make changes to an analyzer or source generator. Please provide a "Developer Mode" toggle that invalidates analyzer cache every build when enabled.

---
#### Feedback Bot on 5/9/2021, 11:14 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by RikkiGibson** [comment]
Isn't this an issue where it's prohibitively difficult to unload analyzers once they've been loaded in netframework?

**Comment by jinujoseph** [comment]
Duplicated of https://github.com/dotnet/roslyn/issues/29123

**Comment by PathogenDavid** [comment]
I don't think this is actually related to https://github.com/dotnet/roslyn/issues/29123, but it is probably a duplicate of https://github.com/dotnet/roslyn/issues/48083 and maybe https://github.com/dotnet/roslyn/issues/44093. (Those issues are for source generators, but it's the same root cause.)
