### ISSUE TITLE
All edits in a VSIX project are marked as "Rude Edits"

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#54955]
1. Open Roslyn.sln
2. Press F5 to begin building and debugging (I am using VS 2022 so I used the main-vs-deps branch)
3. While Debugging edit any code file

# Expected

edits that small and in-scope can be applied without issues (such as adding and if statement)

# Actual

All edits are treated as rude edits.

![image](https://user-images.githubusercontent.com/9797472/126237672-5e2553e3-f4df-4442-a036-cbe994174407.png)

![image](https://user-images.githubusercontent.com/9797472/126237690-2670ac76-2009-4ab7-847d-e41f11b8d381.png)

**Comment by tmat** [comment]
@isadorasophia

**Comment by tmat** [comment]
Moving to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1365273
