### ISSUE TITLE
Auto brace completion should support adding open brace when close brace is typed.

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#5497]
Forking off the brace completion related discussion from #5200 into a new issue here.

@zinvob writes:

> Another big frustration for me is automatic end bracket and end ", I can't find any way to turn those off. I often wrap codelines inside IF after they are written, so when I complete the IF and press { I always get } that needs to be deleted before moving to the end of the code to write }.
> 
> ...
> ...
> Brace completion could actually work for most situations if they also supported automatic adding of start brace.
>  Example:
> 
> ``` C#
>  if (somecondition)
>  code
>  code
>  <- enter }
> ```
> 
>  auto behaviour traverse back to find first logical place for brace start and format ends up with
> 
> ``` C#
>  if (somecondition)
>  {
>  code
>  code
>  }
> ```
> 
> This will cover my normal usage. I wrap existing code or write new.
> 
> ...
> ...
> Lets say I have
> 
> ```
>  code1
>  code2
>  code3
>  code4
> ```
> 
> Then I want to put code2 and code3 inside an IF. Then I could insert `if (condition)` between `code1` and `code2`, move down and insert `}` between `code3` and `code4` **and have the start brace added**. If this is implemented, normal auto add close bracket will not annoy because _I don't need to write the start bracket in this case_.
> 
> It will also simplify other cases. Lets say I have
> 
> ``` C#
>  if (bla)
>  ifcode;
>  othercode1;
>  othercode2;
> ```
> 
>  and I want to add some lines to `ifcode`.. I just write the lines and at the end write `}`.

**Comment by zinvob** [comment]
Another logic that should be added if possible. If more than one if/while/for etc. "block" without brackets exists within the current block, check indentation and select the one matching indentation. If that's hard to do, show a windows with lines for selecting the if/while/for etc. you want to match on (or just match selection within the editor). Best would be selection based on same indentation as where you put your }.

**Comment by Neme12** [comment]
I don't see how this could work. If I have:
```c#
class C
{
    void M()
    {
        if (true)
            statement1();
        statement2();
```
If I type `}`, I expect it to match the `{` of the method, **not** create a block for the if statement.

**Comment by zinvob** [comment]
@Neme12 That's no problem. This functionality should only work when you are not missing closing brackets for methods, class, namespace etc. And normally you would have closing brackets on you method because that was auto added when you pressed { after the method..

**Comment by CyrusNajmabadi** [comment]
Need info on how often this actually hits people to justify the investment here.
