### ISSUE TITLE
Switch expression pattern is not using suggestion mode

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#54977]
**Version Used**: Version 17.0.0 Preview 3.0 [31519.82.main] (I think this is a recent break)

**Steps to Reproduce**:

1. Create a new console app.
2. Type `_ = args switch { $$ }` (cursor at $$)
3. Type `_<space>`

**Expected Behavior**:

`_` is kept.

**Actual Behavior**:

`#if` is inserted (or whatever is top of your completion list).
Here's a different example:
![No suggestion mode](https://user-images.githubusercontent.com/2371880/126367586-ec3c7b49-34fc-4389-a3f1-92503de9c2e8.gif)

**Comment by CyrusNajmabadi** [comment]
Note: we likely shouldn't be in suggestion mode here.  What we *should* be doing is adding the 'discard symbol' (`_`) to the completion list so that this just counts as a real match with normal completion semantics.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph i think we should not have this in the backlog.  it's a pretty unpleasant experience typing a reasonable code construct.

**Comment by jinujoseph** [comment]
cc @genlu fyi

**Comment by 333fred** [comment]
> jinujoseph i think we should not have this in the backlog.  it's a pretty unpleasant experience typing a reasonable code construct.

I would go as far as to say it's the most common switch expression pattern. Just about every switch expression I type has one, and this bug has bit me nearly a double-digit number of times today.

**Comment by CyrusNajmabadi** [comment]
I don't repro this anymore.  We don't seem to hard select:

![image](https://user-images.githubusercontent.com/4564579/215887890-9115b4d9-0b6f-4903-8c63-462e37e20650.png)
