### ISSUE TITLE
BUG: IDE0051 not working when file contains `nameof()`

### ISSUE THREAD

**Issue by LukeOwlclaw** [dotnet/roslyn#54972]
**Version Used**: 
VS2019 16.10.3
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll

**Steps to Reproduce**:

1. Create a new project (e.g. .NET Core 5 Console app)
2. Add `private int mTest = 5;` to ``Program.cs``

You'll see immediately: ``Message	IDE0051	Private member 'Program.mTest' is unused``

3. Add to `Main()`: `Console.WriteLine(nameof(Class1));`

**Actual Behavior**:

Message IDE0051 is gone!

**Expected Behavior**:

Message IDE0051 should stay independent of `nameof` being used in file.

**Screenshots**:
 (for visualizing I set IDE0051 to "error" and used extension "Solution Error Visualizer"):

![image](https://user-images.githubusercontent.com/2737900/126303422-6ed5d70e-04fd-4b7d-b00a-86bf263d2370.png)

![image](https://user-images.githubusercontent.com/2737900/126303534-aba13330-ea59-4468-8d28-bc01f6c13b55.png)

***Same problem applies to IDE0052***

**Comment by LukeOwlclaw** [comment]
The same problem happens when using the range operator `..`. For example write:

    string s = "Hello World!";
    Console.WriteLine(s[0..1]);

And the IDE0051 error will disappear.

**Comment by Dorus** [comment]
VS2022 Version 17.12.2
net8.0

This is still a problem
