### ISSUE TITLE
Create a way to wait for updates in Worksapce for HotReload functionality

### ISSUE THREAD

**Issue by vritant24** [dotnet/roslyn#54978]
As part of hot reload, `Workspace.CurrentSoluton` is passed on to the HotReloadService to retrieve deltas. 
In VS, there is a possibility of a race if the user makes an edit and immediately kicks off an operation that passes an un-updated CurrentSolution to the HotReloadService, thus skipping changes. In test experience scenarios this is not desirable.

We need a way to ask for `CurrentSoluton` after processing all the updates in the editor "so far".

**Comment by tmat** [comment]
Needs LSP snapshotting.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this is needed, it needs a dev and milestone assigned so we do it.
