### ISSUE TITLE
No intellisense on lambda parameter before variable declaration

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5498]
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        var z = args.Select(a => a.$$
        var foo = 
    }
}
```

There's no intellisense at the caret.

**Comment by diryboy** [comment]
I hit this recently, tagging in.

**Comment by rchande** [comment]
Looks like type inference is failing--parameter `a` is an ErrorTypeSymbol, so the IDE is unable to lookup symbols from it. Moving to compiler.

**Comment by bmay2** [comment]
This looks similar to [#557](https://github.com/dotnet/roslyn/issues/557) - the type inferrer considers the lambda parameter there an ErrorType, too.
