### ISSUE TITLE
Code compiled by interactive (repl/scripting) should have language rules (e.g. definite assignment) applied.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#550]
Code compiled by the interactive and scripting variants of the language should follow normal language rules unless there is a specific decision otherwise. Specifically, for variables declared within the code, it should be an error to use a variable before it has been definitely assigned a value.

We should have unit tests that verify this is occurring.

It would be a breaking change to add the constraints later, so this should be done in the first supported iterations.

**Comment by ManishJayaswal** [comment]
We do apply definite assignment rule and an error is give when an unassigned variable is used. We just need to add test for this scenario.

**Comment by gafter** [comment]
I remember reviewing the PR where this was implemented.

**Comment by cston** [comment]
Tests added in #6143.
