### ISSUE TITLE
Source generators, how to add project reference?

### ISSUE THREAD

**Issue by kefyru** [dotnet/roslyn#55003]
I have some class library and link it as project reference to generator.
Generator compiles, but does not works.
Just got:
Warning CS8785 : Generator 'MyGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'MyLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

I found solutions for nuget packages, but they don't works for project reference.
Help please!

**Comment by Bosch-Eli-Black** [comment]
@kefyru You've probably already figured this out, but if not, see https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-580567 🙂

**Comment by RikkiGibson** [comment]
It looks like the question was answered.
