### ISSUE TITLE
IDE0150 description is missing in the error list

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#55005]
**Version Used**: 17.0.0-p2.0

![image](https://user-images.githubusercontent.com/8040367/126506042-87a62cc1-5a77-4d74-bdf2-e07d7033906e.png)

IDE0150 shows up for `is object` checks:

![image](https://user-images.githubusercontent.com/8040367/126506203-730e40d9-b956-46c3-9585-b906391ed4b1.png)

**Comment by Youssef1313** [comment]
Thanks for pinging @jnm2 
Opened #55007
