### ISSUE TITLE
Implement #! and #load in VB...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5500]
Need to port changes from:

https://github.com/dotnet/roslyn/commit/00e73149ef142fc703e7a8643344da6b58c75dde

and 

https://github.com/dotnet/roslyn/commit/f1702c92cbdb952d8d62e49d11a0f018fe002036

so that ```#!``` and ```#load``` can work in VB scripts.

Note:  There is also work to do for syntax highlighting and completion.

**Comment by amcasey** [comment]
Subsumed by https://github.com/dotnet/roslyn/issues/6554.
