### ISSUE TITLE
refactor to create local method creates argument for local const member

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55031]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/refactor-to-create-local-method-creates-/1413956)._

---
If you have function with code like:

```csharp
const string NAME = "SOMETEXT";
Assert.AreEqual(string. Format(NAME, 0, 0), SomeOtherMethod(j));
```

and you want "Extract local method" just the assert line.
It will create an argument for NAME. Also the refactor preview in context menu shows that NAME is already red underlined.

[@ryzngard added info]: This happens for language versions that don't support static local methods. The extraction doesn't add static, but name collisions happen because of captures.

---
#### Fiona Niu[MSFT] on 5/6/2021, 01:22 AM: 

<p>Thank you for your feedback! Does this reproduce for all project or specific project? In order for us to investigate this further, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you could provide some screenshots of this issue. Thanks for your help!</p>
<p>We look forward to hearing from you!</p>

#### Ronny Borchert on 5/6/2021, 04:53 AM: 

<p>This issue does not occur in .NET5 project. I used to make this gif a .NET 4.8 project.<br>
After refactor and build project this error appears:</p>
<p>Severity	Code	Description	Project	File	Line	Suppression State<br>
Error	CS0136	A local or parameter named ‘NAME’ cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter	ConsoleApp3	C:\xxx\Program.cs	15	N/A</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bae6fe1abcce549d78efb2d4633c32386637558987560851841_localMethodRefactor.gif&amp;tid=ae6fe1abcce549d78efb2d4633c32386637558987560851841">localMethodRefactor.gif</a></p>

#### Feedback Bot on 5/6/2021, 05:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/10/2021, 09:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Andrew Hall 🤘 [MSFT] on 5/10/2021, 02:30 PM: 

<p><a target='_blank' href="https://developercommunity.visualstudio.com/user/752fa17a-6bd6-4609-97b6-244710870eab/profile">Ronny Borchert</a> the behavior of the refactoring is currently by design. I’m not sure I follow the rest of the explanation. In the GIF you provided are you switching between net5 and net48?</p>

#### Ronny Borchert on 5/10/2021, 11:51 PM: 

<p>In gif is no switch between net5 and net48. It is just that net48 would refactor code which is only valid for net50.</p>

#### Andrew Hall 🤘 [MSFT] on 7/16/2021, 03:13 PM: 

<p>Thanks for your feedback! There seems to be two parts, so I want to address them individually:</p>
<ol>
<li>
<p>Constant gets added as a parameter in extracted method: This is currently by design. Often times we’ve found that extracting to a method is for reuse, but with potentially different values. This behavior functions the same for other local variables and arguments used. Does the behavior you expect work if you also highlight the declaration line of “NAME”?</p>
</li>
<li>
<p>“Also the refactor preview in context menu shows that NAME is already red underlined”: I was unable to reproduce this issue on VS2022 builds. Does this still happen for you? Can you provide more information and a screen shot for this behavior?</p>
</li>
</ol>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Ronny Borchert on 7/21/2021, 04:48 AM: 

<ol>
<li>
<p>The issue is that this refactoring is creating a local method which is using as variable name “NAME”. This is in .NET 5 allowed, but not with targeting .NET Framework 4.8. If the const value is also selected refactor works as expected, issue is just that name of argument is same. That means for .NET Framework 4.8 this parameter have to be rename i.e. to “NAME1”.</p>
</li>
<li>
<p>I tried it in 17.0.0 preview 2 and got the same result. See Gif animation:<br>
<img src="https://aka.ms/dc/image?name=Be657dfd24cfb4ed4b5316ef3b14f3e54637624648785209643_reproInVS2022Preview2.gif&amp;tid=e657dfd24cfb4ed4b5316ef3b14f3e54637624648785209643" alt="reproInVS2022Preview2.gif"></p>
</li>
</ol>

#### Andrew Hall 🤘 [MSFT] on 7/21/2021, 04:25 PM: 

<p>I see, this helps a lot. The issue here is that local functions can’t be static prior to net5. I misunderstood that context. I’ll get a github bug tracking this. Thank you for the follow up!</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Adding a comment with a good gif showing the problem. Note that this is language version dependent

![image](https://user-images.githubusercontent.com/475144/126572512-6374a57e-aa8b-4749-9bd7-272df1ca335d.png)
