### ISSUE TITLE
Inheritance Margin Improvements

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#55041]
We currently have the following icons: 

1.	Implementing I ↑
2.	Implemented I ↓
3.	Overriding O ↑
4.	Overridden O ↓
5.	Implementing and overriding I O ↑
6.	Implementing and overridden I O ↕

We should add the following three icons: 

1.	Overriding and Overridden O ↕
2.	Implementing and implemented I ↕
3.	Implemented and overridden I O ↓

The current tool tips are helpful in some scenarios and aren't as helpful in others. We should consider updating the tool tips to be more specific rather than defaulting to saying `{type name} is inherited`. We can have the following tool tips:

1. Implementing I ↑ -> Implements {type} from {type} {type name} (click to navigate)
2. Overriding O ↑ -> Overrides {type} from {type} {type name} (click to navigate)
3. Overridden O ↓ -> {type} {type name} is inherited (click to navigate)
4. Implemented I ↓ {type} {type name} is inherited (click to navigate)

The tool tip should include text letting the user know to click on the icons in-order to navigate.

If there is only one option in the dropdown we should automatically navigate the user rather than opening the single result. Updating the tool tips will help make it clear that clicking on it will navigate the user. 

The current header names are not correct and are essentially the opposite of what the icons represent.

We should consider turning inheritance margin on by default in preview 3 to collect feedback. UX is currently working on a design for users to quickly toggle the icons off/on. We should also consider a configuration option for each icon by surfacing an option for each icon in Tools > Options.

**Comment by Cosifne** [comment]
Copied a conclusion that we made in https://github.com/dotnet/roslyn/issues/54454
Based on the stats, I think
1. We should give a more detailed tooltip when there is only one target in the context menu. 
Based the table [here](https://github.com/dotnet/roslyn/issues/53489#issuecomment-843385909)

* Headers for classes and structures (The selected class is 'class Bar')
    * `I↑` Implemented interfaces    **// 'class Bar' implements 'interface IBar'**
    * `O↑` Base types                      **// 'class Bar' is derived from 'class BaseBar'**
    * `O↓` Derived types                 **//  'class Bar' derives 'class SubBar'**
* Headers for interfaces (The selected interface is 'interface IBar')
    * `I↑` Inherited interfaces         **// 'interface IBar' is inherited from 'interface IBaseBar'**
    * `I↓` Implementing types         **// 'interface IBar' is implemented by 'interface ISubBar'**
* Headers for members of a class or structure (The selected member is 'Bar()')
    * `I↑` Implemented members    **// 'Bar()' implements 'IBar.Bar()'**
    * `O↑` Overridden members      **// 'Bar()' overrides 'BaseClass.Bar()'**
    * `O↓` Overriding members      **//  'Bar()' is overridden by 'SubClass.Bar()'**
* Headers for members of an interface (The selected member is 'Bar()')
    * `I↓` Implementing members   **// 'Bar()' is implemented by 'SubBar.Bar()'**
   
2. For two targets and more under the same header
* Headers for classes and structures (The selected class is 'class Bar')
    * `I↑` Implemented interfaces    **// 'class Bar' has multiple implemented interfaces**
    * `O↑` Base types                      **//  'class Bar' has multiple base types**
    * `O↓` Derived types                 **//  'class Bar' has multiple derived types**
* Headers for interfaces (The selected interface is 'interface IBar')
    * `I↑` Inherited interfaces         **// 'interface Bar' has multiple Inherited interfaces**
    * `I↓` Implementing types         **// 'interface Bar' has multiple Implementing types**
* Headers for members of a class or structure  (The selected member is 'Bar()')
    * `I↑` Implemented members    **// 'Bar()' implements members from multiple interfaces**
    * `O↑` Overridden members      **// 'Bar()' overrides members from mutliple classes**
    * `O↓` Overriding members      **// 'Bar()' is overriden by members from multiple classes**
* Headers for members of an interface (The selected member is 'Bar()')
    * `I↓` Implementing members   **// 'Bar()' is implmented by members from multiple types**

This should cover 83% of the total usage.

For the rest of the usage.
3. If the margin contains targets of different headers. the tooltip should give the header information.

* classes and structure  (The selected class is 'class Bar')
There will be 4 tooltip for this case:
**'class Bar' has Implemented interfaces and Base types
'class Bar' has Base types and Derived types
'class Bar' has Implemented interfaces and Derived types
'class Bar' has Implemented interfaces, Base types and Derived types**

* Interfaces (The selected interface is 'interface IBar')
**'interface IBar' has inherited interfaces and Implementing types**

* Members of a class or structure  (The selected class is 'Bar()')
**'Bar()' has Implemented members and Overridden members.
'Bar()' has Overridden members and Overriding members.
'Bar()' has Implemented members and Overriding members.
'Bar()' has Implemented members, Overridden members and Overriding members.**

4. Multiple members are on the same line. Show a general tooltip,
'Multiple members are inherited'

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
