### ISSUE TITLE
Shift+Tab (Outdent / Decrease Indent) does not work in virtual space

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#55050]
🔗 Originally filed as [AB#1356628](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1356628)

**Version Used**: 

16.11 Preview 3 [31428.362.d16.11]

**Steps to Reproduce**:

1. Configure the editor as follows, with selection specified by `[|...|]`:

    ```csharp
    class C
    {
        [|
        void Method()
        {
            |]
        }
    }
    ```

    ⚠ Make sure there are no characters on the lines containing `[|` and `|]`. These locations should **both** be in virtual space, like this:

    ![image](https://user-images.githubusercontent.com/1408396/126694464-33931a05-ef6b-45d4-807b-cb5add2f5f8c.png)

    ![image](https://user-images.githubusercontent.com/1408396/126694500-d9298aa5-400f-44b4-974d-7c8fd3458bce.png)

2. Press <kbd>Shift</kbd>+<kbd>Tab</kbd>

**Expected Behavior**:

```csharp
class C
{
    [|
void Method()
{
        |]
    }
}
```

**Actual Behavior**:

```csharp
class C
{
[||]
    void Method()
    {

    }
}
```

**Comment by CyrusNajmabadi** [comment]
@sharwell  is this us or hte editor?
