### ISSUE TITLE
String interpolation refactoring doesn't work on Console.WriteLine

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/roslyn#55053]
![image](https://user-images.githubusercontent.com/31178401/126697413-033ce8c6-e462-4f2d-ade1-007903a99919.png)

SDK: 6.0.100-preview.6.21355.2
VS: 17.0p2

**Comment by Youssef1313** [comment]
This is the expected behavior of this code refactoring. It keeps the semantics the same. Its main usage is when you have a long string containing a bunch of braces and you want to add some variables in it. See https://github.com/dotnet/roslyn/issues/48219

**Comment by 333fred** [comment]
Not sure I agree with that assessment. Sure, it calls a different method, but the effect is the same. We should recognize this and offer the refactoring (imo).

**Comment by Youssef1313** [comment]
@333fred That would be a separate analyzer with a codefix?

**Comment by 333fred** [comment]
> ie, I consider this issue as a request for a new analyzer and a codefix to handle this case, not to modify the existing refactoring.

I'd defer to @CyrusNajmabadi or someone else on the IDE team to answer that question. _Personally_, I view it as the same thing, but I'm not a decision-maker here :)

**Comment by jmarolf** [comment]
We have this refactoring defined for methods like `string.Format`
![image](https://user-images.githubusercontent.com/9797472/128068797-9c679338-d1c2-40ad-b20d-542af03a3781.png)

We should update the refactoring to handle all other .NET "formatting" methods.

We just need to expand this list

https://github.com/dotnet/roslyn/blob/3a5457c3b9483c7b2be1cf6899ee3564c8ade6cf/src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs#L43-L48

**Comment by Youssef1313** [comment]
It looks like the same title "Convert to interpolated string" is used by different codefixes that exist for different purposes. I find this very confusing. Should this be tracked as part of this issue or do I need to create a new issue?

cc @jmarolf @CyrusNajmabadi

**Comment by jmarolf** [comment]
I would argue that we should only show a single refactoring for this case

that converts this:
```csharp
Console.Writeline("Quack quack {0}", "duck");
```

to this: 
```csharp
Console.Writeline($"Quack quack {"duck"}");
```

I think it is fine to have the same text for different refactorings as long as it does what the user expects.
