### ISSUE TITLE
[Complete] Require .NET 6 Preview 6 SDK for Roslyn development

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#55062]
### Roslyn development will soon require .NET 6 preview 6 SDK
The 6.0.0-preview.6 SDK can be downloaded from https://dotnet.microsoft.com/download/dotnet/6.0 

This transition will likely occur early next week, and we will update here when the transition is complete. Please let us know if you have any questions or concerns.

**Comment by JoeRobich** [comment]
Change will go into effect when https://github.com/dotnet/roslyn/pull/54997/ is merged.

**Comment by JoeRobich** [comment]
Arcade updates have started pushing .NET 6 preview 6 SDK. We should move to it at this time.

**Comment by AraHaan** [comment]
Why don't roslyn instead just require the daily quality SDK builds? In this case the builds are currently .NET 6 rc.1.

**Comment by huoyaoyuan** [comment]
> Why don't roslyn instead just require the daily quality SDK builds?

Daily builds have much worse delivery quality than milestone previews. Milestone previews can be easily downloaded by the publish site with CDN.

**Comment by JoeRobich** [comment]
Closing as this is complete.
