### ISSUE TITLE
Compiler NuGet preview feed has just broken: fails with NU1102

### ISSUE THREAD

**Issue by albahari** [dotnet/roslyn#55068]
**Version Used**: 4.0.0-3.21372.2

**Steps to Reproduce**:

1. Set your NuGet feed to https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
2. Install package Microsoft.CodeAnalysis.Features 4.0.0-3.21372.2

**Actual Behavior**:

NuGet package manager fails with NU1022:

Error NU1102 Unable to find package Microsoft.VisualStudio.Debugger.Contracts with version (>= 17.2.0-beta.21371.1)
  - Found 6 version(s) in nuget.org [ Nearest version: 17.2.0-beta.21262.1 ]
  - Found 0 version(s) in Roslyn Preview

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/pull/53400

cc @tmat

**Comment by JoeRobich** [comment]
@albahari During development we often use packages that are publicly available, however not from NuGet.org. For the particular package you reference you would need to add the following to your NuGet.config

```xml
<add key="vs-impl" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json" />
```

In practice, if you are going to be using the prerelease packages of Roslyn, it might be beneficial to also use our [NuGet.config](https://github.com/dotnet/roslyn/blob/main/NuGet.config) for your project.
