### ISSUE TITLE
Allow "Display inline hints" (Alt+F1) in toolbars

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Allow-Display-inline-hints-AltF1-in/1472960)._

---
This feature was introduced in a recent VS 2019 build and is quite useful. Sadly, it's hardcoded to the keyboard shortcut "Alt+F1".
I'd like to be able to have a button/command for it to be able to be added to toolbars and keyboard shortcuts.
Having it as a button could either toggle the feature or have it on as long as the button is pressed.

---
#### Feedback Bot on 7/12/2021, 07:41 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
I believe its time to bring Roslyn features into the task menu bar for feature configuration. I propose we use the following Roslyn icon:
![roslyn_small_icon](https://user-images.githubusercontent.com/46729679/126843072-a1cd35cf-7ceb-47c2-a1a7-a6a9ae235ec6.png)

Place it in the task menu bar similar to where IntelliCode has their Whole Line Completion setting:
![image](https://user-images.githubusercontent.com/46729679/126843513-c5d7e938-6edb-4517-b0c4-a2df6dd4fca1.png)

Selecting the Roslyn icon opens a list of features that we can toggle on/off such as: inline hints, inheritance margin, etc.
![image](https://user-images.githubusercontent.com/46729679/126843634-26dea6ff-8973-44dc-a3a7-356b4f1cb28f.png)

**Comment by Cosifne** [comment]
The concept sounds good. But we might have a design meeting to figure out which feature do we want to put under the task menu.
My thoughts are, only those options that are frequently turned on/off should be put here. And I am not sure if there is a telemtry can let us know this.

And besides, I don't like the Roslyn icon to be shown in the editor. We might want to ask the UX for their advice here

**Comment by ryanbrandenburg** [comment]
Design Meeting Notes:
We'd like to do this by having a button in the margin which will give access to these toggles. We'll need to inform the Platform team once it's  ready.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and movement here.
