### ISSUE TITLE
Cleanup quick parameter refactoring menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55088]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cleanup-quick-parameter-refactoring-menu/1480711)._

---
Who came up with this menu structure:

![B6fd57804519d4bf6a219debc614cc0ce637624569894875943_2021-07-21_11-35-37 (1)](https://user-images.githubusercontent.com/46729679/126845577-f94d352d-f569-412e-9d63-b34bbd248e81.gif)

Can we have just a single set of menu items for this operation? I always get confused with this menu and I use it a lot.

---
#### Feedback Bot on 7/21/2021, 07:38 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
I came up with it :)  There may be up to nine options being shown.  Showing all of them would be a ton of overhead in the list.

**Comment by dcarapic** [comment]
Original poster here.
I would have no problem with the menu if I were able to assign shortcuts. I actually just need two 'refactorings':
1. Name all arguments (I do not not remember the actual menu item caption)
2. Indent all arguments

It would be a bonus if I had just one shortcut to do both.
Is there a way to do this?

If not then really just one sub-menu with 9 options would be better than 2 menus with options that repeat themselves.

**Comment by CyrusNajmabadi** [comment]
> would be better than 2 menus with options that repeat themselves

The options don't repeat. One is about wrapping after each argument. The other is about wrapping only when a certain length is reached. 

Note: once you pick one of these we remember that and we then prioritize that so it will be higher the next time you use this list.

**Comment by CyrusNajmabadi** [comment]
> It would be a bonus if I had just one shortcut to do both.

You'd have to write an extension to do this. In general this is not feasible as there are literally hundreds of features/refactorings, and adding shortcuts for all combinations of them would just bloat things with hundreds to thousands of almost never used commands.

**Comment by CyrusNajmabadi** [comment]
> I would have no problem with the menu if I were able to assign shortcuts.

This is definitely an interesting idea, but also challenging. The list here is dynamic and actually produced by several different refactorings. So providing a way to give shortcuts to those is something we can look into but not something necessarily easy. 

As an example, we'd need to be able to list and assign these shortcuts in the vs options system. But that means we'd need a way for these features to statically be able to state all the potential choices they give (even if they compute that dynamically). 

But it's something we can look into.

**Comment by dcarapic** [comment]
I would actually have no problems in trying to write an extension for a shortcut if one can not be set.
I would just need a little bit of help if you could tell me which of the services in VS is responsible for this refactoring?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
