### ISSUE TITLE
After entering the method, the parenthesis Automatically outputs the parentheses after entering a method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55085]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/输入方法后自动输出括号Automatically-output-parenthe/1467282)._

---
Resharper software has a very good feature, is to enter a method, will automatically generate a pair of parentheses, do not look down on this small function point, accumulated over time, will give developer section to improve a lot of efficiency, it is highly recommended vs and vscode to add this feature.

Resharper software has a great feature, that is, after entering a method, it will automatically generate a pair of parentheses, do not underestimate this small function point, over time, will give the developer's Day to improve a lot of efficiency, it is strongly recommended that vs and vscode add this function.

---
#### Feedback Bot on 7/4/2021, 08:03 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mikadumont** [comment]
@sharwell and @Cosifne

**Comment by allisonchou** [comment]
Design meeting notes (7/26): We plan to take the current argument completion option and add two radio buttons under it to adjust tab behavior (single tab vs. double tab to insert arguments).
Feature will be on by default for preview releases starting in 17.1 P1 until we can gather more feedback. Note we should make sure the feature does not trigger in method group contexts.

**Comment by JoeRobich** [comment]
Commented from https://github.com/dotnet/vscode-csharp/issues/7453:
> Most language extensions autocomplete parentheses in vscode. But C# lacks this feature. It would make developers more productive if the Intellisense also added parenthesis and angle brackets while autocompleting methods like rust, go, and other languages.

**Comment by CyrusNajmabadi** [comment]
@sharwell wasn't this feature done?

**Comment by Rawalanche** [comment]
It's honestly quite embarrassing that as of 2025, Microsoft's defacto official programming language has no proper autocompletion support in Microsoft's official language extension to Microsoft's defacto official code editor. :\
