### ISSUE TITLE
When generating a methode place it below existing methods of same type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55086]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-generating-a-methode-place-it-below/1477841)._

---
When coding and typing in a (yet) not exisiting method. We can auto-generate it. However the methode then often is placed at wrong location inside the script.
If I am typing in class A an new methode member of Class B, I would the new methode be placed in Class B at the location of the other public or internal methods. NOT between private methods.
If i type a new methode member of class A itself and let VS create the methode for me. I want below the other private methods. 

So when auto genereting methodes place them below corresponding method private/public/internal/protected methods
Not for example above in the file below the field definitions or other strange places its placed.

---
#### Feedback Bot on 7/18/2021, 08:23 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader rfeedback on this topic.
