### ISSUE TITLE
Ability to add space after if-statement on "format document"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55097]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ability-to-add-space-after-if-statement-/1467504)._

---
We have a requirement where all if-statements are to be followed by space, i.e.: 

`if(this){ /* statement */}`

Should be formatted with a space after "if" : 

`if (this){ /* statement */}`

Today, I do not have the ability to set this as a code style rule.

---
#### Feedback Bot on 7/4/2021, 10:44 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
this seems odd.  we shoudl always be inserting that space.

**Comment by sharwell** [comment]
It's this option:
![image](https://user-images.githubusercontent.com/1408396/126852398-b089202b-94ee-47ab-9893-64ef24ac953f.png)

**Comment by sharwell** [comment]
And the .editorconfig form:

https://github.com/dotnet/roslyn/blob/b60fe7f175ff96739e82f46e06f7a10be2822a33/.editorconfig#L220
