### ISSUE TITLE
Word selection doesn't work in VB string interpolation literals

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#551]
`Console.WriteLine($"stuff before {1 + 2} stuff after")`

If you double-click on "before", "before" should be selected.  Instead "stuff before " is selected.

Note: this works as expected in C#.

**Comment by amcasey** [comment]
I'm assuming that word navigation (ctrl-left and ctrl-right) uses the same mechanism.

**Comment by Pilchie** [comment]
Yep, we had an internal bug tracking this that @jmarolf filed, which I've just resolved in favor of this.

**Comment by brettfo** [comment]
Re-assigning to @amcasey for verification.

**Comment by amcasey** [comment]
Works on my box.
