### ISSUE TITLE
`IDE0005` is not fixed solution-wise in F# in 17p2.1

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/roslyn#55109]
**Version Used**: 17p2.1

**Steps to Reproduce**:

Create an empty F# console app:
```fs
open System

printfn $"Hello world {5}"
```

Go to `System`, `Ctrl+.` and remove it document-wise, project-wise or solution-wise. All of those will do nothing (although it will remove the current `open` if you press enter).

**Comment by CyrusNajmabadi** [comment]
@TIHan can you transfer this to your repo?  Thanks!

**Comment by TIHan** [comment]
https://github.com/dotnet/fsharp/issues/11892
