### ISSUE TITLE
CS0308 error hide CS0246 codefix (add using directive)

### ISSUE THREAD

**Issue by Kuinox** [dotnet/roslyn#55117]
**Version Used**: 
Visual Studio 2022 Version 17.0.0 Preview 2.1

**Steps to Reproduce**:

```csharp
//File A:
namespace FooBar
{
    public abstract class Foo
    {
        public abstract object Bar( Type type );
    }

    public class Test
    {
        public void TestMethod(Foo arg)
        {
            arg.Bar<object>(); // CS0308 The non-generic method 'Foo.Bar(Type)' cannot be used with type arguments

        }
    }
}
// File B:

namespace FooBar.Extensions
{
    public static class Extension
    {
        public static T Bar<T>( this Foo @this )
            => (T)@this.Bar( typeof( T ) );
    }
}

```
**Expected Behavior**:
The codefix of CS0246 (add using directive) is there allowing me to quickly add `using FooBar.Extensions` and fix the code.
**Actual Behavior**:
Only CS0308 error showed up,
This caused me to thinking that the method I was targeting was not imported/not present anymore.
While typing the code, the autocompletion does propose the extension method.

**Comment by RikkiGibson** [comment]
I think this might be a @dotnet/roslyn-ide issue
