### ISSUE TITLE
Wait dialogs for features invoked from a symbol should show the symbol name

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#5512]
For:
1. Find References
2. Go To Definition
3. Go To Implementation

We show a threaded wait dialog with some boring generic message. We should show the symbol name instead.

**Comment by CyrusNajmabadi** [comment]
Go-to impl and find-refs using the find-window, which do show the symbol name.  

Go-def is asynchronous and will say "navigating to definition" in the BWI tooltip.  I'm wary about making that arbitrarily sized.  I'm going to close out as i'm wary the value is here, and the experience seems good now.  feel free to reactive if you agree @jasonmalinowski .
