### ISSUE TITLE
Join Lines corrupts code (if tab indentation is used?)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55120]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Join-Lines-corrupts-code-if-tab-indenta/1485496)._

---
[severity:It's more difficult to complete my work]
**Edit > Advanced > Join Lines** does not work correctly. I believe it may be caused by handling Tab characters incorrectly.
- It frequently deletes non-whitespace characters from the end of the first line before joining the second line, corrupting the source code.
- If there is whitespace on the end of the first line it does not clean it away, so the joined lines have incorrectly formatted whitespace.

I can reproduce this bug within a few seconds by doing the following:
- open any C# source code file
- Select All and Edit > Advanced > Tabify selected lines to ensure that the indentation is using tabs, not spaces. I am not sure if the problem is repeatable with spaces only.
- Join Lines repeatedly until the red intellisense underlines appear in the code indicating that it's been corrupted. You will now see that around 1-3 non-whitespace characters have been deleted from the ends of some lines before they were joined.

! [JoinLines.png] (https://aka.ms/dc/image?name=Bdde12b0fef064a7fb4f659fa49fc5325637626352092825806_JoinLines.png&tid=dde12b0fef064a7fb4f659fa49fc5325637626352092825806)

Additionally:
- On the end of a line, type several spaces
- Join Lines
- The two lines are joined, but the trailing spaces are preserved so the whitespace formatting of the result is incorrect.

It appears that the Join lines algorithm is calculating a "number of characters to delete" which possibly does not always take newline or tab sequence length into account correctly. Expectation is that it will replace all the whitespace characters from the end of line1 and the beginning of line2 with a single space.

---
#### Feedback Bot on 7/25/2021, 07:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't believe 'join line' is a roslyn feature.  Perhaps thsi needs to move to editor?  @olegtk ?

**Comment by olegtk** [comment]
Yes, Join Lines is editor handled command, please route @jinujoseph. Thanks!
