### ISSUE TITLE
Hang in Inline-Rename when there are errors in the method

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#55140]
If the user has an error in the method they are renaming. Applying the rename (via enter key) will cause a UI deley of over 40 seconds. It appears that most of the hang is coming from `CommitCore`

![image](https://user-images.githubusercontent.com/9797472/127198004-3e26177b-dcf2-4d05-b798-4d3fe33b9078.png)

**Comment by CyrusNajmabadi** [comment]
@vatsalyaagrawal @jinujoseph  please load balance if possible.

**Comment by ryzngard** [comment]
@jmarolf what kind of error? I tried with just typing nonsense in a method and wasn't able to reproduce.

**Comment by jmarolf** [comment]
Let me get a more exact repro, what I was seeing was that when there were errors, the conflict resolution task takes a long time to resolve blocking the UI.

https://github.com/dotnet/roslyn/blob/e079a36f3ade7cda2a464e4fdcde0a11577fd1ea/src/EditorFeatures/Core/Implementation/InlineRename/InlineRenameSession.cs#L744

**Comment by CyrusNajmabadi** [comment]
This coudl certainly be rewritten to be off hte UI thread, while updating the TWD to tell hte user what's going on.

**Comment by CyrusNajmabadi** [comment]
Closing out as we have made this fully async.
