### ISSUE TITLE
Remove dependency on Editor and EditorFeatures from Microsoft.CodeAnalysis.LanguageServer.Protocol project

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#55142]
- [x] Move FindUsagesContext to Features
- [ ] Avoid dependency on editor types such as `ClassifiedTextElement`, `ImageElement`, etc. (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1361656)
- [ ] Move tag ids to Features (`DefinitionHighlightTag.TagId`, ` WrittenReferenceHighlightTag.TagId`, `ReferenceHighlightTag.TagId`)
- [ ] Remove `IThreadingContext`: https://github.com/dotnet/roslyn/projects/45#card-20619668
- [ ] Move `IntellisenseQuickInfoBuilderContext` to Features
- [ ] Move `IInlineRenameService` to features / switch implementation for rename - https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Handler/Rename/RenameHandler.cs,45
- [ ] Remove dependency on global options (requires LSP settings to be implemented by the platform).

**Comment by dibarbet** [comment]
I believe one more is rename - https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Handler/Rename/RenameHandler.cs,45

**Comment by tmat** [comment]
@jinujoseph FYI

**Comment by dibarbet** [comment]
Related to Quick info - https://github.com/dotnet/roslyn/issues/47347

**Comment by dibarbet** [comment]
The LSP layer does not depend on editor features, and almost everything has been moved down.  See
https://github.com/dotnet/roslyn/pull/65292
https://github.com/dotnet/roslyn/pull/65284
https://github.com/dotnet/roslyn/pull/65266
https://github.com/dotnet/roslyn/pull/65264
https://github.com/dotnet/roslyn/pull/65263
https://github.com/dotnet/roslyn/pull/65261
