### ISSUE TITLE
Inline hint (Experimental) - outline is moved

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55185]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inline-hint-Experimental---outline-is-/1488288)._

---
The outline does not stay in place but is push by the hint (variable name)… so the "hint" outline almost overlap the inner outline like if-statement. see screenshot.
Expected behavior: the "hint" outline should not be move by the hint-name. this creates confusions and it is not longer helpful.

![image](https://user-images.githubusercontent.com/1408396/127364317-b4640fc5-83fd-4fbd-8097-c6cb0809f963.png)

---
#### Feedback Bot on 7/27/2021, 08:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by akhera99** [comment]
Do you mind showing a full screenshot of the code causing this overlap?

**Comment by CyrusNajmabadi** [comment]
@olegtk intratext adornments probably shouldn't move these guides around.  Can you guys take?

**Comment by olegtk** [comment]
yeah, I reactivated https://developercommunity.visualstudio.com/t/Inline-hint-Experimental---outline-is-/1488288
