### ISSUE TITLE
Experimental C# LSP Completions committed with overtypeable characters don't overtype

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#55187]
**Version Used**: 
![image](https://user-images.githubusercontent.com/2008729/127369036-40aede80-ee75-4606-8464-58aa11280855.png)

**Steps to Reproduce**:

1. Enable C#'s LSP editor + preview completion:
  ![image](https://user-images.githubusercontent.com/2008729/127371130-1205707e-a2c4-4b5d-953b-5c0ddfc7cb7e.png)
2. In a C# file type each character `if (tru`, you'll end up with `if (tru|` and a completion list highlighting `true`
3. Commit the `true` completion item with `)`

Repro: 
![aJ8HUXNXWB](https://user-images.githubusercontent.com/2008729/127371245-f7ed3f8c-593e-48eb-8656-16fce0ab7490.gif)

**Expected Behavior**: `if (true)|`

**Actual Behavior**: `if (true|`

**Comment by jinujoseph** [comment]
https://github.com/dotnet/roslyn/pull/55252 turning off the feature in 17.0.preview3

**Comment by NTaylorMullen** [comment]
After fixing this we should validate if it fixes this issue: https://github.com/dotnet/aspnetcore/issues/34820

Turning off the experimental C# completions ended up resolving the provisional completion issue for me

**Comment by allisonchou** [comment]
The aforementioned feature flag is no longer applicable
