### ISSUE TITLE
GoToDefinition goes to metadata rather than source

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#55189]
I just updated to the latest internal preview (version details below).
Repro: open `compilers.sln`, go into a unittest (such as `TopLevelStatementTests.cs`), and invoke GoToDefinition on a method (such as `ToTestDisplayString`).

GoToDefinition shows me metadata rather than taking me to the source location for this method. See screen capture:

![broken-gotodef](https://user-images.githubusercontent.com/12466233/127378923-b1a7dd73-97ea-4e29-8f96-a4ac17712881.gif)

I have closed and restarted VS already (and killed msbuild.exe/vbcscompiler.exe processes too for good measure).

```
Microsoft Visual Studio Enterprise 2022 Int Preview
Version 17.0.0 Preview 3.0 [31526.353.main]
VisualStudio.17.IntPreview/17.0.0-pre.3.0+31526.353.main
Microsoft .NET Framework
Version 4.8.04084
```

When I try to repro on VS 16.11, GoToDef correctly navigates to the source code for `ToTestDisplayString`.

**Comment by jinujoseph** [comment]
related to [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1361354)

**Comment by sharwell** [comment]
This is tracked by AB#1361354
