### ISSUE TITLE
Source Generators: design-time completion/intellisense and Target Framework not work

### ISSUE THREAD

**Issue by CorrM** [dotnet/roslyn#55199]
**Version Used**: 
![image](https://user-images.githubusercontent.com/5868825/127389946-bdf4f3d7-1ec5-4fcc-a906-6b07ab6ba366.png)

**Steps to Reproduce**:

1. Setup the project 
![image](https://user-images.githubusercontent.com/5868825/127391422-5c9fa181-1d2a-4076-8bb9-fd3f1d01f495.png)
2. Use generated code
![image](https://user-images.githubusercontent.com/5868825/127391515-0e0a799b-3d16-468d-86e6-345d28025a5e.png)
3. Build
![image](https://user-images.githubusercontent.com/5868825/127391579-e2da75ca-5a21-4d68-b9ee-a6874760aa2f.png)

**Expected Behavior**:
design-time completion/intellisense and My `TestProject->Dependencies->Analyzers->Generator` not generated,
mostly VS not catch it as i see it's generated in the path `$(ProjectDir)Generated\Generator\Generator.MySourceGenerator\HelloWorldGenerator.cs`

And only after restart (not change any setting)
![image](https://user-images.githubusercontent.com/5868825/127392214-d59e39e6-5a38-4015-80c0-2aa71f91efe1.png)

**Actual Behavior**:
Nothing of Expected Behavior happens 😄 ,
Also if i change my generator generated namespace to `HelloWorldGeneratedxxx` and rebuild
![image](https://user-images.githubusercontent.com/5868825/127393152-4a9c8ab4-8e7c-42ec-b297-8ee0dedef437.png)
intellisense will work if restart VS(without change any setting)

**Side Problem**
As i read here [StackOverflow](https://stackoverflow.com/a/63889254/3351489) it should my generator work with any Target Framework, but when targeting net5.0 it's never works even after restart Visual Studio it's not completion/intellisense problem as project never build
![image](https://user-images.githubusercontent.com/5868825/127390537-6f8fdcc4-d1a7-4b13-a035-92c4a9eff834.png)
![image](https://user-images.githubusercontent.com/5868825/127390626-88f26e1b-979e-492b-bb86-a6739c6c7b84.png)
```
Rebuild started...
1>------ Rebuild All started: Project: Generator, Configuration: Debug Any CPU ------
Restored C:\Users\CorrM\source\repos\SourceGenTest\SourceGenTest\SourceGenTest.csproj (in 5 ms).
Restored C:\Users\CorrM\source\repos\SourceGenTest\Generator\Generator.csproj (in 31 ms).
1>Generator -> C:\Users\CorrM\source\repos\SourceGenTest\Generator\bin\Debug\net5.0\Generator.dll
2>------ Rebuild All started: Project: SourceGenTest, Configuration: Debug Any CPU ------
2>CSC : warning CS8032: An instance of analyzer Generator.MySourceGenerator cannot be created from C:\Users\CorrM\source\repos\SourceGenTest\Generator\bin\Debug\net5.0\Generator.dll : Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
2>C:\Users\CorrM\source\repos\SourceGenTest\SourceGenTest\Program.cs(9,4,9,23): error CS0103: The name 'HelloWorldGenerated' does not exist in the current context
2>Done building project "SourceGenTest.csproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

When targeting **`netstandard2.0`**(without change any other setting) it's working!
```
Build started...
1>------ Build started: Project: Generator, Configuration: Debug Any CPU ------
1>Generator -> C:\Users\CorrM\source\repos\SourceGenTest\Generator\bin\Debug\netstandard2.0\Generator.dll
2>------ Build started: Project: SourceGenTest, Configuration: Debug Any CPU ------
2>SourceGenTest -> C:\Users\CorrM\source\repos\SourceGenTest\SourceGenTest\bin\Debug\net5.0\SourceGenTest.dll
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

```
Sorry for all this images but i think images is the best to explain that problem
```
@sharwell @chsienki

**Comment by sharwell** [comment]
A binary containing the source generator is required in order for the IDE to light up features. Since the source generator is part of the same solution where it is used (step 1), it is required to build the solution (step 3) and then restart the IDE. Once the IDE is restarted, all source generator features should work as expected.

**Comment by sharwell** [comment]
> As i read here StackOverflow it should my generator work with any Target Framework, but when targeting net5.0 it's never works even after restart Visual Studio it's not completion/intellisense problem as project never build

This applies only to **SourceGenTest.csproj**. The source generator itself (**Generator.csproj**) must target exactly `netstandard2.0`.

**Comment by sharwell** [comment]
> Also if i change my generator generated namespace to HelloWorldGeneratedxxx and rebuild

Note that most daily development will not alter the source generator itself. Any changes to the source generator implementation (code in **Generator.csproj**) results in different runtime behavior, which are only applied by building the project and restarting the IDE. In our experience, this is certainly problematic for the time when the source generator is under active development, but pretty quickly goes back to just working once the generator code stabilizes.

We're investigating ways to remove this requirement, but the .NET Framework makes it difficult to replace the implementation at runtime.

**Comment by CorrM** [comment]
> > Also if i change my generator generated namespace to HelloWorldGeneratedxxx and rebuild
> 
> Note that most daily development will not alter the source generator itself. Any changes to the source generator implementation (code in **Generator.csproj**) results in different runtime behavior, which are only applied by building the project and restarting the IDE. In our experience, this is certainly problematic for the time when the source generator is under active development, but pretty quickly goes back to just working once the generator code stabilizes.
> 
> We're investigating ways to remove this requirement, but the .NET Framework makes it difficult to replace the implementation at runtime.

so i really need to restart VS every time i change something .?! that mean BIG headache deployment

**Comment by CorrM** [comment]
> Since the source generator is part of the same solution where it is used (step 1), it is required to build the solution (step 3) and then restart the IDE

any work around .?

**Comment by sharwell** [comment]
> any work around .?

Yes, source generators deployed via NuGet packages are not subject to this requirement because they are distributed as binaries instead of source.

**Comment by CorrM** [comment]
there any guide ?

**Comment by sharwell** [comment]
If you create a new analyzer package using the Analyzer with Code Fix template (see image), you can place your source generator in the analyzer project and build the package project to create a NuGet package. The solution will also contain a code fix project, but you can remove that if you don't plan to offer any CodeFixProvider or CodeRefactoringProvider implementations.

![image](https://user-images.githubusercontent.com/1408396/127407151-5813e603-d402-41a8-9f83-57c4fdab8215.png)

**Comment by sharwell** [comment]
@chsienki do we have a longer document for how to create a source generator package?

**Comment by chsienki** [comment]
Hmm, creating a SG package is the same as an analyzer. I assumed we had docs for that, but I can't actually find any. @jmarolf ?

**Comment by sharwell** [comment]
@Youssef1313 probably knows

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn-sdk/issues/873 tracks adding a source generator template just like the analyzer & codefix one. Then, [Source Generators overview](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) can get updated to use the template (which should create a NuGet package easily like analyzers template).

**Comment by CorrM** [comment]
> [dotnet/roslyn-sdk#873](https://github.com/dotnet/roslyn-sdk/issues/873) tracks adding a source generator template just like the analyzer & codefix one. Then, [Source Generators overview](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) can get updated to use the template (which should create a NuGet package easily like analyzers template).

thanks i will give it a try

**Comment by sungaila** [comment]
Any plans on supporting this scenario for Visual Studio?

We have source generators for internal use and put the generator and the unit tests in the same solution.

Restarting VS everytime we want to run the unit tests (after modifying the source generator) is a poor experience.

**Comment by sharwell** [comment]
> Any plans on supporting this scenario for Visual Studio?

We are investigating ways to fix this, but we're not yet certain it's possible. The .NET Framework assembly loader generally doesn't like loading multiple versions of the same assembly. It also isn't possible to unload the assembly after it's loaded, so each new build will add a new assembly in memory until you eventually restart the IDE.

**Comment by CorrM** [comment]
> > Any plans on supporting this scenario for Visual Studio?
> 
> We are investigating ways to fix this, but we're not yet certain it's possible. The .NET Framework assembly loader generally doesn't like loading multiple versions of the same assembly. It also isn't possible to unload the assembly after it's loaded, so each new build will add a new assembly in memory until you eventually restart the IDE.

if can't unload it after load, i think it's possible to restart or any like-technique ?
and there another think i notice, when use source generator code highlight going crazy with all functions, class, structs and record will going to white even tooltip know and have correct colors but text editor going crazy.

![image](https://user-images.githubusercontent.com/5868825/128246487-f6492c91-5057-48b2-97b1-737c21895a11.png)

this is `partial` class, src gen will add some fields and methods for it, and to fix that problem i should go to
`UnrealObjectHolderHelper` declaration file (press F12) then back to the code in shown img to get colors back

**Comment by sharwell** [comment]
> have correct colors but text editor going crazy

This is something we've been tracking separately.

@JoeRobich do you have a link to the issue for this?

**Comment by JoeRobich** [comment]
> do you have a link to the issue for this?

@sharwell I think this is the issue https://github.com/dotnet/roslyn/issues/54833

**Comment by jasonmalinowski** [comment]
Going through this conversation I think there's three issues that were raised:

1. Generators need to be netstandard2.0 (which has been addressed)
2. The classification issue, which @JoeRobich linked to the tracking bug there.
3. The issue around generators needing an unload/reload after a change, which we're tracking at #48083.

I'm closing this since I don't think there's anything else unique in this bug, but if I missed something do raise it!
