### ISSUE TITLE
If no cache is present we do not display "incomplete results" message in Ctrl + T search

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#55201]
**Version Used**:  Version 17.0.0 Preview 3.0 [31527.483.main]

**Steps to Reproduce**:

1. delete `.vs` folder
1. Open Roslyn.sln
1. Open `Ctrl + T` search
1. search for `CSharpSyntaxTree`

**Expected Behavior**:
![image](https://user-images.githubusercontent.com/9797472/127402013-d44720ca-bbd8-4053-aca6-acfc9f1b1fdd.png)

**Actual Behavior**:
No Symbol results are shown and there is no indicator that the results are incomplete
![image](https://user-images.githubusercontent.com/9797472/127401951-368abb4b-2f53-4f37-b8bc-9ac63698cb39.png)

**Comment by davkean** [comment]
Here's what I just hit:

![Search](https://user-images.githubusercontent.com/1103906/127402329-3383fe97-c580-4261-bf5e-d2061e2dda95.gif)

**Comment by CyrusNajmabadi** [comment]
I get this expereince:

![image](https://user-images.githubusercontent.com/4564579/127560657-55aef5ec-1dd5-4aff-95b6-c47afc6b8403.png)

continuing to investigate.

**Comment by CyrusNajmabadi** [comment]
With CSharpSyntaxTree:

![image](https://user-images.githubusercontent.com/4564579/127560965-a5f9b1be-6c07-4b3a-9463-dff0436dacf1.png)

**Comment by CyrusNajmabadi** [comment]
I'll capture a video:

**Comment by CyrusNajmabadi** [comment]
![Animation](https://user-images.githubusercontent.com/4564579/127561473-dd602778-271d-4b9e-8101-a4a57125583f.gif)

Everything seems to be working as expected.  I'm on 

![image](https://user-images.githubusercontent.com/4564579/127561512-999a0762-67ad-419b-a181-86a80a9d2114.png)

**Comment by CyrusNajmabadi** [comment]
Assigning back to Jon to continue this as he repros teh right behavior on his machiens as well.

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/55253
