### ISSUE TITLE
Delegate types are only synthesized for lambdas with parameter types and return type that are valid type arguments

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#55217]
Delegates are currently only synthesized for lambda expressions and method groups when all parameter types and return type are valid as generic type arguments.
```csharp
class Program
{
    unsafe static void Main()
    {
        var d1 = (ref int i) => { };  // ok
        var d2 = (int* p) => { };     // CS8917: The delegate type could not be inferred.
    }
}
```

**Comment by jaredpar** [comment]
I presume this includes `ref struct` as well hence `Span<T>` would be impacted
