### ISSUE TITLE
DiagnosticAnalyzer implementations need a syntax filter to exclude their overhead from unrelated light bulbs

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#55228]
**Version Used**: 17.0.0-preview-3.0-[31527.483.main]

**Steps to Reproduce**:

1. On a line which does not contain a cast (or a suppression for a cast), press <kbd>Ctrl</kbd>+<kbd>.</kbd>

**Expected Behavior**:

The Remove Unnecessary Cast analyzer does not execute as part of calculating the light bulb.

**Actual Behavior**:

The Remove Unnecessary Cast analyzer runs as part of calculating the light bulb, but will never offer any suggestions. This calculation delays the operations which are included.

**List of top-hitting analyzers for this**:

* [ ] Remove unnecessary suppression (only needs to run on a line with a suppression)
* [ ] Remove unnecessary cast (only needs to run on a line with a cast)
* [ ] Simplify type name (only needs to run if the error list is currently showing a Simplify Type Name diagnostic on the current line)

**Comment by mavasani** [comment]
This has been completed
