### ISSUE TITLE
Source Generators: Produce single NuGet package that includes net5.0 library + Source Generator

### ISSUE THREAD

**Issue by Timovzl** [dotnet/roslyn#55229]
Imagine the following scenario:

- ClassLibraryA is a `net5.0` project that exposes an abstract class from which consumers can inherit. It uses net5.0 features.
- SourceGeneratorB is a `netstandard2.0` project that contains a source generator. The source generator reacts to the presence of subclasses of the abstract class defined by ClassLibraryA. It does so _without a hard reference_ (which it could not take anyway), based on full type names.
- ConsumerC wants to use this functionality (i.e. create such a subclass and thus trigger the corresponding source generation). It wants to do so by simply consuming a single NuGet package.

**How can we create a single NuGet package (named ClassLibraryA) that ConsumerC can depend on?** Note that this must lead to ConsumerC getting the source generator, too.

Is this possible at all? If so, are there any examples that demonstrate the solution? If not, why not, and what is the closest alternative?

**Comment by koenbeuk** [comment]
You can take a look at https://github.com/koenbeuk/ScenarioTests/blob/master/src/ScenarioTests/ScenarioTests.csproj as an example.

Line 32 ensures that the Generator is built together with the classlib.
Line 41 then ensures that the generator DLL is embedded correctly with the generated nuget package.

**Comment by Timovzl** [comment]
Thanks @koenbeuk.

Just so I understand this correctly: ScenarioTests.csproj would be the equivalent of ClassLibraryA in my example? And a consuming project can include ScenarioTests as a NuGet package and get the desired result?

**Comment by koenbeuk** [comment]
@Timovzl correct

**Comment by Timovzl** [comment]
@koenbeuk Great. Before I start publishing all sorts of packages, I'm trying to verify my implementation of this approach with regular project references. However, ConsumerC is not receiving SourceGeneratorB.

Do you know if the desired result can also be achieved through straight project references, i.e. with a consumer project inside the same solution?

**Comment by PathogenDavid** [comment]
> Before I start publishing all sorts of packages, I'm trying to verify my implementation of this approach with regular project references.

I don't think analyzers (or source generators) can be transitive like normal project references are. Either way I would not use project references to validate a NuGet package is working correctly, there's too many differences for how things work internally.

You should set up a local package feed and test actual NuGet packages with that. Run `dotnet new nugetconfig` in the solution directory of `ConsumerC` to create a template `nuget.config` then [add a package source](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources) for a directory on your computer and place your packed nupkg in it.

(Note that NuGet will cache the extracted package even though it's local, so either change the version number every time you pack or go to the path printed by `dotnet nuget locals global-packages --list` and manually delete the cached package.)

**Comment by koenbeuk** [comment]
@Timovzl 

Perhaps take a look at one of my sample projects for ScenarioTests: https://github.com/koenbeuk/ScenarioTests/blob/master/samples/BasicSample/BasicSample.csproj

I'm perfectly able to use my generator within my sample simply as a project reference. If you want to ensure that your nuget package works the way it does then take a look at @PathogenDavid comment

**Comment by Timovzl** [comment]
@koenbeuk Looking at your BasicSample.csproj, I notice that with project references, you are referencing both ScenarioTests.csproj _and_ ScenarioTests.Generator.csproj. So far, this is what I have been doing myself. However, needing to reference two projects led me to believe that I would need to reference two NuGet packages as well, which is not what I want.

Am I correct in concluding that with NuGet packages, you can get the generator transitively, but with project references, you cannot?

**Comment by koenbeuk** [comment]
> Am I correct in concluding that with NuGet packages, you can get the generator transitively, but with project references, you cannot?

That is correct, in https://github.com/koenbeuk/ScenarioTests/blob/master/src/ScenarioTests/ScenarioTests.csproj I'm manually adding the source generator DLL inside the nuget package, hence when you install it you get both. It does not reference the source generator directly.

**Comment by Timovzl** [comment]
Thanks, everybody.

I can confirm that it is sufficient for the library project to have the following reference to the generator project:

```
  <ItemGroup>
    <!-- Package the generator in the analyzer directory of the nuget package -->
    <None Remove="$(OutputPath)/$(AssemblyName).Generator.dll" />
    <None Include="$(OutputPath)/$(AssemblyName).Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
```

(I am not sure if the `Remove` line does anything. It might be unnecessary.)

When the library is consumed _as a NuGet package_, the generator is automatically included as an analyzer.

When the library is consumed _through a project reference_ (such as in the library's own unit test project), we need the following:

```
  <ItemGroup>
    <ProjectReference Include="..\MyLibrary\MyLibrary.csproj" />
    <ProjectReference Include="..\MyLibrary.Generator\MyLibrary.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
```
