### ISSUE TITLE
VS2015, uncomment action: bug if single-line commented text contains /* and */

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn#5522]
**Steps to reproduce**:

* Insert the following code:
```c#
namespace UncommentTest
{
    class Program
    {
        static void Main(string[] args)
        {
            //Client.Headers.Add(HttpRequestHeader.Accept, @"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
            //    values["something"] = answers.Single(a => string.Equals(a.Key.Trim(), question.Trim(), StringComparison.InvariantCultureIgnoreCase)).Value; // (2)
            //    Client.Headers.Add(HttpRequestHeader.Accept, @"text/javascript, text/html, application/xml, text/xml, */*");
        }
    }
}
```
* Place the cursor at the start of the second comment (the line marked with "// (2)")
* Click the "Uncomment the selected lines" toolbar button (or same from menu, or Ctrl-E, CTRL-U etc)

**Actual result:**
Visual Studio removes the `/*` and `*/` from comment lines 1 and 3, the text between them become selected. Actual comment out symbols (`//`) are left untouched

**Expected behavior:**
IDE uncomments the second line of the comment.

**Comment by Pilchie** [comment]
This was already reported as #548, and should be fixed in the next VS Update.

**Comment by ig-sinicyn** [comment]
@Pilchie Thanks!
