### ISSUE TITLE
Error for Watch and CallStack-View in IDE

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#55275]
**Version Used**: Visual Studio 2022 Version 17.0.0 Preview 2.1

**Steps to Reproduce**:
Debug code

**Expected Behavior**:
Able to use "Watch" and "Callstack"

**Actual Behavior**:
Error is displayed:

![grafik](https://user-images.githubusercontent.com/26689688/127669713-47ffb794-14b8-4b55-a523-aa72dbf63030.png)

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn issue.  please file VS feedback using:

![image](https://user-images.githubusercontent.com/4564579/127692481-7921d779-a050-45c3-9aba-ed16c03bdcc1.png)

I also recommend you try repairing your VS.  Beyond that, it will take a deeper investigation to see what's wrong.

**Comment by bernd5** [comment]
For reference: https://developercommunity.visualstudio.com/t/debugger-and-callstack-shows-an-error-message-is-n/1495641
