### ISSUE TITLE
VSNotificationServiceFactory

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#55282]

**Comment by CyrusNajmabadi** [comment]
Closing out.  We do not need to track work like this with N issues.  We can have a single issue that breaks out hte individual pieces where we can remove/complete the subpieces as necessary if we even get around to the work.

**Comment by sharwell** [comment]
The other issue is a story. These are intentionally broken out as individual child work items.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
