### ISSUE TITLE
C# Rude edits are duplicated in Web projects

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#55293]
**Version Used**: 
![image](https://user-images.githubusercontent.com/2008729/127703687-27af703f-2bc7-4536-8a6d-e8d29e14edfc.png)

**Steps to Reproduce**:

1. Create a new Blazor Server project
2. F5 to run with debugging
3. Open Error.cshtml.cs in the Pages folder
4. Change `OnGet` to `OnGet3`

**Expected Behavior**: Single rude edit stating `Renaming method requires restarting the application`.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2008729/127703811-8451d5c8-01e6-4aa9-be7d-562d2abc4342.png)

------------

**Notes**:

- This does not happen for regular C# console apps
- This also manifests in C# in Razor files

**Comment by tmat** [comment]
@dibarbet

**Comment by tmat** [comment]
@isadorasophia

**Comment by tmat** [comment]
Moving to debugger: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1363800
