### ISSUE TITLE
StackOverflowException in Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#5529]
Without a debugger attached, this crashes and restarts VS2015 RTM.

With debugger attached, the next exception is thrown from SpellChecker addin:

```
StackOverflowException in Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll

System.StackOverflowException was unhandled
  HResult=-2147023895
  Message=Exception of type 'System.StackOverflowException' was thrown.
  InnerException: 
```

Offending line (from SolutionProjectSpellCheckControl.xaml.cs at 367,78):

``` csharp
                    if(textView.GetLineAndColumn(position, out line, out column) == VSConstants.S_OK &&
                      textView.SetCaretPos(line, column) == VSConstants.S_OK)
```

`textView` is of type `Microsoft.VisualStudio.Editor.Implementation.VsTextViewAdapter`.

I suspect the exception comes from `SetCaretPos`, because in the attached VS the dialog `[Line commit] Committing line` is displayed.

Repro steps:
1. Download/build sources from 'solutionfolders' branch at https://github.com/bkoelman/VSSpellChecker/tree/solutionfolders.
2. F5 to run; in second VS instance, open Roslyn.sln
3. In solution explorer, click on project BasicCompilerSemanticTest
4. Go to Tools > Spell Checker > Spell Check Selected Items
5. Wait a few secs to complete the scan. In the spell check window, click on Word column to sort on it
6. Scroll down to first occurence of word 'Allaire' (in file: roslyn\src\Compilers\VisualBasic\Test\Semantic\Binding\T_68086.vb)
7. double-click on this line (should open document with caret at position): crash

**Comment by Pilchie** [comment]
This is another case of a pathological file where we recurse too deeply into an expression and blow the stack.

**Comment by CyrusNajmabadi** [comment]
Haven't heard anything else about this, and i don't see anything in prism/watson.  Need to know if this is still an issue.
