### ISSUE TITLE
AnalyzerFileReference loading non-ngen file

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#553]
we shouldn't load non-ngen file when ngen file exist.

...
Name
 Image Load Microsoft.CodeAnalysis.EditorFeatures.dll (D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\)
+ ntoskrnl!PsCallImageNotifyRoutines
 + ntoskrnl!MiMapViewOfImageSection
  + ntoskrnl!MiMapViewOfSection
   + ntoskrnl!NtMapViewOfSection
    + ntdll!ZwMapViewOfSection
     + wow64!whNtMapViewOfSection
      + wow64!Wow64SystemServiceEx
       + wow64cpu!ServiceNoTurbo
        + wow64!RunCpuSimulation
         + wow64!Wow64LdrpInitialize
          + ntdll!_LdrpInitialize
           + ntdll!LdrInitializeThunk
            + ntdll!ZwMapViewOfSection
             + kernelbase!MapViewOfFileExNuma
              + kernelbase!MapViewOfFileEx
               + clr!CLRMapViewOfFileEx
                + clr!MappedImageLayout::MappedImageLayout
                 + clr!PEImageLayout::Map
                  + clr!??PEImage::GetLayoutInternal
                   + clr!??PEImage::GetLayout
                    + clr!??PEImage::HasNTHeaders
                     + clr!PEImage::VerifyIsILOrNIAssembly
                      + clr!AssemblyNameNative::GetFileInformation
                       + mscorlib.ni!AssemblyName.GetAssemblyName
                        + microsoft.codeanalysis.desktop.ni!AnalyzerFileReference.get_Display

**Comment by mavasani** [comment]
@heejaechang I thought AssemblyName.GetAssemblyName cannot cause an image load, it fetches the assembly name without loading the assembly into appdomain. https://msdn.microsoft.com/en-us/library/system.reflection.assemblyname.getassemblyname(v=vs.110).aspx
Are we sure ngen image was available? 
In host analyzer manager we just invoke Assembly.Load(AssemblyName.GetAssemblyName(fullPath)), where fullPath is path to managed assembly, but this should theoretically not load the managed assembly if ngen assembly is available.

**Comment by heejaechang** [comment]
Microsoft.CodeAnalysis.EditorFeatures.dll (D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies)

it is loaded from private assemblies, so ngen image must exist. 

can you do windbg sxe ld EditorFeatures to check?

I think the callstack above is from etl trace from RPS run. let me re-check etl trace tomorrow.

**Comment by mavasani** [comment]
_it is loaded from private assemblies, so ngen image must exist._

Are you sure that is always true?
I just installed the latest drop from VSPro_1 branch and see that none of Microsoft.CodeAnalysis.* assemblies are ngen'ed (_ngen display Microsoft.CodeAnalysis.EditorFeatures_). Opening a C# project loads EditorFeatures from private assemblies, confirmed through procexplorer.
So I explicitly ngen'ed Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll and Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.dll and then opening a C# project only loads the native images.

**Comment by mavasani** [comment]
Please re-open if you have a repro machine with ngen'ed images installed and AnalyzerFileReference is causing load of non-ngen image.

**Comment by heejaechang** [comment]
Installing VS should ngen. But since it doesn’t force ngen execution right away, there might be a period you don’t see ngen image.

Do

ngen executeQueuedItems

you will see all of VS ngen request being  executed right away.


-          Heejae

**Comment by mavasani** [comment]
Thanks Heejae. That command force ngen'ed and after that I verified that opening a C# project + applying IDE fixes only loads native images, one from private assemblies is never loaded. Probably something went wrong in the RPS run?

**Comment by heejaechang** [comment]
I just checked recent etl from RPS, looks like I can't find non-ngened image anymore. so might have been an issue of RPS or drop for that particular run.
