### ISSUE TITLE
Test plan for "raw string literals"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#55306]
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/raw-string-literal.md
Championed issue: https://github.com/dotnet/csharplang/issues/4304

## Compiler
- [x] Address PROTOTYPE comments
- [x] test semantic model APIs (GetTypeInfo in literal and expressions in holes)
- [x] Review any public API changes
- [x] nullability
- [x] consider improving diagnostic for bad indent
- [x] Expression trees (see `AsStringInExpressionTrees_01`)
- [x] constant interpolations (see `TestInConstantFieldInitializer...`).
- [x] Update [test plan](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Compiler%20Test%20Plan.md)
- [x] verify order of evaluation of interpolations, definite assignment
- [x] LangVer
- [x] balanced and unbalanced open and close braces
- [x] test parsing with `@$$` and `$$@` (errors)
- [x] test interpolated single-line raw string with newlines in interpolation hole/expression
- [x] nested interpolated strings of different kinds (interpolated, interpolated verbatim, interpolated raw)
- [x] formats
- [x] `SyntaxNormalizer` (see `TestSpacingOnRawInterpolatedString`)
- [x] Conversion of interpolations to `IFormattable` and `FormattableString` result in calling `FormattableStringFactory.Create`, otherwise natural type `string` results in `string.Format`
- [x] Newline in format specifier (see `TrailingSpaceInFormatSpecifier02`)
- [x] interpolation handlers

## Productivity
- [x] Review IDE code that references `SyntaxKind.InterpolatedStringStartToken` (there's a few locations)
- [x] Typing/completion
- [x] Colorization
- [x] QuickInfo
  - [x] test multi-line in immediate window and QuickWatch/watch
  - [x] QuickInfo should display constant value
- [x] Formatting/indentation
- [ ] below minbar below:
- [x] Display indentation line
- [ ] Convert to raw string literal (PR https://github.com/dotnet/roslyn/pull/59180)
- [x] Add a `"` on both ends
- [ ] Add a `$`
- [ ] Interaction with regexes `/*regex*/ """[0-9a-z]*""";` (should colorization correctly)
- [ ] Interaction with datetime completion `DateTime.Now.ToString(... typing here ...)`

IDE follow-up work: https://github.com/dotnet/roslyn/issues/58356
For exploratory testing, see IDE test plan: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Manual-Testing.md

**Comment by allisonchou** [comment]
Link to Roslyn IDE planned feature list: https://github.com/dotnet/roslyn/issues/58356

**Comment by jcouv** [comment]
Closing as completed :-) The feature was merged and follow-up IDE work is tracked by https://github.com/dotnet/roslyn/issues/58356
