### ISSUE TITLE
VSMac broken by new dependency on IManagedHotReloadService in EditorFeatures

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#55308]
See my comment on this PR:
https://github.com/dotnet/roslyn/pull/55074#issuecomment-890286813

Presumably EnC moving to EditorFeatures was driven by a business goal. We need to understand how to reconcile that goal with the goal of not breaking VSMac.

**Comment by KirillOsenkov** [comment]
FYI @jinujoseph @davidwengier @tmat this is going to be high priority because VSMac will be unable to insert a Roslyn with this change.

We can't workaround either because we'd need to implement an inaccessible interface and MS.VS.Debugger.Contracts.dll doesn't have IVT to us.

**Comment by tmat** [comment]
Making `IManagedEditAndContinueDebuggerService` and `IManagedHotReloadService` lazy would fix this, right?

**Comment by KirillOsenkov** [comment]
I think so, if the parts never need to be instantiated MEF won’t try to satisfy imports on them.

**Comment by tmat** [comment]
@KirillOsenkov The interface is imported by the debugger, so if there is no debugger there is no import. I'll make them lazy.
