### ISSUE TITLE
Request: a way to collapse regions from the *end construct*

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#5531]
[filed on behalf of a fellow attendee at VSLive! NY]

It'd be great if there was a way to collapse a region from the end-construct. Like, I have a long method or a long class and I'm near the end. I can scroll up to try to find the start construct, but when I'm scrolling, I often end up missing it and closing the wrong one.

I'm not sure what exactly it would look like. Any ideas?

**Comment by Pilchie** [comment]
This sounds like a request for the core editor (@olegtk and @markw-t).  However, two ideas are:
1. Use the command (Ctrl+M, Ctrl+M)
2. Use "Go to matching brance" (Ctrl + ]), and then collapse from there.

**Comment by gafter** [comment]
@Pilchie What is the best way to move this from our issue database to the core editor's?

**Comment by Pilchie** [comment]
Manually create an issue in their VSTS area path.

**Comment by CyrusNajmabadi** [comment]
So this is possible.  You can just double-click anywhere in the region tag (including teh end) to collapse it.
