### ISSUE TITLE
Any source generator doesn't work when using external classes that are defined out of a project having the source generator itself

### ISSUE THREAD

**Issue by lafuta120** [dotnet/roslyn#55310]
<b>.NET SDK Version:</b> 5.0.302
<b>Roslyn Version:</b> 3.9.0
<b>Visual Studio Version:</b> 16.10.4 (2019 community)

There's no unexpected behavior when I just declare all the utilized types within the same project of source generators, however, even if only one of types I use at the 'Excute' method in a generator is not a component of the project, the entire source generator unit generates no files ever. Here's an example.<br /><br />

ClassLibrary.csproj:
```
// using directives are omitted for brevity
namespace ClassLibrary {
    public class SomeClass {
        public int Value { get; set; }
    }
    public static class SomeStatic {
        public static string GetStuff() => "Stuff";
    }
}
```

and MyGenerators.csproj, which references the <i>project</i> ClassLibrary (using ProjectReference but the error also occurs when Reference to a .dll file is used):
```
// also directives omitted
namespace MyGenerators {
    [Generator]
    public class SomeGenerator : ISourceGenerator {
        public void Initialize (GeneratorInitializationContext context) {
        }
        public void Execute (GeneratorExecutionContext context) {
            // ClassLibrary.SomeClass asd = new(); -- (1)
            // string stuff = ClassLibrary.SomeStatic.GetStuff(); -- (2)
            // Type type = typeof(ClassLibrary.SomeClass); -- (3)
            string source = @"
namespace Hello {
    public static World {
    }
}
";
            context.AddSource("Experimental", source);
        }
    }
}
```

That code is normal, behaves the way we can expect. But if I release either note to executed code on those above, (1), (2), and (3) in this context, rebuild the project, and reload Visual Studio, then no 'generated file' gets appeared. In addition, the same is true for the directory where generated files exist, meaning, the generator does not work <b>totally</b>. I really can't understand why it happens and what action I have to do in order to fix the error. Please leave a solution if anyone reading this issue knows how to do.

**Comment by jaredpar** [comment]
Do you have a small repro project that we can look at where you hit this issue? Based on the info here it's hard to determine what is going on. A small repro would help.

**Comment by lafuta120** [comment]
There's no repro needed. The bug occurs just when a class out of the source generator project itself is used in that Execute method. It's all. Because of this, I've been being unable to reference any class library project from a generator. It eventually results in that 'too heavy and complex' source generator project.

**Comment by Bosch-Eli-Black** [comment]
@jaredpar We're running this issue as well. Would you mind reopening this? I'd be happy to provide a sample repro 🙂

**Comment by Bosch-Eli-Black** [comment]
@jaredpar Ah, never mind, this issue is the same as https://github.com/dotnet/roslyn/issues/57997#issuecomment-1024601830

**Comment by Bosch-Eli-Black** [comment]
By the way, to anyone else who runs across this issue:

Let's say `MyProject` uses `MyAnalyzer`, and `MyAnalyzer` depends on `AnalyzerCommon`.

`MyProject.csproj` must look like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyAnalyzer\MyAnalyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="False" />
                 <!-- For AnalyzerCommon, `ReferenceOutputAssembly` must be *True*! -->
		<ProjectReference Include="..\AnalyzerCommon\AnalyzerCommon.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="True" />
	</ItemGroup>
```


The key is that your project must reference both `MyAnalzyer` *and* `AnalyzerCommon`, and `MyAnalzyer` must have `ReferenceOutputAssembly="False"` but `AnalyzerCommon` must have `ReferenceOutputAssembly="True"`


See https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145 for a complete discussion 🙂
