### ISSUE TITLE
Improve `ILanguageService` public interface documentation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#55326]
Since `ILanguageService` is a public interface. It's worth extending the doc comment with usage example. Do I have to duplicate `MefWorkspaceServices` class like what's done in Roslynator?

https://github.com/JosefPihrt/Roslynator/blob/master/src/Workspaces.Core/Host/Mef/MefWorkspaceServices.cs

If that's the case, consider adding a public api to ease usage if one doesn't already exist.

**Comment by sharwell** [comment]
I'm not aware of any public language services (public interfaces that extend `ILanguageService`). Is there a specific reason why you would be interested in using one of them?

**Comment by Youssef1313** [comment]
@sharwell The main reason is I wanted to create a `LanguageFeatureSupportService`, so in an analyzer I can do things similar to 

```csharp
GetLanguageService<LanguageFeatureSupportService>().IsFeatureSupported(LanguageFeature.XXX) // possible take the compilation?
```

so I don't have to create derived classes for analyzers (mainly wanted to try this in dotnet/roslyn-analyzers - but it also turned into a personal interest to know how to use this public interface, or otherwise why it's public?).

**Comment by Youssef1313** [comment]
@sharwell Can you provide some help here? Thanks!

**Comment by sharwell** [comment]
@Youssef1313 Workspaces and MEF are not available for use in analyzers, so this probably would not work for that scenario.

**Comment by Youssef1313** [comment]
@sharwell Thanks! It will be great if the documentation reflects this clearly. If you don't mind, I'll continue the conversation on Discord for an approach I'm taking not relying on Roslyn's `ILanguageService`

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
