### ISSUE TITLE
TableEntriesFactory<TItem, TData> blocks on asynchronous work inside a lock

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#55339]
**Version Used**: 16.9.3 and newer

🔗 Also filed as [AB#1301172](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1301172)

```
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground<System.Collections.Immutable.ImmutableArray<System.__Canon>>(System.Threading.Tasks.Task<System.Collections.Immutable.ImmutableArray<System.__Canon>> task, System.Threading.CancellationToken cancellationToken) Line 52	C#	Symbols loaded.
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.VisualStudioBaseDiagnosticListTable.LiveTableDataSource.TableEntriesSource.GetItems() Line 291	C#	Symbols loaded.
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory<Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.DiagnosticTableItem, Microsoft.CodeAnalysis.Diagnostics.DiagnosticsUpdatedArgs>.AggregatedEntriesSource.GetItems() Line 156	C#	Symbols loaded.
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.TableEntriesFactory<Microsoft.VisualStudio.LanguageServices.Implementation.TableDataSource.DiagnosticTableItem, Microsoft.CodeAnalysis.Diagnostics.DiagnosticsUpdatedArgs>.GetSnapshot(int versionNumber) Line 78	C#	Symbols loaded.
```

https://github.com/dotnet/roslyn/blob/f11cc592efef4ffc62af1938cb2654c3a9267bfc/src/VisualStudio/Core/Def/Implementation/TableDataSource/TableEntriesFactory.cs#L63-L77

https://github.com/dotnet/roslyn/blob/f11cc592efef4ffc62af1938cb2654c3a9267bfc/src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioBaseDiagnosticListTable.LiveTableDataSource.cs#L289-L296

**Comment by CyrusNajmabadi** [comment]
Unless easy to fix, I don't think we should touch this. This goes away with pull diagnostics entirely.

**Comment by sharwell** [comment]
@CyrusNajmabadi This is a 17.0 priority. Last I checked there is no ETA for a complete switch to pull diagnostics.

**Comment by CyrusNajmabadi** [comment]
Like i said, if tis' a small amount of work, that's fine.  However, we intend to get pull diagnostics working in 17.0.  So i woudl not expend a bunch of effort in changing this if we're just going to throw all this code away anyways.

**Comment by CyrusNajmabadi** [comment]
Closing out as this type is gone.
