### ISSUE TITLE
[Scripting] "private" modifier on script variables and members should mean "file private"

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5537]
The goal is to provide a mechanism how to prevent members from bleeding out of a script when it's #loaded.

**Comment by tmat** [comment]
FYI @MadsTorgersen @amcasey @gafter

**Comment by amcasey** [comment]
@tmat Do you have a link to the design notes?

**Comment by amcasey** [comment]
Moving to @cston, per @ManishJayaswal.

**Comment by gafter** [comment]
Imagining this extended to the "normal" C# language, would this mean I could now declare "private" classes that are only usable within that compilation unit? I guess the compiler would have to mangle the name to prevent a clash, or add a compilation-unit-specific compiler-generated class to contain it?

**Comment by tmat** [comment]
@gafter We might not need to mangle if we use it in regular C#. We might be able to use the CLR "privatescope" visibility.

**Comment by tmat** [comment]
@gafter Just an idea :) 
private private = visible within a file
private protected = visible within assembly and subtypes
private internal = visible within assembly (never outside of assembly, regardless of InternalsVisibleTo)

**Comment by gafter** [comment]
No matter what CLR visibility we use, we need to make sure the name can be reused elsewhere, which is why I suggested mangling the name.

**Comment by ManishJayaswal** [comment]
We decided to not use this mechanism to hide members of the loaded script. We are not convinced if hiding actually makes sense in scripting scenario where people deal with source text all the time.
