### ISSUE TITLE
Improve detection of availability of GAC in GacFileResolver

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5538]
Currently we check for absence of `AssemblyLoadContext`. Consider a better check (perhaps the presence of `Assembly.GlobalAssemblyCache` once CoreCLR mscorlib is cleaned up).

**Comment by gafter** [comment]
@tmat can you please assign this to the appropriate team? I don't know from the description what the problem is or which component is implicated.

**Comment by kennethy2** [comment]
I am not sure of the problem either we need a more in depth knowledge of the problem
