### ISSUE TITLE
Add further options for the generation of expression-bodied members

### ISSUE THREAD

**Issue by IanKemp** [dotnet/roslyn#55398]
If you allow Visual Studio to convert a member body to an expression, it always generates the expression on the same line as the member declaration:

```csharp
public int GenerateFoo()
{
    return 42;
}
```

becomes:

```csharp
public int GenerateFoo() => 42;
```

But sometimes the member names and/or expressions (e.g. LINQ) are quite long and complex, and as a result I'd like to break them onto the next line, e.g.:

```csharp
public int GenerateFoo() =>
    42;
```

or:

```csharp
public int GenerateFoo()
    => 42;
```

There is no option in VS under `Options > Text Editor > C# > Code Style > General > Expression preferences` to customise this sort of code generation, but it would be useful if such an option did exist.

In fact, it would be far more flexible if, instead of just having a bunch of hard-coded options to cover all possible scenarios, you could specify a piece of text as a template, e.g.:

```
public {MemberName}()
    => {ExpressionBody}
```

and the relevant bits would be replaced at runtime - similarly to how VS's class template file works.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
