### ISSUE TITLE
An active inline rename session is still active

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#554]
Ported from TFS WorkItem: **1120490**

------------------------------

**Repro Steps:**

Extract local for all occurrences of **this**. May have to try a few times.

&nbsp;

Module M<BR>&nbsp;&nbsp;&nbsp; Friend Function GetInfoAsync() As Dog<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim expression As ExpressionSyntax = Nothing

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim curr = DirectCast(<FONT style="BACKGROUND-COLOR: #ffff00">expression.Parent</FONT>, ExpressionSyntax)<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If curr Is expression.Parent Then<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Return New Dog(**expression.Parent**.Span)<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Return Nothing<BR>&nbsp;&nbsp;&nbsp; End Function<BR>End Module

Friend Class TextSpan<BR>End Class

Friend Class ExpressionSyntax<BR>&nbsp;&nbsp;&nbsp; Public Property Parent As ExpressionSyntax<BR>&nbsp;&nbsp;&nbsp; Public Property Span As TextSpan<BR>End Class

Friend Class Dog<BR>&nbsp;&nbsp;&nbsp; Public Sub New(span As Object)<BR>&nbsp;&nbsp;&nbsp; End Sub<BR>End Class

------------------------------

**Revisions:**

1) Created By Andrew Casey (ROSLYN) (2/5/2015 5:07:26 PM)

(Dump available, see TFS WorkItem 1120490)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/10/2015 9:15:05 AM)

Can you take a look at this dump and see if you can figure out what's up?

------------------------------

**Comment by dpoeschl** [comment]
@amcasey - Back to you for verification.

**Comment by amcasey** [comment]
When I follow the repro steps, the new local is introduced *after* ```curr```, resulting in a binding error.
