### ISSUE TITLE
Completion does not update documentation from project references

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55418]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-not-updating-vs2022/1493716)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:VS2019]
I'm using VS2022 Preview and I noticed the Intellisense not updating when I add to my comments.

My method comments look like this:
! [2021-08-03 09_49_51-AmaraCode.RainMaker - Microsoft Visual Studio Preview.png] (https://aka.ms/dc/image?name=Bf4ca23dbdac6479c94522ed5470b4b23637635990244072493_2021-08-03_09_49_51-AmaraCode.RainMaker_-_Microsoft_Visual_Studio_Preview.png&tid=f4ca23dbdac6479c94522ed5470b4b23637635990244072493)

which produce this output.

! [2021-08-03 09_40_44-AmaraCode.RainMaker - Microsoft Visual Studio Preview.png] (https://aka.ms/dc/image?name=Bf23b0245779a4f5ea76d7ae31bcedb31637635989495675722_2021-08-03_09_40_44-AmaraCode.RainMaker_-_Microsoft_Visual_Studio_Preview.png&tid=f23b0245779a4f5ea76d7ae31bcedb31637635989495675722)

After I change my comments to look like this
! [2021-08-03 09_41_41-AmaraCode.RainMaker - Microsoft Visual Studio Preview.png] (https://aka.ms/dc/image?name=Bba65b45adf1b4a1da8dfce210a2ddc62637635990940694279_2021-08-03_09_41_41-AmaraCode.RainMaker_-_Microsoft_Visual_Studio_Preview.png&tid=ba65b45adf1b4a1da8dfce210a2ddc62637635990940694279)

The Intellisense output is still the same:
! [2021-08-03 09_42_04-AmaraCode.RainMaker - Microsoft Visual Studio Preview.png] (https://aka.ms/dc/image?name=B32b1d0b8ae8f4023951e179400dbd9a6637635991556011665_2021-08-03_09_42_04-AmaraCode.RainMaker_-_Microsoft_Visual_Studio_Preview.png&tid=32b1d0b8ae8f4023951e179400dbd9a6637635991556011665)

The only way I've been able to get it to update is to close and restart VS2022 preview.  After doing so the Intellisense updates properly.
! [2021-08-03 09_43_38-AmaraCode.RainMaker - Microsoft Visual Studio Preview.png] (https://aka.ms/dc/image?name=B6aee7ea31f2a4c2895e396981a89c5ba637635992365406609_2021-08-03_09_43_38-AmaraCode.RainMaker_-_Microsoft_Visual_Studio_Preview.png&tid=6aee7ea31f2a4c2895e396981a89c5ba637635992365406609)

Hope this helps.

---
#### Scott D on 8/3/2021, 11:53 AM: 

<p>Update to this issue.</p>
<p>I do not have to close VS2022 to get the intellisense to update.  I only have to close the file containing the update to the comment.</p>
<p>Here is a link to the screen recording.  I had to record in full screen because OBS was not capturing the intellisense popup while just recording VS.</p>
<p>[<a target='_blank' href="https://youtu.be/1O3Pcr1towQ">https://youtu.be/1O3Pcr1towQ</a>](Unlisted video on YouTube)</p>

#### Feedback Bot on 8/3/2021, 11:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/4/2021, 10:17 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
### Steps to reproduce

1. In project A, define the following type:

    ```cs
    /// <summary>Summary</summary>
    public class MyClass { }
    ```

2. In project B (which references A), press <kbd>Ctrl</kbd>+<kbd>Space</kbd> to bring up completion, and type `MyC`
3. Scroll to `MyClass` in the completion list, and observe the summary comment for the completion item
4. Change the summary comment to

    ```cs
    /// <summary>Summary comment</summary>
    public class MyClass { }
    ```

5. Repeat steps 2 and 3
6. Close and reopen the document used for step 2
7. Repeat steps 2 and 3 again

### Expected results

* After step 3, the summary comment is `Summary`
* After step 5, the summary comment is `Summary comment`
* After step 7, the summary comment is `Summary comment`

### Actual results

* ✔ After step 3, the summary comment is `Summary`
* ❌ After step 5, the summary comment is `Summary`
* ✔ After step 7, the summary comment is `Summary comment`

**Comment by DreadLordMikey** [comment]
I am experiencing the same issue, but the XML documentation comments are on a file _within the same project_.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
