### ISSUE TITLE
`LongestCommonSubsequence` updates sometimes cannot be filtered out

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#55410]
Roslyn's LSP semantic tokens implementation originally relied on [LongestCommonSubsequence](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs). We are now switching to [Razor's implementation](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextDiffer.cs) since the results of Roslyn's LCS are not correct since occasionally Updates cannot be filtered out.

For example, take this case (EDIT: fixed this to show an actual problem case):

**Before:**
``` C#
fo r (int i = 0;/*c*/; i++)
{

}
```

**After:**
``` C#
for (int i = 0;/*c*/; i++)
{

}
```

Original tokens:
```
0
fo
		[0]	0	int
		[1]	0	int
		[2]	2	int
		[3]	8	int
		[4]	0	int

1
r
		[5]	0	int
		[6]	3	int
		[7]	1	int
		[8]	30	int
		[9]	0	int

2
(
		[10]	0	int
		[11]	2	int
		[12]	1	int
		[13]	36	int
		[14]	0	int

3
int
		[15]	0	int
		[16]	1	int
		[17]	3	int
		[18]	15	int
		[19]	0	int

4
i
		[20]	0	int
		[21]	4	int
		[22]	1	int
		[23]	7	int
		[24]	0	int

5
=
		[25]	0	int
		[26]	2	int
		[27]	1	int
		[28]	21	int
		[29]	0	int

6
0
		[30]	0	int
		[31]	2	int
		[32]	1	int
		[33]	19	int
		[34]	0	int

7
;
		[35]	0	int
		[36]	1	int
		[37]	1	int
		[38]	36	int
		[39]	0	int

8
/*c*/
		[40]	0	int
		[41]	1	int
		[42]	5	int
		[43]	17	int
		[44]	0	int
9
;
		[45]	0	int
		[46]	5	int
		[47]	1	int
		[48]	36	int
		[49]	0	int

10
i
		[50]	0	int
		[51]	2	int
		[52]	1	int
		[53]	8	int
		[54]	0	int

11
++
		[55]	0	int
		[56]	1	int
		[57]	2	int
		[58]	21	int
		[59]	0	int

12
)
		[60]	0	int
		[61]	2	int
		[62]	1	int
		[63]	36	int
		[64]	0	int
{
13
		[65]	1	int
		[66]	0	int
		[67]	1	int
		[68]	36	int
		[69]	0	int

14
}		[70]	2	int
		[71]	0	int
		[72]	1	int
		[73]	36	int
		[74]	0	int
```

New tokens:
```
0
for
		[0]	0	int
		[1]	0	int
		[2]	3	int
		[3]	23	int
		[4]	0	int

1
(
		[5]	0	int
		[6]	4	int
		[7]	1	int
		[8]	36	int
		[9]	0	int
2
int
		[10]	0	int
		[11]	1	int
		[12]	3	int
		[13]	15	int
		[14]	0	int
3
i
		[15]	0	int
		[16]	4	int
		[17]	1	int
		[18]	29	int
		[19]	0	int
4
=
		[20]	0	int
		[21]	2	int
		[22]	1	int
		[23]	21	int
		[24]	0	int
5
0
		[25]	0	int
		[26]	2	int
		[27]	1	int
		[28]	19	int
		[29]	0	int
6
;
		[30]	0	int
		[31]	1	int
		[32]	1	int
		[33]	36	int
		[34]	0	int
7
/*c*/
		[35]	0	int
		[36]	1	int
		[37]	5	int
		[38]	17	int
		[39]	0	int
8
;
		[40]	0	int
		[41]	5	int
		[42]	1	int
		[43]	36	int
		[44]	0	int
9
i
		[45]	0	int
		[46]	2	int
		[47]	1	int
		[48]	29	int
		[49]	0	int
10
++
		[50]	0	int
		[51]	1	int
		[52]	2	int
		[53]	21	int
		[54]	0	int
11
)
		[55]	0	int
		[56]	2	int
		[57]	1	int
		[58]	36	int
		[59]	0	int
12
{
		[60]	1	int
		[61]	0	int
		[62]	1	int
		[63]	36	int
		[64]	0	int
13
}
		[65]	2	int
		[66]	0	int
		[67]	1	int
		[68]	36	int
		[69]	0	int
```

Edits returned by Roslyn LCS:
```
+		[0]	Update (14 -> 13)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[1]	Update (13 -> 12)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[2]	Update (12 -> 11)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[3]	Update (11 -> 10)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[4]	Delete (10)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[5]	Insert (9)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[6]	Update (9 -> 8)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[7]	Update (8 -> 7)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[8]	Update (7 -> 6)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[9]	Update (6 -> 5)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[10]	Update (5 -> 4)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[11]	Delete (4)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[12]	Insert (3)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[13]	Update (3 -> 2)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[14]	Delete (2)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[15]	Delete (1)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[16]	Delete (0)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[17]	Insert (1)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[18]	Insert (0)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
```

We can't filter out these updates:
+		[6]	Update (9 -> 8)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[13]	Update (3 -> 2)	Microsoft.CodeAnalysis.Differencing.SequenceEdit

since they affect the indices of other inserted tokens. For example, see Insert (9) and Update (9 -> 8). The Update in this case is significant because it will change the index of the token previously inserted at Insert (9) from index 9 to index 10. The same goes for the Insert (3) followed by Update (3 -> 2).

**Comment by CyrusNajmabadi** [comment]
@tmat @davidwengier that's about a 6x difference for Roslyn vs Razor.  We should definitely examine to see what's up with the roslyn LCS impl and why it's so stymied here.

**Comment by davidwengier** [comment]
With no context, my gut feeling is that Roslyns impl is probably tuned more for perf (looks like it avoids recursion?) than number of edits. @allisonchou I don't suppose you ran any benchmarks of the different versions? My guess is simply different priorities of the different projects.

**Comment by CyrusNajmabadi** [comment]
Given only 70 items though, we should be very fast here.  Effectively, we have 70 items in teh list and LCS is telling us to make 78 edits :(   that's just... not good :)

**Comment by CyrusNajmabadi** [comment]
Esp. as from `0, 2, 1, 21, 0,` onwards, the contents are identical.  it truly feels like this is more of a bug that's caused the roslyn impl to go entirely off the rails so to speak.

**Comment by davidwengier** [comment]
>  it truly feels like this is more of a bug

That's definitely what it seemed like in the initial edits Allison was talking about in Teams.

**Comment by tmat** [comment]
Roslyn's LCS works fine. The following test that can be added to `LongestCommonSubsequenceTests` demonstrates:

```C#
[Fact]
        public void TestInsert()
        {
            //                    111111111122222222223
            //          0123456789012345678901234567890
            var str1 = "for (int i = 0;/*c*/; i++) { }";
            var str2 = "fo r (int i = 0;/*c*/; i++) { }";

            VerifyMatchingPairs(lcs.GetMatchingPairs(str1, str2), "[29,30][28,29][27,28][26,27][25,26][24,25][23,24][22,23][21,22][20,21][19,20][18,19][17,18][16,17][15,16][14,15][13,14][12,13][11,12][10,11][9,10][8,9][7,8][6,7][5,6][4,5][3,4][2,3][1,1][0,0]");

            VerifyEdits(str1, str2, lcs.GetEdits(str1, str2));

            AssertEx.Equal(new[]
            {
                "Insert -1 2"
            }, lcs.GetEdits(str1, str2).Where(e => e.Kind != EditKind.Update).Select(e => $"{e.Kind} {e.OldIndex} {e.NewIndex}"));

            Assert.Equal(0.032, lcs.ComputeDistance(str1, str2), precision: 3);
        }
```

**Comment by tmat** [comment]
Never mind, the LCS is being run on tokens not characters.

**Comment by tmat** [comment]
> We can't simply get rid of all the "Update" edits because there are some cases where we actually need to consider them

This is not correct usage of the algorithm. Updates need to be filtered out.

**Comment by tmat** [comment]
It seems that problem is not with LCS implementation but with the usage.

**Comment by allisonchou** [comment]
> This is not correct usage of the algorithm. Updates need to be filtered out as they represent matching nodes.

I don't think we can always filter out Updates. For example, going by token:

**Before:**
``` C#
fo r (int i = 0;/*c*/; i++)
{

}
```

**After:**
``` C#
for (int i = 0;/*c*/; i++)
{

}
```

produces these edits:
```
+		[0]	Update (14 -> 13)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[1]	Update (13 -> 12)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[2]	Update (12 -> 11)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[3]	Update (11 -> 10)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[4]	Delete (10)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[5]	Insert (9)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[6]	Update (9 -> 8)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[7]	Update (8 -> 7)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[8]	Update (7 -> 6)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[9]	Update (6 -> 5)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[10]	Update (5 -> 4)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[11]	Delete (4)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[12]	Insert (3)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[13]	Update (3 -> 2)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[14]	Delete (2)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[15]	Delete (1)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[16]	Delete (0)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[17]	Insert (1)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
+		[18]	Insert (0)	Microsoft.CodeAnalysis.Differencing.SequenceEdit
```

I don't think we can ignore all the Updates here, because that would make the results incorrect. We can ignore _most_ of the Updates, but not all. For example, see Insert (9) and Update (9 -> 8). The Update in this case is significant because it will change the index of the token previously inserted at Insert (9) from index 9 to index 10. The same goes for the Insert (3) followed by Update (3 -> 2).

**Comment by tmat** [comment]
What are the tokens being compared?

**Comment by tmat** [comment]
If you can't filter out some Updates that means `ItemsEqual` override is incorrectly implemented since it considers two items equal even though you don't want them to be equal.

**Comment by tmat** [comment]
As you can see here the Razor's implementation does not have Update edit. Only Insert/Delete: https://github.com/dotnet/aspnetcore-tooling/blob/23cfccb732ba543d76fa35de87aae0a8b352fcd0/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DiffEdit.cs#L31

This is equivalent to Roslyn's insert and delete with updates filtered out.

**Comment by allisonchou** [comment]
> What are the tokens being compared?

The tokens being compared are:

Original tokens: 
```
0
fo
		[0]	0	int
		[1]	0	int
		[2]	2	int
		[3]	8	int
		[4]	0	int

1
r
		[5]	0	int
		[6]	3	int
		[7]	1	int
		[8]	30	int
		[9]	0	int

2
(
		[10]	0	int
		[11]	2	int
		[12]	1	int
		[13]	36	int
		[14]	0	int

3
int
		[15]	0	int
		[16]	1	int
		[17]	3	int
		[18]	15	int
		[19]	0	int

4
i
		[20]	0	int
		[21]	4	int
		[22]	1	int
		[23]	7	int
		[24]	0	int

5
=
		[25]	0	int
		[26]	2	int
		[27]	1	int
		[28]	21	int
		[29]	0	int

6
0
		[30]	0	int
		[31]	2	int
		[32]	1	int
		[33]	19	int
		[34]	0	int

7
;
		[35]	0	int
		[36]	1	int
		[37]	1	int
		[38]	36	int
		[39]	0	int

8
/*c*/
		[40]	0	int
		[41]	1	int
		[42]	5	int
		[43]	17	int
		[44]	0	int
9
;
		[45]	0	int
		[46]	5	int
		[47]	1	int
		[48]	36	int
		[49]	0	int

10
i
		[50]	0	int
		[51]	2	int
		[52]	1	int
		[53]	8	int
		[54]	0	int

11
++
		[55]	0	int
		[56]	1	int
		[57]	2	int
		[58]	21	int
		[59]	0	int

12
)
		[60]	0	int
		[61]	2	int
		[62]	1	int
		[63]	36	int
		[64]	0	int
{
13
		[65]	1	int
		[66]	0	int
		[67]	1	int
		[68]	36	int
		[69]	0	int

14
}		[70]	2	int
		[71]	0	int
		[72]	1	int
		[73]	36	int
		[74]	0	int
```

New tokens
```
0
for
		[0]	0	int
		[1]	0	int
		[2]	3	int
		[3]	23	int
		[4]	0	int

1
(
		[5]	0	int
		[6]	4	int
		[7]	1	int
		[8]	36	int
		[9]	0	int
2
int
		[10]	0	int
		[11]	1	int
		[12]	3	int
		[13]	15	int
		[14]	0	int
3
i
		[15]	0	int
		[16]	4	int
		[17]	1	int
		[18]	29	int
		[19]	0	int
4
=
		[20]	0	int
		[21]	2	int
		[22]	1	int
		[23]	21	int
		[24]	0	int
5
0
		[25]	0	int
		[26]	2	int
		[27]	1	int
		[28]	19	int
		[29]	0	int
6
;
		[30]	0	int
		[31]	1	int
		[32]	1	int
		[33]	36	int
		[34]	0	int
7
/*c*/
		[35]	0	int
		[36]	1	int
		[37]	5	int
		[38]	17	int
		[39]	0	int
8
;
		[40]	0	int
		[41]	5	int
		[42]	1	int
		[43]	36	int
		[44]	0	int
9
i
		[45]	0	int
		[46]	2	int
		[47]	1	int
		[48]	29	int
		[49]	0	int
10
++
		[50]	0	int
		[51]	1	int
		[52]	2	int
		[53]	21	int
		[54]	0	int
11
)
		[55]	0	int
		[56]	2	int
		[57]	1	int
		[58]	36	int
		[59]	0	int
12
{
		[60]	1	int
		[61]	0	int
		[62]	1	int
		[63]	36	int
		[64]	0	int
13
}
		[65]	2	int
		[66]	0	int
		[67]	1	int
		[68]	36	int
		[69]	0	int
```

> If you can't filter out some Updates that means ItemsEqual override is incorrectly implemented since it considers two items equal even though you don't want them to be equal.

We use the same ItemsEqual logic as Razor ([ours](https://github.com/dotnet/roslyn/blob/d41ae79bb1a3f0deb2de2f3d67c976f795da9563/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs#L329) and [theirs](https://github.com/dotnet/aspnetcore-tooling/blob/e7ac96226120ce60df7674a065694c6d5f56839b/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs#L33)) so I'm unsure if it's the cause. I also want to note that in _most_ cases we can filter out all Update cases, but there have been a few edge cases (like above) where we cannot.

**Comment by allisonchou** [comment]
Actually our ItemsEqual logic is a little different than Razor's since we're by token and they're by character. But unless I'm missing something (which I totally could be), the ItemsEqual logic looks OK to me?

**Comment by allisonchou** [comment]
fwiw we filter out the Update edits today, and that is currently causing the issue seen in https://github.com/dotnet/roslyn/issues/54671.

**Comment by allisonchou** [comment]
The logic returned by Roslyn LCS is actually correct _if_ we don't filter any of the updates out. But is incorrect if we do.

**Comment by tmat** [comment]
> we're by token and they're by character.

What do you mean by "by token" vs "by character"?

**Comment by allisonchou** [comment]
> What do you mean by "by token" vs "by character"?

Whoops sorry, I meant to say we calculate our edits by token (5 ints represent 1 token in LSP), while Razor calculates by individual int.
Token = something like `int`, `var`, `/* comment */`, etc.
The five ints represent 1) line relative to last token, 2) character relative to last token, 3) length of token, 4) token type, and 5) token modifier.

**Comment by allisonchou** [comment]
I think I figured out the real issue, opened up https://github.com/dotnet/roslyn/pull/55430 to address.
Thanks to Cyrus + Tomas for all the help here. 😄
