### ISSUE TITLE
Intellisense autocompletion is putting #if in when I start a string interpolation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55438]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-autocompletion-is-putting-/1490661)._

---
Intellisense autocompletion is putting #if in when I start a string interpolation.  This results in me having to delete out the #if and retype the $".  This makes working with strings particularly annoying in an otherwise decent feature.

---
#### Feedback Bot on 7/29/2021, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 7/30/2021, 03:35 PM: 

<p>Thank you for providing feedback, and we’re sorry to hear it’s not behaving as you expect. Based on your description so far, we were unable to reproduce the issue. Could you please provide a video of the behavior you are seeing.</p>

#### Travis Liskey [MSFT] on 7/31/2021, 00:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
## Steps to reproduce

1. Enable **Automatically show completion list in argument lists**

    ![image](https://user-images.githubusercontent.com/1408396/128384920-55eb6c11-8da8-44d5-8e06-2d2ed44e5945.png)

2. Type `Console.WriteLine(`
3. Wait for the completion list to appear
4. Press <kbd>$</kbd>
5. Press <kbd>"</kbd>

## Expected results

```csharp
Console.WriteLine($"")
```

## Actual results

```csharp
Console.WriteLine(#if")
```

**Comment by CyrusNajmabadi** [comment]
I do not repro this at all.
