### ISSUE TITLE
Targeting MS.EA.FSharp and MS.VS.LS Xaml to netcore

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#55474]
Targeting the following projects to netcore and adding them as refrences to our remote project , so they can be loaded in core host.

```xml
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="Microsoft.VisualStudio.LanguageServices.Xaml.dll" />
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="Microsoft.CodeAnalysis.ExternalAccess.FSharp.dll" />
```

**Comment by genlu** [comment]
A quick search shows that Xaml and F# only have IDE analzyers, i.e. `DocumentDiagnosticAnalyzer`. We don't actually need those in OOP if so

**Comment by mgoertz-msft** [comment]
Hi @genlu I own the Xaml DLL. It can only run inside of VS and isn't needed in OOP at this point. For Xaml to go OOP is a much bigger effort that has been postponed numerous times due to conflicting priorities. It's still on our backlog though.

**Comment by genlu** [comment]
@mgoertz-msft Thanks for confirming this!
