### ISSUE TITLE
Move analyzers from EditorFeatures to Features

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#55473]
We should move all analyzers from EditorFeatures layer down to Features, and remove the following entry in our vsix manifest. So we can get rid of references to EditorFeature in servicehub core host

```xml
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="Microsoft.CodeAnalysis.EditorFeatures.dll" />
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll" />
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.dll" />
```

**Comment by Youssef1313** [comment]
I think they should instead be moved to `Analyzers` layer, not `Features` layer. See https://github.com/dotnet/roslyn/pull/55043#discussion_r675277581.

**Comment by genlu** [comment]
@Youssef1313 Yea, that's what I meant :) since I believe all analyzers in Features is basically included via the shared projects you mentioned.

That said, turns out there's no regular analyzers in EditorFeature layer (only one that implements `DiagnosticAnalyzer` is EnC analyzer, which we don't run in OOP.) So we just need to update the manifest instead. #55480
