### ISSUE TITLE
CSharpSharedProjects fails in Standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5548]
Test is failing because of 2 issues:
* Expected token type for selection (after changing context) is excluded code when it should be identifer. The test might not be changing contexts correctly.
* Error tag count mismatch. Expects 4 errors, when there are only 2

I will be disabling this test in the standalone runs.

**Comment by mattscheffer** [comment]
@heejaechang @CyrusNajmabadi

**Comment by Pilchie** [comment]
Can you take a look at the first issue?

**Comment by Pilchie** [comment]
The first issue sounds like the same thing as #5343

**Comment by brettfo** [comment]
The second issue is also due to #5343 because the context hasn't changed so the error tags are from the old context.

**Comment by brettfo** [comment]
Closing in favor of #5343.
