### ISSUE TITLE
IDE should not suggest pattern matching when unavailable with given language settings

### ISSUE THREAD

**Issue by Zannick** [dotnet/roslyn#55489]
**Version Used**: 16.10.4

<details>
<summary>Full Versions</summary>

```
Microsoft Visual Studio Community 2019 Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework Version 4.8.04084
Installed Version: Community

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
Azure App Service Tools v3.0.0   16.10.526.50910
Azure Functions and Web Jobs Tools   16.10.526.50910
C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Common Azure Tools   1.10
CreateActionClasses Extension   1.0
IntelliCode Extension   1.0
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
SQL Server Data Tools   16.0.62106.24090
```
</details>

**Steps to Reproduce**:

Use a factory pattern to construct an object and down-cast it and check it for null, as in:

```cs
// factory defined elsewhere returns as interface type
Interface1 ObjectFactory.CreateObject(int);
[...]
// code constructs the object and casts into a class type that implements the interface
var obj = ObjectFactory.CreateObject(x) as BaseObject;
if (obj == null) {
  return -1;
}
[uses of obj below]
```

IDE suggestion: IDE0019 Use pattern matching

**Expected Behavior**:

Suggestion is not offered or code compiles after suggestion applied.

**Actual Behavior**:

Suggestion applied results in:

```cs
if (ObjectFactory.CreateObject(x) is not BaseObject obj)
{
  return -1;
}
[uses of obj unchanged]
```
the IDE shows no code issues (I wasn't sure if obj was supposed to be still in scope outside the 'if' block) but compiling failed with 3 new errors:
* `error CS1026: ) expected`, pointing to the start of `obj`
* `error CS1002: ; expected`, pointing to the final closing paren
* `error CS1513: } expected`, pointing to the final closing paren

indicating that the syntax is unsupported with my current language settings, and not mentioning what language settings (e.g. Preview) would allow this syntax.

**Comment by CyrusNajmabadi** [comment]
We only offer this if you're on C#9 or above:

https://github.com/dotnet/roslyn/blob/f300a818940ea1acef66c946cfa83756729d5e59/src/Analyzers/CSharp/CodeFixes/UsePatternMatching/CSharpAsAndNullCheckCodeFixProvider.cs#L151-L156

Something is screwy with the compiler you're using.  Your IDE has one version, but your compile is using a much older version.

**Comment by CyrusNajmabadi** [comment]
Duping this out against https://github.com/dotnet/roslyn/issues/55485.  It's the same issue.  IDE is fine, but an incorrect compiler version is executing.
