### ISSUE TITLE
Interpolated string regression?

### ISSUE THREAD

**Issue by javiercn** [dotnet/roslyn#55493]
I've noticed some ASP.NET Core tests failing to run locally, and upon inspection with the debugger seems that something is going on with string interpolation.

When I concatenate the string as follows I get the proper text:
```csharp
var expectedMessage = "The type '" + typeof(HasParameterClashingWithInherited).FullName + "' declares more than one parameter matching the " +
                "name '"+ nameof(HasParameterClashingWithInherited.IntProp).ToLowerInvariant() + "'. Parameter names are case-insensitive and must be unique.";
```
```
The type 'Microsoft.AspNetCore.Components.ParameterViewTest+HasParameterClashingWithInherited' declares more than one parameter matching the name 'intprop'. Parameter names are case-insensitive and must be unique.
```

However, when I do the same thing via string interpolation the results are completely different.
```csharp
$"The type '{typeof(HasParameterClashingWithInherited).FullName}' declares more than one parameter matching the " +
                $"name '{nameof(HasParameterClashingWithInherited.IntProp).ToLowerInvariant()}'. Parameter names are case-insensitive and must be unique."
```
This is what I get upon putting the code into a variable and inspecting it. Seems like all the placeholders are empty.
```
' declares more than one parameter matching the Microsoft.AspNetCore.Components.ParameterViewTest+HasParameterClashingWithInheritedThe type ''. Parameter names are case-insensitive and must be unique.intpropname '
```

Note that this is not a test I changed in any way as part of my changes, so I would just expect it to run. The fact that avoiding the interpolated string worksaround the issue seems to point out that there's some compilation/runtime combo going on here.

**Comment by jcouv** [comment]
Roslyn (compiler) fix will be merged shortly. Thanks @Youssef1313
