### ISSUE TITLE
CSharpReplIdeFeatures fails in standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5549]
There are two failures here in the standalone runs:
* ```Missing quick info tag for String. (Scenario 5)
ExpectedQuickInfo: classâ€Ž Systemâ€Ž.String
 Represents text as a series of Unicode characters.To browse the .NET Framework source code for this type, see the Reference Source.
 ActualQuickInfo: classâ€Ž Systemâ€Ž.String```

* ```Missing Correct Signature Help (Scenario 7)
System.Exception: Actual and expected items don't match:
 Expected: void Console.WriteLine(bool value)
 Writes the text representation of the specified Boolean value, followed by the current line terminator, to the standard output stream.```

 ```value (The value to write.)
 value (The value to write.)
 Actual: void Console.WriteLine(bool value)


 value ()
 value ()```

I will be disabling this test in the standalone runs

**Comment by tannergooding** [comment]
@balajikris, @amcasey. Isn't this a known issue?

**Comment by amcasey** [comment]
Sounds like https://github.com/dotnet/roslyn/issues/5013.

**Comment by tannergooding** [comment]
@amcasey, Yup, that's what I was looking for, just couldn't find the bug.
