### ISSUE TITLE
new .editorconfig editor does not show code analyzer rules

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/new-editorconfig-editor-does-not-show-c/1473982)._

---
[regression] [worked-in:16.10.3]
I have an original .editorconfig file that contains c# formatting rules, code styles and code analyzer rules.
When I open the file from solution explorer, .editorconfig viewer shows formatting rules and code styles, but does not show any code analyzer rules.

With .editorconfig editor: 
![Bb15e3acb1a1d453ba4c330156607e74a637618191190403084_20210714-092518-image](https://user-images.githubusercontent.com/9797472/128750322-cb05ac66-a581-4aec-9813-231263bdcbff.png)

With text editor:
![B6f40f67bff8c4e72916b5fbf6f1f7d65637618194019799276_20210714-093001-image](https://user-images.githubusercontent.com/9797472/128750272-b32c2612-ec06-469e-8a31-ac4e364b0e7b.png)

When I open the file with text editor, I see code analyzer rules. And it seems code analyzer work correctly.
I would like to know how to show code analyzer rules on .editorconfig editor.

---
#### Feedback Bot on 7/13/2021, 10:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/20/2021, 02:28 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
fixed with https://github.com/dotnet/roslyn/pull/56124
