### ISSUE TITLE
Preview Changes when renaming C# elements from Razor

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#55516]
Right now we get a view like
![image](https://user-images.githubusercontent.com/14987221/128542251-3118c70a-bc6d-4f22-a37e-fec488b98dd7.png)

Whereas when you re-name something from C# you can preview the changes that are going to happen:
![image](https://user-images.githubusercontent.com/14987221/128542354-9ade22ef-365f-4854-b12f-d86f259be033.png)
Note also that changes to Error.cshtml are absent from this list, even though they will happen.

I imagine this will need work from VSPlatform, and Roslyn for the existing preview window lacking Razor results.

**Comment by ryzngard** [comment]
@ryanbrandenburg this shouldn't be too difficult, except the ability to present as an option to a user. The underlying service is https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/Host/IPreviewDialogService.cs . Do you have thoughts on how we could make this an option for the user? In inline rename it's currently in the top right dialog options

**Comment by ryzngard** [comment]
Marking this as a feature request. We don't control the rename UI in this case, so all of the information is possible just need the correct hooks to show it. @ryanbrandenburg  do you know how extensible the UI is for LSP in VS?

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in preview-changes experiences.
