### ISSUE TITLE
C# rename dialog only displays instances in C# files

### ISSUE THREAD

**Issue by MarkStega** [dotnet/roslyn#55517]
### Describe the bug
After experiencing the rename issue [31369](https://github.com/dotnet/aspnetcore/issues/31369#event-4739990122) in VS 16.10.0 P1 I upgraded to 16.10.0 P2.1. In this preview a rename of a property in a backing zzzz.razor.cs file does nothing.

[Edit] 16.10.0 P3 allows the rename but with an incorrect message.

### To Reproduce
Create xyz.razor & xyz.razor.cs; Define a property 'private bool pIsEnabled{get;set;} in the razor.cs file; Use it in the razor file. Try to rename the property in the razor.cs file. The operation fails whether chosen by the popup menu of F2.

[Edit] In 16.10 P3 the rename occurs in both the backing cs as well as the razor file. However the message for the rename says  "Changing 3 instances in 1 file" rather than the correct "Changing 4 instances in 2 files".

### Exceptions (if any)
none

### Further technical details
VS 16.10.0 P 2.1

**Comment by NTaylorMullen** [comment]
The underlying issue here may be the same as: https://github.com/dotnet/roslyn/issues/55516

**Comment by CyrusNajmabadi** [comment]
Closing out as i cannot repro this on latest builds.
