### ISSUE TITLE
Quick using ABI namespace change not backported

### ISSUE THREAD

**Issue by angelazhangmsft** [dotnet/roslyn#55515]
**Version Used**: 
16.11.0 [31605.320.d16.11]

**Steps to Reproduce**:

1. Set TargetFramework to net5.0-windows10.0.19041.0
2. var g = new Geolocator();
3. Open VS suggestions (Ctrl + .)

**Expected Behavior**:
no ABI namespace

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/69016571/128779714-eef5e2d5-5818-4a8c-8776-7f686eef51a7.png)

cc @jinujoseph @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This is strange. The original pr went in in may. Wasn't that still 16.x back then?  I thought we only recently made main into the 17.x line...

**Comment by angelazhangmsft** [comment]
Not sure, I updated to 16.11 GA and seeing the above. Will there be servicing updates to 16.11?

**Comment by CyrusNajmabadi** [comment]
Closing out.  We won't be taking this for servicing now.
