### ISSUE TITLE
API Proposal: Make RenameDocumentAction sealed instead of abstract

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#55539]
## Background and Motivation

`Renamer.RenameDocumentAsync` was added as a public way for users to sync any policies we have around document file name and folder placement when moving a file. Currently that includes class naming and namespace matching to folder. Known usage of this API is by the project system on Solution Explorer actions with files to invoke Roslyn to handle code changes related to the document change. 

As part of a cleanup effort to share code across the public API surface and internal usage with the `MatchNamespaceToFolderAnalyzer` it was noticed while the class is `abstract` there is no way to pass them in to a public API or constructable object. Therefor no reason for external implementations of this type. All implementations and creations of this type were internal. 

## Proposed API

```diff
namespace namespace Microsoft.CodeAnalysis.Rename
{
     public static partial class Renamer
     {
-       public abstract class RenameDocumentAction
+       public sealed class RenameDocumentAction
        {
-           public abstract string GetDescription(CultureInfo? culture = null);
+           public string GetDescription(CultureInfo? culture = null);
        }
     }
```

## Usage Examples

```C#
var renameDocumentSet = await Renamer.RenameDocumentAsync(document, "NewDocumentName");
foreach (var documentAction in renameDocumentSet.ApplicableActions)
{
    Descriptions.Add(documentAction.GetDescription());
}
```

## Alternative Designs

One alternative design is to leave as is. Other than being useless, this is not breaking anything.

## Risks

This would be a breaking change if, for some reason, someone did actually inherit from this type. This would also be a binary breaking change for users of the API. There should be very little risk of either causing problems.

## Current class link

https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/Portable/Rename/Renamer.RenameDocumentAction.cs

**Comment by ryzngard** [comment]
Part of the change with #55513

**Comment by ryzngard** [comment]
Removing blocking, going to restructure #55513 to do without public API change for now to get the fix in

**Comment by 333fred** [comment]
## API Review

This is not a breaking change, so this is approved.

**Comment by ryzngard** [comment]
See https://github.com/dotnet/roslyn/pull/58508#issuecomment-1016842982
