### ISSUE TITLE
"Fix all occurrences" window should have keyboard mnemonics for Apply/Cancel buttons

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#55540]
**Version Used**: Version 17.0.0 Preview 4.0 [31610.313.main]

**Steps to Reproduce**:

1. Invoke a code fix over a range of code.

**Expected Behavior**:

UI buttons have keyboard mnemonics/accelerators. In particular it feels idiomatic that _Apply_ should work with <kbd>Alt</kbd>+<kbd>A</kbd>.

The workaround is to use <kbd>Enter</kbd> and <kbd>Esc</kbd> instead, but for folks who use mnemonics this is non-obvious.

**Actual Behavior**:

Buttons have no accelerators.

![image](https://user-images.githubusercontent.com/350947/128959886-96577e8a-c6dc-4301-b0a4-96b23c2f2ebf.png)

**Comment by CyrusNajmabadi** [comment]
This is a platform issue.  @olegtk.
