### ISSUE TITLE
Intellisense isn't selecting the starred item by default

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55546]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-isnt-selecting-the-starred/1498892)._

---
In a recent version of VS, intellisense has started showing me a stupid option of casting a value to short instead of the more appropriate choice of Should() (from fluent assertions).
Here is a screen shot of what I mean:
! [Screenshot 2021-08-10 100732.jpg] (https://aka.ms/dc/image?name=Bc645d56b6f2f4a31a3f59220fc1e1c11637642012758166072_Screenshot_2021-08-10_100732.jpg&tid=c645d56b6f2f4a31a3f59220fc1e1c11637642012758166072)

Notice that Should is being suggested with a * but (short) always comes up first. This is super annoying as I NEVER need (short) as an option. I don't think my code base has a single use of short in it. But in the last month or two this has become the top selection in this dialog and it ALWAYS trips me up.

Is there some why to supress certain suggestions? Or to get Intellisense to be smarter about selecting the *'d items by default?

---
#### Feedback Bot on 8/11/2021, 00:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/11/2021, 09:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
`short` is an exact-case prefix match here. User would likely be better if they typed 'Sh' or 'shou' here to match.

We could also consider an option to disable casts in intellisense.

**Comment by genlu** [comment]
While is an exact-case prefix match here, user only typed lowercase, which probably isn't really a strong indication that case sensitive matching is a better choice, since user usually expect completion to fix casing for them.

**Comment by CyrusNajmabadi** [comment]
We could make the casts generally in a lower priority class.
