### ISSUE TITLE
dotnet_analyzer_diagnostic.severity Does Not Work with TreatWarningsAsErrors

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/roslyn#55541]
**Version Used**: 

- VS 2019, .NET 5, `#error version` = `Compiler version: '3.11.0-4.21403.6 (ae1fff34)'. Language version: latest (9.0).`
- .NET CLI 5.0.400 `#error version` = `Compiler version: '3.11.0-4.21373.6 (bb3bdbbe)'. Language version: 9.0.`.

**Steps to Reproduce**:

1. `dotnet new console`
2. Add this [.editorconfig](https://github.com/RehanSaeed/EditorConfig/blob/main/.editorconfig) file to the root of the project, it contains:
```editorconfig
[*.{cs,csx,cake,vb,vbx}]
# Default Severity for all .NET Code Style rules below
dotnet_analyzer_diagnostic.severity = warning
```
3. Add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` to the `.csproj` file.
4. `dotnet build`
5. You get warnings instead of errors.

**Expected Behavior**:

You should get errors.

**Actual Behavior**:

You get warnings.

See also @sharwell's comments in https://github.com/dotnet/roslyn/issues/43051#issuecomment-896125237

**Comment by RehanSaeed** [comment]
On a related note, the new `[rule].[RuleId].[severity]` syntax for specifying severity doesn't seem to work i.e.

## This Works
```
# [rule] = [value]:[severity] syntax
csharp_prefer_simple_using_statement = true:suggestion
```

## This Doesn't Work
```
# [rule].[RuleId].[severity] syntax
csharp_prefer_simple_using_statement = true
dotnet_diagnostic.IDE0063.severity = suggestion
```

See https://github.com/RehanSaeed/EditorConfig/pull/57 for more details.

**Comment by RehanSaeed** [comment]
https://github.com/dotnet/roslyn/issues/55542 May be related.

**Comment by mavasani** [comment]
Verified that this is indeed a bug that would need fixing. Thanks for reporting it.
