### ISSUE TITLE
Scripting dlls don't follow Roslyn naming convention...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5556]
I believe the convention is:  Microsoft.CodeAnalysis.{Language}.{Feature}.dll

Scripting dlls have the "Language" last, i.e. Microsoft.CodeAnalysis.Scripting.CSharp.dll.

**Comment by KevinH-MS** [comment]
Namespaces look to be inconsistent as well...if there aren't conflicts introduced by doing so, I think we could remove "Scripting" from the namespaces, so everything is just under:

Microsoft.CodeAnalysis
Microsoft.CodeAnalysis.CSharp
Microsoft.CodeAnalysis.VisualBasic

**Comment by tmat** [comment]
We should not remove Scripting from the namespace. Microsoft.CodeAnalysis has too much stuff that users of scripting APIs don't need to be bothered with.

**Comment by KevinH-MS** [comment]
I intended to leave this open until VB was done.

**Comment by KevinH-MS** [comment]
Fixed by #6727
