### ISSUE TITLE
Roslyn VS dialogs should have consistency 

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#55560]
We are not consistent in how we layout dialogs. Consider Pull Members Up and the Extract Class dialogs which both have a similar purpose. Both use the same MemberSelection component but one wraps it in a bordered group box and the other doesn't. 

![image](https://user-images.githubusercontent.com/611219/129117859-bdf129a4-96e6-4094-9937-f592e52f2705.png)

![image](https://user-images.githubusercontent.com/611219/129118604-8e4803b2-4eb4-43b1-8a23-d850c6fdb03d.png)

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
