### ISSUE TITLE
Roslyn.Services.UnitTests.dll has a failure in Standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5557]
One unit test is failing inside of this suite. It's is expecting a 6 when receiving a 4. I'm not sure what the numbers refer to. I will be disabling this until we get the testcase fixed.

Failure:
   Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml [FAIL]
      Assert.Equal() Failure\r\nExpected: 6\r\nActual:   4
      Stack Trace:
            at Microsoft.CodeAnalysis.UnitTests.MSBuildWorkspaceTests.TestOpenProject_WithXaml()

**Comment by mattscheffer** [comment]
This is still failing. Wasn't fixed by this commit. Hadn't realized it was closed til now.

**Comment by balajikris** [comment]
Yes, the assert message is non-existent here.. Its expecting 6 documents in the project after opening it and finding 4.

**Comment by DustinCampbell** [comment]
Pretty stale...

**Comment by Pilchie** [comment]
Moving to 2.1, as we won't address this in escrow.
