### ISSUE TITLE
The 17th parameter of a synthesized delegate doesn't have ref information encoded

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#55570]
This also affects the 33rd parameter, and presumably 65th etc. but I stopped bothering to check at 33.

**Steps to Reproduce**:

1. Create multiple lambdas for which delegates will be synthesized, with 17 parameters.
2. Make them differ in the ref kinds of the 17th parameter.
3. See SharpLab, observe two delegates being synthesized that are duplicates of each other:
https://sharplab.io/#v2:EYLgtghglgdgPgNwgJwAQH0CMqC8qAUsALhpgDSrEYBMFV6AzHTCegCzOsCsnGAbL3QB2QQA5BATkGYADNPKUWpWotaYmq0h01YeOzANTIApgDN9QgJS4AfKgDeqAL4BuALAAoJGnTVcBegV6FXoNem16PXpDehEdcR0pfTl9IKUsEPT1aQisqKyYmAtrHDtHVyA

**Expected Behavior**:
The synthesized delegates should have different names

**Actual Behavior**:
They share the same name.

This issue is referenced in source.

/cc @cston 

Relates to test plan https://github.com/dotnet/roslyn/issues/52192

**Comment by cston** [comment]
@davidwengier, thanks for catching this issue.
