### ISSUE TITLE
Add a Code Querying Tool for Improved Search

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55583]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-Code-Querying-Tool-for-Improved-Se/1490662)._

---
There are many times when I'd like to find certain code in a rather large codebase.  It would be fantastic to have a code querying tool to let me search my codebase using Roslyn data.

Ideally this would let me answer questions like:
* What classes derive from A, which have property of type X, named Y?
* What classes have a constructor taking an argument of type X?
* Which methods returning IActionResult have an attribute C?

---
#### Feedback Bot on 7/30/2021, 00:35 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by BhaaLseN** [comment]
This sounds interresting. I usually have the case that I want to find unused members/methods (both public and non-public), as well as very specific "only used once" members/classes - and right now finding those is pretty difficult without 3rd party tools or writing external code to analyze the workspace (which becomes increasingly difficult when both .NET Framework projects with old style csproj and .NET Core/,NET 5 projects with new SDK style csproj files are involved that don't load properly in projects written with the opposite framework)

**Comment by jinujoseph** [comment]
cc @mikadumont

**Comment by jinujoseph** [comment]
Duplicate #6618
