### ISSUE TITLE
Detect SourceGenerator slowness and notify users to disable

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#55580]
## Background and Motivation

I've discussed a lot of the background for this issue in these two issues:
- #55578
- #55579

## Solution

@jmarolf mentioned that we already have APIs to notify users in VS when classical analyzers are slow. SourceGenerators have a similar impact so we need to have a mechanism to detect slow source generators and notify users.

@jmarolf would you mind sharing the pre-existing experience for Analyzers so we can understand how we can propagate this to SGs?

**Comment by sharwell** [comment]
> mentioned that we already have APIs to notify users in VS when classical analyzers are slow

I don't believe this is the case.

**Comment by jmarolf** [comment]
> I don't believe this is the case.

I was referring to `/p:ReportAnalyzer=true` from [here](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Report%20Analyzer%20Format.md) which is not an API, but is the best mechanism we have today to track analyzer performance in a build.

**Comment by sharwell** [comment]
Ah, that covers build performance for analyzers. We _should_ include something similar for source generators, but in most cases the numbers produced by that will not accurately represent the experience inside the IDE for the same analyzers (the build runs source generators in a non-incremental fashion today, which is very different from the behavior while typing).

**Comment by jmarolf** [comment]
True, we may want to add something in https://github.com/dotnet/project-system-tools to allow us to track incremental performance. We currently have https://github.com/dotnet/project-system-tools/blob/main/src/ProjectSystemTools/RoslynLogging/RoslynWorkspaceStructureLogger.cs for a similar purpose.

**Comment by jasonmalinowski** [comment]
(or at least, we won't have it fully wired up such that we can call this closed)

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.  If this needs to be done it needs to be assigned a milestone to do it in.
