### ISSUE TITLE
Option to not add structure guide lines to C# regions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-to-not-add-structure-guide-lines-/1486081)._

---
After a recent Visual Studio update, structure guide lines are currently added to "#region"/"#endregion" pairs. I'd suggest an option to not add the lines for regions. I'd like to disable them for regions because the way the lines are shown is not consistent with how the lines are shown for other kinds of constructs: usually for other constructs (say, methods) the code inside is indented and the lines appear before the code; however, code inside regions is usually not indented with respect to "#region"/"#endregion", making the code look like there's an indentation issue, which is pretty annoying.

![B4121b4018e804718a3886c1984b039c2637628556557328238_Lines](https://user-images.githubusercontent.com/1408396/133484017-bcec5d80-a451-4cf6-997b-0dce825185c6.png)

---
#### Feedback Bot on 7/25/2021, 08:16 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
It appears this was fixed by #54079
