### ISSUE TITLE
"IDE0002 C# Name can be simplified." suggestion is longer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55595]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/IDE0002-C-Name-can-be-simplified-sug/1318740)._

---
Some "Assert"s in Assert.Equal, Assert.NotEqual, etc... are incorrectly shaded as if they're not necessary. The Assert.Equal at https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/BuildIncrementalismTest.cs#L399 is an example of this. When I hit <Ctrl+.> to get suggestions, it claims the name can be "simplified" to Xunit.Assert.Equal.

---
#### Feedback Bot on 1/25/2021, 00:09 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by halter73** [comment]
I filed this VS feedback initially. The test has since [moved to the dotnet/sdk repo](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIncrementalismTest.cs#L167), but I haven't seen this issue in years.

**Comment by CyrusNajmabadi** [comment]
Good to know.  Thanks!
