### ISSUE TITLE
Add Right-Click for IntelliSense Overload Overlay

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Right-Click-for-IntelliSense-Overloa/1492635)._

---
As seen with picture attached, when you **left click on that popup it moves forward +1** to the next overload suggestion.

I would recommend implementing also a **right-click to go back -1 to the previous one**.

_Currently it's only possible to move forward. 
Manually selecting the small arrows is a bit cumbersome._

![B3bb26e6b235944dbb14c7ab62d702ded637635009464219468_Capture](https://user-images.githubusercontent.com/1408396/133484324-efb24bae-a01d-483e-9108-ead46941a40b.PNG)

---
#### Feedback Bot on 8/2/2021, 11:05 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Philipp Elhaus on 8/2/2021, 11:10 PM: 

<p>Also adding a <strong>Mouswheel Up/Down Scroll</strong> while over the popup to shuffle through the overloads would be great.</p>

**Comment by sharwell** [comment]
📝 The up/down arrows on the keyboard also work for changing the selected overload.

**Comment by CyrusNajmabadi** [comment]
This is a request for the editor.  @olegtk .

**Comment by olegtk** [comment]
Good suggestion, I reactivated https://developercommunity.visualstudio.com/t/Add-Right-Click-for-IntelliSense-Overloa/1492635
