### ISSUE TITLE
Pull Members Up retains unnecessary whitespace trivia, causing extra blank lines

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#55608]
**Steps to Reproduce**:
1. Create an empty base class and then a separate inherited class with multiple members:
```
class C1Base
{
}

class C1 : C1Base
{
    public int _testInt;

    public bool TestBool { get; set }

    public void TestMethod()
    {
    }
}
```
2. Select a single member that is not the initial member, for example `TestBool`, and trigger the quick actions menu to select "Pull Members Up" (this also has a similar effect if you trigger this on a non-inherited class and select Extract Base Class).

**Expected Behavior**:
The resulting base class should put the moved member with the correct formatting:
```
class C1Base
{
   public bool TestBool { get; set; }
}
```
**Actual Behavior**:
The member keeps unnecessary leading whitespace trivia:
```
class C1Base
{

    public bool TestBool { get; set; }
}
```
There are certainly times when this extra line is desired, for example if there are other members above the moved member in the destination. However, there should be line whitespace logic (perhaps using Elastic Whitespace) that would retain possible pre-member trivia such as comments, but format whitespace contextually.

**Comment by jinujoseph** [comment]
cc @Cosifne

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
