### ISSUE TITLE
IDE0084 Use pattern matching (IsNot operator) - dangerous for "Not TypeOf..." syntax

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55607]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0084-Use-pattern-matching-IsNot-oper/1500548)._

---
[severity:It bothers me. A fix would be nice]
While I do like and use the "IsNot" replacement suggestions, the rule should not apply where the syntax is "Not TypeOf myObject Is SomeType". The TypeOf check will not always be the same when the syntax is changed to "TypeOf myObject IsNot SomeType" (due to class inheritance and such). Hence the behaviour of the code is changed when some developer believes the IDE0084 suggestion is safe to use to auto fix "TypeOf" syntaxes. Its a constant danger to have this suggestion there (until we add an explicit issue suppression where this occurs).

What I suggest is either that the IDE0084 is changed so it no longer suggests that "Not TypeOf..." should be changed, or that it is changed into two separate rules so that it is possible to disable suggestions for "TypeOf"-syntaxes while keeping it for regular syntaxes.

Best Regards
/Johan

---
#### Feedback Bot on 8/12/2021, 01:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't understand the issue report. What's the actual problem with this transformation?

**Comment by JohanRoss** [comment]
It seems to be a Linq-to-entities issue: I have tried to replicate this with a List, Enumerable and array, but that works just fine. In the production code where this happens, it is a query towards an Entity Framework dbContext:
```
Dim positions = _dbContext.Query(Of Position)().
	Where(Function(p) p.Portfolio IsNot Nothing AndAlso
		p.PositionUsage.HasFlag(PositionUsageNew.Qrt) AndAlso
		p.IsClosed = closedPositions AndAlso
		Not TypeOf p.EvaluableObject Is Liability AndAlso
		orgNumbers.Contains(p.Portfolio.OrganisationNumber)).ToList()
```
Changing "Not TypeOf p.EvaluableObject Is Liability" to "TypeOf p.EvaluableObject IsNot Liability" here makes the query yield no results. However, if i remove that clause from the query, and then apply it to the materialized list afterwards instead, it works fine. (Like `positions = positions.Where(Function(p) TypeOf p.EvaluableObject IsNot Liability).ToList()`)

I apologize for the very late response to this issue. I was going to try to stage something just to test this, but it was taking me too long and i got occupied with other things that needed to be done. We have used "#Disable Warning IDE0084" around this code block to disable the automatic suggestions and make our team aware that it should not be changed. While its a bit ugly, it has been an acceptable workaround.

The main entities involved here are Position, EvaluableObject and Portfolio. EvaluableObject is a base class, that has roughly 40 inherited classes (in max 3 levels of inheritance). In EF, it is set up as TPH, so its only one table for all these classes. I've tried to extract some of the classes/entities here below to give you an idea how it looks (these are in C#):

```
[Table("Positions", Schema = "Market")]
public class Position
{
	public int Id { get; set; }
	public virtual EvaluableObject EvaluableObject { get; set; }
	public bool IsClosed { get; set; }
	public PositionUsageNew PositionUsage { get; set; }
	public virtual Portfolio Portfolio { get; set; }
	// Omitting about 20 other properties and 5 methods...
}

[Table("Portfolios", Schema = "Market")]
public class Portfolio
{
	public int Id { get; set; }
	public string OrganisationNumber { get; set; }
	// Omitting about 5 other properties and 2 methods...
}
	
[Table("EvaluableObjects", Schema = "Market")]
public abstract class EvaluableObject
{
	public int Id { get; set; }
	public string IssuerOrganisationNumber { get; set; }
	// Omitting about 25 other properties and 10 methods...
}

public class Liability : EvaluableObject
{
	// Omitting properties and methods...
}

public class Cash : EvaluableObject
{
	// Omitting properties and methods...
}

public class Equity : EvaluableObject
{
	// Omitting properties and methods...
}
	
public abstract class CouponBondBase : EvaluableObject
{
	// Omitting properties and methods...
}

public class CouponBond : CouponBondBase
{
	// Omitting properties and methods...
}

public class ConvertibleZeroCouponBond : ZeroCouponBond
{
	// Omitting properties and methods...
}
```

I hope you can make something out of this, and perhaps accnowledge what we have encountered.

Best regards
/Johan

**Comment by CyrusNajmabadi** [comment]
>Changing "Not TypeOf p.EvaluableObject Is Liability" to "TypeOf p.EvaluableObject IsNot Liability" here makes the query yield no results. 

> It seems to be a Linq-to-entities issue

This seems to be unfortunate.  I think you could file feedback about EntityFramework to get them to address this.  Perhaps https://github.com/dotnet/ef6 is a better location for the report?

**Comment by JohanRoss** [comment]
Well, if it is strictly tied to EF6, then its not worth creating a new issue for it since no bugs will be fixed there anymore. We are moving our code to EF Core during the year anyway, so guess that if the problem remains there i will create a new issue for the EF Core project...

Thanks for the fast answer, Cyrus!

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
