### ISSUE TITLE
Extract Base Class will trigger on multiple members, even if the containing class already has a base class

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#55610]
**Steps to Reproduce**:
Create a base class and a separate inherited class with members:
```
class Base
{
}

class Derived : Base
{
    public int _testInt;

    public static void TestMethod()
    {
    }
}
```
Highlight multiple members, as shown using `[|this symbol|]` to indicate the range of selection:
```
class Derived : Base
{
    [|public int _testInt;

    public static void TestMethod()
    {
    }|]
}
```
Then invoke the quick actions menu using the lightbulb/screwdriver or Ctrl + .
**Expected Behavior**:
"Extract Base Class" should not show up as a possible refactoring, as there is already a base class. This is the behavior shown when only one member is selected
**Actual Behavior**:
"Extract Base Class" shows up as a possible refactoring. Actually invoking the refactoring will open a dialog, which will create a new base class for `Derived`. Now `Derived` will inherit from multiple classes, which produces a compiler error.

I think it is possible for "Extract Base Class" to be a valid refactoring here. If we created an intermediate (possibly abstract) class that would inherit from `Base` and from which `Derived` would be inherited, as follows:
```
class Base
{
}

class GeneratedExtractedClass : Base
{
    public int _testInt;

    public static void TestMethod()
    {
    }
}

class Derived : GeneratedExtractedClass
{
}
```
However, this would be a significant extension of the "Extract Base Class" feature, and would also require the same refactoring to appear when we selected one member, which it currently doesn't. Either way, the refactoring should appear or not appear regardless of whether one or multiple members are selected.

**Comment by sharwell** [comment]
Either of the following are acceptable:

1. The refactoring to extract a base class is not visible if the type already has a base class
2. The refactoring to extract a base class introduces a new base class which itself is derived from the original base class (i.e. a new class is inserted between the current type and its original base type in the hierarchy)
