### ISSUE TITLE
Create a mocked clipboard for interactive window unit tests

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#5562]
Right now all clipboard related tests are using system clipboard directly, which causes COM exception intermittently (presumably because multiple tests are running in parallel), for example: https://github.com/dotnet/roslyn/issues/5544

**Comment by jaredpar** [comment]
Isn't this a dupe of #5544?

**Comment by genlu** [comment]
@jaredpar This is more like a workitem for me vs a bug people uses to track if it 's fixed, but yeah, we definitely don't need both so I will close this and track the work with https://github.com/dotnet/roslyn/issues/5544

**Comment by genlu** [comment]
@amcasey Could you please verify and close this?
