### ISSUE TITLE
No way to properly distribute types in larger applications

### ISSUE THREAD

**Issue by ScottKane** [dotnet/roslyn#55629]
There is no way to distribute generated types to specific projects within a solution. I'm currently following domain driven architecture which means I have lots of projects in my solution. I have a source generator that I wrap around my feature domain models and from that I can generate the entire end to end CRUD CQRS feature. The problem is, all of these types will only exist within domain, which can't depend on any other projects to use types they have.

My only other option is to EmitCompilerGeneratedFiles and move them around on disk. All files are just dumped into a single directory which makes this difficult. It would be nice if we could pass a Folder/File to GeneratorExecutionContext.AddSource to define this structure.

If it was possible to have all projects depend on the Generators project and have types forwarded to the respective project based on what is implied in the namespace would be amazing.

**Comment by ScottKane** [comment]
You could have a `<ImplicitProjectForwarding>true</ImplicitProjectForwarding>` setting to enforce that for a type to show up in a project, the namespace of the type must contain the project name.

E.g:
Projects:
 - `Domain`
 - `Application`
 - `Infrastructure`

All depend on the project: `Generators`.

This type is generated:
```c#
// Generated
namespace Example.Application.Something
{
    public partial class ExampleClass { }
}
```

Only the project `Application` would see that type.

**Comment by svick** [comment]
@ScottKane Could your generator do that on its own? Effectively run in all three projects, but filter which types to generate based on the project?

**Comment by ScottKane** [comment]
@svick I honestly don't know. I hadn't thought of doing that so I will give it a go.

**Comment by ScottKane** [comment]
No I can't do that, because the types are generated by one project using an attribute on a POCO model. That triggers the syntax receiver which creates all the required types. There's no way to know the consuming projects anyways.

Unless someone can come up with a better solution I think having `<ImplicitProjectForwarding>true</ImplicitProjectForwarding>` or `<ImplicitProjectGeneration>true</ImplicitProjectGeneration>` would solve this.

**Comment by jaredpar** [comment]
> My only other option is to EmitCompilerGeneratedFiles and move them around on disk. All files are just dumped into a single directory which makes this difficult. It would be nice if we could pass a Folder/File to GeneratorExecutionContext.AddSource to define this structure.

This goes against the design of source generators. The intent of source generators is to allow code generation for the current compilation. It is specifically not meant for creating files for other compilations to consume. Doing so breaks the underlying build model because it's adding IO that is invisible to MSBuild. 

> There is no way to distribute generated types to specific projects within a solution. I'm currently following domain driven architecture which means I have lots of projects in my solution. I have a source generator that I wrap around my feature domain models and from that I can generate the entire end to end CRUD CQRS feature. The problem is, all of these types will only exist within domain, which can't depend on any other projects to use types they have.

It's unclear what the problem is here though. Source generators allow for you to know the name of the project that is being generated for (you can feed through the MSBuild name property). Hence that should allow you to distinguish between which project you're in and hence change your code generation. 

@chsienki, @RikkiGibson, @cston

**Comment by ScottKane** [comment]
Sorry I had forgotten to reply here, I was able to do what I needed using the `GeneratorSyntaxContext.SemanticModel.Compilation.AssemblyName` to only generate the relevant types for each project depending on the generator project.

**Comment by jaredpar** [comment]
Glad it worked out!
