### ISSUE TITLE
String interpolation - wrong output

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#55630]
Repo - https://github.com/grpc/grpc-dotnet
Test - AddGrpcClient_AddDifferentClientsWithSameName_ThrowsError (.net6 target)

This test consistently fails with the wrong output.

```
﻿ AddGrpcClient_AddDifferentClientsWithSameName_ThrowsError
   Source: GrpcClientServiceExtensionsTests.cs line 153
   Duration: 40 ms

  Message: 
  String lengths are both 343. Strings differ at index 0.
  Expected: "The gRPC client factory already has a registered client with ..."
  But was:  "'. Greet.Greeter+GreeterClient', bound to the type 'GreeterCl..."
  -----------^


  Stack Trace: 
GrpcClientServiceExtensionsTests.AddGrpcClient_AddDifferentClientsWithSameName_ThrowsError() line 163
```

Text `'. Greet.Greeter+GreeterClient', bound to the type 'GreeterClient` is prepended to the expected output. That looks like it is from a previous string format so it might be a case of bad caching.

Format code:

https://github.com/grpc/grpc-dotnet/blob/f552a4982f76f7b1db7d9fcc33c7d44fe31be985/src/Grpc.Net.ClientFactory/GrpcClientServiceExtensions.cs#L384-L388

It fails in .NET 6, passes for .NET 5 and other targets:

![image](https://user-images.githubusercontent.com/303201/129507616-4e7d3891-8f75-49ff-8d2d-56b6bd5c4a58.png)

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21415.3
 Commit:    8e5e77d8c8
```

@stephentoub

**Comment by Youssef1313** [comment]
I believe this should have been fixed by https://github.com/dotnet/roslyn/pull/55494.

**Comment by svick** [comment]
Closing as dup.
