### ISSUE TITLE
Improve CS0106 for the different cases where it can happen

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#55634]
*Reported by @jim27106 (https://github.com/dotnet/roslyn-api-docs/issues/96)*

Direct report copied:

Please tell C# compiler writers that if a programmer spends the time to write an if statement to catch an error he should spend the time to provide a specific solution.

Original program:
if (height > 200) message = "Two meters is the max.";

Poor programmer
if (height > 200 || height < 180 || weight > 80) message = "Height or weight out of range"; // they should know why they are not eligible.

Good programmer
// These are kinda personal so no solutions are suggested.
if (height > 200) message = "Height is limited to 2 meters (6' 8"). ";
else if (height < 180 ) message = "Height must be at least 1.8 m (~ 5' 11'"). ";
if ( weight > 80) message += "Weight must be less than 80 kg (~ 175 pounds).";

CS0106 is too much of a catch-all.

**Comment by RikkiGibson** [comment]
CS0106 is "BadMemberFlag" but the issue description doesn't mention members.

**Comment by Youssef1313** [comment]
@jim27106 Can you please give some examples where you encountered CS0106 and felt that each situation needs a different message and give an example of the message you were expecting? Thanks!

**Comment by Youssef1313** [comment]
@RikkiGibson Another complaint about the exact same diagnostic:

https://github.com/dotnet/docs/issues/25960#issuecomment-968583163
