### ISSUE TITLE
Visual Studio 2022 Changes Refactoring Order

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55636]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Changes-Refactoring-O/1503752)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.0]
If you have two classes in the same file, in VS2019, the first refactoring is "Move Type to {TypeName}.cs".  This is a very good refactoring to have first.

In VS2022, the first refactoring is "Extract Base Class" which is useful but not used nearly as much.

Can you please revert the order?

---
#### Feedback Bot on 8/16/2021, 00:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jmarolf @mikadumont can you check telemetry on this?  if the data indicates the same as hte above, we should order these differently.

**Comment by jmarolf** [comment]
taking a look [here](https://lens.msftcloudes.com/#/dashboard/efab2a2c-6fb3-4c29-9491-826a9fda2b37) (internal telemetry link).


| Refactoring Name   | Times Applies in the Last 18 Months |
|:-------------------|------------------------------------:|
| Move Type 	     | 13,188,433                          |
| Extract Base Class | 2,509,785                           |

**Comment by TonyValenti** [comment]
I opened the original VSFeedback ticket.

Related to this, it seems like a number of the refactorings have had their order changed.  For example, another refactoring I use a lot is the "Generate Constructor" refactoring.  This used to be near the top but now it is the 8th item in the list:

![image](https://user-images.githubusercontent.com/13609558/129653465-9b1d5609-38a0-4c34-99a9-160f206e830f.png)

I'd like to recommend that, in general, items be ordered according to the telemetry usage.

**Comment by TonyValenti** [comment]
Actually I'd like to clarify my above suggestion. I think time should be sorted in this order:
1.  Fixes should be grouped first (like "add constructor" in this case because it fixes a compile
Error.)
2.  Tweaks should be grouped second. Things like "replace type name with var". 
3.  Utilities should be grouped second. Things like "move to file. 

Each group should be sorted by telemetry

**Comment by CyrusNajmabadi** [comment]
We already place fixes above refactorings :-)

**Comment by TonyValenti** [comment]
@CyrusNajmabadi - not in the screen shot above. If that were the case, GenerateConstructor would be the first one on the list.

**Comment by CyrusNajmabadi** [comment]
Where is the caret?

**Comment by TonyValenti** [comment]
@CyrusNajmabadi -
Create a new C# .NET6 app and use this code
```
// See https://aka.ms/new-console-template for more information

Console.WriteLine("Hello, World!");


public class Foo {
    public Foo(string Value) { }
}

public class Bar : Foo { }
```

If you position the cursor on ```Bar``` and press ```Control-Period``` you'll see this:
![image](https://user-images.githubusercontent.com/13609558/130337641-ac36a436-5bf7-4e2c-8e3a-4cc80965beaf.png)

But if code fixes should be listed first, Generate Constructor should be listed first.

**Comment by CyrusNajmabadi** [comment]
'Generate constructor' is currently not a codefix.  working on addressing that now.
