### ISSUE TITLE
Constant, frequent crash VS 16.11 with Source Generator use

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Constant-frequent-crash-VS-1611-with-S/1503693)._

---
[regression] [worked-in:16.10.x, 16.11]
I have a project that references another project Source Generator Project in single solution. While editing the code in either of these project Visual Studio prompts to attach debugger due to unhandled exception the process is either ServiceHub.RoslynCodeAnalysisService.exe or devenv.exe process but must Roslyn process. If I reboot machine after VS becomes unusable crashes do occur but the start again after some usage and when the free memory on the machine low about 250MB-500MB out of total memory of 4GB, the machine running is VS does  not have other applications running other than browser.

---
#### Feedback Bot on 8/15/2021, 08:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vaptex** [comment]
Another data point, if I unload the project that references Source Generator project then crashing stops.

**Comment by jasonmalinowski** [comment]
@vaptex Are you able to upload the .dmp file for one of the crashes that you're seeing? For some reason the report on Developer Community tried to upload the .dmp but ultimately failed to do so and doesn't say why. You should be able to attach more files to that Developer Community report, but I might have to reactivate the ticket.

**Comment by jasonmalinowski** [comment]
@vaptex If you are able to provide a dump that'd be great. I'm going to close this issue since we otherwise don't have anything to investigate further, but I'm happy to reactivate!

**Comment by vaptex** [comment]
I have crash dump file but not able to attach it

**Comment by vaptex** [comment]
I will try to attach it to dev comm report

**Comment by vaptex** [comment]
devenv.zip

**Comment by jasonmalinowski** [comment]
@vaptex You won't be able to upload the file here, do you need me to reactivate the Developer Community ticket?

**Comment by vaptex** [comment]
Yes, please. Thanks. I created another report as I couldn't attached older one.

**Comment by jasonmalinowski** [comment]
Alright closing this and I'm making sure we won't move the other one to GitHub. :smile:
