### ISSUE TITLE
[Nullable] Compiler doesn't consider `Where(x => x != null)` to be a null check

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/roslyn#55667]
## Background and Motivation

Improve nullability feature by enabling compiler to understand null checks done through LINQ.

Currently lines 3-9 produce nullable warnings, but shouldn't:

```cs
List<string?> list = new() { "a", null };

IEnumerable<string> nonNullableList = list.Where(s => s != null);
string nonNullableValue =             list.First(s => s != null);
nonNullableValue =                    list.Single(s => s != null);

nonNullableList =                     list.Where(s => !string.IsNullOrEmpty(s));
nonNullableValue =                    list.First(s => !string.IsNullOrEmpty(s));
nonNullableValue =                    list.Single(s => !string.IsNullOrEmpty(s));
```

![image](https://user-images.githubusercontent.com/6609929/129751253-6a4f9a2e-f368-4c00-8a84-ebb9c1a0bbf9.png)

**Comment by Dreamescaper** [comment]
Related: https://github.com/dotnet/csharplang/issues/3951

**Comment by CyrusNajmabadi** [comment]
I believe this is currently working as expected from the compiler perspective (teh dotnet/roslyn repo).  We'd need a language change at dotnet/csharplang in order to support this.  I'm going to close this out as i believe the corresponding lang issue is already being tracked.
