### ISSUE TITLE
Nullable references checks and params arrays

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/roslyn#55666]
Not sure if this is a bug, it was certainly unexpected to me and I can't find any documentation about it.
I am using XElement here as it's the type where I ran into this but the question is general for any reference type.

I was porting code to use nullable references and ran into code like the following
`new XElement( "Foo", new XElement( "Bar" ), null );`
this gave the error " error CS8625: Cannot convert null literal to non-nullable reference type."
This was surprising to me as passing expressions that possibly result in nulls to new XElement I thought was a very common pattern, meaning don't generate a child XML element for this argument.
The signature of the constructor is
`XElement (System.Xml.Linq.XName name, params object[] content);`

So should params arrays allow nulls for reference types withough a nullable reference check error?

**Comment by Dreamescaper** [comment]
I don't think there's any difference between params and non-params parameter.
If this array parameter allows null items - it should be declared as `object?[]`.

As for your `XElement` issue - it is simply nullability info, which is fixed now (see https://github.com/dotnet/runtime/issues/43416).

**Comment by davidhunter22** [comment]
Ah thanks for the link I tried in net6.0 and there error does go away.

Does raise a question for me that I also can't find an answer for. For a type like object[] used as an argument there is the nullability of the argument itself and then the nullability of the objects in the array. I assume object?[] refers to the array itself. Is there a way to specify the nullability of the elements?

**Comment by Dreamescaper** [comment]
`object?[]` refers to elements, `object[]?` - to the array itself, `object?[]?` to both.

**Comment by davidhunter22** [comment]
Thanks for the info very helpful
