### ISSUE TITLE
Invert If refactoring is missing unit tests for Visual Basic

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#55677]
There are tests for CSharp but not Visual Basic. See csharp tests at https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs

**Comment by AdamSpeight2008** [comment]
@ryzngard  Are these the unit tests? https://github.com/dotnet/roslyn/tree/main/src/EditorFeatures/VisualBasicTest/InvertIf

**Comment by ryzngard** [comment]
@AdamSpeight2008 that looks right. I swear I looked for this when reviewing the PR and did a FAR to see if `VisualBasicInvertMultiLineIfCodeRefactoringProvider` was used. Apparently it is.
