### ISSUE TITLE
CS8604 report possible null reference despite sufficient null checks have been performed with two variables

### ISSUE THREAD

**Issue by kbilsted** [dotnet/roslyn#55678]
**Version Used**: 
VS Community Version 16.10.4

**Steps to Reproduce**:
in csproj

```
    <Nullable>enable</Nullable>
    <LangVersion>8.0</LangVersion>
```

code

```
 class Test
    {
        void X()
        {
            Test? t1 = null;
            Test? t2 = null;

            if (t1 == null && t2 == null)
                return;

            if (t1 == null && t2 != null)
                throw new Exception("stop here");

            Receiver(t1);
        }

        void Receiver(Test t)
        {
        }
    }
```

**Expected Behavior**:
no CS8604 warning since if `t1==null` the code will either `return` or `throw`.

**Actual Behavior**:
report `t1` may be null

![image](https://user-images.githubusercontent.com/1616338/129790797-538b8884-d8e0-4623-946f-6b55e65198f2.png)

The example is boiled down from a real-life scenario found in https://github.com/kbilsted/ReassureTest.Net/

**Comment by RikkiGibson** [comment]
Thank you for filing this issue. This behavior is by-design for reasons described in https://github.com/dotnet/roslyn/issues/36927#issuecomment-508595947.
