### ISSUE TITLE
Write analyzer that rejects async void unit test methods

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5567]
The test runner can't wait for the test to finish and get exceptions from the task. So such tests are basically useless.

**Comment by tmat** [comment]
@ManishJayaswal Moved to Unknown.

**Comment by aochagavia** [comment]
I would like to work on this issue, but have never worked on Roslyn before. Therefore I have the following questions:

1. The Visual Studio solution contains many projects. In which one of them should I work? It is not clear to me which one of them corresponds to the test runner.
1. Where can I find documentation about analyzers (including examples)?

**Comment by tmat** [comment]
@srivatsn Is there a project in https://github.com/dotnet/roslyn-analyzers/tree/master/src that this analyzer would fit in?

**Comment by srivatsn** [comment]
Ideally we'd have an xunit.analyzers that would have this rule so that anyone using xunit gets the rule.

**Comment by tmat** [comment]
@aochagavia Would you mind starting conversation on https://github.com/xunit/xunit?

**Comment by aochagavia** [comment]
@tmat Done :wink: , should this issue be closed then?

**Comment by onovotny** [comment]
This is inaccurate for xUnit. xUnit properly handles async void test methods by using a custom synchronization context.
