### ISSUE TITLE
Investigate purpose of Logger.LogBlock calls

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#55685]
Are these useful? What kind of analysis has been done recently using the logged data? What information should be logged? Is other telemetry not sufficient?

**Comment by jinujoseph** [comment]
cc @dibarbet @NTaylorMullen i believe this is used in the LSP feature sets

**Comment by dibarbet** [comment]
Logblock is often used to capture data on how long the action inside the block takes.

I don't specifically use it in LSP for a couple reasons (I can't log a separate event for every LSP request, it is too much data.  And the execution is spread out across multiple methods).
But it is used in other features, I used it in toggle comment for example to track execution time.

**Comment by tmat** [comment]
@dibarbet How is the execution time reported? Do we collect telemetry for all LogBlocks all the time?

**Comment by dibarbet** [comment]
I believe only if the log message is >= loglevel.information - https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/Telemetry/VSTelemetryLogger.cs#L73

We output a start event and end event via the VS telemetry API.  They then handle adding the duration properties to the end event based on the corresponding start event

**Comment by dibarbet** [comment]
Example for this logblock - https://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CommentSelection/AbstractToggleBlockCommentBase.cs,77

We get two events for `vs/ide/vbcs/commandhandler/toggleblockcomment`
The first has properties like
| Property | Value |
| - | - |
|reserved.datamodel.action.result |	None |
|reserved.datamodel.action.resultsummary |	null |
|reserved.datamodel.action.type |	Start |

The second has properties like


| Property | Value |
| - | - |
|reserved.datamodel.action.durationinmilliseconds |	6.9987 |
|reserved.datamodel.action.poststartevent |	True |
|reserved.datamodel.action.result |	Success |
|reserved.datamodel.action.resultsummary |	null |
|reserved.datamodel.action.type |	End |
