### ISSUE TITLE
Allow access to Compilation that matches a C# Hot Reload

### ISSUE THREAD

**Issue by spadapet** [dotnet/roslyn#55683]
## Background and Motivation

The XAML Language Service (XLS) in Visual Studio 2022 is using Roslyn's Compilation object to build up type metadata (for parsing XAML and XAML hot reload). Normally, while debugging an app, XLS does not update the Compilation since the types in the running app aren't changing. Now with C# Hot Reload, the types in the running app can change and XLS needs to update the Compilation.

The problem is getting the correct Compilation that matches what C# Hot Reload used. Currently all XLS can do is ask the Roslyn Project to get the current Compilation. That may be incorrect if the user is actively changing their source code right after clicking the hot reload button. There isn't a way to get the C# Hot Reloaded Compilation.

Here's how XLS gets the current Compilation in the devenv.exe process:

```C#
var serviceProvider = ...; // Global VS service provider
var componentModel = serviceProvider.GetRequiredService<IComponentModel>(typeof(SComponentModel));
var workspace = componentModel.GetExtensions<VisualStudioWorkspace>().Single();
var project = workspace.CurrentSolution.Projects.Where(...).FirstOrDefault();
var compilation = await project.GetCompilationAsync();
// ...more work
```

As far as I know, Roslyn computes the Compilation for hot reload out-of-process and it's not available in the devenv.exe process. That's what this proposal is for: To transfer the hot reloaded Compilation to the devenv.exe process and add an API to allow access to it.

## Proposed API

I'm no Roslyn expert so I don't know where that API should be or what it would look like. Maybe it could be a new method on Microsoft.CodeAnalysis.Project similar to GetCompilationAsync(), like GetHotReloadCompilationAsync().

And optionally a new value on enum Microsoft.CodeAnalysis.WorkspaceChangeKind to let listeners of WorkspaceChanged know that a new hot reload Compilation is available. This is optional because I already have a way to know that C# Hot Reload happened

## Usage Examples

This is made up, but it shows the idea

```C#
var serviceProvider = ...; // Global VS service provider
var componentModel = serviceProvider.GetRequiredService<IComponentModel>(typeof(SComponentModel));
var workspace = componentModel.GetExtensions<VisualStudioWorkspace>().Single();
var project = workspace.CurrentSolution.Projects.Where(...).FirstOrDefault();

var compilation = await project.GetCompilationAsync();
XlsUseCompilation(compilation); // XAML tools consume the compilation

workspace.WorkspaceChanged += async (s, args) =>
{
    if (args.Kind == WorkspaceChangeKind.HotReloadCompilationChanged)
    {
        compilation = await project.GetHotReloadCompliationAsync();
        XlsUseCompilation(compilation); // XAML tools consume the hot reload compilation
    }
}
```

## Alternative Designs

I think any design would work for me as long as:
1) I know when C# Hot Reload happens in the devenv.exe process (and I do know that right now, although the WorkspaceChanged event from Roslyn could be more accurate)
2) I have access to the Compilation that matches what was hot reloaded

## Risks

The change shouldn't break anything since the APIs would be new. Performance would be affected in some way since now the devenv.exe process would need to be told about this new hot reload Compilation.

**Comment by sharwell** [comment]
> To transfer the hot reloaded Compilation to the devenv.exe process and add an API to allow access to it.

Roslyn has no concept for this, so I'm not sure it's even possible.

**Comment by spadapet** [comment]
> > To transfer the hot reloaded Compilation to the devenv.exe process and add an API to allow access to it.
> 
> Roslyn has no concept for this, so I'm not sure it's even possible.

Maybe I said it the wrong way, but @tmat has a PR for this: #55717

**Comment by tmat** [comment]
Implemented by https://github.com/dotnet/roslyn/pull/55889
