### ISSUE TITLE
Source Generator should generate source code that is usable by projects that reference the source generator project.

### ISSUE THREAD

**Issue by daemogar** [dotnet/roslyn#55688]
I have used the following configurations of VS and TargetFramework with various combinations and no source generated file is available to use within the main project. I can call ```Debugger.Launch()``` and walk through my code in the Source Generator project, but when I go to access the generated code, nothing seems to be there. I also cannot use any additional package references outside of the two required for source generators. I get the file not found message below.

**Example Project with Issues**
https://github.com/daemogar/BlazorServerWithSourceGenerator

**Version Used**:
IDE: VS Studio 2019 Preview and 2022 Preview
Blazor Server Size Application: .NET 5 and .NET 6
Source Generator Project: .NET 5, .NET 6, and NetStandard2.0

**Steps to Reproduce**:
Following the tutorial at https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview
1. Create a NET6 BlazorServerside project
2. Add a NetStandard2.0 class library with the Package References
3. Create the Generator Code File
4. Add the reference to the Generator library to the Blazor project
5. Restart Visual Studio
6. Try to use the generated code in the Blazor project

**Expected Behavior**:
The following source file should be generated. And I should be able to from any CS file in the application project access ```Hello.World.Message();```.
```cs
namespace Hello;

public class World
{
	public static string Message() => "Hello World!";
	public static string JsonString() => "{ `Hello`: `World` }";
}
```

**Actual Behavior**:
The ```ExampleGenerator.cs``` execute method gets called, but I cannot reference ```Hello.World.Message();``` from anywhere in the application project.

**File Not Found**
2>CSC : warning CS8785: Generator 'ExampleGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

**Comment by sharwell** [comment]
This issue is covered by https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145
