### ISSUE TITLE
CompilerGeneratedAttribute not applied to all generated functions

### ISSUE THREAD

**Issue by captainsafia** [dotnet/roslyn#55697]
**Version Used**: 
- Roslyn: 4.0.0-2.21354.7
- .NET: 6.0.100-rc.1.21415.3

**Steps to Reproduce**:

1. Create a new source file using top-level sources.
2. Add a local function definition.
3. Use a local inline lambda.

```csharp
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;

var app = WebApplication.Create(args);

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

string Hello() => "Hello, World!";
app.MapGet("/hello", Hello);
app.MapGet("/bye", () => "Bye");

app.Run();
```

In the code above, `Hello` and the inline lambda do not have the attribute applied in the generated code.

**Expected Behavior**:

The `CompilerGenerated` attribute is not added to inline lambdas and local functions in the top-level main.

For ASP.NET Core, we've had to resort to checking for the attribute or any of the mangled name characters (">" or "|") to validate whether or not a type is mangled.

**Actual Behavior**:

The `CompilerGenerated` attribute should be applied on all generated functions.

**Comment by tmat** [comment]
@dotnet/roslyn-compiler should confirm but I believe the attribute is not applied on members of generated type - if a type is marked with the attribute all its members are considered compiler-generated.

**Comment by jaredpar** [comment]
That matches my memory. The compiler attempts to minimize the number of attributes emitted to metadata because there is an associated runtime penalty for having them. Strategies like attribute the type if all members have it is a common pattern for us.

**Comment by tmat** [comment]
If we want to add "OriginalName" argument to CG attribute we will need to emit more of these attributes.

**Comment by jaredpar** [comment]
Yep. That will be necesary.

**Comment by captainsafia** [comment]
> @dotnet/roslyn-compiler should confirm but I believe the attribute is not applied on members of generated type - if a type is marked with the attribute all its members are considered compiler-generated.

Yep -- this is correct. As seen by the success I've had with implementing the `IsCompilerGenerated` check that walks up the declaring types for the attribute.

https://github.com/dotnet/aspnetcore/blob/a1bbdc4125e4dbc885bfa0e666ab6a2e10d04670/src/Shared/RoslynUtils/TypeHelper.cs#L21-L28

I'll close this issue now. If we end up needing to emit more attributes because of our decision around the original name thing we can address there.

TY!
