### ISSUE TITLE
Introduce local doesn't use var keyword

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Introduce-local-doesnt-use-var-keyword/1506094)._

---
[severity:It's more difficult to complete my work]
When using the "Introduce local" refactoring in Visual Studio, the variable introduced is declared using the type instead of using the `var` keyword. For example, start with the following code:
```csharp
public class Demo
{
	private class Inner
	{
		private readonly int val;

public Inner(int val)
		{
			this.val = val;
		}
	}

public void Foo()
	{
		var x = new List<Inner> { new Inner(1), new Inner(2), new Inner(3) };
	}
}
```

Highlight and do Alt+Enter on `new Inner(2)` and select "Introduce local".

This creates the following:
```csharp
public void Foo()
{
	Inner inner = new Inner(2);
	var x = new List<Inner> { new Inner(1), inner, new Inner(3) };
}
```

Ideally, it would create the following:
```csharp
public void Foo()
{
	var inner = new Inner(2);
	var x = new List<Inner> { new Inner(1), inner, new Inner(3) };
}
```

---
#### Feedback Bot on 8/18/2021, 01:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This should work. Maybe the case that the users 'var' setting is overriding this?

**Comment by sharwell** [comment]
> This should work. Maybe the case that the users 'var' setting is overriding this?

This is likely the case. I just tried the exact steps above in a project configured to use `var` everywhere, and it used `var` for the local variable.

**Comment by davidwengier** [comment]
Yep, this is definitely working with one or more of the following `.editorconfig` settings (or equivalent Visual Studio settings)

```
csharp_style_var_for_built_in_types=true
csharp_style_var_when_type_is_apparent=true
csharp_style_var_elsewhere=true
```
