### ISSUE TITLE
Invalid pretty-lister behavior when #If directive is preceeded by a semicolon

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#5570]
1. Type ";" on an empty line
2. Type "#If DEBUG" on the next line and press enter

Ovbserved:

```
;
#If DEBUGThen
#End If
```

Expected:

```
;
#If DEBUG Then
#End If
```

**Comment by CyrusNajmabadi** [comment]
CLosing out due to lack of broader feedback.  This is also an area we are no longer investing in.
