### ISSUE TITLE
AD0001: Could not resolve type with token 01000094 from typeref (expected class 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseParameterSyntax

### ISSUE THREAD

**Issue by ChaseFlorell** [dotnet/roslyn#55708]
### Analyzer

**Diagnostic ID**: CSC : warning AD0001: Analyzer 'XXX.Analyzers.Analyzers.DateTimeNowAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not resolve type with token 01000094 from typeref (expected class 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseParameterSyntax' in assembly 'Microsoft.CodeAnalysis.CSharp, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35')'. [/Users/runner/work/1/s/src/YYY/XXX.Foundation/XXX.Foundation.csproj]

**NuGet Packages**: 
```xml
<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
<PackageReference Include="Dawn.Guard" Version="1.12.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.11.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
```

### Describe the bug

We've written our own analyzer and added it to our projects via a `<ProjectReference />`. When building on Azure Devops using  the following tools

> Mono: 6.12.5
> Xamarin.iOS: 14.8.0.3
> XCode: 12.4

We are getting hundreds of thousands of lines stating 

> CSC : warning AD0001: Analyzer 'XXX.Analyzers.Analyzers.DateTimeNowAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not resolve type with token 01000094 from typeref (expected class 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseParameterSyntax' in assembly 'Microsoft.CodeAnalysis.CSharp, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35')'. [/Users/runner/work/1/s/src/YYY/XXX.Foundation/XXX.Foundation.csproj]

### Expected behavior
We should be able to compile without issue

### Actual behavior
Compilation times out and we're unable to proceed with our build.

## Additional context
Building locally with the following tools does not result in the same issues and does in fact allow us to build successfully.

```txt
JetBrains Rider 2021.2
Build #RD-212.4746.113, built on July 30, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
.NET 5.0.7
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, ide.tooltip.showAllSeverities=true, ide.mac.bigsur.alerts.enabled=TRUE, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.mac.file.chooser.native=TRUE, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.mac.bigsur.window.with.tabs.enabled=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=FALSE, awt.file.dialog.enable.filter=FALSE, debugger.show.values.use.inlays=TRUE, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, vcs.enable.add.ignored.directories.to.exclude=false, ide.allow.merge.buttons=TRUE, search.everywhere.settings=true, use.winp.for.graceful.process.termination=FALSE, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=TRUE, rdclient.asyncActions=false
Non-Bundled Plugins: cognitivecomplexity-rider (2021.2.0), com.alayouni.ansiHighlight (1.2.4), com.intellij.ideolog (203.0.27.0), com.intellij.resharper.HeapAllocationsViewer (2021.2.0), com.intellij.rider.plugins.nuke (2021.2.0), com.jetbrains.darkPurpleTheme (1.2), com.markskelton.one-dark-theme (5.3.0), com.thvardhan.gradianto (4.4), com.villains.intelij.plugin.trashpandatheme (1.6), fr.socolin.application-insights-debug-log-viewer (1.2.0), net.vektah.codeglance (1.5.4), com.microsoft.vso.idea (1.161.2), zielu.gittoolbox (212.7.6), io.wisetime.plugins.window.branch (0.6.1), com.jetbrains.rider.android (212.4746.113), Dart (212.4746.57), MetricsReloaded (1.11.2), com.intellij.resharper.azure (3.50.0.1253-2021.2), izhangzhihao.rainbow.brackets (6.19)
```

**Comment by Youssef1313** [comment]
@ChaseFlorell Can you try with a more earlier version of CodeAnalysis packages? e.g, 3.8.0

The higher version of CodeAnalysis packages requires higher version of .NET SDK (I don't know the exact mapping between those versions - there is already a documentation issue tracking that part)

**Comment by ChaseFlorell** [comment]
> @ChaseFlorell Can you try with a more earlier version of CodeAnalysis packages? e.g, 3.8.0
> 
> The higher version of CodeAnalysis packages requires higher version of .NET SDK (I don't know the exact mapping between those versions - there is already a documentation issue tracking that part)

Where might we find that issue? I tried with 3.8.0 and it yielded the same results.

**Comment by ChaseFlorell** [comment]
Update: 3.7.0 seems to have solved my immediate issue.
I still think there's value in having a matrix for what's supported for which build tools.

Thanks @Youssef1313 for pointing me in the right direction.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/issues/51478

I think this needs to be addressed soon, this problem has been reported multiple times.

cc @jmarolf @jinujoseph

**Comment by sharwell** [comment]
@ChaseFlorell Your can add the following line to any C# source file and the build will give you an error message showing the exact version of the C# compiler in use. This is the version you'll be able to reference from your analyzer.

```csharp
#error version
```
