### ISSUE TITLE
Benchmark algorithm options for LongestCommonSubsequence

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#55712]
The current class for calculating LongestCommonSubsequence in Roslyn is superlinear for space, which in some cases [can lead to OOM exceptions](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs#L216), especially when working on large edit sets (going from an empty document to 1000's of lines for example).

Razor [uses the linear-space variation of the same algorithm](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextDiffer.cs#L10-L14). This reduced memory usage comes at the expense of a "Big-O" that's about twice as bad though.

Given the success that Razor has had with the linear-space variation it's worth benchmarking both and seeing which one has better characteristics for the scenarios both teams care about. "wall-clock-time" is likely to be the important metric here, since Allocation and GC may interfere with performance.

If we can come to a consensus on which is preferable we might be able centralize our implementations and enjoy shared iteration on future improvements.

**Comment by jmarolf** [comment]
What is the frequency that we are encountering OOMs today? I would need to see some data to indicate that linear-space is preferred.

**Comment by ryanbrandenburg** [comment]
@jmarolf I'm not sure how to measure frequency for this, but the scenarios required to reproduce it seem fairly common. Making any edit to a 290 line Razor file (just the same Component pasted a bunch of times to reproduce, but I'm sure users have real Razor files that long) is sufficient to cause this, which seems pretty severe to me.

**Comment by jmarolf** [comment]
> is sufficient to cause this

What is this? Are we seeing OOMs even in 64-bit processes dues to memory compaction issues? I am all for exploring this but trading speed for memory usage is only something I want to do if we can measure or demonstrate that our current memory usage patterns are causing real customer problems.

**Comment by tmat** [comment]
@ryanbrandenburg Isn't the main problem in the code that uses this alg - IIRC it calls LCS for the initial request that results in comparison of empty and 200K-long sequence. The caller should special case this and not use LCS if the sequence is empty. Do we have scenarios other than this one where we hit OOM?

**Comment by ryanbrandenburg** [comment]
@jmarolf "OOM" is a bit tricky in this scenario, it's not literally out of memory it's running into a limitation in the size Arrays are allowed to be because the size of the array being created is ~159,015.

@tmat that was the original report, but @gundermanc showed me a repro for "small edit to existing large file" (I sent an email about it but can include it here if people find it useful). I believe @allisonchou already submitted a fix for the "Empty-to-200k" problem.

**Comment by gundermanc** [comment]
> If we can come to a consensus on which is preferable we might be able centralize our implementations and enjoy shared iteration on future improvements.

On the off chance our implementation has any redeeming qualities, [Editor also has a copy of LCS](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=/src/Editor/Text/Impl/DifferenceAlgorithm/TFS/LCSDiff.cs&version=GBmain&line=25&lineEnd=25&lineStartColumn=1&lineEndColumn=46&lineStyle=plain&_a=contents) we forked from Team Foundation Server years ago. I haven't looked too closely but it looks like the same algo Roslyn has. @Quenty had submitted some improvements IIRC.

> Arrays are allowed to be because the size of the array being created is ~159,015.

Is this really a hard limit? We have strings and char arrays much larger that than that generated by both TextMate and LSP JSON serialization.

**Comment by tmat** [comment]
> Is this really a hard limit?

There are two variations of the LCS alg. One that takes O(d(n+m)) memory and another one that is O(n+m). The problem is that the latter might be slower. We need benchmarks to see concrete numbers.

That said, another approach would be to partition the token sequences into smaller ones, run the alg on those and aggregate the results. We don't need to find the smallest amount of edits between the two sequences. We just use it for optimization, so it doesn't need to be precise.

**Comment by tmat** [comment]
I believe @allisonchou finished this work.
