### ISSUE TITLE
Compiler server unit tests ServerWithSamePipeNameExits and MutexStopsServerStarting are flaky in PR runs...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#5572]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_32/6236/

**Comment by jaredpar** [comment]
These were disabled via https://github.com/dotnet/roslyn/commit/c307ef46b8f90754e676d6165361cf8749242265#diff-e0b4cee1461babaede72f6b1a6ea3f45

**Comment by agocke** [comment]
Fixed by #5523
