### ISSUE TITLE
Re-enable test CommandLineTests.ReservedDeviceNameAsFileName 

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#55730]
CommandLineTests.ReservedDeviceNameAsFileName is causing a timeout on the net6p7 upgrade on coreclr test runs and has been skipped in https://github.com/dotnet/roslyn/pull/55681

Potentially related issue - https://github.com/dotnet/runtime/pull/54676

https://dev.azure.com/dnceng/public/_build/results?buildId=1302696&view=artifacts&pathAsName=false&type=publishedArtifacts should have dumps
the testhost process is at
![image](https://user-images.githubusercontent.com/5749229/130135563-c7d69175-ba11-4c41-aa97-79df28f05576.png)

**Comment by vatsalyaagrawal** [comment]
@jaredpar please prioritize. This test was disabled as it was blocking code flow.
