### ISSUE TITLE
Proposal: Avoid closures that capture a single reference-type variable per function

### ISSUE THREAD

**Issue by LordJZ** [dotnet/roslyn#55758]
Note: This proposal uses .NET 5 for examples. I examined the upcoming performance-related changes in .NET 6 [here](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/) and could not find anything suitable. I also did not find any mention of this on github, but please let me know if this is a duplicate.

# Background and Motivation

A .NET single-function delegate (singlecast?) carries the function pointer and the reference to context data (first argument). This first argument is used as `this` pointer for instance method calls and as the closure class reference ("DisplayClass") for `delegate` functions, lambda functions, local functions that convert to a delegate. (The context is also used even in strictly static use-cases for perf reasons, but irrelevant here.)

This means that each time there is a need to close over a variable, at least two allocations are performed: the closure class and the delegate class. In the popular case of closing over one reference-type variable, the closure class allocation can be avoided be reusing that variable as the first argument, which will improve code perf. This also applies to cases where the closure class is shared between multiple lambdas, but all of them only close over a single ref-type variable. It can be thought that this optimization is already implemented when the captured variable is `this`.

# Example

Here `__methodptr` means `ldftn` and 2-argument `new` for delegate types means calling the hidden ctor.

Consider this piece of code:
```C#
void Example1(TaskCompletionSource<object> tcs, CancellationToken ct = default)
{
    ct.Register(() => tcs.TrySetCanceled());
}
```
Currently it is lowered to this:
```C#
class DisplayClass1
{
    public TaskCompletionSource<object> tcs;
    internal void Lambda()
    {
        tcs.TrySetCanceled();
    }
}
void Example1(TaskCompletionSource<object> tcs, CancellationToken ct = default)
{
    DisplayClass1 closure = new DisplayClass1();
    closure.tcs = tcs;
    ct.Register(new Action(closure, __methodptr(DisplayClass1.Lambda)));
}
```
But can be lowered to this instead:
```C#
void Example1(TaskCompletionSource<object> tcs, CancellationToken ct = default)
{
    ct.Register(new Action(tcs, __methodptr(Lambda));
}
static void Lambda(TaskCompletionSource<object> tcs)
{
    tcs.TrySetCanceled();
}
```

In a similar vein this can be applied to event handlers and LINQ. And also `delegate` functions and local functions that convert to a delegate.

# Risks and Drawbacks

* Existing reflection code might break; this includes both end-user code and frameworks such as documentation generators, AOP providers, LINQ rewriters etc.
  *  LINQ rewriters will definitely break (or at least de-optimize) -- not sure how relevant they are in 2021 though.
* If a reflection-heavy code is written after this proposal is implemented, and later the captured variable changes, the reflection-heavy code may break for non-obvious reasons. This can be surprising for reflection users. This can be especially surprising with local functions, which have meaningful names and are more discoverable.
* 1-ref-variable captures and other cases may now have different performance characteristics. (Although this is simialr to how various lambda function kinds (static/non-static/method group conversions) have different perf characteristics.)

# Alternatives

Alternative A to the original example code is to hand-roll this optimization. Drawbacks: requires API support, ugly.
```C#
void Example1a(TaskCompletionSource<object> tcs, CancellationToken cancellationToken = default)
{
    cancellationToken.Register(static x => ((TaskCompletionSource<object>)x).TrySetCanceled(), tcs);
}
```

Alternative B is method group conversion. Drawbacks: requires exact signature match, arguably worse syntax, always instantiates the delegate class.
```C#
void Example1b(TaskCompletionSource<object> tcs, CancellationToken cancellationToken = default)
{
    cancellationToken.Register(tcs.TrySetCanceled);
}
```

Alternative C is creating an extension to change method signature. Drawbacks: pollutes the namespace, requires a separate class and method.
```C#
public static class Extensions
{
    public static void TrySetCanceledWithDifferentSignature<T>(
        this TaskCompletionSource<T> tcs, object sender, EventArgs args)
    {
        tcs.TrySetCanceled();
    }
}

// elsewhere
void Example2(Process process, TaskCompletionSource<object> tcs)
{
    process.Exited += tcs.TrySetCanceledWithDifferentSignature;
}
```

In my opinion, all alternatives require explicit developer effort to implement, and it would be nicer to support this optimization automatically out of the box.

**Comment by jaredpar** [comment]
Optimizations like this fall into the category of: 

> Yes this is possible and in the cases you mention will provide benefits. But are these patterns so predominate in existing code that it would be worth taking the time to implement support in the compiler? Or would we say be better off with an analyzer that did the hand unrolling for the customer? 

There are a couple of elements to consider with this optimization: 

1. Impact: essentially how predominant is this pattern in existing code? If it's very common then yes it's one we should look into. 
1. API guarantees: this essentially requires the compiler to gain knowledge of a number of BCL APIs and their behavior. That is generally something we've been reluctant to do in the past. The idea being customers could choose to implement the BCL a different way hence we could be taking bets on APIs that don't have the behavior we expect. These days though we're probably more open to this type of bet though. 
1. Risk: changing closure code has proven to be a source of unintended regressions in the past. Not unmanagable risk, just higher risk than the average change we make. Hence it's the type of work we'd need to schedule very early in a release to give it time to settle and feel comfortable with the changes. 

Overall though (1) is the most important consideration. Effectively what is the gain for this potential optimization in the wild? 

> Existing reflection code might break; this includes both end-user code and frameworks such as documentation generators, AOP providers, LINQ rewriters etc.

This is not really a concern. The compiler makes zero guarantees about how we emit closure / lambda / async code to metadata. We will, and previously have, changed our emit strategy when doing so provided substantial performance wins. Customers who depend on the structure of our metadata are doing so at their own risk and should expect to be broken from time to time. 

@stephentoub
