### ISSUE TITLE
Go-to-definition doesn't work on the target type of conversion operators

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#5575]
Invoke go-to-definition on the `Bar` reference in the operator:

```
class Foo
{
    public static explicit operator Bar(Foo a)
    {
        return null;
    }
}

class Bar
{
}
```

Expected: The cursor should jump to the class declaration.
Actual: It highlights the operator declaration instead. This happens for both explicit and implicit operators.  
This is a regression from VS2013.

**Comment by Pilchie** [comment]
This is because we now support binding at declarations, where VS2013 didn't.

**Comment by lorcanmooney** [comment]
It looks like this was fixed at come point. It doesn't repro for me any more as of 15.0.26228.4.
