### ISSUE TITLE
Switch with falltrough cases and assignment of a variable

### ISSUE THREAD

**Issue by sebfischer83** [dotnet/roslyn#55754]
**Version Used**: 
5.0.400

**Steps to Reproduce**:
```
internal Key[] Test<T>(T key, Key foundKey)
{
  switch ( key )
  {
    case string s:
      if ( s == foundKey.StringValue )
      {
        return new[] { foundKey };
      }
      break;
    case sbyte:
    case byte:
    case short:
    case int:
    case long l:
      if ( (long)System.Convert.ChangeType(key, TypeCode.Int64) == foundKey.NumericalValue )
      {
        return new[] { foundKey };
      }
      break;
    case ushort:
    case uint:
    case ulong u:
      if ( (ulong)System.Convert.ChangeType(key, TypeCode.UInt64) == foundKey.UnsignedNumericalValue )
      {
        return new[] { foundKey };
      }
      break;
    case Guid g:
      if ( g == foundKey.GuidValue )
      {
        return new[] { foundKey };
      }
      break;
    default:
      throw new ArgumentOutOfRangeException(nameof(key));
  }

  return Array.Empty<Key>();
}
```

**Expected Behavior**:
Why can't l not be assigned because any switch cases before are valid to cast them implicit to long?

**Actual Behavior**:
When trying to use l or u, the compiler told me it is possible uninitialized.
But in the debugger (when not try to use at compile time) the value is there.

**Comment by jcouv** [comment]
This is by design.
With `case int: case long l:`, if you pass an `int` value, then `int` pattern matched and the `long l` pattern is not evaluated and so `l` is considered not assigned.
If you want to propose a language change, please open a discussion thread in csharplang repo.
