### ISSUE TITLE
Inline Rename should include comments by default

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#55766]
For inline rename we should have `include comments` checked off by default. Is there a scenario where users wouldn't want comments to automatically rename?

![image](https://user-images.githubusercontent.com/46729679/130278546-a15a8ecd-e0cb-4f70-ad64-6df1a4893a13.png)

**Comment by ryzngard** [comment]
In general I think include in comments and strings should be off by default, it can very easily change things that don't need to be changed. Keep in mind that references in xml comments are already changed.


```csharp
class Person
{
    /// <summary>
    /// Initializes a <see cref="Person" />
    ///                                      ^-- This changes without checking include in comments
    /// </summary>
    Persion() { }
}

class Airplane
{
    // When a person boards a plane they must show their ticket
    //              ^-- does this need to change with rename?
    void Board() { }
}
```

There might be other examples where a variable or class name is a common word.

**Comment by CyrusNajmabadi** [comment]
I never ever want comments or code changed here (that isn't a cref).

**Comment by mikadumont** [comment]
Good point, the default behavior for cref should suffice and if not we can keep pointing the user to the `include comments` option.
