### ISSUE TITLE
Navigate backwards is broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55762]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Navigate-backwards-is-broken/1507326)._

---
Navigating backwards (CTRL+-) is broken again. Expected behavior is to be able to use "Go to implementation" and so on and then navigate back.

---
#### Feedback Bot on 8/19/2021, 01:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Roslyn doesn't supply any logic for this.  Indeed, we removed any Roslyn specific code for this in: https://github.com/dotnet/roslyn/pull/48717

this should likely be routed internally to editor/platform @jinujoseph .
