### ISSUE TITLE
Improve editor right-click context menu usability & footprint

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5578]
Brought up by @davkean, who may have additional thoughts.

Some ideas:
- Remove things that are absurd at the current caret position (for example, Insert Comment does this, but Rename does not)
- Collapse things where appropriate (two snippets items, three Code Map items (another team), etc.)
- Rearrange the overall list so that similar things are together (Cut/Copy/Paste are between Roslyn-related codegen features such as snippets and Insert Comment)

**Comment by Pilchie** [comment]
@kuhlenh is investigating this right now.

**Comment by Pilchie** [comment]
Moving to RTM, but I think everything we wanted to get done is done in RC, right @kuhlenh?

**Comment by Pilchie** [comment]
Can this be closed now @kuhlenh ?

**Comment by davkean** [comment]
I'm still seeing the following:

![image](https://cloud.githubusercontent.com/assets/1103906/22092917/7d7cde6a-de55-11e6-9ceb-2a2f3b677c04.png)

**Comment by davkean** [comment]
Uploaded a better screen shot

**Comment by kuhlenh** [comment]
The debugger team insisted on keeping Run To Cursor...and Find Matching Clones was borderline. My plan is to watch telemetry on them in 2017 and make modifications accordingly.
