### ISSUE TITLE
Improve refactoring error communication

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#5579]
Brought up by @davkean, who may have more thoughts.

Today, when refactorings (rename, extract method, etc.) encounter errors, they show modal dialogs. One suggestion is to use the status bar, but that may be too transient / subtle / terse (our extract method error display is multi-line). 

Is there something better we can do here?

**Comment by AdamSpeight2008** [comment]
What about including them to an entry in ETW?

**Comment by dpoeschl** [comment]
@pilchie Suggesting for 2.0 to give us time to discuss with the platform for potential VS-wide solutions.

**Comment by Pilchie** [comment]
@AdamSpeight2008 The idea here isn't telemetry for us, it's a less intrusive way of telling the user why their refactoring didn't work.

**Comment by AdamSpeight2008** [comment]
@Pilchie Telemetry not for you but for refactoring authors, of which I see two basic scope of error, warnings and information
* **Public**
 * Stuff you report back to the final user, eg Error Window
* **Private**
 * Stuff you report back to developer of the extension.  

I'm thinking of an additional panel in IDE so they can watch their specific error / events, happen whilst testting it. The existing IDE Error is for user code errors, eg specific to the project being currently worked one. Whilst *extension error list* would be for error coming from extensions. The user then could filter down to their specific extension, for example the one the are developing and see the errors. 

Once the extension / code fix has been release, there is the option for them to obtain some diagnostic data, to help the debug the issue. 
Advanced options in the Extension manager to enable and disable tracing / logging information for a specific extension. If publish via the visual studio gallery, potential look a anonymised telemetry from a larger sample.

**Comment by CyrusNajmabadi** [comment]
Closing out speculative proposals about changes in UI.  Haven't had an issue with this so far.  We should use issues to track changes we will make.  Note: in LSP, this is all controlled by the host.
