### ISSUE TITLE
Request: Small Roslyn changes to aid runtimes without UTF-16 strings

### ISSUE THREAD

**Issue by alexrp** [dotnet/roslyn#55798]
I'm opening this here because this is probably more of a Roslyn feature request than a C# language proposal, and because the request is probably not appropriate for broader C# standardization (yet, at least).

### Some Context

I'm working on a custom runtime / core library experiment. The idea is to try a clean slate implementation of .NET with many of the old legacy features removed, and to try out some radical ideas that are probably never going to happen in regular .NET due to compatibility concerns.

One of the things I'd like to do in my runtime is to get rid of UTF-16 strings. I think most people at this point acknowledge that they were a mistake and that UTF-8 would be ideal if we could restart .NET from scratch. There's clearly great demand for UTF-8 strings (see discussions and reactions on https://github.com/dotnet/csharplang/issues/184, https://github.com/dotnet/corefxlab/issues/2350, and https://github.com/dotnet/runtime/issues/933). Also, it's worth noting that [.NET nanoFramework](https://github.com/nanoframework) is an already-established example of a .NET platform that only supports UTF-8 strings.

I want to go one step further, though: I don't think swapping one opinionated encoding for another is the answer. Rather, I'd prefer something along the lines of Swift's `String` which is just an opaque container of characters that offers different views into its contents. For example, a user might say `str.EnumerateScalars()`, `str.EnumerateGraphemes()`, `str.EnumerateUtf8()`, `str.EnumerateUtf16()`, etc. Also, I would remove the `System.Char` type as its existence no longer makes sense. In this world order, `System.String` could use whatever internal encoding makes sense - it could even be configurable by the user.

### Problems & Proposed Solutions

Implementing `System.String` as a non-UTF-16 container of characters in a custom platform is fairly easy without language support, but there are a few issues that prevent it from working seamlessly. I'll list them below along with some proposed solutions.

#### 1. Roslyn assumes the presence of `System.Text.StringBuilder.Append(char)`.

This happens here: https://github.com/dotnet/roslyn/blob/ba75cb8c43275d935110cb4138f7bc68a75c2957/src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordToString.cs#L74-L78

This is the only of these issues that actually blocks me from not having `System.Char` in my runtime.

**Solution:** Just fall back to `System.Text.StringBuilder.Append(string)` with a string literal if the `char` overload is unavailable.

#### 2. Roslyn assumes the presence of `System.String.Length` and `System.String.Chars`

Roslyn generally does a good job of only using members on `System.String` if they actually exist. However, in the case of `Length` and `Chars`, there is (AFAICT) one single instance where their presence is assumed: https://github.com/dotnet/roslyn/blob/6920e1e044dcadbc53e0af7d1582190fdcb88ec6/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs#L67-L71

This causes "missing predefined member" errors when trying to `foreach` over a string, which is not very actionable for a user.

**Solution:** I think the above method can just be changed to use the safe `TryGetSpecialTypeMethod` method. The null checks at the end of the method should then get the right result, causing a fallback to the regular enumeration pattern.

#### 3. Roslyn *seems* to assume that `System.String` implements `System.Collections.IEnumerable`

Define `System.String` as something like:

```csharp
namespace System;

public sealed class String
{
}
```

Then build this code:

```csharp
const string S = "abcd";

foreach (var c in S)
{
    _ = c;
}
```

Roslyn will crash with: `CSC : error CS7038: Failed to emit module 'string-experiments': Unable to determine specific cause of the failure.`

Annotating `System.Collections.IEnumerable` and `IEnumerator` with some `[Obsolete]` attributes reveals:

```
error CS0619: 'IEnumerable.GetEnumerator()' is obsolete: 'Use the generic IEnumerable<T>.GetEnumerator instead.'
error CS0619: 'IEnumerator.Current' is obsolete: 'Use the generic IEnumerator<T>.Current instead.'
```

**Solution:** I'm... not sure. Maybe someone with more expertise in this area could weigh in. Technically, this doesn't matter *that* much since the code would be illegal in this scenario anyway, but as with the 2nd problem above, it would probably be good to somehow provide a more relevant/graceful error, even if that just means falling back to the generic "this thing doesn't seem to be enumerable" error.

---

I understand that supporting odd scenarios like this is not necessarily desirable, but my hope is that the proposed changes are sufficiently non-invasive that they would be acceptable.

**Comment by jaredpar** [comment]
Thanks for filing the detailed report. 

The compiler today takes a rather hard dependency on the APIs that `string` implements. That is because it is one of the few types that is considered core to the platform. As such the compiler is only designed and tested to work with `string` that meet the API surface we expect. It is essentially a requirement of any corelib to support these APIs. 

Agree that some of these changes are trivial but others are not. Overall though it's not the type of change we typically take to the compiler. It's effectively code to support scenarios that aren't supported. 

I would say the best path forward is to implement the changes in a fork of roslyn. At such a time the work gets to a point where it's out of the experimental / research phase we could consider again whether to take such changes back into the compilers
