### ISSUE TITLE
VB NavBar doesn't always navigate to first member in (especially in Metadata as source)

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#558]
Ported from TFS WorkItem: **1036385**

---

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1.&nbsp; Add this code to a VB Console app's main method:
<FONT size=4 face=Consolas><FONT size=4 face=Consolas>

</FONT></FONT><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas>Dim</FONT></FONT></FONT><FONT size=4 face=Consolas><FONT size=4 face=Consolas> df </FONT></FONT><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas>As</FONT></FONT></FONT><FONT size=4 face=Consolas><FONT size=4 face=Consolas> System.ComponentModel.</FONT></FONT><FONT color=#2b91af size=4 face=Consolas><FONT color=#2b91af size=4 face=Consolas><FONT color=#2b91af size=4 face=Consolas>AddingNewEventArgs</FONT></FONT></FONT><FONT size=4 face=Consolas><FONT size=4 face=Consolas> = </FONT></FONT><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas><FONT color=#0000ff size=4 face=Consolas>New</FONT></FONT></FONT><FONT size=4 face=Consolas><FONT size=4 face=Consolas> System.ComponentModel.</FONT></FONT><FONT color=#2b91af size=4 face=Consolas><FONT color=#2b91af size=4 face=Consolas><FONT color=#2b91af size=4 face=Consolas>AddingNewEventArgs</FONT></FONT></FONT><FONT size=4 face=Consolas><FONT size=4 face=Consolas>()
</FONT></FONT>
1. Go to def on AddingNewEventArgs
2. Use the Nav bar to try and go the the first (default) constructor.

&nbsp;

RESULT: You go to the beginning of the file instead.

&nbsp;

EXPECTED: You go to the member.

&nbsp;

NOTES:
1. This only happens if the outlining region at the beginning of the file is collapsed.
2. It also happens in regular files, but only if you paste code like the MAS code.&nbsp; If you edit the code, the nav bar model re-computes tracking spans and it seems to work.

---

**Revisions:**

1) Created By Kevin Pilch-Bisson (9/26/2014 3:57:34 PM)

---

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me now.  Likely because thsi area has been rewritten several times.  Closing out as we haven't heard any issues about this in this time and there doesn't seem to be a problem now.
