### ISSUE TITLE
Roslyn Compiler Service is forcing unneeded GCs, wasting CPU time

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#55807]
https://github.com/dotnet/roslyn/pull/14345 introduced an aggressive GC strategy for VBCSCompiler, calling GC Collect 11 times in a row. I have no context as to this change (I'm assuming there was an internal thread covering this with my predecessor who ended up making the change), however, in [internalshare]\Public\davkean\DevDiv\1384095.etl.zip, I can see this is just wasting CPU cycles.

In that trace, `ServerDispatcher.RunGC` was invoked 3 times, triggering 11 blocking Gen2 GCs each (highlighted below). This was a total of 70% of the GCs in that process during this run. You can see that basically only the first and last GC actually made a dent in the all 4 heaps (in green):

![image](https://user-images.githubusercontent.com/1103906/130411336-a3897176-33d8-4e2f-90b9-694e8c5d51dd.png)

I think this should be changed to:

``` C#
GC.Collect();
GC.WaitForPendingFinalizers();
GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
GC.Collect();
```

GC Stats:

![image](https://user-images.githubusercontent.com/1103906/130412016-09b224ad-3bc1-4aee-b9d0-49c44eb23d0e.png)

**Comment by sharwell** [comment]
> I think this should be changed to:
> 
> ```cs
> GC.Collect();
> GC.WaitForPendingFinalizers();
> GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
> GC.Collect();
> ```

These approaches are generally more complex than necessary. A single call to `GC.GetTotalMemory(true)` is typically sufficient.

**Comment by jaredpar** [comment]
> I have no context as to this change (I'm assuming there was an internal thread covering this with my predecessor who ended up making the change

The reason for this method in general is to quite literally reduce the amount of memory that VBCSCompiler takes up in task manager. When this method is omitted there is strong user feedback that "VBCSCompiler is a memory leak". Hence this method serves to reduce the committed memory of the VM to help with user perception but is overall not critical to the performance of the process. In fact this likely reduces performance because it will prune `WeakReference` values that we depend on.

**Comment by jaredpar** [comment]
@agocke may remember why 11 was chosen but that was before me.

**Comment by agocke** [comment]
Experimental evidence that there was a problem with finalizers where repeatedly running finalizers, gc'ing, then running finalizers again would seem to free more memory.

This was dialed in for the desktop runtime -- feel free to remove it if it's no longer necessary and the underlying metadata from PEModules is getting freed.

**Comment by davkean** [comment]
Take a look at VS's algorithm for this in GCService.RunFullGCAndCleanup. It factors in whether the successive GCs are productive and if not breaks the loop.

**Comment by sharwell** [comment]
> Take a look at VS's algorithm for this in GCService.RunFullGCAndCleanup. It factors in whether the successive GCs are productive and if not breaks the loop.

This is exactly what `GetTotalMemory(true)` does. I prefer this one-line call for overall simplicity.
