### ISSUE TITLE
Interpolated String Concatenation in .NET 6 is incorrect

### ISSUE THREAD

**Issue by jayendusharma** [dotnet/roslyn#55809]
### Description

Interpolated string concatenation output is different between .NET 5 and .NET 6 preview 7

### Regression?

yes

### Other information

Running the following code snippet in .NET 5 

```csharp
using System;

int a = 0;
string b = nameof(a);
Console.WriteLine($"Name, " + $"Value {a} ," + $"Name {b} .");
Console.ReadLine();
```

gives the following output: "Name, Value 0 ,Name a ."

in .NET 6 the output is: "Name,  ,0Value  .aName".

This is incorrect and shouldn't change

**Comment by jcouv** [comment]
This was fixed in 17.0p4 by PR https://github.com/dotnet/roslyn/pull/55494. Thanks for reporting
