### ISSUE TITLE
No Warning or Error notification after enabling IDE0060 (Remove unused parameter) when method is Obsolete or from an Interface.

### ISSUE THREAD

**Issue by blankor1** [dotnet/roslyn#55810]
**Version Used**: 
netcoreapp3.1
Microsoft.Internal.Analyzers Version="2.6.5
StyleCop.Analyzers" Version="1.1.118
Roslynator.Analyzers" Version="3.0.0
Microsoft.Build.Traversal" Version="2.0.34
<img width="502" alt="package" src="https://user-images.githubusercontent.com/36236746/130434681-92ecbfb7-b606-4965-bf31-653dc007f363.PNG">

**Steps to Reproduce**:

1. In Stylecop.ruleset, set 
```
<Rules AnalyzerId="Microsoft.CodeAnalysis.CSharp.Features" RuleNamespace="Microsoft.CodeAnalysis.CSharp.Features">
    <Rule Id="IDE0060" Action="Error" />
  </Rules>
```
2. Create Interface "ITest.cs"
```
interface ITest
    {
        public void Test(int a, int b);
    }
```
3. Create a class implementing ITest interface and write methods
```
class Program: ITest
    {

        public void Test(int a, int b)
        {
            Console.WriteLine(a);
        }

        [Obsolete]
        public void Test1(int a, int b)
        {
            Console.WriteLine(a);
        }

        public void Test2(int a, int b)
        {
            Console.WriteLine(a);
        }
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```

**Expected Behavior**:
All three methods report Error IDE0060

**Actual Behavior**:
"Test" and "Test1" method not report any Error or Warning, only "Test2" method report Error normally.
<img width="364" alt="IDE0060Result" src="https://user-images.githubusercontent.com/36236746/130434919-255a3899-a642-4a06-aa85-47faf0e034d9.PNG">

**Comment by CyrusNajmabadi** [comment]
This is by design.  For an interface implementation, you can't remove the parameter, or else the interface will not be implemented anymore.

For obsolete, we assume you are not touching this anymore and are already moving people to some other api.  Removing the parameter would be an abi break, which you don't want (which is why you put on obsolete).
