### ISSUE TITLE
Warning S3900 from Sonar is not showing up

### ISSUE THREAD

**Issue by lflender** [dotnet/roslyn#55846]
**Version Used**: 

Visual Studio 2019 16.10.3
Sonar nuget 8.27.0.35380
Windows 10 20H2

**Steps to Reproduce**:

1. Install Visual Studio
2. Install Sonar nuget
3. Have a .editorconfig specifying "dotnet_diagnostic.S3900.severity = warning" at the root of your directory
4. Copy and paste the code described as non-compliant in https://rules.sonarsource.com/csharp/RSPEC-3900
See that no warning is displayed in Visual Studio

**Expected Behavior**:

Warning showing up in the Error List window, just like any other warning from Sonar

**Actual Behavior**:

The warning is not showing up.

Follow up from https://github.com/SonarSource/sonar-dotnet/issues/4824

**Comment by sharwell** [comment]
Resolving as external. As described in https://github.com/SonarSource/sonar-dotnet/issues/4824#issuecomment-904682000, the analyzer project is only partially evaluating the outputs from **.editorconfig** as they apply to the project, which in this case prevents the rules from running even if they are enabled by the user.
