### ISSUE TITLE
Why the Visual Studio's watch window show the property , and the "@" in front of "type".

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55859]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Why-the-Visual-Studios-watch-window-sho/1036342)._

---
I have a class, and has one property naming “type”, and I know Microsoft’s General Naming Conventions.

For something reason, I have to use “camelCasing”.<br>
Based on the above, I have some questions.<br>
Is the word “type” in C# is a reserved word or keyword?<br>
If yes, and where can I find the document?<br>
If no, why the Visual Studio’s watch window shows property and the “@” in front of “type”.

![image](https://user-images.githubusercontent.com/41759/130674067-3a131554-3344-425b-a979-ca6599d112f2.png)

---
#### Feedback Bot on 5/19/2020, 02:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/20/2020, 09:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### CTW on 6/27/2020, 10:17 AM: 

<p>Hi </p><p>Do you have any updates?</p>

#### Feedback Bot on 7/2/2020, 11:16 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### CTW on 7/3/2020, 09:27 AM: 

<p>Thanks for your reply.</p><p>I want to understand why the property "type" in Visual Studio watch windows to be "@type". I know the prefix "@" is mean the C# keyword, but I could not find "type" is a C# keyword at Microsoft Doc. Can you help me find it? Thank you.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
`type` is a C# contextual keyword (in the context of attributes).  See the language specification here: https://github.com/dotnet/csharplang/blob/main/spec/attributes.md#attribute-specification

The debugger code here just puts @ in front of all keywords (contextual or otherwise) to ensure there's no chance of parsing issue in the parser that handles the expressions in things like the watch window.
