### ISSUE TITLE
Compiler error message with unresolved parameter placeholders in VS2019 16.11: "ENC0088	Modifying the body of '{0}' will prevent the debug session from continuing due to internal error: {1}"

### ISSUE THREAD

**Issue by CaiusJard** [dotnet/roslyn#55863]
Steps to reproduce

Make a new .NET 5 Console app and paste this body as the Main:

```
        static void Main(string[] args)
        {
            int rows = 2;
            int cols = 2;
            var x = new decimal[rows + 1][];
            a(x, new[] { 0m }, new[] { 0m });
            var grid = new decimal[cols + 1][][];
            b(grid, 0);

            return;

            static void a(decimal[][] row, decimal[] l, decimal[] r)
            {
                row[0] = l;
                row[^0] = r;
            }
            static void b(decimal[][][] grid, int column)
            {
                var b = grid[^999][column];
                var c = b[0]+1;
            }

        }
```

Run it, let it crash on the `[^0]` in local static func `a()` and leave the code paused

![image](https://user-images.githubusercontent.com/68939130/130402105-71033cc4-a990-4379-9553-0d81e9c2c23f.png)
 

Alter the `[^999]` in `b()` so that it is any other number (any code change in `b()` will do, actually)

![image](https://user-images.githubusercontent.com/68939130/130402236-28f2a5ba-c6bb-4b79-ad5b-6df9f0240a2b.png)

Some internal compilation error occurs and this shows in VS:

![image](https://user-images.githubusercontent.com/68939130/130402320-80a10a58-9a72-415e-8ed8-c66eb6ba9d7d.png)

---

Please advise what additional info would be needed. I Was running 16.10.3 of VS and some earlier .net SDK. Now up to date with 16.11 and 5.0.400 sdk; the issue still presents

**Comment by tmat** [comment]
Does not reproduce in VS 17.0.0 Preview 5.0
