### ISSUE TITLE
CS8629: Nullable value type may be null' reported when it can not be null.

### ISSUE THREAD

**Issue by Tape-Worm** [dotnet/roslyn#55862]
I'm getting CS8629 on a piece of code that should not be null:
```
if (layers[0].ClearColor is not null) // ClearColor is a nullable value type.
{
   target.Clear(layers[0].ClearColor.Value); 
}
```

ClearColor is a nullable value type (`Nullable<GorgonColor>`).  And even though I'm checking for null, it's still giving me the CS8629 warning.  Just for reference, the item in layers[0] is non-nullable (e.g. `Layer[] layers;`).

I've run this code many times with null and without and it all works perfectly. Is there something I'm missing or is there something wrong in the analyzer?

**Comment by jaredpar** [comment]
This behavior is "By Design". The compiler does not track individual array element null state in the analysis. The preferred pattern is: 

```c#
if (layers[0].ClearColor is {} color) // ClearColor is a nullable value type.
{
   target.Clear(color); 
}
```

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md#element-access

**Comment by Tape-Worm** [comment]
Ah I see.

I have to say, this is not a great solution. For instance, I have 2 checks in that function.  In order to do what you describe, I need to create two new variables color0 and color1 to do the check:

```csharp
if (layers[0].ClearColor is {} color0)
{
   
}

if (layers[i].ClearColor is {} color1)
{

}
```  

So while the analyzer may not be wrong, this design is no good for my needs.

So, in order to address what I need, I've done this workaround (which gets rid of the warnings):
```csharp
GorgonColor? color = layers[0].Color;

if (color is not null)
{
}

for (int i ...)
{
   color = layers[i].Color;

   if (color is not null)
   {      
   }
}
```

It would be nice if I had a consistent pattern to use.
