### ISSUE TITLE
Comment selection on a line with a collapsed region should comment the whole region

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#5587]
Suggestion from @yishaigalatzer.

**Comment by CyrusNajmabadi** [comment]
Closing out.  AFAICT, this is the behavior:

If i invoke comment-selection on this:

![image](https://user-images.githubusercontent.com/4564579/152586729-9d19095e-8e20-4b09-8486-3fc3c19c4448.png)


I get:

![image](https://user-images.githubusercontent.com/4564579/152586758-13b90f73-eb10-4a2f-b748-5d2bce52a5b9.png)
