### ISSUE TITLE
Extract local function includes nameof parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55887]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extract-local-function-includes-nameof-p/1511523)._

---
[severity:It bothers me. A fix would be nice]
The "Extract local function" refactoring is nice - especially how it prefers static local functions - but one thing I've noticed is that it includes arguments that don't need to be passed because they're only used for their name.

Example:

```
       private static int calculateFoo(int oldfooparam, int newfooparam)
        {
            if (oldfooparam > 10)
            {
                throw new ArgumentException($"You passed a value for {nameof(oldfooparam)} that is not supported.  Try using the {nameof(newfooparam)} argument which supports larger values.", nameof(oldfooparam));
            }
            return newfooparam + oldfooparam; // implementation does not matter
        }
```

When calling "Extract local function" and using the name `ValidateFoo` refactors to this:

```
        private static int calculateFoo(int oldfooparam, int newfooparam)
        {
            ValidateFoo(oldfooparam, newfooparam);
            return newfooparam + oldfooparam; // implementation does not matter

static void ValidateFoo(int oldfooparam, int newfooparam)
            {
                if (oldfooparam > 10)
                {
                    throw new ArgumentException($"You passed a value for {nameof(oldfooparam)} that is not supported.  Try using the {nameof(newfooparam)} argument which supports larger values.", nameof(oldfooparam));
                }
            }
        }
```

This code works after the refactor, but it's not needed to pass `newfooparam` to this function AND this sort of breaks the point of using `nameof` in the first place - because the `nameof` now refers to the name of the local function parameter and not the name of the parameter on the `calculateFoo` method.  Note that the compiler is smart enough to understand that if you delete the parameter newfooparam in the call to ValidateFoo and in the signature for ValidateFoo, that the newfooparam does not need to be captured, and it's ok for it to be static, and the `nameof` will correctly refer to the name of the `calculateFoo` argument.

---
#### Feedback Bot on 8/24/2021, 00:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Nimbus15** [comment]
@CyrusNajmabadi @nycdotnet Is there someone working on this issue? I'd would be willing to give it a go

**Comment by CyrusNajmabadi** [comment]
@Nimbus15 go for it!

**Comment by Nimbus15** [comment]
@CyrusNajmabadi I'm not sure if I have enough experience to make a fix, I have checked references such as https://docs.microsoft.com/en-us/visualstudio/ide/reference/extract-local-function?view=vs-2019 and I have checked the .editorconfig file that came with the project but I cant seem to think of a fix. Additionally, I am not sure I fully understand the problem.

**Comment by CyrusNajmabadi** [comment]
This has been fixed.  We only pass along the variables we need to pass along:

![Image](https://github.com/user-attachments/assets/13d6947a-6b32-497e-974a-ce993f3c381e)
