### ISSUE TITLE
Consider if "Add Using" quickfix should suggest adding "global" using as well

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#55895]
Relates to test plan https://github.com/dotnet/roslyn/issues/51307

**Comment by glennawatson** [comment]
Got directed here by @davidwengier 

Be useful if you could have an option if the global using should be injected into a certain file, I usually have a globalusings.cs file, or into the csproj. Maybe a set of options in a .editorconfig file?

**Comment by shawnwildermuth** [comment]
I think @glennawatson is on this. I think it would be nice to have the option to add it to a specific file (maybe search for files with just global using statements and if multiple, ask which to add to?)  While refactoring into a global using is nice, I think keeping all globals in a central file (e.g. usings.cs) is a better best practice.  I don't mind if it is two step (e.g. add using for X namespace, then refactor the namespace to move it to global), but I think a single one would be best.

**Comment by CyrusNajmabadi** [comment]
We are not intending for add-using to do anything special with 'global' for now.
