### ISSUE TITLE
Semantic Error in Object Initializer shows nonsensical quick fix

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#559]
Source:

```C#
class C {
	C c = new C {
		c = 45.M()
	};
}
```

Quick fix:

```C#
public static implicit operator C(C v) {
	throw new NotImplementedException();
}
```

This may be related to https://roslyn.codeplex.com/workitem/481

**Comment by jmarolf** [comment]
This has been fixed.  Please verify this in the next release after CTP 6.

**Comment by jmarolf** [comment]
@tmeschter could you verify this please?

**Comment by tmeschter** [comment]
Verified that we no longer offer the nonsensical quick fix.
