### ISSUE TITLE
ERROR: InsertNodesBefore: The item specified is not the element of a list (Only with ExpressionSyntax)

### ISSUE THREAD

**Issue by cth-latest** [dotnet/roslyn#55932]
**Version Used**:  3.11

**Steps to Reproduce**:

1. Parse a MethodDeclarationSyntax from text
2. Get the main block of the MethodDeclarationSyntax `methodDeclarationSyntaxe.DescendantNodes().OfType<BlockSyntax>().First();`
3. Get a list of all ExpressionSyntax child of the BlockDeclaration syntax `methodBlock.DescendantNodes().OfType<ExpressionSyntax>().ToList();`
4. Try to insert a SyntaxNode (Here the try is made with an AssignementSyntax)
```
for (int x = 0; x < methodChilds.Count * 2; x += 2)
{
    methodChilds = methodDeclarationSyntaxes[i].DescendantNodes().OfType<ExpressionSyntax>().ToList();

    if (x >= methodChilds.Count)
        break;

    // Example of a methodsNames element: _ = ARandomMethod();
    var b = ParseExpression(methodsNames[random.Next(methodsNames.Count)]);

    root = methodChilds[x].InsertNodesBefore<SyntaxNode>(methodChilds[x], new[] { b });
}
```

Here this for loop can seems a bit strange but i use that to insert expression syntax before each present ExpressionSyntax

Here that raise that error `System.InvalidOperationException: The item specified is not the element of a list`

Even if the loop can be strange without loop and testing with any element of the ExpressionSyntax list, that raise an exception.

This method work well when i do it for the ClassMembers (MemberDeclarationSyntax), i insert multiple MethodDeclarationSyntax  by this way and all is fine. I don't know why with the ExpressionSyntax that don't work

**Expected Behavior**: Inserted correctly  the Expressions

**Actual Behavior**: Getting `System.InvalidOperationException: The item specified is not the element of a list` error

**Comment by CyrusNajmabadi** [comment]
Please supply a full repro, thank you.

**Comment by Velka-DEV** [comment]
Of course, here is how to reproduce the bug:

Main Program:
```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace InsertionErrorDemo
{
    class Program
    {
        private static Random random = new Random();

        static void Main(string[] args)
        {
            string source = File.ReadAllText("../../ExampleClass.cs");

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source);
            SyntaxNode root = tree.GetRoot();
            
        

            List<MemberDeclarationSyntax> memberDeclarationSyntaxes = root.DescendantNodes().OfType<MemberDeclarationSyntax>().ToList();

            foreach(MemberDeclarationSyntax methodDeclarationSyntaxe in memberDeclarationSyntaxes)
            {
                BlockSyntax methodBlock = methodDeclarationSyntaxe.DescendantNodes().OfType<BlockSyntax>().First();
                var statementSyntaxes = methodBlock.Statements;

                foreach (StatementSyntax statement in statementSyntaxes)
                {
                    var b = SyntaxFactory.ParseStatement($"bool {RandomString(20)} = false;");

                    root = statement.InsertNodesBefore<SyntaxNode>(statement, new[] { b });
                }  
            }

            File.WriteAllText("code.txt", root.GetText().ToString());
        }

        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}
```

ExampleClass Content:
```
namespace InsertionErrorDemo
{
    public class ExampleClass
    {
        public int AMember = 0;
        public int BMember = 0;
        public int CMember = 0;
        public int DMember = 0;

        public void RandomMethod()
        {
            AMember = 20 * 100;
            BMember = AMember + DMember;
        }

        public bool RandomMethod2()
        {
            AMember = 20 * 100;
            BMember = AMember + DMember;

            return BMember == 0;
        }
    }
}
```

The exact same code with MemberDeclarationSyntax or MethodDeclarationSyntax work well (With of course methods inserted instead of statements)

**Comment by Velka-DEV** [comment]
@CyrusNajmabadi Do you prefer a ready to run repo instead ?

**Comment by Velka-DEV** [comment]
@CyrusNajmabadi Hello, any updates about this problem ?

PS: I've made a repro repo here: https://github.com/Velka-DEV/InsertionErrorDemo
