### ISSUE TITLE
Convert to switch statement changes behavior

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#55938]
**Version Used**: 
Version 16.11.1

As per https://twitter.com/vijayankit/status/1431056199550521346.

**Steps to Reproduce**:

1. Ctrl + . on the following switch:

``` C#
enum YesNo
{
    Yes,
    No
}

static YesNo? GetYesNo(string boolString)
{
    switch (boolString)
    {
        case "Yes":
            return YesNo.Yes;
        case "No":
            return YesNo.No;
        default:
            return default; // Returns "null"
    }
}
```

**Expected Behavior**:

Maybe:

``` C#
static YesNo? GetYesNo(string boolString)
{
    return boolString switch
    {
        "Yes" => YesNo.Yes,
        "No" => YesNo.No,
        _ => null,
    };
}
```

**Actual Behavior**:
``` C#
static YesNo? GetYesNo(string boolString)
{
    return boolString switch
    {
        "Yes" => YesNo.Yes,
        "No" => YesNo.No,
        _ => default; // Returns "0"
    };
}
```

**Comment by darjanbogdan** [comment]
It could be good enough to use a `default(YesNo?)` expression instead let the compiler infer, maybe as an additional suggestion to `default` once?

**Comment by CyrusNajmabadi** [comment]
Yes. Complexification should likely do this. And simplification can then return it to null/default if semantics stay the same.

**Comment by CyrusNajmabadi** [comment]
This now produces the following:

```c#
    static YesNo? GetYesNo(string boolString)
    {
        return boolString switch
        {
            "Yes" => (YesNo?)YesNo.Yes,
            "No" => (YesNo?)YesNo.No,
            _ => default,// Returns "null"
        };
    }
```

Not ideal in that the casts to `(YesNo?)` are inserted.  But better in that teh meaning is preserved.  Perhaps in the future a feature could recommend removing those and using `null` for the final branch.
