### ISSUE TITLE
[Interactive] async keyword is not recognized by IntelliSense

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#5593]
When I try to type an async method in Interactive, the IW doesn’t recognize the keyword “async”:
![image](https://cloud.githubusercontent.com/assets/1402694/10205176/8ec6fcae-6774-11e5-89f1-e02213c4b717.png)

This is what happens in the VS Editor (desired behavior):
 
![image](https://cloud.githubusercontent.com/assets/1402694/10205166/8366a242-6774-11e5-8d8c-3c6ff5f6b230.png)

**Comment by kuhlenh** [comment]
The async keyword is only recognized after I type "public." If I try to write a method:

```csharp
> async Task<DateTime> CountToAsync()...
```

The async keyword is not recognized. However, if I type:

```csharp
> public async Task<DateTime> CountToAsync()...
```
it is recognized...

**Comment by genlu** [comment]
@kuhlenh  That's really weird since I have a testcase for that, let me check

**Comment by genlu** [comment]
It works for me, did you use the latest bits?
![async](https://cloud.githubusercontent.com/assets/788783/10381544/854bc08a-6dd0-11e5-8f0a-0e0bfad83105.png)

**Comment by kuhlenh** [comment]
Yeah I just dogfooded...hmm. I'll try again tomorrow!

**Comment by kuhlenh** [comment]
:+1:
