### ISSUE TITLE
Can we have a search box in the method dropdown

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55945]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Can-we-have-a-search-box-in-the-method-d/1509783)._

---
![B7bf24bd37af84759aaf5430b1b213ca6637650607753931714_20210820-182254-image (1)](https://user-images.githubusercontent.com/9797472/132696267-1872a123-e6cf-4c2f-8993-0fb19b9d291d.png)

Can we have a search box in the method dropdown:

---
#### Feedback Bot on 8/25/2021, 02:39 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Related to #36812

**Comment by CyrusNajmabadi** [comment]
So you can already search just in the same file by doing:

![image](https://user-images.githubusercontent.com/4564579/132569036-0d5be4a9-84d0-45fe-a154-7a12b00cf874.png)

**Comment by CyrusNajmabadi** [comment]
You can also filter to members with:

![image](https://user-images.githubusercontent.com/4564579/132569108-95f3e58d-c389-4db3-b9d1-395b61f97126.png)

**Comment by CyrusNajmabadi** [comment]
If we wanted to have a search bar here, this would need to be rerouted to editor.  I'm not sure if this would be taken, esp. as LSP work may make this all obsolete with a new Breadcrumb view.
