### ISSUE TITLE
Rename enhancements 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55947]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-like-ReSharper/1503614)._

---
I have had to stop using ReSharper due to its terrible performance hit.
However I really miss its ability to rename variables and classes. I do this a lot as I have other coders who work for me and dont name things properly. (yes I know thats my fault)
VS is terrible at renaming classes especially if you rename an ASP web page. It forgets about the class behind?
Make a copy of a page and renames the page but not the class behind so now you have a duplicate class.
Renaming functions doesnt work very well and generally breaks things as it doesnt go through the entire solution. ReSharper is really really good at this.
Just a thought.
Craig

---
#### Feedback Bot on 8/16/2021, 01:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
