### ISSUE TITLE
Make the external sources node available in design mode as well. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55946]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Make-the-external-sources-node-available/1513974)._

---
Make the external source node available all the time even when I write my code.  It would be just as useful to have access to external sources while writing code. Today I have to use ILSpy all the time.

---
#### Feedback Bot on 8/25/2021, 08:06 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by davidwengier** [comment]
Closing, this is debugger, not us. I've reopened the feedback ticket
