### ISSUE TITLE
Option to suppress C# inline type hints for discarded parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55943]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-to-suppress-C-inline-type-hints-/1464747)._

---
I have enabled the `Display inline type hints` and while it's overall a very useful feature, when I use a discard in a lambda, they're still shown for those parameters, i.e. `collection. Where(_ => true)`. There would be a type hint for a non-existing variable.

I suggest either suppressing the inline type hints there everytime or adding an option to suppress the type hints on discards.

---
#### Feedback Bot on 6/30/2021, 08:00 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
