### ISSUE TITLE
Group Intellisense extension method suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55948]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Group-Intellisense-extension-method-sugg/1511496)._

---
> As a software developer, I have too many extension methods...

The Intellisense popup already allows the user to filter possible completions by member type, i.e. filter in & out all fields, properties, events, methods, and extensions.

If reducing the haystack to only fields, properties, events, or member methods can suffice, extension methods can grow in sufficient number to render the filter negligible, which is a break to discoverability:

! [image.png] (https://aka.ms/dc/image?name=Bcdd9fe5ed751468980887f8337699b21637653264247469585_20210823-154019-image.png&tid=cdd9fe5ed751468980887f8337699b21637653264247469585)

Hence the suggested new feature:

- Enable the user to group the extension methods by assembly / nuget package / namespace, i.e. like HTML's `<optgroup>`.
- Enable the user to configure a grouping threshold, i.e. _« Do not group extensions if there are less than THRESHOLD methods. » _
- Enable the user to toggle the grouping behavior on the fly, not only in the main configuration panel.
- Enable the user to filter in & out entire groups of extension methods.
---
! [image.png] (https://aka.ms/dc/image?name=B65062dd007004453ad1f79bb2aa81e5c637653263097203022_20210823-153825-image.png&tid=65062dd007004453ad1f79bb2aa81e5c637653263097203022)

---
#### Feedback Bot on 8/24/2021, 00:23 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by genlu** [comment]
Similar to #19256

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
