### ISSUE TITLE
Provide ability to remove enclosing block without its contents

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55949]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-ability-to-remove-enclosing-bloc/1497962)._

---
Sometimes there's a need to remove the enclosing block (like "using", "if", etc.) but leave its contents intact. While removing the opening keyword is pretty easy, it might be troublesome to find and delete the closing keyword or character ("}" character or "End Using", "End If", etc. statement) and then reformat the remaining part. The editor could do it for us.

---
#### Feedback Bot on 8/10/2021, 02:25 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
