### ISSUE TITLE
Make InlineRenameService.StartInlineSession more asynchronous

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5595]
"Event hookup on tab" blocks the UI thread while starting the rename session (specifically constructing the rename info). Customers have reported that this is slow, but there are some mitigations I can think of:
- StartInlineSession gets a full semantic model when it can probably get away with a speculative one (since it's just binding the trigger token). I think this would definitely work in the event hook up case, so we might have to add another overload to do that.
- StartInlineSession computes whether to force the overloads checkbox while computing rename info. This could be made async as long as we had some UI affordance that matched the asynchrony  (a spinner over the checkbox or something)

**Comment by CyrusNajmabadi** [comment]
This is now already StartInlineSessionAsync.
