### ISSUE TITLE
VB.NET explicit cast to integer error fix wraps the argument in braces twice

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55970]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VBNET-explicit-cast-to-integer-error-fi/1515708)._

---
[2021-08-27_08-56-06.gif] (https://aka.ms/dc/file?name=Bac2233f18be846b583952e0f94dd0723637656442420621342_2021-08-27_08-56-06.gif&tid=ac2233f18be846b583952e0f94dd0723637656442420621342)

---
#### Feedback Bot on 8/27/2021, 00:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be investing in these scenarios.
