### ISSUE TITLE
Consider listing all feature flags in src/VisualStudio/Core/Def/PackageRegistration.pkgdef

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#55974]
Only two of Roslyn's feature flags are currently listed in `src/vscommon/featureflags/FeatureFlags.xml`:
- `Roslyn.PartialLoadMode`
- `Xaml.EnableLspIntelliSense`

4 feature flags are listed in https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/PackageRegistration.pkgdef.

All these are displayed in Options > Preview Features. I think we should remove Roslyn's feature flags from FeatureFlags.xml and move them to PackageRegistration.pkgdef.

For feature flags not listed above: Should we present all feature flags there instead of having some of them displayed in C#/VB specific option panes?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to make this change, we should just do it.  The tracking issue doesn't solve things for us.
