### ISSUE TITLE
Invoking Value Tracking may not open window right away

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#55986]
**Version Used**: Version 17.0.0 Preview 4.0 [31626.483.main]

**Steps to Reproduce**:

1. Invoke Value Tracking on a large repository

**Expected Behavior**: The window appears right away, even if it's still being populated.
**Actual Behavior**: Nothing happened.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack fo feedback.
