### ISSUE TITLE
Can't install C# Interactive extension to Visual Studio 2015

### ISSUE THREAD

**Issue by ashleydavis** [dotnet/roslyn#5598]
I'm using Visual Studio 2015 on Windows 8.1.

I compiled the Interactive Window project: https://github.com/dotnet/roslyn/tree/master/src/InteractiveWindow

I opened the 'Binaries\Debug' directory and double-clicked the generated vsix file: Microsoft.VisualStudio.VsInteractiveWindow.vsix

The extension fails to install.

It appears to be something to do with 'Python Tools for Visual Studio', although I have uninstalled that I still can't install the extension.

I get the following error messages in popups:

![vsix installer error](https://cloud.githubusercontent.com/assets/625126/10207932/f062ef6a-6812-11e5-9972-9344ca5a0cc3.png)
![vsix installer error 2](https://cloud.githubusercontent.com/assets/625126/10207934/f3701426-6812-11e5-9e08-4631a7bcb9b5.png)

Following is the error log that was saved to file:

30/09/2015 4:44:51 PM - Microsoft VSIX Installer
30/09/2015 4:44:51 PM - -------------------------------------------
30/09/2015 4:44:52 PM - Initializing Install...
30/09/2015 4:44:52 PM - Extension Details...
30/09/2015 4:44:52 PM - 	Identifier      : 1F42C6D0-F876-4AF0-8185-1BEB0A325BB2
30/09/2015 4:44:52 PM - 	Name            : VisualStudio Interactive Components
30/09/2015 4:44:52 PM - 	Author          : Microsoft
30/09/2015 4:44:52 PM - 	Version         : 42.42.42.42
30/09/2015 4:44:52 PM - 	Description     : Interactive components for Visual Studio.
30/09/2015 4:44:52 PM - 	Locale          : en-US
30/09/2015 4:44:52 PM - 	MoreInfoURL     : 
30/09/2015 4:44:52 PM - 	InstalledByMSI  : False
30/09/2015 4:44:52 PM - 	SupportedFrameworkVersionRange : [4.5,)
30/09/2015 4:44:52 PM - 
30/09/2015 4:44:52 PM - 	Supported Products : 
30/09/2015 4:44:52 PM - 		Microsoft.VisualStudio.Pro
30/09/2015 4:44:52 PM - 			Version : [14.0,)
30/09/2015 4:44:52 PM - 		Microsoft.VisualStudio.VSWinDesktopExpress
30/09/2015 4:44:52 PM - 			Version : [14.0,)
30/09/2015 4:44:52 PM - 		Microsoft.VisualStudio.VWDExpress
30/09/2015 4:44:52 PM - 			Version : [14.0,)
30/09/2015 4:44:52 PM - 		Microsoft.VisualStudio.VSWinExpress
30/09/2015 4:44:52 PM - 			Version : [14.0,)
30/09/2015 4:44:52 PM - 
30/09/2015 4:44:52 PM - 	References      : 
30/09/2015 4:44:52 PM - 
30/09/2015 4:44:52 PM - Searching for applicable products...
30/09/2015 4:44:52 PM - Found installed product - Microsoft Visual Studio Professional 2013
30/09/2015 4:44:52 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
30/09/2015 4:44:52 PM - Found installed product - Microsoft Visual Studio Community 2015
30/09/2015 4:44:57 PM - The extension will be upgraded from version 1.0.0.50618.
30/09/2015 4:44:57 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
30/09/2015 4:44:57 PM - Found installed product - Global Location
30/09/2015 4:45:05 PM - The following target products have been selected...
30/09/2015 4:45:05 PM - 	Microsoft Visual Studio Community 2015
30/09/2015 4:45:05 PM - 
30/09/2015 4:45:06 PM - Beginning to install extension to Microsoft Visual Studio Community 2015...
30/09/2015 4:45:06 PM - Upgrading 'VisualStudio Interactive Components', version 1.0.0.50618 to version 42.42.42.42.
30/09/2015 4:45:10 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.BreaksExistingExtensionsException: This extension cannot be installed because the following extensions contain dependencies that would be broken as a result of this installation:
- Python Tools for Visual Studio
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

**Comment by ManishJayaswal** [comment]
@ashleydavis this is currently not officially supported although we want to enable this. We will look into it.

**Comment by KevinH-MS** [comment]
If you're just looking to play around with the C# Interactive Window, I'd recommend you check out:

http://www.microsoft.com/en-us/download/details.aspx?id=49189

If you're looking to make changes to the window and try them out in VS, then you can check out https://github.com/KevinH-MS/roslyn/commit/daa536a4a7deece4c9877004d041c79db59a6d2a.  It was branched quite a while ago, but if you make the same changes in your fork, you should be able to install the packages successfully on top of RTM.  As noted, you'll need to uninstall Python for now and then install the vsixes in this order:

1. Roslyn.VisualStudio.Setup.vsix
1. Roslyn.VisualStudio.InteractiveComponents.vsix
1. Roslyn.VisualStudio.Setup.Interactive.vsix

Note:  The Interactive stuff relies on compiler and IDE changes that aren't in VS2015 RTM, so the way this is working is by redirecting those assemblies for the entire VS process.  That will break other features in VS...namely, the debugger (expression evaluator) unless you also rebuild/install those as well.

As Manish said, we hope to have a more polished story for this very shortly (on top of VS 2015 Update 1).

**Comment by ManishJayaswal** [comment]
@KevinH-MS do we just need to validate that this works now and then close this issue?

**Comment by ashleydavis** [comment]
Visual Studio 2015 now comes with C# Interactive window. So this isn't an issue at all for me.
