### ISSUE TITLE
Need to provide option to show all signatures in methods.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55989]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Need-to-provide-option-to-show-all-signa/1502092)._

---

By default, all overloads of a method are shown as a single method name without a signature in the suggestion list.

It is cool feature to see all signatures in methods.
Please support this feature in the VS2019/VS2022

![Badfde624ee054073a7424ad774a97586637643731064238322_Show_all_signatures](https://user-images.githubusercontent.com/1408396/132563665-ea15c79d-0eb8-451f-8734-f7a69e42f871.png)

---
#### Feedback Bot on 8/13/2021, 03:09 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
Related to #12363 (particularly for the single-Tab case)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
