### ISSUE TITLE
Introduce Local should look for naming patterns in ForEachStatementSyntax.Expression

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#56]
``` C#
class Program
{
    static void Main(string[] args)
    {
        foreach (var num in GetNumbers())
        {

        }
    }

    static IEnumerable<int> GetNumbers()
    {
        return new[] { 1, 2, 3 };
    }
}
```

Highlight "GetNumbers()" in the foreach statement and use <kbd>Ctrl</kbd>+<kbd>.</kbd> to get the light bulb. Invoke "Introduce Local". Observe that the new local is named "enumerable".

Since we have code to detect known patterns like "GetBlah", it would be nice if we could notice that the Expression of the ForEachStatementSyntax was an InvocationExpression and try to recognize that pattern.

**Comment by giggio** [comment]
I would like to work on this issue, if possible. A few questions:
What code do you have to detect patterns like "GetBlah"? Where is it?
Is this for C# only?
Any pointer on where to start? I saw a lot of infrastructure on [IntroduceVariable](https://github.com/dotnet/roslyn/tree/master/src/Features/Core/IntroduceVariable). Is that it?

**Comment by giggio** [comment]
Oh, and here as well: https://github.com/dotnet/roslyn/tree/master/src/Features/CSharp/IntroduceVariable

**Comment by jmarolf** [comment]
[CSharpIntroduceVariableService](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/IntroduceVariable/CSharpIntroduceVariableService.cs,19) and [VisualBasicIntroduceVariableService](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/IntroduceVariable/VisualBasicIntroduceVariableService.vb,14) determine the name in IntroduceLocalAsync([C#](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs,25), [VB](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/IntroduceVariable/VisualBasicIntroduceVariableService_IntroduceLocal.vb,13)) and  IntroduceFieldAsync([C#](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/IntroduceVariable/CSharpIntroduceVariableService_IntroduceField.cs,17), [VB](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/IntroduceVariable/VisualBasicIntroduceVariableService_IntroduceField.vb,13)), but these both use methods from [AbstractIntroduceVariableService](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/IntroduceVariable/AbstractIntroduceVariableService.cs,20).
- [GenerateUniqueFieldName](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/IntroduceVariable/AbstractIntroduceVariableService.cs,179)
- [GenerateUniqueLocalName](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/IntroduceVariable/AbstractIntroduceVariableService.cs,199)

These then call into the semantic facts services([C#](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/LanguageServices/CSharpSemanticFactsService.cs,131), [VB](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Workspaces/LanguageServices/VisualBasicSemanticFactsService.vb,114)). Which in turn call GenerateNameForExpression([C#](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ISemanticModelExtensions.cs,206), [VB](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Workspaces/Extensions/ISemanticModelExtensions.vb,110)).  The best way to accomplish what you want is to modify the GenerateNameForExpression to have a lot more smarts.

**Comment by giggio** [comment]
Cool. Can I start working on it, then?

**Comment by jmarolf** [comment]
feel free to start working on it.

**Comment by rchande** [comment]
You're free to start working on it. Thanks!

**Comment by balajikris** [comment]
>> "Is this for C# only?"

The issue will likely repro for both C# and VB. the fix however, could be in a common file that could fix both languages.. It'll be useful to add unit tests for both languages (IntrdouceVariableTests.cs, IntrdouceVariableTests.vb) to make sure they're both addressed.. :smiley:

**Comment by sievajetnamdar** [comment]
I managed to add this feature with the corresponding unit tests. Can I commit this to the master branch so that someone can review this? How does this work?

**Comment by CyrusNajmabadi** [comment]
@sievajetnamdar You should open a PR using the "new pull request" button on https://github.com/dotnet/roslyn/pulls

There, you can point at your own fork and branch and a PR will be created from that.  Give the PR a good title, ensure that the code in it is what you want, and submit the PR.  Then tag appropriate people (like @rchande  and me) to look at it.

We'll go through some cycles of reviews+changes on your part.  And when finally approved, it can be merged in by a team member.
