### ISSUE TITLE
Analyser IDE0130 fixer does not update namespaces correctly.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/roslyn#56002]
**Version Used**: 
SDK 5.0.400

**Steps to Reproduce**:

1) Create a class within a nested folder.
2) Rename the folder.
3) Hover over the class namespace to see the analyser fix suggestion.

**Expected Behavior**:
Fixer should replace the namespace with the path of the folder structure.

**Actual Behavior**:
Fixer replaces the current namespace segment with the entire new namespace.
Summary is correct, but the preview and execution of the fixer is not.

![image](https://user-images.githubusercontent.com/21192520/131266437-ea93d857-a993-421b-85a7-6ac5f26b424e.png)

**Comment by Youssef1313** [comment]
I believe @ryzngard has already fixed this in https://github.com/dotnet/roslyn/pull/55424.

**Comment by ryzngard** [comment]
Correct, this has been fixed
