### ISSUE TITLE
`Nullable<T> ?? constant-expr` generates unnecessary temporary

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/roslyn#56007]
**Steps to Reproduce:**

```csharp
int M(Nullable<int> num) => num ?? -1;
```

**Expected Behavior:**
The compiler produces IL equivalent to:
```csharp
public int M(Nullable<int> num)
{
    if (!num.HasValue)
    {
        return -1;
    }
    return num.GetValueOrDefault();
}
```

**Actual Behavior:**
The compiler produces IL equivalent to:
```csharp
public int M(Nullable<int> num)
{
    Nullable<int> num2 = num;
    if (!num2.HasValue)
    {
        return -1;
    }
    return num2.GetValueOrDefault();
}
```

**Suggested fix**

`num ?? constant-expr` could be lowered to `num.GetValueOrDefault(constant-expr)`, which resulted in improved codegen, see

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACMxgYUYG8bGfmmBLAHYZGAWQAUAOQCuAG1nZgsmAB4hGAHyNB0/AEpGAXi078jAPznGccgG5uvBo3WNJUuQqWr1J3QePaugB0AOIwGABq2LLSMADyUAAiMABm2HIY4jZ69tQAvkA=

**Comment by CyrusNajmabadi** [comment]
> num ?? RightOperand could be lowered to num.GetValueOrDefault(RightOperand)

I think this is only true if Right has no side effects. The suggested transformation will evaluate Right early instead of only if Left is null.

**Comment by xtqqczze** [comment]
> > num ?? RightOperand could be lowered to num.GetValueOrDefault(RightOperand)
> 
> I think this is only true if Right has no side effects. The suggested transformation will evaluate Right early instead of only if Left is null.

I believe you are right, however we can still do this transformation for `Nullable<T> ?? constant-expr`.

**Comment by xtqqczze** [comment]
> I think this is only true if Right has no side effects. 

And if a side effect of RightOperand is to modify `num` the temporary variable is clearly necessary. I've modifying the title and description to only expect the behaviour when RightOperand is a constant expression.

**Comment by xtqqczze** [comment]
Related to #53644.

**Comment by RikkiGibson** [comment]
Slightly similar to #52629
