### ISSUE TITLE
Can the Formatter annotate nodes that it doesn't touch

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#56014]
In fixing https://github.com/dotnet/aspnetcore/issues/34320 we had to make the Razor formatting engine aware of which types of nodes the formatter would not touch (object initializer, collection initializer, array initializer, etc.). Unfortunately doing this means hard-coding a list of formatter behaviours in a separate repo, and means walking up a syntax tree arbitrarily high in order to find the right type of parent.

If the formatter could add an annotation to the nodes that it ignores, and hopefully all child nodes too, then it would make this code much more reliable, and future proof Razor against formatter changes - either if these nodes do start to be formatter, or new nodes start to be ignored.

**Comment by CyrusNajmabadi** [comment]
this sounds expensive :)

**Comment by davidwengier** [comment]
I know literally nothing about the formatter, so if this isn't possible then feel free to close, this was just a random idea to avoid Razor having to maintain a list of nodes that are not formatted, and having to walk up the syntax tree to find if it's inside one of them.

**Comment by sharwell** [comment]
Annotations are prohibitively expensive, especially in large numbers. However (and perhaps more importantly), the formatter is allowed to touch anything it wants to. There is no observable difference between a node that the formatter never touches and a node that is left alone because it is already correct.
