### ISSUE TITLE
Use a BitVector instead of bool[] in MethodTypeInferrer.FixParameters

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#56012]
It may be worthwhile to try and measure the difference in allocations when this bool[] is changed to BitVector, noting that most of the time, there will be fewer than 64 method type parameters, and the BitVector would be entirely on the stack.

https://github.com/dotnet/roslyn/blob/62213239743be2deec6dd5c2bebe86957c3f53d3/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs#L821-L854

I think there are several places where allocated arrays could be replaced with stack-allocated structures or pooled objects of some kind. This could help with memory perf.

**Comment by Youssef1313** [comment]
@RikkiGibson Any specific reason for BitVector over `stackalloc`? I'm doing this in https://github.com/dotnet/roslyn/pull/69040

**Comment by RikkiGibson** [comment]
BitVector uses less space to store the flags.

**Comment by Youssef1313** [comment]
@RikkiGibson `BitVector.Create` appears to still be allocating an array on the heap? https://github.com/dotnet/roslyn/blob/2fb8ad0ce8c49872aa781072037cf921efa3a5fd/src/Compilers/Core/Portable/Collections/BitVector.cs#L165

Am I missing something?

**Comment by RikkiGibson** [comment]
From the original issue description

> most of the time, there will be fewer than 64 method type parameters, and the BitVector would be entirely on the stack.

e.g. the shared empty array would be used for the "subsequent words" of the BitVector.

**Comment by RikkiGibson** [comment]
`stackalloc bool[]` is probably also fine, though.

**Comment by Youssef1313** [comment]
Oh yes makes sense. I'll use BitVector then and mark my PR as fixes this issue.

**Comment by RikkiGibson** [comment]
Sounds good!
