### ISSUE TITLE
I can't use source generator with package reference

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/roslyn#56024]
My develop enviroment :

* VS 2022 preview 1.1
* Rider 2021.1.1
* .net 6 preview 6 sdk

my expect:
1. I create a source generator project
2. I upload the project as nuget package
3. I want to use the package as a .net analyzer

problem:
1. this package using PackageReference installed to project, but it doesn't work ( not generate any code)
2. using ProjectReference with this raw project , it work pretty good

so why i can't use a source generator as a normal nuget package, this issues i test with rider and vs 2022

**Comment by sharwell** [comment]
Can you include a copy of the NuGet package? It can either be attached to this issue where it will be publicly visible, or you can use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) feature in Visual Studio to submit the file private to Microsoft under the normal privacy policies.

**Comment by jasonmalinowski** [comment]
I'm going to close this since without further information this bug isn't actionable. @Luoyingliang if you are able to provide more information, we're happy to reopen the bug. Thanks!
