### ISSUE TITLE
Add test for LSP frozen semantics

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#56038]
https://github.com/dotnet/roslyn/pull/55976 adds frozen compilation support for LSP semantic tokens. A test wasn't included due to a lack of testing infrastructure (see https://github.com/dotnet/roslyn/pull/55976#issuecomment-908755504). We should add a test to make sure we're robust.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
