### ISSUE TITLE
Using Nullable in switch does not work as expected

### ISSUE THREAD

**Issue by rickardgranberg** [dotnet/roslyn#5604]
Given the following code:

<code>

    long? value = 1000;

      switch (value)
      {
        case 1000:
          Console.WriteLine("Switch: Value is 1000");
          break;
        default:
          Console.WriteLine("Switch: Value is not 1000");
          break;
      }
</code>

One would expect to get a printout of **Swich: Value is 1000**
This is true in VS 2013, but not in VS 2015 when compiled with roslyn. Instead you get **Switch: Value is not 1000**.

To further support the case, replacing the switch with if-else:

<code>

      if (value == 1000)
      {
        Console.WriteLine("If: Value is 1000");
      }
      else
      {
        Console.WriteLine("If: Value is not 1000");
      }
</code>
yields the expected result, i.e. the output is **If: Value is 1000**

If the new switch behavior is the desired one, the code above should at least result in a compiler warning.

**Comment by axel-habermaier** [comment]
Seems to have been fixed already (see #5025).

**Comment by rickardgranberg** [comment]
Indeed. I guess my search skills was not up to par :(

**Comment by rickardgranberg** [comment]
Actually, this is not the (exact) same problem as [#5025](https://github.com/dotnet/roslyn/issues/5025). The problem is with the implicit type conversion between long? and int.

If I change the declaration of value to be **int?**  like so:

<code>
int? value = 1000;
</code>

The switch works as expected. Also, if I change the **case 1000** like so:

<code>
case (long)1000:
</code>

This also works as expected (or at least as it did in VS 2013)

**Comment by gafter** [comment]
This issue has been fixed by recent changes.
