### ISSUE TITLE
Is CS0273 no longer reported?

### ISSUE THREAD

**Issue by Przemyslaw-W** [dotnet/roslyn#5606]
in VS2013 code like:
```
public int Property1 { get; public set; }
protected int Property2 { get; public set; }
internal int Property3 { get; public set; }
private int Property4 { get; public set; }
```
resulted in error CS0273: The accessibility modifier of the '' accessor must be more restrictive than the property or indexer ''

In VS2015 such code compiles successfully. Is this intentional?

**Comment by axel-habermaier** [comment]
Which version of Visual Studio are you using? I still get CS0273 when I try to compile your code with VS2015 RTM.

**Comment by Przemyslaw-W** [comment]
my bad. I did not notice that the file was accidentally removed from project. All is ok
