### ISSUE TITLE
VB "match closing parenthesis" fails for some constructs (works for others)

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#5607]
![matchclosingparenthesis](https://cloud.githubusercontent.com/assets/3316258/10220871/76d1e1e6-6818-11e5-86e8-cb7359d407af.gif)

Here's a minimal video repro. In all three lines I'm typing the closing parenthesis `)` rather than cursoring-right over it. Observe that "match closing parenthesis" feature works fine when I write the generic type, and when I write console.writeline, but it fails on list.RemoveAt.

I've noticed this failure a lot in my day-to-day coding. I haven't figured out which things work and which don't.

**Comment by balajikris** [comment]
@ljw1004 : I've fixed a class of bugs where typingover fails if the parenthesis occurs after a numeric literal. If you happen to see other cases, please let me know and/or file a bug. thanks.
