### ISSUE TITLE
Need a way to get stack traces from info bar exception notifications

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#5610]
While working, I randomly got this infobar about some fixer that crashed. There's nothing in the activity log (for reasons @dpoeschl explained to me). Can we add a Roslyn-specific log or get these errors back in the VS ActivityLog?

![infobar](https://cloud.githubusercontent.com/assets/3751401/10227314/74590a08-6821-11e5-839e-2c513b7e1833.png)

**Comment by Pilchie** [comment]
Dupe of #2697.
