### ISSUE TITLE
API proposal: `IsAccessibleWithin` symbol extension method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#56116]
## Background and Motivation

For my case, I'm writing a source generator that generates an override of an internal virtual property. I need to know whether the property is accessible for a given type to decide whether to generate code or not.

This is already implemented, but it's internal:

https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions_Accessibility.cs

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
     public static class ISymbolExtensions
     {
+        public static bool IsAccessibleWithin(this ISymbol symbol, ISymbol within);
     }
}
```

## Usage Examples

```csharp
if (propertyToOverride.IsAccessibleWithin(type))
{
    context.AddSource(...);
}
```

**Comment by CyrusNajmabadi** [comment]
I'm not hugely comfortable exposing this as it's effectively a huge hack where we just copy/pasted the C# logic into a shared place.  I would not want to then have to maintain that hack.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Wouldn't the compiler be able to implement that API more reliably? That way we can even get rid of the hacky approach in the workspaces layer. I'm not sure.

I'm certainly against providing such an API if the implementation is going to be hacky or not much reliable.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Wouldn't the compiler be able to implement that API more reliably?

I believe Neal tried this, but it was rejected by compiler team as not having semantics that matched either language.

**Comment by CyrusNajmabadi** [comment]
Note: compiler already has:  Compilation.IsSymbolAccessibleWithin.  The purpose of hte IDE helper is to do that check when the symbols might *cross* languages.

**Comment by Youssef1313** [comment]
My case doesn't really involve cross languages. It's only C#. Should we close then?

**Comment by CyrusNajmabadi** [comment]
Yes.  In that case, the API already exists on Compilation  :)
