### ISSUE TITLE
Allow `EmitCompilerGeneratedFiles` to specify specific generators

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#56113]
In a case where a project has couple of generators, I'm only interested in persisting a specific generator to disk. The current design doesn't seem to allow that?

## Proposal

Add a new MSBuild property, for example `GeneratorFullyQualifiedNamesToPersist`.
If the property value isn't set, keep the current behavior. Otherwise, treat the property value as a list of generators fully qualified names separated by a semicolon, e.g: 

```xml
<GeneratorFullyQualifiedNamesToPersist>MyApp.Generators.MyAwesomeGenerator1;MyApp.Generators.MyAwesomeGenerator4</GeneratorFullyQualifiedNamesToPersist>
```

**Comment by Youssef1313** [comment]
cc @chsienki

**Comment by sharwell** [comment]
💡 I worked around this issue in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3343 by adding one of the source generator output locations to **.gitignore**.

**Comment by Youssef1313** [comment]
Nice! I haven't really thought about it. But unfortunately it might not work well for my case. I'm in a case where the compilation fails if the generated files of a specific generator are persisted (errors say duplicate definition of things that are generated). I'm not yet able to determine the root cause of that (it's likely to be some issue in the codebase rather than a compiler issue). But the workaround is still very helpful if I encountered that in another situation or I could fix the duplicate definition issue.

**Comment by Youssef1313** [comment]
The request here is to select specific *generators* that will emit files to disk. Another request (https://stackoverflow.com/questions/71821116) was to select specific *files* to be emitted to disk.

**Comment by jaredpar** [comment]
Closing as I don't think the granularity here is worth the extra complexity to our build process. I do understand the value in making sure clients can determine which files came from which generators (which I believe we've achieved). But I don't think we need the extra complexity of only emitting certain files to disk here.
