### ISSUE TITLE
Unable to build C# compiler in VS 2022. The process cannot access the file CSharpSyntaxGenerator.dll because it is being used by ServiceHub.RoslynCodeAnalysisService.exe

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#56125]
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 4.0 [31701.447.main]

Build started...
1>------ Build started: Project: CSharpSyntaxGenerator, Configuration: Debug Any CPU ------
2>------ Build started: Project: Microsoft.CodeAnalysis, Configuration: Debug Any CPU ------
1>CSharpSyntaxGenerator -> D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netcoreapp3.1\CSharpSyntaxGenerator.dll
2>Microsoft.CodeAnalysis -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis\Debug\netcoreapp3.1\Microsoft.CodeAnalysis.dll
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
2>Microsoft.CodeAnalysis -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis\Debug\netstandard2.0\Microsoft.CodeAnalysis.dll
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): warning MSB3026: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): error MSB3027: Could not copy "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". Exceeded retry count of 10. Failed. The file is locked by: "Microsoft Visual Studio 2022 Preview (14012), ServiceHub.RoslynCodeAnalysisService.exe (11728)"
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4646,5): error MSB3021: Unable to copy file "D:\GitHub\roslyn\artifacts\obj\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll" to "D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll". The process cannot access the file 'D:\GitHub\roslyn\artifacts\bin\CSharpSyntaxGenerator\Debug\netstandard2.0\CSharpSyntaxGenerator.dll' because it is being used by another process.
1>Done building project "CSharpSyntaxGenerator.csproj" -- FAILED.
3>------ Build started: Project: Microsoft.CodeAnalysis.CSharp, Configuration: Debug Any CPU ------
3>C:\Users\.nuget\packages\microsoft.dotnet.xlifftasks\1.0.0-beta.21412.1\build\Microsoft.DotNet.XliffTasks.targets(91,5): error : The document '../CSharpResources.resx' has a duplicate node 'ERR_CheckedOverflow'.
3>Done building project "Microsoft.CodeAnalysis.CSharp.csproj" -- FAILED.
========== Build: 1 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by jasonmalinowski** [comment]
This was fixed by https://github.com/dotnet/roslyn/pull/56027.
