### ISSUE TITLE
Navigation is broken in "Find References" result window

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#56123]
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 4.0 [31701.447.main]

Clicking or moving between lines in the result doesn't navigate to the corresponding location in source.

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/dotnet/roslyn/pull/55979
