### ISSUE TITLE
Use current Microsoft.*.Core.targets file during bootstrap on CI build

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#5615]
In https://github.com/dotnet/roslyn/pull/5509, I made a change to the Microsoft.VisualBasic.Core.targets file that was incorrect.  My local tests, and the CI build tests did not catch this mistake until it got to the perf-tests team, where it started failing. https://github.com/dotnet/roslyn/pull/5614

It should be possible to use these target files during the bootstrap on the CI servers.

**Comment by TyOverby** [comment]
Apparently Github only lets one person be assigned to an issue, so I'll take point on this; but @pharring and @tannergooding said that @agocke was knowledgeable about this area, so I'll work with him when he comes back.

**Comment by davkean** [comment]
I'm going to move this to the compiler team as bootstapping is owned by them.

**Comment by TyOverby** [comment]
I'm not sure that modifying the deployed version of roslyn is a good idea anymore.  Does anyone @dotnet/roslyn-compiler want to sanity check this?

**Comment by jaredpar** [comment]
I think we actually do this already.  The bootstrap phase of cibuild.cmd copies the targets files into the bootstrap directory so it's picked up during build.  Pretty sure we can close this out.

**Comment by TyOverby** [comment]
Awesome.  Where would I check to make sure?

**Comment by TyOverby** [comment]
@jaredpar Ping.  I'd like to close this if possible.  I looked in cibuild.cmd and couldn't find anything that *explicitly* copies the targets files, but it could be doing that as a part of another step.

**Comment by davkean** [comment]
This is what is copying the targets: https://github.com/dotnet/roslyn/blob/master/cibuild.cmd#L49.

**Comment by jaredpar** [comment]
@davkean is correct.  It's getting implicitly copied as a part of this.  The build puts the targets files into `Binaries\Debug` and that command copies them to the bootstrap folder.  

My worry though is we don't have any validation this is happening and right now it's more or less happening by accident.  Should we add a check to ensure targets files are copied in cibuild.cmd?

**Comment by TyOverby** [comment]
Could I add a part that *explicitly* copies the targets files and will fail the script if that wasn't able to?

**Comment by davkean** [comment]
Just put an exists there and fail the build if it fails.

**Comment by TyOverby** [comment]
@davkean Sounds good
