### ISSUE TITLE
Unable to use RoslynCodeTaskFactory in MAC

### ISSUE THREAD

**Issue by ayankumaar** [dotnet/roslyn#56164]
I am using RoslynCodeTaskFactory in a .targets file to copy a folder in the user's system as a BeforeBuild action. It is working fine in Windows systems. However, in MAC I am getting the following error:

**error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "/Users/XXXX/.nuget/packages/roslyncodetaskfactory/2.0.7/build/netstandard2.0/RoslynCodeTaskFactory.dll". The task factory must return a value for the "TaskType" property.**

Can you please tell me why am I getting this ? I have done some research on this but haven't found much on it. Do I need to do anything specific to MAC to get rid of this error ?

**Comment by svick** [comment]
As far as I can tell, you're using [RoslynCodeTaskFactory from this repo](https://github.com/jeffkl/RoslynCodeTaskFactory), which says:

> As of **MSBuild 15.8**, [RoslynCodeTaskFactory](https://github.com/Microsoft/msbuild/blob/master/src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs) is now built in.  For more information, please read
[the official documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory).

Can you try switching to that version of RoslynCodeTaskFactory and see if that helps?

**Comment by sharwell** [comment]
The package in question is not maintained by this team. Issues for RoslynCodeTaskFactory can be filed at [jeffkl/RoslynCodeTaskFactory](https://github.com/jeffkl/RoslynCodeTaskFactory).
