### ISSUE TITLE
"Pull Members Up" does not correctly qualify additional generic type parameters from derived class

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#56174]
**Steps to Reproduce**:
1. Create a derived/base inheritance relation where the derived class has an additional type parameter compared to the base type:
```
public class Base
{
}

public class Derived<T> : Base
{
    public T TestMethod(T item)
    {
        return item;
    }
}
```
2. Pull `TestMethod` up to "Base"

**Actual Behavior**:
`T` is unqualified in the base type:
```
public class Base
{
    public T TestMethod(T item)     // "T" is not defined
    {
        return item;
    }
}

public class Derived<T> : Base
{
}
```
**Expected Behavior**:
Pulling `TestMethod` up should either:
1. Add `Derived`'s type parameters to `Base`, maybe just appending them
2. Make the method itself generic, such as `public T TestMethod<T>(T item)` 
    - This may not work for things such as generic properties/fields.

In a related problem, pulling members up doesn't re-qualify type arguments that may go by different names in the Base vs. Derived type, such as:
```
public class Base<T1>
{
}

public class Derived<T2> : Base<T2>
{
    public T2 TestMethod(T2 item)
    {
        return item;
    }
}
```
This would refactor without re-qualifying `T2` to `T1`, even though they are equivalent. There are also cases to think about with possible conflicts between the naming of type parameters, for example `Base<T1>` and `Derived<T1, T2> : Base<T2>`, where we may need to find a new name for the type parameters being moved.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
