### ISSUE TITLE
Non-conflicting extension method suppresses Add Using quick fix

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#562]
Source:

```C#
using System.Linq;

class C {
	int i = 0.All();
}
namespace X {
	static class E {
		public static int All(this int o) => 0;
	}
}
```

No quick fix is offered to add `using X;`.

Removing the existing `using` directive will make the quick fix appear.

**Comment by jmarolf** [comment]
@shyamnamboodiripad could you verify this please?
