### ISSUE TITLE
Consider addressing possible conflicts introduced by 'replace method with property'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5620]
From https://github.com/dotnet/roslyn/pull/5303

``` c#
using System;

class C
{
    string GetInt32()
    {
        return "42";
    }

    void M()
    {
        var x = GetInt32();
        var s = Int32.Parse(x);
    }
}
```

Replace 'GetInt32' method with an 'Int32' property will result in code changing meaning.  It may be worthwhile to invest in extracting out the 'conflict resolution' part of 'rename' into some sort of reusable API for these other refactorings.

**Comment by Pilchie** [comment]
I think @dpoeschl wanted to do that for Change Signature too.

**Comment by dpoeschl** [comment]
Yep, making this general enough that anything can consume it (including codefixes/refactorings via some API addition that allows them to specify nodes-of-interest where we could check the binding and expand/reduce for them as necessary) would be awesome.

**Comment by CyrusNajmabadi** [comment]
Have not heard from any customers that this has ever impacted them.  Closing out this speculative concern.
