### ISSUE TITLE
Partial simple program doesn't apply any attributes on `Main` method

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#56217]
**Version Used**: 

main branch

**Steps to Reproduce**:

Type code

```csharp
using System;

// Simple program.
Console.WriteLine();

// Partial class 'Program' in a new file.
internal static partial class Program
{
    [P]
    static partial void Main();
}

// Test attribute.
class P : Attribute { }
```

**Expected Behavior**:

Attribute `[P]` will be marked onto the generated `Main` method.

```csharp
internal static class Program
{
    [P]
    private static void <Main>$(string[] args)
    {
        Console.WriteLine();
    }
}
internal class P : Attribute
{
}
```

**Actual Behavior**:

No attribute on method `Main`.

See [this link on Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAPWwE4AKASgG4CDYAXAUwCcYIAbAAmIDZOAHCM3pQO3TN2wB2AgG8CnRZwDaABQC6CpbwFCRY9ABZOAWWgxKNfAF9a+LJ1WcQnAIL16zKMACuTTrKc1kA)

```csharp
internal static class Program
{
    private static void <Main>$(string[] args)
    {
        Console.WriteLine();
    }
}
internal class P : Attribute
{
}
```

**Comment by Youssef1313** [comment]
This behavior looks expected to me. Your partial `Main` method is really a different method than `<Main>$`, ie, the following is currently allowed (with a warning that can be suppressed):

```csharp
using System;

Main();

internal static partial class Program
{
    [P]
#pragma warning disable CS7022
    static void Main() => Console.WriteLine("Hello, world");
#pragma warning disable CS7022
    
}

class P : Attribute { }
```

**Comment by SunnieShine** [comment]
> This behavior looks expected to me. Your partial `Main` method is really a different method than `<Main>$`, ie, the following is currently allowed (with a warning that can be suppressed):
> 
> ```cs
> using System;
> 
> Main();
> 
> internal static partial class Program
> {
>     [P]
> #pragma warning disable CS7022
>     static void Main() => Console.WriteLine("Hello, world");
> #pragma warning disable CS7022
>     
> }
> 
> class P : Attribute { }
> ```

@Youssef1313 AFAIK `Main` method is a `static` method so if we combine `static` and `partial`, the compiler will require us to provide a implementation (C# 9 partial method feature rule). Therefore, I use the simple program feature to implement, it **does** works and if I removed the part, the compiler will raise a compiler error, so... `static partial void Main` and `Console.WriteLine()` may be different parts in a same method.

**Comment by Youssef1313** [comment]
> if we combine static and partial, the compiler will require us to provide a implementation (C# 9 partial method feature rule).

I think it doesn't require an implementation, the following compiles just fine:

```csharp
using System;

Console.WriteLine();

internal static partial class Program
{
    static partial void Hello(); // No implementation is provided.
}
```

**Comment by SunnieShine** [comment]
> > if we combine static and partial, the compiler will require us to provide a implementation (C# 9 partial method feature rule).
> 
> I think it doesn't require an implementation, the following compiles just fine:
> 
> ```cs
> using System;
> 
> Console.WriteLine();
> 
> internal static partial class Program
> {
>     static partial void Hello(); // No implementation is provided.
> }
> ```

I found I was wrong when I re-read the proposal about the partial method :(

I closed this issue. Thank you.
