### ISSUE TITLE
When a C# compiler unit-test is executed after a compiler change in Roslyn solution, the test is executed against old compiler bits 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#56219]
Note, this is specifically happening when no changes are made in the unit-test project. The build is kicked in, but, I suspect, the updated bits aren't deployed.
If I make a change in the unit-test and run it again, the compiler changes are picked up. 

Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 5.0 [31706.66.main]

**Comment by Youssef1313** [comment]
Could be related to https://github.com/dotnet/project-system/issues/7505?

**Comment by AlekseyTs** [comment]
The same happens with VB unit-tests.
The build output for the first test run (changes only in compiler):
```
Build started...
1>------ Build started: Project: Microsoft.CodeAnalysis.VisualBasic, Configuration: Debug Any CPU ------
1>Microsoft.CodeAnalysis.VisualBasic -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis.VisualBasic\Debug\netstandard2.0\Microsoft.CodeAnalysis.VisualBasic.dll
1>Microsoft.CodeAnalysis.VisualBasic -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis.VisualBasic\Debug\netcoreapp3.1\Microsoft.CodeAnalysis.VisualBasic.dll
========== Build: 1 succeeded, 0 failed, 8 up-to-date, 0 skipped ==========
```

The build output for the second test run (changes only in unit-test):
```
Build started...
1>------ Build started: Project: Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests, Configuration: Debug Any CPU ------
1>Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests\Debug\net5.0\Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.dll
1>Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests -> D:\GitHub\roslyn\artifacts\bin\Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests\Debug\net472\Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests.dll
========== Build: 1 succeeded, 0 failed, 8 up-to-date, 0 skipped ==========
```

**Comment by jaredpar** [comment]
This is a known issue in recent VS2022 bits:

- Primary Issue https://github.com/dotnet/msbuild/issues/6713
- [Teams Discussion](https://teams.microsoft.com/l/message/19:d16b7953d6a7442abdc84e59de75825e@thread.skype/1630079862846?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1630079862846&teamName=.NET%20Developer%20Experience&channelName=General&createdTime=1630079862846)

You should be able to work around this by disabling fast build during unit tests

![image](https://user-images.githubusercontent.com/146967/132711745-277e0620-46e5-43ee-afad-99acc8cef065.png)
