### ISSUE TITLE
Add DateTimeProvider to Incremental Source Generator API

### ISSUE THREAD

**Issue by Marv51** [dotnet/roslyn#56212]
## Background and Motivation
We are using a source generator to generate a class that contains the build date for our app. This source generator is very simple, it just takes `DateTime.UtcNow` and outputs the result it in a C# class.

I converted this to the new incremental source generator (`IIncrementalGenerator`), however non of the implemented providers provide the current date. One of the other providers can be used, but the caching and incremental execution can not be used.

As additional motivation I have found this source generator a great way to learn about source generators, and I believe the current date would a great way to explain the benefit of incremental generators as the caching is very obvious.

## Proposed API

The new IncrementalGeneratorInitializationContext in 4.0 should contain a provider that provides ` DateTime.Now`

As a first idea, maybe this would be a way to go? I am really not familiar with the details here:

```diff
namespace Microsoft.CodeAnalysis
{
     public readonly struct IncrementalGeneratorInitializationContext
     {
+        public IncrementalValueProvider<DateTimeProvider> DateTimeProvider
     }

+  public class DateTimeProvider
+  {
+         public DateTime CurrentDateTime { get; }
+  }
}
```

## Usage Examples
``` C#
public void Initialize(IncrementalGeneratorInitializationContext context)
{
    var a = context.DateTimeProvider.Select((provider, cancel) => provider.CurrentDateTime.ToString("dd-MM-yyyy"));
    context.RegisterSourceOutput(a, (productionContext, currentDate) =>
    {
        productionContext.AddSource("CompileDate.g.cs", GenerateSource(currentDate));
    });
}
```

## Alternative Designs
The current date and time is probably not the only global state that would be useful in source generators. 

For example the system language might also be useful. 

## Risks

none? not clear to me

**Comment by jaredpar** [comment]
I do not see us providing such an API because it violates the basic premise that builds should be deterministic. Any use of `DateTime.UtcNow` either in the logic inside the generator or outputting the result into the generated code violates that basic principle. It means that two builds with all of the same inputs will have different outputs. Having the same inputs equal the same outputs is a core tenant of determinism.
