### ISSUE TITLE
The "Change namespace to match folder structure" refactoring duplicates the root namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56220]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Change-namespace-to-match-folder-st/1521949)._

---
[severity:It bothers me. A fix would be nice]
When using the "Change namespace to match folder structure" refactoring, the root namespace (name of the project or defined namespace in the .csproj) gets duplicated.

![image](https://user-images.githubusercontent.com/611219/132402777-b9f570af-598a-4c5c-9955-286eeb36c7f4.png)

![image](https://user-images.githubusercontent.com/611219/132402797-8d434a98-598d-4873-a440-419db3b03691.png)

Although the "Change namespace to NamespaceBugHunt.Things" refactoring works great, it cannot be applied to the entire project.

---
#### Feedback Bot on 9/6/2021, 02:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/7/2021, 00:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This was recently fixed by @ryzngard

**Comment by BMagerMT** [comment]
@Youssef1313 I assume preview 4 refers to visual studio 2022. Will this also be fixed in a release of 16.11?

**Comment by Youssef1313** [comment]
@BMagerMT Yes I'm referring to VS 2022.

@ryzngard Any chance to backport this? I think this really worth doing since we got multiple bug reports for it?

cc @jinujoseph @CyrusNajmabadi

**Comment by ryzngard** [comment]
The fixes for this will also be updated with new Nuget packages, so I'm not sure it meets the bar for backporting.

**Comment by CyrusNajmabadi** [comment]
This doesn't meet my bar for backporting.  It's a bug, but not that big a deal.

**Comment by Youssef1313** [comment]
> The fixes for this will also be updated with new Nuget packages

@ryzngard I thought the NuGet packages will be using Microsoft.CodeAnalysis 4.x which isn't compatible with VS 2019, anything I'm missing?

**Comment by ryzngard** [comment]
> > The fixes for this will also be updated with new Nuget packages
> 
> @ryzngard I thought the NuGet packages will be using Microsoft.CodeAnalysis 4.x which isn't compatible with VS 2019, anything I'm missing?

Oh you might be right. This happened after we swapped to 4.x.
