### ISSUE TITLE
File-scoped namespace puts semicolon on newline if a comment exists

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#56232]
**Version Used**: 
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 5.0 [31706.66.main]

**Steps to Reproduce**:

1. Create a console app with this content:
```
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyApp // Note: actual namespace depends on the project name.
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
2. Put cursor on namespace and observe the lightbulb
3. Click lightbulb and choose file-scope namespace option

**Expected Behavior**:
Moves to file-scoped namespace and puts semicolon after namespace line

**Actual Behavior**:
If a comment exists on the same line as the namespace, it puts semicolon on a newline

![semicolongwrapped](https://user-images.githubusercontent.com/4821/132423396-c04be47f-ef4d-4284-8ba6-fab3114ae759.gif)

**Comment by Youssef1313** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This was fixed at some point.  You get the right behavior now:

![image](https://user-images.githubusercontent.com/4564579/153311321-e28a5e54-3d34-451f-8743-4b5faa0ea6de.png)
