### ISSUE TITLE
VS 2022 preview 3.1: Xamarin intellisense hints not updated after code changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56247]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-preview-31:-Xamarin-intellisens/1512893)._

---
**In Xamarin projects** there are a number of issues with Intellisense. Some of them are due to the code hints not being updated after the code has changed.
In this case, are the ... hints not being updated properly after the code changes.

In the **image1** below you can see how there are ... underneath a var in the line 201.
If I delete the whole method the ... go to an empty line as it can be seen in the **image2**. Also you can see that the ... in the other methods underneath (also marked with a red arrow) are moved to the bottom, as the location has not been updated.

This is a way that I've found how to reproduce it consistently.
- In a **Xamarin** project
- Create 3 methods with variable definitions (as in image 1)
- Check that the ... are positioned in the right place
- Delete the first method, so the lines of the code change
- Check that ... are placed in the wrong locations.

![B27d4bfb2370d433589d9626bf808620f637654534294306975_20210825-115708-image](https://user-images.githubusercontent.com/9797472/142937975-725a86aa-8a39-4ca6-ae85-5cd2efe0838b.png)

![Be9aff6919f18471980e3c49a4d4e7d95637654537400218839_20210825-120218-image](https://user-images.githubusercontent.com/9797472/142938077-bb6848db-e3fb-4713-9e26-b51ec6c2d65d.png)

---
#### Feedback Bot on 8/25/2021, 01:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
It looks like a bug where our IDE diagnostics become stale after code change, not related to completion (nor needs design review)

**Comment by CyrusNajmabadi** [comment]
Closing as these components were rewritten and we haven't received any more resports.
