### ISSUE TITLE
[Proposal] Operator overloading on Interfaces

### ISSUE THREAD

**Issue by stefc** [dotnet/roslyn#5624]
I really want to see that I can use operator overloading also on Interfaces. 

For example I've an interface IVector<T> that have for example the immutable Add method : 

<code>IVector<T> Add(IVector<T> operand);</code>

instead of 
<code>IVector<double> x = a.Add(b); </code>

I want to write 
<code>IVector<double> x = a + b; </code>

I don't see any reason why operator overloading is restricted to work only on normal classes.

**Comment by AlgorithmsAreCool** [comment]
How would we define this operator? Typically they are in static methods in a class. Would you propose to allow static methods on interface definitions?

**Comment by stefc** [comment]
I think operator overloading can be defined the same as extension methods, somewhere in a static class besides the interface declaration.

**Comment by AlgorithmsAreCool** [comment]
Would this change also allow operator definitions for all types from extension methods?

**Comment by AlgorithmsAreCool** [comment]
See also related discussion 

Static interface members
https://roslyn.codeplex.com/discussions/541436

Possibility to provide operators in interface
https://roslyn.codeplex.com/discussions/570704

**Comment by daveaglick** [comment]
FYI, there's also related discussion (particularly of static extensions and static interfaces) at #996 and #2204. #112 also looks related, though it's about extension properties and not operators.

**Comment by stefc** [comment]
I don't see the operator overloading in the context of a static method inside the interface but that the operator overloading can resides somewhere not neccessary in the class/interface itself. 
For the sideeffect with an existing operator overloading exsist on the class the compiler should be inform with a warning on that and the developer should be aware of this amigous usage. In my case I use either the interface operators or the class operator, if would define both it would be bad design I think. I see the interface as abstraction of the internals of a class.

**Comment by orthoxerox** [comment]
@stefc Interfaces as they exist are very, very OOP-ish in their design, defining only virtual methods. Operators, on the other hand, were designed to be non-virtual, probably because C# is a single dispatch language, and it would be confusing to dispatch only on the runtime type of one of the operands.

I'd rather see operators implemented in templates/traits/"enhanced named generic constraints" than try and shoehorn them into interfaces.

**Comment by ashmind** [comment]
I think this should be done through extension operators -- so it should be covered by #5165 / #4945.

**Comment by aluanhaddad** [comment]
@ashmind agreed. #5165 is promising.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #516](https://github.com/dotnet/csharplang/issues/516) via [**ZenHub**](https://www.zenhub.com/)
