### ISSUE TITLE
C# completion: Completion fails for locals if followed by local function

### ISSUE THREAD

**Issue by MaStr11** [dotnet/roslyn#56245]
**Version Used**: 
Recent main ( bf962c9f)
**Steps to Reproduce**:

Trigger completion here:
```CS
using System.Threading.Tasks;

static class Program
{
    static async Task Main()
    {
        var local = Task.CompletedTask;
        local.a$$

        Task LocalFunction() => Task.CompletedTask;
    }
}
```
**Expected Behavior**:
Completion list contains members of `Task`

**Actual Behavior**:
Completion list is empty

**Background**:
Found during work on #55817. A test is in place for the await completion provider, but the bug is present for the symbolrecommender too. The test contains some more insights in the comments:

https://github.com/dotnet/roslyn/blob/ca6b9ec3b02e74c131b4c06a6cc36954ed05276b/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AwaitCompletionProviderTests.cs#L539-L561

In the screencast, you can see that `Task.CompletedTask` is changing its color when `a` is typed, which indicates binding problems.

![By9JcUUgV0](https://user-images.githubusercontent.com/24472128/132497392-73d778f3-1736-4c17-b2d9-3801e04d7873.gif)

This only happens if the name of the return type of the local function is the same as the one used in the local declarator. The following screencast, with a different return type, does not face the problem:

![MoCQZQW9eY](https://user-images.githubusercontent.com/24472128/132497791-05a74103-67e9-46a6-b335-3faf57a12b8c.gif)

The cause is that speculative binding fails here:
https://github.com/dotnet/roslyn/blob/4f8eaef1ce57f39088f1bc6af1c3ac301375cb7f/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs#L314

**Comment by CyrusNajmabadi** [comment]
Does not repro for me:

![Image](https://github.com/user-attachments/assets/6197fc2e-536a-419f-890a-dd1cf6cb6f03)
