### ISSUE TITLE
BUG Visual Studio and String Interpolation in Visual Basic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56248]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BUG-Visual-Studio-and-String-Interpolati/1521900)._

---
Visual Studio 2022 Version 17.0.0 Preview 3.1
This problem (bug) also applicable to Visual Studio 2019 (I detect it on Visual Studio 2017).

When you use interpolated strings in Visual Basic Intellisense fails if you try to write something in the next line.
In C# works as expected.

I have an asignament using interpolated strings, like this:
```
sDistribuidor = $"AND Agente = '{distribuidor}' "
```
If I press the ENTER key after the end of that line and write something, Intellisense doesn't show.
I need to press the ENTER key again (and left a blank line) to Intellisense works.

If I write this:
```
sDistribuidor = $"AND Agente = '{distribuidor}' "
s
```
There are NO intellisense on the "s".

But if I write this: (note the blank line after the asign to sDistribuidor.
```
sDistribuidor = $"AND Agente = '{distribuidor}' "

s
```
Intellisense works when I type the "s".

Attached a recording of the BUG.

Hope it's clear now.

Thank you.
Guillermo

---
#### Feedback Bot on 9/6/2021, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidbuckleyni** [comment]
Still an issue in last update


![image](https://user-images.githubusercontent.com/5619229/135700251-8be7f045-19d2-462a-a22c-2a8755ec0e7f.png)

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be making changes to these experiences.
