### ISSUE TITLE
[Proposal] keyword for recursive call

### ISSUE THREAD

**Issue by stefc** [dotnet/roslyn#5625]
I love to write code with functional paradigma. For that case I often use recursive function calls. 

It common that if I have a function name for example "abc" that somewhere I also call abc from inside the method. Instead of reenter the method call I would like to use some keyword that here I make a recursive call to myself. 

<code>
void Action(int i) {
   if (i == 0) { return; }

  ...

  recur (i - 1); 

} 
</code>

I first see such keyword in Clojure and I find it very expressive in the source code, with Syntax Highlighting you directly see, where the recursive call is done. With only the identifier you must look twice to your source code. Especially recursive code should be as easy to read as possible in my opinion.

**Comment by svick** [comment]
I don't think a new keyword would be appropriate just to highlight a certain pattern. But detecting recursion (and maybe also other patterns?) and highlighting it differently might.

But it might be enough to use the tools that already exist:

* If you click on the method name in VS2015, it highlights all places where it is called, including recursive calls:

 ![](http://imgur.com/JzV0QnE.png)

* If you're using ReSharper, it will even mark recursive calls with an icon:

 ![](http://imgur.com/6mz9bnr.png)

**Comment by orthoxerox** [comment]
@svick what about anonymous recursive functions? Yes, I know what an Y combinator is, but it is impractical.

@stefc the more important use case for an explicit recursive call would be tail call optimization, covered in #1235

**Comment by svick** [comment]
@orthoxerox I don't see much need for that, especially since the new local functions can be recursive.

**Comment by dsaf** [comment]
@svick I don't think ReSharper can detect mutually recursive calls though.

F# did go the explicit keyword way (for different reasons) - which covers more cases:

https://msdn.microsoft.com/en-us/library/dd233232.aspx

**Comment by aluanhaddad** [comment]
A new syntax for recursive calls is not needed. With well named functions, I think it is clearer to see the name than it would be to see a keyword such as ```recur```.

As others have said I think that recursion aware tooling is a good idea.

**Comment by gafter** [comment]
The only reason I can see changing the language would be to instruct the compilers that a particular call is required to be properly tail-recursive.
