### ISSUE TITLE
Incorrect 'is not null there' hint

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56259]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Incorrect-is-not-null-there-hint/1336533)._

---
[severity:It's more difficult to complete my work]
It seems like the hint isn't aware that multiple calls of a getter might yield different results.

![Ba589f4cf10974c14a27970f92198b0fc637485693829204607_20210210-165622-image](https://user-images.githubusercontent.com/9797472/132584201-33c7e9de-c970-4ae4-8601-f2efbdec118a.png)

Of course, my example is just the simplest explanation of why it is wrong. But why I decided to submit it, is a common use case of Selenium with PageObjects. Like:
```csharp
public IWebElement? LoginButton => this.elementFinder.FindById("loginButton");
```
I think it's a pretty common case to have computed properties like that one. And the analysis incorrectly assumes it won't be null on second `get` if it wasn't null on the first `get`.

I'm not sure if I should submit it as a Visual Studio issue or C# lang or analyzer issue. Please tell me if I should move it elsewhere.

---
#### Feedback Bot on 2/10/2021, 05:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/12/2021, 09:39 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
The analysis assumes that properties are idempotent. We don't currently have an attribute to indicate that a property is "untracked" (i.e. each access uses the declared type to determine flow state rather than tracking a flow state across tests and subsequent accesses of the property).

**Comment by mitoihs** [comment]
Won't it be better to disable those hints then? For me, an incorrect hint is far worse than no hint.

**Comment by Youssef1313** [comment]
Probably something in the IDE side that says `(assuming property is idempotent)` (this extra working should only appear for properties, and possibly only not auto implemented ones)?

*Fix for the IDE side will be around this:*

https://github.com/dotnet/roslyn/blob/0561357bee68c42c592f00d996d3e0f230be8218/src/Features/Core/Portable/QuickInfo/QuickInfoUtilities.cs#L134
