### ISSUE TITLE
Add new item class file formats file-scoped namespace incorrectly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56279]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-new-item-class-file-formats-file-sco/1520074)._

---
[severity:It bothers me. A fix would be nice]
When creating a new class/file, the file formatting is a bit off. It creates the class using the new C# 10 file-scoped namespaces which is nice. The problem is a blank line is inserted at the top and the namespace declaration and class declaration are right next to each other.

Attached is the ASP.NET Web API project that exhibits the issue. I tested this on a new Console application, but it uses the old block style namespaces so the problem does not happen.

---
#### Feedback Bot on 02/09/2021, 07:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 09/09/2021, 02:34 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
This doesn't repro in main, so should be fixed in the next preview.

![NewFileFormatting](https://user-images.githubusercontent.com/754264/132634859-64c15fb2-aaae-4aca-b40f-aca58928cc1c.gif)
