### ISSUE TITLE
Missing definite assignment error for complex "is" checks

### ISSUE THREAD

**Issue by sbomer** [dotnet/roslyn#56298]
**Version Used**: 
9525fa5

**Steps to Reproduce**:
```csharp
using System;
int? c = 4, d = null;
// changing != to || gives an error
if ((c is int ci) != (d is int di))
    Console.WriteLine(di.ToString());
```
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAULAgPwAEAxrQLy0AsctGztMqANnwDcFAPQiGACwgwA5rBm0AhCwQB7Wrly05ANwCmAZ1rTae5MlXIKUAGa0AFPcZQjVBlACUSlva4vabhieHhS0YbT4xACcvlAAdAAqqgDKCMjy9h4egkA===

**Expected Behavior**:
Compiler error about use of uninitialized variable `di`.

Forgive me if this isn't a bug - I'm not familiar with the rules for definite assignment, but at least this behaved differently than I would have expected.

**Actual Behavior**:
No warning/error, and at runtime this prints `0` even though the int was never initialized to that value.

**Comment by RikkiGibson** [comment]
Not sure what's going on here. I expected that `int ci` for example is only assigned when `c is int ci` is true. Using the "Default" compiler in sharp lab gives the expected error. This is likely a regression related to the improved definite assignment feature.
