### ISSUE TITLE
Investigate allocation-free iteration of Symbol.Locations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#56306]
Currently `Symbol.Locations` returns an `ImmutableArray<Location>` for both C# and Visual Basic. Accessing this property frequently requires allocating a new array, which is known to incur substantial memory overhead for some cases (e.g. [AB#1389013](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1389013)). This property could be rewritten using patterns similar to `IOperation.ChildOperations` to avoid array allocations for scenarios where the `ImmutableArray<Location>` is not needed.

**Comment by CyrusNajmabadi** [comment]
If this is still an issue, we should just do this.  If we don't have current traces showing this to be a problem, we don't need this tracking it.
