### ISSUE TITLE
Investigate use of MemoryMappedInfo after disposal

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#56305]
https://github.com/dotnet/roslyn/issues/56195 indicates that `MemoryMappedInfo.Dispose` is being called concurrently with `MemoryMappedInfo.CreateReadableStream` and/or `CreateWritableStream`. While this will no longer throw `AccessViolationException`, it remains a usage problem that needs to be fixed.

One option is updating the storage location(s) of `MemoryMappedInfo` to themselves be wrapped in `ReferenceCountedDisposable<T>`.

**Comment by jinujoseph** [comment]
should be fixed #56764
