### ISSUE TITLE
IDE0060 (unused param) with NotImplementedException

### ISSUE THREAD

**Issue by LWChris** [dotnet/roslyn#56317]
This has been requested earlier as #41236.

I'm not sure but it looks like

* this should've been solved with PR #42408
* that PR should've been shipped with [16.6.P2](https://github.com/dotnet/roslyn/milestone/65)

I have 16.11.2, but still see this issue.

So either this is broken again, it never worked, or there's a side-case where the fix doesn't work.

My project has `net5.0-windows10.0.17763` as target framework.

**Comment by CyrusNajmabadi** [comment]
@LWChris can you supply a repro project?  Pointing to a git repo at a particular commit would be helpful.

**Comment by LWChris** [comment]
@CyrusNajmabadi Sure, but this is literally just an empty project with one method in it:

https://github.com/LWChris/IDE0060_NET5/tree/762dd94f3a02ae25120a8a956b621fd01432eb51

I found that the error toggles in and out of existence.

Sometimes, the error disappears, but cutting and pasting the method makes it re-appear. Sometimes it disappears if you change something unrelated (e. g. add, rename or delete a completely unrelated class), or if you add a second method, that one does not have the message.

Seems like the surpression doesn't work reliably. VS is 16.11.3 now.

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani

**Comment by mavasani** [comment]
Based on the last comment, it seems likely to be an issue with the solution crawler or error list, rather then the analyzer itself. I'll take a look.
