### ISSUE TITLE
Test plan for "using aliases for any types"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#56323]
Championed proposal: https://github.com/dotnet/csharplang/issues/4284
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/using-alias-types.md

Note this doesn't include support for generic aliases (draft spec https://github.com/dotnet/csharplang/pull/4452)

## Compiler
- [x] LangVer (tests with `RegularNext` or `CSharpNext`)
- [x] spec: https://github.com/dotnet/csharplang/blob/main/proposals/using-alias-types.md
  - [x] Consider documenting rule that unsafe aliases are also checked at usage point
- [x] LDM: `using unsafe` or `unsafe using`? LDM decision 2/1/2023.  `using unsafe`.  This keeps all the `using` forms consistent that they start with `using` (or `global using`). 
- [x] Various types:
  - [x] tuples (need positive test)
  - [x] built-in types: `int`, `nint`, ...
  - [x] array types
  - [x] pointer and function pointer
  - [x] ref type (`StaticUsingDirectiveRefType`)
  - [x] dynamic
  - [x] nullable reference types (disallowed: `using X = object?;`, `using X = Y?;` where `Y` is another alias) (`AliasUsingNullableReferenceType`)
- [x] unsafe requires proper compilation flag
- [x] using `unsafe` in a non-alias using (see `UsingUnsafeNonAlias`)
- [x] global alias (with and without `unsafe`) (see `GlobalAliasToType...`)
- [x] duplicate alias (ERR_DuplicateAlias)
- [x] semantic model: `GetTypeInfo` on the RHS, `IAliasSymbol.Target`, `GetAliasInfo`
- [x] SyntaxNormalizer (`using unsafe x = ...`, `using x = (one, two);`, ...)
- [x] Obsolete: `using X = (ObsoleteType, ObsoleteType);`, `using X = ObsoleteType[];`
- [x] EnC: Yes.  Needs tests.  See TopLevelEditingTests.Using_Global_Insert
- [x] `using T = dynamic;` where a `dynamic` type already exists. AliasUsingDirectiveDynamic4 and AliasUsingDirectiveDynamic4.
- [x] `using unsafe X = int;` then use `X` in safe context (no diagnostic).  TestUnsafeAlias14_A, TestUnsafeAlias14_B
- [x] `using X = scoped R;`. TestScopedType1-4
- [x] `using X = ref readonly R;` AliasUsingDirectiveRefReadonlyType
- [x] `using X = __makeref(...);`. TestMakeRef
- [x] `using X = __arglist();`. TestArgList
- [x] review public API changes.  Done: https://github.com/dotnet/roslyn/issues/66913
- [x] inspect the syntactic pointer type detection logic in compiler (is there a circularity issue?). Have made the change to no longer do things syntactically.  Added tests to ensure no issue (TestStructWithReferenceToItselfThroughAliasPointer1/2).  But need eyes on this.
- [x] debugger support (`using X = dynamic;` inspect a value of type `X`).  Added in https://github.com/dotnet/roslyn/pull/67105
- [x] add an EE test.  Added in https://github.com/dotnet/roslyn/pull/67105.
- [x] LDM: should we allow `unsafe` on `using static`? (`using static C<int*[]>;` is already legal, warning wave?)

## Productivity
- [x] Completion
- [x] Completion on `dynamic`
- [x] Classification
- [x] QuickInfo
- [x] Formatting
- [ ] Rename tracking

**Comment by tmat** [comment]
Note this will need a design and updated spec of custom debug information for PDBs - at least for Portable PDBs. We can decide to not make this available in EEs when Windows PDBs are used. If we support Windows PDBs the CDIs need to be designed for Windows PDBs as well. The format for Windows PDBs is different than Portable.

**Comment by jcouv** [comment]
Checked the test plan and it can be marked as completed now. Any further issues should be tracked by individual issues. Thanks

**Comment by CyrusNajmabadi** [comment]
Thanks julien :)
