### ISSUE TITLE
Anaylzers constantly showing in warning state

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56345]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Anaylzers-constantly-showing-in-warning-/1396870)._

---
I'd like to submit a ticket regarding code analysis.
It's a wonderful feature when it works but the stability of it is very questionable.
More often than naught, when I open my solution, all the analyzers attempt to pull from a local path that VS complains about despite numerous efforts to pull the same analyzer from NuGet.
For a team where their definition of done states "all errors, warnings and information" messages are cleared from the code before checking in, these errors make that exceedlingly difficult.
We almost always have "null reference error" on a warning we cannot clear or resolve.
I think it would be great, even in an errored state, if we could right click on the 'local' analyzer and choose 'find nuget package' so the redudant activity of trying to find all these packages is reduced.

---
#### Feedback Bot on 2/13/2020, 00:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/19/2020, 07:32 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/31/2020, 11:50 PM: 

Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq. In case you need answers to common questions or need assisted support, be sure to use https://visualstudio.microsoft.com/vs/support/. We'll keep you posted on any updates to this feedback.

#### Feedback Bot on 4/14/2021, 00:32 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mavasani** [comment]
We would need more info here, potentially a repro to figure this out.

**Comment by jinujoseph** [comment]
Closing this as corresponding DC ticket has been reopened
