### ISSUE TITLE
Quick Actions on non-CLS-compliant classes, methods or properties should suggest setting [CLSCompliant(false)]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56343]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Actions-on-non-CLS-compliant-class/1466823)._

---
I've recently encountered Warning `BC40026`: "Type is not CLS-compliant because it derives from base type that is not CLS-compliant" as well as `BC40028`: "Type of parameter is not CLS-compliant". There isn't much I could do about it, since those mentiond base class and type are from a Microsoft dll. So, naturally, I went to Quick-Actions on offending code to fix the warnings. But the only option I had was to suppress the warning.

I'm pretty sure the actually clean way to deal with those warnings is to set `CLSCompliant(false)`-Attribute.

---
#### Feedback Bot on 7/4/2021, 07:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
