### ISSUE TITLE
Custom equality operator in generic expressions provoke BadImageFormatExceptions

### ISSUE THREAD

**Issue by danielcweber** [dotnet/roslyn#56376]
### Description

The following minimal repro (available [here](https://github.com/danielcweber/BadImageFormatExceptionRepro) as well) will throw a `BadImageFormatException` and it's unclear what the unsupported expression is, why it's unsupported, and how it can be avoided, which is why I consider it a bug:

```
using System;
using System.Linq.Expressions;

namespace BadImageFormatExceptionRepro
{
    class Program
    {
        private readonly struct Wrapper<T>
        {
            public static bool operator ==(T t, Wrapper<T> wrapper) => true;

            public static bool operator !=(T t, Wrapper<T> wrapper) => false;
        }

        private interface IInterface<T>
        {
            void InterfaceMethod(Expression<Func<T, bool>> expression);
        }

        static void Main()
        {
            GenericMethod<string>();
        }

        private static void GenericMethod<T>() where T : class
        {
            Action<IInterface<T>, Wrapper<T>> func = (iface, wrapper) => iface
                .InterfaceMethod(x => x == wrapper);

            func(default, default);
        }
    }
}
```

Expected behaviour: The delegate `func` being run (which would throw a NRE in the process, but this is secondary here). 

Actual behaviour: The delegate isn't run, at least the breakpoint isn't hit. Instead, a `BadImageFormatException` is thrown.

Stack trace:
```
   at BadImageFormatExceptionRepro.Program.<>c__3`1.<GenericMethod>b__3_0(IInterface`1 iface, Wrapper`1 wrapper) in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 27
   at BadImageFormatExceptionRepro.Program.GenericMethod[T]() in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 30
   at BadImageFormatExceptionRepro.Program.Main() in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 22
```

Which version of .NET is the code running on?
.net5.0, .net6.0. Actually, experimenting with this [in SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWAChMAGAAk1wDoAZAS1QEcqBRMAB0QFMBnHugPaoeAbiJFUAQwC2vdpIDGXMgCFJAEwCS0yQHMuAMQGIdcNkvZxBqAEpdOAogG8iZNxWwVcAdlfuXhO5BZJx0AG6ScMrcGkIANgCeZDxwKApwZADqiJLs7FyIADwAKgB8fsFkAZWVmADMXhBkwAICcWQC+TlwxmQAvH0AFMVkcDBZOXkFJaVkAO6TXQCU/bOpyFxihBU1bvWNza3tnQWRvQCEQyNjE7ldM/OLBSt9swBmknE8mztBAL7iQI1UIRKJkBhRRAfJRkTSaVCQ6FcGa/fyo2pQWEIgpIgCyXDgAAsBOpBmxOLx+EJCpgAKwlcYtNqlWZcDjcPjWJYiMjosgA7ZA2q4JqYTG4yQMQZLPnVXbuADiXFQBToCnxRJJNNwJFK0q2uwFfJBkWUlFFmKVKsQao1xPUM2l80JBWUIxAHllfKClGwhTh2KhimRZXG2Tu0zK7zQCn6ZEGdCR4wWEcQL1mieD3pqVHhiODdpJgzAqzIJYGj1T3MB8vcbxjg3UXA+yDiNybLbb1aFwQF/yIAqAA===) I could not find a working configuration.

What OS and version, and what distro if applicable?
Windows 10.0.19043.1165.

What is the architecture (x64, x86, ARM, ARM64)?
x64

Do you know whether it is specific to that configuration?
I assume it's not.

**Comment by 333fred** [comment]
A slightly more minimal version of this repro:

```cs
using System;
using System.Linq.Expressions;

namespace BadImageFormatExceptionRepro
{
    class Program
    {
        private readonly struct Wrapper<T>
        {
            public static bool operator ==(T t, Wrapper<T> wrapper) => true;

            public static bool operator !=(T t, Wrapper<T> wrapper) => false;

            public static bool Equals(T t, Wrapper<T> wrapper) => true;
        }

        static void Main()
        {
            GenericMethod<string>();
        }

        private static void GenericMethod<T>() where T : class
        {
            Func<Expression<Func<T, Wrapper<T>, bool>>> func = () => (x, y) => x == y;

            func();
            Console.WriteLine(""Run"");
        }
    }
}
```
