### ISSUE TITLE
FastUpToDate check always failed on VS2022 with RunAnalyzersDuringBuild=false

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn#56370]
**Version Used**: 
VS2022 Preview3.1 + dotnet sdk 6.0.100-preview.7.21379.14

**Steps to Reproduce**:

1. dotnet new console;
2. Add `<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>` to the csproj file;
3. Open it, and build it more than once;

**Expected Behavior**:
It should not be rebuild since nothing is changed, this makes `RunAnalyzersDuringBuild=false` even more slow than `RunAnalyzersDuringBuild=true`.
>Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped

**Actual Behavior**:
> FastUpToDate: Input 'xxx.csproj.BuildWithSkipAnalyzers' is newer (2021/8/23 17:54:35) than earliest output 'xxx.pdb' (2021/8/23 17:52:15), not up to date. 
...
>Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped

**Comment by mavasani** [comment]
Got a repro and a fix in `Microsoft.Managed.Core.targets` that works. Sending a PR soon..
