### ISSUE TITLE
Add Usings: for Project and Solution

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#56409]
**Brief description:**
Currently, if you're using classes that exist in a namespace like ```System.Linq``` but you forgot to add the import, you can right-click and use the "using System.Linq;" codefix.  This is great but it can only be run on one file at a time.

Please enable this codefix to run on the entire project or hte entire solution.  When it runs, it should fix all the files that have the exact same type or namespace that is missing.  For example, if I am missing a using to ```System``` and I run the code-fix on a line that shows the error:
```The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)````

It should add ```using System;``` to any place a DateTime is causing that error but not to places where another class might be.

**Languages applicable:**
C#

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by jmarolf** [comment]
I would propose that instead we just offer to add it as a global using

**Comment by CyrusNajmabadi** [comment]
I'm a bit uncertain about how one gets into the use case that they have lots of code, all of which references a type which isn't available.

**Comment by LWChris** [comment]
I'm wondering the same as @CyrusNajmabadi.

Only thing I can think of: if you move one of your own classes, and then adjust the namespace accordingly. Now all other files referencing that class should need the new import (and probably remove the old import). Removing the old import can be done by code cleanup, but adding a new import is not a thing AFAIK.

**Comment by TonyValenti** [comment]
@CyrusNajmabadi - I was using the "implicit using" feature from RC7 and I did the refactoring to remove unnecessary using. Then I decided I didn't want that feature  and have to go through a ton of files and add the usings back in.

**Comment by LWChris** [comment]
@TonyValenti Oh that's unfortunate. Usually this is something a VCS would deal with though. You'd have one commit where you enabled that feature, and you can revert that commit later.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and niche scenario.
