### ISSUE TITLE
File scoped namespace is not generated anymore in .Net 6 RC1

### ISSUE THREAD

**Issue by Ponant** [dotnet/roslyn#56410]
Moved from https://github.com/dotnet/sdk/issues/21016

#### Describe the bug
In .Net 6 Preview 7 a class generated with VS used the new C#10 file scoped namespace. In RC1 this is not the case anymore. It uses the block-scope namespace, which sounds like a step back.
Using dotnet new classlib creates a `class1` file with file scoped namespace, but adding a class with VS uses the block-scope namespace. Creating the library from VS uses block-scoped namespace.

Is there a flag to ensure file-scoped namepsaces are generated in VS?

#### Expected behavior
File scoped namespaces are expected

#### Further technical details
VS 2022 Preview 4

**Comment by Ponant** [comment]
temp fix https://github.com/dotnet/aspnetcore/issues/35073

**Comment by CyrusNajmabadi** [comment]
We shoudl be respecting the user's setting here.   @davidwengier ?

> Is there a flag to ensure file-scoped namepsaces are generated in VS?

No.  Ultimately this should be in control of the user.  They can pick the default they want for namespaces, and then templates should be instantiated following that form.

**Comment by davidwengier** [comment]
Yeah, Roslyn will reformat any new document added based on user settings, either in an .editorconfig file, or this VS setting:
![image](https://user-images.githubusercontent.com/754264/133514245-00869b39-739c-4254-9fbf-be65e28ce5ed.png)

**Comment by davidwengier** [comment]
This definitely worked for me last night when adding a new file to Roslyn.sln, I was getting file-scoped, because we don't specify anything in our .editorconfig file :)

**Comment by DamianEdwards** [comment]
@davidwengier that setting is working for me, but I can't seem to make the .editorconfig flag work. There's a known issue with the setting not getting rendered in the .editorconfig UI which is being fixed (@jmarolf) but even if I add it manually it doesn't seem to get picked up.

**Comment by davidwengier** [comment]
@DamianEdwards can you post the editorconfig you used?

**Comment by davidwengier** [comment]
Just tried these steps without issue on Visual Studio 2022 Preview 4:

1. Confirm setting in VS is set to "Block scoped" as per above screenshot
2. Create new ASP.NET Core Web Application targeting .NET 6
3. Place the following `.editorconfig` in the solution root
```
[*.{cs,vb}]
csharp_style_namespace_declarations=file_scoped:suggestion
```
4. In VS, Alt+Shift+C to add new class

Class was added, and had a file scoped namespace

**Comment by DamianEdwards** [comment]
Yeah it's working now for me too. Only difference was I changed the global setting to file-scoped then back to block-scoped, before then trying to override with the .editorconfig, and now it seems to work.

**Comment by davidwengier** [comment]
Going to close this out, as everything is working as expected. @Ponant see my screenshot above for the setting to control this for your VS instance, or my other comment above for the corresponding .editorconfig setting.

**Comment by Ponant** [comment]
ok thank you for the clarification(s) @davidwengier @DamianEdwards

**Comment by davidwengier** [comment]
@Ponant The roslyn feature only formats new files added from a item or project template. Adding a new file via a code action, which is what the razor "Extract to code behind" feature is, is not supported.

I logged https://github.com/dotnet/razor-tooling/issues/5644 on the Razor tooling repo for you, feel free to comment further on it if necessary.
