### ISSUE TITLE
AdhocWorkspace.OpenDocument(documentId) causes parallel execution errors

### ISSUE THREAD

**Issue by gasparnagy** [dotnet/roslyn#56445]
**Version Used**: 4.0.0-3.final

**Steps to Reproduce**:

Our project is a VS extension and for testing it we need to provide the SyntaxTree for a particular document in a unit test. We have 137 tests that run in parallel using xUnit and SpecFlow. 

To provide the syntax tree, we used the following approach:

```
var adhocWorkspace = new AdhocWorkspace();
var project = adhocWorkspace.AddProject("foo-project-name", LanguageNames.CSharp);
var sourceTextContainer = textBuffer.AsTextContainer();
var document = adhocWorkspace.AddDocument(project.Id, "some-file-path.cs", sourceTextContainer.CurrentText).WithFilePath("some-file-path.cs");
adhocWorkspace.OpenDocument(document.Id);
```

Including this code in tests, particularly the `AdhocWorkspace.OpenDocument()` call caused random execution failures for various tests, even if they didn't have this call. The random issues cannot be observed when the the `OpenDocument` call is commented out (there are functional errors in that case of course).

Running the tests sequentially works.

The behavior can be observed on our OSS project, at commit by running the test from "SpecFlow.VisualStudio.Specs": https://github.com/SpecFlowOSS/SpecFlow.VS/commit/0632ff53c0586ee133a2684ab2cacac9072ccb8b

We have been able to workaround the problem by calling `CSharpSyntaxTree.ParseText`, so the issue is not critical for us, but maybe it is useful for anyone fighting against parallel execution issues.

**Expected Behavior**:

Tests run without errors with the same results as the sequential execution.

**Actual Behavior**:

Random execution failures for various tests, even if they didn't have this call. With this test set it happens 9 times out of 10.

**Comment by sharwell** [comment]
`new AdhocWorkspace()` uses MEF 2 (System.Composition) at runtime, which does not support concurrent usage. You will need to switch the runtime execution to vs-mef [like this](https://github.com/dotnet/roslyn-sdk/blob/10b52dee20f620354c35115ce609714bafee505d/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L1345-L1350) in order to support concurrent testing.

**Comment by gasparnagy** [comment]
@sharwell Thank you for the precise answer! We will try that!
// CC @patiqs
