### ISSUE TITLE
Code Cleanup (Formating) Ignores VB.Net 'Pretty listing'-Setting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56459]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Cleanup-Formating-Ignores-VBNet-/1527966)._

---
[severity:It bothers me. A fix would be nice]
Hi,
In the VB.Net Text Editor Settings canb you activate 'Pretty listing (reformatting) of Code', witch ensures among others that Variables are written using the same Case as in there Declaration.
If you use the Code-Cleanup with activated Formating, then this reformating only happens if the file is open in the Code Editor.
If you Call CodeCleanUp on the whole Codebase, then this setting is ignored.
Since this is a Formation option I would expect this to also happen when use use a Code CleanUp (with Formating) on files not open in the Text Editor.

Since this is rater simple to reproduce do is a sample needed?

---
#### Feedback Bot on 9/13/2021, 11:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Alexander Wurzinger on 9/14/2021, 01:41 AM: 

<p>Hi,<br>
I did some Test,<br>
1.) I did a replace, in My Solution, and left the changed files open.<br>
2.) I did a CodeCleanUp on the Solution with activated Formating.<br>
3.) I Saved all Changed Files.<br>
-&gt; I confirmed that  ‘Pretty listing (reformatting) of Code’ was only executed at the Codeeditor in front of me, Codeeditors open in Background didn’t execute the ‘Pretty listing’, witch I would have expected.<br>
So it seems, if I want to do a ‘Pretty listing’ on my hole solution, I would have to open every file, change it, save it and close it again.</p>

#### Feedback Bot on 9/15/2021, 09:46 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to be changing these experiences.
