### ISSUE TITLE
Can't disable Code Style Suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56461]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-disable-Code-Style-Suggestions/1528831)._

---
[severity:It's more difficult to complete my work]
My code is littered with "Code Style Suggestions" and there is no way to get rid of them !!!

Eg: 
"var a = 5" will show a suggestion to change var to explicit type (My style settings are set to prefer VAR)

If i then accept the suggestion and convert to "int a = 5" then Visual Studio will suggest that i "convert explicit type to var"  ARGHGHGHGHGH

How the heck do i disable ALL OF THESE suggestions, i dont want them, i dont need them - JUST GO AWAY !

---
#### Feedback Bot on 9/14/2021, 02:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/15/2021, 09:54 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Wenwen Fan [MSFT] on 9/15/2021, 06:40 PM: 

<p>Thank you for taking the time to log this issue!<br>
The current version of visual studio has been updated, so you can try it again after trying the update.<br>
We look forward to hearing from you!</p>

#### Martin Kirk on 9/16/2021, 05:34 AM: 

<p>Hi</p>
<p>The only place i’ve found to disable suggestions is per-suggestion in the code.<br>
if i hover on the suggestion i can navigate the severity and press NONE, which adds a Code Style Configuration in the repository.<br>
But i can’t disable the same suggestion across solutions in a single setting in Visual Studio (Tools / Options / Text Editor / C# / Code Style) 😦</p>
<p>My wish is that i enable / disable suggestions globally via the settings in Visual Studio  - and perhaps override them with the per solution config.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
Developer wants to bulk disable code style suggestions which is not possible today

**Comment by Youssef1313** [comment]
@jmarolf Won't `dotnet_analyzer_diagnostic.category-Style.severity = none` work? Or `dotnet_analyzer_diagnostic.severity = none` (will disable **ALL** analyzers)

**Comment by Youssef1313** [comment]
This part is also weird:

> "var a = 5" will show a suggestion to change var to explicit type (My style settings are set to prefer VAR)

If the settings is to prefer var, there shouldn't be a suggestion to offer explicit type.

**Comment by jmarolf** [comment]
> Jonathon Marolf Won't `dotnet_analyzer_diagnostic.category-Style.severity = none` work? Or `dotnet_analyzer_diagnostic.severity = none` (will disable **ALL** analyzers)

Ah yes, I always forget about this. This will work

**Comment by Montago** [comment]
Hi guys..

I'm the developer who reported this issue. 

I've been through the Tools / Options / Text Editor / C# / Code Style and setup my preferences, but they are ignored. 

In the Severity i can pick "Error, Warning, Suggestion and Refactor Only" - I would expect that these rules are applied in regards to showing or not showing the suggestions ? 

I've set ALL styles to "Refactor Only" in an attempt to hide all suggestions. 

Later i found that if i hover on a suggestion i can pick "Ignore" on the severity (which isn't present in the Code Style menu) 
If i choose to ignore - a Code Style Config is created for the solution and it stops showing. 

I guess this means that Visual Studio only cares about Code Style Config files and that the Code Syle menu is only a tool to create Code Style Configs ??

I was under the impression that whatever i edit inside the Code Style Menu is Global settings and that Config files are local (Per Solution settings)
