### ISSUE TITLE
netstandard2.1 - source generators is not working

### ISSUE THREAD

**Issue by LeftTwixWand** [dotnet/roslyn#56479]
**Version Used**:
.NET 5
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 3.1

**Steps to Reproduce**:
I've just created a source generator in netstandard2.1 library, and it's not working
But when I'm changing target framework to netstandard2.0 - it starts working!

**Comment by svick** [comment]
If you're talking about making the source generator a .Net Standard 2.1 library, then yes, that doesn't work and that's expected. See https://github.com/dotnet/roslyn/issues/45162 for more details.

**Comment by LeftTwixWand** [comment]
@svick Ok, thank you)
