### ISSUE TITLE
Can't read lightbulb entries when they are too long

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#56485]
![image](https://user-images.githubusercontent.com/4564579/133830186-194267cc-65f4-4445-a036-4903b8808580.png)

HOvering over the items does not show the full title either.  This may need to go to the editor for discussion.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi is this us or editor ?

**Comment by CyrusNajmabadi** [comment]
I believe it is a combination.  First, we should try to improve on our suggestion names.  IN this case, includingt he type name just isn't that important IMO.  However, this shoudl also go to editor that if things are cut off that hovering on them should likely give the full name.

**Comment by CyrusNajmabadi** [comment]
Fixes with https://github.com/dotnet/roslyn/pull/56846
