### ISSUE TITLE
Visual Studio does not suggest import of "System.Windows.Forms" for usage of "DialogResult" enum

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56483]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-does-not-suggest-import-of/1531408)._

---
[severity:Other]
See attached sample and screenshot: I use the enum "DialogResult", but the class does not contain the "import System.Windows.Forms" statement.
There is no "potential fix" to add this import statement.

![image](https://user-images.githubusercontent.com/611219/134399760-26a4c95b-47d6-4ab2-ab58-27df811d248e.png)

---
#### Feedback Bot on 9/16/2021, 03:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
