### ISSUE TITLE
Rationalize checking LanguageService results for consistency/invariants.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#5649]
Inspired by https://github.com/dotnet/roslyn/pull/5618

We should really be pushing the detection of errors  as close as possible to when they are first introduced.  For example, for outlining, we should ideally be producing an error when the client code creates outlining spans.

I think we can accomplish this across all our language service API in a consistent manner by moving to the 'context' pattern.  For example, for outlining, we would change the API to be:

```C#
    internal interface IOutliningService : ILanguageService
    {
        Task AddOutliningSpansAsync(OutliningContext context);
    }

    struct OutliningContext
    {
        ... properties ...
        void AddOutliningSpan(TextSpan textSpan, string bannerText, bool autoCollapse)
        {
              // Check spans here.
        }
    }
```

This approach seems nicer to me than having people have to get and pass along a SourceText object to our current OutliningSpan object.  The latter would be necessary if we wanted to immediately check things at OutliningSpan creation time.  Now, the client doesn't need to do that.  They just need to use the context object, and they'll find out immediately if they're doing something wrong.

**Comment by DustinCampbell** [comment]
I completely agree!

**Comment by CyrusNajmabadi** [comment]
Closing this out as this is hte general pattern we're taking as @mattwar, @DustinCampbell and I work on making APIs public.
