### ISSUE TITLE
Unexpected formatting warning for a space between a `new` modifier and a tuple type syntax.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#56498]
Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit)
Version 17.0.0 Preview 5.0 [31713.378.main]

![image](https://user-images.githubusercontent.com/10522107/133859912-3eb570bb-a15f-4a28-836e-99b8919f3b2e.png)

The warning goes away if the space is removed:
![image](https://user-images.githubusercontent.com/10522107/133860100-dda1e5ce-9581-461f-a8b0-9481b2602769.png)

Expected: No warning when the space is present, a warning when it is missing.

Note: this issue is referenced in source.

**Comment by jcouv** [comment]
The codestyle analyzer was fixed. Once we consume an updated package, the reference in code can be removed.

**Comment by jinujoseph** [comment]
blocked on 17.0 rtm
