### ISSUE TITLE
C# Naming style rules suggest adding regular matches

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Naming-style-rules-suggest-adding-reg/1516102)._

---
Naming style rules suggest adding regular matches，example： user_id，After repair： User_id,but I want to UserId

---
#### Feedback Bot on 8/30/2021, 02:02 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by sharwell** [comment]
Can you add a description of the steps to reproduce this issue, along with the expected behavior and actual behavior? Screenshot(s) would be particularly helpful.
