### ISSUE TITLE
Show region label at #endregion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56507]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-region-label-at-endregion/1516408)._

---
When working with C#, sometimes I'll use #region to logically organize the code into blocks. These regions can be given names. When looking through the code, I find that it could be helpful for the editor to show the region's name (the one specified by #region) to the right of #endregion. The text would not necessarily have to be editable (although the region's name for matching #region and #endregion tags should always match).

---
#### Feedback Bot on 8/30/2021, 02:03 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

#### christopherhume on 9/10/2021, 09:25 PM: 

<p>The #region label, or title, or description, or whatever it’s properly called might appear either as a CodeLens highlight or as a bubble, in the style of IntelliSense when one is near its matching #endregion.</p>
<p>It should be convenient to “Go” to either the #region or the #endregion.</p>
<p>[Similar indications and navigational capabilities might be implemented for #if / #elif conditions.]</p>

**Comment by CyrusNajmabadi** [comment]
`ctrl-]` will go to the corresponding region.  We should though add hover on endregion to show the correspond region tag (like we do when you hover on a `}`.
