### ISSUE TITLE
In Visual Studio/.editorconfig for C#, add new predefined type preferences "For objects"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56504]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-Visual-Studioeditorconfig-for-C-a/1523706)._

---
I would like to have an additional option "For objects" or something like that as a 3rd option in Visual Studio's `Options/Text Editor/C#/Code Style/General/predefined type preferences` and an according new `.editorconfig` entry `dotnet_style_predefined_type_for_string_and_object` to enable the possibility to write all primitive types as predefined types (`int`, `bool`, `double` etc.) and the types of objects as framework types (`Object`, `String`).

That then results in the following additional choice in the options dialog:

For objects: "prefere predefined type" (dotnet_style_predefined_type_for_object_and_string = true)

private object _member;
    static void M(string argument)
    {
        object local = argument;
    }

For objects: "prefere framework type" (dotnet_style_predefined_type_for_object_and_string = false)

private Object _member;
    static void M(String argument)
    {
        Object local = argument;
    }

---
#### Feedback Bot on 9/7/2021, 08:06 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by sharwell** [comment]
Tentatively marking this one as **Won't Fix**. This style area is notoriously difficult to support all possibilities, and this is the first time is many years we've heard of this specific style request. We'll still go over the request in a design review meeting and update with a final resolution.

**Comment by NTaylorMullen** [comment]
### Design Meeting Notes

![image](https://user-images.githubusercontent.com/2008729/134075808-7353de04-4ac6-441b-9b61-0a90a1b3edfc.png)
