### ISSUE TITLE
Add shortcut to add additional "if" clause.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56509]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-shortcut-to-add-additional-if-clau/1503801)._

---
I think it would be nice to be able to easily add an "else if" or just "else" clause to an already existing "if" clause.

**For example**

The following is already typed out:
```
if (true)
{
    printf("Console.Writeline");
}
```

By placing the cursor on the last angle bracket `}` the user could press `Ctrl + Enter` to add an `else` clause like so:

```
if (true)
{
    printf("Console.Writeline");
}
else
{
    printf("Console.Read();");
}
```

Another option is to achieve the same result through a "Quick Action". But I like the `Ctrl + Enter` flavour better.
With the `Ctrl + Enter` approach an option can be added when `Ctrl + Shift + Enter` is pressed for an `else if` clause to be added, instead.

_You might wanna not take the example code too seriously._ (:

---
#### Feedback Bot on 8/16/2021, 01:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Mika Dumont [MSFT] on 8/26/2021, 08:41 PM: 

<p>Thanks for taking the time to provide this feedback! Have you tried snippets? If you type if and press tab twice it will add an if statement for you. Same for an else statement. Let me know if this helps.</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Feedback Bot on 9/7/2021, 06:31 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.

**Comment by IvanStoychev** [comment]
Hello, I'm the original poster of the issue on "developercommunity.visualstudio.com".

I am aware of snippets but I thought pressing "CTRL + ENTER" would be even more convenient, as I don't think currently there is any functionality or reason for a person to press that key combination on the closing bracket of an "IF" statement and, in my mind, it would be very neat, just like the functionality that adds braces to methods if you press "CTRL + ENTER" on the closing bracket of their signature.

**Comment by CyrusNajmabadi** [comment]
closing out due to lack of feedback.
