### ISSUE TITLE
Consider adding Attribute extension F1 shortcut keys in c#，Link to custom document web site

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Consider-adding-Attribute-extension-F1-s/1524021)._

---
Consider adding Attribute extension F1 shortcut keys in c#，Link to custom document web site.
I know that developing extension programs can be achieved , 
I'm Chinese ，Due to the lack of language and documentation，
Extension program is not a quick way for me，
Do you  consider adding a faster way?
For example, Attribute in C#？

---
#### Feedback Bot on 9/7/2021, 08:07 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by jinujoseph** [comment]
Do you mind adding more information , a code sample explaining  ..what's expected and what's actual pls
