### ISSUE TITLE
Add new C# syntax to new IntelliSense suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56511]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-new-C-syntax-to-new-IntelliSense-su/1519375)._

---
When I type `private Dictionary<Guid, Stream> Streams { get; } = ` I'd like to be completed as `new();` not `new Dictionary<Guid, Stream>()`, at least when using appropriate C# language version.

---
#### Feedback Bot on 9/1/2021, 11:58 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
This is how things work.  you just need to type `new();`
