### ISSUE TITLE
error CS0171  LayoutKind.Explicit

### ISSUE THREAD

**Issue by sgf** [dotnet/roslyn#56512]
**Version Used**: 
.net 5,C# 9.0
**Steps to Reproduce**:

 ```C#
   [StructLayout(LayoutKind.Explicit, Pack = 1)]
    public struct UniUint32 {

        public UniUint32(uint _value) {
            value = _value;
        }
        public UniUint32(byte _b1,byte _b2,byte _b3,byte _b4) {
            b1=_b1;
            b2=_b2;
            b3=_b3;
            b4=_b4;
        }

        [FieldOffset(0)]
        public uint value;
        [FieldOffset(0)]
        public byte b1;
        [FieldOffset(1)]
        public byte b2;
        [FieldOffset(2)]
        public byte b3;
        [FieldOffset(3)]
        public byte b4;
        public static implicit operator uint(UniUint32 ip) => ip.value;
        public static unsafe implicit operator UniUint32(uint ip) => *((UniUint32*)&ip);
    }
```

**Expected Behavior**:
Compiled successfully
**Actual Behavior**:

`Error CS0171 UniUint32.b4 	D:\MySrc\DLBSvr\DLBSvr\Net\IPv4.cs 15 Active`

**Comment by PathogenDavid** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/7323 https://github.com/dotnet/roslyn/issues/10319 and https://github.com/dotnet/csharplang/issues/1465

As mentioned in https://github.com/dotnet/csharplang/issues/1465#issuecomment-572244877, if you're targeting .NET 5 You can [use `Unsafe.SkipInit`](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQAwAJMCMAdAEoCuMCUYApkQMID2YADlADY0BOAytwG5QAxjRQBuALAAoHPmLlK1OgElK3Riz5dBI8dOkBtHgi5khCADIQAnozIIAFFdv2A0rAAmRAKIAPFuzCUAhwuAAKEEIA1rgAvLgEAJQAutKYAMy4KCZmCLgAqjBQ+bAI6QBMuADe+lK49RkFRSWUFQ5kpbgA+vwQ7GQ0idXS9aP1hSgQAGZ0PFFQLKrBDnZ5CAAWUCiJknVj9b39NHHdhwO7owC+taONhcWlbcDWCMddwARwz6/dwOVfLzewHSAJ+7wALEMant9hNprN5osio5VrgNlsdiN9rgPrF3gQLti/ni/oT9sCSekyWNgOCSeCydcpFjcAYAGJQGjsDwAeSmUxQNEc2BSLMaHUouDONDJ7M53L5AqFDhFqRhjW+xw+so5XN5/MFjiSatumU1OPKOvl+qVjnKovVZsBOKpLLlesVhoc6QdppxztpZMahAAbLhqAEgnkNNwIAhGFxcBLHPcWmVKgshrEAHzhlhEaVBzKhpMwSYzcOsQJCYK4GNcOMJpoPVrldqdTNxXMAKgcDlTj3K3cSADJM7tLkA=).

If you're targeting older runtimes [call the default `this()` constructor or use `this = default`](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQAwAJMCMAdAEoCuMCUYApkQMID2YADlADY0BOAytwG5QAxjRQBuALAAoHPmLlK1OgElK3Riz5dBI8dOkBtHgi5khCADIQAnozIIAFFdv2A0rAAmRAKIAPFuzCUAhwuAAKEEIA1rgAvLgEAJQAutKYAMy4FCgQAGY0uCgmZgi4AKowUGWwCOkATLgA3vpSuG0Z5ZXVlPUOZDW4APr8EOxkNIm4ILgIABZQKA6Tza1ta7gjYwXxw6Pjkqu4AL4tax0VVTW9wNYIBYPABHA3d0PAdc+398Dpn68PABZltJ1ms5gs4rgPDRchAyOwEAdQW1HrEHgQkcj3mj3pjQT8cek8etgACcQC8ScpCC2gYAGJQGjsDwAeVyuRQNEc2BSNPwmX6lA2exoePpjOZbI5XIcPNShw6LwKjzFDKZrPZnMcSXlZ0yStwuL54vVUq1DjqvIV+q+hqJxrVks1MvSVr1httpLxHUIADZcNQAkFShpuBAEIwuFkag4Lt1ag0oCxJrEAHwBlhETb7Pk+gj+7J5AqBwJCYK4UNccORzqXHp1PoDJMp9MAKgcsa6VzqrcSADJmwcjkA==) (at the expense of a miniscule amount of runtime overhead.)

**Comment by sgf** [comment]
thanks
