### ISSUE TITLE
VCS integration - add "safe changes" flag that assures a commit only contains non-logic and visual changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56510]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VCS-integration---add-safe-changes-fla/1495507)._

---
In large projects there is often an avoidance for improving the code readability by refactoring, for example with the safe VS-supported automatic refactorings like method extraction or renaming things, even simple visual things like  breaking long lines, or making code more readable by introducing new temporary variables. 

It would help the developer community and product quality immensely if there was a code assistant flag in Visual Studio, keeping track of the current changes and telling: **Not yet introduced any major risks of breaking code (like changes in logic structure or flow).** 

There must already be this kind of meta "code-understanding" built in to the now very mature "code refactoring stuff" in Visual Studio, right?

---
#### Feedback Bot on 8/5/2021, 03:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Victor Cassel on 8/12/2021, 05:20 AM: 

<p>Another example, imagine you make a simple refactoring of a central class, which of course affects many dozens other files and projects : These changes are most often non-breaking (or generated by VS-tooling), but there is then no built-in signaling that the following GIT commit and Pull Request contains actually one 1 truly updated file and 99 consequential file changes.</p>

#### Mika Dumont [MSFT] on 8/12/2021, 03:25 PM: 

<p>Thanks for taking the time to provide this feedback! Can you give me more details of what you think this should look like?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Feedback Bot on 8/24/2021, 07:50 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the suggestion open, please provide the requested details.

#### Victor Cassel on 9/3/2021, 00:32 AM: 

<p>Something like this: Maybe say “2 safe changes”<br>
In this case I did a local variable renaming in two methods. If that isn’t a safe change, I don’t know what… 😃</p>
<p>The idea is that you should use this “meta information” further up in the “release chain” to get a “hint” of what kinds of changes are in a commit or in a pull request - that is, this will hint the code reviewer how much effort to put into reading “Every single code line” - ex all 100 change files just depend on one single renamed method, this can be reviewed quicker and with better security.</p>
<p>The change types could be levelled, with pure pure formatting changes being the safest change level of all.</p>
<p><img src="https://aka.ms/dc/image?name=Bc5d4791db47e445b82fed5013987303a637662511381315991_20210903-093217-image.png&amp;tid=c5d4791db47e445b82fed5013987303a637662511381315991" alt="image.png"></p>

#### Victor Cassel on 9/16/2021, 02:10 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing as out of scope of roslyn.
