### ISSUE TITLE
Can we get more information in inheritance margin?

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#56535]
Sometimes just the type name is not enough to know where the navigation will take me. For example in Razor tooling:

![image](https://user-images.githubusercontent.com/754264/133947218-1c7c48a2-f322-420a-8271-a7f80cff8594.png)

One of those `VisualStudioProjectSnapshotManagerDispatcher` is in the `VisualStudio.Mac` namespace, but I want to go to the Windows impl, but I don't know which is which. Perhaps a tooltip with the full namespace name would help?

**Comment by Youssef1313** [comment]
Duplicate of #55790

Good to know it's not only me who want to see fully qualified names in a tooltip :)

**Comment by CyrusNajmabadi** [comment]
if the display names are the same, we should append thigns like teh project name to disambiguate.

**Comment by sharwell** [comment]
Duplicate of #55790
