### ISSUE TITLE
Compiler raising CS1513 & 1514 in response to file scoped namespace on .NET6 RC1 using VS2019 16.11.3 Preview 1.0

### ISSUE THREAD

**Issue by jacrys** [dotnet/roslyn#56542]
**Version Used**: 
Microsoft Visual Studio Community 2019 Preview
Version 16.11.3 Preview 1.0
C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10

**Steps to Reproduce**:

1. Create file with file scoped namespace, or use webapp template
2. open in VS2019 16.11.3 Preview 1.0
3.Compiler error CS1513 & CS 1514 are raised.

**Expected Behavior**:no compiler errors for supported features.

**Actual Behavior**: ompiler error CS1513 & CS 1514 are raised.

![image](https://user-images.githubusercontent.com/3784287/133991600-bd0f39e6-9b8d-4185-96ef-00592243d16d.png)

![image](https://user-images.githubusercontent.com/3784287/133991631-f2ee8f05-b939-4e6f-b76c-82592f5ebea1.png)

**Comment by sharwell** [comment]
I believe this is by design. C# 10 is only supported in Visual Studio 2022 and newer.

**Comment by jacrys** [comment]
I apologize, I did not notice that the support for 2019 was only on Mac
