### ISSUE TITLE
Typo in EditorConfig UI ("carrage return")

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#56558]
Typo in EditorConfig template:

![image](https://user-images.githubusercontent.com/46729679/134075851-d97be070-0968-4043-a745-b901e5bf7638.png)

**Comment by Youssef1313** [comment]
@mikadumont This was already fixed in 16.11. https://github.com/dotnet/roslyn/pull/53327

**Comment by CyrusNajmabadi** [comment]
Closing out as fixed.
