### ISSUE TITLE
Bug - Unable to build solution in VS2015

### ISSUE THREAD

**Issue by cmatskas** [dotnet/roslyn#5656]
In my attempt to load and build the Roslyn solution, I have been unable to successfully build the project. The steps to recreate are:

** Attempt1 **
- Clone Roslyn to local
- Open Roslyn.sln in VS2015
- Click on Build > Build Solution
- Errors ensue (109063!)

**Approach 2**
- Navigate to Roslyn directory
- Open the command prompt
- Execute "cibuild.cmd > output.txt"
- Error ensue (file attached)

**Current setup:**
VS2015 fully uptodate
Xamarin installed (not sure if this is a factor but I saw it in previous posts)
ReSharper 9
OzCode

[Gist with errors](https://gist.github.com/cmatskas/ab783100a08357ee91f7)

**Comment by jmarolf** [comment]
Looks like nuget didn't restore any of the packages.  I'll post some steps that *should* work for you in a bit.  Did you have a look at [Building Testing and Debugging](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging)? If not, it might be a good place to start.

**Comment by cmatskas** [comment]
@jmarolf as a matter of fact yes, I did. I even run the nuget command separately. The output is can be found [on this gist](https://gist.github.com/cmatskas/4fa6775c2573d600959b). Thanks for helping out

**Comment by jmarolf** [comment]
@cmatskas Ok, well the standard question I should ask is "Do you have Windows 10 Tools installed?"

**Comment by cmatskas** [comment]
Hi @jmarolf. Thanks for the recommendation. This fixed the problem! This was my fault as I skimmed quickly through the "Building Testing and Debugging" section. This can be safely closed
