### ISSUE TITLE
Roslyn should move our VSPackage code to be servicehub based

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#56568]
This will remove our UI thread dependencies and ensure we can get to services (like ICacheService) without an unintended UI thread dependency.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I'm not sure I get what the actual ask is here; the stuff we have that's still VSPackage based I'd imagine can't move without all the stuff it uses being reimplemented as servicehub based? There's a lot of legacy IVs* services there.

**Comment by CyrusNajmabadi** [comment]
From our chat today, you'd would at least be moving the modern stuff that doesn't need the UI thread or vspackage goo. Things like our persistence layer code for example.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
