### ISSUE TITLE
Proposal: Stop reporting "An assembly with the same identity '...' has already been imported" errors

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5657]
The compilers perform metadata reference binding in several phases. In the first phase we resolve #r's. In second phase we filter out duplicate references to produce a set [1] of metadata definitions used for binding. Finally in the third phase we recursively traverse the graph of their dependencies and for each AssemblyRef find a matching definition among [1].

Currently second phase produces errors in the following cases:

1) Definitions A and A' of the same simple name are both framework assemblies whose identities unify, but are not exactly equal. E.g. A = "System.Core, 3.5.0.0, PKT=..." and A' = "System.Core, 4.0.0.0, PKT=..."

2) Definitions A and A' from the first phase are both weakly named (have no public key) and have different versions. E.g. A = "A, 1.0.0.0, PKT=null" and A' = "A, 2.0.0.0, PKT=null".

This logic is implemented in ```CommonReferenceManager.TryAddAssembly```
http://source.roslyn.io/#Microsoft.CodeAnalysis/ReferenceManager/CommonReferenceManager.Resolution.cs,632

I'd like to propose that we don't report these errors. Instead, keep both A and A' in the set of available definitions used for AssemblyRef binding and pick the highest version among them when constructing a set of assemblies referenced by the assembly being built.

In phase 3, where we bind AssemblyRefs, we compare the reference identities with each definition identity. If the AssemblyRef matches multiple definition identities we pick the closest version (i.e. the max lower or min higher). If both A and A' are present in the definition pool we'd just naturally pick the highest version as we do in other cases where A and A' are non-FX-unified strongly named identities (e.g. "B, 1.0.0.0, PKT=..." and "B, 2.0.0.0, PKT=..."). 

There are a couple of benefits of this proposal:
1) In scripting scenarios, where the user #loads multiple scripts that #r different versions of assemblies( A and A' above), we would just pick the highest version instead of forcing the user to synchronize versions of #r's accross all the loaded scripts.
2) Simplification of the binding process by consolidating versioning decisions to the third phase

**Comment by tmat** [comment]
@jaredpar @AlekseyTs @gafter @VSadov @agocke @davidfowl

**Comment by jaredpar** [comment]
I'm wondering if this change belongs in the compiler or better in the systems invoking the compiler.  Users rarely get into this situation when invoking the compiler directly, instead it comes from systems like MSBuild.  Given that MSBuild is the one with the logic to produce these incorrect graphs should they be the one to fix it?

**Comment by tmat** [comment]
I have updated the initial description with describing the main scenario - scripting. 

@jaredpar Yes, in regular msbuild scenarios the msbuild resolution logic already preselects the right references and the compiler errors shouldn't be reported at all (if an error is reported it would be from msbuild). 

The proposal is trying to address the scripting scenarios where the user specifies references via #r.

**Comment by tmat** [comment]
@jaredpar Yes, msbuild reports a diagnostic. It's just a warning though, so csc gets to report the error:

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3243: No way to resolve conflict between "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Choosing "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
1>  Consider app.config remapping of assembly "System.Data, Culture=neutral, PublicKeyToken=b77a5c561934e089" from Version "2.0.0.0" [C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll] to Version "4.0.0.0" [C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll] to solve conflict and get rid of warning.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll' and 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll'. Remove one of the duplicate references.
```

**Comment by tmat** [comment]
No idea why it says "Choosing "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily." and then still gives us both :(

**Comment by tmat** [comment]
@davkean

**Comment by jaredpar** [comment]
> The proposal is trying to address the scripting scenarios where the user specifies references via #r.

If that is the case shouldn't we just fix the scripting code around #r to do this logic?  It feels wrong to put logic in the core compiler reference resolution logic to solve a scenario specific to scripting.  If there is a general reason to do this that affects more than just scripting then I think it would make sense to do in the core compiler.  But right now it seems the other compiler hosts take care of this logic in a host specific way.

**Comment by tmat** [comment]
@jaredpar We could put the logic to scripting. However, I think the proposal would move the compiler further towards the general direction we want (that is, away from desktop specific binding policies).

Currently one can add two references A and A' that only differ in version only if these references are strongly named and not FX-unified. If their name is weak it is an error. This introduces inconsistency to platforms that ignore strong names and don't do FX-unification.

It would imo be better to remove these checks and instead use the standard versioning policy we apply in phase 3 here as well. Then we can also make that versioning policy customizable -- to delegate the decision whether two versions are compatible or not outside of the compiler.

**Comment by tmat** [comment]
Actually, just realized that if we really want consistent behavior between weak-named and strong-named references without breaking the current scenarios we'd need to implement additional logic in scripting anyways. 

When strongly named A and A' are passed in the compilation we keep both around (we don't pick the one with higher version). So any usage of a type from A will likely ambiguous and the user needs to use extern alias to disambiguate.

**Comment by tmat** [comment]
Another data point: VB doesn't report an error when A and A' are weak. It just continues with both of them added to compilation references. So I think C# should just do the same.

**Comment by jaredpar** [comment]
@tmat I think that's an interesting piece of data for changing the weak binding behavior.  

Note: I'm very wary of changing these rules this late in the cycle for update 1.  There's not a lot of time left to test this type of change.

**Comment by tmat** [comment]
@jaredpar I understand. I don't think I'm gonna need it for U1. I can use an alternative code path in the missing assembly resolution impl. Just wanted to get more consistency.

**Comment by ManishJayaswal** [comment]
@tmat  moving this to 1.2

**Comment by codespare** [comment]
Another case this occurs is #r'ing an assembly that has references built against .NET runtime 2.0 in csi.exe, such as Microsoft.Web.Administration and Microsoft.Web.Management shipped in Windows 10 for instance. It errors with conflicts on System.Configuration, System.Web and System.ServiceProcess.

**Comment by tmat** [comment]
This is now addressed for scripts by https://github.com/dotnet/roslyn/pull/6373.

**Comment by codespare** [comment]
Using 20d9e160c3f5f64ff883b3f542a8ee59a5b8cfe0 on the stabilization branch, the error doesn't occur anymore and the assembly can be used in my case as well, thank you for the update.

**Comment by codespare** [comment]
Unsure if it's somehow related (it involves type resolution?), but calling an async method synchronously in csi.exe along the lines of:
``` myResult = someObject.someAsyncMethod().Result; ```
returns an equivoqual:
``` error CS0029: Cannot implicitly convert type 'SomeNamespace.SomeType [MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]' to 'SomeNamespace.SomeType [MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]' ``` :)

**Comment by tmat** [comment]
Can you share the script?

**Comment by codespare** [comment]
Assuming a library project compiled in release with:

```csharp
namespace CsiAsyncRepro
{
    using System;
    using System.IO;
    using System.Threading.Tasks;
    using System.Diagnostics.Contracts;

    public class MyAsyncProvider
    {
        public string CreateFile()
        {
            var filename = Path.GetTempFileName();
            using (var file = File.Create(filename))
            using (var writer = new StreamWriter(file)) {
                writer.WriteLine(DateTime.Now.ToString());
                writer.WriteLine(DateTimeOffset.Now.ToString());
                writer.Flush();
            }
            return filename;
        }

        public async Task<ConcreteDataType> FiddleWithFile(TextReader reader)
        {
            Contract.Requires<ArgumentNullException>(reader != null, nameof(reader));

            var aDateString = await reader.ReadLineAsync();
            var aDate = DateTime.Parse(aDateString);
            await Task.Delay(1000);
            var theDateString = await reader.ReadLineAsync();
            var theDate = DateTimeOffset.Parse(theDateString);
            return new ConcreteDataType(aDate, theDate);
        }
    }

    public abstract class AbstractDataType: IEquatable<AbstractDataType>
    {
        protected AbstractDataType(DateTime aDate)
        {
            Contract.Requires<ArgumentException>(aDate <= DateTime.Now);
            ADate = aDate;
        }

        public DateTime ADate { get; }

        public abstract DateTimeOffset TheDate { get; }

        public bool Equals(AbstractDataType other)
        {
            return !Object.ReferenceEquals(other, null)
                && this.ADate == other.ADate;
        }

        public override bool Equals(object obj)
        {
            return obj is AbstractDataType
                && this.Equals((AbstractDataType)obj);
        }

        public override int GetHashCode()
        {
            return ADate.GetHashCode();
        }

        public static bool operator ==(AbstractDataType lhs, AbstractDataType rhs)
        {
            return !Object.ReferenceEquals(lhs, null) ? lhs.Equals(rhs) : Object.ReferenceEquals(rhs, null);
        }

        public static bool operator !=(AbstractDataType lhs, AbstractDataType rhs)
        {
            return !Object.ReferenceEquals(lhs, null) ? !lhs.Equals(rhs) : Object.ReferenceEquals(rhs, null);
        }

    }

    public sealed class ConcreteDataType: AbstractDataType, IEquatable<ConcreteDataType>
    {
        public ConcreteDataType(DateTime aDate, DateTimeOffset theDate)
            :base(aDate)
        {
            Contract.Requires<ArgumentException>(theDate <= DateTimeOffset.Now);
            TheDate = theDate;
        }

        public override DateTimeOffset TheDate { get; }

        public bool Equals(ConcreteDataType other)
        {
            return !Object.ReferenceEquals(other, null)
                && this.TheDate == other.TheDate
                && base.Equals(other);
        }

        public override bool Equals(object obj)
        {
            return obj is ConcreteDataType
                && this.Equals(obj as ConcreteDataType);
        }

        public override int GetHashCode()
        {
            return (base.GetHashCode() << 5) & TheDate.GetHashCode();
        }

        public static bool operator ==(ConcreteDataType lhs, ConcreteDataType rhs)
        {
            return !Object.ReferenceEquals(lhs, null) ? lhs.Equals(rhs) : Object.ReferenceEquals(rhs, null);
        }

        public static bool operator !=(ConcreteDataType lhs, ConcreteDataType rhs)
        {
            return !Object.ReferenceEquals(lhs, null) ? !lhs.Equals(rhs) : Object.ReferenceEquals(rhs, null);
        }

    }
}
```

this repros it in csi.exe:

``` csharp
#r "\bin\Release\CsiAsyncRepro.dll"

using CsiAsyncRepro;
MyAsyncProvider map = new MyAsyncProvider();
var filename = map.CreateFile();

ConcreteDataType cdt;
using (var reader = File.OpenText(filename)) {
    cdt = map.FiddleWithFile(reader).Result;
}
```
but oddly only once I added the IEquatable and CodeContract back (haven't tested with just one of the two yet).

**Comment by codespare** [comment]
Having tested variations, it triggers specifically when Code Contracts is enabled with the 'Assert on Contract Failure' flag set (other settings being: Full Contract Checking, Only Public Surface, Build Reference Assembly), and it doesn't trigger otherwise.

**Comment by tmat** [comment]
CodeContracts could be a likely culprit.

**Comment by tmat** [comment]
Not sure I understand this point:
- references to C:\Windows\System32\inetsrv\Microsoft.Web.Administration.dll and C:\Windows\System32\inetsrv\Microsoft.Web.Management.dll in CsiAsyncRepro

Just adding a reference doesn't do anything unless you use some type from the assembly, which CsiAsyncRepro doesn't

**Comment by codespare** [comment]
Yes, I was just listing the changes I had made between a first try that didn't repro the error vs a second that did. But eventually it boils down to code contract and the return type of Task<ConcreteDataType> as opposed to Task<string> that doesn't trigger the error for instance.

**Comment by tmat** [comment]
Would you mind sharing the dll and the script files? It would help me to diagnose, since I am currently not getting the error.

**Comment by codespare** [comment]
I shared it through OneDrive, it should be accessible under https://onedrive.live.com/redir?resid=E4B2C57B52ED16AD%21105

**Comment by tmat** [comment]
It seems to work:

>csi ImplicitConversionError.csx
CsiAsyncRepro.ConcreteDataType

**Comment by codespare** [comment]
Try the same through repl instead of csi.exe ImplicitConversionError.csx.

**Comment by tmat** [comment]
Got it! Thanks

**Comment by codespare** [comment]
This is the source:

``` csharp
namespace CsiAsyncRepro
{
    using System;
    using System.IO;
    using System.Threading.Tasks;
    using System.Diagnostics.Contracts;

    public class MyAsyncProvider
    {
        public string CreateFile()
        {
            var filename = Path.GetTempFileName();
            using (var file = File.Create(filename))
            using (var writer = new StreamWriter(file)) {
                writer.WriteLine(DateTime.Now.ToString());
                writer.WriteLine(DateTimeOffset.Now.ToString());
                writer.Flush();
            }
            return filename;
        }

        public async Task<ConcreteDataType> FiddleWithFile(TextReader reader)
        {
            Contract.Requires<ArgumentNullException>(reader != null, nameof(reader));

            var aDateString = await reader.ReadLineAsync();
            var aDate = DateTime.Parse(aDateString);
            var theDateString = await reader.ReadLineAsync();
            var theDate = DateTimeOffset.Parse(theDateString);
            return new ConcreteDataType(aDate, theDate);
        }
    }

    public abstract class AbstractDataType
    {
        protected AbstractDataType(DateTime aDate)
        {
            Contract.Requires<ArgumentException>(aDate <= DateTime.Now);
            ADate = aDate;
        }

        public DateTime ADate { get; }

        public abstract DateTimeOffset TheDate { get; }

    }

    public sealed class ConcreteDataType : AbstractDataType
    {
        public ConcreteDataType(DateTime aDate, DateTimeOffset theDate)
            : base(aDate)
        {
            Contract.Requires<ArgumentException>(theDate <= DateTimeOffset.Now);
            TheDate = theDate;
        }

        public override DateTimeOffset TheDate { get; }
    }
}
```

and the proj:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{659C8285-8720-470C-9119-890D616AD2C4}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>CsiAsyncRepro</RootNamespace>
    <AssemblyName>CsiAsyncRepro</AssemblyName>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <CodeContractsAssemblyMode>1</CodeContractsAssemblyMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeContractsEnableRuntimeChecking>True</CodeContractsEnableRuntimeChecking>
    <CodeContractsRuntimeOnlyPublicSurface>False</CodeContractsRuntimeOnlyPublicSurface>
    <CodeContractsRuntimeThrowOnFailure>False</CodeContractsRuntimeThrowOnFailure>
    <CodeContractsRuntimeCallSiteRequires>False</CodeContractsRuntimeCallSiteRequires>
    <CodeContractsRuntimeSkipQuantifiers>False</CodeContractsRuntimeSkipQuantifiers>
    <CodeContractsRunCodeAnalysis>False</CodeContractsRunCodeAnalysis>
    <CodeContractsNonNullObligations>True</CodeContractsNonNullObligations>
    <CodeContractsBoundsObligations>True</CodeContractsBoundsObligations>
    <CodeContractsArithmeticObligations>True</CodeContractsArithmeticObligations>
    <CodeContractsEnumObligations>True</CodeContractsEnumObligations>
    <CodeContractsRedundantAssumptions>True</CodeContractsRedundantAssumptions>
    <CodeContractsAssertsToContractsCheckBox>True</CodeContractsAssertsToContractsCheckBox>
    <CodeContractsRedundantTests>True</CodeContractsRedundantTests>
    <CodeContractsMissingPublicRequiresAsWarnings>True</CodeContractsMissingPublicRequiresAsWarnings>
    <CodeContractsMissingPublicEnsuresAsWarnings>False</CodeContractsMissingPublicEnsuresAsWarnings>
    <CodeContractsInferRequires>True</CodeContractsInferRequires>
    <CodeContractsInferEnsures>False</CodeContractsInferEnsures>
    <CodeContractsInferEnsuresAutoProperties>True</CodeContractsInferEnsuresAutoProperties>
    <CodeContractsInferObjectInvariants>False</CodeContractsInferObjectInvariants>
    <CodeContractsSuggestAssumptions>False</CodeContractsSuggestAssumptions>
    <CodeContractsSuggestAssumptionsForCallees>False</CodeContractsSuggestAssumptionsForCallees>
    <CodeContractsSuggestRequires>False</CodeContractsSuggestRequires>
    <CodeContractsNecessaryEnsures>True</CodeContractsNecessaryEnsures>
    <CodeContractsSuggestObjectInvariants>False</CodeContractsSuggestObjectInvariants>
    <CodeContractsSuggestReadonly>True</CodeContractsSuggestReadonly>
    <CodeContractsRunInBackground>True</CodeContractsRunInBackground>
    <CodeContractsShowSquigglies>True</CodeContractsShowSquigglies>
    <CodeContractsUseBaseLine>False</CodeContractsUseBaseLine>
    <CodeContractsEmitXMLDocs>False</CodeContractsEmitXMLDocs>
    <CodeContractsCustomRewriterAssembly />
    <CodeContractsCustomRewriterClass />
    <CodeContractsLibPaths />
    <CodeContractsExtraRewriteOptions />
    <CodeContractsExtraAnalysisOptions />
    <CodeContractsSQLServerOption />
    <CodeContractsBaseLineFile />
    <CodeContractsCacheAnalysisResults>True</CodeContractsCacheAnalysisResults>
    <CodeContractsSkipAnalysisIfCannotConnectToCache>False</CodeContractsSkipAnalysisIfCannotConnectToCache>
    <CodeContractsFailBuildOnWarnings>False</CodeContractsFailBuildOnWarnings>
    <CodeContractsBeingOptimisticOnExternal>True</CodeContractsBeingOptimisticOnExternal>
    <CodeContractsRuntimeCheckingLevel>Preconditions</CodeContractsRuntimeCheckingLevel>
    <CodeContractsReferenceAssembly>DoNotBuild</CodeContractsReferenceAssembly>
    <CodeContractsAnalysisWarningLevel>0</CodeContractsAnalysisWarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MyAscyncProvider.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```

**Comment by codespare** [comment]
(also you'll notice there is a small glitch with ObjectFormatter output when dumping ``` cdt ``` in the cases that pass: the abstract/override property is output twice)

**Comment by tmat** [comment]
I can repro now.

**Comment by tmat** [comment]
The issues has nothing to do with code contracts. I have a simpler repro. Fixing now. Thanks for reporting!

**Comment by tmat** [comment]
This has been implemented for scripting.
