### ISSUE TITLE
Unable to set up editorconfig options like invert globally

### ISSUE THREAD

**Issue by FalcoGer** [dotnet/roslyn#56610]
**Version Used**: 16.0

**Steps to Reproduce**:

1. Edit roslynator.ruleset
2. Add deprecated rule
3. Get compiler warning about deprecated rule

**Expected Behavior**:

I can't use rules like `RCS0011i` globally because there is no option to `roslynator.RCS0011.invert = true` in the ruleset file or anywhere else.
There should be an option to globally invert rules like RCS0011 instead of having it solution specific every time in an editorconfig file because my style is not going to change between projects. I want to set it up once.

**Actual Behavior**:

I get a warning about the rule being deprecated. The rule itself not showing in the error list.

**Comment by jinujoseph** [comment]
pls file an issue here https://github.com/JosefPihrt/Roslynator/issues
