### ISSUE TITLE
[LOC] Roslyn.Compilers.CSharp.Emit.UnitTests.dll has extra assert failures in JPN

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5662]
Run Roslyn.Compilers.CSharp.Emit.UnitTests.dll on a JPN OS, with JPN VS and VSUML build installed.

Errors are here: 
Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.PubKeyContainerBogusOptions [FAIL]
      Assert.True() Failure
      Stack Trace:
            êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.PubKeyContainerBogusOptions()
   Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerBogus [FAIL]
      Assert.True() Failure
      Stack Trace:
            êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerBogus()
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalBoolExpr01b [FAIL]
      Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : \r\nExecution failed for assembly 'C:\Users\vslab2\AppData\Local\Temp\RoslynTestFailureDump\9fc11f63-18d3-4b07-9b47-c110386c8a33'.\r\nExpected: False\r\nArithmetic operation resulted in an overflow.\r\nActual:   False\r\nŽZp‰‰ŽZ‚ÌŒ‹‰ÊƒI[ƒo[ƒtƒ[‚ª”­¶‚µ‚Ü‚µ‚½B\r\n\r\n
      Stack Trace:
            êŠ Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
            êŠ Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
            êŠ Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
            êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalBoolExpr01b()

**Comment by TyOverby** [comment]
Closed by #6633
