### ISSUE TITLE
[LOC] Roslyn.Compilers.UnitTests.dll has bad string translation for JPN

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5663]
Run Roslyn.Compilers.UnitTests.dll on a machine with JPN OS, JPN VS, and VSUML installed. 

See errors here:
   Microsoft.CodeAnalysis.UnitTests.EncodedStringTextTests.HorizontalEllipsis [FAIL]
      System.IndexOutOfRangeException : ƒCƒ“ƒfƒbƒNƒX‚ª”z—ñ‚Ì‹«ŠEŠO‚Å‚·B
      Stack Trace:
            êŠ Microsoft.CodeAnalysis.Text.StringText.get_Item(Int32 position)
            êŠ Microsoft.CodeAnalysis.UnitTests.EncodedStringTextTests.HorizontalEllipsis()
   Microsoft.CodeAnalysis.UnitTests.EncodedStringTextTests.Decode_NonUtf8 [FAIL]
      Assert.Equal() Failure\r\nPosition: First difference is at position 19\r\nExpected: abc def baz aeiouy ?f?÷EUiy\r\nActual:   abc def baz aeiouy €’¤¶ÉÛE
      Stack Trace:
            êŠ Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            êŠ Microsoft.CodeAnalysis.UnitTests.EncodedStringTextTests.Decode_NonUtf8()
Finished: Roslyn.Compilers.UnitTests.dll

**Comment by TyOverby** [comment]
Closed by #6633
