### ISSUE TITLE
Deprecate the `-unsafe` compiler switch

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/roslyn#56632]
## Background and Motivation

Use of the `unsafe` keyword currently requires passing the `-unsafe` switch to the compiler. While this made sense when .NET still cared about things like code access security and running untrusted code (e.g. Silverlight in the browser), these are not environments that .NET supports any longer. There are no environments that I know of where allowing unsafe code would mean the code will no longer run.

Without support for the concepts of code access security in the runtime or class libraries, it's trivial to write unsafe code without passing the switch anyway (the marshalling APIs, Unsafe APIs, etc.).

It feels like the switch/project setting is unnecessary ceremony before people can use a piece of C# syntax.

## Proposed API

The compiler should assume `-unsafe` was passed on the command line.

## Alternative Designs

Change the default in the SDK instead of in the compiler.

## Risks

People who have misguided assumptions about the security implications of `-unsafe` might feel like this exposes their codebases to security issues. We could provide an analyzer that generates an error if `unsafe` is used. The analyzer could also look for other obvious sources of unsafe code, such as the Marshalling APIs and Unsafe APIs (this would be a net value add wrt security).

**Comment by svick** [comment]
Considering this, should the `unsafe` keyword also be expanded, abolished or otherwise changed? Though that would be a separate discussion for csharplang.
