### ISSUE TITLE
[LOC] Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll has one test that fails due to bad string on JPN OS.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5664]
Run Roslyn.Compilers.VisualBasic.CommandLine.UnitTests.dll on a machine with JPN OS, JPN VS, and VSUML installed.

Error is below:
Microsoft.CodeAnalysis.VisualBasic.CommandLine.UnitTests.CommandLineTests.Bug15538 [FAIL]
      Assert.Equal() Failure\r\nPosition: First difference is at position 0\r\nExpected: Successfully processed 1 files; Failed processing 0 files\r\nActual:   1 ŒÂ‚Ìƒtƒ@ƒCƒ‹‚ª³í‚Éˆ—‚³‚ê‚Ü‚µ‚½B0 ŒÂ‚Ìƒtƒ@ƒCƒ‹‚ðˆ—‚Å‚«‚Ü‚¹‚ñ‚Å‚µ‚½
      Stack Trace:
            êŠ Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            êŠ Microsoft.CodeAnalysis.VisualBasic.CommandLine.UnitTests.CommandLineTests.Bug15538()

**Comment by TyOverby** [comment]
Closed by #6633
