### ISSUE TITLE
Disable redirect when pausing running project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56648]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Disable-redirect-when-pausing-running-pr/1359094)._

---
A feature that allows user to disable being redirected to (in my case) Program.cs when pausing the running project.

While my project is running I can often get away with writing code, saving, pause the project and resume to implement changes.
Every time I pause I'm being redirected to the execution loop which is very annoying.

I see there was made another post about this that was closed due to inadequate information. Please let me know what more information you would need to implement this change!

---
#### Feedback Bot on 3/8/2021, 00:28 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Can you share a repro scenario with expected and actual so we can understand this better.
