### ISSUE TITLE
[LOC] Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll has multiple assert failures with JPN

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5665]
Run Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll on a machine with JPN OS, JPN VS, and VSUML installed. 

Errors are below:
   InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerBogus [FAIL]
      Assert.True() Failure
      Stack Trace:
            êŠ InternalsVisibleToAndStrongNameTests.SignModuleKeyContainerBogus()
   InternalsVisibleToAndStrongNameTests.AssemblySignatureKeyAttribute_3 [FAIL]
      Assert.True() Failure
      Stack Trace:
            êŠ InternalsVisibleToAndStrongNameTests.AssemblySignatureKeyAttribute_3()
   InternalsVisibleToAndStrongNameTests.PubKeyContainerBogusOptions [FAIL]
      Assert.True() Failure
      Stack Trace:
            êŠ InternalsVisibleToAndStrongNameTests.PubKeyContainerBogusOptions()

**Comment by TyOverby** [comment]
Closed by #6633
