### ISSUE TITLE
[LOC] Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll has string translation issues with JPN

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5666]
Run Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll on a machine with JPN OS, JPN VS, and VSUML installed.

Errors are:
Microsoft.CodeAnalysis.CSharp.UnitTests.DynamicViewTests.NoMembers [FAIL]
      Assert.Equal() Failure\r\nPosition: First difference is at position 0\r\nExpected: No further information on this object could be discovered\r\nActual:   ‚±‚ÌƒIƒuƒWƒFƒNƒg‚ÉŠÖ‚·‚éÚ×î•ñ‚ªŒ©‚Â‚©‚è‚Ü‚¹‚ñ‚Å‚µ‚½
      Stack Trace:
            êŠ Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            êŠ Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.Verify(DkmEvaluationResult actual, DkmEvaluationResult expected)
            êŠ Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.Verify(IReadOnlyList`1 actual, DkmEvaluationResult[] expected)
   Microsoft.CodeAnalysis.CSharp.UnitTests.ResultsViewTests.GetEnumerableException [FAIL]
      Assert.Equal() Failure\r\nPosition: First difference is at position 1\r\nExpected: "Exception of type 'E' was thrown."\r\nActual:   "Ží—Þ 'E' ‚Ì—áŠO‚ªƒXƒ[‚³‚ê‚Ü‚µ‚½B"
      Stack Trace:
            êŠ Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
            êŠ Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.Verify(DkmEvaluationResult actual, DkmEvaluationResult expected)
            êŠ Microsoft.CodeAnalysis.CSharp.UnitTests.ResultsViewTests.GetEnumerableException()

**Comment by TyOverby** [comment]
This should have been closed by #6633.
