### ISSUE TITLE
Add the ability to escape strings with special characters (e.g. quotes) when pasting into Visual Studio.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56661]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-the-ability-to-escape-strings-with-s/1532281)._

---
When I use Resharper and paste string values with special characters that need to be escaped, it will automatically do that for me.

---
#### Feedback Bot on 9/18/2021, 01:30 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by sharwell** [comment]
Duplicate of #31869
