### ISSUE TITLE
Add a means to disable HoReload at the solution/project level

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/roslyn#56679]
HotReload is unlikely to support all scenarios, at least not in its first iteration. Eg [support for IL weavers](https://github.com/dotnet/roslyn/issues/56678). 

So it would be nice to have a mechanism to disable HotReload at the solution and/or project level. Ideally this would be done via a well known MSBuild property so it can be checked into source control

cc @LyalinDotCom

**Comment by tmat** [comment]
It is possible to disable Hot Reload in launch settings.
@tmeschter What's the name of the setting?

**Comment by SimonCropp** [comment]
@tmat I did not think launch settings were intended to be committed to source control? given they often have user specific settings like working directory?

**Comment by gfraiteur** [comment]
A disabling mechanism would be useful, but it should be on the method level (e.g. in a PDB section) and not at project level. A user of a weaving technology would typically weave a small percent of the source code, and EnC/HotReload is still desirable in parts of the program that have not overcome transformations.

**Comment by tmat** [comment]
We already have assembly-level flag. See https://github.com/dotnet/roslyn/issues/56681#issuecomment-926759022. 

Type-level or member level attribute seems like a reasonable addition.

**Comment by tmeschter** [comment]
In a launch profile, setting `hotReloadEnabled` to `false` will turn off Hot Reload when launching a process using that profile.

Note that it is up to the launching code to honor this setting. Console, WinForms, WPF, and web applications when started from VS will honor it. I can't speak to command-line scenarios, or other application types.
