### ISSUE TITLE
Correct resolving of delegates and values parameters

### ISSUE THREAD

**Issue by Alezy80** [dotnet/roslyn#56697]
**Version Used**: VS 2022 Preview 4 with NET 6.0 RC1

**Steps to Reproduce**:
Create NET 6.0 program with next code:
```csharp
namespace CompileError
{
    internal class Program
    {
        public delegate TActual ActualValueDelegate<TActual>();

        private static void Main(string[] args)
        {
            Check(TestCode); //CS0121
            Check(() => TestCode()); //CS0121
        }

        private static void Check<TActual>(ActualValueDelegate<TActual> d) { }
        private static void Check<TActual>(TActual v) { }
        private static bool TestCode() => true;
    }
}
```
**Expected Behavior**:
The code must be compiled without any issues
**Actual Behavior**:
The code is compiled fine in all versions of NET/Core before 6.0, but in 6.0 I've got an error:
```
The call is ambiguous between the following methods or properties: 'Program.Check<TActual>(Program.ActualValueDelegate<TActual>)' and 'Program.Check<TActual>(TActual)'
```
If I change signature `Check<TActual>(ActualValueDelegate<TActual> d) { }` to `Check<TActual>(Func<TActual> d) { }` compilation is successful.

**Comment by cston** [comment]
@Alezy80, thanks for reporting this issue.

This has been fixed in https://github.com/dotnet/roslyn/pull/56341.
