### ISSUE TITLE
Add ability to provide a CryptoKeyFile as a byte[]

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn#567]
Today, to provide a strong name, it has to come from a file on disk:

```C#
var options = context.CSharpCompilation.Options.WithStrongNameProvider(strongNameProvider)
                                                           .WithCryptoKeyFile(keyFile);
```

Instead, I'd like to pass a fixed byte[].

**Comment by gafter** [comment]
@davidfowl Why did you close this? Is it no longer a request?

**Comment by tmat** [comment]
Working on it.

**Comment by gafter** [comment]
I tried to verify this, but I see we failed to add a method CompilationOptions.WithCryptoPublicKey.

**Comment by tmat** [comment]
The method is on language specific CSharp/VisualBasic-CompilationOptions. Seems like we are missing "common" methods for many other options. Closing this issue and filing a bug to add all of them.
