### ISSUE TITLE
When adding integer to pointer in checked context add.ovf.un instruction is generated

### ISSUE THREAD

**Issue by jacekbe** [dotnet/roslyn#5671]
It seems that C# compiler in VS2015 generates wrong instruction when doing pointer arithmetic in checked context. Adding integer to pointer causes the compiler to emit add.ovf.un instruction instead of expected add.ovf.

Here is an example program:
```C#
unsafe class Program
{
    private static byte* dummy = (byte *)100000;
    private static byte* TestWithOverflowCheck(int d)
    {
        return checked(dummy + d);
    }

    private static byte* TestWithoutOverflowCheck(int d)
    {
        return unchecked(dummy + d);
    }

    static void Main(string[] args)
    {
        Console.WriteLine("TestWithOverflowCheck(1): " + (ulong)TestWithOverflowCheck(1));
        Console.WriteLine("TestWithOverflowCheck(-1): " + (ulong)TestWithOverflowCheck(-1));
        Console.WriteLine("TestWithoutOverflowCheck(1): " + (ulong)TestWithoutOverflowCheck(1));
        Console.WriteLine("TestWithoutOverflowCheck(-1): " + (ulong)TestWithoutOverflowCheck(-1));
        Console.ReadKey();
    }
}
```

Depending on platform target setting TestWithOverflowCheck(-1) fails in a different way:
 * on any CPU or x86 it throws OverflowException
 * on x64 it prints 4295067295 instead of expected 99999

And here's MSIL output:
TestWithoutOverflowCheck
IL_0001 ldsfld System.Byte* Test.Program::dummy
IL_0006 ldarg.0
IL_0007 add
IL_0008 stloc.0
IL_0009 br.s IL_000B
IL_000B ldloc.0
IL_000C ret

TestWithOverflowCheck
IL_0001 ldsfld System.Byte* Test.Program::dummy
IL_0006 ldarg.0
IL_0007 add.ovf.un
IL_0008 stloc.0
IL_0009 br.s IL_000B
IL_000B ldloc.0
IL_000C ret

**Comment by VSadov** [comment]
This is the same code as was generated by previous versions of C# compiler. Changing this now would result in code behaving differently after recompilation. That would be pretty bad.

**Comment by VSadov** [comment]
@madst  @jaredpar

**Comment by VSadov** [comment]
@MadsTorgersen   @jaredpar

**Comment by jacekbe** [comment]
IMHO it is very unlikely that someone relies on such erroneous behaviour. The only scenario I can think of is that someone uses it as a fancy way to check if integer is non-negative which would be extremely bizarre. Also that wouldn't work on 64-bit platform target where addition of negative integer results in interpreting it as unsigned integer which results in offsetting the pointer by big (>2^31) value. If someone gets valid program behaviour then that would be even more bizarre.
On top of that I don't think there are many people using pointer + checked combination. I enabled it on my project out of curiosity to check if it reveals any bugs, but I don't really rely on it.

On the other hand inconsistency between pointer arithmetic in checked and unchecked context looks very bad especially with 64-bit platform target when neither checked or unchecked variant throws exception but just gives different results.

**Comment by jaredpar** [comment]
Thanks for the detailed report here! 

Given the narrow scope of the bug though and that the behavior is consistent with the native compiler we are "won't fixing" the bug at this time.
