### ISSUE TITLE
Error CS8032 An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from (...)

### ISSUE THREAD

**Issue by augustoproiete** [dotnet/roslyn#56738]
Warning `CS8032` System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from ... when building a class library targeting `net6.0` with .NET 6 RC1 SDK:0

**Version Used**: 
SDK: 6.0.100-rc.1.21458.32
VS: 16.11.3

**Steps to Reproduce**:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net5.0;netstandard2.0;net461</TargetFrameworks>

    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TreatSpecificWarningsAsErrors />
  </PropertyGroup>
 
</Project>
```

**Expected Behavior**:

No warnings or errors

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/177608/134790610-4743b2a5-f6ac-4461-9e07-769a02d1176c.png)

```
Error | CS8032 | An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.1.21451.13\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. | NaturalStringExtensions (net6.0) | C:\augustoproiete\my-project\CSC | 1 | Active
```

**Workaround**:

Disable the warning `CS8032`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net5.0;netstandard2.0;net461</TargetFrameworks>

    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8032</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TreatSpecificWarningsAsErrors />
  </PropertyGroup>
 
</Project>
```

**Comment by svick** [comment]
I believe if you want to use .Net 6, you need VS 2022. The error message is trying to tell you that: .Net 6 requires Roslyn version 4.0 and VS 2019 does not support that.

**Comment by augustoproiete** [comment]
Thanks @svick. I suspect you're correct - though I have been using .NET 6.0.100-preview.4 and prior versions with VS2019 without issues, so it seems support for VS2019 has been dropped in more recent releases.

If you or anyone reading this know of any official announcement that .NET 6 requires VS2022 to work, please post here as I'm sure others will also expect .NET 6 to work with VS2019.

It would also be great if a check could be added, with a clear message that VS2019 is not supported.

**Comment by svick** [comment]
> I have been using .NET 6.0.100-preview.4 and prior versions with VS2019 without issues, so it seems support for VS2019 has been dropped in more recent releases.
>
> If you or anyone reading this know of any official announcement that .NET 6 requires VS2022 to work, please post here as I'm sure others will also expect .NET 6 to work with VS2019.

Both [the download page for .Net 6 RC1](https://dotnet.microsoft.com/download/dotnet/6.0) and [its release notes](https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-rc.1.md) say that only VS 2022 is supported.

It seems preview 4 was the last version to support VS 2019.

**Comment by martincostello** [comment]
There's also a recent change in dotnet/runtime to have the source generators multi-target for different Visual Studio versions: https://github.com/dotnet/runtime/pull/59074

**Comment by jcouv** [comment]
Closing the issue as by-design. Thanks

**Comment by shunyh** [comment]
@augustoproiete 

Yes, it does not support VS2019.

![image](https://user-images.githubusercontent.com/7311188/209508884-b1f48767-390a-40a0-b62a-5f8767fdf86b.png)
