### ISSUE TITLE
[Proposal] scoped keyword for local variable

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#5674]
I suggest to add `scoped` keyword.
It's purpose is to use variable in piece of code and hide it further.
Image a function
```
void Work()
{
    bool success = PerformWork();
    if (success)
    {
        PerformAdditionalWork();
    }

    Result success = Result::CreateSuccessResult();
    SetResult(success);
}
```
Currently it is invalid, because `success` with type `Result` override previous with type `bool`. Basic approach to place each piece of code inside of parantheses
```
void Work()
{
    {
        bool success = PerformWork();
        if (success)
        {
            PerformAdditionalWork();
        }
    }
    {
        Result success = Result::CreateSuccessResult();
        SetResult(success);
    }
}
```
This is very ugly.
I'd like to write like
```
void Work()
{
    // success variable declares here
    scoped bool success = PerformWork();
    if (success)
    {
        PerformAdditionalWork();
    }
    // success variable hides here. success variable now is undeclared. 

    Result success = Result::CreateSuccessResult();
    SetResult(success);
}
```
Scoped variable visible only in next statement.
If next statement is another scoped variable then to next statement after scoped variable.
For example
```
void Work()
{
    scoped var object = GetObject();
    scoped var anotherObject = GetAnotherObject();
    scoped bool success = PerformWork(object, anotherObject);
    if (success)
    {
        PerformAdditionalWork();
    }

    Result success = Result::CreateSuccessResult();
    SetResult(success);
}
```

**Comment by aluanhaddad** [comment]
This seems very confusing. The example use case is confusing without the proposed feature and even more confusing with it. Even in languages the permit this form of reassignment, say JavaScript, it is generally considered a bad practice. Why wouldn't you create a second variable called result and use that? The code would be infinitely more readable. Also you can do this with dynamic. At any rate, a variable going in and out of scope like that with different meanings and different types is extremely confusing.

**Comment by dsaf** [comment]
> This is very ugly.

Why? This is a built-in syntax-level support for scoping that is intuitive and unambiguous.

Furthermore the samples you are provided could be covered by ```out var```: http://odetocode.com/blogs/scott/archive/2014/09/15/c-6-0-features-part-3-declaration-expressions.aspx

**Comment by gafter** [comment]
@KalitaAlexey The C# language was designed with a number of scoping restrictions and constraints (like the "single definition rule") that prevent you from reusing names in a method body in a way that could possibly be confusing. This feature aims to take things in the opposite direction, requiring the reader to be aware of more context to understand the code. It seems to me this feature would most benefit code that exhibits the code smell of being far too long, and in which the programmer had difficulty thinking of appropriate names for variables.
