### ISSUE TITLE
[Proposal] override keyword for local variable

### ISSUE THREAD

**Issue by KalitaAlexey** [dotnet/roslyn#5675]
I suggest to add `override` keyword.
It's purpose is to override local variable at some point
Imagine a function
```
void ChangeObjects(Object object, AnotherObject anotherObject)
{
    var someData = GetSomeData(object.Data);
    var anotherData = GetAnotherData();
    var convertedData = ConvertData(someData, anotherData);
    object.Data = convertedData;

    var someData = GetSomeData(anotherObject.Data);
    var anotherData = GetAnotherData();
    var convertedData = ConvertData(someData, anotherData);
    anotherObject.Data = convertedData;
}
```
Currently it is invalid, because some variables override previous variables. Basic approach to place each piece of code inside of parantheses
```
void ChangeObjects(Object object, AnotherObject anotherObject)
{
    {
        var someData = GetSomeData(object.Data);
        var anotherData = GetAnotherData();
        var convertedData = ConvertData(someData, anotherData);
        object.Data = convertedData;
    }
    {
        var someData = GetSomeData(anotherObject.Data);
        var anotherData = GetAnotherData();
        var convertedData = ConvertData(someData, anotherData);
        anotherObject.Data = convertedData;
    }
}
```
It is ugly.
With `override` keyword
```
void ChangeObjects(Object object, AnotherObject anotherObject)
{
    var someData = GetSomeData(object.Data);
    var anotherData = GetAnotherData();
    var convertedData = ConvertData(someData, anotherData);
    object.Data = convertedData;
   
    override var someData = GetSomeData(anotherObject.Data);
    override var anotherData = GetAnotherData();
    override var convertedData = ConvertData(someData, anotherData);
    anotherObject.Data = convertedData;
}
```

**Comment by orthoxerox** [comment]
I find the blocks much less ugly and quicker to type. They also preserve the symmetry of the repeating blocks of code more that removing `var` or adding `override` do.

**Comment by MgSam** [comment]
If you find yourself truly needing to re-declare the same variable over and over again, perhaps you should re-evaluate the way you've designed your methods rather than ask for a new language feature.

**Comment by aluanhaddad** [comment]
Looks like extract method is what's needed here.

**Comment by dsaf** [comment]
To be fair, this is better than simply repurposing a variable in current language. But I agree with the above comments.

> It is ugly.

Uglier than ```using```? Imagine ```IDisposable``` constraint was dropped:

```csharp
using(var someData = GetSomeData(anotherObject.Data))
using(var anotherData = GetAnotherData()
using(var convertedData = ConvertData(someData, anotherData)
{
    anotherObject.Data = convertedData;
}
```

**Comment by orthoxerox** [comment]
@dsaf This looks a lot like `let` in Lisps. If we get immutable variables, we will be able to write it like this:

```c#
{
    let someData = GetSomeData(anotherObject.Data);
    let anotherData = GetAnotherData();
    let convertedData = ConvertData(someData, anotherData);
    anotherObject.Data = convertedData;
}
```

Yes, no way to pull the variables out of the block, but with some abuse of extension methods you might be able to write:

```c#
anotherObject.Data = 
from someData in GetSomeData(anotherObject.Data)
from anotherData in GetAnotherData()
select ConvertData(someData, anotherData)
```

**Comment by gafter** [comment]
@KalitaAlexey The C# language was designed with a number of scoping restrictions and constraints (like the "single definition rule") that prevent you from reusing names in a method body in a way that could possibly be confusing. This feature aims to take things in the opposite direction, requiring the reader to be aware of more context to understand the code. It seems to me this feature would most benefit code that exhibits the code smell of being far too long, and in which the programmer had difficulty thinking of appropriate names for variables.
