### ISSUE TITLE
List of Workspace/OOP/infrastructure simplifications we may be able to make within the Workspace

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#56763]
This is a issue i'd like us to use to keep track of potential simplifications that now may be possible to take in Roslyn due to larger divisional directions that simplify things for us.  

@tmat @jasonmalinowski @sharwell @mavasani  Please mention (or add directly) things you think we may be able to simplify (or jettison entirely) to improve our lives.

Note: this list is not intended to be in any sort of priority order:

1. Do we need ValueSource anymore?  IT was intended to allow us to abstract over values that might be thrown away or rehydrated.  However, in practice it generally means we just have no clear understanding of the lifetime of values, or the associated costs we might be incurring if they get thrown away and then rehydrated.  In a 64bit world can we consider removing entirely, and just allowing the GC and the OS VM system take over this role?  https://github.com/dotnet/roslyn/pull/68311
1. ~~Even if we don't do '1', can we consider removing ValueSource within the compilation tracker?  The general philosophy would be that once some system accessed a tree/model/compilation, we would presume it was needed and we woudl not throw it away.  We'd allow the GC to them collect older objects that were no longer reachable once all features moved forward to a new snapshot.~~  Done in https://github.com/dotnet/roslyn/pull/58425
1. ~~Do we need recoverable syntaxtrees, or can we just parse and just keep trees around as long as they were requested.  This is likely subsumed by '1' and '2', but we could consider only doing trees if the above are too broad in scope.  A/B test on this happening here https://exp.microsoft.com/a/feature/45353d53-e9b9-4179-a471-832d7f43d71a?workspaceId=a5766fee-9478-488b-9fc0-64d1ad72c290.~~  Done in https://github.com/dotnet/roslyn/pull/64739
1. ~~Can we remove the idea of the 'branch ID'?  No one is really certain what the purpose of this is.  In a snapshot/checmsummed world it also seems entirely unnecessary as all computed/cached data should always be valid against its originating snapshot.   Apocryphally i think this was related to diagnostics, and how we coudl compute them against random snapshots, but not know which snapshot to associate them against.  This could lead to breaking invariants by having some random branch store data that wasn't valid against the main branch.  Now that we have 'pull diagnostics' this may be entire unnecessary/undesirable.~~ BranchId removed in https://github.com/dotnet/roslyn/pull/63578
1. Do we need the TemporaryStorageSystem at all?  It's complex and has had (and continues to have https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1407329) extremely scary bugs with it related to both unsafe code and memory corruption.  It would be nice to not need to have a VM reinvention system if we can help it.  -- Additional data (10/10/22).  Measuring the impact of getting rid of this (specifically SerializableSourceText), does show a measurable impact on soluting syncing time.  Specifically, at least several seconds added consistently with large syncs (e.g. 25 seconds against 15), and many more costly syncs.  We may need to keep this around.

**Comment by jasonmalinowski** [comment]
I'd generally support all of these. And in case if @CyrusNajmabadi you weren't lumping it into the existing things above, whether we still need to be doing the recoverable syntax trees. We've had a pretty regular series of perf issues where the compiler does a pattern that causes us to keep recovering trees again and again.

For branch ID, I removed at least one of the uses in #55910, but alas it wasn't enough to get rid of everything. But that was one of the scarier bits IMHO since it wasn't just a caching concern I think.

**Comment by CyrusNajmabadi** [comment]
> you weren't lumping it into the existing things above, whether we still need to be doing the recoverable syntax trees. 

I'll make an explicit item for this.

**Comment by tmat** [comment]
@CyrusNajmabadi Do we have results of the A/B experiment? https://github.com/dotnet/roslyn/pull/56921

**Comment by CyrusNajmabadi** [comment]
Right now there's something wrong with teh A/B infrastructure that is leading to results being considered invalid by the A/B system itself.  I have meetings with the exp. team to walk me through how to resolve it :)

**Comment by tmat** [comment]
There might also be a problem in consuming the feature flag. Global options (including feature flags) are only available in-proc. If the service is running OOP it won't read the right value. See https://github.com/dotnet/roslyn/pull/56921/files#r720554617

**Comment by CyrusNajmabadi** [comment]
in OOP what value is read?  The default?

**Comment by tmat** [comment]
FeatureFlagPersister will bail since it does not have `IVsFeatureFlags` VS service: https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/FeatureFlagPersister.cs,29
So, yeah, I think you'll get the default value for the option.

**Comment by tmat** [comment]
Actually, the FeatureFlagPersister won't even get created since its provider is only exported in VS layer: https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Options/FeatureFlagPersisterProvider.cs,19

The same result either way.

**Comment by CyrusNajmabadi** [comment]
Yikes.... what a clusterF!

**Comment by tmat** [comment]
:(

**Comment by tmat** [comment]
I need to add throwing version of IGlobalOptionService exported in remote workspace to avoid errors like this.

**Comment by tmat** [comment]
We should go over "Concept-OOP" issues: https://github.com/dotnet/roslyn/issues?q=is%3Aopen+is%3Aissue+label%3AConcept-OOP

**Comment by CyrusNajmabadi** [comment]
2 and 5 are done.  A/B experiment on 3 going on here: https://exp.microsoft.com/a/feature/45353d53-e9b9-4179-a471-832d7f43d71a?progressionStageId=9276eabc-4378-498b-8f4e-600e0fbe133f&workspaceId=a5766fee-9478-488b-9fc0-64d1ad72c290

**Comment by CyrusNajmabadi** [comment]
Closing out as all this work was done.
