### ISSUE TITLE
Fixing namespace should not move to top of the file.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56773]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Fixing-namespace-should-not-move-to-top-/1539639)._

---
[severity:It's more difficult to complete my work]
I copy some code into Visual Studio 2022. Lot of namespace is missing. I fix them one by one. On every namespace fix it's goes to top of the file. Look like broken. 

It's require a fix.

---
#### Feedback Bot on 9/26/2021, 10:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/27/2021, 09:46 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this at all.  Can you provide an example file where you're seeing this?  A video/gif would also be helpful here.  Thanks!

**Comment by anirugu** [comment]
I raised this issue. The problem is when you copied code from somewhere and you started fixing namespace one by one, the cursor move to top of the file. 
If you have 10 missing namespace and you solved them by click on suggestion coming on there over the missing thing, it will move your cursor to top of file. This means I am scrolling to bottom 10 times.

I will try to send video explaining it better.

**Comment by CyrusNajmabadi** [comment]
> I will try to send video explaining it better.

Thanks. That would be helpful. I can't repro this currently. If you can provide an example file and pasted contents that would be useful. Thanks!
