### ISSUE TITLE
CS8620, CS8634 mis-firing on extension method invocation with implied generic type args

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CS8620-CS8634-mis-firing-on-extension-m/1534336)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.11]

```
git clone https://github.com/microsoft/vs-mef.git
cd vs-mef
git checkout 67750f0c7b2ada5880ad2f937560f4051af333fb
.\Microsoft.VisualStudio.Composition.sln
```

Open `src\Microsoft.VisualStudio.Composition\ExportProvider.cs` within VS.

**Expected**

No errors or warnings in the error list.

**Actual**

Two warnings appear in the error list.

Severity	| Code	| Description	| Project	| File	| Line	| Suppression State
--|--|--|--|--|--|--
Warning	| CS8634	| The type 'System.Collections.Generic.Dictionary<Microsoft.VisualStudio.Composition.Reflection.TypeRef, Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker>?' cannot be used as type parameter 'TValue' in the generic type or method 'Utilities.GetValueOrDefault<TKey, TValue>(IReadOnlyDictionary<TKey, TValue>, TKey, TValue?)'. Nullability of type argument 'System.Collections.Generic.Dictionary<Microsoft.VisualStudio.Composition.Reflection.TypeRef, Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker>?' doesn't match 'class' constraint.	|Microsoft.VisualStudio.Composition (net472), Microsoft.VisualStudio.Composition (netcoreapp3.1), Microsoft.VisualStudio.Composition (netstandard2.0)	| C:\git\MEF\src\Microsoft.VisualStudio.Composition\ExportProvider.cs	|994	| Active
Warning	| CS8620	| Argument of type 'ImmutableDictionary<string, Dictionary<TypeRef, ExportProvider.PartLifecycleTracker>>' cannot be used for parameter 'dictionary' of type 'IReadOnlyDictionary<string, Dictionary<TypeRef, ExportProvider.PartLifecycleTracker>?>' in 'Dictionary<TypeRef, PartLifecycleTracker>? Utilities.GetValueOrDefault<string, Dictionary<TypeRef, PartLifecycleTracker>?>(IReadOnlyDictionary<string, Dictionary<TypeRef, PartLifecycleTracker>?> dictionary, string key, Dictionary<TypeRef, PartLifecycleTracker>? defaultValue)' due to differences in the nullability of reference types.	|Microsoft.VisualStudio.Composition (net472), Microsoft.VisualStudio.Composition (netcoreapp3.1), Microsoft.VisualStudio.Composition (netstandard2.0)	| C:\git\MEF\src\Microsoft.VisualStudio.Composition\ExportProvider.cs	|994	| Active

When I explicitly specify the type arguments, the warnings go away:

```diff
-var sharingBoundary = this.sharedInstantiatedParts.GetValueOrDefault(sharingBoundaryName, null);
+var sharingBoundary = this.sharedInstantiatedParts.GetValueOrDefault<string, Dictionary<TypeRef, PartLifecycleTracker>>(sharingBoundaryName, null);
```

But then the language service suggests I remove the type arguments to "simplify" the line, but removing them brings those two warnings back.

---
#### Feedback Bot on 9/22/2021, 03:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jcouv** [comment]
Fix was merged for 17.0
