### ISSUE TITLE
Wrong value of optional arguments are passed using old COM interop libraries

### ISSUE THREAD

**Issue by disklosr** [dotnet/roslyn#5679]
A description of the problem and how to reproduce it are found in this Stackoverflow thread: http://stackoverflow.com/questions/32841800/why-do-optional-parameters-get-passed-wrong-values-in-visual-studio-2015

**Comment by jaredpar** [comment]
@tmat this looks like a duplicate of the boolean read bug.  Can you confirm?

Fix for context: https://github.com/dotnet/corefx/pull/2738

**Comment by tmat** [comment]
@jaredpar Yes, verified that the scenario described on SO works now. This has been fixed by https://github.com/dotnet/corefx/pull/2738.
