### ISSUE TITLE
Implementing auto-properties should not generate code that throws NotImplementedException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#56847]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Implementing-auto-properties-should-not-/1537411)._

---
[severity:It's more difficult to complete my work]
Given an interface like this:

```
public interface IName {
  string Name { get; set; }
}
```

and a class definition like this:

```
public class MyClass : IName { 

}
```

If I allow VS 2022 Preview 4.1 to automatically implement the interface, it results in the following:

```
public class MyClass : IName { 
  public string Name { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
}
``` 

Previous versions of Visual Studio implement the same property using automatic getters and setters:

```
public class MyClass : IName { 
  public string Name { get; set; }
}
```

This older behaviour is much more productive.

---
#### Feedback Bot on 9/23/2021, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is controlled by this option:

![image](https://user-images.githubusercontent.com/4564579/135320262-760d0cbc-3461-4a1b-9af8-3d7e7e9ae0cf.png)
