### ISSUE TITLE
Async lightbulb performance improvements 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#56843]
While investigating lightbulb perf, I identified the following performance improvements that can be done for async light bulb feature:

 - [x] `High` priority fixes: Currently, we only run the [compiler analyzer](https://sourceroslyn.io/#q=CompilerDiagnosticAnalyzer) for high priority code fixes (add using and merge conflict resolution). However, the shortcomings of the current analyzer API doesn't allow compiler analyzer to work in span-based mode for semantic diagnostics (see [here](https://github.com/dotnet/roslyn/blob/b88948f10a1085980df7080f0b765b1a8c614436/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs#L39-L42)), even though [SemanticModel APIs](https://github.com/dotnet/roslyn/blob/b88948f10a1085980df7080f0b765b1a8c614436/src/Compilers/Core/Portable/Compilation/SemanticModel.cs#L339-L365) for semantic diagnostics take an optional filter span. We can workaround this in the analyzer driver by special casing the compiler analyzer and threading in the [input filter span](https://github.com/dotnet/roslyn/blob/b88948f10a1085980df7080f0b765b1a8c614436/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L632-L639) to the `SemanticModelAnalysisContext`, thereby improving the performance for computing compiler diagnostics and populating the High priority code fixes in async light bulb.
 - [x] `Normal` priority fixes: Currently, all the analyzers that are not high-pri are added to the normal priority bucket and executed at once. We can further break down the normal priority bucket as follow:
    1. Normal: Analyzers that produce at least one fixable diagnostic, i.e. have a corresponding code fixer.
    2. Low: Analyzers without any fixable diagnostics, i.e. have no corresponding code fixer. These diagnostics will only have Suppression/Configuration quick actions, which are lower priority and always show up at the bottom of the light bulb.
 
    This new bucketing would allow us to reduce the number of analyzers that are executed in the Normal priority bucket and hence generate all the non-suppression/configuration code fixes faster in async light bulb.

**Comment by mavasani** [comment]
FYI @CyrusNajmabadi @sharwell @jinujoseph @vatsalyaagrawal 

I am planning to work on these improvements this week. Let me know your thoughts.

**Comment by CyrusNajmabadi** [comment]
I support all of this :-)

**Comment by mavasani** [comment]
This is now complete
