### ISSUE TITLE
Roslyn emits redundant non-taken conditional branch for Nullable<T> == comparison

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#56875]
## Version Used

Latest `main` from 29/9/21 (https://github.com/dotnet/roslyn/commit/f69cab304bd134515067ca42c2f672fc8642db69, on sharplab.io)

## Overview

Consider this snippet:

```csharp
static bool M(DateTime? time)
{
    return time == DateTime.MaxValue;
}
```

This is the resulting IL:

```csharp
.method assembly hidebysig static 
    bool '<<Main>$>g__M|0_0' (
        valuetype [System.Private.CoreLib]System.Nullable`1<valuetype [System.Private.CoreLib]System.DateTime> time
    ) cil managed 
{
    .custom instance void [System.Private.CoreLib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
        01 00 00 00
    )
    // Method begins at RVA 0x205c
    // Code size 44 (0x2c)
    .maxstack 2
    .locals init (
        [0] valuetype [System.Private.CoreLib]System.Nullable`1<valuetype [System.Private.CoreLib]System.DateTime>,
        [1] valuetype [System.Private.CoreLib]System.DateTime
    )

    IL_0000: ldarg.0
    IL_0001: stloc.0
    IL_0002: ldsfld valuetype [System.Private.CoreLib]System.DateTime [System.Private.CoreLib]System.DateTime::MaxValue
    IL_0007: stloc.1
    IL_0008: ldloca.s 0
    IL_000a: call instance bool valuetype [System.Private.CoreLib]System.Nullable`1<valuetype [System.Private.CoreLib]System.DateTime>::get_HasValue()
    IL_000f: brtrue.s IL_0013

    IL_0011: ldc.i4.0
    IL_0012: ret

    IL_0013: ldloca.s 0
    IL_0015: call instance bool valuetype [System.Private.CoreLib]System.Nullable`1<valuetype [System.Private.CoreLib]System.DateTime>::get_HasValue()
    IL_001a: brtrue.s IL_001e

    IL_001c: ldc.i4.1
    IL_001d: ret

    IL_001e: ldloca.s 0
    IL_0020: call instance !0 valuetype [System.Private.CoreLib]System.Nullable`1<valuetype [System.Private.CoreLib]System.DateTime>::GetValueOrDefault()
    IL_0025: ldloc.1
    IL_0026: call bool [System.Private.CoreLib]System.DateTime::op_Equality(valuetype [System.Private.CoreLib]System.DateTime, valuetype [System.Private.CoreLib]System.DateTime)
    IL_002b: ret
}
```

Note how at `IL_0013` to `IL_001e` there is a completely redundant conditional branch where `Nullable<T>.HasValue` is invoked again, and this time if it's `false`, the method returns with `true`. This is of course incorrect, but it doesn't affect the semantics of the method given that this branch will never be taken as it's right after the previous (correct) one. So it's not in fact a critical bug, but this still seems questionable and at the very least it results in unnecessary code size, making the JIT and especially the inliner do more work to optimize it properly. Looks like some dead branch didn't get tracked properly during lowering and was maintained during the emit phase? It'd be nice if Roslyn managed to drop this entirely in the future 😄

### Additional notes

This bug only seems to repro when the comparison is against a static property or field of some sort.
For instance, using `int?` and comparing against either a value or a constant (eg. `int.MaxValue`) works fine.
Using `IntPtr` and comparing against `IntPtr.Zero` instead presents the same issue as with `DateTime` and `DateTime.MaxValue`.

**Comment by jnyrup** [comment]
A workaround is to swap the operands of `==`, such that the nullable is on the RHS as [`LowerLiftedUserDefinedComparisonOperator`](https://github.com/dotnet/roslyn/blob/a51b65c86bb0f42a79c47798c10ad75d5c343f92/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs#L1161) uses the LHS to emit the second `HasValue` check.

I guess both `M` and `M2` below could be lowered to something equivalent to `M3` if we want/need to be conservative about not invoking a user-defined `==` operator unless necessary.

```cs
public bool M(DateTime? a, DateTime b) => a == b;

public bool M2(DateTime? a, DateTime b) => b == a;

public bool M3(DateTime? a, DateTime b) => a.HasValue && (a.GetValueOrDefault() == b);
```

[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgZgAIBnDKAVzAzoGEqBvKugXVp1gECLjoBZABQARAIYYYAFWwBbGAH468tHQVLVGkQEo6AXgB8Oi+ZEBuKv0HDR4qcTmKV6rTr0GPsbAZlYitjqOlIJ0zgKuYhKSNF6Gvtq6+t5GMKYW1vIAdAAS8gwAavK4LLkAZLV00kUA4jAYldUwAPJQsjAAZvIsuBjSoXYhUQC+QA==)

I noticed this well while tracking down an uncoverable branch in some code coverage results.
