### ISSUE TITLE
Make FixAllCodeActionContext.FixAllDiagnosticProvider public

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#5687]
To make a test that checks the correct behavior of fix all providers, you'd need to use a `FixAllContext`, which in its constructor requires a `FixAllContext.DiagnosticProvider`. Currently there is no public implementation available, so everyone has to implement their own, which most probably looks very close to the implementation of `FixAllCodeActionContext.FixAllDiagnosticProvider`

**Comment by sharwell** [comment]
I don't think that particular class will help much with the task of testing for the following reasons:

1. `FixAllDiagnosticProvider` doesn't really implement `DiagnosticProvider`. All of the implementation work remains before it can be used.
1. Neither of the diagnostic providers used by StyleCop Analyzers resembles that particular class. Of course this is only one example project, but we do have extensive testing of our fix all providers in place, and the availability of `FixAllDiagnosticProvider` would not have simplified anything.

**Comment by tvsonar** [comment]
@sharwell I checked out the `TestDiagnosticProvider` in StyleCop. It is different, but you could have also gone with the Roslyn implementation too. It doesn't really matter if you pass in a `Func` that filters the diagnostics, or if you pass in the diagnostics, and filter them inside the class. The former seems more generic, as the "instantiator" could provide the filtering. But in any case to me it seems that this class could come with a usable, out of the box implementation.

**Comment by CyrusNajmabadi** [comment]
No longer necessary now that we have an actual testing framework (which validates fixall).
