### ISSUE TITLE
C# LSP in Razor scenarios returns `null` completion results when typing quickly

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#56886]
**Version Used**: Latest

**Steps to Reproduce**:

1. Open a semi-large app & a semi-large Razor file (one that results in C# completion taking a bit longer)
2. Type `@` then dismiss completion
3. Next type `Da` quickly with the intent to get `DateTime` completions

**Expected Behavior**:
You get a C# completion list weaved with a Razor completion list
![image](https://user-images.githubusercontent.com/2008729/135529084-623a443a-4c36-4e4c-8e84-69d9dbf4aca3.png)

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2008729/135528965-a7e6a412-e803-48bd-bc3c-71d3c15e5f21.png)

**Notes**: 
Looks like 2 completion requests are coming through Razor for `D` and then one for `a`. Both requests end up returning a `null` completion result from C# LSP which then tells the platform to not request completion again. Therefore Razor LSP's completion items get provided but not C#'s because they returned the wrong response initially.

VSTS Issue associated: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1412792

/cc @dibarbet

**Comment by dibarbet** [comment]
Resolving as external - Roslyn is getting two completion requests for 'a' when we should get one for 'D' and one for 'a'.  Roslyn only returns items for the word start character, so for both requests for 'a' we return nothing.

Platform to investigate why they're sending two requests for 'a' in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1412811
