### ISSUE TITLE
Diagnostics reported from a source generator should not require rebuilding project(s) to be updated and should display red/green squiggles at the location of the diagnostic

### ISSUE THREAD

**Issue by thinker227** [dotnet/roslyn#56928]
**Version Used**:
16.11.0

**Steps to Reproduce**:
Report a diagnostic from a source generator using `GeneratorExecutionContext.ReportDiagnostic` where the `DiagnosticSeverity` is either `Warning` or `Error`.

**Expected Behavior**: 
Error/warning is created, displaying red/green squiggles underneath the code at the location of the diagnostic, when the condition for the diagnostic to trigger is met, and said error/warning is resolved when the condition is no longer met.

**Actual Behavior**:
A rebuild of the project(s) dependent on the source generator is required for introduced/resolved errors/warnings to be created/resolved. In addition, red/green squiggles do not display underneath the code at the location of the error/warning.

**Comment by CyrusNajmabadi** [comment]
@thinker227 can you please provide a repro source generator where this is happening?

**Comment by thinker227** [comment]
@CyrusNajmabadi https://github.com/thinker227/SourceGeneratorDiagnosticDemonstration
