### ISSUE TITLE
Update VSIX dependencies to support user installation of some VSIXes

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#5695]
Right now we ship 5 VSIXes as a part of the VS install:

1. Roslyn Language Services
2. Roslyn Expression Evaluators
3. Roslyn Interactive Components
4. Roslyn Interactive Language Services
5. Roslyn Telemetry

Some of these have dependencies between each other, which could cause problems when users try to build and install their local versions. We need to:

1. Verify that all stated dependencies are needed.
2. Remove any dependencies that we can to simplify deployment.

**Comment by amcasey** [comment]
@jmarolf Note that this one isn't closed. :)

**Comment by jmarolf** [comment]
Assigning to @jasonmalinowski  to verify
