### ISSUE TITLE
IOp api indicates conversion operation where none should exist.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#56953]
```c#
using System;
using System.Collections;
 
class C
{
    static void Main()
    {
        foreach (C x in new string[] { null })
        {
            Console.WriteLine(x == null);
        }
    }
 
    public static implicit operator C(string s)
    {
        return new C();
    }
}
```

There is an IConversionOp on `new string[] { null }` to System.Collection.IEnumerable.  This is not correct and there is no conversion to that type here.  That's important as this foreach does *not* call through `IEnumerable` (or use `.Cast<C>()`).  Instead, it directly calls into the array, and gets the individual string elements.  Being strongly typed, this will call through the implicit 'C' operator.  

This is relevant as part of https://github.com/dotnet/roslyn/pull/56932.  That's because we are comparing the IOp trees before/after and in teh after we have the same IConversionOperation (to IEnumerable) that we have when we have:

```c#
    static void Main()
    {
        foreach (C x in (IEnumerable) new string[] { null })
        {
            Console.WriteLine(x == null);
        }
    }
 
    public static implicit operator C(string s)
    {
        return new C();
    }
}
```

**Comment by 333fred** [comment]
The IOperation API is correctly representing the language specification here:

https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/statements.md#1395-the-foreach-statement
> If the type X of expression is an array type then there is an implicit reference conversion from X to the IEnumerable interface (since System.Array implements this interface). The collection type is the IEnumerable interface, the enumerator type is the IEnumerator interface and the iteration type is the element type of the array type X.

As such, I don't believe there is a bug here.
