### ISSUE TITLE
CS1729 code fix does not respect naming convention for records

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#56952]
**Version Used**: 4.0.0-4.21458.2 (2bfff7b9)

**Steps to Reproduce**:

````
new Test("repro"); // Use code fix here

record Test();
````

![image](https://user-images.githubusercontent.com/509220/135941909-f7e953cf-a69d-4ba3-b739-27cfed10093e.png)

**Expected Behavior**:

The new parameter name should follow the current naming convention (pascal case).

**Actual Behavior**:

The new parameter name does not follow the current naming convention, so I must apply the fix for the new suggestion (IDE1006)

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/c5713c64ee0c133eadb535f429104e89630afc11/src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs#L413-L414

I think the `capitalize` parameter in the call above should be tweaked.
