### ISSUE TITLE
CSharpMatchFolderAndNamespaceDiagnosticAnalyzer / IDE0130 gives false positive on files in project root

### ISSUE THREAD

**Issue by karl-sjogren** [dotnet/roslyn#56958]
**Version Used**: 

Microsoft.CodeAnalysis.CSharp.CodeStyle version 3.11.0

**Steps to Reproduce**:

1.  Start a new console project with and add a namespace to your Program.cs which matches the root namespace (ie the folder)
2. Add Microsoft.CodeAnalysis.CSharp.CodeStyle version 3.11.0 and enable IDE0130 as a warning
3. Build the project

**Expected Behavior**:

Everything builds with no warnings.

**Actual Behavior**:

A warning is issued about the namespace being wrong and the suggestion is the root namespace with an extra dot at the end.

> C:\code\Misc\IDE0130-bug\Program.cs(2,11): warning IDE0130: Namespace "IDE0130_bug" does not match folder structure, expected "IDE0130_bug." [C:\code\Misc\IDE10130-bug\IDE10130-bug.csproj]

Sample repo is available at https://github.com/karl-sjogren/IDE0130-bug with everything setup for VSCode.

**Comment by Youssef1313** [comment]
@ryzngard This is the one you already fixed?

**Comment by ryzngard** [comment]
Yes, this is fixed with https://github.com/dotnet/roslyn/pull/55424

Tagging @mavasani and @jmarolf to figure out where that fits in with NuGet releases :)
