### ISSUE TITLE
Definite assignment not recognized

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/roslyn#56975]
**C# 9.0 / C# 10.0**: 

While working on an ANTL Visitor I wrote this code:
```
public override VisitorResult VisitAssignmentOrProcCall([NotNull] AssignmentOrProcCallContext context)
{
    // ...
    bool hasExpList = context.actualParameters() is { } actualParameters && 
        actualParameters.expList() is { } expList;
    ExpressionContext[] expressions = hasExpList ? expList.expression() : null;
    //                                             ^^^^^^^ CS0165: Use of unassigned local variable 'expList'
    // ...
}
```

**Expected Behavior**: `expList` is definitely assigned when `hasExpList` is `true`. 

**Actual Behavior**: CS0165

**Further investigation:**
The problem seems to be the assignment of the Boolean result of the pattern matching to a temp. This temp does not carry the definite assignment info with it. It can be shown by this other example:
```
// Working example.
string x() => null;
void Use(string s) { }
if (x() is { } y) Use(y);
```
With the intermediate temp:
```
string x() => null;
void Use(string s) { }
bool result = x() is { } y;
if (result) Use(y); // <<< CS0165!
```

**Comment by kindermannhubert** [comment]
That's correct behavior.
'expList' is assigned only when 'context.actualParameters()' is not null - which does not have to be true.

**Comment by OJacot-Descombes** [comment]
@kindermannhubert Since both conditions are linked with `&&` this must be true. Otherwise `hasExpList` would be false. I also noted that this behaviour also occurs when using only one condition like `bool isYNotNull = x() is { } y; if (isYNotNull) Use(y);`

**Comment by kindermannhubert** [comment]
Oh, sorry, my mistake (overlooked 'hasExpList' condition).

**Comment by OJacot-Descombes** [comment]
Okay, then this would turn my "bug" into a feature request, I guess.
