### ISSUE TITLE
VisualStudioErrorReportingService.ShowErrorInfoForCodeFix doesn't handle Interactive

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5698]
If a code fix crashes in the Interactive window ```_documentTrackingService.GetActiveDocument()``` returns null in ```ShowErrorInfoForCodeFix``` and the Info Bar is never displayed.  As a result, the fix is globally disabled and cannot be re-enabled.

**Comment by amcasey** [comment]
FYI @dpoeschl

**Comment by amcasey** [comment]
FYI @ManishJayaswal @dpoeschl

**Comment by amcasey** [comment]
Oops, the second dpoeschl should have been @Pilchie.

**Comment by dpoeschl** [comment]
/cc: @heejaechang -- The error list will need to solve this problem as well, if/when fixes become invokable from there.

**Comment by dpoeschl** [comment]
Also /cc: @mavasani (we just discussed this offline).

**Comment by heejaechang** [comment]
yep.
