### ISSUE TITLE
Open generated file didn't go live again once the file was present again

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#56997]
Filing on behalf of @stephentoub:

If you create a project that's using the Regex generator, and you remove the attributes while the generated file is open, the open file was correctly given a banner saying the generator was no longer available. However, once the attributes were placed back, the file didn't update back to a live file again.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If this needs to be done for a partner, please assign to a milestone.
