### ISSUE TITLE
UnmanagedCallersOnly functions with ref parameters should be an error

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/roslyn#57025]
### Description

Test case:

```csharp
[System.Runtime.InteropServices.UnmanagedCallersOnly]
static void ScheduledAudioFileRegionCallback (ref int fileRegion)
{
}
```

Results in:

> * Assertion at /Users/runner/work/1/s/src/mono/mono/mini/aot-compiler.c:5142, condition `is_ok (error)' not met, function:add_wrappers, method blittable_unmanagedattribute.SceneDelegate:ScheduledAudioFileRegionCallback (int&) with UnmanagedCallersOnlyAttribute has non-blittable parameters or return type assembly:<unknown assembly> type:<unknown type> member:(null)

Complete test project: [blittable-unmanagedattribute-6a124aa.zip](https://github.com/dotnet/runtime/files/7299470/blittable-unmanagedattribute-6a124aa.zip)

Repro: download & extract & execute `dotnet build`
Binlog: [msbuild.binlog.zip](https://github.com/dotnet/runtime/files/7299472/msbuild.binlog.zip)

I'm guessing it's hitting this:

https://github.com/dotnet/runtime/blob/36229d9d3a5abcf161fbee3a8917dcbdd3070946/src/mono/mono/metadata/marshal.c#L3694-L3697

Note that the C# code is valid, because otherwise the C# compiler should've have compiled it successfully.

### Configuration

```
$ dotnet --version
6.0.100-rtm.21477.21
```

**Comment by wegylexy** [comment]
I depended on `in` to pass in by pointer. Now it's broken.

**Comment by jkotas** [comment]
> I depended on in to pass in by pointer. Now it's broken.

Did it work for you at runtime? The runtime should have been failing for this case.

**Comment by wegylexy** [comment]
> > I depended on in to pass in by pointer. Now it's broken.
> 
> Did it work for you at runtime? The runtime should have been failing for this case.

It is working as expected in production with 6.0.1 as I understood.

```cs
// native code invokes it with a pointer to `struct MyValueType`
[UnmanagedCallersOnly(EntryPoint = "Test")]
static void Test(in MyValueType value)
{
  var copiedValue = value;
  // copiedValue is exactly what is expected
}
```
In the new version, I have to use unsafe pointer.
```cs
[UnmanagedCallersOnly(EntryPoint = "Test")]
static unsafe void Test(MyValueType* value)
{
  var copiedValue = *value;
}
```
I'd expect `ref` and `out` to work similarly, just like `&refVar` in C++.

**Comment by jkotas** [comment]
> It is working as expected with NativeAOT.

It is a bug / TODO in NativeAOT.

**Comment by AaronRobinsonMSFT** [comment]
> ref and out probably don't make sense, but in should be kept supported.

@wegylexy The design of `UnmanagedCallersOnly` specifically called out no support for non-blittable arguments. The fact that by-refs aren't non-blittable wasn't properly conveyed to the Roslyn team and was therefore missed on the language side. The inability to use any by-ref value (i.e., `in`, `ref`, `out`) is therefore by-design. If you would like to see this relaxed it would be a new feature request. It is unlikely it would be relaxed though.

**Comment by wegylexy** [comment]
What about `DllImport`? It seems to pin and pass the pointer.
I thought `UnmanagedCallersOnly` wrap those params as native pointers into unsafe references like `Unsafe.AsRef<T>(void*)` does.

**Comment by jkoritzinsky** [comment]
The pinning that `DllImport` does is due to the fact that `in`, `ref`, and `out` are not blittable. There needs to be extra code emitted to pin the values before passing them to native code. One of the main goals of `UnmanagedCallersOnly` is that it does zero wrapping/conversion of any parameters or return values.

**Comment by xoofx** [comment]
Hey,

We are discovering this problem at Unity as some of our unit tests are now failing compiling by updating Roslyn. That could be quite a breaking change on our side.

Could someone explain exactly why having a ref arg is not considered as blittable as it is considered from the native side as a pure pointer and from managed side, it is still a pointer in a register?

Behind the scene for the pure codegen part, I don't see how the code could be different. So if it is not a codegen problem, what is it? GC tracking ref?

Or differently, what is the difference with doing:

```c#
[System.Runtime.InteropServices.UnmanagedCallersOnly]
static unsafe void ScheduledAudioFileRegionCallback (int* fileRegion)
{
    ActualScheduledAudioFileRegionCallback(ref *fileRegion);
}

static void ActualScheduledAudioFileRegionCallback (ref int fileRegion)
{
  // ...
}
```

cc: @jkotas, @tgjones

**Comment by AaronRobinsonMSFT** [comment]
@xoofx The issue is one of correctness not necessarily code-gen. The guarantees around `ref` values are such that typing an argument from a method that is specifically designed to be called by an unmanaged caller means there is nothing to say that a `nullptr` is being passed in. This makes usage of the `ref` dubious in this scenario. The expectation here would be for users to either confirm the input state is non-null and proceed or know the caller's intent and immediately convert to a `ref` as in the example above. Either way, we are expecting a user action to be explicit rather than providing a guarantee that isn't provably correct.

**Comment by wegylexy** [comment]
An exception to the correctness is the return reference of `Unsafe.NullRef<T>()` and that `Unsafe.IsNullRef<T>()` may return true.

**Comment by AaronRobinsonMSFT** [comment]
>An exception to the correctness is the return reference of Unsafe.NullRef<T>() and that Unsafe.IsNullRef<T>() may return true.

That's not really an exception. The use of anything in the `Unsafe` class is by-definition "unsafe" and it is therefore up to the user to do the right thing, not the compiler. That same logic holds true for this scenario, but since the user isn't creating the `ref` explicitly it can lead users to expect that the `ref` is compiler approved.

**Comment by xoofx** [comment]
> Either way, we are expecting a user action to be explicit rather than providing a guarantee that isn't provably correct.

Thank you, I understand. On our side, the native code is actually C# code that we native compile with our Burst compiler, so it is explicit for the user that if it's declared with a ref, it means that it's not null. But we should be able to workaround if with an IL postprocessing step (with have many others) that will rewrite it to what I described above, so at least we have a workaround, just a bit unfortunate that we have to do that, but I hope it will work on our side. 🙂
