### ISSUE TITLE
IDE Unit Tests are loading binaries from MSBuild Installation

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#5702]
Several of the IDE Unit Test assemblies are attempting to load binaries from the MSBuild installation rather than those that were just built (such as Microsoft.CodeAnalysis.dll).

This means that we are potentially not getting the coverage we should be and are also not testing the bits we should be testing.

Unit Test Assemblies Impacted:
- Roslyn.Services.Editor.UnitTests2.dll (4 Invalid Tests)
- Roslyn.Services.UnitTests.dll (136 Invalid Tests)
- Roslyn.VisualStudio.Services.UnitTests.dll (16 Invalid Tests)

All the failing tests need to be updated to use the Core Targets files and the binaries that are produced locally by the build.

**Comment by tannergooding** [comment]
FYI. @dotnet/mlangide

**Comment by Pilchie** [comment]
What Core Targets do you mean?

**Comment by rchande** [comment]
Can you list the tests?

**Comment by tannergooding** [comment]
@Pilchie:
* Microsoft.CSharp.Core.targets
* Microsoft.VisualBasic.Core.targets

Both of these are modifiable in the local build and can potentially have new breaking changes.

The full list of files (16 of them) which should be grabbed locally are:
* Microsoft.Build.Tasks.CodeAnalysis.dll
* Microsoft.CodeAnalysis.CSharp.dll
* Microsoft.CodeAnalysis.dll
* Microsoft.CodeAnalysis.VisualBasic.dll
* System.Collections.Immutable.dll
* System.Reflection.Metadata.dll
* csc.exe
* csc.exe.config
* csc.rsp
* vbc.exe
* vbc.exe.config
* vbc.rsp
* VBCSCompiler.exe
* VBCSCompiler.exe.config
* Microsoft.CSharp.Core.targets
* Microsoft.VisualBasic.Core.targets

**Comment by tannergooding** [comment]
@rchande, Working on it, I will be attaching logs shortly.

**Comment by DustinCampbell** [comment]
Is this still an issue? It's been sitting here awhile with no update. Moving to 1.3 for now, but I'd hate to keep pushing it down the road indefinitely if it's important.

**Comment by tannergooding** [comment]
@DustinCampbell, I don't believe this is an issue when you install Roslyn via the new deployment mechanism, but it is still an issue if installed via the legacy (pre-update 1) deployment mechanism, as we don't install a Compiler vsix to override the compiler binaries in MSBuild (we are still on the legacy deployment mechanism for our integration tests today).

**Comment by DustinCampbell** [comment]
@tannergooding -- makes sense, but is this really a bug then? It's not clear to me what work is expected for the IDE team? Could you clarify? If there's work for us, I'd like it to be crisp, and if there isn't I'd like to close the issue. :smile:

**Comment by tannergooding** [comment]
I think the bug can be moved off of IDE (@jasonmalinowski already provided a way to fix the original issue when he created the `Roslyn.Compilers.Extension.vsix`).

It still needs to stay on infrastructure however (FYI. @davkean). As someone needs to modify our Integration Test Runner to install the compiler extension during our legacy deployment step, to completely resolve the bug.

**Comment by DustinCampbell** [comment]
Sounds good -- I'm going to move it off @balajikris. I'll put it on you for now to sort out, but you can assign it out to whomever you deem appropriate.

Thanks for putting with my issue-OCD

**Comment by tannergooding** [comment]
Assigning to @davkean, so he can either place it on the backlog or assign to someone on the current @dotnet/roslyn-infrastructure rotation (this should literally be a one line change to `TestRunner.cs`).

**Comment by davkean** [comment]
It's not clear to me what "legacy" scenarios are.

**Comment by tannergooding** [comment]
There is the new deployment mechanism supported in Update 1 (which deploys the VSIXs during build) and the legacy mechanism (which our test runner is currently using due to some issues with the new mechanism) which deploy's VSIXs via our VSIX Installation Utility.

**Comment by davkean** [comment]
Okay, so by legacy, you mean what Jenkins is doing right now. ie Inside Jenkins we're testing against MSBuild's version of our bits in some cases?

**Comment by tannergooding** [comment]
yes, and that should be fixable by modifying the list of VSIXs to install so that it includes `Roslyn.Compilers.Extension.vsix`

**Comment by jasonmalinowski** [comment]
Bug is no longer relevant.
