### ISSUE TITLE
File scoped namespace prevents contained using statements from being collapsible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57032]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/File-scoped-namespace-prevents-contained/1546625)._

---
[severity:It bothers me. A fix would be nice]
In this C# code:
```csharp
using System;
using System.Linq;

namespace Foo;

public class Bar
{

}
```

The `using` statements can be collapsed in editor using the `[-]` button on the left side of the editor. If you reorganize the code to this:

```csharp
namespace Foo;

using System;
using System.Linq;

public class Bar
{

}
```

the `using`s are no longer collapsible.

---
#### Feedback Bot on 10/7/2021, 11:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Yup.  We should fix this.
