### ISSUE TITLE
Compiler Unit Test is loading binaries from MSBuild Installation

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#5703]
A single Compiler Unit Test is attempting to load binaries from the MSBuild installation rather than those that were just built (such as Microsoft.CodeAnalysis.dll).

This means that we are potentially not getting the coverage we should be and are also not testing the bits we should be testing.

Unit Test Assemblies Impacted:
* Roslyn.Compilers.CompilerServer.UnitTests.dll

All the failing tests need to be updated to use the Core Targets files and the binaries that are produced locally by the build.

**Comment by tannergooding** [comment]
FYI. @dotnet/roslyn-compiler

**Comment by jaredpar** [comment]
The tests which load MSBuild should likely just be removed.  I will look into this.

**Comment by jaredpar** [comment]
This should be fixed now.
