### ISSUE TITLE
Test plan for "params Span<T>"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57049]
Championed issue: https://github.com/dotnet/csharplang/issues/1757

## Compiler
- [ ] Nullability
- [ ] IOp/CFG
- [ ] Add to test plan
- [ ] overload resolution (preference between `ROS<T>`, `Span<T>`, etc.)

## Language design
- [ ] LDM: The rules for safety need to be reviewed. Current are unsafe if we want to free or re-use the allocated space from caller

**Comment by Aniobodo** [comment]
Is this coming with .NET 8?
From my point of view, this params of Span<T> is more important than all the published roadmaps of.NET 8.

**Comment by jcouv** [comment]
Closing as subsumed by https://github.com/dotnet/roslyn/issues/71137
