### ISSUE TITLE
Add TODO's for Code Violations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57055]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-TODOs-for-Code-Violations/1547762)._

---
When analyzing source code for issues, it would be really helpful if we could automatically add a TODO for issues that need to be fixed at a later date. 

For example, in the violation below, it could add a TODO like hits:

//TODO: Fix. ConfigurationSettings.AppSettings is obsolete: This method is obsolete, it has been replaced by System.Configuration.

<img width="364" alt="Bfa7467c58e93477d877c3f856101f894637692239113239571_ScreenGrab2" src="https://user-images.githubusercontent.com/1408396/137346828-fa2dc4c1-e596-4d53-b8f9-4370229d0d50.png">

---
#### Feedback Bot on 10/7/2021, 11:42 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by RealDotNetDave** [comment]
I see this has been moved. Is there any info you need from me since I submitted it?

**Comment by jmarolf** [comment]
@RealDotNetDave We discussed how we wanted to solve this in the design meeting. We think the best fix here is to let the Task List in VS automatically show suppressed items (with the option to filter or not include them at all if you want). That way developers can easily see all the suppressions in their solution at a glance. Would that solution be acceptable to you or are there some scenarios we are missing?

**Comment by timheuer** [comment]
Scope creep :-) -- could we do some issue integration as well? -- suppress and add GH issue (if a GH repo).  I suppose I wonder if this could/should also just be done from error/warnings list as well.

**Comment by jmarolf** [comment]
> could we do some issue integration as well?

Hesitant to fall into the nearly-endless pit that is defect management :). We should certainly ensure that what we do doesn't block scenarios like this but the correct fix to start with imho is to just show `#pragma //TODD` in the Task List.

SonarQube, for example, has a rather [intricate](https://docs.sonarqube.org/latest/user-guide/issues/) defect management strategy. I would prefer it if someone from the defect management space came to us and told us what APIs they need vs. us speculating.  I think the nearest effort to us org-wise is https://lgtm.com/ and github's [depandabot alerts](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies). We should reach out and see if those teams are looking to integrate more directly with the IDE/Editor.

**Comment by CyrusNajmabadi** [comment]
CLosing due to lack of feedback.
