### ISSUE TITLE
Add project reference should handle multi-targeting projects better

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#57090]
**Version Used**: Version 17.0.0 Preview 4.1

**Steps to Reproduce**:

1. Create a new class library and make it multi-target two frameworks, say net472 and net6.0.
2. Create a new console app and make it multi-target the same things.
3. In the console app, write Class1 and invoke the fix:

**Expected Behavior**:

We show one "add reference to" entry.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/201340/136860448-84943d00-9d5b-43bd-b8ae-067541f698d4.png)

Note that picking either of the "add reference to" will actually do the same thing, since we ultimately add the same project reference entry to the file.

This might be easy enough to fix just by deduping multiple projects to the same by file name in this case.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
