### ISSUE TITLE
Proposal: Library method for converting string to/from byte [] (without explicit encoding)

### ISSUE THREAD

**Issue by sashas79** [dotnet/roslyn#571]
public static byte[] ToBytes(this string str)
        {
            byte[] bytes = new byte[str.Length * sizeof(char)];

            Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);

            return bytes;
        }

        public static string FromBytes(this byte[] bytes)
        {
            char[] chars = new char[bytes.Length / sizeof(char)];

            Buffer.BlockCopy(bytes, 0, chars, 0, bytes.Length);

            return new string(chars);
        }

**Comment by khellang** [comment]
I thinks this should be filed over at https://github.com/dotnet/corefx :smile:

**Comment by HugoRoss** [comment]
And this implementation does only work on the same machine as the processors of different machines may have different endianess and therefore procude different byte-arrays by the same given string.

**Comment by erik-kallen** [comment]
Why? It seems clearer to me to explicitly state that you want UTF-16. When could this method possibly be useful (other than to save you from typing ```Encoding.Utf16```, which does not seem like a compelling use case to me)?

**Comment by HugoRoss** [comment]
The issue arises when converting a Int16 (a Char is kind of an Int16) into 2 bytes. On one processor the letter "A" is converted to "0041" and on another to "4100". If you read/write it on the same machine there is no problem, but if you open it on another machine it might result in a different string.

**Comment by gafter** [comment]
Please take to https://github.com/dotnet/corefx
