### ISSUE TITLE
Add missing binaries for version stamping by compiler

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57107]
We've added a version stamping feature to the compiler (PR https://github.com/dotnet/roslyn/pull/56759) but some binaries are missing to light it up.
Our plan is to add preview binaries first, then add RTM binaries when they become available in November.

**Comment by jaredpar** [comment]
@tmat is this all merged now such that we can close this otu?

**Comment by tmat** [comment]
@jaredpar  Not sure. I haven't seen response on the email thread with C++ and I was oof in November. @jcouv did you end up updating the DSRN package?

**Comment by jaredpar** [comment]
Closing as this is completed now.
