### ISSUE TITLE
Go To Base/Implementation should be more flexible when signatures do not match

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#57110]
Currently Go To Base invoked on the override does not find the base method when their signatures do not match exactly. 
It would be useful if the feature still worked, finding approximate match (e.g. by name) when they don't, similarly to FAR.

```C#
class C
{
    public virtual void F(bool x)
    {
    }
}

class D : C
{
    public override void F(int x)
    {
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Note: we entirely use the compiler here.  We go directly to the symbol model to answer this.  If we wanted to support this it would be nice if it were through compiler error tolerance.

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community pr here.
