### ISSUE TITLE
refactoring: invert condition for int? comparison errs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/refactoring:-invert-condition-for-int-c/1551034)._

---
[severity:It bothers me. A fix would be nice]
The condition:
```
string? text = null;
if (text?.Length > 128) { /* not null, and longer than 128 chars */ }
else { /* null or not too long */ }
```
is inverted as not nullable, which is semantically incorrect:
```
string? text = null;
if ((text?.Length) <= 128) { /* not null, and not longer than 128 chars */ }
else { /* null or longer than 128 chars */ }
```
The conversion should be:
```
string? text = null;
if (!(text?.Length > 128)) { /* null, or not longer than 128 chars */ }
// or expanded: (text == null || text.Length <= 128)
else { /* not null, and longer than 128 chars */ }
```
I guess this error has alwas been there, I just realized it now.

---
#### Feedback Bot on 10/12/2021, 08:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/13/2021, 09:35 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Not repro.  Looks like this was fixed.  I get:

![image](https://user-images.githubusercontent.com/4564579/198381520-90738b2f-1271-449f-a97e-983482080aff.png)
