### ISSUE TITLE
BackgroundAnalysisScope enhancements

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#57146]
Currently, [BackgroundAnalysisScope](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/Portable/SolutionCrawler/BackgroundAnalysisScope.cs) has three possible scopes that affects how analyzers and code fixes run in the IDE:
 
1. `ActiveFile` or `CurrentDocument`: Runs analyzers and compiler diagnostics only on currently active document
2. `OpenFiles` or `OpenDocuments` (_default scope_): Runs analyzers and compiler diagnostics on all open documents
3. `FullSolution` or `EntireSolution`: Runs analyzers and compiler diagnostics on all documents and projects in the entire solution

NOTE: Code refactorings are not affected by this scope setting, they are always available for currently active line regardless of the current background analysis scope.

We are proposing following enhancements to the scopes:
1. **Add a new analysis scope `None`** with the following semantics:
   1. All analyzers and corresponding code fixes are disabled on all documents
   2. Compiler diagnostics and corresponding code fixes are enabled on all open documents
   
   This scope gives a "compiler diagnostics only" editing experience, where the user intends to just get their code in a working/compilable state. No IDE code style suggestions or code quality diagnostics/fixes are provided in this mode, which should significantly improve the IDE responsiveness and performance while typing. Related issues: https://github.com/dotnet/roslyn/issues/24513 and https://github.com/dotnet/roslyn/issues/38429

2. **Change the semantics of `ActiveFile` or `CurrentDocument` scope** so that compiler diagnostics are enabled on all opened documents instead of just the current document, while all the analyzers continue to run just on the currently active document. Primary motivation for this change to make this scope more usable. It is pretty likely that user making top level changes to the current document, such as method signature changes, affects the compiler diagnostics in other documents, such as at all call sites, and we want to automatically refresh the error list with latest compiler diagnostics without requiring the user to open each affected document to get up-to-date compiler diagnostics. There is also a secondary motivation for this change, which is mentioned below.

3. **Make `ActiveFile` or `CurrentDocument` the default background analysis scope**. With the semantic change to this scope mentioned above, we feel that this is the most appropriate analysis scope for best editing experience with optimum IDE performance characteristics. We plan to first roll out this change to our internal team members for dogfooding, and subsequently roll it out to everyone in Dev17.1

**Comment by CyrusNajmabadi** [comment]
> which should significantly improve the IDE responsiveness and performance while typing.

This past should not be true. Ide responsiveness and performance should be unaffected by analyzers. If that's not the case, we have a problem.
