### ISSUE TITLE
Proposal: Record applied/cancelled status of code action dialogs in telemetry

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/roslyn#57147]
I've been looking through code action telemetry, hoping to answer questions about the value of any given code action. One thing I am specifically interested in is which code actions that trigger dialogs are most/least helpful. My motivation is prioritizing which missing dialogs to implement first in VSMac (and which might benefit from another design pass).

However, I have learned that the editor does not actually record telemetry on whether a code action dialog was applied or cancelled. There is a `CanceledAfterInvoked` property, but it refers to the ThreadedWaitDialog being cancelled, not the Roslyn code action dialog.

In 17.0 and earlier, it would be conceivable to return a dialog result to the editor's LightBulbSession (via `ISuggestedAction3.Invoke`) so that this information could be recorded. But in Roslyn `main`, this is no longer possible because [invoking the code action returns back to the editor immediately](https://github.com/dotnet/roslyn/blob/4e381be1f36d9679c4045437007844a31fab1442/src/EditorFeatures/Core.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs#L104-L109).

**Therefore it seems like the way forward would be for Roslyn to submit its own telemetry for these dialogs.**

Looking at `SuggestedAction` in Roslyn, there does appear to be some logging of `FunctionId.CodeFixes_ApplyChanges`, but I don't see how that would pick up info about the dialog result. If this information is already being logged somewhere, I'd love to hear about it! Otherwise, I'm open to suggestions on how best to address this apparent shortcoming in our telemetry.

/cc @CyrusNajmabadi @AmadeusW

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
