### ISSUE TITLE
Array Initializer into class property throws null reference exception

### ISSUE THREAD

**Issue by timelost** [dotnet/roslyn#57153]
**Version Used**: 
.net 5.0 VS 2019 Version 16.11.4
.net 6.0 latest VS 2022
**Steps to Reproduce**:
Compile the attached file.

**Expected Behavior**:
Either the compile should fail or the runtime should accept the program.

**Actual Behavior**:
Throws a null reference exception

[BugTest.zip](https://github.com/dotnet/roslyn/files/7348387/BugTest.zip)

```
using System.Collections.Generic;

namespace BugTest
{
    class Foo
    {
        public List<int> Bar { get; set; }
    }

    class AlsoFoo
    {
        public IList<int> Bar { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            //these work
            new Foo { Bar = new List<int> { 1 } };
            new AlsoFoo { Bar = new int[] { 1 } };

            // Both of these will die
            new Foo { Bar = { 1 } }; // type mismatch
            new AlsoFoo { Bar = { 1 } };
        }
    }
}
```

**Comment by jcouv** [comment]
This is by-design. Here's the relevant section of the [spec](https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#collection-initializers):
> For each specified element in order, the collection initializer invokes an Add method on the target object with the expression list of the element initializer as argument list, applying normal member lookup and overload resolution for each invocation. Thus, the collection object must have an applicable instance or extension method with the name Add for each element initializer.

In your example, the initializer `= { 1 }` will convert to `Bar.Add(1)`, but `Bar` returned `null` so that throws an exception.

It provides an example to make that work:
```
public class Contact
{
    string name;
    List<string> phoneNumbers = new List<string>(); // note the instantiation happens here

    public string Name { get { return name; } set { name = value; } }

    public List<string> PhoneNumbers { get { return phoneNumbers; } }
}
var contacts = new List<Contact> {
    new Contact {
        Name = "Chris Smith",
        PhoneNumbers = { "206-555-0101", "425-882-8080" }
    },
    new Contact {
        Name = "Bob Harris",
        PhoneNumbers = { "650-555-0199" }
    }
};
```
