### ISSUE TITLE
VS 2022 - Add new class is always internal

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57174]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022---Add-new-class-is-always-intern/1534905)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17 Preview 3]
In VS 2022, in a lib project, add new class always adds the class with the internal keyword.
In older versions the class is added as public or with no keyword at all.

Is this a expected behavior and can this be changed?

Best regards
Michael

---
#### Feedback Bot on 9/22/2021, 01:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/22/2021, 10:06 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by jmarolf** [comment]
There is still something wrong here: The class template [explicitly specifies](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsproject/Templates/Windows/CSharp/ProjectTemplates/ClassLibrary/class1.cs&_a=contents&version=GBmain) public. The document formatting service should not be changing that.

**Comment by MichaelPruefer** [comment]
But how can i change the added modifiert to be e.g. public instead of internal?

**Comment by davidwengier** [comment]
There is currently no function in Roslyn to do that, so the only "automatic" way for this to happen would be if you made your own item template for it.

**Comment by MichaelPruefer** [comment]
"There is currently no function in Roslyn to do that, so the only "automatic" way for this to happen would be if you made your own item template for it."

So the only way for me to fix this, is to update the item template in "%programfiles%\Microsoft Visual Studio\2022\Professional\Common7\IDE\ItemTemplates\CSharp\Code\1033\Class", as this is used for the context menu "Add/Class" ?

**Comment by davidwengier** [comment]
You could do that, or you can create your own template, perhaps for "Public Class" and it can show up in the New Item dialog: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2022

**Comment by MichaelPruefer** [comment]
> 
> 
> You could do that, or you can create your own template, perhaps for "Public Class" and it can show up in the New Item dialog: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2022

Oh cool, i did not know that, thank you :)

**Comment by BowserKingKoopa** [comment]
This is where I ended up five minutes after installing the new Visual Studio.  :)

**Comment by Andy-Corrigan** [comment]
> There is currently no function in Roslyn to do that, so the only "automatic" way for this to happen would be if you made your own item template for it.

I use CodeMaid to do a cleanup on save - is there any way to turn the Roslyn stuff off so I don't have to wade through changing/creating templates to avoid having to wipe out the internal flag every time I make a file?

**Comment by davidwengier** [comment]
> I use CodeMaid to do a cleanup on save - is there any way to turn the Roslyn stuff off so I don't have to wade through changing/creating templates to avoid having to wipe out the internal flag every time I make a file?

I'm not sure I follow what you mean by this. If you don't want the `internal` modifier added, you can adjust the "Require accessibility modifiers" rules, per [Sam's comment](https://github.com/dotnet/roslyn/issues/57174#issuecomment-944592391) above. Roslyn formatting follows the code style options in Visual Studio/.editorconfig

**Comment by Andy-Corrigan** [comment]
> > I use CodeMaid to do a cleanup on save - is there any way to turn the Roslyn stuff off so I don't have to wade through changing/creating templates to avoid having to wipe out the internal flag every time I make a file?
> 
> I'm not sure I follow what you mean by this. If you don't want the `internal` modifier added, you can adjust the "Require accessibility modifiers" rules, per [Sam's comment](https://github.com/dotnet/roslyn/issues/57174#issuecomment-944592391) above. Roslyn formatting follows the code style options in Visual Studio/.editorconfig

There seems to be about a dozen editorconfig files - from what I can see none of them have that setting. How do I get to what Sam sees in his comment?

**Comment by Andy-Corrigan** [comment]
> @Andy-Corrigan It's not clear to me what behavior you want to see when you create a file. Can you clarify?

I want Roslyn to not get involved at file creation - it should just follow the templates, whatever that template may be. For now, I've modified the templates because I can't find the editorconfig file that supposedly turns the settings on or off - but obviously that change isn't permanent once you factor in updating Visual Studio.

**Comment by sharwell** [comment]
> I want Roslyn to not get involved at file creation - it should just follow the templates, whatever that template may be

Based on the number of users who give _exactly the opposite_ feedback (it appears to be a >99%/<1% situation), this doesn't seem to be a viable request. Assuming Roslyn is involved in the file creation process, what action are you wanting it to take?

> For now, I've modified the templates because I can't find the editorconfig file that supposedly turns the settings on or off

The .editorconfig file is part of your solution. For example, the file for the current repository is here:
https://github.com/dotnet/roslyn/blob/main/.editorconfig

If your solution doesn't contain any configuration, the tools assume the project authors aren't particularly opinionated on the subject and will go with the defaults values for the current release. The new file creation features are designed so project authors are allowed to be opinionated about code style (previously it was not possible), and when that occurs files will be created to match those preferences.

**Comment by davidwengier** [comment]
> I can't find the editorconfig file that supposedly turns the settings on or off

For new the project creation scenario, the most reliable way to adjust settings is in Visual Stuid under Tools, Options, Text Editor, C#, Code Style. These settings will sync with your user profile so you should only have to set them once.

**Comment by Andy-Corrigan** [comment]
> > I want Roslyn to not get involved at file creation - it should just follow the templates, whatever that template may be
> 
> Based on the number of users who give _exactly the opposite_ feedback (it appears to be a >99%/<1% situation), this might not be a viable request. The goal is to instead have Roslyn be involved _and_ match expectations for the resulting code style. Assuming Roslyn is involved in the file creation process, what action are you wanting it to take?
> 
> > For now, I've modified the templates because I can't find the editorconfig file that supposedly turns the settings on or off
> 
> The .editorconfig file is part of your solution. For example, the file for the current repository is here:
> https://github.com/dotnet/roslyn/blob/main/.editorconfig
> 
> If your solution doesn't contain any configuration, the tools assume the project authors aren't particularly opinionated on the subject and will go with the defaults values for the current release. The new file creation features are designed so project authors are allowed to be opinionated about code style (previously it was not possible), and when that occurs files will be created to match those preferences.

Ahh, that'd explain why I couldn't find it in the program files - I thought there'd be a universal thing somewhere rather than a per project/solution thing. 

Truth be told, I wasn't aware that Roslyn was even a thing until this version of visual studio so it was a bit baffling when everything started becoming internal... Surely the time to get opinionated about the code style is there's actually code there? Whether a class is public/protected/internal should be decided by the code - maybe a more fitting feature might be some kind of tool that detects whether a class can be made less accessible when building the solution? 

That said, now I know where it's supposed to go, I'll create a editorconfig file and do it that way.

**Comment by johnottone** [comment]
I cant believe this issue is marked as "Closed". I mean really? You can't add a setting that allows users to set their preferred modifier on a new Class file addition. I am working with netstandard2.0 shared libraries for Xamarin, and it is so annoying that every time I add a new class i have to change it to "public". All I am saying, is there should be an option to allow users to set the preference for their new class modifier, no matter what version of Visual Studio, no matter what type of project. If a user wants their classes to be public, why not allow it. It's simply ridiculous for a user to implement a work-around for this.

**Comment by CyrusNajmabadi** [comment]
@johnottone .  Roslyn doesn't own the template here.
