### ISSUE TITLE
Constant string field data is duplicated when accessed from the same assembly

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#57185]
**Version Used**: VS2022 Preview 4.1

**Steps to Reproduce**:
```csharp
static class Foo
{
    private const string _bar = "ABC..."; // 1 MB string data

    private static char Bar(int i)
    {
        return _bar[i];
    }
}
```
**Expected Behavior**: ~1 MB assembly

**Actual Behavior**: ~2 MB assembly

Moving the constant inside the method prevents the issue but, strangely, bloats the PDB instead. Converting the constant to a static expression-bodied property seems to work as expected.

**Comment by jaredpar** [comment]
Believe this is an effect of how IL encodes constatns but will let @AlekseyTs, @333fred confirm

**Comment by tmat** [comment]
The PDB stores all constants so that the Expression Evaluator has access to them. 

In general, declaring large strings in source code is not recommended. Instead, store them in resource files.
