### ISSUE TITLE
API for IFunctionPointerInvocationOperation

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#57195]
## Background and Motivation

As described in #48082 the Operations-API is not usable today for function pointer invocations. This should be changed.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Operations
{
+    public interface IFunctionPointerInvocationOperation : IOperation
+    {
+        IOperation InvokedPointer { get; }
+        ImmutableArray<IArgumentOperation> Arguments { get; }
+    }
}

namespace Microsoft.CodeAnalysis
{
    public enum OperationKind
    {
+        FunctionPointerInvocation = 0x72,
    }
}

```

## Usage Examples

See #48082

## Alternative Designs

It would be possible to reuse the IInvocationOperation to represent the function pointer operation. But the usage of this interface has some drawbacks.
For example `IsVirtual` does not apply to function pointer invocations. In addition we can not model the invoked pointer appropriate.
Therefore we propose the new API.

We could add a property to the interface for retrieving the function pointer method signature as well, rather than requiring the user to do `((IFunctionPointerTypeSymbol)invPointerOperation.InvokedPointer.Type).Signature` to get access to the pointer type signature. In addition we could add a property for the function pointer type. But both features could be implemented via extension method, too.

## Risks

No knwon risk.

**Comment by bernd5** [comment]
"InvokedPointer" sounds good for me as well 👍

**Comment by bernd5** [comment]
I updated the implementation PR and the API Proposal.

**Comment by bernd5** [comment]
we need to use 78 because 72 is already used by interpolated strings...

**Comment by 333fred** [comment]
The number doesn't really matter, as long as it doesn't change after it's checked in :)

**Comment by bernd5** [comment]
It is now implemented and merged into main
