### ISSUE TITLE
NuGet Microsoft.CodeAnalysis.Features package missing

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#572]
Hi guys,

I would just like to raise issue of not having Microsoft.CodeAnalysis.Features.Common, Microsoft.CodeAnalysis.Features.CSharp and Microsoft.CodeAnalysis.Features.VisualBasic packages available on NuGet.org(this kinda make sense since source code wasn't public at time of -beta2) or on https://www.myget.org/gallery/roslyn-nightly feed.

This packages don't depend on VisualStudio dependencies and have a lot of great features([read folder names](https://github.com/dotnet/roslyn/tree/master/src/Features/Core))

It's OK even if everything is internal we got used to use reflection already anyway ;)

Fingers crossed,
David

**Comment by davidfowl** [comment]
+1

**Comment by AbubakerB** [comment]
:+1: much needed!

**Comment by sayedihashimi** [comment]
This would help OmniSharp a great deal, any update here?

**Comment by Pilchie** [comment]
Focused on short term deliverables right now, but will hopefully get to it soon.

**Comment by Pilchie** [comment]
All you people who have weighed in on this - what do you think should happen to the `Microsoft.CodeAnalysis` metapackage?  Should it depend on the C# and VB packages for `Features`, or stay as it is?

Tag @agocke.

**Comment by DavidKarlas** [comment]
Depends on what is goal of `Microsoft.CodeAnalysis` package... I think advanced users never use it, instead they "cherry-pick" only packages they need to minimize number/size of packages...

I guess for new users who add `Microsoft.CodeAnalysis` to their project... I think give them as much API as possible so they discover it via code completion. Also fact that .Workspaces is part of `Microsoft.CodeAnalysis` makes another argument to add .Features to it... When their project becomes more mature they will realize they can reduce size by changing packages and remove .Features, VB/C#, .Workaspaces...

**Comment by davidfowl** [comment]
Stay as is.

**Comment by agocke** [comment]
I agree with @DavidKarlas on who uses `Microsoft.CodeAnalysis` -- it's a catch-all bucket for everything Roslyn-related and most people would probably prefer to specify their exact dependencies once they know what they're doing. So, since it's just a grab bag for everything it might as well contain references to .Features.

**Comment by AbubakerB** [comment]
IMO, I'd have to say, leave it as it is. I'd prefer to opt-in to what i need rather than getting everything when i only need one thing then removing everything else.
I mean if people need something, they'll find what they need --- that's what brought us all here in the first place, right?
Features is nothing more than just that -- features. I think ```Microsoft.CodeAnalysis``` shouldn't depend on it. :)

**Comment by DavidKarlas** [comment]
imho... by this logic .Workspaces can be removed from `Microsoft.CodeAnalysis` since very little amount of users use it(mostly just IDEs)... same goes for VB :)(sorry couldn't resist). As I said... it depends on what is goal of `Microsoft.CodeAnalysis`...

Maybe `Microsoft.CodeAnalysis` should be killed(removed from NuGet.org) :) but that is a bit off topic :)

**Comment by nosami** [comment]
I have the signed dll that comes with VS packaged on a personal myget feed. Am I allowed to distribute this while waiting for the official feed?

**Comment by agocke** [comment]
Checked into stabilization as 1488673. Will have to wait for a new build to succeed for the packages to appear on MyGet.

**Comment by agocke** [comment]
Nevermind, we've actually had a build. :) https://www.myget.org/feed/roslyn-nightly/package/nuget/Microsoft.CodeAnalysis.CSharp.Features

**Comment by nosami** [comment]
Great news. Thanks!
