### ISSUE TITLE
Call Hierarchy window shows duplicates for multiple target frameworks

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57202]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Call-Hierarchy-window-shows-duplicates-f/1554725)._

---
I am working on a very cross-platform solution -- targeting .NET Standard, .NET Framework, .NET 5, UWP, Xamarin.Android, and Xamarin.iOS.  The "Call Hierarchy" currently shows a duplicate call for each target framework, at each layer of the hierarchy.  This makes the total number of calls explode exponentially (e.g. 6 for each call on the first layer, 36 on the next, 216 on the next, etc).  This makes the Call Hierarchy window practically unusable.

I would really like to see multiple target frameworks folded together, the same way "References" window has been doing since 2022 Preview 2 (see https://github.com/dotnet/roslyn/issues/16587).

---
#### Feedback Bot on 10/15/2021, 00:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing duet o lack of feedback
