### ISSUE TITLE
Provide a shortcut for navigation to base types

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn#57236]
I love the new glyphs in the margin for base types/interfaces, but it seems there is no shortcut to invoke the menu. This requires me to use the mouse. I'd prefer having a keyboard-centric way to interact with this UI.

![Go to Base](https://user-images.githubusercontent.com/5169960/137973520-ed377d86-95cf-4814-8d0f-d197ce443235.png)

**Comment by Cosifne** [comment]
A duplicate of https://github.com/dotnet/roslyn/issues/53373
