### ISSUE TITLE
Formatting of list-patterns on multiple lines is incorrect

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57244]
This issue is referenced in tests from PR https://github.com/dotnet/roslyn/pull/53850

Relates to test plan https://github.com/dotnet/roslyn/issues/51289

**Comment by jcouv** [comment]
@jinujoseph I'm afraid this issue needs attention from someone with a bit more expertise. I tried to fix this today but was unable to.

**Comment by sharwell** [comment]
@jcouv I looked at the linked PR and wasn't able to figure out what the request here is.

**Comment by davidwengier** [comment]
> @jinujoseph I'm afraid this issue needs attention from someone with a bit more expertise. I tried to fix this today but was unable to.

Good news, its been assigned to me.

Bad news, I've literally never touched or seen the C# formatter code 😛

**Comment by jcouv** [comment]
Thanks @davidwengier 
If that helps, I've been collecting notes from my previous forays. We can build on that and make it easier for next time.
https://github.com/dotnet/roslyn/blob/main/docs/wiki/Notes-on-formatting.md
