### ISSUE TITLE
[LSP] Always create lsp misc files and resolve rps regression

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#57243]
LSP misc files were created at all times, but caused an RPS regression due to using the default mef host services.  
The workspace was made optional in https://github.com/dotnet/roslyn/pull/56989

However we should be able to create an abstraction over the VS mef workspace services and provide that to the LSP server to resolve the regression.  This should also remove some small complications noted here - https://github.com/dotnet/roslyn/pull/57140/files#r731412296

**Comment by sharwell** [comment]
@dibarbet can you loop me in during the early solution planning here?
