### ISSUE TITLE
Compilers are unable to consume signatures with custom modifiers referencing constructed types.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#5725]
Here is an example of a method signature like this 
```
.method public hidebysig specialname instance class [mscorlib]System.ValueType modopt(valuetype [mscorlib]System.Nullable`1<bool>) modopt([mscorlib]System.Runtime.CompilerServices.IsBoxed) 
        get_OffScreenTransparentBackground() cil managed
```

The modifier that is causing the problem is ```modopt(valuetype [mscorlib]System.Nullable`1<bool>)```. Strictly speaking, it violates ECMA-335 specification. In particular, Section II.23.2.7 says:
```
The CMOD_OPT or CMOD_REQD is followed by a metadata token that indexes a row in the TypeDef table or
the TypeRef table.
```
However, in order to refer to a ```System.Nullable`1<bool>``` type, a row in the TypeSpec table should be used.

**Comment by AlekseyTs** [comment]
Ported from DevDiv 93819

**Comment by shiftkey** [comment]
:eyes:

**Comment by AlekseyTs** [comment]
@VSadov please verify
