### ISSUE TITLE
Code inspection tool that lists all unused code

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57264]
Direct customer feedback copying here:

> Our team inherited a large code base and we needed to find and remove any dead code. The IDE will show us "0 references" for methods, properties, and classes, but only when you open the .cs file that contains the type. I couldn't find a way to list all of those 0-reference types and members in VS. Provide a code inspection tool that lists all of them.

@mavasani I know we have an analyzer for dead code analysis but it defaults to only show active files. Perhaps we can think of a design here where users can easily view unused code across their solution?

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
