### ISSUE TITLE
Add a lightbulb trough to the Interactive Window

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#5726]
Preferably, C# and VB only for now (i.e. not Python).

**Comment by amcasey** [comment]
FYI @ManishJayaswal @Pilchie

**Comment by Pilchie** [comment]
The core editor does this for normal text views.  @olegtk and @markw-t do you have guidance on how to get the lightbulb margin to show?

**Comment by olegtk** [comment]
It requires PredefinedTextViewRoles.Analyzable role.

**Comment by amcasey** [comment]
It looks like we already have that role:
```C#
                var roleSet = editorFactory.CreateTextViewRoleSet(
                    PredefinedTextViewRoles.Analyzable,
                    PredefinedTextViewRoles.Editable,
                    PredefinedTextViewRoles.Interactive,
                    PredefinedTextViewRoles.Zoomable,
                    PredefinedInteractiveTextViewRoles.InteractiveTextViewRole);

                TextView = factory.CreateTextView(window, _projectionBuffer, roleSet);
```

**Comment by amcasey** [comment]
I'm suddenly very suspicious of our options:
```C#
                options.SetOptionValue(DefaultTextViewHostOptions.OutliningMarginId, false);
                options.SetOptionValue(DefaultTextViewHostOptions.GlyphMarginId, false);
```

**Comment by amcasey** [comment]
I set all the margin options I could find and didn't see any change in the window's appearance:
```C#
options.SetOptionValue(DefaultTextViewHostOptions.LineNumberMarginId, true);
options.SetOptionValue(DefaultTextViewHostOptions.OutliningMarginId, true);
options.SetOptionValue(DefaultTextViewHostOptions.GlyphMarginId, true);
options.SetOptionValue(DefaultTextViewHostOptions.ShowErrorsOptionId, true);
options.SetOptionValue(DefaultTextViewHostOptions.SourceImageMarginEnabledOptionId, true);
```

Any thoughts, @olegtk?

**Comment by olegtk** [comment]
so you enabled all these margins and still get none of them (line numbers for example)? Then I'd look at how you are hosting the editor. Chances are you are only displaying bare text view, not a text view host (margins live in text view host).

**Comment by amcasey** [comment]
Got it. :)
```C#
options.SetOptionValue(DefaultTextViewHostOptions.SuggestionMarginId, true);
```

**Comment by dpoeschl** [comment]
+User Friendly, as this means keyboard-only users would have a much harder time figuring out to ```Ctrl+<dot>```, right @amcasey?

**Comment by amcasey** [comment]
Oops, forgot to close this.
