### ISSUE TITLE
Change access level

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57273]
Customer ask: 

>Have a refactoring that can change the accessibility of a member. If the type itself is internal and you want to make the member/property public then also make the type public. Similarly if you are making a public member internal, and nothing else expose it then make the type internal.

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:

We need more information about the underlying scenario. What is the user trying to do? Better understanding of the intent will help us design the correct solution.

**Comment by CyrusNajmabadi** [comment]
Closing as by design.
