### ISSUE TITLE
Delete a class enhancement 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57275]
Be able to delete a type and also remove all references to that type in a solution

**Comment by CyrusNajmabadi** [comment]
This needs to be much more fleshed out.  What would it mean to 'remove all references' to that type?   References can appear practically everywhere, mostly in non-optional contexts.  For example, if you have `List<TypeThatWasRemoved>` what does it mean to remove the reference to that type there.  Leaving `List<>` would be invalid.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
