### ISSUE TITLE
Add all missing using directives to a file

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57271]
We should add the capability to “add missing usings” to operate on the document scope and fix all missing using in the same way auto-import on copy-paste works.

🔗 Also requested in [AB#1746127](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1746127)

**Comment by ryzngard** [comment]
@mavasani is this covered by your fix all change?

**Comment by mavasani** [comment]
@ryzngard No it doesn't. As @sharwell mentioned, we would need to author a custom fix all provider for this use case.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
