### ISSUE TITLE
[In, Out] attributes removed from extern local function parameters

### ISSUE THREAD

**Issue by f2bo** [dotnet/roslyn#57325]
I notice that **[In, Out]** attributes are removed from a P/Invoke parameter when the method is declared as a local function. This causes problems when the changes need to be marshaled back to managed code. If I understand correctly from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions, extern local static functions are supported. Moreover, beginning with C# 9, any attributes on local function parameters should also be preserved.

**Version Used**: 
```
Visual Studio: 16.11.5
C# Tools:      3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
```

**Steps to Reproduce**:
1. Create a C or C++ DLL (_"SomeLibrary.dll"_) exporting a single method (_"SomeMethod"_).

  ```C++
typedef struct {
    bool enabled;
} State;

extern "C"
__declspec(dllexport) void SomeMethod(State* state_ptr)
{
    state_ptr->enabled = true;
}
  ```

2. Create a test project targetting .NET 5.

  ```C#
[TestClass]
public class SomeTests
{
    private const string TestLibraryName = "SomeLibrary";

    [StructLayout(LayoutKind.Sequential)]
    private class State
    {
        [MarshalAs(UnmanagedType.U1)]
        public bool Enabled;
    }

    [DllImport(TestLibraryName)]
    private static extern void SomeMethod([In, Out] State state);

    [TestMethod]
    public void TestOne()           // THIS TEST SUCCEEDS
    {
        State state = new();
        SomeMethod(state);
        Assert.IsTrue(state.Enabled);
    }

    [TestMethod]
    public void TestTwo()           // THIS TEST FAILS!!!
    {
        [DllImport(TestLibraryName)]
        static extern void SomeMethod([In, Out] State state);

        State state = new();
        SomeMethod(state);
        Assert.IsTrue(state.Enabled);
    }
}
  ```
3. Run the tests.

**Expected Behavior**:
Both tests should succeed.

**Actual Behavior**:
`TestTwo` method fails. Below is the generated code.  It seems that the compiler removes the **[In]** and **[Out]** attributes in the local function parameter of the `<TestTwo>g__SomeMethod|4_0` method, unlike the method declared at class scope with exactly the same signature where the attributes are preserved.
```C#
...
[DllImport("SomeLibrary")]
private static extern void SomeMethod([In][Out] State state);

public void TestOne()
{
    State state = new State();
    SomeMethod(state);
}

public void TestTwo()
{
    State state = new State();
    <TestTwo>g__SomeMethod|4_0(state);
}

[DllImport("SomeLibrary", EntryPoint = "SomeMethod")]
[CompilerGenerated]
internal static extern void <TestTwo>g__SomeMethod|4_0(State state);
...
```
Interestingly, other attributes seem to be preserved. For example, using a custom attribute:
```C#
public class XXXAttribute : Attribute
{
}
...
public void TestTwo() 
{
    [DllImport(TestLibraryName)]
    static extern void SomeMethod([In, Out, XXX] State state);
    ...
}
...
```
Generates the following code:
```C#
[DllImport("SomeLibrary", EntryPoint = "SomeMethod")]
[CompilerGenerated]
internal static extern void <TestTwo>g__SomeMethod|4_0([XXX] State state);
```

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)
