### ISSUE TITLE
Smart line break doesn't respect indent_style

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#57323]
**Version Used**: 

17.0 P4

**Steps to Reproduce**:

Use `indent_style = tab` and invoke smart line break using <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Expected Behavior**:

Curly braces are indented with tabs

**Actual Behavior**:

Indented with spaces

**Comment by sharwell** [comment]
I am not able to reproduce this issue in the IDE or in unit tests.

**Comment by Youssef1313** [comment]
@sharwell I haven't tried to minimally reproduce this. But I was consistently hitting this with https://github.com/unoplatform/uno/ at the time I opened the issue.

**Comment by sharwell** [comment]
@Youssef1313 I tried using the .editorconfig from that repository and still wasn't hitting the issue. Can you help narrow it down?

**Comment by sharwell** [comment]
I saw it reproduce once with the complete **.editorconfig** from that repository, but after that I couldn't repeat it and I wasn't ablet to narrow it down. 😦

**Comment by Youssef1313** [comment]
@sharwell Will recording a performance trace while it's happening help?

**Comment by sharwell** [comment]
I'm curious if you're still able to reproduce it if you change all the lines currently [formatted like this](https://github.com/unoplatform/uno/blob/ebdea1ff7373400af92a4aff408aacf4737adb7b/.editorconfig#L8) to instead use [this style](https://github.com/dotnet/roslyn/blob/867da8bb361131ca777e7d1af695b339a4f00e3c/.editorconfig#L18).

**Comment by Youssef1313** [comment]
@sharwell Yes. Still able to reproduce using `[*.{extension1,extension2,..,extensionN}]`

**Comment by Youssef1313** [comment]
https://user-images.githubusercontent.com/31348972/140381659-44192a19-ce3f-4dbb-9ada-d46e6a69b487.mp4


@sharwell I could narrow into a new console app
