### ISSUE TITLE
Unexpected behavior when compiling a project with an error from the roslyn analyzer

### ISSUE THREAD

**Issue by blowin** [dotnet/roslyn#57357]
Use net 6, I also checked it for net 5: 

I have 2 examples. Each of them has the same situation and the roslyn analyzer generates an error per line of code.

1) In the case when the Person type is in the same project with the code that uses it, an error from the analyzer stops the build with an error.

2) When Person is in another project (Lib project in my sample), then when using the type, the analyzer also gives an error, but the project is still built without errors.

Is this the correct compiler behavior?

Sample: https://github.com/blowin/RoslynErrorDemo

**Comment by blowin** [comment]
before building the project, I deleted the bin folder

**Comment by sharwell** [comment]
@blowin The compiler is operating out of the **obj** folder, so deleting the **bin** folder only caused the build to copy the existing assemblies from the **obj** folder to the **bin** folder. If you delete the **obj** folder, the compiler will be forced to run.
