### ISSUE TITLE
Code Style IDE0007 and IDE0008 ('var' preferences) should default to preferring var over explicit type for .Net Core 3.1 and .Net 5.0

### ISSUE THREAD

**Issue by jrdodds** [dotnet/roslyn#57359]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008 shows that the defaults for code style rules IDE0007 and IDE0008 are to prefer 'var' over an explicit type.

This works as documented for .Net Framework 4.8.

However with .Net Core 3.1 and with .Net 5.0 the defaults appear to be inverted. The use of var is flagged as a code style issue.

**Versions**
Tested in VS2019 with .Net Framework 4.8, .Net Core 3.1, and .Net 5.0.

**Steps to Reproduce**:

1. Create a project that targets .Net (e.g. .Net Core 3.1).
2. Make sure there is not any configuration file that may be altering the default behavior of the code style rules.
3. Add a variable declaration statement that uses 'var'.
4. Note that the IDE will flag the 'var' statement and direct to use an explicit type instead of 'var'.

**Expected Behavior**:
Based on the documentation and the behavior with .Net Framework, expected behavior is for 'var' to be preferred over an explicit type.

**Actual Behavior**:
The use of 'var' is flagged as a code style issue.

**Comment by ArturDorochowicz** [comment]
I'm seeing the same issue when using Microsoft.CodeAnalysis.CSharp.CodeStyle 4.0.1 package. I'm using VS2022 and .Net SDK 6.0.101.

**Comment by jrdodds** [comment]
I can't say that I understand the code but I'm guessing the issue is in lines [51](https://github.com/dotnet/roslyn/blob/7f889ac6595990547fc0eb7057ad96d171160512/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L51),  [57](https://github.com/dotnet/roslyn/blob/7f889ac6595990547fc0eb7057ad96d171160512/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L57), and [63](https://github.com/dotnet/roslyn/blob/7f889ac6595990547fc0eb7057ad96d171160512/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L63) of [CSharpCodeStyleOptions.cs](https://github.com/dotnet/roslyn/blob/7f889ac6595990547fc0eb7057ad96d171160512/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs). This seems to be where the expected defaults for the code style options are set. The lines noted are assigning the default value of the bool type (which is `false`) instead of `true` for the three rules for `var`.

**Comment by sharwell** [comment]
It's possible the default IDE profile are different from the fallback default values defined in Roslyn. When the code style analyzers are installed via the SDK or NuGet package, any values defined in the IDE are ignored and the defaults will come from Roslyn instead.

**Comment by jrdodds** [comment]
@sharwell The fallback default values are being set to `false` and that is incorrect according to the documentation and the behavior of .Net Framework.

**Comment by CyrusNajmabadi** [comment]
> to the documentation and the behavior of .Net Framework.

Which documentation are you referring to?

> should be changed to either

This would change teh behavior for all current customers who have not set these values themselves.  I don't think that's a viable path.  We should take the approach that our defaults stay what they are, but that we respect teh user's editorconfig (or VS settings) if present.

We def should never change defaults as that means any users who use defaults now see a difference (it is esp. bad if they work in a mixed environment where different tools have different defaults).

**Comment by ArturDorochowicz** [comment]
@CyrusNajmabadi The documentation states that "prefer var" is the default, while in reality it is not. The documentation is here:
- https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md?plain=1#L43 
- https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md?plain=1#L61
- https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md?plain=1#L79

Are you saying that "prefer var" should be the default (in which case the analyzers have a bug) or that "prefer explicit type" is the default (in which case the documentation has a bug)?

**Comment by jrdodds** [comment]
@CyrusNajmabadi If you go back and read my original description you will see the link to the documentation.

I understand how changing the defaults will cause differences. But I'm a 'current' customer and I'm writing and maintaining code for both .Net Framework and .Net Core and the code rule behavior is not consistent.

It seems that this is a bug in the analyzers and that the flags were flipped when implemented for .Net Core. The issue is not less of a bug because it has always existed in .Net Core.

The defaults for the code style rules are setting an example. The current values send the message that Microsoft doesn't want `var` to be used.

**Comment by ArturDorochowicz** [comment]
> The defaults for the code style rules are setting an example. The current values send the message that Microsoft doesn't want `var` to be used.

Let me also add that both IDE0007 Use implicit type and IDE0008 Use explicit type are enabled in all analysis modes (`All`, `Default`, `Minimum`, `Recommended`) (except for `None`) of the code style analyzers, so that message against 'var' is quite clear and that's really not expected.

**Comment by CyrusNajmabadi** [comment]
I don't believe we've ever tweaked these defaults on the roslyn side.  Is something else overriding things outside of our repo?  Looking at tehse files, they've these values for literal years... :-/

**Comment by jrdodds** [comment]
The values in the repo correspond with the incorrect values/behavior that I see when the analyzer runs for .Net Core.

Is this analyzer code known to be common between .Net Framework and .Net Core? If yes, then maybe there is something in .Net Framework that is overriding these values.

**Comment by jrdodds** [comment]
Hmm. It appears that the documentation was deemed to be in error and was "fixed".

Unless there was an explicit decision to change the policy on `var` and `var` is now considered a feature not to be used, dotnet/docs#28862 made the documentation fit the defect in the analyzers. There is still a defect in the analyzers.

> ... the message against 'var' is quite clear ...

If the defaults are discounted as potentially being the defect, then where is the message against `var` clearly expressed? You can't point to behavior that is potentially defective and say that is the proof that is it not a defect. That's like the old joke: "How many Microsoft software engineers does it take to change a light bulb? None. Darkness is declared the new standard."

I know there is a community that hates `var`. But is there official Microsoft documentation or guidance that essentially says "hey, we introduced `var` in C# version 3 and encouraged its use but now officially we have reconsidered its utility"?

The closest I have found is in "[Implicitly typed local variables](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#implicitly-typed-local-variables)" in "[Common C# Coding Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)". But the implication from that documentation is that `csharp_style_var_elsewhere` should default to `false` while `csharp_style_var_for_built_in_types` and `csharp_style_var_when_type_is_apparent` should default to `true`.

From my perspective:
- Defaulting to `false` for all three options is a defect.
- Defaulting to `true` for all three options is legacy. Users in a mixed environment of .Net Framework and .Net see a difference.
- Defaulting to `false` for `csharp_style_var_elsewhere` and `true` for `csharp_style_var_for_built_in_types` and `csharp_style_var_when_type_is_apparent` aligns with current coding convention guidance.

To keep the current defaults is an option and the case to do that is essentially: This is a defect that won't be fixed because there is too much 'water under the bridge'. The developers and teams that want to comply with the coding conventions need to customize the settings.

Other code analysis tools (e.g. Resharper, SonarQube) actually continuously update and modify their rules. Sometimes the rules change as a language feature becomes better understood. (Shocking, right?) For these other tools, continuous improvement in the code analysis rules is not held back by concerns for backward compatibility; continuous improvement is driven forward by the goal of enabling the production of better code. (I can summarize as the 'water under the bridge' argument doesn't 'hold water'.)

For this issue (57359), `csharp_style_var_for_built_in_types` and `csharp_style_var_when_type_is_apparent` should be changed to default to `true` to align with the current coding conventions.

**Comment by CyrusNajmabadi** [comment]
> But is there official Microsoft documentation or guidance that essentially says "hey, we introduced var in C# version 3 and encouraged its use but now officially we have reconsidered its utility"?

No.  If anything, the opposite.

**Comment by CyrusNajmabadi** [comment]
> For this issue (57359), csharp_style_var_for_built_in_types and csharp_style_var_when_type_is_apparent should be changed to default to true to align with the current coding conventions.

This will not happen as it would be massively destabilizing, and there is no motivation we have to do this.  If customers want those values to be on, they can explicitly choose to enable them if they believe that is the right set of values for their domain.

**Comment by jrdodds** [comment]
@CyrusNajmabadi Do I understand you correctly that `var` is important and encouraged (despite the code analysis rules) and its utility has not been reconsidered and nothing has changed (although the defaults are different between .NET Framework and .NET), but also (despite the rule defaults being inverted) there is no reason to change the defaults and the defaults will never be changed? Did I get that right?

**Comment by jrdodds** [comment]
@CyrusNajmabadi Do you concur that the following is a correct statement?

If a team wants to follow the current coding convention of using `var` "when the type of the variable is obvious from the right side of the assignment, or when the precise type is not important", then the default of `false` for `csharp_style_var_for_built_in_types` and `csharp_style_var_when_type_is_apparent` must be overridden.

**Comment by CyrusNajmabadi** [comment]
> and its utility has not been reconsidered and nothing has changed

Correct. 

> (although the defaults are different between .NET Framework and .NET),

I'm not sure what you're experiencing there. I've looked at the code and the defaults haven't been touched.

**Comment by CyrusNajmabadi** [comment]
> Do you concur that the following is a correct statement?

Teams must decide the development style they wish to follow.  If that style matches the defaults, then they don't need to do anything. But if it doesn't match the defaults, they'll need to choose the setting explicitly.  

This is a 1-time thing per top-level team folder.

**Comment by jrdodds** [comment]
> I'm not sure what you're experiencing there. I've looked at the code and the defaults haven't been touched.

There is no question that in a completely vanilla setup these rules behave differently in .NET Framework than in .NET. That has been established by others reproducing and corroborating the different behaviors. Perhaps the coded defaults you have looked at are effectively not used in .NET Framework?

**Comment by jrdodds** [comment]
> But if it doesn't match the defaults, they'll need to choose the setting explicitly.

Thanks. I'll take that as a diplomatic affirmative.

**Comment by CyrusNajmabadi** [comment]
> Thanks. I'll take that as a diplomatic affirmative.

Not certain what a 'diplomatic affirmative' is.  The above is just a description of how it is intended to work.  If your desired setup matches the defaults, you can choose to pick those up implicitly, or optionally state things explicitly.  If your desired setup does not match the defaults, you must be explicit about what you want.  

THe preferred way of doing this is through editorconfig files.  For monorepo style code, you can do that once, at the top of the repo.  If you have many repos though (and share no common root), you'd need to copy/link that editorconfig to the root of all places you want this setup.

**Comment by jrdodds** [comment]
Thanks @sharwell. Your recent comment gives me a better understanding.

Thanks @CyrusNajmabadi.

**Comment by jrdodds** [comment]
The IDE0007 and IDE0008 rules behave differently in .NET Framework and in .NET. The defaults in .NET do not align with the code conventions. Changes will not be made to the defaults. If the defaults are not the desired behavior, an .editorconfig file should be used to configure the desired behavior.
