### ISSUE TITLE
Generate Type should allow generation in linked files

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#5735]

**Comment by jmarolf** [comment]
related to #2855, but requires separate work.

**Comment by dpoeschl** [comment]
I believe this applies to "regular" linked files (not Shared Projects and not DNX), right @jmarolf?

**Comment by jmarolf** [comment]
@dpoeschl  correct

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of any customer feedback on this.
