### ISSUE TITLE
Navigation Bar shows wrong current method in VB project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57401]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Navigation-Bar-shows-wrong-current-metho/1558826)._

---
[regression]
See below picture.

Whenever the cursor is in a VB method that `Handles` an event (like below the `MedewerkerPlanningGridControl.DragOver` event), the Navigation Bar shows the next (normal) method as current method (in the screenshot `ShowVerrichtingDetails`)

! [image.png] (https://aka.ms/dc/image?name=B47ce83d2f7494f81bacca75356ab46f5637703102313884632_20211020-090350-image.png&tid=47ce83d2f7494f81bacca75356ab46f5637703102313884632)

---
#### Feedback Bot on 10/20/2021, 07:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/22/2021, 09:51 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as i can't repro this and we have rewritten this component.
