### ISSUE TITLE
Pull Members up on Interfaces does not move documentation to interfaces

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#57415]
**Version Used**: 
Version 17.0.0 RC2

**This might be intentional, but thanks for confirming/looking into it.** This was originally reported in [our documentation](https://github.com/MicrosoftDocs/visualstudio-docs/issues/7094) as unexpected.

**Steps to Reproduce**:

1.  When pulling a member up to a base class the xml documentation moves along with it. When pulling a member up to the interface the xml does not move.
2. Simple repro code:
```csharp
public interface Calculator
{
}
public class SuperCalculator : Calculator
{
    /// <inheritdoc/>
    public int Add(int a, int b) => a + b;

    /// <summary>
    /// This is a member comment
    /// </summary>
    /// <param name="a"></param>
    /// <param name="b"></param>
    /// <returns></returns>
    public int Multiple(int a, int b) => a * b;
}
```

![image](https://user-images.githubusercontent.com/8293542/139126402-d270d7aa-794d-4b93-8d61-804da029620e.png)

**Expected Behavior**:
Documentation moves to interface.

**Actual Behavior**:
Documentation does not move to interface.
```csharp
public interface Calculator
{
    int Add(int a, int b);
    int Multiple(int a, int b);
}
public class SuperCalculator : Calculator
{
    /// <inheritdoc/>
    public int Add(int a, int b) => a + b;

    /// <summary>
    /// This is a member comment
    /// </summary>
    /// <param name="a"></param>
    /// <param name="b"></param>
    /// <returns></returns>
    public int Multiple(int a, int b) => a * b;
}
```

The documentation does move when moving to base class:
```csharp
public class Calculator
{
    /// <inheritdoc/>
    public int Add(int a, int b) => a + b;

    /// <summary>
    /// This is a member comment
    /// </summary>
    /// <param name="a"></param>
    /// <param name="b"></param>
    /// <returns></returns>
    public int Multiple(int a, int b) => a * b;
}
public class SuperCalculator : Calculator
{
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and lack of feedback.
