### ISSUE TITLE
C# code cleanup: Add a mechanism to remove inactive code (#if-defed out)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57451]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-code-cleanup:-Add-a-mechanism-to-remo/1564950)._

---
Imagine having a _large_ C# codebase littered with #if WP7 or #if SILVERLIGHT and other obsolete things massively cluttering the code. It would be helpful to have a mechanism that would intelligently remove this dead code, for example, by stripping out all inactive code in the current configuration and removing any #if (etc) directive left empty and collapsing all blank lines leftovers into one blank line, etc. I suspect this would be useful for C and C++ too.

---
#### Feedback Bot on 10/28/2021, 01:52 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
Closing as unlikely to do this.  Such code can just be collapse, and you can hit ctrl-x in the editor to then delete it.
