### ISSUE TITLE
Change assignments (change left hand assignments to the right and viceversa)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57450]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Change-assignments-change-left-hand-ass/1549134)._

---
Should be a nice feature in the "Refactor menu" to change assignments from the left to the right and viceversa.

If I have these assignments:

```csharp
edRe.ID = Convert.ToInt32(txtERID.Text);
edRe.FechaHora = Convert.ToDateTime(txtERFechaHora.Text);
edRe.Avisar = chkERAvisar.IsChecked;
edRe.Duracion = Convert.ToInt32(txtERDuracion.Text);
edRe.EsNueva = chkEREsNueva.IsChecked;

```

Then change to:

```csharp
txtERID.Text = edRe.ID.ToString();
txtERFechaHora.Text = edRe.FechaHora.ToString();
chkERAvisar.IsChecked = edRe.Avisar;
txtERDuracion.Text = edRe.Duracion.ToString();
chkEREsNueva.IsChecked = edRe.EsNueva;

```

To clarify, in the code, the types are:
ID int, FechaHora DateTime, Avisar bool, Duracion int, EsNueva bool.

I know the problem should be with boolean properties / types of the "controls" (chkERAvisar and chkEREsNueva), Text is a wide type of string.

And doing the opposite assignment ;-)

Thanks.
Guillermo

---
#### Feedback Bot on 10/8/2021, 11:34 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:

- User could write a plugin for this focused functionality. A plugin is a better avenue for this request.
- Better fit for repeated edits in intellicode (and/or any serialization framework). 

 Decision: The feature fits better with Intellicode/plugin.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback and ability to write an refactoring extension to do this if desired.
