### ISSUE TITLE
Remove the generated Razor document workaround in DiagnosticIncrementalAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#57459]
Dynamic documents being closed: https://github.com/dotnet/roslyn/pull/57172#discussion_r738658249

Agree that this is something that should be re-thought about. Might exceed the scope of this PR though

_Originally posted by @NTaylorMullen in https://github.com/dotnet/roslyn/pull/57172#discussion_r738659319_

**Comment by CyrusNajmabadi** [comment]
>  For instance, when you open a Razor editor a backing C# file is created for the C# portions of that document; however, that document isn't really "open" per-say (there's no TextView associated with it).

Note: if any part of that document is viewable in an editor in any fashion, then i would describe it as 'open'.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
