### ISSUE TITLE
Formatter requires two passes in the presence of directives inside lambda block bodies, inside argument lists

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#57465]
Given the following code:

```cs
namespace N
{
    public class C
    {
        protected void Render()
        {
            if (true)
            {
                    M(() =>
                        {
#nullable enable
                               if (true)
                                    {
                                    }
                                }
                        );
                }
        }
    }
}
```

Formatting the document once results in:
```cs
namespace N
{
    public class C
    {
        protected void Render()
        {
            if (true)
            {
                M(() =>
                    {
#nullable enable
                            if (true)
                        {
                        }
                    }
                    );
            }
        }
    }
}
```

Note the position of the `if (true)`. It has been moved by the formatter, but not by enough.

Foratting the document again results in:

```cs
namespace N
{
    public class C
    {
        protected void Render()
        {
            if (true)
            {
                M(() =>
                    {
#nullable enable
                        if (true)
                        {
                        }
                    }
                    );
            }
        }
    }
}
```

This is now properly formatted, and subsequent formatting does nothing, as you would expect.

Removing the `#nullable enable` from the file fixes the issue, and the formatter does the right thing on the first pass. Alternatively, changing the code so the lambda is assigned to a discard rather than passing it as an argument, also fixes the issue, even if the `#nullable enable` is left in place.

This bug is the cause of https://github.com/dotnet/razor-tooling/issues/5676 in Razor, which generates code in a similar form to the example here.

**Comment by jinujoseph** [comment]
Triage notes : Important for razor scenarios

**Comment by davidwengier** [comment]
Another repro in Razor: https://github.com/dotnet/razor-tooling/issues/5693

**Comment by davidwengier** [comment]
This has been reported in the following VS feedback issues too:

[developercommunity.visualstudio.com/t/Blazor-format-document---Formatting-goes/1560559](https://developercommunity.visualstudio.com/t/Blazor-format-document---Formatting-goes/1560559)
[developercommunity.visualstudio.com/t/Blazor-Format-Document-doesnt-work-as-e/1575423](https://developercommunity.visualstudio.com/t/Blazor-Format-Document-doesnt-work-as-e/1575423)
[developercommunity.visualstudio.com/t/Poor-HTML-alignment-with-Blazor-componen/1660959](https://developercommunity.visualstudio.com/t/Poor-HTML-alignment-with-Blazor-componen/1660959)
[developercommunity.visualstudio.com/t/CtrlKD-does-not-work-for-blazor-InputS/1665709](https://developercommunity.visualstudio.com/t/CtrlKD-does-not-work-for-blazor-InputS/1665709)
