### ISSUE TITLE
Improve usability of Enable Nullable Reference Types refactoring

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#57476]
Follow-up items to improve #57200.

* [x] Allow the caret to be placed on the `#` or `nullable` tokens (currently it must be placed on the `enable` token)

    https://github.com/dotnet/roslyn/blob/1073bba0eafc043b9755bc802ef7c1e83d274c74/src/Features/CSharp/Portable/CodeRefactorings/EnableNullable/EnableNullableCodeRefactoringProvider.cs#L49-L50

* [x] Allow the refactoring to be triggered from a `#nullable restore` line

* [x] Allow the refactoring to be triggered from a `#nullable disable` line

* [ ] Improve the light bulb preview associated with the change

* [ ] Improve the application preview that appears if the user selects "Preview changes"

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
