### ISSUE TITLE
Documentation recommends inefficient way to read file.

### ISSUE THREAD

**Issue by nschuessler** [dotnet/roslyn#57492]
**Version Used**: 

On this page about [reading AdditionalFiles from a stream](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Using%20Additional%20Files.md):
The example for "Converting an AdditionalFile to a stream" section does:
1) Find additional file from the context based on path
2) Use `SourceText` to read the additional file into a string
3) Create a memory stream on top of the string
4) Read the additional file contents from the `MemoryStream`

This is a bit wasteful of resources.

Why not have an example that opens a `FileStream` with the path already available.
No reason to allocate the entire file in memory and read two streams.

**Steps to Reproduce**:

1. See documentation.
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

**Comment by sharwell** [comment]
> Why not have an example that opens a FileStream with the path already available.

Roslyn extensions _must not_ directly read content from files on disk. Attempts to do so results in undefined compiler output.

**Comment by nschuessler** [comment]
Seems like there should be an API to handle the complexities and give the reader a stream so it can be read normally ... by making a copy to a temp directory or something to satisfy the build system. Anyway, I see this is intentional.
