### ISSUE TITLE
Code Navigation bar does not show event handlers in VB Winforms App

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#57516]
In WPF event handlers appear in the navigation bar:
![image](https://user-images.githubusercontent.com/9797472/139759942-6a4c3e14-dabd-4084-814b-d08ae9a12621.png)

![image](https://user-images.githubusercontent.com/9797472/139760403-2dca74ab-b381-4f9a-a3c9-4fc8c414f949.png)

And in Winforms apps they appear for C#:

![image](https://user-images.githubusercontent.com/9797472/139762320-91cfec8f-3686-40ac-83e3-2d4992785ae6.png)

However we have regressed this for VB Winforms Apps:

![image](https://user-images.githubusercontent.com/9797472/139760849-1ee8401f-66a1-4966-900e-5aac4f1bc09d.png)

**Comment by Cosifne** [comment]
Another feedback reported by user
https://developercommunity.visualstudio.com/t/Clicking-in-a-Controls-Code-behind-Rout/1565129

**Comment by CyrusNajmabadi** [comment]
Can definitely repro.  Working on fix.

**Comment by rozeboosje** [comment]
Thanks. Yes it's the same as the issue I reported.

**Comment by CyrusNajmabadi** [comment]
@rozeboosje The fix is in:

![image](https://user-images.githubusercontent.com/4564579/145869049-a4d91801-b9ff-46f9-b59a-e3a6dbac1ce6.png)

Thanks!

**Comment by rozeboosje** [comment]
Nice one! Looking forward to it.
