### ISSUE TITLE
Type inference fails for Func<Expression<Func<T>>>

### ISSUE THREAD

**Issue by CameronAavik** [dotnet/roslyn#57517]
**Version Used**: 

dotnet: `6.0.100-rc.2.21505.57`

**Steps to Reproduce**:

Compile the following code ([sharplab link](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAOgBlYBHCgUQA8AHAJwFMBnLqAexhcA3AQLoALCQAq3AC7YAPFIB8ACnQBWJcpIdWAShIBvAL5jJMrrMzbVzdt14CFm7Tr0tDp89LkBmW1dXFXcDYzNCCzlxQK17Th5+GBctENDPcNF8S3lVVUMAXh1MfSESAHpykgB3PjYAay4CHMw8wuLSiqrahqbs/zaSIpJ8oY6yypq6xuboweHR4ZKJqo42NjqQEgBhAGUicWxsIA===)):

```csharp
using System;
using System.Linq.Expressions;

void Test1<T>(Func<T> exp) {}
void Test2<T>(Expression<Func<T>> exp) {}
void Test3<T>(Func<Func<T>> exp) {}
void Test4<T>(Func<Expression<Func<T>>> exp) {}

Test1(() => 2); // works
Test2(() => 2); // works
Test3(() => () => 2); // works
Test4(() => () => 2); // error: CS0411
```
**Expected Behavior**:

The `T` generic type parameter is correctly inferred for all 4 cases.

**Actual Behavior**:

In `Test4`, the `T` is unable to be inferred, producing the following error:

> error CS0411: The type arguments for method 'Test4<T>(Func<Expression<Func<T>>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Given that type inference works for `Func<T>`, `Expression<Func<T>>`, and `Func<Func<T>>`, I thought it might be a bug that `Func<Expression<Func<T>>>` doesn't work.

EDIT: As of .NET 6.0.101, the behaviour has changed and now inference fails also for `Func<Func<T>>`, the reason this behaviour was reverted is explained in https://github.com/dotnet/roslyn/pull/57713#discussion_r748779212. An issue https://github.com/dotnet/roslyn/issues/57779 was created to consider addressing this scenario.

**Comment by AlFasGD** [comment]
Definitely related:
- https://github.com/dotnet/csharplang/discussions/129
- https://github.com/dotnet/csharplang/issues/3277

**Comment by CameronAavik** [comment]
I'm not sure that those are related. It seems they are caused by method groups not participating in the type inference. My repro does not have method groups and I think is a different issue.

**Comment by Mirsario** [comment]
Yeah, this is definitely a new bug. It used to work fine in .NET 5. I updated a project to .NET 6 today and was very surprised to see build errors.

**Comment by cston** [comment]
See also https://github.com/dotnet/roslyn/issues/57630.

**Comment by CameronAavik** [comment]
This isn't a full workaround, but I just figured out a way you can trick the compiler to infer the types by creating some helper inference methods

```csharp
Func<T> InferFunc<T>(Func<T> f) => f;
Expression<Func<T>> InferExpression<T>(Expression<Func<T>> f) => f;

void Test1<T>(Func<Func<T>> exp) {}
void Test2<T>(Func<Expression<Func<T>>> exp) {}

Test1(() => () => 2); // error CS0411
Test2(() => () => 2); // error CS0411

Test1(() => InferFunc(() => 2)); // works!
Test2(() => InferExpression(() => 2)); // works!
```

**Comment by cston** [comment]
Thanks for reporting this issue @CameronAavik. 

I will close this issue since the compile error in your original post was fixed in https://github.com/dotnet/roslyn/pull/57713, and since https://github.com/dotnet/roslyn/issues/57779 is tracking inferring from function types.
