### ISSUE TITLE
VS Code CleanUp Setting 'Add Access modifiers' removes overloads in VB.Net Files

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/roslyn#57524]
**Version Used**: VS17.0.0 Preview 7.0

**Steps to Reproduce**:

1. Create a new VB.Net Project with 2 Classes with the Same Properties and interhite Class 1 in Class 2
2. Add the Keyword Overloads to the Properties in Class 2 in order to remove Warnings (BC40003)
3. Run the Code CleanUp-Feature with the Setting 'Add Access modifiers'

**Expected Behavior**:
It should add the Public - Keyword(Access modifier), but let the Overloads-Keyword be

**Actual Behavior**:
IT adds the Public - Keyword(Access modifier), but removes the Overloads-Keyword

Code Samples:
This is the Orinal Code:

`
Public Class Class1
    Property t1 As String
End Class
Public Class Class2
    Inherits Class1
    Overloads Property t1 As String
End Class
`

This is the Code after Code CleanUp:

`
Public Class Class1
    Public Property t1 As String
End Class
Public Class Class2
    Inherits Class1

    Public Property t1 As String
End Class
`

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be making chnages in these experiences.
