### ISSUE TITLE
SARIF output contains a sub-object within properties

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#5752]
The Roslyn compiler produces SARIF output as follows:

````
      "ruleId": "CC0057",
      "locations": [
        {
          "analysisTarget": [
            {
              "uri": "c:\Users\sschen\Documents\Visual Studio 2015\Projects\DemoSolution\AliceProject\Program.cs",
              "region": {
                "startLine": 10,
                "startColumn": 25,
                "endLine": 10,
                "endColumn": 38
              }
            }
          ]
        }
      ],
      "shortMessage": "Parameter 'args' is not used.",
      "fullMessage": "When a method declares a parameter and does not use it might bring incorrect conclusions for anyone reading the code and also demands the parameter when the method is called, unnecessarily.
You should delete the parameter in such cases.",
      "properties": {
        "severity": "Warning",
        "warningLevel": "1",
        "defaultSeverity": "Warning",
        "title": "Unused parameters",
        "category": "Usage",
        "helpLink": "https://code-cracker.github.io/diagnostics/CC0057.html",
        "isEnabledByDefault": "True",
        "customTags": "Unnecessary",
        "customProperties": {
          "identifier": "args"
        }
      }
    },

````

Note that the `properties` property has a sub-property name `customProperties`, whose value is a JSON object, rather than a string as required by the spec.

If necessary, you could "namespace" this, for example:

````
    "customProperties.identifier": "args"
````

**Comment by mavasani** [comment]
@lgolding the custom properties emitted for the diagnostic directly correspond to the property [Diagnostic.Properties](http://source.roslyn.io/Microsoft.CodeAnalysis/R/4ba4b6448b981d28.html). I think this is an important info about a diagnostic instance that we do want to emit, and we can probably concat all the kvps with some delimiter (we already concat the customTags to emit a single string in the log)

**Comment by lgolding** [comment]
@mavasani  You can concatenate them if you are certain the delimiter is not used in any property name or value, or you can "namespace" them as suggested above (which seems safer to me).

**Comment by nguerrera** [comment]
@lgolding What is the rationale for the spec requiring these arbitrary tool-defined values to be strings?

**Comment by lgolding** [comment]
It was for ease of implementation. I thought it would be easier to deserialize into a known type if the structure was fully defined. For example, if I'm writing C#, I can use `JsonConvert.DeserializeObject<T>` where `T` is a class representing a SARIF log file.

Is there a way to accomplish this simple deserialization if some properties can have a type that's not known at runtime?

**Comment by nguerrera** [comment]
In the case of JSON.NET it you can use System.Object for that case and it will deserialize to an appropriate type at runtime:

![image](https://cloud.githubusercontent.com/assets/75470/11009813/d3f76fca-848e-11e5-91e5-941f4c3ed61d.png)

**Comment by nguerrera** [comment]
In light of that, should we relax the string requirement in the spec or do we still want to flatten these properties? 

cc @michaelcfanning

**Comment by lgolding** [comment]
Thanks for the information. It seems reasonable to me. @michaelcfanning, what do you think?

**Comment by nguerrera** [comment]
I've opted to follow the spec as currently defined using the "namespace" approach here in #6701. If we'd rather allow arbitrary structure in properties, I can revert that part.

**Comment by lgolding** [comment]
That certainly makes my life easier :-)
