### ISSUE TITLE
Inline diagnostics should be delayed until after a user is done typing

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#57533]
We should consider delaying inline diagnostics to show up after a user is done typing or after the user types a semicolon at the end of the line. It currently gets in the way of typing.

**Comment by CyrusNajmabadi** [comment]
> to show up after a user is done typing

There's no way to know when a user is done typing :)  It's not a state with meaning.  After all, any point we might consider 'done' the user might just end up writing new code a moment later.

>  It currently gets in the way of typing.

Can you clarify this?  How does it get in the way?  It should not cover the user text at all, and it should only be visible if there is space for it.

If we also require things like a semicolon, we're effectively saying: only show me the errors once the code is 'correct' (by some definition of 'correct').  Which means then if there is an error that we don't show inline diag for, the user can be stuck in a situation where they care about what the diag is (so they can fix it), but we never show it.

**Comment by ryzngard** [comment]
One follow up: does it matter where the diagnostics are showing? At end of line or right side of window?

**Comment by akhera99** [comment]
If a user's cursor is located on a line with a diagnostic, should we hide the diagnostic until after the cursor has been moved?
If yes, should that be an option?

**Comment by CyrusNajmabadi** [comment]
That feels weird to me as well.  I thought the purpose of htis was so that a user could easily tell (without error list, and without hover) what issue they had with their code.  Say they write something, and then get the squiggle.  Now they want to know what it means.  Having to move off the line seems problematic.  

It's also a bit strange that i might see a squiggle with a message, then move my line up to fix it, only to see the message disappear.  If i wanted to read it again once i was on that line, i wouldn't be able to.

**Comment by CyrusNajmabadi** [comment]
Have we considered just slowing down how fast these appear to more jive with the idea of: if the user is flowing with code, don't bother them.  HOwever, if they really stop and are potentially waiting on this info, we then pop up after a suitable delay?

This is the concept with have with squiggles.  But there, the delay was tuned based on the value vs annoyance of that adornment.  If the value/annoyance ratio is different here, we should consider tuning the delay based on that.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to happen, we need to put it in a milestone to get it done.
