### ISSUE TITLE
Convert to block scoped code fix produces incorrect output if namespace declaration is inside a ifdef

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn#57564]
**Version Used**:  17.1.0 Preview 1.0 

**Steps to Reproduce**:

![CS1061](https://user-images.githubusercontent.com/174281/140194307-558802b5-30fa-4b2b-8a04-731114302e2b.gif)

Here's what my original code looked like:

```
#if DEBUG
namespace Test
#else
namespace Test2
#endif
{
    public class MyClass
    {

    }
}
```

**Comment by CyrusNajmabadi** [comment]
Non-whitespae trivia on the `{` should likely move to the next token in the file (or EOF if the next token would be the close curly).

**Comment by pranavkm** [comment]
Related issue: if the only thing inside the body of the namespace is ifdef-ed out, the codefix removes it e.g.

```C#
namespace Test
{
#if RELEASE
    public class MyClass
    {

    }
#endif
}
```
![CS1061](https://user-images.githubusercontent.com/174281/140438739-25993b65-38de-4e7a-a279-aa3f62f315e3.gif)

**Comment by CyrusNajmabadi** [comment]
Thanks @pranavkm that's a good case as well :)

**Comment by davidwengier** [comment]
Possibly related: https://twitter.com/cloudsider/status/1459179024991744003

**Comment by uzinable** [comment]
if namespace close brace is the last char of the file, bug still do his nasty things, im on VS2022
I looked at the tests done for this and almost all have a newline.

see #63769

**Comment by uzinable** [comment]
I add another one to be fully complete :)
if open brace have comment, and there is commented class inside the namespace, it doesn't allow automatic inline namespace to be done :

Before 
![image](https://user-images.githubusercontent.com/34981862/188264692-ad886711-13ae-4ac7-a6e9-43d7bfddc511.png)
After:
![image](https://user-images.githubusercontent.com/34981862/188264708-64ba2059-0e1c-493a-9b3d-e874963d4693.png)

but if we remove commented class, it does :

Before
![image](https://user-images.githubusercontent.com/34981862/188264737-2feccd7a-d425-4221-813c-e0b67f173712.png)
After
![image](https://user-images.githubusercontent.com/34981862/188264742-0b9a1717-c46c-44f3-badf-dd28597eecfc.png)

**Comment by davidwengier** [comment]
Thanks @uzinable, I've moved your comment to an issue, https://github.com/dotnet/roslyn/issues/63792, so it can be addressed.
