### ISSUE TITLE
GetSymbolInfo for InvocationExpressionSyntax fails with OverloadResolutionFailure

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/roslyn#57590]
**Version Used**: 
3.11

**Steps to Reproduce**:
I'd expect `semanticModel.GetSymbolInfo` to succeed for both InvocationExpressionSyntax nodes in the method in the code below.
```csharp
    public static void Main(string[] args)
    {
        const string source = @"
        public class TestClass
        {
            public void M()
            {
                M2(new DateTime());
                M2(new TestClass());
            }
        
            public void M2(object parameter) { }
        }";
        var compilation = CreateCompilation(source);
        var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees.First());
        var tree = compilation.SyntaxTrees.First();
        var nodes = tree.GetRoot()
            .DescendantNodes(x => x is not InvocationExpressionSyntax)
            .OfType<InvocationExpressionSyntax>();
        var node = nodes.First(); //M2(new DateTime());
        var node2 = nodes.ElementAt(1); //M2(new TestClass());

        var symbolInfo = semanticModel.GetSymbolInfo(node); //fails
        var symbolInfo2 = semanticModel.GetSymbolInfo(node2); //succeeds
    }

    private static Compilation CreateCompilation(string source)
    {
        var tree = CSharpSyntaxTree.ParseText(source);
        var references = AppDomain.CurrentDomain.GetAssemblies().Where(x => !x.IsDynamic).Select(x => MetadataReference.CreateFromFile(x.Location)).ToArray();
        var options = new CSharpCompilationOptions(OutputKind.ConsoleApplication);
        var compilation = CSharpCompilation.Create("compilation", new[] { tree }, references, options);
        return compilation;
    }
```

![image](https://user-images.githubusercontent.com/30874283/140432729-f403cc0a-d966-44a6-86c6-72255cb8bf70.png)

**Expected Behavior**:
`symbolInfo.Symbol` returns the symbol for `TestClass.M2(object)`.

**Actual Behavior**:
`symbolInfo.Symbol` is null.

**Additional notes**

Frustratingly, the Syntax Visualizer has no trouble figuring out the semantic information for that syntax node. The code that it uses to fetch semantic information can be found here: 
https://github.com/dotnet/roslyn-sdk/blob/ccc0973f6bad2782222d0a6224ba46fe73799920/src/VisualStudio.Roslyn.SDK/SyntaxVisualizer/Roslyn.SyntaxVisualizer.Control/SyntaxVisualizerControl.xaml.cs#L1139, and it seems to be the same thing I'm doing here.

What I am missing?

**Comment by Youssef1313** [comment]
Calling `compilation.GetDiagnostics()` can usually help finding out the issue.

You'll find two diagnostics in the compilation:

![image](https://user-images.githubusercontent.com/31348972/140480309-fe08dcca-2acf-4fcf-9089-2aa223220219.png)

the second is the important one. You're missing a `using System;`

**Comment by JakeYallop** [comment]
Ah - thanks! I'm missing `using System;` in the original code that the above issue was derived from as well. I actually check diagnostics, but only for source generated code and not the source code, in the original project that the above code is from.

Thanks for help!
