### ISSUE TITLE
'CS1591' should not suggest Design.cs file.

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#57595]
**Version Used**: Visual Studio 2019 Version 16.11.5

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/23723575/140449340-db43212a-e6a0-4c1c-90c4-8ba0021dfcbf.png)
![image](https://user-images.githubusercontent.com/23723575/140449374-adda5636-bca4-4df1-a2c9-0089faebc48c.png)

**Expected Behavior**:

**Actual Behavior**:

**Comment by jinujoseph** [comment]
Duplicate of #41171
