### ISSUE TITLE
Run integration tests against unreleased builds of VS

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#57609]
Setup internal microsoft pipeline for running integration tests against branch builds of VS.

**Comment by vatsalyaagrawal** [comment]
@JoeRobich should we mark this as completed?

**Comment by JoeRobich** [comment]
> @JoeRobich should we mark this as completed?

With https://github.com/dotnet/roslyn/pull/58872 merged, we can enable this pipeline again for the main branch. Going to close this issue.
