### ISSUE TITLE
Visual Studio 2022 EnforceCodeStyleInBuild causes error to show twice

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57647]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-EnforceCodeStyleInBui/1566547)._

---
Changing the CSPROJ to TreatWarningsAsErrors and EnforceCodeStyleInBuild causes the same error to appear twice in the Visual Studio Error window.

---
#### Feedback Bot on 10/29/2021, 08:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/29/2021, 10:51 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Confirmed that this is an issue for top level code. Same code within an explicitly declared Main method generates diagnostics as expected.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.
