### ISSUE TITLE
Compiler cannot properly detect initialization of non-nullable fields with non-null values during object initialization

### ISSUE THREAD

**Issue by bartlomiej-stys** [dotnet/roslyn#57645]
**Version Used**: 
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

**Steps to Reproduce**:

1.  Create new console application `dotnet new console`
2.  Make sure in your .csproj file you have nullable feature enabled: `<Nullable>enable</Nullable>`
3.  Your project should contain only one cs file with the following contents:
```csharp
var person = new Person("Elon_Musk", 25);
Console.WriteLine(person.InitFirstNameAndLastName);

class Person 
{
    private readonly string _firstName;
    private readonly string _lastName;
    private readonly int _age;

    public Person(string firstNameAndLastName, int age)
    {
        InitFirstNameAndLastName = firstNameAndLastName;
        _age = age;
    }

    public string InitFirstNameAndLastName
    {
        get => $"{_firstName}_{_lastName}";
        init 
        { 
            var firstNameAndLastName = value;
            var firstAndLast = firstNameAndLastName.Split('_');
            _firstName = firstAndLast[0];
            _lastName = firstAndLast[1];
        }    
    }
}
```
4. Build the project with `dotnet build` command.

**Expected Behavior**:
Code compiles without warnings.

**Actual Behavior**:
Code compiles with warnings:
```
warning CS8618: Non-nullable field '_firstName' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. 
warning CS8618: Non-nullable field '_lastName' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```

**Additional info**
When I move the initialization of the readonly fields directly to the constructor the warnings go away:
```csharp
var person = new Person("Elon_Musk", 25);
Console.WriteLine(person.InitFirstNameAndLastName);

class Person 
{
    private readonly string _firstName;
    private readonly string _lastName;
    private readonly int _age;

    public Person(string firstNameAndLastName, int age)
    {
        var firstAndLast = firstNameAndLastName.Split('_');
        _firstName = firstAndLast[0];
        _lastName = firstAndLast[1];
        _age = age;
    }

    public string InitFirstNameAndLastName
    {
        get => $"{_firstName}_{_lastName}";
        init 
        { 
            var firstNameAndLastName = value;
            var firstAndLast = firstNameAndLastName.Split('_');
            _firstName = firstAndLast[0];
            _lastName = firstAndLast[1];
        }    
    }
}
```
I believe the compiler shouldn't produce those warnings in the former example, because readonly fields are initialized with non-null values when exiting constructor.

**Comment by svick** [comment]
The compiler does not look inside the bodies of methods and properties to see whether they affect nullability of other members. But you can tell it about that, using [nullability attributes](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis?WT.mc_id=DOP-MVP-5002735).

In this case, [you can use `[MemberNotNull]`](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEBMBGAsAKBQBgAIUMA6AERgEMBzAOwHsBnYGAYydIGEGATCAIJ0qAGwRMYTANy5cAYjoBXESKoAjEREIRhGiLJxgqUQgAdoTBnUIBeQnQgB3QgAULVgBQAiAKIirAPoAsopMANZeADSEaACsAJQyeBgAnB7mUJZ0pACSdDDAAGIwmcAAclQAtoJ0vAAyVCwV1YkG6K7u1rgA3riE/WawRsBaUBBUvFZixBhEAXAlTVUQSQODMMOj45N00yRzqkvVqwOmQ1QjhGMTUwiEMHTAhAG0KwZrKADMHZme+4QLUrNGr1RrlZbRB5PV7xPoDXo4NZrPIFYpA5ZCUFHLR2QHYzENbEnJHPV62QivYmEAC+7wGXxmRBRRUW4OqBLBwLh/QRJP6NAgTxsAD5CAASLzdeas4HUgJSw5siDUrxUtYAbSCEEqamgZQY5WUIg8wmqDDgHml6Ja8QAutykZrtbqoPrDSoTctzZbFcD4naHWsHgVCIH4aHEXy1kYTHilRzseSjCJFG9I1H+jGAayE0Ls9aQYSlaQAMqmEQFDwAcgCVda6YzVsTuJztSL6vwtrVfICvuW5LjufVGC7Yf61LWDtpOGpQA==):

```c#
public string InitFirstNameAndLastName
{
    get => $"{_firstName}_{_lastName}";
    [MemberNotNull(nameof(_firstName))]
    [MemberNotNull(nameof(_lastName))]
    init 
    { 
        var firstNameAndLastName = value;
        var firstAndLast = firstNameAndLastName.Split('_');
        _firstName = firstAndLast[0];
        _lastName = firstAndLast[1];
    }    
}
```

**Comment by bartlomiej-stys** [comment]
@svick 
Oh I didn't know that is possible. Thanks! If the compiler does not look inside the body of methods by design then I think we can close this issue.
