### ISSUE TITLE
Create new class is not being offered

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#57642]
I was unable to create a minimum repro of this, but while working in Roslyn I was creating new classes (Adornment and ViewModel). I created the VM and the adornment class was only offering to change it, not generate a new type

![image](https://user-images.githubusercontent.com/475144/140840273-2c7867f8-c2a3-4d5c-a714-34bb48389654.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of repro.
