### ISSUE TITLE
Can't Declare an Inferred Lambda With Optional Arguments

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#57652]
**Version Used**: 
.NET 6.0, C# 10

**Steps to Reproduce**:
I can declare this:
```
var noOptionals = (string a, int b) => a.Length + b;
```
And that works. But if I do this:
```
var optionals = (string a, int b = 2) => a.Length + b;
```

**Expected Behavior**:
I was hoping that would work, and [Bill thought it might](https://twitter.com/billwagner/status/1458134337501601795), but apparently inferred lambdas can't fall back to creating an anonymous delegate like it can when you do this:
```
var withRefs = (ref string a) => a.Length;
```

**Actual Behavior**:
It doesn't work. Maybe it's not supposed to work, but since you can define a lambda with `ref`, I was hoping you could also use optional parameters with default values.

**Comment by jmarolf** [comment]
@RikkiGibson I assume this works with your prototype?

**Comment by 333fred** [comment]
I doubt it, Rikki's prototype was about putting ref in the type system, not attributes. It seems to me optionalness would still be an issue with that prototype.

@cston, where you expecting this scenario to work in 10 and generate an anonymous delegate type

**Comment by RikkiGibson** [comment]
I do not think optional arguments on lambdas was ever part of the design for the C# 10 lambda improvements. It doesn't seem like a lambda with an optional argument [even parses](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzggPgAQEwEYCwAUJgMwAEOZAwmQN5FmMXmYAsZAsgBQCUdDTQQDcIAJzIAPMgF4yXWAkkyyABj7SAfHTIBfANwDGOojqA=), although it seems like it would be reasonable to do so for error recovery.

I would be curious to know more about the motivation for optional arguments on lambdas.

**Comment by cston** [comment]
Lambda expressions with optional arguments were not a scenario for C#10.

**Comment by 333fred** [comment]
Given that, I'm going to close this issue. @JasonBock, if you would like to make that language request, please open a discussion on csharplang.
