### ISSUE TITLE
VS2022 Incorrect edge rendering on Windows 2008 R2

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#57670]
**Version Used**: 
VS2022 17.0.0 on Windows 2008 R2

![微信截图_20211110105603](https://user-images.githubusercontent.com/12094247/141041518-5165a474-d3da-4f8f-9c67-582ce6ac8e70.png)

**Comment by CyrusNajmabadi** [comment]
Roslyn doesn't control this. Can you please file over at developercommunity?  Thanks!

**Comment by ahdung** [comment]
Okay I will, thank you for your response.  I put here because developercommunity have a bad experience, so if you can, please migrate developercommunity to github, or improve it.
