### ISSUE TITLE
Inconsistency when using multiple NotNullIfNotNull attributes

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/roslyn#57672]
I'm currently migrating to .NET 6 and found some inconsistency in the use of multiple NotNullIfNotNull attribute on a method. I've tried to read all available sources online to understand if it's a bug or by design, but resort to posting here for clarification.

**Version Used**: main (2021-11-09)

**Steps to Reproduce**:

```c#
    public static void Main()
    {
        string result = ReturnFirstOrSecondOrNullIfBothNull("first", "second"); // no warning (correct)
        Console.WriteLine(result); // "first"

        result = ReturnFirstOrSecondOrNullIfBothNull("first", null); // no warning (correct)
        Console.WriteLine(result); // "first"

        result = ReturnFirstOrSecondOrNullIfBothNull(null, "second"); // no warning (correct)
        Console.WriteLine(result); // "second"

        result = ReturnFirstOrSecondOrNullIfBothNull(null, null); // warning (correct)
        Console.WriteLine(result); // null

        TestMethod("first", "second");
    }
    
    [return: NotNullIfNotNull("first")]
    [return: NotNullIfNotNull("second")]
    public static string? ReturnFirstOrSecondOrNullIfBothNull(string? first, string? second)
    {
        return first ?? second;
    }

    public static void TestMethod(string? first, string? second)
    {
        string result;
        if (first is not null || second is not null)
        {
            result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // ** WARNING (not expected)
            Console.WriteLine(result); // "first"
        }

        if (first is not null && second is not null)
        {
            result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // no warning (correct)
            Console.WriteLine(result); // "first"
        }
        
        if (first is null && second is null)
        {
            result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // warning (correct)
            Console.WriteLine(result); // never executed
        }

        if (!(first is null && second is null))
        {
            result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // ** WARNING (not expected)
            Console.WriteLine(result); // "first"
        }
        
        if (first is null && second is null)
        {
            throw new ApplicationException("foo");
        }
        
        result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // ** WARNING (not expected)
        Console.WriteLine(result); // "first"
    }
```

[See this link for full repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfAAQCYBGAWACgCAGAAgJIDoARKCAcxgHsBnBKAMY9GAYS4ATVAEEYEADY4eUHgG5KAYhgBXOXIjA5qWqlkHUlAgGZ6RWiNoBvSrRc2iz104quf9EnXRUHh0EWgBeWgAlVAQtdBgAMSh0PgB5dABlVAEuGHF0gDkdOQBJLAAhLgQACyLdAAoAIixkvka4WkaebNzxRoBKFVoAemHabloAdwh42HZaepz0QIEEfo9fPwBOesDguTWh0c6WlIRGyg3fPZDwqJi4xNaEdKycvMLissqaurkm05tDraXSDEZjCbTWYweaLLjLbJrK4+Bg7G4HMHHZrPC4UZGudGhCLRWLxJJnV49D7oP7fKq1Yr1EFyDpdKl9TEQrhTGYwOYLJYrJHeTbbXZBEKczrdd59S4izaEu4kx7ktKZdmfXR036M5nA4pSqF8mEC+FC9YK3yo8X7Q7g8bFeWi2gAFSCCAAsjFqhIATjWTLegM1FaAL5XK4AbQIAHYQLQClVaVgkwg/v6zgMALrRuMJtMpwuMtmynNXKx+ABsfmoAH57qSnhSNbKtaUKvSMwx67RAQgOj2G0G8pafF4XXG+89aHXh+zQz4I1aK9YGDWCAAWN0e701P1D6dnQf+eeyseefEuHu0QmL0XYBb92jKcZVR26Wh4PC0EfiF88G+oTMhemwTi6BISgcyoPGSzyUm2NJfJ2uoNP2HR/lKABUWG0AA6lIkQFCUBQAOILNwoSoAAHgADoiqDiKBEE2oSUrYlmV60MuXGPvUz6vpRH5yLQABkom/uyAFAcJzHjlxPhKsSsHNuqby9O2OoMmhzwYeyUqQry/JwgiqxyaKrFQfaWL9riLrLi6vFYE+M6CcUYkSX+0kgVx4EQbeVkwU2aovK2GlIdqKHaf86GSeeRxjMaxmCoi5mbJZdoGagaDoMY1HZFoCCMVxPFWj4fEAIT8a5gHMh5cW9N5hppY4CmQXaQWqvBYXUimPzRdVx4NaOCW0Dh+GEcRZEUe+NH0asjEtSiJBolZ7G2SVXFOS5ZxNZ+4nDf+bmgr5bUuDU6BcJM4yoNdUi0bRciCBA/C5AAotRAioLRr0wACXBcCGm1la4XFKY2XUtupvXIf1GaxZho3jQRREkeRTKzXRDFMVxGWSqNHFtFcy5hkAA)

**Expected Behavior**:

No warnings if null values are eliminated through conditions.

**Actual Behavior**:

I get warnings, the lines marked with "** WARNING" are not expected.

**Comment by RikkiGibson** [comment]
Thanks for reporting this issue.

Because the compiler performs a path-independent flow analysis, a check like `if (first is not null || second is not null) { ... }` actually causes the compiler to learn *nothing at all* about the state of `first` or `second`. It's not capable of tracking, for example, "I know that at least one of them is not null, and depending on the result of a test on one of them, I could learn something about the state of the other one."

This is discussed in more detail in https://github.com/dotnet/roslyn/issues/36927#issuecomment-508595947.

**Comment by alrz** [comment]
Linking to https://github.com/dotnet/roslyn/issues/43906 for "and" semantics.

**Comment by joakimriedel** [comment]
Thanks for the clarification and link to background @RikkiGibson 

It would have made for some really pretty code, so I hope this will be revisited if/when path-dependent flow analysis is supported by the compiler.

I don't see how I could solve this with `Debug.Assert`, would you mind to elaborate a bit on that?

```c#
    public static void TestMethod(string? first, string? second)
    {
        string result;
        if (first is not null || second is not null)
        {
            // this won't help
            Debug.Assert(first is not null || second is not null);
            
            // neither would this
            if (first is null) {
                Debug.Assert(second is not null);
            }
            else if (second is null) {
                Debug.Assert(first is not null);
            }

            result = ReturnFirstOrSecondOrNullIfBothNull(first, second); // still warning
            Console.WriteLine(result); // "first"
        }
    }
```

instead I need to do something similar to the following, which is the pattern that I've resorted to use in my real code

```c#
    public static void TestMethod(string? first, string? second)
    {
        string result;
        if (first is not null || second is not null)
        {
            result = ReturnFirstOrSecondOrNullIfBothNull(first, second) ?? throw new ArgumentException("both arguments cannot be null");
            Console.WriteLine(result); // "first"
        }
    }
```
