### ISSUE TITLE
Discussion: Type Providers in c#

### ISSUE THREAD

**Issue by Ncage1974** [dotnet/roslyn#577]
Hopefully this is the correctly place for c# language discussion. Has there been any proposals to adding F# type providers to the c# language? Just today i was grimising  at the thought of having to update some large wcf proxy classes that we have. Type providers would make this so easy. I sure it will be helpful in a lot of cases where you have disparate data sources that change frequently.

**Comment by gafter** [comment]
There is no language proposal for this yet. We'd welcome one!

**Comment by Ncage1974** [comment]
Thanks Neal for the reply. Being unfamiliar with the process is there anything that i need to do other than this issue i created :). I also created an identical issue under the Roslyn project on codeplex.

**Comment by gafter** [comment]
We cannot consider a language proposal if there is no language proposal to consider. A suggestion that we consider doing "something like F# type providers" isn't a language proposal that we can do anything with. We would need much more detail.
