### ISSUE TITLE
Microsoft.CodeAnalysis.Project has no documentation on how the Documents are populated.

### ISSUE THREAD

**Issue by BehroozAmoozad** [dotnet/roslyn#57709]
`Microsoft.CodeAnalysis.Project` has no documentation on how the `Documents` are populated.   
Are we supposed to `AddDocument` Manually?  
Is a bug preventing them from being loaded automatically?  
If we're supposed to load them manually, is there a helper class to filter file extensions with?   
If it's not intended to be loaded automatically then why are Solution's Projects loaded automatically?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518c2d2f-da6a-cf64-0efd-d9b10d9bf192
* Version Independent ID: 8f774c6c-c309-032c-27bd-1f589a362036
* Content: [Project.Documents Property (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.project.documents?view=roslyn-dotnet-4.0.1#Microsoft_CodeAnalysis_Project_Documents)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Project.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Project.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jasonmalinowski** [comment]
@BehroozAmoozad: I'm guessing from your description that you're using MSBuildWorkspace to load projects and documents, but for some reason the documents didn't appear? If so that's either a problem with your projects, or something is wrong with how you're calling MSBuildWorkspace, or something else. There's not expected to be a separate step to initialize them.

**Comment by jasonmalinowski** [comment]
Closing this as I suspect this isn't really a documentation bug, but rather a functional bug. Without any further information I we can't fix that.
