### ISSUE TITLE
[Flaky Test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveDirectives.WorkspaceClearedAfterReset

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#57701]
Example run: https://runfo.azurewebsites.net/view/build/?number=1464500

Message:
```
System.AggregateException : One or more errors occurred. ---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
Server stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.SubmitText(String text) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:line 186
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InteractiveWindow_InProc.SubmitText(String text)
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveDirectives.WorkspaceClearedAfterReset() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpInteractiveDirectives.cs:line 265
```

Runfo Tracking Issue: [Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveDirectives.WorkspaceClearedAfterReset](https://runfo.azurewebsites.net/tracking/issue/214)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1464500](https://dev.azure.com/dnceng/public/_build/results?buildId=1464500)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57698](https://github.com/dotnet/roslyn/pull/57698)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1464500](https://dev.azure.com/dnceng/public/_build/results?buildId=1464500)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57698](https://github.com/dotnet/roslyn/pull/57698)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1464500](https://dev.azure.com/dnceng/public/_build/results?buildId=1464500)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57698](https://github.com/dotnet/roslyn/pull/57698)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1464500](https://dev.azure.com/dnceng/public/_build/results?buildId=1464500)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57698](https://github.com/dotnet/roslyn/pull/57698)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1464497](https://dev.azure.com/dnceng/public/_build/results?buildId=1464497)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57697](https://github.com/dotnet/roslyn/pull/57697)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1464497](https://dev.azure.com/dnceng/public/_build/results?buildId=1464497)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57697](https://github.com/dotnet/roslyn/pull/57697)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1464497](https://dev.azure.com/dnceng/public/_build/results?buildId=1464497)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57697](https://github.com/dotnet/roslyn/pull/57697)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1464487](https://dev.azure.com/dnceng/public/_build/results?buildId=1464487)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57696](https://github.com/dotnet/roslyn/pull/57696)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1464481](https://dev.azure.com/dnceng/public/_build/results?buildId=1464481)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57695](https://github.com/dotnet/roslyn/pull/57695)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1464474](https://dev.azure.com/dnceng/public/_build/results?buildId=1464474)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57693](https://github.com/dotnet/roslyn/pull/57693)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1464465](https://dev.azure.com/dnceng/public/_build/results?buildId=1464465)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57692](https://github.com/dotnet/roslyn/pull/57692)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1464465](https://dev.azure.com/dnceng/public/_build/results?buildId=1464465)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57692](https://github.com/dotnet/roslyn/pull/57692)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1464465](https://dev.azure.com/dnceng/public/_build/results?buildId=1464465)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57692](https://github.com/dotnet/roslyn/pull/57692)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1464465](https://dev.azure.com/dnceng/public/_build/results?buildId=1464465)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57692](https://github.com/dotnet/roslyn/pull/57692)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1464338](https://dev.azure.com/dnceng/public/_build/results?buildId=1464338)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57689](https://github.com/dotnet/roslyn/pull/57689)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1464338](https://dev.azure.com/dnceng/public/_build/results?buildId=1464338)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57689](https://github.com/dotnet/roslyn/pull/57689)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1464338](https://dev.azure.com/dnceng/public/_build/results?buildId=1464338)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57689](https://github.com/dotnet/roslyn/pull/57689)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1463505](https://dev.azure.com/dnceng/public/_build/results?buildId=1463505)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|2-Integration Debug OOP64_false OOPCoreClr_false|
|[1463505](https://dev.azure.com/dnceng/public/_build/results?buildId=1463505)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|2-Integration Debug OOP64_true OOPCoreClr_false|
|[1463505](https://dev.azure.com/dnceng/public/_build/results?buildId=1463505)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|2-Integration Release OOP64_false OOPCoreClr_false|
|[1463505](https://dev.azure.com/dnceng/public/_build/results?buildId=1463505)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|2-Integration Release OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_false OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_false OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_false OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_true OOPCoreClr_false|
|[1463186](https://dev.azure.com/dnceng/public/_build/results?buildId=1463186)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_false OOPCoreClr_false|
|[1462274](https://dev.azure.com/dnceng/public/_build/results?buildId=1462274)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_true OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_false OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_true OOPCoreClr_false|
|[1461102](https://dev.azure.com/dnceng/public/_build/results?buildId=1461102)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_true OOPCoreClr_false|
|[1459771](https://dev.azure.com/dnceng/public/_build/results?buildId=1459771)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|2-Integration Release OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Release OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Debug OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|2-Integration Release OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_true OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Release OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_false OOPCoreClr_false|
|[1459756](https://dev.azure.com/dnceng/public/_build/results?buildId=1459756)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 57635](https://github.com/dotnet/roslyn/pull/57635)|3-Integration Debug OOP64_true OOPCoreClr_false|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|13|13|

**Comment by sharwell** [comment]
Fixed by #57711
