### ISSUE TITLE
Update the inline rename UI

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#57715]
This is a placeholder issue to have a discussion around the design of updating the rename UI. The immediate asks we want are:

1. An editable box instead of editing the editor
2. Appears next to the invocation location
3. Supports all options that were previously supported

As we finalize the design more this issue will be updated

**Comment by JoeRobich** [comment]
UI Proposal: If we used the "Find in document" UI as a starting point, the replace UI could look something like this. Optional replacements become toggle buttons with icons and the preview changes become part of the apply changes dropdown.

![image](https://user-images.githubusercontent.com/611219/141373819-54fa77bc-4359-4ecd-987b-a37920bf7246.png)

![image](https://user-images.githubusercontent.com/611219/141373849-061e1dc9-7ac8-4500-ba31-e0ce50a74072.png)

**Comment by ryzngard** [comment]
# Proposed Design 

I believe we can incorporate a 2 state box that meets the needs of most users. The box defaults to expanded state, which showcases functionality of rename better. It remembers the last expand/collapse state and always uses that for a user moving forward. Pressing the arrow on the left of the textbox changes the collapse state.

With putting the dialog next to the invocation location, highlighted items (including original invocation span) will not update as the user types. 

## Key Requirements 

* [x] An editable box instead of editing the editor
* [x] Appears next to the invocation location
* [x] Supports all options that were previously supported
* [x] Discoverable options 
* [x] Keyboard friendly

## Collapsed State

### Benefit

This allows a more streamlined experience for those familiar with rename that want less visual clutter. Instead of checkboxes we use toggleable icons. Icons are TBD and not final in the mock.  Everything is tab order left to right, top to bottom. Tooltips explain the shortcut for changing the state of an option and short description of what it is.

### Mocks

![image](https://user-images.githubusercontent.com/475144/141540685-f2abb8a7-e7ec-479e-86c3-3fe1fecef207.png)

Clicking the down arrow on the right side of the textbox:

![image](https://user-images.githubusercontent.com/475144/141540705-40bd76c3-c013-4310-878f-dd4dd54b183d.png)

## Expanded State

### Benefit 

This allows users to understand more deeply what rename is doing and the capabilities it offers without having to know ahead of time. It's closer to our current dashboard, but inlined next to where the user invokes inline rename. Tooltips on each checkbox explain the shortcut to toggle. Tab order is left to right, top to bottom.

### Mock 

![image](https://user-images.githubusercontent.com/475144/141541343-5c57f8e9-8de9-4bef-a046-acb69f07c12e.png)

Clicking the down arrow on the right side of the textbox:

![image](https://user-images.githubusercontent.com/475144/141541791-c4b6eaed-fca5-493f-adcb-f65b7d7c273f.png)

**Comment by mikadumont** [comment]
This looks good but I don't entirely agree with this collapsed design for the following reasons: 

1. The options arent discoverable. 
2. This forces the user to take their hands off the keyboard and use their mouse. 
3. Theres no indicator on how to apply rename without requiring the user to lift their hands off the keyboard. 

Here is an example of some issues that can come up in the user's workflow: 

1. A user invokes inline rename and will see this:
![image](https://user-images.githubusercontent.com/46729679/141583997-4fd8e3bd-8f75-4789-9fb5-d1de7d471133.png)

2. They may not know how to apply the rename refactoring unless they take their hands off the keyboard and hover their mouse over the options.

3. They will then learn how to invoke rename but will then realize that it didn't rename their comments/strings and request that rename also updates comments & strings not realizing the option is already there if they just expand the view.

4. Lets say they do discover the option for renaming strings and comments expanding the view still forces the user to to take their hand off the keyboard. 

Inline rename was originally designed to be fully keyboard friendly and don't think we should change this behavior. 

An alternative design can be showing the expanded view always first to the user in-order to teach them about the options:
![image](https://user-images.githubusercontent.com/46729679/141593713-b2476a32-0b19-4081-b3dc-70f5778ed482.png)

When they invoke inline rename a second time we can show them the collapsed view:
![image](https://user-images.githubusercontent.com/46729679/141593744-ee6a9aaf-dca4-418c-b4bb-ba5eff633b3a.png)

**Comment by ryzngard** [comment]
It may not have been clear because if the way I ordered, but I think defaulting to expanded first is the best way. It was just a sentence at the top so easy to miss.

**Comment by ryzngard** [comment]
I updated the design proposal to help clarify more and put expanded state first. 

> They will then learn how to invoke rename but will then realize that it didn't rename their comments/strings and request that rename also updates comments & strings not realizing the option is already there if they just expand the view.

One question I have is how often does the find dialog get this feedback? It has a similar design. I wonder if we can leverage usability research or feedback on there to help influence decisions here. 

> Lets say they do discover the option for renaming strings and comments expanding the view still forces the user to to take their hand off the keyboard.

The icons will still have shortcuts and be keyboard navigable. 

> When they invoke inline rename a second time we can show them the collapsed view:

I put in the proposal that we remember the state for a user but don't automatically expand or collapse. Potentially need more discussion in this area.

**Comment by ryzngard** [comment]
Preview feature for 17.2
