### ISSUE TITLE
Improving The Hot Reload Feature

### ISSUE THREAD

**Issue by sangeethnandakumar** [dotnet/roslyn#57724]
I was trying to write a huge REST API project and I thought hot reload could make me so much more productive.
### As an evolving API requires lot of DTO changes, Model changes, Property modifications, Request/Response changes etc.. dotnet hot reload isn't good for any of these code evolving change scenarios.

_I certainly know and understand the underlying issues for not be able to use hot reload for everything but without these I believe most uses cases aren't covered._

**It would be awesome to be able to change models, properties & function attributes on the go with hot reload.**

To my use case dotnet hot reload is simply an extended version of **"changing code while debugging line by line"**, That already on dotnet for years. Would love to see it became more useful.

**Comment by davidwengier** [comment]
Thanks for logging the issue @sangeethnandakumar, I wonder if you could provide some more specifics of the issues you're seeing.

> 1. Unable to hot-reload when Lambda expression changes

In general changing lambdas should be allowed, though there are certainly limitations (like changing the return type for example) and some extra things we could allow (eg. https://github.com/dotnet/roslyn/issues/54672). Can you give a code example of your before/after to help identify the exact issue?

> 2. If there's an unused variable which was already on a fun argument, And if we write a new statement inside the fun which uses that variable (while prog is running) hot-reload fails

This is surprising. Again, could you provide a before/after of the change you're making here?

> 3. Request/Response classes, DTOs, Model classes often requires addition/removal of properties as they evolve or while testing with tools like Postman/Swagger etc.. That always need a rebuild

Adding properties should be allowed, but deleting members is definitely a limitation at the moment.

> 4. Adding attributes to class or functions (although is not an often change) is a no no to hot-reload

Adding attributes should be allowed. What runtime are you using, and what .NET version are you targetting? .NET 6 running on Core CLR should support this, but the Mono runtime is not currently able to alter attributes.
