### ISSUE TITLE
VB: Allow return statements in scripts and interactive submissions

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5773]
The return value should be treated as the exit code by the command line host.
In interactive submission the return value is the result of the script execution.

**Comment by tmat** [comment]
@ManishJayaswal @cston For some reason we have decided to not allow return statements in script top-level code. @MadsTorgersen and I think that was unnecessary and in fact against the principle that you should be able to copy & paste code from regular C# code and it should just work as much as we can make the semantics reasonable.

The proposal now is that scripts can return a value. The type of he return expression is the same as the submission result type specified by the returnType parameter of CSharpCompilation.CreateSubmission() method.

**Comment by tmat** [comment]
Will need to adjust ```Compilation.GetSubmissionResultType``` appropriately.

**Comment by ManishJayaswal** [comment]
@tmat @cston yes it makes sense to do this in 1.1.

**Comment by KevinH-MS** [comment]
Moving to 1.2 to allow in VB as well...

**Comment by amcasey** [comment]
Subsumed by https://github.com/dotnet/roslyn/issues/6554.
