### ISSUE TITLE
Show dialog when an item can't be edited because of source control

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#57746]
Originally from https://github.com/dotnet/roslyn/issues/45031#issuecomment-940465085 . Creating a new issue to handle the updated work flow with source control as mentioned below

### Conclusion

There are two issues here: 
1. The git source control provider in visual studio should never say that files are not editable, we will need to track this down separately with the team.
2. We need to have a user experience for what should happen when a workspace update is done that a source control provider does not allow.

For 2 we concluded that the user should be shown a dialog similar to go-to-definitions "invalid identifier" experience:
- User initiates an inline rename session
- Source control does not allow some of the files to be edited
- On commit (enter) the user is shown a dialog saying that some of the files are not editable 

### Discussion
- Andrew: why do we use this is editable service?
  - Jason: some source control systems require an explicit operation to make the file editable on disk. Because this is a server operation we want this to be done all at once, not when the user does something like rename as it can take an arbitrary amount of time. There are also source control systems that allow a file to be "locked" to a single user an cannot be checked out until the server allows it.
- Cyrus: so we should show the user a dialog asking them to check out the files
  - Sam: we should handle this the same way we handle pressing go-to definition on a non-identifier
  - Jon: example user experience
    - User initiates an inline rename session
	- Source control does not allow some of the files to be edited
    - On commit (enter) the user is shown a dialog saying that some of the files are not editable

**Comment by jdlundquist** [comment]
> 1. The git source control provider in visual studio should never say that files are not editable, we will need to track this down separately with the team.

Is this possibly related to this issue?
[Visual Studio 2019 Git plug-in breaks IVsQueryEditQuerySave2 interface contract if Git.Operation.EphemeralEditsUseDirtyAttributeOnly option is defined](https://developercommunity.visualstudio.com/t/Visual-Studio-2019-Git-plug-in-breaks-IV/10111861)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this work, it should be assigned to a person/milestone to be done.
