### ISSUE TITLE
Eliminate SourceKind.Interactive

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5774]
Allow scripts to end with an expression, unless the host specifies the return value type to be Void.

**Comment by tmat** [comment]
@mattwar I think you'll approve :) No more ScriptOptions.WithIsInteractive().

**Comment by tmat** [comment]
FYI @cston @ManishJayaswal @amcasey @genlu @KevinH-MS

**Comment by mattwar** [comment]
:+1: 
:+1:

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/2f6d4739ee3b7ee3cf23de138615d021770982b7
