### ISSUE TITLE
Add fix for value conversion for known types

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#57758]
If [CS1503](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1503?f1url=%3FappId%3Droslyn%26k%3Dk(CS1503)) is encountered for types that have known conversion we should provide a fix.

simple example: 

```cs
var i = 0;
var list = new List<string>{ i }; // CS1503: cannot convert int to string 
``` 

This could easily be fixed by calling `i.ToString()`. 

Needs more design to iterate through possibilities and find if there's similar/duplicate asks.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
