### ISSUE TITLE
Disallow a discard assigns to another discard

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#57791]
**Version Used**: 
VS 17.1 preview 1

**Steps to Reproduce**:

Type code

```csharp
// Weird assignment...
_ = _ = f();

static int f() => 42;
```

SharpLab: please visit [this link](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4H0AEBeTXcBmAFAJQDcAsAFDUACAjAGyawAumxJOAfJgCwAmMkA=).

**Expected Behavior**:

There's nothing good on using `_ = _ = f()` expression, so compiler should disallow us to use a discard `_` assigning to another discard `_` (i.e. the part `_ = _`).

**Actual Behavior**:

Compiler allows us using `_ = _ = f()`, although this expression doesn't make something bad.

**Comment by jaredpar** [comment]
I agree that this a bit non-sensical but the design of discards did not change that `=` still returns a value hence this is legal. We could consider a warning here but I don't think it really meets the bar. It's not producing unintuitive or misleading behavior, it's just a bit non-sensical.
