### ISSUE TITLE
Tab completion in VS2022 not complying with code style

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57800]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Tab-completion-in-VS2022-not-complying-w/1584543)._

---
[severity:It's more difficult to complete my work]
My .editorconfig requires this to be used, but if I'm creating a new property it's often not adding "this." making me have to go back and fix it. The tab completion is otherwise creating expected code.

For example, if I'm working on a WPF control and I create a dependency property, I expect the getter/setter to call this. GetValue and this. SetValue respectively. Tab auto-populates the right getter/setter but without 'this'.

---
#### Feedback Bot on 11/15/2021, 10:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in legacy snippets.
