### ISSUE TITLE
implicit generic type

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#5781]
I've got the following case and i'm wondering as to why i have to specify the second generic type:

```
protected TResult ProviderCallSync<TProvider, TResult>(Func<TProvider, Task<TResult>> callback) where TProvider : class, IProviderDiscovery<TProvider>
		{
			if(callback == null)
				throw new ArgumentException("callback", "callback");

			var provider = GetProvider<TProvider>();
			if (provider == null)
				return default(TResult);

			var task = callback(provider);
			return Task.Run(() => task).Result;
		}
```

While my intellisense does work fine when i enter the second type like:
```
return ProviderCallSync<IProjectStructureProvider, ProjectStructure>(d => d.MyCallAsync())
```

I just can't seem to see why it would be necessary to specify the second parameter.

I've looked into ```Task<T>```, to see how you guys managed to provide a way of not forcing someone to constantly chain specify type parameters and allow for a nice fluently typed API. 

However this seems to be impossible to do for my case. Is there an actual reason i can't just do:

```
return ProviderCallSync<IProjectStructureProvider>(d => d.MyCallAsync())
```

That would be much more convenient to work with, because i don't really want to specify the return type of the method before being able to call it. 

If i recall correctly i've run into this inconvenience several times already, so i thought i might just report it and see if implementing this feature might be possible

**Comment by alrz** [comment]
>```
var task = callback(provider);
return Task.Run(() => task).Result;
```

This is wrong on so many levels.

**Comment by svick** [comment]
This sounds like duplicate of #5153 to me.

**Comment by taori** [comment]
@alrz Certainly is wrong. We've got people here who would just do .Result on it. So i'd rather motivate them to at least use a version which doesn't result in async deadlock on synchronization context, if they still can't figure out how to convert code to async after the third explanation :) Also you can't use async on property getters yet afaik

**Comment by taori** [comment]
definitely looks like a duplicate of #5153 so i'll just close this.
