### ISSUE TITLE
List-patterns: lowering assumes the conversion from int to Index will use the implicit conversion operator

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57825]
In `BindLengthAndIndexerForListPattern` we do:
`_ = GetWellKnownTypeMember(WellKnownMember.System_Index__op_Implicit_FromInt32, diagnostics, syntax: node);`

From [Aleksey](https://github.com/dotnet/roslyn/pull/57318#pullrequestreview-808648391): Just to clarify. What bothers me here is the fact that lowering never uses this member explicitly, it relies on conversion classification instead, etc. So, we are making an assumption that all that complicated machinery ends up using the method. However, there is no actual guarantee that that would be the case. For example, if method is not marked with special name flag, it won't be considered as a valid conversion operator.

As part of this, we should confirm whether we want list-pattern to lower as `expr[0]` (using conversion from int to Index) or `expr[new Index(0)]` (using constructor).

**Comment by jcouv** [comment]
From discussion with Aleksey, we're leaning towards aligning on constructor. This involves less machinery (no conversion classification) and aligns with what we do for from-end Index values. We'll update the spec to clarify accordingly.
@333fred Sounds okay?

**Comment by 333fred** [comment]
> From discussion with Aleksey, we're leaning towards aligning on constructor. This involves less machinery (no conversion classification) and aligns with what we do for from-end Index values. We'll update the spec to clarify accordingly. @333fred Sounds okay?

That sounds good to me.

**Comment by jcouv** [comment]
Mads also agreed on aligning on constructor (rather than implicit conversion).
