### ISSUE TITLE
Feature Request: Add or Unify "Add Await" and "Introduce local for" in context actions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57849]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Request:-Add-or-Unify-Add-Await/1562859)._

---
I hope I named the functions appropriately (since I use the Italian localisation mostly)

TL;DR;
I almost always have to go to context actions twice to "Add await" and "Introduce local for". 
I feel a "Add await and introduce local" action to context actions on async methods would be beneficial to many like the one that adds await and ConfigureAwait.

Longer version:
Say that I am typing in an async method, which accesses other async methods defined somewhere else.
If I know all the types involved I might type in order:
var someHelpfulNameBasedOnTheReturnedObject = await _someService.SomeMethodWithASpecificReturnTypeAsync();

and go on my merry way. 
However very often (using other people's codebases, or libraries that none of us have all the time to explore in depth advance, or with incomplete knowledge of all the returned types, or even which methods will or won't be async (due to not everyone sticking to tailing with an "Async", I often start typing while waiting for intellisense to narrow done the selection:  
_someService.Som..
_someService.SomeMethod

_someService.SomeMethodAsync(params...); 
There is a "Add await for" ok, very useful... and I get... 
await _someService.SomeMethodAsync(params...); 
Then I have to go to context actions again and ask: "Introduce local for..." 
to finally get: 
var something = await _someService.SomeMethodAsync(params...); 

this feels very drawn out, I think it would be beneficial to add a "Add await and introduce local" all in one go context action. 

Thanks in advance, 
Paolo Manili

---
#### Feedback Bot on 10/26/2021, 01:29 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by jmarolf** [comment]
My expectation here is that if  "Introduce local for..." is offered and you are inside of an async method _and_  the expression returns an awaitable type we should automatically add the await.

so if you have:
```csharp
async Task M()
{
    _someService.SomeMethodAsync(params...); // Introduce local for...
}
```

the default fixer does 
```csharp
async Task M()
{
    var something = await _someService.SomeMethodAsync(params...);
}
```

I would expect cases where someone is inside of an async method and does not want to await task-like-types when creating new locals is extremely small

**Comment by sharwell** [comment]
> My expectation here is that if "Introduce local for..." is offered and you are inside of an async method and the expression returns an awaitable type we should automatically add the await.

I'm concerned by how subtle the semantics change here is, and would almost prefer we investigate the use of postfix completion (e.g. `.await.var`) instead of changing the code fix to try and automatically combine them.

**Comment by dibarbet** [comment]
Design review conclusion:

We would like to tie this issue to a larger story for rationalizing unassigned values and assignments to them.  This could be part of a code fix for unused expression values that awaits and assigns it to a variable.  See (https://github.com/dotnet/roslyn/issues/58141)

In the meantime, we'd like to suggest trying the await postfix in completion.
![async_suffix](https://user-images.githubusercontent.com/5749229/144935971-1edaa48b-9014-4d78-b764-1663d40769f8.gif)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
