### ISSUE TITLE
When auto implementing an interface or abstract class, I would like the ability to choose on the fly between auto generated and throwing properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57844]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-auto-implementing-an-interface-or-a/1570136)._

---
You have the ability to change the default between throwing properties and auto generated properties under options when auto implementing an interface or abstract class.  In addition to the default, I would like the ability to choose on the fly between auto generated and throwing properties when auto implementing an interface or abstract class.

---
#### Feedback Bot on 11/2/2021, 07:49 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
