### ISSUE TITLE
C# 10 File Namespace usage autoformat

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-10-File-Namespace-usage-autoformat/1578829)._

---
It would be nice if, when adding the semi-colon to the end of the namespace line, the file would autoformat; removing the namespace brackets and moving the class to the left automatically.

---
#### Feedback Bot on 11/10/2021, 11:22 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by CyrusNajmabadi** [comment]
That's a nifty idea!
