### ISSUE TITLE
Copy data type name from variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57842]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Copy-data-type-name-from-variable/1577237)._

---
It would be very useful to be able to right-click on a variable name and copy the data type's name to the clipboard so it may be pasted elsewhere.

For example, if I have:
var item = GetItem(), where GetItem() returns some type, UserDefinedType, and I want to use this type in the parameter list of a new method like:
private void NewMethod(UserDefinedType udt){ }, it'd be nice to be able to copy "UserDefinedType" from the variable and paste it into the parameter list.

Sometimes it is inconvenient to rely only on IntelliSense, as it can be difficult to remember exactly what the name of the data type is, especially if it's a long name, and it's even less convenient to have to navigate around in the code to copy the data type from the method definition.

---
#### Feedback Bot on 11/9/2021, 11:02 PM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by dibarbet** [comment]
Design review conclusion:

We would like to add the ability to copy items in quick info (with a glyph to indicate as such).  This should hopefully address the immediate need to copy the type name without cluttering the context menu with another option.

We would also like to take on a larger investigation on richer copy and pasting.  This could include things like type name expansion, using simplification, and code style support.  See https://github.com/dotnet/roslyn/issues/49442

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
