### ISSUE TITLE
c# Intellisense insert a new row pressing enter while it is disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57858]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/c-Intellisense-insert-a-new-row-pressin/1587766)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.1.0 Preview 1.1]
Hi,

in VS 2022 it always enters a new line in intelligence although i disabled it in the settings 
TextEditor-->C#-->IntelliSense-->Enter key behavior-->Never add new line on enter

In VS 2019 it works perfekt on the same machine. I hope you can fix this.

Thx
Eric

---
#### Feedback Bot on 11/17/2021, 08:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Interesting.  We don't control thsi now as i think this all goes through the editor with async completion, right @genlu ?  Do we need to inform them of this behavior?

**Comment by genlu** [comment]
I couldn't repro this in latest build (17.1 p2)
