### ISSUE TITLE
Simplify interpolation (IDE0071): Should it not flag ToString("with-an-argument")?

### ISSUE THREAD

**Issue by jwatkin** [dotnet/roslyn#57851]
**Brief description:**

The analyzer is currently flagging: $"Some text here: {DateTime.Now.ToString("s")}" with Simplify interpolation (IDE0071). The "ToString" is necessary because it contains an argument. Should the analyzer stop flagging cases where ToString() contains an argument?

**Languages applicable:**

I've only tested this with C# and Visual Studio 2019.

**Code example that the analyzer should report:**

Suggesting that this not be flagged: $"Some text here: {DateTime.Now.ToString("s")}" 

**Additional information:**

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by svick** [comment]
When I tried it, the code fix simplified the code to `$"Some text here: {DateTime.Now:s}"`, which preserves the `s` format string. So I think the diagnostic is correct here.

**Comment by jwatkin** [comment]
Hi svick,

Thank you for kindly pointing that out. {DateTime.Now:s} looks correct to me too.

I've just started using the analyzers and hadn't yet discovered the Light Bulb tool suggestions until you pointed that out. I had only been using the linked web pages for an explanation which of course doesn't have my code's context so wasn't able to offer that specific fix in this case.

Jim
