### ISSUE TITLE
Exclude switch arms from brace placement options

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#57854]
Related to https://github.com/dotnet/roslyn/issues/57736#issuecomment-973029128 and #39557.

The `{` of a pattern should not be moved to the preceding line by the formatter in the following case:

1. The `{` is the first token of a switch arm
2. The `{` is the first token on the line where it appears
3. The containing switch expression already spans multiple lines

**Comment by maloo** [comment]
Can this be included in a patch release of .NET 6 SDK since this is was a breaking change (bug?) from .NET5? Many CI systems use dotnet format, and they are all broken now using .NET 6 SDK. Previously it was a separate tool and easier to select specific version.

**Comment by maloo** [comment]
"all broken", those that use { on previous line

**Comment by maloo** [comment]
@sharwell  Any reason this is still not merged? We keep trying to enable dotnet format every release and it would be nice to get it for dotnet 8 at least. This has been broken since dotnet 6 release...
