### ISSUE TITLE
"Add 'DebuggerDisplay' attribute" might not be respecting user preferences

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#57867]
https://github.com/dotnet/roslyn/blob/837e83d70c58229fb20251c4e9f9e03fb1ce3f03/src/Features/Core/Portable/AddDebuggerDisplay/AbstractAddDebuggerDisplayCodeRefactoringProvider.cs#L164

This will always generate `string`, even if the user prefers `String`. See https://github.com/dotnet/roslyn/pull/19242.

I think the `CSharpSyntaxGenerator.TypeExpression(SpecialType)` API is what needs modification here to respect user preferences. Not that we go and use the other overload.

cc @sharwell @CyrusNajmabadi  (feel free to change the issue title as appropriate, depending on whether you agree we should modify the `TypeExpression` method or just fix the refactoring)

**Comment by CyrusNajmabadi** [comment]
in general, i'd only want us to do anything here if we had actual complaints from users :)

**Comment by Youssef1313** [comment]
I feel like `TypeExpression(ITypeSymbol)` and TypeExpression(SpecialType)` should do the same. Esp that they're public APIs. It's not good if I go and refactor some code to call the second overload and find a behavioral change. That's one point of view. The other point of view is "respect user preferences when possible".

If it's decided to keep everything as is, at least both overloads should have doc comment that say whether it respects user preference or not.

**Comment by Youssef1313** [comment]
Regarding an actual complaint, there was in past a *similar* one: https://github.com/dotnet/roslyn/issues/19174

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
