### ISSUE TITLE
Rename tracking conflicts with Generate Method and cannot be disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57876]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-quick-fixes-are-annoying-and-sugg/1588476)._

---
When I develop I usually write the code calling a method and then I create it using the "Generate method..." but in VS2022 the first quick fix suggestion is not what I expect and instead it suggest that I should do a weird rename. and it does not make any sense to me to have this fix at the top. The rename is just pointless and makes no sense to me. 

My suggestion is to put "Generate method" at the top, as I find it to be the more obvious fix that I would like to do in this situation s my attached picture show.

---
#### Feedback Bot on 11/18/2021, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/18/2021, 10:14 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I've hit this numerous times as well. For users who only _ever_ perform rename operations through <kbd>F2</kbd> or <kbd>Ctrl</kbd>+<kbd>R</kbd>, <kbd>Ctrl</kbd>+<kbd>R</kbd>, it doesn't make sense to leave rename tracking enabled where it interferes with other light bulb operations. An option should be provided to disable the inline rename tracking altogether.

**Comment by JoeMarkov** [comment]
I find the main issue is that if you accidently hit the rename fix, then it renames existing code and introduces new bugs in my code. The rename does not make any sense to me, if feels very random what it do rename.

**Comment by CyrusNajmabadi** [comment]
Rename tracking should be low pri on references, and the same pri as today on declarations

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani who is looking into low-pri codefixes/refactorings.

**Comment by mavasani** [comment]
Need a design discussion to decide the approach we would like to take here:
1. Add an option to disable rename tracking code action
2. Change rename tracking to be a low pri refactoring on references and high pri refactoring on declarations
3. Any other suggestions?

**Comment by JoeMarkov** [comment]
For me, (with the little i have used it ) I found the renaming feature a bit confusing of what it actually renamed. When I hit it by accident it renamed something totally unexpected.

my main wish is that the rename is not the top first alternative in the list of possible refactorings. The generate type I feel is what most wants to use.

**Comment by CyrusNajmabadi** [comment]
@JoeMarkov please file issues with examples showing what you mean. 'rename' should update the declaration name of Symbol and all the references to that symbol. 

If you're saying something "totally unexpected"  that it "introduces new bugs in my code" or that it "feels very random" then please file issues so we can investigate. Otherwise there's not much we can do with the feedback as is currently. Thanks!

**Comment by CyrusNajmabadi** [comment]
> Any other suggestions?

I would like to potentially have the option distinguish between declarations and references. I also use this feature to rename decls. I never do it to rename references. 

Switching to low pri would help. But I wouldn't mind disabling for references as well.

**Comment by ryzngard** [comment]
@mavasani I'm happy to champion this in design review.

1. I'm not sure about priority change. From data, rename tracking is the 5th most popular applied fix, and not undone that often. Here's data from query today 

| Applied_CodeFix                       | Times_Applied |
| ------------------------------------- | ------------- |
| Add Import (Project Symbol Reference) | 87663384      |
| Generate Type                         | 12418350      |
| Generate Parameterized Member         | 7256762       |
| Generate Variable                     | 6796349       |
| Rename Tracking                       | 6237768       |


2. I propose we add a combobox with the following settings for rename tracking: 
	* All References
	* Declarations Only
	* Disabled

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback or movement.  If this needs to happen, it should be assigned a milestone.
