### ISSUE TITLE
Update corefx dependencies to 6.0.0

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#57875]
VS is moving to 6.0, we should keep Roslyn in-sync

Specifically this should include:
- System.Collections.Immutable
- System.Reflection.Metadata

**Comment by RikkiGibson** [comment]
Based on #58570 it looks like we'll need to entirely move off of .NET Standard 1.3 and NET 4.5 in [Microsoft.CodeAnalysis.Debugging.Package.csproj](https://github.com/dotnet/roslyn/blob/main/src/Dependencies/CodeAnalysis.Debugging/Microsoft.CodeAnalysis.Debugging.Package.csproj). I thought the debugger recently made a change which should make it possible for us to do this.

**Comment by RikkiGibson** [comment]
@genlu is there any timeline in which this needs to happen?

**Comment by alrz** [comment]
> VS is moving to 6.0, we should keep Roslyn in-sync

Is there a hidden meaning here or it's just what it says?

**Comment by RikkiGibson** [comment]
I wasn't aware of any other context. I think keeping the versions in sync here just helps us build the product in a more consistent/predictable way.

**Comment by RikkiGibson** [comment]
It's possible that forgetting about this issue has lead to #63780 :/

**Comment by RikkiGibson** [comment]
Closing as stale.
