### ISSUE TITLE
Debugger crashes while trying to access a multidimensional array by executing the code step by step

### ISSUE THREAD

**Issue by unseeme** [dotnet/roslyn#57895]
**Version Used**: 
.NET 5.0
Visual Studio 2019 v16.11.7

**Steps to Reproduce**:

1. Define a multidimensional array, of any type, with arbitrary dimensions and initialize it, with arbitrary values.
2. Set a breakpoint in the previous statement.
3. Execute the code in step by step mode, by pressing F11.

Example:

```
class Program
		{
		static void Main(string[] args)
			{
			// When a breakpoint is set at the next statement,
			// the debugger crashes while executing step by step (presing F11).
			// If the progam is executed without breakpoints, execution
			// behaves as expected, without crashing.
			string[,] array = new string[3, 2] { { "this", "is" }, { "a", "debugger" }, { "crashing", "test" } };

			// This will also crash if executed step by step
			Console.WriteLine(array[0,0]);
			}
		}
```

**Expected Behavior**:

Code is executed without crashing the debug session

**Actual Behavior**:

The debugging session crashes if:

- The execution path reaches a statement where a multidimensional array is read or written, AND
- Such statement is executed in step by step mode (by setting a breakpoint and then pressing F11)

![Crash1](https://user-images.githubusercontent.com/94723727/142705481-ada646f8-8f8c-45d2-a586-2012facf6055.png)
![Crash2](https://user-images.githubusercontent.com/94723727/142705484-3214bae6-443b-4620-9d93-479ecdda0ae9.png)

**Comment by davidwengier** [comment]
This doesn't repro for me in Visual Studio 2022 so I'm going to go ahead and close it as fixed.
