### ISSUE TITLE
[Proposal] Compiler generated `IEnumerator` implementations should be `struct` sometimes

### ISSUE THREAD

**Issue by corranrogue9** [dotnet/roslyn#57903]
---
name: 💡 Compiler generated `IEnumerator` implementations should be `struct` sometimes
about: Garbage collection is not always required when a method which uses `yield return` returns an `IEnumerable`
---

From what I can tell, when `yield return` is used in a method implementation, the compiler always generates a `class` implementation of the corresponding `IEnumerator`. However, often the returned value is immediately enumerated. Garbage collection will need to run at some point because the return value is a `class`. If it were instead a `struct`, then no garbage collection would be needed for these cases. It similarly doesn't always make sense to have a `struct` given that are often a large number of fields in the generated `IEnumerator`. However, the compiler could generate both a `class` and a `struct` and use the one that is appropriate for the caller's situation (i.e. Generate `class <MyEnumerator_class><T> : IEnumerable<T>, IEnumerator<T>` *and* `struct <MyEnumerator_struct<T> : IEnumerable<T>, IEnumerator<T>` and during compilation, select the "correct" one based on the situation of the caller). 

As an example, `System.Linq.Enumerable.Select` would generate both `<Select_class><T>` and `<Select_struct><T>` and `System.Linq.Enumerable.Where` would generate both `<Where_class><T>` and `<Where_struct><T>`. Then, the following:

```
foreach (var element in source.Select(_ => _))
{
}
```

would translate to:

```
foreach (var element in new <Select_struct><T>(source, _ => _))
{
}
```

because the result of the selection will not be passed to any other functions, so there is no need to allocate it on the heap. Similarly, the following:

```
foreach (var element in source.Select(_ => _).Where(_ => true))
{
}
```

would translate to:

```
foreach (var element in new <Where_struct><T>(new <Select_class><T>(source, _ => _), _ => true))
{
}
```

because the result of the selection is being passed into the `Where` clause, so it makes sense to not copy all of the data onto the stack a second time, but the result of the where is being immediately enumerated, so it doesn't need to be allocated onto the heap, which would result in garbage collection.

**Comment by CyrusNajmabadi** [comment]
Producing a struct won't be helpful as the signature returns an `IEnumerable<T>`.  As this is an interface, it will always be on the heap and will just be boxed if it were a struct. 

We would need an entirely new language feature (which we often call 'Shapes') to allow something to be passed out which would be known to be foreach'able, but which wouldn't have the interface requirement that would place it on the heap.

**Comment by Djoums** [comment]
Since we can already use duck typing for returning structs from GetEnumerator(), could that also be applied to functions with yield return ?

**Comment by CyrusNajmabadi** [comment]
You'd need a syntax for this and a way to name that struct.

**Comment by RikkiGibson** [comment]
It might be good to open a discussion in csharplang for this. https://github.com/dotnet/csharplang/discussions

**Comment by jaredpar** [comment]
As @CyrusNajmabadi mentioned this API returns a `IEnumerator<T>` hence the `struct` based implementation has no real benefit here. It only has benefit if we expose the generated enumerator as an accessible type. That creates a lot of complexity here and it also makes it a leaky abstraction. It means that you cannot replace a `iterator` with a hand written enumerator at a later time because it would be a breaking change. 

Closing as I don't see a particular path forward for this.
