### ISSUE TITLE
AdditionalFiles or similar for codefix providers

### ISSUE THREAD

**Issue by smhinsey** [dotnet/roslyn#57907]
I haven't been able to find any documentation on this subject. Is there a feature similar to an analyzer's AdditionalFiles support for codefix providers? If so, what's the API? If not, are you aware of any workarounds to accomplish a similar task? We have a situation where we want to be able to leave an analyzer configured to report diagnostics but selectively disable the codefix suggestions in an overridable way.

**Comment by CyrusNajmabadi** [comment]
I'm not quite sure what you're asking for.  However, a CodeFixProvider is handed a CodeFixContext.  That object exposes the `.Document` that the issue was reported in.  From the Document you can get the `.Project` which contains things like `.AdditionalDocuments`.

**Comment by smhinsey** [comment]
Perfect, thanks.
