### ISSUE TITLE
Navigate to original source from metadata fails to handle documentation comments

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#57924]
Doc comments are now interleaved with members.  Causing:

![image](https://user-images.githubusercontent.com/4564579/142931240-f2359a69-7a41-4919-9c6b-58535427e2e1.png)

This is extremely hard to read, and breaks the prior MAS behavior where we would have hte doc commands collapsed into a small region preceding the symbol *on the same line*.

**Comment by Dreamescaper** [comment]
FWIW, personally I like it much better now (maybe I'd prefer to have line break between members for readability).

**Comment by CyrusNajmabadi** [comment]
@Dreamescaper It's a regression over an explicit design we intentionally had.

**Comment by davidwengier** [comment]
Looks like this only happens when navigating to embedded source from PDBs, which I've been meaning to bring to a design meeting anyway, so thank you for logging :)

**Comment by davidwengier** [comment]
For example, going to definition on a different type doesn't repro this. Including this here for an example of what Cyrus is expecting:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/754264/142940533-59ead04a-9d67-4bdf-849d-dfad3153767a.png">

**Comment by sharwell** [comment]
This line needs to be updated to support documentation comments (specifically ones that have not been reformatted as single line comments during Metadata As Source production):
https://github.com/dotnet/roslyn/blob/948cccc09fa88a638bc6c67871c37fec91742c99/src/Features/CSharp/Portable/Structure/CSharpStructureHelpers.cs#L278

**Comment by CyrusNajmabadi** [comment]
![image](https://user-images.githubusercontent.com/4564579/143136009-925a2866-3cba-4db2-9aa2-4b9ebe181f4f.png)
