### ISSUE TITLE
Formatting adds additional new line trivia to a pragma suppression fix

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#5793]
1. Create a C# classlibrary project with below code:
   
   ``` c#
   using System;
   public class Class : IDisposable
   {
       private readonly Class x1;  // comment
       private readonly Class x2;
   
       public void Dispose()
       {
           throw new NotImplementedException();
       }
   }
   ```
2. Add the [FxCopAnalyzers](http://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) nuget package to the project
3. See CA2213 fire on variable `x2`. Go to the lightbulb and select `Suppress CA2213` -> `in Source`

Expected fix:

``` c#
    private readonly Class x1;  // comment
#pragma warning disable CA2213 // Disposable fields should be disposed
    private readonly Class x2;
#pragma warning restore CA2213 // Disposable fields should be disposed
```

Actual fix:

``` c#
    private readonly Class x1;  // comment
#pragma warning disable CA2213 // Disposable fields should be disposed


    private readonly Class x2;
#pragma warning restore CA2213 // Disposable fields should be disposed
```

I verified that the pragma suppression fixer correctly adds a **single** EndOfLine elastic marker trivia after the pragma disable directive, but it seems the Formatting annotation added to the pragma directive causes it to add couple of additional EndOfLine trivia.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
