### ISSUE TITLE
Add an option for decompiled view to have everything expanded

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn#57931]
Currently in metadata-as-source view all definitions are collapsed by default. I would prefer an option to be able to make it the opposite - to have everything expanded.

Let me explain my thoughts. Metadata-as-source is used for two reasons:
- Investigate how method/property/etc is implemented.
I think it's obvious here - I'd prefer to see the code and documentation straight away, not to expand it (either by clicking twice on small easy-to-miss `...` block, or once on ever smaller `+` button).

- Take a look at the general type structure
This one is not that obvious, but still doesn't work great for me. The thing is that this reason happens for regular source code files as well, and am used to invoke Collapse-to-definitions action. And currently the same Go To Definition action leads to two completely different results and experiences depending on whether the source code is in the solution or somewhere else. I would prefer to have decompiled view to be as close as possible to a regular source code view instead.

**Comment by davidwengier** [comment]
I believe this is Tools -> Options -> Text Editor -> C# -> Advanced -> Enter outlining mode when files open, but I'm not sure if that controls more than just metadata.

**Comment by Dreamescaper** [comment]
Ha. My bad. Thanks a lot)))
