### ISSUE TITLE
Investigate update FAR-like features to show hits in shared-projects, not the projects the shared filed are linked into

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#57952]
For context:

![image](https://user-images.githubusercontent.com/4564579/143133044-6ead1a77-c08b-4710-a51e-42ce9ff81d83.png)

These hits are all from the same files in a single shared project.  Race conditions cause us to show the 4 hits as two sets of two hits in disparate projects.  However, even if we addressed the race conditions, we'd still just show the hits in one project or the other.

A cleaner approach might be if we could actually represent these as a single set of hits just in the shared-project itself.

--

There's no direct way roslyn currently to do this.  But @jasonmalinowski mentioned:

> Conceptually it wouldn’t be difficult to add an API to VisualStudioWorkspace or something that given a DocumentId would give you the shared project info (which I guess is a IVsHierarchy or a special IVsProject GUID)

**Comment by jasonmalinowski** [comment]
Something @dpugh might also know is if there's some other grouping support to make this a bit easier. I know it's been discussed in the past but not sure where that landed.

**Comment by CyrusNajmabadi** [comment]
Closing as we updated FAR to be better here about collapsing resuilts.
