### ISSUE TITLE
Roslyn emits unnecessary conv.u opcodes over transient pointers

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#57970]
**Version Used**: latest `main` on sharplab.io (d1a34b072891080aeec4925c3ed18a33908637f5)

## Overview

It seems that Roslyn is currently generating a lot of `conv.u` opcodes that are not needed as per ECMA spec.

Consider this code snippet:

```csharp
static ReadOnlySpan<byte> Test() => new byte[] { 1, 2, 3, 4 };
```

The generated IL is this:

```asm
ldsflda int32 '<PrivateImplementationDetails>'::'9F64...'
ldc.i4.4
newobj instance void valuetype ReadOnlySpan`1<uint8>::.ctor(void*, int32)
ret
```

There's (correctly) no `conv.u` after the `ldsflda`, because according to the spec:

> **I.12.3.2.1: The evaluation stack**
> "Instructions that create pointers which are guaranteed not to point into the memory manager’s heaps (e.g., `ldloca`, `ldarga`, and `ldsflda`) produce transient pointers (type \*)  that can be used wherever a managed pointer (type &) or unmanaged pointer (type native unsigned int) is expected."

This begs the question: doesn't that mean that Roslyn currently generates unnecessary `conv.u` opcodes whenever you're taking eg. the address of a local? This is especially common in lower level code doing interop. For instance, consider this:

```csharp
static unsafe void Test1()
{
    int x;
    
    Test2(&x);
}

static unsafe void Test2(int* p)
{
}
```

The codegen for `Test1` is as follows:

```asm
ldloca.s 0
conv.u
call void '<Program>$'::'<<Main>$>g__Test2|0_1'(int32*)
ret
```

But... According to ECMA then isn't that `conv.u` unnecessary given that `ldloca.s` here returns a transient pointer which is fine to pass directly where a raw pointer is expected? The memory location here is guaranteed not to be in a managed heap.

Seems like a potential binary size optimization for managed assemblies, and could also possibly save time in the JIT's importer?
Or, am I reading this wrong and there's a specific reason why `conv.u`-s are emitted in these cases?

**Comment by jkotas** [comment]
We have determined in https://github.com/dotnet/runtime/issues/62784 that the paragraph that talks about transient pointers in bogus.

ECMA-335 generally allows implicit conversion of unmanaged pointer to managed pointers (for example, look for "Correct CIL also allows a native int to be passed as a byref (&);"), but not vice versa. I do not think that the proposed optimization is valid given how things are specced currently. We would likely see JITs to choke on it.
