### ISSUE TITLE
Roslyn dosn't work on VSIX

### ISSUE THREAD

**Issue by Makkawi011** [dotnet/roslyn#57971]
Hi , I'm trying to build a single file generator ( VSIX ) in C#, the problem is that I can't get a Syntax tree using roslyn  . Is there a useful way?!

 Note: I tried
 SyntaxFactory.ParseSyntaxTree ("code" ) and CSharpSyntaxTree.ParseText ("code")

Both failed ...!

Another note : I'm trying to make the debug work as long as I'm not trying to call functions from Microsoft.CodeAnalysis

Another note: I use microsoft visual studio enterprise 2019 version 16.10.2
And microsoft .NET Framewrok version 4.8.03752

**Comment by CyrusNajmabadi** [comment]
> Both failed ...!

Can you provide more information?  how did they fail?

**Comment by Makkawi011** [comment]
I am a computer engineering student, I am trying to develop a tool like Code map, code map that analyzes the code and gives (graph) dgml. I'm trying to parse the code and it doesn't work, frankly, I don't know the exception that happens because the debug in the VSIX project is different from what I know in other projects, but I noticed that the debug doesn't take me to the function as long as it makes an exception because of the Microsoft.CodeAnalysis library, And I don't know what to do...

**Comment by Makkawi011** [comment]
Thank you , in the update visual studio 2022 and .net 6 the problem is solved.
