### ISSUE TITLE
Missing quick action to clean up try/finally or try/catch/finally with an empty finally block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57973]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-quick-action-to-clear-try-with-e/1593773)._

---
[severity:It bothers me. A fix would be nice]
ReSharper has a refactoring option to automatically fix code like this:

```csharp
try
{
 // do something
}
finally 
{
}
```

The ReSharper refactor action will remove the entire try/finally block preserving the code inside.

Alternatively if you have code like this:

```csharp
try
{
  // do something
}
catch
{
  // handle
}
finally
{
}
```

The ReSharper refactor action will remove the `finally { }` statement preserving the try/catch.

Visual Studio does not have an equivalent quick action for this.

---
#### Feedback Bot on 11/23/2021, 10:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by JoeRobich** [comment]
### Design Meeting Notes (2022/06/27)
Mark as help wanted

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
