### ISSUE TITLE
Missing quick action for CS0546 ('accessor' : cannot override because 'property' does not have an overridable set accessor)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#57972]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-quick-action-for-CS0546-access/1593769)._

---
[severity:It's more difficult to complete my work]
When overriding an accessor from a base class and it causes a CS0546 error, I expect there to be a quick action to fix the base class definition without me having to manually do it, but there is no quick action here:

! [image.png] (https://aka.ms/dc/image?name=Bdd36f04e98474ec9b2028766ff58f0e2637733078488266391_20211123-154408-image.png&tid=dd36f04e98474ec9b2028766ff58f0e2637733078488266391)

This is something that ReSharper supports as part of its refactoring actions.

---
#### Feedback Bot on 11/23/2021, 10:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
