### ISSUE TITLE
why can't the source generator be used in the net6.0? 

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#57990]
[Source Generator Guide](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview#get-started-with-source-generators)

**Comment by Youssef1313** [comment]
Visual Studio is still based on .NET Framework, and the source generator needs to be run in VS, so you can't target .NET 6.0.

**Comment by neon-sunset** [comment]
This is a design *oversight* and prevents users from explicitly opting out of supporting legacy toolset.
