### ISSUE TITLE
Source Generators: Intellisense is sluggish

### ISSUE THREAD

**Issue by amelmusic** [dotnet/roslyn#58008]
We have somewhat advanced scenario with multiple csprojs involved.
There is 
 - Model.csproj
 - Interfaces.csproj
 - Services.csproj
 - WebAPI.csproj

In model for eg. we annotate class with"Behaviour(CRUD)". which generates CRUD interface inside interface.csproj and implementation inside services.csproj and REST api wrappers inside WebAPI csproj. Each of them is dependent on previous one and since we can't have sequence in generators, we've splitted them in multiple projects. 

In order to generate upper layer eg. REST API, we read interface declaration and generate api. This of course requires us to publish data to disk and from the upper layer we read source code from disk and generate api's .

I believe source generators are triggered on every keystroke and since this is a heavy process it takes a while and therefore intellisense most of the time shows partial results or none at all.
As per documentation, source generators should be triggered only at build time but that's not the case.

As a workaround we have implemented it as mentioned [here](https://github.com/dotnet/roslyn/issues/44093#issuecomment-976814844):

Is there a way to disable Intellisense rebuild during DesignTimeBuild phase and do it only when user builds solution?

**Version Used**: 
4.0.1

**Expected Behavior**:
 Intellisense is not impacted if we have heavy source generators.

**Comment by jinujoseph** [comment]
@sharwell for info

**Comment by jasonmalinowski** [comment]
@amelmusic Are you using the newer incremental generator API, or are you using the original one?

**Comment by jasonmalinowski** [comment]
Also can you clarify this bit?

> This of course requires us to publish data to disk and from the upper layer we read source code from disk and generate api's .

Are you doing your own writing to/from disk or doing something else?

**Comment by sharwell** [comment]
> I believe source generators are triggered on every keystroke and since this is a heavy process it takes a while and therefore intellisense most of the time shows partial results or none at all.

Note that this is already implemented as suggested for IntelliSense/completion (results from an earlier source generator pass are automatically carried forward if the new source generator pass has not yet completed).

> This of course requires us to publish data to disk and from the upper layer we read source code from disk and generate api's .

Can you confirm that you are using `IIncrementalGenerator` and not `ISourceGenerator` for the source generator? The older `ISourceGenerator` interface is _impossible_ to scale efficiently, so until implementations are using `IIncrementalGenerator` our options are limited.

**Comment by amelmusic** [comment]
Yes, I can confirm that we are using `IIncrementalGenerator`
As for reading from disk part; Challenge is that in order to generate source code I need to read generated class from another csproj. For example, I have xCommerce.Model.csproj and inside that project we have class like this:
`    [ModelGenerator(Behaviour = EntityBehaviourEnum.CRUD)]
    public partial class Distributor
    {
        [Key]
        [StringLength(100)]
        public string Id { get; set; }
        [Required]
        [StringLength(50)]
        [RequestField(RequestName = "Insert")]
        [RequestField(RequestName = "Update")]
        public string Name { get; set; }

        [RequestField(RequestName = "Insert")]
        [RequestField(RequestName = "Update")]
        public bool IsActive { get; set; }

        [ChildModel(Mode = ChildModelMode.Insert, MapTo = "DistributorShippingMethod", ChildRequestName = "Insert", CalledFrom = new[] { "Insert", "Update" })]
        [ChildModel(Mode = ChildModelMode.Update, Key = "Id", KeyType = "int", MapTo = "DistributorShippingMethod", ChildRequestName = "Update", CalledFrom = new[] { "Update" })]
        [ChildModel(Mode = ChildModelMode.Delete, Key = "Id", KeyType = "int", MapTo = "DistributorShippingMethod", ChildRequestName = "Delete", CalledFrom = new[] { "Update" })]
        public virtual ICollection<DistributorShippingMethod> DistributorShippingMethod { get; set; }
    }`

Based on this information "interfaces project" generates Interfaces, API project generates REST Apis and so on.
Logic essentially goes like this:
 - when interfaces source generator is started, read all *.cs files from "Model" project, then parse classes to extract "[Model]" attribute, and based on that we generate CRUD / State machine / workflows etc.

Generally, I'm trying to reproduce pattern that I wrote with good old T4 that I described here: https://www.infoq.com/articles/T4-Rest-Code-Generation

Also, I replicated this by using https://github.com/AArnott/CodeGeneration.Roslyn, which works fine as Intellisense and source code is generated only during build.

Ideally, for my scenario, code should be generated only during build, but using "DesignTime" flag seems not to work for VS2022. It looks like value is cached and not reflecting real state.

**Comment by sharwell** [comment]
@amelmusic For that, the approach to take would be:

Add the model files to the project containing the generator. The model files are read by the incremental generator, and subsequent steps only need to run if/when those files change.

**Comment by amelmusic** [comment]
@sharwell it's highly impractical for me to list all files as I have ~100 files and I would have to duplicate entries across 4 csproj files which is prone to errors.

Is it possible to consider listing folders instead of files. This way I would just mention folder name.

**Comment by amelmusic** [comment]
@jasonmalinowski yes, it does.
So model.csproj contains "DTO", Search objects, CRUD/Workflow requests. Via attributes we annotate default logic. ie "Customer DTO" will be crud, and therefore we generate ICustomer service in interfaces.csproj and in CustomerService in services.csproj along with DTO -> Database object mapping. Then of course, you can write additional logic (specific for eg for workflow gateway etc)

**Comment by amelmusic** [comment]
@PathogenDavid thank you, that works. However, intellisense still feels slugish sometimes as there is lots of processing.

I've noticed that sometimes if i type, everything works properly, but if I for example quickly delete . and write it again, intellisense will not show completion. Sometimes, I will see only limited number of options instead of full one and after 5 seconds, full list will appear.

**Comment by sharwell** [comment]
The next step is making sure the incremental steps of the pipeline are constructed such that they effectively use the caching layers provided by the compiler. Each step of the pipeline needs to have the ability to correctly identify "equal" data to know when later steps can be skipped. An example of this can be seen in https://github.com/microsoft/vs-extension-testing/commit/510ce3754255acde37ae5f963ca7088fef3536eb; prior to this change the source generator would re-run all the steps after every edit because the default implementation of equality for `ServiceDataModel` and `ReferenceDataModel` used reference equality, which prevented the cached values from ever being used.

**Comment by jasonmalinowski** [comment]
@amelmusic: if your DTO objects are public and the attributes are sufficient for the other projects to work off of, are your downstream generators then just looking at the symbols w/ attributes or are they still trying to read your model files a second time? You can view public types from your dependencies in a generator too. This may also make it a bit easier for you to optimize as @sharwell was describing since I think you can have your generator only re-trigger on a dependency change too.

**Comment by amelmusic** [comment]
@jasonmalinowski let me try that and I will let you know. If all goes well, it should end up with a blog about incremental generators in real life

**Comment by amelmusic** [comment]
@jasonmalinowski do you have some examples how to read public types from referenced csproj file?

**Comment by jasonmalinowski** [comment]
So if you have the Compilation in the generator, you can access Compilation.GlobalNamespace to get the namespace of all types, including form any references. From there you'd have to recurse through the namespaces. @chsienki is there a special provider for just references, so that way the generator does't rerun on other changes?

**Comment by amelmusic** [comment]
I've managed to tackle this issue. So for anyone else who might come to the same issue, this is what I've discovered:

- if you are relying on external files, they have to be loaded through "AdditionalFiles" and not read directly, this way, compilation will only rerun if file has changed.  You can easily import multiple files in a following way: <AdditionalFiles Include="../XProd.Model/*.bpmn" Visible="False" />
- If you are using wildcard to load files, list will not be regenerated if you are building with dotnet publish command
- Make sure that your generator is not rerun on every keystroke. For eg,  keep an eye on using Compilation.GlobalNamespace. If you directly select data, you will rerun generator on every keystroke. We had to create additional class which had overriden Equals and GetHash methods which would only change if some of the properties that we are interested in are changed. Same thing can happen if you are combining additional files with custom lists.

I can confirm now that incremental generators works much better than v1 version even though it required significant rewrite in my case.

Thank you guys for your help!
