### ISSUE TITLE
VS2022 Release: Blazor doesn't show the helpers automatically in many occasions when underlined code from warnings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Release:-Blazor-doesnt-show-the-/1577590)._

---
I did a merge getting all the latest changes from the current branch. That brought a number of changes in the code.
I went through all the warnings and some of the warnings were properly underlined in the code but not showing the helper to act on them unless I manually right clicked on it to show it.
However, I went to other parts of the code by clicking on the warning and it did show them there, so it seems random.
I went back to the file with issue and I added back the problematic usings and after I added them back, the helper showed.

I've found issues after getting a large number of changes from a branch I was working on, showing issues in the code coming and the Errors, Warnings, Breakpoints... not updated properly with all the changes that came.

See recording.

---
#### Feedback Bot on 11/10/2021, 11:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/10/2021, 11:22 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
![BlazorRemoveUsingNotShowing](https://user-images.githubusercontent.com/10605811/143810798-8d2b44d7-7f70-429d-9b9b-32d9a419c265.gif)

Seems like remove unused usings is not greying out the entire usings span, but instead just the unnecessary ones.

**Comment by sharwell** [comment]
> Seems like remove unused usings is not greying out the entire usings span, but instead just the unnecessary ones.

This analyzer and code fix goes to great lengths to ensure only the unnecessary usings are grayed out, but the refactoring works anywhere within the set of usings (including necessary lines).
