### ISSUE TITLE
Compiler is not picking up the extension method defined.

### ISSUE THREAD

**Issue by candreouTrade** [dotnet/roslyn#58001]
**Version Used**: 
C# 10.0
**Steps to Reproduce**:

1.  Define a class with an Extension method AddOrGetExisting

  ```
public static class MyCacheExtensions
    {
        public static T AddOrGetExisting<T>(this ObjectCache cache, string key, Func<T> factory, CacheItemPolicy policy)
        {
            return new Lazy<T>().Value; 
        }
    }
```
 
2.    Define a second class that makes use of the Extension method.
 
```
internal static class MyCache
    {
        static MemoryCache Cache = new MemoryCache("Cache"); 
        private static ConcurrentDictionary<string, Lazy<DateTime>> GetCache(DateTime t)
        {
            var value = Cache.AddOrGetExisting("", () => new ConcurrentDictionary<string, Lazy<DateTime>>(), new CacheItemPolicy());

            return value;

        }
    }

```

**Expected Behavior**:

Should compile.

**Actual Behavior**:

Error	CS0266	Cannot implicitly convert type 'object' to 'System.Collections.Concurrent.ConcurrentDictionary<string, System.Lazy<System.DateTime>>'. An explicit conversion exists (are you missing a cast?)	ClassLibrary1	c:\...MyCache.cs	18	Active

**NOTE:**

AddOrGetExisting already exists on the MemoryCache class **as instance methods**, but with different method signature to the Extension Method defined.

Adding the following line instead does compile:

`var value = Cache.AddOrGetExisting<ConcurrentDictionary<string, Lazy<DateTime>>>("", () => new ConcurrentDictionary<string, Lazy<DateTime>>(), new CacheItemPolicy());
`

**Comment by cston** [comment]
@candreouTrade, with C#10, the lambda expression has an inferred delegate type, so the call to `AddOrGetExisting()` may bind to the instance method on `MemoryCache` if the parameter corresponding to the lambda is a base type (or interface) of `Func<...>` such as `object` or `System.Delegate` and the other arguments are also convertible to the corresponding parameter types.
