### ISSUE TITLE
Support more than "Diagnostic" for faults (NFE/NFW)

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#58027]
https://github.com/dotnet/roslyn/blob/2df14d40acca3d0a7fe8712c7c0bc012a0e28c88/src/VisualStudio/Core/Def/Implementation/Watson/WatsonReporter.cs#L103

This code currently assumes all faults are the same diagnostic. New automated bug reporting doesn't pick up on this, so we should find out what the correct way to fully utilize faults is.

**Comment by jasonmalinowski** [comment]
@ryzngard: this is a dupe of https://github.com/dotnet/roslyn/issues/57699 -- who wants to take it?

**Comment by ryzngard** [comment]
Ah good catch. I'm happy either way. The change in bug filing might be a reason to expedite. I'll close this one though for tracking purposes
