### ISSUE TITLE
Runtime crash due to assigning a null value to a non-nullable reference using null-forgiving operator and using the null reference

### ISSUE THREAD

**Issue by akshays2112** [dotnet/roslyn#58033]
**Version Used**: 

C# 10

**Steps to Reproduce**:

1.  Run the following C# code in a console project::
...

using System;

NullableReferenceTypes nullableReferenceTypes = new();
Console.WriteLine(nullableReferenceTypes.NonNullableString);
nullableReferenceTypes.SetNonNullableStringWithNullForgivingOperator(null);
Console.WriteLine(nullableReferenceTypes.GetLengthOfNonNullableString());

class NullableReferenceTypes
{
    public string NonNullableString { get; set; } = "NotNull";

    public void SetNonNullableStringWithNullForgivingOperator(string? firstName) => NonNullableString = firstName!;

    public int GetLengthOfNonNullableString() => NonNullableString.Length;
}

...

**Expected Behavior**:

After the null-forgiving operator (firstName!) is evaluated to null then the compiler and/or runtime should not assign the null value to the non-nullable string type and raise a warning and/or error.

**Actual Behavior**:

It manages to assign the null value to the non-nullable string and at the point where it tries to get the length of the string whose value is null, it throws an exception at runtime.

**Comment by akshays2112** [comment]
Disclaimer::
I am revisiting/restudying my C# from scratch as this is a great time in C# and .NET technologies. So forgive me that when I actually apply my mind to understand the C# language and not merely memorize it and use it as a tool to accomplish my goals then this is the result :).

**Comment by Youssef1313** [comment]
I don't think there is a bug here. When you use the null-forgiving operator, you're literally telling the compiler "Hey, I know more than you, this is not going to be null. I'm responsible for that". The operator then suppresses the compiler warning.

Also please note that nullable reference types doesn't have anything to do with the runtime behavior. The feature is almost about extra compiler warnings. The produced IL code is never affected by the use of nullable reference types.

**Comment by akshays2112** [comment]
Will do. Just felt it would be nice if xxx! applied to xxx then after yyy = the result of null it would have an exception thrown. Meaning when it sees ! it should apply it not to the whole statement of the = assignment bit. But ok if this is by design is alright. Just running it by Mads to ensure that he knows about this (@MadsTorgersen and Team). Mads if you feel this is frivolous please close this. Thanks in advance.

**Comment by Youssef1313** [comment]
@akshays2112 I think you're misunderstanding the `!` operator. The operator **doesn't** have any **semantic** meaning. It doesn't change the behavior at runtime. Everything about the feature doesn't change anything at runtime.

**Comment by akshays2112** [comment]
At runtime in a type-safe language, I am assigning a value of null successfully to a non-nullable type with no exception thrown by neither the compiler nor the runtime CLR.  Hope that clarifies why I think it is an issue.

**Comment by Youssef1313** [comment]
The runtime doesn't really know if a reference type is nullable or not as I explained earlier. So I believe you're misunderstanding the feature. Probably someone from the compiler team can explain better than me :)

**Comment by RikkiGibson** [comment]
Please see the [null-forgiving operator documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving).

**Comment by akshays2112** [comment]
Going to close this as per @RikkiGibson saying it is by design.

**Comment by akshays2112** [comment]
Why I thought this was an issue::

From the documentation at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving it says::
It only affects the compiler's static flow analysis by changing the null state of the expression. At run time, expression x! evaluates to the result of the underlying expression x.

So I would expect that the expression evaluates to null but when it comes to the parser looking at the assignment operator = it would barf and say you cannot assign null to this variable as it is a non-nullable type. My problem was the assignment bit not with the ! null-forgiving operator expression evaluating to null bit which is of course by design the purpose of the ! null-forgiving operator.

Peace!  Thanks for hearing me out.

Cheers!

**Comment by Youssef1313** [comment]
cc @BillWagner for any possible documentation enhancements here.

**Comment by BillWagner** [comment]
Thanks for the mention @Youssef1313 

I've read the thread, and the docs referenced go cover this I don't think we need any doc updates for this.
