### ISSUE TITLE
Applying EditorBrowsable attribute to property getters or setters does not work

### ISSUE THREAD

**Issue by JoshLove-msft** [dotnet/roslyn#58039]
**Version Used**: .NET 5.0

**Steps to Reproduce**:

1. Apply EditorBrowsable(EditorBrowsableState.Never) to a setter or getter for a property
2. Build the package
3. Add a package reference to the package containing the property
4. Intellisense still shows both the getter and setter. 

**Expected Behavior**:
Intellisense does not show the hidden getter/setter.

**Actual Behavior**:
Intellisense still shows both the getter and setter.

**Comment by CyrusNajmabadi** [comment]
Can you give an example of what you mean by: > Intellisense still shows both the getter and setter.

here?

**Comment by JoshLove-msft** [comment]
Here is how I'm using the attribute:
![image](https://user-images.githubusercontent.com/54595583/144131822-ce50569f-a7fb-4899-b299-0299e327d183.png)

Here is how it appears in Intellisense:
![image](https://user-images.githubusercontent.com/54595583/144131889-12c379cd-94e9-4ce8-9650-79b84c922d19.png)

**Comment by CyrusNajmabadi** [comment]
Ok.  So we're going to show the property no matter what (since it was itself not hidden).  We don't really have any facility for hiding the fact that our signature-info for it will show the `get; set;`.

**Comment by JoshLove-msft** [comment]
Yes, this would be a request to support this feature 😄

**Comment by CyrusNajmabadi** [comment]
> Yes, this would be a request to support this feature

So, in general, this is not what editorbrowsable does.  It doesn't make symbols appears differently.  It affects if the symbol just shows up in teh completion list (or a couple of other list locations).  Actually making it so we present someone a view that indicates that the items does not exist has never been in scope.

Can you clarify why you'd like this? Note that if the user does something like 'goto def' on that symbol, they'd still see these things.

**Comment by JoshLove-msft** [comment]
The reason we would like this is that it provides more flexibility for us to inherit from types that have public setters for specific properties. In our case, we are looking at adding the following abstraction:

```c#
public abstract class MessageWithMetadata {
   public abstract string ContentType { get; set; }
   public abstract BinaryData Data { get; set; }
}
```

Some types that derive from this are actually read-only. Rather than defining a separate ReadOnlyMessageWithMetadata, we would like to derive from MessageWithMetadata and throw from the type's setters. To offer the best experience, we would like to hide the setters from intellisense.

**Comment by sharwell** [comment]
It seems like it should be easy enough to modify the rendering of the signature in Signature Help and Completion to hide accessors that are marked with `[EditorBrowsable]` such that they would be hidden under the current settings.

**Comment by CyrusNajmabadi** [comment]
> It seems like it should be easy enough to modify the rendering of the signature in Signature Help and Completion to hide accessors that are marked with [EditorBrowsable] such that they would be hidden under the current settings.

FWIW, we don't own the rendering here.  This just goes through SymbolDisplay.  So we'd need a way for it to somehow know to do this.

**Comment by CyrusNajmabadi** [comment]
> Some types that will derive from this are actually read-only. Rather than defining a separate ReadOnlyMessageWithMetadata, we would like to derive from MessageWithMetadata and throw from the type's setters. To offer the best experience, we would like to hide the setters from intellisense.

Note: Abstract/overrides get more complex here, as from the language's perspective these are often the same.  So it's totally possible we might see one or the other, and then might not see your EB attribute.

**Comment by jasonmalinowski** [comment]
We discussed this and elected to leave the behavior as is; we're generally hesitant to tinker with EditorBrowsable because any change here can cause issues for other scenarios and we haven't seen this as a common ask that would warrant changes.

It also seemed for @JoshLove-msft's specific scenario, something stronger like an analyzer might be more appropriate -- many users aren't going to notice the lack of a "set" to indicate the particular derived implementation is actually not settable, and would end up hitting exceptions at runtime. A compile-time analyzer would mean it's caught at compile time, and would also be more durable against refactorings or other code movement. For example, copy/pasting code around won't ever show any of those features, but could still be caught during static analysis.
