### ISSUE TITLE
SyntaxTrivia needs a FunFacts property

### ISSUE THREAD

**Issue by XAML-Knight** [dotnet/roslyn#58065]
## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
     public class SyntaxTrivia : IEquatable<SyntaxTrivia>
     {
+        public List<string> FunFacts{ get; }
     }
```

**Comment by CyrusNajmabadi** [comment]
I'm not sure if this proposal is serious or not.  If serious, please add more information as to what you're asking for @XAML-Knight .  If not serious, please close.

**Comment by jmarolf** [comment]
If not serious then I agree we should maybe put a link to imdb in there. 

Slightly related, I do wish we stopped calling them "code comments" in the first place. Hopefully "code trivia" catches on. like:

```csharp
// Did you know this is the longest method name in all of roslyn?
```
https://github.com/dotnet/roslyn/blob/8a92d8abaffdebe23ff777f692ee0cf26103fdf5/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb#L2966
