### ISSUE TITLE
IOperation support for implicit Index/Range indexer over non-array types

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#58079]
```
    /// <summary>
    /// Represents a reference to an implicit Index or Range indexer over non-array type.
    /// <para>
    /// Current usage:
    ///  (1) C# implicit Index or Range indexer reference expression.
    /// </para>
    /// </summary>
    /// <remarks>
    /// <para>This node is associated with the following operation kinds:</para>
    /// <list type="bullet">
    /// <item><description><see cref="OperationKind.ImplicitIndexerReference"/></description></item>
    /// </list>
    /// <para>This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.</para>
    /// </remarks>
    public interface IImplicitIndexerReferenceOperation : IOperation
    {
        /// <summary>
        /// Instance of the type to be indexed.
        /// </summary>
        IOperation Instance { get; }

        /// <summary>
        /// Index or Range value.
        /// </summary>
        IOperation Index { get; }

        /// <summary>
        /// The <c>Length</c> or <c>Count</c> property that can be used to fetch the length value.
        /// </summary>
        ISymbol LengthSymbol { get; }

        /// <summary>
        /// Symbol for the underlying indexer or a slice method that is being used to implement the implicit indexer.
        /// </summary>
        ISymbol IndexerSymbol { get; }
    }
```

Implicit Index/Range indexer over array types will continue to be represented as ```IArrayElementReferenceOperation```.

See also proposal for list patterns https://github.com/dotnet/roslyn/issues/57194.

**Comment by 333fred** [comment]
### API Review

* Naming: we have both Reference and Access in existing names
    * We'll keep it as is to keep in line IPropertyReferenceOperation
* We'll rename Index to Argument to line up with IPropertyReferenceOperation

#### Conclusion

Rename Index to Argument. Otherwise, API is approved.

**Comment by alrz** [comment]
> ```cs
> /// <summary>
> /// Symbol for the underlying indexer or a slice method that is being used to implement the implicit indexer.
> /// </summary>
> ISymbol IndexerSymbol { get; }
> ```

With this addition, shouldn't we use `IndexerSymbol` for `ISlicePatternOperation.SliceSymbol` as well? (that's unshipped afaik)

**Comment by AlekseyTs** [comment]
> With this addition, shouldn't we use `IndexerSymbol` for `ISlicePatternOperation.SliceSymbol` as well? (that's unshipped afaik)

As far as I understand the ```ISlicePatternOperation.SliceSymbol``` is always used to slice. Even if it is an indexer, it must take Range. An indexer returned by ```IImplicitIndexerReferenceOperation.IndexerSymbol is always used to index. It must take int. The name ```ISlicePatternOperation.SliceSymbol``` looks Ok to me.
