### ISSUE TITLE
Incorrect IDE0004: Remove unnecessary cast

### ISSUE THREAD

**Issue by JKamsker** [dotnet/roslyn#58095]
I am currently unsure if its really a roslyn bug or a c# bug or both.

**Version Used**: 

```
Microsoft Visual Studio Enterprise 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04084

dotnet 6 / C# 10
```

**Steps to Reproduce**:

Code: 
```csharp
var (isEdge, moreOnes) = (true, false);

char? expected_a = isEdge ? null : moreOnes ? '1' : '0';
char? expected_b = isEdge ? null : moreOnes ? '0' : '1';

(char? expected_a_01, char? expected_b_01) = isEdge ? default : moreOnes ? ((char?)'1', (char?)'0') : ('0', '1');
(char? expected_a_02, char? expected_b_02) = isEdge ? default : moreOnes ? ('1', '0') : ('0', '1');

Debug.Assert(expected_a == expected_a_01 && expected_a == expected_a_02);
Debug.Assert(expected_b == expected_b_01 && expected_b == expected_b_02);
```

**Expected Behavior**:
`expected_a`, `expected_a_01 ` and `expected_a_02`  should be equal.  (Namely, null)
The analyzer tells me, that both casts are redundant.

**Actual Behavior**:
`expected_a_02`  and `expected_b_02`  both have the value `0`

**Comment by Youssef1313** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Doesn't repro in 17.1.  17.0 doesn't have the rewrite of this feature.  Will add validation test and close this out.

**Comment by JKamsker** [comment]
It still works for me - vs 17.0.0 - no plugins

![image](https://user-images.githubusercontent.com/11245306/145119302-f62b2a62-44f4-466c-8dcd-95acf0881ce8.png)
![image](https://user-images.githubusercontent.com/11245306/145119381-5e0009ff-dc0d-4c4a-9b34-16e53a49e1a1.png)

**Comment by CyrusNajmabadi** [comment]
@JKamsker Correct.  As i mentioned, this is fixed in 17.1 (not 17.0) and i have a PR out showing that this no longer reproes to ensure this doesn't regress.  Thanks!

**Comment by JKamsker** [comment]
Ah okay, then i'm sorry i missunderstood your comment :D

**Comment by CyrusNajmabadi** [comment]
Not a problem at all.  Nothing to be sorry about.
