### ISSUE TITLE
Visual Studio 2022. Sometime 'add using' code fix do not work for blazor web assembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58091]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Sometime-add-using/1577249)._

---
Hi,

Visual Studio 2022(17.0.0, current). 

Sometime 'add using' code fix do not work for blazor web assembly

thank you

---
#### Feedback Bot on 11/9/2021, 05:07 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Fire Zhang [MSFT] on 11/23/2021, 11:30 PM: 

<p>Thank you for taking the time to log this issue!<br>
Regrettably, I can’t repro the issue on the latest version of VS2022 Enterprise(17.0.1) with following repro steps:</p>
<ol>
<li>Create project Blazor WebAssembly App</li>
<li>Wait for loading finished and build the solution (Result: build successfully)</li>
<li>Open “FetchData.razor” and comment out “@inject HttpClient Http”<br>
Result: “Add using” works fine on error line<br>
Can you firm these steps and tell me at which step you failed?</li>
</ol>

#### Roma on 12/1/2021, 00:57 PM: 

<p>Hi,</p>
<p>Steps:</p>
<ol>
<li>create new blazor wasm project</li>
<li>delete _Imports.razor</li>
<li>open FetchData.razor</li>
<li>move cursor to ‘forecasts = await Http.[cursor possition]GetFromJsonAsync&lt;WeatherForecast[]&gt;(“sample-data/weather.json”);’ line</li>
<li>try to use ‘add using’ refactroing</li>
</ol>
<p>thank you</p>

#### Feedback Bot on 12/1/2021, 00:03 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

**Comment by Romfos** [comment]
it is sad :(

**Comment by NTaylorMullen** [comment]
oh wow something in the middle must be hanging then based on my previous comment.

**Comment by dibarbet** [comment]
Cause:
C# returns this as an edit
```
"edits": [
    {
      "range": {
        "start": {
          "line": 8,
          "character": 17
        },
        "end": {
          "line": 8,
          "character": 17
        }
      },
      "newText": "Net.Http.Json;\r\n    using System."
    }
```

Razor cannot parse the namespace and exits early here - https://github.com/dotnet/razor-tooling/blob/c7a91d7137c46777297660c4fb422fe4a563c816/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/AddUsingsCSharpCodeActionResolver.cs#L86

The appearance of C# hanging is for some reason the request is basically immediately cancelled under the debugger...

**Comment by CyrusNajmabadi** [comment]
Ah interesting.  Looks like an edit produced by a diff operation. Not sure the best way to address this if razor is expecting a very specific format

**Comment by dibarbet** [comment]
Razor has a work item to support arbitrary edits from C# that they are trying to find time to schedule - @NTaylorMullen could you link that issue here?  Without that support we will definitely encounter this problem more as we add more code actions in razor.

In the meantime I am holding my nose and making a workaround in Razor.

**Comment by NTaylorMullen** [comment]
Just created one: https://github.com/dotnet/razor-tooling/issues/6159

**Comment by dibarbet** [comment]
This particular issue is resolved in https://github.com/dotnet/razor-tooling/pull/6156
