### ISSUE TITLE
[Request] "Pick members" dialog should focus search input

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn#58099]
# Version
Microsoft Visual Studio Community 2022
Version 17.1.0 Preview 1.1

# Request description

Hello,

I have start to use the "Picker members" dialog more and more,
but the most annoying is the problem that the window don't focus the search input.

![2021-12-03 17_57_00-AXP enERPplus - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/144643418-93900ec0-7976-43bb-aae1-bd8f3df7e8c5.png)

# Expected behavior
Automatic focus the search input when the "Pick member" dialog is shown.

# Actual Behavior 
The the search input of the "Pick member" dialog have no focus when it is shown.

**Comment by Youssef1313** [comment]
Bug is likely in:

https://github.com/dotnet/roslyn/blob/649315781b4e4f08f35e92c4b98a32295d39df79/src/VisualStudio/Core/Def/Implementation/PickMembers/PickMembersDialog.xaml#L20

There is no `interfaceNameTextBox`

**Comment by CyrusNajmabadi** [comment]
@TobiasSekan Fastest way to resolution here would likely be if you were able to contribute a fix.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
