### ISSUE TITLE
Roslyn.Compilers.CSharp.WinRT.UnitTests requires fixup

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#581]
Four of the unit tests in Roslyn.Compilers.CSharp.WinRT.UnitTests requires a fixup to include the [ConditionalFact(typeof(OSVersionWin8))] attribute.

These tests include:
* WinMdIReferenceINullableTest
* IVectorProjectionTests
* IVectorViewProjectionTests
* IMapProjectionTests

**Comment by tannergooding** [comment]
Fix is available in pull request #583

**Comment by agocke** [comment]
What's failing here? I expect verification to fail on non-Win8, so that's why they have CompileAndVerifyOnWin8 only calls, but I didn't expect the actual compilation to be machine dependent

**Comment by tannergooding** [comment]
Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly 'D:\Temp\1\RoslynTestFailureDump\3edbeaf2-2d1e-4443-8dc9-c34e07f8f21c'.
Exception: System.TypeLoadException: Could not find Windows Runtime type 'Windows.Globalization.NumberFormatting.DecimalFormatter'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at C.Main(String[] args)
---- System.TypeLoadException : Could not find Windows Runtime type 'Windows.Globalization.NumberFormatting.DecimalFormatter'.
-------- System.PlatformNotSupportedException : Operation is not supported on this platform.

**Comment by tannergooding** [comment]
In addition, it doesn't look like 'CompileAndVerifyOnWin8Only' has any check to see what OS we are running on. It simply calls 'CompileAndVerifyWinRT' which itself only creates a standard compilation using the WinRT References and then calls 'CompileAndVerify'.

**Comment by agocke** [comment]
Well, that would do it. I'll take a look. I may have to bring up an older machine.
