### ISSUE TITLE
Value Tracking Shows ALL THE THINGS

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#58104]
When Value Tracking looks for assignments to a property, it doesn't consider paths for assignment. Instead it does a symbol resolution and shows all possible times the value could be assigned to. DataFlow can help with this in some ways, but we should be able to scope assignments better than today. 

Example: 

```csharp
record R(string Name, int Id);

void M()
{
    var r = new R("Test", 1);
	r.Name = "Test 2";  // If we trigger value tracking here, both assignments show up
}

void M2()
{
    var r = new R("Test", 1);
	r.Name = "Test 2"; 
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
