### ISSUE TITLE
Proposal: List, Indexer (Dictionary) and String Patterns

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5811]
Following patterns are based on the syntax proposed in #206.
## List Patterns

_List patterns_ can be used on arrays and all types that have implemented the `IList` interface . It would iterate through the list and match the _list-subpatterns_. 
### Syntax

> _list-pattern:_
>  `{` _list-subpatterns_ `}`
>  `{` `}`
> 
> _list-subpatterns:
>  list-subpattern
>  list-subpatterns_ `,` _list-subpattern_
> 
> _list-subpattern:
>  pattern
>  sequence-wildcard-pattern_
> 
> _sequence-wildcard-pattern:_
>  `**`
>  `***`
### Remarks
- `{ }` matches an empty list. Determined by `Enumerable.Any` or `ICollection.Count` based on type. 
- `**` matches any sequence of one or more items.
- `***` matches any sequence of zero or more items.
- To keep the rules simple, sequence wildcards can be used only one time in the whole pattern.
- At runtime, considering sequence wildcards, it first calculates the minimum/maximum/exact length of the list, if it matches then it starts to iterate.

_EDIT 1:_ Sequence wildcards are capable to be used also in tuple patterns.

``` cs
switch(tuple) {
  case (true, **): ...
}
```

It would match a tuple with any length equal or greater than two.

_EDIT 2:_ It would be nice to be able to use slices (#120) to catch the "rest" of the list at once, e.g.

``` cs
arr is { int first, .. int[:] rest }

// equivalent to
if(arr is { int first, *** }) {
  rest[:] = arr[1:]; // skips the first item
}
```
### Examples

``` cs
switch(array) {
    // matches an empty array
    case { }:           
    // matches an array with exact length of two
    case { var i1, var i2 }:           
    // matches an array of tuples with minimum length of two and returns the first two item
    // with the first item deconstructed into t1 and t2
    case { (var t1, var t2) , var i2, *** }:           
    // matches an array with the minimum length of three,
    // picks the last three item and skips the one before the last
    case { *** , var i1, *, var i2 }: 
    // matches an array with the minimum length of three, returns the first and last item
    case { var i1, ** , var i2 }:
}
```
## Indexer Patterns

_Indexer patterns_ can be used on all types with an indexer, just like dictionary initializers.
### Syntax

> _indexer-pattern:_
>  `{` _indexer-subpatterns_ `}`
> 
> _indexer-subpatterns:
>  indexer-subpattern
>  indexer-subpatterns_ `,` _indexer-subpattern_
> 
> _indexer-subpattern:_
>  `[` _constant-expression-list_ `]` `is` _pattern_

An indexer pattern matches the values extracted by the use of indexer with the specified arguments. Following the property pattern syntax, we use an `is` keyword instead of `=` sign.  The whole match fails only if the one of indexer subpatterns fail. The order in which subpatterns are matched is not specified, and a failed match may not match all subpatterns. It's a compiler-error if type of the expression **_e**_ have not defined an indexer with parameters of type _constant-expression-list_, hence it's _pattern incompatible_.

_EDIT:_ The indexer pattern syntax can be mixed with _property-pattern_ so one can check a indexer and a property in the same pattern (analogous to object initializers).
## String Patterns

_String patterns_ can be considered as _inverted string interpolation_, and of course they can be combined with regular expression literals (#5806):

``` cs
var str = "str123";
if(str is ~$"[a-z]+{int number:\d+}") {
    Debug.Assert(number == 123);
}
```

Behind the scene, this creates a regular expression group at the interpolating section (`{ }`)  and applies the formatting part (`\d+`) to it, when the regex succeed, then it tries to convert the group capture via `TypeConverter` back to the variable type. If regular expression doesn't match or conversion wasn't successful, pattern fails.

Default type for variables in string patterns is `System.String`. The syntax for string patterns is pretty much the same as string interpolation, but formatting part after colon has a different meaning. This can be extended to bind repeating captures to an array or `IEnumerable`.

**Comment by gafter** [comment]
I have a bit of a problem with a general *expression* appearing as part of the pattern, as you have in the indexer pattern.

**Comment by alrz** [comment]
@gafter to avoid assignments in the pattern I think *conditional-or-expression* would be sufficient, right?

**Comment by gafter** [comment]
@alrz To avoid side-effects I suggest *constant-expression*.

**Comment by orthoxerox** [comment]
What if I want to capture that `***` into an variable so I can match recursively? Like...

```c#
void Value Cond(IReadOnlyList<Expr> list)
{
	while (list.Count != 0) {
		switch (list) {
			case { defaultCase }:
				return defaultCase.Evaluate();
			case { condition, result, *** tail }:
				if (condition.Evaluate() != Value.Nil) {
					return result.Evaluate();
				} else {
					list = tail;
				}
				break;
		}
	}
	return Value.Nil;
}
```

**Comment by svick** [comment]
@orthoxerox How exactly would that work? How would the compiler create an `IReadOnlyList<Expr>` from the tail? Is that supposed to work on any type that implements `IEnumerable` or only some list of collection types known to the compiler?

**Comment by svick** [comment]
@alrz 
> At runtime, considering sequence wildcards, it first calculates the minimum and/or maximum length of the list, if it matches then it starts iterate.

How do you figure out whether the count matches before iterating if the type is just `IEnumerable<T>` (i.e. it does not implement `ICollection`, or any other type that has `Count`)?

Or is that just an optimization that does not apply to general `IEnumerable<T>`?

**Comment by alrz** [comment]
@orthoxerox Wildcards are used specifically for **ignoring** items. Actually, you're asking for *array slices* (#120) in patterns which is interesting! Your use case needs two additional feature: *slicing patterns* and *conjunctive patterns*:
So, your second `case` would be
```cs
case { condition, result, *** } & tail[2:]:
```
Although, this syntax depends on slicing proposal, specifically the fact that it is used with arrays can be extended to support `IEnumebrable` via `Skip` and `Take`.

**Comment by alrz** [comment]
@svick that is just an optimization that does not apply to general `IEnumerable<T>`.

**Comment by AdamSpeight2008** [comment]
Isn't syntax going to clash with collection initialisers, and array literals (VB).
Indexer syntax could be an issue in VB, since it doesn't use square brackets for array indexing.
VB as a pre-existing feature that is similar to regex-literals,  The [Like Operator](https://msdn.microsoft.com/en-us/library/swf8kaxw.aspx)
```vb
If thisString Like "[A-Z][A-Z]#" Then
```

**Comment by AdamSpeight2008** [comment]
`[ 1 : 10]` should produce a `Range` 
```vb
Structure Range
  Public ReadOnly Property XB As Int32 'Starting Index
  Public ReadOnly Property XE As Int32 'Finishing Index
End Structure
```
Which would allow use the specify a range as an Indexer parameter
` foo[ [2 : 4] ]` or `mystring[ [ [1 : 4] ]` 
The `Range` could also be `IEnumerable<Int>`, which generates the sequence (inclusive, inclusive)
eg `[2 : 4]` produces `{ 2, 3, 4 }`

**Comment by alrz** [comment]
@AdamSpeight2008 The syntax proposed here is not intended to be used in VB. The pattern that `Like` operator is using, is not a regular expression, nor it supports extracting values from strings the way that string patterns would do. IIRC there is no such thing as `Range` and your examples refer to slicing (#120) which is unrelated to the subject of this topic.

**Comment by AdamSpeight2008** [comment]
@alrz 
 You should be consider the VB implementation as well, *cough co-evolution  cough*
I said `Like` is **similar** not exactly.  
IIRC there is no such thing as `Slice` *cough*
 `Range` is not the same a `Slice`
 * Slice is **Index, Count**
 * Range is **Index<sub>begin</sub>, Index<sub>end</sub>**
  * you could specify  **Index<sub>end</sub>, Index<sub>begin</sub>** and get the reverse sequence.

**Comment by AdamSpeight2008** [comment]
`...` would be good alternative to `***`
What if we allowed unary postfix operators '*' and `+` so the **pattern objects**  can implement 
 '__+' (one or more wildcard items) an d` __* ` (zero or more wildcard operators).
If reqex literal are includes the extra operators could be handy.

**Comment by vladd** [comment]
@alrz  I've got mixed feelings about the string pattern part. It is a very powerful tool in the form as you propose, but of course they have a problem of silently introducing regular expression machinery into a simple syntactic construction. There was enough outcry against the fact that innocently-looking `$"{x}"` brings in a rather heavy `string.Format` behind the scenes, so I doubt that bringing in an even heavier `Regex` would enjoy a lot of support of the community. Such a feature looks better in scripting languages, where the performance considerations are usually neglected.

My preference would be to (somehow) bring the "back interpolation" to the `Regex` class, so that instead of analysing `Matches` one could get them auto-parsed into the outer variables. Unfortunately I don't see any good way for it without heavy compiler's support (the library should somehow get the _references_ to the local variables from the input string or the object the string is going to be converted to), so I cannot really propose anything better.

**Comment by alrz** [comment]
@vladd not silently, you have to use regular expression literal syntax: `~"regex"`. And `$"{x}"` is being optimized (#194).

**Comment by bondsbw** [comment]
Recent proposals on wildcards  (#14794, #14862) use the underscore character `_` as a single wildcard.  As noted in those discussions, `**`, `***`, `..`, and `...` for sequence wildcards are now inconsistent.

Double-underscore `__` was proposed but is difficult to distinguish visually from a single underscore `_` because most fonts do not provide any whitespace between them.

I support something like @AdamSpeight2008's proposed syntax for sequence wildcards.  Though I prefer a single (not double) underscore character followed by the repetition character.  And I added `_?` for _zero-or-one_:

```c#
tuple is (1, _*) // tuple is oneple (1), or (1, _), or (1, _, _), or (1, _, _, _), etc.
tuple is (1, _+) // tuple is (1, _, _*)
tuple is (1, _?) // tuple is oneple (1) or (1, _) only
```

This syntax could also apply to sequence wildcards for use in lambda argument lists (#15027):

```c#
Loaded += _* => { /* not using the arguments */ };
Func<bool> f1 = _* => true;
Func<int, bool> f2 = _* => true;
Func<int, int, bool> f3 = _* => true;
```

**Comment by alrz** [comment]
Out of date.
