### ISSUE TITLE
Question: Global using support for `CSharpCompilationOptions`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#58119]
Could we use the global usings feature when compiling source code?

It seemed the `CSharpCompilationOptions.WithUsings` method would not work as expected.

Sample code:

``` c#
var code = @"
public record Post
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTime UpdatedAt { get; set; }
}
";
var syntaxTree = CSharpSyntaxTree.ParseText(sourceText, new CSharpParseOptions(LanguageVersion.Latest));
var references = new[]
        {
            typeof(object).Assembly,
            Assembly.Load("netstandard"),
            Assembly.Load("System.Runtime"),
        }
        .Select(assembly => assembly.Location)
        .Distinct()
        .Select(l => MetadataReference.CreateFromFile(l))
        .Cast<MetadataReference>()
        .ToArray();
var assemblyName = $"DbTool.DynamicGenerated.{GuidId.NewGuid()}";
var compilation = CSharpCompilation.Create(assemblyName)
    .WithOptions(
        new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        // support only for script? https://stackoverflow.com/questions/38795447/roslyn-effect-of-csharpcompileroptions-withusings
        .WithUsings(new[]
        {
        "System",
        "System.Collections.Generic",
        "System.IO",
        "System.Linq",
        "System.Net.Http",
        "System.Threading",
        "System.Threading.Tasks"
        })
    )
    .AddReferences(references)
    .AddSyntaxTrees(syntaxTree);
using var ms = new MemoryStream();
var compilationResult = compilation.Emit(ms);
```

I would get an error as follows:

> The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)

**Comment by CyrusNajmabadi** [comment]
> Could we use the global usings feature when compiling source code?

No. Global usings are actually contained in source somewhere. I.e.  `global using System;`

**Comment by WeihanLi** [comment]
Thanks @CyrusNajmabadi , would we add support for it? Wondering that maybe it could work like the implicit usings in the SDK.

**Comment by CyrusNajmabadi** [comment]
So implicit usings in the sdk are translated into global usings. So given that that works that way, I dummy think we'd add a new and different way to do it. Is there a reason you can't just add file with the global usings in that?

**Comment by WeihanLi** [comment]
Hi @CyrusNajmabadi , I could add a source file that included the global usings.

I think it would be more simple and have a better developer experience, and the `CSharpCompilationOptions.WithUsings` method is suitable for the global usings. Do you have some concerns on this?

**Comment by CyrusNajmabadi** [comment]
> Do you have some concerns on this?

Yes. I definitely do :-)

**Comment by WeihanLi** [comment]
Got it, thanks @CyrusNajmabadi

**Comment by GeorgeAlexandria** [comment]
@CyrusNajmabadi, I'm not fully understand the meaning of `CSharpCompilationOptions.Usings` when you should put `global usings` in compilation as an additional source file anyway. I searched using of it and just found usage in [UsingsFromOptionsAndDiagnostics.FromOptions](https://github.com/dotnet/roslyn/blob/df86b32122818d4dd9a7f0f357924e7fbfe66387/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.UsingsFromOptionsAndDiagnostics.cs#L27), where seems that it is used to bind `global usings` on to compilation – why does it used `CSharpCompilationOptions.Usings` and does not used the source file with `global usings`? 

Should we put all `global usings` from all source files to `CSharpCompilationOptions.Usings` when create compilation from these source files or it's unnecessary?

**Comment by CyrusNajmabadi** [comment]
That property is for csx usings. However as you are not compiling csx files, but instead are compiling cs files, it's not the right option. The semantics if C's and csx are not the same. Thanks!

**Comment by StefH** [comment]
@WeihanLi 
A possible workaround would be to add these to the code or WithUsings:

``` c#
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

More info here : https://stackoverflow.com/questions/72904348/roslyn-csharpcompilation-with-global-implicit-usings

**Comment by WeihanLi** [comment]
@StefH thanks very much, I include the global usings in my code now.
