### ISSUE TITLE
cw snippet adds global::System.Console when i use it on lambda expressions.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58135]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/cw-snippet-adds-global::SystemConsole-w/1604080)._

---
[severity:It bothers me. A fix would be nice]
When i try to use the Console.Write(); snippet inside a lambda expression it insert global::System.Console.WriteLine(); instead of Console.WriteLine();

---
#### Feedback Bot on 12/5/2021, 11:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/6/2021, 09:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The following code reproduces this issue:

```
using System;

var obj = new T();
obj.On(_ =>
{
    // ⬅️ use the 'cw' snippet here
});

class T
{
    internal void On(Action<object> p) { }
}
```

**Comment by Youssef1313** [comment]
@sharwell Is the "help wanted" label intended? I think it should be "Blocked" on https://github.com/dotnet/roslyn/issues/31879?

**Comment by sharwell** [comment]
@Youssef1313 no, this is a Simplify Type Name failure (note that even after generating the type, there is no code fix offered to simplify the type name).

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback
