### ISSUE TITLE
"Implement all members explicitly" action generates wrong code for static interface properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58136]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Implement-all-members-explicitly-actio/1604127)._

---
See title and the recording.

I have this interface:
```cs
internal interface IDaySolver
{
    internal static abstract int Day { get; }
}
```

I create a new implementation of it, have it implemented automatically by VS and it creates this:
```cs
int IDaySolver.Day => throw new NotImplementedException();
```
which is invalid because the property should have been generated as static.

---
#### Feedback Bot on 12/6/2021, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/6/2021, 09:48 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue is very similar to #54327, but affects static _properties_ instead of static methods.
