### ISSUE TITLE
Rename doesn't work on methods passed as parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-doesnt-work-on-methods-passed-as/1602432)._

---
[severity:It's more difficult to complete my work]
In the following code, I point at the function name Retuern and press context menu Rename.

```
    using Microsoft.AspNetCore.Mvc;
    
namespace net6api. Endpoints;
    
public class Values : IEndPoints
    {
      public async Task<JsonResult> Retuern(string code)
      { }
    
public void DefineEndpoints(WebApplication app)
      {
        app. MapGet("/Values/Return", Retuern);
      }
    
public void DefineServices(IServiceCollection services)
      {
        throw new NotImplementedException();
      }
    }
```
As I type a new name, this comes up:

![image](https://user-images.githubusercontent.com/1408396/144886340-e76878cf-c752-4e50-bb55-d90b592ab69a.png)

Meanwhile, if I point at the use of this function in DefineEndpoints and click Rename, I get:

![image](https://user-images.githubusercontent.com/1408396/144886364-d4b5ec21-b5e9-4d6c-bc42-faa223b72c53.png)

This seems like a bug.

---
#### Feedback Bot on 12/2/2021, 06:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/3/2021, 09:48 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  These names rename just fine.
