### ISSUE TITLE
Go to Implementation/Base to include external references

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#58147]
Find All References and Go to Implementation/Base to include external types (types from metadata) and be able to navigate to them based on sourcelink information/decompilation. Once navigated to the external source additional navigation commands should work from those external files.

**Comment by davidwengier** [comment]
TIL Go To Base already does support external references 🤷‍♂️

**Comment by davidwengier** [comment]
https://github.com/dotnet/roslyn/issues/59126 is needed before this will work over LSP

**Comment by davidwengier** [comment]
Split out FAR to https://github.com/dotnet/roslyn/issues/59568, closing this because it was fixed by https://github.com/dotnet/roslyn/pull/59100
