### ISSUE TITLE
CS8618 should not happen on static classes

### ISSUE THREAD

**Issue by OoLunar** [dotnet/roslyn#58151]
**Version Used**: 
6.0.100

**Steps to Reproduce**:
```cs
namespace Moonlight.Api
{
    public static class Server
    {
        private static bool Initiated;
        public static IConfiguration Config { get; private set; } // CS8618, Non-nullable property 'Config' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

        public static void Init(IConfiguration config, bool force = false)
        {
            if (Initiated && !force)
            {
                throw new InvalidOperationException("Server has already been initiated, and the force argument was set to false.");
            }

            Initiated = true;
            Config = config;
            MinecraftAPI.HttpClient.DefaultRequestHeaders.UserAgent.TryParseAdd("Moonlight/2.0.0 (1.17.1)");
        }
    }
}
```

**Expected Behavior**:
Either for a different warning or message to appear, alternatively no warning at all.

**Actual Behavior**:
Warning CS8618 is thrown despite static classes having no constructors.

**Comment by svick** [comment]
> Warning CS8618 is thrown despite static classes having no constructors.

That is not true, *static* classes can have *static* constructors.

In your case, I think the right approach is to initialize the property to `null!`, to indicate that you're going to ensure the property is not `null` in some other way (the `Init` method):

```c#
public static IConfiguration Config { get; private set; } = null!;
```

**Comment by OoLunar** [comment]
Oh, I had no idea static constructors were a thing. In fact, I've always been told the opposite... I should've done a bit more Googling before opening up an issue about this, my apologies. Thank you for pointing this out.
