### ISSUE TITLE
Stack Trace Explorer to surface the option to close each Stack Trace tab

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#58164]
**Version Used**
17.1 Preview 2

**Steps to Reproduce**:

1. Opening the Stack Trace Explorer window will automatically open a new tab.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/46729679/145086461-e0411526-e301-4777-bc79-7665f94a693d.png">

2. Currently it is unclear how to close each tab. You have to right click to see the option to close the tab:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/46729679/145086299-8e330e2b-a6e0-472e-b358-2c0cfb5d7fcc.png">

**Expected Behavior**:
Instead of needing to right click to see the option to close the tab we should surface the `x` next to each tab so its easily discoverable. 

@ryzngard

**Comment by ryzngard** [comment]
See #58458
