### ISSUE TITLE
Heavy allocation in formatting an unused error message

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58165]
The following line eagerly formats a string, leading to significant allocations (264MB in [AB#1427077](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1427077)) even when the message is not used.

https://github.com/dotnet/roslyn/blob/8322567ec447fe833bf182739bc1773a981a26cd/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs#L303

**Comment by Youssef1313** [comment]
Interpolated string handler will probably shine here? :)

**Comment by CyrusNajmabadi** [comment]
Indeed.  @333fred want to update our contracts to use handlers?

**Comment by 333fred** [comment]
This sounds fun :). I'm prepping for a talk on Thursday, but I can take a look after then.
