### ISSUE TITLE
Completion suggesting names after typing event name

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#58162]
![image](https://user-images.githubusercontent.com/788783/145084087-e45993e9-16c9-4217-9d82-d9e8996c1a8f.png)

This seems like an odd time to suggest event handler names. Note that if I select one, I end up with:
`this.ShowRightOnly.Checked routedEventHandler`
which seems very wrong.

this might be the logic to suggest names after you type X.Y thinking that that expression might be a type name.  However, we should only do this if all the parts of the expression are simple-names or qualified-names.

**Comment by genlu** [comment]
This might be confusing, but since this is in suggestion mode, I think it doesn't actually impede typing.

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Does this still repro for you @genlu ?

**Comment by genlu** [comment]
No it doesn't anymore
