### ISSUE TITLE
Inconsistent semantic model behavior.

### ISSUE THREAD

**Issue by PaulEremeeff** [dotnet/roslyn#5818]
We are currently evaluating Roslyn infrastructure with the prospect of creating C# code analyzer product. While trying it out on several open-source projects, we've discovered a somewhat inconsistent behavior when using *SemanticModel* object to get type information for a *SyntaxNode* (*GetTypeInfo* method).

The setup is as follows: a *SemanticModel* instance is obtained through *GetSemanticModel* method of a *Compilation* object; the *Compilation* instance is obtained by '*GetCompilationAsync*' method of the *Microsoft.CodeAnalysis.Project* object; a *Project* instance is obtained from *Solution* instance which itself is obtained from MSBuildWorkspace OpenSolutionAsync method.

Now, invoking '*GetTypeInfo*' method on some *SyntaxNodes*, we sometimes we get a *TypeInfo* object containing '*TypeKind.Error*' inside the '*Type*' property. This is quite inconsistent, as, most of the times, we actually get a correct '*TypeKind*' for the node in question. But in some situations, it seems, the *SemanticModel* somehow falis to process a particular *SyntaxNode*.

The projects that are fed to the '*MSBuildWorkspace OpenSolutionAsync*' (to get a *SemanticModel* instance) have all of their dependencies present and are perfectly buildable.

We were able to steadily reproduce the issue on a number of occasions, i.e. for several projects. Now, the funny thing is that, for some CS projects (csproj), the '*TypeKind.Error*' is returned by the model when a particular file is missing: for example, let's take a 'test.csproj' – the semantic model returns '*TypeKind.Error*' each time if the 'test.csproj.app.config' file is missing from the '/obj/Debug' folder for this project.

This 'app.config' file is actually auto-generated on a project build in Visual Studio, but, if it is missing, the *SemanticModel* instance just does not work (as described above). Even more funny here is that the contents of this 'app.config' file are irrelevant – if the file is present at the expected location, the model works even if this file is empty. Although, this situation is not true of every csproj we are running *SemanticModel* against – the presence of app.config does not guarantee that the model works, i.e. even with it we still get '*TypeKind.Error*'.

Now, we want to understand, if we are doing something wrong when obtaining a semantic model, and why the mere presence of 'app.config' influence the operation of the model.

**Comment by svick** [comment]
Does the `SemanticModel` contain any diagnostics (call `GetDiagnostics()` to see them)?

**Comment by PaulEremeeff** [comment]
Indeed, *GetDiagnostics* returns interesting results. When *.csproj.app.config* is present, it returns just a single warning. But without this app.config, it returns several hundreds errors, error CS0246: The type or namespace name, error CS0246: The type or namespace name 'IAuthTokens' could not be found, and so on.

Thanks, now we can at least check if the model is correct, but the question remains - why does the presence of app.config influence it, and how we need to construct *SemanticModel* correctly? And is this an expected behavior?

**Comment by PaulEremeeff** [comment]
Also, we are using stable versions of libraries (1.0.0) from Nuget.org.

**Comment by Pilchie** [comment]
@PaulEremeeff Likely the issue is that something is failing the design-time build that happens during `OpenSolutionAsync`.  Can you take a look at the references of the `Compilation` you get back and see if they include everything you expect?

**Comment by Pilchie** [comment]
Tagging @mattwar and @jasonmalinowski.

**Comment by Pilchie** [comment]
(I wonder if we should have a way to get a verbose msbuild log for the evaluations in `OpenSolutionAsync` to help diagnose issues like this)

**Comment by Pilchie** [comment]
Also - I wonder if adding the binding redirects from #3034 (and linked issues/PRs) to your console application would alleviate this problem.

**Comment by mattwar** [comment]
Yes, any app that uses MsBuildWorkspace to open general projects will need the redirects in its own app configuration.

**Comment by PaulEremeeff** [comment]
@Pilchie Sorry for the delay. When %projectName%.app.config is missing, the `Compilation` object does not contain any references for external assemblies used by the project. When app.config is present, the references list is complete. Again, even when I delete the contents of this app.config (binding redirects for the assemblies), the `Compilation` have all the references when this empty file is present. 

This can be reproduced, for example, with [ServiceStack](https://github.com/ServiceStack/ServiceStack), in 'ServiceStack.Authentication.OpenId' project.

**Comment by PaulEremeeff** [comment]
Also, adding binding redirects to app.config to our console app does not seem to help with missing references.

**Comment by Pilchie** [comment]
I cloned ServiceStack, and used the following code.  When I first ran this it worked fine.  However, once I ran `build.cmd` in ServiceStack, the program below started to fail in the way described above. So I added the binding redirects from #3034 to my program (also pasted below for reference), and then it started working.


```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.MSBuild;
using Microsoft.CodeAnalysis.Text;

namespace ConsoleApplication63
{
    class Program
    {
        static void Main(string[] args)
        {
            var ws = MSBuildWorkspace.Create();
            var sln = ws.OpenSolutionAsync(@"D:\Code\ServiceStack\src\ServiceStack.sln").Result;
            var proj = sln.Projects.Single(p => p.Name == "ServiceStack.Authentication.OpenId");

            var c = proj.GetCompilationAsync().Result;

            Console.WriteLine("References");
            foreach (var r in c.References)
            {
                Console.WriteLine(r.Display);
            }

            Console.WriteLine();
            Console.WriteLine("Diagnostics");
            foreach (var  d in c.GetDiagnostics().Where(d => d.Severity != DiagnosticSeverity.Hidden))
            {
                Console.WriteLine(d);
            }
        }
    }
}
```

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <!-- Microsoft.Build.Engine instead of Microsoft.Build here because a task run under Microsoft.Build may load Microsoft.Build.Engine, which will attempt to read this section. -->
        <section name="msbuildToolsets" type="Microsoft.Build.BuildEngine.ToolsetConfigurationSection, Microsoft.Build.Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
    </configSections>
    <runtime>
        <DisableFXClosureWalk enabled="true" />
        <generatePublisherEvidence enabled="false" />
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build.Engine" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build.Conversion.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build.Tasks.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Build.Utilities.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="14.0.0.0"/>
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Microsoft.CompactFramework.Build.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
                <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="9.0.0.0"/>
            </dependentAssembly>
        </assemblyBinding>
    </runtime>
</configuration>
```

**Comment by PaulEremeeff** [comment]
@Pilchie Am I correct at my understanding that binding redirects are added to the console app utilizing Roslyn libs? Although we were not able to fix the issue by adding such redirects to our console app, if I may say so, this solution seems quite inconvenient – as we wish that our app could be utilized (by our users) as a stand-alone static analyzer for csproj projects, requiring a user to modify the app.config for each analysis run seems quite inappropriate. 

So, we currently were forced to implement a workaround – using  `Microsoft.Build.Evaluation.Project` to parse project files and extract references, then adding them manually to Roslyn's 'Project' class. Moreover, when the csproj is missing the `HintPath`, we are forced to use low-level Fusion API (through PInvoke) to get the appropriate version of the assembly from GAC. 

But, should not such a busywork (from architectural point so to speak) be encapsulated inside the Roslyn's `Project` infrastructure? Not meaning to sound offensive or anything, just a feedback )

**Comment by Pilchie** [comment]
@PaulEremeeff: I agree that it's inconvenient.  Unfortunately, there isn't much of an alternative.  If a project we're trying to load references msbuild tasks that were written against an earlier version of msbuild, then those tasks just won't load if the binding redirects aren't present.

With that said, there should be no need for your users to ever modify the settings - simply distribute your app with .exe.config alongside the .exe that includes the binding redirects.

Regarding your workaround - that will work for simple project structures, but won't actually support people who extend their build - you'd end up needing to run a build (as we do in MSBuildWorkspace), and you'd run into the same sort of problem.

The only way we could conceivably do this in a transparent way would be to do our MSBuild evaluation in a separate app domain where we specify the config with the binding redirects.  However, @mattwar already tried that and ran into a bunch of problems with it.  :frowning:
