### ISSUE TITLE
Weird nullable detection

### ISSUE THREAD

**Issue by rui-ktei** [dotnet/roslyn#58187]
**Version Used**: 
.NET 6.0 SDK

**Steps to Reproduce**:
I'm not very sure if this is related to Roslyn or not but it is something regarding the intellisense in VS and Rider.
1. Enable nullable feature in .csproj
2. Create a class with one property `Guid? Id`
3. Write some code like this:
```csharp
var myClass = new MyClass();
var id = myClass.Id != null ? myClass.Id.ToString() : Guid.NewGuid().ToString();
```
4. Observe the behavior (screenshot attached)
What confuses me is that the IDE thinks `id` is `string?` rather than `string`. If you look at the code, no way this `id` can be null, because we have a null check there.
![image](https://user-images.githubusercontent.com/12144265/145148610-e54309c7-6a67-411b-a09b-fa6b4b0dfca9.png)

**Expected Behavior**:
IDE says `id` is `string`

**Actual Behavior**:
IDE says `id` is `string?`

Apologize if this is not related to Roslyn. This is not causing any trouble but I'm curious why it behaves this way. I also understand when code logic becomes complex, we can't easily predict `null`, but this scenario is rather simple.

**Comment by Youssef1313** [comment]
`var` is always nullable. See [LDM](https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-12-18.md).

The compiler will track its nullability states correctly. That's why this is not (and will not be) causing any trouble

**Comment by rui-ktei** [comment]
@Youssef1313 got it. Thanks!
