### ISSUE TITLE
FindAllReferences on Length property or Slice method misses usages in list-patterns 

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#58190]
FAR doesn't understand properties/indexers/methods that are used in list-patterns yet.

```
_ = new Collection() is [1, 2];
class Collection
{
   public int Length => 0;
   public object this[int i] => null;
   public Collection Slice(int i, int j) => null;
}
```

Relates to test plan https://github.com/dotnet/roslyn/issues/51289

**Comment by CyrusNajmabadi** [comment]
Moving out of 17.1  we def don't need this immediately.  Note: this would be a good way for someone to learn how to update FAR/indices.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.  It's also unclear if there's an api to even solve this with.
