### ISSUE TITLE
Invalid token bug?

### ISSUE THREAD

**Issue by khellang** [dotnet/roslyn#582]
Should this:

```csharp
class C
{
    public foo string Message => "Hello World";
}
```

Result in this:

> (5,16): error CS1519: Invalid token 'string' in class, struct, or interface member declaration

?? I'd expect `foo` to be the invalid token, not `string`... See [example](http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcAobBjAGwEMQQYBhbAb2xjpgAdgAjAsPGAMwHtuYUATpFgBZVKSJRUMALwA+GACIAEqgIE+AdW4CCAE0U4AvkAAA)

**Comment by gafter** [comment]
No, "foo" is (syntactically) a perfectly valid return type for a property. But "string" isn't a valid property name.

**Comment by theoy** [comment]
This is a good example where we could present a more intuitive error to the user if someone were to submit a pull request :grin:
