### ISSUE TITLE
Proposal: New compiler error "Your code so bad that I refuse to compile it"

### ISSUE THREAD

**Issue by Indomitable** [dotnet/roslyn#5820]
Today I read for a bug in Roslyn compiler which refuses to compile: (int?)null ?? (int?)5;
I think that instead of fixing this kind of bugs you should introduce a new error in Roslyn compiler:

**Comment by AdamSpeight2008** [comment]
You could write a code analyser for that.

**Comment by gafter** [comment]
We'll get right on that.

**Comment by gafter** [comment]
OK, this is not done. It may need some tuning, however: it is nearly impossible to trigger this error today ;)
