### ISSUE TITLE
Key binding to collapse all #regions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58214]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-references-only-to-the-selected-Ove/1596020)._

---
In the VB.NET code editor, please provide a toolbar and/or ctrl key combination to collapse all #regions.  None of the Edit > Outlining options seem to achieve this.

It would make finding things in large classes so much easier.

---
#### Feedback Bot on 11/25/2021, 11:08 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are unlikely to be changing tehse experiences.
