### ISSUE TITLE
Searching for all references by child class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58222]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Searching-for-all-references-by-child-cl/1598548)._

---
Hello,

I would like to be able to filter the search for a property or function in 'Find All References' by the specific inheriting class that it is being called from.

For example I work with C# in Unity and most classes inherit from the class **MonoBehaviour** which has the **transform** property. If I had a class **A** that inherits from **MonoBehaviour**, I want to be able to filter out all other calls in the 'Find All References' tool so that only calls to _**A**.transform_ show up, whether called by _this.transform_ within the class, or calls in other classes to _**a**.transform_, where **a** is an instance of class **A** or a class that inherits from it. I would imagine this can be done through an additional column called 'referenced from' or something similar.

Thanks,
Connor King

---
#### Feedback Bot on 11/29/2021, 06:33 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
