### ISSUE TITLE
Ensure Coding Styles Suggested or Refactored are Relevant to the Used / Target Version of The Language

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58220]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ensure-Coding-Styles-Suggested-or-Refact/1608312)._

---
Coding style preferences may include refactoring or suggestions for newer version of the language than targeted. In such cases please disable the irrelevant options.

Also running code cleanup please don't mess the code by changing it into code incompatible with the target / compiling version.

E.g. when working on a project targeting .Net 4.0 please don't reformat of suggest formats which were introduced later, but when working on a project targeting a later version please refactor and suggest newer coding styles.

---
#### Feedback Bot on 12/8/2021, 07:28 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
This should be how things work as our features do check lang version.  If there is something we missed, we should address that with specific reported cases and specific fixes.  This issue is too generic to be acted upon.
