### ISSUE TITLE
Add a code cleanup option that turns all C# files to use file-scoped namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58225]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-code-cleanup-option-that-turns-all/1591139)._

---
Really loving file-scoped namespaces to remove unnecessary code indentation. Could you add a code cleanup option that does the "Convert to file-scoped namespace" quick action to all files in a project/solution? Would save a lot of time in a large codebase.

---
#### Feedback Bot on 11/22/2021, 00:03 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
cc @sharwell

**Comment by CyrusNajmabadi** [comment]
This can be done.  just set the desired code style setting to file-scoped-namespace, then run the fixer with 'fix all in project/solutin'.
