### ISSUE TITLE
[LSP] Pass in LSP document version instead of workspace document version for semantic token caching

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#58233]
For semantic tokens caching in LSP, we should eventually pass in the LSP document version instead of the workspace document version. This would ensure the document's contents are properly up to date. We are unable to do this with today's infrastructure since caching is done OOP and the LSP workspace isn't yet available in OOP.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
