### ISSUE TITLE
ICodeGenerationService.CreateMethodDeclaration should not return null

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#58243]

**Comment by Youssef1313** [comment]
Is this about the following?

https://github.com/dotnet/roslyn/blob/f6190793e559d7b69a7e64617f8014ffbb8689af/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs#L580-L597

I can't see what could be done to not return null here.

**Comment by CyrusNajmabadi** [comment]
Would need more information on what is not being generated.  Tomas, do you know what the case was?

**Comment by tmat** [comment]
@Youssef1313 Yes, those are the cases. I think it would be better if the checks were moved to the callers -- i.e. the caller never attempts to generate method decl for the methods for which it doesn't make sense.

**Comment by tmat** [comment]
See https://github.com/dotnet/roslyn/pull/58244/commits/5c348321a5be903253dae9da0207789e09c8801e

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
