### ISSUE TITLE
RFE: Move type to namespace, merge same NS sections

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn#58257]
Not convinced this belongs in *Analyzers*, but I didn't find a closer suitable choice.

Consider the following code in a single file (mentally add `public` to everything if you want to be pedantic):
```
namespace NS1 {
interface I1 {}

class C1 : I1 {}
}
```
You now want to move I1 and C1 to NS2. For one reason or another you couldn't just select both types and move both in one fell swoop. So you first invoke the refactoring on I1, and then on C2. You now end up with
```
namespace NS2 {
interface I1 {}
}

namespace NS2 {
class C1 : I1 {}
}
```

In this scenario, I think it could make sense to merge the two namespace sections (since they are the same).

While low hanging fruit, it's also not especially hight priority. Just one of these quality-of-life improvements to put on the backburner, that maybe could get revisited in 10-15 years.

**Comment by jinujoseph** [comment]
cc @genlu for info

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
