### ISSUE TITLE
Warning on var-declared variables that are never null assigned

### ISSUE THREAD

**Issue by mqudsi** [dotnet/roslyn#58262]
**Version Used**: Version 17.1.0 Preview 1.1

I don't know if this is pedantically a bug in roslyn or if it's an acceptable corner case that merely defies [the documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var), but a `var`-declared nullable reference type that is never assigned a null value still produces a warning if the compiler can't in a single, linear pass determine that it contains a non-nullable value.

The documentation linked above currently says

> When `var` is used with nullable reference types enabled, it always implies a nullable reference type even if the expression type isn't nullable. The compiler's null state analysis protects against dereferencing a potential null value. **If the variable is never assigned to an expression that maybe null, the compiler won't emit any warnings.** If you assign the variable to an expression that might be null, you must test that it isn't null before dereferencing it to avoid any warnings.

But I'm not sure if this is something guaranteed in the language spec or if it's held instead to the same best-effort approach that applies to nullable flow analysis with things like advanced conditional assignments, xor nullables, etc.

**Steps to Reproduce**:

```csharp
var foo = "string";
bool FooStartsWith() {
    return foo.StartsWith("str");
}
```

**Expected Behavior**:

No warnings on the usage of `foo.` since foo was initialized with a non-null value and is never assigned a null or potentially null value.

**Actual Behavior**:

A CS8602 warning is generated for the `foo.StartsWith(...)` invocation because the compiler is unable to prove that `foo` is always non-null when `FooStartsWith()` is called.

I understand *why* it's hard for the compiler to deduce that `foo` will never be null here because when the flow analysis reaches the dereference, it's unaware of whether `foo` may later be assigned a null value and it errs on the side of caution. 

Technically, the compiler can still deduce that it's impossible for a null dereference to occur in a single pass by holding off on emitting the warning until the lifetime of the variable in question is either definitively over (no more outstanding references) and it hasn't been assigned a null value (in which case the warning is to be suppressed) or it's unable to prove that's the case (and the warning is emitted), without needing to actually look into when/where `FooStartsWith()` is called (which would maybe require multiple passes). I'm actually just more curious to know whether or not this behavior is guaranteed in the spec.

(I'm not sure I understand _why_ `var` doesn't conservatively default to a non-nullable reference type when initialized with a non-nullable value and instead generate a warning if a null value is ever assigned to the variable, which seems easier and perhaps saner? But that's obviously not the point of this issue - unless the current behavior is transitional and might change?)

**Comment by RikkiGibson** [comment]
Please see https://github.com/dotnet/roslyn/issues/40157#issuecomment-655056976.

**Comment by mqudsi** [comment]
Thanks - I suppose this can be closed out? I don't know how you guys find those threads, I searched before posting but came back with nothing (vague search terms). Do you know if there were any discussions about my last question regarding why `var` doesn't default to the more conservative non-nullable type?

**Comment by CyrusNajmabadi** [comment]
>Do you know if there were any discussions about my last question regarding why var doesn't default to the more conservative non-nullable type?

Yup.  We def discussed it.  Long story short, we didn't think the effort was worth it, and we were happy with where we landed.  We've been continually listening to feedback though on these decisions to see if there are things we'd want to revise here.  IMO (though i could be wrong), this feels that is unlikely to change.

**Comment by RikkiGibson** [comment]
> I searched before posting but came back with nothing (vague search terms).

Give the new preview GitHub search a try. It's much much better.

**Comment by mqudsi** [comment]
> Yup. We def discussed it.

Sorry, I meant to ask if there were any publicly available (GitHub issues) on the matter to enrich my understanding of how/why things are the way they are and I absolutely did not mean to suggest that such a decision was blithely made :) Thanks for answering that itch!


> Give the new preview GitHub search a try. It's much much better.

I'm unfortunately still waitlisted for that :)

**Comment by Youssef1313** [comment]
@mqudsi https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-12-18.md

**Comment by mqudsi** [comment]
Thanks, @Youssef1313. That really helped! You guys are all incredibly kind and helpful!

**Comment by vladd** [comment]
What I’m missing about this issue is a possibility to explicitly declare a non-nullable local variable with `var`, perhaps something like `var!`, and get the warnings at assignment site rather than at usage site.

**Comment by CyrusNajmabadi** [comment]
@vladd you'd have to start a discussion on csharplang for that.
