### ISSUE TITLE
C# 10 Global Usings Performance

### ISSUE THREAD

**Issue by loganmarshall1** [dotnet/roslyn#58279]
Just wanted to say that everyone at microsoft, c# and dotnet is doing a fantastic job and all of our 6 blazor wasm apps are all on dotnet 6 with AOT and everyone's loving it!

i'm just wondering the performance about eliminating using's from every C-sharp file in a large single project and adding them to a global usings file. Is there any performance losses with removing using's from every file and just putting it in the global using file?

if there's no performance loss I would love to standardize on no using's in any C-sharp file and only put it in the global using's file.

The reason I'm asking this question is I've searched the Microsoft documentation site and online and I can't find anywhere that goes into the performance of the global using approach versus the regular c# 9 and earlier per file scoped usings approach

@MadsTorgersen 🙏❤️

if you read this thank you for your time and I appreciate your brilliance! 🙏

**Comment by CyrusNajmabadi** [comment]
There should be no runtime performance loss to this.

**Comment by loganmarshall1** [comment]
> There should be no runtime performance loss to this. 

Thank you so much for your quick answer. 

I'm more looking for A technical explanation architecturally why there wouldn't be?  That way I can have complete confidence in the change before I make it.

Thanks kindly

**Comment by CyrusNajmabadi** [comment]
Because usings are only needed at compile time to determine which symbols are referenced.  Once determined, that information is just written into the resultant dll. 

At compile time you can write the symbol names it in a fully fully qualified fashion, it you can write the symbol name and the compiler can find the actual symbol in the namespaces brought in by the using. 

However, the end dll will be identical. The using itself (global or otherwise) is not itself encoded into the dll.  As such it can have no runtime impact.

**Comment by loganmarshall1** [comment]
> Because usings are only needed at compile time to determine which symbols are referenced.  Once determined, that information is just written into the resultant dll. 
> 
> 
> 
> At compile time you can write the symbol names it in a fully fully qualified fashion, it you can write the symbol name and the compiler can find the actual symbol in the namespaces brought in by the using. 
> 
> 
> 
> However, the end dll will be identical. The using itself (global or otherwise) is not itself encoded into the dll.  As such it can have no runtime impact. 

Thanks much that's very helpful. Makes perfect sense thanks again.

**Comment by adcloeshelle** [comment]
@CyrusNajmabadi How about on the compilation side? Do you expect global using to impact compilation performance, especially in larger projects or solutions?

**Comment by CyrusNajmabadi** [comment]
They should not have a noticeable impact on compile times.

**Comment by js3k** [comment]
⚙️ Penjelasan Singkat

- global using hanya mempengaruhi kompilasi, bukan eksekusi.
- Compiler akan otomatis menyisipkan namespace itu ke semua file, jadi kamu nggak perlu nulis manual.
- Di runtime, hasilnya sama persis seperti kalau kamu pakai using biasa.

---

🧠 Analogi Rebahan

> "Global using itu kayak remote universal—bikin hidup nyaman, tapi nggak bikin AC boros listrik."

---

📈 Performanya Tetap Stabil

| Aspek              | Pengaruh Global Using |
|--------------------|------------------------|
| Kompilasi          | Sedikit lebih cepat (karena file lebih bersih) ✅ |
| Runtime performance| Tidak berubah sama sekali ✅ |
| Memory usage       | Tidak terpengaruh ✅ |
| Binary size        | Tetap sama ✅ |

---

🛠️ Tips Tambahan

- Jangan terlalu banyak global using yang nggak dipakai—biar tetap rapi dan nggak bikin bingung.
- Bisa pisah Usings.Api.cs, Usings.Domain.cs, dll kalau project makin modular.
