### ISSUE TITLE
Pattern matching: exhaustiveness check doesn't take null into account while nullable is disabled

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#58287]
**Version Used**: main

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABAEygGdMcBYAKAAEBGABlwDEB7ZgCmeACtsBjAF1ycuASkoBvSrmm4AbhABOciKmR4AvEO64iAdyj9eACykzJFGZdziAvrnUA+XACIYzQSnTPT0mwG4fXECqAHZlVWwAihtKShZ2T1QRPyA==

**Expected Behavior**:
Warn on non-exhaustiveness

**Actual Behavior**:
No warnings

**Comment by alrz** [comment]
>exhaustiveness check doesn't take null into account while nullable is disabled

That's correct. Exhaustiveness check doesn't take null into account while nullable is disabled.

**Comment by hez2010** [comment]
Closing as it's by design.
