### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by yiszza** [dotnet/roslyn#58286]
**Version Used**: latest version

**Steps to Reproduce**:

[RoslynTest.zip](https://github.com/dotnet/roslyn/files/7698443/RoslynTest.zip)

code : 
```
MSBuildWorkspace workspace = MSBuildWorkspace.Create();
var project = await workspace.OpenProjectAsync(@"../../../RoslynTest.csproj");

if (project.Documents.Count() == 0)
{
    var diagnostics = workspace.Diagnostics;
    foreach (var diagnostic in diagnostics)
    {
        Console.WriteLine(diagnostic.Message);
    }
}
```
run the demo,

**Expected Behavior**: project.Documents.Count() != 0;

**Actual Behavior**: project.Documents.Count() == 0; The SDK 'Microsoft.NET.Sdk' specified could not be found.

**Comment by cguedel** [comment]
Any update and/or workaround for this?

**Comment by yiszza** [comment]
> Any update and/or workaround for this?
Maybe not

**Comment by WeihanLi** [comment]
The same problem met

**Comment by LordBenjamin** [comment]
I'm also able to reproduce.

csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.5.3" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.2.0" />
  </ItemGroup>
</Project>

```

Program.cs:

```c#
using System.Reflection;
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;

internal class Program {
    public static async Task Main(string[] args) {
        var vs = MSBuildLocator.QueryVisualStudioInstances().First();
        Console.WriteLine(vs.Name);
        Console.WriteLine(vs.Version);
        Console.WriteLine(vs.DiscoveryType);
        Console.WriteLine(vs.MSBuildPath);
        Console.WriteLine(vs.VisualStudioRootPath);
        Console.WriteLine();

        MSBuildLocator.RegisterDefaults();

        using (var workspace = MSBuildWorkspace.Create()) {
            workspace.WorkspaceFailed += Workspace_WorkspaceFailed;

            var project = await workspace.OpenProjectAsync(@"/path/to/file.csproj");
        }
    }

    private static void Workspace_WorkspaceFailed(object? sender, WorkspaceDiagnosticEventArgs e) {
        Console.WriteLine(e.Diagnostic.Message);
    }
}
```

Prints:

```
.NET Core SDK
6.0.400
DotNetSdk
C:\Program Files\dotnet\sdk\6.0.400
C:\Program Files\dotnet\sdk\6.0.400

Msbuild failed when processing the file '/path/to/file.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  /path/to/file.csproj
```

SDKs installed:

```
$ dotnet --list-sdks
6.0.303 [C:\Program Files\dotnet\sdk]
6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]
```

VS versions installed: 2019, 2022, 2022-preview

**Comment by LordBenjamin** [comment]
So I managed to get my code working:
* Changed from targeting `net6.0` to `net472`
* Changed from `MSBuildLocator.RegisterDefaults()` to `MSBuildLocator.RegisterInstance(MSBuildLocator.QueryVisualStudioInstances().Last())`

This essentially means that instead of `MSBuildLocator` registering the .NET 6.0 SDK, it's registering Visual Studio 2022 **Preview**.

Note that this is the only combination that works on my PC - net472/VS2022 didn't work, and none of the three net6.0 SDKs worked.

I found that the "Standalone Code Analysis Tool" template in Visual Studio made it easy to reproduce this issue with various frameworks (because it lets you pick which MSBuild instance to use).
![image](https://user-images.githubusercontent.com/13396705/185454057-7198cf30-37b4-4bf9-a4c6-9dcaa1bdd607.png)

I hope this helps Microsoft debug the issue, and might help others as a workaround (assuming .NET Framework is an option for you).

**Comment by JoeRobich** [comment]
@LordBenjamin Your original code would work if you downgrade MSBuildLocator to version 1.4.1. Seems that something has regressed in that package.

**Comment by JoeRobich** [comment]
@yiszza To use MSBuildWorkspace we recommend using [MSBuildLocator](https://github.com/Microsoft/MSBuildLocator) to load an installation of MSBuild Tools either from a .NET SDK or a VS install. In your project you only referenced the `Microsoft.Build` package which does not bring along the needed build tasks and target.

**Comment by ceztko** [comment]
Thanks @JoeRobich, downgrading to 1.4.1 works for me and saves my day. It's the bug correctly tracked here?

**Comment by JoeRobich** [comment]
The bug is https://github.com/microsoft/MSBuildLocator/issues/176. One workaround is to query for the instance your want then when registering the MSBuildPath, ensure it ends with a directory separator.

```csharp
var instance = MSBuildLocator.QueryVisualStudioInstances().First();
var msBuildPath = Path.EndsInDirectorySeparator(instance.MSBuildPath)
    ? instance.MSBuildPath
    : instance.MSBuildPath + Path.DirectorySeparatorChar;
MSBuildLocator.RegisterMSBuildPath(msBuildPath);
```
