### ISSUE TITLE
MSBuild support for the pathmap option

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5830]
We need to plumb support for the `pathmap` option (as described in #949) through MSBuild.

**Comment by TyOverby** [comment]
Is this option already in the compiler and just needs to get plumbed through?  I can't find any reference to it in the source.

**Comment by jaredpar** [comment]
@TyOverby it's being added by PR #4543.  This should get merged in today.

**Comment by TyOverby** [comment]
Ok, great!
