### ISSUE TITLE
Parameter null-checking public API

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58307]
## Background and Motivation

The parameter null checking feature #36024 needs some new public APIs and behavior changes to public API.

## Proposed API

<details>
    <summary>**Rejected** symbol API</summary>

```diff
namespace Microsoft.CodeAnalysis
{
     public interface IParameterSymbol
     {
+        /// <summary>
+        /// True if the compiler will synthesize a null check for this parameter (the parameter is declared in source with a <c>!!</c> following the parameter name).
+        /// </summary>
+        bool IsNullChecked { get; }
     }
}
```
</details>

```diff
namespace Microsoft.CodeAnalysis.CSharp
{
    public enum SyntaxKind
    {
        // ...

        /// <summary>Represents <c>??=</c> token.</summary>
        QuestionQuestionEqualsToken = 8284,
+        /// <summary>Represents <c>!!</c> token.</summary>
+        ExclamationExclamationToken = 8285,
    }
}

namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public sealed class ParameterSyntax
    {
+        public SyntaxToken ExclamationExclamationToken { get; }
    }
}
```

## Usage Examples

The IDE uses these APIs to properly support the feature. For example, the refactoring to add a null check for a parameter:
https://github.com/dotnet/roslyn/blob/828a71d34f712b89276189acee9ec17d8f142506/src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs#L246-L270

https://github.com/dotnet/roslyn/blob/828a71d34f712b89276189acee9ec17d8f142506/src/Features/CSharp/Portable/InitializeParameter/CSharpAddParameterCheckCodeRefactoringProvider.cs#L97-L112

## Alternative Designs

One alternative would be to eliminate `IParameterSymbol.IsNullChecked`, and force public users to go through syntax and check the `ParameterSyntax.ExclamationExclamationToken` to determine if a parameter is null checked. It seems inconvenient, especially when it comes to IOperation scenarios, where the user may not be referencing `MS.CA.CSharp` but still want to know if a parameter was null checked.

## Risks

Not aware of any risks from the current design.

## Control flow graph

In the current feature implementation, the IOperation behavior is the same whether or not parameter null checking is used. Users are expected to grab the parameter symbol and check its `IsNullChecked` property if they care about it. This seems consistent with IOperation behaviors in other "implicit code" scenarios.

However, the control flow graph behavior **does** currently differ depending on whether parameter null checking is used. Nodes are inserted to represent where the null check occurs and what the semantics of the null check roughly are. **Should the API do this?** Or should the graph be the same regardless of whether parameter null-checking is used, leaving users to check the `IParameterSymbol.IsNullChecked` API and handle appropriately if they need to?

https://github.com/dotnet/roslyn/blob/6ba3deac0e53fbc9e29a867a935fc83d9baf9561/src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_NullCheckedParameters.cs#L19-L54

**Comment by RikkiGibson** [comment]
@AlekseyTs Could I please get your feedback on this, particularly the *Proposed API* and the questions in the *Control flow graph* section?

**Comment by AlekseyTs** [comment]
> Could I please get your feedback on this, particularly the Proposed API and the questions in the Control flow graph section?

I am not a big fan of adding ```IsNullChecked ``` API, but this is not a strong objection and I think the API should be brought to the API review.

Regarding the CFG, I do not think the feature should have any impact on the shape of IOperation tree or CFG.

**Comment by RikkiGibson** [comment]
Conclusion (Fred, feel to correct/modify this):

1. IParameterSymbol.IsNullChecked will be removed.
2. Syntax API is fine as written in issue description.
3. CFG will not produce additional nodes to represent parameter null checks.
