### ISSUE TITLE
Remove Constraint on "Comparison" Operators

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#5831]
Remove the requirement on "comparison" operator overloading, of having to be defined in complement pairs.
```
 <   =>
 <=  >
 =   <>
 <>  =
 =>  <
 >   <=
```
All existing types would still work and build, as they are already defined them, thus subsequent usage will still continue to work. But now objects can the define the specific operator that want to overload. Attempting to use an non implemented operator would be a compile-time error and it is possible (?) runtime error.

**Comment by whoisj** [comment]
As I understood the compiler error when not defining them in pairs is to help resolve the problem of developers forgetting to overload an operator they meant to and getting unexpected results.

Perhaps there should just be a way to tell the compiler: "use the default, I purposefully did not implement this"?

**Comment by gafter** [comment]
@AdamSpeight2008 This change seems unlikely. If you want one to work and the other to be an error, mark the unsupported one `[Obsolete("Operator not supported for this type", true)]`.
