### ISSUE TITLE
ExpressionEvaulator Resultprovider unit tests are failing due to missing implementation.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5832]
I'm seeing 2 new unit test failures in today's standalone results. They narrow down to a single issue: See the bottom. Was there a recent API change here? 

 System.TypeLoadException : Method 'IsFunctionPointerImpl' in type 'Microsoft.CodeAnalysis.ExpressionEvaluator.TypeImpl' from assembly 'Roslyn.ExpressionEvaluator.ResultProvider.Test.Utilities, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fc793a00266884fb' does not have an implementation.
      Stack Trace:
            at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProviderTestBase.CreateDkmClrValue(Object value, Type type, String alias, DkmEvaluationResultFlags evalFlags, DkmClrValueFlags valueFlags)
            at Microsoft.CodeAnalysis.CSharp.UnitTests.ValueFormattingTests.Float()

Unit tests failing are:
Roslyn.ExpressionEvaluator.CSharp.ResultProvider.UnitTests.dll
Roslyn.ExpressionEvaulator.VisualBasic.ResultProvider.UnitTests.dll
All tests are failing inside of these two.

**Comment by ManishJayaswal** [comment]
This has been fixed with and internal change
