### ISSUE TITLE
System.InvalidProgramException when constructing a record struct with parameter list and calling the default constructor

### ISSUE THREAD

**Issue by V0ldek** [dotnet/roslyn#58328]
**Version Used**: 
.NET SDK:
 Version: 6.0.100
 Commit: 9e8b04bbff

**Steps to Reproduce**:

1. Create a record struct with a parameter list with at least two parameters:
```csharp
public record struct S(char First, char Second)
{
}
```
2. Add a constructor that takes a parameter of some type (the exact type seems to not matter):
```csharp
public record struct S(char First, char Second)
{
    public S(object o)
    {
    }
}
```
3. This produces CS8862: A constructor declared in a record with parameter list must have 'this' constructor initializer, which is expected. To fix this error, add a call to the _default_ constructor:
```csharp
public record struct S(char First, char Second)
{
    public S(object o) : this()
    {
    }
}
```
4. Attempt to create an instance of the struct:
```csharp
var s = new S(new object());

Console.WriteLine(s);
```

**Expected Behavior**:
The struct is created and printed with `First` and `Second` set to `default(char)`.

**Actual Behavior**:
A `System.InvalidProgramException` is thrown during execution:

```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program. 
    at S..ctor(Object o)                                                                                                    
    at Program.<Main>$(String[] args) in D:\<path_ommited>\Program.cs:line 1
```

**Full code**:

Occurs both when running compiled to Debug and Release.

```csharp
var s = new S(new object());

System.Console.WriteLine(s);

public record struct S(char First, char Second)
{
    public S(object o) : this()
    {
    }
}
```

https://dotnetfiddle.net/85o0Th

**Comment by V0ldek** [comment]
Additional notes:
1. Calling the synthesised record constructor with two parameters works:
```csharp
public record struct S(char First, char Second)
{
    public S(object o) : this(default(char), default(char))
    {
    }
}
```
2. The issue does not appear when there is one record parameter:
```csharp
public record struct S(char First)
{
    public S(object o) : this()
    {
    }
}
```
**HOWEVER** then the parameter is initalized to garbage -- in my case it's the char '?', but it's clearly not zero-initialized. Changing the type to `int` produces a seemingly random value, probably a piece of memory that wasn't initialized.

**Comment by V0ldek** [comment]
Decompiling with [sharplab.io shows me the following IL](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwG4QBOABAM7EC8xMApgO7EDKAFLQwPbABWNAxgswCUggNwBYAFCSAAgEYAdHICczUqMkyAzMUJ92hdGQSEArvybNeACyLEAYlEKkEcYtduM9MdIMkBvSWIg4mltFk4ec3ZBYhBiBCsoUiFA4ICJYOIAX0ksoA) for the `S(object)` constructor:
```il
.method public hidebysig specialname rtspecialname 
    instance void .ctor (
        object o
    ) cil managed 
{
    // Method begins at RVA 0x20b0
    // Code size 16 (0x10)
    .maxstack 8

    IL_0000: nop
    IL_0001: ldarg.0
    IL_0002: ldarg.1
    IL_0003: stfld char S::'<First>k__BackingField'
    IL_0008: ldarg.0
    IL_0009: ldarg.2
    IL_000a: stfld char S::'<Second>k__BackingField'
    IL_000f: ret
} // end of method S::.ctor
```

Looks invalid to me, there's `IL_0009: ldarg.2`, while the constructor has only two arguments (`this` and `object o`).

**Comment by cston** [comment]
Thanks for reporting this issue @V0ldek. 

I believe the compiler should require that explicit constructors in the `record struct` call either the implicit primary constructor or another explicit constructor.

The constructors above that call `this()` should be reported as errors since the primary constructor and explicit constructors have parameters in each case.
