### ISSUE TITLE
Consider fading unnecessary/trivial discard pattern

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58331]
> I think this is a slightly unfortunate behavior. It does indeed come down to an interaction between pure null tests and exhaustiveness checks. The resolution I would probably want here is to warn even when the input expression doesn't have a slot. i.e. warn when the switch input is a variable as well as when the input is a method call.
>
> As far as `{ Item: _ }` goes, it's a weird one, since it's one of the only patterns which can result in us never actually accessing the property in the emitted code. I would be fine with treating it as a pure null test, but I'd probably be more interested in making a change to grey out such patterns in the IDE.

_Originally posted by @RikkiGibson in https://github.com/dotnet/roslyn/issues/58297#issuecomment-993053079_

**Comment by sharwell** [comment]
Since `value is { Item: _ }` is semantically equivalent to `value is { Item: var _ }` or even `value is { }`, the use of `Item: _` is technically unnecessary and could be faded or removed.

Before implementing this change, we should determine if users are likely to include `_` explicitly as part of showing that the value was considered but does not matter. This is similar to explicitly assigning the result of an expression to a discard, when it could also just as easily have been ignored.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
