### ISSUE TITLE
Allow completion to add a global using rather than a file scoped using

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#58341]
(This feature request was been spliced from https://github.com/dotnet/project-system/issues/7823.)

Update Visual Studio to use the global usings file when inserting a namespace as part of intelisense auto correct. Current behavior is to add the using statement to the current file which is not always desirable.

**Comment by jinujoseph** [comment]
@sharwell

**Comment by sharwell** [comment]
Resolving as **won't fix** per the discussion in https://github.com/dotnet/roslyn/issues/55895#issuecomment-940461765

**Comment by CyrusNajmabadi** [comment]
Design conclusion: 

We reassert that we will not have completion automatically add global imports.

1. far too easy to get into a situation where a minor change can break an entire project.
2. far too hard to realize what has happened.
3. can be very difficult to get back to a good state.

If we saw persistent demand here from users we might reconsider, but would always put this option behind some flag a user would have to opt into.
