### ISSUE TITLE
Option Strict - Object Initialization can be simplified

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58352]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-Strict---Object-Initialization-ca/1611948)._

---
[severity:It bothers me. A fix would be nice]
dim x = new SQLConnection works fine everywhere except in a class variable (outside any sub/function).  When used as a class variable, Option Strict says it must have an "As" clause but with
[Example.zip] (https://aka.ms/dc/file?name=B553b2fb6f8f14e1aa962a0faa8e16a02637750076750308149_Example.zip&tid=553b2fb6f8f14e1aa962a0faa8e16a02637750076750308149)
 an "As" clause, you get a IDE0140	Object creation can be simplified

---
#### Feedback Bot on 12/13/2021, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to chnage these experiences.
