### ISSUE TITLE
IDE0150 incorrectly flags is object check in Expression<Func<T>> where pattern matching is not supported

### ISSUE THREAD

**Issue by BMagerMT** [dotnet/roslyn#58377]
For example in the following the parameter is an Expression<Func<Unit>> (Unit is our type and not important to the issue).

![image](https://user-images.githubusercontent.com/38988659/146439919-306e227e-2ad2-4bfc-a515-f116a23362fa.png)

As you can see it indicates an issue because using "is not null" is preferred. However, in this case it is not supported and if the suggestion is implemented then there is an error. IDE0150 "Prefer 'null' check over type check"

![image](https://user-images.githubusercontent.com/38988659/146440193-58e238c9-d2de-4cb3-bf75-1f62c932886f.png)

CS8122 - An expression tree may not contain an 'is' pattern-matching operator.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/59254

![image](https://user-images.githubusercontent.com/4564579/153286155-daa409be-d0e7-41c8-8586-d9aaee853273.png)
