### ISSUE TITLE
Remove or migrate file based logging for IDE diagnostic analyzer service

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#58394]
https://github.com/dotnet/roslyn/pull/53053 added support for opt-in file logging for generating additional diagnostic logs for IDE diagnostic analyzer service. Description from the PR:

> Adds a new option to enable logging diagnostics information to a log file inside the temp folder, which the user can submit for any intellisense diagnostics/error list related issues. We are not investing in a full-fledged system here as we anticipate many architectural changes in the diagnostics system in Dev17. The support added here is a short term solution to enable getting additional logs.

This issue tracks either migrating this file based logging to loghub based logging OR completely removing this file based logging if there are architectural changes that leads to this logging becoming redundant.

**Comment by jasonmalinowski** [comment]
In discussion, we didn't think we can move this logging over to LogHub yet; @mavasani did you want to close this bug or leave it around for longer?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
