### ISSUE TITLE
IDE suggests refactoring for "add using" instead of "add using static" on static classes

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#584]
If you reference a static member of a static class in the current compilation without qualifying on the static class or static importing the class, the IDE suggests a refactoring to "add `using`" on the static class, rather than the syntactically valid "add `using static`"

**Comment by srivatsn** [comment]
I don't think we show suggestions for add using for a static type. Maybe you ran into a case where the namespace and type name collided? Do you have a repro for this?

**Comment by agocke** [comment]
My original repro was very large. I'll try and get a reduced one.

**Comment by agocke** [comment]
This was a namespace/type collision. Not a bug. Closing.
