### ISSUE TITLE
Provide IDE hint for specifying attribute target

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn#58422]
**Brief description:**

Sometimes, certain attribute target can't be applied without attribute target syntax, for example `[return: ]` for methods, `[property: ]` for record primary constructor, and lambda parameters.
Many user are not familiar with the syntax, or the valid targets of specific code element. They are reporting issues to the APIs, for example https://github.com/dotnet/runtime/issues/62961 https://github.com/dotnet/runtime/issues/49212 https://github.com/dotnet/runtime/issues/60690

The IDE and compiler should hint the user for it. Specifically, if an attribute will become valid when adding attribute target syntax, the IDE should provide a code fix for it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
