### ISSUE TITLE
Inline diagnostic tags are oddly rendered if there's linked files involved

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#58443]
Screenshot. Observe the boldness and color artifacting from subpixel rendering.

![image](https://user-images.githubusercontent.com/201340/146860432-e197fcad-c496-4cd7-b190-78591b35d984.png)

In this case I was editing a file in Roslyn (FatalError.cs) that's linked into a bunch of different projects. I had a syntax error in that, which means there's an error appearing from each project simultaneously, all being rendered on top of each other. Since the tag has a transparent background, the text gets rendered atop each other multiple times. If your font rendering is using clear type or other subpixel smoothing, you end up with it being bold and with weird color artifacts.

The fix is probably to either make the background non-transparent, or just dedup before we render the tag multiple times.

**Comment by akhera99** [comment]
@jasonmalinowski does this still repro? I was unable to get it repro and this issue was brought up when there were existing issues with diagnostics.

**Comment by jasonmalinowski** [comment]
@akhera99 I'm still seeing this on 17.2 Preview 1 at least; was there a different build you wanted me to try?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.  If we need to do this, we need to assign a milestone to get this fixed in.
