### ISSUE TITLE
if you have: `readonly ref int x = ref y` does this count as a read/write ref now?  or just a read-ref?  It should be the latter.  Can  you check, fix if necessary, and add test?

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58466]
> if you have: `readonly ref int x = ref y` does this count as a read/write ref now?  or just a read-ref?  It should be the latter.  Can  you check, fix if necessary, and add test?

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/58459#discussion_r774043282_

Follow-up to #58459

**Comment by mavasani** [comment]
@CyrusNajmabadi @sharwell This case seems to be already addressed in the existing code and we also have a test validating the same: https://github.com/dotnet/roslyn/blob/678b269e0e31a1b31ed1dfc74b464929218b7039/src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs#L1611-L1634

The product code handling this case is below: https://github.com/dotnet/roslyn/blob/678b269e0e31a1b31ed1dfc74b464929218b7039/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs#L206-L219

Note that `readonly ref` is only valid for a variable declaration, not a simple assignment, my recent PR #58459 handled the missing simple assignment with ref case.

**Comment by mavasani** [comment]
Synced with Cyrus, closing issue.
