### ISSUE TITLE
Update the code that computes effective severity for EditorConfig UX similar to #58461

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#58462]
> We also need to update the code that computes effective severity for EditorConfig UX, I will file a separate issue for the same.

FYI @jmarolf - I'll file an issue for this and assign it to you. I couldn't figure out a trivial fix to thread in CompilationOptions into the below methods used for EditorConfig UX: https://github.com/dotnet/roslyn/blob/bf84ccf384893628e7b33fd695b59372131527ce/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/DiagnosticDescriptorExtensions.cs#L53-L135

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/58461#issuecomment-999404255_

**Comment by sharwell** [comment]
⚠️ This feature is likely already working as designed.

**Comment by mavasani** [comment]
I believe this issue can be closed as per Sam's last comment.
