### ISSUE TITLE
IntelliSense not suggesting namespaces after `using` for top-level statements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58470]
**Version Used**: 

17.1.0 P1.1

**Steps to Reproduce**:

1. Trigger completion here, it works as expected.
    ```csharp
    using System;
    using Sys$$
    ```

    ![image](https://user-images.githubusercontent.com/31348972/147214418-7f59fc32-7d60-4dbe-b83e-31e98560f720.png)

2. Trigger completion here, it doesn't work.
    ```csharp
    using System;
    using Sys$$

    Console.WriteLine();
    ```

    ![image](https://user-images.githubusercontent.com/31348972/147214482-b8e6829a-302d-4f27-acf0-f2ade0c16637.png)

Note that `using $$` triggers IntelliSense properly. But `using Sys$$` fails.

It's most likely caused by `using Sys` gets parsed as `LocalDeclarationStatement`, while `using` alone is parsed as an incomplete `UsingDirective`

**Comment by Youssef1313** [comment]
Reporting per https://stackoverflow.com/questions/70437767/top-level-statements-live-code-suggestion-not-working

**Comment by dfkeenan** [comment]
I was experiencing this yesterday. Seemed like if I typed anywhere other then the end of the file code completion broke down. 

I was using 17.2.X.

**Comment by CyrusNajmabadi** [comment]
I don't repro this:
