### ISSUE TITLE
Source generators cannot use a hint name with valid metadata naming convention characters

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58476]
**Version Used**: 4.0.1-1.21558.15 (b3e69109)

**Steps to Reproduce**:

Implement a source generator that adds a source for the following class using the metadata naming convention:

```cs
public partial class Outer
{
    public struct Inner<T>
    {
    }
}
```

The name for this file would be ``Outer+Inner`1.g.cs``.

**Expected Behavior**:

The source generator is successful.

**Actual Behavior**:

The source generator fails because it disallows the [desired characters `` ` `` and `+`](https://github.com/dotnet/roslyn/blob/main/src/Dependencies/Collections/ImmutableSegmentedList%601+Builder.cs) from the hint name.

**Comment by Sergio0694** [comment]
+1 to this. I had to implement a small helper to adjust the hint name for all generated files in all my generators as well to account for this and remove unsupported characters. Would be great to just be able to use the full metadata name directly instead 🙂
