### ISSUE TITLE
Array index from end in ValueTuple assignment throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by zmj** [dotnet/roslyn#58472]
### Description

Assignment from tuple destructuring into a FromEnd index of a generic array throws IndexOutOfRangeException. It looks like `stelem` is called with the Index's raw value, instead of a computed value from the array length.

### Reproduction Steps

```
M(new int[1]);

void M<T>(T[] a)
{
    (a[0], a[^1]) = (default, default);
}
```

### Expected behavior

Assignment succeeds

### Actual behavior

IndexOutOfRangeException

### Configuration

.NET 6.0.101

**Comment by CyrusNajmabadi** [comment]
Yup.  I repro this, and it's super odd.  @jcouv ?

**Comment by reflectronic** [comment]
Seems like there are two issues at play. Roslyn is emitting [invalid IL](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwFkAKAOxgHcACbUjAbQEYBdASgG4BYAKB/oGUAFgEMoABwAyw4ADoASgFc62ALYwZAKWwYA4jHJRsYYhgCeYmBABmxWhlatmPAAIoqhADwAVAHzEv9MxUwqw8AN48VFFUxML0AAzMaMH0AHqJrFQAvDEAJjBWwgq4GMn5hcX2XNwAvjxAA===) for the second assignment:
```
.maxstack 4
.locals init (
    [0] !!T[],
    [1] valuetype [System.Private.CoreLib]System.Index,
    [2] !!T
)

// ...
IL_001b: ldloc.0
IL_001c: ldloc.1 // <---- Suspicious
IL_001d: ldloca.s 2
IL_001f: initobj !!T
IL_0025: ldloc.2
IL_0026: stelem !!T
``` 

The `stelem` opcode requires that the value pushed for _index_ (which I emphasized in the above example with a comment) must be "of type `native int` or `int32`" (§III.4.26). However, the value pushed by `ldloc.1` is a `System.Index`. So, aside from Roslyn emitting invalid code, there is a secondary (and perhaps less critical) bug where the JIT isn't detecting this as an invalid program.

**Comment by CyrusNajmabadi** [comment]
repros for:

```c#
M(new int[1]);

void M<T>(T[] a)
{
    (int v, a[^1]) = (default, default);
} 
```

Does not repro for:

```c#
M(new int[1]);

void M(int[] a)
{
    (int v, a[^1]) = (default, default);
}

**Comment by Youssef1313** [comment]
Doesn't reproduce in `main` branch.
