### ISSUE TITLE
Ternary type inference failure

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/roslyn#58485]
**Version Used**: 

Visual Studio 2022 / SharpLab Main (8 Dec 2021)

**Steps to Reproduce**:

```
using System;

Console.WriteLine(GetValue(false).GetType().Name);

object GetValue(bool shouldBeLong)
{
    long value = 3;
    return shouldBeLong ? value : (int)value;
}
```

**Expected Behavior**:

A human being looking at the code can clearly see that the intent of it is for `GetValue` to return a boxed `Int64` when `shouldBeLong` is `true`, and a boxed `Int32` when it is `false`.

**Actual Behavior**:

`GetValue` unconditionally returns a boxed `Int64`.  Visual Studio shows a Message-level diagnostic stating that the cast to `int` is redundant.

**Comment by canton7** [comment]
The compiler is following [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#conditional-operator) here:

> The second and third operands, x and y, of the ?: operator control the type of the conditional expression.
>
> - If `x` has type `X` and `y` has type `Y` then
>   - If an implicit conversion (Implicit conversions) exists from `X` to `Y`, but not from `Y` to `X`, then `Y` is the type of the conditional expression.
>   - If an implicit conversion (Implicit conversions) exists from `Y` to `X`, but not from `X` to `Y`, then `X` is the type of the conditional expression.
>   - Otherwise, no expression type can be determined, and a compile-time error occurs.

There's an implicit conversion from `int` to `long`, so the type of the conditional expression is `long`. The compiler is correctly informing you that your cast is doing nothing.

**Comment by masonwheeler** [comment]
Good catch.  But if you didn't know that, and you looked at the code itself, you can easily tell that the intent of the code as-written is not what the spec says.

.NET takes a lot of pride in the concept of "the pit of success," the idea that the system is designed well enough that code will accidentally end up doing the right thing without the developer having to be a language lawyer and know all the fiddly little details to make it turn out that way.  This result violates that principle.  Perhaps the spec could benefit from an update?  It seems unlikely that doing so would break anything, as any existing code following this pattern is currently almost certainly doing the wrong thing anyway.

**Comment by canton7** [comment]
But, to look at it a slightly different way, would you expect your code to differ from:

```cs
object GetValue(bool shouldBeLong)
{
    long value = 3;
    var result = shouldBeLong ? value : (int)value;
    return result;
}
```

I'd expect them to both do the same thing, but you don't?

-------

If you're proposing a spec update, I think step 1 is to figure out what the update should be.

**Comment by masonwheeler** [comment]
> I'd expect them to both do the same thing, but you don't?

I don't.  The second version has less information available as input to the type inference mechanism, so it's not surprising that it would yield a different result.

**Comment by canton7** [comment]
Right, but to come to that conclusion you had to reason about how the type inference mechanism works and what information is available to it, which is hardly the Pit of Success.

**Comment by masonwheeler** [comment]
I look at it as reasoning about treating each Statement as a discrete piece of work.

Version 1: Statement says "compute ternary and return as function return type, which is `object`."
Version 2: First Statement says "compute ternary and infer type," second Statement says "return value as function return type, which is `object`."

If instead of `var result = shouldBeLong ? value : (int)value;` it was `object result = shouldBeLong ? value : (int)value;`, I would expect that knowledge of the expected return type, which does not exist when you use `var`, to be taken into account.

**Comment by CyrusNajmabadi** [comment]
Closing out as the compiler is working as per the language spec. 

If you want the language to change here, please open a discussion at csharplang. 

Note: a change like what you are asking is for is highly unlikely as it would definitely be a breaking change and it would be certain to affect existing codebases. We know this for certain as we have tried to tweak rules in this space, and every time we have tried we have found it breaks real code.

**Comment by CyrusNajmabadi** [comment]
>  I would expect that knowledge of the expected return type, which does not exist when you use var, to be taken into account.

It's reasonable for you to want this. However, until the last release, the language didn't work this way at all. Instead, we would find the common type of the ternary and convert burn branches to that. Types only flowed out of the expression, not into it. 

I'm the last release we made it so that if that process failed (e.g. no common type found), then we can look at surrounding context to inform the type. However, that must only happen in the failure case to prevent code from changing meaning and now breaking.

**Comment by CyrusNajmabadi** [comment]
> A human being looking at the code can clearly see that the intent

Note: that's not at all how i read it.  I look at a ternary and as a human I determine what it returns independent of what context it appears in.  That's a virtuous part of the language for me.  That a ternary with compatible 'arm' types can have its type known independent of where it appears.

Your perspective is understandable though.  It's just not what the language has ever done.  This would, in effect, be relitigating subjective choices in the lang design here made over 20 years ago and which has become baked deeply into the entire ecosystem.  Such relitigation is extremely rare and is almost never done when the following is true:

1. it takes existing legal code and changes the meaning of it in a significant way.
2. it is likely to hit a lot of programs that are likely to be depending on the current behavior.

In this case, both of the above are true.  Which would make this sort of change one of the worst types of breaks imaginable.  

--

Note: if we do create a new language, this would likely be something we'd consider up front as to whether we wanted the "inside out" type semantics we have today, or if we'd want "outside in" where an outer type could contextually feed into things (or some hybrid of both).  But for C#, it would be nigh impossible to change this.  Def feel free to continue the discussion over at csharplang though if you want!
