### ISSUE TITLE
Generate field/property not working in top-level statement.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#58491]
The following works:

```c#
class C
{
    static void Main(string[] args)
    {
        Test x = new() { A = 1, B = 1 };
    }
}

class Test { 
}
```

![image](https://user-images.githubusercontent.com/4564579/147395326-4218d399-a3f6-4211-b131-918c6d7943ae.png)

But this does not:

```c#
var x = new Test() { A = 1, B = 1 };
class Test
{
}
```

![image](https://user-images.githubusercontent.com/4564579/147395337-225b25e0-980b-4278-bcbc-bda04793dee0.png)

**Comment by VBAndCs** [comment]
```
class Program {
    void Main()
    {
        Test x = new() { A = 1, B = 1 };
    }
}
```

The genrating code for Test will be:
```
internal class Test
{
}
```

ignoring the initialization part. Unlike for this code:
```
class Program {
    void Main()
    {
        var x = new Test() { A = 1, B = 1 };
    }
}
```

the generated class is:
```

internal class Test
{
    public Test()
    {
    }

    public int A { get; set; }
    public int B { get; set; }
}
```

In fact, the two cases co-exist:
```
Test x = new Test() { A = 1, B = 1 };
```

Generating the class from `Test x` will not generate the fields, unlike generating it from `new Test()`.
I think the generator should look for an initializer at the right hand side.

**Comment by CyrusNajmabadi** [comment]
@VBAndCs that is a separate issue. I've extract it out to https://github.com/dotnet/roslyn/issues/58495.  Thanks.

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
My advice is to review how all code fixes act in top level code (or at least some variety of them). Maybe fixing this doesn't cover all potintial issues in this mode.

**Comment by CyrusNajmabadi** [comment]
@VBAndCs 

> My advice is to review how all code fixes act in top level code (or at least some variety of them). 

We would welcome such an effort.  If you're interested, i'm totally willing to work with you on this sort of thing.  Thanks!
