### ISSUE TITLE
TargetMethod.ReceiverType of an IInvocationOperation should be the constructed generic type

### ISSUE THREAD

**Issue by GianvitoDifilippo** [dotnet/roslyn#58497]
**Version Used**:

- Microsoft.CodeAnalysis.Common 4.0.1
- Microsoft.CodeAnalysis.CSharp 4.0.1

**Steps to Reproduce**:

1. Define a generic base class and a generic derived class. The generic class has a method which can be accessed from the derived class. The derived class invokes that method in one of its own methods.
```cs
namespace Test
{
    public class Base<T>
    {
        protected void Method() { }
    }

    public class Derived<T> : Base<T>
    {
        public Derived()
        {
            Method();
        }
    }
}
```
2. Set up a source generator and get the invocation operation from a constructed `Derived<T>` symbol, e.g., `Derived<string>`.
```cs
public void Execute(GeneratorExecutionContext context)
{
    INamedTypeSymbol stringType = context.Compilation.GetSpecialType(SpecialType.System_String);
    INamedTypeSymbol type = context.Compilation.GetTypeByMetadataName("Test.Derived`1").Construct(stringType);
    IMethodSymbol ctor = type.InstanceConstructors[0];
    IConstructorBodyOperation body = (IConstructorBodyOperation)context.Compilation
      .GetSemanticModel(type.DeclaringSyntaxReferences[0].SyntaxTree)
      .GetOperation(ctor.DeclaringSyntaxReferences[0].GetSyntax());
    IExpressionStatementOperation statement = (IExpressionStatementOperation)body.BlockBody.Operations[0];
    IInvocationOperation invocation = (IInvocationOperation)statement.Operation;
    ITypeSymbol receiverType = invocation.TargetMethod.ReceiverType;
}
```

**Expected Behavior**: `receiverType` is `Test.Base<string>`

**Actual Behavior**: `receiverType` is `Test.Base<T>`

Is this behavior by design?

**Comment by CyrusNajmabadi** [comment]
Yes. This is by design. You are going back to the syntax tree here:

> IConstructorBodyOperation body = (IConstructorBodyOperation)context.Compilation
> .GetSemanticModel(type.DeclaringSyntaxReferences[0].SyntaxTree)
> .GetOperation(ctor.DeclaringSyntaxReferences[0].GetSyntax());

So this is now analyzing the actual syntax, regardless of what instantiation you started with.
