### ISSUE TITLE
Compile-time and runtime conversion from double -> int producing different values

### ISSUE THREAD

**Issue by madelson** [dotnet/roslyn#58498]
**Version Used**: 

VS 17.0.2

**Steps to Reproduce**:

Run this code:
```C#
unchecked
{
	var d = double.PositiveInfinity;
	var i = (int)d;
	Console.WriteLine(i);
	var j = (int)double.PositiveInfinity;
	Console.WriteLine(j);
}
```

**Expected Behavior**:

Prints the same value for `i` and `j`, since both are the result of casting `double.PositiveInfinity` to `int`. 

**Actual Behavior**:

Prints
```
-2147483648
0
```

Apologies if this behavior is documented/explained somewhere.

**Comment by jaredpar** [comment]
These are two different operations:

```c#
var d = double.PositiveInfinity;
var i = (int)d;
``` 

The storage into `d` effectively removes the `const` nature of `double.PositiveInfinity`. That means at that point all of the conversion is done via .NET runtime intrinsics like `conv.i4`. 

```c#
var j = (int)double.PositiveInfinity;
```

This is handled as a constant operation in the compiler and how that is done is essentially unspecified. The conversion from `double` to `int` when there is infinity involved is undefined. From the C# spec 

> In an unchecked context, the conversion always succeeds, and proceeds as follows.
    > If the value of the operand is NaN or infinite, the result of the conversion is an unspecified value of the destination type.


@AlekseyTs, @cston in case they have anything else they want to add here

**Comment by AlekseyTs** [comment]
I have nothing to add here.
