### ISSUE TITLE
GetMemberModel for a field declaration with an initializer returns null

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/roslyn#58490]
**Version Used**: 
4.0.1

**Steps to Reproduce**:

Run the following program:

**The C# file:**
```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

var syntaxTree = CSharpSyntaxTree.ParseText("using System; class X { public DateTime m_now = DateTime.Now; }");
var compilation = CSharpCompilation.Create("temp",
    new[] { syntaxTree },
    new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
    new(OutputKind.DynamicallyLinkedLibrary));
var model = compilation.GetSemanticModel(syntaxTree);
var node = syntaxTree.GetCompilationUnitRoot().DescendantNodes().OfType<FieldDeclarationSyntax>().First();
Console.WriteLine(node.GetType().Name + " : " + node);
var op = model.GetOperation(node);
Console.WriteLine("op == " + (op?.ToString() ?? "null"));
```
**The project file:**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>
</Project>
```
**Expected Behavior**:

The output is expected to show something **different** than **op == null**

**Actual Behavior**:

Here is the actual output:
```
FieldDeclarationSyntax : public DateTime m_now = DateTime.Now;
op == null
```

It seems that there is a problem with the following code - https://github.com/dotnet/roslyn/blob/aeff02363e989ad9d9cbdd519d68f95e4eac5fcb/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L916

It invokes the function https://github.com/dotnet/roslyn/blob/aeff02363e989ad9d9cbdd519d68f95e4eac5fcb/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L1049-L1056
with parameters that would never satisfy the `if` condition.

So the question - is it supposed to work for a `FieldDeclarationSyntax` instance? The code looks like it is, but the function `GetOrAddModelIfContains` has botched the `if` condition.  It seems to me it should have been `span.Contains(node.FullSpan)` instead of `node.FullSpan.Contains(span)`.

**Workaround**

We cannot invoke `SemanticModel.GetOperation` on a field declaration. Instead we must drill down to the actual initializer and use it instead. Awkward and inconvenient, but doable.

**Comment by CyrusNajmabadi** [comment]
This feels normal to me.  tehre is no operation for a field.  Consider, for example:

```c#
private int x = some ... expr, y = other ... expr;
```

This is one fielddeclaration, but multiple different actual field symbols with different initializers (with operations for each of them).  :)

**Comment by MarkKharitonov** [comment]
@CyrusNajmabadi - you are correct, of course. But then, why does the function https://github.com/dotnet/roslyn/blob/aeff02363e989ad9d9cbdd519d68f95e4eac5fcb/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L839 has the following case in the first place:
https://github.com/dotnet/roslyn/blob/aeff02363e989ad9d9cbdd519d68f95e4eac5fcb/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L910-L923
?
What does it hope to achieve?

**Comment by CyrusNajmabadi** [comment]
As far as I can tell, it's exactly what I was saying above. If the span is within the initializer then it will find the binder for that specific initializer. If the span is outside the initializer then it won't work.

**Comment by MarkKharitonov** [comment]
I understand now. Thank you.

**Comment by CyrusNajmabadi** [comment]
You're welcome :)
