### ISSUE TITLE
Add direct test covereage for SymbolFinder

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#585]
Ported from TFS WorkItem: **975825**

---

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>Found during mobbing. 

&nbsp;

SymbolFinder.FindImplementationsAsync has no calls from test code. We should test it directly rather than rely on tests of consumers of this api.

---

**Revisions:**

1) Created By David Poeschl (6/27/2014 11:28:38 AM)

---

**Comment by lgolding** [comment]
After talking with Sri: sending this back to Jason and re-adding "Up for Grabs" label.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This functionality is tested thoroughly through many tests.  We don't need additional ones that duplicate what we already have.
