### ISSUE TITLE
Suggestion: Lower specific calls to String.StartsWith to faster code

### ISSUE THREAD

**Issue by thargol1** [dotnet/roslyn#58504]
I like `String.StartsWith()` because of it's readability and I want to keep in my code. Therefore I don't post this suggestion in the analyzer section.

Any call to String.StartsWith with a single constant character string en `StringComparison.Ordinal` can be lowered to code like this:
```csharp
// assume value is the string
// assume c is the first character of constant character string
ArgumentNullException.ThrowIfNull(value);
if (value.Length == 0) return false;
return value[0] == c;
```
I hooked this up in an extension method:
```csharp
public static bool StartsWithOrdinal(this string value, char c)
{
	ArgumentNullException.ThrowIfNull(value);
	if (value.Length == 0) return false;
	return value[0] == c;
}
```
and ran a benchmark:

```csharp
[Benchmark(Baseline = true)]
public bool Orginal()
{
	return TestValue.StartsWith("@", StringComparison.Ordinal);
}

[Benchmark]
public bool Modified()
{
	return TestValue.StartsWithOrdinal('@');
}
```

|      Method |      Mean |     Error |    StdDev | Ratio |
|------------ |----------:|----------:|----------:|------:|
| Orginal | 3.8787 ns | 0.1021 ns | 0.0852 ns | 1.000 |
|    Modified| 0.0391 ns | 0.0337 ns | 0.0375 ns | 0.009 |

(I did get a warning:  'The method duration is indistinguishable from the empty method duration')

This method can be used for multicharacter strings also, but at a given time you're generating to much code and lossing performance. 

An example for checking if a string starts with 'https://' in ordinal ignore case:
```csharp
// assume value is the string
ArgumentNullException.ThrowIfNull(value);
if (value.Length < 8) return false;
if (value[0] is not ('H' or 'h')) return false;
if (value[1] is not ('T' or 't')) return false;
if (value[2] is not ('T' or 't')) return false;
if (value[3] is not ('P' or 'p')) return false;
if (value[4] is not ('S' or 's')) return false;
if (value[5] is not ':') return false;
if (value[6] is not '/') return false;
if (value[7] is not '/') return false;
return true;
```
This is over 2 times faster than a regular call to `String.StartsWith("https://", StringComparison.OrdinalIgnoreCase)` but it also increases code size a lot. On the other hand the compiler has access to the internal working of the String object and could generate a much faster vector based comparison, like StartsWith uses internally.

**Comment by lsoft** [comment]
(`if (value.Length < 7) return false;` probably should be `if (value.Length < 8) return false;`)

**Comment by thargol1** [comment]
> (`if (value.Length < 7) return false;` probably should be `if (value.Length < 8) return false;`)
Code adjusted... thanx

**Comment by svick** [comment]
[`string.StartsWith(char)`](https://docs.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-6.0#System_String_StartsWith_System_Char_) is already ordinal, and [the implementation is basically what you want](https://github.com/dotnet/runtime/blob/46f5b99/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L1016)

**Comment by thargol1** [comment]
> [`string.StartsWith(char)`](https://docs.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-6.0#System_String_StartsWith_System_Char_) is already ordinal, and [the implementation is basically what you want](https://github.com/dotnet/runtime/blob/46f5b99/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L1016), so I don't think anything needs to be done about that case.

I'm a bit embarrassed I missed that overload.

Also my test was incorrect. `TestValue` was a constant string, so the compiler optimized it my code to just `return true`

I added a new test:
```csharp
[Benchmark]
public bool Orginal2()
{
	return TestValue.StartsWith('@');
}
```
and reran the test:

|   Method |      Mean |     Error |    StdDev | Ratio |
|--------- |----------:|----------:|----------:|------:|
|  Orginal | 3.2924 ns | 0.1012 ns | 0.1385 ns |  1.00 |
| Orginal2 | 0.2955 ns | 0.0225 ns | 0.0188 ns |  0.09 |
| Modified | 0.8199 ns | 0.0494 ns | 0.0462 ns |  0.25 |

I keep the issue open for opinions about the multi character strings. I found multiple references to two-character StartsWith calls in the Roslyn sourcecode, but I can't estimate the performance gain of optimizing those calls.

The Roslyn source code contains multiple references to String.Compare(single-character-string, StringComparison.Ordinal) e.g. in `src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/StringExtensions.cs` and `src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/Util/XmlRenamer.vb` perhaps someone can upgrade those to be a little bit faster.

**Comment by CyrusNajmabadi** [comment]
I'm not sure what's being asked for here.  However, when it comes to performance, we generally don't keep around speculative issues.  Either we have data indicating an issue, or things are fine.  This keeps the repo less cluttered (as we already have >5000 active issues).

Thanks!
