### ISSUE TITLE
Line-end errors overlap with the line content

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#58501]
**Version Used**: Version 17.1.0 Preview 1.1

**Steps to Reproduce**:

The error text is overlapping badly with the line content, with the experimental "Display diagnostics inline" feature turned on to "At the end of the line of code". Images speak 1000 words:

![image](https://user-images.githubusercontent.com/2371880/147438603-65958704-2281-4921-b0ff-ed039934aa66.png)

**Comment by CyrusNajmabadi** [comment]
I believe @akhera99 just fixed this. I think it had to do with multiline errors.

**Comment by akhera99** [comment]
Yes, should be fixed via #58398

**Comment by 333fred** [comment]
Excellent: closing out.
