### ISSUE TITLE
IDE0161 - #endif not retained [C#]

### ISSUE THREAD

**Issue by AlexanderMorou** [dotnet/roslyn#58510]
When using IDE0161 - `Convert to file-scoped namespace`, #endif may be omitted in the results.

```C#
namespace TestNamespace
{
#if DEBUG
    public class Test
    {
    }
#endif
}
```
Applying suggestion IDE0161 will result in the following output:
```C#
namespace TestNamespace;
#if DEBUG
public class Test
{
}
```

This results in CS#1027 - `#endif directive expected`

Tested in Visual Studio 2022 versions 17.0.0 and 17.0.4

**Comment by AlexanderMorou** [comment]
I didn't follow the exact guidelines on this because I assumed it's obvious that a suggestion should never create an compilation error when it is applied.

**Comment by CyrusNajmabadi** [comment]
This was fixed with: https://github.com/dotnet/roslyn/pull/58434

The new output is:

![image](https://user-images.githubusercontent.com/4564579/147531526-a9d39cca-66f7-4c86-9e3a-177b878966b0.png)

**Comment by AlexanderMorou** [comment]
Hey @CyrusNajmabadi, do you know roughly when that will be released?

I'm going to undo all files I've altered since IDE0161 was introduced because, if I'm reading #58434's commit notes right, the refactoring will no longer try to format the affected code (which isn't ideal).

**Comment by CyrusNajmabadi** [comment]
> Hey @CyrusNajmabadi, do you know roughly when that will be released?

@AlexanderMorou from teh linked issue the fix will be released in: 

![image](https://user-images.githubusercontent.com/4564579/147536034-ad3156f2-50ab-446b-bd3d-585be8182c3d.png)

**Comment by CyrusNajmabadi** [comment]
> (which isn't ideal).

Why is that not ideal?

**Comment by AlexanderMorou** [comment]
The behavior of formatting the code to remove the namespace indentation was not ideal. The rationale is there may be choices about how to format the code that may be lost due to the automatic formatting.

I'm saying I prefer that it will not format the code in 17.2.

**Comment by CyrusNajmabadi** [comment]
I see.  thanks!
