### ISSUE TITLE
CS8345 (ERR_FieldAutoPropCantBeByRefLike) wording can be misleading

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58513]
**Version Used**: 

main

**Steps to Reproduce**:

```csharp
using System;

public class C
{
    public Span<int> P { get; } = new int[] { 0, 1, 2, 3 };
}
```

> error CS8345: Field or auto-implemented property cannot be of type 'Span<int>' unless it is an instance member of a ref struct.

Auto property of type `Span<int>` **can** be an instance member of a class:

```csharp
using System;

public class C
{
    public Span<int> P => new int[] { 0, 1, 2, 3 };
}
```

**Expected Behavior**:

A more accurate error message indicating that an auto property of type `Span<int>` is allowed as an instance member of a class when it's an expression-bodied property.

**Actual Behavior**:

> error CS8345: Field or auto-implemented property cannot be of type 'Span<int>' unless it is an instance member of a ref struct.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi On the IDE side, can we special case this in `MakeRefStructCodeFixProvider`?

**Comment by svick** [comment]
I don't think that's an auto-property. [The documentation says:](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties)

> auto-implemented properties make property-declaration more concise when no additional logic is required in the property accessors. [...] When you declare a property as shown in the following example, the compiler creates a private, anonymous backing field that can only be accessed through the property's `get` and `set` accessors.

You do have logic in the (implicit) `get` accessor and there is no backing field, so this is not an auto-property.

[This is consistent with the (outdated) spec:](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#automatically-implemented-properties)

> An automatically implemented property (or auto-property for short), is a non-abstract non-extern property with semicolon-only accessor bodies.

**Comment by Youssef1313** [comment]
Yup it's definitely not an auto property. Can't stop laughing at what I wrote :rofl:
