### ISSUE TITLE
Namespace statement code fix converts tabs to spaces

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#58530]
**Version Used**: VS 17.1 Preview 3 (32028.93.main)

**Steps to Reproduce**:

1. Have a code file with a namespace and a type defined within it, with members. This file should use tabs for indentation. An .editorconfig should exist that tells the editor and language service to preserve those tabs.
2. At the end of the `namespace Foo` line (that uses braces), press `;`

**Expected Behavior**:

The code action that automatically removes the braces and unindents the namespace content should honor the .editorconfig setting by preserving tabs instead of converting them all to spaces.

**Actual Behavior**:

The automated code change replaces all tabs with spaces, as shown here.

![d300f1ba-ee09-443f-b12c-6d2d220ceed9](https://user-images.githubusercontent.com/3548/147716849-fede1997-4f0d-4c3a-84d2-df04db0b8ff5.gif)

The last frames show the spaces converted back to tabs as the result of the Format Document command.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/58434
