### ISSUE TITLE
Syntax highlight breaks down for generic method used as method group for a Delegate param

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#58538]
**Version Used**: VS2022 17.0.2

**Steps to Reproduce**:

1. Paste the following code:

```csharp
Bar(Foo<int>);

static void Foo<T>()
{
}

static void Bar(Delegate del)
{
}
```

**Expected Behavior**:

`Foo<int>` should be colored just any other methods.

**Actual Behavior**:

The syntax highlight for `Foo<int>` is broken. In particular, `Foo` is white, instead of yellow:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/10199417/147823345-595abe01-4d47-4ab2-8b28-6cfd91b99d95.png">

Note though how the IntelliSense popup does show up correctly when hovering over `Foo<int>`. Just colors are broken.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/153105306-1f763a71-3fa9-4152-ae6e-8562a48049ea.png)

**Comment by CyrusNajmabadi** [comment]
On: 

![image](https://user-images.githubusercontent.com/4564579/153105347-df31f55a-f75c-4c22-bbc8-f4bf6217e234.png)
