### ISSUE TITLE
[Feature Request] :Run roslyn in the browser so I can compile c# any where.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/roslyn#58532]
Then I can run it on mono too

**Comment by svick** [comment]
What is preventing you from running it in the browser now?

**Comment by Xyncgas** [comment]
.NET interactive is unavailable for the web, I want to do it myself, but mono can't run roslyn.

**Comment by Xyncgas** [comment]
It was a fun idea I had couple days ago that maybe I can replace javascript files with c# files on my webserver and see if it works, which it means letting users to create their own scripts in c# as the next step, then now they can visit a webapp and change how it works

**Comment by jaredpar** [comment]
Closing as this particular issue is a bit off topic. This repo is more concerned with the C# compiler and IDE experience. This more of a request for a different product
