### ISSUE TITLE
Generate a desktop application at runtime (codegeneration) fails in NET 6 / VS2022

### ISSUE THREAD

**Issue by vcarlucci** [dotnet/roslyn#58540]
**Version Used**: 
VS2022 Version 17.1.0 Preview 1.1
Language: C#

**Steps to Reproduce**:

Abstract: I have to compile from a string which contains some code at runtime to a new generated console application .exe. When I try to compile the code to a output type of class library, all works. But when I define the output kind to console application it will casuse issues in the final generated .exe

1. Prerequisites:
    -For example a wpf or console application to import and execute the class posted below mentioned in pt 2
    -I installed following nuget packages:
        > Basic.Reference.Assemblies
        > Microsoft.CodeAnalysis.Common
        > Microsoft.CodeAnalysis.CSharp
    
1. Simple class example to generate code from a string, in this example all options set to generate a console application
_(Note, when I generate with this class a class library, all works fine)_

``` c#
using Basic.Reference.Assemblies;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace CompilerSimplified
{
    public static class Compiler
    {
        public static bool Start()
        {
            string FileName = "AppCodegenerated";
            string ExePath = AppDomain.CurrentDomain.BaseDirectory + @"\" + FileName + ".exe";
            string code = @"using System; Console.WriteLine(""Hello.""); Console.ReadLine(); ";


            // ------- References -------------
            // .net platform references
            List<MetadataReference> References = new List<MetadataReference>();
            foreach (var item in ReferenceAssemblies.Net60) // ReferenceAssemblies from Nuget: Basic.Reference.Assemblies;
                References.Add(item);

            // or tried this: loop manually through system platform 
            //string[] fileEntries = Directory.GetFiles(@"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0\", "*.dll");
            //foreach (string fileName in fileEntries)
            //    references.Add(MetadataReference.CreateFromFile(fileName));MetadataReference.CreateFromFile(fileName));
            // ------- References END -------------



            // delete existing file
            if (File.Exists(ExePath))
                File.Delete(ExePath);

            // compiler options
            CSharpCompilationOptions DefaultCompilationOptions =
                new CSharpCompilationOptions(outputKind: OutputKind.ConsoleApplication, platform: Platform.AnyCpu)
                .WithOverflowChecks(true).WithOptimizationLevel(OptimizationLevel.Release);

            // encode soucre code
            string sourceCode = SourceText.From(code, Encoding.UTF8).ToString();

            // CSharp options
            var parsedSyntaxTree = Parse(sourceCode, "", CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp10));

            // compilation
            var compilation = CSharpCompilation.Create(FileName, new SyntaxTree[] { parsedSyntaxTree }, references: References, DefaultCompilationOptions);
            var result = compilation.Emit(ExePath);

            // return
            if (result.Success)
                return true;
            else
                return false;
        }

        private static SyntaxTree Parse(string text, string filename = "", CSharpParseOptions options = null)
        {
            var stringText = SourceText.From(text, Encoding.UTF8);
            return SyntaxFactory.ParseSyntaxTree(stringText, options, filename);
        }

    }
}
```

2. The code gets compiled without any errors and the executable file is stored in /bin folder

**Expected Behavior**:
Start of the codegenerated console application .exe (bin/AppCodegenerated.exe) should start and display "Hello."

**Actual Behavior**:
Start of the codegenerated console application .exe (bin/AppCodegenerated.exe) opens the console, but shows following exception in the console:

`Unhandled exception: System.IO.FileNotFoundException: 
The file or assembly "System.Runtime, Version = 6.0.0.0, Culture = neutral, 
PublicKeyToken = b03f5f7f11d50a3a" or a dependency on it was not found. 
The system can not find the stated file.`

*Not sure if I am in the right project region here, if not please move to the correct one. Thank you!

**Comment by jaredpar** [comment]
> Simple class example to generate code from a string, in this example all options set to generate a console application

In this particular case though, because you are using the `Net60` reference set, you are generating a .NET Core application. Those cannot be generated as a pure IL exe like a .NET Framework application can. Instead the usual setup is you: 

1. Generate the exe as a .DLL say app.dll 
2. Then you either `dotnet exec app.dll` or you generate an apphost file which is a piece of native code which loads the .NET runtime and then it loads app.dll and begins execution. 

When generating applications for .NET Core you need to take that into consideration. You simply can't generate a pure EXE using the C# compiler here.

**Comment by vcarlucci** [comment]
@jaredpar Thanks for the good answer. Your second point with the dll which could then be executed via an exe I have already thought, but have hoped that this can be solved somehow more elegant. But it seems I have to go this way. 

Maybe this is a future improvement feature worth, also because you can select the output kind "DesktopApplicaton" and there would be in my opinion quite a few use cases for this.

Thank you for the support
