### ISSUE TITLE
Revisit FileTextLoaderOptions.FileLengthThreshold

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#58553]
VS is now 64-bit. Do we still need this option, or can we just use the default 100MB? 

If so it should be passed explicitly to `FileTextLoader` constructor instead of read from `Workspace.Options`.

**Comment by tmat** [comment]
@jasonmalinowski @sharwell @CyrusNajmabadi

**Comment by jasonmalinowski** [comment]
I think the point of this behavior was to deal with people who accidentally added gigantic files as additional files without realizing what they did and tanking perf in the process. Or folks who did intentionally add a gigabyte of files as additional files without realizing what they were doing. (We told them to stop it.)

Do we have any telemetry for whether this is still being tripped in practice? If not, I'd propose add it, wait for a bit to see if anybody actually hits it. If nobody does, just rip this out entirely. If we are seeing this get hit, see if we can figure out why, or perhaps do a better design. It might be easy to add a "we are loading a really huge file" warning too to the error list to make people aware they're doing odd things...

**Comment by tmat** [comment]
If we add telemetry how long should we wait for the data before we can make changes?

I lean towards keeping the 100MB limit, but not having it be configurable. I don't see a scenario where opening >100MB source file would be desirable. With VS being 64-bit we should be able to handle files smaller then 100MB (not OOM), so I don't really see motivation for customers to change this setting in registry.

**Comment by CyrusNajmabadi** [comment]
I'm with tomas on this.  We've never once documented this or had anyone ask to change this stuff.  I'm ok with the value as a safeguard against pathological stuff.  I don't really see a need for it to be configurable.
