### ISSUE TITLE
x[^0..^0] should throw

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#58563]
**Version Used**: 
VS2022 Community 17.0.4

**Steps to Reproduce**:
```C#
int[] x = { 1, 2, 3, 4, 5, 6, 7 };
var y = x[^0..^0]; 
var z = x[^1..^1];
```

**Expected Behavior**:
Throw exceptions.

**Actual Behavior**:
y and z are empty arrays like what happens when using:
```C#
int[] x = { 1, 2, 3, 4, 5, 6, 7 };
var y = x[7..6];
var z = x[6..5];
```

This behavior is inconsistent.

In fact, I think C# should give compile time errors about wrong literal ranges.

**Comment by CyrusNajmabadi** [comment]
THose literal ranges are correct.  They are both empty ranges at legal positions in the array.  There's no reason to throw here.

**Comment by CyrusNajmabadi** [comment]
For: 

```c#
int[] x = { 1, 2, 3, 4, 5, 6, 7 };
var y = x[^0..^0]; 
```

This means get teh subrange in the selection above (indicated with `[|...|]`):

```c#
int[] x = { 1, 2, 3, 4, 5, 6, 7 [| |] };
```

This is an empty selection at a legal position in the list.  So you get an empty array back. For `var y = x[^1..^1];` That is equivalent to:

 ```c#
int[] x = { 1, 2, 3, 4, 5, 6 [| |], 7 };
```

Again, a legal empty range.

**Comment by CyrusNajmabadi** [comment]
For:

```c#
var y = x[7..6];
var z = x[6..5];
```

Neither of these are legal ranges.  In both cases the 'start' comes after the 'end'.   The equivalent to:

```c#
var y = x[^0..^0]; 
var z = x[^1..^1];
```

Using `from start` indices would be:

```c#
var y = x[7..7]; 
var z = x[6..6];
```

Both of these are legal and produce the same results as the `from end` indices.

**Comment by HaloFour** [comment]
Comparison with Python:

```python
>>> list = [ 1, 2, 3, 4, 5, 6, 7 ]
>>> list[-1:-1]
[]
```

**Comment by VBAndCs** [comment]
Isn't ^0 means x.Length - 1?
At the start is inclusive, and at the end is exclusive, so it should be equivalent to [6, 5]?
What I am missing here?

**Comment by VBAndCs** [comment]
And how can I get the same empty array with normal range (without using ^)?

**Comment by CyrusNajmabadi** [comment]
> Isn't ^0 means x.Length - 1?

No.  It means `0, from end`.

**Comment by CyrusNajmabadi** [comment]
> At the start is inclusive, and at the end is exclusive, so it should be equivalent to [6, 5]?

It is.  See the picture i drew.  It's Inclusive on the start point, and exclusive at the end point.  Causing an empty result.

**Comment by CyrusNajmabadi** [comment]
> At the start is inclusive, and at the end is exclusive, so it should be equivalent to [6, 5]?

I showed in https://github.com/dotnet/roslyn/issues/58563#issuecomment-1004215799

Your code is equivalent to:

![image](https://user-images.githubusercontent.com/4564579/147958132-b99e6743-d7c2-4272-ad28-215207e50595.png)

**Comment by VBAndCs** [comment]
OK. The behavior is consistent, but I still can't understand it! These range rules are insane! This can't make the code easier by any means!

**Comment by CyrusNajmabadi** [comment]
> but I still can't understand it! 

What don't you understand?

> These range rules are insane!

They are very clear and work well.  Tons of APIs have been updated to them and they're easy to use effectively.

>  This can't make the code easier by any means!

Demonstratively false :)
