### ISSUE TITLE
Add null check quick action adds one-liner

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58571]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-null-check-quick-action-adds-one-lin/1618674)._

---
[regression] [worked-in:Not sure - at least in September 2020...]
Previously (at least on September 2020) I was able to [tweak the _Add null check_ Quick Action](https://blog.ploeh.dk/2020/09/07/add-null-check-without-brackets-in-visual-studio) so that it'd produce code like this:

```
if (create is null)
    throw new ArgumentNullException(nameof(create));
```

Now (VS 16.11.8) VS instead adds a one-liner:

```
if (create is null) throw new ArgumentNullException(nameof(create));
```

This means that I'll now have to manually edit the generated code after VS creates it, because I want it on two lines. This sort of defeats the purpose of a Quick Action.

How do I make it generate the code in two lines, _without brackets?_

---
#### Feedback Bot on 12/21/2021, 01:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is controlled by the following option:

![image](https://user-images.githubusercontent.com/4564579/153105206-675feb7b-ff94-4423-9a1d-800adfad22b9.png)

If you have this set to true, then we'll put this on a single line.  To disallow it, set it to false.
