### ISSUE TITLE
Member access inside object creation inserts unwanted parentheses

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58574]
**Version Used**: VS 17.1 Preview 1.1
C# Tools 4.1.0-1.21551.6+e4419d6f6792da7011c8589ba118f59d830ca72f (commit e4419d6f6792da7011c8589ba118f59d830ca72f)

**Steps to Reproduce**:

1. Paste the following code into VS:
```cs
var outer = new $$;

public class Outer
{
    private Outer() { }

    public class Inner
    {
        public Inner() { }
    }
}
```

2. Delete the $$ and at that position type `Outer.Inner`.

**Expected Behavior**: `Outer.Inner` inserted in the editor.

**Actual Behavior**: `Outer().Inner` is inserted in the editor, which includes unwanted parens.

"Real world" scenario recording:
![nested-class-bug](https://user-images.githubusercontent.com/5833655/147979413-40920f06-f840-4aad-8346-06060071243c.gif)

**Comment by Youssef1313** [comment]
I think this was already reported, but can't find the issue.

**Comment by Youssef1313** [comment]
The feature responsible for this is:

https://github.com/dotnet/roslyn/blob/c885d0cd1ed4c674d55fa5964a2f44e1615baf9c/src/Features/CSharp/Portable/Completion/CompletionProviders/ObjectCreationCompletionProvider.cs#L136-L145

There is a `SymbolCompletionItem.GetSymbolsAsync(CompletionItem, Document, CancellationToken)` method which can be used to tweak whether we add `()` or not.

**Comment by RikkiGibson** [comment]
@Cosifne do you know if the behavior described in this issue is by design?

**Comment by Cosifne** [comment]
@RikkiGibson 
Looks like a dup of this issue? https://github.com/dotnet/roslyn/issues/51629
