### ISSUE TITLE
Does .NET still support CSI?

### ISSUE THREAD

**Issue by Keithcat1** [dotnet/roslyn#58588]
CSI is a C# REPL that was supported in older versions of .NET I believe. However, when I run "csi /version" I get 3.11.0-4.21403.6 () which looks like it's not using the preview version of .NET 6 I have installed on my computer. Could some form of CSI be added, possibly to the dotnet command? Being able to rapidly test code snippets makes learning C# easier for me and is something I do in Python all the time.

**Comment by tmat** [comment]
It is included with msbuild: E.g. `C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\csi.exe`

**Comment by Keithcat1** [comment]
Okay found it. Had to install Visual Studio build tools 2022, didn't quite know that was a thing.

**Comment by ahdung** [comment]
So how to specify dotnet version in csi?

**Comment by kvlanger** [comment]
If you are on linux and have the dotnet cli you have to install csi tool:

```bash
dotnet tool install --global dotnet-csi --version 1.1.9
```

and add this to your PATH

`export PATH=$PATH:~/.dotnet/tools`

restart your terminal and you can do `dotnet-csi foo.csx`

or

`dotnet csi foo.csx`

or just `dotnet csi`
