### ISSUE TITLE
Null-forgiving operator (!) does not work if it is used before an actual warning

### ISSUE THREAD

**Issue by datvm** [dotnet/roslyn#58603]
**Version Used**: VS 2022 17.0.3

**Steps to Reproduce**:

Discussion on [this StackOverflow question](https://stackoverflow.com/questions/70305430/why-does-null-forgiving-operator-does-not-work-for-parameter) may be useful.

Consider the following xUnit Test or any library that does not have nullable annotation yet (this is the most popular and annoying case I have):

```c#
public class UnitTest1
{

    [Fact]
    public async Task Test1()
    {
        var result = await this.FindAsync();

        Assert.NotNull(result); // Line 1
        Assert.Equal(3, result.Length); // Line 2: Null warning here
        Assert.Equal("yes", result.ToLower()); // Line 3
    }

    // I use async to demonstrate a shortcoming of workaround
    async Task<string?> FindAsync()
    {
        return await Task.FromResult("Yes");
    }

}
```

As xUnit does not have `[NotNull]` annotations yet, the compiler does not know `result` cannot be `null` from there onwards. However if I mark it as "not null" at line 1, it does not work:

```c#
        Assert.NotNull(result!); // Tooltip says "result" is not null here
        Assert.Equal(3, result.Length); // But here it says "result" may be null
```

One answer on that question gives another scenario:

```c#
object? o = null;
o!.ToString();
o.ToString(); // no warning
```

```c#
object? o = null;
object j = o!;
o.ToString(); // warning
```

**Expected Behavior**:

There should be no warning afterwards if a variable is marked with null-forgiving operator.

**Actual Behavior**:

Null-forgiving operator (!) should mark a variable as not null from where it's used onwards.

**Comment by Youssef1313** [comment]
Until someone from the compiler team confirms whether this is an issue or not, a better approach I suggest is to add your own annotated `Assert` class (call it `AssertEx` for example), and let it just wrap xUnit's methods. That way all your null suppressions are in this one place.

**Comment by jaredpar** [comment]
There is a bit of discussion about this decision here 

https://github.com/dotnet/csharplang/discussions/4102#discussioncomment-128346

Effectively arguments to methods have input state but not output state. The call to the method does not change the state of the argument here hence neither does the `!` operator. Only operations which are likely to result in a direct NRE change the state (member access in particular).

> Until someone from the compiler team confirms whether this is an issue or not, a better approach I suggest is to add your own annotated Assert class (call it AssertEx for example), a

That is exactly what we do in our own code base
