### ISSUE TITLE
Incremental source generators do not recover from an exception

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58625]
**Version Used**: 4.1.0-1.21551.6 (e4419d6f)

**Steps to Reproduce**:

1. Define an incremental source generator that throws an exception for incomplete code
2. Use the incremental source generator while writing code

**Expected Behavior**:

* The source generator produces a diagnostic in the error list when the erroneous state is encountered (covered by #54098).
* The source generator resumes producing working code (via non-incremental update) when the erroneous state is exited.

**Actual Behavior**:

The source generator latches in a non-working state, as reported by #58523.

**Comment by jaredpar** [comment]
@chsienki fyi

**Comment by sharwell** [comment]
🎉
