### ISSUE TITLE
Roslyn analyzer suggestion to convert a switch statement to switch expression alters runtime code behavior

### ISSUE THREAD

**Issue by rotemdan** [dotnet/roslyn#58636]
**Version Used**: 
`.NET 6.0.0`

**Steps to Reproduce**:
```cs
var s = "a";
object result;

switch (s) // Analyzer suggestion: "Use 'switch' expression"
{
	case "a":
		result = (int) 1234;
		break;
	case "b":
		result = 3.14;
		break;
	default:
		throw new Exception("");
};

Console.WriteLine(result.GetType().Name); // Prints "Int32"!
```
When applying the fix. The following code is produced:
```cs
var s = "a";

object result = s switch
{
	"a" => (int) 1234,
	"b" => 3.14,
	_ => throw new Exception(""),
};

Console.WriteLine(result.GetType().Name); // Prints "Double"!
```
**Expected Behavior**:
The fix should not alter runtime behavior of the code, or the suggestion shouldn't be given at all.

**Actual Behavior**:
The analyzer suggestion changes the runtime behavior of the conditional, it produces an object containing a value of type `Double` instead of `Int32`.

I [have reported](https://github.com/dotnet/roslyn/issues/58634) the unnecessary implicit coercion of `Int32` (as well as `Int64`, which is a lossy cast to `Double`) before it is assigned to an `object` target as a compiler bug, but it was immediately dismissed as "By Design". Based on the fact that this "fix" is erroneously suggested by the analyzer as a "lossless" equivalent, I doubt it was intended. However, there's not much I can do except to report it.

**Comment by CyrusNajmabadi** [comment]
Yup. Definitely an issue. When converting this we need to insert preserving cats to the original type.

**Comment by rotemdan** [comment]
@CyrusNajmabadi

The issue is even more serious when a case specifies a `long` value, now the "fix" modifies the assigned value, not just the type:
```cs
var s = "a";

object result = s switch
{
	"a" => 12341234123412341L,
	"b" => 3.14,
	_ => throw new Exception(""),
};

Console.WriteLine(Convert.ToInt64(result)); // Prints "12341234123412340"!
```
The conversion from `long` to `double`, and then back to `long` effectively changed the value from `12341234123412341` to `12341234123412340` due to limits of the numeric precision of `Double`.

Casting back and forth wouldn't work here. You'd have to prevent the analyzer suggestion altogether, or change the language spec to stop making senseless casts for no reason.

**Comment by CyrusNajmabadi** [comment]
@rotemdan Yup. Definitely an issue. When converting this we need to insert preserving cats to the original type.

> Casting back and forth wouldn't work here. You'd have to prevent the analyzer suggestion altogether, 

I don't see why that's the case.  We can just add the appropriate `object` cast in the arms to preserve things. :)

**Comment by CyrusNajmabadi** [comment]
@rotemdan Thanks for the issue report.  I've created a fix that we should be able to get into a subsequent visual studio release.  We really appreciate you catching this and bringing it to our attention!

**Comment by rotemdan** [comment]
> @rotemdan Yup. Definitely an issue. When converting this we need to insert preserving cats to the original type.
> 
> > Casting back and forth wouldn't work here. You'd have to prevent the analyzer suggestion altogether,
> 
> I don't see why that's the case. We can just add the appropriate `object` cast in the arms to preserve things. :)

Yes, for some reason I didn't come across the simple workaround of casting the case expression to `object`. Maybe because this wouldn't have been easy to do if the intention was the result to be interpreted as a union type, since inferring the type of the inner expression would be essential to infer the resulting union:

```cs
var x = c switch // imagine x was is inferred as int | dobule
{
  "a" => 1234 // If I cast this to some other type then the union type may have been inferred incorrectly
  "b" => 3.14
};
```
But since `object` is just one variant type, it's trivial to cast to it directly.
