### ISSUE TITLE
C#: erroneus CS8618 warning with partial class when definition is in one file and initialization in another

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58640]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-erroneus-CS8618-warning-with-partial/1607780)._

---
Hello,
Here is a class separated in 2 files (simple example, to show the problem).

File 1:

```
namespace ClassLibrary1;
public partial class Class1
{
  public static readonly String Value1;

  static Class1 ()
  {
    Value1 = String.Empty;
    Value2 = String.Empty;
  }
}

```
File 2:
```
namespace ClassLibrary1;
public partial class Class1
{
  public static readonly String Value2;
}
```

Even if `Value2` is initialized in the class constructor, VS shows a warning CS8618 for its value:
![image.png](https://aka.ms/dc/image?name=Bcd0a69eb721d44b5844474b2e55e6850637745438840339038_20211208-080443-image.png&tid=cd0a69eb721d44b5844474b2e55e6850637745438840339038)

Test case: 
[ClassLibrary1.zip](https://aka.ms/dc/file?name=B96a7561178354927a4ded74ba920ba1c637745440101166497_ClassLibrary1.zip&tid=96a7561178354927a4ded74ba920ba1c637745440101166497)

---
#### Feedback Bot on 12/8/2021, 00:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/9/2021, 10:51 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
@RikkiGibson The issue description mentions:

> Even if Value2 is initialized in the class constructor, VS shows a warning CS8618 for its value:

I assume "class constructor" is referring to instance constructor. Was this fixed or tested?

**Comment by RikkiGibson** [comment]
Initializing a static field from an instance constructor is not expected to suppress the warning. I don't recall if we have a test for it already, but if we don't, it would be good to add one.

**Comment by Youssef1313** [comment]
@RikkiGibson Yeah makes sense. Consider also testing a non-static field then.

**Comment by RikkiGibson** [comment]
> Consider also testing a non-static field then (it's working already, so doesn't matter a lot).

I think it's a good idea to ensure the test exists.

I did find it interesting how it complicates the desire some have expressed to always report CS8618 on the declaration--if the flow analysis which determines the warning is necessary occurs in a separate file, how is GetDiagnosticsForSyntaxTree supposed to work 🙂. Most likely we will just get #58096 ready to merge and call it good.

**Comment by Patrick8639** [comment]
> @RikkiGibson The issue description mentions:
> 
> > Even if Value2 is initialized in the class constructor, VS shows a warning CS8618 for its value:
> 
> I assume "class constructor" is referring to instance constructor. Was this fixed or tested?

No, it references the static constructor.
