### ISSUE TITLE
ClassifierHelper's AdjustSpans method occasionally generates an empty span

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#58658]
Occasionally `AdjustSpans` in `ClassifierHelper` seems to be generating an empty span, which is unnecessary.
Repro can be found using a Razor generated file.
Nothing explicitly breaks at the moment due to this, but we should likely investigate the cause nonetheless.

Link: https://github.com/dotnet/roslyn/blob/2bcf519cfa869f29bc56385b07cb752f49c80f77/src/Workspaces/Core/Portable/Classification/ClassifierHelper.cs#L127

![image](https://user-images.githubusercontent.com/16968319/148311977-71a6ba75-6b6b-4f8e-aad6-a13aee4d4f60.png)

**Comment by ryanbrandenburg** [comment]
This should be solved by #58955.
