### ISSUE TITLE
__arglist should not be allowed to have a default value

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58672]
Expected to be resolved by #58644

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQMwAIECYUGEUG8CwAUCiWqggCwoCyAFAPr0QBOA5gDZQDOALigLwoYAV3bsAlHiKkUAXyKygA)

```cs
public class C {
    public void M(__arglist = null) { // should error, but doesn't currently
    }
}
```

Related to https://github.com/dotnet/roslyn/pull/58644#discussion_r779204478

**Comment by jaredpar** [comment]
It looks like #58644 is merged now so can this be closed?

**Comment by RikkiGibson** [comment]
Yes.
