### ISSUE TITLE
Change target framework without Navigation bar

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58679]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Change-target-framework-without-Navigati/1599336)._

---
Currently the only way to change target framework for editor, is to use Navigation bar and select from dropdown.

![B61ffbe0eb8f14dcd8c2cdc0705620f07637738736077447536_img](https://user-images.githubusercontent.com/1408396/149427999-d6a9c687-58dd-4939-a557-ee9ae71a60cc.png)

When one does not use the Navigation bar (like myself), there's no other way to switch. Other way - i.e. menu - would be helpful.

---
#### Feedback Bot on 11/30/2021, 06:25 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

#### Kendra Havens [MSFT] on 12/9/2021, 01:53 PM: 

<p>Thanks for taking the time to file feedback! Where were you envisioning this menu might be? Just out of curiosity, is there something in the navigation bar that blocks or discourages you from using it? Is setting the target framework from the Project properties page also not a good option for you?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Jiri Cincura on 12/10/2021, 00:52 AM: 

<p>In the <em>Edit</em> menu as a submenu would be fine for me. I think it’s not that common people heavily multi-target libraries.</p>
<p>Regarding the Navigation bar. It’s taking up space and I didn’t get used to using it for navigating in code - usually I know what I’m looking for or I just Ctrl-F it.</p>
<p>Project properties is setting target for the project, but I’m here talking about the editor and what’s/how/when is highlighted when editing code (in multi-targeted library).</p>

#### Kendra Havens [MSFT] on 12/10/2021, 01:06 PM: 

<p>Thanks for the extra info!</p>

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
