### ISSUE TITLE
File-Scoped Namespace should always have a fix all option available 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#58673]
A user should always have an option to apply a fix all for this code style to their code base.

**Comment by Youssef1313** [comment]
Possibly duplicate of https://github.com/dotnet/roslyn/issues/32461.

**Comment by CyrusNajmabadi** [comment]
I disagree.  Say you have set "file scoped namespaces are an error".  Then i don't think a fix-all should be available.

We have discussed refactorings having fix-alls when appropriate (which @Youssef1313 has linked to).  This should fall under this bucket IMO.   We should just do that work, and then have this be part of the fallout.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to happen, then we should assign a dev/milestone.
