### ISSUE TITLE
Visual Studio should suggest private extension methods to be made public

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58686]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-should-suggest-private-ext/1619050)._

---
Suppose I have a `private` extension method called `MyExtension(this object o)...`

Suppose I call `myObject.MyExtension()`.

Suppose that produces a compile error (No method named `MyExtension` available).

Then Visual Studio should suggest that `MyExtension` be made `public` rather than `private`.

---
#### Feedback Bot on 12/21/2021, 06:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jinujoseph** [comment]
Related #10337, #16632,

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
