### ISSUE TITLE
region should have different background color 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58689]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/region-should-have-different-background-/1617085)._

---
Hi

every region should have different background color so one can focus on them
.........................
Thanks

---
#### Feedback Bot on 12/19/2021, 07:17 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
