### ISSUE TITLE
[UI] Indent incompatible types in CS0029 error popup in a way they can differ easier

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UI-Indent-incompatible-types-in-CS0029/1609560)._

---
Now:

![B43e95f904899461a97a4fb05d62efcc3637746602576060981_20211209-162417-grafik](https://user-images.githubusercontent.com/1408396/149426711-3cb14ed8-57e7-4f67-9198-217d5ec7b166.png)

Better:

![B8f203fa63f4140a18cecee06bb96a65e637746604835099203_20211209-162803-grafik](https://user-images.githubusercontent.com/1408396/149426723-ac6653b3-a41f-4949-b160-4a0e7ba6d1a9.png)

---
#### Feedback Bot on 12/9/2021, 11:40 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
Moving to compiler.  This relates to formatting of a particular diagnostic string.
