### ISSUE TITLE
Quick Actions and Refactorings should allow user to add a new extension method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Actions-and-Refactorings-should-al/1618324)._

---
I've written some extension methods for Selenium.

When I type:

`webElement.MethodThatDoesNotExist(123)`

And `MethodThatDoesNotExist` is not a valid method, 

Then I should be prompted with a choice to create an extension method named `MethodThatDoesNotExist` with an `int` parameter.

There's details to work out. Here are some suggestions:

If there's only one project in the solution,
and there's only one static class, 
then the extension method should be added to that class.

If there's only one project in the solution,
and there's multiple static classes, 
then the user should be able to choose which static class to add the extension method to.

The type of the extension method should also be a choice from: 
the type of `webElement`, 
any of its base classes,
and any of any of those classes' interfaces 
(or whatever makes sense).

Once the user chooses a type for the extension method (i.e. a type for the `this` parameter of the extension message), 
then, if there are multiple static classes and only one of them has an extension method for that type, 
then prompt that static class (i.e. keep extension methods with the same type for their `this` parameter in the same file).

---
#### Feedback Bot on 12/20/2021, 11:13 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback and complexity of design.
