### ISSUE TITLE
code formatting: align on equal sign, after comma... 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58680]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/code-formatting:-align-on-equal-sign-af/1614709)._

---
regarding code formatting it'll be nice to get some fragments displayed as a kind of table

what I wanted from VS is (assuming the fragment below is in monospace)

```
                tm = {
                        .tm_sec   = static_cast<int>(second),
                        .tm_min   = static_cast<int>(minute),
                        .tm_hour  = static_cast<int>(hour),
                        .tm_mday  = static_cast<int>(day),
                        .tm_mon   = static_cast<int>(month - 1),
                        .tm_year  = static_cast<int>(year - 1900),
                        .tm_isdst = 1
                };

```
instead I get this one

```
                tm = {
                        .tm_sec = static_cast<int>(second),
                        .tm_min = static_cast<int>(minute),
                        .tm_hour = static_cast<int>(hour),
                        .tm_mday = static_cast<int>(day),
                        .tm_mon = static_cast<int>(month - 1),
                        .tm_year = static_cast<int>(year - 1900),
                        .tm_isdst = 1
                };
```

I'm tired waisting my limited mental capabilities on parsing text files,

My proposal would be:
If activated in editor options and and the trigger character (maybe '=',  list configurable) is preceded by TAB then all consecutive lines should be displayed (not formatted) as aligned to the trigger char. (a tabular way)
Blank line terminates display group

Another candidates could be trigger followed by TAB for example comma separated lists noted down as a table

---
#### Feedback Bot on 12/15/2021, 09:47 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
This is not C#, this is C++.  I'll reactive the original issue on vsfeedback.
