### ISSUE TITLE
foreach should prompt "{ }" for autocomplete

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58685]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/foreach-should-prompt---for-autocomp/1619053)._

---
If I type this:
```
var array = new [] {1,2,3};
foreach(var i in array)
```
Visual Studio should prompt an autocomplete an empty `foreach` body with brackets:
```
var array = new [] {1,2,3};
foreach(var i in array)
{
    // cursor goes here after autocomplete
}
```
I should only have to press "tab" for that to happen. I should not have to type: "enter" "{" "enter" "}" "upArrow" "enter"

---
#### Feedback Bot on 12/21/2021, 06:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
You should just be able to write `{` then `<enter>`.

**Comment by Youssef1313** [comment]
You can also hit <kbd>Shift</kbd>+<kbd>Enter</kbd>. The advantage of this is that it works whether your cursor is before or after the closing parenthesis.

![shift_enter](https://user-images.githubusercontent.com/31348972/148509238-681984ea-cfb4-4f02-8a5c-3fa4937a3c12.gif)


An even better alternative is to not write `foreach(....)`, but only type `foreach` then hit double tab, and use tab after that to navigate to parts you want to type in.

![tab_tab_snippet](https://user-images.githubusercontent.com/31348972/148509251-e866d494-d186-420c-ae94-3022a7e447b0.gif)

Given there are enough easy ways to type this fast, I don't think there is anything Roslyn needs to do here.

**Comment by CyrusNajmabadi** [comment]
Agreed. There are ample features already to help here
