### ISSUE TITLE
Find All References is not rendering correctly

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#58693]
**Version Used**: Version 17.1.0 Preview 3.0 [32104.457.main]

**Steps to Reproduce**:

1. Create a new test project
2. Reference a method from another method, and find-all-refs on the referenced method.

**Expected Behavior**:

The find-all-references window renders the references correctly.

**Actual Behavior**:

Rendering is incorrect. Here are some examples of what I'm seeing.

Duplicated words:
![image](https://user-images.githubusercontent.com/2371880/148468555-a686c95a-0273-457e-aadb-d6a2dcd76969.png)

Missing Punctuation:
![image](https://user-images.githubusercontent.com/2371880/148468645-aa9a6d04-3bfa-4eea-ae68-dc21dd62abca.png)

Duplicated Puncutation:
![image](https://user-images.githubusercontent.com/2371880/148468669-745b1183-5d0e-4f40-8359-bccc9bb35f25.png)

**Comment by CyrusNajmabadi** [comment]
@allisonchou possibly due to some of your changes to the classification helpers?

**Comment by allisonchou** [comment]
Yep, this was caused by my change - fix is pending M2 insertion: https://github.com/dotnet/roslyn/pull/58620

**Comment by 333fred** [comment]
Thanks! I'll close this out then.
