### ISSUE TITLE
Proposal: Allow null coalescing operator for pointers

### ISSUE THREAD

**Issue by jacekbe** [dotnet/roslyn#5869]
I realize that pointers in C# are not the most widely used construct but they exist and it would be nice if null coalescing operator worked for pointer types as well so we could write:
`T *p1 = p2 ?? p3;`
instead of:
`T *p1 = p2 != null ? p2 : p3;`

**Comment by aluanhaddad** [comment]
This makes sense.

**Comment by gafter** [comment]
This issue was moved to dotnet/csharplang#323
