### ISSUE TITLE
Some optimizations about queries.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58692]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/一些关于查询的优化。。。。。。。。。。。。。。。。。。/1620848)._

---
! [image.png] (https://aka.ms/dc/image?name=Bc18a5abb29fc4c38a27ba9da64932bb8637758438063129698_20211223-161006-image.png&tid=c18a5abb29fc4c38a27ba9da64932bb8637758438063129698)
It is recommended to refer to the idea, which can see the approximate position of the variable reference on its scroll bar. I moved the scroll bar directly to the approximate position to see some of the code in which the variables were referenced

---
#### Feedback Bot on 12/24/2021, 01:44 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by jaredpar** [comment]
closing as the issue has little info and the vs feedback link is broken

**Comment by CyrusNajmabadi** [comment]
I think the request is on the ide. Specifically, when the caret is in a symbol, and we're highlighting references in the doc, also show markers in the scroll bar showing where those references are. That way you can navigate quickly to them. 

Seems like a reasonably idea. However we also have a key binding to let you easily jump through the references as well. @jasonmalinowski do you remember what the key binding is?

**Comment by jasonmalinowski** [comment]
The keys are Ctrl+Shift+Up and Ctrl+Shift+Down.
