### ISSUE TITLE
navigation drop-downs in C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58691]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/navigation-drop-downs-in-C/1614656)._

---
Read my words very slowly.... you are getting sleepy.... very, very, sleepy.  When you wake up, you will add the following to the C# editing environment:

Please add Controls to the middle navigation drop-down and filter available events in the third drop-down navigation box... you know... similar to what you offered in the VB.NET environment.  You will make many people happy... and you do want to make many people happy, don't you?!

SNAP!

---
#### Feedback Bot on 12/15/2021, 09:47 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
We could potentially take a PR for this.  VB is very different though in that the *declaration* specifies that it "handles" some event.  In C#, you need code generated somewhere to do the actual event hookup.  We could find common patterns seen in things likw WinForms/WPF/etc.
