### ISSUE TITLE
Add FAR test coverage for UI rendering

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#58706]
There seems to be a test gap for Find All References in which we aren't testing the UI output. This has resulted in bugs such as https://github.com/dotnet/roslyn/issues/58693:

![image](https://user-images.githubusercontent.com/16968319/148496413-5d92c2d8-0672-4563-87dd-d417312436e1.png)

We should add tests to ensure potential bugs are caught ASAP.

**Comment by allisonchou** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
