### ISSUE TITLE
IDE0044 or CS0266 - sbyte assignment via ternary operator and integer literal leaves you with no choice

### ISSUE THREAD

**Issue by Jens-G** [dotnet/roslyn#58709]
**Version Used**: 

VisualStudio.17.Release/17.0.4+32014.148

**Steps to Reproduce**:

```
protected sbyte ExtractInt8(object data)
{
	return (data is sbyte value) ? value : (sbyte)0;   // IDE0044 redundant cast
	return (data is sbyte value) ? value : 0;          // CS0266 no implicit cast from int to sbyte
}

```
**Expected Behavior**:

The cast is indeed necessary here. So the IDE0044 looks wrong to me.

**Actual Behavior**:

See code. Both versions produce some issue. There is no right answer.

**Possible Workaround**:

```
protected sbyte AsInt8(object data)
{
            const sbyte ZERO = 0;  // prevents IDE0004 (redundant cast) 
            return (data is sbyte value) ? value : ZERO; 
}

```

**Comment by Youssef1313** [comment]
That's an IDE0044 bug. cc @CyrusNajmabadi

**Comment by Youssef1313** [comment]
This is likely already fixed. Can't reproduce in SharpLab:

![image](https://user-images.githubusercontent.com/31348972/148539458-40307574-415a-4ad5-baf3-4470312e1eb5.png)

**Comment by Jens-G** [comment]
Great, I wait for  17.1 becomes a stable version then. Thanks guys!
