### ISSUE TITLE
A possible easy solution to not build docs-only changes on CI

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58710]
This doesn't change yaml files, only changes on dev.azure.com.

![image](https://user-images.githubusercontent.com/31348972/148548589-043384fc-49ae-4ba6-94dc-bda67772f97d.png)

I'm not sure if this will work as intended, but I tested on a small repo, and it seems to work?

![image](https://user-images.githubusercontent.com/31348972/148548987-91f56516-41c2-4cc7-8cd5-7930642dc16b.png)

The check is required and it's not showing the "Use your administrator privileges to merge this pull request without waiting for requirements to be met." message.

@jaredpar Would you be able to test this and see if it works?

**Comment by Youssef1313** [comment]
If the suggestion didn't work, you can close the issue. But I'm a bit optimistic per the small try I done.

**Comment by Youssef1313** [comment]
Hmm, I re-tested with adding `paths` `exclude` in yml and I see the same result. It's possible that GitHub behavior has changed for the good.

**Comment by jaredpar** [comment]
In general you cannot use excludes in our CI system. The reason is that many of our checks are required and GitHub interprets that as "required to pass". If you have an excluded file, make a change and submit a PR then the checks do not run at all. That is not considered passing hence the PR is red

**Comment by Youssef1313** [comment]
I'm aware of that (this was the reason of https://github.com/dotnet/roslyn/pull/46590), but when I re-tested on a small repo I've, I no longer see this behavior. The PR is showing the required checks as "skipped", and at the same time it's allowing me to merge. Without ticking a "Use your administrator privileges to merge this pull request without waiting for requirements to be met." checkbox.

What I'm suggesting is to give it a try. Hopefully, it could work. If it didn't, we can revert and close this issue.

**Comment by jaredpar** [comment]
Yeah something seems to have changed here. Your one PR is not hitting the problem where skipped checks failing because they are required. GitHub now seems to consider skipped runs as satisfying required parameters. That would be a welcome change but hard to see if they did that intentionally

**Comment by Youssef1313** [comment]
> That would be a welcome change but hard to see if they did that intentionally

I "hope" they did it intentionally. Either way I think it's worth to give a try and see if everything works fine.

If in future the behavior has changed again, we can revert too.

**Comment by RikkiGibson** [comment]
I recreated branch https://github.com/dotnet/roslyn/tree/features/dont-build-docs-changes.

You can try merging your work to that branch, then open a follow-up PR with a doc-only change and see if CI does the thing we want.

**Comment by Youssef1313** [comment]
@RikkiGibson Thanks. That's a cleaner way of testing instead of testing on `main`. I rebased https://github.com/dotnet/roslyn/pull/58712.

**Comment by RikkiGibson** [comment]
Looks like we are ready to test out the follow-up PR.

**Comment by Youssef1313** [comment]
@RikkiGibson Yeah. The PR is here: https://github.com/dotnet/roslyn/pull/58716
