### ISSUE TITLE
Many compiler tests are flaky under Linux Environment

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#58719]
Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=1540087&view=results

Runfo Tracking Issue: [uselibvariablevb](https://runfo.azurewebsites.net/tracking/issue/244)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1541610](https://dev.azure.com/dnceng/public/_build/results?buildId=1541610)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541609](https://dev.azure.com/dnceng/public/_build/results?buildId=1541609)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541430](https://dev.azure.com/dnceng/public/_build/results?buildId=1541430)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541384](https://dev.azure.com/dnceng/public/_build/results?buildId=1541384)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541293](https://dev.azure.com/dnceng/public/_build/results?buildId=1541293)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541253](https://dev.azure.com/dnceng/public/_build/results?buildId=1541253)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1541025](https://dev.azure.com/dnceng/public/_build/results?buildId=1541025)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|[PR 57969](https://github.com/dotnet/roslyn/pull/57969)|Test Linux Debug Single Machine|
|[1540629](https://dev.azure.com/dnceng/public/_build/results?buildId=1540629)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540628](https://dev.azure.com/dnceng/public/_build/results?buildId=1540628)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540619](https://dev.azure.com/dnceng/public/_build/results?buildId=1540619)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540618](https://dev.azure.com/dnceng/public/_build/results?buildId=1540618)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540617](https://dev.azure.com/dnceng/public/_build/results?buildId=1540617)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540616](https://dev.azure.com/dnceng/public/_build/results?buildId=1540616)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540614](https://dev.azure.com/dnceng/public/_build/results?buildId=1540614)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540570](https://dev.azure.com/dnceng/public/_build/results?buildId=1540570)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540510](https://dev.azure.com/dnceng/public/_build/results?buildId=1540510)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540363](https://dev.azure.com/dnceng/public/_build/results?buildId=1540363)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540354](https://dev.azure.com/dnceng/public/_build/results?buildId=1540354)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540308](https://dev.azure.com/dnceng/public/_build/results?buildId=1540308)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540308](https://dev.azure.com/dnceng/public/_build/results?buildId=1540308)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540308](https://dev.azure.com/dnceng/public/_build/results?buildId=1540308)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540308](https://dev.azure.com/dnceng/public/_build/results?buildId=1540308)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540308](https://dev.azure.com/dnceng/public/_build/results?buildId=1540308)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540294](https://dev.azure.com/dnceng/public/_build/results?buildId=1540294)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540166](https://dev.azure.com/dnceng/public/_build/results?buildId=1540166)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540166](https://dev.azure.com/dnceng/public/_build/results?buildId=1540166)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540166](https://dev.azure.com/dnceng/public/_build/results?buildId=1540166)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540166](https://dev.azure.com/dnceng/public/_build/results?buildId=1540166)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|
|[1540087](https://dev.azure.com/dnceng/public/_build/results?buildId=1540087)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Linux Debug Single Machine|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|22|22|

**Comment by Cosifne** [comment]
I linked one tests in Runfo here (but actually there are totally about 150 tests failing)

**Comment by MattGal** [comment]
Pretty sure this is/was https://github.com/dotnet/core-eng/issues/15292, caused by the 1ES team's agent inserting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` into the environment.  Should be resolved now, please let dnceng know if not.

**Comment by Cosifne** [comment]
Closed because the dotnet/core-eng side bug is resolved
