### ISSUE TITLE
list pattern with conjunctive and pattern 

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#58738]
**Version Used**: 
Visual Studio Version 17.1.0 Preview 2.0
C# Tools   4.1.0-2.21607.5+4e139d3fdfc73247aece2e29d7abcecd0d4f6464

**Steps to Reproduce**:

```cs
var a = new[] { 1 };

// OK
if (a is [var y] && y is 1)
{
}

// CS0029 Cannot implicitly convert type 'int' to 'int[]'
if (a is [var x] and x is 1)
{
}
```

**Expected Behavior**:

No error.

**Actual Behavior**:

CS0029 on line 9 col 22.

Moreover, compiling the following code falls into infinite loop.

```cs
var a = new[] { 1 };

if (a is [var x] and x is [1])
{
}
```

**Comment by alrz** [comment]
>Moreover, compiling the following code falls into infinite loop.



I couldn't repro an infinite loop but there's a missing case in https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs#L1038

>if (a is [var x] and x is 1)

That's not valid code - you can't use pattern variables inside patterns. You probably want `a is [1]`.
