### ISSUE TITLE
Has this kind of optimazation been done?

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/roslyn#58749]
### Discussed in https://github.com/dotnet/roslyn/discussions/58739

<div type='discussions-op-text'>

<sup>Originally posted by **Xyncgas** January  9, 2022</sup>
```
public void _Function (A arg1 = default, B arg2 = default, C arg3 = default){}
```

gets optimized :

```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private void _Function_ (A arg1 = default, B arg2 = default, C arg3 = default){}
public void _Function(A arg1) =>_Function_ (arg1);
public void _Function(B arg2) =>_Function_ (arg2:arg2);
public void _Function(C arg3) =>_Function_ (arg3:arg3);
...Continues
```
</div>

**Comment by CyrusNajmabadi** [comment]
I don't understand what this is asking for. It looks to be something you could potentially accomplish with a source generator though. I'm going to close this out until now information is provided.

**Comment by Xyncgas** [comment]
I am wondering if this optimization has been done before by the compiler.
Because if roslyn isn't doing this I might do it myself.
The purpose for this is creating many function overloads instead of overloading on one single function with default parameters therefore reducing the datas that needs to be passed in each called especially if you are scaling on this function and since default parameters are provided in the private function being inlined they will be defined at compile time.
If you were to tell me, of course, that this is a terrible idea I might agree with you.
let's say if passing parameters to a function is just as efficient as having those parameters declared and defined in the function body already :
A :
```
void A (int a=0){}
```
B:
```
void B () {int a =0;}
```
A vs B

**Comment by CyrusNajmabadi** [comment]
> If you were to tell me, of course, that this is a terrible idea I might agree with you.

1. Is there any data to indicate that this is beneficial?
2. I would not this this should be done at the compiler level.  Perhaps the JIT level.

**Comment by Xyncgas** [comment]
1. It looks beautiful.
2. I am wondering if this has been done, I am not asking for it to be

**Comment by CyrusNajmabadi** [comment]
@Xyncgas no. The compiler does not do this. 

You could potentially do it with a source generator though. Though it seems highly unlikely to be worth it.

**Comment by Xyncgas** [comment]
Thanks for the information. And of course, I think might not actually be any better than passing in parameters even with they are value types because I think since it is a parameter with default values it could totally be 0 copy
