### ISSUE TITLE
Visual Studio does not suggest changing the language version to preview when using generic attributes.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/roslyn#58742]
**Version Used**: Visual Studio 2022 17.0.4

**Steps to Reproduce**:

Create a new project and paste the following code:

``` csharp
using System;

[assembly: Test<int>]

class TestAttribute<T> : Attribute
{

}
```

**Expected Behavior**:

Visual Studio would display error CS8652 and suggest to set the language version to `preview`.

**Actual Behavior**:

Visual Studio does display the error but doesn't offer to fix the language version. Since we can't change it visually from the Properties page, we have to directly edit the project file.

**Comment by RikkiGibson** [comment]
It seems we are issuing the error `CS8652 The feature 'generic attributes' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.` but for some reason the fixer is not lighting up.

![image](https://user-images.githubusercontent.com/5833655/148853485-90e9feb8-8c1f-4c32-ad53-1d5095b20980.png)

**Comment by sharwell** [comment]
I thought we stopped offering the language version code fix?

**Comment by RikkiGibson** [comment]
If that is the case, it seems like the behavior in the issue description is by-design.

**Comment by sharwell** [comment]
Looks like support for CS8652 was added in https://github.com/dotnet/roslyn/pull/33089.

**Comment by sharwell** [comment]
Ah, we suppress the code fix if the new language version is greater than `MaxSupportedLangVersion`, which it will always be less than `preview`.
