### ISSUE TITLE
C# refactor "Create and assign property" does not add appropriate white spaces around the assignment operator '='

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58750]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-refactor-Create-and-assign-property/1629807)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Visual Studio 2019]
As you can see in the screenshot bellow, it does not wrap the assignment operator with appropriate white spaces.
Expected: 

```
this. Nombre = nombre;
```
Actual:

```
this. Nombre=nombre;
```

! [image.png] (https://aka.ms/dc/image?name=B741df7c486964538a8f46e8ca0187f83637770056796436455_20220105-155439-image.png&tid=741df7c486964538a8f46e8ca0187f83637770056796436455)

---
#### Feedback Bot on 1/5/2022, 06:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I do not repro this at all.  Appropraite spacing is added here.  Would need more customer info to resolve this.

**Comment by Narvalex** [comment]
@CyrusNajmabadi What info do you need?

**Comment by CyrusNajmabadi** [comment]
@Narvalex a repro case where this happens :)

**Comment by Narvalex** [comment]
@CyrusNajmabadi In the following link you can see a video of the errror repro. Hope this helps
https://gicaldev-my.sharepoint.com/:v:/g/personal/alexis_gicaldev_com_py/EVKBeQWiGExHq6ysB1Sn4XUBfJpTQdoNcnc0S1ch8Rz9yQ?e=wMLkeH

**Comment by CyrusNajmabadi** [comment]
That doesn't seem to match what the bug report said, which is that you get:

```c#
this. Nombre=nombre;
```

I don't see any space after `this. ` in your video.  

In terms of the spacing around the `=`.  What values do you have in your editorconfig or VS settings?  What is your value here:

![image](https://user-images.githubusercontent.com/4564579/168150936-a3270481-88e3-4e51-be48-e4bf27fbeb5a.png)


![image](https://user-images.githubusercontent.com/4564579/168150919-c22a3c18-0dd4-4913-96d9-474adcf7a5b6.png)

**Comment by Narvalex** [comment]
Oh no... my bad! You are right, that was it!. I'm so sorry for opening this issue. Thanks @CyrusNajmabadi for your help!

**Comment by CyrusNajmabadi** [comment]
You're welcome!

**Comment by JohannSig** [comment]
What I don't understand how this spacing setting changed from my VS 2019 to when I installed VS 2022. Is ignoring spaces around binary operators the default behavior?

**Comment by Narvalex** [comment]
> What I don't understand how this spacing setting changed from my VS 2019 to when I installed VS 2022. Is ignoring spaces around binary operators the default behavior?

That is exactly what happened to me. I wonder why
