### ISSUE TITLE
Double click to select string results in selection outside of string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58774]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Double-click-to-select-string-results-in/1618589)._

---
I have this line in my code: `Console.WriteLine("==============");`.

If I double click on one of the = signs, it ends up selecting `("==============");` instead of selecting the contents of the string `==============`

---
#### Feedback Bot on 12/21/2021, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/3/2022, 10:35 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/3/2022, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/10/2022, 09:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This appears to be behaving by design. A separate command (**Edit &rarr; Advanced &rarr; Expand Selection**) is available for a more semantic-aware selection expansion operation, where double-click is more a Select Word operation.

**Comment by CyrusNajmabadi** [comment]
Design conclusion:

This feature already works by falling back to using the editors 'word matching' algorithm when inside a string.

1. We should preserve that fallback.  
2. However, we should clamp the results the editor produces so that they only go up to the insides of the quotes in a strings.
3. When doing this, make sure `double-click and drag` still continues to work.
