### ISSUE TITLE
Peek Definition fails on 'new' operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58775]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Peek-Definition-fails-on-new-operator/1628606)._

---
[severity:It's more difficult to complete my work]
C#, VS 2022 latest version.

I have a file MyFoo.cs. I close it in the editor (if it was loaded)

I have an instantiation of the class MyFoo in another file:

var myFoo = new MyFoo();

I right-click on the 'new' operator and choose: Peek Definition

It opens the peek window at the start of the file containing class MyFoo.

I then open MyFoo.cs in the editor.

I retry the right-click on the 'new' operator.

This time it opens the peek window correctly at the constructor for MyFoo.

---
#### Feedback Bot on 1/4/2022, 07:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/10/2022, 09:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I was not able to reproduce this in 17.1 Preview 3.

**Comment by jinujoseph** [comment]
needs steps to reproduce
