### ISSUE TITLE
Internal interfaces in "Metadata as Source" aren't classified properly

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#5878]
If you open MAS for (eg) `ImmutableList<T>`, the base interfaces `IOrderedCollection<T>, IImmutableListQueries<T>, IStrongEnumerable<T, ImmutableList<T>.Enumerator>` (which are all internal) are classified as Identifier rather than User Types - Interface.

**Comment by SLaks** [comment]
In Quick Info, they are highlighted as interfaces.

**Comment by SLaks** [comment]
Internal interfaces in base type lists for nested types don't have Quick Info at all (but their generic parameters do)

**Comment by CyrusNajmabadi** [comment]
The problem is likely that binding these types actually fails in the generated source code.  Might be difficult to get this working.  But worth at least taking a look into.

**Comment by SLaks** [comment]
Then why does F12 work everywhere?
Isn't that powered by the same binding?

**Comment by SLaks** [comment]
BTW, this also happens for internal types in other places.
The only other example I've found so far of an internal type appearing in metadata is attribute parameters (especially `DebuggerTypeProxy`).
There, quick info also fails, but F12 still works.

**Comment by Pilchie** [comment]
We deliberately check for accessibility errors in Go to definition, in case the user wants to go there and change the accessibility. I don't think it would be right to successfully classify them though.

**Comment by CyrusNajmabadi** [comment]
> I don't think it would be right to successfully classify them though

I don't know if I agree.  Or, at least, I don't agree for MAS.  The generated code is clearly correct.  And we should be classifying properly.  

Now, for non-MAS scenarios, I also think it's fine to still classify.  I mean, we understand what you're saying, and you're going to get a perfectly good squiggle telling you there's something wrong.  Falling back to 'identifier' makes it often really feel like the IDE doesn't know what's going on, and I think it would be nice to avoid that.

**Comment by SLaks** [comment]
+1, especially for MAS.

Alternatively, you could make MAS bind as if it were within that project, so it wouldn't be an error in the first place (I don't know how easy that would be...)

**Comment by CyrusNajmabadi** [comment]
> Alternatively, you could make MAS bind as if it were within that project, so it wouldn't be an error in the first place (I don't know how easy that would be...)

"within that project" is a tough concept.  Remember that we're synthesizing source code, but then binding it attached to the original DLL (so it knows about all the symbols from that dll).  You have a mix of source and metadata, and the compiler already has built in logic for how resolution should work there.

That said, I think there may be ways to address this.  For example, when we ask for a semantic model, we can ask to ```ignoreAccessibility```.  i.e. ```public SemanticModel GetSemanticModel(SyntaxTree syntaxTree, bool ignoreAccessibility)```.    We should consider doing this for classification for MAS files.

**Comment by diryboy** [comment]
MAS is metadata in the first place, source code is just a representation, so every element it binds to should be reflected by the "color".

That's a different story from the source you're currently authoring, if something doesn't "color" as expected, you can do a Go To Definition to find out why, and decide whether change the accessibility for the referenced element, or not reference it at all.

**Comment by CyrusNajmabadi** [comment]
I see the following, which looks correct:

![image](https://user-images.githubusercontent.com/4564579/198713864-73531257-d397-4271-a20f-c82b1b11b639.png)

We aren't showing the interfaces we don't know about.
