### ISSUE TITLE
Linq expression evaluated as nullable reference 

### ISSUE THREAD

**Issue by bhatiarohan01** [dotnet/roslyn#58787]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.4

**Steps to Reproduce**:

1. if (!RenderClassType.GetProperties().Any(n => n.GetCustomAttributes().Where(m => m is IObviateComponent).**Any(o => o != null && (o as IObviateComponent**).LayoutIdentifier.CompareLayoutIdentifier(LayoutIdentifier))))
                
2.  The bolded part above will have warning dereference of possible null, even though the null check should not let this happen. Moreover, converting the (O as IObviateComponent) to explicit cast (IObviateComponent)o resolve the issue.

**Expected Behavior**:
No warning for deference of possible null value
**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
Correct.  `as` is always treated as a potentially `null` introducing construct (as that's the point of it) :)

In other words, we unilaterally assume that you wrote that in particular because you felt it could be null.

If null is not possible, you can instead write:

```c#
.Any(o => o != null && ((IObviateComponent)o).LayoutIdentifier.CompareLayoutIdentifier(LayoutIdentifier))))
```

**Comment by CyrusNajmabadi** [comment]
Note: the compiler is implementing the spec properly here.  If you'd like teh spec to change, you should open a *Discussion* over at github.com/dotnet/csharplang so that the problem can be discussed and properly triaged there. Thanks!
