### ISSUE TITLE
Task list not working with VB.Net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58780]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Task-list-not-working-with-VBNet/1630738)._

---
[severity:It's more difficult to complete my work]
The task list in Visual Studio Professional 2019 Version 16.11.8 is not displaying any tasks from VB.Net source code.  The task list appears to work correctly with C# code, but not with VB.Net code.

---
#### Feedback Bot on 1/6/2022, 08:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/10/2022, 10:02 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I'm able to reproduce this in 17.1 only when OOP is disabled. I suspect this option is disabled (unchecked) in 16.11 for the user who reported this:

![image](https://user-images.githubusercontent.com/1408396/149020392-6ac43b94-5f86-4478-822d-4119d7dddb90.png)
