### ISSUE TITLE
[Responsiveness] Roslyn package load is causing MEF initialization on UI thread (80ms on opening solution)

### ISSUE THREAD

**Issue by Erarndt** [dotnet/roslyn#58795]
Build: 32110.19.main
Test: Speedometer TestSolutionOpenClose-PerfMetrics

![image](https://user-images.githubusercontent.com/60519722/149040868-8f56f600-36c6-47b5-827f-1aa27e7b175e.png)

It seems like this could be resolved by switching to a background thread in two places:

Before this call [here](https://github.com/dotnet/roslyn/blob/785ce8c99a625f8b672d62c1da6e6a637f942e5e/src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage.cs#:~:text=await%20LoadComponentsAsync(cancellationToken).ConfigureAwait(false)%3B):

and inside this call [here](https://github.com/dotnet/roslyn/blob/a9cdf7f0091ce8f0abecdd78eea693fb9043330b/src/VisualStudio/Core/Def/RoslynPackage.cs#L190)

**Comment by sharwell** [comment]
Was this already fixed by #58351?

**Comment by CyrusNajmabadi** [comment]
This is a complaint about the cost of doing color schemes.  Giving to Joey to see if he knows of ways to get this off the UI thread.

**Comment by davkean** [comment]
This is more than InitializeColors, this is retrieving MEF components on the UI thread causing dll loads & other MEF overhead. This can be off thread and then switched back to the UI thread when init actually needs to occur to talk to VS STA APIs.

From what it looks like by code inspect, this code path is expecting to be called off the UI thread, but its not, its being inlined.

**Comment by CyrusNajmabadi** [comment]
Related to: https://github.com/dotnet/roslyn/issues/15148

**Comment by davkean** [comment]
The first case can be resolved by changing:

``` C#

        protected async Task LoadComponentsInUIContextOnceSolutionFullyLoadedAsync(CancellationToken cancellationToken)
        {
            // UIContexts can be "zombied" if UIContexts aren't supported because we're in a command line build or in other scenarios.
            // Trying to await them will throw.
            if (!KnownUIContexts.SolutionExistsAndFullyLoadedContext.IsZombie)
            {
                await KnownUIContexts.SolutionExistsAndFullyLoadedContext;
                await LoadComponentsAsync(cancellationToken).ConfigureAwait(false);
            }
        }
```

To:

``` C#
        protected async Task LoadComponentsInUIContextOnceSolutionFullyLoadedAsync(CancellationToken cancellationToken)
        {
            // UIContexts can be "zombied" if UIContexts aren't supported because we're in a command line build or in other scenarios.
            // Trying to await them will throw.
            if (!KnownUIContexts.SolutionExistsAndFullyLoadedContext.IsZombie)
            {
                await KnownUIContexts.SolutionExistsAndFullyLoadedContext;
                await TaskSceduler.Default;
                await LoadComponentsAsync(cancellationToken).ConfigureAwait(false);
            }
        }
```

The second case, can be resolved by change InitializeColors from (ColorSchemeApplier constructor looks free-threaded):

``` C#
        private void InitializeColors()
        {
            // Initialize ColorScheme support
            _colorSchemeApplier = ComponentModel.GetService<ColorSchemeApplier>();
            _colorSchemeApplier.Initialize();
        }
```

to:

``` C#
        private Task InitializeColorsAsync()
        {
            // Initialize ColorScheme support
           await TaskScheduler.Default;

            _colorSchemeApplier = ComponentModel.GetService<ColorSchemeApplier>();

            await JoinableTaskFactory.SwitchToMainThreadAsync();
            _colorSchemeApplier.Initialize();
        }

```

**Comment by sharwell** [comment]
I'm not a fan of this:

```
                await TaskSceduler.Default;
                await LoadComponentsAsync(cancellationToken).ConfigureAwait(false);
```

Rather than ensure the async method is _called_ on the correct thread, it can itself await `TaskScheduler.Default` at the start of its implementation.

**Comment by sharwell** [comment]
You'll want documentation for the thread switching as well. Here's an example from the same file:

https://github.com/dotnet/roslyn/blob/259a9e27ab8c6a1d8d3a3445b079fd5e3a13ec0a/src/VisualStudio/Core/Def/RoslynPackage.cs#L178-L180

**Comment by davkean** [comment]
> Rather than ensure the async method is called on the correct thread, it can itself await TaskScheduler.Default at the start of its implementation.

Extension points should start on a background thread, it shouldn't be up to each extension point to first switch off the UI thread.

**Comment by sharwell** [comment]
@davkean There is no practical way to audit the code base to ensure this applies with any level of consistency. As a result:

* If the method starts with an explicit context switch, it can be assumed that the implementation is on that context
* If the method does not start with an explicit context switch, it _cannot_ be assumed that the implementation is on that context

This leaves us with the option of either including a switch in both the caller and the callee, or just the callee. But having a call only in the caller is a silent/undocumented call site restriction with no analyzer enforcement or maintainability expectation.

**Comment by CyrusNajmabadi** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/60205 and https://github.com/dotnet/roslyn/pull/60211.  Closing out for now.  If we see other codepaths adding to UI thread delays we can address those separately.
