### ISSUE TITLE
Formatting operations not added to the undo stack separate from committed completion entry

### ISSUE THREAD

**Issue by danquirk** [dotnet/roslyn#588]
Formatting operations used to (in VS2013) get their own place in the undo stack following completion behavior. In VS2015 this is no longer the case. Examples:

2013:
![formattingundostackvs2013](https://cloud.githubusercontent.com/assets/7121557/6234988/d59842f6-b693-11e4-8824-65d5c3b9872a.gif)
2015:
![formattingundostackvs2015](https://cloud.githubusercontent.com/assets/7121557/6234993/da07440e-b693-11e4-968e-c88c9439ff71.gif)

This is a sequence of typing

1. doo
2. semicolon
3. undo
4. undo
5. redo
6. redo

TypeScript appears to have inherited this new Roslyn behavior: https://github.com/Microsoft/TypeScript/issues/1930

**Comment by rchande** [comment]
Fixed with number #2372

**Comment by rchande** [comment]
@danquirk can verify that this is fixed and then close the issue and add the "verified" tag?

**Comment by Pilchie** [comment]
Let's close this, since we believe it is fixed.
