### ISSUE TITLE
`OrganizeImportsTests` involving non-English characters are failing locally.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58834]
**Version Used**: 

main

**Steps to Reproduce**:

Run `Build.cmd -testCoreClr` locally.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/31348972/149326881-7b16a7ea-7a34-4d7d-99d2-0b17451bcc98.png)

**Expected Behavior**:

No test failure. The code path for comparing appears to be using `InvariantCulture`, which per [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-6.0):

> invariant culture data is stable over time and across installed cultures and cannot be customized by users. This makes the invariant culture particularly useful for operations that require culture-independent results, such as formatting and parsing operations that persist formatted data, or sorting and ordering operations that require that data be displayed in a fixed order regardless of culture.

[StackOverflow question](https://stackoverflow.com/questions/25727349/culture-invariant-case-sensitive-string-comparison-returns-different-results-on) around this area for reference.

The comparison, per my understanding, happens in:

https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TokenComparer.cs

https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Utilities/TokenComparer.vb

**Comment by Cosifne** [comment]
I play with this [test](https://github.com/dotnet/roslyn/blob/3294cefa6ed212369759695ce16945909f2ac5fe/src/Workspaces/CSharpTest/OrganizeImports/OrganizeUsingsTests.cs#L1091) and the key problem is the comparing of three Japanese characters.
The test is assuming ア < ｱ < あ
I don't know Japanese but from my testing, the current comparison result is
Enable Kana + Ignore Width : あ = ｱ < ア 

And I can't find a combination to let あ be the largest.
If enable Kana then あ <ア, diable Kana then あ = ア
If with Width then あ < ｱ, ignore width then あ = ｱ

**Comment by CyrusNajmabadi** [comment]
@dtivel I believe you wrote these test cases like 15 years ago right :)   Any recollection on the concerns here?

**Comment by dtivel** [comment]
I don't remember anything about this test.  What does test history look like?  Has the test been flaky for the past 15 years or did it suddenly start failing now?

**Comment by CyrusNajmabadi** [comment]
> I don't remember anything about this test. What does test history look like? 

This predates roslyn by like 10+ years :D  it was back when i added "sort imports" back in the wee VS2005 days and we worked on it together :)

**Comment by Cosifne** [comment]
> I don't remember anything about this test. What does test history look like? Has the test been flaky for the past 15 years or did it suddenly start failing now?

It's been reported to fail since Jan. But I am not sure it is starting to fail since which commit.
I feel it would be good to review the test to see if it still makes sense after 10 years.
If yes, we could talk to some cultural experts to see how to achieve it

**Comment by RikkiGibson** [comment]
It's possible that #57365 introduced the failure during local runs. It is probably related to a different runtime being used when running coreclr tests in CI versus locally.

**Comment by Cosifne** [comment]
Fixed in this PR:
https://github.com/dotnet/roslyn/pull/63853
