### ISSUE TITLE
"display inline parameter name hints" shortcut not working when "Display all hints while pressing Alt+F1" is checked

### ISSUE THREAD

**Issue by luisfco** [dotnet/roslyn#58839]
The shortcut Alt+F1 does nothing.

Tested in:
VS2019  v16.11.9
VS 2022  v17.0.4
VB and CS files

Also it would be nice if the shortcut could be customized.

Thanks

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Do you have the geforce tools installed?  They hijack this shortcut as well.
