### ISSUE TITLE
Test plan for Utf8StringLiterals feature.

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#58848]
Speclet - https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/utf8-string-literals.md
Feature branch - https://github.com/dotnet/roslyn/tree/features/Utf8StringLiterals
Championed issue - https://github.com/dotnet/csharplang/issues/184

## Compiler
- [x] LangVer
  - [x] for `u8` suffix
- [x] compiler test plan
- [x] parsing
  - [x] `u8` and `U8` suffix allowed
  - [x] no trivia between string constant and `u8` suffix
  - [x] single and multi-line verbatim strings
  - [x] single and multi-line raw string literals
  - [x] interpolated strings with suffix disallowed
  - [x] disallowed in `#` directives
- [x] natural type of `"abc"u8` is `ReadOnlySpan<byte>`: `NaturalType_01`
- [x] no target type of constant string with `u8` suffix to `byte[]` or `Span<byte>`: `ImplicitConversions_02`
- [x] explicit conversion from constant string with `u8` suffix to `Span<byte>`, or `byte[]` is disallowed: `ExplicitConversions_02`
- [x] implicit/explicit conversion from constant string to `ReadOnlySpan<byte>`, `Span<byte>`, or `byte[]` is disallowed: `ImplicitConversions_01`
- [x] implicit/explicit conversion from non-constant string to `ReadOnlySpan<byte>`, `Span<byte>`, or `byte[]` is disallowed: `NoConversionFromNonConstant_01`, `_02`
- [x] implicit/explicit conversion from `null` to `ReadOnlySpan<byte>`, `Span<byte>`, or `byte[]` is allowed (unchanged): `NoBehaviorChangeForConversionFromNullLiteral_01`
- [x] implicit/explicit conversion from `(object)null` to `ReadOnlySpan<byte>`, `Span<byte>`, or `byte[]` is disallowed: `ImplicitConversions_04`, `ExplicitConversions_04`
- [x] implicit/explicit conversion from `(string)null` to `ReadOnlySpan<byte>`, `Span<byte>`, or `byte[]` is disallowed: `ImplicitConversions_03`, `ExplicitConversions_03`
- [x] error reported for invalid UTF8 in `u8` string: `InvalidContent_02`, `_03`
- [x] pattern matching `ReadOnlySpan<byte>` against string constants: `PatternMatching_01`, `_02`, `_03`
- [x] Expression tree use or implicit conversion and `u8` literal disallowed
- [x] UTF8 `byte[]` stored in `<PrivateImplementationDetails>` if Length > 2
- [x] pattern matching `ReadOnlySpan<byte>` against string constants: `PatternMatching_01`, `_02`, `_03`
- [x] Expression tree use or implicit conversion and `u8` literal disallowed
- [x] UTF8 `byte[]` stored in `<PrivateImplementationDetails>` if Length > 2
- [x] concatenation: `UserDefinedConcatenation_01`, etc.
- [x] `const ReadOnlySpan<byte> x = "abc"u8;` is disallowed: `NotConstant_01`
- [x] `void M(Span<byte> x = "abc"u8)` is disallowed: `DefaultParameterValues_01`, `_02`
- [x] `"abc"u8` and implicit conversion disallowed in attribute value: `AttributeArgument_01`, etc.
- [x] nullability of `"abc"u8`: `NullableAnalysis_03`
- [x] Missing and invalid type and members: `ReadOnlySpan<T>`, `Span<T>`, etc.
- [ ] ~~Document breaking changes~~ (none)
- [x] IOperation: `IOperationTests_IUtf8StringOperation`
- [x] `GetTypeInfo()`
- [x] `GetConversion()`
- [ ] EE
- [ ] EnC with `<PrivateImplementationDetails>`
- [x] SyntaxNormalizer: string, single and multi-line raw string
- [x] null terminator: `NullTerminate_01`, `_02`

## Public API
- [x] API review https://github.com/dotnet/roslyn/issues/61847

## IDE
- [x] SyntaxClassifier: string, single and multi-line raw string
- [x] QuickInfo: `byte[]` natural type

## Debugger
- [ ] Can/should we show the string (rather than just bytes) when hovering over such variables? (There's discussion on csharplang on this and decompilation experience)

## Other
- [x] LDM: `readonlySpanOfByte is "abc"` or `readonlySpanOfByte is "abc"u8`? (also reported [here](https://github.com/dotnet/roslyn/issues/60747) and [here](https://github.com/dotnet/csharplang/discussions/6036)) https://github.com/dotnet/csharplang/issues/6161
- [x] LDM: confirm whether the conversion part of the feature is desirable (answer: no)
- [x] LDM: confirm whether the suffix part of the feature is desirable (answer: yes)
- [x] LDM: allow concatenation? ([issue](https://github.com/dotnet/roslyn/issues/60896)) https://github.com/dotnet/roslyn/pull/62044
- [x] Update [utf8-string-literals.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/utf8-string-literals.md) to reflect LDM decisions
  - [x] require `u8` suffix: [notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#target-typing-a-regular-string-literal-to-utf8-types)
  - [x] natural type `ReadOnlySpan<byte>`: [notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#natural-type-of-utf8-literals)
  - [ ] no target type to `byte[]`: [notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#target-type-utf8-literals-to-byte)
  - [x] null terminated: [notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-18.md#should-utf8-literals-be-null-terminated)
  - [x] concatenation: [notes1](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-06.md#concatenation-of-utf8-literals), [notes2](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-29.md#utf-8-literal-concatenation-operator)

**Comment by ericwj** [comment]
Re
> - [ ] interpolated strings with suffix disallowed

I bump into this. Quite weird actually, I had:
```
""""
"": {
}
""""u8
```
which was fine
* I removed the starting `"":` 
* it started to consider the `{}` as interpolation holes
* so I add a `$` 
* now I'm broken - `u8` is no longer allowed, even though I don't have interpolation holes

**Comment by AlekseyTs** [comment]
@ericwj This issue is not for general purpose discussions on topics related to the feature. If you have an issue to report/discuss, please open a separate dedicated issue for that.

**Comment by CyrusNajmabadi** [comment]
@ericwj not sure what you mean:

![image](https://user-images.githubusercontent.com/4564579/187500437-c9451d0e-8255-43cf-abd5-465c5580146a.png)

The curlies are not interpolation holes here.

**Comment by ericwj** [comment]
> The curlies are not interpolation holes here.

I minimized the example on Github after which I copied it back in VS and indeed the error was gone too.
