### ISSUE TITLE
Quick info needs to show signatures of anonymous delegates.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#58871]
![image](https://user-images.githubusercontent.com/4564579/149592546-fed15873-1b18-4473-b0e7-4a545f3858e3.png)

We should show these signatures in quick info (just like we show the shape of anonymous types).

**Comment by CyrusNajmabadi** [comment]
@jnm2 i can't remember.  did you do anything here?

**Comment by jnm2** [comment]
https://github.com/dotnet/roslyn/issues/46190

**Comment by CyrusNajmabadi** [comment]
Thanks!
