### ISSUE TITLE
csi.exe should not change the current working directory

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#5888]
Right now if you build and run `csi.exe` from the root of the Roslyn directory (i.e., `./Binaries/Debug/csi.exe`) the current working directory is changed to the location of the executable itself. This makes passing relative paths as arguments very difficult (because most people will want to naturally use the tab-completion provided by their shell to complete a path) and resolving path arguments almost impossible.

`csi` should follow the same convention as other scripting languages and maintain the current working directory. If the goal is to provide a portable method to find things near the executable, I would recommend an implicit variable, like the Args property, be placed in scope. My recommendation would be a property called ScriptRoot which provides a fully qualified path as a string to the directory that contains `csi.exe`.

**Comment by tmat** [comment]
Should be fixed by https://github.com/dotnet/roslyn/pull/5857. Please verify after it's merged.
