### ISSUE TITLE
IDE0045 introduce unnecessary casts

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#58898]
**Version Used**: 4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff

**Steps to Reproduce**:

```cs
Guid? id;

// two cases:
// 1. id variable here converted to var id
if (true)
{
    id = Guid.NewGuid();
}
else
{
    id = Guid.Empty;
}

// 2. here variable is reused
if (true)
{
    id = Guid.NewGuid();
}
else
{
    id = Guid.Empty;
}
```

**Expected Behavior**:

```cs
// 1
var id = true ? (Guid?)Guid.NewGuid() : Guid.Empty;
// or
var id = true ? Guid.NewGuid() : (Guid?)Guid.Empty;

// 2
id = true ? Guid.NewGuid() : Guid.Empty;
```

**Actual Behavior**:

```cs
// 1
var id = true ? (Guid?)Guid.NewGuid() : (Guid?)Guid.Empty;
// 2
id = true ? (Guid?)Guid.NewGuid() : (Guid?)Guid.Empty;
```

**Comment by CyrusNajmabadi** [comment]
This isn't really an issue with 'Convert to conditional expression'.  But rather that the cast-simplifier doesn't feel like these casts are removable.  The issue arises even if you have the basic code:

```c#
        var id = true ? (Guid?)Guid.NewGuid() : (Guid?)Guid.Empty;
```

These casts should be marked as removable, but they are not.

**Comment by CyrusNajmabadi** [comment]
> They actually marked as removable (in IDE, if that's what you mean)

They are not marked as removable for me (have verified this locally, working on a fix now).
