### ISSUE TITLE
Quick Actions refactoring offers to introduce parameter for variable that is already a parameter

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/roslyn#58893]
![image](https://user-images.githubusercontent.com/434140/149699497-54b17596-e8fd-427d-9cfe-652da52000bf.png)

VS `Quick Actions` offers to introduce a parameter for `service`, which already comes into the method as a parameter, resulting in code that will fail to compile.

![image](https://user-images.githubusercontent.com/434140/149699771-10e0e782-ef73-447e-9f3b-60d53de2a93c.png)

This is the list of all refactorings offered from `Quick Actions`, with the default (**Use discard**) being legitimate.

VS version:

```
Microsoft Visual Studio Enterprise 2022
Version 17.1.0 Preview 3.0 [32112.464.d17.1]
VisualStudio.17.IntPreview/17.1.0-pre.3.0+32112.464.d17.1
```

**Comment by CyrusNajmabadi** [comment]
We should likely offer this fix. But we should ensure the name doesn't collide.

**Comment by aaronpowell** [comment]
@CyrusNajmabadi but it's already available as a parameter, so what is this fix offering of value?

**Comment by CyrusNajmabadi** [comment]
What was the reason to pass it twice...

**Comment by aaronpowell** [comment]
I wasn't wanting to pass the parameter twice, it was just offered up by VS so I explored it.

**Comment by CyrusNajmabadi** [comment]
Oh...  i think i'm confused about your repro then.  Can you give a full repro of this?  Importantly, please let us know what part of code your caret was on when you brought up the lightbulb.

I thought you were on the `DoConfigureServices(services, configuration, services)` line.   And thus, you were indicating you wanted to pass the parameter multiple times.

**Comment by aaronpowell** [comment]
Ah right, no the cursor is on `services` within the `DoConfigureServices` method, and it was offering a refactoring to introduce `services` as a parameter (which it already is). Here's a gif of it in action.

![roslyn-bug](https://user-images.githubusercontent.com/434140/149845095-d9d6900e-6f1e-4ba5-886e-4cdd811610a4.gif)

**Comment by CyrusNajmabadi** [comment]
Could 6 you supply a repro case?  Thanks!

**Comment by aaronpowell** [comment]
I've tried across several codebases, .NET 5 and .NET 6, new and old, and it seems to happy on any method parameter.

**Steps to repo**

1. Clone https://github.com/aaronpowell/httpstatus
2. Open in VS 2022 (I'm on `Version 17.1.0 Preview 3.0 [32113.165.d17.1]` and don't have any others installed to test 😅)
3. Open `Program.cs`
4. Place cursor on the `args` parameter on line 14
5. Activate Quick Actions

![image](https://user-images.githubusercontent.com/434140/149848857-e0e328e5-a85f-4e7f-a332-b975fb54bcb5.png)

(Sorry, can't share the original codebase, it's one of our products that's closed source)

**Comment by sharwell** [comment]
This seems trivially reproducible (cursor on `base(mes$$sage)`):

![image](https://user-images.githubusercontent.com/1408396/150241058-b2796a60-6268-4f13-9c1f-c865bdd56f7b.png)
