### ISSUE TITLE
IDE0040 warns to add accessibility modifiers to explicitly-implemented static interface methods

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#58914]
**Version Used**: 
Version 17.1.0 Preview 3.0 [32113.165.d17.1]

**Steps to Reproduce**:
Explicitly implement a static interface method, e.g.
<img width="697" alt="image" src="https://user-images.githubusercontent.com/2642209/149961641-568ae99a-11e8-4972-96af-119924416cfb.png">

**Expected Behavior**:
No warning.

**Actual Behavior**:
IDE0040 warns that a visibility should be added.  But visibility isn't supported:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/2642209/149961868-6f0c2436-3c54-4693-836a-6420eaa61735.png">

**Comment by Youssef1313** [comment]
Working on a small fix now.
