### ISSUE TITLE
Analyzer driver fails to account for source generator outputs in ServiceHub

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#58916]
Likely duplicates:

#58913
#58976
[AB#1462513](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1462513) (https://developercommunity.visualstudio.com/t/issue-when-using-loggermessage-and-static-extensio/1638197)
[AB#1461488](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1461488) (https://developercommunity.visualstudio.com/t/Code-generated-by-Source-Generator-is-ma/1636837)
[AB#1459138](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1459138) (internal only)

Possibly related:

[AB#1438489](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1438489)
#57082

**Comment by jasonmalinowski** [comment]
Closing this as I've closed out all the bugs that are likely dupes. The "possibly related" ones aren't, so those are still around.
