### ISSUE TITLE
Questionable DFA behavior

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58922]
Cherry-pick https://github.com/dotnet/roslyn/commit/383c9064f2223f90658da0ad19a13fc932f53513

The tests currently pass. The behavior around `if (isAutoProp)` looking suspicious to me.

@AlekseyTs @333fred

**Comment by RikkiGibson** [comment]
Discussing offline. I think the difference between auto and non-auto properties here comes down to the implicit-`readonly`-ness of auto implemented getters.

**Comment by Youssef1313** [comment]
Thanks for clarifying @RikkiGibson!
