### ISSUE TITLE
Code Cleanup: Settings revert out of the set and cannot be used

### ISSUE THREAD

**Issue by BhaaLseN** [dotnet/roslyn#58924]
**Version Used**: Visual Studio 2022 (17.0.4)

**Steps to Reproduce**:

1. Open any code file to see the Code Cleanup at the bottom of the text editor
   _(in my case: a C# source file)_
2. Choose to configure the Code Cleanup profiles, pick Profile 2, select **all** cleanups at the bottom, and move them to the top. Confirm with "OK"
   _(I used Profile 2 because I don't use it, so YMMV. The idea is to configure Profile 1 as i want it, because it is default and runs on a hotkey; but this issue prevents me from doing that)_
3. Reopen the Code Cleanup profile configuration and switch back to Profile 2

**Expected Behavior**:
All cleanups are added to the list and run when the profile is executed.

**Actual Behavior**:
Four cleanups do _not_ stick to the profile and always revert back to being off:
![Code Cleanup Profile 2](https://user-images.githubusercontent.com/826052/150009349-29c7b4c9-4acc-46ab-aca0-d4032a219572.png)
- Apply 'this.' qualification preferences
- Make private fields readonly when possible
- Remove unnecessary usings
- Sort usings

I _think_ this might be related to the other four that apply to Visual Basic; but they have no effect on a C# file.
**Edit:** It just occurred to me that I could attempt an remove the Visual Basic cleanup, then add the C# cleanup (for example, remove "Sort imports" and add "Sort usings"). However: this simply reverts it back to the opposite. The profile always references (or lists) the Visual Basic cleanup and removes the C# cleanup (with the end result that it doesn't work on C#). Maybe they use the same internal name by accident, or something along that sort?

Especially the last two make Code Cleanup annoying to use, because they were one of the first actions to be in there; and at least for me, I've gone from running "Remove and Sort Usings", "Format Document", "Save" (as a key sequence Ctrl+R, Ctrl+S - Ctrl+E, Ctrl+D - Ctrl+S) to just running "Run Code Cleanup", "Save" (as a key sequence Ctrl+E, Ctrl+D - Ctrl+S; effectively using my muscle memory of using Ctrl+E, Ctrl+D anyways to run the previous "Format Document" which is now part of the Code Cleanup; as well as others).

The upcoming "Automatically run code cleanup on save" feature will even make this nicer for me; but only when I can configure my preferred cleanups correctly.

**Comment by sharwell** [comment]
This was fixed by #57883, and tracked here:
https://developercommunity.visualstudio.com/t/Configure-Code-Cleanup-selections-are-/1571097
