### ISSUE TITLE
Valid keywords missing from completion list between parentheses

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#58921]
Reported by @dpugh

IntelliSense keeps overwriting what I type by giving me what it thinks I want. Spoiler: it isn’t.
 

Typing space here gives me “NewsStyleUriParser” and I just wanted “new “.
![image](https://user-images.githubusercontent.com/788783/149998250-899df9af-29b4-4e1f-bc20-c477167f2fc4.png)

This feels like the same root cause as this scenario:
 
![image](https://user-images.githubusercontent.com/788783/149998260-26db4ec0-af6f-4de6-94ae-e321a4a529d8.png)

Where typing a ‘.’ Gives me CallConvThiscall. Instead of “this.”.

Essentially, Roslyn is using the () as a trigger to do a cast and limits the IntelliSense selection to types. Or, at least, that is what I though was happening: IntelliSense does – see below – contain fields (data3), local variables (data), and snippets (do). So why are keywords like this and new not showing up in IntelliSense? It doesn’t seem to make any sense to offer a field but not this.

Is there a way to turn this optimization off? I find it incredibly annoying (as a (former (Lisp) programmer) who doesn’t believe it is possible to have too many parentheses).

 
![image](https://user-images.githubusercontent.com/788783/149998299-7cfae033-ef9a-4171-94e9-f77e45200a5b.png)

**Comment by Youssef1313** [comment]
Similar scenario: https://github.com/dotnet/roslyn/issues/58906

**Comment by genlu** [comment]
Looks like this is fixed now
![image](https://user-images.githubusercontent.com/788783/157129467-a2924e88-2fcb-4598-bfef-d7d85dc40261.png)

**Comment by CyrusNajmabadi** [comment]
@genlu did you verify when teh parenthesized expression *precedes* another statement (which causes it to think this is a cast and not a parenthesized expression)?

**Comment by genlu** [comment]
ah, you are right. That's actually where the problem is.
