### ISSUE TITLE
Some nullable parameters are null-checked

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#58929]
https://github.com/dotnet/roslyn/blob/6be7f048e3cbb7a48cddcdef33d274ab40d3f799/src/Workspaces/Core/Portable/Workspace/Workspace_Registration.cs#L78-L83

https://github.com/dotnet/roslyn/blob/6be7f048e3cbb7a48cddcdef33d274ab40d3f799/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs#L144-L147

cc @genlu @dibarbet @CyrusNajmabadi 

It seems like if the parameter type allows null, then the parameter should not be null checked.

**Comment by sharwell** [comment]
I opted to not push for a new analyzer here, because the current analyzer for upcoming `!!` feature already helps identify and remove these cases.
