### ISSUE TITLE
Peek Definition tries to show the generated .razor.g.cs file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58939]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/choosing-peek-definition-on-an-enum-de/1632175)._

---
The title pretty much encapsulates it. Seems like a possible dup of https://github.com/dotnet/razor-tooling/issues/4956 but thats closed.

Also 'peek definition' fails for anything in a shared/<component>.razor file, enum was just an example.

it complains that it cannot find shared/<comp>.razor.g.cs

! [image.png] (https://aka.ms/dc/image?name=B36c7568d4a96495d9fb2cfbff2ecdaf2637772901271836506_20220108-175526-image.png&tid=36c7568d4a96495d9fb2cfbff2ecdaf2637772901271836506)

---
#### Feedback Bot on 10/01/2022, 05:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 13/01/2022, 06:13 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
> From @NTaylorMullen 
> The C# systems go-to-def infra utilizes the `AbstractSpanMappingService` that Razor implements to find where the location exists. In my testing that works as expected so something may be falling over on the C# front here.
