### ISSUE TITLE
Roslyn in OS package managers

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#5895]
# DRAFT

The goal is to have an official Roslyn package for Debian, Red Hat, and Homebrew in addition to providing the resources for other package system maintainers to quickly and easily produce unofficial Roslyn packages.

This effort can be broken down into three main steps, with the final step fulfilling the above goal of high quality idiomatic Linux / OSX packages.

* [ ] `make && sudo make install`
    * [ ] Debian
    * [ ] Red Hat
    * [ ] Homebrew
* [ ] Source package + binary package (with mono bootstrap)
    * [ ] Debian
    * [ ] Red Hat
    * [ ] Homebrew
* [ ] Source package + binary package (with the rest of dotnet/coreclr)
    * [ ] Debian
    * [ ] Red Hat
    * [ ] Homebrew

## make && sudo make install
The first step is to have the classic `make && sudo make install` incantation build and install Roslyn from source using Mono as a dependency.  The installed `roslyn` executable will be runnable on CoreCLR  by default.

Build-time dependencies: Mono, MSBuild.
Run-time dependencies: CoreCLR, libunwind.8, libssl?

## Source package and binary package
After getting basic install working with Make, it should be fairly simple to get simple source packages that run the makefile during installation.  

Now we can explicitly depend on Mono, though MSBuild will continue to be an issue.  If by this time MSBuild has a source package, we could depend on that.

Binary packages will be easier, requiring us to basically zip up all the required DLLs and executables that are required to run Roslyn.  The installation method will just be to unzip into `/usr/`.

## Integrated package

Once the other dotnet packages come online, we will integrate our source and binary packages with them.  Unfortunately, MSBuild will require mono for the foreseeable future, but Roslyn itself should be run using the coreclr version installed by their package manager.

**Comment by TyOverby** [comment]
@agocke: Here's a draft of our plan as I remember it from our discussion last Thursday.

**Comment by agocke** [comment]
Hopefully source build won't be too system-specific. `make && make install` should be pretty uniform.

**Comment by TyOverby** [comment]
@agocke: https://github.com/streadway/hello-debian

**Comment by davkean** [comment]
Going to move this to compilers, as this is a product deliverable not a infrastructure issue.

**Comment by TyOverby** [comment]
This is pretty outdated now.  Closing.
