### ISSUE TITLE
Need VS2022 17.0.5 release notes

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#58963]
[https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes)
Again, new version released without release notes. Developercommunity no body response so I post here.

**Comment by DoctorKrolic** [comment]
You can close this issue, release notes are already added

**Comment by CyrusNajmabadi** [comment]
Not a roslyn issue.  Thanks :)
