### ISSUE TITLE
Creating named tuple type synonyms in using not allways allowed

### ISSUE THREAD

**Issue by AlexeiScherbakov** [dotnet/roslyn#58967]
**Version Used**:
Microsoft Visual Studio Community 2019
Version 16.11.2
.NET Core SDK 5.0.400
**Steps to Reproduce**:

Create 2 files with using synonyms definition

This is working
```
using TreeKey = System.ValueTuple<string, string, string, string, string, string>;
using TreeKey2 = System.ValueTuple<(string a, string b, string c, string d, string e, string f)>;
```
This is not
```
using TreeKey = System.ValueTuple<string, string, string, string, string, string>;
using TreeKey2 = System.ValueTuple<(string a, string b, string c, string d, string e, string f)>;
using TreeKey3 = (string a, string b, string c, string d, string e, string f);
```

**Expected Behavior**:
Tuple synonym TreeKey3 must be allowed, because TreeKey2 synonym is allowed

**Actual Behavior**:
Tuple synonym TreeKey3 don't compile. Tuple synonym TreeKey2 which contains same(!) named tuple inside can be compiled. TreeKey & TreeKey3 are equivalent, but TreeKey3 contains syntax sugar.

**Comment by CyrusNajmabadi** [comment]
Language feature request tracked here: https://github.com/dotnet/csharplang/issues/4284
