### ISSUE TITLE
Creating a new C# class from item template is missing a space between the access modifier and 'class' keyword

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58974]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Creating-a-new-C-class-from-item-templa/1640048)._

---
[severity:It bothers me. A fix would be nice]
1. Open a C# project
2. Add new item -> C# class

Expected:
The new file is syntactically correct

Actual: 
There is a space missing between the access modifier and the class keyword, creating a syntax issue:
```
internalclass HtmlWorkspaceSymbolInterceptor
        ^
       should be a space here
```

---
#### Feedback Bot on 1/18/2022, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
This happens when there is an `.editorconfig` file with `csharp_style_namespace_declarations = file_scoped` in scope

**Comment by Youssef1313** [comment]
@davidwengier And now I know why I couldn't reproduce!

**Comment by davidwengier** [comment]
@Youssef1313 I cheated and opened the same (closed source) project that @jimmylewis was using when he reported it 😛
