### ISSUE TITLE
Add a feature that we can hide this bar

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58979]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-feature-that-we-can-hide-this-bar/1623990)._

---
! [image.png] (https://aka.ms/dc/image?name=B0e30b39172c1417baf73e5907799cef4637762981688720172_20211228-222248-image.png&tid=0e30b39172c1417baf73e5907799cef4637762981688720172)

I dont know how can I hide this bar (red rectangle in this picture) when my cursor over a keyword,
 it is very annoying bar that interfered our work, thanks!

Don't know how to hide this prompt bar, when my cursor moves to a keyword, it is very annoying, affecting the work, thank you!

---
#### Feedback Bot on 12/28/2021, 07:32 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by sharwell** [comment]
This TypeScript was incorrectly moved to the C# team. We've now moved it back.
