### ISSUE TITLE
Code Folding for Additional Types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58982]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Folding-for-Additional-Types/1616912)._

---
Can we get Code Folding for XDocument, XElement, XAttribute, etc.

For those of us who are generating complex 'X' type documents, it is extremely difficult to keep things organized.

---
#### Feedback Bot on 12/19/2021, 07:14 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
This appears to be a request to support code folding for multi-line invocation and/or object creation expressions.

**Comment by CyrusNajmabadi** [comment]
Closing duet o lack of feedback.
