### ISSUE TITLE
Visual Basic Auto-implement interface behaviour changed

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#5898]
If you have code like this:

``` VB
Public Class BandEntry
    Implements IBandEntry
End Class

Friend Interface IBandEntry
    Property BandStart As Decimal
    Property BandTypeID As Integer
    Property Rate As Decimal
End Interface
```

In VS2013 when I used the auto-implement interface feature (in VB, press return after implements statement, body of class would be auto populated) it would produce out like the following: 

``` VB
Public Class BandEntry
    Implements IBandEntry

    Public Property BandStart As Decimal Implements IBandEntry.BandStart

    Public Property BandTypeID As Integer Implements IBandEntry.BandTypeID

    Public Property Rate As Decimal Implements IBandEntry.Rate
End Class
```

In Visual Studio 2015 it produces output like this: 

``` VB
Public Class BandEntry
    Implements IBandEntry

    Public Property BandStart As Decimal Implements IBandEntry.BandStart
        Get
            Throw New NotImplementedException()
        End Get
        Set(value As Decimal)
            Throw New NotImplementedException()
        End Set
    End Property

    Public Property BandTypeID As Integer Implements IBandEntry.BandTypeID
        Get
            Throw New NotImplementedException()
        End Get
        Set(value As Integer)
            Throw New NotImplementedException()
        End Set
    End Property

    Public Property Rate As Decimal Implements IBandEntry.Rate
        Get
            Throw New NotImplementedException()
        End Get
        Set(value As Decimal)
            Throw New NotImplementedException()
        End Set
    End Property
End Clas
```

Is it possible to have the old behaviour back either by default or as an option? We commonly use interfaces to specify data types between our presentation and view layers, and a lot of the time all we need us the auto-property implementation. Since this change I need to go through the generated code removing 90% of it every time. I appreciate others might have to do the same in reverse, but I'd suggest they'd need to go through the generated code replacing the bodies anyway, so there's less wasted effort that way. Making it an option, or perhaps having two choices from a lightbulb menu would make both camps happy?

**Comment by jmarolf** [comment]
Note: C# in Visual Studio 2013 and 2015 generated the following code:

```C#
public class BandEntry : IBandEntry
{
    public decimal Rate
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }

    public int BandTypeID
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }

    public decimal BandStart
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I would prefer this to be an option for both VB/C#.  Both should have a 'prefer auto properties when generating code' option.

**Comment by Pilchie** [comment]
What is the current state of this?

**Comment by CyrusNajmabadi** [comment]
AFAICT, nothing has changed here.

**Comment by Pilchie** [comment]
Except that you added options that control preferences for how these are generated right?  Is there more we should do here?

**Comment by CyrusNajmabadi** [comment]
I don't recall ever adding an option to control how properties are generated (wrt to auto-property or not).  Seems like a nice enough option to add though!
