### ISSUE TITLE
Create a test for AdditiveSpans changes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#58984]
We [modified the behavior for AdditiveSpans](https://github.com/dotnet/roslyn/pull/58983/files) to resolve an issue with some Razor scenarios, but did not yet add a test due to time constraints.

AFAIK the test makes the most sense in `SemanticTokensRangeTests.cs`, but someone with more experience in the Roslyn repo might know better.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
