### ISSUE TITLE
the flag (tag? dont know the name) regarding inheritance is misleading

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#58992]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/the-flag-tag-dont-know-the-name-regar/1640574)._

---
a) it says 'xxx is inherited'

This is incorrect grammar. A class 'inherits' from its base class / interface. The base class 'is inherited' by its derived class. It should say 'xxx inherits'. I can imagine another part of the UI that flags classes that are used as bases , in that case what would it say? 'xxx is inherited' would be correct.

b) For a plain record (show in screen shot) this is simply annoying

All records implement iequatable automatically so this adds nothing. Every record says it. The UI should be silent if the record only has the compiler added interface

I spent some time trying to work out what this was trying to tell me.

![image](https://user-images.githubusercontent.com/1408396/151228950-a40c7bd1-ba36-4165-b9d7-ae6b3b76b5a2.png)

---
#### Feedback Bot on 1/18/2022, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/20/2022, 11:42 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
For issue a)
I feel https://github.com/dotnet/roslyn/issues/55041 should be enough to address it.

For issue b)
Inheritance Margin is filtering out these types https://github.com/dotnet/roslyn/blob/3b32fc36ec4c2a81457d90f965c89c5b6fc37082/src/Features/Core/Portable/InheritanceMargin/InheritanceMarginServiceHelpers.cs#L113

A better solution I can imagine is, only show the glyph if the type implicitly inherits from some type, like
`class A : B { }`

**Comment by CyrusNajmabadi** [comment]
@Cosifne do we need to do anything here at this point?  if not, clsoe this out.  Given this is just a single report, this seems minor.
