### ISSUE TITLE
Investigate why „  ” in Polish translations doesn't show correctlly

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#58994]
See https://github.com/dotnet/roslyn/pull/41095

**Comment by Youssef1313** [comment]
Here I'm printing the character from a new console app. It looks like the console window, by default, doesn't support UTF-8 characters.

![image](https://user-images.githubusercontent.com/31348972/150521057-e20686d0-9694-4a8b-8925-2c3b54dcfd55.png)

**Comment by Youssef1313** [comment]
@jcouv Do you think anything can be done here?

**Comment by Youssef1313** [comment]
Looks simple. `Console.OutputEncoding = Encoding.UTF8;` fixes this issue.

**Comment by jcouv** [comment]
From discussion in linked PR, it looks like `CscTask` is behaving as expected. Namely, it honors [`ToolTask.StandardOutputEncoding`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tooltask.standardoutputencoding?view=msbuild-17-netcore).
That documentation page says: "Console-based output uses the current system OEM code page by default. [...]". So it seems we're at the mercy of the console settings.
I'll go ahead and close.

@Youssef1313 Feel free to re-open if I misunderstood. Thanks
