### ISSUE TITLE
Add telemetry to codefix error infobar

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#5899]

**Comment by dpoeschl** [comment]
Getting telemetry on this may guide us to an eventual better experience that doesn't put the initial burden of choosing whether to re-enable on the customer. /cc: @davkean

**Comment by jmarolf** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/b3fbd58987414f16bbed1e4979245f11beaacd60
