### ISSUE TITLE
Extract Interface not available on double clicking class name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59038]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extract-Interface-not-available-on-doubl/1644496)._

---
When I select the class name(by double clicking on it)->right click->Refactor->Extract, i only see the option to extract class not interface.
Workaround select class name(don't double click)->right click->Refactor->Extract, then you can see Extract Interface
This is not uniform and causes confusion, and in my case wasted a lot of time

---
#### Feedback Bot on 1/23/2022, 08:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
I believe this was inaccurately moved to Roslyn. We do not have a `right click -> refactor` menu. I did double check that our `Extract Interface` works with double clicking on the class name.
