### ISSUE TITLE
IDE does not offer name simplification for global using type aliases

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59042]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE-does-not-offer-name-simplification-f/1644488)._

---
When global using denotes type alias, IDE does not offer option to simplify type name in files (except for file where using is declared).

![B748c37ae07274aa983d3794236563aff637783951037924590_GlobalUsingAliasSimplificationFailure](https://user-images.githubusercontent.com/1408396/150846116-73d12f47-4601-42c0-a376-4e3701250cf2.png)

---
#### Feedback Bot on 1/23/2022, 11:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/24/2022, 09:54 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/59088
