### ISSUE TITLE
Raw string literal API review.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#59046]
## Background and Motivation

[Raw string literals](https://github.com/dotnet/csharplang/blob/main/proposals/raw-string-literal.md) have been approved for C# 11.  New syntax APIs are needed for this change.

## Proposed API

```diff
public enum SyntaxKind
{
+        SingleLineRawStringLiteralToken = 9072,
+        MultiLineRawStringLiteralToken = 9073,

+        InterpolatedSingleLineRawStringStartToken = 9080,   // $"""
+        InterpolatedSingleLineRawStringEndToken = 9081,     // """
+        InterpolatedMultiLineRawStringStartToken = 9082,    // $"""<whitespace><newline>
+        InterpolatedMultiLineRawStringEndToken = 9083,      // <newline><whitespace>"""
}
```

```diff
public class SyntaxFactory
{
+    public static InterpolatedStringExpressionSyntax InterpolatedStringExpression(Microsoft.CodeAnalysis.SyntaxToken stringStartToken, Microsoft.CodeAnalysis.SyntaxToken stringEndToken);
}
```

## Alternative Designs

There are two major design alternatives to consider.  One for normal raw strings, and one for interpolated raw strings.

First, for normal raw strings, i took teh approach of adding the new literal *token* kinds but *not* adding a new literal *expression* kinds.  In other words, SingleLineRawStringLiteralToken  and MultiLineRawStringLiteralToken  both map to StringLiteralExpression.

This doesn't actually match how we do things elsewhere.  For example, there is TrueKeyword+TrueLiteralExpression and FalseKeyword+FalseLiteralExpression.  We do not have TrueKeyword/FalseKeyword mapping to BooleanLiteralExpression.

We could keep the 1:1 relation here, adding SingleLineRawStringLiteralExpression and MultiLineRawStringLiteralExpression.

--

Second, for interpolated strings, we chose to heavily reuse the existing InterpolatedStringExpressionSyntax and InterpolationSyntax nodes.  This means, for example, that the same InterpolationSyntax node *and kinds* are used for `{ 0 }` as well as `{{{ 0 }}}`.  In hte latter there is an Open/CloseBraceToken that spans the three characters.  Note: there is precedence for this elsewhere in the language.  For example, in an xml comment `List{T}` says that it has a LessThan/GreaterThanToken for `{` and `}`.

**Comment by 333fred** [comment]
### API Review

API is approved, merging the separate end tokens for the interpolated string form.

* Do we want to have a 1:1 relation between tokens and expressions, or is it fine to have multiple syntaxes map to StringLiteralExpressionSyntax/InterpolatedStringLiteralExpressionSyntax?
    * We've found the single expression kind useful for the IDE, our consumers probably will too.
    * These things are still just strings, have constant values.

**Conclusion**: We will not have separate expression kinds for these strings.

* Should we reuse SyntaxKind.OpenBrace for all interpolated raw string literals, no matter the number of braces?
    * We also think that a single token would be nice for consumers, just like a single expression kind.
    * Already happens in strings with @$" and $@", and for LessThan/GreaterThan with XML doc comments and generic types in crefs.
    * SyntaxFacts.GetText will return the default, whatever the default is, just as it does with the other exception cases today.

**Conclusion**: We will reuse OpenBrace as the token type, no matter how many braces are in the token. Our future selves should try to think about whether similar cases should be less specifically named to avoid confusion like this.

* Should we use trivia for the multi-line whitespace/newline portions?
    * For all but the trailing whitespace/newline after the open token, the whitespace _is_ significant.
    * Language takes the parsed text and creates semantic meaning for it. Syntax should reflect the written text.
    * If we ever want to add a language specifier at the start in the future, we should add a new token for that, and then keep the interior content the same as it is now.

**Conclusion**: All the content between the open and close tokens will be part of the text, no trivia involved.

* Should we merge the end tokens types for single and multiline?
    * Having different start tokens was useful for the IDE, but different end token kinds weren't.

**Conclusion**: Merge `InterpolatedSingleLineRawStringEndToken` and `InterpolatedMultiLineRawStringEndToken`.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We did the token merge prior to merging raw literals in.
