### ISSUE TITLE
IntelliSense and syntax highlight not working at all for function pointer callconv-s

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#59052]
**Version Used**:

- VS2022 17.0.5
- VS2022 17.1 Preview 3

**Steps to Reproduce**:

1. Write any function pointer with explicit callconv(s), eg.:

```csharp
delegate* unmanaged[Stdcall]<void> f0;
delegate* unmanaged[Cdecl]<void> f1;
delegate* unmanaged[MemberFunction, SuppressGCTransition]<void> f2;
delegate* unmanaged[Thiscall]<void> f3;
delegate* unmanaged[Fastcall]<void> f4;
```

2. Observe that syntax highlight is broken (the type is white)
3. Observe that IntelliSense is broken (hovering doesn't show the type info)

**Expected Behavior**:

- The modifiers should be colored (in green, as they're classes)
- Hovering on them should display the usual type info like on any other type

**Actual Behavior**:

- No syntax highlight at all
- No hovering tooltip at all

![](https://user-images.githubusercontent.com/10199417/150996711-b5ab92bd-b0a2-4f0c-b265-7ca40471e382.png)

In case it matters, both issues also reproduce on casts, not just member declarations.

**Comment by CyrusNajmabadi** [comment]
This is very low priority for us.  We would take a suitably small and targetted fix here though.

**Comment by Youssef1313** [comment]
This actually got already fixed. @CyrusNajmabadi I think it could be closed.

**Comment by CyrusNajmabadi** [comment]
Okey dokey!
