### ISSUE TITLE
Remove reflection based code in VisualStudioDiagnosticAnalyzerProvider

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#59076]
> can you file a bug in https://devdiv.visualstudio.com/ to track getting some apis from the VS team so we don't need to do this?

Sure. I do see that both the types being reflected in this method are public, so maybe this is just old code before VS team made them public? There is also whole bunch of reflection based code here: https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioDiagnosticAnalyzerProvider.cs. I am going to first take a stab at getting rid of this from our end, if possible. For the ones we cannot get rid of, I'll create a bug for VS team to provide public APIs.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/59075#issuecomment-1021949930_

**Comment by mavasani** [comment]
Based on the discussions with the VS Extension Manager team, the extensibility APIs in all Extension manager related assemblies are internal to their team, and are not yet publicly supported. We need to stick with the fragile reflection based code for now.

**Comment by CyrusNajmabadi** [comment]
Have we talked to them about how that causes major issues like this?  I don't get how it can be internal when a core vs scenario like this is shipping :-)
