### ISSUE TITLE
Typing `///` in top-level statements inserts a documentation comment template

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#59081]
**Version Used**: `Compiler version: '4.1.0-3.22062.11 (cc0d213b)'. Language version: 10.0.` (Visual Studio 17.1.0 preview 4.0)

**Steps to Reproduce**:

1. Create a new console project and populate `Program.cs` as follows:

```csharp

Console.WriteLine("Hello, World!");

Console.WriteLine("Hello, World!");
```

2. Type `///` in the at the end of any line

**Expected Behavior**:

`///` is inserted with no special behavior. (Same as in normal method bodies.)

**Actual Behavior**:

A documentation comment template is erroneously generated:

![image](https://user-images.githubusercontent.com/278957/151220153-61910070-7234-4af2-9c17-3add6e6e7066.png)

**Comment by Youssef1313** [comment]
Same issue with namespaces.

**Comment by PathogenDavid** [comment]
Thanks, @Youssef1313!

**Comment by CyrusNajmabadi** [comment]
Indeed.  Thanks @Youssef1313 !
