### ISSUE TITLE
"Operator placement when wrapping" should belong to code-style tab

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#59098]
https://github.com/dotnet/roslyn/blob/3b32fc36ec4c2a81457d90f965c89c5b6fc37082/src/VisualStudio/Core/Def/EditorConfigSettings/DataProvider/Whitespace/CommonWhitespaceSettingsProvider.cs#L38

It should belong to code-style tab in EditorConfig UI.

@jmarolf

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
