### ISSUE TITLE
Fix parameter doc completion on primary constructors

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#59095]
Let's make sure that completion works properly on nominal records as well, particularly in the following scenarios analogous to method parameters:

![param-doc-completion-1](https://user-images.githubusercontent.com/5833655/99158368-e25ab280-2686-11eb-87d6-3352a6f7541f.gif)

![param-doc-completion-2](https://user-images.githubusercontent.com/5833655/99158415-6ca31680-2687-11eb-8496-33877c3f89e5.gif)

That is, typing a `///` on the line before a record declaration should include `<param>` tags for all the record primary constructor parameters, and within a `///` block the `<param>` elements should be suggested with appropriate parameter names, based on which parameters haven't been documented yet.

_Originally posted by @RikkiGibson in https://github.com/dotnet/roslyn/issues/44571#issuecomment-727275489_

Tagging @Youssef1313 who might know the right area to make the change here 😄

**Comment by RikkiGibson** [comment]
Rejoice, because apparently it was fixed when I wasn't paying attention :)

**Comment by Youssef1313** [comment]
PR that fixed this for reference: https://github.com/dotnet/roslyn/pull/52737

Both parameter wrapping and doc comments rely on the updated extension method.
