### ISSUE TITLE
EditorConfig UI: Location column doesn't refresh

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#59099]
1. Pick up code-style option whose location is "Visual Studio Settings" and change the option value.
2. The option gets updated correctly in `.editorconfig` file, but the UI is still showing "Visual Studio Settings".
3. Close and re-open the UI, the location now shows correctly

@jmarolf

**Comment by jmarolf** [comment]
duplicate of https://github.com/dotnet/roslyn/issues/60232

**Comment by ChrisMyrick** [comment]
+1 in increasing the priority of fixing this issue.
