### ISSUE TITLE
RE0001 should be moved to Analyzers layer

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#59101]
- It doesn't show in EditorConfig UI because it's not included in the code style package.
- It cannot be enforced on build for the same reason.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/07c890cb76d8e62fa29553c84a23896feec3b78b/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs#L92

This feels weird, shouldn't it be `option.Notification.Severity`? Applies to both RE0001 and JSON0001

@mavasani Can you please confirm?

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/07c890cb76d8e62fa29553c84a23896feec3b78b/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/AbstractRegexDiagnosticAnalyzer.cs#L27

This too:

https://github.com/dotnet/roslyn/blob/07c890cb76d8e62fa29553c84a23896feec3b78b/src/Features/Core/Portable/EmbeddedLanguages/RegularExpressions/LanguageServices/RegularExpressionsOptions.cs#L16-L21

**Comment by CyrusNajmabadi** [comment]
Closing out as unplanned.
