### ISSUE TITLE
'Simplify new expression (IDE0090)' should arguably _not_ be encouraged

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/roslyn#59119]
Please consider changing the default option value for `Simplify new expression (IDE0090)` to `false`.

The reason is that if people go with the default recommendation, they end up with lots of:-

`Item item = new(...);`

This is bad - as I have found to my cost - because it then means that a `Find in Files` in your solution for all instances of where your code is newing-up objects of a certain type gets very hard.  You'll need a regular expression - or - you change the name of the type at the definition, re-compile and then see where the errors are.  Neither option is good.  (There may be a clever third way that I don't know about, afforded by Visual Studio.)

If, however, people use the:-

`var item = new Item(...);` or `var item = new Item { ... }`

forms, then finding all instances of where I'm newing-up `Item` is trivial and virtually bomb-proof.  I just have to seach for "new Item".  The only gotcha is when `new` is on one line and `Item` is on another - something I always avoid.

I do actually use target-typed new expressions for when I'm newing-up `System.Object` (e.g. for an object that I'm going to do a `lock` on), but otherwise I have learned through bitter experience to avoid this feature.

Just because something exists doesn't mean you have to - or should - use it.  In this case, I would say that target-typed new expressions "lead you up the garden path" to a place you don't want to be... i.e. a place where finding all the locations where you new-up an object of a certain type becomes unnecessarily hard.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9ae307d-3966-023f-b327-406e7d605436
* Version Independent ID: a55dc225-570c-97be-63c5-d27830efa653
* Content: [IDE0090: Simplify 'new' expression - .NET](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0090)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0090.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0090.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CyrusNajmabadi** [comment]
I agree with @Youssef1313 .  We have rich semantic features for this purpose.  Not recommending them for the impact on those who only want find-in-files isn't really our philosophy.

Note: as a default this is entirely in line with what we do elsewhere.  So i think we should preserve this decision.  Users who would prefer to use find-in-files as a primary search mechanism can trivially disable this suggestion and never have to deal with that.

**Comment by Bellarmine-Head** [comment]
> Why would you search your codebase this way? You can use Find All References in IDE instead.

Because that would find ALL references, wouldn't it?  I just want to find all the places where I'm newing-up an instance of a certain type.  The number of those places might be considerably smaller than the number of all references.

(I usually want to find all places where I'm newing-up a type because I added a new property and want to ensure a value is always passed in.  When C# finally adds the `required` keyword for properties in a class - slated for C# 10 but it never made it - then I can simply make the property required, and my current need goes away.)

**Comment by Bellarmine-Head** [comment]
> We have rich semantic features for this purpose

Really?  Apart from "find ALL references" (see above for my reasons for why this might/could be limited), what is the semantic feature that finds me where I'm newing-up instances?

**Comment by Youssef1313** [comment]
@Bellarmine-Head You can find all references of a constructor, instead of the type. Besides that, you can just disable IDE0090.

**Comment by Bellarmine-Head** [comment]
> You can find all references of a constructor, instead of the type

How (in Visual Studio Pro 2019)?  Note: find all references to a type's **constructor** is obviously not what I'm after, but knowing how to do it could point me to doing what I do actually want to do.

All I'm seeing is how to find all references to a type, and group them in funky ways.


> Besides that, you can just disable IDE0090

Of course, but I really wonder about the benefit of the enabled IDE0090 recommendation.  Are target-typed new expressions actually _good_?  better than alternative/previous forms?  I wonder what the motivation was for introducing them, and I also wonder whether the rule was introduced to "push the new hotness" rather "make your code better".  For me, it seems like a step back.

**Comment by Bellarmine-Head** [comment]
It seems to me that target-typed new expressions don't make my code better.  It's an alternative to current forms, sure, but not one that is better.  And until someone can show me the "rich semantic feature" in VS 2019 Pro that enables me to find (only) all the places where I new-up a certain type, I would say that the target-typed new expression form is a step backwards for me.

**Comment by Youssef1313** [comment]
> How (in Visual Studio Pro 2019)? Note: find all references to a type's **constructor** is obviously not what I'm after, but knowing how to do it could point me to doing what I do actually want to do.

Just right click the constructor declaration and choose "Find all references"?

**Comment by Bellarmine-Head** [comment]
> Just right click the constructor declaration and choose "Find all references"?

@Youssef1313 

Ah!  That is interesting!  Yes, that seems to work.  I added a ctor to a type, r-clicked on it to "Find all references", and it found all the places where I'm newing-up instances of the type.  I didn't know that.  Thanks; I've learned something useful.

However, in keeping with more modern code style, and like many others it seems, my classes tend not to have constructors!!  (Hence I had to add one explicitly to test out the ability.)

I tend to have:-

```
    class Thing
    {
        public String Code { get; set; }
        public String Name { get; set; }
    }
```

or
 
```
    class Thing  // or record
    {
        public String Code { get; init; }
        public String Name { get; init; }
    }
```

depending on the C# version of the current project.

This is why I said:-

```
(I usually want to find all places where I'm newing-up a type because I added a new property and want to ensure a value is always passed in. When C# finally adds the required keyword for properties in a class - slated for C# 10 but it never made it - then I can simply make the property required, and my current need goes away.)
```

**Comment by Bellarmine-Head** [comment]
If the "rich semantic feature" can only find you places where you're newing-up instances if the types in question have explicit constructors - something the C# world is arguably moving away from - that would seem to be a bit of shortcoming (?)

**Comment by Youssef1313** [comment]
@Bellarmine-Head I actually noticed now that if you do a "Find all references" on the type itself, the result is already grouped:

![image](https://user-images.githubusercontent.com/31348972/151814160-550220e1-425d-40e2-b069-1a2722c7649c.png)

So you can collapse the references of the type itself and just look at the constructor references.

**Comment by Bellarmine-Head** [comment]
> So you can collapse the references of the type itself and just look at the constructor references.

Ooh, good find.  Thanks for sharing.  I didn't spot that there even was a second group in my code, because the first group had so many items - hundreds!  I thought it was the only group.  The second `new` group is very useful.

I will have to change my ways from using `Find in Files` (which I've used for 10+ years).

**Comment by Youssef1313** [comment]
Glad I could help!

**Comment by Bellarmine-Head** [comment]
Re. `Item item = new(...);` vs `var item = new Item(...);` I guess the benefit is that you type one word less.

**Comment by Bellarmine-Head** [comment]
Ok closing this.  I've been converted to the new ways.  Thx for your help @Youssef1313

**Comment by Youssef1313** [comment]
> Re. `Item item = new(...);` vs `var item = new Item(...);` I guess the benefit is that you type one word less.

Yes. A more important benefit (in my opinion) is for field initializers where `var` isn't allowed. Imagine a field like this:

```csharp
private Dictionary<int, List<(string, string)>> _myDictionary = new Dictionary<int, List<(string, string)>>();
```

With target-typed new, it's now just this:

```csharp
private Dictionary<int, List<(string, string)>> _myDictionary = new();
```

This one is my favorite use of target-typed new

**Comment by Bellarmine-Head** [comment]
>> With target-typed new, it's now just this:

That's a very good use-case.  Without the TTNE, the uber-long field initializer is painful and old-fashioned looking.

**Comment by Clonkex** [comment]
> I added a new property and want to ensure a value is always passed in

I know you found ways to do what you're looking for, but it seems really odd to me that you would have this issue in the first place. If you want to ensure a value is always set on a property at instantiation-time.... well that's precisely what a constructor is for. I'm kind of confused why you would opt to have to manually search your codebase to ensure your requirements are met rather than using constructors. It sounds like asking for bugs to me. Just declare a constructor with the required fields (and no parameterless constructor) and the compiler will instantly tell you if you're following your own rules.

**Comment by Bellarmine-Head** [comment]
> Just declare a constructor with the required fields (and no parameterless constructor)

This is not always what I want to do, or can do.  For example it doesn't work so well for deserialization (e.g. from JSON).  Often you find you can't get away with having no parameterles constructor, and the properties do get initialized in other ways (direct write to the property, or via reflection).

I like the simpler way of defining POCO C# classes / records in a way that resembles F# records... without having to define 1, 2, 3, 4 constructors each time.  Quick, simple, less verbose, plays nicer with deserialization.  The C# support for this style would be complete had the `required` keyword made it into C# 10 as initially hoped, but it's coming in C# 11.

**Comment by Bellarmine-Head** [comment]
https://www.youtube.com/watch?v=9CDgPgWF9IY

**Comment by ThomasYoussef-Business** [comment]
I strongly believe that there should be an option with Visual Studio's analyzers to choose to discourage the `new(...)` expression as well.

Some may find it to be better, but I believe that saying exactly what you're creating anew is important and being slightly more verbose is clearer in the intent of that construction.

**Comment by ThomasYoussef-Business** [comment]
> In all cases where we suggest simplifying, the code does exactly say what is being created anew.

The flexibility would be welcome regardless, as some codebases may benefit from the more verbose expressions.
I also feel like that isn't always the case, such as assigning to a variable defined higher up in the file. In that scenario, you might not see the type of the variable and would instead have to rely on the tooltip you receive from hovering with your mouse over the variable.

**Comment by sharwell** [comment]
@ThomasYoussef-Business Note that the current analyzer will not proactively instruct users to remove cases where target-typed new was used and the result isn't "obvious". However, it would be possible to create a new custom analyzer that performed this operation for you.
