### ISSUE TITLE
.NET Hot Reload concept of Reloadable Types needs to be added to capabilities check

### ISSUE THREAD

**Issue by LyalinDotCom** [dotnet/roslyn#59118]
We added the concept of a ReloadableType in .NET 6, this works in CoreCLR scenarios today but isn't supported by Mono at this time. While we hope to bring this support to .NET 7, in the meantime this is not reported as a "rude edit" by tooling because it is not a known capability to evaluate and that's a bug we should resolve.

Suggested Fix:

1. Add a Hot Reload capability that checks if ReloadableTypes are supported and for Mono in .NET 6 report that it is not
2. If detected that the user is trying to edit a ReloadableType when support is missing, the tooling (VS + `dotnet watch`) should report a rude edit through the regular mechanism
3. In .NET 7 when this support is added to Mono, the capabilities should be updated to properly reflect this support

**Comment by tmat** [comment]
@davidwengier 
We have (`AddNewTypes`)[https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/EditAndContinue/EditAndContinueCapabilities.cs,4a4dbc900a077102,references] capability. I am not sure if it correctly blocks reloadable types

**Comment by davidwengier** [comment]
The code is there (https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs#L2560-L2573) and there are tests that cover it: https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs#L1516

@LyalinDotCom will mono get general "add new types during hot reload" support for .NET 7? If so I don't think we need to do anything here. If there is something specific to reloadable types that they're adding, that won't enable adding new types in general, then we would need a new capability.

Alternatively, is there a known repro that doesn't report a rude edit for this now? Could be something else going on.

**Comment by tmat** [comment]
@davidwengier Cool. Thanks for checking.

**Comment by lambdageek** [comment]
> will mono get general "add new types during hot reload" support for .NET 7?

I'm exploring if that's viable.  So far the answer is looking like "yes".  (There are annoying implementation complications for instance fields, and I suspect I will hit more "annoying, but not unsolvable" problems around generics, but no showstoppers as yet).

**Comment by davidwengier** [comment]
If it helps, its pretty easy on the Roslyn side to change the meaning of `AddNewTypes` to give it more nuance, so mono could report `AddNewNonGenericType` for example, and we wouldn't have to make any changes to core CLR, same as what we do for `AddDefinitionToExistingType` currently: https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/EditAndContinue/EditAndContinueCapabilities.cs,73

**Comment by davidwengier** [comment]
Cleaning up 17.2 bugs, so going to close this out. Feel free to comment or reopen if we need to do something here.
