### ISSUE TITLE
Async/await are not highlighted inside a razor file when clicked

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59120]
Normal C#:
![devenv_0WytHg5mC4](https://user-images.githubusercontent.com/70431552/150510448-c89ed5cb-e150-4f61-8eb8-da346c33e410.gif)

Razor file:
![devenv_QM8HNG1QpJ](https://user-images.githubusercontent.com/70431552/150510469-90d39db9-ce2c-48e9-9ed5-ba1bf2ea91bb.gif)

**Comment by dibarbet** [comment]
Cause:
In LSP we look at the IDocumentHighlightsService to find the highlighted spans.  However, keyword highlights are provided by an entirely separate IHighlighter service (https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/Implementation/KeywordHighlighting/AbstractKeywordHighlighter.cs).

Currently determining if the IHighlighter service can be unified, or if we just need to call both in LSP.
