### ISSUE TITLE
FixAllProvider doesn't support more than two fixes with some identical insertions

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#59130]
**Version Used**: 4.1.0-3.22075.3, but the bug is also present in `main`:

https://github.com/dotnet/roslyn/blob/0761a364b9ceb9704634b09ad8d52ee52cb74037/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/TextChangeMerger.cs#L193-L194

*Steps to Reproduce**:

1. Write an analyzer that emits a diagnostic on some expression, like a function call.
2. Write a code fix that makes two changes; Change the expression with the diagnostic and also change the enclosing method (such as by adding the `unsafe` modifier to the method). It's important that the change to the enclosing method is the same no matter the expression with the diagnostic.
3. Run the "Fix all in Document" action or run the FixAllProvider from code manually over a document with three separate instances of this diagnostic in the same method.

**Expected Behavior**:

All three code fixes are applied to fix the three diagnostics

**Actual Behavior**:

Only the first two code fixes are applied. The third code fix is silently dropped because one of the two changes in the code fix intersects with two other (identical) changes (one each from the other code fixes for the other diagnostics).

https://github.com/dotnet/roslyn-analyzers/pull/5822 hits this bug in the test for the `MarshalSizeOf` code-fix test.

**Comment by CyrusNajmabadi** [comment]
I think in this case writing a custom fixallprovider would be desirable.

**Comment by jkoritzinsky** [comment]
I can write a custom FixAllProvider, but I still feel that this should be fixed. The provided steps above work when there are only 2 code fixes that have an identical span since the if block above and the equality check handle that case.

**Comment by sharwell** [comment]
@jkoritzinsky The BatchFixAllProvider is inefficient and not intended to work as a single pass for all scenarios. The recommended solution here is to rewrite the code fix to support [`DocumentBasedFixAllProvider`](https://github.com/dotnet/roslyn/blob/0761a364b9ceb9704634b09ad8d52ee52cb74037/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs), which is orders of magnitude faster and guaranteed to not run into the problem described above.

**Comment by CyrusNajmabadi** [comment]
Note: you can also use [FixAllProvider.Create](https://github.com/dotnet/roslyn/blob/0761a364b9ceb9704634b09ad8d52ee52cb74037/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs#L54) to make this simpler as well (it's the same tech as DocumentBasedFixAllProvider).
