### ISSUE TITLE
MSBuild warnings should fail Jenkins jobs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5913]
The Jenkins job scripts need to be changed such that MSBuild warnings (warning MSB) turn into errors.  These warnings range from innocuous to serious but today go completely unnoticed as they occupy a few lines in the thousands of lines our tests output.  These need to be turned into errors so we can evaluate and fix them at the time they are created.

**Comment by davkean** [comment]
I believe @amcasey just added one.

In the future, they are easier to add, visit http://dotnet-ci.cloudapp.net/failure-cause-management/ and click Create New.

**Comment by davkean** [comment]
Oh, nevermind, misread this. 

This is turning "warnings" -> "errors", not MSBuild errors -> Failure cause. My mistake.

**Comment by davkean** [comment]
Not just jenkins jobs - this should fail *all* builds

**Comment by davkean** [comment]
We could probably achieve this with a build logger. Problem is, I can't see a way to always enabling it (you'll want this to occur in VS and via the command-line on dev boxes as well).

I think we should reach out to MSBuild and either ask for a feature to enable this - or just do the feature work ourselves for them.

**Comment by davkean** [comment]
Resolved with: https://github.com/dotnet/roslyn/commit/efd3c5d6038e932a77a89fcc99dabaeffbbdc1f1
