### ISSUE TITLE
WorkCoordinatorWorkspace.Dispose has flaky asserts

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5915]
Consider the code here:

```
protected override void Dispose(bool finalize)
{
    base.Dispose(finalize);
    Assert.False(_workspaceWaiter.HasPendingWork);
    Assert.False(_solutionCrawlerWaiter.HasPendingWork);
}
```

The types being tested for HasPendingWork are shared amongst all runs of the unit test on the same thread.  This is due to how the MEF caching behavior works.  Hence this test isn’t checking if this test left any pending work, it’s checking if this test or any test before it left pending work.  Given the current flaky behavior it seems some of the tests are not properly shutting down their async resources and hence triggering this test in a flaky manner.   

This is causing our tests to behave in a flaky manner and hence are being disabled.

**Comment by heejaechang** [comment]
@jaredpar can you tell me which tests are disabled?

**Comment by jaredpar** [comment]
@heejaechang I didn't disable any tests with this change, I just disabled this specific assert because it can't be made correctly with the current architecture of the tests.

**Comment by heejaechang** [comment]
this is already fixed.
