### ISSUE TITLE
IOperation tree change for target-typed new is breaking analyzers in the wild

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#59171]
**Version Used**: 17.1 Preview 4

The change in behavior described here is caused by 39c57377c6075b2ee9ae343d293a5ce3b368e6bc.

**Steps to Reproduce**:

1. Write an IOperation analyzer for field initializers based on the Roslyn 4.0 IOperation tree, such as this one:

    https://github.com/dotnet/roslyn-analyzers/blob/50d35c8d1c50a8e4dc6d0327be904495c23c5e19/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs#L390-L403

2. Update to VS 17.1 Preview 4, which includes commit 39c57377c6075b2ee9ae343d293a5ce3b368e6bc

**Expected Behavior**:

The IOperation tree does not change in ways that break the analyzer.

**Actual Behavior**:

The IOperation tree changes. Analyzers must now know and support _both_ of these trees, and create different test projects for Roslyn 4.0 and 4.1 in order to write tests for both outcomes.

**Comment by AlekseyTs** [comment]
@sharwell Please provide details about the what change in IOperation tree breaks the analyzer. Why an analyzer have to break? 

> Analyzers must now know and support both of these trees

If I remember correctly, the change was adding a conversion for target typed new nodes, the conversion that is part of the language specification. I think it is reasonable to assume that analyzers would be written in a way that deals with conversion nodes.

**Comment by AlekseyTs** [comment]
> Analyzers must now know and support both of these trees, and create different test projects for Roslyn 4.0 and 4.1 in order to write tests for both outcomes.

Also, I am not able to provide any meaningful response to the statement above without the following information:
- What exactly the analyzer is trying to accomplish by examining IOperation tree?
- How exactly it is trying to accomplish that?
- Why it is trying to accomplish the task this way? Are there relevant references to documentation or specification, etc. ?

**Comment by sharwell** [comment]
> What exactly the analyzer is trying to accomplish by examining IOperation tree?

The analyzer is looking for a `IFieldInitializerOperation` whose `Value` is a `IObjectCreationOperation` with specific characteristics.

> How exactly it is trying to accomplish that?

The link shows the exact pattern it was attempting to match.

> I think it is reasonable to assume that analyzers would be written in a way that deals with conversion nodes.

It could go either way, but if the node isn't providing new value to analyzers that cannot be otherwise determined, it would be much better to preserve the original shape. The `IOperation` tree isn't (and doesn't need to be) a full-fidelity match to the language specification after lowering.

**Comment by AlekseyTs** [comment]
Implicit conversions in IOperation tree can easily be detected by examining ```IOperation.IsImplicit``` property.

**Comment by CyrusNajmabadi** [comment]
I would far prefer the IOp tree be high fidelity.  If there's a conversion there from teh compiler, then put a conversion in teh tree.  I don't want us to get into the expr-tree pit where we can't change anything because we're too worried about breaking stuff.

Finally, i'm also curious if there are cases where this analzyer was broken before anyways (for example, if the conversion might appear for other normal use cases).  This change may have exacerbated an underlying weakness in the analyzer that was already present.

**Comment by 333fred** [comment]
Adding this to the list for API review to discuss tomorrow.

**Comment by 333fred** [comment]
## API Review

This conversion node was added to the tree to allow the compiler to better do nullability analysis, but it's also semantically correct to have. The specification states that there exists a conversion from target-typed new nodes to the final type, which is what is now reflected by the IOperation tree. We should definitely look into infrastructure improvements in the roslyn-analyzers repo to ensure that future changes get caught earlier, but in general this change is in line with what we expect to happen with the IOperation tree as the language grows.
