### ISSUE TITLE
Re-enable MakeConst tests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5918]
The MakeConst VB and C# tests in our samples directory both have no tests in them.  This means xunit runs very fast on the assemblies and appears to expose the following bug in EventListener

https://github.com/dotnet/corefx/issues/3793

This is causing our Jenkins runs to incorrectly fail.  As a result I'm taking them out of the runs for now.  These projects should either be updated to have tests or simply deleted altogether.

**Comment by davkean** [comment]
Moving this to compilers, as they own it, not infrastructure.

**Comment by davkean** [comment]
Oh, no sorry, these are samples. Who owns samples?
