### ISSUE TITLE
Consider negating options with non-default(T) default values

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59195]
The default values of some options in record structs that represent options (e.g. `CompletionOptions`) are not `default(T)`, where `T` is the type of the option. For example, `true` insted of `false`.
This is inconvenient since `default(ComplationOptions)` != `ComplationOptions.Default` and may result in bugs if `default(ComplationOptions)` is used.
It would be better to negate the options that have non-`default(T)` default value.

For example, instead of 
```
internal readonly record struct CompletionOptions(
        bool TriggerOnTyping = true,
        bool TriggerOnTypingLetters = true,
        bool? TriggerOnDeletion = null,
        bool TriggerInArgumentLists = true,
        bool IsExpandedCompletion = false,
        EnterKeyRule EnterKeyBehavior = EnterKeyRule.Default,
        SnippetsRule SnippetsBehavior = SnippetsRule.Default,
        bool HideAdvancedMembers = false,
        bool ShowNameSuggestions = true,
        bool? ShowItemsFromUnimportedNamespaces = null,
        bool UnnamedSymbolCompletionDisabled = false,
        bool TargetTypedCompletionFilter = false,
        bool TypeImportCompletion = false,
        bool ProvideDateAndTimeCompletions = true,
        bool ProvideRegexCompletions = true,
        int TimeoutInMillisecondsForExtensionMethodImportCompletion = 500,
        bool FilterOutOfScopeLocals = true,
        bool ShowXmlDocCommentCompletion = true);
```

we could have
```
internal readonly record struct CompletionOptions(
        bool DisableTriggerOnTyping = false,
        bool DisableTriggerOnTypingLetters = false,
        bool? TriggerOnDeletion = null, // what's the meaning of null?
        bool DisableTriggerInArgumentLists = false,
        bool IsExpandedCompletion = false,
        EnterKeyRule EnterKeyBehavior = EnterKeyRule.Default,
        SnippetsRule SnippetsBehavior = SnippetsRule.Default,
        bool HideAdvancedMembers = false,
        bool HideNameSuggestions = false,
        bool? ShowItemsFromUnimportedNamespaces = null,
        bool UnnamedSymbolCompletionDisabled = false,
        bool TargetTypedCompletionFilter = false,
        bool TypeImportCompletion = false,
        bool HideDateAndTimeCompletions = false,
        bool HideRegexCompletions = false,
        int TimeoutInMillisecondsForExtensionMethodImportCompletion = 0, // we'd need to redefine meaning of 0
        bool IncludeOutOfScopeLocals = false,
        bool HideXmlDocCommentCompletion = false);
```

Note that changing the meaning of the properties of the record struct does not need to affect the option storage. When reading the option default from storage we can adjust (negate) the value as needed.

**Comment by sharwell** [comment]
I believe you could also add a parameterless constructor that delegates to the one shown here.

**Comment by tmat** [comment]
Good idea. `default(CompilationOptions)` would still be incorrect though, right?

**Comment by tmat** [comment]
Yeah, confirmed that `default(S)` compiles to `initobj` which does not invoke parameterless ctor.

**Comment by sharwell** [comment]
`default(S)` wouldn't work, but `new S()` would work.

**Comment by CyrusNajmabadi** [comment]
Alternative, maybe these shouldn't be structs.  I'm not sure if we get value from that here TBH.  I'd be ok with a bog standard record-class.  This would allow easy passing of null (which features can replace with XXXOptions.Default).  It also would be fine for perf as features generally instantiate around 1 (maybe 2) of these per full op they do.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
