### ISSUE TITLE
Test plan for "checked operators"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#59196]
Proposal: https://github.com/dotnet/csharplang/issues/4665

## Productivity
- [ ] QuickInfo should show whether a checked or regular operator is used

**Comment by AlekseyTs** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/59458

**Comment by jcouv** [comment]
It would have been better to close the other issue instead, as the present issue is the one linked from feature status page.
