### ISSUE TITLE
Public API analyzer reports an error in VS that doesn't show up during command line builds for a property getter initialized using new expression bodied member syntax

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/roslyn#592]
I am running into the following error when I open Roslyn.sln in VS. But the solution builds fine on the command line.

Error	 *RS0017*	Symbol 'Microsoft.CodeAnalysis.CSharp.Syntax.AnonymousMethodExpressionSyntax.Block.get' is part of the declared API, but is either not public or could not be found	CSharpCodeAnalysis		1

The error has no location. But it is referring to a the getter of a property that is initialized using the new expression bodied member syntax -

![image](https://cloud.githubusercontent.com/assets/10579684/6236120/85e8892e-b69c-11e4-9dc2-48fb929a96ff.png)

Given that the error is reported in VS and not on the command line, I suspect this is a bug in one of the analyzer drivers (probably the VS analyzer driver - looks like the analyzer isn't being called for the Block.get symbol when running inside VS).

**Comment by mavasani** [comment]
Should be fixed with #911
