### ISSUE TITLE
Built-in VB UnboundIdentifiersDiagnosticAnalyzer crash

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#5920]
Here's the screenshot of the error message:

![unbound](https://cloud.githubusercontent.com/assets/3316258/10466077/1a2f6eca-71a7-11e5-8dc8-28bff7d38568.png)

I saved a copy of the project at the moment it gave this error. Put it at \\ddfiles\team\Public\lwischik\repro\unbound-identifiers.zip

**Comment by lgolding** [comment]
Per @Srivatsn and @mavasani, this is an IDE-only analyzer.
