### ISSUE TITLE
Unable to use nuget package with native binaries in Source Generator

### ISSUE THREAD

**Issue by flo-everett-xero** [dotnet/roslyn#59219]
Hi,

I'm trying to write a source generator that checks out a git project. I understand that when referencing a nuget package from a source generator, you need to add a `TargetPathWithTargetPlatformMoniker` step, like
```xml
<ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.26.2" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>
  
  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PKGLibGit2Sharp)\lib\netstandard2.0\*.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
```
This works fine with managed dlls, however the LibGit2Sharp package also has a dependency on LibGit2Sharp.NativeBinaries, which contains all the native binaries it needs to actually execute git commands. 

Trying the naive approach of
```xml
<ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.26.2" GeneratePathProperty="true" PrivateAssets="all" />
    <PackageReference Include="LibGit2Sharp.NativeBinaries" Version="2.0.306" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PKGLibGit2Sharp)\lib\netstandard2.0\*.dll" IncludeRuntimeDependency="false" />
      <TargetPathWithTargetPlatformMoniker Include="$(PKGLibGit2Sharp_NativeBinaries)\runtimes\**\*" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
```
doesn't work - I get an error on each native binary saying `PE image doesn't contain managed metadata.`

I also attempted to directly copy the binaries into the output directory with a `<Content Include="">` step, however although thenative binaries were successfully copied, the references to them were still broken - I got a "could not find assembly" error

Any help, guidance, or fixing of this issue would be greatly appreciated!

**Comment by jaredpar** [comment]
> I'm trying to write a source generator that checks out a git project.

This is against the rules of source generators. They should never be making on disk changes directly. Doing so violates both the rules of generators and the correctness of overall builds. 

Closing as this is not a supported action for generators.
