### ISSUE TITLE
Adjust generic null-checking codegen for clarity

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#59223]
Relates to the following incomplete item in #36024:
> * check for unconstrained `T` does not box when `T` is a nullable value type (include a `ThrowIfNull<T>(T value, string parameterName)` helper method?)

cc @stephentoub 

Consider the following null check:
```cs
public class C {
    public void M<T>(T item!!) {
    }
}
```

It compiles to this IL:
```il
    .method public hidebysig 
        instance void M<T> (
            !!T item
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 17 (0x11)
        .maxstack 8

        // sequence point: hidden
        IL_0000: ldarg.1
        IL_0001: box !!T
        IL_0006: ldstr "item"
        IL_000b: call void '<PrivateImplementationDetails>'::ThrowIfNull(object, string)
        IL_0010: ret
    } // end of method C::M
```

The concern with this codegen is that it depends on `ThrowIfNull` actually getting inlined in order to elide the boxing, which isn't guaranteed to happen, and is not easy to glean by reading the IL. The suggestion is to instead use a codegen strategy equivalent to one of the following:

```cs
// do the null-check inline and the throw via helper
if (item is null) { <PrivateImplementationDetails>.Throw("item"); }

// emit a generic ThrowIfNull helper and call it
<PrivateImplementationDetails>.ThrowIfNull<T>(item, "item");
```

It sounds like adding the generic helper is preferred but either one would be fine.

**Comment by jcouv** [comment]
Closing as the feature is no longer applicable.
