### ISSUE TITLE
Null-checking nullable param warning should be relaxed

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#59226]
There are some cases where null-checking a nullable parameter is useful:

**Overriding a method with a nullable parameter and rejecting null input**
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/5833655/152232709-e29a47f1-a160-4f66-9083-db0f8421c743.png)

**Null-checking a nullable parameter when the postcondition guarantees non-nullability**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/5833655/152232746-ddeebb3d-e395-41c5-ac30-d1ce79c6f396.png)

In both these scenarios, we should either avoid issuing a warning on '!!', or avoid offering the code fix which introduces '!!'.

cc @stephentoub

**Comment by CyrusNajmabadi** [comment]
>Overriding a method with a nullable parameter and rejecting null input

this woudl seem to violate teh contract.  Parameter should not be covariant.   right?

**Comment by stephentoub** [comment]
>> Overriding a method with a nullable parameter and rejecting null input

> this woudl seem to violate teh contract. Parameter should not be covariant. right?

It does, and the annotation is incorrect. I wouldn't change the warning for that specific case; I was just highlighting some examples to Rikki.

The second is more interesting... that pattern appears in multiple places.  As I mentioned to Rikki, I've been changing those to try to delete the helper entirely, but it's annoying that there's a warning introduced for something that's actually the recommended pattern for how to do this today.

**Comment by RikkiGibson** [comment]
I would be fine with doing nothing in the first scenario (code fix continues to change it to '!!', a warning is issued).

In the second scenario I think we can say that we shouldn't issue a warning due to presence of `[NotNull]`. We should also ensure that `[DisallowNull] object? x` produces no warnings--could see this being meaningful in `void Clear([DisallowNull] ref object? obj)`

**Comment by CyrusNajmabadi** [comment]
> The second is more interesting...

Yup.  I have no issue with the second.  It seems unfortunate for us to have a warning there when i think the attribute and the `!!` are in agreement :)

**Comment by RikkiGibson** [comment]
I found some relevant notes for [scenario 1](https://github.com/dotnet/csharplang/blob/main/meetings/2019/LDM-2019-01-14.md#generating-null-check-for-parameter):

> A: Yes. In the case where a user is warned about violating the OHI contract, the correct decision is to silence the OHI warning, keeping consistency between the implementation and signature of the method.

I think this reinforces that there's nothing we need to change in that scenario.
