### ISSUE TITLE
Repo Survey (2022 Edition)

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#59221]
A couple years ago we surveyed you, the members of the community, in this repo to learn how we were doing as maintainers. 

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new, please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:
https://www.surveymonkey.com/r/8QTQTGJ?Source=roslyn

**Comment by DoctorKrolic** [comment]
Are [dotnet/razor-tooling](https://github.com/dotnet/razor-tooling) and [dotnet/razor-compiler](https://github.com/dotnet/razor-compiler) not part of the survey or theн are just forgotten to be added?

**Comment by danmoseley** [comment]
Survey is now closed and we'll dig through your feedback. Thanks everyone that responded.

**Comment by danmoseley** [comment]
@DoctorKrolic I missed them as I do not work with them and didn't know about them. I have made a note for next time.
