### ISSUE TITLE
Fix the bug of escape code inside regex keep causing ide to crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59249]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Fix-the-bug-of-escape-code-inside-regex-/1650955)._

---
[regression] [worked-in:not sure]
In vb.net at least, not sure about other language ep crashing when I type the escape character, 
for example I type escape character for bracket \( then it crashed. 
I am so upset each time when there is a \ inside the regex it confirms crash. I do not wish to declare a new string variable if possible.

```
Regex.Replace(test, "\(", "")
```

---
#### Feedback Bot on 2/2/2022, 07:11 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by CyrusNajmabadi** [comment]
I repro no crash here:

![image](https://user-images.githubusercontent.com/4564579/152419131-46c44f55-c8c4-43f0-bf9a-21a76a15cd38.png)

I've tried typing this in all sorts of forms, and it seems to work just fine.
