### ISSUE TITLE
null exception in compilation - Microsoft.CodeAnalysis.CSharp.UnitTests.InteractiveUsingTests.ConsumePreviousSubmissionUsings_Valid

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#5924]
look at the below log.

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/443/

**Comment by amcasey** [comment]
I believe this is a dup of https://github.com/dotnet/roslyn/issues/5927.

**Comment by amcasey** [comment]
@heejaechang Can you please verify that this is/was a dup?

**Comment by heejaechang** [comment]
@amcasey log is already gone. so can't verify. I will close it since no info is available now.

**Comment by heejaechang** [comment]
@amcasey ah, you already closed :)

**Comment by amcasey** [comment]
@heejaechang If you agree that this issue is a dup of #5927, you can just add the "Verified" label and unassign yourself.  If you disagree, please reopen.
