### ISSUE TITLE
IntelliSense is not suggesting generate method option

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59251]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-is-not-suggesting-generate-/1649102)._

---
I'm using latest version of VS2022.
When I use IntelliSense it's not showing generate method option when method is async type.
Please refer below screenshot. I'd like to see **generate Get() method option** with return type Task<object>.
! [image.png] (https://aka.ms/dc/image?name=Bbb6613b5da3f4aebb1cb0da61a19db11637788912337447480_20220127-201034-image.png&tid=bb6613b5da3f4aebb1cb0da61a19db11637788912337447480)

---
#### Feedback Bot on 1/27/2022, 10:34 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
I don't repro this at all.  We'll need more info from the customer here (including full repro):

![image](https://user-images.githubusercontent.com/4564579/152440767-a953edd5-3ba2-4b68-90ec-10ec1fb1fcdd.png)
