### ISSUE TITLE
'Implement Interface' quick actions using defined global using

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59250]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Implement-Interface-quick-actions-usin/1650760)._

---
When using `Implement Interface` quick actions to implement this type
```csharp
global using JobId = System.String;
global using IdentityId = System.String;

public class Job : IStandardEntity<JobId, IdentityId?> { }
```
It will generate something like this.
```
public class Job : IStandardEntity<JobId, IdentityId?>
{
    public string Id => throw new NotImplementedException();
    public string? CreatorId => throw new NotImplementedException();
}
```

I think it would be great if it keeps the type name `JobId` and `IdentityId` instead of using the `string` directly (global using).
What I'm thinking, it should generate the code like bellow instead.
```
public class Job : IStandardEntity<JobId, IdentityId?>
{
    public JobId Id => throw new NotImplementedException();
    public IdentityId? CreatorId => throw new NotImplementedException();
}
```
And also, I think this idea will be applicable for all quick actions for generic type.
Thanks,

---
#### Feedback Bot on 1/30/2022, 06:06 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by sharwell** [comment]
📝 It's critical that the user add tests demonstrating that the change is not order-dependent, and is not capable of producing the following code (which has the same underlying semantics as the desired result):

```csharp
public class Job : IStandardEntity<JobId, IdentityId?>
{
    public IdentityId Id => throw new NotImplementedException();
    public JobId? CreatorId => throw new NotImplementedException();
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
