### ISSUE TITLE
null exception in compilation - Microsoft.CodeAnalysis.CSharp.UnitTests.InteractiveUsingTests.AliasHiding

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#5925]
test found another null exception.

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/445/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/InteractiveUsingTests/AliasHiding/

**Comment by amcasey** [comment]
I believe this is a dup of https://github.com/dotnet/roslyn/issues/5927.
