### ISSUE TITLE
Make OptionKey serializable so that integration tests can pass it between processes

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59267]
Tracks TODO in WellKnownGlobalOptions.cs

**Comment by sharwell** [comment]
This is not necessary. Only the legacy integration tests suffer from this issue and the new integration tests [already support `OptionKey`](https://github.com/dotnet/roslyn/blob/f91d6a88d1a08f849a3820d795e5948dbd10d3f8/src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicNavigationBar.cs#L107-L108).
