### ISSUE TITLE
Rule listed as "csharp_style..." can change functionality

### ISSUE THREAD

**Issue by EliKlein** [dotnet/roslyn#59263]
This rule is a little bit off from what it should be.

The [page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator) on the null-coalescing operators (?? and ??=) says that they can replace the "is" operator:

> Beginning with C# 8.0, you can use the ??= operator to replace the code of the form
> ```
> if (variable is null)
> {
>     variable = expression;
> }
> ```
> with the following code:
> ```
> variable ??= expression;
> ```

However, IDE0016 refers to the "==" operator. That operator is sometimes overloaded, and can behave differently from "is". This rule is supposed to be a style rule, and as such should not be able to change the functionality of the code when applied.

As an example of this mattering: In Unity in particular, the "GameObject" class has some odd behavior with "==" equality checks and null (sometimes behaving as if the object is null when "is" would not see it as null). I believe the rule should be to replace "is" checks with null-coalescing exception throws, instead of "==" checks. Or the rule should also mention that it only applies to types which do not overload the equality operator.

At the very least, whatever tool(s) happen(s) to be running in my code editor (I think OmniSharp and/or Roslyn?) can't detect that the object type I'm comparing overloads the "==" operator. I know _that_ escapes the scope I should be aiming for with opening an issue in this particular spot, but I figure it might be important context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d81a25a-3d7c-48e7-b354-57f244941ab1
* Version Independent ID: b8c401f4-b4b3-089e-95ab-e468df19931b
* Content: [IDE0016: Use throw expression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0016)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0016.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0016.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CyrusNajmabadi** [comment]
I feel that an object htat overloads `== null` to have different semantics than `is null` playing with fire and really shouldn't do things that way.  It's just going to lead to all sorts of problems.  If that API insists on doing that though, the solution is easy, just supress the diagnostic for that line.

**Comment by CyrusNajmabadi** [comment]
> Add a WarningAnnotation that this can change semantics.

I would not do this.  It would be a needless warning in practically all scenarios.  Considre every string that uses `== null`.  That is totally fine to use `is null`.  Indeed, i can't really understand why this GameObject type would *not* have those semantics, it seems to a pit of confusion.

**Comment by CyrusNajmabadi** [comment]
> Special case Unity

I'm not hugely opposed to this if it simple.  But i really feel like unity shoudl fix things here.

**Comment by EliKlein** [comment]
> I feel that an object htat overloads `== null` to have different semantics than `is null` playing with fire and really shouldn't do things that way. It's just going to lead to all sorts of problems.

This is true. However, I have heard that Unity doesn't exactly want to fix the problem, because it's going to end up affecting a *lot* of code if they do it differently. So I personally err towards assuming it's not going to change (if only for a long while).

One thing that might help a little bit is to change the example listed on the page from `s == null` to `s is null`. On the other hand, as the person who brought up this issue, I definitely have a bias, since I know the context here. I wouldn't be able to tell you if that would make things more confusing for anyone, or have some other kind of problem.

**Comment by CyrusNajmabadi** [comment]
Closing as won't-fix/by-design.  See conversation in https://github.com/dotnet/roslyn/issues/62765.
