### ISSUE TITLE
[LSP] Experiment with LSP client on VSMac

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#59265]
@gundermanc has been prototyping lsp client support on VSMac.

We've managed to make roslyn lightup with a few small changes (https://github.com/dibarbet/roslyn/commit/83cbd3e7510589d4b4f16d5ebfa08c99568c87bd) but these need to be expanded a bit to be more robust

1.  We need to ensure the LSP feature flag option is settable in the tools options equivalent for VSMac
2.  The LSP feature flag option must be respected by existing VSMac entry points so the appropriate command handlers turn themselves off and allow LSP to take over.
3.  We need an implementation of the ILspWorkspaceRegistrationService for VSMac.
4.  We need an implementation of the ILspLogger for VSMac.
5.  Additional work to lightup razor server (unknown).

I'm not exactly sure where the code changes for these should live.  Reading the options will probably need to be handled on the VSMac side.  Implementations of the services probably also need to be on vsmac?

cc @KirillOsenkov @davidwengier

**Comment by gundermanc** [comment]
**cc: ** @KirillOsenkov, @sandyarmstrong.

Thanks @dibarbet! I'm going to dig a bit more into your branch and see what is/isn't working. Top priority is costing this exercise.

**Comment by gundermanc** [comment]
Alright looks like the following are at least partially working:

- Semantic tokens
- Hover
- Document highlight

Initially discovered issues:

- Every reported semantic token seems to be appended with ' name'. e.g.: 'class' is reported as 'class name', so it lights up, but is colored incorrectly on Mac. @allisonchou any idea why this was done? Dropping it makes everything happy again.
```csharp
            if (tokenTypeName?.EndsWith(" name") ?? false)
            {
                tokenTypeName = tokenTypeName.Replace(" name", string.Empty);
            }
```

![image](https://user-images.githubusercontent.com/5387680/152462299-fb0415b3-1581-49fb-91a0-bfe37971779c.png)

- Various MEF parts, like quick info, don't shut off and we end up with duplicates

![image](https://user-images.githubusercontent.com/5387680/152462366-be1ac739-5b62-410c-99aa-7c196451d856.png)

**Comment by KirillOsenkov** [comment]
Hey folks, as an experiment, I've just tried out updating to Roslyn 17.1 outside of Visual Studio, and seeing these MEF errors:
https://gist.github.com/KirillOsenkov/97a3443dbb6c72febb45c8d669ea5ba4

We need a cross-plat or exported definition of:
 * `ICodeDefinitionWindowService`
 * `RequestDispatcherFactory`
 * `ILspLoggerFactory`
 * `LspWorkspaceRegistrationService`
 * `DefaultCapabilitiesProvider`

**Comment by KirillOsenkov** [comment]
OK, regarding those 5 types:

Need to be implemented in VSMac:
 * `ICodeDefinitionWindowService`
 * `ILspLoggerFactory`
 * `LspWorkspaceRegistrationService` (copy paste https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/LanguageClient/VisualStudioLspWorkspaceRegistrationService.cs,c3b2436599714213)

Fix by adding Microsoft.CodeAnalysis.LanguageServer.Protocol to MEF in VSMac:
 * `RequestDispatcherFactory`
 * `DefaultCapabilitiesProvider`

**Comment by dibarbet** [comment]
`ICodeDefinitionWindowService` is interesting - what in LSP ends up importing this?  I wouldn't expect that it is required but could be wrong

**Comment by KirillOsenkov** [comment]
If you look in the MEF error in the gist it seems to be the DefinitionContextTracker, or you can find references on https://sourceroslyn.io or http://index
