### ISSUE TITLE
Fix flaky interactive tests

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5927]
A couple of interactive tests have shown up as being flaky in the lab.  Disabling them for now to keep the lab green.

**Comment by amcasey** [comment]
I'm doing lab runs here: https://github.com/dotnet/roslyn/pull/5921

**Comment by amcasey** [comment]
My initial guess is that it's possible for us to remap an alias before its target has been resolved (and xunit is suppressing asserts?).

**Comment by amcasey** [comment]
There's still a skipped test.

**Comment by amcasey** [comment]
Unskipping: https://github.com/dotnet/roslyn/pull/9897

**Comment by amcasey** [comment]
Unskipped: https://github.com/dotnet/roslyn/commit/7eedb32c03262f0de125b1d34487602df638e01e
