### ISSUE TITLE
The name does not exist in the current context

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#59275]
### Discussed in https://github.com/dotnet/roslyn/discussions/59274

<div type='discussions-op-text'>

<sup>Originally posted by **foxesknow** February  4, 2022</sup>
When using a `switch` expression to match types I've noticed something strange. This code:

```
List<string> items = value switch
{
    string i  => new(){i},
    IEnumerable<string> sequence => sequence.ToList(),
    _ => throw new Exception()
};
```

Generates an error `error CS0103: The name 'i' does not exist in the current context`

Changing the `new()` to `new List<string>()` fixes the issue:

```
List<string> items = value switch
{
    string i  => new List<string>(){i},
    IEnumerable<string> sequence => sequence.ToList(),
    _ => throw new Exception()
};
```

Is this a bug?

At first I thought it was the `new()` causing the problem, but this works:
```

List<string> items = value switch
{
    string i  => new(){},
    IEnumerable<string> sequence => sequence.ToList(),
    _ => throw new Exception()
};
```
</div>

**Comment by 333fred** [comment]
@foxesknow I've converted this to an issue on roslyn.

**Comment by alrz** [comment]
Looks like a dup of https://github.com/dotnet/roslyn/issues/54193

**Comment by 333fred** [comment]
Indeed, this does not reproduce on the latest main: https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGYrPAAi1IBYBuC62gOgBlYBHJo4zgM4IAPLTwA+KlAQBTMAKoBeKgAoA8sABWMgMYIAlDFQAbY1QEB3aToAWxAN7EqzmqWpRniyTBkWV++ygAXzgnF1oAZlE3SQEZLlQZGB0ZJVj4xOSZVgAVAHtBBH9QohcqAH00qgQbZDyLKh8GgFEADxSABwQoPJh/YiCGIA. Thanks @alrz, closing as a duplicate of https://github.com/dotnet/roslyn/issues/54193.
