### ISSUE TITLE
Quick Actions "Use pattern matching" after #endif directive adds extra #endif

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59289]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Actions-Use-pattern-matching-aft/1651108)._

---
[severity:It bothers me. A fix would be nice]
1. Create a new Class Library project with .NET 6 as the target framework.
2. In Class1.cs, paste the following code:

```
namespace ClassLibrary1
{
    public class Class1
    {
        public void Method1()
        {
            object original = new Class1();

#if DEBUG
            var x = 0;
#endif

            Class1? converted = original as Class1;

            if (converted == null)
            {
                converted = new Class1();
            }
        }
    }
}
```
3. On the `Class1? converted = original as Class1;` line, select the `Use pattern matching` Quick Action.
4. Observe that the code now has an extra `#endif`, which creates an error:
```
namespace ClassLibrary1
{
    public class Class1
    {
        public void Method1()
        {
            object original = new Class1();

#if DEBUG
            var x = 2;

#endif
#endif      // This extra #endif creates a `CS1028: Unexpected preprocessor directive` error.


            if (original is not Class1 converted)
            {
                converted = new Class1();
            }
        }
    }
}
```

---
#### Feedback Bot on 2/2/2022, 08:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/65032
