### ISSUE TITLE
IDE0062 code fix (local function can be static) removes "unsafe" keyword

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#59286]
**Version Used**: 

VS2022 17.1.0 preview 4
Compiler version: '4.1.0-3.22062.11 (cc0d213b)'. Language version: 10.0

**Steps to Reproduce**:

1. dotnet new console
2. `program.cs` (top level program)
    ````
    A();
    unsafe void A()
    {
    }
    ````

![image](https://user-images.githubusercontent.com/509220/152591660-06e645a0-a582-4fa9-a5d1-b9fe7e4bdd88.png)

**Expected Behavior**:

`unsafe static void A()`

**Actual Behavior**:

`static void A()`

**Comment by Youssef1313** [comment]
Bug is likely here:

https://github.com/dotnet/roslyn/blob/78c556a916fe4d31be864ad856e1e5d28c946348/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1454-L1457

**Comment by meziantou** [comment]
@Youssef1313 Thanks for pointing the right file! I've submitted a PR https://github.com/dotnet/roslyn/pull/59297
