### ISSUE TITLE
Inline parameter hint is off when incorrect number of arguments is passed

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59317]
![image](https://user-images.githubusercontent.com/41759/152658268-30c5ea99-92b8-4122-9fb3-7b15268ac4d1.png)

**Comment by CyrusNajmabadi** [comment]
is this incorrect?  it seems somewhat reasonable?  We could have the feature disable in the case of a non-exact match.

**Comment by tmat** [comment]
Actually, the above is reasonable. Wrong example. When I saw this in real code the types and actually named arguments didn't match:

![image](https://user-images.githubusercontent.com/41759/152664886-b2da34e5-5938-4517-98d4-c5bf98cbf812.png)

**Comment by CyrusNajmabadi** [comment]
Ah yeah.  at the very least, we should not add inline hints for parameters that already have a named-argument :)
