### ISSUE TITLE
Go to member doesn't work inside blazor .razor file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59326]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-to-member-doesnt-work-inside-blazor-/1650843)._

---
[severity:It's more difficult to complete my work]
methods inside @code { } in a .razor file are not visible for "Go to member" 
default hotkey = (Ctrl+1, Ctrl+M)

---
#### Feedback Bot on 03/02/2022, 00:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 05/02/2022, 06:16 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by davidwengier** [comment]
Possibly related to https://github.com/dotnet/roslyn/issues/58939

**Comment by davidwengier** [comment]
TIL when you filter the Go To All box by something, member in this case, it switches to "Current Document" mode. Current document mode fails for razor files because Roslyn doesn't track them. It works if you turn off current document mode, because Roslyn does track the .g.cs files, and correctly maps the locations found back to the razor files, so its a little bit of an inconsistent experience.

**Comment by CyrusNajmabadi** [comment]
Closing as external.  Razor handles these scenarios.
