### ISSUE TITLE
Namespace segments are clickable inside hovers but they lead to nowhere

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59335]
**Version Used**:
VS 2022 v.17.1 Preview 5

**Steps to Reproduce**:
1. Open any project
2. Hover over any type
3. Focus on hover and see what components of it are clickable

**Expected Behavior**:
All clickable components lead to somewhere

**Actual Behavior**:
Besides types/properties etc. namespace segments are also clickable but they lead to nowhere

**Demo:**
![devenv_RkSRd4OMqS](https://user-images.githubusercontent.com/70431552/152829453-916e75a3-b3f9-42bf-b00e-22bf7d4b8c2a.gif)
_Here I try to click on every clickable item and "Microsoft" and "CodeAnalysis" do not redirect me anywhere_

**Conclution:**
Namespace segments should not be clickable

**Comment by sharwell** [comment]
The behavior here should match the behavior of <kbd>Ctrl</kbd>+<kbd>Click</kbd> to **Go To Definition**: for this feature namespaces should not be clickable symbols.
