### ISSUE TITLE
Typing <enter> in single-line raw string literal should convert it to multiline.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#59347]
For example: If i have:

```c#
var v = """[a-z]{1}"""; 
```

If i hit `<enter>` right after the `"""` i should get:

```c#
var v = """
    [a-z]{1}
    """; 
```

Right now you get:

```c#
var v = """
[a-z]{1}"""; 
```

**Comment by BhaaLseN** [comment]
Should this be dependant on an option similar to "Split string literals on enter"?

**Comment by CyrusNajmabadi** [comment]
I don't think it would need an option here. Other strings have different strategies you could take on enter. Raw strings don't really have that.
