### ISSUE TITLE
Design for exhanced refactoring UX

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#59352]
Currently we have two kinds of code actions in IDE, refactoring vs codefix. While it's fairly clear what's the difference between the two conceptually, we now ended up in a situation where many IDE analyzer/codefix really should have been implemented as refactoring instead (but implemented this way only to have some of the benefits of being an analyzer, like visual cue in editor, errorlist, fix-all, etc.) And it's inevitable that users start enforcing them as part of the build (which is what analyzers are supposed to do) and asking for ability to fine turn their behavior to better fit their preference. On the other hand, them being analyzer/codefix also have the disadvantage of not able to provide multiple actions for user to choose as a fix.

We'd need to come up with a design for an enhanced refactoring user experience to address this. For example, a FixAll-like function for refactoring, and UI to show all refactoring available, etc.

FYI @jmarolf

**Comment by mavasani** [comment]
> For example, a FixAll-like function for refactoring

We have https://github.com/dotnet/roslyn/issues/32461 tracking this.

> UI to show all refactoring available

Related: https://github.com/dotnet/roslyn/issues/35525. I had also created a prototype tool window to compute all available refactorings in the active document and populate it as a tree view, grouped by refactoring. Basically, in the background we walk through each syntax node/line in the file and compute available refactorings and then populate this tool window. It had below functionality:
1. Users can click on any entry in the tool window and navigate to that line and we automatically invoke the light bulb on that line, which will be populated with the refactoring.
2. Users can select any refactoring node and apply it across the entire document (similar to FixAll across a document). It would be applied only if there are no merge conflicts.
3. Potential to enhance with buttons to compute available refactorings across the project or solution and populate the tool window. This is an expensive operation, so cannot be done in the background.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
