### ISSUE TITLE
Expose `NullableSyntaxAnnotation`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#59368]
## Background and Motivation

Code fixes have valid use cases for using `NullableSyntaxAnnotation`, the way it's currently done in roslyn-analyzers is via reflection:

https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/NullableSyntaxAnnotationEx.cs

## Proposed API

Make `NullableSyntaxAnnotation` public, and make it static too

```diff
namespace Microsoft.CodeAnalysis.CodeGeneration
{
-    internal sealed class NullableSyntaxAnnotation
+    public static class NullableSyntaxAnnotation
     {
        // ...
     }
```

## Usage Examples

Indicated in roslyn-analyzers use case.

**Comment by jcouv** [comment]
Since this is talking about `Microsoft.CodeAnalysis.CodeGeneration.NullableSyntaxAnnotation`, it's not a compiler question. Tagging @CyrusNajmabadi since he created that type.

**Comment by CyrusNajmabadi** [comment]
What does roslyn-analyzers need this for?  This just impacts metadata-as-source, and it's unclear to me why roslyn-analyzers would care about that.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Looking at the code, I see it's indeed only checked for metadata-as-source.

- I opened https://github.com/dotnet/roslyn-analyzers/pull/5886 to see if any tests will fail in CI.
- If it's only useful for metadata-as-source, then we will need to do a small cleanup in this repo:
    - Delete https://github.com/dotnet/roslyn/blob/48bf2d855d9fe1980e16e44265bbd7bf113fc533/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Lightup/NullableSyntaxAnnotationEx.cs
    - The documentation comment for the type mentions `SyntaxGenerator`, the statement isn't super clear to me, but if this annotation is unrelated to `SyntaxGenerator` then the doc comment needs an update.
    - The type may be moved to a namespace other than `Microsoft.CodeAnalysis.CodeGeneration`.
    - Delete this code: https://github.com/dotnet/roslyn/blob/48bf2d855d9fe1980e16e44265bbd7bf113fc533/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.cs#L63-L75

**Comment by Youssef1313** [comment]
Confirmed that roslyn-analyzers don't want it, and likely the reflection in roslyn too.

**Comment by 333fred** [comment]
Please give a ping when the requirements are set.

**Comment by Youssef1313** [comment]
@333fred No API work will be needed. This type was used incorrectly both in dotnet/roslyn and dotnet/roslyn-analyzers. The work needed is just a code cleanup to eliminate the use of the API where it does nothing.

**Comment by 333fred** [comment]
Got it, thanks. Updated labels appropriately.

**Comment by Youssef1313** [comment]
My previous comment is only correct about dotnet/roslyn-analyzers. For dotnet/roslyn, the code is needed and it's the path responsible for metadata-as-source.

I'm cleaning up the reflection-based code in dotnet/roslyn in https://github.com/dotnet/roslyn/pull/59618 (hoping it will still build), and also making the documentation more clear about that.

For roslyn-analyzers, https://github.com/dotnet/roslyn-analyzers/pull/5886

**Comment by Youssef1313** [comment]
Only action needed is in roslyn-analyzers.
