### ISSUE TITLE
ValueTracker: avoid constructing symbols in-proc (on client)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#59378]
The service is currently working with symbols on both client and server sides. We should move all symbol handling to server-side, so that we never create symbols in-proc.

**Comment by ryzngard** [comment]
Logic that gets symbol on client side is: https://github.com/dotnet/roslyn/blob/e6f450fffff8cb39ab7691a0e75d5ebbb198226d/src/VisualStudio/Core/Def/ValueTracking/ValueTrackingCommandHandler.cs#L105 

Should be moved into `IValueTrackingService` and use `SymbolKey` for any time symbol information is stored on client side.

**Comment by tmat** [comment]
One more observation:

`IValueTrackingService.TrackValueSourceAsync(TextSpan selection, Document document, CancellationToken cancellationToken);` 

seems to be only called from tests. Consider removing from product code to simplify.
