### ISSUE TITLE
Wrong defaults for code analysis rules

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn#59371]
**Version Used**: 

Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.3

**Steps to Reproduce**:

1. Create a new C# console app project.
2. Add an existing item - choose .NET .editorconfig file.
3. Open the .editorconfig tab, go to the Analyzers tab, and look at the Globalization rules (for example).

**Expected Behavior**:

Defaults should match https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md.

**Actual Behavior**:

Defaults, at least for Globalization rules, are incorrect.

| ID | Expected default | Actual default |
| - | - | - |
| CA1303 | Disabled | Warning |
| CA1304 | Hidden | Disabled |
| CA1305 | Hidden | Disabled |
| CA1307 | Disabled | Warning |
| CA1308 | Disabled | Warning |
| CA1309 | Hidden | Disabled |
| CA1310 | Hidden | Disabled |
| CA2101 | Info | Suggestion | (okay)

Bug opened based on conversation here - https://github.com/dotnet/roslyn-analyzers/issues/5852#issuecomment-1032253105.

**Comment by jmarolf** [comment]
https://github.com/dotnet/roslyn/issues/60232
