### ISSUE TITLE
Expand hints we show for users

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#59379]
Inline hints already shows type information and parameter information. Some other ideas from asks: 

1. Steps in chained method calls
2. Disposed usings that are not part of a usings block.

**Comment by ryzngard** [comment]
Questions for design review: 

Do we think these are good adds?
Is inline hints infra the right design? 
Are there similar areas we could expand on? 

Once discussed we should assign for someone to provide a proposal.

**Comment by Cosifne** [comment]
Design meeting conclusion:
We want to tie the design to the editor's layering mode, to provide a 'tab' 'tab' system (when pressing tab, move to the next location with inline info) and test it

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
