### ISSUE TITLE
Create separate toggles for inline parameter hints and inline type hints

### ISSUE THREAD

**Issue by akhera99** [dotnet/roslyn#59380]
**Current behavior:**
Alt-F1 is used to toggle both inline parameter hints and inline type hints.

**Requested behavior:**
Introduce separate toggles to display type and parameter hints separately because one toggle shows too much all at once.

**Comment by akhera99** [comment]
Questions for design review:

Is this new behavior better than the existing behavior?
If we were to add separate toggles, would we need to remove the shortcut for one?

**Comment by CyrusNajmabadi** [comment]
> Introduce separate toggles to display type and parameter hints separately because one toggle shows too much all at once.

I'm curious why it's "too much".  I'm also not sure how we reconcile what goes in what buckets.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
