### ISSUE TITLE
Introduce API for determining which symbols within a reference were used

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#59389]
We currently have an optimization in msbuild which ensures we skip building a project when its dependencies' ref assemblies are unchanged.

That is, the dependency internals changing isn't enough--its public surface needs to change.

It's speculated that some additional incremental build optimization could be achieved if we also knew which symbols were actually used by the referencing project. We're going to add telemetry to try and detect how much potential savings there is here, by making the project system detect situations where a reference's ref assembly changed, then the referencing project recompiled, but its MVID was ultimately unchanged.

The idea here is that we could avoid rebuilding the referencing project depending on how the reference's ref assembly changed. For example, changes which only add new types would be fine. We would have to be very sensitive to changes which affect overload resolution and things like that. For example, the referenced assembly could add a member which causes overload resolution to choose the member instead of some extension method which was being chosen before.

If some tractible set of rules were found which prevent over-building in 80% of such cases, let's say, it could still be a win.

cc @drewnoakes

**Comment by CyrusNajmabadi** [comment]
This seems nigh-impossible IMO, unless you can conservatively know *with complete certainty* which symbols the compiler actually interrogated, and can know exactly *how* it interrogated them.

For example:

> For example, changes which only add new types would be fine.

This seems like it would never be true.  Consider something as basic as name lookup.  If i have the folllowing:

```c#
using SomeNS1;

namespace Foo
{
    using SomeNS2;

    class X { T type; }
}
```

If T is found in SomeNS1 this compiles successfully.  If a new type T is added in your dll to SomeNS2 then this dependent code absolutely must be recompiled.  Note that what actually needs to be record here are complex concepts like "the children of SomeNS2 were examined".  That way you can know that hte introduction of a type `T` into `SomeNS2` will invalidate downstream compilations.

I strongly recommend not going this route all.  In the incremental compiler space it is devilishly difficult, and only really is feasible if your compiler is designed from the ground up to support this concept (e.g. it internally tracks literally every interaction of some component examining some other visible entity).

**Comment by RikkiGibson** [comment]
It seems especially tough that any assembly can "add" types to any namespace. I'm convinced that this is not worth doing. Thanks.
