### ISSUE TITLE
Source Generators: Timing APIs

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn#59398]
## Background and Motivation

Internally the generator driver tracks the wall clock time of individual generators and the overall generator execution pass. We already expose this via ETW events, and a set of internal properties. This proposal makes the properties public so that consuming hosts can access the information directly.

Related to https://github.com/dotnet/roslyn/issues/58080

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
     public class GeneratorDriver
     {
+      public GeneratorDriverTimingInfo GetTimingInfo();
     }

+    public struct GeneratorDriverTimingInfo
+    {
+       public TimeSpan ElapsedTime;
+       public ImmutableArray<GeneratorTimingInfo> GeneratorTimes;
+    }

+   public struct GeneratorTimingInfo
+   {
+      public ISourceGenerator Generator;
+      public TimeSpan ElapsedTime;
+    }
}
```

## Usage Examples

``` C#
var driver = driver.RunGenerators();

var timings = driver.GetTimingInfo();

var totalTime = timings.ElapsedTime;
foreach (var timing in timings)
{
   Console.WriteLine($"Generator {timing.Generator} took {timing.ElapsedTime.TotalMilliseconds}ms");
}

```

## Risks

This is a simplified version of https://github.com/dotnet/roslyn/issues/58080 where we don't consider cancellation. We think by placing the API explicitly into its own `GeneratorTimingInfo` rather than being part of the run results, we are open to expand it the future: e.g. add `bool WasCancelled` to the `GeneratorTimingInfo`, without needing to consider what to do with the results in such a case. There is a risk that there is some part of the future cancellation design we havn't thought through sufficiently that will break this assumption.

**Comment by 333fred** [comment]
## API Review

This API is approved.
