### ISSUE TITLE
Add a PE file section to indicate that the timestamp isn't a real timestamp

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#5940]
With the `/deterministic` flag, we place some bits into the PE file's timestamp field that isn't a timestamp. So that tools can tell that it isn't really a timestamp, we currently set the upper bit. We are also specifying an additional PE debug directory entry that, if present, is a specific indicator that the timestamp field contains a non-timestamp. We should produce this PE section when compiling to produce a deterministic output.

The following is the closest thing we have to a spec. I hope it makes sense:

> So here is the proposal on how we determine whether time stamp field in a PE actually store a real time date stamp.
 
> Like how we add incremental LTCG signature or COFF group info into PE, we can just define a new debug directory entry type.
 
> Here are all debug directory entry types that have already been defined:

> ```c 
#define IMAGE_DEBUG_TYPE_UNKNOWN          0
#define IMAGE_DEBUG_TYPE_COFF             1
#define IMAGE_DEBUG_TYPE_CODEVIEW         2
#define IMAGE_DEBUG_TYPE_FPO              3
#define IMAGE_DEBUG_TYPE_MISC             4
#define IMAGE_DEBUG_TYPE_EXCEPTION        5
#define IMAGE_DEBUG_TYPE_FIXUP            6
#define IMAGE_DEBUG_TYPE_OMAP_TO_SRC      7
#define IMAGE_DEBUG_TYPE_OMAP_FROM_SRC    8
#define IMAGE_DEBUG_TYPE_BORLAND          9
#define IMAGE_DEBUG_TYPE_RESERVED10       10
#define IMAGE_DEBUG_TYPE_CLSID            11
#define IMAGE_DEBUG_TYPE_VC_FEATURE       12
#define IMAGE_DEBUG_TYPE_POGO             13
#define IMAGE_DEBUG_TYPE_ILTCG            14
#define IMAGE_DEBUG_TYPE_MPX              15
```

> We can add a new one:

> ```c
#define IMAGE_DEBUG_TYPE_NO_TIMESTAMP  16
```

> Here is what debug directory looks like for ntdll.dll:

> ```none
        Time Type       Size      RVA  Pointer
    -------- ------ -------- -------- --------
    5609EE9F cv           22 0011DFE4   11AFE4    Format: RSDS, {FBA98142-7084-4ADE-9DDE-27DC9D6986ED}, 1, ntdll.pdb
    5609EE9F pogo        590 0011E01C   11B01C    50475500 (PGU)
```

> With repurposed time date stamp field in PE, the above will change to:

> ```none
        Time Type       Size      RVA  Pointer
    -------- ------ -------- -------- --------
    5609EE9F cv           22 0011DFE4   11AFE4    Format: RSDS, {FBA98142-7084-4ADE-9DDE-27DC9D6986ED}, 1, ntdll.pdb
    5609EE9F pogo        590 0011E01C   11B01C    50475500 (PGU)
    5609EE9F (16)        0  00000000   0 
```

> The last entry will indicate the time date stamp field in this binary doesn't represent a real time date stamp.

**Comment by gafter** [comment]
@jaredpar @tmat @dotnet/roslyn-compiler

**Comment by gafter** [comment]
@tmat Since we generate none of these sections (I think)... do you have any idea what this spec means?

**Comment by tmat** [comment]
We generate "cv". I don't think we generate any other, but I'd need to double check.

**Comment by tmat** [comment]
We should also make sure that the Debug Directory is fully documented. 

//cc @vargaz

**Comment by gafter** [comment]
The debug directory itself is specified in the PE/COFF, section 5.1.1. (pages 71-72):
https://msdn.microsoft.com/en-us/windows/hardware/gg463119.aspx

The IMAGE_DEBUG_TYPE_REPRO is a new value for Debug Type.
