### ISSUE TITLE
Show potential fixes often contains no fixes related to error/warning

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/roslyn#59403]
**Brief description:**
Every time I open a lightbulb that is shown on an error or warning I have a small hope that there might be a codefix, but the majority of the time it only has the "Suppress or Configure issue" menu. If I knew it didn't have a useful codefix I wouldn't be opening the lightbulb nearly as often when it appears. Is there any way we could distinguish when the lightbulb actually has a relevant code fix to the issue versus when it is only showing the severity menu or unrelated codefixes?

**Example**

1. User gets a warning.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/8293542/153102354-c2b4e238-5fc2-4bd4-a96b-367fd3970769.png">

2. Hovering shows a lightbulb
<img width="256" alt="image" src="https://user-images.githubusercontent.com/8293542/153102438-f8ef55a8-9d31-4205-9daa-3f2e12ce00e0.png">

3. Expand lightbulb hoping for a codefix that addresses the wanring. ("Make nullable" codefix in this case)

4. Get disappointed it's only the "Suppress or Configure issue" menu
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8293542/153102578-72a5d283-1a12-44c2-b4fe-c5f253f0f934.png">

**Suggestion**
It'd be nice if the lightbulb was just slightly different. Like if it wasn't colorized and had a different pattern to the icon.

I believe other issues are along these lines. We get people's hopes up showing a lightbulb when we don't have any relevant suggestions. https://github.com/dotnet/roslyn/issues/47636

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/23326

**Comment by sharwell** [comment]
I agree fairly strongly with @Youssef1313 here: we _should_ have the ability to fix most cases that arise, which would naturally resolve the original concern.

**Comment by kendrahavens** [comment]
I'd like to check if we have data. I hypothesize an enormous amount of people are clicking on the lightbulb, seeing only the "Configure or suppress severity" and not taking any action.

**Comment by CyrusNajmabadi** [comment]
Closing out as not actionable.  We'd need an actual design to state what we should be doing here instead.
