### ISSUE TITLE
'view commit details' bug about 'xxx.resx'

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#59415]
**Version Used**: 
Visual Studio 2022(newest 17.0.6)

**Steps to Reproduce**:

1. -> click `view history`.
2. -> click `view commit details`.
3. -> click `xxx.resx` file and check code.

**Expected Behavior**:
No Error.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/23723575/153193476-b43961da-4490-4a40-8eb3-b4c12b83276b.png)
The file Path: C:\Users\Developer\source\repos\[soluton name]\[project name]\Resources\RuleItem.json

**Comment by jinujoseph** [comment]
This is external to Roslyn, pls file it as a VS Feedback ticket and it will be redirected to right team

**Comment by kelicto** [comment]
@jinujoseph I don't know how to do. Could you give me more help? Thanks.

**Comment by jinujoseph** [comment]
@kelicto sure https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by kelicto** [comment]
Thanks!
