### ISSUE TITLE
Error format string not filled for Error ENC0088	Modifying the body of '{0}' will prevent the debug session from continuing due to internal error: {1}

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#59418]
**Version Used**: 
VS2019 16.11.10 Preview 1.0
**Steps to Reproduce**:
(doesn't repro in a console app (at least i don't know which specific requirements are necessary), but reproduces reliably in my project. i'm willing to explain more, but it's not OS.
1. have an overriden method M with a base calls
2. have a local method LM in that method M
3. put a breakpoint in M after the base call
4. debug until breakpoint is hit
5. modify content of LM till EnC error appears
6. notice: {0} and {1} aren't replaced

**Expected Behavior**:
{0} is replaced with the method name, {1} is replaced with the internal error
**Actual Behavior**:
this error text is shown:
> Modifying the body of '{0}' will prevent the debug session from continuing due to internal error: {1}

**Notes**
when discussing the behaviour in the c# discord, @Youssef1313 mentioned that that error string isn't in the roslyn sources...

**Comment by Youssef1313** [comment]
I done a [repo search](https://grep.app/search?q=debug%20session%20from%20continuing) and yeah can't find it.

cc @tmat @davidwengier

**Comment by PathogenDavid** [comment]
[GitHub Code Search found it](https://cs.github.com/?scopeName=All+repos&scope=&q=%22will+prevent+the+debug+session+from+continuing+due+to+internal+error%22) in various older forks. The message was reworded in https://github.com/dotnet/roslyn/commit/911be131f6e14b71880244520c1a9c4bffb83750. The new wording is:

https://github.com/dotnet/roslyn/blob/82094cf4d4648a4d5fe308a3665993dfcaa63e77/src/Features/Core/Portable/FeaturesResources.resx#L1219-L1222

(FYI, `#error version` will tell you what commit Roslyn was built from, it's nice for situations like this.)

**Comment by Youssef1313** [comment]
Thanks @PathogenDavid!

It looks like the message needs two arguments, but only one is passed:

https://github.com/dotnet/roslyn/blob/82094cf4d4648a4d5fe308a3665993dfcaa63e77/src/Features/Core/Portable/EditAndContinue/AbstractEditAndContinueAnalyzer.cs#L1198

Probably nothing is replaced at all if the number of passed arguments doesn't match the number of placeholders.

**Comment by tmat** [comment]
@davidwengier

**Comment by davidwengier** [comment]
Hilariously the message for the diagnostic has been broken since the day it was added (for the record, only 1 month after I joined the team 😛): https://github.com/dotnet/roslyn/pull/46793/files#diff-a61167b90b09bc3d02049a4ab4e309ad36e6b5a3a60f6f988be10272418007f0R1182-R1185

The real fix is to try to work out _why_ the internal error occurred, but "doesn't repro in a console app" does not fill me with hope

**Comment by davidwengier** [comment]
The internal error does not repro in VS 2022, so the root cause is at least something we've fixed already.

**Comment by htna** [comment]
Microsoft seems to less considering stabilizing their product when releasing.
Often, when there are debug errors that do not appear previously, rebooting your computer resolves those issue.
