### ISSUE TITLE
Visual Studio adds second quotation mark in unappropriate situations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59427]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-adds-second-quotation-mark/1640398)._

---
[regression] [worked-in:2017, and probably earlier version of 19]
Hello,

in earlier versions of Visual Studio a second quotation mark has been automatically inserted, but only in certain places. Like at the end of the line.

If I put a quotation mark directly before or after text, only one quotation had been inserted.

Now, if I want to wrap text in quotation marks, I cannot enter one quotation mark before and one after, because Visual Studio enters two in both cases.

If my memory serves well, that was not a problem in Visual Studio 2019, but it is now a problem in Visual Studio 2019. Visual Studio 2017 works correctly.

---
#### Tracy Wang [MSFT] on 1/18/2022, 08:21 PM: 

<p>Does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use(C# or C++ console)? It would be very helpful if you could provide some screenshots of this issue. Thanks for your help!</p>

#### Martin Prohn on 2/8/2022, 03:05 AM: 

<p><a target='_blank' href="https://aka.ms/dc/file?name=B90d29a1e6e914d289fda188879e92c5d637799147424505235_Visual-Studio-2017.mp4&amp;tid=90d29a1e6e914d289fda188879e92c5d637799147424505235">Visual-Studio-2017.mp4</a><br>
<a target='_blank' href="https://aka.ms/dc/file?name=B31859f263a11417181378fd35349f3c3637799147651471796_Visual-Studio-2022.mp4&amp;tid=31859f263a11417181378fd35349f3c3637799147651471796">Visual-Studio-2022.mp4</a></p>
<p>I created two videos to show the problem. One with Visual Studio 2017 and one with Visual Studio 2022.</p>
<p>On the first line I type »string s = “Hello World”;«, an I write quotation mark before entering the text. In both versions, both quotation are created.</p>
<p>On the second line I type »string s = Hello World« and then I put quotation mark around the text. That only works in Visual Studio 2017. Visual Studio 2022 (and also current version of 2019) creates two quotation marks befor and after the text.</p>
<p>Note: It makes of course no sense to enter text and then put quotation marks around it, like it is shown in the video. That is only to show the problem. More realistically is the case, that you paste text in here and then put quotation marks around the pasted text. So it is not only a niche problem, but happens quite a lot.</p>

#### Feedback Bot on 1/25/2022, 11:21 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Martin Prohn on 2/8/2022, 03:08 AM: 

<p><a target='_blank' href="https://developercommunity2.visualstudio.com/user/772609d6-10c5-6e05-be78-731d9a947917/profile">Tracy Wang [MSFT]</a> Sorry I didn’t answer your question. I mostly write C#. So there the problem happens. I think it also happens when editing XML files. So I assume it is language independent.</p>
<p>BTW When I deactivate “Automatic brace completion” than it doesn’t happen anymore (even though quotation marks are not braces), but than  of course brace completion also don’t work anymore.</p>

#### Feedback Bot on 2/8/2022, 05:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Related to #59178

**Comment by vatsalyaagrawal** [comment]
Design meeting notes:
1. PR from DavidW is good enough for now. 
2. We will update the experience as needed if we get more feedback. 
3. We may want to align the experience across VSCode and VS at some point in future. 
4. We should look into heuristic VB uses to detect when there are unterminated strings.

**Comment by DrPepperBianco** [comment]
Hello Microsoft,

may I ask about progress in this case?

The error still appears and I have problems with it on a daily basis.

**Comment by CyrusNajmabadi** [comment]
@DrPepperBianco prs welcome. Thanks!

**Comment by hao0531** [comment]
Can't we just simply disable auto adding two double quotes?

**Comment by sharwell** [comment]
@DrPepperBianco It appears that the majority case for this issue was already fixed for the 17.2 release. Can you clarify the exact scenario that you are running into that is still causing problems?

**Comment by CyrusNajmabadi** [comment]
Closing out as fixedd.
