### ISSUE TITLE
Pattern matching null check should be eliminated if has been checked

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#59449]
**Version Used**: master

**Steps to Reproduce**:

Given this code:
```csharp
#nullable enable
using System.Collections.Generic;

public class C
{
    public int M(List<int> x!!)
    {
        return x switch
        {
            [] => 0,
            [_] => 1,
            [..] => 2
        };
    }
    
    public int N(List<int> x)
    {
        if (x is null) return 0;
        return x switch
        {
            [] => 0,
            [_] => 1,
            [..] => 2
        };
    }
}
```

Both of above cases are exhaustive, but Roslyn doesn't think so.

**Expected Behavior**:
```csharp
public class C
{
    public int M(List<int> x)
    {
        <PrivateImplementationDetails>.ThrowIfNull(x, "x");
        int count = x.Count;
        if (count != 0)
        {
            if (count == 1)
            {
                return 1;
            }
            return 2;
        }
        return 0;
    }

    public int N(List<int> x)
    {
        if (x == null)
        {
            return 0;
        }
        int count = x.Count;
        if (count != 0)
        {
            if (count == 1)
            {
                return 1;
            }
            return 2;
        }
        return 0;
    }
}
```

**Actual Behavior**:
```csharp
public class C
{
    public int M(List<int> x)
    {
        <PrivateImplementationDetails>.ThrowIfNull(x, "x");
        if (x != null)
        {
            int count = x.Count;
            if (count != 0)
            {
                if (count == 1)
                {
                    return 1;
                }
                return 2;
            }
            return 0;
        }
        throw new SwitchExpressionException(x);
    }

    public int N(List<int> x)
    {
        if (x == null)
        {
            return 0;
        }
        if (x != null)
        {
            int count = x.Count;
            if (count != 0)
            {
                if (count == 1)
                {
                    return 1;
                }
                return 2;
            }
            return 0;
        }
        throw new SwitchExpressionException(x);
    }
}
```

**Comment by RikkiGibson** [comment]
Unfortunately, the compiler doesn't distinguish between the states "should not be null, but a bad caller could still pass null" and "certainly not null, because we already checked and threw".

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson we def don't ahve that concept.  but it is an interesting one.  i wonder, in practice, how much this would actually save though.

**Comment by hez2010** [comment]
> in practice, how much this would actually save though

This makes the method hard to be inlined by JIT because of the throw expression.

**Comment by RikkiGibson** [comment]
Perhaps we should do similar to what we did for !! and do the throw via a synthesized wrapper method.

**Comment by jcouv** [comment]
The behavior of method `N` is correct. Nullability analysis affects diagnostics and attributes emitted in metadata, but not codegen. The `switch` should have a `null` check whether nullability analysis thinks it's necessary or not.
Thus I think method `M` also looks correct (the `switch` also should have a `null` check for the same reason).

**Comment by alrz** [comment]
I think patterns proposal mentioned that we still emit null checks for unannotated types because that's not a definite guarantee. However, with `!!`, it is now. Although the fact that we could have this info only for parameters and nothing else makes it less attractive but I'd agree the current codegen is less than ideal even if only for parameters.

**Comment by CyrusNajmabadi** [comment]
> The behavior of method N is correct. Nullability analysis affects diagnostics and attributes emitted in metadata, but not codegen. The switch should have a null-check whether nullability analysis thinks it's necessary or not.
Thus I think method M also looks correct (the switch also should have a null-check for the same reason).

I'm not sure i agree with this.  Codegen of a method body is an implementation detail.  We could certainly have whatever sort of analysis we want tie into that as long as the emitted code is correct and hte change is not ever observable.  

THis feels like a pass that simply removes unreachable code.  Whether or not that works off of NRT or some other system really doesn't matter, just as long as the semantics of the lang are preserved.

**Comment by CyrusNajmabadi** [comment]
> for example. It seems hard to justify in terms of "return on investment".

NO question :)

I wasn't trying to imply this *should* be done.  Merely that it did seem like something that *could* be done while not violating anything about the language or having any observable effects. 

Whether or not you want to do it is up to you :)

**Comment by RikkiGibson** [comment]
Moving the "synthesize a 'throw' wrapper" to dedicated issue #59601.
