### ISSUE TITLE
compile error when using function pointer in Expression<>

### ISSUE THREAD

**Issue by bysdxt** [dotnet/roslyn#59454]
**Version Used**: 
.net sdk 5.0.404
.net sdk 6.0.102
**Steps to Reproduce**:
code:
```cs
using System;
using System.Linq.Expressions;
namespace test
{
    unsafe class Program
    {
        static double f() => 0;
        static delegate*<double> fp() => &f;
        static void Main()
        {
            Expression<Func<double>> h = static () => fp()();
            Console.WriteLine(h);
        }
    }
}

```

**Expected Behavior**:
error CS1944
**Actual Behavior**:
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : Process terminated. System.InvalidOperationException: Unexpected value 'FunctionPointerInvocation' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind' [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node) [Z:\test\test.csproj]
......
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0() [Z:\test\test.csproj]

生成失败。

C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : Process terminated. System.InvalidOperationException: Unexpected value 'FunctionPointerInvocation' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind' [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [Z:\test\test.csproj]
......
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, BindingDiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [Z:\test\test.csproj]
C:\Program Files\dotnet\sdk\5.0.404\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0() [Z:\test\test.csproj]
    0 个警告
    112 个错误

**Comment by Youssef1313** [comment]
cc @333fred
