### ISSUE TITLE
ToString format specifier completion for Guid shows DateTime specifiers instead

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#59453]
**Version Used**: int.main

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/350947/153389480-08de918c-d374-439d-b513-464cd49d6343.png)

**Expected Behavior**:

Should show N D B P and X specifiers, with examples for each.

**Actual Behavior**:

Shows DateTime specifiers instead.

**Comment by jinujoseph** [comment]
cc @genlu
