### ISSUE TITLE
Event handler tab-completion does not work in new project templates

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#59488]
**Version Used**: dev17

**Steps to Reproduce**:

1. create a "new-style" .NET 6 console project
2. try to use event handler tab completion

![reproducer](https://user-images.githubusercontent.com/344204/153588963-fa949965-f5bd-42eb-9728-ff445653532b.gif)

**Expected Behavior**:

Event handler is generated and inserted as local function.

**Actual Behavior**:

Nothing happens

**Notes**:

I think, Visual Studio needs extra options in the new project dialog, to allow each user to **select whether they want** top-level statements and/or implicit usings. This would alleviate the pain I have with the new project templates.

![image](https://user-images.githubusercontent.com/344204/153589240-2713d53c-320d-42b3-bbea-92185d00bd39.png)
from https://github.com/dotnet/roslyn/issues/43563#issuecomment-627633925, apparently this has been a known issue since May 2020.

Because top-level statements are effectively rubbed into one's face when creating a new project (not a good thing at all!), one would have every right to expect this to work.
Every time I try to adapt to this, I get bitten by something. and I am forced back to trusty old `class Program`.

**Comment by svick** [comment]
@siegfriedpammer 

> I think, Visual Studio needs extra options in the new project dialog, to allow each user to select whether they want top-level statements and/or implicit usings.

There is an extensive discussion about that at https://github.com/dotnet/docs/issues/27420.

**Comment by siegfriedpammer** [comment]
> @siegfriedpammer 
> 
> > I think, Visual Studio needs extra options in the new project dialog, to allow each user to select whether they want top-level statements and/or implicit usings.
> 
> There is an extensive discussion about that at https://github.com/dotnet/docs/issues/27420.

Thank you. Seems there is nothing more for me to add to the discussion.
