### ISSUE TITLE
Keyword completion for top-level statements is showing up in C#8

### ISSUE THREAD

**Issue by hypeartist** [dotnet/roslyn#59489]
I've stumbled upon some strange completion service behaviour. Pre-conditions: **C# version 8.0**. Typing 'u' at the beginning of the document AND before any existing 'using' directive I see 'using', 'extern', 'global' as completion items - that's just what I expect to see. But in case there is no 'using' directive anywhere below insertion position the completion list gets filled with full bunch of totally unrelated items. 

![image](https://user-images.githubusercontent.com/3519388/153593317-18d6b4ea-30c4-478e-8acf-b50095008d4d.png)
![image](https://user-images.githubusercontent.com/3519388/153593356-7d7b5d73-cd62-4e77-ba25-7b31b91c5c36.png)

**Comment by sharwell** [comment]
@genlu @CyrusNajmabadi Should we just update `IsGlobalStatementContext` to check language version?

https://github.com/dotnet/roslyn/blob/0098764330d1e22c43ead6065e4ed5f8aae09195/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs#L1931

**Comment by CyrusNajmabadi** [comment]
So, generally, completion doesn't check lang version. The idea is that we don't want to punish someone for using lang features too early. This is so get can try to use them if interested, then get useful upgrade helpers to actually have them available.

**Comment by CyrusNajmabadi** [comment]
I would say that that absent other signals, we should consider a way to have `using` be more prominent here

**Comment by sharwell** [comment]
We already dealt with what happens when you type `us` in #51137. If we want to handle what happens when you type `u` we can apply the same strategy to additional cases.

**Comment by sharwell** [comment]
> The idea is that we don't want to punish someone for using lang features too early. 

In the past I agreed with this, but there are two problems:

1. Users can't easily change language versions anymore.
2. If a user explicitly states the language version is 8, we should not be nudging them out of that. They picked 8, not "maybe 8 or something later"

**Comment by CyrusNajmabadi** [comment]
> Users can't easily change language versions anymore (increasing the language version is typically an unsupported action).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
