### ISSUE TITLE
Variables in list, recursive and var patterns are not colorized as local

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#59484]
**Version Used**: 17.1p3

**Steps to Reproduce**:

It seems like only declaration patterns are covered.

![image](https://user-images.githubusercontent.com/3105979/153585922-1d708c47-cc49-47a5-a8e2-6302aaa2bb47.png)

This happens with list, recursive and var patterns (parenthesized or singleton)

**Comment by Youssef1313** [comment]
I think there is a missing check in:

https://github.com/dotnet/roslyn/blob/ad96ee4b0690c886a51c69120372286163ddf6a0/src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs#L261-L265

**Comment by Youssef1313** [comment]
I wonder when/why it's intended to fallback to

https://github.com/dotnet/roslyn/blob/ad96ee4b0690c886a51c69120372286163ddf6a0/src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs#L267

**Comment by alrz** [comment]
> I think there are missing checks in:
> 
> https://github.com/dotnet/roslyn/blob/ad96ee4b0690c886a51c69120372286163ddf6a0/src/Workspaces/CSharp/Portable/Classification/ClassificationHelpers.cs#L261-L265

I think this whole block could return `ClassificationTypeNames.LocalName`. Any SingleVariableDesignation is always a local.

**Comment by Youssef1313** [comment]
@alrz Yup, that's what I intended by https://github.com/dotnet/roslyn/issues/59484#issuecomment-1038395943
