### ISSUE TITLE
GTD on type with partial declarations spanning multiple files

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5948]
Currently it seems that GTD navigates to a rather arbitrary partial declaration of the type.
Could we prefer the declaration that appears in the file of the same name as the class (if there is any)?

**Comment by dpoeschl** [comment]
@tmat What's the example? In most normal cases, it should show the Find Symbol Results window to disambiguate.

**Comment by tmat** [comment]
Yeah, but the first one it auto-opens is arbitrary. Could we pre-select the file that matches the class name?

**Comment by dpoeschl** [comment]
@tmat No documents should "auto-open", or do you mean if you do ```F12 Enter```?

IIRC, the top-level nodes in Find Symbol Results are ordered alphabetically (sub-nodes can be sorted, but the same node sorting API isn't used for top-level nodes), so we'd either need to fix that bug/design (part of the platform code), preselect the desired one (which I don't think is supported currently, but I'll check), or prefix them with something (```Part 1```, ```Part 2```... or something) to make the desired one the first one in the list.

**Comment by Pilchie** [comment]
Is this happening because @tmat has previews enabled, so it automatically previews the first entry?

**Comment by dpoeschl** [comment]
@Pilchie Is that a thing? I couldn't find such an option.

**Comment by Pilchie** [comment]
@dpoeschl @tmat  - have we actually seen this repro?

**Comment by dpoeschl** [comment]
I haven't seen or heard of this outside this particular report.

**Comment by jaredpar** [comment]
Could this be related to #7111 and #7112?
