### ISSUE TITLE
#endif is seen as LeadingTrivia of namespace instead of TrailingTrivia of using statement

### ISSUE THREAD

**Issue by Jake-Rich** [dotnet/roslyn#59496]
**Version Used**: 

**Steps to Reproduce**:
1. Using statement surrounded by `#if` preprocessor directive
```
using System;
#if UNITY
using Unity
#endif

namespace Namespace
{
   public class ClassName 
   { 
   } 
}
```

2. Analyze code in roslyn with source generator.
3. Use source generator to move `UsingStatementSyntax` inside of the `NamespaceDeclartionSyntax`

```
Console.WriteLine( namespaceSyntax.WithUsingStatements( CompilationUnitSyntax.Usings );
```

**Expected Behavior**:

```
namespace Namespace
{
using System;
#if UNITY
using Unity
#endif
   public class ClassName 
   { 
   } 
}
```

**Actual Behavior**:

```
#endif

namespace Namespace
{
using System;
#if UNITY
using Unity
   public class ClassName 
   { 
   } 
}
```

Exploring the syntax tree shows the `#endif` trivia is the `LeadingTrivia` of the `NamespaceDeclarationSyntax` and not the `TrailingTrivia` of the `UsingStatementSyntax`. 

I think it was implemented this way to cover the edge case where there is no token in front of the `#if` directive by assuming there will always be a NamespaceDeclaration, UsingStatment or EndOfFile token after it. However this can lead to "unintended behavior" as the formatting becomes incorrect when it attaches the `#if` and `#endif` to different tokens and you try moving those tokens around.

**Comment by jcouv** [comment]
This is by-design. The rule is that trailing trivia doesn't go past end-of-line.
Quoting from @CyrusNajmabadi elsewhere:

> The general rule (and i would consider deviations to be bugs) is:
> When creating a token, we consume all trivia up to the token start.  then we consume the token contents.  then we consume all trivia up through the first end of line.
> Then that loops.
> 
> If you have:
> ```
> // c1
> int foo; // c2
> 
> // c3
> string bar; // c4
> ```
> 
> `// c1` and the end-of-line after it belong to `int`.  Then the space after `int` belongs to it.
> Then you have `foo` with no trivia, then `;` with trailing trivia `// c2` (and the end-of-line after that)
> Then the `string` has end of line, `// c3`, end of line 
> For comments, this has the benefit of being a heuristic that is intuitive most of the time.
> For directives... it's all non-intuitive no matter what we do.

The way this applies in your scenario is that the trailing trivia for `Unity` is an end-of-line, and `#endif` (with new lines) is the leading trivia for `namespace`.
