### ISSUE TITLE
ID0056 bad suggestion in netstandard2.0

### ISSUE THREAD

**Issue by giladfrid009** [dotnet/roslyn#59514]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.4

**Steps to Reproduce**:

1. Create netstandard2.0 project
2. Paste this snippet of code:
```csharp
int[] arr = { 1,2,3};
_ = arr[arr.Length - 1];
```
3. An IDE0056 suggestion will appear as a warning, to simplify the indexing.
The proposed solution is:
```csharp
_ = arr[^1];
```
which is not supported by the C# version.

***Note***: The solution has another project targeting .NET5

Full csproj content, in case it might be usefull:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
	  <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
	  <LangVersion>preview</LangVersion>
	  <nullable>enable</nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>

</Project>
```

**Expected Behavior**: 
No warning appearing at all. 
Note that possibly there are other bugs related to the System.Index typed introduced in a later version of the language.

**Actual Behavior**:
Bad suggestion, with a code fix that doesn't compile.

**Comment by Youssef1313** [comment]
By looking at code, there is a language version check, which is supported by a unit test as well:

https://github.com/dotnet/roslyn/blob/5193908c7283d377b9133a24e0e4394c603869c6/src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs#L174-L178

https://github.com/dotnet/roslyn/blob/5193908c7283d377b9133a24e0e4394c603869c6/src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseIndexOperatorTests.cs#L22

I couldn't reproduce this even with your note and adding adding a `ProjectReference` to the .NET 5 project to reference the .NET Standard project

> Note: The solution has another project targeting .NET5


@giladfrid009 Can you create and upload a repro project/solution?

**Comment by giladfrid009** [comment]
> By looking at code, there is a language version check, which is supported by a unit test as well:
> 
> https://github.com/dotnet/roslyn/blob/5193908c7283d377b9133a24e0e4394c603869c6/src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.cs#L174-L178
> 
> https://github.com/dotnet/roslyn/blob/5193908c7283d377b9133a24e0e4394c603869c6/src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseIndexOperatorTests.cs#L22
> 
> I couldn't reproduce this even with your note and adding adding a `ProjectReference` to the .NET 5 project to reference the .NET Standard project
> 
> > Note: The solution has another project targeting .NET5
> 
> @giladfrid009 Can you create and upload a repro project/solution?

Of course, the issue is present in the following project:
https://github.com/giladfrid009/SimpleSIMD

The Exact location: 
Generator/ArrOverloader.cs , line 87

**Comment by Youssef1313** [comment]
Ok it looks like you're using C# preview (which was apparent from the original report code snippet but I didn't notice it), so the following statement isn't correct:

> which is not supported by the C# version.

I think we'll need to check both for the existence of `System.Index` and also the language version, not the language version alone.

**Comment by Youssef1313** [comment]
Hmm.. I see that the code has also a check for `System.Index`

https://github.com/dotnet/roslyn/blob/5193908c7283d377b9133a24e0e4394c603869c6/src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseIndexOperatorDiagnosticAnalyzer.InfoCache.cs#L45-L50

And `System.Index` appears to be coming from the `Microsoft.CodeAnalysis.CSharp` package.

My guess is that `IsAccessibleWithin` check is failing, but can't tell for sure now.
