### ISSUE TITLE
INamespaceOrTypeSymbol.GetTypeMembers does not return all type members.

### ISSUE THREAD

**Issue by AlyElhaddad** [dotnet/roslyn#59517]
`INamespaceOrTypeSymbol.GetTypeMembers` does not return all type members.

**Version Used**: 
Visual Studio: 2022 (17.0.5).
`Microsoft.CodeAnalysis.Analyzers`: `3.3.3`.
`Microsoft.CodeAnalysis.CSharp`: `4.0.1`.

**Steps to Reproduce**:
1. Using Visual Studio, create an ASP.Net Core API application with the default template and target framework `net6.0`.
2. Create a source-generator project for this web app, and reference it in the web app.
3. Using the `Compilation` instance (in `GeneratorExecutionContext.Compilation` of `ISourceGenerator.Execute`), recursively get all type members of all assemblies, namespaces and types, using `INamespaceOrTypeSymbol.GetTypeMembers`.
4. Print the full type name for each of the `INamedTypeSymbol`s.

**Expected Behavior**:
You get all the names of the `INamedTypeSymbol`s available on all assemblies, namespaces and types.

**Actual Behavior**:
You get all the names of the `INamedTypeSymbol`s available with at least one (or few) missing.
The one that I know for sure is missing is: `Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigurationFactory` (found [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Logging.Configuration/src/LoggerProviderConfigurationFactory.cs)).

**Further info**:
One might guess that it's due to the type being `internal sealed class` but I have made sure to test that on another `internal sealed class` included in the attached solution, and it does show. One might also think that this type is not referenced at all, but I made sure that it is by getting it during runtime via reflection. I've attached a solution with minimal reproduction of the issue.

*A solution where the issue is reproduced*:
[RoslynBug_GetMembersNotGettingAllMembers.zip](https://github.com/dotnet/roslyn/files/8053990/RoslynBug_GetMembersNotGettingAllMembers.zip)

**Comment by jcouv** [comment]
@333fred Could you take a look (triage or fix as appropriate)?

**Comment by 333fred** [comment]
@AlyElhaddad what you're observing here is a difference between the _ref_ assemblies that you build against with framework references (which do not include internal members), and _source_ assemblies (such as your reference to `AnotherDependencyWithInternalSealedClass`), which do include internal members. You can read more about ref assemblies [here](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies), but you'll note that the ref assembly definition for Microsoft.Extensions.Logging.Configuration (defined [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Logging.Configuration/ref/Microsoft.Extensions.Logging.Configuration.cs)) does not include the `LoggerProviderConfigurationFactory` type. In general, you should not depend on being being to find internal types from framework assemblies at compile time, as you will be compiling against assemblies that do not include that information.

**Comment by AlyElhaddad** [comment]
@333fred accessing every type regardless of its modifiers is important for my project. Is there any way or a workaround where all types could be accessed? If not, could we please turn this into a feature request?

*I've made a [source-generation-based dependency injection framework](https://github.com/AlyElhaddad/ThunderboltIoc). I'm trying to integrate that with `Microsoft.Extensions.DependencyInjection` and in order to do this, I have to take into account all services registered by Microsoft and 3rd-parties, including those with non-public modifiers.*

**Comment by 333fred** [comment]
> Is there any way or a workaround where all types could be accessed? If not, could we please turn this into a feature request?

You would need to have your projects depend on the implementation assemblies, rather than the ref assemblies. This is likely to be somewhat difficult, but I'm afraid I don't have any better ideas for you. It is very intentional that ref assemblies work like this, as it improves compiler performance and memory consumption to avoid all of these types.

> That -I suppose- should be using the source assembly rather than the ref assembly because after all, this is how it's going to execute. Nonetheless, the type still didn't show

You should use a decompiler to look at the assemblies and ensure the types that you want are there. You should also make sure to use msbuildlog to look through the compiler inputs and make sure that you're actually depending on the implementation assemblies, not the ref assemblies.

> I added <ProduceReferenceAssemblies>true</ProduceReferenceAssemblies> to AnotherDependencyWithInternalSealedClass.csproj and tried to reference that instead of the debug output, and ironically, my internal sealed class still showed.

You're using a project reference, not an assembly reference. Ref assemblies are about the produced NuGet, they do not affect a project reference. There is no perf benefit there for avoiding internal implementation details.

**Comment by drewnoakes** [comment]
> ... On the other hand, I added `<ProduceReferenceAssemblies>true</ProduceReferenceAssemblies>` ...

Note that the property is singular `ProduceReferenceAssembly`, not plural `ProduceReferenceAssemblies`.

Fixed in MSBuild's XSD here: https://github.com/dotnet/msbuild/pull/7799
