### ISSUE TITLE
IDE0064: Update analyzer title and associated doc

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#59513]
Currently the `IDE0064` title is `Make readonly fields writable` (see [here](https://github.com/dotnet/roslyn/blob/a73b0619f0c8fd390f3505a5f982a9ed8b3e8701/src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx#L236)) differs from doc name `Make struct fields writable` (see [here](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0064)).

I would like to suggest (and offer to fix) these names so that they are in sync and are updated to a message like `Make struct readonly fields writable` which seems a clearer intent (especially when browsing rules with the VS 2022 editor).

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
