### ISSUE TITLE
IDE help after typing `struct record Foo`

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#59534]
I keep typing this and I wonder if the IDE could switch it to `record struct` as I type, similar to how typing `@$"` produces `$@"`, and/or make the resulting parse less confusing.

**Comment by jcouv** [comment]
The syntax model doesn't permit representing this order. So I don't think there's much we could do from compiler/parser side to improve this.
@sharwell Would it be worth considering an IDE-side solution (detect token "struct" followed by token "record" with an  analyzer, and offer a fixer to swap)?

**Comment by CyrusNajmabadi** [comment]
> The syntax model doesn't permit representing this order.

We can detect this and make eitehr a struct with a skipped token, or a record witha  skipped token.  We'd then only need a special diag id to call this out which teh IDE could fix.

**Comment by jcouv** [comment]
Thanks for the clarification @CyrusNajmabadi. That makes sense and doesn't force an unnatural change to the syntax model.
From our offline discussion, we should test this with trivia on the second token (that will be skipped).

**Comment by CyrusNajmabadi** [comment]
Reopening.  The IDE side has not gone in.  This is just the compiler producing a sepcific diag for us to key off of.

**Comment by jcouv** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/59652
