### ISSUE TITLE
C# LSP Regex completion does not work as expected.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#59545]
**Version Used**: 

**Steps to Reproduce**:
1. Enable C# LSP feature flag
2. Try and commit any sort of Regex completion item

For instance:
![devenv_g0v6pLWNfP](https://user-images.githubusercontent.com/2008729/153945523-33d61328-a473-4398-82d7-a54d96a81ed7.gif)

**Expected Behavior**: commit works as expected

**Actual Behavior**: Extra content is duplicated / labels seem to apply? Gif is kinda long but shows a lot.

**Comment by dibarbet** [comment]
@CyrusNajmabadi we convert the Roslyn completion item to the LSP completion item.  I could imagine something going wrong here - https://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/LanguageServer/Handlers/Completion/CompletionHandler.cs,209

LSP first looks at the `textEdit` of the completion item, if it exists it uses that.  If no text edit, it will use the `insertText` to commit.  If that doesn't exist, it uses the `label`.

Just guessing, but potentially it's using the label to commit?

**Comment by CyrusNajmabadi** [comment]
Yes.  That seems buggy.  It should be using LSPCompletionProvider.GetChangeAsync to determine what actual change should be made.

**Comment by dibarbet** [comment]
@CyrusNajmabadi note there are potential perf issues with providing text edits instead of insert text - @allisonchou how far did we get in the experiment to always provide text edits in completion?  Did it end up being bad for perf?

**Comment by CyrusNajmabadi** [comment]
Our completio API has no concept of 'insertion text'.  If we want to try to have logic htat finds that special data, it must only do so on providers where that is safe.  e.g. the provider (or item) needs to opt into that in some way.  If it doesn't, we need to fallback to using the actual API we have for computing the change.  otherwise, we're just going to get this wrong :)

**Comment by allisonchou** [comment]
We likely want to implement this work item before turning TextEdits on by default - https://github.com/dotnet/razor-tooling/issues/4408
I recall TextEdits making completion perf noticeably slower, the above task should help speed things up

**Comment by dibarbet** [comment]
tracking this in https://github.com/dotnet/roslyn/issues/59773
