### ISSUE TITLE
Disabling "Insert * at the start of new lines when writing /* */ comments" has no effect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59542]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Disabling-Insert--at-the-start-of-new-/1662106)._

---
[severity:It bothers me. A fix would be nice]
1. In Tools > Options > Text Editor > C# > Advanced, disable "Insert * at the start of new lines when writing /* */ comments"
2. Open a C# file and type "/*" then press return
3. \* is inserted at the start of the new line

Visual Studio Professional 2022 (64-bit) 17.0.6

---
#### Feedback Bot on 2/13/2022, 07:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@dibarbet I wasn't able to reproduce this in normal editing, so I'm guessing it's specific to the LSP editor.

**Comment by dibarbet** [comment]
@NTaylorMullen in razor, is the * comment insertion handled via textmate, or something else?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen in razor, is the * comment insertion handled via textmate, or something else?

language-configuration.json so ya this wouldn't respect settings.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is razor.
