### ISSUE TITLE
[Unity] Telegram.Td.dll - Assets\Example.cs(4,12): error CS0246: The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by taeyeonlee** [dotnet/roslyn#59557]
**Version Used**: 
https://docs.unity3d.com/2022.1/Documentation/Manual/CSharpCompiler.html

**Steps to Reproduce**:
Hi  @CyrusNajmabadi, @RikkiGibson, @jaredpar
When using the library (Telegram.Td.dll) in Unity (Windows OS), it logged this error, Any ideas ?									
When using the library (Telegram.Td.dll) in Visual Studio (Windows OS), it's working fine.									
Unity Error log : Assets\Example.cs(4,12): error CS0246: The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)			

Source for (Telegram.Td.dll) : https://github.com/tdlib/td/blob/master/td/telegram/ClientDotNet.cpp

Example.cs (in Unity)

```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Td = Telegram.Td;
public class Example : MonoBehaviour
{
}
```

**Expected Behavior**:
It should be no error.
**Actual Behavior**:
Unity Error log : Assets\Example.cs(4,12): error CS0246: The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jcouv** [comment]
From the error, it looks like the assembly with `Telegram` is not referenced by the project. This is likely not a compiler bug.
I'm not too familiar with Unity, but the way I would recommend troubleshooting this is building with logs. You want to see the list of references given to the C# compiler. With msbuild, you can pass the `/binaryLog` (or `/bl`) option to produce a complete and compact log, which can then be opened with the [structured log viewer](https://msbuildlog.com/).

**Comment by jcouv** [comment]
@taeyeonlee We didn't hear back from you. From my estimation, your project is missing some references. I'm not seeing a compiler issue.
I'll go ahead and close the issue. Please re-open with repro details if my understanding is incorrect. Thanks
