### ISSUE TITLE
Change Inline Hints shortcut/behavior to be Ctrl+Ctrl with a toggle like behavior

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#59579]
- We should change the Inline Hints shortcut from Alt+F1 to Ctrl+Ctrl to pass accessibility requirements. 
- Ctrl+Ctrl should be a toggle like behavior to turn Inline Hints on/off without requiring the user to hold the shortcut down in-order to view hints. 
- We should change the first option in Tools > Options to say `Enable or Disable all hints by pressing Ctrl+Ctrl`.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/46729679/154325412-69610492-f760-4c72-b10a-8f81f8021aff.png">

- The Tools > Option to `Enable or Disable all hints by pressing Ctrl+Ctrl` should be checked off by default and be the default behavior.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
