### ISSUE TITLE
Ctrl+Left/Right Arrow inside raw string literals does not behave as expected

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/roslyn#59581]
**Version Used**: Visual Studio 17.2 Preview 1 / Compiler version: '4.2.0-1.22108.11 (a29b6ae8)'. Language version: preview.

**Steps to Reproduce**:

1. Create a new console app
2. Populate `Program.cs` as follows:

```
string s = """
    Hello
        World$$!
    :)
    """;
Console.WriteLine(s);
```

3. With your text cursor at the position of the `$$` (as pictured below) press Ctrl + Left arrow<br>(Which should be bound to `Edit.MoveControlLeft` by default.)

![image](https://user-images.githubusercontent.com/278957/154333878-11a8a362-53d3-4703-ace5-f9dfe1980e0a.png)

**Expected Behavior**: Text cursor moves to the beginning of `World` (Which would be consistent with cooked strings)

![image](https://user-images.githubusercontent.com/278957/154332245-2b12f1e5-f2b6-4f06-b1a3-cf4830738752.png)

**Actual Behavior**: Text cursor moves to the beginning of the raw string literal:

![image](https://user-images.githubusercontent.com/278957/154332363-7406dde8-4b3a-4cfa-977a-8031f0194eba.png)

(Ctrl+Right arrow has the same erroneous behavior.)

**Comment by jnm2** [comment]
Related: a very annoying behavior is that single words can no longer be double-clicked to do a whole-word select once they are inside a raw string literal. Instead, double-clicking causes the whole literal to be selected.

**Comment by rainersigwald** [comment]
This also affects ctrl-backspace to delete a word--or _the entire raw string up to the cursor_ as it does right now.

**Comment by CyrusNajmabadi** [comment]
Raw string literals have had very little IDE work done to support them.  That will be coming in upcoming sprints :)

**Comment by PathogenDavid** [comment]
I figured that was probably the case. I'm trying to break a my bad habit of using preview releases and ignoring bugs instead of reporting them 😅
