### ISSUE TITLE
The IDE interferes with typing a new raw string literal 

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#59593]
**Version Used**: VS 17.2-p1

Type `var x = """`. The IDE properly does this:

![`var x = """"""`](https://user-images.githubusercontent.com/8040367/154375851-24e7b2ab-bd4b-4aeb-b2a2-1688f1afa59e.png)

Now press enter, the necessary next keystroke required by the C# spec in order to create a valid raw string literal. That produces this very broken code:

![`var x = """" +
    """"`](https://user-images.githubusercontent.com/8040367/154375934-6392b4dc-696c-412c-89ec-ea0fb5327657.png)

Interpolated raw string literals behave the same.

**Comment by jnm2** [comment]
I'm not sure if something deeper is going on. I'm getting this each time I restart VS, but the solution builds successfully and there are no errors in the error list:

![image](https://user-images.githubusercontent.com/8040367/154376636-350280d2-0ba7-4041-8c2e-eef819cbe7c6.png)

**Comment by CyrusNajmabadi** [comment]
> I'm not sure if something deeper is going on. I'm getting this weird behavior which doesn't go away when I restart VS, but the solution builds successfully and there are no errors in the error list:

that looks like an older parser was loading somehow.

**Comment by CyrusNajmabadi** [comment]
This is otherwise a dupe of https://github.com/dotnet/roslyn/issues/59347

**Comment by jnm2** [comment]
Is there anything I can do to investigate the older parser getting loaded, or should we close this one?

**Comment by jcouv** [comment]
To confirm an older parser is used, add `#error version` (this causes the parser to emit a diagnostic with compiler version)

**Comment by jnm2** [comment]
![image](https://user-images.githubusercontent.com/8040367/158917316-ce6e0dd9-304f-437b-bacd-3dafb6c1be69.png)

**Comment by jnm2** [comment]
I feel very dumb. I don't normally install ReSharper in previews and I forgot it was there. That was it. So sorry, everyone!
