### ISSUE TITLE
Interpolated raw string literals don't handle double braces correctly

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#59603]
**Version Used**: Version 17.2.0 Preview 2.0 [32216.143.main]

It seems like double braces are not handled correctly with interpolated raw string literals. I've included a comprehensive set of examples, but the only issues are with the last two sets.

1. Classification always seems to want to highlight double braces, even when they shouldn't be special, as with three and four dollar signs
2. Double braces only output one brace even when using more 3 or more $ signs (the spec calls out this shouldn't happen)

Additionally CS9006 is a little surprising in practice. I can't use `{{` with `$"""`, because 2 > 1, but I can use `{{{` with `$$"""` because they're not parsed as three braces grouped together. Using `{{{{` with `$$"""` would error though. Once you understand what the parser is doing it makes sense, and to be fair exactly this example is called out in the spec, but it is jarring at first as a user, and I don't imagine surprising users into checking the spec is the goal. Perhaps once the classification issue is fixed it will be a little clearer.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/754264/154400659-7c4abaee-01fe-4bbd-9755-a74723ca52a7.png">

**Comment by CyrusNajmabadi** [comment]
I'll takea  look asap.
