### ISSUE TITLE
IDE0073 triggered when header template unspecified

### ISSUE THREAD

**Issue by lonix1** [dotnet/roslyn#59606]
**Version Used**: 
vscode + c# extension
tested with net5 and net6

**Steps to Reproduce**:

1. `.editorconfig` file has `file_header_template = unset`
2. open some file
3. go to top row, press <kbd>ctrl .</kbd>

**Expected Behavior**:
Shows "Add file header" from analyser [IDE0073](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0073).

**Actual Behavior**:
I've not specified a file header, so it should not offer to add one.

**Comment by sharwell** [comment]
This behavior is by design. When `file_header_template` is not specified, IDE0073 is automatically disabled. However, when IDE0073 is disabled we have a separate code refactoring (not based on an analyzer) which offers to add a file header based on other files located in the same directory.

**Comment by lonix1** [comment]
Thanks.

> separate code refactoring (not based on an analyzer) which offers to add a file header

Is that exposed in some way to allow us to disable it? BTW I'm using VSCode not VS.

**Comment by lonix1** [comment]
I see! :) It's unfortunate though because other extensions adds their own, and it becomes a huge mess. It would be nice to be able to disable them selectively, the way we can do for analysers. Thanks for the explanation.
