### ISSUE TITLE
Suboptimal code for non-linear is-pattern expressions compared to switch

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#59615]
```cs
class C {
    string Worst(object i) {
        // uses a boolean flag for the result and a conditional jump
        return i is 1 or C(2) ? "aaa" : "bbb";
    }
    string Switch(object i) {
        // falls back to switch arms when possible; this info isn't available for `is` expressions
        return i switch { 1 or C(2) => "aaa", _ => "bbb" };
    }
    string Best(object i) {
        // ideally it should be lowered as `||` - still "linear" without using a flag
        return i is 1 || i is C(2) ? "aaa" : "bbb";
    }
    void Deconstruct(out int i) => throw null;
}
```
Relates to https://github.com/dotnet/roslyn/issues/45679

([sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCKDeBYAUCglBARgAYUB1AJwHsBnAFwAobgArAUwGMGUoBKLHkIiUAejEoArnQ50UEFMBo0ANhwgwUAM1UQA5jppUUDABYcUVOVNW9NAEwUouNGA6gMobiKpRspMAAHYVECBAB2Pj55YhRjdCYkQQB+FAAiCCz0lBAM4AL0gG5QggBfUqIyFABlAHdPLjMWdm5eASF8MPFJbV9VeWAILgBrUxoUOgaGJoUqMHk6iy0g+jooYHUi0zMoeVhtCb2YAHJ7ADdoPU3LQ5MAAz37lA4ADyDrOnW3OkqRSOiU0aZiwKDiCTQSUEAF4AHwZLIQdIAGhQAH0UHD8oUUGUSl1ypUSOQAEJyZisTg8PiCHAE0QSPgODSqVQATz4vDoZhoticwEsqhodQ41icEHk9zgcGeAFpJl5WRlVLANFQctMeVJeAhyIpdAY/oQAVAYmCUNLontEskUGlMtlctjgMVKhV6QgACwoAAi3B+DCoUh4LG1fBg7Rh8PMtDqKBgtlU+LKQA=))

**Comment by jcouv** [comment]
Re-opening, as the change had to be reverted in https://github.com/dotnet/roslyn/pull/69544
