### ISSUE TITLE
"Convert to switch statement" refactoring generates invalid code

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#59616]
**Version Used**: 
Version 17.2.0 Preview 2.0 [32208.508.main]

**Steps to Reproduce**:
```C#
foreach (char c in "abcd")
{
    if (c >= 128 || c == 'b' || c == 'd')
    {
        Console.WriteLine(c);
    }
}
```
Apply the  "Convert to switch statement" refactoring.

**Expected Behavior**:
Either it doesn't offer the refactoring, or the refactoring is applied and the code continues to compile and run as it did before.

**Actual Behavior**:
It generates this:
```C#
foreach (char c in "abcd")
{
    switch (c)
    {
        case >= 128:
        case 'b':
        case 'd':
            Console.WriteLine(c);
            break;
    }
}
```
which fails to compile with:
```
error CS0266: Cannot implicitly convert type 'int' to 'char'. An explicit conversion exists (are you missing a cast?)
```

**Comment by alrz** [comment]
Related: https://github.com/dotnet/roslyn/issues/48832
