### ISSUE TITLE
Support implementation edges for interfaces to types for cross-project/repo find references

### ISSUE THREAD

**Issue by noellelc** [dotnet/roslyn#59617]
The current C# LSIF tool is missing `item` edges that link implementations to all relevant ranges. The full spec can be found here: https://microsoft.github.io/language-server-protocol/specifications/lsif/0.6.0/specification/. @jasonmalinowski @CyrusNajmabadi 

As an example of a missing link:
![image](https://user-images.githubusercontent.com/63023800/154529643-2dbff241-2003-4315-bfcc-a8f296e82000.png)

**Comment by CyrusNajmabadi** [comment]
I'm not exactly sure what is being asked for here, and i odn't really know anything about this LSIF format.  But at first glance, this seems very hard to do as it's asking for reverse links.  So we'd have to, per symbol, find all the references to it and then encode that into the final file.  Not sure how we can do that efficiently.

**Comment by noellelc** [comment]
I think it would be valuable to set up some time with @Dirk ***@***.***> to discuss how he's implementing it for TypeScript, as the creator/owner of LSIF.
