### ISSUE TITLE
Remove Unnecessary Braces Refactoring

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#59628]
Direct customer ask copying here: 

> A tiny thing I just ran into that I was surprised wasn’t there: Remove Unnecessary Braces.
 
![image](https://user-images.githubusercontent.com/46729679/154583988-328c5702-9664-470e-8f9e-acd78eef3c17.png)

> I would like to just Alt-Enter with my cursor on the brace and have it remove them and unindent the block.

**Comment by jinujoseph** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/19229

**Comment by jinujoseph** [comment]
cc @mikadumont
