### ISSUE TITLE
WPF UserControl inheriting abstract class should have a quick action to implement it

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59623]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WPF-UserControl-inheriting-abstract-clas/1649935)._

---
Given an abstract control such as:

```
public abstract class Foo 
{
    public abstract string GetString();
}
```

and a UserControl defined as such:

```
public partial class Bar : Foo 
{
    public Bar()
    {
        InitializeComponent();
    }
}
```

It should be possible to use quick actions to implement the GetString() function. Currently it's necessary to remove the partial definition and rename the class to `Bar2` to be able to use the quick actions and then put the partial definition back.

It would be nice if VisualStudio could detect this case and correctly add the quick action

---
#### Feedback Bot on 1/28/2022, 11:36 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/4564579/154584815-544bd207-78ec-4c68-baf2-80064e6eb325.png)

We'd need a fuller explanation of what is going on to address anything here.
