### ISSUE TITLE
IDE0055 (Fix formatting) errors after upgrading to SDK 6.0.200 (VS 17.1.0)

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/roslyn#59637]
### Analyzer

**Diagnostic ID**: [IDE0055](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules): `Fix formatting`

### Analyzer source

**SDK**: [SDK 6.0.200](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.200](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug
After upgrading VS to the VS 17.1.0 version, when I build my solution I get an IDE0055 error on GlobalSuppression.cs files, the content of the files is something like this

```
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "My reason", Scope = "member", Target = "~M:Method")]
```

If I click on Fix formatting an space is added after "]", but then i got a "SA1028" error
If I add a new line after "]"  the error that appeas is "SA1518".

### Actual behavior
An error is generated with files that end with assembly level attributes.

### Expected behavior
No error

**Comment by mavasani** [comment]
@sharwell

**Comment by sharwell** [comment]
This was caused by #56639. Will send a PR to fix.

**Comment by RehanSaeed** [comment]
I'm still getting this on `6.0.300` also but only running on GitHub Actions on Ubuntu. When building locally using VS 17.3 Preview 1.0 or the CLI, it builds the code just fine.

**Comment by sharwell** [comment]
@RehanSaeed This issue only relates to attributes that appear at the end of a file. Can you file a new issue for the behavior you are seeing?
