### ISSUE TITLE
Improve error messages for Json StringSyntaxAttribute

### ISSUE THREAD

**Issue by dotMorten** [dotnet/roslyn#59641]
**Brief description:**

I was playing with the new StringSyntaxAttribute for Json and got it working nicely, here shown with a missing `:` between key and value:

![image](https://user-images.githubusercontent.com/1378165/154612953-24993376-3a05-47a5-a3df-5bf3258f1d4d.png)

The error message isn't the best, and in this specific context can be quite misleading to talk about properties and object.

As @[DavidAnson](https://github.com/DavidAnson) [suggested](https://twitter.com/DavidAns/status/1494512094208663554):
![image](https://user-images.githubusercontent.com/1378165/154613094-ec3e2a43-6356-4762-8239-3414ac01b756.png)

**Additional information:**

Used: Visual Studio 2022 Update 2, preview 1.
Copied the code analyzer from https://github.com/dotnet/runtime/blob/785f81814f873112b2469694524d26c0592aed96/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/StringSyntaxAttribute.cs and added to my .NET 6 project.

**Comment by CyrusNajmabadi** [comment]
Yes.  We should give a specific message for a misplaced string literal in an object literal and have it instead say that a colon is expected.
