### ISSUE TITLE
StringSyntax doesn't recognize {params} arrays, collection initializers, etc.

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#59645]
We have some APIs where parameters accepting string[] are annotated with [StringSyntax(...)], where that is meant to be about all of the strings passed in that array.  For cases where those are literals, it'd be great if Roslyn's support for recognizing that attribute and applying it to literals also handled array elements, params array arguments, collection initializer elements, etc.
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/2642209/154724454-2e1eed50-f084-4fbc-afca-c6574f9fe07e.png">
cc: @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This seems reasonable.
