### ISSUE TITLE
The raw string literal refactoring should have the same diagnostic span as the verbatim string literal refactoring

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#59655]
Version 17.2 Preview 1

Placing my cursor at the end of the line after the semicolon only shows me the refactoring to convert to a verbatim string and not to convert to a raw string. 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/46729679/154770959-f1e5516d-5fcc-484f-adb6-b4218148bb9c.png">

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of feedback.
