### ISSUE TITLE
Behavior changed for [CallerArgumentExpression] in constructor for [InterpolatedStringHandler] for the receiver parameter

### ISSUE THREAD

**Issue by RobinsonWM** [dotnet/roslyn#59661]
**Version Used**: 
`4.1.0-3.22075.3 (592501cb)`

**Steps to Reproduce**:

Compile and run this short C# program and observe the console output:
```csharp
using System;
using System.Runtime.CompilerServices;

public class C {
    public static void Main()
    {
        new C().DoLog($"foo={1}");
    }
    
    public void DoLog([InterpolatedStringHandlerArgument("")] LogMessage msg) {}
}

[InterpolatedStringHandler]
public struct LogMessage
{
    public LogMessage(int literalSize, int holeCount, C receiver, [CallerArgumentExpression("receiver")] string rawInterpolationString = null)
    {
        Console.WriteLine(rawInterpolationString);
    }
    
    public void AppendLiteral(string s){}
    public void AppendFormatted(object o){}
}
```

**Expected Behavior**:
On `4.0.1-1.22053.6 (9942dc95)` and earlier, it outputs `$"foo={1}"`

**Actual Behavior**:
On `4.1.0-3.22075.3 (592501cb)` it outputs `new C()`

**Commentary**:
There was a change in behavior between `4.0.1-1.22053.6 (9942dc95)` and `4.1.0-3.22075.3 (592501cb)`.  I did not see any specific documentation about this corner-case, so I am opening this issue to ask whether this change in behavior was intentional or a regression.  I have an application that relied on the old behavior, and when the `mcr.microsoft.com/dotnet/sdk:6.0` Docker image was updated on 2022-02-17 with the new compiler, my application started exhibiting strange behavior at runtime.
In `4.0.1-1.22053.6 (9942dc95)`, if the constructor for a `[InterpolatedStringHandler]` had an argument for the receiver, and a later parameter used `[CallerArgumentExpression]` for the receiver, the old version of the compiler would insert the raw interpolation expression.  The new version inserts the expression that was used to reference the receiver.
I am not aware of another way to obtain a string literal containing the raw interpolation expression, so it appears that a capability has been removed from the language.

**Comment by jcouv** [comment]
Tagging @333fred to advise.

**Comment by 333fred** [comment]
This behavior change is correct. The expression being passed to the receiver parameter _is_ the receiver of the method call, so the previous behavior was a bug. There is no way to obtain a caller arg expression of the string being passed to LogMessage other than in LogMessage itself. Arguably it could be added, but that's a language change, not a bugfix.
