### ISSUE TITLE
Proposal: Access Modifier on Optional Parameters

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#5966]
Optional parameters are used to easily define various overloads for a method but with the ability to attach an access modifies on them one can use optional parameters internally and doesn't expose them to the client. e.g.
```cs
public static void F(int input, private int arg = 0) {
    ...
    F( ... , arg + 1);
}
```
can't be called with second parameter outside of the `private` scope.
```
Foo.F(input);
```
- Allowed access modifiers in this context would be anything except `public` which is default.
- Parameters with access modifiers would be declared in order from least restrictive modifiers to most restrictive ones.

**Comment by HaloFour** [comment]
This is a big departure from how optional parameters work in C# (or the CLR).  They don't define overloads, they only define metadata to supporting compilers to allow them to automatically push an argument value.  I assume that from your example that what you want to have happen is that the following code is "generated" by the compiler:

```cs
public static void F(int input) {
    F(input, 0);
}

// automatically generated, accessibility defined by the "optional" parameter
private static void F(int input, int arg) {
   ...
   F( ..., arg + 1);
}
```

So what if you have multiple optional parameters, each with their own accessibility modifier?

```cs
public static void F(int input, private int arg1 = 0, protected int arg2 = 1) {
    ...
    F( ..., arg1 + 1, arg2 + 2);
}
```

Would that generate the following?

```cs
public static void F(int input) {
    F(input, 0, 1);
}

protected static void F(int input, int arg2) {
    F(input, 0, arg2);
}

protected static void F(int input, int arg1, int arg2) {
    ...
    F( ..., arg1 + 1, arg2 + 2);
}
```

**Comment by alrz** [comment]
@halofour I was about to add the second bullet.

**Comment by dsaf** [comment]
What is the plan for other languages: http://stackoverflow.com/questions/5456989/is-the-new-feature-of-c-sharp-4-0-optional-parameters-cls-compliant ?

**Comment by gafter** [comment]
@alrz is there a corresponding CLR proposal?

**Comment by alrz** [comment]
@gafter there isn't AFAIK

**Comment by gafter** [comment]
@alrz This doesn't seem like the sort of thing we'd want to put in the language absent CLR support.

**Comment by alrz** [comment]
@gafter obviously it needs CLR support to expose the modifiers. but since we have optional parameters already this would make them more useful in case of the need to declare another method just for restricting parameters.

**Comment by gafter** [comment]
@alrz In the unlikely event that the CLR team adds this feature, we'll look at adding language support.

**Comment by paulomorgado** [comment]
Optional arguments (parameters aren't really optional) used on non-private (and, with extreme careful, internal) members is a recipe for disaster.

And this proposal just adds more confusion to it.

**Comment by alrz** [comment]
@paulomorgado Two terms used interchangeably, but yes "optional arguments" would make more sense. I was just wondering why do they exist the way they do now, while it's highly recommended to avoid them? I just wanted to make them more useful and maybe they should've implemented by implicitly declared overloads instead of injecting default values in callsite. Since that wouldn't backward compatible and as you said it will be a disaster I just close this.

**Comment by paulomorgado** [comment]
They exist in Visual Basic for historical reasons and are useful in C#, not for producing them but for calling things like COM (and badly written Visual Basic :smile:).

I use them myself on private methods only. They are safe to use this way.
