### ISSUE TITLE
Interactive should provide ScriptPath property that provides the path to the running script

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#5967]
A ScriptRoot property that also contains the directory the running script lives in is also a good idea.

**Comment by agocke** [comment]
@tmat FYI

**Comment by tmat** [comment]
I agree it should be an easily accessible piece of information.

As a workaround one can define a script method that returns this information:
```C#
string GetScriptPath([System.Runtime.CompilerServices.CallerFilePath]string path = null) => path;
```

You can also declare in in a utils.csx file and #load that file:

```C#
#load "utils.csx"

Print(GetScriptPath())
```

**Comment by tmat** [comment]
Instead of introducing a bunch of properties, we should perhaps have a single one "Script" (or it could be a static class) with various properties. 

```
Script.Path
Script.Directory
Script.Language
```
etc.

**Comment by ManishJayaswal** [comment]
This is covered in #5979 so closing this as dupe.
