### ISSUE TITLE
Can't debug EditorFeatures layer

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59673]
Followed [this](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md) instructions on how to debug roslyn with VS. However, if I place breakpoint here:
https://github.com/dotnet/roslyn/blob/7e835c8c324e294b467ba69648a2049e3acbcc6f/src/EditorFeatures/Core/Implementation/LanguageServer/Handlers/Hover/HoverHandler.cs#L50 ...which _should*_ trigger, whenever I hover ower method or class, and then try to hit it, it just don't work for me.

_*_ - well, first, name suggests, that this class is used to handle hover logic. Second, if I search in the repo with "Hover" request, most results reference different places in this file or it's test.

Checked **VS 17.1** and **VS 17.2 Preview 1**. The behaviour is identical in both cases.

**Comment by CyrusNajmabadi** [comment]
HoverHandler is only used is LSP cases. You'd likely want to set a breakpoint on one of the QuickInfo types instead.
