### ISSUE TITLE
Regression of type argument detection in 6.0.101 (CS0411)

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/roslyn#59699]
### Description

Code that was working now gives a [CS0411](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0411).

### Reproduction Steps

The code that no longer compiles:

    var funcs = (new[]{"Turn this string into a func that returns the string"}).Select(x => () => x);

Essentially using LINQ to turn an array of strings into Funcs that return those strings. The exception is from the `Select` method.

### Expected behavior

No error

### Actual behavior

>CS0411	The type arguments for method 'Enumerable.Select<TSource, TResult>(IEnumerable<TSource>, Func<TSource, int, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

### Regression?

✔6.0.100
❌6.0.101

### Configuration

Windows 10 x64

**Comment by Youssef1313** [comment]
I think this is tracked in https://github.com/dotnet/roslyn/issues/57779
@cston to confirm.

**Comment by cston** [comment]
@danielchalmers, thanks for reporting this issue.

The type inference behavior for this scenario was changed in https://github.com/dotnet/roslyn/pull/57713 to revert to the C#9 behavior. We will investigate enabling this in https://github.com/dotnet/roslyn/issues/57779 as @Youssef1313 indicated.

**Comment by cston** [comment]
Closing as this issue is tracked by https://github.com/dotnet/roslyn/issues/57779.

**Comment by danielchalmers** [comment]
thank you for all the info!
