### ISSUE TITLE
Incorrect entries being shown after calling FindEntryPoints

### ISSUE THREAD

**Issue by melytc** [dotnet/roslyn#59696]
**Version Used**: 17.2 Preview 2

**Steps to Reproduce**:
The project system is calling [FindentryPoints](https://github.com/dotnet/roslyn/blob/587388c52c4aefb5010e972c619222f4025182f1/src/VisualStudio/VisualBasic/Impl/ProjectSystemShim/EntryPointFinder.vb#L26) when populating the Startup Object property in the Project Properties UI (see [here](https://github.com/dotnet/project-system/blob/6d9a0248f63682e4d8071534329d6770f6e2770a/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/StartupObjectsEnumProvider.cs#L87)). This is done for both the C# and VB scenarios, with the distinction that the VB scenario will be called with the flag `findFormsOnly = true`. However, calling that function returns a set of unexpected entries.

**Expected Behavior**:
Only returns forms entries.

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/8518253/155248419-a1911427-01bb-4739-93dd-a33285f8a726.png)

**Comment by melytc** [comment]
For the VB scenario, we are expecting to receive:

- Every Form in the Assembly directly or indirectly inherited from Form. 
- Every Module which holds a Sub Main (Public, Friend, Protected) 
- Every Class which holds a Shared Sub Main (Public, Friend, Protected) 

From the testing I've done, I can see that Forms and Modules are correctly sent. Would it be possible to add Classes to the entries?

I tried to fix it myself but got lost trying to debug it. If you (@jmarolf) have time next week, @drewnoakes and I would be down to learn by doing some pair programming. :)

**Comment by jmarolf** [comment]
@melytc sounds great! I'll send a meeting invite to we can get to the bottom of this.
