### ISSUE TITLE
False positive CS0826 on empty array

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/roslyn#59701]
**Version Used**: 

Dotnet sdk 6.0.101

**Steps to Reproduce**:

`string[] array = new[]{};`

**Expected Behavior**:

No error

**Actual Behavior**:

> `No best type found for implicitly typed array.`

**Comment by CyrusNajmabadi** [comment]
Closing out as not a roslyn issue.  Lang change can be tracked at teh linked issue above.
