### ISSUE TITLE
Implicit operator conflicting with `&staticFunction`

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/roslyn#59703]
### Analyzer

**Diagnostic ID**: [IDE0004](https://docs.microsoft.com/en-en/dotnet/fundamentals/code-analysis/style-rules/ide0004): `cast is reduant`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.101](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug

Shows reduant cast info, but when removed, code errors.

### Steps To Reproduce

Implicitly convert `delegate*` of static function to something.

### Expected behavior

No error.

### Actual behavior

Error

## Additional context

https://github.com/SupinePandora43/TechDemo/blob/daf2337f397d55404c38bd773385bbc85628d0ba/src/TechDemo/Program.cs#L49

**Comment by mavasani** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I don't repro this on latest roslyn.  What version of VS are you using?

**Comment by SupinePandora43** [comment]
> I don't repro this on latest roslyn. What version of VS are you using?

VSCode

**Comment by CyrusNajmabadi** [comment]
I'm not sure how VSCode works here.  They may not be up to date with Roslyn.  Does this repro in VS?
