### ISSUE TITLE
API Extensions: ILocalSymbol.IsReadOnly

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#59709]
## Background and Motivation

Sometimes a rewriter/analyzer needs to know if a local symbol is readonly, or not.
A non const ILocalSymbol is readonly for example for:
- fixed variable
- foreach iteration variable
- using variable

Without it is very difficult to determine if for example a managed pointer (aka `ref`) to that local can be created.

## Proposed API

ILocalSymbol should get a new Property "IsReadOnly" like we have them for `IFieldSymbol`.

```diff
namespace Microsoft.CodeAnalysis
{
  public interface ILocalSymbol
  {
+     bool IsReadOnly { get; }
  }
}
```

## Usage Examples

``` C#
ILocalSymbol local = ...
if (local.IsReadOnly){
  //handle readonly
} else{
  //handle non readonly
}
```

## Alternative Designs

Add properties for the specific readonly-situations like `IsForEach` and `IsUsing` - similar to `IsConst` and `IsFixed`.
Those could be added additionally, too.

## Risks

No known risk.

## Implementation hint

We need to negate just: https://github.com/dotnet/roslyn/blob/fd441234f5a516fae447785f860001e99c05cf71/src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs#L273

**Comment by bernd5** [comment]
Currently I'm in favor of the alternative Design because the "readonly foreach/using var" does not do an implicit copy on non-readonly member access which is usually the case.
(Not sure if it is specified in the spec)

**Comment by jcouv** [comment]
@333fred I think all the details were provided in this request. I'm moving to Compiler.Next by default, for discussion.

**Comment by bernd5** [comment]
Because the foreach and using variable do not have full readonly semantics (copy on non-readonly member usage for value types) it might be better to call the property `IsAssginable` instead of `IsReadonly`.

**Comment by 333fred** [comment]
@AlekseyTs as area owner.

**Comment by AlekseyTs** [comment]
We already have ```ILocalSymbol.IsConst``` add ```ILocalSymbol.IsFixed```. Another alternative would be to add ```IsForEach``` and ```IsUsing``` properties.

**Comment by bernd5** [comment]
I would be okay for me with those specific properties - especially because of different  semantics.

**Comment by 333fred** [comment]
## API Review

The alternative design is approved.

```diff
namespace Microsoft.CodeAnalysis
{
  public interface ILocalSymbol
  {
+     bool IsForEach { get; }
+     bool IsUsing { get; }
  }
}
