### ISSUE TITLE
CallerArgumentExpression with "dynamic" variable not working

### ISSUE THREAD

**Issue by olivier-theatre** [dotnet/roslyn#59704]
### Description

When using the CallerArgumentExpression attribute and passing a "dynamic" object, I get a null value instead of the variable name.

Here are some examples of method signature I wrote:
- public static void IsNotNull(object? guardedObject, [**CallerArgumentExpression**("guardedObject")] string? name = null)
- public static void IsNotNull(dynamic? guardedDynamic, [**CallerArgumentExpression**("guardedDynamic")] string? name = null)

In both case, when passing a "dynamic" variable for "guardedObject or "guardedDynamic" parameter, the "name" variable is not filled.

Is-it an expected behavior ?

Thanks in advance for your response.

### Reproduction Steps

Create a method with a signature such as:

- public static void IsNotNull(object? guardedObject, [CallerArgumentExpression("guardedObject")] string? name = null).
- public static void IsNotNull(object? guardedObject, [CallerArgumentExpression("guardedObject")] string? name = null)

Call this method with a dynamic variable for the guardedObject parameter:

dynamic myDynamicVariable = <get an object here>;
EnsureThat.IsNotNull(myDynamicVariable);

### Expected behavior

I expect the "name" parameter from CallerArgumentExpression to be filled with the name of the passed variable.

### Actual behavior

The "name" parameter from CallerArgumentExpression is not filled.

### Known Workarounds

I manually pass the name of the dynamic variable as the CallerArgumentExpression name parameter.

EnsureThat.IsNotNull(myDynamicVariable, nameof(myDynamicVariable));

**Comment by Youssef1313** [comment]
This is the same behavior for `CallerMemberName`.

```csharp
#nullable enable

using System.Runtime.CompilerServices;

var c = "X";
C.M(c); // prints <Main>$

dynamic c2 = "X";
C.M(c2); // prints (null)

public class C
{
    public static void M(object? g, [CallerMemberName] string? name = null)
    {
        System.Console.WriteLine(name ?? "(null)");
    }
}
```

And it's by-design. From [Caller-info attributes](https://github.com/dotnet/csharpstandard/blob/75ffd87b805cda3e1355ba8e93c91ba41a968908/standard/attributes.md#2155-caller-info-attributes):

> Caller information is only substituted when a function is explicitly invoked in source code. Implicit invocations such as implicit parent constructor calls do not have a source location and will not substitute caller information. Also, calls that are dynamically bound will not substitute caller information. When a caller-info attributed parameter is omitted in such cases, the specified default value of the parameter is used instead.

**Comment by jcouv** [comment]
Thanks @Youssef1313 for the explanation. Closing as by-design.
