### ISSUE TITLE
Extract Interface or Create new type generates copyright information from origin file including the file name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59715]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extract-Interface-or-Create-new-type-gen/1666011)._

---
[severity:It bothers me. A fix would be nice]
Repro steps:

Goto a class and under quick actions select "Extract Interface"
OR
Goto a class and select quick actions under a undefined type and select "Generate class"

Expected Result:
File is generated with the right filename in the copyright.

Actual Result:
File is generated with the filename where the request orginated.

---
#### Feedback Bot on 2/15/2022, 10:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
