### ISSUE TITLE
Change signature refactoring window removes "?" when specifying a nullable type when adding parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59718]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Change-signature-refactoring-window-remo/1670575)._

---
With an existing method, e.g.:

```
public async Task Upsert<T>(T item)
        where T : class
    {
```
Press ctrl + . and choose "Change signature".
Choose "Add" (parameter)
Type name: "string?" (note the question mark to specify that the string should be nullable)
Parameter name: customerId
Parameter Kind: Optional with default value: (and type in) null
Value to inject at all call sites: Omit

Should result in methods being updated with `string? customerId` but instead are updated with `string customerId`.

Can you possibly look into this since we're all embracing C#8's nullable reference types please?

---
#### Feedback Bot on 2/20/2022, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
