### ISSUE TITLE
Provide option to disable Source Link for Go To Definition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59717]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-option-to-disable-Source-Link-fo/1669243)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.0]
Always getting the prompt "Do you want to use Source Link " anytime I use Go To Definition is annoying.

I don't need Source Link if I just want to see public api surface information.

I disabled Source Link (and source link server support) in the Debugging-settings, but that doesn't have any effect on the Go To Definition-support for Source Link - please respect developer choice and don't nag them if they don't want to:
! [grafik.png] (https://aka.ms/dc/image?name=Bcd760d2fd85c401badedd07029150d26637807052142831035_20220217-153332-grafik.png&tid=cd760d2fd85c401badedd07029150d26637807052142831035)

This makes a horrible user experience.

---
#### Feedback Bot on 2/17/2022, 06:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @mikadumont

**Comment by chuckries** [comment]
@tmat correct. It should be removed in 17.2 Preview 2.

**Comment by AliveDevil** [comment]
Ok, now it doesn't ask any but it just straight up uses SourceLink to download the source files, VS 17.2.3:

![image](https://user-images.githubusercontent.com/734738/174041078-cde56f5d-7536-4619-82e0-3f69e879e102.png)

**Comment by davidwengier** [comment]
@AliveDevil The setting you've highlighted affects Source Link when debugging, but not in Go To Definition. At the moment there is no setting to outright disable Source Link for Go To Definition, but I'd love to know what your scenario is that makes you want it.

There is a potential workaround, depending on your set up, where you can turn off the "Always use Microsoft and Nuget symbol servers" option (or similar; I may have remembered the wording on that wrong) under Tools, Options, Text Editor, C#, Advanced. If you then don't have any symbol servers ticked in the Symbols settings, under Debugging options, then Source Link requests would fail and you'll just see decompilation or metadata.

**Comment by AliveDevil** [comment]
I have disabled all symbol servers and disabled the option "Always use default symbols for navigation", which doesn't have any effect.

Reason I'm not fond of source link integration: There sometimes is noise in those sources (e.g. ReactiveUI DynamicData ObservableCollection, where some `#ifdef` are inside the source link files).
Most of the time I'm fine with just seeing the reference disassembled public surface of libraries I'm consuming for finding some functionality - and the general idea of downloading the source files to some cache location which is opaque to where it lands.
If I'm then required to look into the sources I just go to Github, or disassemble the implementation library in ILSpy, which doesn't include ifdefs and is literally the implementation, that is used for my application.

**Comment by brian-reichle** [comment]
I'm with @AliveDevil on this one. 99% of the time when I use go-to-definition, I'm interested in the api shape and method signatures; I'm not interested in implementation. The code provided by source link will often obfuscate the information I'm after (and that's before you take into account the formatting differences); If the class happens to be a partial class, the information I want might not be there at all. Perhaps the ideal situation would be to have both available via different commands so that we can choose the command that best fits the task at hand.

**Comment by CyrusNajmabadi** [comment]
@davidwengier 

> I'm with @AliveDevil on this one. 99% of the time when I use go-to-definition, I'm interested in the api shape and method signatures; I'm not interested in implementation.

can we consider a block-structure set of rules that will then collapse the source-link code such that it looks just like the code you would see when looking at metadata-as-source?  That way we can hopefully have a reasonably middle ground?  Specifically, that the code looks just like api-shape/method-signatures for those that just need that, but it can also be expanded to see the underlying code by people who care?

Users could then just control this through this property:

![image](https://user-images.githubusercontent.com/4564579/181349609-eb892db5-0223-48e3-8388-c1c75edb4d85.png)

**Comment by davidwengier** [comment]
Unless I'm misunderstanding, that is what that setting does. I don't think there is a diffference between the collapsing logic of "Collapse Source Link" versus "Collapse metadata signatures", the settings only control when the collapsing is done, not how.

**Comment by CyrusNajmabadi** [comment]
Oh, ok then.  @AliveDevil  can you just use that option then?

**Comment by brian-reichle** [comment]
@CyrusNajmabadi no amount of collapsing will help if the class definition is split across multiple files using partial classes, and the file selected doesn't contain the information you are looking for.

**Comment by tmat** [comment]
I think a separate command for viewing metadata would be definitely useful. There are two distinct scenarios when users want different things:
1) Look at the actual implementation, possibly placing breakpoints into it.
2) Look at the shape of the public API, not interested in implementation.

I don't think we can reconcile these into a single view.

Re partial classes: we should download all files that contain the partial definition and GTD should offer the list when invoked on the type definition. @davidwengier does that work currently?

**Comment by davidwengier** [comment]
Firstly, for background, my intention with this issue was simply to collect feedback and see if there was enough votes and comments to justify adding the option as stated in the issue description.

> I think a separate command for viewing metadata would be definitely useful

This is part of the original plans for better GTD that we were working with the editor team about. Not sure where that would be tracked (@mikadumont do you know?) or what the status is.

> we should download all files that contain the partial definition and GTD should offer the list when invoked on the type definition. @davidwengier does that work currently?

That is tracked by https://github.com/dotnet/roslyn/issues/59713

**Comment by AliveDevil** [comment]
What about roslyn analyzer generated code then? Source Link has no idea where that code came from as its completely transient.
With metadata-only this is a no-brainer as it’s all there.

**Comment by davidwengier** [comment]
It's probably not the answer you want to hear, but code generated by a source generator is embedded in the PDB directly, so will be shown without needing anything from Source Link. Sorry! 😁

Rest assured, you don't need to sell anyone on the scenarios where metadata is useful, we're not debating that.

**Comment by AliveDevil** [comment]
Seeing that your PR went into Visual Studio on build `32802.320` and the current release is `32804.467` … frankly I don't see that option in the Text Editor\C#\Advanced-Tab, as shown in the PR animation.
Even reenabling Source Link support in the debuggern doesn't bring that option in. Anything I'm missing?

**Comment by davidwengier** [comment]
VS build numbers sadly don't work like that, and those two builds will be from different branches. The new option should be in the next preview version released.

**Comment by AliveDevil** [comment]
Oh well, thanks for clarification.
Awaiting 17.4 / 17.3.x whichever first includes that option in public release then.

**Comment by davidwengier** [comment]
> why is there no fallback to metadata if navigation to source link fails?

There is. If you're seeing the "cannot navigate to symbol" message then something else could be going on. If you can work out how to repro it, it would be good to log a new issue.

**Comment by AliveDevil** [comment]
Repro, 100% success.

https://user-images.githubusercontent.com/734738/184885803-0f8f852b-c608-455e-8a31-2e379a0f1ea3.mp4

[sl-gtd.zip](https://github.com/dotnet/roslyn/files/9351205/sl-gtd.zip)

**Comment by cremor** [comment]
@AliveDevil Thanks, that's also what I'm seeing. Could you please create a new issue for it?

@davidwengier So there is no way to disable "navigate to source link" in 17.3?

**Comment by AliveDevil** [comment]
> disable "navigate to source link" in 17.3?
I read the comment that in 17.3 the previously mentioned checkbox to disable navigate to source link isn't available, as it is only included in 17.4 Preview. Or, if by any chance this change gets backported to a patch-release of 17.3, then any 17.3.x-release.

**Comment by CyrusNajmabadi** [comment]
This will not get backported to 17.3.  17.3 fixes will only be for critical, world breaking issues (e.g. bad crashes in super common cases).  In the meantime though 17.4 previews are out :)

**Comment by castholm** [comment]
Is there any way to disable SourceLink completely and always get the "from metadata" result when using GTD?

While I can't speak for anyone else, this recent change has affected my productivity in Visual Studio negatively. Even with the new collapsing behavior I find the SourceLink results make for a poor developer experience when 99% of the time all I want is view is the public API surface.

Having private/internal members, field assignments and single-line property/method implementations included in the results is very distracting and makes it difficult to visually scan the results and locate the public members. Sometimes you can't even find immediately certain public members at all because they are hidden away in partial classes.

**Comment by cremor** [comment]
@castholm Yes, starting with VS 17.4. See #63089

**Comment by jez9999** [comment]
> @AliveDevil The setting you've highlighted affects Source Link when debugging, but not in Go To Definition. At the moment there is no setting to outright disable Source Link for Go To Definition, but I'd love to know what your scenario is that makes you want it.

I've got a scenario: it's broken.  On multiple occasions I've pressed F12 and it has not gone to anything useful.  For example, I hit F12 on `ValueTuple` and it takes me to the top of `DateTimeOffset.cs` for some reason.  See [my StackOverflow post](https://stackoverflow.com/questions/74210217/sourcelink-f12-doesnt-work-properly-in-visual-studio-2022) for more examples.  There should *definitely* be an option to disable "sourcelink on Go To Definition".

**Comment by CyrusNajmabadi** [comment]
@jez9999 there is such an option:

![image](https://user-images.githubusercontent.com/4564579/199287091-c9d34bc1-a29c-4cc3-8d38-fc2d0520d9b9.png)

**Comment by jez9999** [comment]
> Reference in new

Yep, happily that seems to work in disabling it for me.

**Comment by cremor** [comment]
> I used the Options search feature to find it, but searching for "sourcelink" returned nothing, and "source link" only returned the Debugging option. I'm using 17.8 LTSC.

See #72639
