### ISSUE TITLE
VS crash when removing project from multi project solution

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#5972]
Repro:
1. Create new VB console application.
2. Add a 2nd new console application to the solution.
3. Remove the 2nd project from the solution.

VS then crashes. 

System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.CodeAnalysis.Workspaces.dll
Additional information: Object reference not set to an instance of an object.

**Comment by Pilchie** [comment]
This seems to be caused by recent (internal) changes to prevent serializing TS projects to the CodeLens out of process workspace.

**Comment by balajikris** [comment]
Looking..

**Comment by balajikris** [comment]
Fixed internally with PR 5513

**Comment by balajikris** [comment]
Fix should be in last night's build.
