### ISSUE TITLE
[LSP] Semantic tokens regex colorization incorrect

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#59731]
Using LSP semantic colorization (32222.65.main):

Actual:
![image](https://user-images.githubusercontent.com/16968319/155470090-6afb4050-4c45-4c37-8a20-571f7b5adb00.png)

Expected:
![image](https://user-images.githubusercontent.com/16968319/155470195-4e5cc8a5-fc84-45dd-9285-453b4ccb9fe8.png)

**Comment by dibarbet** [comment]
I can repro the behavior in the actual screenshot on old version of int.preview, but am not seeing it on the latest main from today (32303.288.main).

@allisonchou can you confirm it's working for you as well?
![image](https://user-images.githubusercontent.com/5749229/156684882-88799150-e976-42bb-9639-d3aea805cb13.png)

**Comment by allisonchou** [comment]
@dibarbet yep, seems to be working for me too in the latest main:
![image](https://user-images.githubusercontent.com/16968319/157564601-8f4f18c4-4652-4980-8814-820f47fe1ea6.png)

I don't think anything changed recently on our side in the semantic tokens space, maybe it was a platform issue?
Will go ahead and close out the issue 🙂
