### ISSUE TITLE
RequiresAssemblyFilesAnalyzer throws InvalidCastException  

### ISSUE THREAD

**Issue by nagya** [dotnet/roslyn#59749]
**Version Used**: 6.0.200, bug is new in this version, i.e. was not present in 6.0.1

**Steps to Reproduce**:

1. [Test1.zip](https://github.com/dotnet/roslyn/files/8135375/Test1.zip)
2. `dotnet build`

**Expected Behavior**:

No compile time exception and no warning.

**Actual Behavior**:

```
CSC : warning AD0001: Analyzer 'ILLink.RoslynAnalyzer.RequiresAssemblyFilesAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'. 
```

**Repro project details**:

`PublishSingleFile=true` must be set in the project file, and both type constraints are needed in the source file.

## Test1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
</Project>
```

## Class1.cs
```
namespace Test1;

public abstract class Class1<T> where T : Class1<T>, new() { }
```

**Comment by Youssef1313** [comment]
This is not related to dotnet/roslyn. It should go in dotnet/linker instead where the implementation of this analyzer exists.

https://github.com/dotnet/linker/blob/2999a6a9dd884d554be18d3c86a4a9db4b61e156/src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs
