### ISSUE TITLE
Source Generators break Sync Namespaces feature

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59748]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Source-Generators-break-Sync-Namespaces-/1589153)._

---
[severity:It's more difficult to complete my work]
Using the Source Generators feature (I have a MWE with StrongInject) seems to break Sync Namespaces functionality.

StrongInject: https://github.com/YairHalberstadt/stronginject
MWE: https://github.com/LiHRaM/stronginject-sync-namespaces-mwe

StrongInject is a compile-time dependency injection framework, and whenever I move interfaces or classes that it refers to, Sync Namespaces errors. 

Trying to sync the namespaces within the project will return the error: `The solution does not contain the specified document.`

---
#### Feedback Bot on 11/18/2021, 06:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/19/2021, 00:07 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
@YairHalberstadt do you mind explaining the repro here a bit better? I have the MWE, do I just change move `Demo` to a folder?

**Comment by ryzngard** [comment]
or @LiHRaM who I think actually filed the issue and has the MWE

**Comment by LiHRaM** [comment]
Sure, I'll try to see if I can reproduce the behavior again with the latest Visual Studio and then I'll do a writeup of how to induce the error.

**Comment by LiHRaM** [comment]
This is no longer an issue on VS 17.0.6, so as far as I'm concerned you can close this issue. :smile:

**Comment by ryzngard** [comment]
@LiHRaM perfect! I was testing in 17.1 and didn't hit it so thought I might be doing something wrong. I'll close, thanks for the quick follow up :)
