### ISSUE TITLE
Visual Studio hangs when typing """

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/roslyn#59741]
**Version Used**: 
VS 2022 Enterprise 17.2 preview

**Steps to Reproduce**:

1. Open VS 2022
2. Open a C# editor, such as C# Interactive
3. Quickly enter three quote characters (""") (the new raw string literal start token)

**Expected Behavior**:
IDE will generate the close token """, cursor is the middle of the start token and the end token. ("""|""")

**Actual Behavior**:
IDE hangs, display a message box saying a background operation is in progress, Cancel button does not work.

**Comment by RikkiGibson** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/59848
