### ISSUE TITLE
`NotNullIfNotNullAttribute` doesn't work for nullable value-typed parameters

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#59764]
**Version Used**: 
VS2022 17.2p1

**Steps to Reproduce**:

Type code to test the usages on `NotNullIfNotNullAttribute`:

```csharp
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

f(null, null);
f(null, 42);
f(42, null);
f(42, 42);
g(null, null);
g(null, 42);
g(42, null);
g(42, 42);

static void f([NotNullIfNotNull("b")] int? a, [NotNullIfNotNull("a")] int? b)
{
    if (a.HasValue)
    {
        Console.WriteLine(a.Value);
        Console.WriteLine(b.Value); // Warn here.
    }
    if (a != null)
    {
        Console.WriteLine(a.Value);
        Console.WriteLine(b.Value); // Warn here.
    }
    if (a is not null)
    {
        Console.WriteLine(a.Value);
        Console.WriteLine(b.Value); // Warn here.
    }
}

static void g([NotNullIfNotNull("b")] object? a, [NotNullIfNotNull("a")] object? b)
{
    if (a != null)
    {
        Console.WriteLine(a);
        Console.WriteLine(b);
    }
    if (a is not null)
    {
        Console.WriteLine(a);
        Console.WriteLine(b);
    }
}
```

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABNmTHAWACgyABAJgEZKAGXCmgOgBEoIBzGAewGcALlADG/FgGFeAE2wBBQqgCe/KPwDcZMgDMAFCnQAaXAdQBKTaT2njAFioWdu+8dOOrzqnYeWu+tKiuAe5+Nrj2IZ5B6JEu4T5apMwAbEy2uHoA2gByvILZAQCS2rn5AboARMAVZgC6uLCCAPy4EMY5eQXoxaVdqJUQNfWNLcBmZADeZLgzDdq4uhAsABIQ/ABqEKjI2OOks7hT+wezzACciyyb27uWJ6c0F8BXWzvuBwC+07NQ84u4AEIALwmYLfGZHe4zc6Xa5vO5QmHPOG3cG4L7HGa/BYQBr8Ex5UExNGQxGPWGvVGYk5Il43d6zDEYyg0VIUdJ+DplbolTrlKpDXC8YAAK2wImarXavSKvO5/QqgzqQtF4slY0maOx/2BRPMJLRBxhEAZ9yRpvRWr+uLUBMEer2B1JZvJJoRLqeFqZQA==)

**Expected Behavior**:

Both methods `f` and `g` don't warn.

**Actual Behavior**:

Three warns of CS8629 (Nullable value types may be null) are raised on `b.Value` in `Console.WriteLine(b.Value)`, in the method `f` (method `g` doesn't warn).

**Comment by RikkiGibson** [comment]
It doesn't look like these are intended usages of the attribute. `NotNullIfNotNull` is a way of expressing the behavior "if the input given by 'parameterName' is not null, then this output (the attributed parameter or return) will be not null".

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullifnotnullattribute?view=net-6.0

I think the observed difference in the warnings between 'object?' and 'int?' here is that `Console.WriteLine` can always accept an `object?`, but accessing `int?.Value` is only safe if the `int?` has not-null flow state.

**Comment by RikkiGibson** [comment]
I hope the answer cleared things up. Feel free to follow up if you have further questions.

**Comment by SunnieShine** [comment]
@RikkiGibson Hello. Thanks for your reply.

I don't think the usage is weird. I think that the second parameter `[NotNullIfNotNull("a")] int? b` means if `a` is not null, then `b` will be also not null.

However, when I tested on this case, `b` is still "maybe null". Through the attribute usage, we can learn that if `a` is not null` (as the given aspect), `b` (as the output aspect) is also not null. Therefore `b.Value` is unnecessary to write as `b?.Value` or `b!.Value`.

**Comment by RikkiGibson** [comment]
It's alright, I'm happy to help clarify.

It sounds like you understand it already, but in case it helps, one way I like to think of these attributes is: when applied to a method, the method is making a promise to the callers about its behavior. The compiler may insert some warnings to try and help the method fulfill that behavior, but the compiler doesn't implicitly fulfill the behavior, the method itself must do that.
