### ISSUE TITLE
'Move to namespace' refactoring does not work for types in the global namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59778]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Can-no-longer-move-a-class-to-a-namespac/1651028)._

---
[severity:It's more difficult to complete my work]
In previous versions, you could press Ctrl + period and you could move to a namespace, this appeares to be no longer the case in VS 2022!

---
#### Feedback Bot on 2/2/2022, 09:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jiahui Zhang (Beyondsoft Corporation) [MSFT] on 2/8/2022, 01:41 AM: 

<p>Thank you for your feedback! We tried to reproduce this issue in C# Console Application (.NET Framework) project, and the class can be moved to a namespace successfully, please refer to the video below:<br>
<img src="https://aka.ms/dc/image?name=Ba28f6e20afec4be4b31879cb4983b7f2637799103633607341_lightbulb.gif&amp;tid=a28f6e20afec4be4b31879cb4983b7f2637799103633607341" alt="lightbulb.gif"></p>
<p>In order to investigate this issue further, can you help to confirm several questions?</p>
<ol>
<li>Which project type and language you use? Can you provide us a simple demo project which can reproduce this issue?</li>
<li>Are you installed any extensions and third party plugins? (Such as Resharper? Could you try to uninstall other extensions and third party plugins and then check whether this issue also reproduces or not?)</li>
<li>Would you please provide us a dynamic video using <a target='_blank' href="https://www.screentogif.com/">https://www.screentogif.com/</a>? So that we can check if there is any difference between our repro steps and yours.</li>
</ol>
<p>Please feel free to let us know if you have any doubt. We look forward to hearing from you!</p>

#### Andrew Scott on 2/9/2022, 04:06 AM: 

<p>I am not sure what to say, but I will explain it the best I can.</p>
<p>I am using Unity 2021, it creates all the project solution etc., and there is an option inside Unity to do the following</p>
<p><img src="https://aka.ms/dc/image?name=Bf7e366ac5e014f718f658ce3b5f354cd637800049373429422_20220209-230216-image.png&amp;tid=f7e366ac5e014f718f658ce3b5f354cd637800049373429422" alt="image.png"></p>
<p>If the player projects is selected, it modifies the project/solution in Visual Studio to the following.</p>
<p><img src="https://aka.ms/dc/image?name=Bcb3c932c876c4bb0a42b9daaeca8cd3a637800050268213729_20220209-230346-image.png&amp;tid=cb3c932c876c4bb0a42b9daaeca8cd3a637800050268213729" alt="image.png"></p>
<p>And when that happens I don’t see move to namespace as shown in the following image</p>
<p><img src="https://aka.ms/dc/image?name=B255850e9b16a4ff18801416d1484edd1637800051339298570_20220209-230533-image.png&amp;tid=255850e9b16a4ff18801416d1484edd1637800051339298570" alt="image.png"></p>
<p>I have also raised this with Unity, in case it is something they are doing wrong. But it is that one option that is stopping this.</p>

#### Feedback Bot on 2/25/2022, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
