### ISSUE TITLE
Analyzer package doesnt work with Roslyn

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#5977]
CSC : warning CS8032: An instance of analyzer Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer cannot be created from C:\ Users\jaredpar\.nuget\packages\Microsoft.Net.RoslynDiagnostics\1.1.1-beta1-20150818-01\tools\Roslyn.Diagnostics.Analyzers.dll : Could no t load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its depend encies. The system cannot find the file specified.. [E:\dd\roslyn\src\Compilers\core\Portable\CodeAnalysis.csproj]

**Comment by jaredpar** [comment]
Looks like we filed at the same time :smile:

duping to #5978 as the team has started running with that one.
