### ISSUE TITLE
[LSP] Razor C# doc comments do not auto-complete

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#59772]
**Version Used**: 17.2-Preview1+ (VSMain)

Originally mentioned by customer in: https://developercommunity.visualstudio.com/t/Blazor-documentation-editing-is-broken/1654897

**Steps to Reproduce**:

1. In a Blazor project pen a Razor file (looks like C# LSP editor polyfills this with client side logic which is outside of LSP)
2. Make the content with cursor at ('|'):    
```
@code {
    /// <summary>
    /// |
    /// </summary>
    public void Bar()
    {
    }
}
```
4. Type out `<br>`

**Expected Behavior**: `<br></br>`

**Actual Behavior**: `<br>`

**Repro gif**:
![devenv_dlBpF951iD](https://user-images.githubusercontent.com/2008729/155774179-80119863-ca69-4481-b349-0086073ed301.gif)

**Comment by dibarbet** [comment]
tracking text edits for completion in #59773
