### ISSUE TITLE
[LSP] Doc comment completions do not auto-insert attribute content

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#59773]
**Version Used**: 17.2-Preview1 (VSMain)

Originally mentioned by customer in: https://developercommunity.visualstudio.com/t/Blazor-documentation-editing-is-broken/1654897

**Steps to Reproduce**:

1. Enable C# LSP editor
2. In a doc comment try invoking the `<see` completion item

**Expected Behavior**:
Inserts `<see cref="|"/>` where cursor is at `|`
![devenv_cgP0iZFIur](https://user-images.githubusercontent.com/2008729/155774843-61d7b131-815b-4703-b89e-e9b17648825b.gif)

**Actual Behavior**:
Just inserts `<see`
![devenv_ulo2t6frwx](https://user-images.githubusercontent.com/2008729/155774665-405690ce-548e-4364-96da-40799e19c16e.gif)

**Comment by dibarbet** [comment]
We need to support text edits from completion, with @allisonchou flag on this mostly works, though we need to fix the caret position.

I remember this was blocked on https://github.com/dotnet/razor-tooling/issues/4408 per https://github.com/dotnet/roslyn/issues/59545#issuecomment-1045207133
![completion_textedits](https://user-images.githubusercontent.com/5749229/156431359-e79fbec8-3b3f-461b-ac52-2e43bc7653ef.gif)

@NTaylorMullen I see the lsp spec change is merged, I guess we only need the vs client implementation?

**Comment by dibarbet** [comment]
Same underlying issue as https://github.com/dotnet/roslyn/issues/59545

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I see the lsp spec change is merged, I guess we only need the vs client implementation?

Ya I believe so

**Comment by dibarbet** [comment]
Quick update - client change is merged, https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/385049 once that flows through will look at supporting the C# and Razor implementation.
