### ISSUE TITLE
Move to toolset with csc and vbc binding redirects

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#5978]
Both csc.exe and vbc.exe need to be shipped with binding redirects.  Right now only VBCSCompiler.exe has a config file that does redirects.

**Comment by agocke** [comment]
This must be a package or delivery deployment problem -- we do have configs right now. Looking into it.

**Comment by jaredpar** [comment]
I'm seeing this in our Microsoft.Net.Compilers package.  Check the one we are using for the Sprint compiler.  It doesn't appear to be in there.

**Comment by agocke** [comment]
Agreed, looks like a NuGet package authoring problem. The files are built, but not included in the nuget package.

**Comment by jaredpar** [comment]
Have we verified they show up on the actual installation? 

@tannergooding for this question in case he knows.

**Comment by agocke** [comment]
Tanner just told me in person that we've seen this in the installation as well, but the exe.config files *are* there.

**Comment by agocke** [comment]
@jaredpar Looks like the exe configs were added  Fri Sep 18 16:45:54, which is after our last toolset compiler update.

**Comment by agocke** [comment]
@jaredpar Is there a reason we're not using the latest toolset compiler?

**Comment by jaredpar** [comment]
@agocke yep.  It has a bug, which of course we fixed immediately after we snapped the toolset, that gets triggered by a specific pattern in our code base.  We had to revert it after taking it because of this.
