### ISSUE TITLE
CS0403, CS0037, CS8978 - Null assignment to nullable generic types

### ISSUE THREAD

**Issue by joshlang** [dotnet/roslyn#59805]
**Version Used**: 

C# 10, VS 2022 (17.1.0)

**Steps to Reproduce**:

```
class A<T>
{
    T? Item = null;  // CS0403
    T? Item2 = (T?)null;  // CS0037
    public A(A<T>? other) => Item = other?.Item; // CS8978
}
```

**Expected Behavior**:

No compiler errors

**Actual Behavior**:

Compiler error `CS0403: Cannot convert null to type parameter 'T' because it could be a non-nullable value type. Consider using 'default(T)' instead.`

Compiler error `CS0037: Cannot convert null to 'T' because it is a non-nullable value type`

Compiler error `CS8978: 'T' cannot be made nullable.`

...

Constraining 'T' to `struct` or `class` makes the errors disappear.  So it seems it doesn't like the difference between null and Nullable<>.  Fine.  

But `default` works.  So clearly, IL generation shouldn't be the issue.

Needing to use `default` makes it so `other?.Item` must be written as `other is null ? default : other.Item`

...

Anyway, clearly there's a workaround and it's an inconvenience, not a showstopper, but it seemed worthy to report anyway.

**Comment by svick** [comment]
The problem is that when `T` is a value type (and not constrained to `struct`), then `T?` means `T` and `default` is not `null`. So there is no way for that code to work.

**Comment by joshlang** [comment]
HOLY SMOKES

Well you're right.  I defined A<int> and looked at intellisense for "Item".

That's super-duper unintuitive.  I expected it to be an `int?`

Alright though - thanks for the speedy answer

**Comment by CyrusNajmabadi** [comment]
> That's super-duper unintuitive. I expected it to be an int?

If you want that, you need to do: 


```c#
class A<T> where T : struct
{
    T? Item = null;
    T? Item2 = (T?)null;
    public A(A<T>? other) => Item = other?.Item;
}
```

Then things should be fine.

**Comment by joshlang** [comment]
Let me clarify

I expected `T?` to be nullable.

The nullable version of whatever T is.

**Comment by CyrusNajmabadi** [comment]
@joshlang Understood.  That's just not how the actual runtime works.  This was determined back when generics were done 17 years ago.
