### ISSUE TITLE
Extraneous padding is not removed when formatting string interpolations

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#59811]
**Version Used**: 4.2.0-2.22123.8 (c5713c64)

🔗 Derived from [AB#1488026](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1488026)
🔗 Related to #24499

**Steps to Reproduce**:

Run **Format Document** on the following code:

```csharp
return $"{      hostAddress?? ""}/{nasTypeId   }/{version??""}";
```

**Expected Behavior**:

```csharp
return $"{hostAddress ?? ""}/{nasTypeId}/{version ?? ""}";
```

**Actual Behavior**:

```csharp
return $"{      hostAddress ?? ""}/{nasTypeId   }/{version ?? ""}";
```

**Comment by CyrusNajmabadi** [comment]
If someone does this, make sure to not touch the format specifier as the semantics of whitespace there is relevant.
