### ISSUE TITLE
Add missing namespace for 'Deconstruct' methods 

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#59817]
**Version Used**:  lastest main

**Steps to Reproduce**:

Create a code referencing Roslyn Utilities, for example:
![image](https://user-images.githubusercontent.com/24360909/156068953-fa54b007-2777-43d4-b6b5-db56e8fb96d7.png)
I create a dictionary and try to deconstruct the KeyValuePair in a ForEach loop. But I can't get a suggestion to import Roslyn.Utilities

**Expected Behavior**:
There should be a suggestion to import this file
https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/InternalUtilities/KeyValuePairUtil.cs
Also, other type which has deconstruct methods should also be considered, like IGrouping

**Actual Behavior**:
No import suggestion is provided.
![image](https://user-images.githubusercontent.com/24360909/156069210-034a91b5-e752-4a02-adc4-f73436937124.png)

**Comment by CyrusNajmabadi** [comment]
I would love this :D

**Comment by sharwell** [comment]
Here's how this was fixed for `GetAwaiter()` extension methods:
https://github.com/dotnet/roslyn/pull/30615

**Comment by BhaaLseN** [comment]
Just wondering, is there a reason why this `Deconstruct` method is not simply added publicly to the `System.Collections.Generic` namespace?

It feels like every other project I have has/had to define their own 
```c#
public static void Deconstruct<TKey, TValue>(KeyValuePair<TKey, TValue> p, out TKey key, out TValue value)
    => (key, value) = (p.Key, p.Value);
```
variant - where one could expect it to be built-in.

**Comment by CyrusNajmabadi** [comment]
That's a question for the runtime @BhaaLseN

**Comment by sharwell** [comment]
@BhaaLseN It was added [directly to `KeyValuePair<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=net-6.0) in .NET Standard 2.1

**Comment by BhaaLseN** [comment]
Great, thanks! 👍

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community pr for this.
