### ISSUE TITLE
IntelliSense in REPL shouldn't show type name for globals

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5983]
![image](https://cloud.githubusercontent.com/assets/41759/10501130/32f4aa6e-7293-11e5-8ef9-6527b57489b6.png)

it should just show `void Print(object value)`

![image](https://cloud.githubusercontent.com/assets/41759/10501178/896c3aba-7293-11e5-8cb4-208e6fa2f78f.png)

![image](https://user-images.githubusercontent.com/41759/78518679-fbf15e80-7775-11ea-8311-adf58a7b3fac.png)

**Comment by amcasey** [comment]
Probably most valuable for the host object - not for regular static imports.
