### ISSUE TITLE
Remove Unused References: Support assembly references

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#59834]
**Version Used**: VS2022 17.0.6

**Steps to Reproduce**:

1. Create a sdk style project, target framework is net48
2. Add some assembly reference
3. Use "Remove Unused References"

**Expected Behavior**:
Remove Unused References

**Actual Behavior**:
Nothing removed

**Comment by CyrusNajmabadi** [comment]
Closing out as by design.
