### ISSUE TITLE
[ask mode]Interactive Editor Features should expose no public APIs

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#5986]
Fixed by https://github.com/dotnet/roslyn/pull/5988

**Comment by tmat** [comment]
@dotnet/interactive

**Comment by gafter** [comment]
#5988 says it fixes #5986, and #5986 says it fixes #5988. But neither has any description of what it is supposed to accomplish.

**Comment by ManishJayaswal** [comment]
@tmat please validate that this is true and then close.
