### ISSUE TITLE
LSIF tool fails with duplicate analyzers

### ISSUE THREAD

**Issue by noellelc** [dotnet/roslyn#59883]
Version Used: 4.0.0-3.21372.2

Steps to Reproduce:

1. Run LSIF tool on certain projects
1. Tool succeeds across several documents within a project
1. Tool throws an unhandled exception:
```
Unhandled exception: System.ArgumentException: Specified sequence has duplicate items
Parameter name: analyzerReferences[2]

```

Expected Behavior:
Tool de-duplicates analyzerReferences

Actual Behavior:
Tool fails if duplicate analyzers are configured.

**Comment by Youssef1313** [comment]
There are couple of `ToBoxedImmutableArrayWithDistinctNonNullItems(analyzerReferences, nameof(analyzerReferences))`:

https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs#L243
https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/ProjectInfo.cs#L351
https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L866
https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L947
https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/SolutionInfo.cs#L87

And also `RequireUniqueNonNullItems`

https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L807
https://github.com/dotnet/roslyn/blob/baa973650a553742bbe5405b5d167b0fc316efbb/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L898

These calls should be eliminated if duplicate analyzers will be allowed.

**Comment by jasonmalinowski** [comment]
We'd likely leave all those checks in place, since having duplicates flowing into that layer might indicate other problems. See https://github.com/dotnet/roslyn/pull/58701 for where we fixed a near-identical bug for the regular references, by fixing it at the place that's more targeted.
