### ISSUE TITLE
Cross-language references to C# methods with out parameters are not found by FAR, GTD, etc.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#599]
Ported from TFS WorkItem: **829965**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** 

<BR>**Steps to reproduce:**<BR><BR>1. Copy/paste into C# class library:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">WithoutOut</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
 
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">WithOut</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">out</SPAN> <SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: black">x</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">;</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

&nbsp;

2. Copy/paste into VB class library:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Class</SPAN> <SPAN style="COLOR: #2b91af">D</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">T</SPAN><SPAN style="COLOR: black">()</SPAN>
        <SPAN style="COLOR: blue">Dim</SPAN> <SPAN style="COLOR: black">c</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: blue">New</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN><SPAN style="COLOR: black">()</SPAN>
        <SPAN style="COLOR: black">c</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #ff0000">WithOut</FONT></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: black">c</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #00ff00">WithoutOut</FONT></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Class</SPAN></PRE>

&nbsp;

3. Add a reference from the VB class library to the C# class library.

&nbsp;

4. Invoke GTD on the call to c.WithOut() in the VB file.

&nbsp;

Expected: GTD should take you to the source location in the C# file

Actual: Metadata As Source

------------------------------

**Revisions:**

1) Created By David Poeschl (11/21/2013 8:20:30 PM)

------------------------------

2) Edited By Andrew Casey (ROSLYN) (6/13/2014 4:03:24 PM)

I hit this while trying to port some code from C# to VB (in Roslyn).

------------------------------

3) Edited By Andrew Casey (ROSLYN) (11/12/2014 10:52:46 AM)

Still happening.&nbsp; Tried to GTD on 

<font color="#2b91af" face="Courier New" size=1><font color="#2b91af" face="Courier New" size=1><font color="#2b91af" face="Courier New" size=1>CustomDebugInfoReader</font></font></font><font face="Courier New" size=1><font face="Courier New" size=1>.TryParseVisualBasicImportString</font></font>
&nbsp;in VB.

------------------------------

4) Edited By Andrew Casey (ROSLYN) (2/11/2015 12:24:55 PM)

Guess the SymbolId for the method has RefKind &quot;Ref&quot; instead of &quot;Out&quot;.&nbsp; Presumably, the comparison needs to be more forgiving for VB symbols.

------------------------------

**Comment by amcasey** [comment]
I'm going to give this a shot.

**Comment by amcasey** [comment]
Back to @dpoeschl  for verification.
