### ISSUE TITLE
Generate Nested Type Quick Fix shouldn't be offered if the name conflicts

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#5990]
Source:

``` C#
class X {
    Point Point;
}
```

This shouldn't offer the Generate _Nested_class quick fix, since it gives a compiler error (`Point` alread exists)

**Comment by dpen2000** [comment]
This should probably be implemented as suggested by @CyrusNajmabadi in #11628 :

> Instead, a nicer way to do things is to offer the feature, but add the 'conflict' annotation on the appropriate node so that teh user knows there will be an issue.... This conflict annotation will then show up appropraite in the preview window.

**Comment by CyrusNajmabadi** [comment]
Haven't heard about thsi being an issue.  And likely confusing if this went away and a user wanted to generate this (maybe renaming the field later).  Keeping around as by design.
