### ISSUE TITLE
Typing a semicolon should move the cursor to the end of the statement

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59913]
If I have this line: _differenceCreator.CreateReportDifferences(testResult, comparisonFiles); 
When I change the last argument to something else, but leave the last 2 characters in place, when I hit the semicolon again, I end up with this:
_differenceCreator.CreateReportDifferences(testResult, newVariable); ;
ReSharper was smart enough to not duplicate the semicolon.

**Comment by sharwell** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/52299#issuecomment-811247953
