### ISSUE TITLE
Add "Inspect value destination"

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59917]
Similar to _Track value source_, there should be a way to track the value destination. In ReSharper, this is called _Inspect value destination_. We have also found _Track value source_ to be less reliable than the comparable _Inspect value source_ from ReSharper.

**Comment by mwelsh1118** [comment]
Agreed.  Example below.

Given this code:
```
public interface IX
{
    void DoSomething();
}

public class Example
{
    public void Caller()
    {
        IX x = null;
        Callee(x);
    }

    public void Callee(IX x)
    {
        x.DoSomething();
    }
}
```
Value tracking the **x** in the line x.DoSomething() will bring up a windows with 4 copies of "Callee(x);" The tracking stops at that point (rather than showing x was assigned null on the line IX x = null;). Highlighting the x in Callee(x); and choosing _Track value source_ does nothing. The tracking window also shows only the file/line number rather than the type/method where the call is.

**Comment by jinujoseph** [comment]
cc @mikadumont , @ryzngard

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
