### ISSUE TITLE
Automatically wrap a long line upon hitting a semicolon

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59911]
When completing a long statement (typing semicolon), ReSharper will wrap the line automatically. It isn't perfect and sometimes needs to be refined after-the-fact, but the automatic formatting is helpful.  We are aware of both the built in word-wrap (which is very arbitrary) and the _Ctrl+.->Wrap every argument->Indent all arguments_ quick fix (which requires manual intervention and only handles argument lists).

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/15406

**Comment by sharwell** [comment]
Duplicate of #15406
