### ISSUE TITLE
O/I icon should show base/derived classes/method in a tree

### ISSUE THREAD

**Issue by mwelsh1118** [dotnet/roslyn#59918]
The blue O & I icons in the left margin bring up a window with the base types, implemented interfaces, and derived types. However, there is no indication of the type hierarchy structure. ReSharper has a comparable _Inspect class hierarchy_ that bolds overriden methods also.

**Comment by CyrusNajmabadi** [comment]
Effective dupe of the issues raised in https://github.com/dotnet/roslyn/issues/58219
