### ISSUE TITLE
Show generic collections in IntelliSense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59920]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-generic-collections-in-IntelliSense/1662322)._

---
When assigning a value to something like `IList<int>`, after typing `new`, show suggestion for `List<int>`, etc.

---
#### Feedback Bot on 2/13/2022, 10:13 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

#### Jan Seriš on 2/27/2022, 11:18 AM: 

<p>This feature is already present. What do you mean? It is even present without the clever code suggestions as default upon Enter key press (or similar) - I use it all the time.</p>
<p><img src="https://aka.ms/dc/image?name=B9a5bb006983f4ad0b79615ae7e657dc4637815862897941323_20220227-201807-image.png&amp;tid=9a5bb006983f4ad0b79615ae7e657dc4637815862897941323" alt="image.png"></p>

**Comment by TahirAhmadov** [comment]
@jinujoseph Hi, any chance this can be added for the next major VS? It'd really be a huge time saver for most C# (and VB.NET etc.) devs out there.

**Comment by CyrusNajmabadi** [comment]
@TahirAhmadov we'd likely take contribution if you were interested. That said, collection literals will likely make this moot.

**Comment by TahirAhmadov** [comment]
@CyrusNajmabadi  Good point about collection literals. Still, I envision an all-encompassing solution, where when doing `new` after an interface, possible implementers are suggested.
I could potentially look into it, which repo would it be?

**Comment by CyrusNajmabadi** [comment]
It's this repo :-)

**Comment by CyrusNajmabadi** [comment]
> I meant, can you provide some pointers which folder it's in?

This would likely be: https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Completion/Providers/AbstractObjectCreationCompletionProvider.cs

**Comment by CyrusNajmabadi** [comment]
Closing out as subsumed by copilot/intellicode.
