### ISSUE TITLE
 indent guidelines Missing on C #

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59926]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/indent-guidelines-Missing-on-C/1669488)._

---
I have Problem with showing  indent guidelines and i checked it in options But its not working and I dont find any solutions on that. Maybe some bad options or Latest Visual studio Version dont have it or I dont Know So please Help and i have it in former versions too

---
#### Feedback Bot on 2/17/2022, 06:47 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by jinujoseph** [comment]
could you paste a screen shot pls

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of communication.
