### ISSUE TITLE
"Power" Member Rename to update Constructors and other References

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59923]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Power-Member-Rename-to-update-Construc/1670571)._

---
One of my favorite features in Visual Studio is the Rename (F2) feature, that updates all the places in my code where a property is used.

I'm proposing that this feature be extended with a "Power Rename", which also updates constructors, and other secondary references.

Consider the following:

```csharp
public class Class1
    {

public string Member { get; set; }

public Class1(string member)
        {
            Member = member ?? throw new ArgumentNullException(nameof(member));
        }

public void Load(string member)
        {
            Member = member ?? throw new ArgumentNullException(nameof(member));
        }

}
```

A rename of Member to MyProperty currently results in:

```csharp
public class Class1
    {

public string MyProperty { get; set; }

public Class1(string member)
        {
            MyProperty = member ?? throw new ArgumentNullException(nameof(member));
        }

public void Load(string member)
        {
            MyProperty = member ?? throw new ArgumentNullException(nameof(member));
        }

}
```

With this feature, it would result into

```csharp
public class Class1
    {

public string MyProperty { get; set; }

public Class1(string myProperty)
        {
            MyProperty = myProperty ?? throw new ArgumentNullException(nameof(myProperty));
        }

public void Load(string myProperty)
        {
            MyProperty = myProperty ?? throw new ArgumentNullException(nameof(myProperty));
        }

}
```

---
#### Feedback Bot on 2/20/2022, 10:02 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
