### ISSUE TITLE
Automatically inserting code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59924]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatically-inserting-code/1662891)._

---
I type something like "node." (note the period at the end) outside of the context of it's definition and visual studio will just populate it with what it think I want, with no prompt, just jumping to the nearest thing, but I know what I want I'm smarter then it, so it shouldn't be inserting anything unless I explicitly perform some key,  ie: Tab. I've tried and tried to hunt down option but it should be hard to turn off visual studio from inserting ANY CODE unless I select it using some kind of key, like Tab.

---
#### Feedback Bot on 2/13/2022, 10:39 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by sharwell** [comment]
You can enable this behavior manually here:
![image](https://user-images.githubusercontent.com/1408396/157519787-e87e49b8-0dc4-4b74-9b7d-8573ffa9e982.png)
