### ISSUE TITLE
The name of the generated event handler is invalid for generics classes.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59935]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-name-of-the-generated-event-handler-/1681517)._

---
I have a class whch is called "MyClass<T>", which has an event "MyEvent"

When I write the following:
MyClass<MyType>. MyEvent +=
and press tab-tab to generate the event handler, it generated the follolwing method:
`MyClass<MyType>_MyEvent` 

Which is invalid and causing a lot of errors in the code.

Visual studio should generate a valid name in this case, too.

---
#### Feedback Bot on 3/3/2022, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
> Which is invalid and causing a lot of errors in the code

This doesn't seem actionable. The name 'MyClass_MyEvent' is legal. We'd need more information here to do anything about this.

**Comment by svick** [comment]
@CyrusNajmabadi It seems the mover ate the angle braces. If I generate event handler using the code in the original report (`MyClass<MyType>.MyEvent +=`), I indeed get invalid code:

![](https://user-images.githubusercontent.com/287848/158165819-6736fb78-afe7-41ad-a67f-1b8281378453.png)

![](https://user-images.githubusercontent.com/287848/158165659-0b2a536d-f31f-49f1-a615-8997a3ef3d55.png)

As such, I'm reopening this.
