### ISSUE TITLE
Make IMoveStaticMembersOptionsService available for VSMac

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#59936]
```
ERROR [2022-03-03 13:50:32Z]: CSharpMoveStaticMembersRefactoringProvider
System.InvalidOperationException: Service of type 'Microsoft.CodeAnalysis.MoveStaticMembers.IMoveStaticMembersOptionsService' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]() in /_/src/Workspaces/Core/Portable/Workspace/Host/HostWorkspaceServices.cs:line 44
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context) in /_/src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:line 51
   at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Document document, TextSpan state, CodeRefactoringProvider provider, CodeChangeProviderMetadata providerMetadata, IExtensionManager extensionManager, Boolean isBlocking, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs:line 183
```

Seeing this in the latest VSMac builds. @davidwengier @jinujoseph 

I don't see anything forbidden in https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/MoveStaticMembers/VisualStudioMoveStaticMembersOptionsService.cs,26, perhaps it could be moved down to EditorFeatures? Or make a copy of it for EditorFeatures.Cocoa so we can have it.

**Comment by filipw** [comment]
we noticed the same in Omnisharp today https://github.com/OmniSharp/omnisharp-roslyn/issues/2353

cc @JoeRobich

**Comment by davidwengier** [comment]
hmmmm.. I fixed this in https://github.com/dotnet/roslyn/pull/59210 so either I did it wrong, or something has regressed.

**Comment by sandyarmstrong** [comment]
Oh I forgot about that @davidwengier. Presumably we'll get that once we bump to 17.2-era Roslyn?

**Comment by davidwengier** [comment]
Ahh yes, that's right, we haven't inserted any 17.2 bits. Should be fixed next week then (assuming the schedule hasn't changed while I've been away 😛)

**Comment by JoeRobich** [comment]
@filipw Opened https://github.com/OmniSharp/omnisharp-roslyn/pull/2354 to move O# to 4.2.0-1.final Roslyn.

**Comment by davidwengier** [comment]
Closing this as fixed by https://github.com/dotnet/roslyn/pull/59210

**Comment by KirillOsenkov** [comment]
Would we want the actual feature Move Static Members to work in VSMac at some point? Should we track using this issue?

**Comment by davidwengier** [comment]
I think @sandyarmstrong said he has an issue, or issues, tracking creating implementations of this, and other interfaces, but if not we certainly could. Not sure whether thats better tracked here or in vsmac, since I don't know where the implementation code would actually live.

**Comment by KirillOsenkov** [comment]
Let’s track it here. Ideally I’d investigate moving the existing implementation down to EditorFeatures since it happens to not require anything from host that is VS-specific. Don’t see a reason for it to be in the VS layer.

Ideally we should strive to move stuff as downer as possible in terms of layers, so more of it is reusable. The VS layer should be as slim as possible.

**Comment by sandyarmstrong** [comment]
This is the top-level experience tracking things like this on the VSMac side: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1469930.

It tracks implementing these missing things:

* Extract Base Class dialog
* Move Static Members dialog
* Move To Namespace dialog
* Pull Members Up dialog
* Identify missing Roslyn options we want to expose

**Comment by CyrusNajmabadi** [comment]
Closing out as vs4mac is not a thin anymore.
