### ISSUE TITLE
SyntaxContexts IsGlobalStatementContext should take file scoped namespaces into consideration

### ISSUE THREAD

**Issue by akhera99** [dotnet/roslyn#59931]
**Expected Behavior**:
```
namespace Namespace;
$$
class Program
{
    public async Task MethodAsync()
    {
    }
}
```

At the cursor location, IsGlobalStatementContext() should be false since it's located within a file-scoped namespace.

**Actual Behavior**:
IsGlobalStatementContext is true.

**Comment by Youssef1313** [comment]
Might be related to the change in `SyntaxTokenExtensions.cs` (in `IsBeginningOfGlobalStatementContext` which is called by `IsGlobalStatementContext`) in https://github.com/dotnet/roslyn/commit/4edc074e4684a06df218c828b431a6f4e096ca9a
