### ISSUE TITLE
Refactoring is incorrect for dynamic types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#59934]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-is-incorrect-for-dynamic-typ/1680288)._

---
[severity:It bothers me. A fix would be nice]
While automating Excel in VS2022 / C# 10.0, I had the following code:

		foreach (var cell in cells2) {
			// Code here not relevant
		}

VS correctly showed the data type of `cell` as dynamic.
I got the refactoring suggestion to replace `var` with the explicit type. But instead of changing it to `foreach (dynamic cell in cells2)`, it changed it to `foreach (object? cell in cells2)`. Which produced a compile-time error in the body of the `foreach` calling a method/property (e.g. `cell.Row`) on `cell` because the compiler tried to resolve the reference at compile time, not at runtime.

The refactoring is incorrect for dynamic types.

---
#### Feedback Bot on 3/1/2022, 07:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
