### ISSUE TITLE
"Implement interface" action can implement the wrong interface

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#59942]
**Version Used**: 17.2.0 Preview 2.0 [32302.304.main]

**Steps to Reproduce**:

```c#
interface I1 { bool P1 { get; } }
interface I2 { bool P2 { get; } }

class C : I1, I2
{

}
```

Ctrl+. on `I2` in the interface list. And invoke "Implement interface".

**Expected Behavior**:

`I2` is implemented, as it is under the caret.

**Actual Behavior**:

`I1` is implemented instead.

![image](https://user-images.githubusercontent.com/350947/156691314-423087c7-432f-4816-b3d7-da37cb338ee1.png)

**Comment by CyrusNajmabadi** [comment]
I do not repro this:

![image](https://user-images.githubusercontent.com/4564579/215867785-e086d52d-cae1-406b-9ae2-f5ec1b2d7ab2.png)
