### ISSUE TITLE
Slice pattern: cannot modify slice

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#59943]
**Version Used**: 6.0.200

**Steps to Reproduce**:

Given this code:

```csharp
using System;

var x = new int[4];
if (x is [..var y])
{
    y[1] = 3;
}

Console.WriteLine(x[1]);
```

`y` should be a slice of `x`, but change to `y` doesn't apply to `x`.

**Expected Behavior**:
Print `3`

**Actual Behavior**:
Print `0`

**Comment by jcouv** [comment]
This is by-design. The behavior of underlying APIs (ie. slicing on arrays) dictate this.
[Consider](https://sharplab.io/#v2:EYLgtghglgdgPgWAFADcICcAEAPTBeTGAUwHdNYAXAbQBYBdAbmTSwC99MABARgDoAlAK4wKUMEV4BhAPZgADlAA2RdAGUVKKAGMiAZwHDR4gBJFFclfoDiRCqsHAAgunQQAngApsAGkwAGXl4APT8ASiYkVipuOg4AZgieXh4ATi9ounDMAHpszAAFdEpdfyA==):
```
var x = new int[4];
var z = System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray(x, 0..^0);
z[1] = 3;
System.Console.WriteLine(x[1]); // Prints 0
```

This is getting a sub-array, which allocates a new array with relevant range of elements, modifies it, and prints from the original array (which is unmodified).

**Comment by hez2010** [comment]
BTW, will slice pattern be made work with `List<>`?

**Comment by jcouv** [comment]
@hez2010 This is not a compiler question, but a runtime/BCL question. It looks like `List<T>` lacks members to make it sliceable. Those can either be added by the BCL or as extension `Slice` method.

**Comment by hez2010** [comment]
Thanks for explanation.
