### ISSUE TITLE
Failed to download Microsoft.CodeAnalysis.Scripting nightly build

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/roslyn#5995]
I was trying to download Microsoft.CodeAnalysis.Scripting version 1.1.0-rc1-20151014-15 from https://www.myget.org/F/roslyn-nightly/ but failed due to error "
Unable to resolve dependency 'System.Reflection.Metadata (≥ 1.1.0-beta-23413)'". Can someone publish the required System.Reflection.Metadata version?

Thanks!

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
It is published to https://www.myget.org/F/dotnet-core/ feed. You should be able to use that.

**Comment by WenningQiu** [comment]
Thanks nguerrera!
