### ISSUE TITLE
Add an attribute specifying the original type, when we create a diff of a ReloadableType

### ISSUE THREAD

**Issue by Clancey** [dotnet/roslyn#59954]
## Background and Motivation

C# Hot Reload added a new `CreateNewOnMetadataUpdateAttribute` attribute, which creates a new type without any limitations. This will be heavily used in Comet. When the new types are sent to the Framework, we need a way to identify the original type it is replacing.

## Proposed API

Let's add an attribute to the new generated types that will specify the original type it is replacing. This will be automatically applied during the diff creation.

`[OriginalType(string fullName)]`

Now at runtime, a library framework can check which type is being replaced, by querying the attribute.

**Comment by lambdageek** [comment]
Should it be there original type, or the previous type?  if I make two successive edits, should it go 
- `[OriginalType("MyClass")] class MyClass#1 {...}` and `[OriginalType("MyClass")] class MyClass#2 {...}` or  
- `[OriginalType("MyClass")] class MyClass#1 {...}` and `[OriginalType("MyClass#1")] class MyClass#2 {...}`

**Comment by Clancey** [comment]
> * `[OriginalType("MyClass")] class MyClass#1 {...}` and `[OriginalType("MyClass")] class MyClass#2 {...}`

It should all reference back to the original type.

**Comment by tmat** [comment]
> Should it be the original type, or the previous type? 

If we call the attribute `OriginalName` it won't matter.

**Comment by tmat** [comment]
Related: https://github.com/dotnet/roslyn/issues/55651

**Comment by lambdageek** [comment]
https://github.com/dotnet/runtime/issues/66222

**Comment by lambdageek** [comment]
@tmat I had a wacky idea while I was working on the API proposal:
> Roslyn could emit the new types as nested types of the original type. Then to find the relationship between the old and new type we would merely get the enclosing type.

This is pretty terrible and we don't want it, right?

**Comment by tmat** [comment]
> Roslyn could emit the new types as nested types of the original type. 

Seems a bit obscure and too complicated.
