### ISSUE TITLE
CSharpGoToImplementation.SimpleGoToImplementation test is not deterministic

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#59950]
Starting with #57861, there are two different possible behaviors for Go To Implementation for this test. The test assumes one of these two behaviors will occur, which leads to spurious failures for the other valid case.

There are two options:

1. Add a test hook to force the command to use a particular path
2. Update the test to detect which of the two outcomes occurred, and treat both as valid

**Comment by jasonmalinowski** [comment]
> Update the test to detect which of the two outcomes occurred, and treat both as valid

This is more work, but seems to me the right thing to do; otherwise we're only testing one branch which means the other branch could be completely non-functional.

**Comment by sharwell** [comment]
I'll see if I can get it included in one of my stabilization PRs. It's easy enough to create the second path by forcing the allowed delay time to 0. 😄

**Comment by jasonmalinowski** [comment]
@sharwell I'm hoping it's not too difficult to be able to detect "the active window is now the go to implementation window" and then branch accordingly. I think that's the common failure I've seen in PRs so hopefully not too bad..,.
