### ISSUE TITLE
Typo on CodeGenDifferences.md file

### ISSUE THREAD

**Issue by sonergonul** [dotnet/roslyn#59967]
I think there is a typo on [CodeGenDifferences.md](https://github.com/dotnet/roslyn/blob/version-1.1.0/docs/compilers/CSharp/CodeGen%20Differences.md) which says;

• The string switch codegen in Ro**ls**yn is completely new...

which should be

• The string switch codegen in Ro**sl**yn is completely new...

Somehow I couldn't clone the repository to my current machine and send a PR for that.

**Comment by jcouv** [comment]
Fixed. Thanks
