### ISSUE TITLE
A lot of invalid suggestions when creating class

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#59965]
**Version Used**:
VS 2022 v17.2 Preview 1

**Steps to Reproduce**:
```
public $$ class Test
{

}
```
$$ - place, where to invoke completions

**Expected Behavior**:
List of possible class modifiers is shown

**Actual Behavior**:
![devenv_VmZ9MLRfTe](https://user-images.githubusercontent.com/70431552/156883012-10af8d74-85aa-4514-9774-3e91625fc9bb.gif)

**Comment by CyrusNajmabadi** [comment]
Those recommendations are appropriate. You may be writing a new symbol on front of an existing one. Or you may be changing an existing symbol to a different one. So keyword completion only considers what's to the left in almost all cases.
