### ISSUE TITLE
GetHashCode function generated from record does not null-check before calling `EqualityComparer<T>.GetHashCode` . 

### ISSUE THREAD

**Issue by Jason5Lee** [dotnet/roslyn#59964]
**Version Used**: 6.0.102

**Steps to Reproduce**:

1. Create a C# project with a record definition `public record Rec<T>(T Value);`.
2. Compile the project with Release.
3. Decompile the compiled binary by ILSpy.

**Expected Behavior**:
In the decompiled code, the related methods for the record such as `GetHashCode` are properly implemented.

**Actual Behavior**:
The `GetHashCode` is implemented as

```csharp
public override int GetHashCode()
{
    return EqualityComparer<Type>.Default.GetHashCode(EqualityContract) * -1521134295 + EqualityComparer<T>.Default.GetHashCode(Value);
}
```

Notice the expression `EqualityComparer<T>.Default.GetHashCode(Value)`. The `EqualityComparer<T>.GetHashCode` method invoke here has an argument with `[DisallowNull]` attribute, but the code does not null-check `Value` before.

If you try to manually implement a record from the decompiled code, there will be a warning.

So, either the `GetHashCode` implementation is wrong, or the `[DisallowNull]` attribute is mis-used.

**Comment by CyrusNajmabadi** [comment]
IEqualityComparer disallows null as you don't know if any particular subclass will handle null or not. However, EqualityCompar.Default is known to be null safe, so the compiler can freely call it.

However, becuse Default just returns an IEqualityComparer, there is no way to annotate it differently, so you effectively have to ignore/suppress the warning (effectively what the compiler does)
