### ISSUE TITLE
VisualBasicAddImportsCodeFixProvider crashes

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#5997]
I frequently get this crash, like, once every four hours of coding
![bug2](https://cloud.githubusercontent.com/assets/3316258/10516589/d44c744e-730d-11e5-8555-22025053bc44.png)

It's happened on a wide variety of projects in a wide variety of circumstances but I've not yet found a reliable way to repro it, and if I get a crash then re-enable it then try to get the crash again, I don't see anything.

I'm filing this bug so you can add more instrumentation around it. Please add a button called "get crash information" or "file bug" or something to the bar. Otherwise, it'll forever be impossible to debug.

**Comment by Pilchie** [comment]
You already fixed one issue here - is it possible to confirm that @ljw1004 is just hitting that?  @ljw1004 - are you running the Update 1 CTP? It should have the fix in it.

**Comment by ljw1004** [comment]
No, not running Update1 CTP.

I tried using a separate instance of VS to attach to the first crashing instance, and I turned on first-chance exceptions, but even when the crash occurred it still failed to trigger the debugger.

I got a consistent repro [video below]. Source code is at \\ddfiles\team\Public\lwischik\repro\repro-imports.zip
![repro-imports](https://cloud.githubusercontent.com/assets/3316258/10521315/077b0090-7324-11e5-9b30-f66a5b5634ec.gif)

Note: even if this particular crash is fixed in Update1, I'd still really like to see an option for more detailed diagnostics. I assume lots of 3rd-party analyzers will also crash.

**Comment by jmarolf** [comment]
This doesn't repro on the latest Update 1 build.  Tracking option for diagnostics with https://github.com/dotnet/roslyn/issues/2697

**Comment by ljw1004** [comment]
@jmarolf, did you get it to repro on VS2015 RTM? I ask because in all of these cases, the repro is never very solid. So a "didn't repro" signal doesn't mean much unless you got a positive repro elsewhere.

(still, closing the bug is fine, and I can always file a new one if I see it again. Thanks for tracking the option.)
