### ISSUE TITLE
CoreCompile target claims the wrong input for signing key

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#59992]
The `CoreCompile` target claims `$(AssemblyOriginatorKeyFile)` as a target input:
https://github.com/dotnet/roslyn/blob/ed571f2de04665ebbc670684708ac7519ab11117/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L33

But the target doesn't actually use that property. Instead, it uses the `$(KeyOriginatorFile)` property:
https://github.com/dotnet/roslyn/blob/ed571f2de04665ebbc670684708ac7519ab11117/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L108

**Comment by AArnott** [comment]
The two properties are related by a target that may copy the value of one into another. So this may be more subtle than meets the eye. But it *looks* wrong to me.

**Comment by jcouv** [comment]
Thanks for reporting this. Fix merged in 17.2
