### ISSUE TITLE
Win32ResourceFile not working

### ISSUE THREAD

**Issue by tangkhaiphuong** [dotnet/roslyn#59990]
**Version Used**: net 5.0

**Steps to Reproduce**:

1. Create .NET Core project with target framework `net5.0`
2. Create win32 resource and compile
```
// Using command to compile: rc Program.rc

#define IDS_AGENT_ID    10000
#define IDS_DASHBOARD_UR  10001

STRINGTABLE
{
    IDS_AGENT_ID,   "00000000-0000-0000-0000-000000000000"
    IDS_DASHBOARD_UR, "wss://localhost:25443/api/v1/agencies/{id}/ws"
}
```
`rc.exe Program.rc`
3. Using `Program.res` to project
```
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Win32ResourceFile>Program.res</Win32ResourceFile>
    <ApplicationIcon>Program.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

```

**Expected Behavior**:
Output assembly Demo.exe must have embeded resource

**Actual Behavior**:
Using Resource Hacker to verify but not found win32 embed resource.

**Comment by jcouv** [comment]
@tangkhaiphuong Many things can happen between the project file and the compiler. I'd recommend you try a build with `/bl` option, then open the resulting binary log with the log reader (https://msbuildlog.com/) and inspect the command-line with `csc.exe`.
Please share that command-line if you still think there's a compiler problem. Thanks

**Comment by tangkhaiphuong** [comment]
Correct property is `Win32Resource`
