### ISSUE TITLE
[Proposal] Add support for traits and/or mixins

### ISSUE THREAD

**Issue by dsaf** [dotnet/roslyn#60]
Description:

http://en.wikipedia.org/wiki/Trait_%28computer_programming%29

Previous discussions:

https://roslyn.codeplex.com/discussions/570952
https://roslyn.codeplex.com/discussions/542646

**Comment by dsaf** [comment]
Additional proposal #129.

**Comment by gafter** [comment]
@dsaf As far as I can tell #129 has nothing to do with this. #129 is about constraints, and this is about behavioral inheritance.

**Comment by dsaf** [comment]
@gafter you are right, I would change #129's title to "Trait-like contracts".

**Comment by AdamSpeight2008** [comment]
@gafter @dsaf  #129 isn't about constraints. It's about creating an abstraction for a common set of proposal and existing features. All of which focus around does this *(whatever this is interface, contract, constraint, generic type, static method)* met some specific criteria.

  It is different to an interface, since it doesn't require it to a baked into the object being validated.
 For example does this object have a specific method? Not necessary indicated via an interface.

Generic Constraints can not be extracted out into a library, or us inheritance. *AFAIK*

Implementation of how the traits are validated are

**Comment by gafter** [comment]
@AdamSpeight2008 Sure, if you like the word *criteria* bettern than *constraints*. In either case it isn't what computer scientists call *traits*, and it would be less confusing if you select a different word.

**Comment by AqlaSolutions** [comment]
It's a great duplication reducer. There are some usecase examples in #4980. I would really like to see this feature in C#.

**Comment by alrz** [comment]
`using` declarations in C++ are pretty neat. What about this syntax
```cs
class Foo {
    friend class Wrapper;

    friend void F() { } 
    public void G() { } 
    public void G(int a) { } 
}
class Wrapper {
    readonly Foo foo = ...;

    // includes public methods as public methods
    public using public foo ;         

    // includes public methods as protected methods
    protected using public foo ;   

    // includes friend methods as private methods
    private using friend foo ;     

    // includes all G overloads as internal methods (also a dot would be sufficient)
    internal using foo::G; 

    // includes a specific G overload as a public method
    public using foo::G(int);

    // or
    public using foo::G();
}
```
Note that `friend` is a new modifier which is used for composition over inheritance scenarios.

**Comment by alrz** [comment]
@dsaf This is about traits *or* mixins? Perhaps you should change the title to be more specific. I'm thinking that this thread is considered for proper mixins.

**Comment by dsaf** [comment]
@alrz I don't have enough experience with both to make a judgement. Are concepts *really* that clearly defined? E.g. how different is a stateful trait from a mixin?

**Comment by alrz** [comment]
@dsaf Mixins are about behavioural inheritance, while traits are similar to interfaces, for example in Scala interfaces are presented as traits, *that* close. But I don't think that it has anything to do with mixins.

**Comment by dsaf** [comment]
@alrz What about this:

http://docs.scala-lang.org/tutorials/tour/mixin-class-composition.html
> To define a class that can be used as a **mixin** we use the keyword **trait**

http://docs.scala-lang.org/tutorials/tour/traits
> **Traits** are typically integrated into a class (or other traits) with a **mixin** class composition

**Comment by alrz** [comment]
@dsaf Well, in these definitions, a trait is considered as a target for a mixin composition. Still it doesn't change the meaning of a trait. And since in C# there is no trait, I expect that classes can be composed to other classes as interface implementations through mixins. Still, everything has its own definition.

**Comment by GeirGrusom** [comment]
Mixins can have state whereas traits can't. Java 8's default methods is a trait implementation.

**Comment by dsaf** [comment]
@GeirGrusom what about so called "stateful traits" that actually can have state?

**Comment by GeirGrusom** [comment]
Why would something that describes a trait of some object require state? If it can't rely on the objects state it's not really a trait of that type; it's a mixin.

**Comment by dsaf** [comment]
That's a question for computer scientists / language designers I am afraid:

http://stephane.ducasse.free.fr/Presentations/2009-TraitsAtSC.pdf

**Comment by alrz** [comment]
Since I've got the habit of implementing anything with generators, so,
```cs
partial class Class {
  [Mixin] ISomething something = new Something();
}

// to be generated
partial class Class : ISomething {
  public void DoSomething() => something.DoSomething();
}
```
Not sure what exact capabilities are discussed in the original post, i.e none.

**Comment by axel-habermaier** [comment]
@alrz: Nice one! Seems like generators could be the most important feature of C# 7, even more so than pattern matching. Particularly since records and discriminated unions won't make it.

**Comment by dsaf** [comment]
The proposal is not specific because I am not qualified to describe it properly. It's mostly to register an interest towards this language feature.
I am not surprised that code generation can be used to "implement" custom language features, especially when language/compiler gives additional support for it. E.g. 
https://bitbucket.org/skwasiborski/mixins/wiki/Home   ,   http://joseoncode.com/2011/02/01/static-mixins-in-net

Still not a fan of partial types.

**Comment by alrz** [comment]
>Still not a fan of partial types.

@dsaf If you are referring to the source type being `partial` check out #6953, otherwise, I don't see what is wrong with partial types, considering that they are actually the very feature that make generators useful in the first place.

**Comment by UnoSD** [comment]
Subscribing to the discussion. @UnoSD

**Comment by MartinJohns** [comment]
Hey @UnoSD ,

Just a friendly pointer that there is a subscribe button to subscribe to discussions. No need to add pointless comments. :-)

It's on the right side:
![image](https://cloud.githubusercontent.com/assets/5269069/20433762/61b53f46-ada5-11e6-89a3-83459d571fc2.png)

**Comment by UnoSD** [comment]
@MartinJohns, unfortunately if you subscribe just with the button, then you won't be able to search for the issues to which you are subscribed. In this way, you can also search for mentions, that's just a small workaround until finally the GitHub team implements a solution: https://github.com/isaacs/github/issues/283

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

Traits are now proposed at https://github.com/dotnet/csharplang/issues/52 and are under active design/development.
