### ISSUE TITLE
dotnet build support for projects with Source Generators where .Net Standard 1.0 library used in generation-time

### ISSUE THREAD

**Issue by HavenDV** [dotnet/roslyn#60004]
### Description

This is a very specific problem. MSBuild 17.0 and dotnet build 6.0.200 is not able to build a library with a source generator that has a generation time dependency as a .Net Standard 1.0 library (and therefore contains .Net Standard 1.0 dependencies in the analyzers/dotnet/cs folder). MSBuild 17.2 preview successfully builds it. I don't know in which version exactly MSBuild solved it.

Ubuntu 20.04.3:
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3002068/154892421-346d63ab-0467-4c65-a8d9-24f2391d5c06.png">

Windows 11:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/3002068/154892647-f2f2ce0c-7378-474d-8bf0-b3c122f6436a.png">

### Repro
[source-generator-issue-repro.zip](https://github.com/dotnet/core/files/8106543/source-generator-issue-repro.zip)
Run `dotnet-build`:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/3002068/154896446-40bea1c9-78e9-42b1-a278-35755a713011.png">

MSBuild 17.2 will works:
`msbuild -restore /p:Configuration=Debug /p:Platform="Any CPU"`
<img width="611" alt="image" src="https://user-images.githubusercontent.com/3002068/154896471-d882ed9d-7fb5-4ffa-83f9-23acdfb8636a.png">

### Configuration

dotnet build gives error on both Windows and Ubuntu 20.04.3
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3002068/154892261-d034547a-38f5-4e5e-b1b2-21ee6ebaf3d2.png">

### Regression?
No

### Other information

Generator that throws this error when building another project:
https://github.com/HavenDV/H.NSwag.Generator  
There are very specific dependencies that eventually lead to using .Net Standard 1.0 at Generation Time.  
  
Text error:
```
CSC : error NSG0001: System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)) 
```
Workaround: Use MSBuild 17.2

**Comment by sharwell** [comment]
> and therefore contains .Net Standard 1.0 dependencies in the analyzers/dotnet/cs folder

The .NET Standard 1.0 dependencies are provided by the runtime. They cannot be included in the analyzer package (doing so will break the build).

**Comment by HavenDV** [comment]
Of course, I have tried not to include the .net standard 1.0 libraries. But then the generator just doesn't work, throwing an error for the main dependency that it can't find the dll or one of its dependencies

**Comment by HavenDV** [comment]
I don't experience this problem since version 6.0.302.
