### ISSUE TITLE
Within the Roslyn build, treat AD0001 as a warning/error

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#6001]
@jaredpar came across an issue where the public API analyzer was throwing an exception in its compilation start action (see https://github.com/dotnet/roslyn-analyzers/issues/312). This effectively disabled the analyzer for the rest of the project build.

The exception was surfaced as an AD0001 diagnostic, but unfortunately these are surfaced as *info* diagnostics rather than warnings or errors. This means the only way you'll see them at the command line is if you bump up the MSBuild verbosity and then go looking through the build log. Otherwise, you have no idea it happened.

We should update the shared .ruleset file to turn AD0001 into a warning, which will then be prompted to an error during CI builds.

**Comment by srivatsn** [comment]
This has been fixed.
