### ISSUE TITLE
Avoid reparsing on solution open

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/roslyn#60014]
From @jasonmalinowski 

This is following up to the idea we had to have the project system pass in an approximation of the options that impact parsing once we’ve completed evaluation; this will mean we don’t end up reparsing everything again when things change.

There are only a handful of properties that impact parsing. You can see them on the ParseOptions type at https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.parseoptions, and the derived types which also have the language version. So the ones that would probably matter for getting this right (or close enough) would be to pass in:

•	/define (here’s how it’s processed: https://github.com/dotnet/roslyn/blob/7714ab4a89129ccc1885f961c0d3a12adce2add5/src/Compilers/Core/MSBuildTask/Csc.cs#L398) 
•	/doc (just passed in directly from DocumentationFile)
•	/features (here’s how it’s processed: https://github.com/dotnet/roslyn/blob/7714ab4a89129ccc1885f961c0d3a12adce2add5/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L834-L848)
•	/langver (it’s just passed in directly from LangVersion)

The handling for /define is mostly handling some strange or error cases – simply just treating it as a string.Split/Join is probably a good enough of an approximation for 99% of projects. The handling for /doc is a bit interesting: we translate the path existing or not into the parsing mode on the ParseOptions type, which is why you don’t see the string there but it’s something we’d need to deal with.

I think it should also be possible to avoid reparsing trees that don’t have any #defines if only the /define switch changes; that would help speed up Debug/Release transitions if the project system wasn’t destroying and re-creating contexts.

**Comment by jasonmalinowski** [comment]
So I gave this a shot at implementing and the project system changes are trivial, but the MSBuild target changes are a bit trickier than I expected. The problem being that for any modern SDK project, the preprocessor symbols are being generated as a part of targets, not during the evaluation pass anymore. It looks like /langver is being set still during evaluation so we can get that, and combined with https://github.com/dotnet/roslyn/pull/59406 that might mean we still get a bit of a win here.

@sfoslund @rainersigwald I see when https://github.com/dotnet/sdk/pull/11635 was implemented, the computation of the implicit directives was put in the execution pass -- I'm guessing that was needed because some construct there isn't good for evaluation only? The context here: we're playing with an experiment to get the language service more accurate options up front, as otherwise we spend a lot of time parsing C# files only to potentially throw out the parses once we get the full design time build results back.

@drewnoakes How does CPS then run design time builds during the execution pass? If we wanted to try running just the generation of those directives earlier, I'm guessing that would be expensive?

**Comment by drewnoakes** [comment]
@jasonmalinowski today we try and run a single design-time build to gather data from all targets. I don't think that running multiple passes would be a net win for the product.

In the case that the project system does have cached data on project load, we should be able to provide the correct arguments from caches during workspace construction, so long as the caches are up to date.

**Comment by CyrusNajmabadi** [comment]
@drewnoakes in this case though, this causes Roslyn to have go through and reparse everything :-/. It's definitely not ideal. 

That said, @jasonmalinowski I have some ideas here. 

Specifically around storing if there is #if in the file.

**Comment by davkean** [comment]
We should attempt to move everything we need back to evaluation needed for parsing so we don't need a design-time build to gather it. Targets also break the property editing experience.

**Comment by rainersigwald** [comment]
> @rainersigwald I see when [dotnet/sdk#11635](https://github.com/dotnet/sdk/pull/11635) was implemented, the computation of the implicit directives was put in the execution pass -- I'm guessing that was needed because some construct there isn't good for evaluation only? The context here: we're playing with an experiment to get the language service more accurate options up front, as otherwise we spend a lot of time parsing C# files only to potentially throw out the parses once we get the full design time build results back.

I don't remember details any more, but I think the main thing is the looping-over-items implementation. I mentioned (https://github.com/dotnet/sdk/pull/11635/files#r428619651) a possibility to shift the computation to SDK-construction time, and that still seems feasible. @marcpopMSFT may have further thoughts.

**Comment by rainersigwald** [comment]
(though note that we'll have to be resilient to execution-time changes even if we get them off the mainline path)

**Comment by marcpopMSFT** [comment]
> I don't remember details any more, but I think the main thing is the looping-over-items implementation. I mentioned (https://github.com/dotnet/sdk/pull/11635/files#r428619651) a possibility to shift the computation to SDK-construction time, and that still seems feasible. @marcpopMSFT may have further thoughts.

I don't recall either but I assume it was to ensure it automatically updated each new release so we wouldn't have to update it every year (and likely forget). Seems worth it though for the perf improvement goals.

**Comment by jasonmalinowski** [comment]
> @jasonmalinowski today we try and run a single design-time build to gather data from all targets. I don't think that running multiple passes would be a net win for the product.

@drewnoakes: I guess the targets being ran I would already be running during the full design time build pass. I would have assumed the cost for all the MSBuild execution for a project would just be the cost of the underlying targets, but is that assumption wrong? Does multiple builds of different targets take longer than running those as one batch?

> In the case that the project system does have cached data on project load, we should be able to provide the correct arguments from caches during workspace construction, so long as the caches are up to date.

@drewnoakes: I know you had mentioned batching in an internal email conversation at one point; if the caches are present today how soon do we get a command line?

**Comment by jasonmalinowski** [comment]
> I don't remember details any more, but I think the main thing is the looping-over-items implementation.

@rainersigwald/@marcpopMSFT: is the general problem an ItemGroup can't use other item groups during evaluation? And is there a general mechanism already in place for trying to generate that in some other way during SDK construction or would that have to be invented? Happy to give it a shot if it's not _too_ much pain.

**Comment by davkean** [comment]
It was going to be added for NuGet central package version support for legacy project system but I don't know what happened to that. 

> @drewnoakes: I guess the targets being ran I would already be running during the full design time build pass. I would have assumed the cost for all the MSBuild execution for a project would just be the cost of the underlying targets, but is that assumption wrong? 

Yes that assumption is wrong, this is why we don't use MSBuild for fast up-to-date.

**Comment by drewnoakes** [comment]
> I know you had mentioned batching in an internal email conversation at one point; if the caches are present today how soon do we get a command line?

I haven't gathered numbers. Perhaps @arkalyanms knows. I would expect the delay involved in waiting for the DTB cache to load to be low enough that a user shouldn't notice the difference. Whether that's a good trade-off comes down to whether we avoid enough redundant work to speed up other areas. But we can't make a call here until we have some real-world numbers.

**Comment by jasonmalinowski** [comment]
We've completed this work.
