### ISSUE TITLE
Make FixAll APIs for ContainingType/Member scope public

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#60029]
@jmarolf Yes, these APIs are intentionally public. Otherwise, public clients such as MS.CA.Testing library, would be unable to create a FixAll provider that supports these new FixAll scopes. We can certainly keep them internal in this PR and have a separate PR to just make these APIs public.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/pull/59989#discussion_r821311317_

**Comment by mavasani** [comment]
@jmarolf I'll use this issue to track making APIs public. I'll switch the APIs to internal in the current PR

**Comment by mavasani** [comment]
We would need to revert https://github.com/dotnet/roslyn/pull/59989/commits/2df4e07f971dc80771b249de77e04c453eea0d9f to make APIs public

**Comment by mavasani** [comment]
Proposed public APIs:

1. Add a new ctor to DocumentBasedFixAllProvider: Currently it has a parameterless [ctor](https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs,33). We want to add a new ctor overload that takes an array of supported FixAllScopes for the provider.

```csharp
// Current ctor
protected DocumentBasedFixAllProvider()

// New ctor
protected DocumentBasedFixAllProvider(ImmutableArray<FixAllScope> supportedFixAllScopes)
```

2. Add a new overload for [FixAllProvider.Create]() static method that takes an additional `supportedFixAllScopes` parameter:

```csharp
// Current public API:
public static FixAllProvider Create(Func<FixAllContext, Document, ImmutableArray<Diagnostic>, Task<Document?>> fixAllAsync)

// New overload
public static FixAllProvider Create(
            Func<FixAllContext, Document, ImmutableArray<Diagnostic>, Task<Document?>> fixAllAsync,
            ImmutableArray<FixAllScope> supportedFixAllScopes)
```

**Comment by 333fred** [comment]
## API Review

* Some test cases to add:
    * Top level statements
    * Mutli-cursor in VS
        * Will we need to make `triggerSpan` an ImmutableArray to deal with this?
* We should consider renaming `triggerSpan` to `diagnosticSpan`, to make it clear this is the span of the _diagnostic_ that triggered the code, not the user's selection span.
* What is the use case for `GetDocumentSpanDiagnosticsAsync` to be public? Is it for the testing framework? Otherwise, we're not sure if we should add this helper now, or wait for use cases.

**Comment by mavasani** [comment]
> Mutli-cursor in VS
>> Will we need to make triggerSpan an ImmutableArray to deal with this?

Instead of making this an array and adding complexity of dealing with multiple declarations in the engine, I would prefer that the code fix engine/host invokes the `FixAllProvider.GetFixAsync(FixAllContext)` once per each caret position and using a single trigger span for the `FixAllContext`.

> We should consider renaming triggerSpan to diagnosticSpan, to make it clear this is the span of the diagnostic that triggered the code, not the user's selection span.

Sure, I'll make the change.

> What is the use case for GetDocumentSpanDiagnosticsAsync to be public? Is it for the testing framework? Otherwise, we're not sure if we should add this helper now, or wait for use cases.

This helper can be used by custom FixAllProviders to request diagnostics within a document span. We can keep this internal for now and have the custom FixAllProviders that support the new spans to invoke the `GetDocumentDiagnosticsAsync` for entire document and then filter to the span, though it will be more expensive.

**Comment by sharwell** [comment]
@333fred is this supposed to still be open?

**Comment by 333fred** [comment]
I'm not sure. @mavasani, is there anything left to do here?

**Comment by mavasani** [comment]
Nope, nothing from my side. Closing
