### ISSUE TITLE
Have layer mode in the editor to support multiple features

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#60020]
Come from the design meeting on 3/7/2022.
This idea has been purposed multiple times, and we need to have a design & experiment around it.

Possible related issues:
https://github.com/dotnet/roslyn/issues/59352
https://github.com/dotnet/roslyn/issues/39850
https://github.com/dotnet/roslyn/issues/59379

We want to have different layers in the editor, each layer would have a different emphasis on various topics.
For example, 
https://github.com/dotnet/roslyn/issues/39850, it would be put under a 'performance layer' focusing on the performance-related hints

**Comment by CyrusNajmabadi** [comment]
Closing out as far too broad.  If we are doing this we need commitment from teams involved (editor/lsp/etc.) and someone driving this.
