### ISSUE TITLE
Relax file collapsing on navigation for Source Link

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#60049]
We currently have a single option called "Enter outlining mode when files open" which makes metadata-as-source files appear completely collapsed on first navigation. Feedback from the debugger team (and me 😛) is that this is not ideal when the metadata source comes from embedded/Source Link, partly because the source is more relevant than decompilation/metadata, and partly because it hurt discoverability of these new features.

Proposed solutions:
1. Disable this behaviour for "real" source, rather than grouping all types of "metadata as source" together
2. Don't collapse the target of the navigation (ie, the method being navigated to) so that it is fully visible, but leave the user to expand anything else they want to see
3. 1 or 2, but controlled by an option

**Comment by JoeRobich** [comment]
### Design Notes

**Discussion**
- The current behavior of showing code collapsed was on purpose. There is a lot of noise when things were expanded. We even added custom formatting to adjust blank lines.
- Seems like this request is intended as a feature advertisement.
- Expect stepping into a method would expand the method body. Works today.
- We don't have a good document outline view and we may not want to change the collapse behavior on GoTo until we do.
Peek definition currently only shows metadata-as-source not decompilation, although that can be investigated.

**Proposal**
<img width="434" alt="image" src="https://user-images.githubusercontent.com/611219/159367117-757f1870-278c-4ccc-9716-2cd45c0cf7c8.png">
"Enter outlining mode when files open" option controls whether new files are collapsed when opened. When turned off, files aren't collapsed and it doesn't allow users to collapse them. 
Adjust this option to not collapse by default but still allow users the ability to collapse. Possibly add additional options for "Collapse definitions from metadata" on by default.

**Comment by davidwengier** [comment]
I reviewed the meeting recording, and this is my plan of record:

* Remove "Enter outlining mode when opening files"
  * Turning this option off not only doesn't collapse files, but it removes the ability to collapse files, which is bad
* Add two new options from https://github.com/dotnet/roslyn/issues/44843#issuecomment-1020633184 for "Collapse regions" and "Collapse usings"
* Add a third new option for "Collapse implementations from metadata on file open (on by default)
* Review after all of the above and check:
  * Does the "Collapse regions when collapsing to definitions" serve any purpose any more
  * Is there any functionality loss from the removal of the "Enter outlining mode" checkbox
