### ISSUE TITLE
ControlFlowGraph for VB.NET declaration should generate implicit assignment

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [dotnet/roslyn#60056]
**Version Used**: 17.0.4 / 4.0.1 and all previous versions

**Steps to Reproduce**:

Create `ControlFlowGraph` for this statement VB.NET statement and inspect operations:
```
Dim B As Boolean
```

The code is equivalent to C#  version
```
var b = false;
```
and has the same behavior as the explicit variant
```
Dim B As Boolean = False
```
because variable `B` has a default value of `False` that can be directly used.

**Expected Behavior**:

CFG should contain the same operations as equivalent C# code. Except for the fact that they will be all marked as implicit.

* `SimpleAssignmentOperation` (implicit)
  * `LocalReferenceOperation` (implicit)
  * `LiteralOperation` (implicit)

**Actual Behavior**:

CFG contains three empty blocks with no operations.

**Remark**

Same behavior should apply to other types as well - all of these should be assigned to their default values.
```
Dim A, B, C As New StringBuilder, D, E, F As Integer
```

**Comment by jcouv** [comment]
FYI @AlekseyTs @333fred, this indeed seems a bug, but I'm pushing out to Backlog milestone. Feel free to correct assessment or priority.

**Comment by jcouv** [comment]
Thanks for the explanation

**Comment by pavel-mikula-sonarsource** [comment]
Thanks for looking into this. 

I'll just document our alternative solution here in case somebody else bumps into this:

**Alternative way to solve it on CFG user side:**

Branch has `EnteringRegions`. Local variables are listed in `LocalLifeTimeRegion` in `Locals` property.

So when traversing branch, initialize all `branch.EnteringRegions.SelectMany(x => x.Locals)` to their default values if needed.
