### ISSUE TITLE
"Create and assing field" generates code without spaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60064]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-and-assign-field-generates-code/1684147)._

---
After a fresh install of Visual Studio 2022 v17.1.0 on a new laptop, I noticed that the code generated for "Create and assign.." is without spaces. It should be "_context = context;" instead of "_context=context". My colleagues don't have this issue but they're using the same version of Visual Studio.

![image.png](https://aka.ms/dc/image?name=Bf52f1b67be334872822c7623bd1d0ecd637820042375803243_20220304-162357-image.png&tid=f52f1b67be334872822c7623bd1d0ecd637820042375803243)

UPDATE:

This "issue" is fixed by setting this option:

![image.png](https://aka.ms/dc/image?name=B082fb787af1540cba73a3530691ec6f6637820053818158180_20220304-164302-image.png&tid=082fb787af1540cba73a3530691ec6f6637820053818158180)

Which is crazy because this option is only for binary operators. So I still think this is a bug.

---
#### Fiona Niu[MSFT] on 3/6/2022, 11:39 PM: 

<p>Thank you for your feedback! Does this reproduce for all project or specific project? If it’s reproduce with the specific project, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you could provide us a recording of the behavior.</p>
<pre><code>Windows 10
• Win-G to activate game mode bar (https://support.microsoft.com/en-us/help/4028293/windows-using-game-mode-on-your-pc )
• Record the video and attach to this feedback ticket.
</code></pre>
<p>We look forward to hearing from you!</p>

#### Marcel Wijnands on 3/6/2022, 11:55 PM: 

<p>I had this issue in every project. I had it in my own projects and to make this screenshot I created a new .NET 6 Console Application. Had the same issue. Also I don’t have any 3rd party extensions installed or anything. It was a fresh install and immediately saw this happening, as I use this feature a lot.</p>

#### Feedback Bot on 3/8/2022, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This feature should use `ElasticSpace` instead of `ElasticMarker` to ensure that spaces are used in all cases except where the code style is set to remove them.

**Comment by Youssef1313** [comment]
@sharwell I thought the mentioned code-style option considers `=` as a binary operator so that this is expected?

**Comment by mwijnands** [comment]
Hi, I submitted this bug. Maybe the problem is with Visual Studio. This is the default style option when installing a fresh copy of VS 2022 on a fresh windows system.

So either the "bug" is that VS has this as a default style option (weird because who wants this..? also it was never the case) _or_ this option should just be for binary operators where `=` should not be considered one. I don't know.

**Comment by CyrusNajmabadi** [comment]
This doesn't feel like a bug to me.  assignment has been treated as a binary expression for a long time.  in the codebase which predated roslyn, they were the same node, so were treated uniformly.  Roslyn has different SyntaxModel types, but that we kept ths behavior for consistency with the origianl implementation.
