### ISSUE TITLE
Comment Selection command doesn't work in .editorconfig file

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60073]
**Version Used**: 87422e8edfe8981c61849bf89697421fc61c673f

**Steps to Reproduce**:

1. Open an editorconfig file in VS
2. Selet a line and hit ctrl+k, ctrl+c to Comment Selection

**Expected Behavior**: The line is commented out with a leading `#`

**Actual Behavior**: Bottom bar says "The key combination (Ctrl+K, Ctrl+C) is bound to command (Comment Selection) which is not currently available.

**Comment by sharwell** [comment]
📝 The editor experience for **.editorconfig** files is controlled by the editor (I believe through TextMate), so there's nothing we can do for it here.

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by olegtk** [comment]
Yeah, VS by default has very rudimentary support for .editorconfig editing. I suggest trying extension like https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is external to roslyn.
