### ISSUE TITLE
EditorFeatures.Cocoa should target `net6.0-macos`

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/roslyn#60078]
VSMac 17 has migrated from Mono (typically targeting `net472`) to .NET (typically targeting `net6.0-macos`). The VS Editor has followed, and now packages that `EditorFeatures.Cocoa` depends on (like `Microsoft.VisualStudio.Text.UI.Cocoa`) target `net6.0-macos`.

However, it is only possible to target `net6.0-macos` if the `macos` workload is installed in the .NET SDK. This workload can be installed on Windows and generally works fine there. https://github.com/dotnet/roslyn/pull/59429 initially added workload support to the Roslyn build, but ran into problems. Periodically, workload signature validation fails (notably, signature validation only happens on Windows), due to the SDK mixing up workload packages in various feeds referenced in Roslyn's NuGet.config.

For now, https://github.com/dotnet/roslyn/pull/59429 has taken the approach of manually referencing the libraries it needs using `PackageDownload`, manual references, and disabling various warnings. But we should follow up with the SDK team and as soon as workload resolution stabilizes, we bring back the macos workload and the `net6.0-macos` target.

**Comment by jasonmalinowski** [comment]
@sandyarmstrong For this:

> But we should follow up with the SDK team and as soon as workload resolution stabilizes, we bring back the macos workload and the net6.0-macos target.

Any sense if this "stabilization" is already underway or will soon be addressed? We've been discussing how to improve some unit testing in our side and having this target net6.0-macos would make that a lot easier.

**Comment by sandyarmstrong** [comment]
> Any sense if this "stabilization" is already underway or will soon be addressed?

I'm doing a little more investigation before I write up a bug and follow up with the SDK team.

> We've been discussing how to improve some unit testing in our side and having this target net6.0-macos would make that a lot easier.

I don't think the target for the project should make any difference in testing. Any testing using this assembly, regardless of target, will require a macOS pipeline.

And incidentally, if we were building this project on macOS instead of Windows, there would be fewer issues with workload provisioning, and any such problems would be isolated to the Mac and not impact people building on Windows. But I believe there is a lot of appeal to having this project build as part of normal local Windows builds (regardless of target framework).

**Comment by jasonmalinowski** [comment]
> I don't think the target for the project should make any difference in testing

So one thing I was looking at was making many of our unit tests run on a mac. We'd need a mac leg regardless (and we already have those), but one issue was our common test helpers would have needed a certain amount of "if mac, if windows" when creating icky things like MEF compositions to pull in different binaries. And those would have had different dependencies. But being able to just multi-target them would be much, much simpler.

**Comment by sandyarmstrong** [comment]
Finally filed the SDK issue: https://github.com/dotnet/sdk/issues/24815

**Comment by sandyarmstrong** [comment]
I think the signature validation issue has abated, but adding use of `net6.0-macos` in the Roslyn build could still negatively impact Roslyn developers on Windows due to https://github.com/dotnet/sdk/issues/30230 (see also https://github.com/AArnott/Xunit.StaFact/pull/68#issuecomment-1419425148).

It's not hard to add support for installing the macos workload using Roslyn's existing build scripts. But what Andrew was experiencing with StaFact was that if VS was not launched from the command prompt, the IDE would try to restore workloads, and fail due to the above bug. This adds another barrier to contribution.

I'll follow up again with the SDK team.

**Comment by CyrusNajmabadi** [comment]
Closing as vs4mac is gone.
