### ISSUE TITLE
[Flaky test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpOutlining.OutliningConfigChange

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#60072]
Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=1650156&view=results
Example message:
> System.AggregateException : One or more errors occurred. ---- System.ArgumentNullException : Value cannot be null. Parameter name: projectNames

Runfo Tracking Issue: [[Roslyn][Flaky test]CSharp.CSharpOutlining.OutliningConfigChange](https://runfo.azurewebsites.net/tracking/issue/304)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1654115](https://dev.azure.com/dnceng/public/_build/results?buildId=1654115)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[1652586](https://dev.azure.com/dnceng/public/_build/results?buildId=1652586)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60037](https://github.com/dotnet/roslyn/pull/60037)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1651690](https://dev.azure.com/dnceng/public/_build/results?buildId=1651690)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[1651690](https://dev.azure.com/dnceng/public/_build/results?buildId=1651690)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1650156](https://dev.azure.com/dnceng/public/_build/results?buildId=1650156)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|4|4|

**Comment by sharwell** [comment]
The cause of failure here is completely unrelated to the test (the failure occurred during initialization, before the test in question started).

**Comment by allisonchou** [comment]
I see, thanks Sam! Closing this issue then
