### ISSUE TITLE
Compiling Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj results in  CS8103

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/roslyn#60085]
I'm having _CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals._ while compiling  Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj. Did someone get into the same issue and know how to work around it?

**Version Used**: 

A shallow fork of `release/dev17.1`.

**Steps to Reproduce**:

Build the Roslyn source code.

**Expected Behavior**:

Success

**Actual Behavior**:

CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

**Comment by gfraiteur** [comment]
I worked around the issue by commenting out one class. I assume that the project is close to its limit.

**Comment by jcouv** [comment]
Yes, this has been fixed in more recent branches. Some tests were moved out of the Emit project and new tests are added to Emit2 project.
I'll close as this was already resolved moving forward.
