### ISSUE TITLE
Debuggee app crashes on applying code changes

### ISSUE THREAD

**Issue by calgagi** [dotnet/roslyn#60099]
**Version Used**: current VS main (32308.76.main), CLR: 6.00.222.6406

**Steps to Reproduce**:

1.  Create a new .NET 6 c# console app project
2. Copy paste the code:
```csharp
using System;

namespace ConsoleApp10
{
    internal class Program
    {
        static (string token, string value) advanceToNextQuoteAndSkip(string value)
        {
            Console.WriteLine("HI");
            return ("HI", "x");
        }

        static void Main(string[] args)
        {
            advanceToNextQuoteAndSkip("HIII");
        }
    }
}
```
3. Set a breakpoint on the `return ("HI", "x");` line in `advanceToNextQuoteAndSkip`
4. F5 and hit breakpoint
5. Comment out the `Console.WriteLine("HI");` line
6. Apply code changes (EnC)

**Expected Behavior**:
Code changes applied successfully.

**Actual Behavior**:
Debuggee app crashes.

**Investigation**:
1. Crash happens when the debugger is trying to remap the leaf frame to find the new instruction pointer for execution
2. If you change `advanceToNextQuoteAndSkip` to return an `int` and repeat step 3 and onwards, then the crash doesn't occur.

**Comment by calgagi** [comment]
cc @isadorasophia

**Comment by tmat** [comment]
I believe there is a similar bug on CLR - it doesn't handle struct return types correctly: https://github.com/dotnet/runtime/issues/46274

**Comment by calgagi** [comment]
Closing since it seems like this is a dupe of the CLR issue linked above
