### ISSUE TITLE
[ask mode] Update Roslyn to use Microsoft.DiaSymReader.Native 1.3.0

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6010]
Currently we use 1.2.0-rc, which doesn't support deterministic PDB ID. The new version should be available by the EOW -- we are waiting for the C++ team to deliver it.

**Comment by tmat** [comment]
@MattGertz

**Comment by jaredpar** [comment]
CC @tannergooding

**Comment by tmat** [comment]
Updated the versions in the title and description to correct ones.
