### ISSUE TITLE
C# Preview error MSB6006: "csc.exe" exited with code -2146232797.

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/roslyn#60103]
**Version Used**: 

Visual Studio: Version 17.1.1
`<LangVersion>preview</LangVersion>`

**Steps to Reproduce**:

When compiling a project after adding `!!`, I started seeing this error message:

`error MSB6006: "csc.exe" exited with code -2146232797.`

Here is the repository where it occurred: https://github.com/TortugaResearch/Anchor/tree/Null-Check-Experiments

I haven't been able to narrow it down to which line is triggering the bug.

**Comment by RikkiGibson** [comment]
Most likely a dupe of #58796. If you are able to grab a stack trace from e.g. the event viewer, or by getting a binary log of your build and looking at the error, that would be really handy.

We have seen this reported in a few places. Should we service this in 17.1 @jaredpar?

**Comment by Grauenwolf** [comment]
Confirmed. 

When I removed `!!` from the async methods, the project successfully compiled.
