### ISSUE TITLE
New rename dialog doesn't always allow Left / Right arrow navigation immediately after starting rename interaction

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#60117]
**Version Used**: VSMain

**Steps to Reproduce**:

1. Start a rename session
2. Hit left / right arrow

![devenv_MOmMWT98fn](https://user-images.githubusercontent.com/2008729/157936881-5433d7d8-b106-471c-a638-23a987b7f673.gif)

**Expected Behavior**:
Can move my cursor among the rename dialog UI

**Actual Behavior**:
NO cursor navigation

**Notes**:

Seems like every other session works?

**Comment by ryzngard** [comment]
This should be resolved with https://github.com/dotnet/roslyn/pull/60846
