### ISSUE TITLE
RecoverableTextAndVersion using lock improperly.

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn#6012]
The GetValueAsync API should be using the semaphore slim asynchronously.  Instead, it is using it synchronously, across an await call.  Maybe we need an analyzer here.

This is related to connect issue/devdiv work item 132147.

**Comment by tmeschter** [comment]
@mattwar An analyzer for this seems simple enough. Could you file an issue at [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers)?
