### ISSUE TITLE
Should we block references to `Program` in top level code projects

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#60133]
Today top level code generates a real `Program` class/symbol to hold the top level statements in.  This class is legal to eb referenced and used (unlike top-level-statement locals which are in scope, but not usable).  However, while it's usable there do not appear to be actual valuable reasons to use it.  Instantiating it gives you a type without usefulness, and it doesn't expose anything static on it that it actually relevant to that type.

Should we consider just hiding this type from intellisense contexts?

Note: it's possible there are some scenarios where it might be reasonable to expose it.  For example, you could imagine attributes that might want to reference this like so `[Weave(typeof(Program))]` or APIs that use it generically like `Benchmark.StartupObject<Program>()`.  Perhaps we should allow it in contexts that want to actually refer to a type-reference, and not which are in an expression-scenario where the type would only be a stepping-stone to something else.

**Comment by Youssef1313** [comment]
```csharp
System.Console.WriteLine();

partial class Program
{
}
```

Note that for the above case it shouldn't be hidden.

A use case in expression contexts is https://github.com/dotnet/roslyn/issues/60136 :)

**Comment by CyrusNajmabadi** [comment]
That's def a good point.  I generally mean 'a synthesized Program class without any type declarations associated with it'.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
