### ISSUE TITLE
Improve "Convert regular string to interpolated string" refactoring

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60148]
Noticed while working on https://github.com/dotnet/roslyn/pull/60146

Currenly refactoring suggestion applies if string has at least one curly brace, so strings like `value {`, `other } value`, `nothing to see here }{` etc are valid for this refactoring.

I propose to offer refactoring only when string is "valid" for interpolation, like `value {}`, `other {} value {}` or `nothing to {see} here`.

This is very easy and fast to do, so I'll implement it on my own if this proposal is approved.

**Comment by CyrusNajmabadi** [comment]
This seems like it will only disable scenarios that are working today right?  Without actually reported problems I would not want to change things here. If it ain't broke.

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/48219 for the original intent of this refactoring.

**Comment by Youssef1313** [comment]
The suggestion of "valid" for interpolation is probably covered by a codefix for the analyzer suggested in https://github.com/dotnet/roslyn-analyzers/issues/2767?

**Comment by DoctorKrolic** [comment]
@Youssef1313 I see. When creating an issue, I thought about this refactoring more like it should be an analizer + codefix, but now I got the original intent. In this context my suggestion is not very good indeed, closing the issue
