### ISSUE TITLE
[Use switch expression (IDE0066)]: Incorrect Code Suggestion

### ISSUE THREAD

**Issue by BraedonWooding** [dotnet/roslyn#60159]
```csharp
        public object Foo(string something)
        {
            switch (something)
            {
                case "Double": return 2.5;
                case "Int": return 2;
                default: throw new Exception("A");
            }
        }
```

Above is some relatively trivial code, this returns an object and functions as expected.  However, C# in Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.0.2 suggests the following transformation through the IDE0066 suggestion...

![image](https://user-images.githubusercontent.com/22880786/158152496-6c8f99b5-8fe3-423c-965f-c59d46d4f8a2.png)

Or that is 

```csharp
        public object Foo(string something)
        {
            return something switch
            {
                "Double" => 2.5,
                "Int" => 2,
                _ => throw new Exception("A"),
            };
        }
```

This results in an implicit cast which causes the return value to be a Double and *NOT* an integer...  This differs from the original behavior.  While I don't think the implicit cast of the expression switch is an issue (since that seems common behavior now even with ternary's) which shouldn't be happening is this suggestion, at-least if you are going to suggest such a transformation it should come with explicit casts like...

```csharp
        public object Foo(string something)
        {
            return something switch
            {
                "Double" => (object)2.5,
                "Int" => 2,
                _ => throw new Exception("A"),
            };
        }
```

**Comment by Youssef1313** [comment]
The unnecessary cast is likely already fixed by https://github.com/dotnet/roslyn/pull/56932

@BraedonWooding Can you update VS and check if IDE0004 goes away?

**Comment by BraedonWooding** [comment]
@Youssef1313 I've just done the upgrade.

Yes it does seem that the unnecessary cast goes away.  However, IDE0066 still is recommended without a cast sadly :(.

Regardless I've updated the description to remove the mention of IDE0004 since that does seem to be resolved in later versions.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/58694

Convert latest main produces this: 

![image](https://user-images.githubusercontent.com/4564579/158272264-d2165b00-27c2-42da-bc47-4d29aa98e9ac.png)

Thanks!

**Comment by BraedonWooding** [comment]
Ahh, and it'll hit Visual Studio 17.2, wonderful.  Thanks.

**Comment by CyrusNajmabadi** [comment]
You're welcome!
