### ISSUE TITLE
VS2017 Preview error VB editor with a Try-Catch inside another Try-Catch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60166]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2017-Preview-error-VB-editor-with-a-Tr/1690561)._

---
[severity:It bothers me. A fix would be nice]
Using Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 1.0
Using the Visual Basic editor.

If you have a Try Catch block and insert a new Try-Catch the "auto created" Try have the "ex As Exception" parameter in the Catch block. 
The same name in both.
The old and the new "auto added".

See the gif to be clear.

Thank you.
Guillermo

![B4423756ea1484facac1ce68a604d13dd637826323082397899_Bug_VS2022_2Try_VB](https://user-images.githubusercontent.com/1408396/159536782-007e7f45-2b70-4e85-b7d8-4eaad3148062.gif)

---
#### Feedback Bot on 3/13/2022, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vatsalyaagrawal** [comment]
@akhera99 FYI...

**Comment by sharwell** [comment]
Blocked on #31879

**Comment by CyrusNajmabadi** [comment]
Closing as we are unlikely to be investing in these experiences.
