### ISSUE TITLE
Can't debug roslyn analizers

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60161]
When I set a breakpoint in any analizer from `Features` layer, it don't trigger, even if I set it before building solution. However, changing code changes behaviour of the launched VS from build. What am I doing wrong?

**Comment by Youssef1313** [comment]
@DoctorKrolic Are you debugging a unit test? or debugging RoslynDeployment?

It would be best to debug from unit test.

**Comment by DoctorKrolic** [comment]
I am Launching as `RoslynDeployment`. Suggestion about debugging unit tests is good, but is it possible to debug as `RoslynDeployment` at all?

**Comment by Youssef1313** [comment]
I think it's because analyzers run out of process. You can try to attach the roslyn process to debugger.

**Comment by DoctorKrolic** [comment]
Out of what process? `devenv.exe` or roslyn code analisis process of service hub? I thought, roslyn works via LSP exept some cases like hovers and all diagnostics are processed on the server side...

**Comment by Youssef1313** [comment]
I think they run in `ServiceHub.RoslynCodeAnalysisService` process so you need to attach this process. @CyrusNajmabadi Can you confirm whether I'm correct here?

**Comment by JoeRobich** [comment]
@DoctorKrolic As @Youssef1313 has said, code analysis runs out of process in the `ServiceHub.RoslynCodeAnalysisService` process.

If it simplifies your workflow, you can disable this behavior in Tools > Options:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/611219/159542112-74d8ccc8-62d4-4f42-8f09-33fa7e8c2497.png">

**Comment by DoctorKrolic** [comment]
@JoeRobich Disabling this check for roslyn VS extension makes debugging analizers a lot more convenient, thanks!

**Comment by DoctorKrolic** [comment]
@Youssef1313 It depends. I prefer first to repro the issue manually in IDE, then fix it, and only then write unit tests. I like, when I can tweak code to see how it changes the behaviour in debugging without need to write another unit test and separately start it.
