### ISSUE TITLE
Add MSBuild task+targets to netcore package

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#6017]

**Comment by gafter** [comment]
@agocke Milestone 1.1?

**Comment by agocke** [comment]
@gafter Yup, sounds good

**Comment by agocke** [comment]
Thinking this should be a separate MSBuild-focused package

**Comment by agocke** [comment]
This is the Microsoft.CodeAnalysis.BuildTask.Portable package added in #7174
