### ISSUE TITLE
VS displays the wrong field value

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#60179]
**Version Used**: 
Visual studio 2022

![image](https://user-images.githubusercontent.com/23723575/158333257-374a2679-3f1d-44e7-af9e-0b8964bc1cf7.png)

**Comment by kelicto** [comment]
I also noticed that when dealing with variables with the same name.
Java style: you need to use the annoying this keyword everywhere (then use it, with highlighting, the effect is more coordinated and comfortable on the whole).
C# style: if you use the slide line style, it can work well, but it will not be pure and single enough. The advantage is that you can easily know its type through the slide line (this style is a little outdated).

**Comment by CyrusNajmabadi** [comment]
This is not roslyn.
