### ISSUE TITLE
Prioritize background work for visible documents

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#60185]
🔗 Improvements derived from investigation of [AB#1493674](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1493674) ([public link](https://developercommunity.visualstudio.com/t/Intellisense-typing-and-highlighting-re/1683883))

* Post-edit operations for visible documents should run before operations for background documents
    * [x] Semantic Classification should delay requests for non-visible documents.
    * [x] Navigate To should delay requests for non-visible documents, only to run after visible documents have completed updating.
    * [x] Inheritance Margin should delay requests for non-visible documents, only to run after visible documents have completed updating.
* Post-edit updates for non-visible documents should run sequentially.
    * [ ] Semantic Classification should send only request updates for one document at a time. Alternately, it would be acceptable to create an API that requests information for several documents at once, and this new API can be used to calculate that update in order in the background.
    * [ ] Navigate To should send only request updates for one document at a time. Alternately, it would be acceptable to create an API that requests information for several documents at once, and this new API can be used to calculate that update in order in the background.
    * [ ] Inheritance Margin should send only request updates for one document at a time. Alternately, it would be acceptable to create an API that requests information for several documents at once, and this new API can be used to calculate that update in order in the background.
* [x] ComputeCompilationAsync should only send one request for each project. If multiple open documents are associated with the same project, each of these documents needs to share the same CompilationAvailable tracker, and only one call to ComputeCompilationAsync is required to update that project.

**Comment by CyrusNajmabadi** [comment]
Update on these.

First, inheritance-margin is just a tagger.  So all work we've done for taggers benefits that.  From now on i'll just have that be implied.  Here's the work done so far:

1. all taggers now pause what they're doing when non-visible: https://github.com/dotnet/roslyn/pull/60371.  Effectively taggers run when they are notified about changes they care about.  However, we suppress those notifications when non visible so the tagger never thinks it has a reason to run.  When the tagger becomes visible again, it kicks off work to bring itself up to date.
2. nav-bar delays itself if non-visible.  https://github.com/dotnet/roslyn/pull/60367.  We can also likely extend this functionality to pause entirely like we do with taggers.  We could even consider just making nav-bar into a tagger itself, where the contents of hte bar are driven off of tags we produce.
3. ComputeCompilationAsync already works with project-cone-semantics, meaning it only cares about syncing its project (and projects it depends on).  On the OOP side we now have a PR that if multiple requests are concurrently asking about the same checksumed-solution-snapshot, that we share the computation on that side to produce the snapshot (https://github.com/dotnet/roslyn/pull/60575).  This means we'll get teh same snapshot with the same compilation trackers, which means that asking for the compilation for that project on the oop side should share all that computation (including the computation from the trackers to make the compilation).

**Comment by CyrusNajmabadi** [comment]
@sharwell I think we can likely close this out.  THe only thing remaining was: "Post-edit updates for non-visible documents should run sequentially."  However, as non-visible documents should no longer do work, we don't have to really be concerned about any coordination for anything they're doing.

**Comment by CyrusNajmabadi** [comment]
PR to bring nav-bar pausing to non-visible documents: https://github.com/dotnet/roslyn/pull/60607

**Comment by CyrusNajmabadi** [comment]
Closing out.  I think the work done so far is sufficient for the goals we have.
