### ISSUE TITLE
Typo: "Apply namespace matches folde preferences"

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/roslyn#60213]
`<trans-unit id="Apply_namespace_matches_folder_preferences">` is set to "Apply namespace matches ***folde*** preferences" on all languages.

What's the best way of fixing this? Simple pull request or is there somewhere else to submit language changes?

**Comment by Youssef1313** [comment]
@danielchalmers Thanks for noting this. A simple PR is the way to go here. If you can build the repository locally, you'll need to only update `FeaturesResources.resx` and leave xlf files untouched. Then, when you build the repository, the xlf files will get updated automatically.
