### ISSUE TITLE
Fix Test_Windows_CoreClr_Debug_Single_Machine job

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60218]
After #59903 was merged, all runs of 'Test_Windows_CoreClr_Debug_Single_Machine' started failing. We missed this since it only runs in rolling builds.

[Example run](https://dev.azure.com/dnceng/public/_build/results?buildId=1644160&view=results)

Also failing in #60207

1. Let's fix the issue causing the job to fail.
2. Let's introduce some method of reporting so that we know when breaks like this have been checked in.

**Comment by JoeRobich** [comment]
https://github.com/dotnet/roslyn/blob/bddc362ffbb3cc541bcc64990727a5bbdf353d23/eng/Versions.props#L200-L205

**Comment by JoeRobich** [comment]
Updated the message fabric bot places on Arcade updates that change the pinned dotnet SDK version. It now includes a task list of things to update, including the NuGet version.

**Comment by JoeRobich** [comment]
> Let's introduce some method of reporting so that we know when breaks like this have been checked in.

I would love to know when two consecutive rolling builds of main have CI failures.
