### ISSUE TITLE
Inline Hints: Modify the tagger logic to be less convoluted

### ISSUE THREAD

**Issue by akhera99** [dotnet/roslyn#60229]
Current logic involves creating a [cache](https://github.com/dotnet/roslyn/blob/cb30fc7bf978188727c259d496dc80f8b3d9bc46/src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTagger.cs#L35) that may not be necessary

Determine other methods to locate the appropriate spans in which to draw the tags and investigate if there are any performance concerns with cache removal.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
