### ISSUE TITLE
add support for HelpKeyword so that error list can support offline help viewer properly

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#6022]
existing HelpLink only works with online situation, we need HelpKeyword support as well to support offline sitatuion.

**Comment by heejaechang** [comment]
fix 
https://github.com/dotnet/roslyn/pull/5907 and https://devdiv.visualstudio.com/DefaultCollection/DevDiv/Default/_git/VS/pullrequest/5553

**Comment by mavasani** [comment]
@heejaechang I think this is already fixed, correct? If so, can you please close this issue?
