### ISSUE TITLE
"Null check can be clarified" assumes derived type check is a null check

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#60221]
Null check can be clarified incorrectly assumes that a type check is a null check.

**Version Used**: 
Version 17.2.0 Preview 2.0 [32303.453.main]

**Steps to Reproduce**:

1.

```
        protected override void Cleanup(bool failed = false)
        {
               this.observer?.OnError(this.Completion.Exception is AggregateException ? this.Completion.Exception.InnerException : this.Completion.Exception);
         }
```

**Expected Behavior**:
No "null check can be clarified

**Actual Behavior**:
```
Message	IDE0150	Null check can be clarified	Microsoft.VisualStudio.ProjectSystem
```

![image](https://user-images.githubusercontent.com/1103906/158731847-3774a56d-c370-4a03-aec8-edeb8edd5669.png)

If above was to be fixed, it would change behavior of the program.

**Comment by CyrusNajmabadi** [comment]
Can you post the type of `this.Completion`?

**Comment by davkean** [comment]
@CyrusNajmabadi Ha! Didn't actually check, I assumed it was Exception but its actually AggregrateException. This is my bad and its doing as designed.

**Comment by CyrusNajmabadi** [comment]
thanks :)
