### ISSUE TITLE
Test ExternalDiagnosticUpdateSourceTests.TestExternalDiagnostics_RaiseEvents is failing

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6023]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/86/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Diagnostics/ExternalDiagnosticUpdateSourceTests/TestExternalDiagnostics_RaiseEvents/

**Comment by tmat** [comment]
@tannergooding Has this failure also been fixed?

**Comment by srivatsn** [comment]
Per Manish, @heejaechang was in a recent discussion about this issue. Is this fixed now?

**Comment by heejaechang** [comment]
@srivatsn let me take a look, not sure what the issue is.

**Comment by heejaechang** [comment]
this unit test has been running. so, I think it no longer repro. please re-activate if it repro again.
