### ISSUE TITLE
The status of the editorconfig file is unedited after modifying the .editorconfig file

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#60233]
**More info:**
The issue doesn't happen when you create a project, then add and modify .editorconfig(.net) file

**Steps to reproduce:**
1. Clone repo: [https://github.com/dotnet/project-system.git](https://nam06.safelinks.protection.outlook.com/?url=https://github.com/dotnet/project-system.git&data=04%7c01%7cv-yuadon%40microsoft.com%7cf48c78f8b5ea4b5a8af508d92f6c2b80%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637592963991132901%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=jH6z9TUjS8T%2B3hxJ1MYsWyi%2BakBvseern/WMkr4gfxk%3D&reserved=0) on git cmd
1. Open ProjectSystem.sln with VS 
1. Add .editorconfig(.net) item on Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles project
1. Change value the .editorconfig file, then observe the file status
1. Close and reopen the .editorconfig file 
1. Observe value of .editorconfig file

**Actual result:**
Step4 result: The status of the .editorconfig file is unedited
Step6 result: The value of the .editorconfig file don't change successfully
![7e24e59b-8981-4846-8ddb-ba2c737b962b](https://user-images.githubusercontent.com/9797472/158859045-3a9071ee-c845-4363-801e-9e366dd6f8ad.gif)

**Comment by Youssef1313** [comment]
Also https://github.com/dotnet/roslyn/issues/54556 and https://github.com/dotnet/roslyn/issues/56676

**Comment by jmarolf** [comment]
duplicate of https://github.com/dotnet/roslyn/issues/54556
