### ISSUE TITLE
No obvious way to "View Code" of an .editorconfig after the designer was added

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#60236]
Typically, files with designers give these options in the context menu in Solution Explorer:

![image](https://user-images.githubusercontent.com/9797472/158860501-13fe613b-9b8d-4fae-b1c0-ccbb49707ec9.png)

**Comment by sharwell** [comment]
Slightly edited the title since there are technically two ways to open it:

1. You can use **Open With...** and select **XML (Text) Editor**
2. You can open the designer and then press <kbd>F7</kbd>

**Comment by Youssef1313** [comment]
The F7 thing loses the color highlighting that existed prior to the EditorConfig UI.

**Comment by jmarolf** [comment]
duplicate of https://github.com/dotnet/roslyn/issues/53120
