### ISSUE TITLE
Tests CscTests.PathMapOption and VbcTests.PathMapOption are failing

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6024]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/86/

**Comment by tmat** [comment]
@gafter

**Comment by tannergooding** [comment]
@tmat That was fixed last night, it should no longer be repro'ing (the job listed is from last night as well).

**Comment by tmat** [comment]
ok
