### ISSUE TITLE
Smart break line does not work with checked / unchecked blocks

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60250]
**Version Used**:  main 32315.191

**Steps to Reproduce**:

1. Create new .net6 console app
2. Type `checked` or `unchecked` and attempt to invoke smart break line (shift enter)

**Expected Behavior**:
Inserts curly braces.  Note this should not apply when doing something like `var m = checked(1+2);` as curly braces are not valid there.
```
checked
{
    $$
}
```

**Actual Behavior**:
Just inserts a new line, see gif.
![smartbreakline_checked](https://user-images.githubusercontent.com/5749229/158919717-3615f094-e9db-4a85-9ea6-ac3abf37ef33.gif)

**Comment by dibarbet** [comment]
cc @Cosifne

**Comment by Cosifne** [comment]
Yeah, I think checked block is missing
