### ISSUE TITLE
C# compiler should not produce 'CS8618 Non-nullable field must contain a non-null value when exiting constructor' warning with null check in constructor

### ISSUE THREAD

**Issue by swardinfo** [dotnet/roslyn#60283]
**Version Used**: 
.NET SDK 6.0.201
Visual Studio Community 2022 Ver 17.1.1

**Steps to Reproduce**:

1. Create a class called Class1 with an int property called Number.
2. Create a class called Class2 with a non-nullable uninitialized Class1 field called _class1, an int property called Number and a constructor with a non-nullable Class1 parameter called class1.
3. Within the Class2 constructor, assign class1 to _class1 then follow this with an if statement that checks if _class1 is not null and if true, assign the _class1.Number value to Class2's Number property.
4. In the project properties set 'Nullable' to 'Enable' and 'Treat warnings ass errors' to unchecked

```C#
    public class Class1
    {
        public int Number { get; set; }
    }

    public class Class2
    {
        private Class1 _class1;

        public Class2(Class1 class1)
        {
            _class1 = class1;

            if (_class1 != null)
                Number = _class1.Number;
        }

        public int Number { get; set; }
    }
```

**Expected Behavior**:
~~There should be no errors or warnings.~~
There should be a different warning that relates to the use of the null check as the one that is produced is ambiguous to the actual problem.

**Actual Behavior**:
The following warning is produced
```
CS8618 Non-nullable field '_class1' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```

The warning is also there if _class1 is assigned a new instance of Class1 instead of the passed in value or if _class1 is a property instead of a field.
```
    // This still produces the warning
    //_class1 = class1;
    _class1 = new Class1();
```
The warning is **not** there if the 'if statement' (null check) is commented out such that the Class2 Number property is assigned the _class.Number value without it.
```
    // This prevents the warning
    //if (_class1 != null)
    Number = _class1.Number;
```

Additional:
I'm not sure of this is related or just a Visual Studio thing but when hovering over the right side of `_class1 = class1;` the pop up message says 

> 'class1' is not null here

 but the left side says 

> '_class1' may be null here

even though it's just been assigned the former's value.

**Comment by Youssef1313** [comment]
This is by-design, I think. When you do an explicit (a.k.a pure) null check, the variable/local state is changed to maybe null.

**Comment by swardinfo** [comment]
I've edited my question to say that the warning given should be relevant to the use of the null check rather than no warning at all.

Whilst using a null check on a value type such as an 'int' will result in the warning
```
The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'
```
Something else would be needed for a non-nullable type as the null check will still produce true or false. Currently, in Visual Studio, when the warning occurs the class identifier is highlighted with the green underline, whereas I would have thought that the actual null check should have it here. I'm guessing this is a Visual Studio and not a compiler issue but it did lead me into a wild goose chase, trying to figure why the argument I'd passed in was null.

@Youssef1313 

> This is by-design, I think. When you do an explicit (a.k.a pure) null check, the variable/local state is changed to maybe null.

I'm not sure that designing in side effects is a good option. Merely observing an object's state should not change it. Imaging you had the following with a bool that's value gets changed simply using it in an if statement. The result could be disastrous.

```
bool engineHasOil = true;
if (engineHasOil) // Using the if statement changes engineHasOil to false
{
    DriveCar;
    Console.WriteLine("Engine seized, pay $20000 to get repaired");
}
```

**Comment by Youssef1313** [comment]
> if (engineHasOil) // Using the if statement changes engineHasOil to false

This can't happen and isn't related to the original question. The thing that happens is "*pure* null checks change the variable *state* to maybe-null".

This doesn't change a variable *value.
