### ISSUE TITLE
New Rename UI disappears when typing

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#60288]
**Version Used**: Version 17.2.0 Preview 3.0 [32316.126.main]

I tried to use the new rename UI using the keyboard and it disappeared :(

![RenameUIDisappear](https://user-images.githubusercontent.com/754264/159191298-8dd50425-3a52-4324-94ba-55ca2f7af54b.gif)

If I use the mouse to do the selection in the textbox, it works fine.

FYI @ryzngard in case this is known

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this.
