### ISSUE TITLE
Public API analyzer not running reliably in Roslyn

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6028]
There is a bug in the Public API analyzer that causes it to throw on startup when there are duplicate entries in API files:

https://github.com/dotnet/roslyn-analyzers/issues/312

A recent change to our code base inadvertently triggered just such a case in our API files.  This added `SourceKind.Interactive` to both the shipped and unshipped files:

https://github.com/dotnet/roslyn/commit/2f6d4739ee3b7ee3cf23de138615d021770982b7

When the compiler attempts to load an analyzer and it throws on startup it will issue a diagnostic with severity "Information".  By default MSBuild does not report such diagnostics so this change effectively disabled public API checking on Microsoft.CodeAnalysis (on accident, no way commit author would have known this happened).  

This needs to be fixed on two fronts:

- Failing to load analyzers in our repo should be an error. 
- Need to fix up the missing entries in the API files.

**Comment by tmeschter** [comment]
The first bullet point is tracked by #6001.

**Comment by jaredpar** [comment]
@tmeschter good catch.  Should have a PR here in a bit that covers both.

**Comment by davkean** [comment]
For contributors, this results in a message showing up in in the Error List similar to:

Message	AD0001	Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added.'.
