### ISSUE TITLE
New rename dialog always renames file once checkbox is selected

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#60294]
**Version Used**: VSMain

**Steps to Reproduce**:

Pre-req: Enable new rename dialog

1. Initiate the rename on a class
2. Select "Rename file":
![image](https://user-images.githubusercontent.com/2008729/159330403-fd5bf350-3efa-4189-9658-5528890685da.png)
3. Execute it
4. Go to another local somewhere and rename it

**Expected Behavior**: Local is renamed and file is not renamed to match

**Actual Behavior**: Local and file get renamed to be the same
![devenv_egNRLrExV2](https://user-images.githubusercontent.com/2008729/159330577-34927ef1-7c2c-4717-ba4a-46f55467cfa7.gif)

/cc @ryzngard

**Comment by KirillOsenkov** [comment]
@ryzngard this bug is very impactful for VSMac, any rename operation renames the file. Would be nice to prioritize this.

I think we should flip the default of RenameFile option to false, for other Roslyn hosts as well.

**Comment by ryzngard** [comment]
> @ryzngard this bug is very impactful for VSMac, any rename operation renames the file. Would be nice to prioritize this.
> 
> I think we should flip the default of RenameFile option to false, for other Roslyn hosts as well.

Is this only for the new rename dialog that's a preview feature? I didn't think that was applicable to VSMac... Likely a different issue entirely.

**Comment by KirillOsenkov** [comment]
we still use the old rename dialog in VSMac and it broke with the latest Roslyn insertion

**Comment by KirillOsenkov** [comment]
Confirmed setting `InlineRenameSessionOptionsStorage.RenameFile` to false fixes the bug for us.

**Comment by drewnoakes** [comment]
I just started seeing this today. I rename stuff all the time. Has something changed recently?

**Comment by davidwengier** [comment]
The issue, AFAIK, is the checkbox state being used in places it shouldn't. Perhaps you only recently checked the checkbox?

**Comment by drewnoakes** [comment]
A workaround is:

1. Invoke rename on a top-level type whose name matches the file.
2. Uncheck the "rename file" checkbox
3. Dismiss the rename

After that, you can rename other symbols without also changing the file name.
