### ISSUE TITLE
Search for method names in classes using Solution Explorer search is not consistent in case-sensitivity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60305]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Search-Solution-Explorer-fix/1685656)._

---
[severity:It bothers me. A fix would be nice]
Visual Studio 2022(Enterprise) için Search solution exprorer'da büyük küçük harf duyarlılığı çok fazla. Class'ların içerisinde metot ararken bazen sonuç getirmiyor.
(Örneğin : UserService isimli class'ımda AddUser isimli bir metodum olsun. Arama kısmında AddUser yazmama gerek kalmasın adduser dediğimde de sonuç getirsin lütfen. Good luck with :d

---
#### Feedback Bot on 2/9/2022, 05:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Chris Wang [MSFT] on 2/10/2022, 00:45 AM: 

<p>Thank you for sharing your feedback!<br>
There are two things that need to be clarified:</p>
<ol>
<li>Make sure your projects are loaded ready, then you can search anything in Solution Explorer</li>
<li>Did you have enabled the “Search within file contents” in Solution Explorer search box dropdown list? Because in VS 2022, we’ve changed the default search behavior in solution explorer to not search file contents (to improve performance). If you’d like to enable it, click on the drop down next to search text box (on the right of the magnifying glass), and there you can check “Search within file contents”.</li>
</ol>
<p>We are looking forward to hearing from you soon.<br>
Thanks</p>

#### Feedback Bot on 2/23/2022, 01:03 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Feedback Bot on 3/7/2022, 05:21 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

**Comment by mikadumont** [comment]
Translation: `Case sensitivity is too high in the Search solution explorer. When searching for methods in classes, sometimes it does not return any results. I have a method named AddUser in my class named UserService. I don't need to type AddUser in the search section, and when I say adduser, it will return results, please.`

In the turkish language unicode characters have complext case-sensitivty rules similar to the german "double s". This sounds like the rules aren't be properly handled by the platform. Seems like these rules are not being properly handled by us since (as I understand it) we do the filtering or Ctrl+T search?

**Comment by CyrusNajmabadi** [comment]
We use:

```c#
            culture ??= CultureInfo.CurrentCulture;

            _compareInfo = culture.CompareInfo;
```

So it may be hte case that the current culture comparer has issues here.  we could potentially try the current culture and fallback to Invariant, but that also means doubling the search cost of these searches for people in different regions.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
