### ISSUE TITLE
"Extract method" - generated method with expression body if possible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60303]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extract-method---generated-method-with/1692414)._

---
It is possible to refactor C# code with the function "Extract method". But the generated method has always a block body, even if an expression body is possible:

```
var numbers = Enumerable.Range(0, 100);
var result = numbers. Select<int, int>(x => 2 * x);
```

"Extract methon" on "2 * x" results:

```
var numbers = Enumerable.Range(0, 100);
var result = numbers. Select<int, int>(x => Duplicate(x));

int Duplicate(int x)
{
    return 2 * x;
}
```

But here the code can be shorten:

```
int Duplicate(int x)
    => 2 * x;
```

---
#### Feedback Bot on 3/15/2022, 08:20 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by Youssef1313** [comment]
This should respect `csharp_style_expression_bodied_methods`

**Comment by ryzngard** [comment]
Confirmed working as expected with `csharp_style_expression_bodied_methods`
