### ISSUE TITLE
Region should indent when within function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60306]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Region-should-indent-when-within-functio/1646614)._

---
When #Region is used inside a function, it should indent with the function. Having the region flush with the left edge makes it look like the function is at the end.

---
#### Feedback Bot on 1/25/2022, 10:19 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

#### Dante Gagne [MSFT] on 1/28/2022, 10:39 AM: 

<p>This functionality is actually language specific. Can I assume you’re doing this in C#?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### David Sherwood on 1/28/2022, 01:23 PM: 

<p>No, I’m using <a target='_blank' href="http://VB.net">VB.net</a>.</p>

#### Feedback Bot on 3/4/2022, 01:38 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by CyrusNajmabadi** [comment]
Closing out as intentional.  We have considered this and explicitly rejected this in teh past.
