### ISSUE TITLE
Refactor - surround highlighted text with Try/Catch

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60302]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactor---surround-highlighted-text-wit/1694885)._

---
I would like to be able to highlight some code and with [Ctrl+.] get an option to wrap that in a try/catch or try/finally or try/catch/finally block.

```
string value = await Dosomething(). ConfigureAwait(false);
```
highlight everything to the right of the `=` and choose try/catch would generate
```
string value;
try
 {
   value = await Dosomething(). ConfigureAwait(false);
 }
catch (Exception e)
{
  
}
```

---
#### Feedback Bot on 3/18/2022, 00:47 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by sharwell** [comment]
This feature is currently provided through a code snippet (**Edit &rarr; IntelliSense &rarr; Surround With... &rarr; `try`**).

**Comment by CyrusNajmabadi** [comment]
Closing as this is already supported.
