### ISSUE TITLE
Speculating with `nameof` doesn't produce a `NameOfBinder` leading to incorrect results

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60337]
**Version Used**: 

main

**Steps to Reproduce**:

```csharp
        [Fact]
        public void NameOfNintSpeculation()
        {
            var source = @"
class C
{
    void M()
    {
        var x = nameof(nint);
    }
}
";
            var comp = CreateCompilation(source, parseOptions: TestOptions.Regular9);
            comp.VerifyDiagnostics(
                // (6,24): error CS0103: The name 'nint' does not exist in the current context
                //         var x = nameof(nint);
                Diagnostic(ErrorCode.ERR_NameNotInContext, "nint").WithArguments("nint").WithLocation(6, 24)
            );
            var tree = comp.SyntaxTrees.Single();
            var root = tree.GetRoot();
            var existingNint = root.DescendantNodes().OfType<ArgumentSyntax>().Single().Expression;
            var existingNameOf = root.DescendantNodes().OfType<InvocationExpressionSyntax>().Single();
            var model = comp.GetSemanticModel(tree);
            var nameofToSpeculate = (InvocationExpressionSyntax)SyntaxFactory.ParseExpression("nameof(nint)");
            var speculativeSymbolInfo = model.GetSpeculativeSymbolInfo(existingNameOf.SpanStart, nameofToSpeculate.ArgumentList.Arguments[0].Expression, SpeculativeBindingOption.BindAsExpression);
            var symbolInfo = model.GetSymbolInfo(existingNint);
            
            Assert.Equal(symbolInfo, speculativeSymbolInfo);
        }
```

**Expected Behavior**:

Test passes. Both `symbolInfo` should be empty.

**Actual Behavior**:

Test fails. Things go wrong because there is no `NameOfBinder` in chain when speculating, so `IsInsideNameof` is false here:

https://github.com/dotnet/roslyn/blob/df7da42d03887aef94d2752a8e0d6b96c9980554/src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs#L934-L939

**Comment by jcouv** [comment]
Assigning to @cston for triage (I think this is a `nint/nuint` specific issue)

**Comment by Youssef1313** [comment]
@jcouv Not really `nint/nuint`-specific. I discovered this in the context of a semi auto property test when I worked on disallowing `nameof(field)`

Any code path that relies on `NameofBinder` in the chain will fail when speculating.

**Comment by AlekseyTs** [comment]
I do not think this is a bug. One shouldn't expect that the speculation happens as though the new expression will replace the argument at the provided position. Position determines what is in scope and what is accessible, but doesn't mean that we should interpret the expression as though it is an argument of ```nameof```.
```
        /// <param name="position">A character position used to identify a declaration scope and
        /// accessibility. This character position must be within the FullSpan of the Root syntax
        /// node in this SemanticModel.
        /// </param>
```

**Comment by 333fred** [comment]
Closed as by-design

**Comment by Youssef1313** [comment]
@AlekseyTs I thought this is already done with `typeof`:

**Comment by AlekseyTs** [comment]
> So was expecting something similar with `nameof`.

That is an "ancient" code and I wish we didn't add that special handling.
