### ISSUE TITLE
Respect C# naming conventions when generating `record`'s members

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60342]
**Version Used**:
VS 2022 v17.2 Preview 2.1, C# 10

**Steps to Reproduce**:
Start code:
```
new Person($$);

public record Person(string FirstName, string LastName);
```
Then invoke signature help where `$$` is.

**Expected Behavior**:
Signature help shows, that generated constructor's parameters are in camelCase.

**Actual Behavior**:
Constructor's parameters are generated from record's properties without additional changes, which results in PascalCase:
![devenv_V8LkE8sXex](https://user-images.githubusercontent.com/70431552/159762343-feb791c8-b042-49f8-9512-e2f045912ebf.png)

Signature help is only one way of reproducing this issue. Inline parameters also show this:
![devenv_ikn2kYZ0Mf](https://user-images.githubusercontent.com/70431552/159762692-1a3b553e-8a1a-44e3-99c6-894d47b12211.png)

So, in the end, there is no doubt, that the problem lies in compiler layer when generating member's names while lowering records

**Comment by Youssef1313** [comment]
This is going to be a large breaking change if taken. I don't think the compiler team will make such a breaking change, but let's wait for someone :)

cc @jcouv

**Comment by DoctorKrolic** [comment]
I see this as breaking change only in case, when someone uses named arguments like `new Person("Some", LastName: "Name")`. For already compilered binaries old naming will stay until source get recompilered in new version. In all other scenarios it is compatable, isn't it?

**Comment by Youssef1313** [comment]
> I see this as breaking change only in case, when someone uses named arguments

Yes, that's the case when it will be a breaking change.

---

> For already compilered binaries old naming will stay until source get recompilered in new version.

Yes, but this doesn't mean there is no breaking change.

**Comment by CyrusNajmabadi** [comment]
We will absolutely not change this.  It's a core part of the design and is well understood that hte parameter and record properties are named the same.  The lang design explicitly rejects getting into the space of casing :)
