### ISSUE TITLE
Convert to property doesn't work with expression bodied members

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#6034]
``` C#
class C
{
    int GetNumber() => 42;
}
```

Invoke convert to property and you end up with:

```C#
class C
{
    int Number { get; } => 42;
}
```

We should remove the `{get;}` in this case.

**Comment by CyrusNajmabadi** [comment]
Opening so we track fixing this for Update1.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/6213
