### ISSUE TITLE
Missing space between "internal" access modifier and "class" keyword when creating a new C# class when using File Scoped Namespaces as a VS default.

### ISSUE THREAD

**Issue by nicktheone** [dotnet/roslyn#60345]
**Version Used**: 
Microsoft Visual Studio Community 2022 (64 bit) - Current
Versione 17.1.1

**Steps to Reproduce**:

1. Create a new .NET 6 Console app.
2. Change the default namespace handling in VS (not with an .editorconfig file) from Block to File Scoped.
3. Create a new class from right-click on project>add>class...

**Expected Behavior**:
VS should generate a correctly worded file like so:
```namespace PriceChecker;
internal class Class1
{
}
```

**Actual Behavior**:
VS generates a file with a missing space/typo like so:
```namespace PriceChecker;
internalclass Class1
{
}
```

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/59091

**Comment by jinujoseph** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/58974
