### ISSUE TITLE
Odd behaviour with async method declaration: bad keyword suggestion

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60340]
**Probably related to** https://github.com/dotnet/roslyn/issues/60339

**Version Used**:
VS 17.2 Preview 2.1

**Steps to Reproduce**:
Start code:
```
class Test
{
    public async $$
}
```

**Expected Behavior**:
`async` keyword is not suggested

**Actual Behavior**:
`async` keyword is even preselected:
![devenv_WBraUCkb1Q](https://user-images.githubusercontent.com/70431552/159758791-f6b430fb-9628-4403-962b-b25381a22014.png)

**Comment by CyrusNajmabadi** [comment]
It's legal to have an async method that returns a type called `async`.  That said, this is extremely minor.  In general we do not go out of our way to try to ensure a keyword is *not* available.  If it's missing where valid, that's bad.  If it's available where not, that's NBD (esp. when a list is going to have 10k elements in it).

**Comment by DoctorKrolic** [comment]
IMO this is a weird language design, that accepts having a type, which name does not match naming conventions and matches keyword. Why not to allow, for example, `public` type name in this case?

Anyway, if `async` can be a return type, then IDE should check, if such type is present in the context and if not, treat `async` as keyword here and in all other isseus I made about this

**Comment by jmarolf** [comment]
Certainly agree that while `async async` is valid it's not likely what the user want to type. Would be fine with us having a more granular context so we don't suggest keywords that are unlikely to be helpful.

**Comment by CyrusNajmabadi** [comment]
> Why not to allow, for example, public type name in this case?

`public` is a keyword, and was at 1.0, so we could reserve it.  `async` didn't exist as a feature until C# 5.0.   We have to be backward compatible with code that may have been written in all prior versions.  That's part of our high compat bar.

> Anyway, if async can be a return type, then IDE should check, if such type is present in the context and if not, treat async as keyword here and in all other isseus I made about this

We can do that.  However, we generally have an assessment around cost of trying to handle these narrow scenarios, versus value achieved from it.  For example, once a single extra character is typed, then it becomes a keyword.  If a change can be made here that is cheap we would likely take it.  However, we're unlikely to expend a lot of effort to solve this given all the much higher priority things on our plate right now.

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic we'd certainly accept a reasonable PR here.
