### ISSUE TITLE
Odd behaviour with async method declaration: wrong types suggestion

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60341]
**Probably related to** https://github.com/dotnet/roslyn/issues/60339

**Version Used**:
VS 2022 v.17.2 Preview 2.1

**Steps to Reproduce**:
Start code:
```
class Test
{
    public async $$
}
``` 

**Expected Behavior**:
Only `Task`, `Task<>`, `ValueTask` and `ValueTask<>` are suggested

**Actual Behavior**:
![devenv_VObHb5szpa](https://user-images.githubusercontent.com/70431552/159759684-c832da14-5efe-4f3d-9e64-991982b0134c.gif)

**Comment by CyrusNajmabadi** [comment]
This would be a reasonable thing to filter down to.  Note: we would want any type with `[AsyncMethodBuilder]` on it.

**Comment by sharwell** [comment]
@CyrusNajmabadi If you put `[AsyncMethodBuilder]` on the method itself, does it allow any type or only awaitable types?
