### ISSUE TITLE
"Convert to LINQ" refactoring suggestions ignore side effects in conditional

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60355]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Convert-to-LINQ-refactoring-suggestion/1697375)._

---
The following code is meant to grab an element of a particular type out of a list, using implicit assignment in the if statement. Convert to LINQ separates the conditional body from the conditional assignment. Given this code:

```cs
interface IElement {}
List<IElement> list;
public T Get<T>() where T : IElement
{
    foreach (var el in list)
    {
        if (el is T t)
        {
            return t;
        }
    }
    return default;
}
```

This suggestion changes the function body to:

```cs
    foreach (var _ in from el in list
                      where el is T t
                      select new { })
    {
        return t;
    }
```

or the call form:

```cs
    foreach (var _ in list. Where(el => el is T t). Select(el => new { }))
    {
        return t;
    }
```

Neither of which is valid because they don't create the name 't' in the context for the return statement.

---
#### Feedback Bot on 3/20/2022, 06:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MisinformedDNA** [comment]
I'm also seeing this with the below code:

```cs
var list = new List<C>();
foreach (var item in list)
{
    if (item is D derivedItem)
    {
        Console.WriteLine(derivedItem.ToString());
    }
}

public class C {}

public class D : C {}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this issue.
