### ISSUE TITLE
`[SuppressMessage]` should be able to suppress `dotnet_style_namespace_match_folder` warnings

### ISSUE THREAD

**Issue by snebjorn** [dotnet/roslyn#60361]
**Version Used**: 

System.Diagnostics.CodeAnalysis

Not sure how to find the version. Doesn't seem to be explained. But here's my dotnet info

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Steps to Reproduce**:

1. Add `dotnet_style_namespace_match_folder = true` to your `.editorconfig`
2. Name a namespace that doesn't match the folder. Extension methods for `Microsoft.Extensions.DependencyInjection` is a typical example of this.
Here's a real world example from AutoMapper https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/986267d95da70fef4c4811b59065533137bdd304/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L1
3. Try to suppress the style choice as you actually want the namespace to be `Microsoft.Extensions.DependencyInjection`.
4. Observe that `[SuppressMessage]` can't be used on namespaces.

**Expected Behavior**:

This is what I was hoping to do

```cs
[SuppressMessage(...)]
namespace Microsoft.Extensions.DependencyInjection;

public static class ServiceCollectionExtensions
{
```

**Actual Behavior**:

This is what I had to do.

```cs
#pragma warning disable IDE0130
namespace Microsoft.Extensions.DependencyInjection;
#pragma warning restore IDE0130

public static class ServiceCollectionExtensions
{
```

Using `#pragma` for styling/linting feels wrong. 
It's not clear what that does, you basically have to know what it does. 
Besides It's two lines instead of one.

**Comment by Youssef1313** [comment]
This is limited by the language. A namespace cannot have attributes.

You can use a one line only (omit the `restore` line and keep only the `disable`). It's common to add a comment besides the `#pragma warning disable` to say what the actual suppressed diagnostic is. I also believe there is a quick info if you hover over IDE0130

**Comment by jcouv** [comment]
I agree with @Youssef1313. Closing as by-design. 
I couldn't find a proposal to allow attributes on namespaces on csharplang repo. I think it wouldn't work in general, but might be worth considering if we added support for compilation-only attributes (ie. attributes that wouldn't be emitted, since it's no clear where namespace-level attributes would be emitted...).

**Comment by snebjorn** [comment]
What I'm really after is a unified and descriptive way to suppress what is commonly known as "linting".

`[SuppressMessage]` can't be used on namespace or directive (`using`) and possibly others. This is a problem.
`#pragma` doesn't have a `disable-next-line`. This makes it more verbose than it needs to be.

Both of them use non-human-readable ids. This is error prone and impossible to guess if it's correct in a code review.
`[SuppressMessage]` does include a human-readable part. But it's very verbose.

I feel like ESLint strikes a good balance. They offer a [host of way to suppress rules](https://eslint.org/docs/user-guide/configuring/rules#disabling-rules) and can even suppress multiple rules. It's non-verbose, human-readable, versatile. It's working great in the JS/TS community.

**Comment by Youssef1313** [comment]
Related discussion: https://github.com/dotnet/csharplang/discussions/1070
