### ISSUE TITLE
Non-public classes are visible while non-public methods aren't?

### ISSUE THREAD

**Issue by aybe** [dotnet/roslyn#60360]
**Version Used**: 
- Microsoft.CodeAnalysis.CSharp 4.1.0
- Microsoft.CodeAnalysis.Analyzers 3.3.3

**Steps to Reproduce**:

Here's the environment, two classes in a library, one being public, the other being internal; each of them have, public, private and internal methods all decorated with an attribute:

<img width="217" alt="devenv_IqIAXIdhl9" src="https://user-images.githubusercontent.com/1537591/159932040-f7826ab1-3a1e-4e2f-99d4-8545225acbf8.png">

What I'm looking for is, to find which methods are decorated with that particular attribute, no matter whether they're public or not.

For this, I've written the following generator and debugged it using [these instructions](https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022).

```
using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Generator;

[Generator]
public class HelloSourceGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        var assemblySymbols = context.Compilation.SourceModule.ReferencedAssemblySymbols;
        var assemblySymbol = assemblySymbols.Single(s => s.Name.StartsWith("Library"));
        var assemblyMembers = assemblySymbol.GlobalNamespace.GetMembers();

        foreach (var namespaceOrTypeSymbol in assemblyMembers)
        {
            var symbols = namespaceOrTypeSymbol.GetMembers();

            foreach (var symbol in symbols)
            {
                if (symbol is INamedTypeSymbol namedTypeSymbol)
                {
                    var members = namedTypeSymbol.GetMembers();

                    foreach (var member in members)
                    {
                        if (member is IMethodSymbol methodSymbol)
                        {
                            var attributes = methodSymbol.GetAttributes();

                            foreach (var attribute in attributes)
                            {
                                var s = attribute.AttributeClass?.ToString();
                                if (s == "Library.TestAttribute")
                                {
                                    Console.WriteLine(member);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required for this one
    }
}
```

**Actual Behavior**:

The result is quite surprising, neither of the non-public methods are returned, but public methods whether they are in a public or non-public type are:

```
Microsoft (R) Visual C# Compiler version 4.1.0-5.22165.10 (e555772d)
Copyright (C) Microsoft Corporation. All rights reserved.

Library.InternalClass.PublicMethod()
Library.PublicClass.PublicMethod()
```

**Expected Behavior**:

Unless I'm mistaken, something being non-public shouldn't be returned according to what appears to be the default behavior.

Now in my case, I'm actually looking for the opposite, being able to access anything regardless its visibility.

Note: I've only started coding my first source generator yesterday so there's a strong possibility that I got it all wrong.

Here's a repro: https://github.com/aybe/SourceGeneratorTests

**Comment by CyrusNajmabadi** [comment]
If you're referencing a dll, i don't believe there's any guarantee that it will contain non-public members.  From teh language's perspective there is no difference if you are referencing something that has a non-visible member, vs the member not being there at all.

Note: if you walk the source directly though (as opposed to getting it from ReferencedAssemblySymbols) you will likely see it.

**Comment by aybe** [comment]
I'm going to give a try in analyzing the sources directly and see if that makes any difference.However, how would you explain that in the example I gave, that a public method in an internal type is indeed visible but not the other way around? I mean, how did the analyzer decided that this member ought to be exposed but not for the other cases? On Mar 24, 2022 18:24, CyrusNajmabadi ***@***.***> wrote:
If you're referencing a dll, i don't believe there's any guarantee that it will contain non-public members.  From teh language's perspective there is no difference if you are referencing something that has a non-visible member, vs the member not being there at all.
Note: if you walk the source directly though (as opposed to getting it from ReferencedAssemblySymbols) you will likely see it.

**Comment by aybe** [comment]
The devil was in the details, I rewrote it from scratch and after spending a long time in the debugger it's working now!

In fact there's getting the members from the referenced assembly symbols in the source module was wrong, got them from the global namespace instead and now every single member is visible no matter its visibility.
