### ISSUE TITLE
Records with `;` body break references to members from record attribute

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#60379]
**Version Used**: 

Master branch 25.03.2022

**Steps to Reproduce**:

Compile the following code:
```c#
using System;

[Obsolete(nameof(Id))]
record R1(string Id) { }

[Obsolete(nameof(Id))] // CS0103: The name 'Id' does not exist in the current context
record R2(string Id);
```

**Expected Behavior**:

Both records compile fine.

**Actual Behavior**:

> CS0103: The name 'Id' does not exist in the current context

for `record` declaration with `;` body.

**Comment by jcouv** [comment]
Thanks for reporting this. It was fixed in https://github.com/dotnet/roslyn/pull/40525 (merged in 17.3p2)
