### ISSUE TITLE
The Type property from a IPropertySymbol is null / throws exception?

### ISSUE THREAD

**Issue by StefH** [dotnet/roslyn#60380]
**Version Used**: Microsoft.CodeAnalysis.CSharp 4.1.0

**Steps to Reproduce**:

1. Define a class in a .NET 6 project (implicit usings enabled)
``` c#
public class User
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? Date { get; set; }
}
```

2. Get the symbol via the call `GetTypeByMetadataName`
``` c#
var symbol = _context.Compilation.GetTypeByMetadataName("MyNameSpace.User");
```

The symbol is correctly found.

3. Get the property "Date"
``` c#
var property = classSymbol.NamedTypeSymbol.GetMembers("Date").First();
``` 

**Expected Behavior**:
``` c#
var type = property.Type; // This should be "DateTime?"
```

**Actual Behavior**:
``` c#
var type = property.Type; // Actually it's null (Object reference not set to an instance of an object.)
```
And the debugger shows this:
![image](https://user-images.githubusercontent.com/249938/160122921-cc93c444-5da0-4e30-a4a7-a207ef75e8ce.png)

**Comment by StefH** [comment]
@Youssef1313 
When running that code inside a source-generator, it fails.

See this project https://github.com/StefH/PropertySymbol

(Start the console-app in debuyg-mode)

**Comment by Youssef1313** [comment]
This is only reproducible if I added a breakpoint on the `Console.WriteLine(property.Type);` and try to inspect with the debugger.

I think the debugger tried to evaluate something early leading to a bad symbol state or something like that.

**Comment by StefH** [comment]
Note that this error is only for the "DateTime? Date".
The "string FirstName" does work correct.

**Comment by Youssef1313** [comment]
@jcouv 

```
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertySymbolBase.get_TypeWithAnnotations()
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.PropertySymbol.Microsoft.CodeAnalysis.IPropertySymbol.get_Type()
```

**Comment by AlekseyTs** [comment]
I am not able to reproduce this issue. If you are still able to reproduce it, please provide clear and complete repo steps and reactivate the issue.
