### ISSUE TITLE
Typing await followed by space puts a space between method name and the parentheses

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60389]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Typing-await-followed-by-space-puts-a-sp/1702497)._

---
When I convert a method to async and go to existing code that calls the method to convert to call asynchronously, the editor puts a space in between the method name and the parens.

---
#### Feedback Bot on 3/24/2022, 06:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.
