### ISSUE TITLE
VS 2022 suggesting code breaking simplifications

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60387]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-suggesting-code-breaking-simplif/1702267)._

---
Hi

As you can see on the screenshow, VS suggest to remove the casts being done.
The signature of the method being called:
`public static bool IsTargetModelDifferent<T>(T source, T target) where T : class`

The suggestion removes one casts at at time, so it ends up removing them all, if you keep follow the suggestions it gives you.
The reason this brakes the code, is because the called method at some point does a `typeof(T). GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)` which only want to look a declared properties for the specified type.
By following the suggestions, that type has now changed.

---
#### Tracy Wang [MSFT] on 3/24/2022, 07:53 PM: 

<p>Thank you for your feedback! Does this reproduce for all project or specific project? If it’s reproduce with the specific project, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you could provide some screenshots of this issue. Thanks for your help!</p>
<p>We look forward to hearing from you!</p>

#### Eske Sunddal Hansen on 3/25/2022, 01:41 AM: 

(private comment, text removed)
#### Eske Sunddal Hansen on 3/25/2022, 01:48 AM: 

(private comment, text removed)
#### Feedback Bot on 3/25/2022, 02:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Picture:

![image](https://user-images.githubusercontent.com/4564579/160213134-be09689f-2ffb-4029-838e-8c189b90e669.png)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  Eske, can you provide a full repro where you're seeing this?

**Comment by m910q** [comment]
Hi

I provided that on the Developer Community feedback site.
Here's a copy:
[B2100ead7e83e42ec8861603dd1815be7637837944637742894_Feedback.zip](https://github.com/dotnet/roslyn/files/8360968/B2100ead7e83e42ec8861603dd1815be7637837944637742894_Feedback.zip)

I changed the called method to output its found properties, so its easy to spot the difference.
It happens on both .NET Framework 4.5.2 and .NET 6

**Comment by CyrusNajmabadi** [comment]
I can't repro this issue.  This is what i see:

![image](https://user-images.githubusercontent.com/4564579/160725375-4f95c563-b964-4e28-85e7-faffafea99bb.png)

However, if i choose 'fix all in document' it correct changes it to:

![image](https://user-images.githubusercontent.com/4564579/160725434-4d391262-d4d8-4c2e-bf60-b3160d928442.png)

Which is correct where no code meaning has changed.  No repro on any issue here.
