### ISSUE TITLE
When I copy text which includes a stack trace, the Stack Trace Explorer window appears, covering other content

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60382]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-I-copy-text-which-includes-a-stack-/1697188)._

---
[regression] [worked-in:17.0.7]
When I copy text which includes a stack trace, the Stack Trace Explorer window appears, covering other content. I cannot find an option to disable this behavior.

Please make this optional and make it easy to disable this “feature” from the window which pops up itself.

This is [documented as a feature in the 17.1.0 release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1710--visual-studio-2022-version-1710). It says:

> There is now a Stack Trace Explorer Window that displays stack traces from the clipboard allowing you to click and navigate directly to the related code. By default, if you copy a stack trace from your solution and then switch focus to the Stack Trace Explorer window, the stack trace will automatically appear. To open the Stack Trace Explorer window, go to View > Other Windows and select Stack Trace Explorer. 
> ![Stack Explorer](https://docs.microsoft.com/en-us/visualstudio/releases/2022/media/17.1/17.1_p2_stack_trace_explorer.gif)

The text “by default” implies that this is a configuration or optional feature. However, I cannot find the option to disable it. Perhaps it is configurable but finding out how to configure it is difficult. If someone lets me know how to configure it, that’d make me happy!

Thanks!

---
#### Feedback Bot on 3/21/2022, 00:32 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

#### Mika Dumont [MSFT] on 3/21/2022, 05:20 PM: 

<p>Thanks for taking the time to provide this feedback. You can disable this behavior in Tools &gt; Options &gt; Text Editor &gt; C# &gt; Advanced and at the bottom you can deselect the option to automatically open Stack Trace Explorer on focus. Please continue to provide feedback and help us be even better.</p>

#### Nathan Phillip Brink (binki) on 3/22/2022, 06:56 AM: 

<p>Thanks. I thought that if I search “Stack Trace” in the options dialog it would have shown me the category where that option was shown. I was not willing to manually search through every category. Because the Options dialog search did not return any results, I had filed this issue. It turns out it is an option after all and this issue itself documents how to find it.</p>

**Comment by mikadumont** [comment]
We should make sure Stack Trace Explorer settings show up in CTRL+Q & Tools Options search. @ryzngard

**Comment by ryzngard** [comment]
This feature has been changed to disabled by default

**Comment by citymaus** [comment]
I have supposedly disabled this behavior in VS > Tools > Options > Text Editor > C# > Advanced > Automatically open Stack Trace Explorer on focus > Unchecked, and yet I still get the annoying stack trace window popups whenever a stack trace is in my clipboard. Please reopen this issue.

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.1.2

**Comment by CyrusNajmabadi** [comment]
@citymaus can you try on 17.3:

![image](https://user-images.githubusercontent.com/4564579/180249473-e2812c27-3771-417f-a40f-a447de3b2585.png)

?

thanks!

**Comment by citymaus** [comment]
@CyrusNajmabadi That fixed me up -- thank you!

**Comment by CyrusNajmabadi** [comment]
@jfogi expand the languages menu.
