### ISSUE TITLE
Analyzer to check line length does not exceed predefined value.

### ISSUE THREAD

**Issue by voroninp** [dotnet/roslyn#60422]
What part of Roslyn API should I use to check lines, if I want to create an analyzer which reports lines with the lengths exceeding some configured value?

**Comment by CyrusNajmabadi** [comment]
You'd want to use a [DiagnosticAnalyzer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticanalyzer?view=roslyn-dotnet-4.1.0).  Thanks!

**Comment by CyrusNajmabadi** [comment]
> Should I register action for all kinds of nodes and then use location and then call GetLineSpan ?

I would just register a SyntaxTree action and then just walk the lines of hte SourceText associated with teh SyntaxTree :)   You can look at each line and determine it's end point and if that goes past your preferred column.  Cheers!
