### ISSUE TITLE
Test plan for UnsignedRightShift feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#60433]
Feature branch - https://github.com/dotnet/roslyn/tree/features/UnsignedRightShift
Specification - https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/unsigned-right-shift-operator.md
Proposal: https://github.com/dotnet/csharplang/issues/4682

## Compiler

- [x] LangVer
- [x] Update test plan
- [x] Verify behavior of VB
- [x] Verify behavior of C++/CLI
- [x] Inform F# of changes

### Public APIs

- [x] IOperation
  - [x] shift: `TestBinaryOperators_UnsignedRightShift`
  - [x] compound assignment?
  - [x] CFG
- [x] Symbol display on `>>>` operator
- [x] SyntaxNormalizer
- [x] GetSymbolInfo
    - [x] Intrinsic operators
    - [x] User-defined operators
- [x] GetSpeculativeSymbolInfo
- [x] API review

### Parsing

- [x] Expressions
- [x] Disambiguation with nested generics
    - [x] Presense of tuple types at various levels
- [x] Operator declaration
    - [x] Regular declarations
    - [x] Explicit implementations

### Semantics

- [x] Operator is called
    - [x] Intrinsic operators
    - [x] User-defined operators
- [x] dynamic LHS or RHS
- [x] Lifted operators
    - [x] Intrinsic
    - [x] User-defined
- [x] Constants and constant folding
- [x] Disallowed in expression tree (`BuiltIn_Lifted_ExpressionTree_*`)
- [x] Results on hover in EE/debugger

## Productivity
- [x] F1 on `>>>` and `>>>=` - tests are in place, need to add actual doc pages
- [x] Declaring `>>>` operator
- [x] Using operator in expressions
- [x] QuickInfo should show used operator
    - [x] User-defined operators
    - [x] Intrinsic operators
- [x] `>>>` token classification
- [x] Syntax normalizer for declarations
- [x] Go to definition from operator usage and explicit interface implementation
- [x] Find all references for operators
- [x] Go To Implementation
- [x] Operator completion for explicit implementation
- [x] Operator completion when available (in expressions on types with the operator)
    - [x] Intrinsic operators
    - [x] User-defined operators
- [x] Implement interface fixer
- [x] Formatter tests
    - [x] Signature formatting
    - [x] Indentation inside operator
- [x] Navbar
- [x] Object Browser
- [x] Metadata as source
- [x] Call hierarchy window
- [x] Code lens

**Comment by jasonmalinowski** [comment]
Code Lens and Call Hierarchy behave like any other operator; not worth adding explicit tests in those cases.

**Comment by jasonmalinowski** [comment]
And the discussed fix for how we handle the parse ambiguity: https://github.com/dotnet/roslyn/pull/60789

**Comment by jasonmalinowski** [comment]
@333fred IDE looks good, I don't see any remaining work here.
