### ISSUE TITLE
[LSP] All requests for opened source generated documents fail

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60434]
For source generated documents that are open in the IDE, the LSP client sends requests to the server with the temp file path.  However source generated documents are special and are not standard documents that we can look up in the solution by file path, so [this code](https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol/Extensions/Extensions.cs,50) fails to find them.

We need to modify the document lookup and document tracking for source generated files so that we can find them when asked by the client.  Some notes
1.  We can get the source generated document id from the temp file path using this API (https://github.com/dotnet/roslyn/blob/373411ac6edfa011af9d8b69e925d783949c7e0d/src/VisualStudio/Core/Def/Workspace/SourceGeneratedFileManager.cs#L154) abstracted out into an interface we can get in LSP.
2.  Workspace changes can cause source generated documents to be re-created, but the text buffer the LSP client has may not be up to date.  Normally this is handled by forking in LSP by retrieving the workspace doc and applying the LSP text on top (`document.WithText`).  However this API throws for source generated documents.  
    1.  Instead what we need to do is freeze the source generated document with the contents from LSP.  
    2.  The freezing must be done **on each request** as the freezing API (in its current form) expects to only be called for a source generated document _once_.  We cannot incrementally update the source generated documents in that frozen solution (normally we incrementally update LSP docs).  Therefore we must re-freeze every request by calling this API - https://github.com/dotnet/roslyn/blob/373411ac6edfa011af9d8b69e925d783949c7e0d/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs#L1751 whenever we get a request to lookup a source generated document.  

### Longer term
1.  We should consider updating the freezing API to allow incremental updates to the frozen solution so we can treat source generated documents the same as regular documents in LSP - incrementally update them in response to didChange requests.  Also requires 2).
2.  We also need to make the API allow updating multiple source generated files in the same frozen snapshot.  Currently it only supports freezing a single source generated file.  This means if we have multiple source generated files open, the snapshot would only be frozen for the requested source generated file.  If something caused the contents of the second source generated file to change in the workspace but not on the client, we may produce invalid spans.
    1.  Note this limitation exists already non-LSP VS in `GetOpenDocumentInCurrentContextWithChanges`.

We will have to be careful in scenarios where the source generated document moves workspaces (e.g. to misc), but this can happen to regular documents as well and _should_ be handled by the LspWorkspaceManager when it listens to workspace events
https://github.com/dotnet/roslyn/blob/373411ac6edfa011af9d8b69e925d783949c7e0d/src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs#L136

Additionally we will need to ensure that LSP virtual docs can handle these cases.  For example navigation responses should support sending back document versions for source generated URIs so that the client can ask the server for updated contents when it tries to navigate (if it doesn't have that version) - cc @NTaylorMullen 

cc @jasonmalinowski

**Comment by jasonmalinowski** [comment]
> The freezing must be done on each request as the freezing API expects to be called only once ever.

One small comment here: the limitations of the freezing API was largely motivated by the current existing need for it in GetOpenDocumentInCurrentContextWithChanges; there we didn't have a need some fancier stuff, so I made the APIs throw to catch mistakes/other problems. But there's no conceptual limitations why the APIs can't be updated, and in some cases it might be as easy as removing a check somewhere.

**Comment by dibarbet** [comment]
this is done, we now support sg docs via LSP
