### ISSUE TITLE
API Review Followup - Analyzers/Suppression

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6044]
These are the remaining items from our 1.1 API review:

- CompilationWithAnalyzerOptions should be sealed
- CompilationWithAnalyzerOptions.AnalyzerOptions should be renamed Options
- SuppressionInfo should be sealed
- AnalyzerTelemetry API changes as per [this](https://github.com/dotnet/roslyn/issues/5974#issuecomment-149987997) comment.

**Comment by mavasani** [comment]
I am going to split this into 2 items - I'll move the MSBuildProjectLoader related changes to a separate issue and assign it to @mattwar

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/commit/e1009fdece0f3a5c353a9e1eaed7a0c34a3dace7
