### ISSUE TITLE
Disable IDE0004 (Remove unnecessary cast) for explicit cast of 0 to enum type

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#60457]
According to the C# language specification, the literal value `0` is implicitly convertible to any enum type. Sometimes, code includes an explicit cast to the enum type in cases where the enum does not define a zero value and `default(TEnum)` is deemed less clear. The IDE0004 analyzer (correctly) marks this cast as unnecessary, but removing the cast seems to impair readability. I propose modifying the IDE0004 analysis as follows:

1. If the enum type defines a zero value, report the IDE0004 as it currently does, but modify the code fix to replace `(TEnum)0` with `TEnum.None` (or whatever the zero value name is).
2. If the enum type _does not_ define a zero value, silently suppress IDE0004.

**Comment by Youssef1313** [comment]
> * If the enum type defines a zero value, report the IDE0004 as it currently does, but modify the code fix to replace `(TEnum)0` with `TEnum.None` (or whatever the zero value name is).

@sharwell Worth doing this for any value (zero and non-zero) as part of another analyzer?

**Comment by CyrusNajmabadi** [comment]
It's an interesting case.  Afaict, we have no other cases of keeping a cast for readability purposes.  We also haven't heard this so far...

i do like your '1' suggestion of converting to just use the Zero member.  I'm wary about your '2' case.  Do you have a code example that demonstrates this issue?

(also, i worry that we might do this and get people saying that they were surprised we don't offer to remove this unnecessary cast).

**Comment by sharwell** [comment]
> I'm wary about your '2' case. Do you have a code example that demonstrates this issue?

https://github.com/microsoft/perfview/blob/7614732957fa5dfc073f140b3c8bae417718b132/src/MemoryGraph/graph.cs#L610

The code fix wants to apply this change:

```patch
-m_reader.Goto((StreamLabel)0);
+m_reader.Goto(0);
```

**Comment by CyrusNajmabadi** [comment]
So i'm not sure why that would be different from, say, this sort of scenario:

`m_printer.Print((string)null)`

That said, i do think the "use existing named value vs casted integer" is very sensible.  So i'd be cool with just doing that, and leaving '2' alone for now as something to hold off on.

**Comment by sharwell** [comment]
@CyrusNajmabadi This issue primarily tracks (2) from my original list. The other item was only included for completeness.

**Comment by jinujoseph** [comment]
In design review to discussion if we need to make this exception

**Comment by allisonchou** [comment]
Design meeting notes (4/4/2022):
- May consider adding this if there are repeated customer asks
- We'll file a separate issue for code refactoring to use enum string name instead of integer
