### ISSUE TITLE
Get rid of CS1674

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#6045]
The following code is potentially a memory leak:

    public class Shape {
        public void Move(object to) {
            var mover = GetMover();
            mover?.Move(to);
        }
        public virtual IMover GetMover() {
            return new ManagedMover();
        }
    }
    public interface IMover {
        void Move(object to);
    }
    public class ManagedMover : IMover {
        public void Move(object to) {}
    }

While `ManagedMover` doesn't implement `IDisposable` and obviously doesn't hold on to any unmanaged resources, `Shape` could be subclassed and a different implementation of IMover could be `IDisposable`.

To fix this you currently need to cast mover as `IDisposable` and dispose it: 

    public void Move(object to) {
        var mover = GetMover();
        using (mover as IDisposable) {
            mover?.Move(to);
        }
    }

(or similar code with a try/finally block)

If CS1674 didn't exist, you could simply do this:

    public void Move(object to) {
        using (var mover = GetMover()) {
            mover?.Move(to);
        }
    }

**Comment by alrz** [comment]
#357 solves this.

**Comment by bbarry** [comment]
This has nothing to do with variance.

It is a usability issue faced by library writers when using interfaces and unsealed types in extensible ways.

Perhaps my example was a little too abstract. Consider a real world example of where this occurs: `IEnumerable.GetEnumerator()`

Suppose you were writing an extension method for `IEnumerable` (not the generic one) and manually enumerated over it:

    public static IEnumerable<TResult> Cast<TResult>(this IEnumerable source)
    {
        IEnumerable<TResult> typedSource = source as IEnumerable<TResult>;
        if (typedSource != null) return typedSource;
        if (source == null) throw Error.ArgumentNull("source");
        return CastIterator<TResult>(source);
    }

    private static IEnumerable<TResult> CastIterator<TResult>(IEnumerable source)
    {
        IEnumerator e = source.GetEnumerator();
        while (e.MoveNext())
        {
            yield return (TResult)e.Current;
        }
    }

Aside from skipping out on the CLR benefits a `foreach` loop and a bunch of inlining can take care of this code fails to dispose of the `IEnumerator` instance. But wait you might say, "`IEnumerator` doesn't implement `IDisposable`!" And you would be correct. Except that doesn't stop an implementation from doing so. Indeed there are classes out there that implement both `IEnumerator` and `IDisposable` within the .NET framework itself. [Some](http://referencesource.microsoft.com/#System.Management/managementobjectcollection.cs,414) [of](http://referencesource.microsoft.com/#System.Messaging/System/Messaging/MessageEnumerator.cs,25) [them](http://referencesource.microsoft.com/#System.Messaging/System/Messaging/MessageQueueEnumerator.cs,29) are even public.

If you happened to do this with message queues you would be leaking a handle every time you created such an enumerator ([in fact such a bug exists in the reference source](http://referencesource.microsoft.com/#System.Messaging/System/Messaging/MessageQueue.cs,1856); that is a separate issue though). That in its own wouldn't be too big of a deal (GC eventually would recover this handle). But [if you disable garbage collection](http://stackoverflow.com/a/6005949) you potentially run into real issues.

To fix it you need to call dispose:

    private static IEnumerable<TResult> CastIterator<TResult>(IEnumerable source)
    {
        IEnumerator e = source.GetEnumerator();
        while (e.MoveNext())
        {
            yield return (TResult)e.Current;
        }
        (e as IDisposable)?.Dispose();
    }

However dispose in this case still doesn't get called if there was an exception during enumeration. Instead you need this:

    private static IEnumerable<TResult> CastIterator<TResult>(IEnumerable source)
    {
        IEnumerator e = source.GetEnumerator();
        try
        {
            while (e.MoveNext())
            {
                yield return (TResult)e.Current;
            }
        }
        finally
        {
            (e as IDisposable)?.Dispose();
        }
    }

Which incidentally is exactly the pattern `using` provides:

    private static IEnumerable<TResult> CastIterator<TResult>(IEnumerable source)
    {
        IEnumerator e = source.GetEnumerator();
        using (e as IDisposable)
        {
            while (e.MoveNext())
            {
                yield return (TResult)e.Current;
            }
        }
    }

And this is as clean as we could make the method (again ignoring `foreach`). 

However if [this](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs#L69) check and [that](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/CSharp/Portable/Binder/UsingStatementBinder.cs#L100) check were removed, and [the rewriter](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_UsingStatement.cs#L207) were to handle the expansion:

    // SPEC: Otherwise, when Resource type is a nullable value type or
    // SPEC: a reference type other than dynamic that does not implicitly
    // SPEC: convert to IDisposable, the expansion is:
    // SPEC: 
    // SPEC: { 
    // SPEC:   ResourceType resource = expr; 
    // SPEC:   IDisposable d = expr as IDisposable
    // SPEC:   try { statement; } 
    // SPEC:   finally { if (d != null) d.Dispose(); }
    // SPEC: }

Then you wouldn't need to do the `obj as IDisposable` bit yourself.

[note this is not how that is actually implemented because a foreach loop optimizes better and handles the case of the enumerator being disposable](https://github.com/dotnet/corefx/blob/4774046623d7ad991003954a76d054664b97593f/src/System.Linq/src/System/Linq/Enumerable.cs#L1417)

**Comment by sharwell** [comment]
I currently strongly disagree with this proposal. In the original example, `IMover` does not implement `IDisposable`, and `GetMover` returns an `IMover` object. To me, this is prima facie evidence that a `using` statement is not needed as part of the use of `GetMover`. Since a `using` statement is not needed, CS1674 will not be reported and thus does not cause a problem.

**Comment by bbarry** [comment]
@sharwell `using` is not needed in the original example (which is here in the first code sample having extra code removed and identifiers renamed). The idea that someone might provide a class that implements both `IMover` and `IDisposable` wasn't on the radar of the author. 

The trouble happens that the original API shipped. Some time later the replacement author received a bug report because a user had subclassed the api and wrote a version that delegated out to COM. Something like this:

    public class ComShape : Shape {
        public overrides IMover GetMover() {
            return new ComMover();
        }
    }
    public class ComMover : IMover, IDisposable {
        public void Move(object to) {}
        public void Dispose() {}
    }

The new author that inherited this original codebase and that bug report (me), noted that the scenario the user reported was sensible and attempted to fix it with the using statement and hit CS1674 which makes sense because the interface does not inherit `IDisposable`. Unfortunately I cannot add that to the interface because it would break everyone else. So I fixed it with the `using (mover as IDisposable)` line and a comment in documentation that `IMover` could be `IDisposable`. So I figured this must have occurred elsewhere and I go looking for what other people have done. I learn that the .NET team faced almost exactly the same problem that I did with `IEnumerable` in the .NET framework 1.0. via @KrzysztofCwalina's [blog post](http://blogs.msdn.com/b/kcwalina/archive/2005/01/07/348876.aspx) where he states that the team chose to make `IEnumerator<T> : IDisposable` as well as a [stackoverflow post](http://stackoverflow.com/questions/4982396/does-foreach-automatically-call-dispose) which led me to msdn where it states that the `foreach` statement appears to take care of exactly the scenario that CS1674 explicitly does not. I decided to then file it away as one of those places where C# is just a little quirky.

Fast forward a few years and I start seeing requests to this repo about RAII and I am reminded of my issue and left thinking about how it could be done better. I've come up with 4 ideas:

1. This request. With what appears to be a pretty simple change to the compiler, that error message is unnecessary.
2. This request + a little bit. I think an expansion to LocalRewriter_UsingStatement.cs could be written to allow `using` to work on any type that defines `Dispose()`. This would match the way `foreach` actually works with any collection pattern (neither `IEnumerable` nor `IEnumerator` are actually necessary to use `foreach`). However, in `foreach`, the `IDisposable` interface is explicitly required on the result instance of the `GetEnumerator()` call for use of a disposable collection pattern. For that reason I am not entering that issue (it might have merit though; I lack the will to argue for it as option 1 is sufficient for me [in fact the pattern I am using is sufficient combined with option 3, but it would make my code look nicer]).
3. Create a set of annotation attributes and code analyzers around the idea of treating the `IDisposable` interface as the invasive species it appears to be. One would put an attribute `[CanBeDisposable]` on the `IMover` interface and get warnings where it is not sent to a using block or linked to disposal in a finally block. I haven't quite figured this out yet, so there isn't any Nuget for it at the moment or consideration of what it would take for an issue here.
4. Type system changes to .NET such that you can specify no subtypes are allowed to inherit from a particular type. Perhaps there could be a change to .NET such that how open a type is to subclassing. Here I begin questioning my sanity.

**Comment by sharwell** [comment]
> The trouble happens that the original API shipped. Some time later the replacement author received a bug report because a user had subclassed the api and wrote a version that delegated out to COM. ... Unfortunately I cannot add that to the interface because it would break everyone else. So I fixed it with the  using (mover as `IDisposable`)  line and a comment in documentation that `IMover` could be  `IDisposable`.

I see this as a particularly reasonable case where project requirements (here: compatibility) force you to write code which is more verbose than you would otherwise expect. Careful design generally avoids the need to do this, but as you noted sometimes it happens. The way you handled the situation is exactly the way I would expect the situation to be handled.

Nevertheless, cases like this do make resource management harder so a compiler change which hides them would make it easier for people to unknowingly/unintentionally make bad design decisions.
