### ISSUE TITLE
GenerateAssemblyInfo set to false disables EnablePreviewFeatures, then CA2252

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [dotnet/roslyn#60454]
When `GenerateAssemblyInfo` is set to false and `EnablePreviewFeatures` is set to true in the csproj, the compilation ignores `EnablePreviewFeatures` and ends with error CA2252.

**Version Used**: 

- Visual Studio 17.1.2
- C#   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f

**Steps to Reproduce**:

1. Create a .NET 6 library.
2. Create an interface in the project.
3. Add a function to the interface : `static abstract void A();`
4. Add `<EnablePreviewFeatures>True</EnablePreviewFeatures>` to the csproj.
5. Compile. That should be OK.
6. Add `<GenerateAssemblyInfo>False</GenerateAssemblyInfo>` to the csproj.
7. Compilation fails with error CA2252. 

Code:

        internal interface ITest
        {
	        static abstract void A();
        }

**Expected Behavior**:

No compilation error.

**Actual Behavior**:

Compilation fails with error CA2252.

**Comment by Youssef1313** [comment]
This should be moved to dotnet/roslyn-analyzers, I think.

FYI @buyaa-n @jeffhandley

**Comment by ChrisBertrandIndus** [comment]
> This should be moved to dotnet/roslyn-analyzers, I think.
> 
> FYI @buyaa-n @jeffhandley

Thank you.
I moved it to https://github.com/dotnet/roslyn-analyzers/issues/5939
