### ISSUE TITLE
[Flaky integration tests] IDE version '17.2.32314.265' unexpectedly dismissed the light bulb.

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#60461]
Example failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=1687571&view=results

Failures seen in:
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpUpdateProjectToAllowUnsafe.LegacyProject_AllConfigurationsUpdated
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpCodeActions.FastDoubleInvoke
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpCodeActions.ClassificationInPreviewPane
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpCodeActions.GFUFuzzyMatchAfterRenameTrackingAndAfterGenerateType
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpCodeActions.FixAllOccurrencesIgnoresGeneratedCode (this one can't be skipped since it's marked as a critical test)

Message:
> "IDE version '17.2.32314.265' unexpectedly dismissed the light bulb."

Runfo Tracking Issue: [[Roslyn] IDE version '17.2.32314.265' unexpectedly dismissed the light bulb.](https://runfo.azurewebsites.net/tracking/issue/312)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1689551](https://dev.azure.com/dnceng/public/_build/results?buildId=1689551)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60471](https://github.com/dotnet/roslyn/pull/60471)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1689147](https://dev.azure.com/dnceng/public/_build/results?buildId=1689147)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60466](https://github.com/dotnet/roslyn/pull/60466)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1688866](https://dev.azure.com/dnceng/public/_build/results?buildId=1688866)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60095](https://github.com/dotnet/roslyn/pull/60095)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1688605](https://dev.azure.com/dnceng/public/_build/results?buildId=1688605)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60462](https://github.com/dotnet/roslyn/pull/60462)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1688550](https://dev.azure.com/dnceng/public/_build/results?buildId=1688550)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60452](https://github.com/dotnet/roslyn/pull/60452)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1688428](https://dev.azure.com/dnceng/public/_build/results?buildId=1688428)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60431](https://github.com/dotnet/roslyn/pull/60431)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1688421](https://dev.azure.com/dnceng/public/_build/results?buildId=1688421)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60429](https://github.com/dotnet/roslyn/pull/60429)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1687963](https://dev.azure.com/dnceng/public/_build/results?buildId=1687963)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60338](https://github.com/dotnet/roslyn/pull/60338)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1687960](https://dev.azure.com/dnceng/public/_build/results?buildId=1687960)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60297](https://github.com/dotnet/roslyn/pull/60297)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1687585](https://dev.azure.com/dnceng/public/_build/results?buildId=1687585)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60452](https://github.com/dotnet/roslyn/pull/60452)|2-Integration Release OOP64_false OOPCoreClr_false|
|[1687571](https://dev.azure.com/dnceng/public/_build/results?buildId=1687571)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[1687482](https://dev.azure.com/dnceng/public/_build/results?buildId=1687482)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60450](https://github.com/dotnet/roslyn/pull/60450)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1687391](https://dev.azure.com/dnceng/public/_build/results?buildId=1687391)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60440](https://github.com/dotnet/roslyn/pull/60440)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[1687213](https://dev.azure.com/dnceng/public/_build/results?buildId=1687213)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60225](https://github.com/dotnet/roslyn/pull/60225)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1687213](https://dev.azure.com/dnceng/public/_build/results?buildId=1687213)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60225](https://github.com/dotnet/roslyn/pull/60225)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1687110](https://dev.azure.com/dnceng/public/_build/results?buildId=1687110)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1687036](https://dev.azure.com/dnceng/public/_build/results?buildId=1687036)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[1686839](https://dev.azure.com/dnceng/public/_build/results?buildId=1686839)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1686479](https://dev.azure.com/dnceng/public/_build/results?buildId=1686479)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60425](https://github.com/dotnet/roslyn/pull/60425)|2-Integration Release OOP64_false OOPCoreClr_false|
|[1686253](https://dev.azure.com/dnceng/public/_build/results?buildId=1686253)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60357](https://github.com/dotnet/roslyn/pull/60357)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1686228](https://dev.azure.com/dnceng/public/_build/results?buildId=1686228)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1684942](https://dev.azure.com/dnceng/public/_build/results?buildId=1684942)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60321](https://github.com/dotnet/roslyn/pull/60321)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1684938](https://dev.azure.com/dnceng/public/_build/results?buildId=1684938)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[1684897](https://dev.azure.com/dnceng/public/_build/results?buildId=1684897)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1684588](https://dev.azure.com/dnceng/public/_build/results?buildId=1684588)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[1684122](https://dev.azure.com/dnceng/public/_build/results?buildId=1684122)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60405](https://github.com/dotnet/roslyn/pull/60405)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1683963](https://dev.azure.com/dnceng/public/_build/results?buildId=1683963)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60405](https://github.com/dotnet/roslyn/pull/60405)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1683923](https://dev.azure.com/dnceng/public/_build/results?buildId=1683923)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60404](https://github.com/dotnet/roslyn/pull/60404)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[1683631](https://dev.azure.com/dnceng/public/_build/results?buildId=1683631)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|[PR 60401](https://github.com/dotnet/roslyn/pull/60401)|1-Integration Release OOP64_false OOPCoreClr_false|
|[1683147](https://dev.azure.com/dnceng/public/_build/results?buildId=1683147)|[roslyn-integration-CI](https://dnceng.visualstudio.com/public/_build?definitionId=245)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|5|29|29|

**Comment by sharwell** [comment]
This error occurs because the light bulb is still showing errors in the current CI version. When this happens, we need to let the editor team know that the light bulb is broken and update the workaround here:
https://github.com/dotnet/roslyn/blob/dcfd613ee1fc661bc764fc67d5f107ba0eb184f7/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/LightBulbHelper.cs#L91-L95

**Comment by JoeRobich** [comment]
This is failing in our nightly main branch run of integration tests - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5963150&view=results (microsoft)

**Comment by sharwell** [comment]
@JoeRobich That issue is tracked internally: AB#1511117
