### ISSUE TITLE
Add Ability to Embed netmodules

### ISSUE THREAD

**Issue by mwasplund** [dotnet/roslyn#60503]
## Background and Motivation
Compiling many small libraries can lead to large unwieldly runtime folders. Ideally a developer should have full control over how they organize their internal codebase into isolated units of code for code cleanliness and incremental build performance that does not require for internal structures to leak into the distribution package. Netmodules are a way to compartmentalizing individual units of compilation, however when linked into a reference assembly the netmodule itself is still a runtime dependency that must be distributed with the assembly that uses it. I propose that a new flag be added to the compiler to allow for the module reference to be embedded into the assembly. This will allow for the creation of a single self contained executable that can perform more aggressive IL trimming to limit binary size.

## Proposed API

I am proposing that we add a new compiler flag similar to /addmodule that embeds the netmodule IL within the assembly it is referenced from. 

/embedmodule:file list | Link the specified modules into this assembly and embed the runtime resources

## Usage Examples

``` 
csc /target:module /out:obj/Class.netmodule Class.cs
csc /target:exe /out:bin/Program.exe /embedmodule:obj/CLass.netmodule Program.cs
```

## Alternative Designs

It may be possible to accomplish this task with careful configurations for the MSVC Link.exe, but that seems roundabout and may not support all runtimes that dotnet targets and I was unable to get it to work with executables.

```
csc /target:module /out:obj/Class.netmodule Class.cs
csc /target:module /out:obj/Program.netmodule /addmodule:obj/CLass.netmodule Program.cs
link /dll /out:bin/Program.dll obj/Class.netmodule obj/Program.netmodule
```

## Risks

NA

**Comment by jcouv** [comment]
My sense is that linking assemblies together and trimming the result is best handled by tools outside the compiler.
Assigned to @jaredpar to advise and triage.

**Comment by jaredpar** [comment]
> My sense is that linking assemblies together and trimming the result is best handled by tools outside the compiler.

Historically that has been the case here. The preference has been to put the work into tools like ILMerge, ILLinker, etc ... vs. into the core compiler. There isn't any inherent reason it couldn't be in the compiler but overall we've favored putting these into external tools. 

In the case of net modules specifically though I don't really see a path forward here. They are not supported in .NET Core and at this point I don't see us making this type of investment in .NET Framework. The generally idea I'm partial to for DLLs but netmodules there really just isn't path forward for so going to close this out. 

If this is an area that interests you though for say DLLs I would encourage you to file an issue on dotnet/core to discuss how this could be approached in the overall ecosystem.

**Comment by mwasplund** [comment]
I did not realize that net modules was removed entirely. It seems to me that .net is missing a core concept of a static library vs the existing dynamic libraries. I will raise the issue over in dotnet/core. Thanks.
