### ISSUE TITLE
BANG BANG!!  Your compiler has died ...(asynchronously)

### ISSUE THREAD

**Issue by joshlang** [dotnet/roslyn#60520]
**Version Used**: 

<LangVersion>preview</LangVersion> (C# 11 preview)

Visual Studio 17.1.3

**Steps to Reproduce**:

Add this code to a default template C# class library using C# 11 preview
```
async void Blarg(object o!!)
{
}
```

Then compile.

**Expected Behavior**:

Compiles

**Actual Behavior**:

Dies.  With: `error MSB6006: "csc.exe" exited with code -2146232797.`

Note: Removing `async` lets compilation succeed.

**Comment by Youssef1313** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/58822 for Visual Studio 17.2

**Comment by RikkiGibson** [comment]
Thank you for reporting this issue. As was noted above we, have fixed the bug in 17.2.
