### ISSUE TITLE
Revise current experimental code-style options and promote them to be non-experimental

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60539]
- `dotnet_style_allow_multiple_blank_lines_experimental` (for IDE2000)
- `csharp_style_allow_embedded_statements_on_same_line_experimental` (for IDE2001)
- `csharp_style_allow_blank_lines_between_consecutive_braces_experimental` (for IDE2002)
- `dotnet_style_allow_statement_immediately_after_block_experimental` (for IDE2003)
- `csharp_style_allow_blank_line_after_colon_in_constructor_initializer_experimental` (for IDE2004)

There are increasing usages of these (see https://grep.app/search?q=%28dotnet_%7Ccsharp_%29.%2B%3F_experimental%20%3D&regexp=true&filter[lang][0]=EditorConfig)

Promoting them will require removing the `_experimental` suffix from them (and possibly change the ID since IDE2xxx was meant to be experimental?)

I think this is better to be done sooner than later to avoid breaking people in future.

**Comment by CyrusNajmabadi** [comment]
These are all still experimental. Nothing has changed with that :-)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi What's the process of making them non-experimental?

I mean when can they be switched to non-experimental? Note that these have been there for more than a year https://github.com/dotnet/roslyn/pull/50358

**Comment by CyrusNajmabadi** [comment]
Reimplement them to work just as part of standard formatting

**Comment by dibarbet** [comment]
Design review conclusion:

For the very short term we plan to leave this as experimental until the plans for the formatter have been decided.  A decision here should fall out from what we decide is the path forward for the formatter as these options in general fit into the formatting space.

cc @jmarolf - do we have an issue tracking the plan for the formatter?  This one should probably be referenced there so we can update it appropriately when we make the decision.

**Comment by joegoldman2** [comment]
The scope of this issue can probably be extended to:

- `csharp_style_allow_blank_line_after_token_in_conditional_expression_experimental`
- `csharp_style_allow_blank_line_after_token_in_arrow_expression_clause_experimental`

**Comment by CyrusNajmabadi** [comment]
Closing out.  There is no intent on making these non experimental.
