### ISSUE TITLE
Large amount of time spent in ExecuteAndCatchIfThrows

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#6053]
During my investigation of DotNetAnalyzers/StyleCopAnalyzers#1618, I ran the sampling profiler on **csc.exe** compiling **StyleCop.Analyzers.csproj** (the specific command was obtained by invoking MSBuild with diagnostic verbosity, and searching for csc.exe in the resulting log).

The resulting output showed `AnalyzerExecutor.ExecuteAndCatchIfThrows` as the primary time consumer. The most concerning part, however, is the top three calls when sorted by Inclusive Samples %:

| Method | Inclusive Samples % |
| --- | --- |
| JITutil_MonContention | 69.89 |
| JIT_MonEnterWorker_InlineGetThread_GetThread_PatchLabel | 13.89 |
| Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock | 12.08 |

Based on this report, it appears that StyleCop.Analyzers is consuming very little actual time in the overall compilation process.

:question: Is there anything we can do in our analyzers to improve the overall efficiency here?

:question: Are any changes implemented or planned for Roslyn itself which will help alleviate these problems for users?

![image](https://cloud.githubusercontent.com/assets/1408396/10532131/15d913aa-7380-11e5-949f-cc405123b778.png)

**Comment by mavasani** [comment]
I think the performance will improve by the following 2 work items:

1. https://github.com/dotnet/roslyn/issues/6399: Converting the lock statement guarding analyzer callbacks into an async disposable wait.
2. https://github.com/dotnet/roslyn/issues/1565: Enabling analyzers to explicitly opt-into concurrent callbacks. Currently we never make concurrent callbacks into an analyzer, and the above per-analyzer instance lock ensures that. However, if an analyzer is written in a thread-safe way (I presume most of style cop analyzers would be), they can explicitly state this in metadata and the analyzer driver can avoid any lock for such analyzers.

@srivatsn @JohnHamby We should discuss (2) at the next design meeting.

**Comment by sharwell** [comment]
> However, if an analyzer is written in a thread-safe way (I presume most of style cop analyzers would be), they can explicitly state this in metadata and the analyzer driver can avoid any lock for such analyzers.

If we had the ability to do this, all of them would quickly move in that direction.

**Comment by mavasani** [comment]
Yes, and the work on Roslyn side is pretty trivial - just look for this metadata and skip locking. I agree with @sharwell that we should do this part of #1565 ASAP.

**Comment by srivatsn** [comment]
Yes let's talk about it on Monday.

**Comment by mavasani** [comment]
@sharwell https://github.com/dotnet/roslyn-internal/commit/dab1c327febbc11ec16ceb1985a9cfc9f9eabea9 should enable you to completely avoid/control locking for your analyzer.
Can you please try the new API and confirm if it resolves the lock contention?

**Comment by mavasani** [comment]
Actually the correct commit that added the new API is https://github.com/dotnet/roslyn/commit/069d016819a823bca72251351fbd16e08c82482f
