### ISSUE TITLE
Some source generators stopped working with 6.0.200 SDK (file not found)

### ISSUE THREAD

**Issue by maxkatz6** [dotnet/roslyn#60532]
**Description**

It seems like source generators that use AdditionalFiles for other properties that are not files worked before in 6.0.1xx and don't work anymore in 6.0.2xx.
I doubt if it's really expected to pass something that is not a file to AdditionalFiles property.
But was it planned breaking change in minor update? What should be used instead, any workarounds?

Creating this issue here to confirm that it is expected behavior as for now.

**Version Used**: 

ThisAssembly.Constants version 1.0.9
.NET SDK version 6.0.200:
```
maxkatz6@mak-kat-mb thisassembly-test % dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    f13c273745

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Steps to Reproduce**:

1. Install 6.0.200 SDK from [dotnet/installer](https://github.com/dotnet/installer#table) repository
2. ```dotnet new console```
3. Reference ```<PackageReference Include="ThisAssembly.Constants" Version="1.0.9" />```
4. Add simple constant to be generated ```<Constant Include="Foo.Bar" Value="Baz" />```
5. ```dotnet build```

**Expected Behavior**

It works, constant are generated.

**Actual Behavior**
```
maxkatz6@mak-kat-mb thisassembly-test % dotnet build
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/maxkatz6/repos/thisassembly-test/thisassembly-test.csproj (in 290 ms).
CSC : error CS2001: Source file '/Users/maxkatz6/repos/thisassembly-test/Foo.Bar' could not be found. [/Users/maxkatz6/repos/thisassembly-test/thisassembly-test.csproj]

Build FAILED.

CSC : error CS2001: Source file '/Users/maxkatz6/repos/thisassembly-test/Foo.Bar' could not be found. [/Users/maxkatz6/repos/thisassembly-test/thisassembly-test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.79
```

**Additional Info**

Bin log:
[msbuild.binlog.zip](https://github.com/devlooped/ThisAssembly/files/8037434/msbuild.binlog.zip)

Issue in source generator repository https://github.com/devlooped/ThisAssembly/issues/85
CC @kzu

**Comment by chsienki** [comment]
We didn't intend to break this, although the additional files are definitely being used in an unexpected way: I'll add some detail on the linked issue how it should probably be handled.

The underlying issue was fixed with https://github.com/dotnet/roslyn/pull/59776. That was backported for VS 17.1 (https://github.com/dotnet/roslyn/pull/59786), but it looks like we didn't opt to take it for servicing in the SDK for 2xx.

As a workaround for now you should be able to use the previews of 6.0.3xx
