### ISSUE TITLE
Please allow to create class with dynamic size

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#6055]
C/C++ has this feature, why C# doesn't have?
for example:
class A
{
    int a;
    long b[]; /\* The memory of b is in the memory of instances of class A. b is not an independent object and can't be referenced directly, but accessing elements of b is allowed. The length of b is determined/specified when creating instances of class A. The default length of b is zero. */

```
public A(int a0)
{
    a=b.Length+a0;
}
```

}

A e1 = new[10] A(5); // the length of b is 10 in object e1
int x=7,y=8;
A e2 = new[x] A(y); // the length of b is 7 in object e2
A[] ee=new A[2];
ee[0]=new[4] A(0);
ee[1]=new[0] A(4);

**Comment by ygc369** [comment]
A class can only have at most one array with dynamic length, but can have more than one inline arrays with fixed length. 
for example:
class A
{
    int a[10]; // fixed size
    int b[20]; //fixex size
    object c[]; //dynamic size
}

**Comment by dsaf** [comment]
It would be nice to see the motivation and reasoning explaining why it would be a valuable feature. Is it about memory layout and performance or ease of use? Formatting of sample code is not done properly so it's hard to read.

> C/C++ has this feature, why C# doesn't have?

Why doesn't C++ have all the Haskell features?

**Comment by HaloFour** [comment]
Arrays are references in the CLR.  C# fakes fixed arrays by creating a struct of a fixed size and adding it as a field to the class.

**Comment by ygc369** [comment]
@dsaf 
It's about performance, reduce the total count of objects, make GC faster. (Arrays are objects too!)

**Comment by MI3Guy** [comment]
It would be especially nice for immutable collections. I think it would require CLR support however
.

**Comment by ygc369** [comment]
@MI3Guy 
What you said is just what I want to say.It's suitable for immutable collections.
I think that CLR may already support it.

**Comment by HaloFour** [comment]
@ygc369 To my knowledge the CLR does not support anything like this currently.  The CLR determines the size of the class based on its fields and allocates the memory for it before the constructor is executed.

**Comment by vladd** [comment]
I don't see how this solves the problem in general. If we are to allow "inlining" the _last_ array field, why shouldn't we allow "inlining" of all array fields? (Just because C++ can't do it?) The feature is too weak to be helpful.

**Comment by ygc369** [comment]
@vladd 
allowing "inlining" of all array fields would be better if possible.

**Comment by mikedn** [comment]
> C/C++ has this feature, why C# doesn't have?

C++ doesn't actually have this feature. It just happens that it usually works but as far as the language specification is concerned any attempts at using such tricks puts you in the "undefined behavior" land. In particular, C++ doesn't have any built-in way to instantiate such types. The closest you can get is to allocate the required amount of memory and then use placement new to initialize the instance.

> A class can only have at most one array with dynamic length, but can have more than one inline arrays with fixed length.

Dynamic size and inline arrays are rather different features and they should be discussed separately. Inline arrays can, to an extent, be simulated by the C# compiler. Dynamic size requires runtime support if you want to achieve the stated goal of reducing the number of allocated objects.

> It's about performance, reduce the total count of objects, make GC faster.

While the number of objects and references does have an impact on GC efficiency the amount of allocated memory is likely to have a greater impact. Not to say that this feature couldn't help GC but without some tangible examples "make GC faster" is kind of speculative.

> It's suitable for immutable collections

How? The way ImmutableList (for example) is currently implemented has nothing to do with this feature. Are you perhaps considering alternative implementations, possibly based on B-trees?

**Comment by gafter** [comment]
@ygc369 The possible benefits to a (very) few users of this feature would have to be weighed against the cost to all users of the platform in the runtime overhead of a more complex CLR and complexity in garbage collection.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
