### ISSUE TITLE
cut and paste should be greyed out when previous submissions or outputs are selected.

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6056]
currently paste does noting and cut behaves like copy.

**Comment by amcasey** [comment]
I think cut's behavior is expected - it's what I would expect anyway.  I'll compare paste to (e.g.) metadata-as-source.

**Comment by amcasey** [comment]
Confirmed that paste matches metadata as source.  Please reactivate if you feel strongly.
