### ISSUE TITLE
Add Tools Options Telemetry 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#60569]
We should add telemetry for all of Roslyn's/Razor's settings in Tools Options so we can track which options we can start enabling by default or delete. 

Our telemetry system is primarily a set of 'events' that record what the user has done. We would like to more deeply design a system that captures general options/preferences/language features users use. 

How often should these be reported? 
- When VS starts? 
- When the Sln is open? 
- When the Project is open?

**Comment by ryzngard** [comment]
@mikadumont putting this into 17.4. I think that would be a good time to check into P1 and evaluate how useful this telemetry is

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this needs to be done, it needs to eb assigned to a person/milestone for that work to happen in.
