### ISSUE TITLE
Crash when params array used with reordered attribute arguments

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60572]
The break was probably introduced by dotnet/roslyn#59750. I'll take a look.

_Originally posted by @RikkiGibson in https://github.com/dotnet/runtime/issues/67440#issuecomment-1088054591_

Scenario:

```cs
using System;

class Attr : Attribute
{
    public Attr(bool b, int i, params object?[] parameters) { }
}

[Attr(i: 1, b: true)]
class Program { }
```

**Comment by Youssef1313** [comment]
@jcouv @RikkiGibson Can you close this?

**Comment by jcouv** [comment]
Done. Thanks
