### ISSUE TITLE
Ensure Top level statements appear in the entry point list

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#60570]
**Version Used**: 17.3.0 Preview 1.0 [32403.30.main]

**Steps to Reproduce**:

1. Create a new .NET 6 Console App
2. Open the Project Properties Page
3. Navigate to the Application->General->Startup Object section

**Expected Behavior**:
`global::Program.<Main>$(string[] args)` should be recognized as an entry point.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/9797472/161638241-5f956b7f-9f5a-4665-836f-f2daa87952a2.png">

**Actual Behavior**:

No entry points shown:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/9797472/161637376-1a2d0d3f-ba57-4863-bffd-2b30819c204f.png">

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback on this.
