### ISSUE TITLE
[Flaky Build] "Out of memory" and "Task was cancelled" while attempting to restore Roslyn's solution

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6057]
__Symptom:__

You run:
```
nuget restore Roslyn.sln
```

and get output like the following:

```
A task was canceled.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.6 (win7-anycpu).
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
Out of memory.
```

__Resolution:__ 
This is being tracked by this [bug](https://github.com/NuGet/Home/issues/1586) over on NuGet.org. 

To avoid, run:
```
nuget restore Roslyn.sln -DisableParallelProcessing
```

**Comment by tannergooding** [comment]
Closing as issue already has a resolution.

**Comment by davkean** [comment]
This is still an issue until we upgrade NuGet, let's leave it open so that it's still linked from https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging.

**Comment by diryboy** [comment]
Yes, yes, nuget need upgrade, whenever packages are updated, the restore gave me a lot of `task was cancelled` errors, and `-DisableParallelProcessing` makes the process very slow and still get `task was cancelled` errors.

![image](https://cloud.githubusercontent.com/assets/159110/10690910/a89100ee-79b7-11e5-814b-9c0bf0e7849c.png)

**Comment by davkean** [comment]
Yep, we're going to upgrade soon: https://github.com/dotnet/roslyn/issues/6170.

**Comment by davkean** [comment]
This should now be fixed in https://github.com/dotnet/roslyn/pull/6864 by @agocke.
