### ISSUE TITLE
UTF8 string IDE follow up items

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#60582]
Relates to https://github.com/dotnet/roslyn/issues/58848
Proposal - https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md

Existing features:
 - [x] ~String split command handler~ (done in https://github.com/dotnet/roslyn/pull/60599)
 - [x] ~Brace matching for double quotes~ (done in https://github.com/dotnet/roslyn/pull/60599)
 - [x] ~Structure navigation~ (done in https://github.com/dotnet/roslyn/pull/60599)
 - [x] ~Pressing F1 on the `u8` suffix?~ (done in https://github.com/dotnet/roslyn/pull/60599)

New potential features:
 - [x] ~Code style option to prefer `"abc"u8" instead of `new byte[] { 1, 2, 3}`~ - https://github.com/dotnet/roslyn/pull/60647
 - [ ] (The same) code style option to prefer `"abc"u8" instead of `Encoding.UTF8.GetBytes("literal")
 - [ ] ~Code style option to prefer explicit `u8` suffix for `ROS<byte> x = "ABC"`~ No longer applicable

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
