### ISSUE TITLE
Proposal: Remove unneeded code-style options, or not include more of them

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60584]
### Overview

Code-style options are to serve the following main purposes:

- Control how certain code generation features behave.
- Changes how analyzers/codefixes behave per user preference.

Today, some code-style options exist that only enables/disables certain analyzers. This is already achievable by the `dotnet_diagnostic.IDExxxx.severity = none` setting.

From earlier discussion with @CyrusNajmabadi, those options are needed for showing a Visual Studio setting for these code-styles. However, that comes with noise for `.editorconfig` files.

### Is it really necessary?

I *think* the fact that we need a code-style option for showing VS setting doesn't mean we really need an editorconfig storage location for this particular code-style option. We can create a roaming-only storage location for such option to show it up in VS and be able to persist it

### Proposal

Two directions can be taken:

- Take a breaking change and remove the unnecessary code-style options (should be done in a major version). We should offer an easy way for developers to get rid of those `csharp_style_that_is_deleted` and replace them with the corresponding `dotnet_diagnostic.IDExxxx.severity`
- Keep the existing code-style options. For new analyzers, follow a new pattern that creates roaming-only storage location options.

cc @mikadumont @mavasani @CyrusNajmabadi @sharwell @jmarolf

**Comment by CyrusNajmabadi** [comment]
I don't like either of those choices :-)

> and replace them with the corresponding dotnet_diagnostic.IDExxxx.severity

These seem cryptic and painful to use. I can't look at an editorconfig and have any idea what that does. 

The benefit of named options is readability and self-documentation. Editorconfig is not a tool-only artifact (like VS' xml options file). It's something intended for humans to edit and understand as text.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Users have to deal with IDExxxx syntax anyway for enabling rules in command-line builds.

**Comment by Youssef1313** [comment]
Some notes:

- Some analyzers don't have an option associated with them currently (denoted by `No editorconfig based code style option` [here](https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Test/Diagnostics/IDEDiagnosticIDConfigurationTests.cs).

- If we look at CAxxxx, there is no way to enable/disable them with readable `.editorconfig` options, and I think there was no complains about that.

- The IDE feature that changes severity in .editorconfig already adds a "readable" comment, e.g:

    https://github.com/dotnet/roslyn/blob/74912d41ede5fbe4517db9459a4ccc680dbc66d0/.editorconfig#L41-L42

**Comment by Bosch-Eli-Black** [comment]
@Youssef1313 We currently have some rules like this in our `.editorconfig` file:

```ini
[*.cs]
dotnet_sort_system_directives_first = true

# IDE0037: Use inferred member name
dotnet_style_prefer_inferred_anonymous_type_member_names = false:suggestion

# IDE0063: Use simple 'using' statement
csharp_prefer_simple_using_statement = true:none
```

We put these rules in `.editorconfig` because we want these rules to be applied to everyone on the team. If these are moved to roaming storage, is these still a way to automatically share these settings between team members via Git?

**Comment by Youssef1313** [comment]
This issue doesn't apply to `dotnet_sort_system_directives_first`.

It applies to the two others you mentioned, and what you'll need to do (in case the breaking change is accepted) is `dotnet_diagnostic.IDE0037.severity = suggestion` and `dotnet_diagnostic.IDE0063.severity = none`.

**Comment by Bosch-Eli-Black** [comment]
Oh, okay, cool, thanks 🙂

**Comment by sharwell** [comment]
I also find it frustrating to have so many seemingly-duplicate options. In the past, the consensus has been to keep following the existing approach until we have a _proven viable alternative_ which addresses future options, developer clarity, and backwards compatibility.

**Comment by PathogenDavid** [comment]
I'm in agreement with Cyrus that the IDExxxx options are cryptic.

In my opinion it'd be more valuable if command line builds were able to understand the human-friendly code style options. To me, the individual analyzer rules that enforce these options should really just be an implementation detail.

**Comment by Youssef1313** [comment]
@PathogenDavid I think compiler support for these options was discussed at some point, but I can't recall what and why the conclusion was.

Speaking of the current state for analyzers and their options, the cryptic IDExxxx codes are necessary (currently). So I still don't see how the proposal affects this or how it makes .editorconfig files less readable.

**Comment by PathogenDavid** [comment]
> I think compiler support for these options was discussed at some point, but I can't recall what and why the conclusion was.

I recall that as well but I couldn't find it when I checked earlier.

> the cryptic IDExxxx codes are necessary (currently).

Only if you want code style enforced at build. I've seen plenty of editorconfigs which configure many friendly options but no IDExxxx analyzers.

**Comment by mavasani** [comment]
I believe we should wait for consensus on #52991 before moving ahead with this accepting/rejecting/modifying this proposal

1. If #52991 gets implemented, command line builds will support decoding `:severity` syntax for code style option entries, and we don't need to do anything here.
2. If #52991 gets rejected or we are unable to find a feasible and acceptable design/implementation for it, we can revisit this proposal.

**Comment by jasonmalinowski** [comment]
The general consensus during the design meeting yesterday was:

1. IDExxxx codes are difficult to decipher, so they really aren't user friendly. A good example was trying to have intellisense for formatting options in an .editorconfig: they're not something you can easily filter a list down on. Something looking for formatting options for 'var' could type 'var' and see what there is, and you can't do the same with IDE codes.
2. We should probably drive #52991 further to see if that's really the way we want to go.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, it should be assigned to a person/milestone to be done in.
