### ISSUE TITLE
Breaking change in overload resolution around string literals

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#60612]
Using `Microsoft.Net.Compilers.Toolset` `v4.3.0-1.22206.2` or later, attempt to compile:
```csharp
class C
{
    static void M(ReadOnlySpan<char> x, ReadOnlySpan<byte> y) { }

    static void M(ReadOnlySpan<char> x, ReadOnlySpan<char> y) { }

    static void T() => M("test", "string");
}
```

### Expected behavior:

Everything succeeds and the `M(ROSpan<char>, ROSpan<char>)` overload is called

### Actual behavior:

`CS0121: The call is ambiguous between the following methods or properties: 'C.M(ReadOnlySpan<char>, ReadOnlySpan<byte>)' and 'C.M(ReadOnlySpan<char>, ReadOnlySpan<char>)'`

This is a breaking change and impacts `System.Security.Cryptography.RSAWrapper.ImportFromEncryptedPem`: https://github.com/dotnet/runtime/pull/67440#discussion_r844476607

**Comment by tannergooding** [comment]
CC. @AlekseyTs, @cston, @RikkiGibson (as per https://github.com/dotnet/roslyn/blob/main/docs/Language%20Feature%20Status.md)

**Comment by AlekseyTs** [comment]
CC @stephentoub 
I think this is an expected breaking change. See https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#utf8-string-literal-conversion

I am not sure why I didn't discover the break several weeks ago when I tried to build runtime repo with the new compiler. 

This is a preview feature. If we find that the break is too painful to deal with, we will adjust the design. Some of the options are:
- Add some new tie-breaking rules to overload resolution
- Remove the new conversions and go with just `U8` literal suffix.

**Comment by stephentoub** [comment]
Frankly, I'm surprised it's not a bigger break in runtime. My stated preference has been and continues to be that `"..."` is chars and `"..."u8` is bytes, that if you want UTF8 / bytes, you need to be explicit with the `u8` suffix.  My primary motivation for that preference has been to ensure the encoding is clear in the code, since there are any number of ways text can be encoded into bytes.  But it also helps to avoid these ambiguities (and breaking changes). If we don't do that, I think we should add a tie-breaking rule to overload resolution that makes `"..."` more closely associated with chars, so that things continue to behave the way they have.

**Comment by davidwengier** [comment]
Whilst I don't write the sort of code that makes me a consumer of UTF8 strings day-to-day, in doing the IDE work I must admit the implicit conversion seems odd to me and the `u8` suffix is much nicer. I find that thinking of UTF8 string literals as being byte arrays in disguise makes more sense to me than as a special type of string syntax, so having a "normal" string literal also be a byte array in disguise is jarring.

I could definitely see us needing a code style preference to always include the suffix, for clarity.

> `"..."` is chars and `"..."u8` is bytes, that if you want UTF8 / bytes, you need to be explicit with the u8 suffix.

I agree.

**Comment by stephentoub** [comment]
> Frankly, I'm surprised it's not a bigger break in runtime. My stated preference has been and continues to be that "..." is chars and "..."u8 is bytes, that if you want UTF8 / bytes, you need to be explicit with the u8 suffix. My primary motivation for that preference has been to ensure the encoding is clear in the code, since there are any number of ways text can be encoded into bytes. But it also helps to avoid these ambiguities (and breaking changes). If we don't do that, I think we should add a tie-breaking rule to overload resolution that makes "..." more closely associated with chars, so that things continue to behave the way they have.

I will say, however, having gone through dotnet/runtime looking for places using `u8` makes sense, I will add that there are two cases I've seen where being able to treat a string constant as convertible to a `ReadOnlySpan<byte>` or `byte[]` is welcome:
1. Defining a single constant for use as both UTF16 and UTF8.  There are a bunch of types that support processing both char-based (UTF16) and byte-based (UTF8) data, and in these situations it's not uncommon to have some constant data that's used in the processing.  With a `const string` being convertible to a `byte[]` or `ReadOnlySpan<byte>`, you can declare the constant once and then use it for both; without that ability, you end up either needing to write out the string twice (once where it's used for char and once where it's used for byte), or you end up declaring it once for string and paying the runtime overheads of converting that to UTF8.
2. `nameof`. There are a handful of places where the name of something is what's being encoded, and without the conversion support, there's no good way to do this at compile time.

Even with that, I still think we should remove the implicit conversion, but we should also think about whether there's an explicit gesture that could bring it back.

**Comment by AlekseyTs** [comment]
Should be fixed in https://github.com/dotnet/roslyn/pull/61481.
