### ISSUE TITLE
Double bang shows unexpected error when added to last argument of constructor

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#60615]
Version: The latest consumed in dotnet/runtime as of today https://github.com/dotnet/runtime/blob/afb1c64a8dd8933d7b4aab99ab0eade72d6e2dab/eng/Versions.props#L43-L53

```xml
    <!-- Code analysis dependencies -->
    <MicrosoftCodeAnalysisAnalyzersVersion>3.3.3</MicrosoftCodeAnalysisAnalyzersVersion>
    <MicrosoftCodeAnalysisCSharpCodeStyleVersion>4.2.0-2.final</MicrosoftCodeAnalysisCSharpCodeStyleVersion>
    <MicrosoftCodeAnalysisCSharpWorkspacesVersion>4.2.0-2.final</MicrosoftCodeAnalysisCSharpWorkspacesVersion>
    <MicrosoftCodeAnalysisCSharpVersion>4.2.0-2.final</MicrosoftCodeAnalysisCSharpVersion>
    <MicrosoftCodeAnalysisNetAnalyzersVersion>7.0.0-preview1.22180.6</MicrosoftCodeAnalysisNetAnalyzersVersion>
    <MicrosoftCodeAnalysisVersion>4.2.0-2.final</MicrosoftCodeAnalysisVersion>
    <!--
      TODO: Remove pinned compiler version once arcade supplies runtime with a compiler capable of handling !!
      and has https://github.com/dotnet/roslyn/pull/59776
    -->
    <MicrosoftNetCompilersToolsetVersion>4.2.0-2.final</MicrosoftNetCompilersToolsetVersion>
```

Take this code:
```cs
    public class MyClass
    {
        public MyClass(int x, string text !!)
        {
        }
    }
```

When the `!!` operator is added to the last argument of a constructor, and it has a space added in between the argument name and the operator, the suggestion `IDE0055: Fix formatting` shows up:

<img src="https://user-images.githubusercontent.com/1175054/162098024-45ef9971-1582-48a8-b64a-9ceb104db8e1.png" width="500" />

But once the suggestion is applied, it becomes an error - `CS1003: Syntax error, ',' expected`:

<img src="https://user-images.githubusercontent.com/1175054/162098159-821a6c34-e47c-4dbc-9c2f-63f839a38450.png" width="500" />

Interestingly, this behavior is different when it happens to a method. If I add a space, I get `CS1003: Syntax error, ',' expected`:

<img src="https://user-images.githubusercontent.com/1175054/162098633-e805539e-3f0c-45c2-a854-a219d62c158d.png" width="550" />

And if I remove the space, it works:

<img src="https://user-images.githubusercontent.com/1175054/162098738-40f7ad19-cfb0-4f6f-86cd-1586a740efed.png" width="400" />

**Comment by Youssef1313** [comment]
This is an incremental parsing issue which was fixed in https://github.com/dotnet/roslyn/pull/59977. Note that even with the space, you should find command-line builds succeed.

**Comment by jcouv** [comment]
Thanks @Youssef1313. Closing as dupe
