### ISSUE TITLE
Suggest lambda when calling method accepting callback

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60629]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggest-lambda-when-calling-method-accep/10001926)._

---
VisualStudio doesn't suggest lambda during autocompletion.

```
class P
{

    delegate void F(int x, int y);

    void Q(F f){}

    void W()
    {
        Q( // <-- Here VS should suggest lambda / delegate.
        // Q((x, y) => ..
        // Q(delegate(int x, int y) { .. })
    }
```

---
#### Feedback Bot on 4/1/2022, 02:53 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
