### ISSUE TITLE
Stack Trace Explorer doesn't map async methods in stacks to code

### ISSUE THREAD

**Issue by vritant24** [dotnet/roslyn#60624]
**Version Used**: 
Visual Studio Version 17.3.0 Preview 1.0 [32404.36.main]

**Steps to Reproduce**:
1. copy a stack trace with an async method in it, where a line would be of the form:
`at <namespace>.<class>.<>c__DisplayClass3_0.<<method>b__0>d.MoveNext()` 
2. open the stack trace viewer.

Currently `method` in the format listed above cannot be linked to code, but if it was `<namespace>.<class>.<method>` it could. From the few stack traces I've copied, there seems to be a pattern of async methods in stacks listed as 
`<c__DisplayClass(suffix).<<method>b__(suffix)>d.MoveNext()`. Could this pattern could be used to discard the extraneous text and construct `<namespace>.<class>.<method>` to map it to code?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
