### ISSUE TITLE
Visual Studio help me use Azure App Configuration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-help-me-use-Azure-App-Conf/10005246)._

---
Visual Studio already recognizes methods from common libraries and will help me install the necessary NuGet packages.

Would like to see Visual Studio help me install the packages I need for Azure App Configuration
![image.png](https://aka.ms/dc/image?name=B9d670c4c39b54e26b987cd8183e2f584637847699015040071_20220405-103821-image.png&tid=9d670c4c39b54e26b987cd8183e2f584637847699015040071)

---
#### Feedback Bot on 4/6/2022, 07:49 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing.  This is potentially something copilot can help with.  Not roslyn
