### ISSUE TITLE
Highlight exit points (C#, C++)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60634]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Highlight-exit-points-C-C/1704796)._

---
Visual Studio should have an ability to highlight all possible exit points when caret is pointing on exit statement.
For example given code:

```cpp
void f(int a)
{
 if (a > 0) return;

switch (a) {
  case 1:
    g(a);
    break;
  case 2:
    h(a);
    break;
  case 3:
    i(a);
    break;
 }
}
```

Putting caret on break or return highlights other statements that directly leave the function.

---
#### Feedback Bot on 3/29/2022, 07:39 AM: 

(private comment, text removed)

**Comment by sharwell** [comment]
This already does work if you place the caret on `return`, but I agree it would be nice if it also worked when placing the caret on the method's return type. Some other IDEs do this and I've found it helpful.

**Comment by ozdotnet** [comment]
Look's like this is on-hold for a long time. Any feedback when this can be implemented? Or is this a one more reason to buy Resharper?

**Comment by CyrusNajmabadi** [comment]
> Any feedback when this can be implemented?

This could be implemented at any time. We'd def welcome a PR from you @ozdotnet if you were interested. Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this and no community movement.
