### ISSUE TITLE
link back to code line from Developer PoweShell

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60630]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/link-back-to-code-line-from-Developer-Po/1699260)._

---
If I have an error running the code from the Terminal (PowerShell) there is no link back to the code editor.

```
dotnet run
...
\path\to\filename.cs(374,5): error description ...
```

In Visual Studio Code you can CTRL+click on the path and the editor brings you directly to the file, line (374) and char (5).

Moving from the free VS Code to a licensed VS 2022 this is a downgrade!

Please, consider to implement this feature in VS too!

---
#### Feedback Bot on 3/23/2022, 07:04 AM: 

(private comment, text removed)

**Comment by jinujoseph** [comment]
i have reopened the DC issue to right team.
