### ISSUE TITLE
Refactoring to aid Exception Data Population

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-to-aid-Exception-Data-Popula/1696650)._

---
It would be great to have a refactoring for a method or block that:

1: splits all declarations and initializations and moves the declarations to the top of the method or block.
2: wraps the code after the declarations in a `try{}` `catch(Exception ex) {}` block.
3: populates the catch block with:
```cs
catch(Exception ex)
{
    ex. Data.Add($"{MethodBase.GetCurrent()?. Name} p1", p1);
    ex. Data.Add($"{MethodBase.GetCurrent()?. Name} p2", p2);
    ex. Data.Add($"{MethodBase.GetCurrent()?. Name} v1", v1);
    ex. Data.Add($"{MethodBase.GetCurrent()?. Name} v2", v2);
}
```

Where `p1` and `p2` represent all parameters, and `v1`, `v2` represent all variables.  Non-primitive values would be serialized as Json with a depth of and formatted indented.

---
#### Feedback Bot on 3/21/2022, 07:32 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
I'm going to close this out as being too niche and domain specific for the person filing hte issue.  If such a refactoring/transformation is desired, it can be create using Roslyn's existing extensibility mechanisms (like [CodeRefactoringProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.coderefactorings.coderefactoringprovider?view=roslyn-dotnet-4.1.0)).

**Comment by sharpninja** [comment]
> I'm going to close this out as being too niche and domain specific for the person filing hte issue. 

I've been fighting for this for [nearly two decades](https://www.toolbox.com/tech/programming/blogs/improve-exception-handling-with-reflection-and-generics-040906/), and it has not always fallen on deaf ears within Microsoft as the Data property was a later addition to the base Exception and functions as the `SelfDocumentingException` from my original article.  The idea behind the refactoring is to get people to use the tools that Microsoft invested in many years ago.  Imagine how much the quality of bug reports would improve if this became a common pattern that was easy to implement with a simple refactoring.

**Comment by CyrusNajmabadi** [comment]
> i've been fighting for this for [nearly two decades](https://www.toolbox.com/tech/programming/blogs/improve-exception-handling-with-reflection-and-generics-040906/),

I tried reading the blog post, but the code was not comprehensible. Can you potentially clean it up and ping us?

**Comment by CyrusNajmabadi** [comment]
>  The idea behind the refactoring is to get people to use the tools that Microsoft invested in many years ago. Imagine how much the quality of bug reports would improve if this became a common pattern that was easy to implement with a simple refactoring.

This doesn't look at all like a pattern that people would like. As mentioned above, it seems exceptionally niche. If you do think there is value in this, you can certainly write your own refactoring here as Roslyn is an open system. 

Note: it's not at all the case that just because we add something that it is used or adopted. We have plenty of features that were speculatively added because someone thought it would be the great new way to do things, and they have <20 hits in their entire lifetime. 

I have never once seen this pattern requested represented anywhere or had any sort of push from any userbasr (internal out external) for this. You're asking us to invest majorly into this despite that, and despite it being likely this would have similarly low usage :-/

**Comment by sharpninja** [comment]
I have cleaned up the code from article and placed in a Gist:

https://gist.github.com/sharpninja/73a0ccd3ddcdfda1b828f04d0d42e765
