### ISSUE TITLE
""u8 should use singleton byte array

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#60643]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/e79be97e37654f8389f9d0d49bb27d39dd413577

**Steps to Reproduce**:
```C#
public class C
{
    public void M() => N(""u8);
    public void N(byte[] bytes){}
}
```

**Expected Behavior**:
```C#
public class C
{
    public void M() => N(Array.Empty<byte>());
    public void N(byte[] bytes){}
}
```

**Actual Behavior**:
```C#
public class C
{
    public void M() => N(new byte[0]);
    public void N(byte[] bytes){}
}
```

**Comment by Youssef1313** [comment]
@stephentoub Was this fixed?

**Comment by stephentoub** [comment]
No, just no longer relevant:
https://github.com/dotnet/csharplang/discussions/6052
