### ISSUE TITLE
Add option for diagnostics (squiggles/error list/etc.) to only check *visible* (not just *open*) files.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#60652]
This would dramatically lower costs when many files are open.  Note: a subtlety is taht we should only analyzer visible open files *and* "non-visible, open files that also have an existing visible diagnostic in them".  This way if the user has an error in a doc, and switches to *another* doc to fix it, they will see the error in the original doc go away (in the error list) without having to switch back.

**Comment by mavasani** [comment]
This is complete.
