### ISSUE TITLE
Need to make CodeLens tagger not tag files that are not visible.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#60651]
Tracking this internally with [AB#1524818](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1524818)

**Comment by sharwell** [comment]
This _shouldn't_ be having an impact (the tagger operates on syntax, and shouldn't calculate any references for anything not currently visible.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://devdiv.visualstudio.com/DevDiv/_git/d9dc88ef-476f-4add-967b-f7ddd47f4b71/commit/cc3377332fcbe5e51e6f339761b350a939f90a96
