### ISSUE TITLE
Restore back C# and VB CodeStyle layer unit test projects

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#60666]
@Youssef1313 My bad that I did not notice that your change actually deletes a bunch of test projects. C# and VB CodeStyle unit test projects test the analyzers that ship as part of respective CodeStyle NuGet package. I am going to file an issue to restore these projects back.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/pull/60549#discussion_r846622897_

**Comment by mavasani** [comment]
@Youssef1313

**Comment by davidwengier** [comment]
At least I wasn't going crazy then :)

**Comment by Youssef1313** [comment]
My bad. Sorry @mavasani @davidwengier.

Hope #60667 pass CI easily to get this merged as soon as possible.
