### ISSUE TITLE
Proposal: Allow patterns in foreach statement

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6067]
A syntactic sugar for `foreach` statement to be able to use patterns in place of the variable declaration,
```cs
foreach(let <pattern> in list) {
  ...
}

// equivalent to 

foreach(var $item in list) {
  let <pattern> = $item else continue;
}
```
If the pattern was not fallible there would be no `else continue` in the translation.

**Comment by alrz** [comment]
wait a minute, third example looks very very familiar.

**Comment by alrz** [comment]
This can also used to ignoring parameters (#20, #2145 and #2397)

**Comment by alrz** [comment]
The problem with this design is that if you try to override some method that has multiple overloads, compiler doesn't know which one you are overriding. So there should be a hint to the compiler about type of the target object.
```cs
class Foo {
    public virtual bool Equals(Bar bar) { ... }
}
class Baz : Foo {
    // ambiguous between object.Equals(object) and Foo.Equals(Bar)
    public override bool Equals(case Foo foo) { ... }
    // type hint
    public override bool Equals(case Foo foo : Bar) { ... }
}
```

**Comment by paulomorgado** [comment]
I'm sorry but I can't understand what you're proposing.

Can you provide more examples of producing/consuming code using this proposal?

**Comment by alrz** [comment]
@paulomorgado The original post is all examples by the way! It's about inserting a `case` *pattern* in place of a variable/parameter declaration so one can use extracted values from patterns. So basically
```
case (int a,int b) => ...
```
is equivalent to
```
(Tuple<int,int> t) => match(case (a,b): ... );
```

**Comment by aluanhaddad** [comment]
If I understand the examples correctly, this seems very powerful and has a lot of potential. More clarification is needed for several of the examples however. 
Specifically how is
```C#
void F(case (int a, int b)) {}
```
different from 
```C#
void F(int a, int b) {} 
```
which is part of #347?

The same questions apply to lambda expression examples.
Also, what are the element types of enumerables in the ```foreach``` and LINQ examples?

This could be great, but I'm, not sure I understand it fully.

**Comment by alrz** [comment]
The former is a *tuple-pattern* mentioned in [#5154 comment](https://github.com/dotnet/roslyn/issues/5154#issuecomment-145699928). The latter uses regular parameters. Introducing `case` keyword for patterns help with backward compatibility, because allowing patterns directly in method parameters would dramatically change method declaration syntax and semantics. But this would be an compatible extension to the existing syntax.

**Comment by gafter** [comment]
In your original examples, none of the patterns are complete. So they all produce warnings?

I'm not sure I understand the semantics of any of the proposals exhibited by your examples.

**Comment by alrz** [comment]
@gafter Tuples, single case ADTs and active patterns are considered as a complete pattern in this context (just like F#). But for event handlers
```
foo.Event += (case Foo(member), e) => { };
```
or type annotated `case`
```
(Foo case Bar bar) => {}
```
this is not complete.

However, in *overloading via patterns* section, if you cover all the cases. it would be considered as complete.

**Comment by gafter** [comment]
> Tuples, single case ADTs and active patterns are considered as a complete pattern in this context (depending on the static type of target object, just like F#).

But these declarations *don't have a target object*.

Perhaps I need to understand your proposed overload resolution rules. Can you please at least give me a hint?

**Comment by alrz** [comment]
>But these declarations don't have a target object.

It's the **parameter type**. For example in `intList.Select(a => ... )` type of `a` will be inferred from type of `intList` right? So there is no need to explicitly specify type for it, although you can do `intList.Select((int a) => ...)` as in *explicit-anonymous-function-signature*.

Same rules apply to `case` parameters: `tupleList.Select(case (a,b) => ...)` Well, type of the parameter is inferred as in *implicit-anonymous-function-signature*, hence types of `a` and `b` will be inferred too because of the **static type of the target object** which is the **parameter type** whether it's inferred or it's specified as in `(Foo case Bar bar) => ...` or `(case Foo sender, e) => ...`. Note that the latter uses a *implicit-anonymous-function-signature* hence you don't need to specify the type for `e`.

Overload resolution rules remains the same since there is a static parameter type for each `case`. But for you to be able to declare multiple versions of the same method with different parameter patterns, identical methods should be merged. So
```
public override bool Equals(object) => false;
public override bool Equals(object case Foo foo) => Equals(foo);
```
translates to:
```
public override bool Equals(object obj) =>
    obj match(case Foo foo: Equals(foo) case *: false);
```
First method `Equals(object)` uses #6115 which may be considered as `case *` when compiler is checking for identical methods to merge and completeness of these patterns.

This part is not essentially part of this proposal, and considered as an additional feature.

**Comment by gafter** [comment]
I can't tell what is part of this proposal and what isn't.

**Comment by alrz** [comment]
@gafter I meant that this can be done without going through complexity of multiple methods. F# supports patterns in method parameters but doesn't support this one — which is common in functional languages like Haskell:
```haskell
isEmpty [] = true
isEmpty _ = false
```

**Comment by alrz** [comment]
> How is this any different from the same syntax without case?

You mean like `(Foo foo) => ...`? well, that's not a pattern anymore, that's the parameter type itself. while `(Foo case Bar bar) => ...` defines a lambda which takes a `Foo` but matches it against the `Bar bar` pattern. or for event handlers you would define `(object case Foo sender, EventArgs e) => ..` which takes an `object` as first parameter to be used as an `EventHandler`.

**Comment by aluanhaddad** [comment]
> Overload resolution rules remain the same since there is a static parameter type for each case. But for you to be able to declare multiple versions of the same method with different parameter patterns, identical methods should be merged. So
> 
> ```C# 
>public override bool Equals(object) => false;
> public override bool Equals(case Foo foo) => Equals(foo);
> ```
>translates to:
> ```C#
> public override bool Equals(object obj) =>
>     obj match(case Foo foo: Equals(foo) case *: false);
>```

I take this to mean that the purpose is to defer selection of the overload until runtime and then pattern match against the actual value to select the overload that will be invoked.
So if one has
```C#
Foo x = new Foo();
object y = new Foo();

var equal = x.Equals(y);
``` 
then the value of ```equal``` will be ```true``` because the overload taking an object is selected at compile time but the use of ```case``` to declare a parameter in another overload implies that a pattern match will be performed at runtime and ```bool Equals(case Foo foo) => Equals(foo);``` is actually called. Is this the correct interpretation? 

If so, how is the following evaluated?
```C#
class Foo 
{
    ...
    public override bool Equals(case Foo foo) => Equals(foo);
    bool override  Equals(object o) => false;
    public bool Equals(int i) => i % 2 ==0;
}
...
Foo foo = new Foo();
var equal = foo.Equals((object)4);
```

**Comment by alrz** [comment]
@aluanhaddad
>I take this to mean that the purpose is to defer selection of the overload until runtime

There is no overload and the translation occurs at compile-time.
>```cs
bool override  Equals(object o) => false;
```

this is simply an error because you are overriding the method for the second time. Note that I said the `Equals(object)` in my example is implicitly a `Equals(object case *)`. For `equal` to be `true` you would define `Foo` as:
```cs
class Foo 
{
    ...
    public override bool Equals(case Foo foo) => Equals(foo);
    public override bool Equals(case int i) => i % 2 == 0;
    public override bool Equals(case *) => false;

}
```
If `Equals(int)` is not part of `object.Equals` override, then you should call `foo.Equals(4)`.

**Comment by gafter** [comment]
I think the chances of us supporting a syntax that promotes the body of a method out into the surrounding context is practically nil.

**Comment by alrz** [comment]
@gafter I think the chances of needing to write something like `tuples.Select(case (a,b) => ...)` is totally not nil. `.Select(t => (var (a,b) = t; ...))` makes no diffrence btw.

**Comment by gafter** [comment]
@alrz And I thought C# was Turing-complete...

**Comment by alrz** [comment]
@gafter so is [css](https://github.com/elitheeli/stupid-machines/tree/master/rule110)...

**Comment by gafter** [comment]
@alrz So what did you mean by "needing"?

**Comment by alrz** [comment]
@gafter I meant that it would be very common, besides, what else would you do in `tuples.Select(t => ...)` other than deconstructing the `t` first? Unless you want to pass it to another method, which in that case, the "another method" will do the deconstruction. That's why I told you before that tuple items' names are not important. Actually in functional languages, the only way to access items is by deconstruction (through patterns).

Tuples, ADTs, records, patterns, all this come from functional paradigm, so normally you would always see this kind of features together in a language. Because when you have one, you will "need" the  other. That is the way that it would make sense.  for me at least.

**Comment by gafter** [comment]
@alrz Yes, I can see how, if your tuples don't have member names like ours do, you'd benefit from promoting pattern matching into the declaration. But we do have names for our tuple members, and it conflicts with our desire to separate the method's contract (the header, outside its body) from its implementation (inside its body).

**Comment by alrz** [comment]
@gafter I see. While still `case (a,b) => ...` for lambda expressions seems way better to me I think this verboseness can be addresses with a simplified `match` syntax, instead of
```cs
.Select(t => t match ( case (a,b): ... ))
```
could it be at least
```cs
.Select(t => match t case (a, b) : ...)
```
or even
```cs
.Select(t => t case (a,b) : ...)
```
and then parenthesised it when you want to dot off them (like LINQ) or control precedence:
```cs
(t case (a,b) : ... ).Foo()
```
or chaining them
```cs
(t case (a,b): ... ) case P(x): ... case *: ... ;
```
So

>*match-expression:*
&emsp;*relational-expression match-sections*

What about `foreach(case (a,b) in list)` and from/let clause? Since there is no method contract here.

**Comment by aluanhaddad** [comment]
@alrz I think he is saying this is unnecessary for tuples because you will be able to write
```C#
tuples.Select((a, b) => ...)
```
@gafter is that correct?

**Comment by gafter** [comment]
@aluanhaddad No, that is not correct. We are not proposing to extend the parameter syntax.

**Comment by aluanhaddad** [comment]
@gafter so it will not be possible to declare a function, anonymous or otherwise, that takes a tuple as an argument? That is what I meant by ```((a, b)) =>``` it has a single argument of type tuple.

**Comment by alrz** [comment]
@aluanhaddad
>so it will not be possible to declare a function, anonymous or otherwise, that takes a tuple as an argument? That is what I meant by `((a, b)) =>` it has a single argument of type tuple.

What you are using is deconstruction syntax, which is basically a pattern. That's not possible to use patterns directly in method parameters. But I proposed that it should be with a `case` or whatever keyword like `case (a,b) => ...`

A lambda that takes a tuple as argument would be possible but probably like `((int,int) t) => ((var a, var b) = t; ...))` very intuitive so far. You may add another pair of parenthesises if you are passing this to another method.

**Comment by alrz** [comment]
@gafter I've updated the opening post and restrict it to only `foreach` statement. I think that is a reasonable and straightforward syntactic sugar to consider.

**Comment by alrz** [comment]
@gafter I've updated the opening post and restrict it to only `foreach` statement. I think that is a reasonable and straightforward syntactic sugar to consider.
