### ISSUE TITLE
VS tries to complete xml summary inside a string

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60670]
Noticed while working on https://github.com/dotnet/roslyn/pull/60648

**Version Used**:
Latest `main` - https://github.com/dotnet/roslyn/commit/0c7c0b33f0871fc4308eb2d75d77b87fc9293290

**Steps to Reproduce**:
Start code:
```csharp
var str = @"
public class Class1
{
    int x;
    /// <summary>
    /// This is a description
    /// </summary>$$
    public void Method(int unused) { }
}";
```
Press enter.

**Expected Behavior**:
I am in a string. I do not expect and want any intelligent behavior here
```csharp
var str = @"
public class Class1
{
    int x;
    /// <summary>
    /// This is a description
    /// </summary>
$$
    public void Method(int unused) { }
}";
```

**Actual Behavior**:
```csharp
var str = @"
public class Class1
{
    int x;
    /// <summary>
    /// This is a description
    /// </summary>
    /// $$
    public void Method(int unused) { }
}";
```

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/49564

**Comment by DoctorKrolic** [comment]
Ok, closing this issue as duplicate
