### ISSUE TITLE
The type of the group join and join variable after `into` and `join` keywords isn't displayed on tooltip

### ISSUE THREAD

**Issue by KyouyamaKazusa0805** [dotnet/roslyn#60680]
**Version Used**: 
VS2022 17.2 p2.1

**Steps to Reproduce**:

Type code
```csharp
var selection =
    from demon in demons
    join pet in pets on demon equals pet.Owner into gj // Here.
    select new { Demon = demon, Pets = gj };
```

**Expected Behavior**:

When we hover on the variable `gj` after keyword `into`, the question mark `?` will be displayed
as its type:

![](https://user-images.githubusercontent.com/23616315/162655405-d7819a6e-d3de-4fdd-ba04-0c6efb1555dc.png)

But when we hover on the variable `gj` in the line 3, the type of the variable will be displayed correctly:

![](https://user-images.githubusercontent.com/23616315/162655640-4bb376ad-6a48-4506-aaa2-1b05484ab3b8.png)

In addition, variable after keyword `join` doesn't display its type neither.

![](https://user-images.githubusercontent.com/23616315/162658022-dbb3bd28-10d6-4942-b077-477a2659e973.png)

But iteration variable correctly displays:

![image](https://user-images.githubusercontent.com/23616315/162658059-8cd1378c-1573-4596-ba9e-007dcc708c71.png)

**Actual Behavior**:

The variable `gj` is of type `IEnumerable<Pet>`, and `pet` is of type `Pet`.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedbakc.
