### ISSUE TITLE
Does not work with VS2013

### ISSUE THREAD

**Issue by mwisnicki** [dotnet/roslyn#607]
Trying to open solution with `Microsoft.CodeAnalysis 1.0.0-beta2`:

```
MSBuildWorkspace.Create().OpenSolutionAsync(slnPath);
```

I get an exception:
```
{"Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}
```

Looking at the codeplex bugtracker, this issue was already [reported](https://roslyn.codeplex.com/workitem/405) and closed as duplicate of another bug that was since fixed, yet it still doesn't work.

**Comment by Pilchie** [comment]
Our official nuget packages require that MSBuild 14 be installed, which can be done without installing all of Visual Studio 2015 by installing the Build Tools MSI.

Alternatively, the source contains code under `#if MSBUILD12` that should eliminate that dependency if you build yourself.

**Comment by mwisnicki** [comment]
Can you add this information to nuget description ?
