### ISSUE TITLE
Revise `FindImplementationForInterfaceMember` for abstract statics

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60704]
https://github.com/dotnet/roslyn/blob/b0cd71f82fbada617a7cb5354f52bbc478c1ff1d/src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs#L456-L459

I haven't verified, but it could be wrong.

- Affects [Public API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.itypesymbol.findimplementationforinterfacemember?view=roslyn-dotnet-4.1.0#microsoft-codeanalysis-itypesymbol-findimplementationforinterfacemember(microsoft-codeanalysis-isymbol))
- There is a callsite for nullable analysis.

**Comment by jcouv** [comment]
This was fixed in https://github.com/dotnet/roslyn/pull/60965. Thanks
