### ISSUE TITLE
Refactor local function from lambda

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#60701]
Please add refactoring converting lambda into local function or static local function.

```cs
void F() {
Func<int> a = () => 1;

int x;
Func<int> b = () => x;
}
```

==>

```cs
void F() {
static int a() { return 1; }

int x;
int b() { return x; }
}
```

**Comment by sharwell** [comment]
😕 I believe this already exists:

![image](https://user-images.githubusercontent.com/1408396/164075485-013438c6-ed9a-4559-9fd9-7fce54a711a7.png)

**Comment by NN---** [comment]
There is no such option in 17.1.4.

**Comment by CyrusNajmabadi** [comment]
Works for me as well:

![image](https://user-images.githubusercontent.com/4564579/164118546-6a7670ee-9191-4e95-bd7b-0cba41ea654a.png)

Closing out.  @NN---  if you have a repro and you can see this not working on any 17.2 build, please let us know.
