### ISSUE TITLE
InteractiveWindow.ProcessPendingSubmissions only processes one pending submission

### ISSUE THREAD

**Issue by zooba** [dotnet/roslyn#6072]
See [`ProcessPendingSubmissions`](https://github.com/dotnet/roslyn/blob/7fb8879dd8f42f344f91509fe2af1bcd0a1532f0/src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs#L729):

```csharp
private void ProcessPendingSubmissions() 
{ 
    // Snipped early exit code for when queue is empty

    var submission = _pendingSubmissions.Dequeue(); 
    SetActiveCode(submission.Input); 
    Debug.Assert(submission.Task == null, "Someone set PendingSubmission.Task before it was dequeued."); 
    submission.Task = SubmitAsync(); 
    if (submission.Completion != null) 
    { 
        // ContinueWith is safe since TaskCompletionSource.SetResult should not throw. 
        // Therefore, we don't need to await the task (which we would normally do to 
        // propagate any exceptions it might throw).  We also don't need an NFW 
        // exception filter around the continuation. 
        submission.Task.ContinueWith(_ => submission.Completion.SetResult(null), TaskScheduler.Current); 
    } 
}
```

This is important because [`IInteractiveWindow.SubmitAsync`](https://github.com/dotnet/roslyn/blob/7fb8879dd8f42f344f91509fe2af1bcd0a1532f0/src/InteractiveWindow/Editor/InteractiveWindow.cs#L195) (as implemented on `InteractiveWindow`, *not* the one referenced in the code snippet above) is public API that pends all the inputs and then waits for them all to be processed. Because only the first is processed, the task returned by `SubmitAsync` never completes.

I'd expect this function to look more like this: (sample code/untested/etc.)

```csharp
private async Task ProcessPendingSubmissions() {
    while (_pendingSubmissions.Any()) {
        var submission = _pendingSubmissions.Dequeue(); 
        SetActiveCode(submission.Input); 
        await SubmitAsync(); 
        submission.Completion?.SetResult(null);
    }
}
```

**Comment by zooba** [comment]
Ping @alexandersher, @dinov, @ManishJayaswal

**Comment by amcasey** [comment]
Related to https://github.com/dotnet/roslyn/issues/5964.

**Comment by ManishJayaswal** [comment]
We should fix this for 1.1.
@dotnet/interactive FYI

**Comment by zooba** [comment]
Not just related - it's the same issue. Feel free to close this one as a dup.

**Comment by amcasey** [comment]
Dup of #5964.

**Comment by amcasey** [comment]
@tmat Can you please verify my assessment that this was a dup?
