### ISSUE TITLE
Date format IntelliSense popup uses local format for en-us

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60729]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Date-format-IntelliSense-popup-uses-loca/10009926)._

---
[severity:It bothers me. A fix would be nice]
When typing the formattable element inside the interpolated string like in the screenshot, VS helpfully shows a preview if how things would look like depending on culture for each format. The local culture I have at the moment is displayed fine, but then in case of en-US given (I assume for comparing to Invariant), it _also_ uses the local culture. As such both strings are identical. Look at the screenshot and everything should be clear.

![image](https://user-images.githubusercontent.com/754264/163280282-70ceadce-b422-47f5-8f9a-5cf400b1a909.png)

---
#### Feedback Bot on 4/11/2022, 03:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Yeah, that's super weird.  The purpose of this is to always at least show en-US, and i'm nto sure why it would appear russian there.
