### ISSUE TITLE
Go to implementation for methods on shared base interfaces is broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60731]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-to-implementation-for-methods-on-shar/10010432)._

---
[severity:It's more difficult to complete my work]
If we have a base interface
```
interface IBase
{
    void Test();
}
```
Which is inherited by two other interfaces

```
interface IFirst : IBase
{

}

interface ISecond : IBase
{

}
```

Then these are implemented in two classes

```
class First : IFirst
{
    public void Test()
    {

    }
}

class Second : ISecond
{
    public void Test()
    {

    }
}
```
Now we use the interface
```
IFirst test = new First();
test.Test();
```

If we try to go to implementation on the method Test it brings up the window to choose which implementation we want to go to.

It should go directly to the method in class First as only one class implements IFirst.

---
#### Feedback Bot on 4/11/2022, 10:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is by-design.  The symbol here is not IFirst.Test(), it is IBase.Test.  And asking for the implementations of that is asking in particular "what are all the impls of IBase.Test".  IN this case there are two.

**Comment by CyrusNajmabadi** [comment]
Note: if the code were:

```c#
interface IBase
{
    void Test();
}

interface IFirst : IBase
{
    void Test();
}

interface ISecond : IBase
{

}
```

Then the symbol at `test.Test();` would be `IFirst.Test()` (not IBase.Test()).  IN that case, go-to-impl takes you just to First.Test() (as that's the only think that implementt `IFirst.Test()`
