### ISSUE TITLE
New Inline Rename text is hard to read in blue theme

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#60734]
**Version Used**: 
Version 17.3.0 Preview 1.0 [32412.434.main]

The new Inline Rename text for applying shortcuts is hard to read in blue theme:

![image](https://user-images.githubusercontent.com/46729679/163285122-e7b7a9a4-1963-464f-aa7e-4c9c9137687e.png)

**Comment by CyrusNajmabadi** [comment]
Oooh, measuring the contrast level, it's 1.07.  That's probably enough for everyone.

**Comment by ryzngard** [comment]
I think it's the text at the very bottom, which is definitely not 1.07

**Comment by CyrusNajmabadi** [comment]
I was definitely joking :)  It's absolutely not ok.  Sorry that my tongue in cheek didn't come across!

**Comment by ryzngard** [comment]
Looking back it makes sense, I just responded too quickly 😂
