### ISSUE TITLE
Intellisense is frustrating in VS2022 for VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60732]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-is-frustrating-in-VS2022-fo/10012169)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:15 - maybe later I went from 2015 to 22]
When selecting (for example ".Select") with Intellisense the generic type wants to be defined.
This is frustrating as the following gets output, and I am constantly deleting the "Of " that was inserted to write "Function(x)"
```
  Dim asd = {1, 2, 3}
  asd.Select(Of
```
Please either leave it at the bracket - or even better, if the T can be inferred through the functions parameters intellisense "Function(x) ", if not Intellisense "Of "

---
#### Feedback Bot on 4/13/2022, 09:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to be investing in these scenaraios.
