### ISSUE TITLE
Cross compilation for `arm64` on `x64` with a source generator in a solution fails

### ISSUE THREAD

**Issue by kiminuo** [dotnet/roslyn#60744]
**Version Used**: 4.0.1

**Steps to Reproduce**:

1. Get https://github.com/kiminuo/WalletWasabi/tree/feature/apple-silicon-roslyn-backup source code
3. `cd WalletWasabi.Fluent.Desktop` (this project depends on the `WalletWasabi.Fluent.Generators` project which fails to be loaded properly later on)
4. `dotnet build -c Release --arch arm64 --self-contained` on an `x64` platform (i.e. on an `x64` machine)
    * Alternatively `dotnet build -c Release --arch x64 --self-contained` on an `arm64` platform
6. The following warning should be emitted:
   ```
    CSC : warning CS8034: Unable to load Analyzer assembly C:\WasabiWallet\WalletWasabi\WalletWasabi.Fluent.Generators\bin\Release\netstandard2.0\win-arm64\WalletWasabi.Fluent.Generators.dll : Could not load file or assembly 'WalletWasabi.Fluent.Generators, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (0x80131621) [C:\work\WasabiWallet\WalletWasabi\WalletWasabi.Fluent\WalletWasabi.Fluent.csproj]
   ```

**Expected Behavior**:

I would expect the `WalletWasabi.Fluent.Generators` to be loaded without an issue (or give more helpful message what is actually wrong) during the build.

**Actual Behavior**:

The warning is emitted and the build fails. 

My impression is that when one wants to cross-compile a C# project referencing a source generator, an incorrect compiled assembly of the source generator might be loaded. This is a wild guess!

Any pointers how to debug this further would be greatly appreaciated.

**Comment by jcouv** [comment]
@chsienki for triage

**Comment by kiminuo** [comment]
Removing this line fixes the issue:

https://github.com/kiminuo/WalletWasabi/blob/167493c89cfeae6cc3ca304a5bad4b334e57e78a/WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj#L13

I'm not really sure why though.

**Comment by chsienki** [comment]
From the error it looks like a bug in the assembly loading logic, and we're trying to load an incorrect file. Will dig in more.

**Comment by kiminuo** [comment]
btw: I've tried to minimize a repro for this issue: [ReproSourceGenerators.zip](https://github.com/dotnet/roslyn/files/8508047/ReproSourceGenerators.zip) Maybe you find it helpful.

**Comment by jjonescz** [comment]
This doesn't seem like a bug in the compiler. The compiler is simply instructed by MSBuild to load the arm64 version of the generator which fails (that the error isn't more detailed is unfortunate, but that's runtime's issue - `AssemblyLoadContext.LoadFromAssemblyPath` doesn't provide more information about the failure). You can add `AdditionalProperties="IsRidAgnostic=true"` to the source generator `ProjectReference` which fixes this problem.
