### ISSUE TITLE
Generic methods with the same name but diferent constraints

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#6075]
Why this is not possible?
``` C#
private static void MethodName<T>(T value) where T : class
{
}

private static void MethodName<T>(T value) where T : struct
{
}
```

As constraints are different compiler can figure out which method to call.

**Comment by danieljohnson2** [comment]
I think it'll be difficult to make this unambiguous, if you allow arbitrary constraints. Class-vs-struct seems simple enough, but consider:

    void MethodName<T>(T value) where T : IConvertible {...}
    void MethodName<T>(T value) where T : struct {...}
    void MethodName<T>(T value) where T : new() {...}
    
    MethodName<int>(42); // T=int; which is called?

The three methods could, in theory, do entirely different things.

**Comment by vladd** [comment]
This is a consequence of the fact that the generic constraints are currently not a part of a function signature. See [this Jon Skeet's article](http://codeblog.jonskeet.uk/2010/10/28/overloading-and-generic-constraints/) for more details.
Are you proposing to change the function overload resolution's way of working?

**Comment by gafter** [comment]
This requires CLR changes that I would be reluctant to request.

**Comment by donovanlange** [comment]
Having recently encountered this myself, I'd actually put in a +1 for changing how method resolution works to take into account generic constraints.  

While I can understand the cases where resolution can be ambiguous as a result (as in the examples above...) semantically, it both seems more useful, and from the folks I've chatted with around the office , more /intuitive/ as well to most people that constraints are interpreted as part of the method signature.  This means that when the method can be resolved unambiguously to a single method, that it's invoked "correctly"; when ambiguous, a compiler error indicating the ambiguity should be returned (rather than the current error message that I've seen indicating a lack of a type converter to the selected method signature's types).

[This also seems in line with the comments responding to the various articles and blog posts involved.]

**Comment by Reza1024** [comment]
+1 on adding constraints to signature. For cases where using the constraints, it is still ambiguous it is natural to cause error. But if using the constraints it is not ambiguous anymore, I found it unintuitive to produce error.

I have made two very simple examples (generic and non-generic) to show why it is not intuitive.
```C#
namespace Generic
{
	public class A { }
	public class B { }
	public class AA : A { }
	public static class Ex
	{
		public static A Do(this A a) => a;
		public static T Do<T>(this T b) where T : B => b;
	}

	public class Consumer
	{
		// error CS0311: The type 'Generic.AA' cannot be used as type parameter 'T' in the generic type or method 'Ex.Do<T>(T)'. There is no implicit reference conversion from 'Generic.AA' to 'Generic.B'.
		A Use1() => new AA().Do();

	}
}
```
and the non-generic almost-equivalent
```C#
namespace NonGeneric
{
	public class A { }
	public class B { }
	public class AA : A { }
	public static class Ex
	{
		public static A Do(this A a) => a;
		public static B Do(this B b) => b;
	}

	public class Consumer
	{
		A Use3() => new AA().Do(); // This one works obviously
	}
}
```

**Comment by gafter** [comment]
Issues that would need to be addressed for this to happen:

1. The language restriction is based on a CLR restriction (constraint is not part of a method's signature). The proposer will have to push a change through the CLR specification and implementations (https://github.com/dotnet/coreclr) before (or at the same time as) a language change. You'll need to get other implementations such as mono to agree, or provide the changes for them. I don't believe the C# language team feels that this is important enough for us to call in any favors, so it is up to you to push this.
2. Constraints are not currently considered during overload resolution. That too would have to be fixed. There is a proposal for this being considered for C# 7: see #250. We'll do what we can to push this forward.
3. Finally, if the previous two items are taken care of, we could (and would) just remove the restriction currently in place disallowing declaring two methods like this.

So, @xperiandri, can you take care of point 1?

**Comment by Reza1024** [comment]
Thanks @gafter for the detailed answer. I understand the complexity with point 1 and glad to see the overload resolution is already being considered for C# 7. Although point 1 is required for the @xperiandri 's case, but considering the constraints in the overload resolution could solve so many other cases, including the one in my example.

**Comment by xperiandri** [comment]
@gafter, thanks for explanation.
I would do that one day but I have no idea how.
And I still want to try to bring workspaces #4618 to F# first, if you remember that question.
