### ISSUE TITLE
Generic completions should add `<>` and put cursor between them

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60751]
This is a bit annoying especially when there are 2 different classes, one of which is generic and the other is not, like `Task` and `Task<>`. When applying `Task<>` I expect something like this to happen:

```csharp
class Test
{
  public async Tas$$
}
```
Apply `Task<>` completion.

**Expected result:**
```csharp
class Test
{
  public async Task<$$>
}
```

**Actual result:**
```csharp
class Test
{
  public async Task$$
}
```
Basically, the same, if I apply `Task` completion

**Comment by CyrusNajmabadi** [comment]
This is possible ok, as long as we don't break muscle memory. Specifically, if the user types `T` `tab` `<` they should still end up with `Task<$$>`

**Comment by DoctorKrolic** [comment]
From my experience of using JetBrains IDEs you get used to such behaviour in about a week

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic We are not going to break muscle memory in tehse cases.  We have done that in the past and it's very upsetting for users.  Telling them they can just get used to it is a non-starter.  We need to be respectful of the usage patterns many have built up over decades.

**Comment by sharwell** [comment]
Note that `<>` _is_ inserted if you complete the item by typing `<`, e.g. the following sequence:

<kbd>Ta</kbd>, <kbd><</kbd>

The completion list is optimized for these typing scenarios, particularly in the fact that the use of <kbd>Tab</kbd> (or alternatives like <kbd>Enter</kbd>) are neither required nor desired due to unnecessary inefficiency.

**Comment by DoctorKrolic** [comment]
The fact, that user doesn't have to press `Tab` or `Enter` doesn't look like a valid reason for rejecting this fetrure request for me. To enter `<` I need to press 2 different keys that are on opposite sides of my keybord. Just pressing `Tab` will certainly increase my productivity in such scenarios. I think it is alright to introduce this feature as long as it is possible to keep user's muscle memory and don't break cases, that worked previously as @CyrusNajmabadi said

**Comment by CyrusNajmabadi** [comment]
> The fact, that user doesn't have to press Tab or Enter doesn't look like a valid reason for rejecting this fetrure request for me. To enter < I need to press 2 different keys that are on opposite sides of my keybord. 

I'm both sympathetic, but also feel that `<` is a core part of hte language, and will be something you'll need to be typing in lots of scenarios anyways.  I'm also a bit worried about this as nothing else works this way.  So generics would be operating very out of line with everything else.  I'm ok with it potentially being tried out to see if it was viable.  However, I don't think we coudl make any promises it would be taken (esp. if we feel like the risk is too high).

**Comment by DoctorKrolic** [comment]
> generics would be operating very out of line with everything else

1 feature is better than 0 features, isn't it? Slowly but surely other scenarios can be worked out later as well.

> if we feel like the risk is too high

Can you describe what risks does this feature have if taken?

**Comment by CyrusNajmabadi** [comment]
> 1 feature is better than 0 features, isn't it? Slowly but surely other scenarios can be worked out later as well.

Inconsistency is not a good thing :)

> Can you describe what risks does this feature have if taken?

Breaking anything related to muscle memory.  Basically, most of hte combination of keystrokes *except* not hitting `<` after tab woudl need to be preserved.
