### ISSUE TITLE
Verify change to AssemblyLoading_DependencyInDifferentDirectory_Delete test

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60766]
Changes were made to AssemblyLoading_DependencyInDifferentDirectory_Delete test as part of the .net7 upgrade.   This change needs to be verified for correctness.  https://github.com/dotnet/roslyn/pull/60523/commits/3c25e89e976b6de5ffff7102a7ae321a325d683d#diff-bfbf73256688a8ef87fad62fba8e4d7ac730f6bbbf3f3c42ecc322c0fa0f6405R142

Original PR - https://github.com/dotnet/roslyn/pull/60523

**Comment by chsienki** [comment]
Moving to @RikkiGibson who has more context

**Comment by jaredpar** [comment]
These were all verified when the tests were re-vamped to support more granular testing
