### ISSUE TITLE
Verify change to ConstantValueToStringTest01 test

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60767]
A change was made to the ConstantValueToStringTest01 as part of the .net7 upgrade.  This change needs to be verified for correctness.  
https://github.com/dotnet/roslyn/pull/60523/commits/3c25e89e976b6de5ffff7102a7ae321a325d683d#diff-fa3e4d702687221608839d749b02eae5fc7fff1aac1467cd089c473e36449c19R195

Original PR - https://github.com/dotnet/roslyn/pull/60523

**Comment by Youssef1313** [comment]
Note: This most likely relates to converting this enum member to string:

https://github.com/dotnet/roslyn/blob/ee9e2e6081ab82c1e1141aa3e560e87ac66c14c2/src/Compilers/Core/Portable/ConstantValue.cs#L15-L16

@stephentoub It is https://github.com/dotnet/runtime/pull/57973 causing this change?

I see https://docs.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=net-6.0 says:

> If multiple enumeration members have the same underlying value and you attempt to retrieve the string representation of an enumeration member's name based on its underlying value, your code should not make any assumptions about which name the method will return.

But do you think it's still worth documenting this as a breaking change in dotnet/docs? cc @gewarren

**Comment by stephentoub** [comment]
> But do you think it's still worth documenting this as a breaking change in dotnet/docs?

I don't. Every bug fix has the potential to break someone somewhere, and this is a bug-fix-level difference.

**Comment by jcouv** [comment]
Based on information above (thanks @Youssef1313 @stephentoub), the test change is expected and correct. Closing
