### ISSUE TITLE
Verify changes to ConvertOnEnum test

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#60765]
Changes were made to the C# and VB version of the ConvertOnEnum test as part of the .net 7 upgrade.  These changes need to be verified for correctness.

C# - https://github.com/dotnet/roslyn/pull/60523/commits/3c25e89e976b6de5ffff7102a7ae321a325d683d#diff-40a79f7f2b3feb455ff28a9a837a28924f8dab42d627f0aa6aed06a6e756258dR353
VB - https://github.com/dotnet/roslyn/pull/60523/commits/3c25e89e976b6de5ffff7102a7ae321a325d683d#diff-c21a4bd605e74c668a379180c58b139560a2e9c7118a0126a7dff9d4b759c32eL509

Original PR - https://github.com/dotnet/roslyn/pull/60523

**Comment by Youssef1313** [comment]
This one has the same reason as https://github.com/dotnet/roslyn/issues/60767, and the baseline change in test looks okay per the runtime change https://github.com/dotnet/runtime/pull/57973 and per `.ToString()` documentation.

**Comment by jcouv** [comment]
Based on information above (thanks @Youssef1313), the test change is expected and correct. Closing
