### ISSUE TITLE
Inline temporary variable adds extra type conversions in VB

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60782]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inline-temporary-variable-adds-extra-typ/10012663)._

---
[severity:It bothers me. A fix would be nice]
Let's have Visual Basic code 
 
```
 Dim a As New List(Of Integer)
 Dim q = a
 Dim c = q.Select(Function(x) 2 * x)
```
 Now we put the _caret_ after `q` on the second line (`Dim q = a`) and select Inline temporary variable from **Quick Actions and Refactoring …** drop down. The expected result is 
```
 Dim a As New List(Of Integer)
 Dim c = a.Select(Function(x) 2 * x)
```
but actual result is 
 
```
Dim a As New List(Of Integer)
Dim c = Enumerable.Select(Of Integer)(CType(CType(a, List(Of Integer)), IEnumerable(Of Integer)), CType(Function(x) 2 * x, Func(Of Integer, Integer)))
```
which is not only ugly but also syntactically wrong (_Error: BC32087 Overload resolution failed because no accessible '[Select]' accepts this number of type arguments._).
The equivalent code is C# is refactored correctly. There are other situations where extra type conversion in VB is added but the presented one is easy to reproduce and most annoying.

---
#### Feedback Bot on 4/14/2022, 03:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to be changing tehse experiences.
