### ISSUE TITLE
Remove RoslynImageCatalogGuid

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6078]
Once the RTM version of `KnownImageIds.vsct` is available, we can start consuming `CSInteractiveWindow` and `VBInteractiveWindow` from there.  For now, we've defined our own symbol, `RoslynImageCatalogGuid`, with identical values.

**Comment by ManishJayaswal** [comment]
@amcasey moving this to 1.2

**Comment by dpoeschl** [comment]
Removing User Friendly tenet, as this is an implementation detail.

**Comment by amcasey** [comment]
It appears that only `CSInteractiveWindow` made it into Update 1.

**Comment by amcasey** [comment]
This is just code hygiene and can happen whenever.
