### ISSUE TITLE
Introduce local option is not available in VB when the expression is in an interpolated string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60783]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Introduce-local-option-is-not-available-/10012731)._

---
[severity:It bothers me. A fix would be nice]
Let's have following VB code 
        
        Dim a = 1
        Dim x = $"result:{a + 1}"
        Dim y = Math.Sqrt(a + 1)
when we mark `a + 1`  on the **second** line only _Extract method_ refactoring is available
![image_2022-04-13_151540862.png](https://aka.ms/dc/image?name=B4bd0f13cb3114f6599d06a0c26805335637854525453184653_image_2022-04-13_151540862.png&tid=4bd0f13cb3114f6599d06a0c26805335637854525453184653)
but when we mark `a + 1`  on the **third** line the option _Introduce local_ is also available
![image_2022-04-13_151809126.png](https://aka.ms/dc/image?name=B6462ea888ac344e68c38f30a3443ad39637854526914553777_image_2022-04-13_151809126.png&tid=6462ea888ac344e68c38f30a3443ad39637854526914553777).

When the equivalent code is tested in C# the  the option _Introduce local_  is available on both places
![image_2022-04-13_152435577.png](https://aka.ms/dc/image?name=B3a3cd85ffa56490099029fc0e9292891637854530813133317_image_2022-04-13_152435577.png&tid=3a3cd85ffa56490099029fc0e9292891637854530813133317)

---
#### Feedback Bot on 4/14/2022, 03:25 AM: 

(private comment, text removed)
#### Feedback Bot on 4/15/2022, 08:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closign as we are not likely to be changing these expereinces.
