### ISSUE TITLE
Revisit usage of global SimplifierOptions in IBuiltInAnalyzer.OpenFileOnly 

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#60795]
Some built-in analyzers declare themselves as "open file only" (IsOpenFileOnly) when certain code style options have certain severity.

The decision is made based on Solution-wide IDE options, not based on values of these options in editorconfig. 
Is this correct?

See IBuiltinAnalyzer.IsOpenFileOnly and CompilationHasOpenFileOnlyAnalyzers

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn/issues/26758

**Comment by CyrusNajmabadi** [comment]
IBuiltInAnalyzer.OpenFileOnly was removed.
