### ISSUE TITLE
IMethodSymbol doesn't have IsNew

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#60790]
https://github.com/dotnet/roslyn/blob/acb47af8bc29d116d73d1e3469d9a5a625e9fcae/src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs#L167

`IMethodSymbol` doesn't have `IsNew`. I saw it was by design, but it would introduce some problems.

Assuming we have a partial method to be implemented by a source generator:

```csharp
public class C
{
    public void Foo() { }
}

public partial class D : C
{
    public new partial void Foo();
}
```

Without knowing whether `Foo` is `new` modified, we cannot generate the correct code in a source generator without saving the entire SyntaxNode:

```csharp
public partial class D : C
{
    public partial void Foo() { } // error CS8800: Both partial method declarations must have identical combinations of 'virtual', 'override', 'sealed', and 'new' modifiers.
    public new partial void Foo() { } // ok
}
```

Also:

```csharp
public class C
{
    public void Foo() { }
}

public partial class D : C
{
    public partial void Foo();
}
```

```csharp
public partial class D : C
{
    public partial void Foo() { } // ok
    public new partial void Foo() { } // error CS8800: Both partial method declarations must have identical combinations of 'virtual', 'override', 'sealed', and 'new' modifiers.
}
```

**Comment by jcouv** [comment]
@hez2010 I didn't understand what is the problem with going back to the method's syntax to see if the `new` modifier is present.

**Comment by hez2010** [comment]
This will require a reparsing of source code which harms the performance. 
Basically when generate code, we only need a `IMethodSymbol` to get necessary information of a method, but its lack of `IsNew` make it impossible to build the method signature without reparsing.

**Comment by jcouv** [comment]
@hez2010 Thanks for the clarification.
My prior is it's fairly rare for parsing costs to become the bottleneck. Have you observed a significant performance difference in your source generator when doing a syntax check for `new` vs. not having a check for `new` at all?

**Comment by hez2010** [comment]
Then how about get rid of `new` as a requirement of partial method signature check? i.e. make below code compiles:

```csharp
new partial T Foo();
partial T Foo() { ... }
``` 

```csharp
partial T Foo();
new partial T Foo() { ... }
```

**Comment by RikkiGibson** [comment]
The purpose of 'new' is just to silence a warning, so I could imagine us making a change to reduce the severity of a 'new' mismatch and allowing source generators to suppress the warning via pragma.

**Comment by Youssef1313** [comment]
This is done in RegexGenerator by simply calling `.Modifiers.ToString()` on the syntax node:

https://github.com/dotnet/runtime/blob/400d171cae5491320470af921dbd0b49728f99dd/src/libraries/System.Text.RegularExpressions/gen/RegexGenerator.Parser.cs#L207

**Comment by jcouv** [comment]
Chatted with @jared and confirmed that at the moment, the intent is for users to get the information from the syntax (as illustrated by @Youssef1313).
I'll go ahead and close as by-design.
