### ISSUE TITLE
SourceText.WithChanges should create optimized TextLineCollection

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/roslyn#608]
When creating a new SourceText using WithChanges currently lazy Lines collection is not being propagated. When working on larger files ~ 1000 lines+ it starts to be a bottleneck while using SourceText as backing store for the source code editor.

In my opinion if Lines collection has been already resolved subsequent calls to WithChanges should create new objects with lines collection incrementally modified.

It should be rather simple to update lines collection using information about changes introduced.

If accepted I can try to implement and contribute such an optimization.

**Comment by theoy** [comment]
Paging Dr. Neal (@gafter), is our resident parser junkie :smile:

/cc @Pilchie @pharring @jaredpar who I think will be interested in this too. I think we just need to verify that the intended optimization here is aligned with our performance goals in IDE scenarios.

**Comment by Pilchie** [comment]
Also tagging @mattwar

**Comment by pharring** [comment]
I don't believe this affects Visual Studio IDE scenarios because they use editor buffer snapshots and they have their own line tracking. However, other hosts might be using the base SourceText implementations and they've not been tuned for continual modification. For those scenarios, we'd certainly consider improvements to "WithChanges" line tracking.

@mkosieradzki Are you developing your own source code editor?

**Comment by mkosieradzki** [comment]
@pharring Yes. that's exactly what I am doing :) - what is kinda trivial task with all the support from Roslyn. :)

I am aware that VS is not using SourceText as backing store for source code, but for custom editors it's a great help. (Currently I have created an asynchronous (background thread) wrapper for Lines property resolution and I treat it like a long running operation).

Should I try to create optimized version of SourceText WithChanges and prepare a pull request?

**Comment by pharring** [comment]
Yes @mkosieradzki, please go ahead. Don't forget to add unit tests to exercise the new code path.
Thanks.

**Comment by pharring** [comment]
Thanks to @mkosieradzki for the fix.

**Comment by pharring** [comment]
(updating tags)
