### ISSUE TITLE
[EnC] Fail to apply updates to a partial method that contains a lambda

### ISSUE THREAD

**Issue by Illusive7Man** [dotnet/roslyn#60804]
**Version Used**: 
Visual Studio 2022 Version 17.1.4

**Steps to Reproduce**:

1. Create Web API Action as a **partial method**
2. Run the project
3. Make changes to the implementation of the action
4. Press **Hot Reload**

**Expected Behavior**:
Changes to be applied.

**Actual Behavior**:
Window says "Edits were made which cannot be compiled. Changes won't be applied until the compile errors are fixed..."
`ENC1002  Cannot apply changes -- unexpected error:None''Microsoft.CodeAnalysis.Emit.SymbolChange''` shows up in the Error List.

**Comment by davidwengier** [comment]
Thanks for the report. The presence of a lambda in the partial method is the key to the issue here.
