### ISSUE TITLE
Inaccurate error message when attempting to use a property as a `ref`

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#60807]
**Version Used**: current main on SharpLab (eb3ccc5)

**Steps to Reproduce**:

[Compile the following code:](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfdVLAAlgWJ2IF5jCSBhAOgAUBuAWACguABAJmL0uAby7FxxHgGZJARgBspGOWbFhxAOaoErYgGdtugL5cTnIA==)

```c#
ref int y = ref C.P;

class C
{
    public static int P { get; set; }
}
```

**Actual Behavior**:

> error CS0206: A property or indexer may not be passed as an out or ref parameter

**Expected Behavior**:

An error message that does not talk about `ref` parameters, since no method with a `ref` parameter is involved.

**Comment by ArcadeMode** [comment]
I will attempt to clarify this by instead showing `CS8145: Auto-implemented properties cannot return by reference` when attempting to use `ref` with property access.

**Comment by svick** [comment]
@ArcadeMode [You can have a `ref`-returning indexer](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfdVLAAlgWJ2IF5jCSZUB3YgYQAoBKAbQAYBdANwBYAFCiAAgCZWogN6jii4uIDMtIqRjkEACygBnLmVJ9qAPmK70Ae2YwArgBtHwkQF8gA=) and [a property that is not auto-implemented and also not `ref`-returning produces CS0206](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD5QnABDAdsdD0C86qGAwgHQAKA3ALABQDAAgEzqkMDeD6v6TAZn4BGAGyYc6Sjz7d6fBegDmEXAQB86ACws68xbwDOq9JwC+M3hfpmgA), so I think that's not accurate either.

**Comment by svick** [comment]
@ArcadeMode Yeah, that sounds good to me.
