### ISSUE TITLE
Proposal: Method Forwarding

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6081]
This feature (inspired by C++ `using` declarations) provides some sort of mixin capability in C#.
### Syntax
>*using-declaration:*
&emsp;*using-modifiers*<sub>opt</sub> `using` *using-modifiers*<sub>opt</sub> *using-target* *using-characteristic*<sub>opt</sub> `;`

>*using-target:*
&emsp;*simple-name*
&emsp;*simple-name* `::` *identifier*  *type-parameter-list*<sub>opt</sub> *parameter-type-list*<sub>opt</sub>

>*parameter-type-list*:
&emsp;`(`   *parameter-types*<sub>opt</sub>  `)`

>*parameter-types:*
&emsp;*parameter-type*
&emsp;*parameter-types* `,`  *parameter-type*

>*parameter-type:*
&emsp;*type*

>*using-modifiers:*
&emsp;*using-modifier*
&emsp;*using-modifiers using-modifier*

>*using-modifier:*
&emsp;`public`
&emsp;`private`
&emsp;`protected`
&emsp;`internal`

>*using-characteristic:*
&emsp;`for` *interface-type*
&emsp;`as` *identifier*

>*friend-declaration:*
&emsp;`friend` `class` *class-type* `;`
&emsp;`friend` `struct` *struct-type* `;`

### Example
```cs
class Foo : IFoo {
    friend class Wrapper;

    private internal void F() { } 
    public void G() { } 
    public void G(int a) { } 

    public void H() { }

    public string Baz => ...;
}

interface IFoo { void H(); }

class Wrapper : IFoo {
    private readonly Foo foo = ...;

    // includes public methods and properties as public members
    public using public foo;         

    // includes public methods and properties as protected members
    protected using public foo;   

    // includes friend methods and properties as private members
    private using private internal foo;     

    // includes all G overloads as internal methods (also a dot would be sufficient)
    internal using foo::G; 

    // includes a specific G overload as a public method
    public using foo::G(int);

    // or
    public using foo::G() as Bar;

    // generates
    public void Bar() => foo.G();
    
    // property
    public using foo::Baz;

    // generates
    public string Baz => foo.Baz;

    // explicit interface implementation
    using foo::H for IFoo;

    // includes all IFoo members from foo
    public using foo for IFoo;

    // includes all IFoo members from foo as explicit implementation
    using foo for IFoo;
}
```
Note that `private internal` is a new access modifier which would be used specifically in composition over inheritance scenarios.

**Comment by gafter** [comment]
I'd rather we do proper mixins. This proposal doesn't save many keystrokes except in the case where you "include all" of the members, and that seems dangerous.

**Comment by alrz** [comment]
@gafter I'd say that this is a common pattern in composition over inheritance principle. This proposal is not about saving keystrokes, it actually allows one to use another (inner) object members in a more explicit and concise way, without inheriting from it. Since you will specify exact access modifiers on the target members, why would it be dangerous?

I didn't quite get what you meant by "the rest of the overridden methods in the original type won't be used". `using` declarations are a syntactic sugar for declaring the exact same method as inner class and pass the parameters to it.

I didn't know about these mixins you're talking about (there is not a specific proposal for them, I guess). Are they a new kind of type? 

What about `private internal` access modifier and `friend` classes? The fact that declaring a member as `internal` will open it to the whole assembly sometimes is not desired and `private protected` doesn't address this. And of course they could be used independent of `using` declarations and still be useful.

**Comment by gafter** [comment]
@alrz See https://en.wikipedia.org/wiki/Mixin and http://docs.scala-lang.org/tutorials/tour/mixin-class-composition.html 

One advantage of mixins over composition as you propose is that when you call a virtual method on `this` from inside the mix-in code, you are calling the final overrider in the original object. If you do it using forwarding you get the overrider in the object to which you forwarded.

**Comment by alrz** [comment]
@gafter I know what they are, I just wanted to know how they would look like in C#, anyway, I see your points. Whatever they would look like, they would be safer than `using` declarations. Should I narrow this to `private internal` access modifier or that is unlikely as well?

**Comment by gafter** [comment]
@alrz I don't think we'd be likely to add syntactic support for forwarding. If we did I doubt we'd want to make special rules about particular accessibility levels.

**Comment by alrz** [comment]
@gafter Then I rather looking forward to see a proper proposal for mixins.
