### ISSUE TITLE
Quick action "Save to 'as' expression" does not add spaces around "as"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60817]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-action-Save-to-as-expression-d/10012661)._

---
From a method I returned an object with a cast. The quick actions suggested to change this to an 'as-expression'. The provided preview (see attachment) of the change showed no spaces around the "as" and after accepting the change this also resulted in (slightly wrong and easily corrected) previewed code. Note that the previewed code already had a red squiggle to mark an error in it.

---
#### Feedback Bot on 4/14/2022, 03:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Looks like this: 

![image](https://user-images.githubusercontent.com/4564579/163866340-11e221fa-2288-460a-bb9d-d8806aa1d2bb.png)

**Comment by sharwell** [comment]
I suspect the preservation of `?` during the conversion confused the parser.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/64080
