### ISSUE TITLE
Generate event doesn't work with conditional access

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#60811]
**Version Used**: 

17.2 P1.0

**Steps to Reproduce**:

```csharp
class C
{
     public event EventHandler MyEvent;

     public static void M(C c)
     {
         c?.MyEvent +=$$
     }
}
```

**Expected Behavior**:

Generate event is suggested.

**Actual Behavior**:

It's not suggested.

If the null conditional access is removed, it's suggested as expected.

**Comment by Youssef1313** [comment]
Null access isn't valid here per the current language rules anyway. Closing.

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson good case for when we add support here to the language
