### ISSUE TITLE
Make inputting <see langword="null"/> more ergonomic and discoverable

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#60814]
**Version Used**:

Currently 17.3 int.main. Has been like this for as long as I can remember.

**Summary**:

I am trying to enter this doc comment:

```c#
/// <see langword="null"/>
```

Completion currently makes this more work than just typing it out manually would be.

**Steps to Reproduce**:

In an XML doc comment, type <kbd><</kbd><kbd>s</kbd><kbd>tab</kbd> and you should input this (where `|` is the caret):

```c#
/// <see cref="|"/>
```

To change this from `cref` to `langword` slows you down, requiring changing focus from writing to editing, then a bunch of navigation which requires repetitive use of non-home-position shortcuts, or use of the mouse, which slows you down.

**Expected Behavior**:

A `null` item should be available in the current `cref` completion, that when accepted converts the attribute to `langword`.

Looking at specific keystrokes, to input `<see langword="null"/>` two keystroke sequences should be possible:

1. <kbd><</kbd><kbd>s</kbd><kbd>e</kbd><kbd>e</kbd><kbd>tab</kbd> ➡️ `<see cref="|"/>` (and opens completion again)
2. <kbd>n</kbd><kbd>u</kbd><kbd>l</kbd><kbd>l</kbd><kbd>tab</kbd> ➡️ `<see langword="null"/>|`

Either completion item could be selected in fewer keystrokes. <kbd><</kbd><kbd>tab</kbd><kbd>n</kbd><kbd>tab</kbd> may be enough.

This change makes it very easy to enter `langword`, and doesn't change anything for people who don't use `langword`. It would also make the `langword` feature more discoverable.

**Actual Behavior**:

Completion assumes `cref` which gets in the way when you want `langword`, or fails to

**Comment by Youssef1313** [comment]
Currently the shortest way to type this is to simply type `null`, then <kbd>CTRL</kbd>+<kbd>.</kbd>

![image](https://user-images.githubusercontent.com/31348972/163818262-dc8270f6-743e-45ef-a6b2-f651930b8de1.png)

**Comment by Youssef1313** [comment]
There is also https://github.com/dotnet/roslyn/issues/51481

**Comment by CyrusNajmabadi** [comment]
Yup. Closing out as already having an existing feature to make this easy.

**Comment by drewnoakes** [comment]
Thanks both. I'll try that out.
