### ISSUE TITLE
Test plan for "file types"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60819]
Proposal: dotnet/csharplang#6011
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/file-local-types.md

## Compiler
- [ ] type named `@file` exists
- [ ] type in nested namespace can hide file-type: `file class C { } namespace N { class C { }  class D  {    ... use unqualified "C" (ie. type N.C) ...  } }`
- [ ] SyntaxNormalizer
- [ ] `file` type "var" (or some other contextual keyword) declared
- [ ] SPEC: disallowed in global using (see `GlobalUsingStatic_01`)
- [x] add modifier to compiler test plan
- [x] file-interface can be implemented (implicitly or explicitly), but not when signature leaks file-type (see `InterfaceImplementation_*`)
- [x] type named "file" disallowed (should be error)
- [x] top-level local function named "file" exists
- [x] file-type allowed in attribute type
- [x] spec
- [x] modifier only allowed in new LangVer (see `LangVersion`)
- [x] modifier only allowed on top-level types (see `Nested_*`, `AccessThroughType_*`)
- [x] modifier can only be specified once (see `DuplicateModifiers_01`)
- [x] modifier allowed on various kinds of types:
  - [x] `class`
  - [ ] `struct`, 
  - [x] `record`, record struct` (see `PrimaryConstructor_01`)
  - [x] `interface` (see `InterfaceImplementation_02`)
  - [x]  `enum` (see `FileEnum_*`)
  - [ ] `delegate`
- [x] access modifiers disallowed on file-types (see `AccessModifiers_01`)
- [x] duplicate file-types are disallowed
- [x] file-type can be static (see `StaticFileClass`)
- [x] file-type can be generic (see `Generic_01`)
- [x] partial file-types in same file are the same type (see `Duplication_04`)
- [x] partial file-types in different files are different types (see `Duplication_05`)
- [x] file-type only allowed in base type of file-types (top-level or nested in generic or tuple) (see `BaseClause_*`)
  - [ ] generic base type instantiated with file-type?
  - [x] using an alias as base (see `Alias_01`)
- [x] file-type can have a base type or implement an interface (see `Nested_06`, `BaseClause_02`)
- [x] file-type only allowed in signatures within file-types (see `SignatureUsage_*`, `PrimaryConstructor_01`)
  - [ ] positive cases?
- [x] file-type as type constraint
  - [x] on method (see `Constraints_01`)
  - [x] on various other declarations: types, ...
- [x] file-type can be accessed with unqualified or qualified name (see `AccessThroughNamespace_*`)
- [x] file-type can be accessed via using, static using, but not global using (see `AccessThroughGlobalUsing_*`, `GlobalUsingStatic_01`, `UsingStatic_*`)
- [x] file-type can be accessed from top-level statements (see `TopLevelStatements`)
- [x] file-types can introduce extension methods (see `ExtensionMethod_*`)
- [x] file-types of same name can be declared in various nested namespaces (usual scoping rules apply)
- [x] types can be shadowed and there's no way to access shadowed types
- [x] file-type cannot be accessed from another file
  - [x] `file class C { } class Program { class C { } ... method with usage of inner class C ... }`
  - [x] `file class C { } class Program<C>{ ... method with usage of type parameter C ... }`
  - [x] `file class C { } class Program<C, T> where T : C { }`
  - [x] `file record C(C x);`
  - [x] `file class C<T> where T : C { }`
- [x] file-type can be used in various locations that allow types: 
  - [ ] locals, 
  - [x] constraints (methods, types, delegates),  
  - [x] interface (see `BaseClause_02`)
  - [x] attributes (see `FileEnum_02`)
  - [ ] typeof, 
  - [ ] nameof
  - [x] alias (see `Alias_01`)
  - [x] base type (`file class Outer { class Inner : Outer { } }` 
  - [x] `file class Outer { class Inner : Base<Outer> { } }`), 
  - [x] lambdas (see `Lambda_01`)
  - [x] local functions (see `LocalFunction_01`)
  - [ ] anonymous types
  - [x] cref (see `Cref_*`)
  - [ ] ...
- [x] SymbolDisplay shows unspeakable name (see `SymbolDisplay`)
  - [x] https://github.com/dotnet/roslyn/pull/61646#discussion_r910269265 Parse the emitted file type name in order to display in a similar fashion as the file type in source
- [x] Scripting (see `Script_01`)
- [x] EE (done in PR https://github.com/dotnet/roslyn/pull/62812)
- [x] Semantic model (LookupSymbols, GetSymbolInfo) (see `SemanticModel_*`)
- [x] Speculation (see `Speculation_01`)
- [x] Base reference in partial error scenario https://github.com/dotnet/roslyn/pull/60977#discussion_r883884467
- [x] PDB verification (no changes in initial design)
- [x] public API: should we have `bool INamedTypeSymbol.IsFile`? Possibly `SyntaxTree? INamedTypeSymbol.AssociatedSyntaxTree`?
- [x] public API: should we have public SymbolDisplayOptions to show the associated file of a named type? e.g. `NS.MyClass@MyFile`.
- [x] GetTypeByMetadataName (see `GetTypeByMetadataName_*`)
    - [ ] Test getting a retargeted file type from source using its metadata name
    - [x] https://github.com/dotnet/roslyn/pull/61646#discussion_r910270377 Test when MetadataTypeName.ForcedArity is specified
- [x] Confirm whether we should have `SymbolDisplayCompilerInternalOptions.IncludeContainingFileForFileTypes` 
- [x] `IsFile` should be `false` on a nested type with `file` modifier

## Language
- [x] LDM question: allow file types in signatures of explicit interface implementations within non-file types? e.g. `class C { void SomeInterface.M(FileType ft) { } }` https://github.com/dotnet/roslyn/pull/60977#discussion_r870862917 (answer: no)

## Productivity
- [x] completion for `file` (done in PR https://github.com/dotnet/roslyn/pull/62215)
- [x] colorization/classification for `file` (verified manually)
- [x] formatting/spacing for `file` (verified manually)
- [x] nav bar disambiguation when regular type and file-type with same name are in the current file (verified manually)

**Comment by tmat** [comment]
We should also consider scope of the type declaration in interactive submissions.

Defining the type in one submission and accessing it in another one should work: 

```C#
> file class C {}
> new C()
> file class C {} // should hide original definition of C
```

However, each submission has a different file name (e.g. `Submission#0`, `Submission#1`, etc.).

**Comment by jcouv** [comment]
Spotted one spec gap (Rikki will update spec). Otherwise the test coverage is pretty comprehensive. Only a couple minor bullets were not checked. I'll go ahead and close the test plan.

**Comment by RikkiGibson** [comment]
A few missing tests were noted in recent discussion with @AlekseyTs.

- [ ] What happens when we try to use a file-type by name in `-main:<type>`. Test with both its source name and metadata name.
- [ ] What happens when `partial file class` is combined with top-level-statements. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgWAFAAECMA6dBOAFASgG5lkAzKAGwFMACABwgCcAXKCCmlAJk7QHZkAb2Q1RnACw0AKlQDOzAoIC+yJUA==).
- [ ] What happens when `partial file class` and `partial class` are used together in the same file. (related to the previous point). [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgWAFAAcICcAuUIBsAEAAgExECMA7PgN7kBsRALPgLLQwAUAlDfgL79kyAGZRcAU3xosOAiXIVk1ZPlVN8AFXEBnTN2p9kfIA===)
    - I don't think we're sure what should happen here. It feels like a 'file class' never has the same name as a non-file class, in a sense, so maybe it doesn't make sense to group them, and we should require repeating the file modifier in all the partial declarations of a file type. May need to confirm with LDM.
