### ISSUE TITLE
GoToDefinitionOpensProvisionalTabIfDocumentNotAlreadyOpen failed with "cannot navigate to symbol"

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#60831]
Failed in this run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1718842&view=results

The dump shows we're showing this message box:

https://github.com/dotnet/roslyn/blob/3c00d8606624a7a2207451832a4af6adf94bf96b/src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs#L149-L150

**Comment by sharwell** [comment]
We should be overriding the notification service in integration tests to prevent dialogs from showing. Need to see if that code somehow isn't ported or isn't working in the new integration tests.

**Comment by jasonmalinowski** [comment]
This caused a failure in https://github.com/dotnet/roslyn/pull/63200.

**Comment by CyrusNajmabadi** [comment]
Closing as this is not skipped and hasn't failed recently.
