### ISSUE TITLE
Convert to interpolated string refactoring is not available in VB when an implicit conversion is used

### ISSUE THREAD

**Issue by TPIvan** [dotnet/roslyn#60835]
**Version Used**: Visual Studio 17.1.4

**Steps to Reproduce**:

1. Let's have following code

       Dim r As Object = "g"
       Dim s = "a" + r 
2.  Check _Quick Actions and Refactorings_ on the second line. _Convert to interpolated string_ refactoring is not available. 
3.  Change the second line to
 
        Dim s = "a" + r.ToString
       and the refactoring will become available
4.  When the refactoring is used the result is 
       
        Dim s = $"a{r.ToString}"
       Where there is a Quick Action for `ToString`  _Simplify interpolation_ and final result is

        Dim s = $"a{r}" 
        
**Expected Behavior**:
The "Convert to interpolated string refactoring" is available on `Dim s = "a" + r` and having the result `Dim s = $"a{r}"`
**Actual Behavior**:
Described in steps to reproduce

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to change these experiences.
