### ISSUE TITLE
Stack Trace Explorer should have middle click to close tab

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#60848]
There already is an "x" but middle click would be nice to have.

**Comment by sharwell** [comment]
It seems like _if_ this is supported, it should be done as a standard gesture throughout the UI and not just for this window.

**Comment by sharwell** [comment]
Currently the middle click behavior is setting focus to the window/tool pane.

**Comment by ryzngard** [comment]
> It seems like _if_ this is supported, it should be done as a standard gesture throughout the UI and not just for this window.

Editor tabs close on middle click. Specifically middle click on the tab heading. I think we should follow that behavior in our tool window as well. To be clear, it would only be middle click on the tab heading and not the full tool window.

**Comment by drewnoakes** [comment]
Middle click also closes tool windows, if you click on their tabs.

It also works to close tabs in every browser, and most desktop window managers I've used (task bar, alt+tab switcher, ...).

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
