### ISSUE TITLE
Inline Rename breaks when deleting portion of identifier

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#60869]
**Version Used**: Latest IntPreview

**Steps to Reproduce**:

1. Create a long identifier.
    ```C#
    int IdentifierLotsOfWords = 42;
    ```
2. Select a portion of the identifier.
    ![image](https://user-images.githubusercontent.com/116161/164337473-4438b6c7-8d36-469f-923c-fda30253322b.png)

3. Press F2 to start an Inline Rename    
    ![image](https://user-images.githubusercontent.com/116161/164337568-a0b09b70-7491-4349-8b14-d8e146134d44.png)

4. Press the DELETE key to delete the selected portion.

**Expected Behavior**: The selected portion of the identifier is deleted.

**Actual Behavior**: The rename is cancelled.

Note: Repeating steps 2-4 will eventually get Inline Rename in a bad state where the UI won't go away and there's a gold bar that reports a `COMException`. Here's the ActivityLog from session where this happened: [ActivityLog.txt](https://github.com/dotnet/roslyn/files/8525900/ActivityLog.txt)

**Comment by ryzngard** [comment]
Does this reproduce is you manually put focus into the flyout? I have a feeling this is a case where focus should have been in the flyout and isn't. Likely fixed by #60846

**Comment by CyrusNajmabadi** [comment]
Wasn't able to repro this on latest builds.  We demonstrate the expected behavior
