### ISSUE TITLE
Suggest type parameter constraints, including "generic math" interfaces

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#60878]
Opened https://github.com/dotnet/runtime/issues/59030 a while back because I find it hard to discover all the generic math interfaces due to naming. I definitely missed a bunch, see `IFloatingPointIeee754`.

I think roslyn can help with suggesting the correct constraints.
```cs
bool M<T>(T a, T b) => a > b;
```
->
```cs
bool M<T>(T a, T b) where T : IComparisonOperators<..> => a > b;
```
If there's multiple possible choices, it could list all of them for discoverability.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
