### ISSUE TITLE
Add a command to expand the C# property { get; set; }

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60889]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-command-to-expand-the-C-property-/10009582)._

---
It would be very helpful to have a refactoring/quick actions command to expand a C# property's { get; set; } block to:
{
   get
   {

   }
   set
   {

   }
}

It'd also be nice to have options to have it defaulted to 
get => _fieldName;
set => _fieldName = value;

or 

get => _fieldName;
set
{
   _fieldName = value;
}
since in many cases, the only action in the getter is to return the field value, but in the setter, often I'm also raising the PropertyChanged event, etc.

---
### Original Comments
(no comments)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
