### ISSUE TITLE
Show entire string in constant string interpolation tooltip

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60890]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-entire-string-in-constant-string-in/10016289)._

---
In C# 10 you can create a constant string from other constant strings.
```
const string First = "One";
const string Second = $"{First} Two";
```

When hovering over the constant Second it shows the string $"{First} Two" in the tooltip.

It would be nice if it could show the entire string like this $"One Two".  Or even all the levels like this $"{First} Two" = $"One Two".

---
#### Feedback Bot on 4/18/2022, 00:28 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.

**Comment by voroninp** [comment]
Reconsider, please.
We hardcode routes as a hierarchy of string constants, and it's quite important to see the resultant path, instead of just an expression.

<img width="907" height="81" alt="Image" src="https://github.com/user-attachments/assets/e8dc9572-dc3a-4355-93ac-2b8c449b8116" />
