### ISSUE TITLE
For loop auto completion, why not make settings to customize it's behavior?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60891]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/For-loop-auto-completion-why-not-make-s/10014350)._

---
Leave it as it is by default,
 or on first start of the application ask the user how they would like 
auto complete to function in general for primitive functions like
for, while, if, switch and so on.

Say we autocomplete a for loop with 
for, -tab-, -tab-
     and then we do it again.
     for, -tab-, -tab-

we end up with nested loops each using the default "int i"

which is rather annoying for me. 
perhaps incrementing the letter for each nesting i, j, k 
would not be too bad.

---
#### Feedback Bot on 4/15/2022, 01:06 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
The new 'for loop' smart snippet does this:

![Image](https://github.com/user-attachments/assets/9ddadaa8-ca84-4aab-aad6-3f9f4c0c4f8b)

It will pick a name not already in use.
