### ISSUE TITLE
IDE0060 should not activate when a base member is hidden with `new`

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#60902]
**Version Used**: 
17.2.0 Preview 3.0

**Steps to Reproduce**:
```cs
public class Test : Dictionary<int, string>
{
    public static new void Add(int key, string value) // shows IDE0060 twice
    { }
}
```
In my code, I also add `[EditorBrowsable(…Never)]` with the intention of hiding the base member.

**Expected Behavior**:
IDE0060 should not activate for `new` methods.

**Actual Behavior**:
IDE0060 ("Remove unused parameter…") shows up and suggests removing the parameters which would result in a warning for using the `new` keyword without hiding a member.

**Comment by CyrusNajmabadi** [comment]
I disagree with this assessment. We should still notify you if the unused parameter. However, we likely should remove the 'new' if no longer necessary.
