### ISSUE TITLE
Intellisense Method Paramter list to wrap not truncate

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60911]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-Method-Paramter-list-to-wra/10020341)._

---
VS Class Intellisense Method Parameter list should wrap for the entire definition of the method, not truncate after 250 characters.

---
#### Feedback Bot on 4/21/2022, 06:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi aware of the 250 char limitation ?

**Comment by CyrusNajmabadi** [comment]
I have no idea what that is referring to :)

**Comment by CyrusNajmabadi** [comment]
I think this may be referring to sig-help, and potentially some hardcoded top length we (or hte editor) shows in there.  I seem to recall hearing other complaints about this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of broad feedback on this.
