### ISSUE TITLE
Allow making attributes suppress warnings with `(Unconditional)SuppressMessage`

### ISSUE THREAD

**Issue by geekley** [dotnet/roslyn#60938]
Add compiler support for the proposed attribute from https://github.com/dotnet/runtime/issues/68301

---
## Background and Motivation
Please make it possible to suppress warnings everywhere an arbitrary attribute is applied.

Just suppressing warnings for unused code is already useful in many use cases. But the flexibility of suppressing any warnings generically based on applied attributes can have a lot of other powerful use cases as well, so this would be the ideal.

Currently, you need to apply it everywhere next to the attribute usage, which is quite verbose. For example:
```cs
class MyClass : Node {
  // Godot.Export implies the member is not unused, even if it's private
  // It's used by tools (Godot Editor) even if it's unused by code
  [Export, SuppressMessage("", "IDE0051")] string MyField { get {...} set {...} }
}
```

## Proposed API

```diff
namespace System.Diagnostics.CodeAnalysis {
  public sealed class SuppressMessageAttribute : Attribute {
+    // Suppresses warnings everywhere an attribute is applied, instead of in the attribute class itself.
+    public bool AttributeUsage { get; set; }
  }
  public sealed class UnconditionalSuppressMessageAttribute : Attribute {
+    // Suppresses warnings everywhere an attribute is applied, instead of in the attribute class itself.
+    public bool AttributeUsage { get; set; }
  }
}
```

## Usage Examples
```cs
using System.Diagnostics.CodeAnalysis;
// Suppress "Remove unused private member" everywhere [Export] attribute is applied
[assembly: SuppressMessage("", "IDE0051",
  AttributeUsage = true, Scope = "member", Target = "T:Godot.ExportAttribute")]
```
```cs
using Godot;
class MyClass : Node {
  // used by Godot's inspector, even though it's private
  [Export] string MyField { get {...} set {...} } // shouldn't raise IDE0051
}
```

## Alternative Designs
This method is preferred instead of just allowing to subclass `SuppressMessage`, because then you can just apply it on any attribute from whatever library you're using. Maximum flexibility is the best in this case.

My examples don't consider cross-assembly applicability (in a way where the lib author already uses this to specify what warnings their own attributes suppress on other projects), but I imagine it might be useful to allow this with `UnconditionalSuppressAttribute`, so library consumers don't have to worry about this.

You could alternatively allow a value like `"attributeusage"` or similar on the Scope property, but I'm not sure whether this may provide less flexibility than a separate field. If not, this would be simpler. Another option is making a separate class for attribute suppression, but I believe it might be overkill, since the fields would be the same anyways.

## Risks
No idea.

**Comment by jaredpar** [comment]
At the moment there is no desire for increasing the ways in which diagnostics can be toggled on or off. The number of ways is already far too large and it's difficult for even the product team to keep track of them all. Any expansions here need to come with a significant justification and this does not meet it at this time.
