### ISSUE TITLE
Intellisense should not provide completion of class, from which we inherit from

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#60935]
**Version Used**:
VS 2022 v17.2 Preview 4

**Steps to Reproduce**:
```csharp
class MyClass : My$$
{

}
```

**Expected Behavior**:
`MyClass` is not presented in completion list

**Actual Behavior**:
![devenv_lkwUiQhmmA](https://user-images.githubusercontent.com/70431552/164990121-b589c605-8051-47e3-8e54-8ffaaa1d4a1e.png)

Accepting completion breaks code compilation

**Comment by CyrusNajmabadi** [comment]
We would take a very targeted fix here that was extremely simple in size and scope.  As per prior discussions having an occasional extra item in intellisense is ok as the goal is not to be perfect, just to have a reasonable impl that contains a superset of what is legal.

**Comment by Youssef1313** [comment]
This might break the following scenario:

```csharp
public class C : C.Inner
{
    public interface Inner { }
}
```

It could be special cased, but does it worth doing so?

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 other important cases:

```c#
public class C : IEnumerable<C>
{
}
```

Also:

```c#
public class Map<K, V> : IEnumerable<Map.Entry>
{
    public class Entry { }
}
```

**Comment by sharwell** [comment]
The behavior here is by design. Leaving the issue open for someone to verify we have completion unit tests covering the edge case mentioned by @Youssef1313.

**Comment by CyrusNajmabadi** [comment]
> @sharwell How can wrong suggestion, that breaks code if applied, be by design?

@DoctorKrolic 

First, we've talked about this a few times, but the design of intellisense is *not* "everything in this list can be applied and will always lead to correct code".  The design is: if there's a thing that is legal, it should be in the list.  But it's ok for other stuff to be in the list as well. :)

Second, as mentioned in the past as well, we have to weigh the overall value a change brings to the user with the actual real net cost this adds to the codebase.  Completion is already one of the most expensive and complex parts of roslyn, and adding more complexity to an area that we've seen only one report of an issue in 20 years is something that may be unpalatable.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi I reported this issue not because I intentially tried to create some edge case, but I faced this in real-case scenarious. For instance:
![devenv_ToPCnUETvV](https://user-images.githubusercontent.com/70431552/166065065-034d6c61-dd61-43dd-a9ca-1943468eecca.png)
Such naming template is used in real work and here this bug gets a bit annoying

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic I don't think that scenario is important enough to warrant fixing.  It would literally just solve that *exact* case, but wouldn't solve the realistic numerous other cases that arise with normal intellisense.  For example:

![image](https://user-images.githubusercontent.com/4564579/166069892-4fe05b2c-c4a4-4754-bd8e-3002def01bdb.png)

As you can see, there are literally thousands of items shown here, none of which are viable.  Attempting to addrss this space by removing one item, when the issue can still repro with numerous others in many other cases it's overfitting to a very specific case.

--

That said, if the PR is extremely simple we'd likely take it.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
