### ISSUE TITLE
Unchecked `nuint->nint` conversion should emit no conversion

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#60944]
From @tannergooding in https://github.com/dotnet/csharplang/pull/6059/files#r858012318

You can see [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgZgAIS6BhOgbyrs4fuwDsM6AWQAUAVz4CEASjoBeAHx1hEqQgDcHLrTq4IvAOZCxug3WlzFwk/tUbKXbnV4SjvcfzMyFS5/1ubOAMcXADkxF3NvMAALGDAAaxgAE2FlP2k7B21rOjDRHMjFGLjElKs9Gwyg7V8BMLcIryLYhOTU2tUpOwBfIA===):
* unchecked uint to int is a nop
* unchecked ulong to long is a nop
* unchecked nuint to nint is a conv.i
*
* checked uint to int is a conv.ovf.i4.un
* checked ulong to long is a conv.ovf.i8.un
* checked nuint to nint is a conv.ovf.i.un

So nuint to nint is the "inconsistent" thing (unless I'm missing something important)

Note: please make sure to update spec accordingly if an implementation change is made.

**Comment by AlekseyTs** [comment]
@jcouv 
Is the title of the issue too general? Is this specifically about unchecked conversions? 
Is there a typo in the second set of examples in the description? Those that use conv.ovf commands. Should they say checked instead of unchecked?

**Comment by tannergooding** [comment]
@jcouv, I fixed the comment in the top post and ` https://github.com/dotnet/csharplang/pull/6059/files#r858012318` to be `checked` (rather than `unchecked`) for the last 3 bullets
