### ISSUE TITLE
FAR misclassifies target-typed constructor call sites

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#60949]
**Version Used**: 
Version 17.3.0 Preview 1.0 [32421.362.main]

**Steps to Reproduce**:

```C#
C F1() => new(1);
C F2() => new C(1);

record class C/*here*/(int X);
```

Invoke FAR on C as indicated by the comment.

**Expected Behavior**:

![image](https://user-images.githubusercontent.com/41759/165192535-fe64fcf1-ef3a-4c5d-b8a9-a2512ae05385.png)

**Actual Behavior**:

The Kind should be "Constructor" not "Read".

**Comment by CyrusNajmabadi** [comment]
Should hopefully be a simple fix :)
