### ISSUE TITLE
Raw string newline completion should indent when the previous line ends with open brace

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60945]
Version: VS 17.2 preview 4

```cs
var str = """
    void M() {$$ // hit enter here
    }
    """;
```

Expected behavior:
```cs
var str = """
    void M() {
        $$ cursor is here
    }
    """;
```

Actual behavior:
```cs
var str = """
    void M() {
    $$ cursor is here
    }
    """;
```

This is what VS Code ends up doing and I find it quite convenient. I think it's very common to embed snippets of code in other languages into raw strings, so it would be nice if some heuristic were implemented here which is likely to be correct across languages. cc @CyrusNajmabadi

**Comment by sharwell** [comment]
I don't think we should make any change here _except_ if it occurs as part of lighting up embedded language features.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
