### ISSUE TITLE
note: teh CT being in FixAllContext was somewhat a mistake

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#60957]
note: teh CT being in FixAllContext was somewhat a mistake (and i remove it from 'FixAllState' intentionally so it would be captured by that).  Consider (not in this PR) removing this and making it so that we don't assume the context is responsible for storing the CT.

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/60906#discussion_r857974984_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
