### ISSUE TITLE
[C# Interactive] Cutting and pasting a line with the | character adds an extra space

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#6095]
Try the following
Type `test|`
With the cursor after the | cut the line with ctrl + x
Then paste the line back with ctrl + v

Expected: `test|`
Actual: `test |`

Note the extra space between test and |. 

Additionally if you ctrl+z to undo the paste, it removes the extra space added from the paste. Using another undo removes the line entirely.

**Comment by davkean** [comment]
This looks by design. On paste, I assume we're formatting in interactive similar to a normal editor. We insert a undo unit for formatting changes, so that's why CTRL+Z undoes the extra space.

**Comment by mattscheffer** [comment]
The bug here is the extra spaced added when `test|` is pasted. Not the undo. The extra space doesn't occur in any of the other editor windows.

**Comment by davkean** [comment]
The behavior above is what we do you paste "test|" into a method body in the editor. Here's what happen when I tried your repro in the editor:

![image](https://cloud.githubusercontent.com/assets/1103906/10580199/3da9a68e-7631-11e5-8f83-e660bb7e827b.png)

On paste, we reformat the code - and we think "test |" is an expression, and put a space between "test" and "|". On undo, we let you undo just the formatting changes. This describes your behavior above.

By "doesn't occur in any of the other editor windows" - how exactly are you verifying that?

**Comment by mattscheffer** [comment]
Ah you're right. It doesn't repro on Dev12 which is what I had on my home machine when i tried to repro this.
