### ISSUE TITLE
Test plan for RelaxingShiftOperator feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#60967]
Feature branch - https://github.com/dotnet/roslyn/tree/features/RelaxingShiftOperator
Specification - https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/relaxing_shift_operator_requirements.md
Proposal: https://github.com/dotnet/csharplang/issues/4666

**Comment by jcouv** [comment]
Feature was merged into 17.3p2

**Comment by 333fred** [comment]
This test plan review was done over email. No significant additional tests beyond what was added in the [pr](https://github.com/dotnet/roslyn/pull/60717) were desired.
