### ISSUE TITLE
[Blocked] Linux machines are failing to run jobs due to "hung process"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6098]
Lots of the Linux machines have [hung process](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/225/), breaking lots of jobs

dci-ub-bld-12
dci-ub-fbld-1
dci-ub-bld-15

**Comment by jaredpar** [comment]
Is there a reason we can't a `kill -9` to our scripts that start coreclr?

**Comment by agocke** [comment]
This appears to be a deadlock in the analyzer driver. Manish can you look at this? You'll need to ssh into the ub-bld-12 machine. I've left a `screen` session running. You should be able to resume using `screen -x` once you get on the machine.

**Comment by davkean** [comment]
Wonder if this is #4858.

**Comment by davkean** [comment]
@mavasani this is blocking the majority (all?) of our Linux runs at the moment, could you take a look today at this?

**Comment by mavasani** [comment]
This is not related to #4848. I debugged this, discussed a fix with @AlekseyTs and am working on sending out a PR.

**Comment by amcasey** [comment]
A workaround is currently in place, so new failures are not expected.

**Comment by mavasani** [comment]
Sent a PR against the stabilization branch: https://github.com/dotnet/roslyn/pull/6171

**Comment by davkean** [comment]
The workaround cleans up the machine, but I don't think prevents the deadlock in the first place, right? 

@jasonmalinowski

**Comment by davkean** [comment]
We're also continually hitting deadlocks on Window machines also, for example: http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_future_win_rel_unit32/13/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52.

**Comment by mavasani** [comment]
The fix has been checked into stabilization and master - can someone from mlinfraswat take care of merging this into future and also driving the toolset update?

**Comment by tannergooding** [comment]
@mavasani. The changes are merged. If that is the last thing required for this issue, can you please close it?

**Comment by mavasani** [comment]
@tannergooding We eventually need a toolset update to ensure we don't see this on local dev boxes - you can track that work through this issue or some other way. Feel free to close this if it is the latter.

**Comment by ManishJayaswal** [comment]
We do a toolset update every sprint so assigning it to Andy to close this out when next toolset update is done.

**Comment by agocke** [comment]
Assigning to Tanner to assign to the infra person who does the toolset update :)

**Comment by davkean** [comment]
Going to close this bug - we're not seeing failures anymore, so don't need toolset update earlier than normal. Let's keep a watch and do the toolset update if we this on internal and signed builds.
