### ISSUE TITLE
Attempting bulk suppression using source code attribute in document doesn't suppress anything and silently fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60983]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Attempting-bulk-suppression-using-source/10013378)._

---
Using control+., then attempting to suppress in source (attribute), and choosing document it silently fails and suppresses nothing. It only works if I suppress each item one at a time which would take a long time because there's dozens of methods. Recording provided.

---
#### Feedback Bot on 4/14/2022, 02:52 PM: 

(private comment, text removed)
#### Feedback Bot on 4/16/2022, 02:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
