### ISSUE TITLE
[C# 9] IDE0017 is not shown for short constructor call

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#60982]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-9-IDE0017-is-not-shown-for-short-co/10013994)._

---
[severity:It bothers me. A fix would be nice]

```csharp
MyEntity entity1 = new MyEntity();
entity1.MyProperty = "Value";
```
Shows the suggestion "IDE0017: Object initialization can be simplified"

The same thing does not work for 

```csharp
MyEntity entity1 = new();
entity1.MyProperty = "Value";
```

---
#### Feedback Bot on 4/15/2022, 11:50 AM: 

(private comment, text removed)
#### Feedback Bot on 4/16/2022, 02:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
Doesn't repro in latest main (https://github.com/dotnet/roslyn/commit/55bc2b7a1d957238a6cb75682850f27f4584733f). Here is the code, that takes care of implicit object creation:
https://github.com/dotnet/roslyn/blob/55bc2b7a1d957238a6cb75682850f27f4584733f/src/Analyzers/Core/Analyzers/UseObjectInitializer/AbstractUseObjectInitializerDiagnosticAnalyzer.cs#L45-L60
If exactlier, these lines:
```cs
if (syntaxKinds.ImplicitObjectCreationExpression != null)
    matchKinds.Add(syntaxKinds.Convert<TSyntaxKind>(syntaxKinds.ImplicitObjectCreationExpression.Value));
```

However, I found another bug: IDE0017 doesn't work at all in top-level statements. Nither with explicit nor with implicit object creation. But I feel it should be a separate issue

**Comment by CyrusNajmabadi** [comment]
Closing out as not-repro.
