### ISSUE TITLE
API Request: SyntaxEquivalence

### ISSUE THREAD

**Issue by theoy** [dotnet/roslyn#61]
Forking this feature request from #16 as it becomes spread across multiple layers.

Original post: https://github.com/dotnet/roslyn/issues/16#issuecomment-71153426

Pertinent APIs: http://source.roslyn.codeplex.com/#q=SyntaxEquivalence

**Comment by CyrusNajmabadi** [comment]
SyntaxEquivalence is now exposed through methods like https://github.com/dotnet/roslyn/blob/65a15a5658b4836a855d6fdf75a5be3c2968310c/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs#L1914
