### ISSUE TITLE
Copy & paste from VS REPL sometimes doesn't preserve the color of error messages

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6100]
Repro:
```
Microsoft (R) Roslyn C# Compiler version 42.42.42.42
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> 1 1 
(1,3): error CS1002: ; expected
> void foo() { }
> 
```

Select all content of the REPL (Ctrl+A) and paste to Word. The keyword is blue but the error is black.

Note that if the selection starts at the first submission it works fine.

**Comment by ManishJayaswal** [comment]
Adding approved for next preview label as the PR that fixes this was approved.

**Comment by dpoeschl** [comment]
@genlu Is this fixed? Is this issue still open to track something?

**Comment by genlu** [comment]
@dpoeschl Yes this was fixed. Closed.
