### ISSUE TITLE
Inferred delegate type for method group should include any default parameter values

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#61007]
The inferred delegate type for a method group should include any default parameter values from the method signature (see [C# LDM-2022-04-27](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-04-27.md#default-parameter-values-in-lambdas)).

The inferred type of `m` below should be a synthesized delegate type where the `int` parameter has default value `1`, and `m()` should compile successfully.

In C#10, the inferred type of `m` is `Action<int>` so `m()` is an error.

```c#
var m = M;
m(); // error CS7036: no argument corresponds to parameter 'obj' of 'Action<int>'

static void M(int i = 1) { }
```

Including default parameter values in inferred delegate types is a _breaking change_ from C#10.

**Comment by jcouv** [comment]
@cston Would we treat this as a feature  (gated on LangVer) or a bug?

**Comment by jjonescz** [comment]
See #65300.
