### ISSUE TITLE
Emit `GC.AllocateUninitializedArray` for an initialized array creation expression

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#61011]
Right now a `newarr` immediately followed by the initialization (memberwise or block) is emitted which seem to be wasteful.
```cs
new[] { 1, 2, 3, 4 };
```
```cs
var t = GC.AllocateUninitializedArray<int>(4);
InitializeArray(t, ... );
```

**Comment by 333fred** [comment]
Not a perf improvement. See https://github.com/dotnet/roslyn/issues/62864.
