### ISSUE TITLE
Applying IDE0030 on target-typed ternary results in broken code

### ISSUE THREAD

**Issue by ajtribick** [dotnet/roslyn#61016]
**Version Used**: 

dotnet 6.0.202

**Steps to Reproduce**:

The following code triggers IDE0030: Use coalesce expression. (Note that this only seems to occur when the code is a member of a class, it does not happen on a local function in Program.cs)

```csharp
class Foo
{
    static object Databasify(int? value) => value.HasValue ? value.Value : DBNull.Value;
}
```

**Expected Behavior**:

Simplest would be not to treat the null-coalescing operator as a replacement for a ternary operator if the ternary operator uses target-typing. If the null-coalescing operator is preferred here, then it should result in `((object?)value) ?? DBNull.Value`.

**Actual Behavior**:

Applying the fix results in:

```csharp
class Foo
{
    static object Databasify(int? value) => value ?? DBNull.Value;
}
```

which does not compile, as `??` is not target-typed.

**Comment by CyrusNajmabadi** [comment]
Unable to repro this.

**Comment by BHolthuijsen** [comment]
It seems that this is indeed fixed!

The following used to generate IDE0030 (in July 2022), now it does not.

``` csharp
int? myID = null;
SqlCommand sqlCommand = new();
sqlCommand.Parameters.AddWithValue("@MyID", myID.HasValue ? myID.Value : DBNull.Value);
```
