### ISSUE TITLE
Improved suggestions for possible redundant conditional statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61023]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Improved-suggestions-for-possible-redund/10024656)._

---
Can we suggest to add intelligent suggestions if the IDE found that the conditional statements seems to be redundant. This will reduce nested statements and improves readability.

Ex: main condition of  if(driver.LicesenseNumber != updateDriver.License) is still same as the inner condition of if(updateDriver.LicenseNumber != driver.LicenseNumber). If the main condition passed, then no need to recheck in inner condition since we already know the result on main.

![image](https://user-images.githubusercontent.com/754264/165876713-8e194762-f10a-4bc3-a90c-8bbfe0b334c8.png)

---
#### Feedback Bot on 4/27/2022, 11:48 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
