### ISSUE TITLE
.editorconfig does not have the ability to warn if a function is too long, or if the number of characters in a line exceeds 80 characters.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61021]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/editorconfig-does-not-have-the-ability-/10022924)._

---
.editorconfig does not have the ability to warn if a function is too long, or if the number of characters in a line exceeds 80 characters.  It would also be useful to have a warning if the number of lines in a .cs file if too big as well.

---
#### Feedback Bot on 4/26/2022, 00:08 AM: 

(private comment, text removed)

**Comment by Youssef1313** [comment]
Possibly a duplicate of https://github.com/dotnet/roslyn/issues/15406?

**Comment by sharwell** [comment]
Duplicate of #15406
