### ISSUE TITLE
Two new lowerCamelCase rules for (local variables and parameters) under Tools>Options>Text Editor>C#>Code Style>General 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61024]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Two-new-lowerCamelCase-rules-for-local-/10023884)._

---
Request for two new rules under 
Tools>Options>Text Editor>C#>Code Style>General 

* New rule "**Local variables**" should start with lover case (lowerCamelCase).
* New rule "**Parameters**" should start with lover case (lowerCamelCase). 

More info about rule is in link under chapter Terminology, two rules like that would be useful for me.  And as i know i can not set VS2020 to have rules like that and i do not know any extension which could do that.
https://www.c-sharpcorner.com/UploadFile/8a67c0/C-Sharp-coding-standards-and-naming-conventions/

---
#### Feedback Bot on 4/27/2022, 00:02 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
