### ISSUE TITLE
C# Interactive window doesn't show error squiggles when Pull Diagnostics is turned on

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61033]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Interactive-window-cannot-recognize-o/10023611)._

---
\[severity:It bothers me. A fix would be nice\] \[regression\] \[worked-in:16.4\]  
It should be with a red wavy underline, but nothing there.
![image](https://user-images.githubusercontent.com/754264/165877439-c728eafe-e08f-4a4f-8d9c-96be57125579.png)

---
### Original Comments

(private comment, text removed)
#### Wenwen Fan [MSFT] on 28/04/2022, 04:18 PM: 
Thank you for taking the time to log this issue!
Do you still reproduce this issue now? I can’t reproduce this problem in VS2022 Community (17.1.5) with below steps:
1.Click View> Other Windows > C# Interactive.
2.Enter int a="";under C# Interactive.
Result: It is underlined with a red wavy.
Did I miss some steps? If so, can you provide the detailed repro steps and a demo project that can be reproduced? Can you try updating to the latest VS?
We look forward to hearing from you!

#### flithor on 28/04/2022, 07:47 PM: 
It looks like the feature “Enable pull diagnostics” of the advanced setting of c# text editor caused this issue.
Disable it:
![image](https://user-images.githubusercontent.com/754264/165877486-358d7813-de41-4d03-8ce6-f291983f4664.png)

Enable it:
![image](https://user-images.githubusercontent.com/754264/165877497-9e589551-e152-477a-a46a-3b17b7936f6e.png)

**Comment by Flithor** [comment]
I.. just guess disable it may works... and... yes it works...
But what's this? And why caused bug?

**Comment by dibarbet** [comment]
Once https://github.com/dotnet/roslyn/pull/61441 merges the Roslyn server should support diagnostics, however squiggles will still be missing until https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1543570 is fixed
