### ISSUE TITLE
How to correctly extract all Statements and all Comment Trivia from `SyntaxBlock`s

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#61041]
I've looked for an existing answer with different terms, but couldn't find any.
If there is already one, feel free to link it.

I write CA Analyzer and CodeFixes for our company-internal specific needs.
Essentially, i want to "unpack" `SyntaxBlock`s and keep "all" their Statements *and* Comment-Trivia.
(Replacing the one `DoStuff()` Invocation and removing `Assert.Fail()` is no problem.)
We're using `Microsoft.CodeAnalysis.Testing.CodeFixVerifier`, so the resulting AST has to match the one from the parsed solution.
Things I've tried, but didn't work:
1. just concat all Block's Statements => Trivia may be attached to Blocks Brackets
2. using MissingTokens etc. for try/catch/finally and brackets => AST mismatch
3. extract all existing Statements and make a `EmptyStatement` (with missing semicolon Token) with the Open/Close-Brackets' relevant Trivia => AST mismatch
4. like 3, but "merge" Trivia manually afterwards (currently not producing the expected result, still looking into that)
   1. attach a custom Annotation to the 'missing EmptyStatement'
   2. iterate over the resulting Statement List, and get EmptyStatements Trivia and attach Add them to next Statements LeadingTrivia (if last, use previous Statements TrailingTrivia)
   3. throw away EmptyStatement

Comments (multi/single line) may appear in "any" place (before/after Statement/Bracket; like below) or not at all.
I'd like to avoid Re-Parsing of the 'fixed' code-string.
Is No4 the right track, or is there already a convenience function?

##### Example (simplified):

before:
```cs
  public void StuffTest()
  {
    // before
    Init();
    try
    {
      Prepare();
      // try, before
      DoStuff();
      // try, after
    }
    catch (DivideByZeroException ex)
    {
      // catch, before
      Assert.IsNotNull(ex);
      // catch, after
    }
    finally
    {
      // finally, before
      Clean();
      // finally, after
    }
    // after
    Assert.Fail();
  }
```
after:
```cs
  public void StuffTest()
  {
    // before
    Init();
    Prepare();
    // try, before
    DivideByZeroException ex = Assert.ThrowsException<DivideByZeroException>(() => DoStuff());
    // try, after
    // catch, before
    Assert.IsNotNull(ex);
    // catch, after
    // finally, before
    Clean();
    // finally, after
    // after
  }
```

**Comment by svick** [comment]
What you could do is to use a [`CSharpSyntaxWalker`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.csharpsyntaxwalker) to visit all the relevant statements and comments and then put them back together the way you want.

A simple version of that could look something like this:

```c#
class Walker : CSharpSyntaxWalker
{
    List<SyntaxTrivia> comments = new();
    List<StatementSyntax> statements = new();

    public Walker() : base(SyntaxWalkerDepth.Trivia) { }

    public override void VisitExpressionStatement(ExpressionStatementSyntax node)
    {
        VisitLeadingTrivia(node.GetFirstToken());

        var modifiedNode = node
            .WithLeadingTrivia(comments)
            .WithoutTrailingTrivia();

        statements.Add(modifiedNode);

        comments.Clear();

        VisitTrailingTrivia(node.GetLastToken());
    }

    public override void VisitTrivia(SyntaxTrivia trivia)
    {
        if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
            comments.Add(trivia);
    }

    public static BlockSyntax Walk(BlockSyntax node)
    {
        var walker = new Walker();
        walker.Visit(node);

        return SyntaxFactory.Block(walker.statements)
            .WithCloseBraceToken(SyntaxFactory.Token(SyntaxKind.CloseBraceToken).WithLeadingTrivia(walker.comments))
            .NormalizeWhitespace();
    }
}
```

When called like this :

```c#
string code = @"
public void StuffTest()
{
    // before
    Init();
    try
    {
        Prepare();
        // try, before
        DoStuff();
        // try, after
    }
    catch (DivideByZeroException ex)
    {
        // catch, before
        Assert.IsNotNull(ex);
        // catch, after
    }
    finally
    {
        // finally, before
        Clean();
        // finally, after
    }
    // after
    Assert.Fail();
    // final
}";

var declaration = (MethodDeclarationSyntax)SyntaxFactory.ParseMemberDeclaration(code);

Console.WriteLine(Walker.Walk(declaration.Body));
```

It prints:

```c#
{
    // before
    Init();
    Prepare();
    // try, before
    DoStuff();
    // try, after
    // catch, before
    Assert.IsNotNull(ex);
    // catch, after
    // finally, before
    Clean();
    // finally, after
    // after
    Assert.Fail();
// final
}
```

(Though `NormalizeWhitespace()` is probably not the right way to handle whitespace in a code fix.)

**Comment by LukasGelke** [comment]
Yes, I also tend to avoid `NormalizeWhitespace()` in such cases.

But I see what your solution is. It's rather simple but effective. Maybe I should have worded my question better: tests and code review should catch these cases, but I don't know if there are any cases, where there is actually some kind of nested structure (if()/ using() Statements etc). 
By the nature of the offending code segments "it shouldn't be".
Maybe it should be worded something like "unpack blocks one depth".

But I haven't considered such an "unusual" use of a Walker. I'll try this concept but limiting it to a single depth, and just unpacking the TryStatement (and it's catches and finally). I'll have to replace the entire method body anyways, as I may want to add/remove some nodes outside the Try; and maybe have to attach some Trivia.

**Comment by Hoschi1982** [comment]
I have to use 'SyntaxWalkerDepth.StructuredTrivia' ... then it works

**Comment by ryzngard** [comment]
This looks to be resolved and possibly improperly labeled. Let me know if that's not the case, but I'm closing for now.
