### ISSUE TITLE
Visual Studio freezes even more when bulk undoing hundreds or more actions

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#61063]
## Description

I undid an hour's worth of actions (2281 specifically) to revert back to the original file state, when I realized that I was editing the wrong file.
Aside from the freeze while undoing the actions one by one, it then froze for even longer after having reverted the code, probably trying to analyze the intermediate states of the code.
In other words, I was seeing the code having been reverted back to when I had opened Visual Studio, but it also froze with a constant CPU utilization of 100% on the one core for a few minutes again.

## Version

Visual Studio 2022 Community 17.2.0 Preview 4.0

## Demonstration Example

- Starting document upon opening the file
```csharp
// Old code
public void BlaBla() { }
```

- Last iteration of the document
```csharp
// New code
public int ComplicatedMethod() => 1;
```

- Under the undoable action list, clicking the last action causes all actions to be undone, reverting the document to its starting iteration (after a while after all actions are being iteratively processed):
```csharp
// Old code
public void BlaBla() { }
```

- The code is not yet highlighted, and VS freezes for a while, but does not appear as irresponsive. CPU util is 100% for the single core it occupies. After freezing is done, the code starts being highlighted and code analysis is performed.

**Comment by CyrusNajmabadi** [comment]
I'm not sure what this is referring to. 

What actions are you talking about here?  Thanks!

Also, for this to be actionable, please follow the instructions here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Reporting-Visual-Studio-crashes-and-performance-issues.md

**Comment by AlFasGD** [comment]
By "actions" I refer to file editing actions such as writing, pasting, deleting characters, etc. that are accessible in the undo/redo buttons.

After clicking on the very last action to undo, I waited for all the actions to be sequentially performed until the result appeared, which I expected to be the original document. Once the actions were done, the document appeared in its initial state as expected, everything was white (not highlighted), then VS froze for a good minute or so. During that freeze, my one CPU core was being constantly 100% utilized. What I believe is that code analysis was being performed on every single iteration of the document during the undoing.

An important thing to note here is that memory consumption was spiking too, upwards 2 GB of extra memory being allocated during undoing.

**Comment by CyrusNajmabadi** [comment]
@AlFasGD please collect a trace and link to it. This issue is unfortunately not actionable without that. We have no idea if Roslyn is even involved in the perf issue you're seeing.

**Comment by AlFasGD** [comment]
I uploaded [a trace](https://drive.google.com/file/d/1BPCCpkHMLj5XOCFrYKTbH25IsCIzJqLg/view?usp=sharing) using PerfView, hope this is useful

**Comment by CyrusNajmabadi** [comment]
There's nothing i can see in roslyn in that trace.  It appears to be entirely the editor.  Please file a report using 'report a problem' in VS itself here:

![image](https://user-images.githubusercontent.com/4564579/167042205-d58d6344-d438-4456-9651-9ed73f46a813.png)

Ideally attach this trace to it (and/or collect another trace using that report a problem tool).  Thanks!
