### ISSUE TITLE
`cref` block is disallowed when the referenced member of type contains any unconstrainted generic argument with nullable annotation

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#61076]
**Version Used**: 

VS2022 17.2p5

**Steps to Reproduce**:

Screenshot:

![](https://user-images.githubusercontent.com/23616315/166147372-c191fd5c-1d60-4d92-994a-42959d753127.png)

**Expected Behavior**:

No warnings will be raised.

![](https://user-images.githubusercontent.com/23616315/166147405-6bea9a55-dd7b-4c93-9318-2233448be5b5.png)

There's no warning if we remove the nullable annotation from `T?`.

**Actual Behavior**:

CS1574 raised.

**Comment by jcouv** [comment]
Nullable annotation do not affect the real/runtime signature, which is what a `cref` references. There's not need/benefit to putting nullability annotations in references.
If anything, I would improve the diagnostic (maybe say "nullability annotations should not be included in `cref`" or some such).
