### ISSUE TITLE
Add more detailed scopes to C# language rules, to allow finer syntax coloring control

### ISSUE THREAD

**Issue by kraybit** [dotnet/roslyn#61074]
**Brief description:**

- In VS Code, I'd like to be able to set different colors for different storage modifers like `public` and `private`, in C# code. For this I believe we'd need more detailed scopes.
- Right now, both the `public` and `private` modifier has the textmate scope `storage.modifier.cs, source.cs`, which means it's impossible (?) to distinguish between them when coloring.

**Suggestion**

- Add finer scopes, such as `storage.modifier.public.cs` for the `public` modifier, and so on.
- So that settings like these would work in VS Code:
```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "storage.modifier.public",
      "settings":{"foreground": "#F00"}
    }
  ]
}
```
_Example of what does **not** work right now, as storage.modifier.public does not exist._

**Languages applicable:**

- C#

**Remarks**

- This was first posted here: https://github.com/microsoft/vscode/issues/137159
- Then here: https://github.com/OmniSharp/omnisharp-vscode/issues/4896
- And now it has ended up here, by redirection : )

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
