### ISSUE TITLE
Intellisense text recognition issues when editing C # code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61089]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cコードの編集時のインテリセンスの文章認識の問題/10028049)._

---
\[severity:It bothers me. A fix would be nice\]  
In VisualStudio2022, in C # document
delegate =>
If you enter the sentence, recognition of the entire document will stop.

I don't know where to report it, but I will report it here for the time being.

---
#### Feedback Bot on 5/1/2022, 04:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
![image](https://user-images.githubusercontent.com/475144/166312137-59a69e27-c01e-42be-8152-7b94b0af94bc.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/60825
