### ISSUE TITLE
Error in scanning "1.0e-99999999999999999999999"; should convert to zero

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#6109]
The literal `1.0e-99999999999999999999999` should scan as the value `0.0`, but it acts as if it is an overflow (compile-time error).

**Comment by leppie** [comment]
The following seems to be able to fix it:
```                    
try
{
  int exponentMagnitude = int.Parse(source.Substring(firstExponent, lastExponent - firstExponent));
  if (exponentSign == '-')
  {
    exponent -= exponentMagnitude;
  }
  else
  {
    exponent += exponentMagnitude;
  }
}
catch (OverflowException)
{
  exponent = exponentSign == '-' ? int.MinValue : int.MaxValue;
}
```

**Comment by gafter** [comment]
@leppie what happens if your exponent adjustment overflows? Can we use TryParse to avoid the exceptional code?

**Comment by leppie** [comment]
@gafter: I assign, I dont modify :) It is working correctly for me in IronScheme.

TryParse will give you no indication if the exponent is a valid integer but too big or small. Again, for me in IronScheme, this is not a problem, but I dont know how the C# lexer works.

**Comment by gafter** [comment]
@leppie Given that the substring that would be passed to TryParse does not contain a sign, any failure indicates an overflow (not underflow).

I'm worried about your code

```cs
exponent += exponentMagnitude
```

This could "overflow" and "wrap around", turning what should come out as an infinity into a zero.

**Comment by leppie** [comment]
That is the original code. But I see what you mean though, another issue really. 

Seeing these are exceptional cases, I feel exceptions should be OK. Wrapping that in `checked` should do the trick.

I'll submit a PR for both issues soon.

**Comment by leppie** [comment]
Updated:
```
try
{
  int exponentMagnitude = int.Parse(source.Substring(firstExponent, lastExponent - firstExponent));
  checked
  {
    if (exponentSign == '-')
    {
      exponent -= exponentMagnitude;
    }
    else
    {
      exponent += exponentMagnitude;
    }
  }
}
catch (OverflowException)
{
  exponent = exponentSign == '-' ? int.MinValue : int.MaxValue;
}
```
This is still not 100% correct, but one would have to have more than a 2 billion digit number before the separator. Will probably run into more problems before that could be hit :)

**Comment by leppie** [comment]
I am not sure I agree with `CS0594: Floating-point constant is outside the range of type 'double'`. This should be a warning at best. 

Tested with `1.0e99999999999999999999999`

**Comment by gafter** [comment]
@leppie An exception is not OK. These are not exceptional cases. As a rule, handling all kinds of correct and incorrect source code is the job of a compiler *in the normal case*. It is a normal use of a compiler to feed it an incorrect program and expect it to give the correct diagnostics.

The C# language specification requires an error (not a warning) here:
> If the magnitude of the specified literal is too large to be represented in the indicated type, a compile-time error occurs. [Note: In particular, a real-literal will never produce a floating-point infinity. A non-zero real-literal may, however, be rounded to zero. end note]

**Comment by leppie** [comment]
On the old compiler: `1.0e-99999999999999999999999` does however error too. Should the behavior be the same? If so, I'll just pull the PR, I dont know enough of the surrounds to cater for that.

**Comment by gafter** [comment]
No. The point of this bug report is that it improperly reports an error. It should just convert to zero.

**Comment by leppie** [comment]
Do you mean the `Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.OverflowException: Value was either too large or too small for an Int32.` error in debug mode and then defaulting to zero?

**Comment by leppie** [comment]
I am still confused, and Git is playing tricks on me, will try again tomorrow.

**Comment by leppie** [comment]
The following is valid, but also crashes the compiler: `0e9999999999999999999999`
