### ISSUE TITLE
CS0539 implementing interface method with T? explicitly

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/roslyn#61116]
**Version Used**:  NET6

Getting a strange CS0539 error trying to implement an interface method explicitly. Not sure if this is by-design, thought I would ask.

(Nullable context enabled in this scenario.)

Consider these two interfaces:

```csharp
internal interface Interface1
{
	void Method<T>(T value);
}

internal interface Interface2
{
	void MethodNullable<T>(T? value);
}
```

`Interface2` differs in that it has `T?`. My goal is to accept `T`, `null`, or `Nullable<T>`.

These interfaces both work fine when implemented directly/implicitly(?):

```csharp
internal sealed class TestClass : Interface1, Interface2
{
	public void Method<T>(T value) { }

	public void MethodNullable<T>(T? value) { }
}
```

But for some reason `Interface2.MethodNullable` generates CS0539 when implemented explicitly:

```csharp
internal sealed class TestClassExplicit : Interface1, Interface2
{
	void Interface1.Method<T>(T value) { }

	// Generates CS0539
	void Interface2.MethodNullable<T>(T? value) { }
}
```

**Expected Behavior**:

No errors.

**Actual Behavior**:

* `CS0535 'TestClassExplicit' does not implement interface member 'Interface2.MethodNullable<T>(T?)'`
* `CS0539 'TestClassExplicit.MethodNullable<T>(T?)' in explicit interface declaration is not found among members of the interface that can be implemented`
* `CS0453 The type 'T' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'`

**Comment by CyrusNajmabadi** [comment]
You need to write your explicit interface impl as:

```c#
    void Interface2.MethodNullable<T>(T? value) where T : default { }
```

Will add explanation later as to why this is.

**Comment by CyrusNajmabadi** [comment]
Ok, so this is a fallout of decisions we made back when we added generics in C# 2, and the later how those were impacted by NRT added in C# 8.

Back in C#2.0 it was possible to write the following:

```c#
interface IFoo
{
    void Foo<T>(T t);
    void Foo<T>(T? t) where T : struct;
}

class C : IFoo
{
    void IFoo.Foo<T>(T t) { }
    void IFoo.Foo<T>(T? t) { }
}
```

Note that when declaring these implementations in 'C' that the methods do *not* have constraints written on them.  This was fine for C# 2.0 as there was never any question about what this might mean.  In other words, the compiler could see `void IFoo.Foo<T>(T? t) { }` and know that `T` was only valid with a `struct` constraint, and so it could find `void Foo<T>(T? t) where T : struct;` in the interface to match this as an implementation of.  

However, once we added NRT this became potentially ambiguous.  Consider for example:

```c#
interface IFoo
{
    void Foo<T>(T? t);
    void Foo<T>(T? t) where T : struct;
}

class C : IFoo
{
    void IFoo.Foo<T>(T? t) { }  //<-- which method does this correspond to?
}
```

To match prior semantics, we wanted to ensure that that impl method still match the `Nullable<T>` method in the interface (e.g. the one with `where T : struct` on it).  But how could a user write the impl method and have it match the NRT method (the top method in the interface)?  

To solve that, we added `where T : default` to say "ok, this is a case where T is actually unconstrained, and if you see the `?` that doesn't mean `Nullable<T>`, instead it means `NRT`'s `?`.

**Comment by CodeBlanch** [comment]
Thanks for the explanation @CyrusNajmabadi!
