### ISSUE TITLE
Please provide two features to realize "copy-on-write"

### ISSUE THREAD

**Issue by ygc369** [dotnet/roslyn#6111]
(I've submited this idea to the coreclr forum:https://github.com/dotnet/coreclr/issues/1792, but I don't know if that is the right place, so I submit it here too.Maybe this idea need both effort.)

If some "half-immutable" objects can copy on write, a lot of memory would be saved. 
To realize this, two features are needed.
(1)  I need to get the reference count (rc) of an object to decide whether to copy. If rc is one, there's no need to copy, modifying the object directly is safe. If rc is more than one, we have to copy the object first, and then modify the new object. (all above is what "half-immutable" means.)
for example:
[RC] //reference count of objects of class with attribute "RC" would be tracked by CLR.
class test
{
  int a; 
  ~test() //finalizer
  {
    ......
  } 
}
test c = new test();
int rc=RC.get(c); //rc=1
test b=c;
rc = RC.get(c); //rc=2, if b is not used any more in the later, then rc may be 1 here, especially in "release mode".
b=null;
rc= RC.get(c); //rc=1
c=null; //rc=0, the finalizer should be called at once and wouldn't be called when GC happens.

(2)  Updating the reference of an object in the object's non-static member functions should be allowed.

for example:
[RC]class test
{
  int a;
  public void add(int x)
  {
    if(RC.get(this)>1)this=new test(); //should be allowed
    a+=x; //"a" here may be the field of the new object
  }
}

test c =new test();//c.a=0
c.add(1); //c.a=1,no new object allocated
test b=c;//the references of b and c are same, b.a=1
c.add(1);//the reference of c changed, the reference of b not changed, c!=b, c.a=2, b.a=1

**Comment by Joe4evr** [comment]
If you could please learn [how to Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) and put your samples into code blocks (both here and in #6055), that'd make it a lot easier to understand your examples. Thanks in advance.
