### ISSUE TITLE
"Convert to raw string" should work for interpolated verbatim strings

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#61124]
**Version Used**:

Version 17.3.0 Preview 2.0 [32502.216.main]

**Steps to Reproduce**:

```c#
            string projectXml =
$@"<Project>
  <PropertyGroup>
    <PROP>{propertyValue}</PROP>
  </PropertyGroup>
</Project>";
```

<kbd>Ctrl</kbd>+<kbd>.</kbd> within the string.

**Expected Behavior**:

Option "Convert to raw string" is provided, producing:

```c#
            string projectXml =
                $"""
                <Project>
                  <PropertyGroup>
                    <PROP>{propertyValue}</PROP>
                  </PropertyGroup>
                </Project>
                """;
```

**Actual Behavior**:

No code fix is provided. You have to make the edit manually. VS keeps trying to insert extra `"` as you do this, and reformatting everything, making it frustrating and more likely that the end result is not a correct translation between representations.

🔗 Also reported in [AB#1753368](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1753368)

**Comment by Rekkonnect** [comment]
Any updates on when we could expect to have this? It's a somewhat decent code fix that I would like to have.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70006.
