### ISSUE TITLE
Stable Roslyn Packages on nuget.org point to pre-release licences

### ISSUE THREAD

**Issue by afscrome** [dotnet/roslyn#6112]
The Microsoft.CodeAnalysis.CSharp 1.0.0 package at https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/1.0.0 links to a pre-release / preview licence ( http://www.microsoft.com/web/webpi/eula/dotnetcompilerplatform_redistributables_preview.htm ) .  Given that the 1.0.0 packages are stable packages, I'd expect them to point to a different licence.

**Comment by amcasey** [comment]
Thanks for the report!  We're working to correct the license now.

**Comment by davkean** [comment]
Moving this to interactive as it's a product bug, and Andrew's looking into it.

**Comment by amcasey** [comment]
I'm happy to report that package (and our other redistributable packages) now links to http://www.microsoft.com/net/dotnet_library_license.htm.
