### ISSUE TITLE
`Convert to 'Program.Main' style program` should keep leading trivia inside `Main` method

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61126]
**Version Used**:
Latest main

**Steps to Reproduce**:
```cs
// user must provide at least 1 cmd argument
if (args.Length == 0)
{

}
```
Execute `Convert to 'Program.Main' style program` refactoring

**Expected Behavior**:
```cs
internal class Program
{
    private static void Main(string[] args)
    {
        // user must provide at least 1 cmd argument
        if (args.Length == 0)
        {

        }
    }
}
```

**Actual Behavior**:
```cs
// user must provide at least 1 cmd argument
internal class Program
{
    private static void Main(string[] args)
    {
        if (args.Length == 0)
        {

        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This is by design. The comment is just likely the copyright banner, so we move to the top of the file to preserve it there.

**Comment by Neme12** [comment]
@CyrusNajmabadi Wouldn't it be worth checking if there's a blank line after the comment and only then keep it at the top? It seems unlikely that it would be a copyright banner when there's a statement directly on the next line.

**Comment by CyrusNajmabadi** [comment]
> It seems unlikely that it would be a copyright banner when there's a statement directly on the next line.

I don't see why that would be unlikely at all.  :)

Furthermore, the issue will still arise if someone writes:

```c#
// this is a comment about the statements that follow

statement1;
statement2;
statement3;
```

That person wants this to stick with teh statements, but even with the blank line check, we would move it to be the copyright header.

**Comment by Neme12** [comment]
> I don't see why that would be unlikely at all. :)

I thought that'd usually be the case and if there's a copyright header, it wouldn't have actual statements right below it, only things like usings. It looks like Roslyn itself actually has a blank line below the copyright header even before usings. It might be a good heuristic. And regarding your second point, if people comment a statement, the usually add the comment right above it without a blank line.

**Comment by CyrusNajmabadi** [comment]
> It might be a good enough heuristic, better than always assuming that it's a copyright header.

Since this feature is so new, i'm amenable to a reasonably sized PR that made that change.

**Comment by Neme12** [comment]
Another heuristic might be to always treat it as belonging to the statements unless the comment contains words like "license", "copyright" or the copyright symbol. That would only work for English, but in my experience people usually code in English even if they speak a different language.

**Comment by DoctorKrolic** [comment]
I feel like checking for "license" or other specific word is overfitting here. Checking for empty line is rather good solution on its own
