### ISSUE TITLE
Proposal: Method type-parameter-list inference

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6114]
Considering #1042, #1470, #2114, #2319, #4423, #5168, #5429 and others, there is a strong demand for a more powerful type inference in C#. Although, this one is missing:
```cs
public TResult F<>(T arg) {}
```
Compiler would infer types that are not in the scope as type parameters in order of args first and then the return type.

This also can be extended to use in delegates and record type declarations.

```cs
public struct ValueTuple<>(T1 item1,T2 item2);
public delegate void Action<>(TArg1,TArg2); // using #6115
```

**Comment by HaloFour** [comment]
Typos turning into generic type parameters?  No thanks.

**Comment by alrz** [comment]
@HaloFour this could be addressed by forcing `TName` convention but currently there is no such thing in the language.

**Comment by paulomorgado** [comment]
+1 @HaloFour

**Comment by alrz** [comment]
@paulomorgado come on, this is already closed :))
