### ISSUE TITLE
Comment block conflicts with string content

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61168]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Comment-block-conflicts-with-string-cont/10022530)._

---
[severity:It bothers me. A fix would be nice]
Trying to comment a function with block comments, I encountered a conflit with a string variable containing the pattern of the end block comment.
That makes the function not well commented, and the rest of the code not correctly parsed.

```
        // Before...
        public void test()
        {

            var i = 0;
            var dummy = "*/*";
            var j = 1;
            var k = 2;

        }

        /*
        // Trying to put a block comment on the whole function...
        public void test()
        {

                var i = 0;
                var dummy = "*/*";
                var j = 1;
                var k = 2;

        }
        */
```

---
#### Tracy Wang [MSFT] on 4/25/2022, 02:01 AM: 

(private comment, text removed)
#### Ludovic Lefebvre on 4/25/2022, 02:19 AM: 

(private comment, text removed)
#### Feedback Bot on 5/5/2022, 02:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by svick** [comment]
Do I understand it correctly that the issue here is that you expect code like `"*/*"` to *not* end a block comment?

If so, then this is the expected behavior that's explicitly called out by [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#633-comments):

> *Note*: These rules must be interpreted carefully. For instance, in the example below, […] the delimited comment starting before `D` ends before `E`. The reason is that `"D */ "` is not actually a string literal, since it appears inside a delimited comment.
>
> A useful consequence of `/*` and `*/` having no special meaning within a single-line comment is that a block of source code lines can be commented out by putting `//` at the beginning of each line. In general it does not work to put `/*` before those lines and `*/` after them, as this does not properly encapsulate delimited comments in the block, and in general may completely change the structure of such delimited comments.
>
> Example code:
>
> ```csharp
> static void Main()
> {
>     Console.WriteLine(/* "D */ "E");
> }
> ```

Altering this behavior would be a significant breaking change, so I don't expect it to happen.

**Comment by jcouv** [comment]
Thanks @svick for digging up the relevant spec. I agree we won't be able to change this (too big of a break). Closing as by-design.
