### ISSUE TITLE
Nullable tracking flips annotation when deconstructing iteration variable

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn#61172]
**Version Used**: 
.NET SDK 6.0.202 (also happens to repro on 7.0.100-preview.2.22153.17)

**Steps to Reproduce**:

1. Checkout https://github.com/Joe4evr/NullableFailRepro
2. See the comments in `Problem.cs`

**Expected Behavior**:

The tuples iterated over from `AsIndexed()` deconstruct into an `int` and `ObjectWrapper<DomainObject?>`, as Quick Info on the method clearly shows.
![NullCorrect](https://user-images.githubusercontent.com/1058562/167250922-1de9dbaa-925e-4a41-8030-6b596d362913.png)

**Actual Behavior**:

The second tuple element is changed to `ObjectWrapper<DomainObject>?` after deconstruction. The added `?` to `ObjectWrapper<>` might be from the `var` declaration, but the removal from `DomainObject?` is wrong when the start of the method clearly stated there could be wrapper instances with a `null` underlying value, causing dereferences of the underlying object to not warn as they should.
![NullIncorrect](https://user-images.githubusercontent.com/1058562/167251143-7701c1c3-0831-4de9-ae75-4b468da50372.png)

**Comment by Neme12** [comment]
That's weird, it does emit a warning for me:
![image](https://user-images.githubusercontent.com/11444821/167251696-66befc95-4a22-49f0-9bc6-fd8e25d3fac7.png)

I'm using VS 17.2.0 Preview 6.0.

**Comment by Neme12** [comment]
I still don't understand why `ObjectWrapper` itself is annotated as nullable though:
![image](https://user-images.githubusercontent.com/11444821/167251786-dba0b789-ed4e-4baf-bab6-56f0bbfc402a.png)

**Comment by Joe4evr** [comment]
> I'm using VS 17.2.0 Preview 6.0.

Okay, so I guess this is fixed recently, it's just not in stable yet?
![image](https://user-images.githubusercontent.com/1058562/167254041-a7220b35-13a3-41f1-b235-99939615713e.png)

Well, dang.

**Comment by 333fred** [comment]
> I still don't understand why `ObjectWrapper` itself is annotated as nullable though:
> ![image](https://user-images.githubusercontent.com/11444821/167251786-dba0b789-ed4e-4baf-bab6-56f0bbfc402a.png)
> 

Because that's the behavior of var. The variable declared allows you to assign null to it, but starts with the appropriate current flow state (not null in this case).

**Comment by Neme12** [comment]
@333fred Huh I see, I wouldn't expect that to be the case, but I guess it can be useful. What's funny though is that in this case, it's an iteration variable that you cannot reassign anyway.  😄 It would make sense to not make it nullable when it's a readonly variable, but I guess it has no effect on the code anyway compared to if it was treated as non-nullable, or does it?

**Comment by 333fred** [comment]
> it has no effect on the code anyway compared to if it was treated as non-nullable

Correct.
