### ISSUE TITLE
Using a more verbose qualification of the identifier of the return type of a property results in name conflict-related errors

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/roslyn#61171]
**Version Used**: Version 17.2.0 Preview 6.0

## Example

**EDIT**: This bug is consistently reproduced in the context of enabled nullability (`#nullable enable` or `<Nullable>enable</Nullable>`). With nullability disabld in that context, this bug does not occur.

Consider the abstract property:
```csharp
public abstract NodeType NodeType { get; }
```
where `NodeType` is declared within `Tree<TValue>`, so it can be referenced as `Tree<TValue>.NodeType`.

When autocompleting the property's override, the return type is written as the most verbose version of the nested type, even if `NodeType` is visible in that scope:
```csharp
public override Tree<TValue>.NodeType NodeType => throw new NotImplementedException();
```

Then, when using the simplified version of the nested type's name that conflicts with the property's name, an error will be yielded, as it will consider the right-hand `NodeType` to be the property name, instead of the returning type's name.
```csharp
public override Tree<TValue>.NodeType NodeType => NodeType.Leaf;
```

**Expected Behavior**:
- Shorten the name of the return type as much as possible when generating the override's code, if visible in that scope.
- Show a suggestion that the name of the inner type can be shortened (in the above example to `NodeType`).
- Allow writing:
```csharp
public override Tree<TValue>.NodeType NodeType => NodeType.Leaf;
```
for the above example.

**Actual Behavior**:
None of the above.

[Update(jcouv):] [sharplab repro](https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABNmTHAWACgABAZlwGdsIcATXcgJlwBUAnbbAHg4A1BsmwA+MgG8yuWS2qYaAFy4QAxkpbsAcgHtG2GXOmk5Z+bkUr1mvQY4BPAA5472Ry9yTcAc2xKAblwAXyNZUNIwizoGbGY2XAAFCB4YJTdcEFw3KJNzOSpcXQA3bC4uKANs/XdnVxqPPABeMWr7OoA6ZNTAqIiowpimLVwAGXoAMwysnNNjKLNCkrKKqu5eAWFUUTEOt0a22s8Ww8aO8YgJgIW5AHpb3ABRct0uS2BlrPzvn9+zAD9AUDAX0yANqARkGBTnVcjdZN0CEoADTwsaTVFzcJkYJAA===)

**Comment by CyrusNajmabadi** [comment]
Can you provide a full code sample?  Thanks.

**Comment by AlFasGD** [comment]
As wished:
```csharp
public sealed class Tree<TValue>
{
    public abstract class Node
    {
        public abstract NodeType NodeType { get; }
    }

    public sealed class ParentNode : Node
    {
        public override NodeType NodeType => NodeType.Parent;
    }

    public sealed class LeafNode : Node
    {
        public override Tree<TValue>.NodeType NodeType => NodeType.Leaf;
        // Error above:                                   ~~~~~~~~
    }

    public enum NodeType
    {
        Parent,
        Leaf,
    }
}
```

**Comment by jcouv** [comment]
What is the error you get when you say "error above"?
I'm not seeing any compiler error on [sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQMwAIDOBTCAbDATFBAJhQBUAnDDAHlIDUcBXDAPgFgAoAb05T8NQRgaAC7kIAYxGESAOQD2eDL348O/DQJRDR4qSgVLSATwAOGA4ownzKLigDmGEQG4UAXxV9PHL1sw4+DIoAAoQlDAihhYglkp+apr8yCjyAG4Y5ORQSnHWZhbRNhYAvCx5xQB0YRGufj5+KQG4BMQoADJYAGbRKLHRCX4aKemZ2bkUVLQM2MwslUUFFUtly+aVnRBdLkP8APR7KACiWfLk2sCjsUk3t3caAH5Pz0/1nI2oGDCMYGvK6qpdnwal8RAAaIEdboQgHeTjuIA==).

**Comment by AlFasGD** [comment]
![image](https://user-images.githubusercontent.com/8298332/167289243-1e17f114-db99-4356-b61d-37cf30af3b4b.png)
That's what I get in VS 2022 Version 17.2.0 Preview 6.0

**Comment by Neme12** [comment]
I'm seeing the error too in 17.2.0 Preview 6.0.

**Comment by Neme12** [comment]
Even if this issue is no longer reproducible in the latest version, I think someone should still think about which behavior is correct (having the error vs not having an error) and there should be a regression test added even if the current behavior is correct.

**Comment by AlFasGD** [comment]
Without knowing how the spec addresses this, if at all, in which case it should be specifically mentioned, I'd argue the behavior should be no error. I'm glad to see that in SharpLab it works as intended with none of the aforementioned issues, and regression tests appear mandatory.

**Comment by Neme12** [comment]
Hm, this is weird. In SharpLab, there are no errors and it compiles even when using an old branch (like demos/build-2020):
![image](https://user-images.githubusercontent.com/11444821/167299286-38eef64c-5d63-42eb-ac48-347cd8d9c1ed.png)

Maybe this is actually affected by some compilation options?

**Comment by Neme12** [comment]
Oh, I see. With `<Nullable>enable</Nullable>`, it shows an error, but without it, it compiles.

**Comment by AlFasGD** [comment]
If it's related to nullability, I'd guess symbol comparison freaks out because of nullability variance? I don't even want to know what type symbol is resolved as the container class in this example (nullable or not).

**Comment by AlFasGD** [comment]
Another interesting point is that if you constraint `TValue` to `struct`, with reference type nullability enabled, no error will be reported. This narrows the problem down to type parameter nullability issues.

**Comment by jcouv** [comment]
Thanks for the clarification. Added sharplab repro link to OP. Nullability annotations and analysis should only affect warning diagnostics, but in this case enabling nullability results in an error.
