### ISSUE TITLE
Fade-out of unused variables or parameters and dark theme

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61185]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Fade-out-of-unused-variables-or-paramete/10031816)._

---
When using the dark theme, the fade effect of the unused parameters or identifiers is too low and there is only a small difference with the other identifiers, even though I set the background color to black and the text to white.

![image](https://user-images.githubusercontent.com/611219/167464622-3a7d38b5-8a66-4580-b105-fdd0d9c552b4.png)

---
#### Feedback Bot on 5/5/2022, 06:29 PM: 

(private comment, text removed)
#### Feedback Bot on 5/6/2022, 00:27 PM: 

(private comment, text removed)
#### Francesco Tovagliari on 5/7/2022, 00:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JoeRobich** [comment]
So this feedback is in contrast to many others we receive, typically we hear that the unused fading makes code too dark to be legible. Since the fading opacity is fixed, users are unable to improve this situation without further adjusting classification colors.

**Comment by vatsalyaagrawal** [comment]
This is F#, closing this Github issue. We will reopen the original feedback ticket and route that to F# team.
