### ISSUE TITLE
[LSP] Re-enable LSP GoToDefinition + GoToImplementation integration tests

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#61188]
GoToDefinition and GoToImplementation LSP integration tests are failing with errors such as:

```
Assert.Equal() Failure
↓ (pos 5)
Expected: FileImplementation.cs
Actual:   FileInterface.cs ⬤
↑ (pos 5)
```
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1751692&view=results

For now, we're going to disable the failing tests so we can re-enable the LSP integration pipeline in CI, but we should investigate why these failures are occurring.

**Comment by dibarbet** [comment]
closing.  no plans to re-enable lsp integration tests for this until we actually switch to LSP for this feature.
