### ISSUE TITLE
`not` not appearing after `and`/`or` in pattern.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#61184]
![image](https://user-images.githubusercontent.com/4564579/167453391-8ae99dd5-5498-4ad1-ba33-a5fe585e3b2f.png)

**Comment by Neme12** [comment]
Oh, did you mean "not appearing" as opposed to "appearing"?

**Comment by CyrusNajmabadi** [comment]
> Oh, did you mean "not appearing" as opposed to "appearing"?

**Comment by CyrusNajmabadi** [comment]
Oh, sam edited the title.  Yes, that :)
