### ISSUE TITLE
Make local function 'static' removes `unsafe` modifier

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#61207]
**Version Used**:  Visual Studio 17.2.0 Preview 6.0

**Steps to Reproduce**:

```c#
class C
{
    void M()
    {
        unsafe void F()
        {
        }
    }
}
```

Use the "Make local function 'static'" code fix on `B`.

**Expected Behavior**:
```c#
class C
{
    void M()
    {
        static unsafe void F()
        {
        }
    }
}
```

**Actual Behavior**:
```c#
class C
{
    void M()
    {
        static void F()
        {
        }
    }
}
```

It looks like #32423 wasn't fixed completely 😄 I think it would make sense to go through all of the "allowed modifiers" lists for each declaration type again to make sure that something else isn't still missing. @CyrusNajmabadi Looks like you did the previous work here in #42268.

**Comment by Youssef1313** [comment]
Fixed in 17.3 Preview 1 by https://github.com/dotnet/roslyn/pull/59297

**Comment by Neme12** [comment]
I still think the lists should be reviewed. This has happened over and over.

**Comment by Neme12** [comment]
Also, the tests of the allowed modifiers in https://github.com/dotnet/roslyn/blob/main/src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs#L2218
don't test local functions at all.

**Comment by CyrusNajmabadi** [comment]
Closing as fixed. Thanks @Youssef1313
