### ISSUE TITLE
Improve NormalizeWhitespace for object initializers

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/roslyn#61204]
**Version Used**: 

`Microsoft.CodeAnalysis.Common` version 4.1.0
`Microsoft.CodeAnalysis.CSharp` version 4.1.0

**Steps to Reproduce**:

Call `NormalizeWhitespace()` on the following code:

```c#
object messages = new object
{
	Output = new object()
	{
		Status = ""testing"",
		Errors = new List<string>(),
		Messages = new List<string>()
	}
};
```

(Here's a .NET fiddle that reproduces the issue: https://dotnetfiddle.net/j8yH4j)

**Expected Behavior**:

Output:

```c#
object messages = new object
{
	Output = new object()
	{
		Status = ""testing"",
		Errors = new List<string>(),
		Messages = new List<string>()
	}
};
```

**Actual Behavior**:

Output:

```c#
object messages = new object {Output = new object ()
{Status = "testing", Errors = new List<string>(), Messages = new List<string>()}};
```

**Additional Info**

With many people calling `NormalizeWhitespace()` on the outputs of their source generators, I think this is a bigger issue than it used to be. We're running into this issue with our source generator, as well.

**Comment by jcouv** [comment]
Sorry, but it's unlikely we'll get to this given the priority relative to other issues. I'll mark this as help-wanted, but push it to the backlog (ie. we won't actively work on it unless something changes).

**Comment by Bosch-Eli-Black** [comment]
Okay, no worries 🙂  Maybe we can revisit this if auto formatting of source generators gets implemented (https://github.com/dotnet/roslyn/issues/49685)

**Comment by Bosch-Eli-Black** [comment]
@CyrusNajmabadi Honestly, that like sounds fun 🙂   But... in order for me to be able to to contribute to open source projects at my current job, my understanding is that I must take an in person class on the subject, and that class isn't offered in my location, so... 😅
