### ISSUE TITLE
Add AnalyzerConfigSet.GetOptionsForDirectory

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#61217]
## Background and Motivation

The IDE needs to determine all editorconfig options that apply to all documents in a project.

## Proposed API

```diff

namespace Microsoft.CodeAnalysis;

public class AnalyzerConfigSet
{
+    public AnalyzerConfigOptionsResult GetOptionsForDirectory(string path);
}
```

## Usage Examples

```C#
set.GetOptionsForDirectory(projectDir);
```

## Alternative Designs

Keep current workaround: The IDE currently calls `AnalyzerConfigSet.GetOptionsForSourcePath` with a synthesized path under the project directory: 

```C#
set.GetOptionsForSourcePath(Path.Combine(projectDir, "\0.cs"));
```

`\0` is used for file name to avoid conflicts with patterns listed in the editor config file.

**Comment by jcouv** [comment]
Assigned to @mavasani and @333fred to drive/prioritize as area owners for api-Analyzers

**Comment by 333fred** [comment]
I don't think just "directory" works. The `.cs` extension is important for understanding what rules to resolve in that directory.

**Comment by mavasani** [comment]
Agree with @333fred - I think the workaround looks reasonable to me. If we wanted a new API, it would have to be `public AnalyzerConfigOptionsResult GetOptionsForDirectory(string path, string extension);`. I personally feel the issue mentioned in https://github.com/dotnet/roslyn/issues/61777#issuecomment-1170859556 for the existing API [AnalyzerConfigSet.GetOptionsForSourcePath](https://github.com/dotnet/roslyn/blob/58d8ea0066f649de1bfe1852bb90f56db981bb67/src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs#L189) is more critical to address.

Also tagging @chsienki
