### ISSUE TITLE
Building skeleton assemblies appears to be much more expensive now that we have generators.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#61226]
Looking at some traces, i'm seeing an enormous amount of time being spent producing skeleton references (whih in turn is spending lots of time in generators):

![image](https://user-images.githubusercontent.com/4564579/167731083-bb800fc2-be0b-44c3-a0de-68bc8eb0b0e2.png)

![image](https://user-images.githubusercontent.com/4564579/167731131-317c8457-491a-40bd-9bc3-80a950239e6a.png)

I have a theory that generators aren't respecting EmitOptions.EmitMetadataOnly.  this is causing us to do an actual *full* analysis of the code in teh project which has skyrocketed computation costs for these projects.  The point of metadata-only is to only generate the top level symbols without binding method bodies.  Effectively producing something akin to a 'ref assembly' that downstream projects can then use for symbolic information.  If we end up binding all method bodies then taht effectively defeats the purpose and makes these scenarios churn through much more CPU and memory continuously.

**Comment by CyrusNajmabadi** [comment]
From talking to chris, sounds like we may need to ensure that we collect and report generator timings involved here so we can appropriately get the respective teams to look (and so users can understand the impact that certain generators are having so they can disable them).

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Given your other fixes in the area, did we conclude this was the other regressions and not source generators here? Again that's not to say that there *isn't* stuff we can improve there -- but wondering if we should close this and reopen other bugs with the other ideas we had there.

**Comment by CyrusNajmabadi** [comment]
I think i can close this out.  Things are more expensive, but not as explosively so with my current/upcoming work.
