### ISSUE TITLE
Make string interpolation work properly with constants

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/roslyn#6122]
Consider this non-working example:

```csharp
const string Name = "Mary";
const string Number = "five";

const string Result = $"{Name} has {Number} apples"; // error CS0133: The expression being assigned to 'Result' must be constant
```

At the same time, the following will work:

```csharp
const string Name = "Mary";
const string Number = "five";

const string Result = Name + " has " + Number + " apples";
```

Should they really be so different? I think it's a good idea to make string interpolation generate constant strings if invoked on compile-time constants.

**Comment by ramzzzay** [comment]
Yep, i mean it's will be a great job to make .Net more user friendly.

**Comment by alrz** [comment]
@ramzzzay I'd say developer-friendly, the term “user” can describe an individual who uses drugs, btw.

**Comment by ramzzzay** [comment]
@alrz yes, good correction bro, i said it on automatic =)

**Comment by SLaks** [comment]
Note that this isn't so inconsistent; `"A" + 1` is already not a constant expression (because it involves a conversion).

**Comment by ForNeVeR** [comment]
Yes, I understand that it's because number-to-string conversions uses current locale, so it won't be constant value across machines. I'm talking only about string concatenation here.

**Comment by SLaks** [comment]
It would be very confusing to have this feature only work for strings and no other types; I don't think that's a good idea.

**Comment by ForNeVeR** [comment]
It is already working only for strings and not for another types; it is already confusing :)
Compare the following:

```csharp
const string A = "a" + 1; // error
const string B = "b" + "1"; // ok
```

**Comment by SLaks** [comment]
I know, but hiding the concatenation in interpolation syntax makes it more confusing.

**Comment by AdamSpeight2008** [comment]
There is the additional issue the arghole `{ value , alignment : formatting }` can have alignment and more formatting applied to it.

I was in the process of update [String Format Diagnostic](https://visualstudiogallery.msdn.microsoft.com/adbded26-4bc1-4d24-be86-61eef8768eee) to handle string interpolations as well, when me computer broke. Now that I have new one I can get back to it. It could provide information about constants. It currently does not provide code fixes.

**Comment by alrz** [comment]
I'm sure that he meant "string constants".

**Comment by gafter** [comment]
String interpolation is defined in terms of an invocation of `string.Format`. It therefore isn't, formally, a constant.
