### ISSUE TITLE
Rename doesn't resolve conflicts by reducing extension method invocations

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#6123]
Source:

**ProjectA**:

``` C#
public static class Extensions {
    public static int M(this int x) => x;
}
```

**ProjectB** (references ProjectA):

``` C#
class Extensions2 {
    int x = Extensions.M(0);
}
```

Rename `Extensions2` to `Extensions`.

The invocation will become an unresolvable conflict.

Instead, it ought to reduce it to `0.M()`.

Although this scenario is a bit of a corner case, I think it would be nicer to reduce extension method invocations instead of expanding to `global::Namespace.Extensions.Method()`, even when it isn't necessary to resolve the conflict.

**Comment by Pilchie** [comment]
I'm not sure that I agree that we should simplify to extension invocation in general.  Usually when people write extension method calls as static invocations it's because they wanted them to be that way.

**Comment by CyrusNajmabadi** [comment]
Subsumed in https://github.com/dotnet/roslyn/issues/66730.
