### ISSUE TITLE
[LSP] Semantic tokens flickering

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61239]
Latest main with LSP semantic tokens feature flag turned on.

In roslyn, copy paste some code from one file to another.  Watch as the colors flicker back and forth from uncolored to colored.  See gif (it's a long gif FYI).

![lsp_semantic_tokens_flickering](https://user-images.githubusercontent.com/5749229/167757256-a8834c22-2a01-4f07-b2f6-38911907eac7.gif)

**Comment by dibarbet** [comment]
cc @allisonchou

**Comment by allisonchou** [comment]
This should be resolved with the Editor's semantic token improvements
