### ISSUE TITLE
`and`/`or` should be colorized as keywords when matching enum

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61246]
Probably connected with https://github.com/dotnet/roslyn/issues/61245

**Version Used**:
Latest main (https://github.com/dotnet/roslyn/commit/e6b5dd830f1b790bd80e62272129cc040d0a2fdc)

**Steps to Reproduce**:
```cs
var a = DayOfWeek.Monday;

if (a is DayOfWeek.Friday and )
{
    
}
```
**Expected Behavior**:
`and` is treated as keyword. The same behaviours as in `if (a is 0 and )`, where `and` is a keyword that starts new pattern part

**Actual Behavior**:
`and` is treated as local variable

**Comment by sharwell** [comment]
This will be interesting to fix, since this appears syntactically the same as:

```
expression is TypeName variableDeclaration
```

**Comment by DoctorKrolic** [comment]
@sharwell Why not to fix this on compiler side? I think, it is enough context here to say, that `and` is a keyword. I gave an example of `if (a is 0 and )`, where we match to constant `0`, so it is clear, that `and` is a keyword, and it already works this way. `DayOfWeek.Friday` is constant as well, so IMO this 2 examples are semantically equal

**Comment by CyrusNajmabadi** [comment]
> and is treated as local variable

Isn't that expected. This was legal code prior to the introduction of `and/or` patterns, and must remain legal for back compat:

```c#
        object o = null;
        if (o is System.String and)
        {

        }
```

So the compiler is likely doing the right thing.  It's up to the IDE to provide a good experience around features here though, including understanding if the user is partially writing something and intends to add more that turns this into another legal constructor (where `and/or` then become keywords).

**Comment by DoctorKrolic** [comment]
> the parser operates on syntax only

I didn't know that. I thought we have enough semantic context to mark `and` as a keyword. I meant only this specific case with enums and `o is System.String and` should remain legal ofc. 

> It's a deep part of the design of roslyn and is effectively sacrosanct.

It's a pity(

**Comment by CyrusNajmabadi** [comment]
>It's a pity(

Imagine if it wasn't htis way.  Now parsing has to be impacted by the entire cost of semantics, which can be *several orders of magnitude* (no exaggeration) more expensive.  It also means you can't parse a file independently, and that *every cahnge you make* must reparse and rebind *every other file* if their parsing could be affected by semantics.

**Comment by CyrusNajmabadi** [comment]
It depends on which feature you're talking about.  If it's "diagnostics", that would be at the compiler layer.  If it's IDE features, it woudl be at the IDE layer.

All i'm saying is that there is no world where the syntax tree will change here.  THe parser is parsing correctly.  It's up to things higher to decide what to do in this semantically broken (but syntactically correct) case.

**Comment by RikkiGibson** [comment]
Agree that it doesn't make sense to change the parse here. Are there editor features that are not functioning as well as they could because of this parse? Are there some changes in how pattern syntax is inspected which would make some editor behaviors better?

**Comment by CyrusNajmabadi** [comment]
Closing out.  the behavior here is totally fine.  The keyword is classified as such when it's known to be a keyword.  In a broken intermediary state it is classified as an identifier.  This is normal and common with many of our constructs.
