### ISSUE TITLE
Convert to raw string doesn't offer to change semantics if there is only whitespace at the end of the string

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#61267]
When there is no whitespace at the start of a string, we don't offer the ".. and remove whitespace" refactoring for Convert to Raw String. Given that the refactoring changes whitespace at the end, this becomes slightly painful in some circumstances.

For example, in Razor we have lots of tests that look like this:

```
var input = @"
first line
second line
";
var expected = @"first line
second line
";
```

For `input` we can use the semantic changing refactoring, but for `expected` we don't. This means that after doing the whitespace-removing refactoring on `input`, we have to do the normal refactoring on `expected`, and the results don't match, so the tests don't pass. We end up with:

```
var input = """
first line
second line
""";
var expected = """
first line
second line

""";
```

Seems like if the whitespace-removing refactoring is going to adjust trailing whitespace, then it should be offered whenever there is trailing whitespace, so then things are consistent.

Yes, I could just use the non-whitespace-removing refactoring on `input`, but I do want the whitespace removed.

**Comment by CyrusNajmabadi** [comment]
Yup. That seems reasonable to tweak
