### ISSUE TITLE
Add aliases informations to deps.json.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/roslyn#61271]
Since I think roslyn is responsible for the deps.json file generation I have linked this issue here : https://github.com/dotnet/runtime/issues/69245#issue-1233900214

**Comment by CyrusNajmabadi** [comment]
Not sure what you're asking for. Can you give an example of when this would be needed and what you would like to see in deps.json.

**Comment by malylemire1** [comment]
It's actually a problem found in Razor runtime compilation : https://github.com/dotnet/aspnetcore/issues/41632#issue-1232925234

**Comment by CyrusNajmabadi** [comment]
Can you clarify what you would like roslyn to do here?  An example of what you are talking about would be very helpful. Thanks!

**Comment by malylemire1** [comment]
Simply adding and alias value if found in csproj for each reference.
`"MyPackage": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-I68Jl/Vs5RQZdz9BbmYtnXgujg0jVd61LhKbyNZOCm9lBxZFGxLbiQo6yFj21VYi7DzPvEvrVOmeC6v41AoLfw==",
      "path": "path",
      "hashPath": "MyPackage.nupkg.sha512",
      "alias": "MyPackageAlias"	
    },
    "MyProject/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
      "alias": "MyProjectReferenceAlias"
    },`

**Comment by CyrusNajmabadi** [comment]
If this were to be done, it seems like it would be the project system, msbuild, or some other identity responsible for deps.json generation. I'm not sure what Roslyn would do here. For example, afaict, Roslyn had no knowledge of nuget packages. They've all been unpacked by the time they get to us.

**Comment by rainersigwald** [comment]
This is best tracked as https://github.com/dotnet/sdk/issues/25386.
