### ISSUE TITLE
Code Style: use block body for accessors: doesn't format correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61279]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Style:-use-block-body-for-accessors/10038542)._

---
[severity:It bothers me. A fix would be nice]
Given a property like the following:

```
public int Foo { get => _foo; set => _foo = value; }
```

Applying "use block body for accessors" to the setter results in the following formatting:

```
public int Foo
{
    get => _foo; set
    {
        _foo = value;
    }
}
```

Notice that the "set" keyword has not been pushed to the next line. I expect this:

```
public int Foo
{
    get => _foo;
    set
    {
        _foo = value;
    }
}
```

If you apply the refactoring to the getter first and then the setter, it formats correctly.

---
#### Feedback Bot on 5/11/2022, 08:19 PM: 

(private comment, text removed)
#### Gordon Tyler on 5/12/2022, 05:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by doxxx** [comment]
Reproducing my additional comment which was removed above:

This property started out as an auto-property:

```
public int Foo { get; set; }
```

However, I needed it to generate property change notifications.

First, I applied the “convert to full property” quick action:

```
public int Foo { get => _foo; set => _foo = value; }
```

Then I applied “use block body for accessor” to the setter, which lead to the bad formatting in my original post.

If I apply it to the getter first, it formats like so:

```
public int Foo { get { return _foo; } set => _foo = value; }
```

I’d actually prefer this to be formatted like so:

```
public int Foo
{
    get
    {
        return _foo;
    }

    set => _foo = value;
}
```

But the only code style option for that is to turn off “leave block on single line”, which also affects the original auto-property form which I’d prefer to always stay on a single line. I think there needs to be separate rules for which block constructs should be left as one line.

It would be super awesome if there was a quick action to convert an auto property into a full property with property change notifications, if the current type implements INotifyPropertyChanged. It should re-use an existing OnPropertyChanged helper method if it already exists.
