### ISSUE TITLE
C# Code Generator and Code Analyzer don't Recognize Nested Enum as Belonging to Current Generic Class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61281]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Code-Generator-and-Code-Analyzer-don/10039068)._

---
[severity:It bothers me. A fix would be nice]
Auto-generation of a code snippet with an enum nested in a generic class adds the identifier of the class we're in as superfluous qualifier.

Sample code:

```
namespace DemoCodeAnalyzerOnNestedEnum
{
    internal class DemoClassWithNestedEnum
    {
        public enum DemoNestedEnum
        {
            First,
            Second
        }

        public static string DemoNestedEnumUsage()
        {
            var demoNestedEnumValue = ((new Random()).Next(2) == 0) ? DemoNestedEnum.First : DemoNestedEnum.Second;

            switch
        }
    }
}
```
Put the cursor immediately behind the keyword "switch", press [Tab], replace the selected "switch_on" by "demoNestedEnumValue", and press "Enter". 

Observed result (switch block only):

```
            switch (demoNestedEnumValue)
            {
                case DemoClassWithNestedEnum.DemoNestedEnum.First:
                    break;
                case DemoClassWithNestedEnum.DemoNestedEnum.Second:
                    break;
                default:
                    break;
            }
```
Expected result (switch block only):

```
            switch (demoNestedEnumValue)
            {
                case DemoNestedEnum.First:
                    break;
                case DemoNestedEnum.Second:
                    break;
                default:
                    break;
            }
```

With a non-generic class, the code generation runs just fine.

Not only the code generator, but also the code analyzer has a flaw here: it doesn't issue a message "Simplify member access (IDE0002)". (In a non-generic class, it does.)

---
#### Feedback Bot on 5/11/2022, 10:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
Cannot repro (https://github.com/dotnet/roslyn/commit/a27a56aa948b7cc3fbf8212b36305eb7a1260b10):
![kauZ6sCyUA](https://user-images.githubusercontent.com/70431552/173065918-5741e9a6-dd89-4367-a98c-af32537abe9b.gif)

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Can you please double-check and verify if this bug is currently reproducible or not? I don't trust myself after several false-positives recently...

**Comment by CyrusNajmabadi** [comment]
Your verification looks good to me :)

**Comment by DoctorKrolic** [comment]
It is better to close this issue as "not planned" I suppose:
![firefox_3ZJ9UnIgZm](https://user-images.githubusercontent.com/70431552/174423661-1a609384-bc0e-4560-b144-cf7b566fabd6.png)
