### ISSUE TITLE
It looks like the "implement interface explicitly" option doesn't spit out static modifier for static events and properties.

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#61311]
It looks like the "implement interface explicitly" option doesn't spit out static modifier for static events and properties.

_Originally posted by @AlekseyTs in https://github.com/dotnet/roslyn/issues/53925#issuecomment-1124383100_

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/65063
