### ISSUE TITLE
Improve `ru` localization for IDE0059 codefix

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61325]
IDE0059 codefix is about removing redundant assignment. The original name is `Remove redundant assignment` and the translation is `Удалить избыточные операторы назначения`. The word `операторы` is redundant here 😄. If to translate back to English it will become `Remove redundant assignment operators`. So translation can be simplified here, and become just `Удалить избыточное назначение`. Is will stay sensible and readable.

Edit: As mentioned in one of the comments below, `assignment` can be translated even better and become `присваивание` insted of `назначение`

So I request these changes in the end:
In https://github.com/dotnet/roslyn/blob/main/src/Analyzers/Core/CodeFixes/xlf/CodeFixesResources.ru.xlf:
```diff
<trans-unit id="Remove_redundant_assignment">
  <source>Remove redundant assignment</source>
- <target state="translated">Удалить избыточные операторы назначения</target>
+ <target state="translated">Удалить избыточное присваивание</target>
  <note />
</trans-unit>
```

**Comment by DoctorKrolic** [comment]
Again, I would like to be aware of the state of this request, so please let me know here when this is passed to a localization team.

**Comment by CyrusNajmabadi** [comment]
@JoeRobich can you help with this as well?  Thanks!

**Comment by vorotynsky** [comment]
I think `оператор присваивания` (or `присваивание`) is clearer than `оператор назначения` (or `назначение`).

Check the translation:
 - [Assignment from wikipedia](https://en.wikipedia.org/wiki/Assignment_(computer_science)) and the [same article in russian](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D1%81%D0%B2%D0%B0%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5).
 - MSDN: [Assignment operators (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/assignment-operator) and [the russian translation](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/assignment-operator).

**Comment by DoctorKrolic** [comment]
@vorotynsky It definitely is, nice suggestion!

**Comment by JoeRobich** [comment]
Opened issue for this string.
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/610226 (microsoft)

**Comment by JoeRobich** [comment]
Internal issue is reported as Resolved. LOC strings will be updated closer to the release of 17.3.
