### ISSUE TITLE
User-defined conversion does not work on Generics of interfaces

### ISSUE THREAD

**Issue by arontsang** [dotnet/roslyn#61339]
**Version Used**: dotnet 5

**Steps to Reproduce**:

```
void Main()
{
	IBar bar = null;
	Foo<IBar> fooBar = bar;
}


public class Foo<T>
{
	public T Value {get;}
	
	public Foo(T value){ Value = value;}
	
	public static implicit operator Foo<T>(T value) => new Foo<T>(value);
}

public interface IBar
{
	
}
```

**Expected Behavior**:
bar is implicitly converted into `Foo<IBar>`
**Actual Behavior**:
compiler exception. CS0029 Cannot implicitly convert type `IBar` to `Foo<IBar>`.

**Comment by svick** [comment]
This behavior is correct per [the spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#14104-conversion-operators):

> User-defined conversions are not allowed to convert from or to *interface_type*s. In particular, this restriction ensures that no user-defined transformations occur when converting to an *interface_type*, and that a conversion to an *interface_type* succeeds only if the `object` being converted actually implements the specified *interface_type*.
