### ISSUE TITLE
IntelliSense/Auto-complete off-by-one on overload count on members of lambda argument objects

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn#61343]
**Version Used**: 17.2.0, 17.3.0 P1

**Steps to Reproduce**:

1. Invoke a method taking in a lambda with at least one parameter (eg. most LINQ methods (`things.Select(t => ...)`), or `String.Create(42, someObj, (span, obj) => ....)`
2. Inspect the members of any of the passed-in objects inside the lambda

**Expected Behavior**:
The counter for overloads should be accurate in the sense that it shouldn't count the first member signature in the quick info box, since if a member name occurs only once, it's not overloaded. And because the text has always been `(+ X overloads)`, it stands to reason that `X` should be `n - 1` of the amount of members with that name, and none of the text if `X == 0`.

**Actual Behavior**:
The box includes the signature already displayed in its count, thus believing everything has an overload, including non-overloaded and non-overloadable members, such as properties:
![image](https://user-images.githubusercontent.com/1058562/168560022-25cd0801-9deb-4b7c-be1e-5d9bf85c586b.png)

**Comment by Neme12** [comment]
I can repro this too.
![image](https://user-images.githubusercontent.com/11444821/168572764-6c81f499-a1d2-4683-8c39-3b549113323a.png)
