### ISSUE TITLE
Convert to interpolated string adds (object) to everything

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61346]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Convert-to-interpolated-string-adds-obj/10041793)._

---
[severity:It's more difficult to complete my work]
Since the latest build/update choosing "Convert to Interpolated String" adds a cast to (object) to every part of the string. For example:

```
string alarm = string.Format("{0}{1} - Id:{2}", dateTime, parse[(int)ALRFields.AlarmText], parse[(int)ALRFields.ID]);
```
becomes

```
string alarm = $"{ (object)dateTime}{ (object)parse[(int)ALRFields.AlarmText]} - Id:{ (object)parse[(int)ALRFields.ID]}";
```
or

```
throw new InvalidDataException(string.Format("Invalid data in '{0}' - no data found.", DataPath));
```
becomes

```
throw new InvalidDataException($"Invalid data in '{ (object)DataPath}' - no data found.");
```

Note that in all these examples, the parameters to string.Format were (are) strings.

---
#### Feedback Bot on 5/15/2022, 07:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
Cannot repro (https://github.com/dotnet/roslyn/commit/b1fbb442e69354081785032f9fbe65f8eb09d33f):
![0AbmZJzxGh](https://user-images.githubusercontent.com/70431552/172021018-cf7853f6-3ce0-4dc9-ad79-4a9e9b8d2aeb.png)
![yd1hvEh29s](https://user-images.githubusercontent.com/70431552/172021021-7781bc9c-92d0-4bc0-b4a1-359d681a1f22.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro, absent a fuller case that demonstrates the issue.  Thanks! :)

**Comment by StelioKontosXBL** [comment]
@DoctorKrolic, @CyrusNajmabadi - This is a very real issue that can be incredibly counter-productive in my experience also.

To reproduce, simply enable the C# nullable context setting in the project properties.

Requesting that this issue be reopened pending either:

- an explanation as to why the explicit casting to `Object` is necessary when compiling with nullable context enabled, or
- recommended steps to suppress this behavior when using intellisense to automate formatted strings to interpolated strings.

**Comment by CyrusNajmabadi** [comment]
@StelioKontosXBL can you file a small repro so we can make sure we're on the same page?

**Comment by davidwengier** [comment]
This repros for me:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/754264/173965001-9302459d-bf03-4745-ae2c-f2a39616237a.png">

**Comment by StelioKontosXBL** [comment]
> @StelioKontosXBL can you file a small repro so we can make sure we're on the same page?

With Nullable context enabled:

![devenv_NfzZV479yj](https://user-images.githubusercontent.com/37424493/173965053-8ed82ce2-6a8c-4388-b8cf-d9bcbc29efb4.png)

With Nullable context disabled:

![devenv_BcOSQKxhAr](https://user-images.githubusercontent.com/37424493/173965073-57fdfe81-43cf-4351-9127-2e685ddc255b.png)
