### ISSUE TITLE
Proposal: Always allow omission of braces for single line statements (try, catch, finally, property, get, set, etc.)

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/roslyn#6135]
Instead of:

    try
    {
      Run();
    }
    catch (Exception e)
    {
      Log(e);
    }
    finally
    {
      Close();
    }

This should be allowed:

    try
      Run();
    catch (Exception e)
      Log(e);
    finally
      Close();

Likewise,

    public string MainPhone
    {
      get
      {
        return Phones.FirstOrDefault()?.Number;
      }
      set
      {
        SetPhone(index: 0, number: value);
      }
    }

Would be much more readable as:

    public string MainPhone
      get
        return Phones.FirstOrDefault()?.Number;
      set
        SetPhone(index: 0, number: value);

Is there any problem with it?
Currently if an opening curly brace is not following the `try` or `catch` keywords it's a compile error.

I think `try`-`catch` is the only block that doesn't support inline statements. Am I wrong?

**Comment by NN---** [comment]
The only problem that try-catch is not an expression making this proposal a little bit useless.
If inline try-catch is changed to be an expression, it will be a nicer change.

old::
```cs
int i;
try
{
  i = F();
}
catch
{
 i = 1;
 }
```

new:
```cs
var i = try F(); catch 1;
```

**Comment by weitzhandler** [comment]
@NN--- 
I would stick to the original non-expression version.
A `for`, `foreach`, `do-while` statements are all non-expression blocks that allow inline statements.

**Comment by NN---** [comment]
In that case there is no real advantage of removing braces.
You can inline braces in one line for short statement.

**Comment by alrz** [comment]
addressed by #5402.

**Comment by gafter** [comment]
What is the motivation for the proposed change? Why is it a good idea at all?

**Comment by gafter** [comment]
@weitzhandler 

It looks ambiguous.

```cs
  try
      try
        S1;
      catch (E1 e1)
        S2;
  catch (E2 e2)
    S3;
```

**Comment by weitzhandler** [comment]
@gafter 
This is also looks ambiguous, but as long as the rules are clear there is no problem:
    if (x)
      if(y)
        Go();
      else
        Remove();
    else
      Throw();

I understand this is not a very essential feature, but I like to keep single-liners without braces, and the try blocks break my coding patterns...

**Comment by weitzhandler** [comment]
I am still hoping one day this will be addressed, I'm hoping to see more love for single-lines.
It makes no sense to waste two lines and redundant braces when you have try-catch blocks that execute a single statement.
And the truth is, I'd really hope to see this implemented for properties as well.

    public string MainPhone
    {
      get
      {
        return Phones.FirstOrDefault()?.Number;
      }
      set
      {
        SetPhone(index: 0, number: value);
      }
    }

Would be much more readable as:

    public string MainPhone
      get
        return Phones.FirstOrDefault()?.Number;
      set
        SetPhone(index: 0, number: value);

I'd say the omission of braces should be supported anywhere for single-line statements.

**Comment by gafter** [comment]
Do I need to assign this to the "When Heck Freezes Over" milestone and leave it open?

**Comment by alrz** [comment]
LMAO.

**Comment by weitzhandler** [comment]
I hope heck DOES freeze and this issue gets implemented.

**Comment by paulomorgado** [comment]
I hope Heck freezes and stay froze forever.

There are horror stories out there for C-like languages that allow block and single statements. C# did very well by not allowing that for new features.

**Comment by aluanhaddad** [comment]
:-1:
