### ISSUE TITLE
Renaming moves focus to a different editor, doesn't rename

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#61357]
This is exceedingly weird, but I have two editor windows open, side by side, and when trying to rename something in the file on the right, I don't get the rename pop up but instead focus is shifted to the editor on the left. If I rename something in the file on the left it works fine.

This repros whether I use F2, Ctrl+R, R or the right click menu item, as you can see in the GIF.

![RenameFocusBug](https://user-images.githubusercontent.com/754264/168718676-0f336a91-0214-4795-b426-43f1913cda7f.gif)

@ryzngard

**Comment by davidwengier** [comment]
Just noticed, when I try to rename something on the left, focus shifts to the right, and vice versa, ad infinitum :)

**Comment by ryzngard** [comment]
Jedi mind tricks: "This is not the rename you're looking for..."

**Comment by tamlin-mike** [comment]
Could this be an incarnation of the long-standing bug that when using keyboard shortcuts, the _action_ is performed on any element (token) the mouse cursor - even in single-document scenarios - happens to be over?
If so, AFAIK only known way to avoid this is to always manually make sure the mouse cursor is not hovering over any edit area; chances that will ever get fixed are by now asymptotically approaching 0%.

Footnote:
The following information could by some be considered impolite, to the extent they ignore it's verifiably true.
Having **two** documents open at the same time (*gasp*) could be considered by the "Visual Studio Team" (which based on comments on Developer Community can be among the dullest tools in the shed) an "Advanced Feature", and as such not a supported scenario. Visual Studio is by their priorities first and foremost intended to help beginners and simpletons - it is explicitly designed to discourage, prevent, and outright sabotage advanced uses and scenarios.

**Comment by CyrusNajmabadi** [comment]
@tamlin-mike This sort of behavior is not ok as per the .net code of conduct: https://dotnetfoundation.org/about/code-of-conduct

Importantly, please keep in mind the following:

> Demonstrating empathy and kindness toward other people

It is not acceptable to malign people in this way.  Either the people working on the product, or the large community of people that VS targets.
