### ISSUE TITLE
Referencing Microsoft.CodeAnalysis.Compilers causes dependency to netstandard.dll

### ISSUE THREAD

**Issue by 0liver** [dotnet/roslyn#61360]
**Version Used**:
```xml
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers;</IncludeAssets>
    </PackageReference>
```

**Steps to Reproduce**:

1. Add the above package reference to a .NET Framework project.
2. Build errors will force you to also add a reference to `Microsoft.CodeAnalysis.Compilers` with the same version.
3. Build the project.
4. Run the application that uses the project's DLL.

**Expected Behavior**:
I expect my application's UI to load without error.

**Actual Behavior**:
> CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

![image](https://user-images.githubusercontent.com/164360/168771666-e75642e5-1660-409d-8dba-953fdc7c0ce3.png)

We use `Microsoft.CodeAnalysis.CSharp.CodeStyle` as part of our own analyzers package which we simply reference from our client projects. We expect them to work in both .NET (Core) and .NET Framework projects.

The above setup worked with `Microsoft.CodeAnalysis.CSharp.CodeStyle` < 4.0.0, as far as I can remember, but back then the additional references to  `Microsoft.CodeAnalysis.Compilers` and  `Microsoft.Net.Compilers.Toolset` were not necessary.

**Beware**: the offending package is actually `Microsoft.CodeAnalysis.Compilers`, but that one is a necessary dependency when using `Microsoft.CodeAnalysis.CSharp.CodeStyle` in a .NET Framework project.

Side note: We currently still target .NET Framework 4.6.1, but I've tried to retarget it to all of 4.6.2, 4.7.2, and 4.8 with the same result.

**Comment by sharwell** [comment]
> Build errors will force you to also add a reference to Microsoft.CodeAnalysis.Compilers with the same version.

Microsoft.CodeAnalysis.Compilers and Microsoft.Net.Compilers.Toolset are for internal infrastructure purposes only, and not intended for general use. The Microsoft.CodeAnalysis.CSharp.CodeStyle package should not be updated to a version newer than the compiler in use for the project. The .NET SDK used by the project can be updated to use a newer version of the compiler and this package.

/cc @jaredpar

**Comment by 0liver** [comment]
Thanks. Where can I find out which compiler version I am using, and which version of `Microsoft.CodeAnalysis.CSharp.CodeStyle` would match that one? Do you have a support matrix?

**Comment by 0liver** [comment]
By the way, after updating `Microsoft.CodeAnalysis.CSharp.CodeStyle` to `4.2.0`, I could actually drop the dependency on `Microsoft.CodeAnalysis.Compilers`, and, most importantly, the resulting DLL does not need `netstandard.dll` to run, anymore.

**Comment by jaredpar** [comment]
> By the way, after updating Microsoft.CodeAnalysis.CSharp.CodeStyle to 4.2.0, I could actually drop the dependency on Microsoft.CodeAnalysis.Compilers, and, most importantly, the resulting DLL does not need netstandard.dll to run, anymore.

Correct. 

> Where can I find out which compiler version I am using, and which version of Microsoft.CodeAnalysis.CSharp.CodeStyle would match that one? Do you have a support matrix?

@sharwell will need to answer that. I was a bit surprised it just didn't already have a ref to `Microsoft.CodeAnalysis.Common`

**Comment by 0liver** [comment]
If you can't help me figure out which version I **should** be using in our .NET Framework projects, I'll just keep using the current version, especially now that the awkward inclusion of `netstandard.dll` has been fixed.

In any case, thanks for your help.

**Comment by sharwell** [comment]
It should not be necessary to reference `Microsoft.CodeAnalysis.CSharp.CodeStyle`. Setting `<EnableCodeStyleInBuild>` to true in the project file will automatically enable the version of this assembly which shipped with the compiler currently in use.

**Comment by 0liver** [comment]
With version 4.2 it is indeed not necessary anymore, even without setting `<EnableCodeStyleInBuild>` to true.
