### ISSUE TITLE
Source generator Is not found/executed

### ISSUE THREAD

**Issue by WiredUK** [dotnet/roslyn#61365]
**Version Used**:  4.2.0

**Steps to Reproduce**:

1. Create a solution with 2 projects:
2. Source generator project is
    * `netstandard2.0` 
    * References `Microsoft.CodeAnalysis.CSharp` 4.2.0 with `PrivateAssets="all"`
    * References `Microsoft.CodeAnalysis.Analyzers` 3.3.3 with `PrivateAssets` and `IncludeAssets` elements
    * It contains a single class that implements `ISourceGenerator`, has a `[Generator]` attribute and outputs a simple static cs file.
3. Consuming project is:
    * `net6.0`
    * References the source gen project with `OutputItemType="Analyser" ReferenceOutputAssembly="false"`
 
See this minimal repo as an example: https://github.com/WiredUK/SourceGenTesting

**Expected Behavior**:
The source generator should run and allow me to use the generated code in the consuming project.

**Actual Behavior**:
Absolutely nothing happens, the source generator doesn't even show in the consuming project as an analyser (screenshot in example repo). Adding `throw new Exception()` or `Debugger.Launch()` in the source generator also doesn't do anything.

**Comment by chsienki** [comment]
Hi @WiredUK 

You have a typo in `ConsoleApp.csproj`. It should be Analy **_z_** er not Analy **_s_** er. 

```diff
-    <ProjectReference Include="..\MySourceGenerator\MySourceGenerator.csproj" OutputItemType="Analyser" ReferenceOutputAssembly="false"/>
+    <ProjectReference Include="..\MySourceGenerator\MySourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
```

As a fellow brit, I feel your pain :)

**Comment by WiredUK** [comment]
You're a gent, cheers @chsienki!
