### ISSUE TITLE
Calling ReplaceNode/ReplaceNodes on the Type specifier of a DeclarationPatternSyntax results in losing a space

### ISSUE THREAD

**Issue by nloum** [dotnet/roslyn#61371]
**Version Used**: 

4.2.0

**Steps to Reproduce**:

1. Get a SyntaxTree that contains a DeclarationPatternSyntax. E.g., `if (blah is Foobar foobar) ...`
2. Use the [ReplaceNode](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnodeextensions.replacenode?view=roslyn-dotnet-4.2.0) to replace the `Foobar` with a different type
3. Look at the modified syntax tree

Minimal working example:

```
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

var input = @"object thing = ""test"";
if (thing is IEnumerable<char> str) {
    Console.WriteLine(str);
}";

var tree = CSharpSyntaxTree.ParseText(input);

SyntaxNode needle = null;
SyntaxNode replacement = null;
var root = tree.GetRoot();
foreach (var descendantNode in root.DescendantNodes().OfType<DeclarationPatternSyntax>())
{
    needle = descendantNode.Type;
    replacement = PredefinedType(Token(SyntaxKind.StringKeyword));
}

var rootWithSyntaxError = root.ReplaceNode(needle, replacement);

Console.WriteLine(rootWithSyntaxError.ToString());
```

**Expected Behavior**:

The declaration pattern should be updated like this:

```
object thing = "test";
if (thing is string str) {
    Console.WriteLine(str);
}
```

**Actual Behavior**:

The declaration pattern is mangled so that there is no space between the type and the new variable name. Notice the `stringstr` in the output of the minimal working example:

```
object thing = "test";
if (thing is stringstr) {
    Console.WriteLine(str);
}
```

**Comment by CyrusNajmabadi** [comment]
This is expected, got didn't preserve the trivia when copying the value over.

**Comment by CyrusNajmabadi** [comment]
specifically. There is a space after the type that needs to be there to not have an issue here.

**Comment by nloum** [comment]
Oh that makes sense, thank you for the explanation!

**Comment by Neme12** [comment]
@nloum You can try this:
```c#
var newRoot = root.ReplaceNode(needle, replacement.WithTriviaFrom(needle));
```
This will make sure that the new node has the same trivia as the original one. Trivia are things like whitespaces, comments etc.
