### ISSUE TITLE
[Bug] 'ref this' argument in a structure isn't work when translate to VB.net.

### ISSUE THREAD

**Issue by RevensofT** [dotnet/roslyn#61374]
**Steps to Reproduce**:
```vb
Module ref_test

  Structure store
    Friend value As Integer
    Sub initialize()
      initialization(Me)
      ' It should be equally to { initialization(ref this) } in C#.
    End Sub
  End Structure

  Sub initialization(ByRef Data As store)
    Data.value = 123
  End Sub

  Sub main()
    Dim Data As New store

    Data.initialize()
    Console.WriteLine($"{Data.value}") ' Output: 0

    initialization(Data)
    Console.WriteLine($"{Data.value}") ' Output: 123
  End Sub

End Module
```

**Expected Behavior**:
 Data.initialize's output should be 123.

**Actual Behavior**: 
 Data.initialize's output is 0.

**Comment**:
I think it might be because out of update compile code of VB.net in structure's instance method because it can be done in C# and it doesn't broken anything language rule in VB.net.

**Comment by AlekseyTs** [comment]
Here is a couple of relevant quotes from the language specification:


>9.2.5.2 Reference Parameters
>...
>Copy-in copy-back. If the type of the variable being passed to a reference parameter is not compatible with the reference parameter's type, **or if a non-variable (e.g. a property) is passed as an argument** to a reference parameter, or if the invocation is late-bound, then a temporary variable is allocated and passed to the reference parameter. The value being passed in will be copied into this temporary variable before the method is invoked and will be copied back to the original variable (if there is one **and if it's writable**) when the method returns.

>11.4.3 Instance Expressions
>An instance expression is the keyword Me. It may only be used within the body of a non-shared method, constructor, or property accessor. **It is classified as a value.**

To summarize.

```Me``` is a value, it is not writable. This can be observed by trying to assign to it:
```
Me = Nothing ' error BC30068: Expression is a value and therefore cannot be the target of an assignment.
```

When ```Me``` is passed by ref, the value being passed in is copied into a temporary variable and reference to that variable is passed to the method. Since ```Me``` is not writable, a copy-back from that temp after the invocation does not occur. Otherwise, creating that temp would be pointless.
