### ISSUE TITLE
`CopyRefAssembly` task should log the file copy

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#61383]
If the `CopyRefAssembly` task finds that the destination .dll has the same MVID as the source, it will helpfully log a message that the copy is skipped:
https://github.com/dotnet/roslyn/blob/bb11cf445557b977a26fcd10872553cd0a47a30b/src/Compilers/Core/MSBuildTask/CopyRefAssembly.cs#L66

However if it proceeds to copy the file over, it doesn't seem to log the message.

It would help for various analysis tools if it logged the same message as the MSBuild `Copy` task in case the file is copied:
"Copying ... to ..."
https://github.com/dotnet/msbuild/blob/e049bfe3dddb84270dec5fc1aaedc9664f77eb98/src/Tasks/Copy.cs#L303

**Comment by KirillOsenkov** [comment]
Ideally also log another, diag-level message that would print the source MVID and the destination MVID in case they were different, as well as the timestamp on both source and destination. This would be incredibly valuable for incremental build investigations.

**Comment by jcouv** [comment]
Thanks for the feedback. Will take a look and tag you on PR.
