### ISSUE TITLE
[Question] How do I get all the INamedTypeSymbols in a given compilation?

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#6138]
I've been trying this for about 45 minutes now, but I can't seem to figure out how to get a list of all of the `INamedTypeSymbol` available in a given compilation. I tried digging through the `Compilation.GetTypeByMetadataName` stuff, but couldn't figure it out.

I tried using `Compilation.GlobalNamespace.GetTypeMembers()` and it seems to give me all the `IModuleSymbols` that are referenced by the current project. (I see mscorlib, System.Core etc.) I then tried getting the type members inside these modules, but they were either empty or contained `PrivateImplementation` stuff.

Is there an API to get access to all the `INamedTypeSymbols` available in a compilation?

**Comment by SLaks** [comment]
You need to recurse through all of the namespaces in the global namespace

**Comment by daveaglick** [comment]
Yep - I've found the easiest way to do the recursion is with a `SymbolVisitor`:

```
// Main code
CSharpCompilation compilation = CSharpCompilation.Create(...);
GetAllSymbolsVisitor visitor = new GetAllSymbolsVisitor();
visitor.Visit(compilation.Assembly.GlobalNamespace);

// Visitor
public class GetAllSymbolsVisitor : SymbolVisitor
{
    public override void VisitNamespace(INamespaceSymbol symbol)
    {
        Parallel.ForEach(symbol.GetMembers(), s => s.Accept(this));
    }

    public override void VisitNamedType(INamedTypeSymbol symbol)
    {
        // Do what you need to here (add to collection, etc.)
    }
}
```

**Comment by SLaks** [comment]
@daveaglick You can syntax-highlight that code by wrapping it in
~~~
```C#
~~~

**Comment by SLaks** [comment]
See also http://stackoverflow.com/a/32937808/34397

**Comment by daveaglick** [comment]
@SLaks Holy cow - I had no idea I could force language highlighting. One of those simple little things I never picked up...thanks!

**Comment by SLaks** [comment]
Also, your visitor won't catch nested types.

**Comment by daveaglick** [comment]
Yeah, just left that out - there's actually a pretty full example here that does:
https://github.com/Wyamio/Wyam/blob/develop/Wyam.Modules.CodeAnalysis/AnalyzeSymbolVisitor.cs

**Comment by JoshVarty** [comment]
Thanks guys, that should be more than enough to get me started. :)

**Comment by drewnoakes** [comment]
@daveaglick that link's broken. I believe it is now:

https://github.com/Wyamio/Wyam/blob/develop/src/Wyam.CodeAnalysis/AnalyzeSymbolVisitor.cs

**Comment by daveaglick** [comment]
@drewnoakes Indeed it is! A casualty of refactoring, thanks for updating it.

**Comment by aodl** [comment]
@daveaglick  that link's broken. I believe it is now:

https://github.com/Wyamio/Wyam/blob/develop/src/extensions/Wyam.CodeAnalysis/Analysis/AnalyzeSymbolVisitor.cs

:)

**Comment by daveaglick** [comment]
...and _that_ link will probably break soon too! Here’s one that’s pegged to a specific commit so it should be evergreen:

https://github.com/statiqdev/Framework/blob/76e2d2bda014353478ae65ef179f55180b432b94/src/extensions/Statiq.CodeAnalysis/Analysis/AnalyzeSymbolVisitor.cs

**Comment by kentcb** [comment]
Hmm, maybe I'm missing something, but I did this:

```C#
        private static IEnumerable<INamedTypeSymbol> GetNamedTypeSymbols(Compilation compilation)
        {
            var stack = new Stack<INamespaceSymbol>();
            stack.Push(compilation.GlobalNamespace);

            while (stack.Count > 0)
            {
                var @namespace = stack.Pop();

                foreach (var member in @namespace.GetMembers())
                {
                    if (member is INamespaceSymbol memberAsNamespace)
                    {
                        stack.Push(memberAsNamespace);
                    }
                    else if (member is INamedTypeSymbol memberAsNamedTypeSymbol)
                    {
                        yield return memberAsNamedTypeSymbol;
                    }
                }
            }
        }
```

Now trying to evaluate whether a visitor is cleaner/better.
