### ISSUE TITLE
source link should show file info

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#61398]
**Brief description:**

When we go to definitions, we need to be clear about the information in the file

![sourcelink](https://user-images.githubusercontent.com/5714438/169197587-80be7d3a-1a91-4980-bf34-2d6f9b758adc.png)
![dll](https://user-images.githubusercontent.com/5714438/169197595-1316d483-8eae-474f-a1b9-9d51d52f5db0.png)

**Comment by davidwengier** [comment]
@Varorbc Thanks for the feedback. Putting information into the file doesn't make sense, because with Source Link you are seeing the original source file that was used to produce the referenced DLL, and its important that the content be the same for debugging purposes, so checksums match etc.

There are few pieces of information we do put in places (eg, tab caption, navigation bar etc.). Could you expand a little on what information you're looking for specifically, and what it's used for?

**Comment by Varorbc** [comment]
1.I need to know which package provides these classes?
2.I need to know the package version. Because I often encounter the problem that after the package is updated, the code is not updated after going to the definition, so I need to confirm the relevant information of the package.

**Comment by CyrusNajmabadi** [comment]
Tab-Caption seems like a reasonable starting point (if it's not too difficult to do) :)

**Comment by davidwengier** [comment]
> 1.I need to know which package provides these classes?

Unfortunately, package information is not really something that is easily resolved here. Assembly information is known, and the assembly name is in the left most navigation bar in the editor

> 2.I need to know the package version.

That is in the left most navigation bar in the editor

> Tab-Caption seems like a reasonable starting point

That is available.

For example:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/754264/169210335-40015662-d8ae-4da6-ac2c-80f54e0d1b94.png">

**Comment by Varorbc** [comment]
> Unfortunately, package information is not really something that is easily resolved here. 

Package information maybe obtained from here

![image](https://user-images.githubusercontent.com/5714438/169213716-9901eb8b-f8f2-4e0f-a32c-56a7c309c692.png)

> That is in the left most navigation bar in the editor

The package version is inconsistent

![image](https://user-images.githubusercontent.com/5714438/169213383-0d8ba936-3029-411d-8cfc-aa98fdf70c3f.png)

![image](https://user-images.githubusercontent.com/5714438/169213908-4220eef6-a93f-4687-8e3a-d6b86c594d01.png)

**Comment by davidwengier** [comment]
Yes, we're showing assembly information, so that is assmeblt version which may or may not be the same as package version depending on what the package author does.

Seems like showing the DLL path, perhaps in the tooltip for the tab, would meet your request?

**Comment by Varorbc** [comment]
Yes, because the dll path already contains packages and versions

**Comment by davidwengier** [comment]
Sounds good.

I'll update https://github.com/dotnet/roslyn/pull/61205 to include that behaviour:
![image](https://user-images.githubusercontent.com/754264/169222026-2332340e-9879-4621-9761-289371822155.png)

**Comment by Varorbc** [comment]
by the way, why is the effect of peek definition and go to definitions different?

**Comment by davidwengier** [comment]
Peek definition never shows "real" code, only ever signatures. As far as I know the only reason for this is historical, and there is certainly no technical limitation. In fact, the PR to fix it would be to change the `false` keyword to `true` here:
https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core.Wpf/Peek/DefinitionPeekableItem.cs#L81

If you want to log a new issue for to change that, we can take it to a design meeting and see what the opinion of the team is.

**Comment by Varorbc** [comment]
Thank you for your explanation. I think it would be best if it were the same
