### ISSUE TITLE
roslyn.visualstudio.integrationtests.csharp.csharpextractmethod.extractmethodwithtriviaselected is flaky

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#61407]

**Comment by Cosifne** [comment]
https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Aroslyn-integration-ci+name%3ARoslyn.VisualStudio.IntegrationTests.CSharp.CSharpExtractMethod.ExtractMethodWithTriviaSelected

**Comment by sharwell** [comment]
The feature is working fine. The exception indicates that the test harness is reading the wrong text. Porting the test to the new test project is likely to fix.

![17 52 11-CSharpExtractMethod ExtractMethodWithTriviaSelected-EqualException](https://user-images.githubusercontent.com/1408396/169386701-228da10a-6804-428a-83f0-87ae40c8ef79.png)

**Comment by CyrusNajmabadi** [comment]
this is likely me.  the feature is async (now).  so we need to wait for the async work to complete before validating the text.
