### ISSUE TITLE
Spec Inaccuracy: Identical simple names and type names can be ambiguous

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#6141]
> **§ 7.6.4.1 Identical simple names and type names**
> The two possible meanings of E.I are never ambiguous, since I must necessarily be a member of the type E in both cases. In other words, the rule simply permits access to the static members and nested types of E where a compile-time error would otherwise have occurred.

This statement has never been true; since C# 1.0, there have been cases where this rule introduced ambiguities and created compile-time errors where there otherwise would not have been.

```C#
class E {
	void I(int a, long b) { }
	static void I(long a, int b) { }

	class C {
		E E;
		C() { E.I(0, 0); }
	}
}

```

**Comment by gafter** [comment]
@SLaks The rule in this case does not result in ambiguity in name lookup, it results in a method group. The ambiguity you see is an overload resolution ambiguity, not a name lookup ambiguity.

**Comment by gafter** [comment]
I'm moving this issue to the ECMA site. https://github.com/ECMA-TC49-TG2/spec/issues/435

**Comment by SLaks** [comment]
Why is that private?

So an ambiguity in name lookup would mean that ambigous between (eg) a method and a type?
I see.

**Comment by gafter** [comment]
It is private because that's the way the ECMA thing is run.

Do you want me to see if I can get you invited to the ECMA team?

**Comment by SLaks** [comment]
That'd be awesome, although I'm not sure how much time I'll have for it.
