### ISSUE TITLE
EnC: editing around try-catch block in top-level local function does not work

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#61415]
**Version Used**: 
Version 17.3.0 Preview 1.0 [32421.362.main]

**Steps to Reproduce**:

```C#
F();

void F()
{
    // System.Console.WriteLine(1);
    try
    {
        G();
    }
    catch
    {
    }
}

void G()
{ // breakpoint here
}
```

Place breakpoint as indicated.
Once hit, uncomment `// System.Console.WriteLine(1);` and apply changes.

**Expected Behavior**:
Change is applied.

**Actual Behavior**:

Rude edits reported:

ENC0060: Adding try block around an active statement requires restarting the application.
ENC0061	Deleting try block around an active statement requires restarting the application.

![image](https://user-images.githubusercontent.com/41759/169400251-137ee02c-7c12-4632-aae8-acf6460fb654.png)

**Comment by davidwengier** [comment]
Looks like a limitation of how we compute edits for lambdas and local functions. The matches just contain the local function body, whereas for a normal method they contain the try..catch expression itself.

Guess we need to ignore the exception region check bits that are in local functions/lambdas, and then check them when doing the actual body matches for them.

**Comment by davidwengier** [comment]
lol nevermind this is just a typo
