### ISSUE TITLE
Opening the interactive window hits debug assertion in CSharpSemanticModel.GetImportScopesCore

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61426]
**Version Used**: 
Using VS main - 
![image](https://user-images.githubusercontent.com/5749229/169425307-0531f28c-7cd5-4c59-8aca-5f990a9b9167.png)

Using Roslyn commit - 2fd58951039e953cbd5a3735c8eb8426d35a4cfe

**Steps to Reproduce**:

1.  F5 Roslyn at the commit above
2.  Open a C# project
3.  Open the interactive window
4.  Wait a sec, then you'll see the following debug assertion (a couple more popup afterwards as well) - https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs#L5304
5. ![image](https://user-images.githubusercontent.com/5749229/169425023-d851c521-95ae-4869-86bd-85d7cdb4e81a.png)

**Comment by dibarbet** [comment]
cc @CyrusNajmabadi (from commit history)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63419.
