### ISSUE TITLE
Necessary imports should be added when inlineHints are applied

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#61438]
Double clicking inline hints which replace `var` with a type name do not add using directives when necessary.

**Steps to Reproduce**:

1. Create a new console app
2. Add a new class named OtherClass.cs with the following:
```c#
using System.Collections.Immutable;

namespace ConsoleApp;

internal class OtherClass
{
    public static ImmutableDictionary<string, string> GetNameMap()
        => ImmutableDictionary<string, string>.Empty;
}
```
3. Replace the code in Program.cs with the following:
```c#
var nameMap = ConsoleApp.OtherClass.GetNameMap();
```
4. With inline type hints for `var` enabled you should see the following:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/611219/169595810-d5dc9610-741d-438c-8e13-2b9885d8b9ac.png">
5. Double click the inline type hint to apply the text to the document.

**Expected Behavior**:
`var` is replaced with `ImmutableDictionary<string, string>` and a `using System.Collections.Immutable;` using directive is added.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/611219/169596743-6051f7d6-2eae-4836-b54b-6dfd9e75ca2e.png">

**Actual Behavior**:
`var` is replaced with `ImmutableDictionary<string, string>?` which is error squiggled.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/611219/169596047-39eb0a87-ef19-4daf-a1cf-720295799718.png">

**Additional Thoughts**:
The VS Code implementation of this behavior supports associating multiple TextEdits with each inlay hint. Currently Roslyn supports a single TextEdit.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
