### ISSUE TITLE
Required Members VB Support

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#61435]
Tracking bug for determining what level of support VB will have for required members.

Scenarios to consider:
- object creation
- OHI

Relates to test plan for "required members": https://github.com/dotnet/roslyn/issues/57046

**Comment by mrange** [comment]
Hi. Just FYI to me objection creation seems important as I am now struggling to create classes in VB that has required members. Registered this issue: https://github.com/dotnet/roslyn/issues/61435
