### ISSUE TITLE
Natively supporting System.Dynamic.IDynamicMetaObjectProvider in Microsoft.CodeAnalysis.Scripting APIs

### ISSUE THREAD

**Issue by hypervis0r** [dotnet/roslyn#61445]
## Background and Motivation

I am currently working on a Domain Specific Language feature for my application, and I am utilizing the Roslyn Scripting API in order to compile, verify, and run the DSL code provided. Due to the requirements of the application, I require setting arbitrary global variables for the DSL code to utilize (for example, HTTP header keys/values). I also think it would be interesting for the evaluated code to be able to _set_ global variables as well. After doing a bit of research, I found that `System.Dynamic.DynamicObject` and `System.Dynamic.ExpandoObject` would be effective for this, but due to the way the Roslyn Scripting API is structured, it currently would not be possible.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Scripting
{
     public abstract class Script
     {
+        public Task<ScriptState> RunAsync(dynamic globals, CancellationToken cancellationToken);
+        public Task<ScriptState> RunAsync(dynamic? globals = null, Func<Exception, bool> catchException = null, CancellationToken cancellationToken = default(CancellationToken));
     }

     public sealed class Script<T> : Script
     {
+       public new Task<ScriptState<T>> RunAsync(dynamic globals, CancellationToken cancellationToken);
+       public new Task<ScriptState<T>> RunAsync(dynamic? globals = null, Func<Exception, bool> catchException = null, CancellationToken cancellationToken = default(CancellationToken));
     }

+    public delegate Task<T> ScriptRunner<T>(dynamic? globals = null, CancellationToken cancellationToken = default(CancellationToken));
}

namespace Microsoft.CodeAnalysis.CSharp.Scripting
{
     public static class CSharpScript
     {
+       public static Task<ScriptState<T>> RunAsync<T>(string code, ScriptOptions options = null, dynamic? globals = null, Type globalsType = null, CancellationToken cancellationToken = default(CancellationToken));
+       public static Task<ScriptState<object>> RunAsync(string code, ScriptOptions options = null, dynamic? globals = null, Type globalsType = null, CancellationToken cancellationToken = default(CancellationToken));

+       public static Task<T> EvaluateAsync<T>(string code, ScriptOptions options = null, dynamic? globals = null, Type globalsType = null, CancellationToken cancellationToken = default(CancellationToken));
+       public static Task<object> EvaluateAsync(string code, ScriptOptions options = null, dynamic? globals = null, Type globalsType = null, CancellationToken cancellationToken = default(CancellationToken));
     }
}

// I don't know Visual Basic but there would be API additions to the `globals` parameters there too
```

## Usage Examples

``` C#
dynamic globals = new ExpandoObject();

// HTTP header name with associated value
globals.accept_encoding = "gzip";
await CSharpScript.EvaluateAsync<bool>("if (accept_encoding == \"gzip\") { num = 5; return true; } else { return false; }", globals: globals);

// Will print `2` on true, `1` on false.
Console.WriteLine(((IDictionary<String, Object>)globals).Count)

// Will print `5` on true, "globals.num not set" on false.
if (((IDictionary<String, Object>)globals).ContainsKey("num"))
    Console.WriteLine(globals.num);
else
    Console.WriteLine("globals.num not set");
```

## Alternative Designs

Currently, I'm modeling my application feature off of a library written in Go called [govaluate](https://github.com/Knetic/govaluate). While their code evaluation isn't full compiled Go code like with the Roslyn APIs, it is still similar enough in my opinion. In `govaluate`, global variables are passed into the evaluation function as a `map`, similar to the `System.Dynamic.ExpandoObject` (which is a `Dictionary` internally).

## Risks

I'm not well experienced in the Roslyn codebase, but I would have to assume the internal APIs were not built for dynamic objects. This may require changes to the internal APIs.

**Comment by tmat** [comment]
The compiler implementation does not support dynamic lookup on global object - tracked here: https://github.com/dotnet/roslyn/issues/3194. New APIs are not needed in order to enable this kind of lookup.
