### ISSUE TITLE
Support pull mode in the DefaultDiagnosticAnalyzerService

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61442]
In order to remove the solution crawler we'll need to make the `DefaultDiagnosticAnalyzerService` support pulling for diagnostics.
See https://github.com/dotnet/roslyn/blob/5b9a9d44eee29f433d6c9ef9740642dd4d08e963/src/Features/LanguageServer/Protocol/Features/Diagnostics/DefaultDiagnosticAnalyzerService.cs#L46-L53

This is required to allow LSP to pull diagnostics from it (in non-VS scenarios).

Discussion on -
https://github.com/dotnet/roslyn/pull/61396#discussion_r877968774

**Comment by CyrusNajmabadi** [comment]
Closing as this type is gone and we are fully on pull now.
