### ISSUE TITLE
Unable to add configuration item

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#61459]
**Version Used**: 
Visual Studio 2019

**Steps to Reproduce**:
Please see the follow screenshot.

**Expected Behavior**:
Enable to add configuration item

**Actual Behavior**:
Unable to add configuration item

**ScreenShot**
![image](https://user-images.githubusercontent.com/23723575/169788989-1a6facfa-01a6-428f-adec-4e493d20e65d.png)

**Comment by Youssef1313** [comment]
@kelicto Do you mean accepting the code action doesn't modify .editorconfig (ie, it does nothing)?

If that's what you're observing, then this is a duplicate of https://github.com/dotnet/roslyn/issues/45417.

**Comment by kelicto** [comment]
Yes
