### ISSUE TITLE
In Intellisense, Parameter Descriptions Set to inheritdoc Concatenate Together

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-Intellisense-Parameter-Descriptions-/10048143)._

---
\[severity:It’s more difficult to complete my work\]  
For a parameter with the description `<inheritdoc/>`, on hover Intellisense displays descriptions for ALL parameters with the description `<inheritdoc/>`.

See attached screenshot of issue or reproduce with the following code:

```csharp
namespace Wumpty.Wump;

/// <summary>  
/// The <see cref="Foo"/> class hello worlds.  
/// </summary>  
public abstract class Foo  
{  
    /// <summary>  
    /// Initializes a new <see cref="Foo"/> instance.  
    /// </summary>  
    /// <param name="herpity">  
    /// This  
    /// </param>  
    /// <param name="derpity">  
    /// Should Not  
    /// </param>  
    /// <param name="derpderp">  
    /// Be  
    /// </param>  
    public Foo(string herpity, string derpity, string derpderp) { }  
}

public class Bar  
    : Foo  
{  
    /// <summary>  
    /// Initializes a new <see cref="Bar"/> instance.  
    /// </summary>  
    /// <param name="herpity">  
    /// <inheritdoc/>  
    /// </param>  
    /// <param name="derpity">  
    /// <inheritdoc/>  
    /// </param>  
    /// <param name="derpderp">  
    /// <inheritdoc/>  
    /// </param>  
    public Bar(string herpity, string derpity, string derpderp)  
        : base(herpity, derpity, derpderp) { }  
}
```

![image](https://user-images.githubusercontent.com/1408396/170338400-28343639-5bd7-4bca-9100-aaa5af5bad30.png)

---
#### zacharylayne on 5/19/2022, 05:21 PM: 

(private comment, text removed)
#### Feedback Bot on 5/19/2022, 08:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The bug lies in the computation of `currentName` here:

https://github.com/dotnet/roslyn/blob/8ba416dd72d8f65a353066e905940751431b6ce2/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L572-L577

When the current element includes a `name` parameter (as `<param>` does in the example), the `currentName` XPath filter should restrict the match to a corresponding element with the same name.

**Comment by zacharylayne** [comment]
Would be the bees knees if this were fixed. :)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
