### ISSUE TITLE
Convert switch statement to expression - incorrect 'OR' operator for fallthrough options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61468]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Convert-switch-statement-to-expression--/10049321)._

---
Steps to reproduce:
Use "Convert switch statement to expression" feature on this code:
    
```
private static int SwitchMethod(TestEnum testEnum)
    {
        switch (testEnum)
        {
            case TestEnum.Option1:
                return 1;

            case TestEnum.Option2:
            case TestEnum.Option3:
                return 2;
            default:
                return 0;
        }
    }
```
Incorrectly generated code: TestEnum.Option2**or**TestEnum.Option3 => 2,
    
```
private static int SwitchMethod(TestEnum testEnum)
    {
        return testEnum switch
        {
            TestEnum.Option1 => 1,
            TestEnum.Option2orTestEnum.Option3 => 2, //<--- !!!! incorrectly concatenated 'OR' operator
            _ => 0,
        };
    }
```
Expected: TestEnum.Option2 **or** TestEnum.Option3 => 2,

```
private static int SwitchMethod(TestEnum testEnum)
    {
        return testEnum switch
        {
            TestEnum.Option1 => 1,
            TestEnum.Option2 or TestEnum.Option3 => 2, // <-- notice spaces between
            _ => 0,
        };
    }
```

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.0

-cheers

---
#### Feedback Bot on 5/22/2022, 07:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
![NoRepro](https://user-images.githubusercontent.com/24360909/172677448-8a8307c0-3d74-4025-86d5-d58fbc17c436.gif)

And I am using 
![image](https://user-images.githubusercontent.com/24360909/172678002-cd0f4551-f590-4235-8118-415954ef45f1.png)
