### ISSUE TITLE
Inline Diagnostics are being omitted when there's not enough space

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/roslyn#61482]
**Version Used**: 
VS 2022, Version 17.3.0 Preview 1.1, Windows

**Steps to Reproduce**:

1. Enable the display of Inline Diagnostics
2. write code with an error
![image](https://user-images.githubusercontent.com/16213022/170088051-cbf9a7ab-6c2e-439b-8ba6-3d2eaeee5926.png)
3. zoom in so the error tag is partially hidden
![image](https://user-images.githubusercontent.com/16213022/170088181-83b56079-dd86-4702-b6d5-08bfb2605e2d.png)
5. force a redraw by scrolling down and up again
![image](https://user-images.githubusercontent.com/16213022/170088227-9c9b8812-84ad-4bc8-b3bf-80f5100d4414.png)
7. the too-long error disappears

**Expected Behavior**:
I'd want the error adornment to be visible nonetheless, just out of the viewport

**Actual Behavior**:
The error tag isn't being drawn in the first place

**Notes**
this might be because of the fix in issue https://github.com/dotnet/roslyn/issues/58501

**Comment by CyrusNajmabadi** [comment]
@akhera99 Is this the expected behavior?  Seems sensible to me that if there's not enough room, that we don't show anything.  Not sure what else we would do here.

**Comment by akhera99** [comment]
> @akhera99 Is this the expected behavior? Seems sensible to me that if there's not enough room, that we don't show anything. Not sure what else we would do here.

Yeah, that was the intended behavior from the start. I think it could be sensible to add an option to show even if it gets cut off, but I wouldn't want that to be the default behavior.

**Comment by sharwell** [comment]
Even if it gets cut off, the first part of the message generally provides enough context to understand the problem. For another view, think about what it would be like if Error List skipped the message if it didn't fit. 😄

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
