### ISSUE TITLE
Compilation error when generic type matches overload method that takes that type

### ISSUE THREAD

**Issue by WillRay** [dotnet/roslyn#6148]
This was initally found [in this StackOverflow post](http://stackoverflow.com/questions/33177145/visual-studio-2015-does-not-compile-when-generic-type-matches-overloaded-method).

The code below will compile in VS2013. However, in VS2015 it will give the following error:

> CS0534  C# does not implement inherited abstract member Validator\<object\>.DoValidate(object)

```c#
public abstract class Validator
{
    public abstract void DoValidate(object objectToValidate);
}

public abstract class Validator<T> : Validator
{
    public override void DoValidate(object objectToValidate)
    {
    }

    protected abstract void DoValidate(T objectToValidate);
}

public abstract class ValidatorBase<T> : Validator<T>
{
    protected override void DoValidate(T objectToValidate)
    {
    }
}

public class Required : ValidatorBase<object>
{
}
```

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
