### ISSUE TITLE
Visual Studio 17.3 doesn't include CS9026 in error list or IDE highlight

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#61484]
**Version Used**: 

Version 17.3.0 Preview 2.0 [32522.79.main]

**Steps to Reproduce**:

1. Create a new project targetting .NET 7.0.
2. Enable preview language features: `<LangVersion>preview</LangVersion>`
3. Add the following code:

```csharp
const string text = "hello \uD801\uD802";
byte[] bytes = text; // Error: the input string is not valid UTF16
```

**Expected Behavior**:

There should be squiggles under `bytes` because of CS9026. The Error List window in Visual Studio should include CS9026 on the 2nd line.

**Actual Behavior**:

The build (correctly) fails, but the Error List window is blank, and there's no red squiggles under `bytes`.

**Comment by vatsalyaagrawal** [comment]
@AlekseyTs when did we release this error?

**Comment by AlekseyTs** [comment]
>  when did we release this error?

17.3p1
