### ISSUE TITLE
Symbol of closed Generic Attribute does not fill `TypeArguments` with correct symbols 

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn#61490]
**Version Used**: .NET SDK 6.0.202

**Steps to Reproduce**:

```cs
using System;

public sealed class RequireStateAttribute<TState> : Attribute
    where TState : struct, Enum
{
    public RequireStateAttribute(TState state) { }
}

public enum StateEnum
{
    State1,
    State2
}

public class C
{
    [RequireState<StateEnum>(StateEnum.State1)]
    public void M() { }
}
```

1. Obtain the `INamedTypeSymbol` for the use of `[RequireState<StateEnum>]` on `C.M`

**Expected Behavior**:
The `TypeArguments` array contains the type symbol for `StateEnum`.

**Actual Behavior**:
The `TypeArguments` array contains the ***type parameter symbol*** for `TState`.
![image](https://user-images.githubusercontent.com/1058562/170102461-330c5ec7-7503-405f-9abc-9a3a8b55e568.png)
This *is* correct for the `TypeParameters` array, but not the `TypeArguments` array.

**Comment by CyrusNajmabadi** [comment]
> Obtain the INamedTypeSymbol for the use of [RequireState<StateEnum>] on C.M

Can you explain (with code) what you actually wrote to get this symbol.  Ideally, an actual repro snippet of code so we can make sure we're doing exactly what you're doing.

**Comment by Joe4evr** [comment]
> Can you explain (with code) what you actually wrote to get this symbol. Ideally, an actual repro snippet of code so we can make sure we're doing exactly what you're doing.

Sure, here it is:
```cs
public override void Initialize(AnalysisContext context)
{
    context.EnableConcurrentExecution();
    context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
    context.RegisterSyntaxNodeAction(AnalyzeNode, SyntaxKind.Attribute);
}

private static void AnalyzeNode(SyntaxNodeAnalysisContext context)
{
    if (context.Node is not AttributeSyntax attributeSyntax)
        return;

    var attrTypeInfo = context.SemanticModel.GetTypeInfo(attributeSyntax);

    // Expected: type symbol of the type used as type argument
    // Actual: type parameter symbol of 'TState'
    var tstateType = ((INamedTypeSymbol)attrTypeInfo.Type!).TypeArguments[0];
    
    // other stuff omitted for brevity
}
```

In full, line in the analyzer: https://github.com/Joe4evr/Discord.Addons/blob/MpGame4/src/Discord.Addons.MpGame/Analyzers/GameStateProviderAnalyzer.cs#L62
Failing test: https://github.com/Joe4evr/Discord.Addons/blob/MpGame4/test/MpGame.Tests/Analyzers/GameStateProviderAnalyzerTests.cs#L54-L60
Test code line: https://github.com/Joe4evr/Discord.Addons/blob/MpGame4/test/MpGame.Tests/Analyzers/SourceTexts.cs#L20

**Comment by CyrusNajmabadi** [comment]
i would expect you'd need to use GetSymbolInfo to get the constructor and use the containing type of htat.  That said, GetTypeInfo seems reasonable as well, and slightly surprising it has the wrong type.  @jcouv ?

**Comment by Joe4evr** [comment]
> i would expect you'd need to use GetSymbolInfo to get the constructor and use the containing type of htat.

I'm probably missing something about this because `GetSymbolInfo(attributeSyntax)` doesn't return anything useful:
![image](https://user-images.githubusercontent.com/1058562/170132949-60119944-f1f0-4fdf-8a4b-c7b619f8919b.png)

**Comment by CyrusNajmabadi** [comment]
YOu may not need to call this on hte name portion of hte attribute, not the attribute itself.

**Comment by Joe4evr** [comment]
So the constructor info doesn't have the type argument symbol either
![image](https://user-images.githubusercontent.com/1058562/170219167-ff488888-650a-4d96-9239-41f82f4ca838.png)

**Comment by Joe4evr** [comment]
So this works:
```cs
var stateType = context.SemanticModel.GetTypeInfo(((GenericNameSyntax)attributeSyntax.Name).TypeArgumentList.Arguments[0]).Type!;
```
But it's long and very non-obvious (and the behavior in OP most certainly still looks like a bug).

**Comment by jcouv** [comment]
@Joe4evr Something else is going on. I tried both `GetTypeInfo` and `GetSymbolInfo` and they worked (see test below).
Does your compilation have any diagnostics?

```
        [Fact, WorkItem(61490, "https://github.com/dotnet/roslyn/issues/61490")]
        public void TODO2()
        {
            var source = @"
using System;

public sealed class RequireStateAttribute<TState> : Attribute
    where TState : struct, Enum
{
    public RequireStateAttribute(TState state) { }
}

public enum StateEnum
{
    State1,
    State2
}

public class C
{
    [RequireState<StateEnum>(StateEnum.State1)]
    public void M() { }
}
";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();

            var tree = comp.SyntaxTrees[0];
            var node = tree.GetRoot().DescendantNodes().OfType<AttributeSyntax>().Single();
            var model = comp.GetSemanticModel(tree);

            var type = (INamedTypeSymbol)model.GetTypeInfo(node).Type;
            Assert.Equal("RequireStateAttribute<StateEnum>", type.ToTestDisplayString());
            Assert.Equal("StateEnum", type.TypeArguments[0].ToTestDisplayString());
        }
```

**Comment by jcouv** [comment]
@Joe4evr I didn't hear back from you. Since I wasn't able to reproduce the issue, I'll go ahead and close. Feel free to re-open if you can provide some more details. Thanks
