### ISSUE TITLE
Nullability warning disappears when commenting out *seemingly* unrelated code

### ISSUE THREAD

**Issue by mikeclayton** [dotnet/roslyn#61516]
[Update:] [sharplab repro](https://sharplab.io/#v2:EYLgtghglgdgPgWAFAAEAMACFBGAdAGVgEcBuZZAYhgFcAbWiYWgUw2ZkZfNWwDYMA9sABWzAMYAXAPwYA4swkpeACgCUyAN7IMOrAHYMMZgHdBI8RLVkkAX245+KACwYAIgIDKAsAoAWsAHM1TW5dDAA3CAAnDAAHBhgAZwwAXgwAURofKM5mXHSwWIkATwAeAAUEgD4rUN1ImIAzKFoJZijmABNUuITE7TDdXA9mFkllAcHBgHppjABhDwAOXmwATgwAOToGYBaoEsFGjA7G9vYxVhLY5mTYCIhaalYBY+vWAHJSiBgBGGKwAJqMl3iAzKJJBgAGqPZ5VD6TKa6WYYToCW4wD4SDCQCRiXwYCTRAIKQnFG4YL4/P4AoEg8nMMFCCHSaGw5jw3CIpG9H6pKqGEzcpFaJA8nkwp6sNLxH7DfFdOjMYVTOxipGqayIhqEiCJADWyTSzVa506Koww1GFgm6vFGGpMH5cgUSmCdsGmu4auQ7i8Pgk/hgQS9SGQKAATBhKj8Qh6UABmcEWGQeBWdJWI0U8kkSaw8xIKfO6NU2IA=). 

First off, apologies if this is the wrong repo to raise this issue - I posted it as [a question on StackOverflow](https://stackoverflow.com/questions/72377872/c-sharp-nullability-warning-disappears-when-commenting-out-seemingly-unrelat) originally, and a commenter suggested it's a bug, so I'm posting it here as well. Please feel free to point me in the right direction if there's a better home for it though... 

**Version Used**: 

Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.1

and

```
C:>dotnet --list-sdks
3.1.419 [C:\Program Files\dotnet\sdk]
5.0.200 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]
7.0.100-preview.4.22252.9 [C:\Program Files\dotnet\sdk]
```

**Steps to Reproduce**:

The following code in a new dotnet 6.0 Console Application project gives a nullability warning:

**ConsoleApp1.csproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

**Program.cs**

```csharp
static object? GetTask()
{
    return new object();
}

static void DoSomething()
{

    var plans = Enumerable.Empty<Plan>();

    var filtered = plans
        .Select(
            // CS8619 Nullability of reference types in value of type '<anonymous type: object Value>'
            // doesn't match target type '<anonymous type: object? Value>'.
            plan => new
            {
                Value = plan.Schedule
            }
        );

    var tasks = filtered
        .Select(
            anon => GetTask()
        );

}

DoSomething();

class Plan
{
    public object? Schedule
    {
        get;
        set;
    }
}
```

See [live demo on sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwGI8cAbMgQ2DJgAIY9raBYAKAAEAGOjgRgB0AGQCWeAI4Budu35I6EYACsYYDAH46AcRgYOSABQBKdgG92dS7wDsdPDADuC5aozHpbAL4zOfeRxQ6ABEIAGUIAFtdAAsxAHNjMx8rOgA3Sig6AAcqPABnOgBeOgBRUiioZhgBEoisjABPAB4ABVyAPndkq3TMgDMRMgwYWAATIuzcvIsUqwFQmFo1AxnZ2YB6dboAYVCADiQ+AE46ADlyKmBBkUaFPrpYPpHGMHpGrJgCsTTKMhx6CD3d70ADkTUoeAgeAaEQgOAKwJAzhUajoADVfv92iDVmsrJs6KMIJ88CCMHQIpQMGBonQMBk4ro6Q0PnQwRCoTC4QiWTAkYoURp0ZiYNiBLi8ZMIUV2nZHBK8eY2JLJRi/vRijkIfMaTBRuQYAq1t5lXijB5cb06ZQ8gBrArFAZDZ6jeaLVwrU1rDl4GXaXT6RJeujmnwm9ghcJRDCxPAJUNsWQAJjobQhSWDHAAzMjXJpQrr9axg0rJYyMB5JXldJWrCbPEA==)

The code as-is gives this warning:

![image](https://user-images.githubusercontent.com/1193763/170350415-1c0b3f55-9a6e-4c9d-aeab-6eaff5c4abaf.png)

> CS8619 Nullability of reference types in value of type '<anonymous type: object Value>' doesn't match target type '<anonymous type: object? Value>'.

but if I comment out the ```var tasks = ...``` statement the nullability warning disappears...

![image](https://user-images.githubusercontent.com/1193763/170350474-509522d2-a578-49db-b8fb-2215148c1a84.png)

It looks like the analyser is getting its knickers in a twist because it decides that the ```Value``` property of the anonymous type should be "not null" (i.e. ```<anonymous type: object Value>```) but then proceeds to create an anonymous object with a nullable ```Value``` (i.e. ```<anonymous type: object? Value>```).

It also seems to be related to the ```GetTasks``` method - if you replace ```anon => GetTask()``` with ```anon => null as object``` the nullability warning goes away as well:

![image](https://user-images.githubusercontent.com/1193763/170350516-970dc8fc-7516-475d-a58a-f519ac90d92b.png)

Additionally, moving the code out of the DoSomething method also seems to remove the warning:

![image](https://user-images.githubusercontent.com/1193763/170350575-c761daee-421c-4706-99cd-cf76d9318c39.png)

**Expected Behavior**:

I *think* the code is valid, and there should be no nullability warning.

**Actual Behavior**:

There's a nullability warning.

**Comment by mikeclayton** [comment]
**Update**

A commenter on the StackOverflow question posted another smaller, more technical MRE [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwGI8cAbMgQ2DJgAIY9raBYAKAAEAGOjgRgB0AGQCWeAI4Budu35JeKOgBEcAW1UBPABQBKOgG8AvjM595HRQDFdB9nXt0teGAHc6AYQDaAXQOGdAgDKMLRgGFpgdAC8AHx0zm76dGACAPJ0/tJsDnQA9LkeEOqMGHQQOKUYABb0zgilZGL0GBB0qpQA1vQulFB4YgDmdAAmIgDOlAAOkzC9dg4q6to6WcZssgBMHga8AMxlwABWMGEA/HSpkhnsQA===):

```csharp
#nullable enable
using System.Linq;

static void Dummy() {}

static void F() {
    (new C[] {}).Select(c => new { c.O });
    // Comment out the next line to make warning disappear
    Dummy();
}

class C { public object? O; }
```

**Comment by Neme12** [comment]
@mikeclayton It doesn't seem related to that (the other issue doesn't even look like a bug to me). This issue is likely related to local functions. If you put the methods (actually local functions) into a class, this doesn't reproduce.

**Comment by mikeclayton** [comment]
@Neme12 - you're probably much more likely to be right than me :-)

To labour the point though, this modified version of the code in #61487 gives a very similar error:

```csharp
static (string? token, int index)[] GetTokens(
    string? value, int defaultIndex
) => value?.Split(',') switch
{
    null => new[] { (null as string, defaultIndex) },
    { Length: 1 } => new[] { (value, defaultIndex) },
    { } multiple => multiple.Select((id, idx) => (id, idx)).ToArray(),
};
```

![image](https://user-images.githubusercontent.com/1193763/170363602-1f08f332-7566-426c-b24c-89fcaf476d63.png)

Here, ```value``` is a ```string?``` but  ```new[] { (value, defaultIndex) }``` seems to be resolved to ```(string token, int index)[]```.

Happy to ignore this though if it's a distraction from example ^^^ :-)

**Comment by Neme12** [comment]
@mikeclayton Sure, it's the same warning, but there, `value` is treated as non-null because if that pattern matches, that means that the `Split` method was called, which means that `value` wasn't null.

**Comment by mikeclayton** [comment]
Also, fwiw, in my original application, ```DoSomething()``` and ```GetTasks()``` are instance methods in a single class - I'm trying to extract a more representative example at the moment...

**Comment by Neme12** [comment]
@mikeclayton Could you please post a repro then where the methods are in a class? When I put them in a class, I don't get any warning: [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEA3GUCWAZgJ4A+AxAHYCuANrQIbC0wAEMlTLAsAFAACABlb8AjADoAMvkoBHANx8+/AEysAwnwDefVntYRgAKxhgMAflYBxGBn5IAFAEpd+nb32eRAdlaUYAO4GxqYYzooe+gC+SpF6/CisACIQAMoQALa2ABYyAObOrnruRV7YDFCsAA6MlADOrAC8rACiNFlQXDDiLRlVGMQAPAAKtQB84bFe+uWVhPi0GHgwACZN1bV1pdN64qkwLGYO2zueAPRnGqkAHEiiAJysAHJ0jMAL+AMGhKywhMuUMBsAZVGANGSscq0ahsCA/EFsADkgwYlAglGIGQg1AaCJAwRMZlYADUGNCYGNESdTnoLqwVhAwZRERhWBkGBgwNlWBgKnlbDziKDWMjUejMdjcUKYPjDISLCSyTDKeJqTSaqimmM/IE1ad3DTDYryesNZQ9lzVnQYHqdjE4jSnBE1bMeQw6gBrBrNeaLZYrPYHULHB2nMWULXWWz2Qqh/ROqbRPj25RqUao7SlfgAZgJoUsqUtK2tpQNO35GAipzqtirSd4USAA===)

**Comment by mikeclayton** [comment]
I'm trying to do that at the moment, but the class has a lot of dependencies so it's tricky to isolate it.

It might take a while - I'll post something as soon as I've got it...

**Comment by mikeclayton** [comment]
This is the simplest I can reduce it to at the moment - there might be more that can be removed, but if I comment out ```foreach (var task in tasks) ...``` the warning disappears:

**Engine.cs**

```csharp
namespace ConsoleApp1;

public class Plan
{
    public object? Schedule { get; set; }
}

public class Engine
{

    public void GetTasks()
    {

        var plans = Enumerable.Empty<Plan>();

        var filtered = plans
            .Select(
                // "CS8619 - Nullability of reference types"
                plan => new
                {
                    Schedule = plan.Schedule
                }
            );

        var maps = filtered
            .Select(
                plan => new
                {
                    Value = plan
                }
            );

        var tasks = maps
            .Select(
                map => GetTask()
            );

        foreach (var task in tasks)
        {
            var t = task;
        }

    }

    private object? GetTask()
    {
        return null;
    }

}
```

**CS8619 Warning**
![image](https://user-images.githubusercontent.com/1193763/170372597-908d765e-12fa-4c6b-99c1-dda5bff58d59.png)

**No Warning**
![image](https://user-images.githubusercontent.com/1193763/170372738-0610e73f-bc4f-4ac4-9394-0f0cb793aa8a.png)
