### ISSUE TITLE
A change for natural type of a UTF-8 string literal to `ReadOnlySpan<byte>` breaks several IDE tests

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#61517]
The tests will be disabled referencing this issue. It is not clear if we only need to adjust the tests, or implementation of IDE features   should change too.

The ```UseUTF8StringLiteralDiagnosticAnalyzer``` will be disabled too.

**Comment by davidwengier** [comment]
I think we need to adjust the implementation to add `.ToArray()`, correct? So instead of `byte[] b = "abc"u8` it would need to be `byte[] b = "abc"u8.ToArray()`?

Is there a branch with the compiler changes where I can do the work? Or will you just disable the analyzer when you change the compiler?

**Comment by davidwengier** [comment]
Question: Now that `.ToArray()` is required, is this still an objective advantage over `new byte[] { 65, 66, 67 }` or is there potentially a perf downside? If so, we may want to remove this from code style, and just have it be a refactoring.

**Comment by davidwengier** [comment]
Feedback from @stephentoub on the question above:

> I don't know that this makes sense as a "code style", but I think there's value in it as a refactoring. In particular:
> `Encoding.UTF8.GetString("literal")` => `"literal"u8.ToArray()`
> and
> `(ReadOnlySpan<byte>)new byte[] { (byte)'a', (byte)'b', (byte)'c' }` => `"abc"u8`
> or similar.
> 
> There's a perf benefit to the former and a readability/maintainability benefit to the latter.
> There's unlikely to be a meaningful perf difference between `new byte[] { (byte)'a', (byte)'b', (byte)'c' }` and `"abc"u8.ToArray()` but the latter is easier to read / maintain.

**Comment by Neme12** [comment]
I agree that this doesn't make sense as a code style because when the data in the array is indeed a UTF-8 string, the string literal is a clear improvement and more readable. So while I don't think it makes sense to add a code style option for this, a fix-all would be useful, which can't be done if this is just a refactoring.

**Comment by stephentoub** [comment]
> Could the compiler optimize "literal"u8.ToArray()

https://github.com/dotnet/runtime/issues/68103

**Comment by davidwengier** [comment]
> which can't be done if this is just a refactoring.

Yes it can 😛
