### ISSUE TITLE
Delegates with nint types in the signature don't get NativeIntegerAttributes anymore

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/roslyn#61525]
**Version Used**: 

.NET 7.0.100-preview.5.22274.1

**Steps to Reproduce**:

1. Compile (as a library):

```cs
delegate nint D1 (nint a);
```

2. Inspect the IL to see the NativeIntegerAttribute on the D1 members.

**Expected Behavior**:

This is the test case build with .NET 6.0.300, there are NativeIntegerAttributes on the Invoke return type and parameter, the BeginInvoke parameter, and the EndInvoke return type:

```
.class private auto ansi sealed D1
       extends [System.Runtime]System.MulticastDelegate
{
  .method public hidebysig specialname rtspecialname
          instance void  .ctor(object 'object',
                               native int 'method') runtime managed
  {
  } // end of method D1::.ctor

  .method public hidebysig newslot virtual
          instance native int  Invoke(native int a) runtime managed
  {
    .param [0]
    .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = ( 01 00 00 00 )
    .param [1]
    .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = ( 01 00 00 00 )
  } // end of method D1::Invoke

  .method public hidebysig newslot virtual
          instance [System.Runtime]System.IAsyncResult
          BeginInvoke(native int a,
                      [System.Runtime]System.AsyncCallback callback,
                      object 'object') runtime managed
  {
    .param [1]
    .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = ( 01 00 00 00 )
  } // end of method D1::BeginInvoke

  .method public hidebysig newslot virtual
          instance native int  EndInvoke([System.Runtime]System.IAsyncResult result) runtime managed
  {
    .param [0]
    .custom instance void System.Runtime.CompilerServices.NativeIntegerAttribute::.ctor() = ( 01 00 00 00 )
  } // end of method D1::EndInvoke

} // end of class D1
```

**Actual Behavior**:

No NativeIntegerAttributes anywhere:

```il
.class private auto ansi sealed D1
       extends [System.Runtime]System.MulticastDelegate
{
  .method public hidebysig specialname rtspecialname
          instance void  .ctor(object 'object',
                               native int 'method') runtime managed
  {
  } // end of method D1::.ctor

  .method public hidebysig newslot virtual
          instance native int  Invoke(native int a) runtime managed
  {
  } // end of method D1::Invoke

  .method public hidebysig newslot virtual
          instance [System.Runtime]System.IAsyncResult
          BeginInvoke(native int a,
                      [System.Runtime]System.AsyncCallback callback,
                      object 'object') runtime managed
  {
  } // end of method D1::BeginInvoke

  .method public hidebysig newslot virtual
          instance native int  EndInvoke([System.Runtime]System.IAsyncResult result) runtime managed
  {
  } // end of method D1::EndInvoke

} // end of class D1
```

According to our CI this happened between these two commits: https://github.com/dotnet/roslyn/compare/a59a22c6f3c2cc1883e20cece412209f18f4a29f...038b1a9de7cf82a66c8e57fc3262454beadbbabc

Additionally the issue doesn't seem to repro in https://sharplab.io, which is currently using https://github.com/dotnet/roslyn/commit/e6b5dd830f1b790bd80e62272129cc040d0a2fdc, so that narrows down the change to https://github.com/dotnet/roslyn/compare/e6b5dd830f1b790bd80e62272129cc040d0a2fdc...038b1a9de7cf82a66c8e57fc3262454beadbbabc, although I couldn't find any obvious candidates.

**Comment by tannergooding** [comment]
This is part of the `Numeric IntPtr` feature and is "by design": https://github.com/dotnet/csharplang/issues/6065

For .NET 7 and later (or more specifically any compilation that defines `System.Runtime.CompilerServices.RuntimeFeature.NumericIntPtr` in the "core library") `nint` is to `IntPtr` as `int` is to `Int32`. That is, they are true aliases of each other and are identical to C#. `IntPtr` has all the operators, literals, and other language support and likewise `nint` no longer gets the `NativeInteger` attribute to avoid bloating metadata unnecessarily.

The attribute will still exist and `nint` will be differentiated from `IntPtr` for .NET 6 or previous (including .NET Standard and .NET Framework).
