### ISSUE TITLE
Enhanced `#line` directives should be supported independent of language version

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#61530]
Enhanced `#line` directives (see [spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/enhanced-line-directives.md)) should be supported independent of language version.

 See [comment](https://github.com/dotnet/roslyn/issues/61094#issuecomment-1138697807).

**Comment by jcouv** [comment]
Was fixed by https://github.com/dotnet/roslyn/pull/61686. Closing
