### ISSUE TITLE
Move to namespace refactoring doesn't work with file-scoped namespace

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#61539]
Direct customer ask copying here:

> My file defines the namespace using the file scoped namespace syntax. Following the documentation instructions, I press ctrl + . when the caret is on the class identifier. The context menu that appears does not contain a "Move to namespace" choice.

> But, if I change the namespace definition to block scoped namespace, the choice appears as documented.

> Please advise on how to access this refactoring when using file scoped namespace. All my files are using file scoped namespaces, so it is not an option for me to revert to block scoped namespace syntax.

**Comment by CyrusNajmabadi** [comment]
I believe we fixed this.
