### ISSUE TITLE
C# override autocomplete should not use expression body syntax

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61543]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-override-autocomplete-should-not-use-/10052012)._

---
[severity:It bothers me. A fix would be nice]
In C#, when typing "override Method \[TAB\]", the autocomplete will suggest the following syntax. The example below uses _GetObjectData_.

```cs
public override void GetObjectData(SerializationInfo info, StreamingContext context) => base.GetObjectData(info, context);
```

For method overrides, given how common it is to call the base implementation at some point within the method, it's likely that the developer is writing imperative-style code rather than functional-style code. The autocomplete for method overrides should continue to utilize { } style syntax, as shown below.

```cs
public override void GetObjectData(SerializationInfo info, StreamingContext context)
{
    base.GetObjectData(info, context);
}
```

Then I can easily put the cursor either before or after the call to the base method and insert my logic at the appropriate place.

---
#### Feedback Bot on 5/24/2022, 06:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This behavior is controlled by the code style option "Use expression body for methods", which is found here:

![image](https://user-images.githubusercontent.com/1408396/171762433-dea4cb42-d41d-45de-b975-e75c16d30276.png)

It can also be configured via **.editorconfig**:

https://github.com/dotnet/roslyn/blob/bfe247943db8ac65220e949ff5d7d05ccb63e8c2/.editorconfig#L201-L202

**Comment by CyrusNajmabadi** [comment]
Yes.  This is by design.
