### ISSUE TITLE
Immediate Window has a data acquisition fault

### ISSUE THREAD

**Issue by kelicto** [dotnet/roslyn#61558]
**Version Used**: 
Visual Studio 2019

**Steps to Reproduce**:
This is a method(**FindNodeByFieldValue**) of the DevExpress(https://supportcenter.devexpress.com/) control that does not allow variable data to be retrieved from the window, 

**Expected Behavior**:
Failure to display data correctly

**Actual Behavior**:
Immediate Window has a data acquisition fault

**Screenshots**
![image](https://user-images.githubusercontent.com/23723575/170674123-c80fbbb2-1349-4200-8129-bab95920bcaa.png)

Note: Node objects will have an Id property, and an object ReportCs can be bound to a Node that also has an id property. They are not the same thing, even if the values are equal.

**Comment by tmat** [comment]
Does it work when you add the expression to Watch Window?

**Comment by kelicto** [comment]
I don't remember, and reproduction may be a troublesome thing.

**Comment by tmat** [comment]
Unfortunately, there is not much we can do without a repro.

**Comment by tmat** [comment]
Thanks, whenever you have a chance. Much appreciated.
