### ISSUE TITLE
Subword selection does not work in "Go to all" 

### ISSUE THREAD

**Issue by MartyIX** [dotnet/roslyn#61559]
**Version Used**: MSVS 17.3 Preview 1.1

**Steps to Reproduce**:

1. Press `CTRL+,`
2. Write `SomeClass[CaretHere]`
3. Press CTRL+ALT+SHIFT+ left arrow.

**Expected Behavior**:

`Class` part of `SomeClass` text should be selected.

**Actual Behavior**:

Nothing happens.

**Comment by CyrusNajmabadi** [comment]
Not a Roslyn issue. @olegtk can you port?

**Comment by olegtk** [comment]
Tracked as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1546914
