### ISSUE TITLE
[Flaky Build] Sample projects are picking up references from bin, sometimes causing a race

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6155]
See [log](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1167/consoleFull#429197940a82fefab-f698-416f-8fca-58544c94cd4e) 

```
CSC : error CS0009: Metadata file 'd:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\Binaries\Debug\System.Collections.Immutable.dll' could not be opened -- The process cannot access the file 'd:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\Binaries\Debug\System.Collections.Immutable.dll' because it is being used by another process. [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Samples\CSharp\RemoveUnusedParameter\Impl\RemoveUnusedParameter.csproj]
```

Notice that the test project is picking up Immutable from the bin directory, which it shouldn't be and it's  race because it gets deployed by some other project into the bin directory as per this case.

**Comment by davkean** [comment]
tag @jmarolf

**Comment by davkean** [comment]
Dropping infrastructure, this is an IDE bug or whomever owns the samples.

**Comment by jaredpar** [comment]
In this case the DLL reference is explicitly given a HintPath which is valid.  I can't see how this could be our issue that it chooses to read the Binaries\Debug directory.  

If anyone else runs into this could we get a diagnostics MSBuild log?  I think that's the only way we'll be able to track this down.

**Comment by jaredpar** [comment]
Found the problem.  PR in progress on internal repo to fix this bug.
