### ISSUE TITLE
CS1591 CodeFix does not work correctly when there is anything but OpenBraceToken

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#61562]
since #56620 was done here, I think this belongs here

**Version Used**: 
VisualStudio (with a "clean rootsuffix"): 17.2.2
DotNet: 6.0.300
**Steps to Reproduce**:

1. Create a new Solution/Project (eg ConsoleApp) with net6.0
2. we use a 2 wide 'space' smart indent; if that matters
3. in the csproj add/enable: `<GenerateDocumentationFile>true</GenerateDocumentationFile>`
4. implement/overrride abstract member. Like This:
```cs
namespace Issue; 

/// <summary>
/// Hello C1
/// </summary>
public abstract class Class1
{
  /// <summary>
  /// Hello C1.DoStuff
  /// </summary>
  public abstract void DoStuff();
}

/// <summary>
/// Hello C2
/// </summary>
public class Class2 : Class1
{
  private const int Number = 1;

  public override void DoStuff()
  {
    throw new NotImplementedException();
  }
}
```

5. Notice `Class2.DoStuff` raises CS1591
6. Invoke CodeActions on it (Alt+Enter) and choose "Excplicitly inherit documentation" and apply

**Expected Behavior**:
```cs
public class Class2 : Class1
{
  private const int Number = 1;

  /// <inheritdoc/>
  public override void DoStuff()
  {
    throw new NotImplementedException();
  }
}
```

**Actual Behavior**:
```cs
public class Class2 : Class1
{
  private const int Number = 1;
/// <inheritdoc/>

  public override void DoStuff()
  {
    throw new NotImplementedException();
  }
}
```

Notice:
 - no leading whitespace 
 - Trivia is "attached to" the bottom of member above (`Number` in this example)

**Comment by CyrusNajmabadi** [comment]
We woudl take a community contribution here.
