### ISSUE TITLE
Getting Speculative SemanticModel for method body method declaration without body (block or expression) is impossible

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#61564]
**Version Used**:  4.2.0

**Steps to Reproduce**:

Using the following repro, getting the speculative semantic model for the method body fails no matter where I put the "position":

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Testing;
using System.Collections.Immutable;
using System.Runtime.InteropServices;

string source = @"
partial class Foo
{
    public partial void Method(int i)$$;
}"; 

/* This also fails if do any of the following:
public partial void $$Method(int i);
public partial void Method($$int i);
public partial void Method(int$$ i);
public partial void Method(int $$i);
public partial void Method(int i$$);
public partial void Method(int i);$$

*/

TestFileMarkupParser.GetPosition(source, out var parsed, out int position);

SyntaxTree tree = CSharpSyntaxTree.ParseText(parsed);
Compilation comp = CSharpCompilation.Create("Test", syntaxTrees: ImmutableArray.Create(tree));

SemanticModel model = comp.GetSemanticModel(tree);

string newMethodImpl = @"
public partial void Method(int i)
{
    int j = i;
    return j;
}";

bool success = model.TryGetSpeculativeSemanticModelForMethodBody(position, (MethodDeclarationSyntax)SyntaxFactory.ParseMemberDeclaration(newMethodImpl)!, out SemanticModel? speculativeModel);
if (success)
{
    Console.WriteLine("Created model");
}
else
{
    Console.WriteLine("Failure");
}
```

**Expected Behavior**:

Prints "Created model".

**Actual Behavior**:

Prints "Failure"

**Comment by 333fred** [comment]
I wouldn't necessarily expect that to work. That's the partial declaration, not the implementation, and declarations don't have bodies.

**Comment by jkoritzinsky** [comment]
If we're emitting the partial implementation in a source generator, there's no partial implementation position we can use to get a speculative semantic model without creating a new `Compilation` object in the source generator, which can be quite expensive as I understand it.

**Comment by CyrusNajmabadi** [comment]
What are you using the speculative model for?

**Comment by jkoritzinsky** [comment]
We were considering using the semantic model to do simplification of our generated code based on the IOperation tree. Today we generate our syntax with the Roslyn syntax APIs instead of our own data model so as to reduce the amount of code we have to maintain while also providing type safety in our code generation step. However, once we generate syntax, reasoning about said syntax to simplify it based on the resulting semantics is difficult. We considered using a speculative semantic model to allow us to simplify our generated code without having to write our own semantic analysis, but we then hit this issue.

**Comment by CyrusNajmabadi** [comment]
In this case, you could just fork the compilation and do your analysis on that semantic model.

**Comment by jkoritzinsky** [comment]
My understanding is that forking the compilation in this manner is too expensive and might cause slowdowns in the IDE (one of multiple reasons why there is no dependency mechanism between source generators)

**Comment by CyrusNajmabadi** [comment]
Yes.  It can definitely cause slowdowns :)  But it sounds like you genuinely have a situation that may need to be slow.  Speculative semantics are supported for a limited set of scenarios.  By Design, its about being able to reuse *top level* information and rebind potential information *within* a method body.  If you need to determine what meaning code has *outside* of a body... then that's no longer "speculation" as defined by roslyn, and we don't have any optimization tricks we can use to help here anymore.
