### ISSUE TITLE
Prevent inline hints from being toggled after holding CTRL

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61574]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prevent-inline-hints-from-being-toggled-/10043708)._

---
Basically, as they are right now, if you hold CTRL for a little, stop and then press or hold it shortly after, inline hints deactivate/activate.

My suggestion is to cancel the command if the button is held down for a little, just like ReSharper does.

---
#### Feedback Bot on 5/16/2022, 08:21 PM: 

(private comment, text removed)
#### Feedback Bot on 5/27/2022, 10:02 AM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
Moving to the editor to change the behavior and shortcut to ctrl+ctrl.
