### ISSUE TITLE
Eliminate use of ParsingTests.UsingTree("...", verifyErrors: false)

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#61586]
it would be great if we could file a design-debt item to eliminate usages of 'verifyErrors: false', or at least move any such usages to clearly-and-ugly-named methods, e.g. `UsingTreeIgnoreDiagnostics`.

_Originally posted by @RikkiGibson in https://github.com/dotnet/roslyn/pull/61389#discussion_r878629034_

**Comment by jcouv** [comment]
@RikkiGibson @cston I placed this in Compiler.Next milestone. I'll let you adjust priority as you feel (doesn't seem urgent, but also seems cheap to fix...)
