### ISSUE TITLE
Named arguments completions are broken in C#

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61585]
**Version Used**:
VS 2022 v17.3 Preview 1.1

**Steps to Reproduce**:
```cs
M(1, b$$)

void M(int a, int b)
{

}

```
At position of `$$` invoke completions. The first item in the list will be `b:`. Accept it.

**Expected Behavior**:
```cs
M(1, b: $$)

void M(int a, int b)
{

}

```
_Note, that the space after ':' is intentional here, as having it is the propper formatting for C# code. Completion should take it into consideration_

**Actual Behavior**:
Nothing new is added to the code:
```cs
M(1, b$$)

void M(int a, int b)
{

}

```

**Additional details:**
In VB named arguments work as expected:
```vb
Class Program
    Sub A()
        M(3, b$$)
    End Sub

    Sub M(a As Integer, b As Integer)

    End Sub
End Class
```
Accepting `b:=` completion produces expected result:
```vb
Class Program
    Sub A()
        M(3, b:=$$)
    End Sub

    Sub M(a As Integer, b As Integer)

    End Sub
End Class
```
Considering this fact, I have no doubt that behaviour for C# is broken and was not planned by design

**Comment by CyrusNajmabadi** [comment]
This is intentional behavior. Only colon completes out the colon here. This was based on heavy feedback that inserting the colon was often not wanted and that inserting just the name was intentional to insert a new non-existent variable that the user would then generate a local for.
