### ISSUE TITLE
IDE0072 Add missing cases not well implemented when nullable

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/roslyn#61594]
I am not sure it is the right place to post this issue, but here it is: 

Using Visual Studio 17.1.6, adding missing cases to a switch statement on a nullable enum gives an incorrect generated code.

```
public static string ToAnotherEnum(this MyEnum? myEnumValue)
        => statut switch
        {
        }
```

This code will auto-implement the following: 

```
public static string ToAnotherEnum(this MyEnum? myEnumValue)
        => statut switch
        {
            MyEnum?.Value1 => throw new NotImplementedException(),
            MyEnum?.Value2 => throw new NotImplementedException(),
        }
```

Which seems incorrect, there should not be the `?`.

**Comment by DoctorKrolic** [comment]
Cannot repro. Full code snippet:
```cs
static class MyEnumExtensions
{
    public static string ToAnotherEnum(this MyEnum? myEnumValue)
        => myEnumValue switch
        {
        }
}

enum MyEnum
{
    Value1, Value2
}
```
Executing `IDE0072` codefix on `switch` produces:
```cs
static class MyEnumExtensions
{
    public static string ToAnotherEnum(this MyEnum? myEnumValue)
        => myEnumValue switch
        {
            MyEnum.Value1 => throw new NotImplementedException(),
            MyEnum.Value2 => throw new NotImplementedException(),
        }
}

enum MyEnum
{
    Value1, Value2
}
```
Generated code here is correct (if not count missing `;`, but it was in the original snippet as well)

**Comment by JeanCollas** [comment]
![image](https://user-images.githubusercontent.com/3519393/171836348-41048230-a710-4447-8a02-d8cffc949077.png)

![image](https://user-images.githubusercontent.com/3519393/171836071-c389fb1f-30b8-44da-b6a6-acce7fe99c30.png)
![image](https://user-images.githubusercontent.com/3519393/171836139-e69d277f-d33e-408f-8f40-dc24a4ea7d16.png)
![image](https://user-images.githubusercontent.com/3519393/171836231-dc9df37b-376e-4c56-9be2-45b066d9a197.png)

What information could I add to help locate the issue ?

**Comment by DoctorKrolic** [comment]
1. Try to reproduce it in the latest VS preview (currently VS v17.3 Preview 1.1)
2. If the issue is still there, create minimal code snippet for reproducing the problem in new empty project. Provide it here
3. If the issue depends on specific project file settings (like `Nullable`), `.editorconfig` options etc. also provide minimal examples of them here.

**Comment by davidwengier** [comment]
Confirmed this repros for me in 17.3 Preview 1.1, in a project with nullable annotations enabled.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/754264/171844578-b13aa633-8693-409e-93d1-aca70aa976ed.png">

Without the `#nullable enable` line it doesn't repro. Taking out that line but putting `<Nullable>enable</Nullable>` in the project files makes it repro again.

@DoctorKrolic Can you check and make sure you're trying in a file that has `#nullable enable` or a project that has `<Nullable>enable</Nullable>`?

**Comment by DoctorKrolic** [comment]
@davidwengier Yes, reproduced with `<Nullable>enable</Nullable>`
