### ISSUE TITLE
Async backfill for completion

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#61600]
Currently the commit phase of completion blocks until the completion finishes. While this operation is generally extremely fast, it occasionally fails to achieve the desired targets for typing responsiveness. This led to a variety of IDE operations which result in completion commit silently failing to insert text if it would otherwise take "too long":

![image](https://user-images.githubusercontent.com/1408396/171220109-21c7ad97-1d94-4a4e-a5bf-972fa666f3f2.png)

With the recent work to provide an inline UI for asynchronous post-edit (or post-command) operations that is cancellable but does not block typing, it may now be possible to develop a fully-asynchronous completion commit behavior that operates using backfill. The following sequence demonstrates how this might work:

1. The user types the first identifier character (e.g. `M`)
    1. Completion starts computing the completion list
2. The user types additional identifier characters (e.g. `yAtt`)
3. The user types a commit character (e.g. `(`)
    1. Completion dismisses the completion list and starts an asynchronous edit operation that will eventually select and insert a completion item
4. The user types another identifier character (e.g. `a`)
    1. Completion queues a request to start computing a new completion list once the previous commit operation completes or is cancelled
5. The first (now asynchronous) commit operation completes by selecting and inserting `MyAttribute`
6. A completion list appears for `a`

In most cases, the commit phase of completion is sufficiently quick that users will not notice the difference between the current blocking behavior and the new asynchronous behavior. However, this approach will allow us to close the responsiveness gap in various edge cases, and also provides a UX model which is compatible with the complete decoupling of typing from completion edits.

### Special considerations:

* The new model allows for certain optimizations that are not currently possible. For example, once a user types a commit character, there is no need to compute any information for completion items which is only used for display purposes in the completion list (it is known that no completion list will appear for this item).
* It is possible that multiple completion requests stack up together (e.g. if `.` was typed after step 6 in the previous example, and before the first commit finished). If the user presses <kbd>Esc</kbd> to cancel the background operation, it should cancel all pending completion edits at once.
* To the degree possible, moving the caret should not automatically cancel these operations.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative, a large amount of work, and somethgin that would need to be driven by the completion maanger (the editor in VS or VSCode).
