### ISSUE TITLE
Add a code fix to suggest adding `partial` modifier

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#61611]
If we just provide a code fix for this case that adds the `partial` modifier, it would be easy for the user to correct it. Also, we should make sure that if the user hits <kbd>F12</kbd> at the location of the error, they see all files defining the type.

> I'd argue the generator should report a custom error here and say that the type they're augmenting needs to have the partial modifier on it

The guidance I've been giving is source generators generally do not need to provide a diagnostic for any case where the compiler is already going to report a compilation error.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/issues/61597#issuecomment-1142368461_

**Comment by RikkiGibson** [comment]
@Neme12 let's confirm from @dotnet/roslyn-ide that you have a green light here to work on this.

**Comment by sharwell** [comment]
Yep, this is a code fix for CS0260.

**Comment by Neme12** [comment]
@sharwell Please see additional comments in #61597, @CyrusNajmabadi seems to disagree with adding this strongly.
