### ISSUE TITLE
Unable to evaluate an outer constant inside a local function

### ISSUE THREAD

**Issue by eterekhin** [dotnet/roslyn#61624]
Reproduces on Visual Studio 2022.
```csharp
namespace ConsoleApp20
{
    class Program
    {
        public static void Main(string[] args)
        {
            const string constant = "test string";
            inner();
            void inner()
            {//breakpoint is here
                
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/48148702/171386908-d863800b-f0d7-4eb1-af11-ca6a3dac6d30.png)

It might be related to [60358 issue](https://github.com/dotnet/roslyn/issues/60358)

**Comment by jcouv** [comment]
Yes, debugging and expression evaluator is limited with local functions at the moment.
If you want to see `constant`, you need to click in "Call Stack" window and select the method.
When the execution is inside the local function, the only locals that you can see in the "Locals" window are the parameters and locals of the local function.
I suspect this will remain like that (works like any other invocation), so I'll close this issue as by-design.
