### ISSUE TITLE
Show where a thrown error may be caught, akin to find usages.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61628]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-where-a-thrown-error-may-be-caught/10050334)._

---
It would be great to be able to find candidate catch blocks to where a function may throw. While "find usages" is already great to be able to see potential calls to a function and where it returns to. But finding the respective catch blocks can be far more complicated.

This would be particularly easy, if there are few potential stacks. I.e. a sub function of a large module is running. But due to its size navigation by hand is not feasible.

For my specific use case the kind of thrown error is obscured, but the error throwing function is marked [[noreturn]].

---
#### Feedback Bot on 5/23/2022, 08:27 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing duet o lack of feedback and large complexity of any solution.
