### ISSUE TITLE
Warning to programmer about sync Task return in c#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61625]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Warning-to-programmer-about-sync-Task-re/10056334)._

---
Hi,
We got a problem in programming that is an unreadable source.
See the example please:

```
    internal class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                _ = Example();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            Console.ReadLine();
        }

        static Task Example()
        {
            throw new Exception("");
        }
    }
```

In that code Example method will not run in the background, but the programmer thought it will run in the background because he added "_ =" before the code.
I have an idea to solve this problem.

We have a green line warning in this source:

![image](https://user-images.githubusercontent.com/1408396/171719953-33c67a2c-8617-4a1a-9d0d-2d147a26499c.png)

because we didn't await the Example method.

My idea is when we use "_ =" before Sync methods like "static Task Example()" visual studio shows that green warning to the programmer, then he will know the code will not run in the background, so exceptions will throw in the main method.
This will prevent programmer mistakes.
Thanks.
Best regards.
Ali.

---
#### Feedback Bot on 5/30/2022, 00:17 AM: 

(private comment, text removed)

**Comment by sharwell** [comment]
I'm concerned that many misconceptions may have occurred in the formation of this feature request.

The request mentions "synchronous" and "background" calls. Note that even methods with `async` can execute synchronously, and `async` methods that yield might still not execute in the background.

It may help to start here:
https://blog.stephencleary.com/2016/12/eliding-async-await.html
