### ISSUE TITLE
Add convert unused parameter to discard to code cleanup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61627]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-convert-unused-parameter-to-discard-/10040700)._

---
Visual studio highlights unused parameters with error code IDE0058 and suggests converting them to discard '_' which is great. However, there's no step as part of code cleanup to do this automatically.

It would be great if code cleanup could swap these automagically (if configured to do so)

---
#### Feedback Bot on 5/12/2022, 07:35 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of feedback.
