### ISSUE TITLE
Code cleanup (C#) with new line preferences doesn't remove all empty lines

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#61629]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-cleanup-C-with-new-line-preferen/10049313)._

---
Hello,
I enabled the code cleanup setting to remove (multiple) empty lines, but there are some cases where the empty line is not removed.

Case 1:
If you have (multiple) empty lines after the last statement of a method, before the closing } then one last empty line will still be there after the cleanup, it would be better if there is no empty line between the last statement and the closing }

Example:

```
public void SomeMethod()
{
    LastStatement();



}
```

Should be changed to:

```
public void SomeMethod()
{
    LastStatement();
}
```

instead of the current result:

```
public void SomeMethod()
{
    LastStatement();

}
```

Case 2:
If you also enable the code cleanup setting to sort usings and you have a empty lines before the first using (so line 1)
then this empty line will not be removed and the first using (after the sort) will be placed at line 2, with a empty line 1, which is kinda weird

Example:

```



using A;
using B,
```

should change to:

```
using A;
using B,
```

instead of the current:

```

using A;
using B,
```

---
#### Feedback Bot on 5/22/2022, 10:52 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is handled with the new option:

![Image](https://github.com/user-attachments/assets/a06c3d60-2259-4956-b09d-b14b4d2876a7)
