### ISSUE TITLE
API proposal: represent `ref` fields and `scoped` parameters and locals

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#61647]
This issue is referenced in source/test.

## Background and Motivation

Represent `ref` modifier for fields and the related `scoped` modifier for parameters and locals (see [language proposal](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md)).

`ref` fields:
```csharp
readonly ref struct Ref<T>
{
    private readonly ref T _t;
    public Ref(ref T t) { _t = ref t; }
}

readonly ref struct ReadOnlyRef<T>
{
    private readonly ref readonly T _t;
    public ReadOnlyRef(ref T t) { _t = ref t; }
}
```

`scoped` parameters and locals:
```csharp
static void F(scoped ref int x, ref int y)
{
    scoped Ref<int> r = new Ref<int>(ref x);
}
```

### Symbols
```diff
namespace Microsoft.CodeAnalysis
{
    public interface IFieldSymbol : ISymbol
    {
+       /// <summary>
+       /// Returns the RefKind of the field.
+       /// </summary>
+       RefKind RefKind { get; }

+       /// <summary>
+       /// Custom modifiers associated with the ref modifier, or an empty array if there are none.
+       /// </summary>
+       ImmutableArray<CustomModifier> RefCustomModifiers { get; }
    }

    public interface ILocalSymbol : ISymbol
    {
+       /// <summary>
+       /// Returns true if the local ref or value is scoped to the current method.
+       /// </summary>
+       bool IsScoped { get; }
    }

    public interface IParameterSymbol : ISymbol
    {
+       /// <summary>
+       /// Returns true if the parameter ref or value is scoped to the current method.
+       /// </summary>
+       bool IsScoped { get; }
    }
}
```

### Syntax
`SyntaxKind.ScopedKeyword` is added.

`ScopedTypeSyntax` is added that combines a `scoped` keyword and following type syntax.

If the type following `scoped` includes a `ref`, `ref readonly`, `in`, or `out`, the type is represented as a nested `RefTypeSyntax`.

```diff
namespace Microsoft.CodeAnalysis.CSharp
{
    public enum SyntaxKind
    {
+       /// <summary>Represents <see langword="scoped"/>.</summary>
+       ScopedKeyword = 8447,
    }

    public class SyntaxFactory
    {
+       public static ScopedTypeSyntax ScopedType(SyntaxToken scopedKeyword, TypeSyntax type);
    }
}

namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
+   public sealed class ScopedTypeSyntax : TypeSyntax
+   {
+       public SyntaxToken ScopedKeyword { get; }
+       public TypeSyntax Type { get; }
+
+       public ScopedTypeSyntax Update(SyntaxToken scopedKeyword, TypeSyntax type);
+
+       public ScopedTypeSyntax WithScopedKeyword(SyntaxToken scopedKeyword);
+       public ScopedTypeSyntax WithType(TypeSyntax type);
+   }
}
```

### Metadata encoding
`ScopedRefAttribute` is used by the compiler to emit `scoped` modifiers to metadata.

The attribute type definition is synthesized by the compiler if missing from the compilation.
```diff
namespace System.Runtime.CompilerServices
{
+   [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
+   internal sealed class ScopedRefAttribute : Attribute
+   {
+   }
}
```

## Usage Examples

Using `RefTypeSyntax` is a change for `ParameterSyntax` which currently represents ref keywords in `ParameterSyntax.Modifiers`. The proposal is to _use `RefTypeSyntax` for ref keywords in parameters within `scoped` types only_, to avoid a breaking change for C#10 syntax.

For example, the parameters from `static void M(ref int x, scoped ref int y)` will be represented as:
```csharp
SyntaxFactory.ParameterList(
    SyntaxFactory.Parameter(
        modifiers: SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.RefKeyword)),
        type: SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.IntKeyword)),
        identifier: "x"),
    SyntaxFactory.Parameter(
        modifiers: default,
        type: SyntaxFactory.ScopedType(
            SyntaxFactory.Token(SyntaxKind.ScopedKeyword),
            SyntaxFactory.RefType(
                SyntaxFactory.Token(SyntaxKind.RefKeyword),
                SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.IntKeyword)))),
        identifier: "y"));
```

**Comment by cston** [comment]
cc @333fred, @jaredpar

**Comment by RikkiGibson** [comment]
It feels like in order to merge the feature in a timely manner, we could reduce the set of proposed public APIs for the initial merge, perhaps to just the following:

1. Syntax changes
2. `IFieldSymbol.RefKind`

Then in the following couple of weeks or so, we could converge on a design for how to represent `scoped`. It might be useful to consider how the feature could evolve in future versions of the language when we consider the shape of the public API.

**Comment by jaredpar** [comment]
The `ref` fields feature is in a bit of a time crunch here and it needs to be merged in soon-ish so we can coordinate changes with dotnet/runtime. Sounds like a good suggestion to balance getting the feature in and merged so we can work with runtime and backload some of the other work which is more fit / finish.

**Comment by cston** [comment]
Updated proposal based on recent changes to the [spec](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md):
- `IParameterSymbol` and `ILocalSymbol` now have a single `IsScoped` property in each case rather than separate `IsRefScoped` and `IsValueScoped` properties
- `LifetimeAnnotationAttribute` takes a single `int` value rather than two `bool` values, and a single `IsScoped` property

**Comment by 333fred** [comment]
## API Review

* Need to update the docs for SymbolDisplayMemberOptions.IncludeRef
* For locals and parameters, could we hide IncludeRef and add a new IncludeRefAndScoped with the same value?
* Should we have a ScopedKind now, instead of IsScoped? That way we could adapt to `ref scoped` in the future
    * An enum `ScopedKind`, with `None`, `ScopedValue`, and `ScopedRef`

**Comment by cston** [comment]
Updated the synthesized attribute in the description (see also https://github.com/dotnet/roslyn/issues/62838).

**Comment by cston** [comment]
Updated syntax API based on recent discussions, and moved `SymbolDisplay` proposal to a separate issue: https://github.com/dotnet/roslyn/issues/63208.

**Comment by 333fred** [comment]
## API Review

The shape is generally approved, swapping the `IsScoped` for the `ScopedKind` previously discussed. We will also follow up with Cyrus when he's back from vacation on whether we should use the `ScopedTypeSyntax` for parameters, or whether we should be consistent with existing parameter parsing (putting the keyword as a modifier on the parameter).

```cs
namespace Microsoft.CodeAnalysis
{
    public interface IFieldSymbol : ISymbol
    {
       /// <summary>
       /// Returns the RefKind of the field.
       /// </summary>
       RefKind RefKind { get; }

       /// <summary>
       /// Custom modifiers associated with the ref modifier, or an empty array if there are none.
       /// </summary>
       ImmutableArray<CustomModifier> RefCustomModifiers { get; }
    }

    public interface ILocalSymbol : ISymbol
    {
       /// <summary>
       /// Returns the scope kind of the local.
       /// </summary>
       ScopedKind ScopedKind { get; }
    }

    public interface IParameterSymbol : ISymbol
    {
       /// <summary>
       /// Returns the scope kind of the parameter.
       /// </summary>
       ScopedKind ScopedKind { get; }
    }
    public enum ScopedKind
    {
        None,
        ScopedValue,
        ScopedRef,
    }
}
namespace Microsoft.CodeAnalysis.CSharp
{
    public enum SyntaxKind
    {
       /// <summary>Represents <see langword="scoped"/>.</summary>
       ScopedKeyword = 8447,
    }

    public class SyntaxFactory
    {
       public static ScopedTypeSyntax ScopedType(SyntaxToken scopedKeyword, TypeSyntax type);
    }
}

namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
   public sealed class ScopedTypeSyntax : TypeSyntax
   {
       public SyntaxToken ScopedKeyword { get; }
       public TypeSyntax Type { get; }

       public ScopedTypeSyntax Update(SyntaxToken scopedKeyword, TypeSyntax type);

       public ScopedTypeSyntax WithScopedKeyword(SyntaxToken scopedKeyword);
       public ScopedTypeSyntax WithType(TypeSyntax type);
   }
}
```

**Comment by cston** [comment]
> We will also follow up ... on whether we should use the `ScopedTypeSyntax` for parameters ... .

The conclusion from the follow up discussion over email:

> _For parameters_, the `scoped` modifier will be represented as a token in the `ParameterSyntax.Modifiers` list. This matches how ref/in/out are represented for parameters.
> 
> _For local declarations_, the `scoped` modifier will be represented, with a new `ScopedTypeSyntax` type, as part of `VariableDeclarationSyntax.Type`. This is similar to `RefTypeSyntax` for `ref` and `ref readonly` in local declarations.

**Comment by cston** [comment]
API has been updated.
