### ISSUE TITLE
[Tracking] Tests that have failed a few times

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6167]
Tracking bug against me to track tests that have failed indeterministically that I need to look into

Failure Count | Test|Log
------------- | -------------|-------------
1|Microsoft.CodeAnalysis.CSharp.UnitTests.IncrementalParsingTests.IncrementalParseTopDownCommentOutLines |[log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/212/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/IncrementalParsingTests/IncrementalParseTopDownCommentOutLines/)
2|Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.ProjectCacheHostServiceFactoryTests.TestImplicitCacheMonitoring| [log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/440/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces/ProjectCacheHostServiceFactoryTests/TestImplicitCacheMonitoring/) [log](http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/2557)
1|Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestGetTextAsyncDoesNotKeepTextAlive|[log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/460/)

**Comment by amcasey** [comment]
ProjectCacheHostServiceFactoryTests.TestImplicitCacheMonitoring in http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_win_dbg_unit64/440/

**Comment by davkean** [comment]
I had just added it: :)

**Comment by davkean** [comment]
None of these have failed recently, no point tracking this anymore.
