### ISSUE TITLE
Make `Throw` a control keyword in VB

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#61687]
Almost all syntax constructs form C# and their VB analogs has similar colorization. For instance, C#'s `if` and VB's `If ... EndIf` are both control keywords and are colored with pink color by default. However, the same does not apply to `throw` (C#) and `Throw` (VB). I don't see any obstacle in making VB's `Throw` control keyword as well

**Comment by CyrusNajmabadi** [comment]
Yes.  If we missed that, we should fix it.  Feel free to open a PR on it and i can review it asap.
