### ISSUE TITLE
Converting Expression<Func<T,object>> to string may be unusable when used for code generation.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/roslyn#61691]
I try to convert an expression in the form `Expression<Func<Person,object>>` to a string for later manipulation.

This expression is stored in a public property in a class and it's used in source code generation.
 
Example 1 (This works as expected)

```
Expression<Func<Person,object>> exp1 = p => "abc";  
Console.WriteLine(exp1.ToString() ); // ok, p => "abc"
```

Example 2 (This has a result that is not expected):
	
```	 
Expression<Func<Person,object>> exp2 = p =>  Guid.NewGuid();
Console.WriteLine(exp2.ToString()); 
//the string is including a convert method:  p => Convert(NewGuid(), Object), and it cause a compilation error when re-used in source code generation.
```

I expect expression to be `p =>  Guid.NewGuid()`, without including the `Convert` method: `f=> Convert(NewGuid(), Object)`

The problem in  the `Convert` method is the string expression is un usable and cause  a compilation error in the new source code generated.
		 
What do I need to do to get a usable  string expression as is like: `f =>  Guid.NewGuid()`  without convert method.
 
Demo for a [test case](https://dotnetfiddle.net/mwbpXk)

**Comment by CyrusNajmabadi** [comment]
Closing out.  There is no documentation or expectation that an `Expression<T>`'s ToString will roundtrip to usable C# code that can be the compiled in a source generator.  The ToString just gives a somewhat comprehensible view of the object one can look at in the debugger.

**Comment by moh-hassan** [comment]
@CyrusNajmabadi 
I don't use generic T, but the expression use a class defined at compile time as I explained in the post.
The documentation in https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.tostring?view=net-6.0
Explain that `Expression.ToString` Method:
 Returns a textual representation of the Expression, no more no less.

And what I need is a textual representation of the expression for later manipulation.

**Comment by CyrusNajmabadi** [comment]
That's correct.  It's a textual representation.  Like many (practically all in the .net fx) types, those textual representations are not legal C# code.  They're intended to just be a reasonably readable construct to aid in things like logging/debugging.

**Comment by CyrusNajmabadi** [comment]
> And what I need is a textual representation of the expression for later manipulation.

You will have to generate something yourself.  This is not a capability provided by the framework.
