### ISSUE TITLE
Need telemetry for how often a code-action with UI has its UI cancelled.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#61694]
It's possible we have htis, but i couldn't find any telemetry indicating this situation.  We should know this on a per-code-action basis.

**Comment by CyrusNajmabadi** [comment]
@jmarolf @mavasani @mikadumont do you know if we have a marker for this already?  I could not find one.

**Comment by jmarolf** [comment]
Some of this I tried to do via Kusto query. I have this query [here](https://devdiv.visualstudio.com/DevDiv/_git/Insights?path=/Roslyn/How_Often_Codefixes_Are_Undone_In_a_Day.kql) that tracks how often a codefix is applied followed by an "Undo" action. I could modify it to include cancelling the action but that would only be if a dialog popped up that the user and the editor reported that telemetry. We don't have anything that tracks something being cancelled in our own telemetry

**Comment by jmarolf** [comment]
@ryzngard The query I link to is only good for the last 7 days unfortunately. We would need a Cosmos query to store trends for longer. How hard is that?

**Comment by CyrusNajmabadi** [comment]
> We don't have anything that tracks something being cancelled in our own telemetry

Note: we should be able to tell.  We go through a custom code path in SuggestedAction.  So this would specifically be a case where we got an 'options' object, but then when we asked for the operations to perform, we got an empty array back (that's what cancellation is represented as).

**Comment by ryzngard** [comment]
> @ryzngard The query I link to is only good for the last 7 days unfortunately. We would need a Cosmos query to store trends for longer. How hard is that?

Likely we can still do only Kusto here. We can have jobs for producing custom data stores in Kusto on a daily basis and aggregate accordingly.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
