### ISSUE TITLE
Expose MethodSymbol.CallsAreOmitted and AttributeData.IsConditionallyOmitted

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#617]
@erik-kallen reported:

These members provide information which, as far as I can see, is not available anywhere else. Can you please consider exposing them?

**Comment by gafter** [comment]
@erik-kallen

**Comment by erik-kallen** [comment]
Since this is set to be in milestone 1.1, is there a workaround to get the information (except from using private reflection)?

**Comment by Youssef1313** [comment]
@jaredpar `IMethodSymbol.IsConditional` was exposed as a public API in https://github.com/dotnet/roslyn/pull/37526. Does this address the issue?

**Comment by jaredpar** [comment]
@333fred ?

**Comment by 333fred** [comment]
I think so.
