### ISSUE TITLE
Upgrade to NuGet to 3.2.1 reduce the number of infrastructure issues

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6170]
There are few bugs that our infrastructure is running into due to the build of NuGet we're using, we should upgrade to at least 3.2.1.

["Out of memory" and "Task was cancelled" while attempting to restore Roslyn's solution](https://github.com/NuGet/Home/issues/1586)
[NuGet package fails to load often with the Roslyn solution](https://github.com/NuGet/Home/issues/1597)
[NuGet is creating lots of temp files in %TEMP%, which eventually fails after there is 65,536 of them](https://github.com/NuGet/Home/issues/1608)

We should wait until @yishaigalatzer gives us the heads up, however, as I don't think there's a build with above yet.

**Comment by yishaigalatzer** [comment]
I'm waiting on one more pr to get merged (for corrupted packages.config) You can try today's build though (from myget nugetbuild feed)

Sent from my Windows Phone
________________________________

**Comment by diryboy** [comment]
Tried 3.3 beta from myget, it's way better, still gave task canceled errors on Test.Proprietary, but the second run was successful.

**Comment by davkean** [comment]
This has been fixed in https://github.com/dotnet/roslyn/pull/6864.

**Comment by diryboy** [comment]
Thanks!
