### ISSUE TITLE
"Add parameter" quickfix doesn't work for adding `Action<>`

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/roslyn#61715]
**Version Used**: 
VS 17.3.0 Preview 1.1

**Steps to Reproduce**:

Consider the following code:
```c#
public class Example
{
    public void Add(int x)
    {
    }

    public void DoSomething()
    {
    }

    public void Main()
    {
        DoSomething(Add);
    }
}
```

Put your cursor on the line `DoSomething(Add);` and perform an "Add parameter to 'DoSomething()'" quickfix.

**Expected Behavior**:
```c#
public void DoSomething(Action<int> add)
{
}
```

**Actual Behavior**:
```c#
public void DoSomething(object add)
{
}
```

**Misc**
Interestingly, the quickfix "Generate method 'DoSomething' works correctly, resulting in this code:

```c#
private void DoSomething(Action<int> add)
{
    throw new NotImplementedException();
}
```

**Comment by DoctorKrolic** [comment]
The source of problem lies here:
https://github.com/dotnet/roslyn/blob/134278cd43e1c3ac701a651a3369f3eecd3a37bb/src/Features/Core/Portable/AddParameter/AbstractAddParameterCodeFixProvider.cs#L395
Here `argumentExpression` is a `SyntaxNode`, that represents argument, in our case - `IdentifierNameSyntax` `Add`. I wonder, if `GetTypeInfo` should return type info about identifier (in this case it is a compiler bug), or it should be handled on IDE side? 
Can someone from compiler team tell pls? Thanks!

**Comment by Youssef1313** [comment]
@DoctorKrolic I'm not sure about the expected compiler behavior, but it would be good to know how things work for `Generate method`

**Comment by Bosch-Eli-Black** [comment]
Wow, that was fast! 😄

Thanks! 🙂
