### ISSUE TITLE
Issue: Lock Congestion using CSharpSyntaxRewriter

### ISSUE THREAD

**Issue by hopperpl** [dotnet/roslyn#61716]
**Version Used**: 
4.3.0-1.final

I'm converting Lua code to C# using Roslyn and am using CSharpSyntaxRewriter to perform code morphing and such things. The performance of CSharpSyntaxRewriter is not the best, so I try to run jobs in parallel. The syntax trees in each separate thread/task have nothing in common, they are completely separated objects. 100% completely untangled. 

The performance does not increase a bit because all threads block each other. The problem is in System.Private.CoreLib\src\System\Runtime\CompilerServices\ConditionalWeakTable.cs in function Add() ... -- the _lock object is the same for all syntax trees... so whenever any new node is created, which happens a lot especially during e.g. formatting, or optimizing - all the stages I do - each thread fights with all the others for every single node.

Parallel Stack gives a beautiful overview:

![image](https://user-images.githubusercontent.com/14023243/172172226-ba947505-3c40-4ec0-a513-567367493788.png)

Stack of any of those threads:

![image](https://user-images.githubusercontent.com/14023243/172172359-a03eeb2b-2f69-431f-81f7-007ffd190d09.png)

And the _lock is the same object:

![image](https://user-images.githubusercontent.com/14023243/172172405-6522b243-fbf9-400e-a006-848df7d44cc9.png)

I have a bit of trouble understanding, why the CompilerServices function is on top of the stack, it must be "compiler" generated. And I think it seems to be related to SyntaxAnnotation as the ConditionalWeakTable is GreenNode -> SyntaxAnnotation[]. Do I use these? Yes, and something is now telling me that I should not.

* Is this a bug? I don't know, but I think it's odd that 2 completely separated syntax trees share data and lock each other
* If it's not a bug and by design, how do I separate those trees?
* And if the trees cannot be separated, where is the ConditionalWeakTable  declared? I truly cannot find it.

**Comment by CyrusNajmabadi** [comment]
> Is this a bug? I don't know, but I think it's odd that 2 completely separated syntax trees share data and lock each other

The CWT allows us to associate some piece of data with instances of some type. In this case associating a SyntaxAnnotation[] with each red-Node we create.  So, if you're making a ton, it is possible for there to be high contention here as this sharing object is used by all nodes everywhere.

**Comment by CyrusNajmabadi** [comment]
> Are there other similar "shared" tables among trees? I see diagnostics also has a CWT.

Not sure.  It's all an impl detail, so it may change at any point.  Best is to just profile and see if perf is your concern.

**Comment by sharwell** [comment]
@hopperpl if you run your tool on .NET Core / .NET instead of .NET Framework, the problem will not appear. ConditionalWeakTable was re-implemented to no longer contain this fast-path lock.

**Comment by hopperpl** [comment]
I don't follow, sorry. I am using .NET Core 7.0 Preview 4 -- as luckily for internal tools we can use preview versions.

I finally found the location of the CWT here, https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/Syntax/GreenNode.cs -- or does this not apply? the "portable" path part irritates me a bit. But I removed the SyntaxAnnotations temporarily and the locks almost disappeared, it is already faster, so it must be the right source or a similar source.

**Comment by sharwell** [comment]
Ah, I thought you were hitting lock contention in _reading_ values from the ConditionWeakTable. It sounds like you are hitting contention while _adding_ values to it; .NET 7 still has a lock on this path. The easiest solution here is to either construct the trees in parallel, or avoid the use of (large numbers of) annotations.
