### ISSUE TITLE
No warning when base required member is not initialized in constructor with "SetsRequiredMembers" attribute

### ISSUE THREAD

**Issue by sirduke** [dotnet/roslyn#61718]
**Version Used**: 

**Steps to Reproduce**:
```
#nullable enable
public class Base
{
    public required string RequiredProperty { get; set; }
}

public class Derived : Base
{
    [SetsRequiredMembers]
    public Derived() : base()  // warning about uninitialized RequiredProperty expected
    {}

}
```

[sharplab repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzguATEBqAPgAQAYACfARgDoARKCAcxgHs0oBjFCgYUYwFMBBGBAA2ATxRQUAbgCwAKADEMAK7DhEYMN7FeQzb3n4AzKQBMxAEKoDcgN7zij0iYBOvAI7KobjKTIkAJQ8vHwAFF0YAB14XBFFiW2I6XgQpYhQUtIBfeRy5QxN8cyoYqAA3Xl8QS2t5ezknYgBtAGUUlCDPb0qAWV4wYBiUAF0HJ2NiEpdyyoAKAEpiauBrBYS83PkhMF4USIhWbXIKAOUYBCgdrkYwSKgtFzaXMrZdurHHJv4EBGngZQQvAAqih6LxZt9flB/oCACoQFzJBAcTjqFAoYi4YiQv4A3jwxHtCgtX7KVgITHYn64uEIpEcABiUF4wl8WJx0LxBPpFHCURicTgxAAkjAABalQG+AC8xAAZiIMkL+GpGAB3HqqC6RLTEWUK4QZeajBrjEwZESVMzETohXr9QYuDkw7TVZ14j4JT2NCa27oYPoDGLuwELb1OeqNRp5aOe71famcwEgsEQxMu7lElXCZWqjVaqA67Sy0m8IWiiXTKV6+WK3jG8NRqMTC1aXxFYjcW73GIM3gQBDKNx+nwh11UqEuxtNiPTmfNkxdu4PPsDoe8EeVMezcgkOX9wduAByEB28zn89npsvN6cq8PvBPOxr+7Xx9PvFk19vTZjP5nEy7sQ97rk+2iJEi2QXjeEzAIwjDCCKKAAPKRBcjBCIhEGZOkOF/v+xB5Hk2y7Pshx+NQtAMMwFzsNcfCCCI4iSJGTjxmOKbJGmk5cnSRLcDAaAuGSCCMC45bipKVr6nWubCOqmrCNquoyYa9Ymj65r9m21ptMim4Bg6QxjksE40jYjSsU2Ex6R0wT+oGjooNu57fpZ074YRmxyEAA) 

**Expected Behavior**:
warning CS8618: Non-nullable property 'RequiredProperty' must contain a non-null value when exiting constructor

**Actual Behavior**:
no warning

**Comment by jcouv** [comment]
I think this was by-design, but I'll let @333fred confirm

**Comment by 333fred** [comment]
Actually, I misread the op. This is indeed a bug.
