### ISSUE TITLE
Records Feature: convert between primary constructor and traditional constructor 

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#61749]
## Summary

I would like a refactoring that converts this form: 
```csharp
public record Source
{
  public Source(
    string? name = null,
    string? path = null,
    int? sourceReference = null,
    SourcePresentationHint? presentationHint = null,
    string? origin = null,
    ImmutableArray<Source>? relatedSources = null,
    ImmutableArray<Checksum>? checksums = null)
  {
    Name = name;
    Path = path;
    SourceReference = sourceReference;
    PresentationHint = presentationHint;
    Origin = origin;
    RelatedSources = relatedSources;
    Checksums = checksums;
  }

  [JsonPropertyName("name"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public string? Name { get; init; };

  [JsonPropertyName("path"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public string? Path { get; init; };

  [JsonPropertyName("sourceReference"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public int? SourceReference { get; init; };

  [JsonPropertyName("presentationHint"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public SourcePresentationHint? PresentationHint { get; init; };

  [JsonPropertyName("origin"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public string? Origin { get; init; };

  [JsonPropertyName("sources"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public ImmutableArray<Source>? RelatedSources { get; init; };

  [JsonPropertyName("checksums"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public ImmutableArray<Checksum>? Checksums { get; init; };
}
```

to this: 

```csharp
public record Source(
  [property: JsonPropertyName("name"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] string? Name = null,
  [property: JsonPropertyName("path"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] string? Path = null,
  [property: JsonPropertyName("sourceReference"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] int? SourceReference = null,
  [property: JsonPropertyName("presentationHint"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] SourcePresentationHint? PresentationHint = null,
  [property: JsonPropertyName("origin"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] string? Origin = null,
  [property: JsonPropertyName("sources"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] ImmutableArray<Source>? RelatedSources = null,
  [property: JsonPropertyName("checksums"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] ImmutableArray<Checksum>? Checksums = null);
```

and back again.

## Motivation

When working with a lot of data that needed to be serialized, I found myself converting between these two forms. Either first writing out the simple primary constructor case and then converting it when I discovered that I needed multiple constructors. Or starting with the verbose case and finding I could convert it to a primary constructor when I had factored away the more complex construction requirements. In either case the conversion was tedious.

## Design

This transformation should be available on the constructor's identifier and its modifiers.

```csharp
public record Source
{
  [|public Source|](
```

```csharp
[|public record Source|](
```

But _not_ include the parameters. 

It should also be safe to offer this on any constructor inside a record that meets the primary constructor requirements even if there are multiple constructors in record.

However, it does not make sense for this refactoring to provide a fix-all in the case of multiple constructors. We would only want to do this transformation if there is a single constructor for the record.

## Drawbacks

I am being a bit bullish proposing that we expand the target area to include the modifiers. We might want to offer a refactoring on modifiers in the future and this would conflict. This isn't a problem for me as there would just be two refactorings offered. I am willing to make the target a little bigger, and therefore easier to hit, in the hopes of it being more discoverable.

### Required members

My reading of the spec suggests that this should be a simple transformation between these two forms.

```csharp
public record Person(
  [property: RequiredMember] string FirstName,
  [property: RequiredMember] string LastName,
  string? MiddleName = null);
```

```csharp
public record Person
{
    public Person(string firstName, string lastName, string? middleName = null)
    {
        FirstName = firstName;
        LastName = lastName;
        MiddleName = middleName;
    }
    
    public required string FirstName { get; init; }
    public required string LastName { get; init; }
    public string? MiddleName { get; init; }
}
```

### Primary Constructors on classes

My understanding is that the C# LDM is considering adding primary constructors to [more than just records](https://github.com/dotnet/csharplang/issues/2691) in the future. My expectation is that this would be less challenging to implement and maintain than records but we would need to wait for the proposal to be approved and implemented. Perhaps this feature can be delayed until primary constructors have expanded use.

**Comment by tmat** [comment]
Working on Roslyn options I discussed usage of primary constructors to represent data with the LDM. The conclusion was that (primary) constructors are not ideal for that purpose and instead the recommendation is to use init properties and object initializers. 

```C#
public record Person
{   
    public required string FirstName { get; init; }
    public required string LastName { get; init; }
    public string? MiddleName { get; init; }
}

new Person { FirstName = "...", LastName = "..." };
```

**Comment by davidwengier** [comment]
> Required Members: My reading of the spec suggests that this should be a simple transformation between these two forms.

It doesn't seem to me like it's worth putting any effort into supporting this scenario. I might be misunderstanding the language feature, but if the properties are specified in the primary constructor, then marking them with `RequiredMember` seems redundant to me, and I think it would be odd if the IDE inserted that attribute. Aren't they required by virtue of being constructor parameters? If the user wanted to go further and add more constructors that chain, and take advantage of those aspects of the language feature, that is something they can do after the fact.

**Comment by jmarolf** [comment]
> I might be misunderstanding the language feature, but if the properties are specified in the primary constructor, then marking them with RequiredMember seems redundant to me, and I think it would be odd if the IDE inserted that attribute. 

The case I can think of would be something like this: 

```csharp
public record Person
{
    public Person(string firstName, string lastName, string? middleName = null)
    {
        FirstName = firstName;
        LastName = lastName;
        MiddleName = middleName;
    }

    public Person() {}

    public required string FirstName { get; init; }
    public required string LastName { get; init; }
    public string? MiddleName { get; init; }
}
```

where you provide a default and assigning constructor so that folks can do either

```csharp
var person = new Person("David ", "Wengier");
```
or

```csharp
var person = new Person { FirstName = "David ", LastName = "Wengier" };
```

In this case, invoking the refactoring on the assigning constructor I would expect to transform it into:

```csharp
public record Person(
  [property: RequiredMember] string FirstName,
  [property: RequiredMember] string LastName,
  string? MiddleName = null)
{
  public Person() {}
}
```

So that the semantics of the properties being declared are the same.

**Comment by jmarolf** [comment]
> While working on Roslyn options I discussed usage of records with primary constructors to represent data with the LDM. The conclusion was that (primary) constructors are not ideal for that purpose and instead the recommendation is to use init properties and object initializers.

This was my experience as well when working with System.Text.Json. It is unfortunate that the terse syntax and the "correct" syntax and not compatible. Forcing me to declare more verbose records.

If the LDM thinks that primary constructors are useful in other cases besides serialization, then this refactoring is useful. Like all refactorings you are not required to apply them.

**Comment by davidwengier** [comment]
Thanks for the clarification @jmarolf thats a good point.

Might be worth mentioning, or expanding the examples, so its clear what happens for multiple constructors. In your example above, I would consider the empty constructor to be "primary", but I guess if the refactoring is invoked on the other constructor then we use the one the user invoked it on?

**Comment by tmat** [comment]
My feeling from the LDM discussion was that primary ctors are only useful for records with a few properties. Once you get to representing objects with more then a few properties they lead you off a cliff. So I'm not sure the IDE should help you to get off that cliff.

**Comment by tmat** [comment]
On the other hand, refactoring that converts class/struct with readonly properties and simple constructor that just assigns them from parameters to a record with init properties and also updates all call sites of the constructor to use object initializer might actually be more useful.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of broad feedback on this topic.  We already have many conversino forms.  We should add more if we ahve strong signals indicating it is  needed.
