### ISSUE TITLE
IntelliSense variable name suggestions offered in wrong spot (32601.517.main)

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#61747]
**Version Used**: 
32601.517.main

**Steps to Reproduce**:
Put the caret at the end of line 23, typed a space, and IntelliSense name selection appeared.

![image](https://user-images.githubusercontent.com/11394666/172428672-33fae942-1c99-49c1-8dfe-757f3e466b44.png)

**Expected Behavior**:
No IntelliSense variable name suggestions

**Actual Behavior**:
IntelliSense variable name suggestions

**Comment by CyrusNajmabadi** [comment]
I do not repro this.  Do you still have this happening to you David?
