### ISSUE TITLE
Intellisense for NuGet package name and version

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#61744]
### Intellisense
Full Intellisense for NuGet package references is provided for both packages that are locally cached as well as packages defined in any feed - local and online.

![Tooltip](https://github.com/dotnet/ProjFileTools/raw/main/art/completion-name.png)

![Tooltip](https://github.com/dotnet/ProjFileTools/raw/main/art/completion-version.png)

### Hover tooltips
Hovering over a package reference shows details about that package.

![Tooltip](https://github.com/dotnet/ProjFileTools/raw/main/art/tooltip.png)

**Comment by davidwengier** [comment]
Thanks for the issue, but this is a project system feature, and already reported as https://github.com/dotnet/project-system/issues/766
