### ISSUE TITLE
js and css no code prompt in asp.net core project, say CSS Language Server (VSCode) failed to initialize

### ISSUE THREAD

**Issue by ahdung** [dotnet/roslyn#61769]
**Version Used**: VS2022 17.2.3

**Steps to Reproduce**:

1. Create a asp.net core project and a razor page
2. type some js or css codes

**Expected Behavior**:
Have code prompt

**Actual Behavior**:
No code prompt

17.1.6 is good.

![微信截图_20220608170224](https://user-images.githubusercontent.com/12094247/172578649-bf29b283-c43f-40bc-a038-0524cca2fabd.png)

![微信截图_20220608170948](https://user-images.githubusercontent.com/12094247/172578695-aa106e92-6ed9-4964-ac31-3ae7e5ab6d60.png)

**Comment by CyrusNajmabadi** [comment]
I don't believe this is a roslyn issue.  Can you report this through VS itself (Help -> Send Feedback -> Report a problem).  Thanks!

**Comment by ahdung** [comment]
Sorry, I did that first, but developercommunity often no response.
