### ISSUE TITLE
Improved UX (error message) for generator users using outdated Roslyn version

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#61774]
This issue came up when a Paint.NET plugin author tried to implement a plugin using a new version of ComputeSharp.D2D1, which bumped the Roslyn dependency to 4.2.0, while being on VS 17.1. The generators seemingly just stopped working with no clear indication of the issue, until after a while they noticed the following error messages:

> "1>CSC : warning CS8032: An instance of analyzer ComputeSharp.Core.SourceGenerators.AutoConstructorGenerator cannot be created from C:\Users\Osman\.nuget\packages\computesharp.core\2.0.0-alpha.25\analyzers\dotnet\cs\ComputeSharp.Core.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer ComputeSharp.Core.SourceGenerators.GlobalUsingDirectivesGenerator cannot be created from C:\Users\Osman\.nuget\packages\computesharp.core\2.0.0-alpha.25\analyzers\dotnet\cs\ComputeSharp.Core.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer ComputeSharp.D2D1.SourceGenerators.ID2D1ShaderGenerator cannot be created from C:\Users\Osman\.nuget\packages\computesharp.d2d1\2.0.0-alpha.25\analyzers\dotnet\cs\ComputeSharp.D2D1.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.."

This is completely unintelligible for an unexperienced user, and there is absolutely no way for them to possibly understand what the issue is. In this case, I could suggest that maybe they were on an older version of VS, so the analyzer was failing to be loaded. Especially given **source generator consumers might not be advanced users**, I really feel like we should have better UX for this scenario. Analyzer authors should be able to bump their dependency to a stable version without breaking consumers on older versions of Roslyn without a clear way for them to understand what the hell is going on. That message is completely obscure for a beginner.
 
### Proposal

If Roslyn fails to load an analyzer, it should check what Roslyn dependency it has. If it has one that's newer than the current version of Roslyn, it should change the error message (or **clearly inform the user in some way**) that the issue is due to their version of VS/Roslyn not being up to date, and that they should update to the latest stable release.

This would make life much easier for analyzer consumers 🙂

### Alternative

Another approach could be for analyzer authors to bundle a custom .targets checking the installed Roslyn version and emitting a diagnostic if so. This is possible, but it adds a lot of overhead to analyzer authors, plus custom .targets are something that is (1) absolutely not trivial to implement correctly, and (2) not something they might even know they need.

If this approach is preferred, at least we should have a sample in the docs that analyzer authors can reuse.

cc. @rickbrew

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/20316

**Comment by Sergio0694** [comment]
Ughhhhh I missed that one 😆
Thanks @Youssef1313! Closing this then.
