### ISSUE TITLE
Update ModuleMetadata to hold onto an object it can keep-alive.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#61778]
## Background and Motivation

A core thing the IDE does is load metadata into ModuleMetadata/AssemblyMetadata objects that can then be used to create the references that are attached to the compilations we make.  Currently, this is very complex due to livetime issues.  Specifically, to create a ModuleMetadata we need to use:

```c#
public static unsafe ModuleMetadata CreateFromMetadata(IntPtr metadata, int size)
```

This API takes a pointer to the blob with the metadata and the size of that blob.  The IDE owns this piece of memory, leading to unpleasant lifetime concerns.  Specifically, as long as ModuleMetadata is alive (which can be effectively forever, due to our immutability model, and handing these objects out directly), then the blob of memory needs to be pinned and not-released, otherwise memory corruption and crashing can occur.  

To aid with this, the IDE has many ConditionalWeakTables that exist just so that the ModuleMetadata/AssemblyMetadata instances we hand out root these blobs/memory-mapped-files/com-wrappers/etc. so that they cannot disappear underneath them.  

To simplify this system greatly, we would like to update ModuleMetadata so that *it* can own an underlying object that should then be rooted as long as the ModuleMetadta is alive.  When ModuleMetadata gets Disposed up, then that underlying object can go away.

Note: this functionality is already supported for ModuleMetadata for:

```c#
public static ModuleMetadata CreateFromStream(Stream peStream, PEStreamOptions options)
```

Here, if Stream is an UnmanagedMemoryStream, then it will be held onto for the live of ModuleMetadata.  So this jsut expands this support out to CreateFromImage.  This requires a new API (unlike CreateFromStream) As there is no runtime check that can be down to know what hte source of the blob was that was passed in.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
    public class ModuleMetadata
    {
        public static ModuleMetadata CreateFromMetadata(IntPtr metadata, int size);
+        /// <summary>
+        /// Create metadata module from a raw memory pointer to metadata directory of a PE image or .cormeta section of an object file.
+        /// Only manifest modules are currently supported.
+        /// </summary>
+        /// <param name="metadata">Pointer to the start of metadata block.</param>
+        /// <param name="size">The size of the metadata block.</param>
+        /// <param name="owner">Data that should be kept alive as long as this <see cref="ModuleMetadata"/> is alive.  This can be
+        /// useful, for example, if there is backing memory that the metadata depends on that should be kept rooted so it
+        /// doesn't get garbage collected.</param>
+        /// <param name="disposeOwner">Whether or not <paramref name="owner"/> should be <see cref="IDisposable.Dispose"/>'d when this object is
 +       /// Disposed.</param>
 +       /// <exception cref="ArgumentNullException"><paramref name="owner"/> is null.</exception>
+       public static ModuleMetadata CreateFromMetadata(IntPtr metadata, int size, IDisposable owner, bool disposeOwner);
    }
```

This helper just passes those values along to the underlying ModuleMetadata object which already supports these semantics.  The core two ideas here though are:

1. ModuleMetadata now roots 'owner' ensuring that as long as it is alive, the underlying data won't be GC'ed.
2. Ownership of that data can be transferred or not using disposeOwner.  If disposeOwner is false, ownership is not transferred, if it is true, ownership is transferred.  This follows the pattern of the rest of the methods in this type which use values like `leaveOpen = false` to determine if stream ownership is transferred.

**Comment by Neme12** [comment]
Would `nint` be more appropriate for `size`?

**Comment by CyrusNajmabadi** [comment]
This follows hte entire rest of hte API here.  My understanding from some discussions is that most of the stack here would not support >32bit size for any of this.

**Comment by 333fred** [comment]
### API Review:

* We think that the `owner` and `disposeOwner` parameters are a bit over-general, and that an approach involving passing a callback to be called when the compiler is done with a reference or an event fired at that time would be a better approach.

**Conclusion**: Needs to be reconsidered with the callback approach.

**Comment by tmat** [comment]
> involving passing a callbac

Isn't `IDisposable` such callback?

**Comment by CyrusNajmabadi** [comment]
> Or is the suggestion to combine the owner and disposeOwner into a single callback object?

Exactly.  It's felt to be a bit clunky right now to have these two entities, when really that could all be encapsulated.

**Comment by tmat** [comment]
Sounds reasonable. One thing to note though is that methods that take `Stream` also take `leaveOpen` as a separate flag in some form (bool or enum).

**Comment by CyrusNajmabadi** [comment]
Yup yup.  We brought it up.  There though it makes a lot of sense, as there is a lot of 'knobs' that need to be controlled.  Here... it's less necessary.  I will bring some alternatives, and we can compare/contrast them to the proposal above.
