### ISSUE TITLE
DiagnosticAnalyzerService.GetDiagnosticsAsync does not return additional file diagnostics

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61789]
https://github.com/dotnet/roslyn/blob/40cc8f5a5dbc2337aa4022653772425cfca0fb2f/src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs#L44

eventually calls into this method

https://github.com/dotnet/roslyn/blob/40cc8f5a5dbc2337aa4022653772425cfca0fb2f/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs#L274-L279

to add diagnostics.  Additional file diagnostics are reported as syntax local diagnostics.  However the caller does not pass in the additional file documentIds and so never appends the syntax local diagnostics.

https://github.com/dotnet/roslyn/blob/40cc8f5a5dbc2337aa4022653772425cfca0fb2f/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs#L112

This results in the DiagnosticAnalyzerService.GetDiagnosticsAsync to never return additional file diagnostics.

**Comment by sharwell** [comment]
@dibarbet I updated the links to point to Roslyn code, only to find that the second two links pointed to the same location. I believe one of the two was meant to point somewhere else.

**Comment by dibarbet** [comment]
thanks, fixed!

**Comment by vatsalyaagrawal** [comment]
@dibarbet can this be closed?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
