### ISSUE TITLE
Question: How to use syntax trees efficiently.

### ISSUE THREAD

**Issue by hopperpl** [dotnet/roslyn#61797]
First of all I like to apologize to ask such a simple question here and fill up the "Issue" pool, but unfortunately the Roslyn documentation is not very good to answer questions.

I build a syntax tree from scratch during a Lua -> C# code conversion. The whole process works quite nicely and efficiently, and in a very short time. A 900 KB lua binary is converted into "basic" C# code within 30-50 msec --- to give some ballpark idea of the conversion speed. 

Now the issue starts because 2 further steps are involved: first a few morphing steps, which pretty much simplify expressions like `if (A == true)` to just `if (A)` or `if (A) if (B)` to `if (A && B)` and so on. And the second step is to format the syntax tree with whitespace and indention. Now, the morphing step takes over 4000 msec and the formatting over 1900 msec. We are talking about 900 kB of binary code, and the C# code has over 20000 lines, so these times are not surprising in general -- but compared to the 30-50 msec to actually perform the code conversion to simplistic C# ... it is a lot!

Now, how do I do the two listed step? Using CSharpSyntaxRewriter. I don't believe I do anything wrong in general, as NormalizeWhitespace() is not a rocket ship either which uses a CSharpSyntaxRewriter as well. It even need more time, about 2300 msec instead of the 1900 msec.

Overall, I put this issue down to 2 primary problems. First of all, I used SyntaxAnnotations which is really, really bad for parallel processing (separated Lua files in parallel due to the internal CWTs). The second issue I found is the extremely slow ReplaceNode function, and I'm not sure about the way it is designed. But I have a bad feeling about how it this.

Lua uses (or can use) lambda functions excessively. And when in the final morphing step I move the sub-function code into the main function code (it's exactly like C# with anonymous, inlined lambdas), the processing time increases drastically for every further lambda... and I get the feeling that ReplaceNode literally traverses every node from the root down to every leaf to perform the operation, and with every inlined lambda added, the number of nodes to traverse grows and grows and grows, although I did not call ReplaceNode on the Root, I called it from the affected Statement node. I reversed it, processing statements from bottom to top and it's a a lot faster, 2x - 3x, as seemingly all new nodes are then "behind" the affected node to replace. For me, that is counter-intuitive because I did not call this "on the root" node.

Long story short, I need information how to process syntax trees on a very, very large tree:

1. **how do I call ReplaceNode fast and efficiently, when I absolutely know that the node in question is tree-wise under the given starting node?**
2. **how do I pull out a StatementSyntax from a "big tree" and make it its own tree?** I have a BlockSyntax with 10000 statements, I pull all 10000 statements out, process each individually, then make a new BlockSyntax and replace the old one -- currently I to ToString()/Parse() to "remove the tree" but of course that is ... well... dumb ... but it is so much faster

My intuition says, if I have an immutable tree, and in that tree I want to replace a node, and I give a start position of that node, then only the node and its leaves are traversed, this node is replaced and the rest of the whole tree stays unchanged and untraversed. But that is 100% not what is done. 

This is a timing overview for 10 big files:

![image](https://user-images.githubusercontent.com/14023243/172811271-011c1977-fdbf-457c-9fa6-1cd8a36fb047.png)

The whole fully working code generation from Lua is not even listed, it's in the filtered "noise". These account for 10 big files, so each one on average has a timing divided by 10. 10 fully working files to generate in under 500 msec, and then calling NormalizeWhitespace() (which is shown in the 2nd line in the image) takes 23 seconds. My own code formatter (to bypass the borked lambda block indention) takes 19 seconds. The statement combiner takes 35 seconds. 500 msec and all work is done, 60000 msec to make it look pretty. 

I need to understand what I'm doing wrong, or why NormalizeWhitespace() - the own Roslyn code - is doing badly as well. I do know that if I use a List\<StatementSyntax\>(), hold everything there and at the very end make all into a block and method, and never touch it again, it will be a fraction of the time. I'm just hesitant to do that as it undermines the whole Roslyn concept.

So, some insight about how to efficiently do all the morphing and formatting I would highly appreciate. I do not want to implement my own (mutable) syntax tree, but considering the time values and without a better solution, I do not think I have a choice.

**Comment by RikkiGibson** [comment]
Closing out as there doesn't appear to be anything actionable here.
