### ISSUE TITLE
'Introduce local' CodeAction in 'async Task' ArrowExpression adds invalid 'return' keyword to new method body

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#61796]
**Version Used**: 
Visual Studio 2022 v17.2.3

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

**Steps to Reproduce**:

1. Have any(?) project. I used the default ConsoleApp1 with net6.0
2. have a case like this:
```cs
using System;
using System.Threading.Tasks;

namespace ConsoleApp1;

internal class Example1
{
  private async Task DoStuff() => await ConsumeAsync(await TransformAsync("abc"));

  private Task<object> TransformAsync(string v) => throw new NotImplementedException();

  private Task ConsumeAsync(object value) => throw new NotImplementedException();
}
```
3. select `await TransformAsync("abc")`
4. Run 'Introduce local' CodeAction

**Expected Behavior**:
```cs
private async Task DoStuff()
{
  object value = await TransformAsync("abc");
  await ConsumeAsync(value);
}
```

**Actual Behavior**:
```cs
private async Task DoStuff()
{
  object value = await TransformAsync("abc");
  return await ConsumeAsync(value);
}
```
Note the `return` keyword. Since `DoStuff` has no Return Value (`async Task`) this is incorrect code

**Comment by Youssef1313** [comment]
Bug appears to be here:

https://github.com/dotnet/roslyn/blob/dcc6976026c13ad15c920b6d15cca318f47e9903/src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs#L71

The IDE should have a logic similar to:

https://github.com/dotnet/roslyn/blob/dcc6976026c13ad15c920b6d15cca318f47e9903/src/Compilers/CSharp/Portable/Symbols/MethodSymbolExtensions.cs#L159-L167
