### ISSUE TITLE
API for Lifted operators, please

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#618]
@erik-kallen reported:

How can I determine if an `IMethodSymbol` represents a lifted operator? According to `https://roslyn.codeplex.com/discussions/562085`, you have an internal class you could consider making public which would solve the problem. However, I think a property on `IMethodSymbol` would be more discoverable (it is "bloated" with info like `IsCheckedBuiltin` anyway).

**Comment by erik-kallen** [comment]
@gafter the one called erikkallen on CodePlex is actually me. erikkallen on GitHub is someone else who is probably wondering why he receives messages from the dotnet repo :)

**Comment by erikkallen** [comment]
Indeed I was wondering that since I am more fond of the Ruby on Rails camp :D

**Comment by gafter** [comment]
oops

**Comment by erik-kallen** [comment]
@erikkallen We should have an Erik Kallen meetup sometime :)

**Comment by erikkallen** [comment]
Haha yes we should and who knows there might be more out there :D

**Comment by erik-kallen** [comment]
Is this being considered?

**Comment by gafter** [comment]
It is unlikely for the VS2015 timeframe. Perhaps in an update several months later.

**Comment by CyrusNajmabadi** [comment]
Closing out as IOperation exposes IsLifted through apis like IBinaryOperation.IsLifted.
