### ISSUE TITLE
Allow rename tracking and rename via light bulb (refactoring) to be disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#61800]
Extracted from https://github.com/dotnet/roslyn/issues/57876#issuecomment-973638254

> I've hit this numerous times as well. For users who only _ever_ perform rename operations through F2 or Ctrl+R, R, it doesn't make sense to leave rename tracking enabled where it interferes with other light bulb operations. An option should be provided to disable the inline rename tracking altogether.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
