### ISSUE TITLE
Jenkins failures aren't getting sent to submitters

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6180]
Jenkins failures are getting sent to the Swat team, but not to the original submitter:

![image](https://cloud.githubusercontent.com/assets/1103906/10616367/9f09f4e0-7719-11e5-9e42-24331ab4e1be.png)

**Comment by davkean** [comment]
Now they've also stopped being sent swat at all ([Log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/402/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52), [Log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/379/consoleFull#-189014258379494335-f7bd-47d0-8771-8661e00c2db2))

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by amcasey** [comment]
We have the "Failure - Any" trigger set with recipients "Developers" and "Culprits" as described here: https://wiki.jenkins-ci.org/display/JENKINS/Email-ext+plugin.  Maybe it's a Jenkins issue?

**Comment by amcasey** [comment]
Confirmed that ```$DEFAULT_RECIPIENTS``` is blank.  Maybe that prevents the developers from being added to the to line?

**Comment by amcasey** [comment]
I tried resetting the triggers and then the whole action, but I still couldn't get it to send to the developer.  Maybe it's having trouble figuring out who that is?

**Comment by davkean** [comment]
Yeah, that could be it - wonder if it can't look it up from github.

**Comment by davkean** [comment]
or wonder if it looks at commit itself

**Comment by ManishJayaswal** [comment]
@mmitche @tannergooding can one of you take a look at this?

**Comment by mmitche** [comment]
@amcasey @ManishJayaswal @davkean Do you have an open example PR that isn't working?  I want to take a look at the info that GitHub is sending in the hook.

**Comment by davkean** [comment]
Every PR is failing to send to the contributors. It appears that swat has started getting emails again.

**Comment by mmitche** [comment]
Well, swat is specifically CC'd according to the configuration.  Let me check on what DEFAULT_RECIPIENTS is supposed to be

**Comment by mmitche** [comment]
There is also no mail set up to the send to anyone for prtests according to the config:

```
if (branchName == 'prtest') {
              switch (buildTarget) {
                case 'unit32':
                  addPullRequestTrigger(myJob, jobName, opsys, "(unit|unit32|unit\\W+32)")
                  break;
                case 'unit64':
                  addPullRequestTrigger(myJob, jobName, opsys, '(unit|unit64|unit\\W+64)')
                  break;
              }
              addScm(myJob, '${sha1}', '+refs/pull/*:refs/remotes/origin/pr/*')
            } else {
              addPushTrigger(myJob)
              addScm(myJob, "*/${branchName}")
              addEmailPublisher(myJob)
            }
```

**Comment by tannergooding** [comment]
@mmitche, @davkean. Emails were explicitly not configured for PRs. It is up to the individual submitter of the PR to follow up and verify that the jobs completed successfully (there is also currently no way to limit the e-mail to only be sent to members of the Microsoft group, as PRs can be submitted by anyone).

**Comment by mmitche** [comment]
@tannergooding I think our ideal case is that the submitter gets the email always.  I do recognize that this presents a problem, since our MS status mail address cannot send mail to non MS addresses.

**Comment by davkean** [comment]
Exactly, I don't know why "It is up to the individual submitter of the PR to follow up and verify that the jobs completed successfully" is a good thing, why waste a developer's time looking at the PR?

**Comment by davkean** [comment]
I'm not going to fix this - doesn't seem like anyone cares. I've heard zero feedback around this.
