### ISSUE TITLE
Project-level default for await configuration

### ISSUE THREAD

**Issue by Keith-McKinley** [dotnet/roslyn#61816]
### Is your feature request related to a problem? Please describe.
It is both tedious and easily-forgotten to religiously include `.ConfigureAwait(false)` in libraries. While the default behavior does make sense, the default should be able to be defined in the csproj file. Allowing a flag such as `<DefaultAwaitConfiguration>false</DefaultAwaitConfiguration>` would be of great help

### Describe the solution you'd like
Allow a sinple declaration in the csproj xml (and similar for other .net languages) that changes the way the compiler builds the assembly. If this sets the default to `false`, then the developer could use `.ConfigureAwait(true)` in specific cases where that behavior is desired.

When the project file lacks the flag, the current default (true) should be used.

### Additional context

**Comment by CyrusNajmabadi** [comment]
Closing out as a dupe. Please use the existing csharplang discussions for this.
