### ISSUE TITLE
Ok to store contexts for later?

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#61823]
Hi!

I have gotten indications that it is not ok to store for example an AnalysisContext and use it later on, like in the following code:
```
public void RegisterSyntaxTreeAction(AnalysisContext analysisContext, Action<SyntaxTreeAnalysisContext, Settings> action)
{
    analysisContext.RegisterSyntaxTreeAction(
        syntaxTreeAnalysisContext =>
        {
            Settings settings = GetSettings(analysisContext, syntaxTreeAnalysisContext, syntaxTreeAnalysisContext.CancellationToken);
            action(c, settings);
        });
}
```

In this code we would capture `analysisContext `and not use it until the syntax tree action is called, i.e. "later on".

My question is if this is ok?

If not, then I don't understand why there is a TryGetValue method in AnalysisContext, since I don't see any members in AnalysisContext which could be used to get a SourceText instance needed to make an actual call to TryGetValue. Could you give a use case for this method, provided that it is not ok to hang on to context instances? I don't see a problem with other context classes, only AnalysisContext.

Available methods etc is based on Microsoft.CodeAnalysis.* 4.2.0

**Comment by mavasani** [comment]
@bjornhellander It is fine to capture/store context objects in an analyzer and use them later. Certain APIs on context objects wouldn't be meaningful if used later. For example, [AnalysisContext.ConfigureGeneratedCodeAnalysis](https://github.com/dotnet/roslyn/blob/b55ec310613097be69bc8beb4b34f810771d0fa2/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L219)

**Comment by bjornhellander** [comment]
Nice. Thank you!
