### ISSUE TITLE
Re-work AutomationObject design

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#61855]
- https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/CSharp/Impl/Options/AutomationObject/AutomationObject.ObsoleteAndUnused.cs

    I think this can be deleted. While there is a comment saying they're kept for backcompat. My tests shows that backcompat isn't affected by deletion. I confirmed this by exporting my current VS settings, manually modify the file by renaming an element to a name AutomationObject don't know about, then importing the settings again. No crash happened.

- AutomationObject can get outdated easily (missing options), and get unintentionally filled with editorconfig-only code-style options (extra unnecessary options). A source generator may be a good solution to this. A unit test approach may also be worth investigating (will likely be reflection-based).

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
