### ISSUE TITLE
Bad code generated for nullable parameter default value of a new instance

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#6186]
The following code is rejected by VS2013 and accepted by VS2015. Once accepted, it is obvious it should print `True`. But it prints `False`.

```cs
using System;

struct Foo { object x, y; }
class C
{
    public static void M(Foo? foo = new Foo())
    {
        Console.WriteLine(foo.HasValue);
    }
    public static void Main(string[] args)
    {
        M();
    }
}
```

/cc @VladimirReshetnikov

**Comment by VSadov** [comment]
I believe this should be a compile error

**Comment by gafter** [comment]
@VSadov I think I agree, but we should find a spec quote to support that.

**Comment by AlekseyTs** [comment]
@gafter Please verify
