### ISSUE TITLE
Lightbulbs to add usings blocked by similar namespaces

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#61880]
**Version Used**: 
32611.49.main

**Steps to Reproduce**:
I’ve noticed that I’m not getting as many lightbulbs to add missing usings as I have before (this problem has probably been around a while but I just hit an egregious case today). See below for more details but expected an “add using” lightbulb to appear in this situation. Is my expectation wrong or did something break? 
 
![image](https://user-images.githubusercontent.com/11394666/173623214-3ba0d859-f076-4d31-9833-ef0ba9d48d09.png)

 The error would be resolved with an added "using Microsoft.VisualStudio.IntelliCode.Core;" but that is apparently being blocked because there is also a "Microsoft.VisualStudio.Utilities" that is confounding the analyzer:
![image](https://user-images.githubusercontent.com/11394666/173623531-63717db8-1b7a-41cd-82fe-0844c39116a9.png)

Based on discussions with Cyrus/Jason it seems this is expected (but annoying) behavior because of the confounding namespace. That said, it would be nice if the added using was proposed as a suggestion since it would fix the problem.

**Comment by CyrusNajmabadi** [comment]
Note: this will only work in David's case, because he has `usings` inside a namespace, and so the new `using` will take precedence over the symbol found in the containing namespace.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
