### ISSUE TITLE
[LSP] Enable Pull Diagnostics

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#61897]
Top level issue to track enabling LSP pull diagnostics by default

Dogfood blocking issues
- [x] https://github.com/dotnet/roslyn/issues/58778 (external)
- [x] De-dupe build diagnostics regression https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1552639/
- [x] Diagnostic squiggles missing for project context scenarios in latest main
- [x] Support diagnostics in additional files - https://github.com/dotnet/roslyn/pull/61930

Issues blocking turning on by default
- [ ] **[External]** (Request diagnostics at a slower rate from open non-visible documents) https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1569166
- [ ] https://github.com/dotnet/roslyn/issues/62495
- [ ] **[External]** (Support interactive window / file rename) https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1563105
- [ ] **[External]** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1569172 https://github.com/dotnet/roslyn/issues/62560
- [ ] **[External]** Workspace diagnostics requests cancelled after 2 minutes - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576626
- [ ] **[External]** Workspace diagnostics requests block text document diagnostics requests until workspace completes or is cancelled - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576625
- [ ] **[External]** Workspace diagnostics are not requested until a file is opened - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1578505/
- [x] https://github.com/dotnet/roslyn/issues/63147

Non-blocking issues
- [x] https://github.com/dotnet/roslyn/issues/61275
- [ ] Need to figure out how someone can configure suppressions from the error list if we don't own the error list.
- [ ] Need to remove IDiagnosticService.DiagnosticsUpdated. Currently this is used by tagger (but is not needed if tagger is just pulling), and by typescript. David believes TS just uses this for LSP-push-diags in liveshare and can likely be removed since we have worked with them to support pull diagnostics.
- [ ] Move IDiagnosticService.GetDiagnosticsAsync to be snapshot based. Currently it takes in Workspace+ProjId/DocId. This is non-sensical as that means you may get random results depending on the state of Workspace.CurrentSnapshot. This needs to move to take Project/Document instead.

See also: https://github.com/dotnet/roslyn/pull/62741, https://github.com/dotnet/roslyn/pull/62735 and https://github.com/dotnet/roslyn/pull/62771

Next steps
- [x] Enable flag for team
- [ ] Rollout to internal preview users
- [ ] Rollout to external preview users
- [ ] Rollout to everyone

**Comment by CyrusNajmabadi** [comment]
I'm closing this out as pull diags has been on for ages.  if there's more to do ehre, we can have targeted issues for that.
