### ISSUE TITLE
Expression Evaluator Regression - Expression Evaluation in Watch seems to do not take usings into account

### ISSUE THREAD

**Issue by Swiftly1** [dotnet/roslyn#61914]
**Version Used**: 

    PS C:\Roslyn\roslyn> git rev-parse HEAD
    9f883da6e4d576cea93d7271f3e2a52d1f2d6570

![obraz](https://user-images.githubusercontent.com/77643169/173811267-6b0938c7-952a-4a28-b0ef-a06dc64269df.png)

**Steps to Reproduce**:

![obraz](https://user-images.githubusercontent.com/77643169/173811148-3d22730a-ff87-42bf-9066-ecd055b5aac6.png)

1: dotnet new console

2: paste this code

	using System.Linq;

	while (true)
	{
		var list = new List<string> { "1", "2", "3", "4" };
		Console.WriteLine("asd");
		Thread.Sleep(500);
	}

3: put this expression into watch 

    list.Select(x => Convert.ToInt32(x)).Where(x => x > 1).ToList()

**Expected Behavior**:

Returns list that contains {"2", "3", "4"}

**Actual Behavior**:

Returns The debugger is unable to evaluate this expression

Internally it creates this error:

```
(1,6): error CS1061: 'List<string>' does not contain a definition for 'Select' 

and no accessible extension method 'Select' accepting a first argument of type 'List<string>' 

could be found (are you missing a using directive or an assembly reference?)
```

________________

My debugging attempt found that methodResolution fails (IsEmpty == true)

![obraz](https://user-images.githubusercontent.com/77643169/173812026-d3c29e2c-f3d5-474c-9159-b35092edbe8c.png)

and then this error is generated

![obraz](https://user-images.githubusercontent.com/77643169/173812213-4ea62f0b-3df3-4bb0-813c-c51b32b2191d.png)

![obraz](https://user-images.githubusercontent.com/77643169/173812266-b230578a-e02a-45d5-ac1d-b843995653a0.png)
 
but I feel like that's because methods are empty when creating `BoundMethodGroup`

![obraz](https://user-images.githubusercontent.com/77643169/173812784-464a1d57-23a5-4c2c-9f18-4933e666afd7.png)

and that's because something is not found here

![obraz](https://user-images.githubusercontent.com/77643169/173814093-729a87ee-5c5b-46f3-afa8-9a88ae4f903a.png)

because `NamespaceOrTypeSymbol` has no informations of `System.Linq` in it?? 

I've got lost at this point

**Comment by Swiftly1** [comment]
Update:

Seems like `Convert ToInt*` behaves weirdly, take a look at this example:

![obraz](https://user-images.githubusercontent.com/77643169/178051817-74d77433-5dc9-4b7b-ac95-8fc61db8efc8.png)

**Comment by CyrusNajmabadi** [comment]
@tmat do you know what might be going on here.  that `Convert.ToDecimal` works in the watch window, but `Convert.ToInt32` does not is... interesting to say the least :)

**Comment by tmat** [comment]
The original issue says there is `no accessible extension method 'Select' accepting a first argument of type 'List<string>'` error, which I'd attribute to some binding issue with top-level code.


> that `Convert.ToDecimal` works in the watch window, but `Convert.ToInt32` does not is... interesting to say the least :)

@chuckries This looks like possible VIL interpreter issue.

**Comment by dibarbet** [comment]
this repros on 17.4 p2 32803.494.main

**Comment by isadorasophia** [comment]
It seems to be a lack of support on VIL for `ReadOnlySpan<char>` parameters, which is the case for [Convert.ToInt32](https://github.com/dotnet/runtime/blob/339a6bcc082c1ab229e40522d7bc84f9feca02ca/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs#L279). This doesn't happen with `Convert.ToDecimal` because we hook the method with the `string` parameter instead. 🙂

I'll work on a fix on our side.

**Comment by CyrusNajmabadi** [comment]
@isadorasophia what does 'vil' stand for?  Thanks!

**Comment by isadorasophia** [comment]
@CyrusNajmabadi it's a VS debugger component used for expression evaluation 😁

**Comment by Swiftly1** [comment]
It seems like it's been fixed and pushed to the prod

I guess I'm closing this

![obraz](https://user-images.githubusercontent.com/77643169/209447324-1aa695de-c7f2-4f16-b96f-75e26ea1ae9d.png)
