### ISSUE TITLE
"Unnecessary Cast Analyzer" suggests to remove identity conversion on field of struct, which causes a change in behavior

### ISSUE THREAD

**Issue by siegfriedpammer** [dotnet/roslyn#61922]
**Version Used**: 
Whatever SharpLab currently uses

**Steps to Reproduce**:

```csharp
using System;
public struct S {
    public int Field;
    public void Increment() => Field++;
    public void Print() => Console.WriteLine(Field);
}
public class C {
    S s;
      
    public static void Main() {
        new C().M1();
        new C().M2();
    }

    public void M1() {
        s.Increment();
        s.Print();
    }
    
    public void M2() {
        ((S)s).Increment(); // cast causes local copy of s
        s.Print();
    }
}
```

Decompilation: https://sharplab.io/#v2:D4AQTAjAsAUCDMACAzgFwE4FcDGrEGVEBvWRMxBRASwDs8AxKgUwBsATAblPMpABZEASRrZ0TALZM6ACgCUiALwA+RI1ZsA1Bq4xyFJP0QAFdLVRzFKkBACc0te1k6AvrF5hEAYWLcyhZDp6ZL4UYB4kukFkNEwA7l5yAHQAshBygVGIMfGeSclg6SGuMCG8AqkWEZkoicKiElLmTiF6yIkmZoWRZMV6pQblBfJVmdLS+LLIsrUiYpIyzd1BbR0LGT2wzkA=

As you can see, ILSpy preserves the semantics by keeping the extra local variable.

Run: https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcDMACAzsSAY2GwGVsBvdbG7LbASyhIDEGBTAGwBMBua2vTgAWbAEkohMOwC27ZgAoAlNgC8APmxsu3ANS7+aWnRwjsABTBNgytZrhIAnAu08lhgL7ohCbAGFKARpyXENjGiC6BF8qI3CaKHYAd39lADoAWSRlMPjsRJS/dIyEHMivNEihUSzbWLy8NIkpWXkbd0jjXDTLazK4mgrjKtMa0pV6vIUFUiVcJSbJaTlFDoHw7t7V3MH0DyA==

M1 prints 1
M2 prints 0

**Expected Behavior**:
The cast in M2 is not reported as redundant.

**Actual Behavior**:
The cast is reported as redundant. Removing it causes a value-copy to be removed, which causes a change in behavior as can be seen in the 2. sharplab link.

**Comment by CyrusNajmabadi** [comment]
Hrmm... this one is tricky.  If we prevent this, then basic pointless casts like `(int)someInt` won't be reported.  We could potentially look to see if the struct is readonly, but this will still result in a false-negative for many many many valid cases :-/

**Comment by sharwell** [comment]
The specific change here is we would not report an identity cast on a non-readonly value type if a non-readonly member of that type is being accessed.

**Comment by jnm2** [comment]
@CyrusNajmabadi The fix here was incomplete for type parameters. Followup: https://github.com/dotnet/roslyn/pull/85201
