### ISSUE TITLE
StringSyntax doesn't work on an attribute property assignment

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#61947]
StringSyntax doesn't work when used with an attribute property assignment
```cs
class TestAttribute : Attribute
{
    public TestAttribute()
    {
    }

    public TestAttribute([StringSyntax("Regex")] string pattern)
    {
    }

    [StringSyntax("Regex")]
    public string Pattern { get; set; }
}

[Test("^sd[sfd]f$")] // works
[Test(Pattern = "^sdf$")] // doesn't work
class TestClass
{
}
```

Fails with this check: https://github.com/dotnet/roslyn/blob/5f998f32b01ba58815eca8e1d940f9231426754d/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/AttributeArgumentSyntaxExtensions.cs#L30-L34

Called from:
https://github.com/dotnet/roslyn/blob/254d2aaaa56446f22acdf71d1b3e9b2af8ec6430/src/Workspaces/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs#L210-L214

cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
will fix asap.
