### ISSUE TITLE
CompletionProvider descriptions not working

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#61950]
I have a custom `CompletionProvider` that overrides `GetDescriptionAsync` to add text to the completion item tooltip. The completion provider works, but `GetDescriptionAsync` is never called and the tooltip is empty.

![image](https://user-images.githubusercontent.com/303201/173969620-963ced37-9209-409a-896f-787929b8bba1.png)

It also doesn't work in unit tests. `CompletionService.GetDescriptionAsync` doesn't return a description.

I did some debugging and _I think_ it is because the code that displays the items includes project providers:
https://github.com/dotnet/roslyn/blob/5f01883263cc2f1da722ccc54d03a60e6fe31bfc/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.ProviderManager.cs#L102-L120

But when displaying the description, and getting the provider for an item:
https://github.com/dotnet/roslyn/blob/f2ef02aa06aa8d15863fad5438aa6817c79d7cde/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs#L411-L423

The providers are loaded from a different place, which doesn't include the custom provider:
https://github.com/dotnet/roslyn/blob/f2ef02aa06aa8d15863fad5438aa6817c79d7cde/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.ProviderManager.cs#L44-L75

cc @sharwell @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@genlu this may be helped with your current work.  can you take a look at this to help James out?

**Comment by genlu** [comment]
@JamesNK Thanks for the detailed bug report. This seems like a bug around handling reference-based CompeltionProvider as you suggested. Will send out a fix soon
