### ISSUE TITLE
Null check inside a loop affects CS8602 for unrelated code in the same method

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/roslyn#61964]
**Version Used**: .NET SDK 6.0.301

**Steps to Reproduce**:

The combination of a loop and a null check involving either a null oblivious type or a non-nullable type, appears to affect the CS8602 warning for another unrelated piece of code in the same method. Different kind of loops work to reproduce the issue. Maybe it's possible to reproduce it with even less code, but this is as small as I could make it.

```c#
#nullable disable
namespace ThirdParty
{
    public class Widget { public string Name; }
}

#nullable enable
namespace MyApplication
{
    record Foo(Bar? Bar);
    record Bar(Baz? Baz);
    record Baz();

    class UsesNullObliviousType
    {
        public static void DoWork(List<Foo> foos, ThirdParty.Widget widget)
        {
            var baz = foos.Select(foo => foo.Bar.Baz); // line 18

            for (int i = 0; i < 10; i++)
            {
                var x = widget.Name;
            }
        }
    }

    class UsesNullObliviousTypeAndDoesNullCheck
    {
        public static void DoWork(List<Foo> foos, ThirdParty.Widget widget)
        {
            var baz = foos.Select(foo => foo.Bar.Baz); // line 31

            for (int i = 0; i < 10; i++)
            {
                if (widget.Name is null)
                {
                }
            }
        }
    }

    class UsesNonNullableType
    {
        public static void DoWork(List<Foo> foos, string unrelatedObject)
        {
            var baz = foos.Select(foo => foo.Bar.Baz); // line 46

            for (int i = 0; i < 10; i++)
            {
                var x = unrelatedObject;
            }
        }
    }

    class UsesNonNullableTypeAndDoesNullCheck
    {
        public static void DoWork(List<Foo> foos, string unrelatedObject)
        {
            var baz = foos.Select(foo => foo.Bar.Baz); // line 59

            for (int i = 0; i < 10; i++)
            {
                if (unrelatedObject is null)
                {
                }
            }
        }
    }
}
```

**Expected Behavior**:
> C:\...\Test.cs(18,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]
> C:\...\Test.cs(31,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]
> C:\...\Test.cs(46,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]
> C:\...\Test.cs(59,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]

**Actual Behavior**:
> C:\...\Test.cs(18,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]
> C:\...\Test.cs(46,42): warning CS8602: Dereference of a possibly null reference. [C:\...csproj]

**Comment by jcouv** [comment]
Likely related to https://github.com/dotnet/roslyn/issues/61516
