### ISSUE TITLE
Mismatch between CSDiagnostic line number in message and location

### ISSUE THREAD

**Issue by goebeler** [dotnet/roslyn#61960]
I am having a problem evaluating compilation errors generated during CSharpCompilation.Emit.

I am using roslyn to generate CS code with #line directives containing unique ids of source objects that were used to generate the source following each #line directive as line number.

Now when there is an error during compilation (i.e. incompatible argument types), I would like to retrieve the unique id of my source object. 

```
var result = compilation.Emit(
                    peStream: stream
                    , pdbStream: symbolsStream
                    , embeddedTexts: embeddedTexts
                    , options: emitOptions);

                messages = result.Diagnostics
                    .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(diagnostic =>
                    {
                        var location = diagnostic.Location.GetMappedLineSpan();
                        var message = diagnostic.GetMessage(); // message contains the correct "line number" (Id)
                        // message is "generated.cs(640,1): error CS1503: ... and so on"
                        return (NetworkError)new UnknownNetworkError(
                            nodeId: location.StartLinePosition.Line,  // Problem here! Line should be 640, but is 639.
                            errorMessage: message);
                    })
                    .ToList();
```

The generated code looks like that (method names changed):
```
#line 640
            outputRoot.MethodExpectingFoo(child:

#line 576
            SomeStaticClass.StaticMethodReturningBar()

#line 640
);
```

So can anyone tell me where I can find the actual line number as it is mentioned inside the error message? I am not sure if this is an error or if I am looking in the wrong location (pun intended).

Thank you!

**Comment by jcouv** [comment]
From what I understood from your example the diagnostic is printed out with line 640 as the location (as expected), but the `diagnostic.Location.GetMappedLineSpan().StartLinePosition.Line` is 639.

I'm able to repro with the test below. This feels like a 0-based versus 1-based counting situation. I'll let @cston confirm what is expected.

```
        [Fact]
        public void TODO2()
        {
            var source = """
class C
{
    int M(int x, int y)
    {
#line 42
        return z;
    }
}
""";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics(
                // (42,16): error CS0103: The name 'z' does not exist in the current context
                //         return z;
                Diagnostic(ErrorCode.ERR_NameNotInContext, "z").WithArguments("z").WithLocation(42, 16)
                );

            var diagnostic = comp.GetDiagnostics().Single();
            Assert.Equal(41, diagnostic.Location.GetMappedLineSpan().StartLinePosition.Line); // expected 42
        }
```

**Comment by goebeler** [comment]
> .. This feels like a 0-based versus 1-based counting situation. I'll let @cston confirm what is expected.

If that's the case and I can rely on that, my problem would be solved.

**Comment by jasonmalinowski** [comment]
Yeah, the APIs are all zero-based indexes for line counting.

**Comment by jcouv** [comment]
Thanks @jasonmalinowski for confirming. I'll close this as by-design.
