### ISSUE TITLE
cast issue with object

### ISSUE THREAD

**Issue by MatthieuMEZIL** [dotnet/roslyn#6197]
C# allows to use (uint)0 and (uint)(object)0U
But it does not allow (uint)(object)0

Why this restriction and is it something that could be handle in the future?

**Comment by svick** [comment]
Eric Lippert has [an article explaining this](http://ericlippert.com/2009/03/03/representation-and-identity/).

The short version is that it would make each unboxing operation much more complicated. You can use either `Convert.ToUInt32((object)0)` or `(uint)(dynamic)0` instead.

**Comment by gafter** [comment]
We do not have any plans to change the semantics of cast to do the conversion.
