### ISSUE TITLE
Promote CompletionList.ItemsList to public API

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#61971]
## Background and Motivation

`CompletionList.ItemsList` was recently added in https://github.com/dotnet/roslyn/pull/61620, which is currently used by VS to help avoiding LOH allocation when large amount of items present (e.g. when Import Completion is enabled). The existing `Items` property is now lazy, so accessing it would also incur additional allocation. Making it public so the external consumers of Roslyn's CompletionService (like O#) could benefit from the change as well (or, if LOH wasn't a concern before, at least they wouldn't suffer from more unnecessary allocations).

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Completion
{
    public sealed class CompletionList
    {
        public ImmutableArray<CompletionItem> Items { get; }
+       public IReadOnlyList<CompletionItem> ItemsList { get; }
    }
}
```

Additionally, we might want to consider making `Items` property obsolete and direct people to use `ItemsList` instead.

## Usage Examples

``` C#
var completionService = document.GetRequiredLanguageService<CompletionService>();
var completionList = await completionService.GetCompletionsAsync(...).ConfigureAwait(false);

// Use `ItemsList` instead of `Items` would avoid unnecessary array allocation which might end up in LOH
foreach (var roslynItem in completionList.ItemsList)
{... }
```

## Alternative Designs

The new property could also be exposed in the ExternalAccess pattern, but it would limit the usage to partners like O#.
The underlying implementation is based on `SegmenetedList<CompletionItem>`, which isn't public , and going with `IReadOnlyList` would also provide some flexibility in case we'd want to substitute the underlying type in the future.

## Risks

The property already exists today as internal, I don't perceive any risk by exposing it. Having two seemingly identical properties might be confusing which can be mitigated by deprecating the old one and documentation.

**Comment by chsienki** [comment]
# API Review Notes

- It would be nice if we had some sort of common array type.
- Should we just make this a breaking change instead of having two different collection types?
  - That could cause issues for in-proc extensions as a binary break
  - We would have to wait for a major version change
  - Too many people use this API
- We should make Items obsolete? and member visible hidden
- If we use IReadOnlyList<T> will then want to remove it for the allocation
	- Should we have a custom enumerator type instead?
	- Think IReadOnlyList<T> is sufficient 

**Conclusion**: Approved. Deprecate and Hide existing `Items`
