### ISSUE TITLE
Proposal: Add support for implicit auto-casting of incoming method parameters

### ISSUE THREAD

**Issue by tumtumtum** [dotnet/roslyn#6198]
The proposed language feature makes it easier to implement overridden such as Object.Equals(object) by allowing parameters to implicitly be casted to a specific type using the as operator.

Example without:

```csharp
public class Foo
{
  public string Name { get; set; }
  public string Description { get; set; }
  public override bool Equals(object obj)
  {
     var otherFoo = obj as otherFoo;
     return otherFoo != null && otherFoo.Name == this.Name && obj.Description == this.Description;
  }
}
```

Example with new feature:

```csharp
public class Foo
{
  public string Name { get; set; }
  public string Description { get; set; }
  public override bool Equals(object obj as Foo) => obj != null && obj.Name == this.Name && obj.Description == this.Description;
}
```

**Comment by HaloFour** [comment]
Your use case sounds better accomplished through pattern matching:

```cs
public override bool Equals(object obj) {
    return obj match {
        case Foo other: (other.Name == this.Name && other.Description == this.Description),
        case *: false
    };
}
```

**Comment by svick** [comment]
It feels to me that this would promote a bad practice: a method that claims to support a wider set of types than it actually does.

`object.Equals(object)` is pre-generic, I don't think modern code should be designed like this (except of course you have to override `Equals(object)` even in modern code).

Do you have other examples where this would be useful?

**Comment by gafter** [comment]
The effect that you're trying to achieve belongs inside the body of the method as it is not part of the method's contract. So we are unlikely to do this.

**Comment by tumtumtum** [comment]
I wasn't suggesting that it would be part of he method contract. The implementation would be completely within the method body and would not change the method contract. 

But fair enough.

**Comment by tumtumtum** [comment]
Another use case is when implementing an anonymous method which takes a certain parameter but you want a more derived version without doing casts over and over:

For example:

```
void Foo(Expression<Func<Expression, bool>> predicate) { ... }

void Test()
{
  Foo(c => c is MethodCallExpression && ((MethodCallExpression)c).Method.IsGenericMethod
      && ((MethodCallExpression)c).GetGenericMethodDefinition() == FirstMethod
      && ((MethodCallExpression)c).Arguments.Count == 1);
}
```

Could be rewritten as:

```
void Test()
{
  Foo(c as MethodCallExpression => c != null
      && c.Method.IsGenericMethod
      && c.GetGenericMethodDefinition() == FirstMethod
      && c.Arguments.Count == 1);
}
```

I'm not suggesting that the public contract would be changed. It's an internal "compiler magic" implementation to make code more readable but implicit casts will still be inserted.

**Comment by gafter** [comment]
Under the proposed pattern-matching feature, you would write

```cs
void Test()
{
  Foo(e => e is MethodCallExpression c
      && c.Method.IsGenericMethod
      && c.GetGenericMethodDefinition() == FirstMethod
      && c.Arguments.Count == 1);
}
```

I do not see any justification for a separate feature for just this use case.

Note that it is clear from the source that the type restriction is not part of the contract because it appears inside the body.
