### ISSUE TITLE
Formatter doesn't handle `when` blocks correctly

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#62]
Consider the following code snippet:

``` csharp
class C
{
    void M()
    {
        try
        {
            if(x){
                G();
            }
        }
        catch(Exception e) when (H(e))
        {

        }
    }
}
```

If this is passed to the `Formatter` API it will output the following:

```csharp

class C
{
    void M()
    {
        try
        {
            if (x)
            {
                G();
            }
        }
        catch (Exception e) when(H(e))
        {

        }
        }
    }
```

This output has the following bugs:

- The last two `}` braces are not correctly indented
- There should be a space between `when` and `(`.  The current behavior is inconsistent with how we format other similar operators.

**Comment by DustinCampbell** [comment]
Oops. Yeah that's my bug.

**Comment by DustinCampbell** [comment]
This appears to be working now. I added a regression test with PR #491.

**Comment by khellang** [comment]
Looks, like this has affected the Roslyn codebase (through the codeformatter?) where `when` is used, some examples:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/MetadataReader/MetadataDecoder.cs#L1403-L1410
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/MetadataReader/MetadataDecoder.cs#L1538-L1553

**Comment by jaredpar** [comment]
@khellang indeed.  Formatting the Roslyn code base is how we initially discovered this bug.  I tried to catch all of the bad cases as I did the format but it looks like these slipped through.  

I just updated the code formatter to use a version of Roslyn with this fix.  So this will be corrected next time that I run it across the code base.

**Comment by jaredpar** [comment]
Confirmed the fix is present in the rc1 NuGet packages.
