### ISSUE TITLE
Roslyn VB is more case-sensitive than the native with certain Unicode characters

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#620]
```vb
#Const Ǉ = True

Module Program
    Const ǈ = "ǈ"

    Sub Main()
        Console.WriteLine(ǈ.ToUpperInvariant = "Ǉ") ' True
        Foo()
    End Sub

    <Conditional(ǈ)>
    Sub Foo()
        Console.WriteLine("Foo")
    End Sub
End Module
``` 
 
This code prints True Foo when compiled with the native vbc, but only True with Roslyn.
The upper-case form of ǈ, 'LATIN CAPITAL LETTER L WITH SMALL LETTER J' (U+01C8) is Ǉ. 

Originally reported by @VladimirReshetnikov

**Comment by gafter** [comment]
@VladimirReshetnikov Was this fixed with our recent changes to the way we do case mapping?

**Comment by theoy** [comment]
Is the Roslyn behavior "better" than the native compiler, by Unicode standards? If so we probably want to retain the new behavior. Please investigate.

**Comment by gafter** [comment]
See also #1070 where we recognize that Roslyn has been updated to comply with a more recent Unicode version.

**Comment by gafter** [comment]
I'm closing this issue on the assumption that the new behavior is "better" than the old behavior and compatible with more recent versions of the Unicode specification.

If you (anyone) has information suggesting otherwise, please reopen.
