### ISSUE TITLE
VS2022 Quick action to Convert to file scope for the whole project/solution is not available.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62018]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Quick-action-to-Convert-to-file-s/10072634)._

---
VS2022 keeps creating new files using the old namespace style.
There is a Quick Action to fix it, but it can't be applied to the whole solution. This is very annoying, because we can't keep consistent code throughout the solution and we can only go one by one to fix this.
In the image below you can see that the option to apply to the whole solution has been forgotten.

![image.png](https://aka.ms/dc/image?name=B09f082b09c5f4a6c9b434b6640fbadcb637909590417758459_20220616-165041-image.png&tid=09f082b09c5f4a6c9b434b6640fbadcb637909590417758459)

---
#### Feedback Bot on 6/16/2022, 01:27 PM: 

(private comment, text removed)
#### Feedback Bot on 6/17/2022, 00:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
I am going to add FixAll support for this refactoring.

**Comment by Youssef1313** [comment]
> VS2022 keeps creating new files using the old namespace style.

If you added `csharp_style_namespace_declarations = file_scoped` to your editorconfig, then Visual Studio will use file scoped for new files.
