### ISSUE TITLE
Rename UI can be obscured immediately after showing

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#62016]
**Version Used**: 17.3.0 Preview 3.0 [32616.196.main]

**Steps to Reproduce**:

1. Click on a parameter name symbol and leave the mouse over it
2. Move hand from mouse to keyboard
3. Invoke rename (i.e. Ctrl+R,R)
4. The rename dialog appears, but moments later the parameter tool tip appears, floating over and obscuring the rename dialog.

**Expected Behavior**:

The dialog is not immediately obscured.

Perhaps:

- The dialog floats above any tool tip, or
- Tool tips are not prompted by the display of the rename dialog

**Actual Behavior**:

Dialog is obscured as soon as it appears, meaning you cannot see what you are typing.

There doesn't seem to be a way to dismiss the tool tip using the keyboard alone. The standard shortcut of <kbd>Esc</kbd> closes the rename dialog, not the tool tip.

After clicking on the symbol to rename it, the user will likely move their hands back to the keyboard to type the new name. When this occurs, and because it can't be dismissed via the keyboard, the user's hands have to move back to the mouse. These moves increase the perceived friction of the feature.

![video](https://user-images.githubusercontent.com/350947/174537959-1db94b5e-c19d-4ee9-a9c4-eeb5da36d3c8.gif)

**Comment by CyrusNajmabadi** [comment]
Closing out as we've gotten no more reports of this.
