### ISSUE TITLE
Assignment operator on array field  may execute with inconsistent left / right ordering

### ISSUE THREAD

**Issue by suedama1756** [dotnet/roslyn#62020]
**Version Used**: 

4.2.0-4.22252.24

**Steps to Reproduce**:

On first run of some deterministic parsing code the following fails to write the correct value to an array field.

```cs
for (var i = 0; i<length; i++) {
  store.Indices[refIndex + i] = Read(bytes, ref pos);
}
```

Indices is an int[] field (not protected by property accessor). The call to Read will result in Indices growing.  If the code is rewritten as below everything works as expected.

```cs
var index = Read(bytes, ref pos);
store.Indices[refIndex + i] = index;
```

The code that fails only fails on first pass, subsequent calls over the same data work as expected. The issue is with the order of assignment evaluation, on first run it appears to be left to right, on subsequent runs it is right to left. This leads me to think the issue is in non-optimized fast JIT code generation. The code is currently part of a large solution I cannot share, I will work on seeing if I can provide a minimal example and update the issue.

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:

Assignment evaluation order should be deterministic 

**Actual Behavior**:

Left hand side is evaluated first in on initial code execution leading to assignment to stale field value, and right to left in subsequent runs.

**Comment by CyrusNajmabadi** [comment]
I believe this is by design. The language explicitly and intentionally says that it evaluates from left to right.

**Comment by CyrusNajmabadi** [comment]
> The issue is with the order of assignment evaluation, on first run it appears to be left to right, on subsequent runs it is right to left. 

Are you sure it's that?  Or is it perhaps that in subsequent runs the array is large enough and does not have to grow?

**Comment by suedama1756** [comment]
I already considered this and I'm fairly certain this is not the case as the whole flow is re-initialized (e.g. the array is not re-used), but will verify again and report back.

**Comment by CyrusNajmabadi** [comment]
Note: roslyn emits the IL. If you feel the IL is in error, please show us what it is and why the think that. If the IL is fine, but you're getting different behavior given the same input values, then this sounds like it would be runtime issue and we'd move it there. 

That says, the general report that c# should not be evaluating left to right is incorrect afaict. That is the defined behavior of the language.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/expressions.md#11182-simple-assignment

```
The run-time processing of a simple assignment of the form x = y consists of the following steps:

    If x is classified as a variable:
        x is evaluated to produce the variable.
        y is evaluated and, if required, converted to the type of x through an implicit conversion (§10.2).
        If the variable given by x is an array element of a reference_type, a run-time check is performed to ensure that the value computed for y is compatible with the array instance of which x is an element. The check succeeds if y is null, or if an implicit reference conversion (§10.2.8) exists from the type of the instance referenced by y to the actual element type of the array instance containing x. Otherwise, a System.ArrayTypeMismatchException is thrown.
        The value resulting from the evaluation and conversion of y is stored into the location given by the evaluation of x.
```

And array indeed is classified as a variable. So left to right is expected.

**Comment by suedama1756** [comment]
Agree the title should be updated as left to right is the correct order. Given I get results as if its evaluating right to left in subsequent runs however I believe there may be an issue with optimisation as the order should be consistent.

**Comment by CyrusNajmabadi** [comment]
>  which may indicate an issue with the optimisation as the order should be consistent

This issue is currently not actionable without more data. For example, is the IL that the compiler emits incorrect?  Or is it correct, but something later seems to be a problem. 

Absent a repro that demonstrates the issue, I'm not sure what could be done here.

**Comment by suedama1756** [comment]
What I am saying is that it always resizes (As per your question above) so cannot be re-using an array which happens to have the correct value in it. What I believe I am getting is inconsistent behavior. I can't share the full source, once I finish work I will try and create something I can share that hopefully reproduces the issue

**Comment by suedama1756** [comment]
Ok, found the issue. Was using ArrayPool , I set true to see if I could get more insight and found that it had the magic value at refIndex + i already set on the second run. This was due to the read growing the array which returns the LHS to the pool, meaning that the assignment was writing back to the returned array!! Thanks for the quite response anyway, left to right, one to remember when switching languages for sure
