### ISSUE TITLE
Generic methods with same name but different type

### ISSUE THREAD

**Issue by rqueizan** [dotnet/roslyn#62052]
Why can't I have two generic methods, which are differentiated by type, one is class type, the other structure type?
In principle they would never overlap, right?

**Version Used**: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.3.0 Preview 2.0
TargetFramework: net6.0

**Steps to Reproduce**:
```
private async Task<T?> SomeMethod<T>(T x) where T : class => await Task.FromResult<T?>(default);
 
private async Task<T?> SomeMethod<T>(T x) where T : struct => await Task.FromResult<T?>(default);//Error: CS0111

Or something like that:

private async Task<T?> SomeMethod2<T>() where T : class => await Task.FromResult<T?>(default);
 
private async Task<T?> SomeMethod2<T>() where T : struct => await Task.FromResult<T?>(default);//Error: CS0111
// Error: CS0111 Type 'XXXXX' already defines a member called 'SomeMethod' with the same parameter type
```

**Expected Behavior**:
No compiler errors

**Actual Behavior**:
Compiler error: CS0111 Type 'XXXXX' already defines a member called 'SomeMethod' with the same parameter type

**Comment by CyrusNajmabadi** [comment]
Because the runtime doesn't treat constraints as part of the signature, so they are duplicates there. If you'd want this relaxed, runtime would need some support for this first. Thanks,!
