### ISSUE TITLE
IntelliSense suggests the "String" class, not the "string" keyword

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62079]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-suggests-the-String-class/1581662)._

---
[severity:It's more difficult to complete my work]
In C# when I write the lower case "string" keyword, IntelliSense suggests always the upper case written "String" class. When I'm choosing it gets automatically faded out with the tip to use the lower case "string" keyword. I would expect that IntelliSense is smart enough to suggest the users preferences. ..Or at least suggest what the user has written (lower or uppercase version)

---

I believe this is because the MRU (most recently used) cache the completion uses. By default, we’d select the keyword if you typed `string` (which is a perfect match.) However, once you selected and committed the type item `String` , it’d be saved in MRU and next time you type `string` the completion would “remember” that decision and select type `String` even though `string` is a strictly better match. Manually selecting `string` and committing it would cause subsequent selection to pick `string`.

**Comment by genlu** [comment]
I think we should tweak MRU to take capitalization into account and prefer better match over MRU item in such case

**Comment by KrisNie** [comment]
![image](https://user-images.githubusercontent.com/20340761/201838530-6c78ed6d-49bf-47ae-a876-4a75685ab706.png)

I still have this issue in my VS.


Microsoft Visual Studio Professional 2022
Version 17.4.0
VisualStudio.17.Release/17.4.0+33103.184
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA224
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

C# Tools   4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by KrisNie** [comment]
> 

Sorry, I see it's the problem of ReSharper.

Have a nice day!

**Comment by eduarddejong** [comment]
Hi! For reproducing the issue, just try some simple typing on https://sharplab.io.

With double / Double you can notice the issue occurs basically every time, seems even worse than with string / String.
But it also looks like that once you are using the lowercase version of the type, the symptoms tend to disappear.

For the argumentation why this issue is a real problem, I would like to share this article from Jared Parsons:
https://blog.paranoidcoding.com/2019/04/08/string-vs-String-is-not-about-style.html

Especially for new developers I think it is important that they learn the right practices here. Getting correct code suggestions is kind of a vital thing in my opinion.

**Comment by CyrusNajmabadi** [comment]
@eduarddejong 

> just try some simple typing on https://sharplab.io/.

Sharplab is not roslyn.  Roslyn controls the editing experience in VS.  Thanks!

**Comment by eduarddejong** [comment]
@CyrusNajmabadi
Thanks a lot for clarifying. I wasn't aware of that possibility.
