### ISSUE TITLE
record primary constructor does not have CompilerGenerated attribute

### ISSUE THREAD

**Issue by kofifus** [dotnet/roslyn#62073]
```
record R(int I);
```

Looking at the main branch 21/6/2022 in sharplab.io I see:

```
public R(int I)
{
    <I>k__BackingField = I;
    base..ctor();
}
```

Is there a reason that this constructor is not decorated with the CompilerGenerated attribute like all other methods ? (see https://github.com/dotnet/roslyn/pull/58542)

**Comment by AlekseyTs** [comment]
Yes, there is a piece of syntax that declares the constructor, the parameter list in the type declaration.
