### ISSUE TITLE
DateTime tooltip is US format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62082]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DateTime-tooltip-is-US-format/10070479)._

---
The tooltip used to display the value of a C# DateTime object during debugging is US format.  For most of the rest of the world not using the weird month/day/year ordering, this is horribly confusing.    DateTime objects should be displayed using localised formatting, or explicitly field by field.

In the screenshot attached, for example - DateTime firstOfDecember = new DateTime(2022, 12, 1);  ... this is shown in the debug tooltip as "12/1/2022" which is read as "the 12th of January 2022" for most places outside the USA - I hope Americans will understand why this is confusing and wrong!

---
#### Feedback Bot on 6/14/2022, 11:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
No idea, maybe @tmat knows what's going on here?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response and information.
