### ISSUE TITLE
"Implement abstract class" should add "where T : default" when a parameter is covariant in T?

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/roslyn#62092]
**Version Used**: Visual Studio 17.2.5 (VisualStudio.17.Release/17.2.5+32616.157 ; C# Tools 4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44)

**Steps to Reproduce**:

1. Write the following code:
```csharp
interface I<out T> { }

abstract class C
{
    protected abstract void M1<T>(T? t);
    protected abstract void M2<T>(I<T?> i);
}

class C2 : C
{
}
```
2. Use "Implement abstract class" on `C2`

**Expected Behavior**:

The resulting code should compile.

**Actual Behavior**:

`M1` is correctly implemented but `M2` is not, as it is missing `where T : default` and thus does not compile:

```csharp
    protected override void M1<T>(T? t) where T : default
    {
        throw new NotImplementedException();
    }

    protected override void M2<T>(I<T?> i) // <- this does not compile
    {
        throw new NotImplementedException();
    }
```

---

A more realistic example for is using a `Func<T?>` as parameter.

It took me a while to even understand what the issue was, since the compiler doesn't say anything about `where T : default` being something you can do in the resulting error messages. Perhaps the compiler could detect that there is an override that would work if it had `where T : default` and warn about that?

**Comment by Youssef1313** [comment]
I think I missed this case in https://github.com/dotnet/roslyn/pull/53318.

**Comment by SolalPirelli** [comment]
This happens for implementing interfaces _implicitly_ as well:

```csharp
interface I<out T> { }

interface I2
{
    void M1<T>(I<T?> i);
}

class C : I2
{
}
```

"Implement interface" produces valid code, "Implement all members explicitly" does not. (I like how the preview for the latter already shows the red squiggles within the preview -- how cool is that? 😄 )
