### ISSUE TITLE
Quick Refactoring - Introduce Parameter Object

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62106]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Refactoring---Introduce-Parameter-/10027620)._

---
It would be useful to have a new quick refactoring to replace a long list of method arguments with a parameter object and ideally replace all call sites with the instantiation of this parameter object. 
It's usually burdensome when refactoring some legacy code bases when you have a complex call hierarchy with a long list of arguments passed down the hierarchy, to refactor it with introducing a class that would logically group the arguments together and is also potentially error prone when done manually.      

Functionality would potentially behave similarly like existing "change signature" refactoring, where you could select all the parameters that would be included in such a parameter object and also provide a class name for it.  

Refactoring reference: https://refactoring.com/catalog/introduceParameterObject.html

Best Regards,
Aleksandar

---
#### Feedback Bot on 5/1/2022, 06:59 PM: 

(private comment, text removed)

**Comment by JoeRobich** [comment]
### Design Meeting Notes (2022/06/27)
- Should we offer refactoring option from a selection containing multiple parameters?
    - Refactorings shouldn't require precision mouse work.
- From Change Signature dialog provide capability to extract parameters to a new type. 
    - Looking for a proposal that handles params parameters, cancellation tokens, event handlers, etc… 
    - This allows the user to position the new parameter object within the signature without requiring follow up work.
- When there are multiple method signatures with the same set of parameters, we would like to be able to identify and update them all to use the new parameter object to avoid repeating this operation many times.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
