### ISSUE TITLE
Intellisense should display construction hints for aggregate initiliazer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62107]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-should-display-construction/10063248)._

---
if I have a type like
struct Point { int x; int y; }

intellisense for construction isn't helpful - it just shows the default, copy, move ctors. but this type is intended to be constructed as aggregate, i.e. auto p = Point{1,2};
It'd be useful for VS to consider aggregate initialization for constructor intellisense hints, so that it prompts me e.g. Point(int x, int y)  (but maybe with different display hints to clarify it's aggregrate init)

A nuance to consider is that aggregate init considers Point{int x}, Point{int x, int y}, etc

---
#### Feedback Bot on 6/6/2022, 07:10 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is not c#, this is c++.  closing out and will move teh VS ticket.
