### ISSUE TITLE
Diagnostics Inline: Show Hints, Suggestions, Refactorings, Spelling Errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62105]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Diagnostics-Inline:-Show-Hints-Suggesti/10034797)._

---
I'd like it if the new "diagnostics inline" showed not only errors and warnings, but additionally hints, suggestions, possible refactorings, and everything else. Even better, if it could be configured, what is shown.

---
#### Feedback Bot on 5/9/2022, 08:06 PM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
@akhera99 and @jmarolf I know we plan to make inline diagnostic UX improvements down the line but it may be worth exploring an option to display inline fixes for errors and warnings rather than diagnostics.

**Comment by JoeRobich** [comment]
### Design Meeting Notes (2022/06/27)
- Maybe we can launch a lightbulb session for the user when the inline error is clicked similar to clicking on the lightbulb.
- Can we just add "Press Ctrl + . to fix" to inform the user how to fix the error?
- Perhaps we can share a message using the tipping service.

Needs a proposal. Should work with UX to ensure a consistent experience across languages.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
