### ISSUE TITLE
'Converted to interpolated string' supports InvariantCulture

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62111]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Converted-to-interpolated-string-suppo/10073925)._

---
‘Converted to interpolated string’ works with the following code.

```cs
Console.WriteLine(String.Format("Hello World!{0}", 1.1));
// Converted to Console.WriteLine($"Hello World!{1.1}");
 ```

However, it does not work with `InvariantCulture`

```cs
Console.WriteLine(String.Format(CultureInfo.InvariantCulture, "Hello World!{0}", 1.1));
// Expect to convert to Console.WriteLine(FormattableString.Invariant($"Hello World!{1.1}"));
```

VariantCulture is often used in text processing where the same result must be obtained.

---
#### Feedback Bot on 6/19/2022, 08:10 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
