### ISSUE TITLE
Wrong behavior of compiling for functions with nullable string return when nullable is enabled

### ISSUE THREAD

**Issue by zijianhuang** [dotnet/roslyn#62115]
**Version Used**: 
.NET run time: 6.0.6, SDK 6.0.301
VS 2022 Pro 17.2.5
Windows 10

**Steps to Reproduce**:

```c#
		[Fact]
		public void TestAthletheSearch()
		{
			Type methodContainerType = Type.GetType("NullableReferenceTypes.Misc");
			Assert.NotNull(methodContainerType);
			var methodBase = methodContainerType.GetMethod("AthletheSearch");
			Assert.NotNull(methodBase);
			var customAttributes = methodBase.CustomAttributes.ToArray();
			Assert.NotEmpty(customAttributes);
			Assert.Equal((byte)1, customAttributes[0].ConstructorArguments[0].Value);
			Assert.Equal("System.Runtime.CompilerServices.NullableContextAttribute", customAttributes[0].AttributeType.FullName);
		}

#nullable enable
		public string AthletheSearch(string? sort, string? search)
		{
			return "ABCD";
		}
#nullable disable
```

[Repo](https://github.com/zijianhuang/TestNullableReferenceTypes) is available for testing.

**Expected Behavior**:

Expected 1 from System.Runtime.CompilerServices.NullableContextAttribute

**Actual Behavior**:

The value is 2, telling the function is with a nullable string return.

However, for this:
```c#
		public string GetNotNullStringOnNullableEnabled(string? sort)
		{
			return "ABCD";
		}
```

The compiler gives correct result: 1. Only when the parameters have more than 1 nullable string, the problem occurs.

## Presumptions

When the compiler recognizes a return is nullable, it will inject System.Runtime.CompilerServices.NullableContextAttribute with value  2, otherwise 1.

**Comment by cston** [comment]
@zijianhuang, `NullableContextAttribute` is added to methods and type definitions to indicate the nullability of type references that have no `NullableAttribute` attributes (see [nullable-metadata.md](https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md)).

For this particular method, is there also an explicit `[return: NullableAttribute(1)]` attribute that indicates the nullability of the return type directly?

**Comment by zijianhuang** [comment]
@cston 

You are quite right that `ReturnTypeCustomAttributes[0]` as `System.Runtime.CompilerServices.NullableAttribute` is with value 1 in method AthletheSearch.

In my original test suite, I do have cases testing this as well. And the test cases in the Repo submitted is focused on NullableContextAttribute, since I expected some consistent behavior in AthletheSearch and GetNotNullStringOnNullableEnabled.

**Comment by zijianhuang** [comment]
@cston 

I had read the md again carefully this time. Apparently this:
......
The C#8 compiler uses the following algorithm to determine which NullableAttribute and NullableContextAttribute attributes to emit. First, NullableAttribute attributes are generated at each type reference and type parameter definition by: calculating the byte[], skipping empty byte[], and collapsing byte[] to single byte where possible. Then at each level in metadata hierarchy starting at methods....
......
Had explained well, and apparently the inconsistency I had observed is the consistent result based on such algorithm.

Thank you very much. Case closed.
