### ISSUE TITLE
Create Implementation Shortcut in right menu for Interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62110]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-Implementation-Shortcut-in-right-/10064168)._

---
With a given interface, using right-click, I can see several useful options (Go To Base, Go to Definition, and Go To Implementation, etc.). 

**Feature request**: Add a menu item in the right-click menu for "Create Implementation".

When I've recently created an interface or have added an interface to my solution, sometimes I want to easily create a concrete class which implements the interface. This would create the file, name the class, and then connect to an existing VS shortcut. The existing shortcut shows up when using insights (Alt+ Enter / Ctrl + '.') to implement an interface for a class if VS can't find the implemented properties. 

Since interfaces generally prepend an 'I' before the interface name, we can easily create a concrete class in a new file with the remainder of the class name.

---
#### Feedback Bot on 6/7/2022, 08:02 PM: 

(private comment, text removed)

**Comment by JoeRobich** [comment]
### Design Meeting Notes (2022/06/27)
- Different work flow from a lot of our existing functionality.
- Should it default to generating into new file? 
    - Don't want to add more UI for capturing implementation filename.
- In case multiple types need to be generated, should we allow generate without navigating to the generated implementation?
- Feature triggered on interface header.
    - Like that this case is narrow.
- We can generate in the same file and the user can extract as needed.

Move to help wanted.

**Comment by CyrusNajmabadi** [comment]
CLosing out as subsumed by the implement interface lightbulb.
