### ISSUE TITLE
Support ref field assignment in object initializers

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#62120]
```csharp
ref struct R<T>
{
    public ref T F;
}

int i = 0;
var r = new R<int> { F = ref i };
```

See [LDM notes](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-06-06.md#question-3-ref-assignment-in-object-initializers).

Relates to test plan https://github.com/dotnet/roslyn/issues/59194

**Comment by ufcpp** [comment]
```cs
int x = 1;

var a = new A();
a.X = ref x; // error. (a is not scoped.)

var b = new A { X = ref x }; // no error?

ref struct A { public ref int X; }
```

**Comment by cston** [comment]
@ufcpp, the escape scope of the local is set by the initializer unless the local is explicitly declared `scoped`.

For `a`, the initializer value `new A()` can be returned from the current method, so `a` is unscoped. For `b`, the initializer cannot escape the current method, so `b` is implicitly `scoped`. 

The error for `a.X = ref x;` can be avoided by declaring `a` as `scoped var a = new A();`.
