### ISSUE TITLE
`and` and `or` as alternatives to `&&` and `||`

### ISSUE THREAD

**Issue by maxtoroq** [dotnet/roslyn#6212]
This would make programs easier to read.

Category: Boolean conditional logical operators

**Comment by HaloFour** [comment]
Do they provide any additional benefit beyond being easier to read specifically for people who aren't already familiar with the plethora of other languages that share the same Boolean operators?  If not I don't see why it would be worth the effort.  I wouldn't favor this any more than I would favor forcing VB.NET to accept `&&` or `||` as alternatives to its Boolean operators.

**Comment by maxtoroq** [comment]
@HaloFour Not <q>specifically for people who aren't already familiar with the plethora of other languages that share the same Boolean operators</q>, it would make it easier for everyone, including experienced programmer. Syntax matters.

**Comment by HaloFour** [comment]
Consistent syntax matters even more.  You learn it once and done.  There is no reason to have two interchangable sets of operators.  There is especially no reason given that C# has *six* Boolean operators, not two.  What do you propose for the remainder?

**Comment by maxtoroq** [comment]
@HaloFour If that's your argument then why lambda expressions when you have `delegate`?

**Comment by HaloFour** [comment]
Lambda syntax supersedes anonymous delegates as being appreciably superior, familiar and succinct in selector delegates which are incredibly common in LINQ.  You can only continue to use anonymous delegates as a relic of backward compatibility.

Your renaming of the operators provides no benefit, is more verbose and would only provide very temporary familiarity to people who are coming from a non-C/C++ language background.  And there are still four other Boolean operators.

**Comment by maxtoroq** [comment]
@HaloFour Now you are just repeating yourself. Your point is made.

**Comment by alrz** [comment]
How many logical *and* or *or* do you have in your code? Definitely there is something wrong with that and you should solve this unreadability in some other ways. Anywho, `&&` and `||` are more readable to me and they're consistent with corresponding bitwise kinds. I would save `and` or `or` for conjunctive and disjunctive patterns, they would make more sense in that context.

**Comment by maxtoroq** [comment]
@alrz I don't understand, why would there be anything wrong with my code?

> Anywho, && and || are more readable to me

Then continue to use them. I what ways this new syntax affects you or the language in general?

**Comment by mburbea** [comment]
What about the bitwise `&` and `|` operators? 
Sadly, you'd probably have to introduce things like::

`and` for `&`
`or` for `|`
`andalso` for `&&`
`orelse` for `||`

I personally think that I'd prefer to not do this.

**Comment by maxtoroq** [comment]
@mburbea That is not needed.

**Comment by mburbea** [comment]
Why? Says who?
You're ignoring the fact that these operators offer short circuiting behavior.

```csharp
var x = SomeBoolOp() || SomeOtherBoolOp();
var y = SomeBoolOp() | SomeOtherBoolOp();
```
`x` and `y` will have the same value, but the second line will evaluate the *side effects* of `SomeOtherBoolOp`, where as the first line will not. That's a pretty useful distinction and if we offer alternate syntax we should offer it for all variants.

I also question why just these two boolean logic operators? Why not just go full sql and change the unary negation operator with `not`?

**Comment by HaloFour** [comment]
@mburbea And don't forget `xor`.  While we're at it, we should change the name of the compiler from `csc.exe` to `vbc.exe`.

**Comment by alrz** [comment]
Personally I would like to see `complement` operator, regarding readability and consistency.

**Comment by maxtoroq** [comment]
@mburbea I know the difference between `&&` and `&`.

> if we offer alternate syntax we should offer it for all variants.

Why?

> Why not just go full sql and change the unary negation operator with not?

That's not a bad idea, but this issue is about `and` and `or` only.

**Comment by mburbea** [comment]
Ah yes good point, `xor` certainly should be allowed.  :+1: 

Well I'd think that `complement` might be the `~` operator. Where as `not` would be the equivalent of `!`.

What I'm trying to point out is your asking for making C# like vb, but you're not even thinking out these operators as well as the vb team. This would also cause massive confusion to Vb users who would have to remember the different meaning of `and` in C# vs vb.

**Comment by alrz** [comment]
By the way, I don't see any reason that why we can't use `plus`, `division`, `multiply` or `minus` operators. They are very readable.

**Comment by maxtoroq** [comment]
> What I'm trying to point out is your asking for making C# like vb, but you're not even thinking out these operators as well as the vb team. This would also cause massive confusion to Vb users who would have to remember the different meaning of and in C# vs vb.

I had no idea VB had such a bad design. Should C# be constrained by the bad design of VB?

**Comment by mburbea** [comment]
Is it a bad design? Why is `and` obviously `&&`?

**Comment by maxtoroq** [comment]
@mburbea Having `And` and `AndAlso` is a terrible design. First, it's confusing. Second, it saves the best keyword (`And`) for the least used case. Short-circuit is by far the most used and needed behavior. I cannot remember the last time I used `&` or `|` for boolean purposes.

**Comment by alrz** [comment]
> I cannot remember the last time I used `&` or `|` for boolean purposes.

Once I did use the `=` for boolean purposes. e.g. `var boolean_purposes = false;`

**Comment by HaloFour** [comment]
@maxtoroq 

> First, it's confusing. Second, it saves the best keyword (`And`) for the least used case.

You assume that VB was designed initially 14 years ago and in a bubble.  Despite the marketshare-destroying incompatibilities they did introduce it is still largely derived from a 45 year old language where `AND` already had a specific behavior, which did not include short-circuiting.  Converting the existing binary `AND` keyword to a short-circuiting logical operator and introducing a new `BITAND` operator was not well received by the community during VB.NET beta 1.

@alrz 

> Once I did use the `=` for boolean purposes e.g. `var boolean_purposes = false;`

Clearly `var boolean_purposes equals false;` is much clearer.  Actually, `MOVE FALSE TO BOOLEAN-PURPOSES.` is even clearer.  I suggest that C# become COBOL.

**Comment by gafter** [comment]
I don't see how adding these to the language makes any existing programs easier to read. Are you saying that having two different ways of saying the same thing in the language makes programs easier to read, because it adds a bit of variety, thus making the reading experience more interesting?

**Comment by gafter** [comment]
Perhaps you're suggesting we should add these to the language earlier rather than later, to make sure we cannot use them later to express conjunctive and disjuntive types and/or patterns. I mean `&/|` patterns.

**Comment by gafter** [comment]
@alrz 
> By the way, I don't see any reason that why we can't use plus, division, multiply or minus

That's not consistent. Either it is plus, dividedBy, times, and minus, or add, divide, multiply, and subtract. I'm not sure which I like better.

**Comment by gafter** [comment]
Could it be `andthen` and `orelse`? I like Ada.

**Comment by alrz** [comment]
@gafter I like the more expressive version: `if(a andofcourse b orpossibly c) {}`
>That's not consistent.

You're right, it should be `multiplication`, `subtraction`, `addition` and `division` to be consistent.

**Comment by aluanhaddad** [comment]
:-1:

**Comment by dsaf** [comment]
I wanted to suggest custom operators, but it seems that even F# is limiting them to ```!%&*+-./<=>?@^|~``` characters.

**Comment by orthoxerox** [comment]
@dsaf I usually say I like custom operators, but when I take a look at [this](http://jim-mcbeath.blogspot.ru/2008/12/scala-operator-cheat-sheet.html) I am not sure any more.

**Comment by HaloFour** [comment]
@orthoxerox Probably only a matter of time before someone writes the full APL set for Apple Swift.  `life←{↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}`

**Comment by dsaf** [comment]
@orthoxerox I did not say I like them :). This is one of my complaints about F# as well.

**Comment by alrz** [comment]
@HaloFour THAT IS JUST BRILLIANT.

**Comment by orthoxerox** [comment]
@HaloFour I'm not again custom operators per se, they are very good for internal DSLs, but I wish there was a way to restrict them to obvious places in code, just like computation expressions are wrapped in `blah { }` in F#.

On the other hand, I wish `>>=` was a synonym for `SelectMany` everywhere.

**Comment by alrz** [comment]
>On the other hand, I wish `>>=` was a synonym for SelectMany everywhere.

I see what you did there.

**Comment by EgorBo** [comment]
I think at least it would be nice to have "is not" or "isnt".
Let's say I want to check an object that it's not of some specific type:
```
if (!(obj is SomeType))
```
it'd be better to have:
```
if (obj isnt SomeType)
```

**Comment by alrz** [comment]
@EgorBo That would be a *negative pattern* then, since `is` will be used for patterns too, what would happen to pattern variables' scope? There should be new semantics introduced specifically for `isnot` as well. If you aimed for readability I would suggest the whole negative constructs like `unless` and `until` for that matter.
