### ISSUE TITLE
CodeLens showing incorrect user as author

### ISSUE THREAD

**Issue by OldManMeta** [dotnet/roslyn#62125]
**Version Used**: 

Visual Studio Enterprise LTSC 17.2

**Steps to Reproduce**:
you tell me....

**Expected Behavior**:
That it shows the right person

**Actual Behavior**:
It shows the wrong person....

<img width="332" alt="image" src="https://user-images.githubusercontent.com/107874035/175545248-456e4e65-adf3-404f-8abf-13683408a814.png">

To add some context to this - I only have a single account registered with this version of VS. I do have VS2022,2019 community additions installed on the same box, but not in use.

**Comment by CyrusNajmabadi** [comment]
@OldManMeta this is not a roslyn issue. Can you file this using VS' feedback mechanism?  It can then be routed to the right team.

**Comment by OldManMeta** [comment]
Hi @CyrusNajmabadi - If I was on a salary, then I would have all day to search and find the single "correct" way to provide the feedback - but I'm not, so I don't. - I'm searching for a **solution**, which came up with a link to issue #39615 which to me looked out of place also on a Roslyn issue list - but was referring to codelens. So out of courtesy, I throw it in here.

I'll close it - the issue still exists. you decide if you want to fix it and make a better product.

Cheers

**Comment by CyrusNajmabadi** [comment]
> you decide if you want to fix it and make a better product.

The issue is not in roslyn, but is in another plug-in to vs which communicates with codelens. Reporting the issue to the vs team can get it routed properly. We are not that team, this is the open source c# repo. Thanks! :-)

**Comment by CyrusNajmabadi** [comment]
>  I'm searching for a solution, 

That's totally reasonable. However, it's unlikely that someone here will have such a solution. Vsfeedback has a better chance of connecting you to someone who would. Thanks!
