### ISSUE TITLE
Using a custom Interpolated String handler for logging may skip side effects

### ISSUE THREAD

**Issue by cg110** [dotnet/roslyn#62128]
**Version Used**: VS2022 17.2.4

**Steps to Reproduce**:

1. Create a customer Interpolated string handler, that has a last param of out bool isEnabled
2. set isEnabled to false in the handler, eg for a logging handler that's disabled.
3. Log a message where a format has a side effect, eg : $"I'm logging the {i++} entry'
4. find that i isn't incremented.

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

I'll to create one when I find the time, but wanted to get the bug raised.

**Expected Behavior**:

I'm not sure, but I'd expect side effects to happen, the same as they would for string.format("I'm logging the {0} entry", i++);  Or when logging is enabled.

**Actual Behavior**:

i isn't incremented, as all the code is skipped as isEnabled returned false.

Something I also want to check is if function calls aren't made, eg does it skip the string.join:
$"I'm logging the {string.join(",", myListOfStuff)} entry'
and if the call is logging the return of a call this maybe a problem, as the call may never be made.

**Comment by svick** [comment]
This is explicitly called out in [the documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#compilation-of-interpolated-strings) as the correct behavior:

> One side effect of interpolated string handlers is that a custom handler, including `DefaultInterpolatedStringHandler`, may not evaluate all the expressions used as placeholders in the interpolated string under all conditions. That means side-effects in those expressions may not occur.

**Comment by cg110** [comment]
I missed that bit of documentation, as I hadn't seen it mentioned in the examples et. I'd seen.

I'll close the issue, I'm more surprised the default handler might skip side effects. I'd have assumed it would just be those that return false for the isEnabled out flag that do.

I suspect if internally I have an enabled flag that throws everything away the side effects would mostly happen as the Append calls still happen (although probably slower than the out bool)

**Comment by cg110** [comment]
Note as mentioned, if I don't use the out bool, but instead check an enabled flag in the AppendLiteral/Formatted calls it does do the side effects (which matches current behavior)

While I anyone relying on side effects in a logging line is probably doing something wrong, I'm sure someone will/is, and don't want the pain of debugging it, as the first request will be can you repro the issue with logs on, and it'll start working.

Perhaps I'll add an alternate Unsafe/No Side Fx function or mechanism to my logging apis.
