### ISSUE TITLE
Source Generators does not work with multitarget dependencies

### ISSUE THREAD

**Issue by QuantumDeveloper** [dotnet/roslyn#62148]
**VS 2022 17.3.0 Preview 2**: 

I have Source Generator which are using local project reference with multitargeting (`netstandard2.0; net6`)

When I have multitarget references roslyn cannot load correct version and simply says that it cannot load referenced dll.

But if I remove multitargeting and leave only `<TargetFramework>` tag, generator starts working correctly.

So, seems source generators does not support multitaget references.

Issue here is that I need multitargeting in my projects. Does this issue can be solved somehow? Or maybe I am missing something?

**Comment by jaredpar** [comment]
The strong recommendation is that generators and analyzers target `netstandard2.0` only. The compiler runs on a variety of runtimes and the only TF that is supported by all of them is `netstandard2.0`. 

It is possible to construct a multi-targeted generator but it is considered an expert level scenario. It requires a lot of custom build authoring. While it can be done we do not recommend anyone does it.
