### ISSUE TITLE
API Review Followup - MSBuildProjectLoader APIs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6215]
These are the remaining items from our 1.1 API review:

- MSBuildProjectLoader.LoadProjectInfoAsync should take ImmutableDictionary parameters
- MSBuildProjectLoader.LoadSolutionInfoAsync should take ImmutableDictionary parameters

**Comment by mavasani** [comment]
Ported from https://github.com/dotnet/roslyn/issues/6044

**Comment by Pilchie** [comment]
Fixed by #6395.
