### ISSUE TITLE
Generated constructor with invalid parameter name

### ISSUE THREAD

**Issue by tfenise** [dotnet/roslyn#62162]
**Version Used**: 

Microsoft Visual Studio Community 2022, 17.2.5

**Steps to Reproduce**:

1. Enter the following code in a C# project in Visual Studio.
```
class MyClass
{
    int _0;
}
```

2. Let the IDE generate a constructor including the field `_0` for me. (Right click on `MyClass`)

**Expected Behavior**:

The IDE generates a functional constructor.

**Actual Behavior**:

It generates:

```
class MyClass
{
    int _0;

    public MyClass(int 0)
    {
        _0 = 0;
    }
}
```

**Comment by ShahriyarB** [comment]
What would you suggest for the name of _0 variable in the constructor?

**Comment by ShahriyarB** [comment]
What would you suggest for the name of _0 variable in the constructor?
