### ISSUE TITLE
Unused usings not faded

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62183]
In, 17.3 Preview 2, open Compilers.sln, open any file and add unused using statement. It's not faded, however, pressing <kbd>Ctrl</kbd>+<kbd>.</kbd> offers to remove it.

![image](https://user-images.githubusercontent.com/31348972/176157140-25464d4b-6d95-4cdd-ab3b-da5974907e84.png)

cc @CyrusNajmabadi @tmat

I have the fade out option in Tools → Options checked:

![image](https://user-images.githubusercontent.com/31348972/176157617-296ba61b-1f97-4ad9-b343-a89244fcc8ca.png)

I'm not sure if this is the same root cause as https://github.com/dotnet/roslyn/issues/61844

**Comment by CyrusNajmabadi** [comment]
@mavasani @sharwell ?

**Comment by tmat** [comment]
Looking now.

**Comment by tmat** [comment]
I can't reproduce with the latest main build. Both LSP and non-LSP seems to work fine.

**Comment by Youssef1313** [comment]
@tmat fwiw, it's not consistent on my side. It randomly works and randomly stops working.

**Comment by colgreen** [comment]
I have this problem in VS 17.2.4 (and just upgraded to 17.2.5, and still the same).  The quick menu option to remove unused imports works fine, but the redundant imports/using are never greyed out now.  I would guess this was a recent VS update that did this, my best guess is 17.2.3 as it's been a problem for a while now.

**Comment by colgreen** [comment]
It seems to work for me here for a fresh clone of this repo and opening Compilers.sln. However...

In an unrelated Visual Studio solution at my workplace we had this same problem, but it was persistent (not intermittent). Today I was able to prevent the problem (i.e. make the redundant 'usings' show greyed out) by switching off the following setting in the csproj files (actually set in a single .props file in the root folder of the repository):

     <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

Either set to false or comment out. Maybe it's the same root cause and this bit of info will help find the underling problem.

**Comment by mavasani** [comment]
@Youssef1313's observation is correct. @tmat below commit seems to have introduced this regression: https://github.com/dotnet/roslyn/pull/58765/files#diff-79a48e9c4861b0c6822ce70a5385deb3a520730889acd0bc8a33b1f904f9a0feL168-L175

Earlier, we use to default to always fading the unnecessary imports and unreachable code for analyzer shipping in the CodeStyle layer. With this change, we default the fading to false. Was there a specific reason for switching this default or just an oversight? If the latter, I'll create a PR to fix this up.

**Comment by mavasani** [comment]
FWIW, I think even the prior implementation of having the analyzer determine whether the diagnostic should be faded or not by looking at the option seems incorrect. Fading is a host concept, not something for the analyzer to determine. IMO, the analyzer should always add the `Unnecessary` custom tag to the diagnostic it reports to indicate fading, and the it should be the responsibility of the tagger that fades based on `Unnecessary` custom tag to look at the option and determine whether it should skip fading if user prefers such. I think this pattern should be followed for all fading diagnostics, not just the unnecessary imports one.

**Comment by Youssef1313** [comment]
> Earlier, we use to default to always fading the unnecessary imports and unreachable code for analyzer shipping in the CodeStyle layer. 

That means if someone *unchecked* "Fade out unused usings" and is using CodeStyle package, the option will have no effect? Probably *always* fading out and removing the UI options is something to consider?

**Comment by Youssef1313** [comment]
> IMO, the analyzer should always add the Unnecessary custom tag to the diagnostic it reports to indicate fading, and it should be the responsibility of the tagger that fades based on Unnecessary custom tag to look at the option and determine whether it should skip fading if user prefers such. I think this pattern should be followed for all fading diagnostics, not just the unnecessary imports one.

The page refreshed and this comment appeared just after I commented. Yeah that seems more reasonable than my suggestion to remove the UI option.

**Comment by mavasani** [comment]
> Probably always fading out and removing the UI options is something to consider

That is the second alternative, I think it might be better to follow https://github.com/dotnet/roslyn/issues/62183#issuecomment-1181338289. Given these fading related options exist, I presume there was some desire/feedback to allow users to control the user experience, so I think we may want to continue supporting them.

**Comment by mavasani** [comment]
Thanks, let me work on a PR to clean this up for all fading diagnostics.

**Comment by mavasani** [comment]
Created #62562 to fix this issue. 

However, we would need to ship a new CodeStyle NuGet package in the .NET SDK with this fix to get back the fading when users specify `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>`.
