### ISSUE TITLE
API proposal: Expose functionality of `SyntaxGenerator.TypedConstantExpression` via a better method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62181]
## Background and Motivation

`SyntaxGenerator.TypedConstantExpression` is a very useful API, but it accepts `TypedConstant` parameter. In most cases (except attributes), we don't (and maybe can't) have `TypedConstant`.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Editing
{
     public abstract class SyntaxGenerator : ILanguageService
     {
+        public abstract SyntaxNode ConstantExpression(ITypeSymbol? type, object? constantValue);
     }
```

Implementation for C# will directly delegate to the internal implementation here:

https://github.com/dotnet/roslyn/blob/a3015838ebea9773834c42322dc129fb392b5d27/src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs#L52-L75

## Usage Examples

This can be very useful in code fixes, especially for producing flag enum values (but that's not only the useful case).

**Comment by Youssef1313** [comment]
Note that the internal API is used by some codefixes in Roslyn itself, and this is blocking moving these codefixes to the shared Analyzers layer.

cc @mavasani

**Comment by CyrusNajmabadi** [comment]
Which existing features that you want to use this API would pass false for `bool canUseFieldReference`?  My preference would be to not expose that flag and always treat it as true.

**Comment by jcouv** [comment]
Assigned to area owners. Please re-assign and move to an appropriate milestone when a decision is made.

**Comment by CyrusNajmabadi** [comment]
No movement has happened on this.  Closing out as not needed.
