### ISSUE TITLE
GoToDefinition integration tests failed due to empty file

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#62188]
The dump is here:

https://dev.azure.com/dnceng/public/_build/results?buildId=1848470&view=artifacts&pathAsName=false&type=publishedArtifacts

The go to definition integration test failed and hung the test because it displayed the "unable to navigate" dialog. Looking at the Compilation in the dump, it appears the source file that would have contained the definition is empty. I don't see a _loadDiagnostic in the state which implies either the file was actually empty or we had some failure to read it.

**Comment by jasonmalinowski** [comment]
@sharwell Any chance this is a duplicate of something you're already looking at?

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't seen this recently.
