### ISSUE TITLE
Null coalescing does not work as expected with types that have implicit operators

### ISSUE THREAD

**Issue by Goolyio** [dotnet/roslyn#62184]
**Version Used**: 6.0.101

**Steps to Reproduce**:

1. Create a type that utilises implicit operators so no explicit type conversions are required when returning from a method. For example a result wrapper that looks like
```csharp
public struct ResultWrapper<T, E>
{
    private readonly T _value;
    private readonly E _error;
    
    public bool IsSuccess { get; }
    
    public T Value => IsSuccess
        ? _value
        : throw new InvalidOperationException("Cannot get the value as the result is unsuccessful");
    
    
    public E Error => !IsSuccess
        ? _error
        : throw new InvalidOperationException("Cannot get the error as the result is successful");
    
    internal ResultWrapper(bool isSuccess, E error, T value)
    {
        if (isSuccess)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
        }
        else
        {
            if (error == null) throw new ArgumentNullException(nameof(error));
        }

        IsSuccess = isSuccess;
        _value = value;
        _error = error;
    }
    
    public static implicit operator ResultWrapper<T, E>(T value) => new ResultWrapper<T, E>(true, default, value);
    public static implicit operator ResultWrapper<T, E>(E error) => new ResultWrapper<T, E>(false, error, default);
}
```
2. Create a function that could potentially return the type `T` or `E`. For example,
```csharp
public static ResultWrapper<string, int> ExampleFunctionWithResultResponse()
{
  // Content
}
```
3. Make a call to something that could potentially return a null response. An example could be
```csharp
public static string RespondWithPotentiallyNull()
{
  var unknownAtCompileString = Console.ReadLine();

  // Could either return a string with the value "meme" or null
  return unknownAtCompileString == "true" ? "meme" : null;
}
```
4. Within the function created in step 2 (`ExampleFunctionWithResultResponse`) invoke the function created in step 3 (`RespondWithPotentiallyNull`) and then do a null check using the null coalescing operator `??` to return either a `string` or `int` from the function (both will be implicitly converted into the type `ResultWrapper<string, int>`).
```csharp
public static ResultWrapper<string, int> ExampleFunctionWithResultResponse()
{
  var potentiallyNullString = RespondWithPotentiallyNull();
  
  return potentiallyNullString ?? 400;
}
```

**Expected Behavior**:
Compiles with no warnings, implicit type casts are added during the first steps of compilation and works the same way as if the null check was done in a ternary that looks like.
```csharp
return potentiallyNullString is not null ? potentiallyNullString : 400;
```

**Actual Behavior**:
Does not compile and shows the error `error CS0019: Operator '??' cannot be applied to operands of type 'string' and 'int'`.

[Broken null coalescing example](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFAEg1uVAzAAlnuAdmQG9kVYZyykc766A3AQwCcdWBTAZwFcAbAC44AvDgCiAD2YBbAA79OUAKyCAlgHsAdgHU1ggBYA5AfwDCG5ou4BjNVoDmACgCUAbnIBfZAx/1sBABsOABKPAKCOqzMcnKcrAA8UHAADAA0OPaCAHwS0vKKKuraeoYm/OaW1naOrn50NAwMLOxyGoKcWupW/ACe5fxh3G1a3JyioTwjwKUGAArtnd0V/aauHrRNdPVNAPS7OACSAGY4huNcw9pjmdw4WqZHOADuzF1nGniEOMwc4UIvfQGH5aTJdTgOeKZU5adpnAydL7w8bJFI7XybLZQb5tDpdNQ9VYVIYjG4AfjJOAALCkUhsGN5UOQAslgkMIlEYnFEqiMllcgBxTiCdlCJwAIw0Gn4twAKqxeJwXNRyBRvmpuPLFThKQAiAxqXU4EA4OAbFCMjEMFlwYKoyZXLQzIELPHLPoDOqYnCNLY4dH0Fo4XhaADWsOeWgAgoILPI1IoAMqCVj2BwTCyjaWcAB0YWYwAAMvZOOsA9tvdbviHwxpIzG43IE5xk6nHKIxLqU4qjXqZJx+0aTQ8KvT6IzGch9jgo6DOPkFONuN2bMJDMxhLx1PwNTwQZkCmo7MINNyNxpWJhcMuFauHRzorF4glZRlxNlSDs5KmWB0/gXtD6HBZRwAB9Fh+EVMc6G/NRfwuTgAK0IDxDA+JWAvaD/W9AJJWlI5uETXgbBsHg7hIHBIUENwcEtegdgCECADUrG1ERckOQjiNI7huHLHUwIgxV+JNQwMOee5OAkw4tAgtRgAAeTPYotCkUi5BUpxdTMN5YWEKjkRwITxmYO5zj+PgAQ1YNRm4sjjgEXV3B2FycNwVDxFYDD2HYnAAEJOKIkiyP4ylQPQi8RPhcTJOk2SrHkpT4g3TRVMkdTNO03S4QM8yIvYUzDMuCJbhwPhgt4hz+CcrCdiyeItCse8hE5J9WAlKUZQ1IKeO4N8cHyjIQOM5VvV9LY1FOJxurs3jRr9H1+IYSacCcYyO3uUwXGiutYpnVgHF4fsugGNTOA01KnEa/sNGONbWKVZzK3HfjOH4MZ+PGhboVW/KNpHfhtrE3atCk/bDuOwRTvS87NOuzhbqcfKXCehbJ2euhAtmu4xBmiruCwhhwIeiZjMJ+hwq8i8JnyrC6Ira1cFZA8FCPfQcFPZLBGp0VIkfbkXzfbInGGh7tt80GJN51qBdfCRhe7TgMmAThjmYCIMhGrCbWCNRD2PDnlJ5/4+a5Z85ffJxUOR0Rckl5rTbawX5acNX3qVgaqdYZXVfVoQns8IA===)

[Working ternary example](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFAEg1uVAzAAlnuAdmQG9kVYZyykc766A3AQwCcdWBTAZwFcAbAC44AvDgCiAD2YBbAA79OUAKyCAlgHsAdgHU1ggBYAVTqy1sAngAoAlAG5yAX2QMX9bAQBsOAEo8BgjqszHJypgA8UHAADAA0OGpaggB8EtLyiirq2nqGJmaWtm50NAwMLOxyGoKcSWrM/PwWAHIC/H7cVVrcnKK+PF3AuQYACtW16g1NrY22DrRldMVlAPQrOACSAGY4hr1cndo9Cdw4Wm2bOADuzEm7GniEOMwc/kLX+gbPWglJnADmpgSOy01V2Blqj3BvSi0WWrgWiygTyqNTqUxabQ6XWOalOoOE50aOAA/DhURN6o1MY1sUdeiAcAAWaLReYMZyocgeKLeDoBIIhMKsSIxeKJFI4ADinEE/KEVgARhoNPwTkZWLxODZqOQKE88RqtaScAAiAxqU04RlweYoTkIhg8uDeWH9Q5aIafMZoybUmb8IqInClRY4eH0Co4XhaADWoKuWgAgoIAMIaeRqRQAZUErES/z66e6qs4ADo/MxgAAZRKcOYRpbBp1PGPxjSJlPpzM5vMF0RiU15rVWsmmmScCdWxlE/js+icznINY4JM/TjpBS9bjDgDGwkMzGEvHU/DxPG+CQyal3+hwGmFR40rEwuB3mv37oFwVCESM8XEZJSGWOR8xYGpXirbQmhwIwcAAfRYfgtXnOhQLUcD9k4KCtBg8QENMVhn1Q8Ngw8ZVVU2bhs14Xddx4U4SBwQFBDsHAHXoZYPDggA1BpjREVINmo2j6O4bhGxNRD+M4STGUMIirjOTglI2LQkLUYAAHlH2yLQpHouQ9KsU1U1uAlmNlaEcCQ41mFOPZXj4d48WjbpRIYrYBFNexlj8sjcHw8RWCI9hBJwABCYSaLohjJLJeDCOfOTwUU5TVPUhpNJ00wj00fTJEM4zTPMsEWOspL2Hs6yDgCE4cD4WLxK8/gfJI5YJVMcw1XlQIf2FJUVTVPEYrE7gAJwSr4jg2ztWWUNFjUHYrBGjzxJ1Zt6AWsM6CWnArFmgczjaGxUo7dLV1Yf5eAnJIAwMzgjPyqxzAnDQtgOmSbF8za6A4xZOH4HpJO2na9qsSqjtnU6FPOrQVMu67bsEe7Cse4zXs4d6IZC59vpIjlkEk6K1tOMRVqa7gCfoaTkN6MRZupuhEtxsLJtZkj/tIp1cF5K8FBvO8H1ywRny/IRBV/EV/wkZIrBmr7RFSeGlN6yXhXCGXAKsYdOHiYBOC2ZgAniWafp5rx+bPW9hGF4JRfYNX+r/AC5fwyrTvClXxb6oUXdlqwjaBvX2dC/XDeNoQfscIA=)

**Comment by jcouv** [comment]
I'll follow up to confirm, but I think this is by-design.
We implemented target-typed conditional ([spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/target-typed-conditional-expression.md)) in C# 9. That feature did not include `??`, but I don't remember the reason why.

**Comment by Goolyio** [comment]
> Found some discussion in comments: [dotnet/csharplang#2460 (comment)](https://github.com/dotnet/csharplang/issues/2460#issuecomment-485742745) There was a proposal to change language: [dotnet/csharplang#2473](https://github.com/dotnet/csharplang/issues/2473) but it was not accepted.
> 
> Here are the notes:
> 
> > When attempting to spec and implement this, we found that it doesn't actually work well in practice, as ?? has a number of complicated rules around type resolution already and what part should be target-typed is confusing. We believe that, given the investigation, we won't be moving this one forward, and it moves to the Likely Never milestone.
> 
> I'll go ahead and close this as by-design, unfortunately.

Ah interesting, thanks for looking ❤️
