### ISSUE TITLE
Inheritance margin not working for interactive workspace

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#62229]
Talked to @jasonmalinowski  offline about this
![Interactive](https://user-images.githubusercontent.com/24360909/176327578-61d4bc13-e1ee-4bf2-9872-ff724845a4c9.gif)

Press F12, navigate from Interactive workspace to metadata workspace, 
then it can't navigate back

**Comment by CyrusNajmabadi** [comment]
@arunchndr need to decide if we're investing in interactive experiences.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in interactive experiences.
