### ISSUE TITLE
Editorconfig UI failing to do anything

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#62232]
**Version Used**: Version 17.3.0 Preview 2.0

**Steps to Reproduce**:

1. Create a new .editorconfig file
2. Attempt to change the `var` preferences

![Editorconfig not saving](https://user-images.githubusercontent.com/2371880/176353389-84d46521-33a8-459e-ba22-34e0fec24065.gif)

**Expected Behavior**:

Editorconfig setting is updated.

**Actual Behavior**:

Editorconfig setting _appears_ updated. Reopening the file shows that it is not.

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/56676
Duplicate of https://github.com/dotnet/roslyn/issues/54556

@jmarolf This has been reported too many times now 😕

**Comment by 333fred** [comment]
Closing as a duplicate of https://github.com/dotnet/roslyn/issues/54556

**Comment by jmarolf** [comment]
focusing on this today

**Comment by davidwengier** [comment]
> ptal a look

ATM machine
