### ISSUE TITLE
Severe ConditionalWeakTable contention observed on TryParseConversionOperatorDeclaration failure path

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62238]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/RoslynCodeAnalysisService-takes-up-all-m/10071654)._

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1555394

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.11.10]
Since I updated to Visual Studio 2022 I have many problems with the memory occupation of RoslynCodeAnalysisService process.

Many times it occupies all the available memory and makes other running programs crash due to memory unavailability:
![image.png](https://aka.ms/dc/image?name=Ba2147add068b4ca0b5277000edc2fa9b637908835243360859_20220615-115202-image.png&tid=a2147add068b4ca0b5277000edc2fa9b637908835243360859)

Once it made the video card driver crash too, reducing the screen resolution to 640x480.

Is it possible to limit the RoslynCodeAnalysisService to 32 bit to avoid high memory consuption? This is causing huge problems.. I am thinking to go back to Visual Studio 2019, and it is a shame.

---
#### Feedback Bot on 6/15/2022, 10:40 PM: 

(private comment, text removed)
#### Francesco Formenti on 6/16/2022, 00:34 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 6/16/2022, 09:14 AM: 

(private comment, text removed)
#### Francesco Formenti on 6/20/2022, 02:55 AM: 

(private comment, text removed)
#### Francesco Formenti on 6/17/2022, 01:09 AM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2022, 07:19 AM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2022, 07:43 AM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2022, 07:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
From @sharwell:
>this appears to be a regression caused by:
[Support syntax for explicit implementation of conversion operators (#… · dotnet/roslyn@847f9c6 (github.com)](https://github.com/dotnet/roslyn/commit/847f9c60edcf75262c4aaa9264419f323955ae6c)

>The heap dump shows 48 threads contending for the ConditionalWeakTable lock to add annotations (specifically diagnostics) to the missing explicit token created in TryParseConversionOperatorDeclaration.
