### ISSUE TITLE
Allow a ref field to refer to a ref struct type

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#62243]
Currently, `ref` fields cannot refer to `ref struct` types.

```csharp
ref struct R1<T>
{
}

ref struct R2<T>
{
    public ref R1<T> F; // error CS9050: A ref field cannot refer to a ref struct.
}
```

See https://github.com/dotnet/roslyn/pull/62186

See also https://github.com/dotnet/roslyn/issues/62098

**Comment by SK-Genius** [comment]
And Allow it recursive:
```c#
ref struct ParentIds
{
    int Id;
    readonly ref ParentIds Parent;
} 
```
without

> error CS9050: A ref field cannot refer to a ref struct

and

> error CS0523: Struct member 'ParentIds.Parent' of type 'ParentIds' cause a cycle in the struct layout

**Comment by SK-Genius** [comment]
Maybe also introduce something like
```c#
ref struct ReadOnlyRefStack<T>
{
    T Item;
    readonly ref readonly ReadOnlyRefStack<T> Prev;

    //[...]
}
```
and
```c#
static string Join(ReadOnlySpan<char> seperator, params ReadOnlyRefStack<string> values) => // ...
```

**Comment by jaredpar** [comment]
Closing as this is less a compiler issue and more a language design issue.

**Comment by Delsin-Yu** [comment]
What would be the appropriate repo for this issue? And why does this issue get closed as `completed`?

**Comment by RikkiGibson** [comment]
csharplang would be the place for it, yes.

**Comment by Delsin-Yu** [comment]
Thanks, I have opened [the discussion](https://github.com/dotnet/csharplang/discussions/9152) there.
