### ISSUE TITLE
Switch expression using pattern matching on floating point values reports wrong result for double.Nan

### ISSUE THREAD

**Issue by colgreen** [dotnet/roslyn#62241]
**Version Used**: dotnet 6.0

**Steps to Reproduce**:

Run this console app, taken from: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns

```
Console.WriteLine(Classify(13));  // output: Too high
Console.WriteLine(Classify(double.NaN));  // output: Unknown
Console.WriteLine(Classify(2.4));  // output: Acceptable

static string Classify(double measurement) => measurement switch
{
    < -40.0 => "Too low",
    >= -40.0 and < 0 => "Low",
    >= 0 and < 10.0 => "Acceptable",
    >= 10.0 and < 20.0 => "High",
    >= 20.0 => "Too high",
    double.NaN => "Unknown",
};
```

**Expected Behavior**:
Output of:

High
**Unknown**
Acceptable

**Actual Behavior**:

High
**Too high**
Acceptable

---

SharpLab currently shows the prblem in the lowered C#:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+WRiqQLIAUAJhAK7AAbGKQQBKUvUZ0CjWeRwAGUgFsAzgHNSAXhGlVAdwCWAFzAALWpLlyAPKTgoFAOiVaAfKQBEAFQgRSAhD6ngA0VtaMbjoOzkoAhgB2XKR2rh6eADJBoeERpFGk8UkppIou2ukAgmBgMAAOxnGCMDkyeZE6ZUXJdlixFV4AEobqZq3tHaR95e5evv5mI2NhbRM8/EJOAHJxWwOeAKoJANYJQQnjEQC+ANwRhOFX4YRXQA===

```
    public void M(double x)
    {
        if (x < 10.0)
        {
            if (x >= -40.0)
            {
                if (x < 0.0)
                {
                    string text = "Low";
                }
                else
                {
                    string text = "Acceptable";
                }
            }
            else if (x < -40.0)
            {
                string text = "Too low";
            }
            else
            {
                string text = "Unknown";
            }
        }
        else if (x < 20.0)
        {
            string text = "High";
        }
        else
        {
            string text = "Too high";
        }
    }
```

I.e. the 'Unknown' result is nested inside the x < 10 branch, and NaN is not less than 10! (I believe it returns false for all comparison operators).

**Comment by gafter** [comment]
oops.  Mea culpa.

**Comment by jcouv** [comment]
@gafter No worries. This is a pretty subtle issue. For the moment, I disabled the optimization because I couldn't think of a good fix to maintain it, let me if you had some ideas on that.

**Comment by gafter** [comment]
Just off the top of my head, I would try to avoid "inverting" relational operators.  That may require keeping a flag in the balanced tree of values for which sense of the comparison operator should be used.

An alternative is to handle the NaN case first, though that is a little unfortunate because NaN is typically an uncommon case.
