### ISSUE TITLE
Suppress active issues generates global suppressions for diagnostics at top level in files

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6225]
1. Create a C# project with below code:

    ```C#

    // Global comment with trailing whitespace    
    ```
2. Install the CodeCracker analyzer from nuget.org
3. Build solution and verify diagnostic CC0065 in error list.
4. Increase severity of CC0065 to a warning using the ruleset editor/solution explorer
5. In the solution explorer click on the project -> Analyze -> Suppress active issues

**Got**: We generate a global suppress message attribute with no target member symbol:

```C#
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0065:Remove trailing whitespace", Justification = "<Pending>")]
```

**Question:** Above attribute does suppress the diagnostic correctly, but because it does not belong to any specific symbol, the suppression occurs across the entire project. Should we consider generating a pragma suppression for diagnostics at top level of documents?

**Comment by srivatsn** [comment]
The behavior as it stands is worse than doing nothing because this turns off the rule entirely for the project and the point of baselining is to allow for new issues from this rule to be seen. We should probably just not add suppressions at all for such rules.

**Comment by srivatsn** [comment]
We've decided to keep the current behavior and revisit as we get feedback. If we have a different mechanism for scoping suppressions (like maybe attributes everywhere) then this may be doable.
