### ISSUE TITLE
Are `Microsoft.CodeAnalysis.Location` instances safe to cache in Incremental Source Generators?

### ISSUE THREAD

**Issue by dferretti** [dotnet/roslyn#62269]
Hello!

I am working on an incremental source generator, and trying to follow all the steps to make it cache friendly. 
Specifically, I am building up my own simple domain model that contains just a few strings and other things from basic interfaces it analyzes, and gathering them very early on in the collecting/transforming phases of the generator (step 1 to be exact). This comes from the advice here: https://github.com/dotnet/roslyn/blob/931d6c735cfaee43582071983b615fcc45ca76bf/docs/features/incremental-generators.md#authoring-a-cache-friendly-generator

Everything is working fine - I can read in the Semantic Model and collect the data I need, and I can build and cache these simple models that all implement IEquatable/Equals/GetHashCode/etc.

However, now I would like to include some error Diagnostics for certain business cases that my generator will not support. Hitting the same issue as described here: #57965, it seems I have to update my domain model to contain successfully constructed models as well as some basic diagnostic lists, so I can thread both of those through to the Source Producing Context later on.

Is it safe for me to include the `Location` instances I read from the symbols? Or are those large / hash-unstable or otherwise things that shouldn't be cached (like the symbols themselves)? Or should I go further and just create the full `Diagnostic` inside my `Select` transformations - and trust those aren't too big and can be cached?

Looking more closely I can see that is what is going on in the PR linked from that above issue: #54379. I just want to make sure because I noticed the Location class has a reference to `SyntaxTree` which seems like something that could be large.

**Comment by CyrusNajmabadi** [comment]
Could you store a tuple of the file path and span you care about?  That would be small, value-safe, and would have the same semantics as what you have today.

**Comment by dferretti** [comment]
Thanks for the quick response! Yeah that looks like it could do the trick. Once I find any symbol's `Location`, I can extract `location.SourceTree.FilePath`, `location.SourceSpan`, and `location.GetLineSpan()` which all look good. And then that is enough for me to use `Location.Create(filePath, textSpan, lineSpan)` on the other side.
