### ISSUE TITLE
Visual Basic Move Static Members: Refactoring one of multiple fields incorrectly formats whitespace

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#62283]
**Version Used**: 
Visual Studio 17.3 Preview 3

**Steps to Reproduce**:

1. Create a new VB console app
2. Paste the following code: 
```
Class Program

    Public Shared Foo As Integer, Bar As Integer

End Class
```
3. Select `Foo` and activate the "Move static members to another type..." dialog box, and select only Foo. Use the provided default class creation and press OK.

**Expected Behavior**:
In the new created file:
```
Class ProgramHelpers

    Public Shared Foo As Integer

End Class
```

**Actual Behavior**:
```
Class ProgramHelpers

    Public Shared Foo As Integer End Class
```
This causes an error as the end class block should be on a separate line (errors BC30481 and BC30205)

It is fairly easy to fix manually, but it does introduce an annoying error that it really shouldn't. I suspect this is an issue with other refactorings that "split" multiple fields declared on the same line (there aren't many of these with VB support), and may be a problem with our syntax generator.

**Comment by Youssef1313** [comment]
`FieldGenerator.GenerateFieldDeclaration` produces an elastic marker. So I think something is wrong with elastic trivia handling?

**Comment by Youssef1313** [comment]
![image](https://user-images.githubusercontent.com/31348972/177013293-b3d9f5c7-d4d8-4769-939a-017419badb47.png)

😕

**Comment by Youssef1313** [comment]
We were reusing the original syntax, which doesn't have trivia :)

Fixing in #62346
