### ISSUE TITLE
Should Remove Suppression(s) be more aggressive in deleting pragma suppressions?

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6229]
1. Create a C# project with below code:
```C#
#pragma warning disable CC0065 // Remove trailing whitespace
class C
{
    // Global comment with trailing whitespace    
}
#pragma warning restore CC0065 // Remove trailing whitespace
```

2. Install the CodeCracker analyzer from nuget.org
3. Open error list, change the filter for "Suppression state" column to also show suppressed issues.
4. Select suppressed diagnostic CC0065 in error list -> Remove suppression(s)

**Got**: We correctly un-suppress the given diagnostic and it becomes active now. However, the final code seems a bit cluttered - one may have expected just to see existing pragmas getting removed.

```C#
#pragma warning disable CC0065 // Remove trailing whitespace
class C
{
#pragma warning restore CC0065 // Remove trailing whitespace
    // Global comment with trailing whitespace    
}
#pragma warning disable CC0065 // Remove trailing whitespace
#pragma warning restore CC0065 // Remove trailing whitespace
```

**Question:** Current implementation for Remove Suppression code fix tries to look for a pragma disable and enable on leading trivia of start token and trailing trivia of end token on the line containing the diagnostic. If we find both, then we just remove them and unsuppress the diagnostic.
However, if we don't find such a pair, we assume that any pragma disable/enable pair suppressing this diagnostic instance is applied on a broader scope (which is true for this example as it is applied for the entire class definition). In this case we instead wrap the current diagnostic line with a pragma enable/disable pair to turn on the diagnostic just for this line.
This gets us the desired unsuppression, but leads to lot of cluttered pragmas in code (and the number keeps growing as you roundtrip between suppress/remove suppression).

We may want to consider being more aggressive here and instead look for any enclosing disable/enable pair (any number of lines apart) and try removing it? We may end up un-suppressing more diagnostics, but that is probably ok as user has option to then apply more fine grain suppressions around individual diagnostics.

**Comment by srivatsn** [comment]
This behavior is less than ideal but if we had remove unused suppressins as a feature then this could get cleaned up with that fix. Won't fixing this bug for that reason.
