### ISSUE TITLE
Diagnostic reported for `scoped` modifier on non-ref struct type should be a warning only

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#62318]
CS9048 should be a warning, not an error.

```csharp
static void F(scoped int i) // CS9048: The 'scoped' modifier can be used for refs and ref struct values only.
{
}
```

**Comment by jaredpar** [comment]
Closing as we decided to leave as an error for now. The primary motivation was making it easier for generators by not requiring them to do semantic lookup on types before adding `scoped` to them. Will revisit if that turns into a real problem.
