### ISSUE TITLE
GetAllowedModifiers for record struct should not include 'ref'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#62325]
https://github.com/dotnet/roslyn/blob/1fcfda544da9cb4980da03d46bc753424172b75a/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1459-L1464

https://github.com/dotnet/roslyn/blob/1fcfda544da9cb4980da03d46bc753424172b75a/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1497-L1499

'ref' is not allowed on 'record struct' declarations. Should we make a change to disallow the 'ref' modifier here?

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
