### ISSUE TITLE
EndToEndDeterminismTest should use `Temp.CreateDirectory`

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6233]
This causes us to leave many temporary directories strewn about at the end of tests like VBCSCompilerTests/CompilerServerTests.cs

**Comment by TyOverby** [comment]
@agocke

**Comment by tmat** [comment]
TempRoot should be disposed by xunit calling the test class Dispose.

**Comment by agocke** [comment]
@tmat Iff you use the one in TestBase, right? This makes sense -- @TyOverby's PR had the creation of a temp root outside TestBase and I couldn't figure out how it was supposed to be disposed. It looks like you're never supposed to create your own TempRoot, is that right?

**Comment by tmat** [comment]
You can. You just need to make sure to dispose it. If the test class implements IDisposable xunit disposes it. Why don't we inherit from TestBase though?

**Comment by agocke** [comment]
@tmat In this case I think the class can just inherit from TestBase.

**Comment by agocke** [comment]
@TyOverby I think this bug can be resolved by just changing https://github.com/dotnet/roslyn/blob/11c0850cda9993bb4b66227a25a919174d3fe808/src/Compilers/Core/VBCSCompilerTests/EndToEndDeterminismTest.cs#L24 to call `Temp.CreateDirectory()`

**Comment by TyOverby** [comment]
@agocke That looks about right.  I'll make that change when I add more end-to-end tests.
