### ISSUE TITLE
Why doesn't this code work?

### ISSUE THREAD

**Issue by Mr0N** [dotnet/roslyn#62342]
### Description

![image](https://user-images.githubusercontent.com/61237140/177000675-fcc0d23f-1046-4a96-b10d-f8bd303f0b21.png)
Why doesn't this code work?

### Reproduction Steps

    
using (result.archive) { }
                using (result.image) { }
            using var ccc = File.OpenRead("");
            using (result.archive);
            using (result.image) ;
            using result.archive;
            using result.image;

### Expected behavior

=-------------------

### Actual behavior

=----------------

### Regression?

==

### Known Workarounds

=

### Configuration

=---------------------- 

### Other information

=--------------------------

**Comment by Youssef1313** [comment]
It's not allowed per the language grammar:

https://github.com/dotnet/roslyn/blob/1fcfda544da9cb4980da03d46bc753424172b75a/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4#L521-L523

https://github.com/dotnet/roslyn/blob/1fcfda544da9cb4980da03d46bc753424172b75a/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4#L702-L704

If you don't use parentheses, then `using` should be followed by a variable declaration (in your example this is `using var c = ....`

**Comment by Mr0N** [comment]
> 



> 

And why not, the semantics are similar, in theory it should work.

**Comment by Mr0N** [comment]
![image](https://user-images.githubusercontent.com/61237140/177002152-4464cacd-cb39-48e9-9c3d-f7a24e1d89bc.png)
Either way, it doesn't work that way either

**Comment by CyrusNajmabadi** [comment]
> And why not, 

Because it has identical syntax to a using directive (which is already allowed). E.g. `using System.Collections;`.  

So that would be entirely ambiguous syntactically at the top level.
