### ISSUE TITLE
Document breaking change regarding interface usage as type argument

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62355]
It looks like the breaking change reported in https://github.com/dotnet/roslyn/issues/62354 isn't documented in https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md

**Comment by AlekseyTs** [comment]
I am not sure why would that be considered a breaking change. Interfaces couldn't declare static abstract members before. So, there is no existing working code that stops compiling because a compiler change.
