### ISSUE TITLE
VS setting are very inconsistent in terms of native/custom control usage

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#62359]
**Version Used**:
VS 27.3 Preview 2

**Demo:**
![devenv_ksOLS7yceb](https://user-images.githubusercontent.com/70431552/177048892-cee595b8-1b33-4b3e-8e20-7e8414b4d06a.gif)

**Expected Behavior**:
All controls are either native or custom

**Actual Behavior**:
Different tabs have different control styles

**Additional context:**
I initially thought that this was windows 11 issue and even opened a ticket in feedback hub. But then I realized that I didn't see something similar in any other app during ~half a year of win 11 usage. I did a bit of investigation and now I can tell that:
1. This is an issue for windows 10 as well. But native and custom controls look very similar there, so it is not that much noticeable
2. This is an issue for an entire VS setting window. This issue can be left for C#/VB-related settings sections, but the fix is required for a lot of other settings tabs
3. I suspect what is happening is that custom controls try to bind to the VS theme, but always select the default "white" one. Considering that setting window in general is not adapted to other themes this feels weird. From my personal point of view, it is better either to make all controls native or theme the entire window at once

**Comment by Youssef1313** [comment]
FYI @ryzngard

**Comment by davidwengier** [comment]
I'll leave Andrew to comment on whether there is anything the Roslyn-owned pages can do, but they are at least all internally consistent. The VS options window as a whole, however, is a known trouble area - it variously uses WPF, WinForms and Win32 depending on the page, and each of those have different levels of theming and style support. A VS feedback ticket is a more appropriate place to request any consolidation and unification work here.
