### ISSUE TITLE
"Generate constructor from members" puts the result above properties

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#62358]
Roslyn currently puts generated constructor before properties and considers it as an expected behaviour:
https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateConstructorFromMembers/GenerateConstructorFromMembersTests.cs#L452-L471
_This is one of the examples, but there are many across all related tests_

However, me personally and almost all code examples from the Internet I've seen prefer to put constructor _after_ the properties. So I would like this refactoring to do it that way as well. Even if I am wrong and there are those, who prefer it to be the way it is currently working, then such behaviour needs to be somehow configurable.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
