### ISSUE TITLE
There is no way to get "Snippets behavior"/"Enter key behavior" to the default after change

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62363]
In Tools → Options → Text Editor → C# → IntelliSense

![image](https://user-images.githubusercontent.com/31348972/177174740-25cca42d-ea81-42ef-847a-9846d4b39a1f.png)

The default (nothing is selected) refers to "Default" in these two enums:

https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/Features/Core/Portable/Completion/SnippetsRule.cs#L7-L28

https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/Features/Core/Portable/Completion/EnterKeyRule.cs#L7-L28

Once we select a radio button, it cannot be unselected, so we end up having to choose between the other enum values, except "Default".

There should probably be a forth radio button?

**Comment by CyrusNajmabadi** [comment]
Closing as this was fixed.
