### ISSUE TITLE
Two UI checkboxes are tied to a single option

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62362]
https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs#L118

https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs#L124

**Comment by Youssef1313** [comment]
Fixing in #62680, keeping the issue open for a test.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/issues/63309
