### ISSUE TITLE
`#nullable enable` adds a "not CLS-compliant" diagnostic

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62368]
Extracted from test `WRN_CLS_BadArgType_ConstructedTypeAccessibility`:

```csharp
#nullable enable
[assembly: System.CLSCompliant(true)]
public class C<T>
{
    protected class N { }
    protected void M1(C<int>.N n) { }	// Not CLS-compliant - C<int>.N not 
    // accessible from within C<T> in all languages
    protected void M2(C<T>.N n) { }	    // CLS-compliant - C<T>.N accessible inside C<T>
}
```

The above produces warnings for M1 and M2:

```csharp
warning CS3001: Argument type 'C<int>.N' is not CLS-compliant
warning CS3001: Argument type 'C<T>.N' is not CLS-compliant
```

If `#nullable enable` is changed to `#nullable disable`, only warning for M1 is produced.

The root cause is very likely the same as https://github.com/dotnet/roslyn/issues/58966.

This issue was actually part of my investigation to figure out a compiler scenario for the fix I've for #58966

**Comment by Youssef1313** [comment]
@AlekseyTs I modified the test in https://github.com/Youssef1313/roslyn/commit/2e1e4b823fb29ec8d2fcc72321de453aea14b1f3. It's supposed to pass, but it currently fails. https://github.com/dotnet/roslyn/issues/58966#issuecomment-1174871588 has some info that I hope could help.

**Comment by jaredpar** [comment]
CLS Compliance is generally not checked in .NET Core which is the only place nullable is officially supported.
