### ISSUE TITLE
Support 'file' modifier in "IDE0036: Order modifiers" analyzer

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62407]
We also need to define the default preferred order for `file`.

https://github.com/dotnet/roslyn/blob/46119cbbf9f39b7b70b82106a59d0ad80aae674a/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpIdeCodeStyleOptions.cs#L20-L30

@RikkiGibson Any specific order you prefer? (e.g, before abstract/sealed? after them?)

**Comment by RikkiGibson** [comment]
My instinct is to put them right after the accessibility modifiers.
