### ISSUE TITLE
When `csharp_prefer_braces = true:error` build doesn't fail as expected.

### ISSUE THREAD

**Issue by cyclr-adrian** [dotnet/roslyn#62418]
**Version Used**: 
17.2.5

**Steps to Reproduce**:
1. Clone: [https://github.com/cyclr-adrian/CodeStyleAsErrorDoesntBreakTheBuild](https://github.com/cyclr-adrian/CodeStyleAsErrorDoesntBreakTheBuild)
2. Build solution
3. Notice that the build succeeds and there are no errors in the VS Error List window
4. Open `Program.cs`
5. Clean solution
6. Build solution
7. Notice that the build succeeds but there is an error in the VS Error List window

**Expected Behaviour**:
As the code style is set to `error` I would expect:
1. that the build would fail
2. the failure would be visible in the VS Build output window 
3. the error would be visible in the VS Error List window 
8. the VS Error List window would be automatically displayed to the user with the errors on completion of the failed build.

**Actual Behaviour**:
1. the build succeeds with:
```
Build started...
1>------ Build started: Project: CodeStyleAsErrorDoesntBreakTheBuild, Configuration: Debug Any CPU ------
Restored C:\Users\Adrian\source\repos\CodeStyleAsErrorDoesntBreakTheBuild\CodeStyleAsErrorDoesntBreakTheBuild\CodeStyleAsErrorDoesntBreakTheBuild.csproj (in 2 ms).
1>CodeStyleAsErrorDoesntBreakTheBuild -> C:\Users\Adrian\source\repos\CodeStyleAsErrorDoesntBreakTheBuild\CodeStyleAsErrorDoesntBreakTheBuild\bin\Debug\net6.0\CodeStyleAsErrorDoesntBreakTheBuild.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
2. the failure is not visible in the VS Build output window as the build was successful
3. depending on whether the `Program.cs` file was open whilst doing the build
   - if the `Program.cs` file was open, then the error would be visible in the VS Error List window
![image](https://user-images.githubusercontent.com/95350065/177522189-0cffa1b5-a6a7-45ab-8ec9-9c2cfd1b3c20.png)
   - if the `Program.cs` file was closed, then the error would be **NOT** be visible in the VS Error List window
4. the VS Error List window is not automatically displayed to the user

**Comment by Youssef1313** [comment]
This is by-design. The compiler doesn't know about the `option = value:severity` syntax. So this is an IDE-only severity.

If you want to set the severity for build, you need to use `dotnet_diagnostic.IDE0011.severity = error`

**Comment by Youssef1313** [comment]
You may also want to add the following to your csproj:

```xml
<PropertyGroup>
  <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
</PropertyGroup>
```

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is handled by turning on enforcement at build time.
