### ISSUE TITLE
Support -trait for RunTest.exe

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#6241]
[Roslyn.Services.Editor.(\w+).UnitTests are known slow](https://github.com/dotnet/roslyn/commit/c3e4799eb2a5fb5fb84ff9a938868bfd177b8fd3#diff-0102553256b475e6f1e0f2663dedf27bL93), it would be nice that `-trait` can be specified to shorten the test time when running them locally, as running test is the easy way for external contributors to verify editor features currently, or I have to use the long xunit runner command lines and if failure encountered, have to open the browser myself after finding the report file.

**Comment by davkean** [comment]
Thanks for the great suggestion. I imagine we want to pass this through BuildAndTests.proj as well.

**Comment by oocx** [comment]
I have never contributed anything to roslyn or other .net projects before. I think this could be something easy to start with as a first contribution. If that's ok for you, I'm going to implement support for -trait and -notrait arguments in RunTests.exe and will add Trait / NoTrait build properties to BuildAndTests.proj.

**Comment by diryboy** [comment]
Thanks @oocx, I started working on this about an hour before your comment, supporting these options, but not yet checked how to pass them to msbuild, if you are sure how to do this then you are welcome to start and I'll drop mine.

**Comment by oocx** [comment]
Yes, I have msbuild support. I'm not at home right now, I'll answer more detailed when I am home again.
________________________________
Von: Paul Chen
Gesendet: 25.10.2015 14:30
An: dotnet/roslyn
Cc: Mathias Raacke
Betreff: Re: [roslyn] Support -trait for RunTest.exe (#6241)


Thanks @oocx<https://github.com/oocx>, I started working on this about an hour before your comment, supporting these options, but not yet checked how to pass them to msbuild, if you are sure how to do this then you are welcome to start and I'll drop mine.

-

**Comment by diryboy** [comment]
Then I'll drop mine. Looking forward to seeing your PR @oocx :)

**Comment by oocx** [comment]
You can now specify trait and notrait options. Example:
msbuild BuildAndTest.proj /t:Test /p:Trait="Feature=Classification;Feature=DataTips" /p:NoTrait="Feature=SomeFeatureToExclude

or

RunTests.exe -trait:"Feature=Classification" -notrait:"Feature=SomeFeatureToExclude"

You can specify multiple traits by separating them with ';'.

I hope I followed all guidelines correctly. I'm new to pushing changes to github, I usually only work with TFS :). Let me know if my commit is ok or if I need to change anything.

Mathias
