### ISSUE TITLE
'Extract base class' doesn't work well for records

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62415]
```csharp
record CC
{
    public void M()
    {
    }
}
```

Invoke lightbulb on `M`:

![image](https://user-images.githubusercontent.com/31348972/177498045-f90ef347-51b0-4168-9af0-30444e1fd390.png)

1. Code action should be "extract base type"

2. Unspeakable `<Clone>$` shouldn't be shown
  ![image](https://user-images.githubusercontent.com/31348972/177498146-02b493f9-4523-431d-b5eb-88035d41173e.png)

3. Same as 1, but for the window title.
4. Generated type should be record, it's currently class, which produces CS8864 Records may only inherit from object or another record

**Comment by ryzngard** [comment]
Going to treat this in two passes: 

1. Fix extract class to not fail horribly for records
2. Do a pass to make sure intricacies of records are handled better. For example, can't invoke on `record R(string $$S)` right now
