### ISSUE TITLE
Revise and combine `GetSymbolModifiers` and `DeclarationModifiers.From` implementation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62416]
https://github.com/dotnet/roslyn/blob/46119cbbf9f39b7b70b82106a59d0ad80aae674a/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L29-L39

https://github.com/dotnet/roslyn/blob/46119cbbf9f39b7b70b82106a59d0ad80aae674a/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs#L65-L96

It seems both methods are intended to serve the same purpose. Only the public one should be kept, and implementation should be revised to include any missing modifiers.

Not only that, callers also should be revised, for example:

https://github.com/dotnet/roslyn/blob/46119cbbf9f39b7b70b82106a59d0ad80aae674a/src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs#L84-L91

The new type can be in a new file, and inherited from another existing file, so `file` should be filtered.

Other callers may need to be tweaked as well.

**Comment by Youssef1313** [comment]
It's best to wait on this issue until https://github.com/dotnet/roslyn/pull/62413 is done and merged.

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
