### ISSUE TITLE
SourceProductionContext and GeneratorExecutionContext  should share a common interface for AddSource()

### ISSUE THREAD

**Issue by ScottKane** [dotnet/roslyn#62439]
I noticed that `SourceProductionContext` and `GeneratorExecutionContext` both have the same functionality without an interface defining it.

Given the scenario of a project containing legacy v1 generators not yet updated to v2 and a common emitter shared amongst them to add the source to the generation context, there should be a common interface to expose the `AddSource(string hintName, SourceText sourceText)` signature so that a v2 generator could use the same emitter.

Possibly:

```c#
public interface ISourceProducer
{
    public void AddSource(string hintName, SourceText sourceText);
}
```

**Comment by jaredpar** [comment]
@chsienki PTAL

**Comment by chsienki** [comment]
This isn't easily achievable: the contexts are `struct`s with internal state that is modified when you call `AddSource`. If you pass them via interface they'll be copied as part of boxing so any modification you make won't be reflected in the original struct.

I'm going to close this out, but feel free to reply if you have a specific use case that you're struggling with that this aims to solve and we can see if there's a better approach.
