### ISSUE TITLE
Refactoring from implicit to explicit type doesn't seem to work properly with nullabilty

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62474]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-from-implicit-to-explicit-ty/10087938)._

---
[severity:It bothers me. A fix would be nice]
When refactoring from var using the built in refactoring, it is declaring types as nullable that are explicitly declared as non-nullable on the return type for the method. I have attached three screenshots as examples.

---
#### Tracy Wang [MSFT] on 7/5/2022, 11:44 PM: 

(private comment, text removed)
#### Benjamin Michaelis on 7/6/2022, 02:30 PM: 

(private comment, text removed)
#### Benjamin Michaelis on 7/6/2022, 02:31 PM: 

(private comment, text removed)
#### Feedback Bot on 7/6/2022, 05:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
@CyrusNajmabadi yup! https://github.com/dotnet/roslyn/pull/58866  which was in 17.3 

This bug was in 17.2, so I'll close

**Comment by ryzngard** [comment]
> I do have an example project to show the current and expected functionality

Can you check if it is fixed in the latest public preview? If not we can reopen

**Comment by BenjaminMichaelis** [comment]
@ryzngard it does in fact look fixed in the latest public preview! I will keep an eye out for this though in the next days and ping here if I see something that looks off. Thanks for doing that!
