### ISSUE TITLE
Proposal: Default Generic Type Parameter

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6248]
The ability to specify a default type for a generic type parameter:

``` cs
class Foo<TBar = Bar, TBaz = Baz> {}
```

As a real world example, the `IdentityDbContext` class in ASP.NET Identity:

``` cs
class IdentityDbContext<TUser = IdentityUser, TRole = IdentityRole, TKey = string, TUserLogin = IdentityUserLogin, TUserRole = IdentityUserRole , TUserClaim = IdentityUserClaim> where ...
```

to avoid the need to declare different subtypes for different default types like

``` cs
class IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string, IdentityUserLogin, IdentityUserRole, IdentityUserClaim> { ... }
class IdentityDbContext<TUser> : IdentityDbContext<TUser, IdentityRole, string, IdentityUserLogin, IdentityUserRole, IdentityUserClaim> where TUser : IdentityUser { ... }
```

In companion with improved type aliases can avoid [this](http://www.asp.net/identity/overview/extensibility/change-primary-key-for-users-in-aspnet-identity) for god's sake.

To use default type parameters, one may skip the type parameter as follow:

``` cs
var foo = new Foo<,>(); // new Foo<Bar, Baz>()
var foo = new Foo<A,>(); // new Foo <A, Baz>()
```

This has some interactions with generic type argument inference proposals like #5429 or #2319.

**Comment by gafter** [comment]
@alrz Lucky for us you're not aware of the work to add higher kinded types

oops :speak_no_evil:

**Comment by alrz** [comment]
@gafter you mean like #2212? what about it, how is that relevant? :speak_evil:

**Comment by orthoxerox** [comment]
@alrz how will you disambiguate between creating instances of classes `Foo` and `Foo<T = Bar>` via `new Foo()`?

**Comment by alrz** [comment]
@orthoxerox `new Foo()` and `new Foo<>`. see the examples.

**Comment by aluanhaddad** [comment]
@alrz I don't think this adds very much value.

@gafter
>Luckily for us you're not aware of the work to add higher kinded types
You don't say? :)

**Comment by alrz** [comment]
>I don't think this adds very much value.

That's it? Well that was not helpful either.

**Comment by BeeWarloc** [comment]
Foo<> already have a meaning inside typeof(), which obviously can't change.
Having Foo<> mean different things inside and outside of typeof() could be a bit confusing.

**Comment by MgSam** [comment]
@gafter Any further details forthcoming on this work?

I do think this is a useful idea. It would allow users to use generic methods/types without necessarily having to specify each type if they're happy with the default, thus potentially making consumption far more straightforward.

[TypeScript](https://github.com/Microsoft/TypeScript/issues/2175) has a similar proposal currently.

**Comment by gafter** [comment]
@MgSam Any further details on what work? Higher-kinded types? If anything it is years away, and would be led by changes to F# and CLR.

**Comment by alrz** [comment]
@gafter I think this can eliminate the need for generic-non generic variations of types without breaking existing code,

```cs
interface IEnumerator<T = object> {
  T Current { get; }
  bool MoveNext();
  ...
}
interface IEnumerable<T = object> : IEnumerable {
  IEnumerator<T> GetEnumerator();
}
```
doesn't it?

**Comment by aluanhaddad** [comment]
> I think this can eliminate the need for generic/non generic variations of types without breaking existing code

I'm not sure what that means. Are you saying that there is type equivalence between
```C#
interface IEnumerator<T = object> {
    T Current;
    bool MoveNext();
}
```
and 
```C#
interface IEnumerator {
    object Current;
    bool MoveNext();
}
```
?
If so would be a breaking change because
```C#
new ArrayList() is IEnumerable == true
```
and 
```C#
new ArrayList() is IEnumerable<object> == false
```

**Comment by alrz** [comment]
@aluanhaddad I'm saying that we could get rid of `IEnumerable`.

**Comment by alrz** [comment]
Moved to https://github.com/dotnet/csharplang/issues/278
