### ISSUE TITLE
Error List not showing suppressed diagnostics

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62498]
**Version Used**: 

17.3 Preview 2

![no-suppressed-diag](https://user-images.githubusercontent.com/31348972/177974468-7ae97b41-bd9b-4342-9946-3c6f561f1168.gif)

Error shows before suppression, but didn't show after suppression

Note that I selected "Suppressed" from the Error List filter (which is off by default).

(Same applies to compiler warnings)

cc @mavasani

**Comment by mavasani** [comment]
@Youssef1313 I am unable to reproduce this on the latest internal dogfood builds: 
![image](https://user-images.githubusercontent.com/10605811/190123447-1dbdc0a2-6aa3-4c07-9a4f-3143587787d0.png)

One thing I note is that your repro shows all `Suppression State` values as `<blank>`, there are no Active, N/A or Suppressed entries. I am wondering if this is some error list bug. Can you check if you can reproduce this on 17.4 Preview1: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview?

**Comment by Youssef1313** [comment]
Sure, I'll check that as soon as I can.

**Comment by mavasani** [comment]
@Youssef1313 any luck?

**Comment by Youssef1313** [comment]
Not yet :(
I got quite busy with my internship. I should be able to test in two weeks or so. You can assign me so that I don't forget.

**Comment by Youssef1313** [comment]
@mavasani Sorry for the delay here. I'm trying to reproduce this in 17.4 P1, but I now cannot find "Suppression State" in error list at all:

![image](https://user-images.githubusercontent.com/31348972/194693381-116e89aa-1b86-40db-9137-ddcab3329105.png)

"Show Columns" doesn't have it as well:

![image](https://user-images.githubusercontent.com/31348972/194693415-02f096d2-3a9f-4f93-943e-3f742752d608.png)

**Comment by mavasani** [comment]
@Youssef1313 That is interesting. I just updated to the latest internal dogfood build and can see the column: 
![image](https://user-images.githubusercontent.com/10605811/195346289-339826bd-01aa-4b10-9d0e-833e993c5858.png)

I am not sure why this column is behaving specially for you :-)

**Comment by mavasani** [comment]
I confirmed with @Evangelink offline that he is also able to see the Suppression State column and correct filtering for the entries based on the chosen filters for this column. He verified the same on 17.3.5 as well as latest preview for 17.4.

I am going to try this on a fresh install of a Community sku of VS and get back to you.

**Comment by Youssef1313** [comment]
I'll also re-test once I get home back.
If I could repro, I'll try to debug it on my own, and I can give you remote access via Zoom or similar software if necessary to investigate further.

**Comment by Youssef1313** [comment]
![image](https://user-images.githubusercontent.com/31348972/195644485-59611304-0186-4773-a2c4-c98f6fe9fcee.png)

@mavasani The column appears when I have Roslyn.sln open, but it doesn't for a new project. 😕

**Comment by Evangelink** [comment]
@Youssef1313 Could you zip your project so we can try with exact same project (this would leave VS or extensions)? Also, are you still on 17.4P1? And are you using Community sku?

**Comment by Youssef1313** [comment]
Yeah I'm on 17.4 Preview 1. It's really just a new project.

[ConsoleApp9.zip](https://github.com/dotnet/roslyn/files/9780113/ConsoleApp9.zip)

and yes, I'm using community.

**Comment by Evangelink** [comment]
Awesome! I don't understand but hey I have the same issue on that project on my personal machine (Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.4.0 Preview 2.0). But when opening `RoslynAnalyzers` solution column appears and I can filter.

**Comment by mavasani** [comment]
Another possible cause could be LSP pull diagnostics, see https://github.com/dotnet/roslyn/issues/65172. @Youssef1313 can you confirm if you have pull diagnostics enabled or not?

![image](https://user-images.githubusercontent.com/10605811/199493838-9df21efb-026f-4cf7-b7f0-8c4264221d20.png)

**Comment by Youssef1313** [comment]
@mavasani Yes I have pull diagnostics enabled.

**Comment by Youssef1313** [comment]
> EDIT: Found the issue... it's linked to `<ImplicitUsings>enable</ImplicitUsings>`. As soon as I comment the line, column show up. @Youssef1313 could you confirm you see the same thing?

I can't imagine why `ImplicitUsings` would affect error list.

**Comment by Youssef1313** [comment]
@mavasani Should I close as a duplicate of #65172 ?

**Comment by mavasani** [comment]
Yes, if disabling pull diagnostics fixes the issue then go ahead

**Comment by Youssef1313** [comment]
Yes, it does fix it. I'm going to close out.
