### ISSUE TITLE
[LSP] Diagnostics do not refresh on option change

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#62495]
Diagnostics currently will not be refreshed on global option changes - only when you make a modification to a file with new diagnostics be computed

See https://github.com/dotnet/roslyn/issues/61844#issuecomment-1169090318

This likely requires us to listen to global option change events and store that in our version cache.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we do need to do this, please assign to a milestone.
