### ISSUE TITLE
Inconsistent / missing errors for scoped keyword usages

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#62490]
**Version Used**: 
```
Branch main (3 Jul 2022)
Latest commit [8fd033c](https://github.com/dotnet/roslyn/commit/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2) by Youssef Victor:
Ensure elastic trivia for reusable syntax in field generator (#62346)
```

**Steps to Reproduce**:

Compile the following code. [sharplab link](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4GcAuAnArgY0wAIBlIgbyIF8BYAKAAEAmIgYXvPqKIYGYeALEQCyARgAUrAPYAbGQFNCUKTCIIAlFwpbuAel1EAFvOzyiAclMAzIunxSADvISlzRKOiIQ5UgO7OiKylsWykwM1MIdBUdQOD5CHxDInFrW3snFzJPWDV1CmotWjpuLT5BESZxbM0S7Tq9A2NTd0xzTxgpYm8ZP2dYtLtHALIADyIAXiJBgG4ifSITbGC2EgBOAAYBAA4QIgAVYwshzLcwKQQoKygTInwIVWAzXHQAoJDrTweXQZwCYgAbt5cPJPCoZABPAB0RXoxXozDYsgUShidE4dXKACV5FYAKIwXDhbAQTArADi8kwBKJJlJwXE+QmAD4iJhDMtfERCXIAIQzOH0eiwTAmGDeHgsHH4wnE+nYDhlfhpMisXDYUwwYgstkcvzc3B8gWY/jAKSyERSAHyABy8lGmEZk1ZVm8r2NVCAA)
```cs
struct S { }
class C
{
  public void M1(Collection d)
  {
    // here 'ref scoped S' is allowed for some reason
    foreach (ref scoped S s in d) { }
  }
  
  public void M2(S s)
  {
    // here it's not allowed
    ref scoped S x = ref s; // error CS9048: The 'scoped' modifier can be used for refs and ref struct values only.
  }
}

class Collection
{
  public RefEnumerator GetEnumerator() => throw null!;
}

internal class RefEnumerator
{
  public ref S Current => throw null!;
  public bool MoveNext() => false;
}
```

**Expected Behavior**:
Either both `ref scoped S` declarations are invalid or neither of them

**Actual Behavior**:
`ref scoped S` is allowed as a foreach variable but not as a local variable
This seems like a bug as both declare a reference to the same type

**Comment by TessenR** [comment]
I think this can be closed now as `ref scoped` is not allowed anymore and `scoped ref` wasn't parsed in declaration expressions in the first place

**Comment by cston** [comment]
Thanks for reporting @TessenR.

Both of the `ref scoped` cases in the example are now reported as syntax errors following https://github.com/dotnet/roslyn/pull/64021.
