### ISSUE TITLE
A `ref T` field where `T` is `unmanaged` is itself treated as `unmanaged`

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/roslyn#62528]
Tested with a daily SDK build (7.0.100-preview.7.22358.13):
```cs
unsafe
{
    var byref = default(ByReference<int>);
    var byptr = &byref; // does not error
}

readonly ref struct ByReference<T>
{
    public readonly ref T Value;
}
```

**Expected Behavior**:
`error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('ByReference<int>')`

**Actual Behavior**:
The code compiles successfully.

**Comment by DaZombieKiller** [comment]
Worth noting: assuming this is unintended behaviour, [it is currently being relied upon by the reflection stack](https://github.com/dotnet/runtime/blob/1967649721058a457157d4321af3e6fceaa5441b/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs#L248-L254).

**Comment by RikkiGibson** [comment]
It feels like it would be reasonable to make people use https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.aspointer?view=net-6.0 if they want to keep doing this.

**Comment by Sergio0694** [comment]
Note, for that they'd currently be forced to use a function pointer jump, which adds an extra indirection. As in:

```csharp
unsafe
{
    var byref = default(ByReference<int>);
    var f1 = (delegate*<ref byte, ref byte>)&Unsafe.As<byte, byte>;
    var f2 = (delegate*<ref ByReference<int>, ref byte>)f1;
    
    void* byptr = Unsafe.AsPointer(ref f2(ref byref));
}
```

That said, it would work around the issue until `ref struct`-s in generics are allowed 😄

**Comment by MichalPetryka** [comment]
@jaredpar Did #63209 fix this too?

**Comment by cston** [comment]
Thanks for reporting this issue. It has been fixed in https://github.com/dotnet/roslyn/pull/64064.

The compiler now reports:
```
warning CS8500: This takes the address of, gets the size of, or declares a pointer to
    a managed type ('ByReference<int>')
```

cc @jcouv
