### ISSUE TITLE
Warning suppressors should run insofar as not all errors are unsuppressible

### ISSUE THREAD

**Issue by MiaoYu-Goh** [dotnet/roslyn#62540]
I am a software engineer working on DOTS at Unity Technologies. We use source generators heavily.

When users create a struct that implements `IJobEntity` (a public interface in the DOTS API), the struct needs to be declared `partial`. This allows our source-generator solution to declare another part of the same struct, and generate additional methods and fields in it. Because partial structs trigger [`CS0282`](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0282), we have created a `PartialStructWarningSuppressor` (which inherits from `DiagnosticSuppressor`) in our source-generator solution to suppress `CS0282`.

However, I noticed that `PartialStructWarningSuppressor` does not run whenever there are unsuppressible errors during the `CompilationStage.Parse` stage or the `CompilationStage.Declare` stage. [In the `CompileAndEmit()` method](https://github.com/dotnet/roslyn/blob/e1296f03d00b79198e6fbb2e007c8b03b66b8950/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L963), `if (HasUnsuppressableErrors(diagnostics))` is checked several times, each time causing an early exit from the method if the condition is true -- e.g. [here](https://github.com/dotnet/roslyn/blob/e1296f03d00b79198e6fbb2e007c8b03b66b8950/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L984) and [here](https://github.com/dotnet/roslyn/blob/e1296f03d00b79198e6fbb2e007c8b03b66b8950/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1114). [Suppressors are run fairly late in the method](https://github.com/dotnet/roslyn/blob/e1296f03d00b79198e6fbb2e007c8b03b66b8950/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1213), and exiting early from the method means that `PartialStructWarningSuppressor` is ignored if at least one suppressable errors are encountered.

I believe this to be a bug -- we should still run suppressors even when there are unsuppressable errors. Currently we see a flood of messages about `CS0282` in the Unity editor whenever there are unsuppressable errors elsewhere in the code, which is a very confusing and unpleasant experience for users. Those warnings about `CS0282` will automatically go away (i.e. be suppressed) once all unsuppressable errors are fixed, but our users can't/don't know that. 

I think the fix is probably quite straightforward: Instead of checking `HasUnsuppressableErrors(diagnosticBag)`, simply check: `diagnosticBag.AsEnumerable().All(diagnostic => diagnostic.IsUnsuppressableError())`. If `false`, it means that there are suppressable errors, which means that suppressors should be run. Run suppressors, and then exit from the method. If `true`, exit immediately.

We should do the same in both the `CompilationStage.Parse` stage and the `CompilationStage.Declare` stage.

**Comment by RikkiGibson** [comment]
I'm wondering if `HasSuppressableWarnings` could be implemented more efficiently than `.AsEnumerable.All()`. I'm also wondering if we could just always run suppressors, even without searching for suppressable diagnostics in advance.

**Comment by MiaoYu-Goh** [comment]
I have managed to implement a fix and verified that it works locally. Here are the changes to the `CommonCompiler.CompileAndEmit()` method:

https://gist.github.com/MiaoYu-Goh/8b8d047b16142d36edb0c2c209252dd2#file-commoncompilerchanges-cs-L1
https://gist.github.com/MiaoYu-Goh/8b8d047b16142d36edb0c2c209252dd2#file-commoncompilerchanges-cs-L23
https://gist.github.com/MiaoYu-Goh/8b8d047b16142d36edb0c2c209252dd2#file-commoncompilerchanges-cs-L164

**Comment by MiaoYu-Goh** [comment]
@Youssef1313 Thank you! I have created a PR here: https://github.com/dotnet/roslyn/pull/62641
