### ISSUE TITLE
[LSP] Report syntax diagnostics from document pull without waiting for semantic diagnostics

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#62560]
Reported by @CyrusNajmabadi 

Currently there is some perceived slowness in diagnostics because we always compute syntactic and semantic diagnostics before reporting anything to the client in document pull.   It can take a bit to compute semantic diagnostics which is expected.  However, we can generally compute syntax diagnostics fairly quickly and in the old system we would push those first so that they show up fast.

Document pull supports streaming, so we should compute the syntax diagnostics first, send a report, while we are still waiting for semantic diagnostics to be computed.

**Comment by gundermanc** [comment]
FWIW Visual Studio's LSP client supports progressive notifications in document diagnostics but it doesn't actually update the UI until all of the notifications have landed.

**Comment by dibarbet** [comment]
> FWIW Visual Studio's LSP client supports progressive notifications in document diagnostics but it doesn't actually update the UI until all of the notifications have landed.

Thanks for catching it before I tried and failed.  Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1569172

**Comment by CyrusNajmabadi** [comment]
@dibarbet can this be closed?  we do have different providers now for syntax/semantics right?

**Comment by dibarbet** [comment]
yup, closed.
