### ISSUE TITLE
Elvis operator doesn't seem to work with value types

### ISSUE THREAD

**Issue by BrainSlugs83** [dotnet/roslyn#6256]
For example, neither of these syntaxes work:

1.) Example 1

    var array = new int[0];
    if (array?.length > 0) { // ...

2.) Example 2

    var array = new int[0];
    if (array?.any()) { // ...

It would make sense that if an Elvis operator check failed (i.e. the object being checked was null), that it should just return default(T) for value type properties (this would give intuitive behavior for both of the scenarios listed above which should be pretty common for most of us).

**Comment by svick** [comment]
This would be a breaking change, so I don't think doing this make sense.

**Comment by ufcpp** [comment]
1.
```cs
var array = new int[0];
if (array?.length ?? 0 > 0) { // ...
```

2.
```cs
var array = new int[0];
if (array?.any() ?? false) { // ...
```

**Comment by gafter** [comment]
Works for me

```cs
        var array = new int[1];
        if (array?.Length > 0) { }
        if (array?.Any() == true) { }
```
