### ISSUE TITLE
Auto-quotes and "$" operator problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62571]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-quotes-and--operator-problem/10092299)._

---
[severity:It bothers me. A fix would be nice]
I have some sort of problem. When I want to use **'$'** operator in C#, for instance in `Console.Writeline($"Hello world")`, auto-quotes for some reason doesn't work, but it perfectly works when I use **'@'** operator before a string like here: `Console.Writeline(@"Hello world")`

---
#### Feedback Bot on 7/11/2022, 06:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
The reason is because in statements like `Console.WriteLine($);` (this is how brace completion service sees it when you type `"` after a `$`) `$` is parsed not as a string interpolation token, but as `BadToken` of `SkippedTokensTrivia` of `OpenParenToken` - https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABATARgLAChcowE4AKAEgEoBuIA. I am not sure if this case needs to be handled on IDE side or compiler parsing needs to be improved here

**Comment by CyrusNajmabadi** [comment]
if you have `$"` i would expect that to view that as an appropriate start of an interpolated string.   Indeed, looking at the code, it's unclear to me why that doesn't happen:

```c#
        private bool TryScanInterpolatedString(ref TokenInfo info)
        {
            Debug.Assert(TextWindow.PeekChar() == '$');

            if (TextWindow.PeekChar(1) == '$')
            {
                // $$ - definitely starts a raw interpolated string.
                this.ScanInterpolatedStringLiteral(ref info);
                return true;
            }
            else if (TextWindow.PeekChar(1) == '@' && TextWindow.PeekChar(2) == '@')
            {
                // $@@ - Error case.  Detect if user is trying to user verbatim and raw interpolations together.
                this.ScanInterpolatedStringLiteral(ref info);
                return true;
            }
            else if (TextWindow.PeekChar(1) == '"')
            {
                this.ScanInterpolatedStringLiteral(ref info);
                return true;
            }
```

We should be going into this case:

```c#
            else if (TextWindow.PeekChar(1) == '"')
            {
                this.ScanInterpolatedStringLiteral(ref info);
                return true;
            }
```

which should always succeed.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Brace completion service sees the given tree **before** the character is inserted. So `"` doesn't exist there yet, only the dollar sign. But looking at the code you provided I still don't get why `$$` is considered as "definitely starts a raw interpolated string", while a single `$` is not "definitely starts of a normal interpolation string" and requires additional check of a quote
