### ISSUE TITLE
Roslyn.Compilers.VisualBasic.Semantic.UnitTests are deadlocking

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6257]
The Roslyn.Compilers.VisualBasic.Semantic.UnitTests have deadlocked 3 times in the past 3 days: 
https://github.com/dotnet/roslyn/issues/6166.

Can we please have someone look into this? Otherwise, we're going to have to disable them.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure as an FYI.

**Comment by davkean** [comment]
I wonder if this an assert dialog or something? Unfortunately, we don't yet take screenshots on teardown.

**Comment by tannergooding** [comment]
@jaredpar, @Pilchie. I thought we were going to properly swallow asserts and convert them into exceptions?

**Comment by davkean** [comment]
See https://github.com/dotnet/roslyn/issues/2796 for the bug tracking the Assert dialog.

**Comment by AlekseyTs** [comment]
@brettfo Please verify

**Comment by brettfo** [comment]
Confirmed dupe of #2796.
