### ISSUE TITLE
Visual Basic Options don't export correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62570]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Basic-Options-dont-export-correc/10092095)._

---
[severity:It's more difficult to complete my work]
While setting up code guidelines I noticed that the naming conventions i designated for Visual Basic won't get exported with the other settings. Only the general settings for Visual Basic and naming conventions for C# get exported correctly. 

Can this be fixed or circumvented? I can't use the .editorconfig file, because it would be far too much work to add it to every project our firm has.

---
#### Feedback Bot on 7/11/2022, 07:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Could someone assign me since I'm doing some automation object work to ensure everything is imported/exported correctly?

**Comment by CyrusNajmabadi** [comment]
Done.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out as we're unlikely to make changes to thse experiences.
