### ISSUE TITLE
Proposal: Enhancing the precise rules for determining definite assignment related with the Null-Conditional Operator

### ISSUE THREAD

**Issue by sumtec** [dotnet/roslyn#6258]
The null-conditional operator is awesome and I like it very much. However, it brings us an issue which is not much an issue before.

Consider the following code:
```csharp
private void Test(Dictionary<string, object> dict)
{
    object result;
    // object tryGetSuccess = dict == null ? null : (object)dict.TryGetValue("Foo", out result);
    // if (tryGetSuccess == null) result = null;
    if (dict?.TryGetValue("Foo", out result) == null) result = null;    
    Debug.WriteLine(result);
}
```

At a glance, the code looks good. However, it can't be compiled. The compiler complains about the result variable not being set before using it. This is quite unexpected because result will be set to null if dict is null. And otherwise, the result should be set by the TryGetValue method no matter whether the key "Foo" exists or not.

The reason for the compilation error is that, according to the [C# language spec 5.3.3.5 If statements](https://msdn.microsoft.com/en-us/library/aa691197(v=vs.71).aspx), it will treat the local variable as "not definitely assigned" at the end of the statement if the variable is not set either in the testing part, or in both the two branches.

The comment above the line of null-conditional operator "if" statement is the equivalent form. It's obvious that the first line set the result variable in only one of its branches. So, this is "not definitely assigned". And the second statement set the result in only one of its branches as well. As a result, the compiler complains that the result is not assigned before using it but that's not true.

It's quite reasonable that the compiler doesn't analyze all the execution path because it might takes a long time and make things complicated. And before introducing the null-conditional operator, it's quite reasonable to say if you didn't set it in both two branch, it's not considered as assigned at the end of the statement. 

However, there's only one branch in the null-conditional operator and you can't set it in the other branch. And also, when people are writing null-conditional operator expression, they are not actually think it as a typical conditional statement, but "do nothing if anything is null in the chain and return null", or "don't panic if null appears". So, when the compiler complains about it, I feel counter-intuitive.

There is an walk-around but it cut the benefit from null-conditional operator:
``` csharp
result = dict == null ? null : dict.TryGetValue("Foo", out result);
```

Although you can still use null-conditional operator if you have a longer chain, it still ruins the benefit of the straightforwardness brought by the null-conditional operator:
``` csharp
result = parent?.child?.dict == null ? null : dict.TryGetValue("Foo", out result); // why I just can't use "?." all the way?
```

The proposal is to eliminate this kind of issue:

Add a special rule to the null-conditional operator / conditional operator like this:

If any of the branches of the null-conditional operator / conditional operator yields a const value, and that const value is immediately compared with an expression which contains constant only at the following null-conditional operator / conditional operator / expression of an if statement, the compiler will do a simple analyze on all the possible path to see if it match the same set of const value.

eg:
``` csharp
    if (dict?.TryGetValue("Foo", out result) == null) { result = null; }
    // equals to
    if (
        dict == null // result not definitely assigned
        ? null  // result not definitely assigned but it yields the const value null
        : (object)dict.TryGetValue("Foo", out result) // definitely assigned
    )
        result = null;  // definitely assigned. For the other possibility, it's already definitely assigned.

    // Although the following code looks almost the same,
    // it introduced a temporary variable, and used in the if statement after that, 
    // which might be a bit more complicated. 
    // This can be exclude from the proposal if it introduce some other problems.
    object tryGetSuccess = 
        dict == null // not definitely assigned
        ? null  // not definitely assigned but it yields the const value null 
        : (object)dict.TryGetValue("Foo", out result); // definitely assigned
    if (tryGetSuccess == null) // Now it matches the const value null
        result = null; // definitely assigned. For the other possibility, it's already definitely assigned.

```

To make it work, we just need to mark the variable as partial assigned, and put the constant value yield in the other branch into a set related with the variable. When one of these constant value is matched with the expression in the following conditional check (which contains constant expression only), remove this value from the set. Once it leaves the conditional expression block or if block, check all the sets. If it's empty, mark the variable as definitely assigned. Otherwise, not assigned. And then dispose all the sets.

Maybe someone else can find a better solution which make it apply to more cases but I think this is good enough.

There's another way to resolve this issue by making the compiler believe that the equivalent form of the null-conditional operator chain in an if statement like this:

``` csharp
if (a?.b?.method1(out result1)?.method2(out result2) == null) { //blockA }

// equals to
if (a==null || a.b == null)
{
    //blockA
} 
else
{
    var c = a.b.method1(out result1);
    if (c == null)
    {
        //blockA
    }
    else
    {
        if (c.method(out result2) == null)
        {
           //blockA
        }
    }
}
// So, if the block A sets result1 and / or result2, it / they will be considered as definitely assigned.

// Currently, the compiler might think it as the following, which brings this issue:
object value = null; // or Nullable<T> value = null, where T == typeof result1
if (a != null && a.b != null)
   value = a.b.method1(out result1); // result1 not set in the else branch
if (value != null && value.method2(out result2) == null)
{
    // blockA
}
```
Yes, it might be a bit easier to implement and does not require to change the rule. However, I think it's quite ugly because the compiler need to treat it (a?.b?....xxx == null) as a special case. It is not a generic way to solve the problem and it won't benefit the conditional operator (?:).

Anyway, it would be better fixed than not.

Another walk around is assigning the result before it like this:
```csharp
private void Test(Dictionary<string, object> dict)
{
    object result;
    // object tryGetSuccess = dict == null ? null : (object)dict.TryGetValue("Foo", out result);
    // if (tryGetSuccess == null) result = null;
    if (dict?.TryGetValue("Foo", out result) == null) result = null;    
    Debug.WriteLine(result);
}
```

However, it's not exactly equal with the original form. It might bring some kind of code degrading issue. Here are some examples:

``` csharp
        private void Test2(Dictionary<string, object> dict)
        {
            object result = null
            //object tryGetSuccess = dict == null ? null : (object)dict.TryGetValue("Foo", out result);
            //if (tryGetSuccess == false) result = null;
            // I made a mistake to write it as false, not null;
            // It looks good and can be compiled but it's wrong.
            if (dict?.TryGetValue("Foo", out result) == false) result = CreateIt();
            Debug.WriteLine(result);
        }

        private void Test3(Dictionary<string, object> dict)
        {
            object result = null;
            if (dict?.TryGetValue("Foo", out result) == null)
            {
                DoSomething(); // by 2nd person.
                DoSomeOtherThing(result); // by 4th person. And accidentally, it passes all the test.
                /*
                    Do a lot of things by 3rd person.
                */
                result = CreateIt();
            }
        }
```

For detail explanation, please see the comment.

P.S.:
I'm not surprise if it's not going to be fixed because it's kind of edge case. However, I am so upset in this case that the code looks so right but unable to be compile. (And to get rid of it, you need to avoid using this feature but no other choice.) It's a good feature but with a flaw inside.

**Comment by gafter** [comment]
`object result = null;`

problem solved.

**Comment by sumtec** [comment]
@gafter Yes, this is a walk-around but it's not equivalent. And I think it might lead to another problem. Let's take a look at the other case:

``` csharp
        private void Test2(Dictionary<string, object> dict)
        {
            object result = null
            //object tryGetSuccess = dict == null ? null : (object)dict.TryGetValue("Foo", out result);
            //if (tryGetSuccess == false) result = null;
            // I made a mistake to write it as false, not null;
            if (dict?.TryGetValue("Foo", out result) == false) result = CreateIt();
            Debug.WriteLine(result);
        }
```

Now, you think you are right and compiler says ok but it's not what you thought. The problem here is that it make you feel that you should give the result a value which might have no meaning to make it work.

You may say we should prevent it by appropriate test cases. Yes, and no. It's kind of because there is an issue in the language rule so we need to test it, like something you can run through the case without break in the C.

After some days, a different person might add some code between this two lines. And it makes the third person believe the result variable is properly initialized while it's not. It's just a meaningless null (or default<T>). It provides a way to degrade the quality of the source code. For example:

``` csharp
        private void Test3(Dictionary<string, object> dict)
        {
            object result = null;
            if (dict?.TryGetValue("Foo", out result) == null)
            {
                DoSomething(); // by 2nd person.
                DoSomeOtherThing(result); // by 4th person. And accidentally, it passes all the test.
                /*
                    Do a lot of things by 3rd person.
                */
                result = CreateIt();
            }
        }
```

Not fixing it won't be a big deal, we can still walk around it. It's just not smelling good.

**Comment by gafter** [comment]
We have "definitely assigned when true", "definitely assigned when false", but we do not have "definitely assigned when null" and "definitely assigned when not null", which is what would be needed in the spec.

**Comment by paulomorgado** [comment]
> when people are writing null-conditional operator expression, they are not actually think it as a typical conditional statement, but "do nothing if anything is null in the chain and return null", or "don't panic if null appears". So, when the compiler complains about it, I feel counter-intuitive.

If that's all "people" are think of, they better think again. "People" is forgettng about the short circuiting effect. The whole chain is only evaluated until the first **null** happens. That being said, `result` wont be definetily assgined if the `TryGetValue` isn't invoked. And that is the expected behavior.

Your `Test` method is translated by the compiler to:

    private void Test4(Dictionary<string, object> dict)
    {
        object result;
        bool? nullable = (dict != null)
            ? new bool?(dict.TryGetValue("Foo", out result))
            : new bool?();
        if (!nullable.HasValue)
        {
            result = null;
        }
        Debug.WriteLine(result);
    }

And in that code `result` isn't definitely assigned after the **if** statement either. Why should it be using the **null-conditional operator**?

**Comment by sumtec** [comment]
@gafter When you said "definitely assigned when null", did you mean a special treatment for chained null-conditional operator? I thought about it before, it's easy but it won't help the other cases like this:

``` csharp
        private void Test4(Dictionary<string, object> dict)
        {
            object result = null
            if (dict?.TryGetValue("Foo", out result) != true) result = CreateIt();
            Debug.WriteLine(result??"null");
        }
```

And I just come up with another idea which you may like: The out parameter will be assigned to ```default(T)``` if anything in the chain is null. And then, we don't need to change the rule for determine whether a variable is definitely assigned. And we can make the code even simpler, like this if we just need it to be null:
``` csharp
        private void Test5(Dictionary<string, object> dict)
        {
            dict?.TryGetValue("Foo", out result);
            Debug.WriteLine(result??"null");
        }
```
If we want it to be something else when the dict is null:
``` csharp
        private void Test6(Dictionary<string, object> dict)
        {
            if (dict?.TryGetValue("Foo", out result) == null) result = CreateIt();
            Debug.WriteLine(result??"null");
        }
```
And if we want it to be something else when either the dict is null or "Foo" doesn't exist in the dict:
``` csharp
        private void Test6(Dictionary<string, object> dict)
        {
            if (dict?.TryGetValue("Foo", out result) != true) result = CreateIt();
            Debug.WriteLine(result??"null");
        }
```

I think that is good enough, although I still prefer the original idea bit because it also fix some cases for the conditional operator ```?:``` as well.


@paulomorgado 
If you think about the code carefully, you will find out that the result can be coming from ```TryGetValue``` if the ```dict``` is not null, or be ```null``` because ```dict``` is null. There is no other path which does not assign the ```result```. Even though it's short circuited, it doesn't affect the run-time result. In other word, it's definitely assigned in run-time but the compiler doesn't intelligent enough to believe so.

The problem is caused by, as what I mentioned at the beginning of the proposal, the rule **[5.3.3.5](https://msdn.microsoft.com/en-us/library/aa691197(v=vs.71).aspx)**. The compiler won't consider separate ```if``` statement's execution path as a whole, even if they are actually chained by constant values.

As you've mentioned the short circuiting, I want to make it little bit clear. The primary propose for short circuiting, I think, is to improve the performance by doing less things. Yes, indeed, the null-conditional operator does short circuiting. However, the proposes between them are different. The null-conditional operator's propose was to reduce the code we need to check the null value before doing anything and preventing the unwanted NullReferenceException being thrown. It just accidentally has the same structure of code as the logic short circuiting.

When people write ```dict.TryGetValue(key, out result)```, they won't think it has anything to do with the short circuiting although actually it does if think throwing an exception to prevent the ```TryGetValue``` from being hit into is kind of short circuiting. They will just think it like this:
> Call the TryGetValue with key and return if it's there and the result if it's there". 

It's almost the same for ```dict?.TryGetValue(key, out result)```. People will just think it like this:

> Call the TryGetValue with key and return if it's there and the result if it's there. But hey, please, don't panic if the dict is null. If it's null, just do nothing and return me null.


P.S.: I believe that performing a simple static code analyzing against the AST with only constant value is not a huge thing. And we don't need to introduce any concept like ```constexpr``` in C++11/14. We can just use the same definition we've already used related with the keyword ```readonly```. It's not supposed to deal with something complicated which is far from a normal person's understanding. It's supposed to fix some chained operation related with null-conditional operator / conditional operator.

**Comment by paulomorgado** [comment]
There's no magic in the null-conditional operators and what you're asking is to introduce it based on the assumption of what you think "people" think.

You are assuming that each and every method with out parameters will return the default value for its type for some arbitrary condition. But that's not an universal true, so the compiler can't make any asumptions.

@gafter gave you the correct answer for your problem on his first comment on this issue.

`dict.TryGetValue(key, out result)` is not about short-circuiting exceptions. It's about not using exception-based flows. If an invalid value is expected to be processed, than it's not an exception. The fact the these methods were not in the early versions of the framework is a design bug.

**Comment by sumtec** [comment]
@paulomorgado I think you misunderstood what I was saying.

Firstly, I am not saying the TryGetValue itself is about short-circuiting exceptions. I am saying, if the dict is null, it will throws an exception instead of reaching the TryGetValue. Thus, the null check on dict short "circuited" the TryGetValue. Let's change the name of the method name to DoSomething. The example would become:

``` csharp 
private void Test(SomeClass someThing)
{
    object result;
    if (someThing?.DoSomething("Foo", out result) == null) result = null;    
    Debug.WriteLine(result??null);
}
```

A bit clear? I am **NOT** talking about the TryGetValue itself. I am talking about the **definitely assigned** test against the combination of the keyword ```?:``` and ```out```.

And secondly, I didn't assume the ```out``` parameter will default to ```default(T)``` or ```null```. No, absolutely not. However, please consider the following code a bit carefully:
``` csharp
object result;
someThing?.DoSomething("Foo", out result);
// Right now here, does result is definitely assigned or not?
// If not, can we use it? No, is it?
// Then, we must write an if statement to assign it right?
if (...) result = DoSomethingItShouldBe();
// And you can use the result variable here.
```

The solution @gafter gave on his first comment just eliminate the if statement by assigning it to ```null``` at the first step. However, the null came from nowhere. It has no special meaning but to make the compiler think it is definitely assigned. This will give an opportunity to put some code in between, and make use of the meaningless result variable. That's why I think it would be a problem.

And my idea about assigning it with default(T) if **any element in the chain** is null and the ```result``` is **not definitely assigned** is just trying to defer the assigning. Or, the compiler equivalent became:
``` csharp
private void Test(Dictionary<string, object> dict)
{
    // dict?.TryGetValue("Foo", out result);
    object result;
    object tryGetSuccess;
    if (dict == null)
    {
        tryGetSuccess = null;
        result = null;
    }
    else
    {
        tryGetSuccess = (object)dict.TryGetValue("Foo", out result);
    }

    Debug.WriteLine(result);
}
```

So, now the ```result = null``` moved from the definition of the result, into a specific branch. Thus, we don't need to initialize it when we define it and leave a potential hole in between. If you think that assigning the result to null inside only the branch which is not going to call the ```TryGetValue``` is "assuming all the out parameter default to null", why wouldn't you think @gafter 's reply is also making the same consumption?

And I also gave different solutions when you don't want the result default to null as long as the method returns a value. And please, do **NOT** confusing the null return value and the value for the **out** parameter. They are different things.

Surely, this idea is not fully developed. For example, what should we do if the result was partially assigned before? Maybe we need to fall back to how it does today at this situation: not trying to initialize the result back to ```default(T)``` because it could have some meaningful value already. And still let compiler give an error. Any way, this is not about making an assumption that all the ```out``` parameter will default to what. It's about make the compiler believe that the ```result``` is definitely assigned in some cases which it now think it's not but it actually is.

And thirdly, for your first reply, I think what you mean is I assumed that all people think it's not kind of short-circuiting. If that's what you think, I would say: No, I never assumed that. Please have a look at my proposal carefully, I've given the exact compile time equivalent as you gave on your first reply. I don't know why you have the conclusion that I think it's not kind of short-circuiting. 

And I also tried to explain why, at least, I will expect it to be treated as definitely assigned in my proposal and my reply. If it is not clear, I would like to say it here again:
> ** It's actually definitely assigned at the run-time. The compiler is not clever enough to realize it. And the null-conditional operator make it even obvious because when I say "a?.b(out c)" what I want is just don't panic. **

What the language spec says is one thing, and what we mean when we are writing the code is another different thing. Please don't confusing them.

If I didn't explain clearly, please forgive me.

**Comment by gafter** [comment]
@sumtec 

> When you said "definitely assigned when null", did you mean a special treatment for chained null-conditional operator? I thought about it before, it's easy but it won't help the other cases like this:
```cs
        private void Test4(Dictionary<string, object> dict)
        {
            object result = null;
            if (dict?.TryGetValue("Foo", out result) != true) result = CreateIt();
            Debug.WriteLine(result??"null");
        }
```

Indeed, it would help for a case such as this. A "definitely assigned when not null" value for the left-hand operand of `!= true` would result in a "definitely assigned when false" value for the whole comparison. Therefore this case would be solved by such a rule.

**Comment by paulomorgado** [comment]
This is perfectly good code in **Visual Basic**:

    Private Sub Test(dict As Dictionary(Of String, Object))
        Dim result As Object
        If (dict?.TryGetValue("Foo", result) Is Nothing) Then
        End If
        Debug.WriteLine(result)
    End Sub

It only produces a warning, not an error.

Having variables definitely assigned is a characteristic of **C#** but not of **Visual Basic**.

The value assigned to `result` on @gafter's comment doesn't come out of nowhere. It's the developer's decision what that value is.

This is one possible refactoring of your original code:

    private void Test(Dictionary<string, object> dict)
    {
        object result;
        if ((dict == null ? (bool?)null : dict.TryGetValue("Foo", out result)) == null) result = null;
        Debug.WriteLine(result);
    }

If what you're proposing was implemented, than this refactoring would make the code uncompilable.

**Comment by paulomorgado** [comment]
@gafter 

> > @sumtec 
> > 
> > When you said "definitely assigned when null", did you mean a special treatment for chained null-conditional operator? I thought about it before, it's easy but it won't help the other cases like this:
> > 
> >     private void Test4(Dictionary<string, objectdict)
> >     {
> >         object result = null;
> >         if (dict?.TryGetValue("Foo", out result) != true) result = CreateIt();
> >         Debug.WriteLine(result??"null");
> >     }
> 
> Indeed, it would help for a case such as this. A "definitely assigned when not null" value for the left-hand operand of ` != true`  would result in a "definitely assigned when false" value for the whole comparison. Therefore this case would be solved by such a rule.

When not null what? `dict` or `dict?.TryGetValue("Foo", out result)`?

**Comment by gafter** [comment]
@paulomorgado The left-hand-side of `!= true`, which is `dict?.TryGetValue("Foo", out result)`. The variable `result` is definitely assigned when `dict?.TryGetValue("Foo", out result)` is non-null. Therefore after comparing that value for equality (or inequality) to `true` or any other non-null value, the variable `result` is definitely assigned when true (or false).

**Comment by paulomorgado** [comment]
If I understand it correctly, the assumption is that, if the evaluation of the expression is not null, the assumption is that all evocations in the chain happened and `result` is definitely assigned, right? I suppose that would be valid for methods returning a value of any value type, right?

IF so, then why does that pattern deserve a different treatment from this?

    object stuff;
    if (thingy?.GetAValueOfAReferenceType(out stuff) == null) stuff = null;
    // is stuff definitely assigned here?

**Comment by gafter** [comment]
@paulomorgado It would have the same behavior for your snippet. If we did "definitely assigned when null", that is. But I don't believe it is something we are likely to do.

**Comment by sumtec** [comment]
@paulomorgado 
> The value assigned to result on @gafter's comment doesn't come out of nowhere. It's the developer's decision what that value is.

When I said it came from nowhere, it's meaningless in my case:
``` csharp
private void Test4(Dictionary<string, objectdict)
{
    object result = null; // That's meaningless except to make the whole thing get compiled.
    if (dict?.TryGetValue("Foo", out result) != true) result = CreateIt();
    Debug.WriteLine(result??"null");
}
```

Consider when the method ```CreateIt()``` impact performance heavily and you have a good chance that the value is in the ```dict``` in most cases, you cannot write it in the way like this:
``` csharp
private void Test4(Dictionary<string, objectdict)
{
    object result = CreateIt(); // The performance issue here
    dict?.TryGetValue("Foo", out result);
    Debug.WriteLine(result??"null");
}
```

@gafter It seems like what you mean is to add a third state called "definitely assigned when not null". And such a state will carry a null state for the next if statement or (null-)conditional operator expression. If it is, it's quite the same as what I proposed except that you just enable the null value but not all the constant.

Anyway, it seems like that it's not going to be improved. Well, then, I think what we need to do is to avoid using null-conditional operator with out parameter if the default value is not easy to get.

**Comment by paulomorgado** [comment]
@gafter 
> @paulomorgado It would have the same behavior for your snippet. If we did "definitely assigned when null", that is. But I don't believe it is something we are likely to do.

Please, don't. Anyone that knows the language only expects that `result` would only be assigned at `dict?.TryGetValue("Foo", out result)` if `dict.TryGetValue` was invoked. The reverse is that, if `result` is definitely assign, that means that `dict.TryGetValue` was invoked.
