### ISSUE TITLE
Potential infinite loop parsing anonymous types.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#62603]
Reported originally by @AntonGrekov in https://github.com/dotnet/roslyn/issues/24513.

Anton provided a trace (https://developercommunity.visualstudio.com/t/RoslynCodeAnalysisServiceexe-drains-UPT/10091268) that demonstrates something going very bad with parsing anonymous types (`new { ... }`).

Repeating the notes from that issue:

Trace shows teh entirety of the time in:

![image](https://user-images.githubusercontent.com/4564579/178774366-d7b73e6d-2b88-443d-a74a-6480586a56bd.png)

Interestingly the memory allocation hit is here:

![image](https://user-images.githubusercontent.com/4564579/178774749-5a6c8813-a0f7-42dc-a845-347f037b5e74.png)

as a massive single outlier in the total memory allocated here:

![image](https://user-images.githubusercontent.com/4564579/178774821-3416a65c-0388-4090-b805-2f525df6166d.png)

This indicates one of a few possibilities here:

1. You have a truly MASSIVE anonymous-type e.g. `new { ..... OMGHUEG ... }`.  
2. You have a truly MASSIVE number of anonymous-types.  e.g. `new { ... } ... new { ... } ... ad infinitum`.
3. The compiler has a bug where it's effectively getting into an infinite loop while parsing anonymous-types due to some construct it doesn't understand.  This infinite loop is what is causing the huge spike in CPU and the massive memory allocations as we spin forever, making no progress, constantly allocating nodes for the body of that anonymous type.

'3' seems very likely, but i can't rule out '1' or '2'.  Would you be willing to zip up all your sources and send them to me?  I could then do a simple parsing analysis to see what is likely causing this.

In hte meantime.  @333fred @jcouv do you know of any existing issues with parsing anonymous-types, or anything we have fixed in this area that could be causing '3'?  Looking at the code, i can see we do have a loop that does `while (IsMakingProgress(ref lastTokenPosition))`.  However, i personally am not familiar/comfortable with the parser's idioms for loop parsing while ensuring progress to know if this is written correctly.  This will likely take further investigation from compiler team here.

**Comment by jcouv** [comment]
@AntonGrekov Any chance you'd have a repro you could share for this? Alternatively, making a crash dump when the situation is occurring would also help.

**Comment by CyrusNajmabadi** [comment]
I've asked if he can package his sources and send to me.  With that, i can see if we can repro locally by just trying to parse the files.  Absent that, i can look at all the anonymous types to see if there's something of interest.

**Comment by CyrusNajmabadi** [comment]
Note: the crashdump gives me:

![image](https://user-images.githubusercontent.com/4564579/178807383-4d71a80a-17d1-4c32-8171-bf4f9b1cb947.png)

If @antongrekov can capture a dump of the servicehub process when its in this state and uploads it, that would likely show the stack doing the parsing and we would likely be able to (hopefully) grab the sourcetext without too much issue.

**Comment by RikkiGibson** [comment]
I wasn't able to determine what causes the infinite loop by inspecting the code. It will help us solve this if we get a reproducer program.

**Comment by CyrusNajmabadi** [comment]
@antongrekov  please see previous messages in this thread and the original one.  We'll need at least a copy of your source aat the time when you're encountering this problem.

**Comment by CyrusNajmabadi** [comment]
Marking as need-more-info.
