### ISSUE TITLE
Square brackets not expanding correctly in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Square-brackets-not-expanding-correctly-/10093299)._

---
[severity:It bothers me. A fix would be nice]
When opening (or expanding a bracket; as shown below) a square bracket in Visual Studio, two lines of spaces are added instead of the expected one line of space.

```
// expected

[] -> [

      ]


// actual 

[] -> [


      ]
```
 

Since VS Code has consistent behavior between brackets/braces (only one space per bracket opening), I suppose this is an error as well and not an intentional implementation.

_Note:_ Curly braces in Visual Studio have the expected behavior. So the potential bug is isolated to square brackets.

**Gif attached displaying current behavior in VS.**

**Other Info**
C# Console App
.Net Version: 6.0
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.2.4

---
#### Feedback Bot on 7/12/2022, 05:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
User gif:

https://vsfeedback.azurewebsites.net/api/fileBlobMetrics/getAzureBlobFromTransferId?transferId=9b7c8b69a81e4d04b35a5acebcb1c686637932558614968764

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi `Request does not contain valid AAD or VSO (AzDo) Jwt token. Error message: JWT token is null`

**Comment by HermesBonilla** [comment]
Thanks @CyrusNajmabadi. :)

Hope the report was helpful!

**Comment by CyrusNajmabadi** [comment]
This no longer repros for me.
