### ISSUE TITLE
Accessing static abstract operators gives unclear error message

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#62614]
When accessing most `static abstract` or `static virtual` interface members C# surfaces `CS8926: A static virtual or abstract interface member can be accessed only on a type parameter.`

For example see this code:
```csharp
public bool M() => INumber<int>.IsNegative(5);
```

However, for operators in particular it still surfaces `error CS0023: Operator '+' cannot be applied to operand of type 'I<S>'`

For example see this code:
```csharp
public void M(INumber<int> x) => +x;
```

It would likely be beneficial to also surface `CS8926` for this scenario since the restriction is due to it being a `static abstract/virtual` and therefore requiring a properly constrained `T` to access.

**Comment by tannergooding** [comment]
CC. @jaredpar, @AlekseyTs

**Comment by AlekseyTs** [comment]
Here is complete stand alone repro with INumber:
```
class Program
{
    static void Main()
    {
    }
    
   
    public object M1(System.Numerics.INumber<MyInt> x) => +x;
}

struct MyInt : System.Numerics.INumber<MyInt>
{
    static MyInt System.Numerics.IUnaryPlusOperators<MyInt, MyInt>.operator +(MyInt value)
    {
        throw new System.NotImplementedException();
    }
}


namespace System.Numerics
{
     public interface INumber<TSelf>
        : INumberBase<TSelf>
        where TSelf : INumber<TSelf>
    {
    }

    public interface INumberBase<TSelf>
        : IUnaryPlusOperators<TSelf, TSelf>
        where TSelf : INumberBase<TSelf>
    {
    }

    public interface IUnaryPlusOperators<TSelf, TResult> where TSelf : IUnaryPlusOperators<TSelf, TResult>
    {
        static abstract TResult operator +(TSelf value);
    }
}
```

error CS0023: Operator '+' cannot be applied to operand of type 'INumber<MyInt>'

**Comment by AlekseyTs** [comment]
I think the error accurately reflects analysis performed by the compiler. After type substitution, the signature of the operator is 
```
static abstract MyInt operator +(MyInt value);
```

Note, the parameter type is ```MyInt```, the type of ```x``` is, however, ```INumber<MyInt>```. There is no implicit conversion from ```INumber<MyInt>``` to ```MyInt```. Therefore, the operator is not applicable. The fact that it is abstract doesn't even come into play.

**Comment by tannergooding** [comment]
> Therefore, the operator is not applicable. The fact that it is abstract doesn't even come into play.

Right, the issue is that this is still confusing to consumers of the API and its been raised by a few different users.

If possible, it would be beneficial for the compiler to recognize that `+x` is being done on a `INumber<T>` (the type of `x`) and surface a more helpful diagnostic to the consumer as the intent of the user was likely to access the `static abstract` operator and therefore the change would be to access it via a type parameter.

**Comment by AlekseyTs** [comment]
Access on a type parameter like this isn't going to work either:
```
public object M2<T>(T x) where T : System.Numerics.INumber<MyInt> => +x;
```

So that is not the primary issue. I do not think compiler should special case specific definition of an operator that we have today. Perhaps a doc comment and documentation in general for the operator should clearly describe how to properly consume it and provide good/"bad" examples.
