### ISSUE TITLE
False IDE0055 (Fix formatting) reported when using multiple TargetFrameworks

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62612]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/False-IDE0055-Fix-formatting-reported-/10093052)._

---
[severity:It bothers me. A fix would be nice]
I am compiling a class for multiple TargetFrameworks. Some parts of the class are only compiled for certain TargetFrameworks. Correct formatting of the documents is enforced via .editorconfig and `EnforceCodeStyleInBuild`.

It seems, the desired formatting of `#region`-statements depends on whether the code is active or not. So no matter how I try to fix the formatting - the build will always raise a warning for one of the frameworks.

In the screenshot it is nicely visible, that line 6 has the same formatting as line 17, yet the formatting of line 6 is flagged.

Workaround: Avoid usage of `#region`-statements in code that is compiled conditionally.

---
#### Feedback Bot on 7/12/2022, 07:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
User image:

![image](https://user-images.githubusercontent.com/4564579/178817460-fcb43ab1-20f4-4f7f-9052-90902c669b56.png)

I agree this is weird.  I don't know why we'd do any formatting checks in a region that is conditionally disabled.  Region checks in particular (though still understood to be regions) should not be checked here.

**Comment by sharwell** [comment]
The solution here is to avoid reporting diagnostics for formatting of preprocessor directives inside a disabled code block.

**Comment by Youssef1313** [comment]
I'm hitting the exact same issue

**Comment by manfred-brands** [comment]
In what version is this released? I'm running 7.0.109 and it still reporting this. (NUnit source code conditional on NETFRAMEWORK)
