### ISSUE TITLE
Correct way to rename a file in a code fix

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#6261]
We have a code fix for [SA1649: File name must match first type name](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md) which renames a file. We have special handling in place to make sure that when renaming a file which is linked into multiple projects, all projects are updated to reflect the new name of the file. However, we are now facing the problem described in DotNetAnalyzers/StyleCopAnalyzers#1665, where renaming a file in a shared project moves that file into each of the projects referencing the shared project.

:question: What is the proper way to perform and in-place rename of a file as part of a code fix?

:memo: For reference, the [current code fix can be seen here](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1649CodeFixProvider.cs#L50-L72).

**Comment by Pilchie** [comment]
Should there be a `RenameDocument` API that handles this?

**Comment by lorcanmooney** [comment]
I'm trying to fix #5378, but it _really_ needs this `RenameDocument` API to give the user an acceptable experience.

`RenameFileEditor` has a workaround that I tried, but it trashes the undo stack and causes the file to be reopend, losing the cursor position and view state.

**Comment by ryzngard** [comment]
There's a `Renamer.RenameDocument` API now.

**Comment by sharwell** [comment]
@ryzngard do you know which version this is first available in?

**Comment by ryzngard** [comment]
@sharwell  16.7 P1

**Comment by sharwell** [comment]
Reopening as the current `RenameDocumentAsync` API does not simply rename a document. It instead performs a _symbol_ rename within the document, and is therefore useless as a document rename.

**Comment by sharwell** [comment]
The resolution here is to call `RenameDocumentActionSet.UpdateSolutionAsync` after calling `RenameDocumentAsync`, and pass in an empty set of actions.
