### ISSUE TITLE
Convert Type to Record

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#62623]
## Summary

This feature would add a refactoring that allows the user to convert a declared type into its corresponding record type declaration and converts properties and constructions to use positional parameters appropriately. It would also potentially convert all classes/structs in the selected scope using a fix all feature.

## Background and Motivation

A new feature in C# 9 is the `record` type, which provides an easy way to create an immutable and value-equality data type. It automatically generates properties constructors, and equality comparisons based off some initial parameters. We want to encourage people to learn about and use this new type, and so this refactoring would help people who already have lots of data types convert them to records quickly and efficiently.

This feature has a few asks from users, shown in #47598 and #49682

## Proposed Feature

[Prototype feature](https://user-images.githubusercontent.com/43689321/178840528-cf2981ea-148a-42e0-8ed8-3b7102d5d7d0.webm)

For the following, imagine we are attempting to refactor a type `R`
- Single refactoring will activate on classes without a base class or structs, where there is at least one property that we can move to a positional parameter
  - we can move properties that are `get; init;` for classes and readonly structs, and `get; set;` for normal structs, and shouldn't have explicit definition for the property itself or any accessors
- Refactoring can be activated when the cursor is on the class declaration
- Moveable properties will be converted to positional parameters with the same type and name, and attributes/doc comments converted
- Any existing constructor with the same signature as the converted positional parameters will be deleted
- All other constructors will be prepended with a `this(...)` initializer that gives values for every positional parameter
  - If a certain parameter can't be moved from the constructor body to the initializer, we fill in with `default`
  - The exception is the copy constructor, which must call using the `base()` initializer
- If the user has defined the operators `==` and/or `!=`, we remove them if they reference the `.Equals` method
- If the user has an `Equals(object? other)` method, we replace it with `Equals(R? other)`
  - If that method also exists, we delete the object one
- If the user has a method called `R Clone()`, we delete it
- If the user has defined a method with the signature `bool PrintMembers(StringBuilder)`, we ensure it is `protected virtual` for classes, and `private` for structs
- If the user defines a property `Type EqualityContract` in a class, we ensure it is `protected virtual` and readonly
- We refactor any bracket-based constructions of the changed type in the solution to instead use the provided constructor with positional parameters
  - Any properties named/created that aren't in the positional params stay in the bracket construction

## Alternative Designs

- Convert `get; set;` properties to positional parameters in classes as well
- Convert properties with explicit expressions/initializers to positional parameters (but keep overriding declaration as well)
- Offer to convert classes with base types even though it will produce an error
- Search for derived classes of class we are currently in and stop refactoring/offer to convert those as well
- Offer to convert classes/structs with no convertible properties (either for single refactoring or as part of a fix all)
- Don't delete any of the proposed deleted members. This would create errors that the user would have to solve
  - Constructor with same params as positional params - Consider re-ordering params so they no longer match?
  - Equality operator overloads
  - `Equals(object? other)` It's a pretty unlikely edge case if the user has `Equals(object? other)` and `Equals(R? other)` and the former doesn't just call `Equals(other as R)` (which is what the generated implementation does)
  - `Clone()` This is a case where we most likely will break something either way, as `Clone` is probably an important method, but isn't allowed to be declared on a record type. We could rename it to `_Clone()` or something instead
- Only refactor in a more limited scope, such as project or folder
- Offer dialog for individual and/or fix all to allow user to modify which members get deleted, how properties are converted, etc.

**Comment by CyrusNajmabadi** [comment]
A few thoughts:

> This feature would add a refactoring that allows the user to convert a declared type into its corresponding record type declaration and converts properties and constructions to use positional parameters appropriately.

This is def great.  However, it would be catering to the group that likes records with primary constructors.  We def have a significant number of users who like init-property-based records.

> we can move properties that are get; init; for classes and readonly structs, and get; set; for normal structs,

Supporting `get; set;` on normal classes seems like it would be great too.  Lots of people will be using those.  I do think we'll likely have to let the user know semantics may change and that not all code may successfully transition.  

> If the user has an Equals(object? other) method, we replace it with Equals(R? other)

It would be interesting/desirable (IMO) if we analyzed their methods to see if they have the same semantics that the default Equals would generate.  And, if so, we remove.  Otherwise we keep.  THere is precedence for this with the "Use System.HashCode analyzer/fixer" which figures out what is being examined (And how) to determine hashing.

**Comment by CyrusNajmabadi** [comment]
> Offer dialog for individual and/or fix all to allow user to modify which members get deleted, how properties are converted, etc.

I think tehre could be a lot of value in this.  Especially the core case of determining which order the parameters should be in.  That said, i would totally be ok having that be initially scoped out, and then come in later.

**Comment by Soreloser2** [comment]
> I think it would be worth offering two fixes here perhaps, one "Convert to record" and one "Convert to record (without positional constructor)"?

Previously I was hesitant about offering a refactoring without a positional constructor since it seemed like it wouldn't do much besides adding the record keyword, but I think I see the motivation behind it now, for example users with old C# data types that were `get; set;` could convert them to `get; init;`, and we could do some more refactoring around methods that records provide such as HashCode and equality semantics (potentially deleting them).

I think offering multiple options definitely makes sense, we could have "Convert to positional record", "Convert to propertied record" (these both could probably have better names), and "Advanced...", which could handle different combinations of options and the ability to apply to all through a dialog.

**Comment by davidwengier** [comment]
> Previously I was hesitant about offering a refactoring without a positional constructor since it seemed like it wouldn't do much besides adding the record keyword

Thats a very good point, and maybe the refactoring could consider that even. ie, if it seems like the only thing that will actually be done is change a keyword, don't offer. Leaving all of these more complicated scenarios for later, when there is a dialog, would also be totally fine IMO.

**Comment by Soreloser2** [comment]
Interesting note: The [Records language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records) claims that it is an error to explicitly override the equality operators `==` and `!=`, however in a test project, I was able to write these methods and build in a record without error. Perhaps this is a bug in the language implementation, or maybe the specification is outdated. Other methods which have a similar requirement do show errors, so it seems it is unique to the operator overloads. If we were to follow this, we would probably then consider those operators similar to how we consider `Equals` and `GetHashCode` since there is a default implementation that we probably want to use, but the user is _allowed_ to override/define them themselves.

**Comment by Soreloser2** [comment]
Generally, we have been thinking about a use case where a user has a bunch of old classes that they would like to be immutable and are either all `get; init;` or all `get; set;` (because they haven't converted since `init` was introduced). However, in the case where the user has multiple properties, and some are `set`, while others are `init`, should we assume that the user does not want their `set` properties to be converted? I'd think so. Maybe this is a case where the positional parameter conversion would not move the `set` properties, but a non-positional one would convert the `set` to `init`.

**Comment by genlu** [comment]
Design meeting notes:

Conclusion:
Convert a type with setter property to immutable record would break things in certain cases but given that this is a refactoring and users explicitly ask for it, it should be OK.

We could provide two options. One does everything to convert it to an immutable record (with primary ctor, we can revisit this if there's pushback from users and have that as a separate refactoring instead), another one does smaller incremental change that doesn't change {set} property to {init}, only try to get rid of the implementation of equality, etc.
