### ISSUE TITLE
[API Proposal]: ModuleInitializerAttribute for VB.NET

### ISSUE THREAD

**Issue by KoB-Kirito** [dotnet/roslyn#62625]
### Background and motivation

I need [this](https://github.com/dotnet/runtime/issues/35749) functionality in VB.NET, but sadly:
[BC42381] 'System.Runtime.CompilerServices.ModuleInitializerAttribute' is not supported in VB.

### API Proposal

-

### API Usage

```vb
Imports System.Runtime.CompilerServices

Public Class INeedSomeInitBeforeStartup

    <ModuleInitializer>
    Public Shared Sub Foo()
    End Sub

End Class
```

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue. Unfortunately at this time it is not in the scope of features being considered for Visual Basic.
