### ISSUE TITLE
AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer should sub-type AbstractBuiltInCodeStyleDiagnosticAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#62638]
https://github.com/dotnet/roslyn/blob/8bd10f1548db958b1983f3bd236fcc56aafae1be/src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs#L21-L22

**Comment by Youssef1313** [comment]
This analyzer can analyze *and* report diagnostics in generated code, so a new property similar to

https://github.com/dotnet/roslyn/blob/8bd10f1548db958b1983f3bd236fcc56aafae1be/src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs#L74

will be needed.
