### ISSUE TITLE
Fix all warnings and errors set in EditorConfig should be the default setting in Code Cleanup 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#62651]
`Fix all warnings and errors set in EditorConfig` should automatically be promoted. A user should be able to set their EditorConfig and then run code cleanup and it all works. We can have a third profile that represents EditorConfig settings and have it be the default. Having this be the default experience will solve current discoverability issues and overhead of needing to configure both an EidtorConfig and Code Cleanup. 

![image](https://user-images.githubusercontent.com/46729679/179050643-2d4f374d-4700-46f7-8114-985d75f49817.png)

**Comment by mikadumont** [comment]
Investigating this a bit more profiles currently dont roam so users have gotten used to loosing their settings after each re-install. Therefore overriding settings for the EditorConfig one may not upset users since theyre used to this behavior especially if there will now be a benefit to them loosing it.

**Comment by genlu** [comment]
Design meeting notes: 

Conclusion: we'd like to address the UX issue that everyone still need to change their setting individually even if there's editorconfig, but making "fix all warn/error of editorconfig" default could have negative perf impact.

Next step:
- Demonstrate with experiment that no perf impact if no warn/err set in editorconfig, or if there is warn/err set, we don't impact perf when no such diagnostics exist. 
- Discuss with Editor team, explore a better solution to expose this capability.

**Comment by yitzhaks** [comment]
There may be a middle ground here. We can allow configuring the cleanup profiles in the .editorconfig file. This will allow users to create a shared cleanup profile and make it as lightweight or intensive as they wish.

**Comment by bt-Knodel** [comment]
This option for us adds Obsolete every in code.  Is there a setting in EditorConfig that prevents code modifications like adding Obsolete?

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.  IF we need to do this, this needs to be assigned to a dev/milestone to acctually be done in.
