### ISSUE TITLE
Cleanup fading options

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#62666]
Follow-up cleanup work for #62562:

- [ ] https://github.com/dotnet/roslyn/pull/62562#discussion_r921318283
- [ ] https://github.com/dotnet/roslyn/pull/62562#discussion_r921356555
- [x] https://github.com/dotnet/roslyn/pull/62562#discussion_r921299606
- [ ] https://github.com/dotnet/roslyn/pull/62562#discussion_r921296616
- [ ] https://github.com/dotnet/roslyn/pull/62562#discussion_r921304789

LSP related cleanup for pull diagnostics:
- [ ] https://github.com/dotnet/roslyn/pull/62562#discussion_r921415397

**Comment by CyrusNajmabadi** [comment]
All of these were completed.  Closing this out.
