### ISSUE TITLE
What are the different top-level solution files?

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#6267]
I'm kind of puzzled about the four different solution files in repository root:

 * `Compilers.sln`
 * `CrossPlatform.sln`
 * `Roslyn.sln`
 * `Workspaces.sln`

`Roslyn.sln` seems pretty obvious: it's got all of Roslyn proper in it. For the others, I'd like to see explanations of:

 1. What is it for?
 2. What does it consist of?
 2. How is it maintained?

If this can all be put succinctly enough, it should probably go in `README.md`; otherwise, I think it at least warrants a link from there.

**Comment by davkean** [comment]
Added a section to the wiki: https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging.

Also just submitted a PR to remove Workspaces.sln.

**Comment by SamB** [comment]
[Obligatory link to #6275]
