### ISSUE TITLE
SyntaxProvider in incremental source generators caches a lot of symbols for large solutions

### ISSUE THREAD

**Issue by Tatenshi** [dotnet/roslyn#62674]
We have a large solution with many projects, many of which use source generators. At the moment we use four non-incremental generators. We use these very extensively to generate a lot of source files. Because we have performance problems with our current generators, we wanted to change them to incremental generators, because they are made for such large solutions. During this conversion we noticed a problem.

All generators use SyntaxProviders. These have a Predicate and a Transform. If I understood it correctly, the result of the Predicate is cached, because the transform step must be run again, but the Predicate only if something has actually changed in the syntax tree. This is possible because the driver knows which nodes have changed and can therefore safely skip the Predicate. However, the Transform may have changed even if it has not, since it works on the Semantic Model.

Now the thing is that many of our source generators hit a lot of symbols. By this I mean that for example one of our source generators hits almost every class definition of our whole solution in the Predicate step (where we are mainly interested in the name of the class) and generates things based on that. Another one hits almost every property of almost every class. This in combination with our solution size leads to a lot of symbols being cached from the first Predicate. You can see this in the RAM usage, which is very high (6-10 GB range) in the RoslynCodeAnalysisService process after porting 3 of 4 source generators to their incremental version.

Now, however, the fact is that we actually don't need the semantic model for our generators at all. Our existing non-incremental source generators also only use the syntactic model. Therefore the question, if there would be a possibility to get access to the Syntactic Model only. Thereby, if I have understood it correctly, no caching of the expensive symbols would be necessary any more. The necessary information from the syntactic model would be also only very small (in the one example only the class name), why a fast extraction is no problem. Only the caching of the symbols from the predicate step causes problems. A further advantage would be that a change of a file can have only a very limited effect on the output, since there is no access to the semantic model.

**Comment by jaredpar** [comment]
@chsienki PTAL

**Comment by chsienki** [comment]
Thanks @Tatenshi. I'm just trying to understand your scenario a little bit better:

It sounds like you only want to look at the syntax in a source file, with no need to get at the symbols. This is possible today by just returning the syntax that was selected back in the semantic transform (the semantic model is lazily created, so unless you access it we'll never actually create one).

Eg.

```csharp
IncrementalValuesProvider<SyntaxNode> classes = context.SyntaxProvider.CreateSyntaxProvider((n, ct) => n is ClassDeclarationSyntax, (ctx, ct) => ctx.Node);
```
Or better yet, extract the class name directly during the semantic check in order to skip later steps

```csharp
IncrementalValuesProvider<string> classNames = context.SyntaxProvider.CreateSyntaxProvider((n, ct) => n is ClassDeclarationSyntax, (ctx, ct) => ((ClassDeclarationSyntax)ctx.Node).Identifier.Text);
```

That will only allow you to inspect the syntax without ever creating the symbols.

Does that answer your issue, or are you still seeing large memory usage even when just looking at the syntax nodes?

**Comment by Tatenshi** [comment]
Unfortunately, I was no longer able to recreate my original problem even without the suggested changes.

During the course of the day I did get to very high RAM usage over 14 GB a couple of times, however the problem here was not the symbols/syntax elements but CSharpCompilation & CSharpGeneratorDriver which together consumed about 13 GB in the RoslynCodeAnalysisService. I don't know if these are related to my theory above, but would guess no.

Therefore, would add the incremental generators to my workflow for this week and monitor if I can somehow recreate it. I would get back to you by the end of next week at the latest

Translated with www.DeepL.com/Translator (free version)

**Comment by Tatenshi** [comment]
Unfortunately, I still could not recreate it. I had the high RAM usage by the two classes described above a few more times, but that could also be related to the usage of the semantic model. So I would close the issue for now. If after switching the V2 generators to the pure syntactic model, problems occur again or if I can recreate it, I would reopen it.

Thanks for the help :)
