### ISSUE TITLE
.net 6 + ISymbol.GetAttributes returns Attributes without constructor arguments. 

### ISSUE THREAD

**Issue by G31st** [dotnet/roslyn#62672]
Hi All, strange bug... 

Versions: 
"Microsoft.CodeAnalysis" Version="4.3.0-2.final"
"Microsoft.CodeAnalysis.CSharp" Version="4.3.0-2.final" 
"System.CodeDom" Version="7.0.0-preview.6.22324.4" 

I've tried all versions of CodeAnalysis 4.0.1-4.3.0* and CodeDom 6.0.0-7.0.0-preview.6.22324.4

Steps to Reproduce:

1. Set all assemblies to target : TargetFramework = net6.0 
2. When calling : ISyntaxContextReceiver.OnVisitSyntaxNode() context.SemanticModel.GetDeclaredSymbol(methodDeclarationSyntax).GetAttributes().FirstOrDefault();
The attribute returns without having any details on the parameters from the constructor:
[MyHttpApi(Method.Get, "/Example/HelloWorld", Version = HttpApiVersion.V1)]

Expected Behavior:
![image](https://user-images.githubusercontent.com/52254120/179193848-02bb6c60-6f96-4e3c-9707-3947c179aaab.png)

Actual Behavior:

![image](https://user-images.githubusercontent.com/52254120/179192279-a6b70010-6170-4a46-97ae-3a0c4b2b17cd.png)

The strangest thing here is that if the custom attribute assembly (MyHttpAPIAttribute) targets  a much older framework ie netstandard2.0 then the generator assembly (still in .net6 ) returns the expected behavior. 

![image](https://user-images.githubusercontent.com/52254120/179197717-62ce6899-178e-48c2-a296-8cf598559c19.png)

**Comment by svick** [comment]
Can you provide code that reproduces the issue? Are there any diagnostics reported on the compilation in question?

**Comment by pinkfloydx33** [comment]
> the generator assembly (still in .net6 )
Don't generators have to be netstandard2.0?

**Comment by jaredpar** [comment]
Closing do to lack of actionable sample here as requested.
