### ISSUE TITLE
[API Proposal]: `IMethodBodyOperationBase` should have a `Symbol` property

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62705]
## Background and Motivation

Analyzers that registers operation callbacks for `IMethodBodyBaseOperation` or `IConstructorBodyOperation` cannot get the symbol for the method/constructor without falling back to semantic model, which is discouraged by https://github.com/dotnet/roslyn-analyzers/blob/bd2c586f5559e30cc366dcf0089305dcb1947b88/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Operations
{
     public class IMethodBodyOperationBase
     {
+        public ISymbol Symbol { get; }
     }
```

## Usage Examples

In analyzers, as indicated above.

## Alternative Designs

Instead of introducing the property in `IMethodBodyOperationBase`, we can introduce `MethodSymbol` and `ConstructorSymbol` on `IMethodBodyBaseOperation` and `IConstructorBodyOperation` respectively

**Comment by Youssef1313** [comment]
Tagging @333fred as area owner.

**Comment by 333fred** [comment]
When would you register for a callback and not have a context with the correct symbol on it?

**Comment by Youssef1313** [comment]
That seems to work in my case. Thanks.
