### ISSUE TITLE
Regression: RegisterPostInitializationOutput+AddSource added in source generator is duplicated resulting in compiler errors

### ISSUE THREAD

**Issue by pakrym** [dotnet/roslyn#62711]
**Version Used**: 
VS 17.2.6
SDK 6.0.302

**Steps to Reproduce**:

Sorry I don't have a smaller repro. 
1. Build https://github.com/mike-ward/tweetz/tree/master/src/tweetz.core using 17.2.6/6.0.302

**Expected Behavior**:
The Jab code generator runs as before and the project compiles.

**Actual Behavior**:

The file included in `RegisterPostInitializationOutput+AddSource` (
https://github.com/pakrym/jab/blob/main/src/Jab/ContainerGenerator.Roslyn4.cs#L27-L30 ) is duplicated and results in many errors similar to `Duplicate 'AttributeUsage' attribute`.

I've got two reports from people having similar problems at https://github.com/pakrym/jab/issues/109. I was able to track down the issue to the pre-added source file being duplicated.

This is a regression from 6.0.300

**Comment by davidwengier** [comment]
Is it happening in a wpf project? If so, this would be https://github.com/dotnet/wpf/issues/6792

**Comment by davidwengier** [comment]
Just looked at the issue on your repo, seems like yes. Have commented there and will close this as a duplicate.
