### ISSUE TITLE
Code CleanUp doesnt not work as expected

### ISSUE THREAD

**Issue by vancodocton** [dotnet/roslyn#62727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I config `src/IdentityServer/UI/UI.csproj` as below
```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>DuongTruong.IdentityServer.UI</AssemblyName>
		<RootNamespace>DuongTruong.IdentityServer.UI</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

</Project>
```
Then I create new Razor Pages - Empty by using VS Community in `src/IdentityServer/UI/Pages/Demo.cshtml.cs`:
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuongTruong.IdentityServer.UI.Pages
{
    public class DemoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
```
Then I figure out that there is a quick action.
![image](https://user-images.githubusercontent.com/55989165/179484821-8c525d1b-c006-441d-9c50-22062c0f4e85.png)

When I clicked, it throw an exception from VS. I've choose `enable and ignore`, and don't know how to show it again.

Then I run code cleanup for my solution, with fixer `Apply namespace matches folder preferences`, the namespace change `DuongTruong.IdentityServer.UI.Pages` to `DuongTruong.IdentityServer.UI.UI.Pages`, that break my structure:
```
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuongTruong.IdentityServer.UI.UI.Pages
{
    public class DemoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
```
I've use this fixer to refactor my code if it doesn't match folder structure.

### .NET Version

6.0.302

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by vancodocton** [comment]
src/IdentityServer/UI is my own custom project using Duende.IdentiyServer for Application (UI + API). Hope this issue will be fixed soon.

**Comment by ryzngard** [comment]
@vancodocton this is by design. An easy fix would be to make the root namespace not include "UI". Suggested namespaces will always be root namespace + relative path, so in this case it's `DuongTruong.IdentityServer.UI` from the root namespace + `UI.Pages` from the relative path of `\UI\Pages`.

**Comment by vancodocton** [comment]
> @vancodocton this is by design. An easy fix would be to make the root namespace not include "UI". Suggested namespaces will always be root namespace + relative path, so in this case it's `DuongTruong.IdentityServer.UI` from the root namespace + `UI.Pages` from the relative path of `\UI\Pages`.

My project is in folder `src/IdentityServer/UI`, not in folder `src/IdentityServer`. Hence, the relative path to the razor page is only `Pages/` folder. So that, I've reported it because of it doesn't working as expected. 

The suggested namespace is correct, but when I run code analysis, it turn to wrong.

**Comment by ryzngard** [comment]
I see, I missed that small detail. Thanks for more information @vancodocton . Is there a sample zip you cna provide with the sln/csproj? Otherwise I'll try to get one with a repro later
