### ISSUE TITLE
CS0121 for extension methods with and without ref modifier

### ISSUE THREAD

**Issue by joemey** [dotnet/roslyn#62729]
**Version Used**: 

.Net 6.0.101 and .Net 7.0.100-preview.6

**Steps to Reproduce**:

```
using System;

public static class A
{
    public static void Foo(this Span<byte> span) { }
}

public static class B
{
    public static void Foo(this ref Span<byte> span) { }
}

public class Program
{
    static void Main()
    {
        Span<byte> span = new byte[10];
        span.Foo();  // error CS0121: The call is ambiguous between the following methods or properties: 'A.Foo(Span<byte>)' and 'B.Foo(ref Span<byte>)'
        A.Foo(span);
        B.Foo(span);  // error CS1620: Argument 1 must be passed with the 'ref' keyword
    }
}
```

**Expected Behavior**:

I would expect that `A.Foo()` is used because `B.Foo()` is not a valid candidate.

this is not restricted to use of `Span<byte>`, chaning the type to `int` (or any other struct type) results in the same error

**Comment by svick** [comment]
> I would expect that `A.Foo()` is used because `B.Foo()` is not a valid candidate.

[`B.Foo` is a valid candidate.](https://sharplab.io/#v2:D4AQTAjAsAULIGYAEIIDYViQIVgb1iSJWVQxABYkAxAe1oAoAXACwEsBnJAJwFMAzJAGUADgEMAdgB4ARgE8mvAHxIO4iQEokeJAF9Y+uDESYUEAOz5CxMiioBZMWwkMN1ogRjFvw9bIXKqupIALxIErwA7kjyigDaEAAMALoA3O4+apIAdHSMGulexIa6QA) [The feature "ref extension methods" was added in C# 7.2.](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods#extending-predefined-types)

**Comment by joemey** [comment]
comparing [only A.Foo](https://sharplab.io/#v2:D4AQTAjAsAULIGYAEIIDYViQQVgb1iSJWVQxABYkAxAe1oAoAXACwEsBnJAZQAcBDAHYAeAEYBPJgFMAfEg4DBASiR4kAX1ia4MRJhQQA7PkLEyKKgFl+bQQyWmiBGMVc9FYybPmKkAXiRBKQB3JAlpAG0IAAYAXQBuRzcFIQA6OkYlRJdibXUgA) and [only B.Foo](https://sharplab.io/#v2:D4AQTAjAsAULIGYAEIIDYViQIVgb1iSJWVQxABYkAxAe1oAoAXACwEsBnJAJwFMAzJAGUADgEMAdgB4ARgE8mvAHxIO4iQEokeJAF9Y+uDESYUEAOz5CxMiioBZMWwkMN1ogRjFvw9bIXKqupIALxIErwA7kjyigDaEAAMALoA3O4+apIAdHSMGulexIa6QA) I see that `B.Foo` is only a valid candidate, because the compiler simply adds the `ref` modifier to the method call. 

that's not what I would have expected, because there is no indication (or warning) that I'm calling a method which can alter the struct im passing in.

On a second thought, i don't see how to add the `ref` modifier when using the short form of the extension method in the first place.

**Comment by joemey** [comment]
> Effectively, this is passed by ref for struct instance methods.

I know how structs are passed and that's actually the reason I'm so confused about this. This is not a struct instance method im calling, but a static method where I have to use the `ref` modifier to choose if I want to pass by reference or by value.

In this case, [the compiler adds the missing `ref` modifier by itself which is not obvious and is not mentioned anywhere](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaogZgAIiykmSGAhagb2of6aNmrIigYAxCBAAUGABYBLAM4NYAMwYK8GBgDcAhgBsAlA256jAaksBuBgF8+A+kxZMxHfVFmKVAzdoWJmZB1naOVBG0QuzMAOw8TvzC7gwAsvpa0sZJZrn+WjoKDAC8DAAMNvnOZACc0grGVVT+BQB0kjJNDAD0PQwAPHAMwACeqjBq1cl1DU3Tmm2e3t19g8NjQQvM9Y3N/hH2QA=) and why i thought that `B.Foo` wasn't a valid candiate in the first place.

**Comment by CyrusNajmabadi** [comment]
> This is not a struct instance method im calling, but a static method where I have to use the ref modifier to choose if I want to pass by reference or by value.

**Comment by CyrusNajmabadi** [comment]
Question ahs been answered.  This is oeprating as per the language spec.  Requests to change how hte language work should go to dotnet/csharplang.  Thanks!
