### ISSUE TITLE
`IsKnownIDEDiagnosticId` implementation doesn't look correct

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62733]
`IsKnownIDEDiagnosticId` will return `true` only for IDE analyzers that has an option passed to `AbstractBuiltInCodeStyleDiagnosticAnalyzer`. It will return `false` for other IDE analyzers.

https://github.com/dotnet/roslyn/blob/027ff7b510ed0d5a5616e093eb572117826cf8dc/src/Analyzers/Core/Analyzers/IDEDiagnosticIdToOptionMappingHelper.cs#L34-L36

@mavasani

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
