### ISSUE TITLE
provide a way to create CompilationReference that get Compilation lazily

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#6274]
I already talked about it with @VSadov . basically to reduce memory foot print we would like to let compilation go in IDE that is held alive in memory by p2p reference when it is not needed.

current propose is adding new API that accepts compilation factory which can re-produce compilation for the snapshot when needed on demand.

**Comment by heejaechang** [comment]
it would be nice if we can do this for update 2.

adding @pharring @rchande since it is related to performance improvement on IDE.

**Comment by jaredpar** [comment]
I'm considering pushing this out to 1.3.  It doesn't seem that anyone has the bandwidth to absorb this change into IDE right now.

**Comment by VSadov** [comment]
Yes. It feels like even if we implement this, IDE will have no time to use this.

**Comment by heejaechang** [comment]
yep. we need this by diagnostic goes OOP which is for update 3

**Comment by jaredpar** [comment]
@heejaechang given the priority of the Out Of Proc work how does this issue stack up now?  I'm considering moving it to 2.1.

**Comment by heejaechang** [comment]
@jaredpar regardless of OOP, I think we can reduce quite a bit of memory usage if we do this. for example, for any open file, IDE make sure it holds onto compilation that open file belong to. and you can imagine if we only hold onto direct p2p reference compilation instead of all transitive p2p references, how much compilations we can let go.

**Comment by CyrusNajmabadi** [comment]
> I already talked about it with @VSadov . basically to reduce memory foot print we would like to let compilation go in IDE that is held alive in memory by p2p reference when it is not needed.

This is not a concept we intend to support.  Indeed, we've moved away from this.  Recreating/dumping compilatinos is so expensive, we want to never do it.  once a compilation is created, it's b etter to keep around until naturally GC'ed rather than try to purge and cause expensive recreates.
