### ISSUE TITLE
VS does not show me the function declaration (arguments) when it hits an error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62742]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-does-not-show-me-the-function-declara/10096992)._

---
Hello!

Normally, when I type a function or when I place the mouse over a function, VS hints me the arguments:

![image](https://user-images.githubusercontent.com/4564579/179606360-c1ed1300-58c4-447d-9951-7378562fc2e9.png)

When I did something wrong in my code, and VS breaks the IDE, I would like to inspect the function arguments to see what I did wrong.

But it does not do that:

![image](https://user-images.githubusercontent.com/4564579/179606471-988e67c3-5a9c-4443-a04a-bfa61008d46a.png)

In the video you can see how it broke because I made a mistake. 
When I move the mouse over the function or even type into it, VS does not show me the possible args.

I have to really stop the app to be able to see them.

---
#### Feedback Bot on 7/17/2022, 07:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
ctrl-shift-space when in teh signature is the key binding here.    We call this parameter-info:

![image](https://user-images.githubusercontent.com/4564579/179606599-7bba67da-2229-4844-aaba-9ad42d338faa.png)
