### ISSUE TITLE
[LSP] Support language experiences for roslyn options in editorconfig files

### ISSUE THREAD

**Issue by Danyboyyy** [dotnet/roslyn#62758]
## Summary
This feature is looking to add hovering, completion, and diagnostics to .editorconfig files. 

## Background and Motivation
Despite that .editorconfig files have a GUI for users to modify their settings, some developers prefer modifying these settings in the default text file format. Providing language experiences to these developers will make them have a better experience while dealing with these files.

## Proposed Feature
As mentioned above, there are three main features we want to support: hovering, completion, and diagnostics.

### Hovering
- Display information related to the setting when the user hovers over it
![image](https://user-images.githubusercontent.com/54334789/179638001-3e078b3f-c705-4e1d-8239-03d3a07a7fea.png)

### Completion
- Show completion options when the user is typing a setting
![image](https://user-images.githubusercontent.com/54334789/179638054-3ace1a7c-6eb8-450d-8003-51c1e6dfa1de.png)

- Show the possible values a setting can have
![image](https://user-images.githubusercontent.com/54334789/179638076-9313ee6e-fcdb-4fe0-b9b5-3a457220e00e.png)

- Commit characters: '=', ' ' 

### Diagnostics
Show diagnostics when the user:
- Typed repeated fields
- Miss-typed a setting or its value
- Assigned an incorrect value to a setting

## Alternative Designs
- Add support for classification

**Comment by Youssef1313** [comment]
A quite related old suggestion: https://github.com/dotnet/roslyn/issues/48433

**Comment by Youssef1313** [comment]
The diagnostics part is very related to https://github.com/dotnet/roslyn/issues/19055

**Comment by CyrusNajmabadi** [comment]
Closing out.  Roslyn is tasked with language experiences for C#/VB.  editorconfig experiences are out of scope for us.  This may be something the platform team wishes to pick up.
