### ISSUE TITLE
make CompilationTracker.Finalize in Workspace to create p2p reference that doesnt hold onto compilation strongly

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#6276]
currently, we have this issue where a compilation will hold on to all its p2p reference compilations in memory transitively.

this seems causing some of our OOM issue since one compilation held by background compiler happen to have a lot of p2p references transitively. worse case, whole solution's compilations left alive in memory.

with new API from compiler (#6274), Workspace should be able to create p2p reference (CompilationReference) that doesnt hold onto compilation strongly.

this should let us release all compilations that are not actively used by IDE.

**Comment by Pilchie** [comment]
@mattwar, I believe @heejaechang is investigating some reports of OOMs.  Can you two talk and see if this would help alleviate that?

**Comment by heejaechang** [comment]
This is memory consumption by a solution with 2 default c# console projects with default references.

[cid:image001.png@01D1578E.B1DA95C0]

Given the size of memory consumption by symbols and compilation, it would be nice if we can unload as much as unnecessary compilations (and dll references) from memory.

Current p2p reference is too aggressive, and blindly make live in memory without actual  benefit.

**Comment by heejaechang** [comment]
![image](https://cloud.githubusercontent.com/assets/1333179/12569267/0942235a-c382-11e5-99f4-4cd365a21294.png)

**Comment by heejaechang** [comment]
@jaredpar can we do #6274 sooner so that IDE can unload a lot of compilation (and its dll references from memory)? for example, vs with Roslyn (open) with 1 file opened from csharp vs test project causes us to load over 100 compilations. we probably can reduce a lot of them with the issue implemented.

**Comment by heejaechang** [comment]
another data point. more than half of compilation seems made alive by p2p reference.

![image](https://cloud.githubusercontent.com/assets/1333179/12569779/c076cdc4-c386-11e5-9016-4d7d55dde7d8.png)

**Comment by jaredpar** [comment]
If you all want to persue this for update 2 we can move the compiler side back.

**Comment by CyrusNajmabadi** [comment]
> , it would be nice if we can unload as much as unnecessary compilations (and dll references) from memory

This sounds nice.  However, i'm concerned about two things.  
1. that this may trade off memory for churn.  So we release the compilation.  Then the compiler needs it immediately, and it gets regenerated expensively.
2. This won't be effective.   Even if we weakly hold onto compilations, the compilations will still stay around because of symbols that are help by the project's compilation.  i.e. if we have P1 which references P2, and we have a symbol in P1 which then references a symbol from P2, then P2's compilation is going to stay alive as long as P1's compilation is alive.

**Comment by mattwar** [comment]
How are you going to make compilation references lazy?  You would have to make them re/construct themselves in a synchronous code path.  Wouldn't this defeat the purpose of the async API's in the workspace?

**Comment by heejaechang** [comment]
once we have this ability, proposal was making background compiler to not only hold onto compilations that are directly related to opened files, but its direct p2p reference compilations.

any indirect compilations that are used by symbols in direct p2p reference compilation will make sure those to stay alive in memory. so all those compilations that are actually never used in compilation in opened files will be go away.

about those repeatedly re-creating compilation will be a job for our compilation cache, that cache should make sure repeatedly re-created compilation to be cached.

**Comment by heejaechang** [comment]
@mattwar I think you are talking about getting syntaxtree being async. but those are already when called from compiler side, we do those synchronously. so we can just treat it as same effect?

and I think it will be really very rarely happen.

**Comment by DustinCampbell** [comment]
What's the plan here? I'm going to go ahead and move this 1.3, but please let me know if this needs done now.

**Comment by jaredpar** [comment]
@DustinCampbell this should be in 1.3.  We decided in a separate thread the linked compiler bug wouldn't be fixed until then.

**Comment by DustinCampbell** [comment]
Thanks @jaredpar

**Comment by CyrusNajmabadi** [comment]
This is not a concept we intend to support. Indeed, we've moved away from this. Recreating/dumping compilatinos is so expensive, we want to never do it. once a compilation is created, it's b etter to keep around until naturally GC'ed rather than try to purge and cause expensive recreates.
