### ISSUE TITLE
Removing unused parameters from operators is suggested

### ISSUE THREAD

**Issue by corngood** [dotnet/roslyn#62767]
**Version Used**: 
sharplab default

**Steps to Reproduce**:

I noticed this when making a repro for another issue on sharplab.  I'm not sure how to get details on the suggestions.

https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABAZixICYsAVLAb2KxcooHsA3DAJx4Etg2fjAAuWAOIZRACWQBnABYBhdkIAUASiwBeAHxYADAG5mrcli68BQrKnbsEWAKIBHOMgTz17VACsMAGNRAH5Lf219LAAzT3kMUyJWNkoARgA2OwcndgAHXmRRdh4dHXVaMIAPABo6MIBPSINYrwSzFgsSDKzHS3yeQuKAQjKKrBq6rEbdA1EeODak8wouzIxK3IR+QP5xPIKiniwRUXKqpqNEgF8gA

**Expected Behavior**:

Removing parameters from operators shouldn't be suggested.

**Actual Behavior**:

Removing the unused parameters from these operators is suggested:

```csharp
    public static bool operator==(T? x, T? y) => false;
    public static bool operator!=(T? x, T? y) => true;
    public static explicit operator int(T? x) => 0;
```

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/32852

**Comment by corngood** [comment]
After reading through those other issues I discovered that it can be suppressed using discard names:

```csharp
    public static bool operator==(T? _, T? _1) => false;
    public static bool operator!=(T? _, T? _1) => true;
    public static explicit operator int(T? _) => 0;
```

So I'll close this.  Thanks.
