### ISSUE TITLE
Rename operation should have a wait dialog

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#62777]
Based on internal discussion in Teams, it is expected that in very complex solutions it can take some time to perform a rename. I found that the UI just freezes and it can be fairly disconcerting when it freezes for a minute or more. We should have a threaded wait dialog instead and allow users to cancel the operation if possible.

cc @CyrusNajmabadi @jmarolf @ryzngard

**Comment by Cosifne** [comment]
Sounds like we should pass an IProgressTracker into https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Rename/Renamer.cs,32f2a3a4300147bd,references ?

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson were you using the lightbulb, or were you explicitly invoking rename?

**Comment by RikkiGibson** [comment]
I was explicitly invoking it.

**Comment by CyrusNajmabadi** [comment]
@Cosifne We'll need to update the command handler here to use a TWD.  @ryzngard  for visibility.

**Comment by ryzngard** [comment]
Rename should have a BWI when it's computing locations. https://github.com/dotnet/roslyn/pull/61906 changed it from TWD

**Comment by ryzngard** [comment]
Oh, I see. This is after applying and waiting for the rename to be applied. Agree, TWD should be there. I thought it had one.

**Comment by ryzngard** [comment]
We do have a TWD after apply

![image](https://user-images.githubusercontent.com/475144/192050101-be75a97d-b823-4f7d-81ea-b0bb26a457eb.png)

Is there something missing here? Here's the code: https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs#L780

Going to close but definitely feel free to reopen if I misunderstood

**Comment by RikkiGibson** [comment]
Awesome! Most likely the editor version I was using predated this feature. I'll give it a try when I get the chance. Thanks!
