### ISSUE TITLE
Cannot get the size of a value tuple in the expression evaluator in the debugger

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#62776]
**Version Used**: Version 17.3.0 Preview 4.0

**Steps to Reproduce**:

1. Use C# 8.0 or greater (as asked from the error)
2. Break the application at any point during debugging
3. Open the expression evaluator
4. Enter the `sizeof((byte, byte, byte))` expression for evaluation

**Expected Behavior**:

The expression is computed and the result is returned (which is 4 in this example)

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/8298332/179844011-65c9ef49-eb2d-419c-8c1c-dc16dd758922.png)

**Comment by Youssef1313** [comment]
Not available in C# 10, but available in 8.0 or greater? Weird message.

**Comment by RikkiGibson** [comment]
We should be able to figure this out by adding a test to [CompileExpressionsTests](https://github.com/dotnet/roslyn/blob/main/src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/CompileExpressionsTests.cs). Maybe the helper `GetFeatureAvailabilityDiagnosticInfo` isn't working properly with the compilations which are generated for EE.

https://github.com/dotnet/roslyn/blob/eee6b3c9180c77f4d58be0b2f8cafd2204297d10/src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs#L927

**Comment by ryzngard** [comment]
@tmat PTAL

**Comment by Youssef1313** [comment]
I'm assuming the compilation used by the debugger has no syntax trees.

It's more likely this is a compiler issue in https://github.com/dotnet/roslyn/blob/5030cd43fa32bd67f4da3dededd205110ad800b4/src/Compilers/CSharp/Portable/Compilation/CSharpCompilationExtensions.cs#L14

I think replacing `== true` with `!= false` might resolve the issue.
Alternatively, checks should always be done against `Compilation.LanguageVersion` (which defaults to `LanguageVersion.Default` if the compilation doesn't have any trees.

A possible alternative is whatever caller creating compilation without trees should pass a dummy tree.

**Comment by Rekkonnect** [comment]
In 17.9 this appears to be working.
