### ISSUE TITLE
`RemoveUnnecessarySuppressionExclusions` shouldn't have roaming location or should be exposed in UI

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62784]
https://github.com/dotnet/roslyn/blob/5030cd43fa32bd67f4da3dededd205110ad800b4/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CodeStyle/CodeStyleOptions2.cs#L268-L273

The roaming storage doesn't seem useful as this option isn't exposed in Tools → Options.

I think we can keep it *not exposed* in UI and remove the roaming location, keeping only editorconfig location.

@mavasani Any concerns here?

**Comment by mavasani** [comment]
Sounds reasonable to me

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of movement.  If you want to take this on @Youssef1313 go ahead.

**Comment by Youssef1313** [comment]
The class `RoamingProfileStorageLocation` no longer exist actually. I'm not sure how storage is working right now as there have been LOTS of refactorings in the past that I didn't follow closely. I went ahead and closed https://github.com/dotnet/roslyn/pull/62785 as well
