### ISSUE TITLE
API proposal: GeneratorDriver.ReplaceGenerators

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#62796]
## Background and Motivation

The GeneratorDriver has APIs for taking an existing GeneratorDriver and adding additional generators or removing generators, while preserving the existing cached state. There's no API for simply specifying all the generators at once, and there's no way to ask a GeneratorDriver for the underlying generators directly, so if you need to simply say "I need a GeneratorDriver with these generators", and you want to preserve cached generator state, you can't easily do it.

The motivation here was the IDE is adding some changes for Razor caching so we can ensure we reuse GeneratorDrivers from older runs to newer runs. To ensure correctness when we're using the old GeneratorDriver we need to ensure its updated with the correct list of generators if a later one was added/removed since the last Razor activity. Rather than us trying to figure out what to add/remove, its easiest just give the list to the GeneratorDriver, since it already has the data internally.

## Proposed API

Implementation: https://github.com/dotnet/roslyn/pull/62219/files#diff-d19793306af7a0ed1d42db723b6eba037523b35a290799c83402e854d7e5917dR77

```diff
namespace Microsoft.CodeAnalysis
{
     public class GeneratorDriver
     {
+        public GeneratorDriver ReplaceGenerators(ImmutableArray<ISourceGenerator> generators)
     }
```

The name "ReplaceGenerators" was chosen because it matches the Add/Remove/ReplaceAdditionalTexts pattern that already exists on this type.

## Alternative Designs

1. The IDE tracks the generators we've added to the driver ourselves, and then we just call Add/Remove. This seems odd since it's just duplicate work that can only result in extra bugs.
2. We expose the list of generators on the GeneratorDriver, and it's up to the caller to do the diff. We could do this, but adding the API seemed just as easy, and made it consistent with additional texts.

**Comment by 333fred** [comment]
## API Review

Approved as-is.
