### ISSUE TITLE
Can AsyncSemaphore be replaced with SemaphoreSlim now?

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#628]
@jasonmalinowski mentioned to me the other day that we may (now) be able to delete our AsyncSemaphore implementation and replace it with SemaphoreSlim. AsyncSemaphore was added to workaround a bug in SemaphoreSlim in, I think, .Net Framework 4.0. That bug has since been fixed in a later version of the framework. If the Workspaces layer (where AsyncSemaphore is defined) can take a dependency on the new framework version, then we can remove the workaround.

Need to research:
1. What's the minimum framework requirement for the Workspaces layer?
2. In what version of the framework was SemaphoreSlim's bug fixed?

**Comment by pharring** [comment]
Tagging as Performance because, while they've been tuned in the past, AsyncSemaphore allocations are not cheap.

**Comment by jasonmalinowski** [comment]
The bug was fixed in .NET framework 4.5.1. Our current minimum version is 4.5 so it's not a huge jump to accept it.

**Comment by pharring** [comment]
Moving to 4.5.1 would also allow us to eliminate the reflection in TemporaryStorageServiceFactory.MemoryMappedFiles.cs

**Comment by pharring** [comment]
@Pilchie, Can you (or anyone else) think of a good reason NOT to move to 4.5.1 as the minimum target for the Workspaces layer?
Indeed, perhaps it should be 4.5.2 since support for 4.5.1 is [ending mid Jan 2016] (http://blogs.msdn.com/b/dotnet/archive/2014/08/07/moving-to-the-net-framework-4-5-2.aspx)

**Comment by tmat** [comment]
Not just 4.5.2, we should move to 4.6.

**Comment by Pilchie** [comment]
For csc, if we move to CoreCLR, targeting 4.6 definitely makes sense.  For the workspaces layer, if we want to reach maximum penetration, 4.5.2 is a good target since it is on Windows Update, whereas 4.6 won't be for a while.

tag @theoy, since he has done some thinking about this too.

**Comment by pharring** [comment]
Agreed. 4.5.2 for now.

**Comment by jasonmalinowski** [comment]
Agreed -- let's do 4.5.2. I agree we _should_ consider 4.6 (it'd make some stuff I just did easier) but let's not let the mythical future prevent us for doing something we all agree on now.

**Comment by tmat** [comment]
Sounds good. Although it's not that mythical :)

**Comment by jasonmalinowski** [comment]
Until the commit happens that moves us to 4.6, it's mythical!

**Comment by pharring** [comment]
Closed with #1632
