### ISSUE TITLE
Fix all of inline temporary with multiple #region directives duplicates a directive

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#62805]
@333fred gets all the credit for this repro:

1. Paste the following code in:
```
class C
{
    #region outer
    void M(out int a, out int b)
    {
        #region inner
        int c;
        int d;
        M(out c, out d);
        #endregion
    }
    #endregion
}
```
2. Click on the "d" in "int d", and choose inline temporary variable applying to all in document.

**Actual Output:**
Before https://github.com/dotnet/roslyn/pull/62760 is merged, it crashes. Once it's merged, then you get:
```
class C
{
    #region outer
    void M(out int a, out int b)
    {

        #region inner
        #region inner
        M(out int c, out int d);
        #endregion
    }
    #endregion
}
```

Observe the #region inner has been duplicated.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi @mavasani @sharwell Do you think one of you understands well enough how our fix alls handle trivia to take a stab at this? Not that I can't dig into this but it seems it's deep with how SyntaxEditor applies multiple edits at once and I admit I don't know enough of how that works to distinguish a right fix and wrong-but-kinda-works fix here.

**Comment by CyrusNajmabadi** [comment]
Nope.  I would expect fix-all here to effectively be doing two fix-ones.  And i would expect each fix-one to do the right thing with trivia.  So it's less clear to me what's going on and where teh problem is arising from.
