### ISSUE TITLE
Brace matching takes the cursor into insert mode

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6280]
![capture1](https://cloud.githubusercontent.com/assets/9527491/10706036/c088f028-7997-11e5-91e0-ab6a55797b8e.PNG)

After I type the first "(" , it auto completed by putting in the closing round brace but it also puts the cursor in insert mode. So what ever I type now overwrites the closing round brace.

**Comment by ManishJayaswal** [comment]
FYI @Pilchie

**Comment by ManishJayaswal** [comment]
This is on d14rel branch build

**Comment by Pilchie** [comment]
Tagging @olegtk - do you know of any editor changes that might cause this?

**Comment by ManishJayaswal** [comment]
never mind , user error, I did not notice I was in overwrite mode. If you do not have any characters to the right of cursor then the cursor does not indicate that it is in overwrite mode by showing a blinking box instead of a blinking line. @dpoeschl showed me that there is a small text at the bottom right of the VS window that tells me what mode I am in and I was on overwrite mode.
