### ISSUE TITLE
'Change signature' preview reference changes doesn't work

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62825]
Using https://github.com/dotnet/roslyn/commit/deabaa7744075fec2b2688872576561259761552

Go to https://github.com/dotnet/roslyn/blob/deabaa7744075fec2b2688872576561259761552/src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer.cs#L72

Invoke "Change signature" and remove the unused `language` parameter, check the "Preview reference changes" checkbox.

Note that changes are written to disk directly without a preview.

**Comment by sharwell** [comment]
Duplicate of #4608
