### ISSUE TITLE
IDE0075: GetCurrentNode returned null

### ISSUE THREAD

**Issue by corngood** [dotnet/roslyn#62827]
**Version Used**: 

6.3.322007+dc5c84e776364e1c23a5cf2d1a848d4022f8634f

**Steps to Reproduce**:

- [using this source](https://sharplab.io/#v2:CYLg1APgBDUAICYCMBYAULeAGeSAsA3OupnAMzwJQAqApgLYAOAwgPZMCGATrVwDzUAfFBBQAkgFEAjgFcOAGwCWAFwCebTj35CoAb3QBIAzw7BWAO3mr4AVgEAaGo4BGrVvOGKAztLnyoALxQ5jLy8kRoRiZmltZwdtSOiubKwgDmtMoAEhxeABZswLSBwaHhxJEG5DQMLOyM3LwAFPEOTlCu7p4+sgqOrYlQyalQGdm5BaxFAJR6hkbKed4AdN6+CiVrveWVBosrYzn5hcVBhxMnEUYAvhVG1Z3+6/JeTdRQAB6O76qzAYLzAwfQJBEJhKAAMghUGsAVBZUBAH4oMouDJiqJgXDSmEkVAAGYKLwYmEgnHyPGEl4krZ+Mlgim7ZEfZbPV6/ERDHp+JpfGHTCLzarDKAAcUyR0mRTenz+wix8PByJwonOxymp0V/mZy3F43V0tmqolFw1vIFhluaCAA=)
- try to fix IDE0075 with e.g. `dotnet format`

**Expected Behavior**:

Fix will be applied.

**Actual Behavior**:

```
Failed to apply code fix SimplifyConditionalCodeFixProvider for IDE0075: GetCurrentNode returned null with the following node: x == null
                        ? false : y == null
                        ? false : isEqual == null
                        ? x.Equals(y) : isEqual(x, y) - line 281
Failed to apply code fix SimplifyConditionalCodeFixProvider for IDE0075: GetCurrentNode returned null with the following node: x == null
                        ? false : y == null
                        ? false : isEqual == null
                        ? x.Equals(y) : isEqual(x, y) - line 281
Failed to apply code fix SimplifyConditionalCodeFixProvider for IDE0075: GetCurrentNode returned null with the following node: x == null
                        ? false : y == null
                        ? false : isEqual == null
                        ? x.Equals(y) : isEqual(x, y) - line 281
```

**Comment by Youssef1313** [comment]
Using the lambda overload here https://github.com/dotnet/roslyn/blob/8a7b8df1d07784318dc06eb45324970ebb932804/src/Analyzers/Core/CodeFixes/SimplifyBooleanExpression/SimplifyConditionalCodeFixProvider.cs#L70-L71 will likely fix this.

ie,

```csharp
editor.ReplaceNode(expr, (node, _) => /*fully compute replacement here given 'node' (don't use expr for calculating replacement)*/);
```
