### ISSUE TITLE
SourceGenerator How to distinguish SyntaxNode generated by intelliCode 

### ISSUE THREAD

**Issue by 84819760** [dotnet/roslyn#62820]
Intellicode will trigger the generation of a new tree,How to distinguish SyntaxNode generated by intelliCode ？
![QQ截图20220721150742](https://user-images.githubusercontent.com/23549775/180155816-76f12164-bf59-4849-82fa-a9d041ae136d.png)

**Comment by CyrusNajmabadi** [comment]
There is no way to distinguish them.  Intellicode just spits out normal text which becomes a standard part of the roslyn pipeline.  Once emitted there is no way to distinguish it from anything the user may have written themselves.

**Comment by 84819760** [comment]
I found a way to distinguish. I hope there can be an official way。

**Comment by CyrusNajmabadi** [comment]
@84819760 what way did you find?

**Comment by 84819760** [comment]
No method to distinguish syntaxnode was found.
But  found a way to distinguish syntaxtree.

**Comment by 84819760** [comment]
Can only distinguish whether it is generated by intellicode...
···
public void Execute(GeneratorExecutionContext context)
{
   var isPrediction = new StackTrace().GetFrames()
        .Select(sf => sf.GetMethod().DeclaringType)
        .Any(type => type.Name is "SemanticsModelPredictionModifier");
   if(isPrediction) return;
}
···
