### ISSUE TITLE
Emit DynamicallyAccessedMembers for where T : new()

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#62857]
C# is using `Activator.CreateInstance` for `new()` constrainted generics. When `DynamicallyAccessedMembers` is present, roslyn should emit `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]` for such `T`:

```csharp
void M<T>() where T : new() { ... }
```

should be compiled to:

```csharp
void M<
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T
    >() where T : new() { ... }
```

**Comment by huoyaoyuan** [comment]
Wouldn't ILLink and the analyzers recognize the `new()` constraint as a well known pattern?

**Comment by hez2010** [comment]
Yes, I see `new()` is using `Activator.CreateInstance<T>()` overload which has `DynamicallyAccessedMembers` annotated.
