### ISSUE TITLE
Interfaces don't forward static members to other interfaces

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/roslyn#62855]
### Description

Interfaces don't forward static members to other interfaces

for example this doesn't work...
```cs
public interface ICreatable<out T> where T : ICreatable<T>
{
    static abstract T Create();
}
public interface ICreatable<out T, in TArgs> where T : ICreatable<T, TArgs>
{
    static abstract T Create(TArgs args);
}

public interface IWindow : ICreatable<IWindow, WindowArgs>
{ 
    uint Width  { get; }
    uint Height { get; }
    
}
```

It complains when I pass `IWindow` to `ICreatable`

```
The interface 'HazelSharp.Common.Windowing.IWindow' cannot be used as type parameter 'T' in the generic interface 'HazelSharp.Common.Patterns.ICreatable<out T,in TArgs>'. The constraint interface 'HazelSharp.Common.Patterns.ICreatable<HazelSharp.Common.Windowing.IWindow,HazelSharp.Common.Windowing.WindowArgs>' or its base interface has static abstract members.
```

### Reproduction Steps

- Copy the code
- Paste it in your IDE (I'm using rider)
- See error

### Expected behavior

It would forward the static member to the IWindow interface so that any class or struct that eventually implements IWindow has to implement ICreatable too

### Actual behavior

It errors...
```
The interface 'HazelSharp.Common.Windowing.IWindow' cannot be used as type parameter 'T' in the generic interface 'HazelSharp.Common.Patterns.ICreatable<out T,in TArgs>'. The constraint interface 'HazelSharp.Common.Patterns.ICreatable<HazelSharp.Common.Windowing.IWindow,HazelSharp.Common.Windowing.WindowArgs>' or its base interface has static abstract members.
```

### Regression?

Idk

### Known Workarounds

None that I know of.

### Configuration

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>11</LangVersion>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTK" Version="4.7.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Platform" />
    </ItemGroup>

</Project>
```
![image](https://user-images.githubusercontent.com/2453707/180326600-d1174ec4-ada6-4ce9-af1d-6c303f39485d.png)

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue. Unfortunately it's hard to determine exactly what the problem is here because the sample is incomplete. Could you provide a complete sample, including `WindowArgs`, to help us see what the issue is?

**Comment by Shadowblitz16** [comment]
> Thanks for taking the time to file this issue. Unfortunately it's hard to determine exactly what the problem is here because the sample is incomplete. Could you provide a complete sample, including `WindowArgs`, to help us see what the issue is?

 I don't have the project anymore but WindowArgs was just a non generic readonly record struct to pass in the creation args to the IWindow.

**Comment by jaredpar** [comment]
Updating the repro to the following: 

```csharp
public interface ICreatable<out T> where T : ICreatable<T>
{
    static abstract T Create();
}
public interface ICreatable<out T, in TArgs> where T : ICreatable<T, TArgs>
{
    static abstract T Create(TArgs args);
}

public interface IWindow : ICreatable<IWindow, WindowArgs>
{ 
    uint Width  { get; }
    uint Height { get; }
}

public record struct WindowArgs(int i) {}
```

Produces a very different error:

> error CS8920: The interface 'IWindow' cannot be used as type argument. Static member 'ICreatable<IWindow, WindowArgs>.Create(WindowArgs)' does not have a most specific implementation in the interface.

The error difference is likely cause I'm using the C# 11 compiler vs you using the C# 10 compiler. 

At a glance that error seems to make sense in this context but I will let @333fred say for sure.

**Comment by 333fred** [comment]
This error is as-designed. Interfaces with static abstract members cannot be used as type arguments, as that presents a type safety hole that could cause a static member that does not actually exist to be invoked (causing a runtime exception).

**Comment by Shadowblitz16** [comment]
@333fred please reopen this. your failing to understand the issue.
The issue is that unlike instance interface members static interface members don't forward there interface to other interfaces
```cs
public interface A
{
   public void Instance();
   public static abstract void Static();
}

public interface B : A B // implements A so classes that implement B should be requires to implement A also
{
    
}

public class C : B // B should have the interface of A also but static members from A are not carried to B like instance members.
{
    
}
```

**Comment by 333fred** [comment]
@Shadowblitz16 looking at your example I'm not sure what you are saying. Can you show a us an example of where you expect to be able to use `B`? And to make sure, have you seen https://github.com/dotnet/csharplang/issues/5955?

**Comment by Shadowblitz16** [comment]
@333fred sorry I am trying to be a clear as possible forgive my communication issues, I have autism so its hard for me.

basically the way I see static interface members is that they are just like interface members but are static.
I still don't understand the need for the abstract keyword and why normal static members aren't allowed but that's not the issue.

The issue is for example with instance members if B implements A and C implements B since B implements A, C is required to implement A also regardless if B redefineds A's members.

This doesn't seem to be the case with abstract static interface members.
with them it seems to act differently.

**Comment by 333fred** [comment]
@Shadowblitz16 there is no difference there with `static abstract` and regular instance `abstract` members. Both will require that `C` satisfy all interfaces, in this case both `A` and `B`.

**Comment by Shadowblitz16** [comment]
@333fred I just want a static interface where I am not forced to implement it in the next interface or abstract class.

**Comment by CyrusNajmabadi** [comment]
> @333fred I just want a static interface where I am not forced to implement it in the next interface or abstract class.

But then where will the implementation of that interface member be found?

**Comment by 333fred** [comment]
> @333fred I just want a static interface where I am not forced to implement it in the next interface

You are not forced to implement it in the next interface.

> or abstract class.

The feature is not designed to allow this.
