### ISSUE TITLE
Low level struct improvements allow returning references to a current method's stack

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#62850]
**Version Used**: 
```
Microsoft Visual Studio Professional 2022
Version 17.3.0 Preview 3.0
VisualStudio.17.Preview/17.3.0-pre.3.0+32708.82
Microsoft .NET Framework
Version 4.8.04084
```

**Steps to Reproduce**:

Compile and run the following code separated into two projects:

Project 1:
  - Use C# 10:
    ```
    <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>
      <LangVersion>10</LangVersion>
    </PropertyGroup>
    ```
  - Add the following code:
    ```cs
    public class EscapeRulesMixing
    { 
     public static ref int LegacyOutReferenceReturn(out int x)
     {
       x = 42;
       return ref x;
     }
    }
    ```
    
Project 2:
  - Reference Project1, use C# 11:
    ```
    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net6.0</TargetFramework>
      <LangVersion>preview</LangVersion>
    </PropertyGroup>
  
    <ItemGroup>
      <ProjectReference Include="..\Project1\Project1.csproj" />
    </ItemGroup>
    ```
  - Add the following code:
    ```cs
    using System;
    
    class Program
    {
      static void Main()
      {
        ref var r = ref ReferenceOnTheStack(); // get a reference pointing somewhere further on the stack memory
        Usage(ref r); // break things
        Console.ReadKey();
      }
    
      static ref int ReferenceOnTheStack()
      {
        Span<int> s = stackalloc int[100];
        ref var r = ref EscapeRulesMixing.LegacyOutReferenceReturn(out s[50]);
        return ref r; // returns a reference to the current method's stack memory
      }
      
      static void Usage(ref int q)
      {
        q = -1;
        Console.WriteLine(q); // prints '-1'
    
        Span<long> span = stackalloc long[50]; // allocate something on the new stack
    
        Console.WriteLine(q); // prints '0', stackalloc zero-ed the memory
    
        long sum = 0;
        foreach(var x in span)
          sum+=x;
        Console.WriteLine(sum); // prints '0', all elements of stackalloc are zero
    
        q = -1; // here we actually write to the memory allocated by 'stackalloc'
    
        sum = 0;
        foreach(var x in span)
          sum+=x;
        Console.WriteLine(sum); // prints '4294967295', one of the element was set to '0xFFFFFFFF' and reinterpreted as long
      }
    }
    ```
    
**Expected Behavior**:
A compilation error for `return ref r` in `ReferenceOnTheStack`

**Actual Behavior**:
the code prints

```
-1
0
0
4294967295
```

you could break things in a more interesting way if you return an odd element of stackalloc int[] from the first method. E.g. using the 25th element from the span as the `out` argument will print -4294967296 instead.

**Notes**:
Alternatively, you can simply compile the first project and use the compiled dll as a reference for the second project.

AFAIK the problem here is that the compiler uses two different sets of rules to determine which references are safe to return from a method.
- C# 10 projects that don't target a runtime supporting ref fields allow returning references to `out` arguments
- C# 11 projects or projects targeting runtimes that support ref fields assume that `out` arguments are implicitly `scoped` and therefore a method can't return a reference to one of its `out` arguments. Therefore `out` arguments don't contribute to allowed escape scope of a reference returned from a method

As demonstrated above it's possible to create an example that would use both sets of rules by putting parts of the code in different projects (or dlls). The compiler allows returning a reference to an out parameter in the C# 10 project assuming that callers of this code will enforce ref safety at call sites. But the call site is compiled with C# 11 language level which assumes that `out` parameters are implicitly scoped and thus a reference to an out parameter cannot be returned from a method (even though it was and still is legal in C# 10), therefore it doesn't consider the `out` argument as a possible source of the reference returned from the `LegacyOutReferenceReturn`, violating ref safety.

- for referencing code from the same solution it's possible to check whether updated ref escape rules are applied to _declarations_ of the out parameter and consider them unscoped if they are compiled with C# 10 rules
- one way to fix this problem for compiled assemblies, including ones that are produced with older compilers is to explicitly emit `LifetimeAnnotation` attribute encoding the implicit `scoped` modifier for `out` parameters when compiling an assembly using the updated ref escape rules. Therefore, it will be possible to check at call sites whether an `out` parameter was considered `scoped` or not when it was compiled. If it was considered `scoped` there will be an annotation and a reference to this out parameter cannot be returned from a method. If there's no annotation then it was compiled either by an older version of the compiler, or with C# 10 language level, i.e. using "old" ref escape rules and a reference to it could be returned from a method, so arguments passed to such parameters must contribute to allowed escape scope of references returned from an invocation.

**Comment by cston** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63461.

The compiler now reports the following compiling project 2:
> (16,16): error CS8157: Cannot return 'r' by reference because it was initialized to a value that cannot be returned by reference
