### ISSUE TITLE
IDE warning: null possibility after de-nulling in do-while loop

### ISSUE THREAD

**Issue by Yukihana** [dotnet/roslyn#62866]
**Version Used**: .net 6 c#

**Steps to Reproduce**:

```
MyType? myvar = null;
do
{
    if (someothercondition)
        continue;

    myvar = new();
}
while(someCondition);

myvar.DoSomething();
```

**Expected Behavior**:
Since a do-while executes before doing condition check, unlike `for` and `while`, it will execute the code at least once.
Therefore, it should consider that `myvar` is being assigned to, at-least once.

**Actual Behavior**:
myvar `Possible null` warning on the last line of the code, even though there is no `break` in there.

I tried searching for if this was already an issue but I didn't get any relevant hits. I'm not sure if I used the right jargons. This is my first time posting an issue.

**Comment by Youssef1313** [comment]
The warning looks correct to me. Consider the case where the first evaluation of `someothercondition` is `true`, and the first evaluation of `someCondition` is false, the loop will break with a null `myvar`

**Comment by Yukihana** [comment]
> 

I hadn't considered that! Wow what a blunder. Thanks.
