### ISSUE TITLE
VisualStudioWorkspaceDiagnosticAnalyzerProviderService.TryGetRootAndShellFolder is broken

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6286]
[TryGetRootAndShellFolder](http://source.roslyn.io/Microsoft.VisualStudio.LanguageServices/R/a6cb92baaa80a016.html) is doing reflection on the VS Extension manager to find properties "ShellFolder" and "RootFolder" - these properties seem to have been removed from the Extension Manager type and hence this method always returns false. We need to delete/fix this code.

**Comment by heejaechang** [comment]
they added new API that let us do the same thing without using reflection. but we can't move to the new API until our base drop moved to update 1.. that is why we still have that code.

**Comment by heejaechang** [comment]
by the way, it should be well expecting that code to fail and it is under try/catch, so I am not sure why something is failing.

**Comment by mavasani** [comment]
no nothing is failing due to this code, we take the fallback path and it works fine - I just opened this bug to track updating this piece of code. If you already have a tracking item feel free to dupe this one.

**Comment by heejaechang** [comment]
fix checked in
