### ISSUE TITLE
investigate low memory situation a bit more to find out when those situation is happening

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#6288]
we should investigate some context on when that happens.

32bit vs 64bit. how big solution on each context? expensive extension used?

**Comment by davkean** [comment]
Untagging Infrastructure, infrastructure area path is not for something that we ship - assigning to analyzers at the moment because Heejae filed the bug, but's it's unclear as to what the context is of this bug? What is this in relation to?

**Comment by heejaechang** [comment]
I think it is something telemetry and performance v team will take a look. I don't think it belong to any specific team.

**Comment by heejaechang** [comment]
moved to 1.3

**Comment by heejaechang** [comment]
closing this one. devdiv perf team is looking into this.
