### ISSUE TITLE
`AccessibilityModifiersRequired` default might not be respected correctly

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62908]
I didn't try yet to find a repro, logging the issue based on the implementation.

https://github.com/dotnet/roslyn/blob/713c3b83d57f54a058de825cdf4519571eaf00a7/src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.DisposePatternCodeAction.cs#L338

Here, `TryGetEditorConfigOption` doesn't fallback to the option's default value.

https://github.com/dotnet/roslyn/blob/713c3b83d57f54a058de825cdf4519571eaf00a7/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/AnalyzerConfigOptionsExtensions.cs#L61-L62

It's also strange to ask for editorconfig option specifically. While the option isn't exposed in Tools → Options, I still believe we shouldn't ask for editorconfig directly.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
