### ISSUE TITLE
InteractiveSessionTests Are Failing

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#6291]
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference3
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference2

are failing, see http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/130/

introduced with https://github.com/dotnet/roslyn/commit/d2bfd11ddada278f3343d23746b9c3c2f18e3312

**Comment by davkean** [comment]
These were introduced by the auto-integration from stabilization -> master. If these are your only failures, merge your PRs.

**Comment by davkean** [comment]
Can someone from @dotnet/interactive please fix these issues? These are blocking master.

**Comment by davkean** [comment]
@tmat is looking into this

**Comment by tmat** [comment]
Fixed by #6328
