### ISSUE TITLE
OperatorPlacementWhenWrapping should be moved to formatting options

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62936]
The option is currently in code-style options, but it's not really a code-style option.

It should be moved to formatting options, or turned into a code-style option with an analyzer.

@mavasani @CyrusNajmabadi  Let me know if you think there should be an associated analyzer or just be moved to formatting options.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
