### ISSUE TITLE
VS 17.3 Preview 3 Regression from Preview 2 with ref structs

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#62940]
**Version Used**:
VS 2022 17.3 Preview 3

**Steps to Reproduce**:

```cs

public readonly ref struct Ex {
    readonly Exception? _value;
    readonly Func<Exception>? _func;
    readonly Type? _type;

    public string? Message { get; }

    public Ex(in Func<Exception> func) { _func = func; _value = null; Message = null; _type = null; }    

	//CS8347: Cannot use a result of 'Ex.Ex(in Func<Exception>)' in this context because it may expose variables referenced by parameter 'func' outside of their declaration scope
	//CS8156: An expression cannot be used in this context because it may not be passed or returned by reference
	public static Ex Null(string message) => new Ex(() => new NullReferenceException(message));
}

```

**Expected Behavior**: Everything worked fine - compiled without errors or warnings in VS 2022 17.3 Preview 2.

**Actual Behavior**: Does not compile in VS 2022 17.3 Preview 3+

@cston Is there a systematic workaround for all these ref-related issues introduced with VS 2022 17.3 Preview 3 that we can use in the meantime before DotNet 7 RC ships which fully supports proper annotations? Is there a way, perhaps I could use a version of Roslyn from VS 2022 17.3 Preview 2 with the later VS previews, given how the newer versions of Roslyn with _ref-fields_ feature merged-in break things until DotNet 7 RCs?

It seems that many of these ref-returning/escaping issues happen when the parameter is declared `in`. So seemingly Preview 3 changed the rules governing its use slightly.

**Comment by cston** [comment]
@fitdev, thanks for reporting this.

To support `ref` fields (in Visual Studio 17.3 preview 3 when compiling with `-langversion:preview`), escape analysis assumes that a method that returns a `ref struct`, or passes a `ref struct` by `ref`, may capture `ref` or `in` parameters in a `ref` field: see [`ref` arguments and `ref struct` return](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#method-ref-struct-return-escape-analysis-depends-on-ref-escape-of-ref-arguments).

To resolve this, `ref` and `in` parameters that are not captured can be declared as `scoped`.

In the example above, it looks like `func` can be declared as `scoped in Func<Exception>`.

**Comment by jcouv** [comment]
Closing as by-design. Thanks @cston
