### ISSUE TITLE
What are red and green nodes?

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#6296]
I saw a reference to a "red-green" model in https://github.com/KirillOsenkov/XmlParser, and wanted to read up on it, but I couldn't find any obviously-related documentation, not even in `GreenNode.cs`.  I've managed to gather that there are red nodes and green nodes, and it looks like one kind is internal and the other is public, and it looked like there's some hash consing going on, but I'd still like to see a "book of the compiler" on it, or at least a nice big comment reachable from the top of `GreenNode.cs`.

**Comment by Pilchie** [comment]
http://blogs.msdn.com/b/ericlippert/archive/2012/06/08/persistence-facades-and-roslyn-s-red-green-trees.aspx describes it pretty well.

**Comment by SamB** [comment]
Hmm, well, that certainly helps, but it would sure be nice to have something about this in the tree ...

**Comment by SamB** [comment]
Oops, misclicked...

**Comment by ArsenShnurkov** [comment]
please give a link to the latest documentation on them

**Comment by Meir017** [comment]
Is there an updated link for this? The microsoft link is broken and codeplex closed...

**Comment by CyrusNajmabadi** [comment]
See https://stackoverflow.com/questions/10417169/are-roslyn-syntaxnodes-reused/10417510

**Comment by jmarolf** [comment]
Direct link to Eric's blog post: https://blogs.msdn.microsoft.com/ericlippert/2012/06/08/persistence-facades-and-roslyns-red-green-trees/

**Comment by CyrusNajmabadi** [comment]
@jmarolf That's the broken msdn link.

**Comment by jmarolf** [comment]
@CyrusNajmabadi 	it loads for me, does that 404?

**Comment by CyrusNajmabadi** [comment]
Crazy!  I get:

![image](https://user-images.githubusercontent.com/4564579/50193396-3f0e9080-02eb-11e9-80b7-cd7539174d5d.png)

**Comment by jmarolf** [comment]
weird, maybe because I am on the microsoft network?
![image](https://user-images.githubusercontent.com/9797472/50193424-69f8e480-02eb-11e9-8c2b-b9f2532822d2.png)

Anyways, this should probably be ini the docs here anyway

**Comment by VSadov** [comment]
I think @KirillOsenkov moved some of the codeplex stuff about red/green nodes to github.

**Comment by VSadov** [comment]
https://github.com/KirillOsenkov/Bliki/wiki/Roslyn-Immutable-Trees
