### ISSUE TITLE
Pasting in verbatim string doesn't properly escape double quotes

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#62969]
Paste the following in a verbatim string:

```csharp
var lambda = [SuppressMessage("", "CA2013")] () => Object.ReferenceEquals(1, 2);
```

It gets pasted as:

```csharp
var lambda = [SuppressMessage(", ""CA2013"")] () => Object.ReferenceEquals(1, 2);
```

Expected:

```csharp
var lambda = [SuppressMessage("""", ""CA2013"")] () => Object.ReferenceEquals(1, 2);
```

**Comment by CyrusNajmabadi** [comment]
Can you give the full original text you had (That had the verbatim string in it)? And can you meet us know if you were copying from within VS, or from outside of VS?

Thanks!

**Comment by Youssef1313** [comment]
I was copying text from GitHub and pasting in the place of `$$`:

```csharp
            string x = @"using System.Diagnostics.CodeAnalaysis;

$$";
```

**Comment by CyrusNajmabadi** [comment]
thanks!

**Comment by CyrusNajmabadi** [comment]
Fix available.  Testing now.

**Comment by Youssef1313** [comment]
Nice! That's too fast. 
Thanks @CyrusNajmabadi !
