### ISSUE TITLE
Document Outline handle node expand/collapse state across complex edits

### ISSUE THREAD

**Issue by emilyanas2323** [dotnet/roslyn#62979]
At the moment, if the text buffer is updated or if the user performs a sort/search, the document symbol model is regenerated and the expanded/collapsed node states are not preserved (instead all the nodes are expanded). We should be able to keep track of node expand/collapse state across complex edits that change the symbol tree structure.

Text buffer change after collapsing nodes:

https://user-images.githubusercontent.com/32170897/181305507-97aa94de-6dd3-4c2a-bfee-6f1da58ecd00.mp4

Sort after collapsing nodes:

https://user-images.githubusercontent.com/32170897/181305204-9743a7fc-7f84-4b79-bea2-5b308817a288.mp4

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
