### ISSUE TITLE
Document Outline use default search and toolbar

### ISSUE THREAD

**Issue by emilyanas2323** [dotnet/roslyn#62978]
We would like to update the search textbox and the toolbar in the Document Outline UI to use the default search and toolbar to keep the experience consistent with the rest of Visual Studio.

Document Outline toolbar and search box:
![image](https://user-images.githubusercontent.com/32170897/181304182-f91e9ca5-5760-41b7-a9b7-1b45abfcea56.png)

Solution Explorer toolbar and search box:
![image](https://user-images.githubusercontent.com/32170897/181304233-3fdf0f0f-17fc-4761-b9a8-d058dd58ae14.png)

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
