### ISSUE TITLE
Regression in VS 2022 17.3 Preview 3 from Preview 2 when using a ref struct inside of iterator block

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#62973]
**Version Used**: VS 2022 17.3 Preview 3+

**Steps to Reproduce**:

```cs
using System;
using System.Buffers;
using System.Collections.Generic;

public readonly ref struct PooledArrayHandle<T> {

  public T[] Array { get; }
  readonly ArrayPool<T>? _Pool;

  public PooledArrayHandle(int length, ArrayPool<T>? pool = null) {
    _Pool = pool ?? ArrayPool<T>.Shared;
    Array = _Pool.Rent(length);
  }

  public void Dispose() => _Pool?.Return(Array);

}

public static class Test {

    public static PooledArrayHandle<T> RentArray<T>(this int length, out T[] array, ArrayPool<T>? pool = null) {
      var handle = new PooledArrayHandle<T>(length,pool);
      array = handle.Array;
      return handle;
    }

  public static IEnumerable<int> Foo() {
    
    using var handle = RentArray<int>(200, out var array); // <-- CS4013: Instance of type 'PooledArrayHandle<int>' cannot be used inside a nested function, query expression, iterator block or async method
  
    for (int i = 0; i < array.Length; i++) {
      yield return i;
    }
  }

}

```

[sharplab repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuAdAEICuAZgwKYBOKA3EaRbgCxdC3AMxlWzCABMA9jAA2ATzHMGZFAlZ0AxgjIAFadLnNJAQVasICgBIQYk4wB4AKgD4yAbyJEyFUc4BtAF0yc0slDzIAc2YEDjIAXx9lKVlFUIsrAyMXVwB+MgB9bLlBZMxREpMwq1t7YwAKWF1jGCiEAAs4DPCS3IKAB0M5MgBeMhg6OTkASk9k32LhsbIhozI8gpqFPrcqAGUOiHFJQV9fbZWloyoAJWYYBAbW9o6Zs8TvQl8Kij4yAAiUBQQxQzAac1G7mucjyd1idFYMAa23eXySQmIokoADYKNgyM5mOp5pjzn5eHiqmZMjY7A5mLkyPdHttcg1OsCyM0yC9Ot1pHRdIEQsdwt1trt8qtluNJtM5l5vuSyAA3Y5kI71ZgrGDMADu+mG1VpdQZ7L5XTWsw+5LFVhWWoZVG2tvOmAA7Jr6cY3RjytjcHjKMJHM13AAxQwQ0nkhYUcjq1je7UrFkINnhhrYEgkAVCtUa+0Kd5kAD0ZbIjgAtNWyABhfZ8Ei4YQgMgASRg6jsWh10lUCAUAx1AHJqdszU5w6OyFo7DBpLpgDq6GDJNzu1BJDqIBNiQgTGQGHQYDooLJugBHOhsJTMAAeA3EKBQF/g3MPlgQ0mTwDk0haAA1mQv4UAAHGQYCxB00iSMk8YMGBTSPNyKwkPEUBVmQxZUAAMg8ryYQA1MRirxj8uC4BQXpQH6yT+oQCRAA===)

**Expected Behavior**: It should be possible to use a ref struct, as it was possible before, i.e. in VS 2022 `7.3 Preview 2 or earlier.

**Actual Behavior**: CS4013: Instance of type 'PooledArrayHandle<int>' cannot be used inside a nested function, query expression, iterator block or async method

**Comment by jaredpar** [comment]
This is fixed, will add regression test.

**Comment by jaredpar** [comment]
The new behavior, disallowing `PooledArrayHandle<T>` in the iterator, is correct. This is a `ref struct` and as such it cannot appear in an iterator because doing so would be putting a `ref struct` as a field of a `class`. That is a major type and GC safety issue. 

Adding a regression test to verify this is the correct behavior.

**Comment by fitdev** [comment]
But how come it worked in DotNet 6? It was still a ref struct then, so was it a bug in the runtime / compiler at that time which has now been fixed?

**Comment by fitdev** [comment]
Thank you for clarifying this. Pity though that in C# currently there is no safe and allocation-free way of using some "disposable" resource (array from ArrayPool in my example) through the `using` pattern in iterators and async methods.
