### ISSUE TITLE
Remove duplicate code between NavigationBarClient.cs and DocumentOutlineControl.xaml.cs to track text views 

### ISSUE THREAD

**Issue by emilyanas2323** [dotnet/roslyn#62980]
`NavigationBarClient.cs` and `DocumentOutlineControl.xaml.cs` use very similar logic in order to keep track of IVsTextViews. We should refactor out the duplication between the two files.

Navigation bar text view logic:
https://github.com/dotnet/roslyn/blob/69bdfb29ce4d027c5f5bf70f50be9bebcb5df1aa/src/VisualStudio/Core/Def/NavigationBar/NavigationBarClient.cs#L59-L79
https://github.com/dotnet/roslyn/blob/69bdfb29ce4d027c5f5bf70f50be9bebcb5df1aa/src/VisualStudio/Core/Def/NavigationBar/NavigationBarClient.cs#L350-L375

Document Outline text view logic:
https://github.com/dotnet/roslyn/blob/736d6f98ff3b1938a157e923d48bc7ffc7d35a77/src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineControl.xaml.cs#L125-L135
https://github.com/dotnet/roslyn/blob/736d6f98ff3b1938a157e923d48bc7ffc7d35a77/src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineControl.xaml.cs#L166-L203

**Comment by CyrusNajmabadi** [comment]
Closing as speculative.
