### ISSUE TITLE
Why my coding style preferences is not working on visual studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#62985]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Why-my-coding-style-preferences-is-not-w/10103648)._

---
[severity:It bothers me. A fix would be nice]
I like brackets on the same line, but for some reason, visual studio 2022 keeps putting things on different lines, although I specify in the settings. I save everything but nothing happens

---
#### Feedback Bot on 7/25/2022, 05:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of repro.
