### ISSUE TITLE
API Request: SymbolEquivalenceComparer

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#63]
Forking this feature request from #16 

Original post: https://github.com/dotnet/roslyn/issues/16#issuecomment-70846421 by @MrJul

Pertinent APIs: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/SymbolEquivalenceComparer.cs,f93cc1c775e51f8b

I've personally seen different developers _within my own team_ hit upon the snag of not being able to correctly compare ISymbols that originate from different Compilations, and each try to come up with their own solution for it. It would be much better if there was a 'one true way' to do this.

**Comment by mattwar** [comment]
I'm not sure if I'd consider this the one-true-way, but it is at least a way that we are using internally.

**Comment by CyrusNajmabadi** [comment]
A request for this should go through our "api proposal" path.  Note that these APIs are unlikely to be exposed as they are really 'feature-level' apis that encode feature semantics and change as necessary.  As a public API we would be unable to do that as it would likely break people (or every change would need some way to make it opt-in only, which would greatly increase complexity).
