### ISSUE TITLE
Support specifying module context in EE

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/roslyn#63000]
**Steps to Reproduce**:
1. Debug a managed dump file;
2. Switch to a managed frame and evaluate a static variable;
```MyAssembly.MyClass.MyStaticField```

**Expected Behavior**:
✅ ```MyStaticField``` is evaluated.

**Actual Behavior**:
❌ error CS0234: The type or namespace name 'MyClass' does not exist in the namespace 'MyAssembly' (are you missing an assembly reference?)

The problem is that Roslyn EE only looks at transitive closure of references in the current frame. If there are no frames that reference the target assembly, the expression won't be evaluated.

**Proposal**
In Native EE, we support evaluating within a module with the following syntax:
`MyAssembly.dll!MyAssembly.MyClass.MyStaticField`

The idea is that Roslyn EE could support something similar, so static fields could be evaluated within any managed frame.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this issue.
