### ISSUE TITLE
Method Symbol So hard to get arguments

### ISSUE THREAD

**Issue by hxia999** [dotnet/roslyn#63003]
i want to get argument from metho symbol but icant 
some help for me pls

**Comment by CyrusNajmabadi** [comment]
Methods don't have arguments, they have parameters. You can get them with IMethodSymbol.Parameters. If that's not sufficient for what you're trying to do, then we'll need more information on what your problem is to suitably answer it. Thanks!

**Comment by hxia999** [comment]
> Methods don't have arguments, they have parameters. You can get them with IMethodSymbol.Parameters. If that's not sufficient for what you're trying to do, then we'll need more information on what your problem is to suitably answer it. Thanks!

for expleam 
![image](https://user-images.githubusercontent.com/65902824/181662688-de0bf301-a396-45ec-9ee2-d9c5d08fbe74.png)
i want to get <e.DateTime.ToString("yyyy")> <"Year"> in parameters i cant see any about it

**Comment by Youssef1313** [comment]
A method symbol doesn't really have this information. In simple words, an `IMethodSymbol` is the semantics of method declarations, they don't know about the callsites.

Can you clarify more about your context? Are you writing an analyzer, for example?

What do you want to know about `e.DateTime.ToString("yyyy")` and `"Year"`? Just the syntax node?

I think it's hard to help without knowing more about what you want to do.

**Comment by hxia999** [comment]
> A method symbol doesn't really have this information. In simple words, an is the semantics of method declarations, they don't know about the callsites.`IMethodSymbol`
> 
> Can you clarify more about your context? Are you writing an analyzer, for example?
> 
> What do you want to know about and ? Just the syntax node?`e.DateTime.ToString("yyyy")``"Year"`
> 
> I think it's hard to help without knowing more about what you want to do.

i made a  sourceGenerators analyzer expression  for mapper

**Comment by CyrusNajmabadi** [comment]
Closing out aas this is a question, not an issue.
