### ISSUE TITLE
CSharpConvertToAsyncMethodCodeFixProvider crashes in specific case

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/roslyn#6301]
In this code snippet

```` C#
async void SomeMethod()
{
    |  // pointer here
    await ...;
}
````

Types `await` at the pointer position, Visual Studio 2015 will pop up a banner says `'CSharpConvertToAsyncMethodCodeFixProvider' encountered an error and has been disabled.` as the screenshot displays:
![snip_20151025070137](https://cloud.githubusercontent.com/assets/1330321/10713191/44c7e976-7ae6-11e5-98b8-dd9a2357a392.png)

Also tested with my extensions disabled. I'm using Visual Studio 2015 Enterprise RTM.

**Comment by jmarolf** [comment]
Thanks for reporting this! Did some testing on update 1 bits and I believe this PR fixed the issue: https://github.com/dotnet/roslyn/pull/5328
