### ISSUE TITLE
Figure out interaction between design-time and compile-time source generated files in debugging context

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63022]
We need to think about how debugging is gonna interact with GTD. Let's say you GTD on the generated method and the IDE navigates to the design-time impl that just throws. You want to debug through the impl, so you place a breakpoint. Now the breakpoint needs to be mapped to the compile-time impl.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If we need to do something here, can you explain what it is and assign to a milestone?
