### ISSUE TITLE
IDE0065 - using inside vs. outside

### ISSUE THREAD

**Issue by itrashpod** [dotnet/roslyn#63035]
I like putting my usings inside and external usings outside and I know of others who think alike... so why exclusive?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c09643-bb99-b1ad-fd2b-23a724951e7d
* Version Independent ID: 9bcaa508-d3fd-0d9c-dbf8-286e241191fe
* Content: [IDE0065: 'using' directive placement - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0065)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0065.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0065.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CyrusNajmabadi** [comment]
Not sure what this is asking for.  Nothing should be stopping this from being allowed.
