### ISSUE TITLE
Rename doesn't resolve conflicts by value of uncastable lambda

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#6306]
```C#
void X<T>(T t, Func<T, long> e) { X(new { a = 1 }, a => a.a); }
[Obsolete]
void Y<T>(T t, Func<T, int> e) { }
```

Rename `Y` to `X`.

<strike>
**Expected**:
```C#
X(new { a = (long)1 }, a => a.a);
```
</strike>

**Expected**:
```C#
X(new { a = 1 }, a => (long)a.a);
```

**Comment by DustinCampbell** [comment]
This one's tricky. I don't think the expected result is the correct one. The anonymous type actually has a shape where the property 'a' has the type Int32. It's just implicitly converted to Int64 as the result of the lambda. However, if we were to change the shape of the anonymous type by inserting a cast to Int64, that might break anonymous type unification elsewhere.

I think the best conflict resolution would be:

```C#
X(new { a = 1 }, a => (long)a.a);
```

**Comment by SLaks** [comment]
You're right; I don't know why I wrote that.

Changing the anonymous type would definitely be wrong.
