### ISSUE TITLE
Find all references that might change its value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63076]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-all-references-that-might-change-it/10049358)._

---
A variable has an unexpected value and I need to find what changed it.  I often have to do that and "Find all references" is useful, but I would like to be able to refine the search to references where the variable could be changed, such as an assignment, used as a non-const reference in a function call, or a non-const member function call if it is non-trivial.  Even if this was partly available it would help speed up error tracking.

---
#### Feedback Bot on 5/22/2022, 11:39 PM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
I would expect Track Value Source to somewhat solve this but I'm curious if we want to blur the distinction between the two over time.

**Comment by CyrusNajmabadi** [comment]
Find-all-refs already has a `Kind` column that includes if it was read or written to.  e.g.:  

![image](https://user-images.githubusercontent.com/4564579/181847153-8af68d9e-b880-4107-ab27-65966fb7dce0.png)

Closing out with needs-more-info as to why this isn't good for this case.
