### ISSUE TITLE
Move argument name hints to top of argument instance [C#] 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63079]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Move-argument-name-hints-to-top-of-argum/10096903)._

---
Hi my name is Yuriy Temnov, this report is a suggestion of fearure for C# type hints in VS 2022.

As you know in C# type names can be long as like very long in some cases E.g. "SendApplicationNotificationNotificationHandler".
Visual Studio 2022 has a feature that adds hints for argument names and I like it a lot.

But it has some drawbacks:

Problem arises when I need to create instance with many arguments or call some method on smaller screens it takes a lot of space. 
Below i attached my proposal for an option for how this feature can help to trade horizontal space for vertical.

This will allow for more compact code view and less horizonal scrolling. Also this will help to avoid weird and inconsistent formatting of code as workaround.

Example 1:

From:
![image](https://user-images.githubusercontent.com/611219/181845980-63eba7d4-a014-43b2-b1f5-a6e3883c6346.png)

To:
![image](https://user-images.githubusercontent.com/611219/181845997-f2447b4e-07c0-49c0-b89e-936ffdc37ef3.png)

Example 2:

From:
![image](https://user-images.githubusercontent.com/611219/181846006-d2be2970-d05f-40ee-aa47-5a0a066d20f8.png)

To:
![image](https://user-images.githubusercontent.com/611219/181846017-258b8cef-990a-4e8b-9af8-fc9744c12e88.png)

Example 3:

From:
![image](https://user-images.githubusercontent.com/611219/181846027-6db1727f-a407-404b-82f0-3cda91112367.png)

To:
![image](https://user-images.githubusercontent.com/611219/181846039-e34a7001-4a0b-4ba9-a822-bfaf27834acf.png)

I found this feature useful, but at this time I forced to WFH and all I have is my 15.6" laptop. 
I would really appreciate if you could add this feature.

Thank you.



---
#### Feedback Bot on 7/18/2022, 01:22 AM: 

(private comment, text removed)

**Comment by DoctorKrolic** [comment]
Current implementation seems better fore me. It is more logical and looks better. We are in a code editor, not a word document, so making such multi-pseudo-lines is not the thing I would like to see

**Comment by davidwengier** [comment]
There is an extension by @AdmiralSnyder that does inline hints for `var` usage, and places them above the code: https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner

**Comment by CyrusNajmabadi** [comment]
I personally think this is reasonable for users that are ok with veritical space being used over horizontal space (e.g. how CodeLens works).  We can wait to see how much feedback we hear on this though.

**Comment by AdmiralSnyder** [comment]
i'm biased here, but i'd say that letting the user decide where to put hints is a good thing. it's work, though :-)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of  significant feedback around this.
