### ISSUE TITLE
Display inherited comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Display-inherited-comments/10091938)._

---
When a class implements an interface, I would like to see the inherited comment of the member if there is no comment explicitly specified (it could be the same when overriding). For example:

```
public interface IFoo 
{
    /// <summary>
    /// This is value of foo.
    /// </summary>
    public string FooValue { get; }
}

public class Foo : IFoo
{
    public string FooValue { get; }
}
```

When I hover over Foo.FooValue, I will see the "This is value of foo" comment. But if I look at Foo definition, I don't see any comment. It would be great, if it would show the comment at the Foo.FooValue definition - it could be some grayish green, to distinguish it from a regular comment.

---
#### Feedback Bot on 7/11/2022, 07:56 PM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
@sharwell we have inheritdoc have we considered offering this as an option to automatically show inherited comments?

**Comment by CyrusNajmabadi** [comment]
This is how the feature works:

![Image](https://github.com/user-attachments/assets/e97e8b26-73bc-4a8f-9159-43831099b0c3)
