### ISSUE TITLE
[Feature request]auto remove generic correspondent angle brackets

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63080]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-requestauto-remove-generic-cor/10088681)._

---
IDE:Visual Studio 2022 17.3.0 Preview 2.0

I tried to remove 'Task' & '<',
`
new Func<Task<List>>
`

Then it shows a error.
`
new Func<List>> // -->CS1729 error, redundant close angle bracket
`

If Visual Studio can remove '>' automatically, that should be great.
`
new Func<List> // -->Remove correspondent close angle brackets automatically.
`

---
#### Feedback Bot on 7/6/2022, 11:29 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We don't generally add fixers for something that is trivially easy to do jsut by typing a character (like `delete`)
