### ISSUE TITLE
Question: How can I combine multiple IncrementalValuesProvider<T>

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/roslyn#63093]
I have about 4 IncrementalValuesProvider<T>

I'd like to combine them into a object that makes sense, so `IncrementalValuesProvider<MyFourThings>` instead of having to use `result.Left.Right.Right.Left`

Can this be done?

**Comment by CyrusNajmabadi** [comment]
What are the explicit types of your IncrementalValuesProvider?  e.g. what is their `<T>`? If they have hte same `<T>` are you trying to just concatenate them?

**Comment by Sergio0694** [comment]
Possible duplicate of https://github.com/dotnet/roslyn/issues/58127?

**Comment by mrpmorris** [comment]
The types are completely unrelated. 

I want to combine them and project them into an entirely new object.

**Comment by CyrusNajmabadi** [comment]
Could you give ane xample of how you want them combined?  e.g. say you have two values providers.  One provides the ints `1, 2, 3` and the other the bools `true, false`.  What would the final provider provide?

**Comment by mrpmorris** [comment]
(ImmutableArray<bool> b, ImmutableArray<int> i) => new MyClass(b, i)

**Comment by CyrusNajmabadi** [comment]
Oh, i see.  You should call .Collect on both to go from a Values to a Value provider. Then .Combine both to get the tuple. Then do a .Select to make your type out of the tuple.

**Comment by mrpmorris** [comment]
Thank you!

**Comment by mrpmorris** [comment]
Unfortunately, it is not working....

```
// Templates
IncrementalValueProvider<ImmutableArray<TemplateInfo>> templates =
    TemplatesValueProvider.SelectTemplates(context);

// Classes
IncrementalValueProvider<ImmutableArray<ClassInfo?>> classes =
    CodeValueProvider.SelectClasses(context);


IncrementalValueProvider<(ImmutableArray<TemplateInfo> Left, ImmutableArray<ClassInfo?> Right)> combined =
    templates.Combine(classes);

var source = combined
    .Select(x => new CompilationInfo
    {
        Templates = x.Left,
        Classes = x.Right
    });
```

Gives the following error...

![image](https://user-images.githubusercontent.com/3111981/182041095-b4464f62-082f-42c7-982b-cb9e8925d549.png)

**Comment by CyrusNajmabadi** [comment]
Try explicitly providing the type arguments and seeing what goes wrong then.

**Comment by CyrusNajmabadi** [comment]
(I believe Select takes a lambda that has two parameters not one).

**Comment by mrpmorris** [comment]
I have no idea what the types should be

`.Select<IncrementalValueProvider<(ImmutableArray<TemplateInfo> Left, ImmutableArray<ClassInfo?> Right)>, CompilationInfo>`

`.Select<(ImmutableArray<TemplateInfo> Left, ImmutableArray<ClassInfo?> Right), CompilationInfo>`

Neither are accepted.

**Comment by CyrusNajmabadi** [comment]
Your select method needs to take two arguments. One is the data, the other is your cancellation token.

**Comment by mrpmorris** [comment]
@CyrusNajmabadi That is exactly what I was missing, thank you so much!

```
        var source = combined
            .Select((x, _) => new CompilationInfo
            {
                Templates = x.Left,
                Classes = x.Right
            });
```

**Comment by michael-hawker** [comment]
This this is similar to what I was doing with the before/after for RegisterSourceOutput.

I found the whole Left/Right thing very confusing as well, especially when adding new things to the combine list... found a cool trick with tuple deconstruction though:

```cs
var source = providerA
    .Combine(providerB)
    .Combine(providerC);

context.RegisterSourceOutput(source, static (context, data) =>
{
    var ((providerA, providerB), providerC) = data;
```

Then adding is pretty simple as you just prepend another `(` for a new tuple and add `, providerD)` at the end:

```cs
var source = providerA
    .Combine(providerB)
    .Combine(providerC)
    .Combine(providerD);

context.RegisterSourceOutput(source, static (context, data) =>
{
    var (((providerA, providerB), providerC), providerD) = data;
```

Eveything is in the same order and none of this Left.Left.Right stuff to track.
