### ISSUE TITLE
The Kind extension members have no documentation

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#631]
Repro:
- Install the rc1 NuGet packages.
- Goto definition on the `Kind()` extension method.

Result is no documentation present.  This is not a flaw in the documentation uptake as other members like `GetTypeInfo` in the same file have documentation.

This is particularly important because the latest update changed how you determine what keyword a given `SyntaxToken` is.  The `CSharpKind` method was replaced with possibly `Kind` and `CSharpContextualKind` was simply deleted.  

I said possible above because I don't know if `Kind` is the direct equivalent of `CSharpKind` or if it's a combination of `CSharpKind` and `CSharpContextualKind`.  I use the two methods for different purposes and the documentation gives me no hint as to how they function now.  I'm going to have to run some experiments to figure out how they work.

**Comment by ljw1004** [comment]
Please help! I was upgrading my analyzer, discovered that CSharpContextualKind and VBContextualKind no longer exist, discovered that there's a Kind property, didn't find any xml doc-comments for it, didn't find any Internet websites explaining it, and I'm pretty much stuck right now.

**Comment by Evangelink** [comment]
@jaredpar Is this issue still relevant? If so, are you expecting a PR that will provide documentation for each of the enum values of C# and VB.NET `SyntaxKind`?

**Comment by jaredpar** [comment]
It's still relevant just low priority. At the time this issue was filed the code base had done a major refactoring to use the `Kind()` method. The newness of the API and the lack of documentation threw me off a bit. At this point though the API is in heavy use, more well known hence the need for the documentation decreased a bit. Documentation here though would still be welcome.

The expectation was the `Kind` member has documentation attached to it.
