### ISSUE TITLE
C# feature: Add an eval clause to LINQ

### ISSUE THREAD

**Issue by gabrielh** [dotnet/roslyn#6311]
When writing LINQ queries one often wants to evaluate the result immediately (especially in an multithreaded environments) rather than lazily, so quite often one uses a ToList() or a ToArray(): 
```C#
    (from i in numbers
     where i < 0
     select i*2).ToArray();
```
Since this requires the use of brackets around the query, the readability advantages of LINQ are reduced and often people drop LINQ and instead use chained extension methods:
```C#
     numbers.Where(i => i < 0).Select(i => i*2).ToArray();
```
The same happens with all methods that exit the monad, *e.g.* First/Last/Single, Any/All/Contains, Aggregate, Average/Min/Max/Sum, Count, etc. 

So wouldn’t it be nice to support an extra clause in LINQ that would let one apply any of these methods to the query?
```C#
    from i in numbers
    where i < 0
    select i*2
    eval ToArray();
```
I am using the eval keyword here as it does actually result in the evaluation of the query. 

Similarly for queries on Option/Maybe
```C#
    from i in 1.AsOption()
    from j in -2.AsOption()
    select Sqrt(i*j)
    eval Or(0);
```

More details and a demo are available [here](http://softwaretransactions.com/2014/11/05/exiting-the-monad-with-eval-in-linq/)

**Comment by dsaf** [comment]
I see some relation to the forward pipe operator proposal #5445 .

**Comment by JamesTryand** [comment]
I think I've just been sick in my mouth.

**Comment by svick** [comment]
This is a duplicate of #3571 with different name and slightly different syntax.

I think that `eval` is not a great name, because it's also a name of [a well-known function in many other languages](https://en.wikipedia.org/wiki/Eval) which does something completely different.

Also, `eval` may not actually evaluate the sequence, you could write for example `eval AsEnumerable()`.

**Comment by gabrielh** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/3571
