### ISSUE TITLE
"Toggle Line Comment" comments in a way that violates stylecop rules for C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63113]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Toggle-Line-Comment-comments-in-a-way-/10107583)._

---
[severity:It's more difficult to complete my work]
I select some lines of code in a C# file and press Ctrl + / to toggle line comment. 
It comments like this:
            //if (deltaXBetweenActualAndExpected > 0)
            //{
            //    AdjustXGoingBackwards(row, deltaXBetweenActualAndExpected, isForward);
            //    DistributeDeltaXInGutters(row, deltaXBetweenActualAndExpected, isForward);
            //}

Which violates SA1005 where there should be a space between the comment and the code. https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1005.md

This causes grief as now we have to manually fix code commented this way to build the project/solution.

---
#### Feedback Bot on 7/31/2022, 06:45 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
THis is a stylecop issue and should be moved there.  This has been how we have commented since the feature was implemented almost 20 years ago.

**Comment by sharwell** [comment]
The issue here is StyleCop expects commented _code_ to start with `////`, and not just `//` that precedes textual comments. This works for Comment Lines and Uncomment Lines (which can be invoked twice in a row to be compliant with StyleCop), but not with Toggle Line Comment since executing the command twice acts as an undo.

**Comment by CyrusNajmabadi** [comment]
Closing out as external.
