### ISSUE TITLE
Workspace Project: missing `OnCompilationOutputInfoChanged()`

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#63115]
PR https://github.com/dotnet/roslyn/pull/41745 has introduced `CompilationOutputInfo` to Project, and a way to set that via ProjectInfo.

However we have a different family of protected APIs on Workspace On* that allow you to set individual properties from a class derived from Workspace.

For example here's an API to set the OutputFilePath:
https://github.com/dotnet/roslyn/blob/255e967640f66ad8a0861e75e9f8eb154d667060/src/Workspaces/Core/Portable/Workspace/Workspace.cs#L529

When we added CompilationOutputInfo we neglected to add OnCompilationOutputInfoChanged.

It should be something along the lines of:

```
        protected internal void OnCompilationOutputInfoChanged(ProjectId projectId, CompilationOutputInfo compilationOutputInfo)
            => SetCurrentSolution(oldSolution => oldSolution.WithProjectCompilationOutputInfo(projectId, compilationOutputInfo), WorkspaceChangeKind.ProjectChanged, projectId);

```

**Comment by KirillOsenkov** [comment]
To be fair, this family of APIs doesn't seem to be used much, as most hosts prefer to set the ProjectInfo wholesale. However we should consider adding this one for completeness and consistency.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this is needed, this should go through an API request.
