### ISSUE TITLE
Use keyword color for u8 suffix for UTF8 literals

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63139]
## Summary

The new UTF8 literals use the `u8` suffix which is currently in orange, just like the strings. This makes it extremely hard to notice it while glancing over code, as it very easily gets confused with the rest of the literal. Could we use either the keyword color, or at least some color that's not just the same identical orange as the rest of the literal? Keyword color makes sense given it's a special identifier?

![](https://user-images.githubusercontent.com/10199417/182451092-3ce2ba28-f25c-40ea-be14-1eab365ed31c.png)

**Comment by CyrusNajmabadi** [comment]
That def seems reasonable.
