### ISSUE TITLE
Correctness-determinism failure caused by R2R image of Microsoft.CodeAnalysis.InteractiveHost.dll

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#63145]
We saw [determinism failure](https://dev.azure.com/dnceng/public/_build/results?buildId=1901006&view=logs&jobId=057c83a9-93f9-5bce-4899-deb8d06fc190&j=057c83a9-93f9-5bce-4899-deb8d06fc190&t=c5bfdee9-9599-5edf-2f50-077f25ca809b) caused by comparing R2R image of Microsoft.CodeAnalysis.InteractiveHost.dll:

> ["ERROR! InteractiveHost64\Debug\net6.0-windows7.0\win10-x64\R2R\Microsoft.CodeAnalysis.InteractiveHost.dll contents don't match"](https://dev.azure.com/dnceng/public/_build/results?buildId=1901006&view=logs&j=057c83a9-93f9-5bce-4899-deb8d06fc190&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=c5bfdee9-9599-5edf-2f50-077f25ca809b&l=5648)

I only see the failure once so I'm not sure if this is something easily reproducible (and I'm not familiar with what our corretness-determinism CI is doing unfortunately) but the logs and R2R output are still available, and I copied them to
 > \\\\mlangfs1\Public\gel\DeterminismLog\Correctness_Determinism Attempt 1 Logs.zip 

in case the run expires and got deleted.

To build R2R image for this binary, use the follow command
```
dotnet publish "[PathToRoslynRoot]\src\Interactive\HostProcess\InteractiveHost64.csproj" -f net6.0-windows7.0 /p:ContinuousIntegrationBuild=true
```

And you cand find the file at 
```
"[PathToRoslynRoot]\artifacts\bin\InteractiveHost64\Debug\net6.0-windows7.0\win10-x64\publish\Microsoft.CodeAnalysis.InteractiveHost.dll"
```

**Comment by genlu** [comment]
FYi @davidwrighton

**Comment by davidwrighton** [comment]
This issue has been fixed in the runtime. The fix should ship as part of the RC1 release of .NET 7.
