### ISSUE TITLE
[LSP] Semantic classification does not work in the interactive window

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#63148]
main - 17.4p2

1.  Turn on the semantic tokens feature flag (tools ->options -> preview features -> enable c#/vb semantic tokens).
2.  Restart VS
3.  Open interactive window
4.  Type `Console.WriteLine`
5.  Note the missing colorization
![image](https://user-images.githubusercontent.com/5749229/182482731-bcfc03c0-85fb-49b2-b065-2897bdb53757.png)

This does not occur with lsp semantic tokens off

There is a similar issue on diagnostics, but the cause is most likely different as that applies to the diagnostics service only
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1563105

cc @allisonchou

**Comment by allisonchou** [comment]
PR in review: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/418178
