### ISSUE TITLE
Unit testing support for <include> documentation elements

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#6315]
I'm having trouble writing a unit test that includes a documentation comment containing an `<include>` element. I tried using `AddAdditionalDocument` to add the included file to the workspace, and I also tried writing the file to disk. In both cases, the expanded documentation simply included a comment saying the `<include>` element could not be expanded. See sharwell/StyleCopAnalyzers@93749a8 for an example.

:question: Does the `AdhocWorkspace` support resolving `<include>` elements in a documentation comment? If so, where do I place the included file such that it will be located?

:memo: This is part of my work to resolve DotNetAnalyzers/StyleCopAnalyzers#1603.

**Comment by jaredpar** [comment]
CC @jasonmalinowski as he knows `AdhockWorkspace` the best.

**Comment by daveaglick** [comment]
If it helps, I was having this same problem and resolved it by supplying an `XmlReferenceResolver` to the compilation options. Failure to supply one results in the described behavior.

**Comment by jasonmalinowski** [comment]
I believe @daveaglick's advice is correct: the compiler/workspace tries to abstract files, and so unless there's a resolver doing something the compiler just will skip them.

**Comment by sharwell** [comment]
We successfully implemented unit tests for this functionality in DotNetAnalyzers/StyleCopAnalyzers#1898.
