### ISSUE TITLE
`IDE0240` codefix leaves redundunt blank line

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#63163]
**Version Used**:
VS 2022 v17.3 Preview 6

**Steps to Reproduce**:
1) Create new console app, it will contain `<Nullable>enable</Nullable>` in a `.csproj` file by default
2) Add this code to `Program.cs`:
```cs
using System;

#nullable enable

namespace MyNamespace;

class MyClass
{

}
```
3) Invoke codefix of `IDE0240` on `#nullable enable`

**Expected Behavior**:
```cs
using System;

namespace MyNamespace;

class MyClass
{

}
```

**Actual Behavior**:
```cs
using System;


namespace MyNamespace;

class MyClass
{

}
```
_Note that there are 2 blank lines between `using System;` and `
namespace MyNamespace;`_

**Comment by sharwell** [comment]
@sdelarosbil Sure 👍
