### ISSUE TITLE
error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import>declaration is correct, and that the file exists on disk

### ISSUE THREAD

**Issue by coyot** [dotnet/roslyn#6316]
I've cloned the repository to my local machine. I have VS Community 2015 installed and would like to test features implemented for C# 7.0

Unfortunately while restoring the Roslyn.sln (as in the readme site) I am getting such issues:

C:\repos\roslyn\build\Targets\VSL.Imports.targets(54,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import>declaration is correct, and that the file exists on disk. [C:\repos\roslyn\src\Interactive\CsiCore\CsiCore.csproj]

How can I get version 5.0 of the targeted framework if the latest one if the one from 4.6 - what am I missing here? Is there anyone who could help me?

I chacked the .csproj of one of the failing projects and yeah, there is:

< TargetFrameworkVersion>v5.0< /TargetFrameworkVersion>

....

**Comment by diryboy** [comment]
Did you install the [following tools](https://github.com/dotnet/roslyn/wiki/Getting-Started-on-Visual-Studio-2015#step-3)?
Universal Windows App Development Tools -> Tools (1.1.1) and Windows SDK
Windows 8.1 and Windows Phone 8.0/8.1 tools -> Tools and Windows SDKs
Visual Studio Extensibility Tools

**Comment by coyot** [comment]
Does it mean I need at least Windows 8.1 to run it?

**Comment by coyot** [comment]
@diryboy thanks for help - apparently I was missing Tools and SDK. I had to also add FakeSign to the local .nuget directory because it is missing as well..

**Comment by davkean** [comment]
reopening, and turning into a question, so that devs can find it from the list of known issues here: https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging.

**Comment by aadil79** [comment]
I had the same issue.Got pass that.
I was still getting build errors.Apparently, I was also missing the build tool (2015)
http://www.microsoft.com/en-us/download/details.aspx?id=48159
And the NET Framework 4.6 targeting Pack.
http://go.microsoft.com/fwlink/?LinkId=528261
After getting that installed i was able to build it succesfully.

**Comment by davkean** [comment]
@aadil79 Both of those installed always isntalled by Visual Studio 2015. If they are missing, then it sounds like installation did not install correctly. I would repair your installation.

**Comment by aadil79** [comment]
Thanks @davkean.

**Comment by 06needhamt** [comment]
Issue still occurrs for me today when all of the items mentioned above are installed i am updating to VS2015 Update 3 to see if that helps

**Comment by jasonmalinowski** [comment]
@06needhamt Are you still having any issues?

**Comment by 06needhamt** [comment]
No everything is working fine for me now. I must of forgot to report back. Thanks for the help

**Comment by tofutim** [comment]
I installed 2017RC and may have created this issue for myself.

**Comment by jasonmalinowski** [comment]
@tofutim, can you clarify what you mean?

**Comment by tofutim** [comment]
dotnet restore Kumquat.Capture.csproj
```
...\Apps\kumquat\src\Capture\Kumquat.Capture\Kumquat.Capture.csproj(49,3): error MSB4019: The imported project "C:\
Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found.
 Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

I used to be able to 'dotnet restore' but now it seems that I always get this portable error when trying to dotnet restore a netstandard portable library. Perhaps dotnet is only for Core?

**Comment by jasonmalinowski** [comment]
@tofutim Can you open a bug on https://github.com/dotnet/cli? I'm not sure your issue is related to the original issue, or is in the right place here.

**Comment by hemantshelar** [comment]
Hi there,
I have VS Community 2015 Update 3 version installed on my machine and I can still see this error on my development machine?  I am missing anything else?

VS version : VS Community 2015 Update 3
Windows: windows 10

Error: C:\data\GymPortal\GymPortal\src\GymPortal.DataAccess\GymPortal.DataAccess.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\data\GymPortal\GymPortal\src\GymPortal.DataAccess\GymPortal.DataAccess.xproj

**Comment by davkean** [comment]
This above is tracking a different issue. The issue you've got looks like your missing the .NET Core tools for VS2015.

**Comment by tofutim** [comment]
I think I solved this by running 'dotnet restore' as either myself or Admin
or if using something like TeamCity, run it from there.

**Comment by Divi28** [comment]
@coyot  can you tell me what Tools and SDK  you have installed to resolve the issue?

**Comment by SanctiMortem** [comment]
I am experiencing the same error on all of my old project that I try to open with newer version of Unity... The only fix I've found is to re-do the whole project on the new unity version... (not a realistic fix).

I have the 2019.1.6f1 and all projects below 2019 are experiencing the same problem, some of them more issues regarding the same MSbuild but different error.

Please Help, what was the SDK and Tools that fixed the error? is there another fix?

Thank you in advanced

**Comment by jasonmalinowski** [comment]
@SanctiMortem: you may want to file a new issue on https://github.com/dotnet/project-system or on Unity to get better traction. This was a specific bug tracking a specific problem with the Roslyn repo at the time and it's quite likely we were doing not-normal shenanigan's in our build.

**Comment by dnorenavega-EDR** [comment]
I've added to my VS2019 installation, my build version SDK like this and it worked  
Include .Net Framework 4.7.2 sdk
And 4.7.2 targeting pack
C# and Visual Basic Roslyn compilers
