### ISSUE TITLE
GTD fails to navigate to System.Reflection.Metadata.Ecma335 types

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63166]
Version 17.4.0 Preview 2.0 [32731.56.main]

Repro:
Navigate to `System.Reflection.Metadata.Ecma335.EditAndContinueLogEntry` from `CheckEncLogDefinitions` definition in `src\Compilers\CSharp\Test\Emit\Emit\EditAndContinue\EditAndContinueTestBase.cs`

Output:
```
Navigating to symbol 'System.Reflection.Metadata.Ecma335.TableIndex' from 'System.Reflection.Metadata'.
Symbol found in assembly path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.6\ref\net6.0\System.Reflection.Metadata.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.6\System.Reflection.Metadata.dll'
Found PDB on symbol server.
No source document info found in PDB.
```

Is the PDB bad (in which case we need to work with runtime team to fix it) or do we have a bug?

Also, the progress indicator does not indicate failure and it does not disappear:

![image](https://user-images.githubusercontent.com/41759/182659270-5033e962-ea3b-4c82-b370-f19fd33c9012.png)

If there is such failure shouldn't we open metadata view?

**Comment by tmat** [comment]
@davidwengier

**Comment by davidwengier** [comment]
The background work indicator not disappearing issue should be fixed when https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/414278?_a=files makes its way into VS.. hopefully soon, as it's very annoying when pasting.

**Comment by davidwengier** [comment]
This works for me in Version 17.4.0 Preview 2.0 [32803.298.main]

```
Navigating to symbol 'System.Reflection.Metadata.Ecma335.EditAndContinueLogEntry' from 'System.Reflection.Metadata'.
Symbol found in assembly path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.6\ref\net6.0\System.Reflection.Metadata.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.6\System.Reflection.Metadata.dll'
Found PDB on symbol server.
'/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/EditAndContinueLogEntry.cs' found via SourceLink.
```

Looks like the BWI fix has been inserted too.

**Comment by davidwengier** [comment]
oh, just noticed the output in your issue shows you were navigating to `TableIndex`. Was that from a different navigation attempt? That one makes sense to not come from Source Link, as it would need the compiler changes to add type document info presumably.

**Comment by tmat** [comment]
That was different attempt. None of the types worked.

**Comment by tmat** [comment]
Weird, it works now...

**Comment by davidwengier** [comment]
Very strange. My first few attempts didn't work either, because the PDB was slow to download, but the output window did clearly says "Timed out downloading PDB" in those cases. I suspect you wouldn't have that issue in the US anyway :)

**Comment by davidwengier** [comment]
Did you update VS?

I wonder if the BWI issue was just bringing down everything.

**Comment by tmat** [comment]
No, I can still see BWI issue

**Comment by davidwengier** [comment]
Maybe it was just a download timeout?
