### ISSUE TITLE
Possibly infinite loop in DecompilationMetadataAsSourceFileProvider.GetGeneratedFileAsync

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63178]
This loop should have limit on number of attempts:

https://github.com/dotnet/roslyn/blob/7ef824709b724824706adf3bfc2a19723609aa40/src/Features/Core/Portable/MetadataAsSource/DecompilationMetadataAsSourceFileProvider.cs#L125-L140

**Comment by tmat** [comment]
@davidwengier

**Comment by davidwengier** [comment]
The real reason I was employed by Microsoft: To fix issues with code that is 8 years old... https://github.com/dotnet/roslyn/blob/4754991da6685dfe4d7fcb967e8163490d12df8a/src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs#L119-L132

😛

**Comment by CyrusNajmabadi** [comment]
Closing out, existing loop has a timeout and bails out when it can't write the file.
