### ISSUE TITLE
Compiler lacks ways to get to the built-in operator methods it synthesizes from the semantic model

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#63186]
## Background and Motivation

Given code like the following:

```c#
int i, j;
bool x = i == j;
```

If you ask for the semantic info about `==` The compiler will synthesize the following MethodKind.BuiltInOperator:

![image](https://user-images.githubusercontent.com/4564579/182714580-bc628fed-6f36-4ee7-a51a-2523abb8876f.png)

This works great for the IDE *except* for scenarios where we need to involve our out of process server.  To communicate information about symbols, we serialize enough information into a string (We call 'SymbolKey') and then we resolve that on the other end to get back at that symbol.

This works for the vast majority of other symbols by either:

1. Allowing the symbol to be found from a top-down walk of the root `IAssemblySymbol` (used for things like `INamedTypeSymbol`s and members of those named types)
2. Allowing the symbol to be constructed as appropriate from constituent parts.  For example, the `IArraySymbol` for `int[]` can be generated by getting the symbol for `int` and then calling `Compilation.CreateArrayType(intType)`.  This works for generics, tuples, anonymous types, etc. etc.

We even have construction methods to create 'error types' and 'error namespaces' as both can be returned from the compiler, but are not reachable from the root symbol.

However, for these built-ins, there is no suitable mechanism to get back at them.  As such, all IDE features fail over if they need to communicate between OOP and the host.  For example, we cannot do find-references on these symbols.  And if we wanted to push things like 'quick info' over to OOP we would be blocked on these.

We seek an API to allow us to 'rehydrate' these special symbols against a compilation, just like we can with everything else :)

## Proposed API

There are two approaches I can see for allowing this.  One would be to allow a very low level:

```diff
public class Compilation
{
    // for binary operators
+    public IMethodSymbol CreateBuiltInOperator(BinaryOperatorKind kind, ITypeSymbol left, ITypeSymbol right, ITypeSymbol returnType, bool isChecked);
    // for unary operators
+    public IMethodSymbol CreateBuiltInOperator(UnaryOperatorKind kind, ITypeSymbol value, ITypeSymbol returnType, bool isChecked);
}
```

(We can also haggle over the particular shapes there.  For example, instead of `ITypeSymbol left, ITypeSymbol right` it could be `ImmutableArray<ITypeSymbol> parameterTypes`).  This would be low level as it would basically do nothing but just directly instantiate the low level `SynthesizedIntrinsicOperatorSymbol` types that both languages have.  

Pros: would work and is simple/easy.
Cons: would allow doing something like say "I want to create the built-in operator that takes two `IList<string>`s" (which don't actually exist).

With this, the IDE would simply serialize the component bits and a flag saying this is a built-in operator.  On the OOP side we'd just deserialize the parts and then call `compilation.CreateBuiltInOperator(...)` to get back a workable symbol.

---

The alternative is to not make this low level, but effectively give a way on an `INamedTypeSymbol` for either all its `BuiltIn` symbols, or for a particular one.  e.g., something akin to:

```diff
public interface INamedTypeSymbol
{
+    ImmutableArray<IMethodSymbol> GetBuiltInOperators();
}
```

The pros are that this could be setup to only return values for INamedType's that we actually have built-in-operators for.  The cons are that we would now have to be very precise and exact about producing and returning that correct list.

The IDE would then use this by serializing out the info about the containing type (like `int`) and the constituent parts of the operator symbol.  On the OOP side, we'd rehydrate `int` then ask it for its built-in-operators.  We'd then look at each one looking for the one that matched the info we had from the host side.

## Usage Examples

``` C#
// some lines of code here
```

**Comment by 333fred** [comment]
### API Review

The first variant is inline with existing compiler APIs, and is approved. We will investigate throwing for invalid inputs (ie, attempting to create an `IMethodSymbol` for a built-in that does not exist).

```cs
namespace Microsoft.CodeAnalysis;
public class Compilation
{
    // for binary operators
     public IMethodSymbol CreateBuiltInOperator(BinaryOperatorKind kind, ITypeSymbol left, ITypeSymbol right, ITypeSymbol returnType, bool isChecked);
    // for unary operators
     public IMethodSymbol CreateBuiltInOperator(UnaryOperatorKind kind, ITypeSymbol value, ITypeSymbol returnType, bool isChecked);
}
```

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks all and @DustinCampbell and @333fred .  The point about this matching existing APIs is very true.  I will attempt to make a PR for this.  Hopefully it's non-trivial to figure out the list of inputs that this is valid for.  I may need some help with that though.  I'll let you know as i work on the PR!
