### ISSUE TITLE
Renamer.RenameSymbolAsync problem

### ISSUE THREAD

**Issue by AhigaO4** [dotnet/roslyn#63202]
**Version Used**: 

**Steps to Reproduce**:

1. Try to rename class
2. Try to rename Method that accept a varibles of rename class
3. Got InvalidOperationException

**Expected Behavior**:
Renamed Class
Renamed Method

**Actual Behavior**:
Renamed Class
Then trying to rename Method got InvalidOperationException Error

**Comment by CyrusNajmabadi** [comment]
What version of VS?  Can you give a note specific repro?
