### ISSUE TITLE
Update `SymbolDisplay` to include `scoped` for parameters and locals

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#63208]
## Background and Motivation

Include `scoped` modifier for parameter and local types from `SymbolDisplay`.

## Proposed API

For `SymbolDisplayLocalOptions`, the `IncludeRef` option is extended to include `scoped`, and a new `IncludeRefAndScoped` option with the same value is added.

For `SymbolDisplayParameterOptions`, the `IncludeParamsRefOut` option is extended to include `scoped`, and a new `IncludeParamsRefOutScoped` option with the same value is added.

```diff
namespace Microsoft.CodeAnalysis
{
    [Flags]
    public enum SymbolDisplayLocalOptions
    {
        // ...

        /// <summary>
-       /// Includes the <c>ref</c> keyword for ref-locals.
+       /// Includes the <c>ref</c> keyword for ref-locals and the <c>scoped</c> keyword for scoped locals.
        /// Replaced by <see cref="IncludeRefAndScoped"/>.
        /// </summary>
        IncludeRef = 1 << 2,

+       /// <summary>
+       /// Includes the <c>ref</c> keyword for ref-locals and the <c>scoped</c> keyword for scoped locals.
+       /// </summary>
+       IncludeRefAndScoped = 1 << 2,

    }

    [Flags]
    public enum SymbolDisplayParameterOptions
    {
        // ...

        /// <summary>
-       /// Includes the <c>params</c>, <c>ref</c>, <c>in</c>, <c>out</c>, <c>ByRef</c>, <c>ByVal</c> keywords before parameters.
+       /// Includes the <c>params</c>, <c>scoped</c>, <c>ref</c>, <c>in</c>, <c>out</c>, <c>ByRef</c>, <c>ByVal</c> keywords before parameters.
        /// Replaced by <see cref="IncludeParamsRefOutScoped"/>.
        /// </summary>
        IncludeParamsRefOut = 1 << 1,

+       /// <summary>
+       /// Includes the <c>params</c>, <c>scoped</c>, <c>ref</c>, <c>in</c>, <c>out</c>, <c>ByRef</c>, <c>ByVal</c> keywords before parameters.
+       /// </summary>
+       IncludeParamsRefOutScoped = 1 << 1,
    }
}
```

## Usage Examples

``` C#
// some lines of code here
```

## Risks

---
_Separated out from https://github.com/dotnet/roslyn/issues/61647. See https://github.com/dotnet/roslyn/issues/61647#issuecomment-1178239504 that should be addressed._

**Comment by cston** [comment]
The notes [from API review](https://github.com/dotnet/roslyn/issues/61647#issuecomment-1178239504):

> ## API Review
> 
> * Need to update the docs for SymbolDisplayMemberOptions.IncludeRef
> * For locals and parameters, could we hide IncludeRef and add a new IncludeRefAndScoped with the same value?

**Comment by cston** [comment]
Updated the proposed API based on previous [API review discussion](https://github.com/dotnet/roslyn/issues/61647#issuecomment-1178239504).

**Comment by 333fred** [comment]
### API Review

* Like reusing
* Should we just call it `IncludeModifiers`?
    * Yes
* What about implicit cases? `out` is implicitly `scoped` in some cases, for example.
    * Shouldn't include in symbol display if it's not legal.
    * Rather than trying to really determine this, maybe we just say we don't put `scoped` on `out` parameters.
* Can we punt it to 17.5, as we're running up to the deadline for 17.4?
    * Yes, this is fine.

**Conclusion**: Accepted, renaming the options to `IncludeModifiers`.
