### ISSUE TITLE
"Show potential fixes" is recommending a syntax error when doing a null check in VB.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63214]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-potential-fixes-is-recommending-a/10109751)._

---
[severity:It bothers me. A fix would be nice]
```
Dim result = DBFunctions.ExecuteSqlScalar(Of Double?)(sql)
If result Is Nothing Then result = -1
```

`sql` is a SQL string; `result` is a return value of type `Nullable`

There's a hint on `result = -1` that says the code is unnecessary (it isn't, it's setting a value if the variable is null), and Visual Studio tries to "help" by deleting that code, leaving me with a syntax error: a line that says just this: `If result Is Nothing Then`

---
#### Feedback Bot on 8/2/2022, 07:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not planning on investing in these scenarios.
