### ISSUE TITLE
"Enter Outlining mode when opening files" shouldn't apply when peeking definitions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63215]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Enter-Outlining-mode-when-opening-files/10110616)._

---
[severity:It's more difficult to complete my work]
The option "Text Editor > C# > Advanced > Enter outlining mode when files open" is also applied when peeking definitions. 
[Test.zip](https://aka.ms/dc/file?name=B53493541f9f34435a977f13f786ea769637951095137538445_Test.zip&tid=53493541f9f34435a977f13f786ea769637951095137538445)
Using the attached files for example, and with this option enabled, open "Consumer.cs" and peek the definition of the "GetThem" method:
![image](https://user-images.githubusercontent.com/754264/182945226-f7f47adb-0493-4084-9ba4-42d38d94ba25.png)
then the "Class2" return type:
![image](https://user-images.githubusercontent.com/754264/182945252-eb6bec36-d679-4c8e-8b49-76472ab04be2.png)
then the "Class1" property type:
![image](https://user-images.githubusercontent.com/754264/182945274-ff63eeba-4df0-40f2-8dcb-5d5b416a433f.png)
At this point, the peek window is three levels deep. If you then "peek backward" and "peek forward" between the peek definition windows (either with Ctrl+Alt+Minus/Plus or the arrows next to the dots), you'll see that the previously highlighted definitions have been hidden by the file being outlined:
![image](https://user-images.githubusercontent.com/754264/182945305-fe579f87-bb67-46b4-88a2-1bf523f370c6.png)
So if you're multiple levels deep, it becomes impossible to check how you got there, without starting from scratch.

Files opened in the peek window should not have outlining applied to them.

---
#### Feedback Bot on 8/3/2022, 07:34 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this issue.
