### ISSUE TITLE
The Compile ItemGroup intellisense cache is not refreshed when a build finishes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63224]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The-Compile-ItemGroup-intellisense-cache/588021)._

---
The Compile ItemGroup intellisense cache is not refreshed when a build finishes.

Steps to reproduce: 
- Install https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin 
- Create a new project using the **Cross-Platform App (Uno Platform)** app project template
- Close the project (see https://developercommunity.visualstudio.com/content/problem/587976/xaml-intellisense-does-not-start-properly-on-proje.html) 
- Open the MainPage.xaml file in the `MyApp.Shared\MainPage.xaml` 
- Add an `x:Name="myTextBlock"` attribute to the Hello world textblock.
- Build the `MyApp.iOS` project, the build will succeed.
- In the constructor of `MainPage.xaml`, add the following code `myTextBlock.Text = "";` and notice that intellisense does not recognize the new name.

Known workaround:
- Right click on "MainPage.xaml.cs", properties
- Set the `Build action` property to `None`
- Set the `Build action` property to `Compile`

Notice that now, intellisense recognize the `myTextBlock` element.

**Comment by Rytisgit** [comment]
I was affected by this. While trying to fix it I found #44093 and got intellisense to work again by applying the workaround in the issue description

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski please advise if this is us, or external.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response @jasonmalinowski .
