### ISSUE TITLE
Does not support unicode greater than 9999 in a regular expression

### ISSUE THREAD

**Issue by BrandonStudio** [dotnet/roslyn#63228]
**Version Used**: 

**Steps to Reproduce**:

Create a new instance of `System.Text.RegularExpressions.Regex`:
```csharp
new Regex(@"[\x{20000}-\x{2A6DF}]");    // CJK ext-B
```

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAdgKYDumcAdACqsAPAC7cASqwDmAVwA2AQwBOAUQEAHBawDOmgJYB7ZprGTB1KFABEAbQA6AvDAAMzxwF8AtHYcBBAGwARADFXAF0LWgBuRiJXZFcgA===

**Expected Behavior**:
No warning, no error.

**Actual Behavior**:
Warnings on `\x`: RE0001: insufficient hexdemical digits

**Comment by CyrusNajmabadi** [comment]
@stephentoub have been looking in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs and i'm not sure what would allow the above pattern.

It looks like ScanCharClass would fall through to this: 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L685.  But that leads here (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L1695) which only allows two chars for a `\x` escape.

**Comment by CyrusNajmabadi** [comment]
@stephentoub ignore the above.  this properly throws at runtime:

![image](https://user-images.githubusercontent.com/4564579/184702679-cbf68de0-f3ff-4f86-bdae-2c64ae248f4b.png)


System.Text.RegularExpressions.RegexParseException: 'Invalid pattern '[\x{20000}-\x{2A6DF}]' at offset 4. Insufficient hexadecimal digits.'

@BrandonStudio closing out.  This is an invalid regex and the IDE is letting you know that.

**Comment by CyrusNajmabadi** [comment]
Docs also state this: 

https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-escapes-in-regular-expressions

![image](https://user-images.githubusercontent.com/4564579/184702851-a7a73c21-72fa-434f-8e83-619c5ea9900d.png)

**Comment by stephentoub** [comment]
The .NET regex engine operates over System.Chars, which have a range of 0x0 to 0xFFFF.  There is no support for surrogate pairs.
https://github.com/dotnet/runtime/issues/36425

**Comment by CyrusNajmabadi** [comment]
@BrandonStudio It's neither a problem of Roslyn or of .Net.   It's a feature-request :)

A problem would be if the docs stated this was possible, but it didn't work.  Then things would not be working as expected.  Right now, things are working as specified.  It's just that you'd like new things to be supported.  :)   for that, we'll need a feature request (which it sounds like it already exists).  Thanks!

**Comment by CyrusNajmabadi** [comment]
Feel free to continue the discussion there.  Roslyn is just the editor code that gives the warning 'live' that your pattern has a problem.  We follow the rules of .net here, so we'll update our side if they ever support this.
