### ISSUE TITLE
Additional tab white space on XML comment leading trivia if Attribute is added prior

### ISSUE THREAD

**Issue by elachlan** [dotnet/roslyn#63227]
I am currently working on this PR for CsWin32: https://github.com/microsoft/CsWin32/pull/621

We have this code that causes the xml comment to have an extra leading tab white space:
```csharp
typeDeclaration = typeDeclaration
                    .WithLeadingTrivia()
                    .AddAttributeLists(AttributeList().AddAttributes(GeneratedCodeAttribute))
                    .WithLeadingTrivia(typeDeclaration.GetLeadingTrivia());
```

typeDeclaration is MemberDeclarationSyntax.

The generated code attribute is:
```csharp
private static readonly AttributeSyntax GeneratedCodeAttribute = Attribute(IdentifierName("global::System.CodeDom.Compiler.GeneratedCode"))
        .WithArgumentList(FixTrivia(AttributeArgumentList().AddArguments(
            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(ThisAssembly.AssemblyName))),
            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(ThisAssembly.AssemblyInformationalVersion))))));
```

If we do not add the attribute, then the leading trivia xml comment is formatted correctly.

Am I missing something obvious?

**Comment by Youssef1313** [comment]
```
typeDeclaration = typeDeclaration
                    .WithLeadingTrivia()
                    .AddAttributeLists(AttributeList().AddAttributes(GeneratedCodeAttribute))
                    .WithLeadingTrivia(typeDeclaration.GetLeadingTrivia());
```

I'm not seeing this line being hit with `typeDeclaration` corresponding to `PInvoke` in test `TestSimpleMethod`. Can you confirm?

It looks like trivia is messed up at `WhitespaceRewriter`

**Comment by elachlan** [comment]
Thank you for pointing me in the right direction!

**Comment by elachlan** [comment]
@Youssef1313, You can hit via `HasGeneratedCodeAttribute` test. I am fairly sure the issue is in `VisitList`. Though I am unsure how to solve it. It seems like it thinks that the XML comments are related to the attribute and not the class?

**Comment by Youssef1313** [comment]
@elachlan Yeah the doc comment trivia indeed belongs to the attribute.

**Comment by elachlan** [comment]
Should it belong to the class and not the attribute? This issue really only applied to comment trivia on classes with attributes. In `VisitList` we can't really test for that because the parent is null.

**Comment by Youssef1313** [comment]
> Should it belong to the class and not the attribute?

Unfortunately, no. That's how trivia works. They're specifically attached to a token (more specifically, the first token of the method declaration). When there is an attribute, the first token of the method declaration is the `[` (OpenBracketToken).

**Comment by Youssef1313** [comment]
Hope https://github.com/elachlan/CsWin32/pull/1 corrects the implementation :)
