### ISSUE TITLE
FindAllReferences cache does not get cleared when closing/opening a solution

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#63234]
**Version Used**: 
17.4.0 Preview 2.0 [32801.332.main
**Steps to Reproduce**:

1. Have two copies of the same solution. Open one solution in VS.
2. Find all references for some symbol in the solution.
3. Open the other version of the solution.
4. Find all references for the same symbol as in step 2.

**Expected Behavior**:
Only we see the references for the symbol in the second solution.
**Actual Behavior**:
See references for the symbol in both solutions.

The problem may be that FindAllReferences is caching the results from the first solution and not clearing the cache when the solution is closed.

**Comment by vatsalyaagrawal** [comment]
@CyrusNajmabadi FYI

**Comment by CyrusNajmabadi** [comment]
No problem fixing this. But also fairly low pri

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of feedback on this.
