### ISSUE TITLE
Provide easy way to opt out of 'implicit usings'

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#63239]
For users that do not like implicit usings, we should consider an IDE feature to turn them *smartly*.  Specifically, while you can just disable that feature today (either by directly editing the project file, or through project-properties), it could leave your code in a broken state if you had code that depended on those usings.

I recommend adding a lightbulb item and/or an item in this list:

![image](https://user-images.githubusercontent.com/4564579/183146609-bf0e4e23-800f-487f-8c18-7bd345cf2331.png)

The item would offer to disable implicit-usings, giving the user one of two options in terms of how to deal with that:

1. move the implicit-usings to an explicit file (e.g. GlobalUsings.cs), opting to use an existing file named that if it already existed.
2. add the usings as necessary to all files (or files that would break without them).  We could potentially determine which behavior depending on if users have the option to warn/error on using that are unused.  Note: if we only add to files that need it, it will likely be costlier to run.  So that's somethign we'll have to be careful around.

This would allow the project to switch back to explicit-form without breaking anything.

**Comment by EvaldasPovilaitis** [comment]
Just please make an option somewhere to disable implicit usings overall and that would be owesome.

**Comment by CyrusNajmabadi** [comment]
@EvaldasPovilaitis Thanks for that feedback.  My recommendation would be to pass that along to dotnet/runtime.  We're not in control of that experience over here in Roslyn.  We can push user actions into the project system, but we don't have any control over disabling these things altogether or controlling what the defaults are.  Thanks!

**Comment by EvaldasPovilaitis** [comment]
Does this mean I should open an issue on the .NET SDK repo to get this parametrized somewhere?

**Comment by CyrusNajmabadi** [comment]
@EvaldasPovilaitis Yup!  That would definitely be a good idea so that they know you would like this.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Implicit usings are controlled by sdk, and they own exposing options for this.
