### ISSUE TITLE
Why can't use the same name for Nullable Type

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/roslyn#63240]
Seems C# compiler isn't smart enough, there should not be conflict
```C#
namespace Test
{
    internal class Program
    {
        static void Main()
        {
            if (Way is Way.A) // right
            {

            }

            if (Kind is Kind.A) // wrong, must be : if (Kind is Test.Kind.A)
            {

            }
        }

        static Way Way { get; set; }

        static Kind? Kind { get; set; }
    }

    enum Way { A, B, C }

    enum Kind { A, B, C }
}
```

**Comment by CyrusNajmabadi** [comment]
The primary reason for this is that the spec simply doesn't allow for it.  SPecifically, for it to be ok to access a type *and/or* member with a particular name, then the names must match.  e.g. `Way` the type name and `Way` the property name exactly match.  For the `Kind?` version, the type name is `Nullable<Kind>` which doesn't match `Kind`.  

It certainly seems somewhat intuitive that this should work though.  So best would be to look for an existing discussion for this on dotnet/csharplang.  If you can't find one, open a new discussion about the idea.  Thanks!
