### ISSUE TITLE
DiagnosticDescriptor contructor creating instances with emtpy or default properies on coreclr on Linux/Darwin

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/roslyn#6326]
Our code at https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp/RoslynDiagnostics.cs#L7 is returning an instance of `DiagnosticDescriptor` with none of the properties set to what was specified in the constructor.

A simple demonstration:
![image](https://cloud.githubusercontent.com/assets/2030323/10741078/12291776-7be3-11e5-887c-6a5702c87541.png)
Output:
![image](https://cloud.githubusercontent.com/assets/2030323/10741105/3931ceda-7be3-11e5-9575-fd586df12eda.png)

@muratg @pakrym

Note that this only happens on CoreCLR on Linux/Darwin. Mono works fine and CoreCLR on Windows works fine.

**Comment by JunTaoLuo** [comment]
The source for the demo:
```
                Console.WriteLine("adding diagnostic");
//                 var diagnosticVal = RoslynDiagnostics.RealSigningSupportedOnlyOnDesktopClr;
                var diagnosticVal = new DiagnosticDescriptor(
                    id: "DNX1001",
                    title: "title",
                    messageFormat: "message",
                    category: "category",
                    defaultSeverity: DiagnosticSeverity.Warning,
                    isEnabledByDefault: true
                );
                Console.WriteLine(diagnosticVal);
                Console.WriteLine("category: " + diagnosticVal.Category);
                Console.WriteLine("defaultSeverity: " + diagnosticVal.DefaultSeverity);
                Console.WriteLine("description: " + diagnosticVal.Description?.ToString());
                Console.WriteLine("helpLinkUri: " + diagnosticVal.HelpLinkUri);
                Console.WriteLine("id: " + diagnosticVal.Id);
                Console.WriteLine("isEnabledByDefault: " + diagnosticVal.IsEnabledByDefault);
                Console.WriteLine("messageformat: " + diagnosticVal.MessageFormat?.ToString());
                Console.WriteLine("title: " + diagnosticVal.Title?.ToString());
```

**Comment by JunTaoLuo** [comment]
Version tested was 1.1.0-rc1 restored from the feed dotnet-core myget feed

**Comment by pakrym** [comment]
This looks to be coreclr problem on linux\darwin, reproduces on latest coreclr build (23426) but not on the previous one (23420)

**Comment by JunTaoLuo** [comment]
tracking in https://github.com/dotnet/coreclr/issues/1871
