### ISSUE TITLE
Inconsistency in allowed and forbidden operations using tuple syntax when System.ValueTuple is not defined

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#63278]
**Version Used**: VS 17.3 -- 4.3.0-3.22401.3 (41ae7738)

**Steps to Reproduce**:

1. Create a C# project targeting `net462`, or any target framework that doesn't contain `System.ValueTuple<>`.
2. Add the following source code file:
```c#
public class C
{
    private readonly int _a, _b;

    // Uses tuple syntax, IL doesn't reference System.ValueTuple`2, but is not permitted.
    // CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
    public C(int a, int b) => (_a, _b) = (a, b);

    public void Deconstruct(out int a, out int b)
    {
        a = _a;
        b = _b;
    }

    public void M()
    {
        // Uses tuple syntax, IL doesn't reference System.ValueTuple`2, and is permitted.
        var (a, b) = this;
    }
}
```

**Expected Behavior**:
Both usages are permitted as they don't result in references to `System.ValueTuple`2` being emitted in IL (see [SharpLab](https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiAlgGwD4AEDMACLAJjwGEBYAKAG9K868AHAJxQDcBDKCPJidgEwD2YNAE88KMFDwB9dglnAA3JVr1cpABSTp8iVLzAAlHgC8APjya5CmcbNW9xlRTV0NWACx4AIhADGwgDOUEwArv5QmoJh0jp4ejFxBsZueDQU9FkJDnIu2fTAucppAL6qmer4XngAsppGaRkFdBxMjgr2pnhQABYoQfn05RQjQA===)).

**Actual Behavior**:
The assignment via tuple in the constructor results in an error, while the deconstruction assignment is allowed.

**Comment by jaredpar** [comment]
This behavior is "By Design". There are a few specific cases where we allow deconstruction or tuple syntax even without a valid `Tuple<>` type. These are very limited cases though. It is not necessarily related to whether we do or do not end up emitting the tuple type into metadata.
