### ISSUE TITLE
Generate new type dialog from struct interface list as generic type parameter only allows generating interfaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63280]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generate-new-type-dialog-from-struct-int/10113798)._

---
Consider the following C# code:

``` cs
using System.Collections.Generic;
namespace Test
{
    public readonly struct ExampleCollection : IEnumerable
    {
    }
}
```
Provided that the type `Example` does not exist, if one now moves the cursor to `Example` and invokes Quick Actions, there are three options for fixing it:

1. Generate class 'Example' in new file
1. Generate class 'Example'
1. Generate new type...

The first two options would create a code snippet of `public class Example`. Selecting the third option should allow generating other kinds of types. However, in this particular case, the only kind available within that dialog box is `interface`. It does not allow creating a `class`, `struct`, or `enum` contrary to user expectation.

**Expected behavior**: I can choose to create `Example` as a `class`, `struct`, `enum`, or `interface`.

**Actual behavior**: I can only choose to create `Example` as an `interface`.

---
#### Feedback Bot on 8/8/2022, 07:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gjaw** [comment]
Seems like the bot moving the bug over here broke the original code sample, missing the generics from `IEnumerable`. The code should be
``` cs
using System.Collections.Generic;
namespace Test
{
    public readonly struct ExampleCollection : IEnumerable<Example>
    {
    }
}
```

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/35e54c1b711eb741eb4d4cc1b133e09d79e17e7d/src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs#L671-L675

This code looks suspicious.
