### ISSUE TITLE
DocumentEditor.AddAttribute() ignores generic parameters

### ISSUE THREAD

**Issue by iserrato** [dotnet/roslyn#63281]
**Version Used**: 4.3.0-2.22302.14

**Expected Behavior**:
[DocumentEditor.AddAttribute(node, attribute)](https://sourceroslyn.io/Microsoft.CodeAnalysis.Workspaces/R/2f8384b30abf10eb.html) adds the specified attribute to a generic type parameter.

**Actual Behavior**:
No attribute is added

**Likely area of fix**:
[In SyntaxNodeExtensions.cs](https://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/J/s/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxNodeExtensions.cs/SyntaxNodeExtensions.cs,c2127bd6c9b2f8b7), GetAttributeLists() does not check for TypeParameterSyntax.

**Current workaround**:
Replacing the node with a new node that has the attributes added.
```
var newNode = (TypeParameterSyntax) node;
var nodeWithAttribute = newNode.AddAttributeLists ((AttributeListSyntax) attribute);
(DocumentEditor)editor.ReplaceNode (node, nodeWithAttribute);
```

**Comment by CyrusNajmabadi** [comment]
@iserrato we would definitely take a contribution here if you're interested!

**Comment by iserrato** [comment]
@CyrusNajmabadi Sure thing! This seemed like a more involved change than the previous one I made, but I think I got it figured out

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/63292
