### ISSUE TITLE
Constructors mentioned in crefs are classified like types

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#633]
Ported from TFS WorkItem: **840118**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Copy/paste to a C# file:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: gray">///</SPAN> <SPAN style="COLOR: gray">&lt;</SPAN><SPAN style="COLOR: gray">summary</SPAN><SPAN style="COLOR: gray">&gt;</SPAN>
<SPAN style="COLOR: gray">///</SPAN><SPAN style="COLOR: green"> To create an instance of MyClass, call </SPAN><SPAN style="COLOR: gray">&lt;</SPAN><SPAN style="COLOR: gray">see</SPAN> <SPAN style="COLOR: gray">cref</SPAN><SPAN style="COLOR: gray">=</SPAN><SPAN style="COLOR: gray">"</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN><SPAN style="COLOR: gray">"</SPAN><SPAN style="COLOR: gray">/&gt;</SPAN>
<SPAN style="COLOR: gray">///</SPAN> <SPAN style="COLOR: gray">&lt;/</SPAN><SPAN style="COLOR: gray">summary</SPAN><SPAN style="COLOR: gray">&gt;</SPAN>
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">MyClass</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: black">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN> <SPAN style="COLOR: black">{</SPAN> <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

&nbsp;

**Expected: **The cref to be colored like this: <SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af"><SPAN style="COLOR: black">MyClass</SPAN></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN>

**Actual: **The cref is actally colored like this: <SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN>

------------------------------

**Revisions:**

1) Created By David Poeschl (12/9/2013 4:08:55 PM)

------------------------------

**Comment by davkean** [comment]
Here's an image to better clarify this as the port lost it:

![image](https://cloud.githubusercontent.com/assets/1103906/11230644/4b88eb26-8d55-11e5-9535-4baf6471b7f3.png)
