### ISSUE TITLE
TargetFramework net6.0 and LangVersion default shouled be C# 10

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#63303]
**Version Used**: 

.NET SDK 7.0.100-preview.7.22377.5
Visual Studio Version 17.4.0 Preview 1.0

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/3760955/183816719-e7de8025-4386-4431-8ea3-69e9769e876f.png)

![image](https://user-images.githubusercontent.com/3760955/183816882-fa41a9d9-f2b2-4909-a5ee-fc1b46c7d093.png)

**Expected Behavior**:

For .NET 6, LangVersion default should be C# 10.

**Actual Behavior**:

11.

**Comment by Youssef1313** [comment]
If you have an explicit `<LangVersion>default</LangVersion>`, it's the same as "latest".

https://github.com/dotnet/roslyn/blob/c18a66e5912ba8ad6183eed6d2496ae8221a52d0/src/Compilers/CSharp/Portable/CSharpResources.resx#L4724-L4729

If you don't specify a LangVersion at all, then the value will depend on the target framework per this logic:

https://github.com/dotnet/roslyn/blob/c18a66e5912ba8ad6183eed6d2496ae8221a52d0/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L30

**Comment by ufcpp** [comment]
Should the behavior be the same between `<LangVersion>default</LangVersion>` and no `LangVersion` tag?
IIRC, default behavior was changed in .NET Core 3.0. The document must be changed.

**Comment by ufcpp** [comment]
If this is by-design, how can I change LangVersion to target-spesific (10 for net6.0, 11 for net7.0, etc.)?
If I have `<LangVersion>latest</LangVersion>` tag in Directory.build.props and I want a csproj to be target-spesific version, is it possible?

**Comment by Youssef1313** [comment]
I'm not sure if that works, but try an empty value like this `<LangVersion></LangVersion>`

**Comment by ufcpp** [comment]
Oh, empty `<LangVersion></LangVersion>` just works...

**Comment by jaredpar** [comment]
> Should the behavior be the same between <LangVersion>default</LangVersion> and no LangVersion tag?

No. The logic in the MSBuild targets is effectively that if `$(LangVersion)` is not set then it will be derived from the current `$(TargetFramework)`. If it's set though, even to default, then we take the value that the user provided. This is a standard approach for most MSBuild properties. 

> Oh, empty <LangVersion></LangVersion> just works...

Yes this will work because it effectively unsets the value.
