### ISSUE TITLE
[Flaky Test] Microsoft.DiaSymReader.PortablePdb.UnitTests are failing

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#6331]
Jenkins doesn't provide any details on this. Please refer to 
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/502/

This is found from PR https://github.com/dotnet/roslyn/pull/6289 

@dotnet/roslyn-infrastructure

**Comment by genlu** [comment]
@tannergooding @davkean I'd like to get more detail about the failure. How can I get the test log from the server?

**Comment by davkean** [comment]
@tmat These tests have failed a few times over the past week - we don't know why its crashing yet, as we no useful logging from TestRun.

**Comment by davkean** [comment]
I'm working on a repro for this exact issue at the moment on my Azure VM.

**Comment by ManishJayaswal** [comment]
@davkean is this still failing? I think @tmat fixed this in #6328

**Comment by davkean** [comment]
Not sure he did - this error is not a test failing. This error is the entire assembly failing to run, either due to a xunit crash or something else.

**Comment by davkean** [comment]
What he fixed what the scripting test failures, seen here: https://github.com/dotnet/roslyn/issues/6291.

**Comment by ManishJayaswal** [comment]
@tmat can you please take a look - we are on a crusade to root out flaky tests :-)

**Comment by davkean** [comment]
I'm having a lot of trouble repro'ing this in isolation - I keep running into https://github.com/dotnet/roslyn/issues/6358 which is blocking my repros. Going to try and fix this tomorrow.

**Comment by tmat** [comment]
Has this been seen again recently? I have added logging to xunit runner which should shed some light on why this happens.

**Comment by davkean** [comment]
We've not see it recently. I'll close this and reopen if we see it again.
