### ISSUE TITLE
Last 13 characters of error output in 'C# Interactive' window are not colored red

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#63317]
**Version Used**: VS 17.3 (Roslyn 4.3.0.3-22401.3)

**Steps to Reproduce**:

1. Open the "C# Interactive" window in VS.
2. Submit any statement that results in error diagnostics.

**Expected Behavior**: All error diagnostics are colored correctly (red).

**Actual Behavior**: The last 13 characters are colored black, while the rest is colored correctly.

![image](https://user-images.githubusercontent.com/823398/184029865-359baf97-cbd2-481f-a128-cb596c00e0bd.png)

This does not affect `csi` in the console, which is always colored correctly.

![image](https://user-images.githubusercontent.com/823398/184030318-abdc54f9-6285-4a1c-ac75-3f20a63dd425.png)

**Comment by dibarbet** [comment]
@tmat should this be transferred to https://github.com/dotnet/interactive-window ?  I don't think we color the text here

**Comment by tmat** [comment]
Moved to  https://github.com/dotnet/interactive-window
