### ISSUE TITLE
Enable incremental member edit analysis by default

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#63324]
Currently this incremental analysis is guarded by a feature flag, which is off by default: https://github.com/dotnet/roslyn/blob/d7be4604edb3727a22530d2062a3d5931b475280/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs#L295

Once LSP diagnostics has been baked and enabled by default, we should turn on this feature flag and eventually remove it.

**Comment by dibarbet** [comment]
Analysis is now gated by the LSP feature flag itself, so will be enabled by default when LSP pull diagnostics is on by default
https://github.com/dotnet/roslyn/pull/65468
