### ISSUE TITLE
IntelliSense shows wrong type for multi-targeted fields with #ifdefs

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63331]
**Version Used**: VS 17.2.6 (also repros on sharplab main)

**Steps to Reproduce**:

1. Create a new class library
2. Add the following to the .csproj:

```xml
<PropertyGroup>
  <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  <LangVersion>10.0</LangVersion>
</PropertyGroup>
```

3. Paste the following code:

```csharp
unsafe
{
    D2D1_PROPERTY_BINDING d2D1PropertyBinding;

    d2D1PropertyBinding.getFunction = null;
}

unsafe struct D2D1_PROPERTY_BINDING
{
#if NET6_0_OR_GREATER
    public delegate* unmanaged<void*, byte*, uint, uint*, int> getFunction;
#else
    public void* getFunction;
#endif
}
```

4. Set the .NET 6 target from VS's drop down
5. Hover on `d2D1PropertyBinding.getFunction` to show the tooltip
6. Observe the tooltip shows `void*` and not `delegate* unmanaged<void*, byte*, uint, uint*, int>`

Sharplab repro: [here](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRgJYBsKpgTwAcUAfOAO2SkgFgAoAb3oAJXmARAJnYEYB9AAoAlAPICAokIAqATT4AhAJIA5dioDizACbceAhAHtiCAvIzkt5gOYBueizY7e+oxBP4zF6wDorEGAACAKwwGAbkzAC8zORwWFh2dAC+9nQUVJDMyDAIcADGMBy6gqIS0nJKqhr0THRszAEAzMxwyAAWBiYAVMyEhsYEylAAthCJ9ADEGGDMyuJSAGx8AAx8IkJ86kLiAIJSkg6sTdoQOFawED0Uw1DkUH5aADwBACxdADTMwPgwl59w5hgn0BAD4sv5gqFwokJqdkBBDg1mq8evDAiEwuQYRAvGBUlMZnNFis1hstrt9kJEcctKcIOdfldyDc7g9nm9Pt9Gf9ATzyDAPsxQcw/OioVjJnCEXU2McUSKIRjoZLcfQkkA===).

**Expected Behavior**:

The tooltip should show the type for the currently selected target from VS (ie. reflect the actual type of the field).

**Actual Behavior**:

The tooltip always shows `void*` no matter which target is selected.

![image](https://user-images.githubusercontent.com/10199417/184133387-2d449762-824e-40f1-b370-ecdf18af9d83.png)

**Comment by Youssef1313** [comment]
I investigated this. It turns out we're missing a `VisitFunctionPointerType` override in `ErrorVisitor`:

https://github.com/dotnet/roslyn/blob/afef8332b40c289ff99140adff92aa2d07776053/src/Features/Core/Portable/QuickInfo/CommonSemanticQuickInfoProvider.ErrorVisitor.cs#L13

Not sure if there are other overrides we might be missing as well.

**Comment by Youssef1313** [comment]
Also missing an override for type parameters:

![image](https://user-images.githubusercontent.com/31348972/184147245-08fe360a-69ba-45a2-9299-1346aba0b7d8.png)

**Comment by CyrusNajmabadi** [comment]
DefaultVisit should likely be asserting and also returning false.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I actually wonder why do we care whether a symbol has an error? Shouldn't we still show whatever symbol we have in quick info?

**Comment by CyrusNajmabadi** [comment]
THe code looks appropriate.  It's basically saying: if there's a problem under the current project-flavor, see if there's another flavor that doesn't have a problem and show that instead.  Seems fine to me.  But we shouldn't default to "i don't know" meaning "tehre is an error".  We should default it to meaning "there is no error" and we should assert so someone adds the right code to make that scenario work IMO.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this area.
