### ISSUE TITLE
Building Corelib in runtime triggers several asserts

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#63348]
Steps: 

1. Enlist in github.com/dotnet/runtime
2. sync to 57e8776ac5cf5586f5199f0a65329d8a81827cf6
3. Move to `src\libraries\System.Private.Xml\src`
4. Build with a debug version of csc. 

The following two asserts will be hit: 

https://github.com/dotnet/roslyn/blob/6a9e93ce60d7ef7f0f95030372ed512b0d6fd5ce/src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs#L94-L100

https://github.com/dotnet/roslyn/blob/6a9e93ce60d7ef7f0f95030372ed512b0d6fd5ce/src/Compilers/CSharp/Portable/CodeGen/EmitConversion.cs#L156-L159

**Comment by jaredpar** [comment]
Trying to decide if this is something we need to look at now because it's potentially serious or something we can tackle during technical debt time. 

@333fred can you give me a read on the first one
@cston can you give me a read on the second one

**Comment by 333fred** [comment]
1st seems to be related to attributes, it's firing on a noneoperation at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs#L9790. Shouldn't cause immediate issues.

**Comment by 333fred** [comment]
Looking at the stack, an ILLink analyzer is asking for the CFG of an attribute. We weren't expecting that today, but it will be fixed by https://github.com/dotnet/roslyn/pull/59369.

**Comment by cston** [comment]
For the assert failure in EmitConversion.cs, a simple repro is to compile the following with the `RuntimeFeature.NumericIntPtr` feature:
```csharp
using System;
class Program
{
    static void M(int n)
    {
        Span<char> s = n < 10 ? stackalloc char[n] : new char[n];
    }
}
```

**Comment by jaredpar** [comment]
Closing as both issues were addressed

**Comment by jcouv** [comment]
Re-opening. I've done a build of the `runtime` repo with debug compiler bits yesterday and hit those same two assertions. This was using latest compiler and `runtime` repo from `main`.

**Comment by 333fred** [comment]
We had to revert the IAttributeOperation PR for now. We'll get it back in at some point.

**Comment by jaredpar** [comment]
@333fred now that the `IAttributeOperation` PR was re-merged what else is left here?

**Comment by 333fred** [comment]
I don't believe anything. Closing out.
