### ISSUE TITLE
'Generate class' and 'Generate type' should handle records properly

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63376]
![image](https://user-images.githubusercontent.com/31348972/184471564-71783b2b-cedc-4405-b68c-4b41dab8ae45.png)

![image](https://user-images.githubusercontent.com/31348972/184471572-6042219c-a265-4fcb-80d2-91da9ee0f1b6.png)

In both cases, a record should be offered instead of a class.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback here
