### ISSUE TITLE
IDE0230 (Convert to UTF-8 string literal) doesn't work

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63380]
I'm on 17.3 P2

csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>exe</OutputType>
      <TargetFrameworks>net6.0</TargetFrameworks>
      <LangVersion>Preview</LangVersion>
      <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
```

editorconfig:

```ini
[*]
csharp_style_prefer_utf8_string_literals = true:error
dotnet_diagnostic.IDE0230.severity = error
```

![image](https://user-images.githubusercontent.com/31348972/184480632-664dcf59-6731-4dc8-96c6-6ad5a057d053.png)

In solution explorer, the analyzer shows with error icon, meaning the analyzer is recognized and editorconfig is read correctly.

This is strange, the test case is a copy of an existing passing test.

cc @davidwengier

**Comment by davidwengier** [comment]
I don't repro this, though admittedly on a later version of VS. Given that the tests pass I wonder if this is an issue with diagnostic reporting, rather than that individual anaylzer.

**Comment by Youssef1313** [comment]
@davidwengier The error doesn't show in command-line builds as well for me.

**Comment by davidwengier** [comment]
hmmmm... I didn't try command line, but it was shown in the output window.

**Comment by Youssef1313** [comment]
Output window should be the same as command-line output. Let me see if updating the SDK fixes it for me.

**Comment by Youssef1313** [comment]
@davidwengier Here is a repro: https://github.com/Youssef1313/TestIDE0230

I setup GitHub Actions on the repo and it's passing. Hope that makes it easier to investigate further.

**Comment by Youssef1313** [comment]
I'm missing LangVersion in the latest GitHub repro. It works now on GitHub Actions. I'll re-validate locally.

**Comment by Youssef1313** [comment]
The issue reproduces on Preview 5 but works on Preview 6 and Preview 7. Closing as already fixed.

**Comment by Youssef1313** [comment]
Thanks for taking a look @davidwengier.

My bad I wasn't on a newer preview.

**Comment by davidwengier** [comment]
Thank you for your thoroughness @Youssef1313 :)
