### ISSUE TITLE
`args` not offered in top-level statements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63393]
Try to type `args` in top-level program. Completion doesn't show it.

```csharp
using System;

var x = "";
ar$$
```

It can show up correctly on other contexts like `_ = ar$$`

**Comment by DoctorKrolic** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/55969

**Comment by Youssef1313** [comment]
Thanks @DoctorKrolic 
Closing out as a duplicate.
