### ISSUE TITLE
Error list is stuck

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63394]
Steps I performed:

1. Activated the option added in https://github.com/dotnet/roslyn/pull/53053
2. Had to do multiple builds with code and editorconfig changes in between
3. Luckily, I was able to reproduce. There is no consistent repro. I was just hitting a high repro rate :)
4. Here is the log file found in `C:\Users\PC\AppData\Local\Temp\Roslyn\Telemetry`

[08_14_2022_11_44_58.log](https://github.com/dotnet/roslyn/files/9333183/08_14_2022_11_44_58.log)

The missing error is `CA1826`. In the last build I performed, it showed in command-line output but not in the IDE at all.

In some builds code was `_ = ((IReadOnlyList<string>)args).First();` and in others it was `_ = ((IReadOnlyList<string>)args)?.First();`. Both should have CA1826 diagnostic but I had to change code from one form to the other between some builds to get a repro.
I was also changing `dotnet_diagnostic.CA1826.severity = none` to `dotnet_diagnostic.CA1826.severity = error` from a build to another to be able to repro.
At some point, I'm setting it as error but error list just got stuck.

Tagging @mavasani since you worked on #53053. I hope there is enough info to investigate

**Comment by mavasani** [comment]
@Youssef1313 Can you please try this scenario after https://github.com/dotnet/roslyn/pull/63665 is merged? Alternatively, you can locally build the bits with this change and try the scenario in RoslynDev hive. Thanks!

**Comment by mavasani** [comment]
Closing this issue as underlying race condition for analyzer callbacks into top level code has been fixed. Kindly reopen if you still see this issue.
