### ISSUE TITLE
SourceGenerator is too slow

### ISSUE THREAD

**Issue by 84819760** [dotnet/roslyn#63397]
It is impractical to run  Execute method at each keystroke and maintain an acceptable level of performance in the IDE. Can you provide an independent Addsource (string hintname, string source) method?After completing the time-consuming operation, asynchronous call the addsource method.

**Comment by CyrusNajmabadi** [comment]
Asynchronously won't help here.  THe information is still needed by every service that needs compilation information.  This will just add an unbounded asynchronous delay to taht work.

**Comment by 84819760** [comment]
@CyrusNajmabadi 

It is difficult to minimize updates. There are always times when the processing capacity is exceeded, such as copying and pasting a large piece of code. In fact, it is only necessary to ensure that the last change is processed (except in the compilation stage).


What is needed at present is to process only the last change and discard the nodes generated in the process.

For example, the "Execute()" method overwrites the last updated node with "Last Syntaxnodes", then creates a task to generate code, and discards the Syntaxnodes generated during task operation. Wait for the task to complete before reading "Last Syntaxnodes". In this way, the time of "Execute()" method is almost zero, and the last typing can be guaranteed to be processed.


For example,Enter 1 to 9:
Suppose the typing delay is 100ms
It is assumed that each processing is 400ms

![image](https://raw.githubusercontent.com/84819760/imgs/main/SourceGenerator/process.jpg)

The prerequisite is that the "Execute()" method is triggered in the same order as the input order, and that the "Addsource (string hintname, string source) " is called independently.

**Comment by CyrusNajmabadi** [comment]
> What is needed at present is to process only the last change and discard the nodes generated in the process.

This is already the model in roslyn, and why Cancellation and CancellationTokens are so prevalent in our design.  We practice cooperative cancellation where we cancel in-flight work when it is no longer relevant.  This is very much the case with source generators.  If we don't need the results (say, because someone continued typing) then we will cancel that work and kick off new work.

**Comment by 84819760** [comment]
@CyrusNajmabadi 

High latency of Execute method will lead to poor IDE experience. Am I using it wrong?
IDE: Microsoft Visual Studio Community 2022 17.3.0

````
    public virtual void Execute(GeneratorExecutionContext context)
    {
        var token = context.CancellationToken;
        try
        {
            for (int i = 0; i < 400; i++)
            {
                token.ThrowIfCancellationRequested();
                Thread.Sleep(1);
            }
        }
        finally { }
        context.AddSource("code", $"// {DateTime.Now}");
}
````
![image](https://raw.githubusercontent.com/84819760/imgs/main/SourceGenerator/Method1.gif)

**Comment by CyrusNajmabadi** [comment]
Yes.  You're blocking the thread you're on 400 times, hurting the threadpool.  Don't use the above pattern :)

**Comment by CyrusNajmabadi** [comment]
WRT codelens... i'm not sure waht you expect to happen.  Codelens needs correct semantics (so it can actually tell how many references there are and where they are).  So that must run all generators like with any part of the system that needs semantics.

**Comment by 84819760** [comment]
@CyrusNajmabadi 
Execute() has a very high probability of 400ms delay, e.g. when copying and pasting a large chunk of code, so I need AddSource (string hintname, string source) method that can be called independently

**Comment by CyrusNajmabadi** [comment]
> Execute() has a very high probability of 400ms delay, e.g. when copying and pasting a large chunk of code,

This should be rare and should be amortized over all the edits users do.  If you have a good incremental generator it should not matter either as amortized costs should be appropriately low.  Invest in making your generator cheap and somethnig that only does work when necessary.

> method that can be called independently

**Comment by 84819760** [comment]
@CyrusNajmabadi 

To ensure the IDE experience, my current practice is to control Execute() within 100ms, displaying the current result if it finishes processing within 100ms, and displaying the last generated result if it fails to finish processing. One problem with doing this is that the latest result cannot be displayed if it is not processed after the last typing. This is because I lose the opportunity to call the AddSource() method.

**Comment by CyrusNajmabadi** [comment]
I don't know what you mean by "displaying the current result".

**Comment by CyrusNajmabadi** [comment]
@84819760 Can you point out how your incremental generator is working?  Why does it need so long to run after each edit?

**Comment by 84819760** [comment]
@CyrusNajmabadi 
In most cases Execute() can be completed within 1-30ms, unless copying a large amount of code in will result in more than 400ms

**Comment by CyrusNajmabadi** [comment]
@84819760 why is that the case?  What is your incremental generator doing?  Can you point out how your incremental generator is working? Why does it need so long to run after each edit?

Also, you may want to take this to discord.gg/csharp.  It might make it much easier to explain what you're doing.

**Comment by 84819760** [comment]
The node I collected is the "GenericNameSyntax" that specifies "Identifier.Text" and then converts it to "IMethodSymbol", not "TypeDeclarationSyntax"

**Comment by CyrusNajmabadi** [comment]
@84819760 let's take this to discord.  we'll need more information as to what's going on to make progress on this.  Thanks!

**Comment by 84819760** [comment]
@CyrusNajmabadi  
After switching from "ISourceGenerator" to "IIncrementalGenerator", there is a significant improvement, thank you very much.

**Comment by 84819760** [comment]
@CyrusNajmabadi 
Switch to "IIncrementalGenerator" I found a new problem, is there a way to solve it? #63422

**Comment by CyrusNajmabadi** [comment]
Sounds like a bug.  If you want to contribute a fix, i'm sure we'd be interested in it :)

**Comment by 84819760** [comment]
I tried to fix it, but the downloaded "roslyn" source code did not compile successfully, but I found a silly way to avoid this bug, but it is not clear what the consequences of doing so are.
![GeneratoOk](https://user-images.githubusercontent.com/23549775/185027278-267b1028-67e7-4d1d-8fdc-143ffaa96733.gif)

**Comment by 84819760** [comment]
@CyrusNajmabadi 

through observation, it is found that:
after deleting the last node, the "IEqualityComparer. Equals()" method of the last node in the cache is not executed. after checking the source code, it is suspected that there is a problem with this code. the source code I downloaded did not compile successfully and could not be debugged, so I hope that those who are in a position to do so can try.

````
method : Microsoft.CodeAnalysis.NodeStateTable<T>.Builder.TryModifyEntries(...)

public bool TryModifyEntries(ImmutableArray<T> outputs, IEqualityComparer<T> comparer, TimeSpan elapsedTime, ImmutableArray<(IncrementalGeneratorRunStep InputStep, int OutputIndex)> stepInputs, EntryState overallInputState)
{
    if (_previous._states.Length <= _states.Count) return false;
    var previousEntry = _previous._states[_states.Count];
    if (previousEntry.Count == 0 && outputs.Length == 0)    { ... }

    /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        After deleting the end node,
        the number of outputs will be less than the number of caches, 
        so "previous.Last().Equals(outputEntry)" will never be executed, 
        likely to be judged as not updated.
        */
    var sharedCount = Math.Min(previousEntry.Count, outputs.Length);

    for (int i = 0; i < sharedCount; i++) { ... }
    // removed
    for (int i = sharedCount; i < previousEntry.Count; i++) { ... }
    // added
    for (int i = sharedCount; i < outputs.Length; i++) { ... }
}
````

**Comment by 84819760** [comment]
@CyrusNajmabadi 
through observation, it is found that:
after deleting the last node, the "IEqualityComparer. Equals()" method of the last node in the cache is not executed. after checking the source code, it is suspected that there is a problem with this code. the source code I downloaded did not compile successfully and could not be debugged, so I hope that those who are in a position to do so can try.

````
method : Microsoft.CodeAnalysis.NodeStateTable<T>.Builder.TryModifyEntries(...)

public bool TryModifyEntries(ImmutableArray<T> outputs, IEqualityComparer<T> comparer, TimeSpan elapsedTime, ImmutableArray<(IncrementalGeneratorRunStep InputStep, int OutputIndex)> stepInputs, EntryState overallInputState)
{
    if (_previous._states.Length <= _states.Count) return false;
    var previousEntry = _previous._states[_states.Count];
    if (previousEntry.Count == 0 && outputs.Length == 0)    { ... }

    /* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        After deleting the end node,
        the number of outputs will be less than the number of caches, 
        so "previous.Last().Equals(outputEntry)" will never be executed, 
        likely to be judged as not updated.
        if(previousEntry.Count > outputs.Length) {   ????  }
        */
    var sharedCount = Math.Min(previousEntry.Count, outputs.Length);

    for (int i = 0; i < sharedCount; i++) { ... }
    // removed
    for (int i = sharedCount; i < previousEntry.Count; i++) { ... }
    // added
    for (int i = sharedCount; i < outputs.Length; i++) { ... }
}
````
