### ISSUE TITLE
The compiler broke recently 

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/roslyn#63395]
**Version Used**: 

AMD 3950x

.NET SDK:
 Version:   7.0.100-rc.1.22413.1
 Commit:    fd587269d0

**Steps to Reproduce**:

1. Clone https://github.com/tactical-drone/zero/commit/04643f0129be32a250596bfb04bded3bbb01a761
2. Mess with the constant set on [this](https://github.com/tactical-drone/zero/blob/04643f0129be32a250596bfb04bded3bbb01a761/zero.core/runtime/scheduler/IoZeroScheduler.cs#L45) line 
3. Set it to `2` or `*4` or high. For some reason buffer sizes cause all kinds of havoc. It's hard to explain. 
4. The compiler also also slowed down massively since about 2 months ago. 

**Expected Behavior**:

Profit

**Actual Behavior**:

Every day I download the latest nightly because I am doing bleeding edge development that needs to work in the future, not now. It is hard to explain but since 2 days ago it became clear that there is something massively wrong with the compiler. IDE crashes all the time. Many hangs. Even a compile hang after a fresh start on the `REV` stated above. 

The errors are severe enough that you guys should be seeing it too. Just a heads up if you are not. Here is some proof. After many hangs and giving up I found this in my task manager after closing the IDE:

![image](https://user-images.githubusercontent.com/1815319/184535779-7c658795-b6e7-4ca9-960d-d7deb238af38.png)

![image](https://user-images.githubusercontent.com/1815319/184535823-16c1dec0-9897-4bf3-a512-5d08f0898c65.png)

On the positive side. Together with these issues I have seen low level performance double. Whatever you guys did, do some more of it.

**Comment by jaredpar** [comment]
I took a look at the repro you provided and wasn't able to see anything. I used a debug compiler built from the latest source code and was able to build `zero.core.csproj` without any issues (using several different versions of that constant). 

You mentioned the compiler crashes: do you have a crash dump that we could look at?

**Comment by tactical-drone** [comment]
@jaredpar Ok thanks. It must be my computer then.

There is too much uncertainty here. I am going to close this issue util I can get a handle on this.

**Comment by tactical-drone** [comment]
@jaredpar I think found the problem. My static constructors were not executing before `int main`. Still have C++ logic in my head. AFAIK C# is lazy with those, I forgot. I think what happened is something changed around the execution order of this lazy load causing problems. This also explains why if I make buffers bigger strange things started to happen, which was delaying the startup of the scheduler causing strange things. 

Thanks!
