### ISSUE TITLE
"Error CS8034: failed to load Analyzer", if analyzer is packed with native dependencies

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63396]
**Version Used**: VS17.3

**Steps to Reproduce**:

1. Checkout to https://github.com/Sergio0694/ComputeSharp/pull/349/commits/84badb3944b6eaa628cc45aa6d0657e2fd830454

**OR**

1. Create a new analyzer
2. Bundle a native .dll in some subfolder (eg. `analyzers\dotnet\cs\Libraries\x64\foo.dll`)
3. Create a NuGet package for the analyzer
4. Reference that from a project
5. Try to build the project

**Expected Behavior**:

The analyzer should work just fine and Roslyn should ignore those bundled native libs (as they're not assembly references).

**Actual Behavior**:

> CSC : error CS8034: Unable to load Analyzer assembly C:\Users\runneradmin\.nuget\packages\computesharp\2.0.0-alpha.2855646720\analyzers\dotnet\cs\Libraries\arm64\dxcompiler.dll : PE image doesn't contain managed metadata. [D:\a\ComputeSharp\ComputeSharp\tests\ComputeSharp.NuGet\ComputeSharp.NuGet.csproj]

**Additional context**:

This is me trying to follow up on #63290 and the conversation I had with @CyrusNajmabadi, and doing work to stop doing IO from my generator in ComputeSharp (see https://github.com/Sergio0694/ComputeSharp/pull/349). Currently, I'm bundling two native .dll-s as embedded resources, and then extracting them into a temp folder to load them and P/Invoke into them. The PR is changing that to instead pack those libraries with the analyzer, so they're copied in a subdirectory in the analyzer folder, from where I can load them directly (without additional IO).

For some reason though, Roslyn is trying to load those .dll-s automatically, and then failing due to them being native libs.

Questions:
1) Is there a way to get Roslyn to ignore those files so it doesn't fail to load the analyzer?
2) Can we document this scenario, "bundling native dependencies in a generator", so it's easier to setup for others too?

cc. @sharwell @chsienki

**Comment by dibarbet** [comment]
possible dupe of https://github.com/dotnet/roslyn/issues/54899

**Comment by Sergio0694** [comment]
Yeah this seems like a duplicate indeed, closing this one 🙂
