### ISSUE TITLE
Navigate Backward does not include small cursor movements.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#634]
Ported from TFS WorkItem: **906952**

---

**Repro Steps:**

**Affected Branch:** Dev14\VSPro_Platform<BR>**Affected Build:** 21514.00<BR><BR>**Steps to reproduce:**<BR>1. Create a new VB Console Application.
1. Set the contents of Module1.vb to the following:

<BLOCKQUOTE style="MARGIN-RIGHT: 0px" dir=ltr><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>

<FONT face=Consolas>Module</FONT></FONT></FONT></FONT><FONT face=Consolas><FONT size=2><FONT color=#000000 size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>Module1</FONT></FONT></FONT></FONT>

<FONT face=Consolas><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>&nbsp;
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; Class</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass2
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2 face=Consolas>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sub</FONT></FONT></FONT><FONT size=2><FONT size=2><FONT face=Consolas> myMethod2()</FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim</FONT></FONT></FONT><FONT size=2><FONT size=2> mc1 </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>As</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass1</FONT></FONT></FONT><FONT size=2><FONT size=2> = </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>New</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass1
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>mc1.myMethod1<FONT size=2 face=Consolas><FONT size=2 face=Consolas>() </FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>' MARKER 1
</FONT></FONT></FONT></FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Sub
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Class</FONT></FONT></FONT></FONT>

<FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; Class</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>FillerClass
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Class</FONT></FONT></FONT></FONT>

<FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2 face=Consolas>&nbsp;&nbsp;&nbsp; Sub</FONT></FONT></FONT><FONT size=2><FONT size=2><FONT face=Consolas> Main()</FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim</FONT></FONT></FONT><FONT size=2><FONT size=2> mc1 </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>As</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass1</FONT></FONT></FONT><FONT size=2><FONT size=2> = </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>New</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass1
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

<FONT face=Consolas><FONT color=#0000ff>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT>mc1.myMethod1<FONT size=2 face=Consolas><FONT size=2 face=Consolas>() </FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>' MARKER 2
</FONT></FONT></FONT></FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Sub</FONT></FONT></FONT></FONT>

<FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; Class</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#2b91af size=2><FONT color=#2b91af size=2><FONT color=#2b91af size=2>MyClass1
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2 face=Consolas>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sub</FONT></FONT></FONT><FONT size=2><FONT size=2><FONT face=Consolas> myMethod1()</FONT>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Sub
</FONT></FONT></FONT></FONT><FONT size=2><FONT size=2>

</FONT></FONT><FONT face=Consolas><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>&nbsp;&nbsp;&nbsp; End</FONT></FONT></FONT><FONT size=2><FONT size=2> </FONT></FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT face=Consolas>Class</FONT></FONT></FONT></FONT>

<FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT face=Consolas></FONT>&nbsp;

<FONT face=Consolas>End</FONT></FONT></FONT></FONT><FONT face=Consolas><FONT size=2><FONT color=#000000 size=2> </FONT></FONT><FONT color=#0000ff size=2><FONT color=#0000ff size=2><FONT color=#0000ff size=2>Module
</FONT></FONT></FONT></FONT>
1. Place the cursor within "<FONT face=Consolas>myMethod1</FONT>" on the line with comment "<FONT color=#008000 face=Consolas>MARKER 1</FONT>".
2. Right click and choose "Go To Definition" (or press F12).
3. Place the cursor within "<FONT face=Consolas>myMethod1</FONT>" on the line with comment "<FONT color=#008000 face=Consolas>MARKER 2</FONT>".
4. Right click and choose "Go To Definition" (or press F12).
5. In the VS menu, choose "VIEW &gt; Navigate Backward" (or press Ctrl+-).

&nbsp;

**Expected Results:<BR>**Cursor returns to line "<FONT face=Consolas>mc1.myMethod1</FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>() </FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>' MARKER 2<FONT color=#1e1e1e face="Segoe UI">".</FONT></FONT></FONT></FONT>

&nbsp;

**Actual Results:<BR>**Cursor returns to line "<FONT face=Consolas>mc1.myMethod1</FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>() </FONT></FONT><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas><FONT color=#008000 size=2 face=Consolas>' MARKER 1<FONT color=#1e1e1e face="Segoe UI">".</FONT></FONT></FONT></FONT>

&nbsp;

This also happens in C#. This does not repro on older Visual Studio installations.

---

**Revisions:**

1) Created By Collin Deel (Chinasoft) (3/17/2014 2:34:28 PM)

---

2) Edited (4/18/2014 12:56:17 PM)

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font size=3><font color="#000000"><font face=Calibri>We intentionally coalesce go back markers that are close (with in 10 lines or so). When doing a go to definition, Roslyn calls through:</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>&nbsp;</font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font size=3><font color="#000000"><font face=Calibri><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.TryNavigateToSpan(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.TextSpan textSpan, bool usePreviewTab)<span style="">&nbsp;&nbsp;&nbsp;&nbsp; </span>Unknown</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>&nbsp;</font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font size=3><font color="#000000"><font face=Calibri>And that code – for a file that is already open – calls into CTextManager.NavigateToLineAndColumn2 which treats it like a normal caret move (meaning that it will get ignored if the caret didn’t end up moving much in a document that was open and had focus).</font></font></font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>&nbsp;</font>

<p class=MsoNormal style="MARGIN:0in 0in 0pt;"><font color="#000000" size=3 face=Calibri>It looks like C++ ends up explicitly calling IVsEditorGoBackLocations.SetNonMergeableGoBackLocation() to get around that behavior. Roslyn should probably do something similar (when navigating to an already open file).</font>

**Comment by CyrusNajmabadi** [comment]
Haven't had any reports on this behavior in all this time.  Not going to change this unless things change wrt user feedback in this area.
