### ISSUE TITLE
Proposal: Automatically convert Singlecore-Processor program to Multicore-Processor program

### ISSUE THREAD

**Issue by Anil86** [dotnet/roslyn#6340]
I want c# feature to automatically convert Singlecore-Processor program to Multicore-Processor program. Now there is quad core & 8 core processors available. These processors are even available on mobile. 

I want c# to go big, feature that has never been available, neither on c# nor on any other programming language.

**Comment by HaloFour** [comment]
Sequential tasks automatically "spread" across multiple threads "for the heck of it" will simply run slower than their single-threaded counterparts.  Multithreading doesn't make programs faster and does absolutely increase the complexity due to synchronization significantly.

**Comment by paulomorgado** [comment]
And that would be a runtime feature already possible today using [`Parallel`](https://msdn.microsoft.com/library/system.threading.tasks.parallel "Parallel Class").

**Comment by bbarry** [comment]
Other languages do have parallel features built-in. Perl6 (calls it "autothreading") can do something like:

    my @words = <order not guaranteed to say method>;
    @words».say

At the moment I don't believe that is done in parallel, but the spec says it could be. I think order is specified for current language looping structures but there is always [`System.Threading.Tasks.Parallel`](https://msdn.microsoft.com/library/system.threading.tasks.parallel). An equivalent program to the above Perl6 would be something like this:

    class Program {
        private static void Main(string[] args) {
            var words = new[] {"order", "not", "guaranteed", "to", "say", "method"};
            Parallel.ForEach(words, w => Console.WriteLine(w));
        }
    }

**Comment by jmarolf** [comment]
don't forget about [parallel linq](https://msdn.microsoft.com/en-us/library/vstudio/dd460688(v=vs.110).aspx)

**Comment by HaloFour** [comment]
@bbarry Indeed, but in any such language it should be something that the developer opts-into as any parallelism increases overhead and if the operation is very short it's likely not going to be faster (and likely will be slower) to get more threads involved.  PFX/TPL with LINQ and `async`/`await` make C# quite easy for writing multithreaded and/or asynchronous applications with minimal syntax.  I don't think additional (or worse, completely automagick) language features are necessary.

That said, I am always interested in language (or framework) features to simplify threading/synchronization scenarios.

**Comment by bbarry** [comment]
@HaloFour agreed.

I am interested in said features but I'm not sure language syntax is the best place for them.

**Comment by HaloFour** [comment]
@bbarry Indeed, it would have to be considered on a case-by-case basis.  `async`/`await` was genius that I don't know was that recognized beforehand and now is being adopted (at least considered) in a number of languages.  I also have a soft spot for the chord syntax from Cⲱ (#1165) which I think was one of the most clever way to program reactive joins in a language

**Comment by svick** [comment]
For reference, [automatic parallelization](https://en.wikipedia.org/wiki/Automatic_parallelization) has been studied for a long time, but the results haven't been great:

> fully automatic parallelization of sequential programs by compilers remains a grand challenge due to its need for complex program analysis and the unknown factors (such as input data range) during compilation

I don't think it makes much sense to make this kind of experiments on the production versions of Roslyn/CLR. (But of course anyone is free to experiment in their own fork.)

**Comment by MgSam** [comment]
I want c# feature that finds and fixes bugs in code for me with no work involved. Also c# make program do what user wants without needing all the typing and the thinking.

c#, go big or go home.

**Comment by dsaf** [comment]
> ...feature that has never been available, neither on c# nor on any other programming language.

I wonder if there was a reason for this...

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
