### ISSUE TITLE
Using Source Generator occurs a weird building error 

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/roslyn#63418]
**Version Used**: 
OS：Windows 10 21H2
SDK：.NET 6.0.400
IDE：Visual Studio 2022 17.4.0 Preview 1

**description**:

I using source generator to help us generate the view and viewmodel wire code，and it's work well so many day，but today i try to add some feature , the weird thing happen.

the msbuild report me occuring CS0111 error,  but this class only generated by source generator ,and only define the method once. and i can ensure that the method will not be define in other place.and they work so well just before thirty minutes ago.And i do nothing change with my solution.

![shot2](https://user-images.githubusercontent.com/29297262/184756993-c576c01d-b078-40de-b7cc-9dc7a168fe2c.png)

![shot](https://user-images.githubusercontent.com/29297262/184756792-64a3d737-eb64-4c0b-9526-32f3990d2be6.png)

**Actual Behavior**:

**Comment by Luoyingliang** [comment]
I rollback all the change by git, there stills occurs error. next step i will rollback the visual studio to try

**Comment by Luoyingliang** [comment]
When i create an new file and copy all generated code to the file manually,there are no trouble stuck the build task

**Comment by hez2010** [comment]
You may execute `dotnet clean` to remove all intermediate files and try again.

**Comment by Luoyingliang** [comment]
> You may execute `dotnet clean` (or delete the `obj` directory) to remove all intermediate files and try again.

it's doesn't affect anything，i use `dotnet clean` clean all the project or i delete all the `obj` folder which in the directory, wait for regenerated . but they are nothing change.

**Comment by Luoyingliang** [comment]
i can create a repo to reproduce this problem

**Comment by Luoyingliang** [comment]
the repo is published. https://github.com/Luoyingliang/CA0111

**Comment by Youssef1313** [comment]
@Luoyingliang Cloning your repro and running `dotnet build` on command-line leads to a successful build.

![image](https://user-images.githubusercontent.com/31348972/184810729-3c97054b-bbb4-4858-94eb-c0263bd749e0.png)

Do you see errors in IDE, but not in command-line builds?

**Comment by Luoyingliang** [comment]
> @Luoyingliang Cloning your repro and running `dotnet build` on command-line leads to a successful build.
> 
> ![image](https://user-images.githubusercontent.com/31348972/184810729-3c97054b-bbb4-4858-94eb-c0263bd749e0.png)
> 
> Do you see errors in IDE, but not in command-line builds?

@Youssef1313 i trying command line, but the same result.Is there any thing can affect it,such as  application cache etc.

![QQ截图20220816142405](https://user-images.githubusercontent.com/29297262/184812037-32ea0ca7-6d04-48cc-be87-f6e47e792c31.png)

**Comment by Luoyingliang** [comment]
my dev environment is following information:

![QQ截图20220816142733](https://user-images.githubusercontent.com/29297262/184812438-01a72f51-5d26-41db-8c06-a225cbbb7751.png)

**Comment by Luoyingliang** [comment]
![QQ截图20220816142733](https://user-images.githubusercontent.com/29297262/184812521-7a6af16f-13a9-4f36-ba1e-b8f113486c51.png)

this is my dev enviroment

**Comment by Luoyingliang** [comment]
![QQ截图20220816142733](https://user-images.githubusercontent.com/29297262/184812654-965607a4-7226-4629-8e12-cdee2ef5e85a.png)

**Comment by hez2010** [comment]
Can you try adding `/bl:build.binlog` to your build command line and post the binlog?

**Comment by Luoyingliang** [comment]
> Can you try adding `/bl:build.binlog` to your build command line and upload the binlog?

ok, i upload the binlog to the repo, can you clone again?

**Comment by Luoyingliang** [comment]
is there any progress increase?

**Comment by hez2010** [comment]
I'm not able to reproduce the issue. Your project builds fine for me.

**Comment by Luoyingliang** [comment]
how about the binlog，perhaps the build failed reason in logs



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 17, 2022 18:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dotnet/roslyn] Using Source Generator occurs a weird building error  (Issue #63418)




 
I'm not able to reproduce the issue. Your project builds fine for me.

**Comment by davidwengier** [comment]
Looks like you're hitting this issue with WPF temp projects: https://github.com/dotnet/wpf/issues/6792

**Comment by Luoyingliang** [comment]
> Looks like you're hitting this issue with WPF temp projects: [dotnet/wpf#6792](https://github.com/dotnet/wpf/issues/6792)

yes，i reproduce the problem.

because i install the new version of dotnet sdk（6.0.400）,so the source generator in wpf project will be run twice。but this is the critical info.

because develop a maui project that need version 6.0.4, but when i install the 6.0.4 will cause my wpf project break down,

so,damn it

i will try check out an new branch to resolve that.but this is not the best solution.

**Comment by Luoyingliang** [comment]
> Looks like you're hitting this issue with WPF temp projects: [dotnet/wpf#6792](https://github.com/dotnet/wpf/issues/6792)

thx
