### ISSUE TITLE
interactive test failures

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#6342]
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference3
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference2

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/551/

**Comment by davkean** [comment]
Thanks for filing these.

**Comment by davkean** [comment]
Duplicate #6291
