### ISSUE TITLE
IDE0049 should be updated to suggest converting IntPtr to nint and UIntPtr to nuint.

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn#63421]
**Brief description:**

As mentioned in https://github.com/dotnet/runtime/issues/72348 with the [numeric IntPtr feature](https://github.com/dotnet/csharplang/issues/6065), `nint` is now an alias for `System.IntPtr` and `nuint` is alias for `System.UIntPtr`, the [analyzer `IDE0049`](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0049) should be updated to suggest converting `IntPtr` to `nint` and `UIntPtr` to `nuint`. Preferably default to "Info" level.

**Languages applicable:**

C# only

**Additional information:**

Related to https://github.com/dotnet/runtime/issues/72348

**Documentation requirements:**

When this analyzer is updated, the  [Documentation for IDE0049 analyzers](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0049) could be updated accordingly.

**Comment by Youssef1313** [comment]
Note: we have to analyzers, one that goes from C# aliases to .NET types and one that goes from .NET types to C# aliases.

Both should be updated.

https://github.com/dotnet/roslyn/blob/eaf6778d7238a206876917a24eb8dd9c6dfa3909/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpPreferFrameworkTypeDiagnosticAnalyzer.cs

https://github.com/dotnet/roslyn/blob/eaf6778d7238a206876917a24eb8dd9c6dfa3909/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs

**Comment by CyrusNajmabadi** [comment]
@cston can you point to docs (or give the rules) on precisely when we should consider these types equivalent?

**Comment by cston** [comment]
The compiler treats `nint` / `nuint` as aliases for `System.IntPtr` / `System.UIntPtr` when compiling with a corlib that includes `System.Runtime.CompilerServices.RuntimeFeature.ByRefFields`. Otherwise, the pairs of types are considered distinct.

**Comment by CyrusNajmabadi** [comment]
Sounds good.  I see tehre is AssemblySYmbol.RuntimeSupportsNumericIntPtr.  Could we expose that publicly?

**Comment by buyaa-n** [comment]
This also should consider [@jkotas suggestion](https://github.com/dotnet/runtime/issues/72348#issuecomment-1197392137) in the original issue:

> It would be nice for the code-fixer to suggest replacing `IntPtr` with actual pointer types where the code is actually operating on pointers.
> 
> Blank replacing `IntPtr` with `nint` will often make code harder to understand. See discussion in https://github.com/dotnet/runtime/pull/70297
