### ISSUE TITLE
UTF8 multiline raw string literals don't show left column guide in the IDE

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63428]
**Version Used**: VS17.3

**Steps to Reproduce**:

1. Write a UTF8 multiline raw string literal
2. Observe that no column guide is shown on the left

**Expected Behavior**:

The IDE should show the alignment column guide on the left like with non-UTF8 raw string literals.

**Actual Behavior**:

No column guide is shown:

![image](https://user-images.githubusercontent.com/10199417/184954797-13a967ef-a95f-4fd7-a1d1-3a69640cde02.png)

cc. @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@Sergio0694 contributions welcome :)  this will likely be a 1-2 line-fix (along with a couple of tests).
