### ISSUE TITLE
Deprecate all public constructors of various diagnostic analysis context types

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#63440]
**Analysis context types:** https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs

**Context:** This types were originally made public with the intent of allowing custom analyzer hosts to implement their own analyzer driver implementations, which would have required these constructors to be public. Since then, we have introduced `CompilationWithAnalyzers` type, which is the primary public API from the compiler layer for custom analyzer execution for individual documents/spans. We don't believe there are any custom analyzer driver implementations out there which need the public constructors for analysis context types. This issue tracks marking all of them as obsolete.

**Comment by mavasani** [comment]
Tagging @jaredpar @333fred @RikkiGibson @chsienki to confirm if they are fine with this proposal.

**Comment by 333fred** [comment]
Seems fine with me.

**Comment by 333fred** [comment]
### API Review

* We're ok with the general concept, and we don't think we want to expose public constructors with `IsGeneratedCode` on them
* We think we should wait until .NET 8 to mark them deprecated, however, so we get more review time.
