### ISSUE TITLE
Rename doesn't work on the properties associated with positional parameters/primary constructor parameters in records

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#63455]
**Version Used**: 
17.4 Preview 2 (32816.508.main)

**Steps to Reproduce**:

1. Create a record type with a primary constructor and a method that uses the created property.
```
public record R(int Foo, int Baz)
{
    public int DoubleProp()
    {
        return 2 * Foo;
    }
}
```
2. Activate "rename" on the `Foo` declared in the primary constructor

**Expected Behavior**:
The reference to `Foo` in `DoubleProp` is renamed to whatever the user types

**Actual Behavior**:
The reference to `Foo` in the method is not renamed, only the parameter is.

Note that if you activate rename on the reference to `Foo` in the method, it correctly renames both the reference and the parameter.

**Comment by Youssef1313** [comment]
Also https://github.com/dotnet/roslyn/issues/44560

**Comment by Soreloser2** [comment]
Duplicate of ^^^
