### ISSUE TITLE
IDE0200 (lambda expression can be removed) results in compile error (partial method)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63465]
```csharp
using System;
using System.Diagnostics;

public partial class C
{
    internal void M1()
    {
        M2(x => M3(x));
        // Fix results in:
        //M2(M3); // error CS0762: Cannot create delegate from method 'C.M3(string)' because it is a partial method without an implementing declaration
    }
    
    partial void M3(string s);

    private static void M2(Action<string> a) { }
}
```

**Comment by CyrusNajmabadi** [comment]
That's wacky. I would expect this to just work and act the same way as just calling a partial method that doesn't have an impl-method.  Not sure if this is a compiler error or not.

**Comment by jaredpar** [comment]
This is "By Design". It's one of the scenarios the spec explicitly calls out as an error when the implementation side of a `partial` is missing: 

> It is a compile-time error to create a delegate to method

Section 10.7.2 in the C# 5.0 specification
