### ISSUE TITLE
"Scoped" word is forbidden since MSBuild version 17.3.0+92e077650

### ISSUE THREAD

**Issue by mkielek** [dotnet/roslyn#63469]
### Issue Description
Using "scoped" identifier in deconstructed tuple doesn't compile. Errors:
CS1001 Identifier expected
CS0246 The type or namespace name 'scoped' could not be found (are you missing a using directive or an assembly reference?)

It happens when calling an extension method accepting a Func with generic arguments.

### Steps to Reproduce
`dotnet new console`
replace Program.cs with:
```cs
("","").ProcessTuple((a, scoped) => "");

public static class Extensions
{
    public static void ProcessTuple<T1, T2>(this (T1, T2) t, Func<T1, T2, string> f)
    {

    }
}
```
`dotnet build` fails with `error CS1001: Identifier expected`

### Analysis
In MSBuild version 17.2.0+41abc5629 similar code works with no issues.
In MSBuild version 17.3.0+92e077650 it fails to compile.
Changing "scoped" to other name resolves the issue, but still an old code won't compile on an environment with latest MSBuild.

It happens when targeting both .NET 5 or .NET 6. There is .NET SDK 6.0.400 installed.

**Comment by CyrusNajmabadi** [comment]
Agreed.  We can potentially block this off as a type name, but not as a normal symbol identifier.
