### ISSUE TITLE
LangVersion 10 does not find better matching extension method.

### ISSUE THREAD

**Issue by manfred-brands** [dotnet/roslyn#63487]
**Version Used**: 
.NET 6.0.400

**Steps to Reproduce**:

Given an interface `IGet`:
```csharp
internal interface IGet
{
    [return: NotNullIfNotNull("defaultValue")]
    T? Get<T>(string key, T? defaultValue);
}
```
And an extension method `GetExtensions`:
```csharp
internal static class GetExtensions
{
    public static T Get<T>(this IGet get, string key, Func<T> getDefault)
        where T : class
    {
        return get.Get<T>(key, null) ?? getDefault();
    }
}
```
When calling `Get` with a `Func` parameter, the compiler no longer picks the extension method.
Instead it thinks that the `Func` is the value to obtain. Switching to _LangVersion_ 9.0 the code compiles fine.
```csharp
IGet get = new Getter();

string DefaultGenerator() => string.Empty;

string a = get.Get("a", string.Empty);
string b = get.Get("b", () => string.Empty);
string c = get.Get("b", DefaultGenerator);
```

Sharplab Repo [main](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAOgBEoIBzGAewGcAXKAY2YoGFGEApgEEYEADYBPZlGYBuAgQDEMAK5ixEYGIEkBorQIX4AkgHEBrEnQskAvCRgCA7iXOtWAgE4AKAJTz8AnJSKgEAMwg1VnNHTwhWRh9fOwA+MmwiCgBRMAAHVgkAoIySCDsrCwo3bwAiCBq4dMyc/Il/YtJgcutWKota4AaSP1Sm7LyC9sISjm7K6prBxtCIqJiveMSpglgPT1ExEl2vCI4dMwsCAG8CEjuSAG10AHYQEgA5RlZ3tTFjMM+31+tUEqzErAAauIVAIar4ALq3e4AFQA/K4LAAeZEpbzBEgAawEEkaaJIoMi4KhYhhUwAvkZjvtxOkAGxkTAY1hZAAeHhg0kYAuuSLu6AAzGySMiudjcawABYyEgXSw9Rr4okksgAVjlFVYK0prF8ovudycCq8OhlbywZpu+HN5peBr6rDl3i1jVU6mSqPRPSNUT8AXNDPwEZ2MD2BxIzAE4gECA5XL2JDeqpFTvuEul6Lcns1xNJ6IpUWptNGis8jBcjhcgOMeW0YD0HgQvLO+SgQtDBAjQA=)

**Expected Behavior**:

The last two calls get compiled into GetExtensions.Get calls as per Sharplab [C# 9](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGMD2A3KCCWUAdjKkvAkcgDQAmIA1AD4ACATAIwCwAUCwAwACFhwB0AEUIBzIpmQx86ZKIDCmWhACCRKABsAnsnzIA3L14BiInF26owXREEQdDiOZ4BJAOIQYgqT9BAF5BIggAd0FfGBgIBAAKAEozHl4RIXEIMCgbGF9whFhMRKSQgD5hDn5RAFEAWwAHGH1U9OrBKBCAv1EYhIAiKAHqKpqG5v0U9qFgbsCYPr9B4BHBZIqxuqaW6b4O9Hne/oHV0aycvIL44oQ93nwSeJ1dQUe4hBz0Jx8/XgBvXiCYGCADaLAA7CBBAA5TAwGE2XSeMBwhFIwYaS66GAANT0cAgAySAF0gSCACoAfmifgAPBTygkMoIANYQfSjamCLG5HH43SEvYAXw872eeiqADZhGxaTBagAPOJUfCYKgA8nAlgAZmlggp8oZTJgAAtjIJfv4FqMWezOcIAKzGnowC58mBJLUg4ERU3xJyG6Hsb2Ang+n2Q11LGDGhL20bWWxlKk0hbuvLJVI+0U8XMPJ6USXIaCOWiy+UfQTQq2a8Mg3UGmkxON2jlcmm8vICoWbM0ITBRcJRNGeJqOeouOK0JXfZpqohZ3i5oA==)

**Actual Behavior**:

```
error CS0029: Cannot implicitly convert type 'System.Func<string>' to 'string'
error CS0029: Cannot implicitly convert type 'System.Func<string>' to 'string'
```

**Comment by svick** [comment]
C# 10 has [documented breaking changes regarding overload resolution of lambdas and method groups](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%206.md).

**Comment by manfred-brands** [comment]
Thanks, my issue would fall into this.
