### ISSUE TITLE
Inline rename stops updating the buffer live if you temporarily rename to 'in'

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#63493]
**Version Used**: Version 17.4.0 Preview 1.0

**Steps to Reproduce**:

1. Paste the following code into a new console app as a top level statement:
```
for (int colIndex = 0; colIndex < 123; colIndex++)
{
}
```
2. Start a rename of 'colIndex' to 'index', pausing after you typed 'in'.

**Expected Behavior**: It continues to update.
**Actual Behavior**: Sometimes it stops updating.

**Comment by jasonmalinowski** [comment]
I've seen this, @genlu was able to reproduce too. This was originally reported by @timheuer.

**Comment by ryzngard** [comment]
This should be fixed with the new experience. Closing, let me know if you keep hitting
