### ISSUE TITLE
CS0540 partial type with generic base does not implement interface

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#63490]
**Version Used**: `4.4.0-2.22405.13 (dcfe294d)` / `7.0.100-preview.4.22252.9`

**Steps to Reproduce**:

**Test1.cs**
```C#
interface ITest
{
    void Test();
}

class Generic<T> { }
class Argument { }
partial class Partial : Generic<Argument> { }
```

**Test1.cs**
```C#
partial class Partial : Generic<Argument>, ITest
{
    void ITest.Test() { }
}
```

Now either
1. include `#nullable enable` in Test1.cs; or
2. set `<Nullable>enable</Nullable>` in the project and add `// <auto-generated />` to Test2.cs

**Expected Behavior**: Compiles without errors. As per [Partial and Methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods) "Parts can specify different base interfaces, and the final type implements all the interfaces listed by all the partial declarations."

**Actual Behavior**:
```
Test2.cs(5,10,5,15): error CS0540: 'Partial.ITest.Test()': containing type does not implement interface 'ITest'
```

**Related:**
#32041, #31858

**Comment by RikkiGibson** [comment]
It wasn't clear to me why #32401 was related.

**Comment by miloush** [comment]
My apologies, that was a typo: #32041
