### ISSUE TITLE
AnalyzerFileReference.InMemoryAssemblyLoader should always try to satisfy AssemblyResolve events

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn#635]
When we load an analyzer assembly A we also hook `AppDomain.CurrentDomain.AssemblyResolve` so that we can handle loading A's dependencies. When our event hook is called we inspect `ResolveEventArgs.RequestingAssembly` and only try to handle the event if the requesting assembly is an analyzer.

In practice we've discovered that `RequestingAssembly` is sometimes null, leading us to miss our chance to load a dependency.

Instead, we should always attempt to handle the `AssemblyResolve` event and only use `RequestingAssembly` (when available) as a hint for where to look first.

**Comment by tmat** [comment]
We need to remove the use of AssemblyResolve completely to make the compilers x-plat.
/cc @jaredpar

**Comment by tmeschter** [comment]
@tmat Can you elaborate?

**Comment by tmat** [comment]
AssemblyResolve is not available on CoreCLR. @jaredpar has some ideas how to avoid the need for assembly resolution in the compilers.

**Comment by tmeschter** [comment]
I'm marking this as verified because the fix has been in for a month, and given the number of analyzers we now have I'm sure we would have run into issues again if something were not working.
