### ISSUE TITLE
Clarification on Supported use of RegisterForPostInitialization

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/roslyn#63501]
this is a request for clarification following a [comment](https://developercommunity.visualstudio.com/t/Intellisense-incorrectly-reporting-RZ100/10118073#T-ND10126231) on a Visual Studio bug report.

The comment was from Microsoft and marked as private, but the author has given permission to reproduce it here

> Unfortunately, this is not a supported scenario and ultimately it won’t work until there is some plan and resolution for https://github.com/dotnet/roslyn/issues/57239
> 
> Roslyn source generators cannot see the output of other source generators, as they all run on the same compilation - that is, the one that contains only user code. Unfortunately for you in this case, thats a problem because the part of Razor that processes the .razor/.cshtml file and generates the backing C# class, is itself a source generator. You might see some parts of it working, because tooling vs command line use different pieces of tech, and some code paths generate the backing file directly, rather than using the source generator, but without Roslyn closing the feature gap, this can never be 100% working.
> 

I believe they have misunderstood, as the Roslyn documentation states that is precisely the purpose of the `RegisterForPostInitialization` method - 

> /// This method allows a generator to opt-in to an extra phase in the generator lifecycle called PostInitialization. After being initialized
> /// any generators that have opted in will have their provided callback invoked with a <see cref=“GeneratorPostInitializationContext”/> instance
> /// that can be used to alter the compilation that is provided to subsequent generator phases.
> ///
> /// *For example a generator may choose to add sources during PostInitialization.* These will be added to the compilation before execution and
> /// will be visited by a registered <see cref=“ISyntaxReceiver”/> and available for semantic analysis as part of the <see cref=“GeneratorExecutionContext.Compilation”/>
> ///
> /// *Note that any sources added during PostInitialization <i>will</i> be visible to the later phases of other generators operating on the compilation.*
> /// </remarks>
> /// <param name=“callback”>An <see cref=“Action{T}”/> that accepts a <see cref=“GeneratorPostInitializationContext”/> that will be invoked after initialization.</param>
> 

I want to clarify that I do not have a problem with my project - the code all works exactly as expected, but I am being told the VS team cannot investigate the Razor Tooling bug because use of `RegisterForPostInitialization` to add sources is **unsupported**.

If true, this will have a massive impact on anyone who can only use supported software in their projects - as adding `Attributes` - for example - in this way is quite common - and is part of the Roslyn samples.

**Comment by davidwengier** [comment]
You should feel free to post my comment here in full, I think posting it privately is the default for the feedback system.

To clarify though, I was not referring to any specific part of a source generator being supported or not. What I was trying to say is that a source generator cannot currently see the output of any other source generator, so using a source generator in a Razor scenario may not work, because the Razor code is processed by a source generator itself.

For example, if you tried to annotate a method in a source generator with `[RegexGenerator]` to use the new .NET 6 Regex generator, it wouldn't work because the Regex generator would not see the output of the Razot generator, so wouldn't see that method.

**Comment by SQL-MisterMagoo** [comment]
I'm trying to get clarification because this precise scenario - of being able to add sources that other source generators can see - appears to be what this `RegisterForPostInitialization` method is for - and this is backed up by the Roslyn samples showing how to do it.

**Comment by davidwengier** [comment]
I think a repro project would be very helpful here.

From the feedback ticket I could see that you had an analyzer project referenced, which I assumed to me a generator, and no razor class libraries referenced, so that was an immediate red flag that issues would not be unexpected.

**Comment by SQL-MisterMagoo** [comment]
I have created a repro and sent you the link on the VS feedback ticket.

For others reading this, here is a sample of the sort of code I am asking about:

```csharp
using Microsoft.CodeAnalysis;

namespace SampleSourceGenerator;

[Generator]
public class SampleGenerator : ISourceGenerator
{
	private const string SampleAttributeSource = @"namespace SampleLibrary;
			[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]
			public sealed class SampleAttribute : System.Attribute
			{}";

	public void Execute(GeneratorExecutionContext context)
	{
		// do nothing here
	}

	public void Initialize(GeneratorInitializationContext context)
	{
		context.RegisterForPostInitialization(pic =>
		{
			pic.AddSource("SampleAttribute.g.cs",SampleAttributeSource);
		});
	}
}
```

### Index.razor snippet
```html
@page "/"
@using SampleLibrary
@attribute [Sample]
```

Should this be a "supported scenario" in Razor / VS?

**Comment by davidwengier** [comment]
Thanks for the repro project, but unforutately it gives me a 404. Is it private?

Two things to call out: Firstly, an attribute being found and compiling correctly is very different to the Razor component discovery process, so there could be difference there. I'm guessing the repo you created is a much more complete example than the comment above, so will see what that shows up. Secondly, you mentioned "it just happens sometimes when you have been working on a project for a while"; are you making changes to the source generator at all? There is a definite known limitation at the moment with source generators that are project references, and Visual Studio not picking up changes to them without restarted. Could that be what is going on?

**Comment by SQL-MisterMagoo** [comment]
Yes, sorry I don't want it public, but have added you as a collaborator now, so you should have access.

I completely understand there is a big difference between an attribute being found and compiled and the Razor Component discovery process. 

My concern here is:

1. The Roslyn documentation for the LTS release of .NET 6 states that `RegisterForPostInitialization` is the way for developers to add source that will be accessible to the rest of the compilation - and indeed, in practice this appears to be true - I have never had a compilation fail in this scenario. Yet response to VS feedback is "it is not a supported scenario for the Razor tooling".

For now, I would just like clarification of this point - is using `RegisterForPostInitialization` to add sources that are accessible to the rest of the compilation a supported scenario or not?

If the answer is "Yes in general for Roslyn source generators" but "no for Razor tooling" then we at least know. 

Thanks

**Comment by davidwengier** [comment]
Thank you for the repo project, and thank you for educating me about `RegisterForPostInitialization`. I haven't kept up with source generators since v1, and I guess my preconception that "source generators can't see the output of other source generators" needs more qualification these days.

Now for the bad news: I can't reproduce any issues with your sample project. Everything seems to work fine, I don't get any RZ diagnostics, I can see the component in intellisense etc. I will dig into the issue more from the Razor side

As for this issue, I think it can probably be closed. I was mistaken when I made such a broad comment about source generators. There is indeed one way to get some generated output to be seen by other generators.

**Comment by SQL-MisterMagoo** [comment]
Thanks for the clarification.
