### ISSUE TITLE
NullReferenceException from implicit cast of null-conditional member access expression 

### ISSUE THREAD

**Issue by wangyoutian** [dotnet/roslyn#63516]
**Version Used**: 
C# 4.8.1
Visual Studio: 2019

**Steps to Reproduce**:
Run the following test, where we can see NullReferenceException is thrown:

```c#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Diagnostics;

namespace t
{
	[TestClass]
	public class NulyOperImplicitCastNulXpn_UnitTest1
	{
		public class T
		{
			string _boxed="abc";

			static public implicit operator string(T x) { return x._boxed; }
		}
		public class U
		{
			public T m=new T();
		}

		[TestMethod]
		public void TestMethod1()
		{
			var u = new U();
			u = null;
			try
			{
				f(u?.m);   /// here we expect a "shortest path", so  a null is returned; but in fact, the whole expression is wrapped into an implicit cast expression. 
				throw new Exception(
					"executed code should not be reaching here."
				);

			}
			catch (NullReferenceException x)
			{

				Trace.WriteLine("we expect it to be null or txt cast from T");
			}

			void f(string s) {
				;
			}
			

		}
	}
}
```

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:
We expect either:
1) the implicit cast is operated on the "m" only if "u" is not null, not on the whole expression: "u?.m".
or
2) at least a warning is issued.

**Actual Behavior**:
A NullReferenceException is thrown at the implicit cast method body. It takes a few thoughts/try to attribute that to the nullable member access expression.

**Comment by CyrusNajmabadi** [comment]
i don't see what the issue is here.  You wrote `f(u?.m)`.  `u?.m` evaluated to `null` since `u` was null.  Then the null `T` was converted to a `string` since you're calling `f(...)` (which takes a string).  So `static public implicit operator string(T x) { return x._boxed; }` is called with a null for `T x`.  you did `x._boxed` so that null-refs at runtime.  

> the implicit cast is operated on the "m" only if "u" is not null, not on the whole expression: "u?.m".
or

This has never been how the language has worked.  We did the argument evaluation, got null, then converted it as necessary to the right type in order to actually call into the method.

**Comment by wangyoutian** [comment]
After I change the `class T` to `struct T` as follows:

```C#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Diagnostics;

namespace t
{
	[TestClass]
	public class NulyOperImplicitCastNulXpn_UnitTest1
	{
		public struct T
		{
			string _boxed;
			public T(string x)
			{
				_boxed = x;
			}

			static public implicit operator string(T x) { return x._boxed; }
		}
		public class U
		{
			public T m=new T("a");
		}

		[TestMethod]
		public void TestMethod1()
		{
			var u = new U();
			u = null;
			try
			{
				f(u?.m);
				throw new Exception(
					"executed code should not be reaching here"
				);

			}
			catch (NullReferenceException x)
			{

				Trace.WriteLine("we expect it to be null or txt cast from T");
			}

			void f(string s) {
				;
			}
			

		}
	}
}

```
, the NullReferenceException is not thrown this time. I would say this behavior is at least not consistent, as per the explanation, current behavior shall work the same on other kind of type, such as struct.

**Comment by svick** [comment]
@wangyoutian That's called lifted conversion and it only applies to value types.

You're right that reference types and value types are not consistent, but in a sense, that's the whole reason they are different kinds of types.

Also note that nullable reference types try to make reference types more consistent with value types. If you enable them, [you'll get a warning on your code](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABATARgFgAobABgAJt8A6AERgEMBzAOwHsBnYGAY04DcJEgGJWAVwA2kxgCNJEChFZyFw4ioC2ETgAdGvRcBIBvEgEhsAZiq4KAOSkIA8rugBJTbsl8YwAMKM3I6SABq6rAD6AKqsfgAqOsBExOZmqZY2eBTxFml5lviUkbLsAB4QKEIZmTkAFNSUZQCUBenmHeYl5ZUUALwUZdWdAL7qndQAbFQ2MF4+vH4U7G5QjMDsUFRFdfGDzRQmVADsgzTdFVUUYxk3Hda2FNF57fc2e5p9rBAA7vUARIx/s1huYbnkHtgACw5JIAWQgwAAFuwUPg6q0Mq9zGBGFtxP0KN8/tEMaDzASBhJpOTgFAEG0CuY4HVxAB+GiaEFM5FQdh/YkUACiZUMuh47FYdSZ5n+EAqvHEwF6vFRik4KKkKCJ7GAFFkiigEAMSJgrGYFCR0Ag/yZ3Jqdw6vHWvCRFDqIUkACUIHBraxDCKxRLWPtGTVzPE1oYaAB1WDKgAyZogdX+P0U8rcvD1Sw2+sU1Mkyy2wDKeud3AocD5mhywPJ4Jq0OrDSKFE4B2x5kbeTuNxGQA).

**Comment by wangyoutian** [comment]
re: [https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBECWAhgOYB2A9gM4Au+AxpQNzLIDEpArgDZeEBGXAKbpBpfkJZIxAW0GUADoTrDqyAN7IAkFADMmGOgBy3AJ4B5eYIBOASWnyu9fNQDChGsa4ANeaQD6AKqkzgAqctSISJoaUdp6NFYcdNToIVrR6dpwGH585AAegsDMsXGpABRYGPkAlJkxmo2auQVF6AC86PklTQC+kk1YAGyYevj2jnTO6OSWVoTU5FaY2eUhXTXoapgA7F3YLYXF6P2xp426+ugB6Q0XeuvS7aSCAO4VAESEHzU9mqfpS5QAAsqXCAFlBNQABbkYBwcp1WJ3TQAN0Iyw4HXQL3eAURf00WM6nB4hOoVhM9UymgAZuUOAB+bDSX40mFWcjvXHoACi+WU8lo5FI5Rpmg+gkKdA41DadDhwkosO4wBx5BSfGEVkESmh+FIxHQ0Osgg+NLZpXOjToCzo0PQ5U8XAASoJaabSMp+YLhaQNtTSpoQvNlNgAOpWZyCAAyBsE5Q+r2EUssyXQ00W6C1OO4XBmy2o+RStpo6FpnOkqR+hIBpRB5cq2XQlE2KM0tfS51OvSAA==](sharplab for struct)
I can see for the struct the callsite is compiled as:
```
<TestMethod1>g__f|2_0(t.HasValue ? ((string)t.GetValueOrDefault()) : null);
```
That is virtually what I intend to mean in my opening post: 

> the implicit cast is operated on the "m" only if "u" is not null, not on the whole expression: "u?.m".

But for class type, the compiled callsite is:
```
 <TestMethod1>g__f|2_0((u != null) ? u.m : null);
```
per [https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBECWAhgOYB2A9gM4Au+AxpQNzLIDEpArgDZeEBGXAKbpBpfkJZIxAW0GUADoTrDqyAN7IAkFADMmGOgBy3AJ4B5eYIBOASWnyu9fNQDChGsa4ANeaQD6AKqkzgAqctSISJoaUdp6sOghWtHJ2nAYfnzkAB6CwMyxcYkAFFgY2QCUqTGatZqZOXnoALzo2QV1AL6SdVgAbJh6+PaOdM7o5JZWhNTkVpjpxSFtFehqmADsbdgNufno3bGHtbr66AHJNSd6y9LNpIIA7iUARIQvFR2ah8mnUAAsiXCAFlBNQABbkYBwYpVWJXTQAN0I8w4LXQD2eAVhX00aNanB4uOoVhM1VSmgAZsUOAB+bDST4UiFWcjPTHoACi2WU8lo5FIxQpmheglydA41CadChwkokO4wAx5Go6D4wisgiU4PwpGI6HB1kELwpTMKx1qdBmdHB6GKni4ACVBJSjaRlNzefzSCtyYVNCFpspsAB1KzOQQAGV1gmKL0ewjFljoqvGszVwkJXAm82o2VVVpo6EprOkiQ+uJ+hQBxdK6XQlFWCM0leSx0OnSAA](sharplab for class) .
We can see the compiled is quite different expression, and one is typed T, one is typed string.

**Comment by wangyoutian** [comment]
This might be a somewhat pitfall for some programmers as the identity source code compiles into different semantics.

To make this more obvious, I  fabricated a generic example:
```C#

using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Diagnostics;

namespace t
{
	[TestClass]
	public class NulyOperImplicitCastNulXpn_UnitTest1
	{
		public struct T1struc
		{
			string _boxed;
			public T1struc(string x)
			{
				_boxed = x;
			}
			static public implicit operator string(T1struc x) { return x._boxed; }
		}
		public class T1class
		{
			string _boxed;
			public T1class(string x)
			{
				_boxed = x;
			}
			static public implicit operator string(T1class x) { return x._boxed; }
		}
		public interface T1interface<X>
		{
			X m { get; }
		}
		public class U1struc
			: T1interface<T1struc>
		{
			public T1struc m => new T1struc("a");
		}
		public class U2class :
			T1interface<T1class>
		{
			public T1class m => new T1class("a");
		}

		[TestMethod]
		public void TestMethod1()
		{
			var u = new U2class();  ///todo: Change this to <see cref="U1struc"/>, we get no NullReferenceException.
			u = null;
			try
			{
				f(u?.m);
				throw new Exception(
					"executed code should not be reaching here"
				);
			}
			catch (NullReferenceException x)
			{

				Trace.WriteLine("we expect it to be null or txt cast from T");
			}
			void f(string s) {
				;
			}
		}
	}
}
```
Note: the commented todo in the above code.

**Comment by svick** [comment]
It is different, because the types in question are different. For a class, the type of `u?.m` is `T`, so the conversion operator from `T` is used directly. For a struct, the type of `u?.m` is `Nullable<T>`, so the conversion operator from `T` cannot be applied directly and is instead lifted into an operator from `Nullable<T>`.

In any case, I don't think anything is going to change here, since that would be a significant breaking change.

**Comment by wangyoutian** [comment]
@svick @CyrusNajmabadi ,Thanks. This discussion helps a lot.
