### ISSUE TITLE
Error CS1508 is not pointing to Microsoft doc page

### ISSUE THREAD

**Issue by khaled-saleh-sf** [dotnet/roslyn#63515]
I hope this is the right section to create the error for. The issue is that error CS1508 is not pointing to this page when it's shown in Visual studio 2022.

![image](https://user-images.githubusercontent.com/97256983/161008192-80d152d3-5d3e-4440-88c7-3cd37f572463.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c173c631-4eaf-e59b-0374-62cb1fbac4a7
* Version Independent ID: 7cdf3c66-bd51-6473-b207-249cf6ce3be7
* Content: [Compiler Error CS1508](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1508)
* Content Source: [docs/csharp/misc/cs1508.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1508.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by ryzngard** [comment]
@mavasani PTAL. Did we break something here?

**Comment by mavasani** [comment]
This should be fixed with https://github.com/dotnet/roslyn/pull/58409. @jmarolf can you please review that PR? The PR is now associated with 3 bug fixes.

**Comment by khaled-saleh-sf** [comment]
@mavasani Would this fix solve the issue where the HelpUrlLink is used on the Diagnostics creation but not pointing to a custom link and still goes to the Microsoft doc page?

![image](https://user-images.githubusercontent.com/97256983/193644892-481446b3-903f-4b5b-a36e-b74cfdc842bc.png)

**Comment by mavasani** [comment]
> Would this fix solve the issue where the HelpUrlLink is used on the Diagnostics creation but not pointing to a custom link and still goes to the Microsoft doc page

@khaled-saleh-sf This scenario already works fine for diagnostics reported from live analysis during typing. The issue only comes up for diagnostics that are reported from an explicit Build or Rebuild commands, as we currently do not associate a help link for these diagnostics. With https://github.com/dotnet/roslyn/pull/58409, we will do this associated correctly for all diagnostics (live or build), and things should work as expected.

**Comment by khaled-saleh-sf** [comment]
@mavasani Great! would that be released in the upcoming VS 2019 update too?
