### ISSUE TITLE
source generator IncrementalValuesProvider caching lost on add/remove

### ISSUE THREAD

**Issue by zbynek001** [dotnet/roslyn#63514]
When working with `IncrementalValuesProvider`, it looks like it's using caching only, when items have the same index in the internal array. And if there is new item added/removed somewhere in the middle, all subsequent items cannot use previously cached results.

Is there some way to do the equality check based on something else then index? Like providing some custom `keySelector` function which could be used instead?

**Comment by CyrusNajmabadi** [comment]
Correct. The order must be the same. So adding an item at the start of judge will prevent caching of the remainder.  This should ideally but be a problem as amortized cost will still be low as long as your generator does this rarely.
