### ISSUE TITLE
Go to definition on NotImplementedException ctor opens TypeNameParser.cs

### ISSUE THREAD

**Issue by cremor** [dotnet/roslyn#63532]
**Version Used**: Visual Studio 17.3.1

**Steps to Reproduce**:

1. Create a new .NET 6 console application.
2. Add the code `throw new NotImplementedException();`
3. Use "Go to definition" (or "Go to implementation") on the `NotImplementedException` constructor call.

**Expected Behavior**:
The `NotImplementedException` class should be opened.

**Actual Behavior**:
The file TypeNameParser.cs, which contains the classes `SafeTypeNameParserHandle` and `TypeNameParser`, is opened.

**Comment by cremor** [comment]
Tagging @davidwengier because he fixed the last Go to definition bug that I found 😃

**Comment by davidwengier** [comment]
Did the source come from SourceLink? (it should say in the Visual Studio tab).
What symbol servers do you have turned on?
Can you paste in the output from the "Navigate To External Sources" category in the Output Window.

**Comment by cremor** [comment]
Yes, source is from source link:
![grafik](https://user-images.githubusercontent.com/116314/186085603-c8f7c6ba-01ec-420c-b799-890d3440b1fb.png)

No symbol servers turned on.
![grafik](https://user-images.githubusercontent.com/116314/186085855-68195d7d-16b6-45db-b737-940e23093b13.png)

Output from output window:
```
Navigating to symbol 'System.NotImplementedException.NotImplementedException()' from 'System.Runtime'.
Symbol found in assembly path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.8\ref\net6.0\System.Runtime.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.CoreLib.dll'
Found PDB on symbol server.
'/_/src/coreclr/System.Private.CoreLib/src/System/TypeNameParser.cs' found via SourceLink.
```

**Comment by davidwengier** [comment]
Thanks, I can see what is going on. It's resolving the symbols incorrectly, finding the metadata from the reference assembly, but using that on the implementation assembly.

**Comment by davidwengier** [comment]
Oh, I forgot. I already fixed this :)

Fixed by https://github.com/dotnet/roslyn/pull/62406

**Comment by cremor** [comment]
Thanks. Is there a workaround for this? Or is it another thing where we have to wait until 17.4 to get a working go to defintion back, like #63424?
Sorry for sounding negative, but I really regret updating to 17.3 already 😞

**Comment by davidwengier** [comment]
I'm afraid not. 17.4 Preview 1 is out, and can be installed side-by-side with 17.3, but at this point of release unless a bug causes a hard crash for a lot of users, or is a security fix of some kind, its not going to meet the bar for servicing.

**Comment by cremor** [comment]
OT: Is 17.3 special somehow in that only such important bugs are fixed? Because in previous versions there often have been small fixes. E.g. just two weeks ago 17.2.7 was released and it even contained a fix for a visual imperfection according to the release notes.

**Comment by davidwengier** [comment]
No, nothing special about 17.3. I don't know the specifics of that issue, but potentially it was impacting every VS user who uses git, which would be a lot more users than people who try to go-to-def on .NET types.

**Comment by cremor** [comment]
I found another case. Is this fixed too?

1. Go to definition on `HashCode.Combine<T1, T2>(T1, T2)`.
2. Opens source link file RuntimeType.CoreCLR.cs

Output window:
```
Navigating to symbol 'System.HashCode.Combine<T1, T2>(T1, T2)' from 'System.Runtime'.
Symbol found in assembly path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.8\ref\net6.0\System.Runtime.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.dll'
Symbol found in assembly path 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Private.CoreLib.dll'
Found PDB on symbol server.
'/_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs' found via SourceLink.
```

**Comment by davidwengier** [comment]
Yeah, the bug was around following typeforwards, which you can identify by 3 or more "Found symbol" lines.
