### ISSUE TITLE
Edit.SubwordExpandSelection should not include quotes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63539]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/EditSubwordExpandSelection-should-not-i/10065305)._

---
[severity:It's more difficult to complete my work]
Edit.SubwordExpandSelection should not include quotes

VS2022 / 17.2.2 bind a key to Edit.SubwordExpandSelection, when the cursor is within (eg) an html attribute that has 2 subwords, press the key twice.  VS doesn't select just the subwords, it also includes the quotes.

Example:

_class="exampleClass"_

put the cursor on the "p", press key for Edit.SubwordExpandSelection, selects just _example_ (as expected), press key again, it should be _exampleClass_ but is instead _"exampleClass"_.

This makes it tedious to copy into another attribute, eg to then copy into _class="existingClass"_ you get _class="existingClass"exampleClass""_

Double-clicking the word selects _exampleClass_ without the quotes.

---
#### Tracy Wang [MSFT] on 6/8/2022, 08:06 PM: 

(private comment, text removed)
#### Marc Free on 6/9/2022, 08:05 AM: 

(private comment, text removed)
#### Feedback Bot on 6/9/2022, 05:28 PM: 

(private comment, text removed)
#### Feedback Bot on 6/13/2022, 02:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is being tracked by the editor team as Roslyn is returning results that are expected from the APIs they are calling.
