### ISSUE TITLE
Remove docs/samples folder and all contents from the repo

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/roslyn#6353]
All of the Word and PDF docs in the repo have been migrated to markdown files in the wiki. You can find them here:
## Getting Started
- Getting Started - Syntax Analysis ([VB](https://github.com/dotnet/roslyn/wiki/Getting-Started-VB-Syntax-Analysis) | [C#](https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis))
- Getting Started - Semantic Analysis ([VB](https://github.com/dotnet/roslyn/wiki/Getting-Started-VB-Semantic-Analysis) | [C#](https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Semantic-Analysis))
- Getting Started - Syntax Transformation ([VB](https://github.com/dotnet/roslyn/wiki/Getting-Started-VB-Syntax-Transformation) | [C#](https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation))
## Analyzers and Code Fixes
- How To Write an Analyzer and Code Fix ([VB](https://github.com/dotnet/roslyn/wiki/How-To-Write-a-Visual-Basic-Analyzer-and-Code-Fix) | [C#](https://github.com/dotnet/roslyn/wiki/How-To-Write-a-C%23-Analyzer-and-Code-Fix))

Since we don't want to maintain these binary files in the repo moving forward they should be deleted.

**Comment by davkean** [comment]
Can you point out which files in particular so that anyone can pick up this? We've also stopped marking things like as this as infrastructure, and instead assign to a team to pick up.

**Comment by AnthonyDGreen** [comment]
This entire folder: https://github.com/dotnet/roslyn/tree/master/docs/samples

**Comment by TheXenocide** [comment]
I was going to open a separate ticket, but it seems like this may be related to the fact that the links don't work in this documentation (linked to from the main repository readme/front page of the roslyn repo github page): https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #44](https://github.com/dotnet/roslyn-sdk/issues/44) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #45](https://github.com/dotnet/roslyn-sdk/issues/45) via [**ZenHub**](https://www.zenhub.com/)
