### ISSUE TITLE
IDE refactor to file-scope namespace corrupts C# file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63542]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE-refactor-to-file-scope-namespace-cor/10107784)._

---
Create the following C# file in any project, using “latest” C# language option (I used .NET Framework 4.8). The file has a closing brace (for the namespace) as the last character in the file, without a trailing carriage-return (CR), line-feed (LF), or other character afterwards.

```  
namespace foo
{
#if true
	class foobar { }
#endif
// There must be no CR, LF, or other character after the brace on the following line!
}
  
```

(Note that the bug still happens if the comment line is omitted)

Now, place the cursor after the namespace name “foo”, and press semicolon. This causes auto-refactoring of the entire file for the new file-scoped namespace syntax.

The result is the following invalid C# code:

```  
namespace foo;

#if true
class foobar { }
  
```

Note that the `#if` directive is not closed.

Additional Info
---------------

If the `#if` directive specifies `false`, the disabled code is permanently removed. Again, ensure that there is no CR/LF on the last line of the file.

```  
namespace foo
{
#if false
	class foobar { }
#endif
}
  
```

Here is the result:

```  
namespace foo;
  
```

Although in this case the result is not malformed C#, I expected the excluded code to be retained after refactoring (and not deleted).

---
#### Feedback Bot on 7/31/2022, 08:29 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 7/31/2022, 11:51 PM: 

(private comment, text removed)
#### Glenn Slayden on 8/1/2022, 03:46 AM: 

(private comment, text removed)
#### Glenn Slayden on 8/22/2022, 11:21 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 8/2/2022, 03:01 AM: 

(private comment, text removed)
#### Andrew Hall 🤘 [MSFT] on 8/19/2022, 01:11 PM: 

(private comment, text removed)
#### Glenn Slayden on 8/22/2022, 11:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Customer provided repro in file: 

```c#
namespace foo
{
#if false
	class foobar { }
#endif
}
```

hitting ";" at the end of `foo` repros

**Comment by glenn-slayden** [comment]
(I am the originator of the issue)

**Comment by CyrusNajmabadi** [comment]
@glenn-slayden thanks :)  fix available now.
