### ISSUE TITLE
Register additional document code fix/refactoring provider by ContentType

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/roslyn#63547]
## Summary

This is a proposal for an optimization for the related additional document code fix/refactoring suggestion #62877.

## Background and Motivation

While the ExportCodeRefactoringProvider.Languages represent the language(s) of the project, the additional documents will have different content types. Specifying the `ContentType` when exporting code fix/refactoring providers would help to run only the appropriate code for any given additional document.

Without this change each provider would need to be instantiated and check at runtime (during `ComputeRefactoringsAsync` for example) if it is even applicable for the content type of an additional document.

## Proposed Feature

Specify `ContentType` when exporting code fix/refactoring providers:

```
    [ExportCodeRefactoringProvider(LanguageNames.CSharp)]
    [ContentType("Xaml"]
    [Shared]
    internal sealed class MyXamlRefactoring : TextDocumentCodeRefactoringProvider
    {
        ...
    }
```
If no `ContentType` is specified then the provider applies to any content type.

## Alternative Designs

???

**Comment by jasonmalinowski** [comment]
@mgoertz-msft: Although I agree we probably need some filtering, I'm not sure content type is the thing we'd want to filter on -- we absolutely have hosts where content type isn't even a concept, like VS Code. Would an extension filter work? Or if we passed along information from the project system item types, would that work too?

**Comment by mgoertz-msft** [comment]
@jasonmalinowski An extension filter would work since the ContentType registration is based on the extension anyway.

ProjectSystem/Build item types is actually something that should be accessible through Roslyn anyway, see #44099.

**Comment by mavasani** [comment]
Implemented with https://github.com/dotnet/roslyn/pull/64364
