### ISSUE TITLE
IDE0031 should not report cases where method call is on static method and instance of same name as type is used in null check

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#63557]
**Version Used**: 4.4.0-1.final

**Steps to Reproduce**:

Sharplab example: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDNgAgCLIN7LftKAZkLgDZCAWNAWQFMAXACwHtgAKDNYASjWwC+yISiTFCMNAGF+eAly7Y0Ac0YBuNCIJo5+cVGoAVOgGcG7HrtlJt2gJYAzNJzQBCALxoAdgFcANn6WNrb4uMEh2hgAdPTMbJw8albaWgQiAkA=

Real life example: https://github.com/dotnet/runtime/pull/74445/files/82265a6e849b44cb5bea33ec5fe70378a332aeff#diff-d9a95a9f0bf172beb599708e09f724a553a82e0e80be2a6a029b57651dbe45a0

**Expected Behavior**:

No IDE0031 diagnostic

**Actual Behavior**:

IDE0031 diagnostic reported on the static method call.

**Comment by CyrusNajmabadi** [comment]
@jkoritzinsky your sharplab link does not seem to be a sharplab link :)

**Comment by jkoritzinsky** [comment]
Fixing that as we speak :)

**Comment by jkoritzinsky** [comment]
Updated to a sharplab link: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDNgAgCLIN7LftKAZkLgDZCAWNAWQFMAXACwHtgAKDNYASjWwC+yISiTFCMNAGF+eAly7Y0Ac0YBuNCIJo5+cVGoAVOgGcG7HrtlJt2gJYAzNJzQBCALxoAdgFcANn6WNrb4uMEh2hgAdPTMbJw8albaWgQiAkA=

**Comment by CyrusNajmabadi** [comment]
Thanks!
