### ISSUE TITLE
Compiler error regex failure

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6355]
*See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1395/ for more details.*

**Issue 1: Compile Error**
error CS1061: 'Task

/cc: @davkean

**Comment by davkean** [comment]
:( 

My RegEx foo is terrible.

Anyone who knows RegEx want to attempt to pick this up? You can change this via http://dotnet-ci.cloudapp.net/failure-cause-management/a82fefab-f698-416f-8fca-58544c94cd4e/.

**Comment by tannergooding** [comment]
@dpoeschl, what's wrong with the regex here?

**Comment by dpoeschl** [comment]
@tannergooding ¯\(°_o)/¯

**Comment by dpoeschl** [comment]
@tannergooding Unless you're asking "What do you expect to see?", in which case the answer would be:

```
error CS1061: 'Task<object>' does not contain a definition for 'PumpingWaitResult' and no extension method 'PumpingWaitResult' accepting a first argument of type 'Task<object>' could be found (are you missing a using directive or an assembly reference?) [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\RoslynTaoActions\RoslynTaoActions.csproj]
```

**Comment by tannergooding** [comment]
Ah. You want it to tag the whole line, rather than just the first 12 characters or so.

**Comment by dpoeschl** [comment]
Looked at it with @davkean, we think the regex is right and Jenkins is probably messing this up because it thinks <object> is an html tag. :sad:

**Comment by tannergooding** [comment]
@mmitche, is it possible to have the Identified problems page display the full highlighted text or is this some limitation in Jenkins that causes it to only show a subsection of it.

Perhaps modifying the group to say `.*(error CS\d+.*$)` instead of `.*(error CS\d+.*)` would work, as it would force the regex parser to match up to the end of the line...

**Comment by davkean** [comment]
@tannergooding We're capturing the right text - it's when Jenkins is displaying the group on page that's causing it to be cut off.

**Comment by mmitche** [comment]
@tannergooding I think it's Jenkins attempting to avoid putting HTML into the output for security reasons  (the same reason you can't put certain HTML into job descriptions).  I would be nice to be able to somehow transform that text.

**Comment by tannergooding** [comment]
@mmitche, does the plugin not have an option for sanitizing HTML (so that < becomes &lt;)? If it doesn't, can we add it?

**Comment by mmitche** [comment]
Probalby not, but I think Jenkins has that built-in in it's utility functionality, so it could probably be added.

**Comment by mmitche** [comment]
Actually, it might have this already as an option.

**Comment by davkean** [comment]
@mmitche Did it have this option?
