### ISSUE TITLE
IDE0074 should not fire on null coalescing assignment with function pointers

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#63551]
**Version Used**: 4.4.0-1.final

**Steps to Reproduce**:

Sharplab sample https://sharplab.io/#v2:CYLg1APgAgDABFAjAOgEoFcB2AXAlgWwFNkBJHQgJwHsAHAZUoDdcBjQgZwG4BYAKCgDMcLOwCGAM0IIATHADCcAN584quAG0AIgBttJfDSoVsACgBEAQTMBKALoq1NCrkajsUpADY4hAB7uKTDhgQm1CAHM3QgAqYUx8UUxRcMJgAB4oABYAPjgAcUJsKABWE2seXjU4B1UnFyjg0Iio2KwEpJT0rNz2AH1xLBYKqpqEIRCwyPdW+MTk1IycuABZMqVRqonm6bj2+a6lgcwWOABeOD6joY21XHE4Eyuz88x0XWsb1WVKqt/VJ/Ol0GZ3yhRKZWGfzgAF9PggAOxwK6Q1Sw3jQoA

See https://github.com/dotnet/runtime/pull/74445/files/82265a6e849b44cb5bea33ec5fe70378a332aeff#diff-771d144c08a078d1a01c295dd30f1aceeee603029a763ef72749cb0a8a5ddef3 for the real-life example.

**Expected Behavior**:

No diagnostic

**Actual Behavior**:

IDE0074 diagnostic reported, but `??=` cannot be used with function pointers.

**Comment by CyrusNajmabadi** [comment]
@333fred why can't `??=` be used with function pointers?

**Comment by 333fred** [comment]
No null-monadic operators (??,?., etc) can be used with pointers of any kind.

**Comment by CyrusNajmabadi** [comment]
Hrmm... could you go in more depth on that?  Given an interpretation of `x ?? y` as `if x is null y else x` wouldn't that just fall out?

**Comment by 333fred** [comment]
See https://github.com/dotnet/csharplang/issues/398.

**Comment by CyrusNajmabadi** [comment]
Yes. Do that plz :-)

**Comment by 333fred** [comment]
It's open for community contributions. No one has yet.
