### ISSUE TITLE
C# Interactive Window should default to .NET Core if the current project targets it

### ISSUE THREAD

**Issue by daverayment** [dotnet/roslyn#63563]
## Summary
Ensure the C# Interactive environment reflects the type of project currently loaded. If no C# project is loaded then default to the more modern .NET Core.

## Background and Motivation
.NET Framework 4 is now only receiving security and maintenance updates, having been superseded by the cross-platform .NET Core (now just ".NET"). 

The C# Interactive Window still loads in a .NET Framework 4 scripting environment by default, even if the currently loaded project is targeting .NET Core. In addition, the title bar for the window does not indicate which version of the environment has been loaded unless the user executes a `#reset [32|64|core]` command:

![image](https://user-images.githubusercontent.com/7127766/186436944-531ada2e-d097-47f2-84f6-71bec45ffb2a.png)
(Which version has been loaded here? I am developing a .NET 6 application, but the Interactive Window is actually running .NET Framework 4.)

![image](https://user-images.githubusercontent.com/7127766/186438263-e4011434-15cb-474e-84f4-04b77eee2973.png)
(After resetting to 64-bit .NET Framework environment the version info is present in the title bar.)

This is an obvious source of confusion for the user who naturally wants to explore language features or libraries related to the project they are currently working on.

## Proposal
When the C# Interactive window is opened, Visual Studio should inspect the current project's target version for C# and automatically load in the relevant version. This would save the user having to use the `#reset [core|32|64]` command, which is not widely known.

If the current project does not target C#, the window should load the latest .NET Core environment, as this is most likely to be the one which the user will want to explore, given the current .NET landscape.

## Alternative Designs
1. Provide the user the opportunity to choose a default for the Interactive Window when first using it. This would remove the need to interrogate the project properties. Alternatively, make this a preference and document it when opening the window each time.
2. Highlight the `#reset [32|64|core]` command when opening the window each time, and indicate clearly what environment is being loaded instead of just printing "Loading context from 'CSharpInteractive.rsp'." This small addition would make things more obvious to beginners and explain why modern .NET features are not available, even if the default cannot be changed for some reason.

## Suggestion
Finally, provide the user with a drop-down list of the available scripting environments in the window's toolbar area, surfacing the switching functionality in a much more discoverable fashion when compared to learning the `#reset` command syntax.

**Comment by bartvanandel** [comment]
I'd argue that the default target should in fact be .Net Core, now that .Net 4 is aging to be a dinosaur.
Making this configurable would be viable too, that's actually where I tried to find a solution before coming here.

**Comment by genlu** [comment]
I think https://github.com/dotnet/roslyn/pull/70127 somewhat addressed this issue (fix the bug we didn't show target framework until a reset, improve the help test for `#reset`, and making .NET core default host framework)
If you think auto-select framework based on current project is still necessary, please let us know and feel free to reopen the issue

**Comment by nlaslett** [comment]
This should really be reopened to address the well-stated issues and goals of the original poster.  Having the interactive console default to Core in all cases, with no intuitive way to switch to Framework, does not make sense when there are so many legacy Framework projects still in active development.  Auto-detecting based on the loaded project would be ideal. Baring that, a dropdown list in the window toolbar would be very helpful.  Any of the suggestions in the original post would be good; it seems all of them were ignored.
