### ISSUE TITLE
It appears that retested jobs do not pick up the latest changes from the branch they are targeting

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6356]
We're seeing lots of indications that retested jobs do not pick up the latest changes from branch, unless the PR is closed and opened. 

Here's an example, https://github.com/dotnet/roslyn/pull/6275. It hit some test failures, they were fixed, the PR was retested but they ran into the same issues. The PR needed to be closed and reopened to pick up the latest changes.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by ManishJayaswal** [comment]
@brettfo can you take a look at this?

**Comment by jaredpar** [comment]
Can you clarify as to which changes you are referring to here: roslyn or roslyn-internal?

**Comment by davkean** [comment]
Roslyn

**Comment by jaredpar** [comment]
I actually wouldn't expect this to work.  Jenkins doesn't merge PRs with HEAD when it runs suites, it just runs the latest commit in the PR without merging.  Hence if a suite is fixed after I submit a PR then I don't expect it to be fixed in my PR until I merge that fix into my PR (rebase or merge)

**Comment by davkean** [comment]
@jaredpar If there are no conflicts, then I would expect this to work (in does, if you close and reopen the PR). At least, this is how every single check-in system I've ever used in the past works.

**Comment by davkean** [comment]
@tannergooding What's your expectation around this? How easy would it to have the PR always merge with the latest in head on retest?

**Comment by jasonmalinowski** [comment]
This is definitely working now.
