### ISSUE TITLE
Unclear stack state for unconditional branches

### ISSUE THREAD

**Issue by AnakinSklavenwalker** [dotnet/roslyn#63564]
**Version Used**: Current Main branch [54aeea4](https://github.com/dotnet/roslyn/commit/54aeea412317bcddf24ca85e98004df02d6bf999)

**Steps to Reproduce**:

Consider the following C# code:
```cs
private string[] _s;

public void M(int i) {  
	var v = _s?[i] ?? "123";
	Foo(v);
}

private void Foo(string d){ }
```

which compiles into:
```
IL_0000: ldarg.0
IL_0001: ldfld string[] C::_s
IL_0006: dup
IL_0007: brtrue.s IL_000d

IL_0009: pop
IL_000a: ldnull
IL_000b: br.s IL_000f

IL_000d: ldarg.1
IL_000e: ldelem.ref

IL_000f: dup
IL_0010: brtrue.s IL_0018

IL_0012: pop
IL_0013: ldstr "123"

IL_0018: stloc.0
IL_0019: ldarg.0
IL_001a: ldloc.0
IL_001b: call instance void C::Foo(string)
IL_0020: ret
```

While implementing some static analysis code for IL i came across ECMA 335 `I.12.4 Control flow` which states:

```
[...]
5. In order for the JIT compilers to efficiently track the data types stored on the stack,
the stack shall normally be empty at the instruction following an unconditional
control transfer instruction (br, br.s, ret, jmp, throw, endfilter, endfault, or
endfinally). The stack shall be non-empty at such an instruction only if at some
earlier location within the method there has been a forward branch to that
instruction.
```

[sharplab.io code](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIGYAEGBMOAwjgN4CwAUDjTgA4BOUAbhAgKZ4CMADANoBdHAH0AzgG4qtHFNrY8AFhwBZABSwEOKAEoyNWdJqsGOZjgC8I0QH4+UIdes4ARF3xZnk6of3efAen8cACkAV1FNBAALNi1NABMAe3ZRHBhEzQBzdk1EugQoMCgAL3Z4nAgAdwgATwNDADFExNVmbS9pAF96+sYWNk4MJSaWjF4ceO0KPxxuyk6gA=)

I don't really understand what's going on here. To me this IL violates this section of the ECMA spec at 
```
IL_000a: ldnull
IL_000b: br.s IL_000f
```
because it clearly leaves the stack not empty before `br.s` is executed. To me the exclusion made in the section is also not applicable because that `br.s` instruction was never reached due to a "forward branch" but only by a normal fall-through case. 
I wonder why the compiler emits such code and what the idea was behind that decision, also i wonder whether the spec rule should be interpreted as a hard or soft constraint. Since the text mentions JIT compilers explicitly, this sections sounds more like an advice to compiler builders to make lives easier for the JIT guys, rather than a strict rule, which, if violated, breaks CIL code.

Btw: Compiling the code above with a `string[]` as method parameter instead of a field access emits IL, which is compliant to the section shown above. .

**Comment by svick** [comment]
If I'm reading that part of ECMA-335 right, it forbids code like the following:

```cil
    br L2
L1: pop
L2: ldnull
    br L1
```

Here, "the instruction following an unconditional control transfer instruction" `br L2` is `pop` and the stack is non-empty at that instruction because of the `ldnull` and `br L1`. Indeed, when I assemble that code, I get the following error from `peverify`:

> [offset 0x00000005] Stack height at all points must be determinable in a single forward scan of IL.

Though it's confusing that the language of the error message is completely different from the language used in ECMA-335, I think they're both talking about the same thing.

In your case, "the instruction following an unconditional control transfer instruction" `IL_000b: br.s IL_000f` is actually `IL_000d: ldarg.1`. And that instruction does have a forward branch (`IL_0007: brtrue.s IL_000d`), so ECMA-335 is satisfied.

**Comment by AnakinSklavenwalker** [comment]
Ah, I see. Yep that makes total sense to me. I think I got a little confused about the wording and which exact instruction was written about. 

About the error message: Yeah, that sounds totally different. Not even sure if they mean the say thing. I means the problems are definitely related, but ECMA cares about type tracking while PEVerify claims about stack integrity.
