### ISSUE TITLE
Timeout on Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MutexStopsServerStarting is too short

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6357]
As part of the test cleanup, we're disabling tests that are flaky based on Azure runs that we're doing, this test is one of them.

The test is not yet disabled, when it is, the associated commit will be linked.

The timeout (5 seconds) on MutexStopsServerStarting is too short, under CPU contention this can fail.

On some runs I'm seeing failures:
``` XML
      <test name="Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MutexStopsServerStarting" type="Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests" method="MutexStopsServerStarting" time="6.8698076" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\r\nExpected: True\r\nActual:   False]]></message>
          <stack-trace><![CDATA[   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.MutexStopsServerStarting() in C:\Users\davidjenkins\Documents\GitHubVisualStudio\roslyn\src\Compilers\Core\VBCSCompilerTests\CompilerServerTests.cs:line 2421]]></stack-trace>
        </failure>
      </test>
```

**Comment by davkean** [comment]
We're also running into this with ServerWithSamePipeNameExit, and we'll probably run into this without all the other tests in here.

@agocke  and I talked about this, and we think the approach should be increase the default timeout of the server _as part of the test_ , and just make sure the time we wait is slightly less than that.

**Comment by jaredpar** [comment]
I think we should figure out how to delete the timeout entirely.  So long as there is a timeout we will continue having issues.

**Comment by AdamSpeight2008** [comment]
Could it also be the cause of #6581

**Comment by davkean** [comment]
Jared, didn't you just resolve this with #6714?

**Comment by jaredpar** [comment]
@davkean good catch.
