### ISSUE TITLE
using statement declaration within switch ending in goto results in "csc.exe" exited with code -2146232797

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63570]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/using-statement-declaration-within-switc/10011768)._

---
[severity:It's more difficult to complete my work]
The following code results in this compiler error, but doesn't show any red squigglies when coding.
>error MSB6006: "csc.exe" exited with code -2146232797.

```
public static void Test()
{
	StringSplitOptions temp = StringSplitOptions.None;
	switch (temp)
	{
		case StringSplitOptions.None:
			break;

		case StringSplitOptions.RemoveEmptyEntries:
			{
				using var streamReader = new StreamReader("file1.txt");
				goto case StringSplitOptions.None;
			}

		default:
			break;
	}
}
```
Googling this error led me down completely the wrong path - reinstalling versions of .NET, deleting caches, etc.
In the end the cause was the code, it's just the compiler didn't tell me why. The issue is the using declaration can't tell when to close due to the goto. The same issue can be more simply created like this:

```
public static void Test()
{
	StringSplitOptions temp = StringSplitOptions.None;
	switch (temp)
	{
		case StringSplitOptions.None:
			break;

		case StringSplitOptions.RemoveEmptyEntries:
			using var streamReader = new StreamReader("file1.txt");
			break;

		default:
			break;
	}
}
```
However, in this case, intellisense and the compiler can see and explain what is wrong:
>error CS8647: A using variable cannot be used directly within a switch section (consider using braces).

Interestingly, this can be fixed by simply wrapping the whole case in braces like this:

```
public static void Test()
{
	StringSplitOptions temp = StringSplitOptions.None;
	switch (temp)
	{
		case StringSplitOptions.None:
			break;

		case StringSplitOptions.RemoveEmptyEntries:
			{
				using var streamReader = new StreamReader("file1.txt");
				break;
			}

		default:
			break;
	}
}
```
However, the same trick doesn't work when the break is replaced with a goto statement, as evident from the first code snippet.
Similarly noteworthy, is that if the first code snippet is changed such that the using declaration is in the first case of the switch, it compiles:

```
public static void Test()
{
	StringSplitOptions temp = StringSplitOptions.None;
	switch (temp)
	{
		case StringSplitOptions.None:
			{
				using var streamReader = new StreamReader("file1.txt");
				goto case StringSplitOptions.RemoveEmptyEntries;
			}

		case StringSplitOptions.RemoveEmptyEntries:
			break;

		default:
			break;
	}
}
```

Whether this should compile is somewhat beside the point as the real issue (for me at least) was the lack of information about what the issue was when it was occurring. Once I understood the problem, I could easily fix it.

---
#### Feedback Bot on 4/12/2022, 07:53 PM: 

(private comment, text removed)
#### Feedback Bot on 4/26/2022, 08:11 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by 333fred** [comment]
I'm unsure what you mean by "tells the compiler" here. What compiler? Roslyn knows nothing about this attribute.

**Comment by 333fred** [comment]
@nd1012 would you be able to share the source that caused that exception, in a new bug? That looks entirely unrelated to this bug, and likely unrelated to the specific attribute you're using; I suspect other attributes will trigger that as well, since roslyn doesn't know anything about `TargetedPatchingOptOutAttribute` in specific.
