### ISSUE TITLE
Analyzer throws warning RS1022 while creating a new AdhocWorkspace()

### ISSUE THREAD

**Issue by amruthrajv-dev** [dotnet/roslyn#63589]
**Version Used**: 

.Net Standard 2.0
Microsoft.CodeAnalysis.Analyzers - 3.3.3
Microsoft.CodeAnalysis.Common - 4.2.0
Microsoft.CodeAnalysis.CSharp - 4.2.0
Microsoft.CodeAnalysis.WorkSpaces.Common (4.2.0)

**Steps to Reproduce**:

1. Try to create new AdhocWorkspace() in the analyzer class.
2. Compile the project 

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:
No RS1022 warning
**Actual Behavior**:
warning RS1022: Change diagnostic analyzer type 'MyAnalyzer' to remove all direct accesses to type(s) 'Microsoft.CodeAnalysis.AdhocWorkspace'

**Comment by Youssef1313** [comment]
The warning looks correct to me. Analyzers should never have any dependency on Workspaces.

**Comment by amruthrajv-dev** [comment]
I want to use SymbolFinder.FindReferencesAsync() to search for some symbols in the entire solution. How do I create the solution with all the files in my SyntaxTree, without creating the AdHocWorkSpace ?

**Comment by CyrusNajmabadi** [comment]
> I want to use SymbolFinder.FindReferencesAsync() to search for some symbols in the entire solution. How do I create the solution with all the files in my SyntaxTree, without creating the AdHocWorkSpace ?

This is disallowed in an analyzer context.  Analyzers should not even be able to see downstream compilation that may depend on the compilation currently being processed.  

If you need this functionality, it has to be written as a new tool, not an analyzer.

**Comment by amruthrajv-dev** [comment]
Does it mean that I cannot use SymbolFinder.FindReferencesAsync() in an analyzer ? My requirement is to do some analysis based on the references found and then suggest a fix for that. Is there an alternate way to fulfill this ?

Right now, I am able to fulfil the use case with the warning I mentioned above.

**Comment by CyrusNajmabadi** [comment]
> Does it mean that I cannot use SymbolFinder.FindReferencesAsync() in an analyzer 

Correct.  

> Is there an alternate way to fulfill this ?

You would have to write your own tool for this (e.g. a console app).  You can programatically work against roslyn, and use APIs like the Workspace and SymbolFinder.
