### ISSUE TITLE
xUnit is crashing due a NET's EventListener race

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6358]
Tests are often failing with:

```
System.InvalidOperationException: Collection was modified; enumeration operation
 may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resour
ce)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender,
EventArgs e)
```

This a .NET bug; dotnet/corefx#3793, however, we're not going to see a fix soon. I've got an ask out to xUnit to see if we can submit a PR to workaround the issue: https://github.com/xunit/xunit/issues/646

If not, then we might need build our own version of xUnit and work around it manually. We're hitting this ~2 - 3 every 50 runs.

**Comment by jaredpar** [comment]
To followup after some investigation into the xunit code base we determined there is no real work around they can do for this bug.  xunit is just running into this issue through no fault of their own and there is little they can do to avoid hitting it.

**Comment by jaredpar** [comment]
It's been about 1 month since we removed `AppDomain` usage from the majority of our test suites: in particular the suites that were subject to this issue.  Haven't seen any occurrences of this recently, resolving.

**Comment by davkean** [comment]
We're still running into this with the scripting tests. I've submitted a PR as a workaround, let's use this bug to track removing the workaround.

**Comment by jaredpar** [comment]
@davkean i looked at the scripting tests and it looks like they are still using `AppDomain` instances for test isolation.  From app.config:

``` xml
    <add key="xunit.appDomain" value="required"/>
```

This is why scripting is still seeing this issue.  If this is switched to denied then the bug won't be a factor anymore because xunit won't be dealing with `AppDomain` tear down races.  

Do we have a bug changing scripting to no longer using `AppDomain` here?  That seems like the best fix we can do.  It's already been done in many other layers and is good practice for our move to CoreCLR.

**Comment by joshfree** [comment]
Hit this issue recently

Build #159 (Apr 13, 2016 2:26:01 AM)
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/159/

**Comment by jaredpar** [comment]
@joshfree if you're interested in a work around for this framework bug see this commit: https://github.com/dotnet/roslyn/pull/9963/commits/958ca00a68738ac61f5c8b0acce7d140567d2243

**Comment by ManishJayaswal** [comment]
Closing this as this issue is resolved.
