### ISSUE TITLE
"Inline temporary variable" suggests complete deletion of a variable

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn#63587]
**Version Used**: 

- .NET 6.0.7
- C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll
- C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll

**Steps to Reproduce**:

Take this code:

```cs
using System.Collections.Generic;

public class MyClass
{
    public List<string> MyList { get; }
    public MyClass()
    {
        MyList = new List<string>();
    }
}

public class MyTest
{
    public void MyMethod(MyClass m)
    {
    }

    public void Test()
    {
        MyClass m = new();
        m.MyList.Add("Hello");
        MyMethod(m);
    }
}
```

Hover over the colon char after `MyClass m = new();`

The "Inline temporary variable" option is showin up, unexpectedly. This is the suggestion it is giving me if I select it:

```cs    public void Test()
    {
        new MyClass().MyList.Add("Hello");
        MyMethod(new MyClass());
    }
```

[SharpLab link](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAFgG4BYAKHPQGZcAmbAWQE8BhAGwgGdPyBvc7INw0AMlE4AXADz5MAPkZMxk7L2wBzAKYSi2AL4Ch1Rey6cAFAEpDg/mSEPFyidgC82GJoDu2ZzLzyVqT2QgZkYZQ06PTMACqaknw2wrgEigzaABYA9gjmzKbc2GDWIbbJEWUp6GnxklbJdo5CBRxFYG4e3kHJDmAAdMzO/QCCCHkARAASmmxs2ROWwc2CzBkSOXkly6HkekA=).

**Expected Behavior**:

"Inline temporary variable" should show up there.

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/1175054/186561967-3c58f364-9d3f-43dc-b63a-935e7c576770.png)

**Comment by CyrusNajmabadi** [comment]
That seems to be what would be expected. It's inclining the temporary into all use sites. The temporary is initialized with a 'new()' expression, so this replaces ask references with that expression (expanded).

**Comment by carlossanlop** [comment]
@CyrusNajmabadi I'm not sure I follow.

In the suggested code, the first line is creating a `MyClass`, then adding an item to the list. But the class instance is never stored.
Then The `MyMethod` is receiving a completely new instance of `MyClass`, unrelated to the one created and modified the line before.

How is that code useful?

**Comment by CyrusNajmabadi** [comment]
> How is that code useful?

It's intended to provide you the option to inline the temporary, if you want to do that. There is no expectation that you will online every temporary you call this on. 

This is the same with virtually all refactorings offered. They're there if you want to use them. They are not offered with the expectation that you will use them in ask circumstances. 

> Then The MyMethod is receiving a completely new instance of MyClass, unrelated to the one created and modified the line before.

Yes, that's what inlining a new instance will do :-)
