### ISSUE TITLE
SourceText created in didOpen LSP handler needs encoding and checksum algorithm

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63583]
In future we plan to update the workspace with the `SourceText` instances created by `didOpen` to avoid Solution snapshot duplication. Before we do so we need to change the `didOpen` LSP protocol to allow the client to pass the file content as `byte[]` or `Stream` (the latter might be better since we can start reading the stream before the client is finished writing it). It also needs to pass the encoding that the editor uses to decode the file content. For documents that are not loaded from a file `didOpen` should send the content as `string` with no encoding.

The client would use the new version of `didOpen` protocol based on a server capability.

**Comment by tmat** [comment]
@dibarbet

**Comment by davidwengier** [comment]
If `didOpen` needs to be able to handle bytes, then does that also mean that `didChange` needs to send changes in bytes? and what about sending back edits? Seems like this would need to roll out everywhere.

**Comment by tmat** [comment]
We only need bytes and encoding in `didOpen`, if the LSP server is gonna replace document in the Roslyn workspace. We would calculate the initial checksum of the document on disk at that point (using checksum algorithm set on the project). 

When the document changes (`didChange`) is received and the LSP server updates the workspace with the new content the DocumentChanged workspace event is triggered with old and new snapshots of the document. The EnC analyzer receives this notification and updates document state based on whether the checksum of the old snapshot (original document content) matches the PDB. The checksum of the new snapshot (or any further version of the document) is not needed.

**Comment by tmat** [comment]
Essentially, we only need the checksum of the content that is first observed by Roslyn workspace. No matter whether the content is observed by LSP client or by some other VS component that triggers load of the file content to the workspace.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement on this.  If we need to do this, then it needs to go to a dev/milestone for the work to be done in.

**Comment by dibarbet** [comment]
Wanted to summarize an offline conversation on the state here.

While an LSP per document encoding would be the 'simplest' representation on the server side, it would be a relatively large LSP addition as the client would need to keep track of all encodings and ensure requests are converted correctly.  For example, if the server receives a `didOpen` with `sjis`, every subsequent request needs to respect that (both string text as well any position in any request).

We discussed some ways to pare down the change a bit.  Currently Roslyn only needs to know the encoding / bytes for states that are saved on disk.  It may be possible to augment the client to pass the original file encoding / bytes on `didOpen` and `didSave` (along with the standard information) as these signal that the file on disk has changed.  However this information could not replace the current source text representation (LSP requests would happen against the LSP encoded version), and so would have to be stored alongside it for later comparison against the PDB.

**Comment by tmat** [comment]
Change https://github.com/dotnet/roslyn/pull/81933 makes EnC resilient against non-matching encodings, so this is no longer needed for EnC purposes.
