### ISSUE TITLE
[Regression] Navigating to error messages no longer switches context

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#63586]
**Version Used**: 
Version 17.4.0 Preview 1.0 [32706.428.main]

**Steps to Reproduce**:

1. Open attached solution [ClassLibrary4.zip](https://github.com/dotnet/roslyn/files/9420743/ClassLibrary4.zip)
2. Open Class1.cs
3. Switch editor context from ClassLibrary1 -> ClassLibrary4
4. Double-click on any of the errors

**Expected Behavior**:
To navigate to error and for the context to be switched to ClassLibrary1 as it contains the errors
![image](https://user-images.githubusercontent.com/1103906/186558414-3e9610fe-51c9-49c9-8e91-b2a4e4d8141b.png)

**Actual Behavior**:
Navigates to the line but does not switch context

![image](https://user-images.githubusercontent.com/1103906/186558376-d6e9349d-3bc5-482a-a5c5-e18761a64e65.png)

**Comment by davkean** [comment]
This confused a developer that I was working with as they couldn't figure out what was wrong.

**Comment by CyrusNajmabadi** [comment]
Do build errors contain the information about the project that caused them?

**Comment by davkean** [comment]
@CyrusNajmabadi I changed the repro to remove the build step. This is just normal "intellisense" errors that do carry the context of the "project" they were found in.

**Comment by CyrusNajmabadi** [comment]
Sounds good. @dibarbet , could this be lsp related?

**Comment by dibarbet** [comment]
@CyrusNajmabadi @davkean this repros in both LSP and non-LSP.  Unfortunately until we move the navbar to LSP as well I don't see a good way for the client to perform the context switch in LSP diagnostics - unless they can control our navbar provider?

**Comment by CyrusNajmabadi** [comment]
Looks like something we'll need to bring up with the lsp group.  Once this is all lsp, then we won't be involved at all, except to report the diagnostics (or CPS for build diagnostics).  Navigation will be handled outside roslyn, so whoever is navigating will have to go to the appropriate project.

**Comment by CyrusNajmabadi** [comment]
@kayle Roslyn doesn't handle navigation to errors anymore.  So i'm guessing this is on your side?
