### ISSUE TITLE
Bad completion of `nullable` keyword

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#63594]
Noticed while working on https://github.com/dotnet/roslyn/pull/63510

**Version Used**:
17.7 Preview 1

**Steps to Reproduce**:
```cs
#pragma warning disable $$
```

**Expected Behavior**:
No completions (https://github.com/dotnet/roslyn/issues/38874#issuecomment-535612353)

**Actual Behavior**:
`nullable` completion is available. Because it is only one, it is automatically inserted

**Comment by RikkiGibson** [comment]
Fix needs to be made in [here](https://github.com/dotnet/roslyn/blob/a5a5a1c6e9660c6c49f02703a897ffd75cb17488/src/Features/CSharp/Portable/Completion/KeywordRecommenders/NullableKeywordRecommender.cs#L33)
