### ISSUE TITLE
Symbol renaming takes forever due to the wrong MEF import of IToolTipPresenterFactory

### ISSUE THREAD

**Issue by kolos450** [dotnet/roslyn#63619]
**Version Used**: 

Visual Studio 17.3.2

**Steps to Reproduce**:

1. Create a VS extension with the following MEF export:
   ```csharp
   [Export(typeof(IToolTipPresenterFactory))]
   sealed class ToolTipPresenterFactory : IToolTipPresenterFactory
   {
       public IToolTipPresenter Create(ITextView textView, ToolTipParameters parameters) => null;
   }
   ```
2. Run a VS instance with the extension installed.
3. Create a new CSharp project and rename any symbol: method, variable, etc.

**Expected Behavior**:

Renaming succeeds immediately.

**Actual Behavior**:

A `Computing Rename information...` dialog appears and VS completely hangs.

---

The constructor of [`Microsoft.CodeAnalysis.Editor.BackgroundWorkIndicator.WpfBackgroundWorkIndicatorFactory`](https://github.com/dotnet/roslyn/blob/1ce74d634ec9cfb24003fa01f04877a35accd79f/src/EditorFeatures/Core.Wpf/BackgroundWorkIndicator/WpfBackgroundWorkIndicatorFactory.cs) class imports [`Microsoft.VisualStudio.Text.Adornments.IToolTipPresenterFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.itooltippresenterfactory?view=visualstudiosdk-2022) interface like it always has a single implementation. Exporting a second implementation leads to the issue. A VS internal `Microsoft.VisualStudio.Text.AdornmentLibrary.ToolTip.Implementation.ToolTipService` uses `[ImportMany]` as expected.

There was no such issue before VS 17.3.

**Comment by CyrusNajmabadi** [comment]
@kayle since platform is taking over this UI.

**Comment by kayle** [comment]
This should be fixed in 17.4prev2 when Roslyn uses the platform service

**Comment by CyrusNajmabadi** [comment]
@ryzngard Have we moved to the platform service?

**Comment by ryzngard** [comment]
I haven't done work for that. Do we have a tracking issue to move our BWI? If platform service is ready I can take over that work

**Comment by CyrusNajmabadi** [comment]
> Do we have a tracking issue to move our BWI?

I don't think so.  But i'm happy for this to serve that purpose :)

**Comment by CyrusNajmabadi** [comment]
Closing out as external.
