### ISSUE TITLE
BadImageFormatException for abstract static from non-generic interface

### ISSUE THREAD

**Issue by iskiselev** [dotnet/roslyn#63617]
**Version Used**: 
Sharplab.IO, main(8 Aug 2022)

**Steps to Reproduce**:

Use next code:
```c#
using System;

new G<L1>().Test();
new G<L2>().Test();

public interface ILogic{
    abstract static void Run();
}

public class L1 : ILogic{
    public static void Run(){
        Console.WriteLine("L1");
    }
}

public class L2 : ILogic{
    public static void Run(){
        Console.WriteLine("L2");
    }
}

struct G<T> where T : ILogic
{
    public void Test()
    {
        T.Run();
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWAChiYBTAdwAIBxAHgBk8A+ACgEoA6AFTIGcEHANylKtRjjZdeA4cWJYAzFVgIyyAGYQAxmSoBJBgHsA5lG0BvYlRtUIwAch0IqWPADZXAFioAldHJEAL7yREquOFRMVCAGxmaW1rbhbp5YPv4wHFZEtnmueACcrABETCXsIrm2IcGhKZEMkbGGpuY5eSke3n4B7B35Nm7FZTgVVXm1tcSOqNou9NzMVBQAFup63DFxbdrEA0PK6VQyguxJNgf53JyZgZPEQUA===)

**Expected Behavior**:

Program run successfully or fail on compilation

**Actual Behavior**:

System.BadImageFormatException

Additional note if `ILogic` will be `ILogic<T>`, everything will work:
```c#
using System;

new G<L1>().Test();
new G<L2>().Test();

public interface ILogic<T>{
    abstract static void Run();
}

public class L1 : ILogic<L1>{
    public static void Run(){
        Console.WriteLine("L1");
    }
}

public class L2 : ILogic<L2>{
    public static void Run(){
        Console.WriteLine("L2");
    }
}

struct G<T> where T : ILogic<T>
{
    public void Test()
    {
        T.Run();
    }
}
```

Found it while looked for workaround for #63085.

**Comment by AlekseyTs** [comment]
Looks like a runtime issue. The IL looks correct and I do not see much difference in IL between generic/non-generic interface case apart from type parameter reference in the call instruction:
```
    .method public hidebysig 
        instance void Test () cil managed 
    {
        .maxstack 8

        IL_0000: constrained. !T
        IL_0006: call void ILogic::Run()
        IL_000b: ret
    }
-----------------------
    .method public hidebysig 
        instance void Test () cil managed 
    {
        .maxstack 8

        IL_0000: constrained. !T
        IL_0006: call void class ILogic`1<!T>::Run()
        IL_000b: ret
    }
```

**Comment by AlekseyTs** [comment]
Opened https://github.com/dotnet/runtime/issues/74792 for the runtime.

**Comment by AlekseyTs** [comment]
I just tried the scenario in VS (Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.4.0 Preview 2.0
32817.501.main]) and it runs fine. Closing as fixed for now.
