### ISSUE TITLE
ServiceHub.Host.Node.x86.exe has been using 40% of my system resources all morning even though I'm not using VS2022 (dump provided)

### ISSUE THREAD

**Issue by benstaniford** [dotnet/roslyn#63611]
**Version Used**: 

**Steps to Reproduce**:

Unknown, although I've seen this a few times in the last 6 weeks.

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:

I'd expect this process to only use resources while VS2022 is actively being used, not while it's idle in the background.

**Actual Behavior**:

Two ServiceHub.Host.Node.x86.exe, using about 40% CPU resources between them and causing my laptop fans to whir.  Not ideal given the rising cost of energy prices announced this morning.  I've split the dump across 3 files with 7-zip.

(Please remove the final .zip extension from these split zipped files, I had to add it to make github accept the file extension)

[ServiceHub.Host.Node.x86.zip.001.zip](https://github.com/dotnet/roslyn/files/9430943/ServiceHub.Host.Node.x86.zip.001.zip)
[ServiceHub.Host.Node.x86.zip.003.zip](https://github.com/dotnet/roslyn/files/9430941/ServiceHub.Host.Node.x86.zip.003.zip)
[ServiceHub.Host.Node.x86.zip.002.zip](https://github.com/dotnet/roslyn/files/9430942/ServiceHub.Host.Node.x86.zip.002.zip)

**Comment by CyrusNajmabadi** [comment]
This is not roslyn. Roslyn does not use Nodejs. Can you file this issue using normal VS feedback so it can be appropriately routed?  Thanks!
