### ISSUE TITLE
`new str$$` completion shows two lowercase `string`, one as keyword and one as class name

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63614]
![image](https://user-images.githubusercontent.com/31348972/186894491-eea86126-8091-4e60-bc7b-1b54e889c911.png)

A lower-case `string` should be shown as keyword only, not class name.

cc @genlu

**Comment by CyrusNajmabadi** [comment]
I don't repro this:

![Image](https://github.com/user-attachments/assets/30d4f8c3-0616-4a0c-aea0-9c297d48328a)
