### ISSUE TITLE
Autocompletion for `extern alias` directives suggests field/property/method names

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#63626]
**Version Used**: VS 17.4 P1 (4.4.0-1.22043.13)

**Steps to Reproduce**:

1. Add a reference with aliases to the project file.
2. Write `extern alias ` at the top of a C# file.
3. Invoke autocompletion.

**Expected Behavior**: Only eligible aliases (if any) are suggested.

**Actual Behavior**: All eligible aliases (if any) are suggested, as are a field `alias`, a property `Alias` and a method `GetAlias` -- the latter three are most likely not valid here and should not be suggested. Even if there was an alias named 'alias', it will show up as its own list item with the namespace icon.

![image](https://user-images.githubusercontent.com/823398/186989057-cb8d2fd3-59a0-4669-b4d3-81bd1b7dc44d.png)

**Comment by CyrusNajmabadi** [comment]
Closing out as we do not invest in extern alias scenarios.
