### ISSUE TITLE
"Change signature" drops namespace qualifier for alias-qualified names

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#63628]
**Version Used**: 17.4 P1 (4.4.0-1.22403.13)

**Steps to Reproduce**:

1. Reference an assembly or project with at least one public type in the project file and assign it an alias.
2. At the top of a C# file, write an `extern alias` directive for that alias.
3. Write a record declaration with no parameters.
4. Open the lightbulb menu on the record and select "Change signature", then click "Add".
5. Write the alias-qualified type name and a parameter name, select 'Introduce undefined TODO variables', and confirm both dialogs.

**Expected Behavior**: The alias-qualified name is added as a parameter.

**Actual Behavior**: The qualified name (without the alias!) is added as a parameter. If the same qualified name is already present in the compilation, this may even compile, but it will not be what the user intended.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in extern alias scenarios in the ide.
