### ISSUE TITLE
Consider consolidating CA1801 and IDE0060

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63641]
Both analyzers are for unused parameters. I think it makes sense to either deprecate CA1801 or IDE0060, and make sure to port unit tests for the deprecated analyzer to the other to make sure everything is handled correctly.

**Comment by mavasani** [comment]
@Youssef1313 This was already done by @Evangelink a while back: https://github.com/dotnet/roslyn-analyzers/pull/4535. He also graciously added documentation for the same: https://github.com/dotnet/docs/pull/21882. I am going to close out this issue.
