### ISSUE TITLE
Show embedded language classification in syntax visualizer

### ISSUE THREAD

**Issue by chucker** [dotnet/roslyn#63664]
## Summary

The Syntax Visualizer should show the classifications provided by an embedded language.

## Background and Motivation

Consider C# code like so:

```csharp
public static string DeliberatelyInvalidJson = @"
{f
    ""hello"": ""goodbye"", // test
    ""pi"": 3.141
}
";
```

In the Syntax Visualizer window, we can see this gets shown as a `StringLiteralToken`, and classified as `String - Verbatim`.

![image](https://user-images.githubusercontent.com/20194/187429328-34d30085-e34d-4acb-b353-1f801ae07b36.png)

We can also click on the color well to set a different color (rather than the salmon here) for that classification.

Due to embedded language support, if we make the above code valid JSON (and/or declare it as such), the highlighting changes:

```csharp
[StringSyntax("Json")]
public static string Json = @"
{
    ""hello"": ""goodbye"", // test
    ""pi"": 3.141
}
";
```

![image](https://user-images.githubusercontent.com/20194/187429598-f9fe9adc-b3ae-41b7-9e43-c08b9600c497.png)

For example, the number `3.141` will show in light yellow-green, and the string `""goodbye""` will show in brown.

However, the Syntax Visualizer window doesn't know about this. It still shows the entire string as a `StringLiteralToken`, and stll believes the classification to be `String - Verbatim`.

Like any aspect of the Syntax Visualizer, adding the capability would provide greater insight into Roslyn's comprehension of the syntax.

## Proposed Feature

The above highlighting works by implementing `IEmbeddedLanguageClassifier.RegisterClassifications` and supplying classifications for the embedded syntax, e.g. `ClassificationTypeNames.JsonNumber`. Those classifications are provided for particular `TextSpan`s.

Ideally, the Syntax Visualizer should:

* show those spans as new subnodes inside the tree, perhaps as a new type `EmbeddedSyntaxSpan`. This also enables scenarios the Syntax Visualizer can already fulfill for other nodes: for example, you can click on a node in the tree to select the corresponding code. Vice versa, you can click inside the code to have the tree expand and navigate the appropriate syntax node.
*  provide the correct classification for each of those subnodes.
* either change the `Language` property in the properties pane from C# to the embedded language name, or provide an additional property `EmbeddedLanguage`.

**Comment by CyrusNajmabadi** [comment]
Clsoing out as we are not investing in the syntax visualizer.
