### ISSUE TITLE
IDiagnosticService needs cleanup

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6367]
The current IDiagnosticService leaves a lot to be desired wrt to the API (esp. if we want to make it public).

Currently, the API is split into two parts.  The first is the eventing portion.  i.e: 

``` c#
        /// <summary>
        /// Event to get notified as new diagnostics are discovered by IDiagnosticUpdateSource
        /// </summary>
        event EventHandler<DiagnosticsUpdatedArgs> DiagnosticsUpdated;
```

This part is nice and reasonable and fairly easy to use.  However, the second part is more problematic.  This is the part that gives programmatic access to Diagnostics not in eventing form.  This API looks like this:

``` c#
        /// <summary>
        /// Get current diagnostics stored in IDiagnosticUpdateSource
        /// </summary>
        IEnumerable<DiagnosticData> GetDiagnostics(Workspace workspace, ProjectId projectId,
             DocumentId documentId, object id, bool includeSuppressedDiagnostics,
             CancellationToken cancellationToken);
```

Right away there are several problems:
1. What is `object id`?  How do you get it?  What does it mean if you don't include it? 
2. Why do you have to specify projectId and documentId?   ProjectId is redundant if you have a documentId.  
3. What happens if these values are null?  What happens if you pass a `projectId` but a null `id`  (hint: you get all diagnostics back for the entire workspace!)

Now, as it turns out, the `id` is really a special key stating "i want the diagnostics produced by a specific producer of diagnostics which has that ID".  And you can find those IDs by calling:

``` c#
        /// <summary>
        /// Get current UpdatedEventArgs stored in IDiagnosticUpdateSource
        /// </summary>
        IEnumerable<UpdatedEventArgs> GetDiagnosticsUpdatedEventArgs(Workspace workspace, 
                 ProjectId projectId, DocumentId documentId, CancellationToken cancellationToken);
```

But this is also an extremely strange API.  First, you are somehow getting "EventArg" objects back from this call.  Second, the EventArgs objects look like this:

``` c#
    internal class UpdatedEventArgs : EventArgs
    {
        public object Id { get; }
        public Workspace Workspace { get; }
        public ProjectId ProjectId { get; }
        public DocumentId DocumentId { get; }
        ...
```

So, essentially, you're calling into this API, passing in three pieces of data, that just get returned back in an object, along with one final piece of interesting data (the "Id").

This is not an "UpdateEvent".  There is no event happenign here at all.  Furthermore, it's extremely strange to have to call this just to get the IDs, and then have all this additional data passed along.

I propose a simplification in the concepts around this API.  To me, a better API would look like:

``` c#
     internal interface IDiagnosticService
     {
         event EventHandler<DiagnosticsUpdatedArgs> DiagnosticsUpdated;

        IEnumerable<object> GetDiagnosticSourceIds(Workspace workspace, CancellationToken cancellationToken);
        IEnumerable<object> GetDiagnosticSourceIds(Workspace workspace, ProjectId projectId, CancellationToken cancellationToken);
        IEnumerable<object> GetDiagnosticSourceIds(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken);

        /// <summary>
        /// Get current diagnostics for the specified document from this workspace.  If diagnosticSourceId 
        /// is null then all diagnostics will be returned. 
        /// </summary>
        IEnumerable<DiagnosticData> GetDiagnostics(Workspace workspace, object diagnosticSourceId = null, bool includeSuppressedDiagnostics = false, CancellationToken cancellationToken = default(CancellationToken));
        IEnumerable<DiagnosticData> GetDiagnostics(Workspace workspace, ProjectId projectId,  object diagnosticSourceId = null, bool includeSuppressedDiagnostics = false, CancellationToken cancellationToken = default(CancellationToken));
        IEnumerable<DiagnosticData> GetDiagnostics(Workspace workspace, DocumentId documentId, object diagnosticSourceId = null, bool includeSuppressedDiagnostics = false, CancellationToken cancellationToken = default(CancellationToken));
```

This API now cleanly separates the concerns a consumer can have.  Eventing stays the same.  But introspection of existing diagnostics is cleaned up.  Now the API clearly shows that you can get diagnostics without needing to know or care about diagnotic source IDs.  However, if you do want to get specific diagnostics for a source, you can just query for those source IDs and then use them to ask for diagnostics.

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani and @heejaechang

**Comment by heejaechang** [comment]
@CyrusNajmabadi existing API is just merge of the three API you split. giving null will return all of same kind.

you get the key (object) from the event or the GetDiagnosticUpdatedEventArgs (name is weird I know), it return all those data so that source can find those data cheaply. sure we can push that book keeping to each source.

**Comment by heejaechang** [comment]
@CyrusNajmabadi 
"What happens if these values are null? What happens if you pass a projectId but a null id (hint: you get all diagnostics back for the entire workspace!)" 

well this is not true. the API is inclusive. you have 4 different scope. (workspace, project, document, id) and giving null for each scope will return aggregation of the missing part.

giving all 4 will return one specific chunk of diagnostics from one diagnostic source (one diagnostic analyzer, enc, build and host generated exception and etc)

giving only (workspace, project, document ) will return all diagnostics that belong to that document regardless of diagnostic source.

(workspace, project) will return all diagnostics that belong to the project from all document and all diagnostic sources.

and so on.

so, what you basically did, was splitting this 1 API to 3 per each scope.

about giving back just object id, since DiagnosticService itself hold onto that information, you can probably recover those workspace/project/document the id belong to. if a user want to call each diagnostic source directly (which things like LB or error list does), then those diagnostic source also need to make sure holding onto those information so that it can retrieve information cheaply rather than iterating thorough all data to find match.

**Comment by CyrusNajmabadi** [comment]
> well this is not true. the API is inclusive. you have 4 different scope. (workspace, project, document, id) and giving null for each scope will return aggregation of the missing part.

This is true:

Take a look at this code:

```c#
                foreach (var data in current.Values)
                {
                    if (TryAddData(documentId, data, d => d.DocumentId, list) ||
                        TryAddData(projectId, data, d => d.ProjectId, list) ||
                        TryAddData(workspace, data, d => d.Workspace, list))
                    {
                        continue;
                    }
                }
```

Say you provide a projectId.  If the projectId doesn't match, then we'll go and just check the workspace.  If it matches, we'll add the data to the list.

**Comment by heejaechang** [comment]
private bool TryAddData<T>(T key, Data data, Func<Data, T> keyGetter, List<Data> result) where T : class
        {
            if (key == null)
            {
                return false;
            }
 
            if (key == keyGetter(data))
            {
                result.Add(data);
            }
 
            return true;
        }

this is implementation, if key is given, it will not go to next one.

**Comment by CyrusNajmabadi** [comment]
> you get the key (object) from the event or the GetDiagnosticUpdatedEventArgs, it return all those data so that source can find those data cheaply. sure we can push that book keeping to each source.

I think that would make a ton more sense.  Right now the API is *super* weird.  I have to ask for "UpdateEvent" for a given set of data.  Then i get a set of duplicated data for the data i already asked for.  Then i go and pass back that duplicated data again to get the actual diagnostics.

It would make a lot more sense to allow people to just ask for the diagnostics.  And if they *need* to ask on a per-source basis, then there should just be a way to ask for the relevant sources.  It's super weird to say.

> (name is weird I know)

Agreed.

**Comment by heejaechang** [comment]
by the way, even if it did, that is just a bug.

**Comment by CyrusNajmabadi** [comment]
Ah that's true.  I thought it returned 'false' in the case where there was no match.

**Comment by heejaechang** [comment]
@CyrusNajmabadi you can push it down. I just didn't want to force each DiagnosticSourceUpdate implementer to implement it. things diagnostic team own like live diagnostic source or build diagnostic source, I am fine implementing them. but people who just want to cheaply show something in tagger or error list, I didn't want to force them to have this book keeping.

**Comment by CyrusNajmabadi** [comment]
I am also *definitely* not a fan of APIs that take ProjectIds and DocumentIds.  That's a very strange API.  because now you have two things that should be tied tightly, which can be broken by the user.  For example, what does it mean to pass "null" for projectId, but non-null for documentId?  What does it mean if the documentId points to a different projectId than the projectId you pass in?  etc. etc.

The API i propose guides the user to use it in hte right manner.  You can't supply inconsistent data as arguments.  It also makes it clear what is required and what is optional.

For example, in the original API it was never clear that "object id" was actually something optional.  And it was also not at all clear to even figure out how you'd ever find an "id" to even use for this API.

**Comment by heejaechang** [comment]
sure, we could put that as optional parameter. and about that breaking projectid/documentId, we can put argument exception for it. I listed all those since the scope is quite natural regardless whether user has to write redundant info or not.

**Comment by CyrusNajmabadi** [comment]
>  I didn't want to force them to have this book keeping.

I'm a little unclear what you mean by that.

> but people who just want to cheaply show something in tagger or error list

I'm not sure why the way i'm proposing would be expensive...

**Comment by CyrusNajmabadi** [comment]
Ok.  I've talked in person with Heejae, and i think i have a handle on everything the Diagnostics subsystem wants to make available.  I do however think it could be exposed much more cleanly.

1. Diagnostic-Sources.  The actual end entities responsible for producing diagnostics.  Could be implemented by 1st parties or 3rd parties.  It doesn't matter.   Can be "broadcast only" sources, or can be sources that you can query for diagnostic data.  IMO, there would be separate interfaces for these two concepts.  
2. Analyzer-Service (IDiagnosticAnalyzerService).  Responsible for running all those Diagnostic-Sources on snapshots of solutions.  Currently a fairly confusing API with lots of low level operations you can ask about diagnostics.
3. Aggregation-Service (IDiagnosticService).  Aggregates the informatoin about all Diagnostic-Sources so some services have a single location to query for all the data at once.  Provides both an eventing model so you can find out when any Diagnostic-Source fires, as well as a virtual store that you can use to also go and retrieve existing diagnostics.  If the underlying Diagnostic-Source is broadcast only, it will actually cache the diagnostics internally.  If the Diagnostic-Source supports retrieval of diagnostics, then it will defer to the source.

Right now these API are all rather scattered, inconsistent, and a bit confusing.  For example, the IDiagnosticAnalyzerService has hte same problem that some APIs expect IDs.  But there is no clear way from the API to even find out what the IDs are that you can use.  Similarly, APIs have all sorts of optional parameters that can be inconsistent with each other.

--

In my ideal world there would be essentially only be two major APIs, and you'd only need to know one of them if you were a consumer.  One API would be the production API (i.e. IDiagnosticUpdateSource).  It would only be used by people who wanted to add diagnostics into the system.  You could broadcast diagnostics, and optionally support being queried for them.  (I would prefer two interfaces for this personally).

Then there would be the consumption API.  I would have a single entry service that you would use for all consumption needs.  If you wanted aggregated diagnostic information, you'd ask this service for it.  If you wanted to be notified when aggregated diagnostic information changed, you'd subscribe to an event on this service.  If you wanted to run all diagnostic sources on some snapshot of the world, you'd use this.  If you wanted to only query about some some sources, there would be easy ways to ask for all the source IDs.  And all these APIs would be uniform wrt to how they accepted workspaces, projects, documents and source ids.  

In essence, i woudl recommend merging IDiagnosticService and IDiagnosticAnalyzerService, scrubbing them over heavily, and providing a single consumption service for any party interested in diagnostics.

**Comment by heejaechang** [comment]
@srivatsn unless we are going to make this one public, I think it is fine to move to 1.3?

**Comment by srivatsn** [comment]
Wouldn't this make your OOP work easier? I don't have any objections to moving to 1.3

**Comment by heejaechang** [comment]
@srivatsn I will change it as I do out of proc work.

**Comment by heejaechang** [comment]
moving to next milestone. it is not public still.

**Comment by CyrusNajmabadi** [comment]
Closing this out as a lot of changes have gone in here.  And this will go away too with the LSP pull work.
