### ISSUE TITLE
New Inline Rename Checkboxes close session when clicked

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#63676]
**Version Used**: 17.4 Preview 2.0 [32829.479main]

**Steps to Reproduce**:

1. Rename a symbol
2. Type in desired name
3. Click any checkbox in the dialog such as "include in comments"

**Expected Behavior**: The checkbox is ticked so that the settings are applied

**Actual Behavior**: The rename session cancels and does not rename.

See the following example:
[Screen Recording.webm](https://user-images.githubusercontent.com/43689321/187533289-f5bdfd96-8292-4583-ac0e-fce077b7c4b4.webm)

**Comment by sujayvsarma** [comment]
#reopen

**Comment by CyrusNajmabadi** [comment]
@sujayvsarma please clarify why you're asking this to be reopened

**Comment by sujayvsarma** [comment]
Because the bug still exists. I've opened a dev community ticket for it.

Sent from Android device

On 02-Oct-2022 20:49, CyrusNajmabadi ***@***.***> wrote:

@sujayvsarma<https://github.com/sujayvsarma> please clarify why you're asking this to be reopened

**Comment by CyrusNajmabadi** [comment]
What version of visual studio are you using @sujayvsarma ?

**Comment by jasonmalinowski** [comment]
@sujayvsarma The fix here should be in Preview 3 which should be out in the next few days; the fix _just_ missed Preveiw 2, and Preview 2.1 had a fix for an unrelated team so we didn't ship this fix there.

**Comment by jasonmalinowski** [comment]
And I've closed the developer community ticket as well.
