### ISSUE TITLE
Holding CTRL does not always produce navigatable targets

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#63694]
**Version Used**: 
Version 17.4.0 Preview 2.0 [32830.521.main]

**Steps to Reproduce**:

I don't know what the repro is, but CTRL+Click gets in a state where only some things are navigatable. See the below GIF, I'm holding CTRL the entire time, yet only some things are navigatable:

![CTRLClick](https://user-images.githubusercontent.com/1103906/187618980-c366ee02-7c5c-49ec-b54e-c80f48d83660.gif)

And that `LogWriter.Flush` call that is now navigatable after I navigated away and came back
![CTRLClick2](https://user-images.githubusercontent.com/1103906/187619354-267fad5d-fa24-4f9d-bad7-7d98dad59f65.gif)

**Comment by Youssef1313** [comment]
Sometimes I see this, but it eventually ends up being navigatable for me after ~10 seconds. When this happens for me, it navigates to decompiled sources, not metadata. So I assumed the time taken is trying to getting real sources via sourcelink, then when it can't, it tries to decompile.

But I'm not sure if that is what really happens or if it's the same case as you.

cc @davidwengier

**Comment by davidwengier** [comment]
Interesting. I was looking into a different issue with LSP navigation, and in that case the editor just sends Go To Def commands as you mouse around and simply doesn't do the navigation part. If it functions the same way in non-LSP cases I could definitely see a PDB download being an issue, particularly with the example of something only being navigable later on.

(For fun, hold ctrl and mouse around a .cshtml file with some JavaScript in it.. if you hit the right spot, your dragging is interrupted by a message box 😀)

**Comment by arkalyanms** [comment]
@CyrusNajmabadi Based on syncing with Jason, we would like to understand if this should/could be a 2 stage process where we 1) evaluate if this should be navigatable and 2) actually get onto the network to get the needed symbol. 

Or there is just a failure in handling the call to fetch the symbol.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski i'm not aware of how roslyn is involved here.  Is there some API the platform is calling into us to determine if something is navigable or not?

**Comment by CyrusNajmabadi** [comment]
@dibarbet  do you know what lsp entrypoint may be powering this?

**Comment by dibarbet** [comment]
@CyrusNajmabadi this is not powered by LSP unless you're in Razor.  On the roslyn side I believe this is powered by this - https://github.com/dotnet/roslyn/blob/cb18669598e9b49e5cba0ef6439e1c9ac3df97ac/src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.cs#L23

**Comment by Sergio0694** [comment]
I hit this a lot as well, I often have to click on eg. a method several times before the mouse cursor finally changes to the "clicky" icon and clicking actually navigates to that method. Sometimes I just give up after a while and just jump to that file/method after finding it with the CTRL + , search, which is a bit frustrating 🥲

**Comment by davidwengier** [comment]
> I just give up after a while and just jump to that file/method after finding it with the CTRL + , search

Seems like it would be better to give up and press F12 😛
