### ISSUE TITLE
It looks like there is a problem with comparing generic constructed types with their definitions when custom modifiers are ignored

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#6372]
A generic type constructed with its own type parameters + custom modifiers should be considered equivalent to its definition when custom modifiers are ignored. C# compiler has Equals method that takes an extra flag to force this behavior, VB compiler has IsSameTypeIgnoringCustomModifiers extension method. It looks like implementation of the methods will give incorrect answer in the scenario described above.

**Comment by gafter** [comment]
What scenario could cause the compiler to exhibit symptoms because of this issue?

**Comment by AlekseyTs** [comment]
@VSadov Please verify.
