### ISSUE TITLE
Regex syntax highlighting is misleading

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63744]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Regex-syntax-highlighting-is-misleading/10128980)._

---
[severity:It bothers me. A fix would be nice]
The Regex syntax highlighting does not recognize the beginning and matching end of a group in some cases.

---
#### Tracy Wang [MSFT] on 8/23/2022, 11:59 PM: 

(private comment, text removed)
#### Sven Huebner on 8/24/2022, 10:09 PM: 

(private comment, text removed)
#### Feedback Bot on 9/1/2022, 01:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
User image: 
![image](https://user-images.githubusercontent.com/4564579/187985639-68afe9f5-5a94-48c7-9fc5-af9f41498819.png)

**Comment by CyrusNajmabadi** [comment]
Not repro in 17.4p1:

![image](https://user-images.githubusercontent.com/4564579/187986237-8155308e-1e40-4804-9e56-3b6662570fe2.png)

**Comment by shuebner** [comment]
Still there in 17.4.0:
![image](https://user-images.githubusercontent.com/1770684/200780998-9398d7cf-6a5f-4aa0-a219-b272e688cf4e.png)

**Comment by CyrusNajmabadi** [comment]
@shuebner can you please supply your repro code?

**Comment by shuebner** [comment]
You can find the code here: https://github.com/shuebner/repro-roslyn-63744

This is what the code looks like on my machine with VS 17.4.0:
![image](https://user-images.githubusercontent.com/1770684/201002022-b60cd897-0c40-4c7b-8579-820be3c674a4.png)

Note that even reduced to a minimum of `(.*)`, the highlighting is wrong.
It is the `*` that triggers it, `+` works fine.

**Comment by CyrusNajmabadi** [comment]
I don't see any c# files in that repo.  Can you point me to them?

**Comment by shuebner** [comment]
Sorry, something must have gone wrong when pushing my local files.
I updated the repro repo.

Here is the code file: https://github.com/shuebner/repro-roslyn-63744/blob/main/SyntaxHighlightingRepro/Repro63744.cs

**Comment by CyrusNajmabadi** [comment]
I'm seeing: 

![image](https://user-images.githubusercontent.com/4564579/201273928-dca2942d-96d7-442f-8f17-6ebdbacffc55.png)

No clue what's going on. :(

**Comment by shuebner** [comment]
OK, I played around with my local settings and identified the culprit:

With font "Consolas" (in your screenshot) everything is fine.
With font "Cascadia" (in my screenshot) the error appears, which is strange considering the error is the color.

**Comment by CyrusNajmabadi** [comment]
Please file an issue over at developercommunity.  This is def not a roslyn issue, but must be some sort of editor problem.  Please add all the information you've given here.  Thanks!
