### ISSUE TITLE
Rename a property of records: not all references are updated in Visual Studio 2022 17.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63750]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-a-property-of-records:-not-all-re/10045067)._

---
[severity:It's more difficult to complete my work]
When I rename a `PropertyOne` of the record in the following code then another usage of this property isn't updated.

``` csharp
public record MyRecord(string PropertyOne);

public static class Usages {
    public static string GetPropertyOne(MyRecord @record) {
        return @record.PropertyOne;
    }
}
```
Here is how it looks:
https://gyazo.com/7bbadc588b0ffd4e1df8ae89a720260b

Renaming the same property in another place of the code works well: 
https://gyazo.com/58ad817c2d7cb9b2b6c24cd948342d8c

This is a serious issue for us. Since after several renamings of different properties this can silently introduce new bugs to the code.

Visual Studio 2022 17.2 Community Edition

---
#### Feedback Bot on 5/17/2022, 07:25 PM: 

(private comment, text removed)
#### Feedback Bot on 5/19/2022, 00:10 PM: 

(private comment, text removed)
#### Feedback Bot on 8/31/2022, 06:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rekna1** [comment]
still having this problem in 17.8.7
