### ISSUE TITLE
Add abstract/VB usage refactoring For Convert to Record usage refactoring

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#63756]
Let's make sure we have a tracking bug to link here. I think it makes sense to merge this before this is done so we can start getting dogfood coverage (since the number of folks doing cross-language is small enough), but we don't want to lose this.

_Originally posted by @jasonmalinowski in https://github.com/dotnet/roslyn/pull/63648#discussion_r960096363_

Steps:
- [ ] Language-Agnostic Provider
- [X] CSharp Impl
- [X] Csharp Tests
- [ ] VB Impl
- [ ] VB tests

Be able to convert
```
public class C
{
    public int F {get; init;}
}
```
with usage:
```
Public Function Main As C
     Return New C With {
                .F = 0
            }
End Function
```
into:
```
public record C(int F);
```
with usage:
```
Public Function Main As C
     Return New C(0)
End Function
```

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in those scenarios.
