### ISSUE TITLE
No way to annotated a required member that must be set in a derived class

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#63766]
```cs
#nullable enable
public abstract class C {
    // Can't mark neither the property nor the accessor as protected
    public required object Prop { get; /*protected*/ init; }
    protected C() {}
}

public sealed class D : C {
    public D() {
        // No warning if commented out
        Prop = new();
    }
}
```
[sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABNmTHAWACgABAJgEYzyAGXc6gOgCVkYAXKMbFgMIB7MAAcoOAE4BlbJIBuUAMbYAzgG46jZiwAiUCAHMYQ1TyWrBQgCbYAgoVQBPVVA1k6AZlyYzkiEpcTJS4ArgA3mS40bhRMQD08aEQMADkQZCSANa4MNhQXAAWcrhFeKKSQqJyXE65QpKlxT5KKqqqDT6quBVCXNiB2NZx0eTektgAjshQE9a4QsAAVgNBAAqVohG4hthc6rjxAFS9/YPWR0mwBQcAviOxpDGH8QDaslyqbFMzcwCy2DAwDkqgAug9TqshqEABQASgi91ISK8uFU2AgOHmVFwulwIFCEQeD0S7z2Xx+syGAKBIPBTxiY1x8KJDOe0USuAActhoVwhPgYAAzBoqJpuLquYx8bgPZ6crkCgDuEEkMFghlwUCFuCUIhl/XmQmQXDlMQ2VVwAF5ctglfDNGzcEiUaQyIQ+KpRAE8DoONxePxhGIJHJZAplGoyJEna87FwuJIoMATdgAKqqIzYGHxxPJ1MAFVVu0+ggw7VwcFwuaTKf6RckJcs0kTyEClerCdrheL5JYADEoNhUPMqzX8/Xe6WLdVJLUADS4ACSMGKScN1twQsx6MXdnQQiVfzQPFEOE329Q6Lh9OesH6asxaIxWOCuG+0yp1hpwMk47reAEv+qYPDG7KMt4H6/NSgK/sB/Twma0RgeBzoPEizxxl2E7ppmuw5thAENk2LD7qge4HkeJ5QGeeA2q22CLiua4FNCNqXtet4xPeciOM+mLQjiwbiFI/YYlwyATFBX7wYBnZ5gBoFIUw3jCaGkhiRAElSZScyyTCzCMEK4mSdgXIQHwcLKShqExJp2lmRZdFbiZEzmXwjq2RhqFMoZuD2aZ7l4OEOx7HcylMsAQhCKgy6qAA8qIPBCHxIUlgc6L7GhTouu6Tlej6TCsPoRgmGYyiWMItgOJiLhuNGDxYQpqYZlmBHNZOjZ9sIMB+G2/KSExq5yKx8zsTujHVpRx6oKe57jVe2A3g8PGPrF6ICdiIQfBSn7/LBIKyfi8ndv0SlOs8TI7dJ+20pIqj6VZF0xDZ7LedELpAA=)

**Comment by 333fred** [comment]
This is as-designed. Please open discussions for new language features on csharplang :)
