### ISSUE TITLE
Integration tests timing out after 150 minutes

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#63772]
This is most commonly happening on the _32 integration tests (meaning they run in-proc IIRC) though it has happened in a few instances on the _64 tests.

Example build with dumps
https://dev.azure.com/dnceng-public/public/_build/results?buildId=2420&view=logs&s=2da60e49-322f-543a-13b9-30aff4334141&j=73ca024f-5e5b-53f5-c972-c172fc8cd31c

Or
https://dev.azure.com/dnceng/public/_build/results?buildId=1980181&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Cosifne** [comment]
The CI information is expired, but from the description, I feel it is very likely this should be fixed in this https://github.com/dotnet/roslyn/pull/64746 from the description.

Any wait operation for the solution crawler before this fix could cause a forever wait, and it is not repro all the time
