### ISSUE TITLE
RunTests should not write response files to repo root

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#63779]
**Version Used**: 6cc2376ad55aa7399b1aa5451e9b2c1af956a3fb

**Steps to Reproduce**:

Run `.\Build.cmd -restore -test` in the repo root

**Expected Behavior**: File changes don't appear in `git status`

**Actual Behavior**: Many files named vstest_0.rsp, vstest_1.rsp, etc. appear in `git status`
![image](https://user-images.githubusercontent.com/5833655/188222824-e570994a-117a-471a-a33b-e692f9ac77ad.png)

It feels like these files should go somewhere under `artifacts/`.

**Comment by jcouv** [comment]
I'll add those files to the `.gitignore` file as a mitigation. The `.gitignore` change can be reverted once this issue is fixed. Thanks

@arkalyanms Why was this triaged to Backlog milestone? Could we prioritize fixing this annoyance assuming it isn't too hard?

**Comment by RikkiGibson** [comment]
cc @dibarbet
