### ISSUE TITLE
C# 11 Generic Attributes do not allow for generic constructor arguments

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/roslyn#63781]
**Version Used**: 
7.0.100-preview.7.22377.5 

**Steps to Reproduce**:

1. Create an attribute with a generic argument and a constructor that takes an instance of the generic type 
2. Use the attribute

[repro](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQHMIDsIIJYDGqsM+wcMKANACYgDUAPgAIBMAjALABQPzAzAAI2ggAq5kAeyyCeAbx6DhQ8QilYAFAEpFghdyUBfJT0M8eAbQCCMUnnKUAqsiiYNNuw4gAVKAkwwyAB0VgA2oVoAunxCIgDKkgC2EB5kFBAAPN4AfIIggqn26YIA7gAWuBCC3nnCrPK6AA74AG6wVTUA+niUiQDc5gbKggnJhV4aNT0QiTpD+kpK3b2CALyC0/26ZrxDAtWCAGpQoXBVC4sBesIA7ILLM32CO0amsrsWo5mq6tkaOCUxBJpNoojE6oIALIATwAwqEoMhkHpBqZBkA)

**Expected Behavior**:
Successful compilation

**Actual Behavior**:
error CS0181: Attribute constructor parameter 'item' has type 'Person', which is not a valid attribute parameter type

**Comment by CyrusNajmabadi** [comment]
> error CS0181: Attribute constructor parameter 'item' has type 'Person', which is not a valid attribute parameter type

@shawnwildermuth CAn you supply a full repro?

**Comment by RikkiGibson** [comment]
Repro above is a SharpLab link so fairly easy to access and review.

The behavior you are seeing is expected. Think of it this way: If you just declared an attribute constructor `public SomeAttribute(Person p)` and tried to use it, the language would give an error as it always has done. This is the same thing, only it is arising via type substitution.

In this case, the only valid type arguments for `SomeAttribute<T>` in practice are those which are also valid attribute parameter types. For example, `SomeAttribute<object>`, `SomeAttribute<string>`, etc.

**Comment by CyrusNajmabadi** [comment]
> Repro above is a SharpLab link so fairly easy to access and review.

Ah, sorry.  I didn't see that.

**Comment by shawnwildermuth** [comment]
Forgive my confusion, but it works outside of attribute. I'm happy with it 'by design', but I'm trying to understand *why*:

``` csharp
public class Foo<T> where T : class 
{
    T _item;
    
    public Foo(T item) 
    {
        _item = item;
    }
}

public class Bar 
{
    public static void Main()
    {
        var foo = new Foo<String>("Hello");
        
    }
}

```

**Comment by CyrusNajmabadi** [comment]
Attributes are fundamentally restricted.  They must 'bake' their arguments into the metadata in a serializable/deserializable fashion.  That limits the number of types that are allowed to a very specific set.  Namely, some core primitive types, as well as `System.Type` and single dimensional arrays of supported types.

**Comment by shawnwildermuth** [comment]
Of course. Makes sense. Thanks.
