### ISSUE TITLE
BC30064 when assigning a value to a ReadOnly variable in the constructor inside a With block 

### ISSUE THREAD

**Issue by chacham2** [dotnet/roslyn#63807]
**Version Used**: 17.2.6

**Steps to Reproduce**:

1. Create new class
2. Add variable with ReadOnly modifier
3. Assign value to variable in constructor inside a With block

Example:

    Public Class Class1
      Private ReadOnly A As String
      Public Sub New(B As String)
        With Me
          .A = B
        End With
      End Sub
    End Class

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**: `.A = B` should not be redlined.

**Actual Behavior**: `.A = B` is redlined with [BC30064](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30064)

Using 'Me' directly avoids the issue, whether inside or outside the With block.

    Public Class Class1
      Private ReadOnly A As String
      Public Sub New(B As String)
        With Me
          .A = B
          Me.A = B
        End With
        Me.A = B
      End Sub
    End Class

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue unfortunately it's "By Design". The `With` expression when applied to `Me` turns it into a normal instance which means `ReadOnly` applies to fields.
