### ISSUE TITLE
Issue with error CS0114 and CS0109

### ISSUE THREAD

**Issue by JRahnama** [dotnet/roslyn#63821]
Hi, I am from SqlClient team and noticed an odd behavior.

In SqlTransaction we have two functions for [Rollback](https://github.com/dotnet/SqlClient/blob/966fc6eab94e193aa893d960dfc8dc0dd2236029/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlTransaction.cs#L80) and one function for [Save](https://github.com/dotnet/SqlClient/blob/966fc6eab94e193aa893d960dfc8dc0dd2236029/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlTransaction.cs#L154).

One of the Rollback functions is overriding the base class DbTransaction and has no arguments provided. The other one shares the same name(Rollback) but takes an argument of string type. 

The Save method is taking an argument of string type therefore is not overriding any class from its parent.

When we try to build the driver we get an error message saying [CS0114](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0114). I followed the suggestion, although it is not hiding any method, and tried to rebuild the driver and got error [CS0109](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0109). It seems like a loop. When I suppressed the errors in editorconfig file I was able to build the driver.

**Net6.0.400**

**Steps to Reproduce**:

1. Clone net6 branch from [PR#1704](https://github.com/dotnet/SqlClient/pull/1704)
2. Take the rules for CS0109 and CS0114 out of .editorconfig file
3. try building the driver by msbuild and you will see the problem. VS2022 does not show that error.

**Expected Behavior**:
Since the driver does not hide any method we should not get that error when building with msbuild

**Actual Behavior**:
Error CS0114 and CS0109 are thrown in alternately.

**Comment by 333fred** [comment]
@JRahnama it looks like `System.Data.Common.DbTransaction` added `Rollback(string)` and `Save(string)` methods in .NET 5.0: https://apisof.net/catalog/ddd17df1-e088-f946-1352-b791d1491706 and https://apisof.net/catalog/40ee19c8-80bb-173d-b731-e89d3ff7e382. Because of this, you are getting different warnings when targeting different frameworks. You can either suppress the warnings as you're doing now, or you can conditionally apply the `new` keyword via `#ifdef` like so:

```cs
        /// <include file='../../../../doc/snippets/Microsoft.Data.SqlClient/SqlTransaction.xml' path='docs/members[@name="SqlTransaction"]/Rollback2/*'/>
        public
#if NET5_0_OR_GREATER
            new
#endif
            void Rollback(string transactionName)
        { }
        /// <include file='../../../../doc/snippets/Microsoft.Data.SqlClient/SqlTransaction.xml' path='docs/members[@name="SqlTransaction"]/Save/*'/>
        public
#if NET5_0_OR_GREATER
            new
#endif
            void Save(string savePointName)
        { }
```
