### ISSUE TITLE
ShadowCopyAnalyzerAssemblyLoader should deduplicate assemblies

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#63820]
I'm seeing the same .dll getting shadow copied into two subfolders in the AnalyzerAssemblyLoader directory.

Right now it seems to just increment a counter:
https://github.com/dotnet/roslyn/blob/e8a14ac84e263105eea2e5092db8ae5759eac0c1/src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs#L176

I think it should deduplicate either by the hash of the full path to the original assembly, or perhaps the MVID. There's a fast way to read an MVID from a .dll (compiler uses it for ref assemblies).

**Comment by CyrusNajmabadi** [comment]
Clsoing out as speculative.
