### ISSUE TITLE
"Preview referenced changes" on Change Signature dialog doesn't preview changes

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#63831]
**Version Used**: 
Version 17.4.0 Preview 3.0 [32904.27.main]

**Steps to Reproduce**:

1. Use Change Signature on a signature
2. Check Preview referenced changes
3. Click OK

**Expected Behavior**:
For the changes to be previewed before they are applied

**Actual Behavior**:
![PreviewBroken](https://user-images.githubusercontent.com/1103906/188780687-b6d1a4a1-3c4f-4e4d-ad65-3ec01d427276.gif)

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/62825

**Comment by CyrusNajmabadi** [comment]
Closing as dupe.
