### ISSUE TITLE
CSharpSyntaxTreeFactoryServiceFactory+CSharpSyntaxTreeFactoryService+RecoverableSyntaxTree.WithRootAndOptions does not preserve the Encoding property

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/roslyn#63834]
**Version Used**: 

4.2

**Steps to Reproduce**:

Call the SyntaxTree.WithRootOptions  method with an instance of CSharpSyntaxTreeFactoryServiceFactory+CSharpSyntaxTreeFactoryService+RecoverableSyntaxTree

**Expected Behavior**:

The Encoding property of the original object should be copied to the output object.

**Actual Behavior**:

The Encoding property of the output object is null.

**Comment by arkalyanms** [comment]
Moving to Tomas who is fixing some bugs in this space
