### ISSUE TITLE
LSIF generation uses inVs on invalid nodes

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#63841]
**Version Used**: `4.4.0-1.22372.4`

**Description**:

Current LSIF generation defaults to using `inVs` for most LSIF node types. The problem with this is `inVs` are only applicable on `item` and `contains` nodes. Ultimately this results in C# LSIF failing all versions of validators.

**Steps to Reproduce**:

1. Run LSIF generator on any C# project with content 😄

**Comment by jasonmalinowski** [comment]
@NTaylorMullen Is it forbidden for item/contains edges to emit an inV if they would otherwise emit an inVs w/ a single item? Because the reason we're doing this is I was just lazy and always used inVs since thing really forbade inVs w/ a single item in the spec.

**Comment by jasonmalinowski** [comment]
I can either just make it use inV if it's a single collection and inVs otherwise, but if the rule actually depends on edge type then that's more subtle. (And we actually need to doc it.)

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Is it forbidden for item/contains edges to emit an inV if they would otherwise emit an inVs w/ a single item? Because the reason we're doing this is I was just lazy and always used inVs since thing really forbade inVs w/ a single item in the spec.

Based on examples in the spec I don't see any `item` or `contains` nodes using `inV` so I want to say "yes forbidden"? 

@dbaeumer please correct me if I'm wrong. 

> I can either just make it use inV if it's a single collection and inVs otherwise, but if the rule actually depends on edge type then that's more subtle. (And we actually need to doc it.)

Totally agree, probably an opportunity here for spec clarification too 😄

**Comment by dbaeumer** [comment]
The spec actually only defines `inVs` on item and contains. This is actually a space optimization since these edges are often 1:n. 

If we allow inVs on all edges that we need to spec that for 1:1 edges the array can only be one element. I thought that form a spec perspective it is easier to distinguish this.
