### ISSUE TITLE
LSIF Generation requires "free range" tracking resulting in heavy memory overhead for larger projects

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#63842]
**Version Used**: `4.4.0-1.22372.4`

**Description**:

Current LSIF generation emits `contains` nodes after all `item` nodes have been emitted, this results in failed LSIF validation. At first I thought this was a [bug in the validator](https://github.com/microsoft/lsif-node/pull/146) but after conversations with Dirk it's not. To more clearly lay out the issue, current LSIF generation looks like:

```
...
{ "label":"item" .... "inVs":[123] }
...
{ "label":"contains" .... "inVs":[123] }
...
```

While in practice this seems ideal what it results in is at "parse the LSIF" it means that the parser needs to track "free ranges", aka range `123` in the above example until it's able to find a `contains` for it to know what document to associate it with. For larger projects you can imagine how heavy this could become. Turns out this was [put into the spec in 0.6.0 as a constraint](https://microsoft.github.io/language-server-protocol/specifications/lsif/0.6.0/specification/#emittingConstraints) which C# currently breaks.

> if a range is references in a items edge the range must have been attached to a document using the contains edge. This ensures that that target document of a range is known. (@since 0.6.0)

**Steps to Reproduce**:

1. Run LSIF generator on any C# project with content 😄

**Comment by jasonmalinowski** [comment]
@NTaylorMullen So currently we create a single "contains" for the entire document to point to all it's ranges at once; is the goal now that we emit a separate contains for each and every range? That seems chattier/bigger but if that's the goal, sure.

**Comment by jasonmalinowski** [comment]
> You can/should still have a single contains that mentions each of the range; however, you shouldn't link those ranges in via item nodes until you mention they're contained within the document via the contains node.

So that creates a bit of a catch-22: we don't know the ranges to emit until we've walked the entire document, at which point we're linking up the item nodes. I can just hold all of the item nodes/edges in a separate-in-memory list and then dump that afterwards (we might already be doing that anyways due to some of the other peculiar ordering requirements of LSIF), but it's only creating more copying of data around...

**Comment by NTaylorMullen** [comment]
Super interesting, @dbaeumer what's your take here?

**Comment by dbaeumer** [comment]
Actually no quick idea. The reason why that constraint exists is ingestion into the database. It is easier to handle a reference to a range if the range is already connected to the document. 

I do have situations where I haven't emitted the range yet either. So what I do is to flush the range in these situations (see https://github.com/microsoft/lsif-node/blob/af85b765aa3d1a0ecfa1e0b796ae372a5c31ed87/tsc/src/lsif.ts#L336). It is allowed to have `n` contains edges with separate ranges for the same document.

However if this leads to emitting every single range with a contains then we really need to think about how to make this easier for C#.

**Comment by CyrusNajmabadi** [comment]
Closing out sue to lack of movement.  If this is needed, it should be given to a dev and a present milestone to be done in.
