### ISSUE TITLE
Address feedback on "File types EE support"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#63847]
Tracking resolution of these comments separately from the merged PR #62812.

https://github.com/dotnet/roslyn/pull/62812#discussion_r965058162
> @jaredpar: Shouldn't this be `readonly`?

https://github.com/dotnet/roslyn/pull/62812#discussion_r965062740
> @jaredpar: Need to avoid hard coding any crypto algorithms in our code base. Instead need to use one of our centralized locations. When we don't centralize it means we get hassled hard as crypto algorithms are deprecated and we have to find all the individual places it was used. Likely should centralize in SourceHashAgorithms

> @RikkiGibson: I wasn't sure what the correct usage would look like here. It seems like `SourceHashAlgorithms` itself just has helpers for converting to/from the GUID used to denote a hash algorithm in a portable PDB.

**Comment by jaredpar** [comment]
> : I wasn't sure what the correct usage would look like here. It seems like SourceHashAlgorithms itself just has helpers for converting to/from the GUID used to denote a hash algorithm in a portable PDB.

Correct. But we could also expand that central location to return the default crypto implementation.
