### ISSUE TITLE
`CommandLineArgumentReader` doesn't add `analyzerconfig`s on the "best effort" path

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63855]
https://github.com/dotnet/roslyn/blob/aa1540e5ee34ec70a126c02abf9467bc1aa21f6d/src/Workspaces/Core/MSBuild/MSBuild/CSharp/CSharpCommandLineArgumentReader.cs#L25-L35

`analyzerconfig`s are not read in the above code path. This code path is reachable from:

https://github.com/dotnet/roslyn/blob/aa1540e5ee34ec70a126c02abf9467bc1aa21f6d/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L177-L184

Implementation can look like this:

```csharp
        protected void ReadAnalyzerConfig()
        {
            var editorConfigFiles = Project.GetItems("EditorConfigFiles");
            foreach (var editorConfigFile in editorConfigFiles)
            {
                Add("analyzerconfig", editorConfigFile.EvaluatedInclude);
            }
        }
```

NOTE: I don't know if this have any noticeable impact.

**Comment by Youssef1313** [comment]
Should have no impact. These are added to ProjectFileInfo using a [different approach](https://github.com/dotnet/roslyn/blob/aa1540e5ee34ec70a126c02abf9467bc1aa21f6d/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L152-L154). Closing out.

**Comment by arkalyanms** [comment]
From Youssef's latest comment, it looks like the alternate approach still respects the analyzer configs. Please reopen if I misunderstood.

**Comment by Youssef1313** [comment]
@arkalyanms Yes I intended to click the "Comment & close" button and apparently I clicked just "Comment" 😄
