### ISSUE TITLE
API/behavior changes needed to enable LSP pull diagnostics in 17.6

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#63861]
This is the tracking item for work needed between the platform and us to get LSP pull diagnostics into acceptable shape to be enabled for customers (potentially only in preview mode though).

## Separate requests for "Pull Error Diagnostics" vs "Pull Todo/Task Diagnostic"

Currently, there is a single Document-Pull (or Workspace-Pull) request that gets both `Error Diagnostics`, as well as `Todo/Task Diagnostics`.  This is problematic as the client needs to know if the server is reporting real `Error Diagnostic`s or not in order to replace `Build Error Diagnostics` with `Intellisense Error Diagnostics`.

To address this issue, `VSInternalDocumentDiagnosticsParams` and `VSInternalWorkspaceDiagnosticsParams` will be updated to add either a flag, or property bag that can be used to know if the request is for `Error Diagnostics`, or for `Todo/Task Diagnostics`.  

This change also has the added benefit that requests for `Todo/Task Diagnostics` should not happen *unless* the `Task List` is actually open for the user.  This will save unnecessary computation for that common case.

--

Note, we could also support this by going the route of SpellChecking and having different requests entirely.  I am fine with that, though i believe Kayle/David preferred we still use the Diagnostic requests, just with a flag.

## Strongly specify the behavior around 'ResultId' and 'Streaming' reports

For `document pull diagnostics` requests (**Document only**) we will state the following about a single request to get diagnostics:

1. Multiple `VSInternalDiagnosticReport`s can be issued within that call for the *same* `ResultId`.
2. Each report represents a new set of diagnostics computed for that document (e.g. `Syntactic` vs `Semantic` diagnostics).
3. The client should make a best effort to present the reports as they are delivered.  Thus allowing for syntactic diagnostics to present before semantic diagnostics are computed.
4. The client will only record the `ResultId` as `fully completed` if the entire `document pull diagnostic` request completes successfully (e.g. it is not cancelled).

This allows diagnostics for a single document to be progressively streamed in, allowing the server to balance perf/fullness of the results.  As the server will not know exactly what the client has received (e.g. even if it sends all the info for a particular result id, it doesn't know if the client still canceled immediately after that and didn't record it all), it is incumbent on the client to only store the `ResultId` once the request is fully done.  Then, it is acceptable to use that `ResultId` in future calls to the server for updated document diagnostics for that document.

Note: The above requires no change to the protocol, but it will require changes to the implementations on both sides to ensure this works properly in a race-free fashion.

Note: We do not need this for `Workspace Pull Diagnostics`.  It's not important that the experience for closed files be able to stream in syntactic diagnostics before semantic ones.

## Have server specify which `Diagnostic ID`s are truly `Build only`

For the `Build + IntelliSense" dropdown in the error list, there exists a lot of complexity in determining how to provide a reasonable experience when some diagnostics are coming from CPS (e.g. the actual `Build` results) and some are coming from Roslyn (e.g. the `IntelliSense` results).  We propose the following model:

1. The language server can specify a set of `Diagnostic IDs` that are truly `Build Only`.  Roslyn has this list, and it's fairly small (only a few dozen IDs, versus the thousands of actual live IntelliSense Ids).
2. The language server can provide this list when queried for its `Capabilities`.
3. With this information the client can now determine what to do with the combined error list when it has errors from both systems. Specifically, whenever it has an `IntelliSense` diagnostic report for a file *AND* a `Build` diagnostic report for the file, the combined diagnostic report will be:
    a. All the `IntelliSense` diagnostics.
    b. Any `Build` diagnostics with a `Diagnostic ID` that is in the `Build Only` list.

This ensures that the IntelliSense-Server is always the source of truth for `Live` errors, but that `Build only` errors that can only come from the Build-Server will still appear in the combined list.  This does mean that those true `Build Only` errors will not get cleared until a subsequent build.  But that's the nature of a true `Build Only` error.  

The benefit of this as well is that nothing is baked into the client here.  If in the future Roslyn can take over the responsibility of some current `Build Only` error, then that will just naturally work in the client when we change our capabilities list.

Note: the above also works properly for `workspace pull diagnostics` regardless of the status of the Full-Solution-Analysis (FSA) flag.  If FSA is on, then the lang server will start reporting `IntelliSense` diagnostics reports for the closed files, and step '3' in the algorithm takes over.  If FSA is off, then the lang server will *NOT* produce any diagnostic reports for closed files.  So all that will exist are the diagnostics produced by the Build-Server, and those will be all that is shown.

Note: this is why we must separate out requests for `Pull Error Diagnostics`, versus `Pull Task/Todo Diagnostics`.  If we do not, then if the lang server produces an `empty diagnostic report` (because it computed zero `Task/Todo Diagnostics`) then that would wipe out any `Build Diagnostics` not in the `Build Only` Diagnostic ID list.  By separating out the requests, we can distinguish "no error diagnostics report at all" and "an empty todo/task diagnostic report".

## Track resultIds per project context
Today we end up always recalculating diagnostics for files with multiple contexts due to how we store resultIds per document and how the client attaches them to requests.  Consider the following scenario

1.  Some change happens and client asks for diagnostics
2.  Client requests doc diags for net6.0 with some initial resultId - we calculate b/c something changed and pass back resultId 'DocumentPullDiagnosticHandler:82'
3.  Client requests doc diags for net5.0 and passes a *null resultid*. we calculate b/c something changed and pass back resultId 'DocumentPullDiagnosticHandler:83'
4.  No changes, but client eventually polls again
5.  Client requests doc diags for net6.0 with *resultId DocumentPullDiagnosticHandler:83* - note that this is the resultId for net5.0 diagnostics. We think there is a mismatch because we stored a different resultId for the net6.0 document (DocumentPullDiagnosticHandler:82) so we recalculate diagnostics.
6.  Client requests doc diags for net5.0 with a null resultId. This means we recalculate diagnostics.

It looks like theres 2 bugs here
1.  ResultIds are getting mixed up between different project contexts leading. It makes sense to me to have them be unique per context, but open to other suggestions
2.  resultids are missing for one of the contexts entirely, so we'll always re-calculate
One alternate solution for 1) is for Roslyn to not care which context a request came from when looking up resultIds, but I think that could potentially break if only one of the contexts changes (e.g. its a linked file and you change one of the project files)

## Separate categories for syntax versus semantic diagnostics

We need to be able to report syntax errors quickly and not have them blocked on semantics being computed.  This is important for the experience to feel responsive.  It's also important to not have compiler diagnostics (normally fast, even for semantics) gated on analyzer diagnostics (which can often be slow).

Similarly, compiler diagnostics should be smart and only reanalyze bodies if a method body edit happened.

**Comment by CyrusNajmabadi** [comment]
tagging @kayle and @hjihong.

**Comment by dibarbet** [comment]
Added another bug to discuss with resultIds for multiple project contexts.

**Comment by arkalyanms** [comment]
@tmat brought up another item to move our internal teams (F#, XAML, TS) off an internal API for custom diagnostic analyzers and move to a newer pull diags based APIs to get document/workspace diagnostics.

**Comment by CyrusNajmabadi** [comment]
Closing out as all work above has been completed by platform and Roslyn.
