### ISSUE TITLE
C# ternary operator suggest

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63867]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-ternary-operator-suggest/10141554)._

---
Now My Code：
if(bool)
{
    FunctionA()；
}
else
{
    FunctionB()；
}

I Wish Code like this：

bool?FunctionA():FunctionB()；

Can it be achieved? Thanks!

---
#### Feedback Bot on 9/7/2022, 08:06 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  LAnguage requests shoudl be made against dotnet/csharplang.  This is likely a dupe there too.
