### ISSUE TITLE
Field and property initialization order optimization (C# compiler)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63864]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Field-and-property-initialization-order-/10112632)._

---
I would like that the C# compiler in future does a field and property initialization order optimization which ensures I cannot read an uninitialized field or property (of a reference type) and which throws a compile error if I attempt something that cannot be brought into an order like a cross-assignment.

The following unit test compiles without any issues but fails when run:

    using Microsoft.VisualStudio.TestTools.UnitTesting;

    namespace FeatureRequest {

        [TestClass]
        public class UninitializedProperty {

            private static string HappyPath { get; } = AlwaysTrue ? "Positive" : "Negative";

            private static bool AlwaysTrue { get; } = true;

            [TestMethod]
            public void CheckHappyPath() {
                Assert.AreEqual("Positive", HappyPath);
            }

        }

    }

In the example above, `HappyPath` reads the uninitialized value of `AlwaysTrue` which then is still `false`. No compiler or analyzer warning occurs. The in my opinion crucial aspect of it is that moving some fields or properties around in my source file seems to be a save thing to do but silently changes the behavior of my code (and maybe it wasn't even a human that moved the code around, it could have been a tool like 'CodeMaid' that brought some uniformity to the solution).

I suggest the C# compiler analyzes the fields and properties which have an assignment. If the compiler detects any dependencies on other properties or fields in the same class it builds a graph and brings them into a logical initialization order and if that is not possible (e.g. because of direct or indirect cross-references), a compile exception is thrown.

I'm not fully familiar with the runtime and compiler internals and therefore just describe from my limited knowledge how I imagine that could be done.
 - I would keep the order how the fields are compiled and laid out and appear in the metadata as is and only change the order of how they are _initialized_.
 - If there are some dependencies detected in static field/property initializations, emit code to the class constructor `.cctor` that performs the initialization in the evaluated order and before any `.cctor`-user-code.
 - If there are some dependencies detected in instance field/property initializations, emit code to two special field initialization methods (say `BeforeBaseInitializer` and `AfterBaseInitializer`) that are hidden from the user and that are called before and after the super constructor is called. Has the field/property initialization no dependencies on the base class, it is written to the `BeforeBaseInitializer`, otherwise to the `AfterBaseInitializer` in the order according to the graph. Only constructors that call a super-constructor (not in constructors that call another `this`-constructor) the methods are called and only non-empty methods are emitted.

This behavior with splitting before and after calling the base constructor allows the base constructor of an abstract class to already read initialized values from the child class.

Love to hear any comments about it.

---
#### Christoph Hafner on 8/5/2022, 05:32 AM: 

(private comment, text removed)
#### Feedback Bot on 8/8/2022, 00:11 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
> I suggest the C# compiler analyzes the fields and properties which have an assignment. If the compiler detects any dependencies on other properties or fields in the same class it builds a graph and brings them into a logical initialization order and if that is not possible (e.g. because of direct or indirect cross-references), a compile exception is thrown.

This would be a breaking change in the language.

If you would like this, it could be done as an optional analyzer.
