### ISSUE TITLE
String.Empty vs string.Empty

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63866]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StringEmpty-vs-stringEmpty/10113709)._

---
Hi Guys,

While C#'ing, every time I type string.Empty, tabbing or spacing will result on the unwanted String.Empty. Sad face :(

---
#### Feedback Bot on 8/8/2022, 07:45 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Will need more info from the user:

![NoRepro](https://user-images.githubusercontent.com/4564579/189236397-cf88082c-6680-4152-b8b6-af50baf5139d.gif)
