### ISSUE TITLE
Find References additional filter options

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63875]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-References-additional-filter-option/10064116)._

---
Currently Find References has a “Kind” column that denotes if that reference is Read or Write. This helps filter down large lists of references however I find that it is still difficult to find specific usage of a reference, additional filtering options could help me answer questions like “how is this reference being used to modify\\change a variable” as opposed to “how is this reference being used in an conditional” as I find it difficult to visually parse out that kind of information when I’m using Find References.

A specific example is I was recently doing Find References on an enum value because I wanted to determine if a variable was ever being set to that value, but that information was lost in a list if conditionals where that enum value was being checked against.

---
#### Feedback Bot on 6/7/2022, 08:02 PM: 

(private comment, text removed)
#### Mika Dumont [MSFT] on 7/29/2022, 02:34 PM: 

(private comment, text removed)
#### Feedback Bot on 8/10/2022, 00:20 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
I feel like if the user wants to see hoe the value is used, 'track value' is the right feature for that.  I don't feel like 'kind' is appropriate here as there are enumerable ways a variable may end up being used in larger and larger contexts.
