### ISSUE TITLE
Support for static using?

### ISSUE THREAD

**Issue by chrisfoster78** [dotnet/roslyn#6387]
It would be nice to have support for "static using".

Maybe this could be added to AddNamespaces e.g.
```c#
ScriptOptions.Default.AddNamespaces("static System.Math")
```

**Comment by amcasey** [comment]
@chrisfoster78 Did you try passing `"System.Math"`?  I think it may just be a confusingly named API, though @tmat could confirm.

**Comment by tmat** [comment]
The API has been renamed to AddImports. And yes, AddImports("System.Math") should work.

**Comment by amcasey** [comment]
@chrisfoster78 please ping us if you're still having problems with this.
