### ISSUE TITLE
For C#, the compiler should allow returning a single named value and suggest the name for a local variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63870]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/For-C-the-compiler-should-allow-return/10128271)._

---
When returning a single value from a function, it might be useful to give the return value a suggested name, which could be used automatically by the editor, for the code calling the function. For example, the following function

`public (PageResult? pageResult) Identify(OcrPage oPage);`

`var pageResult = Identify(oPage); // calling the function`

Suggests that the returned value should be named as `pageResult`.

However, this fails to compile, as I'm returning a single value, not multiple values.

This can currently be done when returning multiple parameters, the following compiles:

`public (TemplateResult? tResult, bool wasSuccessful) Identify(OcrPage oPage);`

`var (tResult, wasSuccessful) = Identify(oPage);`

This is mostly to avoid issues where I assigned the wrong name, for example, I created a variable for a document result instead of a page result.

`var documentResult = Identify(oPage);`

I did not notice the name was wrong until trying to understand the code later. The code actually compiled fine as the compiler has no idea what the variable being returned is being used for.

So it might be useful to give a warning also for the misnaming when returning multiple values, or to automatically insert the return values when calling the code while editing.

---
#### Feedback Bot on 8/23/2022, 11:33 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
i believe this is a request to replace a tuple-variable with deconstruction.  That seems reasonable as something to offer.
