### ISSUE TITLE
Where is the option that "Always on" Renaming Filename when renaming symbol?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63871]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Where-is-the-option-that-Always-on-Ren/10119646)._

---
Until a few months ago, the option to rename filename when refactoring class names was always on.

One day after patching to the latest version, the option was turned off. I manually turned it on every time I used it, but that state was reset by restarting visual studio.

The alt + f hotkey is pointless. This is because the File menu in the main menu bar opens instead of Rename symbol's &file on.

If this change is a mistake, it will be fixed soon, and if it was intentional, I would expect that a new option would be added, but now, months later, I don't want to bother anymore.

I've always been good at using vs and I'm always amazed by the amazing features. Again, looking forward to some good fixes this time around.

---
#### Feedback Bot on 8/15/2022, 01:33 AM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
@ryzngard

**Comment by ryzngard** [comment]
https://github.com/dotnet/roslyn/issues/63810
