### ISSUE TITLE
Provide a Class Implementation for an Interface on (ctrl+.) 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63874]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-a-Class-Implementation-for-an-In/10091306)._

---
Basically provide an options to generate a class that implement the interface targeted by the (ctrl+.) command.

---
#### Feedback Bot on 7/11/2022, 00:20 AM: 

(private comment, text removed)
#### Mika Dumont [MSFT] on 7/29/2022, 02:28 PM: 

(private comment, text removed)
#### Amine Benhebba on 8/2/2022, 04:15 AM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
This request is for when you are on an interface definition and press ctrl+. to offer an option to create a type implementation for that interface.
![image](https://user-images.githubusercontent.com/46729679/189240536-2ae86d75-84d3-4b29-8b36-82dfeaf4b27c.png)

**Comment by kimsey0** [comment]
It seems like this should basically just be generating an empty class with a name derived from the interface name, then invoking https://github.com/dotnet/roslyn/blob/36c6032607c1ce370594ba90b5ef2bab7b0101a3/src/Features/Core/Portable/ImplementInterface/IImplementInterfaceService.cs#L16
Right?

**Comment by CyrusNajmabadi** [comment]
I'm not seeing a huge need for this.  One can just write:

```c#
class C : ITheInterface
{
}
```

And then just invoke "implement interface".  Absent lots of customer demand here i don't think we should make any changes here.  Preemptively closing out.

**Comment by kimsey0** [comment]
OK. I don't know how or if it usually influences the direction of Roslyn, but this is a feature that's available in ReSharper, CodeRush, and JustCode (and which I find quite useful there).

**Comment by CyrusNajmabadi** [comment]
Generally speaking, parity on everything every other tool does it not a goal.  All these tools have different perspectives on what to offer and how.  What would change things here is if we had consistently seen a fair amount of feedback on our current solution being insufficient over the years and people strongly gravitating towards a different model for how to do these sorts of operations.
