### ISSUE TITLE
Auto Complete for missing interface properties/methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63872]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-Complete-for-missing-interface-prop/10116607)._

---
It would be quite helpful if the C# intellisense in Visual Studio was able to autocomplete unimplemented interface or abstract parent class members as you start typing.
The use case for this is lets say you are implementing a new class that implements an interface. You can right click on the interface name at the top of the class and use the Quick actions to set up default implementations of all of the missing members, which is helpful. But some times I'd much rather be able to simply start typing stuff and have intellisense make suggestions of the missing elements based on access member modifier, type, or partially typed in name of the item. This is particularly valuable when you have a class that already has implemented the interface and then you add a new element to it and are now needing to go through all classes that implement that interface to implement it on each one. Often using the Quick action to do this puts the new elements in places I don't want them forcing me to go hunt for all NotImplementedExceptions and reorganize everything. Thanks for considering this.

---
#### Feedback Bot on 8/11/2022, 02:51 AM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
May be worth considering adding snippets for this or code generation refactorings to the completion list similar to what IntelliCode does today for add param and generate constructor.

**Comment by CyrusNajmabadi** [comment]
We already do the above for overrides.  Expanding out to interface impls would be reasonable IMo.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
