### ISSUE TITLE
PR Test Failure: "Deterministic" parameter not supported by "Csc" task on unrelated IDE change.

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6388]
*PR: https://github.com/dotnet/roslyn/pull/6382*
*Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/612/*
**Issue 1: MSBuild Error**
error MSB4064: The "Deterministic" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [d:\j\workspace\roslyn_prtest_win_dbg_unit64\src\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyntaxGenerator.csproj]

**Comment by davkean** [comment]
Dup of #6211
