### ISSUE TITLE
Feature request: Add generators execution times to `/reportanalyzer`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63887]
`/reportanalyzer` currently reports analyzer execution times. It would be awesome if it can include generators as well.

**Comment by jasonmalinowski** [comment]
@chsienki Didn't we do this already?

**Comment by Youssef1313** [comment]
Ah, thanks @jasonmalinowski 

Found the PR: https://github.com/dotnet/roslyn/pull/61661
It's recent enough that I wasn't seeing it on the compiler version I'm using.

Thanks again!

**Comment by chsienki** [comment]
Yup. @jaredpar added it in #61611
