### ISSUE TITLE
Deprecate usage of Workspace in TextLoader (breaking change)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#63888]
## Background and Motivation

Eliminate dependency on `Workspace` from `TextLoader`. `TextLoader` instances are held on by an immutable `Solution` snapshot and we want to remove all back-references to mutable `Workspace` from the snapshot.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis;

+ public readonly struct LoadTextOptions : IEquatable<LoadTextOptions>
+ {
+     public SourceHashAlgorithm ChecksumAlgorithm { get; }
+     public LoadTextOptions(SourceHashAlgorithm checksumAlgorithm)
+     public bool Equals(LoadTextOptions other)
+     public override bool Equals(object? obj)
+     public static bool operator ==(LoadTextOptions left, LoadTextOptions right)
+     public static bool operator !=(LoadTextOptions left, LoadTextOptions right)
+     public override int GetHashCode()
+     public override string ToString()
+ }

class TextLoader
{
+ [Obsolete]
+ public virtual Task<TextAndVersion> LoadTextAndVersionAsync(Workspace? workspace, DocumentId? documentId, CancellationToken cancellationToken);

- public abstract Task<TextAndVersion> LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken);

+ public virtual Task<TextAndVersion> LoadTextAndVersionAsync(LoadTextOptions options, CancellationToken cancellationToken);
}

class FileTextLoader
{
+ [Obsolete]
+ protected virtual SourceText CreateText(Stream stream, Workspace? workspace);

- protected virtual SourceText CreateText(Stream stream, Workspace workspace);

+ protected virtual SourceText CreateText(Stream stream, LoadTextOptions options, CancellationToken cancellationToken);
}
```

## Usage Examples

Implemented by https://github.com/dotnet/roslyn/pull/63616

## Risks

UPDATE: Added LoadTextOptions parameter.

**Comment by 333fred** [comment]
### API Review

* Uneasy shipping a component that has a StackOverflow built-in by-design
    * What if we just documented that `Workspace` is always `null`?
    * Could write a bit of reflection to detect this cycle and fail in a more helpful manner
* We could add a new analyzer for this particular case
* Users who can call this method are generally in an advanced scenario where they're implementing a host, as you can't get one of these out from the compilation. We think it's ok to make the old version throw
* It would be good to have an analyzer to indicate to the user they should override the new LoadText method, so we can eventually remove the old version and make the new one abstract.

**Conclusion**: The API is approved. The new version of `TextLoader.LoadTextAndVersionAsync` will forward to the old version, and the default implementation of the old version will throw. We we would like to have an analyzer to inform users they must override the new method, but this is not required for shipping the API.

**Comment by tmat** [comment]
@333fred @AlekseyTs @dotnet/roslyn-api-owners Update the new methods with another parameter that allows us to flow in checksum algorithm.

**Comment by 333fred** [comment]
### API Review

* Using the IDE indicated that `LoadTextOptions` would be good to include as well.
* Calling the new API on a loader that has not updated will drop the options. Is that ok?
    * Can also happen if the loader can't reload the original binary representation
    * Could we make `IsReloadable` public, and have it return `false` by default to determine whether or not the options can be dropped?
    * Maybe we just document that the `option`s can be ignored by the loader you're working with?

**Conclusion**: We'll flesh out the documentation for the options parameter.

**Comment by CyrusNajmabadi** [comment]
@tmat can you take next steps on this, or close out?
