### ISSUE TITLE
Default Parameter Values Not Supported By QuickInfo for Anonymous Delegate Types

### ISSUE THREAD

**Issue by adamperlin** [dotnet/roslyn#63890]
Fairly straightforward, but there is inconsistency for quick info in the following cases:

```csharp
$$var lam = (int x = 42) => x;
``` 
Produces
```
 delegate int <anonymous delegate>(int)
``` 
with *no* default parameter value in the signature.
Hovering over the local variable `lam` itself, as in
```csharp
var la$$m = (int x = 42) => x;
``` 
produces 
```
(local variable) 'a lam
Types:
    'a is delegate int (int = 42)
```
Ideally these displays could be more unified, and at the very least a default parameter should be present in both.

**Comment by CyrusNajmabadi** [comment]
we really should cleanup the names here.  Our syntax for normal local functions is just `ret_type name(param_type param_name ...)`.  So we should drop the `delegate` and just say `ret_type <anonymous function>(param_type param_name, ...)`.

I agree that the display for the quick info should follow that as well.
