### ISSUE TITLE
Allow [module: RefSafetyRules] attribute in source

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#63904]
There are [several differences](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#refsafetyrulesattribute) in the ref safety rules and ref parameter scope between C#7.2 and C#11:

> 1. unscoped `ref`/`in`/`out` parameters may escape a method invocation as a `ref` field of a `ref struct` in C#11, not in C#7.2
> 1. `out` parameters are implicitly scoped in C#11, and unscoped in C#7.2
> 1. `ref`/`in` parameters to `ref struct` types are implicitly scoped in C#11, and unscoped in C#7.2

The differences in C#11 are intended to allow ref fields in ref struct types, with minimal breaking changes to existing code.

To improve compatibility further, for source modules that are not using ref fields, we should consider allowing the module to explicitly use C#7.2 ref safety rules even with language version 11 or .NET 7.

Specifically, we could allow a [`RefSafetyRulesAttribute`](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#refsafetyrulesattribute) to be specified in source, to indicate to the compiler that _methods defined in the module_ should be compiled with C#7.2 ref safety rules.

```csharp
[module: RefSafetyRules(7)]
```

**Comment by jaredpar** [comment]
Note: this is not a statement of "we will do this" but that "we could do this". At this point we don't feel that the added complexity is worth it. But if the compat changes we introduced end up being a higher burden than we anticipated it is something we would consider.
