### ISSUE TITLE
Proposal: explicit virtual method overriding

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/roslyn#6390]
# Background
C# provides syntax to explicitly implement an interface method. It would be nice if we could use the syntax to explicitly override virtual methods as well.

# Problem
Supposed we have a situation like this:

```csharp
abstract class Foo
{
  public abstract Foo Related { get; }
}

abstract class Bar : Foo
{
  public override Foo Related { get { return BarRelated; } }
  public abstract Bar BarRelated { get; }
}

class Baz: Bar
{
  public override Bar BarRelated { get { return ...; } }
}
```

The purpose of the BarRelated property is to mandate that whenever something derives from Bar, the Related property will be of a type deriving from Bar (i.e. more specialized).

Having two properties with the same thing (the only difference being the static type) looks pretty awkward though and makes the usage confusing (it's quite likely that consumers with keep accessing "Related" and cast to Bar).

# Proposal
Add explicit overrides of methods:

```csharp
abstract class Foo
{
  public abstract Foo Related { get; }
}

abstract class Bar : Foo
{
  // Provides explicit implementation for the Related property on Foo
  Foo Foo.Related { get { return Related; } }

  // Uses new keyword to hide Related property on Foo and introduce a new one with the same name
  public new abstract Bar Related { get; }
}

class Baz: Bar
{
  private Baz _related;
  public override Bar Related { get { return _related; } }
}
```

**Comment by MichalStrehovsky** [comment]
cc @davidwrighton

**Comment by HaloFour** [comment]
Would this be terribly necessary if C# would support covariant return types (#357)?  That seems like it would at least cover your use case.

The CLR does already support explicit overrides in this manner, as long as the signature matches exactly (including the return type).  The method accessibility and name could be anything so the compiler could emit a private method just as it does with explicit interface implementation.

**Comment by MichalStrehovsky** [comment]
Yes, seems like "covariant return types" would cover my use case. The syntax proposed here gives more control over what's in the base override. It's up to a debate whether more control is a good thing.

**Comment by gafter** [comment]
@MichalStrehovsky If you have no use cases other than covariant returns, I think we'd prefer to do that.

**Comment by orthoxerox** [comment]
You might need that if you ever implement multiple inheritance. When you inherit from two classes that have the same name and signature on two otherwise unrelated methods, you will have to override one or both methods explicitly so there's no name conflict.

**Comment by gafter** [comment]
@orthoxerox OK, I can see us adding this if/when we add mixins.

**Comment by MichalStrehovsky** [comment]
@gafter Actually, after reading about all the problems around covariant returns, I would prefer this syntax.

It makes the fact that we're dealing with two methods more explicit (the compiler doesn't have to try to hide it), sounds easier to implement, and avoids the perf-killing cast that the proposed attribute-based covariant returns have. A cast is *orders of magnitude* more expensive than a virtual call, especially if we end up with variant casts.

**Comment by HaloFour** [comment]
@MichalStrehovsky 

> A cast is orders of magnitude more expensive than a virtual call, especially if we end up with variant casts.

Where are you getting that from?  My experience is that a virtual call is at least twice as slow as a cast between reference types.  Unboxing value types is definitely slower but value types couldn't be covariant so that wouldn't matter.

The performance-killing aspect of the covariant call isn't the cast, it's the fact that it's making a second call after the first virtual call.  This proposal wouldn't avoid that.

**Comment by gafter** [comment]
@MichalStrehovsky I'm not aware of any need or plan to emit cast instructions as part of the implementation of covariant returns. An implicit reference conversion doesn't require a cast.

**Comment by MichalStrehovsky** [comment]
@gafter @HaloFour I'm referring to the attribute-based implementation that floats around the other proposal:

```csharp
public class Bar : Foo
{
    [return: System.Runtime.CompilerServices.ReturnType(typeof(string))]
    public override object Baz()
    {
        return string.Concat(base.Baz(), "buzz");
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        Bar bar = new Bar();
        string result = (string)bar.Baz();
        Console.WriteLine(result);
    }
}
```

Notice the cast at the call site. Casting is more expensive because we need to walk the inheritance chain or interface lists and for variant casts we even need to explode generic types into components and perform assignability checks on them.

A virtual call is two instructions.

**Comment by gafter** [comment]
@MichalStrehovsky Yes, we definitely would not do that thing with attributes and casting.
