### ISSUE TITLE
Extract local function puts function in disabled section

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#63917]
**Version Used**: VS 2022.4p1

**Steps to Reproduce**:

```cs
void M()
{
    Console.WriteLine("test1");
    Console.WriteLine("test2");
#if DEBUG
    Console.WriteLine("test3");
#endif
}
```

Perform an extract local function on the first line in `M`, the `Console.WriteLine("test1")` call.

**Expected Behavior**:

```cs
void M()
{
    NewMethod();
    Console.WriteLine("test2");
#if DEBUG
    Console.WriteLine("test3");
#endif

    static void NewMethod()
    {
        Console.WriteLine("test1");
    }
}
```

**Actual Behavior**:

```cs
void M()
{
    NewMethod();
    Console.WriteLine("test2");
#if DEBUG
    Console.WriteLine("test3");

    static void NewMethod()
    {
        Console.WriteLine("test1");
    }
#endif
}
```

**Comment by 333fred** [comment]
Likely important note for the repro: I'm in Debug mode when I'm doing these steps, so the section is actually active. It just breaks when you switch modes.

**Comment by CyrusNajmabadi** [comment]
Ok to fix this if the complexity of the solution is manageable.
