### ISSUE TITLE
CS0657 diagnostic suppressor is not reflected in IDE/errors (but it is in build output)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#63923]
> **Note**: this is big issue for the (Microsoft) MVVM Toolkit, as we need this to work properly for https://github.com/CommunityToolkit/dotnet/issues/413, which I plan on shipping in the 8.1 release, which will align with the 17.4 release as well. If this is confirmed to be a bug, would it be possible to slip a fix for this in time for 17.4? Otherwise customers will have to manually suppress warnings everywhere, which would be a really really bad user experience for them. cc. @chsienki

**Version Used**: VS 17.3.3

**Steps to Reproduce**:

1. Define the following diagnostic suppressor:
```csharp
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DiagnosticSuppressorAnalyzers
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class ObservablePropertyAttributeWithPropertyTargetDiagnosticSuppressor : DiagnosticSuppressor
    {
        public static readonly SuppressionDescriptor PropertyAttributeListForObservablePropertyField = new SuppressionDescriptor(
            id: "MVVMTKSPR0001",
            suppressedDiagnosticId: "CS0657",
            justification: "Fields using [ObservableProperty] can use [property:] attribute lists to forward attributes to the generated properties");

        public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions => ImmutableArray.Create(PropertyAttributeListForObservablePropertyField);

        public override void ReportSuppressions(SuppressionAnalysisContext context)
        {
            foreach (Diagnostic diagnostic in context.ReportedDiagnostics)
            {
                context.ReportSuppression(Suppression.Create(PropertyAttributeListForObservablePropertyField, diagnostic));
            }
        }
    }
}

```
2. Reference the analyzer above in a blank project
3. Paste the following code:
```csharp
namespace DiagnosticSuppressorRepro;

public class SomeClass
{
    [property: Test]
    [property: AnotherTest]
    public string? Name;
}

internal class TestAttribute : Attribute
{

}

internal class AnotherTestAttribute : Attribute
{

}
```
4. Build the project

Full standalone repro: [DiagnosticSuppressorRepro.zip](https://github.com/dotnet/roslyn/files/9543149/DiagnosticSuppressorRepro.zip)

**Expected Behavior**:

No warnings should show up in either the build output, nor the IDE nor the errors list.

**Actual Behavior**:

Warnings are suppressed in the build output, but still show up in the IDE, solution explorer and errors list.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/10199417/189540726-9867a70f-52b9-4a00-aea0-b0c5ca71bd1b.png">

**Comment by Youssef1313** [comment]
cc @mavasani

**Comment by mavasani** [comment]
Thanks @Youssef1313. There seem to be couple of issues here:

1. Core issue: Bug in diagnostic equality for [CompilerDiagnostic](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs#L112-L115) type reported by our internal `CompilerDiagnosticAnalyzer`. I'll send a PR out to fix this soon, which should resolve this issue.
2. The above bug leads to the below exception being thrown when the diagnostic suppressor reports a suppression: https://github.com/dotnet/roslyn/blob/c71fa5419aa035a8d76c8a82387353e3892180a7/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1606-L1613 However, this exception is not being reported as an AD0001 exception diagnostic in the IDE and is silently getting swallowed. I'll file a separate tracking issue for this bug.

**Comment by Sergio0694** [comment]
@mavasani thank you for the quick fix!
Just to clarify, as I see the PR in the "Next" milestone: will this be included in VS 17.4?

**Comment by mavasani** [comment]
@Sergio0694 Yes, that is correct.

**Comment by Sergio0694** [comment]
Sweet, thank you! 😄
