### ISSUE TITLE
Exceptions from diagnostic suppressors are not being reported in the IDE as AD0001 diagnostics

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#63939]
Thanks @Youssef1313. There seem to be couple of issues here:

1. Core issue: Bug in diagnostic equality for [CompilerDiagnostic](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs#L112-L115) type reported by our internal `CompilerDiagnosticAnalyzer`. I'll send a PR out to fix this soon, which should resolve this issue.
2. The above bug leads to the below exception being thrown when the diagnostic suppressor reports a suppression: https://github.com/dotnet/roslyn/blob/c71fa5419aa035a8d76c8a82387353e3892180a7/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1606-L1613 However, this exception is not being reported as an AD0001 exception diagnostic in the IDE and is silently getting swallowed. I'll file a separate tracking issue for this bug.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/63923#issuecomment-1243612041_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
