### ISSUE TITLE
Assume Bug on macOS while building

### ISSUE THREAD

**Issue by akoconx** [dotnet/roslyn#63936]
**Version Used**: 
Visual C# Compiler version 4.3.0-3.22365.10 (dd078d4e)
dotnet 6.0.400
CPU: Apple Silicon ARM m1 pro
macOS Monterey 12.5.1

**Steps to Reproduce**:
I have a Project of type _Sdk="Microsoft.NET.Sdk.Web"_ and while building I get following error:

_CompilerServer: server failed - server rejected the request 'Error writing build request: Specified argument was out of the range of valid values. (Parameter 'Request is over 5MB in length')'_ 

**Expected Behavior**:
Should build Project

**Actual Behavior**:
_CompilerServer: server failed - server rejected the request 'Error writing build request: Specified argument was out of the range of valid values. (Parameter 'Request is over 5MB in length')'_

**Comment by 2340958** [comment]
Size has been increased here: https://github.com/dotnet/roslyn/issues/52761

**Comment by akoconx** [comment]
Some older packages caused the problem and in the end clearing nuget helped using following command:
dotnet nuget locals all --clear
