### ISSUE TITLE
Add supporting for enumerating Embedded Resources for source generators

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/roslyn#63941]
## Background and Motivation

These days I'm trying to create a source generator used to generating strong-typed resource string wrapper for ASP.NET Core project, while unfortunately, I found it is currently not possible to enumerate the RESX files using code generator API. 

More specifically, I've tried 2 different manner while neither of them work:

- Firstly, I tried to use the `context.AdditionalFiles` to locate them, but none of RESX files appear in the collection, maybe the compiler did not consider Embedded Resource as "additional" files. 
- Secondly, I tried to use `MetadataReader` to extract the embedded resources in the target assembly, however,  `context.Compilation.SourceModule.GetMetadata()` returns `null` and thus no further action can be taken. I guess that metadata generation process may happen after compilation is done, so these information are not yet available during this step.

A Visual Studio custom file generation tool may meet my requirement, while making a visual studio extension is much more complex than code generators, and its usage are also limited to Visual Studio, which means other coding enviroments such as VSCode cannot benefit from it.

Maybe there are also some walkarounds just like locating the project file and then enumerating source RESX files using file system API, while I don't think this is a recommended way to do so.

## Proposed API

Since the metadata for the compilation source may be generated different from an existing module file, it may be better to add an individual API to read it directly from the `Compilation` instance like below:

```diff
namespace Microsoft.CodeAnalysis.Compilation
{
     public class Compilation
     {
+        public ModuleMetadata GetCompilationMetadata();
     }
```

## Usage Examples

(omitted)

## Alternative Designs

Alternatively, the code generation context may consider to provide the project structure (just like the Visual Studio SDK does) to meet requirements related with project level data such as this issue, just like below:

```diff
namespace Microsoft.CodeAnalysis
{
     public class GeneratorExecutionContext
     {
+        public Project GetProject();
     }
```

## Risks

TBC.

**Comment by jaredpar** [comment]
> Firstly, I tried to use the context.AdditionalFiles to locate them, but none of RESX files appear in the collection, maybe the compiler did not consider Embedded Resource as "additional" files.

The compiler knows nothing about resx files. That is an artifact of MSBuild that is processed at a layer above the compiler and some of the resulting artifacts end up passed to the compilation. If a generator or analyzer wanted to process resx files they would need to pass them as additional files. 

> Maybe there are also some walkarounds just like locating the project file and then enumerating source RESX files using file system API, while I don't think this is a recommended way to do so.

That is not allowed in generators. Yes we can't stop you from enumerating the file system. However it **will** cause issues when run inside of Visual Studio as you end up doing IO on threads that is not meant for IO. It will also result in bad build semantics as MSbuild will not re-run compilation when the files you enumerate have changed. 

@chsienki, @RikkiGibson

**Comment by papaneko** [comment]
> However it will cause issues when run inside of Visual Studio as you end up doing IO on threads that is not meant for IO

I though overlapped IO was automatically handled by the .Net FileStream?
