### ISSUE TITLE
function and methods custom have different color.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63954]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/function-and-methods-custom-have-differe/10124541)._

---
if a function or method is an internal from the https://docs.microsoft.com/en-us/dotnet/api/system.string.substring?redirectedfrom=MSDN&view=net-6.0#overloads
website

then I'd like to have it a (slightly) different color text then when it is a custom created method in the visual studio editor.

---
#### Feedback Bot on 8/19/2022, 01:06 AM: 

(private comment, text removed)

**Comment by mikadumont** [comment]
@JoeRobich I believe you added an option for this in `fonts and colors` but should we consider making this the default option?

**Comment by CyrusNajmabadi** [comment]
Is this asking for metadata vs source symbols to have different colors?

**Comment by JoeRobich** [comment]
@mikadumont  I do not believe we have such a classification. I also think we would need a better description of how this proposed classification should work.

**Comment by arkalyanms** [comment]
@JoeRobich You might want to reopen to the feedback ticket to extract more info on this.
