### ISSUE TITLE
Format .editorConfig in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63952]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Format-editorConfig-in-Visual-Studio/10113054)._

---
Currently, format document does not work in Visual Studio. These two features are needed:

1. Turn this:

```
csharp_new_line_before_finally = true
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
```

into this to put setting values in the same position:

```
csharp_new_line_before_finally                                                                               = true
csharp_new_line_before_else                                                                                  = true
csharp_new_line_before_catch                                                                                = true
```

2.
Allow sections and the settings within the section to be sorted.

---
#### Feedback Bot on 8/7/2022, 11:54 PM: 

(private comment, text removed)

**Comment by arkalyanms** [comment]
@jmarolf would you check if this would come from us or the platform?

**Comment by CyrusNajmabadi** [comment]
Closing out.  We are not hte formatting engine for non-c#/vb files.  If platform wants to take that on, they can.
