### ISSUE TITLE
AbstractEmbeddedLanguageBraceMatcher.FindBracesAsync should use frozen partial semantics

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#63958]
Currently `AbstractEmbeddedLanguageBraceMatcher.FindBracesAsync` uses a semantic model with full semantics, which means brace highlighting won't show up until source generators are completed. This should be updated to use non-blocking frozen partial semantics instead.

Identified in [AB#1613387](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1613387)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
