### ISSUE TITLE
Global option to disable format on paste

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63955]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Global-option-to-disable-format-on-paste/10119289)._

---
I don't find format on paste helpful and after getting tired of hitting control-z after every paste I disabled it... or thought I did, but only in C#, and then I went about finding the other half dozen formatters I use and disabling it there as well. It would be nice to have a global option to disable it in all formatters.

---
#### Feedback Bot on 8/15/2022, 01:24 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you move to platform as this is a request for a common optino that goes across all languages.

**Comment by arkalyanms** [comment]
Closing in favor of the reopened feedback ticket.
