### ISSUE TITLE
Code cleanup unable to add lines in between elements when required by style (SA1516)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63950]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-cleanup-unable-to-add-lines-in-betw/1657290)._

---
[severity:It's more difficult to complete my work]
ReSharper has the ability when running a refactor pass to automatically add empty lines when required by SA1516. There is a manual quick action to do this but no way to do it in bulk using "Code cleanup".

---
#### Feedback Bot on 2/8/2022, 10:03 PM: 

(private comment, text removed)
#### Feedback Bot on 2/15/2022, 06:17 PM: 

(private comment, text removed)
#### Feedback Bot on 6/2/2022, 00:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as external.  Stylecop analyzers are their own thing . And if they want to format in a particular way, they need to do so,
