### ISSUE TITLE
Navigate selected symbol's usage in current file using "Next"/"Previous" buttons (VisualAssistX feature)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63953]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Navigate-selected-symbols-usage-in-curr/10131373)._

---
### Description
VisualAssistX (plugin for Visual Studio) allows to navigate by every usage of currently selected symbol in opened file jumping forward or backward by clicking "Next" or "Previous" button. _(Symbol = variable/method/type under current caret position.)_ Here are these two buttons on VisualAssistX toolbar:

![image.png](https://aka.ms/dc/image?name=B612a125c622c42f0a5988331331c399b637970364303384788_20220825-180028-image.png&tid=612a125c622c42f0a5988331331c399b637970364303384788)

_(Sometimes I'm checking if this feature exists in new Visual Studio Preview release. I still had not found it. I'll be grateful for a hint if it is exist and how it is named.)_

I'm using this feature _very frequently_ when working within a separate class/file (_in C# or C++_) and, especially, when _inspecting a code_ for some behaviour or just researching somebody's code.

### Current behaviour
Suggested feature is _much_ faster and comfortable (for me) than current typical Visual Studio scenario:
- click "Find all references",
- then see what was found,
- then doubleclick,
- _(only now I can inspect code),_
- and then go to "Find all references" again and seek next position in list etc...
**... too much interactions.**

### Additional feature info
_"Find all references"_ window is less usable because _switches_ my attention, _eats_ my visual space and _needs_ for additional clicks. I need just jumping from one position to another, nothing else.

Suggested feature's context is limited by _curently opened file_.

And it should be much more comfortable when it is allowed to assing **shortcut keys** to "Next" / "Previous" navigation commands.

---
#### Feedback Bot on 8/25/2022, 08:29 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you move to platform?

**Comment by sharwell** [comment]
The **Edit.PreviousHighlightedReference** (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>&uarr;</kbd>) and **Edit.NextHighlightedReference** (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>&darr;</kbd>) commands already do this. If you want a button instead of the keyboard shortcut, it should be possible to add these existing commands to one of the menus and/or toolbars.
