### ISSUE TITLE
'Frozen Partial' semantics need to be reconciled with OOP and SourceGEnerators

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#63968]
Currently, 'frozen partial' semantics have no effect in OOP.  That's because teh OOP workspace effectively says 'i do not support thsi concept'.  This is problematic as 'frozen partial' is our mechanism to allow features to say things like "do not bother blocking on running SGs for this feature, i'm ok with whatever data is computed so far".  This means we have an issue when such a feature wants to be fast, but also wants to run OOP.  

There is also a conceptual problem here.  Say a feature says "i want to run fast, and not bother running all sg work", but it then executs on some SG document.  If it calls over to OOP and OOP does not run all SGs, it may not have the document hte user is asking for.

We need to reconcile what is going here and what we think the right model is where we have two hosts and potentially different computation (and subsets of computation) running in both.

**Comment by jasonmalinowski** [comment]
So in the case of frozen partial semantics we can probably just try syncing over the generated documents we have from in-proc -- if they're already there we don't have to sync anything, and if they're not there it's hopefully cheaper. It might not be too hard to do as an experiment.

**Comment by CyrusNajmabadi** [comment]
Closing out.  OOP supports frozen partial now.  And the plan is to actually sync the generated docs from the OOP side back to the host side.
