### ISSUE TITLE
Deprecate `Microsoft.Net.Compilers` on NuGet

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#63973]
- [ ] This package was deprecated but doesn't show as deprecated on NuGet.

- [ ] In [this doc](https://github.com/dotnet/roslyn/blob/main/docs/compilers/Compiler%20Toolset%20NuPkgs.md#microsoftnetcompilers), it's noted that this package:
    > will not be produced anymore after the 3.6.0 release. 

    However, the latest version is 4.2.0, so it seems it was produced after 3.6.0? Was that unintentional and fixed (possibly in https://github.com/dotnet/roslyn/pull/60839)? In this case, should the doc be updated to 4.2.0 instead of 3.6.0?

The first point about deprecation on NuGet is the important part of the issue though :)

**Comment by jaredpar** [comment]
Marked as deprecated today.
