### ISSUE TITLE
Problem with "potential fix" suggestions being not displayed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#63974]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-with-potential-fix-suggestions/10129795)._

---
[severity:It bothers me. A fix would be nice]
.cs file is opened and I want to generate the missing properties by using the suggested fixes, by clicking on the small popup that appears over the "squiggled" texts. However nothing happens, clicking on the suggestion hyperlink does nothing either. 

Please check the attached video for the example.

Repro code (issue occurs for the squiggle on `Property` and `Property2`):

```cs
namespace Program
{
    public class Item
    {
        protected static T CreateItem<T>(string something)
            where T : Item, new()
        {
            var viewModel = new T
            {
                Property = something?.GetHashCode(),
                Property2 = something?.GetHashCode(),

            };

            return viewModel;
        }
    }
}
```

---
#### Feedback Bot on 8/24/2022, 08:10 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/30/2022, 04:08 AM: 

(private comment, text removed)
#### kevin.drapel on 8/31/2022, 02:47 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/30/2022, 04:09 AM: 

(private comment, text removed)
#### kevin.drapel on 8/31/2022, 02:51 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/6/2022, 04:33 AM: 

(private comment, text removed)
#### Feedback Bot on 9/12/2022, 00:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback.
