### ISSUE TITLE
Consecutive keystrokes in Interactive Window should be a single undo action

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#6397]
When typing in interactive window, each keystroke is a separate action called `Text Buffer Change` in undo/redo history. We expect consecutive keystroke as a single undo action called `Insert Text`.

![type_history](https://cloud.githubusercontent.com/assets/788783/10799814/0bcab616-7d6c-11e5-85bc-8262b176f332.jpg)

**Comment by genlu** [comment]
@amcasey Could you verify this please?

**Comment by amcasey** [comment]
Verified that there is a single "Insert Text" item in the undo list.
