### ISSUE TITLE
API Request: TypeSymbolExtensions 

### ISSUE THREAD

**Issue by OmerRaviv** [dotnet/roslyn#64]
Forking this feature request from #16 

Original post: https://github.com/dotnet/roslyn/issues/16#issuecomment-70846421 by @MrJul

Pertinent APIs: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp/Symbols/TypeSymbolExtensions.cs,8f632696b9da5eba

In my team, I've seen different developers copy-paste portions of ITypeSymbolExtensions into our own project (e.g. `IsNullableType`, `GetNullableUnderlyingType` , `GetBaseTypes` ), which is a shame - these methods are a convenience I'm sure many other people will find useful as well.

**Comment by AdamSpeight2008** [comment]
I could add them to RoslynExts.

**Comment by dpoeschl** [comment]
Stackoverflow user "Mac" is requesting to use methods from a similar API, INamedTypeSymbolExtensions. http://stackoverflow.com/questions/28234052/finding-all-class-declarations-than-inherit-from-another-with-roslyn

**Comment by wwwlicious** [comment]
Thanks David, I've updated the post with the solution I hacked out, not sure if it is using bad practices though so if there is a ready made internal api for this it would be useful.

**Comment by wwwlicious** [comment]
any progress on this?

**Comment by pakdev** [comment]
Apparently Microsoft's other project (Roslyn Analyzers) also [duplicates some of these extensions](https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs).
