### ISSUE TITLE
Sometimes a block of comment is not collapsable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64001]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/266666/sometimes-a-block-of-comment-is-not-collapsable.html)._

---
After updating to 15.7.3 I noticed that a block of comments does not have a + sign in front of them allowing it to be collapsed.

Clean-rebuild or restart VS, still the same.

Is this a bug or a new feature introduced in this version ? If a feature what is the setting to have the 'old' behavior ?

---
#### Ariel Yang  [MSFT] on 6/5/2018, 09:30 PM: 

(private comment, text removed)
#### Ariel Yang  [MSFT] on 6/20/2018, 00:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue reproduces when the multi-line block comment appears within a C# member.

```cs
class C
{
  /*
  This comment is collapsible
  */

  void Method()
  {
    /*
    This comment is not collapsible
    */
  }
}
```
