### ISSUE TITLE
ETA build is broken

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6403]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1474/

```
error CS0234: The type or namespace name 'PortableExecutable' does not exist in the namespace 'System.Reflection' (are you missing an assembly reference?) [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Hosting\RoslynETAHost\l2zy1y12.tmp_proj]
```

I've seen this twice today.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure this looks like it's breaking ETA runs.

**Comment by davkean** [comment]
Actually I think this is flaky, it's not every build.

**Comment by amcasey** [comment]
How could compilation be flakey?  Is this another msbuild node reuse issue?

**Comment by davkean** [comment]
Looking at the error, it can't find a type in Reflection.Metadata. NuGet restore perhaps failed?

**Comment by tmat** [comment]
Seems like we are not restoring stuff under Closed\packages

**Comment by tmat** [comment]
There should in fact be no references to this folder, but the ETA still has them :(

**Comment by tmat** [comment]
So this is what's going on: closed projects weren't updated to project.json yet, so the i didn't update packages.config to the latest version of S.R.M.

**Comment by tmat** [comment]
Fixed.

**Comment by davkean** [comment]
Fixed where? There's no link. How did this fail now but not during the PR build?

**Comment by tmat** [comment]
here: https://github.com/dotnet/roslyn-internal/commit/757dfa2b2597cad3ef080de195e34ef457b7f8e6
