### ISSUE TITLE
Incorrect ref escape analysis

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#64045]
Note: the erroneous scenario is outlined in https://github.com/dotnet/roslyn/issues/64045#issuecomment-1271568313 and explained in the following comments.

**Version Used**: 

Version 17.4.0 Preview 2.0
C# Tools   4.4.0-2.22430.14+2f760738cb92f32f50c981b68ba04ac3c8b7ee48

**Steps to Reproduce**:

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684

**Expected Behavior**:

Error at

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shoulderror-cs-L7

No error at

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror1-cs-L5
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror1-cs-L6
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L9
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L11
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L14
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L16
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L19
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L21

**Actual Behavior**:

**Comment by jaredpar** [comment]
```csharp

static ref int m()
{
    int i = 0;
    return ref m1(ref i).Item1;
    // No Error
    static RS m1(scoped ref int i) => new(ref i);

    // Error 
    static RS m2(scoped ref int i) => RS.Create(ref i); 

}

ref struct RS
{
    public ref int Item1;
    public RS(ref int item1) => Item1 = ref item1;
    public static RS Create(ref int item1) => new RS(ref item1);
}
```

@RikkiGibson that is a minimal repro of the above. It appears that we're not validating constructors in the same way that we validate methods.

**Comment by RikkiGibson** [comment]
The bug is specific to usage of target typed new and expression-bodied members together. If you use a block body, or you use an explicit type name in the constructor call, you get the expected error.

**Comment by jaredpar** [comment]
@RikkiGibson moving out to 17.5 given that it's target typed new specific. That seems edge enough. Will add back if it becomes more prominent.

**Comment by RikkiGibson** [comment]
Leaving this test case here for future reference

```cs


        [Fact, WorkItem(64045, "https://github.com/dotnet/roslyn/issues/64045")]
        public void ConstructorInvocationValEscape()
        {
            var source = """
                class Program
                {
                    // static RS M1(scoped ref int i1) => new(ref i1);
                    static RS M2(scoped ref int i2)
                    {
                        return new(ref i2);
                    }

                    // static RS M3(scoped ref int i3) => new RS(ref i3);
                    // static RS M4(scoped ref int i4)
                    // {
                    //     return new RS(ref i4);
                    // }
                }

                ref struct RS
                {
                    public RS(ref int i0) => throw null!;
                }
                """;
            var comp = CreateCompilation(source, runtimeFeature: RuntimeFlag.ByRefFields);
            comp.VerifyDiagnostics();
        }
``
