### ISSUE TITLE
WorkspaceAnalyzerOptions should not access Solution.Workspace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64046]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-analysis-isnt-warning-CA2000-Disp/10135898)._

---
[severity:It's more difficult to complete my work]
Code analysis isn't warning [CA2000: Dispose objects before losing scope](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000) when a local object of an `IDisposable` type is created, but the object is not disposed before all references to the object are out of scope.

![image](https://user-images.githubusercontent.com/10605811/189869299-a6aadfe7-8bbf-478d-94a4-e1f97455c0c1.png)

---
#### Feedback Bot on 9/1/2022, 06:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
ComputeHashCodeParts is the code on analyzer side. It’s computing key for some data based on analyzer options passed to analyzer options, hence calling AnalyzerOptions.GetHashCode. WorkspaceAnalyzerOptions is a sub-type of AnalyzerOptions. We want to delete this sub-type for a while, let me find the issue tracking that work

**Comment by tmat** [comment]
I don't think we can remove WorksapceAnalyzerOptions. We need analyzers to be able to access IDE options that are not stored in editorconfig: https://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/IdeAnalyzerOptions.cs,0d7224b6f15a1359,references

**Comment by CyrusNajmabadi** [comment]
i guess my question is: why do we need to hash this guy at all?  Or, if we do, why is the 'Workspace' the part we're hashing.  As opposed to the data inside?

**Comment by mavasani** [comment]
Reported again at https://github.com/dotnet/roslyn-analyzers
