### ISSUE TITLE
Erroneous CS8370 when using IntPtr comparison in C# 7.3

### ISSUE THREAD

**Issue by PJB3005** [dotnet/roslyn#64059]
**Version Used**: 

.NET `7.0.100-rc.1.22431.12`

`4.4.0-2.22426.8 (7886fad5)` according to `csc.dll /version`

**Steps to Reproduce**:

Try to compile the following code with the .NET 7 SDK, with `<LangVersion>7.3</LangVersion>`:

```cs
using System;

public static class Program
{
    public static void Main()
    {
        IntPtr a = default;

        bool b = a == IntPtr.Zero;
    }
}
```

**Expected Behavior**:

This compiled fine in .NET 6

**Actual Behavior**:

It fails to compile with the following error:

```
error CS8370: Feature 'native-sized integers' is not available in C# 7.3. Please use language version 9.0 or greater.
```

**Comment by jaredpar** [comment]
> Try to compile the following code with the .NET 7 SDK, with <LangVersion>7.3</LangVersion>:

What `<TargetFramework>` value are you using?

**Comment by PJB3005** [comment]
> > Try to compile the following code with the .NET 7 SDK, with 7.3:
> 
> What `<TargetFramework>` value are you using?

`net7.0`. I just tested and it only seems to happen on `net7.0`, older target frameworks are fine.
