### ISSUE TITLE
StackTaceExplorer does not handle VS Theme change

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#64058]
**Version Used**: 17.4 Preview 1

**Steps to Reproduce**:

1. Open StackTraceExplorer
2. Click in the editor
3. Change the theme from Light to Dark (Tools > Themes > Dark)

**Expected Behavior**:

All controls in the StackTraceExplorer are updated for the newly applied theme.

**Actual Behavior**:
The context menu updates but the StackTraceExplorer tool windows doesn't.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/611219/190504217-4de69aec-1fb1-435b-b28a-bf24cc7e3bda.png">

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback on this.
