### ISSUE TITLE
Move type to file copies parent class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64066]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Move-type-to-file-copies-parent-class/1489630)._

---
[severity:It bothers me. A fix would be nice]
Using the Move type to file refactoring feature in VS2019 IDE, where the type/class is inside an existing class. The feature copies the entire parent class, not just the selected type/class. Issue occurs in VB.NET, have not tested in C#

I.e.:

class ClassA

class ClassB

end class

end class

Refactoring ClassB using Move type to File copies ClassA also

---
#### Feedback Bot on 7/29/2021, 00:04 AM: 

(private comment, text removed)
#### Feedback Bot on 7/30/2021, 02:38 PM: 

(private comment, text removed)
#### Andrew Hall 🤘 [MSFT] on 7/30/2021, 02:42 PM: 

(private comment, text removed)
#### Feedback Bot on 11/1/2021, 01:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
```vb
Public Class Class1
    Public Class Class2

    End Class

    Public Sub M()

    End Sub
End Class
```

Using "Move Class2 to <filename>" copies everything within Class1.
