### ISSUE TITLE
Quick Actions-Slider does not match the content

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64065]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Actions-Slider-does-not-match-the-/1510431)._

---
[bandicam 2021-08-22 18-10-33-919.mp4] (https://aka.ms/dc/file?name=Bdeaa1019eb564394999d9b15d44afca8637652238846607216_bandicam_2021-08-22_18-10-33-919.mp4&tid=deaa1019eb564394999d9b15d44afca8637652238846607216)

When I try to use the mouse wheel to slide up and down the content of the hint, the slider on the side does not change.
Just like in the video above(The pop-up at the beginning is caused by a conflicting shortcut key in the recording software).

---
#### Feedback Bot on 8/23/2021, 01:45 AM: 

(private comment, text removed)
#### Feedback Bot on 8/23/2021, 09:43 AM: 

(private comment, text removed)
#### Feedback Bot on 12/2/2021, 07:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
From feedback issue: 

When previewing a change from lightbulb, if the change is very large (for example generating the full switch statement of all `HttpStatusCode`) the scrollbar in the preview (hover, not modal preview window) is wrong.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of feedback about htis.
