### ISSUE TITLE
Mono Mac build hang (build timeout)

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6407]
http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_stabil_mac_dbg_unit32/71/

Expected:
```
00:05:39.764   Reading input file "Syntax/Syntax.xml"...
00:05:40.972   291 node structures, 2 enumerations, 639 node kinds
00:06:43.019   BasicCodeAnalysis -> /Users/dotnet-bot/j/workspace/roslyn_stabil_mac_dbg_unit32/Binaries/Debug/Microsoft.CodeAnalysis.VisualBasic.dll
```

Actual:
```
00:05:36.990   Reading input file "Syntax/Syntax.xml"...
00:05:38.204   291 node structures, 2 enumerations, 639 node kinds
02:00:32.952 Build timed out (after 120 minutes). Marking the build as aborted.
```

**Comment by amcasey** [comment]
I've only seen it once and I didn't see any clues in the build artifacts.

**Comment by amcasey** [comment]
This one stopped in a different place: http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_prtest_mac_dbg_unit32/644/console

**Comment by amcasey** [comment]
FYI @jaredpar

**Comment by davkean** [comment]
Here's another Mac one: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/869/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52
```
14:25:26 Stacktrace:
14:25:26 
14:25:26   at <unknown> <0xffffffff>
15:52:58 
```

**Comment by leppie** [comment]
I have a similar issue with Mono 64-bit all versions 3.x to latest where I get a SEGFAULT when `new Stacktrace` is called with IronScheme. This repros reliably, but I cannot make a small test case. Happens in a testsuite of 9000 tests... From what I remember, this was never a problem with Mono 32-bit version.

**Comment by davkean** [comment]
Not a lot we can do with this - other than live with it.

**Comment by jaredpar** [comment]
Eventually #7139 will fix this error for us. That should be completed in the update 2 timeframe.

**Comment by jaredpar** [comment]
Repurposing this bug for general issues on Mono Mac.

**Comment by agocke** [comment]
Resolved with https://github.com/dotnet/roslyn/issues/7139

**Comment by jaredpar** [comment]
![image](https://cloud.githubusercontent.com/assets/146967/13856539/e2a35bcc-ec32-11e5-8e25-af9b3675a641.png)
