### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp.Workspaces 4.3.0 bug

### ISSUE THREAD

**Issue by simonziegler** [dotnet/roslyn#64079]
**Version Used**: 

Microsoft.CodeAnalysis.CSharp.Workspaces 4.3.0

Note that 4.2.0 and all versions prior to that which I have used over the last 20 months are fine, as is 4.4.0-1.final

</body>
</html>
**Steps to Reproduce**:

Sorry, my description may be lightweight:
1. Create a net6.0 project with a single namespace (e.g. a console app, although I've got a class library where this issue is exhibited)
2. Add a separate netstandard2.0 source gen project
3. Get the source gen project to add a new class to the namespace in the net6.0 project 
4. Refer to that class in your handwritten code in the net6.0 project

I'll struggle to create a demo repro.

**Expected Behavior**:

The net6.0 project should have no issue recognising and using the newly created class.

**Actual Behavior**:

I get the following compilation error which indicates that the `LenderDetailsCompanion` is missing. This class is entirely generated.

`1>C:\Users\SimonZiegler\source\repos\Vectis.Clearwell\Vectis.ViewModel\Installation\LenderDetails.cs(156,68,156,90): error CS0246: The type or namespace name 'LenderDetailsCompanion' could not be found (are you missing a using directive or an assembly reference?)`

Here's the line of code in my net6.0 project where the compilation fails:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/11708435/190595651-f43cb903-097b-4428-aecf-ce4df418daaa.png">

**Comment by RikkiGibson** [comment]
Are you possibly getting `warning CS8785: Generator 'Generator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result.` in your project? If so, this may be a duplicate of #63780.

**Comment by simonziegler** [comment]
Thank you - I'll check and report back.

**Comment by simonziegler** [comment]
@RikkiGibson that was an excellent observation. Thank you. If I follow the guidance to reference 4.3.0-3.final rather than 4.3.0 everything works fine. Interestingly 4.3.0 seems to work with .net 7 but I'm not going to risk this in production.
