### ISSUE TITLE
C#, "Move to namespace" bad performance.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64072]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Move-to-namespace-bad-performance/1612758)._

---
# Repro

Place the following batchfile in some junk dir.

```
dotnet new classlib -o VS_Slow_rename_repro
md VS_Slow_rename_repro\JunkA
md VS_Slow_rename_repro\JunkB
for /l %%i in (1,1,1000) do @echo namespace A { class A%%i { int m_int; } } > VS_Slow_rename_repro\JunkA\ClassA%%i.cs
for /l %%i in (1,1,1000) do @echo namespace B { class B%%i { int m_int; } } > VS_Slow_rename_repro\JunkB\ClassB%%i.cs
```

- Run the batch file.

- Open the .csproj as a project in VS.

- Open the C# source file `ClassA1.cs`.

- Place caret on `A1`.

- Invoke the incantaction "Move to namespace...".

- Name the target namespace "A1" (without the quotes).

- Hit return (or click the OK button, I don't care).

# Expected

class `A1` is instantly moved into namespace A1.

# Actual

It takes a long time, even for this simple sample, for the operation to complete. In _actual_ code this has been experienced to take double-digit minutes - even for types that are used by one single other type.

The time is certainly long enough for you to capture a performance trace with another VS started and attached to the one holding the repro project.

What's baffling is that once the move is complete, moving type `A1` _back_ into namespace `A` (using the same Roslyn refactoring) _is_ instant. _That_ is the performance expected.

---
#### Feedback Bot on 12/14/2021, 05:30 PM: 

(private comment, text removed)
#### Feedback Bot on 12/15/2021, 09:51 AM: 

(private comment, text removed)
#### Mike on 1/4/2022, 00:12 AM: 

(private comment, text removed)
#### Feedback Bot on 4/2/2022, 00:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Customer comments:

> A simple move of a class from one namespace to another, using this refactoring, that reasonably would have been expected to take at most a few seconds, ended up locking Visual Studio up for over 20 minutes.

> The class to be moved had a globally unique (within the Solution) name, a globally unique filename (matching the class name), and was only used by a few other classes (all within the moved-to namespace).

> The problem has been traced to Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioSymbolRenamedCodeActionOperationFactoryWorkspaceService.VisualStudioSymbolRenamedCodeActionOperationFactoryWorkspaceService+RenameSymbolOperation.Apply.

> Two methods it calls consumes approximately 50% CPU each

> Microsoft.VisualStudio.LanguageServices.Implementation.VsRefactorNotifyService.TryOnBeforeGlobalSymbolRenamed
> Microsoft.VisualStudio.LanguageServices.Implementation.VsRefactorNotifyService.TryOnAfterGlobalSymbolRenamed

> where (IIRC) the project system seem intent on finding out whether or not there are any files with matching (or non-matching) filename extensions. A lot of time seems to be spent in a concurrent collection’s MoveNext (a dictionary IIRC). That suggests this could be yet another misuse of spinlocks.

> What seems strange is that there were no global symbols involved, yet this code clearly tries to initiate a CPU meltdown by calling xxxGlobalSymbolRenamed .

Note: these are global symbols, and these are our extension points for extensibility authors to hear about a rename of any symbol.  The name 'global' simply means it's a global broadcast to interested parties.

--

That said, if the project system is slow on these calls, then that's on them.  This shoudl likely be routed to project system to address.

**Comment by ryzngard** [comment]
If there was an issue in this I can't fully reproduce on my machine in 17.4 Preview2.1. I definitely would be interested in traces from anyone seeing this to diagnose further. It's very possible this was an issue in project system and has been resolved.
