### ISSUE TITLE
C# shouldn't suggest removing "this." after I've set the option to prefer it

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#641]
Ported from TFS WorkItem: <b>1123663</b>

------------------------------

<p><b>Repro Steps:</b></p>
<p>1. Create a new C# console app.</p><p>2. In Tools-&gt;Options, turn on C# option "Qualify member access with 'this'" on the "Code Style" options page.</p><p>3. Use "this." syntax to refer to a class member.</p><p><br></p><p>Result: a lightbulb with the suggestion "Remove 'this' qualification".</p><p><br></p>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Josh Stevens (2/11/2015 3:09:39 PM)

------------------------------

**Comment by shyamnamboodiripad** [comment]
I was unable to reproduce this issue in recent builds including the recently shipped CTP6 build. When the option to qualify member access with 'this.' is checked, we correctly refrain from offering the fix to remove 'this' qualification.

![image](https://cloud.githubusercontent.com/assets/10579684/6493103/4baf62b4-c26d-11e4-8264-2cbef2f0d158.png)
