### ISSUE TITLE
"Use recursive patterns" suggests redundant "this is { ... }" pattern

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#64111]
**Version Used**: 

Microsoft Visual Studio Enterprise 2022
Version 17.2.4
VisualStudio.17.Release/17.2.4+32602.215

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44

**Steps to Reproduce**:

```csharp
class Bar
{
    public Qux? Qux { get; }

    void Foo()
    {
        if (Qux != null && Qux.Color != ConsoleColor.Red)
        {
            Console.WriteLine("A");
        }
    }
}

class Qux
{
    public ConsoleColor Color { get; }
}
```

Generated code in `Foo` is equivalent to:

```csharp
	if (Qux != null && Qux.Color != ConsoleColor.Red) { ... }
```

**Expected Behavior**:

"Use recursive patterns" rewrites `Foo` to:

```csharp
    void Foo()
    {
        if (Qux is { Color: not ConsoleColor.Red })
        {
            Console.WriteLine("A");
        }
    }
```

Generated code in `Foo` is equivalent to:

```csharp
	Qux qux = Qux;
	if (qux != null && qux.Color != ConsoleColor.Red) { ... }
```

**Actual Behavior**:

"Use recursive patterns" rewrites `Foo` to:

```csharp
    void Foo()
    {
        if (this is { Qux: not null, Qux.Color: not ConsoleColor.Red })
        {
            Console.WriteLine("A");
        }
    }
```

where `this is { ... }` should always pass the `null` check, and simply using `Qux is { Color: not ConsoleColor.Red }` would already carry the `null` check for `Qux`.

Generated code has the redundant `null` check for `this`:

```csharp
	if (this != null)
	{
		Qux qux = Qux;
		if (qux != null && qux.Color != ConsoleColor.Red)
		{
			Console.WriteLine("A");
		}
	}
```

**Comment by CyrusNajmabadi** [comment]
@alrz ?

**Comment by alrz** [comment]
I think avoiding the redundant null check pattern will also resolve the issue with 'this', however we still do this when there's no common receiver eg

```cs
this.Prop1 && this.Prop2
```

**Comment by sdelarosbil** [comment]
Hey, can I take this?

**Comment by CyrusNajmabadi** [comment]
Definitely!
