### ISSUE TITLE
Lowering of `is (not) null` is opposite to the expected when the block is empty

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64118]
**Version Used**:
https://github.com/dotnet/roslyn/commit/54aeea412317bcddf24ca85e98004df02d6bf999 (from sharplab)

**Steps to Reproduce**:
```cs
using System;

public class C
{
    public void M()
    {
        var c = new C();
        
        if (c is null)
        {
            //Console.WriteLine();
        }
    }
}
```
https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAPQGYACLUgYQIG8DSHyz0AWUgWQAoBKexu/IyGkAbhABOpAMakAvKRgBTAO5UeAbj7DSW4VABmpTjKgBnBQFcANld6DtpAQ+EB6F+mwBODbqEBfXQD8PyA===

**Expected Behavior**:
Lowered code if `M` looks like this:
```cs
var c = new C();  
if (c == null)
{
}
```

**Actual Behavior**:
Lowered code of `M` looks like this:
```cs
var c = new C();  
if (c != null)
{
}
```
However as soon as you uncomment `Console.WriteLine();` it becomes expected:
```cs
C c = new C();
if (c == null)
{
    Console.WriteLine();
}
```

This thing has 0 practical impact, I don't know why I am even reporting it 🤔

**Comment by svick** [comment]
You're not directly looking at the IL that's produced by the compiler, you're looking at decompiled code. And [when you look at the IL](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQ5eAzAASE0DC5A3uTe3bXgCw0CyACgCUbDqzIdJNAG4QATjQDGNALw0YAUwDujYQG5RUmoalQAZjQHKoAZ3UBXFChESjNcW6kB6L3iIBOfRNJAF8TMNd2E2o6Xj4CYRMPN1kFZTVNHQYgyKlgjnNLazsYR2d89mTPdj9AoQNc0PDJchCgA), you'll notice that the only difference between the two version is the addition of a call to `Console.WriteLine()`.

Which means the difference you see is solely an invention of the decompiler. (SharpLab uses [ILSpy](https://github.com/icsharpcode/ILSpy). If you think this is something worthy reporting, they would be the ones to report this to.)

**Comment by CyrusNajmabadi** [comment]
Closing out as by-design.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Can you reclose this one as `not planned` please, it better suits the "by design" closing reason. Thanks!

**Comment by CyrusNajmabadi** [comment]
I don't really think it matters :)

**Comment by DoctorKrolic** [comment]
It makes better representation of really completed problems vs false-positive reports when looking at resently closed issues. But it mostly annoys my internal perfectionist TBO, so sorry for disturbing 🙂
