### ISSUE TITLE
Preview Changes Dialog Hides Project Information

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#64116]
## Summary
When doing a fix, I should see project and folder information similar to the solution explorer.

Instead I just see the file names which makes it dangerous to use in my 350-project solution:

![image](https://user-images.githubusercontent.com/13609558/191021528-0d85d320-72bf-45e1-a82b-c554e7b30e9e.png)

## Background and Motivation
Have a better view/control over the scope of changes.

## Proposed Feature
See above.

## Alternative Designs
N/A.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in preview changes experiences.
