### ISSUE TITLE
No Public API for top-level nullability of members

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#64123]
Given a method

```C#
class C
{
   T M();
}
```

There doesn't appear to be any way to determine the top-level nullability of the return type `T`.

This is a pretty important question and the answer is language-defined and very difficult to answer, so I think offering a public API for this is important.

**Comment by agocke** [comment]
Right, there are a bunch of cases that are difficult to handle: unconstrained generics are maybe null, `class?` is nullable, `iface?` is nullable, and then there are all the attributes.

While technically this is the flow state information, this is actually the "starting state" information for flow, so there's no flow analysis necessary to calculate this information. The only thing you need is knowledge of whether or not nullable was enabled at that location, and the location of the constraints.

**Comment by RikkiGibson** [comment]
@jasonmalinowski @333fred for thoughts

**Comment by 333fred** [comment]
> It seems like ITypeSymbol.NullableAnnotation or IMethodSymbol.ReturnNullableAnnotation doesn't really tell you whether the return value would have a maybe-null flow state or a not-null flow state. That's the essential issue, right?

I don't understand. This is exactly what those properties are for. @agocke, can you please clarify what's being asked here?

**Comment by agocke** [comment]
Those properties tell you whether something has been *annotated* as nullable, not whether the return value may be null.

**Comment by agocke** [comment]
@jaredpar  did you mean to close this?

**Comment by jaredpar** [comment]
I put need more info on it waiting for feedback, it got auto-closed

**Comment by 333fred** [comment]
> Those properties tell you whether something has been annotated as nullable, not whether the return value may be null.

Sorry, meant to respond. I have no idea what you're asking for though. There is no difference: if it's annotated, then it might be null.
