### ISSUE TITLE
Closing and reopening C# interactive after vs launch fails and opens pop-up.

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#6413]
This is reproing on RC Update 1 build 
Repro steps:
1. Open VS
2. Open C# Interactive
3. Close VS
4. Reopen VS
5. Close C# Interactive.
6. Attempt to reopen C# interactive.
This window pops up:
![image](https://cloud.githubusercontent.com/assets/10537189/10807135/877c7024-7d99-11e5-92e8-8376d13b6106.png)

If you attempt to reopen C# interactive again, it works fine. It also is fine for any subsequent opening and closing of C# interative. 

At this point you can repeat steps 2-6 to have it repro again.

**Comment by mattscheffer** [comment]
@ManishJayaswal

**Comment by mattscheffer** [comment]
@amcasey

**Comment by amcasey** [comment]
Does this happen for you every time?  I've seen that dialog, but it always goes away after the first repro (even if I restart VS).

**Comment by mattscheffer** [comment]
Yes it is happening every time for me. The key is that C# interactive has to be open when I close VS. I'll send you machine info if you want to look.

**Comment by ManishJayaswal** [comment]
@amcasey @pharring FYI

**Comment by amcasey** [comment]
I can repro the issue on the VM @mattscheffer provided, but package load failures have been blocking my local repro.  I'm attempting a new workaround now.

**Comment by amcasey** [comment]
Building on an observation from @pharring, it appears that there's logic in ```VSInteractiveWindowProvider.Open``` to determine whether the window should be created or shown.  If the user opens and closes the window within the same VS session, then the provider knows that the window already exists and calls ```Show```.  However, it appears to lack a mechanism for detecting whether a window exists from a previous VS session.

**Comment by amcasey** [comment]
PTVS follows a slightly different code path.  If we're lucky, they're unaffected by this bug and we can just follow their approach.

**Comment by amcasey** [comment]
I've confirmed that PTVS is unaffected on @mattscheffer's VM.

**Comment by amcasey** [comment]
"Slightly different" might have been an understatement.  PTVS has additional complexity for handling a family of tool windows.

**Comment by amcasey** [comment]
Actually, it looks like it might be simple - ```Create``` creates the window, but only one caller holds onto the result.  It should probably be saved regardless of the caller.

**Comment by amcasey** [comment]
I believe step (5) of the original repro is unnecessary.

**Comment by amcasey** [comment]
Yep, it appears to be that simple.  PR pending.
