### ISSUE TITLE
Change value escape of 'out' parameters to ReturnOnly

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#64155]
```cs
ref struct ByteContainer
{
    public byte B;
}

ref struct RefByteContainer
{
    public ref byte RB;

    public RefByteContainer(ref ByteContainer bc)
    {
        RB = ref bc.B; // CS9079: Cannot ref-assign 'bc.B' to 'RB' because 'bc.B' can only escape the current method through a return statement.
    }

    public RefByteContainer Create(ref ByteContainer bc)
    {
        return new RefByteContainer { RB = ref bc.B }; // ok
    }

    public void Create(ref ByteContainer bc, out RefByteContainer rbc)
    {
        rbc.RB = ref bc.B; // CS9079: Cannot ref-assign 'bc.B' to 'RB' because 'bc.B' can only escape the current method through a return statement.
    }
}
```

This shows that constructors end up being less "capable" than factory methods. We might want to adjust the rules for 'out' parameters (including 'this' in constructors). We will have to think through whether it would hurt other scenarios to do so. cc @jaredpar @cston

**Comment by jaredpar** [comment]
This does get back to a core question of how we model constructors in terms of span safety rules. There are essentially two ways to look at it and both are conceptually correct: 

```csharp
// option 1
static Span<int> Ctor(ref int i);

// option 2  
static void Ctor(out Span<int> @this, ref int i); 
```

It's been a bit of a struggle to decide which is the better option. If we change `out` to have *safe-to-escape* of *return-only* though then option 2 becomes the clear winner. It can represent both call site and call implementation equally well. I think for implementation simplicity we'll continue to analyze call sites in terms of option 1. But in terms of the spec we'll represent ctors as 2. 

Note: whenever you think about making changes to ctors, always keep the [tricky readonly mutation](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#preventing-tricky-ref-assignment-from-readonly-mutation) problem in mind. Solving that though really just comes down to ensuring the `ref` of `this` has a shorter lifetime than the value which option 2 easily achieves.

**Comment by RikkiGibson** [comment]
Did you mean for option 1 to be `static`?

It does seem like when comparing the declaration versus usage of constructors, the language is depending on the correspondence between `out` and return values in a sense. So my gut feeling at this point is that making val escape of an out `ReturnOnly` is going to flatten out more of the jagged edges.

**Comment by jaredpar** [comment]
> Did you mean for option 1 to be static?

I did. That mean it creates a local then returns it by value. That isn't how it works in reality but conceptually it's fine for `ref` safety and it allows for the type of capture that we're discussing here. 

If you model as an instance method on a `struct` which was conceptually marked as `init` it would look something like this:

```csharp
struct S {
  init void .ctor() { ... }
}
```

That has the problem though that it can't be a normal instance method where *safe-to-escape* of `this` is *calling method*. It wouldn't be able to capture RTRS as `ref` fields. So it has to be special cased. Where is with `out` / option 2 everything juts falls out from the rules without special casing.

**Comment by RikkiGibson** [comment]
Got it, the return value is how values from the parameters might be captured.

**Comment by RikkiGibson** [comment]
Either before or at the same time that we do this, we should ensure that the test mentioned in https://github.com/dotnet/roslyn/pull/64152#discussion_r975898831 is updated to improve clarity.

**Comment by Sergio0694** [comment]
Just trying to understand this better. Consider this example (using explicit `this` for clarity):

```csharp
ref struct ByteContainer
{
    public byte B;

    public static void GetSpan(ref ByteContainer @this, out Span<byte> span)
    {
        // error CS9077: Cannot return a parameter by reference 'this' through a ref parameter; it can only be returned in a return statement
        // error CS8347: Cannot use a result of 'Span<byte>.Span(ref byte)' in this context because it may expose variables referenced by parameter 'reference' outside of their declaration scope
        span = new Span<byte>(ref @this.B);
    }
}
```

Right now that assignment fails, because the RSE scope of `out` is not return-only, so `@this` can't escape through it.

This means that callers can safely do this (with some other implementation of `GetSpan` that does compile):

```csharp
public static Span<byte> Foo()
{
    ByteContainer container = default;

    ByteContainer.GetSpan(ref container, out Span<byte> span);

    return span; // This is fine, span can't have captured container by ref
}
```

Because the compiler knows that the reference to that `container` local can't escape through `span`, so that's safe to return. Once these changes go online instead, `GetSpan` will be able to have `span` capture `ref ByteContainer`, hence that `span` local into `Foo` will no longer be safe to return, so I assume that would have to become an error in this case.

Doesn't this mean that changing the STE scope of `out` to return-only (which I understand is currently planned for post C# 11) will be a breaking change for all existing C# 11 code that was using a similar pattern like the one in this example? As in, compared to just enabling _more_ things, wouldn't that change actually break existing callsites like this one? 🤔

**Comment by jaredpar** [comment]
> Because the compiler knows that the reference to that container local can't escape through span, so that's safe to return. Once these changes go online instead, GetSpan will be able to have span capture ref ByteContainer, hence that span local into Foo will no longer be safe to return, so I assume that would have to become an error in this case.

Correct. 

> which I understand is currently planned for post C# 11

We've said a few times we're focused on implementing the current version of the spec for RC2 and not considering anything else until RC2 has fully landed. Getting that done was enough of a mountain to climb. 

> Doesn't this mean that changing the STE scope of out to return-only (which I understand is currently planned for post C# 11) will be a breaking change for all existing C# 11 code that was using a similar pattern like the one in this example? As in, compared to just enabling more things, wouldn't that change actually break existing callsites like this one?

Don't forget that we enforce the rules a method was compiled with, not the rules that the current code is compiled with. So if we changed this in C# 12 then it could be done by incrementing the ref safety rules versions and it would not be a breaking change unless devs recompiled and accepted the new semantics. Just as similar changes around `ref` today change behavior once you compile with `/langversion:11`. 

It's also possible that we could do this as a bug fix post C# 11 RTM. We are allowed six months to make pretty much whatever change we want as a part of settling features. ref safety isn't different here. It's also possible we could change this before C# 11 RTM. 

But nothing has been committed to. Only that once we settle RC2 we're going to take a look at this.

**Comment by Sergio0694** [comment]
Ah, gotcha, yeah that makes perfect sense. And yeah to be clear, this wasn't meant to "bump" this issue at all, I really just wanted to understand this better and the impacts that this additional change would have. Thank for the additional details Jared! 😊
