### ISSUE TITLE
Files added via a code action aren't included in the project file

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#64157]
Steps to reproduce:
1. Create a TypeScript Blank Node.js Console application
2. In app.ts, write the code `1234;` in a new line.
3. Select that line of code and invoke the "Move to a new file" code action.
4. The code will be moved and the new file will be opened on the editor, but the file isn't added to the project file. Note how files added with "Add new item" are set to "TypeScript compile" in the .nsproj file:
<ItemGroup>
    <TypeScriptCompile Include="TypeScript1.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
  </ItemGroup>

The problem can also be reproduced in .NET framework applications.

**Comment by jasonmalinowski** [comment]
@MariaSolOs is currently investigating this.

**Comment by jasonmalinowski** [comment]
@MariaSolOs's investigation makes us think this is not TypeScript as we're calling into a DTE implementation which they return and it just immediately no-ops.
