### ISSUE TITLE
Incorrect expression is being generated, when anonymous event handler has closure inside

### ISSUE THREAD

**Issue by Dennis-Petrov** [dotnet/roslyn#6416]
Hi.
I've a couple library classes, which helps to deal with `INotifyPropertyChanged`. Nothing magical:

    public class NotificationObject : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged<TProperty>(Expression<Func<TProperty>> property)
        {
            OnPropertyChanged(property.GetMemberPathString());
        }

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    public static class ExpressionExtensions
    {
        private static string[] GetMemberPath(Expression expression)
        {
            MemberExpression memberExpression;
            var memberNames = new Stack<string>();

            while ((memberExpression = expression as MemberExpression) != null)
            {
                memberNames.Push(memberExpression.Member.Name);
                expression = memberExpression.Expression;
            }

            return memberNames.ToArray();
        }

        private static string GetMemberPathString(Expression expression)
        {
            return string.Join(".", GetMemberPath(expression));
        }

        public static string GetMemberPathString<TResult>(this Expression<Func<TResult>> expression)
        {
            return GetMemberPathString(expression.Body);
        }
    }

Consider this code, that uses `NotificationObject` from above:

    public class A : NotificationObject
    {
        private readonly M model;

        public A()
        {
            var boo = 200;

            model = new M();
            model.SomethingHappened += (sender, args) =>
            {
                Console.WriteLine(boo);
                OnPropertyChanged(() => Model);
            };
        }

        public M Model { get; private set; }
    }

**The issue**.
When `SomethingHappened` is raised, `ExpressionExtensions.GetMemberPathString` returns `<>4__this.Model` instead of `Model` because of incorrect member expression.

If I remove closure (that is, comment line `Console.WriteLine(boo);`), `GetMemberPathString` returns correct value - `Model`. Another workaround is to remove lambda, and handle event with regular method.

This code works correctly using VS 2013, either with closure, or without it.
Looks like a bug.

P.S. The real application, where this problem was located, is a WPF application, where such code occurs **very** often.

`M` in sample code is just a class, that generates some event:

    public class M
    {
        private async Task DoSomething()
        {
            await Task.Delay(5000);
            OnSomethingHappened();
        }

        public M()
        {
            var _ = DoSomething();
        }

        protected virtual void OnSomethingHappened()
        {
            SomethingHappened?.Invoke(this, EventArgs.Empty);
        }

        public event EventHandler SomethingHappened;
    }

**Comment by jaredpar** [comment]
@VSadov please take a look at this.
