### ISSUE TITLE
[LSP] Document highlighting throws exception with F# files

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#64169]
Since syntax trees aren't supported in F#, this line throws an exception upon opening a default F# console app:
https://github.com/dotnet/roslyn/blob/2297cd72e2224d140ba639d75432ddd0b0b5f0e7/src/Features/LanguageServer/Protocol/Handler/Highlights/DocumentHighlightHandler.cs#L72

cc @dibarbet

**Comment by CyrusNajmabadi** [comment]
This should likely be using IDocumentHighlightsService

**Comment by jasonmalinowski** [comment]
@dibarbet Did we already fix this? I assume we'd be getting lots of reports if we hadn't.

**Comment by dibarbet** [comment]
@jasonmalinowski afaik this feature isn't turned on unless the LSP editor feature flag is turned on, so users shouldn't be hitting this.  That being said I haven't tried myself so I will confirm.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
