### ISSUE TITLE
Lack of a fresh Roslyn version in the Mono project

### ISSUE THREAD

**Issue by IvanZosimov** [dotnet/roslyn#64174]
## Background and Motivation
Some functionality of the MVVM Toolkit (namely from version 8.0.0 preview1) is available only with Roslyn 4.x, but currently, Mono has only Roslyn [3.9.0-5.21112.8](https://github.com/mono/msbuild/blob/xplat-master/eng/Versions.props#L13). Is it possible to bump Roslyn's version in the Mono to a fresher one? 

The same issue was filed [here](https://github.com/mono/mono/issues/21529) almost 2 months ago. Unfortunately, no response from the Mono team was received. I was suggested to create this issue here and I hope you can help us or redirect us to another team that is in charge of that issue.

## Steps to Reproduce

0. Install the Mono 
1. Clone https://github.com/roughiain/PipelineTestSourceGenerators
2. Restore Nuget packages
3. Try to build the solution on macOS using `msbuild` with these flags:
```msbuild /p:Configuration=Release /p:Platform=iPhone /t:Clean "./TestPipeline.sln"```

### Current Behavior

We've got the warning: 

``` Users/runner/.nuget/packages/communitytoolkit.mvvm/8.0.0-preview3/buildTransitive/netstandard2.1/CommunityToolkit.Mvvm.targets(41,5): warning : The MVVM Toolkit source generators have been disabled on the current configuration, as they need Roslyn 4.x in order to work. The MVVM Toolkit will work just fine, but features relying on the source generators will not be available. ```

### Expected Behavior

No warnings, just a pure build.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Mono Version Used**:

[6.12.0.182](https://github.com/mono/mono/tags)

## Stacktrace

[Link to the logs](https://github.com/roughiain/PipelineTestSourceGenerators/blob/main/pipelineoutput.txt)

## Linked issues

https://github.com/actions/virtual-environments/issues/5782
https://github.com/mono/mono/issues/21529

**Comment by CyrusNajmabadi** [comment]
This does not appear to be a request for the roslyn team.  This should go to the mono team right?  We have no issue with them using a later version of Roslyn :)

**Comment by arkalyanms** [comment]
@IvanZosimov I am not following the Roslyn bug filing recommendation on the mono repo bug you've filed. What would you like the Roslyn team to help with?

**Comment by IvanZosimov** [comment]
Hi, @CyrusNajmabadi and @arkalyanms, thanks for the answers! Practically, the Mono team is an ephemeral concept as I wrote in the motivation for this issue, I thought that the Mono and the Roslyn teams are linked somehow initially :) Sorry for disturbing you.
