### ISSUE TITLE
Non-unit test binaries are being run causing #6358 more likely to happen

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6417]
UnitTestFramework is being picked up a test binary and run, which is causing https://github.com/dotnet/roslyn/issues/6358 more likely to hit.

**Comment by davkean** [comment]
This looks like an internal issue, only, BuildAndTest.proj doesn't include it. tag @amcasey

**Comment by amcasey** [comment]
Fixed the signed build definitions (internal).
