### ISSUE TITLE
Source generator exceptions should be shown as errors, rather than warnings

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/roslyn#64175]
**Version Used**: 

VS 2022

**Steps to Reproduce**:

When a source generator throws an exception, it shows up in the VS Error List pane as a warning, rather than an error.

Our project's source generator is generating C# classes that our other code relies on. If the source generator fails to run, we end up with lots of errors, due to missing classes, but the actual exception that caused the source generator to fail to run is only shown as a warning.

I'd like to propose that either:
1. Exceptions in source generators always be shown as errors.
2. A mechanism be added that allows exceptions from specific source generators to be shown as errors.
3. A mechanism be added that allows a source generator to be marked as "required", and then exceptions from that source generator be shown as errors. (This might also be useful for https://github.com/dotnet/roslyn/issues/55518)

**Expected Behavior**:

See above.

**Actual Behavior**:

See above.

**Comment by Youssef1313** [comment]
Do you throw this exception by yourself in generator code? In this case, you should definitely turn that into a diagnostic instead of an exception.

If it's an "unexpected" exception, you could try/catch everything and turn it into a diagnostic too, but I'm not sure if that's a good practice.

**Comment by Bosch-Eli-Black** [comment]
It's an unexpected exception 🙂

Specifically:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8785	Generator 'MyGEnerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName '[example].g.cs' of the added source file must be unique within a generator.
```

We were previously try/catching everything and turned it into custom diagnostics, but ya... it felt hacky 😆

**Comment by Youssef1313** [comment]
You could treat `CS8785` as an error then. I guess `dotnet_diagnostic.CS8785.severity = error` should work.

**Comment by jaredpar** [comment]
This has been the long standing behavior of analyzers / generators in our ecosystem. Yes it made more sense for analyzers than generators but I'm not sure there is a lot of value in differentiating in them at this point. As @Youssef1313 mentioned it is possible to make this an error today if you want to. As such closing this on out.

**Comment by Bosch-Eli-Black** [comment]
Alright, I guess we'll go with setting `dotnet_diagnostic.CS8785.severity = error` for now 🙂

I hope the team reconsiders this in the future, though 🙂  Currently, when a source generator fails to run, it's easy to miss the warning about the source generator failing amidst the wave of errors caused by the source generator failing.
