### ISSUE TITLE
Create email aliases for specific infraswat roles

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#64191]
Currently the internal mlinfraswat DL is a firehose of different notifications. Many people on the DL just handle it by filtering the messages to folders that they never check.

We're thinking that emails sent based on infra failures should only be sent to specific folks whose job (on-call rotation) it is to monitor those failures. However, making everyone configure their email rules properly, turn the rules on and off before and after their rotation, and so on, is fairly error prone.

Let's set up an alias specifically for Tiger, and specifically for Mantis, have the role-appropriate notifications sent to each, and then change the members of the alias when the rotation changes.

When we do this work, we can try to ensure that automatic emails generally are not sent to mlinfraswat. We can start reserving that alias for when a person wants to notify everyone of some infra problem.

**Comment by jasonmalinowski** [comment]
I had _thought_ we had fixed the firehose problem, but again I could have some rule eating emails I don't realize. That said, having the DL represent the current role assignments would mean I can stop asking "who is it this week?" and just email that DL. And if they rotate then a longer conversation picks up the new person automatically.

**Comment by RikkiGibson** [comment]
I think you're right. It looks like most of the non-actionable emails I used to get on that DL have stopped in recent times. Thanks!

**Comment by RikkiGibson** [comment]
I haven't been experiencing any email firehose problems in recent sprints so will close out.
