### ISSUE TITLE
False IDE0059 message

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/roslyn#64198]
**Version Used**: VS 17.2.2, .NET 6 (but also previous versions)

**Steps to Reproduce**: 
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0ATEBqAPgYgDsBXAG1IENhSYACGQqmgWACgABAJgEY32AGWu24A6AMIRyMMABcAlhEIBnANx9BwlGtZ8AzEM60xtAN5taFofvYpaAWQAUASlPnL7iMABW0mbVhKZH4AvLSEMADutAAyckoyADxyhDIAfM7a7u7CnEkpaLSePrIA/Km0SjAyAJIyMAC2mVkWcgBmtA4SypIwIgBKMBQYseHOtMGhAERUYJNObs1mrM3NAG4UULQbUBQAnuO0AIJQO7visBR11coyFIRgMA4yuwAOMBCtDskyTgUArPwnE0VpZKjU6vUDl8CnIIS5guVtnsRABlKoANQopGIj1hDRhQLYCyyAF9ie4YKRKuTLEsQe51ptSHEQh1qrF4k4AkEVLQAPR82jVAAiAFF+Pw/gBOGnNMG1BpQuQwuHjcrM+IiQ4YDBfOHA0lsAW0ESm2UVKoK+oOfgFbicXSE5aWMmsElAA===)
```cs
Action<int, object?> setItem;
if (Console.ReadLine() == "abc")
{
    var array = Array.CreateInstance(typeof(int), 50);
    setItem = (i, item) => array.SetValue(item, i);

}
else
{
    var list = (IList)result; // IDE0059
    setItem = (i, item) => list.Add(item);
}
// ...
setItem(x, y);
``` 

**Expected Behavior**: no IDE0059 message

**Actual Behavior**: it reports IDE0059 message
![image](https://user-images.githubusercontent.com/16783987/191611356-853b388d-4478-4feb-b262-2ae7b8308724.png)

`Severity	Code	Description	Project	File	Line	Suppression State Message`	
`IDE0059	Unnecessary assignment of a value to 'list'	Util	Read.cs	216	Active`

![image](https://user-images.githubusercontent.com/16783987/191618431-bd7ea086-2c8b-4d9d-a82e-6cb25b61ab16.png)

**Comment by RikkiGibson** [comment]
It would be useful to include the message itself as well here.

**Comment by TahirAhmadov** [comment]
@RikkiGibson I've updated the OP. Thank you.

**Comment by CyrusNajmabadi** [comment]
Can you supply a full repro?  I don't see where 'result' is defined. Thanks!

**Comment by TahirAhmadov** [comment]
@CyrusNajmabadi I've added a SharpLab to OP. Looks like this is triggered by the presence of an `if`.

**Comment by CyrusNajmabadi** [comment]
That does seem strange.  @mavasani ?

**Comment by mavasani** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/57344. @akhera99 already has a PR out for fixing it

**Comment by TahirAhmadov** [comment]
@mavasani thank you, I should have checked first.
