### ISSUE TITLE
VB Field Or Property: Wrong type inferred when the usage is on a lambda

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#642]
Ported from TFS WorkItem: <b>528229</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1. ETA VB</P>
<P>2. Paste the code given below.</P>
<P>3. Ctrl + . on Highlighted and Generate&nbsp;a field or property&nbsp;</P>

```
Class [Class]
    Private Sub Method(i As Integer)
        foo = Function()
                  Return 2
              End Function
    End Sub
End Class
```

Actual: `Object` is inferred as the type
Expected: `Func(Of Int)`

------------------------------

<p><b>Revisions:</b></p>

1) Created By Balaji Krishnan (11/28/2012 5:07:21 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 1);)

------------------------------

2) Edited By Dustin Campbell (11/28/2012 5:07:22 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 2);)

------------------------------

3) Edited By Cyrus Najmabadi (11/28/2012 5:07:23 PM)

This appears to be a bug in VB binding.&#160; We ask for both GetSemanticInfo and GetSemanticInfoInParent on the lambda block, and in both cases get back an error type.&#160; If VB inference suports this then at least one of the above should return a semanticinfo with Func&lt;int&gt;.
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 3);)</p>

------------------------------

4) Edited By Cyrus Najmabadi (11/28/2012 5:07:24 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 4);)

------------------------------

5) Edited By Balaji Krishnan (11/28/2012 5:07:24 PM)

clearign team triage so that the compiler triage sees this.
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 5);)</p>

------------------------------

6) Edited By Anthony D. Green (11/28/2012 5:07:26 PM)

<p>Implicit locals aren't in scope.</p>
<p>foo doesn't appear to be declared</p>
<p>The type of VB's lambdas are anonymous compiler generated delegate types and would not be Func(Of T) anyway.</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 6);)</p>

------------------------------

7) Edited By Balaji Krishnan (11/28/2012 5:07:27 PM)

<p>Anthony,</p>
<p>foo was&#160;left un-declared intentionally, i am testing the &quot;Generate Field&quot; Code Action, which will fill in the declaration for me. Everything works in this case, except that we wrongly infer the type of the Field. This, as per Cyrus, is an issue with the compiler. Now, in this context, i am not sure if the absence of implicit locals contribute to this bug. Can you please confirm?</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 7);)</p>

------------------------------

8) Edited By Balaji Krishnan (11/28/2012 5:07:28 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 8);)

------------------------------

9) Edited By Anthony D. Green (11/28/2012 5:07:29 PM)

<p>Ah, I see. Good catch. This is still by design. VB synthesizes special delegate types for lambdas on their own - it does not use (or even know about) the Action and Func types. So, eventually we can return a synthesized delegate type symbol for this case but it will *never* return Func(Of Integer) as the natural type of a lambda. A VB lambda will only take on a Func type in context (when bound InParent).</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 9);)</p>

------------------------------

10) Edited By Anthony D. Green (11/28/2012 5:07:30 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 10);)

------------------------------

11) Edited By Balaji Krishnan (11/28/2012 5:07:30 PM)

<p>sending it back to you, just to consider that C# works here : </p>
<p>Generating a field for&#160;'z'&#160;in<br>&#160;&#160;&#160; <span style="COLOR:blue;">static</span> <span style="COLOR:blue;">void</span> <span style="COLOR:black;">Main</span><span style="COLOR:black;">(</span><span style="COLOR:blue;">string</span><span style="COLOR:black;">[]</span> <span style="COLOR:black;">args</span><span style="COLOR:black;">)</span><br>&#160;&#160;&#160; <span style="COLOR:black;">{</span><br>&#160;&#160;&#160;&#160;&#160;&#160;&#160; <span style="COLOR:black;">z</span> <span style="COLOR:black;">=</span> <span style="COLOR:black;">()</span> <span style="COLOR:black;">=&gt;</span> <span style="COLOR:black;">1</span> <span style="COLOR:black;">+</span> <span style="COLOR:black;">2</span><span style="COLOR:black;">;</span><br>&#160;&#160;&#160; <span style="COLOR:black;">}</span></p>
<p><span style="COLOR:black;">gives :&#160;&#160;&#160;<span style="COLOR:blue;">private</span> <span style="COLOR:blue;">static</span> <span style="COLOR:#2b91af;">Func</span><span style="COLOR:black;">&lt;</span><span style="COLOR:blue;">int</span><span style="COLOR:black;">&gt;</span> <span style="COLOR:black;">z</span><span style="COLOR:black;">;</span></span></p>
<p><span style="COLOR:black;"><span style="COLOR:black;"></span></span>&#160;</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 11);)</p>

------------------------------

12) Edited By Cyrus Najmabadi (11/28/2012 5:07:32 PM)

<p>&quot;The type of VB's lambdas are anonymous compiler generated delegate types and would not be Func(Of T) anyway.&quot;</p>
<p>&#160;</p>
<p>Is that true?</p>
<p>&#160;</p>
<p>i thought you could write:</p>
<p>&#160;</p>
<p>dim foo = function() 2</p>
<p>&#160;</p>
<p>And have VB decide that that was&#160; Func&lt;int&gt;.</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 12);)</p>

------------------------------

13) Edited By Anthony D. Green (11/28/2012 5:07:33 PM)

<p>We discussed this in the design meeting and resolved that the lambda itself is typeless. And that it is convertable to an anonymous delegate type synthesized by the compiler which is not a System.Func or System.Action type, though that delegate itself may be convertable to those types. To work around this you'll need to either bind the arguments/return type of the lambda and construct a System.Action/Func delegate yourself OR generate a named&#160;delegate type which uses the same signature and parameter names as the anonymous delegate type (to preserve the parameter names).</p>
<p>&#160;</p>
<p>Anonymous delegate types are not in scope yet so this work will have to wait until the future.</p>
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 13);)</p>

------------------------------

14) Edited By Balaji Krishnan (11/28/2012 5:07:34 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 14);)

------------------------------

15) Edited By Balaji Krishnan (11/28/2012 5:07:35 PM)

closing for now and marking as revisit in custom01 so that i can take a look at this after anon delegates are implemented.
<p>(TFS Integration from 'DevdivProjects-Roslyn' Id: 6996 (rev 15);)</p>

------------------------------

16) Edited By Balaji Krishnan (9/25/2013 4:22:39 PM)

<p>Per AdGreen, the compiler synthesizes internal types and its up to the IDE to find the corresponding Func or Action(of T).</p>
<p>&nbsp;</p>
<p>Reactivating the bug and sending it to IDE triage to take a look.</p>
<p>&nbsp;</p>
<p>I'm curious as to how C# works here without any extra work from the IDE though.</p>

------------------------------

17) Edited By Kevin Pilch-Bisson (2/16/2015 3:47:29 PM)

Moving to Diagnostics for GFU.

------------------------------

**Comment by jmarolf** [comment]
@shyamnamboodiripad could you verify this please?

**Comment by MattGertz** [comment]
Verified both C# and VB.

**Comment by shyamnamboodiripad** [comment]
Thank you for verifying @MattGertz!
