### ISSUE TITLE
task+closure 

### ISSUE THREAD

**Issue by rbwhitaker** [dotnet/roslyn#64217]
**Version Used**: .NET 6, Visual Studio 
Microsoft Visual Studio Professional 2022
Version 17.0.5
VisualStudio.17.Release/17.0.5+32112.339
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Professional

Also tested by changing the project to target .NET 5 and saw the same behavior.

**Steps to Reproduce**:

(1) Put the following code into a new .NET 6 project:

```cs
var theBool = false;
Task.Run(() => { theBool = true; });
while (!theBool) { }
Console.WriteLine("Done");
```
(2) Compile and run it in a debug (non-optimized) configuration.
(3) Compile and run it in a release (optimized) configuration.

**Expected Behavior**:

The code eventually terminates in both debug (non-optimized) and release (optimized) builds. Or, minimally, there is the same observable behavior across both versions.

**Actual Behavior**:

The code eventually completes in debug (non-optimized) builds, but in release mode, the `while` loop never terminates.

**Comment by rbwhitaker** [comment]
Perhaps a tiny bit more information. I just tried this code, which adds another `Console.WriteLine` in the lambda to ensure that it is actually running.

```cs
var theBool = false;
Task.Run(() => { theBool = true; Console.WriteLine("Changed it."); });
while (!theBool) { }
Console.WriteLine("Done");
```

In both debug and release configurations, that `"Changed it."` text is displayed.

**Comment by CyrusNajmabadi** [comment]
As this is read and written from multiple threads, isn't some sync primitive needed?

**Comment by rbwhitaker** [comment]
> As this is read and written from multiple threads, isn't some sync primitive needed?

That's a fair point. And putting a lock around both threads' usage of the variable does actually solve the problem. And pushing the variable to a field in an object instead of a local variable, and putting `volatile` on it seems to have also addressed it. (Too bad you can't put `volatile` on a local variable, since the variable is getting shunted off to a closure object anyway.)

On the other hand, I'd have thought that a read and write of a `bool` would be atomic. I could also imagine something being in the CPU's cache rather than main memory for a while, but I'd have thought that would eventually resolve itself. Just that the loop might take some extra cycles until the cached version is pushed back to main memory where it can be read by another thread.

Having said that, I can agree that it is more correct for there to be a sync primitive applied here, and it does solve my problem. It still strikes me as weird or problematic that there's such a stark difference in behavior between debug and release mode. But I can be on board with the response of, "This deserves a synchronization primitive, and once that's done, the problem no longer exists." So if you want to close this out, I'm fine with that.

**Comment by svick** [comment]
@rbwhitaker There is such a stark difference, because this is an optimization the JIT is allowed (but not required) to make. Specifically, in the absence of synchronization primitives (like `lock` or `volatile`), it is allowed to assume that no other thread will interfere with the execution of the method and make any changes that would not change behavior under such circumstances.

Specifically, the `while` loop [compiles into](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuArANxFEBuEATmQgBYCmAQgPa8AbMgF4yAMwgCUnOsQBsAOgBKAVxgAKdQEoRAPjIBvNlz6CRbZiplkAvltkB3dlAGcy6gIQce/ATqM2RJQAnOoARAAivDCcYfZAA===):

```asm
    L0034: movzx ecx, byte ptr [esi+4]
    L0038: test ecx, ecx
    L003a: je short L0038
```

This is the equivalent of:

```c#
var copy = closure.theBool;
while (!copy) {}
```

Which explains why the code doesn't terminate.

**Comment by rbwhitaker** [comment]
That's a great explanation. Thanks for helping me understand!
