### ISSUE TITLE
API sample tests are not running

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6422]
The API sample tests are not running as they are MSTest-based. Either we should kill the projects, or convert them to xUnit.

**Comment by davkean** [comment]
When this is done, you should update the names of the tests, or update BuildAndTest.proj and internal's test's include pattern to include it.

**Comment by tmeschter** [comment]
My vote is to kill these projects. We haven't really tried to keep them up-to-date.

**Comment by davkean** [comment]
Which projects? I have zero context on this.

**Comment by tmeschter** [comment]
There's also issue #4442, which hinges on whether or not we want to keep the samples or delete them. That one is assigned to @AnthonyDGreen to decide.

**Comment by tmeschter** [comment]
As for which projects, I think we're talking about the entirety of https://github.com/dotnet/roslyn/tree/master/src/Samples.

**Comment by codespare** [comment]
Those samples are often useful to get a hang of the public API. Most other tests have internal visibility and not as useful in that regard as seen from the 'outside'.
