### ISSUE TITLE
[Flaky Build] VbiCore,VbcCore, CsiCore and CscCore are deploying the same binaries to output causing races

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6423]
These projects appear to be all copying CoreCLR to the output directory:

```
  VbiCore -> D:\roslyn\Binaries\Debug\core-clr\vbi.exe
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): warning MSB3026: Could not copy "C:\Users\davkean\.nuget\
packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.1-beta-23428\runtimes\win7-x64\lib\dotnet\mscorlib.ni.dll" to "D:\roslyn\Binaries\
Debug\core-clr\mscorlib.ni.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\roslyn\Binaries\Debug\core-clr\mscorlib.ni.dl
l' because it is being used by another process. [D:\roslyn\src\Compilers\VisualBasic\VbcCore\VbcCore.csproj]
  CscCore -> D:\roslyn\Binaries\Debug\core-clr\csc.exe
  CSharpResultProvider.Portable -> D:\roslyn\Binaries\Debug\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll
```

and:

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): warning MSB3026: Could not copy "C:\Users\davkean\.nuget\
packages\runtime.win.System.Text.Encoding.CodePages\4.0.1-beta-23428\runtimes\win\lib\dotnet5.4\System.Text.Encoding.CodePages.dll" to "D:\roslyn\
Binaries\Debug\core-clr\System.Text.Encoding.CodePages.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\roslyn\Binaries\D
ebug\core-clr\System.Text.Encoding.CodePages.dll' because it is being used by another process. [D:\roslyn\src\Compilers\CSharp\CscCore\CscCore.csp
roj]
```

This is happening every build for me.

**Comment by davkean** [comment]
tag @agocke

**Comment by agocke** [comment]
How would we fix this?

**Comment by davkean** [comment]
@jasonmalinowski 

Basically, this is a problem because we're deploying to the same directory. Do we want to actually copy CoreCLR to the build directory? What are we getting out of that?  

Jason fixed a bunch of projects to stop copying binaries. If we do want to copy, then we should have a single project that determines this - otherwise you're going to run into weird issues where you have torn builds, for example, if VbiCore updated to v2 of CoreCLR, but everyone else had v1, you might get a mixture copied into binaries.

**Comment by jasonmalinowski** [comment]
Honestly, I'd vote that all CoreCLR projects just compile to project-specific subfolders. It's trivial to set up and doesn't require care to maintain. Yes, it'll take a bit more disk space, but cost is on the order of pennies, versus the many dollars of dev time we'll waste trying anything else.

**Comment by tmat** [comment]
@jasonmalinowski At some point most tests will be CoreCLR projects. We don't want 50 copies of CoreCLR. The size is actually significant. CoreFX is doing that and their bin directory is ~2GB and have like 15000 files after running tests.

**Comment by tmat** [comment]
@agocke Do we actually need to copy CoreCLR? CoreRun seems to work just fine if the app is in a different directory than CoreCLR.

**Comment by tmat** [comment]
@agocke I guess the problem is that CoreCLR is not a single nuget that contains everything but rather a multiple ones whose content need to be copied? If so then having a single project that does that and all our CoreCLR projects depend on makes sense.

**Comment by davkean** [comment]
I don't think it makes sense for a portable project to deploy the runtime binaries for a single runtime. What if we want to run this on desktop, are we deploying the right binaries? Or Linux? Or Mac?

Deployment should be a separate step, not part of build.

**Comment by davkean** [comment]
I think we should opt all projects out of nuget deployment, and only those that explictly opt-in should get it. This will avoid these issues in the future.

**Comment by tmat** [comment]
@davkean I agree it should. Does NuGet support deployment? I don't think it does.

**Comment by davkean** [comment]
This would could be just a explict deployment target/project that involves the NuGet build task.

**Comment by tmat** [comment]
As a workaround, until deployment story is figured out I propose we add project CoreRuntime that all portable projects depend on that deploys CoreCLR. In addition we should introduce configurations DebugCore/ReleaseCore that changes what runtime is used for F5/xunit run.

**Comment by davkean** [comment]
Okay, I played around with this and flipped the default on this, so that "by default" projects do not copy NuGet implementations. This resulting in only a handful of files different between a build with this turned on by default, and this turned off by default:

```
.\core-clr\microsoft.visualbasic.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.componentmodel.dataannotations.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.core.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.net.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.numerics.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.runtime.serialization.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.servicemodel.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.servicemodel.web.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.windows.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.xml.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.xml.linq.dll	only in D:\roslyn\Binaries\Debug - Before
.\core-clr\system.xml.serialization.dll	only in D:\roslyn\Binaries\Debug - Before
```

These look like the PLIB compatibility pack, and tests appear to be passing, so we're probably not using these (they aren't actually supported on CoreCLR anyway). I'm going to submit a PR with this.
