### ISSUE TITLE
static interface methods not emitted when interface marked ComImport

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#64238]
Not sure if this is a bug, an unexpected scenario, or a self-inflicted "just don't do that" thing, but: consider interface:

``` c#
public interface IFoo
{
    void Bar();
    static void Blap() => System.Console.WriteLine("IFoo.Blap");
}
```

This works fine; we can call `IFoo.Blap();`

Now imagine we decorate `IFoo` with `[ComImport]` and `[Guid]` - *because we can* (see below); at this point, the compiler *no longer emits the method body*; instead of

``` msil
    .method public hidebysig static 
        void Blap () cil managed 
    {
        // Method begins at RVA 0x2067
        // Code size 11 (0xb)
        .maxstack 8

        IL_0000: ldstr "IFoo.Blap"
        IL_0005: call void [System.Console]System.Console::WriteLine(string)
        IL_000a: ret
    } // end of method IFoo::Blap
```

we get:

``` msil
    .method public hidebysig static 
        void Blap () cil managed 
    {
    } // end of method IFoo::Blap
```

If we run the code, we now get a `TypeLoadException`, citing

> Could not load type 'IFoo' from assembly '(whatever)' because the method 'Blap' has no implementation (no RVA).

This seems ... unexpected. Not sure if this is an internal limitation due to some legacy feature of `[ComImport]`, or ... what! And yes, I acknowledge that anything under `System.Runtime.InteropServices` is basically "there are no rules here" territory.

Proposals:

1. make it emit the method body (presumably there's an `if` test that is hitting an unanticipated combination of scenarios), or
2. make it emit a compiler error/warning that this scenario is not going to work

---

As for why we might want to do this... well, historically, before static interface methods existed, the following is a sneaky way to allow instantiation of interfaces (perhaps when the concrete type is generated and unobvious - think "service proxies" etc). A `static IFoo Create() {...}` method would also have worked, but is both TFM and langver dependent, where-as `[CoClass]` et al work *all* the way back.

``` c#
IFoo obj = new();
obj.Bar();
// IFoo.Blap();

[global::System.Runtime.InteropServices.ComImport]
[global::System.Runtime.InteropServices.Guid("00112233-4455-6677-8899-aabbccddeeff")]
[global::System.Runtime.InteropServices.CoClass(typeof(Foo))]
interface IFoo
{
    void Bar();
    // static void Blap() => Console.WriteLine("IFoo.Blap");
}
class Foo : IFoo
{
    void IFoo.Bar() => Console.WriteLine("Foo.Bar");
}
```

[Here's a sharplab of the same](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTBJAYge3wAJ9gArIgXiJgFMB3ACgEoBuTUsgOgCEIAnFuwx5CvADYQADkMyYA2gHNxpCOJAgEKLgCUArjAAuUMLS7YjtfvikBlKwDcoAY1oBnLgGF8YbGCn4/IYAugrKquqa2vpGJmYWhlY29vxOrh4A4npQACaMAEQADIUoKEhIAMwVALQALLUArA3VAGwtAOzt1QAc3QCcfdUQEMDAzs45ObS0AGYz+cyhGEoqwGoaWroGxqbmltZ2ji7uXviekm5ujIYAnlK0+DOMBPjMi5iwifwzEK5EovhMABvTBEMFEBC1Ih8QRsUHgrQtCFQniSGTMKgAPghKD6BQBEmkC2EAF9MMgiC8iCB/i9gfCwZDaWIYSwsTi8fkXrwBMTMCSgA=) - see the reversed C#:

``` c#
[ComImport]
[Guid("00112233-4455-6677-8899-aabbccddeeff")]
[CoClass(typeof(Foo))]
internal interface IFoo
{
    void Bar();

    static void Blap();
}
```

**Comment by AlekseyTs** [comment]
It looks like method bodies in ComImport interface are not supported by runtime. If compiler emits one, the following exception is thrown at runtime:
```
System.TypeLoadException : Method with non-zero RVA in an Import.
``` 

Compiler should report an error instead of silently dropping bodies.

**Comment by MichalStrehovsky** [comment]
> It looks like method bodies in ComImport interface are not supported by runtime. If compiler emits one, the following exception is thrown at runtime:

Cc @dotnet/interop-contrib on whether this is deliberate.

**Comment by jkoritzinsky** [comment]
I believe this is intentional behavior that we've had since DIMs were introduced (or possibly earlier)

**Comment by AaronRobinsonMSFT** [comment]
> I believe this is intentional behavior that we've had since DIMs were introduced (or possibly earlier)

Yes, this is intentional. Interfaces marked with `ComImport` are intentionally excluded from DIM support. This can be reconsidered, but it would be a feature and require investigation into all the nuances of how they could impact the COM interop scenario.

Like most things in the built-in COM interop system we are reluctant to change or expand functionality because its primary intended use is transitioning from .NET Framework to .NET Core/.NET 5+. For .NET 8, we are working on a [source generator solution for COM interop](https://github.com/dotnet/runtime/issues/66674) that will be the way forward.

**Comment by MichalStrehovsky** [comment]
> Yes, this is intentional. Interfaces marked with ComImport are intentionally excluded from DIM support.

Just a note that this is about a static method, not a DIM. Static methods on interfaces were supported by the runtime since ~.NET 1.0 (long before DIM in any case).

**Comment by mgravell** [comment]
Really insightful - thanks; TIL a few more things (that I wish I hadn't) about COM interop!

I suspect the real thing here, then, is that the compiler should at least log something about this, and not just swallow method bodies silently.

**Comment by AlekseyTs** [comment]
> I suspect the real thing here, then, is that the compiler should at least log something about this, and not just swallow method bodies silently.

See https://github.com/dotnet/roslyn/pull/64257
