### ISSUE TITLE
Add a new Location.Create overload for external file location with a different mappedLineSpan

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#64236]
## Background and Motivation
TypeScript would like to create `ExternalFileLocation` for TS diagnostics reported on their secondary projection buffers, such that the diagnostic location has a different mapped location pointing to the primary buffer (separate file and line span), for display purposes, such as in the error list. The core story behind their request is as below:

> The story is that currently projection script blocks in HTML and ASPX have the same URI as the original file, causing problems with LSP scenarios since the editor expects unique URIs for every buffer. This produces all kinds of buffer/snapshot errors, including diagnostic squiggles being shifted, exceptions from the LSP editor code, etc. Todd helped me get a fix for this that involves using a [different name for these projection buffers](https://devdiv.visualstudio.com/DevDiv/_git/WebTools/commit/587323f525ca72627c26d94799de5aa717481b06?refName=refs%2Fheads%2Fdev%2Ftoddgrun%2FAddContainedBufferTextDocumentName3), but then I had to [update TypeScript-VS](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/TypeScript-VS/pullrequest/423511) because all of our script block handling code has always assumed that projection buffers use the same file name as the original documents.

> And so now the update in TypeScript-VS is almost ready to go except for this issue with diagnostics, since Roslyn won't allow me to display diagnostics with the primary/mapped buffer's file name (since the workspace doesn't have a document with that name, it has been using the secondary buffer name).

## Proposed API
Currently, `Location.Create` public API for creating external file locations only supports providing a single lineSpan, which is used as both the actual line span and the mapped line span.

https://github.com/dotnet/roslyn/blob/620a86b61272b794670bbbf5a425bfa7ec59ce91/src/Compilers/Core/Portable/Diagnostic/Location.cs#L168-L179

https://github.com/dotnet/roslyn/blob/0f83d53179cd936842c743ad5dd48bc41cbbfb80/src/Compilers/Core/Portable/Diagnostic/ExternalFileLocation.cs#L35-L43

The public API request is to add a new `Location.Create` overload that supports mapped file + line span, either one of the below public APIs would suffice.

### Proposal 1
Draft PR for this proposal: #64240
```diff
namespace Microsoft.CodeAnalysis
{
     public abstract class Location
     {
+        public static Location Create(string filePath, TextSpan textSpan, LinePositionSpan lineSpan, string mappedFilePath, LinePositionSpan mappedLineSpan);
     }
```

### Proposal 2
```diff
namespace Microsoft.CodeAnalysis
{
     public abstract class Location
     {
+        public static Location Create(TextSpan textSpan, FileLinePositionSpan lineFileSpan, FileLinePositionSpan mappedFileLineSpan);
     }
```

**Comment by MariaSolOs** [comment]
@mavasani I'm not sure if `public static Location Create(string filePath, TextSpan textSpan, LinePositionSpan lineSpan, LinePositionSpan mappedLineSpan);` is the right overload, since it doesn't fix the different file name issue.

`ExternalFileLocation`s are created as follows:
https://github.com/dotnet/roslyn/blob/620a86b61272b794670bbbf5a425bfa7ec59ce91/src/Compilers/Core/Portable/Diagnostic/ExternalFileLocation.cs#L14-L43
Line 33 is what's causing diagnostics in the error list to use the file name given to the projection buffer, and not the one of the containing document.

I instead suggest adding a location variant that takes 2 different file names such that we can have the following: 
```
private readonly TextSpan _sourceSpan;
private readonly FileLinePositionSpan _lineSpan;
private readonly FileLinePositionSpan _mappedLineSpan;

internal ExternalMappedFileLocation(string filePath, string mappedFilePath, TextSpan sourceSpan, LinePositionSpan lineSpan)
{
  _sourceSpan = sourceSpan;
  _lineSpan = new FileLinePositionSpan(filePath, lineSpan);
  _mappedLineSpan = new FileLinePositionSpan(mappedFilePath, lineSpan);
}

public override FileLinePositionSpan GetLineSpan()
{
  return _lineSpan;
}

public override FileLinePositionSpan GetMappedLineSpan()
{
  return _mappedLineSpan;
}
```

**Comment by mavasani** [comment]
@MariaSolOs the term "LineSpan" and "MappedLineSpan" is a kind of a misnomer here, it's type is actually FileLinePositionSpan, and it denotes file + span within the file https://github.com/dotnet/roslyn/blob/620a86b61272b794670bbbf5a425bfa7ec59ce91/src/Compilers/Core/Portable/Diagnostic/FileLinePositionSpan.cs#L12-L32

With this new overload, you should be able to create a `mappedLineSpan` that points to a different file as compared to `lineSpan`: https://github.com/dotnet/roslyn/blob/620a86b61272b794670bbbf5a425bfa7ec59ce91/src/Compilers/Core/Portable/Diagnostic/FileLinePositionSpan.cs#L43-L61

**Comment by mavasani** [comment]
@MariaSolOs Ah, I see your point. `Location.Create` method actually takes a `LinePositionSpan`, not a `FileLinePositionSpan`. Let me update the proposal.

**Comment by 333fred** [comment]
### API Review

* FileLinePositionSpan has a boolean that indicates if it's a mapped path, which isn't settable externally.
    * This is implicit information in proposal 2, so we're leaning towards proposal 1.

**Conclusion**: Proposal 1 is approved.
