### ISSUE TITLE
InvalidCastException: cannot cast NonErrorNamedTypeSymbol to IMethodSymbol

### ISSUE THREAD

**Issue by ladenedge** [dotnet/roslyn#64251]
**Version Used**: 

VS 17.4.0 Preview 2.1
.NET 7 RC1 [7.0.100-rc.1.22431.12]

**Steps to Reproduce**:

Unfortunately no indication of the offending code is provided in the error.  I use Interop extensively in my project, if that helps any.

**Expected Behavior**:

This warning was not present with earlier versions.  Alternatively, some indication of the offending code would be useful, of course.

**Actual Behavior**:

> Warning	AD0001	Analyzer:
> 'Microsoft.Interop.Analyzers.NativeMarshallingAttributeAnalyzer' threw an exception of type 'System.InvalidCastException' with message
> 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.'.
> MyProject C:\Source\MyProject\CSC	1	Active	Analyzer Failure

Please let me know if I can provide additional information.

**Comment by Youssef1313** [comment]
Probably fixed in https://github.com/dotnet/runtime/pull/72535.

@jkoritzinsky Are you able to confirm? Thanks!

**Comment by jkoritzinsky** [comment]
Yep that PR has the fix.

Closing this as a duplicate
