### ISSUE TITLE
Update docs.microsoft.com links to learn.microsoft.com

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#64268]
It looks like docs.microsoft.com has moved to learn.microsoft.com

The most important link to update is:

https://github.com/dotnet/roslyn/blob/de96b01ccc6c51d2ad0501df18475079fbe2c7e1/src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs#L276

But consider updating *all links* (even code comments).

**Comment by Youssef1313** [comment]
FYI @mavasani

**Comment by Bosch-Eli-Black** [comment]
@Youssef1313 BTW, some previous links to documentation that were working are now broken after being redirected to `https://learn.microsoft.com` 🙂

For example: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexgeneratorattribute.-ctor

**Comment by Youssef1313** [comment]
@Bosch-Eli-Black This has nothing to do with the move from docs to learn. This happened because of https://github.com/dotnet/runtime/pull/72434

**Comment by Bosch-Eli-Black** [comment]
@Youssef1313 Lol, oh! 😆  Thank you! 🙂
