### ISSUE TITLE
VS2022 C# cannot remove IDE0220 code style warnings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64289]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-C-cannot-remove-IDE0220-code-sty/10146419)._

---
[severity:It bothers me. A fix would be nice]
Even though I've set all code style warning options to None as best I can, I cannot find a way to remove this warning other than in source or in suppression file, although suppression does work, I think I would have to suppress it in every project.
I admit the code is not safe, however, this is a sample function illustrating the issue.
This message was not showing before 09/13/2022, not sure why it started showing today. Can be seen in the sample function DisposeElements.
[WindowsFormsApp2.zip](https://aka.ms/dc/file?name=B283c71e862ed4771831a7cb2b06d26ea637986806014786290_WindowsFormsApp2.zip&tid=283c71e862ed4771831a7cb2b06d26ea637986806014786290)
 Thank you.

---
#### Feedback Bot on 9/13/2022, 08:09 PM: 

(private comment, text removed)

---
#### xa sunpots solved on 9/15/2022, 10:10 AM, 0 votes: 

<p>Dear Microsoft Dev,<br>
I am also getting used to all the new Blue compile warnings in 2022 which were not there in 2017 and actually I appreciate them in some cases and also I’m becoming able to deal with them.<br>
So please remove my complaint and please forgive me for being a pissy little [Redacted].<br>
Thank you.</p>

**Comment by CyrusNajmabadi** [comment]
We will need information on what actual warning they're getting that they cannot configure.
