### ISSUE TITLE
Intellisense does not recognize start of string, changes "D: to "Date:

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64280]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-does-not-recognize-start-of/10150751)._

---
[severity:I'm unable to use this version]
I want to type the following:

    Dim sPath As String="D:\somefile.txt"

After I type....

    Dim sPath As String = "D:

... Intellisense changes it to 

    Dim sPath As String = "Date:

Please see the attached video.

Obviously, Intellisense does not recognize that I have started typing a string when I entered ".

A video is attached.

---
#### Feedback Bot on 9/18/2022, 06:57 PM: 

(private comment, text removed)
#### Feedback Bot on 9/26/2022, 10:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
Hmm, not able to repro with a console app. it was correctly parsed as a string

![image](https://user-images.githubusercontent.com/788783/192366040-15e1bcae-7d31-438e-9254-55f5914f6c2e.png)

 I suspect another string literal somewhere in the file might be involved but can't say for sure with the information provided. Keep this open for now to see if someone could provide a better repro
