### ISSUE TITLE
VS refactor suggests an incorrect pattern matching for `!(a?b is true | false)`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-refactor-suggests-an-incorrect-patter/10156290)._

---
VS refactor suggests expression like `!(a?.b is true)` to `a?.b is false`, which is incorrect because of nonequivalent. 

![image.png](https://aka.ms/dc/image?name=B99e62db13a254e10a2f71c752980eabd637995332467414291_20220923-203405-image.png&tid=99e62db13a254e10a2f71c752980eabd637995332467414291)

---
#### Feedback Bot on 9/25/2022, 06:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by kimsey0** [comment]
This type of problem seems to occur elsewhere as well. For example, asking Visual Studio to _Replace '||' with '&&'_ in `true || a?.b is true` results in `!(false && a?.b is false)` instead of the expected `!(false && a?.b is not true)`.

**Comment by kimsey0** [comment]
Thinking further about this, swapping `is true` and `is false` patterns is only valid if the value is Boolean, since no non-Boolean values match either pattern. For example, swapping isn't valid in this instance either:
```csharp
object a = 123;
if (!(a is true)) ;
```

**Comment by CyrusNajmabadi** [comment]
@jnm2 did you just fix this?

**Comment by kimsey0** [comment]
#64432 from @jnm2 seems to fix a similar but separate issue for comparison operators. I've just submitted #64520 which I believe fixes this problem with `is true` and `is false` patterns.

**Comment by jnm2** [comment]
And I also wonder about `is <` etc.

**Comment by kimsey0** [comment]
Inequality patterns seem to always be negated with a `not`. That's valid in all cases, but doesn't lead to the prettiest result for numeric types. For example, negating `123 is > 10` results in `123 is not > 10`, where I'd prefer `123 is <= 10`. We could create a new issue for this.

**Comment by CyrusNajmabadi** [comment]
> We could create a new issue for this.

yes please.

**Comment by kimsey0** [comment]
I created the issue linked above. 😄
