### ISSUE TITLE
Type inference for GFU and friends doesn't infer method to return Task if ConfigureAwait is used

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#643]
Ported from TFS WorkItem: <b>809537</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1. Add the following inside Main() inside a new console app:</P><FONT size=2 face=Consolas><FONT size=2 face=Consolas>
<P></FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas></FONT></FONT></FONT>&nbsp;</P>
<P><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>bool</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> x = </FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>await</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas> Foo().ConfigureAwait(</FONT></FONT><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas><FONT color=#0000ff size=2 face=Consolas>false</FONT></FONT></FONT><FONT size=2 face=Consolas><FONT size=2 face=Consolas>);</P></FONT></FONT>
<P>&nbsp;</P>
<P>2. Try GFU on Foo()</P>
<P>&nbsp;</P>
<P><STRONG>Expected:</STRONG> it infers a return type of Task&lt;bool&gt;</P>
<P><STRONG>Actual:</STRONG> it infers a return type of object.</P>
<P>&nbsp;</P>
<P>NB that if we remove the configure await, we do infer Task&lt;bool&gt;. It looks like the inference service needs to be caught about ConfigureAwait specifically, or more generally if you're awaiting the result of a method, we might want to see if that method is defined or is an extension of Task or Task&lt;T&gt;. The latter algorithm would also allow for things like:</P>
<P>&nbsp;</P>
<P>bool x = await Foo().SafeContinueWith(false)</P>
<P>&nbsp;</P>
<P>to infer something more useful.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Jason Malinowski (10/24/2013 5:40:24 PM)

------------------------------

2) Edited By Dustin Campbell (8/12/2014 3:52:21 PM)

Diagnostics team -- it looks like this one might be more appropriate on your plate?

------------------------------

3) Edited By Dustin Campbell (8/12/2014 3:52:46 PM)

Eh.. maybe not.

------------------------------

4) Edited By Kevin Pilch-Bisson (2/16/2015 3:45:10 PM)

Moving to Diagnostics for GFU.

------------------------------

**Comment by jmarolf** [comment]
@srivatsn Could you verify this please?
