### ISSUE TITLE
Crash (InvalidOperationException) when hovering/clicking in .cshtml files...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#6430]
![capture](https://cloud.githubusercontent.com/assets/6464209/10832246/89a61a36-7e47-11e5-94e7-0467220dac4a.PNG)

- Create an ASP Web App.
- Modify an existing .cshtml file to include the code above.
- Hover/click in the indicated location.

**Comment by dpoeschl** [comment]
@KevinH-MS The fix was merged, right? Is this still active? Tagging anyway, for @mavasani's info.

**Comment by KevinH-MS** [comment]
Yes, fixed
