### ISSUE TITLE
Missing closing parenthesis on auto-completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64328]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-closing-parenthesis-on-auto-comp/10129989)._

---
[severity:It bothers me. A fix would be nice]
When using auto-completion for method declarations or control statements the editor suggests the opening parenthesis as on the picture below:
![image.png](https://aka.ms/dc/image?name=Bc2807a0dc2ac4c2c9ab3c42883a15cbd637969505538254953_20220824-170913-image.png&tid=c2807a0dc2ac4c2c9ab3c42883a15cbd637969505538254953)
But when I hit tab to auto-complete it does not insert the closing parenthesis automatically.  When I then hit enter to start the body it still does not insert the closing parenthesis and I end up having to place it manually and return to the block body which is quite annoying.
![image.png](https://aka.ms/dc/image?name=Bf54d208fe87a4a0ba7799e2dd54fdbdc637969509829734489_20220824-171622-image.png&tid=f54d208fe87a4a0ba7799e2dd54fdbdc637969509829734489)
![image.png](https://aka.ms/dc/image?name=B3102a1e014a5458cb5e029fe532d4bd4637969510069665197_20220824-171646-image.png&tid=3102a1e014a5458cb5e029fe532d4bd4637969510069665197)

---
#### Feedback Bot on 8/24/2022, 06:19 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/29/2022, 11:47 PM: 

(private comment, text removed)
#### Shin Q'dan on 9/7/2022, 06:59 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/29/2022, 11:48 PM: 

(private comment, text removed)
#### Feedback Bot on 9/6/2022, 07:38 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/15/2022, 07:51 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/16/2022, 01:57 AM: 

(private comment, text removed)
#### Shin Q'dan on 9/16/2022, 03:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
this is not roslyn, this is intellicode.  @dibarbet  can you redirect?

**Comment by dibarbet** [comment]
re-opened the feedback and moved to intellicode.  Closing this issue as external.
