### ISSUE TITLE
Intellisense should not suggest such improbable suggestions and should delete suggestion at a single Backspace keypress

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64326]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-should-not-suggest-such-imp/10096990)._

---
[severity:It bothers me. A fix would be nice]
Hello!
 
I accidentally type "Sim" instead of "Dim", and Intellisense turns this into "SimpleBookmark ".

I have never used "SimpleBookmark", and Intellisense should not suggest it.

Intellisense should be smarter.

And when I type Backspace after an Intellisense mistake, it should immediately delete the entire suggestion and not have me delete each character by pressing Backspace again and again.

---
#### Feedback Bot on 7/17/2022, 07:43 PM: 

(private comment, text removed)
#### Feedback Bot on 7/18/2022, 00:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by arkalyanms** [comment]
Ask#1: The backspace suggestion to remove the entire word if backspace immediately follows completion seems reasonable. 
Ask#2: The ranking ask in the suggestions on the other hand that tracks per user history of usage is likely not going to be covered here. 

Adding the "up for grabs" tag to cover ask#1.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not intending to invest in these particular scenarios.
