### ISSUE TITLE
Code lens don't work for source-generated files

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64348]
**Version Used**:
VS 17.3.3

**Steps to Reproduce**:
1. Create MAUI App
2. Install `CommunityToolkit.Mvvm` Nuget package
3. Create class that derives from `ObservableObject`
4. In that class declare a method and annotate it with `[RelayCommand]` - this causes source generation
5. Open Code Lens for that method

**Expected Behavior**:
CodeLens shows correct list of references and do go-to-source when I click them

**Actual Behavior**:
CodeLens shows correct list of references but clicking generated ones doesn't do anything:
![Bug](https://user-images.githubusercontent.com/70431552/192880485-398e945d-1533-4552-9328-32d42c8cc43a.gif)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in SG scenarios.
