### ISSUE TITLE
extract interface (vb) does not handle commented code correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/extract-interface-vb-does-not-handle-c/10084115)._

---
[severity:It bothers me. A fix would be nice]
When using the extract interface Quick Refactoring on a class which contains inline comments at the end of  a member definition, the Implements keyword is added on a new line (following the comment).

Steps to reproduce
1. Create a class
```
Public Class TestClass
    Public Property Commented As Boolean 'comment included

    Public Property Uncommended As Boolean
End Class
```
2. Right click the class name and select Quick Actions and Refactorings...
3. Select Extract Interface

The resulting code contains an error in the way that `Commented` is refactored
```
Public Interface ITestClass
    Property Commented As Boolean
    Property Uncommended As Boolean
End Interface

Public Class TestClass
    Implements ITestClass

    Public Property Commented As Boolean 'comment included
    Implements ITestClass.Commented
    Public Property Uncommended As Boolean Implements ITestClass.Uncommended
End Class
```

---
#### Feedback Bot on 6/29/2022, 07:50 PM: 

(private comment, text removed)
#### Feedback Bot on 7/5/2022, 00:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not planning on more investments here.
