### ISSUE TITLE
Normalize all usages of CultureInfo("en-US")

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#6442]
As discussed in PR #6266 and #6404, the current fallback culture for many IDE operations is **`en-US`** and instead of re-creating this multiple places in our codebase, one central property/method should be created to better handle the potential scenario of **`en-US`** no longer being the proper default, or if more complex logic needs to be implemented.

Examples of where **`en-US`** is explicitly used and could potentially be replaced:
- [`CaseInsensitiveComparison`](http://source.roslyn.io/#Microsoft.CodeAnalysis/CaseInsensitiveComparison.cs,172aceef738c9be5)
- [`CompletionRules` in a PR into `stabilization`](https://github.com/dotnet/roslyn/pull/6266)
- [`USCultureInfo` field](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/Extensions.cs,197ebf1ddc966de3)

**Comment by dpoeschl** [comment]
/cc: @jinujoseph (you may be interested in this general discussion)

**Comment by CyrusNajmabadi** [comment]
Unlikely to do anything here.
