### ISSUE TITLE
The Roslyn directory artifacts\bin weights 11.8 GB ?

### ISSUE THREAD

**Issue by ndepend** [dotnet/roslyn#64435]
I compiled Roslyn v6.0.1 and the directory `artifacts\bin` weights 11.8 GB. 

The 3,29MB Roslyn DLL `Microsoft.CodeAnalysis.dll`  is duplicated 117 times for a total footprint of 377 MB.

The 24MB DLL `Microsoft.CodeAnalysis.Test.Utilities.dll ` is duplicated 75 times for a footprint of 1.75 GB.

This massive duplication consumes significant hard-drive space and must have a (slight?) impact on Roslyn build duration.

Is there a well identified reason to not have only a few DEBUG binary directories like `artifacts\bin\Debug\net6.0`, `artifacts\bin\Debug\net472,` `artifacts\bin\Debug\netstandard2.0`... ?

The [windirstat](https://windirstat.net/) view:

![Roslyn Windirstat View](https://user-images.githubusercontent.com/511445/193515482-fc179ef7-9653-463d-98a7-3ab3a7966548.png)

![Roslyn bin weight](https://user-images.githubusercontent.com/511445/193514606-94cd0d70-d93d-4e33-bc67-d2282d764489.png)

![Roslyn DLL duplicated](https://user-images.githubusercontent.com/511445/193514634-edb40a2d-1543-4e08-a381-dbfdd911b2c6.png)

![Roslyn DLL duplicated bis](https://user-images.githubusercontent.com/511445/193514660-f3b17ca3-2bab-448f-b27e-4486d4af4162.png)

**Comment by RikkiGibson** [comment]
Setting the environment variable `ROSLYNUSEHARDLINKS` to `true` will reduce this size quite a bit though you might need to use a utility like [`du`](https://learn.microsoft.com/en-us/sysinternals/downloads/du) to accurately measure it.

@jaredpar it seems like hard links have been working in CI for a while now. See #50178. Maybe we should turn them on by default?

**Comment by jaredpar** [comment]
> it seems like hard links have been working in CI for a while now. See https://github.com/dotnet/roslyn/pull/50178. Maybe we should turn them on by default?

The issue is that certain Visual Studio features do not work well with hard linking. IIRC it's designer based scenarios that break which is why we keep it disabled by default.

> must have a (slight?) impact on Roslyn build duration.

When measured we've found that in terms of performance on modern SSD it has very little performance impact for builds. 

> Is there a well identified reason to not have only a few DEBUG binary directories like artifacts\bin\Debug\net6.0, artifacts\bin\Debug\net472, artifacts\bin\Debug\netstandard2.0... ?

That is much harder, if at all possible, to validate for build correctness (aka items like no double writes). Hard linking is presented as an option for those who want to avoid the duplication.
