### ISSUE TITLE
Auto add using as global

### ISSUE THREAD

**Issue by jrahma** [dotnet/roslyn#64443]
### Description

Hi,

It will be great to automatically add all using to the global using class file by default.

If not then,  the user should decide so if he created a Using.cs class and added the using then all the new Usings should also be added there instead of him doing the cut and paste every time.

### Public API Changes

Code Improvment

### Intended Use-Case

Code Improvment

**Comment by Eilon** [comment]
I believe these code fixes are all part of Roslyn? I don't think .NET MAUI does anything for these as it's just a C# editor feature.

**Comment by genlu** [comment]
@jrahma Thanks for the feedback. Close because this is a duplicate of https://github.com/dotnet/roslyn/issues/55895
Please use the linked issue for future reference/discussion.
