### ISSUE TITLE
Autocompletion suggests `struct` after `sealed record`

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64465]
**Version Used**: VS 17.3.5, Roslyn 4.3.0-3.22470.13

**Steps to Reproduce**:

Invoke the autocompletion list after `sealed record`.

**Expected Behavior**:
`struct` is not suggested, just like it is not shown for non-record type declarations that contain the `sealed` modifier.
![grafik](https://user-images.githubusercontent.com/823398/193784801-d9f8fa6c-a2a7-46ce-b41a-8e8dc32c73c9.png)

**Actual Behavior**:
The keyword `struct` is suggested, which is not valid at that location (`struct` and `sealed` are mutually exclusive).
![grafik](https://user-images.githubusercontent.com/823398/193784393-de6a224d-2066-43ce-9bd8-60d9026dbcab.png)

**Comment by CyrusNajmabadi** [comment]
We would take a reasonably sized pr for this if it were suitably simple.

**Comment by jhinder** [comment]
The same problem exists for the modifier `abstract`, which is not valid for structs:
![grafik](https://user-images.githubusercontent.com/823398/194012079-f0b07019-7a57-45d9-aa02-a0cf70ceddb1.png)
