### ISSUE TITLE
Using `KeyValuePair<,>` can result in null reference runtime errors which are not caught by the compiler

### ISSUE THREAD

**Issue by anthony-c-martin** [dotnet/roslyn#64467]
**Version Used**: dotnet 6

**Steps to Reproduce**: This [Sharplab repro](https://sharplab.io/#v2:CYLg1APgxAdgrgGwQQwEYIKYAIMzZgWACgABABixIEYAWAbmJIGZKAmLAYSwG9it/KLEjSwBZABQBKHnwFyAKhgDOAF3HAMAM2SIVkhkTkBfWf1ODKVCotXiA0hgCeANWQI4GAArIAlgCcAHmoyABpLMgA+HBgVP0dJc15DOQESAHZo2McAOgcc+QB7AGVYnxgAcykDY2IjIA===) compiles without warnings, but fails at runtime.

**Expected Behavior**: Warning about a possible null dereference on `Key.ToString()`.

**Actual Behavior**: Code compiles without warnings.

**Comment by jaredpar** [comment]
This behavior is "By Design". One of the limitations of the NRT analysis is that it doesn't apply when assigning `default` to a `struct` value. This was a deliberate decision made to balance the value of NRT vs. the cascade of warnings that would arise if we applied this to existing code patterns.

**Comment by anthony-c-martin** [comment]
Thanks for the explanation!
