### ISSUE TITLE
IDE1006 should trigger build failed

### ISSUE THREAD

**Issue by Furiphan** [dotnet/roslyn#64464]
**Version Used**: 
Visual Studio : 17.3.5
.net version: 6

**Steps to Reproduce**:

1. Create an editorconfig file in your solution
2. Configure Naming style as bellow
![image](https://user-images.githubusercontent.com/93937283/193774175-050b7f69-1090-427a-9233-5dcc5bfbe50d.png)
3. Set IDE1006 severity to error
![image](https://user-images.githubusercontent.com/93937283/193774295-7f3d9753-213a-4081-9032-8dd3c76ce0d7.png)
4. Create the file Directory.Build.props in your solution with this content
`<Project>
	<PropertyGroup>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
	</PropertyGroup>
</Project>`
5. In a project, create a class with a property who doesn't respect naming convention. Sample:
`public string SupplyPoint_Name { get; set; }`
6. Build your solution

**Expected Behavior**:
The build should fail.

**Actual Behavior**:
The build is ok without error.

**Comment by mavasani** [comment]
@Furiphan Do you see IDE0006 being reported as an error in the IDE while typing?

**Comment by Furiphan** [comment]
> @Furiphan Do you see IDE1006 being reported as an error in the IDE while typing?

@mavasani 
I tried and I haven't error in IDE :/
I thought it was Visual Studio who report the issue but it was Resharper.
Without Resharper, no error is displayed.

**Comment by Furiphan** [comment]
> I see that if you name your property to start with a lower case letter, which is a naming violation, the build indeed does fail with IDE1006 error. So, the issue seems to be the naming style settings you are applying are not sufficient to flag the name in the repro. I'll need help from @sharwell @jmarolf to help provide the correct editorconfig option key/value for ensuring the name in the repro triggers a naming violation. I see from the docs at https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#naming-style-properties that you likely need to specify `word_separator` in some fashion to trigger the expected naming violation.

You're right @mavasani ! I try to rename property with lower case letter and the build failed, as expected.
Same case with Interface class without prefixing it by "i".
For the usecase with underscore, I try to specific empty word_separator without success. 
I tried with other value and I think I understand the behavior of word_separator: it isn't for checking if the separator is correct but for **validating pascal case**.
For sample, I tried to put with the letter **b** as word_separator and I have this behavior:
![image](https://user-images.githubusercontent.com/93937283/208724555-b52ee2c9-7aa5-4064-a2f7-c17fa186cab1.png)
For me, it is a helper for detecting the next upper case letter.

So for detecting underscore usage, it is possibly the wrong way.

**Comment by Furiphan** [comment]
I did another test: if I set all letter in upper case with my explained configuration, I haven't error message too :/
![image](https://user-images.githubusercontent.com/93937283/208728976-525aae55-4283-4a72-a726-cebdbdea31ac.png)

**Comment by Furiphan** [comment]
For underscore usage, I found a way to check it:
I enabled the CA1707 as error:
![image](https://user-images.githubusercontent.com/93937283/208729190-99fe5de9-40f8-4597-bd6e-7ce625781509.png)
It works fine.
But i must to add exception for unit test methods who contains underscore (from best practices https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
=> I applied this solutions: https://stackoverflow.com/questions/11359652/suppressmessage-for-a-whole-namespace

**Comment by mavasani** [comment]
@Furiphan Thanks for your replies, seems you are all set then and the original issue about IDE1006 not being reported as error on build isn't applicable. I am going to close this issue, feel free to re-activate/file another issue if you are still running into problems.
