### ISSUE TITLE
Allow "Convert cast" refactorings to work with nullable value types

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64466]
Originally proposed here: https://github.com/dotnet/roslyn/pull/64080#discussion_r974463693

In short, currently "Convert cast" refactorings only work with reference types. The proposal is to make them work with nullable value types, e.g. `(byte?)null` -> `null as byte?` and vise versa

As [suggested](https://github.com/dotnet/roslyn/pull/64080#discussion_r980028433) by @sharwell I already added tests for these cases and currently skipped them in the codebase. Just a reminder for someone who will work on this issue

**Comment by arkalyanms** [comment]
Tagging Cyrus as PR merge buddy.
