### ISSUE TITLE
Suggested UX for Inline Diagnostics

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#64474]
We should consider updating the inline diagnostics UX to be less bulky and align more with other inline experiences: 

Current UX for Inline Diagnostics:
![image](https://user-images.githubusercontent.com/46729679/193903729-e3e1036e-841d-45a1-b474-5b7ba50789e2.png)

Suggested New UX for Inline Diagnostics:
![image](https://user-images.githubusercontent.com/46729679/193904448-7e22210e-08cc-480c-bb7a-94802e23621a.png)

![image](https://user-images.githubusercontent.com/46729679/193904963-569dfcd5-70ea-4984-99da-c1cdda991ccc.png)

![image](https://user-images.githubusercontent.com/46729679/193905870-6e923461-34fc-4249-a2a0-31a139ca90b7.png)

**Comment by CyrusNajmabadi** [comment]
Adding hte words 'error/warning/suggestion' personally feels bulkier to me.

**Comment by CyrusNajmabadi** [comment]
Shoudl we possibly just make the red border not so imposing?  Desaturate or fade it out a bit?  So it still maintains distinction, but isn't as eye-grabbing?

**Comment by mikadumont** [comment]
I can bring it up to UX and see what they say. 

Another suggestion that is a different experience though can be to show the fix inline instead of the diagnostic:

![image](https://user-images.githubusercontent.com/46729679/193913645-d9ed775d-7bf2-40c6-abc0-591349d6fef1.png)

Or

![image](https://user-images.githubusercontent.com/46729679/193914119-6a0be0c1-05b4-4db7-b10c-bc7eca3b90e9.png)

IntellICode is experimenting with this UX.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
