### ISSUE TITLE
Flaky test: CompilerServerUnitTests.ServerWithSamePipeNameExits

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6449]
Server took more than 5 seconds to exit.

http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_dbg_unit64/103/testReport/junit/Microsoft.CodeAnalysis.CompilerServer.UnitTests/CompilerServerUnitTests/ServerWithSamePipeNameExits/

**Comment by davkean** [comment]
I'll dupe this against https://github.com/dotnet/roslyn/issues/6357, and make sure that the timeout is increased for both.
