### ISSUE TITLE
Improve reporting/UI for CS0535: T does not implement interface member M

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#64500]
## Summary

When a signature of a method implementing an interface changes the error CS0535: T does not implement interface member M might be reported. 

![image](https://user-images.githubusercontent.com/41759/194112517-c7a63bc7-2305-4468-96af-216d85dd98d0.png)

The error is displayed in the list of implemented interfaces of the type. The fix however needs to be at the location of the method definition, which may be  elsewhere in the file or even in a different file if the type is partial. 

The user has to find the declaration with mismatched signature and also determine what parameter does not match manually.

The following code fixes are suggested:
![image](https://user-images.githubusercontent.com/41759/194114101-2b4075a7-ea5e-4c08-9b8b-cde252a893c9.png)

There is no code fix that suggests adding/removing/updating parameters that changed.

## Proposed Feature

The IDE can make the process of fixing up the signature more efficient:

1. If methods of the same name are present in the type the IDE can calculate diffs of their signatures w.r.t. the signature required by the interface. Code fix can be offered that applies this diff to a selected overload.

2. The display names of methods in the error message could link to location of a method with the most similar signature as the one required the interface, so that the user can navigate to it by clicking on the link.

3. Related error could be associated with CS0535 for each overload whose signature doesn't match.

**Comment by jasonmalinowski** [comment]
@tmat: all good suggestions! For the last bit do you want this also looked at by the compiler for those diagnostics and we might need to rope them in? Otherwise I'm not sure if there's any design questions here or whether we just need to get this on a backlog.

**Comment by ryzngard** [comment]
@tmat @jasonmalinowski do we have a resolution of if this is ready or does this need design review?

**Comment by CyrusNajmabadi** [comment]
We would need compiler participation wrt. including information that allows diagnostics to have some sort of linked info.

**Comment by CyrusNajmabadi** [comment]
wrt to fixing up the methods, we could do this, but i wouldn't want us to put a ton fo complex code for this case (implement interface is already hugely complex).  i would put this on the backlog as this would def not fit into zinc planning.

**Comment by CyrusNajmabadi** [comment]
Closing out as too compelx to be worth the effort.
