### ISSUE TITLE
Formatting: no setting for spacing after target-typed new keyword, default formatting conflicts with StyleCop's SA1000

### ISSUE THREAD

**Issue by 2BitSalute** [dotnet/roslyn#64509]
This issue is already reported here: https://github.com/OmniSharp/omnisharp-roslyn/issues/2348

I don't know how to link it.

**Comment by CyrusNajmabadi** [comment]
StyleCop is in a different repo.  Issues there aren't fixed here.  Thanks!

**Comment by Youssef1313** [comment]
SA1000 was already fixed. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3561
