### ISSUE TITLE
C# code shown when using "go to definition" should be more readable

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/roslyn#64516]
## Summary

When the "Go to definition" feature of Visual Studio for a .NET type shows decompiled C# code, the code should be made more readable by:
- showing internal and private members after public members (possibly even hiding internal and private members in a collapsed region)
- collapsing the implementation of methods leaving only the declaration (and possibly documentation) visible by default.

## Background and Motivation

Recently I have been observing multiple users trying to write C# code using unfamiliar libraries. I noticed that lots of users employ the "Go to definition" feature of Visual Studio to explore a type and understand how it is used (brows the constructors, factory methods, static properties, etc.) and its documentation. I do the same frequently myself.
I observed most of these users being distracted or even overwhelmed by internal members being shown before public members in the decompiled code. Some of them even closed the document altogether.
Those who went past the internal members, had to scroll a lot because the entire implementation of each method is shown.

## Proposed Feature

Private members at the top of the decompiled code:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/41970398/194175604-2def6271-3989-4c4c-a922-9957be97974d.png">

"Go to definition" for .NET types should show an easily browsable representation of decompiled code. The default presentation should prioritize showing public members, especially constructors and static members first to help the user understanding how the type is used.
Method implementations (actual code inside the methods) should be collapsed by default to reduce the amount of scrolling needed to explore the type.
These behaviors may be configurable as different users may have different preferences.
It would even be possible to have different views (declarations only, full decompilation, etc.) toggleable on the document itself.

## Alternative Designs

N/A

**Comment by jasonmalinowski** [comment]
This is one of those cases the user might still find the old style metadata as source more useful here...

**Comment by CyrusNajmabadi** [comment]
> This is one of those cases the user might still find the old style metadata as source more useful here...

@jasonmalinowski isn't htat possibly by just disabling both of these:

![image](https://user-images.githubusercontent.com/4564579/194419497-55e807c5-5613-4683-9f33-6a1f66ae4f7d.png)

Or just choosing to collapse items like so:

![image](https://user-images.githubusercontent.com/4564579/194419543-da3a23cd-a562-4f7c-958d-8cc64685fd07.png)

I'm not sure hwat else we would offer here.  note: for decompilation, if there is a preference on member order, i think that should go to ILSpy as they control the decompilation strategy here.

**Comment by jasonmalinowski** [comment]
> @jasonmalinowski isn't htat possibly by just disabling both of these:

Absolutely! I despise those checkboxes since they're clumsy if you want a different view -- you have to close the tab, go into options, change them, F12 again, etc. But that's a separate rant.

@matteo-prosperi Do the checkboxes above help out?

**Comment by davidwengier** [comment]
Yeah, I agree, the checkboxes are the solution here. There is a long term plan for the editor to provide more control here, so we could tell them we can provide source from Source Link, decompilation, and metadata, and they can decide (based on user preference presumably) which one to show, and allow the user to switch between them etc.

**Comment by jasonmalinowski** [comment]
@davidwengier What's the editor ask here? New UI or something else?

**Comment by davidwengier** [comment]
No asks yet, but it was all going to be via LSP, and they were going to orchestrate between different providers, do all of the UI, new commands etc. We would just advertise that we know how to provide source from X sources, RichNav would advertise that they could provide source too, and everything was going to come together wonderfully.

No idea when/if any of that work is still scheduled.

**Comment by matteo-prosperi** [comment]
> > @jasonmalinowski isn't htat possibly by just disabling both of these:
> 
> Absolutely! I despise those checkboxes since they're clumsy if you want a different view -- you have to close the tab, go into options, change them, F12 again, etc. But that's a separate rant.
> 
> @matteo-prosperi Do the checkboxes above help out?

Using those checkboxes brought me back to the old experience where I get a very readable list of methods and properties with collapsed docs and not implementation code at all. Which is what I need 90% of the times I use "Go to definition". So that's good

I am also experiencing a bug where after changing those checkboxes to show the metadata, setting them back to the original value doesn't restore the disassembly behavior. I continue getting the metadata only. Even after restarting VS and creating a new project.

I don't think that using those checkboxes is a good solution:
1. they are not very discoverable
2. both the disassembly and the metadata behaviors are useful. You are interested in the metadata 90% of the times. You really want to doublecheck the implementation the other 10%. Having to change the option (even if it worked) would be annoyng.

Either having two separate menu commands or some toggle in the metadata/disassembly document would be best.

Thanks!

**Comment by davidwengier** [comment]
Microsoft internal issue for the larger experience: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1353785

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to chnage things here, we should assign to a dev/milestone so it gets done.
