### ISSUE TITLE
[bug] VSCode crashing with large XML and Markdown files.

### ISSUE THREAD

**Issue by RCcola1987** [dotnet/roslyn#64534]
I have a large xml export that I need to work on in VScode but every time I open it and try to either let VScode remove the bad line end codes or run a plugin on the file VScode will eat up about 7GB ram and then crash.

System Specs:
Windows 10 pro 64bit 1909
128gb ram

VScode info
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.18363
Sandboxed: No

I cannot upload the file since even compressed it is 60mb and git hub only allows up to 25mb.

**Comment by CyrusNajmabadi** [comment]
Closing out. Roslyn is not responsible for xml or markdown files in vscode.
