### ISSUE TITLE
Telemetry to measure configuration switch actions in the language service

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#64547]
Requirement from the project system team:

A regression can be detected via AutoPerf dashboard if we can measure the time taken to complete parsing post receiving the data and would require some additional telemetry data captured from the Roslyn side for the same specifically :
•	Knowing when the parsing completes 
•	How many files were parsed

These events currently do not exist on the Roslyn today but would be good to have the events out there since we are currently live with the language service optimization and would like to start measuring these values early on as customers begin to onboard to capture a baseline.

**Comment by arkalyanms** [comment]
cc: @drewnoakes

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
