### ISSUE TITLE
Add functionality to code snippets to both be able to reference a different replacement and to then execute arbitrary logic on that replacement value

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64540]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-functionality-to-code-snippets-to-bo/10156761)._

---
As a very basic example, say I wanted to produce the following code with a custom code snippet (much like the built in 'propfull' snippet.

```
private string _myString
public string MyString
{
    get => this._myString;
    set => this._myString = value;
}
```
At the moment, I would need to have 3 replacements, one for the type (string), one for the field (_myString) and one for the property (MyString).
Compared to other IDEs this is archaic in its design. Compared to JetBrains Rider (or Resharper) for example, you could achieve this in 2 replacements.
I would like to have 2 replacements, that the user types in, and then a 3rd replacement, which is not editable, which is calculated using either a built in function, or supply a delegate that transforms that value.

For example, again using the snippet above, the snippet would appear, and you would need to type "string" for the replacement for the type, and "MyString" for the property name, but then for the field name, id like to be able to define a way to say "Just take, the replacement for MyString and then make it lower case, and add an underscore at the start". Something like that.
This is totally achievable in resharper/rider live templates. In there you would use built in macros, which would be one option in Visual Studio Command Snippets. Another option would be, in the "Function", to allow a user a supply a custom delegate to transform the string from a different replacement.
i.e. I could set the function as something like
```
input =>
{
     if(string.IsNullOrEmpty(input))
        return "_";

    return "_" + char.ToLower(input[0]) + input.Substring(1);
};
```
Or something like that, where "input" is the reference to the replacement for the "MyString" property name, which would in this case produce "_myString" for the field name, without a user needing to actually type that.

This is a very straightforward example, but in all being able to internally reference replacements results and perform arbitrary logic on them would vastly increase the functionality of the visual studio command snippets, which are currently very feature lacking compared to, particularly IntelliJ based IDEs.
You could have very complex custom command snippets which took input values and mutated them in any number of ways for other replacement values.

I have further suggestions for the command snippets functionality that I will raise separately, if this area of Visual Studio is something that you are willing to actively work on.

---
#### Feedback Bot on 9/26/2022, 00:18 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in legacy snippets.
