### ISSUE TITLE
NFW reduction in external and internal releases

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#64550]
This would cover
- Getting our current faults ([NFWs](https://devdiv.visualstudio.com/DevDiv/_queries/query/019e5e3e-df39-4040-9f20-36f121893118/)) to a clean state, so we can monitor the preview based faults more aggressively in 17.5 before release bombards the hits. This would mean aggressively taking a pass at the ones that are open.
- Also consider adding a new rule for faults firing only in Preview but not in release, so as to capture the new regressions introduced in each preview, before they get released. As it stands right now release data is quite huge and covers the preview regressions.

**Comment by arkalyanms** [comment]
Moving back to Jason after offline discussions with Jason and Shen. The current plan is to wait on 17.5 P1 results that have Cyrus's improvements to the task cancelled exception to assess the new ground reality and reset and start looking at the hits after.

**Comment by arkalyanms** [comment]
From Jason and for future consideration for 17.5 P2 and further: _What we can also do too for the NFWs is once we get a set of fixes in, reset queries/dashboards to only look at internal builds past that set of fixes._

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
