### ISSUE TITLE
Improve negation of relational patterns with numeric values in refactorings

### ISSUE THREAD

**Issue by kimsey0** [dotnet/roslyn#64558]
When running a refactoring that negates a relational patterns with a numeric value, for example when inverting `if (123 is > 100)`, the refactoring adds a `not` combinator, e.g., `if (123 is not > 100)`. It would be preferable if it instead negated the relational operator, `if (123 is <= 100)`. Not that this new logic is only valid for numeric values, since `new object() is > 10` is not equivalent to `!(new object() is <= 10)`.

The negation logic that would have to be changed is implemented in https://github.com/dotnet/roslyn/blob/a0014a6f29c8fdb712570c4abde27a7980a6eaf6/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/SyntaxGeneratorExtensions_Negate.cs#L117-L119

Related to #64292.

**Comment by jnm2** [comment]
It's also specifically not an equivalent refactoring for nullable numeric values (https://github.com/dotnet/roslyn/issues/63311) and there should likely be tests of this.
