### ISSUE TITLE
Error reported annotating ref parameter with [UnscopedRef]

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#64569]
Compile:
```csharp
using System.Diagnostics.CodeAnalysis;

ref struct R
{
    public R(in int i) { }

    void SetRef([UnscopedRef] ref int i)
    {
        this = new R(in i);
    }

    void SetIn([UnscopedRef] in int i)
    {
        this = new R(in i);
    }
}
```
Expected:
No errors

Actual:
```
(7,18): error CS9063: UnscopedRefAttribute cannot be applied to this item because it is unscoped by default.
(12,17): error CS9063: UnscopedRefAttribute cannot be applied to this item because it is unscoped by default.
```

**Comment by Sergio0694** [comment]
Just curious, how come we want to remove those errors in this case? Is this to allow the attribute on RSTE return-only parameters to extend them to RSTE caller-method in the future? Because otherwise, currently, the attribute in these cases _is_ indeed useless, right? 🤔

**Comment by jaredpar** [comment]
The spec specifically allows for `[UnscopedRef]` to annotate explicit `in / ref` parameters. It has the effect of changing the RSTE to _calling method_. 

> if applied to a ref parameter it will become calling method where previously it was return only

More generally though `[UnscopedRef]` always acts to make a `ref` one level more permissive than it previously was.

**Comment by Sergio0694** [comment]
Makes sense, just wanted to double check I was following things properly. Thank you! 😄
