### ISSUE TITLE
Uncomment `[ContentType("text")]` attribute and unskip integration test

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#64567]
See https://github.com/dotnet/roslyn/issues/62877#issuecomment-1271493105 for details

This issue tracks uncommenting `[ContentType("text")]` attribute and un-skipping the integration test added for this feature once [AB#1639743](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1639743) has been fixed.

~Revert https://github.com/dotnet/roslyn/pull/64364/commits/0a13f5803e8fa74890884e4d9787af58e326ff70 to address this issue.~ https://github.com/dotnet/roslyn/commit/c891363e60b61c9a865dd6cc9d4930fd4a643d2d refactored the code, so this would need more than just a revert.

**Comment by sharwell** [comment]
Reopening as this feature does not work.

**Comment by arkalyanms** [comment]
The Editor side work is complete now.
