### ISSUE TITLE
Allocate blittable object on stack memory

### ISSUE THREAD

**Issue by kgb7711** [dotnet/roslyn#64589]
In a game loop, if we want to display fps, the game app will generate tons of string instances, thus has a huge impact on performance.
If we can allocate blittable object on stack, the impact will be greatly alleviated. We need the following:
char* ptr = stackalloc  $"The frame per second is :{fps}.";   //Because string is an array of chars,it is blittable

**Comment by CyrusNajmabadi** [comment]
Closing out. This is not a request for Roslyn.  If you are interested in the language allowing this, please open a discussion over at dotnet/csharplang. Thanks!

**Comment by CyrusNajmabadi** [comment]
Note: this feels like something that `Span<char>` is for.

**Comment by svick** [comment]
> Note: this feels like something that `Span<char>` is for.

Indeed. You can do this today:

```c#
Span<char> span = stackalloc char[30];
bool success = span.TryWrite($"The frame per second is: {fps}.", out int written);
Debug.Assert(success && written < span.Length);
fixed (char* ptr = span)
{
    // use ptr here
}
```

It's quite a bit more verbose than the proposed syntax, but it's not clear to me how that would decide how much to actually `stackalloc`
