### ISSUE TITLE
Not offered to "Extract Method" when resulting async method produces two values

### ISSUE THREAD

**Issue by fiotrann** [dotnet/roslyn#64597]
**Version Used**: 
Version 16.11.18

**Steps to Reproduce**:

1. Highlight between the $$$
2. CTRL+.

``` C#
        public async Task Foo(string value)
        {
            $$$var anotherValue = "FooBar";
                
            var customer = await _repository.GetValue(value.Length);$$$
        
            Console.Write(customer.Id);
            Console.Write(anotherValue);
        }

```
**Expected Behavior**:
Expected to be offered to Extract method

**Actual Behavior**:
Not offered to Extract method

If I highlight just one of the declarations, I am offered to Extract Method. In this case, even if the refactoring didn't understand how to return both values from the resulting method, I would still like the refactoring to occur with broken code that I can then fix up, which is better than not offering it.

**Comment by CyrusNajmabadi** [comment]
We should extract and return a tuple (or have two out vars). @arkalyanms

**Comment by ryzngard** [comment]
For cases where it's not async we do out variables. This looks specifically for when cases are async... will see about fixing this.
