### ISSUE TITLE
Support .NET 6 ServiceHub host on ARM64 VS

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#64610]
Currently .NET 6 host is only supported on x64. This is because we only have a single vsix for Roslyn IDE package, and recent change to crossgen our remote assemblies on .NET 6 for X64 makes it incompatible on ARM64. 

Some changes to setup authoring are needed here to have a separate vsix for .NET 6 remote assemblies.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
