### ISSUE TITLE
Edit > Refactor > Extract Interface no longer creates an interface

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64611]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Edit--Refactor--Extract-Interface-no-l/10165096)._

---
[severity:It's more difficult to complete my work] [regression]
When I press Ctrl + K + Ctrl + I, the Extract Interface dialog is displayed, but after clicking 'OK' no interface is created.

When I click Edit > Refactor > Extract Interface, the Extract Interface dialog is displayed, but after clicking 'OK' no interface is created.

While I click Quick Actions > Extract Interface, the Extract Interface dialog is displayed and after clicking 'OK', the interface is created!

I don't know why the first two methods do not work and the third one does.  There does not appear to be any logs in the Output pane showing any errors encountered.  I use shortcuts almost exclusively, so Ctrl + K + Ctrl + I not working has been driving me nuts!

This has occurred on both my Community Edition at home, and the Enterprise Edition at work, after upgrading to the latest version yesterday.

---
#### Feedback Bot on 10/8/2022, 00:27 AM: 

(private comment, text removed)
#### Feedback Bot on 10/10/2022, 00:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/64194
