### ISSUE TITLE
Suggestion to reduce 3-400 MB download each time cibuild.cmd is run

### ISSUE THREAD

**Issue by codespare** [dotnet/roslyn#6462]
Hello, assuming the nugetvnn.zip archive downloaded to restore packages when building is versioned, could it be possible to keep it around instead of throwing it away after each restore? It takes a while to download :)
I had good success with the following modified restore.ps1 script (first 12 and last 1 line changed from the original):

``` powershell
param ([uri]$nugetZipUrl = $(throw "Need an URL to the NuGet zip") )

$destination = ${env:UserProfile}
#$outFilePath = [IO.Path]::ChangeExtension([IO.Path]::GetTempFileName(), "zip")
$nugetZipFilename = ($nugetZipUrl.Segments | select -Last 1)
$outFilePath = "${env:TEMP}\$nugetZipFilename"
if (-not(Test-Path $outFilePath)) {
    write-host "Downloading $nugetZipUrl -> $outFilePath"
    #$client = new-object System.Net.WebClient
    #$client.DownloadFile($nugetZipUrl, $outFilePath)
    wget -Uri "$nugetZipUrl" -OutFile "$outFilePath"
}

# It's possible for restore to run in parallel on the test machines.  As such
# we need to restore only new files to handle simultaneous restore scenarios.
write-host "Extracting"
Add-Type -assembly "System.IO.Compression.Filesystem"
$archive = [IO.Compression.ZipFile]::OpenRead($outFilePath)
foreach ($entry in $archive.Entries) {
    $entryFilePath = join-path $destination $entry.FullName
    if (test-path $entryFilePath) {
        continue;
    }

    # If it's a directory then create it now.  Calling ExtractToFile will
    # throw on a directory.  There is no way I can find to ask a
    # ZipArchiveEntry if it is a directory hence we just check for a file
    # extension
    [string]$ext = [IO.Path]::GetExtension($entryFilePath)
    if ($ext -eq "") {
        $null = mkdir $entryFilePath -errorAction SilentlyContinue
        continue;
    }

    $entryDirectory = split-path -parent $entryFilePath
    if (-not (test-path $entryDirectory)) {
        $null = mkdir $entryDirectory -errorAction SilentlyContinue
    }

    try {
        write-host "Restoring $entryFilePath"
        [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $entryFilePath) 
    } catch {
        write-host "Unable to restore $($entry.FullName) $Error"
    }
}

$archive.Dispose()
#rm $outFilePath
```

**Comment by tannergooding** [comment]
@jaredpar, I thought we were going to make the nuget zip the default option for our CI machines (to save time) and leave the default option to use actual nuget restore (otherwise we lose validation for the lock.json files).

**Comment by jaredpar** [comment]
@tannergooding the use of ZIP on Jenkins is both for time and stability.  There doesn't seem to be a reason to add an option here because 'nuget.exe restore Roslyn' is really easy for people to type if they want to restore manually.  

I'm not worried about the lock validation because lock files only change if you change the packages we're using.  That is pretty explicit now because you have to also add a new nuget.zip file to our build files (else your changes won't compile).

**Comment by codespare** [comment]
The idea is just to keep that zip around instead of deleting it as the last line in restore.ps1 originally does. For that, I use the name of the archive file locally instead of a temp name, and if the download away if it's already available. Having all the dependencies in one package is actually very convenient, but it makes for a big archive and a slow build if not kept from one build to the next.

**Comment by davkean** [comment]
@codespare If you want to submit something here to fix this, I'll happily take it.

**Comment by codespare** [comment]
@davkean just created a pull request with the solution I use.
