### ISSUE TITLE
Adding a method which can add references from NuGet

### ISSUE THREAD

**Issue by mustafas18** [dotnet/roslyn#64629]
# Adding references from NuGet

## Summary
[summary]: #summary

Adding a method which can add references from NuGet. (e.g. `MetadataReference.CreateFromNuget("Microsoft.EntityFrameworkCore"`);

## Motivation
[motivation]: #motivation

Users can easily add their desire references to their code.

**Comment by ryzngard** [comment]
@genlu this might be related to #64712

**Comment by CyrusNajmabadi** [comment]
Closing out.  If this is wanted, a real API request needs to be made which is much more fleshed out.
