### ISSUE TITLE
VS2015 Update 1 build of Roslyn breaks MSBuild-based code generation, Intellisense

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#6463]
As described in https://github.com/AArnott/ImmutableObjectGraph/issues/56, Roslyn in Dev14 Update 1 seems to have regressed folks who are using Roslyn from Dev14 RTM timeframe in code generation within MSBuild.

Note that the failing MSBuild Task already bundles the original versions of the Roslyn assemblies that it was compiled against and goes to trouble to isolate its work in its own AppDomain so that the version of Roslyn on the box doesn't matter. Somehow though, Update 1 of Roslyn managed to break it.

This also permanently breaks Intellisense for the entire project when the problem occurs.

**Comment by davkean** [comment]
Untagging infrastructure as its a product bug.

Andrew, can you attach the fusion log? You indicate that your bundling the Roslyn binaries, but by the look at that error, it looks like you might have been relying on it loading from somewhere else and the ones that you were bundling weren't being used.

**Comment by AArnott** [comment]
Here is the failing fusion log. From the looks of it, it does look for (and find!) the assembly from the NuGet package bundled location. But then for a reason I don't understand, it ultimately is rejected due to a minor version mismatch that I don't see. Could it be a devenv.exe.config file's binding redirect is forcing it to only accept 1.1.0.0 instead of 1.0.0.0?

    *** Assembly Binder Log Entry  (10/30/2015 @ 8:37:26 AM) ***

    The operation failed.
    Bind result: hr = 0x80131040. No description available.

    Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
    Running under executable  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
    --- A detailed error log follows. 

    === Pre-bind state information ===
    LOG: DisplayName = Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/andarno/Documents/Visual Studio 2015/Projects/ConsoleApplication1/packages/ImmutableObjectGraph.Generation.1.0.15192-beta7/tools
    LOG: Initial PrivatePath = NULL
    LOG: Dynamic Base = NULL
    LOG: Cache Base = NULL
    LOG: AppName = devenv.exe
    Calling assembly : (Unknown).
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\andarno\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: GAC Lookup was unsuccessful.
    LOG: Attempting download of new URL file:///C:/Users/andarno/Documents/Visual Studio 2015/Projects/ConsoleApplication1/packages/ImmutableObjectGraph.Generation.1.0.15192-beta7/tools/Microsoft.CodeAnalysis.Workspaces.DLL.
    LOG: Assembly download was successful. Attempting setup of file: C:\Users\andarno\Documents\Visual Studio 2015\Projects\ConsoleApplication1\packages\ImmutableObjectGraph.Generation.1.0.15192-beta7\tools\Microsoft.CodeAnalysis.Workspaces.dll
    LOG: Entering run-from-source setup phase.
    LOG: Assembly Name is: Microsoft.CodeAnalysis.Workspaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    WRN: Comparing the assembly name resulted in the mismatch: Minor Version
    ERR: The assembly reference did not match the assembly definition found.
    ERR: Run-from-source setup phase failed with hr = 0x80131040.
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by Pilchie** [comment]
@aarnott: Yes, my guess is that the devenv.exe.config binding redirect is taking over.  How are you creating your appdomain?  You should be able to specify your own config for it, instead of inheriting.

**Comment by AArnott** [comment]
Thanks, @Pilchie. That gives me some hope I can fix it on my end. Here's how I do it:
https://github.com/AArnott/ImmutableObjectGraph/blob/master/src/ImmutableObjectGraph.CodeGeneration.Tasks/GenerateCodeFromAttributes.cs#L43

**Comment by tmeschter** [comment]
@AArnott Right off the bat I see there's an `AppDomainSetup.DisallowBindingRedirects` property.

**Comment by davkean** [comment]
If the binding redirect was taking over, I would have expected something like this in the log:

```LOG: Redirect found in application configuration file: 1.0.0.0 redirected to 1.1.0.0.
LOG: Post-policy reference: Microsoft.CodeAnalysis.Workspaces, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35```

It's strange that wasn't logged, but it definitely looks like you're VS's app.config:
```
LOG: Using application configuration file: C:\Users\andarno\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
```

**Comment by Pilchie** [comment]
@tmeschter I suspect it would be more complicated than that (because frankly, when isn't it :smile:. but I think you can also use [`AppDomainSetup.SetConfigurationBytes()`](http://referencesource.microsoft.com/mscorlib/R/9ce3065077e31469.html) here.

**Comment by AArnott** [comment]
Adding `DisallowBindingRedirects` fixed the problem.
https://github.com/AArnott/ImmutableObjectGraph/commit/ac0c22cab40d0eaec43d520ca237e5f20f84b7c6

Thanks.

**Comment by AArnott** [comment]
Adding `DisallowBindingRedirects` fixed the problem.
https://github.com/AArnott/ImmutableObjectGraph/commit/ac0c22cab40d0eaec43d520ca237e5f20f84b7c6

Thanks.

**Comment by AArnott** [comment]
Adding `DisallowBindingRedirects` fixed the problem.
https://github.com/AArnott/ImmutableObjectGraph/commit/ac0c22cab40d0eaec43d520ca237e5f20f84b7c6

Thanks.

**Comment by AArnott** [comment]
Adding `DisallowBindingRedirects` fixed the problem.
https://github.com/AArnott/ImmutableObjectGraph/commit/ac0c22cab40d0eaec43d520ca237e5f20f84b7c6

Thanks.
