### ISSUE TITLE
CS8629 false positive for nested ImmutableArray

### ISSUE THREAD

**Issue by bschwehn** [dotnet/roslyn#64645]
**Version Used**: 
4.3.0-3.22470.13 (80a8ce8d)'. Language version: 10.0.
**Steps to Reproduce**:

1. compile this code:
```

    public class A
    {
        public ImmutableArray<string>? Names { get; set; }
        public Object? Obj { get; set; }
    }

    public class Foo
    {
        public int Working(ImmutableArray<A>? s)
        {
            ArgumentNullException.ThrowIfNull(s, nameof(s));
            var ss = s.Value.Length;
            return ss;
        }

        public void AlsoWorking(A? s)
        {
            ArgumentNullException.ThrowIfNull(s);
            ArgumentNullException.ThrowIfNull(s.Obj);
            var ss = s.Obj.ToString();
        }

        public int AlsoWorking2(ImmutableArray<A>? s)
        {
            ArgumentNullException.ThrowIfNull(s);
            var k = s.Value[0];
            ArgumentNullException.ThrowIfNull(k);
            var n = k.Names;
            ArgumentNullException.ThrowIfNull(n);
            var ss = n.Value.Length;
            return ss;
        }

        public int NotWorking(ImmutableArray<A>? s)
        {
            ArgumentNullException.ThrowIfNull(s);
            ArgumentNullException.ThrowIfNull(s.Value[0]);
            ArgumentNullException.ThrowIfNull(s.Value[0].Names);
            var ss = s.Value[0].Names.Value.Length;
      // CS8629 here ^^^^^^^^^^^^^^^^
            return ss;
        }
    }

```

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible
Sharplab does not seem to support System.Collections.Immutable and so far I could not find a repro case without it.

**Expected Behavior**:
None of the methods gives a CS8629. It would be neat if the analysis worked out that s.Value[0].Names cannot be null here.

**Actual Behavior**:
NotWorking method gives CS8629

**Comment by jaredpar** [comment]
Thanks for taking the time to file this feedback issue. Unfortunately this is not a bug. The language is operating as intended here. 


Generally the compiler looks at code flow to determine if items are null or not. So when you test for `ThrowIfNull(s)` the compiler learns that `s` is not `null`. One of the places the compiler does not learn from is array indexing. So the line `(s.Value[0].Names)` does not cause the compiler to learn that `[0]` is not `null`. As such it still warns on the later access.

**Comment by bschwehn** [comment]
Oh, ok, thanks for the quick response (and for vsvim 👍 )
