### ISSUE TITLE
Bitwise operator used on sign-extended operand (short after bitshift), redundant casting

### ISSUE THREAD

**Issue by EBrown8534** [dotnet/roslyn#6464]
I've just discovered that Visual Studio has an issue when you are using a bitwise-or on two `short` values, where one of them has had a bit-shift on it:

When you don't have any casting, the IDE complains about:
> Bitwise-or operator used on a sign-extended operand; consider casting to a smaller unsigned type first

Example: `return Width << 16 | Height;` where `Width` and `Height` are of `short` types.

This will create the warning above, but `return Width << 16 | (ushort)Height;` will not. If you put the explicit cast in there, then it states that the cast is redundant.

It appears that the IDE cannot make up it's mind.

Full examples:

    public short Width = 17;
    public short Height = 94;

    public int ShiftAndOr1()
    {
        // This will cause the "Bitwise-or operator ..." message
        return Width << 16 | Height;
    }
    public int ShiftAndOr2()
    {
        // This will cause the "redundant cast" message
        return Width << 16 | (ushort)Height;
    }

However, this only seems to happen on `short` types, at least as far as I've seen. I don't get the message on my `byte` types that I do the same operations on (except I shift by 8 instead of 16).

    public byte Width = 17;
    public byte Height = 94;

    public int ShiftAndOr()
    {
        // This will not give either message
        return Width << 8 | Height;
    }

**Comment by DustinCampbell** [comment]
Good catch! This has already been reported (#4531) and, thankfully, fixed! (#4643)

In fact, it is already fixed in the latest release of Visual Studio 2015 Update 1.
