### ISSUE TITLE
Intellisense for "sha1" is not optimal

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64646]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-for-sha1-is-not-optimal/10168433)._

---
In a .NET application, VS suggests `Sha1` from `System.Runtime.Intrinsics.Arm` as the first item of Intellisense. While this is valid, I expect more people to use `System.Security.Cryptography.SHA1`. It would be better to make it the first choice on the list.

![image](https://user-images.githubusercontent.com/788783/195203629-b00595b4-a14a-47d1-bb67-e31dc836d690.png)

---
#### Feedback Bot on 10/10/2022, 06:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
Hey @meziantou, thanks for the feedback. One simple change that would address this specific issue is to compare the namespace depth. for example, when pattern matching of two items are equally good, we'd choose the one from `System.Security.Cryptography` (depth of 3) over `System.Runtime.Intrinsics.Arm` (depth of 4).  That said, I'm not sure how effective it'd be in general, for we lack the data to prove it one way of another.

**Comment by meziantou** [comment]
This would work for this special case, but maybe it could break other completions. Hard to tell without more data.

Could IntelliCode suggest the best type using AI? It works great for method completion, maybe it could also help in this context? Or maybe a basic implementation based on MRU or/and the number of usages of each type in the solution?

**Comment by genlu** [comment]
> maybe it could break other completions

I'm not actually too concern about that, this will only be used as tie breaker for unimported items that matches the filter text equally well, and their current selection is pretty much determined randomly (based on the order we get the references from project system and namespace symbols in an assembly returned from compiler). So it can't make it any worse, right?

> Could IntelliCode suggest the best type using AI

That's a good idea. We do have a mechanism in place to do this (which might need a small change to support unimported items). Will check with IntelliCode team.
