### ISSUE TITLE
Variable names suggestion

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/roslyn#64669]
I propose putting recommendation of variable names into the functions you author, then IDE can intelligently look at the pattern of your function (what variable name was returned), to suggest to the caller what they should name the variable that the function is return.

Programmers doesn't have to change anything, while this change makes everyone's life easier, AI can aid the process of naming things when what's returned doesn't have a name

**Comment by CyrusNajmabadi** [comment]
@markw-t can you migrate this?

**Comment by genlu** [comment]
@CyrusNajmabadi I think this is similar to request from IntelliCode to provide them a way to participate in the declaration name suggestion process.

**Comment by markw-t** [comment]
Hey folks: if this is a request for an intelligent/AI-driven feature to do this, feel free to migrate or raise at https://github.com/MicrosoftDocs/intellicode/issues (I don't seem to have migration rights here)
