### ISSUE TITLE
LSIF Go-to-definition does not work when aliases are involved

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#64665]
**Version Used**: 4.5.0-1.22510.9 of the Microsoft.CodeAnalysis.Lsif.Generator project

**Steps to Reproduce**:

1. Create a class library with the following content:
```C#
using SomeClass = AliasedMethodBug.A.Very.Long.Namespace.SomeClass;

//using AliasedMethodBug.A.Very.Long.Namespace;

namespace AliasedMethodBug
{
	public class Class1
	{
		private readonly SomeClass _theClass;

		public Class1()
		{
			_theClass = new SomeClass();
			_theClass.SomeMethod();
		}
	}
}

namespace AliasedMethodBug.A.Very.Long.Namespace
{
	public class SomeClass
	{
		public void SomeMethod()
		{
		}
	}
}
```

3.  Generate LSIF
4. Try and go-to-definition on `new SomeClass()`

**Expected Behavior**:
Brings you to the alias condition at the top like in VS

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2008729/195411691-42ee2c8c-0051-47c3-9eec-b030a3a0014f.png)

**Extra**
[Here's the linked LSIF](https://github.com/dotnet/roslyn/files/9767456/AliasMethodBug.linked.zip) if you want to visualize it with [lsif-debug](https://github.com/NTaylorMullen/lsif-debug).

And here's after the regular `using` is uncommented (things work as expected)
[Working.linked.zip](https://github.com/dotnet/roslyn/files/9767466/Working.linked.zip)

This was originally spawned from an internal bug report but I was able to create a minimal repro of it. If you'd like the internal report let me know and I can get it to you @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If we need to do this it shoudl go in an appropriate milestone for the work to be done.
