### ISSUE TITLE
New rename UI target token highlighting is a bit odd

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64676]
**Version Used**: 
17.4 Preview 3

**Steps to Reproduce**:
```cs
var whatever = 1;
```
Start renaming `whatever`

**Expected Behavior**:
If I add or remove text from original name the highlighting of the target token doesn't change

**Actual Behavior**:
![devenv_zzTWIE4Qc0](https://user-images.githubusercontent.com/70431552/195442099-c4107a6d-6eea-4125-b075-22fbc02e79f9.gif)

The original highlighting color is more like an aqua. When I add chars the new part of the name is highlighted as yellow. And if I make the name shorter, the blue component of the highlighting "overflows" to the text near it. I guess, this blue "highlighting component" is not needed here

**Comment by ontorder** [comment]
to me even did weird stuff like extending the selection to the start of the next line

**Comment by ryzngard** [comment]
yea, basically it keeps a selection that's the same length as the original span. So if that somehow goes onto the next line it looks extra weird

**Comment by DoctorKrolic** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/67031
