### ISSUE TITLE
New rename UI stops updating the editor state when the textbox is fully cleared

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64674]
**Version Used**:
Checked on 17.4 Preview 3 and latest main

**Steps to Reproduce**:
```cs
var whatever = 1;
```
Start renaming `whatever`
Fully clear the textbox in rename UI and then try to type something again

**Expected Behavior**:
After clearing textbox and typing the editor state still updates. ~~Or UI should not allow me to fully clear the textbox. I don't know which option is better here~~ Well, there are cases when the user wants to fully rename the variable/class etc. In such cases the ability to fully clear the textbox is required

**Actual Behavior**:
![devenv_0DoeTSjTZp](https://user-images.githubusercontent.com/70431552/195440200-84b53510-0196-40d2-a39b-3aba09ef219d.gif)

**Comment by CyrusNajmabadi** [comment]
Already fixed @ryzngard ?

**Comment by ryzngard** [comment]
Not a known issue. @DoctorKrolic is this 100% repro? I just tried on 17.4 P3 and wasn't able to repro.

**Comment by ryzngard** [comment]
Nevermind, it repros if the only content is code provided. If there's more content it doesn't repro. Interesting.

**Comment by CyrusNajmabadi** [comment]
Closing as i do not repro this.
