### ISSUE TITLE
Ref fields spec doesn't mention how scope flows from lambda to anonymous delegate types

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#64670]
The prior spec explained how types and ref kinds flow, but now we're adding two parts:
1. `scoped` flows
2. `[UnscopedRef]` flows (see https://github.com/dotnet/roslyn/pull/63787)

That second part probably needs to be confirmed with LDM.

Relates to test plan https://github.com/dotnet/roslyn/issues/59194 (ref fields)

**Comment by AlekseyTs** [comment]
I don't think it make sense to separate both because we cannot reliably separate them from metadata and we are not always dealing with source symbols.

**Comment by jaredpar** [comment]
@jcouv the spec change is merged now, is this tracking any work in this repo or should we close?

**Comment by jcouv** [comment]
Thanks. Closing
