### ISSUE TITLE
Code folding does not work for anonymous objects

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#64679]
Originally Reported as https://github.com/OmniSharp/omnisharp-vscode/issues/5406

Code folding for anonymous object instantiations should be possible as it is for typed object instantiations. This is especially convenient for large and complex anon objects which have multiple nested levels.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/611219/195448091-a0a99751-5e14-4085-a7f5-bd0c9df5747f.png">

**Comment by kandicst** [comment]
@sharwell I'd like to take this one. 

Could you maybe just point me where to look in the project for this change? I tried but only found `FoldingRangesHandler` which is used for comments, imports and regions.

**Comment by sharwell** [comment]
@kandicst It looks like `AnonymousObjectCreationExpressionSyntax` doesn't have `InitializerExpressionSyntax` as a child, so [`InitializerExpressionStructureProvider`](https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Features/CSharp/Portable/Structure/Providers/InitializerExpressionStructureProvider.cs#L15) isn't creating the structure for it. Fixing this would involve creating a new type next to `InitializerExpressionStructureProvider` (e.g. `AnonymousObjectCreationExpressionStructureProvider`) and piping it through all the same places.
