### ISSUE TITLE
When checking ASP.NET 5.0, you can't select Windows 8.1, Windows Phone 8.1 and .NET Framework 4.5.1

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6467]
1. Create a new portable project
2. Choose the following

![image](https://cloud.githubusercontent.com/assets/1103906/10852055/eda902ce-7eeb-11e5-91dd-4aa9cb17fced.png)

Notice that portable retargets you down to .NET 4.5 and Windows 8, meaning that you cannot use any of the new API that was introduced in Windows 8.1 and .NET 4.5.1.

This is incorrect, ASP.NET Core 5.0 should a superset of this.

**Comment by rchande** [comment]
@davkean @Pilchie Trying to understand the impact of this--can this be moved to 1.3?

**Comment by DustinCampbell** [comment]
Moving it to 1.3. @davkean, @Pilchie -- please holler if we should be looking at this in 1.2.

**Comment by rchande** [comment]
Ping @davkean @Pilchie Do we need to fix this for RTM?

**Comment by Pilchie** [comment]
@srivatsn should this move to project system now?

**Comment by Pilchie** [comment]
Ping @srivatsn?

**Comment by srivatsn** [comment]
Is this even relevant anymore? We only show the following now in VS 2017. All the frameworks listed in the bug are not available anymore.

![image](https://cloud.githubusercontent.com/assets/20570/25096701/3eb58bd2-2356-11e7-8aab-44df1bf66228.png)

**Comment by rchande** [comment]
@srivatsn Indeed, it sounds like this can be closed.
