### ISSUE TITLE
Improve the user experience when applying code fixes from error list

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6472]
We recently added commands in the error list to invoke suppression/remove suppression fixes for selected items. Applying any code fix will cause the diagnostic to become stale, but it takes some time for the fixed diagnostic to disappear/change state - we don't treat the documents with diagnostics being fixed specially, causing the delay.

We should try to improve this experience to refresh the stale diagnostics more quickly.

**Comment by mavasani** [comment]
@heejaechang proposed that we should just add the documents containing the diagnostics on which fix was applied in solution crawler high priority queue. The experience will still not be instantaneous as we need to get a new compilation and compute diagnostics on it, but should be lot better than current experience.

**Comment by mavasani** [comment]
Fixed with #6478

**Comment by heejaechang** [comment]
@mavasani thank you for closing this.
