### ISSUE TITLE
New `prop` semantic snippet doesn't place cursor where expected

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#64731]
**Version Used**: 
17.4 Preview 3

**Steps to Reproduce**:
```cs
class MyClass
{
    $$
}
```
Invoke completions at `$$`
Select `prop` snippet
Press `Enter`

**Expected Behavior**:
```cs
class MyClass
{
    public int MyProperty { get; set; }$$
}
```

**Actual Behavior**:
```cs
class MyClass
{
    public int MyProperty {$$ get; set; }
}
```

**Demo:**
![propBug](https://user-images.githubusercontent.com/70431552/195829768-bd98e414-8378-4975-934b-f6f45a23f928.gif)

**Comment by arkalyanms** [comment]
@akhera99 There was a feedback around this as well I sent to you. Please dup. Thanks!
