### ISSUE TITLE
Incorrect var type deduction

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64747]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-var-type-deduction/10151905)._

---
[severity:It's more difficult to complete my work]
`var` type should be of type `IEnumerable` but is indicating `dynamic` instead

![image](https://user-images.githubusercontent.com/60013978/195954735-df1877df-2a83-4bd1-badf-042bf4573f84.png)

---
#### Feedback Bot on 9/19/2022, 06:18 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/25/2022, 08:05 PM: 

(private comment, text removed)
#### Sergio Jr on 10/12/2022, 02:30 PM: 

(private comment, text removed)
#### Feedback Bot on 10/12/2022, 02:13 AM: 

(private comment, text removed)
#### Feedback Bot on 10/12/2022, 06:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Note: Behavior is different for local functions:

```csharp
internal class Program
{
    static string Method1(dynamic arg) => string.Empty;

    static void Main()
    {
        dynamic obj = new object();
        var myVar = Method1(obj);
        var myVar2 = Local(obj);
        
        static string Local(dynamic arg) => string.Empty;
    }
}
```

**Comment by Youssef1313** [comment]
https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#1178-invocation-expressions

> An *invocation_expression* is dynamically bound ([§11.3.3](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#1133-dynamic-binding)) if at least one of the following holds:
>
> - The *primary_expression* has compile-time type `dynamic`.
> - At least one argument of the optional *argument_list* has compile-time type `dynamic`.
>
> In this case, the compiler classifies the *invocation_expression* as a value of type `dynamic`.

This might be by-design per the above part of the spec, but not quite sure why local functions are different.

**Comment by svick** [comment]
@Youssef1313 It is by-design, including local functions, see https://github.com/dotnet/roslyn/issues/59132#issuecomment-1024787694. In short, the reason is that local functions don't have overload resolution.
