### ISSUE TITLE
Caller-Information-like Attribute to inspect nullability of generic type parameter values at runtime

### ISSUE THREAD

**Issue by PaulRitter** [dotnet/roslyn#64755]
## Background and Motivation

I am working on a (De)serialization-API and I would like to make nullability work seamlessly with my generic deserialization method calls.
The simplified signature of my deserialization method is as follows:
```cs
T Read<T>(DataNode node);
```
Inside of this function, I am inspecting the generic type parameter to see if it is nullable, therefore determining if it is safe to return a null value from the method call. This works fine with nullable structs since they are different types at runtime, but this behavior just isn't possible with reference types, since their type definitions dont differ at runtime.
In short, **I want a way to inspect if a generic type parameter provided is nullable.**

## Proposed API

Due to the information of whether or not a given reference type used as a generic type parameter is nullable being only available during compilation as far as I can tell, the first idea that sprung to mind was implementing a similar API as to the one used in the [caller information attributes](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information). In addition to this, you'd also need a way to map the attribute to a specific type parameter. This could be achieved by either providing an index or `nameof(T)`. Im not experienced enough with compiler services to judge which option makes more sense and/or is easier to implement, but `nameof(T)` would certainly be more intuitive and user-friendly in my opinion.

The method parameter annotated with this attribute would then be set to `true` by the compiler incase the generic parameter of the call was indeed nullable, and would be set to `false` if not.

#### Variant 1 (nameof)
```cs
public class GenericParamNullable : Attribute {
	public GenericParamNullable(string parameterName){}
}
```

#### Variant 2 (index)
```cs
public class GenericParamNullable : Attribute {
	public GenericParamNullable(int parameterIndex){}
}
```

#### Variant 1 (nameof)
```cs
T Read<T>(DataNode node, [GenericParamNullable(nameof(T))] bool isNull = false);
T1 Read<T1, T2>(DataNode node, [GenericParamNullable(nameof(T1))] bool isNull = false);
```

#### Variant 2 (index)
```cs
T Read<T>(DataNode node, [GenericParamNullable(0)] bool isNull = false);
T1 Read<T1, T2>(DataNode node, [GenericParamNullable(1)] bool isNull = false);
```

## Alternative Designs

See Proposed API section.

## Risks

None as far as I am aware.

**Comment by jaredpar** [comment]
Thanks for the suggestion here. This is more of a C# language feature though vs. a compiler one. Can you please open this as a discussion topic on [csharplang](https://github.com/dotnet/csharplang/discussions/new)?
