### ISSUE TITLE
SourceGenerator: A way to include files from a dependant project?

### ISSUE THREAD

**Issue by dotlogix** [dotnet/roslyn#64753]
Hey there I am currently testing SourceGenerators.

My main goal is to create DTOs from entities using source generation.
My problem is now that it seems like I can't analyze files from another project.

I have two projects one for Adapters (Dtos, ApiClients, etc) and another one for the Server (Controllers, Services, Entities).
The server references the Adapter project to access the Dtos in the end.

So because of the dependencies I think I can not get the SyntaxNodes of my Entities from a SourceGenerator added to my Adapter project.
I also tried linking the Entity.cs files, but roslyn does not pick these up as SourceFiles for Analysis because they are linked as AdditionalFiles.

Also because my generator creates DTOs and my Server uses these DTOs I can not do dll linking.
Seperating the entities in it's own Dll would also not solve the problem because then my Adapter project would need a reference to the Entity project.

So is there any way you can think of to access the Entity SyntaxTree information from my DTO project?

Discussed in https://github.com/dotnet/roslyn/discussions/64692

**Comment by jasonmalinowski** [comment]
Closing this in favor of the discussion.
