### ISSUE TITLE
StringSyntax only applies to the first string argument when used with params.

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#64756]
**Version Used**: 

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.1

**Steps to Reproduce**:

1. Combine StringSyntax with params
2. Call the method with multiple strings values

```csharp
public static void StringSyntaxParamsText([StringSyntax("Regex")] params string[] args)
{
    StringSyntaxParamsText(new string[] { "^[sdf]$", "^[sdf]$" });
    
    StringSyntaxParamsText("^[sdf]$", "^[sdf]$");
}
```

**Expected Behavior**:

Syntax applies to all string arguments to the method.

**Actual Behavior**:

Only the first string uses the syntax:

![image](https://user-images.githubusercontent.com/303201/195989786-ecaab4bd-dd1a-42cd-b502-e7a3b317a3b7.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/64553
