### ISSUE TITLE
Compilation error when using generics and static abstract members together

### ISSUE THREAD

**Issue by crazycrank** [dotnet/roslyn#64763]
I've been playing around with the new static abstract members, trying to build a nice way to default Ids even when using value objects:

```csharp
// IDefaultable interface to allow classes to provide their own default value
public interface IDefaultable<T>
    where T : IDefaultable<T>
{
    static abstract T Default { get; }
}

// just a marker interface to identify identifier value objects
public interface IIdentifier
{
}

// entity base class which should assign a default value to the Id at creation.
// Two IsTransient methods to check if it has already been persisted. 
// The first try, just comparing the Id to TIdentifier.Default leads to a compilation error (see IsTransientBug)
// I have to first cast both sides of the == operator to IIdentifier to make it compile
public abstract class Entity<TIdentifier>
    where TIdentifier : IIdentifier, IDefaultable<TIdentifier>
{
    public virtual TIdentifier Id { get; protected set; } = TIdentifier.Default;

    // this works
    public bool IsTransient => (IIdentifier)Id == (IIdentifier)TIdentifier.Default;

    // Error CS0019  Operator '==' cannot be applied to operands of type 'TIdentifier' and 'TIdentifier'
    public bool IsTransientBug => Id == TIdentifier.Default;
}
```

Im not sure if this is a bug, or im just completely missing something, but since the compiler error even correctly states that it can't compare TIdentifier to TIdenfitifier, I feel like theres something not quite how it should be

**Version Used**:  17.4

**Steps to Reproduce**:

1. Create new class library project with .net 6
2. Copy code above into a file

[sharplab repro](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGUawJYGMCCwyMCUuMAshALbAQLICSAdizPWGSgDQAmIAagA+AAQBMARgCwAKFkiAzAAJszdgk64ISxgBEInOABsswIxAA8AFQB8spQ6UB3ABb1tVpSB37DJqGaWtrIA3vaOIhIAbEoBxKTkSp6+UMYwSiFKAOYQMADcSgC+ssVyMooqahxcOoy8EGrYYNj0oSWy8spxJGTp4koAoo0wAJ7WdQ0wTS0IdjKOzm5ISRONzfRetfVrM9w+Bqn+gePbU+uzbfMRygBu2AjwUEYrp9MbdRnZuQUADggA9uxyBBeEpkN8ikoALwvSZvBAAOhSaTyHSuDgA9BilDAXNhkM5/ggANbIcIOCrAf7/Z6MZBWUjMZAtNTQmxKAAUjFWZxmAEoPlCYVyefC+VZReckQcUWiFljBggAQglABhdAABg1EgAnA4API/eiwIlKADkQrNSlwUGYzEBSjosR+PyMLVBMH+Sn+RsZvAJ/zAOJGRvNEte5ytttBZvDcMj5KUlOptPpjOZkwAQnAsmydKChbCdvRpX58u0ZEA===)

**Expected Behavior**:
The code compiles without error

**Actual Behavior**:
The code compiles with error CS0019: Operator '==' cannot be applied to operands of type 'TIdentifier' and 'TIdentifier'

**Comment by CyrusNajmabadi** [comment]
AFAICT< this is workign as intended.  THere is no applicable `==` that can be found to compare your two type parameters, so they can't be compared that way.  (For example, they could be structs, at which point what would `==` do?).

you could just do EqualityComparer<TIdentifier>.Default.Equals here though instead of `==`.

**Comment by crazycrank** [comment]
oh man, you're obviously completely right. Adding a class constraint on `TIdentifier` solves this.

When you're knee deep in all these fancy features and forget how structs work 😂
