### ISSUE TITLE
Where are the docs for writing source analyzers outside VS (for cross-platform CLI)?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/roslyn#64769]
I'm not a typical Visual Studio User(because I'm not a full-time windows user). I need to write an analyzer. But all the docs explain how to write analyzers with VS. There is no documentation on how to get started building an analyzer on CLI. How to set up the project? It's really frustrating. Most languages' documentation first explains how to do things on CLI without extra tooling. The IDE documentation is totally separated. These things still give the feeling that .Net is not fully cross-platform. 
Yes, it's cross-platform, but all the documentation is about VS, which is a windows-only product. So you need to use VS on windows to get the full gist of .NET. 
The docs really should be only about the .NET and doing things on every platform. Yes VS is a good product. But there are many people who like to use CLI or other IDEs. I think C# really went in the wrong direction if you compare it to other languages. **In most languages, everything is CLI first. But in C# everything is VS first.** 
I had gone a little off-topic. But all documentation regarding Roslyn should be written as they could be followed on any platform. 

I want to see this in Prerequisites
## Prerequisites

-  [.NET SDK 6.0 or later](https://dotnet.microsoft.com/download/dotnet/6.0)

Not this
## Prerequisites
- [Visual Studio 2019](https://www.visualstudio.com/downloads) version 16.8 or later

**Comment by Youssef1313** [comment]
I think this is a documentation issue that should be in dotnet/docs.

For now, you could start with cloning https://github.com/jmarolf/analyzer-start

**Comment by Youssef1313** [comment]
@ziaulhasanhamim I opened https://github.com/dotnet/templates/issues/721 for having easy `dotnet new` templates.

For now, all the docs can do is point out how you can create the project manually.

You can either close this issue and open an issue on dotnet/docs using [this link](https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%206e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e%0A*%20Version%20Independent%20ID%3A%20a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6%0A*%20Content%3A%20%5BTutorial%3A%20Write%20your%20first%20analyzer%20and%20code%20fix%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix)%0A*%20Content%20Source%3A%20%5Bdocs%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmain%2Fdocs%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix.md)%0A*%20Product%3A%20**dotnet-csharp**%0A*%20Technology%3A%20**csharp-roslyn**%0A*%20GitHub%20Login%3A%20%40BillWagner%0A*%20Microsoft%20Alias%3A%20**wiwagn**), or wait for someone with write access to move this issue.

**Comment by ziaulhasanhamim** [comment]
> I opened https://github.com/dotnet/templates/issues/721 for having easy dotnet new templates

I appreciate that. Thanks. 

> You can either close this issue and open an issue on dotnet/docs using [this link]
(https://github.com/dotnet/docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%206e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e%0A*%20Version%20Independent%20ID%3A%20a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6%0A*%20Content%3A%20%5BTutorial%3A%20Write%20your%20first%20analyzer%20and%20code%20fix%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix)%0A*%20Content%20Source%3A%20%5Bdocs%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmain%2Fdocs%2Fcsharp%2Froslyn-sdk%2Ftutorials%2Fhow-to-write-csharp-analyzer-code-fix.md)%0A*%20Product%3A%20**dotnet-csharp**%0A*%20Technology%3A%20**csharp-roslyn**%0A*%20GitHub%20Login%3A%20%40BillWagner%0A*%20Microsoft%20Alias%3A%20**wiwagn**), or wait for someone with write access to move this issue.

Ok I will close it and open it there
