### ISSUE TITLE
Building crash using newer .NET SDK than 6.0.203

### ISSUE THREAD

**Issue by laurentkempe** [dotnet/roslyn#64774]
**Version Used**: 17.3.2

All versions [.NET 6.0.6, .NET 6.0.7, .NET 6.0.8, .NET 6.0.9 and .NET 6.0.10](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) after .NET 6.0.5/SDK 6.0.203 are crashing with the same output shown in Actual Behavior below. Version .NET 6.0.5/SDK 6.0.203 works fine.

**Steps to Reproduce**:

I do not have a way to reproduce it in a smaller project than the project I work on which I cannot share.

**Expected Behavior**:

Compiles without any crash.

**Actual Behavior**:

This is the crash we get while compiling our solution either using `dotnet build` or using Rider IDE.
It is related to Roslyn analyzer because when adding the following to Directory.Build.props, then the solution compiles

    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>

Otherwise, we get the following crash 
[build-crash.log](https://github.com/dotnet/roslyn/files/9801350/build-crash.log)

**Comment by Youssef1313** [comment]
Looks similar to https://github.com/dotnet/roslyn/issues/59626

**Comment by laurentkempe** [comment]
It looks similar @Youssef1313 for `System.ArgumentException: An item with the same key has already been added` but the stack traces are quite different

**Comment by 333fred** [comment]
@laurentkempe would you be willing to capture a crashdump of the exception for me to reproduce the issue? These are very hard to replicate without access to the original code or a crashdump with the scenario in question. If so, I can walk you through the process of capturing and privately sharing it.

**Comment by laurentkempe** [comment]
Would be great @333fred

**Comment by 333fred** [comment]
Thanks Laurent. Here's how you go about it:

1. Install https://github.com/jaredpar/basic-compiler-logger by using `dotnet tool install --global Basic.CompilerLog --add-source https://api.nuget.org/v3/index.json`
2. Start by building the project that sees this crash from the command line, either with `dotnet build /bl` or `msbuild /bl`, whichever you normally use.
3. This will create a file called `msbuild.binlog`. Extract an rsp file from the failing project by doing `complog rsp msbuild.binlog`. This may take a minute.
4. This will make a folder called `.rsp`. Find the rsp file that corresponds to the project that is failing to compile.
5. I've [attached](https://github.com/dotnet/roslyn/files/9823062/csc.zip) a debug build of the net472 version of csc.exe. Grab that and unzip it, or if you prefer, build the Roslyn repository.
6. Open VS and select "Open Project or Solution". Navigate to the csc.exe you downloaded/built, and select that.
7. Right click csc in the solution explorer and hit properties. Under arguments, type `@<path to the rsp file you found in 4>`. Set the working directory to the location of the failing project.
8. Open the exception settings window (Debug->Windows->Exception Settings). Search for InvalidOperationException and check that to ensure that the debugger will break on the exception.
9. Hit F5 to start debugging. The debugger should stop on the exception.
10. Hit Debug->Save Dump to save the dump on the exception.
11. Use VS's Report a Problem feature (top-right of the IDE) to create a VS feedback issue. Upload saved heapdump to the bug, and link it here. I'll be able to access it through there.

Thanks! Let me know if you have any trouble with these steps.

**Comment by laurentkempe** [comment]
Thanks Fred, for the instructions.

It works well till step 9 and there the debugger doesn't stop on the exception. I then turned all on the exception settings window to be sure and still no chance.

What seems weird is the content of the output window which is opened when starting to debug

```
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(1,1): error CS1525: Invalid expression term '/'
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(2,2): error CS1525: Invalid expression term 'unsafe'
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(2,2): error CS1002: ; expected
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(2,2): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(2,9): error CS1525: Invalid expression term '/'
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(3,9): error CS1003: Syntax error, '(' expected
C:\Users\l\project\.rsp\Project.Tests.Shared.rsp(3,10): error CS1525: Invalid expression term '/'
```

**Comment by 333fred** [comment]
Thanks Laurent! For those who stumble upon this particular stack in the future, update your compiler version if you can or look through your codebase for explicitly-converted tuple expressions, like `((Action, int))(MethodGroup, NotRelevantExpression)`, and explicitly cast each individual tuple element, rather than the whole tuple.

**Comment by laurentkempe** [comment]
Did the change proposed @333fred and now it compiles without any crash, thanks!
