### ISSUE TITLE
`[UnscopedRef]` ignored on `ref` parameter from metadata of `ref struct` type

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#64778]
Compile with pre-C#11 compiler (to avoid https://github.com/dotnet/roslyn/issues/64569):
```csharp
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[module: RefSafetyRules(11)]

public ref struct R { }

public class A
{
    public static void NoAttributes(ref R x, ref R y) => throw null;
    public static void UnscopedRefOnly([UnscopedRef] ref R x, ref R y) => throw null;
}
```
Compile with C#11, linking to library above:
```csharp
class Program
{
    static void F1(ref R x, ref R y)
    {
        A.NoAttributes(ref x, ref y);
    }

    static void F3(ref R x, ref R y)
    {
        A.UnscopedRefOnly(ref x, ref y); // error?
    }
}
```
Expected:
```
(10,9): error CS8350: This combination of arguments to 'A.UnscopedRefOnly(ref R, ref R)' is disallowed
    because it may expose variables referenced by parameter 'x' outside of their declaration scope
```
Actual: No errors

See also https://github.com/dotnet/roslyn/issues/64569.

**Comment by RikkiGibson** [comment]
It wasn't clear to me why a mixing error is expected. Pre-C# 11 has no concept of `ref`s being able to escape into variables of ref struct type. The RSTE and STE of `ref R x` are the same by default, yet the reference does not escape into the value.

**Comment by cston** [comment]
> Pre-C# 11 has no concept of refs being able to escape into variables of ref struct type.

Good catch, thanks. I've updated the repro to include `[module: RefSafetyRules(11)]`.

**Comment by cston** [comment]
Enabling the end-to-end scenario for https://github.com/dotnet/roslyn/issues/64569 will require fixing this. This can be closed if necessary.
