### ISSUE TITLE
VB.NET `Convert If to Select Case` code fix bug

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#64787]
**Version Used**: 
Latest

**Steps to Reproduce**:

1.  use this snippet:
```vb
  Public Sub Main()
        Dim x = ""
        If x = "s" Then
            x = ""
        ElseIf Foo() Then
            x = "1"
        End If
    End Sub

    Function Foo() As Boolean
        Return True
    End Function
```

2. Move the caret to the `If` token and from the bulb choose `Convert to select case` 

**Expected Behavior**:
Get this converted code:
```vb
        Select Case x
            Case "s"
                x = ""
            Case Else
             If Foo() Then
                x = "1"
             End If
        End Select
```
**Actual Behavior**:
The converted code removed the elsif condition:
```vb
        Select Case x
            Case "s"
                x = ""
            Case Else
                x = "1"
        End Select
```

**Comment by VBAndCs** [comment]
There are more issues about this code fix, regarding comments:
This code:
```vb
        If x = "s" Then
            x = "" ' Comment 1
        Else
            x = "1" ' Comment 2
        End If
```

is converted to:
```vb
        Select Case x
            Case "s"
                x = "" ' Comment 1
            Case Else
                x = "1" ' Comment 2
        End Select ' Comment 2
```

And this one:
```VB
        Dim x = ""
        If x = "s" Then
            ' Comment 1
        Else
            ' Comment 2
        End If
```

is converted to:
```vb
        Select Case x
            Case "s"
            Case Else
        End Select
```

With comments erased!
Comments are important to keep.

**Comment by VBAndCs** [comment]
Comments will be erased also from this:
```vb
        Dim x = ""
        If x = "s" Then ' Comment 1
            x = "1"
        Else  ' Comment 2
            x = ""
        End If
```

**Comment by CyrusNajmabadi** [comment]
@VBAndCs We'd def appreciate any contributions here if you'd be interested in it.  We'd be happy to help you walk through getting enlisted and making a PR to solve this.  Right now this would likely be on our backlog, but we'd take a small, scoped, PR to address these concerns you've found.  Thanks, and let us know what you think!

**Comment by CyrusNajmabadi** [comment]
Bug is lkely in VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb in AsSwitchSectionStatements.  It's probably not handling ElseIfs properly.

**Comment by CyrusNajmabadi** [comment]
> Comments will be erased also from this:

@VBAndCs it would probably be best if you opened separate issues here.  that way individual fixes can close out the issue and we can track things appropriately.  thanks!

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
This fix should be revised and tested as a whole.

**Comment by VBAndCs** [comment]
> Bug is lkely in VisualBasicConvertIfToSwitchCodeRefactoringProvider.Rewriting.vb in AsSwitchSectionStatements. It's probably not handling ElseIfs properly.

There is another way to look at it: This fix shouldn't be suggested at first place, because the two if branches don't check values of the same variable!
It may be appropriate if there are two or more branches testing x, and the last elseif testing something else.
So, this fix may be written on the first assumption, and the bug is that the code that suggests fixes has changed!

**Comment by CyrusNajmabadi** [comment]
> This fix should be revised and tested as a whole.

@VBAndCs there is no need to combine the fixes and we would take independent prs on this.

**Comment by CyrusNajmabadi** [comment]
> There is another way to look at it: This fix shouldn't be suggested at first place, because the two if branches don't check values of the same variable!

That's not really important here. It goes into the default case.  So it doesn't need to test anything.

**Comment by VBAndCs** [comment]
@CyrusNajmabadi 
look at this too:
```vb
        If x = "s" Then ' Comment 1
            x = "1"
        ElseIf Foo() Then
            x = ""
        ElseIf x = "t" Then
            x = "2"
        End If
```

it is converted to:
```vb
        Select Case x
            Case "s"
                x = "1"
            Case Else
                x = ""
        End Select
```

Which removed a full branch!
The suggestion to convert to select case is wrong at the first place, because this is not a select case structure!

**Comment by VBAndCs** [comment]
And this one is fun:
```vb
        Dim x = ""
        Dim y = 1
        If x = "s" Then ' Comment 1
            x = "1"
        ElseIf y = 2 Then
            x = ""
        ElseIf x = "t" And y = 1 Then
            x = "2"
        End If
```

it is converted to:
```vb
        Select Case x
            Case "s"
                x = "1"
            Case Else
                x = ""
        End Select
```

obviously, the fix is built on the assumption that this is a valid select case, which should be verified by the analyzer in the first place.
I used this fix many times in the past, but today I started to face bugs. You should review last updates.

**Comment by CyrusNajmabadi** [comment]
> Which removed a full branch!

Yes, as i said, the elseif cases are not being handled properly.

**Comment by CyrusNajmabadi** [comment]
> The suggestion to convert to select case is wrong at the first place, because this is not a select case structure!

Again, as per above, we would gladly take contributions here.  :)

**Comment by CyrusNajmabadi** [comment]
> You should review last updates.

If you notice anything, please let us know.  You can also work with the team on our discord channel.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely to be making changes here.
