### ISSUE TITLE
Refactoring (Extract Interface) - Allow inclusion of Doc Comments

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#64793]
When performing code refactoring and extracting an interface from an already written class, allow the newly created interface class to have the Doc Comments (Xml Comments) for properties, methods, etc from the original class source. 

Current behavior:
No comments are copied over, meaning if you are trying to use something via the interface, no tooltips etc will be shown for the method params and so on.

**Comment by beccamc** [comment]
Thanks for the feedback! This issue is being tracked here - https://github.com/dotnet/roslyn/issues/51485
