### ISSUE TITLE
Offer more autocomplete options when accessibility modifiers don't match.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/roslyn#64821]
**Version Used**: 

**Steps to Reproduce**:

1. Given the following setup: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwIQIYDOApsgN7IaUYAOATgPYAuRAxs8BgJYB2zt3eADYYAbp1qMArkKwAWDAFkAFAEoKVckioYAvsj0ok6LDAwBhDCFyESSTTqA
2. In SharpLab, type the following into the C class body:

```csharp
protected override $$
``` 

**Expected Behavior**:
Even though ```M()``` is protected internal, I would expect it to show up in the autocomplete. Actually prior to Roslyn it would actually even work if you typed ```public override $$``` it would show up.

**Actual Behavior**:
The ```M()``` method is not shown.

**Comment by arkalyanms** [comment]
Not sure if this is actionable on Roslyn. Its possible an integration point is broken on the sharplab side. But @genlu to scout and resolve.

**Comment by mitchdenny** [comment]
Happens in VS as well.

**Comment by CyrusNajmabadi** [comment]
This is by design. Once you start typing modifiers, we use that to filter the list of overrides down more. If you don't want that, just type 'override<space>' and all will be there.

**Comment by davkean** [comment]
@CyrusNajmabadi I think you have misunderstood the bug. Though in broke me in the move to Roslyn, filtering by modifiers makes sense in the new design, however, in the case above users need to know non-public modifiers to know what to type to show the override:

For example, let's imagine v1 BCL had the following:


``` C#
public abstract class Stream
{
   protected abstract int Read(Byte[], Int32, Int32);
}

```

Users only need  to type "protected override".

Then in v2, BCL decided to do the following:

``` C#
public abstract class Stream
{
   protected internal abstract int Read(Byte[], Int32, Int32);
}

```

Now everyone needs to type "protected internal override" for Read to show. This seems unintentional. The non-public "internal" modifier should be stripped when making this determination.

**Comment by CyrusNajmabadi** [comment]
Makes sense

**Comment by mitchdenny** [comment]
Thanks for addressing this @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
yw!
