### ISSUE TITLE
CS8785 ForAttributeWithMetadataName issue with source generator

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#64841]
**Version Used**: 

	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0"
	<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3"
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" 

## VS Info
<details>
  <summary>Expand</summary>
  
Microsoft Visual Studio Community 2022
Version 17.3.5
VisualStudio.17.Release/17.3.5+32922.545
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Markdown Editor v2   2.0.130
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

Solution Colors   1.1.44
Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Web Compiler   1.14.8
Compiler for LESS, Sass and CoffeeScript files

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Steps to Reproduce**:

```cs

[Generator(LanguageNames.CSharp)]
internal class HierarchyGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var childProvider = context.SyntaxProvider.ForAttributeWithMetadataName(Constants.ChildAttributeName, IsCommandClass, GetHierarchicFlow)
			.SelectMany(static (tuples, token) => tuples);
		var parentProvider = context.SyntaxProvider.ForAttributeWithMetadataName(Constants.ParentAttributeName, IsCommandClass, GetHierarchicFlow)
			.SelectMany(static (tuples, token) => tuples);
		
		var mergedHierarchy = childProvider.Collect().Combine(parentProvider.Collect());
		context.RegisterSourceOutput(mergedHierarchy, GenerateHierarchy);
	}

	private void GenerateHierarchy(SourceProductionContext context, (ImmutableArray<(bool root, string parent, string child)> Left, ImmutableArray<(bool root, string parent, string child)> Right) input)
	{
		try
		{
			GenerateInternal(context, input);
		}
		catch (Exception e) when (e is not OperationCanceledException)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				new DiagnosticDescriptor(
					"ATSCG0000",
					"An exception was thrown by the Hierarchy generator",
					"An exception was thrown by the Hierarchy generator: '{0}'",
					"Hierarchy",
					DiagnosticSeverity.Error,
					isEnabledByDefault: true),
				Location.None,
				e.ToString()));
		}
	}

	private void GenerateInternal(SourceProductionContext context, (ImmutableArray<(bool root, string parent, string child)> Left, ImmutableArray<(bool root, string parent, string child)> Right) input)
	{
		context.CancellationToken.ThrowIfCancellationRequested();

		var result = new HashSet<(bool root, string parent, string child)>(input.Left.Concat(input.Right));
		var roots = new HashSet<string>(result.Where(static d => d.root).Select(d => d.parent));
		var globalHierarchy = result.ToLookup(d => d.parent);
		var hierarchyPerRoot = roots
			.Select(root =>
			{
				var children = new HashSet<(string parent, string child)>();
				AddChildrenRecursive(root, globalHierarchy, children);
				return (root, children);
			}).ToDictionary(d => d.root, d => d.children);

		context.CancellationToken.ThrowIfCancellationRequested();

		var sb = new StringBuilder();
		AppendSource(sb, hierarchyPerRoot);
		context.AddSource("GeneratedHierarchy.g.cs", sb.ToString());
	}

	private void AppendSource(StringBuilder stringBuilder, Dictionary<string, HashSet<(string parent, string child)>> hierarchyPerRoot)
	{
		/*
		 *	// <auto-generated/>
		 *	using Amusoft.Toolkit.System.CommandLine.CommandModel;
			using Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator;

			namespace Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.Samples;

			public static class GeneratedHierarchy
			{
				public static readonly ICommandHierarchy ParentCommand = CommandHierarchyBuilder.FromArray(
					new[,]
					{
						{typeof(MixedChainParent), typeof(MixedChainChild1)},
						{typeof(MixedChainParent), typeof(MixedChainChild2)},
					});
			}
		 */

		if (hierarchyPerRoot.Count == 0)
			return;

		var nsParts = hierarchyPerRoot.Keys.First().Split('.');
		var ns = string.Join(".", nsParts.Take(nsParts.Length - 1).ToArray());

		stringBuilder.AppendLine($$"""
			// <auto-generated/>
			using Amusoft.Toolkit.System.CommandLine.CommandModel;

			namespace {{ns}};

			public static class GeneratedHierarchy
			{
			""");

		foreach (var hierarchy in hierarchyPerRoot)
		{
			stringBuilder.AppendLine(AppendSourceHierarchy(hierarchy));
		}

		stringBuilder.Append("""
			}
			"""

			);
	}

	private string AppendSourceHierarchy(KeyValuePair<string, HashSet<(string parent, string child)>> hierarchy)
	{
		var sb = new StringBuilder();
		/* 
				public static readonly ICommandHierarchy ParentCommand = CommandHierarchyBuilder.FromArray(
					new[,]
					{
						{typeof(MixedChainParent), typeof(MixedChainChild1)},
						{typeof(MixedChainParent), typeof(MixedChainChild2)},
					});
		 */

		var hierarchyName = hierarchy.Key.Split('.').Reverse().Take(1).First();

		sb.AppendLine($$"""
			public static readonly ICommandHierarchy {{hierarchyName}} = 
				CommandHierarchyBuilder.FromArray(new[,]
				{
		""");
		foreach (var tuple in hierarchy.Value)
		{
			sb.AppendLine($"\t\t\t{{typeof({tuple.parent}), typeof({tuple.child})}},");
		}

		sb.Append("""		
				});
		""");

		return sb.ToString();
	}

	private void AddChildrenRecursive(string root, ILookup<string, (bool root, string parent, string child)> globalHierarchy, HashSet<(string parent, string child)> results)
	{
		foreach (var tuple in globalHierarchy[root])
		{
			if (results.Add((tuple.parent, tuple.child)))
			{
				AddChildrenRecursive(tuple.child, globalHierarchy, results);
			}
		}
	}

	private static IEnumerable<(bool root, string parent, string child)> GetHierarchicFlow(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
	{
		if (context.TargetSymbol is INamedTypeSymbol classSymbol)
		{
			var hierarchyAttribute = context.Attributes
				.Select(static d => GetHierarchyData(d))
				.Where(static d => d is not null);

			var isRoot = classSymbol is {BaseType.MetadataName: "RootCommand"};

			foreach (var attributeData in hierarchyAttribute)
			{
				if (attributeData is {Data.ConstructorArguments.Length: > 0} && attributeData.Data.ConstructorArguments[0].Value is INamedTypeSymbol {} firstParameterType)
				{
					if (attributeData.ChildAttribute)
						yield return (isRoot, classSymbol.ToDisplayString(), firstParameterType.ToDisplayString());
					if (attributeData.ParentAttribute)
						yield return (isRoot, firstParameterType.ToDisplayString(), classSymbol.ToDisplayString());
				}
			}
		}
	}

	private static HierarchyData? GetHierarchyData(AttributeData attributeData)
	{
		if (attributeData is {AttributeClass: { } attrClass} && attrClass.ToDisplayString() is {} metadataName)
		{
			if (metadataName is Constants.ChildAttributeName)
				return new HierarchyData(attributeData, true, false);
			if (metadataName is Constants.ParentAttributeName)
				return new HierarchyData(attributeData, false, true);
		}

		return default;
	}

	private record HierarchyData(AttributeData Data, bool ChildAttribute, bool ParentAttribute);

	private static bool IsCommandClass(SyntaxNode node, CancellationToken cancellationToken)
	{
		if (node is ClassDeclarationSyntax classDeclaration)
		{
			if (classDeclaration.BaseList is {Types.Count: > 0} baseList)
			{
				return baseList.Types[0].Type is IdentifierNameSyntax {Identifier.Text: "Command" or "RootCommand"};
			}
		}

		return false;
	}
}
```

**Expected Behavior**:
Source generator does not run into fail states from calling sdk methods

**Actual Behavior**:
ForAttributeWithMetadataName crashes the generator

**Additional context**:

![grafik](https://user-images.githubusercontent.com/5545184/196805403-a0340804-9de5-4e19-9240-a902bc3cd4d0.png)

**Comment by jjonescz** [comment]
Hi @taori, thanks for reporting this issue. I'm unable to reproduce the error. Could you please share also where you define the parent and child attributes and how your source generator is used? It would be best if you shared the whole solution where this error occurs.

**Comment by CyrusNajmabadi** [comment]
@taori is this still repro'ing for you right now?
