### ISSUE TITLE
Feature request: Renaming a parameter also changes part of a string

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#64851]
ASP.NET Core has endpoints that are matched to a route. For example:

```cs
[HttpGet("todos/{id}")]
public Todo Get(int id) => _dbContext.Todos.Find(id);
```

Calling the server with "todos/1024" matches this route and the method is called with an id value of 1024. The route parameter `{id}` is matched by name (case-insensitive) to the method parameter `int id`.

Today there is no tooling to help developers keep these names in sync. We're adding analyzers to ASP.NET Core to provide some guidance, but it would be great if the rename refactor had knowledge that these two pieces of code are linked.

What would be ideal is the rename refactor on the method parameter changed the route string along with the parameter name. For example, renaming the parameter to `todoId` automatically changed the route string to `"todos/{todoId}"`.

This kind of works today if you select "Include strings" in the rename refactor popup.

![image](https://user-images.githubusercontent.com/303201/196831597-7afff674-f238-4589-8bf5-a11d65ad613c.png)

Unfortunately, "Include strings" is a big hammer and changes that string in all routes, which wouldn't be what users want.

In the other direction, it would be great if the rename refactor could be triggered while the cursor is in the `{id}` part of the route string, and it could automatically rename that parameter and the method parameter. Today, an error message is shown that rename only works on an identifier.

![image](https://user-images.githubusercontent.com/303201/196831819-2fab39c4-77ae-40dd-9b39-b0a6132d9189.png)

**Possible idea:**

A way to add metadata to a `TextSpan` that identifies that it is associated with an identifier, e.g. class name/method name/parameter name. Then rename refactor knows that attempting to launch rename on that part of the string means the identifier should be renamed. And any rename on that identifier should also update the `TextSpan`.

I mentioned earlier that route parameters use case-insensitive match on method parameter names. Usually, they are the same (camel case), but if they are different and a rename is triggered, then just rename both to be the same.

@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski ?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Once you've got the metadata in place this shouldn't be too hard to do. Do we already have an API for the embedded language stuff that points spans to symbols?

**Comment by CyrusNajmabadi** [comment]
Not in three slightest :-)

**Comment by JamesNK** [comment]
@DustinCampbell

**Comment by CyrusNajmabadi** [comment]
this is effectively a feature request (as with the rest of hte asp stuff).  It would be best if you can let us know how critical this stuff is so we can see about fitting into upcoming sprints.  Thanks.

**Comment by JamesNK** [comment]
(background: I was just demoing route tooling to Dustin 😄)

This isn't critical. I think the route tooling experience is in an acceptable place today without rename support. However, rename is a valuable addition to the experience.

A lot of the work in route tooling is to make method parameters feel like a natural extension of route parameters. Users will find it odd that rename doesn't work.

**Comment by TahirAhmadov** [comment]
I experienced a related problem. In my case, I was renaming a lambda parameter, and **all** strings in the class were changed, and because I renamed `r` to `c`, a whole bunch of `"\r"` were changed to `"\c"`, which created a huge problem. For now, I can obviously un-check the `Include strings` option, but it should really be improved to be more picky with the scopes where it changes strings.

**Comment by CyrusNajmabadi** [comment]
@TahirAhmadov PRs welcome :)

**Comment by CyrusNajmabadi** [comment]
Closing out as this needs to be an actual feature request the teams agree on.  With resources costed and a milestone where this is needed provided.
