### ISSUE TITLE
Diagnostic text for CS4016 is inaccurate for `ValueTask<T>` methods

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64863]
**Version Used**: VS 2022 17.3.6

**Steps to Reproduce**:

```csharp
async ValueTask<int> M() => new ValueTask<int>();
// CS4016: Since this is an async method, the return expression must be of type 'int' rather than 'Task<int>'
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAIAYAEGCMArANwCwAUBgMx4BMOAwjgN4U7t4AcOAahCgFcAphgBsAHlgIAfDgCyACgCUOALyyYQgO69+wsZJgzlZcgF8gA)

**Expected Behavior**:
The diagnostic text is aware that the return type in the signature is `ValueTask<T>`.

**Actual Behavior**:
The diagnostic text always assumes that the return type in the signature is `Task<T>`.

**Comment by ArcadeMode** [comment]
I'll pick this one up, seems easy enough to fix
