### ISSUE TITLE
Autocompletion for `return new …` statement differs between `Task` and `ValueTask` methods

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64862]
**Version Used**: VS 2022 17.3.6

**Steps to Reproduce**:

1. Paste the code below into the editor.
2. Invoke the autocompletion list after each of the two `new` keywords.

```csharp
class C
{
    async Task<string> M1Async()
    {
        await Task.CompletedTask;
        return new ;
    }

    async ValueTask<string> M2Async()
    {
        await Task.CompletedTask;
        return new ;
    }
}
```

**Expected Behavior**:
In both cases `string` is suggested, as the methods are marked as `async`.

**Actual Behavior**:
* `object` is suggested in the `Task` method.  
  ![grafik](https://user-images.githubusercontent.com/823398/196961513-b5b63599-85b1-4658-a6d3-d7ebc8d1a5f5.png)
* `ValueTask<object>` is suggested in the `ValueTask` method.  
  ![grafik](https://user-images.githubusercontent.com/823398/196961653-ca0fabdb-94a8-465e-ac52-7bd61dd203aa.png)

Accepting the autocompletion of `ValueTask<string>` leads to error CS4016.

**Comment by Youssef1313** [comment]
@MartyIX Probably `ObjectCreationCompletionProvider`

**Comment by Youssef1313** [comment]
Root cause might be https://github.com/dotnet/roslyn/issues/30559, but can't confirm without debugging through this.

**Comment by Youssef1313** [comment]
This should also work for the following:

```csharp
using System.Threading.Tasks;
using System.Runtime.CompilerServices;

class C
{
    async MyTask<string> M()
    {
        return new $$
    }
}

[AsyncMethodBuilder(typeof(Task<>))]
struct MyTask<T>
{
}


```

**Comment by Youssef1313** [comment]
@MartyIX You can use .NET 6 in tests by doing something like this:

https://github.com/dotnet/roslyn/blob/39485811c4d1b869ed1531f50fdbcc43bd3dfa48/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs#L12031-L12042
