### ISSUE TITLE
Notify InfraSwat and ICs ASAP when validation insertions are failing RPS

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#64872]
We want ICs to become aware of RPS regressions which could have been introduced by their changes as quickly as possible. However, this is sometimes made difficult by the fact that a dozen or more PRs can be merged in Roslyn each day, and infraswat team can't manually review them all.

One strategy we think could help is to tag the most recent PR committer as a reviewer on the automatically generated insertion so they get notified about what happens in the insertion. If ddrits fails, PR owner checks with Mantis/Tiger if there is a known infra issue.
If no known infra issue, PR owner investigates the original PR.

Another strategy is perhaps to adjust email rules to the tiger or mantis alias so that emails come in as soon as the RPS failure comment is posted on an insertion.

**Comment by arunchndr** [comment]
This likely wont make the cut. Putting the onus on the IC creating the validation insertion to check the RPS results seems fair.
