### ISSUE TITLE
Suggestion: Support for AttributeTargets.Constructor to be valid in the ValidOn property of the AttributeUsageAttribute specified on AttributeUsageAttribute

### ISSUE THREAD

**Issue by devsnicket** [dotnet/roslyn#6487]
If the AttributeUsageAttribute could be specified on an attribute's constructors and not just on the whole class we could have different parameterised constructors available to specific AttributeTargets.

At the moment to clearly show what constructor parameters are supported when adding the metadata of an attribute in the code (i.e. AttributeTargets) you must create multiple attributes types. This can make the code using the attribute unnecessarily verbose as different attribute names have to be specified even though the intent of those attributes might be the same.

Properties on the attribute also have this limitation, but as the type can only define one set of public properties per type there is no way to avoid it. Having completely different constructor parameters on a normal type would be very odd, but as Attributes exist just to specify metadata I don't think the normal rules apply.

Personally this would allow me to be more expressive when extending C# when doing things like weaving, but I don't believe it would require any radical changes to the language or compiler.

```
namespace System
{
    // add AttributeTargets.Constructor
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Constructor)] 
    class AttributeUsageAttribute
...
namespace DevSnicket.Weaving
{
    class MyWeavingFeature1 : Attribute
    {
        [AttributeUsage(AttributeTargets.Constructor)]
        MyWeavingFeature1(string constructorSpecificParameter)
        ...
        [AttributeUsage(AttributeTargets.Property)]
        MyWeavingFeature1(int propertySpecificParameter)
    }
}
...
using DevSnicket.Weaving;

namespace DevSnicket.MyProduct1
{
    class MyClass1
    {
        [MyWeavingFeature1("someconstructormetadata")]
        MyClass1()
        ...        
        [MyWeavingFeature1(1234)]
        Object MyProperty1
    }
}
```

**Comment by paulomorgado** [comment]
Wouldn't that be a CLR suggestion rather than a language suggestion?

**Comment by gafter** [comment]
@paulomorgado The compiler tends to help enforce these. I think it is both.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

See also https://github.com/dotnet/roslyn/issues/18002 for a general discussion of closing and/or moving language issues out of this repo.

We're not currently tracking this feature request, but if you're still interested in it, please submit a proposal on https://github.com/dotnet/csharplang
