### ISSUE TITLE
Explicit interface member autocompletion does not work correctly when an attribute precedes the declaration

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64891]
**Version Used**: VS 2022 17.4 Preview 4 (4.4.0-3.22512.2)

**Steps to Reproduce**:

1. Press Space at each of the marked locations.
2. Press Ctrl+Space after the inserted space at each of the marked locations.

```csharp
interface I
{
    void M();
}

class C1 : I
{
    void$1$
}

class C2 : I
{
    [Obsolete]
    void$2$
}
```

**Expected Behavior**: The autocompletion for explicit interface implementations shows at both locations, and Ctrl+Space inserts `I`.

**Actual Behavior**:
* Location 1: the list opens as expected. Pressing Ctrl+Space auto-inserts `I`.  
  ![image](https://user-images.githubusercontent.com/823398/197251339-4c704a13-bfe3-4ec0-bb1d-08cb9720ec6d.png)
* Location 2: no list opens. Pressing Ctrl+Space does not insert anything.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback about this.
