### ISSUE TITLE
Source Generators - make WriteTo public for Syntax classes 

### ISSUE THREAD

**Issue by kamyker** [dotnet/roslyn#64894]
## Background and Motivation

I was trying to write high performance source generator without allocations but only WriteTo methods don't allocate. Additionally WriteTo that doesn't write whitespaces is internal (for SyntaxToken) or missing (SyntaxNode).

## Proposed API

Add/Make all WriteTo(TextWrite, bool, bool) public, a bit like in this PR:
https://github.com/dotnet/roslyn/pull/64888/files

## Usage Examples
```
public void Initialize(IncrementalGeneratorInitializationContext context)
{
	var classes = context.SyntaxProvider
		.CreateSyntaxProvider((syntaxNode, cancellationToken) =>
		{
			var writer = SWPool.Get();
			var sb = writer.GetStringBuilder();
			bool set = false;
			if(syntaxNode is ClassDeclarationSyntax cds)
			{
				cds.Identifier.WriteTo(writer, false, false);
				writer.Flush();
				if(sb.Equals("ClassThatImLookingFor") || sb.Equals("AnotherClass"))
					set = true;

				sb.Clear();
			}
			SWPool.Return(writer);
			return set;
		}, (context, cancellationToken) =>
		{
			var classSyntax = (ClassDeclarationSyntax)context.Node;
			return classSyntax;
		})
		.Collect();
	context.RegisterSourceOutput(classes, GenerateCode);
}
```

## Alternative Designs
None but additionally there should be non-alloc way to get `ReadOnlySpan<char>` as it's a bit easier to use than StringWriter.

**Comment by CyrusNajmabadi** [comment]
i dont' like the idea of the booleans being part of this contract. why are they needed?  if you don't want to write out leading/trailing trivia, those can just be stripped before writing the node to the stream.

**Comment by kamyker** [comment]
> i dont' like the idea of the booleans being part of this contract. why are they needed?

Currently there are are only public WriteTo(writer) that always point to internal WriteTo(write, true, true);

**Comment by kamyker** [comment]
I've tried calling it with reflection and everything works fine. No idea why that method is internal to begin with.
```
public static class SyntaxTokenEx
{
	static readonly MethodInfo WriteToInternal =
		typeof(SyntaxToken).GetMethod("WriteTo", BindingFlags.NonPublic | BindingFlags.Instance)!;

	delegate void WriteToDel(in SyntaxToken t, TextWriter w, bool s,
	                         bool e);

	static readonly WriteToDel GetDataInternalDel =
		(WriteToDel)Delegate.CreateDelegate(typeof(WriteToDel), null, WriteToInternal);
	//
	public static void WriteTo(this SyntaxToken node, TextWriter w, bool leading,
	                           bool trailing)
	{
		GetDataInternalDel(node, w, leading, trailing);
	}
}
```

**Comment by CyrusNajmabadi** [comment]
> Waste of cpu to write with leading/trailing trivia then read and remove it.

You can trim before that.  e.g. `t.WithLeadingTrivia(default).WithTrailingTrivia(default)`, then write that to the stream.

**Comment by CyrusNajmabadi** [comment]
> No idea why that method is internal to begin with.

We don't expose methods unless there is an extremely good reason to do so.  In this case, there are totally suitable things that can already be done practically freely.

Doing so means we now have to maintain these APIs forever, even if they have a design we would not want in the future.  In other words, once made public, we can never remove or change it.  That's an enormous maintenance code for us that we do not take lightly.

**Comment by kamyker** [comment]
> You can trim before that. e.g. `t.WithLeadingTrivia(default).WithTrailingTrivia(default)`, then write that to the stream.

Doesn't exist for SyntaxNode.

> Doing so means we now have to maintain these APIs forever, even if they have a design we would not want in the future. In other words, once made public, we can never remove or change it. That's an enormous maintenance code for us that we do not take lightly.

It's used by ToString() so chance of removing that api is close to 0. Speaking of it's a bit confusing that there's ToFullString(), ToString() and WriteTo() that works like ToFullString(). There should be WriteFullTo to begin with but I know it can't be changed anymore.

> We don't expose methods unless there is an extremely good reason to do so. In this case, there are totally suitable things that can already be done practically freely.

And somehow properties like this are fine?
```
/// <summary>
/// Same as accessing <see cref="TextSpan.Start"/> on <see cref="Span"/>.
/// </summary>
/// <remarks>
/// Slight performance improvement.
/// </remarks>
public int SpanStart => Position + Green.GetLeadingTriviaWidth();
```
Quick way of getting basic string without trivia is extremely important for overall performance of all source generators. It should also be as easy to find as possible to make everyone use it.

**Comment by CyrusNajmabadi** [comment]
>Doesn't exist for SyntaxNode.

Sure it does.  You just remove the leading trivia from the first token, and the trailing from the last.

> It's used by ToString() so chance of removing that api is close to 0

This is not true at all. We support ToString().  But that doesn't mean that ToString must be implemented using these helpers.  We might decide on entirely different ways of implementing it.

> And somehow properties like this are fine?

Yes. 

> Quick way of getting basic string without trivia is extremely important for overall performance of all source generators. It should also be as easy to find as possible to make everyone use it.

That doesn't mean this API is the right way to expose that functionality or performance aspect you are looking for.

**Comment by kamyker** [comment]
> That doesn't mean this API is the right way to expose that functionality or performance aspect you are looking for.

I hope you can find a better way, I'll keep using reflection delegate.

**Comment by CyrusNajmabadi** [comment]
> I hope you can find a better way,

The way explained above seems like it's a good way to do things.

**Comment by kamyker** [comment]
> The way explained above seems like it's a good way to do things.

That way is x2 slower than reflection delegate call. Anyway looks like ToString() is quicker. Seems like string allocations in modern NET are fast enough.

**Comment by CyrusNajmabadi** [comment]
> That way is x2 slower than reflection delegate call.

Can you show your measurements for this?
