### ISSUE TITLE
Open source System.Linq assembly

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#649]
Creating an issue to track the open source effort.

**Comment by AlekseyTs** [comment]
Creating an issue to track the open source effort.

**Comment by AlekseyTs** [comment]
Source code and existing tests were formatted and sanitized. We should consider porting more test from desktop.

**Comment by gafter** [comment]
Why is this issue in dotnet/roslyn? Is the intent to make these part of the Roslyn repository? That would be very strange indeed.

**Comment by AlekseyTs** [comment]
Completed, see https://github.com/dotnet/corefx/pull/1131.
