### ISSUE TITLE
Incorrect "Cast is redundant" on lambdas assigned to dynamic

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/roslyn#6490]
I have a dynamic object like this, and I'm trying to assign a lambda to one of its properties:

```
dynamic d = new ExpandoObject();
d.MyFunc = (Func<int>)(() => 0); // <- 'Cast is redundant' message appears here
```

If I execute the code suggestion, it will remove the cast, creating a compilation error:

```
d.MyFunc = () => 0; // CS1660 Cannot convert lambda expression to type 'dynamic' because it is not a delegate type
```

**Comment by davkean** [comment]
Is this on RTM? Or with VS Update 1 RC?

@DustinCampbell You fixed a bunch of these, was this one of them?

**Comment by hmemcpy** [comment]
Hmm, right, I updated to Update 1 RC, forgot about it.

**Comment by hmemcpy** [comment]
Can confirm this happens in RC as well.
Funnily enough, the error shows up in the refactoring preview :)

![image](https://cloud.githubusercontent.com/assets/601206/10903420/18083a48-8212-11e5-8275-c62bb3aa87d2.png)

**Comment by DustinCampbell** [comment]
Well, the refactoring preview *is* a real window into the future. So, if a refactoring or fix will introduce an error, it'll show up there.

**Comment by DustinCampbell** [comment]
It looks like we just forgot to check assignments in the unnecessary cast detection. https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs#L306-L316
