### ISSUE TITLE
Codefix for CS1997 uses `Task<T>` even if the original return type was not `Task`

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64901]
**Version Used**: VS 2022 17.4 Preview 4

**Steps to Reproduce**:

1. Open the Quick Actions on the `return` token.
2. Apply "Fix return type".

```csharp
class C
{
    async ValueTask M()
    {
        await Task.CompletedTask;
        return 0;
    }
}
```

**Expected Behavior**: The return type is changed to `ValueTask<T>`.

**Actual Behavior**:
The error message is wrong (see #59001), and the codefix always uses `Task<T>`, even if the original return type was `ValueTask` or a custom task-like type.
![image](https://user-images.githubusercontent.com/823398/197289219-1b853c7f-4ccd-4d8f-a06c-dff173ea361a.png)

**Comment by DoctorKrolic** [comment]
The compiler error message is also misleading. It should say, that the method returns `ValueTask` and suggest returning a `ValueTask<int>` (in this case). If a method returns an unknown non-standart type, there should be no suggestion about returning a `Task<T>`, e.g.:
```cs
using System.Runtime.CompilerServices;

[AsyncMethodBuilder(typeof(C))]
public class C
{
    async C M()
    {
        await Task.CompletedTask;
        return 0; // The CS1997 suggests to return `Task<T>` even though it is most likely not something I wanna do here
    }
}
```
