### ISSUE TITLE
"Convert to method": `nameof` expression in attributes is converted to string literal

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64904]
**Version Used**: VS 2022 17.4 Preview 4

**Steps to Reproduce**:

1. Open Quick Actions on the identifier `M2`.
2. Select "Convert to method".

```csharp
sealed class A : Attribute
{
    public A(string _) { }
    public string P { get; set; }
}

class C
{
    void M()
    {
        void M2([A(nameof(b), P = nameof(b))] string b)
        {
        }
    }
}
```

**Expected Behavior**: The nameof expressions survive the refactoring.

**Actual Behavior**: The nameof expressions are resolved to string literals.
![image](https://user-images.githubusercontent.com/823398/197295993-4f19c718-1319-4364-8d66-6d3123e36f11.png)

**Comment by CyrusNajmabadi** [comment]
We could attempt to reuse the syntax nodes.  However, a core problem we will have is if they bind to things that are no longer in scope at teh place the method is decalred.
