### ISSUE TITLE
Attribute properties are not suggested for local methods

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64905]
**Version Used**: VS 2022 17.4 Preview 4

**Steps to Reproduce**:

1. Invoke the autocompletion list at each marked location.
```csharp
sealed class A : Attribute
{
    public int P { get; set; }
}

class C
{
    void M([A($1$)])
    {
        void M2([A($2$)] string b)
        {
        }
    }
}
```

**Expected Behavior**: `P =` is suggested in both cases.

**Actual Behavior**:
* Regular method: `P =` is suggested.
* Local method: `int` is suggested, and `P =` is not even in the autocompletion list (typing P highlights "Parallel").
![image](https://user-images.githubusercontent.com/823398/197296509-23fd277b-a4ff-4164-a2ab-aec0252a7826.png)

**Comment by DoctorKrolic** [comment]
On the latest public preview not reproducible:
![vcPhXsNUgw](https://user-images.githubusercontent.com/70431552/199958117-fe339c26-9bd1-4d24-b373-2f0e48098fbb.gif)
If completion is invoked explicitly, the `P =` item is still there

**Comment by jhinder** [comment]
The behaviour is weird with 17.4 Preview 6. Sometimes the attribute property appears in the list, sometimes it doesn't, and I can't tell when and why that happens. Really odd.

P appears:
![image](https://user-images.githubusercontent.com/823398/200114784-3cb20021-e6f1-48d3-8535-bb0aa27077bb.png)

P doesn't appear:
![image](https://user-images.githubusercontent.com/823398/200114788-a168eb0d-5c7a-4f5c-bc96-0fec46881eaa.png)

**Comment by CyrusNajmabadi** [comment]
I can't repro either.  Absent other reports, i'm closing this out.
