### ISSUE TITLE
Multiline MSBuild properties are passed to analyzers as just empty strings

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#64917]
**Version Used**: VS 17.3.6

**Steps to Reproduce**:

1. Define an MSBuild property visible to the compiler
2. Set that property to a multiline string, eg.
```xml
<MyProperty>
  Foo;
  Bar
</MyProperty>
```
3. Get that property from the analyzer global options (via "build_property.MyProperty")

**Expected Behavior**:

The property value visible to the analyzer should match the one defined in the .csproj.

**Actual Behavior**:

The value the analyzer gets is just an empty string..? 🤷‍♂️

**Screenshot**:

![image](https://user-images.githubusercontent.com/10199417/197364113-5bb0ebe4-7398-4645-8f6d-e016ced609a6.png)

**Comment by Sergio0694** [comment]
This generally seems to be completely broken. Even single-line properties don't work correctly, and only the value after the first `;` character is actually received by the analyzer. I also tried by concatenating the property, same result. For instance:

![image](https://user-images.githubusercontent.com/10199417/197364283-e9c50cd0-c3a5-49b7-9d34-2b36d0de1574.png)

Here you can see the analyzer only sees "System.Range", but not "System.Index".

**Comment by Sergio0694** [comment]
It would seem that the issue is with some characters, eg. whitespaces and ';'. Using ',' seems to work as expected.

**Comment by Youssef1313** [comment]
@Sergio0694 This is likely an issue with the generation of `GeneratedMSBuildEditorConfig.editorconfig`.

Can you take a look at the contents of this file (you'll find it in `obj\[Debug\Release]` for the build of `PolySharpTests`)?

We'll need to do proper escaping here:

https://github.com/dotnet/roslyn/blob/e35743fc99a259b8e3296d7282caac3fde40c5cd/src/Compilers/Core/MSBuildTask/GenerateMSBuildEditorConfig.cs#L78

The [`;` in .editorconfig](http://docs.editorconfig.org/en/master/editorconfig-format.html) indicates start of a comment.

**Comment by Youssef1313** [comment]
This is actually a duplicate of https://github.com/dotnet/roslyn/issues/43970

**Comment by Sergio0694** [comment]
Ah, yup this is indeed a duplicate, whoops! Thank you! 😅
