### ISSUE TITLE
"Add Parameter" dialog does not recognize generic method parameter types in tuple types

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#64938]
**Version Used**: VS 2022 17.4 P4

**Steps to Reproduce**:

1. Define a method with a generic parameter.
2. Open the "Change signature" dialog for that method.
3. Add a new parameter of the type `(T, int)`.

**Expected Behavior**: The type is recognized, like `T` by itself or any tuple not containing the type parameter like `(int, int)`.

**Actual Behavior**: The dialog shows a warning: "Type name is not recognized".
![image](https://user-images.githubusercontent.com/823398/197616119-869d607c-5a68-4b10-9ddf-f1ee2a048af7.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
