### ISSUE TITLE
dotnet_sort_system_directives_first no longer respected for Microsoft.* namespaces in latest VS 17.4.0 Preview

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn#64930]
**Version Used**: 17.4.0 Preview 2.0

**Steps to Reproduce**:

1. Create an `.editorconfig` with `dotnet_sort_system_directives_first = true`
2. Create a file with `System` usings, e.g.:
```cs
using System;
using System.Globalization;
```
3. IntelliSense add a `Microsoft.*` namespace, e.g.:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/454813/197513114-f0def8b9-b7f2-487b-964b-3563a3a01b82.png">

**Expected Behavior**:
The result should be (and was up until recently):
```cs
using System;
using System.Globalization;
using Microsoft.Extensions.Logging.Abstractions;
```

**Actual Behavior**:
```cs
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Globalization;
```

This is specific to `Microsoft.*` as far as I can tell (or at least I couldn't repro with anything else). So this appears to probably be an intentional change somewhere with undesirable effects.

I noticed this because it's coming up in a ton of commit diffs. The same issue applies to "remove and sort usings" in Visual Studio. In looking through issues here it looks like maybe there isn't an analyzer for this today, but the behavior change is causing us friction and doesn't follow the basic name of the option. Can we please revert to the old behavior so that it _only_ applies to `System.*` and our files are consistent?

**Comment by davkean** [comment]
@CyrusNajmabadi?

**Comment by CyrusNajmabadi** [comment]
i'm unaware of any changes here at all.  and we have tons of tests here.  so my guess is something is broken reading the options in and making sure we're respecting them.

**Comment by jasonmalinowski** [comment]
@jmarolf: assigning this one to you since we seem to have had quite the recentl flood of ".editorconfig isn't working" reports, so I'm wondering if something generally is broken.

**Comment by NickCraver** [comment]
@jasonmalinowski for what it's worth, I've also noticed our indent settings for spacing in XML files aren't being respected either - could be 2 one-offs or a more global issue.

**Comment by CyrusNajmabadi** [comment]
i don't repro this, and we haven't gotten any more reports of this.  closing out.
