### ISSUE TITLE
IDE0004 unhelpful suggestions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#64945]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0004-unhelpful-suggestions/10161369)._

---
[severity:It bothers me. A fix would be nice]

I regularly use two code constructs where casting is either necessary or useful, yet IDE0004 suggests otherwise:

1. When doing arithmetic on byte values, e.g. `n = CInt(a(i)) - CInt(b(i))`, the casts are dimmed and it suggests removing them, even though that would result in an overflow if the latter value is the larger.

2. `Select` blocks are much easier to complete when the operand is cast to an enumeration, e.g. `Select Case CType(c, img_flags)`, because Intellisense can offer values from the enumeration. But, again, IDE0004 disagrees.

Thanks.

---
#### Feedback Bot on 9/29/2022, 05:59 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/11/2022, 10:35 PM: 

(private comment, text removed)
#### Spiritman on 10/12/2022, 03:03 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/14/2022, 01:27 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@CyrusNajmabadi Please update the **Feature - IDE0004** label to include the diagnostic title.

**Comment by CyrusNajmabadi** [comment]
Done.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not planning on investing here.
