### ISSUE TITLE
Cannot install v1.1.0-rc1 due to Microsoft.DiaSymReader.Native

### ISSUE THREAD

**Issue by SLaks** [dotnet/roslyn#6495]
I tried to install Workspaces v1.1.0-rc1 in a fresh .Net 4.6.1 project.

I got the following error:

> Could not install package 'Microsoft.DiaSymReader.Native 1.2.0-rc'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

It looks like you depend on this NuGet package to pull in the native DLL used by `[DllImport]`s; can you configure that package to be willing to install?

**Comment by ErikEJ** [comment]
:+1: me too https://github.com/aspnet/EntityFramework/issues/3622

**Comment by tmat** [comment]
Fixed.

**Comment by ErikEJ** [comment]
@tmat  Thanks.  Will this fix appear in the aspnetcidev feed on MyGet any time soon?

**Comment by osmedd** [comment]
@tmat Many thanks... and a stupid question... Should I expect to see this in a Roslyn Nightly build soon?  I was kind of hoping to put together a snappy demo using Roslyn this week and Murphy is causing me extreme sadness.

**Comment by tmat** [comment]
@davidfowl David?

**Comment by tmat** [comment]
Yeah, it should be up on http://myget.org/gallery/roslyn-nightly in a couple of days.

**Comment by ErikEJ** [comment]
And aspnetcirelease ?

**Comment by osmedd** [comment]
Theoretically, I could build off the github source if I needed something sooner? (he says being outwardly very calm but...)

Alternatively, is there any way to get around this?  I cannot install the nightly build at all (by selecting Microsoft.CodeAnalysis.Scripting.VisualBasic and getting all the dependencies) so I am a bit stuck.

Suggestions welcome. :)

**Comment by tmat** [comment]
You can create a UWP app with project.json and restore it from there, I think.

**Comment by ErikEJ** [comment]
@osmedd you can download and unzip the packages

**Comment by osmedd** [comment]
Thanks everyone.  I found after yesterday's nightly build I could pre-install the Microsoft.DiaSymReader.Native package and then install the Scripting package and dependencies.  Demo success!
