### ISSUE TITLE
Roslyn.Toolsets.Xunit.targets fails to make "Run" command work on test projects

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#6496]
build/Targets/Roslyn.Toolsets.Xunit.targets, whose sole purpose is to make VS's "Run" command work on test projects, isn't working.  I thought the following change would help:

```diff
diff --git a/build/Targets/Roslyn.Toolsets.Xunit.targets b/build/Targets/Roslyn.Toolsets.Xunit.targets
index b4469d1..9a49878 100644
--- a/build/Targets/Roslyn.Toolsets.Xunit.targets
+++ b/build/Targets/Roslyn.Toolsets.Xunit.targets
@@ -3,7 +3,7 @@

   <PropertyGroup>
     <StartAction Condition="'$(StartActions)' == ''">Program</StartAction>
-    <StartProgram Condition="'$(StartProgram)' == ''">$(NuGetPackagesPath)\xunit.runner.console.2.1.0\tools\xunit.console.x86.exe</StartProgram>
+    <StartProgram Condition="'$(StartProgram)' == ''">$(NuGetPackageRoot)\xunit.runner.console.2.1.0\tools\xunit.console.x86.exe</StartProgram>
     <StartArguments Condition="'$(StartArguments)' == ''">$(AssemblyName).dll -html $(OurDir)\xUnitResults\$(AssemblyName).html -noshadow</StartArguments>
     <StartWorkingDirectory Condition="'$(StartWorkingDirectory)' == ''">$(OutDir)</StartWorkingDirectory>
   </PropertyGroup>
```

But unfortunately, `$(NuGetPackageRoot)` doesn't seem to be defined when VS asks MSBuild to evaluate these properties, so that does not work.

**Comment by Pilchie** [comment]
Might be better to just change it to `$(UserProfile)\.nuget\packages\` directly

**Comment by SamB** [comment]
@Pilchie: I guess that works *if* we assume that no cross-platform IDEs use that property.

**Comment by davkean** [comment]
@jasonmalinowski Didn't you fix this?

**Comment by jasonmalinowski** [comment]
Yes in b35c3fdd12dd338221af7befd08646da49a94f1f, which looks like that's what @SamB did. Does that not work?

**Comment by davkean** [comment]
I believe we've fixed this, @SamB please file another issue if that's not the case.
