### ISSUE TITLE
CodeFix provider does not show up

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn#64975]
### Discussed in https://github.com/dotnet/roslyn/discussions/64881

<div type='discussions-op-text'>

<sup>Originally posted by **taori** October 21, 2022</sup>
I am currently working on some package to simplify the creation of CLI programs. To guide the library usage and simplify some processes i added a couple of features using sourcegenerators, analyzers and now also codefixes. Everything but the codefix work. 

My code is here:

https://github.com/taori/Amusoft.Toolkit.System.CommandLine/tree/codefix-bindhandler/src/Amusoft.Toolkit.System.CommandLine.Generator

What i have tried so far is:
- delete .vs folder (fixes a lot of generator issues)
- delete bin/obj
- insert into fresh analyzer with codefix scaffold (works just fine when installed as vsix)
- upgrade workspace in fresh project - works too
- check other projects for maybe different configuration to create nupkg files with analyzer+codefixes

Is there some tracing i can enable to figure out why my codefix won't load with the current package? 
Can i not ship Analyzers together with codefixes in the same nupkg?

I am unsure how to move further with this. Any help is welcome</div>

**Comment by taori** [comment]
@jasonmalinowski Can you reopen it? The discussion is being ignored. I was asking for guidance to obtain logs to pinpoint the issue myself, however noone seems responsible, so the codefix not showing up without any indication on why still remains. Therefore discussion and issue itself are unrelated to each other

**Comment by CyrusNajmabadi** [comment]
The link in the OP doesn't take me anywhere.

**Comment by jasonmalinowski** [comment]
@taori I'll poke some folks internally on that discussion. I guess I don't see what this issue is tracking that's different than the discussion at this point.

**Comment by taori** [comment]
> The link in the OP doesn't take me anywhere.

the branch was merged in the meantime. updated the link now

**Comment by deerchao** [comment]
Is ths fixed, or is there a workaround?
