### ISSUE TITLE
Workspace should state that it needs IWorkspaceTaskSchedulerFactory service implementation

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#6498]
**Current Behavior**
When using an own host implementation (e.g. using MefHostServices) and do not provide an implementation of the IWorkspaceTaskSchedulerFactory (or do not adding the default assemblies in case when using MefHostServices), then the Workspace runs into an NullReferenceException during creation because it tries to access this service. It is reproducible using code like this:
 
    var assemblies = new List<Assembly>() { Assembly.GetExecutingAssembly() };
    var host = MefHostServices.Create(assemblies);
    var adhocWorkspace = new AdhocWorkspace(host);

**Reason**
Reason is the implementation of the Workspace ctor:

    protected Workspace(HostServices host, string workspaceKind)
    {
        _primaryBranchId = BranchId.GetNextId();
        _workspaceKind = workspaceKind;

        _services = host.CreateWorkspaceServices(this);

        // queue used for sending events
        var workspaceTaskSchedulerFactory = _services.GetService<IWorkspaceTaskSchedulerFactory>();
        _taskQueue = workspaceTaskSchedulerFactory.CreateTaskQueue();

        // initialize with empty solution
        _latestSolution = CreateSolution(SolutionId.CreateNewId());
    }

The ctor tries to resolve the WorkspaceTaskSchedulerFactory that is not present if the client code does not provide it or or does not add the default assemblies which contain an implementation of the factory. The following call to the workspaceTaskSchedulerFactory throws the NullReferenceException.

**Impact**
One does not know the reason for the problem when running code like above. You have to look into the source code to figure it out.

**Expected Behavior**
I would expect an exception that states the problem and provide some hints what the client code should do. E.g. adding the default assemblies to the host or provide an own implementation of the WorkspaceTaskSchedulerFactory.

**Comment by davkean** [comment]
This was resolved in: https://github.com/dotnet/roslyn/pull/6952
