### ISSUE TITLE
Copying out of raw string literal results in indented contents

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#64993]
Pasting into a raw string literal smartly indents the content. But copying out of a raw string literal results in indented contents in the clipboard.
This makes it hard to copy from a raw string literal to some other app (notepad, sharplab, email, etc).

When the copy action happens and the selection range is within an indented raw string literal, we should consider putting the un-indented contents into the clipboard instead. 
I don't know if it's a good solution, but we could consider using the start position of the selected range as a hint.

Below is an example to illustrates the problem.
FYI @CyrusNajmabadi 

![copy-raw-literal](https://user-images.githubusercontent.com/12466233/197904318-7f4093b5-971c-4927-ba36-417cabacec50.gif)

**Comment by CyrusNajmabadi** [comment]
Subsumed by https://devblogs.microsoft.com/visualstudio/copy-with-proper-indentation/.  Def send feedback to editor about making this first-class in VS itself :)

**Comment by jcouv** [comment]
Nice. Thanks!

**Comment by CyrusNajmabadi** [comment]
@Bosch-Eli-Black I'd recommend filing a VS issue.  :)

**Comment by Bosch-Eli-Black** [comment]
@CyrusNajmabadi Fair enough! 🙂  Will track via https://developercommunity.visualstudio.com/t/easy-copy-code-without-indentation/1156022
