### ISSUE TITLE
.NET 7 RC 2 breaks F# to C# interop

### ISSUE THREAD

**Issue by gdar91** [dotnet/roslyn#64992]
### Description

F# to C# interop breaks after upgrading to RC 2. When you have more than one type in the f# library, you can't access the properties (members of a record and cases of an union) of the first type.

For example, this below will fail:

F# Library: Library.fs:
```
type A = A

type B = B
```

C# Console: Program.cs
```
var a = A.A;

Console.WriteLine($"{a}");
```

### Configuration

.NET 7 RC2. Behaves the same on mac and windows.

### Regression?

It worked well in RC1.

### Other information

[https://github.com/gdar91/Rc2FsCs](https://github.com/gdar91/Rc2FsCs)

**Comment by cston** [comment]
This sounds like the same issue as reported in https://github.com/dotnet/core/issues/7865#issuecomment-1275325404 and linked to https://github.com/dotnet/fsharp/issues/14147.

**Comment by cston** [comment]
cc @KevinRansom
