### ISSUE TITLE
Build should complete without errors when there are whitespaces in the checkout folder

### ISSUE THREAD

**Issue by robinsedlaczek** [dotnet/roslyn#6500]
**Problem**
When there are whitespaces in the folder name where Roslyn is cloned to, then there are several problems during build. E.g. when cloning to

    E:\Git Repositories\

**Reason**
Missing quotes arround pathes in project and target files.

**Expected Behavior**
I would expect that I can use whitespaces in folder names and that compilation works fine in such environments.

**Comment by davkean** [comment]
Resolved with #6501.
