### ISSUE TITLE
`NotNullIfNotNullAttribute` does not work when a methodgroup is passed to `IEnumerable<>.Select`

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#65000]
**Version Used**: 

.NET 7 RC 2

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgBEoIBzGAewGcAXKAYxsIGEqATAUwEEYIANgE8aUGgG5MOfEQAysAI6SMmAMQwArgIERgArri789XTJgD6uALy4eAJzsQhhAKJgADnSEAeAtgB8ABQAlIQAylz6jHSBAB7W/rjEVGFUYFx0ABaw5HHBoRFRMfFWibGEskbkWcHKljb2js5unj5+QQWRXNGByanpWTmdRXEJuOWVMNWZtWYqGADaCADsILgAclR061oCAJIAZpvbu4H86VQHecEAulIoAGwy2AD8SSlpGdlTgX5vscExlk7FQAO64GBccHHPYefTpGB0LgcFyxRhcTxQKgwELKIA

**Expected Behavior**:

Line 8 in the sharplab link doesn't display error CS8602

**Actual Behavior**:

Line 8 in the sharplab link displays error CS8602

**Comment by jaredpar** [comment]
Duping off the primary issue here: #37468
