### ISSUE TITLE
`[Obsolete(null, error: true)]` is displayed as a warning.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/roslyn#65042]
**Version Used**: 4.3.0-3.22430.17 (e2a5bd7c)

**Steps to Reproduce**:

https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwYQwb2Q2IwG0B5AIwGcB7AGwFMAXRgCgDsBXe+gGgzMATl0YBKALpES6LABYM5NmIIYAvtOKasmKAvIxlGALwA+RcoDcyDUiA==

**Expected Behavior**: Compilation should fail.

**Actual Behavior**: Compilation suceeds with a warning.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/9fe7909d79c591bd863c5a869bda2266001d1a5e/src/Compilers/CSharp/Portable/Symbols/ObsoleteAttributeHelpers.cs#L170

**Comment by jcouv** [comment]
Thanks @Youssef1313 for digging this up. This is a bug but we'll keep this legacy behavior. I'll close as won't fix.
