### ISSUE TITLE
Combination of MethodImpl and ref parameters confused IDE0060 rule

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn#65062]
### Analyzer

**Diagnostic ID**: [IDE0060](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060): `Remove unused parameter`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 

```
    <MicrosoftCodeAnalysisAnalyzersVersion>3.3.4-beta1.22524.2</MicrosoftCodeAnalysisAnalyzersVersion>
    <MicrosoftCodeAnalysisNetAnalyzersVersion>7.0.0-preview1.22524.2</MicrosoftCodeAnalysisNetAnalyzersVersion>
```

### Describe the bug

IDE0060 warning is reported incorrectly

### Steps To Reproduce

```c#
        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Test(ref byte destination, ref byte source)
        {
            destination = ref Unsafe.AddByteOffset(ref destination, 1);
            source = ref Unsafe.AddByteOffset(ref source, 1);
        }
```

### Expected behavior

No warning

### Actual behavior

```
error IDE0060: Parameter 'destination' can be removed; its initial value is never used 
error IDE0060: Parameter 'source' can be removed; its initial value is never used 
```

## Additional context

It's strange that removing `MethodImplAttribute` fixes the problem

**Comment by eerhardt** [comment]
@CyrusNajmabadi - will this be fixed for `7.0.200`? We are putting workarounds into source-build to get unblocked. But we shouldn't be shipping with those workarounds: https://github.com/dotnet/installer/commit/a1525e5c10a0193142364db6fc487ffff7b56b40.

**Comment by CyrusNajmabadi** [comment]
I don't know why this was assigned to me.

**Comment by mavasani** [comment]
I verified that this issue repros with following:
1. Add a NuGet package reference to https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle/4.4.0
2. Enable CodeStyle analyzers shipping in the .NET 7 SDK by setting the MSBuild property: `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>`

However, this does not repro with the below:
1. Latest pre-release C# code style page, i.e. https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.CodeAnalysis.CSharp.CodeStyle/versions/4.5.0-3.22619.4
2. Do not install any C# code style package and also disable code style package from the SDK: `<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>`. This will use the latest code style analyzer version that ships with Visual Studio in Features assembly, which matches the `4.5.0-3.22619.4` or later version of the analyzer.

Above confirm that this was indeed a bug in IDE0060, but it has been fixed now and the fix should hopefully flow into the .NET SDK soon. I am going to close out this issue.

**Comment by mavasani** [comment]
> will this be fixed for 7.0.200?

@jmarolf Any idea when the latest code style packages flow into the .NET SDK?

**Comment by marek-safar** [comment]
The issue is not resolved, dotnet/runtime as of today uses `4.5.0-3.22613.20` version of C# code style package and still exposes the exactly same problem.

**Comment by 333fred** [comment]
@marek-safar does it reproduce with the version Manish referenced? The version you mentioned is older.

**Comment by mavasani** [comment]
I am unable to reference the issue even with `4.5.0-3.22613.20` version of the code style package.

@marek-safar - Are you sure dotnet/runtime is on this version of the package? I did the below searches and that indicate to me you are still on `4.4.0`:

https://github.com/dotnet/runtime/search?q=MicrosoftCodeAnalysisCSharpCodeStyleVersion

https://github.com/dotnet/runtime/search?q=MicrosoftCodeAnalysisVersion_LatestVS

https://github.com/dotnet/runtime/blob/97a51ccdb147992b80d427b83a77caa967d275b4/eng/Versions.props#L67

**Comment by mavasani** [comment]
I do see `4.5.0-3.22613.20` for packages below, but they are not for code style package: https://github.com/dotnet/runtime/blob/97a51ccdb147992b80d427b83a77caa967d275b4/eng/Versions.props#L40-L42

**Comment by marek-safar** [comment]
@mavasani you are right that code style package is still stuck at 4.4.0 version. Manually updating it resolved the issue in dotnet/runtime. Thanks for the extra check!
