### ISSUE TITLE
Completion seems broken (no entries in IntelliSense list) in most recent d17.4

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#65060]
**Version Used**: 
[33020.496](https://aka.ms/vs/17/release/184097643_2012228958/vs_Enterprise.exe)
**Steps to Reproduce**:

1.  Create a toy C# console application
2. Do something that invokes IntelliSense (Console.)

<img width="1452" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/11394666/198374904-844b9994-96f3-4721-aec5-debd656dfbce.png">

**Expected Behavior**:
Full IntelliSense list

**Actual Behavior**:
No items in the system namespace (Action, etc.) listed

**Comment by dpugh** [comment]
David Sterling (& CTI, who reported the bug here: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1658107) has a consistent repro on his machine but no-one else seems to be able to reproduce the problem.

**Comment by jasonmalinowski** [comment]
@genlu I think this also got discussed over email or Teams but can't find it now.

**Comment by genlu** [comment]
Yes. But no one else was able to repro, and based on the discussion of the azdo bug (which is resolved), it seems has something to do with SDK
