### ISSUE TITLE
`AddImportsAnnotation` doesn't match existing line endings

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65081]
See failure in https://github.com/Youssef1313/YAnalyzers/pull/43 (also https://github.com/dotnet/aspnetcore/pull/44463)

It's passing on Windows only.

**Comment by adityamandaleeka** [comment]
@jasonmalinowski Just to confirm, will this fix only be available in 17.5+?

**Comment by jasonmalinowski** [comment]
@adityamandaleeka: we haven't even investigated yet. The "milestone" is just tracking us at least investigating it "soonerish" rather than "laterish".

**Comment by CyrusNajmabadi** [comment]
is there a repro, or more information on what the issue is that you would like fixed?

**Comment by adityamandaleeka** [comment]
@CyrusNajmabadi The test failures in the aspnetcore PR linked above demonstrate the issue. The PR uses the `AddImportsAnnotation` but the new tests fail on Unix because the added imports use the LF line terminator instead of CR/LF.

Output from one of the failing tests:

```
Context: Iterative code fix application
content of '/0/Test0.cs' did not match. Diff shown with expected as baseline:
using System.Collections.Generic;<CR><LF>
using Microsoft.AspNetCore.Hosting;<CR><LF>
-using Microsoft.AspNetCore.Http;<CR><LF>
+using Microsoft.AspNetCore.Http;<LF>
using Microsoft.AspNetCore.Mvc;<CR><LF>
<CR><LF>
var context = new Microsoft.AspNetCore.Http.DefaultHttpContext();<CR><LF>
context.Request.Headers.Append("Accept", "text/html");

Expected: True
Actual:   False
```

**Comment by CyrusNajmabadi** [comment]
Wouldn't `lf` be the expected line ending on unix?  Does the test specify the desired editorconfig eol?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I guess tests in roslyn-analyzers repo (and possibly roslyn as well?) run both on Windows and Unix and they don't seem to specify editorconfigs, and don't fail.

Moreover, what's happening for https://github.com/Youssef1313/YAnalyzers/pull/43 is the exact opposite, I get CRLF on Ubuntu 😄

**Comment by Youssef1313** [comment]
Also https://github.com/dotnet/format/issues/1099 seems to discourage `end_of_line` usage?

**Comment by CyrusNajmabadi** [comment]
Can someone create a test in roslyn that demonstrates the issue?  I'm not really liking the idea of having to go try to set everything up like in the other repos to figure out what's going on here.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/dc57983861812e197fc2c0f78996c2d70e0670b4/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/AddImports/AddImportHelpers.cs#L57

This line forces `\r\n`. I don't think this behavior is correct.

**Comment by CyrusNajmabadi** [comment]
It's elastic. So the formatter should replace with the right new line

**Comment by Youssef1313** [comment]
> It's elastic. So the formatter should replace with the right new line

Then we we have `ElasticCarriageReturnLineFeed`, `ElasticLineFeed`, and `ElasticCarriageReturn`?

The fact that all these three exists makes me thinks that it forces a specific EOL? I thought the correct trivia here would be `ElasticMarker`, not `ElasticCarriageReturnLineFeed`

**Comment by CyrusNajmabadi** [comment]
They have actual text, because all trivia must have text.
