### ISSUE TITLE
When CInt( string value) is used as with Select Case you get IDE0004

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65084]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-CInt-string-value-is-used-as-with/10179138)._

---
[severity:It bothers me. A fix would be nice]
``` 
Dim s as String = "6"
Select Case CInt(s)
  Case > 90
    Me.PumpBatteryRemainingLabel.Text = $"Full"
 Case > 50
    Me.PumpBatteryRemainingLabel.Text = $"High"
 Case > 25
    Me.PumpBatteryRemainingLabel.Text = $"Medium"
 Case > 10
    Me.PumpBatteryRemainingLabel.Text = $"Low"
  Case Else
    Me.PumpBatteryRemainingLabel.Text = $"Critical"
End Select
```
If you remove the Cint then you get "Option Strict On disallows implicit conversions from 'Integer' to 'String'."

---
#### Feedback Bot on 10/24/2022, 07:49 AM: 

(private comment, text removed)
#### Feedback Bot on 10/25/2022, 03:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
tag @CyrusNajmabadi who has recently rewritten this analyzer.

**Comment by CyrusNajmabadi** [comment]
ihave not touched the VB impl (and it terrifies me) :)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not planning on investing in these scenarios.
