### ISSUE TITLE
[Test Failure] MSBuild Error in prtest/lin/dbg/unit32 on PR #6502

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6508]
PR: [#6502](https://github.com/dotnet/roslyn/pull/6502) *Cache static method group conversions* by @diryboy
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/796/

**Issue 1: MSBuild Error**
error MSB6006: "csc" exited with code 134. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj]

**Comment by diryboy** [comment]
Hi @dpoeschl, my pr changes compiler(early implementations however), does this happen after the bootstrap? If so it could be my bad.

**Comment by dpoeschl** [comment]
@diryboy Maybe. Do you know what code "134" means here? I only thought it might be an infrastructure issue since only the Linux build failed in this way, and the actual build log doesn't give more context (maybe we need to increase the build verbosity on Linux?).

**Comment by diryboy** [comment]
Did you see this failure in other PR? One thing I can do is add a message after the bootstrap and let it run again and see if this failure is consistent in my PR, so we know if this has something to do with my changes(when other PR does not have this kind of issue).

**Comment by diryboy** [comment]
For code 134, I believe it's [`ERR_NotNullConstRefField`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Errors/ErrorCode.cs,109) the resource file says 

    '{0}' is of type '{1}'. A const field of a reference type other than string can only be initialized with null.

But I did not generate const ref fields.

**Comment by diryboy** [comment]
Ah, I saw `Building CrossPlatform.sln`, that's within `build_roslyn()`, the bootstrap was complete. so if you don't see this kind of error in other PR then it's very likely my bad.

**Comment by diryboy** [comment]
Hi @dpoeschl you may consider closing this issue as I closed the #6502. I'm working on another one and do not see similar issue. I've seen bad changes on the compiler causing a lot of nonsense errors and hangs, this is very likely just one of them. Sorry for that.

**Comment by dpoeschl** [comment]
@diryboy No problem, thanks for following up!
