### ISSUE TITLE
Semantic classifier: Unreachable exception in TextDocumentStates

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#65094]
I'm hitting an exception in the classifier/workspace that I don't have a good repro for, but I have some understanding of what's happening.

The (not good) repro, that works for me on one machine reliably under specific circumstances:

1. open a .cs file in Misc workspace
2. close the file
3. open it again

System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.TextDocumentStates`1.GetRequiredState(DocumentId documentId) in C:\Roslyn\src\Workspaces\Core\Portable\Workspace\Solution\TextDocumentStates.cs:line 76

<HTML>
<BODY>
<TABLE><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>TextDocumentStates`1.GetRequiredState Line 76</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>ProjectState.UpdateDocument Line 895</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>SolutionState.CompilationTracker.FreezePartialStateWithTree Line 194</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>SolutionState.WithFrozenPartialCompilationIncludingSpecificDocument Line 1659</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>Solution.WithFrozenPartialCompilationIncludingSpecificDocument Line 1652</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.Workspaces</TD><TD>Document.WithFrozenPartialSemantics Line 457</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.EditorFeatures</TD><TD>ClassificationUtilities.&lt;ProduceTagsAsync&gt;d__2.MoveNext Line 70</TD></TR><TR><TD>&nbsp;</TD><TD>mscorlib</TD><TD>AsyncTaskMethodBuilder.Start Line 317</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.EditorFeatures</TD><TD>ClassificationUtilities.ProduceTagsAsync</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.EditorFeatures</TD><TD>AbstractSemanticOrEmbeddedClassificationViewTaggerProvider.ProduceTagsAsync Line 124</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.EditorFeatures</TD><TD>AbstractAsynchronousTaggerProvider`1.TagSource.ProduceTagsAsync Line 397</TD></TR><TR><TD>&nbsp;</TD><TD>Microsoft.CodeAnalysis.EditorFeatures</TD><TD>AbstractAsynchronousTaggerProvider`1.TagSource.&lt;RecomputeTagsAsync&gt;d__46.MoveNext Line 238</TD></TR></TABLE>

</BODY>
</HTML>

What I think is happening, is when we first open the file, it gets DocumentId A. Then we close it, and reopen, and it gets DocumentId B.

However here in the _map, there's only one DocumentId stored, and it's still the previous A, whereas we're trying to look up B:

https://github.com/dotnet/roslyn/blob/fa34e104360f8f974d3a59f62ed748e55924cc42/src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentStates.cs#L76

Chances are the repro won't work for you, but I can easily set it up on my machine and it works 100% on my machine. I don't know why, perhaps it's a timing issue.

But conceptually, the tagger is calling Document.WithFrozenPartialSemantics on the new document, but the inProgressProject here still has the old document Id:

https://github.com/dotnet/roslyn/blob/fa34e104360f8f974d3a59f62ed748e55924cc42/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs#L196

**Comment by KirillOsenkov** [comment]
Dump is available at \\kirillo3\Public\Bugs\Roslyn65094 (ask me for permissions)

**Comment by KirillOsenkov** [comment]
If you need the matching source to debug the dump, it's at https://github.com/KirillOsenkov/roslyn/tree/vs17.3.3-ide

**Comment by CyrusNajmabadi** [comment]
Closing as i don't see any prism hits for this.
