### ISSUE TITLE
Open source System.Linq.Expressions assembly

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#651]
Creating an issue to track the open source effort.

**Comment by AlekseyTs** [comment]
Creating an issue to track the open source effort.

**Comment by AlekseyTs** [comment]
Dependency on the Interna.DynamicHelpers have been removed. The next step is to bring expression compiler back in.

**Comment by ViIvanov** [comment]
Excuse me, can I post a suggestions about System.Linq.Expressions to Roslyn issues? Is this a Roslyn part or BCL part?

**Comment by AlekseyTs** [comment]
System.Linq.Expressions is not part of Roslyn. Please post suggestions at the appropriate BCL forum.

**Comment by ViIvanov** [comment]
Thank you!

**Comment by AlekseyTs** [comment]
Dependency on Internal.DynamicDelegate.Augments has been removed. Expression compiler is brought back.

**Comment by AlekseyTs** [comment]
https://github.com/dotnet/corefx/pull/1178
