### ISSUE TITLE
Proposal: obsolete ISourceGenerator, SyntaxReceiver and all non-incremental APIs

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#65106]
## Background and Motivation

The non-incremental generator APIs, namely `ISourceGenerator` & friends, are fundamentally not scalable and suffer from pretty big performance issues, which makes it so that they should literally just never be used. Them existing poses several issues:
- There's plenty of docs and blog posts around showing how to use these APIs. Especially new developers see them, think they're correct, and then proceed to write their own generators like that. Which means that:
  - They waste time learning how to use a fundamentally broken API
  - They will waste time when (ideally) migrating, as their architecture will not have been properly structured for incrementality
  - If they publish their generators, users will use them, potentially in large solutions, VS will become slow, and they'll just open tickets for VS without realizing the issue is with one of the NuGet packages they're referencing
  - Even if they don't open tickets for VS, they'll still just enjoy a much worse developer UX while working
- There's literally nothing that clearly tells them that these types should just never be used anymore

This same scenario happened several times on C# Discord, and it keeps happening.
It would be nice to just finally obsolete these types 🙂

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public interface ISourceGenerator
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public interface ISyntaxReceiver
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public delegate ISyntaxReceiver SyntaxReceiverCreator();

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public interface ISyntaxContextReceiver
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public delegate ISyntaxContextReceiver? SyntaxContextReceiverCreator();

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public readonly struct GeneratorInitializationContext
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public readonly struct GeneratorExecutionContext
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public readonly struct GeneratorSyntaxContext
    {
    }

+   [Obsolete("Non-incremental source generators should not be used, use IIncrementalGenerator instead.")]
    public readonly struct GeneratorPostInitializationContext
    {
    }
}
```

## Risks

No risks. This is not a binary nor a source breaking change. If people wanted to still use them they can just suppress the warning. It seems like just letting everyone use `ISourceGenerator` with no warnings whatsoever is a bigger risk on its own.

**Comment by jaredpar** [comment]
I'm not against this. When we went into source generators we went in knowing there was a decent chance we'd need to invent a better interface for the IDE, and if that happened we'd push the community in that direction over time. Incremental source generators are well established at this point and all our future design thoughts are around them only. I think an obsolete here as a nudge to get the ecosystem moving is fine. 

@CyrusNajmabadi, @chsienki, @KathleenDollard  thoughts?

**Comment by CyrusNajmabadi** [comment]
Yes.  We should obsolete (warning, not error) these.  It sends the message we want to send, while still being compatible.  Maybe in teh future we can then take a stronger stance and move to error and eventual removal.

**Comment by 333fred** [comment]
We should also add notes to the sg cookbook, and update the incremental doc to cover FAWMN.

**Comment by chsienki** [comment]
I'm pro this, but there are a couple of other things we'd need to consider too.

When we added incremental generators, we decided to 'smuggle' them in through `ISourceGenerator`, so all of our public APIs expect `ISourceGenerator` and there is a `.AsSourceGenerator()` you can call on an incremental generator to wrap it up. 

If we do this, we'd need to add replacement APIs that take `IIncrementalGenerator` instead and obsolete all the `ISourceGenerator` taking ones. Not hard to do, but just something we need to be aware of.

**Comment by Youssef1313** [comment]
Also what happens to the testing library?

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn-sdk/blob/ba5f8a6bf7b477b44a43ea943d3e831d6301afb7/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing/CSharpSourceGeneratorTest%602.cs#L13

and

https://github.com/dotnet/roslyn-sdk/blob/ba5f8a6bf7b477b44a43ea943d3e831d6301afb7/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.SourceGenerators.Testing/SourceGeneratorTest%601.cs#L34

**Comment by chsienki** [comment]
Yeah, we'll need to update the testing library too if we do that.

**Comment by RikkiGibson** [comment]
I was curious whether a custom obsolete diagnostic ID should be used here. e.g. if the user isn't ready to move away from ISourceGenerator, to enable them to suppress all the related warnings in one go.

**Comment by jjonescz** [comment]
@RikkiGibson I think that would be great, also to easily suppress the diagnostic across Roslyn. But seems that `DiagnosticId` is not present in `ObsoleteAttribute` that's available to Roslyn. See also https://github.com/dotnet/roslyn/pull/66462#discussion_r1073570050.

**Comment by 333fred** [comment]
We can use a custom attribute in the .NET 6/7 version of roslyn, and use the standard one in old versions.
