### ISSUE TITLE
Reading stdout while other xunit processes are writing

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6511]
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/258

```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.EventSymbolTests.MissingCompareExchange_04

Expected: TrueFalseTrue\r\n
Actual: Microsoft.CodeAnalysis.VisualBasic.UnitTests.EventSymbolTests.CustomEventTypeDuplicateErrors [SKIP]\r\n      530406\r\nTrueFalseTrue\r\n
```

The test verifies that "TrueFalseTrue" is written to standard out, but it sure looks like something else wrote to standard out at the same time (xunit, reporting a skipped test) and caused it to fail.

**Comment by amcasey** [comment]
From the same run:

```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.PropertyTests.ReadOnlyAutoPropertiesAndOverrides

Expected: 5_\r\n
Actual:        Microsoft.CodeAnalysis.VisualBasic.UnitTests.PropertyTests.Dev10IgnoresSentinelInPropertySignature [SKIP]\r\n      527657\r\n5_\r\n
```

**Comment by amcasey** [comment]
Also ```Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenGetTypeOperator.CodeGen_GetType_InLambda``` in http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit32/256

**Comment by amcasey** [comment]
FYI @jaredpar, this is a weird one.

**Comment by TyOverby** [comment]
Looks like this is because [`Execute`](http://source.roslyn.io/#Roslyn.Test.Utilities.Desktop/RuntimeAssemblyManager.cs,400) is capturing the standard-out for the entire process.

**Comment by TyOverby** [comment]
It looks like the two options that we have available to fix this is

1. Start a new process for every run that then runs the desired test.
2. Come up with a new way of "printing" from test runs.

**Comment by jaredpar** [comment]
I agree the current behavior seems strange / bad idea.  But I don't see how it's causing a bug in the current setup.  Right now all of the suites run serially so it doesn't seem possible for them to overlap here.

**Comment by TyOverby** [comment]
Locking / flushing behavior on stdout has been the source of bugs for me in the past.

**Comment by TyOverby** [comment]
Please note that in this test, we are only using Console.Write, not Writeln, so this might be a flushing issue?  Does C# flush only on newline?

**Comment by jaredpar** [comment]
@TyOverby hmm, that may be the case.  I believe it does indeed not guarantee a flush unless there is a new line.

**Comment by jaredpar** [comment]
@TyOverby it looks like the `StreamWriter` which is wrapped around the stdout stream is auto flush

http://referencesource.microsoft.com/#mscorlib/system/console.cs,374

But `Flush` in the `__ConsoleStream` is essentially a nop

http://referencesource.microsoft.com/#mscorlib/system/io/__consolestream.cs,109

It looks like flush is defined by the windows semantic here to the console.  I think that may indeed be guaranteed only on a new line.

**Comment by TyOverby** [comment]
It turns out that there are a *lot* of tests that start up threads, so my idea of whitelisting the "current" thread won't work without a huge rewrite.

Would it be possible to blacklist the Xunit thread?

**Comment by jaredpar** [comment]
@TyOverby that's unfortunate.  Does xunit always write from the initial thread?  If so I think we can track that.

**Comment by TyOverby** [comment]
What are you calling the "initial thread"?  The thread that the test runs in stays the same throughout the whole test (except for if the test code spawns a new one).

#### Threads
```
B = bad, G = good

B Xunit Thread
G    Test Thread
G        Maybe sub-threads if the test uses them
G    Test Thread
G        ...
```

**Comment by jaredpar** [comment]
I meant the initial process thread.  I believe that's different than the thread tests are run on.

**Comment by TyOverby** [comment]
I don't know but I would expect it to.

**Comment by TyOverby** [comment]
Is there a way to get the initial thread?  My googling efforts haven't payed off.  Is there a way that we could hijack the main thread - run some code there that sets up the blacklist - and then back off?

**Comment by jaredpar** [comment]
This bug should no longer repro.  After our lunch conversation I dug through the history here and found this failure occurred before my change to refactor how we do in process compilation, verification and execution.  Hence this failure occurred under the old model.

In the old model it was possible for binaries to be executed in the initial `AppDomain`.  Once we disabled `AppDomain` isolation in the process that meant it was executing in the same `AppDomain` as the xunit main loop and hence shared `Console.Out`.  So when xunit printed output to the screen it could interfere with our tests.  

My refactoring change ensured that we always emit and execute in a separate `AppDomain`.  This means the xunit main loop and our in process execution will never share `Console.Out`.  Hence this bug should no longer be repro after my change. 

Closing for now.  If this shows up again, outside stabilization, please reopen.
