### ISSUE TITLE
Remove Unnecessary Usings is modifying white space before first type declaration

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#65114]
**Version Used**: Version 17.5.0 Preview 1.0 [33027.274.main]

**Steps to Reproduce**:

1. Create a file with unnecessary usings, with spaces before the first type declaration
1. Create a `.editorconfig` specifying tabs
   ```editorconfig
   [*.cs]
   indent_style = tab
   indent_size = tab
   tab_size = 4
   ```
1. Invoke "Remove Unnecessary Usings"

**Expected Behavior**:

Only the usings are removed.

**Actual Behavior**:

Usings are removed, but trivia is also updated.

```diff
--- a/src/D2DLibExport/D2DGeometry.cs
+++ b/src/D2DLibExport/D2DGeometry.cs
@@ -22,22 +22,9 @@
  * SOFTWARE.
  */
 
-using System;
-using System.Collections.Generic;
-using System.Runtime.InteropServices;
-using System.Text;
-
-using FLOAT = System.Single;
-using UINT = System.UInt32;
-using UINT32 = System.UInt32;
-using HWND = System.IntPtr;
-using HANDLE = System.IntPtr;
-using HRESULT = System.Int64;
-using BOOL = System.Int32;
-
 namespace unvell.D2DLib
 {
-  public class D2DGeometry : D2DObject
+	public class D2DGeometry : D2DObject
   {
     internal HANDLE DeviceHandle { get; private set; }
```

**Comment by jasonmalinowski** [comment]
@drewnoakes: the .editorconfig is set to tabs, but the underlying file is still using spaces? I agree it's not ideal that we're touching that (and a bit odd we're not touching anything else...) but at the same time we more or less assume your .editorconfig is the source of truth.

**Comment by CyrusNajmabadi** [comment]
It's expected that we do some touching of things (since we often have to clean up after ourselves). However, in this case, as there are no usings in the interior namespace, we absolutely should not be touching anything there.
