### ISSUE TITLE
Add `=` for property completions inside initializers

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65130]
There is already a case, when VS suggests completion of an attribute property with a `=` char:
![devenv_B3k9UF81xG](https://user-images.githubusercontent.com/70431552/199109607-cf6d2c2e-e910-4b62-a7e5-6e23004f3f7d.png)

At the same time completions inside object initializers (which I guess are used more commonly) are just property names:
![devenv_vyWeifmcMW](https://user-images.githubusercontent.com/70431552/199109863-11087a26-0fe9-4e02-b00a-e6dca91de979.png)

I think, there is nothing bad if VS suggests properties with `=` inside initializers the same way it is currently doing in attributes. So I expect to get `MyProperty =` and `MyProperty1 =` completions in the sample above.

This thing also applyes to VB:
![devenv_BH9BAHGKQh](https://user-images.githubusercontent.com/70431552/199110262-11534159-3011-4f06-9d01-c8248583b857.png)
Here it would be cool if VS suggests `P =` completion instead of just a `P`

**Comment by Youssef1313** [comment]
Note: The following is valid:

```csharp
using System;
using System.Collections;

public class C : IEnumerable
{
    public string P { get; set; }

    public void M()
    {
        var x = new C()
        {
            P
        };
    }

    public IEnumerator GetEnumerator()
    {
        throw new NotImplementedException();
    }

    public void Add(object o) { }
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
