### ISSUE TITLE
C# compiler: severe performance issues with sister project

### ISSUE THREAD

**Issue by hopperpl** [dotnet/roslyn#65142]
Version: `7.0.100-rc.2.22477.23`

when compiling the dotnet sister project `Silk.NET`, I ran into a serious performance issue with the C# compiler.

https://github.com/dotnet/Silk.NET

it is the sub-project `Silk.NET.Direct3D.Compilers`
* compilation time 37 min
* requires 18 GB of memory

the other sub-project `Silk.NET.Direct3D12` compiles within 10 seconds

Both sub projects are very similar, it's just boiler-plate code for COM/DX wrappers, but it has some heavy sized source files.

You don't have to compile everything, these 3 steps fully suffice:
* `git clone https://github.com/dotnet/Silk.NET.git`
* switch to `src\Microsoft\Silk.NET.Direct3D.Compilers`
* run `dotnet build -c Release -f net5.0 -verbosity:diag`

The performance problem is solely the compiler, the long running command is `C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Roslyn\bincore\csc.dll" /noconfig /unsafe+ /checked- /nowarn:1701,1702,IL2121,1701,1702 /fullpaths /nostdlib+ <... and so on ...>`. This command is causing the 37 min execution time.

* disk I/O: nothing during the latter 36 min
* memory: steady increase at around  8 MB/s

Now, my guts tell me the compiler is running into some exponential growth here, like if another function is added to the source then compile time doubles to over 1 hour. Add 5 more and this is a whole day's job.

msbuild diagnostics:
* for `Direct3D12` : `7290 ms  Csc                                        1 calls`
* for `Direct3D.Compilers`: `2254364 ms  Csc                                        1 calls`

**Can I stick a needle in csc.exe (resp. csc.dll) do gather performance information? what it's doing all this time and why it needs 18 GB of memory?**

**Comment by CyrusNajmabadi** [comment]
Please provide a perf view trace. Instructions here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Recording-performance-traces-with-PerfView.md

**Comment by jaredpar** [comment]
@cston PTAL

**Comment by hopperpl** [comment]
So, this turned to be out as an Analyzer, which was called by csc, that is causing the issue. It is the Silk.NET.Core.Touch project which modifies source code (source generator). 

It is not a Rosyln compiler issue therefore, but some feedback from csc about long-running analyzers, source generators would be helpful. Maybe when an analyzer is running more than 5 seconds, print a log warning message. 

And as suspected, it is an exponential growth problem with the SyntaxTree.

**Comment by jaredpar** [comment]
> Maybe when an analyzer is running more than 5 seconds, print a log warning message.

Unfortunately we can't do that because it causes our builds to be non-deterministic. Time is generally a bad metric in the compiler because so many outside sources can influence it: power of the box, other actions happening on the box, the changes to the code size over time, etc ...

This is why we've invested in the `/p:ReportAnalyzer` property to provide the timing information so customers can make their own evaluation of impact.
