### ISSUE TITLE
Semantic snippets: `cw` snippet inserts unexpected blank line when between statements

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65150]
**Version Used**:
Latest main

**Steps to Reproduce**:
```cs
using System;

var a = 0;
$$
var b = 3;
```
Execute `cw` snippet at `$$`

**Expected Behavior**:
```cs
using System;

var a = 0;
Console.WriteLine($$);
var b = 3;
```

**Actual Behavior**:
```cs
using System;

var a = 0;
Console.WriteLine($$);

var b = 3;
```

**Comment by akhera99** [comment]
if I had to guess, I believe the issue is that I indiscriminately add trivia to each token in the snippet when I should match the trivia from the original document

**Comment by DoctorKrolic** [comment]
I wonder why you've designed semantic snippets the way they are currently done? Any snippet provider has to provide a snippet in a form of `TextChange`s (which it would most likely generate using syntax factory/generator) in order for them to be inserted into the document and then be parsed back to syntax again? There is a chain of `syntax (most likely) -> text -> syntax -> final text` in the end, where on the first transition snippet provider has to `NormilizeWhitespaces` in order to separate tokens, like `await Console...` in the `cw` snippet and on the last transition the base `AbstractSnippetProvider` has to manually add trivia around snippet tokens. Isn't it simpler and, as a result, more reliable to just give snippet provider a `SyntaxEditor`, so it can generate snippet as syntax nodes in the first place?

**Comment by CyrusNajmabadi** [comment]
> to just give snippet provider a SyntaxEditor, so it can generate snippet as syntax nodes in the first place?

This would tie snippets to C# or VB.

**Comment by DoctorKrolic** [comment]
> This would tie snippets to C# or VB.

`SyntaxEditor` is a shared public API that works with shared `SyntaxNode`s and can be used in any .NET language
