### ISSUE TITLE
Clean up syntactic classification of non-RDT'd buffers

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6516]
PR https://github.com/dotnet/roslyn/pull/6392 introduced special handling of non-RDT'd buffers in the syntactic classifier. This change makes this buffer tagger sometimes depend on its attached views, which really ought to make it a view tagger, but doing so make the classification not show up on RTF-copy or the enhanced scroll margin. We should do a couple of things.
1. (At least) Try to switch to an IViewTaggerProvider with the correct roles required to be part of RTF-copy/etc.
2. (Optimally/Additionally) Track such buffers in the MetadataAsSourceWorkspace to light up all IDE features.

**Comment by jasonmalinowski** [comment]
Also:

3. Correctly consume the MEF host from the MEF container instead of using DefaultHost which creates another one

**Comment by Pilchie** [comment]
This depends on #873 being checked in.

**Comment by Pilchie** [comment]
This bug was a follow-up to #873.  As that was reverted, this doesn't mean anything on its own.
