### ISSUE TITLE
Unused using statements are no longer greyed out

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#65169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Seemingly since I upgraded to Visual Studio 17.4.0 Preview 5.0, Visual Studio is no longer greying out my unused `using`s.  Here, I temporarily set IDE0005 to a warning to see what would've been greyed out:

![usings](https://user-images.githubusercontent.com/793830/199448936-2ebe3676-82d0-4eaa-bc2c-567aa0800cec.png)

I checked the options under 'Text Editor | C#', and 'Fade out unused usings' is checked.

### Expected Behavior

`using` statements not needed should be greyed out as before.

### Steps To Reproduce

Insert a `using` statement that isn't used by the code in the file.

### .NET Version

7.0.100-rc.2.22477.23

**Comment by Youssef1313** [comment]
That was supposed to be fixed in https://github.com/dotnet/roslyn/pull/62562 😕 

cc @mavasani

**Comment by mavasani** [comment]
Do you have EnforceCodeStyleInBuild MSBuild property set to true or explicitly have a NuGet package reference to C# code style analyzers package?

**Comment by jez9999** [comment]
I did have an explicit NuGet package reference, yes.  Removing it seems to fix it.  That reference breaks things now?

**Comment by Youssef1313** [comment]
@jez9999 Try using the latest version of the NuGet package.

**Comment by jez9999** [comment]
Do we still need to explicitly pull it in from NuGet or is its functionality bundled now?

**Comment by jez9999** [comment]
By the way, I had 4.3.1 (latest stable) referenced.

**Comment by Youssef1313** [comment]
@jez9999 Sorry if I wasn't clear, you need the previews.

The functionality from the NuGet package is shipped with the .NET SDK, and you can enable it via `EnforceCodeStyleInBuild`, but I'm not sure which version of the package is used in the latest .NET SDK.

**Comment by mavasani** [comment]
Yes, the fix for this issue went into the CodeStyle analyzer itself. So if you are either referencing an older CodeStyle analyzer package OR fetching it from within the SDK and the analyzer assembly is an older version than the one with the fix, then you would continue to see this issue.
