### ISSUE TITLE
Issues with error list entries with LSP pull diagnostics enabled

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65172]
**Expected behavior:**

![image](https://user-images.githubusercontent.com/10605811/199492396-4fb9f79d-4b3f-49d7-9eec-2ee25b3bd940.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/10605811/199492677-7421fb5a-7f1a-48da-826d-7653904f3302.png)

Note that the `Suppression State` column is empty and we are also missing the expansions on the leftmost column to view the diagnostic descriptions. Also the value for `Tool` column is different with pull diagnostics enabled (`Roslyn` vs `Compiler`).

**Comment by mavasani** [comment]
@dibarbet @CyrusNajmabadi - not sure if these are known issues. If so, and we already have a tracking item, feel free to close this one out.

**Comment by dibarbet** [comment]
thanks - not known I believe.  Assigning to myself.  Descriptions should be available in the spec so will have to dig into those.  Suppressions I don't think is spec'd so we'll have to talk with the client there.

**Comment by dibarbet** [comment]
Tracking the suppression state column externally
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1664419
