### ISSUE TITLE
Roslyn SDK VSIX intermittently fails to install

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6520]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p0/98
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p1/99

```
00:25:53.852 Installing Roslyn Templates\PreRelease\Roslyn SDK.vsix...
00:26:00.526     Retrying (failed with exit code 2)
00:26:00.526 Installing Roslyn Templates\PreRelease\Roslyn SDK.vsix...
00:26:06.504     Failed with exit code 2
```

File locking?

**Comment by amcasey** [comment]
I've added a failure cause to Jenkins.

**Comment by jaredpar** [comment]
This is happening on the VSI tests constantly.  Are we actively looking at this?

**Comment by amcasey** [comment]
@jaredpar, yes, @jmarolf and @brettfo are actively investigating.

**Comment by mavasani** [comment]
Reopening as this seems to be happening very often once again:

1. http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/307/console
2. http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/308/console
3. http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/561/console

**Comment by jmarolf** [comment]
This is no longer relevant as we no longer deploy the templates vsix on test machines
