### ISSUE TITLE
Share synthesized delegate types with same default parameter values

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#65213]
## The problem

```cs
var lam1 = (double d, int x = 10) => { };
var lam2 = (string s, int x = 10) => { };
```

Currently,
- `lam1` has type `<>f__AnonymousDelegate0` and
- `lam2` has type `<>f__AnonymousDelegate1`.

Do we instead want one generic type for both only differing in type argument, i.e.,
- `lam1` to have type ``<>A{00000000}`1[System.Double]`` and
- `lam2` to have type ``<>A{00000000}`1[System.String]``?

## Possible solution

`AnonymousTypeManager.AnonymousDelegateTemplateSymbol` would need to be updated, especially, `SynthesizedDelegateKey` would need to encompass parameter default values. Currently, it only contains ref kind bit vector which gets hex-serialized into the delegate name (`{00000000}` in the example above). Default parameter values cannot be serialized like that. Hence, these templates would need to be numbered similarly to current non-templated delegate types (`<>f__AnonymousDelegateN`).

---

This issue is referenced in code.

**Comment by jcouv** [comment]
Tagging @cston to background on current sharing strategy and thoughts

**Comment by cston** [comment]
It may be rare to have two synthesized delegates with default values in the compilation where the signatures have the same shape but distinct types. Is it worth optimizing this case?
