### ISSUE TITLE
Use the in memory compilation to build in VS

### ISSUE THREAD

**Issue by giggio** [dotnet/roslyn#6522]
Right now, if we ask for a build, VS will rebuild all the projects that changed. But VS already has the whole compilation in memory. This requested build should simply emit the in memory compilation to disk. This would be super fast.

**Comment by Pilchie** [comment]
We don't actually have the entire compilation in memory.  First of all, we only cache a few projects around the files being edited.  Second of all, the IDE never actually asks the compiler API to generate IL for method bodies.  It's *possible* that some time could be saved in parsing and building the symbol table, and (at the cost of memory), we could conceivably cache IL while binding method bodies for diagnostics.  It's not clear whether the improvements in build times would be worth the memory tradeoffs.

Additionally, there are quite a few build processes that end up changing input files during the build invalidating any of this work anyway.

**Comment by giggio** [comment]
If the possibility exists, and it could make the whole process faster, I would like to be in control. Or at least, partially. If I have 16GB of RAM, I would not mind spending 1GB or even 2GB to have a faster compilation. Give me the option.

Regarding the input files that change, isn't it the same on a regular build? Input files can change, regardless, right? So what is the difference?

**Comment by CyrusNajmabadi** [comment]
This suggestion isn't really viable as it doesn't correspond to how the compilers/compilations actually work.
