### ISSUE TITLE
HATS driven user/session exploration to identify progression/regression over the dev17 releases

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#65232]
Ask #1:
I think first order of business is to validate if the completion, lightbulb and error list goals are downtrending based on our telemetry and dashboards. If not, we can define goals there to improve. If there are no data/dashboards, @Cosifne's current work on telemetry and dashboards should help and we can continue pushing to expand on scenarios.

Ask #2: 
Here are the HATS survey verbatims - https://microsoft.sharepoint.com/:x:/r/teams/VisualStudioProductTeam/Shared%20Documents/Dev17%20VS%20Perf%20Epic/Planning/17.3%20Performance%20Feedback.xlsx?d=w42fc4a9a440149d2b7a0c1fdad5eced1&csf=1&web=1

The ask here is to reverse engineer the verbatims to session id to see if there are known problem areas across 3 features spaces to present the identified problems back to the Platform team.
- completion
- lightbulb
- error lists

**Comment by arkalyanms** [comment]
Tagging both @genlu and @mavasani to this to perform initial exploration.

**Comment by arkalyanms** [comment]
Here is the same effort from the 64 bit switch - https://microsoft-my.sharepoint.com/personal/gel_microsoft_com/_layouts/OneNote.aspx?id=%2Fpersonal%2Fgel_microsoft_com%2FDocuments%2FOneNote%2FGen-Shared&wd=target%28Shared.one%7C4306AC3E-5C63-411F-88B0-08EFDE96D897%2FFeedback%20ticket%20completion%20telemetry%7C7A3DCC38-C901-416C-A214-E12F2D393A9A%2F%29
onenote:https://microsoft-my.sharepoint.com/personal/gel_microsoft_com/Documents/OneNote/Gen-Shared/Shared.one#Feedback%20ticket%20completion%20telemetry&section-id={4306AC3E-5C63-411F-88B0-08EFDE96D897}&page-id={7A3DCC38-C901-416C-A214-E12F2D393A9A}&end

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
