### ISSUE TITLE
Roslyn experimental hive expired; cannot be activated in Community Update1 RC

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#6527]
I have a VM image with VS 2015 Community RTM installed (unactivated). Now, after more than 30 days, I started this VM and updated to Update1 RC. The "normal" VS can be activated by logging in with email address, but I found no way to do the same for the Roslyn experimental hive. As a result, debugging analyzers has become impossible.

Repro:
- Install VS2015 Community RTM
- Install Update1 RC
- Wait for 30 days, so VS starts with Activation screen (trial expired)
- Click Sign in, follow the wizard
- Click Sign out
- Create new analyzer and F5 to Debug
- Second VS instance starts with Activation screen. It shows: "You are not able to update your license in this application. Start Visual Studio to fix this issue."
- Clicking the Sign in button closes VS without any message; clicking the "Start.. to fix" link starts a normal VS instance, which is already activated.

How is the Roslyn hive supposed to be activated?

**Comment by Pilchie** [comment]
Thanks for the report.  I've confirmed with the licensing team that this was a known issue in the RC build that has since been fixed.

**Comment by vsugrob** [comment]
@Pilchie I have the same issue as OP. You mentioned that this issue was fixed, but I can't find new patch for Visual Studio 2015 Community to install. There is no version newer than Update1 RC on visual studio download page.

**Comment by bkoelman** [comment]
You can run the regular update, which updates all editions.

https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx

**Comment by vsugrob** [comment]
@bkoelman Thank you, I completely overlooked that link.
