### ISSUE TITLE
`IDE0019 Use pattern matching` Should be smarted about unused variables

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65287]
**Version Used**:
17.5 Preview 1

**Steps to Reproduce**:
```cs
void M(object obj)
{
    [||]var str = obj as string;
    if ((object)str != null)
    {

    }
}
```
Invoke `IDE0019 Use pattern matching` codeaction at `[||]`

**Diagnostic Id**:
`IDE0019`

**Expected Behavior**:
```cs
void M(object obj)
{
    if (obj is string)
    {

    }
}
```

**Actual Behavior**:
```cs
void M(object obj)
{
    if (obj is string str)
    {

    }
}
```
`str` is in the resulted code even though it isn't used. I think, in such cases codefix should remove unused variables. It is very unlikely that you will use this codefix while typing because such code style is kinda ancient nowadays and most likely you will use it to refactor an old code bases where it is already known if the variable is later used or not

**Comment by CyrusNajmabadi** [comment]
> str is in the resulted code even though it isn't used

This doesn't feel like a realistic scenario tbh.  Most times this is done is to typecheck and then use the value if it typechecks.  If the user really doesn't intend to use the variable they can remove (though i would def question that code).
