### ISSUE TITLE
Question: nuget package release schedule

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#65295]
Hi team, is there a release schedule for the NuGet packages? 
Since .NET 7 has been released, is there a release for the NuGet packages?

It seemed the NuGet packages are still in preview

![image](https://user-images.githubusercontent.com/7604648/200716254-d1d815bf-f1a8-4f11-bd4f-154977ce0901.png)

And when I use the preview package(`4.4.0-4.final`) to pack a stable package it reports a `NU5104` warning, should I ignore this warning or wait for the NuGet package release?

Thanks

**Comment by jasonmalinowski** [comment]
@WeihanLi Normally the answer is "right after release", but that doesn't mean we sometimes don't run into issues; this got held up due to some packaging fixes that had to happen. @jaredpar @ryzngard anything further to add?

**Comment by ryzngard** [comment]
Correct. Since it's a manual process there can be slight delays. Generally we snap to VS releases for our package releases. 4.4.0 is with VS 17.4 GA for example. We have to verify the packages, possibly modify dependencies to final releases, and do manual validation prior to publishing them.

**Comment by WeihanLi** [comment]
Get it, thanks
