### ISSUE TITLE
Analyzer to enforce "Async" suffix on methods returning tasks

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#65309]
It's quite common that I call out the need for an `Async` suffix on a method name during code review.

Given this is a standard convention, would a diagnostic that flagged violations make sense?

It would improve productivity by reducing feedback loops in several projects for which I review PRs.

Another convention such an analyzer may wish to support is `When*` methods, such as `Task.WhenAll` and friends, which do not end with `Async`.

**Comment by CyrusNajmabadi** [comment]
I blieve this analyzer already exists in the vsthreading package.  @AArnott  can you add more details?

**Comment by AArnott** [comment]
That is true. The analyzer is documented here: https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD200.md
