### ISSUE TITLE
Re-enable support in LSP code actions for creating files.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#65303]

**Comment by dibarbet** [comment]
Closing  - this is supported in the LSP server, but only currently works in VSCode as VS does not provide the capabilities for adding/deleting documents.  When they do, this should work in VS as well.

See https://github.com/dotnet/roslyn/blob/main/src/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHelper.cs#L152C23-L152C52
