### ISSUE TITLE
F1 help on `switch` keywords always opens documentation about switch statements

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#65312]
**Version Used**: VS 2022 17.5 Preview 1

**Steps to Reproduce**:

Select each of the `switch` keywords, then press <kbd>F1</kbd>.

```csharp
class C
{
    void M(int a)
    {
        _ = a switch
        {
            _ => 0
        };

        switch (a)
        {
        }
    }
}
```

**Expected Behavior**:
* The keyword of the switch expression opens the [switch expression documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression).
* The keyword of the switch statement opens the [switch statement documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(switch_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue).

**Actual Behavior**:
Both keywords open the switch statement documentation.

**Comment by jcouv** [comment]
Fix was merged for 17.5. Thanks @jhinder for reporting this
