### ISSUE TITLE
Filter out File-scoped types from ImportCompletion

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#65339]
![image](https://user-images.githubusercontent.com/788783/201203341-411bd3ce-8a2d-4ab5-9694-6586d7e3faee.png)

**Comment by RikkiGibson** [comment]
I assume this doesn't reflect a misbehavior in the LookupSymbols API?

**Comment by genlu** [comment]
> I assume this doesn't reflect a misbehavior in the LookupSymbols API?

This code path simply iterates through symbols from an assembly, so no
