### ISSUE TITLE
FakeSign failure - binary already signed

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6533]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p1/309

00:14:42.895   PE file is already strong-name signed.
00:14:42.895   Use the -f (force) option to sign d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\Binaries\Obj\SyntaxVisualizerControl\Release\Roslyn.SyntaxVisualizer.Control.dll anyway.
00:14:42.907 d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\build\Targets\VSL.Imports.targets(288,5): error MSB3073: The command ""C:\Users\dotnet-bot\.nuget\packages\FakeSign\0.9.2\tools\FakeSign.exe" "d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\Binaries\Obj\SyntaxVisualizerControl\Release\Roslyn.SyntaxVisualizer.Control.dll"" exited with code 1. [d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerControl\SyntaxVisualizerControl.csproj]

**Comment by amcasey** [comment]
This was worked around in pull request #6528 but that shouldn't have been necessary in the first place.

**Comment by amcasey** [comment]
Also,

00:14:42.907   PE file is already strong-name signed.
00:14:42.909   Use the -f (force) option to sign d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\Binaries\Obj\SyntaxVisualizerDgmlHelper\Release\Roslyn.SyntaxVisualizer.DgmlHelper.dll anyway.
00:14:42.916 d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\build\Targets\VSL.Imports.targets(288,5): error MSB3073: The command ""C:\Users\dotnet-bot\.nuget\packages\FakeSign\0.9.2\tools\FakeSign.exe" "d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\Binaries\Obj\SyntaxVisualizerDgmlHelper\Release\Roslyn.SyntaxVisualizer.DgmlHelper.dll"" exited with code 1. [d:\j\workspace\roslyn-internal_master_win_vsi_p1\Open\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerDgmlHelper\SyntaxVisualizerDgmlHelper.vbproj]

**Comment by amcasey** [comment]
This seems to have started this morning.  It's not (yet) clear what changed.

**Comment by amcasey** [comment]
I'm not seeing instances in stabilization, which suggests it was a commit to master that caused the problem (including, possibly, the merge from stabilization).

**Comment by amcasey** [comment]
As expected, the unit tests are unaffected.

**Comment by amcasey** [comment]
I've seen at least 11 failures across 7 machines, so it's probably not a machine state issue.

**Comment by amcasey** [comment]
Repros on my box.

**Comment by jaredpar** [comment]
Resolved via #6528

**Comment by amcasey** [comment]
@jaredpar You're not interested in finding out why it suddenly started failing - apparently, on every run - this morning?

**Comment by jaredpar** [comment]
@amcasey if we want to use this for tracking the investigating why this happened that's fine.  But I think it should be moved out of flaky / contributor pain then.

**Comment by amcasey** [comment]
@jaredpar Done

**Comment by amcasey** [comment]
Both calls to FakeSign are trigger by setup.proj.  Curiously, Roslyn.SyntaxVisualizer.DgmlHelper.dll and Roslyn.SyntaxVisualizer.Control.dll are signed twice each, but Roslyn.SyntaxVisualizer.Extension.dll is only signed once.

**Comment by amcasey** [comment]
It looks like we're signing the file twice because we're building it twice.  (Note that the second time we build it, compilation is skipped as a no-op so there isn't a fresh, unsigned file waiting for FakeSign.)

**Comment by amcasey** [comment]
Stabilization succeeds locally.

**Comment by amcasey** [comment]
Still confirming, but it looks like it can be fixed by removing the `quot;`s in `Outputs`:

```
<Target Name="FakeSign"
      Condition="'$(DelaySign)' == 'true' AND
                 '$(ShouldSignBuild)' != 'true' AND
                 ('$(Language)' == 'C#' OR '$(Language)' == 'VB') AND
                 '$(BuildingProject)' == 'true'"
      Inputs="@(IntermediateAssembly)"
      Outputs="@(IntermediateAssembly);$(PostCompileBinaryModificationSentinelFile)">

<Exec Command="&quot;$(FakeSignToolPath)&quot; &quot;@(IntermediateAssembly)&quot;" />

</Target>
```

**Comment by amcasey** [comment]
FYI @brettfo, could this be causing vsix issues too?

**Comment by brettfo** [comment]
@amcasey Not in any way that I can see, but given the odd issues we've seen, it's certainly possible.

**Comment by amcasey** [comment]
No recent reports.

**Comment by jaredpar** [comment]
This component was deleted entirely so definitely safe to close.
