### ISSUE TITLE
C# document outline add region

### ISSUE THREAD

**Issue by Cerbere64** [dotnet/roslyn#65333]
Hello,

It's a feature request for the new "Document Outline" feature for C# files.
Is it possible to view regions, with a collapse/expand management ?

Something like this :
![image](https://user-images.githubusercontent.com/49989377/201035728-b5185e7d-8b95-4235-ad72-a9693c4691bd.png)

Thanks

**Comment by CoolCoderSuper** [comment]
Add this to VB as well

**Comment by CyrusNajmabadi** [comment]
This woudl be a request for platform/editor.  Tagging @olegtk if you guys want to take this.  Closing out from roslyn.
