### ISSUE TITLE
False negative CS0029 for arrays

### ISSUE THREAD

**Issue by ds1709** [dotnet/roslyn#65357]
**Version Used**: 10

**Steps to Reproduce**:
```c#
class Program
{
    public static void Main()
    {
        object[] a;
        Program[] b = new[] { new Program() };
        a = b; // CS0029 error expected
        a[0] = new Exception(); // System.ArrayTypeMismatchException
    }
}
```

**Comment by Youssef1313** [comment]
This is behaving correctly per spec:

https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/conversions.md#1028-implicit-reference-conversions

There is an implicit conversion:

> - From an *array_type* `S` with an element type `Sᵢ` to an *array_type* `T` with an element type `Tᵢ`, provided all of the following are true:
>   - `S` and `T` differ only in element type. In other words, `S` and `T` have the same number of dimensions.
>   - An implicit reference conversion exists from `Sᵢ` to `Tᵢ`.

**Comment by jcouv** [comment]
That's correct. I'll go ahead and close a By Design.
