### ISSUE TITLE
Visual Studio 2022 formatting issue

### ISSUE THREAD

**Issue by Bgajic-mono** [dotnet/roslyn#65359]
**Version Used**:  Visual Studio 2022, 17.40

I'm using C# and have formatting issue since upgrading to 17.40

**Expected Behavior**:
1.
```
if () {
```
2.
```
if () |{}
```
press `Enter`

3.
```
if () 
|{}
```
**Actual Behavior**:
1.
```
if () {
```
2.
```
if () |{ }
```
press `Enter`

3.
```
if () 
    |{ }
```

This was working as expected in previous version of VS2022, something broke in the newer. I haven't changed any setting besides turning off the new thing that selects text with the same characters as currently selected. 
Indenting is set to `block`, insert spaces, automatically format while typing and on return is turned off.
Please help, this is really bothering.

After I complete } space is inserted between {} e.g. if () |{ }`. After I press enter while the caret is located before opened bracket, Actual Behavior step 3. happens.

**Comment by Bgajic-mono** [comment]
https://github.com/dotnet/roslyn/issues/30787

I found similar issue, though it's about smart indentation. It seems that the issue that I have is that even though everything is set to block, it still uses smart (along with space being inserted when opening a bracket). Please advise.

**Comment by Bgajic-mono** [comment]
Another useful thing, after closing curly space is inserted between the two, and on enter press this is the result:
```
{
    }
```
Expected:
```
{
}
```

**Comment by jasonmalinowski** [comment]
@Bgajic-mono Do you know which version of VS you were using before where this worked?
@tmat any idea if this is similar to the other regressions if something is handling options badly?

**Comment by tmat** [comment]
> Indenting is set to block

This makes me think it's probably the same issue as fixed by https://github.com/dotnet/roslyn/pull/65382.

**Comment by Bgajic-mono** [comment]
@jasonmalinowski @tmat I rolled back to 17.3.6 and it's working properly there.

**Comment by Bgajic-mono** [comment]
@jasonmalinowski @tmat 

I updated to 17.8.0 - no issues found regarding brace formatting. 

Unfortunately, it is now really hard to read tooltip text (intellisense etc.). Is there an option to turn off tooltip scaling with font percent scaling? E.g. At xxx%, font scaling should only scale editor text to xxx% and not tooltip text. Reducing the font size for "Editor Tooltip" and/or "Statement Completion" settings wouldn't work for me (reducing font size will result in "squashed" look).

**Comment by CyrusNajmabadi** [comment]
@Bgajic-mono Please file VS feedback using the built in VS feeback mechanism.  Thanks!

![image](https://github.com/dotnet/roslyn/assets/4564579/239c9409-c516-4907-919b-92e9d0e76127)

Closing this out as you have reported the formatting issue is fine.
