### ISSUE TITLE
When does AttributeData.AttributeClass return null?

### ISSUE THREAD

**Issue by weifenluo** [dotnet/roslyn#65355]
[AttributeData.AttributeClass](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.attributedata.attributeclass?view=roslyn-dotnet-4.3.0#microsoft-codeanalysis-attributedata-attributeclass) returns nullable `INamedTypeSymbol?`. When does it return null? I'm asking this question because I can't ensure 100% test coverage of my code.

**Comment by CyrusNajmabadi** [comment]
Best is to just spelunk through the source.  In this case, i can see one way it can be null is if the decoding of metadata for the attributes doesn't succeed. i.e. this:

```c#
        internal bool GetCustomAttribute(CustomAttributeHandle handle, [NotNullWhen(true)] out TypeSymbol? attributeClass, [NotNullWhen(true)] out MethodSymbol? attributeCtor)
        {
            EntityHandle attributeType;
            EntityHandle ctor;

            try
            {
                if (!Module.GetTypeAndConstructor(handle, out attributeType, out ctor))
                {
                    attributeClass = null;
                    attributeCtor = null;
                    return false;
                }
            }
            catch (BadImageFormatException)
            {
                attributeClass = null;
                attributeCtor = null;
                return false;
            }
```

**Comment by RikkiGibson** [comment]
I wonder if we could get a null AttributeClass here if the attribute type is defined in an assembly which is not referenced in the compilation. e.g. LibraryA defines SomeAttribute, then LibraryB uses SomeAttribute on a symbol, and in your compilation you only reference LibraryB.

It's possible we end up filling in some kind of error/placeholder attribute in that case, though.
