### ISSUE TITLE
Xml Doc dropdowns do not list inherited class members

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn#65351]
When trying to add things like a CREF or PARAMREF in an Xml Doc (C#), any members inherited from base classes are not displayed. The system does let you still add the item, but it is not resolved:

In the below, the class `Tenant` is derived from a class called `ChangeTrackedEntity` which defines the `Id` property (public, type Guid). But it is not listed in the displayed dropdown.
![image](https://user-images.githubusercontent.com/7371750/201264685-a7ff9dd1-897f-439f-9a1a-dba7acaf7888.png)

On adding `Id` manually and trying to `F12` (Navigate to Definition) into it, you get:
![image](https://user-images.githubusercontent.com/7371750/201264785-d3cc43fc-8339-4cd2-aa47-f3366b06aaa0.png)

Please move if this is not the right repo / system for this bug.

**Comment by CyrusNajmabadi** [comment]
Closing out.  The above is not legal.  The member must be referenced through it's actual containing type, not through any derived types.

**Comment by sujayvsarma** [comment]
What is "illegal" about accessing base class members through derived types? Isnt that the very purpose of inheritance? Or has inheritance become illegal?

**Comment by sujayvsarma** [comment]
@CyrusNajmabadi - No idea what you are pointing to as being "illegal" here.

1. https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/inheritance
2. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/
3. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments

All of the above describe inheritance in the same way that developers the world over know and use it. There is nothing in (specially the 3rd link) that says you cannot have a '.'-access into a base class. The only text about the content of the CREF is --

![image](https://user-images.githubusercontent.com/7371750/201389029-218dd75b-eb2a-478d-9344-b62176a161d2.png)

The best co-relation I can make between what you say and what is happening is that the Xml comment parser does not want to walk the inheritance tree during population of the dropdown -- is this your point? 

If not, please point me to the documentation that says this is illegal.

**Comment by CyrusNajmabadi** [comment]
> If not, please point me to the documentation that says this is illegal.

https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/documentation-comments.md#d314-see

The definition of the symbol you are referencing does not exist.  There is no Tenant.Id symbol, so it fails.

>  There is nothing in (specially the 3rd link) that says you cannot have a '.'-access into a base class.

You're misunderstanding the specification.  Unless specifically legal, something is not legal.  We don't say "we didn't remember to say thsi is not allowed, so you can do it".  We say "we only allow it if we explicitly stated it was allowed".

**Comment by sujayvsarma** [comment]
Ah. Thank you for your explanation.
