### ISSUE TITLE
Latest LSIF generator explodes failing to find service for ILspHoverResultCreationService

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn#65367]
**Version Used**: 4.5.0-2.22557.7

**Steps to Reproduce**:

1. Clone https://github.com/NTaylorMullen/LSIFDb
2. `dotnet build /bl`
3. Pass the binlog into the LSIF generator

**Expected Behavior**:
LSIF is generated

**Actual Behavior**:
![image](https://user-images.githubusercontent.com/2008729/201411540-1e9910dd-73a8-4b0b-9a2c-60c8d98217c6.png)

**Comment by NTaylorMullen** [comment]
Tried to isolate "a" failure and found a different one which may be hiding underneath (using the same repo steps above)?
    - **Fails:** 4.5.0-2.22554.6 (5 days ago)  79f430693384048224da2b87aa74b05a7bf96ecd
    - **Works:** 4.5.0-2.22552.19 (8 days ago)  dfcc1f720b2e84c06da057b6ab1225d773ff669f

The [GitHub diff of the two commits](https://github.com/dotnet/roslyn/compare/79f430693384048224da2b87aa74b05a7bf96ecd...dfcc1f720b2e84c06da057b6ab1225d773ff669f) bit doesn't seem to return anything for me but I might be holding it wrong 

![image](https://user-images.githubusercontent.com/2008729/201411777-63fb0d32-82fe-4ea8-bbe1-c1db6831990f.png)



Oh and there's nothing between those two builds according to nuget package explorer:

![image](https://user-images.githubusercontent.com/2008729/201411801-bec80a7e-6593-49f2-8eda-fb93c10e05a4.png)

**Comment by Youssef1313** [comment]
Likely related to https://github.com/dotnet/roslyn/pull/65264.

**Comment by jasonmalinowski** [comment]
@dibarbet Ah, right now it's just using the default MEF construction you get for AdhocWorkspace or any other workspace.
