### ISSUE TITLE
Another Round of Milestone Cleanup

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#65389]
Seems like the following could now be closed.  Thx

https://github.com/dotnet/roslyn/milestone/130
https://github.com/dotnet/roslyn/milestone/110
https://github.com/dotnet/roslyn/milestone/127
https://github.com/dotnet/roslyn/milestone/128
https://github.com/dotnet/roslyn/milestone/116 (although just released)

**Comment by jasonmalinowski** [comment]
We'll keep the 17.4 open since we're still doing bugfixes for it. @jaredpar any reason we can't close the rest?

**Comment by jaredpar** [comment]
None I'm aware of.

**Comment by jasonmalinowski** [comment]
So I closed the easy ones, but @arkalyanms and @jaredpar it looks like we have 264 open bugs in the 17.3 milestone. I'm not sure what you want to do with those before closing. IDE is to be blamed for most of them but there's a few compiler bugs too.
