### ISSUE TITLE
[Compatibility issue] VB compiler generates tons of BC36954 errors when I upgrade .NET 6 projects to .NET 7

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/roslyn#65392]
**Version Used**: 
4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46

**Steps to Reproduce**:

The following code reports BC36954 error when I upgrade a .NET 6 project to .NET 7.
```vbnet
Dim s = "123".AsSpan()
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEA3YaAuIUArgHZoAmIA1AD4CSAtgA7T4DOABAMoCe7+GIwCwAKAAKxYBgCWYTgFkIFYhhidxUCAHMoAQxGjOxjVNnzuUxXpmkAFAEoxJl5wAiMxpy4BeTgCIARgAmAGZ/ADoAQXZuZj17JyMTAFFSCh4pMTSMpRU1IA=

Out commercial .NET 6 VB projects have a lot of "Ref Struct" consuming code like this, because many 3rd-party dependencies require it.

The migration to other languages is unacceptable. If we can't migrate our .NET 6 projects to newer .NET versions smoothly, we have no choice but stop upgrading to newer .NET versions and begin porting these incompatible products to non-.NET platforms. 

**Diagnostic Id**:

BC36954

**Expected Behavior**:
No compilation errors.

**Actual Behavior**:
```console
error BC36954: Overload resolution failed because no accessible 'AsSpan' can be called:
    Extension method 'Public Function AsSpan() As ReadOnlySpan(Of Char)' defined in 'MemoryExtensions': 'ReadOnlySpan(Of T)' requires compiler feature 'RefStructs', which is not supported by this version of the Visual Basic compiler.
    Extension method 'Public Function AsSpan(start As Integer) As ReadOnlySpan(Of Char)' defined in 'MemoryExtensions': 'ReadOnlySpan(Of T)' requires compiler feature 'RefStructs', which is not supported by this version of the Visual Basic compiler.
    Extension method 'Public Function AsSpan(start As Integer, length As Integer) As ReadOnlySpan(Of Char)' defined in 'MemoryExtensions': 'ReadOnlySpan(Of T)' requires compiler feature 'RefStructs', which is not supported by this version of the Visual Basic compiler.
```

**Comment by jcouv** [comment]
@Nukepayload2 These Span APIs should have been inaccessible from VB in .NET 6 already. A mechanism was in place (attribute `[Obsolete("Types with embedded references are not supported in this version of your compiler.")]` emitted on ref structs) to prevent compilers without ref sruct support from using types they didn't understand/support. 

This mechanism was imperfect as the following example shows (compiled against .NET 6 TFM):
![image](https://user-images.githubusercontent.com/12466233/201510807-59343de4-d393-4511-93b2-1ac820c7c9b9.png)

In .NET 7, this mechanism was strengthened, resulting in the message you're seing: "... requires compiler feature 'RefStructs', which is not supported by this version of the Visual Basic compiler.".

Tagging @333fred @jaredpar @AlekseyTs in case anything to add or if they can think of a possible mitigation.

**Comment by Nukepayload2** [comment]
@jcouv If you remove `As ReadOnlySpan(Of Char)`, there will be no obsolete errors.
```vbnet
Dim s = "123".AsSpan()
Dim iCanEvenSliceIt = s.Slice(1)

```
![image](https://user-images.githubusercontent.com/10798596/201521421-3c42c21e-14ff-4da3-a5d5-fa2fcc6e708e.png)

**Comment by AdamSpeight2008** [comment]
```vbnet
Imports System
Imports System.MemoryExtensions

Public Module Program
    Public Sub Main()
        Dim s = "123".AsMemory
        Dim iCanEvenSliceIt = s.Slice(1,1)
        Console.WriteLine(iCanEvenSliceIt)
    End Sub
End Module
```

**Comment by Nukepayload2** [comment]
@AdamSpeight2008 
Some 3rd-party libraries don't have `Memory(Of T)` overloads. They only provide `Span(Of T)` overloads. In .NET 6 projects, I can convert `Memory(Of T)` to `Span(Of T)` by getting the `Memory(Of T).Span` property. But I can't do that in .NET 7 projects.
