### ISSUE TITLE
[Test Failure] "Git Failed to Fetch Error" in prtest/win/dbg/unit32 on PR #6531

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6539]
PR: [#6531](https://github.com/dotnet/roslyn/pull/6531) *Support removal namespace in interactive mode* by @drognanar
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/835/

**Issue 1: Compile Error**

**Issue 2: Git Failed to Fetch Error**
Failed to fetch from Git.

**Comment by davkean** [comment]
This looks like a transient error talking to githu. Not sure what we can actually do about this, other than watch and see if occurs. Closing, will watch to see if this is happening a lot.
