### ISSUE TITLE
Rename constantly failing in MAUI Apps

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#65397]
**Version Used**: 17.5p1 public

**Steps to Reproduce**:

1. Create a new .NET MAUI App
2. Open a CS file, insert a method named M.
3. Attempt to rename the method to M2.

**Expected Behavior**:

Method is renamed

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/2371880/201495478-ae6eb211-2188-4f0f-8c90-7feb04bc15ff.png)

It does not appear to work correctly with any combination of old/new rename UI or async/sync rename.

**Comment by 333fred** [comment]
I will note that changing the name of a thing, and then invoking the rename thing quickfix, does generally seem to work. The other way never does in my MAUI projects.

**Comment by 333fred** [comment]
@ryzngard does your fix also fix non-inline renaming?

**Comment by ryzngard** [comment]
@333fred this fixes rename ui that comes from the command invocation, not the lightbulb (called rename tracking)

**Comment by DiogoMartinh0** [comment]
When can we expect to be able to use this?

**Comment by ryzngard** [comment]
@DiogoMartinh0 it should be in 17.5 Preview 2

**Comment by DiogoMartinh0** [comment]
Issue seems to still be present in Version 17.5.0 Preview 2.0

**Comment by 333fred** [comment]
There's no way this could have made p2, it was merged after p2 released. I'm guessing that was a typo for p3 @ryzngard?

**Comment by DiogoMartinh0** [comment]
Merged 4 days before P2 release seemed too close to the release but...

**Comment by ryzngard** [comment]
Yes, definitely a typo. Preview 3 not 2.

As a work around you can still use rename tracking (rename the item and then use the lightbulb to finish the rename)

**Comment by DiogoMartinh0** [comment]
When is P3 expected to be released?
