### ISSUE TITLE
Add IDExxx rule for converting multiline string to raw string

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65405]
Currently there is only "Convert to raw string" code refactoring with fix-all support (weird. How can a _refactoring_ has _fix_ all? I doesn't fix anything). Using this fix-all is not much helpful as it converts all strings to raw form, even simple single-line onse, e.g. `"a"` -> `"""a"""`. It would be a lot more helpful if there is an `IDExxx` rule for converting only _multiline_ strings to raw form, .e.g
```cs
@"First line
Second line
"
```
to
```cs
"""
First line
Second line
"""
```
Such rule should check for language version and probably be _suggestion_ by default.

**Comment by Youssef1313** [comment]
> How can a refactoring has fix all?

The general support for refactoring fix all was worked on by @mavasani https://github.com/dotnet/roslyn/pull/60906

and for this specific refactoring: https://github.com/dotnet/roslyn/pull/61105

**Comment by mavasani** [comment]
NOTE: If we intend to scope the FixAll to only work on a smaller subset of strings than it does today, we probably need to use more fine grained equivalence keys for the registered code actions.

**Comment by CyrusNajmabadi** [comment]
> How can a refactoring has fix all?

it can go an update all occurrences within a particular scope.

**Comment by CyrusNajmabadi** [comment]
> If a refactoring needs fix all it is probably not really a refactoring and it should be analyzer/codefix

It's not an analyzer/fixer.  There's no rule being enabled here.  It's just a transformation people can apply, but may want to apply to multiple locations (e.g. all the cases in a method, or in a file, etc.).

**Comment by CyrusNajmabadi** [comment]
>Such rule should check for language version and probably be suggestion by default.

We definitely do not want to turn this on as a suggestion.  It's not expected that raw strings be the idiomatic way to write these cases.

**Comment by DoctorKrolic** [comment]
> it can go an update all occurrences within a particular scope.

I mean, it is mostly naming problem. Refactoring doesn't fix anything, so it cannot have _fix_ all scopes)

> There's no rule being enabled here

There is no rule, that you should use pattern matching instead of `as` cast and null check either. But this is an `IDExxx` rule, while case with raw strings isn't. From my understanding, there is not that much difference here.

> We definitely do not want to turn this on as a suggestion

Well, even if hidden by default, having an analyzer opens a lot more options. Users would be able to either elevate or completely suppress the rule via VS settings or `.editorconfig`. Like my personal preference would be a suggestion, so I can make code more readable (especially for strings with escape sequences) and keep it readable with the help of my IDE.

**Comment by CyrusNajmabadi** [comment]
>Refactoring doesn't fix anything, so it cannot have fix all scopes)

Sure it can.  It's the scopes that the code fixup is applied to.  'fix' doesn't mean "broken".  It's akin to "fixing lunch" :)

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
