### ISSUE TITLE
Warning about null value while value is set as not null

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn#65406]
**Version Used**: 
Visual Studio 17.4.0

**Steps to Reproduce**:
```cs
using System;
using System.Diagnostics.CodeAnalysis;

#nullable enable

public class A
{
    private readonly string _s;

    public required string S
    {
        get
        {
            return _s;
        }
        [MemberNotNull(nameof(_s))]
        init
        {
            if (_s is null) throw new ArgumentException("Must not be null or empty");
            _s = value;
        }
    }
}

public class C
{
    public static void Main()
    {
        new A { S = "" };
    }
}
```

**Diagnostic Id**:
```
warning CS8618: Non-nullable field '_s' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```

**Expected Behavior**:
No warning.
The field `_s` is not null after `init` block which specifies it using `MemberNotNullAttribute`.

**Actual Behavior**:
Warning about making `_s` to be nullable.

**Comment by NN---** [comment]
Probably the same as #43587

**Comment by jaredpar** [comment]
@333fred to confirm dupe

**Comment by 333fred** [comment]
Unrelated. I'm not sure whether we really support this scenario, however. We generally don't process property bodies when considering nullability of fields, but we might make an exception for MemberNotNull of required properties. We'll need to run it by LDM.

**Comment by 333fred** [comment]
https://github.com/dotnet/csharplang/issues/6754 will be discussed by LDM on Wednesday. There are some subtleties to this request: chained constructors, in particular, are more difficult than they appear on the surface, as we would need to use `MemberNotNull` attributes to infer a _starting_ state for the mentioned members, not just an ending state.
