### ISSUE TITLE
Make ReferenceLocation.IsWrittenTo public

### ISSUE THREAD

**Issue by FelixKeck** [dotnet/roslyn#65408]
## Background and Motivation

I'm trying to find all references of a variable and distinguish them by read/write accesses. Therefore I use `SymbolFinder.FindReferencesAsync`. The returned reference locations have a property `IsWrittenTo` which looks like it provides this information. Sadly this property is internal so I cannot use it. Is it possible to make this property public or are there other ways to retrieve this information? Thanks for feedback.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.FindSymbols
{
     public readonly struct ReferenceLocation : IComparable<ReferenceLocation>, IEquatable<ReferenceLocation>
     {
-        internal bool IsWrittenTo => SymbolUsageInfo.IsWrittenTo();
+        public bool IsWrittenTo => SymbolUsageInfo.IsWrittenTo();
     }
```

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi @mavasani Any reason we shouldn't do this?

**Comment by CyrusNajmabadi** [comment]
Generally speaking, because it's not a good representation of things (and really should be removed).  References can be bucketed into many disparate concepts.  So finding the write way to represetnt that isn't clear.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We recommend using IOp for this purpose.
