### ISSUE TITLE
Implement-Constructor not offered.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6541]
Repro code:

```c#
class Base
{
    public Base(string value)
    {
    }
}

class Derived : Base
{
}
```

We get the error:
There is no argument given that corresponds to the required formal parameter 'value' of 'Base.Base(string)'

We should be offering to "implement constructor" here.

**Comment by jmarolf** [comment]
But base isn't an abstract class...  I assume you are asking for us to implement a new codefix that offers to add the required constructors?

**Comment by CyrusNajmabadi** [comment]
@jmarolf Good point.  Will update the title.

Note: we get this right if you try to "generate type".  We just don't do this properly for the case where you have both types already.

**Comment by jmarolf** [comment]
@CyrusNajmabadi yep, the existing codefixes should always check for this case when generating a type. We'll just need to implement a new one that addresses this.
