### ISSUE TITLE
Analyzer / generator shadow load directory needs to be per user on Unix

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#65415]
Context: https://github.com/dotnet/runtime/issues/77723

The root cause of this problem is the temp directory on Unix is the global one while on Windows it's per user. Hence there is a bit of a disconnect on how the shadow copy logic works there. Need to add a user component to the path on Unix to make things consistent here. 

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by akoeplinger** [comment]
Looks related to https://github.com/dotnet/roslyn/issues/61900

**Comment by akoeplinger** [comment]
I also think I saw either the sdk or nuget running into a similar issue but can't find the relevant GitHub issues.

**Comment by a74nh** [comment]
> Looks related to #61900

Curiously that issue is asking for permissions to be made more restrictive (755->700), whereas the "quick fix" for this issue would be be less restrictive (755->777).

(Agree that the proper fix for this would be to create directories per user).

**Comment by akoeplinger** [comment]
I just found the change I had in mind: https://github.com/dotnet/msbuild/commit/7f3a30cd04aa884699b7980a9209aade28f1eca2

**Comment by mrgleba** [comment]
Is there a chance this would get fixed sooner than 17.6?
Right now it's impossible to use roslyn on a linux box by more than 1 person.
The first user to create /tmp/CodeAnalysis locks everyone else out.
