### ISSUE TITLE
Type `T[]*` reports parser error

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#65429]
**Version Used**: 

VS 17.5p1

**Steps to Reproduce**:

Type a code snippet that uses `int[]*`:

```csharp
#pragma warning disable CS8500

static unsafe long IterateBits(long* array, int length, int* @out)
{
    var baseVec = Vector256.Create(-1);
    var incVec = Vector256.Create(64);
    var add8 = Vector256.Create(8);
    var initOut = @out;

    for (var i = 0; i < length; i++)
    {
        var w = array[i];
        if (w == 0)
        {
            baseVec += incVec;
        }
        else
        {
            for (var k = 0; k < 4; k++)
            {
                var byteA = (byte)w;
                var byteB = (byte)(w >> 8);
                w >>= 16;

//                       ↓ here
                fixed (int[]* pVt = BitPosTable)
//                     ~~~~~~
                fixed (int* pByteA = pVt[byteA], pByteB = pVt[byteB])
                {
                    var vecA = Vector256.Load(pByteA);
                    var vecB = Vector256.Load(pByteB);
                    var advanceA = LengthTable[byteA];
                    var advanceB = LengthTable[byteB];
                    vecA = baseVec + vecA;
                    baseVec += add8;
                    vecB = baseVec + vecB;
                    baseVec += add8;

                    Vector256.Store(vecA, @out);
                    @out += advanceA;
                    Vector256.Store(vecB, @out);
                    @out += advanceB;
                }
            }
        }
    }

    return @out - initOut;
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgYgA4CcIHNIAIDuEUyzpYAmUAzhMADYCmWAwgMoAcArAAwcA0jrAzACYAjAFgAUBIACHLFOEA6AEoBXGABcoYWgoCSGlLHJQAxuQDc02fIBsWACpU6lya9tY1lAGb1qAexhiXXVaNBCAISh1cgAKf0CAKix8NABPXlh1LDpA9QALDI0kqSk/FXUASgkAbwkseqwAN3wsYAhyWgA1WhMsAF4sbpN1PxRBNhsFBhRaCBCYgFphCpcGppbYEyH+wZ6RsYmpmbnaGJsAFhW6huaUZJISFh2h/fHJ6dn5livxNdusWBRADy5R2JTK6hc13qXlGWBi/ygOw45gBWAAPNlaLk8qioABqfFVX4NWoktb1f44HYpCCpADaUAAuqsKfUoF54dS+gMOMS2fUyQKKW0Ott8QNNkNWWyAL7Qim0agdBVrIXChqwu4IloAa2RqP1mPOhsJ/I1gtVFvWd2AqRCAEEdjE7SEKjgZdbKS1XbRws7fRUYtSAHwhrDfT1e0MhgbCGxQ8lerAAehTWAACvgOncKOQVLQQACsh1aGByFh8nNK3l6OpUkh6AByTL0pkAfgSTatFrTWBMEBgMD8WWA9BmCxwhnUIRgyQrLY0ba7yWo+TK6DyxYBFbAo3omRUUSgjR0PY1XigAA9aCR4a2O0kkJ0sgNIuoM35yI4aLRzcmsEvG87xiTIn3Ce1aCdAZn3UelfQdJleCQCCIh2WD4Mg8ImX/ZN1QAv4WlPExoN2YZRjeBQABk/AgEgYhQyCHR+AiKX+Yj/QGF4KMOGi6IY1C/RY1ibhaOjmhgEwoJ2KjsXQfIfzoTDHRZc8vX+cTBykzisFknFFNoZS/VUpNWOI0jRS6HosHxJoegdKMCMs8UBjox5HIAjidmc6zbI4jzkx83oJXudyJDU61uIOSYmH2U5zN4cFymEkS5FKUEQs0ySoICr0oso2L9wRHpwkS9LKly60kqyTKSAk7TKrlCL6nlUyGlatZWoVKQAHY0ohLAFgBQh1BBSEJC61xLzoOR4zkQQHCcWgagkABIKR+FmuxjhIAJqFSYa4KZXS5IUpb+jWslVtWngsGEXh7qwQQHt4Z6nt4fgXve77Pp+j7eHObg1tWx63re37wf+rBAb+rBfph+GAd4NggfEa7QdeqHIbhpHYcRnHodxlHgex/H8ZhlGCZhimieR3gbFR9HMdh0ncdZwmqdpkmobJ3Gac5jnKf5ymGe5gneY5/nybpwWZdFtHVulrAhZlkXaeV+m5c1rAesZkHmex9mYaNqHqbpsXfols2NYF/nhc1i3Tad2XbZl+2sHl66lZVm21Zdv2/YZnW9ZN12be99W1eBiP/e192g8D3hdejvm3dVuP049rWs+D4H4+zoPdZtoPC+1oui5YNbZUTdbNvcHa9oOh82ywd9P2/c6+ku4GYFoHAW+qLBbuH3gR6H0fR6wWU9d7/vjsHx6x6Xieh6nme+4H77l/Hnfh7XnuN/nu7me3pf94V2fN9+0+V736eD7nrAF6hm/d/P67L6P7HX7v9fH+f2GP936rU/k/DmP9b7ANAQAmGEDV73wvofMBb1YG3zQfAv+m8MbgPQb/B+V9cZwNkAgj+SCAH4yASQkBZDYaoN3pAqh0Dj60NwZPRhNDKZELYZgo+j1OGsLfuw/+31+H0LEcQnhYDsGiNPlAmhv0ZECIkfg3hUNFHiLkcI7G6iz5CKwczBRSjNGb35kQ4xqiXaUMkYPFBMsrEqKkczUxuDzFgPxjohh1jmHuKMXor+zsPEYIcQA7GzjBFeKDlwoJiDhGPUiUo7hwTvrxPEZ4pJ2CUmyL8W47WZjsnkNyb4rx2NMkuPycwkpRSkkw1Kak6JpDYm41qbo4pTSEn1OoY076NSqkxIIRzZpaS+kWPxoMjpTDQmFI0eU7BoyyleL9nkrxfCplZNacXdpyjhmOJEasoZDT+mLN6QckZ2c1lJO0Xs8J6SDFnP2Z0kxdy6lbJOTs/mYyXkPP8S7D5riQnq2aX8gWRzpnLICVcz5EzwU5xaTclhGzrnbMHkXKJkKaGPRRZsoFb1MXPMSUiipScsXlN+ri+xBLHqkuJesqleLxnotucHZ5QKYZkuOV8t5RK6Voq0bjNloK4W2KZecgl+N+Wwopc7cV+LXk2Kleyphsy+XzKSZTaVArJU23VXgglb01XUsFTLbVQLDHCoVQygm+rmXlMuWajVsrCWWq5RKh1/NtUyo5TAo15reUu2NTMpx3r7WeuBc6lVmqfF2p1Q6yZWrw0OqVX6+5TDS7co9YqsuBrdWZu5UCjJYbg1MN+qm8lCaoYlvjSGypUbk0WureKllObS0hsej0mtiKY1tPbdGltgac4NpJV2/1YKBYVo7VW52Y6e0ZvhVOoFft3X0q6Qun1m89VNsrTO9d/bN3yOzsOuFpqp3ppoba49S79GwxXeOph7yC0ut7T8+9J7fV3u7Xmvt17p17qfe+gNoad03tPdCud/7Y1fqBSwTZtaulQbTRe75cGlmGojFmh1v0kNocfRhrDUKCaYetSO7GBGH23t4CR1dFiYYUcLcBjmNHSN1txgxl9/TqO4YtfjFjCHkHO24zyy9saGPzvI9BnjADKb8dY98yTHGunbv4yamWUnxPeOU5R3jTrUOEZQ6a4T5T+YqYE1R9TOns0u0U2B9W+mvGRssyOuzu7fWOdo/J6FJGgVByM9JnZXm5Nru1kZj9yTRNmfQ4F/zpyc72YueW0LIqy2wz865x50XIucrS2FidAz4tOcE12mzSS5naYS9hgreXvnFcK5q2NyXv3CL9kF/9jWNNyoRTFmr2dqvhfa61tTvWUuVa6xVnZZ7cuqbfR1xLk2RttZm4N0bALxvGZyb+7rZW1swYCwBurPn/k7fi0CiuYmVsAOO7mm1XKmtEau312l13D23ay3h+7fXE3ncY8I1ly3ZvMO+yV37QqPu/ewf99bRblUA4WwUjmwOgPOch+DpjAs4enbjVD0rM6rVTey9jt7zM8fQ606jrbUXCefe26aknqnE3k720mjHpOMt0/h9tt1P2aefqe/VtjQakddMjaj7F0KhdWYAx9zz3P8eAZx3h1Nsvkfy9+8WqXRPKU5v55TjXIPGVK9Z0fNt1OecmZl4DodHO0eg+1/r1bhuLfBeK6Lml5uMfBdq9zkTpvnsWuvZrmT1uKcWO3Xr43q3fc660yH+nY2mUebF0ej3Bn932//W+p3sXf3p865nw7g6c+u//ZGkPwuDux/p4mtP5Gp5VxcK1IAA===)

**Expected Behavior**:

No parser error on `int[]*`: C# 11 allows managed-typed pointers.

**Actual Behavior**:

It seems that C# syntax parser cannot correctly handle the expression `int[]*`; we should add an extra but unnecessary token `?` to make parser behave well: `int[]?*`.

![image](https://user-images.githubusercontent.com/23616315/201832791-ce9cf68d-d24a-46d6-88ec-92b775068685.png)

![image](https://user-images.githubusercontent.com/23616315/201832853-b04ac266-0e7c-48eb-b3c8-7628a66ad944.png)

**Comment by RikkiGibson** [comment]
It would be useful to know if this problem is particular to use inside 'fixed' expressions or if it is the same for locals, parameters, etc.

**Comment by Youssef1313** [comment]
@RikkiGibson Not specific to fixed.

**Comment by CyrusNajmabadi** [comment]
The original code looks *very* intentional.  there are explicit tests that disallow this.  Did something change here wrt what we think should be legal or not?  @jaredpar ?

**Comment by Youssef1313** [comment]
For reference, it was done in https://github.com/dotnet/roslyn/pull/32431.

**Comment by jaredpar** [comment]
The part about the nullable annotation is confusing me a bit. Is that saying a work around for the bug is to add the nullable annotation? 

There was an explicit change to allow pointers to managed types in C#. Previously that was an error but now it's a warning. This was part of the general theme of [downgrade errors to warnings](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-09-21.md#unsafer-unsafeness) for memory safe diagonstics if they occur inside an `unsafe` context. The ask to make `int[]*` follows from that decision.

**Comment by CyrusNajmabadi** [comment]
> This was part of the general theme of [downgrade errors to warnings](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-09-21.md#unsafer-unsafeness) for memory safe diagonstics if they occur inside an unsafe context. The ask to make int[]* follows from that decision.

Gotcha.  Then making this change def makes sense to me.

**Comment by Youssef1313** [comment]
> The part about the nullable annotation is confusing me a bit. Is that saying a work around for the bug is to add the nullable annotation?

When parsing a type, the parser says: if we got `*` and previous token was `]`, don't parse. So adding the `?` in between makes the parser happy.

**Comment by CyrusNajmabadi** [comment]
Agreed. We should parse according to our grammar (which allows this).  Disallowing (if we want that) should be done semantically.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Umm.. Revisiting the grammar in https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/grammar.md, it doesn't seem it allows it?

Following is part of the grammar:

```antlr
pointer_type
    : value_type ('*')+
    | 'void' ('*')+
    ;

value_type
    : non_nullable_value_type
    | nullable_value_type
    ;

nullable_value_type
    : non_nullable_value_type '?'
    ;

non_nullable_value_type
    : struct_type
    | enum_type
    ;

struct_type
    : type_name
    | simple_type
    ;

enum_type
    : type_name
    ;

simple_type
    : numeric_type
    | 'bool'
    ;

numeric_type
    : integral_type
    | floating_point_type
    | 'decimal'
    ;

integral_type
    : 'sbyte'
    | 'byte'
    | 'short'
    | 'ushort'
    | 'int'
    | 'uint'
    | 'long'
    | 'ulong'
    | 'char'
    ;

floating_point_type
    : 'float'
    | 'double'
    ;
```

**Comment by RikkiGibson** [comment]
This strikes me as a case of using grammars to enforce semantic rules, which we don't really do in the implementation. The "grammar" effectively in use in the implementation permits parsing many invalid programs simply so we can have a better guess at what the user meant to do. The corresponding spot in the grammar generated by the implementation is:

https://github.com/dotnet/roslyn/blob/1c349c7032ec178955a8fcccc62015ee39b00031/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4#L400-L402

Since we are downgrading the *pointer to managed type* from error to warning in unsafe context, we might want to adjust the standard for C# 11 to indicate that pointers can also refer to managed types.

**Comment by CyrusNajmabadi** [comment]
> we might want to adjust the standard for C# 11 to indicate that pointers can also refer to managed types.

I think we have to do that :)  Otherwise we're not a compliant impl :)

**Comment by hamarb123** [comment]
FYI I also discovered this 9 days ago https://github.com/dotnet/csharplang/discussions/6692 (https://github.com/dotnet/roslyn/issues/65529), so it's clearly something that people may run into.
