### ISSUE TITLE
Documentation Xml does not contain documentation from Source Generators generated code

### ISSUE THREAD

**Issue by codetuner** [dotnet/roslyn#65426]
**Version Used**: 

Microsoft.CodeAnalysis.Analyzers: 3.3.3

**Steps to Reproduce**:

1. Have a Source Generator project containing a Source Generator generating a class in your code, including XML comments. I.e:

            [Generator]
            public class CustomGenerator : ISourceGenerator
            {
                public void Initialize(GeneratorInitializationContext context) {}
                
                public void Execute(GeneratorExecutionContext context)
                {
                    context.AddSource("myGeneratedFile.cs", SourceText.From(@"
                         namespace GeneratedNamespace
                         {
                             /// <summary>
                             /// This is documentation for SomeGeneratedClass...
                             /// </summary>
                             public class SomeGeneratedClass
                             { }
                         }", Encoding.UTF8));
                }
            }

2. Use this Source Generator to generate the code in a(nother) project.

3. For that other project, enable documentation file generation (in project properties)

**Expected Behavior**:

The generated documentation ({AssemblyName}.XML) should contain the documentation for the SomeGeneratedClass class.

**Actual Behavior**:

The generated documentation ({AssemblyName}.XML) does not contain the documentation for the SomeGeneratedClass class.

**Comment by jjonescz** [comment]
Thanks for reporting this issue. However, I cannot reproduce the problem. [This example](https://gist.github.com/jjonescz/02a66a267888ec347ebd8594e7c167c0) generates the following XML doc:

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ClassLibrary</name>
    </assembly>
    <members>
        <member name="T:GeneratedNamespace.SomeGeneratedClass">
            <summary>
            This is documentation for SomeGeneratedClass...
            </summary>
        </member>
    </members>
</doc>
```

**Comment by codetuner** [comment]
Hi! I'm sorry, it's indeed more subtle than I thought. After further investigation I found it seems to relate to where the code is generated to and when it is generated. But I'm working on a sample to reproduce the problem.

**Comment by codetuner** [comment]
Ok here I have it: https://gist.github.com/codetuner/ab68269bf631f8413c3c5b85d1d325b3
The solution consists of 3 projects. See the README in the Gist.
When running, Swagger shows documentation for the Id property of the SupplierDto class (which is not generated by the SourceGenerator), but does not show documentation for the Id property of the CustomerDto class (which is generated by the SourceGenerator).
See screenshot: https://i.ibb.co/jkr0YWL/2022-11-18-00-40-53-Swagger-UI-Personal-Microsoft-Edge.png

**Comment by jjonescz** [comment]
Thanks for taking the time to create the sample. I can reproduce the problem now.

If you add `<EmitCompilerGeneratedFiles>True</EmitCompilerGeneratedFiles>` to a `PropertyGroup` in `WebApplication6.csproj`, you will see that the source generator produces this file:

```cs
namespace WebApplication6.Dtos
{
    public class CustomerDto
    {
        public int Id { get; set; }
    }
}
```

No documentation comment is generated. The problem is that your source generator extracts documentation comment XML from a referenced DLL:

```cs
var documentation = context.Compilation.GetTypeByMetadataName("SampleClassLib.Customer").GetDocumentationCommentXml();
```

This does not seem to be currently supported, see #51769. Simplest solution would be to move the source generator to `SampleClassLib`, so it has access to the `Customer` class directly.
