### ISSUE TITLE
VS2022 Preview + Extension issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65444]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Preview--Extension-issues/10200977)._

---
On latest VS2022 Preview environment many of the exstions are failing and getting below error:
![image.png](https://aka.ms/dc/image?name=Be8337c5cf0b4487fb0750bc91494913c638040569167430791_20221114-160836-image.png&tid=e8337c5cf0b4487fb0750bc91494913c638040569167430791)

---
#### Feedback Bot on 11/14/2022, 05:47 PM: 

(private comment, text removed)
#### Franky Fan [MSFT] on 11/14/2022, 07:11 PM: 

(private comment, text removed)
#### tjshah on 11/15/2022, 06:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Were you already investigating this one?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski No.  I was not.

**Comment by sharwell** [comment]
I moved this back to a feedback ticket since it's a duplicate.
