### ISSUE TITLE
F12 GoToDefinition, when you're on a declaration, should go to the implementation

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#6544]
Please consider making it so when you do F12 GoToDefinition, and you're on a declaration, then it does just a GoToImplementation on it. (current behavior is to recenter the current editor window).

**Comment by jasonmalinowski** [comment]
I'm very hesitant to make this change for a few reasons:

1, Go to Definition on a declaration can be used to jump between multiple partial class definitions; making this change would break that user experience. Although we should probably have a better feature for that specifically, I wouldn't want to break muscle memory until we have that.
2. The command is Go to Definition. It doesn't go to implementations. :smile: I suspect making this change is just going to result in more bugs being filed that F12 launched them somewhere very different and they don't know what their IDE just did.
3. If there aren't any implementations, then what should it do? Does it do current behavior? That seems very strange as F12 will then do one of two things based on other structure of the code you don't know about. In some sense this creates "spooky action at a distance".

@ljw1004, @Pilchie, @DustinCampbell, thoughts?

**Comment by ljw1004** [comment]
I don't think anyone has muscle memory about pressing F12 on a declaration. That's because, as you say, it's mostly useless except in the rare case of partial class definitions. You can't have muscle memory for something that only rarely works!

Just what is an "definition" of a declaration? In my mind the definition of a declaration is its implementation... I'm not sure what else it might be.

If you hit F12 and there are no implementations then the most important thing it SHOULDN'T do is to recenter your editor file on the cursor. That's just weird and jarring and unexpected. It would be better to either do nothing or to say that there are no definitions.


Generally, I don't think we should be basing this too much on idiosyncracies of how the current VS works. VS currently has far too huge a right-click menu, and far too many navigation shortcuts. We need to overhaul them all into something sleeker and more modern. I'm reckon that this change would be one part of that overhaul.

**Comment by Pilchie** [comment]
Moving to @kuhlenh to think about this experience.

**Comment by jasonmalinowski** [comment]
Oh! I never shared my highly informal and highly unscientific poll about "how do people get to another partial of the thing I'm in?" on Twitter: https://twitter.com/jasonmalinowski/status/695724769413476352

Looking through responses, it seems there is a mix between:

- Using Go to Definition
- Using Find References
- Using Navigate To on the name, especially since we prepopulate it

So yes, there's very much the muscle memory out there that made me hesitant to make the change as originally requested. That said, none of the options for what people _are_ doing is great either. :-)

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard anything at all about this from customers.  Go to impl exists and is easy to get to with both keyboard shortcut and mouse.
