### ISSUE TITLE
Question: Roslyn version in Visual Studio 17.4?

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#65455]
Hi!

I am assuming that each version of Visual Studio is using a particular version of Roslyn. Please correct me if I am wrong :-)
Anyway, I found this page: https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022 but it does not list the new 17.4. I was wondering if any of you can tell me which version is used in 17.4?

**Comment by Youssef1313** [comment]
It is the same pattern that is documented in this page. VS 17.x will use Roslyn 4.x (the same `x`).
So 17.4 uses 4.4.

**Comment by bjornhellander** [comment]
Execllent! Thank you, @Youssef1313!

**Comment by jasonmalinowski** [comment]
In general, always subtract 14 from the VS major.minor to get to Roslyn version. Note the patch level things will vary a bit, and we also won't discuss what happened when 15.5 somehow became 2.6. :smile:
