### ISSUE TITLE
Extract Method does not reproduce nullability of generic parameters of method parameters

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#65456]
**Version Used**: 
17.5.0 Preview 1.0

**Steps to Reproduce**:
```cs
public class Test
{
    public int M(Dictionary<string, string?> v)
    {
        return v.Count;
    }
}
```
Run `Extract Method` on the return statement line 

**Expected Behavior**:
The NewMethod's parameter type should be `Dictionary<string, string?>`.

**Actual Behavior**:
The NewMethod's parameter type is `Dictionary<string, string>` (note the missing `?` on the second generic parameter), which results in an immediate nullability error.

![image](https://user-images.githubusercontent.com/1947968/202155639-911ddd9c-76bc-4313-882d-5df0bd2ed5aa.png)

**Comment by kinkeadian25** [comment]
Hey, is it alright if I start working on this?

**Comment by ryzngard** [comment]
Absolutely! Let me know if you want pointers on where to get started
