### ISSUE TITLE
Altering the preprocessor symbols with Project.WithParseOptions() does not re-evaluate conditionally included documents

### ISSUE THREAD

**Issue by ceztko** [dotnet/roslyn#65461]
**Version Used**: 

Microsoft.CodeAnalysis 4.4.0

**Actual Behavior**:

Altering the preprocessor symbols of a `CodeAnalysis.Project` with `project.WithParseOptions((project.ParseOptions as CSharpParseOptions)!.WithPreprocessorSymbols(new string[] { "NEW_DEFINE" }))` does not cause the project to load conditionally included documents with a `DefineConstants.Contains()` condition such the following:

```
  <ItemGroup Condition="!$(DefineConstants.Contains('NEW_DEFINE'))">
    <None Include="ClassConditional.cs" />
    <Compile Remove="ClassConditional.cs" />
  </ItemGroup>
```

**Expected Behavior**:

There should be a supported way to alter the preprocessor symbols on a loaded project so that documents conditionally being included in the compilation will be re-evaluated. This is supported using VisualStudio ui: editing the "Conditional preprocessor symbols" in the project properties (image below) will correctly re-evaluated documents to be included/compiled in the project.

![image](https://user-images.githubusercontent.com/3037449/202230731-b9d5b286-8f11-4ae8-a66c-f28a766e72c3.png)

**Steps to Reproduce**:

1. Uncompress the attached [TestConditionalDefineConstantsInclude.zip](https://github.com/dotnet/roslyn/files/10023424/TestConditionalDefineConstantsInclude.zip)

2. Open `TestConditionalDefineConstantsInclude.sln` and execute the single project present;
3. The fixture project is loaded in the MSBuild Workspace and a "NEW_DEFINE" is inserted in the project. The test crashes verifying that the `ClassConditional.cs` is not present in the working set of project documents.

**Comment by jasonmalinowski** [comment]
This is effectively by design, since the Project snapshot you're using isn't linked back to the original MSBuild to retrigger any evaluation of the MSBuild in the way you want. What might work for what you're trying to do would be to fire up a new MSBuildWorkspace and in the Create() method you can pass a list of additional properties to pass along, where you could set DefineConstants to something else; alternately if your actual goal is to edit the project file, the appropriate MSBuild APIs might be more clear.

**Comment by jasonmalinowski** [comment]
And it might help @ceztko if you can clarify a bit more of what your scenario is here as far as giving pointers in different directions.

**Comment by ceztko** [comment]
Thank you for the prompt answer. The scenario is a code generation task, where I have to load a project and ensure all relevant  files are selected for compilation, also based on externally passed defines. The fact, as you stated, that the `CodeAnalysis.Project` is not linked to the original MSBuild project is clarifying why what I was trying couldn't work. On a quick test creating the `MSBuildWorkspace` with:

```
var workspace = MSBuildWorkspace.Create(new Dictionary<string, string>() { { "DefineConstants", "NEW_DEFINE" } });
```

allows me to load the project with the correct number of files selected for compilation and the preprocessor symbols including the external define. Thank you.
