### ISSUE TITLE
CA2252 - Static Abstract Build Error with Preview Features Enabled

### ISSUE THREAD

**Issue by dmcnaughton-nbc** [dotnet/roslyn#65460]
**Version Used**: .NET 7.0 SDK 7.0.100

**Steps to Reproduce**:

1. Create .NET 6 project with following configuration
![image](https://user-images.githubusercontent.com/37875998/202221481-fca08d16-432d-4eee-a85c-6090f7da681e.png)

2. Implement code using **static abstract** method
3. Build project
4. Receive following error: IDataTableHelper.cs(9,38,9,60): error CA2252: Using both 'static' and 'abstract' modifiers requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information.

Example source code: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AIgIYAu5+KAzJjOgMLoDey6X3AlgHaUApgCc+5ADbp+Q4QDNyAY0HoAkhWoAVcgCNxggBKDxABxEAefug0A+Tt3sck9+1gBs6HQGdKwxZXQAygCO4gAK5L4AtoIy6ACCwMABPgCuCpQpwoLA4VExIgAUds7OWHRmWKjW6MYR5NEyngA06AD0regASoIS4gCeUp4efIEhufX5wswA9uJ66TzTI9PaAFaC6cUl3JU1dQ0iAHITTVvbROU26MBU5ACUtCUAvltb0iJikrCjYfuT7Ft2uhSClIpEBt9KNMPFBsINPClBEMAO48SgAC3QGOUAXREWMABkdFsXkgnkA

![image](https://user-images.githubusercontent.com/37875998/202222294-0d692a72-09f1-4e9f-8ae4-1a905d164bab.png)

**Diagnostic Id**: N/A

**Expected Behavior**: Expected behavior is what the .NET 6.0 SDK did, which was to successfully build the project with preview features when the **PreviewFeaturesEnabled** flag was set to true

**Actual Behavior**: Received build error CA2252.

**Comment by dmcnaughton-nbc** [comment]
A temporary work-around is to create a **global.json** file and setting the sdk version to 6.X. Documented here: https://dev.to/polarbit/how-to-change-default-dotnet-sdk-version-43ph

**Comment by Youssef1313** [comment]
This is by-design. See https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md#meaning-of-property-in-multi-targeted-projects

**Comment by dmcnaughton-nbc** [comment]
@Youssef1313 Thanks for the additional info, since this does appear to be a duplicate of that ticket I'll mark this as closed.

For those who find this thread, the solution is to add `
    <GenerateRequiresPreviewFeaturesAttribute>true</GenerateRequiresPreviewFeaturesAttribute>` to your csproj file when you use `<EnablePreviewFeatures>true</EnablePreviewFeatures>` on a project targeting a **TargetFramework** that's *different* than the major SDK version you're using by default.
