### ISSUE TITLE
Implement interface members code fix doesn't add <inheritdoc/> over generated members

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#65486]
**Version Used**: 17.4

**Steps to Reproduce**:

1. Define an interface with some members
2. Define a class implementing the interface
3. Click on the "implement all interface members" code fix

**Expected Behavior**:

Roslyn should also add `/// <inheritdoc/>` over generated members.

**Actual Behavior**:

The generated members have no XML docs.

**Comment by Youssef1313** [comment]
Aren't doc comments implicitly inherited in this case?

**Comment by sharwell** [comment]
> Aren't doc comments implicitly inherited in this case?

Yes, as an IDE feature.

> But generated documentation file by the compiler isn't.

This has always been the case for implementing an interface. I'm not sure we need to include the explicit `<inheritdoc/>` when the IDE will do it for you anyway.

**Comment by Youssef1313** [comment]
> I'm not sure we need to include the explicit <inheritdoc/> when the IDE will do it for you anyway.

Do tools like docfx will implicitly inherit docs?

The compiler will also warn about missing doc comment for public member (if `GenerateDocumentationFile` is true). So for someone treating warning as errors, the codefix is effectively producing a code that doesn't compile.

**Comment by Sergio0694** [comment]
> "So for someone treating warning as errors, the codefix is effectively producing a code that doesn't compile."

This is exactly what happened for me in ComputeSharp 🙂

Also I will add, having an explicit `<inheritdoc/>` still gives you more info, as you can just glance at code and know whether a given method is just without XML docs, or whether it's inheriting those. Additionally, especially when reading code outside of an IDE, it makes it much easier to tell whether a given method is implementing an interface member or not.

**Comment by CyrusNajmabadi** [comment]
I would be ok adding this if the user has that compiler error enabled.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback, and that this has external implications.
