### ISSUE TITLE
even better operator[]

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#6551]
I can't explain it simpler than this:
```csharp
class MySortedArray
{
  public int this[int index] { get { /* ... */ } }
  public int OriginalIndicesOfElements[int index] { get { /* ... */ } }
  // this might be an overkill but worth considering
  public T As<T>[int index] { get { unsafe { int x = this[index]; return *(T*)(&x); } } }
  // ...
}
// usage:
MySortedArray a = /* ... */;
for (int i =0; i < a.Length; i++)
{
  Console.WriteLine("a[{0}]=a'[{1}]={2}   (long)a'[{1}]={3}",
      a.OriginalIndicesOfElements[i], i, a[i], a.As<long>[i]);
}
```

I'm not even gonna mention NativeBufferWrapper and Casting an array

**Comment by HaloFour** [comment]
Consuming a named indexer would produce ambiguities as it could also be the combination of a property accessor with an indexer on the result.  Non-default indexed properties are considered bad practice according to the [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229006(v=vs.110).aspx), the suggested pattern being to have a named property return an indexable object.  IIRC C# supports consuming those properties only to support COM interop.

```cs
public struct OriginalIndices {
    public int this[int index] { get; }
}

public class MySortedArray {
    public OriginalIndices OriginalIndicesOfElements { get; }
}
```

**Comment by ufcpp** [comment]
Perhaps what actually you want is achieved by ref returns? https://github.com/dotnet/roslyn/issues/118

**Comment by gafter** [comment]
You're asking for #2144 and #523.
