### ISSUE TITLE
List pattern indexable requirement binds to this[object] indexer

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/roslyn#65521]
**Version Used**: SharpLab main (18 Nov 2022)

**Steps to Reproduce**:

```c#
using X = A;
// -or-
//using X = System.Collections.Generic.Dictionary<int, int>;

_ = new X() is [>0];

class A
{
    public int this[int i] => 1;
    public int this[object i] => throw null!;
    public int Count => 1;
}
```
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4GIaoDZ4TB4CmABACZQDORpAsAFAACADGQBpkC8ZAggG4mAemFkAtAHtk4kcLaceZZgEYALADoAIlADGCKJJgRkATwA8sBHDJWAfEMZMA+kpgkA7pwAUASlvUZADadqwAuo5MzABM/EwA3kxkycoAzLYwCGQIABY0QVa2YTx2ZCqOKWkZWbn5ksAAViT6RSXZOciSXrgEAIQVKczphQDCkuhZ3KXlTAC+QA==

**Diagnostic Id**:

for dict:
`error CS1503: Argument 1: cannot convert from 'System.Index' to 'int'`
for A:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at A.get_Item(Object i)  // !!!!!
   at Program.<Main>$(String[] args)
```

**Actual Behavior**:
[Compiler preferred](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/list-patterns#pattern-compatibility) `Index` overload is matched by `this[object i]`, and sometimes tries to (mis)use `int` anyway (I assume caused by `IDictionary.this[object key]` implemented explicitly).

```c#
private static void <Main>$(string[] args)
{
    A a = new A();
    bool flag;
    int num;
    if (a != null && a.Count == 1)
    {
        flag = a[new Index(0)] > 0;
    }
    else
        num = 0; // dead store, is it for stack balancing?
}
```

**Expected Behavior**:

match `Index` exactly (or implicitly convertible from `Index`).

**Comment by jcouv** [comment]
FYI @alrz

**Comment by alrz** [comment]
> match Index exactly (or implicitly convertible from Index).

- `Index` is implicitly convertible to `object`, therefore `this[object]` is preferred; it's the winning candidate for `this[Index]`.
- `Dictionary<int, int>` won't work because no type substitution is considered when looking for `this[int]`

The behavior is consistent with indexer access in both cases: `new X()[^1]`.

**Comment by OwnageIsMagic** [comment]
I meant by means of user defined conversion operator, not boxing. Boxing `Index` is almost always is the wrong thing to do, and I would be glad even if compiler would consider only exact `this[Index]`.
i.e. pattern matching `OrderedDictionary` is always silently wrong.
Didn't get point about _type substitution_.

**Comment by alrz** [comment]
If you don't want the compiler to call `this[object]`, you could add `this[Index]` and redirect it to `this[int]` overload.
This behavior is inherited from range indexers from C# 8.0, so changing that is simply not an option.

>Didn't get point about type substitution.

The indexer on the dictionary is defined as `this[TKey]`, not `this[int]`. The compiler won't pick it up even if `TKey` is `int`.

**Comment by OwnageIsMagic** [comment]
I hope we both agree that it's not reasonable behavior, but it looks like `won't fix` (Maybe resolving in through warning wave is feasible?).

_Just another bittersweet feature (like slicing not returning Span by default)._

**Comment by jcouv** [comment]
Thanks @alrz for the analysis. This looks expected based on overload resolution rules. This is the same behavior resulting from indexing: `new X()[^1]` ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4GIaoDZ4TB4CmABACZQDORpAsAFAACADGQBpkC8ZAggG4mAemFkAtAHtk4kcLaceZZgEYALADoAIlADGCKJJgRkATwA8sBHDJWAfEMZMA+kpgkA7pwAUASgDaAHoqALqOTMwATPxMAN5MZInKAMy2MAhkCAAWNP5WtiE8dmQqjkkpaRnZuZLAAFYk+gVFmVnIkl64BACEZUnMqfkAwpLoGdzFpUwAvkA=))
Closing as by-design
