### ISSUE TITLE
[Proposal] Wide Char Literal

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6552]
Wide Char LIteral
----------------------

**Syntax**
* `"x"c` denotes the standard char literal
* `"x"w` denotes the wide char literal
```vb.net
Dim ch_0 As Char = "x"c
Dim ch_1 As Char = "x"w
Dim ok = ch_0 <> ch_1 '  ok == True
```

**Example**
From [CharacterInfo.vb](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/CharacterInfo.vb)
```vb.net
Friend Const FULLWIDTH_LATIN_CAPITAL_LETTER_C As Char = ChrW(s_fullwidth + AscW("C"c))   REM Ｃ
Friend Const FULLWIDTH_LATIN_SMALL_LETTER_C   As Char = ChrW(s_fullwidth + AscW("c"c))   REM ｃ
Private Const s_fullwidth = CInt(&HFF00L - &H0020L) '&HFEE0L

Friend Shared Function IsLetterC(ch As Char) As Boolean
  Return (ch = "c"c) Or (ch = "C"c) Or
         (ch = FULLWIDTH_LATIN_CAPITAL_LETTER_C) Or (ch = FULLWIDTH_LATIN_SMALL_LETTER_C)
End Function
```
to
```vb.net
Friend Shared Function IsLetterC(ch As Char) As Boolean
  Return ( ch = "c"c) Or (ch = "C"c) Or (ch = "c"w) Or (ch = "C"w)
End Function
```

**Implementation**

By adding an additional `ElseIf` clause to the ScanStringLiteral function in [Scanner.vb](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L2310)
```vb.net
            ' // Check for a Char literal, which can be of the form:
            ' // """"c or "<anycharacter-except-">"c
            Dim cx As Char
            If Peep(3, cx) AndAlso IsDoubleQuote(Peek(2)) Then
                ch = Peek(1)
                If IsDoubleQuote(ch) Then
                    If IsDoubleQuote(cx) AndAlso Peep(4, ch) AndAlso IsLetterC(ch) Then

                        ' // Double-quote Char literal: """"c
                        Return MakeCharacterLiteralToken(precedingTrivia, """"c, 5)
                    End If

                ElseIf IsLetterC(cx) Then
                    ' // Char literal.  "x"c
                    Return MakeCharacterLiteralToken(precedingTrivia, ch, 4)
                ElseIf IsLetterW(cx) Then
                    ' // Char(Wide) literal "x"w
                    Return MakeWideCharacterLiteralToken(precedingTrivia, ch, 4)
                End If
            End If
```
**Note:-** *Minor difference in implementation of this method, is due to be basing it off one that utilised Peep functionality (#6305)*

**Comment by vladd** [comment]
Is the standard char literal not a wide one?

**Comment by orthoxerox** [comment]
It can't be named `Char` because `Char` is UTF-16. I've implemented clones of `Char` and `String` that are UTF-32, but have never felt the need for emoji or mathematical script character literals, especially since modern emoji are no longer single UTF-32 codepoints.

**Comment by mburbea** [comment]
Out of curiosity which emoji is above the utf-32 code point?

**Comment by orthoxerox** [comment]
For example, 🇷🇺 is U+1F1F7 U+1F1FA, just like all other flags. Or people with skin color modfiers, like U+1F46D U+1F3FF (two women with really dark skin holding hands).

As an ultimate example, U+1F469 U+1F3FB U+200D U+2764 U+200D U+1F468 U+1F3FF should be displayed as a single "very pale woman and a very dark-skinned man love each other" glyph.

**Comment by svick** [comment]
If I understand @AdamSpeight2008's proposal correctly, it's not about UTF-32 characters or anything like that. It's about [fullwidth characters](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms), used in Chinese, Japanese and Korean. (Which are all a single UTF-16 code unit.)

@AdamSpeight2008 Do you think this would be widely useful outside of the VB compiler? If it's all about witdth-invariant character comparisons, maybe a library solution would make more sense?

**Comment by AdamSpeight2008** [comment]
@svick The compiler would be the initial use case. It would be helpful if say i Chinese, Japanese and Korean were my native language and programming.Without using the "kludgey" method currently being used. Modifying `Char` would likely break a lot of code.

**Comment by svick** [comment]
@AdamSpeight2008 Correct me if I'm wrong, but if one of those languages is my native language, then I'm also using an [IME](https://en.wikipedia.org/wiki/Input_method), which also supports typing fullwidth characters, no?

So, I could write the above code directly as (where the third and fourth characters are fullwidth):

```vb
Friend Shared Function IsLetterC(ch As Char) As Boolean
  Return ( ch = "c"c) Or (ch = "C"c) Or (ch = "ｃ"c) Or (ch = "Ｃ"c)
End Function
```

> Modifying `Char` would likely break a lot of code.

Was that in response to my proposal of a library solution? What I meant was adding support for something similar to [`StringComparison`](https://msdn.microsoft.com/en-us/library/c64xh8f9), e.g.:

```vb
Friend Shared Function IsLetterC(ch As Char) As Boolean
  Return ch.Equals("c"c, CharComparison.InvariantCultureIgnoreCaseIgnoreWidth)
End Function
```

Adding this shouldn't break anything.

**Comment by whoisj** [comment]
... wait what? CLR `char` type is 16-bit (nearly) UTF-16 compliant. It basically is `wchar_t`, in fact `char` is `wchar_t`.

I'm very confused to what this offers.

Maybe you're looking for an ascii character type, but then why?

**Comment by Joe4evr** [comment]
@whoisj
> I'm very confused to what this offers.

It's not about the underlying unmanaged type, he wants to be able to use the letters ＴＨＡＴ ＬＯＯＫ ＬＩＫＥ ＴＨＩＳ. As stated above, these are often used in Chinese, Japanese, and Korean character sets in place of the normal ASCII Latin character set.

Either way, I don't see a lot of value. I actually saw a [video on channel9](https://channel9.msdn.com/Events/TechDays-Sweden/TechDays-Sweden-2015/The-Code-Behind-The-Vulnerability) the other day, that shows how these could be used to perform XSS if you're not careful (skip to 34:33).

And even if there was a lot of value, what's gonna be the equivalent C# syntax?
```C#
char c = 'a';
char w = 'a'w; //I mean, it *could* work
```

**Comment by ufcpp** [comment]
I don't want full-width char literals by any means. The full-width alphanumeric characters are horrible damned negative legacy. I and probably most of Japanese developers hate it.

**Comment by Joe4evr** [comment]
There we go, input from an actual Japanese developer. Time to move on. :stuck_out_tongue_winking_eye:

**Comment by AdamSpeight2008** [comment]
If it possible to express the fullwidth character as a literal char. Why is not being used?

**Comment by ufcpp** [comment]
I guess it's dark side of history, a legacy code from ancient time when there was neither .NET nor Unicode.

**Comment by matarillo** [comment]
+1s for both @svick and @ufcpp. Those who live in DBCS world use IMEs to write wide characters directly into codes, otherwise people without IMEs can make use of unicode character escape sequences ("\uXXXX"). Even if Visual Basic compilers make some special consideration to wide characters, it must be a "technical debt" from ancient VB6/VBA/VBScript era, and we can easily dispose it now.

**Comment by kekyo** [comment]
I think so, too. It's dirty and minor usage.

**Comment by AdamSpeight2008** [comment]
@kekyo  
It usage is likely minor but the VB workaround has a runtime cost, that could be removed.

-----------------
So consensuses are:-
* no for the literal.
* use of full-width characters is backward-compatibility with the VB6  days,
* The `char` literal to no represent them eg `(ch = "ｃ"c) Or (ch = "Ｃ"c)`  
*proviso: possible comment to indicate full-width chars.*

**Comment by ufcpp** [comment]
@AdamSpeight2008 

> The char literal to no represent them eg `(ch = "ｃ"c) Or (ch = "Ｃ"c)`

No. you can use full-width characters in VB Char literals. VB compiler can compile the following code in UTF8:

```vb
    Friend Const FULLWIDTH_LATIN_CAPITAL_LETTER_A As Char = "Ａ"c
```

Or, as @matarillo mentioned above, you can use the unicode character escape sequences ("\uXXXX").
This has no cost at runtime. [CharacterInfo.vb](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/CharacterInfo.vb) might have to be modified to use such literals (`"ａ"c`).

**Comment by AdamSpeight2008** [comment]
**@ufcpp**
VB.net doesn't have unicode character escape sequences. 
I'm looking into modifying `CharacterInfo.vb`

**Comment by AdamSpeight2008** [comment]
One of them is causing the testing to Assert, think it it could be one of the double quotes.
The `Chrw` representation works, just the the char literal version doesn't. Suspect that it require the `"` to be used, instead of double quoting to indicate you actual what the double quote character.

**Comment by gafter** [comment]
Closing, as we do not plan to add support for wide characters to the VB language.
