### ISSUE TITLE
Autocompletion offers type parameters that already have a `where` constraint

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#65528]
**Version Used**: VS 2022 17.5 Preview 1

**Steps to Reproduce**:

Invoke autocompletion at the marked locations.

```csharp
class C1<T1, T2> where T1 : class where $$ {}
class C2<T1> where T1 : class where $$ {}
```

**Expected Behavior**:
1. The autocompletion inserts `T2` as that's the only type parameter without an existing type constraint.
2. Nothing happens because there are no autocompletion items.

**Actual Behavior**:
1. The autocompletion list opens, offering both `T1` and `T2`. ![image](https://user-images.githubusercontent.com/823398/202918860-aa3939c4-7f26-4411-a88f-2f833c6100e0.png)
2. `T1` is automatically inserted.

In both cases inserting `T1` is not useful as there cannot be multiple type parameter constraints clauses for any type parameter (error CS0409).

**Comment by CyrusNajmabadi** [comment]
This is less a bug and more a question of of it's better to help speed things up, or require the user to have to write out everything manually. The user may just be in the middle of hacking up a whole lot of their code. Generally speaking in opposed to filtering down in these cases where the list is small. It can be useful in some cases (for example with large override lists or property lists) to know what's left. However, as type parameter lists are 99% less than 4 elements, is fine and reasonable to show them all.

**Comment by Youssef1313** [comment]
I agree with @CyrusNajmabadi

I think, if anything should be done here, the improvement would be to preselect the first type parameter that doesn't yet have a constraint. So in repro in the original issue, both T1 and T2 will exist, but T2 is the one that is preselected. Though this might be acceptable only if the fix is going to be too small?

What do you think @CyrusNajmabadi ?

**Comment by CyrusNajmabadi** [comment]
I think it's be ok with it. But it's also so minor that I don't care about it :-)

**Comment by Youssef1313** [comment]
> it's also so minor

Yeah I agree, that's why I mentioned "this might be acceptable only if the fix is going to be too small"

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback.
