### ISSUE TITLE
Compiler treats `string?` as `string`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65520]
**Version Used**: 
17.5 Preview 1

**Steps to Reproduce**:
```cs
List<string?> GetListOfThings()
{
    string? str = "";
    return CreateList(str);
}

List<T> CreateList<T>(T value) where T : class? => new() { value };
```

**Expected Behavior**:
No nullability warnings because type of `str` is nullable string `string?`, so the inferred generic type should be `string?`

**Actual Behavior**:
![devenv_qx3RzbBI7C](https://user-images.githubusercontent.com/70431552/202867723-38a25111-0def-4338-bb99-14c88bc5f91b.png)

**Additional context:**
1. I expect to have no nullability warning even when I use `var` instead of `string?` as a type of `str` because `var` is implicitly `string?` by default
2. The code is magically fixed when I add explicit cast of `""` to `string?`:
```cs
List<string?> GetListOfThings()
{
    string? str = (string?)"";
    return CreateList(str);
}

List<T> CreateList<T>(T value) where T : class? => new() { value };
```

**Comment by jcouv** [comment]
This behavior is expected. In generic type inference, the flow-state of expressions matters, not their declared types.
See https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md#generic-type-inference
Closing as by-design
