### ISSUE TITLE
Embedded languages - support customizing tooltip

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn#65531]
Roslyn supports colorizing embedded languages:

![image](https://user-images.githubusercontent.com/303201/202943815-ab245869-c36d-4e53-b52f-97d6b51e682e.png)

However, the tooltip, when over the embedded language string, is always `class System.String`

For strings with an embedded language, it would be helpful if the tooltip could be changed depending on the part of the string the mouse pointer is over. A tooltip lets someone unfamiliar with the syntax know what precisely that part of the string does.

For example, regex101.com shows a tooltip that gives more information about what the hovered set of characters does:

![image](https://user-images.githubusercontent.com/303201/202944216-036be872-92fe-47fb-9ae8-4295ffc5bb0b.png)

A date format string, e.g. `DateTime.Now.ToString("g")`, could provide information in the tooltip for `g` like it does in the completion tooltip description:

![image](https://user-images.githubusercontent.com/303201/202944770-ff74a3e1-857d-411c-a1fa-296e84a2a56f.png)

Currently, all the helpful information the date format string completion provider provides is hidden away unless you're writing a new string. A tooltip makes it available to someone reading and learning code.

**Comment by JamesNK** [comment]
cc @CyrusNajmabadi

**Comment by JamesNK** [comment]
As an addition to the ASP.NET Core tooling experience, this is a nice to have feature.

**Comment by CyrusNajmabadi** [comment]
There's been no future communication on this.  Closing out as not planned.  IF this is needed for an ASP experience, we should drive this with an actual deliverable on the ASP side with a date/sprint attached.  We can then do teh work here linked with that item as the driver.
