### ISSUE TITLE
Regular and generic methods with the same name in top-level statements cause compiler errors CS0308, CS0128

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/roslyn#65534]
**Version Used**: 
Microsoft Visual Studio Community 2022
Version 17.4.1
VisualStudio.17.Release/17.4.1+33110.190
C# Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c

**Steps to Reproduce**:
Write regular and generic methods with the same name in top-level statements.
```cs
static double Sum(IEnumerable<int> values);
static TResult Sum<T, TResult>(IEnumerable<T> values)
```
See full code in [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AcgK4C2ApgE4CWAxgM75LIBuAhregHZUARnWboAvP2oB3dPT4AXANoBddAG90cADToYOgMw7sOgKw6Avm0490zKnHHoAylQAUAysNrMAlG268dpQwji6UADxy8jrAAPbkggA21AB87kIifsgEcACcrgAkAEQlyOjlzvaOakFw5mUVYSESNVQw9UgV6CVFWewocABs6HEJyZWUrlj6kQop6NyJ5NS+yGoN5YmxfADm6LQr5InyjqhWnRUAZrEHXIwAFuiuAQtcS9SyfK/vqxfl638uvtDsd0GAJItlmwuh0NpgAOzAuzHNiwgbDAAqACUQScwuEMTpsbi0tMCfNISsfHCpPc6B8MegQOgAJIUTx0ABCXGY1HJNLpB3QxORJ2ZbIytG5vIJONFKTWcJFRxOB1FjmVx2IAC06LFzl1rrcHk8XpTPt9lr8ugCgRUHtRGABrajAdRIlVgiSa+TEADCt3k1D9dOdrueb2WfnQHRh2UBUERapVqOQQA=)

**Diagnostic Id**:
```
error CS0308: The non-generic method 'Sum(IEnumerable<int>)' cannot be used with type arguments
error CS0128: A local variable or function named 'Sum' is already defined in this scope
```

**Expected Behavior**:
Successful code compilation.

**Workaround**:
Rename the regular or generic method to different names.
```cs
static double Sum1(IEnumerable<int> values);
static TResult Sum2<T, TResult>(IEnumerable<T> values)
```

**Comment by svick** [comment]
This code correctly doesn't compile, because those aren't *methods*, they're *local functions*. And you can't overload local functions.

**Comment by AlexRadch** [comment]
> This code correctly doesn't compile, because those aren't _methods_, they're _local functions_. And you can't overload local functions.

The compiler generates two static (not local) methods 
`internal static double <<Main>$>g__Sum1|0_0(IEnumerable<int> values)` and 
`internal static TResult <<Main>$>g__Sum2|0_1<T, TResult>(IEnumerable<T> values)`.

See generated code in [sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AcgK4C2ApgE4CWAxgM75LIBuAhregHZUARnWboAvP2oB3dPT4AXANoBddAG90cADToYOgMw7sOgKw6Avm0490zKnHHoAyvYAUAysNrMAlG268dpQwji7BADxy8jrAAPbkggA21AB87kIifsgEcACcrgAkAEQlyOjlzvaOakFw5mUVYSESNVQw9UgV6CVFWewocABs6HEJyZWUcK5Y+pEKKejcieTUvshqDeWJsXwA5ui0q+SJ8o6oVp0VAGaxh1yMABborgGLXMvUsnxvH2uX5Rt/l0DkcTugwBIlis2F0OptMAB2EF2E5sOEDYYAFQASqDTk1wpidDi8WkZoSFlDVj54VIHnRPpj0CB0ABJCieOgAIS4zGoFNp9MO6BJKNOLPZGVoPL5hNxYpS63houOp0OYscKpOxAAWnRYhcujc7o9nq8qV8fis/l1AcCKo9qIwANbUYDqZGq8ESLXyYgAYTu8mo/vpLrdL3eKz86A6sOyQKgSPVqrRyCAA===) at the right panel.

**Comment by CyrusNajmabadi** [comment]
That's the emit strategy. From the perspective of the language though, they are local functions, and thus do not support overloading.

**Comment by CyrusNajmabadi** [comment]
Closing this out as the compiler is following the spec properly here. If you'd like to have this be allowed, please open a discussion at dotnet/csharplang. Thanks!

**Comment by AlexRadch** [comment]
> Closing this out as the compiler is following the spec properly here. If you'd like to have this be allowed, please open a discussion at dotnet/csharplang. Thanks!

Wow, [I get it now](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/top-level-statements#semantics), thanks!
