### ISSUE TITLE
InsertMembers with method declarations to an interface declaration causes modifiers to be reset

### ISSUE THREAD

**Issue by hugener** [dotnet/roslyn#65545]
**Version Used**:  4.4.0

**Steps to Reproduce**:

1. In an analyzer codefix, I use the SyntaxFactory.MethodDeclaration to create a method declaration with public, static modifiers and an implementation to leverage default interface methods. (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods)
2. Insert methods into an interface declaration with SyntaxGenerator.InsertMembers
3. The methods are added, but the public and static modifiers are stripped from the SyntaxTree giving a different meaning to the generated code.

Sorry I did create a minimal solution, but I found the line that I suspect causes modifiers to be stripped in case of adding to an interface declaration:
https://github.com/dotnet/roslyn/blob/b1b8636a866cb01c419b25caec47db9788a7f4db/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L775

I can understand the behavior, in the context of C# not supporting this prior to version 8, but shouldn't this be a supported scenario now? 

Does anyone see a workaround?

**Expected Behavior**:

Code to be generated as:
```
public interface IOption<T>
{
    public static IOption<T> Some(T value) => new Some<T>(value);
}
```

**Actual Behavior**:
```
public interface IOption<T>
{
    IOption<T> Some(T value) => new Some<T>(value);
}
```

**Comment by jaredpar** [comment]
> I can understand the behavior, in the context of C# not supporting this prior to version 8, but shouldn't this be a supported scenario now?

The other consideration is whether or not changing the behavior will impact existing use cases. Have to consider existing customers may be depending on this behavior. Not sure that we can safely change this. 

@333fred to confirm

**Comment by 333fred** [comment]
This is an IDE api. Moving over there for triage.

**Comment by CyrusNajmabadi** [comment]
Closing as we would need an api design brought forward here.  The existing behavior cannot change, as many features depend on the apis to remove bodies when generating into interfaces.  So we'd need some way to indicate to the api that bodies should be kept/generated even in interfaces now.
