### ISSUE TITLE
Compilator can't find the matching overload for operator+ when implementing nullability to project

### ISSUE THREAD

**Issue by spiritomtom** [dotnet/roslyn#65546]
### Describe the bug
I have an overload of operator+, which takes two arguments: (CustomObject x, Guid[]?), but the compilator doesn't call the overload when used. And throws this error message: "Error	CS8620	Argument of type 'Guid[]' cannot be used for parameter 'y' of type 'Guid' in 'CustomObject CustomObject.operator +(CustomObject x, Guid[]? y)' due to differences in the nullability of reference types." even though all types should be matching.

### Further technical details
- Include the output of `dotnet --info`
- VS 2022

**Comment by svick** [comment]
[Here is the repro code in a more convenient form:](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDIG4EMBOACALgY2wF5sA7AUwHdsAVcgZ1wGEAbde+gCgEoBuNLNgDmAVwCWwAIKZM6AJ7FsnAOLjgAbQC6Afm4VqqieoDMm/iiQFFVsMLXTZc3tgD0L7AHsA1shslREg7yzm7Y5DIeOEwAygAcAGwwAAzIyLC0DMxsHMgA3sjYhdhQxsVw8RmMrOz0ngAO4ei4kbacdFXZtQAeADTYhho62HLcxAB8BUVT+pVZNTzmAL6pSEA==)

```c#
using System;

var tc = new TestClass();
var guidArray = (Guid[]?)new Guid[3];

tc = tc + guidArray; // ok
tc += guidArray; // warning CS8620 (or error with <WarningsAsErrors>Nullable</WarningsAsErrors>

class TestClass
{
    public static TestClass operator+ (TestClass x, Guid[]? y) =>
        new TestClass();
}
```
