### ISSUE TITLE
Types are not suggested after `required` modifier

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#65556]
**Version Used**: 4.4.0-3.22518.13 (7856a68c) on VS 17.4.0 x64 with .NET 7.0.100 x64 SDK

**Steps to Reproduce**:

1. Create a class
2. Type `required`
3. Type any type name such as `str`
4. <kbd>Ctrl</kbd> + <kbd>.</kbd> to pull up suggestions

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

```cs
class C
{
    public required /* type name here */
}
```

**Expected Behavior**: `string` is suggested among other types

**Actual Behavior**: no suggestions are made

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/64593 (in 17.5 Preview 1)
