### ISSUE TITLE
Analyzers created with Microsoft.CodeAnalysis 4.4.0 cannot be used with .net 6

### ISSUE THREAD

**Issue by rominator1983** [dotnet/roslyn#65562]
**Version Used**: 
dotnet 6.0.403
Microsoft.CodeAnalysis 4.4.0

**Steps to Reproduce**:

1. Create a new code analyzer as a package based on Microsoft.CodeAnalysis 4.4.0
2. Use that new code analyzer inside a .net 6 project
3. compile the .net 6 project with dotnet build

**Diagnostic Id**: CS9057

**Expected Behavior**:
Project builds

**Actual Behavior**:
Compilation gives the following error:
```
CSC : error CS9057: The analyzer assembly 'XXXXX.dll' references version '4.4.0.0' of the compiler, which is newer than the curren
tly running version '4.3.0.0'. [XXXXXX.csproj]
```

Due to the analyzer depending on Microsoft.CodeAnalysis 4.4.0 it seems like the c# compiler 4.4.0 must be present.

Using some commands (thanks to https://github.com/dotnet/runtime/discussions/70715) you can see the following:
`dotnet "C:\Program Files\dotnet\sdk\6.0.403\Roslyn\bincore\csc.dll"` => SDK 6.0.403 includes csc 4.3.1-3.22505.12 (95493021)
`dotnet "C:\Program Files\dotnet\sdk\7.0.100\Roslyn\bincore\csc.dll"` => SDK 7.0.100 includes csc 4.4.0-4.22520.11 (9e075f03)
`C:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin\Roslyn\csc.exe` => The newest Visual Studio 17.4 uses csc 4.4.0-6.22559.4 (d7e8a398). This is actually irrelevant for this issue.

So the question is: Will csc 4.4.0 and Microsoft.CodeAnalysis be backported to be included in the .net 6.0 SDK?
Or how is one supposed to deal with upgrades of Microsoft.CodeAnalysis (including possible security fixes) in his/her code analyzers?

It is not possible for us to switch to dotnet 7 since it is not an LTS. So does one have to stay at Microsoft.CodeAnalysis 4.3.1 until dotnet 8 is released?

**Comment by arkalyanms** [comment]
The seems to have hit an unsupported compiler analyzer part of the matrix. But will let Jared pass judgement.
