### ISSUE TITLE
VS 2015 RTM - csproj xml node Project\ProjectExtensions\VisualStudio\UserProperties attribute order differs based on machine that saves file

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#6556]
When 2 or more people make changes to a project that has multiple properties stored on the UserProperties tag, the order of the properties on the attribute appears to depend on order that code runs to set the attributes.

I have several csproj files with

    <ProjectExtensions>
      <VisualStudio>
        <UserProperties 
          PingPoet_SlashDocs_DocCommentIncludeFileBasePath="...removed..." 
          PingPoet_SlashDocs_SlashDocPathReplacePattern="...removed..." 
          PingPoet_SlashDocs_SlashDocPathMatchPattern="^...removed...$" />
      </VisualStudio>
    </ProjectExtensions>

(the node is on one line).

With the project file in source control and multiple developers, this line changes every time a dev makes any change to the file. This results in merge conflicts very often as in this case there are 6 possible ways to have that line.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#123
