### ISSUE TITLE
Exception thrown on solution load in VSMac

### ISSUE THREAD

**Issue by Therzok** [dotnet/roslyn#65573]
**Version Used**: 
4.5.0-dev (tip of https://github.com/dotnet/roslyn/pull/65568)

**Steps to Reproduce**:

1. Open a maui project in VSMac
2. Look in the log file for exceptions

**Expected Behavior**:

No exception (@CyrusNajmabadi mentioned this might cause some events to be discarded).

**Actual Behavior**:

https://gist.github.com/Therzok/ee0716447f7dbe8f40f0767bf1eb029a

**More information**:

What is happening here, is likely a side-effect of VSMac having multiple `Host` kind workspaces. VSMac supports multiple solutions opened at the same time, so we create one workspace per solution opened.

There is also an empty workspace we create, which I'm looking into how to remove. But the problem might still persist.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is for vs4mac.
