### ISSUE TITLE
`dotnet_style_prefer_is_null_check_over_reference_equality_method` not respected by other features

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65577]
![image](https://user-images.githubusercontent.com/31348972/203497868-d6896f4e-75af-4055-9f69-b64f47488992.png)

Code generation features should probably respect this code-style option.

Tagging @sharwell as he mentioned this for a similar option in https://github.com/dotnet/docs/issues/22450#issuecomment-765558476

also @mavasani @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This is correct behavior.  all 'false' means here is that we won't try to move existing code over to the new pattern.  It doesn't mean that we will actually emit with ReferenceEquality.  That's how nearly all our 'style' features work.  'false' is simply the disabling option, where as 'true' means 'migrate me to the more idiomatic form'.
