### ISSUE TITLE
BadImageFormatException with virtual static interface properties

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#65584]
**Version Used**: 4.5.0-ci (https://github.com/dotnet/roslyn/commit/ed12a880a3454a00e58bc829cefb80bd94adfb3d)

**Steps to Reproduce**:

Paste and run this code ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWAChiAVAUwGcEAeASQCEJkA+ACgEoBuMq2pgF7tuxYljwA2AARYALFIrUapYcSnqpAdwAW5ZOQVSQUugDEA9ueIBvNRvEBONqQB0AOVRhgekUQC+okSwCHoAZhAAxgZmljZ26uLSEMDUyJEIUsFSHl56UtZSAObkCFxSAf6BwWGR0UzIRiYWVkS2RBoykpkwGTHm7p7eDQC8LFJ4AAw8lSREuFKCjYzMce32XVk5Q1KjUjhTxH5AA)):

```csharp
using System;

Test<IBar>();
Test<Baz>();

static void Test<T>()
    where T : IFoo
{
    Console.WriteLine(T.Number);
}

interface IFoo
{
    static abstract int Number { get; }
}

interface IBar : IFoo
{
    static int IFoo.Number => 10;
}

class Baz : IBar
{
    static int Number => 20;
}
```

**Expected Behavior**:

Should run fine maybe? Or if this syntax isn't valid, there should be an appropriate error.

**Actual Behavior**:

```
System.BadImageFormatException: Bad IL format.
   at Program.<<Main>$>g__Test|0_0[T]()
   at Program.<Main>$(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

This happens with both `Test<IBar>()` and `Test<Baz>()`.

**Comment by GerardSmit** [comment]
FYI, this seems to be running fine in the CoreCLR runtime (.NET 7.0):

```
$ dotnet run
10
10

$ dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219
 ```

**Comment by GerardSmit** [comment]
Just saw that the result is 10, 10 instead of 10, 20. This is because the property is not public in the class:

```csharp
class Baz : IBar
{
    static int Number => 20;
}
```

Changing it to a public property:

```csharp
class Baz : IBar
{
    public static int Number => 20;
}
```

Gives the expected result:

```
$ dotnet run
10
20
```

**Comment by 333fred** [comment]
Sharplab.io is not on 7 yet, there isn't a bug here.

**Comment by 333fred** [comment]
Ok, I was wrong, sharplab is on 7 now.

**Comment by 333fred** [comment]
@ashmind, is the instrumentation doing something weird here?

**Comment by ashmind** [comment]
@333fred Yep looks like a SharpLab rewriting issue, [if rewriting is disabled this does not fail](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAgGUALCZABwBkJgA6AJXQSjAFMBuYsQDaEAM5jeYYABsAniHIA5APYBJRu14B3ZFG4wA5gF0hRACq8xCADxqAQnQB8ACgCUgi1duOAXq48zLDwANnIsABZyS2sbcwDiciTybWpeZF5o8kU1ADEVFWIAb0Tk4IBOF3NWJVRpdMCiAF8zWAR0gDMIAGNMvILi0qTgsJZrZB6EcjblOuB08iLyQ14EfnIW5taYduQu3vIHOmzD/MKiEqJk8NDpndOCmrmFgF4ncjxST03iXHI/E5HZCDK5lW4zWr1ZDkN7kHBfYhNIA=).

**Comment by 333fred** [comment]
Thanks @ashmind!
