### ISSUE TITLE
CA1822 on implicit implementation of a static interface member

### ISSUE THREAD

**Issue by GerardSmit** [dotnet/roslyn#65585]
**Version Used**: 

```
.NET SDK:
 Version:   8.0.100-alpha.1.22567.28
 Commit:    f707476564
```
(while testing; this also applies to .NET 7.0.100)

**Steps to Reproduce**:

1. Create an interface that contains an `static abstract` property.
2. Create an interface that implements the interface and override the property with an implicit implementation.
3. In Rider EAP you will now get a `CA1822` error: "Member '...' does not access instance data and can be marked as static"
4. In Visual Studio 16.5 you will get an error "The modifier 'static' is not valid for explicit interface implementation" (this seems to be a bug).

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible:

```cs
public interface IBaseInterface
{
    static abstract int Property { get; }
}

public interface IInterface : IBaseInterface
{
    static int IBaseInterface.Property => 10;
}
```

[Sharplab.io link](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEDMACWAXAUwCcAzCAYwOwEkAFIgezyYE8AHKgbwF8BYAKCy4YhUhSp1GzPOwIAeACoA+bCBr0mrDth4ChEYAGc8RCnmzoATNg3TZilWsmaZHBzr789OfMTKV1KS0CADEzBiIWAU4BbDiLAEYANmwDY1Nyc2c7bVtgnWwAcwI8AG5sT09vYVF/CTzXUPDI9ycG2TDMiKj+eOwAdwALYioFVQtLOECXDuaWB2jY+JgCfsSUtJMzGyDG93btTiKS8qre+PRk6Zz63dmuyIA6A6oAXhUFZ7uOUoFuIA===)

**Diagnostic Id**: CA1822 

**Expected Behavior**: No warning, since the member is already static.

**Actual Behavior**: Warning that the member could be static.

**Screenshot:**
_Rider:_
![image](https://user-images.githubusercontent.com/2109929/203542848-ea15c150-6baf-4035-92e9-ab2c662769b9.png)

_Visual Studio_
![image](https://user-images.githubusercontent.com/2109929/203543791-9363f1cd-c566-4f45-83b2-fa54c6aa6af0.png)

**Runnable example:**
```csharp
Print<Test>();

void Print<T>()
    where T : IBaseInterface
{
    Console.WriteLine(T.Property);
}

public interface IBaseInterface
{
    static abstract int Property { get; }
}

public interface IInterface : IBaseInterface
{
    static int IBaseInterface.Property => 10;
}

public class Test : IInterface
{
}
```

**Comment by Youssef1313** [comment]
> The modifier 'static' is not valid for explicit interface implementation

Is this error coming from ReSharper?

---

I'm not able to reproduce the CA1822, but this belongs to dotnet/roslyn-analyzers anyway.

**Comment by GerardSmit** [comment]
> Is this error coming from ReSharper?

This seems to be the case. I really need to remember to disable ReSharper in these cases 🥲

Without ReSharper I'm not seeing CA1822 in Visual Studio. So this seems to be a Rider specific bug.

> this belongs to dotnet/roslyn-analyzers anyway

Because it's Rider-only I'll report this to JetBrains. Sorry for the trouble.
