### ISSUE TITLE
TextDocument.Folders is always empty for additional files

### ISSUE THREAD

**Issue by etvorun** [dotnet/roslyn#65589]
**Version Used**:  4.300.22.22804

**Steps to Reproduce**:
1. Unzip attached file.
2. Open MauiApp4\MauiApp4.sln
3. Use Solution Explorer to open (and debug Roslyn internals) MyControl.xaml, LinkedControl.xaml and dark.xaml from SharedMaui project.
[MauiRepro.zip](https://github.com/dotnet/roslyn/files/10078571/MauiRepro.zip)

**Expected Behavior**: [TextDocument.Folders](https://github.com/dotnet/roslyn/blob/dde846ec7ffbaff1dcfbfff264358a87ab55531e/src/Workspaces/Core/Portable/Workspace/Solution/TextDocument.cs#L54) contains folders matching folder structure in solution explorer

**Actual Behavior**: TextDocument.Folders always contains 0 items

**Note**: *.cs files have valid Folders for plain and linked items; empty for *.cs files from SharedMaui project.

**Comment by etvorun** [comment]
This is related to [#44131](https://github.com/dotnet/roslyn/issues/44131). XAML intellisense needs to know project relative paths. For example, in order to display completion for `<Button Background='...'` it needs to walk merged resource dictionaries like `<ResourceDictionary Source='views/resources/Styles.xaml'>`  or `<ResourceDictionary Source='/MyLib;component/controls/colors.xaml'>`. Thus we need to do two things:
* [optional]: find Project for MyLib
* find additional document based on project relative path \controls\colors.xaml. Actual document can be a linked file or come from shared project

**Comment by etvorun** [comment]
@jasonmalinowski can you pleaee take a look :)

**Comment by jasonmalinowski** [comment]
I think this recently came up too in the replacement for IWorkspaceProjectContext that we were working on with @tmeschter -- we weren't doing link file support (or something equivalent) for additional files since we didn't really have any idea somebody would have a need for them.

That said, I'm still confused on the scenario here @etvorun -- the existing XAML compiler also consumes link directives to handle things like this at the MSBuild layer? Because Roslyn doesn't use these folders other than when doing a few refactorings and placing new files on disk. It's not something we use to impact our semantics at all.

**Comment by etvorun** [comment]
@jasonmalinowski 
Example:
<project>/Views/MyPage.xaml
```
<Page>
  <Page.Resources>
    <ResourceDictonary>
      <ResourceDictonary.MergedDictionaries>
        <ResourceDictonary Source='Styles.xaml'/> <!-- relative to document -->
        <ResourceDictonary Source='/Styles.xaml'>  <!-- relative to project root -->
        <ResourceDictonary Source='/Resources/Styles.xaml'>  <!-- relative to project root -->
        <ResourceDictonary Source='/MyLib;component/Resources/Styles.xaml'>  <!-- relative to referenced project which builds MyLib.dll -->
      </ResourceDictonary.MergedDictionaries>
    </ResourceDictonary>
  </Page.Resources>
  <Button Style='{StaticResource }'/>
<Page>
```

To show intellisense when editing `{StaticResource }` we need to examine content of *.xaml files listed in MergedDictionaries sections. That requires finding `AdditionalDocument` based on project relative path, i.e. it is a function of TextDocument.Folders + TextDocument.Name. If TextDocument.Folders are always empty then it would break XAML intellisense.

**Comment by dibarbet** [comment]
@arkalyanms for scheduling - XAML needs this for their LSP implementation
