### ISSUE TITLE
`SyntaxTree.GetChanges()` returns non-deterministic results

### ISSUE THREAD

**Issue by paulssn** [dotnet/roslyn#65580]
**Version Used**: 4.4.0
**Reproducible for**: C#, VB.NET

### Context
We were analyzing a problem reported by users, and ended up debugging and trying to understand the behaviour of `SyntaxTree.GetChanges()`. A 3rd-party-library uses the returned changes for code formatting, with sometimes completely unexpected results.

### Steps to Reproduce:

1. Run the provided sample program from [here](https://github.com/paulssn/RoslynGetChangesTest) (and see the explanation below).
2. => `SyntaxTree.GetChanges()` returns seemingly non-deterministic results

### Expected Behavior:
`SyntaxTree.GetChanges()` returns the same set of changes every time, if both trees are constructed from the same source text.

### Actual Behavior:
`SyntaxTree.GetChanges()` does not deliver consistent results on subsequent calls. Actually it seems to be not fully deterministic, as it also varies between Debug and Release configuration for example.

Consider the following sample program:

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

for (var i = 0; i < 10; i++)
{
	CalculateChanges();
}

static void CalculateChanges()
{
	var tree1 = GetTree("tree1.cs");
	var tree2 = GetTree("tree2.cs");

	var treeChanges = tree2.GetChanges(tree1);

	Console.WriteLine($"Number of changes: {treeChanges.Count}");
}

static SyntaxTree GetTree(string file)
{
	return CSharpSyntaxTree.ParseText(File.ReadAllText(file));
}
```
This prints the following for our specific example:
```
Number of changes: 950
Number of changes: 31
Number of changes: 27
Number of changes: 31
Number of changes: 31
Number of changes: 31
Number of changes: 31
Number of changes: 31
Number of changes: 720
Number of changes: 944
```
I can't share the SyntaxTree producing exactly these results, but it seems that one can reproduce similar behaviour, by either executing `GetChanges()` a lot of times (>1000), or by using large files with a lot of changes.

I tried it with a random big source file from the roslyn repository and a corresponding changed version (see attached project), and it produces the following results:
```
Number of changes: 3514
Number of changes: 9400
Number of changes: 9402
Number of changes: 25088
Number of changes: 9464
Number of changes: 9415
Number of changes: 9451
Number of changes: 22002
Number of changes: 3524
Number of changes: 9402
```

### Reason / what we know so far:
After some debugging we figured out, that the reason for this behaviour seems to be the following:
* Behind the scenes `GetChanges()` uses the `SyntaxDiffer` which is calculating the similarity of SyntaxNodes (`SyntaxDiffer.GetSimilarity()`).
* This is done by doing a reference comparison of the underlying `GreenNode`s.
* If we now inspect a comparison of specific nodes, it turns out that sometimes the nodes actually are equal and sometimes they are not.
* It seems like that's the case, because there's a global static cache for the nodes: If nodes are not re-used from the cache for some reason, they are treated as not equal, as another node is created and the comparison by reference fails.
   * We didn't analyze the whole caching logic, and therefore I can't explain why a node is cached sometimes and sometimes it's not, but it seems there are several factors playing into that.

### Questions:
* Is this the intended behaviour or a bug?
   * For me it feels wrong if caching (a performance optimization) would influence a feature like `GetChanges()`, ie has a functional impact.
* Is there something we missed, and the described behaviour can be explained by anything else?
* Let's assume this behaviour is intended, is there a way to get some kind of diff between SyntaxTrees or Documents in a consistent way?

**Comment by Youssef1313** [comment]
Might be related to https://github.com/dotnet/roslyn/issues/17498

cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Yes, this is by design. The only requirement of GetChanges is that the changes be accurate. I.e. applying the changes to one text gets you three other. There are no guarantees beyond that. 

> is there a way to get some kind of diff between SyntaxTrees or Documents in a consistent way?

The only way would be to write your own diff system.

**Comment by tmat** [comment]
@CyrusNajmabadi This is not great. Likely cause of test flakiness: https://github.com/dotnet/roslyn/issues/39696

**Comment by CyrusNajmabadi** [comment]
Any other approach would not allow the impl to make optimization decisions (like using the nodes if they have them, and falling back to a full diff approach if not).  I can't see any way of changing this safely.  If we want some sort of deterministic diff, it will likely have to be through a new API that guarantees that and uses no concepts of referential identity or node caches to make any determinations.

**Comment by paulssn** [comment]
> Yes, this is by design. 

Hmm, doesn't seem ideal. But nevertheless, thanks for the clarification!

> The only requirement of GetChanges is that the changes be accurate. I.e. applying the changes to one text gets you three other.

I think I don't understand, What is guaranteed? 🤔

**Comment by CyrusNajmabadi** [comment]
> What is guaranteed? 

What the function gives you back a list of changes that, when applied to the old text, gives you the new text. It is acceptable, for example to get a single text change replacing the entirety off the old text with the contents of the new text.

**Comment by tmat** [comment]
Seems like GetChanges should have returned an opaque type that does not expose the exact list of TextChanges, but instead just a method to apply the changes to text. As it is right now it is too easy for the caller to not realize the non-determinism and use the returned text changes in a way that leads to propagating the non-determinism. 

At minimum this should be documented in the API. Maybe we should make the API obsolete.

**Comment by tmat** [comment]
Actually, we use the method in multiple features and propagate the non-determinism. How are our tests not failing randomly? :(

**Comment by paulssn** [comment]
> > What is guaranteed?
> 
> What the function gives you back a list of changes that, when applied to the old text, gives you the new text. It is acceptable, for example to get a single text change replacing the entirety off the old text with the contents of the new text.

Ok, got it - thanks!
What would be the way to apply the changes to the old text, ie is there some roslyn API for that? I'd like to check whether this works reliably.

**Comment by CyrusNajmabadi** [comment]
Not at computer, but it's basically SourceText.WithChanges
