### ISSUE TITLE
Template formatting with namespace style leads to mis-aligned content

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WeatherForecastController-does-not-forma/10205694)._

---
In a new Blazor Webassembly App project with ASP.NET Core Hosted, in the server app, the WeatherForecastController does not format correctly.

It formats like the screenshot:

The closing brace for the string array is placed at the wrong level.

This happens for .Net 6 and .Net 7

---
#### Feedback Bot on 11/17/2022, 05:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment]
For Roslyn folks who may be investigating; the templates are correct, however there seems to be some misalignment being introduced.


> https://github.com/dotnet/aspnetcore/blob/a55d4a41ad60430cdfcdaf22b4136ab8fe57fafa/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherForecastController.cs#L30-L33
> 
> https://github.com/dotnet/aspnetcore/blob/a55d4a41ad60430cdfcdaf22b4136ab8fe57fafa/src/Components/WebAssembly/testassets/Wasm.Authentication.Server/Controllers/WeatherForecastController.cs#L15-L18
> 
> https://github.com/dotnet/aspnetcore/blob/a55d4a41ad60430cdfcdaf22b4136ab8fe57fafa/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs#L31-L34

**Comment by CyrusNajmabadi** [comment]
We changed 'file scoped namespace' formatting to not actually format, but to just indent and dedent hte lines.  so this should be fixed.
