### ISSUE TITLE
Comments should be aligned with the text below, not above.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65608]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Comments-should-be-aligned-with-the-text/10211415)._

---
[severity:It bothers me. A fix would be nice]
Can we change the alignment of comments so they're aligned with the lines that follow them rather than the line that they follow?

![image](https://user-images.githubusercontent.com/1408396/204008792-f68514a9-7d44-4a9b-a87d-4ea50f03e82e.png)

---
#### Feedback Bot on 11/23/2022, 08:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Duplicate of #23624
