### ISSUE TITLE
csharp_style_pattern_matching_over_as_with_null_check incorrect results near labels and goto statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65609]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/csharp_style_pattern_matching_over_as_wi/10211340)._

---
Code cleanup is supposed to produce code that functions identically to the original.

One of the rules in my set, I think it is csharp_style_pattern_matching_over_is_with_cast_check, but possible csharp_style_pattern_matching_over_as_with_null_check fails.  

Before Cleanup
```
    public static IList GetMembers(this LambdaExpression e)
    {
        var memberInfos = new List();

        var body = e.Body as MemberExpression;
Again:
        if (body == null)
        {
            var ubody = (UnaryExpression)e.Body;
            body = ubody.Operand as MemberExpression;
        }

        memberInfos.Add(body.Member);

        if (body.Expression != null)
        {
            body = body.Expression as MemberExpression;
            if (body != null)
            {
                goto Again;
            }
        }

        memberInfos.Reverse();
        return memberInfos;
    }
```

After cleanup (look at the code around the "Again" label)

```
    public static IList GetMembers(this LambdaExpression e)
    {
        var memberInfos = new List();

Again:
        if (e.Body is not MemberExpression body)
        {
            var ubody = (UnaryExpression)e.Body;
            body = ubody.Operand as MemberExpression;
        }

        memberInfos.Add(body.Member);

        if (body.Expression != null)
        {
            body = body.Expression as MemberExpression;
            if (body != null)
            {
                goto Again;
            }
        }

        memberInfos.Reverse();
        return memberInfos;
    }
```

---
#### Feedback Bot on 11/23/2022, 08:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of broad feedback on this.

**Comment by jbt00000** [comment]
Why does broad feedback matter?

This is a bug.  Your optimizer breaks existing code in subtle ways.

It is one thing to defer as you have bigger fish to fry.  Simply closing it is weak.  Why even have issues?

**Comment by CyrusNajmabadi** [comment]
> Why does broad feedback matter?

Meaning we haven't heard enough to think this is broadly impacting customers.

> This is a bug

Yes.  But like all bugs, they are triaged and we have to make choices on where we put the limited resources we have available.

>  Why even have issues?

To help determine what to put our resources into.  But if we decide it's not worthwhile, then bugs just act as an enormous source of noise.  Note: if you are interested in fixing this issue, feel free to make a PR.  We'd likely take it.  But we're unlikely to make a change here ourselves.  Thanks.
