### ISSUE TITLE
[VB.NET] Using the `Convert to conditional expression` quick fix generates a wrong DirectCast

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/roslyn#65615]
I have this code(with a missing `End If`)

```
Dim value As Double
If value >= 360 Then
    value = value Mod 360
 ElseIf value < 0 Then
    Dim v = (value Mod 360)
    If v < 0 Then
       value = 360 + v
    Else
       value = 0
    End If
```

I used the quick fixes to convert the `if v` statement to an if expression and I got this
```
value = If(v < 0, 360 + v, DirectCast(0, Double))
```

Which is strange and also gives an error, because direct cast can't be used with doubles and integer.
So, regardless the outer block has a proper close or not, this should not effect this fix, and DirectCast shouldn't be used between types that are not related, not to mention value types!
Note that when I add the messing end if, the fix works as expected!

**Comment by CyrusNajmabadi** [comment]
@VBAndCs We'd be happy to take a fix here if you'd like to contribute one.  Let us know and we can help you with it.

**Comment by CyrusNajmabadi** [comment]
@VBAndCs can you provide a larger repro?  Specifically, providing the definition of `value`?

**Comment by VBAndCs** [comment]
```
 Dim value As Double
        If value >= 360 Then
            value = value Mod 360
        ElseIf value < 0 Then
            Dim v = (value Mod 360)
            If v < 0 Then
                value = 360 + v
            Else
                value = 0
            End If
```

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing as we are not likely to be investing in these scenarios.
