### ISSUE TITLE
Make `Covert to raw string` refactoring understand interpolation

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65625]
Currently `Covert to raw string` refactoring is not suggested, when invoked over interpolation string. It would be very helpful, if it can unserstand code like
```cs
var str = @$"
class C
{{
    {returnType} M()
    {{
    }}
}}"
```
and automatically determine how many interpolation tokens is required, so the result of converting code from above would be
```cs
var str = $$"""
    class C
    {
        {{returnType}} M()
        {
        }
    }
    """
```

**Comment by CyrusNajmabadi** [comment]
@allisonchou for visibility
