### ISSUE TITLE
The `SyntaxGenerator` class does not generate default values for parameters of member/constructor/operator.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#65638]
## Background and Motivation

The `SyntaxGenerator` class does not generate default values for parameters of member/constructor/operator.
Issue to track on our side: https://github.com/dotnet/arcade/issues/11734

[SyntaxGenerator.cs#L171](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L171):
```C#
internal SyntaxNode MethodDeclaration(IMethodSymbol method, string name, IEnumerable<SyntaxNode>? statements = null)
{
    var decl = MethodDeclaration(
        name,
        parameters: method.Parameters.Select(p => ParameterDeclaration(p)),
// ...
```
we call `public SyntaxNode ParameterDeclaration(IParameterSymbol symbol, SyntaxNode? initializer = null)` method providing the first parameter and never the second one.

`IParameterSymbol` has next properties:
* `bool HasExplicitDefaultValue { get; }`
* `object? ExplicitDefaultValue { get; }`

We can generate default values for parameters if `HasExplicitDefaultValue` is set. I believe the internal class `Microsoft.CodeAnalysis.CSharp.CodeGeneration.ExpressionGenerator` is responsible for generating default values.
```C#
internal static ExpressionSyntax GenerateExpression(
    ITypeSymbol? type,
    object? value,
    bool canUseFieldReference)
```

## Proposed API

```diff
internal SyntaxNode MethodDeclaration(IMethodSymbol method, string name, IEnumerable<SyntaxNode>? statements = null)
{
    var decl = MethodDeclaration(
        name,
-        parameters: method.Parameters.Select(p => ParameterDeclaration(p)),
+        parameters: method.Parameters.Select(p => ParameterDeclaration(p, p.HasExplicitDefaultValue ? ExpressionGenerator.GenerateExpression(p.Type, p.ExplicitDefaultValue) : null)),
// ...
```

**Comment by andriipatsula** [comment]
cc. @RikkiGibson , @ViktorHofer , @smasher164

**Comment by CyrusNajmabadi** [comment]
yes.  seems like unintentional.  will fix.

**Comment by andriipatsula** [comment]
@CyrusNajmabadi , the same issue is for `ConstructorDeclaration` and `OperatorDeclaration` methods. Could I kindly ask you how much it could take to fix this issue? Either I copy/past couple of classes from roslyn into sdk (`Microsoft.DotNet.GenAPI` project) to support default parameter generation or will wait till it resolved.

**Comment by CyrusNajmabadi** [comment]
I don't get hte need for this for operators.  Optional values make no sense tehre.  Why do you need that?  My fix will fixup constructors.

**Comment by andriipatsula** [comment]
>I don't get hte need for this for operators. Optional values make no sense there

yeh, sorry. Agree

**Comment by weltkante** [comment]
Nice 👍 - ran into this exact problem when trying to write an IIncrementalGenerator that generats forwarding stubs to another object.

**Comment by CyrusNajmabadi** [comment]
SyntaxGenerator cannot be used by source generators. It exists at a higher layer (workspaces) not available to generators

**Comment by weltkante** [comment]
ah, too bad
