### ISSUE TITLE
Writes through `UnscopedRef` allows bypassing lifetime rules

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/roslyn#65648]
**Version Used**: 
57cfbe6f5ba818c42485bf15f03146f15546e12e

**Steps to Reproduce**:

The following example compiles:

```csharp
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

public class Repro
{
    private static void Bad(ref RefStruct2 s2)
    {
        int value = 100;
        RefStruct1 s1 = new RefStruct1();
        s1.Ref.RefField = ref value;
        s2.RefField = ref s1.RefField;
    }

    private ref struct RefStruct1
    {
        public ref int RefField;
        [UnscopedRef] public ref RefStruct1 Ref => ref this;
    }

    private ref struct RefStruct2
    {
        public ref int RefField;
    }
}
```

[Sharplab Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQeADAAR5EB0AIlBAOYwD2AzglAMZd6AYQ7oApgEEYEFAE8uULgG5yVWgwBKAVxi8wY4RzAAHVGIBOAZQsA3fmOXlVAZloFqGscfMdyAb3JqIOpvKBsIBDF1ADZaABZqACEIdAAKczEAMw8sywRzLT4Edy4CAEpA4ICyYNrqWARqcJQtKIBeaiJKShUauqDPTLyCoqJqLjGOmDEAdxyh/MKEIlSy3v6gifpB7ayAMSgxFHRqDozs5tb1jdLdzIOjk7Os8c19w+ProIBfJz6g0LhSLUc7jRZFebDJakf7UaobWiuUENeYPT6VfoAbQAqjAuHwOMYxOhBgBdREgl6DKGjeanAB8lOyCAAFoovtRfmQMSFzGEIlFQTwRo1qeDijz4Rs8EiXijBmj0Byud8gA==)

A byref to `value` escapes from `Bad`.

**Expected Behavior**:
Compiler error.

**Actual Behavior**:
No compiler error.

**Comment by jaredpar** [comment]
This has similar problems as #62618. Essentially we're returning a `ref` value with RSTE and STE of *current method*. That allows for the re-assignment to occur. My instinct is the STE here should be *calling method* but I'm not 100% confident in that.

**Comment by RikkiGibson** [comment]
In this scenario I would expect an equivalent diagnostic for both `s1.RefField = ref value` and `s1.Ref.RefField = ref value`.
