### ISSUE TITLE
BasicVenus failing in standalone runs due to extra window popup when creating a new WebPage project

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#6567]
There appears to be a new window pop up when attempting to create a ASP.NET project in the latest update builds.

To repro on a clean machine go File -> New Web Site... -> ASP.NET Empty Web Site -> OK. 
This window pops up which asks if you would like to install a nuget package to enable C# 6.

![image](https://cloud.githubusercontent.com/assets/10537189/10953706/4795fb5a-82fe-11e5-8d35-6f6d6375cb62.png)

I'm guessing this is by design, as hitting 'Enable C# 6' allows things to progress normally. We just need to update some of the VSI tests to deal with this.

I've disabled BasicVenus.xml for the standalone tests in the meanwhile. There may be other tests affected and I'll disable those and make notice here.

**Comment by mattscheffer** [comment]
Also affecting CSharpVenus and CSharpWebApp

**Comment by mattscheffer** [comment]
And BasicWebApp

**Comment by Pilchie** [comment]
This change was reverted by the asp.net team today, so these should start working again in tomorrow's update 1 build.

**Comment by mattscheffer** [comment]
Ooh good to know. Are we expecting them to push the change for next update?

**Comment by Pilchie** [comment]
Yes.

**Comment by mattscheffer** [comment]
Thanks, I'll close this for now and re-open when the check it back in.
