### ISSUE TITLE
Conversion operator clashes with the explicit impls

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#65685]
**Version Used**: main branch

**Steps to Reproduce**:

Compile the following code:
```c#
interface ISam1<T> where T : ISam1<T>
{
  static abstract T operator +(T a, T b);
  static abstract implicit operator int(T t);
}

interface ISam2<T> where T : ISam2<T>
{
  static abstract T operator +(T a, T b);
  static abstract implicit operator int(T t);
}

class Foo : ISam1<Foo>, ISam2<Foo>
{
  // two explicit impls delegating to one sign operator
  static Foo ISam1<Foo>.operator +(Foo a, Foo b) => a + b;
  static Foo ISam2<Foo>.operator +(Foo a, Foo b) => a + b;

  public static Foo operator +(Foo a, Foo b) => a;

  // two explicit impls delegating to one conversion operator
  static implicit ISam1<Foo>.operator int(Foo t) => 1;
  static implicit ISam2<Foo>.operator int(Foo t) => 2;

  // CS0557: Duplicate user-defined conversion in type 'Foo'
  public static implicit operator int(Foo t) => 42;
}
```

**Expected Behavior**:

Code compiles fine. There is no other members in the type for `operator int` to clash with.

**Actual Behavior**:

> CS0557: Duplicate user-defined conversion in type 'Foo'

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn/blob/15683879b536f1a2dc59b99543ea9d076ec65190/src/Compilers/CSharp/Portable/Symbols/ConversionSignatureComparer.cs#L51-L71

@AlekseyTs Is the implementation above correct?

**Comment by AlekseyTs** [comment]
Without taking a closer look, it is quite possible that the problem is not in the comparer. An explicit implementation cannot conflict with a regular declaration, so there is really no point in comparing their signatures.

**Comment by Youssef1313** [comment]
@AlekseyTs The callsite of the comparer is a `HashSet` where we add members of a type to check for duplicates. If we are not going to modify the comparer, we'll probably need to split this `HashSet` into two, one for implicit conversions and one for explicit conversions.

What I had in mind earlier is something like this. Is that wrong for some reason?

```csharp
(member1.Name == member2.Name || (member1.Name == WellKnownMemberNames.ImplicitConversionName && member2.Name == WellKnownMemberNames.ExplicitConversionName) || (member1.Name == WellKnownMemberNames.ExplicitConversionName && member2.Name == WellKnownMemberNames.ImplicitConversionName))
```

**Comment by AlekseyTs** [comment]
@Youssef1313 Are you working on a fix or just curious?

**Comment by AlekseyTs** [comment]
> If we are not going to modify the comparer, we'll probably need to split this `HashSet` into two, one for implicit conversions and one for explicit conversions.

Again, without taking closer look, I think that explicit implementations shouldn't be added into ```conversionsAsConversions``` set. They are not regular conversions.   
```
                    var conversion = symbol as SourceUserDefinedConversionSymbol;
                    var method = symbol as SourceMemberMethodSymbol;
                    if (!(conversion is null))
                    {
                        // Does this conversion collide *as a conversion* with any previously-seen
                        // conversion?

                        if (!conversionsAsConversions.Add(conversion))
```
