### ISSUE TITLE
Symbol.IsSupportedOperatorName (C#) appears to be unused and should be deleted

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#657]
Was browsing through the C# symbol code and saw [IsSupportedOperatorName] (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/SemanticFacts.cs,d03fb008022be42d).

There appear to be no references to this method, even from test code. Looks like it can be deleted (and its attendant [s_supportedOperators](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/SemanticFacts.cs,5457d3ec75bcec84,references) HashSet.

**Comment by gafter** [comment]
This was an intended part of our public API. We don't know if there are external consumers at this time.

We could defer the allocation of the hash table until it is used by placing the hash table (and its initialization) in a nested class. Do you think that would be worth doing?

**Comment by pharring** [comment]
It's on an 'internal' type, so it's inaccessible to external consumers. Did you intend it to be public?

I'm not worried about deferring initialization. It's "BeforeFieldInit", so it should already be deferred.

**Comment by gafter** [comment]
Oh, didn't realize the container was internal.
