### ISSUE TITLE
Possible Optimization: An attribute to force the generation of a jump table for a switch on integer

### ISSUE THREAD

**Issue by ndepend** [dotnet/roslyn#65703]
In our product code we are analyzing assemblies and are switching over IL instructions OpCode. I figured out that the IL generated goes over all OpCode values one by one to do the proper branch while this `switch` represents a critical branch in our code.

Why is Roslyn not relying on the [IL `switch` operation and jump table](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.switch?redirectedfrom=MSDN&view=net-7.0) possibility in this case? What are the conditions to generate a jump table? (the IL code range we are about is `[17,210]` maybe that explains?). What about a method attribute that forces the generation of a jump table so the programmer can benchmark and choose?

In our case this switch is a critical path in our code and certainly a jump table would help.

![image](https://user-images.githubusercontent.com/511445/204967902-7aecc47c-0c49-4afe-8f83-4ff1782b0d59.png)

**Comment by svick** [comment]
The algorithm currently used for emitting integer-based switches is described here:

https://github.com/dotnet/roslyn/blob/9fb1877ba1366b4a35de96639a8276538f9f4090/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs#L69-L96

In short, the IL `switch` instruction on its own only works well if the labels are "dense": you don't want to have a 200-items long jump table just for a dozen labels.

But even if there are no `switch` instructions, the generated code is not a linear search over all labels, it's a binary search, which should make it as efficient as possible. You can see that in your IL, many of the checks are `bgt` and `ble`, not just `beq`; the part of the tree visible in the IL is something like this:

```
>114(>2(=0(=2), 17-18(=113(=114))), >162(=118(=137(=162)), =174(...)))
```

**Comment by ndepend** [comment]
Thanks @svick glad it is a binary search and lot a linear one.

>you don't want to have a 200-items long jump table just for a dozen labels.

Actually yes, that is what I would want for a critical path to at least benchmark it and then see if it is worth wasting 200*4 = 800 bytes of memory for that, which is not much on today machines.

**Comment by CyrusNajmabadi** [comment]
Why not profile exactly that?  Just make a sense switch, where the other branches don't do anything.

**Comment by ndepend** [comment]
@CyrusNajmabadi I'd like to be how? change the Roslyn for jump table emitting code and recompile it? Unfortunately I am not acquainted with the Roslyn code base.
If the benchmark shows interesting win instead of modifying the jump table emitting code I'd suggest to provide instead a method attribute that the user could use to force a jump table emitting in his/her concerned method.

**Comment by CyrusNajmabadi** [comment]
Just change your current sparse switch to be a dense switch.  I.e. add in the missing cases and have them just be no-ops.  Profile and see how the performance compares.

**Comment by ndepend** [comment]
So I did some tests and didn't find any significant improvements in real conditions. I guess the `switch` is taking just a small fraction of the time spent in the concerned method.

With DotTrace on 8M IL instructions analyzed here are the number for the concerned method in 6 tests:
```
with jump table              without jump table
62 009ms                     58 401ms
60 582ms                     58 469ms
59 528ms                     64 044ms
```
For now we'll spend our optimization resources on something else thanks

**Comment by CyrusNajmabadi** [comment]
Closing out.
