### ISSUE TITLE
PublicAPI analyzer is not running

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#65707]
Add a new public method and build with analyzers. You should get an error saying public API files need to be updated, but no error occurs.

**Comment by mavasani** [comment]
This was recently fixed by @333fred. We need to move the repo to new analyzer package with the fix.

**Comment by RikkiGibson** [comment]
Looks like the fix was implemented in dotnet/roslyn-analyzers#6291

**Comment by mavasani** [comment]
Enabled with https://github.com/dotnet/roslyn/pull/65737
