### ISSUE TITLE
Document outline should do shorter qualification for explicit interface methods

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#65714]
**Version Used**: 17.5.0 Preview 1

**Steps to Reproduce**:

1. Have an explicitly implemented interface method in a class.

**Actual Behavior**:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/201340/205189476-4bea7586-6fcd-4f91-82fb-6b1a9b534ad3.png">

**Expected Behavior**:

We didn't use the fully qualified interface name; just the base name is likely to be sufficient. Ideally we could use whatever qualification is already in the source.

**Comment by sharwell** [comment]
This was fixed by #65641

![image](https://user-images.githubusercontent.com/1408396/236352188-8211712e-a45a-4b83-b63b-bed08878e569.png)
