### ISSUE TITLE
add "inline method" refactoring for async methods in C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65721]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/add-inline-method-refactoring-for-asyn/10161218)._

---
Currently it's not possible to use the "inline method" refactoring on an async methods.
https://learn.microsoft.com/en-us/visualstudio/ide/reference/inline-method?view=vs-2022

---
#### Feedback Bot on 9/30/2022, 01:53 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback
