### ISSUE TITLE
Audit if new APIs added to IFileChangeWatcher.cs were intentionally public or not

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65738]
@jasonmalinowski It seems the correctness analyzers leg is failing as you recently added a public API that has no entry in unshipped file:
```
src/Workspaces/Core/Portable/Workspace/ProjectSystem/IFileChangeWatcher.cs(26,25): error RS0016: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'WatchedDirectory' is not part of the declared public API
```

Looking at your PR which added this public API: #65701, it seems the public API addition was likely unintentional. I am going to to switch it to an internal type, and feel free to make it public again if that was an intentional change.

EDIT: It seems #65701 added 2 more public interfaces: `IFileChangeContext` and `IWatchedFile`. I am not sure if any of them were intentionally made public. I have switched all of them back to internal.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/65737#issuecomment-1336096630_

**Comment by jasonmalinowski** [comment]
None of these were intended to be made public, so thank you this was a very good catch!
