### ISSUE TITLE
Review all the non-infra changes in #65737

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65746]
#65737 unblocks the repo from re-enabling the public API analyzer, which was inadvertently turned off few weeks back. Apart from the core infrastructure changes in that PR, I had to make additional source/public API file changes. This issue tracks reviewing those changes with the devs that made the original API changes while the public API analyzer was disabled.

I have added comments to https://github.com/dotnet/roslyn/pull/65737 for the changes/devs that need to be reviewed

**Comment by mavasani** [comment]
Assigned to @333fred to take this up in the next public API review meeting.

**Comment by tmat** [comment]
LGTM

**Comment by 333fred** [comment]
Thanks both. Closing out.
