### ISSUE TITLE
Update `Xunit.Combinatorial` version

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#65754]
Current version of `Xunit.Combinatorial` package is `1.3.2`:
https://github.com/dotnet/roslyn/blob/c01cce63989d85d1bfb656f9e9762f5c38e49e36/eng/Versions.props#L272
According to [Nuget](https://www.nuget.org/packages/Xunit.Combinatorial/1.3.2) this version is 2 years old.
I propose to update it to the latest stable version [1.5.25](https://github.com/AArnott/Xunit.Combinatorial/releases/tag/v1.5.25). The main reason for change is a new `CombinatorialMemberDataAttribute`, which can be quite handy in cases like this:
https://github.com/dotnet/roslyn/blob/c01cce63989d85d1bfb656f9e9762f5c38e49e36/src/Analyzers/CSharp/Tests/MakeTypePartial/MakeTypePartialTests.cs#L306-L354
Here I want to test, that by selecting both the first and the second diagnostic to fix I get the same result. But I also want to test it against all possible partial member declarations specified as a member data. If I had `CombinatorialMemberDataAttribute`, I would declare the test as a `Theory`, that accepts a combinatorial data of `declarationType` from member `AllValidDeclarationTypes` and a combinatorial member of `diagnosticIndex` from fixed range of values `0` and `1`. But I have to duplicate code in order to test all required cases.
The need of this new attribute is pretty niche, but the cost is just a single line change and a _very_ low risk of breaking something, so I think it is acceptable

**Comment by CyrusNajmabadi** [comment]
Feel free to make the PR.

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi You closed this too early. I just tried to manually bump the version and after running `Restore.cmd` got error `NU1102`: Unable to find package 'Xunit.Combinatorial' with version (>= 1.5.25), found 12 versions in dotnet-public [ Nearest version 1.4.1 ]
It seems that roslyn doesn't use Nuget directly and in its source the latest version isn't available yet. Do you know if this sync process is automatic and we just need to wait or it is done manully, so in order to get it working here someone has to make a PR to dotnet sdk repo or something like that?

**Comment by CyrusNajmabadi** [comment]
No clue. @dibarbet do you know how this works.

**Comment by DoctorKrolic** [comment]
Found the source where the package was searched: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public/NuGet/Xunit.Combinatorial/versions/1.4.1 Now just need to figure out how to force this thing to update its package version list...

**Comment by DoctorKrolic** [comment]
Yes, the update process is now fine. I have some troubles with using new features, but this is another story) Thanks!

**Comment by DoctorKrolic** [comment]
Uh, version `1.5.25` doesn't support `CombinatorialMemberData` for `strings`s, the support for it was added [later](https://github.com/AArnott/Xunit.Combinatorial/pull/55) I see...
