### ISSUE TITLE
CS8602 in child class when in the construtor ensures the value of base class property won't be null

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/roslyn#65753]
### Analyzer

**Diagnostic ID**: [CS8602](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8602)): `Dereference of a possibly null reference`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 7 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 7](https://dotnet.microsoft.com/download/dotnet/7.0)

### Describe the bug

The title is self explicative, When you have a child class using a property of the base class, and the property in the base class can be null but it isn't (ctor ensured), it stills warns about CS8602.

### Steps To Reproduce

Take this example:

```C#
public record EntityBasedEntryViewModel<T> : EntryViewModel where T : IEntity
{

    public T? Entity { get; }

    [MemberNotNullWhen(false, nameof(Entity))]
    public sealed override bool IsNewEntryPlaceholder => base.IsNewEntryPlaceholder;

    protected EntityBasedEntryViewModel(T? entity, string description) : base(entity == null, description)
    {
        Entity = entity;
    }

}

public record PieceReportViewModel : EntityBasedEntryViewModel<ICDAPieceReport>
{

    public string Piece => Entity.Piece;

    public bool? HasCaries => Entity.HasCaries;

    public bool ShowHasCariesOption { get; }

    public bool HasComplication => Entity.HasComplication;

    public ComplicationType ComplicationType => Entity.ComplicationType;

    public string ComplicationComment => Entity.ComplicationComment;

    public SilnessLoePlaqueValue Plaque => Entity.Plaque;
    public LoeSilnessGingivalValue Gingival => Entity.Gingival;
    public WWDCProbingDepthValue ProbingDepth => Entity.ProbingDepth;
    public SilnessMarginLocationValue MarginLocation => Entity.MarginLocation;

    public CDAValue CDASurfaceColor => Entity.CDASurfaceColor;
    public CDAValue CDAAnatomy => Entity.CDAAnatomy;
    public CDAValue CDAMarginal => Entity.CDAMarginal;

    public PieceReportViewModel(ICDAPieceReport entity, bool structureIsImplant) : base(entity, $"{TextResources.Piece} {entity.Piece}")
    {
        ShowHasCariesOption = !structureIsImplant;
    }
}

```

Currently it warns in `PieceReportViewModel` properties about `Entity` property, but in the PieceReportViewModel ctor we "ensure" `entity` parameter can't be null, then `Entity` will never be null (in this subclass tree types)

### Expected behavior

Not Warning

### Actual behavior

It warns about it.

**Comment by jcouv** [comment]
From the bug description, I couldn't tell where the warning is reported and I couldn't repro (got many errors because of missing types).
Please provide a small self-contained repro. We recommend [sharplab](https://sharplab.io/) as the most efficient mechanism in our bug filing template. Thanks

**Comment by DrkWzrd** [comment]
The warning occurs in the child class.
I have a parent class `EntityBasedEntryViewModel`. There is a property called `Entity` (which is nullable).

But in a child class `PieceReportViewModel`, I have a ctor ensuring that `Entity` could not be null in this class type.
But the class is populated with warnings telling me "`Entity` could be null, because in the parent class could be null".
And that could be right if `Entity` property could be modified in other circumstances, but is a get-only property.

![image](https://user-images.githubusercontent.com/40547839/233797477-c10001fd-da09-486d-b51e-fe7b8a9326df.png)

**Comment by CyrusNajmabadi** [comment]
There's no way for the compiler to know that it can be null in the case. It doesn't know what the base constructor does, or that's there's a relation between the nonnull value you pass to it and the property.  Null analysis across method bodies is based on signatures. There's no intermethod analysis that happens. :-)

**Comment by jcouv** [comment]
Thanks @CyrusNajmabadi for the analysis. That's correct, there's no inter-method analysis in the current design for this feature. I'll close as by-design. 
If you have a proposal for improved analysis, it should be discussed in the csharplang repo. Thanks
