### ISSUE TITLE
Add documentation of IDE0120

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65758]
<html>
<body>

IDE0120 | https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0120 | Simplify LINQ expression
-- | -- | --

</body>
</html>

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

**Comment by gewarren** [comment]
Please assign to me.

**Comment by arphox** [comment]
Maybe **Feature - IDE0120** label should be added?
