### ISSUE TITLE
Can't use C# LangVersion 1 w/ Roslyn (only version 2 onwards)

### ISSUE THREAD

**Issue by federico-r-figueredo** [dotnet/roslyn#65751]
**Version Used**: 

**Steps to Reproduce**:

1. Set compiler options to C# language version 1...

    ...via CLI...
    ![image](https://user-images.githubusercontent.com/49570839/205464661-db022a1f-fda0-4da7-8d5d-035a40a06d79.png)

    ...ir via .csproj XML...
    ![image](https://user-images.githubusercontent.com/49570839/205464630-bc9e82cb-ecee-49e3-8211-39dbeb4da30b.png)

3. Use valid C# v.1 source code (e.g.: no static classes)...

    ![image](https://user-images.githubusercontent.com/49570839/205464613-b4c276f7-a44d-48da-a796-e507a08d8e0f.png)

4. build the project

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**: CS8022

**Expected Behavior**: The compiler generates successfully the IL code (.exe or .dll) form the source code

**Actual Behavior**: I  get -> error CS8022: Feature 'namespace alias qualifier' is not available in C# 1. Please use language version 2 or greater...

![image](https://user-images.githubusercontent.com/49570839/205464585-58ffb8af-4870-416e-a8bd-c9034cdd35d6.png)

**Comment by svick** [comment]
As the error message shows, the problem is not with your code, but with code that is autogenerated by the SDK. To disable that, add `<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>` to your csproj.
