### ISSUE TITLE
Add missing documentation for new IDExxxx code style analyzers 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65757]
With https://github.com/dotnet/roslyn/pull/62242, we now keep track of all the undocumented IDExxxx code style rules in the Features project. This is a master issue that tracks adding documentation for each of these undocumented rules in [dotnet/docs](https://github.com/dotnet/docs) repo.

Steps to follow to add documentation: https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md

Existing documented rules: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/

New IDExxxx code style rules that need to be documented: https://github.com/dotnet/roslyn/blob/main/src/Features/RulesMissingDocumentation.md

## Tracking issues

   - [x] https://github.com/dotnet/roslyn/issues/65758
   - [x] https://github.com/dotnet/roslyn/issues/65759
   - [x] https://github.com/dotnet/docs/issues/32876
   - [x] https://github.com/dotnet/roslyn/issues/65761
   - [x] https://github.com/dotnet/roslyn/issues/65762
   - [x] https://github.com/dotnet/roslyn/issues/65763
   - [x] https://github.com/dotnet/roslyn/issues/65764
   - [x] https://github.com/dotnet/roslyn/issues/65765
   - [x] https://github.com/dotnet/roslyn/issues/65766
   - [x] https://github.com/dotnet/roslyn/issues/65767
   - [x] https://github.com/dotnet/roslyn/issues/65768
   - [x] https://github.com/dotnet/roslyn/issues/65769
   - [x] https://github.com/dotnet/roslyn/issues/65770
   - [x] https://github.com/dotnet/roslyn/issues/65771

**Comment by mavasani** [comment]
Tagging @Youssef1313 as an FYI - thanks for your help here!

**Comment by cremor** [comment]
Related: dotnet/docs#28791
If this issue handles documenting EditorConfig rules too then maybe my issue can be closed in favor of this one.

**Comment by mavasani** [comment]
Yes, both should overlap. Documenting IDExxxx rules also entails documenting the editorconfig option name/value that the rules are associated with.

**Comment by gewarren** [comment]
Everything in the list except the experimental analyzers (IDE200X), JSON001, JSON002, and RE001 have been added by:

https://github.com/dotnet/docs/pull/36421
https://github.com/dotnet/docs/pull/36394
https://github.com/dotnet/docs/pull/36378
https://github.com/dotnet/docs/pull/36346
https://github.com/dotnet/docs/pull/36336

**Comment by cremor** [comment]
Shouldn't this issue be kept open so that the [RulesMissingDocumentation.md](https://github.com/dotnet/roslyn/blob/main/src/Features/RulesMissingDocumentation.md) list is checked regularly? Not just for adding missing documentation pages, but also for removing entries that have been documented. Because right now the list contains many entries that are already documented.
