### ISSUE TITLE
CSharpInteractiveFormsAndWpf is flaky in standalone runs

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn#6575]
Testcase consistently fails in standalone runs during the SumbitReplText and the start of the testcase. It usually passes on reset however.The error and stack trace are always the same.

```
Executing action [11/3/2015 4:10:12 PM] SubmitReplText

Tao.Engine.Exceptions.UnexpectedResultException: Output prompt not found after 10000 ms.  Tail of output
k"
. #r "System.Xaml"
> Text

Server stack trace: 
   at Roslyn.VSHosting.Test.RoslynInProcessAPI.WaitForPrompt(Int32 timeout, String prompt)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Roslyn.VSHosting.Test.RoslynInProcessAPI.WaitForPrompt(Int32 timeout, String prompt)
   at Roslyn.VSHosting.Test.SubmitReplTextAction.Execute(TaoEngine engine)
   at Tao.Engine.DebuggableActionExecutor.Execute()
   at Tao.Engine.DefaultActionExecutor.Execute()
```

![image](https://github-cloud.s3.amazonaws.com/assets%2F10537189%2F10957080%2Fe4f70922-8315-11e5-9383-9e571570b840.png)

I'm disabling this test in the standalone runs.

**Comment by amcasey** [comment]
That "Text" after the prompt is what's making `WaitForPrompt` unhappy.  Unless the text of the entire window ends with `>`, it will fail.

**Comment by amcasey** [comment]
The `#r`s appear to happen only in test initialization, so this must be the first scenario.  In fact, we may not even be in the first scenario, since `<InitTest> is also supposed to submit usings.

**Comment by amcasey** [comment]
Another curious point: the screenshot shows the lightbulb next to the second submission.  I understood that didn't work (https://github.com/dotnet/roslyn/issues/6587).

**Comment by amcasey** [comment]
None of the submissions entered by this test case begin with "Test", so I'm not sure where that's coming from.

**Comment by amcasey** [comment]
The last scenario of the preceding test (CSharpInteractiveCommands) does `<SetReplText>Text</SetReplText>`.

**Comment by amcasey** [comment]
I ran it immediately after CSharpInteractiveCommands locally and it failed 10 times in a row.

**Comment by amcasey** [comment]
At the beginning of the test, we reset the interactive window and then it helpfully restores the unsubmitted text (i.e. "Text").  We just need to clear the window at the end of the scenario (and the beginning of the next one).

**Comment by dpoeschl** [comment]
@amcasey This appears to have failed again now: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/436/

**Comment by dpoeschl** [comment]
@amcasey Sorry, the failure I linked to is a different test, but it still has "Output prompt not found after 10000 ms."

**Comment by amcasey** [comment]
Do you have the updated link?  It should have a dump of nearby text and (ideally) a screenshot.

**Comment by amcasey** [comment]
@dpoeschl The test expects to find a blank prompt but actually finds `> Console.WriteLine("Hello World");`.  There can't be too many scenarios that produce that text, so I'd guess the fix is to find it and clear the input at the end of the scenario.

**Comment by amcasey** [comment]
@dpoeschl Have you seen more occurrences?

**Comment by amcasey** [comment]
Tracking the new failure as https://github.com/dotnet/roslyn/issues/6976.
