### ISSUE TITLE
Introducing inefficiency: It seems the Add Reference dialog box pops up from the Roslyn "red light bulb" ... seems superfluous for all occasions.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#65778]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Introducing-inefficiency:-It-seems-the-A/10220458)._

---
![image.png](https://aka.ms/dc/image?name=B4fa8fa03554a4c4b8c5d08ae432a73b8638056362553773686_20221202-205053-image.png&tid=4fa8fa03554a4c4b8c5d08ae432a73b8638056362553773686)

**Figure 1.**  Getting the "little red light bulb smart tag" for a missing reference.  The reference in question happens to be one of the other projects in the currently-open solution.

![image.png](https://aka.ms/dc/image?name=B0d298332590d4ff7a62baaeb7a180ace638056363399303636_20221202-205218-image.png&tid=0d298332590d4ff7a62baaeb7a180ace638056363399303636)

**Figure 2.** Selecting the **Add Reference to Core.Controls, Version=blablabla...** menu command pops up the **References Manager** dialog box in my face.

Hello,

I am trying to be nice about this, but there seems to be an annoying new functionality with the debut of Version 16.11.21 of Visual Studio 2019.  I am an avid user of Visual Studio, and I like to keep my hands off the mouse as much as humanly possible when programming.

Every so often, when I'm coding, I will run into a scenario, as shown in **Figure 1** above.  This is not a big deal, happens all the time.

**Before 16.11.21**, clicking the menu item exposed by the Smart Tag would add the reference to my project in the background.   It would appear again if more project(s) or DLL(s) needed to be referenced.  Which, again, I did not mind at all.  It is like Visual Studio is "thinking for me."  I loved it.  I could click on the squiggly, access the smart tag with my mouse, click the command, and then dust off my hands.

**You clever Microsoft people, you** have changed it, and now it sucks.  Now, version 16.11.21 and later, clicking the little menu command in the Smart Tag makes the **Add Reference**, i.e., **References Manager** dialog pop up in my face blocking my coding and interrupting my train of thought, as shown in **Figure 2.**

I suppose someone had the wonderful idea to say, "You know when someone clicks that Smart Tag Add Reference menu now, we want them to have that handy References Manager up and displayed for them for max versatility and so they can get at all their references."

It sounds, in principle, a good idea.  But I like the old way better.  Is there **Tools** -> **Options** setting(s) that I can check a checkbox for, to change the behavior of the **Add Reference** menu item in **Figure 1** to the old behavior of just adding the dad-gum reference for me that it already knows needs to be added?

I guess I just think that displaying the dialog shown in **Figure 2** is superfluous since Roslyn seems to know **_already exactly which reference is to be added_**; yet, popping up the dialog in **Figure 2** is _modal_, _mean_, and _nasty_ --- not to mention _annoying_ and _useless_ because it _reduces automation__.

I mean, why the heck are we bothering with _me_ having to _select a reference by hand_ in the **References Manager** dialog when the Smart Tag already knows the reference that is to be added? Just add it for me already!

**Please put the old behavior back!**  That would be great.

![image.png](https://aka.ms/dc/image?name=B690a2d386d094d70ba20a8bb719de09f638056369475158326_20221202-210225-image.png&tid=690a2d386d094d70ba20a8bb719de09f638056369475158326)

---
#### Feedback Bot on 12/4/2022, 06:47 PM: 

(private comment, text removed)
#### Feedback Bot on 12/5/2022, 04:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Odd.  We didn't change anything on the roslyn side here.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski all we do here on the roslyn side is:

```c#
            protected override Task<CodeActionOperation?> UpdateProjectAsync(Project project, bool isPreview, CancellationToken cancellationToken)
            {
                var projectWithReference = project.Solution.GetRequiredProject(FixData.PortableExecutableReferenceProjectId);
                var reference = projectWithReference.MetadataReferences
                                                    .OfType<PortableExecutableReference>()
                                                    .First(pe => pe.FilePath == FixData.PortableExecutableReferenceFilePathToAdd);

                return Task.FromResult<CodeActionOperation?>(new ApplyChangesOperation(project.AddMetadataReference(reference).Solution));
            }
```

Do you have any idea why this would invoke the Reference-Manager dialog?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi No idea; I'm wondering if something broke in the project system here which is causing that to fire now. Short of debugging through the project system I'm not sure what else to do here.

**Comment by astrohart** [comment]
@[jasonmalinowski](https://github.com/jasonmalinowski) and @CyrusNajmabadi did I maybe screw up a project system setting?

ALSO: I am using ReSharper.  You know how ReSharper likes to override certain Visual Studio settings because it thinks that it is improving IDE performance that way.  Does popping up the Reference Manager tie in to some sort of "Tools -> Options" Setting?

From the looks of the code snippet you showed, it does not seem like it would; huh,  How bizzare.

**Comment by CyrusNajmabadi** [comment]
> Does popping up the Reference Manager tie in to some sort of "Tools -> Options" Setting?

Not that i'm aware of.  if you have a clean vs without resharper, does this repro?

**Comment by jasonmalinowski** [comment]
I'd be surprised if Resharper could interfere with this.

@astrohart: when you said "Before 16.11.21" in your original ticket, do you mean like it worked in a previous 16.11.* patch release like 16.11.20, or that's just a generic "it was working at some point in the past?"

**Comment by CyrusNajmabadi** [comment]
Unable to repro this, and we haven't heard about this from anyone else.  It's possible this is a resharper issue.
