### ISSUE TITLE
SolutionState should enforce changes to a document happen to all links of that document atomically.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#65797]
Right nwo we allow linked documents to diverge in their state in the in-memory model when individual docs are forked.  We also allow for docs to diverge as we transition individual links in response to event notifications (like file-changed notifications).  Thsi also means that it's possible to observe linked docs with different text in it.

This is both difficult to reason about, and likely the source of bugs. We should actually *strongly* enforce that linked-docs share a single text-source, and that all links are updated atomatically to preserve sane semantics here.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Is your thought here that we entirely jettison the current behavior where we allow the linked copies to diverge for the purposes of refactoring across targets? Or we generally always share state until that moment happens?

**Comment by CyrusNajmabadi** [comment]
i would jettison the behavior entirely.  a change in *text content* to one doc-state changes all the linked file contents atomically for the snapshot you get out of it.   A change in tree-content would also update all the text contents for the other files, though their trees would still be lazily built from that.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  This is very tricky at teh solutionstate level.  Instead, we're doing this at the workspace level when the workspace actually tries to bring itself in sync with a solution.
