### ISSUE TITLE
Additional (unstable) dependencies in Microsoft.CodeAnalysis.Scripting RC1

### ISSUE THREAD

**Issue by profix898** [dotnet/roslyn#6579]
Playing with the NuGet packages for the scripting API, eg. Microsoft.CodeAnalysis.Scripting.CSharp, the latest rc1 package has several new dependencies compared to beta1. While beta1 basically only installed the Microsoft.CodeAnalysis.* packages and the System.Reflection.Metadata package, RC1 now requires a whole lot more. Including unstable/beta packages from the System namespace (see screenshots).

BETA
![beta](https://cloud.githubusercontent.com/assets/2789426/10964950/30320920-83aa-11e5-99cc-0248949f283d.png)

RC
![rc1](https://cloud.githubusercontent.com/assets/2789426/10964951/3033a4ce-83aa-11e5-952a-9b15ac41bf44.png)

Is this accidentally or by purpose? Just wondering why installing CodeAnalysis causes an explosion of additional dependencies. I'm hoping to see a "cleaner" picture for the release package.

**Comment by ManishJayaswal** [comment]
@profix898 Can you check what happens with released packages?

**Comment by profix898** [comment]
![rel111](https://cloud.githubusercontent.com/assets/2789426/12755268/0be5a002-c9cf-11e5-9faf-eb5a9b0d3a54.png)

With the latest stable package v1.1.1 (and pulling into a v4.6.1 full framework project) there are actually even more dependencies, but at least they are all stable. I think that the proliferation of dependencies is something to keep an eye on, but for now I wouldnt consider that a major issue.

**Comment by Suchiman** [comment]
The biggest issue for me about these additional dependencies is for me: 
![devenv_2016-02-02_18-38-21](https://cloud.githubusercontent.com/assets/7110884/12758385/39a485c8-c9dc-11e5-9203-776eb7eb5bd2.png)

**Comment by tmat** [comment]
Is Microsoft.CodeAnalysis.Scripting you the selection of packages? If so you'll need to target Framework 4.6, which is minimal requirement of Scripting. Other Roslyn assemblies should work on 4.5.2 so that would be a bug.

**Comment by Suchiman** [comment]
@tmat In this screenshot, scripting wasn't actually involved, although it happens with scripting too. In this case, it's caused through Microsoft.CodeAnalysis.Common which has a dependency on "System.Collections.Immutable (>= 1.1.37)" which has a dependency on System.Runtime

**Comment by tmat** [comment]
@ericstj Does System.Collections.Immutable require FX 4.6?

**Comment by Suchiman** [comment]
@tmat *slowclaps for nuget* ok! upgrading to .NET 4.6 made it possible to upgrade the existing projects and also install scripting, thanks!

Although nuget says it wants to install several dependencies you usually only see on .NET Core (like System.Runtime), it actually doesn't add (most of them) to the csproj.
I wish it would be more obvious or reasonable explained why stuff turned so weird now with .NET Core...

**Comment by tmat** [comment]
This is very old issue and we made several releases since. Closing.
