### ISSUE TITLE
The `SyntaxGenerator` does not generate implicit conversion operators

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#65833]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

## Background and Motivation
The `SyntaxGenerator.Declaration(ISymbol symbol)` handles `SymbolKind.Method` with
* `MethodKind.Constructor`
* `MethodKind.SharedConstructor`
* `MethodKind.Ordinary`
* `MethodKind.UserDefinedOperator`

and not `MethodKind.Conversion` as a result the exception ArgumentException("Symbol cannot be converted to a declaration") is thrown. [SyntaxGenerator.cs#L575](https://github.com/dotnet/roslyn/blob/55259597ad41ac41e0d1888fa52a92e73318b57e/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L575)
Issue to track on our side: https://github.com/dotnet/arcade/issues/11848

Example:
```C#
public readonly partial struct Memory<T>
{
    public static implicit operator System.Memory<T> (T[] array) { throw null; }
}
```

## Proposed API

```diff
public SyntaxNode Declaration(ISymbol symbol)
{
/// ...
case SymbolKind.Method:
    var method = (IMethodSymbol)symbol;
    switch (method.MethodKind)
    {
        case MethodKind.Constructor:
        case MethodKind.SharedConstructor:
            return ConstructorDeclaration(method);

        case MethodKind.Ordinary:
            return MethodDeclaration(method);

        case MethodKind.UserDefinedOperator:
            return OperatorDeclaration(method);

+     case MethodKind.Conversion:
+         return ConversionOperatorDeclaration(method); // I didn't find existed function for that
    }
/// ...
}

+ public SyntaxNode ConversionOperatorDeclaration(IMethodSymbol method, IEnumerable<SyntaxNode>? statements = null)
+ { /*...*/ }
```

**Comment by CyrusNajmabadi** [comment]
Tentatively approving as this is an IDE only api and is just a basic ommision.  I'll bring through API review this week.  We'd accept a PR here if you want to make one @andriipatsula .

**Comment by 333fred** [comment]
## API Review

* Should we just make `OperatorDeclaration` handle conversions as well, as conversions are user-defined operators?
* Needs to be further investigated for consistency with existing methods. We'll review again at the next session if there is still any need for public api changes, instead of just implementation changes.
