### ISSUE TITLE
The `DeclarationModifiers` class does not properly handle `readonly` keyword for `struct` \s

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#65834]
**Version Used**: `main`

**Steps to Reproduce**:
Issue on our side: https://github.com/dotnet/arcade/issues/11850

[DeclarationModifiers.cs#L80](https://github.com/dotnet/roslyn/blob/55259597ad41ac41e0d1888fa52a92e73318b57e/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs#L80)

The initialization of isReadOnly in `DeclarationModifiers.From` must be extended in case ~ when ISymbol is type declaration.
```C#
public static DeclarationModifiers From(ISymbol symbol)
{
/// ...
    isReadOnly: field?.IsReadOnly == true || property?.IsReadOnly == true,
/// ...
```
`DeclarationModifiers.From(...)` is used not just for fields and properties and for `SymbolKind.NamedType` with `TypeKind.Class` and `TypeKind.Struct`: [SyntaxGenerator.cs#L612](https://github.com/dotnet/roslyn/blob/55259597ad41ac41e0d1888fa52a92e73318b57e/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L612)

```C#
namespace Foo
{
public readonly struct PublicReadonlyStruct { }
}
```
After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
```C#
namespace Foo
{
public struct PublicReadonlyStruct { }
}
```
**Diagnostic Id**:

**Expected Behavior**:

**Actual Behavior**:

**Comment by RikkiGibson** [comment]
It seems like we'd also want to check method?.IsReadOnly and type?.IsReadOnly.

**Comment by kinkeadian25** [comment]
@CyrusNajmabadi I will work on this if you want

**Comment by CyrusNajmabadi** [comment]
Go for it :-)

**Comment by kinkeadian25** [comment]
@CyrusNajmabadi and @Youssef1313, sorry going to work on this today! It has been an extremely busy week but have all the time in the world for roslyn now thankfully! Going to knock this out and work on anything else I can or you need from now on!
