### ISSUE TITLE
The `SyntaxGenerator` class omits `this` and `params` keyword for extension methods

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#65835]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

**Version Used**: 4.5.0-3.22601.3 (~main)

**Steps to Reproduce**:
Issuer on our side: https://github.com/dotnet/arcade/issues/11853
```C#
namespace Foo
{
    public static class MyExtensions
    {
        /// ! `this` keyword
        public static int WordCount(this string str) { return 42; }
        /// `params`
        public static void VariableNumberOfArguments(params object[] list) {}
    }
}
```
After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
```C#
namespace Foo
{
    public static class MyExtensions
    {
        /// `this` keyword is not generated
        public static int WordCount(string str) { }
        /// `params` keyword is not generated
        public static void VariableNumberOfArguments(object[] list) {}
    }
}
```

[sharplab link](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzggPgAQEwEYCwAUDBGAKYoAOEAxmQAQBiA9s0QN5H3f2YDMvXADZe2egFkAngFEAHgjIwUUZkq49OhHtvoB6ffQCE9AAYIAFlBQn6AazKSA7swBOAE3U7eAzMPqwEegB1VzcAYWYAVxgEAAoLK0EABno0FwBKenZeAHZ6ABZsAG56AF9PMqJSoA===)

**Diagnostic Id**:

N/A

**Expected Behavior**:
`WordCount(this string str) { }`
`public static void VariableNumberOfArguments(params object[] list) {}`

**Actual Behavior**:
`WordCount(string str) { }`
`public static void VariableNumberOfArguments(object[] list) {}`

**Comment by andriipatsula** [comment]
Similar (or the same) scenario related to variable number of parameters (param keyword)
```C#
public static class Test
{
    public static void VariableNumberOfArguments(params object[] list)
    {}
}
```
After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
```C#
public static class Test
{
    public static void VariableNumberOfArguments(object[] list)
    {}
}
```

**Comment by Youssef1313** [comment]
@andriipatsula What method(s) of `SyntaxGenerator` did you use?

**Comment by andriipatsula** [comment]
Hello @Youssef1313 . Thank you for a quick responce.
[SyntaxGenerator.cs#L551](https://github.com/dotnet/roslyn/blob/447c48956e16f4286db0a457840ab9f5dae1a17c/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L551)
