### ISSUE TITLE
GeneratedRegex Attribute Failed to generate code and shows CS8795 error

### ISSUE THREAD

**Issue by laolarou726** [dotnet/roslyn#65850]
**Version Used**: 

- Visual Studio 2022 17.4.2
- .NET 7.0.100

**Steps to Reproduce**:

1. Create a class with GeneratedRegex

```c#

private partial class Test{
    [GeneratedRegex("(\\d+\\.?\\d*|\\d*\\.?\\d+)")]
    private static partial Regex DecimalRegex();
}

```

2. The error will shows

<img width="793" alt="image" src="https://user-images.githubusercontent.com/25716486/206314271-f35094d8-1ce0-4fb7-80a4-1dcfa9719e86.png">

<img width="262" alt="image" src="https://user-images.githubusercontent.com/25716486/206314439-291d2995-d672-4501-95ea-7f81d59f0ae4.png">

SourceGenerator does not generate anything.

**Diagnostic Id**:

CS8795

**Comment by jasonmalinowski** [comment]
This doesn't reproduce in 17.5.0 Preview 2.0; we'd be hearing pretty loudly if we broke this generally. @laolarou726 any idea if there's something special with your setup, or was that screenshot from a larger project where there might be some extra things impacting it?

**Comment by laolarou726** [comment]
> This doesn't reproduce in 17.5.0 Preview 2.0; we'd be hearing pretty loudly if we broke this generally. @laolarou726 any idea if there's something special with your setup, or was that screenshot from a larger project where there might be some extra things impacting it?

I think this bug is randomly happening to me. Sometime I need close Visual Studio and open again then the problem will resolve.

**Comment by jasonmalinowski** [comment]
If you get to the point where you have the squiggle, if you click on the method name and invoke Go to Definition, what happens? The request may seem odd since it seems like it shouldn't work if there's a squiggle at all, but it's possible a few different systems are out of sync here.

**Comment by laolarou726** [comment]
> If you get to the point where you have the squiggle, if you click on the method name and invoke Go to Definition, what happens? The request may seem odd since it seems like it shouldn't work if there's a squiggle at all, but it's possible a few different systems are out of sync here.

Sometimes it will jump to the right definition. But VS still shows error there.

**Comment by cheenamalhotra** [comment]
This is happening in VS 2022 as well in .NET 7.0 projects.

Microsoft Visual Studio Enterprise 2022
Version 17.6.0 Preview 2.0
VisualStudio.17.Preview/17.6.0-pre.2.0+33513.286
Microsoft .NET Framework
Version 4.8.09032

**Comment by onionhammer** [comment]
Same thing happening in VS Code with C# dev kit (not omnisharp), using Riok.Mappery

![image](https://github.com/dotnet/roslyn/assets/969938/6d9f5b37-95dc-4197-a62e-f11fc5ef1789)

**Comment by sharwell** [comment]
@onionhammer This issue is also specific to Visual Studio (not VS Code). Can you file a new issue for the behavior you observed?

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this in a while and we've basically rewritten all the SG code in the ide.
