### ISSUE TITLE
Negated is-expression doesn't work with list patterns

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#65876]
Should adjust GetDecisionDagForLowering to use the inner pattern.

https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsBmAAl3IGFyBvY8pyvANkoBZyBZaGcgBQBKco2YMizKSwCcA7gA8BMAKYB3ANoBdOnjg4AvkKEBuMdNnylqzTpxw8R0+elY8cxcvXbdTs5ItRAIs3Dy9bXX0/FylQ+XCfe0djf0DLbgSdZOdg8gMXFzIWdmAAe1KAGx4BWARtCBEJNKwAdnIIcigAZ3IYUoRBDT17ADoRrXJS5HINMf0HCamZvC0cqXzcorcS8qrPWvrGmOZW8gBCAQ7upgEh+bHF6dmR+ZXJp5WUlw2DIA==

**Comment by AlekseyTs** [comment]
@alrz Links to SharpLab a always welcome. However, a bug report must include a clear description of the issue in the issue (what happens if SharpLab goes down for one reason or another?):
- a repro code
- observed
- expected
- possibly an explanation for the expectations

**Comment by jcouv** [comment]
In short, in the sharplab repro (copied below) `return a is not ([1,2,..] or [..,2,1] or [1]);` and `return !(a is  ([1,2,..] or [..,2,1] or [1]));` should behave the same, but they don't.

```
using System;
public class C {
    static void Main () 
    {
        Console.WriteLine(Mx(new[]{1,2}));
        Console.WriteLine(Mx(new[]{2,1}));
        Console.WriteLine(Mx(new[]{1}));
        
        Console.WriteLine(M(new[]{1,2}));
        Console.WriteLine(M(new[]{2,1}));
        Console.WriteLine(M(new[]{1}));
    }
    
    public static bool M(int[]a) {
        return a is not ([1,2,..] or [..,2,1] or [1]);
    }
    public static bool Mx(int[]a) {
        return !(a is  ([1,2,..] or [..,2,1] or [1]));
    }
}
```
