### ISSUE TITLE
Add Imports not offered after first submission

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6587]
1. `#r "System.Xml"`
2. `typeof(ArrayList)`

Expected: Lightbulb offering to import `System.Collections`
Actual: No lightbulb

**Comment by amcasey** [comment]
Note that it works before the `#r` and it resumes working after `#reset`.

**Comment by amcasey** [comment]
FYI @kuhlenh @ManishJayaswal @jmarolf @tmat

**Comment by amcasey** [comment]
The compilation in which we are looking for the symbol has 45 `ReferencedAssemblyNames` but 0 `References`.

**Comment by amcasey** [comment]
The underlying reference manager has 0 `DirectiveReferences`, 39 `ImplicitReferences`, and 7 `ExplicitReferences`.

**Comment by amcasey** [comment]
The compilation has 0 `ExternalReferences` - that seems to be what's getting dropped.

**Comment by amcasey** [comment]
Since the intention of `Compilation.References` seems to be to return references explicitly added via either compilation options or `#r`, it seems strange that it isn't just returning `GetBoundReferenceManager().ExplicitReferences`.  There doesn't seem to be a performance advantage since retrieving the `DirectiveReferences` triggers binding of the reference manager anyway.

**Comment by amcasey** [comment]
That change appears to have fixed this particular issue.  I'll run the tests to try to figure out what it breaks.

**Comment by tmat** [comment]
I introduced ExplicitReferences just recently, for ask mode, so I haven't had a chance to do more cleanup, which would indeed be nice.

**Comment by amcasey** [comment]
Unit tests are green on my box.  Shall I create a PR?

**Comment by ManishJayaswal** [comment]
@tmat let's investigate the fix here. We should take this fix to shiproom - ideally tomorrow at 1p

**Comment by amcasey** [comment]
To be explicit: I'm pretty sure my change is just masking the problem.

**Comment by amcasey** [comment]
I'll keep investigating, but this really needs @tmat's input.

**Comment by tmat** [comment]
Looking

**Comment by amcasey** [comment]
@tmat pointed out that it doesn't just fail after `#r` - it fails anywhere other than the first submission after a reset.

**Comment by amcasey** [comment]
Please unskip the flagged IDE test when this is fixed.

**Comment by amcasey** [comment]
Does the scenario described in this issue work now?  Or has it become moot?
