### ISSUE TITLE
Shift core projects from netcore3.1 to net6.0

### ISSUE THREAD

**Issue by sanmuru** [dotnet/roslyn#65905]
## Background and Motivation
According to [.NET Lifecycle](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core), .NET Core 3.1 is going to be out of date. Is it the time to shift to the next LTS runtime version?
And then, something personal, it is annoying to receive CS0433 that `MemberNotNullAttribute` and some other types are in both `Microsoft.CodeAnalysis` and `System.Runtime`(Version 6.0).

## Proposed Change
```diff
-<TargetFrameworks>netcoreapp3.1;netstandard2.0</TargetFrameworks>
+<TargetFrameworks>net6.0;netstandard2.0</TargetFrameworks>
```

## Risks
To core projects: No
To test projects: Not tested

**Comment by svick** [comment]
[As far as I can tell](https://www.fuget.org/packages/Microsoft.CodeAnalysis.Common/4.4.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.dll/System.Diagnostics.CodeAnalysis/MemberNotNullAttribute?code=true), the `MemberNotNullAttribute` that's in `Microsoft.CodeAnalysis.dll` is `internal`, so that shouldn't be causing any errors. (Unless you're doing something weird, like using `IgnoresAccessChecksTo`.)

**Comment by sanmuru** [comment]
> [As far as I can tell](https://www.fuget.org/packages/Microsoft.CodeAnalysis.Common/4.4.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.dll/System.Diagnostics.CodeAnalysis/MemberNotNullAttribute?code=true), the `MemberNotNullAttribute` that's in `Microsoft.CodeAnalysis.dll` is `internal`, so that shouldn't be causing any errors. (Unless you're doing something weird, like using `IgnoresAccessChecksTo`.)

Yes, you are right. I did use `IgnoresAccessChecksTo`, but for some reasons.
I created a fork of Roslyn early of this year, added projects supporting for other languages, and soon found it too laggy to build the whole solution since there were so many C# and VB projects that are actually not needed.
Then I deleted those C# and VB things and here came the nightmare. It was rather painful to deal with git conflicts since I deleted and modified so many files. I struggled and wasted mush time and effort to keep matching upstream repository till I could not stand it any more.
I created a new fork of Roslyn, maked it support accessing internals in certain assemblies by specifying them via new compiler options, and of course an embedded IgnoreAccessChecksTo attribute.
Now I am doing my work base on the new compiler toolset, I no need to worry about everyday changes in this repository, I only need to update `Microsoft.CodeAnalysis.Common` package version.
BTW, `InternalsVisibleTo` in `Microsoft.CodeAnalysis` project still cause CS0433.

**Comment by svick** [comment]
I empathize, since I was in similar situations before (in one I used IACT to Roslyn, another was a fork of Roslyn), but I don't think Roslyn should make changes just because of such niche and unsupported use cases.

On the other hand, the request to stop supporting an unsupported runtime sounds reasonable to me.

**Comment by sanmuru** [comment]
Yeah, that's why my case 'personal' LOL.

**Comment by jaredpar** [comment]
> According to [.NET Lifecycle](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core), .NET Core 3.1 is going to be out of date.

There is a difference between compiling a library for a target framework and running on that target framework. Compiling a library for an existing target framework is supported even when that target framework goes out of service. So `netcoreapp3.1` moving out of service doesn't invalidate how our libraries are compiled. 

It would be a problem if our applications targeted `netcoreapp3.1` but they do not. Instead they target `net6.0`. 

> Is it the time to shift to the next LTS runtime version?

There are a lot of constraints that influence the target framework that we use in our libraries. The Roslyn compiler is first and foremost a library and it can be hosted in a large variety of environments. When we move to a new target framework it forces all of those hosted environments to move forward as well. That is not a problem for most consumers but we do have projects, like Visual Studio, for whom moving to a new target framework is a significant event. 

The other constraints are hard to articulate. But essentially moving forward will change performance characteristics of our code and that takes a bit of time to settle across our Visual Studio insertion points. 

Taken together moving to a new target framework is not a case of flip the target framework, compile, merge and move on. Instead it requires coordination between a number of parties and usually a bit of follow up work to deal with unexpected fallout of the change. 

I do think we will move to `net6.0` in the near future though. There are other .NET 8 incentives pushing us in this direction. But it won't happen just at this moment.
