### ISSUE TITLE
C# compiler erroneously allows declarations of abstract members in a struct

### ISSUE THREAD

**Issue by noblethrasher** [dotnet/roslyn#6590]
The following code compiles, but should  not:

    struct Foo
    {
        public abstract void Bar();
    }

    new Foo().Bar() //TypeLoadException at runtime: 'Abstract method in non-abstract class.'

**Comment by Sebazzz** [comment]
Can confirm this in C# compiler version 1.0.0.50618 (Visual Studio 2015 RTM).

**Comment by bbarry** [comment]
Confirming the following program compiles with VS2015 RTM but does not compile with VS2012 Update 4:

    namespace ConsoleApplication12 {
        internal struct Foo {
            public abstract void Bar();
        }
        internal class Program {
            private static void Main(string[] args) { new Foo().Bar(); }
        }
    }

**Comment by leppie** [comment]
Another case that compiles:
```
struct Foo {  public abstract int Baz { get; set; } }
```
