### ISSUE TITLE
`AsPublicInterfaceImplementation` doesn't handle expression-bodied correctly.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65931]
```csharp
public interface IGeneral
{
    object DoSomething();
}

public class C : IGeneral
{
    object IGeneral.DoSomething() => new();
}
```

Call `AsPublicInterfaceImplementation` on the explicit implementation above. It produces:

![image](https://user-images.githubusercontent.com/31348972/206969587-8fe75347-c5b5-4ec8-b1b2-f401a2f3c633.png)

The following code should check for ExpressionBody

https://github.com/dotnet/roslyn/blob/683e22d4a2351e5495e18fbb2f7089f2f1a9679d/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L581-L619

Accessors should be fixed too.

**Comment by kinkeadian25** [comment]
I will work on this issue!
