### ISSUE TITLE
Capturing wrong variable in a local static function by using an extension method

### ISSUE THREAD

**Issue by thecristidima** [dotnet/roslyn#65938]
**Version Used**: C#11; main (30 Nov 2022) on sharplab;

**Steps to Reproduce**:

Run the following code using `<LangVersion>latest</LangVersion>` or `<LangVersion>11.0</LangVersion>`: https://sharplab.io/#gist:b2eb10fdce4d06159c10ca727b7f5ccb

**Diagnostic Id**: -

**Expected Behavior**: The output should be:
```
Anna: Anna
Billy: Billy
```

**Actual Behavior**:
```
Anna: Anna
Billy: Anna
```

This problem happens for `LangVersion` 11.0 (or latest at the time of writing). Switching to an older version will behave as expected.

This problem doesn't happen if we make any of the following changes:

- Remove `static` from `Foo(int)`'s declaration
- Change `Select(Foo)` to `Select(x => Foo(x))`

**Comment by Youssef1313** [comment]
Works as expected in C# 10 but not in C# 11.
Likely a regression from cached method groups feature.

**Comment by jaredpar** [comment]
```csharp
OutputClass[] Test(Person person)
{
    var arr = new int[] { 1 };
    return arr.Select(Foo).ToArray();

    static OutputClass Foo(int i)
    {
        return new OutputClass(person.GetName);
    }
}
```

The bug here seems to be that this compiles at all. This is a `static` local function it should not be able to capture `person` at all. That seems like the bug. Guessing that our capture check in `static` local functions is missing method group conversions. 

@cston

**Comment by Youssef1313** [comment]
Makes sense. Thanks @jaredpar.

I opened #65965. The check was missing for method groups where the method is extension method.
