### ISSUE TITLE
VB Code gen optimization: Use `Array.Empty<T>()` for `Dim x(-1) As T`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65933]
```vb
Public Class C
    Public Sub M()
        Dim x(-1) As String
    End Sub
End Class
```

Currently generates:

```cs
    .method public 
        instance void M () cil managed 
    {
        // Method begins at RVA 0x2058
        // Code size 8 (0x8)
        .maxstack 8

        IL_0000: ldc.i4.0
        IL_0001: newarr [System.Runtime]System.String
        IL_0006: pop
        IL_0007: ret
    } // end of method C::M
```

I think it could produce `Array.Empty<T>()`?

**Comment by jaredpar** [comment]
I agree it likely could compile to `Array.Empty<T>`. However I do not think we should do this. 

The benefits are likely not that great as I don't think this is very common in VB. Further it's not consequence free as it could break code that depended on the return value being different on every invocation. As such I would not move forward with this.
