### ISSUE TITLE
LSP pull diagnostics performance issues in squiggles + error list

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#65935]
**Version Used**: Latest internal 17.5 dogfood build

**Steps to Reproduce**:

Ensure pull diagnostics is enabled:

![image](https://user-images.githubusercontent.com/10605811/207006293-249c07fd-ffc7-4b53-aa27-2e7b7bf335d5.png)

1. Build the release version of the latest Roslyn bits from main branch (`build -Configuration Release`)
2. Install RoslynDeployment.Vsix generated by the above steps
3. Open Roslyn.sln
4. Open `Binder_Expression.cs` and go to the below line: https://github.com/dotnet/roslyn/blob/683e22d4a2351e5495e18fbb2f7089f2f1a9679d/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L342
5. Repeatedly remove and add back the semi-colon at the end of the statement - basically introduce and fix a compiler syntax error

## Expected behavior
Compiler syntax errors are refreshed quickly both in the error list and the squiggles in the editor

## Actual behavior - LSP pull diagnostics enabled + analyzers enabled for current document
Compiler syntax errors are very slow to refresh, both error list and squiggles.

![LspPullDiagnostics_AnalyzersEnabled](https://user-images.githubusercontent.com/10605811/207008217-4558f591-048d-4958-904d-3d1d4ed97ea1.gif)

The above experience is with both analyzer and compiler diagnostics enabled for current document with LSP pull diagnostics.

## Actual behavior - LSP pull diagnostics enabled + analyzers disabled
Now disable the analyzer diagnostics completely by changing the `Run background analysis for:` option to `None`:

![image](https://user-images.githubusercontent.com/10605811/207008834-8f430638-456c-4ce5-ba5c-28162712c414.png)

Repeat the step 5. in the repro steps above, i.e. removing and adding the compiler syntax error. You can see that both the error list and squiggles refresh comparatively much quickly now (though the refresh should ideally be still faster):
![LspPullDiagnostics_AnalyzersDisabled](https://user-images.githubusercontent.com/10605811/207009929-76daf55b-1682-4c7a-852e-5ff9a8bf0a7c.gif)

## Actual behavior - LSP pull diagnostics disabled + analyzers enabled for current document
Now re-enable the analyzer diagnostics again by setting `Run background analysis for:` option to `Current Document` and also disabling LSP pull diagnostics + closing and restarting VS:

![image](https://user-images.githubusercontent.com/10605811/207010433-42e539e6-b6fc-4c3a-a243-7de450afac6a.png)

Repeat the step 5. in the repro steps above, i.e. removing and adding the compiler syntax error. Notice that with LSP pull diagnostics disabled, both error list and squiggles refresh extremely quickly now, even with analyzer diagnostics enabled for current document (default option value):

![LspPullDiagnosticsDisabled_AnalyzersEnabled](https://user-images.githubusercontent.com/10605811/207011338-769a7db4-ebe5-4e58-877b-83947fe22b60.gif)

## Conclusion
Error list + squiggles refresh in LSP pull diagnostics mode seems to be done only after all the compiler and analyzer syntax and semantic diagnostics have finished computing. This leads to extremely slow refresh in the default background analysis mode for compiler + analyzer diagnostics. The refresh rate for compiler syntax errors improves when analyzers are completely disabled, but still slow as it still seems to be waiting for compiler semantic diagnostics to be re-computed after the edit. When LSP pull diagnostics is disabled, compiler syntax errors seems to refresh first before any compiler semantic or all analyzer diagnostics are computed, making the experience way better. IMO, we cannot ship with LSP pull diagnostics enabled by default unless we can match the refresh rate in non-LSP pull diagnostics mode for compiler syntax errors.

**Comment by mavasani** [comment]
@CyrusNajmabadi @dibarbet @arkalyanms - I believe this performance issue for slow refresh rate of compiler syntax errors should be considered as a blocker for shipping with LSP pull diagnostics enabled by default.

**Comment by CyrusNajmabadi** [comment]
LSP pull is not enabled but default. And @dibarbet is working with platform on supporting diagnostic categories.

**Comment by CyrusNajmabadi** [comment]
I'm not sure why this is assigned to me.

**Comment by mavasani** [comment]
I am no longer able to repro this performance problem with LSP pull diagnostics enabled. Closing.
