### ISSUE TITLE
`throw` in switch expressions doesn't parse properly

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#65934]
```csharp
using System;
using System.IO;

class C
{
    bool M()
    {
        try
        {
            return true;
        }
        catch (Exception e)
        {
            return e switch
            {
                IOException => false,
                _ => throw, // error. `throw e` doesn't error.
            };
        }
    }
}
```

**Comment by Youssef1313** [comment]
This might be by-design on compiler side. If so, I can open an issue/discussion on csharplang if you think this can move forward.

**Comment by jaredpar** [comment]
@Youssef1313 this is by design. The `throw` expression feature only allows for the `throw e` form, not `throw`. 

https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.0/throw-expression.md
