### ISSUE TITLE
VisualStudioWorkspaceDiagnosticAnalyzerProviderService throws NRE when initializing interactive window

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#6594]
During the composition of the interactive window, a null ref exception is thrown [here](https://github.com/dotnet/roslyn/blob/stabilization/src/VisualStudio/Core/Def/Implementation/Diagnostics/VisualStudioWorkspaceDiagnosticAnalyzerProviderService.cs#L145) Condider using ?. instead of using a catch all

**Comment by amcasey** [comment]
We've been having lots of issues with this on developers' boxes, so it would be nice to understand what's going on.

**Comment by amcasey** [comment]
FYI @ManishJayaswal

**Comment by amcasey** [comment]
It looks like this can only happen if we can't find the `ShellFolder` property on the extension manager.

**Comment by amcasey** [comment]
Static type: `Microsoft.VisualStudio.ExtensionManager.IVsExtensionManager`
Runtime type: `Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService`

**Comment by amcasey** [comment]
Actual properties are `DidLoadUserExtensions`, `HasExtensionsAutoUpdated`, and `RestartRequired`.

**Comment by amcasey** [comment]
I'm not convinced this is the actual exception causing the package load, since there's a catch on the next line.

**Comment by jmarolf** [comment]
updated this bug.  The service does not fail to initialize, I misread my package load failure list.

**Comment by cston** [comment]
Fixed in #6599.

**Comment by Pilchie** [comment]
+ @heejaechang

**Comment by heejaechang** [comment]
@cston thank you for fixing the null exception.

this is unfortunate one that we need update 1 drop to use new API editor team added.
