### ISSUE TITLE
Rank AsyncCompletionSessionDataSnapshot.Defaults over IntelliCode starred suggestions

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#65982]
We have a scenario where I think we are correctly setting the default of the AsyncCompletionSessionDataSnapshot but IntelliSense is not selecting the desired item. It looks like the problem is that the default isn't being selected because it is not in the list of starred completion items (which are displayed at the top of the list).

Cyrus, Mark and I have discussed this and the preferred behavior would be:

1. If the gray text matches something in the starred completion list, select that.
2. Otherwise, if the gray text matches something elsewhere in the completion list, star that item and place in the starred section, and select it.
3. Otherwise, ignore the gray text and select the 1st thing in the starred completion list.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, we need to assign to a milestone and actually do this. It will not get done int he backlog.
