### ISSUE TITLE
Source generators in multi-targeted project being loaded twice

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#65996]
**Version Used**: 17.4.3, 17.5.0 Preview 3.0 [33213.424.main]

**Steps to Reproduce**:

1. Reference the MVVM Toolkit 8.1.0-preview2
2. ...? Try using it in a project that also references a library using the MVVM Toolkit? It's not entirely clear to me what the exact repro steps are, but I'm seeing a bunch of reports of similar issues from users of the MVVM Toolkit in several scenarios (eg. https://github.com/CommunityToolkit/dotnet/issues/495)

> **Note**: by multi-targeting I mean the MVVM Toolkit generators that are multi-targeting Roslyn 4.0 and 4.3

This completely broke the Microsoft Store solution as well, so I could use some help 😅

I can also help folks checkout in the repo if needed, otherwise there might be a small public one in the linked issue.

cc. @sharwell @chsienki help? 🥲

I'm clearly seeing analyzers being loaded twice:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/10199417/207469661-f5a1aaab-dfad-4402-a6d4-b3508fa4caf4.png">

I'm also seeing a bunch of random errors from other analyzers crashing (not from the MVVM Toolkit).
Not entirely sure whether it's related. For instance:

```
StreamJsonRpc.RemoteInvocationException: An element with the same key but a different value already exists. Key: '(DocumentId, #28831a34-a993-7077-19bf-b4a7d74f060e - __IMessengerExtensions.g.cs)'
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17.MoveNext()
RPC server exception:
System.ArgumentException: An element with the same key but a different value already exists. Key: '(DocumentId, #28831a34-a993-7077-19bf-b4a7d74f060e - __IMessengerExtensions.g.cs)'
      at System.Collections.Immutable.ImmutableSortedDictionary`2.FillFromEmpty(IEnumerable`1 items, Boolean overwriteOnCollision)
      at System.Collections.Immutable.ImmutableSortedDictionary`2.AddRange(IEnumerable`1 items, Boolean overwriteOnCollision, Boolean avoidToSortedMap)
      at System.Collections.Immutable.ImmutableSortedDictionary.ToImmutableSortedDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IComparer`1 keyComparer)
      at Microsoft.CodeAnalysis.TextDocumentStates`1..ctor(IEnumerable`1 states)
      at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__40.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10199417/207471678-6cfa8617-66a0-4ae0-a186-6f79d7524161.png">

**Comment by Sergio0694** [comment]
I have no idea what's going on but it seems literally everything is broken 🤣

![image](https://user-images.githubusercontent.com/10199417/207478632-2fde5028-0098-47d0-88f6-e3a6059c3565.png)

**Comment by Sergio0694** [comment]
@CyrusNajmabadi I just tried with Version 17.5.0 Preview 3.0 [33213.424.main] and while I no longer see duplicated generators in the solution explorer, I'm still seeing a whole bunch of errors about duplicated members being generated. Should I be worried? I'm not sure where that fix was merged into exactly, is this VS preview version supposed to have it already? The Store solution is pretty broken right now given this 🥲

**Comment by Sergio0694** [comment]
Ok that's not actually true, I do still see analyzers twice

![](https://user-images.githubusercontent.com/10199417/207733460-32f8b3d5-b14c-4e4b-8465-ba05ee4d4abf.png)

**Comment by Sergio0694** [comment]
Also cc. @jasonmalinowski. For context, this currently has completely broken the MVVM Toolkit 8.1 in the Store solution (and I saw other folks reporting issues as well). If this is broken both on 17.4.3 and 17.5 (but really even if it was just broken on 17.4.3) it's basically a blocker for our next release of the .NET Community Toolkit. Is there a chance we could get some help on this?
Thank you! 🙂

**Comment by sharwell** [comment]
The legacy project targets don't support Roslyn Component Versioning, so they just load everything under the analyzers node.

**Comment by Sergio0694** [comment]
@sharwell This is a major issue for us, as we need to keep supporting 4.0 but also want the performance of FAWMN when available, and have a lot of customers (including us in the Store team) using non-SDK-style projects.

Is there a way to check whether the legacy .csproj is being used from the .targets we ship in the MVVM Toolkit, so we can just delete the extra analyzer from there?
