### ISSUE TITLE
Change encoding on files to be "git compatible"

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#66]
Git think some of .cs files are binary because they use "UCS-2 Little Endian"(according to Notepad++):
![image](https://cloud.githubusercontent.com/assets/774791/5888789/432c5b7a-a40d-11e4-9138-8ec2efafb212.png)

If I convert file to UTF8 git applications start displaying this files as text file(diff works).
Without this change pull requests look like this: https://github.com/dotnet/roslyn/pull/65/files

I think some tool should be used to convert all files to UTF8.

**Comment by jaredpar** [comment]
That does look incorrect.  I will take a look at that.

**Comment by jaredpar** [comment]
Note it appears the encoding of the files is actually UTF-16LE.  This is the value reported by the [Mozilla Universal Char Detector](https://www.nuget.org/packages/UDE.CSharp).  Notepad++ appears to have a [bug](http://programmers.stackexchange.com/a/187174/278) which causes this to be reported as UCS-2LE. 

Either way should be switched to UTF-8.

**Comment by MattGertz** [comment]
Marking as verified as no new cases reported.
