### ISSUE TITLE
Find all references for preprocessor symbol does not yield any results

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#66009]
## Summary

Find all references could also yield results for the selected preprocessor symbol

## Background and Motivation

Oftentimes custom configurations are being used, which include conditional preprocessor symbols, like `DEV_DEBUG` or `DEV_INTERNAL`, which are used in `#if` directives. Additionally, the `DEBUG` and `TRACE` symbols are defined in debug configurations on their own almost always, which come in handy in many applications.

## Proposed Feature

When using "find all references" I should be able to see all the places that I'm using the selected preprocessor symbol. For example, when I hover over the `DEBUG` symbol in the `#if DEBUG` directive, I should be able to see all the places that the `DEBUG` symbol is used. The behavior should also mind for the file-defined preprocessor symbols.

**Comment by CyrusNajmabadi** [comment]
@Rekkonnect We'd likely takea  PR here if you wanted to contribute it.
