### ISSUE TITLE
"Go To Implementation" doesn't find all implementations

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#66008]
**Version Used**: 

Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.5.0 Preview 3.0 [33206.467.main]

**Steps to Reproduce**:

In Roslyn solution
1. Go to the definition of abstract property ```Microsoft.CodeAnalysis.CSharp.Syntax.BaseExpressionColonSyntax.Expression``` in Syntax.xml.Syntax.Generated.cs
2. Right click and select "Go To Implementation"

**Expected Behavior**:

Two implementations found, in ```ExpressionColonSyntax``` and in ```NameColonSyntax``` types.

**Actual Behavior**:

Only implementation in ```ExpressionColonSyntax``` is found.

I am not sure if the fact that implementation in ```NameColonSyntax``` type is not in a generated file makes any difference for the scenario.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski I don't even see this command offered in that file:

![image](https://user-images.githubusercontent.com/4564579/207667505-0734a492-60f6-47a5-952d-7857d6e8294b.png)

Something broken with SG files?

**Comment by jasonmalinowski** [comment]
Turn this back on:

![image](https://user-images.githubusercontent.com/201340/207704641-960f1a72-f64d-44c3-8560-d6a4d5cd8121.png)

(this is the feature flag we're flipping back, so by the time you investigate this it might be back on)
