### ISSUE TITLE
IDE2001 codefix is offered but does nothing

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66017]
![image](https://user-images.githubusercontent.com/31348972/207704989-3393c4c9-f4a3-4630-8e93-61569b164e9c.png)

The scenario above is a switch *statement* with a trailing `;` (the `;` here is empty statement and should really be removed).

The codefix doesn't do anything. It should probably attempt to move the `;` to its own line.

Repro: https://github.com/dotnet/roslyn-analyzers/blob/aef515f9955c81491bab8f3ac854915a92f2fc15/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHash.cs#L237-L251

**Comment by CyrusNajmabadi** [comment]
I'm surprised this feature triggered here.  it's not an embedded statement.  So i'm not sure why the analyzer fired.
