### ISSUE TITLE
When performing a 'Fix All' code fix, we should show progress.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6601]
This is especially important when doing a 'solution wide' fix all.  We should at least have progress saying how far along we are with project granularity.  Having document granularity would be even better.

Right now these operations can take a _loooong_ time, and you have no idea how far along they are.

**Comment by Pilchie** [comment]
From #8211, some good suggestions:

> Hi.
> When I run any changes from code-cracker or any other analyzer via BatchFixAllProvider for the whole solution.. 
> First in the last step it is blocking operation on UI thread of VS so it gives me [Not Responding] and Second could there be some more verbosity? Like:
> 
> Searching solution to apply change: {change description} A of N files searched, found B occurences
> Then there is a preview window and after hitting Apply
> Applying changes: C of D changes applied It would be so awesome. Thanks, regards.

**Comment by CyrusNajmabadi** [comment]
I agree.  The issue blocking this was that the editor dialog was not something we could update from the background thread that we're processing on.  The editor has made the UI updatable from the background, so we can do this now.

**Comment by CyrusNajmabadi** [comment]
However, this will only work on update2 or later once we take on this work.  If we want our code to run downlevel, we'll have to do some sort of detection to know what version of the Editor we're on so we can tell if it's safe to update the dialog from the background.

**Comment by Pilchie** [comment]
@CyrusNajmabadi Should this be resolved now?

**Comment by CyrusNajmabadi** [comment]
Closing out.  this has been done.
