### ISSUE TITLE
Missing space character in auto completed new statement for a C# array

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-space-character-in-auto-complete/10230430)._

---
When entering the following code in a C# code file:
**double[] x = new**
the expected dropdown with possible types suggesting 'double' appears, when hitting the space bar to add a white space after 'new'. 
But if you continue the input by selecting 'double' (for example via the 'down' key) and proceed with typing '[' to enter the size of the new array, the editor will remove the white space between 'new' and 'double' turning the code into:
**double[] x = newdouble[**
If the selection 'double' from the dropdown is confirmed (pressing enter or tab) before entering '[' the editor behaves as expected.

---
#### Feedback Bot on 12/15/2022, 00:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as not repro.
