### ISSUE TITLE
'non-nullable field is uninitialized' inspection for backing field of required property

### ISSUE THREAD

**Issue by ArdorDeosis** [dotnet/roslyn#66055]
**Version Used**:    '4.4.0-6.22565.8 (53091686)'. Language version: latest (11.0).

**Steps to Reproduce**:

Have the following code snippet:
```csharp
internal class ReproductionClass
{
  private readonly string name;

  internal required string Name
  {
    get => name;
    init => name = value;
  }
}
```
[sharplab](https://sharplab.io/#v2:CYLg1APglgdgLgUwE4wIYBsAEABATJgJQQAckB7YAVwGM4oyYBhdVAZ1YFgAoAb280ykoAN1SJMSBKmAN0ATxwBGAAyY0AWwQBubv0yxEKDBIQBHSlEnAlqgHKpNevlwECA5gjiYAvAD41Dtp6ArBQXn4Bmj6YouiUQS6YAL7cSUA===)

**Expected Behavior**:
I would expect no such warning since the field is set in a required init-only setter.

**Actual Behavior**:
"Non-nullable field 'name' is uninitialized. Consider declaring the field as nullable." warning on the name backing field

**Comment by jaredpar** [comment]
@333fred PTAL

**Comment by 333fred** [comment]
This is by-design. With https://github.com/dotnet/roslyn/pull/65987, you can put `MemberNotNull` on the initer and the warning will go away. [sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAOgBEoIBzGAewGcAXKAY2oIGFKEBTAQRggBsAntSjUA3AFgAUFNi0OAJ159cAJmwAlDgAd57AK4N6lGCz4Rq1KQG8p2bDqgA3CHOzyOEBMcG48OXmAcEtKSdrIKSm4cAI56UO4IvjgAchCBttg2oXbYZBy02AC8AHzYAUEZdgDaALIcYMAKyZS0yXp8fAAU5ZQAZt1pHACUQwC6ldiwUAUlZYNF2M58ehXZAL5Sa0A).
