### ISSUE TITLE
Analyzer config discovery doesn't work when all source files are generated

### ISSUE THREAD

**Issue by aelij** [dotnet/roslyn#66051]
**Version Used**: .NET SDK 7.0.101

**Steps to Reproduce**:

1. Create a project file:
   ```xml
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net70</TargetFramework>
        <OutputType>exe</OutputType>
      </PropertyGroup>
      <Target Name="GenerateBeforeBuild" BeforeTargets="BeforeCompile">
        <ItemGroup>
          <Compile Remove="Generated/**/*.cs" />
        </ItemGroup>
        <WriteLinesToFile File="Generated/Program.cs" Lines="await System.Threading.Tasks.Task.CompletedTask%3b" Overwrite="true" />
        <ItemGroup>
          <Compile Include="Generated/**/*.cs" />
        </ItemGroup>
      </Target>
    </Project>
   ```
2. Create an EditorConfig file:
   ```ini
   [*.cs]
   dotnet_diagnostic.CA2007.severity = error
   ```
3. `dotnet build` twice

**Expected Behavior**:

Both builds fail.

**Actual Behavior**:

Only the second build fails (after a .cs file exists).

**Analysis**:

I believe the problem is that the following is evaluated during the initial project evaluation and not within a target:

https://github.com/dotnet/roslyn/blob/dc57983861812e197fc2c0f78996c2d70e0670b4/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L130-L139

This means that if there are no `Compile` items at this point, analyzer config files won't be added.

**Comment by aelij** [comment]
@mavasani can you please triage this bug?

**Comment by mavasani** [comment]
@chsienki

**Comment by jcouv** [comment]
When the editor config discovery is not sufficient for a scenario, the fallback is to specify the editor config files (see below). Also, editor config is primarily meant for user-provided source files, as analyzers on generated source files would not be actionable.
So I don't think we're going to change editor config discovery to accommodate such edge case scenarios.

```
   <PropertyGroup>
     <TargetFramework>net70</TargetFramework>
     <OutputType>exe</OutputType>
     <DiscoverEditorConfigFiles>false</DiscoverEditorConfigFiles>
   </PropertyGroup>
   <ItemGroup>
    <EditorConfigFiles Include=".editorconfig" />
   </ItemGroup>
```

**Comment by aelij** [comment]
@jcouv isn't this a simple matter of moving the `ItemGroup` into a target?
