### ISSUE TITLE
Selenium WebDriver for .Net 6.0 do`nt starts  in C# Interactive

### ISSUE THREAD

**Issue by AleksandrEfimov** [dotnet/roslyn#66066]
Hello!
**Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.3

**Steps to Reproduce**:

1. Open VS C# Interactiv 
2. Load required dll:
[WebDriverNet6.0.zip](https://github.com/dotnet/roslyn/files/10263362/WebDriverNet6.0.zip)
Or from links:
https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/
https://www.nuget.org/packages/Selenium.WebDriver
https://www.nuget.org/packages/Selenium.Support
(In last Release WD declared about support .Net 6.0)

a)
```
 #r "C:\Users\po\Downloads\selenium.webdriver.4.7.0\lib\net6.0\WebDriver.dll"
 #r "C:\Users\po\Downloads\selenium.support.4.7.0\lib\net6.0\WebDriver.Support.dll"
```
b)
```using OpenQA.Selenium.Support;
. using OpenQA.Selenium.Support.UI;
. using OpenQA.Selenium.Chrome;
. using OpenQA.Selenium;
```
3. 
Create ChromeDriver instance:
```
IWebDriver wd = new ChromeDriver("path_to_exe");
```
**Expected Behavior**:
I got driver instance and ran browser. 
The WebDriver.dll for .NetFramework 4.8 gets this result:
```
> #r "C:\Users\pozii\Downloads\selenium.webdriver.4.7.0\lib\net48\WebDriver.dll"
. 
. #r "C:\Users\pozii\Downloads\selenium.support.4.7.0\lib\net48\WebDriver.Support.dll"
> using OpenQA.Selenium.Support;
. using OpenQA.Selenium.Support.UI;
. using OpenQA.Selenium.Chrome;
. using OpenQA.Selenium;
> IWebDriver wd = new ChromeDriver(@"C:\Users\pozii\Downloads\chrDriver_108\");
瑓牡楴杮䌠牨浯䑥楲敶⁲〱⸸⸰㌵㤵㜮‱ㄨづ㍥㘸攸づ收ㄹ摡㌶愶㜸㐴〲㍥慣愳㍥㔷愶ⵣ敲獦戯慲据⵨敨摡⽳㌵㤵筀ㄣ㄰紶 湯瀠牯⁴㔵㤱റ伊汮⁹潬慣⁬潣湮捥楴湯⁳牡⁥污潬敷⹤਍汐慥敳猠敥栠瑴獰⼺振牨浯摥楲敶⹲档潲業浵漮杲猯捥牵瑩⵹潣獮摩牥瑡潩獮映牯猠杵敧瑳潩獮漠⁮敫灥湩⁧桃潲敭牄癩牥猠晡⹥਍桃潲敭牄癩牥眠獡猠慴瑲摥猠捵散獳畦汬⹹਍

```

**_Are somebody get tips how change encoding?_**

**Actual Behavior**:
```
(1,17): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
(1,17): error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

When I tried create FirefoxDriver got same error.
But I can create and run an app targeting to .Net 6.0 in IDE for example Console or DLL types. But in C# Interactive can`nt.

Possible I must to do something else?
I did`nt find complete describe tunning this REPL, then tried next:

```#r "System.Runtime"
> IWebDriver wd = new ChromeDriver();
System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  + AsyncTaskMethodBuilder<TResult>.Start<TStateMachine>(ref TStateMachine)
> #r "System.Collections"
> IWebDriver wd = new ChromeDriver();
System.TypeLoadException: Could not load type 'System.Globalization.CultureInfo' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  + OpenQA.Selenium.Chrome.ChromeOptions.get_CapabilityName()
  + OpenQA.Selenium.Chromium.ChromiumOptions..ctor()
  + OpenQA.Selenium.Chrome.ChromeOptions..ctor()
  + OpenQA.Selenium.Chrome.ChromeDriver..ctor()
> 
```

So we can seeing requirements with downgrade version. In that moment I did stop.

Thank you for anything help!

**Comment by tmat** [comment]
> `#r "C:\Users\po\Downloads\selenium.webdriver.4.7.0\lib\net6.0\WebDriver.dll"`
> `#r "C:\Users\po\Downloads\selenium.support.4.7.0\lib\net6.0\WebDriver.Support.dll"`

Seems like these are NET 6.0 assemblies, so you need to switch to .NET Core runtime like so:

```
#reset core
```

**Comment by AleksandrEfimov** [comment]
Wow! It is amazing!
Where did I could read about that early?
Thanks a lot!
