### ISSUE TITLE
`async` and `required` should be mutually exclusive

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66088]
Considering that `async` is method-only modifier and `required` is property-only modifier, having one of these should prevent completion suggestion of another.

**Version Used**:
Latest `main`

**Steps to Reproduce**:
Case 1:
```cs
class MyClass
{
    async $$
}
```
Case 2:
```cs
class MyClass
{
    required $$
}
```

**Expected Behavior**:
Case 1 - no `required` completion
Case 2 - no `async` completion

**Actual Behavior**:
Opposite to expected

**Comment by arkalyanms** [comment]
Closing as per discussion in the PR.
