### ISSUE TITLE
DebugType does not default to "none" for Release configuration

### ISSUE THREAD

**Issue by oliverbooth** [dotnet/roslyn#66103]
When building an application or library in Release mode, a .pdb file is generated with its absolute path embedded into the output assembly. This is absolutely not ideal, and borders on a major security flaw, as it exposes some potentially sensitive information such as filesystem structure and - depending on the build path - developer's real names. I've written [a blog post](https://blog.oliverbooth.dev/2022/12/22/a-hidden-csharp-compiler-setting-that-might-kind-of-dox-you/) which explains this behaviour in some more detail, but suffice to say that even in cases where no PDB file is published to the public (and rightfully so), the path to that file is still in the assembly, and in one case I was able to discover a developer's real first name because the build was published to their Desktop folder.

An example of how this appears in dotPeek when examining the assembly for Stardew Valley, a game made with XNA:
![image](https://user-images.githubusercontent.com/1129769/209201515-aa1914f1-0acb-402e-a2ac-1d7f535cd746.png)

This seems to massively contradict [what the documentation states](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype) about this compiler option.
> The **DebugType** option causes the compiler to generate debugging information and place it in the output file or files. Debugging information is added by default for the _Debug_ build configuration. ___It is off by default for the _Release_ build configuration.___

As far as I can tell, this is flat out false. I believe this is a huge oversight, possibly a bug.

**Steps to Reproduce**:

1. Create any type of application
2. Build it under Release configuration (or even dotnet publish it)
3. Examine dll metadata in application such as dotPeek or ILSpy

**Expected Behavior**:
Debug symbols should not be emitted in Release configuration. More importantly, the absolute path to the .pdb file should not be embedded into the assembly at all.

**Actual Behavior**:
It does do that. Developer's filesystem structure is publicly exposed in a huge number of cases.

**Comment by jcouv** [comment]
I was able to repro this with a simple `dotnet new console` project and running `dotnet build -property:Configuration=Release -bl`.
Looking at the binary log, `csc` receives the following arguments `/debug- /debug:portable`. The policy for `csc` arguments is that the last one wins, so a portable PDB will be emitted despite the `/debug-`.
Looking at the `Csc` task properties, I see `EmitDebugInformation=False` and `DebugType=portable`. The `EmitDebugInformation=False` results in `/debug-` and `DebugType=portable` results in `/debug: portable` being given to `csc`.

I see two possible fixes:
1. the `Csc` task should skip `DebugType` when `EmitDebugInformation=False` (fix in roslyn repo)
2. `DebugType` property should not be set by the SDK when `EmitDebugInformation=False` or in the *Release* configuration build (fix in SDK)

Tagging @rainersigwald to advise.

**Comment by jcouv** [comment]
> More importantly, the absolute path to the .pdb file should not be embedded into the assembly at all.

@oliverbooth I'd missed this part of your comment. **If a PDB is emitted** (which I agree it should not in this scenario, based on documentation) then it may contain absolute paths. This seems by-design.  
It may be possible to substitute some of those paths by using a path map.

**Comment by svick** [comment]
Even if the change to start emitting PDBs in Release mode was unintentional, wouldn't reverting it now be a breaking change?

**Comment by jcouv** [comment]
> [would fixing this] be a breaking change?

@svick That'll certainly be a consideration. But I'd like to figure out what is the "correct" solution first, then we can sort out other practical constraints ;-)

**Comment by oliverbooth** [comment]
> > More importantly, the absolute path to the .pdb file should not be embedded into the assembly at all.
> 
> @oliverbooth I'd missed this part of your comment. **If a PDB is emitted** (which I agree it should not in this scenario, based on documentation) then it may contain absolute paths. This seems by-design. It may be possible to substitute some of those paths by using a path map.

Oh yeah of course! Whether it's absolute or relative path is irrelevant. The issue was more that debug symbols get emitted at all for Release mode by default haha

**Comment by jcouv** [comment]
As a tangent, for the issue of including dev/local paths in the PDB, I was told that the recommended solution is to use the [`ContinuousIntegrationBuild`](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#continuousintegrationbuild) setting. I don't know much about it myself.

**Comment by jcouv** [comment]
From discussion with @jaredpar, @tmat and @rainersigwald, we think this is a documentation bug. PDBs should be produced even in Release mode by default.
