### ISSUE TITLE
Long switch expression is duplicated in `InferTypesWorker_DoNotCallDirectly` overloads

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66116]
https://github.com/dotnet/roslyn/blob/975dcc54c811405ac9c1fb6c69bbcb32574da689/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs#L141-L193

https://github.com/dotnet/roslyn/blob/975dcc54c811405ac9c1fb6c69bbcb32574da689/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs#L203-L258

We should make sure there is a single method of the two that have this switch expression, and should make sure that cases from **both** are handled.

**Comment by vibeeshan025** [comment]
New to Roslyn's contribution. Shall I work on this?

**Comment by CyrusNajmabadi** [comment]
Sure. You could work on this!
