### ISSUE TITLE
Proposal: Create ScriptState.ContinueWithAsync(Script) overloads

### ISSUE THREAD

**Issue by tenor** [dotnet/roslyn#6612]
I propose we create two overloads of the `ScriptState.ContinueWithAsync` methods that will accept a script object parameter.

There is currently no *public* way to compile a submission, examine the compilation and decide if you want to run it or not.

The `ContinueWithAsync` methods only accept raw code, so the only way to do what I just described is to call the internal `Script.ContinueAsync` method. A public `ScriptState.ContinueWithAsync(script)` overload seems more natural to me.

I can provide a PR if approved.

**Comment by tmat** [comment]
Right. We should make ContinueAsync public again. It's used by both csi and VS REPLs.
@mattwar

**Comment by tenor** [comment]
That works! My proposal was mostly about API consistency.

**Comment by mattwar** [comment]
@tmat that's fine with me.
