### ISSUE TITLE
Add subtle color highlight to const fields by default

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#66129]
## Summary

Currently, the default color scheme in VS2022 doesn't use any special color for constants, making it impossible to just glance at code and know whether a static member being accessed is in fact a const, or just some static member. I've been using a custom color for years and it's worked quite well for me, and I'm thinking it might be something useful to just add to the default color scheme. The idea is just to make the color slightly different for constants, so they can be differentiated at a glance. Kinda like how structs use a slightly different shade of green than classes.

For instance, I'm using a subtle violet color for constants, like so:

![](https://user-images.githubusercontent.com/10199417/209562243-3af0cf3f-81b6-4fd8-829a-882819a66f16.png)

This way it's very easy to know that a given member is a constants and not a normal static member.

## Proposed Feature

In the pic above, I've used a subtle violet shade for constants. This works quite well with a dark theme, though I suspect it might need some changes to properly adapt to the light and high contrast themes as well. The general idea is just: let's pick _some_ subtle colored shade and use that for all fields classified as constants.

## Additional notes

We might also consider doing the same (either same color or different one) for enum members. This would particularly be useful when an enum is used with `using static` directive, as in that case the member would be directly referenced in code, without the type name prefix. Having a different color would make it much easier to know that a given identifier is in fact an enum member.

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of broader feedback.

**Comment by Sergio0694** [comment]
I still think this is a good idea, but at least I can work around it by customizing the color for my profile 😅
