### ISSUE TITLE
Proposal: Allow specifying directory for Source Generator emitted files

### ISSUE THREAD

**Issue by cathei** [dotnet/roslyn#66122]
## Background and Motivation

When generating number of files, especially with incremental source generators, it would be nice to have directory structure for organization in IDE and debugging purpose. Currently they can only be placed directly under each generator folder.

<img width="328" alt="Screen Shot 2022-12-24 at 1 36 43 AM" src="https://user-images.githubusercontent.com/1960113/209448597-f03d3ae7-2f8a-48ff-a1af-0c8385711f49.png">

## Proposed API

Allow `hintName` parameter to accept path separator and generate directory accordingly, for following APIs:

```csharp
SourceProductionContext.AddSource(string hintName, string sourceText);
SourceProductionContext.AddSource(string hintName, SourceText sourceText);
GeneratorExecutionContext.AddSource(string hintName, string sourceText);
GeneratorExecutionContext.AddSource(string hintName, SourceText sourceText);
GeneratorPostInitializationContext.AddSource(string hintName, string sourceText);
GeneratorPostInitializationContext.AddSource(string hintName, SourceText sourceText);
IncrementalGeneratorPostInitializationContext.AddSource(string hintName, string sourceText);
IncrementalGeneratorPostInitializationContext.AddSource(string hintName, SourceText sourceText);
```

Path separators are currently invalid character for `hintName`, therefore this wouldn't break current behaviour.

## Usage Examples

``` C#
public void Execute(GeneratorExecutionContext context)
{
    var path = Path.Combine("Some", "Directory", "MySource.g.cs");
    context.AddSource(path, GetSourceText());
}
```

## Alternative Designs

Could have directory as separated parameter.

## Risks

May affect tools that relies on current flat directory structure.

**Comment by jaredpar** [comment]
This idea seems reasonable to me. One restriction though is that the paths would need to be relative. That is they could only be used to create directories under the source generator emit directory, they could not specify absolute paths. An absolute path would be troublesome for a number of command line build scenarios as well as IDE. 

@chsienki do you have any thoughts here?

**Comment by chsienki** [comment]
Yeah, I think this seems sensible. Agreed that it would need to be a relative path, and we'd also need to sanity check for things like `\..\` in the provided path, but I don't think that would be a deal breaker.
