### ISSUE TITLE
Isolate NuGet packages folder on a per-build basis

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6613]
We've run into a bunch of breaks over the past week that have to do with NuGet package changes, that are not being caught on developer or Jenkin machines:

Here are some examples:
Build error in stabilization: #6562
PR Test Failure: A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "System.Console (ò 4.0.0-beta-23123)" or update the version field: #6438

The reason for this is because it appears that NuGet treats the user-wide `%USERPROFILE%\.nuget` folder as a package source, rather than just as a user-wide cache of packages. This can lead to `NuGet restore` finding packages or upgrading a project to a package that _does not exist_ in the original source.

This is extremely problematic when we are working across many different projects with different dependencies and branches (stabilization, master, future), but sharing a user and machine to build these projects.

There's not yet a good way to avoid this issue on developer box without controlling the environment that restores packages (be it the command-line or VS), but on the Jenkins machines, we should at least isolate the .nuget folder per build to catch these issues before the developer merges a PR. This will increase download time, etc (perhaps look at introducing a proxy to avoid this), but will lead to less issues found after the fact.

**Comment by Pilchie** [comment]
Do you have a repro of the package upgrade issue?  I bet @yishaigalatzer would like to hear about that.

**Comment by davkean** [comment]
I've already mentioned it to both him and Justin, I'm setting up a repro for an issue - but this is well known.

**Comment by davkean** [comment]
I suspect we should have caught this with our project.lock.json change detector but it's been disabled: https://github.com/dotnet/roslyn/blob/master/cibuild.cmd#L72

**Comment by jaredpar** [comment]
@davkean that code will only catch changes if we restore in Jenkins.  We don't do that today.

**Comment by davkean** [comment]
I'm going to close this out - while we might see this catch some issues, the perf savings (we're down to a 30 second restore on build machines) greatly outway any issues we have here.
