### ISSUE TITLE
IDE0031: Null check can be simplified. Use null propagation does nothing.

### ISSUE THREAD

**Issue by Tape-Worm** [dotnet/roslyn#66141]
**Version Used**: 
.NET 6.0
Visual Studio 2022 (17.4.3)

**Steps to Reproduce**:

Create a minimal console project in .NET 6 and add the following code:
```csharp
byte? value = 255;

object? boxedValue = value is null ? null : value.Value;
```

Bring up the analyzer options:
![image](https://user-images.githubusercontent.com/9710137/209767139-0ec44d0b-a100-48ab-8a15-3db76c2b5f86.png)

Select "Preview Changes" and this comes up:
![image](https://user-images.githubusercontent.com/9710137/209767291-dfe2946e-fd6e-42a8-8c4a-2c62b12ec598.png)

**Diagnostic Id**:

IDE0031

**Expected Behavior**:
Change the line from `object? boxedValue = value is null ? null : value.Value;` to `object? boxedValue = value ?? null;` (or something similar).

**Actual Behavior**:
The code `object? boxedValue = value is null ? null : value.Value;` remains.

**Comment by svick** [comment]
I think an even better fix would be to change the code to:

```c#
object? boxedValue = value;
```

**Comment by Youssef1313** [comment]
> I think an even better fix would be to change the code to:
> 
> ```cs
> object? boxedValue = value;
> ```

I agree this should be the fix.

Care should be taken to not use `var` if it exists in the original code, e.g, `var boxedValue = value is null ? (object?)null : value.Value;` should be `object? boxedValue = value;`

**Comment by CyrusNajmabadi** [comment]
"simplify expression" would also be fine with me.
