### ISSUE TITLE
Pattern-based fixed statement behaves inconsistently for nullable value types

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#66167]
```
unsafe class C
{
    public static void Main()
    {
        Test((int?)null);
        Test2((int?)null);
    }

    public static void Test<T>(T arg)
    {
        fixed (int* p = arg)
        {
            System.Console.Write(p == null? 0: p[1]);
        }
    }
    public static void Test2(int? arg)
    {
        fixed (int* p = arg)
        {
            System.Console.Write(p == null? 0: p[1]);
        }
    }
}

static class FixAllExt
{
    public static ref int GetPinnableReference<T>(this T dummy)
    {
        return ref (new int[]{1,2,3})[0];
    }
}
```

Observed:
```
02
```

Expected:
Consistent behavior between generic and not generic code. The output should be either ```00```, or ```22```.

It looks like https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.3/pattern-based-fixed.md#translation implies that there must be a null check for the target, but it is not clear whether the intent was to actually perform the null check for nullable value types.

**Comment by MadsTorgersen** [comment]
I think it is fair to say that the null check should be performed for nullable value types. The translation code in the linked spec says `// NOTE: null check is omitted for value types `, but I think it means for _nonnullable_ value types. At least that would be most consistent with how nullable value types are treated elsewhere.

I release that `GetPinnableReference` can only be implemented on nullable value types via extension method, which means that calling it on null won't yield a null reference exception. But it still seems right to treat null as null consistently, leading to `00` in the example above.

**Comment by jcouv** [comment]
@AlekseyTs I triaged this in C# 12 milestone (not urgent since issue has existed for a while) but feel free to bring up to an earlier milestone. Thanks
