### ISSUE TITLE
`DeclarationModifiers.From` doesn't handle constant locals

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66172]
https://github.com/dotnet/roslyn/blob/5730ffc208e3b7d7fe284cc26f75ae4a43703005/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs#L65-L96

`isConst: field?.IsConst == true`, this only handles constant fields. Should it handle constant locals? @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
