### ISSUE TITLE
Revise `DeclarationModifiers.From` implementation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66171]
- NOTE: The most common use for `DeclarationModifiers.From` is `SyntaxGenerator.WithModifiers`, which filters the modifier to only syntactically valid ones via `GetAllowedModifiers`. So for this specific (common) use case, there is no behavioral change. This issue is more about the standalone behavior of `DeclarationModifiers.From`

https://github.com/dotnet/roslyn/blob/450573325c1a1bc259d0b4ab76f712f7bbc7ecb1/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs#L65-L97

The name implies that this method returns *declaration* modifiers (e.g, those that are *declared syntactically*).

- `isSealed: symbol.IsSealed`: this will [return true for structs, enums, constants, etc](https://github.com/dotnet/roslyn/blob/5730ffc208e3b7d7fe284cc26f75ae4a43703005/src/Compilers/CSharp/Portable/Symbols/Symbol.cs#L454-L460), is this the intended behavior for this API?
- `isReadOnly: field?.IsReadOnly == true || property?.IsReadOnly == true || type?.IsReadOnly == true || method?.IsReadOnly == true`: same concern goes for properties.

**Comment by jaredpar** [comment]
Not quite sure what the proposal is here. Are you suggesting we change the behavior of these APIs? If so won't that be a breaking change for existing customers?

**Comment by Youssef1313** [comment]
Yes, technically a breaking change. In past, I think breaking changes were accepted when they made since. It's unlikely that anyone depends on the current behavior anyway.

**Comment by Rekkonnect** [comment]
Note in the thread that you mention `isStatic: symbol.IsStatic` and link to the `IsSealed` declaration mentioning that it returns true for structs, enums, consts, etc.

**Comment by Youssef1313** [comment]
Fixed. Thanks for noting @Rekkonnect

**Comment by jcouv** [comment]
Assigned to @jasonmalinowski as [area owner](https://github.com/dotnet/roslyn/blob/main/docs/area-owners.md#areas) for Workspace APIs. Please advise and triage.
