### ISSUE TITLE
SyntaxGenerator: Consider filtering `async` modifier for methods without a body

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66173]
https://github.com/dotnet/roslyn/blob/5730ffc208e3b7d7fe284cc26f75ae4a43703005/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L228

https://github.com/dotnet/roslyn/blob/5730ffc208e3b7d7fe284cc26f75ae4a43703005/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L232

For a false value of `hasBody`, should we drop `async` modifier if exists?

**Comment by CyrusNajmabadi** [comment]
Yes.

**Comment by Youssef1313** [comment]
@kinkeadian25 You might be interested in this issue.

**Comment by kinkeadian25** [comment]
I will work on this here soon, I have been assuming every change requires a test. Should I keep doing that even for small changes like this? @Youssef1313

**Comment by Youssef1313** [comment]
@kinkeadian25 Yes, tests are very important

**Comment by kinkeadian25** [comment]
yeah sorry, right after i posted this I told myself stupid question. How do you feel about passing hasbody as a parameter to AsModifiersList for each type of declaration syntax and adding it as a check to the Abstract if statement? @Youssef1313

**Comment by Youssef1313** [comment]
`AsModifierList` has many callers. I think we should just alter its return value in the code path for generating methods.

**Comment by kinkeadian25** [comment]
that makes more sense, thank you!
