### ISSUE TITLE
`DeclarationModifiers.From` doesn't return `readonly` for methods

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66170]
https://github.com/dotnet/roslyn/blob/5730ffc208e3b7d7fe284cc26f75ae4a43703005/src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs#L80

**Comment by Youssef1313** [comment]
FYI @kinkeadian25

**Comment by kinkeadian25** [comment]
Added in!
