### ISSUE TITLE
Syntax highlight breaks down when scrolling with sticky scroll headers enabled

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#66186]
**Version Used**: VS 17.5.0 Preview 2

**Steps to Reproduce**:

1. Enable the sticky scroll header
2. Scroll over any code where there are some types as base types or method parameters

**Expected Behavior**:

The syntax highlight should not be affected by the user scrolling over source, and it should just always remain consistent.

**Actual Behavior**:

You can see some types losing the syntax highlight for some time every single time you scroll:

![sticky_scroll_glitch](https://user-images.githubusercontent.com/10199417/210219461-64f085ec-3891-403a-8cf3-e52e07f1a6ef.gif)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you route?  I don't believe Roslyn is involved in this feature.

**Comment by olegtk** [comment]
@Sergio0694, this is a known issue, fixed in Preview3, thank you for reporting though!
