### ISSUE TITLE
COM library is causing a CS0246 Error in VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66200]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/COM-library-is-causing-a-CS0246-Error-in/10242595)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.11.22]
We use a **COM library in a .NET framework 4.8** project to communicate with a control of a machine tool. The project was created under **VS 2019 with no problems**. 
Now we want to use it under VS2022 and we get the warning that the library couldn't be loaded, but **the assembly will be build under VS2022** with no issues. Because the library isn't recognized, the code suggestion doesn't work and every object of the library we use causes a **CS0246 error with a message that the type or namespace couldn't be found**. That is really annoying, because it's like coding with a text editor.
We have tried to remove and add the library, but VS2022 lists the DLL in the tab of COM libraries, but refuses to add the DLL, because the IDE doesn't accept that it is a COM library. Under VS2019 it is no problem to remove and add the DLL.
As a temporary solution we have to use both IDEs for our solution, because we also have new projects, which are now written in .NET 6 and are not compatible with VS2019.

---
#### Feedback Bot on 1/2/2023, 07:03 PM: 

(private comment, text removed)
#### Feedback Bot on 1/3/2023, 10:28 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I believe this is fied with https://github.com/dotnet/roslyn/pull/66034.  @mavasani ?

**Comment by mavasani** [comment]
That could be the issue, but we would need a confirmation from the customer whether waiting for some time after opening their solution causes the spurious CS0246 errors to go away. If not, it could be an unrelated issue in the project system layer.
