### ISSUE TITLE
CS0121 diagnostic produced when an overload is obvious

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/roslyn#66221]
**Version Used**: 
Tested against C# 11.0 with dotnet 7. Have not tried other versions

**Steps to Reproduce**:

```csharp
using System;
using System.Threading.Tasks;
using System.Linq.Expressions;

IClient<int> client = null!;

// The below line causes CS0121
client.Enqueue(arg => Task.FromResult(arg), continuation => continuation);

interface IClient<TArg> {
    void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
    void Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
}

interface IContinuationBuilder<TResult> { }
``` 

(or see [sharplab.io](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5lqZwB0AMgJYB2AjsQKIAeADgE4CmAzh+QPaUf4kyAJIBhADbk2lAC4AeKjIB86AMaTpM9AF50lAK7jxAQkHJ1U2fRr62tgBQBDFgHMdKqADZiAMRY8AWwAlTkMZJ1cASgAaNT4ZKn1HBL53ONlE5N5KSLMUOE9MGHQAKR4AIw5kAG9kdHrMAGYiQq8FWRUAQWBgAHlKNntFdGcXSLSvX39g0PFw0fQwdDhc5ABfZE2kRTYWADNHVTZ0MQ1ZOQAVTtclGrqGqGaoABZ0Ohs7NkuQjjCle0YrE43D4cig2Eu1xcsQuPz+KjYzHYXGysXBcjE8UyKUoACF9ORxMBdt9ZspYpiMgYsnx8YTiSxSb85kolAB+dIJak4nR6QziVZCJANJqYV7vai2WxMv4ApHA7JgiFXVxozwylms9CIoEovhoiGUrlJHF0okk2FkpQU0RY7nZM0MjXKdmc7HZXkGIyCjZCnb7Q7HI3u2kE82My3M5ToaroNZAA==))

Given that the expression passed to `client.Enqueue` returns a Task of int, You would expect no ambiguity, yet CS0121 is raised. Currently I'm aware of 2 logic alterations that works around this issue (hence my suspicion of a compiler bug):

```csharp
// NO error when the continuation argument is omitted,
client.Enqueue(arg => Task.FromResult(arg));
```

```csharp
// NO error when the continuation parameter is of type `Action<IContinuationBuilder<TResult>>`
client.Enqueue(arg => Task.FromResult(arg), continuation => {});
```

**Diagnostic Id**:
error CS0121: The call is ambiguous between the following methods or properties: 'IClient<TArg>.Enqueue<TResult>(Expression<Func<TArg, TResult>>, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>?)' and 'IClient<TArg>.Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>>, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>?)'

**Expected Behavior**:
The overload taking a `Expression<Func<TArg, Task<TResult>>> expression` should be used

**Actual Behavior**:
error CS0121

**Comment by CyrusNajmabadi** [comment]
Both of those overloads look applicable.  Can you explain why one is not?

**Comment by CyrusNajmabadi** [comment]
> Given that the expression passed to client.Enqueue returns a Task of int, You would expect no ambiguity

It appears as if this overload is completely applicable: 

`void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);`

If you just have that overload and not the other, does it compile?  If so, there are two options to pick.

**Comment by koenbeuk** [comment]
> Both of those overloads look applicable. Can you explain why one is not?

They are both applicable but one is preferred: 

```csharp
client.Enqueue(arg => Task.FromResult(arg));

interface IClient<TArg> {
    void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression);
    void Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>> expression);
}
```

The above scenario has 2 overloads that are both applicable however C# is able to determine that the latter is preferred (it compiles). 

I am unable to explain why in my original sample, C# is not able to determine the preferred overload. 

> It appears as if this overload is completely applicable:
> 
> `void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);`
> 
> If you just have that overload and not the other, does it compile? If so, there are two options to pick.

It compiles with just that overload, note though that TResult will now be `Task<int>` (where I am expecting TResult to be of `int`).

**Comment by koenbeuk** [comment]
Perhaps where I'm confused (And there may be a very legitimate reason, why does the first sample compile bot not the second?)

compiles:
```csharp
client.Enqueue(arg => Task.FromResult(arg), continuation => {});

interface IClient<TArg> {
    void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Action<IContinuationBuilder<TResult>>? continuation = null);
    void Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>> expression, Action<IContinuationBuilder<TResult>>? continuation = null);
}
```

does not compile
```
client.Enqueue(arg => Task.FromResult(arg), continuation => continuation);

interface IClient<TArg> {
    void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
    void Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
}
```

**Comment by CyrusNajmabadi** [comment]
@jaredpar do you know what the distinction is here?

**Comment by jcouv** [comment]
> compiles: `client.Enqueue(arg => Task.FromResult(arg), continuation => {});`

I'm not sure what you mean. This gives me an [error](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5lqZwB0AMgJYB2AjsQKIAeADgE4CmAzh+QPaUf4kyAJIBhADbk2lAC4AeKjIB86AMaTpM9AF50lAK7jxAQkHJ1U2fRr62tgBQBDFgHMdKqADZiAMRY8AWwAlTkMZJ1cASgAaNT4ZKn1HBL53dABvAF9IsxQ4T0wYdAApHgAjDmR05HRazABmIgKvBVkVAEFgYAB5SjZ7RXRnF0i0r19/YNDxcOH0MHQ4HORM5DWkRTYWADNHVTZ0MQ1ZOQAVdtclKpq6qEaoABZ0Ohs7NjOQjjCle0ZWTm4fDkUGwZwuLlip0+3xUbGY7C4vEosRBcjE8USySRACF9ORxMAth9pspYujZJiUpRcfjCSxiV8ZkolAB+OIUgxY1K6AxGZZCJB1BqYJ4vai2WwM76/eEApHA0HnVwozxSpnM9Bw/6Ivgo0HkhKcqk0glEqEkpRk0QYo04vGm+nmxnKVnsw1JKk6PSGcT81YCzY7PYHA2Uu20s3QpkZdCZIA) `error CS1643: Not all code paths return a value in lambda expression of type 'Func<IContinuationBuilder<int>, IContinuationBuilder<int>>'`

**Comment by jcouv** [comment]
Both overloads are applicable (commenting either one out results in no error). I don't see which [overload resolution tie-breaker rule](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/expressions.md#11643-better-function-member) would come into play to prefer one overload over the other.
So as far as I can tell the ambiguity error is by-design.

**Comment by koenbeuk** [comment]
Thanks for linking me to the spec for the overload resolution tie-breaker. I'll have to dive in. I'll close this issue for now as I'm no longer convinced its a compiler issue. I do think that there is room to investigate in a better tie-breaker here as the following 2 seemingly similar calls result in unexpected and hard to debug behavior. I'll open a discussion in the lang repo once I feel confident enough on the subject.

```csharp
client.Enqueue(arg => Task.FromResult(arg)); // Compiles
client.Enqueue(arg => Task.FromResult(arg), continuation => {}); // CS0121

interface IClient<TArg> {
    void Enqueue<TResult>(Expression<Func<TArg, TResult>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
    void Enqueue<TResult>(Expression<Func<TArg, Task<TResult>>> expression, Func<IContinuationBuilder<TResult>, IContinuationBuilder<TResult>>? continuation = null);
}
```
