### ISSUE TITLE
[LSP] Remove NFW reporting in `RangeToTextSpan` after issue is fixed

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn#66258]
We are adding additional NFW reporting in `RangeToTextSpan` in order to diagnose the exception found in [this issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1534360) (MSFT internal). It should no longer be needed in this location after the underlying issue is resolved.

**Comment by beccamc** [comment]
Also remove the code from https://github.com/dotnet/roslyn/commit/0d26c3545c16e09bc4cb18619e8426b90decc39a

**Comment by beccamc** [comment]
David and I agreed the custom logging is useful. Closing.
