### ISSUE TITLE
Ctrl+Alt+Up/Down shortcuts do not search interactive window history

### ISSUE THREAD

**Issue by zooba** [dotnet/roslyn#6626]
Originally reported as https://github.com/Microsoft/PTVS/issues/958

The Ctrl+Alt+Up shortcut does not navigate or search history (or alternatively, does not match previous entries - there's no way to tell without debugging the function).

```
>>> a = 123
>>> b = 234
>>> a<Ctrl+Alt+Up>
```

In this case, I expect to have `a = 123` appear in the current buffer, but it remains unchanged.

**Comment by amcasey** [comment]
Our best guess is that RDP was swallowing the keyboard shortcut.  Please re-activate or re-file if you encounter the issue again.
