### ISSUE TITLE
After last update VS stops suggest "Introduce local variable "

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66271]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-last-update-VS-stops-suggest-Intr/10244560)._

---
[regression]
Hello Team,
One of the most used features is the `Alt +Enter` shortcut with the **introduce local variable** over the highlighted text.
A few days ago, after installing the latest VS update it stopped suggest me the "introduce local variable" but only **Extract Method** or **Extract local function**.
Can you please help with this issue?
Thanks!

---
#### Feedback Bot on 1/4/2023, 06:52 PM: 

(private comment, text removed)
#### Feedback Bot on 1/5/2023, 10:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Doesn't repro for me.  I get: 

![image](https://user-images.githubusercontent.com/4564579/210859881-c48242bd-ef58-4bee-a429-ac81c7c45948.png)

We'd need a fuller repro here to know what's going on.

**Comment by aharon-yaffe-sp** [comment]
After restart my VS it looks OK now.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Looks like the same symptoms of #66272 ?

**Comment by mavasani** [comment]
> After restart my VS it looks OK now.

Thanks, we will close this issue. Please re-activate if you hit this again and have more information for us to investigate.
