### ISSUE TITLE
Formatting doesn't fix curly brace for else-clause

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6628]
![elseformatting](https://cloud.githubusercontent.com/assets/4564579/11009952/34e7bbe0-8490-11e5-99d3-8eb2a1e7d851.gif)

**Comment by CyrusNajmabadi** [comment]
This affects 'format document' as well, not just format-on-typing.

**Comment by diryboy** [comment]
Cannot reproduce this from VS2015 RTM.

**Comment by Pilchie** [comment]
I can reproduce this on the latest bits as well.  Looks like we regressed something since RTM :frowning:

**Comment by diryboy** [comment]
Say if someone or me take a look and able to create PR to fix this week, will it be too late to be included in update 1? This could be really annoying.

**Comment by Pilchie** [comment]
Not at this point.  We have what we believe will be our final build of Roslyn already, barring some significant hang/crash/data loss issue in a common scenario :frowning:

**Comment by matty-hall** [comment]
Will this be in Update 2?  Both it and [7768](https://github.com/dotnet/roslyn/issues/7768) are maddening regressions from VS2013 that I bump into constantly.  Please!

**Comment by Pilchie** [comment]
@matty-hall That's still the plan.

**Comment by Pilchie** [comment]
Fixed by #9350.
