### ISSUE TITLE
Method dropdown selects a random item when a different item is clicked

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66290]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Method-dropdown-selects-a-random-item-wh/10244772)._

---
[severity:It bothers me. A fix would be nice]
Not always, but frequently, I will select a method from the dropdown and end up in a different method or property. A second attempt works fine. The items can be many between the desired item and the item I end up at. It was happening more frequently while editing a VB project. But it has happened a few times now while editing a C# project. This has been going on for a while and I think it has been going on since before my last update. Also, it is not something that can be duplicated on demand. It just happens. 

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.5

Thanks.

---
#### Feedback Bot on 1/4/2023, 06:51 PM: 

(private comment, text removed)
#### Feedback Bot on 1/6/2023, 06:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Does this repro in the 17.5.x builds?  We did a fair amount of refactoring of the impl here, so we'd need to know if it's still a problem.  Thanks!
