### ISSUE TITLE
CodeStyle options in Tools|Options showing up with some sort of ToString'ed version of our option type.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66291]
![image](https://user-images.githubusercontent.com/4564579/211051796-0544a521-fd07-418d-b677-5ea3bb64ed94.png)

@tmat could this be something in your options refactorings that caused this?

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/66069/commits/db91dc47c2c024532437ac3f9fc03e0225c76ff9

**Comment by CyrusNajmabadi** [comment]
Thanks!
