### ISSUE TITLE
`scoped` keyword not included in completion list

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#66305]
**Version Used**: 
Version 17.5.0 Preview 3.0 [33305.347.main]

**Steps to Reproduce**:

1. New Console App
2. Type `scoped` within `Main` method body

<img width="400" alt="scoped-completion" src="https://user-images.githubusercontent.com/10732005/211121874-af62420f-f5d4-4e27-babb-55497a16d17e.png">

**Comment by Youssef1313** [comment]
That's strange. It should be in Preview 3 if I understand correctly: https://github.com/dotnet/roslyn/pull/65696

**Comment by Youssef1313** [comment]
It should also be covered by this test:

https://github.com/dotnet/roslyn/blob/319291d3822622e7a92da86cb0109e14ddc4e7ce/src/EditorFeatures/CSharpTest2/Recommendations/ScopedKeywordRecommenderTests.cs#L103-L108

**Comment by cston** [comment]
Thanks @Youssef1313, I'll investigate.
