### ISSUE TITLE
Request: easier to switch between PCL and ClassLibrary

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn#6630]
Please make it easy to switch between a PCL and a ClassLibrary.

Scenario: I wrote an analyzer a while ago during beta period, when the analyzer template still spat out ClassLibraries. Then RTM happened, and guidance was to write them as PCLs. I don't know how to switch a library "in-place", so I had to delete my existing folder, create a new project in its place, copy all the files over, and copy all the custom magic from my .csproj.

Now due to #6627 I discover that my analyzer has to actually be a ClassLibrary after all (needs to access the filesystem). And again I have to go through the pain.

I tried changing my library's targets from its existing PCL targets to just ".NET46 + ASP.NET5" in the hope that this would maybe work, but it popped up an error about how this would switch to project.json, so there'd be a lot of work on the NuGet references front that I don't want to go down.

**Comment by Pilchie** [comment]
Tag @srivatsn @davkean Sounds like this should move to the project system repo?

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn-project-system#1046
