### ISSUE TITLE
Fresh clone gold bar: "Current solution contains incorrect configurations mappings"

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#66315]
Cloned Roslyn. Got commit https://github.com/dotnet/roslyn/commit/00f49cc4587f982524e726a801e946ddf7cf42ed.
Ran Restore.cmd. No errors or warnings shown.

Opened VS 17.4.3, selected Roslyn.sln, got this message:

![image](https://user-images.githubusercontent.com/8040367/211215748-853b0d59-075d-40c5-be02-a4caac6be58c.png)

I'm not sure what to look at in Configuration Manager:

![image](https://user-images.githubusercontent.com/8040367/211215871-3edb3a60-5125-44df-9489-ff4b86b4a695.png)

**Comment by CyrusNajmabadi** [comment]
I'm also getting this on latest Main:

![image](https://user-images.githubusercontent.com/4564579/211343115-ea3d470d-6f70-45c2-8524-774f2746d962.png)

@jaredpar Do you know what could be causing this, or who would be best to look into this?

**Comment by rainersigwald** [comment]
There are some set-x64 platforms specified in the solution:

https://github.com/dotnet/roslyn/blob/1f9d1698ae7574211dfff46bf5ac07a5852692d0/Roslyn.sln#L630-L637

But no, no idea on why this would have cropped up recently (blame on those lines says 2016 so doesn't seem likely to be the proximate cause.
