### ISSUE TITLE
Missing suggestions after `file` keyword

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#66319]
**Version Used**: 

VS 17.5 p2

**Steps to Reproduce**:

Type code using `file` keyword:

```csharp
//      ↓ here
file sealed class A { }
//   ~~~~~~
```

**Expected Behavior**:

Intellisense will suggest other keywords that will be used for declaration on types after `file` keyword, such as `class`, `struct`, `sealed`, `abstract`, `readonly`, etc..

**Actual Behavior**:

No suggestion.

![image](https://user-images.githubusercontent.com/23616315/211233165-0db273a3-0fde-4fcc-85ee-27efa3026911.png)

![image](https://user-images.githubusercontent.com/23616315/211233194-b55284ca-7702-4f07-bb2d-5b54d845052f.png)

![image](https://user-images.githubusercontent.com/23616315/211233204-0d375158-4a27-4bd6-8f45-c3694894394d.png)

> Intellisense behaves well if other keywords besides it, but `file` is an exception.

**Comment by Youssef1313** [comment]
I guess the change will be here:

https://github.com/dotnet/roslyn/blob/00f49cc4587f982524e726a801e946ddf7cf42ed/src/Features/CSharp/Portable/Completion/KeywordRecommenders/SealedKeywordRecommender.cs#L37-L45

Haven't confirmed though.

The change will be needed for more keyword recommenders, such as:

- abstract
- sealed
- static
- unsafe
- readonly
- ref

**Comment by Youssef1313** [comment]
@kinkeadian25 You might be interested to take a look at this one.

**Comment by kinkeadian25** [comment]
Yeah, I can work on this! Just got the time to work on that other issue, but should be able to do both over the next couple days
