### ISSUE TITLE
Honor Microsoft.FSharp.Core.AutoOpenAttribute in C#

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/roslyn#66321]
### Discussed in https://github.com/dotnet/roslyn/discussions/66216

<div type='discussions-op-text'>

<sup>Originally posted by **Xyncgas** January  3, 2023</sup>
AutoOpened modules in F# won't work in C#, in the way you have to explicitly type out the static class name that was compiled, creating a lot of noise and reduce the interoperability in terms of being convenient to use F# codes in C# whilst they're all part of the .NET Eco System.

People who are used to auto open module in F# might also have class names that's hard to type or even random guid :
```F#
namespace project
    module ``{7B0214CC-828F-4488-8D16-F47BB33BE22C}`` = let myPublicVariable = 0
````

While this is compiled, it looks like this for a C# project : 
```C#
namespace project
{
  [AutoOpen]
  [CompilationMapping(SourceConstructFlags.Module)]
  public static class {7B0214CC-828F-4488-8D16-F47BB33BE22C}
  {
    public static int myPublicVariable
    {
      [DebuggerNonUserCode] get => 0;
    }
  }
}
```

which is unusable in C# because you can't type the static class name, unless you get around it by honoring the auto open attribute

Allow me to shed some light in the scenario when people are using guid as module names in F# :
F# currently doesn't let you have the same module name in two separate files if these modules are under the same namespace, which we are used to in C# by declaring a class as ```partial``` and many might agree it's a useful feature. The reason for doing this generally is separating the implementation in different files so it's more organized. (E.g. Light.frequencyTranform / Light.separateFrequency are two functions that belongs to the module ```Light``` but put in separate files)</div>

**Comment by svick** [comment]
To make the module at least accessible from C#, you could change the name to something like `GUID7B0214CC828F44888D16F47BB33BE22C`.

Also, I suspect it's more likely that C# would introduce its own version of this (see e.g. https://github.com/dotnet/csharplang/issues/4029, though that's more limited than F# `AutoOpen`), than that it would start honoring F# attributes.

**Comment by Xyncgas** [comment]
Is C# compiler supposed to make the name accessible when it's implemented, or F# people are on their own when mixing languages

**Comment by Xyncgas** [comment]
> > Is C# compiler supposed to make the name accessible when it's implemented, or F# people are on their own when mixing languages
> 
> C# sees this as metadata so it doesn't have any control over it but as long as the name is a valid C# identifier I think you could even use a code generator to add global using static for types annotated by AutoOpen.

Good idea
