### ISSUE TITLE
Document.GetOptionsAsync returns wrong TabSize for VB document

### ISSUE THREAD

**Issue by AlexanderEgurtsovDX** [dotnet/roslyn#66325]
**Version Used**: 
4.4 and 4.5
**Steps to Reproduce**:

1.  Change Tab Settings for VB and CSharp to set both Tab Size/Indent Size to 2:
https://www.screencast.com/t/CDnT1G23SOj
2.  Run attached sample refactoring on simple C# and VB code. The only purpose of the refactoring is to get document options and display TabSize value. While TabSize is equal for C# and VB, Code Provider shows different values:
https://www.screencast.com/t/GgYfVMYQQ
3.  We were using GetOptionsAsync to re-format documents when performing different CodeRush functionality. This issue breaks the coding experience for VB customers of CodeRush.

**CodeRefactoring to reproduce the issue**
```cs
    [ExportCodeRefactoringProvider(LanguageNames.CSharp, LanguageNames.VisualBasic, Name = nameof(TabsSpacesTestCodeRefactoringProvider)), Shared]
    internal class TabsSpacesTestCodeRefactoringProvider : CodeRefactoringProvider {
        public sealed override async Task ComputeRefactoringsAsync(CodeRefactoringContext context) {
            // TODO: Replace the following code with your own analysis, generating a CodeAction for each refactoring to offer
            var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
            var options = await context.Document.GetOptionsAsync(context.CancellationToken).ConfigureAwait(false);
            var tabSize = options.GetOption(Microsoft.CodeAnalysis.Formatting.FormattingOptions.TabSize);
            // Find the node at the selection.
            var node = root.FindNode(context.Span);
            // For any type declaration node, create a code action to reverse the identifier text.
            var action = CodeAction.Create($"Tab Size {tabSize}", c => ReverseTypeNameAsync(context.Document, node, c));
            // Register this code action.
            context.RegisterRefactoring(action);
        }

        private async Task<Solution> ReverseTypeNameAsync(Document document, SyntaxNode node, CancellationToken cancellationToken) {
            // Produce a reversed version of the type declaration's identifier token.
            return document.Project.Solution;
        }
    }
```

**Expected Behavior**:
The real TabSize value is returned in VB when settings are changed.
**Actual Behavior**:
The default TabSize value is returned in VB.

**Comment by tmat** [comment]
Which version of VS does it not work in?

**Comment by AlexanderEgurtsovDX** [comment]
This code sample doesn't work in 17.5 Preview 2.

However, very similar issue is with the 17.4.3. When generating .editorconfig for VB solution, the default settings are used instead of changed:
https://www.screencast.com/t/UYtRgB51NDXO

**Comment by tmat** [comment]
I believe the issue was introduced in https://github.com/dotnet/roslyn/pull/62759
