### ISSUE TITLE
Warnings raised by incremental source generators are not disabled by the SuppressMessage attribute

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/roslyn#66337]
**Version Used**: 

Code generator using Microsoft.CodeAnalysis.CSharp 4.3.0
Consuming project targeting net6.0
Compiling using .net sdk 7.0.100
On Visual Studio 17.4.2

**Steps to Reproduce**:

1. Create an incremental source generator that adds a diagnostic warning
2. Create a consuming project that raises the warning. Use Visual Studio to generate the SuppressMessage attribute to disable the warning
![image](https://user-images.githubusercontent.com/41970398/211429267-97e35a51-2bf3-4774-bb59-7e45e4a4a6d6.png)

**Expected Behavior**:

The warning is disabled both in the IDE and in the output of the next build.

**Actual Behavior**:

The warning is not disabled (both in the IDE and during the next project build). The attribute is shown in "dimmed" color as if there wasn't a matching warning being raised.
![image](https://user-images.githubusercontent.com/41970398/211429426-b3c3596d-b18a-46a5-869d-0ef248982f6f.png)

**Comment by jasonmalinowski** [comment]
@mavasani Any gut idea what might be wrong here?

**Comment by mavasani** [comment]
@jasonmalinowski The generator driver would need to explicitly apply source suppressions from SuppressMessageAttributes via invoking this method: https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/SuppressMessageAttributeState.cs,729e65b0a36267d8,references. If a suppress message attribute was applicable to the diagnostic, you'll get a new diagnostic instance with `IsSuppressed` property set to true and invoking [Diagnostic.GetSuppressionInfo](https://sourceroslyn.io/#Microsoft.CodeAnalysis/Diagnostic/Diagnostic.cs,347) on this diagnostic instance would also give you the `AttributeData` for the suppress message attribute that led to suppression.
