### ISSUE TITLE
Distinguish classification between built-in types, boolean values and other keywords

### ISSUE THREAD

**Issue by dmrowiec-pl** [dotnet/roslyn#66331]
## Summary

This issue is related to classification of given keywords and types, what has impact on how the syntax can be highlighted with different colors in IDEs like VSCode.

## Background and Motivation

Currently, type names like "int", "bool", "string", as well as boolean values like "true", "false" and also "null", are all being classified as "keyword". As a result, when enabling semantic highlighting in IDE like VSCode with the usage of OmniSharp, instead of extending the syntax highlighting with having better knowledge of symbols, it makes it questionable to use the feature. Bare textmate scopes are more detailed in that area and even without having any knowledge of what given symbol actually is, they are able to distinguish between those types.

## Proposed Feature

The proposal is to add different classification type names for built-in type names, boolean values etc. instead all being a "keyword".

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
