### ISSUE TITLE
Weird the compiler doesn't stop you from doing this.

### ISSUE THREAD

**Issue by barakadax** [dotnet/roslyn#66330]
With dotnet SDK 7.0.100: 

1. Compile this piece of code:
`Dictionary<string, string> x = new() { [null] = "" };`

Fails on runtime:
`Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary2.set_Item(TKey key, TValue value)`

Can it be blocked while compiling?

**Comment by RikkiGibson** [comment]
A warning occurs on the `null` when targeting more recent versions of .NET such as .NET 6 or 7. In that case `<Nullable>enable</Nullable>` is the default project setting. [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5nIAiAlgMYAuxA9gHYCGATgJ4A8WqANJnKgHzoAPdAF50NAKYB3ABQBKdAG90AbRoBXADYaAuiPQAifegC+uIA==)
