### ISSUE TITLE
US International Keyboard and double quotes 

### ISSUE THREAD

**Issue by kfam98** [dotnet/roslyn#66346]
**Version Used**:  4.5.0-3.23056.2

There seems to be an issue when using double quotes on an international US keyboard on mac. This is not reproducible in Windows.

**Steps to Reproduce**:

1. Set up your keyboard to US International
2. Open Visual Studio for Mac
3. Create an empty string variables, i.e. `var x = "";`

**Expected Behavior**:
The double quote should be closed 

**Actual Behavior**:
- In a method body: 3 double quotes appear in the next line when adding the semi-colon.
- As is: Unable to add semi-colon or type anything into the editor

https://user-images.githubusercontent.com/29488088/211652657-a4d72292-fa03-4ea9-93fe-7fcec17f2a3b.mov

**Comment by sandyarmstrong** [comment]
@kfam98 do you have LSP enabled? I wouldn't expect to see that error message unless LSP was enabled. I can repro without LSP and without that error in my logs.
