### ISSUE TITLE
IncrementalGenerator caches ReferencedAssemblySymbols too aggressively

### ISSUE THREAD

**Issue by randrewy** [dotnet/roslyn#66341]
My issue looks similar to #48083 but as I've been told **it is about caching generated assembly,** not the generator itself. But I can't figure out what's going wrong.

A have 4 projects:
* ClientApi - references `Grpc.Tools` and contains definitions of services in proto-files
* Generator - generates a class with a list of all GRPC-clients found in `ReferencedAssemblySymbols`
* Implementation - references `Generator` and `ClientApi`
* Program - references `Implementation` and uses generated class

So I have a project with some services and clients generated by `grpc` and I want to autogenerate a class with all grpc-clients as properties.

In `ClientApi` project I have this proto:
```
syntax = "proto3";
package client_api;

service TestService {
    rpc Method1(Message) returns (Message) {}
}

message Message {}
```

In `Implementation` project I can see that this class is successfully generated by my generator:
```cs
using ClientApi;
using Grpc.Core;

#nullable enable
namespace GeneratedApi;

public partial class GeneratedApiBase
{
    public TestService.TestServiceClient TestServiceClient {get; set;}
}
```

But if I try to use it in `Program`
```cs
using GeneratedApi;

Console.WriteLine(new GeneratedApiBase().TestServiceClient);
```
there is this error:
```
Program.cs(3, 42): [CS1061] 'GeneratedApiBase' does not contain a definition for 'TestServiceClient' and no accessible extension method 'TestServiceClient' accepting a first argument of type 'GeneratedApiBase' could be found (are you missing a using directive or an assembly reference?)
```

Manually building projects one-by-one helps to overcome this issue, but then it fails again after adding new service to proto-file.
It looks like as if  `ClientApi` is cached somewhere in a state without files generated by GRPC, and SorceGenerator fails to understand that the appear at some point. 

Here is a [sample_solution.zip](https://github.com/dotnet/roslyn/files/10380574/Program.zip), where
1. building solution will fail
2. rebuilding `Implementation` without dependencies, and building `Program` after that will fix issue

**Comment by jcouv** [comment]
It's not clear from the description whether there is a compiler bug or even a build issue. Please provide a binary log to help confirm that.

**Comment by randrewy** [comment]
What kind of binary log do you want me to provide?

**Comment by jcouv** [comment]
> Manually building projects one-by-one helps to overcome this issue

This tells me we're not dealing with a compiler issue. 
What you want to do is run a build with the `-bl` option in the setup where it produces an error. Then you'll need to review the inputs given to the `Csc` task (that's the task that produces an error, so the [log viewer](https://msbuildlog.com/) will make it easy to find), then you want to figure out which output is missing or incorrect, and trace back where it came from.

**Comment by chsienki** [comment]
Huh, this took me a while to figure out what was going on, but there isn't a bug here. 

When you reference a project, MSBuild by default switches out the regular assembly passed to the compiler for a _Reference_ assembly. This has all the non-public members stripped out of it (See https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies and https://stackoverflow.com/a/49780042/1576746 for a detailed explanation of the how + why).

Your generator is keying off of `__ServiceName` as the filter to decide which assemblies to generate code for. That property is private, and so is not present in the Reference Assembly version of the code. That means your generator is effectively producing different code depending on whether it sees the reference assembly or the implementation one. 

As for a fix, I would recommend keying off something public, so you don't have this issue. If you prefer, you can also disable reference assembly generation for the ClientApi project, by setting `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>`. That way the project the generator is running on will always build against the implementation assembly which has the member present.

**Comment by randrewy** [comment]
Hey! Thank you for looking into it and explaining this behaviour!
Keying off something public for some strange reason doesn't help to overcome the issue, though not producing reference assamblies does help and everything works fine.
