### ISSUE TITLE
Enabling inline diagnostics results in stale "Avoid multiple blank lines" diagnostic 

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#66345]
**Version Used**: Version 17.6.0 Preview 1.0 [33308.44.main]

**Steps to Reproduce**:

1. Open a repository that has IDE2000 enabled; and add multiple blank lines somewhere.
2. Go to the first or second blank line.
3. Press Ctrl+L to delete the line.

**Expected Behavior**: The squiggle and inline diagnostic go away.

**Actual Behavior**: The squiggle goes away, the inline diagnostic stays around. If you scroll away and scroll back, it'll then be gone.

**Comment by ryzngard** [comment]
Looks related to #65209

**Comment by jasonmalinowski** [comment]
@ryzngard This was for the inline diagnostics adornment -- even if diagnostics goes away, it doesn't. @akhera99 I think you said you were able to reproduce this?

**Comment by akhera99** [comment]
> @ryzngard This was for the inline diagnostics adornment -- even if diagnostics goes away, it doesn't. @akhera99 I think you said you were able to reproduce this?

Yeah this reproduces.

**Comment by ryzngard** [comment]
ah gotcha, sorry it looked related to stale diagnostics to me. Thanks for reopening

**Comment by jasonmalinowski** [comment]
@akhera99 Any chance we can fix this for 17.5? It makes the feature somewhat unusable otherwise...
