### ISSUE TITLE
Raw string literals do weird things with unbalanced quotes

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#66368]
If you type, or open a file with, a raw string literal that has unbalanced quotes, like below, the editor gets confused and does weird things. Adding a line, adds multiple blank lines, but then you can't put the caret inside the block of blank lines to fix it.

eg:
```
var x = """"""
    1
    2
    3
    4
    5
    """;
```

See GIF. Note the very quick error popup in the gif, which says "Unexpected null - 99", but flashed up too quick to be captured because I accidentally hit enter.

![RawStringsAreBonkers](https://user-images.githubusercontent.com/754264/211988698-7235b1d4-ff36-4fbc-a5be-5ef182b554cc.gif)

**Comment by CyrusNajmabadi** [comment]
What the what...

**Comment by davidwengier** [comment]
That was exactly my reaction!
