### ISSUE TITLE
"Add explicit cast" quick fix produces a bogus fix

### ISSUE THREAD

**Issue by filipw** [dotnet/roslyn#66369]
**Version Used**: 
First reported for Roslyn `4.5.0-2.22527.10` in OmniSharp (https://github.com/OmniSharp/omnisharp-roslyn/issues/2475) but also reproducible in Visual Studio 17.4.4

**Steps to Reproduce**:

```csharp
short s = 0;
int i = 0;
s += i;
```

Invoke "explicit cast" over last line. [Sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAzgBYD2ATgC7rPoBedAAYA3IyZEAlgDteUwSPFJJxfmCFTlTAL7IdQA===)

**Diagnostic Id**:

`CS0266`

**Expected Behavior**:

```csharp
short s = 0;
int i = 0;
s += (short)i;
```

**Actual Behavior**:

```csharp
short s = 0;
int i = 0;
(void)(s += i);
```

(does not even compile!)

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/56141

**Comment by filipw** [comment]
Ah I didn't see it (tried to search upfront but github search is not great). Thanks.
