### ISSUE TITLE
The `SyntaxGenerator` omits `ref`, `readonly`, `new` keywords for return types.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#66376]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

---

**Version Used**: 4.6.0-1.23059.11 (~main)

**Steps to Reproduce**:
Issue on our side: https://github.com/dotnet/arcade/issues/11881

[SyntaxGenerator.cs#L172](https://github.com/dotnet/roslyn/blob/45046d0a51e7aa1f67e11b9dd00621535f9fe39c/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L172) --> [CSharpSyntaxGenerator.cs#L3384](https://github.com/dotnet/roslyn/blob/45046d0a51e7aa1f67e11b9dd00621535f9fe39c/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L3384) -?-> [ITypeSymbolExtensions.cs#L42](https://github.com/dotnet/roslyn/blob/45046d0a51e7aa1f67e11b9dd00621535f9fe39c/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.cs#L42)

Looks like, we need to extend the `ITypeSymbolExtensions.GenerateTypeSyntax` extension method:
```C#
private static TypeSyntax GenerateTypeSyntax(
            INamespaceOrTypeSymbol symbol, bool nameSyntax, bool allowVar = true)
{
///...
}
```

Examples:
```C#
public ref T GetPinnableReference() { throw null; }
public ref readonly T this[int index] { get { throw null; } }
new bool Add(T item);
public static new int Default { get { throw null; } }
```
After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
```C#
public T GetPinnableReference() { throw null; }
public T this[int index] { get { throw null; } }
bool Add(T item);
public static int Default { get { throw null; } }
```

**Diagnostic Id**:

**Expected Behavior**:

**Actual Behavior**:

**Comment by CyrusNajmabadi** [comment]
Note: we have no facility for supporting 'new'.  It is a source-only construct non-existent in metadata.

**Comment by ericstj** [comment]
@CyrusNajmabadi I see https://github.com/dotnet/roslyn/pull/66445 fixes the `ref` and `readonly` cases 🎉 @smasher164 can you make sure we track the `new` case with an issue in https://github.com/dotnet/sdk.  We can handle it in GenAPI.

**Comment by smasher164** [comment]
> can you make sure we track the `new` case with an issue in https://github.com/dotnet/sdk. We can handle it in GenAPI.

Opened https://github.com/dotnet/sdk/issues/30082

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/66445.
