### ISSUE TITLE
The `SyntaxGenerator` omits accessibility level for accessors

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#66379]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

---

**Version Used**: 4.5.0-3.22601.3 (~main)

**Steps to Reproduce**:
Issue on our side: https://github.com/dotnet/arcade/issues/11935

Fields accessors are generated without accessibility levels.
Example:
```C#
class Foo
{
    public int Bar { get; protected set; }
}
```

After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:

```C#
class Foo
{
    public int Bar { get; set; }
}
```

**Diagnostic Id**:

**Expected Behavior**:

**Actual Behavior**:

**Comment by andriipatsula** [comment]
There are two overloaded methods `AccessorDeclaration`:
https://github.com/dotnet/roslyn/blob/234e15d0b7b74ad1119612ed214939928b5b4aea/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L473
and
https://github.com/dotnet/roslyn/blob/234e15d0b7b74ad1119612ed214939928b5b4aea/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L379-L380

The problem is that for `PropertyDeclaration` we use the first one (without `Accessibility` parameter)
https://github.com/dotnet/roslyn/blob/234e15d0b7b74ad1119612ed214939928b5b4aea/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L356-L360

On the other hand, we don't have information about accessors accessibility on that level. One option is to extend the `class DeclarationModifiers`...

**Comment by jasonmalinowski** [comment]
Assigning this to you @CyrusNajmabadi since you're already reviewing the community PR.
