### ISSUE TITLE
[Bug] Explicit layout with record struct

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/roslyn#66373]
### Discussed in https://github.com/dotnet/roslyn/discussions/66372

<div type='discussions-op-text'>

<sup>Originally posted by **Xyncgas** January 12, 2023</sup>
For example
```F#
[<Struct; StructLayout(LayoutKind.Explicit)>]
 type Dimension2D = 
            {
                [<FieldOffsetAttribute(0)>]
                Memory : Vector2
                [<FieldOffsetAttribute(0)>]
                Width : float32
                [<FieldOffsetAttribute(4)>]
                Height : float32
            }
            with
            static member Zero = { Memory = Vector2.Zero; Width = 0f; Height = 0f; }
```
The point of explicit layout is you can change the memory by changing width / height, or the opposite way by using System.Numerics.Vector2 methods to change the memory

However I noticed that, while it's already hard to create a record with only memory is set
```F#
{Dimension2D.Memory = Vector2.Zero} //Alone doesn't work
```
If I were to do :
```F#
{ Dimension2D.Zero with Memory = Vector2.Multiply(aVector, value) } //Bug : the value remains zero after this no matter what you do
```
Where ```AnotherMemory``` is not zero and so is value, the result is zero for some reason

But if I were to do
```F#
let v = Vector2.Multiply(aVector, value)
{ Dimension2D.Zero with Memory = v; Width = aVector.X; Height = aVector.Y } //Works
```
Even still, now what's the point of having explicit layout if I am losing one of the big advantage that is to assign multiple values at once

It gives me a feeling that either I can't have record struct with explicit layout in F# like I can in C#, or there is a bug with it</div>

**Comment by ryzngard** [comment]
This looks like a bug with the https://github.com/dotnet/fsharp compiler. It doesn't look like I can transfer the issue there, so you'll have to file separately.
