### ISSUE TITLE
Add support for a generation of a finalizer (destructor) in the `SyntaxGenerator`

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#66374]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

## Background and Motivation
The `SyntaxGenerator.Declaration(ISymbol symbol)` does not handle `SymbolKind.Method` as a result the exception ArgumentException("Symbol cannot be converted to a declaration") is thrown. [SyntaxGenerator.cs#L575](https://github.com/dotnet/roslyn/blob/55259597ad41ac41e0d1888fa52a92e73318b57e/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L575)
Issue to track on our side: https://github.com/dotnet/arcade/issues/11938

Example:
```C#
class Object
{
    ~Object() {}
}
```

## Proposed API
Entry point: [SyntaxGenerator.cs#L551](https://github.com/dotnet/roslyn/blob/23fdd87e45d33399b49931a885c8ff954bc16f4e/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L551)
```diff
var method = (IMethodSymbol)symbol;
+if (method.MethodKind == MethodKind.Destructor)
+{
+    return DestructorDeclaration(method, method.Name);
+}

//...

+ private static SyntaxNode DestructorDeclaration(IMethodSymbol method, string name) {}
```

**Comment by CyrusNajmabadi** [comment]
Could you clarify why you need to generate this?  The presence/absense of a destructor should be an impl detail that isn't really relevant to anyone looking at the type.

**Comment by andriipatsula** [comment]
Hello @CyrusNajmabadi 
I believe you are right. I just found that if assembly contains member-destructor, the `SyntaxGenerator.Declaration` throws an ArgumentException. We can filter out such members on our side.

/cc @ViktorHofer, @ericstj what do you think?

**Comment by ericstj** [comment]
We do include finalizers in our reference assemblies. These can help a derived class understand if they should define the finalized themself or not if needed. 

We consider removing the finalizer breaking https://github.com/dotnet/runtime/blob/b5381bf99531b88a7ddaad7a03ccacf1b92fff63/docs/coding-guidelines/breaking-change-rules.md#code
And it’s presence in the reference assembly does help us monitor such breaking changes.
