### ISSUE TITLE
`SyntaxGenerator.Declaration` missing interface modifiers

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66387]
https://github.com/dotnet/roslyn/blob/89976fde42e8a7cad791798653279a47e2c5599d/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L600-L622

Modifiers are missing in interfaces, unlike classes and structs (e.g, `file`).

**Comment by Youssef1313** [comment]
cc @CyrusNajmabadi @kinkeadian25

**Comment by CyrusNajmabadi** [comment]
SynGen is basically used by a subset of features, and contains with functionally to work well for them. There's a new customer using is to roundtrip all symbols, so it's finding holes that haven't been relevant for it features that sit on it.

Also, most of our features that require a high degree of customizability end up using a different code gen layer that is not exposed. It would be nice to unify all of this. But it hasn't ever been a priority, and it risks many regressions.

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of movement.
