### ISSUE TITLE
Add `Use pattern matching` diagnostic for list patterns

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66388]
Example code:
```cs
class MyClass
{
    void M(IReadOnlyList<int> ints)
    {
        if (ints.First() == 1)
        {

        }
    }
}
```
Expected fix:
```cs
class MyClass
{
    void M(IReadOnlyList<int> ints)
    {
        if (ints is [1, ..])
        {

        }
    }
}
```
Same with `Last()` or indexer access, e.g. `ints[0] == 1` -> `ints is [1, ..]`.
This analyzer/fix should also support nested patterns:
```diff
class MyClass
{
    void M(IReadOnlyList<string> ints)
    {
-       if (ints[0] is { Length: > 5 })
+       if (ints is [{ Length: > 5 }, ..])
        {

        }
    }
}
```
And ideally concatenated conditions:
```diff
class MyClass
{
    void M(IReadOnlyList<string> ints)
    {
-       if (ints[0] is not null &&
-           ints[1] is { Length: > 7 })
+       if (ints is [not null, { Length: > 7 }, ..])
        {

        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
I'm most wary about the first case.  Using `.First()` is clear and idiomatic.  The other cases are more interesting and i can see the pattern making things somewhat better and simpler.  Perhaps there needs to be at least two items checked in the list (and not just the first/last) to warrant a pattern suggestion here.

**Comment by Youssef1313** [comment]
Note: `First` would throw if the collection is empty, while refactoring it to list patterns won't throw.

I'm aware that codefixes are not guaranteed to preserve the same behavior, but this worth having a separate ID is accepted with a [WarningAnnotation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.codeactions.warningannotation?view=roslyn-dotnet-4.3.0).

**Comment by CyrusNajmabadi** [comment]
Generally, I think I'd be ok with not preserving throwing semantics.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
