### ISSUE TITLE
The `SyntaxGenerator` adds redundant `sealed` keyword for delegate types.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/roslyn#66381]
## Context
One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. 

Unfortunately, the current [SPRB](https://github.com/dotnet/source-build-reference-packages/tree/main/src/referencePackageSourceGenerator) (Source Build Reference Package generation tooling), [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

We developed a [Roslyn-based GenAPI](https://github.com/dotnet/sdk/tree/main/src/GenAPI) tool that aims to replace the CCi-based version. During the testing we found several bugs in the API (Workspaces) all summarized at [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue in dotnet/arcade.

---

**Version Used**: 4.5.0-3.22601.3 (~main)

**Steps to Reproduce**:
Issue on our side: https://github.com/dotnet/arcade/issues/11937
Example:
```C#
namespace Foo
{
    public delegate bool SyntaxReceiverCreator(int a, bool b);
}
```

After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:

```C#
namespace Foo
{
    public sealed delegate bool SyntaxReceiverCreator(int a, bool b);
}
```

as a result: `Build falure: error CS0106: The modifier 'sealed' is not valid for this item `

**Diagnostic Id**:

**Expected Behavior**:

**Actual Behavior**:

**Comment by Youssef1313** [comment]
Might be related to https://github.com/dotnet/roslyn/issues/66171

Though I'm very curious how can this happen given the allowed modifiers are correct here:

https://github.com/dotnet/roslyn/blob/89976fde42e8a7cad791798653279a47e2c5599d/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1505-L1518
