### ISSUE TITLE
False negative for IDE0060 (parameter not used) when combining local functions and lambdas

### ISSUE THREAD

**Issue by Blokyk** [dotnet/roslyn#66391]
This is a very nitpicky issue, and it's not exactly a scenario that would actually happen IRL if I had to guess, but I'm quite curious as to why this happens, since detecting if parameters are captured in lambdas works fine in a method's main body

---

**Version Used**: 4.5.0-2.22527.10 (`401447a2`)

**Steps to Reproduce**:

1. Create a normal method with one or more parameters
2. Define a local function inside of it, and use one of the parameters inside this function's body, *but do not call the local function in the method body*
    - The parameters should all be marked with IDE0060, although the one used inside the local function gets the "initial value never used" version, while the other ones get the normal "unused parameter"
3. Add some sort of lambda expression (that doesn't capture the param) inside the local function's body
    - The parameter that was used in the local function won't be marked with IDE0060 anymore

[SharpLab repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCecAmIA1AD4ACATAIwCwAUGQAwAEZVAdADKwCOA3PXpkAzKwrMAwswDe9ZvOYB6RcwDkAY1XMAFhADOzAJIARAKKNGANkZxmwAK4JmMAPZPVe1XIUjWAFmYAWSoACjYWPVt1XXRmdQBKGW8FBVgnLBcXEMTZOhT8hVMYezAMCGAAG1R2ACUIGABzVBCbZipGePYAZVQq9QQQqGYAXgA+Zih4gTyC/LYAThC9KeTZ+TIAdmZGabWAX1WDmflV5Ts3bTVPZnr8NU0b9FRmSHQAa1Q7gHcoBEuTcxWRinFSuBDlCp4HQuL6oNDoWwGJoIAx/Z4AIlgvygEAqzGQuPszxgcIwzHsek+6PxGD0UBc8BBzC+2igVXuWmRqO0z0ozHRTzALjQ5OKlLuAAcIOgIKUEBh0atfGQAoEKGF2sxInEYnEcqsUmlmBksvrjmtmEUSmVKtU6o1mq12lMlKCXMwKrLgPgIAbZgslitzWtNttdrMjms/fIzupcRVYA1mGjjfYYP16TBmWy8SF1C50E9+pDEoLhc80dHXUYzBZrMx8DiGq49AgoOpjegXGArl5gwoq8oTdlw/IjnsgA)

**Diagnostic Id**: IDE0060

**Expected Behavior**:
The parameter used inside the local function should be marked with IDE0060 if the function is never called, and shouldn't if it's actually called at some point.

**Actual Behavior**:
Said parameter is actually only marked with IDE0060 if the local function doesn't contain a lambda expression (whether it captures it or not...), even if the function is never actually called in the methpd's body

**Comment by CyrusNajmabadi** [comment]
The language (and by extension teh compiler) recognizes the flow of data/use with local functions (by tracking where they are called in code, and doing the analysis precisely there).    So an uncalled local function is viewed differently as one that is called.

No such understanding is given for lambdas since there is no way to know if they are invoked at all.

**Comment by Blokyk** [comment]
Right, but since the parameter isn't used in the lambda, I wouldn't expect it to affect the data flow analysis for it, that's what I'm more surprised by.

**Comment by mavasani** [comment]
> Right, but since the parameter isn't used in the lambda, I wouldn't expect it to affect the data flow analysis for it, that's what I'm more surprised by.

@Blokyk The flow analysis inside IDE0060 analyzer is designed to be pretty conservative in presence of lambdas and local functions. We can definitely make it smarter to handle more cases, such as understanding captures, passing these methods by reference as arguments to method calls, etc., but that can present more challenging cases leading to unexpected false positives from unhandled code patterns. We decided to instead keep the flow analysis conservative and err towards more false negatives.

**Comment by Blokyk** [comment]
Right, makes sense, I'll close this issue then.
