### ISSUE TITLE
OutputWIndowLogger does now follow WindowLogging guidelines

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/roslyn#66397]
Per @davidwengier:

> The [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsoutputwindowpane.outputstringthreadsafe?view=visualstudiosdk-2022) say to try the non-message-pump version of this first, then fallback to this if that fails.
> 
> Here is how I did it in Roslyn, after getting a Prism bug about thread crimes:
>https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/PdbSourceDocument/PdbSourceDocumentOutputWindowLogger.cs#L66-L73

**Comment by mavasani** [comment]
@davidwengier do you know who would be a good person to look at this?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative and due to lack of movement.  If this is an issue this should be assigned to a person/milestone to actually get done.
