### ISSUE TITLE
Remove overload in IAsyncOperationListener that we're keeping for back compat.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#6640]
Change to revert here: https://github.com/dotnet/roslyn/pull/6639

We can remove this once we get Jared' experimental feature in place and can have TS just building off our latest nuget feed.

**Comment by Pilchie** [comment]
Tagging @paulvanbrenk I think we determined that this was a machine setup issue, and this should just be removed now.

**Comment by paulvanbrenk** [comment]
Yep that was a setup issue.
