### ISSUE TITLE
High CPU Utilization with Very Basic Keypresses

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66410]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/High-CPU-Utilization-with-Very-Basic-Key/10247502)._

Internal ticket: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1714591

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.4]
Please see attached.  I am seeing high CPU utilization that is occurring in a basic .cs file.  Upwards to 50% with delays/hitches on the UI thread.

This seems new for 17.5

---
#### Feedback Bot on 1/8/2023, 06:56 PM: 

(private comment, text removed)
#### Feedback Bot on 1/10/2023, 08:51 AM: 

(private comment, text removed)
#### Cyrus Najmabadi [MSFT] on 1/11/2023, 00:26 PM: 

(private comment, text removed)
#### Mike-E-angelo on 1/11/2023, 01:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jaredpar I think someone on compiler shoudl likely take a look here.  Looking into the trace (in the attached azdo bug) there is an enormous amount of time (>50%) in BindAssemblyReferences:

![image](https://user-images.githubusercontent.com/4564579/212385841-9a777afa-7c19-4dc9-b302-c6f545f9fefa.png)

This ends up calling through ResolveReferncedAssembly, which then does an absolutely enormous amount of calls to AssemblyIdentityComparer.Compare:

![image](https://user-images.githubusercontent.com/4564579/212385946-29760561-8e34-4e6c-8f1b-d6b95715b6b2.png)

Looking at these methods, tehre is a lot of linear work being done where each item is compared against N other items.  For example, within BindAssemblyReferences where a linear walk is done, and each item is them resolved against all M AssemblyData's already present:

![image](https://user-images.githubusercontent.com/4564579/212386242-4ce2c669-cd0b-48eb-9651-98da77777a17.png)

Then inside ResolveAssemblyReference:

![image](https://user-images.githubusercontent.com/4564579/212386292-8dacf7b9-8ee2-48d0-b853-f18812344e84.png)

This then bubbles down into string comparisons of names (which i'm guessing may be very long, with a ton of common prefix content) of assembly identifies.

My guess is that in this scenario there are so many assemblies that this sort of algorithm ends up scaling very poorly, which then impacts all higher layers.  I don't have any strong suggestions on what to do here as this isn't an area of familiarity to me.  However, it might make a lot of sense to do a prepass on these arrays, producing a map keyed off things like the names that are checked.  Those maps would just be O(n) to build.  Then, when looking at an item, trying to find if hter'es a corresponding item in the map would be O(1) to see if htere are any potential hits that would then be compared.  This could potentially help a lot.  However, someone who is more of an expert here would have to look to see.

**Comment by jaredpar** [comment]
@AlekseyTs PTAL

**Comment by chsienki** [comment]
#66430 was reverted as part of a VS regression investigation. [Internal link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1733125) has the details on the regression that occurred.

**Comment by AlekseyTs** [comment]
@chsienki Could you please provide specific details about the regression? It looks like the provided link doesn't have any details and information there requires some non-trivial analysis/interpretation.

**Comment by chsienki** [comment]
Honestly, I didn't do a particularly deep analysis as to the _why_ of the results, but we're seeing a *lot* more strings allocated, and reverting that PR seems to fix it. 

![image](https://user-images.githubusercontent.com/16246502/233459524-74dfe7e0-ff89-4d18-b3ae-a2af6ea30251.png)

Your PR does seem to be adding strings to track the assembly references, so if it's called a lot it could account for the difference.

**Comment by AlekseyTs** [comment]
@chsienki If we want to revisit the original issue, we need a clear and detailed understanding what was the problem with the previous approach,

**Comment by davkean** [comment]
Folks, all regressions have traces associated with it that using PerfView you can diff from prior builds. Note, we've caught this issue in our CPU tracing too: https://prism.vsdata.io/failure/?eventType=cpu&failureType=dualdirection&failureHash=ac8dc2a3-4bb9-9489-ea96-6029eae9bdd5, it also has traces attached.

**Comment by Mike-E-angelo** [comment]
Thank you for any update on this issue reported on [January 13th, 2023](https://howlongagogo.com/date/2023/january/13).  My environment continues to be plagued [with constant CPU utilization after the most basic of keypresses](https://github.com/dotnet/razor/issues/8371#issuecomment-1682691987).

**Comment by CyrusNajmabadi** [comment]
@Mike-E-angelo please provide traces with your report. Thanks!

**Comment by Mike-E-angelo** [comment]
[Hi @CyrusNajmabadi please note that I already did this with [the original ticket on developercommunity](https://developercommunity.visualstudio.com/t/High-CPU-Utilization-with-Very-Basic-Key/10247502).  This issue was then fixed, deployed, and reverted.

**Comment by CyrusNajmabadi** [comment]
@Mike-E-angelo many fixes have gone in since then. Please file updated traces (against latest public preview) so we can see what the hot spots are now. Thanks.

**Comment by Mike-E-angelo** [comment]
> @Mike-E-angelo many fixes have gone in since then. 

I recall this one being more tricky and difficult to encounter, and happened after many hours of development.  I can keep an eye out for my own trace, but it looks like you have one from [just last week from your own personnel](https://github.com/dotnet/roslyn/issues/66410#issuecomment-1681518686) so it is very much active and alive.
