### ISSUE TITLE
Compilation fails when pattern matching and DoesNotReturnIf are combined

### ISSUE THREAD

**Issue by virzak** [dotnet/roslyn#66426]
**Version Used**: main (12 Jan 2023)

**Steps to Reproduce**:

```cs
using System;
using System.Diagnostics.CodeAnalysis;

class C
{
    public static double GetDouble(object o)
    {

        AssertTrue(o is double d);
        return d;
    }

    static void AssertTrue([DoesNotReturnIf(false)] bool b)
    {
        if (!b) throw new Exception("Exception");
    }
}
```

**Expected Behavior**:
Expect this to compile

**Actual Behavior**:
error CS0165: Use of unassigned local variable 'd'

**Additional information**:
This pattern is something that happens in test projects and resolving this would eliminate additional checks.

**Comment by CyrusNajmabadi** [comment]
These attributes only affect NRT analysis (which is best effort and can be incorrect). They do not affect definite assignment analysis which is precise and can't trust random attributes (which might be incorrect). 

So I think this is by design. @RikkiGibson ?

**Comment by Youssef1313** [comment]
I agree this is by-design. I'd probably rewrite it as follows:

```csharp
using System;

class C
{
    public static double GetDouble(object o)
    {

        AssertOfType<double>(o, out var d);
        return d;
    }

    static void AssertOfType<T>(object o, out T t)
    {
        if (o is not T) throw new Exception("Exception");
        t = (T)o;
    }
}
```

**Comment by RikkiGibson** [comment]
Agree. The way I think about this is, the failure mode for nullable if a method is annotated incorrectly is that the user unexpectedly reads a null, while the failure mode for definite assignment is the user unexpectedly reads uninitialized memory, which we consider to be more dangerous.
