### ISSUE TITLE
[Enhancement] Generate code between functions is tabbed up to tab level

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/roslyn#66424]
![image](https://user-images.githubusercontent.com/7494772/212449134-51806eb0-2da8-46fa-8fff-cf745ce95b15.png)

I like the autogenerated code emitted by omnisharp for vscode.

I do not like how when they get generated empty lines don't match the current tab level, as seen in the image.

People seem to really like their code prettyfiers but I don't use any, mostly for the fact it eliminates the tabs. My tabs are sacred to me and its purpose for being there is so that I don't have to tab to make a function or deal with the existence of empty lines since the editor when pressing enter will give you one. You also will get tabs emitted when you select a function's closing brace and press enter to create said function (the only way to do it besides clicking into the 'pit' to tab it up then to create a function).

**Comment by CyrusNajmabadi** [comment]
Generally speaking, roslyn never does this (and it's not likely to ever do it). It's up to the host (like VS) to place the carpet at the right location, and generate at the right location, even if there is no whitespace there. 

VS definitely already had support for this. This sounds like this may be a vscode issue then. In which case, the issue should likely be opened in their repo. Thanks!

**Comment by tilkinsc** [comment]
I'd assume that this setting here should govern the whitespace since I disabled trailing whitespace deletion, which is a setting in the extension. Perhaps a regression then. I will continue to explore this elsewhere.
![image](https://user-images.githubusercontent.com/7494772/212450607-4bc5cc36-7421-41c3-adad-7e071b2d6cca.png)

**Comment by 333fred** [comment]
This is a roslyn feature request. We might end up deciding not to support it, but the ask is to have the text edit that we generate when generating code have tabs in the indicated location, which is not an editor setting.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not doing this.
