### ISSUE TITLE
Sticky scroll should display case lines of switch statements

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#66432]
It's not uncommon for the contents of a `case` to be long enough to off-screen in certain kinds of code. I started noticing this at my day job. Here's a random example from the Roslyn codebase. The case right before the `{` line is really what you want to see, not the `{`. And even if there was no block statement, the `case` line is still equally helpful to see.

![image](https://user-images.githubusercontent.com/8040367/212559050-36285dcc-f113-4b8e-bc3b-a1cec21148ec.png)

**Comment by jnm2** [comment]
@CyrusNajmabadi asked me to file here.

**Comment by CyrusNajmabadi** [comment]
@olegtk I think sticky scroll is handled entirely by the platform?  Are there extension points to help out here?

**Comment by olegtk** [comment]
Sticky scroll uses IStructureTag as a data source and specifically IStructureTag.HeaderSpan to identify lines that should be sticky. In this particular case seems like when the first visible line is inside "{" block inside "case" statement we get IStructureTag, whose HeaderSpan points to the span of "{".

**Comment by CyrusNajmabadi** [comment]
Ok.  I'll look into this on our side.  It may just be a case (no pun intended) of making 'case clauses' have structure guides.

**Comment by olegtk** [comment]
IStructureTag has a bunch of other properties that control visualization of structure guides, let me know they are not sufficient to cover this scenario.
Btw, we are also considering to expand IStructureTag to address the "else" issue (just showing "else" line without corresponding "if" line is useless), e.g. by adding IStructureTag.PrimaryHeaderSpan or something like this to let IStructureTag representing "else" block point to its "if" span.
