### ISSUE TITLE
Refactor primary view selection so we have the same code path for nav bars and document outline

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#66448]
_Originally posted by @jasonmalinowski in https://github.com/dotnet/roslyn/pull/65641#discussion_r1065202499_

**Comment by jasonmalinowski** [comment]
Happy to assign this to me too since I'm the one requesting it. Just waiting for the document outline rewrite to land first.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we are doing this, this needs to go in a specific milestone to eb done.
