### ISSUE TITLE
Visual Studio 2022 makes double quote escaped when pasting copied text

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-makes-double-quote-es/10253048)._

---
Visual Studio 2022 makes double quote escaped when pasting copied text. I couldn't find any option to turn this off.

To reproduce
1. Type in: ("
1. Type in on the next line: ")
2. Copy text from the first line Ctrl+C
3. Paste at the end of the second line, the result is: ("\")

Should be ("") instead.

---
#### Feedback Bot on 1/15/2023, 06:49 PM: 

(private comment, text removed)
#### Feedback Bot on 1/17/2023, 09:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by iiKuzmychov** [comment]
Autoescaping on pasting string it`s a cool feature. If you want to cancel escaping just click ctrl+z after pasting the text.

**Comment by DaveLaa** [comment]
This "workarround" (with ctrl+z) doesn't work for multiline partial selection (select multiline region with holding alt). On Paste this will be quoted and with ctrl+z it appears all in one line. The multiline partial selection feature is not available any more on paste in VS 17.x.x. within strings.
Is it so hard for you to just put an option in VS to disable this absolute annoying "i know better than you" feature?

**Comment by CyrusNajmabadi** [comment]
> Is it so hard for you to just put an option in VS

@DaveLaa there is an option for this:

![image](https://github.com/dotnet/roslyn/assets/4564579/38ac4322-db96-4501-a71b-b70003f17018)

**Comment by DaveLaa** [comment]
I deactivated this checkbox but still it is not working... VS still doesnt paste the multiline partial selected clipboard content as multiline edit in text.

Case you have:

    public static readonly string[] Files = [
        "file1.jpg",
        "file2.jpg",
        "file3.jpg",
        "file4.jpg",
        "file5.jpg"
    ];

Now you want to paste something in every file name like "C:\\temp\\". You copy this as partial selection and want to past it in front of the first file to be placed partially in all files. You would like to get:

    public static readonly string[] Files = [
        "C:\\temp\\file1.jpg",
        "C:\\temp\\file2.jpg",
        "C:\\temp\\file3.jpg",
        "C:\\temp\\file4.jpg",
        "C:\\temp\\file5.jpg"
    ];

But what you get is:

    public static readonly string[] Files = [
        "C:\\\\temp\\\\\r\nC:\\\\temp\\\\\r\nC:\\\\temp\\\\\r\nC:\\\\temp\\\\\r\nC:\\\\temp\\\\\r\nfile1.jpg",
        "file2.jpg",
        "file3.jpg",
        "file4.jpg",
        "file5.jpg"
    ];

And if you then hit ctrl-z, you get:

    public static readonly string[] Files = [
        "C:\\temp\\
C:\\temp\\
C:\\temp\\
C:\\temp\\
C:\\temp\\
file1.jpg",
        "file2.jpg",
        "file3.jpg",
        "file4.jpg",
        "file5.jpg"
    ];

It is just not working any more...

**Comment by CyrusNajmabadi** [comment]
@DaveLaa that would be another feature then, not us.  I'd recommend filing an issue with that specific case (and the options you have enabled or disabled) on developercommunity.

**Comment by Tyler-H** [comment]
@CyrusNajmabadi  Disabling the feature you shared in your screenshot fixes the issue Dave mentioned in the June 24th post, FWIW, so it _is_ the same feature causing both types of unexpected behaviors.
