### ISSUE TITLE
try formatting does not put { on new line

### ISSUE THREAD

**Issue by miloush** [dotnet/roslyn#6645]
Automatic brace completion setting off. All new line settings default.
```C#
try {
|
```
Type `}`. Actual:
```C#
try {
}|
```
Expected:
```C#
try
{
}|
```
like in Visual Studio 2013.

This breaks the workflow when you hit up arrow key and enter, expecting to end up writing the body of the try block.

When you format the document, the brackets go where expected, suggesting that "Automatically format completed block on }" does not work for the case of `try`.

**Comment by diryboy** [comment]
Similar to #6628

**Comment by miloush** [comment]
@diryboy that one reportedly affects the format document functionality, while this does not
