### ISSUE TITLE
ForAttributeWithMetadataName in IIncrementalGenerator failing with ArgumentException

### ISSUE THREAD

**Issue by zbynek001** [dotnet/roslyn#66451]
**Version Used**: 
Visual studio: 17.4.4
Microsoft.CodeAnalysis: 4.4.0.0

**Steps to Reproduce**:

1. Create IIncrementalGenerator using ForAttributeWithMetadataName
2. In the core remove attribute to trigger generator in one file
3. Switch to another file using the generator, navigate to definition
4. Repeat combinations of above until getting ArgumentException from the generator

**Expected Behavior**:

No exception thrown

**Actual Behavior**:

The generator will stop working with following error:

Warning	CS8785	Generator '...Generator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'		Generator threw the following exception:
'System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.SyntaxValueProvider.<>c__DisplayClass11_0`1.<ForAttributeWithMetadataName>b__0(ValueTuple`2 tuple, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass0_0`2.<WrapUserFunction>b__0(TInput input, CancellationToken token)'.

**Comment by zbynek001** [comment]
looks like this is similar to #64841
And it happens also in VS 17.5.0 Preview 3

**Comment by zbynek001** [comment]
did some mode digging, and it seems to be related to a caching behavior when removing items.

I've a generator which is extending classes having Generate attribute with generated partial class.
And I'm able to reproduce it all the time with a bigger project having quite many (hundreds, thousands) of such classes. 
And my steps to reproduce are as simple as: 
- have 2 files (A.cs, B.cs) open i VS having those attributes
- in A.cs, comment out the attribute
- switch to B.cs

That's in my case enough to trigger it. Which makes it very hard to work with such generator, since basically anything can crash it :/

So far, I was not yet able to create a simple project to reproduce it.


After some debugging, the issue happens here:

https://github.com/dotnet/roslyn/blob/e1ee2f544a7a4f8d536278bed4e180c54919276e/src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithSimpleName.cs#L108-L111

before the `Where(...)`, the compilation still contains all SyntaxTrees, after it, there might be a SyntaxTree not belonging to it

**Comment by zbynek001** [comment]
hmm, and I can reproduce it not only when removing items, but also when adding items...

**Comment by CyrusNajmabadi** [comment]
@jcouv Is this the issue you fixed with stale entries in the node table?

**Comment by zbynek001** [comment]
I think i'm getting closer to the underlying issue and looks like it's related to index mismatch in `TransformNode` when accessing data from `previousTable`. It's relying on `_states.Count`, but that might match item unrelated to the source `entry`, leading to issues in the `newTable`

Here is what happens in our case, and how the data looks in `previousTable`, `sourceTable` and `newTable` looks like in the `Where(...)` step, and one step later in the pipeline.


Here is detail of what exactly happens in our project.
There are many files inside, many of them, but not all, contain classes with Generate attribute.
And this is what happen, when in one file called `UpdateInjectSriptInnerActions.cs` we remove the Generate attribute

### 1. step - Where(ContainsAttributeList)

Related part of data from `TransformNode.UpdateStateTable` below.
The item with the deleted attribute has index 674 in `previousTable`.

| Index | sourceTable | previousTable | newTable |
|---|---|---|---|
| 665 | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Cached) | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Cached) | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Cached) |
| 666 | Actors\Configuration\TemplateType\Events\CreateValidationStarted.cs   (Cached) |   |   |
| 667 | Actors\EventStoreCleaner\Worker\Events\ConfigurationUpdated.cs   (Cached) |   |   |
| 668 | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Cached) | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Cached) | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Cached) |
| 669 | Actors\Configuration\PredictiveScore\Commands\GetPredictiveScoreInfo.cs   (Cached) |   |   |
| 670 | Actors\Configuration\Actions\InjectHtml\Events\InjectHtmlActionConfigurationUpdated.cs   (Cached) |   |   |
| 671 | Actors\Configuration\Collection\CollectionCampaignsStats\Commands\GetCollectionCampaignPotentialChartData.cs   (Cached) |   |   |
| 672 | Actors\Tracking\User\UserOrganization\UserCollection\Events\PersonalizationAssetUpdated_v1.cs   (Cached) |   |   |
| 673 | Actors\Configuration\Modules\ModuleConfigurationEx.cs   (Cached) |   |   |
| 674 | Actors\Configuration\EventType\Commands\CreateEventType.cs   (Modified) | **Actors\Configuration\Actions\InjectScript\Commands\UpdateInjectSriptInnerActions.cs   (Cached)** | **Actors\Configuration\Actions\InjectScript\Commands\UpdateInjectSriptInnerActions.cs   (Removed)** |
| 675 | DataLake\User\UserCollection\PersonalizationAssetRemovedEentHubModel.cs   (Modified) |   |   |
| 676 | Actors\Configuration\Language\Commands\CreateLanguage.cs   (Modified) |   |   |
| 677 | Actors\EventStoreCleaner\Coordinator\Events\SettingsUpdated.cs   (Modified) |   |   |
| 678 | Actors\Configuration\Campaign\Events\SegmentHandoverCampaignDeleted.cs   (Modified) |   |   |
| 679 | DataLake\User\UserCollection\LifeCycleStatusEventHubModel.cs   (Modified) |   |   |
| 680 | Actors\Configuration\Actions\Overlay\Dimensions.cs   (Modified) |   |   |
| 681 | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Modified) |   | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Added) |
| 682 | DataLake\User\UserCollection\BasketVoucherCodeUsageEventHubModel.cs   (Modified) | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Cached) | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Removed) |
| 683 | Actors\Tracking\User\UserOrganization\UserCollection\Events\CrossSellingOptionsConfigurationIdReset.cs   (Modified) |   |   |
| 684 | Actors\Portal\PortalUser\Events\DataRolePermissionsUpdated.cs   (Modified) |   |   |
| 685 | Actors\RetentionIndexReader\Coordinator\WorkerStatus.cs   (Modified) |   |   |
| 686 | ViewModels\Collection\CollectionInfo.cs   (Modified) |   |   |
| 687 | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Modified) |   | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Added) |
| 688 | ViewModels\LeadTypeMapping\LeadTypeMappingModel.cs   (Modified) | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Cached) | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Removed) |
| 689 | Actors\Configuration\TemplateType\Events\TemplateTypeCreated.cs   (Modified) |   |   |
| 690 | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Modified) |   | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Added) |
| 691 | Actors\Tracking\User\UserOrganization\UserCollection\Commands\ApiUserCollectionCommands.cs   (Modified) | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Cached) | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Removed) |
| 692 | Actors\Configuration\Language\Events\ValidationFailed.cs   (Modified) |   |   |
| 693 | Actors\Configuration\Organization\Commands\CreatePayloadValueExtractionDefaultConfiguration.cs   (Modified) |   |   |
| 694 | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Modified) |   | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Added) |
| 695 | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Modified) | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Cached) | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Modified) |
| 696 | ViewModels\PortalUser\PortalUserModel.cs   (Modified) | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Cached) | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Removed) |
| 697 | ViewModels\Language\LanguageModel.cs   (Modified) |   |   |

inside the `newTable`, the deleted item is marked as deleted, and all following items are there twice, once as `Removed` and then as `Added`, or as `Modified`, if on the same index was previously another item with Generate attribute.

This part looks ok so far, since all the items after the deleted one are `Modified` in the `sourceTable`.



### 2. step - Transformation after the Where

Again, related part of data from `TransformNode.UpdateStateTable` below.
The item which had the Generate attribute deleted (`UpdateInjectSriptInnerActions.cs`) has now index 130.

| Index | sourceTable | previousTable | newTable |
|---|---|---|---|
| 127 | Actors\Configuration\Collection\CollectionRecommendedOptions\Commands\GetRecommendedOptionsV2Parameters.cs   (Modified) | Actors\Configuration\Collection\CollectionRecommendedOptions\Commands\GetRecommendedOptionsV2Parameters.cs   (Cached) | Actors\Configuration\Collection\CollectionRecommendedOptions\Commands\GetRecommendedOptionsV2Parameters.cs   (Cached) |
| 128 | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Modified) | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Cached) | Actors\Global\Utilities\Saga\OrganizationOffboard\Commands\NotifyEventStoreCleanerStopped.cs   (Cached) |
| 129 | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Modified) | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Cached) | Actors\Configuration\Modules\MerkleGetApi\Events\OrganizationModuleRelationUpdated.cs   (Cached) |
| 130 | **Actors\Configuration\Actions\InjectScript\Commands\UpdateInjectSriptInnerActions.cs   (Removed)** | **Actors\Configuration\Actions\InjectScript\Commands\UpdateInjectSriptInnerActions.cs   (Cached)** | **Actors\Configuration\Actions\InjectScript\Commands\UpdateInjectSriptInnerActions.cs   (Removed)** |
| 131 | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Added) | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Cached) | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Added) |
| 132 | Actors\Global\Configuration\Events\PortalUsersRolesMigrated.cs   (Removed) | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Cached) | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Removed) |
| 133 | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Added) | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Cached) | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Added) |
| 134 | Actors\Configuration\Collection\Commands\UpdateActionCategoryEnvironmentFilters.cs   (Removed) | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Cached) | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Removed) |
| 135 | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Added) | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Cached) | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Added) |
| 136 | Actors\Configuration\PredictiveScore\Commands\CreatePredictiveScore.cs   (Removed) | Actors\Configuration\Modules\RecommendedOptionsV3\Commands\UpdateModule.cs   (Cached) | Actors\Configuration\Modules\RecommendedOptionsV3\Commands\UpdateModule.cs   (Removed) |
| 137 | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Added) | Actors\Configuration\SegmentHandling\Commands\UpdateSegmentHandling.cs   (Cached) | Actors\Configuration\Collection\Events\CampaignAdded_v4.cs   (Added) |
| 138 | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Modified) | Domain\User\Interest_v2.cs (Cached) | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Modified) |
| 139 | Actors\Tracking\IpHash\Events\UsersRemoved.cs   (Removed) | Actors\Configuration\Modules\MerkleGetApi\Events\MerkleGetApiModuleUpdated.cs   (Cached) | Actors\Configuration\Modules\MerkleGetApi\Events\MerkleGetApiModuleUpdated.cs   (Removed) |
| 140 | Actors\Configuration\Modules\RecommendedOptionsV3\Commands\UpdateModule.cs   (Added) | Actors\Configuration\Collection\Events\PayloadValueExtractionModuleConfigurationSet.cs   (Cached) | Actors\Configuration\Modules\RecommendedOptionsV3\Commands\UpdateModule.cs   (Added) |
| 141 | Actors\Configuration\Modules\RecommendedOptionsV3\Commands\UpdateModule.cs   (Removed) | Actors\Configuration\Actions\Commands\UpdateActionURLFilterConfiguration.cs   (Cached) | Actors\Configuration\Actions\Commands\UpdateActionURLFilterConfiguration.cs   (Removed) |
| 142 | Actors\Configuration\SegmentHandling\Commands\UpdateSegmentHandling.cs   (Added) | Actors\Configuration\Actions\Overlay\Events\OverlayActionConfigurationUpdated_v1.cs   (Cached) | Actors\Configuration\SegmentHandling\Commands\UpdateSegmentHandling.cs   (Added) |
| 143 | Actors\Configuration\SegmentHandling\Commands\UpdateSegmentHandling.cs   (Removed) | Actors\Configuration\Campaign\Events\CampaignUpdated_v2.cs   (Cached) | Actors\Configuration\Campaign\Events\CampaignUpdated_v2.cs   (Removed) |
| 144 | Domain\User\Interest_v2.cs   (Added) | Actors\Tracking\User\UserOrganization\UserCollection\SurveyResponseModel.cs   (Cached) | Domain\User\Interest_v2.cs (Added) |
| 145 | Domain\User\Interest_v2.cs   (Removed) | Actors\Portal\DataRole\Events\ValidationStarted_v1.cs   (Cached) | Actors\Portal\DataRole\Events\ValidationStarted_v1.cs   (Removed) |


**And here is the issue!**

Items, which have state `Removed` inside `sourceTable`, take the item on the same index from `previousTable` and change the status to `Removed` and add it to the `newTable`.
Since the index inside `sourceTable` was change in the previous step due to Addded + Removed, it doesn't match the index inside `previousTable` 

And this ends up with duplicates or invalid items inside the `newTable` in this step, which then breaks following steps in the pipeline

**Comment by zbynek001** [comment]
Some more details here. So the previous comment basically described what happens, when the Generate attribute is removed from one class (1st iteration). But the real issue happens in an iteration afterwards, when we edit some other file having the Generate attribute inside. (2nd iteration)

What happens inside 2nd iteration is, that the data from `newTable` from 1st iteration is used as `previousTable` in 2nd iteration, but it's also modified. All `Removed` items are removed, and the rest is changed to `Cached`.

Again, some data here from the `Where(tuple => tuple.Item2.Length > 0)` step.
And this happen when file `CorssSellingOptionsDefaultConfigurationUpdated.cs` was edited.


| Index | sourceTable | previousTable | newTable |
|---|---|---|---|
| 1774 | Actors\Configuration\TemplateType\Commands\UpdateTemplateType.cs   (Cached) | Actors\Configuration\Actions\Events\ActionTestLinksUpdated.cs   (Cached) | Actors\Configuration\Actions\Events\ActionTestLinksUpdated.cs   (Cached) |
| 1775 | Actors\Configuration\Topic\Events\TopicUpdated.cs   (Cached) |   |   |
| 1776 | Actors\Configuration\Collection\Commands\GetOKApiConfig.cs   (Cached) |   |   |
| 1777 | Actors\Configuration\TemplateType\Events\CreateValidationFailed.cs   (Cached) |   |   |
| 1778 | DataLake\User\UserCollection\UserIdChangedEventHubModel.cs   (Cached) | Actors\Configuration\Organization\Events\CorssSellingOptionsDefaultConfigurationUpdated.cs   (Cached) | Actors\Configuration\Organization\Events\CorssSellingOptionsDefaultConfigurationUpdated.cs   (Cached) |
| 1779 | Actors\Configuration\Actions\GetAllActionsByCampaignId.cs   (Cached) | **Actors\Configuration\Actions\Commands\UpdateActionEventFilterConfiguration.cs   (Cached)** | **Actors\Configuration\Actions\Commands\UpdateActionEventFilterConfiguration.cs   (Cached)** |
| 1780 | Actors\Configuration\Collection\CollectionContentPersonalization\LabelStructure.cs   (Cached) |   |   |
| 1781 | Actors\Tracking\User\UserOrganization\UserCollection\Events\TestModeOverrideSet.cs   (Cached) |   |   |
| 1782 | Actors\Configuration\Campaign\Events\ValidationStarted_v2.cs   (Cached) |   |   |
|  |  |  |  |
| 2007 | Actors\Configuration\PredictiveScore\Events\ValidationStarted_v1.cs   (Cached) | out of bounds |   |
| 2008 | ViewModels\Partner\PartnerConnectionRef.cs   (Cached) | out of bounds |   |
| 2009 | Actors\Configuration\Organization\Events\CorssSellingOptionsDefaultConfigurationUpdated.cs   (Modified) | out of bounds | Actors\Configuration\Organization\Events\CorssSellingOptionsDefaultConfigurationUpdated.cs   (Added) |
| 2010 | **Actors\Configuration\Actions\Commands\UpdateActionEventFilterConfiguration.cs   (Cached)** | out of bounds | **Actors\Configuration\Actions\Commands\UpdateActionEventFilterConfiguration.cs   (Added)** |
| 2011 | Actors\Global\BackupCoordinator\AzureSQLBackup\Commands\StartAzureSQLBackup.cs   (Cached) | out of bounds |   |


In the source, this file has index 2009. But see what happens on index 1778: Item with status `Cached` is using data from `previousTable`, but this is wrong item, which ends up in the `newTable`, and this is actually `SyntaxTree` from previous compilation, not from the current.
And then on index 2009 we end up with duplicated item in `newTable`. But this is the correct `SyntaxTree` from the current compilation which should be there, but the previous one should not!

Same happens basically on all indexes higher, that the index of the item when the Generate attribute was removed in 1st. iteration.

The indexes are basically mismatched due to the 1st iteration in some cases creating 2 items from 1 (Added/Removed) and then when the state is transformed to `previousTable` for the 2nd iteration, the items there don't match `sourceTable`

**Comment by zbynek001** [comment]
What seems to fix this issue, but not sure if in all cases, is changing the behavior of `StateTableStore` transformation from `newTable` to `previousTable`.

Changing this:

https://github.com/dotnet/roslyn/blob/a8824e82d523f5a698dcab6e2754618d347f94b2/src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs#L106-L118

to not skip `Deleted` items, but replace them with empty `Cached` `TableEntry`,
when called from here:

https://github.com/dotnet/roslyn/blob/e99067409097d5f5a7892ec453c9b0a445cedf3a/src/Compilers/Core/Portable/SourceGeneration/Nodes/StateTableStore.cs#L51-L58

**Comment by zbynek001** [comment]
Here is a simple solution reproducing the issue:
https://github.com/zbynek001/GeneratorForAttributeWithMetadataNameIssue

**Comment by jjonescz** [comment]
Thanks @zbynek001 for your detailed investigation, I've been able to reproduce the bug and I'm working on a fix.
