### ISSUE TITLE
C# compiler shouldn't allow Actions or Funcs to take ref parameters

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn#6646]
The following code compiles without error on VS 2015 RTM:

```csharp
var a = new Action<string>(ref b => b = "hello");
```

Flipping it around, like `Action<string> a = ref b => b = "hello"` will give a syntax error at `ref`.

It appears to work on [TryRoslyn](http://tryroslyn.azurewebsites.net/#K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABQBKZq3ayeVAE4wqMALwwIqAO4wAgqWRg+EADwoFkKAD4xC1ADMYBNVadqYAIgAWqIkT4eEjiyAL7YIUAA=) as well; when you switch to the earliest build, though (xplat), it correctly generates an error message.

**Comment by leppie** [comment]
This is a compat 'bug', it detects properly when strict mode is enabled. IMO, strict should be default.

**Comment by axel-habermaier** [comment]
How and where do I enable strict mode?

**Comment by leppie** [comment]
@axel-habermaier: add `/features:strict` to the compiler command line.

**Comment by axel-habermaier** [comment]
@leppie: Ah, so this option is only exposed via the command line? So that's why I never found it in Visual Studio... Thanks!

**Comment by leppie** [comment]
@axel-habermaier: Yes. Not sure when it was added.

**Comment by gafter** [comment]
It’s an intentional bug that we maintain so as not to break existing code. As noted we handle it correctly in "strict" mode. We're still trying to figure out exactly how "strict" mode should be publicly supported (if at all).
