### ISSUE TITLE
Suppressing warning CA1854 creates invalid entry in suppression file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66486]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suppressing-warning-CA1854-creates-inval/10242274)._

---
Suppressing warning CA1854 creates the following entry in the suppression file:

This entry throws errors BC32017, BC30037, BC 30198, BC 30636, BC 30689 and BC30648.

---
#### Feedback Bot on 1/3/2023, 07:53 AM: 

(private comment, text removed)
#### Tracy Wang [MSFT] on 1/3/2023, 11:32 AM: 

(private comment, text removed)
#### RalphL on 1/3/2023, 00:05 PM: 

(private comment, text removed)
#### Feedback Bot on 1/4/2023, 02:14 PM: 

(private comment, text removed)
#### Feedback Bot on 1/4/2023, 09:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Suppression code fix is failing to escape double quotes inside a string. It appears VB allows more than one form of double quote (in this case, localized curly quotes)

![image](https://user-images.githubusercontent.com/10605811/213413819-b79ca599-ec6f-4835-9814-616532b13e42.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broader feedback on this.
