### ISSUE TITLE
Unnecessary (?) CS8907 when base record got property and derived record got same property as constructor parameter

### ISSUE THREAD

**Issue by tom-sek** [dotnet/roslyn#66494]
### Analyzer

**Diagnostic ID**: [CS8907](: `Parameter '<param_name>' is unread. Did you forget to use it to initialize the property with that name?`

### Describe the bug
Unnecessary (?) CS8907 when base record got property (not form constructor but as normal property) and derived record got same property from constructor parameter. 
Let's say I got external record with property that is not required and I want extend that external record for internal usage and make property required.

### Steps To Reproduce

    public record ItemPrice(decimal Price, string Currency)
    {
        public int LastModified { get; init; } //not required
    };

    public record ItemPriceInternal
    (
        decimal Price,
        string Currency,
        decimal Rounding,
        int LastModified //internally required, but this generates  CS8907 warning
     ) : ItemPrice(Price, Currency)
    {
        public int CustomerId { get; init; }
    }

### Expected behavior
This is valid and looks like what I would expect from ItemPriceInternal implementation above.

    public record ItemPriceInternalExpected : ItemPrice
    {
        public decimal Rounding { get; init; }
        public int CustomerId { get; init; }
        
        public ItemPriceInternalExpected(
            decimal price,
            string currency,
            decimal rounding,
            int lastModified)
            : base(price, currency)
        {
            Rounding = rounding;
            LastModified = lastModified; 
        }
    }

**Comment by Youssef1313** [comment]
I *think* the current behavior is by-design. I'd change the code to the following:

```csharp
public record ItemPrice(decimal Price, string Currency)
{
    internal ItemPrice(decimal price, string currency, int lastModified)
        : this(price, currency)
    {
        LastModified = lastModified;
    }
        
    public int LastModified { get; init; } //not required
};

public record ItemPriceInternal
(
    decimal Price,
    string Currency,
    decimal Rounding,
    int LastModified
 ) : ItemPrice(Price, Currency, LastModified)
{
    public int CustomerId { get; init; }
}
```

**Comment by jaredpar** [comment]
Believe this is by design, will let @jcouv confirm
