### ISSUE TITLE
Keyword color for u8 identifier is broken in VS 17.5 Preview 3

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#66507]
**Version Used**: 17.5.0 Preview 3.0

**Steps to Reproduce**:

1. Use an UTF8 string literal

**Expected Behavior**:

The `u8` identifier should be using the keyword color, as implemented in #63139.

**Actual Behavior**:

![](https://user-images.githubusercontent.com/10199417/213831864-08258323-3972-4959-be9f-5c295d456738.png)

cc. @Youssef1313

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Do you know if any recent changes here?

**Comment by Youssef1313** [comment]
Probably related to #65928 ?

**Comment by Sergio0694** [comment]
I'm confused as to how the tests you added last time didn't catch this regression though? If that `u8` is for some reason being classified in the same way now wouldn't they spot that? 🤔

**Comment by Youssef1313** [comment]
The tests only verify classification span as far as I know. I'm guessing the regression is with how those spans are merged.

**Comment by Sergio0694** [comment]
Is there any chance a fix for this might make it into VS 17.5? It's really hard to spot UTF8 literals at a glance without it 🥲
@CyrusNajmabadi what do you think?

**Comment by CyrusNajmabadi** [comment]
I don't repro on preview4:

![image](https://user-images.githubusercontent.com/4564579/218231338-080eb5dc-4709-4e4d-ad85-89d6117b6ff3.png)

![image](https://user-images.githubusercontent.com/4564579/218231355-ada0cd34-0154-472a-99cb-c6a6e36d9290.png)

Does anyone see this on the latest builds?

**Comment by Sergio0694** [comment]
Not sure what happened, but yeah I also can't repro it anymore on P6 (was still broken on P4 for me).

![](https://user-images.githubusercontent.com/10199417/218269384-5a041de4-cbfb-49da-8ccc-145571ae19ac.png)

Anyway, clsoing this since it seems to be all good now 🙂

**Comment by CyrusNajmabadi** [comment]
I fugred out what's going on here.
