### ISSUE TITLE
Needless exceptions being thrown while processing XML doc comments for quick info in LSIF

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#66503]
I'm seeing this code throwing and swallowing exceptions during LSIF indexing:

https://github.com/dotnet/roslyn/blob/6b45de8aa0b7d891f1af935a6fab1830c299cde7/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L254-L284

The xmlText that came back is something like `<summary></summary><param></param>` with multiple top-level nodes. That's being passed to XElement.Parse however, which is throwing an exception since it's expecting a single top level node. I'm not sure where things are getting off slightly, but there's some mismatch here -- some code expects there's a single top level node, and something else isn't providing it.

**Comment by jasonmalinowski** [comment]
Looks like this is a bug in the XmlDocumentationProvider we have that we use at the workspaces layer. It's returning an XML fragment when everything else in the system is returning the containing element that wraps everything.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
