### ISSUE TITLE
Intellisense generates incorrect cref in XML docs when method has ValueTuple parameters

### ISSUE THREAD

**Issue by mikernet** [dotnet/roslyn#66502]
**Version Used**:  VS17.4.0 / .NET 7

**Steps to Reproduce**:

Using Intellisense to select a method that has a ValueTuple parameter when setting the `cref` attribute generates incorrect syntax:

```cs
    public void Test((int X, int Y) point) { }

    /// <inheritdoc cref="Test((int X, int Y))"/>
    public void Test2() { }
```

Should be:

```cs
    public void Test((int X, int Y) point) { }

    /// <inheritdoc cref="Test(ValueTuple{int, int})"/>
    public void Test2() { }
```

**Comment by CyrusNajmabadi** [comment]
We woudl take a targetted community pr here.

**Comment by CyrusNajmabadi** [comment]
No repro:

![Image](https://github.com/user-attachments/assets/db4c104b-0ea9-46bd-b27f-06f8a4f77401)

![Image](https://github.com/user-attachments/assets/f98700d8-a419-41fe-8c93-f73f3caf4d3d)

**Comment by mikernet** [comment]
Thanks - tested it again as well and it appears to have been fixed since the issue was posted. Cheers!
