### ISSUE TITLE
Constants test in the BasicExpressionCompilerTest.LocalsTests occasionally fails with OverflowException

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#6651]
Likely due to a DSR issue. see http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit32/297/testReport/Microsoft.CodeAnalysis.VisualBasic.UnitTests/LocalsTests/Constants/ for an example

**Comment by tmat** [comment]
On it. We'll need a crash dump. I'm going to add some tracing to the test meanwhile.

**Comment by agocke** [comment]
The test is disabled so you should just try running it in a loop for now

**Comment by srivatsn** [comment]
The failure is in a EE test. Moving to Area-Interactive

**Comment by agocke** [comment]
@srivatsn Thanks, misclick :)

**Comment by agocke** [comment]
Another instance skipped in c4a7c8de83ab2395674f71cfe4e8e23e48665dbb

**Comment by tmat** [comment]
@agocke Could you point me to the other instance of failure? I have added instrumentation to gather more info.

**Comment by TyOverby** [comment]
@agocke 

Is this failure related or should I file a new flaky bug?

http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit32/309/testReport/junit/Microsoft.CodeAnalysis.CSharp.UnitTests/LocalsTests/Constants/

**Comment by agocke** [comment]
@TyOverby Same failure.

**Comment by tmat** [comment]
Likely bug in native DiaSymReader. Needs more investigation.

**Comment by natidea** [comment]
Adding flaky label since there are still disabled tests referring to this bug and we are tracking this

**Comment by tmat** [comment]
There is actually no disabled test anymore.
