### ISSUE TITLE
Intellisense not working in Blazor razor files

### ISSUE THREAD

**Issue by RonPeters** [dotnet/roslyn#66513]
Using CommunityToolkit.Mvvm 8.0.0/8.1.0
[ObservableProperty] works fine in classes that are defined in the Blazor project. But if the Blazor project consumes a DLL that contains a view model with an [ObservableProperty], that property will never show up in Intellisense in the razor file, even though it works fine in c# files in the Blazor project.

I've added default values to all non-nullable properties: https://github.com/CommunityToolkit/dotnet/issues/57
I've deleted .vs folder and restarted Visual Studio: https://github.com/dotnet/roslyn/issues/44093

Nothing works. I ended up giving up on the source generator and doing the properties the old fashioned way to get Intellisense.

Steps to reproduce

**Version Used**: Possibly 4.3.1 (using CommunityToolkit.Mvvm 8.1.0)

**Steps to Reproduce**:

// No Intellisense:
```
public partial class TestViewModel : ObservableObject
{
    [ObservableProperty]
    private string example = default!;
}
```

// Succesful Intellisense:

```
public partial class TestViewModel : ObservableObject
{
    private string example = default!;
    public string Example
    {
       get => example;
       set => SetProperty(ref example, value);
    }
}
```

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**: Intellisense should be available in razor files that consume the view model class, just like in c# files

**Actual Behavior**: Intellisense is not available in razor files that consume the view model class, but is available in c# files

Originally reported in CommunityToolkit: https://github.com/CommunityToolkit/dotnet/issues/576

**Comment by genlu** [comment]
Sounds like an issue with source generator. Could this be related to https://github.com/dotnet/roslyn/issues/66104? Both involves CommunityToolkit.Mvvm.

@RonPeters Would it be possible for you to provide a repro project for me to investigate? Thanks!

**Comment by TheBlubb14** [comment]
Hi @genlu 
I have the same issue using Visual Studio Version 17.6.0 Preview 5.0, Balzor Server with .Net 8.0.100-preview.3.23178.7 and CommunityToolkit.Mvvm 8.2.0-preview2.

I have created a sample project here https://github.com/TheBlubb14/ReproBlazorIntellisense
My intellisense doesn't work here https://github.com/TheBlubb14/ReproBlazorIntellisense/blob/11fff20d70274311da978f7adc40424c478ac9b4/ReproBlazorIntellisense/Pages/Index.razor#L14-L15

**Comment by CyrusNajmabadi** [comment]
Closing out as razor is external.
