### ISSUE TITLE
Possible to detect "external" global using aliases in analyzer?

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#66517]
If I in an analyzer would like to know if there are any using aliases in effect, then I can easily check for the normal/old kind by checking the syntax tree, but what about **global using aliases**? Is it possible to somehow detect if there are global using aliases in effect although they are specified in another file, just by looking at the syntax tree, compilation, analysis context etc?

**Comment by CyrusNajmabadi** [comment]
You can use GetImportScopes (https://github.com/dotnet/roslyn/blob/e1ee2f544a7a4f8d536278bed4e180c54919276e/src/Compilers/Core/Portable/Compilation/SemanticModel.cs#L781) to determine this.

**Comment by Youssef1313** [comment]
Curious why do you want to do that?

**Comment by jcouv** [comment]
Closing as answered.

**Comment by bjornhellander** [comment]
@CyrusNajmabadi: Thanks for the suggestion! It looks promising. I will look into it.

@Youssef1313: StyleCop's SA1121 takes a shortcut if there are no using statements, but misses the global using statements, so misbehaves if those are the only using statements present.

Sorry for the delay. I haven't had any time to continue looking into this yet. I will open a new issue if needed, so keep this closed. Thanks again!
