### ISSUE TITLE
"abstract void Main()" compiles successfully 

### ISSUE THREAD

**Issue by KirillAldashkin** [dotnet/roslyn#66516]
**Version Used**: .NET 7.0

**Steps to Reproduce**:
1. Create console application
2. Write interface with `static abstract void Main()`
3. `dotnet run`

https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgZgAIBLKYAUzADMBDAYwqIGEiBvPIro1TANiK0ARgGdgYBsB4AWIgFlaZABQBKANx4AvkA

**Expected Behavior**:
Compilation fails with some error.

**Actual Behavior**:
Program compiles successfully, and exception is thrown when running program.

**Comment by Youssef1313** [comment]
This needs to be adjusted here:

https://github.com/dotnet/roslyn/blob/e1ee2f544a7a4f8d536278bed4e180c54919276e/src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs#L705-L717
