### ISSUE TITLE
Please add codefix for constructor exits with "null" non-nullable members

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66523]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/请求在类的构造函数中修补程序可以一键添加所有非NULL值的属性/10180037)._

There's no codefix for "[CS8618](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8618)#nonnullable-reference-not-initialized): Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable." Please add codefix to declare all those member as nullable.

---
![image](https://user-images.githubusercontent.com/788783/214135060-2e088f62-f6e3-444e-8b96-ded21053f4fd.png)

---
### Original Comments

Please make this refactoring available at constructor too (which triggers at member only)
![image](https://user-images.githubusercontent.com/788783/214136345-b07eab98-16b0-45c5-a2fc-10e6b715be6d.png)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of b roader feedback.
