### ISSUE TITLE
Better error fix suggestions on For loops when use commas rather than semicolons

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66522]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Better-error-fix-suggestions-on-For-loop/1626853)._

---
Better error fix suggestions on For loops when use commas rather than semicolons.

So this below gives a bunch of errors: "local variable or function is already defined in this scope", "variable j is declared but never used", "invalid expression term<", "; expected", "invalid expression term ,".

The red swiggles incorrectly highlight the "j" and the "<".  They correctly show the second "," but fail to show under the first comma.

```
for (int j = pos1, j < pos2, j++)
{
   // stuff
}
```

Could you reduce this to "; expected" error and have it red swiggle the commas?

---
#### Feedback Bot on 1/4/2022, 02:23 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
I did something similar for foreach.  I could take a look to see how hard this would be to do.
