### ISSUE TITLE
Disallow MethodImplOptions.Synchronized for async lambdas

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#66530]
### Discussed in https://github.com/dotnet/roslyn/discussions/66529

<div type='discussions-op-text'>

<sup>Originally posted by **pavel-zhur** January 24, 2023</sup>
In this case the compiler generates an error:
```
// CS4015: 'MethodImplOptions.Synchronized' cannot be applied to an async method
[MethodImpl(MethodImplOptions.Synchronized)]
async Task Selector()
{
    await Task.Delay(1);
}
```
but no error here:
```
var tasks = Enumerable.Range(0, 10)
    .Select(
        [MethodImpl(MethodImplOptions.Synchronized)] // no error here
        async (x) => await Task.Delay(1))
    .ToArray();
```

It seems the CS4015 error needs to be thrown when applying the MethodImplOptions.Synchronized to async lambdas as well.</div>

**Comment by jcouv** [comment]
Thanks @pavel-zhur for reporting this.
