### ISSUE TITLE
No `Protected` keyword completion after `Private` in VB

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66544]
**Version Used**:
17.5 Preview 4

**Steps to Reproduce**:
```vb
Class C
    Private $$
End Class
```

**Expected Behavior**:
`Protected` is available in completion list at `$$` because `Private Protected` is a valid VB accessibility modifier

**Actual Behavior**:
Opposite to expected

**Comment by CyrusNajmabadi** [comment]
Closing as we are not planning on investing in these scenarios.
