### ISSUE TITLE
Refactor "Remove parameter" mistakenly removes arguments with '@'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66547]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactor-Remove-parameter-mistakenly-r/10259275)._

---
The refactor "Remove parameter" misbehaves by removing arguments at call-sites that it shouldn't. In particular arguments whose parameter names start with `@` and have been explicitly specified.

I've reproduced it a minimal example shown in the screenshot.
Simply create a new C# console app and insert the following in its only C# file:

```csharp
void m(object? param, bool @new = true)
{

}

m(null);
m(null, false);
m(null, @new: false);

```
Execute the refactor "Remove parameter" on and remove `param`, and observe that the argument `@new: false` on the last line is mistakenly removed. I expected that argument not to be removed.

### Version

Reproduced in Visual Studio version 17.4.4.

---
#### Feedback Bot on 1/23/2023, 06:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
I'm definitely able to reproduce this, definitely broken.
