### ISSUE TITLE
Variables captured in a lambda and in a local function are getting different treatment in DefiniteAssignmentPass

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#66557]
```
        private void ReportUnassignedIfNotCapturedInLocalFunction(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration = true)
        {
            // If the symbol is captured by the nearest
            // local function, record the read and skip the diagnostic
            if (IsCapturedInLocalFunction(slot))
            {
                RecordReadInLocalFunction(slot);
                return;
            }

            ReportUnassigned(symbol, node, slot, skipIfUseBeforeDeclaration);
        }
```

This creates observable differences for region analysis. For example, in DataFlowsIn

**Comment by jaredpar** [comment]
Thought this was by design though as we consider the invocation of the local function when determining definite assignment of captured locals. Same is not true for lambdas.

@agocke

**Comment by agocke** [comment]
I'd have to see an example, but Jared's directionally right. For instance, in the following code

```C#
void M()
{
    int i;

    void Local()
    {
        i++; // i is considered definitely assigned here, as Local is considered unreachable
    }
}
```

This could create some unintuitive results in the region analysis if the region contains a local function definition, but not a use. Intuitively, the definite assignment of local function captured variables happens at the local function call site, not at the variable use site.

**Comment by jcouv** [comment]
@AlekseyTs You mentioned this has observable result on region analysis, could you provide an example? For purpose of triage, I'm not sure if this is a bug or by-design.

**Comment by jcouv** [comment]
Assigned to @AlekseyTs and milestone=Backlog for clarification (confirm whether this is by-design or a bug). Feel free to move to an earlier milestone as needed.

**Comment by AlekseyTs** [comment]
I am satisfied with Andy's response
