### ISSUE TITLE
CultureInfo.CurrentCulture API banned in Analyzers but alternative API is inaccessible

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#66566]
**Version Used**:  4.6.0-1.23076.1

**Steps to Reproduce**:

1. Reference the most recent Microsoft.CodeAnalysis.Analyzers package
2. Use CultureInfo.CurrentCulture in an analyzer or code fix

Example at: https://github.com/dotnet/runtime/pull/81164

**Diagnostic Id**:

RS1035

**Expected Behavior**:

There is an API we can use to get the culture from the command line arguments, as directed to do so by the diagnostic.

**Actual Behavior**:

There is no API to get the culture from the command line arguments.

cc: @RikkiGibson @jaredpar

**Comment by Youssef1313** [comment]
This should be moved to dotnet/roslyn-analyzers

**Comment by jkoritzinsky** [comment]
@RikkiGibson told me to file it here since it’s more about exposing the API the diagnostic points to instead of the diagnostic being wrong.

**Comment by Youssef1313** [comment]
Makes sense. Thanks @jkoritzinsky

**Comment by Youssef1313** [comment]
btw, we have the exact same usage here:

https://github.com/dotnet/roslyn/blob/e99067409097d5f5a7892ec453c9b0a445cedf3a/src/Features/CSharp/Portable/CodeFixes/Suppression/CSharpSuppressionCodeFixProvider.cs#L60

but no warnings 😕 

Something is probably wrong.

**Comment by agocke** [comment]
@jaredpar for triage

**Comment by jaredpar** [comment]
What API is being requested here? Unclear from the bug.

**Comment by Youssef1313** [comment]
@jaredpar I'm guessing https://github.com/dotnet/roslyn/blob/1d8f8cd8be6581a03e8379b8f146dcb5f11800c9/src/Compilers/Core/Portable/CommandLine/CommandLineArguments.cs#L304

It is already public but there doesn't seem to be a way to get it from analyzers?

**Comment by agocke** [comment]
FWIW I would suggest that, since this is blocking Roslyn integration, the immediate fix should be to disable the analyzer ASAP, and then bring back the analyzer once the correct API is ready and tested.

**Comment by RikkiGibson** [comment]
Razor source generator uses CurrentCulture as well https://github.com/dotnet/razor/blob/ec14eb2f781105866a7426be6f8955e45ad4e654/src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/Diagnostics/RazorDiagnostics.cs#L107-L108

**Comment by RikkiGibson** [comment]
I currently believe that compiler API surface shouldn't be changed here.

Rather the actual resolution is described at https://github.com/dotnet/roslyn-analyzers/issues/7086#issuecomment-2223967184.

Will close out and track in the linked issue in roslyn-analyzers.
