### ISSUE TITLE
CA1707 applies to method names

### ISSUE THREAD

**Issue by garcipat** [dotnet/roslyn#66574]
First I wanted to write my own Analzer to prevent the usage of "_" as a variable name in linq expressions. 
Toda I found that there is a analyzer checking variable names for containing discard/underscore. See [#CA1707](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1707)

After activating it, Im getting errors on my test methods where we usually have the method to test separated with the expected result like

```csharp
public void MyMethod_ShouldReturnSucess()
{
...
}
```

In the documentation of CA1707 its described that it checks 
- namespaces
- types
- members
- parameters

Since methods are affected, is that a missing listing, is that analyzer wrong or is a method considered a member? I was expecting members only convering properties.

**Comment by CyrusNajmabadi** [comment]
Methods are members.

**Comment by garcipat** [comment]
Okay that means I need to implement my own analyzer for that then it seems. A shame this is bundled in one.
