### ISSUE TITLE
Avoid including pdb in NuGet packages

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#66595]
https://github.com/dotnet/sourcelink/blob/main/README.md

> If you distribute the library via a package published to [NuGet.org](http://nuget.org/), it is recommended to build a [symbol package](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) and publish it to [NuGet.org](http://nuget.org/) as well. This will make the symbols available on [NuGet.org symbol server](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-server), where the debugger can download it from when needed. Alternatively, you can [include the symbols in the main package](https://github.com/dotnet/sourcelink/blob/main/README.md#alternative-pdb-distribution). However, doing so is not recommended as it increases the size of the package and thus restore time for projects that consume your package.

It looks like the recommendation is to not include pdb files. Looking at `Microsoft.CodeAnalysis.CSharp`, I see two 3MB pdb files:

![image](https://user-images.githubusercontent.com/31348972/215559085-af27502a-1acb-445c-a7ce-34bb16d6954b.png)

**Comment by tmat** [comment]
I need to update the Source Link page. Both options of distributing PDBs (snupkg and including PDBs in the main package) are now common.

**Comment by Youssef1313** [comment]
@tmat Curious why pdb file size isn't a concern?
