### ISSUE TITLE
[Test Failure] CompilerServerUnitTests.ServerWithSamePipeNameExits in prtest/win/dbg/unit64 on PR #6658

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6660]
PR: [#6658](https://github.com/dotnet/roslyn/pull/6658) *Revert "Syntactically classify buffers without a workspace"* by @dpoeschl
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/991/

**1 Test Failures:**
Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.ServerWithSamePipeNameExits

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by dpoeschl** [comment]
@agocke Is this known?

**Comment by agocke** [comment]
@dpoeschl I think this is a dup of https://github.com/dotnet/roslyn/issues/6357

**Comment by davkean** [comment]
Agreed, looks like a dup of 6357, which is now resolved.
