### ISSUE TITLE
Add API to determine what features the runtime supports.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66620]
## Background and Motivation

IDE would like this api so we can know if we should suggest users convert from `System.IntPtr` to `nint` (and the nuint equivalent).  We only want to suggest this when totally safe to do so.

Right now, the logic to figure this it just hard enough for us to not feel comfortable reimplementing hte logic.  So the proposal is to just make this API (which already exists internally), public.

## Proposed API

```diff
+ public enum RuntimeFeature
+ {
+     ByRefFields,
+     CovariantReturnsOfClasses,
+     DefaultImplementationsOfInterfaces,
+     NumericIntPtr,
+     UnmanagedSignatureCallingConvention,
+     VirtualStaticsInInterfaces,
+ }

public class Compilation
{
+    bool SupportsRuntimeFeature(RuntimeFeature feature);
}

```

## Alternative Designs

Potentially some sort of enum that lists all the different things supported (like RuntimeSupportsDefaultInterfaceImplementation, RuntimeSupportsStaticAbstractMembersInInterfaces), and `IAssemblySymbol.SupportsFeature(FeatureEnum)`?

Perhaps expose this on the compilation itself?

**Comment by CyrusNajmabadi** [comment]
@AlekseyTs @jcouv @davidwengier  for preliminary thoughts on the naming here.  Note: using `RuntimeFeature` may be problematic due to the collision with the same named type in https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimefeature?view=net-7.0.

Potential alternative may be `RuntimeCapability`?

**Comment by jcouv** [comment]
Sounds good to me, although I might slightly prefer `RuntimeSupportsFeature` to `SupportsRuntimeFeature` for the method name. Thanks

**Comment by chsienki** [comment]
### API Review

- No problem with the overall intention of the API. 
- Would make more sense for this to be on `Compilation` rather than `IAssemblySymbol`. 
- Instead of a single property for the specific feature (and others in the future) lets go with the alternative design and have a single API that you call with an enum to determine if the feature is supported.

Approved.
