### ISSUE TITLE
#load completion is slow for network drives

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6662]
1. it doesn't look like #load completion has cancellation.
2. If you type `#load "\\"`, it's super slow while it tries to discover things on the network--we should proabably disable that.

**Comment by rchande** [comment]
FYI @amcasey

**Comment by amcasey** [comment]
@KevinH-MS tells me we'll need to fix it separately for `#r`.

**Comment by KevinH-MS** [comment]
Or rather, we should make it be the same code instead of two separate implementations and then fix it once.  :wink:

**Comment by tmat** [comment]
Fixed.
