### ISSUE TITLE
C# refactoring "Move type to new file" generates file violating stylecop rule SA1505

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66639]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-refactoring-Move-type-to-new-file-g/10266552)._

---
[severity:It bothers me. A fix would be nice]
When I apply the C# refactoring "[Move type to new file](https://learn.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-matching-file?view=vs-2022&tabs=csharp)" on a file that contains multiple classes, a new file is generated but that file contains a newline after the opening brace of the namespace. This violates the stylecop rule [SA1505](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1505.md).

---
#### Feedback Bot on 2/1/2023, 02:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Stylecop is an external project.  It is a non-goal for roslyn to follow the rules it sets.
