### ISSUE TITLE
Suboptimal codegen for local async method

### ISSUE THREAD

**Issue by sakno** [dotnet/roslyn#66638]
**Version Used**:  .NET SDK 6.0.405

Let's take a look at the following example:
```csharp
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

public class C {
    public static ValueTask<int> SumAsync(int x, int y, CancellationToken token)
    {
        return ExecuteAsync();

        [AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder<>))]
        async ValueTask<int> ExecuteAsync()
        {
            await Task.Delay(10, token);
            return x + y;
        }
    }
}
```

Roslyn produces suboptimal IL code that lacks benefits of state machine pooling because compiler generates display class for all implicitly captured locals. As a result, three parameters from example above placed as a fields of the display class instead of state machine value type. As a result, display class allocates on every execution of the method.

State machine declaration:
```csharp
[StructLayout(LayoutKind.Auto)]
private struct <<SumAsync>g__ExecuteAsync|0>d : IAsyncStateMachine
{
    public int <>1__state;
    public PoolingAsyncValueTaskMethodBuilder<int> <>t__builder;
    public <>c__DisplayClass0_0 <>4__this;
    private TaskAwaiter <>u__1;
}
```

Display class declaration:
```csharp
[CompilerGenerated]
private sealed class <>c__DisplayClass0_0
{
    public CancellationToken token;
    public int x;
    public int y;
}
```

This is not obvious for developers and creates false imagination about pooling. Moreover, it is bad from data locality perspective. Display class allocates every time while state machine may be taken from the cache (as already boxed state machine).

However, there is workaround and the code above can be rewritten as follows:
```csharp
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

public class C {
    public static ValueTask<int> SumAsync(int x, int y, CancellationToken token) {
        return ExecuteAsync(x, y, token);
    }
    
    [AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder<>))]
    private static async ValueTask<int> ExecuteAsync(int x, int y, CancellationToken token)
    {
        await Task.Delay(10, token);
        return x + y;
    }
}
```

Now all parameters are placed in state machine value type and no display class generated:
```csharp
[StructLayout(LayoutKind.Auto)]
[CompilerGenerated]
private struct <ExecuteAsync>d__1 : IAsyncStateMachine
{
    public int <>1__state;
    public PoolingAsyncValueTaskMethodBuilder<int> <>t__builder;
    public CancellationToken token;
    public int x;
    public int y;
    private TaskAwaiter <>u__1;
}
```

Now the pooling is much more reasonable.

Interesting, but the same issue doesn't happen with synchronous methods:
```csharp
public static int SumAsync(int x, int y, CancellationToken token) {
        return ExecuteAsync();

        int ExecuteAsync()
        {
            return x + y;
        }
    }
```

Compiles to:
```csharp
[StructLayout(LayoutKind.Auto)]
[CompilerGenerated]
private struct <>c__DisplayClass0_0
{
    public int x;

    public int y;
}

public static int SumAsync(int x, int y, CancellationToken token)
{
    <>c__DisplayClass0_0 <>c__DisplayClass0_ = default(<>c__DisplayClass0_0);
    <>c__DisplayClass0_.x = x;
    <>c__DisplayClass0_.y = y;
    return <SumAsync>g__ExecuteAsync|0_0(ref <>c__DisplayClass0_);
}

[CompilerGenerated]
private static int <SumAsync>g__ExecuteAsync|0_0(ref <>c__DisplayClass0_0 P_0)
{
    return P_0.x + P_0.y;
}
```

I understand that local function can modify implicitly captured parameters or locals, that's why Roslyn needs to have some heap-allocated memory location to store that mutations. Perhaps, the compiler can distinguish closure types:
* Immutable closure, when captured variable is in rvalue position only
* Mutable closure, when captured variable found in at least one lvalue position

P.S.: ref locals can be captured from within local synchronous function because C# 11 finally allows to declare ref fields. All you need is to convert display struct to display ref struct with ref fields.

**Comment by jaredpar** [comment]
Yes this type of rewrite is possible but 

- It requires extra analysis in the compiler that is not done today
- It's unclear just how many call sites would benefit from this transformation 
- High perf uses generally understand this trade off today and already write their hot paths to take advantage of this type of behavior

There are definitely patterns like this where we could generate better code. In practice though we don't see them happening enough to justify the cost of implementing the transformation (compared to doing other higher impact optimizations). Particularly because this type of transform is relatively expensive to implement. 

Issues like this I think need impact data associated with them. Essentially how many call sites would benefit from it? Lacking that it's not going to meet our priority bar for implementation. 

> ref locals can be captured from within local synchronous function because C# 11 finally allows to declare ref fields. All you need is to convert display struct to display ref struct with ref fields.

The display `struct` here can be pushed to the heap and implements interfaces thus it can't capture `ref` fields because `ref struct` cannot do either of those items.
