### ISSUE TITLE
EnumUnderlyingType is NULL when calling Complation.GetTypeByMetadataName() on any Enum defined in a MetadataReference.

### ISSUE THREAD

**Issue by robgruen** [dotnet/roslyn#66631]
Any enum that is defined in a metadatareference is being incorrectly typed as TypeKind.Class instead of TypeKind.Enum.  As a side effect, IsReferenceType is true (when it should be false), IsValueType is false (when it should be true) and the EnumUnderlyingType is also missing.  The base type is listed as System.Enum so my guess is there's a small logic error in the loading of the reference.

This can be easily reproed by creating a project and then by getting a TypeSymbol for any built in enum (I used System.ConsoleColor). If you try the same code but instead declare the enum in the compiled class it works correct.  This behavior also works correctly in msbuild.exe (but not in msbuild.dll when calling dotnet msbuild ...)

Here's a code snip:

```
ProjectId projectId = ProjectId.CreateNewId(ProjectName);
                ProjectInfo projectInfo = ProjectInfo.Create(
                    projectId,
                    VersionStamp.Default,
                    ProjectName,
                    ProjectName,
                    LanguageNames.CSharp,
                    compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

                Solution solution = new AdhocWorkspace()
                    .CurrentSolution
                    .AddProject(projectInfo)
                    .AddMetadataReference(projectId, MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

               Compilation compilation = solution.GetProject(projectId).GetCompilationAsync().Result;
               INamedTypeSymbol sym = compilation.GetTypeByMetadataName("System.ConsoleColor");

               // If you inspect sym here you'll notice it's got the incorrect TypeKind.  Should be Enum.  Is Class.
```

**Comment by jaredpar** [comment]
I'm not able to reproduce this behavior. I used the `System.DateTimeKind` `enum` as `System.ConsoleColor` isn't available in that DLL. Using that I get the expected kind of `Enum`.
