### ISSUE TITLE
Visual Studio 17.4 Incorrect Enforcing of New Breaking Change in Earlier C# Versions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66646]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-174-Enforcing-of-File-Key/10260528)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.3]
Visual Studio 2022 version 17.4 and above contains a breaking change for C# 11 and the use of the word "file" which is now reserved:

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207#types-cannot-be-named-file

However, this is incorrectly being enforced in earlier versions of C# and breaks existing builds. In this case we use .NET Framework 4.8 with C# 7.3. See attached screenshots and the attached solution which demonstrates the problem.

[breaking_change_err.png](https://aka.ms/dc/file?name=B899cb9e658574c47801e3a758a5b4fb2638101572133334642_breaking_change_err.png&tid=899cb9e658574c47801e3a758a5b4fb2638101572133334642)
[breaking_change_err_02.png](https://aka.ms/dc/file?name=B238dcf7628224c439844904d93a2900b638101572256796962_breaking_change_err_02.png&tid=238dcf7628224c439844904d93a2900b638101572256796962)

---
#### Feedback Bot on 1/27/2023, 10:07 PM: 

(private comment, text removed)
#### Feedback Bot on 1/31/2023, 05:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
One scenario that we broke in old language versions is:

```cs
public class file { }

public class C
{
    private file item; // ok
    private file[] file { get; set; } // error on '[' and second 'file'
}
```

**Comment by RikkiGibson** [comment]
Use of the 17.6 milestone here does not preclude fixing this bug in 17.4 servicing.
