### ISSUE TITLE
Support standard input in the interactive window

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6666]
Currently, the host doesn't redirect standard input, so all consumers receive nothing.

**Comment by amcasey** [comment]
1.3 pending feedback.

**Comment by KevinH-MS** [comment]
@genlu would you be able to look at this?

**Comment by genlu** [comment]
@KevinH-MS I will take a look this week. So we are trying to fix this in 1.2?

**Comment by KevinH-MS** [comment]
It seems like enough people have run into this that we should try to address it for 1.2 (via e-mail and the referenced issue above).  @ManishJayaswal , please chime in if that doesn't sound like the right priority.

**Comment by genlu** [comment]
#7743 is related.

**Comment by ManishJayaswal** [comment]
closing this as it is a dupe of #7743
