### ISSUE TITLE
BlockSyntax capturing - cannot detect in declarations

### ISSUE THREAD

**Issue by vladimirKa002** [dotnet/roslyn#66676]
Hello,

I am trying to capture all curly braces scopes in the C# code. By using a visitor class I can easily track `BlockSyntax` nodes of methods and loops:
```
public override void VisitBlock(BlockSyntax block)
{
        // Process
}
```
 However, `class`, `namespace`, `enum`, etc declarations do not have such construct, but have only `OpenBraceSyntax` and `CloseBraceSyntax` objects and various other members depending on type:

![image](https://user-images.githubusercontent.com/71442532/216286235-7029fccd-f9ac-495f-a0f4-de6c71c2a113.png)

Could you please advise if there is any more or less strightforward way to capture all scopes including in declarations?

**Comment by DoctorKrolic** [comment]
`BlockSyntax` is a statement and it is not designed to be a part of any declaration

**Comment by CyrusNajmabadi** [comment]
You could just walk all tokens. For every openbrace you hit, go to it's parent and look for a child if that parent that is a close brace.

**Comment by vladimirKa002** [comment]
Thank you for your suggestions! Indeed, it is a good idea to find openbrace. In my case, I also needed to perform analysis of the corresponding to scope statement, like declarations. So, I decided to find all constructs that have either braces tokens children (like, namespaces, classes) or `BlockSyntax` (like, loops, methods) and then parse their content.
