### ISSUE TITLE
FindCallersAsync not able to find all the callers specially protected one

### ISSUE THREAD

**Issue by punitsinghi** [dotnet/roslyn#66671]
Hi,

We have a solution which has many project and in one of the project I need to find all the callers of a particular symbol.

I am using below method to find all the callers..  

              var msWorkspace = MSBuildWorkspace.Create();
              msWorkspace.LoadMetadataForReferencedProjects = true;
            msWorkspace.OpenSolutionAsync(solutionPath).Result
            var compilationProject = solution.Projects.Where(x => x.Name.Contains("Engine")).FirstOrDefault().GetCompilationAsync().Result
            var symbol = compilationProject.GetSymbolsWithName(item).FirstOrDefault()
            var members = symbol.ContainingType.GetMembers();
            var referenceSymbols = **SymbolFinder.FindCallersAsync(symbol, solution).Result;**

              Class A : BaseClass
              {
               protected internal override Test()
              {
              }
              }
              
              Class B 
              {
                    Class B(A a)
                  {
              }
               protected internal override Test2()
              {
              a.Test();
              }
              
              }

So based on the above I would have expected that Test2() should be returned as part of Caller which is not the case. I see that works fine when a solution has single project while on multiple projects it doesnt find the reference.

**Comment by jcouv** [comment]
Marked this as Area-IDE since the reported issue relates to `SymbolFinder.FindCallersAsync` (in Workspaces project).

**Comment by CyrusNajmabadi** [comment]
Can you provide a fully self-contained repro project for this?  Putting it on github would be fine.  Thanks!
