### ISSUE TITLE
portable pdb files not copied to Release/Debug folders

### ISSUE THREAD

**Issue by ctaggart** [dotnet/roslyn#6668]
When the `DebugType` is set to `portable`, the `pdb`s are not being copied to the `Debug` or `Release` folder when I do a build. I'm expecting this folder to have the `pdb` files like normal:

![image](https://cloud.githubusercontent.com/assets/80104/11053583/25ec3722-8717-11e5-982f-4a4f95f68135.png)

They are in the `Obj` folders:
![image](https://cloud.githubusercontent.com/assets/80104/11053609/4df5143c-8717-11e5-8da9-c8fc21a058ce.png)

For comparison, here is `DebugType` set to `full`:

![image](https://cloud.githubusercontent.com/assets/80104/11053637/888148fa-8717-11e5-9d1b-8e073a209560.png)

This can be reproduced by setting the altering the `DebugType`s in `build/Targets/VSL.Settings.targets`. 
![image](https://cloud.githubusercontent.com/assets/80104/11053783/ecbb46ee-8718-11e5-8ca4-3be5f276fb71.png)

**Comment by jaredpar** [comment]
Thanks for reporting this issue!  This is actually a bug in the MSBuild target files.  I just sent a PR to correct the behavior. 

https://github.com/Microsoft/msbuild/pull/379
