### ISSUE TITLE
Make "Binder" logic publicly usable

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#6670]
We are working on an analyzer and codefix to simplify `if` statements (with certain statements in the true and false part) to use conditional expressions. So, `if (condition) x = a; else x = b;` should be changed to `x = condition ? a : b;`.

However, this can only be done if `a` and `b` are of the same types, or there's implicit conversion between them, or ... This logic is implemented in `Binding.BindConditionalOperator()`, which has a comment on the top saying that there are some differences between the implementation and the specification. So if anyone would like to implement a similar analyzer/code fix, he would need to either implement the check from the spec which would not match the behavior of the compiler, or reimplement the logic from the compiler. To avoid these reimplementations and probably slight differences between the implementations, it would be preferable to make the `Binder` public and be able to reuse the logic from it.

One workaround to this problem is to do the modification, assemble the new syntax tree, change the compilation to include the modified tree, and then get the semantic model for the modified tree, and check the type of the expression if that's an error type or not. This way we are reusing the implementation in the compiler, but it's probably quite resource intensive.

A side note: I couldn't find the C# 6.0 language specification, only version 5. Is it available somewhere? In version 5, I checked the type inference of conditional expressions. Section 7.14 details this, but it seems to me that it is missing the obvious case when both `x` and `y` has type, and these types are the same. Shouldn't this also be included in the spec? Who is maintaining the specification? Is it also the Roslyn team?

**Comment by gafter** [comment]
We are unlikely to expose `Binder` et al... as it is subject to massive changes as the language changes.

@MadsTorgersen Can you comment on the C# 6 language specification?
