### ISSUE TITLE
Background analysis performance improvements

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#66714]
**Issue:** Recent performance measurements for background analysis have shown that for very large files and for large number of open files in a VS session, background analysis leads to a steady increase in memory pressure in the OOP Roslyn ServiceHub process. Majority of the allocations and memory usage is coming from the partial analysis state tracking done in CompilationWithAnalyzers for open file analysis: https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisState.cs,c6a89afa028d81d8. We also have few feedback reports for the same, for example https://developercommunity.visualstudio.com/t/Code-Analyzer-crashes-for-a-large-file/10016304 shows 50% of memory usage in OOP Roslyn ServiceHub process coming from AnalysisState objects.

**Historical context:** Prior to moving analyzer execution to the OOP Roslyn ServiceHub process, for background analysis, we used to execute all analyzers one by one on each open file to compute diagnostics. This was done as a response to high GC and many UI delays while typing that stemmed from attempting to run all analyzers concurrently inside the devenv.exe process. However, this in-proc sequential analyzer execution led to repeated forking of the compilation inside CompilationWithAnalyzers instance for every analyzer being executed, which caused high allocations and increase in memory pressure. To avoid this, we introduced analyzer state tracking within CompilationWithAnalyzers, whereby we re-use the same underlying compilation for computing all analyzer diagnostics, even if asked sequentially by the CompilationWithAnalyzers host, but need to keep track of which analyzer has completed callbacks for which symbol/node/operation. This state tracking is needed to avoid duplicate callbacks into the analyzer for the same symbol/node/operation, which is needed for functional correctness. However, we need to keep dictionaries and hashsets storing references to all symbol/node/operation executed for corresponding compilation events, which increases the memory pressure. This also affects execution speed as we need to acquire locks for reading and writing into these data structures prior to every callback.

**Potential perf improvements:** With the move to analyzers being executed completely in OOP Roslyn ServiceHub process, we now execute all the analyzers concurrently in OOP. We do execute the compiler analyzer separately upfront though, to ensure that compiler diagnostics get refreshed before we compute analyzer diagnostics. We basically have 4 calls into `CompilationWithAnalyzers`: compiler syntax diagnostics, compiler semantic diagnostics, analyzer syntax diagnostics, analyzer semantic diagnostics. This means lot of reasoning why the partial analyzer state tracking logic was added into `CompilationWithAnalyzers` may no longer be required. We can use the following implementation logic:
1. For compiler syntax and semantic diagnostics, use the [underlying compilation](https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,23) to compute diagnostics without any state tracking.
2. For analyzer diagnostics, we cannot re-use the same [underlying compilation](https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,23) without state tracking, so we just fork the compilation for computing analyzer diagnostics and do not re-use this forked compilation for any other calls into `CompilationWithAnalyzers`. Forking compilation should be fine here as we only make 2 calls into `CompilationWithAnalyzers` for all analyzer syntax and semantic diagnostics. In case a cancellation happens during analyzer execution and the host re-queries for the diagnostics for the same tree, we will use a new forked compilation, so we don't run into the risk of duplicate callbacks into the analyzer for the same compilation.
3. [AnalysisResultBuilder](https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,47) within `CompilationWithAnalyzers` will be changed to de-dupe reported analyzer diagnostics.

I prototyped the above changes over the last week and see significant memory improvements in allocations and peak memory pressure for background analysis. Steady state memory usage for the OOP Roslyn ServiceHub process reduces by almost 30%-40% on opening bunch of files in the C# compiler project in Roslyn.sln, all of this savings coming from no longer holding AnalysisState objects in memory for current project. I also notice vast reduction in allocations from background analysis. I haven't measured the execution time differences, but something I plan to carry out this week. Another big plus here is we can delete a large amount of code and reduce maintenance costs for a part of code base that has had very subtle race conditions over time.

**Fallback approach:** If the above approach of completely getting rid of AnalysisState for partial state tracking does not work out for some reason (perf or functionality), then we can experiment with optimizing memory usage in AnalysisState by tracking spans instead of syntax nodes and operations. This fallback strategy should also lead to good amount of performance improvements.

**Comment by mavasani** [comment]
FYI @arkalyanms @sharwell @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
> I prototyped the above changes over the last week and see significant memory improvements in allocations and peak memory pressure for background analysis. Steady state memory usage for the OOP Roslyn ServiceHub process reduces by almost 30%-40% 

Nice!

Am i also reading the above correctly that this likely makes things *simpler*?  If so, that's great in my book :)

My general feedback about this space is simply that it's enormously complex.  So we should be really focusing on high simplification efforts.  My hope/belief/bias is that doing that will also make easier to optimize :)

**Comment by mavasani** [comment]
> Am i also reading the above correctly that this likely makes things simpler? If so, that's great in my book :)

Yes, that is also one big motivation. We should be able to make the core analyzer execution layer much more simpler.

 > My general feedback about this space is simply that it's enormously complex. So we should be really focusing on high simplification efforts. My hope/belief/bias is that doing that will also make easier to optimize :)

Yes, definitely. However, one issue I ran into yesterday during more dogfooding is for partial types. My simpler model of just forking the compilation for each semantic analyzer diagnostics request for each open file is not sufficient if the file has a partial type with other partial definitions in separate files. We have SymbolStart/SymbolEnd analyzers that need to run analyzer callbacks for all partial type definitions on the same compilation to get the correct SymbolEnd diagnostics. This was easier to implement in the current model with state tracking, but is a bit more trickier in the newer model. Despite these hurdles, the code simplification + performance improvement from removing all state tracking logic should bring overall goodness, so I am going to keep pursuing this path. Eventually, we will be doing a val build with RPS + also run the compiler benchmark suites for it: https://github.com/dotnet/performance/blob/1c76fee8e93712f5d8422f04fe0011705ebf3090/src/benchmarks/real-world/Roslyn/StageBenchmarks.cs#L47-L70

**Comment by sharwell** [comment]
> Steady state memory usage for the OOP Roslyn ServiceHub process reduces by almost 30%-40%

Can you check what the steady-state behavior looks like when ServiceHub is disabled as well?

**Comment by mavasani** [comment]
# Performance measurements

Measurements were done against locally built Release bits from main branch and PR branch for #66750 across the following scenarios. For some of the scenarios, I also measured numbers for InProc analyzer execution in devenv.exe process by unchecking the below Tools Options check box:

![image](https://user-images.githubusercontent.com/10605811/217788746-1e6b9c90-2280-4feb-8d69-e820a77aabc5.png)

## Scenario 1) Compute diagnostics for a single, very large source file
### Steps
1. Follow the steps in https://developercommunity.visualstudio.com/t/Code-Analyzer-crashes-for-a-large-file/10016304 to create a Winforms app with a huge source file (1000k lines)
2. Open this source file in VS and wait for error list to finish computing diagnostics 

### Performance numbers
| Sr. No. | Metric | OutOfProc Analyzer Execution | OutOfProc Analyzer Execution | InProc Analyzer Execution | InProc Analyzer Execution |
| :---: | :---: | :---: | :---: | :---: | :---: |
| | | **main branch** | **PR branch** | **main** | **PR branch** |
| 1. | Time to complete scenario | 6 minutes 45 seconds |  3 minutes 50 seconds |  --- | --- |
| 2. | Peak memory usage (ServiceHub OOP process) | 12 GB |  5 GB |  --- | --- |
| 3. | Peak memory usage (devenv.exe process) | 6 GB |  6 GB |  --- | --- |

## Scenario 2) Opening bunch of source files
### Steps
1) Open `Roslyn.sln` with no open files
2) Open below source files one by one from `Microsoft.CodeAnalysis.csproj` and `Microsoft.CodeAnalysis.CSharp.csproj`:
   - `AnalyzerDriver.cs`
   - `CompilationWithAnalyzers.cs`
   - `Binder.cs`
   - `Binder_Expression.cs`
   - `Binder_Statements.cs`
   - `Operations.Generated.cs`
3) Wait for error list to finish computing diagnostics after each file open
4) Make a single edit to `Binder.cs`
5) Wait for error list to finish refreshing

### Performance numbers
| Sr. No. | Metric | OutOfProc Analyzer Execution | OutOfProc Analyzer Execution | InProc Analyzer Execution | InProc Analyzer Execution |
| :---: | :---: | :---: | :---: | :---: | :---: |
| | | **main branch** | **PR branch** | **main** | **PR branch** |
| 1. | Time to complete scenario | 11 minutes 30 seconds | 5 minutes |  4 minutes | 3 minutes |
| 2. | Peak memory usage (ServiceHub OOP process) | 11.5 GB ** |  8.5 GB |  N/A | N/A |
| 3. | Steady state memory usage (ServiceHub OOP process) *** | 6 GB |  4.8 GB |  N/A | N/A |
| 4. | Peak memory usage (devenv.exe process) | 5 GB |  3.5 GB |  11.2 GB | 11.5 GB  |
| 5. | Steady state memory usage (devenv.exe process) *** | 3.5 GB |  3.5 GB |  11.2 GB | 9.6 GB  |

 ** _For main branch measurement, OOP memory usage rises to 9 to 10 GB and falls to 5 GB couple of times during the scenario, indicating higher allocations and GC in OOP. This doesn't happen for measurements against the PR branch during the scenario._

 *** _Steady state memory usage - memory measured few seconds after scenario completion (20-30s) when the CPU usage for for both ServiceHub OOP process and devenv process has dropped to 0_

## Scenario 3) Reading code and switching between open files
### Steps
1) Open `Roslyn.sln` with below files from `Microsoft.CodeAnalysis.csproj` and `Microsoft.CodeAnalysis.CSharp.csproj` already opened at VS startup:
   - `AnalyzerDriver.cs`
   - `CompilationWithAnalyzers.cs`
   - `Binder.cs`
   - `Binder_Expression.cs`
   - `Binder_Statements.cs`
   - `Operations.Generated.cs`
2) Tab to each open file and wait for error list to finish refreshing
3) Edit `Binder.cs`
4) Wait for error list refresh
5) Open `Binder_Invocation.cs` and wait for error list refresh

### Performance numbers
| Sr. No. | Metric | OutOfProc Analyzer Execution | OutOfProc Analyzer Execution | InProc Analyzer Execution | InProc Analyzer Execution |
| :---: | :---: | :---: | :---: | :---: | :---: |
| | | **main branch** | **PR branch** | **main** | **PR branch** |
| 1. | Time to complete scenario | 10 minutes | 4 minutes 20 seconds |  3 minutes 50 seconds | 4 minutes 45 seconds |
| 2. | Peak memory usage (ServiceHub OOP process) | 9 GB** | 7.7 GB |  N/A | N/A |
| 3. | Steady state memory usage (ServiceHub OOP process)  | 4.6 GB | 4.3 GB |  N/A | N/A |
| 4. | Peak memory usage (devenv.exe process) | 3.8 GB | 4 GB |  10 GB | 9 GB  |
| 5. | Steady state memory usage (devenv.exe process) | 3.8 GB | 4 GB |  11.2 GB | 9 GB  |

  ** _For main branch measurement, OOP memory usage rose to 8 to 9 GB and fell to 5 GB once during the scenario, indicating higher allocations and GC in OOP. This doesn't happen for measurements against the PR branch during the scenario._

## Scenario 4) Editing source code
### Steps
1) Open `Roslyn.sln` with below files from `Microsoft.CodeAnalysis.csproj` and `Microsoft.CodeAnalysis.CSharp.csproj` already opened at VS startup:
   - `AnalyzerDriver.cs`
   - `CompilationWithAnalyzers.cs`
   - `Binder.cs`
   - `Binder_Expression.cs`
   - `Binder_Statements.cs`
   - `Operations.Generated.cs`
2) Open `CompilationWithAnalyzers.cs` and make few edits:
   ```csharp
        private void SomeMethod(int[] array)
        {
            for (int i = 0; i < array.Length; i++)
            {
                Console.WriteLine(i);
            }
        }
   ```
   1. Type out empty method `SomeMethod`, wait for 10 seconds
   2. Type out the for loop header, wait for 5 seconds
   3. Type out loop body
   4. Wait for error list refresh
3) Open `Binder.cs` and make repeat edits from previous step

### Performance numbers
| Sr. No. | Metric | OutOfProc Analyzer Execution | OutOfProc Analyzer Execution | InProc Analyzer Execution | InProc Analyzer Execution |
| :---: | :---: | :---: | :---: | :---: | :---: |
| | | **main branch** | **PR branch** | **main** | **PR branch** |
| 1. | Time to complete scenario | 6 minutes 45 seconds | 4 minutes |  4 minutes 40 seconds | 3 minutes 25 seconds |
| 2. | Peak memory usage (ServiceHub OOP process) | 9 GB | 6.7 GB |  N/A | N/A |
| 3. | Steady state memory usage (ServiceHub OOP process)  | 9 GB | 4.8 GB |  N/A | N/A |
| 4. | Peak memory usage (devenv.exe process) | 3.1 GB | 2.9 GB | 9 GB | 8.1 GB  |
| 5. | Steady state memory usage (devenv.exe process) | 3.1 GB | 2.9 GB | 9 GB | 8.1 GB |
