### ISSUE TITLE
VS2022 intellisense removes whitespace when using <inheritdoc>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66719]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-intellisense-removes-whitespace-w/10269588)._

---
\[severity:It bothers me. A fix would be nice\]  
Take the following code:

``` csharp 
/// <summary><see langword="true"/> <see langword="false"/> perhaps</summary>
public bool Foo { get; }

/// <inheritdoc cref="Foo"/>
public bool Bar { get; }
```

1.  Hovering Foo, intellisense describes it as “true false perhaps” (with true and false coloured blue) - exactly as expected.
2.  Hovering Bar, intellisense describes it as “truefalse perhaps” (with true and false coloured blue) - with the whitespace between the two sub-elements removed, but not between sub-elements and regular text (or between words in regular text). This applies for all combinations of sub-elements I’ve tried, such as  etc.

---
#### Feedback Bot on 2/2/2023, 09:06 PM: 

(private comment, text removed)

---
#### Erik Westberg solved on 2/5/2023, 09:00 PM, 0 votes: 

<p>A non-breaking space can be used between elements to force a whitespace. “&amp;_#_160;” without the underscores.</p>

**Comment by Eagle3386** [comment]
When this gets fixed, the general XML syntax violation of skipping to insert a single whitespace between `"` and `/` should be fixed, too.
That's because `<see cref="IFoo"/>` is nothing but incorrect XML syntax & must be written as `<see cref="IFoo" />`

**Comment by CyrusNajmabadi** [comment]
> That's because `<see cref="IFoo"/>` is nothing but incorrect XML

Why is that the case?

**Comment by CyrusNajmabadi** [comment]
Looking at the spec: https://www.w3.org/TR/xml/#sec-starttags

> Tags for Empty Elements
> `[44]   	EmptyElemTag	   ::=   	'<' Name (S Attribute)* S? '/>'	[WFC: Unique Att Spec]`
> 
> Empty-element tags may be used for any element which has no content, whether or not it is declared using the keyword EMPTY

This states that optional spaces are legal at the end.  An example is even given for this:

![Image](https://github.com/user-attachments/assets/44befd31-6215-493e-805b-68b5b03ae520)

**Comment by Eagle3386** [comment]
@CyrusNajmabadi Yes, I was mislead by my personal background of XHTML where - back in the days - `<br />` & only that notation was allowed. Forgive me.
But still, it'll be nice if VS supported those preferring `<br />` instead of `<br/>`.

**Comment by CyrusNajmabadi** [comment]
> But still, it'll be nice if VS supported those preferring

Def file a suggestion.  It seems out of scope of this issue.

**Comment by Eagle3386** [comment]
@CyrusNajmabadi Sorry for asking that much questions, but what does "Def file a suggestion" mean? That "Def" confuses me here.. 😞

**Comment by CyrusNajmabadi** [comment]
reactivating.  i clicked on the wrong button.  thanks :)
