### ISSUE TITLE
Checked-in `WindowsProxy.winmd` binary in the repository

### ISSUE THREAD

**Issue by premun** [dotnet/roslyn#66718]
### Context

The key goal of source-build is to satisfy the official packaging rules of commonly used Linux distributions, such as [Fedora](https://fedoraproject.org/wiki/Packaging:Guidelines) and [Debian](https://www.debian.org/doc/manuals/maint-guide/build.en.html). Many Linux distributions have similar rules. These rules tend to have two main principles: consistent reproducibility, and source code for everything.

In order to support the "source code for everything" requirement, binary files are not allowed in product repositories. Aside from, binaries that can be created during the build process from source are better not to be checked in as one of the main goals of git is that humans can review the code changes.

The file in question: https://github.com/dotnet/roslyn/blob/main/src/ExpressionEvaluator/Core/Source/ExpressionCompiler/Resources/WindowsProxy.winmd

### Questions

- What scenario / which RID is this file used for?
- Is this file necessary for a successful build of the .NET SDK?
- If it is, can it be removed from the repository and replaced with a source and process that synthesizes it during build?

### Possible workarounds

At the moment, we only source-build Linux x64/arm64 so if this file is required for other RIDs, it can be temporarily removed from the source build. This is only in case it's difficult to replace the file with source. Other platforms will be supported by source build in the future though, so this problem will re-surface in case we go around it this way.

**Comment by jcouv** [comment]
Tagging @tmat @cston to triage/assign. Thanks

**Comment by dviererbe** [comment]
Hi, I am a Maintainer for the .NET Ubuntu packages. I noticed that the new binary tool does delete this binary for source-build, because it is excluded (see: https://github.com/dotnet/dotnet/blob/9b6ca75f0d7283c3bce8e77c6859741ea9bb7add/eng/allowed-sb-binaries.txt#L50-L51).

> Is this file necessary for a successful build of the .NET SDK?

I do not think so, because we removed this file from our source tarballs for .NET 6, 7 and 8 and have not encountered any issues yet.

Because I think it is not needed, I was wondering why it was excluded from removal?

**Comment by akoeplinger** [comment]
That looks like an error, the file is Windows-specific so it should be removed in source-build and only be there in the Microsoft VMR build.

**Comment by akoeplinger** [comment]
Ah I see, the whole ExpressionEvaluator tree is excluded from building in source-build, that's why you don't need to touch the project file: https://github.com/dotnet/roslyn/blob/08a167c19e5e04742b0922bdb1ea8046e9364f4b/src/ExpressionEvaluator/Directory.Build.props#L4

**Comment by ellahathaway** [comment]
This was removed from source-build with https://github.com/dotnet/sdk/pull/42949. Given that, can we close this issue?

**Comment by dviererbe** [comment]
> This was removed from source-build with [dotnet/sdk#42949](https://github.com/dotnet/sdk/pull/42949). Given that, can we close this issue?

With the file removed from the source build exclude list, this is fine from my side 👍🏻
