### ISSUE TITLE
CSharpSyntaxWalker does not invoke VisitTrivia

### ISSUE THREAD

**Issue by CodeSetting** [dotnet/roslyn#66713]
**Version**
NuGet Microsoft.CodeAnaylsis.CSharp 4.4.0

**Description**
The `CSharpSyntaxWalker` class does not visit trivia by invoking its `VisitTrivia` method.  In the documentation, I did not find a mention that this is the expected behavior, so I assume it is a bug.

If this is not a bug...

- Is there an option to make it visit this trivia (like the derived `CSharpSyntaxRewriter` does)?
- Can some note be added to the documentation to clarify this limitation (or the availability of an option)?
- Can the class be enhanced in a future version to support this behavior?  It is very inconvenient.

**Steps To Reproduce**
1. Parse some text containing trivia via `CSharpSyntaxTree.ParseText`.
2. Create a derivation of `CSharpSyntaxWalker` that overrides `VisitTrivia` and produces noticeable output.
3. Instantiate the derived class.
4. Invoke the `Visit` method of the instance for the root node of the tree returned by `CSharpSyntaxTree.ParseText`.
5. Verify that no noticeable output is produced by the override of `VisitTrivia`.

**Sample Console Application**
The following application demonstrates the difference in behavior between `CSharpSyntaxWalker` and `CSharpSyntaxRewriter`.

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

var tree = CSharpSyntaxTree.ParseText(
    "class MyClass { /* My comment */ int x = 0; }");

Console.WriteLine(nameof(TrivialWalker));
new TrivialWalker().Visit(tree.GetCompilationUnitRoot());
Console.WriteLine();

Console.WriteLine(nameof(TrivialRewriter));
new TrivialRewriter().Visit(tree.GetCompilationUnitRoot());

public class TrivialRewriter : CSharpSyntaxRewriter
{
    public override SyntaxTrivia VisitTrivia(SyntaxTrivia trivia)
    {
        Console.WriteLine($"  {trivia.Kind()} \"{trivia}\"");
        return base.VisitTrivia(trivia);
    }
}

public class TrivialWalker : CSharpSyntaxWalker
{
    public override void VisitTrivia(SyntaxTrivia trivia)
    {
        Console.WriteLine($"  {trivia.Kind()} \"{trivia}\"");
        base.VisitTrivia(trivia);
    }
}
```

**Expected Behavior**:
The program should display the same out for both `TrivialWalker` (`CSharpSyntaxWalker`) and `TrivialRewriter` (`CSharpSyntaxRewriter`).

**Actual Behavior**:
The program does **not** display any trivia visited by `TrivialWalker`, indicating that trivia is **not** visited and its `VisitTrivia` method is **not** invoked.

The following is the actual output:

```
TrivialWalker

TrivialRewriter
  WhitespaceTrivia " "
  WhitespaceTrivia " "
  WhitespaceTrivia " "
  MultiLineCommentTrivia "/* My comment */"
  WhitespaceTrivia " "
  WhitespaceTrivia " "
  WhitespaceTrivia " "
  WhitespaceTrivia " "
  WhitespaceTrivia " "
```

**Comment by CodeSetting** [comment]
I found that by adding the following constructor to TrivialWalker I was able to get the expected behavior.

```csharp
public TrivialWalker() : base(SyntaxWalkerDepth.Trivia) { }
```

While I don't like the default value of depth or the parameter's name, this does not seem to be a bug.  So, I am closing this issue.

The documentation for the constructor does poorly to describe this behavior.  I'll add feedback for that page instead.

Sorry for the issue.

**Comment by CyrusNajmabadi** [comment]
@CodeSetting best to maybe just submit docs pr to improve things there :-)

**Comment by CodeSetting** [comment]
@CyrusNajmabadi  Thank you. The feedback button on the bottom of the page "automagically" opens a PR for the related docs...so, done and linked to this non-issue :smile:

**Comment by CyrusNajmabadi** [comment]
Perfect!
