### ISSUE TITLE
VS2022: Intellisense agressively inserts unneeded/incorrect usings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022:-Intellisense-agressively-inserts/10265665)._

---
Intellisense very helpfully inserts usings as you type code, but it has become intrusively aggressive to the point where it slows development down.
After only 10 minutes typing code my using list looks like this:

![image.png](https://aka.ms/dc/image?name=B5b24624d36624997b816523f20af8bc1638107543252501145_20230131-093205-image.png&tid=5b24624d36624997b816523f20af8bc1638107543252501145)

This is in a WPF project so it should never have any references to Windows.Forms. How it even thought I needed AxImporter is beyond me - no doubt it decided momentarily that I wanted to autocomplete the name of a local variable with a "much better match" from an unreferenced dll at the far outer rim of the universe. If it's going to insert this junk then please can it remove it again when it discovers the using isn't needed - all the spurious entries are greyed out, so it knows they are unused. This could be achieved by using a short term cache of the usings it has auto-added, and if they are discovered not to be needed when I have finished typing that line of code, or even just the current symbol, then they could be removed again.  

It is becoming quite disruptive having to keep deleting all this junk manually. It frequently causes problems where same-named types exist in different namespaces, as intellisense often prefers to add distant types rather than the ones defined locally, so it often resolves the types incorrectly. You can no longer autocomplete code as intellisense has added a using that resolves to the wrong type - this is much worse than simply showing the symbols as an unknown type and allowing me to ctrl+.  and choose the correct namespace. Intelllisense should not autonomously add usings when there are multiple possible namespaces to choose from - it needs to ask the user in such a case.

---
#### Feedback Bot on 1/31/2023, 11:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Can disable thee features by turning off:

![image](https://user-images.githubusercontent.com/4564579/217320887-5cb9f517-9967-47ba-a259-fc95ca6f613c.png)

and

![image](https://user-images.githubusercontent.com/4564579/217320994-4037ab90-3e4d-4369-9ac9-99fd8bdce93a.png)
