### ISSUE TITLE
Inplace Property + DefaultConst definition

### ISSUE THREAD

**Issue by comdiv** [dotnet/roslyn#6674]
Now
```
class A{
    public const string DefaultMyValue = "mydefault";
    public string MyValue {get;set;} = DefaultMyValue;
}
```
motivation - remove magic string, allow restore of values, allow caller to lookup possible values without instantiation of class
problems:
1) we should explicitly define two same by type and close by value members
2) any codecleaner would try to separate members to long distance in file

Think that inline const syntax could be helpfull
```
class A {
    public string MyValue {get;set;} = const "mydefault";  //should automatically create const with name DefaultMyValue

   public string MyValue2{get;set;} = static "mydefault2"; //should automatically create writeable static DefaultMyValue

   public string MyValue3{get;set;} = protected const "zzz"; //const should have protected visibility
}
```

**Comment by gafter** [comment]
We generally do not have the compiler make up public APIs with names not provided by the user.
