### ISSUE TITLE
Move `UseValueTuple` from `SymbolDisplayCompilerInternalOptions` to `SymbolDisplayMiscellaneousOptions`

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66757]
## Background and Motivation

IDE has a [bug](https://github.com/dotnet/roslyn/issues/22626) where we spit out the wrong signature for members containing tuples within crefs.  e.g. we emit:

```
<seealso cref="M((string, int))"/>
```

Which is not considered legal by the language.  We need to generate 

```
<seealso cref="M(ValueTuple{string, int})"/>
```

instead.  Currently, we are making use of hte compiler's ability to give us viable symbol display strings using ToDisplayString with appropriate options for this scenario.  However, we are lacking any way to say not to give us tuples, but instead give us ValueTuple.  Internally, the compiler already has a flag for this, it's just not exposed publicly.  So the request is to just give us that.

## Proposed API

```diff
public enum SymbolDisplayMiscellaneousOptions
{
+        /// <summary>
+        /// Display `System.ValueTuple` instead of tuple syntax `(...)`.
+        /// </summary>
+        UseValueTuple = 1 << 11,
}
```

## Alternative Designs

Do not expose anything.  But that will require the IDE to effectively have to rewrite all the logic present that uses symbol display here (really undoing the value of SymbolDisplay and a core reason we created it in the first place).

**Comment by 333fred** [comment]
### API Review

* `ExpandValueTuple` in Misc options
* Approved
