### ISSUE TITLE
GetProjectDependencyGraph doesn't return dependencies

### ISSUE THREAD

**Issue by mvodep** [dotnet/roslyn#66754]
**Version Used**: 
3.3.1

**Steps to Reproduce**:

1. Create a "Standalone Code Analysis Tool"
2. Create a Reference Project where "OrderManagement.OrderGateway" references "OrderManagement.Invoicing"
3. Call solution.GetProjectDependencyGraph().GetProjectsThatTransitivelyDependOnThisProject (https://github.com/mvodep/Playground/blob/main/Roslyn/Architecture/ArchitectureAnalyzer/ArchitectureAnalyzer/ProjectDependeciesAnalyzer.cs)

Minimal Solutions: https://github.com/mvodep/Playground/tree/main/Roslyn/Architecture

**Expected Behavior**:
OrderManagement.Invoicing y is returned (https://github.com/mvodep/Playground/blob/main/Roslyn/Architecture/OrderManagement/OrderManagement.OrderGateway/OrderManagement.OrderGateway.csproj) when calling depency for OrderManagement.OrderGateway

**Actual Behavior**:
No dependecy is returned

**Comment by CyrusNajmabadi** [comment]
> Create a Reference Project where "OrderManagement.OrderGateway" references "OrderManagement.Invoicing"

If OrderGateway references Invoicing, then i would not expect Invoicing to be returned when calling GetProjectsThatTransitivelyDependOnThisProject on OrderGateway.  Invoicing doesn't depend on OrderGateway.  It's the reverse.  OrderGateway depends on Invoicing.

**Comment by mvodep** [comment]
You are right - I was trying all methods - description is wrong.

But anyhow. As you can see in my demo project: I iterate over the solution (both projects) - no dependecy is returned at all. Its always an empty list - on both projects

**Comment by CyrusNajmabadi** [comment]
Are there any diagnostics reported by your workspace?

**Comment by mvodep** [comment]
I seems that the project template had too old packages. Updated all nuget Microsoft.CodeAnalaysis.* packages - now it works. Sorry
