### ISSUE TITLE
CoreClr command line compiler argument parsing

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6677]
The CoreClr command line compilers handle arguments differently from the desktop compilers.  They use the command line provided to `Main` instead of manually parsing out the arguments (`BuildClient.GetCommandLineArgs)`.  This means they will be unable to correctly handle arguments like:

```
/r:a,b 
/r:"a,b"
```

This can't be converted without thought though as the CoreClr compiler actually has extra arguments as for as windows is concerned.  `GetCommandLineW` on CoreClr will typically return `corerun.exe csc <rest of argument string>`.  Need to find a reliable way to peel off the host value from the Windows command line.

**Comment by tmat** [comment]
Do we need to support all the obscure command line parameter forms as desktop does?

**Comment by jaredpar** [comment]
It's not possible for us to change it on Windows.  The compiler is invoked by all manner of tools that generate arguments in the tricky patterns (MSBuild in particular).  Changing the parsing breaks all of these scenarios.

**Comment by tmat** [comment]
Is msbuild going to invoke us via corerun though? Isn't it giving us the command line thru a task?

**Comment by jaredpar** [comment]
@tmat yes on cross plat
