### ISSUE TITLE
Compiler no longer catches a whole class of programming errors due to the poor interaction of natural delegate types and generics

### ISSUE THREAD

**Issue by nagya** [dotnet/roslyn#66772]
**Version Used**: 

C# 10 and later.

**Steps to Reproduce**:

```csharp
using System;
Console.WriteLine($"id={Guid.NewGuid}");
```

**Expected Behavior**:

Compile error, or at least warning, that alerts the developer to the obvious typo, the missing `()` in the call to `Guid.NewGuid()`. This was the behavior before C# 10.

Once the typo is fixed, the expected output is like:

```
id=d5790d8a-563c-479a-9b41-b55f6504d3ae
```

**Actual Behavior**:

No error or warning; execution produces the following output:

```
id=System.Func`1[System.Guid]
```

**Comment by CyrusNajmabadi** [comment]
This is by design. Methods can now be referenced directly and have a natural type. 

We cannot warn here as it's completely legitimate to potentially pass delegates to these apis.  It's a normal pattern and internally apis may then choose to invoke the delegate in a lazy fashion to get a value.

**Comment by nagya** [comment]
@CyrusNajmabadi, the same could be said for a method that takes an `object`, yet:

```
object o = Guid.NewGuid;
[CS8974] Converting method group 'NewGuid' to non-delegate type 'object'. Did you intend to invoke the method?
```

The same scrutiny would be useful when the target type is not object, but an un-constrainted generic.
