### ISSUE TITLE
Incorrect CS8774 when adding extra conditions that shouldn't affect nullable analysis

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#66773]
**Version Used**: 17.5.0 Preview 4.0

**Steps to Reproduce**:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

public class C
{
    public C() => Refresh();
    
    public IEnumerable<string> Foo;
    
    [MemberNotNull(nameof(Foo))]
    public bool Refresh()
    {
        IEnumerable<string> baz = new[] { "Hello", "World" };
        
        if (Foo is null ||
            !baz.SequenceEqual(Foo ?? Enumerable.Empty<string>()))
        {            
            Foo = baz;
            
            return true;            
        }
        
        return false;
    }
}
```

[Sharplab link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4oDchJ5OAdACICWAhgOYB2EAzgC4swvBgGEIAExgBBLmwA2AT14teNImQoMAMiy4BHdbQDM5LKVGEA3oVJ3yp0QAoAlKQC8APlIAlGADNYXgALV3V7Ult7DFMKYwAeCmJvADEICHD7KLsAbQBZGABbYBgoADkIfjKAV3l5JzlCmAh/JzSIFxcAXWyHUmB0+V8AoNCXXpsCCIi4xJxk/rYALw9SLhgAdxyu0itSACIACRg6iH2AGgOAdWh5CX3SAF9M6cip19IWf1I29M/eNa1IZoNC9D6kACEwGWDAAyjB9NUYFwwDAAKKIhS/CCkAD8uNIaK41SaUDYwHkMAYaMKAAd+Io5slXJ0wfY9uCsu9OaR2qtoUsXpy2a8MAB2Uj8KBIqg8uwip4KhXi0j+BS8GBCx6ER5AA=).

**Diagnostic Id**: CS8774

**Expected Behavior**:

No warning should be generated.

**Actual Behavior**:

> "warning CS8774: Member 'Foo' must have a non-null value when exiting."

Is produced on that `return false;` statement. Note that **removing the `!baz.SequenceEqual(Foo ?? Enumerable.Empty<string>())` makes the error go away**. This is incorrect, because that condition is an OR expression with `Foo is null`, so regardless of whether that evaluates to true or false, the conditional branch is always taken if `Foo` is null, meaning that in all cases, when the method returns `Foo` is always guaranteed to not be null.

**Comment by Youssef1313** [comment]
I believe this is by-design. When you do an explicit null check, the null state becomes "maybe null"

So, `Foo ?? ...` makes `Foo` as "maybe null".

The code should just be:

```csharp
        if (Foo is null || !baz.SequenceEqual(Foo))
```

**Comment by RikkiGibson** [comment]
I've been curious in the past whether there is some way we could indicate "by the way, here's where we decided the variable might contain null.." which could "blame" the `??` expression. However, I don't expect to invest time in figuring that out in the near term.
