### ISSUE TITLE
Is "Enforce code style on build" still an experimental feature?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#66788]
Is this feature still in the experimental stage? If not, can the experimental text be removed

https://github.com/dotnet/project-system/blob/badd7918a9939559a6927a3a4b5b1ec690117972/src/Microsoft.VisualStudio.Editors/PropPages/xlf/CodeAnalysisPropPage.zh-Hans.xlf#L35-L39

https://github.com/dotnet/project-system/blob/e1a502c54f64ada738285e89f05a5ce7917003c5/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/CodeAnalysisPropertyPage.xaml.zh-Hans.xlf#L20-L24

![image](https://user-images.githubusercontent.com/350947/196654110-d297b3f6-6859-48a7-9c61-a1749e269466.png)

![image](https://user-images.githubusercontent.com/350947/196654161-735c793a-a0b4-4f3e-bd63-0cd349a6ea90.png)

**Comment by drewnoakes** [comment]
Moving to Roslyn as project-system does not own this UI.

**Comment by mavasani** [comment]
This is no longer experimental. Tagging @jmarolf @mikadumont

**Comment by drewnoakes** [comment]
I filed https://github.com/dotnet/project-system/pull/8846 to remove the "(experimental)" qualifier from these strings. If your team approves, we can merge it for 17.6.

**Comment by drewnoakes** [comment]
The Project System change has been merged. Updating the docs is being tracked by https://github.com/dotnet/docs/issues/33956.
