### ISSUE TITLE
Pause and continue Event execution

### ISSUE THREAD

**Issue by hrastyy** [dotnet/roslyn#668]
In some cases I'd like Events not to be rose immediately. Would be nice if you could introduce something like
Button1.Click.Pause(); /\* or */ Button1.Click.Wait();
as well as
Button1.Click.Continue(); // to reset Event functionality ignoring pending Actions
and
Button1.Click.ContinueExecutePending(); // to execute pending Actions and reset Event functionality
And some Attribute in System.Windows.Forms.Form would be nice, something like
MyForm.Events.Interrupt(); // to stop Event execution until return of current method

**Comment by svick** [comment]
This sounds like something that could by done by using a library, I don't see why would you need to change the language for this.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
