### ISSUE TITLE
Interactive: Signature help not classified

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6681]
**Expected Behavior**:

![image](https://user-images.githubusercontent.com/41759/78519422-280ddf00-7778-11ea-8a87-1835fdbd6367.png)

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/41759/78519411-1d534a00-7778-11ea-8ebb-3f8152823295.png)

**Comment by Pilchie** [comment]
It's also not classified in razor files.  I believe the problem is that the sig help is presented on the surface buffer, but our classification only works on the subject buffer specific content type.

**Comment by jasonmalinowski** [comment]
Moving back to IDE since it impacts non-interactive too.

**Comment by CyrusNajmabadi** [comment]
Need info if we're even fixing interactive issues or not.
