### ISSUE TITLE
Compiler doesnt create field in StateMachine in release mode

### ISSUE THREAD

**Issue by GazziFX** [dotnet/roslyn#66829]
**Version Used**: dotnet 6.0.308

**Steps to Reproduce**:

1. Write code below
2. Run in debug
3. Run in release

It happens if pointers is used

```csharp
long x = 10;

unsafe
{
    Console.WriteLine(*&x);
}

await Task.Delay(1000);

unsafe
{
    Console.WriteLine(*&x);
}
```

**Expected Behavior**: prints 10 both times

**Actual Behavior**: prints 10 and 0

**Comment by GazziFX** [comment]
If I assign same variable it works as expected
```csharp
long x = 10;

unsafe
{
    Console.WriteLine(*&x);
}

await Task.Delay(1000);

x = x;

unsafe
{
    Console.WriteLine(*&x);
}
```

**Comment by jaredpar** [comment]
I suspect that we're not treating `&` as read operations in our lifting logic here and that is what causes this issue.
