### ISSUE TITLE
IncrementalValuesProvider returns wrong cached objects

### ISSUE THREAD

**Issue by thecamper222** [dotnet/roslyn#66840]
**Version Used**: Microsoft.CodeAnalysis.CSharp v4.4.0

**Steps to Reproduce**:

1. Edit PropertyName Attribute value in GenerateProperties.LetPropiertiesGenerate for the first field from one char to zero chars and back to one char
2. Check the generated output
3. Issue is reproduceable with every field expect the last two

**Diagnostic Id**:
Sorry I don't really know how to get one.

**Expected Behavior**:
No matter how often I change the value of the property from one char to zero chars, the source generator is generating the properties for all remaining fields, depending on the rules.

**Actual Behavior**:
Every time I execute the steps to reproduce, the next field below the field that was changed is gone. 
Instead the last field of the class gets duplicated and is generated multiple times.

**Additional information:**
If I remove the caching, by making my struct cache unfriendly everything works fine. And since I'm checking for equality by comparing all properties which are value types, I don't think the issue is in the equality check of the transformed objects.

**Solution with IIncrementalSourceGenerator and one class** 
[AutoPropertySourceGenerator.zip](https://github.com/dotnet/roslyn/files/10719617/AutoPropertySourceGenerator.zip)

**Comment by jaredpar** [comment]
@jjonescz can you take a look? Suspect there is an issue with equality here.

**Comment by jjonescz** [comment]
Verified locally that this will be fixed by #66840.

**Comment by jaredpar** [comment]
Duping against #66643
