### ISSUE TITLE
Which commit corresponds to 4.4.0 (latest) on nuget? 

### ISSUE THREAD

**Issue by benjamin-asdf** [dotnet/roslyn#66848]
We have a fork of roslyn and would like to use the exact commit that is the latest nuget package release commit (version 4.4.0 here: https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/).

**Comment by CyberAndrii** [comment]
It is displayed on the README tab

![image](https://user-images.githubusercontent.com/37713088/218591737-0ef058ed-7585-4cf2-80b7-7b9ece0227a5.png)

**Comment by benjamin-asdf** [comment]
Thanks!
