### ISSUE TITLE
EditorBrowsable is not working on Visual Studio 2022

### ISSUE THREAD

**Issue by komdil** [dotnet/roslyn#66843]
### Description

I have some scenarios in which I need to hide my properties (or class members) from IntelliSense to not confuse some other developers that use my code. 
After some research, I found an attribute from the `System.Runtime` named `EditorBrowsable`. The summary comment of this class is saying that: `Specifies that class or member is viewable in an editor. This class cannot be inherited `

When I use this attribute on my code, it is not working as I expect. My properties are still showing on Visual Studio IntelliSense ****

### Reproduction Steps

Create a class library project on .NET6 named Model
Create User class, add two properties and put EditorBrowsable in one of them: 
 
```
   public class User
    {
        public int Id { get; set; }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public string accessId { get; set; }
    }
```

Create new console project named MyBL, add project reference to Model project and try to use created class: 

![image](https://user-images.githubusercontent.com/50167116/218472184-4850c105-fbac-4cac-84fb-77aa0fd74a22.png)

### Expected behavior

Visual Studio IntelliSense should not show accessId property because I put `[EditorBrowsable(EditorBrowsableState.Never)] `attribute

### Actual behavior

Visual Studio IntelliSense is showing that property 

### Known Workarounds

It will work when you 
remove project reference
add dll reference 
unload Model project 
re-open visual studio 

### Other information

I am not sure maybe it is Visual Studio bug or it is expected, but according to the summary comment of class it should work

**Comment by komdil** [comment]
@stephentoub I tried, but it didn't work

**Comment by CyrusNajmabadi** [comment]
Note. Editorbrowsable will only work for metadata references, not source references.

**Comment by komdil** [comment]
> Note. Editorbrowsable will only work for metadata references, not source references.

Hmm, Is there any way to do this without making a metadata reference and without changing the structure of classes? It looks like the issue (#4434) is still opened

**Comment by komdil** [comment]
> No. The entire design here is about hiding from external consumers. If you have source access, then it's your choice, and you should see it all.
> 
> This is very much intentional.

I am not sure what to do. Can you make it clear?

**Comment by MrGadget1024** [comment]
I know this is closed, but when dealing with classes that have a lot of `ShouldSerializeWhatever` methods, which have to be public for XmlSerializer to use them, having them all show up in IntelliSense in a separate project from that class is really annoying.

Yes, I'm smart enough not to actually call them from a consuming app, but it's a long scroll to get past them when looking for a method or property that happens to be after them alphabetically.

I also tried removing the project reference and adding a direct ref to the compiled DLL, and they still show up when decorated with `EditorBrowsable(EditorBrowsableState.Never)`.

**Comment by CyrusNajmabadi** [comment]
> I also tried removing the project reference and adding a direct ref to the compiled DLL, and they still show up when decorated with EditorBrowsable(EditorBrowsableState.Never).

@MrGadget1024 Can you please file a bug with a repro for that part?

**Comment by MrGadget1024** [comment]
> Can you please file a bug with a repro for that part?

Would that be expected to work for Debug builds of the DLL, or only Release builds?

**Comment by MrGadget1024** [comment]
> Can you please file a bug with a repro for that part?

Done - See #71209
