### ISSUE TITLE
Interactive: No way bulk #r

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6687]
I have a directory of assemblies I'd like to #r.

#r doesn't appear to support wildcards ("#r *.dll" didn't work).

I also can't #r in a loop:
foreach (var file in str.Split(new[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries))
. {
. #load "C:\roslyn-internal\Open\Binaries\Debug" + file
. }
(3,2): error CS8098: Cannot use #load after first token in file
(3,48): error CS1025: Single-line comment or end-of-line expected

**Comment by amcasey** [comment]
Are the assemblies related to each other?  `#r` automatically pulls in dependencies, so referencing the "last" one goes a long way.

**Comment by amcasey** [comment]
FYI @tmat

**Comment by MgSam** [comment]
Wildcard support would be really helpful. Often you want to give Interactive the same context as an application, so it would much quicker to just do `#r "c:\whatever\*.dll"`.

**Comment by rchande** [comment]
@amcasey I was trying to do the same thing as @MgSam (give the REPL the same context as my application)

**Comment by tmat** [comment]
@MgSam You don't need wildcards to do so. If you want to give the same context as Library.dll just ```#r "Library.dll"```. #r will recursively add all dependencies. 

Similarly, if your app is App.exe just ```#r "App.exe"```.

**Comment by MgSam** [comment]
Thanks. That's useful. 

I still see wildcards having a purpose though- if you have a folder full of dlls (from a NuGet package or something) and want to quickly reference them all to explore what's in all the assemblies.

**Comment by tmat** [comment]
Wouldn't adding a reference to the NuGet package address that scenario? Being able to add a reference to a nuget package is on our backlog.

**Comment by MgSam** [comment]
@tmat The "recursively add dependencies" behavior does not seem to be working for me. Is this in the current version or is it a future feature?

**Comment by tmat** [comment]
IN the current version. If it doesn't work as you'd expect please file an issue.

**Comment by KevinH-MS** [comment]
As @tmat said, ```#r``` of the entry point assembly should allow you to achieve the desired effect.

If that's not working or you'd still like to be able to use wildcards, please reopen.
