### ISSUE TITLE
C# Task List doesn't display items

### ISSUE THREAD

**Issue by smimon** [dotnet/roslyn#66872]
**Version Used**: 
Visual Studio 2022 Community 17.4.4
**Steps to Reproduce**:

1. Open a solution containing many todo items
2. Initially, they appear in the task list
3. Open and close visual studio a few times, eventually they will disappear and it is impossible to get them back
4. Repairing the installation causes them to reappear for a short time, then they disappear again
5. Task list is working fine in VS 2019

**Expected Behavior**: Task list should show all todo items

**Actual Behavior**: None are being shown

![image](https://user-images.githubusercontent.com/2358820/218742406-11657cf3-9552-4fcd-9bc6-7aa62cdfb1b7.png)

**Comment by CyrusNajmabadi** [comment]
Does this repro for you in the latest preview builds?

**Comment by smimon** [comment]
I'll try over the next couple of days and report back, cheers

**Comment by smimon** [comment]
Still working as of 3 days of use - better than current build. Will wait another week and report back again.

**Comment by smimon** [comment]
Working many days later, seems to be fixed now.

The preview build is hammering my CPU in the background, which the current stable build doesn't, but that's another issue...

Thanks
