### ISSUE TITLE
Interactive: EE visualization of lists

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6689]
The EE has a nice way of visualizing collections where it will print every member of the collection. For example, in the immediate window:

```
x
Count = 1
    [0]: "foo\r\nbar"
```

However, the visualization in the interactive only appears to call ToString:
```
x
List<string>(1) { "foo\r\nbar" }
```

It would be great to have the same (really nice) visualization the EE uses.

**Comment by amcasey** [comment]
We hope to make this behavior extensible.

**Comment by ManishJayaswal** [comment]
Yes first we want to improve the print method and then make it more extensible so that custome visualizations can be added.

**Comment by amcasey** [comment]
This appears to be expressed by `MemberDisplayFormat.List`.  I'm currently working on making this configurable.

**Comment by amcasey** [comment]
Part of https://github.com/dotnet/roslyn/issues/6887

**Comment by amcasey** [comment]
```
> #r "C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.Scripting.dll"
> using Microsoft.CodeAnalysis.Scripting.Hosting;
. PrintOptions.MemberDisplayFormat = MemberDisplayFormat.SeparateLines
```

**Comment by amcasey** [comment]
@rchande Can you please verify that `PrintOptions.MemberDisplayFormat` works for you?
