### ISSUE TITLE
High CPU usage in VBCSCompiler after update .NET 6 to .NET 7

### ISSUE THREAD

**Issue by Sashuteak** [dotnet/roslyn#66895]
I have ASP NET Core Web App and after I update  .NET 6 to .NET 7 I get High CPU usage in VBCSCompiler when deploy my app in docker

dotnet --info output

```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     ol
 OS Version:  8
 OS Platform: Linux
 RID:         ol.8-x64
 Base Path:   /usr/lib64/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.2 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
```

Here is what i get

![vbcscompiler](https://user-images.githubusercontent.com/22148861/219037915-b7602236-b3fe-4ddd-b5d1-2c7b400a4902.png)

**Comment by jcouv** [comment]
@Sashuteak Based on the information you provided, it's not obvious that this is a C# compiler issue. This may be an ASP.NET or Razor issue. To know, we'd have to figure out why `VBCSCompiler` is taking more resources. It could be that the analyzers have changed, it could be that the inputs it received have changed.
One way to narrow this down is to capture before/after build information with the options documented here: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Troubleshooting-tips.md#investigating-build-time-regressions
