### ISSUE TITLE
Editorconfig UTF-8 BOM setting is ignored when creating a new file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66907]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Editorconfig-UTF-8-BOM-setting-is-ignore/10089891)._

---
[severity:It bothers me. A fix would be nice]
Hello,

My `.editorconfig` file has a setting to use UTF-8 encoding:

```.editorconfig
root = true
[*]
charset = utf-8
```

However, when I create a new `.cs` file, the encoding is UTF8-BOM.

I have searched, and noticed that someone had [the same issue in the past](https://developercommunity.visualstudio.com/t/specifying-charsetutf-8-in-editorconfig-incorrectl/36385), year of 2017. The Visual Studio team says it is fixed. However, for VS 2022, it seems as a regression bug.

Thanks.

---
#### Bruno Saboia on 7/7/2022, 03:04 AM: 

(private comment, text removed)
#### Feedback Bot on 7/7/2022, 06:14 PM: 

(private comment, text removed)
#### Feedback Bot on 7/11/2022, 00:06 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/14/2022, 00:40 AM: 

(private comment, text removed)
#### Bruno Saboia on 7/18/2022, 04:01 AM: 

(private comment, text removed)
#### Bruno Saboia on 7/18/2022, 09:20 AM: 

(private comment, text removed)
#### Bruno Saboia on 7/18/2022, 10:39 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/22/2022, 00:13 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ryzngard** [comment]
@jmarolf assigning to you just because it seems you had more context. If this isn't right let me know.

**Comment by tmat** [comment]
@olegtk I think this would be an editor issue.

**Comment by olegtk** [comment]
This is somewhat related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1316977 that @AmadeusW fixed in 17.5.  
The editor doesn't create new files though, we only open them so we don't have much control over which encoding is used to create files, that's probably item template?

**Comment by tmat** [comment]
Good point, the template should probably check the editorconfig options applicable to the specified file location. Does editor have API that would allow it to do so?

**Comment by Dean-NC** [comment]
ping

**Comment by brunosaboia** [comment]
This is probably an editor issue. Are we still able to send it to the right team?
