### ISSUE TITLE
API proposal for "Using Alias to any Type"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66913]
Championed proposal: https://github.com/dotnet/csharplang/issues/4284
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/using-alias-types.md
Test Plan: https://github.com/dotnet/roslyn/issues/56323

## Proposed API

```diff
using_directive
-  : 'global'? 'using' ('static' | name_equals)? name ';'
+  : 'global'? 'using' ('static' | ('unsafe'? name_equals))? type ';'
  ;
```

```diff
public sealed class UsingDirectiveSyntax
{
+    public SyntaxToken UnsafeToken { get; }
+    public TypeSyntax Type { get; }

-     public NameSyntax Name { get; }

+    /// <summary>Returns <see cref="Type"/> if it is a <see cref="NameSyntax"/>, null otherwise.</summary>
+    public NameSyntax? Name { get; }

+     // All the Update/With methods
}

public sealed class SyntaxFactory
{
+    public static UsingDirectiveSyntax UsingDirective(NameEqualsSyntax? alias, TypeSyntax type);
+    public static UsingDirectiveSyntax  UsingDirective(
+        SyntaxToken globalKeyword, SyntaxToken usingKeyword, SyntaxToken staticKeyword, SyntaxToken unsafeKeyword,
+        NameEqualsSyntax? alias, TypeSyntax type, SyntaxToken semicolonToken);
}
```

**Comment by 333fred** [comment]
### API Review

* Have we thought about what we'd need to do if we end up doing generics in alias names?
    * The part that would change is independent of this.
* Do we want an "expanded using alias" thing to avoid API breaks?
    * Would result in more pain for users than making `Name` nullable, as everywhere that is currently `UsingDirectiveSyntax` is now `BaseUsingDirectiveSyntax`
* Rename `Type` to be `NamespaceOrType` to be more clear
* Approved

**Comment by CyrusNajmabadi** [comment]
Closing out as completed.
