### ISSUE TITLE
Navigation to errors in files generated by a source generator in Roslyn from build output doesn't work in VS

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#66928]
For example, the build output window displays this path

src\Compilers\CSharp\Portable\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs

and, after double clicking it, VS goes to a blank window,

From error window, VS goes to 

Local\Temp\VSGeneratedDocuments\88c0daf0-ef0e-1bba-0412-f9788595e3e2\Syntax.xml.Syntax.Generated.cs

And the actual file that is updated in source control is 

src\Compilers\CSharp\Portable\Generated\CSharpSyntaxGenerator\CSharpSyntaxGenerator.SourceGenerator\Syntax.xml.Syntax.Generated.cs

This is very confusing and feels very broken.

**Comment by Youssef1313** [comment]
Likely same root cause as https://github.com/dotnet/roslyn/issues/53054

**Comment by CyrusNajmabadi** [comment]
We do not own navigation to build errors.  Letting @kayle  know.
