### ISSUE TITLE
Make ExternalAccess.FSharp multi-target so it can be used by VSMac

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/roslyn#66951]
VSMac has been using an old fork of this assembly for several years. We'd like to adopt the upstream version, but it depends on `Microsoft.VisualStudio.LanguageServices` and `Microsoft.CodeAnalysis.EditorFeatures.Wpf`.

If those can be easily removed or refactored out, great. Otherwise, perhaps we can multi-target and offer a version usable on Mac that references `EditorFeatures.Cocoa` (and drops or reimplements whatever depends on `Microsoft.VisualStudio.LanguageServices`).

This may be blocked on https://github.com/dotnet/roslyn/issues/60078, as the most reasonable way to achieve this would be for the existing project to simply add a `net6.0-macos` target and conditionalize a few dependencies.

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in vs4mac.
