### ISSUE TITLE
Show call stack for AD0001 in IDE

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#6696]
Analyzer exceptions in the IDE should be expandable to show a call stack. Today they are not:

![analyzer exception](https://cloud.githubusercontent.com/assets/11762653/11078324/fd9131a8-87b9-11e5-8129-5dda7fdb6a31.png)

This is a possible regression.

**Comment by Vannevelj** [comment]
Is there a difference between AD0001 as a warning (in your case) or as an info message (in my case)? Mine does have a callstack but it's not particularly useful:

![image](https://cloud.githubusercontent.com/assets/2777107/11078591/238341c4-8807-11e5-857a-be5944de1171.png)


Much more interesting would be information about the node that was being analyzed at the time the exception was thrown.

**Comment by lgolding** [comment]
@Vannevelj It's the same diagnostic -- it's been promoted from "info" to "warning" in Update 1.

You're right, information about the node would also be useful. The call stack is also useful, especially to the Roslyn analyzers team.

**Comment by Vannevelj** [comment]
@lgolding Curious, I'm at Update 1 RC myself.But that's good, now it's easy to look past it as an info message. I didn't realize at first that the `IsDefinedInAncestor` is a method I defined myself so my remark on the call stack not being useful was misplaced.

**Comment by lgolding** [comment]
@Vannevelj Glad it helped!

We here just saw a case where the call stack was missing, and we're worried it might be a regression -- that's why we filed the bug.
