### ISSUE TITLE
Parameter Info may not be shown after a named argument

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#66962]
**Version Used**: VS 2022 17.4.5

**Steps to Reproduce**:
Invoke Parameter Info at the marked location.

```csharp
class C
{
    public void M(string? a = null, string? b = null, int c = 0)
    {
        M(c: 0, $$);
    }
}
```

**Expected Behavior**: The Parameter Info tooltip is shown.

**Actual Behavior**: The tooltip is not shown.

* If another named argument is supplied, the tooltip is shown. Example: `M(c: 0, a: "", $$)`
* If either of the `string?` parameters is removed from the method signature, the tooltip is also shown.

**Comment by Xyncgas** [comment]
That's because the compiler thinks maybe it is not there

**Comment by mavasani** [comment]
@sharwell

**Comment by sdelarosbil** [comment]
I could not reproduce this on my end, this might be fixed already

**Comment by jhinder** [comment]
Yes, I can't reproduce this anymore on VS 17.10 P2 as well. Maybe it was fixed by accident in the past year.
