### ISSUE TITLE
DocumentationComment missing newline for member declarations

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/roslyn#66972]
**Version Used**: 

Microsoft.CodeAnalysis.CSharp 4.4.0

**Steps to Reproduce**:

I want to generate class declaration with documetation comment provided, and using the following code:

```C#
var dec = ClassDeclaration("TestClass")
  .WithLeadingTrivia(Trivia(DocumentationComment(XmlSummaryElement(XmlText("Description for class.")))));
Console.WriteLine(dec.NormalizeWhitespace().ToFullString());
```

**Expected Behavior**:

The output I wanted should be 
```C#
///<summary>Description for class.</summary>
class TestClass
{
}
```

**Actual Behavior**:

Actualy the result will be
```C#
///<summary>Description for class.</summary>class TestClass
{
}
```

You may see the result is broken since the class declaration line is commented by the documentation comment mark.

How can I fix this problem? Many thanks!

**Comment by svick** [comment]
I *think* the right way to make your code work is:

```c#
var dec = ClassDeclaration("TestClass")
    .WithLeadingTrivia(Trivia(DocumentationComment(
        XmlSummaryElement(XmlText("Description for class.")),
        XmlText(XmlTextNewLine("\r\n", continueXmlDocumentationComment: false)))));
```

But I would also consider this behavior to be a bug in `NormalizeWhitespace()`.

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/50626

**Comment by sgjsakura** [comment]
> 

Actually your workaround works! many thanks!
