### ISSUE TITLE
error in update to 7.0.200 sdk

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/roslyn#66973]
**Version Used**: 7.0.200

**Steps to Reproduce**:

My app was working fine on 7.0.102. After updating to 7.0.200 I have an error when building. It seems that VS is using version 4.4, while 4.5 should be used in SDK

**Diagnostic Id**:

cs9057

**Expected Behavior**: success build

**Actual Behavior**: fail build
img:
![image](https://user-images.githubusercontent.com/10164223/220331120-c0b6ba18-1e77-45c2-8df5-6fdd787ab83d.png)

**Comment by pinkfloydx33** [comment]
Getting the same issue....

Setting `EnforceCodeStyleInBuild` to `false` resolves it but isn't the desired outcome. Building via `dotnet build` instead of via VS does not produce the warnings.

**Comment by EngRajabi** [comment]
Your suggestion erases the problem and does not solve the problem.

**Comment by pinkfloydx33** [comment]
I am aware of that hence:
> but isn't the desired outcome 

I was providing more context in case it helps triage the issue as it's impacting me as well.

**Comment by RikkiGibson** [comment]
The analyzers come from the .NET SDK while the compiler comes from the VS installation. Updating VS *should* resolve this.

Which VS version is in use when the error is observed?

**Comment by pinkfloydx33** [comment]
Not at my desk to check, but it's fixed in the most recent version of VS (_not_ the version that came out at the same time as the .200 SDK, but rather the patch update that came out a few days later). Note however that it started happening in the version that came out in tandem with the SDK update.

**Comment by EngRajabi** [comment]
The problem was solved by updating to version 17.5.
Why should the release version be finalized with the problem, only after 1 week, the 17.5 version will be finalized and the problem will be solved!
