### ISSUE TITLE
Completions suggest unreachable variables in static local functions

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#66982]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
![devenv_HUTRApYHjC](https://user-images.githubusercontent.com/70431552/220441224-ffaae404-6033-48d7-87c9-efdf51f841c5.png)

**Expected Behavior**:
`args` is not suggested because having it here leads to compiler error

**Actual Behavior**:
`args` and any other variables from outer method's body are suggested

**Comment by CyrusNajmabadi** [comment]
I would be up for taking a fix on this.   :)

**Comment by DoctorKrolic** [comment]
The question here is whether this is and IDE responsibility to filter out unreachable symbols, or compiler APIs shouldn't return them in the first place during lookup
