### ISSUE TITLE
Intellisense shows wrong argument description on overloads if first suggestion is params

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#66984]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-shows-wrong-argument-descri/10160149)._

---
[severity:It bothers me. A fix would be nice]
1. Type `"Hello".Split('s',`
- Intellisense shows the params char[] separators overload
2. Ignore the first suggestion, and look at the other suggestions
- Intellisense is still showing the information for the first argument, even though the cursor is on the second argument

---
#### Feedback Bot on 9/28/2022, 08:55 PM: 

(private comment, text removed)
#### Feedback Bot on 9/29/2022, 03:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Image:

![image](https://user-images.githubusercontent.com/4564579/220463288-f3675cf6-92da-4a18-8242-3d6a753fffd0.png)

**Comment by CyrusNajmabadi** [comment]
@jcouv you broke this :D.  looking to see if it can be trivially fixed.  thsi relates to teh lightweight overload resolution stuff.  effectively, that system comes in and resolves to `params char[]` with a parameter index of 0.   which later overrides the system that says that the parameter index is 1.  hoping i can resolve this to parameter index 1 in the case of params.
