### ISSUE TITLE
IDE0260 recommends switching to invalid pattern

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#67010]
**Version Used**: 
Version 17.6.0 Preview 2.0 [33420.113.main]

**Steps to Reproduce**:
```C#
internal class Program
{
    static void Main() { }

    static B M(object o)
    {
        if ((o as A)?.Value is not B b)
        {
            throw new Exception();
        }

        return b;
    }
}

class A
{
    public B Value;
}

class B
{
}
```

**Diagnostic Id**:
IDE0260

**Expected Behavior**:
No warning.

**Actual Behavior**:
IDE0260 fires and recommends changing:
```C#
        if ((o as A)?.Value is not B b)
```
to:
```C#
        if (o is A { Value: not B b })
```
which is invalid and results in:
```
error CS8780: A variable may not be declared within a 'not' or 'or' pattern.
```

**Comment by CyrusNajmabadi** [comment]
Odd.   The top expression defines a variable within a not pattern.  @RikkiGibson do you know why the top is allowed but the bottom isn't. I keep looking at them and they seem functionally identical. It's unclear to me why the second form isn't ok.

**Comment by RikkiGibson** [comment]
My recollection is that 'is not A a' is a special case and it's generally not allowed in other contexts. Would need to dig up the and/or/not patterns proposal to recall why.
