### ISSUE TITLE
Move PreviewWorkspace diagnostic computation to OOP

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#67014]
> When i open the _OutOfProc one i still see a ton of diagnostics work in process:

That is coming from PreviewWorkspace diagnostic computation always running InProc. See the first bullet point in https://github.com/dotnet/roslyn/issues/66968#issuecomment-1437946680.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/66970#issuecomment-1441203217_

**Comment by mavasani** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
I can look into this tomorrow.

**Comment by CyrusNajmabadi** [comment]
I propose we do https://github.com/dotnet/roslyn/pull/67030 for this instead.  Much simpler and i believe the user experience is fine.  It's also where we're going to be soon anyways with LSP pull diagnostics.  So having a ton of complexity in roslyn to support OOP diagnostics for preview window, when it's not going to work soon anyways just seems like a waste of effort.
