### ISSUE TITLE
Make fixer for `CS0535` smarter when implementing `IEnumerable<T>`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#67023]
Given code like:
```cs
class MyClass : IEnumerable<int>
{
    
}
```
Th fixer for `CS0535` currently doesn't treat this case as some kind of special, so applying it just creates method declarations for non-implemented members:
```cs
using System.Collections;

class MyClass : IEnumerable<int>
{
    public IEnumerator<int> GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }
}
```
However, implementation for non-generic enumerator in 99.99% cases would be then changed by user to
```cs
IEnumerator IEnumerable.GetEnumerator()
{
    return GetEnumerator();
}
```
I think, considering that, fixer for `CS0535` can be made smarter in this specific case and produce code like this in the first place:
```cs
using System.Collections;

class MyClass : IEnumerable<int>
{
    public IEnumerator<int> GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
```

**Comment by mavasani** [comment]
Assigning to @CyrusNajmabadi to review/triage the feature request.

**Comment by CyrusNajmabadi** [comment]
Yes. This would be nice to do.

**Comment by CyrusNajmabadi** [comment]
We woudl take a targeted user pr here.
