### ISSUE TITLE
 Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,31): error CS1002: ; expected'

### ISSUE THREAD

**Issue by ltemimi** [dotnet/roslyn#67038]
Hi

When I call the roslyn to give an expression that has a date time in it I get the error
 Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,31): error CS1002: ; expected'
The error appears to be because of the  space between the date part and the time part of the DateTime

All other variables types such as string , int etc   work fine

Please help

**Comment by jcouv** [comment]
@ltemimi I don't think we'll be able to help based on the limited information you provided so far. What is the expression you're using and how are you calling roslyn?

**Comment by ltemimi** [comment]
Below is the expression when the filter contains a from date TO to date filter I get the exception where fromDate < DateTime.now. So Roslyn cannot handle date time because of the space between the date part and the time part. It thinks there should be a ";" (semi colon). This is a well known issue. Thanks for the help

  try
        {
            var whereFilterFieldsClauseExpression =
                await CSharpScript.EvaluateAsync<Expression<Func<TEntity, bool>>>(whereFilterFieldsClause, options);

            result = result.Where(whereFilterFieldsClauseExpression);
        }
        catch (Exception ex)
        {
            var err = ex.GetBaseException();
            // ignored
        }

**Comment by CyrusNajmabadi** [comment]
> Below is the expression when the filter contains a from date TO to date filter I get the exception where fromDate < DateTime.now

I don't see any of that in the snippet you provided.  Can you give the full piece of code?

**Comment by ltemimi** [comment]
Please find attached my Queryable extension you will if the datatype is date I use Expression trees as Roslyn can't handle date type because of the space between the date part and the time part. Roslyn thinks there should be a ";"

PLEASE RENAME AND REMOVE THE ".zip" as ".cs" is not supported.
thanks for the help
[QueryableExtensions.cs.zip](https://github.com/dotnet/roslyn/files/11252270/QueryableExtensions.cs.zip)

**Comment by CyrusNajmabadi** [comment]
There doesn't seem to be a Main method there that let's me run this.

**Comment by ltemimi** [comment]
The entire solution is too big to send all that is needed and a linq query with a date filter.
