### ISSUE TITLE
`AdditionalTextWithState.GetText` causes LOH allocations

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#67057]
Not proficient with PerfView, but got a trace shows the following:

![image](https://user-images.githubusercontent.com/31348972/221379008-fbe79467-e8d8-4a75-8334-e771b118184d.png)

To my understanding, `AdditionalTextWithState.GetText` is called for "large enough" files that these `string[]` allocations are in LOH

One of the invocations for `GetText` only calls `GetChecksum`. Is a creating the file as `char[]` necessary? Could it be postponed until only requested? The internal hash calculation operates on a stream and reads 4096 bytes at a time. So I assume there is an unnecessary string creation here?

Another question, does calling `GetText` multiple times on the same file allocates every time? If yes, would using a `Lazy<T>` avoids this cost (without hurting correctness)

**Comment by ToddGrun** [comment]
Hi @Youssef1313 -- There have been *significant* performance changes in this area over the last year. Internal traces haven't shown this as an area of excessive allocations, so I'm wondering if you are still able to reproduce similar traces against very recent roslyn build. As for your specific questions, the SourceText.From override that takes in a TextReader does check for large files before reading the textreader contents into a single string to avoid LOH allocations..

**Comment by Youssef1313** [comment]
Thank you @ToddGrun 

I just profiled and indeed I'm no longer seeing those allocations.

**Comment by CyrusNajmabadi** [comment]
Thanks for confirming @Youssef1313 ! :)
