### ISSUE TITLE
Inheritance margin tests break when enabling "Frozen Partial Semantics" in OOP.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#67065]
Oop doesn't actually support 'frozen partial semantics' at all (it's workspace fails out immediately).  I'm enabling it in https://github.com/dotnet/roslyn/pull/67063.  This is working, but ends up breaking Inheritance-Margin (which was asking for frozen-partial, but actually getting non-frozen snapshots).

Working around this is trivial (in OOP, we just disable frozen-partial snapshots for inheritance-margin).  But this should be looked into to figure out why this is not working and how to get it working.

**Comment by CyrusNajmabadi** [comment]
My guess is that frozen-partial-in-oop can end up causing the remote solution-snapshot to be mismatched with the in-proc ones.  For example, if a file is not parsed in OOP (but was in-proc), it won't appear in the oop snapshot.

my guess is that for OOP we need a different concept of frozen-partial.  Specifically, while it can avoid running generators/skeletons, it should not dump any files from teh snapshot.  It should keep all of them in.

@jasonmalinowski do you have any thoughts/ideas here?  It might be good for @Cosifne to investigate this and see what about OOP-frozen-partial is causing the problem.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi What was the break? My general mental model would either:

1. Doing the freeze in-proc and then that solution gets sent over the wire. The in proc and out of proc are in sync.
2. We're calling freeze out-of-proc _only_. and we never really looked at any in-proc state in the first place, so nothing can be out of sync.

But I'm imagining something else is going on here?

**Comment by CyrusNajmabadi** [comment]
So several inheritance margin tests broke (specifically the ones that test both in-proc and out-of-proc), because OOP now reported no results for things that inproc does report results for.

**Comment by Cosifne** [comment]
Yep, both sides are using frozen documents. 

> Doing the freeze in-proc and then that solution gets sent over the wire. The in proc and out of proc are in sync.

> We're calling freeze out-of-proc only. and we never really looked at any in-proc state in the first place, so nothing can be out of sync.
I believe inheritance margin send the forzen document to OOP, (that should also send the solution?) so it should be in sync. Need to debug and see why it failed

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
