### ISSUE TITLE
Aggregate telemetry for understanding analyzers/fixer perf to report on slow analyzers

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#67074]
- We should collect data in aggregate that help us chart out where all analyzers/fixers/refactorings land perfwise
- vs/ide/vbcs/diagnostics/analyzerperformanceinfo telemetry event needs to be aggregated and reenabled
- We should correlate the analyzers that impact scenarios like Lightbulb directly to prioritize fixes in those analyzers/fixers
- Finally dashboard and reporting to track and protect our gains going forward

**Comment by CyrusNajmabadi** [comment]
Small tweak:  We want to collect information on the following:

1. How long each lightbulb priority group is taking.  A group doesn't show until it is done, so we need to know the aggregate time for the group.
2. How long individual analzyers/refactoring providers are taking to provide light bulb items.  This will help us establish which providers are causing a group to be slow to appear.
3. How long individual actions take to apply.  This doesn't impact time to bring up lightbulb, but it does impact time to get to the preview, and time the user has to wait once they do invoke an action.

**Comment by CyrusNajmabadi** [comment]
Once we have info for 1/2/3 above, we can then drive perf improvements for particular analyzers/refactorings/actions.  If we aren't sure what's causing slowness (and we can't repro locally), we can add more targetted aggregate tracking on a per analyzer/refactoring and per-action basis, and then let the telemetry for those guide us.

**Comment by mavasani** [comment]
@ToddGrun is this complete now? Any more planned work for this? If not, we should probably close this out.

**Comment by ToddGrun** [comment]
@mavasani  -- I need to get this code working in vscode, that's my main goal this week.

**Comment by CyrusNajmabadi** [comment]
@ToddGrun do we still need this?  Can we close out otherwise?

**Comment by ToddGrun** [comment]
This has been done for a while, closing this out. We have telemetry for analyzers and dashboards created.
