### ISSUE TITLE
Completions should not show `Obsolete` items with `error` set to `true`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#67089]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
var c = new MyClass();
c.$$

class MyClass
{
    [Obsolete("Do not use this", error: true)]
    public void M()
    {

    }
}
```
Invoke completions at `$$`

**Expected Behavior**:
`M` is not shown, because using it leads to compiler error

**Actual Behavior**:
`M` is in the list and is even promoted by IntelliCode:
![devenv_6Hbff4pn5C](https://user-images.githubusercontent.com/70431552/221824947-c0d2b7bf-e560-4726-910c-fa1030bc0488.png)

**Additional context:**
When fixing this issue need to verify that such items are shown in `nameof` context, since code like this is perfectly valid:
```cs
var c = new MyClass();
var name = nameof(c.M); // usage of `M` here

class MyClass
{
    [Obsolete("Do not use this", error: true)]
    public void M()
    {

    }
}
```

**Comment by Youssef1313** [comment]
If this change is accepted, care should be taken to not regress other scenarios. For example:

```csharp
using System;

var c = new MyClass();
c.M(); // perfectly fine here.

class MyClass
{
    [Obsolete(null, error: true)]
    public void M()
    {

    }
}
```

Yes, it is a bug that is kept for backward compatibility that when the message is null we always produce a warning not an error.

Are there any other cases? I don't know.

**Comment by CyrusNajmabadi** [comment]
I'm generally opposed to this. I think it's fine to offer. If someone doesn't want the item in completion, they can editorbrowsable it. 

I would also be fine with updating the UI to show the item in a special way (like a strike through).

**Comment by DoctorKrolic** [comment]
I was thinking for a strikethrou for non-error obsolete items. But since completing these ones leads to compiler error, they become just unnecessary noise in the list

**Comment by CyrusNajmabadi** [comment]
You can use obsolete things from other obsolete things. We've definitely done this. Hiding means that becomes more painful. 

> they become just unnecessary noise in the list

I disagree. If someone doesn't want it in the list, that have that capability already with editorbrowsable.  We should not conflate things here.

**Comment by DoctorKrolic** [comment]
I am not getting it. Of course I agree, that the list should show non-error cases, but commiting an error one means you will 100% have to clear it a bit later because of an error. How having it in the list can be helpful then?

**Comment by CyrusNajmabadi** [comment]
This is legal:

![image](https://user-images.githubusercontent.com/4564579/221982156-1e3ec0d0-85cb-4981-86bd-a098c047a352.png)

It's a core part of the design of obsolete that it can be used/suppressed.

**Comment by CyrusNajmabadi** [comment]
Keeping around as by design.
