### ISSUE TITLE
Primary constructor parameter assignment in initializers uses wrong nullable warning

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#67099]
**Version Used**:  features/PrimaryConstructors

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAUEEsC2UECeAwgPYB2yMCcAxjCQsgDQAmIA1AD4ACATAIwBYAFABiMnAA2kqMEkQABBDKz5I7gGYFfBUQAU3fgAYFyAJQKA3iIW3tWw0YD8CgGJYIklvwUBeBXrIfgoS0mYA3AoA9FG6AMoAHABsRiaoIeSoyFCQMAQKAOqoAO74ZFhkAOY2dpraxm4eXrzhNbZt9rp6FiAKMAAWWMh6AEQjZh3WwnYzjZ4svMGhkpEx8cm8AKwK6dm5+QBy5IUlZRXV03YAviJXQA=

We report a non-safety W-warning for the assignment to the primary ctor parameter. This warning code is intended for assignments that are considered "stylistic", and it's expected that some users will decide to suppress them globally to avoid updating the types of locals. A separate error code should be used for nullable assignments can be seen outside the current method body (such as CS8625), as these are actual safety issues and not just stylistic choices.

**Comment by 333fred** [comment]
This is broken for both the new primary constructors feature, but also for existing record scenarios as well.

**Comment by AlekseyTs** [comment]
> also for existing record scenarios as well.

This aspect remains unchanged. It should be triaged separately and decision whether we would like to change behavior for records as well.

@333fred Please add a repro for records, and please do not make it just a SharpLab link. Issues shjould be self-contained.
