### ISSUE TITLE
System.Text.RegularExpressions.Generator stops working after file rename

### ISSUE THREAD

**Issue by kugushev** [dotnet/roslyn#67125]
**Version Used**: 4.5.0-6.23123.11+271ccd71554f7d28d2f90551aafd0bdeb5d327aa

**Steps to Reproduce**:

1. Open the following repo in Visual Studio (or Rider, doesn't matter): https://github.com/AnastasiiaPosulikhina/RoslynAnalyzersDogfooding
2. Open `Support RegexGenerator.cs`
3. Rename it, e.g. `Support RegexGenerator123.cs`
4. Wait until MatchIfValid() method becomes highlighted with red squiggles
5. Rename it back to `Support RegexGenerator.cs`

**Expected Behavior**:

Appropriate partial method should be generated for `private static partial Regex MatchIfValidUrl();` 

**Actual Behavior**:

Partial method MatchIfValidUrl() must have an implementation part because it has accessibility modifiers

**Root Cause**:
In Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel the ArgumentException throws at Line 2260

**Comment by BrennanRPope** [comment]
Same problem for me. Both Rider ad VS suggest this change, so it is absolutely an issue with Roslyn or the cached generated source. Either way, I think that IDE's need to stop recommending this change until this is sorted out. While it is a technically superior concept, right now it's probably wasting millions of hours of developers' time trying to figure out what is going wrong.

**Comment by CyrusNajmabadi** [comment]
I can't repro this, and we haven't heard about this issue in over a year.  Note: with the current SG system, we will use cached results until the next build.
