### ISSUE TITLE
Using the discard operator can not be compiled

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#67121]
![image](https://user-images.githubusercontent.com/7604648/222105564-360467a8-0e87-40d0-a8d5-d9013b2ce2fb.png)

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRgJYBsKpgTwAcUAaAExAGoAfAAQAYACWgRgDoAZDAOwEcBuALAAoEbQDMzAEyMAwowDeIxiuaTaAFkYBZABQBKRctUmAblASMyGAMaMAvI24QA7sxYa2AEVswMAe24LfAAeHhgSRmB/fywAPgMhYRMzC0ZCBH8yOBsYZAcnVwBtAF0FRhZIqUjxAF8klNVzS2Q4YGQbBAxgKGAcAAVM7Nz8xwysnLy2AHUACwgkXQAPBzirWzYAFQR8AHEIGAA1KCw4CGXI/zgYRmbGAH1DADInh/0t/wBBBAQofETjI1aAB2Ritdqdbq9AZDSbIBqqWoiWpAA==

```c#
using System.Collections.Generic;
using System.Linq;

public class C {
    public void M() {
        var dic = new Dictionary<int, bool>();
        var products = new[]{ 1, 2, 3};
        var subscribableProducts = products.Where(x => dic.TryGetValue(x, out var _) && _).ToArray();
        return subscribableProducts;
    }
}
```

**Expected Behavior**:

Able to compile

**Actual Behavior**:

Error reported

**Comment by SunnieShine** [comment]
It seems that it is not a bug. I find this:

https://github.com/dotnet/roslyn/blob/main/docs/features/discards.md

This document says:

> In C# 7.0, they can appear in the following contexts:
>
> * out variable declarations, such as `bool found = TryGetValue(out var _)` or `bool found = TryGetValue(out _)`

which means `out var _` is a real discard, so `_` after `&&` is a real variable name, which cannot be found. Therefore, compiler says it is a wrong use.

In my knowledge of C# syntax, `out var _` is a new-styled declaration of a variable, different with `var variable = expression;`. The reason why other variable declarations like `var _ = expression;` will be treated as a normal variable is that a variable with an only underscore can be used in old C# version, which is allowed and corrected variable declaration. Here it may cause a breaking change if we change the semantic of a variable declaration `var _ = expression;`; therefore, we have to omit its type name (or `var` keyword) to call a method whose return value should be ignored: `_ = Method();`.

However, `out var _` is a newer variable declaration, which is born in C# 7 (Inlined `out` variable declaration). This variable declaration syntax may not cause a breaking change. Therefore, `out var _` is a correct discard usage.

**Comment by WeihanLi** [comment]
@SunnieShine thanks very much
