### ISSUE TITLE
VB incorrectly allows access to a protected constructor from a shared member of a derived class

### ISSUE THREAD

**Issue by cpowers534at** [dotnet/roslyn#67130]
**Version Used**:

Tested in Visual Studio 2019

**Steps to Reproduce**:

The following code will compile without error, but is contrary to the specification for Protected:

```
    Public Class A
        Protected Sub New()

        End Sub
    End Class

    Public Class B
        Inherits A

        Public Shared Function MakeA() As A
            Return New A()
        End Function
    End Class
```

The language specification [states](https://github.com/dotnet/vblang/blob/main/spec/general-concepts.md#accessibility), "A Protected member is accessible to a derived class, provided that either the member is not an instance member, or the access takes place through an instance of the derived class." In this case, the member is an instance member (a non-shared constructor), and the access is not taking place through an instance of the derived class (rather it's through a shared member of class B).

**Diagnostic Id**:

N/A

**Expected Behavior**:

Compiler error due to no access to the protected constructor from MakeA.  For a non-constructor member, the compiler issues error BC30390 "'A.Protected Sub Foo()' is not accessible in this context because it is 'Protected'."

**Actual Behavior**:

Compiles without error.

**Comment by jcouv** [comment]
Thanks for the compact example and reference to the language specification. That does seem a deviation from the spec.
I verified this behavior dates all the way back to the native VB compiler, so changing this would be a significant break at this point. I'll close this as Won't Fix.
Tagging @AlekseyTs @jaredpar @KathleenDollard as FYI
