### ISSUE TITLE
VB For Each issue

### ISSUE THREAD

**Issue by CoolCoderSuper** [dotnet/roslyn#67134]
1. Loop through collection
2. Declare variable inside loop
3. Change variable in loop and next iteration the varaible is not reset

Code: 
```vb
Imports System
Imports System.Collections.Generic
Public Module Program
    Public Sub Main()
        Dim l As New List(Of String)
        For Each str In l
            Dim intVal As Integer
            intVal += Integer.Parse(str)
        Next
    End Sub
End Module
```
Result from SharpLab:
```c#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue | DebuggableAttribute.DebuggingModes.DisableOptimizations)]
[assembly: AssemblyVersion("0.0.0.0")]

[StandardModule]
public sealed class Program
{
    public static void Main()
    {
        List<string> list = new List<string>();
        List<string>.Enumerator enumerator = default(List<string>.Enumerator);
        try
        {
            enumerator = list.GetEnumerator();
            int num = default(int);
            while (enumerator.MoveNext())
            {
                string current = enumerator.Current;
                num = checked(num + int.Parse(current));
            }
        }
        finally
        {
            ((IDisposable)enumerator).Dispose();
        }
    }
}
```
If you initalize the varaible at declaration it works fine and assigns `intVal` to zero before it runs the loop.
But shouldn't the variable be declared or at least reinitialized every time?

**Comment by jcouv** [comment]
Although this is surprising, there's a good chance this is by-design. 
The native VB compiler has the same behavior (tested with `C:\Windows\Microsoft.NET\Framework\v4.0.30319\vbc.exe`, the local is not initialized, only read and incremented).
The spec was not super clear either way, but I'll try to confirm from that angle too.

**Comment by CoolCoderSuper** [comment]
What scenario would this be helpful?

**Comment by jaredpar** [comment]
> What scenario would the current way be helpful?

In this case it's not about whether this is helpful or not but what is the expected behavior of the language. VB has a number of behaviors, including this one, that stretch back 20+ years. Helpful or not customers depend on these behaviors and changing them can, and **will**, cause program behavior to change as a result.

**Comment by CoolCoderSuper** [comment]
Yeah, that makes sense.
