### ISSUE TITLE
Add partial classes view in margin menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-partial-classes-view-in-margin-menu/10283393)._

---
Adding partial classes view in margin menu would help finding corresponding classes like .razor components for code-behind .razor.cs files:

![image.png](https://aka.ms/dc/image?name=B43fd8a6b3fbd49dc87372410ef6213ac638122221354216922_20230217-091534-image.png&tid=43fd8a6b3fbd49dc87372410ef6213ac638122221354216922)

---
#### Feedback Bot on 2/20/2023, 00:58 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as this would be handled by razor if htey wanted this.
