### ISSUE TITLE
Find refs within a metadata as source view doesn't search it

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6716]
``` C#
namespace ClassLibrary1
{
    public class Class1 : Object
    {
    }
}
```

Alt-F12 (peek) on Object. You should be shown a MAS view of System.Object. Navigate to any instance of Object in the peek. Observe that highlight refs navigates within occurrences of Object within the peek. Find Refs on an occurrence of Object within the peek

Expected:
Find refs results from inside the MAS view

Actual:
Find refs searches only the solution

**Comment by jasonmalinowski** [comment]
Do you expect this? The results from FAR for the MAS workspace would be incomplete since it won't include all types from metadata, just the types that you happen to have generated. We _could_ fix that, although I'm not sure I'd actually be happier as a user if we did.

**Comment by Pilchie** [comment]
@rchande, @dpoeschl, and I talked about this one a bit. What @rchande expected was to be able to see where else in a given metadata as source file, and argument type was used in order to understand the API.  Something we never considered, but a valid use case.

**Comment by Pilchie** [comment]
It's not clear exactly what the user model for this would be - perhaps another node in the Find Symbols Results window with metadata as source specific matches?  Would it include *all* metadata as source files, or only the current ones, etc?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this, as high cost/complexity of the solution.
