### ISSUE TITLE
Incremental generator not being run incrementally for selected primitive value

### ISSUE THREAD

**Issue by kzu** [dotnet/roslyn#67160]
**Version Used**: 
Microsoft Visual Studio Community 2022
Version 17.5.0

**Steps to Reproduce**:

[NonIncremtalGenerator.zip](https://github.com/dotnet/roslyn/files/10875045/NonIncremtalGenerator.zip)

Given the following generator:

```csharp

[Generator]
public class TestGenerator : IIncrementalGenerator
{
    static int counter;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.AnalyzerConfigOptionsProvider
                .Select((c, x) =>
                    c.GlobalOptions.TryGetValue("build_property.MSBuildProjectFullPath", out var projectPath) ?
                    File.GetLastWriteTimeUtc(projectPath).Ticks :
                    DateTime.UtcNow.Ticks),
            (ctx, src) =>
            {
                // Open the generated Foo.cs and see it regenereate on every build, 
                // even if the datetime value (in the Select above) remains the same.
                ctx.AddSource("Foo.cs", $"// Counter: {Interlocked.Increment(ref counter)}, {src}");
            });
    }
}
```

and the following item group in the consuming project:

```xml
  <ItemGroup>
    <CompilerVisibleProperty Include="MSBuildProjectFullPath" />
  </ItemGroup>
```

After reading the [caching](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#authoring-a-cache-friendly-generator) section, and given that the selected value for the generation is a primitive value (the ticks since the project file was last changed), I was expecting the generator to only be run whenever the project file was changed (that's the ticks retrieved from the property value).

**Expected Behavior**:

Should run the generator only when the project file is changed

**Actual Behavior**:

Runs on every build, whenever a source file is changed in the consuming project.

The attached solution contains the generator project and consuming test project. Build the solution, open the Sample.cs and build the solution. Now open the generated file at `Tests\obj\Debug\net6.0\generated\Generator\TestGenerator\Foo.cs` make changes to the Sample.cs file and build. After every build, you will see the counter incrementing, but the value (ticks) remaining constant, which is unexpected unless I misunderstood something.

![nonincremental](https://user-images.githubusercontent.com/169707/222703375-e8e115c9-6404-4dd4-9117-ae3619c6f655.gif)

**Comment by kzu** [comment]
Further testing: if the "selects" are like "check-points" in the execution as noted in the docs, the following Thread.Sleep (simulating an expensive transformation) shouldn't be run more than once:

```csharp
        context.RegisterSourceOutput(
            context.AnalyzerConfigOptionsProvider
                .Select((c, x) =>
                    c.GlobalOptions.TryGetValue("build_property.MSBuildProjectFullPath", out var projectPath) ?
                    File.GetLastWriteTimeUtc(projectPath).Ticks :
                    DateTime.UtcNow.Ticks)
                .Select((x, c) =>
                {
                    Thread.Sleep(5000);
                    return x;
                }),
            (ctx, src) =>
            {
                // Open the generated Foo.cs and see it regenereate on every build, 
                // even if the datetime value (in the Select above) remains the same.
                ctx.AddSource("Foo.cs", $"// Counter: {Interlocked.Increment(ref counter)}, {src}");
            });
```

Note that the input to that select is constant (the .csproj didn't change between builds).

![sleepy](https://user-images.githubusercontent.com/169707/222705894-77b3792c-2718-41ce-9e8f-670a6ddc3118.gif)

**Comment by CyrusNajmabadi** [comment]
Incremental generators are only about speeding up execution in a host that supports incremental generation (like the vs ide). The batch (command line) compiler will always run the pipeline stages fully.

**Comment by kzu** [comment]
My videos (attached) and usage is within VS. Not seeing the incrementally kick in :(

**Comment by sharwell** [comment]
> After every build, you will see the counter incrementing

Builds run through the compiler, which is never going to be incremental unless you've overridden its internal feature flag to turn on incrementality there.

Even when incrementality is enabled, it's _allowed_ to skip steps but not required to.

**Comment by CyrusNajmabadi** [comment]
> My videos (attached) and usage is within VS. 

Your builds are invoking the command line compiler. There is no incremental builds within the compiler there (and there is no current plans to add support for that). This would require the compiler to persist in-memory data somehow, which is currently out of scope fit is for this space. 

Incremental generators are for and IDE host for building the in-memory information that drives things like completion-lists, find-references, etc.  I.e. the features we want to be able to work immediately and with high accuracy after an edit has been made.

**Comment by kzu** [comment]
I see. Closing based on the above (being by-design -for now?) and the Twitter exchange at https://twitter.com/jaredpar/status/1631727829305163776?s=20. 

Thanks for the amazingly quick reply. You guys rock.
