### ISSUE TITLE
[Suggestion] Indent Options - Make Open and Close Braces Options Independent (esp. C#)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67170]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggestion-Indent-Options---Make-Open-/10275616)._

---
Options>TextEditor>C#>Formatting>Indentation>
Change from: [ck]=> Indent open and close braces.
To:
[ck]=> Indent open braces.
[ck]=> Indent close braces.

This would allow formatting and Code Cleanup to support the scenarios below.
These formats are especially useful for code automation and parsing.  

```
class Foo
{
        }

bool Test (   )
{
        }

bool Test
(    )
{
        }
```

Currently you can do:
```
item { }

item { 
}

item { 
    }

item
{ 
}

item
    { 
    }
```
The last form is (visually) better as
```
item
{ 
    }
```

---
#### Feedback Bot on 2/9/2023, 08:51 PM: 

(private comment, text removed)

**Comment by sharwell** [comment]
Marking as **Blocked** on #31691

This feature won't be directly implemented, but may optionally be used as a validation case for generality of a new extensible formatter.

**Comment by CyrusNajmabadi** [comment]
We are unlike to do this.
