### ISSUE TITLE
Language Injection : Syntax highlighting and Intellisense support for languages or formats contained in string.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67182]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Language-Injection-:-Syntax-highlighting/10294477)._

---
Hello. I had to use the JetBrains Rider at a company for a short time. I like the feature called language injections and would love to have it in visual studio.

It provides syntax highlighting and intellisense when using different languages or formats such as sql, html, js or json in C#. In this way, it is very comfortable and enjoyable to convert string expressions to other formats. I think it will be very nice, especially with the raw array that comes with C# 11.

![image.png](https://aka.ms/dc/image?name=B0b378a71392c4246a21b8f34d14c0428638132140653052651_image.png&tid=0b378a71392c4246a21b8f34d14c0428638132140653052651)

I apologize if this feature has been mentioned before or if mentioning another company is prohibited.

---
#### Feedback Bot on 2/28/2023, 10:17 PM: 

(private comment, text removed)
#### Feedback Bot on 3/3/2023, 09:47 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
We are not plannign on doing this.
