### ISSUE TITLE
Anonymous objects are clickable inside quick info, but lead to nowehre

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#67185]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
var a = new { };
```
Hover over `var` and try to click on `'a`, that represents anonymous object

**Expected Behavior**:
Anonymous objects are either clickable & their target leads somewhere or they are not clickable at all

**Actual Behavior**:
They are clickable and lead to nowhere:
![bug](https://user-images.githubusercontent.com/70431552/222917119-34f48027-ce75-45e4-926e-54c213372ec6.gif)

**Comment by mavasani** [comment]
@sharwell Can you please confirm the preferred behavior for this scenario? We can mark this as help wanted once we have a recommended design.
