### ISSUE TITLE
VS 2022 spell checker is considering c# keywords as spelling error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67181]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-spell-checker-is-considering-c-/10295936)._

---
[severity:It bothers me. A fix would be nice]
C# keywords like "readonly" are being reported as Spelling error.  These should be excluded by default.

---
#### Feedback Bot on 3/1/2023, 10:14 PM: 

(private comment, text removed)
#### Feedback Bot on 3/2/2023, 01:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this.  Would need an example of where this is happening to fix.  Note: the VS spell checking system allows for users to say which words they want to ignore.  So if a user does write an invalid word in something like a comment or string, they can just tell the spellchecker it's legal and it will not prompt them again.
