### ISSUE TITLE
Exception in 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer'

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#672]
1.Build Roslyn.sln and start a new VS instance in RoslynDev hive
2.Create a C#/VB class library project 

Got:
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception with message 'Object reference not set to an instance of an object.'.			1

**Comment by tmeschter** [comment]
I see the problem. Whoops.

**Comment by tmeschter** [comment]
Assigning back to @mavasani for verification.

**Comment by mavasani** [comment]
Yep, already noticed it is fixed with latest sources.
