### ISSUE TITLE
Method => Property: Somehow convey that the set method's semantics are changing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6720]
Start with C#:
```C#
class C
{
    public virtual int GetX() { return 1; }
    void SetX(int x) { }
}
```
Invoke Convert Method to Property on ```GetX``` and view the preview window for "Replace 'GetX' and 'SetX' with property".

It would be nice if we could somehow indicate in the preview (whether via text or conflict span or...) that the semantics of SetFoo have changed from non-virtual to virtual.

**Comment by DustinCampbell** [comment]
This feels a bit off in the weeds. @Pilchie and I are opting to won't fix.
