### ISSUE TITLE
Provide access to ApplicationDefinition project item from Microsoft.CodeAnalysis.Project

### ISSUE THREAD

**Issue by etvorun** [dotnet/roslyn#67215]
## Background and Motivation

XAML intellisense is moving to Roslyn LSP layer. To provide completions for XAML resource references -  e.g. `Background="{StaticResource ...}"` - it needs to know application resources file, which is usually [project]\App.xaml. However platforms like WPF require it to be ApplicationDefinition, e.g.
MyApp.csproj
`<ApplicationDefinition Include="MyApp.xaml"/>` 

## Proposed API
To be decided by Roslyn team. Callers should be able to get either path or file name + folders (in a rare case where it is a linked item). It should be available from Project. Either directly, or via helper method.

**Comment by CyrusNajmabadi** [comment]
This needs to go through API review.  As there's been no discussion on this in over a year, i'm assuming it's not needed anymore.  If it is needed, we should attach it to well known deliverables for both teams with a specific release/sprint date.
