### ISSUE TITLE
Expose project ID on compilations in ServiceHub.RoslynCodeAnalysisService.exe 

### ISSUE THREAD

**Issue by etvorun** [dotnet/roslyn#67218]
## Background and Motivation

As part of moving XAML intellisense into Roslyn LSP layer we need ability to run XAML code analyzers in ServiceHub.RoslynCodeAnalysisService.exe. XAML intellisense needs to create/cache/update heavy per-project constructs. However there are no Projects or Workspaces RoslynCodeAnalysisService. Only Compilation. Being able to get access project ID from Compilation will save lots of work for XAML team.

More details. XAML intellisense creates XAML type system which skews .NET types. For example, 3 .NET entities:
```
public class Grid
{
    public static readonly DependencyProperty RowProperty = ...;
    public static int GetRow(UIElement element) { ... }
    public static void SetRow(UIElement element, int value) { ... }
```
become single Grid.Row property in XAML type system. Unfortunate design of XAML type system is that one can navigate from type back to project: [IType.PlatformMetadata](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS?path=/src/Xaml/Shared/Source/Markup/Metadata/IType.cs&version=GBmain&line=12&lineEnd=12&lineStartColumn=9&lineEndColumn=52&lineStyle=plain&_a=contents) => [IPlatformMetadata.DefaultProjectMetadata](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS?path=/src/Xaml/Shared/Source/Markup/Metadata/IPlatformMetadata.cs&version=GBmain&line=115&lineEnd=115&lineStartColumn=9&lineEndColumn=57&lineStyle=plain&_a=contents) => [IProjectMedatata](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS?path=%2Fsrc%2FXaml%2FShared%2FSource%2FMarkup%2FMetadata%2FIProjectMetadata.cs&_a=contents&version=GBmain). Breaking this 15+ years old design will be significant effort for XAML team and will affect XAML intellisense, XAML hot reload and XAML designer.

## Proposed API
To be determined by Roslyn team. Given Compilation which represents Project in RoslynCodeAnalysisService.exe, there should be a way to get GUID or other form of project identification.

**Comment by etvorun** [comment]
@jasonmalinowski (cc @mgoertz-msft) this is a follow up on our discussion about moving XAML intellisense into Roslyn LSP layer.

**Comment by jasonmalinowski** [comment]
I'm confused by the request here, specifically this bit:

> However there are no Projects or Workspaces RoslynCodeAnalysisService.

We absolutely have Project/Solution snapshots just like we have in-proc; this seems like you might be conflating that with us not giving analyzers project info generally, simply because analyzers run in other places we indeed don't have project info.

**Comment by etvorun** [comment]
@jasonmalinowski maybe needed API already exists and I need to learn about it:). In our DiagnosticAnalyzer.Initialize we call context.RegisterAdditionalFileAction(SomeXamlAction). When our SomeXamlAction is called we get AdditionalFileAnalysisContext which gives us Compilation. We need to find project ID for that compilation.

**Comment by CyrusNajmabadi** [comment]
> When our SomeXamlAction is called we get AdditionalFileAnalysisContext which gives us Compilation. We need to find project ID for that compilation.

There literally may be no project-id here.  At the analyzer level, it's not a concept (consider the command line, where projects do not exist, and hte compiler is just called with data from an msbuild task).  Note that this is how things work for all of our roslyn-analyzres as well.  We have no backdoor to get at this information for us either.  Instead, the anlayzer just runs (Again, in the context of just compilation data) and then reports diagnostics.  Later, the diagnostics can be processed (for example, to give lightbulb actions), and that processing is done in the context of solutions/projects/documents.

**Comment by tmat** [comment]
> XAML intellisense needs to create/cache/update heavy per-project constructs.

As we discussed at the last meeting XAML will be able implement LSP handlers that receive solution snapshot from Roslyn. At this level you have access to the projects, so completion etc. would be able to use that.

As @CyrusNajmabadi pointed out on analyzer level there is no access to projects.

What features are you implementing in the analyzer? Should those be in the LSP handlers instead?

**Comment by jasonmalinowski** [comment]
@etvorun I think at this point this ticket doesn't really make sense given the current directions we're going, should we just close it?

**Comment by CyrusNajmabadi** [comment]
Closing out given lack of any conversation.
