### ISSUE TITLE
Preview Changes takes too long to classify when checkboxes

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6722]
The entire view goes white for half a second when the window is large. Only some things turn white when the window is small.

![previewchangesclassification](https://cloud.githubusercontent.com/assets/235241/11105158/0715eb92-8882-11e5-8e13-109ecb8b003f.gif)

**Comment by CyrusNajmabadi** [comment]
Haven't heard about thsi from anyone else.  Need info if this is actually worth investing into.
