### ISSUE TITLE
`Simplifier.AddImportsAnnotation` does not work with Attributes

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#67237]
**Version Used**: 
Microsoft.CodeAnalysis.CSharp.Workspaces=4.5.0
Visual Studio=17.5.0
**Steps to Reproduce**:

1. use "Analyzer and CodeFix" Template to make an Analyzer to report any Property, and a CodeFix like this:
```cs
private async Task<Document> AddAttribute(Document document, PropertyDeclarationSyntax prop, CancellationToken cancellationToken)
{
  DocumentEditor editor = await DocumentEditor.CreateAsync(document, cancellationToken);
  SyntaxGenerator gen = editor.Generator;

  SyntaxNode attr = gen.Attribute(
    gen.QualifiedName(gen.DottedName("System.ComponentModel")
    .WithAdditionalAnnotations(Simplifier.AddImportsAnnotation)
    , gen.IdentifierName("BrowsableAttribute"))
      //.WithAdditionalAnnotations(Simplifier.AddImportsAnnotation)
      ,
    new[] { gen.LiteralExpression(false) }
    );
  editor.AddAttribute(prop, attr);
  return editor.GetChangedDocument();
}
```
2. try to invoke CodeFix

**Diagnostic Id**:

**Expected Behavior**:
- added `using System.ComponentModel;` and `[Browsable(false)]`

**Actual Behavior**:
- added `[System.ComponentModel.Browsable(false)]`

** Notes**:
- Neither Location for `WithAdditionalAnnotations`works.
- also while trying more, the my Example-Analyzer (created by the template) broke, and now VS doesn't even register the CodeFix anymore

**Comment by CyrusNajmabadi** [comment]
Does this pattern work elsewhere for you?

**Comment by Youssef1313** [comment]
@LukasGelke `AddImportsAnnotation` alone does nothing. It works only when there is a proper symbol annotation. A symbol annotation is just a `SyntaxAnnotation` whose kind is the magic string "SymbolId" and the data is the fully qualified symbol name.

For the commit you are referencing, `AddImportsAnnotation` is added to the result of `GenerateTypeSyntax` which internally adds the proper symbol annotations.

**Comment by LukasGelke** [comment]
ohhh. So one has to provide the correct type (via SymbolAnnotation) manually. ok. 
Seems simple enough to "copy" the `SymbolAnnotation`.
So this is the "intended" way? Is this preferred, over just (correctly) adding an `UsingDirectiveSyntax` to the root, although one needs the `Compilation` and resolved `Symbol`?
Our CodeFix is specifically made for our Company-Libraries, where the actual class wee need resides. So the type should always be available in either case.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
