### ISSUE TITLE
StructLayout doesn't work for record structs with DateTime fields

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67242]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StructLayout-doesnt-work-for-record-str/10281245)._

---
[severity:It bothers me. A fix would be nice]
I have a 8 byte packed struct layed out as 2-2-4-8 byte fields. In ordrer to use it in unmanaged interop, I've declared it as a readonly record struct with StructLayout(Sequential) attribute applied. I expect the compiler in generated struct to preserve fields order the way I described them in record. It does so when the last 8-byte field is typed as `long`. However when I change it to `DateTime`, it lays out fields as 4-2-2-8 bytes instead.

```
using System.Runtime.InteropServices;

unsafe
{
	Wrong     wrong = new(0x0102, 0x1122, 0xAABBCCDD, new(0x1F2E3D4C5B6A7988));
	Correct correct = new(0x0102, 0x1122, 0xAABBCCDD,     0x1F2E3D4C5B6A7988);
	byte*   wrongPtr = (byte*)&wrong;
	byte* correctPtr = (byte*)&correct;
    Console.WriteLine($"Correct: {correctPtr[0]:X}=2 {correctPtr[2]:X}=22 {correctPtr[4]:X}=DD {correctPtr[8]:X}=88");
    Console.WriteLine($"Wrong  : {  wrongPtr[0]:X}=2 {  wrongPtr[2]:X}=22 {  wrongPtr[4]:X}=DD {  wrongPtr[8]:X}=88");
    Console.WriteLine();
}

[StructLayout(LayoutKind.Sequential)]
readonly record struct Wrong  (ushort Type, ushort U2, uint U4, DateTime I8);
readonly record struct Correct(ushort Type, ushort U2, uint U4,     long I8);
```
Produces
```
Correct: 2=2 22=22 DD=DD 88=88
Wrong  : DD=2 BB=22 2=DD 88=88
```

**Comment by jcouv** [comment]
So we coincidentally discussed this last week and I'd filed an issue for primary constructors and record structs:
https://github.com/dotnet/roslyn/issues/67162

Closing as duplicate
