### ISSUE TITLE
[Lightbulb Perf] Expose an optional FilterSpan public API on SyntaxTreeAnalysisContext and SemanticModelAnalysisContext

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#67257]
https://github.com/dotnet/roslyn/pull/67255#issue-1618807605 has the details.

> 4. SemanticModel analyzer- execute semantic model action callback on the input file. The driver was only doing so for compiler analyzer, but after this PR we do so for all semantic model analyzers. Note that the public API for semantic model action callbacks does not take a filter span for analysis, though we have this span available in the driver. We should consider exposing a new public API for an optional FilterSpan on SemanticModelAnalysisContext, which should allow SmanticModel analyzers to optimize the diagnostic computation and reporting for just the span, instead of entire file. I'll file a tracking issue for this.

> 5. SyntaxTree based syntax-only analyzer - execute callback on input tree. Driver already did this correctly. Note that the public API for SyntaxTreeAction on the DiagnosticAnalyzer does not take any filter span, so there is no further optimization possible here - we have to request full tree syntax diagnostics. I'll file a tracking issue for exposing an optional FilterSpan on SyntaxTreeAnalysisContext to help analyzers optimize the diagnostic computation and reporting to just the span.

**Comment by CyrusNajmabadi** [comment]
Note: I would say 5 is very low priority. Our syntaxtree analyzers are *very* fast. 

4 would be good though as the addition of semantics slows things down a bunch.

**Comment by mavasani** [comment]
> Note: I would say 5 is very low priority. Our syntaxtree analyzers are _very_ fast.

I have seen performance traces showing Formatting analyzer, which is a SyntaxTree analyzer, when computing lightbulb diagnostics in large source files. I think we should add the API for both these contexts - it should be a very simple change with good performance benefit.

**Comment by CyrusNajmabadi** [comment]
Just to check, would the formatting analyzer be able to actually use this?  Can you check that there's a place that this would flow through? (i'm guessing yes, but we should just make sure).  Thanks!

**Comment by CyrusNajmabadi** [comment]
> I have seen performance traces showing Formatting analyzer, which is a SyntaxTree analyzer, when computing lightbulb diagnostics in large source files. 

Yup.  If we're seeing it in traces, then i'm def ok fixing.

**Comment by mavasani** [comment]
> Just to check, would the formatting analyzer be able to actually use this? Can you check that there's a place that this would flow through? (i'm guessing yes, but we should just make sure). Thanks!

Formatting analyzer calls into this helper: https://github.com/dotnet/roslyn/blob/d697090189c072943c2a3d315cb011a713a37a4a/src/Analyzers/Core/Analyzers/Formatting/FormattingAnalyzerHelper.cs#L18-L25

I believe we can pass in the `root.FindNode(context.Span)` instead of `tree.GetRoot(cancellationToken)` to `Formatter.GetFormattedTextChanges` call in that helper.

**Comment by mavasani** [comment]
@sharwell to confirm though.

**Comment by CyrusNajmabadi** [comment]
Yeah, def need confirmation on this.  I do think the formatter can format a span, but i think it would be through this entrypoint:

```c#
        internal static SyntaxNode Format(SyntaxNode node, IEnumerable<TextSpan> spans, ISyntaxFormatting syntaxFormattingService, SyntaxFormattingOptions options, IEnumerable<AbstractFormattingRule>? rules, CancellationToken cancellationToken)
```

But this does seem reasonable :)

**Comment by mavasani** [comment]
Talking with @arkalyanms, we are seeing IDE0055 analyzer show up in lightbulb telemetry on 17.7 P1. So this confirms that we should push for exposing this public API and use it to optimize the formatting analyzer.

**Comment by 333fred** [comment]
### API Review

* Purely informative, analyzers can still report outside of it
* Already proven internally.
* Should this be internal only?
    * Already used internal only, and we need it further, such as in roslyn-analyzers
* Call it `FilterSpan`
* Should we add it to _all_ contexts?
    * Some contexts might start being called from a different file than is being filtered. SymbolStart/Stop for a partial field, for example

Approved for these two apis. Further additions will need to consider the different tree and span scenario.

**Comment by mavasani** [comment]
> Approved for these two apis. Further additions will need to consider the different tree and span scenario.

@333fred @CyrusNajmabadi I think we should be fine with adding the FilterSpan API only for these 2 contexts.

However, attempting to implement the `SyntaxTreeAnalysisContext.FilterSpan` API and thread this span from the IDE layer to the compiler layer revealed that we also to need add overloads to the below 4 `CompilationWithAnalyzers` APIs that execute SyntaxTree actions to compute syntax diagnostics:

https://github.com/dotnet/roslyn/blob/0368609e1467563247e9b5e4e3fe8bff533d59b6/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L367-L425

## Proposal

Add public API overloads to the above 4 APIs that take a `TextSpan filterSpan` as the second last parameter:

```csharp
public Task<ImmutableArray<Diagnostic>> GetAnalyzerSyntaxDiagnosticsAsync(SyntaxTree tree, TextSpan filterSpan, CancellationToken cancellationToken);
public Task<ImmutableArray<Diagnostic>> GetAnalyzerSyntaxDiagnosticsAsync(SyntaxTree tree, ImmutableArray<DiagnosticAnalyzer> analyzers, TextSpan filterSpan, CancellationToken cancellationToken);
public Task<AnalysisResult> GetAnalysisResultAsync(SyntaxTree tree, TextSpan filterSpan, CancellationToken cancellationToken);
public Task<AnalysisResult> GetAnalysisResultAsync(SyntaxTree tree, ImmutableArray<DiagnosticAnalyzer> analyzers, TextSpan filterSpan, CancellationToken cancellationToken);
```

**Comment by mavasani** [comment]
Draft PR: #67818

**Comment by 333fred** [comment]
@mavasani let's send an email to API review with that proposal and see if we can do it over email while I'm out next week.

**Comment by mavasani** [comment]
> > Approved for these two apis. Further additions will need to consider the different tree and span scenario.
> 
> @333fred @CyrusNajmabadi I think we should be fine with adding the FilterSpan API only for these 2 contexts.
> 
> However, attempting to implement the `SyntaxTreeAnalysisContext.FilterSpan` API and thread this span from the IDE layer to the compiler layer revealed that we also to need add span based overloads to the below 4 `CompilationWithAnalyzers` APIs that execute SyntaxTree actions to compute syntax diagnostics:
> 
> https://github.com/dotnet/roslyn/blob/0368609e1467563247e9b5e4e3fe8bff533d59b6/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L367-L425
> 
> ## Proposal
> Add public API overloads to the above 4 APIs that take a `TextSpan? filterSpan` as the second parameter:
> 
> ```cs
> public Task<ImmutableArray<Diagnostic>> GetAnalyzerSyntaxDiagnosticsAsync(SyntaxTree tree, TextSpan? filterSpan, CancellationToken cancellationToken);
> public Task<ImmutableArray<Diagnostic>> GetAnalyzerSyntaxDiagnosticsAsync(SyntaxTree tree, TextSpan? filterSpan, ImmutableArray<DiagnosticAnalyzer> analyzers, CancellationToken cancellationToken);
> public Task<AnalysisResult> GetAnalysisResultAsync(SyntaxTree tree, TextSpan? filterSpan, CancellationToken cancellationToken);
> public Task<AnalysisResult> GetAnalysisResultAsync(SyntaxTree tree, TextSpan? filterSpan, ImmutableArray<DiagnosticAnalyzer> analyzers, CancellationToken cancellationToken);
> ```
> 
> Note that the [existing APIs to compute semantic analyzer diagnostics](https://github.com/dotnet/roslyn/blob/0368609e1467563247e9b5e4e3fe8bff533d59b6/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L471-L529) have an identical shape to the above proposed API

FYI: This proposal was accepted via offline email discussion.
