### ISSUE TITLE
Remove from Microsoft.CodeAnalysis.Features the deprecated Microsoft.CodeAnalysis.Elfie

### ISSUE THREAD

**Issue by fabiocbr75** [dotnet/roslyn#67256]
### Describe the bug
When you add Microsoft.CodeAnalysis.Features nuget package (all versions) in a .net 6 project, also a **deprecated** Microsoft.CodeAnalysis.Elfie is downloaded.

### Steps To Reproduce

Add to your project the Microsoft.CodeAnalysis.Features nuget package

### Expected behavior
No deprecated package used.

### Actual behavior
Microsoft.CodeAnalysis.Elfie deprecated package used.

**Comment by acarrazzoni-qontigo** [comment]
I can't even find the Microsoft.CodeAnalysis.Elfie version 1.0.0 package on nuget.org so I can't add Microsoft.CodeAnalysis.Elfie to my employer's internal repository

**Comment by CyrusNajmabadi** [comment]
We cannot remove this feature @arkalyanms .  This is waht powers 'add using' for nuget packages.  We consume this package so we can read the index hte nuget team produces.  PResumably they should own this package and its future.
