### ISSUE TITLE
CS7038: Failed to emit module 'name': Unable to determine specific cause of the failure.

### ISSUE THREAD

**Issue by hopperpl** [dotnet/roslyn#67258]
**Version Used**: 

17.6 P1 using .NET 8.0 P1

**Steps to Reproduce**:

1. `ISourceGenerator` created a full C# source file with a partial class definition, containing a full `enum` definition
2. a standard C# source file on top also defined the same enum in the same partial class (by accident, unintentional)

**Diagnostic Id**:

`CS7038`

**Expected Behavior**:

`CS0102: The type '<class>' already contains a definition for '<enum>'`

**Actual Behavior**:

`CS7038: Failed to emit module '<name>': Unable to determine specific cause of the failure.`

**Comment by jcouv** [comment]
Confirmed something is going wrong here.
Repro:
```
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/67258")]
        public void TODO2()
        {
            var source = @"
public partial class C
{
    public enum E { }
}
";

            var parseOptions = TestOptions.Regular;
            SingleFileTestGenerator testGenerator = new SingleFileTestGenerator(source); // duplicate source
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new[] { testGenerator }, parseOptions: parseOptions);

            Compilation compilation = CreateCompilation(source, options: TestOptions.DebugDllThrowing, parseOptions: parseOptions);
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _);

            Assert.Equal(2, outputCompilation.SyntaxTrees.Count());
            outputCompilation.VerifyEmitDiagnostics(); // missing diagnostic

            CompileAndVerify(outputCompilation);
            // Produced bad IL:
            // PEVerify failed for assembly 'C:\Users\jcouv\AppData\Local\Temp\RoslynTests':
            // Error: TypeDef has a duplicate based on namespace and name, token=0x02000006.
            // Error: TypeDef has a duplicate based on namespace and name, token=0x02000005.
        }
```

**Comment by RikkiGibson** [comment]
This might be a bug in `DeclarationTreeBuilder`.

**Comment by jcouv** [comment]
Sorry, I forgot to paste the details of quick investigation which led me to think this is a regression. I suspect the problem was introduced by the change of `var key = (t.Name, t.Arity);` to `var key = (t.Name, t.Arity, t.AssociatedSyntaxTree);` in `SourceMemberContainerSymbol.MakeTypeMembers`.
