### ISSUE TITLE
IIncrementalGenerator. Can't use generated properties - no errors in IDE, but build is not possible.

### ISSUE THREAD

**Issue by meancrazy** [dotnet/roslyn#67273]
**Version Used**: 
.Net SDK 6.0.406, Rider 2022.2.4

**Steps to Reproduce**:

1. Clone https://github.com/meancrazy/TestCodeGenerator
2. Try to build solution
3. See `Error CS1061 : 'TestVm' does not contain a definition for 'UtcNow' and no accessible extension method 'UtcNow' accepting a first argument of type 'TestVm' could be found (are you missing a using directive or an assembly reference?)`, but no errors in IDE
4. Also if comment any usage of generated properties and try to look to the IL, properties are missed, looks like compiler doesn't see generated file.
5. Also, generated files looks pretty good
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/1130419/224563283-d04b62f3-94cd-421a-bd31-8264a8841259.png">

**Expected Behavior**:
Project compiles and run

**Actual Behavior**:
Error CS1061, couldn't build project

**Comment by vuphuctho** [comment]
The issue is with Nuget package  `Microsoft.CodeAnalysis.CSharp` - version 4.5.0 is not compatible with runtime `net6.0`. Downgrading the package to version 4.0.0 works.

**Comment by jasonmalinowski** [comment]
@meancrazy In the actual build, was there a warning saying your generator couldn't be loaded? BEcause as @vuphuctho points out, your package version might be too high in this case.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
