### ISSUE TITLE
Compiler erroneously allows pointer to be used within a type-argument in a using-alias

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#67281]
This is currently allowed in the language without error:

```c#
using X = List<int*[]>;
```

This is due to the compiler only checking *directly* that the type parameters of a generic type are `managed types`, and 'Arrays' are managed types.

However, this should likely be illegal as the spec defines the concept of an [Unsafe Context](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/unsafe-code.md#222-unsafe-contexts), which is the only location where pointers can even be syntactically used.

We need to decide what to do about this.  Given that the above code was allowed since C#2.0 there is a def compat concern if we were to disallow this.  

That said, in C# 12 we added the ability to say `using unsafe X = ...`.  This gives us the option to say that in C# 12 we would now make this required, but continue to allow it in C#11 and prior.  We could potentially also have our upgrade-fixers detect/fix this in the rare, but possible, chance that this comes up in the wild.

**Comment by 333fred** [comment]
Discussed in LDM: https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-03-13.md#unsafe-in-aliases-hole
