### ISSUE TITLE
Provide a way to disable a rule from the lightbulb and errorlist

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#6728]
Today, one can suppress an instance of a rule from the lightbulb. It would be nice to have an action that changes the ruleset to disable that rule for that project with a single action as well.

**Comment by CyrusNajmabadi** [comment]
@mavasani do we have this?

**Comment by mavasani** [comment]
Yes, the configuration code actions already added this support from the lightbulb.
