### ISSUE TITLE
visual studio 2022 code search not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67297]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/visual-studio-2022-code-search-not-worki/10296052)._

---
[severity:Other]
visual studio 2022 code search not working well.
in my code I write WithOne but code search not found that.              

---
#### Feedback Bot on 3/1/2023, 10:20 PM: 

(private comment, text removed)
#### Feedback Bot on 3/3/2023, 00:36 AM: 

(private comment, text removed)
#### Feedback Bot on 3/14/2023, 08:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
This needs more information from the customer to be more actionable.
