### ISSUE TITLE
CompilationEndAction action is never called in VS Code or JetBrains Rider with solution-wide analysis enabled.

### ISSUE THREAD

**Issue by allisterb** [dotnet/roslyn#67294]
I wrote an analyzer that uses a compilation end action. While it works fine in Visual Studio, the end action never seems to get called in other IDEs that support Roslyn analyzers, even with solution-wide analysis enabled.

```
public override void Initialize(AnalysisContext context)
{
    ...
    context.RegisterCompilationStartAction(ctx =>
    {
        ...
       // MyAction never gets called 
       ctx.RegisterCompilationEndAction(cctx => MyAction(cctx.Compilation));
```

**Version Used**: 
Microsoft.CodeAnalysis.CSharp 3.11 (NuGet)
Using latest MSBuild for VS 2019.

**Steps to Reproduce**:

1. Write an analyzer that registers a compilation-end action in `RegisterCompilationStartAction`.
2. Make sure solution-wide analysis is enabled in Visual Studio Code and JetBrains Rider. There are settings to do this e.g. https://www.jetbrains.com/help/rider/Code_Analysis__Solution-Wide_Analysis.html. In VS Code OmniSharp I believe it's on by default.
3. Open a .NET project with Roslyn Analyzers enabled.

**Expected Behavior**:
Action registered to run at end of compilation should be called in other IDEs besides Visual Studio.

**Actual Behavior**:
Action is never called.

**Comment by allisterb** [comment]
@CyrusNajmabadi thanks for the quick response. According to the Rider docs, Rider has Roslyn solution-wide analysis, which I'd assume works the same as Visual Studio.
 
![ridersoln](https://user-images.githubusercontent.com/11426372/225043351-40738eaa-3049-4c83-8aa7-d0dfc60237c3.png)

When solution-wide analysis is disabled in Visual Studio, the end action also is never called.

The fact that it doesn't run in both VS Code and Rider is what made me think it's a Roslyn issue, not an issue with the IDEs.

**Comment by CyrusNajmabadi** [comment]
> The fact that it doesn't run in both VS Code and Rider is what made me think it's a Roslyn issue, not an issue with the IDEs.

We don't control how they use our APIs.  We have no concept in the analysis engine of "oh, FSA is on/off, so do/don't do this".  Instead, each host has their own analysis engine that calls into the analyzers.  It's up to the host to respect their individual FSA option and determine what that means wrt to calling Compilation-End actions. :)
