### ISSUE TITLE
Inconsistent capitalisation of "Remove Unnecessary Usings" in lightbulb menu

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#67328]
![image](https://user-images.githubusercontent.com/350947/225512805-a7240cac-59da-4763-8ba7-af206af014c5.png)

"Remove Unnecessary Usings" should probably be "Remove unnecessary usings".

**Comment by SimonZhao0512** [comment]
Hi @mavasani, I am a first time contributor, can I work on this issue?

**Comment by drewnoakes** [comment]
Thanks for your interest but it looks like it's already been fixed in https://github.com/dotnet/roslyn/pull/70675

Perhaps there's another issue you'd like to pick up.

**Comment by drewnoakes** [comment]
Fixed in #70675.
