### ISSUE TITLE
declaring new variable in out statements opening the code block

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#6733]
Little syntactic sugar which would save time on many occasions:
```csharp
if (int.TryParse("123", out int value))
{
  value *= 2;
} 
```

**Comment by Joe4evr** [comment]
This was on the roadmap for C# 6. Would be nice to see again once they solve the issues that made them drop expression declarations the first time.

**Comment by stepanbenes** [comment]
Seems like duplication of #6183
