### ISSUE TITLE
UseAutoProperty analyzer needs to be rewritten as a SymbolStart/End analyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#67350]
Currently, the analyzer uses SemanticModel actions, but can report diagnostic across files for partial definitions of types. Such diagnostics are non-local diagnostics, and lightbulb does not support non-local diagnostics. Rewriting the analyzer as SymbolStart/End analyzer should allow reporting local diagnostics within any of the partial definitions.

**Comment by CyrusNajmabadi** [comment]
I can try to take this.
