### ISSUE TITLE
Public LSP Handler API that provides Roslyn context

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/roslyn#67363]
## Background and Motivation

Currently XAML consumes internal APIs and infrastructure to handle LSP requests and maintains another API layer with IVT to the actual logic to handle the requests where it also relies on Roslyn symbols and workspace information. Shifting the API boundary to the LSP request handler layer would enable a cleaner separation between Roslyn and XAML while maintaining the need for XAML to run inside of whatever process the Roslyn LSP server runs.

## Proposed API

TBD

## Usage Examples

TBD

## Alternative Designs

TBD

## Risks

TBD

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this is needed, we need to move this off hte backlog to a real milestone.
