### ISSUE TITLE
Ref-assigning a ref parameter to a ref field with primary constructor

### ISSUE THREAD

**Issue by ufcpp** [dotnet/roslyn#67371]
**Version Used**: 

Visual Studio 17.6 Preview 2
C# Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98

**Steps to Reproduce**:

```cs
ref struct Ok
{
    public ref int Ref;

    public Ok(ref int x)
    {
        Ref = ref x; // OK
    }
}

ref struct Error(ref int x)
{
    public ref int Ref = ref x; // CS9077. Isn't this a bug?
}

ref struct ForReference([UnscopedRef] ref int x)
{
    public ref int Ref = ref x; // OK

    public void M1(ref int x)
    {
        Ref = ref x; // CS9077. This is correct.
    }

    public void M2([UnscopedRef] ref int x)
    {
        Ref = ref x; // OK
    }
}
```

**Expected Behavior**:

No error on `public ref int Ref = ref x;`, for consistency with `Ok` struct.

**Actual Behavior**:

CS9077 error.

See also #68610

**Comment by jcouv** [comment]
@AlekseyTs Please advise/triage

**Comment by jcouv** [comment]
@cston Is this a known issue for ref fields? I couldn't find an existing issue on this.

**Comment by FaustVX** [comment]
I've came across the same issue (#69055),
And I found a workaround for this if you are interrested.
It use `Unsafe.AsRef()` on the `ref` primary parameter.
```C#
ref struct Workaround(ref int x)
{
    public ref int Ref = ref Unsafe.AsRef(in x);
}
```

[sharplab.io](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAUEEsC2UECeAwgPYB2yMCcAxjCQsgDQwgBuE2YBTAJiAGoAPgAEADAAIRARgB0AJThkYuCLNI4ADlgA2nAMqc2WGigDcAWABQ1pGAmVqdCQHUGAa3wklvABR2JLGUJAA8ASmsAb2sJWKkAZgkAoJgJeQh7AF4kjIkAVQooSFkAQWR0sF8g0LDLKwBfIA===)
