### ISSUE TITLE
Stop silently adding 'using' directives when no auto-completion has been requested

### ISSUE THREAD

**Issue by betty-crokker** [dotnet/roslyn#67372]
## Summary

I have iTextSharp in other modules in my project.  In a C# file that is not referencing iTextSharp at all, I want to create a local variable of type `List<string>` so I start typing `List<` and as soon as I type the left-angle-bracket, VS decides that I mean the iTextSharp version, so it silently adds the line `using iTextSharp.text;` at the top of my file.  This causes my `List<string>` to fail, as that's not at all the List class I wanted.

Notice I not using any kind of auto-complete here.  If I had typed `List` and then hit the Tab key, that is me as a user asking VS to complete what I was typing.  In that case, it's reasonable for VS to perform the auto-completion, which would include adding the `using` directive.  In my case, I did not hit Tab, and so I was not asking VS to do any automatic completion.

Also notice there is an [existing issue](https://github.com/dotnet/roslyn/issues/36730) that talks about VS selecting non-generic classes when the left angle bracket key is pressed.  This suggestion is related but separate, as it's still problematic for VS to pick a class and automatically add the using directive, even if VS does a better job picking the class.

This is, as far as I know, the only time when the IDE modifies a user's source code without their knowledge or consent.

There is an option
Tools → Options… → Text Editor → C# → IntelliSense → Show items from unimported namespaces
that controls this feature, but 
(1) It says "show items", not "show items and then have VS pick one for you and automatically add the using directive" so the user is not aware of what the current option actually controls
(2) Showing items from unimported namespaces is often useful, even though "have VS pick one for you and automatically add the using directive" is not.  Having one option that controls both features is not as useful as being able to select them individually.

There is an [existing issue](https://github.com/dotnet/roslyn/issues/66898) to remove unused automatically-added directives on save.  This is related but again, the silent adding of using directives is a problem immediately, not just on save.

There is also a [request for updating the help page](https://github.com/MicrosoftDocs/visualstudio-docs/issues/9059), but I don't see that as a solution here.  The "Show items from unimported namespaces" option clearly (although incorrectly) states what it controls so the user is unlikely to feel they don't understand the option and go looking for a help page. 

## Proposed Feature

Stop modifying user code when the user has not asked VS to do so.  Only add using directives when auto-completion is request (by hitting the Tab key).

**Comment by CyrusNajmabadi** [comment]
@genlu could we add an option here so that unimported-completoin can only be committed using `<tab>`?

**Comment by genlu** [comment]
@betty-crokker You have summed up the issues around import completion really well :)

>  it silently adds the line using iTextSharp.text;

This should only happen if there's no type `List` in scope, since we always prefer in-scope types over unimported ones. Is this the case? In other words, did you intend to type `List`, and use "add using" codefix to manually add the missing import later?

> In my case, I did not hit Tab, and so I was not asking VS to do any automatic completion.

This is not the default behavior for VS completion though. By default, characters like ` ` and `<` would normally commit the hard selected items. For example, if you typed `Lis` and then `<`, it'd end up with List<> (with using statement added if not already). Additionally, complex code change is not limited to items from unimported namespaces, others like snippets and `await` would do something similar.

If you want VS to only auto-complete with TAB, then you can set Tools->Options->TetxEditor->Advanced->Default completion mode to TAB-only

<img width="896" alt="image" src="https://user-images.githubusercontent.com/788783/226432218-7d410798-1d46-4278-823b-814600b4ea0c.png">

**Comment by genlu** [comment]
> could we add an option here so that unimported-completoin can only be committed using <tab>?

@CyrusNajmabadi totally. But I want to understand if this is a broader issue first. From the sound of it, it seems suggestion mode fits the description above from @betty-crokker

**Comment by genlu** [comment]
> Setting Tools->Options->Text Editor->Advanced->Default Intellisense completion mode to Tab-Only doesn't work.

@betty-crokker OK, that's definitely a bug. I will look into that. Meanwhile, you can try to toggle "suggestion mode" via this button instead.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/788783/227060444-a17f38da-1c28-493d-8628-373aa885c746.png">

**Comment by betty-crokker** [comment]
Aha!  Yes, that option does the trick.  Thank you!

**Comment by genlu** [comment]
@betty-crokker Great. I will close this issue as by-design. As discussed above, for those who don't want VS to select and commit any item from the completion list during typing, they could use "tab-only" mode.

**Comment by ppg-avocado** [comment]
I have the same problem.
I use Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.8.3

I have Visual Studio set to auto-complete commits with TAB only, in settings:
Tools -> Options -> Text Editor -> Advanced -> Default IntelliSense completion mode: Tab-only
![image](https://github.com/dotnet/roslyn/assets/145983726/aa318313-a0a1-4fda-b675-94facb4bdbea)

then restart visual studio.
then i typed List and then <, Visual Studio then automatically adding using directive "using iTextSharp.text;" even i did not hit Tab or Enter.

so, Setting Tools -> Options -> Text Editor -> Advanced -> Default IntelliSense completion mode to Tab-Only doesn't work in my case.
here is toolbar screnshoot when visual studio open:
![image](https://github.com/dotnet/roslyn/assets/145983726/3b083f74-794b-4701-87af-5013a37fd9ed)

is there any other solution?
