### ISSUE TITLE
Expose metadata to mark analyzers for concurrent execution

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#6737]
[NOTE: Split from https://github.com/dotnet/roslyn/issues/1565, which now only tracks *enabling incremental analysis for 3rd party analyzers in IDE*]

This issue tracks exposing metadata from analyzers to mark them as thread-safe, such that analyzer driver will be free to make concurrent action callbacks into the analyzer instance.

**Comment by mavasani** [comment]
Possible design approaches:
1. Expose attribute which can be applied on `DiagnosticAnalyzer`.
2. Expose a property on `DiagnosticDescriptor`
3. Expose an API on `AnalysisContext` passed into `Initialize` method.

**Comment by sharwell** [comment]
[comment so I'm notified of updates]

**Comment by sharwell** [comment]
This is a big deal for performance in large projects. :+1:  I anticipate a majority of analyzers either supporting this from the start or only requiring minor updates to work with it.

**Comment by mavasani** [comment]
Design team decided on approach 3.
A new API `AnalysisContext.RegisterConcurrentExecution()` will be added - analyzers which invoke this API might have their unrelated actions (basically all the non-start and non-end actions) invoked concurrently by the analyzer driver.

**Comment by bmenees** [comment]
The VS 2015 Update 2 [announcement] (https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx#CsharpAndVB) references this issue as "enabling Analyzer writers to mark their analyzers for concurrent execution".  But it took me some digging to discover that the new API is _not_  `AnalysisContext.RegisterConcurrentExecution()` as mentioned by mavasani on Dec 1 2015.  The new API is actually `AnalysisContext.EnableConcurrentExecution()`.  I wanted to point that out here to save other people some time.  Currently, RegisterConcurrentExecution is only referenced in a cref comment link in roslyn-master\src\Test\Utilities\Desktop\CommonDiagnosticAnalyzers.cs, and that probably should be changed to EnableConcurrentExecution.

The Update 2 announcement also mentions "providing control over whether analyzers run in generated code".  For lack of a better place to put it, here's an example of doing that: `analysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);`
