### ISSUE TITLE
LSIF generator should have a stable, well-defined set of consumer + customer-facing requirements

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#67385]
#67383 tracks an issue that has recently cropped up in various repos that have LSIF generation enabled via build task. It appears that MSBuildLocator changed how it determines where MSBuild is and the downstream impact of that change may have broken assumptions in the build task that consumes the LSIF generator.

Zooming out.. I think there's a problem with the current relationship between the LSIF generator and the build task. The task does its best to assume what the LSIF generator needs to run, initialize those ENV VARS, download the tool, etc. If ENV VARs are the issue, the burden is on the user to properly set these ENV VARs when they acquire the .NET SDK.

In the near term, I think we need documentation for the LSIF generator that describes:

- The requirements for it to run successfully.
- Known issues, solutions to common problems, FAQ, and how to report a problem.
- Troubleshooting steps if it fails to work correctly.

Ideally these can be broken down into obligations of the build task vs. obligations of the user.

**Comment by gundermanc** [comment]
**cc: ** @jasonmalinowski, @NTaylorMullen

**Comment by jasonmalinowski** [comment]
@gundermanc We really should have a bigger conversation on this, and also get some MSBuild folks in on that conversation too. For example, in the bug you're linking to, if this is indeed an MSBuildLocator problem...we don't know really know what the requirements are either. It's black voodoo magic to us too. Not saying we can't learn better, but we might need multiple contributors here.

**Comment by gundermanc** [comment]
I'm filing these issues piecemeal but final one is identifying a long-term strategy between the 3 teams where: 1) we define a packaging strategy and pattern for getting you the inputs you need 2) you bootstrap your dependencies 3) MSBuild facilitate.

I'm happy to drive this with folks' input.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this stuff is important, we need to drive to specific pieces of work and milestones to do it.  Opening lots of open design questions and pushing out indefinitely doesn't lead to shipped solutions for the problem.
