### ISSUE TITLE
Integrate `dotnet format` in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67399]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Integrate-dotnet-format-in-Visual-Stud/10309553)._

---
Currently I have to run `dotnet format` in terminal to format files opened in Visual Studio.

Visual Studio 2022 is able to give me messages and IntelliCode based on settings in `.editorconfig`, but I have to fix them one by one. I need something that does `dotnet format` with one click / keyboard shortcut.

Maybe we could make it a code cleanup option or something in the context menu.

---
#### Feedback Bot on 3/15/2023, 04:26 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
