### ISSUE TITLE
Add Explicit Return Type in C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67409]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Explicit-Return-Type-in-C/10247566)._

---
Please add a feature to suggest adding an explicit return type. I know we can use the var keyword, But sometimes I need to add an explicit return type and each time I should type this.

![image](https://user-images.githubusercontent.com/4564579/226675824-0e32dd76-e2b2-4a75-800f-a182bca965c2.png)

---
#### Feedback Bot on 1/8/2023, 11:10 PM: 

(private comment, text removed)
#### Danial on 3/8/2023, 02:43 PM: 

(private comment, text removed)

**Comment by mavasani** [comment]
You can add `var` keyword for the type declaration and pressing Ctrl + Dot should show you a refactoring `Use explicit type` which will replace it with the full explicit type name.

Closing this out as this doesn't seem to warrant a separate refactoring.
