### ISSUE TITLE
Display only methods of a particular scope

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67407]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Display-only-methods-of-a-particular-sco/10248409)._

---
In C#, the combo boxes at the top give nice access within the code, particularly the alphabetized list of members of a class. While I rarely use the other boxes, they are also useful. 

I would really like one more feature - the ability to see public properties only. I think might best appear as another drop down with checkboxes for different scopes. I want this all the time when I am exploring API code (code I am using). 

Research could explore how to do this, as we do not usually filter code in the editor. As such, this might need to be a feature on the member dropdown, although that would be less ergonomic for my use case.

If we provide this feature for C#, we should also provide it for VB. 

And, those boxes are overlooked to often. Jazzing them up will give us a good reason to talk about them :)

---
#### Feedback Bot on 1/9/2023, 09:05 PM: 

(private comment, text removed)

**Comment by sharwell** [comment]
It seems likely that Document Outline will provide the necessary functionality here.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
