### ISSUE TITLE
Formatting toolbar should work in code window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67404]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Formatting-toolbar-should-work-in-code-w/10257626)._

---
Formatting toolbar is grayed out while editing c# code.
It would be useful to be able to use text highlighting while coding.

BR
Olavi

![image.png](https://aka.ms/dc/image?name=Bcd2cddcf0d10468e96cc9efef6731bf7638097295762095635_20230119-145255-image.png&tid=cd2cddcf0d10468e96cc9efef6731bf7638097295762095635)

---
#### Feedback Bot on 1/19/2023, 09:21 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not roslyn.
