### ISSUE TITLE
Visual Basic Documentation Comments should minimize beside target, not above it.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67401]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Basic-Documentation-Comments-shou/10301875)._

---
When inline documentation (e.g. a summary xml tag) is collapsed in the Visual Basic editor, it shows as a single expandable line directly above whatever it is attached to. When that thing is collapsed, it shows as a separate line below the collapsed documentation. This can be really confusing when you have many collapsed methods next to each other.

It would be better for the documentation to collapse to, say, a "..." to the left of the method or whatever it is attached to, so the relationship between the two is obvious.
It would also be good for the attached documentation to disappear entirely when the method (or whatever) is collapsed, again to make the relationship between the clear, and also because it is logical: collapsing something collapses/conceals its members, so it should also collapse/conceal its documentation.

[Screenshot 2023-03-06 223721.png](https://aka.ms/dc/file?name=B574b2280f10a4528958fe65b0d6015b7638137642922331374_Screenshot_2023-03-06_223721.png&tid=574b2280f10a4528958fe65b0d6015b7638137642922331374)

---
#### Feedback Bot on 3/7/2023, 02:40 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Only one report of htis from one user for a scenario that has worked the same way for 20 years.  Not planning on doing this without good reason.
