### ISSUE TITLE
Highlight references under cursor only if fully selected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67408]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Highlight-references-under-cursor-only-i/10247136)._

---
Using Visual Studio 2019 Professional, v16.11.16.

Tools > Options > Text Editor > C# (or Basic) > Advanced > Highlighting (see attached).

There is a feature called "Highlight references to the symbol under cursor". Occasionally useful, but problem is that this generates a lot of distracting visual clutter. Its also a little slow as some background task has to analyse the code. Most of the time I don't want this feature to be active, so have turned it off.

To make the feature less intrusive and faster, my suggestion is that references will be highlighted *only* if the whole symbol is selected in the editor i.e. either:

* Change the current feature so that references are only highlighted if the symbol under the cursor is fully selected. To make the feature clearer, the setting text would need to change to something like "Highlight references to the symbol under cursor, (if fully selected)".

* Add a new check box under the current setting which is something like "Only if symbol is fully selected". Default = OFF to maintain existing functionality.

1st has the advantage of not adding yet another setting.  2nd has the advantage of maintaining existing functionality.

To be clear, say the symbol under the cursor is "myVariable". Fully selected means that the cursor is over "myVariable", there is at least one character selected, and the selected text must be exactly equal to "myVariable". If nothing is selected, or "yVar" or "int myVariable =" were selected, then the feature is inactive and nothing is highlighted. Selecting the whole symbol, as in most modern editors like Notepad++, would mean click-and-drag or simply double-clicking (i.e. a conscious choice by the developer rather than just where the cursor happens to be).

Thanks,
Alain Dekker [abdekker d.o.t online  gmail dot com]

[Highlight-References-Under-Cursor.png](https://aka.ms/dc/file?name=Bf3162125af7e49cf93a024fa394768fd638086136281292660_Highlight-References-Under-Cursor.png&tid=f3162125af7e49cf93a024fa394768fd638086136281292660)

---
#### Feedback Bot on 1/9/2023, 01:10 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Definitely nto changing this without a lot of user feedback on needing this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
