### ISSUE TITLE
[MAUI] Roslyn source generator is not run during .NET Hot Reload, triggers rude edit when x:Name is changed

### ISSUE THREAD

**Issue by spadapet** [dotnet/roslyn#67428]
**Version Used**: .NET 7 or .NET 8.0.100-preview.2.23151.8
I installed .NET 8 using the following internal instructions to get MAUI working. However, .NET 7 installed with Visual Studio 2022 gives the same results.

* [.NET 8 Preview 2](https://loop.microsoft.com/p/eyJ1IjoiaHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC5jb20vc2l0ZXMvODIwM2RmODYtZDNjMi00Yzk4LWFkMmUtYzUxMTJmMzVkMGE2P25hdj1jejBsTWtaemFYUmxjeVV5UmpneU1ETmtaamcyTFdRell6SXROR001T0MxaFpESmxMV00xTVRFeVpqTTFaREJoTmlaa1BXSWxNakV6Wm1GeWNsWlZNM1pGYlVaSGJHSkRXa3hoT0MxMVpsVkVVVmxKWjJKa1NuSjZWREZCTFc1bVlVSkdhMVpQUzFvMVVrRTFVa294YjNOTU5HbFNZM1ZPSm1ZOU1ERldWVTVUTmxOYVNVZFVURTVhUWtoSVVFNUlNek5VVkZGRVJGSlpUakphUlNaalBTVXlSaVpoUFV4dmIzQkJjSEFtY0QwbE5EQm1iSFZwWkhnbE1rWnNiMjl3TFhCaFoyVXRZMjl1ZEdGcGJtVnlKbmc5SlRkQ0pUSXlkeVV5TWlVelFTVXlNbFF3VWxSVlNIaDBZVmRPZVdJelRuWmFibEYxWXpKb2FHTnRWbmRpTW14MVpFTTFhbUl5TVRoWmFVVjZXbTFHZVdOc1dsWk5NMXBHWWxWYVNHSkhTa1JYYTNob1QwTXhNVnBzVmtWVlZteEtXakpLYTFOdVNqWldSRVpDVEZjMWJWbFZTa2RoTVZwUVV6RnZNVlZyUlRGVmEyOTRZak5PVFU1SGJGTlpNMVpQWmtSQmVGWnNWazlWZWxwVVRtdFdZVlpzVGs5Vk1YQkVWR3M1WVZGcmVFOVRWbWQ2VjFSUmVVMHhSbE5WTUVVbE0wUWxNaklsTWtNbE1qSnBKVEl5SlROQkpUSXlaRGd3WlRFek5qZ3ROV0l5T0MwMFpXSXhMV0l4WWpZdE5EWTFOR0UxTmpVM1ltSXpKVEl5SlRkRSJ9)

**Steps to Reproduce**:

1. In Visual Studio 2022, create a blank new MAUI app from template:
    * ![image](https://user-images.githubusercontent.com/2523431/226753284-c562f61b-d5a4-451b-b1fa-3759bf5cd34e.png)
2. Choose .NET 7 or 8
    * ![image](https://user-images.githubusercontent.com/2523431/226753466-94c26d81-a125-49e0-89e9-aadb58e07825.png)
3. F5 to build and debug _Windows Machine_ target. You should have .NET Hot Reload and XAML Hot Reload options turned on, which is the default.
4. In the VS solution explorer, you should be able to see the MainPage.xaml.sg.cs file that was generated by MAUI's source generator:
    * ![image](https://user-images.githubusercontent.com/2523431/226753917-ba75a71a-7345-4798-96e0-dc879a8624d6.png)
5. Open in and notice the generated backing field for x:Name=CounterBtn
    * ![image](https://user-images.githubusercontent.com/2523431/226754068-082f0c8a-e988-4ab7-b2d9-4a9739296f27.png)
6. In VS, open MainPage.xaml and add a new Button element with a new x:Name:
    * ![image](https://user-images.githubusercontent.com/2523431/226754429-6922e3b8-1b5a-436d-83f0-74d59475e1df.png)
    * ```<Button x:Name="button2" Text="Button2" />```
7. Click Hot Reload button:
    * ![image](https://user-images.githubusercontent.com/2523431/226754497-589885d0-e3bf-4859-93e0-b24341d4e844.png)

**Expected Behavior**:

The generated MainPage.xaml.sg.cs file should now include the button2 field, since the MAUI source generator should be re-run for hot reloading. Hot reload should apply changes successfully.

**Actual Behavior**:

This is considered a rude edit. If you look at the generated MainPage.xaml.sg.cs file, it hasn't changed (no button2 field).

![image](https://user-images.githubusercontent.com/2523431/226754541-6a5c0ea2-b8ab-4f5c-8a58-9d83d60a11a6.png)

**Comment by davidwengier** [comment]
Source generator is running and updating the generated document:
![image](https://user-images.githubusercontent.com/754264/226766318-dab348d6-1a16-4fd8-928f-4cc0125d94b5.png)

Rude edit is coming from the attribute change on the `InitializeComponent` method

**Comment by spadapet** [comment]
I tried adding attributes to methods and classes in MAUI and console projects, in .NET 7 and 8. All of them had a rude edit when adding an attribute. Only console app showed an error in the error list. So the bug isn't just about MAUI and source generators, it's just attributes in general.

![image](https://user-images.githubusercontent.com/2523431/226807650-69b93f4e-95c8-4d30-8bdd-3ef69dc2cf62.png)

**Comment by davidwengier** [comment]
@mavasani or @tmat might know more about whether rude edits in source generated files are expected to show up in the Error List, or if there are any known bugs.

Being unable to update attributes is surprising though, as the runtime should support it:
https://github.com/dotnet/runtime/blob/696c35cfed2ad87b59294a2ee548ea45e7da06ce/src/coreclr/System.Private.CoreLib/src/System/Reflection/Metadata/MetadataUpdater.cs#L57

**Comment by davidwengier** [comment]
I tested in VS 17.6 P2 and VS main, targetting .NET 7.0.4, and it looks like this works with Ctrl+F5, but not with F5.

**Comment by davidwengier** [comment]
Looks like this was inadvertently broken in https://github.com/dotnet/runtime/pull/56511 when a method was moved, and the debugger is trying to use that method:
https://devdiv.visualstudio.com/DevDiv/_git/Concord?path=/src/vil/host/VisualStudioHost/EE/VilEvaluationServices.cs&version=GBmain&line=2839&lineEnd=2854&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Going to close this out, since its not a Roslyn issue.
