### ISSUE TITLE
Don't create duplicate output window categories

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#67429]
Seems like one of these is created for each solution load. I know logging is important.. but perhaps not this important :)

<img width="472" alt="image" src="https://user-images.githubusercontent.com/754264/226760154-e60715ff-7eb9-4fd0-993c-b3e90d931d05.png">

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, it should be assigned to dev/milestone to eb done.
