### ISSUE TITLE
Consider changing lookup of simple assembly names in #r

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#6742]
```#r "<simple assembly name>"``` currently only queries the GAC for the assembly name. Perhaps we should also consider existing files in the reference search paths and among those and the results we get from GAC pick the highest version.

We can also return all versions we find and let the compiler select the one that best matches other references and mark the others as superseded.

Keep in mind though that the CLR always prefers GAC over other locations and we should respect that. So the scenario described below might not actually benefit from any changes we make.

**Scenario**:

"I was referencing the SharePoint client libraries by assembly name. It turns out that, instead of loading the 14.0.0.0 assemblies in the same folder as the script, csi was loading the 16.0.0.0 assemblies that I didn't remember I had in the GAC and the 16.0.0.0 version of Microsoft.SharePoint.Client.Web has a method with a signature compatible with the extension method I wrote and that translates into a server call to a server that doesn't have that operation."

Solving it was just changing this:

```
#r "Microsoft.SharePoint.Client"
#r "Microsoft.SharePoint.Client.Runtime"
```

into this:

```
#r "Microsoft.SharePoint.Client.Runtime.dll"
#r "Microsoft.SharePoint.Client.dll"
```

**Comment by daveaglick** [comment]
I'm trying to build something similar to what the scripting engine does for this - any pointers on where to look for the code responsible for the #r simple name mapping?

**Comment by tmat** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/Hosting/Resolvers/RuntimeMetadataReferenceResolver.cs,19 

You won't be able to replicate exactly what scripting does as it uses some properties that are currently internal though. We have a work item to make them public on our backlog.

**Comment by daveaglick** [comment]
@tmat Thanks! That's extremely helpful.

**Comment by tmat** [comment]
Let's keep the resolution as is -- that is ```#r "assembly name"``` should use the target CLR Framework assembly resolution mechanism (GAC on Desktop, TPA/Default AssemblyLoadContext on CoreCLR).
