### ISSUE TITLE
CSharp compiler Unit test FuzzTesting.TestBinary is flaky

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#6744]
I get intermittent `System.OutOfMemoryException` from this test.

```none
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.FuzzTesting.TestBinary' failed: System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
	at System.Text.StringBuilder.ToString()
	Parsing\FuzzTesting.cs(94,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.FuzzTesting.TestBinary()
```

**Comment by gafter** [comment]
I'm not sure there is anything we can do about it.

**Comment by TyOverby** [comment]
@gafter, do you know if it would be possible to adequately test this behavior with smaller strings?

**Comment by TyOverby** [comment]
Looking at the test, I think we could cut down the size by a large factor and it will still be a good fuzz test.  I'm checking to see if we can use a stream of random bytes rather than a string.

**Comment by TyOverby** [comment]
I've actually got a "fix" for this.  PR coming soon

**Comment by gafter** [comment]
When we "fixed" the issue this is testing, we picked 40K as the size of an input a bit more than the threshold where the parser used to choke. So making it substantially smaller would not catch a regression of that particular issue.

Having said that, I am not sure this test adds much value any longer.

**Comment by TyOverby** [comment]
The crash occurs when you are doing the massive concatenation at the end.  For a brief period of time, we need double the amount of memory than what is "actually" necessary.

My fix uses unsafe in order to only allocate one large char array, fill that, and then convert it unsafely to a String for the parser.
