### ISSUE TITLE
GetImportScopes returns 0 scope at leading trivia attached to EOF 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#67447]
`SemanticModel.GetImportScopes(pos)` for the code below returns 0 scope, where we expect 1.

```cs
global using System;

/*pos*//**/
```

Demonstrated by https://github.com/dotnet/roslyn/pull/67446

**Comment by jcouv** [comment]
Tagging @AlekseyTs to advise/triage.

**Comment by AlekseyTs** [comment]
For the purpose of all SemanticModel position based requests, a position in a leading trivia of a token is getting adjusted to position in the previous token. For the specific scenario, we are ending up in the `using` statement and usings are not in scope there.

**Comment by jcouv** [comment]
Thanks @AlekseyTs. Closing as by-design then.

**Comment by AlekseyTs** [comment]
This is a behavior that is at least 10 years old. So, I am not sure if changing it is such a good idea.

In general, what I can recommend is to carefully pick the position to pass to SemanticModel API. For example, a position in front of all the usings is not in the usings, and, therefore, is not subject to the "in using" binding rules. It is not like usings bring something into the scope after the directives. They bring something into the scope in the compilation unit containing the usings, in the **entire** compilation unit. And there are special binding rules in the usings, which are different from everywhere else in the compilation unit. I think the most reliable way is to use location of a non-trivia token in the specific syntactic construct of interest. Using positions in between constructs could lead to surprising results.
