### ISSUE TITLE
Syntax actions not always called in Roslyn 4.5.0

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#67458]
**Version Used**: 4.5.0. Works with 4.6.0-1.final.

**Steps to Reproduce**:
1. Checkout https://github.com/bjornhellander/StyleCopAnalyzers/tree/feature/roslyn450-problem
2. Run the tests in c# 11 test project

**Diagnostic Id**: N/A

**Expected Behavior**:
0/2 test failing.

**Actual Behavior**:
70 tests failing

**Notes**:
Originally reported in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3620.

Sorry for not providing a smaller repro, but I have not yet managed to reproduce this in a minimal analyzer project. I will continue trying, but I thought it was better to get it reported anyway.

Some (2?) of the tests fail just because of different compiler errors compared to 4.4.0. That is not a problem.
The reason for the other failing tests seems to be that registered syntax node actions and syntax tree actions do not get called in some cases.

The result seems to be consistent. It is always the same tests that fail, at least on my machine. It does however not seem to be related to the syntax node kind. There are for example multiple analyzers registering actions on property declarations, but only tests for some of them fail.

4.6.0-1.final works, i.e. our tests pass except for the changed compiler errors. You decide how to handle this, since it seems it will start working again as "soon".

**Comment by bjornhellander** [comment]
This could of course be due to problems in the StyleCop Analyzers code, but I saw https://github.com/dotnet/roslyn/issues/67211 and thought it be worth reporting it directly, since it seemed they might possibly be related.

**Comment by sharwell** [comment]
Could this be related to #66779?

**Comment by bjornhellander** [comment]
Seems to have been fixed in https://github.com/dotnet/roslyn/pull/67300.
I noticed that no new nuget packages have been released, but I have no need for any, so closing this.
