### ISSUE TITLE
ToDisplayString for IParameterSymbol adds parameter name nomatter the settings (by default)

### ISSUE THREAD

**Issue by nschuessler** [dotnet/roslyn#67464]
This seems to be a breaking change Roslyn 4.4 to 4.5. The code below exhibits the problem. Basically this code now always includes the parameter name no matter what your `SymbolDisplayFormat` settings are:

```csharp
IParameterSymbol? parameterSymbol = semanticModel.GetDeclaredSymbol(parameter) as IParameterSymbol;
string typeName1 = parameterSymbol.ToDisplayString(format1);  // Original code works with Roslyn 4.4
```

Here is the output:

```
MyNamespace.SecondClass c Match: False
MyNamespace.SecondClass c Match: False
c Match: False
```
See code below for repro.

```cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

SymbolDisplayFormat format1 = SymbolDisplayFormat.CSharpErrorMessageFormat
            .WithGenericsOptions(SymbolDisplayGenericsOptions.None);

SymbolDisplayFormat format2 = format1.WithParameterOptions(SymbolDisplayParameterOptions.IncludeType);
SymbolDisplayFormat format3 = format1.WithParameterOptions(SymbolDisplayParameterOptions.None);

(Solution solution, Project project) = GetSolutionAndProject();

Compilation? compilation = await project.GetCompilationAsync();

if (compilation == null)
{
    return;
}

SyntaxTree tree = compilation.SyntaxTrees.First();
ParameterSyntax parameter = tree.GetRoot().DescendantNodes().OfType<ParameterSyntax>().First();

SemanticModel semanticModel = compilation.GetSemanticModel(tree);

string expected = "MyNamespace.SecondClass";

IParameterSymbol? parameterSymbol = semanticModel.GetDeclaredSymbol(parameter) as IParameterSymbol;
if (parameterSymbol == null)
{
    return;
}

string typeName1 = parameterSymbol.ToDisplayString(format1);  // Original code works with Roslyn 4.4
string typeName2 = parameterSymbol.ToDisplayString(format2);
string typeName3 = parameterSymbol.ToDisplayString(format3);

Console.WriteLine($"{typeName1} Match: {typeName1.Equals(expected)}");
Console.WriteLine($"{typeName2} Match: {typeName2.Equals(expected)}");
Console.WriteLine($"{typeName3} Match: {typeName3.Equals(expected)}");

(Solution, Project) GetSolutionAndProject()
{
    CSharpCompilationOptions compilationOptions =
    new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary);

    ProjectId projectId = ProjectId.CreateNewId(debugName: "MyProject");
    ProjectInfo projectInfo = ProjectInfo.Create(projectId,
        VersionStamp.Default,
        "TestProject",
        "TestProject",
        LanguageNames.CSharp,
        compilationOptions: compilationOptions);
   
    AdhocWorkspace workspace = new AdhocWorkspace();
    workspace.AddSolution(
        SolutionInfo.Create(
            SolutionId.CreateNewId(),
            VersionStamp.Default,
            projects: new[] { projectInfo }));

    Solution solution = workspace.CurrentSolution;
    string fileName = "Program.cs";
    DocumentId documentId = DocumentId.CreateNewId(projectId, debugName: fileName);

    solution = solution.AddDocument(
        documentId,
        fileName,
        SourceText.From(GetExampleCode()),
        filePath: Path.Combine(Environment.GetEnvironmentVariable("TEMP"), fileName));

    return (solution, solution.GetProject(projectId));
}
string GetExampleCode()
{
    return @"
using System;
using System.Collections.Generic;

namespace MyNamespace
{
    public class FirstClass
    {
        public void MyMethod(SecondClass c)
        {
             c.One(4, Environment.NewLine);
        }
    }

    public class SecondClass
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }

        public override string ToString()
        {
            return string.Empty;
        }

        public void One(int p1, string p2) { }
        public void Two() { }
        public void Three() { }
        public void Four() { }

        public static void DoSomething1(string input) { }
    }
}
";

}
```

**Comment by CyrusNajmabadi** [comment]
Yes.  The change was intentional.  Here: https://github.com/dotnet/roslyn/pull/65606

**Comment by CyrusNajmabadi** [comment]
@jjonescz was it intentional that existing callers could not get the same custom behavior the compiler introduced for itself?  That seems odd taht the use case used to be possible, was known to be desirable for the compiler, but was changed and only added in as an internal option that public consumers can then not use.

**Comment by nschuessler** [comment]
How is one to get the old behavior? If this is intentional, then there wouldn't be a need for this member of the enum right?

```
       /// <summary>
        /// Includes parameter names in symbol descriptions.
        /// </summary>
        IncludeName = 1 << 3,
```

Currently this is my workaround:

```
// Workaround for behavior change in Roslyn 4.5 ToDisplayString that appends
// parameter name no matter what.
string junk = $" {parameterSymbol.Name}";
int i = parameterTypeName.IndexOf(junk);
if (i > 0)
{
    parameterTypeName = parameterTypeName.Substring(0, i);
}
```

**Comment by nschuessler** [comment]
Also, are there any other symbol types with formatting changes?

**Comment by jjonescz** [comment]
> was it intentional that existing callers could not get the same custom behavior the compiler introduced for itself? That seems odd taht the use case used to be possible, was known to be desirable for the compiler, but was changed and only added in as an internal option that public consumers can then not use.

Hm, that was not the intention. It seems we decided to change the default behavior midway through the PR without considering external consumers: https://github.com/dotnet/roslyn/pull/65606#discussion_r1036080542. Before that I decided to go with compiler-internal option before deciding on the public API. But I guess the combination of those decisions doesn't make sense.

> If this is intentional, then there wouldn't be a need for this member of the enum right?
> 
> ```
>        /// <summary>
>         /// Includes parameter names in symbol descriptions.
>         /// </summary>
>         IncludeName = 1 << 3,
> ```

This enum member comes from parameter options - which are only used when you call `ToDisplayString` on members, not the parameter themselves:

```cs
/// <summary>
/// Specifies how parameters are displayed in the description of a (member, property/indexer, or delegate) symbol.
/// </summary>
[Flags]
public enum SymbolDisplayParameterOptions
```

**Comment by CyrusNajmabadi** [comment]
> How is one to get the old behavior? (i.e. just getting the type name from the parameter symbol) 

Two questions:

1. What's the use case where that is desirable?  Can you clarify why you'd only want the type, and not hte name, if you're displaying a parameter?
2.  If you *do* want just the type name, why not just call ToDisplayString on the type-symbol of the parameter if you have that?

**Comment by jjonescz** [comment]
> 2\. If you _do_ want just the type name, why not just call ToDisplayString on the type-symbol of the parameter if you have that?

For example, you can't do that if you want to get `"ref int"` for the parameter in `M(ref int p)` - you need to have `IncludeParamsRefOut | IncludeType`, but not `IncludeNameIfStandalone`.

Also I would imagine you want to have a generic format and use it for displaying any kind of `ISymbol` - without special-casing `IParameterSymbol`s.

**Comment by CyrusNajmabadi** [comment]
> For example, you can't do that if you want to get "ref int" for the parameter in M(ref int p)

True.  i'm just trying to think about when i want just `ref int` and not `ref int p` if i'm referring to the parameter *standalone*.   I totally get the use case for when it's in a signature.  But that's already supported today :)

**Comment by nschuessler** [comment]
for (2) above that is what I ended up doing in this case. However we do have code that has a generic `ISymbol` and we probably use a generic ToDisplayString() on it. That means we now need to split it apart by symbol type and treat `IParameterSymbol` differently. It doesn't appear that ISymbol has a Type on it at first glance.
