### ISSUE TITLE
Outlining - Collapse #regions on file open not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67463]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Outlining---Collapse-regions-on-file-op/10318068)._

---
For C# Text Editor - the option to Enter outlining mode when files open > Collapse #regions on file open is not working.

---
#### Feedback Bot on 3/22/2023, 08:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I do not repro this.

**Comment by CyrusNajmabadi** [comment]
@jaysanati see https://github.com/dotnet/roslyn/issues/67463#issuecomment-2495171247
