### ISSUE TITLE
Extract Method "continue anyway" does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extract-Method-continue-anyway-does-no/10323592)._

---
[severity:It's more difficult to complete my work]
Using the extract method should attempt to extract a method with broken return types when it can't fully extract the method, but instead when clicking "yes" to the "continue anyway?" messagebox, nothing happens.

---
#### Feedback Bot on 3/27/2023, 03:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing otu as i cannot repro this.
