### ISSUE TITLE
Breaking change in overload resolution in VS2015 RTM

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#6750]
The following compiles in versions preceding VS2015, but not in VS2015. In other words this appears to be broken by Roslyn.

```cs
using System;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        RunNoThrow(GetSlowlog);
    }

    static void GetSlowlog() { }

    public static bool RunNoThrow(Action a)
    {
        throw null;
    }
    static async public Task RunNoThrow(Func<Task> action, Func<Exception, bool> IsFatal = null)
    {
        throw await (Task<Exception>)null;
    }
}
```

In earlier versions it selected the `RunNoThrow(Action a)` overload. In VS2015 it selects the `RunNoThrow(Func<Task> action, Func<Exception, bool> IsFatal = null)` overload and complains that the return type of `GetSlowlog` is wrong.

I suspect Roslyn has the overload resolution tiebreaker rules in the wrong order.

**Comment by gafter** [comment]
@AlekseyTs Would this be fixed by your pending change?

**Comment by AlekseyTs** [comment]
@gafter Assuming you are referring to #7727, I think, this scenario would be fixed by it.

**Comment by gafter** [comment]
Dup of #6560, which is fixed in master.
