### ISSUE TITLE
Either change nameof or change the warning rules

### ISSUE THREAD

**Issue by PeterWone** [dotnet/roslyn#67526]
In generics `nameof(T)` returns "T" which is logically valid but thoroughly unhelpful.

Either change the behaviour so it returns the name of the actual class, or leave it as is and instead change the ide0082 rule so it doesn't nag people to change `typeof(T).Name` to `nameof(T)` **which is _not_ currently equivalent**. If you decide not to change the behaviour of `nameof` (and I can see why that would be a PITA) you might also want a new rule that applies only in generics exhorting people to change `nameof(T)` to `typeof(T).Name`.

**Comment by CyrusNajmabadi** [comment]
What version of VS are you on.  This should have been fixed by https://github.com/dotnet/roslyn/pull/60182.

Can you supply a repro case where you are seeing this?

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me in latest main:

![image](https://user-images.githubusercontent.com/4564579/228335130-3371c8a8-d0ad-4f6d-8f9c-536eefa0eca3.png)

I do see the item offered where expected:

![image](https://user-images.githubusercontent.com/4564579/228335210-30c6784b-9bce-4a66-9297-179cfdcb5756.png)

If you have a repro, please let us know.

**Comment by PeterWone** [comment]
Thanks Cyrus, I'll do an update and check whether this is still a thing.
