### ISSUE TITLE
Extract Interface in VB module gives misleading error message

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6754]
The existing error message makes me thing I merely need to make my methods extractable (instead of telling me not to extract interface on a module)

![image](https://cloud.githubusercontent.com/assets/235241/11136352/742eca6a-8962-11e5-8e45-f02db73aaeb2.png)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not planning on changes in this area.
