### ISSUE TITLE
EE:  Remove duplicate return value row for Update 2

### ISSUE THREAD

**Issue by pnelsonmsft** [dotnet/roslyn#6755]
To fix VSO bug 137772, I added a "$ReturnValue" alias.  This fixes the bug but has the effect of duplicating the last return value in the Locals window.  We need to fix the EC to filter out "$ReturnValue" (no number) when populating Locals to avoid a regression in Update 2.

**Repro:**

Install a vsucorediag build 24713 or later (won't repro before my fix)

Create a Console app with this code:
```C#
class P
{
    static void Main()
    {
        int i = F();
    }

    public static int F()
    {
        return 1;
    }
}
```
Set a breakpoint at the call to F();
Run to breakpoint
Single Step (F10)
View Locals window

**Result:** Two entries named `P.F returned` in the Locals Window

**Comment by ManishJayaswal** [comment]
We should fix this as it will enable $ReturnValue - see internal bug 137772

**Comment by amcasey** [comment]
@KevinH-MS Can you please verify?
