### ISSUE TITLE
region cannot be collapsed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67555]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/region-cannot-be-collapsed/10322801)._

---
[severity:It's more difficult to complete my work] [regression]
After upgrading from VS2019 to VS2022 (17.5.3), my #region directives no longer collapse and there are no "-" symbols to the left. I have confirmed that the "Collapse to Definitions #regions" option is checked. Is this a bug or do I have a setting wrong? The methods can still be collapsed, but the #regions cannot.

---
#### Feedback Bot on 3/26/2023, 09:15 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 3/27/2023, 09:35 AM: 

(private comment, text removed)
#### 云 赵 on 3/27/2023, 09:43 AM: 

(private comment, text removed)
#### Feedback Bot on 3/27/2023, 11:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Can you supply a repro file/project?  I don't repro this in latest roslyn bits.

**Comment by Okasile** [comment]
"I solved the problem by checking the option 'Show outlines for comments and preprocessor regions'. I apologize for not trying this earlier."

**Comment by CyrusNajmabadi** [comment]
Sounds good.  thanks!
