### ISSUE TITLE
Pasting text in snipped closes the edit mode immediately

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67572]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pasting-text-in-snipped-closes-the-edit-/10326783)._

---
[severity:It's more difficult to complete my work]
Example in VS 2022, C# porject

Situation is, I have a class name in clipboard. Using a snippet "prop" to create a property, pressing tab, creates the snippet. And "int" is marked. When I now paste, the "edit" mode of the snipped stops immediately, and the "MyProperty" text remains. that happens to all snippets. 
This is a real issue for me.

---
#### Feedback Bot on 3/30/2023, 04:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I was not able to reproduce this in Version 17.6.0 Preview 3.0 [33515.466.main] with either the new snippet experience or the old one.

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this either.
