### ISSUE TITLE
Dark theme brace highlighting is still too bright

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6757]
We tried to fix this for 1.1, but it doesn't appear to have worked.

![image](https://cloud.githubusercontent.com/assets/235241/11137357/ac13b2e8-896b-11e5-93eb-9ccbfbf3ad3d.png)

**Comment by sharwell** [comment]
I'm using #58623C as the background color for this, and am quite happy.

**Comment by dpoeschl** [comment]
Okay, I did fix this, and the fix works, but the fix wasn't included in the Update 1 setup. :disappointed:

**Comment by dpoeschl** [comment]
Update: working with the related teams to ensure this gets updated in the next version of Visual Studio.

**Comment by dpoeschl** [comment]
The setup fix for this is merged and tested internally, and brace matching will have the expected default color in future releases.
