### ISSUE TITLE
0b1100_0000, why not just b1100 0000?

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#6758]
Wouldn't it be better if compiler just used space as separator for number so we can read it easier as human beings? I think even prefixing 0 should be optional.

Does anyone think that b1100 0000 can be interpreted differently than 0b1100_0000 by anyone when reading source code?

**Comment by orthoxerox** [comment]
The parser will have a much tougher job. "Oh, an identifier `b1100` followed by a zero literal! What does it mean? Oh, great, now I have to check a special case where the identifier begins with a `b` and has only ones and zeroes, and the number is not just a zero, I must take its length into account! Oh, I wish that was the lexer's job!"

**Comment by krwq** [comment]
Oh, it's tougher - let's just give up and don't do it.

**Comment by SolalPirelli** [comment]
Making the `0` prefix optional would conflict with identifiers.

**Comment by orthoxerox** [comment]
@krwq Just how many binary literals will your code contain? The biggest piece of code where I would have used long binary literals dealt with NaN-packing of values and there were under twenty constants altogether.

**Comment by gafter** [comment]
To answer the original questions: we don't need a reason *not* to do something, and no, it would not be better. We experimented with a few approaches and this felt best.
