### ISSUE TITLE
Add `AdditionalTextValueProvider<TValue>`

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#67611]
This is a parallel API to the existing `SourceTextValueProvider<TValue>` and `SyntaxTreeValueProvider<TValue>`.  This would be useful in roslyn-analyzers where we currently need a CWT to store associated data with an `AdditionalText` file.  Specifically, this is to store the API-data for the "Public API analyzer" that should only be updated when an 'AdditionalText` file instance changes.

We cannot use SourceText (and thus SourceTextValueProvider) for this as we need to store additional information related to the AdditionalText itself (like the path of the file, etc.).

Api is:

```diff
    public sealed class SourceTextValueProvider<TValue>
    {
        public SourceTextValueProvider(Func<SourceText, TValue> computeValue, IEqualityComparer<SourceText>? sourceTextComparer = null);
    }

    public sealed class SyntaxTreeValueProvider<TValue>
    {
        public SyntaxTreeValueProvider(Func<SyntaxTree, TValue> computeValue, IEqualityComparer<SyntaxTree>? syntaxTreeComparer = null);
    }

+   public sealed class AdditionalTextValueProvider<TValue>
+   {
+       public AdditionalTextValueProvider(Func<AdditionalText, TValue> computeValue, IEqualityComparer<AdditionalText>? additionalTextComparer = null);
+   }

    public abstract class CompilationAnalysisContext
    {
        public bool TryGetValue<TValue>(SourceText text, SourceTextValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
        public bool TryGetValue<TValue>(SyntaxTree tree, SyntaxTreeValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
+       public bool TryGetValue<TValue>(AdditionalText text, AdditionalTextValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
    }

    public abstract class CompilationStartAnalysisContext
    {
        public bool TryGetValue<TValue>(SourceText text, SourceTextValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
        public bool TryGetValue<TValue>(SyntaxTree tree, SyntaxTreeValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
+       public bool TryGetValue<TValue>(AdditionalText text, AdditionalTextValueProvider<TValue> valueProvider, [MaybeNullWhen(false)] out TValue value);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
@mavasani for visibility.

**Comment by mavasani** [comment]
Note that TryGrtValue APIs exist on both AnalysisContext and CompilationStartAnalysisContext. New API overload should be added on both the context types.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by jcouv** [comment]
Assigned to @chsienki to triage as area owner for source generators.

**Comment by jcouv** [comment]
Oops, I'd assigned to wrong area. It's actually analyzers. Assigned to @mavasani to triage this request as area owner.

**Comment by sharwell** [comment]
Note that this API was originally motivated by https://github.com/dotnet/roslyn-analyzers/pull/6569, but prior to merge that pull request fully implemented its desired behavior using `SourceTextValueProvider<TValue>`. There are no known cases where the current API is blocking a performance story, and the improvements that roslyn-analyzers would gain from a new API are marginal at best (it would only need to store one `AdditionalTextValueProvider<>` instance, but it would still need the code it uses today for switching on the file extension).

**Comment by CyrusNajmabadi** [comment]
We wanted this for the public api analyzer as well.

**Comment by CyrusNajmabadi** [comment]
So that PR makes me feel even more strongly about wanting this API :)

**Comment by 333fred** [comment]
### API Review

* Worked around it for existing usages, do we really need it?
    * Is it the type of thing that we'd tell people not to use?
    * Not really. It's not super ergonomic, but it's not unsafe or dangerous.
    * Morally kind of wrong though?
* Approved, marked help wanted. If it gets done it gets done.
