### ISSUE TITLE
`IAwaitOperation.Type` shouldn't be void for VB when await is bound as statement

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#67616]
See https://github.com/dotnet/roslyn-analyzers/pull/6546#discussion_r1155254126

```vb
Imports System.IO
Imports System.Threading.Tasks

Public Module Program
    Public Async Function Main() As Task(Of Integer)
        Await File.ReadAllTextAsync("") ' await type is incorrectly void.
        Dim x = Await File.ReadAllTextAsync("") ' await type is correctly string
        Return 0
    End Function
End Module
```

This is special-cased here:

https://github.com/dotnet/roslyn/blob/37bfc47fa1e81ef7807f0cf8d55ce0f184db6303/src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb#L4897-L4901

Per @AlekseyTs comment in the conversation linked above:

> This might be an artifact of how native compiler behaved. It looks like changing this behavior affected only IOperation tests in the expected way. Feel free to open an issue for Roslyn.

**Comment by jeffhandley** [comment]
This is currently blocking how we'd like to finish the implementation of [Implement DoNotIgnoreAttribute analyzer for method return values](https://github.com/dotnet/roslyn-analyzers/pull/6546). In that analyzer, we need a way to determine if an await operation will produce a value or if it's a void. The behavior of `IAwaitOperation.Type` meets our expectaitons for C#, but not VB.

If there's a workaround readily available, please let me know.

**Comment by Youssef1313** [comment]
@jeffhandley *One* possible workaround is to use speculative semantic model (only for VB when `Await` is bound as statement). Basically we would create an artificial `Dim SOMEVARIABLE = Await ...` node and get the operation from it.

I'm not sure if this will have negative performance impact.

**Comment by jeffhandley** [comment]
I've explored a few angles, and I'm going to take the easy way out on that analyzer.

Instead of suppressing diagnostics for void-returning awaitables that have been annotated with `[DoNotIgnore]`, I simply won't suppress those when in VB. I'll leave a comment pointing to this issue and mark the corresponding unit test as skipped because of this work item.
