### ISSUE TITLE
Local constant declarations can specify const multiple times

### ISSUE THREAD

**Issue by jskeet** [dotnet/roslyn#6761]
Roslyn version: 1.0.0.50618

Sample code:

```csharp
class Test
{
    static void Main()
    {
        const const const bool flag = true;
    }
}
```

This should lead to a compile-time error as per C# 5 spec section 8.5.2, but it doesn't.

Source: http://stackoverflow.com/questions/33694904

**Comment by AdamMaras** [comment]
I'm not immediately opposed to this behavior—I see it as being a good way to communicate to other developers that the value is "really really const" and should never ever be changed.

**Comment by leppie** [comment]
It detects the error fine on type level, eg:
```
class Foo {
  const const const bool flag = true;
}
```

**Comment by drauch** [comment]
@AdamMaras: Should be consistent with other modifiers though, e.g. readonly (see SO question).
