### ISSUE TITLE
EditorBrowsable(EditorBrowsableState.Never) does not work on parameterized property

### ISSUE THREAD

**Issue by xiafanfan** [dotnet/roslyn#67615]
**Version Used**: 

**Steps to Reproduce**:

1. Create a VB class library project (.Net Framework) "VBProject"
2. Create a C# (.Net Framework) project "CSharpProject"
3. Add IGate.vb into VBProject
```
    Imports System.ComponentModel
    
    Public Interface IGate
        <EditorBrowsable(EditorBrowsableState.Never)>
        Property DontShow(index As Integer) As Integer
    
        <EditorBrowsable(EditorBrowsableState.Never)>
        Property DontShowInt As Integer
    
        Property Show As Integer
    End Interface
```
4. Build the VB project, and reference its VBProject.dll in CSharpProject.
5. Add the below content to the Program.cs of CSharpProject
```
    using VBProject;
    
    namespace CSharpProject
    {
        internal class Program
        {
            static void Main(string[] args)
            {
                var gate = default(IGate);
                gate.set_DontShow(1, 0);
            }
        }
    }
```

**Diagnostic Id**:

-

**Expected Behavior**:
After entering the name of instance ‘gate’ and pressing the “.” key, the property “DontShow” won’t appear in the drop-down list.

**Actual Behavior**:
the property “DontShow” was listed.
![image](https://user-images.githubusercontent.com/45205308/229425612-a9441654-1f3b-45a0-b2bb-5c293abbd7ec.png)

Demo Project [BugDemo.zip](https://github.com/dotnet/roslyn/files/11135248/BugDemo.zip)

**Comment by CyrusNajmabadi** [comment]
If you put this attribute on the setter/getter of the vb property, does this go away?

**Comment by xiafanfan** [comment]
Hi @CyrusNajmabadi, it appears the VB only define the property and does not have the accessors as they are added when the assembly is built. 
![image](https://user-images.githubusercontent.com/45205308/229435203-f31d0267-57aa-4d56-8a82-55286d5eede7.png)

If explicitly adding get/set accessors. Will got the error:
_BC31060	property 'DontShow' implicitly defines 'get_DontShow', which conflicts with a member of the same name in interface._
![image](https://user-images.githubusercontent.com/45205308/229435301-56af4bf8-46fa-4c5d-a73a-74d58608f9ff.png)

Implementing this Interface and then using this new class as a base class did resolve the display issue. But the limitation is each class can have only 1 base class...

```
Public Class GateImplemnt
    Implements IGate
    <EditorBrowsable(EditorBrowsableState.Never)>
    Public Property DontShow(index As Integer) As Integer Implements IGate.DontShow
        <EditorBrowsable(EditorBrowsableState.Never)>
        Get
            Throw New NotImplementedException()
        End Get
        ...
```

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this scenario.
