### ISSUE TITLE
Public API analyzer doesn't remove previous signature when a new API is changed.

### ISSUE THREAD

**Issue by vScottLouvau** [dotnet/roslyn#6762]
I ran into a lot of trouble on my first Roslyn change because I added a new optional argument to a constructor and the Public API Analyzer corrector added the new signature but didn't remove the old one. Since the constructor takes many arguments it was very hard to figure out what had actually happened.

1. Open Roslyn.sln
2. Open src/Compiles/CSharp/Portable/CSharpCompilationOptions.cs
3. Add a new last optional argument to the third constructor. [I added MetadataImportOptions metadataImportOptions = MetadataImportOptions.Public, but you need to make MetadataImportOptions public as well first).

Result:
   Corrector suggests adding the new signature to PublicAPI.Unshipped.txt [Great]
   Corrector DOES NOT remove the existing signature. [Bad]
   Builds fail and you need to manually remove the previous signature.

Expected:
   If a signature changes, the correction should add the new signature and remove the old one.

**Comment by srivatsn** [comment]
Moved to the roslyn-analyzers repo.
