### ISSUE TITLE
Completions in VB method declaration interfere with smart break line

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#67624]
**Version Used**:
17.6 Preview 2

**Steps to Reproduce**:
```vb
Class Program
    $$
End Class
```
Start writing `Sub M(`
When you type `(` closing `)` will be added automatically
When you reach state `Sub M($$)` press Shift + Enter

**Expected Behavior**:
```vb
Class Program
    Sub M()
        $$
    End Sub
End Class
```

**Actual Behavior**:
Since completion list appears when you type `(`, Shift + Enter commit selected completion instead of executing smart break line, even though completion seems to be soft-selected. However, if you close completion list or make it not being invoked at all, smart break line works as expected:
![bug](https://user-images.githubusercontent.com/70431552/229610047-9ecc2b74-3750-4193-bcf7-fda403b95742.gif)
This behaviou is very annoying when you just type method declaration. C# solves this problem by just not treating `(` as completion invocation char:
![devenv_Yh0ViaJY7A](https://user-images.githubusercontent.com/70431552/229610603-92cf1111-1be8-4133-b6f7-765844fdabc4.gif)
I guess, VB can take similar approach for parity between features in both languages

**Comment by CyrusNajmabadi** [comment]
Closing as we are not investing in these scenarios.
