### ISSUE TITLE
Possible bug related to `UnscopedRef` introduced in 7.1.200

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/roslyn#67626]
**Version Used**: 
SDK 7.0.202

Error did not occur in SDK 7.0.1xx

**Steps to Reproduce**:
[SharpLab link with 7.0.2xx compiler](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwAYACDHAOgBEoIBzGAewGcEoBjFygYSYBMApgEEYEFAE8WUFgG5ChMWEEsADhA6DSfGCyYoRq1fIKFYCQQCcxKcjgBs5LKQAqKhIQDehUr9KrLKAA3CAs7RwBldRgAHmAJCwA+UgAxAFcYDhwACgAJfX5Yeh4UCBYWUg44UnMagEofP28CP1bSAHp20gBtHgiADhwAVnsAXVJRUkEADwCVaSYYSogYZgRSYC00lkF+GqWEAAsZSsWLafXNjghtrSh1yAlSNY2tdXLd0iZLcgB2T/ipEsggAZlZBJlBI02n9KpQAEIJQQ6BDQGBWbpQUYIpFyaGkAC+ChafgCwVCWgokWicSRyXSmSweQKRRKZQqVX26ygDRJvmaMN8nVIADkmFNLJZvvjWsCQaQQj9zAB1SwQIxWUgAXiBoLhiIsKLRGKxJkFsJVao1lhxFjxfMJhCJpiIAGYnKR8ihCjBiqVyl58Rh3VEVjEDcizsbLMkI0bYJqtckhCCbigECZnYRg6Q2JY0hx1nGownLIGHd0AKq6DhMVS7ABKoPGOdDsXiSVIEYqSdIKbTGadQA)

[SharpLab link with 7.0.1xx compiler](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSA6AEWwEMBzAOwgGcM2MHyYBhCABMYAQW7tcATz7Y+AbipU5AWxh8ADuzAw647nwi4ZevespVs3DDChzcDUkgbE6AFV0YqAG8qOlC6PShsADd2J3dPAGUDbgAeYAUnAD46ADEAV24wUgAKAAkLCQdOUVx2Pj46MDQ6BwwWgEoQsODKML66AHoBugBtUQSADlIAViQAXTpZOhgECN1lCG5G9m5eNuBjPL4YCRatjAALFUbNpwR9mDB2I+NsNq12BTo9ugPwuuOp2gDAA7Cdfl9YAAzZwwQowLr9UGNJgAIQyMFMGHYDmcI2wczRGLUiLoAF8NL0whForFjIxEsk0hjsvlCsQyhUqjUAY1mq0OqSekjQkM6AA5CDLKBQaCkvrQugxKBnDAAdSg7GszjoAF46IqwESnFicdw8QTbCLka0NVq9M5jborWEKZQ3VRCABmLx0cq4Srcaq1epBUneuhJHYpdEm25m5zZWOY+O4lW67JSKHPXAYWwe6g+gRQPJgNrJ01psNU0IjACqZkgDokACUYFCFhGo6l0lk6MmGhm6Fmc3mqGSgA==)
```cs
using System;
using System.Diagnostics.CodeAnalysis;

namespace ConsoleApp;

internal static class Test
{
    private static Span<byte> Func1(HoldingClass c, int i)
    {
        // [CS8156] An expression cannot be used in this context because it may not be passed or returned by reference
        return c.ByteContainer[i].Bytes;
    }

    private static Span<byte> Func2(HoldingClass c, int i)
    {
        // No error
        ref var intWrapper = ref c.ByteContainer[i];
        return intWrapper.Bytes;
    }
}

public class HoldingClass
{
    public Span<ByteContainer> ByteContainer => default;
}

public struct ByteContainer
{
    [UnscopedRef] public Span<byte> Bytes => default;
}
```

**Expected Behavior**:
Unsure. It seems suspect that the first function errors and the second one doesn't, and I don't see an entry in the [Roslyn breaking changes doc](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md). Then again, the breaking change from #66024 isn't in the doc either.

**Actual Behavior**:
Accessing the `Bytes` property directly via the class results in the error `[CS8156] An expression cannot be used in this context because it may not be passed or returned by reference`. Storing a `ref` to the `ByteContainer` struct in the class as a local ref variable and then accessing `Bytes` via this variable does not cause an error. The compiler versions in 7.0.1xx SDKs do not error and produce the same IL for both functions

**Comment by jcouv** [comment]
Assigned to @jjonescz since he seems to have a fix in the works. Thanks
