### ISSUE TITLE
Extracting method after confirmations does nothing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67647]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Extracting-method-after-confirmations-do/10230774)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.5.0 Preview 1]
I want to extract a method via Ctrl+R, Ctrl+M. A message pops up that not every code branch returns a value. I have the option to cancel the action or do it anyway. But in both cases nothing happens.

[no method extracting.gif](https://aka.ms/dc/file?name=B82a6045be7a7452285b1a4945a402a53638066465726164850_no_method_extracting.gif&tid=82a6045be7a7452285b1a4945a402a53638066465726164850)

---
#### Feedback Bot on 12/15/2022, 08:30 AM: 

(private comment, text removed)
#### Feedback Bot on 12/15/2022, 07:48 PM: 

(private comment, text removed)
#### Feedback Bot on 4/4/2023, 07:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
I was able to repro this with following VB code:

```vb
Private Sub M()
        Dim Foo = False
        For i = 1 To 100
            If Foo Then Continue For ' Select Foo and Press Ctrl+R and Ctrl + M, followed by Yes on the dialog that shows up
        Next
    End Sub
```
