### ISSUE TITLE
`IGeneratorContext.AddSource` throws ArgumentException wrongly claiming invalid filename on linux

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#67653]
**Version Used**: 4.3.0

**Steps to Reproduce**:

```cs
string uniqueFileName = "Formatters.SharedData.DynamicArgumentTupleFormatter<T1, T2, T3, T4, T5, T6, T7, T8, T9>.g.cs";

context.AddSource(CodeAnalysisUtilities.GetSanitizedFileName(uniqueFileName), sb.ToString());

internal static string GetSanitizedFileName(string fileName)
{
    char[] invalidChars = Path.GetInvalidFileNameChars();
    foreach (char c in invalidChars)
    {
        fileName = fileName.Replace(c, '_');
    }

    return fileName;
}
```

**Expected Behavior**: 

I expect the compiler to accept my sanitized filename.

**Actual Behavior**:

My analyzer fails with this error:

> CSC : error CS8785: Generator 'MessagePackGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Formatters.SharedData.DynamicArgumentTupleFormatter<T1, T2, T3, T4, T5, T6, T7, T8, T9>.g.cs' contains an invalid character '<' at position 51. (Parameter 'hintName')' [/home/vsts/work/1/s/sandbox/SharedData/SharedData.csproj]

In fact my code works on Windows just fine, because on Windows, `Path.GetInvalidFileNameChars()` returns an array that includes `<` and `>` characters. But on Linux, where every character except `/` and \\0 is an allowed filename character, `Path.GetInvalidFileNameChars()` (correctly) only returns these two characters. But roslyn apparently has its own ideas, and throws for this filename even though it's actually valid.

My request is that roslyn honor this .NET API when it comes to valid filenames so that roslyn and our source generator do not each have to maintain their own copies of a superset of characters to be disallowed, complete with all the issues of keeping these two extra lists in sync.

**Comment by Youssef1313** [comment]
I think this may trap generator authors into something that work on Linux but not Windows.

Even though allowable characters in file names is OS-dependent, I think having an OS-independent behavior here is desired. (Just my opinion)

**Comment by AArnott** [comment]
I get that argument, but in that case, there should be a new API that returns all the characters that roslyn disallows so I can sanitize my own file names with it. I looked into the source code and Roslyn has a rather lengthy bit of code to decide whether the filename is valid. Surely I shouldn't have to reproduce that in my source generator.

**Comment by jcouv** [comment]
The code is working per current design. The issue/discomfort with Linux vs. Windows seems small enough that we'd likely not prioritize adding such APIs. Rather than moving the issue to Backlog where we'd likely never look at it again, I'll just go ahead and close this.
That said, it would make sense to better document which characters the Roslyn APIs disallow. A PR to improve our API documentation or diagnostic message would be welcome.
