### ISSUE TITLE
Compiler can't find System.Collections.Immutable 6.0.0

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#67668]
Build release/dev17.6-vs-deps
I am on
https://github.com/dotnet/roslyn/commit/78abd4a4a0e5f9fcf55c6ee920d6265f74ff5b5a

Locally I saw a lot of warnings, complaints about can't find System.Collections.Immutable 6.0.0
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/24360909/230293126-48f65395-bff5-4219-afd6-5c25f44d2fc7.png">

Bin log shows it is building Microsoft.CodeAnalysis.UnitTest project.

The command line is 
[commandLine.txt](https://github.com/dotnet/roslyn/files/11167152/commandLine.txt)

**Comment by Cosifne** [comment]
I briefly talked to @RikkiGibson today, and it might relate to https://github.com/dotnet/roslyn/pull/67220
I tried to debug it locally by directly launch csc in VS and build the project using the same argument from msbuild.
But it looks like S.C.I 6.0.0 is loaded correctly, 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/24360909/230294757-e1227c6d-7d40-4441-b99d-3f5369a8d55e.png">

**Comment by Cosifne** [comment]
Tag @jaredpar  ,  I have the binlog, just ping me if you need it (github doesn't allow me to upload it ☹️)

**Comment by RikkiGibson** [comment]
Note that the analyzer load seems to succeed when using a netcore compiler and fail with a netframework compiler.

To debug this make sure you have csc launch configured to use net472.

**Comment by Cosifne** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/24360909/230473102-a7583bec-0dab-49d5-8ee2-0e80e8d444fd.png">
The loaded assembly in net472
