### ISSUE TITLE
[LSP pull diagnostics] Ordering semantics for open document/project processing for background analysis

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#67687]
> could you file an issue saying that we should consider walkign in this order in workspace pull diags.  We have the information about the previous result, so we should be able to add this back in.  Personally, i do think it's a sensible heuristic.  But i am totally ok with it not being deep in the engine, but a policy decision of the system that 'pulls'.

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/67666#discussion_r1160033717_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculatiev.  Note; i believe we already do this.
