### ISSUE TITLE
C# Compiler `csc -langversion:?` cann't run on macOS

### ISSUE THREAD

**Issue by finscn** [dotnet/roslyn#67692]
**Version Used**: 
C# Compiler version 3.9.0-6.21124.20
**Steps to Reproduce**:

1.  run  `csc -langversion:?`  or  `csc /langversion:?`
2.  there is an error message. `no matches found: ?` 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/288367/230578923-de677343-ce45-4e6e-844e-e179cf59d960.png">

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

**Actual Behavior**:

**Comment by svick** [comment]
It seems you need to escape the question mark, so that zsh doesn't treat it as a glob pattern: `csc "-langversion:?"`.
