### ISSUE TITLE
Semantic code snippet can not loop Tab

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67738]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-snippet-can-not-loop-Tab/10334023)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.5.3]
In the old VS version, I could insert code snippets and cycle between placeholders by pressing the Tab key, but after updating the VS version, the behavior has changed.
Here is a comparison of the old and new versions:

Old:
`prop > Tab key x2 > public [int] [MyProperty] { get; set; }` $END$
Then I can toggle between `[int]` and `[Myproproty]` with the `Tab` key until I press `Enter` to submit, Then the cursor stays at the $END$.

New(v17.5.3):
`prop > Tab key x1 > public [int] [MyProperty] { get; set; }` $END$
I only need to press the `Tab` key to insert the code snippet, and when the placeholder is at `[Myproperty]`, if I continue to press the `Tab` key, the placeholder will not go back to `[int]`, but will commit directly, when the cursor stays directly at $END$

I think the inability to loop through placeholders is bad behavior because it doesn't give you a chance to make mistakes.

---
#### Feedback Bot on 4/9/2023, 07:25 PM: 

(private comment, text removed)
#### Feedback Bot on 4/11/2023, 09:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We haven't heard about this from others.  And the behavior of actually doing a final tab to complete and get to typing actually seems like nice behavior.  So going to resolve this as the new intended design.
