### ISSUE TITLE
Incorrect Indentation after inserting prop or ctor semantic snippets (maybe others...)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67740]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-Indentation-after-inserting-pr/10331653)._

---
[severity:It bothers me. A fix would be nice]
In Visual Studio 2022 (Community or Professional, 17.5.3), if I insert a 'prop' snippet, it is incorrectly indented (i.e. I type prop then press TAB):

![image.png](https://aka.ms/dc/image?name=Ba99007173efa445e81214041e8fbba7a638163064119533737_20230405-164651-image.png&tid=a99007173efa445e81214041e8fbba7a638163064119533737)

However, 'propg' is fine:

![image.png](https://aka.ms/dc/image?name=Bd02b6808cf8f4cd687b07b1b8639fb8a638163063681315348_20230405-164607-image.png&tid=d02b6808cf8f4cd687b07b1b8639fb8a638163063681315348)

BUT, if I type prop then TAB then CTRL+Z then TAB, the indentation is correct:

![image.png](https://aka.ms/dc/image?name=B99dca35950534d969c829b4797d0793e638163064974534200_20230405-164817-image.png&tid=99dca35950534d969c829b4797d0793e638163064974534200)

I get a similar issue with the 'ctor' snippet:

![image.png](https://aka.ms/dc/image?name=B54694d8131fb459f9d8cbda9308ff1e5638163066161073824_20230405-165015-image.png&tid=54694d8131fb459f9d8cbda9308ff1e5638163066161073824)

I believe this may have started when I swapped over to Visual Studio 2022, but can't be certain.

I should point out that I have my Text Editor > C# > Tabs set to Tab Size = 2 and Indent Size = 2. I have always used these settings and never had this issue before with prop & ctor in previous versions of Visual Studio.

Any ideas on how this can be fixed would be greatly appreciated!

---
#### Feedback Bot on 4/5/2023, 09:52 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/6/2023, 02:03 AM: 

(private comment, text removed)
#### Michael Holmes on 4/6/2023, 05:00 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/6/2023, 02:12 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/11/2023, 02:59 AM: 

(private comment, text removed)
#### Feedback Bot on 4/11/2023, 09:37 AM: 

(private comment, text removed)
#### Feedback Bot on 4/11/2023, 09:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Not repro'ing this.  The indentation is fine.
