### ISSUE TITLE
Roslyn emits conv.i for nuint conversion

### ISSUE THREAD

**Issue by En3Tho** [dotnet/roslyn#67746]
**Version Used**: 

7.0.104 sdk

**Steps to Reproduce**:

```csharp
    public static nuint TestSpanNuint(ReadOnlySpan<byte> span) => (nuint)span.Length;
    public static nint TestSpanNint(ReadOnlySpan<byte> span) => (nint)span.Length;
```

Results in
```
.method public hidebysig static native unsigned int
    TestSpanNuint(
      valuetype [System.Runtime]System.ReadOnlySpan`1<unsigned int8> span
    ) cil managed
  {
    .maxstack 8

    // [392 67 - 392 85]
    IL_0000: ldarga.s     span
    IL_0002: call         instance int32 valuetype [System.Runtime]System.ReadOnlySpan`1<unsigned int8>::get_Length()
    IL_0007: conv.i
    IL_0008: ret

  } // end of method Issue84564::TestSpanNuint

  .method public hidebysig static native int
    TestSpanNint(
      valuetype [System.Runtime]System.ReadOnlySpan`1<unsigned int8> span
    ) cil managed
  {
    .maxstack 8

    // [393 65 - 393 82]
    IL_0000: ldarga.s     span
    IL_0002: call         instance int32 valuetype [System.Runtime]System.ReadOnlySpan`1<unsigned int8>::get_Length()
    IL_0007: conv.i
    IL_0008: ret

  } // end of method Issue84564::TestSpanNint
```

Is it expected for Roslyn to emit conv.i instead of conv.u in case of nuint cast? Seems like a bug to me.

**Expected Behavior**:

conv.u is emitted

**Actual Behavior**:

conv.i is emitted

**Comment by En3Tho** [comment]
conv.i -> Converts the value on top of the evaluation stack to native int.
conv.u -> Converts the value on top of the evaluation stack to unsigned native int, and extends it to native int.

I don't see why conv.i is used because it feels very wierd especially taking into account this description.

Basically nuint conversion is expected but in fact it's nint and it's improted by jit as nint, not nuint (well, it's quite logical).

**Comment by svick** [comment]
> no matter if it's int or unit on top of the evaluation stack

I believe there's no such thing. The IL evaluation stack only supports a limited number of types, `int32` is among them, but `uint32` is not. [See Table III.8 of the ECMA-335 spec for more details.](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf#page=330)

**Comment by tfenise** [comment]
`conv.u` does unsigned extension, while `conv.i` does signed extension. That's the difference.

**Comment by huoyaoyuan** [comment]
https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQPkGYACNQgYUIG8dCbijl0A2QgVwgHsA7Ac0IBUApgGdgASU7A+7AKoceACjATCADwCUhALwA+QvLZdualQG5qtAsSaE5vQSPGT2AGUOLl6rbvm3jZ7LSE5jSWDMwGPPzCwABySk6ybpzxqho6ehFGpsF0Vsy2USJxElKuCskead6+2dgAvkA=

Both int->ulong and nint->ulong use `conv.i8`. There should be some consistency behind these.

**Comment by En3Tho** [comment]
Interesting. Thank you everyone.
