### ISSUE TITLE
Roslyn IDE is flagging Enum objects in a inheriting c# files as an error.

### ISSUE THREAD

**Issue by kwcoffee1** [dotnet/roslyn#67764]
Hi,

I'm trying to reference a Enum created in the test.dll file.

The Enum "EDKPivotType" was created in the file "PathToMyCompiledScript\test.cs".
The file "test.cs" compile and create the test.dll file OK.

In the code snippet below (which consumes file test.dll) intellisense recognize the enum "EDKPivotType" and it shows all the enum selections associated with it. However, the default editor used to demonstrate RoslynPad 17 (4.4.0) underlines the enum variable EDKPivotType in RED. The error is: CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Nevertheless, intellisence paints this enum with a foreground color of green. Reference to System.Private.CoreLib.dll is embedded in the Roslyn  IDE. 

**Version Used**: 
Although I'm using RoslynPad 17, Version 4.4.0, the Roslyn real-time debugging is mis flagging the enum line.

**Steps to Reproduce**:
Create a CS file with an Enum. Create a second file to consume that enum, like above.

**Expected Behavior**:
The sample script above should compile error free.

**Actual Behavior**:
See opening comment.

Development Package:
RoslynPad 17, 4.4.0
Windows 11
VS 2022 17.5.3

**Diagnostic Id**:
If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).
The error is in the GUI display as stated above. It's a pre-build error during design-time.

Thank you for your time and effort.

**Comment by kwcoffee1** [comment]
Thank you for your quick response. So, for the delay on my part.

You inference is correct. The user dynamically creates a module test.dll to be consumed by another dynamically create module.
The test modules dependences are created and loaded as follows:

    private static string AppPath
    {
       get                                               //** This is how I find the bin folder in the main project to load supporting modules.
        {
            string main = "CoffeeBot_DeskTop"; 
            string dir = Directory.GetCurrentDirectory();
            int i = dir.IndexOf(main) + main.Length;

#if DEBUG
            return Path.Combine(dir.Substring(0, i),
                "CoffeeBot_DeskTop\\bin\\Debug\\net7.0-windows\\");
#else
            return Path.Combine(dir.Substring(0, i),
                "CoffeeBot_DeskTop\\bin\\Release\\net7.0-windows\\");
#endif
        }
    }

    private static IEnumerable<MetadataReference> DefaultReferences()
    {
        // Find the Directory root by one of it's objects.
        var corePath = Path.GetDirectoryName(typeof(object).Assembly.Location) +
                            Path.DirectorySeparatorChar;
        var deskPath = Path.GetDirectoryName(typeof(MessageBox).Assembly.Location) +
                            Path.DirectorySeparatorChar;

        IEnumerable<string> DLLs = new[]
        {
            AppPath + "API.dll",
            AppPath + "Prism.dll",
            AppPath + "Acquisition.dll",
            AppPath + "Infrastructure.dll",
            AppPath + "CoffeeBot_DeskTop.dll",
            AppPath + "Skender.Stock.Indicators.dll",

            corePath + "System.dll",
            corePath + "mscorlib.dll",
            corePath + "System.Core.dll",
            corePath + "System.Linq.dll",
            corePath + "System.Runtime.dll",
            corePath + "Microsoft.CSharp.dll",
            corePath + "System.Reflection.dll",
            corePath + "System.Collections.dll",
            corePath + "System.Globalization.dll",
            corePath + "System.Net.Primitives.dll",
            corePath + "System.Private.CoreLib.dll",        //** Am loading it here this is required
            corePath + "System.Linq.Expressions.dll",
            corePath + "System.Collections.Concurrent.dll",
            corePath + "System.Collections.NonGeneric.dll",
            corePath + "System.Text.RegularExpressions.dll",
            corePath + "System.ComponentModel.Primitives.dll",

            deskPath + "PresentationCore.dll",
            deskPath + "PresentationFramework.dll",
        };

        var References = new List<MetadataReference>();

        foreach (var dll in DLLs)
        {
            References.Add(AssemblyMetadata.CreateFromFile(dll).GetReference());
        };

        return References;
    }

    // Creating these defaults are redundant and are not required
    private static readonly IEnumerable<string> DefaultNamespaces =
        new[]
        {
            "API",
            "System",
            "System.IO",
            "System.Net",
            "System.Linq",
            "System.Text",
            "Prism.Events",
            "Infrastructure",
            "System.Windows",
            "System.Collections",
            "Infrastructure.Enums",
            "Skender.Stock.Indicators",
            "System.Collections.Generic",
            "System.Collections.ObjectModel",
            "System.Text.RegularExpressions",
        };


//****************  I’m compiling as so:

        var compilation = CSharpCompilation.Create(
            codeAssemblyFile,
            syntaxTrees: Trees,
            references: DefaultReferences(),
            options: DefaultCompilationOptions);


I then run roslynpad to create even more modules.  But it appears that the RoslynPad is loading a System.Private.CoreLib.dll from a difference version.

**Comment by kwcoffee1** [comment]
PS: _ use the dll file that's emitted to compilation file codeAssemblyFile.

**Comment by jcouv** [comment]
Thanks for confirming the issue comes from the references given to the compiler. I'll go ahead and close this as there doesn't appear to be a problem with the compiler behavior. Thanks

**Comment by kwcoffee1** [comment]
Thank you for opening the issue with the right ticket tags. I would like to know if a workaround currently exist.
Like, loading the System.Private.CoreLib.dll assembly Roslyn is expecting or tell Roslyn to use the system default assembly location?  Thanks again
