### ISSUE TITLE
Suggested fix to IDE0030 on Nullable Int results in CS0019

### ISSUE THREAD

**Issue by memiamp** [dotnet/roslyn#67770]
**Version Used**: Visual Studio Pro 2022 (64-bit) 17.4.5

**Steps to Reproduce**:

The below code is the simplest way to reproduce this:

    internal class TestClass
    {
        public int? _port;
        public ILogger _logger;

        public void Test()
        {
            _logger.LogInformation("Testing {port}", _port.HasValue ? _port.Value : "default");
        }
    }

In my own code, see IDE0030 is suggested for `_port.HasValue ? _port.Value : "default"`:

![IDE0030 Nullable Int](https://user-images.githubusercontent.com/38524655/231467582-e548aca2-4456-4e98-9719-74c8b7c5f4d6.png)

Implementing the suggested fix results in CS0019:

![CS0019 After IDE0030 Fix](https://user-images.githubusercontent.com/38524655/231467686-5d978311-5d52-4707-9756-881233724ebb.png)

**Diagnostic Id**:

IDE0030 leading to CS0019.

**Expected Behaviour**:

IDE0030 is not a valid suggestion in this context.  It should not be given.

**Actual Behaviour**:

IDE0030 is suggested and must be suppressed.

**Comment by sdelarosbil** [comment]
Hey, I tried to reproduce this, but I can't seem to be able to: it doesn't suggest me this code action,

Is it still a problem?

**Comment by CyrusNajmabadi** [comment]
@sdelarosbil likely not since htat was 17.4  I'll close out.  We can reopen if someone can repro this.
