### ISSUE TITLE
BindingDiagnosticBags should be pooled

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#67785]
An enormous number of these bags are created while binding.  Leading to around 1% of all allocs in typing scenarios:

![image](https://user-images.githubusercontent.com/4564579/231613394-dfef3492-ed8e-4272-95de-1f058335bfcf.png)

Pooling these would help reduce the amount of work spent in the GC (currently at least 15% of process time in the server):

![image](https://user-images.githubusercontent.com/4564579/231613504-f4b19187-4172-4ae6-9d79-9106871a3a90.png)

--

Alternatively, looking at the type, it seems like it might actually benefit from being a ref-struct** that just lives on the stack where needed and which is passed around by-ref.  Currently it is heap allocated so taht it can participate in inheritance (with C# and VB subclasses).  However, neither of hte subclasses actually add any state.  They just add typesafe helper methods for their corresponding languages.  These helpers could be added as extensions in the C#/VB compiler layers.  

** A ref-struct might not work out in practice though due to this type being used in VB.  I don't know where we landed with that.  If ref-structs are not viable, then a normal struct would work as well, we'd just have to be careful with it.

I also see that there's at least one place where this is stored as state (in DecodeWellKnownAttributeArguments).  We'd likely want to change tthat to keep this diagnostics bag something only kept on the stack like everywhere else in the compiler.

**Comment by CyrusNajmabadi** [comment]
@jaredpar ^

**Comment by sharwell** [comment]
> Alternatively, looking at the type, it seems like it might actually benefit from being a ref-struct** that just lives on the stack where needed and which is passed around by-ref.

This isn't strictly needed (`ref struct` artificially restricts usability). Applying `[NonCopyable]` to the type should be sufficient.

**Comment by AlekseyTs** [comment]
Addressed in #68108.
