### ISSUE TITLE
'Convert to interpolated string' should not be offered for C# language version prior to 10.0 if a constant string is required

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#67792]
1. Create a C# project with following source code:
```csharp
using System.Diagnostics;

[DebuggerDisplay("a" + nameof(Class1))]
internal class Class1
{
}
```
2. Edit the project file to add MSBuild property `<LangVersion>9</LangVersion>`, basically any language version prior to 10
3. Put caret in front of "a" and apply the `Convert to interpolated string` refactoring

**Got:**
Refactoring is successfully applied to convert the attribute to `[DebuggerDisplay($"a{nameof(Class1)}")]`, but it introduces a compiler error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8773	Feature 'constant interpolated strings' is not available in C# 9.0. Please use language version 10.0 or greater.	ClassLibrary2	Class1.cs	3	Active
```

**Comment by Youssef1313** [comment]
@mavasani This was done intentionally. Cyrus mentioned that for **refactorings**, we always want to offer regardless of language version.

See also https://github.com/dotnet/roslyn/pull/63593#pullrequestreview-1087787604

**Comment by mavasani** [comment]
Thanks @Youssef1313. Closing as duplicate of https://github.com/dotnet/roslyn/issues/63592
