### ISSUE TITLE
IntelliSense errors in Visual Basic projects when opening Roslyn, even though builds clean

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6779]
Workspace Info: `\\[internalserver]\public\davkean\RoslynWorkspaceInfo.xml`

This is master, I'm sync'd to 6881111661c521688bfdd17740fee1cc7cc94f39.

I've got `36,000 errors.

**Comment by DustinCampbell** [comment]
Moving to analyzers since that's where the work is happening.

**Comment by heejaechang** [comment]
dup to https://github.com/dotnet/roslyn/issues/6809

when intellisense build failed, we should disable full solution analysis
