### ISSUE TITLE
VB.Net "Convert to Full Property" - "New" key word will not move to field

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#67800]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VBNet-Convert-to-Full-Property---New/10337406)._

---
[severity:It bothers me. A fix would be nice]
Refactoring from a property with "New" key word create wrong code. The "New" key word should move to the field declaration. In VS 2019 the refactoring was correct.
![grafik.png](https://aka.ms/dc/image?name=B42b3774cc68a41a6851dd4fa2330f6e5638168965272970441_20230412-134206-grafik.png&tid=42b3774cc68a41a6851dd4fa2330f6e5638168965272970441)

---
#### Feedback Bot on 4/12/2023, 08:30 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this space.
