### ISSUE TITLE
Implement interface through read-only

### ISSUE THREAD

**Issue by xperiandri** [dotnet/roslyn#6782]
In addition to an "Implement interface through" command there must be an "Implement interface through read-only" command which puts `throw new NotSupportedException()` on every member that changes collection.

**Comment by dpoeschl** [comment]
Hi @xperiandri, can you give an example where/how you'd use this? How do you know if a generated implementation would attempt to mutate the readonly object? Only property/indexer setters? Some heuristic based on method names?

**Comment by xperiandri** [comment]
I just meant that I want to implement collection as read-only, for example `IList` could be read-only.
Ti indicate this it must return true in `IsReadOnly` property and throw NotSupportedException in methods `Add`, `Remove`, setter of index, etc.

**Comment by CyrusNajmabadi** [comment]
Closing out.  As per last design meeting, given the niche nature of the request, this is out of scope for the implement-interface feature.
