### ISSUE TITLE
Unable to Debug an Roslyn Diagnostics

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6784]
I'm having trouble getting VS2015 RTM to install my diagnostic into the Experimental instance, so that I can debug it.

The Error List contains the following Severity
```
AD1002  Unable to load Analyzer assembly   C:\USERS\ADAM\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0ROSLYN\EXTENSIONS\ADAM\FSDVBANALYSER.VSIX\1.0.2\FSDVBAnalyser.dll
Could not load file or assembly 'FSDVBAnalyser, Version=1.0.5795.13535, Culture=neutral, PublicKeyToken=null' or one of its dependencies.  
The system cannot find the file specified.
The project is available Here.
```
How can it get it work?

VS Version information
```
Microsoft Visual Studio Community 2015 Version 14.0.24627.00 Update 1 RC Microsoft .NET Framework Version 4.6.01040

Installed Version: Community

Visual Basic 2015 RC 00322-20000-00000-AA613 Microsoft Visual Basic 2015 RC

Visual C# 2015 RC 00322-20000-00000-AA613 Microsoft Visual C# 2015 RC
```

[Link To Gist of ActivityLog.xml](https://gist.github.com/AdamSpeight2008/40c21f31b9eee94bd23d)
[Link To Stackoverflow](http://stackoverflow.com/questions/33700092/unable-to-debug-any-roslyn-diagnostic)

**Comment by dbolkensteyn** [comment]
Has this been fixed recently? I'm seeing the same issue when installing the development version of the VSIX of SonarLint for Visual Studio 1.5.0 on the publicly released Visual Studio 2015 Update 1 RC.

However, this issue doesn't seem to appear anymore on a later build of Visual Studio 2015 Update 1.

```
Warning	AD1002	Unable to load Analyzer assembly C:\USERS\DINESH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\E044KJ0P.JDC\SonarLint.CSharp.dll: Could not load file or assembly 'SonarLint.CSharp, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

**Comment by dbolkensteyn** [comment]
Update: I could reproduce this with the publicly available RC of Visual Studio 2015 Community Update 1 RC, but not with Enterprise Update 1 RC. cc @srivatsn

**Comment by srivatsn** [comment]
There was a bug in the RC of Update 1 that caused VSIX-based analyzers to fail to load. This has been fixed since. Nuget analyzers will work in RC.

**Comment by srivatsn** [comment]
The original report is also in update 1 RC and this issue has been fixed now.
