### ISSUE TITLE
VB incorrectly reports overflow for negative integer literals

### ISSUE THREAD

**Issue by Giftednewt** [dotnet/roslyn#6785]
![incorrectoverflow](https://cloud.githubusercontent.com/assets/7267084/11165750/c7fc566c-8b10-11e5-93b5-7749b73b1c15.png)

VB is incorrectly reporting overflow for negative integer literals. This happens in both VS2013 and VS2015. I took the screenshot below from VS2015. Looks like the literal is being treated as positive for the diagnostic to return an overflow.

**Comment by gafter** [comment]
The literal *is* positive. The minus sign is not part of the literal, it is a separate operator.

**Comment by AdamSpeight2008** [comment]
In theory it could be include the sign operator, just requires the analysis to be moved higher up.

**Comment by gafter** [comment]
@AdamSpeight2008 What change, exactly, are you proposing to make to the language specification?

**Comment by AdamSpeight2008** [comment]
@gafter
 I'm not advocating a change to the specification but moving where we do the overflow / underflow analysis. Thus the reporting of the overflow out the parser / scanner, to somewhere where we also have the surrounding context. eg Is this numeric literal preceded by a uniary minus operator? 
Before declaring it is an overflow / underflow.  

To the user it looks like a negative number, not a positive number preceded by a minus operator.
That way the squiggle could include the minus operator. (or the also valid case of the positive unary operator).

**Comment by AdamSpeight2008** [comment]
@gafter 
The error is that the reported overflow, isn't an overflow, The values in original post are the `.MinValue`'s for those type. Since were using Two's complement representation, the absolute value for the `.MinValue` is greater than the `,MaxValue`
`Abs(Int16.MinValue) - Int16.MaxValue = 1`

**Comment by gafter** [comment]
@AdamSpeight2008 No, thank you, we will not violate the requirements of the VB language specification by taking your suggestion. The positive numeric literal that appears after the unary negation operator is not representable in its type and an error is required by the specification. Without a change to the specification an error is required.

> 2.4.2 Integer Literals
Integer literals can be decimal (base 10), hexadecimal (base 16), or octal (base 8). A decimal integer literal is a string of decimal digits (0-9). A hexadecimal literal is &H followed by a string of hexadecimal digits (0-9, A-F). An octal literal is &O followed by a string of octal digits (0-7). Decimal literals directly represent the decimal value of the integral literal, whereas octal and hexadecimal literals represent the binary value of the integer literal (thus, &H8000S is –32768, not an overflow error).
> 
The type of a literal is determined by its value or by the following type character. If no type character is specified, values in the range of the Integer type are typed as Integer; values outside the range for Integer are typed as Long. If an integer literal's type is of insufficient size to hold the integer literal, a compile-time error results.

**Comment by gafter** [comment]
@Giftednewt Not wasted time at all, just ammo for a C# version of [Java Puzzlers](http://www.amazon.com/Java-Puzzlers-Traps-Pitfalls-Corner/dp/032133678X).
