### ISSUE TITLE
Simplifier.ReduceAsync reduces default expression removing relevant type arguments

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#67867]
**Version Used**: 
4.5.0, 4.6.0-2.23177.13

**Steps to Reproduce**:

1. Pass the [following](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4wmApgZwA4QDGWABAGID2FAsAFADedJzJAAgMwkEBOALlBAA2bAEwkAgkxaNaLOW07iAFJQoA6AJIISUBHDYBGACxrWB9gB5VagCIA+Egix4cAShL0SAXynyFEpTM1AGVeblgAcxIcfWsANRIAN3dPH1kWNLkOLgg+AWFWMQAhEhByKjVJdOYZP2ZsoqV3MuAIHCwlJwAzCABXQV4VCq1XAEJ9br6BwONTcysK+zGU719V6v8efiFREhsPdazOLfzdrQPMlmyTncKSBNS6LyA===) to `Simplifier.Reduce`
```c#
    namespace Foo
    {
        public partial class A
        {
            public A(Foo.Id id, System.Collections.Generic.IEnumerable<Foo.D> deps) { }
            public A(System.String s, Foo.V v) { }
        }
        public partial class B : Foo.A
        {
            public B() : base(default(Foo.Id)!, default(System.Collections.Generic.IEnumerable<Foo.D>)!) { }
        }
        public partial class D { }
        public partial class Id { }
        public partial class V { }
    }
```
2.  Observe that the base call is [incorrectly reduced](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4wmApgZwA4QDGWABAGID2FAsAFADedJzJAAgMwkEBOALlBAA2bAEwkAgkxaNaLOW07iAFAEkEJKAjhsAjABYAdKx3sAPABEAfCQRY8OAJQl6JAL5T5CiUuMGAyrzcsADmJDjaAGokAG5OLu6yLAlyHFwQfALCrGIAQiQgEh7ORSmcOUpOBcAQOFhKtgBmEACugrwAhNqNLW3tcW5FySypPPxCoiTmzgOJzCPpY1liatNDc5yjmRNR8XSuQA=) to `base(default!, default!)` which fails to compile with 
```
error CS0121: The call is ambiguous between the following methods or properties: 'A.A(Id, IEnumerable<D>)' and 'A.A(string, V)'
```

Here's a repro project that demonstrates the bug: 
[reduceTest.zip](https://github.com/dotnet/roslyn/files/11266691/reduceTest.zip)

Running that will emit the buggy result.

**Expected Behavior**:
Simplifier.Reduce does not simplify the default expressions since those are relevant when determining which base constructor call.

**Actual Behavior**:
Simplifier.Reduce removes type arguments, which results in code that no longer compiles with error `CS0121`

**Comment by CyrusNajmabadi** [comment]
I can look into this.
