### ISSUE TITLE
Code folding in Razor markup does not fold #region

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/roslyn#67874]
## Summary
#region directives do not collapse in Razor and there are no "+/-" symbols to the left. Linked issue: https://github.com/dotnet/aspnetcore/issues/13109#issuecomment-544168002

Razor:
![image](https://user-images.githubusercontent.com/57046415/233042263-ec3b517f-7b9e-414a-9e83-45f3848bfa3c.png)

Code:
![image](https://user-images.githubusercontent.com/57046415/233042807-51439937-600e-4a77-bf87-932bb05e5cf0.png)

## Background and Motivation

Same behaviour as in the code.

## Proposed Feature

Please add this feature so the user experience is the same as in the code.

## Alternative Designs

N/A

**Comment by Bulzi-Robb** [comment]
This use to work and is now broken.
Will it get fixed in future version?

**Comment by arkalyanms** [comment]
The roslyn feature request should be tracked by https://github.com/dotnet/roslyn/issues/40122. There may be some razor hookups needed as well?

**Comment by arkalyanms** [comment]
Marking dup of https://github.com/dotnet/roslyn/issues/40122. If that does not cover razor, we can open a related one.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is razor.  This should be reported to them.
