### ISSUE TITLE
Refactoring: Implement constructor body

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6787]
Today we have "generate constructor" where you highlight properties/fields and we offer to generate a constructor that accepts values for and populates those members, and we also have Generate Method which has custom constructor handling of assigning the parameters to fields. We should offer another variation -- the user writes an empty constructor definition and we offer to generate the backing fields and constructor body. 

The only way to have it generate this boilerplate such that the constructor's parameters are in the desired order is to create a call to the to-be-generated constructor, which is not always convenient.

(From a conversation with @matthejo)

**Comment by Pilchie** [comment]
@dpoeschl Do you think @CyrusNajmabadi new fixes around adding fields for parameters and null checks covers this?

**Comment by dpoeschl** [comment]
Probably, yes. I'll run through it with @matthejo to confirm.

**Comment by CyrusNajmabadi** [comment]
This is available now:

![image](https://user-images.githubusercontent.com/4564579/75635646-ac46d280-5bcc-11ea-86e6-40fddcc26d52.png)

as well as:

![image](https://user-images.githubusercontent.com/4564579/75635654-b799fe00-5bcc-11ea-93aa-240d61703521.png)
