### ISSUE TITLE
Proposal: Pattern-based exception-handling

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6789]
Since `catch` already has an optional "exception filter", I think it would be reasonable to use patterns also in `catch` clauses.

> _specific-catch-clause:_
> &emsp;`catch` `(` _complex-pattern_ `)` _exception-filter_<sub>opt</sub> _block_

All patterns must be _pattern compatible_ with the type `Exception`.

``` cs
try { ... }
catch (WebException { Status is WebExceptionStatus.Timeout } ex) { ... }
```

Instead of

``` cs
try { ... }
catch (WebException ex) when (ex.Status == WebExceptionStatus.Timeout) { ... }
```

If you declare exceptions using record syntax, then you will be able to use _recursive-pattern_:

``` cs
class FooException(Status status) : Exception();
catch (FooException(Status.Timeout)) { ... }
```

With OR patterns (#6235) one should be able to check for multiple exceptions without exception filters.

**Comment by stepanbenes** [comment]
http://tomasp.net/blog/2015/csharp-pattern-matching/

**Comment by alrz** [comment]
@stepanbenes Yeah I know.

**Comment by gafter** [comment]
As you have currently specified them, OR patterns require pattern variables to be of the same type on both sides of the disjunction, so using them to catch multiple types is not easy.

**Comment by alrz** [comment]
@gafter I don't know if OR patterns could use the "most common type" rule? (that would be really nice, by the way) However if they could, still, you have to repeat the pattern variable for each exception like `catch(E1 ex or E2 ex)`, and the fact that the *identifier* in "type patterns" isn't optional makes this not *that* friendly. As an alternative approach, I think "type intersections" as a general feature would be useful also in this context, `catch(E1 & E2)` using the regular *specific-catch-clause*, but in that case if you want to declare a variable, a pair of parentheses would be needed I presume e.g. `catch((E1 & E2) ex)` which is not that bad. I don't know which approach would be more adoptable to make this possible.

**Comment by gafter** [comment]
@alrz if we used the existing dominant type rules, one of the two types would be required to be a subtype of the other. I do not think you would like that.

I think you meant disjunctive, not conjunctive types, as it is only one or the other at any given time. When I did it for Java I used `|`.

**Comment by alrz** [comment]
@gafter "one of the two types would be required to be a subtype of the **other**" I'm not sure if you're talking about OR patterns or type intersections, either way, why is that? I thought the "most common type" would be the "common" base type, so for example, in
```
(NullReferenceException | InvalidCastException) ex
```
I would expect the variable `ex` to be a `SystemException`.

**Comment by alrz** [comment]
Oh I just realized, `catch` then wouldn't work as expected. So I would go with patterns.

**Comment by gafter** [comment]
When I specified and implemented this for [Java](http://docs.oracle.com/javase/tutorial/essential/exceptions/catch.html), you would write

```java
try {
    ...
} catch (NullReferenceException | InvalidCastException ex) {
    ...
}
```

The type specified in the catch clause can be thought of as a disjunction type. The compiler would emit code to catch precisely those two exception types, and the type of the variable `ex` within the catch block is a type whose member set is precisely those members that are common to both types.

That works in Java because
- The "common base type" algorithm is capable of selecting a base type, and
- The idea of compiling by erasure is well established in the language., and
- We make the exception parameter `readonly` so as to avoid specifying too much about the meaning of disjunction types

C#'s "common type" algorithm (as currently specified) never produces a type that is not one of the input types.

**Comment by alrz** [comment]
With the syntax proposed in [#206 (comment)](https://github.com/dotnet/roslyn/issues/206#issuecomment-158500816), with a *complex-pattern* this can trasparently replace the current *specific-catch-clause*, so the following would be possible
```cs
catch(WebException)
catch(WebException ex)
catch(WebException or SystemException)
catch(WebException e or SystemException e)
```
Although, the last one probably requires #6814 or #4586.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #335](https://github.com/dotnet/csharplang/issues/335) via [**ZenHub**](https://www.zenhub.com/)
