### ISSUE TITLE
SyntaxGenerator doesn't remove the WriteOnly modifier for a property when it adds a getter.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#679]
If you have code like this:

```VB.NET
    Public WriteOnly Property Name() As String
        Set
            m_name = value
        End Set
    End Property
```

Try adding a getter to this property like so:

```csharp
    generator.WithGetAccessorStatements(propertyDeclaration, null);
```

**Actual**:
```VB.NET
              Public WriteOnly Property Name() As String
                  Set
                      m_name = value
                  End Set
                  Get
                  End Get
              End Property
```

**Expected**:
```VB.NET
              Public Property Name() As String
                  Get
                  End Get
                   Set
                      m_name = value
                  End Set
             End Property
```

i.e with the WriteOnly modifier removed and the getter above the setter. Note that the getter being added below the setter is the behavior in C# as well.

**Comment by mattwar** [comment]
Yep.  The modifiers enum doesn't even have a representation of WriteOnly.

**Comment by srivatsn** [comment]
f1bb6ff adds the writeonly modifiers. Simply calling WithGetAccessors doesn't remove the WriteOnly modifier but that is probably better behavior to keep the SyntaxGenerator agnostic of semantics. Assigning to myself for verification.
