### ISSUE TITLE
Pattern-captured variable has a wrong value in C# 11 

### ISSUE THREAD

**Issue by hrumhurum** [dotnet/roslyn#67923]
**Version Used**: 

C# 11
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.5.4

**Steps to Reproduce**:

Consider the following C# code:

```c#
class A { }
class B : A { }
class C : A { }
class D : A { }

class Program
{
    static void Main(string[] args)
    {
        A foo = new B();

        if (foo is (B or C) and var x)
        {
            if (x is null)
                Console.WriteLine("NOK");
            else
                Console.WriteLine("OK");
        }
        else
        {
            Console.WriteLine("Inconclusive");
        }
    }
}
```

The corresponding SharpLab snippet is [here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHjAAgEFCBvQgXwPUICFCQTyqbCBhR5i63IgES6keeNqkwB2PGTyE5hcQDYFAFkIBZAIYBLKAApxABgDaAXUKawAcwDOASlnyZuea+YAzAPafCAXkJQAKYA7vR6dgDcoi5uctruhHpePto2iQyeYBx2FlBwhABuloQAHg4xsc6xsfGJJYSpARAANs3l1R0KmACcegBEAHIA8gDSfZGOnYSBzTaBk1Py4r19o+NRFW68HTNzC65Vi8v9AJJQAMaeF80QNtoFgev78tsveLxAA).

**Expected Behavior**:

- The program output is "OK".

**Actual Behavior**:

- The program output is "NOK".

**Additional Notes**:

Interestingly, the code with a simple pattern produces the correct output:

```c#
class A { }
class B : A { }
class C : A { }
class D : A { }

class Program
{
    static void Main(string[] args)
    {
        A foo = new B();

        if (foo is B and var x)
        {
            if (x is null)
                Console.WriteLine("NOK");
            else
                Console.WriteLine("OK");
        }
        else
        {
            Console.WriteLine("Inconclusive");
        }
    }
}
```

The corresponding SharpLab snippet is [here](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUHjAAgEFCBvQgXwPUICFCQTyqbCBhR5i63IgES6keeNqkwB2PGTyE5hcQDYFAFkIBZAIYBLKAApxABgDaAXUKawAcwDOASlnyZuea+YAzAPafCAXkJQAKYA7vR6dgDcoi5uctruhHpePto29BZQcIQAbpaEAB4OMbHOsbHxifmEqQEQADZ1RWXNCpgAnHoARAByAPIA0p2Rji2EgXU2gSOj8uIdnQNDUcVuvM3jk9OupTNzXQCSUADGnsd1EDba2YFLW/Jr93i8QA===).

**Comment by RikkiGibson** [comment]
It would be useful to know if the issue repros in the current VS preview.

**Comment by hrumhurum** [comment]
> It would be useful to know if the issue repros in the current VS preview.

**Testing with:**

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 4.0

**Result:**

The bug is not reproducible with VS version 17.6.0 Preview 4.0: the program produces the correct result. It looks like the issue has been fixed already.

**Comment by jcouv** [comment]
Added a test verifying the fixed behavior
