### ISSUE TITLE
Inadvertent source breaking API change when using CSharp or VB CompilationOptions from 1.0->1.1

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#6792]
Unfortunately, it looks like when we added some compilation options for 1.1, we did so in a way which is source incompatible with 1.0. Specifically, we added a new optional parameter `bool deterministic` about halfway through the constructor for the CSharp and VisualBasicCompilation options.

To demonstrate why this is an issue, consider the API

```csharp
void M(A, [B], [C], [D])
```

where the `[]` indicate optional parameters. If one were to add an additional optional parameter

```csharp
void M(A, [B], [E], [C], [D])
```

then all calls `M(a, b, c)` would fail, since they rely on the third positional parameter of being of type `C`, but it has changed to be of type `E`.

We've also added a constructor

```csharp
void M(A, F, [B], [C], [D])
```

In this case, I don't believe this is a source or metadata breaking change, but it makes maintenance very difficult since there is no way to add the `F` parameter to the first constructor without making a source breaking change (because named parameter calls would now be ambiguous), so all subsequent parameters added to the first constructor would now need to be added to the second constructor.

If possible, we should consider remedying this in 1.1 by moving the added optional parameter to the back, preventing a source breaking change, and remove the second overload entirely, moving the additional parameter to be another optional parameter at the end of the first constructor, reducing confusing and maintenance costs. This recommendation is simply based on applying the rules listed in https://github.com/dotnet/roslyn/blob/e8fdb391703dcb5712ff6a5b83d768d784cba4cf/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md

**Comment by gafter** [comment]
@jaredpar

**Comment by Pilchie** [comment]
We decided to live with the very small source only breaking change in this case.

**Comment by paulomorgado** [comment]
And that's why optional arguments should no be used in public/published APIs.

**Comment by gafter** [comment]
@paulomorgado Because sometimes engineers make errors?

**Comment by agocke** [comment]
@paulomorgado Note that not using `optional`s would not have prevented the second issue I mentioned which, in my opinion, is even worse because it produces an ongoing maintenance burden.

**Comment by paulomorgado** [comment]
@gafter, and using optional arguments should no be used in public/published APIs is one of them.

@agocke, at some point, the number of arguments becomes unmanageable. Sometimes it can be worked around by using named arguments. But named arguments have their problems too (a refactoring can break client code).In the end, the best solution that I know is a settings type like [XmlReaderSettings](http://referencesource.microsoft.com/System.Xml/R/cb30a8c80b6c7ba8.html) and [XmlWriterSettings](http://referencesource.microsoft.com/System.Xml/R/ff9751984c5b1c38.html).

**Comment by jaredpar** [comment]
@paulomorgado the number of arguments can become unmanageable.  A great example of that is our compilation option constructors.  Updating those is indeed a painful process.  In retrospect I wonder if we would have been better off having parameterless constructors and building up instances through the fluent `With` methods.  

But those methods are very much the exception in our code base.  The majority use case are methods with a manageable number of parameters, only a few of which are optional.  The increased usability of these methods far outweighs the minor nuisance that occurs when we add an overload (which itself is a very rare event).
