### ISSUE TITLE
Two solutions for IDE0004 Cast is redundant suggested, but no preference expressed.

### ISSUE THREAD

**Issue by martineyles** [dotnet/roslyn#6793]
To send a nullable int to a SQL database it must been unboxed, cast to object and have null values replaced with DBNull. I created a method to do this in a data access object:

    public object SQLNullableObject(int? input)
    {
        return input.HasValue ? (object)input.Value : (object)DBNull.Value;
    }

The compiler shows to suggestions that the cast to object is not required. Both of these fixes appear valid on their own. Applying one removes the other auto-fix, as in both cases this would break the code, as the if statement has to give only one type of output.

Perhaps only one of these changes should be suggested, though I don't know which would be considered the better change if any, or perhaps neither should be suggested for the sake of code clarity.

**Comment by dpoeschl** [comment]
In *general*, it's a difficult problem to handle codefixes removing other diagnostics. Remove full qualification of ```System.Console``` and now your ```using System;``` isn't unnecessary (or vice versa). There's probably lots of examples. We don't have a communication mechanism between analyzers (or between analyzers & fixes) to coordinate this kind of thing in the general sense, and it becomes even more difficult when you have analyzers & fixes from different sources that may compete to fix a problem in different, mutually exclusive ways.

In this *particular* instance, perhaps we could have an option about not marking this particular brand of casts (```?:``` and ```??```, maybe other scenarios...) as redundant if they are to the same type, as such code was probably written for clarity purposes?

**Comment by DustinCampbell** [comment]
Thanks for reporting the issue. The intent of the feature is to report redundant casts, which it is correctly does. In this case, both casts are redundant until one is removed. So, at the moment, this is working as designed. I'm not sure an option is warranted -- it seems pretty low value.

If you have code where you don't wish Remove Unnecessary Cast to be reported, you could simply disable the warning using `#pragma warning disable IDE0004`.
