### ISSUE TITLE
"View in Object Browser" seems to be missing

### ISSUE THREAD

**Issue by MV10** [dotnet/roslyn#67938]
I'm opening this here because #24085 indicates "View in Object Browser" is a language-service feature.

I never see this context menu item anywhere. The old issue referenced above is about the Solution window, and I know there are many issues about using it with NuGet and Framework dependencies, but VS used to also show this option when right-clicking things in code (and for whatever it's worth, I haven't _ever_ personally seen it anywhere outside source code windows). It has been gone so long, I can't even remember which version last had it -- perhaps VS2008? 2010? It has been sorely missed. I used it heavily since I work on many projects originally written by others.

Should I still see this in VS2022, or was this intentionally removed? Is there a way to get it back? 

If not, can this be treated as a feature-request to bring it back?

**Comment by mavasani** [comment]
@jasonmalinowski do you have any historical background here?

**Comment by MV10** [comment]
No, ages ago you could do that from the _source_ editor...

**Comment by jasonmalinowski** [comment]
@MV10: there is this setting which maybe you're thinking of?

<img width="587" alt="image" src="https://github.com/dotnet/roslyn/assets/201340/0ad2e725-8381-47f6-9cac-e02a40e7cba2">

Looks like we only expose that for VB.NET; any chance you're remembering that behavior?

**Comment by MV10** [comment]
Perhaps. I used VB6 a lot back in the day (even did some stints with MS at Redmond and Bellvue), but there was probably overlap with the earliest C# / .NET days, although at that time I was distracted by web stuff, hard to say.

I guess at this point it makes the most sense as a feature request...?

**Comment by jasonmalinowski** [comment]
@MV10: yep, probably a feature request!

**Comment by MV10** [comment]
Or ... time for me to write an Extension. :) 

thanks!

**Comment by CyrusNajmabadi** [comment]
We are not investing in object browser scenarios anymore.
