### ISSUE TITLE
[return: NotNullIfNotNull(nameof(arg))] should apply to T with async Task<T> methods

### ISSUE THREAD

**Issue by wiz0u** [dotnet/roslyn#67939]
```
[return: NotNullIfNotNull(nameof(arg))]
private async Task<ReturnType> MyMethod(AClass arg)
```
The analyzer seems to consider the returned Task itself should not be null if arg is not null.
As the method is implemented with `async`, it will always return a valid Task, and that attribute should rather apply to the ReturnType returned value

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/csharplang/discussions/2793
https://github.com/dotnet/csharplang/discussions/4994

**Comment by RikkiGibson** [comment]
Solution here will most likely come through RequireAwait described in https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-01-18.md#nullable-post-conditions-and-asyncawait.

**Comment by CyrusNajmabadi** [comment]
I don't see how this is analyzer or ide.  this appears to be compiler/lang.

**Comment by jaredpar** [comment]
Closing as this is more of a language issue than compiler and there are existing language issues tracking this.
