### ISSUE TITLE
Tracking issue on license/cla failures

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#67965]
Many PRs are getting stuck on the license/CLA check.  Enabling / disabling auto-merge may kick the check to finally run, but otherwise the only solution is to close / re-open the PR or push a change which is not good as it causes all checks to re-run. 

This issue tracks PRs that have hit the problem so we have evidence to report back to core engineering.

https://github.com/dotnet/roslyn/pull/67922

**Comment by genlu** [comment]
I hit this in https://github.com/dotnet/roslyn/pull/67947. But was able to resolve it by disable auto-merge.
