### ISSUE TITLE
A possible opportunity for optimization in ImmutableArrayExtensions.GetTypesFromMemberMap

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#67991]
https://github.com/dotnet/roslyn/blob/7c23c2ec0da28827077fc710efeac97c07ec443b/src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs#L971-L995

It looks like ```members.As<TNamedTypeSymbol>()``` can be used to quickly detect a situation when ```hasType is true && hasNamespace is false```

**Comment by jcouv** [comment]
Assigned to @CyrusNajmabadi since he already has a fix in the works.
