### ISSUE TITLE
An opportunity for optimization in ImmutableArrayExtensions.CreateNameToMembersMap

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#67990]
https://github.com/dotnet/roslyn/blob/7c23c2ec0da28827077fc710efeac97c07ec443b/src/Compilers/Core/Portable/Collections/ImmutableArrayExtensions.cs#L934-L938

One branch could do ```builder.ToImmutableAndFree()```, which would allow for the optimization of moving the internal array to the immutable array without a copy.

**Comment by jcouv** [comment]
Assigned to @CyrusNajmabadi since he already has a fix in review.
