### ISSUE TITLE
Using the VB.NET NameOf operator with an event name doesn't work unless used within the same class

### ISSUE THREAD

**Issue by adegeo** [dotnet/roslyn#68004]
The `NameOf` operator only resolves events when used within the same class. For example, when declaring an attribute on a class (or just really referencing the event outside the class) that uses the event name, it can't resolve and is a compile error.

```vb
Imports System.ComponentModel

<DefaultEvent(NameOf(TextChanged))>  ' Compiler error BC30451: Name '<name>' is not declared
Public Class UserControl1

    <Browsable(True)>
    Public Shadows Custom Event TextChanged As EventHandler
        AddHandler(value As EventHandler)
            AddHandler txtValue.TextChanged, value
        End AddHandler
        RemoveHandler(value As EventHandler)
            RemoveHandler txtValue.TextChanged, value
        End RemoveHandler
        RaiseEvent(sender As Object, e As EventArgs)

        End RaiseEvent
    End Event

End Class
```

If you move `NameOf` inside the class in any code, it works fine.

This is different from C# where you can use `nameof(eventName)` anywhere.

Visual Studio 2022 Version 17.6.0 Preview 5.0
TFM: net7.0-windows

**Comment by adegeo** [comment]
@KlausLoeffelmann @KathleenDollard 

While the intellisense naturally excludes events where you can't use them, and includes events where you can (such as with `AddHandler`) the `NameOf` operator shouldn't use any filtering at all.

**Comment by jcouv** [comment]
I believe this is by-design (the nested member is not in scope at the location). The scopes for attributes and nameof may not be the same between VB and C#.

Two observations:
1. you'd get the same diagnostic with any kind of member. Here's an example with a nested type:
```vb
Imports System.ComponentModel

<DefaultEvent(NameOf(Nested))>  ' error BC30451: 'Nested' is not declared. It may be inaccessible due to its protection level.
Public Class UserControl1
    Public Class Nested
    End Class
End Class
```
2. The code compiles fine if you qualify the access to the member with the containing type: `<DefaultEvent(NameOf(UserControl1.TextChanged))>`
