### ISSUE TITLE
VS2022 TODO items in Task List not being updated

### ISSUE THREAD

**Issue by MV10** [dotnet/roslyn#68001]
VS2022 Community v17.5.4

I created a project with five or six TODO comments. These were shown in the Task List as expected, but as I worked and made changes (removing the TODO comments), the Task List was not updated. If I double-click one, it takes me to the line where it used to be. Closing VS completely and reloading VS and the solution corrects the Task List.

In terms of reproducing it, I doubt git activity is related but I'll mention it anyway. I pushed the project up to github, made a branch, worked on a couple of the TODO items, deleted the TODO comments, pushed those, then merged and pulled. The change branch was deleted both locally and remotely. Now in the master branch again, the code is correct (TODO comments are gone) but the Task List still shows them. 

If a reproduction will help, see my project [UPSMonitor](https://github.com/MV10/UPSMonitor)... There was just the original push, then the "async" branch, then one PR/merge and cleanup (in case there is more activity by the time you look). I guess you could look at the history: the original push of Program.cs and Notify.cs have the comments that were removed.

I did notice a similar sounding report in #43309 from a few years ago (closed as fixed). I have not seen any crashes so far, which that other person mentioned.

**Comment by CyrusNajmabadi** [comment]
This system was effectively rewritten between 17.5 and 17.7.  Can you try on latest previews and let us know if you're still having these issues?

**Comment by MV10** [comment]
@CyrusNajmabadi the preview can be installed side-by-side with the release version?

Been awhile since I ran a preview. But if so, I'll give it a shot.

**Comment by MV10** [comment]
Closing ... Works as expected in the preview. Thanks man!
