### ISSUE TITLE
Support defining aliases for generic definition types.

### ISSUE THREAD

**Issue by Dogwei** [dotnet/roslyn#68013]
I've heard that C#12 will improve type aliases, so here's my opinion:
I hope to support defining aliases for generic definition types, example:

```C#
 using Map<TKey, TValue> = System.Collections.Generic.Dictionary<TKey, TValue>;
 using IntegerMap<TValue> = System.Collections.Generic.Dictionary<int, TValue>;
```

If this feature is available, it will be more convenient to rewrite code from other languages into C#.
And it can also solve the problem of generic definition type name conflicts.

**Comment by ufcpp** [comment]
see https://github.com/dotnet/csharplang/pull/4452

**Comment by jcouv** [comment]
Closing in favor of https://github.com/dotnet/csharplang/pull/4452 which already tracks this feature request.
