### ISSUE TITLE
Bug using auto-properties in record structs?

### ISSUE THREAD

**Issue by SommerEngineering** [dotnet/roslyn#68017]
### Description

I have created a data structure, here is a simplified example:

```
public readonly record struct MetaData(string Name)
{
	public string Id { get; } = Guid.NewGuid().ToString();
}
```

Next, I create some instances:

```
var m1 = new MetaData() { Name = "Test" };
var m2 = new MetaData("Test");
var m3 = new MetaData();
var m4 = new MetaData("a") { Name = "Test" };
```

Now, I want to use the `Id` property 😜...

- `m1.Id` returns `null` 😲
- `m2.Id` returns a random `Guid` as `string` 😀
- `m3.Id` returns `null` 🤷‍♂️
- `m4.Id` returns a random `Guid` as `string` as well...

### Reproduction Steps

The record:
```
public readonly record struct MetaData(string Name)
{
	public string Id { get; } = Guid.NewGuid().ToString();
}
```

Create some values:
```
var m1 = new MetaData() { Name = "Test" };
var m2 = new MetaData("Test");
var m3 = new MetaData();
var m4 = new MetaData("a") { Name = "Test" };
```

Read the id:
```
Console.WriteLine($"m1.Id={m1.Id}");
Console.WriteLine($"m2.Id={m2.Id}");
Console.WriteLine($"m3.Id={m3.Id}");
Console.WriteLine($"m4.Id={m4.Id}");
```

### Expected behavior

I expect a random `Guid` as `string` to be returned in all four cases. After all, I have specified an auto property with default value. What could go wrong here 🤷‍♂️?

### Actual behavior

- `m1.Id` returns `null`. How is this possible? The specified default value were not applied to my auto-property.
- `m2.Id` returns a random `Guid` as `string`. Thats fine.
- `m3.Id` return `null`. I ask myself, again, how this could be the case...
- `m4.Id` returns a random `Guid` as `string` as well...

### Regression?

No, I tested it using .NET 6, 7, and 8 preview 3.

### Known Workarounds

Using a variant where the non-default constructor gets used, such as example `m2` and `m4`.

### Configuration

- .NET 7.0.5
- Windows 10.0.19044
- x64

**Comment by jaredpar** [comment]
Thanks for taking the time to file this issue but the behavior here is by design. There is no parameterless constructor in `MetaData` so when you execute `new Metadata()` that is effectively calling `default(MetaData)`. It's not construcing a type, it's creating a zero`d instance of the value. This behavior for `struct` can be a bit confusing at times but dates back to C# 1.0. 

If you want `new MetaData()` to run the member initializers then you need to add a parameterless constructor to the type.
