### ISSUE TITLE
[Lightbulb Perf] Expose FilterSpan/FilterTree public API on remaining analysis contexts

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#68033]
#67257 added `FilterSpan` public API to `SyntaxTreeAnalysisContext` and `SemanticModelAnalysisContext`. These APIs were implemented with #67818 and our IDE code style analyzers moved over to the new API with #68014.
The performance measurements from both these PRs (added to the PR descriptions) showed quite good performance improvements in lightbulb code path from these changes. Hence, we would like to add similar `FilterSpan` API to other context types, and also a `FilterTree` API to context types where it is relevant.

### Proposal
1. Add `FilterSpan` API to the following contexts:
   ```csharp
        /// <summary>
        /// Optional filter span for which to compute diagnostics.
        /// </summary>
        public TextSpan? FilterSpan { get; }
   ```
   1. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L704
   3. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L782
   4. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L920
   5. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1013
   6. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1106
   7. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1229
   8. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1485
   9. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1580

2. Add `FilterTree` API to the following contexts:
   ```csharp
        /// <summary>
        /// Optional filter tree for which to compute diagnostics.
        /// </summary>
        public SyntaxTree? FilterTree { get; }
   ```
   1. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L704
   2. https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L782
   Note that rest of the contexts are only scoped to a specific syntax tree and there is already some property chain to get to this tree from the context object. For example, `OperationTreeAnalysisContext.Operation.Syntax.SyntaxTree`, `SyntaxNodeAnalysisContext.Node.SyntaxTree`, etc. Exposing a `FilterTree` property on them would seem to unnecessarily pollute the API surface and make it confusing for the analyzer authors that they ought to be doing something with it. I'd vote for not exposing `FilterTree` property on rest of the context types, but I am fine if the API review decides otherwise for consistency purposes.

3. **Open question:** Should we add `FilterSpan` API to `AdditionalFileAnalysisContext`? https://github.com/dotnet/roslyn/blob/193c6598997a972d359f60be3f7ee0bf9e80a8aa/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs#L1425
If yes, then this would require us to add public API overloads to below methods that take a `TextSpan? filterSpan` parameter (similar to existing APIs to fetch single file syntax and semantic diagnostics):
https://github.com/dotnet/roslyn/blob/0368609e1467563247e9b5e4e3fe8bff533d59b6/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L427-L455
   ### Proposed API overloads to add
   ```csharp
    public async Task<AnalysisResult> GetAnalysisResultAsync(AdditionalText file, TextSpan? filterSpan, CancellationToken cancellationToken);
    public async Task<AnalysisResult> GetAnalysisResultAsync(AdditionalText file, TextSpan? filterSpan, ImmutableArray<DiagnosticAnalyzer> analyzers, CancellationToken cancellationToken)
   ```
   Note that we have already added Roslyn support for code fixes and refactorings in additional files with #64364, so we can consume this new API on the Roslyn side and thread in filter span for lightbulb code path.

## Performance measurements

- I have created a draft PR #68052 to add the above proposed FilterTree/FilterSpan API to `SymbolStartAnalysisContext` and `SymbolAnalysisContext` + update the IDE code style SymbolStart analyzers to respect the filter tree and span.
- This gives **~10% speedup** for computing SymbolStart diagnostics for a line span. Please see the PR description in #68052 for details

**Comment by mavasani** [comment]
Tagging @333fred @CyrusNajmabadi @sharwell - this is ready to be brought up at the next API review meeting.

**Comment by 333fred** [comment]
@mavasani can you please add a diff view of the apis to the first post?

**Comment by 333fred** [comment]
### API Review

* What if we did `SyntaxTree` everywhere? 
    * Prefer `FilterTree` naming
* We don't have enough info to make a decision on AdditionalTexts here, so that will need to be a followup.

*Conclusion*: APIs 1 and 2 are approved (adding `FilterSpan` and `FilterTree`). We will add `FilterTree` even where it might be duplicative, for ease of API usage.
