### ISSUE TITLE
C# implict operators don't work with tuples

### ISSUE THREAD

**Issue by AlexanderBaggett** [dotnet/roslyn#68045]
**Version Used**: 

.NET 6.0
Visual Studio Community 2022 (version 17.5.4)

**Steps to Reproduce**:

Create a class with an implicit operator that comes from a tuple with one being an enum and the other an exception.
Create a method that has a return type of this class. Try to return a tuple of the specified type from the method.

    using System;
    
    namespace Repro
    {
        public class ReproClass
        {
    
            public ReproClass(EnumRepro repro, Exception exception)
            {
            }
            public static implicit operator ReproClass(Tuple<EnumRepro, Exception> tuple) => new ReproClass(tuple.Item1, tuple.Item2);
        }
        public enum EnumRepro
        {
            Monday = 1
        }
        public class ReproMethodClass
        {
        
            public ReproClass GetRepro()
            {
                var tuple = (EnumRepro.Monday, new Exception(""));
                return tuple;
            }
        }
        
    }
A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDIHYEMC2BTAzgB3QGNsACAJW3wCcB7ZAb2VJdKgGY2YKq6BhADbpcuZqyYokraW06UatQcNwAKAKKoArpnl1S1XrQA0pNQA8S+AC4BLWqlLYLVW/YCUYmaQleWAX08ZDjY4ADZSG0x8ARsiGytSWnxsanQrWmoeBSURFQAVTWjsAB4NbV1jU2drO1QAPlIrQoFsN1IAXgbUbAB3LP4hXKaigDoASStsTDgTYZbxycwYNwBuQICpVmDsLUxTXYrAn18AWXtgdABPDtJETf9A4Nh+2hPsKwALWmAc0XvvQKBaTBCq/UgAcXeFRUHn+0mOvlYADd0Jk5mR2qR1AdDCMzqgLpcTN0+uZLK5UCoAERUtyrIG+KAAdkazWwazhrA20m5rGQfiAA==

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
The dotnet compiler and intellisense recognize this is a valid implicit conversion as defined by the implicit operator and do the conversion and compile

**Actual Behavior**:
Intellisense and the donet compiler instead say :
error CS0029: Cannot implicitly convert type '(Repro.EnumRepro Monday, System.Exception)' to 'Repro.ReproClass'

**Comment by CyrusNajmabadi** [comment]
`Tuple<EnumRepro, Exception>` is different from `ValueTuple<EnumRepro, Exception>`.  The `(x, y)` syntax represents the latter, not hte former.

**Comment by AlexanderBaggett** [comment]
My bad. It doesn't help that Microsoft documentation calls `ValueTuples`  Tuples

**Comment by AlexanderBaggett** [comment]
https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/august/essential-net-csharp-7-0-tuples-explained
