### ISSUE TITLE
ExpressionLambdaRewriter.VisitArrayAccess check seems off

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn#6805]
```csharp
if (node.Type != _int32Type)
```

looks like it should be

```csharp
if (arg.Type != _int32Type)
```

**Comment by bartdesmet** [comment]
Seems it always works now because `node.Type` can never be an `Int32` given that it's an array type. We just may have a spurious conversion. It'd be interesting to see whether the old compiler had this too; if we take away the `Convert` node, some runtime expression analyzers may fail because they relied on it being there... :-(

**Comment by jaredpar** [comment]
That definitely looks like a bug.  @VSadov can you take a look at this.

**Comment by VSadov** [comment]
Looks like a bug. 
It does not result in any differences since array type is neven an int, but then ConvertIndex checks for index being int32 anyways.
