### ISSUE TITLE
Peek to definition on a definition is kinda useless

### ISSUE THREAD

**Issue by dpugh** [dotnet/roslyn#68079]
## Summary
Suppose I have this and do a peek to definition of requester on line 118. I get this:

![image](https://user-images.githubusercontent.com/11394666/236052093-ce5f5ad8-695f-4919-91f1-2bbcb1a795ec.png)

This isn't very useful since I probably wanted to get the definition of the type (IInteractiveSessionParticipent). Would it make sense to peek to definition on a definition take you to the definition of the type? Note you can get this by doing a peek to definition on the "var" but this isn't widely known.

## Proposed Feature
Change the behavior of peek to definition when it is done on the definition of a symbol to show a peek of the type (Go to definition should follow the same logic).

## Alternative Designs
Since peek to definition on the var already does the correct thing, maybe it is sufficient to publicize that behavior (put it on what's new).

**Comment by CyrusNajmabadi** [comment]
Closing as unplanned.  We haven't heard enough feedback to warrant changes here.  Platform could always just bail out of peek if its peekign to the same location.
