### ISSUE TITLE
Please make nodes Equatable

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/roslyn#68070]
## Background and Motivation

I'd like a simple way to determine if a node has changed, without having to write any additional classes.

## Proposed API

```c#
[Generator]
public class FeatureStateClassesSourceGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var featureClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
			fullyQualifiedMetadataName: "Fluxor.FeatureStateAttribute",
			predicate: (SyntaxNode node, CancellationToken cancellationToken) => true,
			transform: (source, cancellationToken) => source);

		context.RegisterSourceOutput(featureClasses, static (context, source) =>
		{
			Console.Beep(1000, 200); // Do something more useful than this
		});
```

The above code will generate a beep even when I alter a class that is not decorated with the specific attribute.

I'd like nodes to be equatable.

Note that I sometimes need to know if *anything* in the class has changed.

**Comment by CyrusNajmabadi** [comment]
Nodes are already equatable.  I'm not understanding what actual problem this solves as the description above sounds like everything is working properly. 

> The above code will generate a beep even when I alter a class that is not decorated with the specific attribute.

Yes, that's correct. When another class is edited, your code needs to rerun to see if it would generate new output.

**Comment by sharwell** [comment]
> The above code will generate a beep even when I alter a class that is not decorated with the specific attribute.

The pipeline above is not optimally written. `RegisterSourceOutput` should be passed a context object which is a domain model containing the information necessary to generate code, without including extraneous data. The pipeline should then be created with steps to extract the information necessary to build the domain model from the code. Once this task is completed, the incremental pipeline will stop calling `RegisterSourceOutput` except in cases where the domain model changes.

**Comment by sharwell** [comment]
Here's an example of a source generator which uses ForAttributeWithMetadataName, but does not regenerate output when items did not change:
https://github.com/dotnet/roslyn/blob/711d661c108078c79fca0fb9eb6c6e8f9f08dd52/src/Tools/Source/CompilerGeneratorTools/Source/EnumeratorSourceGenerator/SourceGenerator.cs
