### ISSUE TITLE
[LSP] Support URIs as a first class document property

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#68083]
We've had various issues over the years with converting to/from URIs in LSP - especially round-tripping them.  Today document only really have file paths - but not all LSP requests are for files that exist on disk.  
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1799925
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1557478
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1688648

Some examples of this are unsaved files, source generated files, and eventually metadata as source files.  

A potential rough solution to this is to make URI a first class property on a document -
1.  All documents will have URIs (nullable or not?) - URIs would be passed in on creation and would have APIs to access and update them.
2.  Various providers of documents would agree on schemas that fit their needs - for example Razor documents could be 'virtual-razor:', source generated docs could have 'source-generated:', etc.
3.  Documents could be looked up in the solution via a requested URI (similar to file path today).
4.  Document.FilePath would continue to exist (and the helpers to update it) as it is a public API.  However the implementation would essentially delegate to the URI properties - if the URI had a file: schema, we'd return the actual file path, otherwise it would be null.

Random other questions
1.  What happens with linked documents - can a single URI represent multiple different documentIds (like a filePath could)?

**Comment by tmat** [comment]
Another thing to be careful about is escaping.

`AbsolutePath` seems to have escaped values for non-ascii strings and also using `/` instead of `\` on Windows:

```
var u = new Uri("file://D:/𫚭/A.cs");
> u.LocalPath
"D:\\𫚭\\A.cs"
> u.AbsolutePath
"D:/%F0%AB%9A%AD/A.cs"
> Uri.UnescapeDataString(u.AbsolutePath)
"D:/𫚭/A.cs"
> u.LocalPath
"D:\\𫚭\\A.cs"
```

We should be careful not to mix these representations (`AbsolutePath` and `LocalPath`). It is absolutely possible to have a directory named `%F0%AB%9A%AD` which would then conflict with the character `𫚭`.

**Comment by tmat** [comment]
Observation: we should try to representing paths using `Uri` type in Roslyn as much as possible. The type is super complicated, full of back-compat quirks and has issues with Unicode characters (see https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1842233).

**Comment by dibarbet** [comment]
@tmat Matteo pointed out that `%` characters must be encoded as well, so as long as the C# URI class is encoding URIs correctly the AbsolutePath property for the URIs in your example would be different.  But I agree that comparing an AbsolutePath with a LocalPath could give misleading results.

```
Because the percent ("%") character serves as the indicator for
   percent-encoded octets, it must be percent-encoded as "%25" for that
   octet to be used as data within a URI.  Implementations must not
   percent-encode or decode the same string more than once, as decoding
   an already decoded string might lead to misinterpreting a percent
   data octet as the beginning of a percent-encoding, or vice versa in
   the case of percent-encoding an already percent-encoded string.
```

**Comment by CyrusNajmabadi** [comment]
i am terrified of this.  I would not be surprised to see us have to adds hacks upon hacks.  And then see other teams do the same (Which we then have to deal with).

I'm virtually *only* ok with using Uri if we say that we *never* touch it and try to interpret anything about it.

**Comment by tmat** [comment]
I believe this approach will be correct:

https://github.com/dotnet/roslyn/pull/69253#discussion_r1275554722

**Comment by jasonmalinowski** [comment]
So a bit of back story on this issue: we had the general idea of adding URIs to documents so we weren't having to stuff URIs inside of strings into the FilePath property, which creates some other fun ambiguities around when it's actually a "real" file path. I wouldn't want to actually do this though until we have a good understanding of both how we expect URIs to be manipulated, but also once we have confidence that our URI libraries actually do that. We clearly don't have that yet!

**Comment by tmat** [comment]
I think it'd be best to keep using string FilePath and deal with the ambiguities - what were the issues?
Definitely not Uri class.

**Comment by jasonmalinowski** [comment]
@tmat Well, it was mostly around when we end up with non-file URIs, although at the time we hadn't gone to just always using the full URI in that case. But I agree I'm now terrified seeing System.Uri acting even more strangely than previously expected.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If we do need to do this, feel free to reopen.
