### ISSUE TITLE
CreateDescriptionItems should not load document text on the UI thread

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#68104]
Observed by @CyrusNajmabadi in https://github.com/dotnet/roslyn/pull/68068#discussion_r1185328726

> ick. i never noticed this before. This really violates a core principle of navto (that no work is done client side to avoid costly UI perf). This is on the UI thread and goes and potentially does IO. Can you make issue that says that server should compute and add this info to items (ideally only if "show descriptions" is selected by user), and the client just has to present. no need for GetTextSynchronously then.

The following line loads/processes document text on the UI thread:

https://github.com/dotnet/roslyn/blob/806dba8b9e1cdfe271adc02f748362cc7af98f13/src/EditorFeatures/Core.Wpf/NavigateTo/NavigateToItemDisplay.cs#L66

**Comment by mavasani** [comment]
@sharwell please feel free to adjust the target milestone as appropriate.

**Comment by CyrusNajmabadi** [comment]
Closing out as we do not support navigate to anymore.
