### ISSUE TITLE
VS integration test failures

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6811]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/31/console

**Comment by TyOverby** [comment]
CC @brettfo

**Comment by brettfo** [comment]
As per the log, failing tests are BasicWinForms.xml and BasicWPF.xml.  The BasicWinForms.xml failure is being tracked by #6988 and BasicWPF.xml is currently passing as per [this build](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/59/console.)

Closing issue in favor of others.
