### ISSUE TITLE
Enhanced new class creation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68123]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Enhanced-new-class-creation/10341271)._

---
When creating a new class with the same name as a class that exists, it should mark the class partial by default.

When creating many files to separate a class into separate responsibilities via partial classes in .NET, the file generated will produce an error as the class is missing a partial.

E.g: 
Class1.cs
Class1.Thing1.cs

Upon creation of the second file, the default visual studio behavior will generate
public class Class1 { }

which will produce an error when Class1.cs already contains a class definition for Class1.

The desired behavior would be for Visual Studio to "just assume" that I'm intending to create a partial class.
public partial class Class1 { }

---
#### Feedback Bot on 4/19/2023, 03:38 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
