### ISSUE TITLE
Imrpove Intellisense replacement logic

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Imrpove-Intellisense-replacement-logic/10328680)._

---
[severity:It bothers me. A fix would be nice]
I typed "privatre" by accident, and VS replaced it with DisablePrivateReflectionAttribute

First

"privatre" by ANY string comparison algorithms would evaluate a weight closer to "private" than it would be to "DisablePrivateReflectionAttribute," so whatever algorithm VS is using is terrible or simply broken.

Second

DisablePrivateReflectionAttribute is actually deprecated, so why would "Intellisense" intelligently insist on inserting deprecated code?

I am only annoyed by this because of the continued insistence to add A.I. to everything these days and make them "smarter" while applying some simple common sense and intelligent design to basic features like text replacement is looked over.

---
#### Tracy Wang [MSFT] on 4/2/2023, 09:34 PM: 

(private comment, text removed)
#### Feedback Bot on 4/3/2023, 01:09 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This isn't an ai/ml feature.  It's simply that currently a case insentive, contiguous, substring match is viewed as better than a fuzzy match.  We'd need a separate weighting system to change this.  Tagging @veler .

**Comment by CyrusNajmabadi** [comment]
Closing out due to lacck of broad feedback on this.
