### ISSUE TITLE
EditorConfig not taken into account if the filename is not `.editorconfig`

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#68130]
**Version Used**: 17.6.0 Preview 6.0

**Steps to Reproduce**:

1. Create a new console application
2. Create a new editorconfig file `CodingStyle.editorconfig` at the root of the solution with the following content:
```editorconfig
# top-most EditorConfig file
root = true

[*]
indent_style = space
charset = utf-8
end_of_line = crlf
insert_final_newline = true
trim_trailing_whitespace = true

# XML project files
[*.{csproj,vbproj,vcxproj,vcxproj.filters,proj,projitems,shproj}]
indent_size = 2

```
4. Fill the EditorConfigFiles property in the csproj (or Directory.Build.props/targets):
```xml
<ItemGroup>
  <EditorConfigFiles Include="..\CodingStyle.editorconfig" />
</ItemGroup>
```
or with the absolute path:
```xml
<ItemGroup>
  <EditorConfigFiles Include="C:\Users\john\source\repos\ConsoleApp1\CodingStyle.editorconfig" />
</ItemGroup>
```
5. Try to format the csproj in Visual Studio (Ctr+K, Ctrl+D)

**Expected Behavior**:

The editorconfig is taken into account and the csproj is intended with 2 spaces.

**Actual Behavior**:

The editorconfig is not taken into account and the csproj is intended with 4 spaces.

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard about this from anyone.  It seems like industry consensus is to name this consistently everywhere.
