### ISSUE TITLE
BUG: Expression is always false

### ISSUE THREAD

**Issue by kelilife** [dotnet/roslyn#68153]
**Version Used**: 
Visual Studio 17.5

**Steps to Reproduce**:
![image](https://github.com/dotnet/roslyn/assets/115648681/7dc2eee2-475e-4c92-8e2a-cd8b70959e03)

**Comment by CyrusNajmabadi** [comment]
That doesn't look like roslyn.  Are you using anyn other extensions?

Can you show what your error list displays for this item?

**Comment by kelilife** [comment]
Yes. Problems caused by Resharper.
