### ISSUE TITLE
Stackoverflow in binding when building System.Runtime with nightly Roslyn build

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#68172]
**Version Used**: 4.7.0-1.23259.11

**Steps to Reproduce**:

1. Clone dotnet/runtime.
2. Run `./build libs`

3. Run `./dotnet build --no-incremental .\src\libraries\System.Runtime\src\System.Runtime.csproj /t:GenerateReferenceAssemblySource` to regenerate System.Runtime's ref assembly source.
4. Run that command again. It will fail when building the ref assembly for System.Private.CoreLib

**Expected Behavior**: Build succeeds

**Actual Behavior**: Stackoverflow with the [attached stack](https://github.com/dotnet/roslyn/files/11456336/stack.txt)

[Zip containing a Compilation Log](https://github.com/dotnet/roslyn/files/11456333/msbuild.complog.zip)

**Comment by jcouv** [comment]
This is a known issue, tracked by https://github.com/dotnet/roslyn/issues/60961
I was able to extract a minimal repro (removing most files from the compilation then removing most types from the remaining file). Added details to the original bug.
