### ISSUE TITLE
Remove Unused References does not work for .NET Standard 2.0 project although it uses the new csproj format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68189]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-Unused-References-does-not-work-f/10362153)._

---
[severity:It's more difficult to complete my work]
Remove Unused References on Rightclick project does not work for .NET Standard 2.0 project although it uses the new csproj format

---
#### Feedback Bot on 5/14/2023, 09:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this.
