### ISSUE TITLE
[Test Failure] AnalyserPowerPack

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6820]
> Errors Microsoft.AnalyzerPowerPack.UnitTests.dll:
  Command: C:\Users\Adam\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe "Binaries\Debug\Microso
  ft.AnalyzerPowerPack.UnitTests.dll" -xml "Binaries\Debug\xUnitResults\Microsoft.AnalyzerPowerPack.UnitTests.dll.xml"
  -noshadow -verbose
  xUnit output: Binaries\Debug\xUnitResults\Microsoft.AnalyzerPowerPack.UnitTests.dll.out.log
  xunit produced no error output but had exit code 1

Produced xml file
```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly />
</assemblies>
```

**Comment by mavasani** [comment]
@AdamSpeight2008 Are you still hitting this issue? If so, kindly report an issue on roslyn-analyzers repo with additional information (repro setup, failing test(s), fails consistently or intermittently, etc.) - our Roslyn based analyzers and unit tests have been moved to that repo.
