### ISSUE TITLE
When git is pulled, the code prompts an error

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#68202]
**Version Used**: 17.7.0 P1

**Steps to Reproduce**:

1. [git clone](https://github.com/Varorbc/Test.git)
2. switch `roslyn` branch
3. reset commit 391dcc13aba889e81949dd2047e000e9febd2bea
4. open `Class2 ` file
5. git pull

**Expected Behavior**:

work well

**Actual Behavior**:

![image](https://user-images.githubusercontent.com/5714438/223030489-c65e65c8-20c1-40c4-baed-383b2cf72448.png)

**Comment by CyrusNajmabadi** [comment]
Clsoing out due to lack of broad feedback on this.
