### ISSUE TITLE
Partial class implementing identically named file interfaces with identically named members should not confuse them

### ISSUE THREAD

**Issue by mkane91301** [dotnet/roslyn#68219]
**Version Used**:  .NET 7

(Before you think this is a crazy scenario, the use case is generated code.)

**Steps to Reproduce**:
(Unfortunately, this can't be demonstrated in a gist, because it requires multiple files.)
1. In one file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
    private readonly Dictionary<int, string> _bar = new() { { 1, "one" }, { 2, "two" } };
    IReadOnlyDictionary<int, string> IFoo.Bar => _bar;
}
```
2. In a second file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
    IReadOnlyDictionary<int, string> IFoo.Bar => _bar;
}
```
3. After getting no complaints in Visual Studio, compile.

**Diagnostic Id**: CS0102

4. Change second file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
}
```
(`Foo` needs to implement `IFoo` because, elsewhere in the file, an instance of `Foo` will be passed to a method taking `IFoo`.)

5. Visual Studio complains that `Foo` doesn't implement `IFoo`.

6.  Compile.

**Diagnostic Id**: CS0535

**Expected Behavior**: The compiler recognizes that `IFoo.Bar` in the part of `Foo` in one file is different from `IFoo.Bar` in a different part because each `IFoo` is file scoped and is therefore a different type. Seeing these as different types, the compiler does not emit CS0102 and compiles the code.

**Actual Behavior**: The compiler confuses file scoped types with the same name and emits CS0102 and doesn't compile the code.

**Comment by RikkiGibson** [comment]
Thanks for reporting! Adding the full error message here, as we don't have the error codes memorized :wink::

```
Class2.cs(8,43,8,46): error CS0102: The type 'Foo' already contains a definition for 'IFoo.Bar'
```
