### ISSUE TITLE
Why is SyntaxToken.RawContextualKind internal?

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#6822]
If I understand correctly, I'm currently forced to use a string comparison to determine if an invocation expression is `nameof`, vs some method or delegate:

```c#
if ((invocationExpression as IdentifierNameSyntax)?.Identifier.ValueText ==
    SyntaxFactory.Token(SyntaxKind.NameOfKeyword).ValueText) [...]
```

I would much prefer access to [`RawContextualKind`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxToken.cs#L68) and the [`ContextualKind()`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L37) extension method just like [`RawKind`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxToken.cs#L51) and [`Kind()`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/CSharpExtensions.cs#L146). Right off the bat it feels cleaner and more performant. Besides that and perhaps more importantly, `nameof` is a contextual keyword. Sometimes the same token value string could be used for `NameOfKeyword`, and sometimes it might refer to a method or delegate. The [XML docs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SyntaxToken.cs#L58) on `RawContextualKind` confirm that this is relevant for contexual keywords. This code would be much smarter:

```c#
if ((invocationExpression as IdentifierNameSyntax)?.Identifier.ContextualKind() ==
    SyntaxKind.NameOfKeyword) [...]
```

Why is the contextual syntactic knowledge stored in `RawContextualKind` barred from public access? Is there a different API that does provide access?

**Comment by gafter** [comment]
`nameof` is not a contextual keyword. Like `var`, It is a normal identifier. When used it is represented by an invocation expression.
