### ISSUE TITLE
Visual Studio no longer displays warning for inappropriate namespace

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68239]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-no-longer-displays-warning/10284772)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.5 Preview 5]
Since the last preview update, I no longer get a warning on two machines when the namespace does not match.
The old version still works.

The editorconfig contains: 
dotnet_style_namespace_match_folder = true:suggestion

---
#### Feedback Bot on 2/20/2023, 07:15 PM: 

(private comment, text removed)
#### Feedback Bot on 2/21/2023, 08:36 AM: 

(private comment, text removed)
#### Feedback Bot on 2/21/2023, 08:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm unable to repro this.
