### ISSUE TITLE
Weird Syntax Highlighting and Error locations with non-deterministic c# source generator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68237]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Weird-Syntax-Highlighting-and-Error-loca/10257631)._

---
[severity:Other]
In visual studio 2022 (17.4.4) when viewing a source generated file (using an `IIncrementalGenerator`, I don't know if this problem can occur with an `ISourceGenerator`) the syntax highlighting can sometimes be super weird, and the error line number don't line up with the visible code off (see how there is an error about a `ThreadPool` on the line for `ISymbolWriter` in the screenshot).
I determined that if the source generator does not produce deterministic output (in my case due to a "list" of symbols that I did not sort) this will happen. 
It is not immediately apparent that there was non-determinism in the output as the displayed generated text, weird highlighting and wrong error locations was not changing, my guess is that the different build pipelines are (build, intellisense, syntax highlighting provider, analyzer, etc.) are being fed the source in a different order.

There is a simple fix, ensure the source generated is the same no matter what order the syntax nodes, or 

I am submitting this report more so that people find a match to the symptoms and are provided a solution as I was unable to find anyone else with this issue and not because I need it fixed, as fixing my generator to be deterministic (in my case by sorting a list before i used it to generate the source) fixed the problem. 

_I did not include the system logs as my workplace rules disallow it_

---
#### Andrew Moskevitz on 1/19/2023, 07:22 AM: 

(private comment, text removed)
#### Feedback Bot on 1/19/2023, 09:10 PM: 

(private comment, text removed)
#### Feedback Bot on 1/20/2023, 08:58 AM: 

(private comment, text removed)
#### Feedback Bot on 1/20/2023, 08:58 AM: 

(private comment, text removed)

---
#### Andrew Moskevitz solved on 1/19/2023, 07:06 AM, 0 votes: 

<p>Ensure the source generated is the same no matter what order the source is process, (e.g. sort any collections before using them)</p>

**Comment by jcouv** [comment]
Tagging @chsienki to advise/triage.

**Comment by chsienki** [comment]
I don't think there's anything we can do here. `IIncrementalGenerators` must be deterministic in their output, or they are fundamentally broken (as we could end up using cached values for the wrong items).

I'm guessing that the mismatch is occurring because we're running the generator both in-proc and out-of-proc, and so getting different results that then don't line up with each other.

**Comment by Applesauce314** [comment]
when i wrote this feedback I was actually not expecting a fix, more just wanted to write it down somewhere so others would  not have to go through the same research process. There may be documentation somewhere that could be updated to make it more clear that the output must be deterministic regardless of the order that the syntax/symbols are processed.
