### ISSUE TITLE
Why is ParameterSymbol.IsCallerMemberName internal?

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#6824]
I need to determine if a given parameter from the semantic model has the `CallerMemberName` attribute. [`ParameterSymbol.IsCallerMemberName`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/ParameterSymbol.cs#L370) seems the safest and most efficient way to check, but it is internal.

The only workaround I can find is `parameter.GetAttributes().Any(_ => _.AttributeClass.GetNamespacedName() == "System.Runtime.CompilerServices.CallerMemberNameAttribute")` where `GetNamespacedName` is:

```c#
public static string GetNamespacedName(this INamedTypeSymbol type)
{
    var sb = new StringBuilder();
    GetNamespacedName(type, sb);
    return sb.ToString();
}
private static void GetNamespacedName(INamedTypeSymbol type, StringBuilder sb)
{
    if (type.ContainingType != null)
    {
        GetNamespacedName(type.ContainingType, sb);
        sb.Append('+');
    }
    else
    {
        GetNamespacedName(type.ContainingNamespace, sb);
    }
    sb.Append(type.Name);
}
private static void GetNamespacedName(INamespaceSymbol @namespace, StringBuilder sb)
{
    if (@namespace?.IsGlobalNamespace != false) return;
    GetNamespacedName(@namespace.ContainingNamespace, sb);
    sb.Append(@namespace.Name).Append('.');
}
```

I'm fairly sure that's not the logic `ParameterSymbol.IsCallerMemberName` uses.

**Comment by gafter** [comment]
It is internal because it was not designed to be part of the language model. It is an internal compiler helper.
