### ISSUE TITLE
Intellisense is showing compiler generated fields in a C# project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68240]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-is-showing-compiler-generat/10306036)._

---
Visual Studio should not show generated (and inaccessible) fields in IntelliSense.

Repro:
- dotnet new console
- Use the following code

````c#
Console.WriteLine("Hello, World!");

class Sample
{
    public static Sample Instance { get; } = new Sample();

    private sealed class Nested
    {
        Sample A()
        {
            // 👇AutoComplete here
            return Sa
        }
    }
}
````

![image](https://github.com/dotnet/roslyn/assets/1408396/c5c0a4ee-c758-489a-ae90-6e54fb365851)

---
#### Feedback Bot on 3/9/2023, 08:53 PM: 

(private comment, text removed)
#### Feedback Bot on 3/13/2023, 03:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I was able to reproduce this in Version 17.7.0 Preview 2.0 [33716.462.main]

**Comment by CyrusNajmabadi** [comment]
@sharwell Is this your feature to show static members when target typing?  If so, it may have to filter out unspeakable names :)

**Comment by sharwell** [comment]
Ah, yes, missed that!

**Comment by sharwell** [comment]
The filter that needs to be updated is here:
https://github.com/dotnet/roslyn/blob/078c7947e2db1253194355d758c8394e87b2a45c/src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs#L221-L230

Tests can be added here:
https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs
