### ISSUE TITLE
Why doesn't MSBuildWorkspace support adding a project?

### ISSUE THREAD

**Issue by Giftednewt** [dotnet/roslyn#6825]
I'm working with the workspaces API and wanted to use the MSBuildWorkspace but it doesn't appear that it supports adding a project. Is there any reason why it couldn't/shouldn't do this?

**Comment by mattwar** [comment]
It is not clear what msbuild project file would be used to represent an new project, as they typically contain more information than is represented in the roslyn project API, and include conditional nodes and target script references. When new projects are created in VS they are done via a template that sets up all the interesting bits. It would be technically possible to create a trivial project file that only contains the exact information needed to get back to an equivalent roslyn project, but that is likely not what a user would want or need for their solution.
