### ISSUE TITLE
Items sticked over the top due to sticky scroll does not highlight in expected way when hovered

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68271]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Items-sticked-over-the-top-due-to-sticky/10369022)._

---
When I try to hover on the sticky lines, the expected line does not highlight. E.g. if there are three sticky lines: l1 : namespace, l2 : class name, l3 : method name. When I hover over l3, l1 gets highlighted. When I hover over l2, l1 remains highlighted and same behavior when I hover over l1.
If there are five sticky lines, when I hover over l5, l3 gets highlighted. For l4, l2 gets selected. Looks like i - 2 th line is getting highlighted, when I hover over ith line.

---
#### Feedback Bot on 5/19/2023, 01:13 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is actually a bug for a different team, so moving back to Developer Community.
