### ISSUE TITLE
Renaming a variable name has issue in new version of Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68273]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming-a-variable-name-has-issue-in-ne/10367016)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.6]
When I try to rename a parameter of a method, visual studio is adding extra characters to it. this is happening after I updated my visual studio to 17.6

---
#### Feedback Bot on 5/18/2023, 07:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we got a bunch of hits on this, made changes, and haven't gotten more hits since
