### ISSUE TITLE
Customize Go To Definition for Source Generated types and members

### ISSUE THREAD

**Issue by ichthus1604** [dotnet/roslyn#68294]
## Summary

Allow Attribute-based customization of the "Go To Definition" (Ctrl+Click) feature in source code, so that a certain type or member can "redirect" Ctrl+Click navigation to a different type or member.

## Background and Motivation

We're currently using source-generated code extensively throughout our codebase as "glue code" to instantiate certain classes and invoke methods on these instances.

This approach works very well for us but disrupts Ctrl+Click navigation, because the source-generated code gets "in the way" and you need to do additional navigation steps to reach the actual target class.

We would like to have a way to override the behavior of Ctrl+Click and "redirect" the navigation to a different place, in a customizable user-defined way.

More specifically, we're using it for ViewModel-driven routing and popup dialogs in our Avalonia application.

So, if ViewModel `Foo` needs to route to ViewModel `Bar`, we do the following:

![image](https://github.com/dotnet/roslyn/assets/98904713/3c92b27a-b4e0-4abe-8a0f-2dfa4bd499f5)

- `Foo` invokes a source-generated routing method called `Bar()` that has the same parameters as the user-defined constructor of the `Bar` class.
- This method invokes a source-generated constructor of the `Bar` class that has the same parameters as the user-defined constructor, plus an additional context object.
- This constructor is based on the user-defined constructor.

We would like to be able to Ctrl+Click from the code in `Foo` directly to the user-defined constructor of `Bar` without the intermediate steps 2 and 3.

A simplified example of this:

```csharp
// User-defined class Foo
class Foo: ViewModelBase
{
    void GoToBar()
    {
        // RouteTo() returns a source-generated type that contains a method for each existing viewmodel, including a Bar() method. 
        // This method has the same parameters as the constructor of the Bar class.
        RouteTo().Bar(5); 
    }

    protected Route RouteTo() { /* ... */ }
}

// User-defined class Bar
partial class Bar: ViewModelBase
{
    // Constructor parameters are "copied" from the user-defined constructor to the source-generated RouteTo().Bar() method
    private Bar(int someValue)
    {
        // ...
    }
}
```

From this user-defined code, our source generator generates the following:

```csharp
// Auto-generated
partial class Route
{
    ContextObject context;

    // Source-generated navigation method
    // Has the same parameters as the user-defined constructor of the Bar class
    public void Bar(int someValue)
    {
         // invokes the source-generated constructor of the Bar class
         var target = new Bar(context, someValue);
         GoTo(target);
    }
}

// Auto-generated
partial class Bar
{
    // This source-generated constructor "copies" all parameters from the user-defined one, adding an additional ContextObject
    public Bar(ContextObject context, int someValue): this(someValue)
    {
        // ...
    }
}
```

As you can see, in this scenario Ctrl+click navigation from Foo to Bar requires 3 steps:
 - Ctrl+Click on `Bar` method in `RouteTo().Bar(5)` will navigate to source generated `Route.Bar(int someValue)`
 - Ctrl+Click on `Bar` type in `new Bar(context, someValue)` will navigate to source generated public constructor in class `Bar`
 - Ctrl+Click on `this` in `: this(someValue)` will finally navigate to the relevant, user-defined constructor of `Bar`.

## Proposed Feature

Create a `[GoToDefinition]` attribute that will allow to annotate the source generated code, indicating that Ctrl+Click (or Go to Definition) navigation should be redirected to a specific type and member in user-defined code and bypass anything in between.

The above generated code could be annotated like so:

```csharp
// Auto-generated
partial class Route
{
    ContextObject context;

    // Source-generated routing method
    // Attribute Indicates that Ctrl+Click of this method should really go to type Bar, constructor with arg "someValue"
    [GoToDefinition<Bar>(MemberName = "ctor", Args = new[] {"someValue"})] 
    public void Bar(int someValue)
    {
         var target = new Bar(context, someValue);
         GoTo(target);
    }
}
```

So that the `[GoToDefinition]` attribute indicates which type and member to go to when Ctrl+Clicking or selecting "Go To Definition" of the annotated method.

## Alternative Designs

None that I can think of right now.

**Comment by CyrusNajmabadi** [comment]
How would a user actually *see* the source-generated code in this case then?  I'm wary of an approach where goto-def doesn't take you to the real definition.

**Comment by ichthus1604** [comment]
@CyrusNajmabadi In our case, we don't want to ever see the source-generated code, since it's glue code. 

But if that would ever be needed, there's 2 actions in the IDE currently: "go to definition" and "go to implementation". AFAIK Ctrl+Click is "Go to Definition", while "Go To Implementation" requires right-click context menu. It's similar to the current experience of navigating to interfaces versus the implementations of those interfaces.

**Comment by ichthus1604** [comment]
@CyrusNajmabadi I'm thinking of more scenarios where such a feature would be useful:

- Allowing seamless navigation between client and server code in Blazor WASM apps. You could have a source-generated API client from your swagger, and use that client in your Blazor code. Ctrl+clicking `MyApi.MyEndpoint()` invocation would take you to `MyApiController.MyEndPoint()` method instead of a source generated boilerplate code performing HTTP calls and JSON serialization.

**Comment by neuecc** [comment]
I would also like to have this feature.
In my [PrivateProxy](https://github.com/Cysharp/PrivateProxy/) Source Generator, for instance, 
currently, when I "Go to Definition" on a generated _field, it takes me to the proxy's _field. 
I would prefer it to lead me to the original definition. 
I think this wouldn't be too out of the ordinary if we consider it similar to the behavior of `StackTraceHiddenAttribute` in StackTrace.

**Comment by kirill-gerasimenko-da** [comment]
In my case I'm generating delegate wrappers around components, which then are used as delegates directly. When I navigate to the generated delegate - I get to the generated code, which is a glue code and there's nothing interesting there. I'd rather go to the original component, instead, since the actual logic is there.

**Comment by CyrusNajmabadi** [comment]
@kirill-gerasimenko-da can you give an example of such code?

**Comment by kirill-gerasimenko-da** [comment]
Sure, so here's the example component:
```csharp
using CliWrap;

[Function]
public class ConvertBook
{
    readonly ILogger<ConvertBook> _logger;

    public ConvertBook(ILogger<ConvertBook> logger) => _logger = logger;

    public async ValueTask<Unit> Invoke(string sourceFile, string targetFile, CancellationToken token)
    {
        Guard.Argument(sourceFile, nameof(sourceFile)).NotNull().NotEmpty();
        Guard.Argument(targetFile, nameof(targetFile)).NotNull().NotEmpty();

        var pipeTarget = PipeTarget.ToDelegate(line => _logger.LogInformation(line));

        var command = Cli.Wrap("ebook-convert")
            .WithArguments(Seq(
                sourceFile,
                targetFile,
                "--remove-paragraph-spacing-indent-size", "1.0",
                "--remove-paragraph-spacing",
                "--change-justification", "left",
                "--extra-css", @".paragraph { text-align: left }",
                "--filter-css", @"font-family,color,margin-left,margin-right,line-height"))
            .WithStandardOutputPipe(pipeTarget)
            .WithStandardErrorPipe(pipeTarget);

        _logger.LogInformation("Convert using: {FullCmd}", command.ToString());

        await command.ExecuteAsync(token);

        return unit;
    }
}
```
And here's what's generated:
```csharp

#pragma warning disable CS0105

using System.Threading;
using System.Threading.Tasks;
using LanguageExt;
using LanguageExt.Common;
using static LanguageExt.Prelude;
using TheUtils;
using System.Runtime.CompilerServices;

namespace HomieBot.Features.BookConverter.Behavior.Calibre
{
    using Unit = LanguageExt.Unit;

    
    public delegate Aff<Unit> ConvertBookAff(string sourceFile, string targetFile, CancellationToken token);
    public delegate ValueTask<Fin<Unit>> ConvertBookSafe(string sourceFile, string targetFile, CancellationToken token);
    public delegate ValueTask<Unit> ConvertBookUnsafe(string sourceFile, string targetFile, CancellationToken token);
    
}

namespace TheUtils.DependencyInjection
{
    using Unit = LanguageExt.Unit;
    using HomieBot.Features.BookConverter.Behavior.Calibre;
    using Microsoft.Extensions.DependencyInjection;
    using TheUtils;
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using TheUtils;
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using static TheUtils.FunctionTransforms;
    using static TheUtils.FunctionTransforms;

    public static partial class ServiceCollectionFunctionExtensions
    {
        public static IServiceCollection AddConvertBookFunction
        (
            this IServiceCollection services,
            ServiceLifetime lifetime
        )
        {
            services.Add(new(
                serviceType: typeof(ConvertBook),
                implementationType: typeof(ConvertBook),
                lifetime));

            services.Add(new(
                serviceType: typeof(ConvertBookAff),
                factory: x => new ConvertBookAff(
                    (sourceFile, targetFile, token) =>
                        Transform(async () =>
                            await x.GetRequiredService<ConvertBook>().Invoke(sourceFile, targetFile, token)
                        )
                ),
                lifetime));

            services.Add(new(
                serviceType: typeof(ConvertBookSafe),
                factory: x => new ConvertBookSafe(
                    (sourceFile, targetFile, token) =>
                        Transform(async () =>
                            await x.GetRequiredService<ConvertBook>().Invoke(sourceFile, targetFile, token)
                        ).Run()
                ),
                lifetime));

            services.Add(new(
                serviceType: typeof(ConvertBookUnsafe),
                factory: x => new ConvertBookUnsafe(
                    (sourceFile, targetFile, token) => 
                        Transform(async () =>
                            await x.GetRequiredService<ConvertBook>().Invoke(sourceFile, targetFile, token)
                        ).Run().ThrowIfFail()
                ),
                lifetime));

            return services;
        }       
    }
}
```
And simplified usage of the generated typed delegate:
```csharp
public class DownloadAndConvertBook
{
    readonly ConvertBookAff _convertBook;
    readonly GetBookNameAff _getBookName;

    public DownloadAndConvertBook(ConvertBookUnsafe convertBook, GetBookNameAff getBookName)
    {
        _convertBook = convertBook;
        _getBookName = getBookName;
    }
    public async Task Invoke(CancellationToken token)
    {
        await _convertBook("c:\book.mobi", "c:\book.epub", tooken);
    }
}
```

**Comment by kirill-gerasimenko-da** [comment]
So when I want to go to to ConvertBookUnsafe - I'd like to go the [Function] component, instead of to the glue code (generated).

**Comment by kirill-gerasimenko-da** [comment]
I have another example where similar approach is used for the context threading between different components, which are wrappers around database queries.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
