### ISSUE TITLE
MissingMethodException in VS 17.6 RoslynCodeAnalysisService process when source generator loads another assembly

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#68290]
**Version Used**: VS 17.6

**Steps to Reproduce**:

Create a source generator, that loads an assembly with another source generator and delegates to it:

```c#
using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Reflection;

namespace SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class Generator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            AppDomain.CurrentDomain.AssemblyResolve += (s, e) =>
                AppDomain.CurrentDomain.GetAssemblies()
                    .Single(x => AssemblyName.ReferenceMatchesDefinition(new AssemblyName(e.Name), x.GetName()));

            var implAssembly = Assembly.LoadFile(@"path\to\SourceGeneratorImpl.dll");

            var implType = implAssembly.GetType("SourceGenerator.GeneratorImpl");

            var impl = (IIncrementalGenerator)Activator.CreateInstance(implType);

            impl.Initialize(context);
        }
    }
}
```

The other source generator only has to use anything involving `ImmutableArray<T>`, e.g. call `Collect` on an `IncrementalValuesProvider<T>`:

```c#
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;

namespace SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class GeneratorImpl : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.AdditionalTextsProvider.Select((text, _) => text).Collect();
        }

        public ImmutableArray<int> SomeImmutableArrayProperty { get; set; }
    }
}
```

Then reference this source generator as a NuGet package from another project and open it in Visual Studio 17.6.

**Expected Behavior**:

The source generator works (in this case, does nothing useful).

**Actual Behavior**:

The following exception is thrown when the `ServiceHub.RoslynCodeAnalysisService` process tries to run the source generator:

```
System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.IncrementalValueProvider`1<System.Collections.Immutable.ImmutableArray`1<!!0>> Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Collect(Microsoft.CodeAnalysis.IncrementalValuesProvider`1<!!0>)'.
   at SourceGenerator.GeneratorImpl.Initialize(IncrementalGeneratorInitializationContext context)
   at SourceGenerator.Generator.Initialize(IncrementalGeneratorInitializationContext context)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken)
```

This seems to happen, because that process has two copies of System.Collections.Immutable loaded and Microsoft.CodeAnalysis uses one, while the loaded source generator uses the other:

![](https://github.com/dotnet/roslyn/assets/287848/892a1847-ca08-4b0c-83cb-db61d1de7cad)

This is not a problem in the devenv process, because that only has one copy of the Microsoft.CodeAnalysis assembly loaded.

Note that this only started happening with VS 17.6.

**Comment by CyrusNajmabadi** [comment]
Unable to repro this, and we haven't heard about this issue from any other user.  Likely a project config issue, closing out as stale.  To fix, we'd need a repro project demonstrating the issue.
