### ISSUE TITLE
Interactive Window is broken on VS 2015 RTM

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6829]
Can't find System.IO.FileSystem.

**Comment by amcasey** [comment]
@jasonmalinowski already has a tentative fix.

**Comment by amcasey** [comment]
FYI @drognanar

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-interactive

**Comment by amcasey** [comment]
Workaround is to copy that DLL to the extension folder.

**Comment by jasonmalinowski** [comment]
Fixed with #6841.
