### ISSUE TITLE
EnC: Adding public method to a library and invoking it within the same edit session

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#68293]
Fails on .NET Framework and .NET 8 Preview 3. Fixed in .NET 8 Preview 4.

Repro

1. Unzip [Repro.zip](https://github.com/dotnet/roslyn/files/11536608/Repro.zip) and open the solution in VS.
2. F10
3. Uncomment definition of method `H` in `Class1.cs` and call `c.H();` in `Program.cs`.
4. F5

**Expected output**

```
1
2
```

Method `H` is not executed.

**Actual output**

```
1
```

Method `H` is executed.

**Comment by tmat** [comment]
Generated deltas:

[Deltas.zip](https://github.com/dotnet/roslyn/files/11536640/Deltas.zip)

**Comment by tmat** [comment]
@AaronRobinsonMSFT

**Comment by mikelle-rogers** [comment]
@tmat, when I use the latest Visual Studio and .NET 8, I get the expected output.
