### ISSUE TITLE
Record's default ToString() outputs private getter value

### ISSUE THREAD

**Issue by xakep139** [dotnet/roslyn#68309]
### Description

Even though `record`'s default `ToString()` implementation doesn't emit any non-`public` properties/fields, a `public` property with `private` or `internal` getter will be output.
It looks to me as OOP's encapsulation principle breaking.

### Reproduction Steps

Consider this example:

```csharp
var rec = new MyRecord() { PrivateGetterProperty = "Sensitive data..." };
System.Console.WriteLine("rec is '{0}'", rec);

record MyRecord // can be "record class" or "record struct"
{
    public string? PrivateGetterProperty { private get; set; }
}
```

The same code that can be run at [sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLIE8BKBTAxgezDgAIw9iBeYqbAdwAoBKYgb2IAUwBLANwENg2AOLZggsJ3wAHbGGDpKxAEQBlbFADOXYL2zE4AvgDoTS4gF8A3AFgAUAAEAjEacBOekrK5iXDcQDkLAAM5v5KMKR4jDa2dl6EJBrAkLjAxBg4BER2LHbE+cT2AMyFjkEA/Bzc/IIiYrKSMnIKbFLVAnoA5qKWxBo9FnbmQA==).

### Expected behavior

The output shouldn't contain `PrivateGetterProperty` value.

### Actual behavior

It outputs `rec is 'MyRecord { PrivateGetterProperty = Sensitive data... }'`.

### Regression?

No.

### Known Workarounds

Override default `ToString()` implementation or make the property non-`public`.

### Configuration

Reproduces on all .NET runtimes starting from .NET 5.

**Comment by CyrusNajmabadi** [comment]
I don't see anything in the specification that says this shouldn't happen. So afaict, Roslyn is working properly here.

**Comment by xakep139** [comment]
@CyrusNajmabadi Can you please share a link to the spec?

**Comment by CyrusNajmabadi** [comment]
Here you go: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/records.md :)

**Comment by xakep139** [comment]
Yeah, it really depends on how you understand `readable property members`, since it's not readable outside of the type

**Comment by CyrusNajmabadi** [comment]
> Yeah, it really depends on how you understand readable property members, since it's not readable outside of the type

The property is 'readable' as per the view of the language.  This code can read it, ergo it's readable.  An unreadable property would be one that was, for example, `settable only` from this location.
