### ISSUE TITLE
How should IParameterSymbols be mapped to ArgumentSyntaxes?

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#6831]
What API should be used to map each `IParameterSymbol` to zero or more `ArgumentSyntax` instances for a given `InvocationExpressionSyntax`?

For example, the first argument should be mapped to the third parameter symbol and the second should be mapped to the first parameter symbol:

``` c#
new ClassInReferencedAssembly().Example(c: 1, a: 2);

public class ClassInReferencedAssembly
{
    public void Example(int a, int b = 0, int c = 0)
    {
    }
}
```
- `SemanticModel.GetSymbolInfo(invocationExpression).Symbol` returns the needed `IMethodSymbol` but not the needed mapping between `ArgumentSyntax` and `IParameterSymbol`.
- `SemanticModel.GetSymbolInfo(invocationExpression.ArgumentList).Symbol` and `SemanticModel.GetSymbolInfo(argument).Symbol` return null.
- There doesn't seem to be information on it in the documentation.
- Searching the code, the only thing I see that looks similar is an internal helper class named `Binder` that returns `IInvocationExpression` objects that have `ArgumentsInParameterOrder` and `ArgumentMatchingParameter`.
- Given the possibilities of out of order named parameters, optional parameters, `this` parameters and params arrays, I am loath to reinvent and implement C#'s binding logic myself. This seems like something that should be centralized with the C# compiler.

**Comment by Pilchie** [comment]
We really need an API to do this.  It's a bit of a pain right now.  I'm pretty sure @DustinCampbell has an idea for what it should look like.

I used (this code)[https://github.com/Pilchie/RoslynCancellationTokenAnalyzers/blob/master/CancellationAnalyzer/CancellationAnalyzer/CancellationTokenMustBePassedExplicitlyAnalyzer.cs#L60] when I wrote something to do it.

**Comment by jnm2** [comment]
This is what I'm doing for now. I think it correctly handles any combination of named and optional and `params` but it doesn't handle `this` parameters: https://gist.github.com/jnm2/9460f0aee66cb5248286

**Comment by DustinCampbell** [comment]
I haven't attempted mapping `IParameterSymbol` back to an `ArgumentSyntax`, but I have code for doing the reverse: https://github.com/DustinCampbell/CSharpEssentials/blob/master/Source/CSharpEssentials/Extensions.cs#L45-L137

**Comment by RikkiGibson** [comment]
I think the IOperation APIs may not have been around at the time this issue was opened, but that appears to be the answer to this question to me. Feel free to follow up if needed @jnm2.
