### ISSUE TITLE
IDE0270 - Ignore when throwing expression

### ISSUE THREAD

**Issue by grosch-intl** [dotnet/roslyn#68313]
### Analyzer

**Diagnostic ID**: IDE0270 Null check can be simplified.

### Describe the improvement

Allow ignoring the rule when an exception is going to be thrown.

I love the null check rule, but there's one very common case where I don't want it:

```csharp
var request = await Context.Request.Where(x => x.Uuid == requestUuid).SingleOrDefaultAsync();
if (request is null)
    throw new NotFoundException();
```

I really dislike ending up with this:

```csharp
var request = await Context.Request.Where(x => x.Uuid == requestUuid).SingleOrDefaultAsync() ?? throw new NotFoundException();
```

as I think it's just not as readable.

### Describe suggestions on how to achieve the rule

Ideally there'd be an "except when throwing exception" option on the rule, or maybe create a second rule entirely that is specifically to skip when it's an exception being thrown.

**Comment by CyrusNajmabadi** [comment]
This *is* the feature.  If you do not want this offered, just disable that suggestion for your repo/project :)

**Comment by grosch-intl** [comment]
@CyrusNajmabadi That's disappointing.  The feature is great for null coalescing when there's an assignment being done, but when it throws an exception it's just plain ugly.

**Comment by CyrusNajmabadi** [comment]
Don't apply the suggestion in that case :)

**Comment by grosch-intl** [comment]
Understood, but isn't this the place to ask for enhancements to a rule?  I want the rule to be marked as an error when it triggers, but then I have a ton of errors showing for the exceptions.

**Comment by CyrusNajmabadi** [comment]
> Understood, but isn't this the place to ask for enhancements to a rule?

Sure.  But we're unlikely to make exceptions here.  We don't really want lots of knobs for these sorts of things.  Especially as the feature is offering the change to the idiomatic form the language intentionally added.  Given millions of users, we'll find that nearly anything that is done will have some people that don't like it.  But adding knobs to appease all of those cases just ends up with tons of complexity.  So we opt to make all our features work fairly uniformly *unless* we see significant and substantive feedback from large enough groups to warrant options.

**Comment by mavasani** [comment]
@grosch-intl Note that you can also write a DiagnosticSuppressor that detects and suppresses IDE0270 instances when fired on code patterns that you want to retain in original form.

**Comment by grosch-intl** [comment]
> Note that you can also write a DiagnosticSuppressor 

Thanks, @mavasani.  Guess I have a new thing to add to my "to learn" list :)

**Comment by grosch** [comment]
Finally got around to figuring this out.  Pasting my solution here in case somebody else comes across this issue.

```csharp
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public class SimplifyIfDiagnosticSuppressor : DiagnosticSuppressor {
    private readonly SuppressionDescriptor _descriptor = new("HIDE0046", "IDE0046", "Suppress if there is an 'else' clause that just throws an exception.");
    public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions => ImmutableArray.Create(_descriptor);

    public override void ReportSuppressions(SuppressionAnalysisContext context) {
        foreach (var diagnostic in context.ReportedDiagnostics) {
            if (context.CancellationToken.IsCancellationRequested)
                return;

            var node = diagnostic
                .Location
                .SourceTree
                ?.GetRoot(context.CancellationToken)
                .FindNode(diagnostic.Location.SourceSpan);
            
            if (node is not IfStatementSyntax ifStatement || ifStatement.Else?.Statement is not ThrowStatementSyntax)
                continue;
            
            context.ReportSuppression(Suppression.Create(_descriptor, diagnostic));
        }
    }
}
```
