### ISSUE TITLE
Sticky scroll doesn't work in C# when Block Structure Guides are disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68310]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sticky-scroll-doesnt-work-in-C-when-Bl/10372373)._

---
[severity:It bothers me. A fix would be nice]
I like the new sticky scroll feature presented in VS 17.6, but unfortunately it doesn't work when Block Structure Guides are disabled in C#, settings Options->Text Editor->C#->Advanced->Block Structure Guides.

![image](https://github.com/dotnet/roslyn/assets/1408396/35120d3f-adf6-4427-b326-2fe65ba7f23e)

I've also tested C++ and XAML which uses settings Options->Text Editor->General->Show structure guide lines. Here the feature sticky scroll works independently if it's enabled or not.

![image](https://github.com/dotnet/roslyn/assets/1408396/8c440dc1-7bb5-4d99-ab98-ac2a75efc1dc)

In actual state it's confusing in C#. The Sticky scroll is enabled but it doesn't work. At least there should be some note that it's necessary to enable Block Structure Guides or should be enabled automatically when Sticky scroll is enabled.

Thank you for consideration.

---
#### Feedback Bot on 5/23/2023, 07:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@olegtk can you route?

**Comment by sharwell** [comment]
Maybe we remove the check box for "Show declaration level constructs" because it duplicates the "Show structure guide lines" setting?

**Comment by rachlep** [comment]
I've reported this issue on Developer Community. I'll add just small note.
When **Show guides for declaration level constructs** is enabled, it looks like:
![image](https://github.com/dotnet/roslyn/assets/129518462/6743beb3-04ca-452d-a9af-453e4b6e530d)
When **Show guides for code level constructs** is **enabled too**, it looks like:
![image](https://github.com/dotnet/roslyn/assets/129518462/b97b3409-097e-4a9b-ae98-2399fe1d11fa)

**Comment by Rachvel** [comment]
I've reported this issue on Developer Community. I'll add just small note.
Without both checkboxes enabled, it looks like:
![image](https://github.com/dotnet/roslyn/assets/129518462/144917f9-2683-4c90-838b-c6d43dc059b3)
When **Show guides for declaration level constructs** is enabled, it looks like:
![image](https://github.com/dotnet/roslyn/assets/129518462/6743beb3-04ca-452d-a9af-453e4b6e530d)
When **Show guides for code level constructs** is **enabled too**, it looks like:
![image](https://github.com/dotnet/roslyn/assets/129518462/b97b3409-097e-4a9b-ae98-2399fe1d11fa)

**Comment by CyrusNajmabadi** [comment]
Closing out on the roslyn side as we're implementing the api properly.  If editor wants to do something here, it can happen on their end.  Note: i think they shoudl still query us for the structure information, and they can turn on sticky scroll still.
