### ISSUE TITLE
VB.Net Pretty listing (reformatting) of code changes floating point number

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68323]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VBNet-Pretty-listing-reformatting-of-/10374029)._

---
[severity:It bothers me. A fix would be nice]
To reproduce the problem, create a new VB.Net project and add the following lines:

```
Dim dbl As Double
dbl = 0.1382549
```

If the `Pretty listing (reformatting) of code` option is on (the default setting), the Visual Studio editor will change the second line:

```
Dim dbl As Double
dbl = 0.13825489999999999   
```

I understand that internally, the number I want is the same as the number the editor changes it to, but its much more difficult to read.

Other numbers that don't have exact floating point representations don't seem to have this problem. For example, the editor does not change `3.14159` to `3.14158999999999988262`. 

BTW, that number isn't random. It's a torque conversion factor from lbf-ft to kgf-m.

Cory

---
#### Feedback Bot on 5/24/2023, 08:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
