### ISSUE TITLE
VSI tests should export screenshots and other debugging build artifacts.

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6832]

**Comment by TyOverby** [comment]
@dpoeschl @brettfo 

Brett suggested that we inline the images as Base64.

**Comment by amcasey** [comment]
I believe @tannergooding already set up a mechanism whereby the bin directory is zipped up and attached to the run results.  Unfortunately, it only happens for failed runs, not for successful runs or aborted run (esp timeouts).

**Comment by TyOverby** [comment]
@amcasey Looks like that is indeed what is happening, @brettfo is working on a solution!

**Comment by jasonmalinowski** [comment]
Removing contributor pain tag -- we agree this is pain for contributors, but shouldn't be in our all-up list.

**Comment by davkean** [comment]
Screenshots are now under the Screenshots folder in the build directory.
