### ISSUE TITLE
Generated field is not working well since the last update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68322]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generated-field-is-not-working-well-sinc/10374413)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.5.4]
Generated field is not working well since the last update. It's not taking the proper type, it's outputting everything to object

---
#### Feedback Bot on 5/24/2023, 09:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Metalfution** [comment]
The problem occurs when you want to generate fields by the constructor parameters. I attach photos so you understand my explanation
![1](https://github.com/dot
![2](https://github.com/dotnet/roslyn/assets/80608745/b479e071-c341-4d3f-afa4-8d35c6def821)
net/roslyn/assets/80608745/af235
![3](https://github.com/dotnet/roslyn/assets/80608745/e8e4a8b2-490b-45c9-baa3-925408a42a70)
938-fbc2-4dce-930d-baee77c508c3)

**Comment by Metalfution** [comment]
I just did another test and the error occurs when the class is instantiated only with new, when the class is explicitly instantiated using new and the class does not occur.

![1](https://github.com/dotnet/roslyn/assets/80608745/33eb7205-7661-4e6c-9b9f-02a927599fad)
![2](https://github.com/dotnet/roslyn/assets/80608745/2c9d9c3e-c838-4bf5-baff-01d641363763)

**Comment by CyrusNajmabadi** [comment]
Ok.  So this is about generate-field working well with implicit-object-creation.  Thanks! :)
