### ISSUE TITLE
BasicWPF VSI test fails

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6833]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/34/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

As part of https://github.com/dotnet/roslyn-internal/pull/376, I'm disabling this test.

**Comment by amcasey** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/17a50bc675cb1572d7d827594642830bfcab2bc7.
