### ISSUE TITLE
HotReload crashes with "An item with the same key has already been added"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#68335]
![image](https://github.com/dotnet/roslyn/assets/31348972/6f8a4fdb-f404-407d-b733-087cea95de06)

I don't have a minimal repro yet, but:

https://github.com/dotnet/roslyn/blob/3acd33d08599f6d63e1c70e3ab2f40e9c350b6b4/src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs#L497 At this line, a duplicate named type symbol is added.

The case involves nested classes, so I'm wondering if it's related to this: https://github.com/dotnet/roslyn/blob/3acd33d08599f6d63e1c70e3ab2f40e9c350b6b4/src/Compilers/Core/Portable/Emit/EditAndContinue/SymbolChanges.cs#L467

where the deletion of the method will add containing types, then we get another change for the same type.

**Comment by davidwengier** [comment]
@Youssef1313 next time you hit it, can you capture a dump and share it (privately on Discord is fine), or even just switch your debug frame to the `CalculateChanges` method and see what is in the `edits` parameter and share that? 

I tried to create a couple of failing tests in https://github.com/davidwengier/roslyn/commit/f15cf980cbefe41e288c059dd076fcdd7a3f8f45 but sadly they both pass. Ordering of the changes in the file don't seem to matter, we still produce the right edits, and emit works fine. I think you must be hitting a specific case where we don't produce edits that we expect in emit.

**Comment by nickrandolph** [comment]
Hey @davidwengier can you point me at how I create the dump you requested?

**Comment by nickrandolph** [comment]
Here's a screenshot showing the `edits` parameter:
![image](https://github.com/dotnet/roslyn/assets/1614057/b2fea006-4970-4b30-b19b-361dd08676ee)

**Comment by nickrandolph** [comment]
The issue seems to be that when calculting changes for MainPage_Bindings (which is a nested class within MainPage), the MainPage type is added to the dictionary of changed types. Then on the next iterationg, when the MainPage edit is being processed, it throws the exception because MainPage is already in the changes dictionary

**Comment by Youssef1313** [comment]
@davidwengier fwiw, I'm suspecting the dictionary is trying to use reference equality. It's created using the parameterless constructor where it should have been supplied `SymbolEqualityComparer.Default`. Just a *guess*

**Comment by nickrandolph** [comment]
> Thanks @nickrandolph! I see you have `Replace` edits there, my tests don't cover that scenario so will see if that is the trick. That's hopefully enough for me to repro the issue.
> 
> If you've caught the exception under the debugger in VS, the easiest way to create a dump is from the Debug menu, "Save Dump As...".

@Youssef1313 will share the dump with you. Let me know if you need anthing more

**Comment by davidwengier** [comment]
The issue is that `[CreateNewOnMetadataUpdate]` is being used on a nested type and its containing type. Suspect this was just not part of any scenarios of the original design, so missed in testing.

FYI @tmat in case you had any thoughts about appropriate usage here :)

**Comment by nickrandolph** [comment]
I can try again but I think the issue exists even if we remove the attribute off the nested type

**Comment by davidwengier** [comment]
The order of edits produced is also vital. Even with the attribute on both types, if the compiler sees the edit for the containing type first, then things work.

But the good news is I got a repro in a failing test

**Comment by nickrandolph** [comment]
Removing the `[CreateNewOnMetadataUpdate]` attribute from the nested type gives the following changes and the same exception raised. I think this issue is more due to the ordering of changes, rather than the inclusion of the attribute on the nested type
![image](https://github.com/dotnet/roslyn/assets/1614057/80447bfd-abfc-40bc-aa73-80482a2c3094)

**Comment by davidwengier** [comment]
PR opened. FYI, it's a long weeked in the US so I've no idea if anyone will be around to look at it for a couple of days.

**Comment by nickrandolph** [comment]
@davidwengier is there a way that I can test this fix using the packages generated by the CI? I've tried referencing the packages from my test app but it seems that VS just defaults to using the version packaged with VS.

**Comment by davidwengier** [comment]
You shoudl be able to clone my fork, switch to the branch, and run `./build.cmd -restore -deployExtensions -launch` and that should run an instance of VS with the changes.
