### ISSUE TITLE
SemanticModel.GetDeclaredSymbol(node) returns null for ParameterListSyntax of a primary constructor

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#68341]
**Version Used**:

Version 17.7.0 Preview 2.0 [33722.583.main] 

**Steps to Reproduce**:

```
class C(int a);
```

`SemanticModel.GetDeclaredSymbol(node)` with the syntax node that represents `ParameterListSyntax` should return the constructor symbol, but returns null.

**Comment by AlekseyTs** [comment]
I think that is By Design. The list syntax doesn't declare any symbol. This is true for records as well.

**Comment by tmat** [comment]
Why wouldn't it declare a constructor? Especially in case where there are no parameters, there is no other node that declares the constructor.

```
class C();
```

**Comment by AlekseyTs** [comment]
> Why wouldn't it declare a constructor? Especially in case where there are no parameters, there is no other node that declares the constructor.

If I remember correctly, with taken an approach where type declaration declares both the type and the constructor in this case.

**Comment by AlekseyTs** [comment]
If you would like to propose a behavior change for an API, consider submitting an "API proposal".
