### ISSUE TITLE
CSharpEditAndContinue times out

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6834]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/35/consoleFull#-2070834298ff246aa2-2f63-4c37-a2a7-7003b4a3f43e

**Comment by TyOverby** [comment]
This looks like another bug.  DiaSymReader is breaking things over in https://github.com/dotnet/roslyn/pull/6823 too.

**Comment by amcasey** [comment]
It passes when I copy Microsoft.DiaSymReader to the same folder as System.IO.FileSystem (as in https://github.com/dotnet/roslyn/issues/6829).

**Comment by jasonmalinowski** [comment]
Fixed with #6841.
