### ISSUE TITLE
Sticky Scroll still thinks it is in try block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68340]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sticky-Scroll-still-thinks-it-is-in-try-/10370008)._

---
[severity:Other]
Sticky Scroll is great!  It helps to see where I am working.  I noticed that it still thinks it is in the try{} block when I scroll down into the catch() or finally{} block. In the screen shot, I am about to scroll down past the catch{} and finally{} block but as I do, the try is still pinned to the top instead of the catch or finally.  Not a big deal, just thought I'd let you guys know, thanks! 

---
#### Feedback Bot on 5/21/2023, 05:52 PM: 

(private comment, text removed)
#### Chris Wang [MSFT] on 5/23/2023, 00:21 AM: 

(private comment, text removed)
#### Denny Peltz on 5/23/2023, 08:29 AM: 

(private comment, text removed)
#### Feedback Bot on 5/24/2023, 01:16 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SkyGen** [comment]
About to scroll down into the catch{} or finally{} block: 

![image](https://github.com/dotnet/roslyn/assets/4681646/0d8069ca-f527-4305-809f-07c61c12594c)

___

In the catch{} block: 

![image](https://github.com/dotnet/roslyn/assets/4681646/5c9f4bab-bcb8-4219-b44e-0d6ac5f5dbe5)

___

In the finally{} block: 

![image](https://github.com/dotnet/roslyn/assets/4681646/90aa955b-e8f3-4721-b3d6-cdaee4aa43c5)

**Comment by CyrusNajmabadi** [comment]
Not repro:

![Image](https://github.com/user-attachments/assets/953cdefb-a0c7-49fa-8f9f-e521149dcf53)

We show the parent and inner headings.
