### ISSUE TITLE
CSharpReplIdeFeatures times out 

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6835]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/40/consoleFull#395803123ff246aa2-2f63-4c37-a2a7-7003b4a3f43e

**Comment by amcasey** [comment]
Once I work around the missing dependencies (e.g. https://github.com/dotnet/roslyn/issues/6834, https://github.com/dotnet/roslyn/issues/6828, https://github.com/dotnet/roslyn/issues/6829), the issue appears to be that the lightbulb isn't appearing.

**Comment by amcasey** [comment]
Lightbulb failure is due to https://github.com/dotnet/roslyn/issues/6587.

**Comment by amcasey** [comment]
Fixed by https://github.com/dotnet/roslyn/commit/17a50bc675cb1572d7d827594642830bfcab2bc7.
