### ISSUE TITLE
Cursor jumps while renaming in the editor

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#68374]
When doing a rename, after clicking to focus the editor, and overtyping part of the identifier being renamed, I can see the cursor jumping to the start of the identifier, then back to the correct position, which is a little annoying. Worse though, is that after a while it seems to stop jumping back to the correct position. See below in the GIF where the "ed" I typed ends up being at the start of the identifier. Could be typing speed related, not sure.

![RenameCursorIssue](https://github.com/dotnet/roslyn/assets/754264/d5ab7c3d-fc92-46a7-9822-5cbde2707718)

**Comment by jasonmalinowski** [comment]
@ryzngard I think you were investigating something like this at one point, right?
