### ISSUE TITLE
Flaky CrossLanguage VS integration test

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6837]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/35/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

**Comment by amcasey** [comment]
```
Failed to delete project files. Look at FileHandlesDump.txt to see which process is holding onto CSProj. 
```

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.
