### ISSUE TITLE
Flaky CsharpCodeActions test

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6838]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/252/consoleFull#70755144648b422d4-e1dd-42d0-bad1-ef3579de49b9

**Comment by amcasey** [comment]
This looks like a type load failure.

**Comment by amcasey** [comment]
@TyOverby you might want to try unskipping this test now that @jasonmalinowski's fix is in.

**Comment by TyOverby** [comment]
@amcasey I'll do this in my next PR.

**Comment by TyOverby** [comment]
Re-enabling here:

https://github.com/dotnet/roslyn-internal/pull/392

**Comment by TyOverby** [comment]
@amcasey @jasonmalinowski 

This is happening again

[machine1](http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_dbg_eta/419/consoleFull#70755144648b422d4-e1dd-42d0-bad1-ef3579de49b9)

[machine2](http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_eta/420/consoleFull#-17027998479a7715dc-d02b-49e9-b7c4-462b8475d445)

**Comment by TyOverby** [comment]
Disabled in https://github.com/dotnet/roslyn-internal/commit/38c3ea3d5ca9fe71ca81a0be3b455b8281747c3e

**Comment by davkean** [comment]
@jmarolf We've just enabled logging to make this easier to diagnose on Jenkins, can you reenable in a PR and retest many times to see if you can repro this? 

This falls under the 48 hours flaky test rule.

**Comment by davkean** [comment]
@jmarolf Ignore this - @dpoeschl's going to do a single run with all the disabled tests -reenabled to capture more data about the actual failures.

**Comment by jmarolf** [comment]
@davkean I wait 10 minutes and things take care of themselves :smile:

**Comment by davkean** [comment]
Dup'ing this against https://github.com/dotnet/roslyn/issues/6906, which will gather more data for these failures. We'll reopen when we have more data.
