### ISSUE TITLE
Implicitly Captured Closure - use attribute to instruct compiler to create separate DisplayClasses

### ISSUE THREAD

**Issue by dnarayan** [dotnet/roslyn#68407]
When a method has multiple lambda functions which capture variables, all variables are captured together in a single 'DisplayClass'. This means that ALL of the variables will remain alive as long as ANY of the lambdas are still alive. This is discussed here: https://www.jetbrains.com/help/resharper/ImplicitlyCapturedClosure.html

This is a problem if some of those variables are holding onto lots of memory and the lifetime of some of the lambdas is long. This is frequently an issue where a method processes some data using Linq, then sets up subscriptions to events using lambdas (such as through System.Reactive), in the same method. 

## Proposal

Allow an attribute `NarrowCapture` to be attached to a lambda which instructs the compiler to create a separate DisplayClass for that lambda, and box any variables that are shared with other lambdas. Additionally allow attributes to be placed on the Action/Func parameters of a method, and follow these so the attribute does not need to be defined with every usage.

**Pros** - Gives developers a tool to control the lifetime of their variables without needing to create separate methods. Massive potential savings on memory leaks.
**Cons** - Performance / memory hit due to additional boxing and extra classes. Somewhat larger assembly size.

## Example
``` C#

// Tells the compiler to create a separate DisplayClass if on a lambda or a method parameter
public class NarrowCaptureAttribute : Attribute { }

public class MyForm : Form
{
    public MyForm()
    {
        var caption = "Hello";

        //Lots of memory which currently is held for the life of ALL lambdas
        var arr = new double[100_000_000]; 

        //Lambda 1, marked NarrowCapture, captures arr, caption
        var sum = Enumerable.Range(0, arr.Length).Sum([NarrowCapture](i) => arr[i] + caption.Length); 

        //Lambda 2, captures caption, sum
        Shown += (sender, args) => Text = $"{caption} :: {sum}"; 

        //Lambda 3, captures caption
        SizeChanged += (sender, args) => Text = $"{caption} Size Changed"; 
    }

    //For the method in general - will be alive until all related lambdas are dead
    private class MockDisplayClass 
    {
        //This is boxed because it's used in the [NarrowCapture] lambda so it can be shared
        public StrongBox<string> caption; 

        public double sum;

        //This does not need arr - because it's not used in the remaining two lambdas not marked with [NarrowCapture]
    }

    //For Lambda 1 - will die with Lambda 1
    private class NarrowMockDisplayClass1
    {
        public double[] arr;
        public StrongBox<string> caption;
    }
}

//Example where a method parameter has [NarrowCapture], so any lambdas used *directly* would get this applied.
static double Sum<T>(T[] arr, [NarrowCapture] Func<T, double> selector)
{
    return arr.Sum(selector);
}
```

I'm not fully aware of how the compiler works - please excuse me if this is way off the mark for how C# works.

**Comment by jcouv** [comment]
From discussion with @jaredpar, this is not something we're likely to do. The cost is high because the implementation for closures is complicated and we rarely touch it, and the benefit doesn't seem to warrant the cost/risk. 
For users who need to control the lifetime more finely the workaround is to split the code into helper methods.

**Comment by CyrusNajmabadi** [comment]
In a similar vein, perhaps it would make sense for someone to write an analyzer that looked for the attribute and then had you null-out values no longer needed so they could be gc'ed and not kept alive by a larger closure. 

In other words, I don't think we should change codegen. I think if there is interest, the investment should go into other tooling to guide the user to rewriting to behave in the manner this group wants.

**Comment by dnarayan** [comment]
Thanks I understand. I'm sure if it were easy, it would have been done way back in 2007 (https://learn.microsoft.com/en-gb/archive/blogs/ericlippert/fyi-c-and-vb-closures-are-per-scope). 

Despite using C# for more than 10 years, I didn't even know this was a thing, until I told one a co-worker how I spent three hours trying to figure out a memory leak - and they said they'd have a look. They found it an hour later because they use Rider and Rider shows a warning that you're creating a possible memory leak. I use VS, and it does not have this warning.

![image](https://github.com/dotnet/roslyn/assets/5045276/10f6ec51-53ce-45c3-bd1b-4338872e3901)

In hindsight, of the memory leaks at my company, probably about 30% are this. In the past, I would just give up trying to fix the leak "correctly" and would just set variables to `default` - which worked, and I now understand is the easiest of the three ways to resolve this issue (the others being to separate out closures into different methods, or just not use closures). 

As you say, the benefit is heavily muted by adding an attribute (which developers would have to know about and use), and many don't even know this is a side effect for how closures work - so they'd get the memory leak despite the attribute being available. A more impactful change would be to eliminate this as a source of memory leaks, but I can't suggest how to do this without some negative impact.

In any case, thank you for addressing the feature request so promptly.
