### ISSUE TITLE
Copy and Paste with double quotes is inserting backslash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68414]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Copy-and-Paste-with-double-quotes-is-ins/10380311)._

---
[severity:It bothers me. A fix would be nice]
I had an original string like:

```
"Pump 1 Control"
```
I edited it to be:

```
"Pump " + pump + " Control"
```
where pump was a string variable. I copied:

```
" + pump + "
```
Then selected the 1 in the original code and pasted and got:

```
"Pump \" + pump + \" Control"
```
Had to CTRL-Z to remove the inserted backslashes.

---
#### Feedback Bot on 5/31/2023, 08:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by neo302** [comment]
Please fix this.  This is painful.

**Comment by CyrusNajmabadi** [comment]
This is working as expected.  The editor option to turn this off is: 

![image](https://github.com/dotnet/roslyn/assets/4564579/b421e638-24f5-413a-81ae-89dd0be41e6a)
