### ISSUE TITLE
F12 for navigating to method body doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68431]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F12-for-navigating-to-method-body-doesn/10381089)._

---
Sometimes when I use the F12 button to navigate to method body, I receive a message saying "Cannot navigate to the symbol under the caret"

---
#### Feedback Bot on 6/1/2023, 01:45 AM: 

(private comment, text removed)
#### Feedback Bot on 6/2/2023, 01:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of any repro at all.
