### ISSUE TITLE
Staying out-of other currencies to bitcoin

### ISSUE THREAD

**Issue by Solotuyo** [dotnet/roslyn#68436]
## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Operations
{
     public class ISwitchExpressionOperation
     {
+        public bool IsExhaustive { get; }
     }
```

## Usage Examples

``` C#
// some lines of code here
```

**Comment by CyrusNajmabadi** [comment]
@Solotuyo please update your title and description to something more reasonable.

**Comment by jcouv** [comment]
`ISwitchExpressionOperation.IsExhaustive` already exists. Closing with prejudice due to irrelevant title and seemingly inapplicable (and incomplete) description.

**Comment by svick** [comment]
@jcouv

> `ISwitchExpressionOperation.IsExhaustive` already exists.

In case it wasn't clear, that's the [API suggestion issue template for this repo](https://github.com/dotnet/roslyn/blob/99a97ee8/.github/ISSUE_TEMPLATE/api-suggestion.md)

**Comment by jcouv** [comment]
Ah, good point. Thanks
