### ISSUE TITLE
CS3002 text is different for nullable Func<>? than non-nullable Func<>. 

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/roslyn#68438]
**Version Used**: 

17.7.0 Preview [ ]

**Steps to Reproduce**:

CS3002 text is different for nullable Func<>? than non-nullable Func<>. 

I know this seems a small thing, but many people will search for the text instead of the error code. There is little helpful information anyway (I am separately discussing that with docs folks). Can we have these match? It seems quite nice to point out that it is the return type that is the problem.

The importance of this. It is low. It also looks easy to fix on the surface.

See the screen shot

![image](https://github.com/dotnet/roslyn/assets/5844318/1cca5d7f-0482-458d-b3ed-4bbe59d5fdd8)

**Diagnostic ID**:

CS3002

**Expected Behavior**:

Same message

**Actual Behavior**:

Different messages

**Comment by CyrusNajmabadi** [comment]
Is cls compliance a thing that is still cared about?  I haven't seen the topic come up in like 10+ years now.

**Comment by svick** [comment]
I'm confused. In the screenshot, the difference between the first two warnings seems to be because one is about the return type of a method (CS3002) and the other is about the type of a property (CS3003).

Or is there some other difference that I'm missing?

**Comment by jcouv** [comment]
It looks like the different message is because one is for a return type position of a method, but the other is for the type of a property. I'll go ahead and close as by-design. Thanks
