### ISSUE TITLE
Fuzz test the incremental state table

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#68459]
It feels like the [NodeStateTable](https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs) tends to have bugs resulting from subtle interactions between steps and across rounds. It may be a good candidate for fuzz testing.

We could write some test code to generate graphs with random arrangements of transforms, operators and so on, random sets of inputs, and then perform random sequences of edits (add, modify, remove of original input).

We could check the output of such tables against a "non-caching" evaluation of the inputs at a given point, or somehow manually construct the outputs we expect based on the operators and transforms in use.

Ideally the code which generates the fuzz-test could also write out a unit test which performs a test of the exact same scenario (i.e. creates the same graph and sequence of inputs which failed during fuzzing).

We have at least one place where we already do fuzz testing, in [TextChangeTests.cs](https://github.com/dotnet/roslyn/blob/826e1770eedb6d8d44a054c9e3ea6569e7ec5970/src/Compilers/Core/CodeAnalysisTest/Text/TextChangeTests.cs#L960), which could be useful as a starting point.

**Comment by chsienki** [comment]
I think this is a great candidate for fuzz testing. My thoughts on how to do it:

1. Construct a random graph of transformations (potentially by applying some random set of operations in a random order).
2. Generate a set of inputs
3. Run the graph on said inputs in a new generator driver (that has no cached state).
4. Randomly modify the inputs.
5. Re-run the graph through the driver created in step 3 with the modified inputs and record them
6. Run the graph with the modified inputs on a new driver instance
7. Check that the outputs from 5 and 6 match

That will allow us to check that for a given set of inputs the 'short circuited, used cache' behavior exactly matches the 'always added, didn't use the cache' version, which should always be true, and where we've seen bugs occurring when it doesn't.
