### ISSUE TITLE
the rename variable utility renames more variable then needed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68464]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/the-rename-variable-utility-renames-more/10385413)._

---
![Screenshot 2023-06-07 095445.png](https://aka.ms/dc/image?name=B08105d7d41324295a41648b3f6c256da638216998668327852_Screenshot_2023-06-07_095445.png&tid=08105d7d41324295a41648b3f6c256da638216998668327852)
as you can see, the rename utility rename variable from other scope just because they have the same name, although it doesnt cause bug yet

---
#### Feedback Bot on 6/7/2023, 01:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  Closing out.
