### ISSUE TITLE
Refactor code to specified region

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactor-code-to-specified-region/10383249)._

---
When using quick actions to refactor methods or properties, have a way to specify which new or existing code region the new method/property should be appended (or prepended) to.

---
#### Feedback Bot on 6/4/2023, 08:29 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
