### ISSUE TITLE
Sticky Scroll Issue for Nested Switch Cases

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68467]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Sticky-Scroll-Issue-for-Nested-Switch-Ca/10385367)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.6.1]
The marked switch must also get sticked to the top which isnt the actual case currently.

![image](https://github.com/dotnet/roslyn/assets/1408396/0b352b6f-9c5a-4636-a220-7c50a2da9304)

As you can see below it didnt stick and gone underneath

![image](https://github.com/dotnet/roslyn/assets/1408396/e9773567-8b03-4d2d-b3e0-992c96ad1348)

---
#### Feedback Bot on 6/6/2023, 11:32 PM: 

(private comment, text removed)
#### Feedback Bot on 6/7/2023, 06:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@olegtk for visibility.  I brought this up in Teams, but this is another case that IStructureTag2 doesn't work for.

**Comment by CyrusNajmabadi** [comment]
No repro:

![Image](https://github.com/user-attachments/assets/c0641556-cefb-4624-9149-52d9db4bb6d2)
