### ISSUE TITLE
C# 11 required properties do not compile on dotnet 6

### ISSUE THREAD

**Issue by Varorbc** [dotnet/roslyn#68478]
[Update(jcouv):] The ask is that required properties not be recommended by the IDE on .NET 6 or lower.

### Describe the bug
When I want to use required properties in a project targeting net6.0 with LangVersion set to latest I face some compile errors.

### To Reproduce

1.
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

</Project>

namespace Csharp11OnDotnet6;

public class Person
{
    public required string Name { get; init; }
}
```

2.`dotnet build`

### Exceptions (if any)

```
error CS0656: Missing compiler required member 'System.Runtime.CompilerServices.RequiredMemberAttribute..ctor'
error CS0656: Missing compiler required member 'System.Runtime.CompilerServices.CompilerFeatureRequi
redAttribute..ctor'
```

### Expected Behavior: build successful

**Comment by jcouv** [comment]
Those errors are expected. The "required members" feature is part of C# 11 and is only supported on .NET 7 and up.

**Comment by CyrusNajmabadi** [comment]
> 1.use The "required members" feature is part of C# 11 and is only supported on .NET 7 and up instead of

That's not the case here though.  That's what we support (and so we don't do additional work in non-supported scenarios).  If you added that attribute somehow, it would work (though we still dont' support that scenario), we don't block it.  So the error you're getting is correct.  The issue here is that those attributes are missing.

> 2.In .net 6 projects, IntelliSense should not recommend "required members"

Could you clarify what you mean?  We def show things in the completion list to help speed up typing, regardless of version.  We don't keep things out of the completion list as that can both be confusing, and it means if you try to type this, you can end up with some other piece of completed text.

**Comment by jcouv** [comment]
Added a summary to OP: "The ask is that required properties not be recommended by the IDE on .NET 6 or lower." and assigned to the IDE team to take a look.

**Comment by CyrusNajmabadi** [comment]
The ide behavior is expected here. This is a viable way to fix the issue. And if we don't offer it, it could be confusing to the user (I believe we had this Convo when creating the feature). The user is not told to pick this option. They choose it, if appropriate, from the options offered. And if they want this, that means they're ok with moving forward.

**Comment by CyrusNajmabadi** [comment]
That is one of the options offered :-)

**Comment by CyrusNajmabadi** [comment]
Can you give an example of what you mean?  What was your code, and which fix did you pick?

**Comment by CyrusNajmabadi** [comment]
@mavasani Do you know how 'code cleanup' does this work?

**Comment by mavasani** [comment]
Also adding @sharwell 

Choosing "Fix all warnings and errors set in EditorConfig" in the code cleanup profile leads to code cleanup sequentially attempting to fix all analyzer and compiler warnings and errors in code and considers all code fixer as potential candidates for providing a fix. It seems that we may need to add logic such that a code fixer can declaratively state that it shouldn't be included in code cleanup, and all fixers that fall in this bucket of "application introduces further compiler errors" should be marked for exclusion in code cleanup. @sharwell thoughts?

**Comment by CyrusNajmabadi** [comment]
Another option is to make this low-pri.  Or order after "declare as nullable".

That said, neither of these is truly better than the other.  So it's unclear to me what would be hte right behavior here as it depends on hte user.

**Comment by sharwell** [comment]
> `<LangVersion>latest</LangVersion>`

This is explicitly instructing the compiler to ignore the official support matrix for force required members to be allowed. As a result, the analyzers related to required members may report diagnostics, and those diagnostics would be fixed if the configuration instructs it to. The change expected here would be the analyzer(s) which suggest the use of required members should only do so when the necessary attribute is present. It sounds like we already check language version, so only the attribute check would be new.
