### ISSUE TITLE
Chain of code generators

### ISSUE THREAD

**Issue by SoftStoneDevelop** [dotnet/roslyn#68483]
Is it possible to build a chain of generators?
Generator1 generates files (which have markers for generator2) that generator2 analyzes and generates something else based on them.

In my case: I have a generator1 and I want to write a generator2 that will generate unit tests for me. But the problem is that the tests that it generates do not analyzed generator1 and therefore there are no methods that generator1 should have generated.

**Comment by jcouv** [comment]
Sorry, but no, generators cannot depend on each other.
Tagging @chsienki @jjonescz as FYI
