### ISSUE TITLE
Code Analysis - List Unused Variables, Procedures & Functions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Analysis---List-Unused-Variables-P/10164004)._

---
List Unused Variables, Procedures & Functions so that from this list individual items can be deleted or retained or just commented out.

---
#### Feedback Bot on 10/8/2022, 01:12 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is already present and we will gray out unreferenced private members.
