### ISSUE TITLE
VS Integration tests should check for unexpected image loads...

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/roslyn#6850]
We shouldn't have to wait for RPS to find out we're loading extra dlls in scenarios where we shouldn't.  Specifically, we should ensure that we have coverage for:

- Roslyn loading before a solution is opened
- VB is not loaded in C# projects and vice versa
- Interactive is not loaded if Interactive is not opened

**Comment by Pilchie** [comment]
We had support for this, but it got disabled.  Isn't there already a bug tracking it?

**Comment by KevinH-MS** [comment]
@Pilchie I looked, but I couldn't find one (my search-fu might be lacking though).

**Comment by Pilchie** [comment]
I think it's #4174.

**Comment by dpoeschl** [comment]
Closing as a dupe of #4174
