### ISSUE TITLE
Have CodeLens References Window Use Find-All-References window instead

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68515]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Have-CodeLens-References-Window-Use-Find/10188408)._

---
Now that we have the new FAR window it seems redundant to have to maintain a codelens window when they show the same information.

![image.png](https://aka.ms/dc/image?name=B5de6e61ef0cd48fd8e8a87f12fd8b480638030050691212039_20221102-095659-image.png&tid=5de6e61ef0cd48fd8e8a87f12fd8b480638030050691212039)

![image.png](https://aka.ms/dc/image?name=Bbcc349a1d3d74996b8f65a792a607f37638030050811084561_20221102-095711-image.png&tid=bcc349a1d3d74996b8f65a792a607f37638030050811084561)

---
#### Feedback Bot on 11/2/2022, 11:40 PM: 

(private comment, text removed)
#### Feedback Bot on 4/25/2023, 08:15 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This would be a platform/editor request @olegtk .  Roslyn doesn't own the codelens ui.
