### ISSUE TITLE
ctor code snippset doesn't work after 17.4.0 preview 5.0 update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ctor-code-snippset-doesnt-work-after-17/10186332)._

---
I updated my visual studio to 17.4.0 preview 5.0
and ctor code snippset doesn't work.
After I unchecked the last checkbox in Tools Menu/Options/Text Editor/C#/IntelliSense/using the new code snippset , it works again.
I want to know why did the new version checked this by default? or why ctor doesn't work after it was checked?

Some others reported the same problem with another version visual studio update. 
https://developercommunity.visualstudio.com/t/Code-snippet-ctor-doesnt-work-as-it-sho/10036360
But I updated every version, don't find problem in that version. I just killed the visual studio by installer itself this time.

---
#### Feedback Bot on 10/31/2022, 08:26 PM: 

(private comment, text removed)
#### Feedback Bot on 3/21/2023, 09:42 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
I don't repro this:

![Image](https://github.com/user-attachments/assets/3a9d9031-f435-4518-acf1-d3d845a4d477)

The snippet does what is expected:
