### ISSUE TITLE
Rename variable (Ctrl+R, Ctrl+R) renames also mentions in XML comments from other methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68520]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-variable-CtrlR-CtrlR-renames/10331631)._

---
[severity:It bothers me. A fix would be nice]
When renaming a variable inline (Ctrl+R, Ctrl+R) and select "include comments" then XML documentation comments from other methods are renamed too. This can cause confusion and problems with documentation generated from XML comments.
Example:

```
/// Example method one, uses start and end
/// The start argument
/// The end argument
public void Method1(int start, int end) { }

/// Example method one, uses start and end
/// The start argument
/// The end argument
public void Method2(int start, int end) { }

/// Example method one, uses start and end
/// The start argument
/// The end argument
public void Method3(int start, int end) { }
```

Now, when I rename the argument `start` in `Method2` then I end up with the following:

```
/// Example method one, uses anotherStart and end
/// The anotherStart argument
/// The end argument
public void Method1(int start, int end) { }

/// Example method one, uses anotherStart and end
/// The anotherStart argument
/// The end argument
public void Method2(int anotherStart, int end) { }

/// Example method one, uses anotherStart and end
/// The anotherStart argument
/// The end argument
```

As you can see, the contents of the XML comments of `Method1` and `Method3` have also renamed the `start` to `anotherStart`, thus the XML documents are out of sync. 

While it is correct that comments should also be renamed, I feel that this should NOT apply to XML documentation comments of other methods.

---
#### Feedback Bot on 4/5/2023, 07:52 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/5/2023, 11:12 PM: 

(private comment, text removed)
#### saurwein on 4/6/2023, 07:20 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/5/2023, 11:13 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/5/2023, 11:21 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/6/2023, 08:12 PM: 

(private comment, text removed)
#### Feedback Bot on 4/6/2023, 11:13 PM: 

(private comment, text removed)
#### Feedback Bot on 4/28/2023, 00:39 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Yes.  this is the idea behind "rename in comments".  It's basically saying "i expect to need to update this name in any comments it appears in"  If you only want to actually rename the ones in your own comment, you don't need to check this box.  Note: your references will need to use things like `<paramref ...>` which is the correct way to use those symbols in a doc comment.
