### ISSUE TITLE
OptionPagesDTE VS integration test is Flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6852]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/47/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

I've disabled the test in roslyn-internals

**Comment by TyOverby** [comment]
Disabled here

https://github.com/dotnet/roslyn-internal/pull/392/files

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.
