### ISSUE TITLE
Closing parenthesis of pointer-type cast is colored incorrectly

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#68536]
### Version Used

Compiler: 4.12.0-3.24470.4 (d799b056)  
.NET: 9.0.100-rc.1.24452.12  
Visual Studio Code: 1.93.1, `38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40`, x64  
C# Extension: v2.49.25  
C# Dev Kit Extension: v1.11.11

### Steps to Reproduce

1. Create or open a C# project in Visual Studio Code (Visual Studio untested).
2. Add the following code wherever syntactically applicable:
   ```cs
   var nullptr = (void*)0;
   ```
3. Observe the closing parenthesis being colored incorrectly.

### Expected Behavior

The parenthesis should have the same color as its opening counterpart.

### Actual Behavior

The parenthesis has the same color as the `*` operator.

**Comment by just-ero** [comment]
This is still the case today. Interestingly, the closing parenthesis after `(void**)0` is colored correctly.

**Comment by CyrusNajmabadi** [comment]
I don't repro in VS:

![Image](https://github.com/user-attachments/assets/05ae3fe3-dd6d-4704-815b-1f504a89ef5f)

or vscode:

![Image](https://github.com/user-attachments/assets/c496eab5-c12c-4e88-a030-2de31f0799be)

**Comment by just-ero** [comment]
Is this a theming issue, perhaps? I use the Visual Studio 2019 Dark theme, that (I believe) comes with the C# extension:
![Image](https://github.com/user-attachments/assets/3a4bdc3c-d115-42e0-b104-cc8a53c37d82)
