### ISSUE TITLE
CodeLens popup is empty 17.6.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68548]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CodeLens-popup-is-empty-1762/10388631)._

---
[severity:It bothers me. A fix would be nice]
Apparently this was supposed to be fixed 2 years ago but I occasionally see it now and then.  This is in 17.6.2
![CodeLens fail.png](https://aka.ms/dc/image?name=Bc6db23784d2343158192d426acce869e638219414560873446_CodeLens_fail.png&tid=c6db23784d2343158192d426acce869e638219414560873446)

---
#### Feedback Bot on 6/11/2023, 08:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RevitArkitek** [comment]
This still happens to me in 17.9.6

**Comment by CyrusNajmabadi** [comment]
@RevitArkitek can you link to a repro project where you are seeing this?

**Comment by RevitArkitek** [comment]
Can’t with anything I’m working on at the moment. When I have some time I can try some public repos and see if I can make it happen. I think it usually happens after I’ve already viewed the pop-up. But I’ll try to confirm that. Thanks.

**Comment by sharwell** [comment]
@CyrusNajmabadi It sometimes happens Roslyn.sln. I was never able to identify a clear trigger, but when it does happen, it seems to persist until the file is closed and reopened.

**Comment by RevitArkitek** [comment]
Still seeing this in 17.10.6.  
![image](https://github.com/user-attachments/assets/a3367bbd-b04b-4783-9fe4-92b41e7c60a7)
