### ISSUE TITLE
#line pragma false-positive error

### ISSUE THREAD

**Issue by quellatalo** [dotnet/roslyn#68543]
**Version Used**: NET 6

**Steps to Reproduce**:

1. Write code with `#line (2, 6) (2, 27) 15 "page.razor"` (as [this page](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#error-and-warning-information) suggests)
2. Compile fine
3. The IDE (checked on both Visual Studio/Rider) still hints error: `Line number expected`

**Expected Behavior**:

No error hints.

**Actual Behavior**:

Error: `Line number expected` hinted

**Comment by CyrusNajmabadi** [comment]
Closing out as i cannot repro this.
