### ISSUE TITLE
[Bug]: Autocomplete for `override` methods does not produce anything

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#68540]
## Version Used

Visual Studio Code 1.79.0

## Steps to Reproduce

1. Create or open any file in C# language mode.
2. Create or enter any class.
3. Type the `override` keyword to see suggestions pop up.
4. Attempt to select any of the suggestions.

## Expected Behavior

The method and its body should be generated, with the accessibility modifiers in correct order.

## Actual Behavior

Nothing is generated at all and the intellisense pop-up is dismissed.

**Comment by genlu** [comment]
@just-ero This could be [this VSCode issue](https://github.com/microsoft/vscode/issues/184924), which should be fixed in newer releases. Could you please upgrade your VSCode to the latest and try again? Thank you!
