### ISSUE TITLE
[SUGGESTION] Solution-wide analysis #104

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68553]
Currently C# Dev Kit reports errors/warnings about opened files.
Can it automatically report solution-wide errors/warnings?

Refer https://github.com/microsoft/vscode-dotnettools/issues/104#issue-1751362927

**Comment by ivanjx** [comment]
isnt full solution analysis already available in roslyn? the old c# extension has it. only not working in the new c# devkit extension

**Comment by segln** [comment]
I think so. But they closed and moved.

**Comment by segln** [comment]
I think so. But they closed and moved.
