### ISSUE TITLE
Inline type hints cannot be triggered by shortcut

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#68554]
Copied from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1779826

1. Open a C# file
2. Press Alt+F1

Expected behavior:

Inline type and parameter hints appear until Alt+F1 is released.

Actual behavior:

Hints do not appear. VS Code displays a message about accessibility features.

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is a vscode issue, not a roslyn one.
