### ISSUE TITLE
CSharpInteractiveCommands is Flaky

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6855]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p2/409/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

**Comment by TyOverby** [comment]
Disabled in https://github.com/dotnet/roslyn-internal/pull/392

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.
