### ISSUE TITLE
[BUG] wrong variable highlights

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68587]
From vscode-dotnettools created by [ivanjx](https://github.com/ivanjx): microsoft/vscode-dotnettools#71  

### Describe the Issue

vscode now highlights variables based on name instead of its scope.

### Steps To Reproduce

![image](https://github.com/microsoft/vscode-dotnettools/assets/12814796/ff897034-8fd0-405e-9c3e-ae702a5da571)

as you can see from the image above, my cursor is inside `Test2()` method but `val` inside `Test()` method is also highlighted.

### Expected Behavior

highlights variable correctly. in the case above, only `val` inside `Test2()`.

### Environment Information

- OS: Ubuntu 23.04
- VSCode: 1.78.2
- Extension: v2.0.206

**Comment by CyrusNajmabadi** [comment]
I'm not seeing vscode call into us at all for document highlights.  Maybe a vscode issue, or maybe we're not registering ourselves properly.
