### ISSUE TITLE
Duplicate variable declaration allowed

### ISSUE THREAD

**Issue by krzeatfev** [dotnet/roslyn#68583]
**Version Used**: 2.9

**Steps to Reproduce**:

bool a = false;

if (a == true)
{     
   bool a = true; 
}

**Diagnostic Id**: don't have.

**Expected Behavior**: like in c#, CS0128: A local variable or function named 'a' is already defined in this scope. Or error CS0136: A local or parameter named 'a' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter,

**Actual Behavior**: no error message, it works.

**Comment by CyrusNajmabadi** [comment]
Not seeing this:

![image](https://github.com/dotnet/roslyn/assets/4564579/a124a355-062d-4754-b54a-dac3b8342d2f)

This is the same for top level code:

![image](https://github.com/dotnet/roslyn/assets/4564579/65df2e1a-1fb8-49cb-bcea-14edc3c41b0c)

**Comment by jcouv** [comment]
I didn't understand the problem either and/or wasn't able to repro.
