### ISSUE TITLE
Var CodeLens

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68585]
From vscode-dotnettools created by [BachiMjavanadze](https://github.com/BachiMjavanadze): microsoft/vscode-dotnettools#78  

Please add `var` CodeLens feature. Give us ability to set font color and size. also give us ability to show only last part of the type

![image](https://github.com/wmjordan/Codist/assets/38082501/733f7b20-bbbc-4749-b53d-8667ff639337)

**Comment by CyrusNajmabadi** [comment]
Odd.  we export this:

![image](https://github.com/dotnet/roslyn/assets/4564579/52479cea-2adf-45d7-b8a2-146517c48bba)

So inlay hints should work.

**Comment by CyrusNajmabadi** [comment]
This is working for me in vs code:

![image](https://github.com/dotnet/roslyn/assets/4564579/00ecd153-f5d5-4759-b549-3f7144be5e57)

It need to be enabled of course.  For example:

![image](https://github.com/dotnet/roslyn/assets/4564579/5b5c9e1a-1d2b-4ce8-8866-f296d83c2543)
