### ISSUE TITLE
Battery/power save mode

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#68580]
## Summary

The IDE should provide a batter/power save mode, which automatically converts implicitly-executed background operations into explicitly-executed background operations. In other words, data used for IDE scenarios would be computed on-demand at the time it is needed, or at the explicit request of the user (e.g. via a "Refresh" button of some sort).

## Background and Motivation

Currently the IDE performs a number of operations implicitly while typing. These operations can consume significant resources in common editing scenarios, even when the result is not being used. For battery-constrained scenarios (e.g. travelling with a laptop), it may be desirable to avoid these implicit operations, even if it results in certain commands taking longer to execute.

## Proposed Feature

In power save mode, implicit background operations would be queued for execution, but not actually executed until the user attempts to use the result or explicitly triggers an update/refresh operation. Some (but not all) of the operations included in this are:

* Updating skeleton assemblies
* Live diagnostics
* Find References caches

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  This would need to be driven as a cross team initiative with approved and assigned stakeholders driving this.
