### ISSUE TITLE
Make brackets of class and methods bold

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68582]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Make-brackets-of-class-and-methods-bold/10212476)._

---

Making class and methods brackets bold will make them more readable and will be easier to detect where method ends.
ex.

![image.png](https://aka.ms/dc/image?name=Baacbf689cf4b4448929186d374809d39638048824336705442_20221124-142712-image.png&tid=aacbf689cf4b4448929186d374809d39638048824336705442)

---
#### Feedback Bot on 11/25/2022, 01:24 AM: 

(private comment, text removed)
#### Feedback Bot on 3/23/2023, 00:51 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
@olegtk i thin this should go to you guys.  Personally, i don't think its' a great idea.  And, rather, teh rainbow-braces feature you already have is a great way to make braces visible, and to be able to tell which braces match.  

Passing to you if you guys think more work is needed in this area.
