### ISSUE TITLE
Intellisense not work with interface

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68594]
From vscode-dotnettools created by [viethung9at1](https://github.com/viethung9at1): microsoft/vscode-dotnettools#108  

Type: <b>Bug</b>

After creating a interface, I write a class to implement it. But when I leave this class without the function implementation, IntelliSense don't send the error message to me until I build the program
The problem solved after I disable C# Dev Kit and leave C# extension run alone
Extension version: 0.1.83
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics          (6 x 2370)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|19.37GB (5.39GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/hung --remote=wsl+Ubuntu-20.04 --crash-reporter-id 8240bcb5-4470-4eff-89ea-3b3c2781c93a|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics (6 x 2370)|
|Memory (System)|9.40GB (5.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
bgfeh915:30763804
e440d664:30763025
pythonnosmt12:30757131

```

</details>

**Comment by CyrusNajmabadi** [comment]
Looking.

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  I see the error messages without needing to build:

![image](https://github.com/dotnet/roslyn/assets/4564579/adfd86b5-64ef-4114-bec3-c4539254ef15)

Need more info from user for a fuller repro.
