### ISSUE TITLE
[BUG] References Code Lens always enabled

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68591]
From vscode-dotnettools created by [tomschrot](https://github.com/tomschrot): microsoft/vscode-dotnettools#35  

Type: <b>Bug</b>

Even if checked off, references are always shown

Extension version: 2.0.206
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 4300U with Radeon Graphics          (4 x 2695)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (2.71GB free)|
|Process Argv|--crash-reporter-id 659d967e-9511-487a-99ad-c9ac54d283d9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30760978
pythongtdpathcf:30739705
pythonnosm12tcf:30757130

```

</details>

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  Turning this off:

![image](https://github.com/dotnet/roslyn/assets/4564579/fd6bed81-503a-40b8-a3ba-239ac41bedbd)

And i immediately see:

![image](https://github.com/dotnet/roslyn/assets/4564579/7a5282b7-b3ce-4aa0-9b44-e0b8044c91b0)

**Comment by MarkusRodler** [comment]
I think he means this option: 
![image](https://github.com/dotnet/roslyn/assets/14873906/6dc5d611-18ce-4be0-95d8-1132a56b7d8b)
It also has no effect for me. It always display code lens. I can only disable code lens globally.
