### ISSUE TITLE
[BUG] cannot rename symbols across projects

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#68593]
From vscode-dotnettools created by [ivanjx](https://github.com/ivanjx): microsoft/vscode-dotnettools#46  

### Describe the Issue

i have 2 projects: `mainapp.csproj` and `logic.csproj`. `logic` is referenced in `mainapp`. when i tried to rename a method or class in `logic` it only changed in the `logic` project itself and not `mainapp`.

### Steps To Reproduce

1. create 2 projects. one project is referencing the other.
2. create a method in one project that is used in the other project.
3. rename that method using F2 key.
4. the other project's method name is not renamed.

[repro.zip](https://github.com/microsoft/vscode-dotnettools/files/11678558/repro.zip)

### Expected Behavior

the other project's method name is renamed too.

### Environment Information

- OS: Ubuntu 23.04
- Visual Studio Code version: 1.78.2
- Extension version: v2.0.206

**Comment by jasonmalinowski** [comment]
This should now be fixed with version 2.0.212 that was released earlier today of the C# extension.
