### ISSUE TITLE
[Future] Lots of tests failing with Could not load file or assembly 'Microsoft.DiaSymReader, Version=1.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6862]
PR: [#6854](https://github.com/dotnet/roslyn/pull/6854) *Add an MSBuild log to output* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/1268/

**770 Test Failures:** (showing first 10)
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymBinderTests.GetReaderFromStream
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymBinderTests.GetReaderForFile
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestGetDocument1
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestMethods1
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestGetDocuments1
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestSymGetAttribute
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestAsyncMethods_GetAsyncStepInfo
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestAsyncMethods_Errors
Microsoft.DiaSymReader.PortablePdb.UnitTests.SymReaderTests.TestAsyncMethods
Microsoft.DiaSymReader.PortablePdb.UnitTests.MethodMapTests.GetRangesHiddenSP_Native

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @dotnet/roslyn-interactive

**Comment by ManishJayaswal** [comment]
@KevinH-MS - This may be another case of wrong binding redirects

**Comment by amcasey** [comment]
@jasonmalinowski I thought we (i.e. you) fixed this exact thing yesterday.

**Comment by jasonmalinowski** [comment]
Yes, in e7a3a3d1a59324c1d57638735f25357c22d6dec7. But that hasn't merged to future yet.

**Comment by davkean** [comment]
Has it been merged to future?

Sent from my Windows Phone
________________________________

**Comment by ManishJayaswal** [comment]
@davkean nightly merge to future might be broken.

**Comment by agocke** [comment]
Just merged

**Comment by natidea** [comment]
@agocke @jasonmalinowski can we close this bug now the fix has been merged into future, or are there any more instances?

**Comment by davkean** [comment]
At home, but I can't tell from Github if its been merged into future or not, Andy?

**Comment by davkean** [comment]
We're still hitting this (somewhat) randomly, @amcasey just hit on master.

This bug is getting stale, and well outside the 48 hours for flaky tests - can we please have @dotnet/roslyn-interactive team member look at this please?

**Comment by tmat** [comment]
Somehow the dll is built with version 42.42.42.42

**Comment by tmat** [comment]
Fixing.

**Comment by tmat** [comment]
Fixed by #7431

**Comment by BrainSlugs83** [comment]
This warning still comes up in the latest version of Visual Studio 2015.  This is the only relevant thing I can find when searching for the error message on Google.  What can we do to make this warning go away?

**Comment by davkean** [comment]
@BrainSlugs83 This error/warning is very specific to the Roslyn GitHub repro and is not talking about Visual Studio. 

What in particular are you hitting and where?
