### ISSUE TITLE
[Test Failure] CSharpGotoDefinition "Cannot navigate to the symbol under the caret"

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6863]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p2/414/consoleFull#-70887886987b2fba6-0f8e-4a04-a3ae-ceac18a86066

**Comment by TyOverby** [comment]
Disabled in https://github.com/dotnet/roslyn-internal/tree/5b487ded68ebecc50232748cdb744ad25c6b8e03

**Comment by davkean** [comment]
@dpoeschl Can you see if this failing consistently? If not, then close it out and wait for a failure with the new logging.

**Comment by dpoeschl** [comment]
Dup'ing this against #6906, which will gather more data for these failures. We'll reopen when we have more data.

**Comment by davkean** [comment]
This [failed again](http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_vsi_p2/), this time with information:

Failure is:

```
MESSAGE:
Expected notification text: [] Actual notification text: [Cannot navigate to the symbol under the caret.]
+++++++++++++++++++
STACK TRACE:
at Roslyn.VSHosting.Test.RoslynActions.RoslynVisualStudioAction.AfterExecute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\RoslynVisualStudioAction.cs:line 157 at Tao.Engine.DebuggableActionExecutor.AfterExecute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 120 at Tao.Engine.DefaultActionExecutor.AfterExecute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 50
```

```
![image](https://cloud.githubusercontent.com/assets/1103906/11602028/1e9898de-9a8c-11e5-85e6-0aaed00e28c3.png)

```

**Comment by davkean** [comment]
I disabled this in https://github.com/dotnet/roslyn-internal/pull/424

**Comment by dpoeschl** [comment]
Trying to get a failure on this in https://github.com/dotnet/roslyn-internal/pull/451

**Comment by dpoeschl** [comment]
Reenabled with logging in https://github.com/dotnet/roslyn-internal/pull/451

**Comment by genlu** [comment]
Hit this in #8783:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/286/

**Comment by dpoeschl** [comment]
Another case where the artifacts disappeared within 4 days. /cc: @davkean 

We had enabled dumps for this situation before, but the build artifacts are already missing so this is still unactionable for now. :frowning:

**Comment by jmarolf** [comment]
hit in https://github.com/dotnet/roslyn/pull/9259
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/357/

**Comment by dpoeschl** [comment]
See `<InternalShare>\public\davip\8867FailureArtifacts.zip` for a dump.

Basically, we change the text of an open document, close it (with the SaveFile=true flag), and then try to GTD or GTI. According to the dump above, this fails because the Document still has the _old_ text in it, not the text we told it to save.

**Comment by davkean** [comment]
We're seeing this in more runs. Both CSharp and VisualBasic go to definition failed in above linked.

**Comment by davkean** [comment]
Given both failed in the same run - this can't be a coincidence.

**Comment by TyOverby** [comment]
This is happening in at least `stabilization` and `future-stabilization`

**Comment by davkean** [comment]
Again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p2/lastCompletedBuild/testReport/(root)/CSharpGotoDefinition/Go_To_Def_opens_in_a_provisional_tab_if_document_wasn_t_already_open/

**Comment by davkean** [comment]
And again: https://github.com/dotnet/roslyn/issues/9615

**Comment by Pilchie** [comment]
Can you investigate here, since @dpoeschl is out this week?

**Comment by jasonmalinowski** [comment]
Roger.

**Comment by jmarolf** [comment]
:point_up: stealing from @jasonmalinowski

**Comment by jmarolf** [comment]
duping against https://github.com/dotnet/roslyn/issues/9602 which suffers from the same saved file issue
