### ISSUE TITLE
RegEx for "Nondeterminstic Compile Time Error" failure cause has false positives

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6865]
PR: [#6857](https://github.com/dotnet/roslyn/pull/6857) *[DON'T REVIEW] [TEST-ONLY] create a dump for a failing test* by @brettfo 
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/1278/

**Issue 1: Nondeterminstic Compile Time Error**
Nondeterministic failure occasionally seen building coreclr.  Retry the job.

@mmitche - Your XamlTaskFactory/CodeTaskFactory failure indications fail when NuGet restores the relevant packages. What should the regex actually be looking for?

**Comment by davkean** [comment]
@mmitche Do you remember what the actual error was that caused the failure so we can tighten the regex?

**Comment by mmitche** [comment]
Will take a look in a bit.  Its looking for CodeTaskFactory or XamlTaskFactory.

Sent from my Windows Phone
________________________________

**Comment by davkean** [comment]
I deleted the failure cause, @mmitche feel free to add it back - but tighten it so that it doesn't catch the source file itself.
