### ISSUE TITLE
'Use primary constructor' should not be shown above 'Initialize field'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#68671]
**Version Used**: 

**Steps to Reproduce**:

1. Create a field with the same name as a constructor parameter
1. Place caret on the constructor parameter
1. Press <kbd>Ctrl</kbd>+<kbd>.</kbd>

![image](https://github.com/dotnet/roslyn/assets/1408396/bf558ef0-5498-46f9-82d2-aafc49451181)

**Expected Behavior**:

'Initialize field' is shown above 'Use primary constructor'.

**Actual Behavior**:

'Use primary constructor' is shown above 'Initialize field'.

**Comment by CyrusNajmabadi** [comment]
Does not repro:

![Image](https://github.com/user-attachments/assets/e729563a-a27a-4ce7-944b-29c188922274)
