### ISSUE TITLE
Proposal: Short-circuit comparison with nullables

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6867]
Currently the compiler produces warnings for the following codes:

``` cs
var result = null > x;
var result = null >= x;
var result = null <= x;
var result = null < x;
```

But emits the code for checking `x` anyway.

In case of nullables and null-checked member access,

``` cs
var result  = x?.x > x.y;
```

It should be also short-circuited.

**Comment by HaloFour** [comment]
So for `var result = null > x` you're proposing that the compiler just emit the IL for `bool result = false`?

As for `?.`, the short-circuiting only applies to the member access expression.  It shouldn't leak to subsequent comparisons anymore than it should to method invocations using that expression as an argument.

**Comment by alrz** [comment]
@HaloFour (1) with short-circuiting comparison in place, the rhs would be considered as "unreachable code" so I think it shouldn't be emitted at least in an optimized build. (2) that's not specific to member access, I just mentioned it as a use case, assume that `x` is a `int?` so in case of `x` being `null`, then `x > 0` should be short-circuited.

**Comment by HaloFour** [comment]
@alrz Oh I see.  I guess the problem is that the behavior of these operators is not short-circuiting so this would be a breaking change from C# 6.0.

**Comment by gafter** [comment]
I don't think we want to take a breaking change.

**Comment by alrz** [comment]
Can't this be this kind of optimizations be optional? `x?.x > x.y` seems really more natural than `x?x > x?.y` or `x != null && x.x > x.y`.

**Comment by gafter** [comment]
@alrz Since the difference is observable, it isn't an optimization.

**Comment by alrz** [comment]
@gafter Anyway, it feels more natural this way. It would consider "breaking change" but it's debatable IMO.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
