### ISSUE TITLE
Prefer simple using statement setting not respected when "No"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prefer-simple-using-statement-setting-no/10394110)._

---
[severity:It's more difficult to complete my work]
No matter how I set the "Prefer simple 'using' statement" in settings (Text Editor/C#/Code Style/General) the behavior is **always** as if the option is "Yes", even when "No" is selected.

---
#### Feedback Bot on 6/19/2023, 01:02 AM: 

![image](https://github.com/dotnet/roslyn/assets/1408396/d2b9a64c-6cff-469e-aacb-aa9818c4bd5f)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This is the expected behavior. When the analyzer is disabled (as shown in the above case), we still have a refactoring available which can be used on-demand to convert a single specific using statement to the simplified form.
