### ISSUE TITLE
(Proposal) Signed Integer Literals

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#6868]
Signed Integer Literals
------------------------

This proposal it the extend the specification, so that the sign of an integer can consider as part of the literal. Not as previously as a separate unary operator.

**Specification Changes**

**SignedIntLiteral**
```
SignedIntLiteral ::= Sign? IntLiteral
Sign             ::= Negative | Positive
Negative         ::= '-'
Positive         ::= '+'
```
**IntegeralLiteralValue**
```
IntegeralLiteralValue  ::=  SignedIntLiteral | IntLiteral | HexLiteral | OctalLiteral
```

**Floating Point Literal**
```
DecimalPoint ::= '.'
FloatingPointLiteralValue ::= SignedIntLiteral DecimalPoint IntLiteral Exponent? |
                              Sign? DecimalPoint IntLiteral Exponent?
                              SignedIntLiteral Exponent
Exponent ::= 'E' SignedIntLiteral
```

----------------------------------------

**Implementation (partial)**

Modify the scanner so that information on whether the preceding token was / wasn't a Unary `MinusToken` or a unary `PlusToken`. So that this can be taken into account when determining the value for this literal, and if said valid is out of bounds.

How can we thread this sign information through the scanner and parser?
 * Extend [ParseExpression](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/VisualBasic/Portable/Parser/ParseExpression.vb#L79)    
  So that in the `UnaryMinus` and `UnaryPlus` cases, sign information is passed down.
 * Modify `ScanTokenCommon` to take an additional optional parameter, which indicates the sign.
 * Modify `ScanIntLiteral` to take an additional optional parameter, which indicates the sign.

[ScanIntLiteral  Scanner.vb](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Scanner/Scanner.vb#L2004)

```VB.net
Enum IntSign
  Negative   = -1
  NotPresent =  0
  Positive   = +1
End Enum


Private Function ScanIntLiteral( ByRef ReturnValue As Integer,
                                 ByRef Here As Integer,
                              Optional Sign As IntSign = IntSign.NotPresent
                               ) As Boolean
  Debug.Assert(Here >= 0)

  If Not CanGet(Here) Then Return False

  Dim ch = Peek(Here)
  If Not IsDecimalDigit(ch) Then Return False

  Dim IntegralValue As Integer = IntegralLiteralCharacterValue(ch)
  Here += 1

  While CanGet(Here)
    ch = Peek(Here)
    If Not IsDecimalDigit(ch) Then Exit While

    Dim nextDigit = IntegralLiteralCharacterValue(ch)
    If IntegralValue < 214748364 OrElse
       (IntegralValue = 214748364 AndAlso nextDigit < 8) Then

      IntegralValue = IntegralValue * 10 + nextDigit
      Here += 1
    Else
      Return False
    End If
  End While
  
  If Sign = IntSign.Negative Then IntegeralValue = -1 * IntegeralValue

  ReturnValue = IntegralValue
  Return True

End Function
```

**Comment by andrewjsaid** [comment]
What is the benefit of this proposal over the current situation?

**Comment by AdamSpeight2008** [comment]
It'll make it possible to express all of the values as a literal.
`Dim s0 As Short = -32768S` is an `Overflow` as it is being treated as `Dim s0 as Short = -(32768S)`

Which happens **ABS(*numerictype*.MinValue) - *numericType*.MaxValue = 1** not **0**

When it should be considered `Dim s0 As Short = (-32768)S` (doesn't compile)

Others Examples
```vb.net
Dim I1 As Integer = -2147483648I
Dim i2 As Integer = -2147483648%
Dim L1 As Long = -92233372036884775808L
```

**Comment by bbarry** [comment]
But -32768 is a valid 16-bit integer in .NET?

Is this only a VB problem?


    internal class Program {
        private static void Main() {
            MinLiterals();
            MaxLiterals();
        }

        private static void MinLiterals() {
            int i = -2147483648;
            Console.WriteLine(i); // -2147483648
            Console.WriteLine(i == int.MinValue); // True
            long l = -9223372036854775808L;
            Console.WriteLine(l); // -9223372036854775808
            Console.WriteLine(l == long.MinValue); // True
        }

        private static void MaxLiterals() {
            int i = 2147483647;
            Console.WriteLine(i); // 2147483647
            Console.WriteLine(i == int.MaxValue); // True
            long l = 9223372036854775807L;
            Console.WriteLine(l); // 9223372036854775807
            Console.WriteLine(l == long.MaxValue); // True
        }
    }

That compiles and prints exactly what I expect (there is no short integer suffix in C# so I skipped that one). The IL looks to be specifying the correct literal values as well.

Relevant bits in C# specification at §2.4.4.2 Integer Literals:

To permit the smallest possible int and long values to be written as decimal integer literals, the following two rules exist:

* When a *decimal-integer-literal* with the value 2147483648 (2<sup>31</sup>) and no *integer-type-suffix* appears as the token immediately following a unary minus operator token (§7.7.2), the result is a constant of type `int` with the value −2147483648 (−2<sup>31</sup>). In all other situations, such a *decimal-integer-literal* is of type `uint`.
* When a *decimal-integer-literal* with the value 9223372036854775808 (2<sup>63</sup>) and no *integer-type-suffix* or the *integer-type-suffix* `L` or `l` appears as the token immediately following a unary minus operator token (§7.7.2), the result is a constant of type `long` with the value −9223372036854775808 (−2<sup>63</sup>). In all other situations, such a *decimal-integer-literal* is of type `ulong`.

**Comment by AdamSpeight2008** [comment]
@bbarry Translated to VB.net
![vb](https://cloud.githubusercontent.com/assets/900107/11275152/282fe280-8ed4-11e5-94c2-1f345b8f1e2a.jpg)

**Comment by bbarry** [comment]
ok, playing around it looks like you have to write 

    Dim l As Long = -9223372036854775808UL

The instruction in the IL for this does have the negative literal (at least when compiled with 2015 rtm):

    ldc.i8       -9223372036854775808

but it seems strange to write UL when you are looking for a signed value.

Perhaps it would be better to extend the specification to specifically permit these decimal literal constants: `-32768S`, `-2147483648I`, `-9223372036854775808L` rather than introducing a new token. `-&H8000S` would be valid syntax for an integer literal under your spec changes, but `&H8000S` is already -32768 (presumably to meet some back compat history requirements).

**Comment by vladd** [comment]
Well, doesn't this introduce a reduce/reduce kind of ambiguity for an expression like `1-1`? It can be treated either as `[int literal 1] [int literal -1]` or `[int literal 1] [binary minus] [int literal 1]`.

**Comment by gafter** [comment]
As @vladd points out, this would break existing programs by interpreting the binary subtraction operator as part of a literal. That is not a breaking change we could accept.

**Comment by paul1956** [comment]
The compiler should be smart enough to figure it out. It only matters for the few (1-3) very specific values where it is currently an overflow error and fixing that error shouldn't be a breaking change. Everything except long has a simple workaround so maybe you just fix that or fix the error message to make it clear what the fix should be.

**Comment by bbarry** [comment]
A spec change that interprets the strings:

* `32768S`
* `2147483648I`
* `9223372036854775808L`

as 

* `32768US`
* `2147483648UI`
* `9223372036854775808UL`

under the semantic rule that the former values must be attached to a *unary-minus* operator should be sufficient, unambiguous and not break any existing programs (all 3 literals are currently compiler errors).

**Comment by paul1956** [comment]
The first one works but the second UL is interpreted as Decimal and requires a cast to Long (with Option Strict)
        Dim x0 As Short = -32768US
        Dim x1 As Long = CLng(-9223372036854775808UL)
![image](https://cloud.githubusercontent.com/assets/12789369/11316130/ff96837a-8fb3-11e5-9810-0a6adaec836d.png)

**Comment by Eyas** [comment]
Instead of the lexer considering the negative sign as part of the integer literal token, can't this proposal refer to to the AST stage: the parser (which sees no ambiguity between negation and subtraction) should consider "`Negate(Integer Literal)`" to be a negative integer literal in code? Errors about overflows would happen after the lexing phase, e.g. by inspecting the AST and thus being aware of positive vs negative values.

**Comment by gafter** [comment]
@Eyas The spec can be written to allow it, but not that way: the spec today doesn't have any concept of stages.

**Comment by Eyas** [comment]
Sure-- not talking about the spec *per se*, but rather that there is no inherent ambiguity in the AST grammar itself.

Getting into weeds on when to emit an error in a potential implementation by comparing it to other classes of errors occurring at different stages of the compilation process. Agreed the weeds are not particularly useful in the discussion phase.

**Comment by AdamSpeight2008** [comment]
The lexer should only see it as digits, and pass the interpretation up the AST.
So it as more information to determine if the value is/isn't in the range of the type.

**Comment by gafter** [comment]
While I have sympathy for the problem to be solved

```vb
Dim s As Short = -32768S ' does not compile
```

the proposal in this issue would be an incompatible language change. That would not be the way in which we would address the issue.
