### ISSUE TITLE
The LSIF generator should allow for a per-document timeout

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#68690]
We recently [ran into an issue](https://github.com/dotnet/roslyn/pull/68449) where a certain large construct in a source file caused terrible indexing for a single file. Although we can't predict in advance where we might have performance issues like this, it might be helpful if the indexer had a flag where we'd abort the indexing of a specific document after a certain timeout. Even if the timeout is high (many minutes), it'd avoid stalling an entire build pipeline when we run into an issue like this. We should of course still raise the issue so we know to investigate further.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
