### ISSUE TITLE
Outputting hover information consumes a huge amount of the LSIF indexing time

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#68691]
Right now computing the hover (i.e. quick info) information consumes about 50% of the total CPU time of an indexing run. There's a number of fixes we can make to help this:

- [ ] 50% of the time in the hover path (i.e. 25% of grand total) is computing the "awaitable" prefix we put before awaitable types or methods with awaitable return types. We don't have any caches on that path, and the process of computing it is expensive in its own right, since we have to check for GetAwaiter() extension methods. If we demand complete correctness, that last bit also makes it difficult to cache. There's a few options here: [a] completely skip computing it, since it's of less use in a browsing scenario or [b] add some caches and accept some inaccuracies, or [c] actually just make the direct code faster in some way.
- [ ] Right now if we index a number of projects in one go, we don't share any information between the projects. So if any framework type is consumed in more than project, we'll produce hover information for it in both cases, even if it could be potentially reused. So this might be creating more hover runs than necessary.
- [ ] A fair bit of the overhead is us computing minimally qualified quick info; it's possible there's some low-hanging fruit to speed up the minimal qualification. It's entirely possible that it just wasn't intended to be called this much in a batch operation.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
