### ISSUE TITLE
Proposal: Sealed Interface Inheritance

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#6869]
Currently, to prevent re-implementation of interfaces you must make the whole class `sealed`. I propose "sealed interface inheritance" which would prevent the re-implementation of interfaces either implicit or explicit in inheritors (without making the interface itself non-public).

``` cs
class Foo : sealed IBar, sealed IBaz
{
}
```

This of course needs CLR to be changed in order to expose the metadata.

**Comment by vladd** [comment]
Doesn't this require CLR changes?

**Comment by BreyerW** [comment]
I wonder: this couldn't be achieved by extending sealed keyword on method? we already have sealed override and maybe could be extended to interface members. Ur solution is shorter and possibly better express programmer intent but as you said ur solution require clr change. Maybe my solution require no or less change to clr?

**Comment by alrz** [comment]
@BreyerW `sealed` methods have no effect on interface re-implementation. it just prevents to override a particular method on a derived class, not explicit or implicit re-implementation of the interface. on the other hand, `sealed` interface inheritance would prevent that, whether it's explicitly or implicitly implemented in the base class.

**Comment by paulomorgado** [comment]
@alrz, what do you intend with this?

This mean that `Foo` implements `IBar` but, what?

Can you give examples of what you can and can't do with this?

**Comment by alrz** [comment]
@paulomorgado For example,
```cs
interface IBar { void Bar(); }
class Foo : sealed IBar { void IBar.Bar() {} }
class Baz : Foo, IBar { void IBar.Bar() {} } // illegal
```
As it turns out, this can be another option for issue described in the first section of [C# Design Meeting Notes for Feb 4, 2015](https://github.com/dotnet/roslyn/blob/master/docs/designNotes/2015-02-04%20C%23%20Design%20Meeting.md)

**Comment by paulomorgado** [comment]
Got it, @alrz!

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
