### ISSUE TITLE
The LSIF generator should emit warnings if the binlog is skipping projects

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#68692]
We ran into one issue where the customer was indexing a binlog, but since it was a binlog produced by a later step like pack (that was broken out from the main build), the binlog didn't actually have any compiler invocations since the compile targets were already up to date. The generator should probably emit warnings in this case.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
