### ISSUE TITLE
Optimize SourceText.CalculateChecksum by leveraging System.IO.Hashing

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/roslyn#68700]
### Context

[`SourceText.CalculateChecksum`](https://github.com/dotnet/roslyn/blob/50aa37f11d39a55f70254eca281749dc40cb52ee/src/Compilers/Core/Portable/Text/SourceText.cs#L576-L596) appears on a relatively perf warm paths based on [perf test runs](https://prism.vsdata.io/?query=c%3Dchecksum%20bf%3Dmicrosoft.codeanalysis.dll!Microsoft.CodeAnalysis.Text.SourceText.CalculateChecksum&eventType=cpu) (internal link)
There is a chance to optimise the perf via leveraging noncryptographic hash from `System.IO.Hashing` (e.g. `XxHash`) which is order of magnitude faster than `SHA1`

### Sugested approach

Partner with MSBuild team to bring `System.IO.Hashing` dependency into VS (and SDK) and then call it on `SourceText.CalculateChecksum` code paths that do not embed data into pdbs.

cc @davkean, @tmat, @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Isn't sha1 what we use though to compute the PDB checksums and whatnot?  We use either SH1 or SHA256 (the latter because i thought SHA1 was deprecated as something MS allows use of).

I'm sure we'd be happy to use a new impl of SHA1/256 that was faster.  But i'm not getting how we could switch to an entirely different hashing algorithm without, well, breaking the world.

**Comment by tmat** [comment]
@CyrusNajmabadi Change is not intended for PDB checksums, but for document content checksums for the IDE.

**Comment by CyrusNajmabadi** [comment]
I thought these checksums were computed because the PDB writing needs it, and has to know the original bytes we're creating the source-text out of.  Is it possible to defer that to later (i could have sworn we wanted that originally, but front loaded it for some reasons that are lost to my brain now).

**Comment by tmat** [comment]
You're right, when we're opening a file to read a document we need to calculate the checksum using the algorithm specified by the project. In that case we wouldn't be able to use a different alg and maybe that's the majority of SHA256 usage. 

In any other case we can use a faster algorithm.

**Comment by CyrusNajmabadi** [comment]
Yeah.  THat's my recollection as well.  And it's effectively what we do for all the closed files (the 99% case).  I think we *maybe* do something slightly different for open files.  But i would expect those to be vastly outnumbered by closed files.  So savings woudl be minimal.

*An* alternative i could conceive of is us generally going to a model where we consider *not* trying to sync closed files, and instead just saying: hey server, these are the files *you* should be reading.  

THis would avoid the client side cost of reading/hashing.  But opens the opportunity for client and server to not agree on contents.

**Comment by tmat** [comment]
What about other artifacts (not documents) that we sync? Wouldn't we be able to use the faster hashing alg there?

**Comment by CyrusNajmabadi** [comment]
Would have to see what sort of cost they have.  Rigth now though, the complaint seems to be about [SourceText.CalculateChecksum](https://github.com/dotnet/roslyn/blob/50aa37f11d39a55f70254eca281749dc40cb52ee/src/Compilers/Core/Portable/Text/SourceText.cs#L576-L596) (which is jus the sourcetxt side of things).  If someone sees a hit on Checksum.Create though, we could certainly move that to *any* sort of hash approach we think does a good job, and has "extremely unlikely collision" properties.  

if xxHash is good at making collisions practically impossible (like sha256 gives us) we could otally move that :)

**Comment by davkean** [comment]
Not as much, but it shows up consuming about 1/10th of a core (throw `c=Checksum.Create` at Prism's CPU page).

**Comment by CyrusNajmabadi** [comment]
Closing out, we do use xxhash128 here.
