### ISSUE TITLE
Bad performance from CoreWF - no fast way to create a LambdaExpression from VB script code

### ISSUE THREAD

**Issue by angelowang** [dotnet/roslyn#68712]
**Version Used**: 
4.0.1

**Steps to Reproduce**:
This is related to this CoreWF (the non-official port of Windows Workflow Foundation) issue: https://github.com/UiPath/CoreWF/issues/208
1. Due to the lack of VbHostedCompiler in .NET Framework, CoreWF has to use roslyn JIT compiler to emit DLL assembly from the script code, and then load the assembly to create a LambdaExpression. This is very slow.
2. As we port our product to .NET 6, it sees significant performance degradation on the first run of the workflow. We are using CodeActivity a lot, so this VBScript to LambdaExpression is critical to us.
3. According to https://github.com/dotnet/roslyn/issues/13523, seems road map is not going that direction :(

**Comment by CyrusNajmabadi** [comment]
Where is the time being spent in the code?  Do you have any traces?  Can yuo show how you're using roslyn here?

**Comment by angelowang** [comment]
@CyrusNajmabadi I don't have trace now. This ticket has some similar callstack: https://github.com/UiPath/CoreWF/pull/178

CoreWF is a open source WF porting (suppoted by .NET foundation). The code to compile VBScript to LambdaExpression is here:
VisualBasicValue is a CodeActivity, which will need to do the compiling from VBScript to LambdaExpression.
https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Microsoft/VisualBasic/Activities/VisualBasicValue.cs#L95
How it is compiled:
https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Microsoft/VisualBasic/Activities/VisualBasicDesignerHelper.cs#L77
https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Activities/ScriptingJitCompiler.cs#L77: accessing the ScriptClass method will do all the compiling
https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Activities/ScriptingAotCompiler.cs#L53: Finally an in-memory DLL is Emit'ed and loaded to create the LambdaExpression.

For one of our xaml file, the first time running the workflow degrades from 0.5s to 20s.
The problem with us is CodeActivity is used a lot, so there will be a lot of VisualBasicValue's which means a lot of expressions will be compiled. And every compiling is independent, and I've already tried to minimize the file access by caching MetadataReference in this https://github.com/UiPath/CoreWF/pull/260, but still is 4s for the same file.

The .NET Framework has been using VbHostedCompiler, which is super fast.
Framework: https://github.com/microsoft/referencesource/blob/master/System.Activities/Microsoft/VisualBasic/Activities/VisualBasicHelper.cs#LL136C76-L136C76
NET6/CoreWF: https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Activities/JitCompilerHelper.cs#L1374, and https://github.com/UiPath/CoreWF/blob/develop/src/UiPath.Workflow/Microsoft/VisualBasic/Activities/VisualBasicSettings.cs#L49

**Comment by CyrusNajmabadi** [comment]
I'm not really sure what in that code is using Roslyn.  Can you collect a trace, see where the cost is, and we can perhaps figure out what team this should go to.

**Comment by angelowang** [comment]
I will first close this one. It is actually a feature request like converting SyntaxTree to a LambdaExpression, instead of needing to compile to a dll first.
And there is some potential to improve it in CoreWF side too.
