### ISSUE TITLE
foreach Convert to LINQ produces incorrect code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68729]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/foreach-Convert-to-LINQ-produces-incorre/10056238)._

---
[severity:Other]
Howdy

When you have a `foreach` that contains an `if (a is Foo b) { b.DoSomething...}`

The convert to linq refactor doesn't recognise there is a scoped cast assignment and produces nonsense code.

>'CS0103: The name 'b' does not exist in the current context'

Maybe it would be worth recognising this pattern and excluding this refactor if it is incorrect / doesn't make sense?

I'm slowly getting better, but this would have confused me no end back in the day.

All the very best

Rob

Here's  my guilty code

```csharp
// Original
private IEnumerable<MinMaxPrefComparer> GetDiscriminators(IEnumerable<IComparer> critics)
{
    foreach (var critic in critics)
    {
        if (critic is MinMaxPrefComparer comparer)
        {
            if (comparer.minDiscriminator || comparer.maxDiscriminator)
            {
                yield return comparer;
            }
        }
    }
}
```

```csharp
// Linq refactor
private IEnumerable<MinMaxPrefComparer> GetDiscriminators(IEnumerable<IComparer> critics)
{
    return from critic in critics
            where critic is MinMaxPrefComparer comparer
            where comparer.minDiscriminator || comparer.maxDiscriminator
            select comparer;
}
```

```csharp
// Linq (Call form) refactor
private IEnumerable<MinMaxPrefComparer> GetDiscriminators(IEnumerable<IComparer> critics)
{
    return critics.Where(critic => critic is MinMaxPrefComparer comparer)
        .Where(critic => comparer.minDiscriminator || comparer.maxDiscriminator)
        .Select(critic => comparer);
}

```

---
#### Feedback Bot on 5/30/2022, 01:02 AM: 

(private comment, text removed)
#### Feedback Bot on 8/31/2022, 08:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
