### ISSUE TITLE
Limit code analysis suggestions to changed code only

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Limit-code-analysis-suggestions-to-chang/1651866)._

---
When .editorconfig is configured to analyse code and highight rule violations and suggestions, can it be configured to only highlight issues with code that has changed.  The IDE already has a "Changes" panel which knows which files are different to the latest version in source control, and it knows which lines are different, and it knows which lines of code have violations - so, it should be possible to apply AND logic to the warnings and changes to only highlight violations in the code on those lines of code.

Could this be built in as a feature of Visual Studio?

More context: In an application that is 20 years old but still very much alive and kicking, serving hundreds of thousands of customers, a lot of the existing code is not standards compliant. To change 100 lines in a class file to correct the violations when the only change needed is a one-liner, that introduces regression risk and increased testing time that we often do not have time for, but we want to make sure the changed code is compliant.  We also want to be able to put git hooks in place that would fail a commit if the CHANGED CODE has any violations.

---
#### Feedback Bot on 2/2/2022, 07:56 PM: 

(private comment, text removed)
#### Feedback Bot on 3/23/2023, 11:05 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
