### ISSUE TITLE
NuGet build task should complain if project.lock.json exists, but not XXX.nuget.props and XXX.nuget.targets

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6873]
If you check-in a project's project.lock.json but not the appropriate XXX.nuget.props/XXX.nuget.targets the NuGet build task does not complain that they are missing when you pull down the project on a build machine.

This leads to hard to diagnose build errors, such as this: https://gist.github.com/davkean/d19c5b909aa265357bf1. Here, I'm expecting a particular target to generate some code, which other parts of my project use. While this project happens to complain loudly when the targets files are missing, others may not and could silently build incorrectly.

Instead, the NuGet build task should verify that the appropriate props/targets exists if the project is expected to be in a restored state.

**Comment by jasonmalinowski** [comment]
@emgarten, @yishaigalatzer: do you write the targets/props always, or only if some package has build metadata?

**Comment by emgarten** [comment]
The nuget targets/props files are only added if they have entries. NuGet will try to delete the targets/props files if they exist if there are no entries.

Assets from the build folder are not written to the lock file, only to the targets/props files, which means there is no way to determine that there is a problem here without re-reading all of the packages. Deleting the targets/props files is essentially the same as deleting part of the lock file. 

In my opinion restore should always be run before a build to perform the validation and restore these files. In order for MSBuild to be able to perform the validation asked for here NuGet would need to add build information to the lock file to enable that.

**Comment by jasonmalinowski** [comment]
Closing in favor of NuGet/Home#2803 since we should track NuGet issues there.
