### ISSUE TITLE
The `language` property of the SARIF file should be output correctly

### ISSUE THREAD

**Issue by aetos382** [dotnet/roslyn#68745]
**Version Used**: .NET 8.0.100-preview.5

**Steps to Reproduce**:

1. Fork [this repository](https://github.com/aetos382/roslyn-sarif-language-bug).
2. Run actions.

**Diagnostic Id**: N/A

**Expected Behavior**: All steps of the workflow are successful.

**Actual Behavior**: The `github/codeql-action/upload-sarif` action fails.

> Unable to upload "csharp-compiler.sarif" as it is not valid SARIF:
> - instance.runs[0].tool.driver.language does not match pattern "^[a-zA-Z]{2}(-[a-zA-Z]{2})?$"

**Causes**: 
The `tool.driver.language` property of the sarif file output by the C# compiler is an empty string (`""`).
Should be either output "en-US" or omit the property (if the locale of the execution environment is English).
See the sarif file attached to the workflow artifact.

**Workaround**: Specifies the `PreferredUILang` property

**Comment by mavasani** [comment]
@aetos382 This seems like an issue with the code-ql github action. I can see that when the C# compiler is invoked with /errorlog switch from the command line it correctly emits the culture name in the `language` property: _"language": "en-US"_

https://github.com/dotnet/roslyn/blob/5d944eaed2d86ba7ec1f0822d9bc62e16ad8fca2/src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs#L204C52-L204C52

**Comment by mavasani** [comment]
> Should be either output "en-US" or omit the property (if the locale of the execution environment is English).

I think omitting the property when the culture name is empty is a reasonable proposal. I'll create a PR with the fix.
