### ISSUE TITLE
C# Dev Kit complains about incomplete ref struct syntax

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#68742]
Happens every time I type `public ref struct`. I'm using the latest VS Code and latest preview C# Dev Kit.

<img width="1405" alt="image" src="https://github.com/dotnet/roslyn/assets/2608468/0cdd2cab-0000-499c-a81c-48f07313ddda">

**Comment by beccamc** [comment]
Thanks for reporting. This is fixed in the latest version 2.0.283. Please check it out and let us know if you see anything else!
