### ISSUE TITLE
Regression: SyntaxFactory.UsingDirective overload always throws

### ISSUE THREAD

**Issue by GrahamTheCoder** [dotnet/roslyn#68761]
**Version Used**: 
Version 17.7.0 Preview 2.0

**Steps to Reproduce**:

1. Call `Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken staticKeyword, NameEqualsSyntax alias, NameSyntax name)` with any valid parameters
2. `throws ArgumentException("usingKeyword")`

**Expected Behavior**:
As previously: Construct and pass a valid Token(usingKeyword)

**Actual Behavior**:
Constructs and passes a `default(SyntaxToken)` which causes the called code to always throw

**Other details**

The bug is here:
https://github.com/dotnet/roslyn/blob/d0f4099ffa7f8ff31fd397a4a96f404e1cd7dfc7/src/Compilers/CSharp/Portable/Syntax/UsingDirectiveSyntax.cs#L38
It passes through default, to an overload that in the generated syntax factory that throws unless the syntax kind of that parameter is `SyntaxKind.UsingKeyword`

The code was added in: https://github.com/dotnet/roslyn/commit/c8d3925ffb827fa70a762becfd951f80e54548f8#diff-95477edd7a2f9bf55ac156fbeb22d71f973b06dc20a7034b373e8c2e8341d6f0

Bug originally reported here: https://github.com/icsharpcode/CodeConverter/issues/1019
Unit test would probably go in `Microsoft.CodeAnalysis.CSharp.UnitTests.SyntaxFactoryTests` and look something like:

```csharp
        [Fact]
        public void UsingDirective()
        {
            var someValidName = SyntaxFactory.ParseName("System.String");
            var usingDirective = SyntaxFactory.UsingDirective(SyntaxFactory.Token(SyntaxKind.StaticKeyword), default(NameEqualsSyntax), someValidName);
            Assert.Equal("using static System.String;", usingDirective.ToString());
        }
```

[jcouv update:] Relates to test plan https://github.com/dotnet/roslyn/issues/56323

**Comment by CyrusNajmabadi** [comment]
@GrahamTheCoder def feel free to submit a fix too.  It will help expedite things!
