### ISSUE TITLE
Support pattern-matching in let clauses in Linq

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#6877]
Given the _let-statement_ proposed in the draft [pattern-matching specification](https://github.com/dotnet/roslyn/blob/future/docs/features/patterns.md) for #206, it has been [proposed by @alrz](https://github.com/dotnet/roslyn/issues/206#issuecomment-158023756) to extend the `let` clause in Linq to support pattern-matching as well:

> because of the similarities with `let` statement I think that would be reasonable to support patterns in it.
> 
> ``` cs
> from person in list
> let Student { Grade is var grade, Name is var name } = person
> where grade > 65
> select new { Grade = grade, Name = name };
> ...
> // equivalent to
> ...
> from person in list
> let $x = person switch(
>   case Student { Grade is var grade, Name is var name }: new {grade, name},
>   case *: null
> )
> where $x?.grade > 65        
> select new { Grade = $x.grade, Name = $x.name }   
> ...
> // complete patterns
> ...
> from tuple in list
> let (var x, var y) = tuple
> where x > y
> select x + y
> ...
> // equivalent to
> ...
> from tuple in list
> let $x = tuple case (var x, var y) : new {x,y}
> where $x.x > $x.y
> select $x.x + $x.y
> ```
> 
> etc.

It isn't clear how this would be expected to work when the pattern is fallible.

**Comment by mattwar** [comment]
You could make it also where as a where clause and omit anything that doesn't match.

**Comment by HaloFour** [comment]
@gafter 

I agree, letting `let` do double-duty here seems intuitive.  But I also agree that failed patterns pose a potential problem.  Having the failed patterns omitted automatically seems a little too implicit.  Maybe support something like `else continue`?

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person else continue
where grade > 65
select new { Grade = grade, Name = name };
```

**Comment by gafter** [comment]
@mattwar I agree, but which Linq method would it translate into? `.Where` doesn't have a mechanism for adding new variables, and `.Let` doesn't have a mechanism for filtering.

**Comment by alrz** [comment]
@HaloFour that's exactly the issue I was thinking about, it implicitly skips failed patterns. but `else continue` seems fair.

**Comment by HaloFour** [comment]
With `let` already providing a bit of syntactic voodoo in LINQ I think that it's reasonable that it would be translated out into multiple extension method calls.

Going with implicit filtering:

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person
where grade > 65
select new { Grade = grade, Name = name };
```

converted into:

```cs
list
    // beginning of let expansion
    .Select(person =>
    person switch (
        case Student { Grade is var grade, Name is var Name } : (true, person, grade, name)
        case * : (false, person, null, 0)
    ))
    .Where(tuple => tuple.Item1)
    .Select(tuple => new { person = tuple.Item2, grade = tuple.Item3, name = tuple.Item4 })
    // end of let expansion
    .Select(projected => new { Grade = projected.grade, Name = projected.name });
```

**Comment by alrz** [comment]
I'd say it could be `Let`:
```cs
list
.Let(person => person switch( ... ))
.Where($x => $x.grade > 65)
.Select($x=> new { Grade = $x.grade, Name = $x.name });

public static IEnumerable<TResult> Let<T, TResult>(
  this IEnumerable<T> source,
  Func<T, TResult> selector)
{
  foreach(var item in source) {
    var result = select(item);
    if(result != null)
      yield return result;
  }
}
```

**Comment by gafter** [comment]
This can be done in one step using [`SelectMany`.](https://msdn.microsoft.com/en-us/library/bb534336(v=vs.100).aspx).

**Comment by gafter** [comment]
@alrz What does `result != null` mean when you don't know if it is a reference type or not?

**Comment by alrz** [comment]
@gafter It will be an anonymous type anyway, I forgot to write the `class` constraint.

**Comment by gafter** [comment]
@alrz No, it is not required to be an anonymous type. We were hoping to start using tuples in many cases for translating `let` to reduce GC pressure.

**Comment by HaloFour** [comment]
@gafter Great point.  The compiler could spit out a private static function that accepts the original range variable (or a tuple of all current range variables) and returns an `IEnumerable<tuple>` of the original range variable(s) plus the variable patterns, then `yield return` a single result on a match.

Going with implicit filtering:

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person
where grade > 65
select new { Grade = grade, Name = name };
```

converted (somewhat) into:

```cs
IEnumerable<(Person, int, string)> $match(Person person) {
    switch (person) {
        case Student { Grade is var grade, Name is var Name }:
            yield return (person, grade, name);
        default: yield break;
    };
};

list
    .SelectMany($match)
    .Where(projected => projected.Item2 > 65)
    .Select(projected => new { Grade = projected.Item2, Name = projected.Item3 });
```

**Comment by alrz** [comment]
@gafter I was assuming the current implementation, I did mention [this] in the tuple issue, too.

I have no idea how this could use `SelectMany` anyway.

**Comment by gafter** [comment]
@HaloFour The Linq pattern is not tied to `IEnumerable`... it would be a shame if this pattern-matching support worked for `IEnumerable` but no other types.

**Comment by HaloFour** [comment]
@gafter Apologies for botching the example.  I didn't imply that it would be tied to `IEnumerable`, aside the fact that `let` would use it to return either 0 or 1 results per attempted match, which I thought was what you were going for.

**Comment by HaloFour** [comment]
@gafter Wait, my example was correct.  I'm not sure where the confusion is?

**Comment by bbarry** [comment]
```
from person in list
let Student { Grade is var grade, Name is var name } = person
where grade > 65
select new { Grade = grade, Name = name };
```

into 

```
list
    .SelectMany(person => person switch (
        case Student { Grade is var grade, Name is var name } : new [] { (person, grade, name) }
        case * : Enumerable.Empty<...>()
    ))
    .Where(projected => projected.Item2 > 65)
    .Select(projected => new { Grade = projected.Item2, Name = projected.Item3 });
```

?

Is it possible to avoid the allocation for that array?

**Comment by HaloFour** [comment]
@bbarry

The compiler wouldn't be forced to impose the restriction of closures not being iterators on itself.  I assume that the compiler would emit a private static iterator function and then pass a delegate to that function to `SelectMany`.

**Comment by orthoxerox** [comment]
What about this approach?

```c#
var students =
from person in people
where person is Student student
select student;
//is transformed into
var students = people
.Select(person => (person is Student student)?(true, student):(false, default(Student)))
.Where(tuple => tuple.Item1 = true)
.Select(tuple => tuple.Item2);
```

**Comment by HaloFour** [comment]
@orthoxerox Looks pretty similar to my first suggestion for an expansion, although you're using `is` with a ternary rather than the `switch` expression.

**Comment by gafter** [comment]
Why are all you folks tying this to Enumerable (e.g. using `Enumerable.Empty` or having the compiler generate a method that performs `yield return`)? The Linq feature can be used with any type that fits the API pattern (e.g. PLINQ, Linq to SQL, IObservable, etc). If we have this construct force the result to be Enumerable<something>, then we've broken one of the important features of Linq.

**Comment by gafter** [comment]
@HaloFour Your first proposed expansion (also @orthoxerox 's most recent proposed expansion) would work.

**Comment by bbarry** [comment]
@gafter I thought you said SelectMany above; I was trying to figure out how that would have worked. I think @HaloFour's tuple expansion https://github.com/dotnet/roslyn/issues/6877#issuecomment-158172883 is better. It seems odd to have `let` reduce the number of items in the statement...

**Comment by gafter** [comment]
@bbarry I thought `SelectMany` could be used, but I tried and now I don't think so.

**Comment by HaloFour** [comment]
@gafter Indeed, implementing this via `SelectMany` would lock it to `IEnumerable<T>` under the hood as the mechanism to return zero or one value.  It was your idea, we were following it.  If this tie to `IEnumerable<T>` is unacceptable then that's fine, but you forgot to mention that before chastising us for chasing your concept.

Anyway, that is all implementation details.  I'd be more concerned with hammering down the semantics and syntax (and variations thereof) at this stage and worrying about how exactly that could be expanded later.  Particularly of interest would be any capability of this feature functioning as a filter as well as a projection, either by default or through additional syntax.

Aside that, it is nice to hear that LINQ may take advantage of tuples for `let` projections.

**Comment by alrz** [comment]
@HaloFour `SelectMany` is not tied to `IEnumerable<T>`, implement it for your desired type and it will work 
```cs
static M<U> SelectMany<T, U>(this M<T> id, Func<T, M<U>> k)
```

**Comment by gafter** [comment]
@alrz How would you use `SelectMany` to implement a pattern-based `let` clause, i.e. so that it can return one result or none, without tying it to `IEnumerable`?

**Comment by alrz** [comment]
@gafter you mean tying it with something else like maybe?

**Comment by gafter** [comment]
@alrz I don't have a particular solution in mind.

**Comment by alrz** [comment]
@gafter Indeed, it *can* be implemented with `SelectMany` :smile: Here's a particular solution,
```cs
public static M<U> SelectMany<T, U>(this M<T> source, Func<T, U?> k)
	where U : struct
{
    return from item in source
           let result = k(item)
           where result.HasValue
           select result.Value;
}

public static M<V> SelectMany<T, U, V>(this M<T> m, Func<T, U?> k, Func<T, U, V> s)
	where U : struct
	where V : struct
{
    return m.SelectMany(x => k(x).SelectMany(y => new V?(s(x, y))));
}

public static U? SelectMany<T, U>(this T? m, Func<T, U?> k)
	where T : struct
	where U : struct
{
    return m.HasValue ? k(m.Value) : default(U?);
}
```
I simulated `Maybe a` with `Nullable<T>` for demonstration, so it can only used with value types (see below), substitute it with `Option<T>` and it works for all types.

I'm using higher-kinded generic type `M<T>` you can substitute it with any type that has implemented `SelectMany` like `IEnumerable<T>` and it works for that particular type.

As an example,
```cs
// assuming
var list = new object[] { 1, 2.0, 3 };

// the following
var q = from item in list
		let double d = item
		select d;

// translates into
var q = from item in list
	    from d in item is double num ? new double?(num) : default(double?)
	    select d;

```
The return value of pattern matching can be an `Option<T>` where `T` is a tuple or anonymous type, to be used in the consequent LINQ operators.

The the thing is, in async sequences, we have three container types to combine: `Task<T>`, `IEnumerable<T>` and `Option<T>` which complicates things exponentially! In that case, I think higher-kinded generics would be really helpful.

**Comment by gafter** [comment]
@alrz None of your `SelectMany` methods are part of the existing Linq pattern described by the C# language specification. I meant using the same `SelectMany` methods that must already be implemented for the current Linq pattern - for example, the ones in [`Enumerable`](https://msdn.microsoft.com/en-us/library/system.linq.enumerable_methods(v=vs.100).aspx).

**Comment by alrz** [comment]
@gafter Well, it cannot be done I guess! They are not new implementations, I just implemented *bind* for `Nullable<T>` (third method) and a transformer for it (first method) and a helper function to be used in query expressions (second method). These are part of functional languages like Haskell, so you don't need to implement them yourself. The fact that `Nullable<T>` is not introduced as a *monad* in the language, restrict us in this kind of situations. Anywho, I'm really interested to see how this can be done with the existing `SelectMany` without tying it to a particular type.

**Comment by gafter** [comment]
@alrz I'm guessing it cannot be done.

**Comment by HaloFour** [comment]
@alrz All you're really doing is implementing the same `Select`/`Where`/`Select` implementation from above.  The C# compiler can already emit tuples (or anonymous types) to project an analog to `Option<T>` so this would require no new BCL types or methods.

Also, to note, that second `Select` wouldn't be necessary as the compiler can simply choose to ignore the fact that the success flag is still projected.  If the LINQ query performs another `let` match or `select` projection it could omit it at that point.

**Comment by alrz** [comment]
@HaloFour This is the functional way of doing things (as if they were existed in the language for `Option<T>` etc) so they wouldn't be special just for implementing `let` in query expressions. If `Select`/`Where` is the prefered way, I do agree that it's more optimized and straightforward solution for this. In that case I think expanding `where ... is ...` would be more sensible than translating `let` to a `where` clause.

**Comment by HaloFour** [comment]
@alrz

My samples assume an implicit filtering of failed patterns, something that I don't know has been decided upon.  If failed patterns wouldn't be filtered out then there would be no call to `Where`.

Well `where ... is ...` already means something today and doesn't convey the capture of those range variables.  If you're arguing that declaration expressions or pattern variables should be lifted to range variables that might be a different proposal.

**Comment by alrz** [comment]
>Well `where ... is ...` already means something today and doesn't convey *the capture of those range variables*.

Yes it does, as for `is` itself. But there weren't any "variables" for `is` before. Don't forget we have two kind of `is` operator,
>*relational-expression:*
&emsp;*relational-expression* `is` *type*
&emsp;*relational-expression* `is` *complex-pattern*


So, I'm saying that `let` can be used for complete patterns like
```cs
from item in list
let (var x, var y) = item
...
```
And the second form of `is` for fallible patterns.
```cs
from item in list
where item is Foo foo
...
```
And for the existing form of `is` it would behave as it always has.

**Comment by HaloFour** [comment]
@alrz 

Pattern variables don't leak out of scope with `is`, though.  Nor would they with `where`.  That `where` clause could similarly combine other Boolean operations, including with declaration expressions, where it was determined that the scope would not exceed the `where` clause.

**Comment by alrz** [comment]
@HaloFour Now that you mentioned declaration expressions it's understandable for me that changing scoping just for pattern variables doesn't make sense. Since `let` clause variable scope is well defined I think that's the only option and for implicit skipping issue, as I said, `else continue` seems fair, as you suggested, but I'm not sure about using `continue` because it's already an statement and might be confusing.

**Comment by gafter** [comment]
Remember that the semantics of query expressions are defined mostly in terms of translation to invocation of methods with expression lambdas. Pattern variables will not leak out of expression lambdas. If we want to change the scoping we need to define a different translation.

**Comment by alrz** [comment]
@gafter 

> semantics of query expressions are defined mostly in terms of translation to invocation of methods with expression lambdas.

I presume *mostly* means "except for `let`". I did take my suggestion back regarding expanding `where`. But still, I think it's not that illogical to have this behavior with `let` clause — btw, I'm sure with introducing `let` statement for deconstruction, this one is expected as well. At least, it could support complete patterns for using with tuples, etc.

**Comment by gafter** [comment]
It isn't `let` in particular that is the exception. There are a few things that make it not quite a syntactic transformation:

1. The query methods are "expected to have particular signatures and result types, as described in §7.16.3"
2. "Assignment to range variables is not allowed in query expressions. However a C# implementation is permitted to not always enforce this restriction, since this may sometimes not be possible with the syntactic translation scheme presented here."
3. Some translation steps (like `let` and a non-initial `select`) involve the use of "transparent identifiers" which are described to be translated into the use of anonymous types. However, "An implementation of C# is permitted to use a different mechanism than anonymous types to group together multiple range variables."

**Comment by paulomorgado** [comment]
I got a bit confused around this.

Part of this discussion is about deconstruction in LINQ queries giving a new meaning to the **let** keyword and match it with the "new" **let** keyword outside of LINQ queries, right?

How would this behave outside of LINQ?

    let Student { Grade is var grade, Name is var name } = person;

Should it behave differently in LINQ queries? I think not.

The other of this discussion is about a condition introducing new "variables", right?

In order for the compiler to handle this without the need for introducing new signatures in `Where`, how about this?

   where person is Student { Grade is var grade, Name is var name }

would be logically translated to:

    let isMatch = person is Student { Grade is var grade, Name is var name }
    where isMatch

or concretely to:

    .Select(person => person is Student { Grade is var grade, Name is var name }
        ? (true, person, grade, name)
        : (false, person, default(Grade), default(Name)))
    .Where(tuple => tuple.Item1)
    .Select(tuple => (tuple.Item2, tuple.Item3, tuple.Item3))

The last `Select` is just to drop the condition value, but it could be kept until the very end and be reused in other similar patterns.

**Comment by HaloFour** [comment]
@paulomorgado The problem remains the scoping.  If the pattern introduces new variables through variable patterns then in normal circumstances those variables would be out of scope as soon as the clause terminated.  That would remain true using `is` within a `let` clause unless that behavior was defined.  If that behavior would be reconsidered then this issue does go away:

```cs
from person in list
where person is Student { Name is var name, Grade is var grade } && grade > 65
select new { name, grade };
```

This is basically a continuation of the conversation at [CodePlex](http://roslyn.codeplex.com/discussions/561432) except with patterns instead of variable declarations.

**Comment by gafter** [comment]
@paulomorgado The expression `person is Student { Grade is var grade, Name is var name }` is already an ordinary boolean expression that could be used in a lambda (or will be with the addition of pattern-matching), so I think we would be reluctant to give it a special meaning in a query's `where` clause.

**Comment by paulomorgado** [comment]
@HaloFour, doesn't the way I showed introduce those variables?

@gafter, the difference is the variables introduced. And I was not proposing to give a new meaning to the `where` clause. Was I?

**Comment by HaloFour** [comment]
@paulomorgado No, not without other changes to the semantics of the `let` clause.  The only additional range variable it would introduce is `isMatch`.  The others would end up going out of scope.

**Comment by gafter** [comment]
@paulomorgado Yes, you were proposing a change from the current specification for the translation of the `let` clause.

**Comment by paulomorgado** [comment]
OK. It's a "change", not a "CHANGE".

@gafter, on hindsight, that last `Select` is kind of stupid. But, apart from that and the needed introduction of the need two variables (`grade`, `name`), what's the difference from translating this:

    from i in Enumerable.Range(0, 10)
    let c = i % 2 == 0
    where c
    select I

into this (now using the tuple proposed syntax)?

    Enumerable.Range(0, 10)
        .Select(i => (i, i % 2 == 0))
        .Where(((i, c)) => c)
        .Select(((i, c)) => i)

**Comment by gafter** [comment]
@paulomorgado the translation above is using precisely the set of methods specified in the language specification, and introduces precisely the set of range variables specified in the language specification, so it appears to comply with the spec.

**Comment by paulomorgado** [comment]
@gafter, I was trying to be "tuply".

**Comment by alrz** [comment]
@paulomorgado  It probably would be
```cs
Enumerable.Range(0, 10)
    .Select(i => (i, i % 2 == 0))
    .Where(t => t case (var i, var c): c)
    .Select(t => t case (var i, var c): i)
```
Since #6067 is not under consideration.

**Comment by gafter** [comment]
@alrz Why would the compiler translate into an application of pattern-matching when it could just generate a member access?

**Comment by gafter** [comment]
@paulomorgado You mean "Twoply"? ;)

**Comment by alrz** [comment]
@gafter Compiler sure would do the second one.

**Comment by gafter** [comment]
@alrz The compiler surely would not give itself busy-work by producing new forms of syntactic sugar that it would then have to undo.

**Comment by alrz** [comment]
@gafter Isn't this the same behavior that currently has been done by anonymous types that are going to implemented using tuples?

**Comment by HaloFour** [comment]
@gafter

> You mean "Twoply"? ;)

There's probably a potty joke there somewhere.

**Comment by gafter** [comment]
@alrz When we use anonymous types, we actually create them as specified. Of course the actual anonymous types have names from the CLR's point of view, but there isn't much lowering going on after that.

**Comment by alrz** [comment]
@gafter In the code above I meant the `t` name is compiler generated
```cs
Enumerable.Range(0, 10)
    .Select(i => (i, c: i % 2 == 0))
    .Where($t => $t.c)
    .Select($t => $t.i)

Enumerable.Range(0, 10)
    .Select(i => (i, c: i % 2 == 0))
    .Where($t => $t.c)
    .Select($t => $t.i)
```
I don't know what I'm missing here.

**Comment by gafter** [comment]
I mean why would we generate names such as `c` and `i` that we would then have to bind and translate into `Item2` and `Item1`? We're done binding; there is no reason to translate into names that do not exist after binding.

**Comment by alrz** [comment]
@gafter I see, I know that these names will be ultimately erased, actually I meant "equivalent to" not "translated into" anywho, what if we are doing this over `Expression<Func<,>>` shouldn't the user names be accessible for `IQueryable<>` translations? same issue with using tuples in `select`
```cs
from item in db.Products
select (item.Name, item.Model)
```
so you say libraries like EF won't get access to these names to do projection etc?

**Comment by gafter** [comment]
An `Expression<Func<...>>` would see the expanded form, just like today. I expect we'd continue to use anonymous types for those so as not to break existing code. Lots of code is quite sensitive to the exact expression tree produced.

**Comment by alrz** [comment]
@gafter Assume that user just wrote the above (to get a list of tuples), it will be "not supported" or compiler would generate an anonymous type (to be used for `Expression<Func<...>>`) and then yields a tuple?

**Comment by gafter** [comment]
@alrz It will be exactly the same as if the user had written

```cs
from item in db.Products
select new ValueTuple<string, int>(item.Name, item.Model)
```

**Comment by alrz** [comment]
So I presume that tuples can't be used with EF queries at all.

**Comment by bbarry** [comment]
This tuple discussion risks getting lost by virtue of not being related to the issue. This probably isn't the correct place to have it. What @gafter was saying though was that the current anonymous types that get generated for range variables internally to the *linq-expression* (ones that never get exposed to the user) could be potentially replaced by tuples when that *linq-expression* is generating code that runs over the `IEnumerable<>` type. Perhaps some future types could hint to the compiler what kind of intermediate types should be generated (so the compiler doesn't expressly apply this change only for that specific instance). 

the linq expression:

```
from i in Enumerable.Range(0, 10)
let c = i % 2 == 0
where c
select i
```

currently uses an anonymous tuple that gets created in the *let-clause*, but doesn't appear in the result. 

If the query was instead:

```
from i in Enumerable.Range(0, 10)
let c = i % 2 == 0
select (c, i)
```

the type of the result item in that linq expression would be a tuple. There is still some anonymous background thing generated in the *let-clause*, but it has no affect on the result type of the expression.

**Comment by alrz** [comment]
@bbarry as @gafter said
> I expect we'd continue to generate anonymous types for transparent identifiers in expression trees so as not to break existing code.

So

>```cs
from i in Enumerable.Range(0, 10)
let c = i % 2 == 0
select (c, i)
```

can be translated into
```cs
Enumerable.Range(0, 10)
    .Select(i => (i, i % 2 == 0))
    .Select(t => (t.Item2, i.Item1))
```
with no breaking changed.

**Comment by HaloFour** [comment]
@alrz @bbarry 

Whereas:

```cs
from i in Enumerable.Range(0, 10).AsQueryable()
let c = i % 2 == 0
select (c, i);
```

would likely be translated as:

```cs
Enumerable.Range(0, 10)
    .AsQueryable()
    .Select(i => new { i = i, c = i % 2 == 0 })
    .Select(t => (t.c, t.i));
```

**Comment by bbarry** [comment]
@alrz, I think so. That looks like a potential optimization the compiler could do for a linq expression that uses the extension methods on `Enumerable`. What heuristics would actually get used to determine if that optimization was good, I have no idea. 

@HaloFour that is what I would expect.

**Comment by alrz** [comment]
Nevertheless, I think for
```cs
from item in db.Products
select (item.Name, item.Model)
```
it would be reasonable that it be translated as
```cs
db.Products
.Select(item => new {item.Name,item.Model})
.Select(t=>(t.Name,t.Model))
```
Otherwise, if you accidentally use a tuple for projecting `IQueryable<T>` you are just accidentally  screwed.

**Comment by HaloFour** [comment]
@alrz 

You'd be opting-into tuples explicitly in that case which is very different from whatever `let` automagickally does under the hood.  Note that your translation would suffer the same amount of screwed-ness given both `Select`s would be in the expression tree and would have to be translated by Entity Framework or whatever queryable provider.

**Comment by alrz** [comment]
@HaloFour I'm thinking that EF should be loud about this and write a big bold statement somewhere that states DON'T USE TUPLES.

**Comment by bbarry** [comment]
There is nothing stating that linq expression tree visitor code couldn't be modified to support tuples, that is an enhancement on those things. 

I think it would be useful for the expression tree representing that tuple to know the compile time names used, but I don't see why a person who "accidentally" projects an `IQueryable<T>` into a tuple shouldn't be permitted to get exactly the thing they expressed in code.

**Comment by HaloFour** [comment]
@alrz I bet they add support for projecting to tuples long before any of this ships.

**Comment by alrz** [comment]
@bbarry I would totally love that. expression trees are generated in compile-time, so are tuple names. nothing stops you from not being able to get those sweet names from an expression tree (#2060).

**Comment by paulomorgado** [comment]
@gafter,

Not "oneply", "twoply" or "threeply" in particular. Just "tuply" in general. :smile: 

/cc @HaloFour

**Comment by alrz** [comment]
If we unify nullables, which help of higher kinded types I think we can implement generic LINQ operations for nullables and utilize it for `let`. 

Besides, although we have nullable references, `T?` meaning two things, depending on the type is awful.

**Comment by HaloFour** [comment]
I'm going to posit that by default a failed pattern should result in a run-time exception.  As with pattern matching in any other context the compiler should go to whatever lengths it can to prevent that.  Where the pattern may be fallible I think that reusing the `else` keyword with an embedded statement is useful and should follow very similar rules to that of using `let` for destructuring outside of LINQ.  The one difference is that the embedded-statement cannot contain a `return` statement since that wouldn't make a lot of sense in the LINQ query.  But since the LINQ query can be considered a looping construct I think that `continue` and `break` should both be acceptable.

In the case of `continue` the LINQ query will omit the elements that do not match the pattern:

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person else continue
where grade > 65
select new { Grade = grade, Name = name };

// translated into

list
    // beginning of let expansion
    .Select(person => person switch (
        case Student { Grade is var grade, Name is var Name } :
            (true, person, grade, name)
        case * :
            (false, person, default(int), default(string))
    ))
    .Where(tuple => tuple.Item1)
    .Select(tuple => new { person = tuple.Item2, grade = tuple.Item3, name = tuple.Item4 })
    // end of let expansion
    .Where(projected => projected.grade > 65)
    .Select(projected => new { Grade = projected.grade, Name = projected.name });
```

In the case of `break` the LINQ query will terminate the sequence:

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person else break
where grade > 65
select new { Grade = grade, Name = name };

// translated into

list
    // beginning of let expansion
    .Select(person => person switch (
        case Student { Grade is var grade, Name is var Name } :
            (true, person, grade, name)
        case * :
            (false, person, default(int), default(string))
    ))
    .TakeWhile(tuple => tuple.Item1)
    .Select(tuple => new { person = tuple.Item2, grade = tuple.Item3, name = tuple.Item4 })
    // end of let expansion
    .Where(projected => projected.grade > 65)
    .Select(projected => new { Grade = projected.grade, Name = projected.name });
```

And, for completeness, support `throw`:

```cs
from person in list
let Student { Grade is var grade, Name is var name } = person else throw new InvalidOperationException("oops!")
where grade > 65
select new { Grade = grade, Name = name };

// translated into

list
    // beginning of let expansion
    .Select(person => person switch (
        case Student { Grade is var grade, Name is var Name } :
            (person, grade, name)
        case * :
            throw new InvalidOperationException("oops!")
    ))
    .Select(tuple => new { person = tuple.Item1, grade = tuple.Item2, name = tuple.Item3 })
    // end of let expansion
    .Where(projected => projected.grade > 65)
    .Select(projected => new { Grade = projected.grade, Name = projected.name });
```

**Comment by alrz** [comment]
@HaloFour Still, you are translating `let` to more than one LINQ operator (and worse, depending on the `else` clause). Supporting `break`, `continue` or `throw` in query expressions just for `let` doesn't make much sense, and also, you assumed that `continue` and `break` are expressions, otherwise the `else` clause should have some weird production rules to support them besides of `throw`. However, I believe they should be expressions to be able to write something like [#5143 comment](https://github.com/dotnet/roslyn/issues/5143#issuecomment-159113202).

My two cents,
```cs
extension<T> IEnumerable<T> {
  public IEnumerable<T> Select<TResult>(Func<T, Option<TResult>> selector) {
    foreach(var item in this) {
      let Some(var value) = selector(item) else continue;
      yield return value;
    }
  }
}

from obj in list
let Foo foo = obj
select foo;

list.Select(obj => obj is Foo foo ? Some(foo) : None());

from person in list
let Student { Grade is var grade, Name is var name } = person
where grade > 65
select new { Grade = grade, Name = name };

list.Select(person => person is Student { Grade is var grade, Name is var name } ?
  Some((grade,name)) : None())
.Where(t => t.grade > 65)
.Select(t => new { Grade = t.grade, Name = t.name});
```
Then you might think of `else continue` to make it explicit.

Using tuples for fallible patterns is not intuitive at all, because still you need to allocate `default` values which totally loses the point. I think an `option` type is the best solution to this kinds of problems, regardless of what language you are coding in.

**Comment by HaloFour** [comment]
@alrz 

> Still, you are translating `let` to more than one LINQ operator (and worse, depending on the else clause).

There is nothing that states that a LINQ clause must be directly translated to a single extension method.  I am working with what I have.  .NET 3.5 LINQ has no single function which performs both a map and a filter.  If a future version of the BCL does include such a function then that would be a good target for optimization, but as it stands I see no reason to limit the feature to some not-yet-released CLR.

I am aware that I am using tuples in my example translation which would not exist until a new BCL is released.  When targeting a currently released framework the translation would use anonymous types instead, just as it does today with `let` range variables.

> Supporting `break`, `continue` or `throw` in query expressions just for `let` doesn't make much sense, and also, you assumed that `continue` and `break` are expressions, otherwise the `else` clause should have some weird production rules to support them besides of `throw`.

I think it makes a lot of sense and also provides good symmetry for the non-LINQ destructuring form of `let`.  And none of those statements need to be treated as expressions as the `else` clause cannot produce a value.  What follows the `else` clause is an *embedded-statement* which must not reach the end of the block.  This would be the exact same syntax *and behavior* that would be expected of the non-LINQ destructuring statement when used within a loop.

> Using tuples for fallible patterns is not intuitive at all, because still you need to allocate default values which totally loses the point.

The developer doesn't have to do anything.  The use of anonymous types, tuples or even `Option<T>` would be strictly an implementation detail.  And the compiler using `default(T)` to fill in those empty anonymous type or tuple properties is effectively free.

Also, I don't think that going for an "overload" of `Select` is a good idea for your proposed extension method.  There are valid reasons to want to include the `None` results in the projected sequence.

**Comment by alrz** [comment]
@HaloFour 
> There is nothing that states that a LINQ clause must be directly translated to a single extension method.

I think that was the first thing that came up and lead to `SelectMany` etc. Otherwise an additional `Where` would just work.

> I see no reason to limit the feature to some not-yet-released CLR.

Same was true for `await` and it is true for tuple types now, but they probably can be supported through some libraries in earlier versions.

>What follows the else clause is an *embedded-statement*

So, perhaps you need to end your embedded statement with a semicolon? Furthermore, embedding an embedded statement in a query expression doesn't seem like a good idea.

>The developer doesn't have to do anything. 

True, but those values will be allocated eventually right?

**Comment by HaloFour** [comment]
@alrz 

> I think that was the first thing that came up and lead to `SelectMany` etc. Otherwise an additional Where would just work.

That was a conceptual implementation that would have avoided the multiple extension methods but would have created an unwanted dependency on `IEnumerable<T>`.  If you read back @gafter was satisfied with my original transformation which I simply repeated here.

> Same was true for `await` and it is true for tuple types now, but they probably can be supported through some libraries in earlier versions.

Actually `await

**Comment by alrz** [comment]
@HaloFour "Why?" because the semicolon is a part of an embedded statement. "the clause does not need to be an expression since no value is being returned." That is also true for `throw`, then I don't see why `continue` or `break` can't be an expression to be used in `switch` in the example that I mentioned above. "No, `default(string)` is literally the same as `null`" I meant the additional wasted pointer, no allocation. PS: At first your comment looked like the unfinished portrait of Franklin Roosevelt :smile:

**Comment by HaloFour** [comment]
@alrz 

> because the semicolon is a part of an embedded statement.

embedded-statement is a list of other potential statements.  Some of those statements do have semicolon requirements, although block doesn't.  I'd be fine if the spec for `let` in this context differed syntactically as obviously a semicolon at that part of the query makes no sense.

> That is also true for `throw`, then I don't see why `continue` or `break` can't be an expression to be used in `switch` in the example that I mentioned above.

Probably because you're using the expression form of `switch` and it was mentioned that it was a bad idea to let the middle of an expression use control statements.  That's a different proposal altogether, though.  The non-LINQ `let` would permit `continue` or `break` in it's `else` clause so this would provide a nice symmetry, and these control statements can only affect the query, not the declaring method.

>  I meant the additional wasted pointer, no allocation.

64-bits of empty space, no big deal.  I'm all for going with a more optimal route given a newer BCL but I think it's ridiculous to not permit a language feature to work on the older frameworks when there is clearly an easy way to implement it, even if it might be slightly less efficient.

>  PS: At first your comment looked like the unfinished portrait of Franklin Roosevelt

I managed to accidentally find some kind of keyboard combination which submits the comment immediately.  I don't even know what I hit :frowning:

**Comment by alrz** [comment]
@HaloFour As the last inquire, would it make sense to turn `let` clause to `let` statement in case of presence of `do` as the last part of the query (#1938) so it doesn't take the unpleasant translation of an incomplete `let` to tuples with an additional `bool`?
```cs
from obj in list
let Foo foo = obj else continue
do WriteLine(foo.Bar);

foreach(var obj in list) {
  let Foo foo = obj else continue;
  WriteLine(foo.Bar);
}
```

**Comment by HaloFour** [comment]
@alrz Works for me.  I'd want the compiler to use the most efficient implementation that it could.

**Comment by orthoxerox** [comment]
@alrz LINQ `from`-syntax is always rewritten into LINQ functional syntax. You would need to add a lookahead translation rule like the one for `from-from-select`, for example.

```c#
from x1 in e1
let P1 x2 = e2 else continue
do s3;
```
would be rewritten into:

```
e1.Select(x1 => {
    let P1 x2 = e2 else return;
    { s3; }
})
```

**Comment by alrz** [comment]
@orthoxerox Per @gafter's [comment](https://github.com/dotnet/roslyn/issues/1938#issuecomment-179607159), it will be a new statement form, not on top of existing *query-expression*, so natually, there will be a lookahead, but I'm not sure about `let` translation.

**Comment by alrz** [comment]
@orthoxerox And your example will be translated to `foreach`. See #1938.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #355](https://github.com/dotnet/csharplang/issues/355) via [**ZenHub**](https://www.zenhub.com/)
