### ISSUE TITLE
Question: Source generator that uses JSON source generator?

### ISSUE THREAD

**Issue by lskyum** [dotnet/roslyn#68779]
The scenario is that I'm using a source generator to generate JSON-RPC request/response handlers.
The generated classes uses reflection based JsonSerializer (System.Text.Json) which works really great.

But what if I was to generate a JsonSerializerContext and use that instead of the reflection based serialization?
Would that even work and what is the logic behind which source generator "triggers" the other?

**Comment by CyrusNajmabadi** [comment]
All source generators run simultaneously against the initial set of sources (the users actual source code). Then, that initial code is combined with the generated code to produce the entire day of files which are compiled. 

Generators never see the results of other generators.

**Comment by sharwell** [comment]
Duplicate of #57239

**Comment by lskyum** [comment]
@CyrusNajmabadi Thanks for the quick answer!

I guess it means, that it would not work, because System.Text.Json.SourceGeneration would not be able so see the JsonSerializerContext that my JSON-RPC generator produces.

**Comment by CyrusNajmabadi** [comment]
Correct.

**Comment by lskyum** [comment]
@CyrusNajmabadi has it ever been considered to have "developer triggered source generators" to prevent the performance problems with chained source generators? Just triggered manually in Visual Studio or dotnet CLI whenever the developer wants. And also during build i guess...

**Comment by CyrusNajmabadi** [comment]
Yes. We are considering exactly that. :-)

**Comment by b-straub** [comment]
> Yes. We are considering exactly that. :-)

Timeframe?
