### ISSUE TITLE
Error List does not present the correct URI for the displayed diagnostic ID from a Roslyn analyzer's  helpLinkUri

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68816]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-List-does-not-present-the-correct-/10401678)._

---
I have a Roslyn code generator that issues a variety of diagnostics via `Microsoft.CodeAnalysis.DiagnosticDescriptor` wherein the `helpLinkUri` points to a URI on our local Wiki hosted on an MS DevOps server. When it detects a bit of bad code, a red or blue squiggle appears under the offending syntax, and hovering over the bad syntax yields a tooltip popup that displays the error. Within that popup, the diagnostic ID is a link that correctly represents the URI from the `helpLinkUri`—as expected.

However, if one builds the project with the offending code in Visual Studio, the Error List window displays the diagnostic as a Warning or Error (correctly), with the ID and message from the `DiagnosticDescriptor` (correctly), but the ID links to a learn.microsoft.com URI instead of the one specified in the `DiagnosticDescriptor`'s `helpLinkUri`.

---
#### Feedback Bot on 6/27/2023, 07:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
I am unable to reproduce this on latest 17.8 dogfood build. Installing https://www.nuget.org/packages/StyleCop.Analyzers/ to a project reports SAxxxx diagnostics with custom helpLinkUri and error list entries point to the correct ones used by the analyzer.

If you are still able to reproduce this, kindly share the name of the Third party analyzer NuGet with which you see this issue and reopen it. Thanks!
