### ISSUE TITLE
Collection expressions: implement IOperation

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#68826]
See https://github.com/dotnet/roslyn/issues/70631 for proposed API.

Note, the previous issue https://github.com/dotnet/roslyn/issues/68687 is referenced in `UseCollectionExpressionHelpers.cs`.

**Comment by cston** [comment]
See also https://github.com/dotnet/roslyn/pull/68795#discussion_r1244636157 to remove `BoundKind.UnconvertedCollectionLiteralExpression` from `CSharpOperationFactory`.

**Comment by jcouv** [comment]
As part of the IOperation work, we'll likely also need to extend `CommonConversion` so that it can represent collection-expression conversions.

**Comment by cston** [comment]
See also related issue https://github.com/dotnet/roslyn/issues/69938.

**Comment by cston** [comment]
Resolving as duplicate of API proposal: https://github.com/dotnet/roslyn/issues/70631.
