### ISSUE TITLE
MemberNotNullAttribute not working as expected when member is in a parent Interface/Class

### ISSUE THREAD

**Issue by tkreindler** [dotnet/roslyn#68836]
### Description

I have a relation between the following two interfaces. Essentially, items have an Id and it's nullable - but if you call the Save function it's guaranteed to be non-null after that. In theory this seems like a perfect use case for MemberNotNullAttribute, however as you can see it doesn't work properly since the Id field is in a parent interface.

Here's an overview of my code:

    interface IReadOnlyItem
    {
        Id? Id { get; }
    }

    interface IItem : IReadOnlyItem
    {
        [MemberNotNull(nameof(Id))]
        void Save();
    }

When I reproduce this code locally I get an error trying to access the Id field after a Save call because it might be null. If I move the Id property to the IItem interface it works perfectly, recognizing the MemberNotNull attribute. Unfortunately for my code this   is untenable - Id has to live in the parent interface and Save has to live in the child interface.

### Reproduction Steps

    interface IReadOnlyItem
    {
        Id? Id { get; }
    }

    interface IItem : IReadOnlyItem
    {
        [MemberNotNull(nameof(Id))]
        void Save();
    }

And then using it in a Nullable=true context

    {
        IItem item = new Item();

        item.Save();

        Id id = item.Id; // has a null value build time error
    }

### Expected behavior

The above code would compile under a nullable context

### Actual behavior

It does not

### Regression?

Unlikely

### Known Workarounds

Overriding the nullability with a '!' in our consumer's code

### Configuration

- 6.0.406 .Net
- Windows 11
- x64
- Almost certainly not specific to this configuration.

**Comment by jcouv** [comment]
There is also a warning report on the `[MemberNotNull(...)]` attribute, which indicates that that usage is not supported. The attribute can only be used to refer to a member of the type, not an inherited member. This behavior is by-design.

```
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/68836")]
        public void TODO2()
        {
            var source = """
#nullable enable

using System.Diagnostics.CodeAnalysis;

class C
{
    void M(I2 i2)
    {
        i2.Init();
        object id = i2.Prop;
    }
}

interface I1
{
    object? Prop { get; }
}

interface I2 : I1
{
    [MemberNotNull(nameof(Prop))]
    void Init();
}
""";
            var comp = CreateCompilation(new[] { source, MemberNotNullAttributeDefinition });
            comp.VerifyDiagnostics(
                // 0.cs(10,21): warning CS8600: Converting null literal or possible null value to non-nullable type.
                //         object id = i2.Prop;
                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "i2.Prop").WithLocation(10, 21),
                // 0.cs(21,6): warning CS8776: Member 'Prop' cannot be used in this attribute.
                //     [MemberNotNull(nameof(Prop))]
                Diagnostic(ErrorCode.WRN_MemberNotNullBadMember, "MemberNotNull(nameof(Prop))").WithArguments("Prop").WithLocation(21, 6)
                );
        }
```
