### ISSUE TITLE
unused variables not dimmed inside lambdas/delegates

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68839]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/unused-variables-not-dimmed-inside-lambd/10381902)._

---
\[regression\] \[worked-in:17.0\]  
Check the screenshot. Unused variable “abc1” is faded because it’s unused.

But the variable “abc2” inside lambda is not faded, even though it’s also unused.

![image](https://github.com/dotnet/roslyn/assets/10605811/25b30c8a-1822-43e6-9f94-ac9e0e0ba391)

UPDATE: same issue happens inside "try { }" block

---
#### Feedback Bot on 6/2/2023, 08:04 AM: 

(private comment, text removed)
#### Feedback Bot on 6/2/2023, 07:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Unused assignments are not flagged inside unused lambdas as we only analyze reachable code blocks in the IDE0059 analyzer. There should be a different diagnostic to flag unused lambda.
