### ISSUE TITLE
Compiler crashes when attempting to compile string interpolation concatenation with parentheses applied

### ISSUE THREAD

**Issue by saltukkos** [dotnet/roslyn#68834]
**Version Used**: 
main (27 June 2023)
**Steps to Reproduce**:

1. Compile the next code:
```
using System;
public class C {
    public void M() {
        System.Runtime.CompilerServices.DefaultInterpolatedStringHandler fs = $"aaa" + $"bbb" + ($"ccc" + $"ddd");
    }
}
``` 

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBBmABM3AYVwG9NcL88EAWXAWQAoBKU8yjhFAOgCUBXGABcoYAKbdCAezAAHKABsxAJwDKKgG5QAxmIDO3ACJiAZhH4KhASWErZUhRCFiAJqqHLYAcwASEGC5KyrgmergAvLgAJABEEPExuADU0THA6YkpjLHauZmpLoUxzADc7BQAvpgVQA=)

**Expected Behavior**: code compiles or compiler error

**Actual Behavior**: compiler crashes with `System.InvalidCastException`

**Comment by jcouv** [comment]
Thanks for reporting this. Fix is in progress for 17.8
