### ISSUE TITLE
Seeding interactive session with project context 

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6884]
( related to dotnet cli but useful for VS as well)

**Comment by ManishJayaswal** [comment]
@genlu

**Comment by ManishJayaswal** [comment]
@drognanar Closing this as this is now implemented.

**Comment by amcasey** [comment]
@drognanar Can you please confirm that any TODOs tagged with this bug number have been addressed (probably just skipped tests)?
