### ISSUE TITLE
VS maxes out CPU for minutes in projects with lots of types

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#68842]
**Version Used**: VS 17.6.3

**Steps to Reproduce**:

1. Open this project in VS: [BuffersRepro.zip](https://github.com/dotnet/roslyn/files/11917295/BuffersRepro.zip)
2. Open `Class1.cs` in the IDE

**Actual Behavior**:

The CPU will be absolutely maxed out for minutes (see screenshot below).
I've recorded a PerfView trace: [link here](https://microsofteur-my.sharepoint.com/:u:/g/personal/sergiopedri_microsoft_com/EZiNaF_cpHtGhCdFqy9tDPIBYWskWB0sn7rvHgKE4DSqUg?e=4bOh0J).

Builds (including from CLI) seem to be reasonably fast. But VS itself just dies when opening the solution/file. I've also seen builds from VS taking minutes, I wonder if this might be from the issue just slowing down VS overall, and builds too as a side effect.

cc. @CyrusNajmabadi

<details>
    <summary><b>Screenshot (click to expand):</b></summary>
<br/>

![image](https://github.com/dotnet/roslyn/assets/10199417/6b43d325-e482-4fa2-912a-d361226ca2c8)
</details>

**Comment by CyrusNajmabadi** [comment]
Looking.

**Comment by CyrusNajmabadi** [comment]
All the time being spent is in the "remove unused members" analyzer: 

![image](https://github.com/dotnet/roslyn/assets/4564579/2a16f4f0-da0f-405f-be44-f32d6183b31f)

@mavasani 

Specifically of interest is this part:

![image](https://github.com/dotnet/roslyn/assets/4564579/e6bd188a-cded-4e97-9163-fe991c756e96)

Unsurprisingly, this is also the higest exclusive time cost of the feature.

Note exactly sure just yet what work in particular is the highest cost.  continuing to look.

**Comment by CyrusNajmabadi** [comment]
GetCandidateSymbolsReferencedInDocComments is the major culprit, accounting for 56% of the time spent.

**Comment by CyrusNajmabadi** [comment]
Working on mitigation now.

**Comment by arkalyanms** [comment]
@Sergio0694 it would be great to hear back from you on the impact of the change, once it goes in. We would love to get a rough before and after impact and see if there are any other residual opportunities to chase down.

**Comment by Sergio0694** [comment]
@arkalyanms happy to report back, absolutely! For context, I hit this while I was prototype a new feature for https://github.com/Sergio0694/ComputeSharp, which would require me adding about 4096 types like those in the repro. So like, this is an actual real use case, not just a weird isolated repro. As of today, I just cannot do that at all, because VS would just become effectively unusable. If this fix (and potentially others) could allow me to implement the feature without VS significantly slowing down, then that'd be a pretty nice win for me, personally 😄

**Comment by sharwell** [comment]
@Sergio0694 If you disable the analyzer for "Remove unused members", does the problem go away? Just want to make sure there aren't other problems that will be hit once the known issue is fixed.

**Comment by Sergio0694** [comment]
@sharwell not seeing the analyzer in the list, could you elaborate how I should disable it? 😅
Happy to test then!

**Comment by sharwell** [comment]
@Sergio0694 you'd need to disable both IDE0051 and IDE0052.
