### ISSUE TITLE
Expose MoveToNamespace action in code fixes

### ISSUE THREAD

**Issue by SamPruden** [dotnet/roslyn#68853]
## Background and Motivation

I would like to write an analyzer and codefix to enforce a specific namespace/directory relationship that's a little different from the standard, motivated by the Unity game engine. I would like the codefix to be able to do the equivalent of [MoveToNamespace](https://github.com/dotnet/roslyn/tree/main/src/Features/Core/Portable/MoveToNamespace) when changing namespaces, but as far as I can tell that functionality isn't exposed.

I tried looking at the [MatchFolderAndNamespace](https://github.com/dotnet/roslyn/tree/main/src/Analyzers/Core/CodeFixes/MatchFolderAndNamespace) codefix for tips, but it looks like that moves the file to match the namespace, which is the opposite of what I want.

It might be possible to chase symbol references throughout the solution and to manually patch them to a changed namespace, but this seems very brittle to problems such as ambiguities introduced by adding new `using`s to other files. Presumably the infrastructure for doing this well already exists and could be exposed.

## Proposed API

I would expect an API similar to `Renamer` for refactoring namespaces.

**Comment by CyrusNajmabadi** [comment]
This needs a real api proposal.  Ideally with a PR showig that this is even possible to do.
