### ISSUE TITLE
Can't trigger inline method from the method itself, and inlining can break compilation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68874]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-trigger-inline-method-from-the-met/10407461)._

---
[severity:It's more difficult to complete my work]
For some time I assumed that Visual Studio didn't support "inline C# method" refactoring but I just realized that I have to go to where the method is used. And when I do, I am asked "inline X()" or "inline and keep X()" even when the former would introduce a compilation error because there are other callers of InlineMe(). 

Example code below
```csharp
        static void Baz()
        {
            X();
        }

        static void Bar()
        {
            X();  // here offered "Inline X()" and "Inline and keep X()" but the former breaks compilation in Baz()
        }

        static int X()  // here expecting to be offered "Inline X()" and possibly "Inline and keep X()" but not offered either
        {
            return 1;
        }
```
What I'm expecting
1. allow me to inline a method everywhere (possibly with option to keep it as well) not just at one call site.
2. don't offer me refactorings that break the build. either make the refactoring work (eg., inline all) or don't offer it.

---
#### Dan Moseley [MSFT] on 7/4/2023, 00:40 PM: 

(private comment, text removed)
#### Feedback Bot on 7/4/2023, 08:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
