### ISSUE TITLE
Analyzer "Apply unused value preferences" doesn't produce working code in VB with option Strict On

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68877]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Analyzer-Apply-unused-value-preferences/10405429)._

---
If you run the Analyzer on VB Code like below
```
   Private Sub SgTextBox_GotFocus(sender As Object, e As EventArgs) Handles SgTextBox.GotFocus
       Me.HiddenTextBox.Focus()
   End Sub
```
Becomes
```
   Private Sub SgTextBox_GotFocus(sender As Object, e As EventArgs) Handles SgTextBox.GotFocus
       Dim unused = Me.HiddenTextBox.Focus()
   End Sub
```
And you get error BC30209 "Option Strict On requires all variable declarations to have an 'As' clause."
On a small project you could be 100's and I don't see any .editorConfig option to specify my preferences for VB.

---
#### Paul M Cohen on 7/2/2023, 08:17 PM: 

(private comment, text removed)
#### Paul M Cohen on 7/2/2023, 08:19 PM: 

(private comment, text removed)
#### Feedback Bot on 7/3/2023, 01:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by paul1956** [comment]
@sharwell the title is wrong. Its option Strict On

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not planning on any work here.
