### ISSUE TITLE
The "Add missing using directives on paste" option doesn't respect global usings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68884]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Add-missing-using-directives-on-pas/10400671)._

---
[severity:It bothers me. A fix would be nice]
With setting **text Editor > C# > Advanced > Add missing using directive on paste** enabled, using directives that are already present in the global usings file end up being added to the code file. This only gets noticed in the PR review, so I'm always having to do an extra commit just to remove the redundent usings that Visual Studio added. 

---
#### Feedback Bot on 6/26/2023, 06:41 PM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2023, 06:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I cannot repro this.
