### ISSUE TITLE
Implement send to interactive command

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6888]

**Comment by ManishJayaswal** [comment]
@genlu

**Comment by m0sa** [comment]
+1 yes, please!

**Comment by ManishJayaswal** [comment]
@drognanar Closing this as this is now implemented.

**Comment by amcasey** [comment]
@drognanar Can you please confirm that any TODOs tagged with this bug number have been addressed (probably just skipped tests)?
