### ISSUE TITLE
CS0111 error upon rebuild

### ISSUE THREAD

**Issue by harishkumar-harihara** [dotnet/roslyn#68895]
[SourceGeneratorErrors.zip](https://github.com/dotnet/roslyn/files/11969501/SourceGeneratorErrors.zip)

**Steps to Reproduce**:

1. Build & run the program once => Generates OK
2.  Rebuild the program again => Error CS0111 occurs, the code generated multiple times in the output file

**Scenario**
The source generator project does not refer the target project directly, instead finds target class for code generation using context.Compilation.GetTypeByMetadataName.

**Description**
ISourceGenerator project to auto-generate a class based on another, changing method signature from Span to Array.

**Comment by Youssef1313** [comment]
This is a bug in the source generator itself. You shouldn't have a static `_methodsToGenerate` that you add methods to, because you end up with duplicates in this static state.

Also, try to move away from `ISourceGenerator` to IIncrementalGenerator` when possible.

**Comment by jcouv** [comment]
Thanks @Youssef1313. Closing as by-design
