### ISSUE TITLE
Support inline arrays with collection literals

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#68927]
- Allow inline array types as target types for collection literals.
- Allow inline arrays as spread elements.

Relates to test plan https://github.com/dotnet/roslyn/issues/66418

**Comment by jaredpar** [comment]
@cston, @AlekseyTs where did we land on the intersection of these features?

**Comment by cston** [comment]
From LDM, this was low priority for C#12 - [see notes](https://github.com/dotnet/csharplang/blob/main/meetings/2023/LDM-2023-08-14.md#conclusion-4).

**Comment by cston** [comment]
Closing for now. We can re-open when we have concrete plans to support inline array target types.
