### ISSUE TITLE
class schema, class namespace wrongly composed and indented in Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68920]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/class-schema-class-namespace-wrongly-co/10409433)._

---
[severity:It bothers me. A fix would be nice]
While creating a new class in project with a number in it's namespace, that's the result. 
It's fully wrong also because it should have used new namespace/class template (namespace MyNamespace; public class MyClassName {}).

1. Wrong typing namespace (.3216 instead of ._3216)
2. Wrong indentation (presumely due to first error)
3. Wrong namespace templates structure/schema

![image](https://github.com/dotnet/roslyn/assets/1408396/4ec3ab6d-8275-4996-b2ca-5f362e91ec04)

This should be the correct result

![image](https://github.com/dotnet/roslyn/assets/1408396/b4843c00-1b2c-4b5b-92ca-ef62a61f9a6e)

---
#### Feedback Bot on 7/6/2023, 09:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
