### ISSUE TITLE
Organize Imports command handler should apply changes using async progress UI

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68921]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/intellisense-hangs-with-waiting-for-back/10409976)._

---
the solution was upgraded from Net Framework to Net 7.0-windows. it compiles and runs successfully. hangs whenever we try IntelliSense assist

---
#### Feedback Bot on 7/7/2023, 02:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Performance traces attached to the feedback ticket show the UI blocked in `GetFullyLoadedOpenDocumentInCurrentContextWithChanges`. This approach is unnecessary and undesirable for `OrganizeDocumentCommandHandler.SortAndRemoveUnusedImports`. It should instead use the async progress UI to apply changes, similar to the way Add Usings on Paste works without interfering with the user's experience.
