### ISSUE TITLE
Update `ConstructedNamedTypeSymbol` to use OneOrMany instead of ImmutableArray for type arguments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#68933]
`ConstructedNamedTypeSymbol` currently represents the type arguments using `ImmutableArray<TypeWithAnnotations>`. It might be a good idea to use OneOrMany to avoid the allocation for the case when the type arity is 1.

Judging per the following:

![image](https://github.com/dotnet/roslyn/assets/31348972/9906a8e2-5fb1-41e3-a99b-d1e3301e0a7b)

**Comment by CyrusNajmabadi** [comment]
Seems like it could be a good win.  Should consider for methods as well.

**Comment by Head0nF1re** [comment]
Hi, can I work on this issue? Would be my first one here.
Already started changing the type in a couple of places on my local branch.

**Comment by RikkiGibson** [comment]
I think the problem is that actually benefitting from use of 'OneOrMany' here requires broadly changing the return type of symbol APIs returning type arguments, which doesn't feel worth it.

**Comment by RikkiGibson** [comment]
I think we shouldn't make the change suggested in this issue due to the necessary level of churn involved.
