### ISSUE TITLE
Consider having a threshold to choose between list/array vs dictionary for lookup

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#68946]
A linear search can perform better than a dictionary lookup if the number of elements is small enough.

Consider having some data structure that internally uses either a list/array, or a dictionary, depending on the number of elements.

This is to be used here, for example:

https://github.com/dotnet/roslyn/blob/33496991002bcf1093028e82671fc5c0de2aa4bf/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol.cs#L262-L287

so `MakeNameToMembersMap` will be effectively creating either a dictionary or a list/array, so that the lookup can be faster if the number of elements is small.

**Comment by Youssef1313** [comment]
![image](https://github.com/dotnet/roslyn/assets/31348972/f182253b-aee5-4d84-9f9f-e3de7eb83d54)

![image](https://github.com/dotnet/roslyn/assets/31348972/826b4353-b774-47f7-a85a-e4744a86e8a3)

Is `TryGetValue` a bottleneck here? Would this resolve it?

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 if you could attach the trace files to these issues, that would be helpful.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi The one I sent you privately this morning is for the same scenario, and I'll be uploading another one taken with larger `-CircularMB` and `-BufferSizeMB`

**Comment by CyrusNajmabadi** [comment]
can you attach (or link) to this as well, just for anyone else who might be looking into this.  Thanks! :)

**Comment by Youssef1313** [comment]
https://developercommunity.visualstudio.com/t/Private-trace-for-https:githubcomdot/10410953

**Comment by sharwell** [comment]
@Youssef1313 I see MakeNameToMembersMap as 0.027% CPU (27 total samples in the trace). Can you clarify which part suggested a problem?

**Comment by Youssef1313** [comment]
I'm not sure, you'd definitely know better, but here I see `TryGetValue` taking 1.5% CPU (if I'm interpreting properly)

![image](https://github.com/dotnet/roslyn/assets/31348972/7674cbef-d19f-4def-9591-bd33590232ff)

**Comment by Youssef1313** [comment]
@sharwell The scenario being tested here is a source generator aggressively calling `GetSymbolInfo` (this is something I'm working on improving at the source generator side already). But I wanted to see what can be done for `GetSymbolInfo` to be faster.

**Comment by sharwell** [comment]
Based on the allocation pattern in the trace, I would first try resolving this by caching the most recent return value for this line:
https://github.com/dotnet/roslyn/blob/1056a3cfb70b65da1b14fcf51a5286b597e1b1d2/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamespaceSymbol.cs#L106

The trace suggests that there are significant numbers of cases where namespace `Y` is resolved within namespace `X`. Common coding practices suggest that in many cases, the same namespace lookup would occur multiple times in sequence (e.g. for Microsoft.CodeAnalysis.dll, it's extremely likely that the first element of a qualified name will be `Microsoft` and that the second element will be `CodeAnalysis`).

If the incoming `name` parameter is the same as the most recent result returned from this line, we can return the same result without a new allocation or any dictionary lookups.

**Comment by Youssef1313** [comment]
@sharwell Is it this allocation?

![image](https://github.com/dotnet/roslyn/assets/31348972/6dee6522-0e35-4f75-aeba-ffb924f125ef)

The call stacks don't show complete in the trace, so I'm unsure how you figured out it's this code path. But:

![image](https://github.com/dotnet/roslyn/assets/31348972/d9d9a66c-c621-472d-94fa-dfbe64fede4a)

The `Symbol[]` allocations are much more for `GetTypeByMetadataName` compared to `GetSymbolInfo`, however, the CPU stack shows most time is spent in `GetSymbolInfo`. So I'm a bit confused.

**Comment by Youssef1313** [comment]
Oh. Thanks @sharwell!

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
