### ISSUE TITLE
Design and implement flow analysis APIs

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6895]

**Comment by ManishJayaswal** [comment]
@genlu

**Comment by ManishJayaswal** [comment]
IOperation work is getting tracked via many other issues so closing this out.

**Comment by JohnHamby** [comment]
This is work on top of IOperation, and is not tracked by other issues.

**Comment by canerozden** [comment]
Hey guys, do you want to extend the dataflow analysis functions that exist, or should we understand that there will be a new flow analysis api that does more job? 
The existing data flow analysis functions gives us little information sometimes. If the result symbols are global variables (property or field) the AnalyzeDataFlow function returns a symbol "this" for every global varible. So we can not understand which varible is readinside for example.

**Comment by CyrusNajmabadi** [comment]
Closing this out as we have AnalyzeDataFlow, and we have the new IOPeration and ControlFlowGraph apis to support these scenarios.
