### ISSUE TITLE
Finish work on VB scripting APIs

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6897]

**Comment by ayman-metwally-developer** [comment]
May I know the plan of this feature? the answer will direct a major design decision.

**Comment by ayman-metwally-developer** [comment]
Please update: Is this feature abandoned?

**Comment by tmat** [comment]
We decided to focus our Visual Basic investments on improvements in tooling of existing language features and interoperability with new C# language features and .NET APIs. See [The .NET Language Strategy](https://blogs.msdn.microsoft.com/dotnet/2017/02/01/the-net-language-strategy) for more details.
