### ISSUE TITLE
Intellisense won't show event names in VB.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#68976]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-wont-show-event-names-in-V/10411844)._

---
_Environment_
I have a WinForms-.NET-FX 4.8 VB.NET-project in Visual Studio Version Version 17.7.0 Preview 2.0 on a 64-bit Win10 PC, but it also happens in a WinForms-.NET 7.0 VB.NET-project.

**Problem**
Intellisense won't show the event names of an object, but accepts them, when written completely.

**Description**
If I have a button called Button1 and I type
```Dim EventName = NameOf(Button1.Cl```
I expect a list of fitting proposals, because I'd like to have
```Dim EventName = NameOf(Button1.Click)```
But the events of this object won't be listed, as you can see here:

![image](https://github.com/dotnet/roslyn/assets/1408396/4a5e5eda-a0b0-4284-bbcc-91f46354903b)

If I try the same in C#, it works. I write
```string EventName = nameof(button1.Cl```
and I get the expected list:

![image](https://github.com/dotnet/roslyn/assets/1408396/51093b59-ef7e-416f-b6d1-c9691719ec1a)

As you can see, there is also a filter button at the bottom of the list to get only the events. This isn't available in VB.NET.

.

**Consequences**
It takes more time to complete my work.

**Remark**
The event proposal list exists in the line of event handlers, so basically it _would/could/should_ work:
![Handles clause.png](https://aka.ms/dc/image?name=B1a2f9e209f7c431399cff675a25615fd638246194832091914_Handles_clause.png&tid=1a2f9e209f7c431399cff675a25615fd638246194832091914)

---
#### Feedback Bot on 7/10/2023, 08:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these scenarios.
