### ISSUE TITLE
IDE0057: Suggestion removes constant start index from Substring

### ISSUE THREAD

**Issue by limjiawei92** [dotnet/roslyn#68973]
**Version Used:**
Visual C# Compiler version 4.6.0-3.23259.8 (c3cc1d0c)

**Steps to Reproduce:**

Call Substring using the following as start indexes: a constant integer with value 0, a non-zero constant integer, an integer with value 0, and a non-zero integer

```
string text = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

const int POS1 = 0;
const int POS2 = 4;
int pos3 = 0;
int pos4 = 4;
            
string result1 = text.Substring(POS1, 4);
string result2 = text.Substring(POS2, 4);
string result3 = text.Substring(pos3, 4);
string result4 = text.Substring(pos4, 4);
```

IDE0057 will suggest that the first Substring can be simplified.

**Expected Behavior:**

IDE0057 should not suggest to use the range operator in all 4 cases.

**Actual Behavior:**

IDE0057 suggests to replace the first substring with:

```
string result1 = text[..4];
```

This reduces readability because POS1 is now unused.
If the value of POS1 needs to be changed to a non-zero value in the future, the user will have to hunt down all such cases instead of simply changing the value of the constant.
This doesn't happen if the start index is not a constant.

**Suggestion:**
This is just a minor inconvenience but it will be nice to consistently suppress the suggestion for all such cases.

**Comment by CyrusNajmabadi** [comment]
The idea behind (and reason to use) a constant, is your are stating *up front* that you are ok with that constant value being embedded at all reference sites.  Indeed, when you change a constant, downstream libraries do not see the change *unless* you recompile them. 

As such, this suggestion is very appropriate as the semantics are preserved, and the expectation is that since you used a constant it would stay constant. If you want to change the value in the future, def don't use a constant as, well, you are varying the value :-)

**Comment by limjiawei92** [comment]
That makes sense, thank you.

**Comment by CyrusNajmabadi** [comment]
You're welcome!

**Comment by anthonymastreanvae** [comment]
Why doesn't the analyzer pick up the 2nd line? The first parameter `POS2` is non-zero constant.

```
string result2 = text.Substring(POS2, 4);
```

Why is this case not supported by the analyzer?

https://github.com/dotnet/roslyn/blob/main/src/Analyzers/CSharp/Analyzers/UseIndexOrRangeOperator/CSharpUseRangeOperatorDiagnosticAnalyzer.cs#L278-L280

**Comment by CyrusNajmabadi** [comment]
@anthonymastreanvae what would you expect that to be converted to?

**Comment by anthonymastreanvae** [comment]
I guess I expected something like this, but I suspect you're going to tell me why you can't or shouldn't construct that end expression 😅 

```
string result2 = text[POS2..(POS2 + 4)];
```

**Comment by CyrusNajmabadi** [comment]
yup.  that seems less idiomatic than the original expression. as it's not an improvement, we should not suggest it.  Tnx.

**Comment by anthonymastreanvae** [comment]
The range operator _can_ do everything `Substring` can do, no? The analyzer suggests only a fraction of the changes that are supported/possible. If you leaned _only_ on the analyzer, you'd have a lot of work left to do to convert fully to the range operator. 🤷‍♂️
