### ISSUE TITLE
Roslyn requires the SizeConst metadata on a MarshalAsAttribute for UnmanagedType.ByValTStr but not UnmanagedType.ByValArray

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn#68988]
**Version Used**: 4.7.0

**Steps to Reproduce**:

1.  Add the `[MarshalAs(UnmanagedType.ByValTStr)]` attribute to a field.
2.  Observe that a CS7046 error is reported.
3.  Change the `UnmanagedType` to `UnmanagedType.ByValArray`.
4. Observe that the error goes away even though all systems have the same requirements for both.

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

[SharpLab Link](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwDoBKArgHbBgC2ApjgJIkUBOA9gA4DKDAbmAMYUDOAbgCwAKFHIAzOj7B6BbsHStRAb1HoN6ANoBZAIb0+ACz0QAgnwAUAVSJk9RPQHMKMACoBPZlQBCHgGqmbqyyAJQAuuqakphYGIJRGona+oYm5la29o4u7l6+AaZm9PR6HhHJMWAkWuHoesIimuiiAL5AA=)

**Diagnostic Id**: CS7046

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

CS7046 is reported for both `ByValTStr` and `ByValArray`, as all runtimes (.NET Framework, CoreCLR, etc) require the SizeConst metadata and throw an exception if it is not present for both cases.

**Actual Behavior**:

CS7046 is only reported for `ByValTStr`.

Fixing this issue would obsolete https://github.com/dotnet/runtime/issues/36134 (as the compiler already does half the analyzer, and this issue corresponds to the remaining work).

**Comment by jaredpar** [comment]
Do not believe this can be an error. Right or wrong it's behavior the compiler has allowed for 8+ years. Guessing it replicates back to the native compiler too. As such making this an error, even for code that won't execute at runtim correctly, isn't going to work. 
Think a warning wave would be the only path forward assuming it meets the bar.

**Comment by jkoritzinsky** [comment]
I'm fine with a warning wave instead of a compile error. I do feel that the compiler should handle this instead of an analyzer in roslyn-analyzers as the compiler is already handling the other identical case. Does that sound reasonable?

**Comment by jaredpar** [comment]
A warning wave is fine by me.
