### ISSUE TITLE
3.1% allocations of `TypeConversions`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#68997]
![image](https://github.com/dotnet/roslyn/assets/31348972/015e7886-d02d-41ab-b96a-47282d4407a2)

![image](https://github.com/dotnet/roslyn/assets/31348972/7895e655-28c2-4367-a678-05d3f1b96186)

Allocations happen here:

https://github.com/dotnet/roslyn/blob/86156faa88860dac9b17223623743aea24814291/src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs#L51

Does it make sense to introduce a lazy `TypeConversions` property on assembly symbol, and use it instead of creating `TypeConversions` instances?

**Comment by Youssef1313** [comment]
Trace in https://developercommunity.visualstudio.com/t/Performance-trace-for-Roslyn-team/10413054

**Comment by jaredpar** [comment]
> Does it make sense to introduce a lazy TypeConversions property on assembly symbol, and use it instead of creating TypeConversions instances?

Our `AssemblySymbol` instances are long lived hence that extra allocation will effectively just grow the size of every instance. Not sure that is the best approach. Did you consider attaching it to say the compilation or another symbol relevant to the scenario? 

@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
The symbols are long lived.  But there are relatively few of them.  I think it would likely be fine for either hte assembly-symbol (or the compilation) to have such a cache where this is held onto, instead of continaully recreating it :)
