### ISSUE TITLE
Incorrect Override Suggested By "Generate overrides..." Refactoring

### ISSUE THREAD

**Issue by JasonBock** [dotnet/roslyn#68994]
**Version Used**: 
VS 17.6.4 (I'm not entirely sure that this repo is the correct one as this shows up in VS, but I'm guessing this refactoring is implemented somewhere within the Roslyn bits)

**Steps to Reproduce**:

Create the following code in a .cs file (note that this code, while arguably "odd", is valid C#):

```csharp
public class StaticToString
{
  protected static new string ToString() => "c";
}
```

Next, create a class that derives from `StaticToString`:

```csharp
public class X : StaticToString
{
}
```

Move the cursor to the class name, `X`, bring up the refactorings, and select *Generate overrides...*. You should end up with 3 members to override:

![image](https://github.com/dotnet/roslyn/assets/904213/0846ce2b-24f1-4532-a3d1-82f4c69a951d)

**Expected Behavior**:

You only get two options: `Equals()` and `GetHashCode()`.

**Actual Behavior**:

You get three, with `ToString()` being included. If you pick all three, the following code is created:

```csharp
public class X : StaticToString
{
   public override bool Equals(object? obj) => base.Equals(obj);
   public override int GetHashCode() => base.GetHashCode();
   public override string? ToString() => base.ToString();
}
```

This is incorrect as you can't override `ToString()`. This creates a `CS0506` error.

**Comment by CyrusNajmabadi** [comment]
Closing out as too niche.
