### ISSUE TITLE
IntelliSense allocates large symbol arrays (LOH)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69004]
![image](https://github.com/dotnet/roslyn/assets/31348972/df661568-2505-4345-b27e-0135e26d126c)

Found these LOH allocations in devenv process.

Same trace as for https://github.com/dotnet/roslyn/issues/68997

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of recent traces demonstrating this is still an issue.
