### ISSUE TITLE
Error list errors (examples: XDG0012) opens the browser to bingdev.cloudapp.net - Certificate for that domain is expired... *again*

### ISSUE THREAD

**Issue by DoctorVanGogh** [dotnet/roslyn#69044]
This is a follow-up of #49829.

"Links" for compilation errors (at least those in the XDG... format) lead to bingdev.cloudapp.net which has an expired certificate.... *again*. :facepalm:

![image](https://github.com/dotnet/roslyn/assets/324067/911548d1-1a63-452d-81b1-b91ddcfb9277)

**Comment by jcouv** [comment]
Based on the previous discussion, this link [appears](https://github.com/dotnet/roslyn/issues/49829#issuecomment-740091964) to come from the IDE layer so I'm marking as Area-IDE.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Who should this go to?  I can't imagine we're responsible for this site.

**Comment by jasonmalinowski** [comment]
Closing this out; as of a month or two this site no longer exists.
