### ISSUE TITLE
IDE0038 is not enforced during build

### ISSUE THREAD

**Issue by ravigneaux-1** [dotnet/roslyn#69052]
**Version Used**: 

- .NET SDK 7.0.304
- Microsoft Visual Studio Community 2022 (64-bit), version 17.6.4

**Steps to Reproduce**:

1. Create a project with `<EnforceCodeStyleInBuild>` and `<TreatWarningsAsErrors>` both set to `true`

2. Create an `.editorconfig` file within the same directory with the following contents:

   ~~~ini
   [*.cs]
   dotnet_diagnostic.IDE0020.severity = warning
   dotnet_diagnostic.IDE0038.severity = warning
   csharp_style_pattern_matching_over_is_with_cast_check = true:warning
   ~~~

3. Add the following code to `Program.cs` (or any other class):

   ~~~csharp
   static void Main(string[] args)
   {
       var fileInfo = new FileInfo(@"Dummy.txt");

       if (fileInfo is FileInfo) { var f = (FileInfo)fileInfo; f.Attributes = FileAttributes.Normal; }
       if (fileInfo is FileInfo) { ((FileInfo)fileInfo).Attributes = FileAttributes.Normal; }
   }
   ~~~

**Diagnostic Id**:

[`IDE0020` and `IDE0038`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0020-ide0038)

**Expected Behavior**:

Both `IDE0020` and `IDE0038` are enforceable (according to [`EnforceOnBuildValues.cs#L38`](https://github.com/dotnet/roslyn/blob/main/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs#L38) and [`EnforceOnBuildValues.cs#L53`](https://github.com/dotnet/roslyn/blob/main/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs#L53)) and fail the build, both in the Visual Studio IDE and using `dotnet build`.

**Actual Behavior**:

Only `IDE0020` is enforceable. `IDE0038` does **not** fail the build, neither in the Visual Studio IDE nor using `dotnet build`.

**Comment by CyrusNajmabadi** [comment]
Or we just use a vanilla syntaxrewriter or just node.replacenodes.  

I can look into this when I get back from vacation

**Comment by CyrusNajmabadi** [comment]
We can't move this down.  This fixer requires teh user to manually provide a name for the new member, and then involves the rename experience.  It's fundametnally more a refactoring than anything else.
