### ISSUE TITLE
Disallow extension methods lookup on non-static or generic types

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69051]
https://github.com/dotnet/roslyn/blob/2fb8ad0ce8c49872aa781072037cf921efa3a5fd/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs#L1722

Currently, extension methods lookup for `PENamedTypeSymbol` considers non-static and generic types.

Are there concerns with taking the breaking change and allow lookup **only** for static non-generic classes?

Note: Looking up lots of `PENamedTypeSymbol`s might be part of the performance issues I'm hitting (I'm not actually very sure, but it's possible). I'm very aware that correctness is more important here, but also I think such a breaking change *might* be reasonable. So opened this issue for discussion.

**Comment by jaredpar** [comment]
> Are there concerns with taking the breaking change and allow lookup only for static non-generic classes?

Yes there are definitely concerns with this. Particularly because the compiler has already noted that this as a compat scenario that we need to maintain. A breaking change of this nature would require strong evidence both in terms of need as well as evidence that it won't have impact on existing code. 

At the moment I'm not seeing that so I'm going to close the issue. If that data is available, I'd be willing to revisit this but the data would need to be strong.

**Comment by Youssef1313** [comment]
![image](https://github.com/dotnet/roslyn/assets/31348972/d935abff-918b-452a-9bc7-3d32a71aae04)

@jaredpar This was the motivation I have for this. I can't 100% tell for sure, but I think `DoGetExtensionMethods` is called for non-static types which could be part of this performance issue.

I wonder if this behavior can be gated on `<Feature>strict</Feature>`?

Or alternatively, we might keep this completely for compatibility, but have `MightContainExtensionMethods` being mutable, where the original implementation will return true, but then if getting extension methods yielded no results, we can set it to false. I understand that immutability is a key design of the compilers, and that symbols properties shouldn't change their value during the life-time of the symbol, but I think the value change for `MightContainExtensionMethods` will be kinda transparent and won't have a noticeable impact?
