### ISSUE TITLE
Documentation for options of code-style rules is incorrect/misleading

### ISSUE THREAD

**Issue by ravigneaux-1** [dotnet/roslyn#69056]
_This is kind of a big one and based on a lot of contradictory statements and misunderstandings. Please exercise care when reviewing!_

In the most general sense, the documentation states the following regarding [code-style rules](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/):

> Most of the rules have one or more associated options to customize the preferred style. For example, [Use simple 'using' statement (IDE0063)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0063) has the associated option `csharp_prefer_simple_using_statement` that lets you define whether you prefer a using declaration or a using statement. The rule enforces whichever options you choose at a specified level (for example, warning or error).

This suggests that, for each rule, either the 'original' style or the 'inverted' style can be enforced. This matches with the specification of most options. For example, the option values of [`dotnet_style_prefer_auto_properties`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0032#dotnet_style_prefer_auto_properties) are specified such that value `true` means

> Prefer auto-implemented properties

and value `false` means

> Prefer properties with private backing fields

With this specification, I would assume that an auto property would raise warning `IDE0032` and suggest to convert it to a full property. But that's not the case.

I then found the following, general statement in the documentation of the [option format](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/language-rules#option-format):

> For each language rule, you specify a value that defines if or when to prefer the style. Many rules accept a value of `true` (prefer this style) or `false` (do not prefer this style).

This confirms my finding that you only have the choice to enforce the style a rule targets or not to enforce it. Enforcing the 'inverted' style is not possible. However, in this case, a very large part of the **documentation on code-style rules is incorrect or at least heavily misleading.** There is a **huge** difference between _"Prefer style B (over style A)"_ and _"Do not prefer style A (but also do not prefer style B)"_.

There **is** a handful of rules for which the opposite can be enforced with value `false`, but these are, as far as I can tell, limited to

- paired rules with one for each preference, e.g. [`IDE0007`/`IDE0008`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008) or [`IDE0003`/`IDE0009`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0003-ide0009)
- `{dotnet|csharp}_style_allow_*` rules

For all other rules, combining `false` with a severity greater than `none` does not make sense, then.

I think the documentation should be carefully reviewed. The specification of option values should clearly communicate whether the value `false` only disables all preferences of the rule or truly 'inverts' the preference.

**Comment by Ravigneaux1** [comment]
Could it be possible that options with the `_prefer_` infix can only be disabled but not inverted, and options without this infix let you decide which style to prefer? Can anyone confirm or disprove this?

**Comment by CyrusNajmabadi** [comment]
Think of true/false being on/off.  'on' means you want the ide pushing you to the more modern form. 'off' means you don't want any notifications. 

There's no 'inverse' because all these features are for new language features. So one's code will always start using the older form, and the options are about if you want to move forward or not. 

> For each language rule, you specify a value that defines if or when to prefer the style. Many rules accept a value of true (prefer this style) or false (do not prefer this style).

Right. If it's on, you're saying you'd prefer to move to the new form.  If it's off, you're saying you're fine sticking with your code as is. You do not have a preference for the new style, so the ide should not push you to it. 

"Do not prefer" is not the same as "prefer not to have".

**Comment by Ravigneaux1** [comment]
> "Do not prefer" is not the same as "prefer not to have".

Exactly, if the documentation was phrased _"Do not prefer A"_, I wouldn't make such a fuss 😉 But the documentation of 95% of the options **literally** says _"Prefer B"_ 😅

**Comment by CyrusNajmabadi** [comment]
Closing out as external.  Feel free to file bugs on the docs team.
