### ISSUE TITLE
Tracking issue for VSI test failures

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6906]
Team members - feel free to update this post with updated information as it becomes available.

"CSharpRazor.xml"; // https://github.com/dotnet/roslyn/issues/6851
"BasicWinForms.xml"; // https://github.com/dotnet/roslyn/issues/6988

These failed during a period of general flakiness (async change + machines not disconnected cleanly) so they have yet to be skipped.  If they keep happening, file real bugs and skip them.
(NOTE: This period of general flakiness has ended as of late 11/24. Any failures on 11/25 or later should be investigated.)

"CSharpWebApp.xml"; // [Completion list not showing](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/63/VS_Integration_Test_Logs/CSharpWebApp.html), #6990
"ProjectSystem.xml"; // [Timeout while renaming file](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/63/VS_Integration_Test_Logs/ProjectSystem.html) - screenshot shows crash dialog, #6990
"BasicVenus.xml"; // BasicVenus.xml crashed due to a failed contract assert, #6989

Previously failing, now re-enabled:

"CSharpCodeActions.xml"; // https://github.com/dotnet/roslyn/issues/6838  // Fixed, re-enabled
"CSharpGotoDefinition.xml"; // https://github.com/dotnet/roslyn/issues/6863  // Not Repro, re-enabled
"CSharpInteractiveCommands.xml"; // https://github.com/dotnet/roslyn/issues/6855  // Not Repro, re-enabled
"OptionPagesDTE.xml"; // https://github.com/dotnet/roslyn/issues/6852  // Fixed, re-enabled
"CrossLanguage.xml"; // https://github.com/dotnet/roslyn/issues/6837  // Not Repro, re-enabled

**Comment by dpoeschl** [comment]
See results at https://github.com/dotnet/roslyn-internal/pull/395

**Comment by TyOverby** [comment]
Here's 15 more flaky tests

http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/438/consoleFull#34100711a640ec72-cfe0-4777-bfdf-7cf9a1be54b8

**Comment by brettfo** [comment]
[BasicWinForms.xml also appears to be flaky](http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/56/)

**Comment by Pilchie** [comment]
Let's just have bugs for the individual failing tests at this point.
