### ISSUE TITLE
LSIF generator tool should have some build time performance and reliability quality gate

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#69068]
In introducing a fix for a reoccurrence of #64255, #68750 was introduced. The customer that was blocked by the initial issue is now blocked by the new performance issue.

Since this is a regression and not much has otherwise changed in the LSIF tool, this would seem to suggest that the regression came from elsewhere in Roslyn, and points to a need for at least some trivial performance release quality gates to avoid regressions when accepting changes from various Roslyn contributors that may unknowingly impact the LSIF scenario.

I propose the introduction of a simple CI check that generates LSIF for a portion of the Roslyn code base and ensures that it completes in a reasonable amount of time.

This check can act as a gate for changes to Roslyn code outside of the LSIF generator that may still impact the scenario.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need this then we should have an explicit request for it for a particular milestone/release.  We can then cost and assign accordingly.
