### ISSUE TITLE
No `modreq(In)` emitted for synthesized delegate `Invoke` method

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#69079]
**Steps to Reproduce**:

```cs
var x = (in int p) => { };
```

[SharpLab](https://sharplab.io/#v2:C4LglgNgPgbghgJwAQA8kF4kAowDsl7BIAOAlBgHxIDeSAvgNxA=)

**Expected Behavior**: The synthesized method ```<>A{00000003}`1.Invoke``` has a `modreq(In)` on its parameter since it's virtual and that's the requirement: https://github.com/dotnet/csharplang/blob/b2a21c67233c490e6c9a15d2459d7c0a1b7c043d/proposals/csharp-7.2/readonly-ref.md#metadata-representation-of-in-parameters

**Actual Behavior**: No `modreq` on the parameter:

```
.class private auto ansi sealed '<>A{00000003}`1'<T1>
    extends [System.Runtime]System.MulticastDelegate
{
    .custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
        01 00 00 00
    )
    // Methods
    .method public hidebysig specialname rtspecialname 
        instance void .ctor (
            object 'object',
            native int 'method'
        ) runtime managed 
    {
    } // end of method '<>A{00000003}`1'::.ctor

    .method public hidebysig newslot virtual 
        instance void Invoke (
            [in] !T1& ''
        ) runtime managed 
    {
        .param [1]
            .custom instance void [System.Runtime]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = (
                01 00 00 00
            )
    } // end of method '<>A{00000003}`1'::Invoke

} // end of class <>A{00000003}`1
```

**Comment by jaredpar** [comment]
This is a weird gray area of `modreq`. I noticed this a few years ago and brought it up to @davidwrighton. Essentially it seems like we have delegates pointing to methods which have signatures that differ on `modreq` and the runtime accepted that. I asked when `modreq` matter in this scenario and the response was 

> modreq matter when they matter 😄 

This is a case where they don't seemingly matter and pushing them to be emitted here doesn't seem like it would add any important guard rails (correct me if I'm wrong). I would leave this as is for now.

**Comment by jjonescz** [comment]
> I would leave this as is for now.

I agree, just wanted an issue to put in a comment instead of PROTOTYPE.

**Comment by AlekseyTs** [comment]
I think we should leave this information somewhere. At least as a comment for ```SourceDelegateMethodSymbol```. And probably somewhere in the spec.

**Comment by jaredpar** [comment]
I agree it should be in the spec.

**Comment by jjonescz** [comment]
Added to the proposal where I found it specified: https://github.com/dotnet/csharplang/pull/7366

**Comment by jaredpar** [comment]
Given that the spec now notes this deviation going to close this issue. If we decide to add the `modreq` in future we can re-open.
