### ISSUE TITLE
error MSB4064: The "ReportIVTs" parameter is not supported by the "Csc" task loaded from assembly: Microsoft.Build.Tasks.CodeAnalysis

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69092]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-MSB4064:-The-ReportIVTs-paramete/10413350)._

---
Building .NET Framework library with Microsoft.Net.CompilersToolset or Microsoft.Net.Compilers fails. (It works fine on 17.6 and previous versions)

1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(136,10): error MSB4064: The "ReportIVTs" parameter is not supported by the "Csc" task loaded from assembly: Microsoft.Build.Tasks.CodeAnalysis, Version=4.6.8.25908, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from the path: C:\Users\vinic\.nuget\packages\microsoft.net.compilers.toolset\4.6.0\tasks\net472\Microsoft.Build.Tasks.CodeAnalysis.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(80,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.

---
#### Feedback Bot on 7/12/2023, 01:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jcouv** [comment]
@viniciusjarina The error message reports assembly version 4.6.8.25908, but ReportsIVTs was only added recently, in VS 17.7p3 which would be a 4.7 version. So the error is expected.
I'd recommend you to look at a binary log (build with `-bl` option from the command-line, then use the "structured log viewer" tool to take a look). I'd first try to find where the `ReportIVTs` option was set. If you can't figure it out, could you share a small repro or the binary log?

Tagging @333fred in case he has more ideas

**Comment by viniciusjarina** [comment]
Thank you @333fred and @jcouv 
I fixed the issue updating the header of the `.csproj`. 
Was probably an old `.csproj` with a old format
```diff
- <Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+ <Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```

**Comment by thomasstockermc** [comment]
The solution by @viniciusjarina worked, but the search enginge discoverability of the workaround is very bad, Because google nor bing found this solution. Maybe this should be documented in the reportivts parameter.
