### ISSUE TITLE
Roslyn shows Shared file in Miscellaneous Files project if its name matches one in head project

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#6909]
Roslyn appears to struggle when a shared project and its importing 'head' project both have source files with the same name. I have been unable to repro this in a simple new solution. But here is the reliable repro from the original project that I saw this in.

**Machine configuration**
- VS2015 Update 1
- Xamarin extension installed

Additionally, install a couple extra Android SDKs:
1. Launch the SDK Manager (from start menu) _elevated_
2. Install "SDK Platform Android 2.3.3, API 10, revision 2", and the SDK Platform for API 15.

You may also need a Xamarin license to get the projects to open or build.

**Repro Steps**
1. Execute these commands

```
git clone https://github.com/AArnott/PCLCrypto
cd pclcrypto
git checkout f31b4e44~1
nuget restore src
src\pclcrypto.sln
```
1. In VS, open the SymmetricCryptographicKey.cs file in the PCLCrypto.Android project.

**Expected**
No errors in the error list.

**Actual**
The error list has several entries claiming that the `SymmetricCryptographicKey` class does not implement an interface fully, missing members such as Name, Mode, Padding.
Yet building this project proves there are not actually any build errors.

If you open the PCLCrypto.Shared.PlatformCommon project's SymmetricCryptographicKey.cs file (note it has the same name as the Android project's file you already opened), you'll see in the context switcher dropdown that the shared file is only in the Miscellaneous Files language service project.
If you now rename the file to SymmetricCryptographicKey.Shared.cs, the errors in the error list go away and the context switcher dropdown populates with all the projects that import that file.
[This commit](https://github.com/AArnott/PCLCrypto/commit/f31b4e44e5e0f0987f94d48f9c4fc3fa93e1a9e4) demonstrates this rename so you can sync to it, or just before it, to see the difference it makes to Roslyn's error list.

**Comment by jinujoseph** [comment]
Old issue also @vsccarl validated as not repro in latest build.
