### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#691]
Is it possible to test the individual parts of the compiler in isolation?
* Scanner
* Parser
* Semantic 
* etc
Or Test the compiler in isolation, eg just the VB / C# compiler? 
A the moment it test both compilers and Editor features.
A 2 hour 15 minute test time is not conducive in finding the source of an issue.

**Comment by Pilchie** [comment]
You can manually run xunit.console on any particular assembly.
