### ISSUE TITLE
public API for roslyn features to expose the ability to report progress as they run.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#69111]
## Background and Motivation

Many features in the IDE may involve long running operations.  For example, a 'code action' can take unbounded time as it does its work computing the change to happen.  During this time, the IDE pops up a dialog (potentially embedded right in the source) allowing a user to know something is happening, and giving them:

1. a description of what is going on.
2. progress of the operation (when possible).
3. a way to cancel (esc, or a button).

This works acceptably, but has a major limitation.  Specifically, when we call out to other components (esp. 3rd party ones) there is no ability for those components to give use information to the user as to what's going on.  As such, our features can only give extremely coarse information on what's happening.  

We do have an API to provide more detailed information.  But it is currently internal.  This is problematic for the above reason, and because it bifurcates our API.  Specifically, our API has internal extension points that use this API, and those that do not.  Making things very hard to manage.  This also acts a limiting factor bringing certain features to things like the CodeStyle package (which can only use public APIs from roslyn).

## Proposed API

```diff
/// <summary>
/// Represents the progress of an operation.  Commonly used to update a UI visible to a user when a long running
/// operation is happening.
/// </summary>
public sealed class CodeAnalysisProgress
{
    /// <summary>
    /// Updates the UI showing the progress of the current operation to the specified <paramref name="description"/>.
    /// </summary>
    public static CodeAnalysisProgress Description(string description);

    /// <summary>
    /// By default, indicates that an item of work has transitioned from being incomplete (see <see
    /// cref="AddIncompleteItems"/> to complete.  This is commonly presented with a progress bar. An optional <paramref
    /// name="description"/> can also be provided to update the UI accordingly (see <see cref="Description"/>).
    /// </summary>
    /// <remarks>
    /// Multiple items of work can be transitioned to be complete by passing an explicit value to <paramref
    /// name="count"/>.
    /// </remarks>
    public static CodeAnalysisProgress AddIncompleteItems(int count, string? description = null).

    /// <summary>
    /// Indicates that one item of work has transitioned from being incomplete (see <see cref="AddIncompleteItems"/> to
    /// complete.  This is commonly presented with a progress bar. An optional <paramref name="description"/> can also
    /// be provided to update the UI accordingly (see <see cref="Description"/>).
    /// </summary>
    public static CodeAnalysisProgress CompleteItem(int count = 1, string? description = null);
}

public class CodeAction
{
    public Task<ImmutableArray<CodeActionOperation>> GetOperationsAsync(
        Solution originalSolution, IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);

    protected virtual async Task<ImmutableArray<CodeActionOperation>> GetOperationsCoreAsync(
        Solution originalSolution, IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);

    protected virtual async Task<ImmutableArray<CodeActionOperation>> ComputeOperationsAsync(
            IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);

    protected virtual async Task<Solution?> GetChangedSolutionAsync(IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);

    protected virtual Task<Document> GetChangedDocumentAsync(IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);
}

public class CodeActionWithOptions
{
    public async Task<IEnumerable<CodeActionOperation>?> GetOperationsAsync(
        Solution originalSolution, object? options, IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);

    protected virtual Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, IProgress<CodeAnalysisProgress> progress, CancellationToken cancellationToken);
}
```

**Comment by CyrusNajmabadi** [comment]
PR for this: https://github.com/dotnet/roslyn/pull/50211

**Comment by arkalyanms** [comment]
@333fred would you remind what the process for scheduling an api review would be? do we leave it up with the api ready for review tag and you pick it up in the next available slot?

**Comment by 333fred** [comment]
> do we leave it up with the api ready for review tag and you pick it up in the next available slot?

Precisely. https://github.com/dotnet/roslyn/blob/main/docs/contributing/API%20Review%20Process.md#review-schedule covers this. Note that we did not get quorum last week, so we were unable to look at anything.

**Comment by CyrusNajmabadi** [comment]
Feedback:

Do some more simplification passes on this.  In particular, see if we can remove almost all of the above, and instead just make ComputeOperations take an `IProgress<CodeActionProgress>` instead, and have `CodeActionProgress(int CompletedItems, int TotalItems, string description)`  (with helper constructors to allow specifying partial parts of that data).

**Comment by 333fred** [comment]
### API Review

* What's the namespace?
* Why is `CurrentScope` necessary?
    * We could probably simplify and remove that?
* Why not just pass in `IProgress`?
    * Do we really need have the scoping? You're already in a code action, are there actually finer scopes?
    * We do use it in one place, but we could probably simplify that case.
    * We'll look at simplifying this.
* If we simplify to IProgress, we can simplify the structs as well.
    * CodeActionProgress, not LongRunningActionProgress, etc

**Conclusion**: Will come back with a simplified proposal.

**Comment by 333fred** [comment]
### API Review

* Simplified version after feedback from last time
* `IncompleteItems` -> `AddIncompleteItems`?
    * Confusing as to whether you're adding new items or adjusting the existing incomplete count
* Add description optional parameters to the other methods
* Add optional count of items that were completed
* Would be helpful to have usage examples of how a CodeAction would call the apis

**Conclusion**: A few minor updates to make, but the general shape is looking good.

**Comment by CyrusNajmabadi** [comment]
Approved over email after latest tweaks were sent out.  PR for this is here: https://github.com/dotnet/roslyn/pull/50211
