### ISSUE TITLE
LSIF generator can sometimes write non-LSIF to stdout

### ISSUE THREAD

**Issue by gundermanc** [dotnet/roslyn#69137]

**Comment by gundermanc** [comment]
In some cases the LSIF generator has been observed to emit non-JSON lines, breaking ingestion.

Here's one such example:


![Image](https://github.com/dotnet/roslyn/assets/5387680/8c145e8b-6d1e-4d85-ad6a-b23521fcb533)


It seems to be localized to the https://devdiv.visualstudio.com/DevDiv/_git/Gladstone repo.

I can probably furnish you with the precise LSIF, if needed.

**Comment by CyrusNajmabadi** [comment]
We use stdout at all?  Ick.  Can we switch to always just writing to a file?

**Comment by gundermanc** [comment]
> We use stdout at all? Ick. Can we switch to always just writing to a file?

Yeah absolutely! FWIW I'm currently working on a proposal for additional diagnostics between the tool and its consumers to help collect more actionable information about how it performs.

Writing to file(s) (ideally one per project) is on the list. Lmk what other modifications you have in mind.

**Comment by jasonmalinowski** [comment]
@gundermanc Even if we haven't moved to file writing generally, is this specific problem still causing issues for that repo? The non-LSIF output looks like it might have been output from the SDK discovery, and hopefully newer builds aren't doing that in the LSIF process anymore. stdout is still dangerous, but at least in this case it should be better?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of response.
