### ISSUE TITLE
[BUG] c# dev kit - high memory usage

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#69134]
From vscode-dotnettools created by [romaluca](https://github.com/romaluca): microsoft/vscode-dotnettools#229  

### Describe the Issue

If i open a my solution with 100 projects in Visual Studio 2022, the memory usage is about 1.2GB
If i open the same solution with vs code, the memory usage is about 4GB

**Comment by CyrusNajmabadi** [comment]
Can someone supply their project, so we can try to repro this?

**Comment by arkalyanms** [comment]
Lifeng mentioned a repro with the Roslyn repo - https://github.com/microsoft/vscode-dotnettools/issues/229#issuecomment-1629828535.

cc: @lifengl

**Comment by ivanjx** [comment]
@CyrusNajmabadi https://gitlab.com/ivanjx/home-server/-/tree/fix/refactor

solution wide analysis enabled. memory usage:
![image](https://github.com/dotnet/roslyn/assets/12814796/02ddf56c-8437-4c76-986b-5214ba7a0c27)

**Comment by CyrusNajmabadi** [comment]
Full solution diagnostics are exactly that.  It's analyzing everything.  My recommendation for using less memory would be to change that to only analyze open/active documents.  This should also drop CPU by a bunch.

**Comment by arkalyanms** [comment]
@ivanjx Also, the default should have been set to openFiles and not fullSolution. So this would have needed intervention on your part to move to the solution scope. Let us know if that was not true.

**Comment by ivanjx** [comment]
that project isnt even that big. please try to load it and check.

**Comment by CyrusNajmabadi** [comment]
Should be fixed with https://github.com/dotnet/roslyn/pull/72147

**Comment by ivanjx** [comment]
when can we expect the fix to be released to the dev kit extension? thanks

**Comment by arkalyanms** [comment]
> when can we expect the fix to be released to the dev kit extension? thanks

The first prerelease to pick up the solution crawler removal work referenced will come out this week.

**Comment by AlexeiNaabal** [comment]
We found this memory issue with a rather large project too (roughly 10000+ c# files). Thus I wrote a simple file generator to span c# files then feed the generated files to vscode and see if it takes huge amount of memory, my test result is YES (and it takes around 10GB FYI).

For anyone interesting about this topic, you can use the program below to generate files and test. 
All generated classes are rather simple with only some primitive fields, properties, and some simple function members, I don't know if it is normal for roslyn to occupy such amount of memory to analyze these files. 

Also this behavior seems consistent with the roslyn in Visual Studio 2022, I can see quite a number of *Symbol instances from both the dotnet-trace's dump of roslyn in vscode c# dev kit and the process dump of rosyln in Visual Studio

```c#
namespace garbage_generator;

class Program
{
    public enum FieldOrProp{
        Field,
        Property
    }
    static string[] primitiveTypes = { "bool", "byte", "sbyte", "char", "decimal", "double", "float", "int", "uint", "long", "ulong", "short", "ushort" };
    static Random random = new Random();
    static string PrimitiveRoller(){
        int index = random.Next(primitiveTypes.Length);
        string primitiveType = primitiveTypes[index];
        return primitiveType;
    }
    static FieldOrProp FieldOrPropertyRoller(){
        int roll = random.Next(5);
        return roll < 3 ? FieldOrProp.Field : FieldOrProp.Property;
    }
    static void Main(string[] args)
    {
        const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        string directoryPath = @"E:\CSharpGarbage\GarbageReceiver\garbages"; // Change this to the directory where you want to generate the files
        int numFiles = 10000;

        if (!Directory.Exists(directoryPath))
        {
            Directory.CreateDirectory(directoryPath);
        }

        for (int i = 1; i <= numFiles; i++)
        {
            string fileName = $"file_{i}.cs";
            string filePath = Path.Combine(directoryPath, fileName);

            using (StreamWriter writer = new StreamWriter(filePath))
            {
                writer.WriteLine("namespace GarbageReceiver;");
                writer.WriteLine($"public class class_{i}");
                writer.WriteLine("{");
                for(int f = 0;f < 5;++f){
                    string primitiveType = PrimitiveRoller();
                    FieldOrProp fp = FieldOrPropertyRoller();
                    switch(fp){
                        case FieldOrProp.Field:
                            writer.WriteLine($"\tpublic {primitiveType} class_{i}_field_{f};");
                            break;
                        case FieldOrProp.Property:
                            writer.WriteLine($"\tpublic {primitiveType} class_{i}_prop_{f} {{ get; set; }}");
                            break;
                    }
                }
                for(int f = 0;f < 5;++f){
                    string primitiveType = PrimitiveRoller();
                    string functionName = $"class_{i}_func_{f}";
                    writer.WriteLine($"\tpublic {primitiveType} {functionName}()");
                    writer.WriteLine("\t{");
                    writer.WriteLine($"\t\treturn default({primitiveType});");
                    writer.WriteLine("\t}");
                }
                writer.WriteLine("}");

                if(i <= 511){
                    writer.WriteLine();
                    writer.WriteLine($"public class class_{i}_tempView");
                    writer.WriteLine("{");
                    writer.WriteLine("\tpublic static Dictionary<int, string> literals = new Dictionary<int, string>()");
                    writer.WriteLine("\t{");
                    int literalNum = random.Next(1, 100);
                    for(int l = 0;l < literalNum;++l){
                        int length = random.Next(10, 200);
                        string content = new string(Enumerable.Repeat(chars, length)
                            .Select(s => s[random.Next(s.Length)]).ToArray());
                        writer.WriteLine($"\t\t[{l}] = \"{content}\",");
                    }
                    writer.WriteLine("\t};");
                    writer.WriteLine("}");

                }
            }
        }

        // Literal string test for roslyn, just for check if literal string have any compact for roslyn
        // string literalPath = Path.Combine(directoryPath, "literals.cs");
        // using(StreamWriter writer = new StreamWriter(literalPath)){
        //     writer.WriteLine("namespace GarbageReceiver;");
        //     writer.WriteLine($"public class literals");
        //     writer.WriteLine("{");
        //     for(int i = 0;i < 10000;++i){
        //         int length = random.Next(10, 201);
        //         const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        //         string content = new string(Enumerable.Repeat(chars, length)
        //             .Select(s => s[random.Next(s.Length)]).ToArray());
        //         writer.WriteLine($"\tpublic static string str_{i} \"{content}\";");
        //     }
        //     writer.WriteLine("}");
        // }

        Console.WriteLine($"Generated {numFiles} files in {directoryPath}");
    }
}

```

**Comment by CyrusNajmabadi** [comment]
10000 files in a single project would be considered 'very very large'.  As a point of comparison, Roslyn.sln itself (which is very very large) has 230 projects, but 15k files.   So this is about 150x larger than Roslyn itself is on average per project.

**Comment by AlexeiNaabal** [comment]
Yes but that's what we are facing now (These 10000+ scripts are separated between only 9 projects and 1 of them is such 'very very large' one). 
Would it help reducing memory usage if we reconstruct that project, adding more sub projects to separate these script?

**Comment by CyrusNajmabadi** [comment]
can't hurt to try.  def don't have on 'full solution analysis' either.

**Comment by CyrusNajmabadi** [comment]
Can i ask why you have 10000 scripts?  And almost 10k scripts in just one project?

**Comment by AlexeiNaabal** [comment]
> Can i ask why you have 10000 scripts? And almost 10k scripts in just one project?

Out team is developing a C# scripting layer for Unreal Engine (only mono framework FTM), aiming to unify all client and server code as C#. The barebone project boilerplate struct of our solution is like, few project for Mono side work, a project for UnrealEngine side work, a project for UnrealEngine scripting work, plus few other supporting project. Thus all scripting code goes to the only scripting work project.

So, there is a project that we coop, as they adding more feature to their project, the codebase gradually grow to be like such 'very very large'.

**Comment by CyrusNajmabadi** [comment]
Can you aggregate your scripts into different functionality components?  Having 10k be in one single project likely makes you the largest single project of all VS users globally :)

**Comment by AlexeiNaabal** [comment]
> Can you aggregate your scripts into different functionality components? Having 10k be in one single project likely makes you the largest single project of all VS users globally :)
> 
> Note: having this take 10gb seems totally reasonable given just how massive your codebase is. I would expect with such an enormous project, you'd be running this on beefy hardware that could scale up to handle it.

Thank you for your inspiration advise. I am communicating with my leader to test if this is the root issue of our memory problem and if it is applicable to aggregate the scripts to different projects.
