### ISSUE TITLE
Unable to build/restore the tree, when the current user has spaces in the name

### ISSUE THREAD

**Issue by asvishnyakov** [dotnet/roslyn#6913]
When I try to build Roslyn on my computer, I get some errors like
`'C:\Users\Aleksandr' is not recognized as an internal or external command,`
`10>  operable program or batch file.`
`10>D:\Roslyn\src\ExpressionEvaluator\Core\Source\Concord\Concord.csproj(48,5): error MSB3073:`
`The command "C:\Users\Aleksandr Vishnyakov\.nuget\packages\FakeSign\0.9.2\tools\FakeSign.exe`
`"D:\Roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll"" exited with code 9009.`

If I start Restore.cmd I'm also get this error:
`For switch syntax, type "MSBuild /help"`
`MSBUILD : error MSB1008: Only one project can be specified.`
`Switch: Vishnyakov\AppData\Local\Temp\tmpCBF5.tmp``

**Comment by davkean** [comment]
Can you try sync'ing to latest in master? I cannot repro this, and it looks like the first issue is at least fixed. Not sure where the second one is failing.

**Comment by davkean** [comment]
Yeah, it looks like it was fixed in 5385f8f7 by @robinsedlaczek.

**Comment by davkean** [comment]
Please open another bug if you can still repro this after sync'ing to latest.
