### ISSUE TITLE
Report diagnostic for collection expression with collection initializer target type where Add() returns a value

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#69136]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/c5ec55bb1fdd7f2bc7c88db0e93bb9c93a81b91e

**Steps to Reproduce**:
Compile and run:

```csharp
using System.Collections.Immutable;

ImmutableArray<int> a = [1, 2, 3];
```

**Expected Behavior**:
Compiler warning or error that `ImmutableArray<int>.Add(int)` returns a value which might indicate the collection type is immutable.

**Actual Behavior**:
No compiler diagnostics; `NullReferenceException` in `ImmutableArray<int>.Add(int)` at runtime.

Relates to test plan https://github.com/dotnet/roslyn/issues/66418 (collection expressions)

**Comment by cston** [comment]
If we report a similar diagnostic for classic *collection initializer expressions* as well, the diagnostic may need to be a *warning wave* warning since it is a breaking change.

```csharp
using System.Collections.Immutable;

ImmutableArray<int> a = new() { 1, 2, 3 }; // warning?
```

**Comment by CyrusNajmabadi** [comment]
Note: Add returns a value for HashSet. 

Perhaps only if the return value is the same type as the instance?

**Comment by alrz** [comment]
> Perhaps only if the return value is the same type as the instance?

That could be a fluent-friendly API just to chain Add methods.

I think itd make sense if void  was a requirement here, at least for collection literals. Anything like HashSet would need to use custom create methods or something similar.

**Comment by CyrusNajmabadi** [comment]
It's a strong principle that a type that works correctly with collection initializers should just work with collection expressions.

**Comment by CyrusNajmabadi** [comment]
>      That could be a fluent-friendly API just to chain Add methods.

I'm unfamiliar with any apis that work like that. I'm not saying they don't exist, just that I don't know if any. Can you point me at any?  It would be useful for seeing what sorts of patterns already exist. 

Note: I'm also ok with this warning being just out of Roslyn-analyzers

**Comment by alrz** [comment]
> It would be useful for seeing what sorts of patterns already exist.

I mean it's just a convenient choice to return `this`, it doesn't indicate whether or not the method is mutating or anything.. actually that could be the reason the return type is ignored in the fisrt place. 

Definitely agree on this being an analyzer, imo faulty usage patterns could get too narrow for a compiler warning.

**Comment by jnm2** [comment]
If it helps, it could start out being limited to types implementing `System.Collections.Immutable.IImmutableXyz` interfaces.

**Comment by RikkiGibson** [comment]
To reiterate my thoughts in #70351, I would feel most comfortable with special-casing ImmutableArray to begin with. I want to enable this warning by default in the platform, so I would want to have 99.5% confidence that the warning we are giving is really catching buggy user code. Not just usage of a user collection type where they decided to have a fluent `Add`.

**Comment by jnm2** [comment]
> I would want to figure out what can downlevel users do, including ourselves, to actually make ImmutableArray usable with collection-expressions.

We're using collection expressions in ImmutableArray downlevel by referencing the System.Collections.Immutable 8.0.0 NuGet package.
