### ISSUE TITLE
Error when using collection-expression for an array-typed attribute argument.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#69133]
```c#
    [X([1, 2, 3])]
    class C
    {
    }

    public class XAttribute : System.Attribute
    {
        public XAttribute(int[] values) { }
    }
```

Error: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type	

This is expected to work, just like with a normal argument.  An attribute argument should support target-typing.  After all, you can pass `null` to the argument, and that is totally fine.  

Relates to test plan https://github.com/dotnet/roslyn/issues/66418

**Comment by RikkiGibson** [comment]
Associated PR was merged so closing this out.
