### ISSUE TITLE
Clarify Interceptors documentation

### ISSUE THREAD

**Issue by b-straub** [dotnet/roslyn#69140]
Example from

https://github.com/dotnet/roslyn/blob/d974dd17343584263625c6fd12d4d3452df44132/docs/features/interceptors.md?plain=1#L130

```cs
using System.Runtime.CompilerServices;

class C
{
    public static void InterceptableMethod<T1>(T1 t) => throw null!;
}

static class Program
{
    public static void M<T2>(T2 t)
    {
        C.InterceptableMethod(t);
    }
}

static class D
{
    [InterceptsLocation("Program.cs", 12, 11)]
    public static void Interceptor1<T2>(T2 t) => throw null!;
}
```

Fails with CS9138. Please clarify the documentation.

**Comment by RikkiGibson** [comment]
`CS9138` is `ERR_InterceptorContainingTypeCannotBeGeneric`. No generic types are involved in this scenario, so it's possible we had a bug here which was later fixed.

The issue description appears to be based on test `InterceptorsTests.InterceptableGeneric_05`, which is working as expected.

I also popped open a new console app with the 8.0.300 SDK, pasted in this scenario with appropriate edits, and things worked as expected.

Will close as no-repro. Feel free to follow up if there are further questions/concerns.
