### ISSUE TITLE
ref struct with ref field

### ISSUE THREAD

**Issue by vzabavnov** [dotnet/roslyn#69148]
I found unexpected behavior with using ref field inside ref struct. I am not sure this is a bug, but the result was not expected.
```c#
public ref struct TheStruct
{
    public ref int TheValue;

    public TheStruct(ref int value) => TheValue = ref value;

    public TheStruct() => TheValue = 0;

    public void Change(int newValue) => TheValue = newValue;
}
```
the test scenario with XUnit:
```c#
var theValue = 38;

var instance = new TheStruct(ref theValue);
Assert.Equal(38, instance.TheValue);

instance.Change(66);
Assert.Equal(66, instance.TheValue);
Assert.Equal(66, theValue);

// set another value 
theValue = 56;
//create new instance but apply to the same variable
instance = new TheStruct();
// what value we should expect here:
Assert.Equal(56, theValue);
```
the last assert failed, `theValue` has **0** value. 
I understand why it happened. but should expect some warning to use such construct or something. at least mention in documentation explanation of such behavior.

**Comment by ufcpp** [comment]
Is a NullReferenceException thrown before the last assert?

**Comment by vzabavnov** [comment]
No exceptions. the ref field keeps previous value.

**Comment by ufcpp** [comment]
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQIPYBsUBoYgCWWAPgAIBMAjALABQ9AblAgAQwAWEAalFnBFYBeVgGYAHAG56TFq0IA7ZDCgKAxoJEKIAd1YAVLgGUYCOGpgAKJGHZde/CAEppdMlQCclxctUaAdIY8fAIuMnQ+KuoQ/gDCHKoA5hCWAGypYW6e3kpRAUEOoa7uXpzBjpn0APRVrMgQMKyqGGVszI6s9GWFmqwArKmuNWpIsILaepF+gsBwjVAADgtYAJ7sGHaCyFAAtoLMCIRQwDj0U9HCrBMGxqbmVpk1rDoJje0Cz1scGHBYACasCAADwWEAsrC4SBA9BKlm6IWcrhholYNjqd3BQRMZgs9AA3vRWETWGQUWjFI0CgikXRiSSUViMVZyQo3ginMIAHw3cofERo94QGl00k87H3SwcoTcqkdEQABmFxNFZAALKx4kkUhSrroelKZfYEZcJj1XABfIA=

Surely TheStruct::.ctor seems to be called for the previous instance.

```
        IL_0035: ldloca.s 1
        IL_0037: call instance void TheStruct::.ctor()
```

In the following code, I believe that TheValue should be initialied to NullRef, but that is skipped. It looks like a bug in the [auto-default structs](https://github.com/dotnet/csharplang/issues/5737).

```cs
    public TheStruct() => TheValue = 0;
```

**Comment by RikkiGibson** [comment]
Expected behavior is for `public TheStruct() => TheValue = 0;` to throw `NullReferenceException` when it is called.
