### ISSUE TITLE
Suppress IDE0044/IDE0051 for [InlineArray] types

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#69143]
.NET 8 introduces the new InlineArrayAttribute, which is put onto a type to indicate that its sole field should be replicated the specified number of times.  C# then provides automatic helpers for indexing into these types and getting at their data as spans.  As a result, the field declared inside the type isn't actually referenced by the developer, and so various analyzers that warn about that end up firing false positives, e.g. IDE0044 "Add readonly modifier" and IDE0051 "Remove unused private members".  Such analyzers should skip types marked as InlineArrayAttribute.

**Comment by anthonymastreanvae** [comment]
I have the hardest time figuring out which version of the SDK (or package) ships the fix... any hints?
