### ISSUE TITLE
IDE C# "quick action" code generation deletes semicolon after block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69153]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE-C-quick-action-code-generation-de/10420472)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Version 17.6.4]
This is a new regression in vs2022 17.6.5.

In the C# IDE editor, when an optional (but permissable) semicolon is placed after a `class`, `enum`, or `struct` code block, it will be deleted, along with an extra blank line, if any of the "code generation" quick actions are applied within that code block.

**REPRO:**

```
class Class1
{

};

class Class2
{

};

```
Notice that there are semicolons after each class block, which is allowed (and optional) in C#.

Next, type the word `override` inside the body of `Class1`, and select any method to automatically implement. Alternatively, you can use the blue paintbrush icon in the left margin to trigger any "code generation" action, such as a constructor, or a code generation action for any other type of member.

**RESULT:**

```
class Class1
{
	public override int GetHashCode()
	{
		return base. GetHashCode();
	}
}
class Class2
{

};
```

Notice that the semicolon after the `Class1` code block has been removed, as well as the extra blank line that was present.

**EXPECTED:**

The generate code "quick actions" should not remove unrelated tokens. I believe that this did not happen in a previous and recent version of Visual Studio 2022.

---
#### Feedback Bot on 7/21/2023, 02:17 AM: 

(private comment, text removed)
#### Glenn Slayden on 7/21/2023, 02:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Wacky, we actually have code that explicitly does this:

```c#
            if (typeDeclaration.SemicolonToken.IsKind(SyntaxKind.SemicolonToken))
            {
                typeDeclaration = typeDeclaration.WithSemicolonToken(default).WithTrailingTrivia(typeDeclaration.SemicolonToken.TrailingTrivia);
            }
```

Removing to see what breaks.

**Comment by sharwell** [comment]
@CyrusNajmabadi I assume you mean this:
https://github.com/dotnet/roslyn/blob/e6f9a9cd213bddbb35626e868d139289719e32a5/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/TypeDeclarationSyntaxExtensions.cs#L112-L118

I think the solution here is to only remove the `;` if the braces weren't _already_ present. If the type declaration already has braces, this method should NOP.

**Comment by glenn-slayden** [comment]
Ping -- I am the original author of the issue.

**Comment by CyrusNajmabadi** [comment]
Hi @glenn-slayden   thanks for reporting this. We checked in the fix for this half an hour ago. Thanks!
