### ISSUE TITLE
autocomplete trashing variable names

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69154]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/autocomplete-trashing-variable-names/10420153)._

---
The auto complete is constantly providing code suggestions.
This generally works fine, except when I am trying to type in a variable name.
![image.png](https://aka.ms/dc/image?name=B70257f946ac84bad884424e092ae8c2f638254893086839904_20230720-153455-image.png&tid=70257f946ac84bad884424e092ae8c2f638254893086839904)
in the attached screen shot, I am typing in "activ" in lower case.
the code suggestions come up with a list like "Activator, etc."; however, there seems to be no way to Ignore the code suggestions.
I tried right arrow and tab, both of which select an item off the list.

In order to enter a new variable name, I have to use the Mouse, which gets ride of the auto complete list.

maybe there is a keyboard short cut to skip selecting an auto complete item; but I havent found it.

What I would like is
1 - if the typed code begins with lower case or _ then dont automatically select an autocomplete item
2 - if the user does right arrow then close the autocomplete list and dont automatically select an item.

---
#### Feedback Bot on 7/20/2023, 08:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
