### ISSUE TITLE
ref struct: uninitialized ref field and no way to initialize it.

### ISSUE THREAD

**Issue by vzabavnov** [dotnet/roslyn#69151]
Have a ref struct:
```C#
public ref struct TheStruct
{
    public ref int TheValue;
}
```
no compile time errors or warning. 'The Value' initialized to its default value `null`.
Any access to this field gives [NullReferenceException](https://learn.microsoft.com/en-us/dotnet/api/system.nullreferenceexception?view=net-7.0), and that expected. But no way to initialize this field **anyhow**.  
```C#
 Assert.Throws<NullReferenceException>(() =>
 {
     var theValue = 38;
     var instance = new TheStruct
     {
          TheValue = theValue
      };
});
```
```C#
var theValue = 38;
var instance = new TheStruct();
//  Error CS8374: Cannot ref-assign 'theValue' to 'TheValue' because 'theValue' has a narrower escape scope than 'TheValue'. 
instance.TheValue = ref theValue;
```

**Comment by huoyaoyuan** [comment]
How about moving declaration of `theValue` after `theStruct`?

**Comment by vzabavnov** [comment]
Only way to initialize the ref field - via constructor. should be some other way, otherwise this kind of construct useless in the language.

**Comment by huoyaoyuan** [comment]
```csharp
            int theValue = 0;

            {
                var instance = new TheStruct
                {
                    TheValue = ref theValue
                };
            }
```

This is totally valid. Also tried this and the compiler allows:

```csharp
        static void Main(string[] args)
        {
            int theValue = 0;

            var instance = new TheStruct
            {
                TheValue = ref theValue
            };
        }
```

**Comment by vzabavnov** [comment]
Agreed, it still kind of "construction", mean initialization. 
Still thing this construct need to mention somewhere in documentation related to ref struct and ref fields in it.
but for assignment - the construction value from semantic point: both TheStructand  and theValue have the same time line.
another example for the same error:
```C#
public ref struct TheStruct
{
    public ref int TheValue;
    public int TheValue1;
    public int TheValue2;

    public TheStruct()
    {
// Error CS8374: Cannot ref-assign 'TheValue2' to 'TheValue' because 'TheValue1' has a narrower escape scope than 'TheValue'
        TheValue = ref TheValue1;
    }

    public void Assign()
    {
// Error CS8374: Cannot ref-assign 'TheValue2' to 'TheValue' because 'TheValue2' has a narrower escape scope than 'TheValue'
        TheValue = ref TheValue2;
    }
}
```

**Comment by CyrusNajmabadi** [comment]
This makes sense to me, the ref may be from a higher stack level. And if you pointed out at a member in this struct that could then be an outer ref pointing into a lower stack frame.  When the lower frame pops, the outer ref wound point at invalid data.

**Comment by vzabavnov** [comment]
Well, from my point of view, this one have the same stack frame:
```C#
var theValue = 38;
var instance = new TheStruct
{
   TheValue = ref theValue
};
```
but here we do not have an error.

**Comment by CyrusNajmabadi** [comment]
Right. They have the same scope.

**Comment by vzabavnov** [comment]
but what is difference when fields are part of the same struct, like example with errors I mentioned? it should not be errors there.

**Comment by CyrusNajmabadi** [comment]
The ref may be from outside the current stack frame. So updating it to point within the current stack frame could lead to it pointing to data that doesn't exist after the stack frame pops. In one case the compiler can see what the reference is to, and so it can see it is safe (because both the ref and the data are to the same frame).  But in the other case the compiler has no idea, so it just conservatively assume the worst.

**Comment by CyrusNajmabadi** [comment]
Here's another way to think about.  Say you had:

```c#
class C
{
    void M(ref int x)
    {
        var s = new TheStruct { TheValue = ref x };
        s.Assign();
    }
}
```

Now, the 's' variable has a ref-field inside of it, pointing to something higher up in the stack.   If `Assign` were allowed, it would now allow the caller of 'M' to end up pointing at a ref to inside the 'M' method, which would obviously be *very bad* :)
