### ISSUE TITLE
Finish PublicSign support

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#6915]
Two things

* [x] Plumb through host object for MSBuild support
* [x] Add cmd line support for VB (backend is shared, so nothing special should have to be done for VB there)
* [X] Property page support is tracked by #6945

**Comment by Pilchie** [comment]
Don't forget IDE property page support, though maybe we should just generalize #5285 for portable-pdb, /feature and this.

**Comment by agocke** [comment]
@Pilchie Yes, I'd prefer to split that out. I don't know if #5285 is the right place to do this, but I'd rather not do it in this bug.

**Comment by jaredpar** [comment]
@Pilchie I filed #6945 to track the complete set options we may need for property pages.

**Comment by agocke** [comment]
This issue is complete.
