### ISSUE TITLE
AnalyzeDataFlow reports captured primary ctor parameters in lambdas that do not capture any

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#69152]
`semanticModel.AnalyzeDataFlow(node).Captured` with `node` being the expression body of the lambda (i.e. `2` in the code below) reports `x` as captured.

`x` is however only captured by `F`, not by the lambda.

```C#
using System;

class C(int x)
{
    void F()
    {
        var f = new Func<int, int>(a => 2);
        var y = x;
    }
}
```

The documentation of `DataFlowAnalysis.Captured` also needs some updating:

```
/// <summary>
/// The set of the local variables that have been referenced in anonymous
/// functions within a region and therefore must be moved to a field of a frame class.
/// </summary>
public abstract ImmutableArray<ISymbol> Captured { get; }
```

**Comment by jjonescz** [comment]
It looks like the `Captured` property doesn't really care what's visible inside the lambda and this is not related to primary constructor parameters. For example, the node `2` below also reports `x` as captured even though it's captured in another lambda:

```cs
[Fact, WorkItem("https://github.com/dotnet/roslyn/issues/69152")]
public void SemanticModel_AnalyzeDataFlow_02()
{
    var source = """
        using System;
        class C
        {
            void F()
            {
                int x = 5;
                var f1 = new Func<int, int>(a => 2);
                var f2 = new Func<int, int>(a => x);
                var y = x;
            }
        }
        """;
    var comp = CreateCompilation(source);
    var tree = comp.SyntaxTrees.Single();
    var literal = tree.GetRoot().DescendantNodes().OfType<LiteralExpressionSyntax>()
        .Single(e => e.ToString() == "2");
    var model = comp.GetSemanticModel(tree);
    var dataFlow = model.AnalyzeDataFlow(literal);
    Assert.Equal(new[] { "System.Int32 x" }, dataFlow.Captured.Select(s => s.ToTestDisplayString()));
}
```

**Comment by tmat** [comment]
@jjonescz That seems contrary to the documentation. Note "Analyze data-flow *within a part* of a method body" and "The set of the local variables ... *within a region*", respectively.

```C#
/// <summary>
/// Analyze data-flow within a part of a method body.
/// note (for C#): ConstructorInitializerSyntax and PrimaryConstructorBaseTypeSyntax are treated by this API as regular statements
/// </summary>
public static DataFlowAnalysis AnalyzeDataFlow(this SemanticModel semanticModel, SyntaxNode statementOrExpression)
```

```C#
 /// <summary>
 /// The set of the local variables that have been referenced in anonymous
 /// functions within a region and therefore must be moved to a field of a frame class.
 /// </summary>
public abstract ImmutableArray<ISymbol> Captured { get; }
```

**Comment by jjonescz** [comment]
> Would `CapturedInside` be the right API to use instead?

Yes, that seems like the correct API.

Looks like `Captured` is the union of `CapturedInside` and `CapturedOutside`:

https://github.com/dotnet/roslyn/blob/5b73439b70c5c5263b5acbb69b426c0264f14af5/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs#L722-L734

Will update the doc comment.

**Comment by jjonescz** [comment]
@CyrusNajmabadi I'm not sure what's the bug. What would you want these APIs to behave like? Currently, `CapturedInside` returns the variables captured inside the region; `CapturedOutside` returns the variables captured in the method but outside the region; `Captured` returns all variables captured inside the method.
