### ISSUE TITLE
`PENamedTypeSymbol` should override `GetMembersUnordered` with an efficient implementation

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69169]
I think this one also could be part of the performance issue I'm seeing. C#'s `PENamedTypeSymbol` (unlike VB) doesn't override `GetMembersUnordered`, defaulting to a slow implementation of `GetMembers`.

**Comment by Youssef1313** [comment]
cc @jcouv @cston @sharwell

**Comment by jcouv** [comment]
Looking at the code for `PENamedTypeSymbol.GetMembers`, I'm not seeing what work could be avoided by a specialized implementation of `GetMembersUnordered`. It just loads the members, so it's not clear what is "inefficient".

**Comment by Youssef1313** [comment]
@jcouv There is a sort operation done:

```
                // Sort the types based on row id.
                members.Sort(membersCount, DeclarationOrderTypeSymbolComparer.Instance);
```

**Comment by CyrusNajmabadi** [comment]
is there a trace showing that Sort is a substantive portion of the cost?  Thanks!

**Comment by Youssef1313** [comment]
Nope, this was just a thought.

**Comment by jcouv** [comment]
Thanks for clarifying. The cost of sorting would likely be cheap compared to the cost of decoding metadata and creating symbols.
I'll go ahead and close for now (seems too speculative). Please re-open if measurements support this proposed optimization
