### ISSUE TITLE
Severity configuration is confusing

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/roslyn#69176]
Hi!

Created this in response to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3679.
I don't know if this is actually related to Roslyn or Visual Studio, so I start here.

When configuring analyzers via the .editorconfig view in Visual Studio, the available severities are Disabled, Suggestion, Warning and Error. If I select Disabled, then "silent" is written to the .editorconfig file. I think that this is very unfortunate since this means that code fixes are still shown and users get confused (as in "but I already disabled this!!"). Isn't it very rare to actually want "silent"? I feel it would be better if users could set "none" via the .editorconfig view, either by treating Disabled as "none" or showing both None and Silent, like when configuring severity via the quick fix context menu.

Tested with Visual Studio 17.6.5.

**Comment by mavasani** [comment]
Working on this..

**Comment by bjornhellander** [comment]
Excellent!

**Comment by bjornhellander** [comment]
Thank you!
