### ISSUE TITLE
"Implement through" isn't available for primary constructor parameters

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#69177]
**Version Used**: Visual Studio 2022, Version 17.7.0 Preview 4.0

"Implement interface through" & "implement abstract class through" code fixes aren't available for primary constructor parameters, e.g. "implement through 'stream'" is available here:
```c#
class StreamWrapper : Stream
{
    private readonly Stream stream;

    public StreamWrapper(Stream stream)
    {
        this.stream = stream;
    }
}
```
but not here:
```c#
class StreamWrapper(Stream stream) : Stream
{
}
```

**Comment by CyrusNajmabadi** [comment]
Would take a reasonably scoped and sized community pr here.
