### ISSUE TITLE
Add an option to disable Preview Changes dialog for FixAll command

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#69180]
Currently, we always show the `Preview Changes` dialog on invoking a FixAll command. We have received requests to add an option to allow skipping this dialog. We can either add a user facing option in Tools Option OR add support to do it via some backdoor setting.

![MicrosoftTeams-image](https://github.com/dotnet/roslyn/assets/10605811/55801df2-3d1b-4e19-908a-800cd5624d44)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We are not investing in preview chnages scenarios.
