### ISSUE TITLE
Compiler emits incorrect sequence point in Release builds

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#69188]
**Version Used**: 

Version 17.8.0 Preview 1.0 [33919.582.main]

**Steps to Reproduce**:

Test:

```C#
        [Fact]
        public void Release()
        {
            var source = @"
class C
{
    public void F()
    {
        object c1 = new object();
        object c2 = new object();
        G(c1, c2);
    }

    public static int G(object o1, object o2) => 1;
}
";
            var v = CompileAndVerify(source, options: TestOptions.ReleaseDll);

            v.VerifyMethodBody("C.F", @"
{
  // Code size       19 (0x13)
  .maxstack  2
  .locals init (object V_0) //c2
  // sequence point: object c1 = new object();
  IL_0000:  newobj     ""object..ctor()""
  // sequence point: object c2 = new object();
  IL_0005:  newobj     ""object..ctor()""
  IL_000a:  stloc.0
  // sequence point: G(c1, c2);
  IL_000b:  ldloc.0
  IL_000c:  call       ""int C.G(object, object)""
  IL_0011:  pop
  // sequence point: }
  IL_0012:  ret
}
");
        }
```

The evaluation stack is not empty at IL offsets 0c5 and 0xb, where sequences points `object c2 = new object();` and `G(c1, c2);` are placed.

Seems like `c1` is optimized to eval stack, which causes subsequent sequence points to be placed on non-empty eval stack.

It's not clear to me why `c1` is optimized but `c2` isn't. If the optimization is desirable, then we should skip the subsequent sequence points that don't have empty eval stack.

**Comment by delmyers** [comment]
As an author of diagnostics tools, I would prefer that variables not be optimized out at the IL level, personally, since it improves our ability to give people information at debug time in certain scenarios. Just my two cents.

**Comment by jcouv** [comment]
@tmat Just to clarify, are you saying that sequence points should only be placed where the eval stack is empty? 
If so, what is the rationale for that invariant?

**Comment by tmat** [comment]
@jcouv That's correct. That requirement has always been in the runtime for PDB sequence points.

**Comment by jcouv** [comment]
@tmat Thanks for the clarification. Do we honor this requirement in switch expressions? (those emit some fancy expression-level sequence points)

**Comment by tmat** [comment]
Yes, we do honor it in debug builds. The only problem is some optimizations in release builds.

IIRC, switch expressions use stack spilling in order to allow sequence points to be placed.

**Comment by jcouv** [comment]
@tmat One more question to help triage/prioritize this issue. What is the impact when the requirement is not met?

**Comment by delmyers** [comment]
@jcouv For some background, the CLR has a concept of "implicit sequence points" which are used to map IL code to jitted native code. When the implicit sequence points and the PDB sequence points don't match, things get a little weird.

**Comment by delmyers** [comment]
So, unfortunately, it is difficult to come up with simple examples, but I have a shortish one here. This one has multiple problems:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;

class Program
{
    static void Main()
    {
        new Test().Run();
    }
}

class Test
{
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public void Run()
    {
        GenericMagic<int>(3, null);
        GenericMagic<Sky>(new Sky(), null);
        GenericMagic<Month>(Month.January, null);

        int @int = GenericSomething<int>();
        Sky @sky = GenericSomething<Sky>();

        GenericClass<int> genericInt = new GenericClass<int>();
        GenericClass<Sky> genericSky = new GenericClass<Sky>();

        genericInt.SetSecret(@int);
        genericSky.SetSecret(@sky);

        genericInt.SayHi();
        genericSky.SayHi();

        GenericClassWithInner<int> genericClassWithInnerInt = new GenericClassWithInner<int>(@int);
        GenericClassWithInner<Sky> genericClassWithInnerSky = new GenericClassWithInner<Sky>(@sky);

        genericClassWithInnerInt.PropertyHashCode();
        genericClassWithInnerSky.PropertyHashCode();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void GenericMagic<T>(T firstArgument, List<T> secondArgument)
    {

    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    T GenericSomething<T>()
    {
        return default;
    }
}

class GenericClass<T>
{
    private T m_secret = default;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void SetSecret(T t)
    {
        m_secret = t;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void SayHi()
    {
        /* hi~ */
    }
}

class GenericClassWithInner<T>
{
    class HashCodeCreator
    {
        readonly object _property;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public HashCodeCreator(object o)
        {
            _property = o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode()
        {
            return _property.GetHashCode();
        }
    }

    public T Property { get; }
    readonly HashCodeCreator _innerClass;

    public GenericClassWithInner(T value)
    {
        _innerClass = new HashCodeCreator(value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int PropertyHashCode()
    {
        return _innerClass.GetHashCode();
    }
}

class Sky
{
    private const int stars = 0;
}

enum Month
{
    January = 0
}
```

This code has several problems with it.

1) You cannot set a breakpoint on line 29 (` GenericClass<int> genericInt = new GenericClass<int>();`)
2) You cannot set a breakpoint on line 39 (`genericClassWithInnerInt.PropertyHashCode();`)
3) You cannot step to either of these lines. The debugger just skips over them.

**Comment by delmyers** [comment]
There are several rules that the jitter has for inferring sequence points from IL code. I believe these are them, but @tommcdon, @AndyAyersMS, you would be the best authorities on this.

1) Method entry
2) Method exit
3) After call/new instructions
4) When the evaluation stack is empty
5) noop instructions.

What I would like to see is a world in which the Roslyn compiler followed the same rules as the jitter.

**Comment by delmyers** [comment]
I would like to understand why there are sequence points at 0x35 and 0x62 according to Roslyn. Are they being triggered by the fact that there was a call, but they are coming late? Or is it because the compiler thinks that the evaluation stack is empty and is making a mistake here?

If it is the second, then I would _not_ like to simply fix that bug, removing sequence points where the evaluation stack is not empty would result in fewer sequence points, and a _more_ degraded debugging experience. If they are triggered by the fact that a call is made, then it seems that something in the logic has to be adjusted to make sure that they are placed immediately after the call.

**Comment by tmat** [comment]
I believe in debug mode we follow the rules. In fact, we only emit PDB sequence points when the evaluation stack is empty.

Release mode might be breaking these rules because of the optimizations that are performed after we determine where sequence points should be placed.

**Comment by tmat** [comment]
> Are they being triggered by the fact that there was a call, but they are coming late? Or is it because the compiler thinks that the evaluation stack is empty and is making a mistake here?

The compiler doesn't make the decision like that. Rather the implementation of each language construct determines where sequence points are placed for that language construct. I believe all these placements are correct. As mentioned above, it's the later optimization phase that breaks things.

**Comment by delmyers** [comment]
I see, so optimizations end up deleting sequence points as the code transformations occur.

**Comment by jcouv** [comment]
From offline discussion (@tmat feel free to correct my summary), we could add two assertions to the compiler:
1. compare the number of sequence points between retail and debug bits (they should be equal; we should not delete sequence points when optimizing)
2. check that sequence points are only produced when the eval stack is empty or that we're immediately following a call, in debug bits

**Comment by tmat** [comment]
@jcouv Mostly correct.

**Comment by jcouv** [comment]
@tmat I may have lost track a bit. Is the outcome that we don't need to change anything in the compiler, or do you still think some of the above assertions would be useful?
