### ISSUE TITLE
XML documentation ignored when generated by an external tool

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69204]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XML-documentation-ignored-when-generated/10420992)._

---
[severity:It's more difficult to complete my work]
I've a solution that, among other projects, includes a class library and an application that references it. This library is a managed wrapper over an existing native library. Since the library is already well documented, instead of copying the relevant information for each API member into XML doc comments in the managed wrapper's source code and letting Visual Studio generate the documentation file, I use an external tool to generate an XML file with the required format from the existing documentation and set its '_Copy to Output Directory_' property as **true**. In this instance, the  '_GenerateDocumentationFile_' setting in the project file is set as **false**.

The problem is that for a project in the **same solution** that references this library, even though I can see that both the library DLL as well as its XML documentation file have been copied to its output folder correctly, I do not get any Intellisense for any of the library members. This happens both when using the library as a project reference as well as referencing its DLL directly. In contrast, Intellisense begins to be shown as expected after reopening the **same** project independently from its original solution.

**To reproduce:**
- Create a new solution containing a class library (e.g. MyLibrary) and a console app (e.g. MyApp)
- Add a new class to the library project and add the following content. For example:
  ```
  namespace MyLibrary;

  public class MyClass
  {
      public void MyMethod(int arg1, string arg2)
      {
      }
  }
  ```
- Add an XML file to the library project with the following content to simulate XML docs being generated by an external tool. Set its '_Copy to Output Directory_' setting to **Always**.
   ```
  <?xml version="1.0"?>
  <doc>
      <assembly>
          <name>MyLibrary</name>
      </assembly>
      <members>
          <member name="T:MyLibrary.MyClass">
              <summary>
              This is my class.
              </summary>
          </member>
          <member name="M:MyLibrary.MyClass.MyMethod(System.Int32,System.String)">
              <summary>
              This is my method.
              </summary>
              <param name="arg1">An integer parameter.</param>
              <param name="arg2">A string parameter.</param>
          </member>
      </members>
  </doc>
   ```
- In the console app, add a reference to the library DLL. (Note: a project reference has the same behavior).
  ```
    <ItemGroup>
      <Reference Include="MyLibrary">
        <HintPath>..\MyLibrary\bin\Debug\net7.0\MyLibrary.dll</HintPath>
      </Reference>
    </ItemGroup>
  ```
- Add some code to the console app and notice that Intellisense is not available for either MyClass or its methods. For example:
  ```
  MyLibrary.MyClass c = new();
  c.MyMethod(123, "ABC");
  ```
- Right-click the library project in Solution Explorer and select **Remove**.
- Notice that Intellisense for MyClass and MyMethod begins to be shown in the console app
- Add the library project back to the solution
- Intellisense is missing again

---
#### Feedback Bot on 7/23/2023, 09:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
