### ISSUE TITLE
IDE0200 is too aggressive

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#69209]
**Version Used**: VS 17.6 preview 2.0, .Net 7.0

**Steps to Reproduce**:

The following correct code triggers `IDE0200` ([link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaogZgAJSGBhB6gb2oZ6bKSYBWADxEyABgB8DAM4ZoMACZiSAbm68xAoigYBlebBYBDADamAFERFipDY2AwBLCHgCUDALzS5C5WRIve0cXPHUqXnYIzRISDR4uaMieNjAgvBxzcOTeAwUTcwsLD28GMAA6ABUIAygnPABzYrdsnKi2svSYAHdi1pyxAE4LX1h/Emb+hgBfammgA==)):

```chsarp
using System;

public class C 
{
    static Func<string> storedAction;
    static void StoreCall(Func<string> action) => storedAction = action;
    
    public static void Main()
    {
        C c = null;
        StoreCall(() => c.ToString()); // IDE0200 here
        
        c = new();
        Console.WriteLine(storedAction());
    }
}
```

After fixing it as suggested, the resulting code instead crashes with a NRE ([link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoaogZgAJSGBhB6gb2oZ6bKSYBWADxEyABgB8DAM4ZoMACZiSAbm68xAoigYBlebBYBDADamAFERFipDY2AwBLCHgCUDALzS5C5WRIve0cXPHUqXnYIzRISDR4uaMieNjAgvBxzcOTeAwUTcwswADoAFQgDKCc8AHM3bJyoxoY0zwY8GAB3C3r45LEATgtfWH8SHt6khgBfammgA==)):

```chsarp
using System;

public class C 
{
    static Func<string> storedAction;
    static void StoreCall(Func<string> action) => storedAction = action;
    
    public static void Main()
    {
        C c = null;
        StoreCall(c.ToString); // NRE
        
        c = new();
        Console.WriteLine(storedAction());
    }
}
```

The reason is obvious, the first code captures the object by reference when storing the delegate, so when it's later instantiated, the delegate will use the new instance correctly, while the second code stores the instance by value (a copy) so it will forever be attached to a null reference when called. The two code snippets aren't equivalent, so the warning shouldn't trigger here.

**Diagnostic Id**:

IDE0200

**Expected Behavior**:

This waring shouldn't be shown here.

**Actual Behavior**:

Both the warning and the auto-fix are present on code following this pattern, in my opinion incorrectly.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/69101
