### ISSUE TITLE
`IAsyncOperation` and unused usings

### ISSUE THREAD

**Issue by rick-palmsens** [dotnet/roslyn#69218]
`dotnet format` reports `using System;` as unnecessary, but is required when awaiting an `IAsyncOperation`. This can happen in WinUI 3 for example, when calling [ContentDialog.ShowAsync()](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog.showasync?view=winrt-22621) and wanting to await the result. The awaiter is apparently implemented as an extension method in the `System` namespace.

> ProgressScreenView.xaml.cs(2,1): warning IDE0005: Using directive is unnecessary.

With `using System;`

![image](https://user-images.githubusercontent.com/57390463/219072016-d8775eca-b961-4414-aa7c-02b3ceada951.png)

Without `using System;`

![image](https://user-images.githubusercontent.com/57390463/219072799-5097d24e-188c-4596-a8d9-f5784da6683a.png)

**Comment by jcouv** [comment]
This definitely looks like a bug, but it did not repro in the scenarios I tried with `IAsyncOperation` instances. Would you be able to provide a minimal code sample that repro'es the problem, or if it comes to that, a project (as tiny as possible, please)?

**Comment by jcouv** [comment]
@rick-palmsens I'm going to close this issue as we didn't hear back from you on the additional information we need. Please re-open when you're able to share a minimal code sample or project that would repro the issue. Thanks
