### ISSUE TITLE
"Navigate To" feature frequently crashes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69234]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Navigate-To-feature-frequently-crashes/10422566)._

---
[regression] [worked-in:possibly 17.6.2 or 17.6.3?]
In one of the last couple of VS updates (17.6.?), the "Navigate To" feature has started to crash frequently (usually it runs for about half a day before it fails).

The typical symptom is that pressing `ctrl + ,` to navigate to a symbol simply stops doing anything (and is only recovered by restarting Visual Studio), but in this specific case an actual error was presented.

![image](https://github.com/dotnet/roslyn/assets/1408396/bc251094-8241-4ccf-af89-a53010d85a1e)

---
#### Feedback Bot on 7/25/2023, 08:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/69917
