### ISSUE TITLE
StringSyntaxAttribute does not work for property assignments in with expressions

### ISSUE THREAD

**Issue by danlyons-softek** [dotnet/roslyn#69237]
**Version Used**: 

.NET 7.0.306 on Visual Studio 17.6.5

**Steps to Reproduce**:

```csharp
public sealed record Foo
{
    [StringSyntax(StringSyntaxAttribute.Json)]
    public required string Bar { get; set; }
}
```

The syntax highlighting for the JSON in `Bar` works great for object initialization and regular property assignment, but it falls down in `with` expressions:

![image](https://github.com/dotnet/roslyn/assets/3289668/81d4daa4-bdae-4442-a0bf-d912b52434f3)

**Comment by CyrusNajmabadi** [comment]
Thanks for the report!
