### ISSUE TITLE
Possible null reference assignment should be ignored when destructuring with a discard

### ISSUE THREAD

**Issue by KyleMit** [dotnet/roslyn#69263]
**Version Used**: .NET 6 & .NET 7

**Steps to Reproduce**:

1. Destructure a `string?` into a `string`, but discard the value

```cs
#nullable enable
using System;

public class Program
{
    public static void Main()
    {
        var p = new Person("Kyle", "Mit", "A");
        (string first, string last, string _) = p;
        
        Console.WriteLine(first);
        Console.WriteLine(last);
    }
}

public record Person(string First, string Last, string? Middle = null)
{
}
```

Demo in [DotNetFiddle](https://dotnetfiddle.net/eqzcAp) (though the warning isn't surfaced there) and [Sharp Lab](https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABNmTHAWACgABAJgEYyzyBmXK56gdjIG8yBIKy3t1I8eANwgAnXAAdcAXlwxsAd1wAFbBIDOAexgAKAEQBpAJ45DAGlyGAslAAuVmwEFDASgDcvHvvLUABlwAMyhtB2t/IIwtCNYggH13eRlvYR4ffwBOfVDwrzJcIuKi7P0YhwLhAF8yWtJ6JglsAGMdCQATdU1dAyjcADEw2MjA3AAZCBH4gH5cew6OnBSUdHcuOrIgA)

**Diagnostic Id**:

[CS8601](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference) - Possible null reference assignment.

**Expected Behavior**:

Because the value is being discarded anyway, would be nice if the null type check would be ignored.

Not sure if this is more of an analyzer suggestion or even desirable, but kinda odd to enforce null checks on a discarded variable.

**Actual Behavior**:

```
        (string first, string last, string _) = p;
                                    ~~~~~~~~ Possible null reference assignment.
```

**Workaround**

Can easily workaround with correct type with `string?` or inferred type with `var`

```cs
(string first, string last, string? _) = p;
```

```cs
(string first, string last, var _) = p;
```

```cs
var (first, last, _) = p;
```

**Comment by CyrusNajmabadi** [comment]
> (string first, string last, string _) = p;

If you're going to discard, why not write this as:

`(string first, string last, _) = p;`

?

Thanks!

**Comment by jcouv** [comment]
Generally, a discard is a variable that cannot be read, but that doesn't mean that anything can be assigned to it.
So the behavior seems by-design for me. 
If I'm reading this code with an eye on nullability, having `string` there would mislead me to thinking that the deconstruction cannot produce a `null`. If a non-nullable type is provided, then it makes sense to honor it.

**Comment by CyrusNajmabadi** [comment]
Also 'string _' is not a discard. It's a variable called _ of type string :-)

**Comment by jcouv** [comment]
> Also 'string _' is not a discard. It's a variable called _ of type string :-)

That depends on the context. In a deconstruction, I think it is a discard.

**Comment by CyrusNajmabadi** [comment]
Really??  We have typed discards?   That's definitely something I didn't know!
