### ISSUE TITLE
Calling SyntaxGenerator.Declaration on an explicit interface indexer implementation generates the wrong result

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#69284]
**Version Used**:  4.8.0-1.23374.10

**Steps to Reproduce**:

1. Call SyntaxGenerator.Declaration on an IPropertySymbol that represents and explicitly implemented interface indexer.

See: 
[syntaxGenTest.zip](https://github.com/dotnet/roslyn/files/12199448/syntaxGenTest.zip)

**Expected Behavior**:
Indexer is emitted.
```c#
global::System.Object global::IFooList.this[global::System.Int32 index] { get; set; }
```
**Actual Behavior**:
Normal property named "Item" is emitted.
```c#
global::System.Object global::IFooList.Item { get; set; }
```

This is related to this issue: https://github.com/dotnet/roslyn/issues/53911

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback that this is an issue, and no movement on this in a year.
