### ISSUE TITLE
Improve handling of CS8974

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/roslyn#69286]
### Analyzer

**Diagnostic ID**: CS8974

### Analyzer source

**SDK**: Built-in analyzers in .NET 7 SDK or later

**Version**: SDK 7.0.306

### Describe the bug

Warning  Show up when i call `GCHandle.Alloc(instance.Method)` prior to `Marshal.GetFunctionPointerForDelegate` for application stability.

### Steps To Reproduce

```cs
class TestClass
{
    void Method(){}

    static void Test()
    {
        var t = new TestClass();
        GCHandle.Alloc(t.Method);
    }
}
```

### Expected behavior

No warning

### Actual behavior

`Converting method group 'Method' to non-delegate type 'object'. Did you intend to invoke the method?` 🤓

## Additional context

First, the analyzer should check if delegate can return a boxed (object) type.
Second, ignore calls to `GCHandle.Alloc`.

**Comment by jcouv** [comment]
Tagging @cston for consideration. 
If I understood correctly, the proposal is to check whether the return type of the method group could convert to `object` before warning. In the OP example, the method group returns `void` so it wouldn't make sense to invoke the method instead.
This would not work well in the new proposed way of determining the natural type of the method group. The method group could return `void` and still be invoked to yield a non-void result (given arguments, we could pick an non-void-returning extension method).

**Comment by jcouv** [comment]
Closing as by-design
