### ISSUE TITLE
region text not updating when collapsed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69296]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/region-text-not-updating-when-collapsed/10423942)._

---
Version 17.6.5

When you edit the text after a #region directive and then collapse the region, the collapsed text does not update correctly on the first attempt.

If you open and re-close the region again the text is updated.
If you scroll up/down the region text is updated (most of the time).

---
#### Feedback Bot on 7/26/2023, 09:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Moved to internal editor team
