### ISSUE TITLE
Cursor jumps during editing with Document Outline enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/when-i-wanna-write-code-in-my-class-c/10426310)._

---
\[regression\] \[worked-in:17.7.0 preview 4.0\]  
Greetings!

“When I want to type some code in an old class I made, the Visual Studio editor goes to another line. I would like to write a function, ‘Hello, World!’, and when I’m typing, it jumps to another line, just like in the screenshot example. However, it jumps to the main class! Please take a look at the example screenshots below.”

![image](https://github.com/dotnet/roslyn/assets/1408396/165a2356-c19a-4573-85be-8f6c85339859)

---
#### Feedback Bot on 7/30/2023, 09:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
I believe this is related to Document Outline. I've seen it occur twice since the feature was enabled again; when it happens, it will happen repeatedly in the same document, but otherwise was extremely rare. I'm not sure what the underlying cause is yet.

**Comment by devabady** [comment]
To be honest, yeah, that's what I thought because I have to work with the Document Outline feature and disable and enable it every time, which will definitely take time. However, we need to fix this bug as soon as possible. best regards, ABDULHADI ALANAZI

**Comment by devabady** [comment]
> I believe this is related to Document Outline. I've seen it occur twice since the feature was enabled again; when it happens, it will happen repeatedly in the same document, but otherwise was extremely rare. I'm not sure what the underlying cause is yet.

To be honest, yeah, that's what I thought because I have to work with the Document Outline feature and disable and enable it every time, which will definitely take time. However, we need to fix this bug as soon as possible. best regards, ABDULHADI ALANAZI

**Comment by SteveReddoch** [comment]
> Document Outline

Yes, I found if I turn off document outline it stops jumping around.
