### ISSUE TITLE
Unable to build/restore the tree, when the current user has spaces in the name

### ISSUE THREAD

**Issue by asvishnyakov** [dotnet/roslyn#6931]
As described [here](https://github.com/dotnet/roslyn/issues/6913), I open another bug, because I still can reproduce issue.
1. I have Windows 8.1 and the user with spaces in the name ("Aleksandr Vishnyakov")
2. I follow [these instructions](https://github.com/dotnet/roslyn/wiki/Building%20Testing%20and%20Debugging):
2.1. I already have Visual Studio 2015 with the Visual Studio Extensibility and Windows 10 tools optional components installed. I also have NuGet 3.2 installed.
2.2. I clone https://github.com/dotnet/roslyn to D:\Roslyn folder in Visual Studio Team Explorer, so *I have latest version of master branch* (commit 268e7d3 at this time)
2.3. I open Developer Command Prompt for VS2015
2.4. I run `Restore.cmd`. When I do it, I get errors like this:
`For switch syntax, type "MSBuild /help"`
`MSBUILD : error MSB1008: Only one project can be specified.`
`Switch: Vishnyakov\AppData\Local\Temp\tmpCBF5.tmp`
2.5. I run `msbuild /v:m /m Roslyn.sln`. I get only one error:
` 'C:\Users\Aleksandr' is not recognized as an internal or external command,
 operable program or batch file.`
`D:\Roslyn\src\ExpressionEvaluator\Core\Source\Concord\Concord.csproj(48,5): error MSB3073: The command "C:\Users\Aleksandr Vishnyakov\.nuget\packages\FakeSign\0.9.2\tools\FakeSign.exe "D:\Roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll"" exited with code 9009.`
and only one warning:
`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets (1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\Aleksandr Vishnyakov\.nuget\packages\Microsoft.Build.Framework\0.1.0-preview-00003\lib\dotnet\Microsoft.Build.Framework.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [D:\Roslyn\src\Compilers\Core\MSBuildTask\Portable\MSBuildTask.csproj]`
2.6. I open Roslyn.sln in Visual Studio and try to rebuild solution. I get a lot of errors. For example:
`10>  'C:\Users\Aleksandr' is not recognized as an internal or external command,
15>------ Rebuild All started: Project: VisualStudioInteractiveWindow, Configuration: Debug Any CPU ------
10>  operable program or batch file.
10>D:\Roslyn\src\ExpressionEvaluator\Core\Source\Concord\Concord.csproj(48,5): error MSB3073: The command "C:\Users\Aleksandr Vishnyakov\.nuget\packages\FakeSign\0.9.2\tools\FakeSign.exe "D:\Roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Metadata.dll"" exited with code 9009.`
or
`18>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3106: Assembly strong name "D:\Roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
18>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3106: Assembly strong name "D:\Roslyn\Binaries\Debug\Microsoft.VisualStudio.Debugger.Engine.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
18>D:\Roslyn\src\ExpressionEvaluator\Core\Source\ExpressionCompiler\DynamicFlagsCustomTypeInfo.cs(6,39,6,49): error CS0234: The type or namespace name 'Evaluation' does not exist in the namespace 'Microsoft.VisualStudio.Debugger' (are you missing an assembly reference?)`
`121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll' could not be found
121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll' could not be found
121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll' could not be found
121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.dll' could not be found
121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ExpressionCompiler.dll' could not be found
121>CSC : error CS0006: Metadata file 'D:\Roslyn\Binaries\Debug\Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.dll' could not be found`
`========== Rebuild All: 111 succeeded, 11 failed, 0 skipped ==========`
If I try to restore nuget packages via Visual Studio (in any step), I get similar errors.

**Comment by davkean** [comment]
Thanks, sorry about this. Let me actually set a user with spaces and see if I can repro this - last time I cheated by setting my source and packages directory to contain spaces.

**Comment by jasonwilliams200OK** [comment]
@davkean, based on https://github.com/dotnet/roslyn/issues/2844#issuecomment-158503114, I am trying to build master on FreeBSD 10.2 and getting the similar error:

> ./cibuild --mono
> ...
> CodeAnalysis -> /root/roslyn/Binaries/Debug/Microsoft.CodeAnalysis.dll
> CSharpSyntaxGenerator -> /root/roslyn/Binaries/Debug/CSharpSyntaxGenerator.dll
> CompilerBoundTreeGenerator-> /root/roslyn/Binaries/Debug/BoundTreeGenerator.dll
> CSharpErrorFactsGenerator -> /root/roslyn/Binaries/Debug/CSharpErrorFactsGenerator.dll
> CSharpCodeAnalysis -> /root/roslyn/Binaries/Debug/Microsoft.CodeAnalysis.CSharp.dll

So far so good. After that couple of MSB3106 warnings from `Microsoft.Common.CurrentVersion.targets(1814,5)` about strong name followed by this error:

> /tmp/.NETPortable,Version=v5.0.AssemblyAttributes.cs(4,35): error: CS0234: The type or namespace name 'Versioning' does not exist in the namespace 'System.Runtime' ...

Note that, I had to slightly hack my way in to get to this point:

Installations:

```csh
# from scratch!
#
# install freebsd
cd ~/

# unzip caveat: see https://github.com/dotnet/roslyn/pull/5859
pkg install mono unzip nano
mv /usr/bin/unzip /usr/bin/lame-unzip
ln -s /usr/local/bin/unzip /usr/bin/unzip

# pre-requisite stuff
mozroots --import --machine --sync 
curl http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip -o ../pcl.zip
unzip ../pcl.zip; rm ../pcl.zip
mv PortableReferenceAssemblies-2014-04-14 /usr/local/lib/mono/xbuild-frameworks/.NETPortable
git clone https://github.com/dotnet/roslyn
cd roslyn
```

Little Hack:

```csh
# hack starts here
# first impersonate as Mac
./cibuild.sh --os Darwin
# once both the zips are laid out in /temp,
# ctrl+C to terminate (as it will fail anyway)
#
cp -r /tmp/mono.mac.4/lib/mono/xbuild/Microsoft/Portable/v5.0/   /usr/local/lib/mono/xbuild/Microsoft/Portable/v5.0
cp -r /tmp/mono.mac.4/lib/mono/xbuild/Microsoft/NuGet/   /usr/local/lib/mono/xbuild/Microsoft/NuGet
# that's the end of hack!

# now run:
./cibuild.sh --mono-path /src/local/bin 
# to eventually hit CS0234
```

**Comment by asvishnyakov** [comment]
Any news?

**Comment by davkean** [comment]
Sorry no news. Due to other fires, have not had time to look at this. It's Thanksgiving in the US this week, so realistically won't be looked at until next week some time, unless something higher pops up.

We do accept contributions, though, so figuring out where we need to add the extra quotes would be extremely helpful. :)

**Comment by asvishnyakov** [comment]
It's hard, because I need to MSBuild log, but I don't know where and how NuGet run it. When I add just "-verbosity detailed" in Restore.cmd I get detailed NuGet log, but not MSBuild.

**Comment by asvishnyakov** [comment]
1. Rebuild fail caused by typo. Fixed. Please, accept [pull request](https://github.com/dotnet/roslyn/pull/7085).
2. Error messages in nuget output possible caused by bug in nuget command-line tool. [Already fixed](https://github.com/NuGet/NuGet.Client/commit/570ffe3a3bec63549bd5214ff33dad5d43f85803) in  nuget source code ([MsBuildUtility.cs](https://github.com/NuGet/NuGet.Client/blob/570ffe3a3bec63549bd5214ff33dad5d43f85803/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs) lines 64-68), but latest verison of nuget (3.2.1-rc) are still broken. Please, do not close this issue until fixed version will be released and will be used to build Roslyn.

**Comment by davkean** [comment]
Thanks appreciate you figuring this out.

We needed to roll back NuGet - due to some other issues we were running into (fixed next week hopefully) so you should be unblocked soon.

**Comment by davkean** [comment]
This was accidentally closed in the merge.

**Comment by asvishnyakov** [comment]
Fixed with 7c289f09f4e58bfc8ca139bbc74a108c58d0e16b

**Comment by asvishnyakov** [comment]
You may close this issue as fixed.

**Comment by davkean** [comment]
Thanks!
