### ISSUE TITLE
IDE0022 suggestion: option to ignore methods with where clause

### ISSUE THREAD

**Issue by Drake53** [dotnet/roslyn#69310]
I have configured IDE0022 with the following option:
```
csharp_style_expression_bodied_methods = when_on_single_line
```

With this setting there are two styles possible:
```csharp
// Style 1: Entire method declaration on a single line
public int GetAge() => this.Age;

// Style 2: Expression body on new line
public int GetAge()
    => this.Age;
```

I prefer the first style, however at the same time I have a rule (I think it's one from StyleCop) that states I should put a where clause on a new line, again giving two style options:
```csharp
public TEnum GetZero<TEnum>
    where TEnum : Enum, struct => (TEnum)0;

public TEnum GetZero<TEnum>
    where TEnum : Enum, struct
    => (TEnum)0;
```

At this point I'd prefer to go back to block-bodied methods, since I find neither style appealing.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
