### ISSUE TITLE
Consider using RuntimeHelpers.CreateSpan as part of stackalloc initialization

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#69325]
Follow-up on https://github.com/dotnet/roslyn/pull/66251#discussion_r1281060220

stackalloc'ing a byte/bool/sbyte[] uses the same optimization as is used for assigning a byte/bool/sbyte[] into a ReadOnlySpan, where the data is blitted into PrivateImplementationDetails. With a stackalloc, there's no allocation to avoid, but it can bulk copy the data into the stackalloc'd memory rather than initializing the elements one by one.

For multi-byte primitives, however, it still sets each element one by one, whereas multi-byte primitives with `ReadOnlySpan<T> span = new T[] { ... }` were updated to use RuntimeHelpers.CreateSpan. The same can be done for stackalloc, e.g. using CreateSpan to get a span to the PrivateImplementationDetails data and then copying that into the stackalloc'd memory.

**Comment by Sergio0694** [comment]
> "there's no allocation to avoid, but it can bulk copy the data into the stackalloc'd memory"

Just curious, does ECMA specifically state that `stackalloc` _must_ allocate new stack only memory to give back to you? As in, would it be a valid lowering optimization for Roslyn to skip that entirely and just lower eg. `stackalloc byte[] { 1, 2, 3 }` (or whatever type that supports creating a span over an RVA) into getting the span and using that directly, with no copy at all? Of course still with the same scoped semantics as if it was really stack only memory. But like, would it be valid? 🤔

Thinking that would both skip the actual allocation (which is still not completely free even if the JIT literally did `sub rsp <blah>`), the data copy, and the additional overhead for the stack cookie and its accompanying check/throw epilogue.
