### ISSUE TITLE
No C# project is currently loaded

### ISSUE THREAD

**Issue by richlander** [dotnet/roslyn#69379]
Got this.

<img width="465" alt="image" src="https://github.com/dotnet/roslyn/assets/2608468/ad135de6-00f5-4c79-ac30-6c7cb2dbc93c">

Takes me to this fun page: https://www.bing.com/?ref=aka&shorturl=vscode/dotnet/debug

I wasn't able to self-diagnose my problem from the information there.

I am seeing this with multiple projects.

```
Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

Dev Kit: v0.4.2

**Comment by timheuer** [comment]
Kamino closed and cloned this issue to [microsoft/vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools/issues/318)
