### ISSUE TITLE
Make the Workspaces integration tests not use the wrong product binaries in non-VS hosts

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6937]
@jasonmalinowski Tracking the rest of the fix for the CSharpCodeActions thing.

**Comment by jasonmalinowski** [comment]
@dpoeschl what was this problem again? :smile:

**Comment by dpoeschl** [comment]
@jasonmalinowski:

```
The "Persistence Service" scenario in the Workspaces integration tests
causes ETA to get into a state where it loads assemblies from the
msbuild directory instead of the binaries directory. This change skips
that scenario in ETA, which allows later runs of CSharpCodeActions in
the same ETA instance to succeed.
```

We (you) were looking into preventing it from loading the wrong assemblies, but we needed a quicker fix.

**Comment by jasonmalinowski** [comment]
Ah, thanks. The bug was lacking, uh, information. :smile:

**Comment by jasonmalinowski** [comment]
@dpoeschl: is this still a problem?

**Comment by Pilchie** [comment]
Still a lack of information here...
