### ISSUE TITLE
Use background work indicator for Go To Implementation

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69390]

**Comment by CyrusNajmabadi** [comment]
Go-to-impl intentionally does not use this.  Go to impl is already async and works in the following fashoin.

First, if a singular result is found in a short amount of time, we just take you to it.   Second, if we find multiple results, or the result is not ready immediately, we pop up the find-symbol-results window and show you the progress the search is making findin the impls.

As we have UI that shows up in the right timing window to let the user know we are doing what they asked, we do not need a secondary in-editor message saying we're doing that.  

BWI is highly relevant when we're doing work on behalf of the user, and there is no other UI affordance that lets them know that's going on.   Feature like Find-Refs and GoTo-Impl, which already have a destination window, and present it (with messages and progress in that window) don't need an additional editor affordance.
