### ISSUE TITLE
VB Embedded Runtime should compile with overflow checks enabled

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6941]
Consider the following code snippet:

``` vb
Sub Main()
    Dim s As SByte = -128
    Dim o As Object = s
    Dim b = CByte(o)
    Console.WriteLine(b)
End Sub
```

This code should always throw on `OverflowException` on the `CByte(o)` expression.  However this code does not throw when overflow checking is disabled and the VB runtime is embedded instead of referenced.  

It appears that when compiling the VB runtime in the embedded case we inherit the overflow checking flag instead of having it always be enabled.  This is a break from Visual Studio 2013.

**Comment by cston** [comment]
The conversion throws an `OverflowException` when compiled with ```vbc -removeintchecks+ c.vb``` but does not throw an exception with ```vbc  -vbruntime* -removeintchecks+ c.vb``` with both VS 2015 and VS 2013. The exception should be thrown regardless of whether VB runtime is embedded but the current behavior is not a breaking change.

**Comment by AlekseyTs** [comment]
It looks like Compatibility Council is leaning towards leaving the current behavior as is due to the risk of introducing a breaking change in the behavior.

**Comment by gafter** [comment]
Please keep the issue open until documentation has been added.

**Comment by AlekseyTs** [comment]
@gafter Please provide more details what document you would like me to update, and then assign the issue back to me.

**Comment by gafter** [comment]
I will refer you to detailed information about guidelines for these things separately.

For this particular issue, please add a new markdown document in https://github.com/dotnet/roslyn/tree/master/docs/compilers/Visual%20Basic (perhaps named `Checked vs Embedded VB Runtime.md`) containing a description of how and when the behavior of VB programs differ from the specified behavior.

**Comment by AlekseyTs** [comment]
Moving issue to RTM bucket for now.

**Comment by gafter** [comment]
Our internal notes in [OneNote](https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook%20-%20New&wd=target%28Compilers%2FCompiler%20Design.one%7CD0427C1F-43BD-44AA-A337-20E46E56BB4C%2FAdd%20notes%20to%20the%20compiler%20specification%7C369912F5-AFA7-4384-A4F4-E3135160CC86%2F%29) say, in part

> Whenever you add or modify code in the compiler that
1. Causes the compiler to vary from the language specification; or
2. Causes the compiler to vary from the native compiler behavior; or
3. Causes the compiler to support user-visible behavior that is not documented in the language specification
> 
> Please add a note in a markdown document on github under
https://github.com/dotnet/roslyn/tree/master/docs/compilers

**Comment by AnthonyDGreen** [comment]
Ran into this bug while Bing-ing something else, but...

The previous behavior was a bug. The early-bound behavior of CByte and all numeric conversions is governed by the integer overflow checking flag (as it should be). It is an explicit design principle that moving between late-bound and early-bound shouldn't (generally) change behavior or semantics. It was always a bug that the run-time conversion didn't respect this setting and the embedded behavior is correct. The correct fix would actually be to have the emitted calls to Converstions.ToByte(Object) either pass in a flag denoting whether conversions should be checked or call a Conversions.ToByteUnchecked(Object) method or some such. We can _consider_ such a solution _if_ we have a localized way of changing Integer overflow checking locally (and indeed such a feature would be require even to restore the native behavior) but we shouldn't invest in restoring the previously broken behavior.

**Comment by gafter** [comment]
@jaredpar I suspect this was closed in error. The previous (broken) behavior was not either documented or fixed. We should do one or the other before this issue is closed. Please correct me if I misunderstand the status.

**Comment by gafter** [comment]
Documented in https://github.com/dotnet/roslyn/issues/29415
