### ISSUE TITLE
SourceGenerators: No file emit despite `EmitCompilerGeneratedFiles` & `CompilerGeneratedFilesOutputPath`

### ISSUE THREAD

**Issue by DoctorVanGogh** [dotnet/roslyn#69417]
**Version Used**: 
Visual Studio 17.6.5

**Steps to Reproduce**:

1. Compile the attached demo solution. 
It contains & uses a "simple" incremental source generator which will output a `Foo.generated.cs` file that contains a class `Bar` which has a `static void <..>() {}` method for each line from `Bar.txt` where the text of the line is used as method names. Current lines are `x`, `y` & `z`.
The text from the line is *repeated* for the method name as many times as the `Repeats` metadata on the `AdditionalFiles` item for the `Bar.txt` file. Initial `Repeats` value is 3, so the generated class will look like:
```cs
    public static class Bar {

        public static void xxx (){}

        public static void yyy (){}

        public static void zzz (){}
        
    }
```
The source generator consuming project has definitions of
```xml
	<PropertyGroup>
		<EmitCompilerGeneratedFiles>True</EmitCompilerGeneratedFiles>			    
		<CompilerGeneratedFilesOutputPath>GeneratedSource</CompilerGeneratedFilesOutputPath>  		        
  	</PropertyGroup>
```
to output the generated source to a defined location.

**Expected Behavior**:
Compilation and **emit** of generated source to the file system in the defined subfolder `GeneratedSource`.

**Actual Behavior**:
Compilation, creation of the `GeneratedSource` folder (which is initially "missing") but **no** persisted source files in that folder:
Pre compilation:
![image](https://github.com/dotnet/roslyn/assets/324067/3207fd06-8004-4f65-ada7-80d85ca589c1)
Post (re)build:
![image](https://github.com/dotnet/roslyn/assets/324067/7fc4c8ba-9da1-45c7-b0a0-c0e357523a0e)

**Additional observations**
The generated source **is** correctly displayed in the "Dependencies/Analyzers" node(s):
![image](https://github.com/dotnet/roslyn/assets/324067/d76ef5a1-c649-4120-86f8-26e8b2f4ba36)

The complete lack of persistent emits is a tad baffling, since I have another generator where emit on (re)build works just fine. 🤷 
What I did observe though, was that emits do **never** work on `DesignTimeBuild`s:
1. Open the generated source from the `Dependencies\Analyzer" node
2. Open the metadata defining `proj` file (typically your `csproj`, here an imported `AnalyzerClient.proj`) in a split view:
![image](https://github.com/dotnet/roslyn/assets/324067/b8fd4e43-a6c8-49cc-b55c-dc6f494e0b92)
3. Change the `Repeats` value from `3` to any other value (example `1`). Save the edited `proj`file. This will trigger a `DesignTimeBuild`:
![image](https://github.com/dotnet/roslyn/assets/324067/7290fecb-8303-4f5a-a074-f4a5698bffaa)
Note how the repetitions in the method name(s) have changed as well as the updated timestamp.

I have **never** been able to get an emit to work on design time builds. It __always__ needed a rebuild for emits to work. 

This can be quite confusing if you have set up your source generator to react to specific changes in attributes, have included your emitted source in a project and the internal intellisense state (and subsequent compilations) will reflect changes to those attributes, but your "on disc" source will not.

**Comment by DoctorVanGogh** [comment]
Well, I should probably actually attach that demo solution 😅 

[AnalyzerDemo.zip](https://github.com/dotnet/roslyn/files/12273540/AnalyzerDemo.zip)

**Comment by shuaihuadu** [comment]
Same problem,  wait for an answer

**Comment by jjonescz** [comment]
Are you saying the sources are not emitted during design time builds but are emitted otherwise? That sounds like by design behavior.

**Comment by jaredpar** [comment]
Closing due to lack of response.
