### ISSUE TITLE
Remove dependency on Microsoft.VisualStudio.LanguageServer.Protocol

### ISSUE THREAD

**Issue by bjorkstromm** [dotnet/roslyn#69416]
We're working on uncoupling that as we speak :)

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/68463#issuecomment-1642658982_

Created separate issue to track this, as original issue was closed when license was updated for CLaSP.

**Comment by 333fred** [comment]
Done in https://github.com/dotnet/roslyn/pull/68990.
