### ISSUE TITLE
Target type preselection: consider base types/implementations

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#6942]
``` C#
abstract class C{}
class D: C
{
    void foo()
    {
        D d;
        C c = $$
    }
}
```

"d" isn't preselected at the caret. Same for VB.

**Comment by Pilchie** [comment]
Also possibly implicit conversions, though it may not be worth it if it is expensive perf-wise.

**Comment by CyrusNajmabadi** [comment]
Need info to determine if this is worth investing in (given that we haven't heard anything about this from any other customers).
