### ISSUE TITLE
dotnet build fails if consumer namespace prefix is same as referenced class with usings within namespace

### ISSUE THREAD

**Issue by realrubberduckdev** [dotnet/roslyn#69439]
[jcouv update:] Condensed repro in comment below.

### Describe the bug
I have created [a small repo with repro code](https://github.com/realrubberduckdev/dotnet-namespace-issue).
I will describe the repro steps below. Overall, if a consumer class's namespace has the same prefix as a namespace it is using and the using are within the namespace block, then the build fails.

e.g. build passes
```
namespace NameSpaceIssueCheck;

using ABC.DEF.Lib1;
using DEF.Lib1;

internal class Class1
{
    public string GetMessage()
    {
        Console.WriteLine(new Class2().GetMessage());
        Console.WriteLine(new Class3().GetMessage());

        return "hello from class A";
    }
}
```

build fails
```
namespace ABC.NameSpaceIssueCheck;

using ABC.DEF.Lib1;
using DEF.Lib1;

internal class Class1
{
    public string GetMessage()
    {
        Console.WriteLine(new Class2().GetMessage());
        Console.WriteLine(new Class3().GetMessage());

        return "hello from class A";
    }
}
```
Note that the only difference between these two files is `namespace NameSpaceIssueCheck;` vs `namespace ABC.NameSpaceIssueCheck;`.

### To Reproduce

[A small repo with repro code](https://github.com/realrubberduckdev/dotnet-namespace-issue).
Steps to reproduce:
- Checkout the repo
- Run the scenario where build works, the consumer class has a different namespace as compared to the ones it is referencing (refer [Class1.cs](https://github.com/realrubberduckdev/dotnet-namespace-issue/blob/194bd2be412f960dfa5b4bbd79368cf5cd6b81f3/BuildWorks/Class1.cs#L1))
```
cd BuildWorks
dotnet build .\NameSpaceIssueCheck.csproj
```
- Run the scenario where the build fails, the consumer class has the same namespace prefix `ABC` as compared to the ones it is referencing (refer [Class1.cs](https://github.com/realrubberduckdev/dotnet-namespace-issue/blob/194bd2be412f960dfa5b4bbd79368cf5cd6b81f3/BuildFails/Class1.cs#L1))
```
cd BuildFails
dotnet build .\NameSpaceIssueCheck.csproj
```
Notice the error:
```
C:\dotnet-namespace-issue\BuildFails\Class1.cs(4,7): warning CS0105: The using directive for 'ABC.DEF.Lib1' appeared previously in this namespace [C:\dotnet-namespace-issue\BuildFails\NameSpaceIssueCheck.csproj]C:\dotnet-namespace-issue\BuildFails\Class1.cs(11,31): error CS0246: The type or namespace name'Class3' could not be found (are you missing a using directive or an assembly reference?) [C:\dotnet-namespace-issue\BuildFails\NameSpaceIssueCheck.csproj]
```
- Run the scenario where build works, the consumer class has the same namespace prefix `ABC` as compared to the ones it is referencing and the using are outside of the namespace block (refer [Class1.cs](https://github.com/realrubberduckdev/dotnet-namespace-issue/blob/194bd2be412f960dfa5b4bbd79368cf5cd6b81f3/BuildWorksUsingsOutsideNamespace/Class1.cs#L1))
```
cd BuildWorksUsingsOutsideNamespace
dotnet build .\NameSpaceIssueCheck.csproj
```
Why does the build fail in the case when using statements are inside the namespace? Why does it start passing if using statements are  moved out?

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Tried with dotnet from command prompt.

**Comment by jcouv** [comment]
Below is a condensed repro.
I tested this with the native compiler (`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe`) and the behavior is the same.
So without having investigated the relevant lookup rules deeply, I can already say whether this behavior is correct or not we're not going to change it.
I'm a bit curious to understand whether it is correct or not (it's not obvious on first glance), so I'll try to take a look to understand better.

```
using System;

namespace NameSpaceIssueCheck // okay
//namespace ABC.NameSpaceIssueCheck // causes error on `new Class3()` below
{
    using ABC.DEF.Lib1;
    using DEF.Lib1;

    internal class Class1
    {
        public void M()
        {
            Console.WriteLine(new Class2());
            Console.WriteLine(new Class3());
        }
    }
}

namespace ABC.DEF.Lib1
{
    public class Class2 { }
}

namespace DEF.Lib1
{
    public class Class3 { }
}
```

**Comment by jcouv** [comment]
Alright, the current behavior is by-design based on the [spec](https://github.com/dotnet/csharpstandard/blob/draft-v7/standard/namespaces.md#143-namespace-declarations). Here's the relevant section/example:

> ```
> namespace N1.N2
> {
>     class A {}
>     class B {}
> }
> ```
> is semantically equivalent to
> ```
> namespace N1
> {
>     namespace N2
>     {
>         class A {}
>         class B {}
>     }
> }
> ```

So in your example, the `using DEF.Lib1;` occurs inside `namespace ABC` which means you're not bringing the namespace that you want into scope. There's actually a warning that gives you a hint (duplicate import). 
The solution is to use `using global::DEF.Lib1;` instead.

**Comment by realrubberduckdev** [comment]
@jcouv thank you very much, this behaviour makes sense now :-)
