### ISSUE TITLE
The .NET SDK has newer analyzers with version '7.0.4' than what version '7.0.3' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.

### ISSUE THREAD

**Issue by Pentadome** [dotnet/roslyn#69436]
Microsoft.CodeAnalysis.NetAnalyzers does not have a 7.0.4 version.

https://github.com/dotnet/roslyn/issues/65581

**Comment by waliMSFT** [comment]
Please have a look in this discussion to unblock your pipeline. 
https://github.com/actions/runner-images/issues/8067#issuecomment-1674350413

**Comment by mavasani** [comment]
Target reporting this warning has been removed with https://github.com/dotnet/roslyn-analyzers/pull/7040
