### ISSUE TITLE
[LSP] [Bug]: New line in or immediately below documentation comment does not break line correctly

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#69441]
## Version Used

- Compiler version: '4.8.0-1.23403.6 (35e87b6a)'. Language version: latest (11.0).
- VSCode: 1.81.0, 6445d93c81ebe42c4cbd7a60712e0b17d9463e97, x64
- C# extension: v2.0.328, C# Dev Kit extension: v0.3.21

## Steps to Reproduce

1. Create or open any file in C# language mode.
2. Add code such as this:
    ```cs
    /// <summary>
    ///     The quick brown fox jumps over the lazy dog.
    /// </summary>
    class C { }
    ```
3. Place the cursor at the end of the documentation comment or the class definition and press enter.

## Behavior

Depending on where in the documentation comment the line break is made, the outcome is slightly different, but overall similar.  
I will be using `|` as the cursor in these examples.

### Example 1

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
/// </summary>|
class C { }
```

<table style="width: 100%">
<tr><th>Actual Behavior</th><th>Expected Behavior</th></tr>
<tr>
<td>

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
///     |/// </summary>

class C { }
```
</td>
<td>

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
/// </summary>
/// |
class C { }
```
</td>
</tr>
</table>

### Example 2

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.|
/// </summary>
class C { }
```

<table style="width: 100%">
<tr><th>Actual Behavior</th><th>Expected Behavior</th></tr>
<tr>
<td>

```cs
/// <summary>
/// |///     The quick brown fox jumps over the lazy dog.

/// </summary>
class C { }
```
</td>
<td>

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
///     |
/// </summary>
class C { }
```
</td>
</tr>
</table>

### Example 3

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
/// </summary>
class C { }|
```

<table style="width: 100%">
<tr><th>Actual Behavior</th><th>Expected Behavior</th></tr>
<tr>
<td>

```cs
/// <summary>
///     The quick brown fox jumps over the lazy dog.
/// </summary>
/// |class C { }
​
```
</td>
<td>

```cs

/// <summary>
///     The quick brown fox jumps over the lazy dog.
/// </summary>
class C { }
|
```
</td>
</tr>
</table>

**Comment by arkalyanms** [comment]
I believe @akhera99 is looking at this from the vscode side.

**Comment by just-ero** [comment]
This appears to be fixed now.
