### ISSUE TITLE
Property page support for new compiler switches

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6945]
A number of compiler switches have come online in 1.0 - 1.2 that need to be considered for property page support:

* [ ] `/deterministic` switch
* [ ] `/pathmap` option 
* [ ] `/publicsign` switch 
* [ ] `/pdb:portable` switch value 

It's possible not all of these will have UI associated with them but need to make the call on them.

**Comment by Pilchie** [comment]
We think all of these can wait to have UI for these until 2.0

**Comment by tiesmaster** [comment]
:+1:

**Comment by jaredpar** [comment]
Agree.

**Comment by DustinCampbell** [comment]
Moving over to project system

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#126
