### ISSUE TITLE
Extend ReadOnlySpan optimization to all constant data

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#69472]
For several years now, if you wrote:
```C#
ReadOnlySpan<byte> span = new byte[] { 1, 2, 3 };
```
where you're targeting a `ReadOnlySpan<T>`, the `T` was `byte`, `sbyte`, or `bool`, and all of the data in the array creation was constant, the compiler would avoid allocating an array, blit the data into the assembly data, and create the span pointing to that assembly data.

Several months ago, we extended that to include all the 2, 4, and 8-byte primitive types as well. When targeting .NET 7+ that has RuntimeHelpers.CreateSpan, it'd do the same assembly data approach, albeit generating a call to RuntimeHelpers.CreateSpan instead of using span's constructor. But when CreateSpan isn't available, it stores the data into an array singleton, and then returns a span around that array.
https://github.com/dotnet/roslyn/blob/56d4640c48404c1a43b59fc576fb2a211d797ef1/src/Compilers/CSharp/Portable/CodeGen/EmitArrayInitializer.cs#L641-L643

We should extend that array-based fallback to cover string literals, decimal constants, n{u}int constants, and anything else for which the language has a representation of a constant value.  Doing so will help avoid the per-use array allocation when someone does use those types, but I think more importantly it becomes a lot easier to explain when the avoid-per-call-allocations optimization actually kicks in: you're targeting a `ReadOnlySpan<T>` and all of the data is const.

**Comment by jcouv** [comment]
@stephentoub This was merged for 17.9. Reference types (except for `string`) were excluded from the change. Those are less useful (the only constant is `null`) and raise additional codegen issues.
