### ISSUE TITLE
Support XAML LSP in vscode

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#69471]
### Overview
In general the plan is to support requests for XAML files from the C#/VB LSP server (the one we use in vscode).  This will allow XAML access to the roslyn solution snapshots that they need in order to respond to LSP requests.  
1.  XAML capabilities will be registered using `client/registerCapability` ([spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability)) in order to support a different set of capabilities for XAML files as compared to C# files.
2.  We will export separate XAML handlers that apply to the C#/VB LSP server.  These handlers will be defined in a Roslyn assembly that we ship with the language server.   
3.  When handling a request we will need to choose which handler to use based on the document URI that we get from the handler.  
4.  Additionally, to support this work this issue will need to be resolved - https://github.com/dotnet/roslyn/issues/69467.  We need to ensure that the closed source XAML component versions line up with what Roslyn is expecting. 

### Details

- [x] Add the ability for the request execution queue to switch between handlers based on the document URI it recieves.
     1.  Move the retrieval of the handler from[ the initial request](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs#L123) into where it gets [de-queued](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs#L191).
     2. Get all handlers for the requested method (need to add the ability for the [HandlerProvider](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/HandlerProvider.cs#L34) to return a map of language -> handler, see next section)
     5. This will allow us to call the `GetTextDocumentIdentifier` method on each handler to find the URI associated with the request (if it is for a text document).
     6. Based on the document URI dispatch the request to the correct handler.
- [x] Add the ability to export an lsp request handler for a specific language.  I see a couple ways we could go about this, but I'd suggest starting with the following.
     1.  Update the [MethodAttribute](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/MethodAttribute.cs) to include some kind of optional language attribute.
     2.  Update the handler provider to read the optional language from the `MethodAttribute` [when it is building the handler map](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/HandlerProvider.cs#L68).
     3.  Note that this would only allow you to export language specific *handlers* for the server (which is likely enough).  You would not be able to export language specific *lsp services*.  This means that you would not be able to override base services like the [LspWorkspaceManager](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs#L46) or others for XAML (which I think is not required).  If that is required we should consider other options, including a separate XAML LSP server or updating [ExportLspServiceFactoryAttribute](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/LspServices/ExportLspServiceFactoryAttribute.cs#L20) (and the stateless version) to support language specific services.  Both are more complicated.
- [x] Allow XAML to hook into some LSP initialization so that they can provide their capabilities via [client/registerCapability](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability). 
     1.  This could fairly easily be done by creating a MEF abstraction that gets called as part of the `Initialized` LSP request.  This is implemented [here](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/RoslynLanguageServer.cs#L103).
     2.  If more complex initialization logic is needed - you could likely write some custom client code in devkit to trigger a brokered service request to a service in Roslyn that would register the capabilities.
- [x] Add support for adding XAML files to the [LspMiscellaneousFilesWorkspace](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs#L31).  Nothing complicated, just enough to ensure that the file exists in the workspace.
- [x] Add a separate XAML assembly containing the handlers and initialization code that gets loaded in VSCode.
     1.  This assembly should only get loaded when devkit is installed.
     1.  Note - we would likely want to only load this XAML assembly in VSCode.  The same language server is loaded in VS and we do not want to load vscode handlers there (VS does not support dynamic registration on document selectors).
- [x] Implement https://github.com/dotnet/roslyn/issues/69467 so we can ship closed source XAML components in a CDN.  
     1.  Should XAML ship to the same CDN as roslyn devkit assemblies?

Caveat - this is a complex area and there may be things that don't work as expected or require additional thinking.  But this is the best outline I know of right now.

**Comment by arkalyanms** [comment]
XAML team may be prototyping as well and we will want to coordinate.

**Comment by mgoertz-msft** [comment]
Yes, I am working on this.

**Comment by mgoertz-msft** [comment]
@dibarbet Thank you again for the excellent write-up here! I have a couple questions I came across while trying to implement this.

1. For calling `GetTextDocumentIdentifier` to determine the correct handler to use in `RequestExecutionQueue` I would need to be able to return `TextDocumentIdentifier`. Right now this project (Microsoft.CommonLanguageServerProtocol.Framework) does not reference the LSP package that this type is defined in. Is it ok to add a package reference to "Microsoft.VisualStudio.LanguageServer.Protocol" or do you have another idea? I suppose the IMethodHandler could return a Uri or perhaps even a bool for whether it could handle a given request.
2. What should we do about handlers that aren't associated with a document, such as workspace pull diagnostics for example?

**Comment by dibarbet** [comment]
> Right now this project (Microsoft.CommonLanguageServerProtocol.Framework) does not reference the LSP package that this type is defined in. Is it ok to add a package reference to "Microsoft.VisualStudio.LanguageServer.Protocol"

Ah... no its not.  The library is meant to not ship a specific version of protocol since its used by others (Razor/ webtools).  We'll have to add an abstraction - maybe a virtual `GetHandlerForRequest` method that by default does what it does today, and then implement it in the roslyn queue - https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs#L13 to look at the `TextDocumentIdentifier`

> What should we do about handlers that aren't associated with a document, such as workspace pull diagnostics for example?

Great question - I forgot about this case, that's on me.  We can only have a single handler for the request because there is no information in it to switch between C#/xaml (and the client will only ever call our server once).  Presumably the workspace requests should return results for both C#/ XAML so we'd need some kind of combo handler that delegated to both the language specific handlers and combined the results.  However I'm not sure how easy it is to write that handler
1.  Most workspace requests stream results back through `IProgress<T>` - maybe we could combine the streams?
2.  We'd have to ensure that the handlers don't report conflicting information.  For example XAML and C# should never ever report workspace diagnostics for the same file
3.  What about handlers like workspace/didChangeConfiguration?  We'd have to somehow figure out which configuration maps to XAML and which maps to C# which seems challenging
4.  Similar issues with workspace/executeCommand - we'd have to figure out which commands are xaml based.

Those aren't unsolvable I don't think, but its more complicated than I planned for.  It is making me question my decision to have the same C# LSP server also provide XAML results.  The LSP client is already designed to handle results from multiple providers so if it was a separate LSP server, everything *just works*.  But the server (and protocol) is not really designed with this in mind.  Want to tag @jasonmalinowski because he always has useful insight as well.

**Comment by jasonmalinowski** [comment]
Oh that is a good question. @mgoertz-msft what sort of diagnostics would you be having to report? Those wouldn't be diagnostics that would already get reported from a Roslyn source generator?

**Comment by mgoertz-msft** [comment]
@jasonmalinowski Probably none. I see that we have a handler but it doesn't seem to do anything besides overriding `GetDocuments()`, so this was more of a general question. All other handlers, and even the one command handler we have so far, are document related (they all override `GetTextDocumentIdentifier()`).

@dibarbet Thanks for the pointer. I hadn't even seen the RoslynRequestExecutionQueue yet. Workspace configuration requests are going to be interesting, we don't have any support for XAML configurations yet. I think I'll continue with the original plan for now and start thinking about how to deal with settings in the meantime.

**Comment by dibarbet** [comment]
Closing this issue as completed.  XAML support is merged and working in VSCode.
