### ISSUE TITLE
LanguageVersionExtensions needs to map special values to specific versions before comparing values

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69477]
https://github.com/dotnet/roslyn/blob/23e9f1b314fa04e7dbc8a4d8696c2e2f5c74fa22/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/LanguageVersionExtensions.cs#L9-L16

~~In the 17.7.0 release, the following method is returning true for `LanguageVersion.Latest`:~~

https://github.com/dotnet/roslyn/blob/09841218a495cafad75ba163350d1e8949d8e5d6/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/LanguageVersionExtensions.cs#L15-L16

~~See [AB#1869118](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1869118) ([public link](https://developercommunity.visualstudio.com/t/Code-Analysis-reports-erroneous-IDE0290-/10438724))~~

**Update:** Due to the way `CSharpParseOptions.LanguageVersion` works, callers of these helpers generally already map specified to effective versions, and the comparisons are valid. It would still be good to update these methods to explicitly perform the mapping as a way to ensure future callers receive consistent results. The above linked bug turned out to be a case where the user was using `LangVersion=Preview` instead of `LangVersion=latest`.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we need to make this change, we should just mae this change as a pr, and drive it with a case where something is broken withh how they currentlyb ehave.
