### ISSUE TITLE
Analyzer to warn if primary constructor parameters are mutated

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#69489]
Could we have this as a built-in code style opt for the time being?

**Comment by CyrusNajmabadi** [comment]
Currently, my preference would be to just wait on the language feature where we let these parameters be marked as 'readonly'.

**Comment by alrz** [comment]
Yes but the language default is only due to technical reasons, in reality I would expect that this is not the behavior most people want at least in aspnet apps or anything that utilizes DI for that matter. What happens is that you lose readonly guarantees if you migrate to primary constructors.

Having said that, since this would be "temporary" in a sense, perhaps it is better to be handled by third party analyzers to fill the gap until the next version or the next LTS comes around.

**Comment by CyrusNajmabadi** [comment]
I would be fine with a third party helper here.

Note: i expect that when we *do* add `readonly` primary-constructors in the language that we will update our existing `add readonly` analyzers/fixers to suggest that you move to that when it would not break anything.

**Comment by sailro** [comment]
I just created a very basic analyzer for that:

https://github.com/sailro/PrimaryConstructorAnalyzer/tree/main

**Comment by CyrusNajmabadi** [comment]
Closing out.  Feedback has been marginal here, and there's a community analyzer for this.
