### ISSUE TITLE
csharp_style_allow_embedded_statements_on_same_line_experimental and csharp_new_line_before_open_brace colide

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/roslyn#69490]
**Version Used**: 

8.0.100-preview.7.23376.3

**Steps to Reproduce**:

1.  Set `.editorconfig`:  
    `csharp_style_allow_embedded_statements_on_same_line_experimental = false:warning`  
     `csharp_new_line_before_open_brace = false`
3. Write an if with braces
4. Format

A minimal repro, with source-code provided, is ideal. 
https://github.com/LokiMidgard/bugRepoIDE2001

**Diagnostic Id**: IDE2001

**Expected Behavior**: No Warning if only an open brace is in the same line

**Actual Behavior**: Warns when an opening brace is there

![image](https://github.com/dotnet/roslyn/assets/389101/48a14ddd-8f91-4c1f-86cc-af111d839b59)

**Comment by CyrusNajmabadi** [comment]
This is not a supported config for those options.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not a supported configuration.
