### ISSUE TITLE
Roslyn.VisualStudio.Services.UnitTests expects static location for CSharpCompilerExecutable

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#695]
Roslyn.VisualStudio.Services.UnitTests incorrectly assumes that the C# Compiler Executable will always be in the same directory as the unit test assembly.

This is not the case for our standalone unit tests which run against a VS install instead of a Roslyn Build.

This should be fixed up to search in the MSBuildToolsPath as a fallback if the compiler doesn't exist in the same directory (see CompilerServerUnitTests for an example).

**Comment by Pilchie** [comment]
Where does Roslyn.VisualStudio.Services.UnitTests ever depend on the compiler executable?

**Comment by tannergooding** [comment]
The 'CSharpCompilerExecutable' field in 'src/VisualStudio/Core/Test/AnalyzerSupport/AnalyzerDependencyCheckerTests.vb'

**Comment by tmeschter** [comment]
Assigning back to @tannergooding for verification.

**Comment by tannergooding** [comment]
Everything is all good. Marked as 'Verified'.
