### ISSUE TITLE
Collection expressions codefix changes behaviour for ImmutableArray<T>

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn#69507]
**Version Used**: 

17.8.0 Preview 2.0 [34014.421.main].

Discovered in https://github.com/dotnet/project-system/pull/9229.

**Steps to Reproduce**:

Given...

```c#
ImmutableArray<string> array = ImmutableArray<string>.Empty;
```

A codefix wants to convert this into:

```c#
ImmutableArray<string> array = [];
```

However this currently compiles as:

```c#
ImmutableArray<string> asdf = default(ImmutableArray<string>);
```

Which is not equivalent and changes behaviour.

**Expected Behavior**:

Codefix should not suggest this change unless the compiler produces equivalent code.

**Actual Behavior**:

Described above.

**Comment by drewnoakes** [comment]
That PR also contains other invalid codefix changes to other immutable `Empty` values that produce compile errors such as:

```
error CS1729: 'ImmutableDictionary<string, TValue>' does not contain a constructor that takes 0 arguments
error CS1729: 'ImmutableHashSet<string>' does not contain a constructor that takes 0 arguments
error CS1729: 'ImmutableList<string>' does not contain a constructor that takes 0 arguments
```

If these aren't duplicates of the issue above I can file a new issue.

**Comment by CyrusNajmabadi** [comment]
> If these aren't duplicates of the issue above I can file a new issue.

These are not duplicates. Can you open another issue?  Thanks!

**Comment by CyrusNajmabadi** [comment]
The immutable array issue is being fixed in https://github.com/dotnet/roslyn/pull/69500

There were will explicitly block IA unless we see that it supports the .net-8 builder-pattern.

**Comment by CyrusNajmabadi** [comment]
@drewnoakes i'll file the other bug.  having a convo with compiler about it right now.

**Comment by drewnoakes** [comment]
> @drewnoakes i'll file the other bug.  having a convo with compiler about it right now.

Thanks. Just getting online now.
