### ISSUE TITLE
Collection expressions need an unnecessary brace if a cast expression is a generic type with a type alias

### ISSUE THREAD

**Issue by SunnieShine** [dotnet/roslyn#69508]
**Version Used**: 

VS 17.8p1

**Steps to Reproduce**:

```csharp
using Cell = int;

var collection = (List<Cell>)[1, 2, 3, 4, 5];
```

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIDCBTANllBeFWAFwG4BYAKEoDcIAnFAYwHscNGipmZ8UAKADJQAzkQA8mHAD4AlAG0AjABoUAJhUBmFQBYVAVgC6JIA==)

**Diagnostic Id**:

CS0119

**Expected Behavior**:

Because the former expression `(List<TypeAlias>)` has `<` and `>`, which won't be treated as an expression, the expression `[1, 2, 3, 4, 5]` won't be treated as an indexer.

**Actual Behavior**:

It seems that Roslyn is treated it as an indexer invocation:

![image](https://github.com/dotnet/roslyn/assets/23616315/576cd2e9-2041-4aec-b48b-8bc67fa21203)

**Comment by CyrusNajmabadi** [comment]
Looking
