### ISSUE TITLE
C# - When jumping to definition in a decompiled or source link file for the first time, the cursor is always at the beginning of file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C---When-jumping-to-definition-in-a-dec/10437709)._

---
[severity:It bothers me. A fix would be nice]
Repro steps:
1. In C# code, try to jump to definition on a symbol in an external package, which requires either decompiling or using source link to get the C# source.
2. If this file has never been visited before, it will take a second to decompile / load. But after loading, the cursor is not at the referenced symbol, instead it's always at the beginning of the source file.
3. Closing the tab and try again. Later attempts can successfully jump to the exact location of the symbol.

IIRC, this behavior has been observed in all versions of VS 2019 and 2022.

In the recording, notice how the first time I jumped to `AddAzureKeyVault` it went to the beginning of decompiled file, but later it could locate the correct symbol.

---
#### Feedback Bot on 8/10/2023, 09:24 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/14/2023, 02:51 AM: 

(private comment, text removed)
#### Jim Du [MSFT] on 8/14/2023, 09:39 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 8/14/2023, 08:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This didn't repro for me no matter how many times i tried:

![image](https://github.com/dotnet/roslyn/assets/4564579/0da11e7f-52fa-438d-8e14-065fca3615e4)

Trying that particular method takes me directly to:

![image](https://github.com/dotnet/roslyn/assets/4564579/6e0dfc7e-abf1-424f-954e-2b5a87823e24)

**Comment by jim-du** [comment]
Hi @CyrusNajmabadi ,

Thanks for looking into this issue. I originally reported this in VS feedback system. The updated repro steps (those "private comments") got lost during ticket transfer.

There are two extra conditions for reproducing this:
(1) Trigger the “go to definition” action inside a “floating tab” (the ones that show up on the right).
(2) (Might not be related) Call this action inside a VS instance over RDP, which has been running for a while and closed / re-connected.

I'm able to reproduce this issue in VS 2022 enterprise preview build 34022.349.main, using this public repo: https://github.com/Azure-Samples/Cognitive-Speech-TTS

Screen recording GIF:

![VSJumpToDefRepro](https://github.com/dotnet/roslyn/assets/102357939/13c1ecae-d5ba-4743-8ea6-22b4a8214f0b)
