### ISSUE TITLE
C# compilation performance regression in latest 7.0.400 SDK

### ISSUE THREAD

**Issue by lahma** [dotnet/roslyn#69515]
**Version Used**:  7.0.400

Solution build time has increased from 10 seconds to over 2 minutes. This happens both locally and on CI server which was updated to SDK 7.0.400. Colleague of mine was able to see local slowdown by updating from SDK 7.0.307 to SDK 7.0.400.

**Steps to Reproduce**:

A repo with small solution that reproes the problem: https://github.com/lahma/SlowGenericsCompilation . It takes over 10 seconds to compile these two small files.

```
dotnet build --no-restore --no-incremental
MSBuild version 17.6.10+2679cf5a9 for .NET
Time Elapsed 00:00:00.44
```

```
dotnet build --no-restore --no-incremental
MSBuild version 17.7.1+971bf70db for .NET
Time Elapsed 00:00:12.84
```

From profiling I can tell that the culprit is changes made to `NamedTypeSymbol.EnsureRequiredMembersCalculated`. Most of the time is spent there.

I created a local debug build of `csc.exe` from `main` branch and commit b91897c8ad5cea55a9d91c5b5b7b1f2a37ce7ead , running it against our csproj file shows the problem. `tryCalculateRequiredMembers` seems to take more than 5 seconds and in multiple occasions.

![image](https://github.com/dotnet/roslyn/assets/171892/707ec8c6-216e-450f-a96f-cfb6d7784ac9)

My guess here is that same information gets checked twice in recursive fashion and `_lazyRequiredMembers.IsDefault` keeps being true as nesting keeps going.

**Diagnostic Id**:

N/A

**Expected Behavior**:

Build takes reasonable time.

**Actual Behavior**:

Build takes unreasonable time.

**Comment by m-gasser** [comment]
We are also impacted by this issue. Interestingly only one of our many Applications seems to be affected.

**Comment by m-gasser** [comment]
Tanks to the sample from @lahma and knowing the pattern we are using, I was able to simplify the code needed to reproduce the issue a lot. The following seems to be the problematic pattern:
```
record Foo<T1>;
record Foo<T1, T2> : Foo<T1>;
record Foo<T1, T2, T3> : Foo<T1, T2>;
record Foo<T1, T2, T3, T4> : Foo<T1, T2, T3>;
record Foo<T1, T2, T3, T4, T5> : Foo<T1, T2, T3, T4>;
record Foo<T1, T2, T3, T4, T5, T6> : Foo<T1, T2, T3, T4, T5>;
record Foo<T1, T2, T3, T4, T5, T6, T7> : Foo<T1, T2, T3, T4, T5, T6>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8> : Foo<T1, T2, T3, T4, T5, T6, T7>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9> : Foo<T1, T2, T3, T4, T5, T6, T7, T8>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>;
record Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> : Foo<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>;
```
