### ISSUE TITLE
When saving, some Code Cleanup fixers modify C# source files excluded from compilation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-saving-some-Code-Cleanup-fixers-mo/10440309)._

---
\[severity:It’s more difficult to complete my work\]  
Add a new .cs file to a project with the content:

```  
using a;
#nullable enable
class C   {
 public void M() { string i = (string)""; } }
  
```

Make sure you have a Code Cleanup profile set to be used when saving that has the following fixers enabled:

*   Remove unused variables,
*   Remove unnecessary Imports or usings,
*   Remove unnecessary casts,
*   Remove unnecessary nullable directive,
*   Format document.  
    There might be more fixers that run on excluded files but there’s a lot of them, so I chose only these for the repro.

Now exclude the file with the UI or by editing the .csproj - add `<Compile Remove="TheFile.cs" />` to an `ItemGroup`, save the project file.  
When you’ll save TheFile.cs, you’ll see that:

*   the unused variable was not removed,
*   **the using was removed**,
*   the cast was not removed,
*   the `#nullable` directive was not removed,
*   **the document was formatted**.

When modifying an excluded file (“Miscellaneous Files”) myself and saving I didn’t expect any fixer/formatter to be run afterwards, changing the file further in any way. I can’t avoid this without modifying settings or using a different file editing program. An excluded file doesn’t participate in the project and should be treated as if it didn’t contain anything to fix or modify, Code Cleanup shouldn’t be interested in the file. Also if you'll close a file and save in the confirmation popup, you may not even notice the non-source file was edited.
Running nothing automatically could be the intended behavior, I guess, because of the 3 example fixers that didn’t run but do run in on an included file.  
The option to _manually_ run Code Cleanup in any open file (with the button / Ctrl+K+E / selecting “Run Code Cleanup”) could be left available for anyone who would find it useful (but I’m indifferent about this).

---
#### Feedback Bot on 8/14/2023, 08:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76019
