### ISSUE TITLE
`ImmutableList<T>` on net7 and compiler-expression-conversions.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#69521]
Extracted from https://github.com/dotnet/roslyn/issues/69507

Right now the compiler returns that `ImmutableList<T>` (and other sibling immutable types) have a collection-expression-conversion when assigning, even on .Net7.  This is incorrect as `ImmutableList<T>` does not fit any of the rules for a constructible collection expresison type.

It is not:

1. a Span type
2. an array type.
3. a type with a CollectionBuilderAtttribute
4. a type that follows the collection-initializer pattern.

Right now, i believe it is falling under '4'.  But as that pattern requires taht you be able to do `new CollectionType()` to construct the type, it should fail this check.

Note: this affects the IDE as we ask the compiler if a type is a constructible collection expression, and the compiler reports that that is the case here.   While IDE could augment the checks it does here, we really do not want to be in the job of reimplementing the core rules of the language here.  

Note: this also affects overload resolution (which is not good).  If a type is not a valid collection type, it shouldn't participate.

**Comment by CyrusNajmabadi** [comment]
Note: the spec does explicitly state:

> To a type that implements System.Collections.IEnumerable where:
> - The type contains an applicable instance constructor that can be invoked with no arguments or invoked with a single argument for the 0-th parameter where the parameter has type System.Int32 and name capacity.

**Comment by CyrusNajmabadi** [comment]
Also of note: the compiler believes an abstract type with a no-arg constructor to be something that tehre can be a collection-expression-conversion to :)

I believe this also falls out from `that can be invoked with no arguments or...`  an abstract type's constructors cannot be invoked at all.  It's not a thing.  So these should be filtered out as well.

**Comment by jcouv** [comment]
@CyrusNajmabadi [ImmutableList](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs) has a `[CollectionBuilder]` attribute so that's why it works. I was able to use it and it works as expected.
I've also tested an `IEnumerable` scenario and verified that it errors as expected when the constructor we need isn't present (see test below).

```

        [Fact]
        public void MissingCtor()
        {
            string source = """
                using System.Collections;
                using System.Collections.Generic;

                C x = [];

                class C : IEnumerable<int>
                {
                    public C(string s) { }
                    IEnumerator IEnumerable.GetEnumerator() => null;
                    IEnumerator<int> IEnumerable<int>.GetEnumerator() => null;
                    public void Add(int i) { }
                }
                """;

            CreateCompilation(source).VerifyEmitDiagnostics(
                // (4,7): error CS7036: There is no argument given that corresponds to the required parameter 's' of 'C.C(string)'
                // C x = [];
                Diagnostic(ErrorCode.ERR_NoCorrespondingArgument, "[]").WithArguments("s", "C.C(string)").WithLocation(4, 7)
                );
        }
```

**Comment by cston** [comment]
> I've also tested an `IEnumerable` scenario and verified that it errors as expected when the constructor we need isn't present

Should the collection expression be considered convertible to a type without the expected constructor though? The question affects overload resolution in particular.

For instance, should the call to `F([])` below be considered ambiguous or bind to `F(List<int>)`?
```csharp
using System.Collections;
using System.Collections.Generic;

abstract class AbstractCollection : IEnumerable<int>
{
    IEnumerator IEnumerable.GetEnumerator() => null;
    IEnumerator<int> IEnumerable<int>.GetEnumerator() => null;
    public void Add(int i) { }
}

class NoConstructorCollection : IEnumerable<int>
{
    private NoConstructorCollection() { }
    IEnumerator IEnumerable.GetEnumerator() => null;
    IEnumerator<int> IEnumerable<int>.GetEnumerator() => null;
    public void Add(int i) { }
}

class Program
{
    static void F(AbstractCollection c) { }
    static void F(NoConstructorCollection c) { }
    static void F(List<int> c) { }

    static void Main()
    {
        F([]); // ambiguous or F(List<int>)?
    }
}
```

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi [ImmutableList](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs) has a [CollectionBuilder] attribute so that's why it works. I was able to use it and it works as expected.

It shouldn't have such an attribute on net7.  What are you testing on?

**Comment by CyrusNajmabadi** [comment]
> Should the collection expression be considered convertible to a type without the expected constructor though?

The spec explicitly says that the type must have:

>  an applicable instance constructor that can be invoked with no arguments or invoked with a single argument for the 0-th parameter where the parameter has type System.Int32 and name capacity.

So it should not be convertible to such a type if it's missing that constructor.

**Comment by RikkiGibson** [comment]
Associated PR was merged so closing this out.
