### ISSUE TITLE
Completion doesn't offer `method` completion for class with a primary constructor

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#69535]
Trying to add `[method: ImportingConstructor]` to a class that uses a primary constructor, and having to fight the editor because it has hard-selected something else:
<img width="349" alt="image" src="https://github.com/dotnet/roslyn/assets/754264/fdeee993-a6ac-4ec9-bed8-ae2984d033c4">

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/Completion/KeywordRecommenders/MethodKeywordRecommender.cs

#Plzfixaussiefriend

**Comment by davidwengier** [comment]
I'm breaking into jail over code style aren't I...
