### ISSUE TITLE
Refactoring to new .cs doesn't open new file in Mac [macOS]

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#69589]
From vscode-dotnettools created by [claudiaregio](https://github.com/claudiaregio): microsoft/vscode-dotnettools#173  

### Describe the Issue

Only indication that refactored code has been turned into a new class is in the file explorer. It makes it difficult to see that a new .cs file has been created, and for users who do not have the file explorer open in the side panel, there is 0 indication that the refactoring has worked properly. 

### Steps To Reproduce

1. Create 'Test' class in Program.cs
2. Highlight class name, right click, select 'Refactor...' 
3. Select 'Move type to Test.cs' 
4. File is created in file explorer, but does not show up in the tab area 

In the screenshot below I created the Calculator class, and it took me a minute to realize the class was in fact created and it didn't fail, it just only showed up in the file explorer and not in the tab area of the editor. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/15915b7d-1c96-48b2-93ef-2ee0f45ecaa7)

### Expected Behavior

For the new file to be created and show up on VS Code's tab area

*Works as expected in Windows

### Environment Information

Apple M2 Pro
OS: Ventura 13.2.1
C# Dev Kit: v0.1.103
C#: v1.25.9
Intellicode for C# Dev: v0.1.9

**Comment by Cosifne** [comment]
Dup of https://github.com/dotnet/roslyn/issues/69638
Need to bring it to LSP and see what they said to move forward.
