### ISSUE TITLE
[BUG] Naming of "Create and assign field" is inconsistent between mac and windows

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#69592]
From vscode-dotnettools created by [NullRefer](https://github.com/NullRefer): microsoft/vscode-dotnettools#143  

### Describe the Issue

OS:Windows 11
vscode: 1.79.1

When add a new parameter in ctor, press `ctrl+.`, `_logger` the default field naming policy
![image](https://github.com/microsoft/vscode-dotnettools/assets/43956007/ff8ce8c6-7870-442f-87de-308df3f2d417)

OS: MacOs
vscode: 1.79.1

When add a new parameter in ctor, press `ctrl+.`, default field naming policy miss the _

![AE3E9BECB25AEE0AB3214358642439E7](https://github.com/microsoft/vscode-dotnettools/assets/43956007/da497f9c-88be-4a87-859c-cd12e0ac8d87)

### Steps To Reproduce

1. open vscode in macos(M1 pro chip)
2. add new parameter in ctor of whatever class
3. the naming of field miss the _

### Expected Behavior

The field name should begin with _

### Environment Information

- OS: windows 11 and MacOs
- vscode: 1.79.1
- C# extension:2.0.206, C# Dev Kit: 0.1.83

**Comment by Cosifne** [comment]
My test:
Windows:
<img width="582" alt="image" src="https://github.com/dotnet/roslyn/assets/24360909/b9a2f330-b4f7-4686-81da-b1ed59c4b6ad">
Mac:

<img width="852" alt="Screen Shot 2023-09-12 at 2 18 34 PM" src="https://github.com/dotnet/roslyn/assets/24360909/a82b162d-9e73-4c5d-bbb2-10428d98cae5">

Both project doesn't have .editorconfig.
@NullRefer
Could you see if the problem still repro with the newest version of the extension?
If so, could you also check if your project contains any editorconfig files specifying the naming convention?

**Comment by NullRefer** [comment]
@Cosifne Oh, my fault. I finally found the `editorconfig` in the windows project. I copy it to the project on mac, and it works. Thanks~

**Comment by CyrusNajmabadi** [comment]
Thanks for letting us know!
