### ISSUE TITLE
[SUGGESTION] Creating Constructor With All Fields Option Not Showing Anymore

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#69593]
From vscode-dotnettools created by [HBA114](https://github.com/HBA114): microsoft/vscode-dotnettools#106  

Type: <b>Feature Request</b>

Creating constructor with all fields in class option not showing anymore. There was a option before dev kit extension released.  Now adding all fields one by one is boring after some time.

Extension version: 2.0.206
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:28:44.251Z)
OS version: Linux x64 5.19.0-43-generic
Modes:

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  In VS i get the following:

![image](https://github.com/dotnet/roslyn/assets/4564579/1dd6e812-8125-47e0-aa9d-44ae86c5ec91)

In Devkit i get:

![image](https://github.com/dotnet/roslyn/assets/4564579/771f03be-b451-41c0-8d1b-9ed39fecd50e)

When i choose the first option i get:

![image](https://github.com/dotnet/roslyn/assets/4564579/85fa429e-0956-4af0-b38e-1f5266552f3d)

Which is as expected.  Would need a repro case to know what's going on.
