### ISSUE TITLE
Roslyn.Compilers.CompilerServer.UnitTests expects System.Collections.Immutable to have the wrong version

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn#696]
When 'System.Collections.Immutable' and 'System.Reflection.Metadata' don't exist in the working directory, it expects them to exist under the MSBuildToolsPath and to have the same version as the unit test assembly.

These files should either ignore the version check altogether or check against their correct version numbers.

A better solution may be to have a one time check to ensure VBCSCompiler.exe has the same version number (if it doesn't exist under the working directory) and assume the other files then have the correct version.

**Comment by jaredpar** [comment]
This should be fixed now.  Please re-open if this is still reproing for you.

**Comment by tannergooding** [comment]
This is still repro'ing, the `ResolveAssemblyPath` method still returns `null` for `System.Collections.Immutable` and `System.Reflection.Metadata` as they have different version numbers as compared to the executing assembly (`Roslyn.Compilers.CompilerServer.UnitTests.dll`).

**Comment by jaredpar** [comment]
@tannergooding this test is passing on all of our Jenkins machines and developer machines.  Can you provide an example of where this is causing a problem?

**Comment by tannergooding** [comment]
@jaredpar, The daily standalone runs, where we test the bits inserted into the latest build of VS (so files are picked up from MSBuild\14.0\Bin, Common7\IDE\PrivateAssemblies, and Common7\IDE\CommonExtensions), as compared to the Jenkins or developer machines, which test the build itself (all files are in the working directory).

**Comment by jaredpar** [comment]
@tannergooding I need more information here.  How does that impact the running of our unit tests (they run against our built binaries)?  

Are our unit tests regularly run against binaries that are produced elsewhere?  If so how is this environment setup?

**Comment by tannergooding** [comment]
@jaredpar, For our daily standalone tests, we take all of our tests and their dependencies, copy them to the test machine and then strip away everything that is inserted into VS (S.C.Immutable, S.R.Metadata, csc.exe, M.CodeAnalysis.*, etc...).

Binding redirects are provided so that the tests will pick up the inserted binaries instead (specifically, we provide CodeBase resolvers in the executable configuration file that forces the assembly resolution service to also look for the binaries at their inserted location).

Several of the tests, such as the CompilerServerUnitTests, explicitly load their dependencies and will check for them in their inserted location. The CompilerServerUnitTests does this via the `ResolveAssemblyPath` method (see below). However, as is, it returns `null` for System.Collections.Immutable (version=1.1.34.00) and System.Reflection.Metadata (version=1.0.19.0) because they have  a different version number from the Unit Test Assembly (today is version=1.0.0.50510).

``` C#
private static string ResolveAssemblyPath(string exeName) 
{ 
    var path = Path.Combine(s_workingDirectory, exeName); 
    if (File.Exists(path)) 
    { 
        return path; 
    } 
    else 
    { 
        path = Path.Combine(MSBuildDirectory, exeName); 
        if (File.Exists(path)) 
        { 
            var currentAssemblyVersion = Assembly.GetExecutingAssembly().GetName().Version; 
            var loadedAssemblyVersion = Assembly.LoadFile(path).GetName().Version; 
            if (currentAssemblyVersion == loadedAssemblyVersion) 
            { 
                return path; 
            } 
        } 
        return null; 
    } 
} 
```

**Comment by davkean** [comment]
Dropping infrastructure as this is a compiler product test.

**Comment by gafter** [comment]
This is over a year old. Closing. Please reopen if you believe this issue still exists.
