### ISSUE TITLE
Interface implementations don't inherit default members

### ISSUE THREAD

**Issue by Monniasza** [dotnet/roslyn#69601]
**Version Used**:
Visual Studio 2022 v17.7.1

**Steps to Reproduce**:
1. Copy https://gist.github.com/Monniasza/ed15f4e9ef44e3e88a79eaeb68d34f61 into [sharplab](https://sharplab.io/)

**Diagnostic Id**:
CS0103

**Expected Behavior**:
The interface implementation inherits default members

**Actual Behavior**:
The interface implementation doesn't inherit default members

**Comment by CyrusNajmabadi** [comment]
This is expected.  You can cast 'this' to the interface type to call the impls.  Similar to if you'd explicitly implemented certain interface members.

**Comment by Monniasza** [comment]
Maybe it could be made so interface implementation inherit default methods, like this.
It would have to be made in the C# language repo
```
interface I{public void M0(){}}
class C: I{
  public void M1() => M0();
}
```

**Comment by Monniasza** [comment]
I'll work around like that:
```
interface I{public void M0(){}}
class C: I{
  private readonly I that = this;
  public void M1() => that.M0();
}
```
