### ISSUE TITLE
Bump version of ICSharpCode.Decompiler to 8.1.0.7455

### ISSUE THREAD

**Issue by andrewcrawley** [dotnet/roslyn#69613]
The Visual Studio debugger uses the version of ICSharpCode.Decompiler provided by Roslyn.  We'd like to get that dependency updated to version 8.1.0.7455 so we can take advantage of a handful of bug fixes in the most recent version.

I've verified that there are no breaking changes in the decompiler APIs that the debugger uses between the currently-shipping version and the latest release.

We'd like to get this done in the 17.8p2 timeframe, so we have time to respond to any issues that might arise.

**Comment by arkalyanms** [comment]
Our current Mantis can help review as well. Starting with @tmat for the debugger perspective first.
