### ISSUE TITLE
Analyzer summary should show suppressor ID

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69628]
![image](https://github.com/dotnet/roslyn/assets/31348972/c6a67cae-ba38-4555-afbb-1048acd1a8be)

Currently, only `DiagnosticAnalyzer.SupportedDiagnostics` is handled. However, `DiagnosticSuppressor.SupportedSuppressions` is not.

The support to show diagnostic IDs was added in https://github.com/dotnet/roslyn/pull/51696. This PR should help a community contributor to know where he should look into :)

**Comment by SimonZhao0512** [comment]
Hi, I am a first time contributor. Currently a front end dev, love c#. I want to tackle this issue, may I?

**Comment by mavasani** [comment]
@SimonZhao0512 Definitely, go for it.
