### ISSUE TITLE
Unable to invoke quick fix for some suggestions

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#69636]
Repro: 

1. Checkout github.com/dotnet/sourcelink at commit 757cc4caca83175e3fb8e87c73cd5f34743cb143 and open SourceLink.sln.
2. Open `src\Microsoft.Build.Tasks.Git\GitDataReader\GitConfig.cs`, go to method `GetVariableValue`.
3. Notice a suggestion:
 
![image](https://github.com/dotnet/roslyn/assets/41759/f9d1ba5e-5676-4d6f-82c5-bff98c5ee86c)

4. The refactoring is not listed in the context menu:

![image](https://github.com/dotnet/roslyn/assets/41759/c3400718-8031-4b08-976a-481294ae7f1d)

5. Light bulb displays a different set of actions:
![image](https://github.com/dotnet/roslyn/assets/41759/a543a5cd-dc3a-4541-ab59-e9e313d0e19f)

6. Depending on the exact hover location "Show potential fixes" might not be displayed:
![image](https://github.com/dotnet/roslyn/assets/41759/830f33bc-c4d7-40b6-b67b-25a0b53aecf7)

**Comment by CyrusNajmabadi** [comment]
Odd, this doesn't repro for me:

![image](https://github.com/dotnet/roslyn/assets/4564579/d81e88d0-3156-4ef1-81d9-40989d1f5bbf)

Investigating further.

**Comment by CyrusNajmabadi** [comment]
Also works from teh ... itself:

![image](https://github.com/dotnet/roslyn/assets/4564579/245d8381-a6fb-4f84-ae80-33d240a0c091)
