### ISSUE TITLE
Support names in dictionary declarations

### ISSUE THREAD

**Issue by comdiv** [dotnet/roslyn#6964]
Due to #6673 became some case of holy war I split it to more localized issues.

Now:
In anonymous class definition we always use NAMES at key side while them always treated as memeber names:
`new { x = 1}`

In class initializers we use NAMES at key side
`new  { x= 1}`

But in Dictionary initializer we never got such sugar:
`new D<s,o>{ ["x"] = 1}` we even not allowed to use `{ "x" = 1}` as in JSON or `{ x= 1}` as in initializers (because in theory it could be conflict with some of D<s,o> member names.

What problems could be

1) If it interfere with some D member `new D<s,o>{ Count = 2 }` compiler can investigate it at compile time and make Warn or Error; alternate : see at #6963 - u can implement it that way that ':' ALWAYS are treated as dictionary set operator in Dictionary ctor. So if you write `new X{ MyField: 2}` - it is well and `new X{ MyField = 2 }` too. But in dictionaries we HAVE to use JS-like syntax `new D<s,o>{Count :2 }` that will be compiled same way as `new D<s,o>{ ["Count"] = 2 }`

2) What about scope iference

```
var x = 1;
object a = new  { x = x }; //anonymous class and noone have think that its {1 = 1} declaration
var d = new Dictionary<string,object>{ ["x"] = x } ;; //all good
//suggested syntax
var newd = new Dictionary<string,object>{ x : x }; // may be it is { "1" : 1} 
//may be better to always-string as JSON
new newjd = new Dictionary<string,object>{ "x" : x };
```

I think it's not really problem - in anonymous classes and in JS we never misunderstood where it's name and where it's reference. So `var x=1;var newd = new Dictionary<string,object>{ x : x };` will always be exactly `var x = 1;var newd = new Dictionary<string,object>{ "x" : x };` and in current syntax it is exactly `var x = 1;var newd = new Dictionary<string,object>{ ["x"] = x };` i don't see any reasone to think something else about it.

In context of  #6673
This issue + #6963 make C# backward compatible with dictionary initializers in JS and JSON so - working with RESTFul APIs , ES, Mongo and so on will became much simpler

**Comment by HaloFour** [comment]
This would be a breaking change to the existing object initializer syntax.  This proposal could not stand on its own as a result.

**Comment by alrz** [comment]
I don't know why there are two kind of syntax for exactly the same thing, an identifier `x` and a string `"x"` shouldn't be the compiler smart enough to know my intent?

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
