### ISSUE TITLE
Web Application with specific config not analysed by MsBuildWorkspace

### ISSUE THREAD

**Issue by FBryant87** [dotnet/roslyn#69654]
When I open a solution like so:

```
MSBuildLocator.RegisterDefaults();

using (var workspace = MSBuildWorkspace.Create())
{
  var solution = await workspace.OpenSolutionAsync(@"mySolution.sln");
}
```

All projects with their references are analysed, **except Web Application** projects with specific configuration. These are still listed in `solution.Projects`, but none of the detailed data is loaded for example, the list of project references.

![image](https://github.com/dotnet/roslyn/assets/10852751/485071dc-1539-462a-9a9a-d685b8d41611)

I've narrowed it down and this only occurs for Web Applications with the following config in their .csproj:

`<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" />`

**Comment by FBryant87** [comment]
Seems to work so must be something specific to my own solution.

**Comment by JoeRobich** [comment]
Hmm. I would expect a .NET Framework build to be able to load your WebApplication, since it will use the Visual Studio MSBuild tools which typically includes the necessary build targets. .NET Core builds use the MSBuild from a .NET SDK which wouldn't include WebApplication support.

Does your project file include lines similar to the following?
```xml
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">17.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
```

**Comment by FBryant87** [comment]
You're on the right track yes, project contains this:

```
<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" />
```

So `MSBuildLocator.RegisterDefaults()` is finding the MsBuild path as:

`C:\Program Files\dotnet\sdk\7.0.306\`

And therefore it looks for the targets here:

`C:\Program Files\dotnet\sdk\7.0.306\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets`

But the targets are actually here:

`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets`

Just trying to think how best to proceed

**Comment by JoeRobich** [comment]
MSBuildLocator should not be locating a MSBuild SDK when targeting .NET Framework. It should only be returning VS instances of MSBuild. If you are seeing this behavior, then you should open an issue against MSBuildLocator.
