### ISSUE TITLE
Invalid "Remove Unnecessary Cast" code fix for null-initialized implicitly typed array

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#6966]
I'm creating an implicitly typed array and `null`-initialize it with some values. To have a type for the array, one of the `null`s needs to be cast, but VS insists the cast is invalid, while the code fix already shows the red error squgglies.

![invalidcast](https://cloud.githubusercontent.com/assets/1947968/11333632/7b35974c-91cf-11e5-853c-16bb4f04734f.png)

**Comment by dpoeschl** [comment]
Hi @Tragetaschen -- can we see a couple lines of surrounding code for your example, including the full definition of ```Something```? When I try ```var something = new[] { (object)null, null, null };``` I do not see the cast as unnecessary. However, the cast is marked as unnecessary if I put an incomplete statement before that:
```
var stuff = 
var something = new[] { (object)null, null, null };
```

Also, I'm confused about ```Something``` being implicitly typed in your example -- is the ```var``` on the previous line? I don't see it next to ```Something``` in the diff window.

**Comment by Tragetaschen** [comment]
I'm in an anonymous type definition:

``` csharp
object Function()
{
    return new
    {
        Something = new[] { (object)null, null, null, null },
    };
}
```

**Comment by leppie** [comment]
Related #6309

**Comment by DustinCampbell** [comment]
Hmmm... this really isn't related to #6309 other than it's a remove redundant cast bug. The fixes required to that system are very different.
