### ISSUE TITLE
The code coloring is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69660]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-code-coloring-is-wrong/10446950)._

---
[severity:Other]

                var runtime = (end - start).TotalMilliseconds / 1000.0;
                const string dateFormat = @"yyyy.MMdd HHmmss";
                // ReSharper disable once UseFormatSpecifierInInterpolation
                runTime.Text = $@"RunTime = {runtime}s at {end.ToString(@"yyyy.MMdd HHmmss")}";
                runTime.Text = $@"RunTime = {runtime}s at {end.ToString(dateFormat)}";

![image](https://github.com/dotnet/roslyn/assets/1408396/35d9c24f-f5f6-4ef8-96be-d0b3a4205c02)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This appears to be by design. The two characters marked in the image have been faded by the IDE0071 diagnostic as unnecessary code.

**Comment by CyrusNajmabadi** [comment]
Agreed.  You can convert this to `{end:yyyy.MMdd HHmmss}` which is what the feature is recommending.
