### ISSUE TITLE
Required project reference when using transitive source generator dependencies

### ISSUE THREAD

**Issue by msedi** [dotnet/roslyn#69668]
Visual Studio 17.8.0 Preview 1.

A similar issue was report here: https://community.sonarsource.com/t/bug-c-source-generators-sonarqube-scanner-cause-build-to-fail/70955/3 and here https://turnerj.com/blog/the-pain-points-of-csharp-source-generators.

I have a source generator (`VMSourceGeneration`) that needs a `MappingMode` enum, which the source generator uses internally, but also needs to be visible to the user of the generator. Since the generator cannot use its own created MappingMode, I have shifted the `MappingMode` to an additional assembly (`VMSourceGeneration.Assets`).

The source generator is dependent on `VMSourceGeneration.Assets.csproj` and it all looks good so far. I have added 

```
	<ItemGroup>
		<!-- Pack the generator dll in the analyzers/dotnet/cs path -->
		<None Include="$(OutDir)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

		<!-- Pack the attributes dll in the analyzers/dotnet/cs path -->
		<None Include="$(OutDir)\VMSourceGeneration.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

		<!-- Pack the attributes dll in the lib\netstandard2.0 path -->
		<None Include="$(OutDir)\VMSourceGeneration.Assets.dll" Pack="true" PackagePath="lib\netstandard2.0" Visible="true" />
	</ItemGroup>
```

so that the package is created such that it supports the `MappingMode` in the analyzer as well as during the build. The problem is though that during debugging, when I do not use the nuget package, but use project references instead, I also need to reference the transitive dependency VMSourceGeneration.Assets.dll. Otherwise the source generator does not produce code.

Is this a known behaviour?

**Comment by jcouv** [comment]
This doesn't feel like a compiler issue, but likely a custom build setup problem. To be able to assist, we'd need to see a minimal repro project(s).

**Comment by msedi** [comment]
@jcouv. My colleague has prepared already an example which I haven't recognized. Please see the issue in #69897. If it's OK for you, we could close this one.
