### ISSUE TITLE
FindReferencesAsync() not finding references if dependencies are transitive

### ISSUE THREAD

**Issue by FBryant87** [dotnet/roslyn#69679]
Produced in Visual Studio 2022 - .NET 7 framework

If ProjectA references a class in ProjectB:

```
//code in ProjectA
var bClass = new BClass();
```

I'd assume the following code would find this reference to BClass in the locations:

```
var symbol = compilation.GetSymbolsWithName("BClass").Single();
var symbolReferences = await SymbolFinder.FindReferencesAsync(symbol, solution);
```

But this will only be the case if ProjectA **explicitly references** ProjectB within its .csproj:

<ProjectReference Include="..\ProjectB.csproj" />

If the reference is transitive and ProjectA gets its reference to ProjectB through some other project, then `FindReferencesAsync()` will not detect ProjectA's use of BClass.

This is quite misleading because ProjectA explicitly mentions BClass.

**Comment by CyrusNajmabadi** [comment]
This is correct behavior.  Absent a direct reference, the type's from project B cannot be used in project A, and the compiler will warn and tell you to add a direct reference.

**Comment by FBryant87** [comment]
Thank you for clarifying Cyrus. In my test project I have:

`var bClass = new BClass();`

There is no warning and ProjectA.csproj contains no reference to ProjectB (it gets it through another). Is this issue only experienced at runtime?

**Comment by CyrusNajmabadi** [comment]
it sounds like you may have some msbuild setting/feature which applies transitive reference (making them direct references).  However you setup your roslyn workspace, you'll need to do the same.

**Comment by CyrusNajmabadi** [comment]
Put another way, if you do this in VS (not through teh FindRefs api) does it find the symbol?  If so, then the project system actually setup a direct reference.  and however you're setting up the workspace will need to do the same.

**Comment by FBryant87** [comment]
This is with the standard .NET 7 template (which uses transitive project references by default) - the reference is not found in VS.

If I were to disable these, it would immediately demand an explicit reference correct:
`<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>`

It feels a little strange because transitive references are a project structuring concern (and this is the default use of them). For `FindReferencesAsync()` to miss 'mentions' of symbols because of how a reference happened to pass between transitive projects is likely to confuse.

**Comment by CyrusNajmabadi** [comment]
> It feels a little strange because transitive references are a project structuring concern (and this is the default use of them). For FindReferencesAsync() to miss 'mentions' of symbols because of how a reference happened to pass between transitive projects is likely to confuse.

This is how hte language/compiler works.  Without a direct reference, the symbol cannot be referenced.  So find-references doesn't look there.

This is also a large part of how we can ensure that find-refs is fast.  If we have to start searching all transitive deps (even though it would not be legal to reference the symbol), then that would be a big perf hit, only to find results that can only appear in error conditions.

**Comment by FBryant87** [comment]
That is a meaningful explanation, thank you. Short of disabling transitive project references in all my source projects (so that explicit references are always included), is there anything I can do to instead get the Workspace to bring these references into account?

(in other words, is there a solution which leaves the code being analysed unchanged)

**Comment by CyrusNajmabadi** [comment]
>  is there anything I can do to instead get the Workspace to bring these references into account?

how are you constructing your workspace?

**Comment by FBryant87** [comment]
With a simple:

```
MSBuildLocator.RegisterDefaults();
using var workspace = MSBuildWorkspace.Create();
var solution = await workspace.OpenSolutionAsync(path);
```

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski any reason why MSBuildWorkspace would not be applying transitive references properly when used programmatically? 

Basically, this all sounds like something has setup the workspace wrongly.  Once things are good FindRefs should just work.

**Comment by FBryant87** [comment]
Just for further context after creating the solution I'm just grabbing a project and loading the symbol:

```
var compilation = await project.GetCompilationAsync();
var symbol = compilation.GetSymbolsWithName("BClass").Single();
var symbolReferences = await SymbolFinder.FindReferencesAsync(symbol, solution);
```

3 projects (A, B and another which carries the reference between A and B). All .NET 7 with default csproj files.

**Comment by jasonmalinowski** [comment]
> any reason why MSBuildWorkspace would not be applying transitive references properly when used programmatically?

It's possible we have a bug here, although given the feature isn't new I'd be surprised if we are entirely busted there.

@FBryant87: just to confirm if you look at Project A's ProjectReferences collection you don't see the reference to B? Otherwise the one thing to check might be to subscribe to MSBuildWorkspace.WorkspaceFailed _before_ you call OpenSolution and see if that is raised due to some underlying failure.

**Comment by FBryant87** [comment]
Ah good shout thank you both - subscribing to WorkspaceFailed allowed me to see than an unrelated package was failing to load. Might be worth considering whether it makes sense for developers to explicitly say they don't want those failures to throw just in case they miss them.

All symbols now found perfectly!

**Comment by FBryant87** [comment]
In my case although all projects were loaded into the workspace, it seems some of them only retrieved partial information such as the reference list of ProjectA. This was due to my analyser project missing a NuGet.Frameworks package.

It's one of those which is easy to miss because everything looked correct - it was only the fact I was writing tests around specific references which caught it

**Comment by jasonmalinowski** [comment]
What was the error? Did it look like https://github.com/dotnet/roslyn/issues/61454?
