### ISSUE TITLE
Allocation issues in SplitRawLineIntoFormattedLines

### ISSUE THREAD

**Issue by ProfFrugal** [dotnet/roslyn#69675]
**Version Used**:  Visual Studio 2022

**Steps to Reproduce**:

1. Capture a trace
2. Do a decompilation operation
3. Check for allocation stacks

Issue: extra allocations in SplitRawLineIntoFormattedLines:

                          private static void SplitRawLineIntoFormattedLines(
                              string line, ArrayBuilder<string> lines)
                          {
                              var indent = new StringBuilder().Append(' ', s_indentSize * 2).ToString();
              
762.9K|                       var words = line.Split(' ');
                              var firstInLine = true;
              
                              var sb = new StringBuilder();
                              sb.Append(indent);
                              foreach (var word in words)
                              {
                                  // We must always append at least one word to ensure progress.
                                  if (firstInLine)
                                  {
                                      firstInLine = false;
                                  }
                                  else
                                  {
                                      sb.Append(' ');
                                  }
              
211.9K|                           sb.Append(word);
              
                                  if (sb.Length >= s_wrapLength)
                                  {
110.4K|                               lines.Add(sb.ToString());
                                      sb.Clear();
109.8K|                               sb.Append(indent);
                                      firstInLine = true;
                                  }
                              }
              
315.2K|                       if (sb.ToString().Trim() != string.Empty)
                              {
322.3K|                           lines.Add(sb.ToString());
                              }

Ident is a constant, sb.ToString is called twice at the end. The text should fit in single line so split and StringBuilder should not be needed in most cases. Refer to: https://frugalcafe.beehiiv.com/p/fc33-visual-studio-decompilation-seems-pause

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/69677.
