### ISSUE TITLE
MissingMethodException for init setters

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/roslyn#69678]
MissingMethodException for init setter.

**Version Used**: dotnet sdk 8.0 preview 7

**Steps to Reproduce**:

I have a repro here, having 3 projects (without having to dump library IL) seems to be required.
https://github.com/NinoFloris/MissingMethod

Take note of the two tfms in InitDefine.
If that's changed to just ns2.0, meaning the project chain is `ns2.0 <- ns2.0 <- net8.0` (i.e. `InitDefine <- ReferenceInit <- Repro`) everything works.
Once it's `{ net8.0, ns2.0 } <- ns2.0 <- net8.0` runtime missing method exceptions show up. 
There are no compiler or sdk errors.

**Comment by svick** [comment]
What worked for me in a similar situation is to forward the definition of `IsExternalInit` to the runtime in cases where it exists. I.e. change [the code](https://github.com/NinoFloris/MissingMethod/blob/406afd/InitDefine/Class1.cs) to (assuming it's moved to its own file):

```c#
#if !NET5_0_OR_GREATER
namespace System.Runtime.CompilerServices
{
    static class IsExternalInit { }
}
#else
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(IsExternalInit))]
#endif
```
