### ISSUE TITLE
Consider move length-based string dispatch behind /optimize

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69674]
This is a request to only enable the optimization from https://github.com/dotnet/roslyn/pull/66081 when `/optimize` flag is provided. Based on observations in [AB#1874059](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1874059), this feature can be costly, and it may be good to avoid it in common IDE/debugging scenarios.

Additional work to improve the compile-time performance of the optimization is submitted in #69673.

**Comment by jcouv** [comment]
@jaredpar I'll plan to do this in 17.9. Let me know if you have any concerns
