### ISSUE TITLE
Usings do not collapse in C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69685]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Usings-do-not-collapse-in-C/10445826)._

---
[severity:It bothers me. A fix would be nice]
Collapsing usings does not work in C#. I have selected "Enter outlining mode when files open" and "Collaps usings on file open". Restarting VS after changing the settings did not change the behavior.

---
#### Feedback Bot on 8/21/2023, 07:33 PM: 

(private comment, text removed)
#### Feedback Bot on 8/23/2023, 11:32 AM: 

(private comment, text removed)
#### Cyrus Najmabadi [MSFT] on 8/23/2023, 11:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We're unable to repro this.  We need an example from the user for wherre this is happening.

**Comment by Jerunnon** [comment]
Hi,

I have the same issue. 

![Image](https://github.com/user-attachments/assets/883a5914-18d9-4d91-b467-6c465355f0d2)

I have selected the option, but when I open a new cs file, the usings are sometimes collapsed and sometimes not.
