### ISSUE TITLE
Only run Source-Generator driver in external process.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#69694]
Our current design for generating sourcegenerator docs violates specific principles around our checksum'ed based synchronization story.

Specifically, while we effectively can synchronize the user's code, references, and options between processes, we don't use the same system for source-generator docs.  Instead, we run generators in both processes, assuming that they must produce the same results, and thus can be referenced uniformly between processes.  While this would be an aspect of a well-written generator, it is not something that can be enforced.  As such, our synchronization story is dependent on user code, out of our control, which may not abide by the invariants we depend on.  

This is already the source of many reported issues where one process refers to a generated doc that is either missing in the other process, or which has different contents.

To resolve this, we intend to make the following change:

1. Instead of computing SG docs in both processes (specifically, using a generator-driver in both processes), we will only truly generate the docs in the OOP server.
2. If the host process needs to get the generated documents (for example, if a local feature needs it, or some client just calls GetSourceGeneratedDocumentsAsync on the project itself), it will call out to the server to get the documents from it.

For efficiency, the host won't directly ask for all the SG documents from the OOP process.  Instead, it will ask for the list of document-ids, and document-state-checksums.  Similar to normal syncing, those ids/checksums will be compared to those cached locally (from the prior project state).  Any that are the same can be used directly from the prior state.  Any that are gone can be removed.  And any that are new or changed can have their contents then be queried from the OOP process doing the expensive sync only for those.

With this change, it will always be the case that the host and server agree on the SG doc contents for any particular solution snapshot.  Messages referring to these documents that happen in either direction will always be sure to succeed at that point.

**Comment by jasonmalinowski** [comment]
Another big advantage of this: now that our OOP is .NET Core, we can handle generator loading/unloading which we can't do today.

**Comment by CyrusNajmabadi** [comment]
That would be great. I will work with you to potentially expose this (both automatically, or through a user gesture)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/69917.

**Comment by sharwell** [comment]
The original fix was reverted, but this was finally fixed with #70109
