### ISSUE TITLE
Unreachable code should be faded out, code fix should remove all unreachable code

### ISSUE THREAD

**Issue by tvsonar** [dotnet/roslyn#6970]
CS0162 reports unreachable code on the first unreachable token. It should report on the whole block of unreachable code (rest of the method, or test of the loop, ...).

At the same time, all the unreachable code should be removed by the codefix, not only the first unreachable statement.

**Comment by dpoeschl** [comment]
Hi @tvsonar, a quick question about this part:

> At the same time, all the unreachable code should be removed by the codefix, not only the first unreachable statement.

I don't believe we ship a fix that removes even the first unreachable statement in this case. Are you seeing this fix available? Have you installed any other extensions that may be adding this to the list?

+Compiler team for the request that the diagnostic report the whole block, 
+IDE team for the codefix suggestion

**Comment by tvsonar** [comment]
Sorry, my bad, I've got many tools installed: SonarLint, CodeCracker, RefactoringEssentials, CSharpEssentials. It seems to be CodeCracker that implements the codefix.

But in any case, fading the full error location would allow tool developers to provide a better fix without needing to do a control flow analysis again.

**Comment by DustinCampbell** [comment]
Yeah, we've meant to do this for quite awhile. We should totally just do this and add a fix for it.

**Comment by Pilchie** [comment]
Assigning to @CyrusNajmabadi since he took a stab at it while on a plane ride...

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/20236

**Comment by StingyJack** [comment]
@CyrusNajmabadi - is it possible to configure the darkness of the faded text? (I went through the commits in that PR and some of the related files to see what entry this might be represented as in the Fonts and Colors config panel but I'm not seeing anything that looks right or even close.)
