### ISSUE TITLE
Collection expressions: conversion error reported for spread of `dynamic` type

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#69704]
**Version Used**:  e85f97f5

**Steps to Reproduce**:

Compile:
```csharp
class Program
{
    static void Main()
    {
        dynamic x = new[] { 2, 3 };
        int[] y = [1, ..x]; // error: cannot convert from 'object' to 'int'
    }
}
```
**Expected Behavior**:
Compiles and runs successfully.

**Actual Behavior**:
```
(6,23): error CS1503: Argument 1: cannot convert from 'object' to 'int'
```

**Comment by jcouv** [comment]
@cston Which milestone do you want this in? Does this need any dynamic runtime work?

**Comment by cston** [comment]
> Does this need any dynamic runtime work?

No, this shouldn't require runtime changes. The corresponding `foreach (var i in x) { ... }` compiles and runs successfully.

**Comment by cston** [comment]
The behavior in the repro is currently by design. The *iteration type* of a spread element with an expression of `dynamic` type or `IEnumerable` type is considered to be `object` rather than untyped.

Added tests for these cases in https://github.com/dotnet/roslyn/pull/71158.

cc @CyrusNajmabadi
