### ISSUE TITLE
Provide a knob for overridden members to keep showing in the editor's `override` menu.

### ISSUE THREAD

**Issue by jozkee** [dotnet/roslyn#69713]
## Summary

Would be nice that members overridden by generated code wouldn't affect the override dropdown menu of the editor.

## Background and Motivation

I'm working on a source generator that is meant to fill gaps in `Stream` implementations with boilerplate So Stream can be more user-friendly, and can guide users to implement Span-based and Task-based members (or any other members that are alignemd with "the current meta").

So for example if a user has the following code:
```cs
[GenerateStreamBoilerplate]
public partial class MyStream : Stream 
{ 
    public override int Read(byte[] buffer, int offset, int count)
    {
        // do something
        return 0;
    }
}
```

We will generate the following:
```cs
partial class MyStream
{
    public override bool CanRead => true;
    public override bool CanSeek => false;
    public override bool CanWrite => false;

    public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
    {
        ValidateBufferArguments(buffer, offset, count);
        EnsureCanRead();
        
        return Task.Run(() => Read(buffer, offset, count), cancellationToken);
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
        throw new NotSupportedException("Stream does not support writing.");
    }

    public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
    {
        throw new NotSupportedException("Stream does not support writing.");
    }

    // The rest of members generated are omitted for brevity.
}
```

We will also emit a diagnostic saying "'MyStream' does not implement any ReadAsync method and hence is doing async-over-sync".

Therefore we would like some of the generated members to still be shown in the override dropdown menu for the following reasons: 
* Users can still enjoy the UX provided by the editor
* The code we provide is boilerplate and hence we don't want to discourage them from discovering the overridable members, especially the ones we just generated to reflect the not-supported operation.

## Proposed Feature

Similar to `EditorBrowsable`, an attribute could be provided to signal that said members can still be overridden.

**Comment by Rekkonnect** [comment]
So if I understand correctly, based on your example above, you want an attribute that when placed on an overridden member, it is still reckoned as "not filled", and available as an option when auto-filling the override. Therefore, slapping that attribute on your `CanRead` would result in `CanRead` showing up in all other partial declarations of the same type, except for the one where you are getting it generated. It would assume that whoever is producing the source is accountable for keeping track of the overridden member being overridden only once, be it manually, or the source generator not writing the override.

I've also noticed this slight gap with boilerplate source generators, it would often happen that I wanted to override a member manually and the editor wouldn't provide it to me as a suggestion, and I would have to manually override it. I support this idea.

**Comment by Jozkee** [comment]
> It would assume that whoever is producing the source is accountable for keeping track of the overridden member being overridden only once, be it manually, or the source generator not writing the override.

Correct, in my case I keep track of what's overridden on non-generated code and generate only what's not.

**Comment by CyrusNajmabadi** [comment]
Haven't heard this request, and this is a lot of complexity for what seems like a narrow scenario.  Closing out as not planned.
