### ISSUE TITLE
IDE0200 on mutable read-only property is invalid

### ISSUE THREAD

**Issue by AliveDevil** [dotnet/roslyn#69717]
**Version Used**: Visual Studio 2022 17.7.1, .NET Framework 4.7.2 & .NET 7.0

**Steps to Reproduce**:

1. Create readonly-lambda property, referencing a field, which has a holder property
2. Create lamba on a method of that property
3. Observe IDE0200, applying that consequently throws NullRef error, as that property hasn't been initialized yet

```
using System;

public class Repro
{
    private readonly Holder<External> holder;
    
    public External External => holder.Value;
    
    public Repro()
    {
        holder = new Holder<External>();
        Factory(() => External.Handler()); // IDE0200
        Factory(External.Handler); // NullReference Exception
    }
    
    private static void Factory(Action action)
    {
        // nop
    }
}

public class Holder<T>
{
    public T Value { get; set; }
}

public class External
{
    public void Handler()
    {
    }
}
```

[Roslyn-69717.zip](https://github.com/dotnet/roslyn/files/12441110/Roslyn-69717.zip)

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQAxAHYCuANhQIbAUwAEAJgJYDOt9hhGAzA9gYAlGAAcoEQgG9CDOQ3EsAbtQAujWNSYQSFAJ4MAEhApMYUADwBRBOqglqFAHwMAFibNQA3LPm+5fAw2dg4UQbbmoQwAvC7upuYAdABqjmQwPgTyDP4C/CLiEAAUAJS5MlnZ8vGeMQwkMADuRh7m1hH2jk6lmVXyAGLUYKrQekWlMS7BkY6JhtQkTPRQpSVeDAD0GwwAkgAiVgAMWIeHudmDw6NF050UcwtL5mub2wBylBQiAGbmMCRgRg2QGiVQsHS5AC+uVyihU6gEOCQAhQDEuIygYwwOCwDCGYJ0ZUqcgqfTkW3qEFEUMI0IIPH4gmMCUsABUnNJcoFWQxUhR0gwpAwAOYwVTrNhi9Z0ukMgS426hTnEvIooyPZalco0gh0oA)

**Diagnostic Id**: IDE0200

**Expected Behavior**:
Don't apply IDE0200 to any property reference at all, or provide wrapping method over the property

**Actual Behavior**:
IDE0200 is applied, thus results in nullreference exception

**Comment by CyrusNajmabadi** [comment]
Could you supply the actual repro code here?  Thanks!

**Comment by AliveDevil** [comment]
Sure thing.

Added repro zip, and repro code.

**Comment by CyrusNajmabadi** [comment]
In this case, it's likely worthwhile to just disable this analyzer here.  This is def an uncommon case where the code depends on either no-op'ing, or a later operation *making* the lambda legal . As this is an uncommon pattern, suppressing in the rare case is better than disabling for all the cases where this remains sensible.

**Comment by AliveDevil** [comment]
Well, in this specific case I didn't do anything, for sake of clarity - the called method could invoke or store the action.
The real scenario here is used in combination with ReactiveUI and ObservableAsPropertyHelper, though the repro is the most basic example of this instance - which relies on lazy initialization of that properties return value.

Thanks for taking the time to look into this.
