### ISSUE TITLE
"Convert to interpolated string" code fix doesn't remove `ToString`

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#69721]
**Version Used**: Visual Studio Version 17.8.0 Preview 1.0

**Steps to Reproduce**:

In this code, applying the "Convert to interpolated string" refactoring:
```c#
struct ValueTuple<T>
{
    public T Item1;
    public T Item2;

    public override string ToString()
    {
        return "(" + Item1.ToString() + ", " + Item2.ToString();
    }
}
```
results in:
```c#
struct ValueTuple<T>
{
    public T Item1;
    public T Item2;

    public override string ToString()
    {
        return $"({Item1.ToString()}, {Item2.ToString()}";
    }
}
```
I think the `ToString` calls should be removed since they're unnecessary. They should also be removed in case of `Item1?.ToString()`.

**Comment by CyrusNajmabadi** [comment]
They should be left in as that's how they were in teh original code (where the user could have removed them as well).    This is also because there are different perf implications here (boxing vs non-boxing), etc.

**Comment by Neme12** [comment]
Why would there be any boxing?

**Comment by Neme12** [comment]
The user could have used `ToString` in the original code to avoid boxing, but that's not needed anymore in the interpolated string version, where there shouldn't be any boxing.

**Comment by CyrusNajmabadi** [comment]
> Why would there be any boxing?

Emits as:

```c#
	IL_0000: nop
	IL_0001: ldstr "({0}, {1}"
	IL_0006: ldarg.0
	IL_0007: ldfld !0 valuetype ValueTuple`1<!T>::Item1
	IL_000c: box !T
	IL_0011: ldarg.0
	IL_0012: ldfld !0 valuetype ValueTuple`1<!T>::Item2
	IL_0017: box !T
	IL_001c: call string [mscorlib]System.String::Format(string, object, object)
	IL_0021: stloc.0
	IL_0022: br.s IL_0024

	IL_0024: ldloc.0
	IL_0025: ret
```

**Comment by CyrusNajmabadi** [comment]
Reactivating.  We could potentially do this if we know that the compiler will not box.  As long as we can replicate the same check they do without issue, this seems fine.

**Comment by Neme12** [comment]
Well only if you don't have `DefaultInterpolatedStringHandler`. If you do, the version without calling `ToString` should actually be better perf-wise because many primitives implement `ISpanFormattable` and can format themselves without allocating an intermediate string.

**Comment by CyrusNajmabadi** [comment]
Seems like a good candidate for an analyzer/fixer.

**Comment by Neme12** [comment]
Should such an analyzer be here or in dotnet/runtime? On the one hand, it's simplifying code that uses a relatively new language feature, which makes me think roslyn, but on the other hand, it's about perf, which makes me think dotnet/runtime.

**Comment by CyrusNajmabadi** [comment]
it shoudl be in roslyn-analyzers.
