### ISSUE TITLE
"Make struct readonly" isn't offered in case of an empty struct

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#69722]
**Version Used**: Visual Studio Version 17.8.0 Preview 1.0

**Steps to Reproduce**:

In this code:
```c#
struct ValueTuple
{
}
```
the "Make struct readonly" code fix isn't offered, even though the struct can be made readonly. I believe it should be offered.

**Comment by CyrusNajmabadi** [comment]
Closing out.  It's likely the user is going to actually put values here.

**Comment by Neme12** [comment]
I mean, by that logic, stuff like IDE0251 (Member can be made 'readonly') and CA1822 (Mark members as static) shouldn't be suggested on empty methods because it's likely the user is going to do something interesting there. And IDE0051 (Remove unused private member) shouldn't be offered at all because it's likely the user is going to use it.

Yes, it's likely that the user is going to add non-readonly fields, but it's just as likely that they are going to add readonly fields and keep the struct readonly. I don't see a reason why the analyzer should special-case this scenario. It satisfies the condition that all members are readonly.

**Comment by CyrusNajmabadi** [comment]
> And it's not like the user will even notice this 

There is a level where things just aren't important enough. Being ultra precise and trying to convey each and every situation to this level is just not necessary. :-)

**Comment by Neme12** [comment]
> Being ultra precise and trying to cover each and every situation to this level is just not necessary

But... but.... *sad noises*
