### ISSUE TITLE
[Feature Suggestion] Disable execution of specific Roslyn analyzers or code fixes during build and design-time (live analysis)

### ISSUE THREAD

**Issue by duki994** [dotnet/roslyn#69733]
Generally, when one wants to disable Roslyn analyzer, usage of `pragma` directives or `.editorconfig` rules are primary choices.

They actually just disable diagnostic reporting, while analyzer runs in the background. End user has no mean to disable actual execution of code of specific analyzer or code fix during live analysis.

Using custom MSBuild tasks is a convoluted way can achieve this. 
Setting severity to "None" as desribed in [Configure severity levels](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-severity-levels) still runs actual code of analyzer.

#### Context where this is applicable
Say someone creates a package with 200 analyzers and 500 code fixes that are very popular. After some time, a malicious analyzer (or code fix) that can read sensitive private data somehow (such as credit cards) and send it over the wire is added. 
Or for example, intentionally pause or slow-down build for some large chunk time in that malicious analyzer.

Another scenario is where you have large number of analyzers and code fixes and want to explicitly run only subset, while others are disabled completely.

##### Immediate remediation
**How can end user disable it easily as immediate fix when found without stopping rest of 200 analyzers and 499 code fixes that aren't malicious?**

There's possibility of disabling/removing entire assembly. This however removes all analyzers, even remaining 200 analyzers and 499 code fixes which are useful.

For example, ESLint in JS/NodeJS ecosystem disables completely rules via configuration files. Their code isn't even run.

This issue is also related to https://github.com/dotnet/roslyn/issues/68998

**Comment by genlu** [comment]
I think this might be addressed in https://github.com/dotnet/roslyn/pull/69778
@mavasani to confirm

**Comment by mavasani** [comment]
This is already supported via globalconfig files: https://learn.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig. If you have an entry `dotnet_diagnostic.RuleId.severity = none` in a global config file, and no overriding entry in any of your editorconfig files that enable the rule, then the analyzer reporting `RuleId` is disabled for the entire project and will never receive any analyzer callbacks.
