### ISSUE TITLE
Automatically "disconnect" remote testing machine after session is over

### ISSUE THREAD

**Issue by TyOverby** [dotnet/roslyn#6974]
Right now, the rbld machines require us to hit a "disconnect.bat" script after the session is over.  Having a way to automatically detect this and execute that script manually would be ideal.

**Comment by davkean** [comment]
Tanner, do you think there is there ever going to a way to do this?

**Comment by davkean** [comment]
I have noticed that it's less of a problem now, in fact, haven't seen it in months.

**Comment by jasonmalinowski** [comment]
We're using dynamic machines now, and with the work happening to easily make repro machines we won't need this.
