### ISSUE TITLE
Can completion items with type/template params fill in <> and hold cursor in between the brackets?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69754]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellicode-suggestion-and-completion/10422684)._

---
[severity:It bothers me. A fix would be nice]
The implementation of Intellicode suggestion is not finished.
My keyboard does not have '<' and '>' characters, so I am using the Windows Visual Keyboard when needed.
It solves the problem but it is annoying to repeatedly switch from my real keyboard to the visual one.
If a suggestion contains these characters when showing the suggestion popup combobox, they are removed from the resulting edited text.

---
#### Feedback Bot on 7/25/2023, 06:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This may not be roslyn. @dpugh is this you guys?

**Comment by CyrusNajmabadi** [comment]
Closing out as external.
