### ISSUE TITLE
IntelliSense fails to capture enclosing local variables when editing a lambda expression, which persists when editing other non-lambda files in C#.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69753]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-fails-to-capture-enclosing-/10370052)._

---
[severity:It's more difficult to complete my work]
IntelliSense makes auto-completion suggestions as normal until I begin to edit a file containing a lambda expression, which seems to induce an internal error that persists between file editors across my project. I am using VS 2022 EE, v. 17.6, but issue was present before updating from 17.5. 

---
#### Feedback Bot on 5/21/2023, 05:56 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 5/22/2023, 08:45 AM: 

(private comment, text removed)
#### Carter Canedy on 5/23/2023, 08:54 AM: 

(private comment, text removed)
#### Carter Canedy on 6/6/2023, 08:21 AM: 

(private comment, text removed)
#### Feedback Bot on 6/6/2023, 09:26 AM: 

(private comment, text removed)
#### Feedback Bot on 6/6/2023, 11:46 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by cartercanedy** [comment]
any updates on this?

**Comment by CyrusNajmabadi** [comment]
I don't repro this at all.  We'd need a fuller repro demonstrating the problem if we wanted to make progress on this.
