### ISSUE TITLE
static lambda's still have a target

### ISSUE THREAD

**Issue by trampster** [dotnet/roslyn#69758]
**Version Used**: 
dotnet sdk 7.0.302

**Steps to Reproduce**:
1. Make a new Console project dotnet new --console 
2. Insert the following into the Program.cs
```
Action action = static () => Console.WriteLine("Hello, World!");
if(action.Target != null)
{
    Console.WriteLine($"target set to: {action.Target.ToString()}");
}
```
4. Run with dotnet run
5. Notice that the target was set.

**Expected Behavior**:
static lambda should have no target, the same as when assigning a static method to an action.

**Actual Behavior**:
The target is set to the instance of the class that created the lambda. This creates unexpected memory leaks if the action is held by an object with a longer lifecycle than the instance which created the lamda, even though the lamda is static and thus should not need to reference that instance to run.

**Comment by jaredpar** [comment]
Thanks for filing but this behavior is "By Design". A capture free lambda is modeled as an instance method on a singleton object. This is done because invocations of delegates that target instance methods have better performance than those that target static methods (due to parameter shifting). As such we model these as instance methods on singletons.

**Comment by trampster** [comment]
Whats the lifecycle of the singleton? is it eligable for garbage collection when the delegate is no longer referenced?

**Comment by trampster** [comment]
Also is there a way to ensure a delegate you where passed is static, I was using .Target == null for this, which does work for static methods, but not for static delegates.
The context for this is in making a weak eventing system that doesn't need reflection, most do this by storing a MethodInfo and doing the callback via reflection. But if you can force the use of static methods/delegates then the reflection would not be required.

**Comment by CyrusNajmabadi** [comment]
> Whats the lifecycle of the singleton? is it eligable for garbage collection when the delegate is no longer referenced?

We cache the delegate instance so that further attempts to acquire it will return the same Singleton.

**Comment by CyrusNajmabadi** [comment]
> Also is there a way to ensure a delegate you where passed is static

Yes. Write an analyzer that requires this at the call sites.
