### ISSUE TITLE
AndersDemo is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6976]
`Output prompt not found after 10000 ms`

http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/416/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/436/VS_Integration_Test_Logs/AndersDemo.html

Probably the same root cause as #6575 - some scenario is cleaning up after itself.

**Comment by dpoeschl** [comment]
@amcasey  Thanks for re-filing!

**Comment by amcasey** [comment]
These are all the logs I can find for this test.  They may not all have the same cause:

http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/332/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/340/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/346/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/350/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/354/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/357/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/364/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/416/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/436/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/19/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/127/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p0/32/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p0/41/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p0/29/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p0/36/VS_Integration_Test_Logs/AndersDemo.html
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p0/48/VS_Integration_Test_Logs/AndersDemo.html

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/127/VS_Integration_Test_Logs/AndersDemo.html is gone - probably log rotation.

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_stabil_win_vsi_p0/29/VS_Integration_Test_Logs/AndersDemo.html is unrelated.

**Comment by amcasey** [comment]
All of the others failed to find the prompt.

All "tail of output" strings:
```
 = null; w.Close(); w = null;
```
```
dd(b);
 . w.Content = g;
 . 
```
```
= null; w.Close(); w = null;
```
```
= null; w.Close(); w = null;
```
```
= null; w.Close(); w = null;
```
```
= null; w.Close(); w = null;
```
```
+) Console.WriteLine(i * i);
```
```
= null; w.Close(); w = null;
```
```
le.WriteLine("Hello World");
```
```
dd(b);
 . w.Content = g;
 . 
```
```
= null; w.Close(); w = null;
```
```
les(@"c:\windows")) Print(f)
```
```
= null; w.Close(); w = null;
```
```
+) Console.WriteLine(i * i);
```

**Comment by amcasey** [comment]
Guess: we're trying to clear the submission with `ESC` and it's inconsistent.

**Comment by amcasey** [comment]
The "tail of output" varies according to which scenario was running when the failure occurred.  For example, `= null; w.Close(); w = null;` is Scenario 8.

**Comment by amcasey** [comment]
Only http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p0/436/ has build artifacts.

**Comment by amcasey** [comment]
It's hard to tell from the log exactly where the attempt to find the prompt is occurring.  Maybe there's a race between submitting text and looking for a prompt?

**Comment by amcasey** [comment]
Looks like we submit and then wait.  Maybe submission is asynchronous?

**Comment by amcasey** [comment]
Submit is an un-awaited async method.  Is there any reason to believe that it will complete if no one tugs on it?

**Comment by amcasey** [comment]
I have no local repros of the failure, but I'll create a PR with a speculative fix.

**Comment by amcasey** [comment]
Speculative fix merged (internally).

**Comment by amcasey** [comment]
There are no active `Flaky` bugs for this test.
