### ISSUE TITLE
Diagnostics not refreshed in FSA with editorconfig option changes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#69763]
1. Enable Full solution background analysis
2. Open a solution which has bunch of analyzer warnings in closed files, say with id `RuleId`
3. Wait for background analysis to populate error list
4. Disable a specific analyzer warning in editorconfig by adding `dotnet_diagnostic.RuleId.severity = none` and save the file
5. Wait for background analysis to refresh the error list

**Expected behavior:**
All `RuleId` entries in the error list are cleared out

**Actual behavior:**
`RuleId` entries in the error list are cleared out only for diagnostics in documents in the current project

**Comment by CyrusNajmabadi** [comment]
Btw.  I would be very ok with some major rewrites here where all the logic was consolidated. Right now it feels like all the behavioral logic is spread out over a variety of places and apis.  So depending on how the consumer calls things you end up with varying behaviors that are very hard to understand. 

A lot of this stems from the being far too many apis and interfaces here to do things.  Simplifying to a bare minimum will go a long way to making it hard to get things wrong here.
