### ISSUE TITLE
Display inherited documentation as an adornment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69789]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Display-comments-in-derived-methods/10423622)._

---
Currently comments on methods, classes, properties, interfaces etc. (further called elements) in C# are "derived" from the base. If you implement a new class and an element is overriden the derived comment cannot be seen automatically. For example see the interface IBase:

![image](https://github.com/dotnet/roslyn/assets/1408396/26b1d299-562a-4e6e-8966-aa7fec758d92)

If you now implement the interface in Impl:

![image](https://github.com/dotnet/roslyn/assets/1408396/d3932037-e87e-494a-b6cc-5f91c069a980)

you cannot see the comments. You can only see them by hovering over the method:

![image](https://github.com/dotnet/roslyn/assets/1408396/dea33fe6-513a-49e9-aa82-b87e70b29257)

It would be much nicer, though, if the comments are visually derived in the editor, so that they look like they have been written manually and they also support folding/unfolding but are not editable:

![image](https://github.com/dotnet/roslyn/assets/1408396/1b36835d-de3d-4b15-9539-9fd804ab2739)

---
#### Feedback Bot on 7/26/2023, 08:32 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as unlikely to do this.
