### ISSUE TITLE
Interpolated string handler API support

### ISSUE THREAD

**Issue by syrompetka** [dotnet/roslyn#69796]
For most "syntax sugar" features (like **foreach**, **await** for example) Roslyn provides corresponding helper methods for semantic model like **SemanticModel.GetForEachStatementInfo** or **SemanticModel.GetAwaitExpressionInfo**.
These methods simplify code analysis a lot.

For new interpolated string handler feature there is no such API.
The only way to get string interpolation semantic details is to use **SemanticModel.GetOperation**. 
Operation API has dramatic performance penalties and undesireble to use.

Proposal: Introduce SemanticModel.GetInterpolatedStringHandlerInfo method that returns all details about interpolated string unfolding process: 
- Used handler constructor overload
- Used AppendLiteral, AppendFormat overloads
- Captured argumens
- and so on

**Comment by CyrusNajmabadi** [comment]
> SemanticModel.GetOperation.
Operation API has dramatic performance penalties and undesireble to use.

Can you provide more information on this?  We use GetOperation virtually all the time across many features and analyzers and have found the performance a non-issue.

**Comment by syrompetka** [comment]
1. IOperation API does not support caching as far I remember
2. In order to process new improved interpolated strings we'll need to call GetOperation for each InvocationExpressionSyntax, BinaryExpressionSyntax and InterpolatedStringText which might be too much
3. For previously introduced "syntax sugar" features corresponding **GetInfo**  (GetAwaitExpressionInfo, GetForEachStatementInfo  f.e.) was introduced alongside with IOperation API fixes but for new interpolated strings only IOperation is available which seems a bit inconsistent. At least I could not find one.

**Comment by CyrusNajmabadi** [comment]
> which might be too much

So we're already calling all this and more that without issue. 

> IOperation API does not support caching as far I remember

Possible, though that would surprise me. @333fred ?

> For previously introduced "syntax sugar" features corresponding GetInfo (GetAwaitExpressionInfo, GetForEachStatementInfo f.e.) was introduced

Right. But those predated iop, and we're basically the poor-man's way if doing things. We did iop so we didn't need to make all these one -off apis that would be better exposed in a true ast.

**Comment by 333fred** [comment]
> IOperation API does not support caching as far I remember

It caches per model. If you don't reuse the model, there's no caching. Further, there's no real advantages to not using IOperation. Basically all the same work will need to be done when a user calls any semantic model api.
