### ISSUE TITLE
Parameter name InlineHints should ignore `this.` and `base.`

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#69793]
## Summary

When determining whether to show a parameter name hint, Roslyn should ignore `this.` and `base.`

## Background and Motivation

I have a repo that requires the use of `this.` when accessing members. This causes parameter name hints to be offered even when the name of the member I am passing matches the parameter name.

![Image](https://github.com/dotnet/roslyn/assets/611219/b4b6105b-f1c0-4ec0-a3c9-e9546b5ce07e)

**Comment by CyrusNajmabadi** [comment]
We woudl take a community contribution here.
