### ISSUE TITLE
Completion: Shift+Home, Delete shouldn't trigger completion

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#698]
Ported from TFS WorkItem: **1024155**

---

**Steps to reproduce:**<BR><BR>1. Start with:

<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN>
<SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Collections</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Generic</SPAN>
<SPAN style="COLOR: blue">Imports</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">Linq</SPAN>
 
<SPAN style="COLOR: black">a<FONT color=#ff69b4>$</FONT></SPAN>$
 
<SPAN style="COLOR: blue">Module</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">args</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: blue">String</SPAN><SPAN style="COLOR: black">())</SPAN>
        
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Module</SPAN></PRE>

1. Shift+Home, Delete to delete the line

&nbsp;

**RESULT:** Completion list is showing.

&nbsp;

**EXPECTED:** No completion showing, since I just deleted the whole line (and used delete, not backspace).

&nbsp;

**NOTE:** Completion did _NOT_ show in this situation in Dev12.

---

**Revisions:**

1) Created By Kevin Pilch-Bisson (9/10/2014 11:25:00 AM)

---

2) Edited By Kevin Pilch-Bisson (2/19/2015 2:26:42 PM)

We can tweak this after RTM, though it is annoying.

---

**Comment by CyrusNajmabadi** [comment]
Closing out as we haven't heard more reports about this in 9 years.
