### ISSUE TITLE
Right-hand closing brackets (`>`) are not properly colored in nested generics

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#69811]
**Version Used**: Visual Studio 2022 Version 17.8.0 Preview 1.0

**Steps to Reproduce**:

1. Turn on the "Enable brace pair colorization" option
![image](https://github.com/dotnet/roslyn/assets/8298332/decea2a7-b64b-427c-a42e-aafc161eff21)
2. In a C# file, use a nested generic like `IEnumerable<IEnumerable<string>>`

**Expected Behavior**:

The brace colors match properly.

**Actual Behavior**:

The `>>` are both the same color, despite the one closing the inner generic type argument list.
![image](https://github.com/dotnet/roslyn/assets/8298332/29173eed-cb4d-401f-917a-0cc9f05b2e89)

Note, if you separate the closing braces with a space, colorization will be normal, as shown in the image above.

**Comment by Rekkonnect** [comment]
Update after revisiting this issue

I use a font that has ligatures for common symbol compounds like `>>`, `...`, etc. For the above example, and likely other ligatures, colorization breaks when the ligature appears. Using a font without ligatures does not break colorization.

The font also contains a ligature for >>>, which also breaks colorization:
![image](https://github.com/dotnet/roslyn/assets/8298332/8f2b0052-b4ca-4651-af91-9b736946aace)

Notice that when hovering over one single opening/closing bracket, it does only highlight its one respective bracket for the same nesting level, despite the front color of the character.

But for more than 3 >, it resorts to displaying just single > glyphs, and colorization happens properly:
![image](https://github.com/dotnet/roslyn/assets/8298332/8f11957b-204c-4c13-aaba-c9132f9da6b4)

The above problem is only on the individual characters' front colors, the rest of the colorization is not affected.

Since this is a font-specific issue involving ligatures, it might be a very difficult/insignificant, and may be up for closing.

**Comment by CyrusNajmabadi** [comment]
@olegtk can you move and let Caleb know about this?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing as dupe.  Thanks!
