### ISSUE TITLE
NuGet is failing to restore on internal jobs

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6981]
PR: [#6978](https://github.com/dotnet/roslyn/pull/6978) *Set Experimental flag for our VSIXes* by @jasonmalinowski
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/60/

**Issue 1: MSBuild Error**
error MSB4057: The target "_NuGet_GetProjectsReferencingProjectJsonInternal" does not exist in the project.

**Issue 2: Compile Error**
error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?) [d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\src\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj]

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

@agocke Please take a look, this looks like a result of updating NuGet.exe. It appears this is their target: https://github.com/search?q=_NuGet_GetProjectsReferencingProjectJsonInternal&type=Code&utf8=%E2%9C%93

Should we rollback NuGet 3.3 until this is resolved?

**Comment by agocke** [comment]
@jasonmalinowski Can you comment? I don't know what would have caused this.

**Comment by davkean** [comment]
@jasonmalinowski He doesn't know, I've pulled in NuGet team offline, but right now, VSI has a massive set of failures - so if can't fix soon, in next 10 mins or so, we should roll back NuGet 3.3.

**Comment by agocke** [comment]
Change reverted in https://github.com/dotnet/roslyn/pull/6994

**Comment by davkean** [comment]
Thanks!

**Comment by dpoeschl** [comment]
@davkean Should the "Urgency" be updated now?

**Comment by davkean** [comment]
Yep, fixed it. I'm going to close this, as we can no longer repro.

**Comment by davkean** [comment]
We just hit this again on a different machine: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2119/.

**Comment by davkean** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_eta/463/.

**Comment by davkean** [comment]
And another: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/67/

**Comment by davkean** [comment]
I've rolled back to NuGet 3.2, until this gets resolved.
