### ISSUE TITLE
Source generator - fail to generate source with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/roslyn#69819]
**Version Used**: dotnet version: 8.0.100-preview.6.23330.14

Hey

I'm working on a source generator and I'd like to format the generated csharp code using `AdhocWorkspace`

``` csharp
var _workSpace = new AdhocWorkspace();
_workSpace.AddSolution(
          SolutionInfo.Create(SolutionId.CreateNewId("formatter"),
          VersionStamp.Default)
);

var root = CSharpSyntaxTree.ParseText(code).GetRoot();
var formatter = Formatter.Format(root, _workSpace);
return formatter.ToFullString();
```

The format code works perfect in visual studio IDE, which means I can see the generated, formalized code from solution explorer -> analyzer -> my source generator. However, when I build the project from dotnet cli, I keep getting file not found exception for `Microsoft.CodeAnalysis.Workspaces` from my source generator.

I tried manually adding reference to `Microsoft.CodeAnalysis.Workspaces.dll` by adding dependency to `Microsoft.CodeAnalysis.Workspaces.Common` with `GeneratePathProperty` to true. But that doesn't resolve my issue.

So how can I make the code formatting work inside source generator - without getting file not found exception.

## To reproduce
The complete code is uploaded [here](https://github.com/LittleLittleCloud/CopilotBuilder/tree/u/xiaoyun/0901)

The link to my source generator is [here](https://github.com/LittleLittleCloud/CopilotBuilder/tree/u/xiaoyun/0901/src/CopilotBuilder.SourceGenerator)

And to reproduce the error, simply clone the repo and 
```
dotnet build
```

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

**Actual Behavior**:

**Comment by jasonmalinowski** [comment]
We don't expect you to be referencing the Workspaces layer like this -- if nothing else, the extra formatting passes are going to slow your generator down. Is the code you're generating compliable without it or are you directly generating the nodes?

**Comment by LittleLittleCloud** [comment]
@jasonmalinowski The code is compilable. It just doesn't format nicely. And that source generator is generating a lot of code so the bad formating seems to be a problem

**Comment by jasonmalinowski** [comment]
There is also a method [NormalizeWhitespace](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.syntaxnodeextensions.normalizewhitespace?view=roslyn-dotnet-4.6.0) you can call that doesn't require the Workspace layer reference.

**Comment by LittleLittleCloud** [comment]
@jasonmalinowski Thanks for the quick response. I've tried `NormailizeWhitespace` and it works well under most cases. However `NormailizeWhitespace` tends to format code into a single line, which causes the formatted code sometimes hard to read.

If it's by design that source generator should not interact with Workspace layer, then feel free to close this issue and I can go with `NormailizeWhitespace` solution.

**Comment by CyrusNajmabadi** [comment]
It is by design.
