### ISSUE TITLE
DisallowNull, T? and inheritance 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/roslyn#69832]
**Version Used**: .net 8.0 preview 7

```cs
abstract class Converter<T>
{
    public abstract void Do([DisallowNull]T value);
}

class NullableConverter<T> : Converter<T?> where T : struct
{
    public override void Do([DisallowNull]T? value) {}
}
```

**Diagnostic Id**: CS8765

**Expected Behavior**:

No warning, the attribute should just make callers aware null isn't allowed. These generic compositions should be supported.

**Actual Behavior**:

We get a warning we can only dismiss by removing the attribute (or a pragma), as we cannot change the type to T.

**Comment by jcouv** [comment]
For some reason, I'm not able to repro in VS 17.8 preview 3, but I don't recall our fixing anything in this area recently.
Could you add `#error version` to your program and share the output?
Mine reports `Compiler version: '4.8.0-2.23429.7 (44555193)'.`

Normally, I would try to repro on neutral grounds (sharplab) but it's been having issues recently :-/

**Comment by NinoFloris** [comment]
Right, sorry about that. This was 100% user error :/
