### ISSUE TITLE
Roslyn has introduced many source-built prebuilts

### ISSUE THREAD

**Issue by mthalman** [dotnet/roslyn#69847]
The following source-build prebuilts have been introduced by Roslyn in the dependency flow into installer: https://github.com/dotnet/installer/pull/17319:

```
/vmr/repo-projects/Directory.Build.targets(688,5): warning : MessagePack.2.5.108 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : MessagePack.Annotations.2.5.108 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.AspNetCore.App.Runtime.osx-arm64.8.0.0-rc.1.23401.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.AspNetCore.App.Runtime.osx-x64.8.0.0-rc.1.23401.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.AspNetCore.App.Runtime.win-arm64.8.0.0-rc.1.23401.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.AspNetCore.App.Runtime.win-x64.8.0.0-rc.1.23401.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.AspNetCore.App.Runtime.win-x86.8.0.0-rc.1.23401.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.Build.Locator.1.6.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Host.osx-arm64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Host.osx-x64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Host.win-arm64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Host.win-x64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Host.win-x86.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Runtime.osx-arm64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Runtime.osx-x64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Runtime.win-arm64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Runtime.win-x64.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.NETCore.App.Runtime.win-x86.8.0.0-rc.1.23381.3 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.VisualStudio.Threading.17.6.40 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.VisualStudio.Threading.Analyzers.17.6.40 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Microsoft.VisualStudio.Validation.17.6.11 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : Nerdbank.Streams.2.10.66 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.Collections.4.0.11 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.Globalization.4.0.11 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.IO.4.1.0 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.Reflection.4.1.0 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.Reflection.Primitives.4.0.1 [/vmr/repo-projects/dotnet.proj]
/vmr/repo-projects/Directory.Build.targets(688,5): warning : runtime.placeholder-rid.System.Resources.ResourceManager.4.0.1 [/vmr/repo-projects/dotnet.proj]
```

These stem from the following packages:

* Microsoft.CodeAnalysis.Workspaces.MSBuild
* Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost (this is the source of most of the prebuilts) (related to https://github.com/dotnet/roslyn/pull/69616)

These prebuilts were not caught by roslyn CI because of https://github.com/dotnet/roslyn/issues/69846.

Here is the attached prebuilt report for more details: 
[prebuilt-usage.zip](https://github.com/dotnet/roslyn/files/12552070/prebuilt-usage.zip)

One of the more concerning of these prebuilts is the dependency on StreamJsonRpc. This is produced outside of .NET and would need to be included in [source-build-externals](https://github.com/dotnet/source-build-externals).

One thing we need to determine first is whether Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost needs to be source-built at all. We need to understand its purpose and whether its relevant to a source-built SDK. @jasonmalinowski - Can you provide more info here?

cc @MichaelSimons

**Comment by jasonmalinowski** [comment]
Background first: Microsoft.CodeAnalysis.Workspaces.MSBuild is a Roslyn package which a tool author can use to take a solution/projects on disk and load them into Roslyn so you can look at the syntax trees, semantics, etc. For example, dotnet format uses it to load the syntax trees to then start formatting them. One consistent problem we've had with MSBuildWorkspace is since it's using MSBuild in-process, it can only support projects that match your runtime type and/or version; for example a tool compiled against .NET Framework may choke on .NET Core projects and vice-versa. Because of needs for the C# extension we're generally enhancing it so it can launch a separate process (the BuildHost binary) and do out-of-proc builds and then pass the stuff back in process.

Now a few questions I have:

> the following packages...Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost

@mthalman: There shouldn't be a BuildHost package, since at the moment we're still shipping the BuildHost binary as a "regular binary" to be loaded in-process as before since we're doing this work one step at a time. There was a bug that was fixed in [this PR](https://github.com/dotnet/roslyn/pull/69835) last night that removed an accidental reference to a non-existent package. So if you are still seeing a package with a reference to a that non-existent package, then something is up and I need to dig further.

> One thing we need to determine first is whether Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost needs to be source-built at all.

At the moment, the code behavior is the same before for the package and this was supposed to be an under-the-hood change. We have other code outside the SDK consuming the BuildHost and the StreamJsonRpc portion of it, so for purposes of unblocking at the moment we absolutely can restrict those references to non-source-build only if that's the easiest solution. Although we will need to revisit this at some point; if there's a different RPC library that's also already sourcebuild friendly I can switch to that too...StreamJsonRpc was just chosen as we use it in other parts of our stack, not because of any specific feature in it.

**Comment by mthalman** [comment]
> There shouldn't be a BuildHost package

No issue here. I should have referred to them as projects instead of packages.

> At the moment, the code behavior is the same before for the package and this was supposed to be an under-the-hood change.

That doesn't seem to be the case. Or maybe I'm misinterpreting what you're saying. There was never a dependency on StreamJsonRpc from Microsoft.CodeAnalysis.Workspaces.MSBuild prior to the addition of the BuildHost.

> We have other code outside the SDK consuming the BuildHost and the StreamJsonRpc portion of it, so for purposes of unblocking at the moment we absolutely can restrict those references to non-source-build only if that's the easiest solution.

It's not the code that's referencing BuildHost that's the issue. It's BuildHost itself, which has the dependency on StreamJsonRpc, that's the issue.

If the implementation which uses StreamJsonRpc is not relevant for the SDK itself, can it be factored out into a separate project that we then don't include with source-build?

**Comment by jasonmalinowski** [comment]
> There was never a dependency on StreamJsonRpc from Microsoft.CodeAnalysis.Workspaces.MSBuild prior to the addition of the BuildHost.

I might have not explained well: yes, the dependency is new, but at the moment for purposes of the SDK we're not actually using the process-launching part of it. We're using that in other places for now. That'll change in a month or so though, so longer term we still need a plan.

Stepping back for a moment, what _should_ this look like? Either we have to make StreamJsonRpc be part of source-build-externals, or we move to a different RPC library?

**Comment by jasonmalinowski** [comment]
> Got it. So any workaround to remove the dependency now won't be relevant once the SDK requires the use of the BuildHost.

Or at least, I don't want to spend more effort on a workaround than necessary, or at least limit stuff we'd have to undo later. I know we have projects now that condition things on DotNetBuildFromSource in MSBuild; I can trivially add some condition checks to the particular source files to unblock this if that's an easy short term solution.

**Comment by mthalman** [comment]
> Or at least, I don't want to spend more effort on a workaround than necessary, or at least limit stuff we'd have to undo later. I know we have projects now that condition things on DotNetBuildFromSource in MSBuild; I can trivially add some condition checks to the particular source files to unblock this if that's an easy short term solution.

If that's easy, that would buy some time and unblock things. Are the changes to eventually include the dependency from the SDK intended for .NET 8?

**Comment by jasonmalinowski** [comment]
> Are the changes to eventually include the dependency from the SDK intended for .NET 8?

The schedule for that isn't tied to 8.0; this is a bit of funky fallout of the fact that Roslyn repository ships things in different vehicles -- I'm honestly quite surprised that Roslyn main was even shipping in 8.0 given it's in RC. So we can delay after whenever that snap is, but I have no idea what that date is.

**Comment by jasonmalinowski** [comment]
@mthalman Is gRPC already within source build or not?

**Comment by mthalman** [comment]
> The schedule for that isn't tied to 8.0; this is a bit of funky fallout of the fact that Roslyn repository ships things in different vehicles -- I'm honestly quite surprised that Roslyn main was even shipping in 8.0 given it's in RC. So we can delay after whenever that snap is, but I have no idea what that date is.

Perfect. Glad to hear this isn't a .NET 8 thing. This gives us a lot of time then.

> Is gRPC already within source build or not?

No. That's part of https://github.com/grpc/grpc-dotnet. Nothing which ships as part of the SDK has a dependency on that.

@jasonmalinowski, can you log an issue for this that describes the need for RPC and the fact that it will have have source-build implications? It'd be good to have something to track this and we can discuss what our options are.

**Comment by jasonmalinowski** [comment]
I think rather than try (re)inventing an RPC approach we're just going to restructure our code a bit. What we were doing was spinning up an external process which is running MSBuild APIs; we can probably restructure things where we just launch the process and pass all the projects we want to analyze in command line switches, just have it output a single JSON blob and then exit. That _might_ work fine and just avoid the RPC need entirely.

**Comment by mthalman** [comment]
Remaining fixes for prebuilts:

- [ ] https://github.com/dotnet/roslyn/pull/69895
- [x] https://github.com/dotnet/source-build-externals/pull/207
- [ ] https://github.com/dotnet/roslyn/pull/69870
- [ ] https://github.com/dotnet/roslyn/pull/69900
- [ ] Microsoft.DiaSymReader?
- [ ] System.Text.Json?
