### ISSUE TITLE
Inline temporary variable adds unnecessary cast

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#69869]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
var a = Math.Round(1.1D);
var b = a;
```
Inline variable `a`;

**Expected Behavior**:
```cs
var b = Math.Round(1.1D);
```

**Actual Behavior**:
```cs
var b = (double)Math.Round(1.1D);
```

**Comment by DoctorKrolic** [comment]
Futhermore, after executing code action, IDE doesn't suggest you remove unnecessary cast. So this is simplifier's problem: it cannot determine, that in the given context overload with `double` return type is used (I guess this is the core problem)

**Comment by CyrusNajmabadi** [comment]
Doubles are challenging due to the casts having semantics even when the types are exactly the same. 

We likely want to be cautious about adding the explicit fp cast in the first place. Avoiding it if we can be sure it isn't necessary.

**Comment by DoctorKrolic** [comment]
> Doubles are challenging due to the casts having semantics even when the types are exactly the same.

Wait what?! Can you give an example?

**Comment by CyrusNajmabadi** [comment]
Machines execute fp operations on higher precision than 32 or 64 bits. Casting explicitly reduces the precision down to those levels. So you can get different results.

**Comment by pyoub** [comment]
i create a pr tried to fix this problem if you can review it please :)

**Comment by CyrusNajmabadi** [comment]
@pyoub if you ping me tomorrow I can take a look!

**Comment by pyoub** [comment]
@CyrusNajmabadi can you check the PR please @DoctorKrolic  already did and didnt like approve the solution. so is there any suggestion?
