### ISSUE TITLE
Microsoft.Build.Framework NuGet package only provides an x86 ref assembly

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#6986]
It looks like the recent refactoring of the MSBuild tasks introduced a MSBuild warning.  

```
16:41:45 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\dotnet-bot\.nuget\packages\Microsoft.Build.Framework\0.1.0-preview-00003\lib\dotnet\Microsoft.Build.Framework.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. 
``` 

These are intended to be build breaks.  Hence treating this as a flaky issue.

**Comment by agocke** [comment]
@jaredpar This is because the reference bits in the NuGet package are architecture specific. We'll have to get a new package from MSBuild.

**Comment by jaredpar** [comment]
Lets grab that package then :)

Or temporarily switch the portable task to have the same architecture.

JaredPar from a phone
http://blog.paranoidcoding.com/
________________________________

**Comment by jaredpar** [comment]
@agocke do we have a bug on the MSBuild repo to track them providing this package?
