### ISSUE TITLE
Stop processing during IncrementalValueProvider

### ISSUE THREAD

**Issue by hugener** [dotnet/roslyn#69868]
## Background and Motivation

Not sure if I missed something here, I'm working on an Incremental Generator, that used the CompilationProvider to first extract some type information. Looking for a type with Compilation.GetTypeByMetadataName might return null in case the type isn't found, if for example the containing assembly was not referenced.
If that's the case, I would just report a diagnostic to inform the user, which is fine.
The problem is that there is no way to stop the pipeline at this port. The only two options are:
* throwing an exception 
* combine the provider into a IncrementalValuesProvider, carrying over a null and use Where to ignore the value.

Throwing in my opinion is the wrong approach as it seems the generator malfunctioned and handling the null in a where clause seem very inefficient since there where runs on all nodes from the IncrementalValuesProvider.

Shouldn't there be a way stop processing a IncrementalValueProvider in case the conditions for processing it are not met?

**Comment by CyrusNajmabadi** [comment]
The ivp stops when it produces the same values as the prior run. So just do that and everything will work out.
