### ISSUE TITLE
Classify exterior documentation trivia spans with trailing or inner whitespace

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6987]
> If the exterior documentation had a trivia node with whitespace nonwhitespace whitespace or whitespace nonwhitespace whitespace nonwhitespace, the ending bound used for the nonwhitespace characters would be too high - potentially outside of the range of the node itself. The index is relative to trivia.Span.Start, but it is added to spanStart.Value instead, which would effectively give the span a length of index instead of actually indicating the end bound.
> 
> This scenario is not created by the lexer currently. The lexer at most generates exterior documentation trivia nodes with leading whitespace - which would hit the block that takes the span from the point where it found non-whitespace to the end of the token

See: https://github.com/dotnet/roslyn/pull/3559.

We'll take this change if tests are written reproducing the problem.

**Comment by Vhoakab84** [comment]
Ok closed.
