### ISSUE TITLE
Alt+F1 for peek hints cannot be rebound to a different shortcut

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69886]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Alt--F1-is-not-toggling-inline-paramete/10457447)._

---
[severity:It's more difficult to complete my work]
Hi,

When I click Alt + F1, I would like to see the inline parameter hints and hide them, so that there is no clutter in code view.

Holding Alt + F1 is triggering windows X box feature and not showing inline parameter hints.
Please give option to change shortcut or change to shortcut that will work in windows.

With regards,
Nithin B.

---
#### Feedback Bot on 9/5/2023, 00:14 AM: 

(private comment, text removed)
#### Nithin B on 9/6/2023, 09:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This shortcut is hard-coded here:
https://github.com/dotnet/roslyn/blob/d080175cabfe297ebf079af099279b61913bcc28/src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsKeyProcessorProvider.cs#L75-L79

**Comment by nithinbandaru1** [comment]
Good to know it is added to backlog. Hoping to see the fix soon,

**Comment by CyrusNajmabadi** [comment]
Platform is taking over this feature through LSP.  So they would own controlling this.
