### ISSUE TITLE
BasicWinForms is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#6988]
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/57/VS_Integration_Test_Logs/

```
Failed to delete project files. Look at FileHandlesDump.txt to see which process is holding onto TestProj. 
                                           Current VS Process Id is 7140, TAO Pid is 5600
```

**Comment by amcasey** [comment]
The machine that ran the test is offline and can be investigated as soon as the current (unrelated) run finishes.

**Comment by davkean** [comment]
@TyOverby Please take a look at the machine and see if you can figure out what's going on here?

Right now, other than RIs/FIs internally, this should be your highest priority.

**Comment by amcasey** [comment]
```
devenv.exe    pid: 7140    290C: C:\Users\dotnet-bot\AppData\Local\Temp\TestProj
```

**Comment by dpoeschl** [comment]
@amcasey @TyOverby dci-win-rbld-05 isn't offline anymore. Did any investigation happen, and did anything come of it?

**Comment by amcasey** [comment]
@dpoeschl I looked at it and pasted the file contents above.  It looked like VS was fighting with itself and the instance was gone so I released the machine.

**Comment by dpoeschl** [comment]
I'm not sure we can do anything with the above failure, but here's a failure Brett mentioned in another thread:

http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p1/56/consoleFull#1932651973a640ec72-cfe0-4777-bfdf-7cf9a1be54b8

15:31:26 --------------------------------
15:31:26 System.Exception: Property value mismatch for control:property: SomeButton:Text, expected: GibberishText, actual: ButtonTextGoesHere
15:31:26    at Roslyn.VSHosting.Test.WinFormsVerifyControlPropertyAction.<>c.<Execute>b__12_0(Object[] args) in d:\j\workspace\roslyn-internal_prtest_win_vsi_p1\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\WinFormsVerifyControlPropertyAction.cs:line 32
15:31:26    at Microsoft.Test.Apex.VisualStudio.Services.Remote.VsUIThreadInvokerService.DispatcherInvocationWrapper(RemoteAction action, Object[] arguments) in f:\dd\src\Omni\Apex\HostIntegration\VisualStudio\Services\Remote\VsUIThreadInvokerService.cs:line 87
15:31:26 ================================

**Comment by dpoeschl** [comment]
Here's the screenshot from the above failure, when it's trying to : ![image](https://cloud.githubusercontent.com/assets/235241/11385565/f4e7efae-92ce-11e5-9a66-1c415cf33247.png)

**Comment by dpoeschl** [comment]
In the above failure scenario, we make a WinForms control with a button having Text of "ButtonTextGoesHere". Based on the final screenshot, this part worked.

We then open the related .Designer.vb file and change the Text assignment line to ```Me.SomeButton.Text = "GibberishText"``` and save the file.

Then, when we open the control file again, but the button's text is still "ButtonTextGoesHere" (when checked programmatically and in the UI). Here's the final screenshot:

![image](https://cloud.githubusercontent.com/assets/235241/11385784/06378808-92d1-11e5-8e6f-6e47e1369935.png)

**Comment by dpoeschl** [comment]
We could add some diagnostic screenshots to see whether a) The .Designer.vb file didn't actually save properly, or b) The designer isn't running the updated code. Is there a scenario here where the designer initially shows with the old/cached state, and then it takes a moment to refresh? Maybe there's some additional event we need to wait for?

Any thoughts, @DustinCampbell, @Pilchie?

**Comment by DustinCampbell** [comment]
Did we close all files before opening them?

**Comment by davkean** [comment]
@DustinCampbell What does that mean?

**Comment by DustinCampbell** [comment]
I meant, did we completely close each file before opening the next one within the test? From the test log it looks like that's the case. Although, it'd be nice if the test log mentioned which file it was opening and closing. FWIW, I don't think this should matter. As soon as the WinForms designer is focused, it should refresh itself by calling into Code Model to get the `IMethodXML` for the `InitializeComponent()` method.

A couple of questions:
* Is this test failing consistently? I realize the issue title says "flaky", but I wanted to check.
* Are we sure the change actually got made to the .Designer.vb file? How do we open that file? That is, do we open it programmatically or via the Solution Explorer? (Note that it's hidden in the Solution Explorer unless Show All Files is clicked.)

@dpoeschl's suggestion is reasonable, though I've never noticed that situation happening. If we want to try hooking an event, I think we should dig in via DTE to get the `EnvDTE.Document` for the WinForms designer. Then, IIRC, the `EnvDTE.Document.ActiveWindow.Object` for the WinForms designer should implement `IDesignerHost`, which has a `LoadComplete` event. That's off the top of my head though. :smile:

**Comment by davkean** [comment]
Removing assignment to Ty and dropping milestone so that triage picks it up.

**Comment by davkean** [comment]
This test is currently disabled in TestLocator.cs:

``` C#
yield return "BasicWinForms.xml"; // https://github.com/dotnet/roslyn/issues/6988
```

**Comment by DustinCampbell** [comment]
Should be fixed with https://github.com/dotnet/roslyn-internal/pull/455
