### ISSUE TITLE
Do not open Intellisense on full-line deletion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69885]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Do-not-open-Intellisense-on-full-line-de/10458272)._

---
[severity:It bothers me. A fix would be nice]
When you delete a full line of code, if the caret ends up at column 0, the Intellisense list opens.

This can be most easily reproduced by creating a `using System;` entry at the top of a .cs file, selecting the entire line, and hitting delete. The resulting Intellisense list shows _everything_ which is rather useless.

It doesn't happen within a code block, I think because auto-indent somehow prevents it. But if you go into a code block and break the formatting by moving the line all the way left, then delete that, it will happen there, too.

I suspect it's a side-effect of the option to show Intellisense in response to delete.

An old, mildly annoying bug...

---
#### Jon McGuire on 9/5/2023, 07:23 AM: 

(private comment, text removed)
#### Feedback Bot on 9/5/2023, 08:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  Deleting the full line doesn't pop up completion for me.

**Comment by MV10** [comment]
I sure wish my employer would let me blow off issues with "works on my machine."

But, in all fairness, I don't recall seeing this recently, it may have been fixed by some other change.

I'd offer to re-test but apparently you don't care enough to even ask.
