### ISSUE TITLE
c# IntelliSense override method has wrong signature.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69880]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/c-IntelliSense-override-method-has-wron/10461900)._

---
[severity:It's more difficult to complete my work]
Define:

```
public abstract class AX<T> 
{
    public abstract T Test();
}
```

with a implementaion

```
public class CX : AX<object?>
{
}
```

alt enter -> implement abstract class gives:

```
public override object? Test()
{
    throw new NotImplementedException();
}
```

but typing override and selecting the Test method generates a different signature which is confusing and causing errors.

```
public override object Test()  // why is this not object?
{
    throw new NotImplementedException();
}
```

Notice de nullable object is wrong in the second one.

public override **object?** Test().
public override **object** Test()

Using:
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.7.3

---
#### Feedback Bot on 9/10/2023, 10:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
📝 Note that there is no compiler warning produced by the scenario above. A derived implementation is allowed to further constrain a return type of `object?` to just `object`.

⚠️ If a change is made here, it is important to ensure that overriding `object.ToString()` continues to declare the return value as `string` (and not `string?` as inherited from the base type).

**Comment by CyrusNajmabadi** [comment]
Closing as not repro.  This appropriately gives: 

![Image](https://github.com/user-attachments/assets/2abeed38-a6ad-44f5-bf47-e2f329a8175f)
