### ISSUE TITLE
Perf: Unrevert "Use dictionary lookup while resolving assembly references"

### ISSUE THREAD

**Issue by ToddGrun** [dotnet/roslyn#69908]
Tracking issue for PR (https://github.com/dotnet/roslyn/pull/69891) to determine whether the changes reverted in that PR actually caused the allocation regression claimed.

That PR removed a O(n^2) algm. Found in a trace where this method was accounting for 17.5% of CPU time ini the RoslynCodeAnalsysisService process.

![afb42fc2-f6ec-49fd-b271-0612f7d4cee9](https://github.com/dotnet/roslyn/assets/6785178/d60e4213-9165-4446-a871-ac7c3330d1e2)

**Comment by sharwell** [comment]
Can we resolve this one as a duplicate of #66410? I already updated the associated pull request to reference that issue along with the previous PRs related to it.

**Comment by ToddGrun** [comment]
Per Sam, will use https://github.com/dotnet/roslyn/issues/66410 to track, so closing this as duplicate.
