### ISSUE TITLE
[Test Failure] Tao CSharpWebApp.xml and ProjectSystem.xml

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6990]
PR: [#commits](https://github.com/dotnet/roslyn/pull/6978/commits) *Set Experimental flag for our VSIXes* by @jasonmalinowski
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/55/

**Issue 1: Tao Test Failures**
Failing integration tests:

CSharpWebApp.xml

ProjectSystem.xml

**Comment by davkean** [comment]
Logged onto the machine, it had a crash dialog but no stored dump. Attempted to get dump, but the debugger failed to attach.

I snapshotted binaries + screenshots:

`\\[internalserver]\public\davkean\6990\Release` and `\\[internalserver]\public\davkean\6990\Release\screenshots`

**Comment by Pilchie** [comment]
This is likely the same as #6989
