### ISSUE TITLE
Freeze when switching to some C# file tabs while Document Outline feature is enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69903]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Freeze-when-switching-to-some-C-file-ta/10454171)._

---
[severity:It bothers me. A fix would be nice]
When the Document Outline feature is enabled (Text Editor > Advanced > Enable document outline), Visual Studio will freeze for a couple seconds when switching to some C# file tabs. It's worth noting that this does not occur the first time the tab is switched to, it only occurs after switching away to another tab and then switching back to the tab. Then, it will continue to happen every time when switching back to the tab.

It is also important to note that this occurs even when the Document Outline window is not open and has not been open at any point in the session. It only requires the Document Outline feature to be enabled.

If the Document Outline feature is disabled, this issue does not occur.

This is admittedly less of an issue at present because the Document Outline feature can be disabled in Options as it is an experimental feature, the only downside is not being able to use this potentially useful feature. However, if in the future, the ability to disable Document Outline is removed, it would become a more significant issue for anyone having this problem.

---
#### Feedback Bot on 8/30/2023, 09:13 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 8/31/2023, 11:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Analysis suggests that the C# Document Outline feature continues to update the tree even when the Document Outline is not currently visible. This prevents the virtualization of WPF tree nodes from working as expected, leading to the realization and update of all nodes for the entire document. The fix would be delaying Document Outline updates until such time as the window is visible.
