### ISSUE TITLE
CSharpGeneratorDriver - possible glitch re "features" (causes "Inconsistent syntax tree features" failure)

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#69906]
I'm using `CSharpGeneratorDriver` in `4.8.0-1.final` to test some AOT/Interceptors work; previously this has been fine, but recently the generator core has been hardened to demand "features" - either `InterceptorsPreview` or `InterceptorsPreviewNamespaces` (depending on the state of the code)

Because of this, I'm creating the inputs for my generators with a  specific `CSharpParseOptions`, for example:

``` c#
    internal static readonly CSharpParseOptions ParseOptionsLatestLangVer = CSharpParseOptions.Default
        .WithLanguageVersion(LanguageVersion.Latest)
        .WithFeatures(new KeyValuePair<string, string>[] {
            new ("InterceptorsPreview", "true"), // rc 1 ?
            new ("InterceptorsPreviewNamespaces", "Dapper.AOT") // rc2 ?
    });
```

the `WithFeatures` is new (i.e. our code didn't need that before the interceptors hardening) - I added it after getting CS9137:

> `The 'interceptors' experimental feature is not enabled. Add '<Features>InterceptorsPreview</Features>' to your project.`

However, `RunGeneratorsAndUpdateCompilation` now fails, citing `"Inconsistent syntax tree features"` from `Compilation.SyntaxTreeCommonFeatures`; it feels like when `CSharpGeneratorDriver` has re-parsed the generated sources, it has not applied the correct `CSharpParseOptions`.

A workaround exists:

``` diff
- driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);
+ driver = driver.RunGenerators(inputCompilation); // AndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

+ // update syntax trees to have same "options" (work around "Inconsistent syntax tree features" glitch
+ // in RunGeneratorsAndUpdateCompilation via Compilation.SyntaxTreeCommonFeatures)
+ var runResult = driver.GetRunResult();
+ var outputCompilation = inputCompilation.AddSyntaxTrees(runResult.GeneratedTrees.Select(x => x.WithRootAndOptions(
+     x.GetRoot(), RoslynTestHelpers.ParseOptionsLatestLangVer)));
+ var diagnostics = runResult.Diagnostics;
```

(basically, I add the syntax trees to the compilation myself, using `WithRootAndOptions` to put back the correct options)

I can try to do a minimal if needed, or you can run DapperAOT in the Issue27 branch: https://github.com/DapperLib/DapperAOT/tree/issue27 

the relevant tests are everything in InterceptorTests, for example Dapper.AOT.Test.InterceptorTests.Test(path: "Interceptors\\BaseCommandFactory.input.cs")

**Comment by sharwell** [comment]
The code is creating the generator driver with the default parse options:
https://github.com/DapperLib/DapperAOT/blob/76222f64027cfbf83fa5687ca8e3ea40901f50d1/test/Dapper.AOT.Test/GeneratorTestBase.cs#L72-L73

If you customize the parse options, they need to be provided in the call to `CSharpGeneratorDriver.Create`.

**Comment by f2bo** [comment]
I'm hitting the same issue when testing an incremental source generator that uses interceptors. The generator runs fine and intercepts the specified method calls successfully when used with a sample project but I've been unable to configure the GeneratorDriver for my unit tests. 

> If you customize the parse options, they need to be provided in the call to CSharpGeneratorDriver.Create.

@sharwell Below is the code I'm using, but it always fails with `'Inconsistent syntax tree features (Parameter 'trees')'` when executing `driver.RunGeneratorsAndUpdateCompilation`.

```C#
var parseOptions = CSharpParseOptions.Default
  .WithLanguageVersion(LanguageVersion.Preview)
  .WithFeatures(new KeyValuePair<string, string>[]
  {
     new ("InterceptorsPreview", "true"),
  });

GeneratorDriver driver = CSharpGeneratorDriver.Create([generator.AsSourceGenerator()], parseOptions: parseOptions);
driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);
```
> there does not exist an overload that takes incremental generators and options:

@mgravell You might want to check out the `AsSourceGenerator()` extension method that converts
an `IIncrementalGenerator` into an `ISourceGenerator` allowing you to use one of the other overloads.

**Comment by f2bo** [comment]
Found the problem. You also need to pass the same parse options to the compilation.

```C#
CSharpCompilation.Create("compilation",
            new[] { CSharpSyntaxTree.ParseText(source, parseOptions, filePath) },  // <== added parseOptions here
            new[] { MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.ConsoleApplication))
```

**Comment by sharwell** [comment]
@mgravell You shouldn't implement `ISourceGenerator` on the incremental generator itself. You can use the `AsSourceGenerator()` extension to get an instance of `ISourceGenerator` for this purpose.
