### ISSUE TITLE
[Test Failure] Vbc2.exe timed out

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#6991]
PR: [#6977](https://github.com/dotnet/roslyn/pull/6977) *Add import cna now add project references.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1499/

**Issue 1: Build Timed Out**
The build timed out, or was forcible aborted after reaching the maximum length. View the log right before the flagged timeout message to see what was happening.

**Issue 2: MSBuild Error**
error MSB6006: "vbc2.exe" exited with code 143. [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Compilers/VisualBasic/Portable/BasicCodeAnalysis.vbproj]

Build log: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1499/artifact/Binaries/Bootstrap_VbcCore.log

**Comment by jaredpar** [comment]
This is fixed by #6984.  The bootstrap phase now uses CoreCLR and hence won't hit the Mono timeout.
