### ISSUE TITLE
Support go to definition (F12) for `goto` statements, navigating to the target label

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#69916]
## Summary

Support go to definition (F12) for `goto` statements, navigating to the target label

## Background and Motivation

In switch statements more often, and perhaps in other parts of the code, `goto` statements could benefit a lot from this feature, by having a direct way to navigate to the target label that is referenced in the code, offering a better experience reading and understanding the logic.

## Proposed Feature

The proposal is to allow pressing `F12` on the `goto` statement, or the `default` keyword for a switch statement label, or the `case` keyword for the switch statement label. Examples of acceptable navigation include (with markup):
```csharp
public void Method(int argument)
{
    switch (argument)
    {
        case 1:
            [goto] [default];
        case 2:
            [goto] [case] 1;
        default:
            break;
    }
}
```

If the user uses the go to definition feature on the spans within `[]`, then they are navigated to the target label that is referenced. In the case of `goto default`, the navigator navigates to the `default:` label within the switch statement, and the `goto case 1` statement would navigate to the `case 1:` label within the switch statement.

## Alternative Designs

None.

**Comment by CyrusNajmabadi** [comment]
We would take a suitably sized PR to support this.
