### ISSUE TITLE
Add integration tests for Tools → Options

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#69929]
These issues would benefit from integration tests for Tools &rarr; Options behavior:

* #49473
* #69425

**Comment by Youssef1313** [comment]
I'm not sure if https://github.com/dotnet/roslyn/pull/62357 could help with #49473. Depending on the root cause of #49473, it could be possible that #62357 help?

Though, #62357 introduces simple unit testing, far away from the capabilities and benefits of integration tests.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, this should be assigned to someone and should be in a milestone to get it done.
