### ISSUE TITLE
Collection expressions: additional implicit conversions from builder return value are not included in semantic model

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#69938]
The additional implicit conversion (converting from the return value of a collection expression builder method to the expected target type) is not included in the semantic model.

The implicit conversion is currently stored in `BoundCollectionExpression.CollectionBuilderInvocationConversion` and only used by lowering.

**Comment by jaredpar** [comment]
Is this critical for .NET 8 or puntable post .NET 8

**Comment by cston** [comment]
The implicit conversion is only meaningful for IOperation. Resolving as duplicate of IOperation API proposal: https://github.com/dotnet/roslyn/issues/70631.
