### ISSUE TITLE
MSBuild and dotnet fails to build after .NET SDK 7.0.307

### ISSUE THREAD

**Issue by gimlichael** [dotnet/roslyn#69931]
### Describe the bug
This is a very exotic bug that was introduced after .NET SDK 7.0.307.

When you try to build a project/solution that has classes with a large amount of generics (for my case, this is 20), then the compiler goes into an infinite loop and CPU goes 100% and nothing happens. You can cancel the build and hereafter you need to kill either .NET Host or VBSCCompiler (depending wether you use Powershell or Visual Studio 2022 IDE ).

When I think about it, it could also be the level of inheritance that is an issue - or maybe a combo of the two "extremes"?

Anyway, my research shows that before things tend to go very bad, build time is drastically impacted by either excessive amount of generics or inheritance level (if more than 16, build goes into infinite loop).

### To Reproduce
To reproduce this error:

- Make sure you are using .NET SDK >= 7.0.400 (this includes .NET 8 EA as well)
- Do a  `git clone https://github.com/gimlichael/Cuemon.git`
- Step into the Cuemon folder
- Do a dotnet build (or open an IDE and run build from here)

### To Prove it worked in previous versions

- Make sure you are using .NET SDK <= 7.0.307
- Do a  `git clone https://github.com/gimlichael/Cuemon.git`
- Step into the Cuemon folder
- Do a dotnet build (or open an IDE and run build from here)

### Further technical details
There is already a bug started by a samer.alisaleh at Microsoft QnA:

- [Visual Studion 2022 Version 17.6 Hangs on Build\Clean\Rebuild All](https://learn.microsoft.com/en-us/answers/questions/1289936/visual-studion-2022-version-17-6-hangs-on-buildcle)

### Root cause

It seems that this class, [Template](https://github.com/gimlichael/Cuemon/blob/development/src/Cuemon.Core/Template.cs), which is part of the Cuemon project, is the root cause for this bug.

Yes, I know it is not best practice with so many generics / deep inheritance level, BUT it should not make the build break .. after all, the code has been similar to this since 2016 and has compiled without issues.

**Comment by jjonescz** [comment]
Thanks for reporting this issue. Looks like a duplicate of https://github.com/dotnet/roslyn/issues/69515.

The fix should be released in the next version of .NET 8 (probably RC2), but I'm not sure if it will make it into .NET 7 (the PR for that is here: https://github.com/dotnet/roslyn/pull/69635; cc @jaredpar).

**Comment by gimlichael** [comment]
> Thanks for reporting this issue. Looks like a duplicate of #69515.
> 
> The fix should be released in the next version of .NET 8 (probably RC2), but I'm not sure if it will make it into .NET 7 (the PR for that is here: #69635; cc @jaredpar).

Thanks for the update; happy that it is going to be fixed before release of .NET 8 - I will await eagerly for .NET 8 RC2.

One note though; my findings is that actually goes into infinite build time - so I agree that they are connected, but it goes from bad to unusable if high enough generics count.

I will close the issue with thanks :-)

**Comment by jjonescz** [comment]
> goes into infinite build time

That's probably just because you have a large inheritance chain and the build times in the broken version are exponential, so they seem infinite.

> they are connected

I have verified that your repro project builds fine with .NET RC2 from https://github.com/dotnet/installer?tab=readme-ov-file#table, so it should be the same issue.

**Comment by gimlichael** [comment]
> > goes into infinite build time
> 
> That's probably just because you have a large inheritance chain and the build times in the broken version are exponential, so they seem infinite.
> 
> > they are connected
> 
> I have verified that your repro project builds fine with .NET 8 RC2 from https://github.com/dotnet/installer?tab=readme-ov-file#table, so it should be the same issue.

I have set global.json to use 8.0.100-rc.2.23464.3; and it does work with dotnet build .. however, if I try to build from Visual Studio 2022, VBCSCompiler behaves like any previous version (until 7.0.400).

I just want to confirm that you are aware of this?

**Comment by gimlichael** [comment]
> > goes into infinite build time
> 
> That's probably just because you have a large inheritance chain and the build times in the broken version are exponential, so they seem infinite.
> 
> > they are connected
> 
> I have verified that your repro project builds fine with .NET 8 RC2 from https://github.com/dotnet/installer?tab=readme-ov-file#table, so it should be the same issue.

I have verified that it DOES WORK using `dotnet build` having global.json set to 8.0.100-rc.2.23464.3.

However, when building from Visual Studio 2022 Preview 17.8.0 Preview 1.0, VBCSCompiler goes into an infinite loop as before.

Just want to make sure that you are aware of this?

Thanks.
