### ISSUE TITLE
Collection literal with custom types not working

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/roslyn#69950]
### Description

When I try to apply the collection literal feature on custom types by following https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#create-methods

I got an error like

```
error CS9188: 'CustomNumberCollection' has a CollectionBuilderAttribute but no element type
error CS9188: 'CustomCollection<string>' has a CollectionBuilderAttribute but no element type
```

Not sure if the issue should be moved to Roslyn, if so, please help move it, thanks

### Reproduction Steps

```c#
CustomNumberCollection customNumberCollection = [1, 2, 3];
System.Console.WriteLine(string.Join(",", customNumberCollection.Numbers));

CustomCollection<string> customCollection = [ "Hello", "World" ];
System.Console.WriteLine(string.Join(",", customCollection.Elements));


[CollectionBuilder(typeof(CustomCollectionBuilder), nameof(CustomCollectionBuilder.CreateNumber))]
file sealed class CustomNumberCollection
{
    public required int[] Numbers { get; init; }
}

[CollectionBuilder(typeof(CustomCollectionBuilder), nameof(CustomCollectionBuilder.Create))]
file sealed class CustomCollection<T>
{
    public required T[] Elements { get; init; }
}

file static class CustomCollectionBuilder
{
    public static CustomNumberCollection CreateNumber(ReadOnlySpan<int> elements)
    {
        return new CustomNumberCollection()
        {
            Numbers = elements.ToArray()
        };
    }

    public static CustomCollection<T> Create<T>(ReadOnlySpan<T> elements)
    {
        return new CustomCollection<T>()
        {
            Elements = elements.ToArray()
        };
    }
}
```

https://github.com/WeihanLi/SamplesInPractice/blob/4fb9b8f3261bc941b2709cd133ed5675492831a1/CSharp12Sample/CollectionLiteralSample.cs#L58

### Expected behavior

Expect it works

### Actual behavior

error likes below

![image](https://github.com/dotnet/runtime/assets/7604648/3b5a90b3-7fd9-47ab-a0b6-2896bca2161a)

### Configuration

.NET 8 RC 1
Windows 11

**Comment by CyrusNajmabadi** [comment]
@cston ^

**Comment by cston** [comment]
From the spec link above:
> The collection type must have an [*iteration type*](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/statements.md#1295-the-foreach-statement).

The iteration type requires a `GetEnumerator` method that matches the expected pattern or implementation of an enumerable interface.

**Comment by WeihanLi** [comment]
@cston @eiriktsarpalis  thanks vey much
