### ISSUE TITLE
Reduce `int[]` allocations from BadArguments

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69969]
![image](https://github.com/dotnet/roslyn/assets/31348972/18312d83-c686-432e-b46c-30460dfb9005)

![image](https://github.com/dotnet/roslyn/assets/31348972/df121582-cca2-4fc3-80bd-7d972a61df21)

Most of the usages of `MemberAnalysisResult.BadArgumentsOpt` are only accessing the first element. So, instead of making this an array, it could be a simple `int?` called `FirstBadArgument`

The remaining usage where all elements are currently needed is

https://github.com/dotnet/roslyn/blob/dc3d0694a4b31b8e27038431888cd4e8dd5b6cb6/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs#L1108-L1111

and I think it should be okay to move this to `FirstBadArgument`, it will just report less diagnostics. It doesn't seem like a big deal.

**Comment by Youssef1313** [comment]
The trace above is captured using 17.8 Preview 2 and the repro I previously shared privately with some Roslyn team members. I can share the repro via DC so it's easier to access if needed. But I assume the above screenshot makes things apparent.

Note: I wouldn't expect this change to completely fix the performance issue, but it's an improvement, and small improvements can build up.

**Comment by CyrusNajmabadi** [comment]
I'm very curious how you ended up in a situation with so many bad overload resolution results.  For context, we normally see that most code is *correct*, with incorrect code being the rare/transient state of the program.  So to have 2GB of overload errors seems... strange.

>  It doesn't seem like a big deal.

I would def not feel comfortable with this.  Losing that information could be confusing for users, or impact tools that leverage that information.

Instead, what *probably* makes the most sense would be to preallocate/cache many common int[]s that show up a lot here.  I imagine given that most overloads don't have that many parameters, we could likely cover the vast majority of cases with a small number of arrays that are reused.

**Comment by Youssef1313** [comment]
> I'm very curious how you ended up in a situation with so many bad overload resolution results. For context, we normally see that most code is correct, with incorrect code being the rare/transient state of the program. So to have 2GB of overload errors seems... strange.

This happens even for correct programs. See https://github.com/dotnet/roslyn/pull/69172#discussion_r1271376600
