### ISSUE TITLE
Consider pooling `MethodTypeInferrer`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69971]
![image](https://github.com/dotnet/roslyn/assets/31348972/092e0674-16af-4f28-9c6b-59cf3283ecf4)

![image](https://github.com/dotnet/roslyn/assets/31348972/f979d8e6-4174-42d0-a601-00f9aede9d63)

1.4GB of allocations in `MethodTypeInferrer` during a 1.5 minutes trace seems a lot. Pooling might help reduce these allocations. There should be a way to cleanup the object for it to be reused though

**Comment by cston** [comment]
Perhaps `MethodTypeInferrer` should be a `struct`.

**Comment by Youssef1313** [comment]
@cston That is a good option. While `MethodTypeInferrer` has lots of fields and is quite large, it's not passed around.

**Comment by jaredpar** [comment]
Seems like a potential MQ item
