### ISSUE TITLE
700MB of `TypeWithAnnotations[]` in `GetLeastOverriddenMember`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#69977]
![image](https://github.com/dotnet/roslyn/assets/31348972/c7c928a9-7271-4d4a-98d9-ecf66cda965b)

Not sure how these can be reduced, if possible.

**Comment by CyrusNajmabadi** [comment]
Closing out. If there are suggestions, or clear indications of an issue, reopen. But otherwise, filling an issue that simply states what current behavior is is not helpful.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Before determining a fix, I think we need to understand whether `GetLeastOverriddenMember` is accessed on the same symbol multiple times, in which case, caching `TypeArgumentsWithAnnotations` in `PEMethodSymbol`, `RetargetingMethodSymbol`, `SourceMemberMethodSymbol`, and `SubstitutedMethodSymbol` might be a good option.

Currently, each access to `TypeArgumentsWithAnnotations` on the mentioned method symbols will allocate a new array.

This comes with the negative impact of increasing the object size for these symbols, but I think this increase might not be bad compared to the win of caching.

But all that is assuming that these allocations are a result of accessing `TypeArgumentsWithAnnotations` on the same symbol multiple times, which I haven't yet confirmed.

@CyrusNajmabadi What do you think? Should this be re-opened to verify my hypothesis and the potential improvement?

**Comment by CyrusNajmabadi** [comment]
I think the investigation should be done first. If it reveals something then an issue can be raised about a proposed fix. 

In other words, right now this is an issue that simply says "you are using this much memory here", that's not useful.  We could file that for each and every type in reach and every scenario. 

Something has to be actually wrong to warrant an issue (either demonstrably, or at least with a strong argument as to why it's bad)
