### ISSUE TITLE
Update ICSharpCode.Decompiler to 8.1.1

### ISSUE THREAD

**Issue by christophwille** [dotnet/roslyn#69982]
We (the ILSpy team) saw PR #69772 that upgraded the decompilation engine to 8.1. At that time, we already had one bug dogeared as "showstopper", and that is why we hadn't proposed an upgrade to 8.1.

We have now fixed the bug and backported it to a bugfix release 8.1.1 that we would highly recommend you upgrade to:

https://www.nuget.org/packages/ICSharpCode.Decompiler/8.1.1.7464

@dibarbet @CyrusNajmabadi for your consideration. Note that we kept the changes to a minimum so it is easier for you.

**Comment by dibarbet** [comment]
Ah thanks.  @andrewcrawley FYI for the debugger side.  Is this upgrade good for you?

**Comment by andrewcrawley** [comment]
Yep, looks good to me.  Thanks for the update!
