### ISSUE TITLE
Analyzer suggestion `IDE0305` ("Collection initialization can be simplified") leads to performance regressions

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#69988]
## Description

With the addition of collection literals in .NET 8, analyzer suggestion `IDE0305` has been introduced. This suggestion appears on code such as this;
```cs
int[] M(List<int> foo) => foo.ToArray(); // Collection initialization can be simplified
```
The suggested change is the following;
```cs
int[] M(List<int> foo) => [.. foo];
```

## Issue

The new syntax is certainly very nice, but actually leads to non-trivial performance regressions (up to 4x worse). You can find some benchmarking results below. I completely understand the desire for this suggestion, but find it questionable when it doesn't actually offer an equivalent outcome. Especially with all the performance-related analyzer suggestions that .NET 8 added elsewhere.

## Benchmark

```cs
[MemoryDiagnoser(displayGenColumns: false)]
public class Benchmarks
{
    private readonly List<int> _list = new();

    [Params(10, 100, 1_000, 100_000, 1_000_000)]
    public int Count { get; set; }

    [GlobalSetup]
    public void Setup()
    {
        for (int i = 0; i < Count; i++)
        {
            _list.Add(i);
        }
    }

    [GlobalCleanup]
    public void Cleanup()
    {
        _list.Clear();
    }

    [Benchmark]
    public int[] ToArray_Linq()
    {
        return _list.ToArray();
    }

    [Benchmark]
    public int[] ToArray_Literal()
    {
        return [.. _list];
    }
}
```
And here are the results on my machine;
```
BenchmarkDotNet v0.13.8, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
AMD Ryzen 5 PRO 4650U with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.100-rc.1.23455.8
  [Host]     : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2


| Method          | Count   | Mean            | Error          | StdDev         | Ratio | RatioSD | Allocated  | Alloc Ratio |
|---------------- |-------- |----------------:|---------------:|---------------:|------:|--------:|-----------:|------------:|
| ToArray_Linq    | 10      |        14.64 ns |       0.353 ns |       0.911 ns |  1.00 |    0.00 |       64 B |        1.00 |
| ToArray_Literal | 10      |        83.89 ns |       1.667 ns |       2.546 ns |  5.79 |    0.39 |      280 B |        4.38 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 100     |        33.40 ns |       0.726 ns |       1.516 ns |  1.00 |    0.00 |      424 B |        1.00 |
| ToArray_Literal | 100     |       390.53 ns |      10.235 ns |      29.695 ns | 11.67 |    0.92 |     1608 B |        3.79 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 1000    |       213.75 ns |       4.800 ns |      13.618 ns |  1.00 |    0.00 |     4024 B |        1.00 |
| ToArray_Literal | 1000    |     3,241.95 ns |      84.984 ns |     245.200 ns | 15.24 |    1.54 |    12448 B |        3.09 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 100000  |   173,960.87 ns |   3,476.459 ns |   8,329.374 ns |  1.00 |    0.00 |   400066 B |        1.00 |
| ToArray_Literal | 100000  |   535,941.57 ns |  10,345.524 ns |  11,069.595 ns |  3.09 |    0.14 |  1449123 B |        3.62 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 1000000 | 1,294,022.79 ns |  25,686.070 ns |  27,483.807 ns |  1.00 |    0.00 |  4000091 B |        1.00 |
| ToArray_Literal | 1000000 | 7,649,278.75 ns | 184,894.259 ns | 515,411.292 ns |  5.83 |    0.56 | 12389341 B |        3.10 |
```

---

Wasn't sure whether this is a runtime or a Roslyn issue. Sorry if this is misplaced.

**Comment by CyrusNajmabadi** [comment]
@cston this should be fixed soon by you right?  We should be able to generate the same code as before in this case, Right?

**Comment by cston** [comment]
https://github.com/dotnet/roslyn/pull/69875 should avoid an unnecessary buffer allocation when creating the array from the list. We should compare the cost of copying with `List<T>.ToArray()` though.

**Comment by CyrusNajmabadi** [comment]
Short circuiting to ToArray seems like the best thing here, since it has the exact desired semantics and gives the underlying collection full control to optimize. 

This goes into the ldm decisions today to allow compiler to do what is best since the result is not observable.

**Comment by CyrusNajmabadi** [comment]
Note: this probably should just go on the "to optimize" issue list we're tracking.

**Comment by just-ero** [comment]
I've done some more benchmarking below.

<details>
  <summary>Benchmark Code</summary>

```cs
[MemoryDiagnoser(false)]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
public class CollectionConversionBenchmark
{
#nullable disable
    private int[] _array;
    private List<int> _list;
    private HashSet<int> _hashSet;
#nullable restore

    [Params(10, 100, 1_000, 100_000, 1_000_000)]
    public int Count { get; set; }

    [GlobalSetup]
    public void Setup()
    {
        _array = new int[Count];
        _list = new(Count);
        _hashSet = new(Count);

        for (int i = 0; i < Count; i++)
        {
            _array[i] = i;
            _list.Add(i);
            _hashSet.Add(i);
        }
    }

    // List to Array
    [Benchmark]
    public int[] List_ToArray_Linq()
    {
        return _list.ToArray();
    }

    [Benchmark]
    public int[] List_ToArray_Literal()
    {
        return [.. _list];
    }

    [Benchmark]
    public int[] List_ToArray_Span()
    {
        return CollectionsMarshal.AsSpan(_list).ToArray();
    }

    // List to HashSet
    [Benchmark]
    public HashSet<int> List_ToHashSet_Linq()
    {
        return _list.ToHashSet();
    }

    [Benchmark]
    public HashSet<int> List_ToHashSet_Literal()
    {
        return [.. _list];
    }

    [Benchmark]
    public HashSet<int> List_ToHashSet_New()
    {
        return new(_list);
    }

    // Array to List
    [Benchmark]
    public List<int> Array_ToList_Linq()
    {
        return _array.ToList();
    }

    [Benchmark]
    public List<int> Array_ToList_Literal()
    {
        return [.. _array];
    }

    [Benchmark]
    public List<int> Array_ToList_New()
    {
        return new(_array);
    }

    // Array to HashSet
    [Benchmark]
    public HashSet<int> Array_ToHashSet_Linq()
    {
        return _array.ToHashSet();
    }

    [Benchmark]
    public HashSet<int> Array_ToHashSet_Literal()
    {
        return [.. _array];
    }

    [Benchmark]
    public HashSet<int> Array_ToHashSet_New()
    {
        return new(_array);
    }

    // HashSet to List
    [Benchmark]
    public List<int> HashSet_ToList_Linq()
    {
        return _hashSet.ToList();
    }

    [Benchmark]
    public List<int> HashSet_ToList_Literal()
    {
        return [.. _hashSet];
    }

    [Benchmark]
    public List<int> HashSet_ToList_New()
    {
        return new(_hashSet);
    }

    // HashSet to Array
    [Benchmark]
    public int[] HashSet_ToArray_Linq()
    {
        return _hashSet.ToArray();
    }

    [Benchmark]
    public int[] HashSet_ToArray_Literal()
    {
        return [.. _hashSet];
    }
}
```
</details>

<details>
  <summary>Setup</summary>

```
BenchmarkDotNet v0.13.8, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
AMD Ryzen 7 5800X, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100-preview.7.23376.3
  [Host]     : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.37506), X64 RyuJIT AVX2
```
</details>

<details>
  <summary>Results: List&lt;T&gt; to T[]</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| List_ToArray_Span       | 10      |          6.279 ns |       0.1215 ns |       0.1136 ns |          6.304 ns |       64 B |
| List_ToArray_Linq       | 10      |          8.485 ns |       0.2178 ns |       0.2420 ns |          8.417 ns |       64 B |
| List_ToArray_Literal    | 10      |         57.928 ns |       1.1851 ns |       1.1085 ns |         57.815 ns |      280 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToArray_Span       | 100     |         17.639 ns |       0.3941 ns |       0.8651 ns |         17.604 ns |      424 B |
| List_ToArray_Linq       | 100     |         19.540 ns |       0.4417 ns |       0.9219 ns |         19.437 ns |      424 B |
| List_ToArray_Literal    | 100     |        318.774 ns |       5.1887 ns |       4.5996 ns |        319.239 ns |     1608 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToArray_Linq       | 1000    |        129.227 ns |       2.4640 ns |       5.2510 ns |        130.129 ns |     4024 B |
| List_ToArray_Span       | 1000    |        137.400 ns |       2.9965 ns |       8.7882 ns |        134.304 ns |     4024 B |
| List_ToArray_Literal    | 1000    |      2,778.519 ns |      29.0893 ns |      24.2909 ns |      2,780.095 ns |    12448 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToArray_Span       | 100000  |     29,471.807 ns |     308.7392 ns |     273.6893 ns |     29,528.346 ns |   400051 B |
| List_ToArray_Linq       | 100000  |     30,568.448 ns |     590.7206 ns |     747.0724 ns |     30,594.043 ns |   400051 B |
| List_ToArray_Literal    | 100000  |    225,726.992 ns |   4,433.3135 ns |   4,146.9242 ns |    226,157.495 ns |  1449761 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToArray_Span       | 1000000 |    543,134.524 ns |  17,620.7504 ns |  51,678.6105 ns |    537,916.211 ns |  4000058 B |
| List_ToArray_Linq       | 1000000 |    547,394.485 ns |  17,325.7115 ns |  51,085.2511 ns |    551,861.133 ns |  4000052 B |
| List_ToArray_Literal    | 1000000 |  3,214,157.392 ns |  16,159.7096 ns |  13,494.0894 ns |  3,212,507.031 ns | 12389164 B |
</details>

<details>
  <summary>Results: T[] to List&lt;T&gt;</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| Array_ToList_New        | 10      |         18.766 ns |       0.3099 ns |       0.2748 ns |         18.820 ns |       96 B |
| Array_ToList_Linq       | 10      |         23.411 ns |       0.3344 ns |       0.3128 ns |         23.368 ns |       96 B |
| Array_ToList_Literal    | 10      |         57.249 ns |       0.5033 ns |       0.4708 ns |         57.229 ns |      216 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToList_New        | 100     |         29.398 ns |       0.6329 ns |       1.5524 ns |         28.983 ns |      456 B |
| Array_ToList_Linq       | 100     |         33.848 ns |       0.5942 ns |       0.5558 ns |         33.771 ns |      456 B |
| Array_ToList_Literal    | 100     |        246.623 ns |       2.8845 ns |       2.6982 ns |        246.973 ns |     1184 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToList_New        | 1000    |        141.221 ns |       2.4398 ns |       2.0373 ns |        141.731 ns |     4056 B |
| Array_ToList_Linq       | 1000    |        161.009 ns |       3.2744 ns |       8.2749 ns |        161.252 ns |     4056 B |
| Array_ToList_Literal    | 1000    |      2,559.765 ns |       7.6269 ns |       6.3688 ns |      2,559.938 ns |     8424 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToList_New        | 100000  |     27,462.438 ns |     540.4603 ns |     530.8043 ns |     27,337.073 ns |   400655 B |
| Array_ToList_Linq       | 100000  |     27,644.118 ns |     366.2739 ns |     342.6128 ns |     27,583.704 ns |   400640 B |
| Array_ToList_Literal    | 100000  |    151,268.074 ns |   2,981.7879 ns |   4,981.8977 ns |    151,565.576 ns |  1049052 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToList_New        | 1000000 |    565,843.564 ns |  16,424.3633 ns |  48,427.6058 ns |    581,619.629 ns |  4000111 B |
| Array_ToList_Linq       | 1000000 |    573,269.847 ns |  16,653.4394 ns |  49,103.0417 ns |    582,868.652 ns |  4000091 B |
| Array_ToList_Literal    | 1000000 |  2,236,961.938 ns |  43,541.8765 ns |  58,127.1545 ns |  2,249,728.906 ns |  8389175 B |
</details>

<details>
  <summary>Results: HashSet&lt;T&gt; to T[]</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| HashSet_ToArray_Linq    | 10      |         19.001 ns |       0.2711 ns |       0.2403 ns |         19.026 ns |       64 B |
| HashSet_ToArray_Literal | 10      |         57.487 ns |       0.7774 ns |       0.6492 ns |         57.436 ns |      280 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToArray_Linq    | 100     |        110.445 ns |       2.2082 ns |       2.7927 ns |        109.460 ns |      424 B |
| HashSet_ToArray_Literal | 100     |        307.863 ns |       5.9886 ns |       6.4078 ns |        309.618 ns |     1608 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToArray_Linq    | 1000    |        978.853 ns |       4.3924 ns |       4.1087 ns |        979.123 ns |     4024 B |
| HashSet_ToArray_Literal | 1000    |      2,733.981 ns |      15.9443 ns |      14.1342 ns |      2,736.214 ns |    12448 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToArray_Linq    | 100000  |    104,697.398 ns |     812.1973 ns |     759.7298 ns |    104,591.455 ns |   400059 B |
| HashSet_ToArray_Literal | 100000  |    243,311.608 ns |   3,845.3833 ns |   3,596.9739 ns |    242,922.217 ns |  1449757 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToArray_Linq    | 1000000 |  1,274,813.633 ns |  17,332.2011 ns |  16,212.5517 ns |  1,275,900.586 ns |  4000052 B |
| HashSet_ToArray_Literal | 1000000 |  3,456,654.660 ns |  37,691.6911 ns |  33,412.7024 ns |  3,463,561.719 ns | 12389164 B |
</details>

<details>
  <summary>Results: T[] to HashSet&lt;T&gt;</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| Array_ToHashSet_Linq    | 10      |         95.464 ns |       1.1996 ns |       1.1221 ns |         95.032 ns |      328 B |
| Array_ToHashSet_New     | 10      |         97.918 ns |       0.8003 ns |       0.7486 ns |         97.673 ns |      328 B |
| Array_ToHashSet_Literal | 10      |        121.111 ns |       2.3496 ns |       1.9620 ns |        121.305 ns |      664 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToHashSet_Linq    | 100     |        720.885 ns |       7.4462 ns |       6.6009 ns |        720.329 ns |     1864 B |
| Array_ToHashSet_New     | 100     |        726.435 ns |      13.1853 ns |      15.6961 ns |        721.857 ns |     1864 B |
| Array_ToHashSet_Literal | 100     |        962.670 ns |      15.3786 ns |      14.3852 ns |        964.763 ns |     6000 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToHashSet_New     | 1000    |      6,665.692 ns |      17.9592 ns |      16.7990 ns |      6,666.171 ns |    17800 B |
| Array_ToHashSet_Linq    | 1000    |      6,676.573 ns |      24.4789 ns |      22.8976 ns |      6,675.908 ns |    17800 B |
| Array_ToHashSet_Literal | 1000    |      8,966.146 ns |     109.2734 ns |     102.2144 ns |      8,981.937 ns |    58664 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToHashSet_New     | 100000  |    786,480.091 ns |   2,843.5243 ns |   2,659.8344 ns |    786,497.949 ns |  1740561 B |
| Array_ToHashSet_Linq    | 100000  |    795,446.901 ns |   3,510.8270 ns |   3,284.0297 ns |    795,701.074 ns |  1740617 B |
| Array_ToHashSet_Literal | 100000  |  1,697,832.383 ns |  10,623.4047 ns |   9,937.1394 ns |  1,700,829.688 ns |  4830509 B |
|                         |         |                   |                 |                 |                   |            |
| Array_ToHashSet_New     | 1000000 |  7,497,434.040 ns |  98,436.0805 ns |  87,261.0214 ns |  7,488,683.594 ns | 18603338 B |
| Array_ToHashSet_Linq    | 1000000 |  7,499,057.143 ns |  98,561.1696 ns |  87,371.9096 ns |  7,479,481.250 ns | 18603338 B |
| Array_ToHashSet_Literal | 1000000 | 11,339,283.021 ns | 124,053.3733 ns | 116,039.6023 ns | 11,355,682.812 ns | 43111303 B |
</details>

<details>
  <summary>Results: List&lt;T&gt; to HashSet&lt;T&gt;</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| List_ToHashSet_Linq     | 10      |         89.867 ns |       1.1545 ns |       1.0799 ns |         89.917 ns |      336 B |
| List_ToHashSet_New      | 10      |         90.543 ns |       0.8917 ns |       0.8341 ns |         90.801 ns |      336 B |
| List_ToHashSet_Literal  | 10      |        126.889 ns |       1.7622 ns |       1.6484 ns |        126.750 ns |      664 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToHashSet_Linq     | 100     |        668.276 ns |       8.1455 ns |       7.2208 ns |        670.497 ns |     1872 B |
| List_ToHashSet_New      | 100     |        677.887 ns |      10.9232 ns |      10.2175 ns |        676.415 ns |     1872 B |
| List_ToHashSet_Literal  | 100     |      1,064.004 ns |      21.1031 ns |      39.1160 ns |      1,069.287 ns |     6000 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToHashSet_New      | 1000    |      6,445.007 ns |      97.4267 ns |      91.1330 ns |      6,405.047 ns |    17808 B |
| List_ToHashSet_Linq     | 1000    |      6,447.174 ns |     120.0389 ns |     112.2845 ns |      6,463.051 ns |    17808 B |
| List_ToHashSet_Literal  | 1000    |      9,915.413 ns |     195.6726 ns |     352.8381 ns |      9,809.775 ns |    58664 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToHashSet_New      | 100000  |    774,821.523 ns |   2,644.9510 ns |   2,474.0888 ns |    773,988.574 ns |  1740546 B |
| List_ToHashSet_Linq     | 100000  |    778,434.824 ns |   4,053.5531 ns |   3,791.6961 ns |    778,914.258 ns |  1740628 B |
| List_ToHashSet_Literal  | 100000  |  1,766,466.767 ns |  11,883.7583 ns |   9,923.4764 ns |  1,768,752.539 ns |  4830510 B |
|                         |         |                   |                 |                 |                   |            |
| List_ToHashSet_Linq     | 1000000 |  7,317,385.714 ns | 105,123.3773 ns |  93,189.1358 ns |  7,324,787.500 ns | 18603346 B |
| List_ToHashSet_New      | 1000000 |  7,379,584.635 ns | 105,705.8883 ns |  98,877.3535 ns |  7,355,975.781 ns | 18603482 B |
| List_ToHashSet_Literal  | 1000000 | 11,718,668.638 ns | 173,428.0735 ns | 153,739.4699 ns | 11,733,361.719 ns | 43111307 B |
</details>

<details>
  <summary>Results: HashSet&lt;T&gt; to List&lt;T&gt;</summary>

| Method                  | Count   | Mean              | Error           | StdDev          | Median            | Allocated  |
|------------------------ |-------- |------------------:|----------------:|----------------:|------------------:|-----------:|
| HashSet_ToList_New      | 10      |         20.002 ns |       0.4408 ns |       0.7242 ns |         19.857 ns |       96 B |
| HashSet_ToList_Linq     | 10      |         26.562 ns |       0.3462 ns |       0.3238 ns |         26.588 ns |       96 B |
| HashSet_ToList_Literal  | 10      |         60.113 ns |       0.7094 ns |       0.6636 ns |         59.914 ns |      216 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToList_New      | 100     |        116.410 ns |       2.3375 ns |       2.5981 ns |        117.112 ns |      456 B |
| HashSet_ToList_Linq     | 100     |        131.848 ns |       2.4958 ns |       2.7741 ns |        131.141 ns |      456 B |
| HashSet_ToList_Literal  | 100     |        259.194 ns |       5.2333 ns |      13.3205 ns |        253.172 ns |     1184 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToList_New      | 1000    |        985.916 ns |       7.7298 ns |       6.4547 ns |        986.638 ns |     4056 B |
| HashSet_ToList_Linq     | 1000    |        987.625 ns |       6.7269 ns |       5.9632 ns |        987.857 ns |     4056 B |
| HashSet_ToList_Literal  | 1000    |      2,196.970 ns |      16.4218 ns |      15.3610 ns |      2,199.569 ns |     8424 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToList_Linq     | 100000  |    105,172.559 ns |     907.5836 ns |     848.9543 ns |    104,600.232 ns |   400091 B |
| HashSet_ToList_New      | 100000  |    105,256.725 ns |     984.7531 ns |     921.1386 ns |    104,635.339 ns |   400091 B |
| HashSet_ToList_Literal  | 100000  |    200,159.548 ns |   3,307.3638 ns |   3,093.7101 ns |    200,711.157 ns |  1049051 B |
|                         |         |                   |                 |                 |                   |            |
| HashSet_ToList_New      | 1000000 |  1,260,777.107 ns |  16,717.6285 ns |  14,819.7422 ns |  1,255,612.305 ns |  4000081 B |
| HashSet_ToList_Linq     | 1000000 |  1,261,789.240 ns |  25,047.3633 ns |  30,760.4115 ns |  1,273,667.480 ns |  4000082 B |
| HashSet_ToList_Literal  | 1000000 |  2,715,106.855 ns |  54,232.9316 ns |  62,454.7247 ns |  2,711,360.156 ns |  8389175 B |
</details>

**Comment by mavasani** [comment]
@CyrusNajmabadi Is there a specific label you associate for this new feature? Who should this issue be assigned to?
