### ISSUE TITLE
Why does code clean up automatically implement interfaces

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#69991]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Why-does-code-clean-up-automatically-imp/10467231)._

---
Running code clean up with only 
"Fix analyzer warnings and errors set in EditorConfig" and/or
"Fix all warnings and errors set in  EditorConfig"

automatically genereates implementations of methods defined in interfaces.
Why is this happening and how can I turn that off.

I feel like this only started happening after the 17.7.3 release.

---
#### Feedback Bot on 9/15/2023, 01:09 AM: 

(private comment, text removed)
#### Feedback Bot on 9/18/2023, 11:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by FrankLefeberDatema** [comment]
Why was this closed?

"Fixing an error" is meaningless if it changes build errors to runtime errors.

Please reconsider fixing this.
