### ISSUE TITLE
Confusing ref escape analysis (CS8168, CS8347)

### ISSUE THREAD

**Issue by nsentinel** [dotnet/roslyn#69990]
I can't figure out why the case noted below gives a compilation error while the other cases are compiled normally..

**Version Used**: 

.NET 8 RC.2

**Steps to Reproduce**:
```csharp
var span = new ReadOnlySpan<float>([1F]);
var x = 1F;

Process(span, ref x);
var span2 = Process(span, ref x);
span = ProcessScoped(span, ref x);

// CS8168, CS8347
span = Process(span, ref x);

return;

static ReadOnlySpan<float> Process(ReadOnlySpan<float> span, ref float m) => span;
static ReadOnlySpan<float> ProcessScoped(ReadOnlySpan<float> span, scoped ref float m) => span;

```

[A minimal repro (sharplab.io), with source-code provided](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUEQG4QBOABCgA4QyUC8lMApgO6UBKrEAJgHkYAGwCeAZTowAPADNhAewgIAfAAoA2rgBiAXQCUAblIVKADyaUdx4oQAK5BQGNWKFGtr04lcq1nmjEypPGGxLB2dXdxDvX38zQMIQ8McXN3EnBRpWPg8pWL8AmyIAehLKAGFxAA5cADZq7yrqgGYAFgB2ImTmCLTo/J9ChOLCTA7RzHruXkERCSk5RWUVSj6otR5+ITFJeiWlVWpBuMp5Q8owfSZVkJspupnt+b2Zc5W11KiMrJzN2Z2C327yOMWomWyfCG/hBl2ujFuUhsQA)

**Expected Behavior**:
Identical behavior

**Actual Behavior**:
Compilation error in one of the cases

> error CS8168: Cannot return local 'x' by reference because it is not a ref local
> error CS8347: Cannot use a result of 'Process(ReadOnlySpan<float>, ref float)' in this context because it may expose variables referenced by parameter 'm' outside of their declaration scope

**Comment by jaredpar** [comment]
In the `Process` case the `ref float m` parameter is returnable as a `ref`. That means it can be returned as a field of a `ref struct`. In this case the method could be implemented as simply: 

```csharp
static ReadOnlySpan<float> Process(ReadOnlySpan<float> span, ref float m) => 
  new ReadOnlySpan<float>(ref m);
```

The same is not true for `ProcessScoped` as `scoped ref` prohibits the value from being returned. These together influence the analysis of the consuming code. 

```csharp
// The local span is declared here and as determined to be _returnable_ because the 
// initializer expression is _returnable_. 
var span = new ReadOnlySpan<float>([1F]);

// The call to Process here is determined to be _not returnable_. The compiler has to assume 
// `ref x` is captured in `span2` and that is _not returnable_ since it's a reference to the 
// current method stack. The local span2 is declared here and is _not returnable_ as a result 
// of the init expression being _not returnable. 
var span2 = Process(span, ref x);

// The call to ProcessScoped here is determined to be _returnable_. The `ref x` cannot be returned 
// as it goes to a `scoped ref` parameter. That means only `span` factors into the returnable 
// calculation and it is _returnable_. 
span = ProcessScoped(span, ref x);

// The call to Process here is determined to be _not returnable_ (same logic as the previous 
// call). . That means we are assigning _not returnable_ to _returnable_ (as span is _returnable_) 
// and the compiler correctly issues an error. 
span = Process(span, ref x);
```

Please let me know if that explanation doesn't make sense.

**Comment by nsentinel** [comment]
Thanks for the detailed explanation!
