### ISSUE TITLE
ReverseContents?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#70]
[ArrayExtensions LIne 138](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/InternalUtilities/ArrayExtensions.cs#L138)

Is that just?

     internal static void ReverseContents<T>(this T[] array, int start, int count)
    {
      Array.Reverse(array, start, count);
    }

**Comment by mikedn** [comment]
.NET's `Array.Reverse` is not generic and therefore it has bad performance.

That said, this extension method appears to be unused.

**Comment by AdamSpeight2008** [comment]
Wouldn't suggest that it should be Generic?

**Comment by gafter** [comment]
This issue does not appear to be actionable. Unless someone can suggest what we might do in response to it, I plan to close it.
