### ISSUE TITLE
[Settings] RadioButton-based settings don't set selection on default setting

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#700]
Ported from TFS WorkItem: **1025034**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Open VS with default settings (any profile will do).

&nbsp;

2. Go to Tools|Options|TextEditor|C#|Formatting|Spacing|Set Spacing For Operators

&nbsp;

**Expected:** "Ignore spaces around binary operators" should be selected

**Actual:** None of the radio buttons are selected

&nbsp;

**Note**: This also effects Tools|Options|TextEditor|C#|Formatting|Indentation|Label Indentation

------------------------------

**Revisions:**

1) Created By David Poeschl (9/11/2014 10:45:24 AM)

Pre-assigning to Ravi because we discussed the RadioButtonViewModel and he might know what's going on there.

------------------------------

**Comment by rchande** [comment]
I can't reproduce this. I reset VS to the default C# settings and looked at the radio buttons, both of which have some selection. Can you take a look?
