### ISSUE TITLE
AddParameterCheck/InitializeMemberFromParameter refactorings should be resilient to the presence of IOperation nodes for compiler generated MyBase.New call

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#70004]
See https://github.com/dotnet/roslyn/issues/64354#issuecomment-1714014459 for more information

**Comment by jaredpar** [comment]
How impactful is this issue? Trying to decide if it's worth pushing through QB mode or fine for 17.9.

**Comment by CyrusNajmabadi** [comment]
It's minor. And API review already decided to move it to 17.9 :-)

**Comment by AlekseyTs** [comment]
#69873 Is merged, it disabled the failing tests. They should be reenabled in order to confirm that refactorings are fixed.
