### ISSUE TITLE
Disallow `RequiresLocationAttribute` in more places in source?

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#70011]
Currently, it is an error if user applies `RequiresLocationAttribute` to a parameter, but it's not an error if user applies it at other places. This is consistent with for example `ParamArrayAttribute`, but not with for example `IsByRefLikeAttribute`.

@AlekseyTs says in https://github.com/dotnet/roslyn/pull/68871#discussion_r1254439062:

> let's confirm with LDM whether we want proactively prohibit application of the attribute in other contexts in order to preserve future design space.

Example:

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwAYACDHAOgCUBXGBKMAU0oGEB7MAB1WYCcAygIBuUAMbMAzgG5ChANrVmAR1pR+0gDIdxERhxgBdUgHpTpcbX6aGKAJ6kYHUgP4d+cUgAsIUpy7MAGZBzOIIPgLMigAKEPwQYACCNhD2JuYBrjYeXr7+zq4hYRHeUYoAklIAQvbKQVpQANbMGRZuuaS0UsykAAaaQaRSCPy04X2ksCPMEAAmhBgAzMOj4xFshADehKR75CsYACykALIAFLv710qq6ppSOnoGxmbtOZ5dPf2DpJrzhgck2mCFmCwI1xucQSyVS6Te2Xcn26vT63HiiSkwJgM3mV0hpAUVVq9UaLTaiM6EBQCG8HFoAHNvFNSn4ssFQuFIpp8ZDYBFuABKXk7CH7AC+hElBEIMES0nRknI+AIouu2FI0MSKQS9iSCFGUGAtFBpBApH1huNpq2pGl0rlLCkit6FBo9EYLHYXF4KAEwn4YkkUm2vI1yjUGm0un0UEMlv4RpNvXNCaTNrtYawpGJdWCZOYaetKYtBsTxdItvtQA=)

```cs
using System;
using System.Runtime.CompilerServices;

[RequiresLocation] // currently no error, has no effect here
[ParamArray] // no error, has no effect here
[IsByRefLike] // error, use `ref struct` instead
public struct C
{
    public void M(
        [RequiresLocation] // error, use `ref readonly` instead
        [ParamArray] // error, use `params` instead
        [IsByRefLike] // error, although it has no effect here
        int p)
    {
    }
}

namespace System
{
    class ParamArrayAttribute : Attribute { }
}
namespace System.Runtime.CompilerServices
{
    class RequiresLocationAttribute : Attribute { }
    class IsByRefLikeAttribute : Attribute { }
}
```

**Comment by jaredpar** [comment]
My instinct here is that we should be disallowing in these cases. If we can squeeze this into 17.8 I would prefer that but I don't mind taking this as a small break in 17.9.
