### ISSUE TITLE
Refactor -> Extract Method ignores namespace aliases

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70024]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactor---Extract-Method-ignores-names/10453558)._

---
[severity:It's more difficult to complete my work]
When using namespace aliases (for example to avoid ambiguities) and then refactor to extract methods, Visual Studio will ignore the alias and put the main namespace back in. See video
[RefactorAlias.mp4](https://aka.ms/dc/file?name=Bb73152b67ae148caaf6773eb2164dd0d638289761800918799_RefactorAlias.mp4&tid=b73152b67ae148caaf6773eb2164dd0d638289761800918799)

---
#### Feedback Bot on 8/30/2023, 04:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
## Steps to reproduce

1. Start with the following code

    ```cs
    using Spec = System.Collections.Specialized;

    namespace ClassLibrary3
    {
        public class T
        {
            public void Method()
            {
                var value = new Spec.ListDictionary();

                Console.WriteLine(value);
            }
        }
    }
    ```

3. Select `Console.WriteLine(value);`

4. Perform an Extract Method refactoring

## Actual result

```cs
using System.Collections.Specialized;
using Spec = System.Collections.Specialized;

namespace ClassLibrary3
{
    public class T
    {
        public void Method()
        {
            var value = new Spec.ListDictionary();
            NewMethod(value);
        }

        private static void NewMethod(ListDictionary value)
        {
            Console.WriteLine(value);
        }
    }
}
```

## Expected result (per user)

```cs
using Spec = System.Collections.Specialized;

namespace ClassLibrary3
{
    public class T
    {
        public void Method()
        {
            var value = new Spec.ListDictionary();
            NewMethod(value);
        }

        private static void NewMethod(Spec.ListDictionary value)
        {
            Console.WriteLine(value);
        }
    }
}
```
