### ISSUE TITLE
I've founded a C# code that crashes Visual Studio (and VS Code C# extension)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70027]
[AB#1883913](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1883913)

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ive-founded-a-C-code-that-crashes-Visu/10462968)._

---

```
using static MyNamespace.AnyClass.AnyEnum.Val;

namespace MyNamespace;

internal class AnyClass : AnyBaseClass
{
    internal enum AnyEnum
    {
        Val
    }
}
```

---
#### Feedback Bot on 9/11/2023, 07:59 PM: 

(private comment, text removed)
#### Feedback Bot on 9/19/2023, 10:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by GRAADD** [comment]
Build failed with that error:
```
Microsoft.CSharp.Core.targets(80,5): Error  : 
Microsoft.CSharp.Core.targets(80,5): Error  : Process is terminated due to StackOverflowException.
```
