### ISSUE TITLE
Proposal: Field-targeting attributes on auto-properties

### ISSUE THREAD

**Issue by HaloFour** [dotnet/roslyn#7004]
This was mentioned on [CodePlex](http://roslyn.codeplex.com/discussions/541822) but was not implemented in C# 6.0.

I'm proposing allowing field-targeted attributes on auto-properties.  The compiler would automatically attach that attribute to the generated backing field.

``` cs
[field: NonSerialized]
public string Name { get; set; }
```

equivalent to:

``` cs
[NonSerialized]
private string name;

public string Name {
    get { return this.name; }
    set { this.name = value; }
}
```

This would bring auto-properties into parity with events which have supported this syntax since C# 1.0:

``` cs
[field: NonSerialized]
public event EventHandler Foo;
```

**Comment by alrz** [comment]
It is surprising that it is not already supported! Should be extended on records too
```cs
class Foo [Ctor] ([Param][field/property/method/return: Attr] int Value);
```

**Comment by jcouv** [comment]
Language issue was moved to https://github.com/dotnet/csharplang/issues/42
Implementation started for 7.3: https://github.com/dotnet/roslyn/issues/22512
