### ISSUE TITLE
Incorporate known spec violations

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn#70043]
@jonskeet had created dotnet/csharpstandard#756 to document where the roslyn implementation differs from the standard.

Some area already documented in the roslyn repo (where these notes should be).

This issue reminds me (or others) to incorporate what he's found that isn't already documented.

**Comment by KennethHoff** [comment]
What's the end goal of this? Update the spec? Fix the implementation? Simply document it so people are aware of it?
