### ISSUE TITLE
`CS1587` is falsely triggered when XML comments are broken up by preprocessor directives

### ISSUE THREAD

**Issue by TaffarelJr** [dotnet/roslyn#70057]
**Version Used**:
7.0.401

**Steps to Reproduce**:

1. Create a function with XML comments
2. Use C# preprocessor directives to add additional XML comments

This is a quick repro from a project that uses multi-targeting, but any preprocessor directive will do:
![image](https://github.com/dotnet/roslyn/assets/5290662/a6fdcc60-a219-40d1-af1f-c375c64fbf8e)

**Expected Behavior**:
Compiler should recognize that the XML comments are being applied to the method that comes AFTER the preprocessor directive. 

**Actual Behavior**:
The compiler thinks the XML comments are being applied to the preprocessor directive itself.

**Comment by CyrusNajmabadi** [comment]
Closing out.  The compiler is behaving correctly here as per the language spec.  Currently the lexical specification of the langauge does not allow other lexical elemetns (like pp directives) to be interspersed with doc comments.  We'd need a language change to make this happen.  Requests for that start as discussions over at dotnet/csharplang.  Thanks!
