### ISSUE TITLE
CSC task of single project taking much longer

### ISSUE THREAD

**Issue by youn123** [dotnet/roslyn#70072]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 4.8.0-3.23465.2 (a0628a05)

**Steps to Reproduce**:
Building an internal project. Please reach out to me on Teams for exact repro steps.

**Expected Behavior**:
CSC task in build takes <1 minute.

**Actual Behavior**:
CSC task in build takes ~3 minutes.

**Comment by CyrusNajmabadi** [comment]
@youn123  what does perfview show as where the time is being taken?

**Comment by youn123** [comment]
Not too familiar with perfview -- if you give me guidance on how to/what to run I can share the relevant logs.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/blob/main/docs/wiki/Recording-performance-traces-with-PerfView.md

Thanks!

**Comment by youn123** [comment]
I've added the log here for "general purpose" collection.

https://microsoft-my.sharepoint.com/:f:/p/yobae/EqF9YosVpA9DhDPqb9l03A8BOESCdvtlaxvqq1U-MG8a-w?e=PLNgSU

**Comment by CyrusNajmabadi** [comment]
The vast majority of the time is in this analyzer:

![image](https://github.com/dotnet/roslyn/assets/4564579/7e74f317-fbce-40f8-b01b-9849cad3072c)

On the exclusive CPU side, i'm seeing a lot of time spent here:

![image](https://github.com/dotnet/roslyn/assets/4564579/5c85cb88-820c-40ad-b2ca-9c8f250818e8)

I feel like this might be something that was recently looked at.  @ToddGrun is this familiar to you?

**Comment by youn123** [comment]
Thank you for the analysis. Will check if this was a recently added analyzer on our end.

**Comment by youn123** [comment]
It appears to be an analyzer we own where performance regressions may have been introduced. Build times are back to normal after merging with our latest main. Thanks for the help!

**Comment by CyrusNajmabadi** [comment]
You're welcome.  Closing out!
