### ISSUE TITLE
VSIX based analyzers don't work on adding a VSPackage item (.pkgdef) to VSIX project (VS2015 RTM)

### ISSUE THREAD

**Issue by BrianBergh** [dotnet/roslyn#7008]
After updating to RC1, create a new "Analyzer with Code Fix (NuGet + VSIX) project".
![image](https://cloud.githubusercontent.com/assets/16006094/11380013/cf8630b6-92f3-11e5-81d9-ff8ee6ba4e61.png)

Create a simple OptionsPackage class (:Package) by adding a VSPackage item to the VSIX project.

![image](https://cloud.githubusercontent.com/assets/16006094/11380110/6bb27d50-92f4-11e5-8e93-78b665a5c85a.png)

**Bonus info regarding RC1 (this bug also exists in the pre-RC)**
In the RC1, i actually get this, when i try to add a VSPackage:
![image](https://cloud.githubusercontent.com/assets/16006094/11380180/d661ae8c-92f4-11e5-946c-b6c2886ad730.png)

It doesn't matter if you choose the UserControl method, or if you use the build-in property converter method.

In this sample, i've added a usercontrol.

![image](https://cloud.githubusercontent.com/assets/16006094/11380150/a93f66d8-92f4-11e5-84a8-d897b24eb66d.png)

These are the VSIX properties:
![image](https://cloud.githubusercontent.com/assets/16006094/11380206/f7368e2a-92f4-11e5-9593-97e4e18c50da.png)

Now, if you press F5 (or at least when i do), i get this error (from the VSPackage):

![image](https://cloud.githubusercontent.com/assets/16006094/11379928/59bc0766-92f3-11e5-819e-e83f9c208088.png)

Resulting in this error in the log:
  <entry>
    <record>444</record>
    <time>2015/11/23 20:17:32.463</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CCopOptionsPackage]</description>
    <guid>{921C5AE7-5515-4020-A281-4C16AC518882}</guid>
    <hr>80131522</hr>
    <errorinfo>Could not load type 'CCop.CCopOptionsPackage' from assembly 'CCop, Version=1.0.5805.38057, Culture=neutral, PublicKeyToken=3058d244428cca12'.</errorinfo>
  </entry>

Now, when I continue, I can see, that the analyzers doesn't work. I don't get any exceptions, but it seems like if the analyzers aren't even invoked at all.

![image](https://cloud.githubusercontent.com/assets/16006094/11380303/8139d5d2-92f5-11e5-8f12-ac8cadd4de7a.png)

So, no analyzers, and no options :/

Now, stop debugging.

Try disabling the VSIX property "Include assembly in VSIX container"
![image](https://cloud.githubusercontent.com/assets/16006094/11380377/e63ddc12-92f5-11e5-9da6-24dc2228a536.png)

Now, F5 to debug again.

Still the same error dialog, and still no analyzers working (nor any options).

Even if i set all properties to false, I still can't make the analyzers work.

Now, try installing the VSIX package manually from the bin/debug folder:
At this point, the analyzers worked in VS2015 RTM, but still no luck in the Update 1 RC1.

Now, the options works (no error dialogs), but the analyzers still won't work:
![image](https://cloud.githubusercontent.com/assets/16006094/11380819/acd03242-92f8-11e5-980d-02b3825a305d.png)

Bonus info: I get this warning:
![image](https://cloud.githubusercontent.com/assets/16006094/11380879/16fc05c4-92f9-11e5-9f12-dbfe886ab9e9.png)

This is what the folder looks like:
![image](https://cloud.githubusercontent.com/assets/16006094/11380905/3265bf9e-92f9-11e5-9650-a39b2de8c6ff.png)

I have no clue what dependency it talks about, as the VSIX installer should include any dependencies, but it seems that it doesn't.

Back to VS, i try to set all properties in the VSIX package to false:
I get the same result.

But, if i reference the Analyzer project output dll manually into my test project (Consoleapp), the analyzers gets invokes, and works great.
![image](https://cloud.githubusercontent.com/assets/16006094/11381079/428a005a-92fa-11e5-8aff-fc429aa2ef4d.png)

But i still get an odd warning at the bottom (from the VSIX package) that it can't find the referenced assembly?

**Comment by BrianBergh** [comment]
@mavasani

**Comment by mavasani** [comment]
@BrianBergh Thanks a lot for filing the issue. I am going to verify your scenario on the latest Update1 bits and post an update here.

**Comment by Suchiman** [comment]
Should be fixed, @DustinCampbell already saw this here https://github.com/DustinCampbell/CSharpEssentials/issues/38#issuecomment-157141869

**Comment by mavasani** [comment]
@Suchiman There are couple of issues mentioned here:

1. On VS2015 RTM - trying to add a .pkgdef + analyzer assembly to a VSIX project causes only one of them to work.
2. On VS2015 Update1 RC - VSIX based analyzers don't work at all.

#2 was fixed by #6285 as you noted. This issue tracks investigating #1 - I'll modify the title accordingly.

**Comment by BrianBergh** [comment]
@mavasani 
I have just tested this with my project, and I can confirm that this approach works for my project as well, after updating VS2015 to Update 1RTM. Thanks for the notification :)
