### ISSUE TITLE
Parameter help and parameter autocompletion are not shown when calling base primary constructor of abstract class

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#70106]
**Version Used**: VS 17.8 Preview 2

**Steps to Reproduce**:
At each of the marked locations:
1. Type `(`.
2. Type `b`.

```csharp
abstract class A1(int a, int b);

class A2(int a, int b);

class C1() : A1$1$;

class C2() : A2$2$;
```

**Expected Behavior**:
1. The parameter help overlay is shown when typing the opening parenthesis.
2. The parameter autocompletion entry `b:` is selected.

**Actual Behavior**:
The behaviour with the abstract base class `A1` is wrong: the parameter help tooltip is never shown, and none of the parameters have an autocompletion item.
![image](https://github.com/dotnet/roslyn/assets/823398/69ae54ae-0d3b-4c86-b13d-a48e148e485d)

The behaviour with the non-abstract base class `A2` is as expected.
![image](https://github.com/dotnet/roslyn/assets/823398/095632a2-a810-4ef4-aab8-c29c496364d7)

**Comment by CyrusNajmabadi** [comment]
@ToddGrun ptal.
