### ISSUE TITLE
IDE0251 Incorrectly suggests readonly (problem area: inline arrays converting to spans)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0251-Incorrectly-suggests-readonly-p/10473998)._

---
[severity:It bothers me. A fix would be nice]
Copy the following code into VS 17.8.0 Preview 2:

```
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
public struct Repro
{
	public ByteArray20 Data;
	public ByteArray20 Hash;

public void RecalculateHash()
	{
		SHA1. HashData(Data, Hash);
	}

[InlineArray(20)]
	public struct ByteArray20
	{
		private byte _byte;
	}
}
```

VS suggests `IDE0251 Member can be made 'readonly'` for the `RecalculateHash` method. Which is incorrect. If I accept the suggestion (adding `readonly` to `RecalculateHash`), the code correctly fails to compile with CS9164; the `Hash` member can't be treated as a (non-readonly) `Span<byte>`.

---
#### Feedback Bot on 9/24/2023, 08:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
@CyrusNajmabadi this should be an easy fix
