### ISSUE TITLE
Pressing `"` should wrap selected text instead of replacing it

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70115]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-string-quotation-marks-wrapping/10474029)._

---
[severity:It bothers me. A fix would be nice]
When I have a value to wrap in quotation marks in C#, and I click shift + ", it removes the text and replaces it with a single ". This only occurs in C# solutions, because when I do the same thing in a C++ file, it works just fine, the same for any other IDE.

---
#### Alison Jin [MSFT] on 9/24/2023, 08:43 PM: 

(private comment, text removed)
#### Dylan Gaddes on 9/25/2023, 03:48 AM: 

(private comment, text removed)
#### Feedback Bot on 9/25/2023, 04:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
The editor team confirmed this is a feature the C++ team specifically implemented, but they're doing general work in 17.9 for it. Going to change the feedback ticket to instead dupe against theirs.

**Comment by jasonmalinowski** [comment]
Their feedback ticket: https://developercommunity.visualstudio.com/t/enable-the-ability-to-surround-a-selection-with-or/641608
