### ISSUE TITLE
Strange output for NormalizeWhitespace for `1 is var i`

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#70135]
**Version Used**: 4.7.0

**Steps to Reproduce**:

Run the following code:

```c#
SyntaxFactory.ParseExpression("1 is var i").NormalizeWhitespace().ToString()
```

**Expected Behavior**:

The code returns the string `"1 is var i"`, i.e. it returns the code unchanged.

**Actual Behavior**:

The code returns `"1is var i"`, i.e. there is no space between `1` and `is`. This is technically correct C#, but I find this formatting quite odd and not consistent with how `is` is formatted in other cases.

**Comment by pyoub** [comment]
Hello this is my first try contribute to ur nice project i did some analysis on this one i have the fix for it :) is't cool if i post a PR for this ?

**Comment by CyrusNajmabadi** [comment]
Yup. Totally cool. Thanks!
