### ISSUE TITLE
Analyzer assembly load failure has too generic message

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#70148]
I have hit

> CSC warning CS8034: Unable to load Analyzer assembly D:\a\1\s\Uno.Gallery.SourceGenerators\bin\x86\Release\netstandard2.0\Uno.Gallery.SourceGenerators.dll : Unable to load Uno.Gallery.SourceGenerators [D:\a\1\s\Uno.Gallery\Uno.Gallery.Windows\Uno.Gallery.Windows.csproj]

and I think the cause is not very apparent from the message. The root cause for this was:

- `ProjectA` is referencing source generator via `ProjectReference`
- `ProjectA` is built with `Platform=x86`
- This caused source generator project to be built with `Platform=x86`
- Then, for some reason, the generator assembly fails to load.

The fix was to modify the project reference as follows:

```xml
		<ProjectReference Include="..\..\Uno.Gallery.SourceGenerators\Uno.Gallery.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetPlatform="Platform=AnyCPU" />
```

It will be really great if the error message can be more explicit and says "Analyzer assembly must be built with Platform=AnyCPU"

**Comment by mavasani** [comment]
Moving to compiler team as this seems related to source generators and platform related assembly load failures at the compiler layer.

**Comment by jaredpar** [comment]
Generator error messages were changed recently to include stack traces which could alleviate this situation a bit (#70136). That should at least give the better error message. Outside that don't believe we'd be adding support for platform messages like this in the compiler.
