### ISSUE TITLE
Visual Studio keeps losing reference to App_Code.dll while coding.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70155]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-keeps-losing-reference-to-/10180388)._

---
[severity:It's more difficult to complete my work] [regression]
When working with an ASP.NET Web Site solution after a few minutes of code changes and updates VS starts to report that I need to add a reference to App_Code.dll. This doesn't happen immediately after opening the solution it takes a few minutes of making changes for it to occur. There doesn't seem to be any exact action or changes that cause it to happen. 

I've tried rebuilding the web site, the solution, just the web page. the solution compiles fine and none of those actions fixes it. The only solution I've found that works temporarily is closing VS and deleting the "root" folder in "Temporary ASP.NET Files" folder. After doing that I can reopen the solution and the issue is no longer there but then after a few minutes of changes it comes right back. 

If I double click on the error to go to the location in code where the reference is needed. I can right click on the ClassList property and select 'Go To Definition' and VS shows me a decompiled version of the WebUserControl source code instead of going to the actual code file.  See additional screen shot included.

I appears to me that when I make changes, VS will recompile those changes in the background to update intellisense and for some reason loses reference to the temp dll files. 

This issue is causing my productivity to be slowed because I'm constantly having to navigate the list of errors to see the real ones, I can't use any of the code navigation shortcuts because VS seems to think there's no symbols for the code. 

I created a simple test solution to test this and was able to make it happen. WebSiteTest.zip
If you open this solution as a web site and just start making changes to the code between the App_Code folder, the user control and the web page. After a few minutes the error starts to show.

I used the "Record your actions" option in the report hoping to capture what's happening, but I kept getting other errors so I'm not sure if that was because of the recording or not. And of course, as soon as I stopped recording the App_Code.dll reference issue happened within minutes.

Example Error: BC30652	_Reference required to assembly 'App_Code.j0ud00zh, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' containing the type 'Class1'. Add one to your project._	

I also have this issue in VS 2019 and I moved to VS 2022 hoping the newer version might solve it, but the issue still remains. So, I'm reporting this as a VS 2022 issue.

---
#### Feedback Bot on 10/24/2022, 09:37 PM: 

(private comment, text removed)
#### Feedback Bot on 10/31/2022, 04:58 AM: 

(private comment, text removed)
#### Bill Hiebert [MSFT] on 3/3/2023, 02:14 PM: 

(private comment, text removed)
#### Dave Polomis on 3/14/2023, 05:57 PM: 

(private comment, text removed)
#### Bill Hiebert [MSFT] on 3/20/2023, 00:17 PM: 

(private comment, text removed)
#### Feedback Bot on 4/24/2023, 07:47 AM: 

(private comment, text removed)
#### Feedback Bot on 6/1/2023, 01:20 AM: 

(private comment, text removed)
#### Feedback Bot on 6/29/2023, 11:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by arkalyanms** [comment]
Starting with @sharwell to narrow down area.

**Comment by CyrusNajmabadi** [comment]
Closing as we've gotten no more reports of this.
