### ISSUE TITLE
"Remove and sort usings" removed newline before first using

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#70153]
![sortusings](https://github.com/dotnet/roslyn/assets/788783/3df217c9-837b-4889-9dda-5782df0e13ad)

It happens only when `using InteractiveHost::Microsoft.CodeAnalysis.Interactive;` is out of order.

**Comment by sharwell** [comment]
Possibly related to #69309, though none of the tests affected by that change appear to include `extern alias` directives.

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community fix here.
