### ISSUE TITLE
dotnet build-server shutdown doesn't work on MacOs

### ISSUE THREAD

**Issue by kugushev** [dotnet/roslyn#70166]
**Version Used**: 
8.0.100-rc.1.23463.5
**Steps to Reproduce**:

1. Build any dotnet project using `dotnet build`
2. A VBCSCompiler process appears (I use htop to filter dotnet processes): `/usr/local/share/dotnet/dotnet exec /usr/local/share/dotnet/sdk/8.0.100-rc.1.23463.5/Roslyn/bincore/VBCSCompiler.dll -pipename:UJx__CSxvvf2HNCS30D9AxulhtCAhi9Rp_jGxaSztpo`
3. Try to kill this process using 'dotnet build-server shutdown'
4. Console output: 
```
VB/C# compiler server shut down successfully.
MSBuild server shut down successfully.
```

**Expected Behavior**:
The VBCSCompiler process should be killed (like in Windows)

**Actual Behavior**:
The VBCSCompiler is still alive

### Root Cause
VBCSCompiler checks a global mutex to prevent multiple servers from starting with the same pipename [here](https://github.com/dotnet/roslyn/blob/f7cb1f2f2bb44bc16dc96670d327b6d176f43631/src/Compilers/Shared/BuildServerConnection.cs#L73).
But the name of Mutex [doesn't contain `Global/` prefix](https://github.com/dotnet/roslyn/blob/f7cb1f2f2bb44bc16dc96670d327b6d176f43631/src/Compilers/Shared/BuildServerConnection.cs#L582).
It's okay on Windows, but not for MacOs.

**Comment by oxffaa** [comment]
Looks usefull

**Comment by jaredpar** [comment]
The impact of `Global\\` wasn't obvious to me at first so adding a bit more info here on what I found. 

Lacking `Global\\` prefix the pipe name is effectively local. The impact of that is different for each OS:

- Windows: lacking the prefix makes it local to the current user session. Other remote desktop sessions in a terminal server environment won't see it. Presence of `Global\\` prefix makes it visible to all sessions.
- Linux: lacking the prefix makes it local to effectively the shell that created it. Other shells can't see it. Presence of `Global\\` makes it visible to all shells. 
- MacOS: believe it has the same impact as Linux 

The `Mutex` guards our actions around the named pipes being created. The named pipes effectively have global scope in all the OS while the `Mutex` have a smaller scope. Moving to the `Global\\` scope puts these into essentially the same scope which is desirable here.
