### ISSUE TITLE
Cleanup DiffViewer code once editor provides an interactive diff viewer control 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#70165]
ok.  then i'm ok with this :)  thanks  @olegtk .  @mavasani can you file issue for tracking this?

_Originally posted by @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/70112#issuecomment-1737855816_

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
