### ISSUE TITLE
Handle diagnostics from HostDiagnosticUpdateSource in LSP pull diagnostics mode

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#70188]
Currently we have a custom [HostDiagnosticUpdateSource](https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/TaskList/HostDiagnosticUpdateSource.cs,22) that reports Host/VS specific diagnostics to the error list. We need to check if these diagnostics are reporting in the LSP pull diagnostics mode.

**Comment by mavasani** [comment]
@dibarbet @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
This type def isn't involved in LSP pull.  And, IMO, that's ok.  We should see if anyone knows or notices.  If they do, we can update LSP pull to pull from another diag source as well if needed :)  

LSP pull uses the IDiagnosticSource interface for this.  I'm going to close this out as non-actionable for now.  I think we can invest in these areas if we actually discover they are needed :)
