### ISSUE TITLE
C#: IntelliSense unimported suggestion items does not automatically add global namespace to using statement it adds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70218]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C:-IntelliSense-unimported-suggestion-i/10480151)._

---
[severity:It bothers me. A fix would be nice]
IntelliSense supports the feature of automatically importing unimported items. 

However, unlike using Quick Fixes, it does not add `global` scope when required, such as when there is a preference to use using statements inside namespaces. Consider this:

```csharp
namespace B
{
    using C;

    public class TestClassA
    {
        public static void SomeMethod()
        {
             SomethingInC.ABCD();
        }
    }
}

namespace A.B
{
    // IntelliSense would add:
    // using B;

    public class Program
    {
         public static void Main()
         {
             TestClassA.SomeMethod(); // <- here
         }
    }
}
```

When using IntelliSense unimported items feature to automatically add using _to_ `B.ClassA` in the above example would add `using B.ClassA`, but since the using statements are inside the A.B namespace, the compiler understands it as importing the `A.B` namespace (because somehow it searches relatively).

Quick Fixes knows this and automatically adds the `global::` scope for you, but IntelliSense somehow just doesn't.

To reproduce the issue, use something similar to above example (the above example obviously doesn't compile) and try to use IntelliSense to reference TestClassA in `A.B.Program`. IntelliSense does not add `global::` scope and a compiler error will happen wherever IntelliSense adds it.

---
#### Feedback Bot on 10/3/2023, 01:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback.
