### ISSUE TITLE
IDE0241 (Unnecessary nullable directive) reported inside unreachable #if block + not reported in others

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#70210]
**Version Used**: 4.7.0-3.23416.8 (commit 43b0b05cc4f492fd5de00f6f6717409091df8daa)

**Examples**:

- In [this example](https://sharplab.io/#v2:C4LghgzsA+DECuA7AJgUwGYAIAKBYAUAbAJZZ76yLwA21YARtapssRA00aiqQUVbQ7MATqigB7UX3wABAMyYZAJkwBhAgG8CmHYoUyAjAAYA/JgDKACgCUmALwA+TAOoBuAgF8CQA===) the diagnostic is reported inside an `#if` block that is not reached.
- Adding just an `#else` directive will no longer report the diagnostic, [example](https://sharplab.io/#v2:C4LghgzsA+DECuA7AJgUwGYAIAKBYAUAbAJZZ76yLwA21YARtapssRA00atRKlyqQJEqtDswBOqKAHtJQ/AAEAzJgUAmTAGECAbwKYDqlQoCMABgD8mAMoAKAJSYAvAD5MI6gG4CAXwJA===).
- Additionally, the diagnostic is wrongfully(?) not reported when there are successive `#nullable X` direcives with some being inside conditional directives. [Example](https://sharplab.io/#v2:C4LghgzsA+DECuA7AJgUwGYAIAKBYAUAbIvADalgBGpqmyAlhFTQUfVnvsWRdbQ0z5FUpCKiIlyzfo2nCU7Vl0m8adWUMLKe09YJZbuUvnrlaAAgGZM5gEyYAwgQDeBTO5vXzARgAMmAGUACgBKTABeAD5MFQBuAgBfAiA==)

**Expected Behavior**:

No diagnostic inside a non-executing block of code, and correctly reported in certain cases.

**Actual Behavior**:

Sometimes reported when it should not be, and some other times it is not reported when it was expected to be reported.

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community pr here.
