### ISSUE TITLE
Only suggestions for types are shown after typing `.` following `is SomeType` pattern

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#70226]
**Version Used**: 4.7.0-3.23416.8 (commit 43b0b05cc4f492fd5de00f6f6717409091df8daa)

**Steps to Reproduce**:

1. Have a type (e.g. `Constants`) containing visible constants
2. Use a pattern expression like `x is Constants`
3. Type `.` and wait for suggestions

**Expected Behavior**:

The suggestions should include the visible constants that are legal in an `is` pattern expression

**Actual Behavior**:

No suggestions containing those constants.

**Examples**:

Enter the following code in Visual Studio and place the cursor at `$$`:

```csharp
public class C
{
    public bool M(string input)
    {
        return input is Constants$$
    }
}

public static class Constants
{
    public const string
        A = "a",
        B = "b",
        C = "c";
}
```

Type out a `.` and observe the lack of suggestions. For better clarity, create a new nested type inside the `Constants` class and wait until the suggestions show, which will only include that new nested type.

**Comment by rezabashiri** [comment]
but it gives me the suggestions 
![image](https://github.com/dotnet/roslyn/assets/18233186/5c5ceb5c-dbc3-4ea8-8dde-701961b6f18e)

**Comment by Rekkonnect** [comment]
In both SharpLab and Visual Studio I don't get those suggestions. ![image](https://github.com/dotnet/roslyn/assets/8298332/72b03da5-b3ba-40bf-92c1-1fbad058f5cf)

Out of curiosity, what are you using? Perhaps Rider, or something else?
