### ISSUE TITLE
macOS tests are crashing regularly

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#70233]
`main` rolling CI has failures in macOS tests: https://dev.azure.com/dnceng-public/public/_build?definitionId=95&_a=summary&branchFilter=319%2C319%2C319

It's not always the same test, but the output is usually similar to:

```txt
The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
Microsoft.CodeAnalysis.UnitTests.EditorConfigTests.QuestionMatch

This test may, or may not be the source of the crash.
```

Unfortunately, the dump is not uploaded, so I don't know how to investigate this further:

```txt
- ⚠DumpFileToLarge: The dump /cores/dotnet_64534_1696393772_crashdump.dmp is 4647264760 bytes, which is larger than the supported 1610612736.0, so was not uploaded.
- ⚠DumpFileToLarge: The dump /cores/core.64534 is 7361921024 bytes, which is larger than the supported 1610612736.0, so was not uploaded.
```

cc @RikkiGibson

**Comment by RikkiGibson** [comment]
Thanks for investigating here. The test really does not seem very complex/intensive so would find it surprising if it really were the source of the crash.

We'll want to talk to core-eng about how we can get dumps for these runs. There might be a max size variable we can adjust while we try to triage here. Also, I'm assuming that local runs of this will pass. I can try on my Mac later potentially.

**Comment by jaredpar** [comment]
@dibarbet we need to pull a Mac OS machine off of the internal queue to try and debug this. The only other option is trying to figure out the correct `ulimit` flags to get the dumps to be reasonable size. The discussions I saw on that didn't have any firm conclusions.

**Comment by jjonescz** [comment]
Related:
- https://github.com/dotnet/roslyn/pull/71706
- https://github.com/dotnet/runtime/issues/97186

**Comment by jjonescz** [comment]
Looks like this stopped when we updated to .NET 9 in https://github.com/dotnet/roslyn/pull/73408.
