### ISSUE TITLE
"The call is ambiguous" error when using collection expressions on an overloaded method

### ISSUE THREAD

**Issue by aradalvand** [dotnet/roslyn#70236]
.NET SDK version: 8.0.100-rc.1.23455.8

This code errs:
```cs
Test.Foo(["one", "two"]);

public static class Test
{
    public static void Foo(string str)
    { }

    public static void Foo(IEnumerable<string> strings)
    { }
}
```
The error message:

> The call is ambiguous between the following methods or properties: 'Test.Foo(string)' and 'Test.Foo(IEnumerable<string>)'

Is this somehow by design?! If so then it's going to render the collection expressions feature next to useless for a large portion of use cases.
I upgraded to .NET 8 and was happy to be able to change all array instantiations `new[] { ... }` into collection expressions, assuming that it would work, but apparently it doesn't.

**Comment by cston** [comment]
@aradalvand, thanks for reporting this issue.

The issue is https://github.com/dotnet/roslyn/issues/69634 which was fixed in https://github.com/dotnet/roslyn/pull/69627.

**Comment by aradalvand** [comment]
Ah, good to know. Thanks.
