### ISSUE TITLE
Const pattern mathing with null weird behaviour

### ISSUE THREAD

**Issue by syrompetka** [dotnet/roslyn#70234]
**Steps to Reproduce**:
Following code:
```
X1 test = new X1();

if (test is { X2.Value: null})
{
    System.Console.WriteLine("zzzzz");
}

if (test is { X2.Value: not null })
{
    System.Console.WriteLine("zzzzz");
}

if (test?.X2?.Value is null)
{
    System.Console.WriteLine("eeee");
}

public class X1
{
    public X2 X2;
}
public class X2
{
    public string Value;
}
```
Outputs only:
```eeee```

Link to sharplab: [NullPatternMatching.cs](https://gist.github.com/syrompetka/699fde793af37426f45065561d19ac47)

**Expected Behavior**:

```test is { X2.Value: null}```
behaves same way as 
```test?.X2?.Value is null```

Also a bit confusing that 
```test is { X2.Value: null}```
and
```test is { X2.Value: not null }```
can be `false` simultaneously

**Actual Behavior**:
If any part of property pattern except last one is null then any constant pattern is evaluated to `false`.
Or such behavior should be described better in specs.

**Comment by CyrusNajmabadi** [comment]
This is working as expected.

`test is { X2.Value: null}`

This says that 'test' must be non-null (which it is), that X2 must be non-null (which it is not).  So this whole thing is false.

`test is { X2.Value: not null }`

This says that 'test' must be non-null (which it is), that X2 must be non-null (which it is not).  So this whole thing is false.

dotted property patterns can only succeed if they can successfully 'reach' to the end property.  if they encounter null along the way, they fail to even get to that part.  They don't shortcircuit to then saying the end property itself is null.
