### ISSUE TITLE
Xml comments on classes generated by source generators are not included in the .xml file build output

### ISSUE THREAD

**Issue by EikeSchwass** [dotnet/roslyn#70249]
**Version Used**: 
- Microsoft.CodeAnalysis.Analyzers 3.3.3
- Microsoft.CodeAnalysis.CSharp 4.1.0

**Steps to Reproduce**:

1. Create a Source Generator that adds classes with xml comments
2. Add the Source Generator to a project that has ````GenerateDocumentationFile```` set to ````true````
3. Build the project and open the generated .xml file -> the xml documentation from the source generated classes are missing

Sorry no repository atm

**Expected Behavior**:
The xml comments from the generated code should be included in the xml documentation file

**Actual Behavior**:
The xml comments from the generated classes/types are missing

**Additional Info**
We use source generators to generate our web api endpoints based on interface definitions (for legacy reasons). The xml documentation is taken from the interfaces and applied to the controllers and endpoints. Because they are not included in the xml output file, the swagger documentation is missing our endpoint documentation

**Comment by jjonescz** [comment]
Thanks for reporting this issue. Can you provide more details? I cannot reproduce this with a simple source generator: https://github.com/jjonescz/RoslynIssue70249.

The generator:

```cs
context.RegisterPostInitializationOutput(static (context) =>
{
    context.AddSource("GeneratedClass1.cs", """
        /// <summary>Generated docs.</summary>
        class GeneratedClass1 { }
        """);
});

var classNames = context.SyntaxProvider.CreateSyntaxProvider(
    static (n, _) => n is ClassDeclarationSyntax,
    static (c, _) => ((ClassDeclarationSyntax)c.Node).Identifier.Text);

context.RegisterSourceOutput(classNames, static (context, className) =>
{
    context.AddSource($"GeneratedWrapper_{className}.cs", $$"""
        /// <summary>Generated wrapper for {{className}}.</summary>
        class GeneratedWrapper_{{className}} { }
        """);
});
```

The xml doc output:

```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ConsoleApp1</name>
    </assembly>
    <members>
        <member name="T:Class1">
            <summary>
            Manual documentation.
            </summary>
        </member>
        <member name="T:GeneratedClass1">
            <summary>Generated docs.</summary>
        </member>
        <member name="T:GeneratedWrapper_Class1">
            <summary>Generated wrapper for Class1.</summary>
        </member>
        <member name="T:GeneratedWrapper_GeneratedClass1">
            <summary>Generated wrapper for GeneratedClass1.</summary>
        </member>
    </members>
</doc>
```
