### ISSUE TITLE
We should have good documentation links for installing VS build tools or Mono

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#70281]
After https://github.com/dotnet/roslyn/pull/70263, we'll show an error if we tried to find either the VS build tools or Mono on the machine, failed, and then also failed to load the project with .NET Core. We should write up some docs and update the error messages to point to them to help users in this case.

An alternative is just find existing documentation that's good enough and use that.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
