### ISSUE TITLE
Pull method up to interface doesn't show interface name when method name is too long (matters when multiple interfaces)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70316]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pull-method-up-to-interface-doesnt-show/10486656)._

---
[severity:Other]
When a method has a long name, which is undesirable but it happens, it becomes impossible to know which interface one is attempting to pull a method up to with the 'Pull method up to interface' quick refactor.

![image](https://github.com/dotnet/roslyn/assets/1408396/b2912077-9a6c-47c9-8132-307d945dae0f)

![image](https://github.com/dotnet/roslyn/assets/1408396/defbf0b2-0e09-4a24-b532-e827606584a0)

Some suggestions when hovering over an option:

- The name of the interface be displayed in the preview view that pops up. (e.g `Lines 7 to 9 of ISomeInterface`). Sometimes you could tell the context from other methods that appear in the interface preview but not always.
- The method name shortened like:
 `Pull GetObjectFrom... up to ISomeInterface`
- A normal tooltip could appear on hover of an option with the full unabbreviated text.

---
#### Feedback Bot on 10/9/2023, 08:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
For the nested menu case, it seems like the method name would not be necessary at all.
