### ISSUE TITLE
Context -bound nameof() operator

### ISSUE THREAD

**Issue by comdiv** [dotnet/roslyn#7031]
For now:

```
// it's legal code
public const string S = nameof(S); 


public void Method() {
   //this is not
     var _s = nameof(_s);
}
```

In second case it fail with "Cannot use local variable '_s' before it is declared ".

I understand that problem is scope and renaming - right side knows outer scope.

My suggestion - add context-bound nameof() operator - for example  `nameof(var)`,
`nameof(void)` and `nameof(class)`. Checked - for now all
this forms are compile error - so they can be used.

```
namespace A{
class X {
    protected string fieldname = nameof(var); // should be "fieldname "
    protected string declname = nameof(class); //sould be "A.X"
    protected string tname = nameof(this); // "A.X" here
    protected string bname = nameof(base); // "System.Object" here
    virtual void Print () {
        var _x = nameof(var); // should be "_x"
        var y = nameof(void); // should be Print
        Console.WriteLine( $"{fieldname} {declname} {tname} {bname} {_x} {y}");
    }
}
class Z : X {}
}
...
new X().Print();
// cout:   fieldname A.X A.X System.Object _x Print
new Z().Print();
// cout:  fieldname A.X Z.X A.X _x Print
```

from my point of view:

```
keywords and it's implementation

nameof(class) - always name of DECLARATION class 
     inplace substitute with string literal

nameof(this) - name of current object instance class 
    if in static context - same as nameof(class), if not - 
    add `private static @____this_name =    nameof(class)` 
    in all classes where 1) nameof(this) is in compile body 2) if base class has such 
    field (mean that it's possible that nameof(this) is in ancestor's methods)
    and then replace `nameof(this)` with `@____this_name`

nameof(base) - name of base class of current - 
    same as `nameof(this)` but with referencing parent class 


nameof(void) - name of closest Method in scope - 
    simply lookup closest Method declaration. So it will be work in lambda too:
        public void X() {
            var t = new {1,2,3}.Select(i=>nameof(void)+i);// it's still X1, X2, X3
        }
alternate to nameof(void) can be nameof() - with empty braces
But if it's in property it should reference Property name:
    public string X {
        get { return nameof(void);} // "X"
    }
    so nameof() is looks like better syntax than nameof(void)


nameof(var) - name of left side in initializers (variables,fields, properties)
        lookup for closest initialize variable operator and take it's name part
    if it's not variable initializer - it lookup for Property or Field initializer and get name from it

```

Profit:
It's better for refactoring without tools - we not require replacing in several places.
It's allow to reference left side variable
It's good for logs, exception formating - code became more readable and avoid usual copy-paste errors that are common for such code parts:

```
void Op1(){
    log.Debug($"start {nameof(Op1)}");
    ....
    log.Debug($"finish {nameof(Op1)}");
}
void Op2(){
    log.Debug($"start {nameof(Op2)}");
    ...
    log.Debug($"finish {nameof(Op1)}"); //uuupss
}

but if nameof(void) will be added:
void Op1(){
    log.Debug($"start {nameof(void)}");
    ....
    log.Debug($"finish {nameof(void)}");
}
void Op2(){
    log.Debug($"start {nameof(void)}");
    ...
    log.Debug($"finish {nameof(void)}");
}
```

It's good for code generation - we not require control all names if just require generate some logging / serialization logic
It's good in custom serialize-deserialize while nameof(var) can be used

It's not breaking change.

**Comment by alrz** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/designNotes/2015-03-04%20C%23%20Design%20Meeting.md

>This works the same as with any other construct, i.e.: not. This is not a special case for `nameof`, and it doesn't seem worth special casing to allow it.

**Comment by comdiv** [comment]
nameof is operator to kill doubing, ambiguity and magic-strings - think it should be extended

**Comment by m0sa** [comment]
+1 would love to see this

**Comment by jrmoreno1** [comment]
I found this by looking to see if someone  had already reported a need for nameof(void) -- I have several projects where that would make adding properties much easier; the property references a resource that is supposed to have the same name (config file or resources), I could then use the same code for all of them, just changing the property name and it would work.  While nameof(property) is better than "property", it is still a bit fragile because of copy/paste/edit (or rather not editing).

**Comment by comdiv** [comment]
+1 
resource idea is very good, I think - it can be even with localization support.

**Comment by jrmoreno1** [comment]
An additional usage that might be beneficial (encountered just today) is referencing a parent class or namespace -- but I can't think of a good syntax for it.

**Comment by gafter** [comment]
Issue moved to [dotnet/csharplang #345](https://github.com/dotnet/csharplang/issues/345) via [**ZenHub**](https://www.zenhub.com/)
