### ISSUE TITLE
Inline hints should cache and reuse measurement data

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70315]
Originally filed as [AB#1898407](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1898407)

**Version Used**: 16.11.34031.81

**Steps to Reproduce**:

Enable inline hints in a large source file during active editing.

**Actual Behavior**:

Significant time on the mean thread is spent in the following call:
https://github.com/dotnet/roslyn/blob/0caa880a161057559d1dcaad890e4053f520136e/src/EditorFeatures/Core.Wpf/InlineHints/InlineHintsTag.cs#L163

Since this measurement occurs with a generally unchanging font and outside of the normal visual tree, its result could be cached and the width and height set directly from the cache whenever the text and properties haven't changed.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
