### ISSUE TITLE
Overload resolution prefers Span<T> over ReadOnlySpan<T> for collection expression

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#70318]
**Version Used**: 

**Steps to Reproduce**:

Compile and run:
```csharp
using System;

class Program
{
    static void Main()
    {
        M([1, 2, 3]);
    }
    
    static void M(Span<int> span) { Console.WriteLine("Span<int>"); }
    static void M(ReadOnlySpan<int> span) { Console.WriteLine("ReadOnlySpan<int>"); }
}
```

See [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBUQAT7EDsFA3hdW7cQGy0As1AstBgAKAJSt2LcuxkDhAbWJxqhZQGYAuqIDcEtgF891I3W74+/YQGUADhBgAeWAgB81AM52Yo6kw4BOYQAiW3snGFcgnWpDaXZTXjkAJQBTCAwAeRgAGwBPUMdnN097Hz86QKDU9Ky8gvDI6Nj9IA===)

**Expected Behavior**:
`ReadOnlySpan<int>`

**Actual Behavior**:
`Span<int>`

Reported by @stephentoub

**Comment by CyrusNajmabadi** [comment]
Isn't span the more specific type, since it can be converted to ROS?
