### ISSUE TITLE
Visual Studio C# text editor indentation for "else switch"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70314]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-C-text-editor-indentation/10486709)._

---
[severity:It bothers me. A fix would be nice]
Minor issue with indentation (minor because it's the first time I've had a need to do this in 23 years!):

```cs
    public class IndentingClass
    {
        private enum State { A, B, C };

        public void InconsistentIndenting(bool condition, State state)
        {
            // If an "if" statement is on the same line as a preceding "else", the indentation matches the "else" (as expected)
            if (state == State.A)
            {
            }
            else if (state == State.B)
            {
            }

            // However, other statements on the same line as an else (such as "switch") don't receive the same treatment and get extra indentation
            if (condition)
            {
            }
            else switch (state)
                {
                    case State.A:
                        break;
                    case State.B:
                        break;
                }
        }
    }
```

The obvious workarounds are to drop the switch to the next line, or surround it with braces, but despite it being an unusual construct, and though some may not consider it the best style, the treatment of "else switch" seems inconsistent with the treatment of "else if" (which is obviously a very common construct). 

The same is also seems to be true of other statements ("else while", "else do", "else try", etc) and although I've never come across a good reason to use those without surrounding braces, I think that given the language allows a single statement to follow an "else", it makes sense that they should be indented consistently.

---
#### Feedback Bot on 10/9/2023, 09:37 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
The recommended style for C# (per the style guidelines in dotnet/runtime) would be to use the following:

```cs
if (condition)
{
}
else
{
    switch (state)
    {
        case State.A:
            break;
        case State.B:
            break;
    }
}
```

**Comment by Giles-Smith** [comment]
Thanks for the feedback @sharwell.

The guideline recommends always using braces for multiline statements, but if you ignore that recommendation (it is, after all, only a guideline), I would expect the editor to indent consistently. There may be merit in the argument about avoiding the potential of misreading "else switch" as the far more common "else if", but I would expect it to be ultimately the author's choice (without having to fight the editor). That said, it's a very minor quibble, and I'll probably end up using braces anyway :)

**Comment by CyrusNajmabadi** [comment]
else-if is a common construct.  else-switch is not.  We don't really put effort into construct combinations that aren't realistically seen/used.  It's too much effort/complexity for literal one-off cases.

Thanks!

**Comment by starikcetin** [comment]
I understand that you might not want to spend time on this, but are there any workarounds at least? I would definitely expect the behaviour described in this question to be the default, and not the other way around.

**Comment by CyrusNajmabadi** [comment]
> I understand that you might not want to spend time on this, but are there any workarounds at least? I would definitely expect the behaviour described in this question to be the default, and not the other way around.

There are no workarounds I can think of. Toys simply is not a supported case.
