### ISSUE TITLE
Interceptor for non-existent methods?

### ISSUE THREAD

**Issue by f2bo** [dotnet/roslyn#70317]
I've implemented a managed wrapper for a native library where one of its functions takes a printf-like format argument and a variable number of arguments. 

Given that there's currently no cross-platform mechanism in .NET to handle a variable number of arguments, I mapped this to a managed method that takes an interpolated string handler argument as well as a set of generic overloads with a fixed (and increasing) number of arguments. In this case, all formatting occurs on the managed side and the native side only ever receives a single string argument with no format specifiers.

```C#
void Log(LogLevel level, [InterpolatedStringHandlerArgument(nameof(level))] ref LogInterpolatedStringHandler format) {...}

void Log(LogLevel level, string format) { ... }
void Log<T1>(LogLevel level, string format, T arg1) { ... }
void Log<T1, T2>(LogLevel level, string format, T1 arg1, T2 arg2) { ... }
void Log<T1, T2, T3>(LogLevel level, string format, T1 arg1, T2 arg2, T3 arg3) { ... }
```

New applications using the managed wrapper would likely use the interpolated string overload. However, in order to test the managed wrapper, I began porting a few existing C applications and find that one of the more time consuming and error prone aspects is the translation of the format specifiers.

So I thought this would be a good excuse to experiment with interceptors and implemented a source generator that intercepts calls to the `Log` method and translates the C format specifiers to an interpolated string. 

For example, given the following call:
```C#
Log("Error: %d, message: %s", code, message);
```

The source generator emits the following interceptor:
```C#
[global::System.Runtime.CompilerServices.InterceptsLocation("...", line: ..., column: ...)]
internal static string Log<T1, T2>(int logLevel, string format, T1 arg1, T2 arg2)
  => Log(logLevel, $"Error: {arg1} - message: {arg2}");
```

This works very well until the number of format specifiers in the original format string exceeds the overload with the largest number of arguments. While the source generator emits valid code in this scenario, since it only requires the interpolated string handler overload, there's an error at the call site as this would require an overload with arguments T1 to T4.  For example:

```C#
Log("Error: %d, message: %s, item A: %d, item B: %d", code, message, 123, 456);
```

I can always keep adding overloads with more arguments to the managed wrapper, but given that these are never actually invoked and that instead, the code that matters is the one emitted by the source generator, it doesn't seem farfetched to think that it should be possible to support intercepting calls to non-existent methods.

The spec mentions ```Interceptors are treated like a post-compilation step in this design. ```, so I guess that's the reason why this currently fails at the call site but I thought I would bring this up in case there's a mechanism that could allow this.

[jcouv update:] Relates to test plan https://github.com/dotnet/roslyn/issues/67421

**Comment by jcouv** [comment]
Tagging @RikkiGibson to advise on design question. In my opinion, we should not do this. Interceptors are seen as an optimization and the program should remain valid in absence of interceptors.

**Comment by f2bo** [comment]
>  Interceptors are seen as an optimization and the program should remain valid in absence of interceptors.

This was also an experiment for me and I don't feel very strongly about it, but I would like to understand the reasoning. Leaving aside the fact that it's an experimental feature, under what other circumstances would an interceptor be absent? Couldn't the same be said for any program that relies on generated code if its source generator is unavailable. Why is this different for interceptors?
