### ISSUE TITLE
"Cannot navigate to the symbol" message box after successfully opening definition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70323]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-navigate-to-the-symbol-message-/10486983)._

---
[severity:It bothers me. A fix would be nice]
I've noticed that after going to the symbol definition (F12) I'm forwarded to proper definition but message appears: "Cannot navigate to the symbol under the caret"

---
#### Feedback Bot on 10/9/2023, 09:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@olegtk  Public report of the issue we were discussing earlier.  Something is up (likely with async doc load).

**Comment by olegtk** [comment]
@RadwanFaci, @AmadeusW

**Comment by CyrusNajmabadi** [comment]
Closing out as this hasn't been reported in a while.  I'm guessing it was in editor/platform and was fixed.
