### ISSUE TITLE
View.SynchronizeClassView command is not implemented

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#7034]
We forgot to implement this command in Visual Studio 2015 after introducing the Roslyn language service.

Original reported on Microsoft Connect [here](https://connect.microsoft.com/VisualStudio/feedback/details/1305402/view-synchronizeclassview-keybinding-does-not-work).

**Comment by royog** [comment]
I cannot get this command (View.SynchronizeClassView) to work at all. I'm on VS 2015 Enterprise V 14.0.24720.00 Update 1 using C#.

**Comment by DustinCampbell** [comment]
Unfortunately, VS 2015 Update 1 does not include this bug fix (it was released on November 21st). However, VS 2015 Update 2 RC was just released a few days ago and does include this.

**Comment by royog** [comment]
Awesome! I just installed **VS 2015 Update 2 RC**, and the **SynchronizeClassView** functionality is **_indeed working_** in this release as you have indicated.

Thank you Dustin!

I'd love to see that <-- over --> icon on top of the Class View window someday ... just like the one on the top of the Solution Explorer window. I'm sure lots more devs would use it (and know it existed) if it were prominently displayed there by default. That said, I'm extremely happy that it's working now in any case!!

Roy

**Comment by CompleteBrains** [comment]
@DustinCampbell 
Thank you, I missed it too.

**Comment by GitteHubert** [comment]
I can confirm that the command is working with solutions that don't have any solution folders.
But, if you nest a project in a solution folder, the command will bring up the class view, but not synchronize the current code element.
Interestingly, the very same buggy behaviour has been reported in the past for previous VS versions:

social.msdn: [Synchronize Class View command still does not work in Solution folders?](https://social.msdn.microsoft.com/Forums/vstudio/en-US/5a0b0946-dc66-436c-9365-f8a003201f85/synchronize-class-view-command-still-does-not-work-in-solution-folders?forum=vseditor)

blogs.msdn: ["...I cannot get it to work for projects in solution folders"](https://blogs.msdn.microsoft.com/ansonh/2005/12/09/synchronize-class-view/) (see comments)
