### ISSUE TITLE
Why de-facto keywords "nameof" and "var"  can be overriden chaotically? Make them keywords.

### ISSUE THREAD

**Issue by comdiv** [dotnet/roslyn#7035]
For now nameof() is not a keyword and it cause not predictible behavior:
```
 string nameof(Action a)
        {
            return "Damned!!!";
        }

	    int A() {
	        return 1;
	    }

        [Test]
        public void NameofOverload2()
        {
            Console.WriteLine(nameof(NameofOverload2));
            Console.WriteLine(nameof(A)); // compiler error
        }

```
So, it someone keep `protected string nameof(...)` in base class it's never be possible to use `nameof` of C# 6 with it's descendants?

Another sample
```
 class var { }

	    public void Varer() {
	        var x = 1; //compiler erorr
	    }
```

It's not good design. While `var` and `nameof` are de-facto keywords i think they should be real keywords.

So if someone very and very want to use it for self proposes - they should use well-known `@var` `@nameof` syntax in this case.

Where are many words in C# that maybe usefull for someone as names (`params`, `default`) but they are legal keywords and developers migrate to @params or _params or args...

Even wander that C# allow so hackish code (it compiles well):
```
string nameof(Action a)
        {
            throw new NotImplementedException("Please install real C# 6 from http://coolcs6.org/x--zz.exe");
        }
public void IWantUseCs6()
        {
            Console.WriteLine(nameof(IWantUseCs6));
        }

        class var { }

	    public void Varer() {
	        var x = new var();
	    }
```

**Comment by HaloFour** [comment]
Because the C# team doesn't like breaking existing code bases.  This decision was very intentional.

**Comment by axel-habermaier** [comment]
What you suggest would break backwards compatiblity; i.e., old code might no longer compile after this change or change its meaning silently. That's why it was not possible to make ``nameof`` and ``var`` keywords, and most likely that will never happen.

Additionally, what you describe is not likely to be a problem anyway -- if you follow .NET naming conventions (which you should), types and methods start with capital letters, so there can be no conflict.

**Comment by sharwell** [comment]
Perhaps there was a case to be made at the time these keywords were introduced, but now that the compiler has shipped with these context-sensitive keywords having special behavior I don't think it makes any sense to reconsider the decision at this point.

**Comment by comdiv** [comment]
@axel-habermaier If developer cannot migrate and change var to @var or to _var - he can continue use C# 2. Why not?
If he want to use new language version - he must to know what keywords was added.
May be you can tell that `async` and `await` should not be keywords? They was added to C#5 and all developers was pushed to rename their own `async`s as names. It's not problem for living codebase and it's not problem for old codebase while they use older building tools. (For ex where are many code for C# 2 and 3.5)

@sharwell  i start read tokenizer deeply in roslyn - may be (if it will be time) i'll find and fix tokenizer to produce "VarSyntax" and "NameofSyntax" instead of current IdentifierSyntax that is attached for them. And you are right - such changes will cause cascade of changes in parser and binder. Because for now `var` is just mnemocode to force substiute type from rightside and `nameof(xxx)` treated as usual method invocation at parser level and resolved only at binding stage.

**Comment by paul1956** [comment]
@axel-habermaier  why did VB make the opposite decision wrt NameOf? In VB NameOf is a Keyword and when I compiled code that had NameOf defined as a function I needed to change the source (which was a good thing).

**Comment by comdiv** [comment]
@axel-habermaier  Looking Roslyn code i have opinion that such chatic implementation was just simple-to-implement (because they are resolved after parser phase). So for parser `var` is nothing more than usual name and nameof is just identifier too. Parser knows nothing about them and SyntaxTree don't know nothing about NameOf construction - it is resolved only at linking (binding?) phase.

**Comment by comdiv** [comment]
@HaloFour "Because the C# team doesn't like breaking existing code bases. This decision was very intentional."

What about `yield`, `partial`, `default` of C# 2.  And then it was `dynamic`

Ok you'll say that just C# 4 became really C#

But what about  , `async`, `await` added to C# 5?

It was another "C# team?" or may be magically this words was never used in "existing code bases"?

**Comment by Pilchie** [comment]
None of those examples are actually breaking.  They are all what we call "contextual keywords", it's just that their context is purely syntactic, whereas `var`, `dynamic`, and `nameof` require semantics to determine the context.

To give a specific example, `yield` is still perfectly valid as an identifiers (developers writing bond trading software probably would have been upset with us if we'd broken that!), it's only considered a keyword if it's immediately followed by either `break` or `return`.  `default` was *always* a keyword (in switch statements).  `partial` is only valid immediately before `class` or `void`, etc.

No new keywords have been added to C# since C# 1.0.

**Comment by HaloFour** [comment]
@comdiv 

You've just rattled off a long list of keywords added contextually so that all existing C# 1.0 code would continue to compile without any changes.  The following is perfectly legal C# 7.0 code:

```cs
int yield = 1;
int async = 2;
int await = 3;
int dynamic = 4;
int partial = 5;
int var = 6;
int nameof = 7;
```

**Comment by Pilchie** [comment]
@paul1956 BTW - the decisions for C# and VB were different because the histories of those languages and the precedent's set previously were already different.  Additionally, due to the larger number of and case insensitivity of VB, VB users are already more used to needing to escape keywords than C# users are, so it was deemed less of an issue there.

Tagging @MadsTorgersen  and @AnthonyDGreen on this thread as well.

**Comment by paul1956** [comment]
@Pilchie for VB you made absolutely the correct decision, thanks for explaining why.

**Comment by comdiv** [comment]
@HaloFour  you're right. I mistaken about history of keywords and ability of those usage.
But yield, async, await and partial could never be in interchangeable context.
Same as let, from, where.

While dynamic, var, nameof can be overriden and crash expected behavior of "semi-keywords" - it's not valid situation. When i write `int yield =1` it doesnt' change behavior of `yield return`  but `class var{}` `class dynamic{}` cause crashing, `string nameof(...)` crash `nameof`. Another situation in compare to `partial`.
At least it should be option of compiler - if such names are allowed for variables, classes and members.

**Comment by HaloFour** [comment]
Not liking it doesn't make it invalid.  It's very easy to make that decision when you don't have millions of lines of code (or have to answer to very large businesses with billions of lines of code).  The C# team played defensively and I think the majority of people benefitted as a result.  As mentioned if you stick to the C# naming guidelines it's a situation you'll never run into anyway.

It's been mentioned in other threads that the team is also not interested in introducing dialects of the language, so switches to change the behavior of keywords is equally unlikely.

**Comment by sharwell** [comment]
> @sharwell i start read tokenizer deeply in roslyn - may be (if it will be time) i'll find and fix tokenizer to produce "VarSyntax" and "NameofSyntax" instead of current IdentifierSyntax that is attached for them. And you are right - such changes will cause cascade of changes in parser and binder. Because for now `var` is just mnemocode to force substiute type from rightside and `nameof(xxx)` treated as usual method invocation at parser level and resolved only at binding stage.

We already went through this once after commit 36bdd5390f8184df51451b21afeac56f35f1a854, and had to update all of our analyzers that looked at these expressions. I would prefer to not have to do that again. :smile:

**Comment by comdiv** [comment]
Ok, after @HaloFour  and @sharwell  i think that trying to request something from C# at it's core is too egoistic. While  i don't want create own "Comdiv C#++" i think i will more use meta-programming support that Roslyn provide while it's some kind of zone where it is able to update C# codebase to more clear (for me) state.

**Comment by HaloFour** [comment]
@comdiv If anything the decision to *not* break everyone's code is very non-egotistic.  Demanding that the team and the entire world has to adapt to meet your standard of "clear" and "valid", however, fits the definition quite well.

**Comment by comdiv** [comment]
Don't understand what you said. I've said that my try to make them keywords is egoistic (from me) from what you not agree?

**Comment by HaloFour** [comment]
@comdiv Ah, sorry, communication failure on my part.  I'll delete the comment.  It wasn't constructive anyway.

**Comment by sharwell** [comment]
@comdiv You raise an interesting point. I went back to see how we detect `nameof` expressions, and it turns out we actually don't - at least not in the general sense. Take a look at the following:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/f1cfec336f14db111d9b684da27e8df3bb9f8b5a/StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121UseBuiltInTypeAlias.cs#L284-L307

It seems like there should be an easier way in general to distinguish `nameof` expressions from another invocation of a method named `nameof`, even if it's just a helper method we create as a community outside of Roslyn itself.

**Comment by comdiv** [comment]
I already see it while i try to implement #7031 but it will get more time that i was thinked about.
For example i can parse `nameof()` and `nameof(this)` and `nameof(base)` but `nameof(class)` will require check SkippedText not arguments...  so it require be more competent in your code and model, more time.

**Comment by bondsbw** [comment]
Does anyone know if there exists a set of analyzers for making this and other potentially confusing syntax illegal?  Or if there is an official set of such analyzers?

BC is very important, but being able to opt-out for the sake of clarity would be a win IMHO.

**Comment by sharwell** [comment]
@bondsbw Which of the following is your question:

1. Is it possible to disable the new `nameof(...)` expression introduced in C# 6?

    Answer: Not by itself. You could set the `<LangVersion>` property in your project file to 5, which would disallow the use of all new syntax features added in C# 6. You would have to create a new analyzer if you wanted to just disable the `nameof` expressions.

2. Is it possible to disable the creation of members named `nameof`, to ensure that the use of `nameof` always just means it's a `nameof` expression?

    Answer: You could easily create an analyzer to do this. I believe it would have limited use in practice since I've never actually seen a member named that (outside of examples meant to demonstrate the conflict).

**Comment by comdiv** [comment]
My - is second veriance. I very like nameof(...) operator and wish that it will be extended (as i describe in other issue #7031). But i still think that `var` and `nameof` should be deprecated as identifiers, while it can cause ambiguity and silent override of it's usual behavior. For I not think so about `partial` while where is no chance where context of name `var partial` can overlap with `partial` in class/member definition. So it's candidate may be not for Error, but for Warn at compiler level to guard from such naming and force renaming and using `var` and `nameof` only as "keywords"

**Comment by bondsbw** [comment]
@sharwell Neither is really my question.  My question is whether there *already* exists a set of useful analyzers that would be useful for the 99%+ of projects that don't rely on backwards compatibility.

**Comment by sharwell** [comment]
@bondsbw There are hundreds of analyzers that have been implemented, and are intended to be helpful in a variety of ways. What are the analyzers you're looking for supposed to check for and/or do about it?

**Comment by comdiv** [comment]
OK i will use analyzers for such things.

**Comment by bondsbw** [comment]
@sharwell Are they official and solve problems like this?  Or are you just saying that some analyzers exist somewhere?

**Comment by sharwell** [comment]
@bondsbw I took a guess at what you were looking for, and the following was your response (emphasis mine):

> **Neither is really my question.** My question is whether there already exists a set of useful analyzers that would be useful for the 99%+ of projects that don't rely on backwards compatibility.

At this point, I still do not know what *specifically* you are looking for, so I don't know what direction to point you in. If you describe exactly what you want an analyzer to look for and what messages you want it to report, I can help you get where you want to be. :smile:

**Comment by bondsbw** [comment]
@sharwell I apologize, I really feel that my questions have been to the point but you seem to be going in a very different direction.  I'll try to word them as directly as possible:

Does Microsoft officially support a set of analyzers that take the undesirable parts of C# out, such as those which were preserved primarily for backward compatibility?

For example:  Is there an analyzer that Microsoft officially supports that removes "nameof" as a possible identifier?

If there is, where can I find it?  And if it exists, does it exist with other analyzers that fix other less desirable language features such as those [listed here](http://www.informit.com/articles/article.aspx?p=2425867)?

I'm not interested in learning how to write analyzers, I already know how to do that.  If the answer is "no" to the above questions, and Microsoft or some third party is unwilling to invest the time to create such a library of analyzers, that's perfectly fine and I'll write my own.  But mine won't likely be as robust as official analyzers, so I figured I would ask.

**Comment by sharwell** [comment]
> Does Microsoft officially support a set of analyzers that take the undesirable parts of C# out, such as those which were preserved primarily for backward compatibility?
>
> For example: Is there an analyzer that Microsoft officially supports that removes "nameof" as a possible identifier?

From what I can tell, it does not currently exist, but issue dotnet/roslyn-analyzers#451 has been filed to create it.
