### ISSUE TITLE
Intermittent MSB6006 compiler failures using CodeQL in GitHub Actions

### ISSUE THREAD

**Issue by martincostello** [dotnet/roslyn#70368]
For some time period of time (I don't remember exactly, but it's been months) I've been getting intermittent failures in the C# compiler in CodeQL analysis legs in GitHub Actions workflows.

Seemingly at random, the code will fail to compile with an [error like this](https://github.com/App-vNext/Polly/actions/runs/6508492459/job/17678347218#step:6:329):

```
Running /home/runner/work/Polly/Polly/.dotnet/dotnet build --no-incremental /home/runner/work/Polly/Polly/Polly.sln
MSBuild version 17.7.3+8ec440e68 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Polly.Core -> /home/runner/work/Polly/Polly/src/Polly.Core/bin/Debug/net6.0/Polly.Core.dll
  Polly.Core -> /home/runner/work/Polly/Polly/src/Polly.Core/bin/Debug/net462/Polly.Core.dll
/home/runner/work/Polly/Polly/.dotnet/sdk/7.0.402/Roslyn/Microsoft.CSharp.Core.targets(80,5): error MSB6006: "csc.dll" exited with code 1. [/home/runner/work/Polly/Polly/src/Polly/Polly.csproj::TargetFramework=net6.0]
```

This only affects compilation for CodeQL so I imagine that _something_ there is part of the problem, however I've attempted to get more information out of the build using approaches like `--verbosity diagnostic` and `/p:ErrorLog=./msbuild.log` (e.g. https://github.com/martincostello/alexa-london-travel-site/pull/1910), but to no avail. I don't seem to be able to get any further detail out of the compiler as to why it is failing.

[In this case today](https://github.com/App-vNext/Polly/actions/runs/6506467377), it failed 5 times in a row.

Maybe this is related to #42616 and some custom analysis for CodeQL is the root cause, but unless I'm incorrectly configuring something, the C# compiler should emit some more detailed information about _what_ is wrong to aid resolution of the problem.

**Version Used**:

At least the following versions of the .NET SDK have manifested this issue:

- 7.0.400
- 7.0.401
- 7.0.402

**Steps to Reproduce**:

Run either of these two workflows in GitHub Actions to perform CodeQL code analysis:

- [.github/workflows/codeql-analysis.yml in App-vNext/Polly](https://github.com/App-vNext/Polly/blob/main/.github/workflows/codeql-analysis.yml)
- [.github/workflows/codeql-analysis.yml in martincostello/alexa-london-travel-site](https://github.com/martincostello/alexa-london-travel-site/blob/main/.github/workflows/codeql-analysis.yml)

**Diagnostic Id**:

MSB6006

**Expected Behavior**:

The code compiles.

**Actual Behavior**:

Errors such as the below occur:

```
/home/runner/work/Polly/Polly/.dotnet/sdk/7.0.402/Roslyn/Microsoft.CSharp.Core.targets(80,5): error MSB6006: "csc.dll" exited with code 1. [/home/runner/work/Polly/Polly/src/Polly/Polly.csproj::TargetFramework=net6.0]
```

**Comment by jaredpar** [comment]
Sorry, this bug somehow slipped through my triage board. I just came across it again today. 

Is this still happening? If so can you try to get a binary log of the build (use the -bl argument)? That will give us a full stack and we can start tracking down where this is coming from.

**Comment by martincostello** [comment]
I'm not sure if it's would still happen to be honest.

In Polly this workaround seemed to avoid the problem https://github.com/App-vNext/Polly/commit/160efa53887a85f45e17088b50f58aa9d9c8298f, and this _seems_ to have done a similar job in the other repo: https://github.com/martincostello/alexa-london-travel-site/commit/e372a2219a9c49018d300e76ca4e38cfe1b09ba0

When I get a moment I'll undo the workaround in a branch and see if it comes back. If it does I'll try and grab a binary log.

**Comment by martincostello** [comment]
No errors after 5 re-runs in Polly and 10 in the other repo.

I'll close this for now on the assumption something somewhere fixed this, and merge the removal of my workaround. I'll open a new issue referencing this one if it comes back again.
