### ISSUE TITLE
Add Using should be case insensitive and fix my incorrect casing

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7036]
I typed ```catch (JSonReaderException)``` and no Add Using for ```Newtonsoft.Json``` was offered because I had accidentally capitalized the ```S``` in ```JSon```. Can we search for matches case insensitively, and then fix up their typo if the user picks one where the match wasn't exact?

**Comment by DustinCampbell** [comment]
We should totally do this as we work on improving Add Using to include referencing projects.

**Comment by Pilchie** [comment]
I've actually been thinking that we should incorporate the general spell check fix with Add Using/Import/Reference, so that it's dictionary is all identifiers, not just the ones already in scope.

**Comment by dpoeschl** [comment]
@Pilchie that sounds great!

**Comment by CyrusNajmabadi** [comment]
This is what it looks like with my latest changes:

![image](https://cloud.githubusercontent.com/assets/4564579/11604565/2f9f1d3a-9aa3-11e5-9e40-25a9ad914c54.png)
