### ISSUE TITLE
Interceptors feature doesn't work for VB - doc omission? gap?

### ISSUE THREAD

**Issue by mgravell** [dotnet/roslyn#70387]
The [docs for interceptors](https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md) don't mention anything about interceptors being C# specific, and *it can be argued* that interceptors is more of a build/compiler thing than an actual language thing, so the "VB isn't getting much by way of language updates" can *sort of perhaps maybe* be interpreted a little flexibly.

I'll grant that a cheap way to make me go away here would be to add the token "C#" to that doc. I'm also not *surprised* by this omission. However, I'll continue just in case; maybe the only outcome is to make the docs more explicit, and that might be OK.

Testing with the nightly build, `8.0.100-rtm.23513.4`, the following C# works and is intercepted (obviously substitute the path for your own local):

project file includes:

``` xml
<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);MyInterceptors</InterceptorsPreviewNamespaces>
```

app code:

``` c#
using System.Runtime.CompilerServices;

Console.WriteLine("Hello, World!");

namespace MyInterceptors
{
    file static class MyInterceptorCode
    {
        [InterceptsLocation(@"C:\Code\xintercept\cs\Program.cs", 3, 9)]
        internal static void Intercept(string? message)
            => Console.WriteLine($"Intercepted: {message?.ToUpper()}");
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
#pragma warning disable CS9113 // Parameter is unread.
    file sealed class InterceptsLocationAttribute(string filePath, int line, int character) : Attribute
#pragma warning restore CS9113 // Parameter is unread.
    {
    }
}
```

However, the semantically equivalent VB does not trigger interceptors:

``` vb
Imports System.Runtime.CompilerServices

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
    End Sub
End Module

Namespace Global.MyInterceptors
    Friend Module MyInterceptorCode
        <InterceptsLocation("C:\Code\xintercept\vb\Program.vb", 5, 17)>
        Friend Sub Intercept(message As String)
            Console.WriteLine($"Intercepted: {message?.ToUpper()}")
        End Sub
    End Module

End Namespace

Namespace Global.System.Runtime.CompilerServices
    <AttributeUsage(AttributeTargets.Method, AllowMultiple:=False)>
    Friend NotInheritable Class InterceptsLocationAttribute
        Inherits Attribute
        Public Sub New(filePath As String, line As Integer, character As Integer)

        End Sub
    End Class
End Namespace
```

/cc @RikkiGibson

**Comment by jcouv** [comment]
We can mention that in the doc. Want to propose an edit?

**Comment by RikkiGibson** [comment]
I also wouldn't be opposed to adding an error when using InterceptsLocationAttribute in VB.

**Comment by mgravell** [comment]
> We can mention that in the doc. Want to propose an edit?

done; https://github.com/dotnet/roslyn/pull/70457 - trivial edit, but: at least it is mentioned
