### ISSUE TITLE
[LSP] `textDocument/didChange` handler behavior doesn't follow lsp spec

### ISSUE THREAD

**Issue by jmederosalvarado** [dotnet/roslyn#70392]
When handling `textDocument/didChange` with a list of changes, these are being applied to the document "at once" based on the previous document version, moreover, the implementation currently assumes that these changes are sorted. The current behavior matches [this description](https://github.com/microsoft/vscode/issues/11487#issuecomment-244869542). However [the lsp spec for this](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeTextDocumentParams) clearly states that changes should be applied sequentially and each change `N` acts on the resulting state after applying change `0...N-1`.

The relevant code for the current behavior can be found [here](https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/Core/Portable/Text/SourceText.cs#L641-L733) and [here](https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs#L32-L45).

For example the following code should print `ahbello` where it should print `abhello`:

```csharp
var text = SourceText.From("hello");

var changes = new[]
{
    new TextChange(TextSpan.FromBounds(0, 0), "a"),
    new TextChange(TextSpan.FromBounds(1, 1), "b"),
};

var changed = text.WithChanges(changes);

Console.WriteLine(changed); // should print "abhello", but prints "ahbello"
```

**Comment by CyrusNajmabadi** [comment]
That does seem like a problem.  We should check with @kayle  to make sure that VS LSP client is following the spec here as well before changing anything

**Comment by jmederosalvarado** [comment]
Thanks @CyrusNajmabadi, just to give you a little bit more context, this is causing issues when trying to use an lsp client other than vscode's, for example neovim.

**Comment by jmederosalvarado** [comment]
> Note in particular that if you make several edits to a document in a single edit, the didChange notification may represent those edits differently as long as the logical resulting text is the same

@kayle what exactly do you mean here? The [LSP spec states](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeTextDocumentParams) that if a `didChange` message contains multiple edits, these should be applied sequentially by the server, and each edit should be applied on the result of the previous ones.

Roslyn computes the text positions where these edits should be applied using the same text state for every edit in the `didChange` message. See the code [here](https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidChangeHandler.cs#L38).

For example, consider a `didChange` message contains two edits `c1` that acts on range [0:0,0:0] and `c2` that acts on range [0:1,0:1]. Roslyn currently computes the positions in the text model where `c1` and `c2` should be applied upon receiving the notification, which means that `c2` will be applied on 0:1 (column 1) of the original text state and not on column 1 of the text resulting from applying `c1`

> Roslyn certainly should not reorder the changes in a `didChange` notification since that could change the resulting text.

[Roslyn orders](https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/Core/Portable/Text/SourceText.cs#L672-L676) the changes in a `didChange` notification. Moreover, it doesn't allow for overlapping changes, because it assumes that each change doesn't act upon the previous one, but rather all changes in a `didChange` message act upon the same original text.

For example, consider a `didChange` message contains two edits `c1` that insets on range [0:0,0:0] and `c2` that also inserts on range [0:0,0:0]. [The current implementation throws](https://github.com/dotnet/roslyn/blob/fe6cc3e7227caafafd76ffd1f3f8981926edf3b6/src/Compilers/Core/Portable/Text/SourceText.cs#L679) an exception because it considers these edits as overlapping (they are both acting on the same segment of the original text). However the expected behavior is that `c2` inserts at column 0 of whatever text results from `c1` inserting at column 0.

**Comment by CyrusNajmabadi** [comment]
@jmederosalvarado he means that the lsp changes you hear about may not correspond precisely to the ITextChanges in the actual snapshot. 

The vs text model is much more precise and fine-grained.  To match the lsp spec it may have to do things like consolidate discontinuous changes into single changes. 

That's totally fine here, and we'll update our impl to match the spec.
