### ISSUE TITLE
Static members missing from completion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70403]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/In-VS2022-smart-hints-are-missing/10483557)._

---
[severity:It bothers me. A fix would be nice] [regression]
C#
```
 void temp()
 { 
     Cursor.Position = new Point (0, 0);
 }
```

When I type Cursor.P it will intelligently prompt Cursor.Position; All this is normal

```
 void temp()
 { 
    Cursor.p
    Random r = new Random();         
 }
```
But when I first enter another line of code, and then type "Cursor.p" above this line, there is no indication of "Position", and the other properties still exist. Although I type it manually, it still works, but I want to know why it does not prompt?

---
#### Feedback Bot on 10/6/2023, 08:51 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/7/2023, 03:08 AM: 

(private comment, text removed)
#### Person (2023-10-04 20:06:35Z) on 10/9/2023, 10:54 AM: 

(private comment, text removed)
#### Person (2023-10-04 20:06:35Z) on 10/9/2023, 11:06 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/7/2023, 03:09 AM: 

(private comment, text removed)
#### Person (2023-10-04 20:06:35Z) on 10/9/2023, 10:45 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/16/2023, 03:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Based on videos provided by the customer, the following will reproduce the bug:

```
class BaseClass
{
  public Cursor Cursor { get; set; }
}

class Derived : BaseClass
{
  void Method()
  {
    Cursor.P  // <-- 'Position' should be offered by completion here, but is missing
    Point p = new Point(0, 0);
  }
}
```

**Comment by CyrusNajmabadi** [comment]
Yup.  I repro this.  Investigating.

**Comment by CyrusNajmabadi** [comment]
Ok.  Have repro.  Investigating now.
