### ISSUE TITLE
Guidance for using primary constructors when "_underscoreCamelCase" syntax is used for private fields?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Guidance-for-using-primary-constructors-/10490634)._

---
[severity:It's more difficult to complete my work]
In every place I've worked at, the desired syntax for private fields is "_underscoreWithCamelCase".  It's also the suggested convention in the [C# coding style docs](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names).  For example, the [dependency injection example](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors#dependency-injection) would be written without primary constructor as follows:

```cs
public class ExampleController : ControllerBase
{
    private readonly IService _service;

public ExampleController(IService service)
    {
        _service = service;
    }

[HttpGet]
    public ActionResult<Distance> Get()
    {
        return _service. GetDistance();
    }
}
```
How is this supposed to be written with primary constructors?  Should it be like this?

```cs
public class ExampleController(IService _service) : ControllerBase
```

This looks kind of bizarre.  Or should we do this?

```cs
public class ExampleController(IService service) : ControllerBase
{
    private readonly IService _service = service;
```

In this case, we still have a private field `service` that looks like a local variable and is usable anywhere in the type.

It seems like primary constructors were designed only for people who prefer `camelCase` for local fields and goes against what's defined in the C# coding style conventions.

---
#### Feedback Bot on 10/12/2023, 08:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
> Or should we do this?
>
> ```cs
> public class ExampleController(IService service) : ControllerBase
> {
>     private readonly IService _service = service;
> ```

This is the approach I would use.

> In this case, we still have a private field `service` that looks like a local variable and is usable anywhere in the type.

It's my understanding that the compiler will warn if you have `service` assigned to a field and also try to use it elsewhere. If this is the case, it would make sense for us to hide `service` from completion lists in cases where using it would produce a warning.

**Comment by CyrusNajmabadi** [comment]
The guidance is:

The parameters should be named using the naming style for parameters (`pascalCased`) .

They are not fields and should be named as a fields.

If you do not like referencing the parameters in members of your type, and which to instead reference fields, then it should be assigned to a field (which then follows your field naming-style).
