### ISSUE TITLE
Add Compilation parameter to EmitBaseline.CreateInitialBaseline (breaking change)

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#70413]
## Background and Motivation

To support EnC operations that delete synthesized members we need to pass initial compilation to `EmitBaseline.CreateInitialBaseline`.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Emit;

public class EmitBaseline
{
+       [Obsolete("This overload is no longer supported")]
+       [EditorBrowsable(EditorBrowsableState.Never)]
        public static EmitBaseline CreateInitialBaseline(ModuleMetadata module, Func<MethodDefinitionHandle, EditAndContinueMethodDebugInformation> debugInformationProvider)
+            => throw new NotSupportedException();

+       [Obsolete("This overload is no longer supported")]
+       [EditorBrowsable(EditorBrowsableState.Never)]
        public static EmitBaseline CreateInitialBaseline(
            ModuleMetadata module,
            Func<MethodDefinitionHandle, EditAndContinueMethodDebugInformation> debugInformationProvider,
            Func<MethodDefinitionHandle, StandaloneSignatureHandle> localSignatureProvider,
            bool hasPortableDebugInformation)
+            => throw new NotSupportedException();

+       public static EmitBaseline CreateInitialBaseline(
+           Compilation compilation,
+           ModuleMetadata module,
+           Func<MethodDefinitionHandle, EditAndContinueMethodDebugInformation> debugInformationProvider,
+           Func<MethodDefinitionHandle, StandaloneSignatureHandle> localSignatureProvider,
+           bool hasPortableDebugInformation)
}
```

## Usage Examples

Used by EnC to emit deltas.
See PR https://github.com/dotnet/roslyn/pull/70184

## Alternative Designs

Allow not passing in the compilation and only throw when the compilation is needed. This might still break some existing code (in theory, as this API is not very likely being used outside of Roslyn) since emitting deltas in certain scenarios now requires the compilation whereas it wasn't required before. Seems better to just throw right away and not complicate the implementation.

## Risks

This is a breaking change. The previous APIs will not work anymore.

**Comment by 333fred** [comment]
### API Review

* Alternative could be to have the old method work, just throw when we need it?
    * Probably not worth the effort
* Runtime at least is going to move to the new API
    * Should be able to, but would need to maintain more infrastructure around old data structures
* Why Obsolete with a warning if it's going to throw?
    * Obsolete with an error, mention the new overload

Approved. Make the `Obsolete` an error instead of a warning.

**Comment by tmat** [comment]
Done.
