### ISSUE TITLE
Diagnostic tags don't follow LSP spec

### ISSUE THREAD

**Issue by jmederosalvarado** [dotnet/roslyn#70426]
**Version Used**: master

**Steps to Reproduce**:

1. send request `textDocument/diagnostics` for a document with diagnostics

**Expected Behavior**:

You will get a response including diagnostics for the text document, however it will contain [invalid diagnostic tags](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag) like `[-6,-4,-7,-2]`

**Actual Behavior**:

Diagnostics tags are either 1 or 2, which are the only valid values [according to the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag)

**Comment by CyrusNajmabadi** [comment]
Looked at the spec and it does say:

> To support the evolution of enumerations the using side of an enumeration shouldn’t fail on an enumeration value it doesn’t know.
