### ISSUE TITLE
[Test Failure] No identified problem in prtest/lin/dbg/unit32 on PR #7024

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7042]
PR: [#7024](https://github.com/dotnet/roslyn/pull/7024) *Update documentation for Update 1* by @jasonmalinowski
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1549/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

All these errors were on fbld-3, which is now offline.

@TyOverby I created http://dotnet-ci.cloudapp.net/failure-cause-management/3423dc9a-6c95-4e22-959c-0a7a6f0717a7/ with a vague explanation for this. If we can fix fbld-3, let's add a better description to that failure cause.

**Comment by davkean** [comment]
This is due to lack of disk space on the machines.

**Comment by TyOverby** [comment]
I investigated the disk-space issues on fbld-3 back when this issue was created and didn't get anywhere.  I think your cause is as good as we are going to get.
