### ISSUE TITLE
Constant folding doesn't work correctly sometimes

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#70437]
**Version Used**:
`main (17 Oct 2023)`

**Steps to Reproduce**:
```cs
public class C
{
    static int M(int a) => a - 1 - 1;
}
```

**Expected Behavior**:
Codegen for `M` is equivalent to:
```cs
public class C
{
    static int M(int a) => a - 2;
}
```

**Actual Behavior**:
Constants are not folded correctly ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKEIwGYACbMgYUIG9CzGKcA2M2BMgWQAoOyIASjIBeAHwCyAWjI5psgNyEAvkA)):
```il
IL_0000: ldarg.0
IL_0001: ldc.i4.1
IL_0002: sub
IL_0003: ldc.i4.1
IL_0004: sub
IL_0005: ret
```

This is not a big deal in this minimalistic forma that I presented. People usually don't write things like `a - 1 - 1` themselves. However, some language features depend on this behavior leading to non-optimal output in cases, when the user cannot even see it, e.g.:
```cs
using System;

public class C
{
    static Span<int> N(Span<int> span) => span[1..^1];
}
```
Here generated IL contains the same `- 1 - 1` sequence, which isn't optimized ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKEIwGYACbMgYUIG9CzGKcA2MgZQAcIYAeWBAD4yAOQAUXHvxhCyAZ24wAlGQC8whTwDaOAHS6AejgC6AbkIBfIA==)):
```il
IL_0000: ldarga.s span
IL_0002: stloc.0
IL_0003: ldloc.0
IL_0004: ldc.i4.1
IL_0005: ldloc.0
IL_0006: call instance int32 valuetype [System.Runtime]System.Span`1<int32>::get_Length()
IL_000b: ldc.i4.1
IL_000c: sub
IL_000d: ldc.i4.1
IL_000e: sub
IL_000f: call instance valuetype [System.Runtime]System.Span`1<!0> valuetype [System.Runtime]System.Span`1<int32>::Slice(int32, int32)
IL_0014: ret
```

**Comment by CyrusNajmabadi** [comment]
This is not a constant as far as the language is concerned. Compiler could attempt something here, but I think it would be better placed in the jit so that all languages get this.

**Comment by DoctorKrolic** [comment]
Jit already does that: https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQMwAJMBMuAwgLABQA3hbrfgIwBsusCuAsvQBSu4QCUuALwA+PrgC0uepOkBuGnUxMWMNuwI81fQaPFSCC8gF8gA=

But this still can be implemented in the compiler just to slightly reduce resulting IL size

**Comment by tannergooding** [comment]
It’s worth noting there are many places where this isn’t a valid optimization, including for binary floating-point types, checked contexts, etc

The pattern is, as indicated, uncommon and while there are potentially some minor IL savings that could happen and which might save some runtime cost, it likely won’t have any measurable real world impact to cover this.

**Comment by CyrusNajmabadi** [comment]
> But this still can be implemented in the compiler just to slightly reduce resulting IL size

I'd want to see how many saved bytes that would be. Could you analyze Roslyn, for example, and show what the savings would be?

I'd also be worried about subtle bugs being caused by this. For example if you folded constants such that an overflow or underflow now didn't happen.

My guess is this would save literally a few bytes on multi mb assemblies. I don't think the savings would be worth it.
