### ISSUE TITLE
BC40003 code fix should offer both 'Overloads' and 'Shadows'

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70434]
**Version Used**: Version 17.9.0 Preview 1.0 [34216.205.main]

**Steps to Reproduce**:

```vb
Class BaseClass

    Protected Sub Method()

    End Sub

End Class

Class DerivedClass
    Inherits BaseClass

    Protected Sub Method()

    End Sub

End Class
```

Bring up the light bulb on `DerivedClass.Method()`.

**Diagnostic Id**:

BC40003

**Expected Behavior**:

Both "Add 'Overloads'" and "Add 'Shadows'" should be offered.

**Actual Behavior**:

Only "Add 'Overloads'" is offered.
![image](https://github.com/dotnet/roslyn/assets/1408396/0ec4c501-6ce6-4a04-9f99-5e958301e127)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in this area.
