### ISSUE TITLE
`u8` should be colorized just like a string

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#70439]
This is the style numeric literals use as well.

![image](https://github.com/dotnet/roslyn/assets/3105979/8d9707d3-1999-4997-aea0-2c6603367015)

In my opinion, this is a little distracting.

**Comment by Sergio0694** [comment]
It actually used to be that way, but we made a proposal to change it to keyword: https://github.com/dotnet/roslyn/issues/63139. The reasoning is that UTF8 literals are usually used in advanced code and have very specific meaning and semantics associated to them, and it's quite confusing to see them especially when they're next to normal strings. Having the `u8` part using the keyword color really helps making the code easier to read and understand.

**Comment by CyrusNajmabadi** [comment]
Honestly, I'd prefer if we classified all the suffixes.  Would make it clearer when being used.
