### ISSUE TITLE
IDE0047 Needs better clarity for dotnet templates

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/roslyn#70459]
**Version Used**: 
latest-recommended

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Source\sandbox\TemplateTest\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Steps to Reproduce**:

1. Create a DotNet Template for net6.0 with a Parameter. Set the code to latest-recommended
2. Add a preprocessor condition to show or hide something based on the parameter in the template
3. See that an error is thrown

**Diagnostic Id**:

IDE0047

**Expected Behavior**:
I expect that IDE0047 doesn't impact Preprocessor directives.

**Actual Behavior**:
IDE0047 impacts Preprocessor directives.

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  Can you supply the exact code you had written @EdLichtman ?  Thanks!

**Comment by EdLichtman** [comment]
https://github.com/EdLichtman/UniformPackagesDemo/tree/DemoIDE0047Error

Open up 

Final_Demo/Templates/templates/Demo.PackageLibrary/Demo.PackageLibrary.sln

and try to build

**Comment by Youssef1313** [comment]
Is https://github.com/EdLichtman/UniformPackagesDemo/tree/a51a9f789ef1b1d5b86be6608ca240e84d3a4942/Final_Demo/Templates/templates/Demo.PackageLibrary/src meant to be "real source code" or only template content?

My hypothesis is that it's meant only as a template content, but it seems you added https://github.com/EdLichtman/UniformPackagesDemo/blob/a51a9f789ef1b1d5b86be6608ca240e84d3a4942/Final_Demo/Templates/templates/Demo.PackageLibrary/src/Demo.PackageLibrary.csproj to your main solution and then this is being compiled.

**Comment by EdLichtman** [comment]
I'm meant to be able to program it as if it were real source code, but for it to be the template content. How am I meant to work on my template if I don't know whether it will compile?

**Comment by CyrusNajmabadi** [comment]
Closing this out as by design. If you add files like this to your project, then we will analyze them just like every other c# file.

If you want it to be a template that isn't analyzed, then you can either not add it as a source file, or you can mark it to be excluded in your editorconfig file.

**Comment by EdLichtman** [comment]
@CyrusNajmabadi except the editorconfig is also not working in this case. Please take a look at the code again -- I've just added an editorconfig and set the severity to none, yet both SA1119 and IDE0047 are erroring

**Comment by sharwell** [comment]
@EdLichtman your .editorconfig has invalid syntax here:
https://github.com/EdLichtman/UniformPackagesDemo/commit/6f74782e662e307a3aadf2c04a1300c971467c9f

The items need to be declared under a file path heading, e.g.:

```
[*.cs]
dotnet_diagnostic.IDE0047.severity = none
dotnet_diagnostic.SA1119.severity = none
```
