### ISSUE TITLE
EnableGenerateDocumentationFile analyzer is a breaking change

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#70460]
The diagnostic added in #58835 is an unconditional diagnostic that fires on existing code. That means it represents a breaking change to customers when upgrading to a new version of the .NET SDK toolset. This was discovered by 1P customers trying to upgrade and represents a blocker for them. This diagnostic needs to be conditioned on a warning version at the least.

**Comment by sharwell** [comment]
It seems straightforward to condition this on warning version.

Note that this is already conditioned on _two_ separate non-default configurations being applied by the customer (explicitly enabling code style diagnostics on build, and explicitly raising the severity of IDE0005 to warning or greater).

**Comment by rainersigwald** [comment]
> explicitly raising the severity of IDE0005 to warning or greater

In the internal codebase in question it appears to be configured (via `.ruleset`) to `Info`.

**Comment by sharwell** [comment]
EnableGenerateDocumentationFile only reports a diagnostic when IDE0005 is configured to warning or greater.

https://github.com/dotnet/roslyn/blob/b801bf24cee9d3dc11394bcd26b7e4d3b4005084/src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs#L121-L125

**Comment by arkalyanms** [comment]
cc: @mavasani
