### ISSUE TITLE
Roslyn crashes when accessing exception variable

### ISSUE THREAD

**Issue by cbghissues** [dotnet/roslyn#70483]
**Version Used**: 7.0.309

**Steps to Reproduce**:

```csharp
using System;
using System.Threading.Tasks;
public static class Program {
    public static ValueTask Test() => ValueTask.CompletedTask;
    public static async Task Main() {
        try {
            await Test();
        } catch (Exception ex) when (true) {
            await Test();
        } catch (Exception ex) when (true) {
            try {
                await Test();
            } catch {
                Console.Write(ex);
            }
        }
    }
}
```

[Minimal Repro](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5mwDM6A3suhZsVgGzoBqAhgDYCuAplHQCrsDOAFwAUASnQBeAHwMWHLgDoAwgHsAtgAdm7Ae2Bd8SSlUxw6UAByY6AWUYBLAHajS5I5QEAnAJ4vDb/1AAnOi8gqIG/hQAvugAxowCsQAW6EIAogAesezqAnbKDujsGWIA7knshUKeHGJkfpGUQSH8wiIRkTHxiSnpWTl5BUUl6OWVqTXsda6NFJ4+9bORzaFtHUtdCcm+S/4qDnzKWvIA6h52OkLF7TOzUbdG9w3oT1FAA==)

**Expected Behavior**: Program compiles.

**Actual Behavior**: Compiler crashes.

**Comment by cston** [comment]
Similar to https://github.com/dotnet/roslyn/issues/67091?

**Comment by jaredpar** [comment]
Similar but not a dupe. This is still reproducing in `main` 

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQeADAAR5ECsA3OYQMzUDe51Pt7dANmoA1CCgCuAUzxCAKpIDOCABQBKagF4AfCLFSZAOgDCAezAAHFJIST0M5mV59aRIXgActIQFloMNZzcTrwIAE4AnoGOwTF4AJzU8kpqDjE8AL7UAMYQCFkAFtTKAKIAHlmS5ghQJjDUkqXqAO75knXKYVLqXNFpvPGJiiqqqWmZOXmFJeWV1bX1jdQtbUWdkt1BfTxhkT1baQNJw6P747kFUfsxpjAKJlYGAOqhUDbKDSObW+lfTj+91H+6SAA)
