### ISSUE TITLE
"paramref" XML attribute doesn't work with primary constructor params (CS1734)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#70509]
**Version Used**: VS 17.8 P4, Roslyn 4.8.0-3.23510.8 (d49b29ec)

**Steps to Reproduce**:

1. Paste the following code:

```csharp
public class Foo(int x)
{
    /// <summary>
    /// Writes <paramref name="x"/>.
    /// </summary>
    public void Bar()
    {
        Console.WriteLine(x);
    }
}
```

([sharplab link](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTCDMACZPAMQHsSAKWAFzwA8BKTAb0zzbwHou8AeAZwCuYSACcAngD5W7LhzwB1EVCoBTPrwAOEERDAiVAMzwxdKgLwAiWhY4SAdNLazeHQcO2THBfAgAseACFtckYMdjwWMPD2BBQATnIGAG4vAF9MVKA===))

**Diagnostic Id**:

CS1734 ("XML comment on "..." has a paramref tag for "...", but there is no parameter by that name").

**Expected Behavior**:

The XML `paramref` should work as usual. @CyrusNajmabadi and @333fred have stressed multiple times how primary constructor parameters are literally parameters, and not fields. If that is the case, then I'd expect `paramref` to also work as expected here 😅

**Actual Behavior**:

![image](https://github.com/dotnet/roslyn/assets/10199417/b3d734c0-85c5-42a3-a2d5-51c8998271bc)

**Comment by jcouv** [comment]
@AlekseyTs Please confirm the expected behavior.

**Comment by AlekseyTs** [comment]
The behavior is expected. A "paramref" refers to the documented declaration.
