### ISSUE TITLE
Productivity: Support "Add reference"/"Add NuGet package" in addition to Add Using

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7051]
We should look at the code that the ASP.NET team wrote for this and generalize it.

- [ ] Support for csproj as well as xproj
- [ ] Support for vbproj
- [ ] Support for P2P refs
- [ ] Support for packages.config as well as project.json?
- [ ] Support for AssemblyFoldersEx based references?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/9296
