### ISSUE TITLE
Productivity: Provide option for VB completion to not insert newline on enter

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7052]

**Comment by diryboy** [comment]
:+1: Yes yes, happens too often for me, just couldn't stop because of muscle memory

**Comment by CyrusNajmabadi** [comment]
VB has this behavior:

![image](https://user-images.githubusercontent.com/4564579/75635620-70137200-5bcc-11ea-8b93-857bf8a609a3.png)
