### ISSUE TITLE
required member that hides base required member is not recognized

### ISSUE THREAD

**Issue by Rubidium37** [dotnet/roslyn#70520]
### Description

I have two classes: one base class and one derived class.
The base class declares a required property.
The derived class hides the base property with a new required property that always sets the value of the base one.
When compiling I get error **CS9031: Required member 'BaseClass.Value' cannot be hidden by 'DerivedClass.Value'.**	

Given that the derived property is garanteed to be set and it sets the base one, I dont' expect such error.
I expect the same behavior of `init` properties, where a property in a derived class can set a property in a base class if both have such modifier.

### Reproduction Steps

The following generates the error:
```C#
class BaseClass
{
	required public object Value { get; set; }
}
class DerivedClass : BaseClass
{
	new required public string Value { get => (string)base.Value; set => base.Value = value; }
}
```

### Expected behavior

I expect successfull compilation, without errors

### Actual behavior

I get 
CS9031: Required member 'BaseClass.Value' cannot be hidden by 'DerivedClass.Value'

### Known Workarounds

The only workaround is to declare all members without the `required` modifier and include them as parameters of all constructors.

**Comment by jcouv** [comment]
@333fred I believe the current behavior is by-design. The error for hiding a required member doesn't depend on any analysis of the code (whether it always sets the hidden required member or not). Can you confirm and close?

**Comment by 333fred** [comment]
This behavior is by design, as @jcouv said. We do not attempt to figure out whether the hidden member is always set or not, as external users of the type cannot know that: all they would know is that there are two required members, and one of them cannot be referenced in syntax.
