### ISSUE TITLE
Roslyn tries to override inherited methods from a record in a class

### ISSUE THREAD

**Issue by Yoticc** [dotnet/roslyn#70530]
**Version Used**:
VS 17.7.5 
.Net 7.0 (SDK 309)

**Steps to Reproduce**:

1. Declare abstract record
2. Add in record an abstract method "AbstractMethod"
3. Create class, which use record syntax and inherit it from declared record
4. Hover over class name and click "Show potential fixes"
5. Click on "Implement abstract class"
6. It will create 2 abstract methods" "AbstractMethod" and "\<Clone>$"
![image](https://github.com/dotnet/roslyn/assets/55879406/4f3f6a5f-2ba9-4199-ae0e-dcfd594940ef)
![image](https://github.com/dotnet/roslyn/assets/55879406/0ca1a51e-86d6-4374-b529-894fc7053eaf)

This is the bug. There should not be \<Clone>$, ideally it should indicate that the class cannot be inherited from the record

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi This is a very easy IDE side fix, but don't you think compiler should not report such error here in the first place?

**Comment by CyrusNajmabadi** [comment]
i have no issue with better compiler diagnostics.

**Comment by Yoticc** [comment]
> i have no issue with better compiler diagnostics.
What are "better compiler diagnostics"? Is this the latest, non-release version of Roslyn? How I get it?
