### ISSUE TITLE
CS9210 firing on new box; no docs

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/roslyn#70552]
**Version Used**: 

Broken Box: Compiler version: '4.9.0-1.23524.3 (8da753b6)'. Language version: latest (12.0).
Working Box: Compiler version: '4.8.0-3.23510.8 (d49b29ec)'. Language version: latest (12.0).

The broken box is a fresh 2022 Preview install.
The working box is currently on Version 17.8.0 Preview 4.0 with a pending update to Preview 5.

**Steps to Reproduce**:

Not really sure - I have the same repo cloned on two machines and only get the exception on one.

Syntax in use is simply:

```csharp
    private ImmutableArray<IStrategy> _plannedStrategies = [];
```

**Diagnostic Id**:

```
error CS9210: This version of 'ImmutableArray<T>' cannot be used with collection expressions.
```

**Expected Behavior**:

Since I am cloning the exact same code between 2 machines, I expect the same behavior (compiling successfully). OR I should be able to go to the help page for this compilation error and figure out what I need to do to fix things.

**Actual Behavior**:

Above error message occurs and there is no doc page that I can use to self-solve.

**Comment by CyrusNajmabadi** [comment]
It's telling you that we don't know how to properly create an immutable array, so you're actually going to end up in a broken state.  Specifically, because we can't find the right entrypoint to create it, it's going to fallback to the legacy brehavior of doing `new ImmutableArray<IStrategy>()`, which is actually *firmly* broken, since you get a `default` instance, not an `empty` instance.

Doc issues can go to dotnet/docs.  We don't have pages on this since the compiler warning was literally just added, and you're using bleeding edge bits.

**Comment by brandonh-msft** [comment]
> It's telling you that we don't know how to properly create an immutable array, so you're actually going to end up in a broken state. Specifically, because we can't find the right entrypoint to create it, it's going to fallback to the legacy brehavior of doing `new ImmutableArray<IStrategy>()`, which is actually _firmly_ broken, since you get a `default` instance, not an `empty` instance.
> 
> Doc issues can go to dotnet/docs. We don't have pages on this since the compiler warning was literally just added, and you're using bleeding edge bits.

I think you're misunderstanding - this code works just fine in an _earlier_ version of the compiler but _fails_ in a more recent version.

**Comment by CyrusNajmabadi** [comment]
Correct.  That's exactly waht the warning is telling you.  We were compiling into something incorrect (a default immutable array, not an empty one).  Now we're saying: this is a problem and almost certainly not what you want, so def take a look and either dont' use collection-expressions here, or do something else to indicate you want a default array.  Like: `private ImmutableArray<IStrategy> _plannedStrategies = default;`

This was added here intentionally, to help catch and prevent the problems this was causing: https://github.com/dotnet/roslyn/pull/70411

**Comment by brandonh-msft** [comment]
gotchya, thanks for that explanation! Will work around it w/ the new() or .Empty initializer 👍🏻

**Comment by BillWagner** [comment]
Thanks both. I'll transfer to `dotnet/docs` to preserve the notes when I add pages for the latest errors / warnings (probably next month around GA)
