### ISSUE TITLE
Boxing ValueTypes heavily when calling InheritanceMarginItem.Equals => InheritanceTargetItem.Equals

### ISSUE THREAD

**Issue by marshall-lerner** [dotnet/roslyn#70559]
**Version Used**: main

**Steps to Reproduce**:

When looking at the [InheritanceTargetItem](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/InheritanceMargin/InheritanceTargetItem.cs) and [DocumentIdSpan](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/DocumentIdSpan.cs#L18) structs, there is no strongly typed Equals method, which causes allocations to happen whenever the .Equals gets called on it.
2. .Equals gets called on InheritanceTargetItem in the [InheritanceMarginItem.Equals](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/InheritanceMargin/InheritanceMarginItem.cs#L63) override
3. .Equals gets called on DocumentIdSpan in the [DetachedDefinitionItem.Equals](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/FindUsages/DefinitionItem.DetachedDefinitionItem.cs#L56) override, which gets called due to InheritanceTargetItem not overriding the .equals method so we compare the [DefinitionItem](https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/InheritanceMargin/InheritanceTargetItem.cs#L28)

**Expected Behavior**:
Instead, choose a pattern that does not require calling Object.Equals, or implement IEquatable<T> on the value type making sure the call site calls through the strongly typed Equals to avoid boxing both left and right-hand sides of the .Equals method.

**Actual Behavior**:
Boxing, allocating, and GC pressure when comparing the value types

**Comment by CyrusNajmabadi** [comment]
@marshall-lerner how much does this show up in your traces?  As inheritance margin only adds items for what's in view, and generally there are very few symbols in view, I'd be surprised to see heavy allocations here.

**Comment by marshall-lerner** [comment]
I was seeing the median being around 200Kb, the 75th percentile around 400Kb, the 99th percentile 14Mb, but the max was ~6Gb

**Comment by CyrusNajmabadi** [comment]
Discussed offline with @marshall-lerner . Taking a look.  Thanks!
