### ISSUE TITLE
Primary constructors: Add node for primary parameter variables

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/roslyn#70564]
**Issue**
Currently, values that are defined in the primary parameter are expressed in the locals window as a local variable:
![image](https://github.com/dotnet/roslyn/assets/7958854/b5234796-9076-46ac-be62-79c6505b6e64)

However, there are a couple of problems with this approach:
1.	User cannot see the value of the primary parameters until they step into a member of the type.
2.	Debugger “hides” that a field (`<strValue>.P`) was generated for that parameter.

**Proposed idea**
The IDE could show these values for the primary constructor parameter under a special node, so users can still expand that without needing to step into a method of the type. 

The idea is to clarify that these were generated as a field, even though they cannot be accessed through `this`.

![image](https://github.com/dotnet/roslyn/assets/7958854/73661cbb-267e-4715-bd92-80930a03b8ee)

**Comment by gregg-miskelly** [comment]
Note: This feature was mostly fixed at same point -- expanding an instance of a class with primary parameters will now show the value of the parameters. The only remaining problem is that there is no syntax to get to the primary parameters from outside of the class. So, if you want to take that primary parameter and invoke a function on it, you can't unless you are in member function.

**Comment by CyrusNajmabadi** [comment]
>  So, if you want to take that primary parameter and invoke a function on it, you can't unless you are in member function.

This is by design.  That's the semantics of how C# works.  These are parameters.  And just like parameters to normal functions, you cannot use them unless you're inside that function.
