### ISSUE TITLE
Replace csproj.dll and msvbprj.dll with CPS based implementations

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7057]
- [ ] [As an existing C#/VB developer, I have parity with previous versions of Visual Studio when I open my project](https://github.com/dotnet/roslyn/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+System-Parity%22+label%3A%22Area-Project+System%22)

- [ ] [New features](https://github.com/dotnet/roslyn/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+System-New+Feature%22+label%3A%22Area-Project+System%22)

**Comment by AdamSpeight2008** [comment]
Dumb question what does `CPS` stand for in the title?

**Comment by davkean** [comment]
"Common Project System"

**Comment by AdamSpeight2008** [comment]
@davkean Thank you. I thunk that `Continuation Passing Style` didn't quite fit.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#127
