### ISSUE TITLE
Roslyn unable to evaluate local variables on Windows Forms on file with Unicode characters

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/roslyn#70580]
**Version Used**: Visual Studio 17.8 Preview 5 with .NET Framework 4.7.2

**Steps to Reproduce**:

1. Clone the project at https://github.com/yangbocheng/for-vs2022-winform-bug. Add a breakpoint on `testAuto设置123.cs`, line 13.
2. Start debugging
3. Stop at breakpoint

**Expected**
All local variables are available.

**Actual**
The parameters do not show up in the local window:

![image](https://github.com/dotnet/roslyn/assets/7958854/d97d2ca7-9aaf-4488-826c-78fd050fc9ff)

**Remarks**
This only reproduces if the **file** name contains any unicode character. If you switch the file name to english letters only, the issue does not reproduce.

**Further details**
Issue was created from https://developercommunity.visualstudio.com/t/cDebug-tool-wont-show-parameters-in-pa/10499481.

**Comment by att1008** [comment]
I also had the same problem, and the previous version also appeared. It was solved by reinstalling the software before, but now it appears again.

**Comment by tmat** [comment]
The issue only seem to occur when the project property `DebugType` is set to `full` or `pdbonly` (i.e. Windows PDBs are used).
A workaround is to set `DebugType` to `portable`.

**Comment by eveloki** [comment]
But .NET Framework 4.8 Base Set is DebugType full
Look https://github.com/eveloki/ConsoleApp1_ChineseTest/blob/master/ConsoleApp1%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95/ConsoleApp1%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95.csproj line 19

**Comment by leleonwu** [comment]
visual studio 17.8、17.8.1 and 17.9 preview1 having the same problem

**Comment by isadorasophia** [comment]
Thanks for letting us know! 

We investigated the issue with Roslyn and turns out that the fix will be in the VS side. You can also use https://developercommunity.visualstudio.com/t/VS2022178C-The-identifier-is-not-defin/10520176 to track once it gets into 17.8 and 17.9. Adding `<DebugType>portable</DebugType>` is just a workaround until the fix gets in the product.

**Comment by qq874663394** [comment]
visual studio 17.8.2 having the same problem
Upgraded from 2017 to 2022 downloaded from the official website, and then migrated to 17.8.2.
.NET Framework version is 4.8
I modified the DebugType and it worked fine

**Comment by oo0595** [comment]
Finally found you,

DebugType=portable Test result: Issue Disappearance

This issue was investigated for two days and reinstalled several times,
I hope to update and resolve it as soon as possible.

**Comment by isadorasophia** [comment]
Thanks for the patience! The fix is now in the latest 17.8 release (17.8.3): https://visualstudio.microsoft.com/downloads/. Please let me know if that doesn't work for you.
