### ISSUE TITLE
Code Style: Roslyn Workspace APIs need to support per-file options

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7058]

**Comment by sharwell** [comment]
In case anyone is wondering why - this would *allow* things like automatic detection of spaces vs. tabs and/or indentation size when editing a file. In general, default behavior which tries to comply with the existing style of a file and only overwritten by project-level settings at the request of the user is a friendlier experience, especially for developers who tend to move around and work on projects created by many different people.

**Comment by paul1956** [comment]
@sharwell I am confused by what behaviour you want. What I think addresses working on a project with multiple people or in my case with different editors, is for a setting that fixed the things you describe automatically according to a file or project setting. I hate when Visual Studio constantly asked me if I want to convert tabs only to have something else convert it back.

**Comment by sharwell** [comment]
> I am confused by what behaviour you want.

I tried to emphasize *allow* in my comment. I was merely giving an example of something new you could do if options could be per-file instead of per-project.

**Comment by Pilchie** [comment]
Automatic detection is something we would like to do, but we would probably do it as a way to set the settings initially.

This will be necessary if we want to support .editorconfig, since you could have a pattern for specific file names.

**Comment by mkrueger** [comment]
Having a more fine grained optionset handling would be awesome. We in XS have options on project level so it would be really helpful if that would be changed.

**Comment by Pilchie** [comment]
This is done, right @jasonmalinowski ?
