### ISSUE TITLE
`CodeGenerationAttributeData` violates the expected nullability contract of its base type `AttributeData`

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#70592]
The attribute on `AttributeData.HasErrors` was improperly implemented, so this issue slipped by.
The intent is to have the following signature:
```

        [MemberNotNullWhen(false, nameof(AttributeClass), nameof(AttributeConstructor))]
        internal virtual bool HasErrors { get; }
```

But `CodeGenerationAttributeData` currently has a `null` `AttributeConstructor` while returning `HasHerrors` as `false`.

This issue is referenced in code, where portion of the attribute is currently commented out.

**Comment by CyrusNajmabadi** [comment]
There's nothing the IDE can do here.  This is an internal method that is not part of the public surface area of this type.
