### ISSUE TITLE
Code Style: Coordinate with platform team about .editorconfig 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7061]
Need to ensure the right things happen for editor level options like tabs vs. spaces, tab size, etc, and that it doesn't interfere with roaming settings for the defaults.

**Comment by sharwell** [comment]
[I have to comment so it notifies me of updates.]

**Comment by BillWagner** [comment]
Can we come up with some scheme whereby project level settings can override users' settings. This is important for Open Source projects and avoiding the "sea of red" diffs.

I'd like to be able to have contributors know that if they applied the project level settings, their diffs would be clean when they submit a PR. They would not need to read a document, or try to determine the settings used by this project from looking at the code.

**Comment by scottdorman** [comment]
Yes, this definitely needs a multi-level approach to settings. Starting at the project level and then working backwards (up to solution and then global) seems like it would work well. That would give us the ability to specify defaults at the solution level and then adjust them as needed for specific projects. As long as the solution level settings were complete, it would override whatever was set globally. If the solution level setting didn't specify something, then the global would be used.

**Comment by Pilchie** [comment]
That's absolutely the plan here - that `.editorconfig` files are aggregated from the directory closest to the file to the one furthest from the file, with the per-user VS registry options a backstop if there is no configuration for a given setting.

**Comment by scottdorman** [comment]
Nice. So you could define different settings at a folder level, then? What's the use case for being that granular?

**Comment by Pilchie** [comment]
When different parts of large codebase have different requirements.  For example, in Roslyn, we often allow hungarian naming in parts of the code that are doing interop with native VS COM interfaces, when those are the names in the PIAs.  Other examples are if projects use something like git submodules to include another project with different style settings.

**Comment by Pilchie** [comment]
(Oh, and it's nice to do folder instead of project in case there are groups of related projects that are organized by folder).

**Comment by scottdorman** [comment]
That makes sense. Thanks for clarifying. Overall, I like that approach.

**Comment by BillWagner** [comment]
I like that plan. Developers on OSS projects (using the tools) would just pick up the correct fixes.

**Comment by Pilchie** [comment]
This is done for now, right @jasonmalinowski ?

**Comment by jasonmalinowski** [comment]
Yes, this is done.
