### ISSUE TITLE
Code completion filters are not coming up in XAML

### ISSUE THREAD

**Issue by mohan636143** [dotnet/roslyn#70618]
## Summary
I have a project which has both `.cs` files and `.xaml` files
The code completion filters are not coming up for `XAML` files but the same works fine `cs` files.
Tried new solution, adding new user control to existing solution but the same happens.
Tried even disabling extensions that are added and also updated the VS2022 latest stable version.

## Background and Motivation
If the completion filters are coming up it would be easy to scroll through the wanted properties or events just like in `cs` files instead of scrolling through all the properties

![image](https://github.com/dotnet/roslyn/assets/24471825/1908c2f6-58a0-4eda-b132-ceea9f9e55f9)

**Comment by mohan636143** [comment]
Though the screenshot is with intellisense from resharper the same happens even when not using it. Below is the screenshot of the same

![image](https://github.com/dotnet/roslyn/assets/24471825/3b46dcf8-62e7-4a9a-b5fb-02bfb729eb6b)

**Comment by mgoertz-msft** [comment]
@mohan636143 This is not a Roslyn issue. There is a VS feedback ticket for this request here that you can upvote: https://developercommunity.visualstudio.com/t/filter-of-intelisense-on-xaml-editor/1161962

**Comment by genlu** [comment]
Thanks for the suggestion. As @mgoertz-msft mentioned, this functionality is provided by XAML language service with is not part of Roslyn.
