### ISSUE TITLE
[LSP] Populate the "relatedDocuments" property in the textDocument/diagnostic response

### ISSUE THREAD

**Issue by boost1231** [dotnet/roslyn#70616]
The Roslyn Language Server reports to the client that "diagnosticProvider. interFileDependencies" is true in the server capabilities. However, when changes to a text file are made that break code in other files, the "relatedDocuments" property is not populated with those diagnostics in the textDocument/diagnostic response.

Could this feature be implemented?

I searched the Roslyn LanguageServer repository and could not find any locations where the "relatedDocuments" property is set? Sorry if I missed it.

For reference: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#relatedFullDocumentDiagnosticReport

**Comment by CyrusNajmabadi** [comment]
These are unrelated concepts to us. The first is simply that, to our language, a change in one file impacts *all* other files (and as such, they must be requeried for diagnostics).  The second is if a particular diagnostic has other documents of interest (a concept which we've not found any use for currently).
