### ISSUE TITLE
Code Style: Analyzer + Code fix for use of var

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7062]
Should have options for:
* Use `var` whenever possible
* Never use `var`
* Use var if the type appears on the RHS (cast expressions, etc)

**Comment by sharwell** [comment]
Another option:

* *Allow* `var` if the type appears on the RHS. This could of course be partially done by making the "use var if the type appears on the RHS" an Info-level diagnostic, but the reason I want to add this case specifically is I'm interested in the ability to make the use of `var` in other cases an error.

**Comment by Pilchie** [comment]
Subtle distinction, but worth being explicit about yes.

**Comment by bkoelman** [comment]
Suggestion: option for "do not use var on primitive types" (because `var` it is not substantially shorter in those cases, so more readable)

**Comment by Pilchie** [comment]
This is in now.
