### ISSUE TITLE
Label indentation wrong when immediately following if/for without brackets in dotnet format

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/roslyn#70622]
**Version Used**: 8.0.452414+aadaa166c39c8686c55dbec3462355b1ca033b62

**Steps to Reproduce**:

1. Run `dotnet format` against this code:
```csharp
class TestClass
{
    void Test(object obj)
    {
        if (obj == null)
            goto firstLabel;

    firstLabel:
        return;

    secondLabel:
        return;
    }
}
```

**Expected Behavior**:

No change, `firstLabel` is at the same indentation level as the containing method.

**Actual Behavior**:

`firstLabel` is indented to match the `if/goto` preceding it:

```csharp
class TestClass
{
    void Test(object obj)
    {
        if (obj == null)
            goto firstLabel;

        firstLabel:
        return;

    secondLabel:
        return;
    }
}
```

If I put curly braces around the `goto` then it gets indented correctly.

**Comment by akoeplinger** [comment]
This seems to happen for all selection/iteration statements without curly braces, e.g. `for` followed by a label.

**Comment by DoctorKrolic** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/38245

**Comment by akoeplinger** [comment]
Closing as duplicate of https://github.com/dotnet/roslyn/issues/38245
