### ISSUE TITLE
Code Style: Analyzer + Code fix for member naming conventions

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7064]
For privates support _, m_, or nothing.

For other accessibilities, check for capitalization

**Comment by sharwell** [comment]
The hard part we ran into here is exposing the following without the number of options becoming overbearing for users:

* StyleCop wants `static readonly` fields to start with a capital letter, even if they are `private`
* dotnet/corefx wants `static` fields to start with `s_`, unless they are also marked `[ThreadLocal]`, which changes the prefix to `t_`.

So in general, users typically only have a small set of available prefixes, but application of these to individual fields is almost an arbitrary combination of the following variables:

* static
* readonly
* const
* accessibility (could be based on either declared or effective accessibility, and may require special treatment for explicitly implemented interface members)
* thread-local

**Comment by Pilchie** [comment]
Interesting - thanks for the insight!

**Comment by Pilchie** [comment]
This is in now.
