### ISSUE TITLE
Code Style: Analyzer + Code fix for requiring/prohibiting this/Me

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7065]
We have an analyzer + code fix to support removing redundant uses, but we need options for what type of access it is (field/property/method/etc), and to require it.

**Comment by sharwell** [comment]
We've implemented support for **require** ([SA1101](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1101.md)) and **avoid** (only use when required to disambiguate) ([SX1101](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1101.md)). While we haven't exposed configuration for the type of member being accessed, it wouldn't be difficult to do so. Currently you use a rule set file to select the mode you want to use along with the severity, but I'm considering merging the two rules and exposing an option in our **stylecop.json** file instead.

**Comment by Pilchie** [comment]
This is in now.
