### ISSUE TITLE
Line completion forces suggested method parameter when typing quotes, causing an error

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/roslyn#70661]
**Version Used**: VS 17.7.4
Developer community ticket: https://developercommunity.visualstudio.com/t/Line-completion-puts-suggested-variable/10328908

**Steps to Reproduce**:

1. Create C# console app with a `main` method (no top-level statements)
2. Type `var fs = File.OpenRead(` and notice that it suggests passing `args[0]`
3. Type a double-quote character to provide a string parameter as 1st parameter.
4. Line completion forces the word `args` in front of the double-quote, causing a syntax error.
 
![BadLineCompletion3](https://github.com/dotnet/roslyn/assets/12361341/1848229b-ec16-4436-ae7e-43a01547f87b)

This happens with many other method calls, not just `File.OpenRead` and slows productivity. It seems to be when providing a string parameter, but not only when the string parameter is the 1st parameter, and not only inside the `main` method. Look at the below animation. I'm calling a method I made in a helper class, with a string parameter as the 2nd one. Same forced problem:

![BadLineCompletion1](https://github.com/dotnet/roslyn/assets/12361341/f1f3bb0f-5e11-4b9a-a5b9-48da9090c0ff)

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**: Don't force a suggested parameter when I type quotes.

**Actual Behavior**: Suggested parameter is forced, causing syntax error.

**Comment by CyrusNajmabadi** [comment]
This is not Roslyn. I think it's whole-line-completion. Tagging @dpugh and @olegtk to see if they can route this to the right team.

**Comment by Dean-NC** [comment]
@CyrusNajmabadi Thanks. I didn't know where to post it.

**Comment by CyrusNajmabadi** [comment]
Closing as this is not roslyn and the responsible team was pinged here.  if you're sstill running into this issue, please file an issue with visual studio. thanks.

**Comment by Dean-NC** [comment]
This was fixed, and I believe it was in VS 17.10.x.

**Comment by CyrusNajmabadi** [comment]
Good to know.  Thanks :)
