### ISSUE TITLE
Code Style: Analyzer + Code fix for modifiers 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7066]
We should support requiring default or requiring explicit, and a specific ordering

**Comment by sharwell** [comment]
I assume you are referring to an implementation of a rule similar to [SA1400: Access modifier must be declared](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md) along with its opposite?

For ordering, I'm assuming you mean a unification/generalization of the following rules:

* [SA1206: Declaration keywords must follow order](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md)
* [SA1207: Protected must come before internal](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1207.md)

**Comment by Pilchie** [comment]
Yes, exactly.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Isn't this done?  Is there anything else to do here?

**Comment by Pilchie** [comment]
I think so.

**Comment by onovotny** [comment]
Is this done? If I to `ctrl + .` from a ctor to add a new field, it creates it as `private .... `. I want a rule that doesn't emit the default accessibility modifiers.

**Comment by CyrusNajmabadi** [comment]
I believe the work was done to allow enforcement of a specific order for modifiers.  I don't think we have anything around default accessibility.

**Comment by CyrusNajmabadi** [comment]
Feel free to contribute such a thing though if you think it would be valuable :)

**Comment by onovotny** [comment]
I'm not even sure where to begin with such a thing. It shouldn't be an analyzer, it should be an editorconfig setting for .NET.

FWIW, it falls into the category of R# compete.

**Comment by CyrusNajmabadi** [comment]
> I'm not even sure where to begin with such a thing. 

@onovotny You can look at my PR here https://github.com/dotnet/roslyn/pull/20517 which added support for enforcing modifier order.

It's not that difficult to do.  

> It shouldn't be an analyzer, it should be an editorconfig setting for .NET.

analzyers are how we enforce editor config settings.  

--

Note: i already did the work here https://github.com/dotnet/roslyn/pull/20911 to add the option to make accessibility modifiers required, and to have the analyzers+fixer which adds them if missing.  However, there is no way to currently say that accessbility modifiers should be disallowed if redundant.  You could definitely easily add that without too much trouble.

**Comment by CyrusNajmabadi** [comment]
So, to sum up, we currently have:

1. A code-style+analyzer+fixer that allows users to specify modifier order, and to enforce and fixup nonconformant code..
2. A code-style+analyzer+fixer that allows users to specify that accessibility modifiers are required, and to enforce and fixup nonconformant code.

What we are missing is a code-style that allows users to specify that accessibility modifiers should be disallowed when redundant.  Once we have that, the existing analyzer+fixer for '2' can be updated to enforce and fixup code appropriately.

**Comment by onovotny** [comment]
Looking at the code here:
https://github.com/dotnet/roslyn/pull/20911/files#diff-379e50afd4d83d3c52706cceaeff98d1R162

Should the value of `never` be equal to `disallowed` or is that semantically different?

**Comment by CyrusNajmabadi** [comment]
It's semantically different.  the 'never' (i.e. the default value) means that the user does *not* require accessibility modifiers (i.e. the way we've shipped since forever).  That's a distinctly different value than "redundant modifiers are disallowed".  We'd need a new value to represent that.  

Note: this should likely go in a different enum.  The current enum describes when modifiers are required.  We'd want an enum describing when modifiers are disallowed.

**Comment by CyrusNajmabadi** [comment]
So we currently have "dotnet_style_require_accessibility_modifiers".  We probably need "dotnet_style_require_disallow_modifiers={never,when_unnecessary}"

**Comment by CyrusNajmabadi** [comment]
The downside of this approach is that it essentially means that we have two opposing options, one which supercedes the other.  

Alternatively, we could have one option, but it would like read very strangely.  i.e. if you had:

dotnet_style_require_accessibility_modifiers=...

What would you put on the right to indicate the idea that you are in fact *not* requiring and *not* allowing accessibility modifiers?

**Comment by onovotny** [comment]
Still not entirely sold on the fact it's a "disallow." Maybe just a different required style value that says `when_not_default`?

**Comment by CyrusNajmabadi** [comment]
> Maybe just a different required style value that says when_not_default?

Er... what does that mean ?    if it's not the default... then you must have had the modifiers there.

**Comment by CyrusNajmabadi** [comment]
The only thing this stuff controls is what happens when the modifier you have is the same that hte language would have picked.

**Comment by onovotny** [comment]
That's why I interpreted the `required=never` option as redundant shouldn't be there and `always` is essentially the current behavior

**Comment by CyrusNajmabadi** [comment]
>  and always is essentially the current behavior

but it isn't.  we don't go in and squiggle your code, telling you there's a problem, when you say something like "int field;"  if 'always' is the default, then that code has a problem.

**Comment by onovotny** [comment]
> but it isn't. we don't go in and squiggle your code, telling you there's a problem, when you say something like "int field;" if 'always' is the default, then that code has a problem.

That's correct...it should be a problem if `always` is the default. It seems like the issue is that the current default behavior allows/doesn't squiggle for inconsistent style, and I think that's wrong.

**Comment by CyrusNajmabadi** [comment]
the option is called "require_accessibility_modifiers" intentionally.  it specifies when an accessibility modifier should be required, and when the system should notify you and let you know when your code is noncofrming.

"never" means "modifiers are *never* required.  i can have them, or not have them, and that's fine".  This has been the default behavior of the IDE for years.  We can't change it or else literally millions of lines of code will get notifications about having a problem.

"always" means "modifiers are always required, i must have them, no matter what".  Users can opt into this for code bases (like roslyn) that require them.

**Comment by onovotny** [comment]
So to be consistent with the existing behavior, how about "require_accessibility_modifiers` = `not_redudant`

**Comment by CyrusNajmabadi** [comment]
>  It seems like the issue is that the current default behavior allows/doesn't squiggle for inconsistent style, and I think that's wrong.

That is very right.  :)   We can't suddenly decide that all the code out there is "inconsistent" and needs squiggling.  Only users can decide that for their own projects.  For example, i would be upset if i downloaded a new version of VS and it decided to start telling me my accessibility modifiers were a problem :)

**Comment by onovotny** [comment]
or `require_accessibility_modifiers` = `disallow_redudant `

**Comment by CyrusNajmabadi** [comment]
> So to be consistent with the existing behavior, how about "require_accessibility_modifiers=not_redudant`

We could have that.  Though it doesn't really read properly.  nothing about htat indicates that "it's *wrong* to put 'private' on a field" for example.   

Hence my thought that this shoudl be a different option.  Now the option clearly states that these are the cases wher emodifiers are *disallowed*, whereas the current option indicates these are the cases where modifiers are *required*.

**Comment by CyrusNajmabadi** [comment]
basically: we can definitely just add another option to "require_accessibility_modifiers"  and we can explain what it means.  It's just going to read oddly.  "here is the option that specifies when modifiers are required.  except if you give this one value, and then it specifies when modifiers are actually disallowed".  It's totally doable, and likely the easier to implement (as you won't have to create a new option+enum+parse-function+etc.).

However, the cleaner approach is to separate out the two concepts:

1. here is the option that controls when the user must provide modifiers.
2. here is the option that controls when the user must *not* provide modifiers.  

Downside is that you could have contradictory values here.  For example, saying "always require redundant modifiers" contradicts "never provide redundant modifiers".

**Comment by CyrusNajmabadi** [comment]
I'm ok with either approach :)

**Comment by onovotny** [comment]
yeah, either way is fine with me. challenge is that it's likely an easy update for someone who knows analyzers and less-so for someone who doesn't :)

**Comment by CyrusNajmabadi** [comment]
Since our options are effectively a public API, i would prefer we do things the 'right way' and have options that cleanly specify their purpose (i.e. having two options here).

This would be a great way to learn analyzers.   As mentioned, you can already just look at the existing code and augment it for this.  The new option would just slot in next to the current option, and you'd just need to update the linked analyzer+fixer.  Super duper easy and a nice small thing to work on to learn from! :)

**Comment by onovotny** [comment]
Maybe I can nerd-snipe @bradwilson in to this one ;)

**Comment by bradwilson** [comment]
I'm afraid I don't know what opinion you wished I had. 😉

**Comment by onovotny** [comment]
I'm going to try to look at this again... @bradwilson I was hoping to snipe you into creating the editorconfig/analyzer to prevent default modifiers from appearing (and flagging those that are there as a warning/error). I.e., your preferred style.

**Comment by onovotny** [comment]
@CyrusNajmabadi Should I look at essentially copying #20911 (all the touch points) for this rule, which is the inverse?

**Comment by CyrusNajmabadi** [comment]
Yup!
