### ISSUE TITLE
Compiler-caused ambiguity (CS0121)

### ISSUE THREAD

**Issue by bradwilson** [dotnet/roslyn#70665]
**Version Used**: `4.7.0-3.23517.17 (9d4cc030)`

**Steps to Reproduce**:

In [xUnit.net's assertion library](https://github.com/xunit/assert.xunit) we offer overloads of functions that take either [`Task`](https://github.com/xunit/assert.xunit/blob/e48a306669184bba25bddbbacfb44113f2f3bf68/ExceptionAsserts.cs#L337) or [`ValueTask`](https://github.com/xunit/assert.xunit/blob/e48a306669184bba25bddbbacfb44113f2f3bf68/ExceptionAsserts.cs#L350). These are commonly used via lambda functions, like:

```csharp
await Assert.ThrowsAsync<DivideByZeroException>(async () => { /*...something that throws...*/ });
```

Which causes C0121:

![Screen shot from user reported issue](https://user-images.githubusercontent.com/1730868/279636440-4adad1a4-14fb-4b9a-b9b5-78abcafe9033.png)

The thing is...the compiler is responsible for both matching the function _and_ generating the signature of the lambda. It could easily choose either one (I assume with a preference towards `ValueTask` due to performance), but it does neither and just fails. And the syntax does not even let the user choose, so the only way around this is to write a function instead of use a lambda.

**Diagnostic Id**: `CS0121`

**Expected Behavior**:

Pick one and compile. 🎉 

**Actual Behavior**:

Make developer sad. 😢 

_Related xUnit.net issue: https://github.com/xunit/xunit/issues/2808_

**Comment by CyrusNajmabadi** [comment]
ValueTask is not a preferred type. It can often be worse.  Specifically, in the case - where something is actually active, it performs worse. My recommendation is to not have both. Just have the Task version. If someone has a ValueTask method they want to test, they can just do `await` on it, or do `.AsTask()` on it. 

We would not recommend overloading on delegates that differ in this way.

**Comment by bradwilson** [comment]
@CyrusNajmabadi Can you explain why you don't just pick `Task`, then, if this is the opinion of the compiler team that `ValueTask` is often worse?

**Comment by CyrusNajmabadi** [comment]
It's often worse. It's often better. Ergo, neither should be picked over the other.
