### ISSUE TITLE
Complete Word fails in collection expression

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70677]
**Version Used**: Version 17.9.0 Preview 1.0 [34216.205.main] (fe6cc3e)

**Steps to Reproduce**:

Place the following code in Roslyn's integration test library, with `FeatureAttribute` namespace not yet imported. Press <kbd>Ctrl</kbd>+<kbd>Space</kbd> at the location marked with `$$`.

```cs
await TestServices.Workspace.WaitForAllAsyncOperationsAsync(
    [
        FeatureAttribute.Workspace,
        FeatureAttribute.SolutionCrawlerLegacy,
        FeatureAttribute.DiagnosticService,
        FeatureAttrib$$ute.EditAndContinue,
        FeatureAttribute.ErrorSquiggles,
        FeatureAttribute.ErrorList,
    ],
    HangMitigatingCancellationToken);
```

**Expected Behavior**:

_Either_ the namespace is automatically imported, or a completion list is shown with `FeatureAttribute` being at item from an unimported namespace.

**Actual Behavior**:

Nothing happens.

**Comment by CyrusNajmabadi** [comment]
@sharwell I don't see a $$ in the test code. Can you update?  Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi I went to edit, but there is already a `$$` present
