### ISSUE TITLE
Code Style: Analyzer + Code fix for spacing

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7067]
We have a formatting engine, but we need an analyzer to indicate when formatting needs to be applied.

Also, we should expand the formatting to support more/all of the StyleCop options (spaces after newline), etc.

**Comment by sharwell** [comment]
[Have to comment so it notifies me of replies.]

**Comment by CyrusNajmabadi** [comment]
We have this.  IDE0055 serves this urpose.
