### ISSUE TITLE
Code Style: Support running Code Fixes automatically as part of a cleanup experience

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7068]

**Comment by sharwell** [comment]
:+1: This will save people a *tremendous* amount of time when they want to adopt style analyzers in a project that didn't previously use them. The particularly important item is making sure code fixes have a way to indicate that they are "pure", meaning they will not make *any* semantic changes at *any* level - absolutely no semantic changes even to the internals of methods. This set of code fixes can be run as a batch operation to safely and efficiently correct large numbers of style violations (even on the order of 500,000+).

**Comment by Pilchie** [comment]
This is actually meant to track something different (though I agree that what you describe is important as well!).

This is more about having formatting type actions (save/typing a `}`, invoking Edit.FormatDocument, etc) will apply more than just whitespace changes - but also things like inserting braces around embedded statements, making modifiers explicit, etc.

Separately, we're looking at making something like dotnet/codeformatter available to bulk update codebases on style changes.

**Comment by DustinCampbell** [comment]
This is related to #8928

**Comment by CyrusNajmabadi** [comment]
@jmarolf this is done now right (with Code Cleanup)?

**Comment by jmarolf** [comment]
yep this is complete
