### ISSUE TITLE
System.BadImageFormatException: Could not load file or assemby 'csc.exe' or one of its dependencies.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemBadImageFormatException:-Could-no/10502149)._

---
System.BadImageFormatException: Could not load file or assemby 'csc.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.
This happens when creating a new project as well.

 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : 
4>  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(80,5): error : Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'csc.exe' or one of its dependencies. An attempt was made to load a program with an incorrect format.

---
#### Watts, John on 10/27/2023, 06:04 AM: 

(private comment, text removed)
#### Feedback Bot on 10/29/2023, 10:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@jaredpar do you know what should be done with this report?  Thanks!

**Comment by jaredpar** [comment]
Closing as this looks like a setup issue. Please try repairing setup on the machine. If that does not work then please let us know and we'll reactivate the VS feedback bug.
