### ISSUE TITLE
C# editor auto complete fails, if followed by an operator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70732]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-editor-auto-complete-fails-if-follow/10509365)._

---
If you want to access a member of an object, you would type "<name of object variable>.<name of member>". As soon as the '.' is typed, a list of suggestions comes up, which is filtered as you start typing the name of the member. If the option is set to always have the suggestion list automatically preselect the first option, you can stop typing the name as soon as the correct option is highlighted. If you continue for example with ';' or type '.' to access a member of the member, the partial name after the first '.' is auto-completed. However this does not work, of the literal following the name of the member is an operator. 

Example:

```
PointF p, q;
float value = p.X + q.X;
```
In this scenario typing 'p.x' (lower case x) is sufficient to select the correct property and auto complete will fix this to upper case, if you for example continue with ".ToString()". If however the member is used in some math formula involving operators like in the above example, auto completion is not correctly triggered, when the operator '+' is typed in and only the second instance if '.x' will be fixed.

Especially when writing readable math heavy code, this is very annoying.

---
#### Feedback Bot on 11/7/2023, 06:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
@genlu this seems like a reasonable suggestion.  Could you take a look to see if it would be easy to do?

**Comment by genlu** [comment]
'+' is one of the default commit char, so not sure why this isn't working. Will take a look

**Comment by genlu** [comment]
OK, it's `UnnamedSymbolCompletionProvider` causing the operators to be excluded from commit chars

**Comment by CyrusNajmabadi** [comment]
But aren't these items provided by the symbol provider?

**Comment by genlu** [comment]
Yes. There's a bug where we collect all excluded commit chars from each item, and try to use it to make a quick decision.
