### ISSUE TITLE
IntelliSense stopped working after upgrade

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70734]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-stopped-working-after-upgra/10505106)._

---
[severity:Other]
Visual Studio upgraded itself from 2022 Preview 17.8.0 4.0 to 5.0 and IntelliSense stopped working. I couldn't work. but Bing AI helped me fix the problem.

---
#### Feedback Bot on 11/1/2023, 06:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Will need more information from customer as to what went wrong and what the repro steps are.  given htat we haven't heard about this from anyone else, it's unlikely we could do anything about this.
