### ISSUE TITLE
Diagnostics do not work when configured from Solution Explorer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70740]
**Version Used**: Version 17.9.0 Preview 2.0 [34305.10.main]

**Steps to Reproduce**:

1. Open a solution
2. Open a source file within the solution
3. Open **Tools &rarr; Options... &rarr; Text Editor &rarr; C# &rarr; Advanced**
    1. Set **Run background code analysis for:** to **None**
    2. Set **Show compiler errors and warnings for:** to **None**
    3. Enable (check) **Enable 'pull' diagnostics**
4. Right click the solution node in **Solution Explorer &rarr; Analyze and Code Cleanup &rarr; Set Analysis Scope &rarr; Open Documents**
5. Close Visual Studio
6. Reopen Visual Studio by double clicking the same solution from (1), so previously opened document from (2) is again open
7. Introduce an error within the document, e.g. by removing a required `;`

**Expected Behavior**:

Diagnostics appear for the open document.

**Actual Behavior**:

Diagnostics do not appear in any document.

**Comment by CyrusNajmabadi** [comment]
@mavasani please take a look.

**Comment by mavasani** [comment]
This seems to be a bug in how RoslynPackage and PackageSettingsPersister coordinate initialization of each other. All of this is completely busted, regardless of LSP pull diagnostics being enabled or not.

Seems like changing the solution specific analysis scope doesn't update the underlying option in the option service, only the scope value stored in the Roslyn package. Basically, this handler is never getting invoked:
https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Options/PackageSettingsPersister.cs,50

This one throws:
https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Options/PackageSettingsPersister.cs,44

As this one returns failed:
https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/RoslynPackage.cs,108

There seems to be a cycle here, not sure how this ever worked. We load option persisters during RoslynPackage initialization here:
https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/RoslynPackage.cs,156
. The PackageSettingsPersister in turn tries to fetch the loaded RoslynPackage.
https://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Options/PackageSettingsPersister.cs,36
seems to run instantly and leads to crashing out as there is no loaded package

**Comment by mavasani** [comment]
I am going to assign this bug back to @sharwell as he is familiar with this piece of code that hooks up the solution specific analysis scope to the `RoslynPackage`. I am not sure at what point the shell's `IsPackageLoaded` API is expected to succeed and how we can defer `PackageSettingsPersister.InitializeAsync` to be invoked after that

**Comment by sharwell** [comment]
@mavasani The above looks like one of the package load errors related to the experimental instance recently. For the case you observed (which does not happen in a more general sense), RoslynPackage did not load at all. I would recommend resetting your experimental instance to fix the package load errors or debugging the main hive.

**Comment by mavasani** [comment]
Thanks, I'll try again after resetting my hive. However, I have tried various combinations of setting the solution specific analysis scope on the main hive and none of them work, both for LSP pull diagnostics enabled and disabled. So, it seems this feature is not working at all.

**Comment by mavasani** [comment]
Alright, resetting the hive did not help. Given that the experience on the main hive is identical to the dev hive, it feels even more likely to me that the same issue noted in https://github.com/dotnet/roslyn/issues/70740#issuecomment-1829238154 is happening on the main hive and this feature itself is broken.

@sharwell can you please check if solution specific analysis scope is being respected for you in configuration on the main hive? I am also interested in knowing if there has been any external feedback about this. If not, I am starting to wonder if this feature is even being used at the extent that we need to keep fixing/maintaining it.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski can you ptal.  Something seems wrong.  I have no idea if it is related to hives, or just is a pure bug on our end.  See internal teams chat.  But the short of it is:

This seems to always be crashing:

![image](https://github.com/dotnet/roslyn/assets/4564579/4260ec90-ab07-4603-bf72-3b9cccc80d51)

As such, nothing about this persister is working properly.
