### ISSUE TITLE
If you 'add class' and pick a name that already exists, we should make the type partial and pull over all information that needs to match.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7075]

**Comment by davkean** [comment]
Or offer to do that - this almost is never the behavior I want.

**Comment by davkean** [comment]
Or do mean Extract Class?

**Comment by CyrusNajmabadi** [comment]
I mean 'add class'.  I'm using it to add another partial, but then i need to go fix up everything manually.

**Comment by DustinCampbell** [comment]
@Pilchie and I are of the opinion that we shouldn't do this.
