### ISSUE TITLE
Find Usages presenter keeps a GC root to a full Solution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70753]
The following `Document` reference indirectly GC roots an entire `Solution` in StreamingFindUsagesPresenter.DocumentSpanEntry.

https://github.com/dotnet/roslyn/blob/65fc4bd08b4bc15f6f00b529f47ffaeead03e434/src/Workspaces/Core/Portable/Workspace/Host/DocumentService/IDocumentExcerptService.cs#L57-L62

This was responsible for more than 1GB of memory overhead in a recent heap dump investigation.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculaative.  If this is an actual issue (which i'm not sure why it would be as it's fine if something in the UI is readily present and holding onto a snapshot for the data is relates to), then we should assign to a milestone for this to be done in.
