### ISSUE TITLE
String interpolation doesn't allow bracket escapes in format string

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#70779]
**Version Used**: 4.4.0-6.22561.11 (1ce8866c)

**Steps to Reproduce**:
```csharp
using static System.Console;
WriteLine($"{1:a{{}");
WriteLine($"{1:{{b}");
WriteLine($"{1:a{{b}");
WriteLine($"{1:a}}b}");
WriteLine($"{1:{{a}");
```
https://sharplab.io/#v2:CYLg1APgAgDABFAjANgYgdAYQPYDsDO2ANgKYDcAsAFADqATgJYAuJAMg7iQBQAkARAG9EIAIYCBAXz4BKSrUYt2nXoOHiARlNnV6zNh278hojVrm7FBlcZESJmmeYX7lRtQNuOgA===

**Diagnostic Id**:
`CS1056`, `CS8086`

**Expected Behavior**:
The code compiles successfully and the escape brackets are moved to the format string, like described in the specification

```antlr
Regular_Interpolation_Format
    : ':' Interpolated_Regular_String_Element+
    ;

fragment Interpolated_Regular_String_Element
    : Interpolated_Regular_String_Character
    | Simple_Escape_Sequence
    | Hexadecimal_Escape_Sequence
    | Unicode_Escape_Sequence
    | Open_Brace_Escape_Sequence
    | Close_Brace_Escape_Sequence
    ;
```
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1283-interpolated-string-expressions

**Actual Behavior**:
The code fails to compile because brackets are not allowed in the format string

**Comment by 333fred** [comment]
As I mentioned, there is no need for a roslyn issue. It already exists in https://github.com/dotnet/roslyn/issues/57750.
