### ISSUE TITLE
Exception in CompletionProvider takes down IntelliSense

### ISSUE THREAD

**Issue by jbevain** [dotnet/roslyn#70786]
**Version Used**: 
main

**Steps to Reproduce**:

1. Create custom completion provider which unfortunately throws in `ShouldTriggerCompletion`:

```csharp
[Export]
public class ThrowingCompletionProvider : CompletionProvider
{
    public override bool ShouldTriggerCompletion(SourceText text, int caretPosition, CompletionTrigger trigger, OptionSet options)
    {
        throw new Exception();
    }
}
```

**Expected Behavior**:

This is debatable.

Maybe the expectation is that the author of the CompletionProvider should catch all exceptions to prevent them bubbling up?

Given that this is a public extension point, it could also be wise for Roslyn to protect from user code throwing exceptions.

**Actual Behavior**:

The exception effectively prevents the IntelliSense from showing up.

**Comment by CyrusNajmabadi** [comment]
We should probably yellow-bar this, and disable that completion provider.

**Comment by sailro** [comment]
Perfect. Thanks!
