### ISSUE TITLE
Completion UI not called when typed char is a number

### ISSUE THREAD

**Issue by TheHandsomeBanana** [dotnet/roslyn#70798]
Microsoft.CodeAnalysis 4.7 

```
[ExportCompletionProvider("MyCompletionProvider", LanguageNames.CSharp)]
[TextViewRole(PredefinedTextViewRoles.Editable)]
internal class MyCompletionProvider : CompletionProvider {
    public override async Task ProvideCompletionsAsync(CompletionContext context) {
        var completions = GetCompletionItems(); // Logic to get completion items
        context.AddItems(completions.Select(e => CompletionItem.Create(e.DisplayText)));
    }

    public override bool ShouldTriggerCompletion(SourceText text, int caretPosition, CompletionTrigger trigger, OptionSet options) {
        return char.IsDigit(trigger.Character);
    }
}
```

The completions are commited correctly when typing a digit (The CompletionItem.Create() Method is indeed called), but the completion ui (The completion list with all the completion items) is not shown. Is that supposed to be like this?

**Comment by genlu** [comment]
Is this in VS? If so, this is by design. Here's the code for the logic with reasoning for the behavior in the comment
https://github.com/dotnet/roslyn/blob/a35b73595c954a0281fac24e0b6136eca572db7a/src/EditorFeatures/Core/IntelliSense/AsyncCompletion/ItemManager.CompletionListUpdater.cs#L220

**Comment by CyrusNajmabadi** [comment]
Closing due to lack of response.
