### ISSUE TITLE
Create nuget package for scripting

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/roslyn#708]
A month ago scripting feature came back. That's great news. Unfortunately it is not available in nightly nuget packages. 

I am aware it is work-in-progress and a lot is changing there now, but still it would be great to have a signed versions (this is something you often run in non-full-trust-environment) of Microsoft.CodeAnalysis.Scripting and Microsoft.CodeAnalysis.Scripting.CSharp (through nightlies channel).

**Comment by jasonwilliams200OK** [comment]
+1000000
**Please** add REPL APIs, so we can get some cool stuff via [scriptcs](https://github.com/scriptcs/scriptcs/).
Related: https://github.com/scriptcs/scriptcs/issues/614.

Copy @filipw, @khellang.

**Comment by filipw** [comment]
This is related to #907

**Comment by ManishJayaswal** [comment]
Scripting NuGet packages are now available in nightly Roslyn feed at myget.org
