### ISSUE TITLE
Migrate C# tests to be less sensitive to the precise text of error messages

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7081]
In order to be able to improve diagnostic text without having to change many tests, most C# tests check for the abstract error (error ID, location and fill-ins) rather than the precise error text. However, a few use a pattern where the precise text is tested.

We should migrate those tests to check for the abstract error.

See also [a commend on a recent PR](https://github.com/dotnet/roslyn/pull/7048#issuecomment-159765502) where this was a pain-point for an external contributor:

> @leppie Looks like some of our semantic analyzer tests have hardcoded strings.
> 
> http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/Semantics/SemanticAnalyzerTests.cs,176

**Comment by leppie** [comment]
Should old test methods like `TestErrors(...)` be marked obsolete to prevent using it and suggest using `VerifyDiagnostics(...)` instead?

**Comment by leppie** [comment]
@gafter There seems to be a gazillion of these for VB too

**Comment by gafter** [comment]
VB likes it that way.
