### ISSUE TITLE
IDE0028 code fixer produces invalid code (build error, invalid syntax)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#70826]
**Version Used**: 4.8.0-7.23558.1 (e0917286)

**Steps to Reproduce**:

1. Paste this code:

```csharp
static void M1(bool condition, int number)
{
    List<int> list = new();

    if (condition)
    {
        list.Add(number);
    }

    M2(list);
}

static void M2(List<int> list)
{
}
```

2. Apply the code fixer for the IDE0028 warning over that `new()`

**Diagnostic Id**: IDE0028 

**Expected Behavior**:

The code fixer should just change the `new()` to `[]` and not try to merge the other statements if it can't actually be done.

**Actual Behavior**:

The code fixer changes the code to be invalid, which then fails to build:

![image](https://github.com/dotnet/roslyn/assets/10199417/624f2af2-dd18-4456-a1ca-d807632e420c)

cc. @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
What build of vs are you on?

**Comment by Sergio0694** [comment]
Just normal VS 17.8 stable, using the .NET 8 stable SDK.

**Comment by CyrusNajmabadi** [comment]
Thanks. Will check today. Very odd.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70173.  Will be in 17.9p1.
