### ISSUE TITLE
`IDE0028` suggests collection expression when assigning to a `dynamic` LHS

### ISSUE THREAD

**Issue by alexrp** [dotnet/roslyn#70822]
**Version Used**: .NET 8.0.100

**Steps to Reproduce**:

```csharp
using System.Dynamic;

static void Foo(dynamic expando)
{
    expando.Missing = new List<string>();
}

dynamic expando = new ExpandoObject();

Foo(expando);
```

Also a `.globalconfig` with `dotnet_diagnostic.IDE0028.severity = error`.

**Diagnostic Id**:

`IDE0028`

**Expected Behavior**:

No diagnostic.

**Actual Behavior**:

`Z:\Source\tests\dynamic\Program.cs(5,23): error IDE0028: Collection initialization can be simplified (https://learn.microsoft.com
/dotnet/fundamentals/code-analysis/style-rules/ide0028) [Z:\Source\tests\dynamic\dynamic.csproj]`

**Comment by CyrusNajmabadi** [comment]
I do not repro this:

![Image](https://github.com/user-attachments/assets/7e625ce6-6e7b-433d-9afa-fbb08d2be319)
