### ISSUE TITLE
[Bug]: 'Invert Logical' code action has malformatted message

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#70828]
(Moved from https://github.com/MicrosoftDocs/intellicode/issues/522)

### Version Used
* Compiler version: '4.9.0-1.23530.4 (79d1884d)'
* VSCode: 1.84.2, 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, x64
* C# extension: v2.10.28, C# Dev Kit extension: v1.1.9
* IntelliCode for C# Dev Kit: v0.1.26

### Steps to Reproduce

1. Create or open any C# file in Visual Studio Code.
2. Create a boolean expression containing a logical operator. Something as simple as `if (true && true) { }` works.
3. Select any token in the boolean expression and view the code actions to see the faulty message.

### Expected Behavior
The displayed message says `Replace '&&' with '||'`.

### Actual Behavior
The displayed message says `Replace '&&' with ' -> -> '`.

**Comment by just-ero** [comment]
cc @cyrusjamula

**Comment by just-ero** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@akhera99 @dibarbet this was the issue I was talking about. We can't blindly manipulate code action titles. Attempting to use `|` as a special character is bogus.

**Comment by akhera99** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70475
