### ISSUE TITLE
Missing case in NRT control-flow analysis

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#70829]
**Version Used**: .NET 8 RTM

**Steps to Reproduce**:

```cs
int M(int[]? arr)
{
    if ((arr?.Length ?? 0) != 1) return 0;
    return arr[0];
}
```

Such pattern is widely generated by CsWin32 and results in warnings, which is pretty annoying. 

**Expected Behavior**:

No warning.

**Actual Behavior**:

warning CS8602: Dereference of a possibly null reference.

**Comment by CyrusNajmabadi** [comment]
I don't know of anything in the language, NRT, or flow control space that would make this not a warning.  We'd have to track that relation between `??` and `!=`.  @RikkiGibson how are these requests handled?  Are they language feature requests?

**Comment by RikkiGibson** [comment]
This is a language feature request. Nullable analysis doesn't track these conditions as designed. It would be a fairly large undertaking to try and do this. We've also had requests to be able to track "not null when expression is a certain enum value", for example. But I don't believe the demand currently justifies the cost of a change here.

**Comment by CyrusNajmabadi** [comment]
Thanks.  Closing out.  As a language request, you can start a discussoin on this over at github.com/dotnet/csharplang @hez2010 .  Thanks!
