### ISSUE TITLE
CS0121 call is ambiguous due to string beeing a candidate for a collection expression.

### ISSUE THREAD

**Issue by FreeApophis** [dotnet/roslyn#70831]
**.NET 8**: 

**Steps to Reproduce**:

```cs
var text = "alpha,beta,gamma";

// I use a collection expression instead of the old way of creating an Array.
var parts = text.Split([" ", ","], StringSplitOptions.RemoveEmptyEntries); // compiles
var parts = text.Split([' ', ','], StringSplitOptions.RemoveEmptyEntries); // error CS0121: The call is ambiguous between the following methods or properties: 'string.Split(char[]?, StringSplitOptions)' and 'string.Split(string?, StringSplitOptions)'
```

`char[]?` and `string?` are ambiguous!

So I thought, oh ambiguous, this is interesting, so I can construct a string with a collection expression?

```cs
string text = ['H', 'e', 'l', 'l', 'o'];
```

This leads to multiple errors, which all seem weird too:

* `error CS1729: 'string' does not contain a constructor that takes 0 arguments`
* `error CS1061: 'string' does not contain a definition for 'Add' and no accessible extension method 'Add' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)`

**Expected Behavior**:

I am not 100% sure what the expected behaviour should be, but since this is a new feature I am sure some clarification would be good.

Intuitivly I would say: either the call to Split should not be ambiguous or the string should be constructible with a collection expression.  But failing both seems like unexpected behaviour, the errors for the string seem odd too. So it might be a specific problem with string.

**Actual Behavior**:

I do not see the need to construct a string from a collection expression even considering the spread operator, so I would say the overload with the string should not be considered which would make the call unambiguous.

**Comment by CyrusNajmabadi** [comment]
@FreeApophis This is expected behavior in C# 12 (we know we want strings to be involved in collection expressions).  HOwever, the language changes to make this a supported scenario will be coming in the future (ideally C# 13).  Could you add your feedback on this to dotnet/csharplang?  Thanks!
