### ISSUE TITLE
Unexpected CS8602 generated in local function after update to VS 17.8

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn#70856]
**Version Used**: `4.8.0-7.23558.1+e091728607ca0fc9efca55ccfb3e59259c6b5a0a`

**Steps to Reproduce**:

```cs
public class Class1
{
	private static void Test()
	{
		var set = new HashSet<Guid>();

		method1();

		void method2(string str, Guid id)
		{
			foreach (var c in str)
			{
			}

			// CS8602: dereference of a possibly null reference
			set.Add(id);
		}

		void method1()
		{
			method2("", default);
		}
	}
}


```

https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4CD0BmMzEgYQBsIBnTvfAbwIBIAA4AnKADcIAFwCmZbADYyFEgBVZnaQAoAlEIH5BgqaJKdZ0kgF4SMWQHcSACS4ALAMqWAPAHEArlAIAHx6NPhCgmCWbgD2CNhhtEaC6KrR0nEImNrkpFqicCQBQSRB+imGxoIAZrGishAAxm4k2qYkTWUw5tKiFdVVxgC+ydUA9OOsHgAcikSYICQIsg01q7IwTfKxNSQQJMKx3FDAbACedv5sbCRrG1uykYIW0gB0AIIICNrl4SNjVLpGLxRIDQRDKIg7LaABEsKKKxqEGu0l0/0EoyMWKxBCAA===

**Diagnostic Id**:

CS8602

**Expected Behavior**:

No errors

**Actual Behavior**:

CS8602 generated

**Comment by jjonescz** [comment]
This changed in 17.8 due to https://github.com/dotnet/roslyn/pull/70071 which just makes `foreach` consistent with other loops here - seems that `for`/`while` always behaved like this (i.e., if you replace the `foreach` in your example with `for` or `while`, you would get the same warning even before 17.8).

**Comment by jjonescz** [comment]
Btw, these workarounds make the warning go away:
- Explicitly specifying the variable type to be non-nullable, i.e., `HashSet<Guid> set = new HashSet<Guid>();`.
- Reordering local functions, i.e., moving `method1` to be defined before `method2`.
