### ISSUE TITLE
Use primary constructor (IDE0290) ignores side effects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70868]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Use-primary-constructor-IDE0290-ignore/10517305)._

---
Side effects are ignored when a refactoring is proposed for IDE0290.

```
class C
{
	public int A;
	public int B;

public C(int value)
	{
		B = ++value;
		A = ++value;
	}
}
```

The proposed refactoring breaks that code:

```
class C(int value)
{
	public int A = ++value;
	public int B = ++value;
}
```

The following refactoring _might_ be proposed instead, though it's highly subjective whether the developer would consider it better or worse than the original code:

```
class C(int value)
{
	public int B = ++value;
	public int A = ++value;
}
```

---
#### Feedback Bot on 11/16/2023, 00:14 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Interesting case!
