### ISSUE TITLE
Add machine epsilon constant

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/roslyn#7088]
Currently there is a `Double.Epsilon` constant, but it is not reliable (because it is **not** the machine epsilon) and could be equal to zero in some extreme cases (on ARM as [stated by MSDN](https://msdn.microsoft.com/en-us/library/system.double.epsilon%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=csharp)).

According to the [Wikipedia article](https://en.wikipedia.org/wiki/Machine_epsilon), machine epsilon is a number around `2 ^ (-53)` or `1.11e-16` (and `Double.Epsilon` is `4.94065645841247E-324` currently).

Machine epsilon could be usable when doing floating point comparison, and the presence of `Double.Epsilon` currently only confuses people (see some StackOverflow questions: [1](http://stackoverflow.com/questions/20222314/is-math-absx-double-epsilon-equivalent-to-math-absx-0d), [2](http://stackoverflow.com/questions/9392869/where-do-i-find-the-machine-epsilon-in-c)). It is **not** usable when comparing double number values.

I propose the new constant value `Double.MachineEpsilon` that should be determined according to the current IEEE754 rules. It could be usable for doing math and comparisons, and it will correspond to the C language `DBL_EPSILON` constant.

Additional reading: http://www.johndcook.com/blog/2010/06/08/c-math-gotchas/

**Comment by Newlifer** [comment]
I second this.

**Comment by 62mkv** [comment]
+1

**Comment by leppie** [comment]
Epsilon is useless for comparisons unless you compare on the same (order of) magnitude. For floating point comparisons you need to first need to normalise both numbers to some exponent, then compare them with the mantissa.

**Comment by ForNeVeR** [comment]
@leppie all you are saying is right for the current `Double.Epsilon`, but not for C `DBL_EPSILON` or the new machine epsilon I propose here. Guys just want some reliable epsilon value for the simple cases (to compare `0.3 - 0.2` with `0.1`, for example), and anyone could still use the old-fashioned way for specific cases.

> Epsilon is the smallest representable value that is not zero.

Should it be true for ARM also? ;)

**Comment by gafter** [comment]
This is not relevant to Roslyn. I think you should submit this request to https://github.com/dotnet/coreclr instead.

**Comment by ForNeVeR** [comment]
Okay, moved to https://github.com/dotnet/coreclr/issues/2175.
