### ISSUE TITLE
Collection expressions: align `ConversionsBase.GetCollectionExpressionTypeKind()` with conversions specification

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#70880]
Align `ConversionsBase.GetCollectionExpressionTypeKind()` with collection expressions conversions [specification](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#conversions).

In particular, verify `List<T>` and `ImmutableArray<T>` are valid target types, even though the compiler uses alternative lowering for collection expressions targeting those types.

*from discussion with @AlekseyTs*

**Comment by AlekseyTs** [comment]
I think we should follow the spec and not target any specific method of determination. Any from the conversions [specification](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#conversions) should work.

**Comment by cston** [comment]
> I think we should follow the spec and not target any specific method of determination.

Updated the issue description.
