### ISSUE TITLE
Compiler failure introduced with Microsoft.CodeAnalysis.CSharp v4.4.0

### ISSUE THREAD

**Issue by gregsdennis** [dotnet/roslyn#70894]
**Version Used**: 
Microsoft.CodeAnalysis.CSharp v4.4.0

**Steps to Reproduce**:

Repro solution: [ConsoleApp1.zip](https://github.com/dotnet/roslyn/files/13404505/ConsoleApp1.zip)

The solution provides two versions of the same program, the only difference is the version of Microsoft.CodeAnalysis.CSharp.

- ConsoleApp1 uses v4.3.1 and runs fine
- ConsoleApp2 uses v4.4.0 and fails with "Method may only be called on a Type for which Type.IsGenericParameter is true." from within the `JsonSerializer.Serialize()` call.

The exception persists in the current version of the package (v4.7.0).

**Expected Behavior**:

The code should succeed without issue.

**Actual Behavior**:

An exception is thrown.

**Comment by gregsdennis** [comment]
Copying @eiriktsarpalis for serializer visibility.

**Comment by huoyaoyuan** [comment]
Can you check if `assembly!.DefinedTypes.First()` is the correct type you want? Do you incorrectly get some compiler synthesized type?

**Comment by gregsdennis** [comment]
Outputting all types just after the assembly null check gives:

```
ConsoleApp1.MyObject
```

for 4.3.1, and

```
Microsoft.CodeAnalysis.EmbeddedAttribute
System.Runtime.CompilerServices.RefSafetyRulesAttribute
ConsoleApp1.MyObject
```

Interesting.  At least I know how to fix my code.  I didn't expect generated types, especially if I'm not using any sourcegen.

**Comment by gregsdennis** [comment]
Well... actually, this is example code.  I'm actually building off of user-supplied code, so I don't know how to find the class I need to deserialize.

For context, this is for [JsonSchema.Net.Generation](https://www.nuget.org/packages/JsonSchema.Net.Generation), which has a playground at https://json-everything.net/json-schema (select "Generate code" option).

**Comment by huoyaoyuan** [comment]
> I'm actually building off of user-supplied code, so I don't know how to find the class I need to deserialize

Ideas:
- Check the only public type
- Use compiler semantic model to get declared elements

It also depends on your contract with user-supplied code.

**Comment by eiriktsarpalis** [comment]
> I didn't expect generated types, especially if I'm not using any sourcegen.

It is very common for the compiler to insert additional types/members in IL, for example to support delegates, iterator methods, local methods or to polyfill missing attributes required by a specific language feature. `assembly!.DefinedTypes.First()` is not a particularly reliable way to identify user-supplied types (also because there could be multiple types, or none at all). A common way to disambiguate is to require an attribute declaration.

**Comment by eiriktsarpalis** [comment]
> "Method may only be called on a Type for which Type.IsGenericParameter is true." from within the JsonSerializer.Serialize() call.

FWIW this error message shows up when running STJ v6. It is handled more gracefully in later versions, throwing NSE because an instance of `System.Type` is being fed to the serializer.

**Comment by gregsdennis** [comment]
Alright.  I think this can probably be closed.  I'm really just using this in my online playground and tests to verify that the code I generate actually works.

Thanks, all.
