### ISSUE TITLE
The default parameter value for struct and record struct is ignored when a new instance is created

### ISSUE THREAD

**Issue by nsentinel** [dotnet/roslyn#70892]
Creating a new structure value via `new()` automatically and unconditionally replaced by using `default()` without taking into account the presence or absence of a default value for the parameter

There is no warning about the issue, and the syntax itself is quite acceptable.

There is no such issue for class because there is no such transformation there.

**Version Used**: 
.NET 8 RTM SDK

**Steps to Reproduce**:
```csharp
using System;

RStruct rStruct = new();
RStructMulti rStructMulti = new(2);
S s = new();
R r = new();

Console.WriteLine($"{rStruct.A}, {rStructMulti.A}, {s.A}, {r.A}");

record struct RStruct(int A = 42);
record struct RStructMulti(int B = 4242, int A = 42);

struct S {
    public S(int a = 42) => A = a;

    public int A { get; }
}

record R(int A = 42);
```

[SharpLab Link](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTAlAygFwCcBXAY3wAJCCTyKBeCmAUwHcAKASgG4caz8AWWIAbfFCr9ywsRMYsOSHplwUAzgyZsuvDNiqaFOzJgQoAnOwAkAIgDe1IgIB0AQQC+AGgoOpQ0eJuXj5qQd4OQTbKWBiEzKQA9oQAJupOdHjp+OywlK6aACxKunGJKWm0lJmVMuI5MJQAQoVIRd65FPmMRdGYalkUqnaYFKMUCADMg/WUEC2cDAB8nZoQuiNjkxQd+XYUAObM+NwU7phnMaVJqdgzK93FQA=)

**Expected Behavior**:

`42, 42, 42, 42`

**Actual Behavior**:

`0, 42, 0, 42`

```csharp
RStruct rStruct = default(RStruct);
RStructMulti rStructMulti = new RStructMulti(2);
S s = default(S);
R r = new R(42);
```

**Comment by huoyaoyuan** [comment]
This should be expected, because parameterless constructor is always treated as defined, and will take precedence in overloading.

You can add a real parameterless constructor starting from C# 10.

**Comment by nsentinel** [comment]
I quite understand the reasons, but in my opinion that doesn't negate the issue, especially for newcomers to the language.

**Comment by CyrusNajmabadi** [comment]
@nsentinel Newcomers aren't using structs (esp. with default parameters).  Both already combine to be a very advanced scenario.

**Comment by huoyaoyuan** [comment]
I agree that it worths an analyzer to hint user for this situation. It's somehow counter-intuitive.

**Comment by nsentinel** [comment]
@CyrusNajmabadi Beginners come from different backgrounds, some come from the world of C and similar languages and structures are a natural element of the language for them.

Besides, imagine a situation when you had to change `record` to `readonly record struct` (for example, because there are too many objects and it is inefficient to process them as ref types because of object header) and in the end, assuming (I think it is natural) similar behavior of different variations of `record`, you get that the behavior has changed because the default constructor is no longer processed.

I think it would be nice to fix the situation, since default constructors for structures have been added, by making their behavior consistent with other language constructs.

**Comment by CyrusNajmabadi** [comment]
You're already describing an advanced scenario. 

And yes. If you convert a class to a struct you will need to understand structs.

**Comment by nsentinel** [comment]
I'm very sad to hear that structures in C# are perceived as something second-rate (or what you call "advanced use case"), although it's absolutely not true. And all attempts to get something acceptable to work just stumble over such remarks. This was the case in .NET Framework, in .NET Core in .NET Core the situation has improved, but it still comes with a lot of difficulties..

I understand that everything can be written off to advanced usage scenarios, or say that C# is not suitable for such things and you should choose other languages or tools, but what prevents you from improving the language/compiler and bringing it in line with expectations? At least normalize the behavior of the constructor for structures.

/Offtopic: Yes, I know what you're writing about and how structures work, because I've been struggling with limitations of structs since the first versions of .NET (since 2000s), that's why I've seen the changes in the language with support and what behavior is caused, but it doesn't mean that it should be left as it is.

**Comment by CyrusNajmabadi** [comment]
> I'm very sad to hear that structures in C# are perceived as something second-rate

They are not second rate. They are different from classes with intentionally different semantics. 

Switching between them requires understanding those differences.

**Comment by CyrusNajmabadi** [comment]
>  but what prevents you from improving the language/compiler and bringing it in line with expectations? At least normalize the behavior of the constructor for structures.

I think you're misunderstanding my position. Imo the way structures work here is good and should not be changed. It's working how I think it *should* work.

**Comment by nsentinel** [comment]
> It's working how I think it should work.

In other words, not calling the normal version of the constructor for record struct is a nuance that was intended that way, and anyone who encounters the need to call it will have to ignore the valid syntax and memorize it as an unused feature of the language. 

Sounds extremely strange to me.

**Comment by CyrusNajmabadi** [comment]
The opposite. The default constructor has always been special/default for structs since 1.0. 

It's deeply baked into what a struct should be considered to be, and how structures differ from classes. 

> will have to ignore the valid syntax

Both are valid interpretations. Just one is 25 years old, and tied to the core essence of structs. The other is not. 

I'd much rather structs be strange in the way you call out, than have then deviate from how they've worked since the beginning.

**Comment by nsentinel** [comment]
Yes, that's what frustrates me about the current situation for all these 25 years.

**Comment by CyrusNajmabadi** [comment]
@nsentinel Thanks for the feedback!  If you'd like a lang change here, i'd recommend starting a discussion over at dotnet/csharplang.  Thanks :)

**Comment by nsentinel** [comment]
@CyrusNajmabadi I'd like a warning from the compiler for such situations, so as not to be misled by potential workability.

**Comment by CyrusNajmabadi** [comment]
@nsentinel Custom Warnings/Errors that are wanted for legal code are exactly what analyzers were designed for.  If you would prefer this not be legal for your codebases, that's def a completely viable/supported/recommended thing to do here :)

**Comment by nsentinel** [comment]
That seems to me to be a rather biased judgment. 

For example, we can look at `CS1718 Comparison made to the same variable; did you mean to compare something else?`.

The warning is given for quite valid code, so why do we need it?

Or `CS0649 Field 'field' is never assigned to, and will always have its default value 'value'`

And many others generated for quite valid code if you approach it from the viewpoint of specification compliance.

I think the developers proceeded from the desire to warn about possible incorrect usage. There are many such warnings and they allow you to use the language more comfortably and correctly.

**Comment by CyrusNajmabadi** [comment]
@nsentinel We now have analyzers, which we didn't have when we started.  We added them precisely because we didn't want to have to always be in the position of deciding which warnings to provide.  

> I think the developers proceeded from the desire to warn about possible incorrect usage. 

Sure.  And we now have analyzers for that.  That's literally *why* we built this system.  Exactly so developers like you can satisfy this desire.

> they allow you to use the language more comfortably and correctly.

Analyzers have now taken the place of this.  With the number of analyzer warnings vastly exceeding hte number of legacy warnings by several orders of magnitude.

**Comment by CyrusNajmabadi** [comment]
If i could go back, all the existing warnings would be done with analyzers.  But we didn't have that back then.  So we're in the split world.  But analyzers are *the* way to do this now.  Thanks! :)

**Comment by nsentinel** [comment]
I don't mind analyzers at all. After all, it doesn't matter to me through which of the infrastructure components I get the corresponding warning. 

But based on the discussion, I understand that you do not find such behavior a problem in principle, transferring it to the category of my personal displeasure. If I understand correctly, instead of adding a warning as part of the existing methods of validation, you suggest that I implement the check for myself, since nobody needs it in general, since everything works properly as it is.

**Comment by CyrusNajmabadi** [comment]
> I don't mind analyzers at all. After all, it doesn't matter to me through which of the infrastructure components I get the corresponding warning.

Terrific :-)

> But based on the discussion, I understand that you do not find such behavior a problem in principle

Correct.  The way structs work here is very much something I think needs to be the case. 

Thanks!

**Comment by nsentinel** [comment]
It's a regret, but unfortunately I'm not surprised - over the past years in working with C# I've already understood the general approach.

I can only wish you good luck with further development of the compiler!
