### ISSUE TITLE
"Move static members" prepends the current namespace twice after the textbox is edited

### ISSUE THREAD

**Issue by xparadoxical** [dotnet/roslyn#70895]
**Version Used**: 
VisualStudio.17.Release/17.8.0+34309.116
C# Tools   4.8.0-7.23558.1+e091728607ca0fc9efca55ccfb3e59259c6b5a0a
**Steps to Reproduce**:

1. Use "Move static members to another type"
2. Edit the Type Name textbox

**Expected Behavior**:
The type name doesn't contain the namespace twice.

**Actual Behavior**:
"New Type Name" has the namespace prepended twice.

The actual target seems to not contain the duplicated namespace and so this doesn't affect what the fixer does, e.g. `NS.NS.T` is displayed but `NS.T` is correctly selected (and created if needed).

https://github.com/dotnet/roslyn/assets/43796685/63d3df00-9427-4fda-9b38-2d1c56af0930

**Comment by arunchndr** [comment]
This may have been fixed recently. Shen to validate and close.
