### ISSUE TITLE
Proposal: implicitly implement interfaces on abstract classes

### ISSUE THREAD

**Issue by mwisnicki** [dotnet/roslyn#709]
At the moment all methods of implemented interfaces have to be defined by programmer.
I would prefer for this to work like in Java, where all unimplemented interface methods on abstract classes become abstract too.

Please either lift this restriction or introduce additional keyword, for example `implicit`, before interface name to enable implicit abstract implementation.

So, for example, this should be possible:

```
abstract class ListBase : implicit IList {}
```

**Comment by coldacid** [comment]
I don't think this should require a new keyword. My own experience with writing abstract classes implementing interfaces is that they only implement one or two interface members and leave the rest to derived classes; having to add another half-dozen abstract declarations of other interface members in this scenario is pointless make-work enforced by the compiler when it should be smart enough to recognize what's going on. Implicit interface implementation on abstract classes should be automatic.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.

**Comment by mwisnicki** [comment]
Moved to https://github.com/dotnet/csharplang/issues/360.
