### ISSUE TITLE
IDE0028 analyzer and code fixer produce not compilable code

### ISSUE THREAD

**Issue by Balkoth** [dotnet/roslyn#70904]
**Version Used**: 
Visual Studio 17.8.0

**Steps to Reproduce**:

```cs
string? exportFilenameItemOne = null;
string? exportFilenameItemTwo = null;

List<string> exportFilenames = new List<string>();
if (exportFilenameItemOne != null) { exportFilenames.Add(exportFilenameItemOne); }
if (exportFilenameItemTwo != null) { exportFilenames.Add(exportFilenameItemTwo); }
```

![image](https://github.com/dotnet/roslyn/assets/80055480/fe408036-d519-422a-b523-5dabfcc1c222)

![image](https://github.com/dotnet/roslyn/assets/80055480/633c64d2-9146-42d1-8219-7b9ba7b548be)

**Diagnostic Id**:

IDE0028

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70173
