### ISSUE TITLE
"Encapsulate fields" refactoring should consider personal code style

### ISSUE THREAD

**Issue by ischas** [dotnet/roslyn#7090]
If I have this code:

```csharp
public class Test
{
    protected readonly bool IsATest;
}
```

the refactoring generates the following code.

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return isATest;
        }
    }
}
```

Since I have checked "Qualify member access with 'this'" I expect to get following refactoring:

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return this.isATest;
        }
    }
}
```

Notice the added `this.`.

![image](https://cloud.githubusercontent.com/assets/8558126/11429724/75333598-947c-11e5-938e-ed170971450b.png)

Thanks to @sharwell for referring to the right project in DotNetAnalyzers/StyleCopAnalyzers#1833

**Comment by Pilchie** [comment]
Note that the right fix here is probably to `Expand()` the generated statement here.

**Comment by Pilchie** [comment]
Closing, since #8435 was merged (though it's only in future atm).
