### ISSUE TITLE
Visual Studio suggests new C# language features despite pinning the SDK to .NET 6.0 in `global.json` file

### ISSUE THREAD

**Issue by TheBlueSky** [dotnet/roslyn#70902]
I have a project in which I pinned the SDK to .NET 6.0 in `global.json` file, as below:

```json
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```

In my `Directory.Build.props` files I have the `LangVersion` set as below:

```xml
<LangVersion>latest</LangVersion>
```

After installing .NET 8 SDK, I noticed that Visual Studio started to suggest changing my code to use the new C# language features, such as primary constructor and collection expression.

I always have the latest SDK installed as well as .NET 6.0; however, I have never noticed Visual Studio suggesting C# language features that are not part of C# 10 (Visual Studio Code, on the other hand, does that; at least I noticed this with the C# language server that is based on OmniSharp).

Is this behaviour intentional or a regression?

Note: If this is not the right place to post this issue, please let me know and I will move it to the right place.

**Comment by CyrusNajmabadi** [comment]
This behavior is intentional. By saying 'latest lang version ' you are indicating that all language features from all language versions are allowed.

**Comment by TheBlueSky** [comment]
Thanks for your answer, @CyrusNajmabadi.

I do not get it, though. C# compiler is part of the SDK, why is the SDK pinned and the compiler is not?

**Comment by CyrusNajmabadi** [comment]
This has nothing to do with the compiler. You stated explicitly which language versions you allow.  "Latest" means you allow all of them. So the analyzers are respecting that and saying "here are features in the latest versions of the language you can use". 

This is the *reason* to choose "latest" here.  If you don't like that outcome, then change the version, or remove that lang version node entirely. :-)

**Comment by TheBlueSky** [comment]
I thought that saying `latest` tells the analyzer to respect my choice of the SDK and use the latest from there 🙂

> remove that lang version node entirely. :-)

What will it default to in this case?

**Comment by CyrusNajmabadi** [comment]
Hopefully whatever version corresponds to the SDK you're using. 

> I thought that saying latest tells the analyzer to respect my choice 

It does.  It's respecting your choice of saying you want to use hte latest language version :)
