### ISSUE TITLE
Nuget for Microsoft.Net.Compilers.Toolset 4.8.0

### ISSUE THREAD

**Issue by Yozer** [dotnet/roslyn#70919]
`error CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.8.0.0' of the compiler, which is newer than the currently running version '4.7.0.0'
`

My project currently uses nuget of MicrosoftNetCompilersToolset at 4.7.0  and it fails to compile with .net 8.0 because .net 8.0 bundles 4.8.0.
Looks like nuget for 4.8.0 was never released
https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/#versions-body-tab

**Comment by hez2010** [comment]
It was released 6 hrs ago: https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/4.8.0

**Comment by netcorefan1** [comment]
This also happens with `Microsoft.CodeAnalysis.CSharp.Workspaces`:
`...references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'`.
I've been able to run my source generator only after downgrading to 4.8.0.
