### ISSUE TITLE
Execute roslynator analyze in a python script doesn't work in some case

### ISSUE THREAD

**Issue by jjadotP** [dotnet/roslyn#70915]
**Version Used**: 
Roslynator Version: 0.7.1.0
Roslynator Target Framework: .NET Core
Roslyn Version: 4.7.0.0

**Steps to Reproduce**:

1. open the folder where the sln is located with cygwin or git bash (with default configuration)
2. execute '~/.dotnet/tools/roslynator analyze'
3. The execution is blocked

**Expected Behavior**:
I wait a correct execution because that work in cmd windows and in powershell windows.
That must analyze solution.

**Actual Behavior**:
When I execute with argument -v diag, the return before blocking is
~/.dotnet/tools/roslynator analyze -v diag
Roslynator Version: 0.7.1.0
Roslynator Target Framework: .NET Core
Roslyn Version: 4.7.0.0

When I execute with argument -m, I have the same result (example : roslynator analyze -m "C:\Program Files\dotnet\sdk\6.0.415")
When I execute Powershell on git bash and after I tried to launch 'roslynator analyze' that doesn't work too
When I execute in a Powershell command open via windows or in cmd windows command that work correctly.

I'm trying to automate tasks via python scripts and I don't know on which environment it will be executed. I have the same problem if I try to run roslynator in pycharm's venv.

**Comment by JoeRobich** [comment]
I believe the correct place for this issue is the Roslynator repo https://github.com/dotnet/roslynator/issues.

**Comment by jjadotP** [comment]
Sorry!
I create an other issue on https://github.com/dotnet/roslynator/issues/1263
