### ISSUE TITLE
false positive for CS8604 when using primary constructor and passing param `ILogger<>` to base ctor

### ISSUE THREAD

**Issue by n0099** [dotnet/roslyn#70932]
### Analyzer

**Diagnostic ID**: [CS8604](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/cs8604): `Possible null reference argument for parameter 'param' in 'base ctor()'.
`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 7.0.311](https://dotnet.microsoft.com/download/dotnet/7.0)

AND

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 8.0.0 (Latest)

### Describe the bug

False positive for rule `CS8604` when using [primary constructor](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors) and passing param [`ILogger<>`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger) to constructor of base class:
https://github.com/n0099/open-tbm/blob/af3fe85e196e0ffaa0fa881e86b2c23999e0f736/c%23/crawler/src/Worker/RetryCrawlWorker.cs#L6

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Click on `Analyze`-`Run Code Analysis`-`On Solution`
2. Open window `View`-`Error List`
3. See error

### Expected behavior

Not reporting.

### Actual behavior

Reporting violation about rule `CS8604`.

## Additional context

Convert the primary constructor back to explicit constructor via Resharper will fix this.

**Comment by jaredpar** [comment]
Do you have a self contained repro for this bug? I cannot reproduce the bug in smaller samples and the linked repo is not buildable (get lots of missing type or namespace errors).

**Comment by n0099** [comment]
> get lots of missing type or namespace errors

Please run `git submodule update --remote`.

**Comment by n0099** [comment]
It's seems only reproducible in the `Built-in CA analyzers in .NET 7.0.311 SDK`:
1. remove the reference to `Microsoft.CodeAnalysis.NetAnalyzers`: https://github.com/n0099/open-tbm/blob/e77ebd3477ebb1326b6eebd327c6b12e99326f10/c%23/shared/tbm.Shared.csproj#L18
2. switch build configuration to `Debug`
3. ![image](https://github.com/dotnet/roslyn/assets/13030387/8c8f8bcd-c314-4962-af32-52cfbf5f5fc3)

**Comment by jaredpar** [comment]
> not in the latest Microsoft.CodeAnalysis.NetAnalyzers@8.0.0

CS8604 is a compiler warning, not an analyzer warning, so the version of Microsoft.Codeanalysis.NetAnalyzers won't impact this scenario.

> It's seems only reproducible in the Built-in CA analyzers in .NET 7.0.311 SDK

This feature, primary constructors, is in preview in 7.0.3xx. It doesn't hit RTM until 7.0.4xx. Can you reproduce this using a 7.0.4xx SDK?

**Comment by n0099** [comment]
> Can you reproduce this using a 7.0.4xx SDK?

I'm still using VS2022 LTSC 17.6.10 which doesn't support .NET7 SDK 7.0.404.
