### ISSUE TITLE
Can't emit source generated code files

### ISSUE THREAD

**Issue by Trubador** [dotnet/roslyn#70947]
**Version Used**:  

Source generator ISourceGenerator in class library with netstandard 2.1 and C# version 12 is used to create a simple helloworld.g.cs file.

If version < 10 is used then error:  error CS8400: Fea 
ture 'file-scoped namespace' is not available in C# 8.0. Please use language version 10.0 or greater

**Steps to Reproduce**:

dotnet build /p:EmitCompilerGeneratedFiles=true
or
 <PropertyGroup>    
<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
in "SourceGenerator.csproj".

Same issue if net 8 class library get build (compiled) that reference the SourceGenerator netstandard 2.1 class library, that still results in no files being written, but the folder does get created.

**Expected Behavior**:

Files written to "obj/debug/generated" folder.

**Actual Behavior**:

No files were written, but there were no errors in compilation with the source generator as well.
It is not possible to verify the generation worked.

**Comment by jjonescz** [comment]
This looks like something that generally works. Can you share what your source generator looks like?

**Comment by Trubador** [comment]
Here it is. This is just a test of using the source generator to create a simple c# class file. 

My next intent is to use it to automatically create test data using the bogus framework based on all the c# entity models I have that are used in EF core so I can replicate realistic test data easily and test that my SQL schema is working properly in xUnit testing and in a real database. I will also need to add the generated test data files to source control after I have had a chance to review them and correct any errors manually by editing the generated files.
Would something like this be possible in order to save manual time on writing the classes for each entity's test data that is quite similar? 

HelloWorldDataSourceCodeGenerator.cs
```c#
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerator
{
    [Generator]
    public class FakeBogusTestDataSourceCodeGenerator : ISourceGenerator
    {
        /*
        Warning: Source generators implementing ISourceGenerator have been deprecated in favor of incremental generators. This document has not been fully updated to reflect that. You should implement IIncrementalGenerator instead of ISourceGenerator.
        https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md
        */

        string filePath = "/GeneratedSourceCode/generatedSourceCode.cs";

        // write file to disk (this is not supported but test if it can be done anyway)
        // call http endpoint (this is not supported but test if it can be done anyway)
        // https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

        public void Initialize(GeneratorInitializationContext context)
        {
            // Initialization logic goes here
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Generation logic goes here
            System.Console.WriteLine("Hello, World!");
            // begin creating the source we'll inject into the users compilation

            // create hello world code file
            var sourceBuilder = new StringBuilder(@"
using System;
namespace HelloWorldGenerated
{
    public static class HelloWorld
    {
        public static void SayHello() 
        {
            Console.WriteLine(""Hello from generated code!"");
            Console.WriteLine(""The following syntax trees existed in the compilation that created this program:"");
    }
}
");
            string generatedCode = sourceBuilder.ToString();
            // using the context, add some source files to the compilation
            context.AddSource("helloworld.g.cs", SourceText.From(generatedCode, Encoding.UTF8));

            // Write the generated code to disk
            System.IO.File.WriteAllText(filePath, generatedCode, Encoding.UTF8);
        }
    }
}
``` 
SourceGenerator.csproj
```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>
      enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>
</Project>
```

**Comment by Trubador** [comment]
Here it is. This is just a test of using the source generator to create a simple c# class file. 

My next intent is to use it to automatically create test data using the bogus framework based on all the c# entity models I have that are used in EF core so I can replicate realistic test data easily and test that my SQL schema is working properly in xUnit testing and in a real database. I have more than 40 c# model entities used in EF core so this would save me quite a bit of tedious labor.
Would something like this be possible in order to save manual time on writing the classes for each entity's test data that is quite similar? 

HelloWorldDataSourceCodeGenerator.cs
```c#
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerator
{
    [Generator]
    public class FakeBogusTestDataSourceCodeGenerator : ISourceGenerator
    {
        /*
        Warning: Source generators implementing ISourceGenerator have been deprecated in favor of incremental generators. This document has not been fully updated to reflect that. You should implement IIncrementalGenerator instead of ISourceGenerator.
        https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md
        */

        string filePath = "/GeneratedSourceCode/generatedSourceCode.cs";

        // write file to disk (this is not supported but test if it can be done anyway)
        // call http endpoint (this is not supported but test if it can be done anyway)
        // https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

        public void Initialize(GeneratorInitializationContext context)
        {
            // Initialization logic goes here
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Generation logic goes here
            System.Console.WriteLine("Hello, World!");
            // begin creating the source we'll inject into the users compilation

            // create hello world code file
            var sourceBuilder = new StringBuilder(@"
using System;
namespace HelloWorldGenerated
{
    public static class HelloWorld
    {
        public static void SayHello() 
        {
            Console.WriteLine(""Hello from generated code!"");
            Console.WriteLine(""The following syntax trees existed in the compilation that created this program:"");
    }
}
");
            string generatedCode = sourceBuilder.ToString();
            // using the context, add some source files to the compilation
            context.AddSource("helloworld.g.cs", SourceText.From(generatedCode, Encoding.UTF8));

            // Write the generated code to disk
            System.IO.File.WriteAllText(filePath, generatedCode, Encoding.UTF8);
        }
    }
}
``` 
SourceGenerator.csproj
```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>
      enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>
</Project>
```

**Comment by jjonescz** [comment]
Well, you need to *use* the source generator somewhere. For example, create a class library / console app, then reference the source generator (source generators are normally meant to be distributed as NuGet packages, so locally referencing them is not straightforward) like this:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
```

Then build that consuming app and you should see the generated files.

**Comment by jaredpar** [comment]
Closing as this does not appear to be a bug in source generators.

**Comment by kmi-bluetezeit** [comment]
It turned out, the problem was a mismatch between the compiler version referenced by the `Microsoft.CodeAnalysis.CSharp` NuGet package and my locally installed compiler version. There was a warning about that during the build that I initially ignored but then it turned out that it prevents the code from being generated.

`2>CSC: Warning CS9057 : The analyzer assembly '/Users/<...>/.nuget/packages/microsoft.codeanalysis.csharp/4.11.0/lib/netstandard2.0/Microsoft.CodeAnalysis.CSharp.dll' references version '4.11.0.0' of the compiler, which is newer than the currently running version '4.10.0.0'.`
