### ISSUE TITLE
Unexpected overload resolution ambiguity while using collection expression

### ISSUE THREAD

**Issue by kindermannhubert** [dotnet/roslyn#70943]
**Version Used**: VS 17.8.1

**Steps to Reproduce**:
```C#
"a,b".Split([','], StringSplitOptions.None);
```

**Expected Behavior**:
Compiles without ambiguity. Calls overload accepting `char[]`.

**Actual Behavior**:
`
The call is ambiguous between the following methods or properties: 'string.Split(char[]?, StringSplitOptions)' and 'string.Split(string?, StringSplitOptions)'
`

I suppose the compiler thinks `string` can be created by collection expression because it's `IEnumerable<char>` but actually it can't. Is this expected?

**Comment by huoyaoyuan** [comment]
This is expected. See #70831

**Comment by kindermannhubert** [comment]
Oh, didn't find the mentioned issue before. Thanks.
