### ISSUE TITLE
Dynamic compound assignment doesn't take receiver by reference

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#70956]
**Version Used**: 2023-11-23

**Steps to Reproduce**:

```cs
interface IBase
{
    int Prop { get; set; }
}

struct Derived : IBase
{
    public int Prop { get; set; }
}

class Program
{
    static void Main()
    {
        var a = new[] { new Derived() };
        F1(a);
        System.Console.Write(a[0].Prop);
        
        a = new[] { new Derived() };
        F2(a);
        System.Console.Write(a[0].Prop);
    }

    static void F1<T>(T[] a) where T : IBase
    {
        ((dynamic)a[0]).Prop++;
    }

    static void F2<T>(T[] a) where T : IBase
    {
        a[0].Prop++;
    }
}
```

[SharpLab](https://sharplab.io/#v2:C4LgTgrgdgPgllYBTMAzAhgYyQAgJIBC6AzkgLABQA3pTnTgsDgApgD2ADjlTgOZLAA3DlJCcAX0qSKlYsEiYmAERRwAbkgAmOEPiKlKNCvRwABAMwNELdlx78xo4dOmVTAJjMBGAOyHa9KZeAGxmACw4ALLoCAAUAJQBdEYmJmroYDjoOAC8OFBIAO4A2gC63PlFOCpg6loJEoJJqQBiXrHo8U3GqXRBAHQAwmxQxGwANkj9AOq1yB3FAAyl/aycXc0mm/TZeQUl5Tz71aoamg3i3b10Le4dGz29A8OjE1OzcPPoSytrHA8mVyPbyhUwRNoAHgAKgA+WJQspZeI4QoACxQuChOj0JHIwJS11isU0AE8oOgALZwTDxb7LeKrWwAaiZV3oQJMQVB4Pc0LhCPKnRR6LAmOxhFxzQJvTpv2ZrOaLiAA)

**Expected Behavior**: Prints `11`.

**Actual Behavior**: Prints `01`.

**Notes**: I'm not 100% sure this is a bug, but it feels like `((dynamic)a[0]).Prop++;` and `a[0].Prop++;` should behave equivalently.

**Comment by svick** [comment]
As far as I can tell, cast to `dynamic` should behave like a cast to `object`, apart from using dynamic binding. In this case, that means boxing the value type, so I think the current behavior is correct.

**Comment by jjonescz** [comment]
> As far as I can tell, cast to `dynamic` should behave like a cast to `object`, apart from using dynamic binding. In this case, that means boxing the value type, so I think the current behavior is correct.

That sounds correct. Thanks. Closing this.
