### ISSUE TITLE
FAQ: How do I compile some code into a collectible type or DynamicMethod

### ISSUE THREAD

**Issue by aspcompiler** [dotnet/roslyn#7095]
The link for this question does not exist: https://github.com/dotnet/roslyn/wiki/FAQ#how-do-i-compile-some-code-into-a-collectible-type-or-dynamicmethod

**Comment by gafter** [comment]
@tmat Who would be a good person to ask to update the documentation with an answer for this?

**Comment by tmat** [comment]
@gafter The answer is that Roslyn doesn't support emitting collectible types or DynamicMethods.

**Comment by gab** [comment]
Not sure why this was closed, the link to the erased FAQ entry is still in the FAQ's table of contents at https://github.com/dotnet/roslyn/wiki/FAQ
