### ISSUE TITLE
'using unsafe' alias is missing appropriate coloring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70967]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/using-unsafe-alias-is-missing-appropri/10525626)._

---
[severity:It bothers me. A fix would be nice]
'using unsafe' alias should be colored using a configuration-defined color (propably the same as structs), but falls back to the default white color.

I'm using the latest version of Visual Studio.

![image.png](https://aka.ms/dc/image?name=B341e2f4f369b49fd80816ae95fe98203638366007718443604_20231126-140611-image.png&tid=341e2f4f369b49fd80816ae95fe98203638366007718443604)

---
#### Feedback Bot on 11/26/2023, 10:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ufcpp** [comment]
https://github.com/dotnet/roslyn/issues/67767
