### ISSUE TITLE
Integration test deadlock caused by improper use of JTF in ExtensionManagerService

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#70966]
This is a tracking issue for cases where integration tests failed due to an improper `Task.Wait()`, which was presumably fixed in this pull request:
https://devdiv.visualstudio.com/DevDiv/_git/VSExtensibility/pullrequest/505481

Once we update the integration test pipeline to public preview [TBD], these deadlocks should stop.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, it shuold be assigned a dev/milestone and we should do it.
