### ISSUE TITLE
Should this not be inferable?

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7096]
```
using System;
class p
{
    static T Baz<T>(T t) => t;
    static Func<T, T> Get<T>() => Baz;
    static void Ork<T>(Func<T, T> f)  {  }
    static void Main() 
    {
        Ork<string>(Get()); // cant resolve arg
        Ork<string>(Baz); // this is fine
    }
}
```

**Comment by HaloFour** [comment]
That would require #5429, C# doesn't infer generic type arguments based on the expected target type.  `Get` would need to accept an argument that was either of type `T` or of `Func<T>` which would be used by the compiler to infer the generic type arguments:

```cs
static Func<T, T> Get<T>(T value) => Baz;
...
Ork<string>(Get("foo"));
```

**Comment by leppie** [comment]
@HaloFour Same your linked issue. Closing.
