### ISSUE TITLE
Confusing range for nullability warning on extension method with inferred generic type (CS8620)

### ISSUE THREAD

**Issue by fowl2** [dotnet/roslyn#70976]
**Version Used**:

Microsoft Visual Studio Enterprise 2022
Version 17.7.7
VisualStudio.17.Release/17.7.7+34302.85
Microsoft .NET Framework
Version 4.8.09037

C# Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

**Steps to Reproduce**:

Consider the following ([on sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMAWAbgFgAoUqAUwHdMAZASwGdgAeAewCMArCgY2AB8ACgCUAOgBKFAA4AbAIa8KQqBFmyRxMiVQBmbDgBs2AEx0mwAKIAPYBSiN6bB5gDepTJ+z7cx1HkwpOUUKFgAVYWAACyZzZnCBTGB5MABzCmAGZhhMMMx6OwBbETcAX1JSoA)):

``` csharp
using System.Collections.Generic;

new List<object>().Replace(null);

public static class ListExtensions {
    public static void Replace<T>(this List<T> targetList, T item) {}
}
```

Notice the following warning, specifically where the squiggles are:

![Warning	CS8620	Argument of type 'List<object>' cannot be used for parameter 'targetList' of type 'List<object?>' in 'void ListExtensions.Replace<object?>(List<object?> targetList, object? item)' due to differences in the nullability of reference types](https://github.com/dotnet/roslyn/assets/12844147/256d6661-8c68-4dd9-95f8-0a5f99d96ee9)

**Diagnostic Id**: CS8620

**Expected Behavior**:

The `null` is squiggled.

**Actual Behavior**:

The `new List<object>()` is squiggled.

**Discussion**

The warning is currently *technically* correct, but most of the time the non-`this` parameter is where attention should be drawn.

I would be interested in contributing a PR to change this, but haven't looked into the implementation (good first bug? :)).

**Comment by jaredpar** [comment]
Believe the squiggle is correct in this case. In this particular case the compiler is inferring `T` to be `object?` not `object`. Hence the diagnostic is about `List<object>` not being compatible with the inferred type of `List<object?>` and hence the receiver expression is squiggled.

**Comment by fowl2** [comment]
@jaredpar but don't you see how it's confusing for a consumer of an extension method? It looks like an instance method call after all. 

I don't 100% understanding why the nullability of the type parameter of the receiver is being inferred differently based on the type of another argument. Surely the type at that point is known for sure?

**Comment by jaredpar** [comment]
> but don't you see how it's confusing for a consumer of an extension method?

I agree it's not intuitive but that can be the case with type inference, particularly when it comes to nullable reference types. These decisions are made such that the majority case has the desired behavior but there will always be corner cases where unintuitive behavior pops up.
