### ISSUE TITLE
Stale error squiggles occasionally remain in the editor

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#7097]
Very occasionally (maybe twice in two weeks of light use) I've seen some old error squiggles remain in the editor, despite the errors having being fixed. For example:

![phantom_errors](https://cloud.githubusercontent.com/assets/13181165/11454398/869ab854-9622-11e5-90b7-191900f5d757.png)

I copy 'n' pasted the nested class to a new file so, for maybe thirty seconds, there were two definitions. After deleting the original, the errors in the new file remained. Some of them are still in the correct positions, but that last one at the bottom seems to be tracking some old text. Notably, the errors were no longer visible in the error list - just the editor. Closing and re-opening the document resolved the problem.

This is happening on the Update 1 RC release and isn't something I've been able to intentionally reproduce. If there's some sort of logs/diagnostics I can get next time I see it, please let me know.

**Comment by lorcanmooney** [comment]
Hmm, maybe not as occasional as I thought. This just happened again, and closing + re-opening the document didn't fix it.

**Comment by srivatsn** [comment]
@CyrusNajmabadi you worked on a fix before Update 1 that fixed the diagnostic taggers when they were showing stale squiggles right? Is this related to that issue?

**Comment by CyrusNajmabadi** [comment]
It certainly could be.  I'd like to know if this reproes on Update1 non-RC, and if there are repro steps that can show the issue happening.  Thanks!

**Comment by lorcanmooney** [comment]
I couldn't narrow down the steps any more than my original post. It seemed to happen when copying a file via the solution explorer. Briefly, two class definitions existed with the same name, and after renaming one, the errors squiggles would remain in the other file. Even with that, it was far from 100% reproducible.

I haven't seen this since upgrading to the final Update 1 release, although I haven't had too much time to use it yet. If nobody else is seeing this, then feel free to close the issue. I'll report back if it starts happening again.

**Comment by srivatsn** [comment]
Ok. I'll close this. Please reopen if you see this happening again.
