### ISSUE TITLE
Offer 'use collection expressions' even in locations that change semantics

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#70996]
At the user's discretion, it may not be important to preserve the concrete type that is getting created in every circumstance.

```cs
class C
{
    IEnumerable<C> M(C a, C b)
    {
        return new C[] { a, b };
    }
}
```

💡 Use collection expression (may change semantics):

```cs
class C
{
    IEnumerable<C> M(C a, C b)
    {
        return [a, b];
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Interested in supporting this. But will need a way to let users know this changes semantics

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Don't we have ways to flag the certain spans that would be broken?
