### ISSUE TITLE
Tooltip suggests dynamic method is awaitable

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/roslyn#7100]
![image](https://cloud.githubusercontent.com/assets/601206/11457274/2e1625d4-96ad-11e5-94e1-4a74fbf9d462.png)

It isn't :D

**Comment by jasonwilliams200OK** [comment]
Yup https://github.com/ekonbenefits/impromptu-interface/blob/c669ccb/ImpromptuInterface/src/Impromptu.cs#L1154-L1165

**Comment by Pilchie** [comment]
Interestingly, this is actually *legal*, and will run properly as long as the dynamic actually is something that has GetAwaiter.  Nevertheless, we shouldn't advertise that you can do this in the IDE, since most of the time, the method won't return something with GetAwaiter.
