### ISSUE TITLE
Unable to use `nameof` in property: attribute in a record's primary constructor

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#71005]
**Version Used**: 4.9.0 Preview 2

**Steps to Reproduce**:

1. Have a record which uses a primary constructor with parameters

```c#
[System.AttributeUsage(System.AttributeTargets.All, AllowMultiple = true)]
public class A : System.Attribute
{
    public A(string x){}
}

record C(int someParam);
```

2. Add a param: attribute to the constructor parameter and use `nameof` to pass in the parameter name

```c#
[System.AttributeUsage(System.AttributeTargets.All, AllowMultiple = true)]
public class A : System.Attribute
{
    public A(string x){}
}

record C([param: A(nameof(someParam))] int someParam);
```

3. Change the code so that the param: attribute is a property: attribute

```c#
[System.AttributeUsage(System.AttributeTargets.All, AllowMultiple = true)]
public class A : System.Attribute
{
    public A(string x){}
}

record C([property: A(nameof(someParam))] int someParam);
```

[sharplab repro](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4G0ACBGAdAQQBdCAnKYAV0IFMBVAZwgHNqAKHA4symgFQhItC9AgBtRcAAT5xAewDuAWQqjCUAA6jqkgLyTSFagEoAugFgAUJgDMkzACZpkkHbxFS5KtUsBvS5IC7W3x2bAAGSQAPIx8AX0t4i0sSagBjWRIESQBhVgB6ACocgAsIGBZJdQEIMBdCWUqSWXVqEkIATxcCvPQqkhqXEJga6lkAM1Z6WTBqAAVqsCNTSVhCSSmZ+f7FgG4gA==)

**Expected Behavior**:

The property is generated with the specified attribute.

**Actual Behavior**:

`error CS0103: The name 'someParam' does not exist in the current context`

**Comment by JoeRobich** [comment]
CC: @RikkiGibson & @jcouv

**Comment by jcouv** [comment]
This is by-design. The spec says:
> Allow nameof(parameter) inside an attribute on a method or parameter.

But this attribute is not an the parameter, it's on the property. 
So this presently remains a scenario where one must fall back to an explicit property:
```
record C(int someParam)
{
    [property: A(nameof(someParam))]
    int someParam { get; set; } = someParam;
}
```

**Comment by jcotton42** [comment]
For those stumbling across this in the future, you can also just fully qualify the property with the typename
```diff
- record C([property: A(nameof(someParam))] int someParam);
+ record C([property: A(nameof(C.someParam))] int someParam);
```
