### ISSUE TITLE
IDE0028 and IDE0300 suggest using collection expressions inside expression trees

### ISSUE THREAD

**Issue by ChristofferGersen** [dotnet/roslyn#71012]
**Version Used**: 8.0.0

**Steps to Reproduce**:

```cs
using Moq; // From the Moq NuGet package
using System.Collections.Generic;

interface ITest
{
  bool CollectionMethod(List<string> values);
  bool ArrayMethod(byte[] values);
}

public static class Program
{
  public static void Main(string[] args)
  {
    var mock = new Mock<ITest>();
    mock.Setup(m => m.CollectionMethod(new() { "a", "b", "c" })).Returns(true); // IDE0028 suggestion
    mock.Setup(m => m.ArrayMethod(new byte[] { 1, 2, 3 })).Returns(true); // IDE0300 suggestion
  }
}
```
In this example `mock.Setup` accepts an `System.Linq.Expressions.Expression<Func<T, TResult>>`, which causes the argument to be an expression tree.

**Diagnostic Id**: IDE0028 and IDE0300

**Expected Behavior**: Do not suggest using collection expressions inside expression trees, because that results in CS9175 - An expression tree may not contain a collection expression.

**Actual Behavior**: The suggestions are given and applying the fix results in CS9175

**Comment by CyrusNajmabadi** [comment]
@jaredpar This is a bit of an interesting one.  While i def am ok with the general principle of "no new features in expression trees", does that also apply when the new feature is just a shorthand for making a new array (which would be allowed)?

Curious your thoughts on this.  If you do think it should work this way, lmk and i'll block these on hte ide side.  Thanks!

**Comment by jaredpar** [comment]
> does that also apply when the new feature is just a shorthand for making a new array (which would be allowed)?

Yes. For a while we tried to skirt the line of making features work in expression trees if it was just a simple syntax transform. But that lead to a lot of user confusion as it's not always intuitive what is / isn't a syntax transform. That also lead to increased confusion around whether we were or were not investing in expression trees anymore. Now we lean towards not letting new features appear in expression trees.

**Comment by CyrusNajmabadi** [comment]
@jaredpar sgtm.  i'll take care of this on the IDE side then.  thanks.
