### ISSUE TITLE
CodeCompletion offers non-static method via "using static Class;"

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/roslyn#7101]
![image](https://cloud.githubusercontent.com/assets/774791/11458740/4d08c410-96c6-11e5-8bde-147084bb5039.png)

Program.cs:
```csharp
using static ClassWithNonStaticMethod;
class Program
{
    static void Main(string[] args)
    {
        var instace = new Program();
        instace.NonStaticMethod();
    }

    private void NonStaticMethod()
    {
        MathMin(0, 1);
    }
}
```

ClassWithNonStaticMethod.cs:
```csharp
using System;

class ClassWithNonStaticMethod
{
    public static int MathMax(int a, int b)
    {
        return Math.Max(a, b);
    }

    public int MathMin(int a, int b)
    {
        return Math.Min(a, b);
    }
}
```

Fun fact: Bug was discovered while using Xamarin Studio :)

**Comment by dpoeschl** [comment]
Nice catch. Thanks for filing this!

**Comment by rchande** [comment]
In `NonStaticMethod`, LookupSymbols (with no qualification) is returning instance members of `ClassWithNonStaticMethod` because there's a using static for it. 

@jaredpar, is it expected that LookupSymbols returns instance members of a type with a using static?
If so, we can filter them out in the IDE, otherwise this is a compiler bug.

**Comment by jaredpar** [comment]
CC @gafter, @VSadov, @AlekseyTs 

Here is the documentation for that method:

> Gets the available named symbols in the context of the specified location and optional container. Only symbols that are accessible and visible from the given location are returned.

My instinct is to say that it should not be returned as instance methods are not accessible via a `using static`.  Will let the rest of the compiler team respond though in case I'm reading this too literally.

**Comment by AlekseyTs** [comment]
A revision of the language spec that I have says the following: "A *using-static-directive* imports the nested types and **static members** contained directly in a type declaration into the immediately enclosing compilation unit or namespace body, enabling the identifier of each member and type to be used without qualification."

Also, compiler reports 
```
error CS0103: The name 'MathMin' does not exist in the current context
```
in this scenario.

It looks to me that Semantic model behavior is inconsistent with the spec and with lookup rules used by  the binder.

**Comment by AlekseyTs** [comment]
@agocke Please verify.

**Comment by rchande** [comment]
@agocke After you verify the compiler fix, can you assign to me? I'd like to add an IDE unit test for this.
