### ISSUE TITLE
[API Proposal]: Add `GetDeclaredSymbol` overload for `LocalFunctionStatementSyntax`

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/roslyn#71028]
## Background and Motivation

For the sake of completeness, an extension method on `SemanticModel` should exist for `LocalFunctionStatementSyntax`. Note that such an overload already exists on the `CSharpSemanticModel`.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.CSharp
{
     public static class CSharpExtensions
     {
+        public static IMethodSymbol? GetDeclaredSymbol(this SemanticModel? semanticModel, LocalFunctionStatementSyntax node, CancellationToken cancellationToken = default(CancellationToken));
     }
```

## Usage Examples

``` C#
using Microsoft.CodeAnalysis.CSharp;

void M(SemanticModel m, LocalFunctionStatementSyntax s)
{
    IMethodSymbol symbol = m.GetDeclaredSymbol(s);
}
```

Related to dotnet/roslyn-analyzers#7061

**Comment by CyrusNajmabadi** [comment]
Should likely be typed to return an IMethodSymbol

**Comment by CyrusNajmabadi** [comment]
@CollinAlpert tweak here: https://github.com/dotnet/roslyn/pull/71034

**Comment by CollinAlpert** [comment]
Cool! I've tweaked the proposal.

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks.  I'll drive this!

**Comment by 333fred** [comment]
### API Review

* Ship it.

**Conclusion**: Approved.
