### ISSUE TITLE
IDE Refactoring for IDE0032 (Use auto property) produces unhelpful/invalid fix

### ISSUE THREAD

**Issue by spydacarnage** [dotnet/roslyn#71032]
**Version Used**: 8.0

**Steps to Reproduce**:

The following code suggests an `IDE0032: Use auto property` message:
```cs
private string _action;
public required string Action
{
    get => _action;
    init => _action = value;
}
```

However, due to wanting to set the value of `_action` elsewhere in a private method, when accepting the auto-fix, it produces the following illegal code which gives an `CS1007: Property accessor already defined` error:
```cs
public required string Action { get; init; private set; }
```

**Expected Behavior**:
The analyzer would identify that this pattern cannot be fixed with an auto-property.
Alternatively, it could be modified to allow the `init; private set;` for this purpose.

**Comment by CyrusNajmabadi** [comment]
I'm not sure what is meant by 'version used: 8.0'.  When i try this locally i get:

![image](https://github.com/dotnet/roslyn/assets/4564579/b03387b2-9d3c-4b28-a860-55821ce6980b)
