### ISSUE TITLE
Enable using collection expressions for IEnumerable<T> on .NET Framework 3.5

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#71033]
Would a community PR be accepted which dropped the `System.Collections.Generic.IReadOnlyCollection<T>` and `IReadOnlyList<T>` interface implementations from the synthesized collection types if these two interfaces were not found?

The motivation for the community PR is for collection expressions targeting `IEnumerable<T>` to just work on .NET Framework 3.5, which is in support till 2029 (though C# 12 is not officially supported). Currently, this is the experience:

> ❌ CS0518 Predefined type 'System.Collections.Generic.IReadOnlyCollection`1' is not defined or imported

The resulting synthesized types would continue to suit all their purposes even when `IReadOnlyList<T>` does not exist.

## Example

Using `<TargetFramework>net3.5</TargetFramework>`:

```cs
class C
{
    void M()
    {
        M2(["1"]);
    }

    void M2(IEnumerable<string> items) { }
}
```

## Alternatives

Keep the current experience. The workaround will be to declare these system interfaces as internal in each project.

## Downsides

The change does not seem complicated to maintain, but it is additional tests and some inserted conditions to skip interface implementations rather than bailing out entirely.

A spec change may also be needed to speak to the situation where these interfaces do not exist. I'll do a spec PR along with this if so.

**Comment by CyrusNajmabadi** [comment]
I think this would be worthwhile to do.  It should be very simple right?  Just making this interface optional when emitting IEnumerable support.

**Comment by CyrusNajmabadi** [comment]
I'm tentatively ok with stating we could take a community PR here.  But let me know what you think @cston @RikkiGibson @333fred .

**Comment by 333fred** [comment]
I don't particularly want to support such a scenario. @jaredpar for other thoughts.

**Comment by CyrusNajmabadi** [comment]
@333fred would it supporting?  Or would it more be like: we're not actively blocking :)  I view it more like the latter.

**Comment by RikkiGibson** [comment]
If 3.5 projects really want to consume collection-exprs, can't they use some definition of those interfaces from elsewhere? It's not required to be in the core library?

**Comment by jaredpar** [comment]
Closing as new features are not supported on older frameworks.

**Comment by jnm2** [comment]
@RikkiGibson Yes, that's in the Workarounds section. My hope was that the Roslyn PR would be tiny enough over thing time to be worthwhile even so.
