### ISSUE TITLE
Better code

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn#7103]
Currently when we are programming we spend a lot of time on design of classes, methods etc. but less on making this process easier. Here is example of a problem and a solution on how we could make a compiler better to make this easier.

General task everyone meets in pretty much every problem (this shouldn't be limited to this problem only):
Create a collection with values of type T

Current solution:
Spend time on finding best collection. Change design. Spend time on changing the code and finding better collection. Use it for a while, scale a little more, find perf issues. Figure out you could do it better with some other collection when you use method SomeRandomMethodName after adding values to a collection. Change code again... This just goes forever in some projects

When working with one collection then: no problem
When working with fifty collections: waste of time.

This seems like this can be automated...

Problem:
Which collection should I use?

How to solve:
Class have information from programmer on what operations will be done on the collection and how frequently (note: this can be auto-detected during compilation time in many cases).

I.e. when user says (or is auto-detected by some smart algorithm from the code):
- I will use Add
- I will use Search randomly after adding elements

at this point we should be considering only one option:
- use List, add values, sort, binary search when searching

At runtime:
- program figures out that it already uses 100M entries and memory starts to be an issue. It should ask you: Do you want to use Database instead? Click yes and your code is using Databases.

There is many options to automate writing code we should explore one of the options and propose something more advanced than all the same for years. Classes, wrappers, interfaces... they get boring and they are slow when people don't use them properly - we should make it better for people who write libraries and allow them to share how to use their stuff the right way.

**Comment by dsaf** [comment]
Sounds like an analyzer a profiler vendor could ship.

**Comment by MgSam** [comment]
If the compiler were smart enough to do all this I think we'd all be out of a job.

**Comment by krwq** [comment]
Or we would all work on the compiler :)

**Comment by exyi** [comment]
I also think that a lot of complex optimizations could be done on .NET code, but maybe it's not a work for a C# compiler but a "IL to IL" optimizer.

@dsaf Analyzer can be good in some cases (choosing a good collection), on the other hand automatic optimization can score a lot in cases where fast code is not nice and maintainable. And it can't be done wrong.
like:
```C#
var trimedargs = args.Select(s => s.Trim()).ToArray();
```
to
```C#
for(int i = 0; i < args.Length; i++) args = s.Trim(); // assign to args since args are never used any more
```

**Comment by CyrusNajmabadi** [comment]
Feels like this is the space of Prose/Pythia in terms of analzying code and providing suggestions based on patterns there.  Closing out as external.
