### ISSUE TITLE
Intellisense cannot determine type when inside a Tuple of Predicates

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71041]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-cannot-determine-type-when-/10529061)._

---
\[severity:It bothers me. A fix would be nice\]  
So I have this piece of code, which shows my problem in simplified format:

```  
namespace TheConsoleApp;
internal class Program
{
    static void Main()
    {
        var Ent1 = new Entity(Guid.NewGuid(), "5qwer");
        var Ent2 = new Entity(Guid.Empty, "5rewq");
        var Ent3 = new Entity(Guid.NewGuid(), "qwer");
        Entity[] ents = [Ent1, Ent2, Ent3];
        foreach (var ent in ents)
        {
            var entErrs = Verifiers.Select(verifier =>
            {
                if (verifier.TestCondition(ent) && verifier.TestRule(new Rule(ent)))
                    return verifier.Error;
                return null;
            }).Where(err => err is not null);
            
            if (entErrs.Any())
            {
                Console.WriteLine($"Entity named {ent.Name} has following errors:");
                foreach (var err in entErrs)
                {
                    Console.WriteLine($"\t{err}");
                }
            }
        }
        Console.ReadLine();
    }

    private static readonly List<(Predicate<Entity> TestCondition,
        Predicate<Rule> TestRule, 
        string? Error)> Verifiers = new()
        {
            (entity => entity.Id != Guid.Empty,
            rule => rule.Entity.Name.StartsWith('5'),
            "Entity name should not start with 5")
        };
}

internal sealed class Entity
{
    public Entity(Guid id, string name)
    {
        Id = id;
        Name = name;
    }
    public Guid Id { get; set; }
    public string Name { get; set; }
}

internal sealed record Rule(Entity Entity);
  
```

And, as you can see, Intellisense is absolutely OK with what is going on inside this list of tuples of predicates:  
![image.png](https://aka.ms/dc/image?name=B6b46a05d4a404744bbb3aa4ceeeff1d0638368688481924673_20231129-163406-image.png&tid=6b46a05d4a404744bbb3aa4ceeeff1d0638368688481924673)

It has no problems determining what is the “entity” and “rule” in these lambdas.  
But as soon as I start adding new items to the list (or edit existing ones), Intellisense just stops trying to understand what’s happening, until that item is finished:  
![image.png](https://aka.ms/dc/image?name=Ba1f702f730b4475685222ef6c1ac9cfe638368691649755542_20231129-163923-image.png&tid=a1f702f730b4475685222ef6c1ac9cfe638368691649755542)

Here, Intellisense has no idea what “entity” is and what “rule” is, until I finish my sentence:  
![image.png](https://aka.ms/dc/image?name=Bb4ff7240253a48bf9b9014e1740976fd638368693625309107_20231129-164241-image.png&tid=b4ff7240253a48bf9b9014e1740976fd638368693625309107)

Of course, I gave it some time to think, but the result was not changed.  
So it IS works correctly, but not all the time, and I had similar scenario, where the “rule” field would be big and would use LINQ stuff, and while it was totally possible to work with with these without the type hints, it was not really handy.  
I also tried this exact scenario in other IDE, which has some kind of analog of Intellisense, and it worked flawlessly, so in my mind it’s totally not impossible to solve (maybe?).

My IDE version: Visual Studio Community 2022  17.8.2
Test project target framework: .NET8, but also can be reproduced on .NET7

---
#### Feedback Bot on 11/29/2023, 06:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro any problems here.  And images are broken so it's not 100% clear what hte user is referring to.  closing out as we haven't gotten other feedback on this.
