### ISSUE TITLE
Make code action's nested actions publicly accessible

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#71050]
## Background and Motivation

Currently, it's possible to group code actions which is great but it's not possible to access them from parent code action.

## Proposed API

Change accessibility of property `CodeAction.NestedCodeAction` from `internal` to `public`:

```diff
public abstract class CodeAction
{
-    internal virtual ImmutableArray<CodeAction> NestedCodeActions => ImmutableArray<CodeAction>.Empty;
+    public virtual ImmutableArray<CodeAction> NestedCodeActions => ImmutableArray<CodeAction>.Empty;
}
```

## Usage Examples

I need to unit test code fixes and refactorings which may be registered as nested code actions.

```cs
CodeAction? action = null;

var context = new CodeRefactoringContext(
    document,
    span,
    a =>
    {
        // 'a' may be code action with nested actions
        // it's necessary to loop through all nested actions

        if (data.EquivalenceKey is null
            || string.Equals(a.EquivalenceKey, data.EquivalenceKey, StringComparison.Ordinal))
        {
            action = a;
        }
    },
    cancellationToken);

await refactoringProvider.ComputeRefactoringsAsync(context);
```

## Workaround

It's possible to use reflection to access nested code action.

```cs
public static ImmutableArray<CodeAction> GetNestedActions(this CodeAction codeAction)
{
    Type type = codeAction.GetType();
    if (type.Name == "CodeActionWithNestedActions")
    {
        PropertyInfo propertyInfo = type.GetProperty("NestedCodeActions", BindingFlags.NonPublic | BindingFlags.Instance);
        return (ImmutableArray<CodeAction>)propertyInfo.GetValue(codeAction);
    }

    return ImmutableArray<CodeAction>.Empty;
}
```

Or is there any other way how to access nested code actions from parent code action?

**Comment by CyrusNajmabadi** [comment]
hey @josefpihrt i'll run point on this.  I would not make CodeActionWithNestedCodeActions , but i would make this internal property to be public:

```c#
internal virtual ImmutableArray<CodeAction> NestedCodeActions
```

I would also point out in teh proposal that we already expose this factory method to *create* teh code action:

```c#
public static CodeAction Create(string title, ImmutableArray<CodeAction> nestedActions, bool isInlinable, CodeActionPriority priority = CodeActionPriority.Default)
```

So it is simply weird that you can create the code action with nested actions, but then can't get to them

**Comment by josefpihrt** [comment]
Thanks for fast answer @CyrusNajmabadi 

I'd be perfectly fine with making property `NestedCodeActions` public.

**Comment by CyrusNajmabadi** [comment]
@josefpihrt Great.  Once you update the proposal lmk and i'll put it on the docket.
