### ISSUE TITLE
Adding existing xaml files to the project

### ISSUE THREAD

**Issue by belmasnaoui** [dotnet/roslyn#7106]
to add a xaml-file to the project  I use AddDocument-methode of the object "Project". 
 project.AddDocument("Myfile.xaml", "test", new[] { folder }, xamlPath);
the Document get added but the extension changes to .cs instead of .xaml

**Comment by Pilchie** [comment]
Hey Matt, we don't expect AddDocument to work for an existing file that isn't a C# or VB file, but it seems odd that it's *changing* the extension.

**Comment by mattwar** [comment]
The Project.AddDocument API is not changing the name.. but the host is when the changes are applied back to the workspace.  

The expected use of AddDocument is to not specify an extension. The host is supposed to add it. Both VS and MSBuild workspaces change the extension to the expected extension when new documents are added.  The VS workspace will also completely change your document name if it collides with an existing document of the same name.
