### ISSUE TITLE
Features currently not available - the issue still exists in Version 17.7.6 of Visual Studio Professional 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71076]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Features-currently-not-available---the-i/10530354)._

---
Starting Visual Studio the first time after a reboot presents multiple error bars of features currently not available. I know, this issue is claimed to be fixed month ago already, but obviously that isn't true, as I still experience it.
The Stack-Traces for all errors are the same and look like this (which is exactly what has been shown in claimed to be fixed issue before):
>StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete. ---> System.OperationCanceledException : The operation was canceled.
>   at System.Threading.CancellationToken.ThrowOperationCanceledException()
>   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(<Unknown Parameters>)
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at async StreamJsonRpc.JsonRpc.SendAsync(<Unknown Parameters>)
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
>   --- End of inner exception stack trace ---
>   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService](<Unknown Parameters>)

The same issue happens when starting Visual Studio 2019, too.

---
#### Feedback Bot on 11/30/2023, 06:25 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 11/30/2023, 07:03 PM: 

(private comment, text removed)
#### Axel Schloß on 12/1/2023, 04:22 AM: 

(private comment, text removed)
#### Feedback Bot on 12/3/2023, 11:49 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 12/4/2023, 05:58 AM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2023, 05:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out due to age and large rewrites here.
