### ISSUE TITLE
Unable to jump to the implementation of a source generated fille

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-jump-to-the-implementation-of-/10531890)._

---
\[severity:It bothers me. A fix would be nice\] \[regression\] \[worked-in:current 17.8.2\]  
I am using a source generator library, called Riok.Mapperly. Until now I was able to right click on a partial method, then go to its Implementation (Go To Implementation: Ctrl + F12). This was possible a few updates back.

The file is generated, as I can manually navigate to it.

Demo:

Right click on the method -> Go To Implementation (Ctrl + F12)

![image.png](https://aka.ms/dc/image?name=Bbb05f0c114eb4af3b7fdf5454eec9d32638370524903579432_20231201-203449-image.png&tid=bb05f0c114eb4af3b7fdf5454eec9d32638370524903579432)

The generated code should be visible, but the file is empty

![image.png](https://aka.ms/dc/image?name=B019e0567cac04dd2b079d32e2542d507638370526407577083_20231201-203720-image.png&tid=019e0567cac04dd2b079d32e2542d507638370526407577083)

After manually navigating to its location and opening the file:  
![image.png](https://aka.ms/dc/image?name=Bcd27d43c64ab48699b8e4e5f5029a4f5638370527195225031_20231201-203838-image.png&tid=cd27d43c64ab48699b8e4e5f5029a4f5638370527195225031)

![image.png](https://aka.ms/dc/image?name=B96778261517248b68980e2a0fdb86a3d638370527802455691_20231201-203940-image.png&tid=96778261517248b68980e2a0fdb86a3d638370527802455691)

I am sure this worked fine before. I suspect this is a bug or did something change?

---
#### Feedback Bot on 12/3/2023, 06:25 PM: 

(private comment, text removed)
#### Feedback Bot on 12/4/2023, 05:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
It looks like ths user is not using roslyn:

![image](https://github.com/dotnet/roslyn/assets/4564579/69003666-501e-4164-bfa6-a3e4cdb94675)

Closing out as external.

**Comment by felichsm** [comment]
Discussed this issue with the Mapperly team. 
Seems to be a bug with ReSharper
see also https://github.com/riok/mapperly/issues/978
