### ISSUE TITLE
Upgrade to .NET 9 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/roslyn#71084]
This repo should be targeting the .NET 9 SDK from the global.json file. This is a requirement necessary for .NET source build in order to target the `net9.0` TFM. If necessary, this change can be made after the first public preview release.

Related to https://github.com/dotnet/source-build/issues/3770

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/roslyn/pull/73408.
