### ISSUE TITLE
ExtractMethod and VerifyTextSync failing on latest scouting queue updated to 17.9 P1

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#71088]
Pipeline - https://dev.azure.com/dnceng-public/public/_build?definitionId=98

Failing tests:
Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicExtractMethod.ExtractViaCodeAction
Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpExtractMethod.ExtractViaCodeAction
Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpRename.VerifyTextSync

**Comment by arkalyanms** [comment]
@beccamc for extract method and @Cosifne for the rename.

**Comment by Youssef1313** [comment]
I have hit a rename bug in 17.9 P1 (I don't have repro steps though - but it was during a recording https://www.youtube.com/watch?v=ND8dDO6oJ4U at 30:00). Not sure if it's related to the test failure.

**Comment by Cosifne** [comment]
> I have hit a rename bug in 17.9 P1 (I don't have repro steps though - but it was during a recording https://www.youtube.com/watch?v=ND8dDO6oJ4U at 30:00). Not sure if it's related to the test failure.

@Youssef1313 , this might not be the case for you. This failure happens because of an internal feature.
If you see any rename bug in the public preview, please create an issue and tag me. I am happy to help.
