### ISSUE TITLE
Rich copy/paste of C# source code into Office fails in the latest Visual Studio preview

### ISSUE THREAD

**Issue by olegtk** [dotnet/roslyn#71099]
**Version Used**:  17.9 Preview1

From https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1919440:

After updating Visual Studio to the latest, the rich copy/paste of source code (with nice colors) into office(word/powerpoint) has stopped working.

The Copy rich text on copy/cut is checked and I am copying a small class/text snippet.

It works fine in Visual Studio “non-preview” version.

**Comment by allisonchou** [comment]
@akhera99 this issue can be closed. The fix is scheduled for 17.11 Preview 1, can you help update the milestone?
