### ISSUE TITLE
Bring Roslyn error log format up to date with SARIF 0.4

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#7110]
This is ready to go. The 0.4 changes are done.

**Comment by nguerrera** [comment]
@lgolding @michaelcfanning this is ready to go now, right? I think I can make the changes based on the 0.4 schema.

**Comment by lgolding** [comment]
@nguerrera @michaelcfanning Yes, this is ready to go. 0.4 is closed.

**Comment by nguerrera** [comment]
Great.
