### ISSUE TITLE
Incorrect result of multiple compound assignment operator

### ISSUE THREAD

**Issue by jip** [dotnet/roslyn#71139]
**Version Used**: 

```console
C:\Program Files\dotnet>dotnet --version
8.0.100

C:\Program Files\dotnet>dotnet --list-sdks
8.0.100 [C:\Program Files\dotnet\sdk]

C:\Program Files\dotnet>dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Steps to Reproduce**:

The following code should swap values in a and b:

```c#
int a = 3, b = 5;
a ^= b ^= a ^= b;
Console.WriteLine($"a = {a}, b = {b}");
```
[Sharplab link](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAlgHYAu6AhugLzqoANOgBGfdAFYA3IyZEeAPX5il3dKpEykc4lDgBOagBIARD354uAX2FiLIqydpadRAPRv0AewCu7AA5+AM4gavwADLbiqLJyHuhBABa+ADbAogCmoeaSUfwx2sRWyFZAA===)

**Expected Behavior**:

`a = 5, b = 3`

**Actual Behavior**:

`a = 0, b = 3`

**Workaround**:

```c#
int a = 3, b = 5;
a ^= b;
b ^= a;
a ^= b;
Console.WriteLine($"a = {a}, b = {b}");
```

**Comment by jip** [comment]
Originally posted here: https://github.com/dotnet/csharplang/discussions/7741 .

**Comment by RikkiGibson** [comment]
Thank you for inquiring about this issue. Closing out as not planned. Feel free to follow up with any further questions or concerns.

**Comment by jip** [comment]
Thank you for clarification. One question though: does Roslyn use grammar rewriting technique to transform ```x «op»= y``` to ```x = x «op» y```?
