### ISSUE TITLE
Preselect default(T) after = in a non-primitive parameter declaration

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7113]
Split from #1647, suggestion from @slaks

**Comment by SLaks** [comment]
Actually, for reference types, `null` is also valid

**Comment by dpoeschl** [comment]
Paste C#:
```C#
class Program
{
    void M(Program p $$
}
```

Remove the ```$$``` and type ```=```

**Expected**: Completion could offer ```null``` and ```default(Program)```.
**Actual**: No completion list offered.

**Comment by Pilchie** [comment]
Note that string is special here.  It would be nice to *only* list null and default.  Unfortunately however, any type *may* have a constant value equal to null.

**Comment by alrz** [comment]
This can wait until we have `default` literal. Then it could suggest `default` for any parameter type.

**Comment by CyrusNajmabadi** [comment]
Closing out for lack of feedback.
