### ISSUE TITLE
NU1608: Detected package version outside of dependency constraint

### ISSUE THREAD

**Issue by DoomerDGR8** [dotnet/roslyn#71146]
**Version Used**:
- Visual Studio 17.9.0 Preview 1.1
- dotnet SDK 8.0.100
- Telerik ASp.Net Core 2023.3.1114

**Steps to Reproduce**:

1. Add a reference to `Microsoft.EntityFrameworkCore.Design, 8.0.0` & `Microsoft.EntityFrameworkCore.Tools, 8.0.0` in an AspCore MVC project
2. Add a reference to `Microsoft.CodeAnalysis, 4.8.0`
3. Add Telerik.UI.for.AspNet.Core, 2023.3.1114, that has a dependency internally on an older version of `Microsoft.CodeAnalysis 4.4.0` & `Microsoft.CodeAnalysis.CSharp.Workspaces (= 4.4.0)`

An error will appear preventing building:

```
Version conflict detected for Microsoft.CodeAnalysis.CSharp.Workspaces.
Install/reference Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0-3.final directly to project ProjectName to resolve this issue.

 ProjectName -> Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.0 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 4.8.0-3.final) 
 ProjectName -> Telerik.UI.for.AspNet.Core 2023.3.1114 -> Microsoft.CodeAnalysis 4.4.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (= 4.4.0).
```

I can resolve Telerik by adding a reference to `Microsoft.CodeAnalysis.CSharp.Workspaces, 4.8`. But that starts a series of errors between my web application and EntityframeworkCore. I keep following the suggestions to add direct references, and this is what I end up with:

```
<ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.8.0" />
</ItemGroup>
```

Now resulting in warnings instead of errors:

```
Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Features 4.8.0-3. final requires Microsoft.CodeAnalysis.Common (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.Common 4.8.0 was resolved.

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Features 4.8.0-3.final requires Microsoft.CodeAnalysis.CSharp (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.CSharp 4.8.0 was resolved

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Features 4.8.0-3.final requires Microsoft.CodeAnalysis.CSharp.Workspaces (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0 was resolved.

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Features 4.8.0-3.final requires Microsoft.CodeAnalysis.Workspaces.Common (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.Workspaces.Common 4.8.0 was resolved.

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Features 4.8.0-3.final requires Microsoft.CodeAnalysis.Common (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.Common 4.8.0 was resolved.

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Features 4.8.0-3.final requires Microsoft.CodeAnalysis.Workspaces.Common (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.Workspaces.Common 4.8.0 was resolved.

Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 4.8.0-3.final requires Microsoft.CodeAnalysis.Common (= 4.8.0-3.final) but version Microsoft.CodeAnalysis.Common 4.8.0 was resolved.
``` 

I am using Visual Studio 2022 Enterprise Preview Latest.

I do not have a global.json file so I'm not restricting the dotNetCore SDK.

Reference: https://www.telerik.com/forums/microsoft-codeanalysis-issues-again

**Comment by jaredpar** [comment]
Closing as this does not appear to be an issue in Roslyn. Instead it appears that another package is pinning a specific version of roslyn and complaining when a more recent one is referenced. The fix will be in the package than is trying to use the 4.8.0-3.final version.

**Comment by sharwell** [comment]
@DoomerDGR8 you should also add the following:

```
<PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.8.0" />
```

**Comment by bcanylmz** [comment]
Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Workspaces.MSBuild 4.8.0 requires Microsoft.CodeAnalysis.Common (= 4.8.0) but version Microsoft.CodeAnalysis.Common 4.11.0 was resolved.

I have the same problem.

**Comment by amirhosseinhosseinzadeh** [comment]
> [@DoomerDGR8](https://github.com/DoomerDGR8) you should also add the following:
> 
> ```
> <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.8.0" />
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.8.0" />
> <PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.8.0" />
> ```

thanks to [sharwell](https://github.com/sharwell) it got fixed !
After compiling with these 3 package i removed them and everything worked fine as well. idk but it seems roslyn need a push to figure out which version of deps are required for build.
in my case it also happened  after upgrading some packages
