### ISSUE TITLE
Wrong handling of readonly field in ref struct which holds another ref struct

### ISSUE THREAD

**Issue by cbersch** [dotnet/roslyn#71144]
**Version Used**: Microsoft (R) Visual C# Compiler Version 4.9.0-1.23560.3 (78d23490)

**Steps to Reproduce**:

1. Run the attached code

**Expected Behavior**:
Console output

    LogInterpolatedStringHandler: message 1
    BrokenLogInterpolatedStringHandler: message 2

**Actual Behavior**:

    LogInterpolatedStringHandler: message 1
    BrokenLogInterpolatedStringHandler:

When debugging, is see, that after a call e.g. to `DefaultInterpolatedStringHandler.AppendLiteral`, the `_inner.chars` field keeps its reference to the rented array, with the correct content, but `_inner._pos` is always reset to `0`, which is the reason for empty output.

The only difference between the two implementations is the `readonly` in the broken handler.

**Code**
```csharp
using System.Runtime.CompilerServices;

Log($"message {1}");
LogBroken($"message {2}");

static void Log([InterpolatedStringHandlerArgument] LogInterpolatedStringHandler handler)
    => Console.WriteLine($"{nameof(LogInterpolatedStringHandler)}: {handler.GetFormattedText()}");

static void LogBroken([InterpolatedStringHandlerArgument] BrokenLogInterpolatedStringHandler handler)
    => Console.WriteLine($"{nameof(BrokenLogInterpolatedStringHandler)}: {handler.GetFormattedText()}");

[InterpolatedStringHandler]
public ref struct LogInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _inner;

    public LogInterpolatedStringHandler(int literalLength, int formattedCount)
    {
        _inner = new DefaultInterpolatedStringHandler(literalLength, formattedCount);
    }

    public void AppendLiteral(string s) => _inner.AppendLiteral(s);

    public void AppendFormatted<T>(T t) => _inner.AppendFormatted(t);

    public string GetFormattedText() => _inner.ToStringAndClear();
}

[InterpolatedStringHandler]
public ref struct BrokenLogInterpolatedStringHandler
{
    // this 'readonly' is the only difference
    private readonly DefaultInterpolatedStringHandler _inner;

    public BrokenLogInterpolatedStringHandler(int literalLength, int formattedCount)
    {
        _inner = new DefaultInterpolatedStringHandler(literalLength, formattedCount);
    }

    public void AppendLiteral(string s) => _inner.AppendLiteral(s);

    public void AppendFormatted<T>(T t) => _inner.AppendFormatted(t);

    public string GetFormattedText() => _inner.ToStringAndClear();
}
```

**Comment by huoyaoyuan** [comment]
`DefaultInterpolatedStringHandler` should not be copied. It should never be put into `readonly` field.

Is there any interest to non-copyable structs from the language team? Some buffer-holding structs fall into this category.

**Comment by jaredpar** [comment]
Agree this behavior is "By Design". The field is marked `readonly` but when calling `AppendLiteral / AppendFormatted` neither the method or the containing type is `readonly` hence the compiler creates a defensive copy and invokes the method on that. It's a copy so the mutations are lost after the method completes.

**Comment by cbersch** [comment]
For a `struct` I agree, but here we have a `ref struct` which is saved in the `readonly` field.

**Comment by huoyaoyuan** [comment]
You may be confused with a `ref struct` field and a `ref` field.

`ref struct` is behaving like the `ref` itself, not the struct that the ref points to. There's no way to do a partial modification for `ref`, but `ref struct` can do that.

Anyway, **`DefaultInterpolatedStringHandler` should never be marked as `readonly`.**

**Comment by jaredpar** [comment]
> For a struct I agree, but here we have a ref struct which is saved in the readonly field.

In terms of defensive copies and mutations there is no distinction between a `ref struct` and `struct`. A `ref struct` is really just a `struct` that has a number of limitations around lifetime.
