### ISSUE TITLE
vbcscompiler.exe should support a /shutdown flag

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7115]
The vbcscompiler.exe should have some nice way to shut down itself down without resorting to killing all instances everywhere. I could imagine it has a /shutdown flag that either:

1. Shuts down running instances that match the invoked vbcscompiler.exe by full path, or
2. Takes a path and shuts down running instances from that path.

**Comment by jaredpar** [comment]
Note: this change needs to be cherry picked to the update 1 tree as well as master.
