### ISSUE TITLE
`ImmutableArray<object>.Empty` is not equal to `ImmutableArray<object> c = []`

### ISSUE THREAD

**Issue by gurustron** [dotnet/roslyn#71159]
### Description

More a question than a bug but:

Based on [`ImmutableArray<T>`](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.cs#L14) having `CollectionBuilderAttribute` referencing `ImmutableArray.Create`:

```
[CollectionBuilder(typeof(ImmutableArray), nameof(ImmutableArray.Create))]
public readonly partial struct ImmutableArray<T> : 
```

Which should return `ImmutableArray<T>.Empty` for empty collection:
```
public static ImmutableArray<T> Create<T>(ReadOnlySpan<T> items)
{
	if (items.IsEmpty)
	{
		return ImmutableArray<T>.Empty;
	}

	T[] array = items.ToArray();
	return new ImmutableArray<T>(array);
}
````

But `ImmutableArray<object>.Empty`  !=  `ImmutableArray<object> c = []`. Based on sharplab the latter actually is `ImmutableCollectionsMarshal.AsImmutableArray(Array.Empty<object>());` which just calls `ImmutableArray` ctor

### Reproduction Steps

```
ImmutableArray<object> a = ImmutableArray<object>.Empty;
ImmutableArray<object> b = ImmutableArray<object>.Empty;
ImmutableArray<object> c = [];
ImmutableArray<object> d = [];
        
Console.WriteLine($"a == b: {a == b}");
Console.WriteLine($"a == c: {a == c}");
Console.WriteLine($"c == d: {c == d}");
```

[sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgGEB7AG3IFMBjAFylJgGdCBJMMAVzomGoDcmXCNFjx4zB269+VAIIAnRRACeAHlLAAVrToA+XBFwBeXNJ59qSlRq276+wgFEwABzqqhGC7OvK1TR09Q2BTc05LORtA+xCXd09vXysFALtgx1wacIBtAF1kyL802yCHA1wAEzzC4QlcTAIATgAKABIAImMTM1BcAG8evoBfToBKbxaO7tMzGhBB4eyxyaaUNq6c3urFge2zKtXvIA===)

### Expected behavior

All are equal

### Actual behavior

a == b: True
a == c: False
c == d: True

### Regression?

No

### Known Workarounds

Not needed

### Configuration

.NET 8 

### Other information

From [SO question](https://stackoverflow.com/q/77622907/2501279)

**Comment by CyrusNajmabadi** [comment]
@gurustron Great question.  This is by design, in that the compielr is free to emit whatever it wants as long as you get the right target type, containing the right elements.  This could also potentially change in the future.  The particular object identity you get back is not guaranteed by the specification.

Note: @RikkiGibson we might want to consider emitting the `IA.Empty` singleton when we see that's what is in the original user code.

**Comment by RikkiGibson** [comment]
The reason the compiler works the way it currently does is simply because it saved me from having to wire up a WellKnownMember for `ImmutableArray<T>.Empty`.

I would be happy to review a change to start using `ImmutableArray<T>.Empty` here instead.

**Comment by gurustron** [comment]
@CyrusNajmabadi thank you. I was confused by `[CollectionBuilder(typeof(ImmutableArray), nameof(ImmutableArray.Create))]` which I assumed would be used by compiler but it seems that it has some other handling for build-in types (or this particular one).

@RikkiGibson I'm interested  in trying it. What would you say - is it a "good first issue"? Last time I've tried to understand Roslyn code base it looked like not for a faint of heart =)

**Comment by RikkiGibson** [comment]
I think it will be an OK first issue. However you might want to hold off on starting to work on it for a week or so, as I have some other collection-expression optimization work in progress right now which may conflict. I can ping you when that is done with.

The main things will be successfully twiddling the big byte array which holds all the WellKnownMembers, and learning to run/author tests. Feel free to take a stab at cloning the repo and browsing around in Compilers.sln.

See [Building, Debugging, and Testing on Windows.md](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md)
and [Building, Debugging, and Testing on Unix.md
](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Unix.md)

**Comment by gurustron** [comment]
Yes, sure, thank you!

**Comment by RikkiGibson** [comment]
It looks like I finished the work but the ping never arrived :) So here it is: Ping

**Comment by gurustron** [comment]
@RikkiGibson thank you for the ping! I will try to get this started in a week or two!
