### ISSUE TITLE
IDE0290 Primary Constructor refactoring generates invalid code when used with `out` parameters of static functions

### ISSUE THREAD

**Issue by myblindy** [dotnet/roslyn#71152]
**Version Used**: .NET 8.0

**Steps to Reproduce**:

This code generates an IDE0290 warning:

```C# 
readonly struct S
{
    static public int F(out int n) => n = 0;
    public S(int _)
    {
        N1 = F(out var n);
        N2 = n;
    }

    public readonly int N1, N2;
}
```

The fix suggested is:

```C#
readonly struct S(int _)
{
    static public int F(out int n) => n = 0;

    public readonly int N1 = F(out var n), N2 = n;
}
```

Note how `N2` uses the `out` parameter calculated during `N1`'s initialization, which isn't available anymore. Through trial and error I've found that all of these have to happen for the problem to occur:
 - The `struct` has to have a parameter, even if unused
 - There has to be a function that both returns a value and sets an `out` parameter
 - Both the return value of the function and the `out` parameter have to be assigned to fields

**Diagnostic Id**:

```
IDE0290: Use Primary Constructor
```

**Expected Behavior**:

In this case, I'd expect the refactoring option to not be available at all. Without more language support (for example, allowing `out var` arguments to reside in the same space as primary constructor arguments), this can't be written in C#. 

**Actual Behavior**:

Seen as above, the warning is generated and the code fix provides invalid code.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/71155.
