### ISSUE TITLE
Collection Initializer Expression `[]` should be disallowable per type (e.g. via Attribute?)

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn#71171]
## Background and Motivation

In our Application we have a class that implements `IEnumerable<T>` and has a `Add(T)` method. However this is unnecessary for the user to know. 99% of the time the other 99% of the methods are used. Thus it seems counter intuitive to use `[]` instead of  `new()`. Even though the emitted code might be the same code, it conveys a different meaning. Our class is not "just a collection".

currently we have a pattern/design like this (simplified):
```cs
internal class MyClass
{
  public void Do()
  {
    using Context ctx = new();
//                      ^- IDE0028: Collection initialization can be simplified
    SomeEntity thing = ctx.Get(123);
    SomeEntity other = ctx.CreateNew();
    ctx.Commit();
  }
}

public sealed class Context : IEnumerable<SomeEntity>, IDisposable
{
  public void Add(SomeEntity entity) { }
  public SomeEntity Get(int key) => new();
  public SomeEntity CreateNew() => new();
  public void Commit() { }
  public IEnumerator<SomeEntity> GetEnumerator() => throw new NotImplementedException();
  IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
  public void Dispose() => throw new NotImplementedException();
}

public sealed class SomeEntity
{ 
...
}
```

## Proposed API

Since changing the implementation is out of the question due to far too many usages and possible breaking changes, it would be great to have something akin to this, from where the analyzers would infer to not pursue any optimization/analysis for this type.
```diff
+[NoCollectionInitializer]
public sealed class Context : IEnumerable<SomeEntity>, IDisposable
{
...
}
```

Further extending on that, there might be a Parameter on the attribute that could change the agressiveness. For Example:
`NoCollectionInitializer(Aggressive=false)` (default?) would only stop the analyzers from generating suggestions. `NoCollectionInitializer(Aggressive=true)` could make the compiler emit a warning or error, because collection initialization is strictly not allowed.

## Usage Examples
the function `MyClass.Do()`would not contain any Diagnostics after applying the Attribut to `Context`

## Alternative Designs

(don't now)

## Risks

(don't know)

**Comment by CyrusNajmabadi** [comment]
> Our class is not "just a collection".

Since collection initializers were added (almost 20 years ago), your class would have been considered a collection. 

`new() { x, y, z }`

would be legal for it.

> would only stop the analyzers from generating suggestions. NoCollectionInitializer(Aggressive=true) could make the compiler emit a warning or error, because collection initialization is strictly not allowed.

You can already do this today. DiagnosticSupressors will suppress the diagnostics from other analyzers.  And you can always add your own analyzers to make this an error. 

Cheers!
