### ISSUE TITLE
Investigate why we have "option strict on" above the copyright banner in some VB files.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#7117]
For example: ExtractMethod/ExtractMethodTests.vb
It seems possible that our code action to add "option strict" might be placing the item above the copyright header.

**Comment by Pilchie** [comment]
Yes, this repros. In fact, the code fix is named "Move to line 1" :smile:

``` VB
' Copyright

Imports System
Imports System.Collections.Generic
Imports System.Linq

Option Strict On

Module Program
    Sub Main(args As String())
        
    End Sub
End Module
```
