### ISSUE TITLE
C#: compile error when casting a constant with non-predefined typenames in unchecked expression

### ISSUE THREAD

**Issue by takeshik** [dotnet/roslyn#7118]
Repro code:

```csharp
using System;

class Program
{
    static void Main()
    {
        var a1 = unchecked((byte)1);
        var a2 = unchecked((byte)-1);
        var b1 = unchecked((Byte)1);
        var b2 = unchecked((Byte) - 1); // this line was formatted like this
        //                  ^^^^
        // CS0119: 'byte' is a type, which is not valid in the given context
        var b3 = unchecked((Byte)(-1));
     }
}
```

In this code, variable `b2` should be 255, but _only_ this definition causes compilation error CS0119.

In contrast to the `b2`,

* the definition `a2`: use predefined typename, not a identifier
* the definition `b1`: the operand `1` is in the value range of `byte` type
* the definition `b3`: only parenthesize the operand `-1`

they cause no error. So I think this error is not due to violation of the language specification. It might be a bug of the compiler.

* C# Compiler Version: 1.0.0.50618, bundled in the Visual Studio 2015 RTM.

**Comment by svick** [comment]
I agree that this is confusing, but as far as I can tell, it follows the specification. §7.7.6 Cast expressions of the C# 5 specification says:

> The grammar for a *cast-expression* leads to certain syntactic ambiguities. For example, the expression `(x)–y` could either be interpreted as a *cast-expression* (a cast of `–y` to type `x`) or as an *additive-expression* combined with a *parenthesized-expression* (which computes the value `x – y`).

> To resolve *cast-expression ambiguities*, the following rule exists: A sequence of one or more *token*s (§2.3.3) enclosed in parentheses is considered the start of a *cast-expression* only if at least one of the following are true:
* The sequence of tokens is correct grammar for a *type*, but not for an *expression*.
* The sequence of tokens is correct grammar for a *type*, and the token immediately following the closing parentheses is the token “~”, the token “!”, the token “(”, an *identifier* (§2.4.1), a *literal* (§2.4.4), or any *keyword* (§2.4.3) except `as` and `is`.

> The term “correct grammar” above means only that the sequence of tokens must conform to the particular grammatical production. It specifically does not consider the actual meaning of any constituent identifiers. For example, if `x` and `y` are identifiers, then `x.y` is correct grammar for a type, even if `x.y` doesn’t actually denote a type.

> From the disambiguation rule it follows that, if `x` and `y` are identifiers, `(x)y`, `(x)(y)`, and `(x)(-y)` are *cast-expression*s, but `(x)-y` is not, even if `x` identifies a type. However, if `x` is a keyword that identifies a predefined type (such as `int`), then all four forms are *cast-expression*s (because such a keyword could not possibly be an expression by itself).
