### ISSUE TITLE
Switch to file-scoped-namespaces in generated syntax files.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#71192]
The syntax files are enormous, but make poor use of horizontal space.  This means that when working on my laptop i often see less of the code and have to horizontally scroll more than desired to see it.  As i spend a lot of time in this file, these issues end up causing a lot of friction.

Over the years we've made many changes here to address these sorts of pain points.  Switching to file scoped namespaces would give back around 100 pixels of space, which would be about a 5% improvement in code visibility.   Given this benefit, and the zero risk cost associated with this change (the IL produced is exactly the same), i think this would be worth doing.

**Comment by CyrusNajmabadi** [comment]
@jcouv @jaredpar fyi.  For context, here's what the PR would look like to make this possible: https://github.com/dotnet/roslyn/pull/71193/files?diff=unified&w=1

Note that it ends up being 26 lines of actual changed code (excluding whitespace only line changes), but ends up substantively improving things on my end.  I'm hoping we can go through with this change.  Note that we've made numerous changes to the syntax file already for similar benefits.  So hopefully this ends up just in line with that.

**Comment by jaredpar** [comment]
Thanks for the suggestion. Will discuss with the team tomorrow after our normal stand up.

**Comment by CyrusNajmabadi** [comment]
@jaredpar Thanks!  I appreciate that :)

**Comment by jaredpar** [comment]
Compiler team discussed this today and we are okay with the proposed changes here. Thanks for filing the detailed issue here 😄

**Comment by CyrusNajmabadi** [comment]
Thansk :)
