### ISSUE TITLE
Script creation of NuGet zips for CI builds

### ISSUE THREAD

**Issue by SamB** [dotnet/roslyn#7119]
It's kind of a pain that the process of creating the NuGet zip files for use in CI is so extremely manual. (It's also kinda crazy how many bytes go into it, but that's a topic for another bug.)

Now I'm not saying that it would necessarily be wise to make it "push-button" easy to make and upload a new zip(making a new one unthinkingly is probably not the best move), but it would be nice if it at least didn't involve having to nuke `~/.nuget/packages` or temporarily rename `~/.nuget` and remember to rename it back, and if we're going to automate that much already we might as well also automate the archive creation too.

We could do a study to figure out what combination of archiver and settings seems to give a decent ban for the buck without being overly complicated to install or (if it was decided to switch away from bog-standard zip files) extract from. (I have a suspicion that the winning archiver would end up being some form of 7-zip, whether we stuck with zip files or not.)

But the script should probably not automatically name the archive <code>nuget.*i*.zip</code>, and should **certainly* not automatically upload to Azure.

It would also be nice to have some tooling for comparing the freshly-minted archive with the current archive, to see if there are any unexpected changes.

**Comment by SamB** [comment]
Note: I've found something like the following to work pretty well from (MSYS2-based) git bash:

```sh
diff -u <(zipinfo -1 nuget.35.zip|sort) <(zipinfo -1 nuget.36.zip|sort) > nuget.zip.diff
```

(`git diff --no-index` didn't like the `/dev` paths that bash turned the Process Substitution forms into.)

**Comment by ctaggart** [comment]
What is the process for creating the NuGet zip files (release or CI)? I was trying to figure out how to build all the nupkg files for the release and only made 3 of them:
``` ps
PS C:\cs\roslyn> ls .\Binaries\*.nupkg

    Directory: C:\cs\roslyn\Binaries

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/28/2016   9:57 AM          41645 Microsoft.CodeAnalysis.BuildTask.Portable.1.2.0-b001.nupkg
-a----        1/28/2016   9:57 AM          33032 Microsoft.Net.Compilers.netcore.1.2.0-b001.nupkg
-a----        1/28/2016   9:57 AM           5738 Microsoft.Net.CSharp.Interactive.netcore.1.2.0-b001.nupkg
```

I was thinking that `BuildNuGets.csx` was going to build all the NuGet packages. Did I do something wrong?
``` ps
.\Restore.cmd
$env:path = "C:\Program Files (x86)\MSBuild\14.0\Bin;$env:path"
msbuild .\Roslyn.sln /p:SignAssembly=false /v:m /t:rebuild /p:Configuration=Release /p:GenerateProjectSpecificOutputFolder=True 
cp Binaries\Release\CodeAnalysisBuildTask\MSBuildTask\* Binaries\Release\CodeAnalysisBuildTask
csi .\build\BuildNuGets.csx .\Binaries\Release\ 1.2.0-b001 .\Binaries\
```

**Comment by davkean** [comment]
@SamB While, we now have a [script for auto-generating the zip file and uploading](https://github.com/dotnet/roslyn/blob/master/src/Tools/UploadNugetZip/CreateAndUpload.ps1), we're in the process of removing it. For example, we no longer use the zip for Windows jobs: https://github.com/dotnet/roslyn/pull/8982.

@ctaggart We don't build the NuGet packages in the open, we want to, this is being tracked by: https://github.com/dotnet/roslyn/issues/8733
