### ISSUE TITLE
Request for Clarification: What is the behavior of relative paths for the purposes of a #line directive?

### ISSUE THREAD

**Issue by otac0n** [dotnet/roslyn#71202]
**Version Used**: 
All Versions (and all VS versions)

**Steps to Reproduce**:

1. Create a Source Generator that emits relative paths using a #line directive.
2. Enable outputting generated files (set `EmitCompilerGeneratedFiles` to `true`).
3. Using Source Generators as the primary build and also use the generated files as a fall-back.

**Diagnostic Id**:

n/a

**Expected Behavior**:

Relative paths should be supported and well defined to avoid leaking full path information to SourceLink.  Full paths are generally unhelpful and just leak private information.

**Actual Behavior**:
The documentation here provides no guidance on relative paths:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#error-and-warning-information

It's unclear how to get VS and CSC to agree on what relative paths mean. They currently don't agree depending on whether you are running from command line or from VS. Double-click to navigate to error behavior seems to be inconsistent between versions of Visual Studio.

**Comment by otac0n** [comment]
Currently, in my project [Weave](otac0n/Weave) I am using:

```
    <CompilerVisibleProperty Include="CompilerGeneratedFilesOutputPath" />

...

    private const string GeneratedOutputPath = "build_property.compilergeneratedfilesoutputpath";

...

    var outputPath = context.AnalyzerConfigOptionsProvider
        .Select((p, ct) =>
        {
            p.GlobalOptions.TryGetValue(ProjectDir, out var root);
            p.GlobalOptions.TryGetValue(GeneratedOutputPath, out var generated);
            var assembly = Assembly.GetExecutingAssembly().FullName;
            var generator = typeof(GenerateWeaveSources).FullName;
            return Path.GetFullPath(Path.Combine(root, generated, assembly, generator));
        });

...

    public static string MakeRelative(string root, string path)
    {
        root = Path.GetFullPath(root);
        var fullFilePath = Path.GetFullPath(Path.Combine(root, path));
        var relativeUri = new Uri(root).MakeRelativeUri(new Uri(fullFilePath));
        var relativePath = Uri.UnescapeDataString(relativeUri.ToString()).Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
        return relativePath;
    }

....

    var relativePath = PathUtils.MakeRelative(outputPath, template.path);

```

**Comment by jaredpar** [comment]
Using a relative file path in a `#line` directive in a generated file has undefined behavior. Normally relative paths are interpreted relative to the path of the current file but given that generated files do not have a defined path this operation has undefined behavior.
