### ISSUE TITLE
C# completion should do a better job for "out" parameters

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#7121]
```C#
class Program
{
    static void Main(string[] args)
    {
        GetBool($$)
    }

    static void GetBool(out bool b)
    {
        b = false;
    }
}
```

At the caret, "out" is in the list but completion isn't particularly insistent that you include it, thus leading to an error that you need to add the "out". Maybe we should do what VB does for ByRef with a builder?

Also, maybe we should have a quick fix to add the missing out.

**Comment by Pilchie** [comment]
Triage doesn't see how a builder would actually help here?  At the callsite, you can't introduce a new symbol.  Additionally, what if there are multiple overloads, some of which don't have an `out` at that location.  Would the experience be confusing?

Is a better model just to support an "Add out" fix?
