### ISSUE TITLE
IDE0055 triggered on no space after spread operator

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#71219]
I get the following warning because there's no space after my spread operator:

![image](https://github.com/dotnet/roslyn/assets/793830/1ff9ad11-4cee-422d-813e-81fa224dfa81)

I don't even see what [formatting option](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options) would apply to this, and in any case I don't want a space after my spread operators.  It shouldn't give this warning.

**Comment by jez9999** [comment]
@CyrusNajmabadi Is there a Github issue for said new formatting system?

**Comment by sharwell** [comment]
I agree that the space after `..` looks incorrect.

**Comment by CyrusNajmabadi** [comment]
Space there was chosen by ldm, and corresponds to the same space we chose for the corresponding slice pattern form. 

This is not an operator, and does not 'bind tightly' (which is when we think there should be no space.

As an example: `!b ? c : d` here we want `!b` as that binds tightly to `b` and not the whole expression. 

But that's not the case with the spread element. `.. a ? b : c` is `.. (a ? b : c)` not `(..a) ? b : c`. The space is intentionally there to not make it feel like it's operating directly on the things it touches. 

Put another way, it's not a unary expression, so it gets a space

**Comment by CyrusNajmabadi** [comment]
The point isn't that both compile, it's that the formatting implies one over the other.

**Comment by CyrusNajmabadi** [comment]
> It feels like we penalized all actual cases

There's no penalty. We made an informed choice to align with slice patterns so that construction and deconstruction would pair up and format uniformly. And we used our general view here on precedence to dictate for both how we felt the formatting should be.

**Comment by nvmkpk** [comment]
I totally understand the design choice here. I just don't like the fact that the IDE forces us to use one vs other when we format the code. I just want to tell the IDE that I want specific choice for my code either through formatting options or through `.editorconfig` file.
