### ISSUE TITLE
Use ToList for collection-exprs of a single spread

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#71217]
Spun-off from #71195
Similar to the request in #70656

```cs
List<int> list = [..expr];

// compile to:
List<int> list = System.Linq.Enumerable.ToList((IEnumerable<int>)expr); // assuming implicit reference conversion is present
```

**Comment by CyrusNajmabadi** [comment]
Yes.  We can consider doing this.  However, we may only want to do this for:

1. interface types.
2. types we statically know that ToList optimizes for (specifically `List<T>` and `Ilist<T>` impls). 

For other types (say, `HashSet<T>`) this will incur an allocation.  So it might be better to rewrite that case as just doing a foreach in the code  (as that will use the struct enumerator).

**Comment by RikkiGibson** [comment]
When the spread operand implements `ICollection<T>`, which HashSet does, `ToList(this IEnumerable<T>)` will determine that with a runtime check, and call `ICollection<T>.CopyTo(T[], int index)` (indirectly through List's [constructor](https://github.com/dotnet/runtime/blob/23a93aa2305d580b6e77f7254624d0b1787b3008/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L76)), rather than foreach and enumerate.

One case where this codegen could make things worse is when the spread operand implements `IEnumerable<T>` but not `ICollection<T>`. I would be fine with only performing this optimization when we can see at compile time that the operand implements `ICollection<T>`. Sound good?

**Comment by CyrusNajmabadi** [comment]
sgtm.
