### ISSUE TITLE
Version 4.9.x packages missing on Nuget Gallery

### ISSUE THREAD

**Issue by thahnen** [dotnet/roslyn#71226]
**Summary**:

We are working to update Roslyn / [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) into our own integration but it fails as it requires version 4.9 of the following packages:
- [Microsoft.CodeAnalysis.CSharp.Features](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Features)
- [Microsoft.CodeAnalysis.CSharp.Workspaces](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces)

It is also very hard to find a mapping between the Nuget package version and the GitHub status quo. There seem to be no tags or release on GH whatsoever or do I miss something?

cc @nquinquenel

**Expected Behavior**:

These packages are available on the Nuget Gallery for us to consume.

**Actual Behavior**:

These packages are not available on Nuget Gallery and we could only make it work for testing locally using the pre-release Nuget feeds you offer in the [README](https://github.com/dotnet/roslyn#nuget-feeds).

We had to change our Nuget.config in order to work and not rely on our internal mirror of the official NuGet Gallery:
```
<packageSources>
  <!-- Add this repository to the list of available repositories -->
  <add key="Preview Repo for Microsoft.CodeAnalysis 1" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
  <add key="Preview Repo for Microsoft.CodeAnalysis 2" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json" />
  <add key="Preview Repo for Microsoft.CodeAnalysis 3" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
</packageSources>
```

**Comment by huoyaoyuan** [comment]
Roslyn package version actually bounds with Visual Studio version. Roslyn 4.9 corresponds to VS 16.9, which isn't released yet.

**Comment by huoyaoyuan** [comment]
Sorry I mistyped the major version. It corresponds to VS 17.9, which is currently in preview yet.

**Comment by thahnen** [comment]
Ah perfect, now it makes sense, thanks a lot!
