### ISSUE TITLE
Elide MemoryMarshal.ToEnumerable when spread in a collection expression

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#71223]
This is a simplified code sample, but imagine the collection expression being in an async method, so that `ReadOnlySpan` can't be used and `memory.Span` can't be accessed:

```cs
byte[] M(ReadOnlyMemory<byte> memory)
{
    return [42, .. MemoryMarshal.ToEnumerable(memory)];
}
```

It would be great to elide the actual MemoryMarshal.ToEnumerable call and instead, access `memory.Span`. The user can't currently write code that accesses `memory.Span` in an async method, but the compiler can access it for enumeration because awaiting can't happen during enumeration of a span.

Current codegen Dec 8 ([SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgCUBXGAFyjAFNCBJSmgJwHsAHAZRYDcoBjGgGcA3JkzJcAYUwBvTLkW5gATwo0A2gF1cAWQAUxGhAAmAeRgAbFbpphWzFQB5V6gHy5a9xwEoFS+QwlYPwAdlwNABYkABpcQkI9OwcbCGYhAAsIS0IAFVYAURhSWmYIYEsafS8Uny0xIKUAX0wWjCA==)):

```cs
List<byte> list = new List<byte>();
list.Add(42);
IEnumerator<byte> enumerator = MemoryMarshal.ToEnumerable(memory).GetEnumerator();
try
{
    while (enumerator.MoveNext())
    {
        byte current = enumerator.Current;
        list.Add(current);
    }
}
finally
{
    if (enumerator != null)
    {
        enumerator.Dispose();
    }
}
return list.ToArray();
```

**Comment by jaredpar** [comment]
This would require us to take a firm dependency on how `MemoryMarshal.ToEnumerable` functions. Essentially, the compiler has to enocde details about the implementation. That is something the compiler fairly rarely does. Don't think this reaches the bar for doing that right now.

**Comment by jnm2** [comment]
Spreading `ReadOnlyMemory<T>.Span` works after all ([sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5nJQDMmM6AwsgN7Lp2YlQAcmAbOgLIAUASgKYBDYAHkAdgBsAnhz4BbAPYAnSQB4ARpIAufAHzo1AVwBmRvooCUtejST07mAJxsAdAE0Aln3HAu5/Lfs6DW0AbQBddAAPdABedBDnZ31jU0VnAGUABwFRMP9AuignKFY3T29ffPoAX2RqoA=)). I tested it early in the implementation. That makes the issue a moot point; there's no reason to use MemoryMarshal.ToEnumerable now.
