### ISSUE TITLE
IDE features don't work with collection expressions + target-typed new

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#71238]
**Version Used**: 
roslyn main

**Steps to Reproduce**:
```cs
MyStruct s = new(1);
MyStruct[] sArr = new MyStruct[] { new(2) };
MyStruct[] sArr2 = [new(2)];


struct MyStruct
{
    public MyStruct(int parameter)
    {
        
    }
}
```

**Expected Behavior**:
All IDE features work for all cases of target-typed new

**Actual Behavior**:
1) There is no hover for `new` inside collection expression:
![devenv_c1fmmi5iQV](https://github.com/dotnet/roslyn/assets/70431552/0124e771-7dd7-4544-baa6-b8ea737923b6)
2) There are no inlay hints for parameter name if inlay hints are enabled:
![devenv_VPdGxBHcG1](https://github.com/dotnet/roslyn/assets/70431552/6159beb9-99e5-4027-badb-f5d7eec4dffd)
3) Signature help cannot be invoked for a `new` inside collection expression:
![collectionexpressions](https://github.com/dotnet/roslyn/assets/70431552/ce6354bd-6c4c-4686-aa51-51c3e33af652)

Considering how many things are broken I suspect there is a chance that some compiler APIs don't return correct results for that case

**Comment by CyrusNajmabadi** [comment]
> Considering how many things are broken I suspect there is a chance that some compiler APIs don't return correct results for that case

Yes.  That likely seems the case.  Want to debug through to find out?  My guess is that the semantic model apis aren't working here.

@cston @RikkiGibson  as a heads up.  Not sure if this is on the compiler side yet though.  We need to investigate first.

**Comment by RikkiGibson** [comment]
It looks like a semantic model bug to me

```cs
// passes
[Fact]
public void TTNewSimple_SymbolInfo()
{
    var source = """
        class C
        {
            static void Main()
            {
                object item = new();
            }
        }
        """;
    List<object> items = new List<object> { new() };
    List<object> items1 = [new()];
    var comp = CreateCompilation(source);
    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    var node = tree.GetRoot().DescendantNodes().OfType<ImplicitObjectCreationExpressionSyntax>().Single();
    var info = model.GetSymbolInfo(node);
    Assert.Equal("object.Object()", info.Symbol.ToDisplayString());
}

// passes
[Fact]
public void TTNewArrayCreation_SymbolInfo()
{
    var source = """
        class C
        {
            static void Main()
            {
                object[] item = new object[] { new() };
            }
        }
        """;
    List<object> items = new List<object> { new() };
    List<object> items1 = [new()];
    var comp = CreateCompilation(source);
    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    var node = tree.GetRoot().DescendantNodes().OfType<ImplicitObjectCreationExpressionSyntax>().Single();
    var info = model.GetSymbolInfo(node);
    Assert.Equal("object.Object()", info.Symbol.ToDisplayString());
}

// fails
[Fact]
public void TTNewCollectionExprs_SymbolInfo()
{
    var source = """
        class C
        {
            static void Main()
            {
                List<object> items = [new()];
            }
        }
        """;

    var comp = CreateCompilation(source);
    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    var node = tree.GetRoot().DescendantNodes().OfType<ImplicitObjectCreationExpressionSyntax>().Single();
    var info = model.GetSymbolInfo(node);
    Assert.Equal("object.Object()", info.Symbol.ToDisplayString());
}
```

**Comment by RikkiGibson** [comment]
Sorry. I made a mistake here. This is why we always call VerifyDiagnostics in tests. Here's the proper (and working) version of the semantic model test in question :)

```cs
[Fact]
public void TTNewCollectionExprs_SymbolInfo()
{
    var source = """
        using System.Collections.Generic;

        class C
        {
            static void Main()
            {
                List<object> items = [new()];
            }
        }
        """;

    var comp = CreateCompilation(source);
    comp.VerifyDiagnostics();

    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    var node = tree.GetRoot().DescendantNodes().OfType<ImplicitObjectCreationExpressionSyntax>().Single();
    var info = model.GetSymbolInfo(node);
    Assert.Equal("object.Object()", info.Symbol.ToDisplayString());
}
```

@CyrusNajmabadi I think public APIs may actually be functioning correctly here. Let me know if there's any other compiler APIs I should test out in order to rule out compiler layer as the cause here.

**Comment by DoctorKrolic** [comment]
> I think public APIs may actually be functioning correctly here.

Nop. It seems like an array type is required for a reproduction:
```cs
[Fact]
public void TTNewCollectionExprs_SymbolInfo_Array()
{
    var source = """
        class C
        {
            static void Main()
            {
                object[] items = [new()];
            }
        }
        """;

    var comp = CreateCompilation(source);
    comp.VerifyDiagnostics();

    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    var node = tree.GetRoot().DescendantNodes().OfType<ImplicitObjectCreationExpressionSyntax>().Single();
    var info = model.GetSymbolInfo(node);
    Assert.Equal("object.Object()", info.Symbol.ToDisplayString());
}
```
This test fails with null ref for me.

Moreover, if I change array to `List` in the original example, things are working as expected:
![devenv_fAgYS7nmTi](https://github.com/dotnet/roslyn/assets/70431552/b3b076bc-1c01-496e-9159-04a4964c3882)

**Comment by RikkiGibson** [comment]
Have repro'd, thanks.
