### ISSUE TITLE
When will this be fixed? It is extremely annoying!

### ISSUE THREAD

**Issue by LeeIsMe77** [dotnet/roslyn#71231]
When will this be fixed? It is extremely annoying!

_Originally posted by @JonasTickster in https://github.com/dotnet/roslyn/issues/67739#issuecomment-1849739478_
            

Agreed. Annoying and should not be happening.  Update, please?  It's been months.

**Comment by CyrusNajmabadi** [comment]
Closing out. Tracked on the linked bug.
