### ISSUE TITLE
Experimental Feature "Enable all features in opened files from source generators" yields duplicated output errors

### ISSUE THREAD

**Issue by PaulBraetz** [dotnet/roslyn#71243]
**Version Used**: 
VS 2022 Community 17.8.2

**Steps to Reproduce**:

I have encountered the problem while attempting to run the generator found here:
https://github.com/PaulBraetz/RhoMicro.CodeAnalysis/commit/0fb7726b6709122db5db474cf587c5c067cf940b#diff-69eb870d227cecbe439f00bd8736c9573d31acf69c1d3673bb05fe7c8f7a125e

using the test here:
https://github.com/PaulBraetz/RhoMicro.CodeAnalysis/commit/0fb7726b6709122db5db474cf587c5c067cf940b#diff-b7264ea0c55e5ea3f1957a243205cc8d8ce534cd78c1335ad10b178fc962c628

**Expected Behavior**:
The generated code opens without error diagnostics.

**Actual Behavior**:
The generated code opens with a duplicate error diagnostic.

Our conversation on discord:
https://discord.com/channels/143867839282020352/598678594750775301/1184344662199259246

**Comment by CyrusNajmabadi** [comment]
Closing as we haven't seem more reports of this, and these systems were entirely rewritten.
