### ISSUE TITLE
IDE0028 suggests to refactor empty collection expressions

### ISSUE THREAD

**Issue by sehra** [dotnet/roslyn#71245]
**Version Used**: 4.8.0-7.23572.1

**Steps to Reproduce**:
```cs
var x = new List<object[]>();
x.Add([]);
```
**Diagnostic Id**: IDE0028

**Expected Behavior**:
Either doesn't offer to refactor, or refactors to something that is equivalent and compiles.

**Actual Behavior**:
Refactors as below, triggering compile error CS0443, CS1003, and CS1525.
```cs
var x = new List<object[]>()
{
  []
};
```

**Comment by RikkiGibson** [comment]
This might be a parser bug. If you replace the `[]` with `([])` then things start working.

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson It's an IDE bug.  We need to parenthesize here.  Because `[]` makes it look like a dictionary initializer.

**Comment by RikkiGibson** [comment]
Is this the case only for `[]`, or for all collection-exprs used as collection initializer elements?

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson likely *all* collection exprs.  Because `[a]` is a legal indexer for the collection-initializer.
