### ISSUE TITLE
Unused class generated when using Expression<Func<>>

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/roslyn#71263]
There is an unused class generated when using a method with an `Expression<Func<>` signature, e.g `Expression<Func<int>>`. Using just `Func<>` does not have this issue - in that case, the generated class is used to cache the delegate, so it seems to be a specific interaction when using expression trees.

There is no difference between Debug/Release.

**Steps to Reproduce**:

```csharp
using System;
using System.Linq.Expressions;

var t = new Test();
t.M(() => 10);

public class Test
{
    public void M(Expression<Func<int>> expression)
    {
    }
}
```

[SharpLab Link](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwHQBkCWAdgI7YCiAHgA4BOApgM4P4D2hDA3MsgG4CGNdABd0AXnSE6Ad3QAVRkIAUASi5Ih2ALKKVYgHzo4qVdxQBmTDDkLkAb2TpHmC1AAs6bZVqNmbADxQAKx+REJ6BnTU9EyshMoOTvZITugAvsipQA==)

**Expected Behavior**:
No additional class is created.

**Actual Behavior**:
A class
```csharp
    [Serializable]
    [CompilerGenerated]
    private sealed class <>c
    {
        public static readonly <>c <>9 = new <>c();
    }
```
is produced, but not actually used anywhere in the code.

**Comment by DoctorKrolic** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/40453

**Comment by JakeYallop** [comment]
Thanks, didn't spot that one in my search for a duplicate.
