### ISSUE TITLE
Type alias for function pointer fails to compile in cast expression

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/roslyn#71278]
**Version Used**: 4.9.0-ci (https://github.com/dotnet/roslyn/commit/a5c8991ef2068908e0ec8f6720a1779aa161ec9e)

**Steps to Reproduce**:

1. Paste the following code:

```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

using unsafe MYCALLBACK = delegate* unmanaged[Stdcall]<void>;

unsafe
{
    void* p1 = (delegate* unmanaged[Stdcall]<void>)&MyCallback; // ok
    void* p2 = (MYCALLBACK)&MyCallback; // error CS0119
}

[UnmanagedCallersOnly(CallConvs = [typeof(CallConvStdcall)])]
static void MyCallback()
{
}
```

([sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYB0AlArjAFyjAFNMBhAezAAcoAbEgJwGVmA3KAYxIGcBuALAAoZGix5CxMgElCzSjTZNOPASJFj8vCADMSKALIBNcgEEAMhYBCZ8gGkUAXhQATEowDmEAiQBUKPiQMBCeJK4A2iwErlwQ9PQAugA8CAAsAHxCwiLaeiQiAN4iKKVoaQE06M4oABTuXj7+gTDBoeFRMXEJKekZAJQAZIYAnuTx9MAQXADW/CgA9AsolDMlZemVAEw1tSbmVrYOQ6PjCVOz80sozEyUTCjkLEjo6ACcIgC+GsIRAKqtCAhMKuM6MJi8ADyMHoI1qYKoMHYvBqEQIIxoJEounhE0R7GisQm/USJM06AAbOUjGMJhcZrV+kUvkA===))

**Diagnostic Id**: CS0119

**Expected Behavior**:

Code should compile just fine.

**Actual Behavior**:

> "error CS0119: 'delegate* unmanaged[Stdcall]<void>' is a type, which is not valid in the given context"

???

cc. @CyrusNajmabadi

**Comment by SunnieShine** [comment]
Hey friend @Sergio0694!

See this link: https://github.com/dotnet/roslyn/issues/67911#issuecomment-1532188654

**Comment by CyrusNajmabadi** [comment]
Closign out as by design.  Needs to be written as `(X)(&Y)` as `(X)&Y` is interpreted as bitwise and-ing.
