### ISSUE TITLE
The source generator fails with weird error messages, which don't express the true reason of failure.

### ISSUE THREAD

**Issue by kkovalev79** [dotnet/roslyn#71280]
**Version Used**: 
4.8.0

**Steps to Reproduce**:

1. Unpack the minimal solution to reproduce:
[SourceGenerationBug.zip](https://github.com/dotnet/roslyn/files/13686505/SourceGenerationBug.zip)

2. Run **dotnet build**

**Diagnostic Id**:

**Expected Behavior**:

The solution builds successfully, the project Target contains a copy of type AuthorizationRequest from the project Source like the following
:

```csharp
#nullable enable
namespace Target.Model
{
	public partial record AuthorizationRequest
	{
		[System.Text.Json.Serialization.JsonPropertyNameAttribute("scope")]
		public string[]? Scope { get; init; }

		public Source.Model.AuthorizationRequest Map() => new()
		{
			Scope = Scope,
		};
	}
}

```
**Actual Behavior**:

The build fails with errors like these:
_c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20
): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGen
erationBug\Target\Target.csproj::TargetFramework=net8.0]
c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,4
4): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGe
nerationBug\Target\Target.csproj::TargetFramework=net8.0]
c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20
): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGen
erationBug\Target\Target.csproj::TargetFramework=net6.0]
c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,4
4): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGe
nerationBug\Target\Target.csproj::TargetFramework=net6.0]
c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20
): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGen
erationBug\Target\Target.csproj::TargetFramework=net7.0]
c:\Temp\1\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,4
4): error CS0116: A namespace cannot directly contain members such as fields, methods or statements [c:\Temp\1\SourceGe
nerationBug\Target\Target.csproj::TargetFramework=net7.0]_

**Comment by jcouv** [comment]
@jaredpar I don't see a clear indication of a misbehavior by the compiler. Seems more like a problem with a specific source generator that produces invalid code in some case. How should we route this?

**Comment by kkovalev79** [comment]
Julien, thanks for your response. I tried to replace the code that generates the source output with similar but hardcoded constant string. It worked fine - the build was successful. So maybe your asumption is close to truth ;)

When I try to open the initial solution in VS2022, I see the correctly generated AuthorizationRequest.g.cs:

```csharp
#nullable enable
namespace Target.Model
{
	public partial record AuthorizationRequest
	{
		[System.Text.Json.Serialization.JsonPropertyNameAttribute("scope")]
		public string[]? Scope { get; init; }

		public Source.Model.AuthorizationRequest Map() => new()
		{
			Scope = Scope,
		};
	}
}
```
but the solution still does not compile:

_Rebuild started at 13:37...
1>------ Rebuild All started: Project: Source, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: SourceGeneration, Configuration: Debug Any CPU ------
Restored D:\Projects\SourceGenerationBug\Target\Target.csproj (in 8 ms).
Restored D:\Projects\SourceGenerationBug\Source\Source.csproj (in 16 ms).
Restored D:\Projects\SourceGenerationBug\SourceGeneration\SourceGeneration.csproj (in 24 ms).
1>Source -> D:\Projects\SourceGenerationBug\Source\bin\Debug\net7.0\Source.dll
2>SourceGeneration -> D:\Projects\SourceGenerationBug\SourceGeneration\bin\Debug\netstandard2.0\SourceGeneration.dll
1>Source -> D:\Projects\SourceGenerationBug\Source\bin\Debug\net8.0\Source.dll
1>Source -> D:\Projects\SourceGenerationBug\Source\bin\Debug\net6.0\Source.dll
3>------ Rebuild All started: Project: Target, Configuration: Debug Any CPU ------
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20,8,25): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,44,10,47): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>Done building project "Target.csproj" -- FAILED.
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20,8,25): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,44,10,47): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(8,20,8,25): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>D:\Projects\SourceGenerationBug\Target\SourceGeneration\SourceGeneration.MvcModelGenerator\AuthorizationRequest.g.cs(10,44,10,47): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
3>Done building project "Target.csproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 13:37 and took 00,817 seconds ==========_

Accoring to this output it seems the code that compiler tries to process differs from the code I see inside AuthorizationRequest.g.cs (see above) in VS2022.
Is there any way to log or diagnose what source code exactly comes to the input of the compiler after the source generation?

**Comment by jjonescz** [comment]
If you set `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` in a `<PropertyGroup>` in your .csproj, the compiler should emit those generated files into `obj/Debug/generated`.

**Comment by jaredpar** [comment]
Do we know what generator is being used here? That is where the issue should go.
