### ISSUE TITLE
[Infrastructure] Commit pump not running

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7129]
we need to re-run commit pumping

http://dotnet-ci.cloudapp.net/view/roslynpr/job/dotnet_roslyn_prtest_win_dbg_eta/

**Comment by heejaechang** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2108/
https://github.com/dotnet/roslyn/pull/6962

**Comment by heejaechang** [comment]
please retest #6962 once pumping is running again.

**Comment by jmarolf** [comment]
@heejaechang features branches are not auto-updated

**Comment by heejaechang** [comment]
@jmarolf sorry, I don't know what that means.

**Comment by jmarolf** [comment]
See comments for https://github.com/dotnet/roslyn/pull/6962 we do not support running ETA from tests from feature branches because the pump only runs on master and future branches.

**Comment by davkean** [comment]
I've updated the failure cause to call out this particular situation so it's obvious that in this case the failure will occur. We could do better here, but right now - not the highest of priorities.
