### ISSUE TITLE
default 'csharp_style_prefer_primary_constructors' to false

### ISSUE THREAD

**Issue by kjkrum** [dotnet/roslyn#71294]
As a matter of opinion, primary constructors are pointless and obnoxious. And as a matter of fact, the automatic refactoring creates [numerous issues](https://github.com/dotnet/roslyn/issues?q=ide0290). Developers should not be continually nagged to use primary constructors, nor should they be forced to suppress IDE0290 in every project.

Proposed solution: default 'csharp_style_prefer_primary_constructors' to false.

**Comment by CyrusNajmabadi** [comment]
Closing out.  As you said, it's a matter of opinion.  We allow that opinion to be expressed by you disabling the options to move to the more modern and idiomatic C# features.  Thanks!

**Comment by kjkrum** [comment]
@CyrusNajmabadi There's nothing idiomatic about it. It's a half-baked malfeature, as evidenced by the large number of issues created by the refactoring or the feature itself.

**Comment by CyrusNajmabadi** [comment]
You're welcome to your opinion.  The opinion of the team is different.  Thanks.

**Comment by kjkrum** [comment]
@CyrusNajmabadi Funny how even critical bug fixes have a high bar for user demand, but you have plenty of cycles for completely uncalled-for syntactic sugar.

**Comment by CyrusNajmabadi** [comment]
@kjkrum if you have run into critical bugs, please file them. Thanks!
