### ISSUE TITLE
Convert to 'switch' statement changes behaviour

### ISSUE THREAD

**Issue by benjymous** [dotnet/roslyn#71295]
**Version Used**: 
Visual Studio 2022 17.8.1 ; 17.8.2

**Steps to Reproduce**:

Start with the following code snippet in a C# project

```
    void testThing(int a, int b)
    {

        if (a == 1 && b==0 )
        {
            testThing(0, 1);
        }
        else
        {
            if (a== 2 && b==1)
            {
                a = b; b = 0;
            }
            testThing(a, b);
        }

    }
```

converting this to a switch statement produces the following code

```
    void testThing(int a, int b)
    {

        switch (a)
        {
            case 1 when b == 0:
                testThing(0, 1);
                break;
            case 2 when b == 1:
                a = b; b = 0;
                break;
        }

    }
```
the second call to testThing() has been lost in the refactoring.

**Expected Behavior**:

the code should behave as before

**Actual Behavior**:

the code no longer behaves as before

**Comment by CyrusNajmabadi** [comment]
@alrz ?

**Comment by dodexahedron** [comment]
The sample code is an infinite loop for all values.

If your original code really does equate to this, that may be part of the issue.

FWIW, I can't duplicate the behavior you're seeing with that code and taking the convert to switch statement code fix. I get this, which _does_ have the same behavior as the original:

```csharp
void testThing(int a, int b)
{
    switch (a)
    {
        case 1 when b==0:
            testThing(0, 1);

            break;
        default:
        {
            if (a== 2 && b==1)
            {
                a = b; b = 0;
            }
            testThing(a, b);

            break;
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
@dodexahedron this repros for me:

Starting with:

```c#
class C
{
    void testThing(int a, int b)
    {
        if (a == 1 && b == 0)
        {
            testThing(0, 1);
        }
        else
        {
            if (a == 2 && b == 1)
            {
                a = b; b = 0;
            }
            testThing(a, b);
        }
    }
}
```

I get:

```c#
class C
{
    void testThing(int a, int b)
    {
        switch (a)
        {
            case 1 when b == 0:
                testThing(0, 1);
                break;
            case 2 when b == 1:
                a = b; b = 0;
                break;
        }
    }
}
```

@alrz do you know why this happens?  The dropping of the recursive call to testThing is very strange.

**Comment by CyrusNajmabadi** [comment]
@alrz i can't tell if this should even be supported.  It looks like 'no', since we'd need a way to conditionally run `testThing(a, b)`  in the 'default' case *and* after the 'case 2' case runs.  But i don't know how the current system models that.  nor do i know how this is intended to fall out from existing analysis.  Can you clarify how this is expected to work here?

**Comment by CyrusNajmabadi** [comment]
Debugging through @alrz  i'm seeing this get hit recursively when we dive into theh 'else' block:

```
            if (current == 0)
            {
                // didn't consume a sequence of if-statements with unreachable ends.  Check for the last case.
                return operations.Length > 0 && ParseIfStatement(operations[0], sections, out defaultBodyOpt);
            }
```

The issue here is that we have *multiple* operations, (one for the inner if, and one for the inner recursive call to testThing).  This code seems to compeltely ignore that.  That seems bad :)

**Comment by CyrusNajmabadi** [comment]
> so I don't understand how roslyn is supposed to make any sense of it

There's nothing about infinite loops (either explicit, or through recursion) that is strange. Understanding it from Roslyn's perspective is not an issue. 

The concern here is that our transformation in this refactoring drops code inappropriately. I have a fix out for this, but I'm looking for confirmation from the original author of the feature.

**Comment by benjymous** [comment]
Yeah sorry - I basically just tried to refactor down the original code into a snippet that still produced tge same issue - I don't think the recursive nature should matter (I just put arbitrary values in this snippet) - you can probably change it to call an entirely different function - I'll give that a try and see what happens

**Comment by benjymous** [comment]
Yes, here's a replacement non-recursive example

```
   void testThing(int a, int b)
   {
       if (a == 1 && b == 0)
       {
           System.Console.WriteLine("case a");
       }
       else
       {
           if (a == 2 && b == 1)
           {
               a = b; b = 0;
           }
           System.Console.WriteLine("case b");
       }

       System.Console.WriteLine(a, b);
   }
```
becomes
```
   void testThing(int a, int b)
   {

       switch (a)
       {
           case 1 when b == 0:
               System.Console.WriteLine("case a");
               break;
           case 2 when b == 1:
               a = b; b = 0;
               break;
       }

       System.Console.WriteLine(a,b);

   }
```

note that the `System.Console.WriteLine("case b");` line has been lost

**Comment by benjymous** [comment]
Here's an even simpler example

```
    public int AnotherTest(int a)
    {
        if (a == 1)
        {
            a--;
        }
        else
        {
            if (a == 2)
            {
                a++;
            }
            a+= 1000;
        }

        return a;
    }
```

becomes

```
    public int AnotherTest(int a)
    {
        switch (a)
        {
            case 1:
                a--;
                break;
            case 2:
                a++;
                break;
        }

        return a;
    }
```

the operation of this new code is clearly different, since the `a+=1000` line is lost

**Comment by CyrusNajmabadi** [comment]
While the other repros are appreciated, they're not needed.  None of the issue here relates to the recursive nature of the original code.  As mentioned above the only concern is the dropping of code, which happens regardless of recursion or not :)   The fix is already out.  We just need to wait on reviews.
