### ISSUE TITLE
[feature request] Insight into what exceptions can reach a certain part of the code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71308]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/feature-request-Insight-into-what-exce/10471183)._

---
Roslyn must be able to see what exceptions are thrown and what exceptions are caught/handled and which are not. It would be nice if Visual Studio could inform us about what exceptions can reach a certain part in the code and offer a non obtrusive way to add an exception handler for it. It would also be nice if these exceptions are on top of the list of exceptions when intellisense shows a suggestion when writing a catch clause.

---
#### Feedback Bot on 9/20/2023, 07:38 PM: 

(private comment, text removed)

**Comment by dodexahedron** [comment]
Does the `<exception cref="SomeExceptionType>Description of when that exception occurs.</exception>` XmlDoc tag not do what you are wanting, at least for intellisense?

As for actual static analysis of it, yeah it would be nice if VS did that natively. But there are a few extensions that have that ability, in the meantime. I use ReSharper plus a ReSharper plugin called "Exceptional," but [this VS extension](https://github.com/tetractic/ExceptionAnalyzers) does a pretty good job for free. There's also a [nuget package](https://www.nuget.org/packages/Tetractic.CodeAnalysis.ExceptionAnalyzers/) for it, which is the more typical means of consuming analyzers.

**Comment by CyrusNajmabadi** [comment]
Closing as not planned.  Extensions can help here, but we do not plan on doing more outside of hwat existing documentation shows.
