### ISSUE TITLE
Implicit range support via extension method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71307]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Implicit-range-support-via-extension-met/10450647)._

---
There are many collection type objects in .NET that do not have a Slice method, and consequently cannot use the [...] range syntax to get a subcollection.  Moreover, a span or a Memory<T> which does support this cannot be obtained over them.  Thus I propose that the implicit range in the [formal proposal](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges#adding-index-and-range-support-to-existing-library-types) include checking extension methods for a Slice method taking the appropriate parameters, and that a CollectionExtensions type utility class exist that contains a generic Slice extension method implementation, perhaps via .Skip(start).Take(length) or similar, to allow ranges to be used for any collection.  There is the System.Runtime.InteropServices.CollectionsMarshal.AsSpan method yes, but it is described as an "unsafe class..." in the documentation, making it not ideal for routine use, and its use is a fairly cumbersome syntax by comparison.

---
#### Feedback Bot on 8/27/2023, 07:55 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This shoudl be possible once we add extensions to teh language.  An extension indexer should be trivial to then add to whatever type you want, which can defer to one of these implementations.
