### ISSUE TITLE
Visual Studio 2022 Preview intellisense colors for overload completion is bad

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71305]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Preview-intellisense-/10399293)._

---
I am using Visual Studio 2022 Community Preview 2 Version 17.7 and am seeing that the font and background colors for shows method overloads is very bad. I have attached two images, one showing the release version of VS2022 and the second showing Preview. The colors for the normal release version are much better.

VS2022 Preview
The very dark blue that is used for the type is very difficult to read.

![image.png](https://aka.ms/dc/image?name=Bc763c17aa0e2409a9f4611648ddaa0a4638232329477857605_20230624-124910-image.png&tid=c763c17aa0e2409a9f4611648ddaa0a4638232329477857605)

VS2022 Standard Release
![image.png](https://aka.ms/dc/image?name=Bc17d90247bce4e86bb0d479dee4d8ca0638232329853866603_20230624-124948-image.png&tid=c17d90247bce4e86bb0d479dee4d8ca0638232329853866603)

---
#### Feedback Bot on 6/24/2023, 07:08 PM: 

(private comment, text removed)
#### Tracy Wang [MSFT] on 6/27/2023, 01:05 AM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2023, 07:51 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Moving back to VS.  This is not roslyn, i don't believe.
