### ISSUE TITLE
intellisense limited on enum's member for enum type member parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71309]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/intellisense-limited-on-enums-member-fo/10484007)._

---
sometimes pop intellisense with the enum preselected doesn’t works  
namespace OtherNamespace  
{  
public class EnumHolder  
{  
public enum SomeThing  
{ item1, item2 }  
}  
}

namespace MainNS  
{

public class TestClass  
{

public static void Method(string s, OtherNamespace.EnumHolder.SomeThing someThing)  
{  
}

public static void Test()  
{  
Method(“”, when typing the comma the intellisense opens with the whole framework (sometimes it’s ok, and even with this code, i don’t know exactly when vs is lost …

---
#### Feedback Bot on 10/6/2023, 11:17 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Does not repro:

![image](https://github.com/dotnet/roslyn/assets/4564579/f812a6da-64c8-4a13-a919-512c414c805f)
