### ISSUE TITLE
Interface constraints not used for generic interface covariance, leading to CS0266

### ISSUE THREAD

**Issue by roavin** [dotnet/roslyn#71301]
**Version Used**: main, as of 15 Dec 2023 (within sharplab); first noticed with `dotnet --version` == `7.0.305`.

**Steps to Reproduce**:

Please see this code snippet (or view it [in sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMACAKgUwGcAXAWACgBvC7W7AenuwGMB7ANwgCcoIZjssYvi4AzCM3xxsEQtgDu+ADZKZciNgQBXMGACegsAAcl+MPn4RiUVjGytRgsuTqD+I8ZOwBJALJ6AMQliVi49AB5WLQFcAD5sSgBfGjosbH8g5hCw72MlcLjsEB8M4NCIwqSKFNpGbGBZfDdhMQkmvgQZTREodnxOrBrmjzaSvQAhRu93Vq8ql1ScABEevoQArlYwaZbPJuK/CamZvYTk8iG64gALKDkEM1sSLisibBumo03gUzAh9AALNgAOpQG4AcQsPWYAEEYAgdiNJAUAMJKWSEWIACgAlENXPJriImrg0RiimNJoR8IjZvghtQFq5akwRJsuNgUQBlAAMmAAbPziii+DBWAIoHkoMwwUoDGwYH0uAJiHojE0AOQEEgAOlKWXKuRMqPRhExGverGwWqIxB1h0y2Qqtvt/ipNJObViGp12Dh2HwAA8TNKwSxbErCDY7EG7sQ5FjuE09FFsGA7lGYABzLrMWTEAD8eKZzIdZTC4UO7tpe3inid2AAvNgYPh5OlAuW9Eb8qTTZjcQBuIbnS5MMXCd7XKxT4mCORigNcdmCRwfbBZqE8ZjhmDPaD8eddBrU7BpF4fDk3PgyOxCJH0ktpN2NMlms7/ZarfobLZvuTFC+1L/h+T4AIz8meQKghCW7SnCCD/iaGLYsWzJ0ISc59uSgFHMB/YMvidBlgaFZAfg/51l2TYtm2HaOoaeTIWaqHDiW5yjuQQA)):

```cs
class Test
{
    // covariant interface, as well as a dummy implementation of it
    interface IMyFactory<out T> {}
    class MyFactoryImpl<T> : IMyFactory<T> {}

    // base interface and a derived class
    interface IMyBaseInterface {}
    class DerivedFromInterface : IMyBaseInterface {}

    // this demonstrates the problem
    void WithGenericAndInterface<TClass>()
        where TClass : IMyBaseInterface
    {
        // error CS0266: Cannot implicitly convert type 'Test.MyFactoryImpl<TClass>' to 'Test.IMyFactory<Test.IMyBaseInterface>'. An explicit conversion exists (are you missing a cast?)
        IMyFactory<IMyBaseInterface> factory = new MyFactoryImpl<TClass>();
    }

    // note that there is no error if the generic constraint is a base class rather than an interface
    class MyBaseClass {}
    class DerivedFromClass : MyBaseClass {}
    static void WithGenericAndClass<TClass>()
        where TClass : MyBaseClass
    {
        IMyFactory<MyBaseClass> factory = new MyFactoryImpl<TClass>();
    }
}

```

**Expected Behavior**:

In the method `WithGenericAndInterface`, the line `IMyFactory<IMyBaseInterface> factory = new MyFactoryImpl<TClass>();` should compile without error, because the compiler recognizes that TClass implements IMyBaseInterface due to the generic constraint on the method, and that IMyFactory's generic parameter is covariant.

**Actual Behavior**:

`error CS0266: Cannot implicitly convert type 'MyFactoryImpl<TClass>' to 'IMyFactory<IMyBaseInterface>'. An explicit conversion exists (are you missing a cast?)`

**Comment by jaredpar** [comment]
This is the expected behavior here. Co and contravariance are only supported on reference types. The `TClass` type parameter is not constrained to `class` hence could be instantiated by a `struct` and thus is not eligible for variance. Adding the `class` constraint will cause this code to compile: 

```csharp
void WithGenericAndInterface<TClass>()
        where TClass : class, IMyBaseInterface
    {
```

**Comment by roavin** [comment]
That makes sense, thank you for the reply. Is it feasible to add a better diagnostic here, though?
