### ISSUE TITLE
Use the dictionary key to name the variable while implementing the "Use pattern matching" IDE0038 suggestion

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71310]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Use-the-dictionary-key-to-name-the-varia/10490378)._

---
For historical reasons I've got quite a few of 

```
if (some.Dictionary.ContainsKey("foo") && some.Dictionary["foo"] is SomeType)) {
  var whatever = Some.Method((SomeType)some.Dictionary["foo"]);
  ...
```
throughout the code and when going through the suggestions and applying the changes, VS suggests just "v" as the name of the variable it introduces:
```
if (some.Dictionary.ContainsKey("foo") && some.Dictionary["foo"] is SomeType v)) {
  var whatever = Some.Method(v);
  ...
```
It would be great if the key (if it's a string literal) was used to name the variable if no other name was inferred from the code. In the example it's just foo, but most often it's something like "categoryId" or "filters" or some other longer string.

Maybe it's already the case, but IMHO if the expression before the "is SomeType" ends with a non indexed property access then the name of the property with the first letter lowercased ought to be used to infer the suggested name of the variable.

Thanks!

---
#### Feedback Bot on 10/12/2023, 07:41 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  We suggest 'type' here, whihc is appropriate (we use the name of hte type itself to drive the local variable name suggestion:

![image](https://github.com/dotnet/roslyn/assets/4564579/96d113f4-a559-4543-b3f4-d16a5bceba3d)

Would need a more fleshed out repro.
