### ISSUE TITLE
Allow user to finish typing before displaying new inline diagnostic messages from Background Analysis

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71314]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Allow-user-to-finish-typing-before-displ/10455380)._

---
The inline diagnostic message from background analysis is a really nice feature but it can be very distracting while entering a new line of code or editing a line to correct an error. It would be great to have some delay between typing and new analysis warnings about the partial code.

![2023-08-31 Screen-001.png](https://aka.ms/dc/image?name=Bcbbbfcd705ff42a69509d8a54083cbe5638290992706776080_2023-08-31_Screen-001.png&tid=cbbbfcd705ff42a69509d8a54083cbe5638290992706776080)

---
#### Feedback Bot on 8/31/2023, 08:17 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Inline tags rruns on the 'idle delay' cadence.  Which is also what we found was the best balance between not being distracting, while also coming up in time so that users do not think there is something wrong.  Absent more feedback this is not going to change.
