### ISSUE TITLE
static analysis to detect refactoring regressions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71315]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/static-analysis-to-detect-refactoring-re/10440289)._

---
It would be really handy if VS had a feature that could tell you whether some code did the same thing before and after refactoring, just based on static analysis

---
#### Feedback Bot on 8/14/2023, 07:35 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
We explored this in the past and found that this was effectively either impossible or useless.  Practically *everything* that can be changed *will* potentially cause things to not be *exactly* the same in some fashion.  So it then comes down to what people consider "the same thing before and after".  Depending on the party, that can be very different.
