### ISSUE TITLE
Stack trace window should show virtual stack frame below for async code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71319]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Stack-trace-window-should-show-virtual-s/10450520)._

---
Right now, there’s no easy way to see the context of an async task in the call stack window.

If a task is running on a different thread from its parent task Ie. inside a Parallel.ForEach call, the call stack will often show nothing other than the current frame because the task is running on a different task pool thread from its parent.

There is a button to show all threads, which is helpful, but a lot of time is repeatedly wasted in switching to tasks and finding the task in question, rather than the needed context info being immediately apparent.

Perhaps a button on the call stack window to switch to show the final logical/virtual stack would be a way to solve this.

---
#### Feedback Bot on 8/27/2023, 07:55 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Moving back.  Stack trace window is not roslyn.  This is part of the TPL debugging story.
