### ISSUE TITLE
REQ: About "references" line over each class and property...

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71312]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/REQ:-About-references-line-over-each-c/10516710)._

---
The "references" over each property of a class could be more helpful if they were separated in two items:
1. Local references (any references of the property from within the same class) and
2. External references (all references from outside of the class).

In the tooltip window (as shown today) there could be three extra links next to "Collapse all": "Show all", "Show locals", "Show external".

In any case, as it is implemented today, it's probably the feature of VS i dislike the most. IMO it should not take an extra line of the editor. It's a huge waist of space and it looks and feels unnatural. It could be a small button left of the [+]/[-] of the outlining vertical line, which when pressed, would display the same tooltip window as today.

There could be an option in Tools/Options to toggle between this behavior and the current one (for those who like it).

---
#### Feedback Bot on 11/15/2023, 09:59 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
>  IMO it should not take an extra line of the editor. It's a huge waist of space and it looks and feels unnatural.

The feature can be disabled here:

![image](https://github.com/dotnet/roslyn/assets/4564579/c846cdf8-35e9-4044-af02-06df10cbd23d)

**Comment by gh658804** [comment]
This is a useful feature so ++ for it being enabled but -- for it "eating" a line in the editor. It would be better if as said in OP:

>>It could be a small button left of the [+]/[-] of the outlining vertical line, which when pressed, would display the same tooltip window as today.

The way it is currently displayed is irritating and somewhat confusing. It would be more clear if it was out of the way (at least as an extra option, indeed some people may like it as is today).
