### ISSUE TITLE
Intelisense, suggestion, and error context menu's overlap and interfere with each other

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71318]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intelisense-suggestion-and-error-conte/10452988)._

---
[regression] [worked-in:Vs2017]
When fixing bugs and making changes to c# code, there are multiple context menu's that show up at the same time and interfere with each other. The same overlap of context menu's happen when calling a method, where the method's context information from the method comment gets disrupted by variable suggestions and by completion suggestions. 

This problem wasn't prevalent in Vs2017.

---
#### Feedback Bot on 8/29/2023, 10:48 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Moving back to editor.  Roslyn doesn't control this.
