### ISSUE TITLE
NAMES SUGGESTION ON TOKEN RENAME INCORRECT CASE

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71349]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NAMES-SUGGESTION-ON-TOKEN-RENAME-INCORRE/10532092)._

---
Please see the video.

When I'm renaming a private variable it is given me a capital for the first letter. My expected behavior would be to have it an camel case.

Also there's no way to tab onto these you have to use the mouse!
[renameSuggestion.mkv](https://aka.ms/dc/file?name=Ba6efc065544f4fa79a76758194c3d17c638371286879723814_renameSuggestion.mkv&tid=a6efc065544f4fa79a76758194c3d17c638371286879723814)

---
#### Feedback Bot on 12/3/2023, 06:40 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is not roslyn.  this is copilot suggestions.  moving back to paltform.
