### ISSUE TITLE
Visual Studio and VS Code Disable/Enable/Deprecate C# methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71345]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-and-VS-Code-DisableEnable/10399264)._

---
It would save time by being able to disable methods in C# that currently do not work, in an easy manner by just clicking a button next to the method declaration, and for any references to that method, they would automatically be disabled as well or commented, until the method is tested as working as expected again. 

Even better if Visual Studio can track the failure of a method, eg. exceptions and timestamps and you would be able to easily see dependent methods that failed because of this failing method and visualize the code change that caused the issue.

It would also help in deprecating methods that can't be completely removed from the code immediately.

This would be quite nice in both Visual Studio and VS Code.

---
#### Feedback Bot on 6/25/2023, 00:24 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Methods can easily be deprecated by adding the `Obsolete` attribute to them.  The compiler will then analyze your code and force you to have to deal with the fallout of htat (like what to do with other methods htat call the obsolete methods).
