### ISSUE TITLE
Create an attribute that will allow us to hide a class from Intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71341]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-an-attribute-that-will-allow-us-t/10456525)._

---
When a C#/.Net class needs major updates we rather create a new version of it. But we can't remove the original yet, because other code still uses it.
We want to stop the original one from polluting Intellisense suggestions.
It would be nice if we could decorate the original class with an attribute to do just that. (Marking the original one as obsolete doesn't hide it.)
It should be simple for you to add such an attribute and could help many developers.

---
#### Feedback Bot on 9/3/2023, 08:10 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is what EditorBrowsable is for.

**Comment by user-001** [comment]
> This is what EditorBrowsable is for.

No. It's not. It's for hiding a class from a different assembly only.

**Comment by sharwell** [comment]
Duplicate of #51269

**Comment by CyrusNajmabadi** [comment]
Note: the BinaryCompatOnly attribute is being considered for this.  We will likely hide those even from your own code.

**Comment by user-001** [comment]
> Duplicate of #51269

That issue is for changing the way EditorBrowsable works. What this issue here is for is for creating a new attribute so we don't break EditorBrowsable. An attribute specifically for hiding a class everywhere.

**Comment by CyrusNajmabadi** [comment]
@user-001 As mentioend, the BinaryCompatOnlyAttribute is what is being considered for that purpose.  Note, it will truly hide a class everywhere.
