### ISSUE TITLE
#endregion name should match #region name, display current region 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71344]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/endregion-name-should-match-region-nam/10467920)._

---
hey,
i have 2 issues with regions:

1.the #endregion directive name is not necessarily the same as the #region directive name.
for example, 2 possible cases i encountered :

```
#region **name**

#endregion 

#region **another name**

#endregion **name**
```
in my opinion, the name of #endregion should be changed automatically to be the same as the name of #region.

2.there's no way for me to tell in what region i'm currently in.
is it possible to add regions to the navigation bar / Structure Visualizer, the same as VS behavior for methods, mentioned here?
https://learn.microsoft.com/en-us/visualstudio/ide/navigating-code?view=vs-2022

thank you very much :) 

---
#### Feedback Bot on 9/17/2023, 11:17 PM: 

(private comment, text removed)

**Comment by svick** [comment]
Regarding 1, technically, `#region` and `#endregion` don't have *names*, they have *messages*. From [the spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#657-region-directives):

> The message specified in a `#region` or `#endregion` directive likewise has no semantic meaning; it merely serves to identify the region. Matching `#region` and `#endregion` directives may have different [message]s.

I think it would be fine to warn when the messages are different, that is likely incorrect. But a message missing from an `#endregion` is a very common style and I don't see anything wrong with it, so I don't think there should be any warning about that.

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not likely doing this due to lack of broad feedback on this.
