### ISSUE TITLE
save as, like everyone else

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71348]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/save-as-like-everyone-else/10532029)._

---
Here's how I do a project "Save As" for C# projects. The challenge is finding all the places where your project name is and giving it a new project name. You need to rename two folders, rename two files, go into .sln to edit project and path, and go into three files and edit the namespace:

Copy project folder.
Rename project folder.
Go into project folder.
Rename the inside project folder.
Rename .sln file.
Edit inside .sln file and rename project and project path.
Go into inside project folder.
Rename .csproj file.
Edit inside Form1.cs and rename namespace.
Edit inside Form1.Designer.cs and rename namespace.
Edit inside Program.cs and rename namespace.
I use Notepad to go inside the .sln and .cs files. It goes pretty fast. I also use GIT, but there are definitely good reasons for a new project, like when you want to do major tweaks and a new project is appropriate, but you want to quickly leverage off your old project. Maybe Microsoft will add a "Save As" for projects in the future!

---
#### Feedback Bot on 12/3/2023, 09:38 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closign out.  Thsi is not roslyn.  Perhaps a project-system issue.  Tagging @tmeschter if he wants to move this somewhere.
