### ISSUE TITLE
Suggestions for generic inference

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71347]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggestions-for-generic-inference/10531126)._

---
public static TSecond To<TFirst, TSecond>(TFirst first ) 
I want to provide only one generic when calling, such as: 
To<YYY>([Redacted]()); // YYY is TSecond,xxx is TFirst object

But it is currently incorrect grammar.
I hope it can infer the generic types of formal parameters and only explicitly specify other generic types

If you think this is useless, I will provide the following example. This is an efficient method for me to convert entities into views, rather than an inefficient method of cloning through reflection

public static class MapperExt
 {
     public static TViewModel ToVM<TEntity, TViewModel>(this TEntity entity, TViewModel viewModel = default) where TViewModel : IToVM<TEntity>, new()
     {
         var vm = viewModel ?? new TViewModel();
         vm.SetEntity(entity);
         return vm;
     }

public static TViewModel ToVM<TViewModel>(this object entity) where TViewModel : IToVM, new()
     {
         var vm = new TViewModel();
         vm.SetEntity(entity);
         return vm;
     }
 }

public interface IToVM<TEntity>
 {
     public void SetEntity(TEntity entity);
 }

public interface IToVM
 {
     public void SetEntity(object entity);
 }

And now I have to use the object method to perform packing and unboxing operations, because generic inference cannot be made. Although I know that there may be ambiguity when calling these two functions, I hope the compiler can infer that it is ambiguous, and when I only define a generic function, it happens to be able to use it

---
#### Feedback Bot on 11/30/2023, 08:38 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  Thsi appears to be a language request.  Those start as discussions on dotnet/csharplang.  Thanks.
