### ISSUE TITLE
Option to show suggestions from unimported namespaces but add namespace inline instead of adding a using

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71350]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-to-show-suggestions-from-unimport/10535337)._

---
Currently we can disable Intellisense suggestions from unimported namespaces, but there is no way to keep these suggestions and fully qualify names when accepting the suggestion rather than adding a using directive.

---
#### Feedback Bot on 12/6/2023, 07:03 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as we just haven't heard feedback on this since adding and we're unlikely to change this behavior.
