### ISSUE TITLE
C# Text Editor: Add option for conditional expression over 'if'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71354]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Text-Editor:-Add-option-for-condition/10505157)._

---
It would be nice if the options "Prefer conditional expression over 'if' with assignments" and "Prefer conditional expression over 'if' with returns" under Options/Text Editor/C#/Code Styles would contain the preference "When on single line".

So the code

```cs
if(motorcycle. Brand == "Yamaha")
{
    motorcycle. Colour = "Blue"
}
else
{
    motorcycle. Colour = "Red";
}
```

will be refactored to
```cs
if(motorcycle. Brand == "Yamaha") ? motorcycle. Colour = "Blue" : motorcycle. Colour = "Red";
```

but the following code will not:

```cs
if (motorcycle. Brand == "Yamaha")
{
    motorcycle. Colour = "Blue";
    motorcycle. MethodA();
    motorcycle. MethodB();
    motorcycle. MethodC();
    motorcycle. MethodD();
}
else
{
    motorcycle. Colour = "Red"
    motorcycle. MethodA();
    motorcycle. MethodB();
    motorcycle. MethodC();
    motorcycle. MethodD();
}
```

---
#### Feedback Bot on 11/1/2023, 10:03 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is by design.  A conditional expression can only contain a single expression for the 'when true' and 'when false' portions of hte code.  If there are multiple statements, we can't actually convert it.
