### ISSUE TITLE
Add the abbility to suppress CS1573 for a CancellationToken parameter

### ISSUE THREAD

**Issue by MartinDemberger** [dotnet/roslyn#71356]
### Analyzer

**Diagnostic ID**: [CS1573](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1573)

### Describe the improvement

I have added a parameter of type `CancellationToken` to all of my web api methods to support cancelling a request.
They shouldn't be part of my published web api documentation.

Currently I get a lot of CS1573 warnings because of them which hide the real missing documentation for other parameters.

### Describe suggestions on how to achieve the rule

It would help if this warning isn't reported for parameters of types CancellationToken. Maybe a additional configuration would help where I can specify which parameter types oder parameter names should be ignored in this warning. Also a interface may be helpful.

**Comment by jaredpar** [comment]
`CancellationToken` isn't special from a parameter / doc perspective and we don't foresee any changes to the rules here.

**Comment by julealgon** [comment]
> `CancellationToken` isn't special from a parameter / doc perspective and we don't foresee any changes to the rules here.

It is special in terms of Web API documentation though, as that token is never exposed in the API itself.

I think this should be reconsidered eventually. Having to document all those `cancellationToken` parameters adds a ton of noise for someone who just wants to expose XML docs to Swagger.
