### ISSUE TITLE
IDE0290 Primary Constructor should exclude interop structs

### ISSUE THREAD

**Issue by LTRData** [dotnet/roslyn#71357]
### Analyzer

**Diagnostic ID**: [IDE0290](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0290)

### Describe the improvement

The analyzer that suggests where to use Primary Constructors and offer auto-conversion goes a bit too far. For example, I think it should exclude structs with `StructLayout` attributes that might need a specific memory layout for use in interop calls. Currently, since primary constructors often introduce new implicit fields for constructor parameters, it may destroy in-memory layout of the structs and native functions could receive wrong or unexpected data in the fields.

### Describe suggestions on how to achieve the rule

Exclude structs with `StructLayout` attribute from IDE0290 suggestions.

**Comment by CyrusNajmabadi** [comment]
Primary constructors are fine here.  We will move the attributes controlling the field layout to the primary constructor parameter, preserving semantcs.
