### ISSUE TITLE
InvalidProgramException when returning a ref field assignment in a property

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#71369]
**Version Used**: 4.4.0-6.22561.11 (1ce8866c)

**Steps to Reproduce**:

Create a project then compile and run the following code
```cs
int n = 0;
_ = new L(ref n).I;

ref struct L {
    ref int i;
    public int I => i = 2;
    
    public L(ref int n) => i = ref n;
}
```

[sharplab](https://sharplab.io/#v2:C4LgTgrgdgPgllYACKSC8SAMBuAsAKAH10UBTAdyQBkAKMUgMxQEoA6AST3wPqYGdgkAMbIqSAN4Ek0pLyQJkcLjKQABAMzzESdugB88kgCZlMqTI3U6jLcijN9hjHKhcAvgSA==)

**Diagnostic Id**: N/A

**Expected Behavior**: Compiler error

**Actual Behavior**: Compiles successfully, but fails at runtime

**Comment by jaredpar** [comment]
@jkotas the IL _looks_ correct to me here and I can get the program to not crash with pretty minor changes to the `Main` method (like using the result after the `new`) call. Seems like possibly a runtime issue.

**Comment by jkotas** [comment]
`get_I` has bad IL. `stind.i4` is trying to store 2 at address 2.
```
    .method public hidebysig specialname 
        instance int32 get_I () cil managed 
    {
        // Method begins at RVA 0x2077
        // Code size 10 (0xa)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: ldfld int32& L::i // IL stack: &L::i
        IL_0006: ldc.i4.2 // IL stack: 2, &L::i
        IL_0007: dup // IL stack: 2, 2, &L::i
        IL_0008: stind.i4 // Trying to store 2 at 2.
        IL_0009: ret
    } // end of method L::get_I
```
