### ISSUE TITLE
Make build tools run on CoreCLR

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7136]
There are a number of managed tools used during our build that need to be transitioned to CoreCLR.   That includes both:

- Targeting a portable profile 
- Change build on all OS to use CoreCLR

These tools include:

- BoundTreeGenerator
- CSharpErrorFactsGenerator
- CSharpSyntaxGenerator
- VBErrorFactsGenerator
- VBSyntaxGenerator

**Comment by TyOverby** [comment]
Right before I started infra-swat, I attempted this for several days.  I made progress, but found out that we had a dependency issue that didn't allow us to update all the tool dependencies.  @agocke has a better handle on the details; maybe we could all talk about it.

**Comment by jaredpar** [comment]
I have some ideas on how to work around this. 

Even if those ideas don't pan out though, need to deliver on this.  We can work with the NuGet team on how to properly unblock these issues.

**Comment by TyOverby** [comment]
I think it was actually an issue with MSBuild, but yeah, I'm interested in your workarounds.
