### ISSUE TITLE
Roslyn SemanticModel symbol resolution not working reliably

### ISSUE THREAD

**Issue by russellw** [dotnet/roslyn#71370]
**Version Used**: 4.8.0

**Steps to Reproduce**:

1. https://github.com/russellw/test-semantic-model
2. also described at https://stackoverflow.com/questions/77684125/roslyn-semanticmodel-symbol-resolution-not-working-reliably

**Expected Behavior**:

Symbol info resolves to method symbol, or failing that, to a list of candidate symbols, or failing that, to a reason for failure.

**Actual Behavior**:

No candidate symbols, and no reason given.

**Comment by CyrusNajmabadi** [comment]
The code is in error. `Environment.Exit` cannot be resolved at all. There are no candidates either to resolve to. So you get no symbol information.  

Check the diagnostics on your compilation object to see the issue.
