### ISSUE TITLE
`()` is not parsed as empty tuple type in type argument list of method call

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#71378]
**Version Used**: VS 17.8.2

**Steps to Reproduce**:
```csharp
class C
{
    void M<T>()
    {
        M<()>();
    }
}
```

**Expected Behavior**:
* The expression is parsed as an invocation expression with a type argument list with an empty tuple type as the first type argument.
* Error CS8124: "Tuple must contain at least two elements".

**Actual Behavior**:
The two angled brackets are parsed as 'greater than' and 'less than' expressions, and the brace pairs are parsed as parenthesized expressions instead of an empty tuple type and a method argument list, respectively.

Syntax tree:
![grafik](https://github.com/dotnet/roslyn/assets/823398/57310747-8949-4410-9c45-39c2f65746ca)

**Notes**:
In non-expression contexts (field declarations, parameter declarations, type base lists, ...) `SomeType<()>` parses just fine and gives the expected error.

**Comment by CyrusNajmabadi** [comment]
THis is expected.  The code is not legal, and this is an expression context.  Seeing that this wasn't a tuple, compiler guessed that you were comparing somethign against a parenthesized expression that was missing elements.   

We could consider tweaking error recovery here.  But there is no bug with the current behavior.
