### ISSUE TITLE
Port compiler tests to CoreClr on Windows

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7137]
The compiler unit tests need to multi-target net46 and netcoreapp2.0 in order to run on CoreClr. This tracks the progress of porting the projects:

- [x] C# syntax tests
- [x] C# symbol tests
- [x] C# emit tests
- [x] C# semantic tests
- [x] VB syntax tests
- [x] VB symbol tests
- [x] VB emit tests
- [x] VB semantic tests
- [x] VB ioperation tests

**Comment by agocke** [comment]
The C# syntax tests and compiler test utilities were moved to portable in #8722. The rest of the Compiler unit tests should follow.
