### ISSUE TITLE
IDE0005 codefix could remove empty pragma

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn#71382]
### Analyzer

**Diagnostic ID**: IDE0005

### Describe the improvement

Assume the following code:

```csharp
#if NET6_0_OR_GREATER
using System.Threading.Tasks;
#endif
```

And assume you are enabling `ImplicitUsings`, you will get some dignostics to remove the `using System.Threading.Tasks` that will leave the empty `#if` that you will have to clean manually.

### Describe suggestions on how to achieve the rule

We could detect if there's nothing left in the pragma and remove it too.

**Comment by CyrusNajmabadi** [comment]
Generally we don't like removing pp directive blocks.  We did that in the past, but users complained they then wanted to put code back into them.

**Comment by sharwell** [comment]
Perhaps we could implement a different (new) analyzer that reports empty preprocessor blocks?

**Comment by Evangelink** [comment]
> Perhaps we could implement a different (new) analyzer that reports empty preprocessor blocks?

That would fit perfectly this case and some others so yes please do. Feel free to close this one as won't fix (and cc me on the other new rule suggestion).

**Comment by CyrusNajmabadi** [comment]
Closing out.  Having another analyzer/fixer would be fine with me as well.
