### ISSUE TITLE
In c# code cleanup, How to stop visual studio 2022 adding comments /* Unmerged change from project 'xxxx (net6.0)'  

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/roslyn#71381]
I did cleanup to c# solution  with 6 projects  using profile2 . I  found that Analyzer add these like comments:
 /* Unmerged change from project 'xxxx (net6.0)'
 Before:
         foreach (var word in words)
 After:
         foreach (string word in words)
 */
 Many of  my source code files have these comments.

 Why code cleanup add theses comments  and what is its advantage?
 How to stop visual studio 2022 adding comments?
 Is there a quick way to remove these comments or i have to undo all changes using git?

**Comment by CyrusNajmabadi** [comment]
this means the code fixer produced a different result in different TFMs of that project.  It then wasn't able to merge the two results together, leading to this issue.  

You can avoid this by not running code cleanup, but instead trying to run that particular fixer manually on those particular projects to get to a good state.

**Comment by moh-hassan** [comment]
@CyrusNajmabadi 
>this means the code fixer produced a different result in different TFMs of that project. It then wasn't able to merge the two results together, leading to this issue.`

Is There a way to direct analyzer to do analysis in only ONE TFM?

>You can avoid this by not running code cleanup, but instead trying to run that particular fixer manually 
Manual fixing is effort consuming and we loose the benefit of batch cleanup.

**Comment by CyrusNajmabadi** [comment]
> Is There a way to direct analyzer to do analysis in only ONE TFM?

Yes.  Run the analyzer manually, and ask to only fixup that project.  If you do solution-cleanup, it will cleanup all TFMs currently.   So just address the cases where you're getting conflicts by doing that analyzer manually.  Then you can go back to solution cleanup.

**Comment by moh-hassan** [comment]
@CyrusNajmabadi 
>Yes. Run the analyzer manually, and ask to only fixup that project. 

The problem is the project of multi target framework.

It should be a plan to fix this issue because sometimes it fill source code with  unhelpful comments. 
Or , at least, allow to be set in configuration file or UI, if we need such comments.
Or, allow to filter for framework.
 
Also, this issue can effect the `dotnet format` tool like [this issue](https://github.com/dotnet/format/issues/1634)

**Comment by CyrusNajmabadi** [comment]
@moh-hassan prs welcome.
