### ISSUE TITLE
`foreach` should support types with multiple `IEnumerable<T>` implementations if there is one implementation all can be converted to

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#71387]
According to [13.9.5 The foreach statement](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/statements.md#1395-the-foreach-statement), `foreach` should support collection types with multiple `IEnumerable<T>` implementations if there is one implementation that all others can be converted to:

> - Otherwise, check for an enumerable interface:
>   - If among all the types `Tᵢ` for which there is an implicit conversion from `X` to `IEnumerable<Tᵢ>`, there is a unique type `T` such that `T` is not `dynamic` and for all the other `Tᵢ` there is an implicit conversion from `IEnumerable<T>` to `IEnumerable<Tᵢ>`, then the collection type is the interface `IEnumerable<T>`, the enumerator type is the interface `IEnumerator<T>`, and the iteration type is `T`.
 
This doesn’t seem to be supported in the compiler though (see [sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoBhAewBtGBTAYwSnpgGcBuYmUp4ALAKLlBOYQHZiAb2LllwgGyUR5ALLQYACgCUSlYokrzWgJ4Nm7Tt3JtyAXnIwWAd23WmrDl30DcXNzADN6ZBYINgALcj0ANwhkcihUmEcDcgB6bPIWZGQI8loAZTxVEVJjEJCGXiYWagB1ZCgEFj0oIJryAF9iAYkpbxs/ewyQYQBmAB56YAArOwA+OBnZqlIVhV6ABzakjvIAGSgeBE28bfIAfUZzhBc3T1PHq+3DYJUsaY1yACCABMgXotuQeFl5HcHhdqMDQZC+P1egBJACiMFQYAKEAQEQ+Kw2WxW1AA4iwEJjsbj8chDORoVgZDDHuTKdSccg8REviizMoMViuTzkPMlqsNgtlhxSRSqcLabyoZQWfc2fLOUr6UF+eYhTTuXSZuyFYbRQymWrYQhTVqjcrkUM+kA)):

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
 
class Program
{
    static void Main()
    {
        MyCollection c = new MyCollection();
        foreach (var i in c) // error CS1640
            Console.Write(i);
    }
}
 
class MyCollection : IEnumerable<object>, IEnumerable<string>
{
    private List<string> _list = new List<string>();
    public void Add(string s) { _list.Add(s); }
    IEnumerator<string> IEnumerable<string>.GetEnumerator() { return _list.GetEnumerator(); }
    IEnumerator<object> IEnumerable<object>.GetEnumerator() { return _list.GetEnumerator(); }
    IEnumerator IEnumerable.GetEnumerator() { return _list.GetEnumerator(); }
}
```

**Expected Behavior**:
No errors.

**Actual Behavior**:
```
(10,27): error CS1640: foreach statement cannot operate on variables of type 'MyCollection' because
    it implements multiple instantiations of 'IEnumerable<T>';
    try casting to a specific interface instantiation
```

The native compiler reports the same error.

**Comment by cston** [comment]
cc @jaredpar, @BillWagner

**Comment by cston** [comment]
The behavior is unchanged from the pre-Roslyn compiler and we haven't received reports of this issue previously.
Per offline discussion, closing as won't fix due to lack of customer impact:

**Comment by svick** [comment]
Should the spec be revised then?
