### ISSUE TITLE
The auto generated async enumerator types implement IAsyncEnumerator public interface methods as private

### ISSUE THREAD

**Issue by koculu** [dotnet/roslyn#71406]
### Description

When a method is implemented using yield statements, an enumerator is automatically created. This enumerator type implements IAsyncEnumerator<T>. However, when attempting to access the MoveNextAsync() method through reflection, I encounter difficulty retrieving method information from the public method collection due to its implementation as a private method.

This is a blocker because I don't want to expose private methods in scripting engine through reflection.

### Reproduction Steps

```cs
public class TestAsyncYield
{
    public static async IAsyncEnumerator<int> GetEnumerator()
    {
        yield return 3;
        await Task.Delay(1000);
        yield return 1;
        await Task.Delay(1000);
        yield return 2;
        await Task.Delay(1000);
        yield return 3;
        await Task.Delay(1000);
        yield return 3;
    }
}

var type = TestAsyncYield.GetEnumerator().GetType();
//  The following method should return public interface method, but it doesn't
type.GetMethod("MoveNextAsync", BindingFlags.Public | BindingFlags.Instance);
```

### Expected behavior

```cs
var type = TestAsyncYield.GetEnumerator().GetType();
//  The following method should return public interface method info, but it doesn't
type.GetMethod("MoveNextAsync", BindingFlags.Public | BindingFlags.Instance);
```

### Actual behavior

The MoveNextAsync method is implemented privately.

**Comment by huoyaoyuan** [comment]
It is technically incorrect to retrieve interface implementing method by name, since explicit implementations do have different names. Use interface method map inatead.

**Comment by koculu** [comment]
> It is technically incorrect to retrieve interface implementing method by name, since explicit implementations do have different names. Use interface method map inatead.

The main point of this issue is not the name of the interface method.
Instead, it revolves around the fact that the public interface method is implemented as a private method. 
Consequently, it cannot be queried through the GetMember or GetMembers method using the Public BindingFlag.

**Comment by CyrusNajmabadi** [comment]
@koculu looking up apis from the public surface area isn't a goal of Roslyn. Interfaces and interface implementation are already things that can be looked up using standard reflection calls. 

You should use that as that is at least guaranteed to work. Depending on anything else would be an implementation detail that could change at any time.

**Comment by koculu** [comment]
@CyrusNajmabadi 
I originally created the issue on dotnet/runtime repository.
@stephentoub transferred the issue into the Roslyn repository.
Could you please move it to the appropriate repository for further evaluation?
Thank you.

**Comment by CyrusNajmabadi** [comment]
It sounds like both the runtime and compiler think this is the right behavior. There are reflection apis you can use. It's not a goal to support using the reflection apis in the particular way that you are requiring.

**Comment by CyrusNajmabadi** [comment]
Closing out as by design. How things are emitted is an internal impl detail. And if you need interface implementation methods/properties, those can easily be found with reflection (and that should be the way to do things anyways).

**Comment by koculu** [comment]
I believe this is not an implementation detail. 
The method signature is visible publicly.
There is a mismatch between the C# code in IDE and the code's meta properties in  Reflection API.
This is an asymmetry and I believe it should be fixed even there isn't any use case depending on it.

Here is the code sample that expose the signature mismatch using public API's:

```cs
public class TestAsyncYield
{
    public static async IAsyncEnumerator<int> GetEnumerator()
    {
        yield return 3;
        await Task.Delay(1000);
        yield return 1;
        await Task.Delay(1000);
        yield return 2;
        await Task.Delay(1000);
        yield return 3;
        await Task.Delay(1000);
        yield return 3;
    }
}

internal class Program
{
    async static Task Main(string[] args)
    {
        var enumerator = TestAsyncYield.GetEnumerator();
        // The MoveNextAsync method is implemented publicly, because we can call it publicly.
        await enumerator.MoveNextAsync();

        // However, in the type's member list it is categorized as private.
        var members = enumerator.GetType().GetMembers(BindingFlags.NonPublic | BindingFlags.Instance);
        var hasMoveNextAsyncInPrivateList = members.Any(x => x.Name == "System.Collections.Generic.IAsyncEnumerator<System.Int32>.MoveNextAsync");

        // The implementation detail mismatch is visible via public APIs.
        // MoveNextAsync method should not be listed in private members.
        Assert.That(hasMoveNextAsyncInPrivateList, Is.False);
    }
}
```

**Comment by CyrusNajmabadi** [comment]
Whether the interface is implemented publicly or privately is an implementation detail. 

You are deciding to call through the underlying type (which itself is an impl detail). Just like you can call the interface method directly (as you showed below), you can lookup the interface method on the type. 

But you have to use interface lookup. Trying to get a public method on the type is not supported, and would be an impl detail. 

I'm not sure how to best explain this beyond this.  If you have more questions please come to the Roslyn channel at discord.gg/csharp, and we can talk more.

**Comment by svick** [comment]
While I agree that the compiler effectively using the equivalent of explicit interface implementation is correct, I wonder what the reason for that is and whether making the interface implementation methods public wouldn't be better.

Another case where this becomes visible is [when using `dynamic`](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSAsA3OlrkgKzFolIBsuAHNgJICCAzgJ5QDGAolAgBbAKZgAhsAD2YADwBLKMAB82AOIjgA4WMkyAFAEp0Ab3TYLuAJy5aAOgAiIgDbjO+pJi+GqlsklwAdmwAZioAX3R0ABNucSF5HmwRbABedU1tUQlpMCMqdAB3AAt5ZxT9OBsROwBZKQA3EQA5EQAPYA5uHiNjNDM0PzwrfRqAYQgwMBElH3Rw7CA):

```c#
static async IAsyncEnumerator<int> GetEnumerator()
{
    await Task.Delay(1000);
    yield return 3;
}

dynamic e = GetEnumerator();

 // This throws RuntimeBinderException, even though the same code with var instead of dynamic works
while (await e.MoveNextAsync())
{
    Console.WriteLine(e.Current);
}
```
