### ISSUE TITLE
VS hangs when debugging C# code

### ISSUE THREAD

**Issue by lorcanmooney** [dotnet/roslyn#7140]
I just downloaded the Update 1 RTM and while debugging some C# (somewhat ironically, an infinite loop of my own), I've managed to make the Visual Studio hang quite simply and predictably:

1. Debug app
2. Pause app in debugger
3. Switch to the second stack frame from the top

It looks like a single thread is spinning. I have a process dump if someone wants to take a look.

**Comment by lorcanmooney** [comment]
In what I saw above, the memory usage of devenv.exe was stable, but I just hit another case where two threads seem to be endlessly allocating. The UI is again unresponsive, but now the working set is swinging wildly between 700 and 900 MB.

**Comment by KevinH-MS** [comment]
@lorcanmooney Sorry for the long delay in getting to this.  Yes, if you have a process dump available somewhere, I'd be very interested in taking a look.

**Comment by lorcanmooney** [comment]
@KevinH-MS Do you have an e-mail address I can send the links to? I'm a little reluctant to make them available to the world...

**Comment by KevinH-MS** [comment]
@lorcanmooney -> kevinh@microsoft.com  Thanks!

**Comment by lorcanmooney** [comment]
@KevinH-MS Thanks, I've sent you a OneDrive share with two dumps.

For what it’s worth, I’ve haven’t seen this since and, unfortunately, I no longer have the code which triggered the problem.

Let me know if I can be of any further help.

**Comment by KevinH-MS** [comment]
Thanks @lorcanmooney!  I was able to crack open both dumps on my machine.  I will follow up with the owners of the code that is executing and post back here with what I find.

**Comment by pnelsonmsft** [comment]
From the dumps, it looks like the debugger is evaluating ToString on a very large StringBuilder.  A quick workaround for this is to disable implicit evaluation of ToString.  You can do this by going to Debug -> Options and unchecking "Enable property evaluation and other implicit function calls" or "Call string-conversion function on objects in variable windows".

I'll see what I can do in terms of making the debugger smarter about timing out in this case.

**Comment by lorcanmooney** [comment]
Thanks, that makes sense. I was debugging an infinite loop at the time, so there probably was plenty of bad data for it to trip over.

**Comment by ManishJayaswal** [comment]
Closing this out.

**Comment by lorcanmooney** [comment]
> Closing this out.

So ... was this fixed?

**Comment by ManishJayaswal** [comment]
@pnelsonmsft is there an internal debugger bug tracking this work? This is not Roslyn specific issue.

**Comment by pnelsonmsft** [comment]
Yes, this is a bug in the debugger and tracked by internal bug 177107.  It is not fixed yet.

**Comment by lorcanmooney** [comment]
Thanks.

@ManishJayaswal  It would be best to add some small explanation when closing an issue like this, since most of us outsiders don't know the internal workings or division of labour.

**Comment by ManishJayaswal** [comment]
@lorcanmooney yes fair point. I should have added a comment stating that.
