### ISSUE TITLE
Websockets and break on exception

### ISSUE THREAD

**Issue by Ti-roy** [dotnet/roslyn#71405]
I am not sure this is right the repo to address debugger issues, but have not found a better one. 

I have an application that heavily relies on websockets. But there is a problem - if exception is thrown inside websockets - debugger will not break. In any other place it will.

It makes my work extremely tedious as it requires me to catch a exception, read it, and then by callstack figure out where it was thrown.

Here is repo with which you can reproduce the behavior: https://github.com/Ti-roy/broken-websockets

**Comment by CyrusNajmabadi** [comment]
@Ti-roy please file that issue using VS' "report a problem" feature. Thanks!
