### ISSUE TITLE
Roslyn Compilation, 160 errors and process terminated due to NullReferenceException when a class with primary constructor implements INotifyPropertyChanged

### ISSUE THREAD

**Issue by sherif-elmetainy** [dotnet/roslyn#71400]
**Version Used**: 
C# 12, dotnet SDK version 8.0.100, MSBuild version 17.8.3+195e7f5a3 for .NET,  Visual Studio Professional 2022 Version 17.8.3
Also occurs when using Rider version 2023.3.2

**Steps to Reproduce**:
1- Create a C# file with the following code and try to compile it. 
```csharp
using System.ComponentModel;

internal class MyClass(MyOtherClass otherClass, string key, int value) : INotifyPropertyChanged
{
    public string MyProperty { get; private set; } = GetValue(otherClass.MyProperty, key, value);
    private PropertyChangedEventHandler? _propertyChanged;


    private static string GetValue(string myProperty, string key, int value)
    {
        throw new NotImplementedException();
    }

    public event PropertyChangedEventHandler? PropertyChanged
    {
        add
        {
            lock (this)
            {
                if (_propertyChanged is null)
                {
                    otherClass.SomethingChanged += OnSomethingChanged;
                }
                _propertyChanged += value;

            }
        }
        remove
        {
            lock (this)
            {
                if (_propertyChanged is null)
                {
                    return;
                }
                _propertyChanged -= value;
                if (_propertyChanged is null)
                {
                    otherClass.SomethingChanged -= OnSomethingChanged;
                }
            }
        }
    }

    private void OnSomethingChanged(object? sender, EventArgs e)
    {
        throw new NotImplementedException();
    }
}

internal class MyOtherClass
{
    public event EventHandler? SomethingChanged;
    public string MyProperty { get; set; }
}

```

**Expected Behavior**:
The code should compile without error.

**Actual Behavior**:

- When building from the command line (`dotnet build`), the C# compiler produces 160 errors the crashes with error `C:\Program Files\dotnet\sdk\8.0.100\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Process terminated. System.NullReferenceException: Object reference not set to an instance of an object. [D:\source\my\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]` (This is a partial log of the error which is very big, the entire error log is attached [here](https://github.com/dotnet/roslyn/files/13751763/result.txt)).
- When building in Visual Studio I get `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.exe" exited with code -2146232797.`

Moreover, when working with either Visual Studio or Rider, the C# analyzers and generators stop working (apparently because of the Roslyn process crashing). While this may not be apparent in my sample reproduction, it occurs in my actual project, but I kept the reproduction to minimum and excluded irrelevant code. 

This seems to be similar to #50198, however the old issue is resolved (may be this is a regression?) and old one was related to records and not primary constructors.

**Workaround**:

Using a normal constructor instead of a primary constructor with that class fixed the issue and allowed me to continue my work.

**Comment by jhinder** [comment]
The repro can be simplified.

* The event must be an interface implementation.
* One of the event accessors needs to reference a field from the primary constructor, but it can be of any type.
* The mere reference of the constructor parameter is enough to trigger the error.

```csharp
using System;

interface I
{
    event EventHandler E;
}

class C(int i) : I
{
    public event EventHandler E
    {
        add { i }
        remove { }
    }
}
```

https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTsAuBTAJwDMIBjPAAgElMBvTCxivANzxhwoFE2OAJCDAAmAG0LcA3JgC+mTMgoBhABS4KUAJQUQ1OgyYIAzM16ce7HAOFiC3fY3oYmzihCFCKtdRVlOXjAjwwAHs2Tx97CIxpIA=

In the cases where it doesn't throw an exception, it fails this assertion here:
https://github.com/dotnet/roslyn/blob/182e829faf57b84150a2b28036f20918f368fc9d/src/Compilers/CSharp/Portable/Symbols/Source/SourceEventAccessorSymbol.cs#L193

**Comment by nvmkpk** [comment]
This also happens in MAUI and WPF when implementing ICommand interface
