### ISSUE TITLE
[Bug]: Code action `Simplify conditional expression` leads to incorrect formatting

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#71418]
### Version Used

* Compiler version: '4.9.0-3.23604.10 (3d13136a)'
* VSCode: 1.85.1, 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, x64
* C# extension: v2.14.8, C# Dev Kit extension: v1.2.5

### Steps to Reproduce

1. Create or open any C# project in Visual Studio Code.
2. Create a method which includes a multi-line ternary expression including booleans:
    ```cs
    bool Foo() => true;
    bool Bar() => true;

    return Foo()
        ? Bar()
        : false;
    ```
3. Apply the recommended code action.

### Expected Behavior

The simplified code is formatted correctly:
```cs
return Foo()
    && Bar();
```
or:
```cs
return Foo() && Bar();
```

### Actual Behavior

Leading indentations are removed:
```cs
return Foo()
&& Bar();
```

**Comment by just-ero** [comment]
This is still an issue on these versions:

* Compiler: 4.12.0-3.24430.2 (28052736)  
* .NET: 9.0.100-rc.1.24452.12  
* Visual Studio Code: 1.93.1, `38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40`, x64  
* C# Extension: v2.46.32  
* C# Dev Kit Extension: v1.11.6

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community PR here.
