### ISSUE TITLE
Translation of lines is causing incorrect formatting

### ISSUE THREAD

**Issue by Jay-o-Way** [dotnet/roslyn#71411]
## Repo URL where the string lives

https://github.com/dotnet/roslyn

## File Name

https://learn.microsoft.com/nl-nl/dotnet/fundamentals/code-analysis/style-rules/ide0047-ide0048
"IDE0047 and IDE0048: Parentheses preferences"

## English String

> The arithmetic binary operators are: `*`, `/`, `%`, `+`, `-`, `<<`, `>>`, `&`, `^`, and `|`.
> The relational binary operators are: `>`, `<`, `<=`, `>=`, `is`, `as`, `==`, and `!=`.

## Current Translation

![image](https://github.com/dotnet/roslyn/assets/65828559/251755e2-1cfd-4406-9461-1cb88422e176)

## Suggested Translation

Note the missing characters.

## Language

Netherlands

## Why Fix is needed

Missing characters.

--- 
## Roslyn Team Instructions

A Roslyn team member will file a bug through https://aka.ms/ceLocBug which the translation team will consider.

Internal Tracking Issue: {Update with tracking issue URL.}

**Comment by Jay-o-Way** [comment]
The `code` is supposed to be off limits!

**Comment by Jay-o-Way** [comment]
Anybody home?

**Comment by Jay-o-Way** [comment]
Hellooo?

**Comment by CyrusNajmabadi** [comment]
Closing out.  Tracked at https://github.com/dotnet/docs/issues/40307.
