### ISSUE TITLE
Infrastructure for shipping language features in updates

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7141]
There is interest in seeing if we can ship small, but impactful, language features in updates.  In order to do this the following work will need to be done:
- Introduce the concept of minor versions to the language: i.e. 6.1, 6.2 
- Ensure minor language versions were opted into explicitly.  Can't use C# 6.1 in VS 2015 Update 2 unless the project file specifically opted into it.  This is important because it prevents silent dependencies on VS updates which could break the build in a team environment. 

Note: at this point this is an **exploratory** item.

**Comment by jaredpar** [comment]
For the time being we've decided to not explore this in the C# 6 language train.  The infrastructure needed to get this working is high enough that it reduces our ability to actually deliver the change in an update.  

It is still being highly considered for C# 7.0 though.  That release has the runway necessary to get the infrastructure in place.

**Comment by MgSam** [comment]
Sad to see this won't be happening any time soon.

@jaredpar Do you mean C# 7 and C# 8? Or by "C# 6 language train" are you referring to the VS2015 updates as opposed to VS vNext?

**Comment by jaredpar** [comment]
By C# 6.0 I mean updates that will be going into the VS 2015 code base.

**Comment by paulomorgado** [comment]
Does this mean that we'll be getting back the dotted version numbers for the language?

/cc @gafter, @MadsTorgersen

**Comment by jcouv** [comment]
I'm now tracking work items in https://github.com/dotnet/roslyn/issues/17173.
Closing this issue as duplicate.
