### ISSUE TITLE
JsonSerializer can't serialize source generated property

### ISSUE THREAD

**Issue by fgsfds** [dotnet/roslyn#71426]
**Version Used**: 
4.8

**Steps to Reproduce**:

Repo with the bug demo https://github.com/fgsfds/SourceGenerationBugDemo

1. Open Test.sln
2. Select 'Common' as startup project
3. Start it
4. In bin folder files 'config.json' and 'config_g.json' are created.

Explanation:

There are two files in the repo: `/src/Common/Config/ConfigProvider.cs` and `/src/Common/Config/ConfigProviderGenerated.cs`

Both contain a class which have one property and a constructor. And another class with a static method that serializes and saves these types as `config.json` and `config_g.json` respectively.

The only difference between these ConfigProviders is that `ConfigProviderGenerated's` property is generated using a `[ConfigParameter]` attribute. Generated property is exactly the same as `ConfigProvider's`. Generator placed in `SourceGenerators` project.

**Expected Behavior**:

Both `config.json` and `config_g.json` contain `{"TestProperty":true}`

**Actual Behavior**:

Only `config.json` contain `{"TestProperty":true}` and `config_g.json` only have empty brackets `{}`

Looks like JsonSerializer doesn't see a property in a generated partial class and thus, doesn't serialize it.

**Comment by CyrusNajmabadi** [comment]
Generators run independently. So they cannot see the outputs of other generators. So this is behaving as expected given this core part of the design.
