### ISSUE TITLE
IDE0305 codefix generates invalid code

### ISSUE THREAD

**Issue by Blokyk** [dotnet/roslyn#71427]
**Version Used**: `4.9.0-3.23604.10 (3d13136a)`

**Steps to Reproduce**:

This seems to be mostly a bad interaction with extension methods and inference.

```cs
ReadOnlySpan<byte> s = default;

s.Foo(new byte[] { 1, 2 });
//    ~~~~~~~~~~~~~~~~~~~
//          IDE0305

static class Utils {
    public static void Foo<T>(this ReadOnlySpan<T> s1, ReadOnlySpan<T> s2) {}
    public static void Foo<T>(this Span<T> s1, ReadOnlySpan<T> s2) {}
}
```

**Diagnostic Id**: IDE0305

**Expected Behavior**:

Codefix should generate the following code:

```cs
s.Foo((byte[])[1, 2]);
// OR
s.Foo((Span<byte>)[1, 2]);
```

Option 2 is slightly better, since it would allow the compiler to "optimize" it if possible, which seems to be one of the goals of the collection expression syntax. However, it's also a lot more verbose at the end of the day, which kind of ruins the appeal, in my opinion. Otherwise, the diagnostic could just *not* trigger in this case.

**Actual Behavior**:

Codefix generates the following code, which doesn't compile, since the compiler can't infer `byte` for the constants:

```cs
// CS1929: 'ReadOnlySpan<byte>' does not contain a definition for 'Foo' and the best extension method overload 'Utils.Foo<int>(Span<int>, ReadOnlySpan<int>)' requires a receiver of type 'System.Span<int>'
s.Foo([1, 2]);
```

**Comment by huoyaoyuan** [comment]
I'd expect the overload resolution to success in this case. `s` is strongly typed as ReadOnlySpan and no implicit conversion is evolved.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/71105.
