### ISSUE TITLE
Option for IDE0305 to ignore ToList and similar calls that would result in [.., expr] format

### ISSUE THREAD

**Issue by arphox** [dotnet/roslyn#71439]
After enabling C# 12, I got several violations of the rule [IDE0305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0305).

An example:

`List<int> result = _sut.Shuffle(input).ToList();` is recommended to be:  
`List<int> result = [.. _sut.Shuffle(input)];`.

I don't like it because I believe it makes readability worse.

Based on what I have found on the IDE0305 documentation page, this is not possible to configure.

I would like to be able to better configure the enforcement of usage of collection expressions so that a code like `var x = y` (where y is an expression) never suggested to be refactored into `var x = [.. y];` because it is simply less readable.

It seems that in most cases it is affected by chained calls like .ToList, .ToArray, etc.
I strongly believe no one wants to see their multi line LINQ method chains' formats to be completely broken by this unreadable `[.. LongLinqExpression]` format.

Disabling IDE0305 _could be_ a option for me, but I'm not sure if I want it because other examples on the documentation pages look nice to have, like:
- `new[] { 1, 2, 3 }.ToList();` -> `[1, 2, 3];`
- `x.AddRange(y).Add(z).AsSpan()` -> `[x, ..y, z]`.

**Comment by CyrusNajmabadi** [comment]
As mentioned, disabling is the solution here. All those cases are the same here. A chain of fluent operations to create a collection. In all the cases, you move from explicit code saying how to make the collection, to declarative code saying *what* collection you want. 

The goal here is to move towards "what", and move away from "how".  Special casing all sorts of ops goes against that (and is a losing battle as any particular dev might want to special case their own particular handful against the hundreds of methods for this that exist today).

In all the cases you showed, the new form seems much more readable and idiomatic.

**Comment by DaveVdE-AM** [comment]
For the longest time I've been using this pattern:

```
private static List<Something> GetSomethingList()
{
    return cachedSomethings
      .Where(...)
      .OrderBy(..)
      .Select(..)
      .ToList();
}
```

How is `[.. ]` going to make this more readable and idiomatic?

**Comment by DaveVdE-AM** [comment]
The better answer of course is to add this to your .editorConfig file:

```
dotnet_diagnostic.IDE0305.severity = none
```

**Comment by CyrusNajmabadi** [comment]
@DaveVdE-AM see message above.
