### ISSUE TITLE
Generate Method isn't offered if a non-applicable extension method exists

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#71433]
Given:

```
var x = new D();
x.$$DoSomething();

public class C
{
}

public class D
{
}

public static class CExtensions
{
    public static void DoSomething(this C c)
    {
    }
}
```

With the cursor at `$$` it would be nice to be offered to generate the `DoSomething` method in `D`, but it is not. In fact there isn't even a diagnostic on `DoSomething()`, which might complicate things, but rather CS1929 is present on `x`.

**Comment by CyrusNajmabadi** [comment]
We would take a targeted community contribution here.
