### ISSUE TITLE
analyzer to detect duplicated code that can be simplified

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71436]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/analyzer-to-detect-duplicated-code-that-/10440298)._

---
I have some juniors who have written code that is hard to maintain because it contains a lot of repetition, for example

```
if (condition)
  lots of code
  option 1
  more code
else
  lots of code
  option 2
  more code
```

This can be made a lot more readable and maintainable by refactoring it to 

```
lots of code

if (condition)
  option 1
else
  option 2

more code
```

but this can be difficult when the code is several screens high, because it's difficult to see which parts are duplicated and which parts aren't.

It would be really handy if there was an analyzer that could detect this situation and warn that a method contains a lot of duplication, and it would be even better if it had a code fix that could remove the duplication correctly.

---
#### Feedback Bot on 8/14/2023, 07:19 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing as out of scope due to high complexity.  Perhaps could be picked up by copilot or ML to look for common patterns.
