### ISSUE TITLE
Add option to "collapse declaration level within #regions when collapsing to definitions"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71450]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-option-to-collapse-declaration-leve/10467729)._

---
# Current Situation

In C#, I often put local test helper classes within a region.

These are merely mock classes, and I'm not interested in their details. All I'm interested in is their sole existence.

Currently, when I collapse a source file's outline to definitions, I can still see each of the classes' members, wasting valuable screen space:

![image](https://github.com/dotnet/roslyn/assets/1408396/d8b2f425-b596-41f8-abe4-1d0d8d84117d)

So, I always need to scroll down, far away, to reach the file's main class; the one I'm actually interested in.

This situation is very cumbersome.
.

# Desired Situation

I propose to add an additional option to the `Options > Tools > Text Editor > C# > Advanced` preferences panel. This additional option should collapse all `class`/`struct`/`record` definitions **within a `#region`** to their mere declaration when the `Edit.CollapseToDefinition` Visual Studio 2022 command is executed.

In the following image I added the proposed option:

![image](https://github.com/dotnet/roslyn/assets/1408396/015ca880-2361-4a18-b8b0-413ea0e704b9)

With this option enabled, the result of `Edit.CollapseToDefinition` would be like this:

![image](https://github.com/dotnet/roslyn/assets/1408396/0a1f427b-3c51-4909-8b7c-4617a7efa482)

---
#### Feedback Bot on 9/17/2023, 07:56 PM: 

(private comment, text removed)

**Comment by sharwell** [comment]
This seems very similar in intent to the existing option "Collapse #regions when collapsing to definitions". I would recommend moving the test classes to a separate file rather than rely on such a specific new feature.

**Comment by CyrusNajmabadi** [comment]
Agreed with sam.  I don't really want to encourage this, especially with the knock off effect of having many features have to have knobs to compensate for this sort of thing.

**Comment by SetTrend** [comment]
The mock class is very local to a test class. It's only used by that class.

So, it wouldn't make sense to transfer it to a separate file and bloat the project tree.

**Comment by sharwell** [comment]
@SetTrend That's certainly one way to look at it, but there are many other examples of repositories that do split up classes into separate files even in cases where they are directly coupled (e.g. a private nested class).
