### ISSUE TITLE
Nullability warning when setting field from required property

### ISSUE THREAD

**Issue by dgolub** [dotnet/roslyn#71455]
**Version Used**: 

.NET 8

**Steps to Reproduce**:

```
public class NullabilityTest
{
    private string _requiredProp;

    public required string RequiredProp
    {
        get
        {
            return _requiredProp;
        }
        set
        {
            _requiredProp = value;
            ImplicitProp = _requiredProp;
        }
    }

    public string ImplicitProp { get; set; }
}
```

**Diagnostic Id**:

**Expected Behavior**:

The code should compile without any warnings, since `RequiredProp` must be set in order to create a `NullabilityTest` object, and both `_requiredProp` and `ImplicitProp` are set from its `set` block.

**Actual Behavior**:

The following warnings occur:

```
D:\NullabilityTest\NullabilityTest.cs(3,20,3,33): warning CS8618: Non-nullable field '_requiredProp' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
D:\NullabilityTest\NullabilityTest.cs(18,19,18,31): warning CS8618: Non-nullable property 'ImplicitProp' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
```

**Comment by jaredpar** [comment]
The `required` analysis does not work this way. It works only on the members for which it is declared, it does not go through the implementation of those members and process side effects. Given that the two members here are non-nullable and not marked as `requried` themselves, they must be set in the constructor else these warnings will occur.
