### ISSUE TITLE
Remove restrictions on lambda to expression tree conversions (CS0832, CS0834, CS0854...)

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn#7145]
The conversion of lambda expressions to expression trees has a few limitations. Some of the most annoying are:

- CS0832 An expression tree may not contain an assignment operator
- CS0834 A lambda expression with a statement body cannot be converted to an expression tree
- CS0854 An expression tree may not contain a call or invocation that uses optional arguments

Since it's possible to create expression trees with blocks and assignments using the `Expression` API, I don't see any reason why the compiler couldn't do it as well (not sure what should be done about the optional arguments, though)

I'm wondering if it would be possible to remove those restrictions, now that we have a new compiler with a clean code base?

**Comment by svick** [comment]
I think this is a duplicate of #2060.

**Comment by thomaslevesque** [comment]
@svick, you're right. I didn't find that one when I searched for similar issues...

Closing this issue now.
