### ISSUE TITLE
IntelliSense feature request: Report references, which cannot be resolved (anymore)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-feature-request:-Report-ref/10546456)._

---
When using the certain IntelliSense tags like <inheritdoc cref=...> and <see cref=...>, it can easily happen during code changes, that the referenced type/member gets renamed or that the signature changed. If that happens, obviously the reference can no longer be resolved. However there is no feedback to the developers triggering them to update the reference as well.

Adding a warning like it is done in case of missing <param> tags for some parameters or <param> tags for non existing parameters would be helpful in maintaining the documentation.

For the special case of the <inheritdoc> tag with a specified path attribute this should include verifying the path.

---
#### Feedback Bot on 12/21/2023, 07:01 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Unclear what this is asking for.
