### ISSUE TITLE
Show interface documentation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71469]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-interface-documentation/10443697)._

---
Given an interface, one writes xml comments such as <summary> ... for it and the members.

For the imlementing side show the complete doc, maybe formatted for the documented members permanently in order for the implementor to know what's beeing ment. That is do not copy the documentation, only show it withn the possibility of collapsing it.
It could work like status of the tests.

It'll be nice to have it in C# vb.net c++ (native)

---
#### Feedback Bot on 8/17/2023, 07:36 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 8/31/2023, 02:31 PM: 

(private comment, text removed)
#### Miroslaw Dobrzanski-Neumann on 8/31/2023, 11:45 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 9/1/2023, 09:06 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Clsoing out as we do have this as we make all interface impls have `<inheritdoc>` semantics anyways.
