### ISSUE TITLE
Whether a substring of a constant string within the scope of a constant should also be considered constants

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71468]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Whether-a-substring-of-a-constant-string/10530442)._

---
I don't think this error is justified in the following diagram, and the substring of a constant string under the range expression of the constant should also be considered a constant string:
![image.png](https://aka.ms/dc/image?name=B84dc23f6bb2649d389f8355139a696d1638369425281616405_20231130-200207-image.png&tid=84dc23f6bb2649d389f8355139a696d1638369425281616405)

---
#### Feedback Bot on 11/30/2023, 07:21 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  The compiler is providing the appropriate error given the language rules.  If a change to the language is desired, that would have to go through a discussion at csharplang.  One likely exists already for this.
