### ISSUE TITLE
Automatically rename file while renaming containing type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71465]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatically-rename-file-while-renaming/10450265)._

---
When I rename a file in VS2022 C# project it is possible to automatically rename a type in that file.
It would be great if I could do it vice versa: when I rename a type, file name is automatically synchronized with the new type name so I don't need to navigate to the Solution Explorer and rename the the file manually.

---
#### Feedback Bot on 8/27/2023, 07:55 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 8/31/2023, 11:56 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 8/31/2023, 11:57 AM: 

(private comment, text removed)
#### Ivan Rogatchev on 9/1/2023, 02:23 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 9/1/2023, 09:06 AM: 

(private comment, text removed)

**Comment by Cosifne** [comment]
I just verified it is fixed using Version 17.12.0 Preview 1.0 [35102.234.main]
![image](https://github.com/dotnet/roslyn/assets/24360909/2993c8f3-3c6a-4dfb-b36e-6764bb7a1d66)
![image](https://github.com/dotnet/roslyn/assets/24360909/d9e8babd-612b-434d-b8ff-17012bb5b5e7)
