### ISSUE TITLE
Allow me to designate parameters as being regular expressions to gain syntax highlighting

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71462]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Allow-me-to-designate-parameters-as-bein/1523076)._

---
Consider a method declaration such as the following:
```cs
bool IsMatch(string regex)
{
    return Regex.IsMatch(someVariable, regex, regexOptions);
}
```
Now consider the call to this method:
```cs
if (IsMatch(@"^\s*xyz"))
```
This regular expression will not be syntax-highlighted by Visual Studio.

**SUGGESTION**

1) Declare a custom attribute in the .NET class library that I can put on the parameter:
```cs
bool IsMatch([IsRegularExpression] string regex)
{
    return Regex.IsMatch(someVariable, regex, regexOptions);
}
```
2) Have Visual Studio syntax-highlight string literals that are passed to such a parameter as regular expressions.
3) Apply the same custom attribute to the actual `Regex.Match/IsMatch/Matches` methods for purposes of discoverability.

---
#### Feedback Bot on 9/7/2021, 03:08 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is what StringSyntaxAttribute already exists for.
