### ISSUE TITLE
Add individual reference viewer for getter and setter in c# property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71467]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-individual-reference-viewer-for-gett/10528226)._

---
Currently for C# property, we can see the overall references of that property.
It will be very helpful if we can view individual references of getter and setter as well.
Maybe, there can have a shortcut key combination by which users will be able to switch between overall reference vs get/set reference as keeping both at the same time could cause UX issues.

I think many developers will be helped by this feature.
Thanks.

---
#### Feedback Bot on 11/30/2023, 01:08 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
References can be filtered down by kind, allowing one to only see the reads and writes of it (so the getter and setter references respectively).
