### ISSUE TITLE
Update DocumentationCommentId.CreateDeclarationId to return null instead of throw.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#71460]
## Background and Motivation

Compiler has the current API:

```c#
public static class DocumentationCommentId
{
        /// <summary>
        /// Creates an id string used by external documentation comment files to identify declarations
        /// of types, namespaces, methods, properties, etc.
        /// </summary>
        public static string CreateDeclarationId(ISymbol symbol)
```

This is used by the IDE in different scenarios.  One of which is FindRefs/HighlightRefs.  Specifically, when searching for a symbol, we also want to see if we can find references in things like `[Suppression]` attributes (which refer to the doc-comment-id for a symbol).  However, the current impl of this method throws in undocumented ways. For example, it will often throw for synthesized symbols (like synthesized operators).  There is no easy way to determine when it will throw (it is not all synthesized operators for example), and the code is structured such that one would have to figure out the set of *not handled* cases in the 3 visitors used by this system.  Consumers trying to avoid the exception woudl effectively have to rewrite the visitation pass the doc-id system uses to determine if throwing will happen, leading to reimplementing the same system, and introducing a fragile, brittle, dependency between the two.

From discussions on bugs that have resulted from this, compiler proposed just changing the above method in the following fashion:

```diff
        /// <summary>
        /// Creates an id string used by external documentation comment files to identify declarations
        /// of types, namespaces, methods, properties, etc.
        /// </summary>
+        /// <remarks>
+        /// Returns null for symbols that do not have a corresponding id.
+        /// </remarks>
-        public static string CreateDeclarationId(ISymbol symbol)
+        public static string? CreateDeclarationId(ISymbol symbol)
```

This would trivially improve the lives of consumers here, allowing them to easily call into this api without having to deal with exceptions for totally normal symbol cases.  

This would not have any ABI issues, though it could lead to a warning for callers calling into this not expecting null.   However, such code was likely not expecting an exception either, so this will gently let them know that there are failure conditions for this api.

**Comment by 333fred** [comment]
### API Review

* Should we instead make a `TryCreate` version?
    * Can only impact cases that use exceptions for null arguments
    * Should a `Try` version throw on `null` input?
* What would we decide if we were to make the API today? Return `null` or `Try` pattern?
* We'll (narrowly) go with the pattern as proposed, altering the existing API. For new APIs, we'd probably prefer the `Try` pattern, but pragmatism drives us to modifying the existing API.

**Conclusion**: API request is approved
