### ISSUE TITLE
Symbol - Static is not bold

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71470]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Symbol---Static-is-not-bold/10539602)._

---
[regression] [worked-in:15.7 I think]
The Text Editor option in which I have set the 'Symbol - Static' option to BOLD does not work any more. Used to work perfectly.

![image.png](https://aka.ms/dc/image?name=B2adcdf13199a4fd790da1497d94bd92d638380083037952700_20231212-210502-image.png&tid=2adcdf13199a4fd790da1497d94bd92d638380083037952700)

---
#### Feedback Bot on 12/12/2023, 07:24 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as not repro.
