### ISSUE TITLE
Published package for the roslyn Microsoft.CodeAnalysis.LanguageServer feature

### ISSUE THREAD

**Issue by zaphar** [dotnet/roslyn#71474]
## Summary

Currently it looks like the only documented way to obtain the C# Dev Kit and then have it download it. The assemblies don't appear to be published publicly anywhere. Ideally this would be published in NuGet so other lsp supporting editors could use it just like Omnisharp.

## Background and Motivation

Support for the new LSP outside of VSCode. Wider usage of the LSP.  Further adoption of the C# language.

## Proposed Feature

Publish the `Microsoft.CodeAnalysis.LanguageServer` assembly publicly somewhere.

This was the only issue type I could find for this so hope it's the right category.

**Comment by zaphar** [comment]
Any chance this could get a look from someone? I would even be happy to work on it if I get some guidance. The lack of a published assembly makes the C# IDE experience much worse in non vs-code editors which sort of defeats one of the main benefits of having an LSP.

**Comment by dibarbet** [comment]
@zaphar we haven't published the packages to nuget.org, but they are available on this azdo feed, for example https://dev.azure.com/azure-public/vside/_artifacts/feed/vs-impl/NuGet/Microsoft.CodeAnalysis.LanguageServer.win-x64/overview/4.11.0-3.24318.7

The package name is `Microsoft.CodeAnalysis.LanguageServer.<platform_name>.

There is also a `Microsoft.CodeAnalysis.LanguageServer` package, but it is no longer updated should be considered deprecated.

If you're taking a dependency on the package, I recommend saving them to your own feed as versions are not kept around forever.
