### ISSUE TITLE
Smarter auto complete for aliased primitive types

### ISSUE THREAD

**Issue by Muchiachio** [dotnet/roslyn#7147]
Currently any code generated by VS removes aliasing from primitive types, it would be great if VS could be smarter and choose the same declaration as user provided one. Ima tired of rewriting long interfaces :cry:
![image](https://cloud.githubusercontent.com/assets/6647444/11505412/ea9ce976-9852-11e5-9094-1fae40922bae.png)
![image](https://cloud.githubusercontent.com/assets/6647444/11505472/2cbdf2f0-9853-11e5-8165-21b77a298ca0.png)

**Comment by lorcanmooney** [comment]
The IntelliSense issue is covered by #4585. As for the code generation cases, that generally seems to work for me - that is, it honours the settings in Options -> Text Editor -> C# -> Code Style.

I can see some cases where following the original source style (assuming the source is actually available) wouldn't be the best option. Imagine you're referencing a third-party project that uses a different style to yours. How would VS know _not_ to follow that style?

**Comment by Muchiachio** [comment]
Thanks for pointing this out, I tried searching but couldn't find your issue :)
Closing this as duplicate.
