### ISSUE TITLE
Short circuiting operations incorrectly converted to non-short circuiting version when reading from a ref

### ISSUE THREAD

**Issue by hamarb123** [dotnet/roslyn#71487]
**Version Used**: .NET 8 (SDK 8.0.100) with C# 12.

**Steps to Reproduce**:

```csharp
using System;
using System.Runtime.CompilerServices;

static bool CheckIfNonNullTrue(ref readonly bool b)
{
    return !Unsafe.IsNullRef(in b) && b;
}

Console.WriteLine(CheckIfNonNullTrue(ref Unsafe.NullRef<bool>()));
```

https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAldBKMAU2oGEB7MABygBtmyAMqCAblADGzAM4BuYsSoA2csA4c+5NgAtmEgNYBJAGYA5DjFOo+fACppmACmTNj5FxAAmFvgE9V6prAAJTEAN7E5FGUAOzkAIQAqjDSEMashtJWNrSujrCqweQAZMWq8kQAvgokeACcjjp6RmYW2XYOzq7kyanp1O25xgA8ahoAfI7B0xVAA

**Expected Behavior**:

Code equivalent to the following is emitted:
```csharp
static bool CheckIfNonNullTrue(ref readonly bool b)
{
    if (!Unsafe.IsNullRef(in b)) return b;
    return false;
}
```

Prints `false`.

**Actual Behavior**:

Code equivalent to the following is emitted:
```csharp
static bool CheckIfNonNullTrue(ref readonly bool b)
{
    return !Unsafe.IsNullRef(in b) & b;
}
```

Throws a `System.NullReferenceException`

A similar issue occurs with `||` also.

/cc @333fred

**Comment by jaredpar** [comment]
This is a bit of a gray area. C# as a language does not recognize that a `ref` can be `null` even though in reality it can be. It is very similar to the situation around `bool` where the language only recognizes `true` and `false` but there are effectively 254 other values of `true` that the language ignores. The code gen for the compiler does not attempt to take into account these other non-conforming values and this is just another case of that.
