### ISSUE TITLE
VBC crash in Double to Decimal conversion

### ISSUE THREAD

**Issue by MattGertz** [dotnet/roslyn#7148]
(MattGe posting from BHarry blog.  Please verify in C# code as well.)

Hi Brian - I found a potential serious regression in VS2015 Update 1 when it comes to VB.  It took me 2 hours of commenting out huge pieces of our codebase until I narrowed it down to one line of code that trips up vbc.exe.  If I paste the rotation code directly into Sub Main, it works.  If I make rotation local to CalculateDimensions, it works.  But if I craft the code as follows, it causes a compiler error.  All you have to do is make a VB 'Console Application'.  Doesn't matter which version of .NET you target (4, 4.5, 4.5.1, 4.6, 4.6.1).  I suspect others will run into something similar.  It's like a needle in the haystack finding the culprit.  Not sure who I should notify about this.

``` vb
Module Module1
   Sub Main()
   End Sub
End Module

Public Class TestClass
   Private _rotation As Decimal
   Private Sub CalculateDimensions()
       _rotation *= 180 / Math.PI 'This line causes '"vbc.exe" exited with code -2146232797'
   End Sub
End Class
```

(MattGe:  Workaround is to change 180 to 180.0 in the example above, indicating a problem with integer conversion in the compiler.)

**Comment by MattGertz** [comment]
Note that this fails too:

        Dim d As Double = 180 / Math.PI
        _rotation *= d / Math.PI 'This line causes '"vbc.exe" exited with code -2146232797'

It's the second line that causes the crash, so it seems that the actual problem is the conversion from Double to Decimal -- Integer has nothing to do with it.  I'm renaming the issue appropriately.

We will want to get a fix out for this quickly.

**Comment by jaredpar** [comment]
The immediate issue is occurring in the [stack scheduler](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/CodeGen/Optimizer/StackScheduler.Analyzer.vb#L1242) 

``` vb
Return top.Item2 = If(Not local.IsByRef, ExprContext.Value, ExprContext.Address) AndAlso
  top.Item1.Kind = BoundKind.Local AndAlso
  DirectCast(top.Item1, BoundLocal).LocalSymbol = local
```

In this scenario `top.Item1` is `Nothing` and hence we NRE on that line.  The value `Nothing` appears to be explicitly legal for `Item1` given [this line](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/CodeGen/Optimizer/StackScheduler.Analyzer.vb#L589)

``` vb
PushEvalStack(Nothing, ExprContext.Address)
```

**Comment by agocke** [comment]
LGTM

**Comment by agocke** [comment]
I also agree with this fix as opposed to just adding a `null` check -- this approach seems no riskier and more robust.

**Comment by jaredpar** [comment]
After digging into the issue here we determined it will reproduce under the following circumstance:

- Compound Operator
- Left side is an instance field or array element of type `Decimal`
- Right side is an expression of type `Double` or `Single`

**Comment by AlekseyTs** [comment]
@agocke Please verify.

**Comment by jaredpar** [comment]
For anyone effected by this bug you can work around it by doing the following:

- Open the affected project in Visual Studio
- Open the Package Manager Console (Tools -> NuGet Package Manager -> Package Manager Console) 
- Run: `Install-package Microsoft.Net.Compilers -version 1.1.1`

That will install a patched version of the compiler.

**Comment by kamranayub** [comment]
I just ran into this today. Will try installing the patched version to see if that fixes it.

**Comment by jaredpar** [comment]
@kamranayub do you have a solution you can share out so we can look into this?  We've been able to verify that particular bug is fixed in that NuGet (manual testing and customer machines).  I'ts possible you are running into a different problem.

**Comment by kamranayub** [comment]
The project I ran into for this isn't a primary thing I work with and I
remember it has a ton of interdependencies. I can try to isolate the error
for the project and see if I can provide more info.
