### ISSUE TITLE
OutOfMemoryException while fixing all violations in a solution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#7149]
We received a report of a failure to apply a "fix all" in StyleCop Analyzers. We narrowed the situation down to a regression in the way Visual Studio 2015 Update 1 interacts with Roslyn 1.1. The problem does not occur in Visual Studio 2015 RTM, and the problem does not occur when we use the Roslyn 1.1 APIs from a command line application.

Steps to reproduce:

1. Clone DotNetAnalyzers/StyleCopAnalyzers
1. Check out commit DotNetAnalyzers/StyleCopAnalyzers@987697122424e109e965abc47185b82777990839
1. Restore NuGet packages
1. Replace all `}(?=\r?$)` in **\*.cs** in the solution with a `}` followed by two spaces (Markdown formatting wasn't working for the spaces here) - Regular expressions enabled
1. Restart Visual Studio
1. Fix all violations of SA1028 in solution

Expected result:

Visual Studio 2015 RTM fixed all violations in 30 seconds (20 seconds to bring up the preview, then 10 to apply changes). Visual Studio 2015 Update 1 should do the same or better.

Actual result:

Visual Studio 2015 Update 1 crashes.

Reference:

See DotNetAnalyzers/StyleCopAnalyzers#1877 for the original report.

**Comment by balajikris** [comment]
It looks like this is fixed by #7784 -- need a dump to be sure though.

**Comment by DustinCampbell** [comment]
Is suspect this is probably fixed too. @sharwell -- please let us know if this is not fixed by the VS 2015 Update 2 CTP.
