### ISSUE TITLE
Abstract/virtual events declared in C# should not be overridable in VB, because VB does not support virtual events

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#715]
Ported from TFS WorkItem: **529732**

------------------------------

**Repro Steps:**

**Affected Branch:** <br> **Affected Build:** <br> **Affected Product Language:** <br> <br>**Steps to reproduce:**<br> <br> 1.

------------------------------

**Revisions:**

1) Created By Vladimir Reshetnikov (11/28/2012 7:18:19 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 14225 (rev 1);)

------------------------------

2) Edited By Kevin Pilch-Bisson (11/28/2012 7:18:20 PM)

Did we make an explicit call about this?

(TFS Integration from 'DevdivProjects-Roslyn' Id: 14225 (rev 2);)

------------------------------

3) Edited By Kevin Pilch-Bisson (11/28/2012 7:18:21 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 14225 (rev 3);)

------------------------------

4) Edited By Dustin Campbell (11/28/2012 7:18:21 PM)

(TFS Integration from 'DevdivProjects-Roslyn' Id: 14225 (rev 4);)

------------------------------

5) Edited By Ravi Chande (2/13/2015 3:07:18 PM)

Still repros, nullrefs if you try to insert the event.

------------------------------

6) Edited By Ravi Chande (2/13/2015 3:09:02 PM)

Probably should fix this because it crashes.

------------------------------

7) Edited By Kevin Pilch-Bisson (2/19/2015 1:59:10 PM)

Please port to GitHub.

------------------------------

**Comment by rchande** [comment]
Can you verify this @VladimirReshetnikov ?

**Comment by Pilchie** [comment]
Should still be closed, we just need someone to Verify.

**Comment by Pilchie** [comment]
I verified this is fixed.
