### ISSUE TITLE
IDE0004 erroneously says a collection expression cast is redundant

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#71511]
**Version Used**: 
Version 17.9.0 Preview 3.0 [34431.11.main]

**Steps to Reproduce**:
```C#
public class C
{
    public IEnumerable<int> M1() => [1, 2, 3, 4];
    public IEnumerable<int> M2() => (int[])[1, 2, 3, 4];
}
```

**Expected Behavior**:
No diagnostic.

**Actual Behavior**:
IDE0004 fires a diagnostic on the `(int[])` cast saying it's redundant, but the presence of that cast actually changes behavior / codegen.
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAFgG4BYAKHPQGZcAmbAYXIG9zt3cb8qAeWAFwB82ALJ4AFAEpsAXmEBtPHGy1lVZQQC6pMh0648vAcJG0ps4eIHzNkxctXZ12LToC+QA==)
```C#
public class C
{
    public IEnumerable<int> M1()
    {
        int[] array = new int[4];
        RuntimeHelpers.InitializeArray(array, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
        return new <>z__ReadOnlyArray<int>(array);
    }

    public IEnumerable<int> M2()
    {
        int[] array = new int[4];
        RuntimeHelpers.InitializeArray(array, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
        return array;
    }
}
```
Note the `return new <>z__ReadOnlyArray<int>(array)` vs  `return array`.

(Separately, I still wish we didn't forcibly allocate a wrapper object in this case.)

**Comment by CyrusNajmabadi** [comment]
Def a bug. Very strange.  On it
