### ISSUE TITLE
IDE0028 Collection Simplification for List<> with optional values causes CS0173

### ISSUE THREAD

**Issue by mwmccallum** [dotnet/roslyn#71527]
**Version Used**: 
VS2022 with net8.0 framework
IDE0028 Collection Simplification for `List<KeyValuePair<string,string>>` with optional values causes CS0173

In my case I am using SqlParameter in place of `KeyValuePair<>`, but I changed it for the this issue to to demonstrate in SharpLabIo.

[Starting Code](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWoGYEBMcAwnAN5ZxUL5TJwCyAFAJTmVY6LwAOAhgCc+AW0QA1PgBsArgFM4AXjgAiAG5S5iZRkxJegkQQkz5StRtkFtXfUOG5jcxSvUnc13dzj87yR6bgAO2lJSR0sABkASwBnABcAHgBpWQBPfwAFPiiBBL0AGj0APiK4JLEM6PjnQNkAdzhWLApMKlqGlPSLLJy87kLuUqYVKCgeAH0fEURxgGMAe2BZZXzvA1F/OBZ8yiD6srTM7NyC4saRscn1gjnF5dWp4SMLLZ3WvY7D7uO+mAGYIYXCaPXC3JYrNZ2BwvFhYAC+OiiADNzo8/C8AIRKYKhLa7cqVWJxAB0AEFgMBzu0Dl0TD0Tv0zsNlKNgetkGD7pCROiTFstuFMHD4UA==)

[Simplified Collection](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWoCZE4DMCucAwnAN5Zy0LFTJwCyAFAJRU6LwAOAhgCd+AW0QA1fgBsArgFM4AXjgAiAG7T5iFRkxI+Q0bkmyFy9Zrm4d3A8JGET8pao2nCNvTzgD7yJ2ZwAHYyUlK6WAAyAJYAzgAuADwA0nIAngEACvzRgon6ADT6AHzFcMnimTEJSlgA2jTBcgDu5elZOXmFJXCsqlBQvAD6vqKIQwDGAPbAcioFPoZiAXDsBY1BLW0Zltm5+TxFPGV9KgPDoyK4kzNzC5fGlqvrmLSbrak7pntdhz2n5xGS0IN1m80W9kcTzWjQAdLCIaJ/E8AITKEJhOAAfjgdSaH3au06BxgRxgJ36gyBflBd0RImRplWcAAunAQLiWS8Wbo6HAAL5YflAA===)

```
List<SqlParameter> SQLParams = new ()
{
  new SqlParameter ( "@p_param1_flag", isParam1 ),
  new SqlParameter ( "@p_param2_code", param2Value ),
  new SqlParameter ( "@p_param3_code", param3Value )
};
if ( param4Value != null )
  SQLParams.Add ( new SqlParameter ( "@p_param4_code", param4Value ) );
```

Collection Simplification results in this code:

```
List<SqlParameter> SQLParams =
[
  new SqlParameter ( "@p_param1_flag", isParam1 ),
  new SqlParameter ( "@p_param2_code", param2Value ),
  new SqlParameter ( "@p_param3_code", param3Value ),
  .. param4Value != null ? [ new SqlParameter ( "@p_param4_code", param4Value ) ] : [],
];
```

This is an generates CS0173 Compiler Error for the last line.
"Type of conditional expression cannot be determined because there is no implicit conversion between 'collection expressions' and 'collection expressions'"

I have to add the following #pragma statements around the new () command like this:

```
#pragma warning disable IDE0028 // Simplify collection initialization
List<SqlParameter> SQLParams = new ()
{
  new SqlParameter ( "@p_param1_flag", isParam1 ),
  new SqlParameter ( "@p_param2_code", param2Value ),
  new SqlParameter ( "@p_param3_code", param3Value )
};
#pragma warning restore IDE0028 // Simplify collection initialization
if ( param4Value != null )
  SQLParams.Add ( new SqlParameter ( "@p_param4_code", param4Value ) );

```

I demonstrated this issue with `KeyValue<string,string>`, to ensure that it was not specific to SqlParameter.

I have thousands of lines of code with SQLParams list, which is impractical to add the #pragma warrning around them all. I have had to disable Code Cleanup. I have tried to remove "Apply object/collection initialization preferences", which seems like it would be the correct item, but it does not change situation.

Thanks, Mike

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70173.

**Comment by mwmccallum** [comment]
I see that this was put into 17.9 P1, will it be cherry picked into a 17.8.x release?

**Comment by CyrusNajmabadi** [comment]
@mwmccallum Nope.  These sorts of minor fixes just flow into the next version of VS.  We only cherry-pick critical issues (like crashes impacting lots of people).

**Comment by mwmccallum** [comment]
Thanks for your response. I am downloading 17.9 preview now.
