### ISSUE TITLE
Go to definition doesn't mark the selected symbol the first time but just opens the source file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71568]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-to-definition-doesnt-mark-the-select/10555321)._

---
[severity:It bothers me. A fix would be nice]

_Environment_
I have a WinForms-.NET-FX 4.8 VB. NET-project in Visual Studio Version 17.9.0 Preview 2.1 on a 64-bit Win10 PC, but it also happens in a WinForms-.NET 7.0 VB. NET-project.

**Problem**
The function "Go to definition" for a method or a class doesn't mark the selected symbol the first time but just opens the source file, especially in new opened solutions or after deleting the .vs-directory of the solution.

**Description**
If I right click on a method and click "Go to definition" or alternatively press the F12 button (default assignment for the mentioned "Go to definition" function), it _can_ happen, that I see the source file of the method or a VS-created variant of it, but the caret is at the beginning of the source file,  not at the position of the method I wanted to see. If I go back to my code and repeat the procedure, the caret will be at the position I expected.

**Video**
In the following video I want to see the definition of the method `ContainsOneOf`. I click on the code, select the function "Go to definition" in the context menu, Visual Studio loads the source file, but doesn't show the method `ContainsOneOf`. If I go back to my code and again select the funtion "Go to definition" in the context menu, Visual Studio shows correctly the method I have selected.

![B758bfd9d69d14b609efd9f1da5083cae638403451704302679_GoToDefinition](https://github.com/dotnet/roslyn/assets/1408396/c5d62819-14b3-4e95-b725-bac4ea091e46)

**Consequences**
I'm annoyed - just a little bit.

---
#### Feedback Bot on 1/8/2024, 08:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
Looks like related to metadata as source.

**Comment by CyrusNajmabadi** [comment]
Closing out as this was a bug in async file open that platform fixed.
