### ISSUE TITLE
[Source Generator] `Microsoft.CodeAnalysis.ISymbol.Name` is missing `@`

### ISSUE THREAD

**Issue by ThaDaVos** [dotnet/roslyn#71577]
**Version Used**: 
Visual C# Compiler version 4.9.0-2.23613.5
DotNet 8.0.100

**Steps to Reproduce**:

1. Create a Source Generator which can access method parameters
2. Use a parameter named as `@event` (as one cannot use `event`
3. Check through debugging that `Microsoft.CodeAnalysis.ISymbol.Name` is missing the `@` in the parameter name

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
The `@` to be included in the name, only `ToDisplayString()` seems to include it

**Actual Behavior**:
The `@` is missing in the name of the parameter

**Comment by ThaDaVos** [comment]
Still think it's a bug, as it's part of the name of the parameter too, even when it's an escape character - it's there for a reason, so not being able to get it through Source Generation will limit what one can do - take the example of a parameter called `event`, this is invalid as `event` is reserved, so the code has to include the `@`

**Comment by sharwell** [comment]
> ... as it's part of the name of the parameter too ...

It's not part of the name of the parameter. The symbol name for the local variables above are `x` and `y`. Even though `y` is declared in source as `@y`, its name is `y`.

Here's an example of an extension you can use to add `@` when necessary:
https://github.com/dotnet/roslyn/blob/9fb270caa64771f3ab9ad9abad1da840f9acaf3b/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/StringExtensions.cs#L13-L29

It would be invoked as `symbol.Name.EscapeIdentifier()` (I'm not a fan of this being an extension on `string`, but it works for an example).

**Comment by CyrusNajmabadi** [comment]
@ is not part of the name at the semantic/symbolic level. It's only part of the name at the syntactic level. Since you are asking a symbolic question, this is by design. 

If you want to know how the code was actually written syntactically, you'll need to go back to Syntax to check.
