### ISSUE TITLE
Flaky stress test in VB suite.

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7159]
The following test in the VB suite fails erratically with an `OutOfMemoryException` on `builder.ToString()`.

Didn't we already fix this in the C# suite? Why didn't we do it here as well?

```vb
    <WorkItem(2867, "https://github.com/dotnet/roslyn/issues/2867")>
    <Fact>
    Public Sub TestBinary()
        ' use a fixed seed so the test Is reproducible
        Dim random = New System.Random(12345)
        Const n As Integer = 40 * 1000 * 1000 ' 40 million "character"s
        Dim builder = New System.Text.StringBuilder(n + 10)
        For i As Integer = 0 To n - 1
            builder.Append(ChrW(random.Next(&HFFFF)))
        Next

        Dim source = builder.ToString()
        Dim tree = VisualBasicSyntaxTree.ParseText(source)

        Assert.Equal(source, tree.ToString())
        Assert.Equal(Syntax.InternalSyntax.Scanner.BadTokenCountLimit, tree.GetDiagnostics().Where(Function(d) d.Code = ERRID.ERR_IllegalChar).Count())
    End Sub
```

**Comment by jaredpar** [comment]
Guessing Ty didn't know about the VB suite when he fixed the C# one (I didn't :frowning:).  Probably can just issue the same fix here.

**Comment by TyOverby** [comment]
Oh yep, same issue; I probably should have checked for a corresponding test on the VB side.

I solved the last one by using unsafe, but that's not possible in VB.  How should I factor that common pattern out?

**Comment by jaredpar** [comment]
@TyOverby both of the compiler suites reference the TestUtilities library which is written in C#.  You could move a helper method into that type which constructs the string with `unsafe` code and call it from both suites.

**Comment by TyOverby** [comment]
@jaredpar Sounds good, thanks!
