### ISSUE TITLE
Update roslyn syntax list constructs to support collection expressions.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#71596]
## Background and Motivation

Current roslyn syntax lists (SyntaxList, SeparatedSyntaxList, SyntaxTriviaList, SyntaxNodeOrTokenList, SnytaxTokenList) can only be constructed by using SyntaxFactory.  This is extremely verbose (needing to prefix with SYntaxFactory) and annoying.  To make a list containing one element, you need to also use SyntaxFactory.SingletonXXXList, but for zero to N values you use SyntaxFactory.List(someCollection).

All these apis should be updated to support collection expressions by way of the CollectionBuilderAttribute.

## Proposed API

```diff
+ public static class SyntaxList
+ {
+    public static SyntaxList<TNode> Create<TNode>(ReadOnlySpan<TNode> nodes) where TNode : SyntaxNode
+ }

+ [CollectionAttribute(typeof(SyntaxList), "Create")]
public readonly struct SyntaxList<TNode>
{
}
```

This would make things much nicer.  For example:

```
// Empty list:
Block(openBrace, [], closeBrace)

// Singleton list:
Block(openBrace, [embeddedStatement], closeBrace);

// Joining lists:
Block(openBrace, [.. initialStatements, .. newStatements], closeBrace);

// etc.
```

--

Note: because of target-typing, you get major simplification.  For example, instead of having to write:

```c#
SyntaxFactory.BaseList(SyntaxFactory.SingletonSeparatedList((BaseTypeSyntax)SyntaxFactory.SimpleBaseType(typeName))); // or
SyntaxFactory.BaseList(SyntaxFactory.SingletonSeparatedList<BaseTypeSyntax>(SyntaxFactory.SimpleBaseType(typeName)));
```

You can just write:

```c#
SyntaxFactory.BaseList([SyntaxFactory.SimpleBaseType(typeName)]);
```

So much simpler to write *and* read.

**Comment by 333fred** [comment]
### API Review

* We love it.
* It will allow `params` usage for these types.
* Let's make sure we get all of our constructible list types, not just `SyntaxList`.
* We'll confirm with the runtime team about recommended naming conventions to make sure that we're naming this inline with the BCL.

**Conclusion**: Approved.

**Comment by CyrusNajmabadi** [comment]
Checked with Stephen on the naming here.
