### ISSUE TITLE
IDE0305 produces invalid code for Add/AddRange

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn#71607]
**Version Used**: 8.0.100

**Steps to Reproduce**:

```
List<int> numbers = new List<int> { 1, 2 };

if (true)
    numbers.Add(3);

numbers.AddRange([3,4]);
```

[SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWAyBLAZwBcAePAOyID45yBXAWwCMBTAJwLgF5aWB3OPmJlKNAN5xEAGjgAmOAF8M2THgBmcABRE2dFgEoscY7UasOAOgCCwYJoDM+5VnrN2Ba7YBKAQ3IBzFk0AbXspZABdJywgA===)

**Diagnostic Id**: IDE0305

**Expected Behavior**:

Generates code that compiles.

**Actual Behavior**:

Generates code that doesn't compile:

```
List<int> numbers = [1, 2, .. true ? [3] : [], .. [3,4]];
```

> error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'collection expressions' and 'collection expressions'
error CS9176: There is no target type for the collection expression.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70173

**Comment by MisinformedDNA** [comment]
Using the latest compiler (9 Jan 2024) in SharpLab, there is still a [scenario](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEAMACdBGAFgG4BYAKHIBkoBnAFwB5Y6A+bGAVzGAFMAnGtgC87HgHcAFAEpsAb2x442AEzYAvqTKdu/GgDoAgggQAlCDADmPCQG0CSgKwBdKZqA===) that fails:

```
List<int> numbers = new() { 1, 2 };
numbers.AddRange([4, 5]);
```

results in 

```
List<int> numbers = [1, 2, .. [4, 5]];
```

> error CS9176: There is no target type for the collection expression.

**Comment by CyrusNajmabadi** [comment]
Yup.  reactivating.  will fix. thanks!
