### ISSUE TITLE
Provide a public Nagivation API

### ISSUE THREAD

**Issue by lsoft** [dotnet/roslyn#71627]
## Background and Motivation

I am a VSIXer. As a VSIXer I'm wokring on the top of VS API, and in 90% time at the top of Roslyn API too. Often VSIXer need to open random documents inside VS. I hope everyone agreed that this is a common task. There is not a problem to open document via VS API: `IVsUIShellOpenDocument.OpenDocumentViaProject`. But there is one exception to this rule.

We have a source generated documents in .NET ecosystem.

As @sharwell noted in [this discussion](https://github.com/dotnet/roslyn/discussions/71532) there is 2 ways to achieve the  goal.

The first way is to imitate the existing Roslyn logic and write everything once again: opening the doc (via temp file with the body, or - like Roslyn - via empty file), paste the body into editor, set it as readonly, put gold bar ('file war source generated ...') etc etc. But it does not make sense! First, if Roslyn changed the representation of SG-documents, the VSIXer need to follow the Roslyn way and recode his\her VSIX. Second, we already have this logic in the process RAM, inside of Roslyn dlls, repeat the logic again in VSIX code is going against of all history of software development industry!

The second way is to reuse Roslyn logic via reflection, as performed [here](https://github.com/lsoft/SyncToAsyncExtension/blob/main/Extension/Helper/VisualStudioDocumentHelper.cs#L131). As @CyrusNajmabadi  [noted](https://github.com/dotnet/roslyn/discussions/71532#discussioncomment-8077592) this is very fragile scenario.

So, if VSIXer need to open SG document, or needs a logic to open any kind of Roslyn documents, then his\her is in a trap. No good way exists.

## Proposed API

I understand complications about public API and evolution. I'm not asking much.

```diff

+namespace Microsoft.VisualStudio.PublicAPI
+{
+    public static class Navigation
+    {
+        public static async Task<bool> NavigateToAsync(
+            DocumentId documentId,
+            TextSpan textSpan,
+            CancellationToken cancellationToken
+            )
+        {
+            Microsoft.VisualStudio.ComponentModelHost.IComponentModel componentModel = ...;
+
+            var workspace = (Workspace)_componentModel.GetService<VisualStudioWorkspace>();
+            var navigationService = (VisualStudioDocumentNavigationService)componentModel.GetService<VisualStudioDocumentNavigationService>();
+
+            var location = await navigationService.GetLocationForSpanAsync(
+                workspace,
+                documentId,
+                textSpan,
+                cancellationToken
+                );
+            if (location is null)
+            {
+                return false;
+            }
+
+            var result = await location.NavigateToAsync(
+                new NavigationOptions(),
+                cancellationToken
+                );
+
+            return result;
+        }
+    }
+}
```

Proposed signature: 

```diff
+            DocumentId documentId,
+            TextSpan textSpan,
+            CancellationToken cancellationToken
```

is very general and unlikely will changed in the future.

## Usage Examples

VSIXer will easily call this method to open any kind of Roslyn document:

```C#
await Microsoft.VisualStudio.PublicAPI.Navigation.NavigateToAsync(...);
````

## Alternative Designs

For example, instead of creaing a new class, existing classes can be made `public`.

We will love any kind of this API, because we are out of good options now.

## Risks

To have an additional public API which need to be supported in the future. I hope the proposed API is not a big deal for Roslyn team, and pros are bigger than contras.

I understand clearly that Roslyn and VSIX development are different areas, but Roslyn is positioned not only as compiler, but as a service. So, the proposed API serves to provide functions to its users. Helping to easily develop VS extensions is a good investment for our ecosystem.

Vsix community is small, and almost voiceless. Here is one our voice. Please support VSIX development.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement.  If this needs to happen, please move forward on this @jasonmalinowski , or assign to someone who will own this in an appropriate milestone.
