### ISSUE TITLE
CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. in Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj

### ISSUE THREAD

**Issue by alexgav** [dotnet/roslyn#71645]
**Version Used**: 
Version 17.10.0 Preview 1.0 [34512.86.main]

**Steps to Reproduce**:

1.  Enlist into Roslyn repo
2. Restore.cmd
3. Build.cmd

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

CS8103: Combined length of user strings used by the program exceeds allowed limit. 

**Expected Behavior**:

Able to build

**Actual Behavior**:

Build fails. 

**Workaround**

Comment out some tests, e.g. comment out entire class roslyn\src\Compilers\CSharp\Test\Emit\Emit\EmitMetadataTests.cs

**Comment by RikkiGibson** [comment]
The string limit AFAIK is a trait of the .NET assembly format. So I would expect this to also occur in CI, but it doesn't. e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=528312&view=results (which has test failures, but not build failures).
