### ISSUE TITLE
"Extract interface" generates invalid code for read-write properties

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#71640]
**Version Used**: VS 17.8.4

**Steps to Reproduce**:

Open the lightbulb menu on the type, select "Extract interface…" and confirm the dialog.

```csharp
struct S
{
    public int I { get; set; }
}
```

**Expected Behavior**:
Valid code is generated.

**Actual Behavior**:
The unexpected keyword "readonly" is placed in front of the "get" keyword, making the code syntactically invalid.

```csharp
interface IS
{
    int I { readonly get; set; }
}
```

**Comment by sdelarosbil** [comment]
Hey, can I take this one?

**Comment by CyrusNajmabadi** [comment]
@sdelarosbil definitely.
