### ISSUE TITLE
Update code fix for SYSLIB1054 to use a collection expression

### ISSUE THREAD

**Issue by Captain-Quack** [dotnet/roslyn#71647]
## Background and Motivation

The code fix for [SYSLIB1054](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib1050-1069) generates an attribute that contains the now outdated `new Type[] { ... }` syntax. This should be replaced with a collection expression instead. 

## Proposed API

```diff
class C 
{
    [LibraryImport(...)]
-   [UnmanagedCallConv(CallConvs = new Type[] { ... })]
+   [UnmanagedCallConv(CallConvs = [...])]
    public static partial void DoAThing(); 
}
```

## Usage Examples

After the fix, this code:

``` C#
/// <summary>
/// Returns if the application's window is currently fullscreen
/// </summary>
[DllImport("cool_name_here", CallingConvention = CallingConvention.Cdecl)]
public static extern bool IsWindowFullscreen();
```
Will change to the following:

``` C#
/// <summary>
/// Returns if the application's window is currently fullscreen
/// </summary>
[LibraryImport("cool_name_here")]
[UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
public static extern bool IsWindowFullscreen();
```

**Comment by CyrusNajmabadi** [comment]
These are not part of Roslyn. I think dotnet/runtime is the right place. But I can't seem to move it right now. Can you reopen there?

**Comment by Captain-Quack** [comment]
Yes, sorry about that.
