### ISSUE TITLE
unexpected changes to scoping rules

### ISSUE THREAD

**Issue by piersh** [dotnet/roslyn#7166]
I'm seeing a difference in the scoping rules between c#5 and c#6 that i haven't seen any documentation for. maybe it's a bug?

source:
````
class C
{
	int F;

	void M()
	{
		if (F == 0)
		{
			var F = 1;
		}
	}
}
````

VS 2013 (csc 12.0.40629.0) gives:
````
a.cs(7,3): error CS0844: Cannot use local variable 'F' before it is declared. The declaration of the local variable hides the field 'C.F'.
````

whereas
VS 2015 (csc 1.0.0.50618) gives:
````
a.cs(9,8): warning CS0219: The variable 'F' is assigned but its value is never used
a.cs(3,6): warning CS0649: Field 'C.F' is never assigned to, and will always have its default value 0
````

**Comment by gafter** [comment]
Yes, we now allow you to *reference* something by a simple name and also *declare* a local with that simple name in a nested scope. See https://github.com/dotnet/roslyn/commit/23891e378a5d98c70971a69794ee55a9948680bc#diff-c5e9174606148de3a162d2be276d575c
