### ISSUE TITLE
CS8073 | Analyzer says the expression is always false, but I say otherwise

### ISSUE THREAD

**Issue by cemahseri** [dotnet/roslyn#71661]
**Version Used**: Visual Studio 2022 17.8.4+34408.163, C# 12, 4.8.0-7.23572.1 (7b75981c)

**Steps to Reproduce**:

```csharp
var tcpClient = new TcpClient();
tcpClient.Dispose();

Console.WriteLine(tcpClient.Client == null);
```

**Diagnostic Id**: CS8073

**Expected Behavior**:

The analyzer should never report the expression as always false, or it should be false.

**Actual Behavior**:

The analyzer reports the expression as always false, but the expression is true.

**Comment by Trojaner** [comment]
https://github.com/dotnet/runtime/issues/97050

**Comment by Trojaner** [comment]
https://github.com/dotnet/runtime/issues/97050#issuecomment-1894669406

I guess it's up to the analyzers to check if the object was disposed before and then ignore nullability warnings?

**Comment by huoyaoyuan** [comment]
I tried with VS17.8.4 and no CS8073 reported for your example. CS8073 is correctly enabled for following sample:
```csharp
        DateTime x = default;

        Console.WriteLine(x == null);
```

**Comment by Cosifne** [comment]
Using VS Version 17.12.0 Preview 1.0 
The problem doesn't repro.
