### ISSUE TITLE
Use C# 11 feature in my source code, but the build command: `dotnet build -p:langversion=10` built successfully.

### ISSUE THREAD

**Issue by iouzzrj** [dotnet/roslyn#71678]
**Version Used**: .NET SDK version: 8.0; csc.dll version: 4.8.0-7.23572.1

**Steps to Reproduce**:

1. `dotnet new console`
2. Use C# 11 feature raw string literals in Console.WriteLine().
3. Use: `dotnet build -p:langversion=10`, build failed because the raw string literal is not available in C# 10.
4. Change to: `dotnet build`, build successful.
5. Change back to: `dotnet build -p:langversion=10`, build successful. This is confusing. I have to use `dotnet clean` and then `dotnet build -p:langversion=10` to let the build failed again.

**Expected Behavior**: I am using C# 11 feature in my source code, the `dotnet build -p:langversion=10` should fail to build.

**Actual Behavior**: I am using C# 11 feature in my source code, the `dotnet build -p:langversion=10` built successfully.

**Comment by jasonmalinowski** [comment]
> I have to use dotnet clean and then dotnet build -p:langversion=10 to let the build failed again.

This is likely because the build is considered up to date -- MSBuild doesn't have logic to realize we need to rerun in this case.
