### ISSUE TITLE
Unable to go-to-def on a `ValueTuple`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#71680]
**Version Used**:
VS 17.8.4

**Steps to Reproduce**:
```cs
using System;
using System.Runtime.CompilerServices;

ITuple iTuple;
Tuple<int, int> tuple;
ValueTuple<int, int> valueTuple;
```
Execute 'Go to definition' on `ITuple`, `Tuple` and `ValueTuple`

**Expected Behavior**:
I can go-to-def on all 3 types

**Actual Behavior**:
go-to-def works fine for `ITuple` and `Tuple`, but fails for `ValueTuple` (you get a popup saying that it isn't possible to go-do-def where the cursor is)

**Comment by victor-pogor** [comment]
@CyrusNajmabadi thanks 😉

Would be this the [right](https://github.com/dotnet/roslyn/blob/60eaadf5c5e8782e43ed2455c80380d6243eac8b/src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs#L178-L193) place to handle the tuple locations?

```diff
private static ImmutableArray<DocumentSpan> TryGetSourceLocations(ISymbol definition, Solution solution, ImmutableArray<Location> locations, bool includeHiddenLocations)
{
if (definition.Kind == SymbolKind.Namespace)
{
    return [];
}

+ if (definition.IsTupleType() && definition.Locations.IsEmpty)
+ {
+     locations = definition.OriginalDefinition.Locations;
+ }

using var sourceLocations = TemporaryArray<DocumentSpan>.Empty;

foreach (var location in locations)
{
    if (location.IsInMetadata)
    {
        return default;
    }

// ...
```

This method is used for building the [DefinitionItem](https://github.com/dotnet/roslyn/blob/60eaadf5c5e8782e43ed2455c80380d6243eac8b/src/Features/Core/Portable/FindUsages/DefinitionItem.cs#L28C37-L28C51).

I have a [draft commit](https://github.com/victor-pogor/roslyn/commit/fefc1f604015b7271fec6fe577d2b8c935da675f) that can give an idea of what I tried.

**Comment by CyrusNajmabadi** [comment]
Either there, or maybe in whoever calls this when they grab the locations in the first place?

**Comment by victor-pogor** [comment]
To be honest, another candidate place I was looking for was adding this special case when the definition item is built. I saw that the symbol is already replaced with the original definition so we have the metadata location.

```diff
 private static DefinitionItem ToDefinitionItem(ISymbol definition, ImmutableArray<DocumentSpan> sourceLocations, ImmutableArray<ClassifiedSpansAndHighlightSpan?> classifiedSpans, Solution solution, FindReferencesSearchOptions options, bool isPrimary)
{
+   // Good thing cause the current symbol is replaced with the original definition
+   // so the tuple location is preserved
    if (!definition.IsTupleField())
    {
        // In an earlier implementation of the compiler APIs, tuples and tuple fields symbols were definitions
        // We pretend this is still the case
        definition = definition.OriginalDefinition;
    }

    // ...

+  // Creates a metadata definition.
+  // The immutable array is default when location.IsInMetadata == true, this logic is in the previous approach.
+  // Maybe changing to something like this?
-   if (sourceLocations.IsDefault)
+   if (sourceLocations.IsDefault || definition.IsTupleType())
    {
        return DefinitionItem.CreateMetadataDefinition(tags, displayParts, nameDisplayParts, solution, definition, properties, displayIfNoReferences);
    }

    if (sourceLocations.IsEmpty)
    {
        return DefinitionItem.CreateNonNavigableItem(tags, displayParts, DefinitionItem.GetOriginationParts(definition), properties, displayIfNoReferences);
    }

    // ...
```

This case also works and generates the definition item as expected:
![image](https://github.com/dotnet/roslyn/assets/24962085/c96474c4-120b-41ce-bef0-3a713cf1d624)

**Comment by CyrusNajmabadi** [comment]
that seems pretty reasonable to me.

**Comment by victor-pogor** [comment]
> that seems pretty reasonable to me.

Could you assign please this issue to me?

**Comment by CyrusNajmabadi** [comment]
Sure :)
