### ISSUE TITLE
C# Interactive shortcut UpArrow doesn't appear to work in VS 2015 Update 1

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn#7170]
When pressing the UpArrow in C# Interactive, the cursor moves up to line above. I thought it would cycle through the history similar to Python Interaction.

The help also states this functionality.
 At the end of the current submission, replace the current submission with a previous submission. Elsewhere, move the cursor up one line.

Anyone else seeing this in v1.1

**Comment by KevinH-MS** [comment]
It looks like this language was introduced with commit 96b34e91(but it's incorrect, because nobody ever implemented what it describes).

To navigate history, you must use Alt+UpArrow and Alt+DownArrow.

I'll correct the ```#help``` text.

**Comment by KevinH-MS** [comment]
Looks like there's an issue tracking the implementation of "SmartUpDown" (#5125).

I've gone ahead an moved that into the current Milestone.

**Comment by shaggygi** [comment]
Thank you for reviewing.  Have a good holiday break :)

**Comment by KevinH-MS** [comment]
@shaggygi same to you! :smile:

**Comment by KevinH-MS** [comment]
Actually, I realized the help text is the way it is because the command implementation is shared with Python (and it accurately reflects the behavior there).  Therefore, I'm going to leave the help text as is and we'll just make it work in C#.

Closing this issue (implementation of new behavior will be tracked by #5125).

**Comment by GSPP** [comment]
`Alt+UpArrow` does not work either. The only combination that works is `Ctrl+Alt+UpArrow` in VS2015 Update 3.

**Comment by tmat** [comment]
@GSPP Is that clean VS or do you have any extensions installed?

**Comment by GSPP** [comment]
@tmat just tested in VS17 15.1 with Resharper and Power Commands as the only seemingly relevant addons.

**Comment by tmat** [comment]
@GSPP Have you tried to disable them?
