### ISSUE TITLE
Hide duplicates caused by "starred" items in IntelliSense

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/roslyn#71744]
## Summary

These duplicates make it more difficult to choose the correct item.

![image](https://github.com/dotnet/roslyn/assets/16783987/a3e93e10-c097-4371-addf-1c6c658f2b54)

## Background and Motivation

This happens frequently because whenever you type a few characters, a long list of suggestions almost always is narrowed down to a few items.

## Proposed Feature

If a suggestion is "preferred" ("starred"), do not show it once more in the list.

## Alternative Designs

N/A

**Comment by CyrusNajmabadi** [comment]
Dupe of https://github.com/dotnet/roslyn/issues/71705
