### ISSUE TITLE
It is not possible to compile a switch expression that calls a method with the DoesNotReturn attribute and always throws an exception

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/roslyn#71786]
**Version Used**:  Latest Stable

**Steps to Reproduce**: [See sharplab code](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoARKCAcxgHsBnBKAYzeoGEWAEwCmAQRgQANgE82UNgG5ixAGYtk5ABQA3CBqjkAvOVILyBgDzk8pU+YDU9gJTEA3sXKfKeAJyaDbADuUAhcABbkHl7R7kTR8V5WNkYAfOQARIA8G4Ag++lwUQnRVjgUhmlZ2Tl5BYWeAPqp5AhhyCyB5DDC7QCiAB5cwgAOnCwwmumikoEQsulOcOQA9IvkAMqoXANsbCqokuRcLGCDUJIQIzA10QC+NU5KcV41VH4BwaERV16xtUXWpeUqvlHr9yMUARkckCvgkGmVyAAVFptTTzJYrATHU7nKCjcjCZCtZAw8i3EHke7EMnEADatBYwjYADkWAgAErCBCoZAwAC6xCoADZKAAWRHIwKoxrNVrtTo9fpDC7jSbTWaUohAA=) 

```cs
using System;
using System.Diagnostics.CodeAnalysis;

for (var i = 0; i < 100; i++)
{
    Console.WriteLine(i switch 
        {
            < 10 => "🌄",
            < 20 => "🌄🌄",
            _ => throw new Exception("Always"), // Successful compilation
        }
    );
    
    Console.WriteLine(i switch 
        {
            < 10 => "🌄",
            < 20 => "🌄🌄",
            _ => Throw(), // Compilation error
        }
    );
}

[DoesNotReturn]
static void Throw() => throw new Exception("Always");
```

**Diagnostic Id**: Compilation error `CS0029 Cannot implicitly convert type 'void' to 'string'`

**Expected Behavior**: Successful compilation, as for code `throw new Exception("Always")`

**Actual Behavior**: Compilation error `CS0029 Cannot implicitly convert type 'void' to 'string'`

**Comment by CyrusNajmabadi** [comment]
By design. "does not return" only affects nullable analysis.

**Comment by AlexRadch** [comment]
> By design. "does not return" only affects nullable analysis.

Can we extend the impact of such attributes to execution flow analysis?

**Comment by AlexRadch** [comment]
> By design. "does not return" only affects nullable analysis.

Compile it to something like next:

```cs
Throw();
throw new UnreachableСodeException();
```
