### ISSUE TITLE
Show minimum size of class/struct type as hint when hovering for C#

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71804]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Show-minimum-size-of-classstruct-type-a/10559842)._

---
With the introduction of C++ type size hints in a recent version, it would be helpful to also have an estimate about the size of the class or struct type in C#. This should also include records.
Optionally, for nested contained reference types, the size calculation could also show the total allocated size for non-null instances.

---
#### Feedback Bot on 1/11/2024, 06:23 PM: 

(private comment, text removed)

**Comment by lsoft** [comment]
Sounds like a good idea for a VS codelense extension.

I can develop such VSIX. Showing such info about the type declaration is an easy task. But I don't know the way to obtain a class/size estimation size, it is a difficult part...

**Comment by DoctorKrolic** [comment]
> But I don't know the way to obtain a class/size estimation size

Primitives (`int`, `byte`, `char` and so on) have known constant size. Size of `struct` is a sum of its members' sizes. Size of a reference type is 4 bytes on 32 bit systems and 8 bytes on 64 bit systems

**Comment by lsoft** [comment]
@DoctorKrolic 

> Size of struct is a sum of its members' sizes.

One need to take care about `StructLayoutAttribute` in order to be precise. Also, additional complication arise with `nuint` etc... And may be something additional which I don't know...

does Roslyn contain somewhere this algorithm (for some purpose)? May be we need only make it public?

**Comment by tannergooding** [comment]
There is no fixed algorithm and it differs per target platform/ABI.

Windows vs Linux vs MacOS vs … can all differ, as can x86 vs x64 vs Arm32 vs WASM vs …, and all the cross permutations there-of.

You are at best getting a rough estimate and one that isn’t necessarily useful for the average dev. It’s much more practical to instead use things like Benchmark.NET or the VS profiler to actually profile your application or method and measure the actual allocations done. Then remeasure each release or when changes are made, so you can track it over time and identify improvements/regressions

**Comment by Cosifne** [comment]
I will mark this as closed.
As @tannergooding  pointed out, the real size of a class/struct depends on the platform & runtime. Roslyn doesn't have any way to give precise estimate of the object size.
