### ISSUE TITLE
Quick actions and refactoring - generate exception class creates obsolete code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71803]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-actions-and-refactoring---generate/10564481)._

---
Visual Studio 2022 17.9.0 Preview 3.0 - In .net8 when generating exception class using the quick actions - it creates a protected method that is obsolete.

![image.png](https://aka.ms/dc/image?name=B2e50078572294d4788aed46ab02a07b5638411938926671453_20240118-105812-image.png&tid=2e50078572294d4788aed46ab02a07b5638411938926671453)

---
#### Feedback Bot on 1/18/2024, 06:12 PM: 

(private comment, text removed)

**Comment by Cosifne** [comment]
Looks like a dup of https://github.com/dotnet/roslyn/issues/72552
And the linked issue is fixed.
