### ISSUE TITLE
[VB] Use `String.Concat` for interpolated strings if possible like C#

### ISSUE THREAD

**Issue by tats-u** [dotnet/roslyn#71839]
#58557 should not be applied to VB now because interpolated strings in VB are *always* translated into `String.Format` unlike C#.
Also, this has not been recommended for everyone because of poorer performance than the `&` operator. 
I really want beginners to use it though.
I do not ask vbc to use `DefaultInterpolatedStringHandler` in .NET because it will be too much modification given VB's popularity than C#.
Some people have to learn VB.NET before C#. It is important to force them to develop the habit of using interpolated strings, which is the common sense in the modern C# and other popular languages.

If interpolated expressions are all String or Char and do not have format specifiers at all, the interpolated string should be converted to a string concatenation.

**Version Used**: 

Any (can be reproduced in sharplab)

**Steps to Reproduce**:

```vbnet
Public Class C
    Public Function InterpolatedString(bar As String, qux As String) As String
        Return $"foo{bar}baz{qux}"
    End Function
    Public Function Concatenation(bar As String, qux As String) As String
        Return "foo" & bar & "baz" & qux
    End Function
End Class
```

https://sharplab.io/#v2:EYLgHgbALANANiAbsGATEBqAPgBQK7BwCWAxgAQDCcAhgM62UCwAUGW2foaWQGJ4B2JAC5EA9vzIBJfkICmAJwAOomnNQBlIfKL8A5gApg1eWQCCDTdr0wyARzxgzFrTt0BKJ2UuuW7P2QAlWSE8eQkAEgAiADNRUQBvI3kAXyMAL3j7MGTI33YAUX5UXgFhMX48tk5icj5BEXFKcRJqOX5W8sNjT29rOwcelz0Pcy8h3Ur/IJCwshi4yLIAMjIk5bn0xZWsycLiurLxFj3KGnogA===

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

```vbnet
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: AssemblyVersion("0.0.0.0")]
public class C
{
    public string InterpolatedString(string bar, string qux)
    {
        return string.Concat("foo", bar, "baz", qux);
    }

    public string Concatenation(string bar, string qux)
    {
        return string.Concat("foo", bar, "baz", qux);
    }
}
```

**Actual Behavior**:

```vbnet
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: AssemblyVersion("0.0.0.0")]
public class C
{
    public string InterpolatedString(string bar, string qux)
    {
        return string.Format("foo{0}baz{1}", bar, qux);
    }

    public string Concatenation(string bar, string qux)
    {
        return string.Concat("foo", bar, "baz", qux);
    }
}
```

**Comment by tats-u** [comment]
Area-Compiler

**Comment by jaredpar** [comment]
For this issue I have similar feedback as your other VB based issues. The primary goal of VB is not squeezing out every little performance change we can do. Changes like this require a bit of justification to get through, not just observing that C# and VB have different code gen.

**Comment by tats-u** [comment]
> similar feedback as your other VB based issues

This is most important one and I have given up other improvements.

`$"...{strValue}..."` should be a much more recommended syntax than `"..." & strValue & "..."`. At least, your team should have added it to let users use them without hesitations. In C#, `+` for strings are less recommended (see https://github.com/dotnet/roslyn/discussions/70957 & https://github.com/dotnet/roslyn-analyzers/issues/7108). Even though VB's `&` does not cause such misunderstanding unlike `+` in C#, users who understand both VB & C# will prefer to use the interpolated string.

There are both pros and cons to use `stringVariable = "literal"` instead of `String.Equals` even other than performance, but `$"..."` has few cons other than the performance issue.

**Comment by jaredpar** [comment]
I do not feel like any of the discussion here has addressed my concerns. As mentioned several times it is not an explicit goal of VB to get every ounce of performance possible out of the language. Changes to VB around performance need to come with significant data on it improving real world applications. That has not been provided here. As such I'm closing this issue

**Comment by tats-u** [comment]
Is it sufficient that rewriting all affected & to interpolated strings in my app increased the execution time by several percent or seconds? Could you show me more concrete criteria?
