### ISSUE TITLE
Improve error message for CS9008

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslyn#71832]
**Version Used**: VS 17.8.5

**Steps to Reproduce**:

```
string s = $$@" foo";
```

Error message:

`Sequence of '@' characters is not allowed. A verbatim string or identifier can only have one '@' character and a raw string cannot have any.`

**Comment by CyrusNajmabadi** [comment]
Why is this incorrect?  `$$` starts a raw string, which cannot have any `@` signs (as the message says). Thanks!

**Comment by josefpihrt** [comment]
`Sequence of '@' characters is not allowed` sounds like that there are multiple `@` characters, but there is only one.

I would expect something like `Verbatim string cannot start with multiple '$' characters.`

**Comment by CyrusNajmabadi** [comment]
Here it means a set of things following each other in order.  Having any such sequence is illegal.  So that means `$$@` is illegal, as is `$$@@`, `$$@@@` and so on :)

**Comment by CyrusNajmabadi** [comment]
> I would expect something like

In this case, we're seeing `$$` first, which is a legal start to a raw string literal.  But then we hit an `@` which is not legal for such a string.  So we report in that fashion.  

You could do things another way and say "well, i see an @, ergo it looks like it's a verbatim, ergo i'll say that you can have at most one $ before or after the @...".  But it really feels like six of one, half a dozen of another.

**Comment by josefpihrt** [comment]
@CyrusNajmabadi  Thanks for replies. I'm fine with the explanation.
