### ISSUE TITLE
[VB] String comparison with string constants can be optimized to either of `String.Equals` (`String.op_Equality`, `op_Inequality`), `String.IsNullOrEmpty`, or `String.CompareOrdinal`

### ISSUE THREAD

**Issue by tats-u** [dotnet/roslyn#71835]
/**Version Used**: 

Any

**Steps to Reproduce**:

```vbnet
Imports System
Public Class C
    Const L = "literal"
    Public Sub M(s As string)
        Console.WriteLine(s = L)
        Console.WriteLine(s = Nothing)
        Console.WriteLine(s <> "")
        Console.WriteLine(s > L)
    End Sub
End Class
```

https://sharplab.io/#v2:DYLgbgRgPgkgtgBwPYCcAuBnABAZQJ4ZoCmcAsAFAAKArhMAJYDGWAwsAIYbYsVZ+tIAdoSwAZLAF4sAIgbEU7YNN78adJrlpYAsgApsAQWyEU9QQHMAlCv78WQjEmBEAdAHVTxUWaL7JY63JbW3thJ1cPei8fPykAOSQ0AAszKxtg0Mdnd08ib0FfbAAeAD4ZaUDguwdwnKi8mOwy0Ur+AFFBABNNCAoO7rZODCA===

```vbnet
Option Compare Text

Imports System
Public Class C
    Const L = "literal"
    Public Sub M(s As string)
        Console.WriteLine(s = L)
        Console.WriteLine(s = Nothing)
        Console.WriteLine(s <> "")
        Console.WriteLine(s > L)
    End Sub
End Class
```

https://sharplab.io/#v2:DYLgbgRgPg8gDgFwJYHsB2ACAwigtnAQwCcBTDAFRIA8EBYAKAYEl8UiEBnDAZQE8OEJXAwAKAVwjAkAY2zACHLlgYZV2dAIwAZDAF4MAIimCiBYAZVrxkmTwkYAsgAouAQS4CiSNAHMAlJZqajhoHCjAJAB0AOpeglreJC562gH0QUEhYRExcSQJaElc+gByKAgAFt7+gRlZ4VGxSPGJyQA8AHyGBmkZwRoNuc35rVxdWr1qAKJoACZ2EAwz81jyikA

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

```vbnet
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyVersion("0.0.0.0")]

public class C
{
    private const string L = "literal";

    public void M(string s)
    {
        Console.WriteLine(s == "literal");
        Console.WriteLine(string.IsNullOrEmpty(s));
        Console.WriteLine(!string.IsNullOrEmpty(s));
        Console.WriteLine(string.CompareOrdinal(s, "literal") > 0);
    }
}

```

```vbnet
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyVersion("0.0.0.0")]

public class C
{
    private const string L = "literal";

    public void M(string s)
    {
        Console.WriteLine(Operators.CompareString(s, "literal", true) == 0);
        Console.WriteLine(string.IsNullOrEmpty(s));
        Console.WriteLine(Operators.CompareString(s, "", true) != 0);
        Console.WriteLine(Operators.CompareString(s, "literal", true) > 0);
    }
}

```

Note:

- The order of `CompareOrdinal`: `null` \< `""` \< `"\0"` \< the others
- `"" = Char.ConvertFromUtf32(&H2060)` produces `True` when `Option Compare Text`.
  - `s = Nothing` produces `True` only for `Nothing` and `""` even when `Option Compare Text`.
- VB's `foo = bar` when `Option Compare Binary` equals to `(foo ?? "") == (bar ?? "")` or `string.CompareOrdinal(foo ?? "", bar ?? "") == 0` in C#.
- We do not have to consider cases where both sides are general variables (other than `String.Empty`).

**Actual Behavior**:

```vbnet
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyVersion("0.0.0.0")]

public class C
{
    private const string L = "literal";

    public void M(string s)
    {
        Console.WriteLine(Operators.CompareString(s, "literal", false) == 0);
        Console.WriteLine(Operators.CompareString(s, null, false) == 0);
        Console.WriteLine(Operators.CompareString(s, "", false) != 0);
        Console.WriteLine(Operators.CompareString(s, "literal", false) > 0);
    }
}

```

```vbnet
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyVersion("0.0.0.0")]

public class C
{
    private const string L = "literal";

    public void M(string s)
    {
        Console.WriteLine(Operators.CompareString(s, "literal", true) == 0);
        Console.WriteLine(Operators.CompareString(s, null, true) == 0);
        Console.WriteLine(Operators.CompareString(s, "", true) != 0);
        Console.WriteLine(Operators.CompareString(s, "literal", true) > 0);
    }
}

```

**Comment by jaredpar** [comment]
Similar to the other issues, what are the gains from making this change? Are there profiles on real wordl applications that demonstrate a benefit here? Or even a micro bench mark that we feel is replicable to general applications?

**Comment by tats-u** [comment]
@jaredpar Currently, VB's `=` & `<>` are slower than `String.Equals`. (note: `= Nothing` must be overwritten using `String.IsNullOrEmpty`)
If you have to teach VB.NET to beginners, you have to say "`String.Equals` is faster but more verbose than `=`".
I know `=` has some pitfalls (e.g. comparison with an empty string or null), but we do not want to recommend the verbose way (`String.Equals`) to beginners .

I performed a benchmark between `String.Equals` & `String.CompareOrdinal` & `Operators.CompareString`. In .NET Framework 4.8.1 (I have not tried .NET 8 but I think `Equals`  is fastest because it is inlined) but `Operators.CompareString` was slower than the other two.

**Comment by jaredpar** [comment]
> Currently, VB's = & <> are slower than String.Equals

There are a number of operations in VB that are known to be less efficient than direct runtime method calls or C# equivalents. The appeal of VB is not that it has the most efficient code possible but more around its usability for new developers, a more verbose syntax that appeals to people, etc ... Small perf changes like this generally do not meet our bar, particularly when it impacts fairly core parts of the language. Yes equivalent wins would get more consideration in C# where high performance is a goal. For a change like this in VB we'd need to see some rather compelling benchmarks for real world applications.

**Comment by paul1956** [comment]
@jaredpar an analyzer/CodeFix is safer and easier way to address.

**Comment by tats-u** [comment]
This change will not only improve performance, but also:

- Improve portability to C# by reducing dependence on the VB runtime. This will help users of, for example, https://icsharpcode.github.io/CodeConverter/ and ILSpy.
- Facilitate a move to `Option Compare Binary`, whose behavior is more predictable and more portable to C# without the VB runtime, by increasing the performance difference between both options more.

> an analyzer/CodeFix is safer and easier way to address.

As far as the comparison to `Nothing` or an empty string is concerned, a rewrite to `IsNullOrEmpty` may be suggested because it is clearer.

**Comment by tats-u** [comment]
https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUAAoCuEwAlgMaECymMTwSoQbZMAc2wBDWnUJzhLdl2IsektgDsAFAEp68g4QDCmDfkyCAdAHVsbKgBlNlLcQDuWgHKZcAC01iOnqyhnImZhaUNnaOzq4eAEQJQfryAKIaMCQsqXIAYkwaHLhspiQekoQAgkTEuHYagdVEyBpUYpTYuYbElILFxpL4QpLdBkZDQgkAZpiYCWOhhABKlLhM2BqEAIyLYZOECRCS2AshS/Kr65uEAEx7hBwHR5IAXmcXBlcbWwDMDxNhocAI5MAAeH0+cm+NwALADnqDwZCoTCtgBWBFAhIcHAdFGfNGEABsWKmBIuRIAtLtzoZAUI0sBhg8vmsfoQAJzch4ZLK9fq4bp8wgFIolUz0EW8fiCIA=

```vbnet
Imports System
Public Module Program
    Public Sub Main()
        Console.WriteLine(Sw(Nothing))
        Console.WriteLine(Sw(""))
    End Sub
    Function Sw(a As String) As Integer
        Select Case a
        Case "foo"
            Return 1
        Case "bar"
            Return 2
        case "baz"
            Return 3
        Case "qux"
            Return 4
        Case "quux"
            Return 5
        Case "corge"
            Return 6
        Case ""
            Return -1
        Case Else
            Return 999
        End Select
    End Function
End Module
```

↓

```cs
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue | DebuggableAttribute.DebuggingModes.DisableOptimizations)]
[assembly: AssemblyVersion("0.0.0.0")]

[StandardModule]
public sealed class Program
{
    public static void Main()
    {
        Console.WriteLine(Sw(null));
        Console.WriteLine(Sw(""));
    }

    public static int Sw(string a)
    {
        uint num = <PrivateImplementationDetails>.ComputeStringHash(a);
        if (num <= 1991736602)
        {
            if (num != 1271706118)
            {
                if (num != 1857515650)
                {
                    if (num == 1991736602 && Operators.CompareString(a, "bar", false) == 0)
                    {
                        return 2;
                    }
                }
                else if (Operators.CompareString(a, "baz", false) == 0)
                {
                    return 3;
                }
            }
            else if (Operators.CompareString(a, "quux", false) == 0)
            {
                return 5;
            }
        }
        else if (num <= 2458699527u)
        {
            if (num != 2166136261u)
            {
                if (num == 2458699527u && Operators.CompareString(a, "corge", false) == 0)
                {
                    return 6;
                }
            }
            else if (Operators.CompareString(a, "", false) == 0)
            {
                return -1;
            }
        }
        else if (num != 2851307223u)
        {
            if (num == 4074852489u && Operators.CompareString(a, "qux", false) == 0)
            {
                return 4;
            }
        }
        else if (Operators.CompareString(a, "foo", false) == 0)
        {
            return 1;
        }
        return 999;
    }
}

[CompilerGenerated]
internal sealed class <PrivateImplementationDetails>
{
    internal static uint ComputeStringHash(string s)
    {
        uint num = 2166136261u;
        if (s != null)
        {
            int num2 = 0;
            while (num2 < s.Length)
            {
                num = (s[num2] ^ num) * 16777619;
                num2++;
            }
        }
        return num;
    }
}
```

↑This outputs:

```
-1
-1
```

https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUAAoCuEwAlgMaECymMTwSoQbZMAc2wBDWnUJzhLdl2IsektgDsAFAEp68g4QDCmDfkyCAdAHVsbKgBlNlLcQDuWgHKZcAC01iOnqyhnImZhaUNnaOzq4eAEQJQfryAKIaMCQsqXIAYkwaHLhspiQekoQAgkTEuHYagdVEyBpUYpTYuYbElILFxpL4QpLdBkZDQgkAZpiYCWOhhABKlLhM2BqEAIyLYZOECRCS2AshS/Kr65uEAEx7hBwHR5IAXmcXBlcbWwDMDxNhocAI5MAAeH0+cm+NwALADnqDwZCoTCtgBWBFAhIcHAdFGfNGEABsWKE3j8AQeXzWP0IAFpdudDIChGlgMNqZdaTcAJz8h4ZLK9fq4bpCwgFIolUz0CW8fiCIA===

Once `Case ""` is replaced with `Case Nothing`, the output code gets less optimized:

```vbnet
Imports System
Public Module Program
    Public Sub Main()
        Console.WriteLine(Sw(Nothing))
        Console.WriteLine(Sw(""))
    End Sub
    Function Sw(a As String) As Integer
        Select Case a
        Case "foo"
            Return 1
        Case "bar"
            Return 2
        case "baz"
            Return 3
        Case "qux"
            Return 4
        Case "quux"
            Return 5
        Case "corge"
            Return 6
        Case Nothing
            Return -1
        Case Else
            Return 999
        End Select
    End Function
End Module
```

↓

```cs
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic.CompilerServices;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue | DebuggableAttribute.DebuggingModes.DisableOptimizations)]
[assembly: AssemblyVersion("0.0.0.0")]

[StandardModule]
public sealed class Program
{
    public static void Main()
    {
        Console.WriteLine(Sw(null));
        Console.WriteLine(Sw(""));
    }

    public static int Sw(string a)
    {
        if (Operators.CompareString(a, "foo", false) == 0)
        {
            return 1;
        }
        if (Operators.CompareString(a, "bar", false) == 0)
        {
            return 2;
        }
        if (Operators.CompareString(a, "baz", false) == 0)
        {
            return 3;
        }
        if (Operators.CompareString(a, "qux", false) == 0)
        {
            return 4;
        }
        if (Operators.CompareString(a, "quux", false) == 0)
        {
            return 5;
        }
        if (Operators.CompareString(a, "corge", false) == 0)
        {
            return 6;
        }
        if (Operators.CompareString(a, null, false) == 0)
        {
            return -1;
        }
        return 999;
    }
}
```

This is due to this issue.

**Comment by jaredpar** [comment]
Closing because at this time, this change is not a direction that we want to be taking in VB.

**Comment by tats-u** [comment]
Moving to Analyzer/Codefix later.

---

>  usability for new developers

I believe VB has more pitfalls and is less convenient than C#.

> a more verbose syntax that appeals to people

COBOL, which is designed to look similar to English?

They should be just your public stances. Your team actually should want to throw away or escape from such a language with large amount of debt since BASIC as soon as possible and dedicate to C#.

**Comment by CyrusNajmabadi** [comment]
> I believe VB has more pitfalls and is less convenient than C#.

VB prioritizes a different set of goals and preferences than C# does (same with C++, F#, TS, Swift, etc.).

We have no goals to make VB and C# the same, and we think its differences are what makes it valuable.

> They should be just your public stances

These are our public stances.  We've outlined our language strategy already, and we've been transparent and frank with you about how we assess these requests.
