### ISSUE TITLE
Analysis of C# projects in Docker does not contain ISymbols from libraries imported in using statements

### ISSUE THREAD

**Issue by vladimirKa002** [dotnet/roslyn#71842]
**Version Used**: 4.8.0

**Steps to Reproduce**:

I have a simple program which performs an analysis of code by retrieving `ISymbols` from entities. I use the following code snippet for this: 

```
Compilation compilation = project.GetCompilationAsync().Result;
var syntaxTree = document.GetSyntaxTreeAsync().Result;
var semanticModel = compilation.GetSemanticModel(syntaxTree, true);
// ... get some syntax node
var symbol = semanticModel.GetSymbolInfo(node).Symbol;
```

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build" Version="17.8.3" />
		<PackageReference Include="Microsoft.Build.Framework" Version="17.8.3" />
		<PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.8.3" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.8.3" />
		<PackageReference Include="Microsoft.Build.Locator" Version="1.6.10" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />

		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" />
	</ItemGroup>
</Project>
```

My input projects might have many imported libraries and their symbols have to be loaded as well. When I run in on Windows, all symbols are found as expected.

However, I also need to run the analyser in Docker container. For this, I have the following Dockerfile:

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /Analyser

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /Analyser
COPY --from=build-env /Analyser/out .

# SDKs
COPY --from=mcr.microsoft.com/dotnet/sdk:8.0 /usr/share/dotnet/sdk /usr/share/dotnet/sdk
COPY --from=mcr.microsoft.com/dotnet/sdk:7.0 /usr/share/dotnet/sdk /usr/share/dotnet/sdk

ENTRYPOINT ["dotnet", "Analyser.dll"]
```

Whenever I run the analyser in Docker, it does not find all `ISymbols` that are present in imported libraries. I wonder if I am missing something in my Dockerfile configuration, because everything works properly on my Windows machine.

I also noticed that when I use `mcr.microsoft.com/dotnet/aspnet:8.0` as a runtime image, even symbol for `List` class in my examples is not found. With `mcr.microsoft.com/dotnet/net:8.0`, symbol for `List` is present, but not other ones.

**Expected Behavior**: 
Projects have to be analysed similarly on both Windows and Docker (contain all `ISymbols` from imported libraried).

**Actual Behavior**:
`ISymbols` are missing when running analyser in Docker.

**Comment by CyrusNajmabadi** [comment]
If you call GetDiagnostics on your compilation what does it return?

**Comment by vladimirKa002** [comment]
It returns me a number of error messages stating that some symbol is not found, like:
```
ProgramWalker.cs(55,41): error CS0246: The type or namespace name 'SyntaxToken' could not be found (are you missing a using directive or an assembly reference?)
TokenHighlightTypes.cs(102,48): error CS0246: The type or namespace name 'SymbolDisplayPart' could not be found (are you missing a using directive or an assembly reference?)
TokenHighlightTypes.cs(162,50): error CS0246: The type or namespace name 'SyntaxTrivia' could not be found (are you missing a using directive or an assembly reference?)
ProgramWalker.cs(63,38): error CS0246: The type or namespace name 'SyntaxNodeOrToken' could not be found (are you missing a using directive or an assembly reference?)
GeneratedCodeUtilities.cs(82,13): error CS0246: The type or namespace name 'SyntaxTree' could not be found (are you missing a using directive or an assembly reference?)
...
```
The logs above are the result of running the analysis on my Analyser itself.

**Comment by CyrusNajmabadi** [comment]
@vladimirKa002 then you are not creating the compilation with the right set of references.

**Comment by CyrusNajmabadi** [comment]
Closing out.  User needs to setup their docker setup properly.

**Comment by CyrusNajmabadi** [comment]
> so maybe there are any additional commands that I need to add into Dockerfile?

Setup of docker is outside of hte bounds of responsibility of roslyn.  You'll basically want to ensure the same setup in their as what you have outside.  Given the missing references to things like SyntaxToken, you're definitely not properly referencing the roslyn sdk.  So you might want to start there.  Thanks!

You can also see if discord.gg/csharp might be able to help.  Someone there might know docker more.
