### ISSUE TITLE
Rev build task version per day

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn#7185]
When we release nuget packages for the compiler with a new build task that task may not be loaded because the task with the same assembly version may have already been loaded with a different path. 

If we Rev the minor version every day (by including the date in the version number) then installing various versions of the compiler should be fine as long s they weren't built in the exact same day.

**Comment by asvishnyakov** [comment]
Incrementing?

**Comment by jasonwilliams200OK** [comment]
+1 on just increment the minor version following the semver convention. Doesn't matter if we end up having `4.20.5008`, it is still a valid plain semantic version.
