### ISSUE TITLE
Broke API Compatibility

### ISSUE THREAD

**Issue by AddioElectronics** [dotnet/roslyn#71866]
Not sure if this is really a bug, but I added a function to NamedTypeSymbol.cs, saved, and then immediately undid my changes and resaved.

Now possibly every symbol that inherited NamedTypeSymbol is throwing the CS0104 error (ambiguous with the public model) and I'm unable to compile.
I don't have anything I can add or remove from the shipped/unshipped text files, and I don't see any changes in git that I could possibly undo.

Any help would be much appreciated.

**Comment by CyrusNajmabadi** [comment]
Please provide more information.  For example, how you're actually attemping to compile roslyn.  If you can include a binlog (along with the actual error messages), taht woud be helpful.

**Comment by AddioElectronics** [comment]
Figured it out, made a stupid mistake.
Intellisense had added a using statement to the PublicModel namespace.
Funny thing is, that was the first thing I checked for. Just it was in a different file I had been working on and didn't think to look there.
I should probably go to bed earlier tonight.

Anyways, thanks for the quick response.
