### ISSUE TITLE
.NET WinForms: IntelliSense remark IDE0051 shown for own class methods, but not for Form class methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71870]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-WinForms:-IntelliSense-remark-IDE00/10573675)._

---
\[severity:It bothers me. A fix would be nice\]

_Environment_  
I have a WinForms-.NET-FX 4.8 VB.NET-project in Visual Studio Version 17.9.0 Preview 4.0 on a 64-bit Win10 PC, but it also happens in a WinForms-.NET 7.0 VB.NET-project.

**Problem**  
The IntelliSense remark IDE0051 for irrrelevant methods are shown for own class methods, but not for Form class methods.

**Description**  
I have the following code:

```  
Friend Class FrmMain

Private Sub Foo()
	End Sub

Private Function Bar() As Boolean
		Return False
	End Function

End Class

Friend Class Foo

Private Sub Bar()
	End Sub

Private Function Baz() As Boolean
		Return False
	End Function

End Class
  
```

The result in the IDE:  

![image](https://github.com/dotnet/roslyn/assets/1408396/b4cf72a4-e03c-4e8d-af34-d87b6dad27a3)

The methods in the class Foo are marked as unnecessary, so their names are gray instead of black and I see the IDE0051 remark. For the FrmMain class (an inherited class of Windows.Form) the two shown methods are also unnecessary, but they are not marked as this.

**Consequences**  
It’s harder to see, which methods can be deleted. The reference counter is nice, but the IDE0051 remark would be better, especially in combination with the method name being greyed out.

---
#### Feedback Bot on 1/29/2024, 06:25 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as this is not an area we are investing in.

**Comment by CyrusNajmabadi** [comment]
> Why would it matter for Roslyn the type hierarchy

Often times there are special constructs that allow something to be referenced, even if not directly by code. Removing such code will break an application.

**Comment by fitdev** [comment]
@CyrusNajmabadi In that case it would be helpful to provide documentation that lists all the cases where an apparently unused member (Find All References yields none) is not considered by this analyzer.
