### ISSUE TITLE
Raw String Literal Concatenation Does Not Preserve NewLines

### ISSUE THREAD

**Issue by groogiam** [dotnet/roslyn#71895]
### Description

Using += on a raw string literal with newlines at the start does not preserve the newline. I could be mistaken about the semantics here but I cannot find anywhere in the docs that talk about this situation.

### Reproduction Steps

```csharp
var bla =
"""

Some Text
""";

bla += bla;

Console.WriteLine(bla);
 
```

### Expected behavior

```

Some Text

Some Text
```

### Actual behavior

```

Some Text
Some Text
```

**Comment by CyrusNajmabadi** [comment]
This is by design, as stephen showed.
