### ISSUE TITLE
Quote completion improvements

### ISSUE THREAD

**Issue by madskristensen** [dotnet/roslyn#71898]
## Summary
The way C# handles quote completion differs from other editors like VS Code, but also from other languages in VS such as C++.

## Background and Motivation
Visual Studio users have noticed that the behaviour around quotes is less than ideal. A [feature request](https://developercommunity.visualstudio.com/t/Please-make-quotes-more-intelligent/10140435) to improve the behavior has gotten 15 votes. The issue experienced by users is that in certain situations, VS should not auto-complete quotes. It’s frustrating to users when it does and affects their overall satisfaction with the IDE.

![Quotation completion issue 2](https://github.com/dotnet/roslyn/assets/1258877/12477b58-d5ab-484e-8331-10a03cb1d48d)

Here’s what some users say about the current behavior:

![image](https://github.com/dotnet/roslyn/assets/1258877/bf830538-335f-415f-98c2-df6f25fbd86f)

![image](https://github.com/dotnet/roslyn/assets/1258877/fecc3fe5-0f94-45a6-abaa-e0cc0c3064e9)

## Proposed Feature

The quotation characters in question are double quote (") and single quote ('). The user has made no selection in the editor.

VS **must not** auto complete after user types a quotation character in these cases:
1.	Cursor immediately after alphanumeric character – P1
    a.	Example: text&lt;cursor&gt;
2.	Cursor immediately before alphanumeric character – P1 
    a.	Example: &lt;cursor&gt;text 
3.	In code comments and strings – P1 
    a.	Example: // comment  &lt;cursor&gt;
    b.	Current behavior – **no change required**

VS **must** auto complete in these cases:
1.	Cursor surrounded by non-alphanumeric characters including whitespace – P1
    a.	Example 1: some &lt;cursor&gt; text
    b.	Example 2: if (&lt;cursor&gt;)
    c.	Current behavior – **no change required**
2.	Cursor immediately after $ or @ in C# if followed by non-alphanumeric character – P2
    a.	Example: sb.AppendLine($&lt;cursor&gt;);

**Comment by CyrusNajmabadi** [comment]
@madskristensen  the linked issue is for ts/js.  The syntax:

![image](https://github.com/dotnet/roslyn/assets/4564579/0dee7529-547a-4295-9ba3-e0ac2602a36d)

is def not legal C# (there is no `{ ... }` syntax to start an object literal in our langauge, like there is in js/ts).  Should this move to ts/js?

**Comment by madskristensen** [comment]
That's from a Razor file. 

The issue is in the C# language service

**Comment by CyrusNajmabadi** [comment]
I'm not sure how i feel about this change.  The use case is very suspect.  Namely:

![image](https://github.com/dotnet/roslyn/assets/4564579/876faa06-c131-4e15-88f6-f85caf012048)

Why would we believe that something is a string just because it starts with a identifier char.  Take, for example: `(this is a string)`.  Why would *that* not have the same behavior?

I guess i'm just very skeptical that people *start* with string contents taht are initially *not* quoted, and then want to add quotes after.

**Comment by CyrusNajmabadi** [comment]
@sitefinitysteve what language are you typing in?  Can you give a more complete example?  Thanks!

**Comment by madskristensen** [comment]
More info from one of the comments on a duplicate feature request https://developercommunity.visualstudio.com/t/Provide-options-to-control-quote-complet/1652026#T-N1705116

**Comment by CyrusNajmabadi** [comment]
@madskristensen  I don't understand several of these reports.  For example:

> This then kicks off intellisense and that slows everything down as it cascades througout.

That doesn't sound like a roslyn case.  Similarly, `class="somename` doesn't seem like roslyn either, as that doesn't look like code that would apply to us at all.

**Comment by CyrusNajmabadi** [comment]
@madskristensen My point is this: pointing to other languages, and how they are potentially getting things wrong (esp. wrt undo behavior) is just confusing here.  Primarily because it makes it seem as if those issues are present with roslyn, even when tehy are specific to other tools.  Reporting them here doesn't address anything because even if we make changes on our end, those issues in other components will still be present.

**Comment by madskristensen** [comment]
Here's an example of turning an expression into a string. I start by adding a quote after the expression. It auto-inserts a closing quote as well. That is not helpful. Then I do the same in the front of the expression, and the same thing happens. Not helpful. 

![Quotes issue](https://github.com/dotnet/roslyn/assets/1258877/d9f3f1e5-7a64-410d-8c95-c8b7682a9c73)

This is adding negative value, because I would have been better off without the quote completion feature. The simple rules I proposed fixes use cases like these, brings the logic on par with C++ in VS and other editors like VS Code.

**Comment by CyrusNajmabadi** [comment]
> Then I do the same in the front of the expression, and the same thing happens. Not helpful.

The presumption though is that you are attempting to turn an expression into a string.  It could just as well be that you are trying to make `var name = "";` and intending to push the next bit to the next line. 

> , brings the logic on par with C++ in VS and other editors like VS Code.

I get that.  But the presumption is also that the valid use cases where this is helpful are ok to break.  It would be just as valid to say: when i'm in C++/vscode, i want this to work so that i can easily write a string like the above, and not get interference.  

In particular, C++ is *not* an editor we look to to try to have parity with.

**Comment by CyrusNajmabadi** [comment]
As an example, using your cases:

> Cursor surrounded by non-alphanumeric characters including whitespace – P1
> a. Example 1: some <cursor> text

I don't see why this wouldn't have the same behavior as the alphanumeric case.

**Comment by madskristensen** [comment]
>The presumption though is that you are attempting to turn an expression into a string. It could just as well be that you are trying to make var name = ""; and intending to push the next bit to the next line.

Theoretically yes, but you'd probably start with a blank space - especially once you know how this works. Status quo means that you'll have a high level of false positives. I believe it better to optimize for the most probable scenario and not every possible scenario.

**Comment by madskristensen** [comment]
>I don't see why this wouldn't have the same behavior as the alphanumeric case.

The idea is to make it predictable with the simple rule that when cursor is surrounded by whitespace or braces/brackets, then it auto-completes, otherwise it won't.

**Comment by CyrusNajmabadi** [comment]
> Theoretically yes, but you'd probably start with a blank space

I literally just wrote that in the last 20 minutes.  Without a blank space. :)

**Comment by CyrusNajmabadi** [comment]
> The idea is to make it predictable with the simple rule that when cursor is surrounded by whitespace or braces/brackets, then it auto-completes, otherwise it won't.

I would be ok with this *as an option*.  But it would likely need to be opt-in to ensure we're not breaking muscle memory on our own side.

**Comment by CyrusNajmabadi** [comment]
>  I believe it better to optimize for the most probable scenario

I genuinely don't see this as "more probable".  IN other words, surrounding with quotes means that users are writing unquoted strings to start with, and then deciding to quote them.  That seems *less* likely than them just entering new strings.  

The case where this may differ is someone copying something like an expr, to pass to something like an assert call, and wanting to then have a quoted version of that expr.   But that seems much rarer.

**Comment by CyrusNajmabadi** [comment]
Note: i don't like the proposed algorithm either.  say i have the following:

![image](https://github.com/dotnet/roslyn/assets/4564579/39c0dc99-57e7-4d4c-a51d-0d088093d2e9)

Now i want to complete the string by typing in the space before 'info'.  Because it is surrounded by whitespace, this would now complete out to two-quotes.  But i think i should only get one quote here (which is what roslyn *does* today).

**Comment by madskristensen** [comment]
> Note: i don't like the proposed algorithm either. say i have the following...

How can it be improved?

**Comment by madskristensen** [comment]
My proposal might not be crisp enough. The general idea is to make auto-completion less aggressive. If there are situations where my proposal makes it more aggressive, then that wasn't the intension and should be improved.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by madskristensen** [comment]
I'm thinking that an experiment with real users trying it might be the best way to iterate toward a final proposal. I'll look into making an extension next week to start the process

**Comment by madskristensen** [comment]
Here's what I'm starting out with https://github.com/madskristensen/QuoteCompletionFix/blob/master/src/TypingCommandHandler.cs

**Comment by CyrusNajmabadi** [comment]
can you make sure the use case of typing `"""` to get `""""""` (a raw string, with the caret in the middle) is not broken?

**Comment by madskristensen** [comment]
Yes, absolutely.

**Comment by CyrusNajmabadi** [comment]
Several fixes made in https://github.com/dotnet/roslyn/pull/72217.  Still keeping this open for the general case where the user is typing in a place where a string is legal, but existing code is there.  We'd like to explore making this contextual, so if it makes sense that existing code would be fine to push-to-the-right (like in an argument list), that we still complete the stirng.  Buf it doesn't make sense to push-to-the-right (like in an initializer) then we don't complete the string.

**Comment by Dean-NC** [comment]
> For Razor, quotes are far from the biggest issues. I would see more value if resource allocation would be considered for significantly improving the Razor editor experience in general.

I completely agree with this. There are times when the automatic closing of quotes is not what I want (mostly in Razor but also in .cs files), but the constant fighting that the Razor editor does with intellisense and also overwriting the HTML attribute or tag name I just typed (when I press space or tab), is very obstructive to the point I can no long just type without watching to see if what I previously typed will be replaced.

**Comment by CyrusNajmabadi** [comment]
@Dean-NC contributions welcome :-)

**Comment by CyrusNajmabadi** [comment]
Closing out as the fixes for C# went in with https://github.com/dotnet/roslyn/pull/72217.  Issues with Razor need to go through that team as they own that experience.
