### ISSUE TITLE
Should speculative semantic models be able to disable nullable analysis?

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#71904]
Follow-up issue for experimental "nullable-disabled semantic model"
Related to #70609
https://github.com/dotnet/roslyn/blob/ca58e990e1eb5c72790a45e95fb5cb8c028f779f/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L53-L60

**Comment by AlekseyTs** [comment]
Why special support is needed for that? It feels like speculative semantic models requested from a model with disabled nullable analysis should inherit that property from the parent.

**Comment by RikkiGibson** [comment]
I think that is the right answer. Thanks. I've made the change in #71036.
