### ISSUE TITLE
CallerArgumentExpression for out arguments

### ISSUE THREAD

**Issue by matejskubic** [dotnet/roslyn#71901]
### Description

[`CallerArgumentExpressionAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute.-ctor?view=net-8.0&devlangs=csharp) does not return only argument name with `out` arguments.

It contains an additional type of argument (word before argument name).

### Reproduction Steps

```cs
using System.Runtime.CompilerServices;

ArgNameTester.GetArgValueByName(out string myName);
Console.WriteLine(myName);


public class ArgNameTester
{
    public static void GetArgValueByName(out string value, [CallerArgumentExpression(nameof(value))] string key = "")
    {
        value = key;
    }
}
```

### Expected behavior

`myName`

### Actual behavior

`string myName`

### Configuration

.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.30fce108

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64

### Other information

Sample at https://github.com/matejskubic/CallerArgumentExpression-out

**Comment by CyrusNajmabadi** [comment]
By design.  The caller expression includes the expression at the call site.  In this case that is a DeclarationExpression including the type name and var name.

**Comment by matejskubic** [comment]
This is not true.

```cs
string testValue = "test";
var result = ArgNameTester.GetArgValueByNameReturn(testValue);
Console.WriteLine(result);

  public static string GetArgValueByNameReturn(string value, [CallerArgumentExpression(nameof(value))] string key = "")
  {
      return key;
  }

```

prints `testValue`.

---

So 
```cs
ArgNameTester.GetArgValueByName(out string myName);
Console.WriteLine(myName);
    public static void GetArgValueByName(out string value, [CallerArgumentExpression(nameof(value))] string key = "")
    {
        value = key;
    }
```
should print `myName` (expected) or `out string value` (as per @CyrusNajmabadi) - the actual print is `string value` which is neither expected nor documented.

> [@CyrusNajmabadi](https://github.com/dotnet/roslyn/issues/71901#issuecomment-1920169083): By design. The caller expression includes the expression at the call site. In this case that is a DeclarationExpression including the type name and var name.
@ericstj @area-System.Runtime.CompilerServices

**Comment by matejskubic** [comment]
@svick seems reasonable. 

The documentation at https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute should be extended with this detailed information.

**Comment by CyrusNajmabadi** [comment]
It is documented:

> Indicates that a parameter captures the expression passed for another parameter as a string.

It explicitly says "the expression passed"

From the language level, when you have "out string value" you have an *argument* node containing `out <expr>`.  And, in this case, the `<expr>` is precisely `string value`.  We call that a *declaration expression* because it's an expiration that declares a new variable. 

As before this is very much by design
