### ISSUE TITLE
Automatic C# code formatting following the the-factor standard set by prettier for typescript

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71929]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-C-code-formatting-following-t/1543702)._

---
The code formatting in Visual Studio for C# is way too complex. In the javascript/typescript market, the prettier plugin has an approach of formatting everything: wrapping lines, auto indenting wrapped lines, formatting braces, etc.  Every behavior in prettier is pretty much fixed, this makes all debates "in the weeds" between teams go away, formatting is always plenty good enough. 

Can we also have this for C#, please?

---
#### Feedback Bot on 10/5/2021, 05:34 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
As with prettier, we are fine with another group making a tool for this and deciding on style and policy.
