### ISSUE TITLE
Separate reference count. Invocation and inheritance are shown in two parts.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71928]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Separate-reference-count-Invocation-and/10554989)._

---
![image.png](https://aka.ms/dc/image?name=Be71f5b5dde5842b8b0e66d7b9dcc50b9638403061105747513_20240108-182148-image.png&tid=e71f5b5dde5842b8b0e66d7b9dcc50b9638403061105747513)
When the project is large, the number of references can be very large, hundreds or even thousands.
Among all references, it is difficult to distinguish which references are inherited and which are called.
If it can be displayed separately, it will be clearer to view.

---
#### Feedback Bot on 1/8/2024, 06:12 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
