### ISSUE TITLE
C# Collection Expression for arrays can't be outlined / folded in text editor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#71932]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Collection-Expression-for-arrays-can/10575331)._

---
Outlining / folding in text editor works for

```
int[] aArray = new int[]
{
   1,
   2, 
   3
}
```

but not for

```
int[] aArray = 
[
   1, 
   2,
   3
]
```

---
#### Feedback Bot on 1/31/2024, 10:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by victor-pogor** [comment]
Hi @CyrusNajmabadi. I'd like to work on this one.

**Comment by CyrusNajmabadi** [comment]
@victor-pogor go for it!

**Comment by CyrusNajmabadi** [comment]
Also, there's no problem at all asking. But it's very safe to work on "help wanted" issues. Those are ones we've already prescreened as good for anyone to pick up.
