### ISSUE TITLE
The studio indicates that parameters need to be inserted, even though default parameters are available there.

### ISSUE THREAD

**Issue by Mr0N** [dotnet/roslyn#71946]
![image](https://github.com/dotnet/roslyn/assets/61237140/c43b0b25-92a8-412e-a560-3fbde9cc954a)
The studio indicates that parameters need to be inserted, even though default parameters are available there.

**Comment by Mr0N** [comment]
![image](https://github.com/dotnet/roslyn/assets/61237140/b83ebbae-2763-4eb4-95e4-93a996e57ec2)

**Comment by DoctorKrolic** [comment]
Read the error carefully: `An expression tree may not contain a call or invocation that uses optional arguments`
