### ISSUE TITLE
The problem with gRPC services

### ISSUE THREAD

**Issue by Mr0N** [dotnet/roslyn#71947]
![image](https://github.com/dotnet/roslyn/assets/61237140/81e06ce1-421c-4929-8342-96d165d1d7f0)

The problem with gRPC services is that if the username in Windows contains Cyrillic characters, the program assembly does not work. Additionally, I found an issue where if .NET 6 is installed not during Visual Studio installation but when opening a project, a window prompts for installing the .NET 6 SDK, resulting in a compilation error even on a clean project that has not been modified. Most likely, the SDK is installed in the user folder or somehow associated with it.

The folder can be changed, but the username is not as easily modifiable.

**Comment by huoyaoyuan** [comment]
> The problem with gRPC services is that if the username in Windows contains Cyrillic characters, the program assembly does not work.

It looks like gRPC SDK is generating invalid temporary path. Please report the issue to gRPC.

> Additionally, I found an issue where if .NET 6 is installed not during Visual Studio installation but when opening a project, a window prompts for installing the .NET 6 SDK, resulting in a compilation error even on a clean project that has not been modified. Most likely, the SDK is installed in the user folder or somehow associated with it.

Can you clarify the installation method/location of .NET SDK? If it's not at the default location, Visual Studio may not be able to find it.
What error did you get? Visual Studio should install at least one version of .NET SDK when you install .NET tooling.
