### ISSUE TITLE
[Test Failure] There are errors when processing test results in prtest/win/dbg/eta on PR #414

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7195]
looks like xunit no longer put xml file where it is expected. did something in infrastructure changed?

...

PR: [#414](https://github.com/dotnet/roslyn-internal/pull/414) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_eta/325/

**Issue 1: There are errors when processing test results**
No xunit test result files were found in the xUnitResults directory

**Comment by heejaechang** [comment]
https://github.com/dotnet/roslyn-internal/pull/413

this is another one failed due to same reason

**Comment by heejaechang** [comment]
@jmarolf @davkean do you know any change in how we run tests?

**Comment by jmarolf** [comment]
I am unaware of any change here.

**Comment by davkean** [comment]
@brettfo Do we covert ETA to the xunit result format? Or is that just vsi?

**Comment by brettfo** [comment]
It's done for both.

**Comment by davkean** [comment]
So what would cause this?

**Comment by davkean** [comment]
I've not seen this since this particular case and logs are gone, going to close this.
