### ISSUE TITLE
Analyzers should only include libraries not provided by the framework

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/roslyn#71952]
### Summary
For Microsoft.CodeAnalysis.Common it is possible to remove the following dependencies for newer frameworks as the libraries are provided by the framework

- System.Collections.Immutable
- System.Reflection.Metadata
- System.Runtime.CompilerServices.Unsafe

For Microsoft.CodeAnalysis.Workspaces.Common it will be possible to remove the following dependencies

- System.Threading.Channels
- Microsoft.Bcl.AsyncInterface - Maybe?

For Microsoft.CodeAnalysis.Features 

- System.Text.Json

For Microsoft.CodeAnalysia.Elfie

- System.Data.DataSetExtensions

It should be checked if any other analyzer packages are impacted

**Comment by jaredpar** [comment]
Thanks for the contribution but at this time we do not want to go in this direction. There are reasons we have specific dependencies on libraries like System.Collections.Immutable.
