### ISSUE TITLE
[Test Failure] Test Failures in prtest/win/dbg/unit32 on PR #7094#issuecomment-161461689

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7196]
PR: [#7094#issuecomment-161461689](https://github.com/dotnet/roslyn/pull/7094#issuecomment-161461689) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/1637/

**1 Test Failures:**
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Classification.SyntacticTaggerTests.TestTagsChangedForEntireFile

**Issue 1: Test Failures**
There were test failures, see Test Results above.

**Comment by DustinCampbell** [comment]
Is this still a thing?

**Comment by davkean** [comment]
I've not seen this in 3 months and logs are long gone.
