### ISSUE TITLE
Roslyn LSP server is packaging more than it should

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#71978]
It appears we're packaging symbols and XML document comment files in our VS Code package. That's just a waste of bandwidth and disk space, so maybe we should stop doing that.

**Comment by KirillOsenkov** [comment]
Note that symbols might be useful if you want line numbers in your exception stack traces. I usually embed pdbs.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need to do this, assign to a milestone.
