### ISSUE TITLE
CS8846 | Analyzer says the switch expression does not handle all cases, but I say otherwise

### ISSUE THREAD

**Issue by cemahseri** [dotnet/roslyn#71971]
**Version Used**: Visual Studio 2022 17.8.6+34525.116, C# 12, 4.8.0-7.23572.1 (7b75981c)

**Steps to Reproduce**:

```csharp
internal sealed record MultiPacketHeader(bool IsGoldSourceServer, bool IsCompressed);

var multiPacketHeader = new MultiPacketHeader(false, false);

var payloadIndex = multiPacketHeader.IsGoldSourceServer switch // Reports CS8846
{
    false when multiPacketHeader.IsCompressed => 20,
    false when !multiPacketHeader.IsCompressed => 12,
    true => 9
};
```

**Diagnostic Id**: CS8846

**Expected Behavior**:

The analyzer should never report the switch expression as not handling all possible inputs.

**Actual Behavior**:

The analyzer reports the switch expression as not handling all possible inputs.

I didn't realize that inside the switch expression, properties will be called more than one. Thanks to @Trojaner for pointing out this. So in the scenario, `IsCompressed` property will be called twice, since both `IsGoldSourceServer` and `IsCompressed` are false and the expression will not fall into the first case. So, to be sure, I've converted these properties to property with backing field and confirmed that getter method of `IsCompressed` is called twice. So I've converted my code to this;
```csharp
internal sealed record MultiPacketHeader(bool IsGoldSourceServer, bool IsCompressed);

var multiPacketHeader = new MultiPacketHeader(false, false);

var isGoldSourceServer = multiPacketHeader.IsGoldSourceServer; // This property only called one time but just let store its value in a variable aswell.
var isCompressed = multiPacketHeader.IsCompressed;

var payloadIndex = isGoldSourceServer switch // Still reports CS8846
{
    false when isCompressed  => 20,
    false when !isCompressed  => 12, // Tells that !isCompressed expression is always true, which is correct
    true => 9
};
```

So about the code above, both of those two properties' getter methods will be called once and the switch expression is effectively like this;
```csharp
var payloadIndex = multiPacketHeader.IsGoldSourceServer switch
{
    false when true => 20,
    false => 12,
    true => 9
};
```

As seen above, all possible inputs are handled.

**Comment by CyrusNajmabadi** [comment]
Closing out.  THe language has no concept of knowing that `multiPacketHeader.IsCompressed` and `!multiPacketHeader.IsCompressed` will produce separate values (indeed, in a real program, it may flip values between calls).

As such, neither of those cases may match at runtime.

**Comment by CyrusNajmabadi** [comment]
@cemahseri As i mentioned, the langauge has no concept of this *whether things are variables or not*.  The only place it has any understanding is around constants.

**Comment by CyrusNajmabadi** [comment]
@cemahseri You're reporting issues on Roslyn, which is the impl of the c# language spec. IN this regard, roslyn is running properly as it is implementing the language faithfully.  If you would like the language to change, that would have to start with a discussion over at dotnet/csharplang.  If your language change is approved, then the compiler (Roslyn) would be updated to abide by those new rules.

**Comment by cemahseri** [comment]
In the second code block, analyzer can very well tell me that expression in the second case is unnecessary. So, as you can see in the last code block, both `true` and `false` exists in each case. Since `IsGoldSourceServer`'s type is bool, I wonder what will it return anything other than `true` and `false`.
```csharp
var payloadIndex = multiPacketHeader.IsGoldSourceServer switch
{
    false when true => 20,
    false => 12,
    true => 9,
    _ => -1
};
```

In the example above, I have no idea how it will reach the default case. If you have any idea, just englishten me.

**Comment by CyrusNajmabadi** [comment]
There are already errors reported for code like that:

![image](https://github.com/dotnet/roslyn/assets/4564579/2dabb9da-9dc8-4a3f-8595-af64cf805233)

Note that two cases are marked here as unreachable.
