### ISSUE TITLE
Compiler freeze with custom assembly attribute

### ISSUE THREAD

**Issue by maazl** [dotnet/roslyn#71970]
**Version Used**: 

Compiler from Visual Studio 17.8.6

**Steps to Reproduce**:

1. Create a new class library project with .NET Framework 4.8 (not tested whether the version is important)
2. Add a single source file with this content:
``` cs
[assembly: Test]
enum TestEnum { Default }
class TestAttribute : System.Attribute
{
    public readonly TestEnum TestEnum;
    public TestAttribute(TestEnum e = TestEnum.Default) { TestEnum = e; }
}
```
3. Build the project

**Diagnostic Id**:

**Expected Behavior**:

The assembly should be generated.

**Actual Behavior**:

Deadlock after starting csc (last line in detailed build log)

If "Go to Definition" is used in Visual Studio the IDE also freezes. The devenv process need to be killed.
Posting the code in SharpLab with .NET Framework target also freezes the right window.

The test case passes in all versions of Visual Studio up to 17.7.6.
It also passes if the TestAttribute is defined _in a separate, referenced assembly_. Only if the attribute is used in the same assembly where it is defined the compiler freezes.

**Comment by hmuris** [comment]
I have the same problem.
