### ISSUE TITLE
Ыtring.Jion Different results on different operating systems Windows/Linux

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/roslyn#71990]
**6.0.26**: 

` StringBuilder str = new StringBuilder();

 str.AppendLine("test1");
 str.AppendLine("test2");
 str.AppendLine("test3");

 var qryColumnsString = string.Join(", ", str.ToString().Remove(str.Length - 2).Split("\r\n"));`

Debug on Windows: 

![image](https://github.com/dotnet/roslyn/assets/25795145/87ee3c1c-c0da-4210-9ebb-df459f3c58ff)

Debug on Linux (WSL,dcoker)

![image](https://github.com/dotnet/roslyn/assets/25795145/ee4557ee-49b3-4765-8c91-de4907461900)

**Comment by CyrusNajmabadi** [comment]
Seems by design .  On Windows the lines will be approved appended with `\r\n` while in Linux it will just be `\n`.

**Comment by EvgenyPrikhodko** [comment]
@CyrusNajmabadi Why doesn't the compiler skip `r`?

**Comment by CyrusNajmabadi** [comment]
The compiler isn't involved here.  You're just calling string and string builder apis.

**Comment by EvgenyPrikhodko** [comment]
@CyrusNajmabadi  Thanks for the feedback, can I leave a wish that the Api takes into account the OS?

**Comment by CyrusNajmabadi** [comment]
Sure. Such feedback would go to dotnet/runtime.  Thanks!
