### ISSUE TITLE
Automatically proffer and register remote brokered services into Roslyn LSP

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#71998]
See https://github.com/dotnet/roslyn/blob/4cd098b66619b74098103d75e6de18484272de99/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/Descriptors.cs#L37

Currently we have to list out and manually register each remote brokered service that we want to consume on the language server side.  However it is possible to read the remote manifest service in order to retrieve the set of remote services, and register them all into our container.

Would be useful for extenders (like XAML) to not have to update Roslyn in order to consume a new brokered service.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do this, please assign to a milestone.
