### ISSUE TITLE
Symbol display incorrect for CS0118 with parameters

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7201]
```
using System;
public class Program
{
    static void Main(params string[] args)
    {
        Action<args> a = null;
    }
}
```
Error:
```
error CS0118: 'params string[]' is a variable but is used like a type
```
Should be `args` and not `params string[]` (works without `params` too, just added to show the effect)

Note: works fine for locals, just seems to be issue with parameters.

**Comment by gafter** [comment]
Yes, see #7211 for the root cause.
