### ISSUE TITLE
Perf ddrits regression in WP64.ProjectManagement 0200.Xaml Designer Load

### ISSUE THREAD

**Issue by arunchndr** [dotnet/roslyn#72010]
WPF has a feature that triggers the enumeration of all loaded assemblies and their references. If some of the references are not loaded yet it loads them. The color tagger in XAML editor uses that feature. The XAML editor is in-proc hence WPF ends up enumerating all devenv assemblies.

The fix would be to move XAML editor (and all other VS componetns that rely on this feature) to OOP or change them to not use the feature. We need a permanent exception for the regression.

**Comment by arkalyanms** [comment]
This needs to move to XAML and reassign to Evgeny.

**Comment by arkalyanms** [comment]
Moved to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1953822

**Comment by CyrusNajmabadi** [comment]
Closing as this was already moved.
