### ISSUE TITLE
Roslyn inlay hints provider needs to disable itself when the C# LSP editor is active

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72023]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Seeing-duplicated-inline-hints-for-metho/10579803)._

---
I'll experiment more with a repro soon but submitting a ticket now to capture my current state. I see inline hints getting duplicated everywhere right now. 

![image](https://github.com/dotnet/roslyn/assets/1408396/cf0fb9b9-5eed-4b3b-babe-8290c02d9282)
![image](https://github.com/dotnet/roslyn/assets/1408396/53b830f8-196c-40c0-81bb-fbd1d252e728)

---
#### Gus Perez [MSFT] on 2/6/2024, 02:38 PM: 

(private comment, text removed)
#### Feedback Bot on 2/6/2024, 08:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Conclusions from parallel email thread trying to figure out this:

- This is triggered by the new Inlay Hints functionality introduced in 17.10 Preview 1 on LSP
- In this case "C# LSP editor" was enabled, so the Inline Hints implementation from Roslyn was clashing with the new one
- Roslyn inlay hints provider needs to disable itself when the C# LSP editor is active

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/71985.
