### ISSUE TITLE
VS coloring not working fine after commenting code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72030]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-coloring-not-working-fine-after-comme/10579900)._

---
I keep getting coloring issues when commenting code in the latest version of  VS.
Sometimes it takes ages to change the color and sometimes doesn't change the color at all, or only partially.
Check the image below. I commented the code and only the .Services changed to green.

![image.png](https://aka.ms/dc/image?name=B5665e95fed8145c68d40160a736d5f79638428629038557113_20240207-113501-image.png&tid=5665e95fed8145c68d40160a736d5f79638428629038557113)

---
#### Feedback Bot on 2/6/2024, 05:35 PM: 

(private comment, text removed)
#### Roberto Mencia on 2/6/2024, 09:30 PM: 

(private comment, text removed)
#### Feedback Bot on 2/9/2024, 06:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/70522.
