### ISSUE TITLE
`GetRelativePath` in `PathUtilities` crashes with IndexOutOfRangeException

### ISSUE THREAD

**Issue by AnakinRaW** [dotnet/roslyn#72043]
**Version Used**: Current develop

I don't know which design limits exist for the `PathUtilities.GetRelativePath(string, string)` method. I saw there is #52936 talking about to replace that method (at least for .NET Core). Both methods however have slightly different behavior currently regarding some cases. 
E.g., .NET returns `.` for same paths, where as Roslyn Utils returns an empty string. However, I don't know whether these differences have an actual impact. 

Still i noticed when using the Roslyn version, in some (trivial) cases the method crashes. Again, idk, what the expectations of this methods are, so maybe these cases are not considered by design.

**Steps to Reproduce**:
Add a test case as follows to FilePathUtilitiesTests.cs
```cs
[Fact]
public void GetRelativePath_CrashingWithTwoUp()
{
    var baseDirectory = @"C:\Alpha\Beta";
    var fullPath = @"C:\";

    var result = PathUtilities.GetRelativePath(baseDirectory, fullPath);

    Assert.Equal(expected: @"..\..", actual: result);
}

[Fact]
public void GetRelativePath_CrashingWithOneUp()
{
    var baseDirectory = @"C:\Alpha";
    var fullPath = @"C:\";

    var result = PathUtilities.GetRelativePath(baseDirectory, fullPath);

    Assert.Equal(expected: @"..", actual: result);
}
```

**Diagnostic Id**:

For each tests the crash has the following stack trace: 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.

System.IndexOutOfRangeException
Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath) in [redacted]\roslyn\src\Compilers\Core\Portable\FileSystem\PathUtilities.cs:line 567
```

**Expected Behavior**:

The method resolves relative paths correctly. 

**Actual Behavior**:

The method crashes with an `IndexOutOfRangeException`. 

This error occurs if the second parameter has less path parts than the first parameter. 
I think, I already have a fix for that, but i need to test that with some more cases. 
So, if that's an issue that shall be resolve, I can create a PR.

**Comment by jaredpar** [comment]
@RikkiGibson FYI as you're going to be looking at relative paths for some of the interceptors work. This is likely on a diff code path but probably relatively close.
