### ISSUE TITLE
Codefix suggestion: use collection expression spread when collection types don't match

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#72055]
Consider the following case:
```cs
int[] arr = [1, 2, 3];
M(arr); // CS1503 here

void M(List<int> ints)
{
}
```
Since there is no implicit conversion from `int[]` to `List<int>` this code produces `CS1503` error. This can be quickly fixed the following way:
```cs
int[] arr = [1, 2, 3];
M([.. arr]);

void M(List<int> ints)
{
}
```
So I think it makes sense to suggest this as a codefix for the given error. The fix should be available on C# 12 and above and if user didn't explicitly specified they don't prefer collection expressions via an [editorconfig rule](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300#dotnet_style_prefer_collection_expression)

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
