### ISSUE TITLE
Consider Refactoring CommandLineParser

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn#7205]
I'm going to focus on the VB implementation, but it is likely this will be applicable to C#'s as well.

The `Parse` function is ~1240 loc, which is a little monolithic.
[start](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L74)
[end](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L1312)

If the local parameters which are used to produce the final immutable instance of `VisualBasicCommandLineArguments` could be contained with in their own object.
It would permit the big `Select Case` case statement code to be extracted out in discreet functions. 
It will also separate the functionalities of parsing the arguments and creation of the output.

--------------------

Prototype Implementation  #7165 

[Mutable_VBCommandLineArguements](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/blob/cmd/src/Compilers/VisualBasic/Portable/CommandLine/Mutable_VBCommandLineArguments.vb)
[Parse](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/blob/cmd/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L74) ~287LoC
[ARG Functions](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/blob/cmd/src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb#L391) *Note: Move into partial class file*

---------------------------

Those *arg* functions do look to have the same basic method signature, so *could* the CommandLineParser be made simpler? By having the *args "parsers"* be supplied as plugins.

```
Interface I_CLAParser
  Supports() : IEnumerable<string>
  Parse( name : string, value : string,  cmd : Mutable_CLA ) : state
```

**Comment by jaredpar** [comment]
I still don't understand the justification for making this change.  Yes the code is monolithic but the structure is well known to anyone who has done command line parsing.  I don't see any advantage in breaking it up into multiple functions here.

**Comment by AdamSpeight2008** [comment]
More of making the team aware that I'm working on making the `VBCommandLIneParser`, plug-in based. It still a work in progress.  My little research project, to see what affect it has. It may end up being chucked, maybe not.
