### ISSUE TITLE
ForAttributeWithMetadataName could run faster if the tree stored a bit on nodes that contained attributes or not.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#72066]
From a customer reported trace:

![image](https://github.com/dotnet/roslyn/assets/4564579/d61733e1-3f23-4453-b455-afc620ab4209)

This is all time spent in the walk looking down a tree to find attribute-annotated nodes to see if htey match the attribute being searched for.  If we had a .ContainsAttribute bit on nodes, we could skip vast swaths of hte tree, speeding things up.  This would be slightly complex as:

1. attributes are lang specific
2. we have no more bits in NodeFlags.

That said we have many unused bits in SlotCount we could potentially reuse for this purpose.

**Comment by agocke** [comment]
Could this go in the declaration table?

**Comment by CyrusNajmabadi** [comment]
@agocke it would require the decl table to walk the entire tree, which would not be desirable.  right now it can stop at method bodies, only keeping info about if there are extension methods or not.  unfortunately, attributes can exist at an arbitrarily deep depth (since you can have statements inside lambdas, and those statements can be local-functions, and local functions can have attributes).

So in this case, it's nicer if we have that bit at the leaves flow up to the root.

**Comment by agocke** [comment]
Never mind, for some reason I thought ForAttributeWithMetadataName was limited to type declarations.

Maybe, secondarily, that would be a useful API. For example, my source generator only needs to know about partial types so it can implement interfaces. It shouldn't need to scan below the type level

**Comment by CyrusNajmabadi** [comment]
> Maybe, secondarily, that would be a useful API. For example, my source generator only needs to know about partial types so it can implement interfaces. It shouldn't need to scan below the type level

True.  Though ideally with the change i'm making the overhead of that is marginal.  But if we do still see costs (say, diving to the method-level, when only types are needed) we could def enhance things in that fashoin. 

For now, just being able to skip the *vast swaths* of the tree taht do not have attributes will be the big savings.
