### ISSUE TITLE
Scripting API Samples error

### ISSUE THREAD

**Issue by mattwood2012** [dotnet/roslyn#7207]
The example:

    "Create & build a C# script and execute it multiple times"

does not work as there is no "Compile" method for "Script<T>" in Microsoft.CodeAnalysis.Scripting, Version=1.1.0.0

**Comment by kuhlenh** [comment]
Looks like you are using an older version of the scripting API. You should be referencing the namespace ```Microsoft.CodeAnalysis.CSharp.Scripting``` and your script should be type ```CSharpScript```.

I have updated the [samples](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples) to now include a "Getting Started" section with install info for the correct API version.
