### ISSUE TITLE
"Find all references" does not find implementation of "partial void" method

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72083]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-all-references-does-not-find-impl/10581449)._

---
\[severity:It’s more difficult to complete my work\]  
When you have auto-generated code with `partial void` methods the quick link will show you the actual implementation but `find all references` will not. Also `go to implementation` (CTRL-F12 or context menu) does not work either:

![image](https://github.com/dotnet/roslyn/assets/1408396/63480f12-9b0f-426b-bd76-00963280feb2)

![image](https://github.com/dotnet/roslyn/assets/1408396/e8cfa8e7-9320-4dc2-bd9c-80f48d8fdf36)

---
#### Feedback Bot on 2/8/2024, 06:34 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this. Can you please supply a repro?
