### ISSUE TITLE
"Convert to raw string" code fix is not always available for `$@` strings

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#72082]
## Version Used

Visual Studio 2022 Version 17.8.6
Roslyn 4.8.0 - 7b75981cf3bd

## Steps to Reproduce

1. Open a file that already contains a `$@` interpolated string, without changing the code.
2. Move the cursor over the `$@` where the code fix would be present.
3. Open the suggestions menu.

## Expected Behavior

"Convert to raw string" code fix suggestions appear.

## Actual Behavior

They do not appear. In order to make the suggestions appear, usually removing and adding any of the `$@` symbols works, i.e. transforming the syntax tree around the string literal declaration.

## Screenshot

![image](https://github.com/dotnet/roslyn/assets/8298332/49849050-3c09-4352-b158-2945eae0544c)

Note: in the above example, no string interpolation takes place despite declaring the string literal as interpolatable. This does not impact the issue; this also happens with strings that use interpolation.

**Comment by Rekkonnect** [comment]
This might have been fixed with 17.9.0, using Roslyn 4.9.0 - 989117396f26e

**Comment by CyrusNajmabadi** [comment]
Support for this was added.
