### ISSUE TITLE
XML Documation for Primary Constructors does not round trip with automated refactoring

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/roslyn#72096]
**Version Used**: .NET SDK  8.0.200 

**Steps to Reproduce**:

1. Create a class with a constructor that is eligible to be have a primary constructor
2. Add some XML docs to that constructor
3. Run the fixup to convert the constructor to a primary constructor (I used VS Code)
4. Run the fixup to convert the primary constructor back to a normal constructor.

The following is a class that is enough for this

```
/// <summary>
/// My Test Class
/// </summary>
public class TestClass {
    /// <summary>
    /// My Constructor
    /// </summary>
    /// <param name="x"></param>
    public TestClass(int x) {}
}
```

**Expected Behavior**: The xml docs should round trip.

**Actual Behavior**: The summary block on the constructor gets converted to a remarks block, which loses that its part of the constructor.

Some other notes, the generated XML docs for primary constructors are just a direct copy of the class doc comments. Basically what this means is you can write docs for either the primary constructor or the class itself, but theres not a great story for writing docs for both.

**Comment by CyrusNajmabadi** [comment]
By design. There's no mechanism at the lang level to round trip this data. So we do our best in a lossy fashion. 

Absent a change to the language to perfectly preserve things, this is expected.
