### ISSUE TITLE
Typing "<see cref" ends up producing borked code.

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#721]
Ported from TFS WorkItem: **1029279**

---

**Repro Steps:**

If you try to actually type "&lt;see cref" you end up with:

&nbsp;

&lt;see cref="cref"

&nbsp;

I keep running into this and it's really aggravating :)

---

**Revisions:**

1) Created By Cyrus Najmabadi (9/17/2014 12:04:22 PM)

---

2) Edited By Kevin Pilch-Bisson (2/19/2015 3:33:08 PM)

Port to GitHub.

---

**Comment by Pilchie** [comment]
This behavior is not a regression from VS2013.  We can look at a better overtype model here in the future.

**Comment by sharwell** [comment]
Tentatively marked **By Design** since the current behavior was not unintentional; will update with discussion outcome following design review.

**Comment by sharwell** [comment]
This behavior is consistent with the current design as a "muscle memory" behavior, even though it doesn't adhere to the general guidance that "typing complete and correct code should not alter the result". There are a few cases where this is suboptimal for users (`<see langword` and `<see href` being two examples), but at this point the prevalence of `<see cref` with a long history of a specific behavior are keeping this in place.
