### ISSUE TITLE
ParameterSymbol.ToDisplayString/Parts(SymbolDisplayFormat.FullyQualifiedFormat) only outputs the paramter name.

### ISSUE THREAD

**Issue by StefanOssendorf** [dotnet/roslyn#72108]
**Version Used**: 4.8.0

**Steps to Reproduce**:
1. Define a method like this:
```csharp
private void Foo(string a, int b = 1, List<Guid>? list = null) { }
```
2. Run the source generator and get the ParameterSymbol for `List<Guid>? list = null` through `var symbol = semanticModel.GetDeclaredSymbol(parameter)`;

3. Execute `symbol.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat)` and/or `symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)`.

**Expected Behavior**:
`ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)` -> `global::System.Collections.Generic.List<global::System.Guid>? list`
`ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat)` -> An array consisting of SymbolDispaylParts including global qualification.

**Actual Behavior**:
`ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)` -> `list`
`ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat)` -> An array only containing the `list` display part.

**Comment by CyrusNajmabadi** [comment]
This is correct.  The FullyQualified name of a paramter is just it's name itself.

**Comment by StefanOssendorf** [comment]
@CyrusNajmabadi 
I understand that, but the behavior of said methods feel inconsistent.
The call of `ToDisplayString()` without any paramters should also output `list`, like you said. But it outputs `System.Collections.Generic.List<System.Guid>? list`. The same goes for the `ToDisplayParts()`.
Furthmore using `ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)` outputs `List<Guid>? list = null`.
So for me something looks wrong.

**Comment by CyrusNajmabadi** [comment]
Not passing any format uses the `CSharpErrorMessageFormat`.  Which is not the same same as the `MinimallyQualifiedFormat`.

**Comment by CyrusNajmabadi** [comment]
> So for me something looks wrong.

These are all display formats.  Their only use is to be used to display things (not to generate code).  By default, if you pass nothing, you get the exact output the compiler itself uses when printing out these symbols by default (like in error messages).

If you want to customize this, we provide format options.  However, absolutely none of them provide the functionality to use the outputted result as source-code for use in something like a generator.

Note: for *ITypeSymbols* (and *only* those).  We do allow for .ToDisplayString results to be used in generated code.  But not for any other type of symbol.

**Comment by StefanOssendorf** [comment]
Okay, thanks for clarification :)

I jut found it werid for `FullyQualifiedFormat` and `MinimallyQualifiedFormat` not to output the "same" just with different representations.
