### ISSUE TITLE
Code Model: CodeParameter2 in DTE code model has no value for Name after Update 1

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#7210]
This appears to have regressed in Update 1.

**Comment by DustinCampbell** [comment]
It also appears to specifically be a problem with external code parameters

**Comment by davidebbo** [comment]
@DustinCampbell About your comment:

> The issue is that the symbol display system will not return a name for a parameter unless SymbolDisplayParameterOptions.IncludeName is set.

Is this something that could be used as a workaround? e.g. the code we have in our T4 template looks like:

```
var serviceProvider = Host as IServiceProvider;
var dte = (EnvDTE.DTE)serviceProvider.GetService(typeof(EnvDTE.DTE));
var projectItem = dte.Solution.FindProjectItem(Host.TemplateFile);
var project = projectItem.ContainingProject;
var codeRef = project.CodeModel.CreateCodeTypeRef("System.String");
var c = codeRef.CodeType.Members.OfType<CodeFunction2>().FirstOrDefault() as CodeFunction2;
var p = c.Parameters.OfType<CodeParameter2>().FirstOrDefault();
this.WriteLine("Type: {0}", p.Type.AsString); 
this.WriteLine("Name: {0}", p.Name);
```

Is there some way to set `IncludeName` before we make the calls? That would get us going until the fix is out. Thanks!

**Comment by DustinCampbell** [comment]
Unfortunately, there isn't really a good workaround if you're using code model. This is just an implementation detail of how code model is using Roslyn APIs under-the-hood.
