### ISSUE TITLE
Nuget for Microsoft.Net.Compilers.Toolset 4.9.0

### ISSUE THREAD

**Issue by TomaszMaczynski** [dotnet/roslyn#72117]
After updating .NET to version 8.0.200 I started getting this error:

`CSC: Error CS9057 : The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.`

It is thrown both for the 4.8 and .NET 8 projects in the solution.

This seems similar to this issue https://github.com/dotnet/roslyn/issues/70919, as the 4.9.0.0 package is not yet published and 4.8.0.0 is referenced in my solution.

**Version Used**: 
.NET 8.0.200
VS 17.8.7

**Comment by JoeRobich** [comment]
The 8.0.200 SDK ships with Roslyn 4.9.0 and analyzers built against 4.9.0. Until a final 4.9.0 package is published to NuGet you could use the last preview version ([4.9.0-3.final](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/4.9.0-3.final)) as a workaround.

**Comment by jaredpar** [comment]
@TomaszMaczynski are you using the Microsoft.Net.Compilers.Toolset package directly? That is not a supported operation. From the README

> This package is primarily intended as a method for rapidly shipping hotfixes to customers. Using it as a long term solution for providing newer compilers on older MSBuild installations is explicitly not supported. That can and will break on a regular basis.

**Comment by jaredpar** [comment]
Gotcha. In that case though, please take this issue up with them. They are using an unsupported package. The documentation for the NuGet clearly states its unsupported and that it can and will break on a regular basis. We don't plan on making any changes here to make the package more usable.
