### ISSUE TITLE
Spread Operator with possible null value gives no compile time warning if nullable enabled

### ISSUE THREAD

**Issue by Lumoryel** [dotnet/roslyn#72121]
**Version Used**: 
C# Language Version 12, VS2022 17.8.7

**Steps to Reproduce**:

1. Run the following code
```
        #nullable enable
        int[]? aInts = null;
        int[] aCombined = [.. aInts];
```

https://gist.github.com/Lumoryel/4a6c48ec5b94475df0dbb50afefef807

**Expected Behavior**:

Compile Time Warning/Error when having nullable enabled

**Actual Behavior**:

No warning, but runtime exception

> System.NullReferenceException: 'Object reference not set to an instance of an object.'
> Local2 was null.

**Comment by RikkiGibson** [comment]
#72051 tracks the same issue.
