### ISSUE TITLE
`RazorSourceGenerator` failed to initialize when building ASP.NET/Razor project in VS 17.10 Preview 1

### ISSUE THREAD

**Issue by premun** [dotnet/roslyn#72139]
**Version Used**: 
Started happening in Visual Studio 17.10.0 Preview 1.0. Building the same project from console works.

**Steps to Reproduce**:

1. `git clone https://github.com/dotnet/arcade-services`
2. Open `arcade-services.sln` in Visual Studio 17.10.0 Preview 1.0
3. Build the `Maestro.Web` project

Compiling from console works (plain `dotnet build`).  
Visual Studio 17.9 Preview 5.0 works too.

**Diagnostic Id**:

`CS8784`

**Expected Behavior**:

I am able to compile the `Maestro.Web` project.

**Actual Behavior**:

Visual Studio gives the following error:

> Error	CS8784	Generator 'RazorSourceGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'TypeLoadException' with message 'Type 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1[TInput]' from assembly 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is attempting to implement an inaccessible interface.'.	Maestro.Web
D:\repos\arcade-services\src\Maestro\Maestro.Web\CSC

**Comment by lucadistefano** [comment]
same problem here, it occurs only with  17.10.0 Preview 1.0. With command line and vs 17.9.0 works

**Comment by JoeRobich** [comment]
I believe this is fixed by https://github.com/dotnet/roslyn/pull/72057

**Comment by tuhincse24** [comment]
Once, after updating to Visual Studio 17.10.0 Preview 1.0, I experienced the same issue. With command line and vs 17.9.0 works

**Comment by jjonescz** [comment]
Closing as duplicate. I see you also updated your repo to use SDK 8.0.200 which should fix the issue for you.
