### ISSUE TITLE
Missing opportunity for a collection expression in a value tuple

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/roslyn#72169]
**Version Used**: 
17.10.0 Preview 1.0

**Steps to Reproduce**:
```cs
public (int, List<int>) M() {
  return (42, new List<int>());
}
```

**Diagnostic Id**: none

**Expected Behavior**:
I don't see a reason why the `new List<int>()` expression couldn't be replaced by `[]`, so I expect code analysis to suggest that.
Doing it manually works:
```cs
public (int, List<int>) M() {
  return (42, []);
}
```

**Actual Behavior**:
Nothing is suggested.

**Comment by RikkiGibson** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Yup!
