### ISSUE TITLE
Unused byref dereference is removed despite NRE as a side effect

### ISSUE THREAD

**Issue by EgorBo** [dotnet/roslyn#72165]
Roslyn should not optimize unused byref dereferences due to possible side effect of NRE. E.g. https://github.com/dotnet/runtime/pull/98547/files PR used such dereferences intentionally to throw NRE before we enter unmanaged code.

**Version Used**: 
Reproduces in .NET 8.0 and in Main on Sharplab.

**Steps to Reproduce**:

```cs
static void Test(ref byte b)
{
    _ = b; // dereference, hence, NRE as a side effect
}
```

**Expected Behavior**:

```cil
.method assembly hidebysig static Test (uint8& b)
{
    .maxstack 8
    ldind.u1
    pop
    ret
}
```

**Actual Behavior**:

```cil
.method assembly hidebysig static Test (uint8& b)
{
    .maxstack 8
    ret
}
```

**Comment by stephentoub** [comment]
It properly keeps it for pointers, so this seems like it's an issue only for managed pointers / refs:
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwGYACbUgYVIG9DSHyyBXGAZwgDMBTcgFlIBZHAApgATwTcAVKQAOASlr1GqgPqkAvKWlyA3CoYBfQ6VMlSrDj35CsIgE7dOpCVPlK6BVeq3yD3owmBEZAA=)

**Comment by hamarb123** [comment]
Seems like a dupe of https://github.com/dotnet/roslyn/issues/71487 ;)

**Comment by EgorBo** [comment]
Thanks, closing as a dup. I guess a "proper" fix for this might result into tons of stloc/ldoc spills to preserve various orders of side-effects everywhere. Since the managed code can't create null byrefs without unsafe help it's probably fine to do that.
