### ISSUE TITLE
Remove unnecessary imports analyzer is significantly slowing builds (11% CPU time)

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn#72162]
![image](https://github.com/dotnet/roslyn/assets/31348972/234898f0-4e12-42c5-a41a-78712f3df600)

@mavasani How can this be disabled? I already have `dotnet_diagnostic.IDE0005.severity = none` in `.globalconfig` file.

**Comment by Youssef1313** [comment]
@lonix1 The one in the screenshot? It is PerfView.

**Comment by sharwell** [comment]
@Youssef1313 I think this may be a red herring. The analyzer does almost no actual work. It just instructs the compiler to complete work it would already complete, and then then waits for that work to finish.

**Comment by Youssef1313** [comment]
@sharwell This was solely through binlog times and profiling with PerfView. I agree that likely the total time may not be affected. It indeed looks like a cost that "moved" from the compiler to the analyzer.

The remaining issue here will still be why it's running even with `dotnet_diagnostic.IDE0005.severity = none`

**Comment by sharwell** [comment]
@Youssef1313 it's running because the following line incorrectly sets `hasAnyCodeStyleOption` to true:
https://github.com/dotnet/roslyn/blob/cecdb802007a49e346215c0afdce354d6c111112/src/Analyzers/Core/Analyzers/RemoveUnnecessaryImports/AbstractRemoveUnnecessaryImportsDiagnosticAnalyzer.cs#L31
