### ISSUE TITLE
SourceGenerator AttributeData.ToString() for attribute with param array not compilable

### ISSUE THREAD

**Issue by codetuner** [dotnet/roslyn#72182]
Within SourceGenerators, querying for attributes of an IPropertySymbol returns a collection of AttributeData objects.

The ToString() method of AttributeData usually returns a compilable representation of the attribute.

I.e. for the following attribute decoration:
```
[StringLength(50, MinimumLength = 2, ErrorMessage = "Name must be between 2 and 50 chars.")]
```
The AttributeData.ToString() returns:
```
[System.ComponentModel.DataAnnotations.StringLengthAttribute(50, MinimumLength = 2, ErrorMessage = "Name must be 
between 2 and 50 chars.")]
```
which can be written in source code and compiled.

However, this does not work with attributes having param array arguments such as the [DeniedValues] attribute of the DataAnnotations namespace. The representation of:
```
[DeniedValues(0, 666)]
```
via AttributeData.ToString() becomes:
```
[System.ComponentModel.DataAnnotations.DeniedValuesAttribute({0, 666})]
```

The curly braces around the parameters make the expression invalid for compilation.

A working reproduction can be found in:
https://github.com/codetuner/SourceGenArrayAttrIssue

Get the code and compile it. It works. But uncomment the `[DeniedValues]` attribute in the **SourceGen.SampleDomain\\Person.cs** file, and compilation fails.

**Comment by CyrusNajmabadi** [comment]
Closing out.  ToString is to get a displayable version of an object.  It is not to produce code to be compiled.  This is expected behavior.

**Comment by CyrusNajmabadi** [comment]
More info: Source generators should not call ToString on objects in an attempt to get legal c# code that they can compile.  That is explicitly not supported and as a non-goal of the roslyn object model.

The *singular* exception are `ITypeSymbol`s (and its descendent interfaces).  You can call ToString on this to produce a string that should be parsable into a legal `TypeSyntax` node.  If that doesn't work in some case, we would likely consider that a bug we'd want to fix.  

Thanks!

**Comment by codetuner** [comment]
Fair enough. Thanks for the information. It means I do have to write a lot of code very similar to what is already written, just for small differences. But you are right, ToString is meant for displayable representations, and only that...
