### ISSUE TITLE
Generate a class or type in Visual Studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72209]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generate-a-class-or-type-in-Visual-Studi/1382117)._

---
In VS2017 we had the ability to do TDD e.g. type the following where Person class does not exists.

`Person person = new Person();`

Use the lightbulb and get
! [F1.png] (https://aka.ms/dc/image?name=Bb507816e427d4ca19bc93a1c63495f27637522890470292211_F1.png&tid=b507816e427d4ca19bc93a1c63495f27637522890470292211)

I have the current release of VS2019 and don't see this option. If it's gone would like to see this again in VS2019 and if not gone what have I missed.

---
#### Feedback Bot on 3/25/2021, 11:53 PM: 

(private comment, text removed)

**Comment by Cosifne** [comment]
The feature is in VS 2019.
