### ISSUE TITLE
There's no way to check if an IOperation node contains diagnostics

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7221]
Currently there's no way to tell if an operation node has errors in it. There's a ContainsDiagnostics property for syntax but that's only true if there are syntax diagnostics. Operations should have the semantic equivalent of that.

**Comment by JohnHamby** [comment]
The property IOperation.IsInvalid now exists. It doesn't precisely capture whether or not diagnostics are present, but it does capture whether or not the operation has reliable semantic information.
