### ISSUE TITLE
Unbound invocations don't produce an InvocationExpression operation

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7222]
An analyzer that registers an OperationAction on InvocationExpression doesn't get invoked for the following code:

```vb.net
Public Sub M()
      UnboundMethod()
End Sub
```

At the syntax level, we know that this is an invocation expression but the bound tree for it says it's a bad expression because it cannot bind the method (say a using was missing). We should instead have some error recovery here and have an InvocationExpression operation with a null symbol instead.

**Comment by srivatsn** [comment]
Note that this only happens for VB. Unbound invocations in C# fire an operation action.

**Comment by lgolding** [comment]
As part of fixing this issue, please remove the `Skip` property from the `Fact` attribute on the unit test `VisualBasic_CA1024NoDiagnosticOnUnboundMethodCaller`. That test should then pass.

**Comment by JohnHamby** [comment]
This seems to be a general issue with the VB compiler--expressions that have semantic issues become Bad bound trees. It's perhaps appropriate to move this issue to someone on the compiler team.

**Comment by srivatsn** [comment]
Tagging @AlekseyTs @gafter @jaredpar

**Comment by AlekseyTs** [comment]
It could be a property access, an array access and maybe something else as well.

**Comment by JohnHamby** [comment]
It should be possible to produce a BadParameterizedExpression or some such that preserves what is known. For example, if the target does not bind, the arguments are still useful. If one argument does not bind, the other arguments and the target are still useful.

**Comment by AlekseyTs** [comment]
BoundBadExpression preserves what is known as child nodes.

**Comment by JohnHamby** [comment]
Is it possible to tell that the children include a method/collection target and a set of arguments/indices?

**Comment by JohnHamby** [comment]
Nothing is going to get done about this for the foreseeable future.
