### ISSUE TITLE
C# compiler no longer allows you to call a method with a signature containing an internal-visible-to no-pia type

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7223]
This is a regression from C# 5. Have not tried VB to see if it also regressed.

Given Interop.dll that was built from this:
``` C#
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: PrimaryInteropAssembly(1, 0)]
[assembly: Guid("01C50CE8-1C33-47EA-9895-5F3B28AF8C52")]
[assembly: InternalsVisibleTo("Csc")]
[assembly: InternalsVisibleTo("CodeAnalysis")]

[ComImport()]
[ComVisible(false)]
[Guid("C1F63D0C-4CAE-4907-BE74-EEB75D386ECB")]
[InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IInteropType
{
}
```

And given CodeAnalysis.dll that was built from this:
``` C#
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Csc")]

internal class Base
{
    public virtual void Method(IInteropType type)
    {
    }
}
```

Compile this: Derived.cs

```
using System;

internal class Derived
{
    public void Foo()
    {
        Base b = new Base();
        b.Method(null);
    }
}
```

Running the following csc command-line:

```
csc.exe /noconfig /nostdlib+ /reference:CodeAnalysis.dll /link:Interop.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll" /out:obj\Debug\Csc.dll /target:library Derived.cs 
```

In C# 6.0, you get:
```
CS1748	Cannot find the interop type that matches the embedded interop type 'IInteropType'. Are you missing an assembly reference?
```

C# 5.0 successfully compiles.

**Comment by davkean** [comment]
I added the bug label, but @AlekseyTs thinks that this behavior is somewhat expected and thinks we should disallow the embedding of internal no-pia types.

**Comment by jaredpar** [comment]
@AlekseyTs was this an intentional break?  If so can we provide the justification on this bug for documentation.

**Comment by davkean** [comment]
Just to add some information around how I hit this, I was trying convert [IVsSqm](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/CSharp/Portable/Utilities/IVsSQM.cs) into a no-pia type. Without above, the type will need to be made embedded as "public" in Microsoft.CodeAnalysis. Public in is quotes, because C#/VB won't actually let you see or consume it, but it will show up in the public API checker.

**Comment by AlekseyTs** [comment]
Here is a quote from NoPIA Compiler Spec:

4.3 Replacing IA types with local types
In order to eliminate all references to the original interop assembly the compilers creates 
local types for the following **public** IA types that are used in the program: 
•	Interface
•	Delegates and events
•	Enums
•	Structs

So, in my opinion it is a bug that compiler embeds an internal type, it should report an error instead. 
Also, if we decide to allow unification of internal types instead, I don't think this will prevent anyone from using the type because they can always create a PIA with the type and grant whatever access they want to it.

**Comment by AlekseyTs** [comment]
Additional info:
Even though native compilers (both VB and C#) do not report any errors, they produce unverifiable assembly (apparently CLR refuses to unify non-public types):
```
peverify Csc.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [Csc.dll : Derived::Foo] Type load failed.
[IL]: Error: [Csc.dll : Derived1::Method] Type load failed.
[token  0x02000004] Type load failed.
3 Error(s) Verifying Csc.dll
```

Derived1 is defined as follows:
```
internal class Derived1 : Base
{
    public override void Method(IInteropType type)
    {
    }
}
```

**Comment by davkean** [comment]
Interesting, so the issue is that we're allowing the embedding of internal types.

**Comment by AlekseyTs** [comment]
Yes, I think this is where the bug is.

**Comment by jaredpar** [comment]
> Interesting, so the issue is that we're allowing the embedding of internal types.

Confused: are you referring to an issue in the native or Roslyn compiler?

**Comment by davkean** [comment]
The Roslyn compiler.

**Comment by AlekseyTs** [comment]
Both native and Roslyn compilers have this issue.

**Comment by jaredpar** [comment]
At this point I believe the best path forward for this bug is "Won't Fix".  Both compilers have this issue and due to compat it's unlikely we would ever change this behavior.
