### ISSUE TITLE
Enumerable.Empty and IDE0301

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/roslyn#72231]
I have this code:

    public IEnumerable<int> Ids { get; set; } = Enumerable.Empty<int>();
    
And I get the suggestion to use:

    public IEnumerable<int> Ids { get; set; } = [];

But in the dotnet souce code [(here)](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Enumerable.cs) there is a note:

> // explicitly not using [] in case the compiler ever changed to using Enumerable.Empty`

`public static [IEnumerable](https://source.dot.net/System.Private.CoreLib/A.html#3acf01620172c7f0)<TResult> [Empty](https://source.dot.net/System.Linq/R/4d026772cf3399f5.html)<TResult>() =>
            [Array](https://source.dot.net/System.Private.CoreLib/A.html#156e066ecc4ccedf).[Empty](https://source.dot.net/System.Private.CoreLib/A.html#bc9fd1be0e4f4e70)<TResult>(); // explicitly not using [] in case the compiler ever changed to using Enumerable.Empty`

I think this is a special case that needs attention.

**Comment by CyrusNajmabadi** [comment]
This is working properly. Closing out as the engine runtime's comment does not apply.

**Comment by qsdfplkj** [comment]
But the reason that is mentioned in the source code. Should I use the same reasoning and not use [] or can i safely apply "[]" syntrax?

**Comment by chrisoverzero** [comment]
> But the reason that is mentioned in the source code.

The reason that is mentioned in the source code is that `[]` currently resolves to `Array.Empty<T>()` and they want to guard against its resolving to `Enumerable.Empty<T>()` in the future. What would be so bad about `[]` resolving to `Enumerable.Empty<T>()`? This is the _definition_ of `Enumerable.Empty<T>()` – they're avoiding a circular definition.

So (as @CyrusNajmabadi said) the engine runtime's comment doesn't apply. Use `[]` for _your_ `IEnumerable<T>` values freely and without worry.

**Comment by CyrusNajmabadi** [comment]
The reasoning is specific to that particular location of code, and has nothing to do with any other locations at all.

> Should I use the same reasoning 

No.  You are not the implementation of `Enumerable.Empty`.  

> or can i safely apply "[]" syntax?

'safe' is up to you.  As the feature says, this may change semantics.  Specifically, we will compile this to `Array.Empty<T>()`.  That may be different than `Enumerable.Empty`.  so it' up to you if that's ok.
