### ISSUE TITLE
Separate closures for anonymous functions with distinct capture lists.

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#7224]
As shown [here](http://blogs.msdn.com/b/ericlippert/archive/2007/06/06/fyi-c-and-vb-closures-are-per-scope.aspx), C# and VB compilers create one closure per scope, no matter how many anonymous functions there are and what their (non-empty) capture lists are:

```c#
Func<Cheap> M(){
  Cheap c = new Cheap();
  Expensive e = new Expensive();
  Func<Expensive> shortlived = ()=>e;
  Func<Cheap> longlived = ()=>c;
  // use shortlived
  // use longlived
  return longlived;
}  
```

The `longlived` function is closed over both `c` and `e`, consuming additional memory. Separate closures should be created for functions that have completely distinct capture lists.

**Comment by gafter** [comment]
Unfortunately, doing this would be a performance regression for many programs, due to the increased memory pressure from the additional closure objects.

**Comment by orthoxerox** [comment]
Hm, what about recognizing this situation and emitting a warning/info? "`e` won't be garbage collected until `longlived` is garbage collected. Consider setting `e` to `null` before returning from the function`"

**Comment by svick** [comment]
@orthoxerox I don't think that a warning would be appropriate for "there is a small chance this is a performance issue", usually warnings are for "there is a large chance this is a correctness issue".

 An analyzer would make sense, but it seems [something like that already exists](https://github.com/mjsabby/RoslynClrHeapAllocationAnalyzer) (it tells you which variables are captured by a lambda).

**Comment by controlflow** [comment]
@gafter how about "regressing" real source of real memory leaks in C# programs? If C# is in care of real memory pressure, how about "regressing" C# programs allocating multiple times where one display class is enough?

```c#
class C {
  System.Func<int> M(int x) {
    int y = x + 1; // <>c__DisplayClass0_0
    if (y > 0) {
        int z = y + 1; // <>c__DisplayClass0_1
        return () => y + z;
    }
      
    return null;
  }
}
```

If you considering splitting the display class as a breaking change, just solve the problem at most scenarios in another *great way*: infer variables captured into closure *by value* and unlift them from display class fields. This solves most of the problems of intersecting closures, this increases performance of captured variables access outside of closure. I know that's hard to support in debugger/edit&continue/other tooling, but you can at least implement this in `/release` mode.

**Comment by gafter** [comment]
In those rare cases that you discover there is a performance issue, you can hand-craft the closure objects to get precisely the behavior you want. I don't think we would do anything in the language for this.
