### ISSUE TITLE
EnC: Changing the type of a locked expression should be a rude edit

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#72240]
- Similar to https://github.com/dotnet/roslyn/issues/3627

```cs
public void M()
{
    var x = new C();
    lock (x) {  }
}
```

When inside the lock statement body, changing from `new C` to `new Lock` or vice versa likely executes wrong unlocking code now (and probably crashes because the synthesized variables are not mapped correctly).

We should update EnC analyzer in the IDE to prohibit changes to the type of the lock expression around an active statement.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/pull/74526
