### ISSUE TITLE
Encoding parameter behavior in SourceText.From differs depending on file size

### ISSUE THREAD

**Issue by m0sa** [dotnet/roslyn#7225]
I stumbled upon this while investigating a bug in assemblies generated by [StackExchange.Precompilation](https://github.com/StackExchange/StackExchange.Precompilation/commit/f48a922b7632e21b9cbc29aaa6d2982db745d133), where VS wasn't hitting breakpoints in some files, claiming they differ from the ones used to compile the assembly, while others worked perfectly.

Digging into the issue I found that the encoding passed into `SourceText.From` affects streams of different sizes differently, ultimately leading to wrong (or correct, depending on how you see it) source hashes in the emitted PDB.

I've created [this gist](https://gist.github.com/m0sa/b7bb3b1f1315a12f05df) to repro the behavior. It generates 2 classes, and saves each one of them as UTF8 and UTF8 with BOM. I then compile all 4 files with csc, as well as via the Roslyn API, passing one of the encodings to `SourceText.From`. Turns out the BOM headers seem to be affecting only the hash generated by `LargeEncodedText` when the stream passed in has no BOM, but the encoding defines it.

This inconsistency should be corrected either by fixing the behavior of the (normal) `SorceText`, so it's affected by the BOM flag in the encoding too, or fix the `LargeEncodedText` so it's not affected by it.

**Comment by jaredpar** [comment]
Thanks for the detailed repro!  We'll take a look at this.

**Comment by cston** [comment]
Fixed in #7641

**Comment by cston** [comment]
Fixed in #7665
