### ISSUE TITLE
Doc comment completions should not insert `=""` if there is already one

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#72259]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
class C
{
    /// <summary>
    /// <see cref=""/>
    /// </summary>
    void M()
    {
    }
}
```
Try to replace `cref` with other valid attrribute, e.g. `langword`

**Expected Behavior**:
`cref` is replaced with `langword`

**Actual Behavior**:
An additional `=""` is added:
![devenv_XIDJACNtsz](https://github.com/dotnet/roslyn/assets/70431552/10458778-6215-4371-9d4a-738479046c42)

**Comment by sdelarosbil** [comment]
Can I take this one?

**Comment by DoctorKrolic** [comment]
Sure)

**Comment by CyrusNajmabadi** [comment]
Yes.  Feel free.  Note: if something is in `help wanted`, and `small fixes` and `backlog`, def just feel free to take.  :)

**Comment by sharwell** [comment]
> Yes. Feel free. Note: if something is in `help wanted`, and `small fixes` and `backlog`, def just feel free to take. :)

Yep, and most items in Small Fixes are going to meet these conditions. Depending on how complex the fix is, you can either comment on the issue saying you are working on it, or just send a PR that links to it.
