### ISSUE TITLE
type hints for collection expressions

### ISSUE THREAD

**Issue by ZacharyPatten** [dotnet/roslyn#72250]
# Proposal

There should be a setting to enable type hints for [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions). If enabled, it would show types like the existing "`Show hints for implicit object creation`" setting in IDEs but for [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions):
![image](https://github.com/dotnet/roslyn/assets/3385986/c5223f9e-6e64-4f92-8e66-346f33ac5b59)

Ideally, there should be a dedicated setting for [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions) type hints:
![image](https://github.com/dotnet/roslyn/assets/3385986/2fe9d640-dbc4-4451-a488-f4bdef0b0e67)

_<sup>note: edited screenshots are from Visual Studio 2022</sup>_

# Background and Motivation

[Collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions) were added in C# 12 along with [`IDE0028`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0028?pivots=dotnet-8-0)'s automatic fix that encourages the use of [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions) over previous construction syntax. However, [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions) don't currently support type hints, so developers who prefer to see type hints have to keep using previous construction syntax and suppress or ignore [`IDE0028`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0028?pivots=dotnet-8-0).

**Comment by CyrusNajmabadi** [comment]
@MisinformedDNA Yes, this suggestion is still valid.  THis is about showing an inline-hint that tells you what the type of the collection expr is that is being created.

**Comment by ZacharyPatten** [comment]
@akhera99 🎉 thanks 👍🏼
