### ISSUE TITLE
Remove compat workaround for interceptors file path lookup.

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#72265]
Related to #71879
https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md

> Temporarily, for compatibility purposes, when the initial matching strategy outlined above fails to match any syntax trees, we will fall back to a "compat" matching strategy which works in the following way:
> - A *mapped path* of each syntax tree is determined by applying [`/pathmap`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.commandlinearguments.pathmap?view=roslyn-dotnet-4.7.0) substitution to `SyntaxTree.FilePath`.
> - For a given `[InterceptsLocation]` usage, the `filePath` argument value is compared to the *mapped path* of each syntax tree using ordinal string comparison. If exactly one syntax tree matches under this comparison, that is the *referenced syntax tree*. Otherwise, an error occurs.
> 
> Support for the "compat" strategy will be dropped prior to stable release.

Note: this issue is referenced in src/doc

**Comment by RikkiGibson** [comment]
Maybe we will end up using this issue to track entirely removing path-based interceptors (in favor of checksum-based.)

**Comment by jaredpar** [comment]
@RikkiGibson check to see if we still need this.

**Comment by RikkiGibson** [comment]
if we are removing this at the same time as filepath-line-col then close htis issue out and refer to it over there

**Comment by RikkiGibson** [comment]
The filepath-line-column scheme will be completely removed when support for .NET 8 is dropped, which means this compat workaround will also be removed at that time. #72855

**Comment by RikkiGibson** [comment]
The filepath-line-column scheme will be completely removed when support for .NET 8 is dropped, which means this compat workaround will also be removed at that time. #72855
