### ISSUE TITLE
Pasting content into raw string doesn't respect smart ident

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#72267]
**Version Used**: 
Latest `main`

**Steps to Reproduce**:
```cs
var rawString = """
    class C
    {
        [SomeAttribute]$$
        void M()
        {
        }
    }
    """;

var contentToCopy = "[MyAttribute]";
```
Copy value of `contentToCopy`
Place caret at `$$`
Press enter
You will appear at this state:
```cs
var rawString = """
    class C
    {
        [SomeAttribute]
        $$
        void M()
        {
        }
    }
    """;

var contentToCopy = "[MyAttribute]";
```
At this point this is smart ident mode and there is no actual spaces at the new line
Now try to paste

**Expected Behavior**:
Either ident mode doesn't work in raw strings at all (after all, they can have any content inside them, not just other code) or the result of operations above is:
```cs
var rawString = """
    class C
    {
        [SomeAttribute]
        [MyAttribute]
        void M()
        {
        }
    }
    """;

var contentToCopy = "[MyAttribute]";
```

**Actual Behavior**:
Value is pasted at the beginning of a raw string line:
```cs
var rawString = """
    class C
    {
        [SomeAttribute]
    [MyAttribute]
        void M()
        {
        }
    }
    """;

var contentToCopy = "[MyAttribute]";
```
However, if you leave smart ident mode and force spaces e.g. by pressing space and then backspace value is pasted as expected

**Final demonstration gif:**
![pasteintorawstring](https://github.com/dotnet/roslyn/assets/70431552/15a96155-bdf4-4ef0-8324-d3fc0eaef8ea)

**Comment by DoctorKrolic** [comment]
Debugged a problem a little bit and here are my results. It looks like there is a conflict between 2 features: smart ident and [string copy-paste](https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharp/StringCopyPaste/StringCopyPasteCommandHandler.cs). Basically what happens is:
- StringCopyPaste comes in the command handler chain before smart ident
- [It executes the next handler](https://github.com/dotnet/roslyn/blob/e3d617bc46b0f92c2d2438188b35e009b942d0d1/src/EditorFeatures/CSharp/StringCopyPaste/StringCopyPasteCommandHandler.cs#L91-L93), letting the smart ident make its chages
- Smart ident only makes 1 change, so [the guarding check](https://github.com/dotnet/roslyn/blob/e3d617bc46b0f92c2d2438188b35e009b942d0d1/src/EditorFeatures/CSharp/StringCopyPaste/StringCopyPasteCommandHandler.cs#L109-L112) doesn't catch it as a conflict
- StringCopyPaste then creates its own change, putting pasted text at the beginning of a raw string line and applies it, overriding what smart ident did
- As a result if you undo a change after pasting, you get the correct change from smart ident:
![pasteintorawstring](https://github.com/dotnet/roslyn/assets/70431552/0578abde-58d1-4d39-904b-26a412fb8beb)

@CyrusNajmabadi I remeber when I did similar analysis for [raw string indentation line issue](https://github.com/dotnet/roslyn/issues/67821) you came up with a fix and implemented it really quickly. So can you please take a look here, maybe there is a quick and easy fix for this issue as well

**Comment by CyrusNajmabadi** [comment]
I dont' really have a view on what to do here.  But can StringCopyPaste check the state of the world prior to callingt eh next handler, then see what the next handler did (wrt to virtual space) and then take that into account for the final change it wants to make?

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback here.
