### ISSUE TITLE
Unnecessary assignment ... message - incorrect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72278]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unnecessary-assignment--message---inc/10600358)._

---
[severity:It's more difficult to complete my work]
If in a VB line you have say x = 10 then later x = 20 & x is not changed between these values or x is not referred to elsewhere then the "Unnecessary assignment ..." message is correct.  However when displaying a listview line say lvw = lvwJobs.Items(x) this line is reported incorrectly as "Unnecessary assignment ..." - the difference is that this line is assigning an object reference whereas x = 10 & x = 20 is simply setting a value to a previously defined variable

---
#### Feedback Bot on 2/25/2024, 07:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing as we are not ingesting in this space.
