### ISSUE TITLE
Allow concurrent analyzers to throttle concurrency in the presence of mutable state

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7228]
https://github.com/dotnet/roslyn/pull/7184 added support for enabling analyzers to mark themselves for concurrent execution.

@JohnHamby pointed out that we need to enhance the API to allow analyzer authors to throttle concurrency in specific analysis contexts in the presence of mutable state. This item tracks designing and implementing this feature.

**Comment by CyrusNajmabadi** [comment]
@mavasani it doesn't seem like anythnig has happened here in 7 years.  We can likel close this out as something we're nto going to do, right?

**Comment by mavasani** [comment]
Yes, closing it out
