### ISSUE TITLE
Confusing error messages

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7229]
```
static void Main(string[] args) {
    System.Action<args[2]> a = null;
}
```
Errors reported:
```
dt.cs(6,21): error CS0103: The name 'a' does not exist in the current context
dt.cs(6,9): error CS0119: 'Action' is a type, which is not valid in the given context
```
It should probably show an error for the nonsense in the type parameter, but does not and recovery gets very confused. The formatter seems to treat the l-value as an expression when autoformatting.

Please post more if you find any.

**Comment by gafter** [comment]
There is no type parameter here, and no syntax error. There is just an expression statement
```cs
System.Action  <  args[2]  >  a = null;
```
and the two errors reported by the compiler are correct. The compiler correctly suppresses the error that the left-hand-side of the assignment isn't an lvalue.

**Comment by leppie** [comment]
Thanks for the explanation ;)
