### ISSUE TITLE
Getting ghost lightbulbs lately

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn#72310]
**Version Used**: 
Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.10.0 Preview 2.0 [34626.289.main]

**Steps to Reproduce**:

1.  you can use a repo https://github.com/timheuer/alexa-skills-dotnet
2. open Response.cs
3. cursor over line 16

**Expected Behavior**:
lightbulb has a suggestion

**Actual Behavior**:
lightbulb shows but clicking just makes it disappear

https://github.com/dotnet/roslyn/assets/4821/2107e2b2-3441-4ed6-b81b-5a531cd02560

**Comment by CyrusNajmabadi** [comment]
This likely indicates one of the code action computations threw an exception.  @akhera99 please see if you can repro under a debugger.  we also likely should try to make the lightbulb resilient to a particular action crashing if that's what is going on here.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of movement and no additional reports of this.
