### ISSUE TITLE
CA1012 Abstract type should not have public constructors

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/roslyn#72330]
**Version Used**: 
17.9.2

**Steps to Reproduce**:
With ```<AnalysisLevel>latest-all</AnalysisLevel>```

Compile this code:
```
public abstract class Foo {

    public Foo() { }

}
```

The problem is that the warning is squiggly line is in the wrong place which makes it take more time to resolve the issue.

It currently shows this:
```
public abstract class Foo {
                      ~~~
    public Foo() { }

}
```

but I think it should show this:
```
public abstract class Foo {

    public Foo() { }
    ~~~~~~
}
```

**Diagnostic Id**:
CA1012

**Expected Behavior**:
The squiggly line is under the code needing to be changed.

**Actual Behavior**:
The squiggly line is under the type name.

**Comment by CyrusNajmabadi** [comment]
Can you move this to Roslyn-analyzers?

**Comment by TonyValenti** [comment]
Moved to https://github.com/dotnet/roslyn-analyzers/issues/7218
