### ISSUE TITLE
[Bug]: Suggestion `IDE0300` does not appear for arguments in primary constructor's base class constructor

### ISSUE THREAD

**Issue by just-ero** [dotnet/roslyn#72337]
### Version Used

- Compiler version: 4.10.0-2.24102.11 (b14dc4dc)
- VSCode: 1.87.0, 019f4d1419fbc8219a181fab7892ebccf7ee29a2, x64
- C# extension: v2.18.16, C# Dev Kit Extension: v1.3.10

### Steps to Reproduce

1. Open or create any C# project in Visual Studio Code.
2.
   ```cs
   class Class1(int[] arr);
   
   class Class2() : Class1(new int[] { 1, 2, 3 });
   ```
   (Side note: this also suffers from #72334, regardless of whether `Class2` has a body or not.)

### Expected Behavior

Suggestion `IDE0300` appears on the `new int[] { 1, 2, 3 }` argument.

### Actual Behavior

Suggestion `IDE0300` does not appear. For comparison, the suggestion *does* appear if a normal constructor is used.

**Comment by sdelarosbil** [comment]
Hey, can I take this?

**Comment by CyrusNajmabadi** [comment]
Definitely :)
