### ISSUE TITLE
[Question] How to use functionality from nuget packages in project referenced source generator

### ISSUE THREAD

**Issue by Drake53** [dotnet/roslyn#72356]
I'm trying to write a source generator which parses a .json file. Since source generators must be .net standard 2.0 there's no built-in json parsing library and I need to add a reference to either newtonsoft.json or system.text.json. The documentation for this:
https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md#use-functionality-from-nuget-packages

However, this only seems to work when consuming the generator as a nuget package. When the generator is added through a project reference this solution doesn't seem to work.

Found a question on stackoverflow with the same issue but no answer, linking it here for reference:
https://stackoverflow.com/questions/77895226/add-system-text-json-to-incremental-source-generator

**Comment by jaredpar** [comment]
@333fred, @chsienki do we have guidance for how to best copy the dependencies in the direct reference case?

**Comment by chsienki** [comment]
We don't have any guidance. I haven't looked into it, but I assume you would also need to pass the dependency as an analyzer, because it won't get picked up by default otherwise. If you reference the dependency in the _consuming_ project too, and set `GeneratePathProperty` you can then pass the binaries as analyzers also. So something like

```xml
<ItemGroup>
    <!-- The generator project -->
    <ProjectReference Include="..\MyProject\MyProject.csproj" OutputItemType="Analyzer" />

    <!-- The dependencies of the generator -->
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" PrivateAssets="all" GeneratePathProperty="true" />
 
    <!-- Include the assemblies of the generator as analyzers -->
    <Analyzer Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\*.dll" />

</ItemGroup>
```

**Comment by Drake53** [comment]
Thanks for the response. Unfortunately, this solution doesn't really seem to work for me.
While it fixes the dll not found issue, I'm still getting a TypeInitializationException, now at System.Text.Json.JsonSerializer.Deserialize<T> (where T is a type defined in the generator project).

It's also not a proper solution for a real-world case with more dependencies (including the generator project also having its own project references), since it seems like the dependencies are not included transitively. For example when I added more dependencies and tried to add the top-level package references using solution given above, I got an error that System.Runtime.dll is not found.

**Comment by jjonescz** [comment]
> It's also not a proper solution for a real-world case

In real world scenarios, you are supposed to package the source generator as a NuGet package. ProjectReferences are not fully supported, see e.g., https://github.com/dotnet/roslyn/pull/66974#issuecomment-1439053836

**Comment by Drake53** [comment]
I see, well in that case all I can say is I hope better support for project references will be reconsidered. IMO it'd be a lot more convenient, especially if you're still learning about/experimenting with writing source generators.
