### ISSUE TITLE
C# Interactive should support stdin e.g. Console.ReadLine()

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn#7235]
In C# interactive, type:

```C#
Console.ReadLine()
```

and press Enter. C# interactive is now 'hung'. I understand why. The interactive host process is waiting for input on stdin. You can 'escape' by clicking on the toolbar to reset the session..

However, would it be possible to support this by piping input from the interactive window during evaluation?

**Comment by KevinH-MS** [comment]
@tmat, there's got to be an existing bug on this, but I can't find it.  Do you know?

**Comment by KevinH-MS** [comment]
Nevermind...found it (#6666)
