### ISSUE TITLE
IntelliSense suggests the `readonly` modifier even when it's already present in the incomplete declaration

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#72372]
**Version Used**:
VS 2022 Version 17.9.2
Roslyn 4.9.0 (a98c90d5645537)

**Steps to Reproduce**:

1. Begin declaring any member, optionally including an accessibility modifier (`public`)
2. Type `readonly`
3. Begin typing `readonly` again, without completing the word

**Expected Behavior**:

`readonly` does not appear again, as it's illegal to include the same modifier more than once.

**Actual Behavior**:

The `readonly` modifier is suggested again.

Note: `static`, `partial` and other modifiers are not suggested more than once.

**Comment by sdelarosbil** [comment]
Hey, can I take this?

**Comment by CyrusNajmabadi** [comment]
Yup
