### ISSUE TITLE
Use Pattern Matching suggestion gives faulty code

### ISSUE THREAD

**Issue by Joy-less** [dotnet/roslyn#72370]
**Version Used**: C# 12

**Steps to Reproduce**:

1. Paste the following code into Visual Studio:
```cs
public class Program {
    public class Cat {
    }
    public static void Main() {
        Cat Cat = new();
        object Object = Cat;
        
        // Suggestion: IDE0083: Use Pattern Matching
        if (!(Object is Cat)) {
            
        }
    }
}
```

2. If you accept the suggestion, it corrects your code to:
```cs
if (Object is not Cat) {
    
}
```
which gives you a compilation error: `(line 14, col 21): A constant value is expected`

**Diagnostic Id**: IDE0083

**Expected Behavior**:
No suggestion given.

**Actual Behavior**:
Faulty suggestion given.

**Related discussion:**
https://github.com/dotnet/csharplang/discussions/7980

**Comment by sdelarosbil** [comment]
Hey, I could take this, but I need some information.

I think in this case, you would try to remove the ambiguity by putting a more qualified name such as Program.Cat here, but I don't know if there is logic dedicated to handling this type of syntax generation. If there is, I would like to know more.

Also, I would like to know how one would manage the logic of only putting enough qualification to the name to resolve the ambiguity, but not necessarily the fully qualified one as it might not be fully necessary.

**Comment by CyrusNajmabadi** [comment]
> I think in this case, you would try to remove the ambiguity by putting a more qualified name such as Program.Cat here

That seems reasonable.  Or we could block this case in the analyzer.

> but I don't know if there is logic dedicated to handling this type of syntax generation

You can use the extension GenerateNameSyntax for this purpose.  

> Also, I would like to know how one would manage the logic of only putting enough qualification to the name to resolve the ambiguity, but not necessarily the fully qualified one as it might not be fully necessary.

GenerateNameSyntax will add an annotation to the node asking our simplifier to simplify it.

**Comment by sdelarosbil** [comment]
> > I think in this case, you would try to remove the ambiguity by putting a more qualified name such as Program.Cat here
> 
> That seems reasonable. Or we could block this case in the analyzer.
> 
> > but I don't know if there is logic dedicated to handling this type of syntax generation
> 
> You can use the extension GenerateNameSyntax for this purpose.
> 
> > Also, I would like to know how one would manage the logic of only putting enough qualification to the name to resolve the ambiguity, but not necessarily the fully qualified one as it might not be fully necessary.
> 
> GenerateNameSyntax will add an annotation to the node asking our simplifier to simplify it.

I experimented using generator.NameExpression which ends up doing that and it does give me the fully qualified name which works, but now I am hitting a second issue: the simplifier reduces it back to the same ambiguous name.

So it seems that there's a part of this where the simplification is uneeded, but now comes the question of how this can be done? It might be possible to manually walk up the names until there's no collisions manually, but now the question becomes how do I know a given name collides?

**Comment by CyrusNajmabadi** [comment]
> the simplifier reduces it back to the same ambiguous name.

The simplifier should be fixed as part of the PR.  Thanks :)
