### ISSUE TITLE
Syntax visualizer should match current theme of VS

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#7239]
Attached pic is syntax visualizer with dark theme in dev14 update1. 
@dotnet/roslyn-ide 

![snip_20151204110749](https://cloud.githubusercontent.com/assets/788783/11598523/49a84854-9a77-11e5-9dac-ae4d9de0e728.png)

**Comment by davkean** [comment]
@dpoeschl Didn't you file something similar?

**Comment by dpoeschl** [comment]
@davkean Internal bug 104685. I'd prefer we use this one for tracking.

**Comment by jmarolf** [comment]
Issue moved to [dotnet/roslyn-sdk #30](https://github.com/dotnet/roslyn-sdk/issues/30) via [**ZenHub**](https://www.zenhub.com/)
