### ISSUE TITLE
Missing member suggestions object initializer after target-typed constructor in collection expression for array

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#72400]
## Version Used
VS 2022 Version 17.9.2
Roslyn 4.9.0 (a98c90d5645537)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

1. Define an explicitly-typed local/field/property S with type `T[]`, where `T` can be any initializable type with an object initializer
2. Define a type that can be initialized with an object initializer
3. Assign a collection expression to S, and initialize its elements with target-typed constructors (`new()`)
4. Attempt to fill the object within the object initializer

Test code:

```csharp
public static class TestClass
{
    private static SimpleRange[] _ranges;

    public static void Method()
    {
        _ranges =
        [
            new()
            {
                Start = 1,
                End = 3,
            },
        ];
    }
}

public struct SimpleRange
{
    public int Start;
    public int End { get; set; }
};
```

## Expected Behavior

The suggestions include the available symbols for assignment (`Start` and `End` in the above example).

## Actual Behavior

The suggestions do not include any of the type's members.
Note that the suggestions properly appear for `List<T>`, like if `_ranges` is of type `List<SimpleRange>`.

## Screenshot

![image](https://github.com/dotnet/roslyn/assets/8298332/4bdcae6e-16b9-4638-84b6-328ecbad47eb)

**Comment by sdelarosbil** [comment]
Hey, can I take this?

**Comment by CyrusNajmabadi** [comment]
Yup!

**Comment by sdelarosbil** [comment]
hmmm, this might need to be retested because I can't seem to reproduce both in a unity test (the test passes) and running visual studio using the F5 deployment with the same code.

I always get Start and End suggested.

**Comment by CyrusNajmabadi** [comment]
@sdelarosbil sounds like it may have already been fixed.  That said, contributing a unit test is always a good idea so that it doesn't regress.  Thanks!
