### ISSUE TITLE
Edit and Continue unavailable message is painfully general

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7242]
![image](https://cloud.githubusercontent.com/assets/235241/11601504/7eed4436-9a88-11e5-9b44-bd6b692f387a.png)

Surely *something* in VS knows which of those things is prevent Edit and Continue...

**Comment by ManishJayaswal** [comment]
Following up with debugger team.

**Comment by KayAnd** [comment]
Unfortunately _something_ in VS does know which of those things is preventing Edit and Continue, but we currently do not have the information to surface the specific cause and additional work is required to extract that out. We do have an internal work item tracking this on our backlog for something to improve in the future.
Thanks for your input!

**Comment by ManishJayaswal** [comment]
We have an internal workitem (220031) tracking this in debugger team ( as the change is not in Roslyn code base) so I am closing this out.
