### ISSUE TITLE
Extensions with constrained generic types are not recommended when invoked on a generic method parameter

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#72457]
## Versions Used
VS 2022 Version 17.9.2
Roslyn 4.9.0 (a98c90d5645537)

VS 2022 Version 17.10.0 Preview 1
Roslyn 4.10.0 (fa72fa61b0d822ea)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

1. Have an extension class
2. Define a generic extension method where the `this` parameter is a generic type parameter from the extension method
3. Assign constraints to the generic type parameter that is the extension
4. Attempt to invoke the generic extension method on a value satisfying the constraints
5. Observe the IntelliSense suggestions

A relatively long code snippet is found on [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfAAQAYACAgRgBYBuAWAChizyA6AGVgEc7HSKWAcgFcwGKAGMAzjwYBiGEIA2iiMEWoSAEyiTV6hgwIBmZgDYyAJhIAVAPY4A4qhhipDAN4MS3siYrnrEgFbGABlBAgECQBBYEkEdAhxBAAeawA+AAoEAAsdGxJJAEovHzKAdxyMDUCQEg54tPTS7096MrKCAHZClgAxKHR4gHl0ABFULAglBEyinjKAXwN2n2MzAvDImLiEpNSM7LzJAuKWjsrqgrqASQAhWAh0HBuYBFQAcwwm87aOtZ61hY0U02iiaBummcUQQOBI6UKJAA/Ii6kCAFoYWwLHzLejndb+AoAVRg4hC8USsFQmiaR3ygTOq1a506PShUxmOO8eIJfnIARI0RgtlyGGCYQiUXEsUp+zpuQZhRKzIuVXQNRIdQaB2aqr+/xIAHojUFRYUhB8vvEaayAb0JVtpbK9sk5tySLzVYSBQVhaL1U6dnLkgrjqcVYaSJcNdcSPdHs9Xu8vugfvq7d4TWaEBaragbZpM2QepIWEGZbtEm75ucvZ1+YL/WL0KTyTA5dTaYdFSdGZGfAb/tmAMK2dAa5KKOGSS3W95F1Vs3ptil7LvuusML2Eqw6gCiAA93h2oCEmlr6jpUgfj85JGeYE09RV1Zrtdf00PfAUAGoQRQhA0dwSC+BBqEKVBwM9c4+TISgSAAWSgnJbE0OZfmLbNglzWd80LYte2BEUW0dKVg1dWZa1VPEG3gpCULQiwMIzJcfGw808PnW02O8f9ANQYiA3FEIKxdasqI9PE8SAA===), showing multiple cases of failing to suggest valid extensions. Try typing the names of the extensions anew to notice the lack of the suggestion.

## Expected Behavior

All generic extension methods that have their generic type parameter constraints met are recommended.

## Actual Behavior

Only unconstrained generic methods are recommended. When a desired generic extension method is manually typed, it is properly recognized and no error is reported.

**Comment by Rekkonnect** [comment]
Can I take this up?

**Comment by CyrusNajmabadi** [comment]
Yes.
