### ISSUE TITLE
[Question] SyntaxKindFacts.cs max keyword length

### ISSUE THREAD

**Issue by romanov** [dotnet/roslyn#7246]
Hello!

I'm trying to replace the C# keyword with another one (via SyntaxKindFacts.cs).

Is it possible to remove the limit (10 symbols) for c# keywords?

Thanks in advance.

**Comment by gafter** [comment]
Try it and see what happens. I think the limit is arbitrary.

**Comment by jaredpar** [comment]
Indeed this limit is arbitrary.  It exists in the compiler as an optimization.
