### ISSUE TITLE
[InlineArray] on a ref struct reports CS0306 as error, but CS9184 as a warning

### ISSUE THREAD

**Issue by mburbea** [dotnet/roslyn#72467]
**Version Used**: 17.9.2

**Steps to Reproduce**:
```cs
using System.Runtime.CompilerServices;

static int M() => default(S)[0];

[InlineArray(1)]
ref struct S
{
    int Element0;
}
```

**Diagnostic Id**: CS0306

**Expected Behavior**:
CS9184 is shown as an error on the declaration of `S`.
**Actual Behavior**:
Compiler Error in `M()` for CS0306, and CS9184 is a warning in `S`. Since it's clearly illegal to declare a ref struct as an inline array it should be a compiler error.

**Comment by jjonescz** [comment]
> Since it's clearly illegal to declare a ref struct as an inline array it should be a compiler error.

It's not illegal to declare it, you just cannot use it in a way that would emit a `ReadOnlySpan<S>` since the struct cannot be used as type argument. But you can use the struct in other ways. For example:

```cs
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[InlineArray(Length)]
ref struct S
{
    public const int Length = 100;
    public short element;

    [UnscopedRef]
    public ref short At(int i) => ref Unsafe.Add(ref element, i);
}

static class Program
{
    static void Main()
    {
        var s = new S();
        for (short i = 0; i < 10; i++)
        {
            s.At(i) = i;
        }
        for (short i = 0; i < 11; i++)
        {
            Console.Write(s.At(i));
        }
    }
}
```
