### ISSUE TITLE
Generate constructor fails when type contains a parameterless primary constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72484]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Primary-Constructor:-reverting-to-normal/10611677)._

---
[severity:It's more difficult to complete my work]
Step to reproduce the issue:
1) Create a class Example with fields A and B of whatever type;
2) Use Quick Actions And Refactoring... > Generate Constructor... to generate a constructor including all fields;
3) Use Quick Actions And Refactoring... > use primary constructor to use primary constructor
Suppose now you want to revert back to standard constructor
4) Manually delete all the code generated by the previous command **except** for the `(` and `)` characters defining the primary constructor.
5) Repeat step (2). 
6) Now you should see the compilation error `A constructor declared in a type with parameter list must have "this" constructor initializer`

Please see attached video

---
#### Feedback Bot on 3/10/2024, 10:44 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 3/11/2024, 07:35 AM: 

(private comment, text removed)
#### Feedback Bot on 3/11/2024, 07:36 AM: 

(private comment, text removed)
#### Feedback Bot on 3/11/2024, 07:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We have a feature dedicated *exactly* to moving back from a primary constructor to a regular constructor.
