### ISSUE TITLE
[Flaky Build] Multiple projects are trying to deploy Microsoft.CodeAnalysis.Test.Resources.Proprietary to output

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7248]
See: https://github.com/dotnet/roslyn/issues/7226#issuecomment-162116473
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(3962,5): warning MSB3026: Could not copy "C:\Users\Paul\.nuget\packages\Micros
oft.CodeAnalysis.Test.Resources.Proprietary\1.1.0-beta1-20150824-02\lib\net45\M
icrosoft.CodeAnalysis.Test.Resources.Proprietary.dll" to "C:\Users\Paul\Documen
ts\GitHub\repos\roslyn-update-1\Binaries\Debug\Microsoft.CodeAnalysis.Test.Reso
urces.Proprietary.dll". Beginning retry 1 in 1000ms. The process cannot access
the file 'C:\Users\Paul\Documents\GitHub\repos\roslyn-update-1\Binaries\Debug\M
icrosoft.CodeAnalysis.Test.Resources.Proprietary.dll' because it is being used
by another process. [C:\Users\Paul\Documents\GitHub\repos\roslyn-update-1\src\T
est\Utilities\Portable\TestUtilities.csproj]
```

**Comment by jaredpar** [comment]
I'm not sure what we can do about this one.  This is just a function of how MSBuild and NuGet work.  The only solution I can think of is to have every project build into a separate folder under `Binaries\Debug`.  Say for example `Binaries\Debug\Microsoft.CodeAnalysis`.  That would fix the issue but it possibly have some other consequences. 

I'm not against trying that out though if we would like to.

**Comment by davkean** [comment]
I know how to fix this, have a look at how the project system projects build in future - no two projects deploy the same dependencies. I did with some [manual targets and props](https://github.com/dotnet/roslyn/blob/future/src/VisualStudio/ProjectSystem/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests/Microsoft.VisualStudio.ProjectSystem.CSharp.UnitTests.csproj#L16) but @jasonmalinowski mentioned there's a general MSBuild property that tells it that you are building into a common directory, and it will stop copying bits into the directory.

**Comment by davkean** [comment]
It needs someone to enable it, and then fix up all the issues that result because of it - I tried here: https://github.com/dotnet/roslyn/pull/6446, but never got time to pick it up again.

**Comment by natidea** [comment]
@davkean Are you working on this?

**Comment by jasonmalinowski** [comment]
I don't think @davkean is. (It's not assigned to him at least.) Also, the property we were aluding to earlier is `UseCommonOutputDirectory`, which suppresses the copying of CopyLocal dependencies from all projects.

**Comment by natidea** [comment]
Adding additional instances of this from Rolling Builds. The builds pass on rerun:
http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit64/971/
```
07:45:41 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3962,5): error MSB3021: Unable to copy file "d:\j\workspace\roslyn-intern---b26116fb\Open\Binaries\Debug\Microsoft.CodeAnalysis.EditorFeatures.xml" to "d:\j\workspace\roslyn-intern---b26116fb\Open\Binaries\Release\Microsoft.CodeAnalysis.EditorFeatures.xml". The process cannot access the file 'd:\j\workspace\roslyn-intern---b26116fb\Open\Binaries\Release\Microsoft.CodeAnalysis.EditorFeatures.xml' because it is being used by another process. [d:\j\workspace\roslyn-intern---b26116fb\Open\src\Samples\CSharp\CopyPasteWithUsing\CopyPasteWithUsing.csproj]
```

**Comment by davkean** [comment]
Dup'ing again: https://github.com/dotnet/roslyn/issues/7248
