### ISSUE TITLE
Rename silently fails when "Rename symbol's file" is selected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72489]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/rename-does-not-work-as-expected/10581975)._

---
[severity:My work is severely impacted or blocked (internal MSFT only)]
1. Tried to rename a class, by right click class name in editor and select "rename..."
2. Type "Enter"
3. Rename does not happen, just enter a new line in editor :(

---
#### [user] on 2/10/2024, 03:13 AM: 

(private comment, text removed)
#### Feedback Bot on 2/10/2024, 11:03 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 2/13/2024, 07:22 AM: 

(private comment, text removed)
#### Feedback Bot on 2/20/2024, 10:19 PM: 

(private comment, text removed)
#### Dennis Saarela on 3/5/2024, 02:39 AM: 

(private comment, text removed)
#### Feedback Bot on 3/7/2024, 07:14 AM: 

(private comment, text removed)
#### Feedback Bot on 3/7/2024, 10:15 AM: 

(private comment, text removed)

---
#### Nicole Hu [MSFT] solved on 3/6/2024, 08:54 PM, 0 votes: 

<p>We are unable to investigate this issue further without the additional information requested. If you are able to provide more information, you can request the issue being reactivate below. See our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">guidelines</a> for further information about our process.</p>

**Comment by Cosifne** [comment]
I see the original issue was reported in 17.8.
For me, the problem sounds like https://github.com/dotnet/roslyn/pull/71220, and the fix is in 17.9.
Close this now, if anyone sees the problem after 17.9 feel free to reopen the issue.
