### ISSUE TITLE
Find References doesn't work when a class contains #line hidden directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72485]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-References-doesnt-work-when-a-clas/10604106)._

---
[severity:It's more difficult to complete my work]
When a class contains a `#line default` directive. Other classes are unable to find references from that class.
For example, with the following code:

(2 separate class files)

Class1:
```
namespace FindReferencesBug {
	
public class Class1 {		

Class1() {

Class2.SomeMethod();
		}

#line hidden
		public void SomeHiddenMethod() {

}
#line default
	}
}
```

Class2:
```
namespace FindReferencesBug {
	
internal class Class2 {

public static void SomeMethod() {
		}
	}
}
```

Finding references to Class2 results in no found references.
However, after removing `#line hidden` directives, Class2 reference is correctly found from Class1.

I have attached a video showing the issue

---
#### Feedback Bot on 2/28/2024, 09:44 PM: 

(private comment, text removed)
#### Feedback Bot on 3/4/2024, 09:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is by design.  We don't show hidden results as that's the purpose of that directive.
