### ISSUE TITLE
`nameof` for type-keywords causes CS1525

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/roslyn#72501]
**Version Used**: .NET 8.0.200

**Steps to Reproduce**:

1. Attempt to compile something with `nameof(<type-keyword>)`.

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoKwgZgAITHSB2Kgbyvu8YcJXoBZAIbYAdgAoAlFx6dKPRcwCcEscIC2MCADMJ4jFKkBuWdwC+Vc0A=

```cs
using System;

public class Program
{
    public void Main()
    {
        Console.WriteLine(nameof(int));
    }
}
```

**Diagnostic Id**:

CS1525

**Expected Behavior**:

The keyword, `int` would be interpreted as meaning `System.Int32` and compilation would succeed. After all, `typeof(int).Name` works ("Int32") as does `nameof(Int32)` (also "Int32").

**Actual Behavior**:

CS1525 with a cryptic message: "[i]nvalid expression term 'int'"

**Comment by CyrusNajmabadi** [comment]
The error is correct.  `int` is not legal here as per the language specification https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/expressions.md#11720-nameof-expressions.  If you'd like that to change, we'd need an actual langauge change to go through at dotnet/csharplang.
