### ISSUE TITLE
Roslyn and .Net disagree about converting double.NaN to long

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn#72526]
**Version Used**: .Net 8

**Steps to Reproduce**:

Compile and run the following code:

```c#
double d = double.NaN;
Console.WriteLine((long)d);

Console.WriteLine(unchecked((long)double.NaN));
```

**Expected Behavior**:

Both versions produce the same output.

**Actual Behavior**:

The output is:

```
-9223372036854775808
0
```

I.e. when .Net converts `double.NaN` to `long` at run-time, the result is `long.MinValue`. But when Roslyn performs an unchecked conversion of a constant `double.NaN` to `long` at compile-time, the result is `0`.

I don't know if this is an issue in Roslyn, in the .Net runtime, or if the inconsistency is expected, but I thought it would be worth reporting nevertheless.

**Comment by RikkiGibson** [comment]
@tannergooding might have insight about what should happen here.

**Comment by svick** [comment]
@tannergooding Thanks for the explanation.

**Comment by RikkiGibson** [comment]
Thanks @tannergooding! I will close out as it looks like the question has been answered.
