### ISSUE TITLE
v1.1.1 is 5x slower than v1.1.0

### ISSUE THREAD

**Issue by squideyes** [dotnet/roslyn#7254]
Hi!  When I upgraded Microsoft.CodeAnalysis.CSharp from v1.1.0 to v1.1.1, I noticed a 5x slowdown. 

To show what's going on, I've created a demo solution that you can download from the following public repository:

    https://github.com/squideyes/RoslynSpeed

Run UsingCodeAnalysis110 then UsingCodeAnalysis111 to see what's going on.

On my machine, UsingCodeAnalysis110 takes approximately 0.25 seconds to complete whereas UsingCodeAnalysis111 takes 1.6 seconds.

Any help in this regard would be greatly appreciated....

**Comment by mikedn** [comment]
I can reproduce this issue on my machine but the difference doesn't appear to be caused by a Roslyn problem. On my machine I have NGEN images for Roslyn v1.1.0 (probably from my VS2015 installation) but not for v1.1.1. For such a large project as Roslyn native images can make a significant difference.

**Comment by squideyes** [comment]
mikedn: thanks for your quick and helpful reply.  Unfortunately, when I tried to ngen the assembly I got the below-listed errors.  Any help in this regard would be greatly appreciated:

C:\Users\louis_000\Desktop\KozasAnt\packages\Microsoft.CodeAnalysis.CSharp.1.1.1\lib\net45>ngen install Microsoft.CodeAnalysis.CSharp.dll
Microsoft (R) CLR Native Image Generator - Version 4.6.1038.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to load dependency Microsoft.CodeAnalysis of assembly Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Failed to load dependency System.Reflection.Metadata of assembly Microsoft.CodeAnalysis.CSharp, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
1>    Compiling assembly C:\Users\louis_000\Desktop\KozasAnt\packages\Microsoft.CodeAnalysis.CSharp.1.1.1\lib\net45\Microsoft.CodeAnalysis.CSharp.dll (CLR v4.0.30319) ...
1>Warning: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. If this assembly is found during runtime of an application, then the native image currently being generated will not be used.
1>Warning: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.. If this assembly is found during runtime of an application, then the native image currently being generated will not be used.
1>Warning: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. (Exception from HRESULT: 0x80070002). If this assembly is found during runtime of an application, then the native image currently being generated will not be used.
1>Warning: System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. (Exception from HRESULT: 0x80070002). If this assembly is found during runtime of an application, then the native image currently being generated will not be used.

**Comment by mikedn** [comment]
> C:\Users\louis_000\Desktop\KozasAnt\packages\Microsoft.CodeAnalysis.CSharp.1.1.1\lib\net45>ngen install Microsoft.CodeAnalysis.CSharp.dll

It looks like you're trying to ngen from the package directory. You should do this from a directory that contains Microsoft.CodeAnalysis.CSharp.dll and its dependencies. For example the bin\Release directory of your project is a good place to do this because all the necessary dependencies have already been copied there.

**Comment by squideyes** [comment]
mikedn: that worked perfectly.  Thank you!

**Comment by KevinH-MS** [comment]
Glad you found a solution!

FYI for others, if you experience a similar issue after installing VS 2015 Update 1, you can run:

```ngen eqi``` (as Administrator)

The issue appears to be that immediately after installing Update 1, the compiler binaries are "queued" to be ngen'ed, but they may not actually get ngen'ed until the machine has reached an "idle" state (may not occur for several hours).

In the case reported here, VS 2015 Update 1 was likely not installed, and nuget install does not perform ngen, so then entire assembly would be JIT'ed in each new process.
