### ISSUE TITLE
System.NullReferenceException should say which reference is null

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72545]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemNullReferenceException-should-say/10599359)._

---
If you have a long line of code that does a lot of things and you get a `System.NullReferenceException` on that line, VS highlights the whole line and doesn't give any further information as to which reference is null, which can be hard to figure out.

It would be nice if it could say that specifically "import.Fields" is null

---
#### John Munro on 2/23/2024, 02:36 PM: 

(private comment, text removed)
#### Feedback Bot on 2/26/2024, 02:27 AM: 

(private comment, text removed)

**Comment by dibarbet** [comment]
Closing - this is already a VS debugger feature:
![image](https://github.com/dotnet/roslyn/assets/5749229/81c60f39-4acf-45c1-9499-20a11a80c200)

Runtime support in the actual exception message is covered by this issue - https://github.com/dotnet/runtime/issues/3858
