### ISSUE TITLE
Case blocks to not be indented by default

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72549]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Case-blocks-to-not-be-indented-by-defaul/10601826)._

---
I just discovered today that Visual Studio automatically indents case blocks for C# (case statements with brackets), like so:

```
switch (something)
{
    case 1:
        break; // Normal formatting
    case 2:
        {
            break; // Formatting with block
        }
}
```
I see that there has been multiple requests over the years (a lot of people asked) to add a way to remove that indentation and we ended up adding the option in the formatting settings. My question is: Why is it like that by default? It seems to be different from any other control flow statements.

```
if (something)
{ // Aligned

switch (something)
{ // Aligned

while (something)
{ // Aligned

for (...)
{ // Aligned
```

Surely I'm not the only one that thinks it's inconsistent? Who chose this and why? Technically this is a feature request to make the option false by default, unless there's a good reason (any official formatting guideline that mentions this? was it like that for too long?).

---
#### Feedback Bot on 2/26/2024, 10:28 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This was chosen by the team back when we did formatting originally.  We're not likely to change any default that has been this way for everyone for 20+ years.
