### ISSUE TITLE
Avoid unnecessary InvalidCastException for VB.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72547]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Avoid-unessary-InvalidCastException/10582676)._

---
I thought I’d fly this **feature request** up the flagpole for the Visual Basic community, because my boss needs help with this, such that **the following are converted/cast to 0 and don’t trigger the InvalidCastException when Option Strict is Off**:

```  
Dim result As Integer = ""
Dim result As Integer = "."
Dim result As Decimal = "."
  
```

I know in other BASIC languages the empty string is considered zero by default. And while the decimal point indicates it’s a floating point number, on it’s own it’s considered zero, and therefore could explicitly cast to an integer no problem.

I do love .NET and it’s type safety, but if Option Strict Off is to make VB.NET similar to other BASIC languages, then the empty string should definitely be considered a Zero, and one I often have to help my boss deal with in the real world. The decimal point example was one I threw in for good measure and not one I bump into, but keeps with the spirit of the BASIC language.

---
#### Feedback Bot on 2/18/2024, 03:04 AM: 

(private comment, text removed)

**Comment by jaredpar** [comment]
Closing as this is a long standing behavior in the VB language and there is little desire to change it.
