### ISSUE TITLE
Simple Elegant Way To Impliment IPropertyNotifyChanged On Auto Properties

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72550]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Simple-Elegant-Way-To-Impliment-IPropert/10599060)._

---
Auto Properties are wonderful compared to how verbose they were before

public string Title { get; set; }

Is much better than:

public string Title
{
    get
    {
        return title;
    }
    set
    {
        if (title == value)
        {
            return;
        }
        title = value;
    }
}

But if we need to use INotifyPropertyChanged to support an MVVM pattern we are forced back into the bad old days.  This is a frequent problem that leads to hundreds of extra lines of ugly code and time lost.

This:

public class DeployProfile : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;
    private void NotifyPropertyChanged([CallerMemberName] String propertyName = "")
    {
        PropertyChanged?. Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    string title;
    public string Title
    {
        get
        {
            return title;
        }
        set
        {
            if (title == value)
            {
                return;
            }
            title = value;
        }
    }
}

Should be able to be written as:
public class DeployProfile : INotifyPropertyChanged
{
    public string Title { get; set; notify;}
}

I do not believe hacky 3rd party code generators are a good solution here.  They have been around for over a decade and only serve as a grubby bandaid rather than a clean, elegant solution in the language itself.

---
#### Feedback Bot on 2/26/2024, 00:58 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Language requests should be made at csharplang.  That said, the upcoming `field` feature will help here.

**Comment by AdamEctobox** [comment]
> Language requests should be made at csharplang. That said, the upcoming `field` feature will help here.

I put this in on the dev community site, there isn't an option for csharplang.  Can you move it over to where it belongs instead of closing it?  You'd think if developers take the time to make suggestions and requests that MS could at least pretend to listen to them instead of closing them for semantics and letting the issues fester for another 5 years.  We've been hemorrhaging dev mindshare for the past decade and huge part of it is that MS stopped courting devs and rested on their laurels.  Now a shit language like python is more popular than C# and MS is using React for more of its own apps than the languages and frameworks that it built.

**Comment by Dragan-Radovac** [comment]
I understand what you mean with out of framework generators. Even the community toolkit, you just don't know how long they will be around.

I use the following as a solution. I hope find it sufficient.

```
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Application;

[Serializable]
public class Entity : INotifyPropertyChanged
{
    public int? Id
    {
        get => id;
        set => Notify(ref id, value);
    }
    private int? id;

    public string? Description
    {
        get => description;
        set => Notify(ref description, value);
    }
    private string? description;

    public decimal? Hours
    {
        get => hours;
        set => Notify(ref hours, value);
    }
    private decimal? hours;

    public decimal? Rate
    {
        get => rate;
        set => Notify(ref rate, value);
    }
    private decimal? rate;

    public decimal? Total => Hours * Rate;

    [field: NonSerialized()]
    public event PropertyChangedEventHandler? PropertyChanged;

    public void Notify<V>(ref V to, V from, [CallerMemberName] string? property = null)
    {
        if (property == null)
        {
            return;
        }
        if (to != null && to.Equals(from))
        {
            return;
        }
        to = from;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
    }
}
```

**Comment by Dragan-Radovac-75** [comment]
The field contextual keyword is now available in preview although I'm unclear on whether it will appear in C#14 or potentially come out earlier. The code example I gave on July 4, 2024 can now be implemented as follows:
```
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Application;

public class Entity : INotifyPropertyChanged
{
    public int? Id { get; set => Notify(ref field, value); }
    public string? Description { get; set => Notify(ref field, value); }        
    public decimal? Hours { get; set => Notify(ref field, value); }
    public decimal? Rate { get; set => Notify(ref field, value); }
    public decimal? Total => Hours * Rate;
    
    public event PropertyChangedEventHandler? PropertyChanged;

    public void Notify<V>(ref V to, V from, [CallerMemberName] string? property = null)
    {
        if (property == null)
        {
            return;
        }
        if (to != null && to.Equals(from))
        {
            return;
        }
        to = from;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
    }
}
```
For a deep dive into the field contextual keyword:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/field-keyword
