### ISSUE TITLE
Compiler doesn't terminate on file with syntax errors

### ISSUE THREAD

**Issue by tamasvajk** [dotnet/roslyn#72557]
**Version Used**: 
C# Compiler version 4.8.0-7.23572.1 (7b75981c)

**Steps to Reproduce**:

1. Get [this file](https://github.com/microsoft/fhir-codegen/blob/4b399f5121680a7a3f14b49279a63dc3c8feaa5d/generated/CSharpFirely2_R5/Generated/Bundle.cs) from `microsoft/fhir-codegen`. 
2. Run `dotnet /usr/local/share/dotnet/sdk/8.0.101/Roslyn/bincore/csc.dll generated/CSharpFirely2_R5/Generated/Bundle.cs`

Another option is copying the content of that file into https://sharplab.io/. 

**Expected Behavior**:
The compiler should terminate in reasonable time.

**Actual Behavior**:
The compiler doesn't terminate in reasonable time.

**Additional Note:**
C# Compiler version 3.9.0-6.21124.20 (db94f4cc) can parse the file, and it reports the syntax errors.

**Comment by cston** [comment]
@CyrusNajmabadi, it looks like parsing ends up in `LanguageParser.ParseCollectionExpression()` and unable to make progress.

**Comment by CyrusNajmabadi** [comment]
Relates to this error construct:

```
      [EnumLiteral("archives", "http://hl7.org/fhir/CodeSystem/iana-link-relations"), Description("Refers to a collection of records, documents, or other
      materials of historical interest.")]
      Archives,
```

Note the wrapping over multiple lines.

**Comment by CyrusNajmabadi** [comment]
Ick.  this is challenging/problematic.  So the string is unterminated on the first line.  So we terminate it (with an error saying it is missing).  But then we get to the next line and we are just in extreme error mode.  We see "materials", "of", "historical" "interest" all as continued arguments.  We then hit the quote and that stats `")]` another argument to the attribute.  And, at that point, all the remaining enum members just appear to be more and more arguments.  And, of course, as arguments, we think we might be seeing collection-exprs when we run into attributes on the enum members.  THis starts a cascading of speculative parsing, which explodes given how many elements there are.  Will have to noodle on what we can do here.

**Comment by CyrusNajmabadi** [comment]
Note: it's not an infinite loop.  More just really expensive with backtracking and retrying things.
