### ISSUE TITLE
Collection expression IL could be simplified for single span element

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#72566]
**Version Used**: 
https://github.com/dotnet/roslyn/commit/d8d7886808a68c720a246b09028f870bc62c30fe

**Steps to Reproduce**:
```C#
using System;
using System.Runtime.CompilerServices;
public class C
{
    public void M1(int i) => Use([i]);
    public void M2(int i) => Use(new ReadOnlySpan<int>(in i));
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Use<T>(ReadOnlySpan<T> span){}
}
```
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgCUBXGAFyjAFNCBhAezAAcoAbGgJwGVuA3KAGMaAZwDcmBAGZ8SXPUwBvTLjX5ZCACy4AsigAUsCrigBKXAF4AfLgCqomgYDaUALpnJGdRvw7dSEaUphY29o4GMDQA7rjENBAAJgDyMOwAnjwsEDAAPMbWQSGequqlas66NBQAFoyJAJKs7AZVtfVNLOzJLFSMMKKEAHKMDWmwsADmZm7luCxcUPwQFDT4KABsfuE0uQAqhfFJqRlZOfu2otkwZkoAvph3QA===)

**Expected Behavior**:
M1 and M2 could produce identical IL.

**Actual Behavior**:
The IL generated is more akin to:
```C#
    public void M1(int i)
    {
        <>y__InlineArray1<int> buffer = default(<>y__InlineArray1<int>);
        <PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray1<int>, int>(ref buffer, 0) = i;
        Use(<PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray1<int>, int>(ref buffer, 1));
    }

    public void M2(int i)
    {
        Use(new ReadOnlySpan<int>(ref i));
    }
```
The JIT is able to produce exactly the same thing for both, but the IL for the former is more complicated and requires the compiler synthesize the `<>y__InlineArray1<T>` type if it wouldn't otherwise be necessary.

**Comment by Neme12** [comment]
See also #72568

**Comment by RikkiGibson** [comment]
I think the compiler should still create a temp here to pass by-ref to the span constructor. The ReadOnlySpan in the original sample should not hold a reference to `x`. Otherwise, the behavior is in violation of the spec, when x is reassigned before the ReadOnlySpan is used.
