### ISSUE TITLE
Then using extract method it does not respect the selection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72561]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Then-using-extract-method-it-does-not-re/10616367)._

---
[severity:Other]
When I select part of an expression and use extract method to extract that part, VS 2022 extracts the full expression, not just the part I selected.

This is a problem since I often use extracted methods to break out complex conditionals that I either need to reuse or want to encapsulate in a descriptive name, and when it expands the selection it makes this impossible.

I checked the suggested examples but the most similar was a closed post that refereed to a 2017 issue in VB that has seen no action for 7 years so I choose to create a new report in the hopes it will get some much needed attention.

A problem with this is that the documentation page for extract method does not mention anything about expanding the selection so the actual behavior is not expected.

https://learn.microsoft.com/en-us/visualstudio/ide/reference/extract-method?view=vs-2022

![Extract_Method.png](https://aka.ms/dc/image?name=Bb4b7727cd2e94c218c09ca661373411b638460569843831809_Extract_Method.png&tid=b4b7727cd2e94c218c09ca661373411b638460569843831809)

In the example I am trying to extract only the  "b > 100 && c == 5" part but the extracted method have picked "a < 10 &&" part also.

If this is the intended behavior I would prefer if it more clearly indicates that it changed the selection, but I find it very illogical to do this.

Sure, if I highlight half or a word, having it expand to the full word might be reasonable, same if the extracted expression would be invalid, then it should warn that the selection will result in broken code.

When using resharper as work, it changes this behavior so the selection is respected.

---
#### Feedback Bot on 3/14/2024, 10:06 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This is by design.  We can only extract selections that represent an actual node from the syntax tree.  when there is `a op b op c`   the tree is actually `(a op b) op c`.  And so the selection is expanded to grab what is actually extractable as that's the part that is executed and produced a value.  in this case `b op c` is not something that is an expression on its own that can produce a value that could work here.  And, extract such a thing would change semantics.

**Comment by dmartensson** [comment]
I think in this case it should warn if the selection does not match a working node.

While I actually have worked with expression trees so I can see how this could be a problem, from a code perspective its not very clear.

I also think that if the selection by it self can be turned into an expression, it could try to reparse the original code with the selected text replaced by a placeholder and if that then works as an expression this should still be possible to do.

My selection is based on the code syntax, not from the resulting expression tree and it results in an unexpected behavior and as stated originally, this expansion is also not documented so when it happens you have no way to understand why unless you look at the editor source code or find this report so at minimum this expansion strategy should be documented in the references "learn" page.

**Comment by CyrusNajmabadi** [comment]
> so at minimum this expansion strategy should be documented in the references "learn" page.

Feel free to open a docs bug to see if there is interest from the docs group in adding any info here.

Given the lack of feedback on this topic here (only one report in 15+ years of having this feature) i'm going to leave this as just being working as intended.
