### ISSUE TITLE
Add code fix for CS9176: There is no target type for the collection literal.

### ISSUE THREAD

**Issue by Neme12** [dotnet/roslyn#72567]
## Summary

It would be great to have a code fix in this case:
```c#
var a = [1, 2, 3];
```
to change `var` into `List<int>`, or maybe `int[]`, or both.

## Background and Motivation

Collection literals currently require a target type, which is unexpected for many developers, and even if someone knows this fact, it's easy to make the mistake of forgetting the target type and just using `var`. I would expect that this makes CS9176 ("There is no target type for the collection literal.") quite a common error for anyone trying out collection literals for the first time or still getting used to them.

## Proposed Feature

In the summary.

## Alternative Designs

Alternatively, there could be no code fix of course. And if there is one, it's not 100% clear what the default type for the collection literal should be. That might be enough of a reason to not do this, although if C# adds a natural type for collection literals in the future, that would suggest that there is a good default type.

**Comment by huoyaoyuan** [comment]
If we add a target type for collection literal, the fix would be no longer applicable. Target type is in the scope of future work.

**Comment by Neme12** [comment]
@huoyaoyuan It would still be applicable in lower language versions.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this.
