### ISSUE TITLE
IntelliSense loses the type of Action<T> parameter only while typing

### ISSUE THREAD

**Issue by datvm** [dotnet/roslyn#72571]
**Version Used**: 

**Steps to Reproduce**:

1. Create a new C# Console App (top-level statement) and put in this code:

```cs
AddConfig(new()
{
    A = a =>
    {

    },
});

static void AddConfig(Config config) { }

class Config
{
    public Action<A>? A { get; set; }
}

class A
{
    public string Foo1 { get; set; } = "";
}
```

2. Try to use `a`, like typing `a.Foo1 = "something"`. IntelliSense cannot shows any member of `a` and the type of `a` is `?`

![image](https://github.com/dotnet/roslyn/assets/6388546/78b4a2f3-37df-4033-b2ac-72d69776b79b)

3. Without accessing to `a`, it correctly detects `a` as `A`. The moment `a` is access/typed however, it becomes `?` again.

![image](https://github.com/dotnet/roslyn/assets/6388546/97f0a478-9f84-4997-8361-a00ca275c5e9)

4. Manually typing a complete statement would result in correct type assertment again, however, pressing Enter and type another statement with `a` and the problem happens again.

![image](https://github.com/dotnet/roslyn/assets/6388546/338e838a-4f9c-4094-a836-917dfb9ed40a)

The behavior is similar to #68027 so I wonder if it's the same issue. This only affects IntelliSense, the code can be compiled successfully if it's typed manully.

I have also just realized it only happen to the automatic `new()` statement. Explicitly type `new Config()` on the first line would fix this issue.

**Diagnostic Id**: None

**Expected Behavior**:

`a`'s type should be kept consistent while typing.

**Actual Behavior**:

`a` loses its type while typing.

**Comment by jcouv** [comment]
The root cause is likely a compiler issue (ability to recover in the presence of an error in a lambda). I'm not sure whether that root cause can be addressed or whether it will need to be worked around from the IDE side.

```
    [Fact]
    public void TODO2()
    {
        var src = """
#nullable enable
using System;

AddConfig(new()
    {
        A = a =>
        {
            a
        },
    });

static void AddConfig(Config config) { }

class Config
{
    public Action<A>? A { get; set; }
}

class A
{
    public string Goo1 { get; set; } = "";
}
""";

        var comp = CreateCompilation(src, targetFramework: TargetFramework.Net70);
        comp.VerifyDiagnostics(
            // (8,14): error CS1002: ; expected
            //             a
            Diagnostic(ErrorCode.ERR_SemicolonExpected, "").WithLocation(8, 14));

        var tree = comp.SyntaxTrees.Single();
        var model = comp.GetSemanticModel(tree);
        var a = GetSyntax<IdentifierNameSyntax>(tree, "a");
        Assert.Equal("? a", model.GetSymbolInfo(a).Symbol.ToTestDisplayString()); // Should be "A a" parameter
    }
```

**Comment by CyrusNajmabadi** [comment]
This def feels like an odd case for the compiler to not be able to get good semantics with (esp. as there are no overloads goign on).  

Given:

```
AddConfig(new()
    {
        A = a =>
        {
            a
        },
    });
```

I would expect `new() ...` to be target typed with `Config`.  Which means 'A' will be `Action<A>`.  So `a =>` will be target typed with `Action<A>`,  So `a` will be a parameter with type `A`.  So `a.` should properly give `Goo`. :)

Given the simplicity of the scenario, i would really want compiler to give reasonable results here :)

Thanks!
