### ISSUE TITLE
Add an extension method to flatten the result of the combination of several IncrementalValueProviders

### ISSUE THREAD

**Issue by jscarle** [dotnet/roslyn#72578]
## Background and Motivation

The `ForAttributeWithMetadataName` with `IIncrementalGenerator` is the prefered approach to generating source in the most efficient manner possible. To take full advantage of this new approach, this requires a shift in mentality that necessitates abandoning inefficient code inspection methods such as looks for classes that implement certain interfaces. This in turn often means creating more attributes and using the combination several attributes to generate the final source.

The class `Microsoft.CodeAnalysis.IncrementalValueProviderExtensions` currently provides several useful extension methods that can be used to transform the results of several calls to `ForAttributeWithMetadataName` including, and especially, `Combine<TLeft, TRight>(this IncrementalValueProvider<TLeft> provider1, IncrementalValueProvider<TRight> provider2)`.

A single `Combine` or two isn't much of an issue, however when several combines are chained, the resulting `IncrementalValuesProvider` ends with a convulated Tuple that is hard to manage.

As little as 4 combine operations are needed to end up with a incremental value provider like this:
`IncrementalValueProvider<((((T1, T2), T3), T4), T5)>`
Which if left unnamed in a consuming method ends up looking like this:
```
T1 => value.Item1.Item1.Item1.Item1
T2 => value.Item1.Item1.Item1.Item2
T3 => value.Item1.Item1.Item2
T4 => value.Item1.Item2
T5 => value.Item2
```

## Proposed API

Something similar to this would allow us to easily unwind the results of several combines.
```cs
internal static class ValueExtensions
{
    public static (T1 T1, T2 T2, T3 T3) Flatten<T1, T2, T3>(this ((T1 T1, T2 T2) _, T3 T3) root)
    {
        return (root._.T1, root._.T2, root.T3);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4) Flatten<T1, T2, T3, T4>(this (((T1 T1, T2 T2) _, T3 T3) _, T4 T4) root)
    {
        return (root._._.T1, root._._.T2, root._.T3, root.T4);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5) Flatten<T1, T2, T3, T4, T5>(this ((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) root)
    {
        return (root._._._.T1, root._._._.T2, root._._.T3, root._.T4, root.T5);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5, T6 T6) Flatten<T1, T2, T3, T4, T5, T6>(this (((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) _, T6 T6) root)
    {
        return (root._._._._.T1, root._._._._.T2, root._._._.T3, root._._.T4, root._.T5, root.T6);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5, T6 T6, T7 T7) Flatten<T1, T2, T3, T4, T5, T6, T7>(this ((((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) _, T6 T6) _, T7 T7) root)
    {
        return (root._._._._._.T1, root._._._._._.T2, root._._._._.T3, root._._._.T4, root._._.T5, root._.T6, root.T7);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5, T6 T6, T7 T7, T8 T8) Flatten<T1, T2, T3, T4, T5, T6, T7, T8>(this (((((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) _, T6 T6) _, T7 T7) _, T8 T8) root)
    {
        return (root._._._._._._.T1, root._._._._._._.T2, root._._._._._.T3, root._._._._.T4, root._._._.T5, root._._.T6, root._.T7, root.T8);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5, T6 T6, T7 T7, T8 T8, T9 T9) Flatten<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this ((((((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) _, T6 T6) _, T7 T7) _, T8 T8) _, T9 T9) root)
    {
        return (root._._._._._._._.T1, root._._._._._._._.T2, root._._._._._._.T3, root._._._._._.T4, root._._._._.T5, root._._._.T6, root._._.T7, root._.T8, root.T9);
    }

    public static (T1 T1, T2 T2, T3 T3, T4 T4, T5 T5, T6 T6, T7 T7, T8 T8, T9 T9, T10 T10) Flatten<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this (((((((((T1 T1, T2 T2) _, T3 T3) _, T4 T4) _, T5 T5) _, T6 T6) _, T7 T7) _, T8 T8) _, T9 T9) _, T10 T10) root)
    {
        return (root._._._._._._._._.T1, root._._._._._._._._.T2, root._._._._._._._.T3, root._._._._._._.T4, root._._._._._.T5, root._._._._.T6, root._._._.T7, root._._.T8, root._.T9, root.T10);
    }
}
```
## Usage Examples

Given the context `IncrementalGeneratorInitializationContext context` in the `Initialize` method of an `IIncrementalGenerator`, the method `GenerateSource` passed as `context.RegisterSourceOutput(pipeline, GenerateSource)` could then do the following:
```cs
private static void GeneratedSource(SourceProductionContext context, ((((T1 T1, T2 T2) Child, T3 T3) Child, T4 T4) Child, T5 T5) root)
{
    var values = root.Flatten();
    /*
    Makes values available as:
    values.T1
    values.T2
    values.T3
    values.T4
    values.T5
    */
}
```

Though thanks to automatic descontructors for Tuples, the following can easily be done as well:
```cs
private static void GeneratedSource(SourceProductionContext context, ((((T1 T1, T2 T2) Child, T3 T3) Child, T4 T4) Child, T5 T5) root)
{
    var (t1, t2, t3, t4, t5) = root.Flatten();
}
```

## Alternative Designs

A better approach would be a method that directly acts on an `IncrementalValueProvider` transforming it from `IncrementalValueProvider<((((T1, T2), T3), T4), T5)>` to `IncrementalValueProvider<(T1, T2, T3, T4, T5)>` and could be called as such:
```cs
provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Flatten();
```

But that requires access and understanding of the Roslyn internal APIs which I'm not sufficiently familiar with.

## Risks

This would be an additive to the current API therefore involves little to no risk.

**Comment by jaredpar** [comment]
@333fred for triage

**Comment by CyrusNajmabadi** [comment]
I'd only think we'd need this if our impl would be substantively more efficient than just doing a simple extension that extracted `((a, b), c)` and flattened itself to `(a, b, c)` (basically, just a combine+select).  I don't think we'd do particularly better.  But @chsienki would be best to determine the efficiency side of this question.

**Comment by chsienki** [comment]
@cyrus Yeah, I mean without benchmarking it I couldn't give an exact answer, but I wouldn't think there would be much difference between `Combine<T1,T2>().Combine<(T1, T2), T3>.Select<(T1, T2, T3), ((T1, T2), T3)>()` and a 'native' `Combine<T1, T2, T3>()`

We would use two less intermediate tables, which would save a small amount of memory, and one less lambda call through the select, which would also be a small improvement. But the actual processing we do is minimal so unless the tables are _very_ large and/or a high number of combines I wouldn't think it would be particularly measurably different.

I can see the utility in a native `Combine` from an API usability point of view, but I think its an easy enough extension method to write yourself that we probably wouldn't want to maintain the API surface ourselves. 

Personally I would love to see C# get support for tuple deconstruction in the lambda itself so you can just do:

`a.Combine(b).Combine(c).Select((var (var (a, b), c), ct) => {});` 

as opposed to 

```
a.Combine(b).Combine(c).Select((pair, ct) => 
{
    var a = pair.Left.Right;
    var b = pair.Left.Left;
    var c = pair.Right;
})
```

But that's a very different ask :)

**Comment by jscarle** [comment]
> I can see the utility in a native `Combine` from an API usability point of view, but I think its an easy enough extension method to write yourself that we probably wouldn't want to maintain the API surface ourselves.

@chsienki I originally looked at a way to write a `Combine<T1, T2, T3>()` but I don't believe it's possible as a consumer because it seems that all of the internal state information needed to write a custom Combine method is exposed as internal only.

**Comment by CyrusNajmabadi** [comment]
@jscarle isn't it just this:

```c#
        public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3)> Combine<TItem1, TItem2, TItem3>(
            this IncrementalValueProvider<TItem1> provider1,
            IncrementalValueProvider<TItem2> provider2,
            IncrementalValueProvider<TItem3> provider3)
        {
            var combine1 = provider1.Combine(provider2);
            var combine2 = combine1.Combine(provider3);
            return combine2.Select((t, c) => (t.Left.Left, t.Left.Right, t.Right));
        }
```

?

**Comment by sharwell** [comment]
Related to https://github.com/dotnet/roslyn-analyzers/issues/6581

It seems sufficiently simple for this to be implemented in the source generator assembly and not really needed in Roslyn.

> This in turn often means creating more attributes and using the combination several attributes to generate the final source.

Another option here is creating methods with the same implementation pattern as `ForAttributeWithMetadataName`, such as `ForTypeDerivedFromClassWithMetadataName` or `ForTypeImplementingInterfaceWithMetadataName`.

**Comment by jscarle** [comment]
> @jscarle isn't it just this:
> ...
> ?

The following does work:
```cs    
    public static IncrementalValueProvider<(
        TItem1 Item1,
        TItem2 Item2,
        TItem3 Item3,
        TItem4 Item4,
        TItem5 Item5,
        TItem6 Item6,
        TItem7 Item7)> Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7>(
        this IncrementalValueProvider<TItem1> provider1,
        IncrementalValueProvider<TItem2> provider2,
        IncrementalValueProvider<TItem3> provider3,
        IncrementalValueProvider<TItem4> provider4,
        IncrementalValueProvider<TItem5> provider5,
        IncrementalValueProvider<TItem6> provider6,
        IncrementalValueProvider<TItem7> provider7)
    {
        return provider1
            .Combine(provider2)
            .Combine(provider3)
            .Combine(provider4)
            .Combine(provider5)
            .Combine(provider6)
            .Combine(provider7)
            .Select((tuple, _) => (
                tuple.Left.Left.Left.Left.Left.Left,
                tuple.Left.Left.Left.Left.Left.Right,
                tuple.Left.Left.Left.Left.Right,
                tuple.Left.Left.Left.Right,
                tuple.Left.Left.Right,
                tuple.Left.Right,
                tuple.Right));
    }
```

But I wouldn't exactly call it... simple.

**Comment by CyrusNajmabadi** [comment]
seems simple and mechanical to me.  It's written once and can be used wherever you need it.  I agree with chris.  I don't see much savings here putting this into the core logic, given that FAWMN should be majorly filtering down the inputs to very small tables anyways.

**Comment by jscarle** [comment]
> It seems sufficiently simple for this to be implemented in the source generator assembly and not really needed in Roslyn.
Part of the motivation is that although this can be solved within the source generator assembly, it's seems a better fit, especially when considering aspects like the issue you linked, for inclusion in Roslyn.

Those who understand best the internal mechanics for efficient combinations such as these would be those directly involved with Roslyn. Considering, as it's been mentioned in the past, the lack of up to date documentation.

> I generally recommend the singleton values be combined and transformed into a data record, at which point the anonymous tuples are gone.
I'm not sure how this would function in this case as I'm calling `ForAttributeWithMetadataName` on 6 different attributes and a CompilationProvider.

> Another option here is creating methods with the same implementation pattern as `ForAttributeWithMetadataName`, such as `ForTypeDerivedFromClassWithMetadataName` or `ForTypeImplementingInterfaceWithMetadataName`.
Would this be that the attributes themselves would have a base class or interface that would act as a marker for the marker attributes for the source generator?

**Comment by CyrusNajmabadi** [comment]
> I'm not sure how this would function in this case as I'm calling ForAttributeWithMetadataName on 6 different attributes and a CompilationProvider.

I would not recommend doing things this way.

**Comment by CyrusNajmabadi** [comment]
> Would this be that the attributes themselves would have a base class or interface that would act as a marker for the marker attributes for the source generator?

Note: we could only do this if it only found things a single level deep (basically, nodes directly specifying the base type or interface).  We'd have to build substantially complex indices if this has to traverse through inheritance.  This gets even harder if it has to traverse through inheritance in *metadata*.

**Comment by jscarle** [comment]
I'm going to leave this here for the sake of posterity, but I'm going to head @CyrusNajmabadi's advice an instead redesign my source generator around a single call a `ForAttributeWithMetadataName` using a main marker attribute and determine the individual parts through inspection of other attributes attached to the same nodes as the ones identified by the initial filter.

Thanks everyone for the feedback and guidance.

```cs
    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3)> Combine<TItem1, TItem2, TItem3>(this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2,
        IncrementalValueProvider<TItem3> provider3)
    {
        return provider1.Combine(provider2).Combine(provider3).Select((tuple, _) => (tuple.Left.Left, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4)> Combine<TItem1, TItem2, TItem3, TItem4>(this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2,
        IncrementalValueProvider<TItem3> provider3, IncrementalValueProvider<TItem4> provider4)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Select((tuple, _) => (tuple.Left.Left.Left, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5)> Combine<TItem1, TItem2, TItem3, TItem4, TItem5>(this IncrementalValueProvider<TItem1> provider1,
        IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3, IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Select((tuple, _) => (tuple.Left.Left.Left.Left, tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5, TItem6 Item6)> Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6>(this IncrementalValueProvider<TItem1> provider1,
        IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3, IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5, IncrementalValueProvider<TItem6> provider6)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Combine(provider6).Select((tuple, _) =>
            (tuple.Left.Left.Left.Left.Left, tuple.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5, TItem6 Item6, TItem7 Item7)> Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7>(
        this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3, IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5,
        IncrementalValueProvider<TItem6> provider6, IncrementalValueProvider<TItem7> provider7)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Combine(provider6).Combine(provider7).Select((tuple, _) =>
            (tuple.Left.Left.Left.Left.Left.Left, tuple.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5, TItem6 Item6, TItem7 Item7, TItem8 Item8)> Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8>(
        this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3, IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5,
        IncrementalValueProvider<TItem6> provider6, IncrementalValueProvider<TItem7> provider7, IncrementalValueProvider<TItem8> provider8)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Combine(provider6).Combine(provider7).Combine(provider8).Select((tuple, _) =>
            (tuple.Left.Left.Left.Left.Left.Left.Left, tuple.Left.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right,
                tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5, TItem6 Item6, TItem7 Item7, TItem8 Item8, TItem9 Item9)>
        Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9>(this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3,
            IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5, IncrementalValueProvider<TItem6> provider6, IncrementalValueProvider<TItem7> provider7, IncrementalValueProvider<TItem8> provider8,
            IncrementalValueProvider<TItem9> provider9)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Combine(provider6).Combine(provider7).Combine(provider8).Combine(provider9).Select((tuple, _) =>
            (tuple.Left.Left.Left.Left.Left.Left.Left.Left, tuple.Left.Left.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Right,
                tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }

    public static IncrementalValueProvider<(TItem1 Item1, TItem2 Item2, TItem3 Item3, TItem4 Item4, TItem5 Item5, TItem6 Item6, TItem7 Item7, TItem8 Item8, TItem9 Item9, TItem10 Item10)>
        Combine<TItem1, TItem2, TItem3, TItem4, TItem5, TItem6, TItem7, TItem8, TItem9, TItem10>(this IncrementalValueProvider<TItem1> provider1, IncrementalValueProvider<TItem2> provider2, IncrementalValueProvider<TItem3> provider3,
            IncrementalValueProvider<TItem4> provider4, IncrementalValueProvider<TItem5> provider5, IncrementalValueProvider<TItem6> provider6, IncrementalValueProvider<TItem7> provider7, IncrementalValueProvider<TItem8> provider8,
            IncrementalValueProvider<TItem9> provider9, IncrementalValueProvider<TItem10> provider10)
    {
        return provider1.Combine(provider2).Combine(provider3).Combine(provider4).Combine(provider5).Combine(provider6).Combine(provider7).Combine(provider8).Combine(provider9).Combine(provider10).Select((tuple, _) =>
            (tuple.Left.Left.Left.Left.Left.Left.Left.Left.Left, tuple.Left.Left.Left.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Left.Left.Right,
                tuple.Left.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Left.Right, tuple.Left.Left.Left.Right, tuple.Left.Left.Right, tuple.Left.Right, tuple.Right));
    }
```
