### ISSUE TITLE
Inconsistent dispose behavior between `await using` and `await foreach`

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#72573]
Execute the following code and examine its output ([sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4GIaoDZ4TB4CmABACZQDORpAsAFBMACATAIysAMZLHAFgDcPPhwB0AFQAWyEhCowA5iMYte/AKyrWbMgGEmAbyZkzfAMxiAbHwAcfWwFloMABQBKU+ZONz/gwB7GGpA0nEAdWQoBBI3ACIAVWpYJUoaAAdA6nJ4j1UA8xYATj5eNxgSAHcyAEFqAE8YAGMAUVwwEmQIBEDkTy8/QrJfYbIAXyZvQv1g0PComLj4gDE++WbpdOosnLI8guGSsgAzdYhNsjcANwhkMigHmDJKmvqmto6uujiPQbHRsNJkMzMDgUxqAg0M0EHVGi12qhOt1iOQQGQAJLvBFfFGkAA8sAQAD5jNNLHCPojkT0+mQAOIkBDYz5I769fr6CAtEgEHpQYKSQIAaxIz16oueAF5KCQThB8AgPGQpcSXtVKTi2d0OZ5DmYsfDWTSOYSYCTMSzqd9UWaSeJGcyjdadX03FyeXyEAKYELJWQJWLlar1W9nbjaf18kxwYxIdDYVaIxyyOjDVTk307aTGICzCwrESDKhkHJzSq1dx9RSWA4AGoQPCoEgsaz44CBMJqpyBa4kAByJAAHk6Pp5yXmAsdW+IAJpQXkUPXk/wsADsp0bOWrwNXVlrZAbTZbtgAIplsiQWeOQSMV0UOMUEgAFHqxZAwA73/OlGfzxfLresb+EW6ZaiaWZEsS4j6CWZawiGCCyIENS4AQ1ZHs2rbtp2eBqmBxrspB5rQT2faDiO17BmqSHIChLz4Hg1YHphJ6Wka547NkPziJxuxXkaN7+JOq6PgkGLml08rNCQX63quv7WHOC54Eu0ZATGQA===)):
```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

class C
{
    public static async Task Main()
    {
        Console.Write("Using dispose ");
        await using (new AsyncEnumerator())
        {
        }

        Console.Write("Foreach dispose ");
        await foreach (var i in new AsyncEnumerable())
        {
        }
    }
}

struct AsyncEnumerable : IAsyncEnumerable<int>
{
    public AsyncEnumerator GetAsyncEnumerator(CancellationToken token = default) => new AsyncEnumerator();
    IAsyncEnumerator<int> IAsyncEnumerable<int>.GetAsyncEnumerator(CancellationToken token) => new AsyncEnumerator();
}

struct AsyncEnumerator : IAsyncEnumerator<int>
{
    public int Current => 0;
    public async ValueTask<bool> MoveNextAsync()
    {
        await Task.Yield();
        return false;
    }
    public async ValueTask DisposeAsync()
    {
        Console.WriteLine("Pattern");
        await Task.Yield();
    }

    int IAsyncEnumerator<int>.Current => throw null;
    ValueTask<bool> IAsyncEnumerator<int>.MoveNextAsync() => throw null;
    async ValueTask IAsyncDisposable.DisposeAsync()
    {
        Console.WriteLine("Interface");
        await Task.Yield();
    }
}
```

Observed:  Using gives priority to `IAsyncDisposable` implementation, foreach ignores `IAsyncDisposable` implementation.
```
Using dispose Interface
Foreach dispose Pattern
```

Expected: Both give priority to  `IAsyncDisposable` implementation
```
Using dispose Interface
Foreach dispose Interface
```

**Comment by AlekseyTs** [comment]
@jcouv FYI

**Comment by jcouv** [comment]
This seems to be by-design and explicitly tested (`DisposePatternPreferredOverIAsyncDisposable`). See related issue https://github.com/dotnet/roslyn/issues/59955
The spec says we should bind a pattern-based `DisposeAsync` first, and if that doesn't work then try converting to interface, and if that doesn't work emit an empty `finally`: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/async-streams.md#semantics

**Comment by AlekseyTs** [comment]
I saw the tests, the behavior did look sound to me anyway.
