### ISSUE TITLE
Add abstract AddMembers et al. on TypeDeclarationSyntax

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn#7258]
[`TypeDeclarationSyntax`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs,b11e4e6f3b6f4164,references) is an abstract type that is inherited by [`ClassDeclarationSyntax`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs,5ec4964afc80b5d4), [`InterfaceDeclarationSyntax`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs,b11e4e6f3b6f4164) and [`StructDeclarationSyntax`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax.xml.Generated.cs,0905b760e27201d0,references).

Today I was working on a code rewriter and the following situation came up. I was given a method, and I wanted to add a sibling method to its containing type. In my case it's either a `struct` or a `class`. Unfortunately, the base class for these two is `TypeDeclarationSyntax` which doesn't expose an `.AddMembers()` method, despite the fact that all of its implementations do.

There are a variety of methods that all of the three concrete implementations of `TypeDeclarationSyntax` have:

``` CSharp
ClassDeclarationSyntax c = null;
InterfaceDeclarationSyntax i = null;
StructDeclarationSyntax s = null;

#region add
c.AddAttributeLists(null);
c.AddBaseListTypes(null);
c.AddConstraintClauses(null);
c.AddMembers(null);
c.AddModifiers(null);
c.AddTypeParameterListParameters(null);

s.AddAttributeLists(null);
s.AddBaseListTypes(null);
s.AddConstraintClauses(null);
s.AddMembers(null);
s.AddModifiers(null);
s.AddTypeParameterListParameters(null);

i.AddAttributeLists(null);
i.AddBaseListTypes(null);
i.AddConstraintClauses(null);
i.AddMembers(null);
i.AddModifiers(null);
i.AddTypeParameterListParameters(null);
#endregion

#region with

c.WithAttributeLists(default(SyntaxList<AttributeListSyntax>));
c.WithBaseList(null);
c.WithCloseBraceToken(default(SyntaxToken));
c.WithConstraintClauses(default(SyntaxList<TypeParameterConstraintClauseSyntax>));
c.WithIdentifier(default(SyntaxToken));
c.WithKeyword(default(SyntaxToken));
c.WithMembers(default(SyntaxList<MemberDeclarationSyntax>));
c.WithModifiers(default(SyntaxTokenList));
c.WithOpenBraceToken(default(SyntaxToken));
c.WithSemicolonToken(default(SyntaxToken));
c.WithTypeParameterList(null);

s.WithAttributeLists(default(SyntaxList<AttributeListSyntax>));
s.WithBaseList(null);
s.WithCloseBraceToken(default(SyntaxToken));
s.WithConstraintClauses(default(SyntaxList<TypeParameterConstraintClauseSyntax>));
s.WithIdentifier(default(SyntaxToken));
s.WithKeyword(default(SyntaxToken));
s.WithMembers(default(SyntaxList<MemberDeclarationSyntax>));
s.WithModifiers(default(SyntaxTokenList));
s.WithOpenBraceToken(default(SyntaxToken));
s.WithSemicolonToken(default(SyntaxToken));
s.WithTypeParameterList(null);

i.WithAttributeLists(default(SyntaxList<AttributeListSyntax>));
i.WithBaseList(null);
i.WithCloseBraceToken(default(SyntaxToken));
i.WithConstraintClauses(default(SyntaxList<TypeParameterConstraintClauseSyntax>));
i.WithIdentifier(default(SyntaxToken));
i.WithKeyword(default(SyntaxToken));
i.WithMembers(default(SyntaxList<MemberDeclarationSyntax>));
i.WithModifiers(default(SyntaxTokenList));
i.WithOpenBraceToken(default(SyntaxToken));
i.WithSemicolonToken(default(SyntaxToken));
i.WithTypeParameterList(null);

#endregion
```

Could we expose some of these from `TypeDeclarationSyntax`? Maybe all of them don't make sense as Roslyn might introduce new kinds of types (eg. records) that don't have some of these properties. 

Could we agree on a subset of these methods that might make sense to expose within `TypeDeclarationSyntax`?

**Comment by Pilchie** [comment]
Tag @mattwar

**Comment by gafter** [comment]
@mattwar Please evaluate this suggestion.

**Comment by mattwar** [comment]
Its possible that some of these could be added.  I'd avoid adding overload for explicit syntax like trivia and keep it to general concepts like members, modifies etc.

**Comment by ddobrev** [comment]
I would like to add my voice for an even more generalised version of this feature. There should be a common interface for all declarations that can have members: compilation units, name-spaces, classes, structures, interfaces, you name it. At the moment I am forced to write this:

        private void AddMember(ref CSharpSyntaxNode parent, MemberDeclarationSyntax member)
        {
            var compilationUnitSyntax = parent as CompilationUnitSyntax;
            if (compilationUnitSyntax != null)
            {
                parent = compilationUnitSyntax.AddMembers(member);
                return;
            }
            var @namespace = parent as NamespaceDeclarationSyntax;
            if (@namespace != null)
            {
                parent = @namespace.AddMembers(member);
                return;
            }
            var @class = parent as ClassDeclarationSyntax;
            if (@class != null)
            {
                parent = @class.AddMembers(member);
                return;
            }
            var @struct = parent as StructDeclarationSyntax;
            if (@struct != null)
            {
                parent = @struct.AddMembers(member);
                return;
            }
            var @interface = parent as InterfaceDeclarationSyntax;
            if (@interface != null)
            {
                parent = @interface.AddMembers(member);
                return;
            }
        }

**Comment by mattwar** [comment]
You can also use the SyntaxEditor class in workspaces dll to do these general operations.

**Comment by ddobrev** [comment]
@mattwar thank you for the tip, I might use that. Nevertheless, the API could definitely use improvement.

**Comment by JoshVarty** [comment]
Is there any concern that you might add types without members in the future? @agocke mentioned discriminated unions as something that might potentially clash with adding `.AddMembers()` to `TypeDeclarationSyntax`

**Comment by ddobrev** [comment]
The situation with AddModifiers is the same, it's not polymorphic while it can and should be.

**Comment by ddobrev** [comment]
Also, why does AddMembers take MemberDeclarationSyntax instead of simply CSharpSyntaxNode? MemberDeclarationSyntax has no additional API. I know it can have in the future but what could that be? What can be "member-specific" when adding a new member to a parent?

**Comment by JoshVarty** [comment]
>Also, why does AddMembers take MemberDeclarationSyntax instead of simply CSharpSyntaxNode? 

It wouldn't make sense to allow the addition of (for example) `InvocationExpressionSyntax` as a "member" of a type. So this ensures that only valid members can be added to types.

**Comment by ddobrev** [comment]
This makes sense. Would you then consider making some statements MemberDeclarationSyntax? For example, EmptyStatementSyntax - it can be conveniently used as a fall-back in cases some method must return a member to add to a parent but cannot. Returning an EmptyStatementSyntax would be better than returning null and checking for it each time.

**Comment by CyrusNajmabadi** [comment]
This was done:

![image](https://user-images.githubusercontent.com/4564579/198716106-e08d9402-f5eb-450a-b98a-3629dd501f53.png)

Closing this out as we do life the common members up now.
