### ISSUE TITLE
Watch windows shows some values as null, even if they have a value.

### ISSUE THREAD

**Issue by Kokujou** [dotnet/roslyn#72595]
**Version Used**: 
Version 17.8.6

**Steps to Reproduce**:
I can't say exactly for which kind of variables it happened, the only thing they have in common is that they are provided using dependency injection

1. inject a variable with dependency injection
2. use the variable in some way that you can see the result, e.g. query a string as a local variable
3. make a breakpoint at the point the string variable is being watchable

![grafik](https://github.com/dotnet/roslyn/assets/13001250/7f6199b3-3214-46b2-86d6-5896762e5824)

**Expected Behavior**:
it should show all variables correctly without null references

**Actual Behavior**:
it shows "null" for the injected variable

**Comment by CyrusNajmabadi** [comment]
I believe this was fixed in 17.9. Can you please update VS and see if it still repros?

**Comment by Kokujou** [comment]
you're right it's fixed! thank you so much for resolving it and sorry, i didn't recognize i was one version behind!

**Comment by CyrusNajmabadi** [comment]
No worries :)
