### ISSUE TITLE
There's no option to disable the vertical guides for C# 11 raw string literals

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72593]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Theres-no-option-to-disable-the-vertica/10618593)._

---
[regression] [worked-in:17.9.3]
When using C# 11 raw string literals, the VS IDE is constantly drawing a vertical guideline for the left edge of the text. I don't want this, and there's no way to turn it off. I can turn off all the other guidelines, but there's no option to disable this one. 

---
#### Feedback Bot on 3/18/2024, 11:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Will see how much feedback we get on this.  The indentation guides serve a very valuable purpose, allowing someone to see what the contents of the string will actually be, as opposed to the prefix-whitespace, which is stripped away.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned.
