### ISSUE TITLE
[Interactive] Question/Suggestion: Exit Command?

### ISSUE THREAD

**Issue by fschneidereit** [dotnet/roslyn#7260]
Right now, when using the interactive compiler on the command-line (csi in my case), there are at least three ways to exit that I can think of:
* Close the window (obviously)
* Press Alt+F4 (quick and easy)
* Execute `Environment.Exit(0);` (works, but a little lengthy)

EDIT: I think I need to specify "exit" here: The intention is to exit the interactive compiler BUT without closing an exisiting command prompt (just return to it). Therefore, closing the window and Alt+F4 don't really qualify anymore. So it boils down to:

* `Environment.Exit(0);`
* Ctrl+C

Now, what about an `#exit` command? At some point, I tried to execute it intuitively (I guess that comes from working with other tools that provide such a command, like PowerShell, for example), just to find out that such a command is not supported. Would it be useful, or is it just unnecessary in most scenarios?

**Comment by Pilchie** [comment]
Note that Ctrl+C also works.

**Comment by fschneidereit** [comment]
<blockquote>Note that Ctrl+C also works.</blockquote>
You're right, I specified my initial post.

**Comment by pharring** [comment]
Suggestion: Add a line to the text that comes up when you do ```#help```
e.g "Ctrl+C to quit"

**Comment by fschneidereit** [comment]
Ctrl+C is the generic way, the idea behind `#exit` is to provide a convenient alternative. I already did a working experimental implementation, it's only a few lines of code, but I hesitate to make a pull request because I'm not sure if this is redundant to most people.

**Comment by KevinH-MS** [comment]
The intention is for folks to use Ctrl+C.  While many other REPLs/shells have dedicated commands, it seemed redundant.  I'll add Ctrl+C to the ```#help``` text.

**Comment by fschneidereit** [comment]
<blockquote>The intention is for folks to use Ctrl+C.</blockquote>This actually makes me wonder if there is any substantiated evidence that Ctrl+C is the intention for "folks". Assuming it is, then adding Ctrl+C to the help text really is just as redundant as proposed "#exit" command which maybe some other "folks" would use intentional given the number-sign syntax.

But it really is a non-issue, so I'm fine with it. :+1:

**Comment by leppie** [comment]
F6 will probably work too

**Comment by paulomorgado** [comment]
I works, @leppie. It's a shortcut for ^Z.

Does that mean that on Linux it would be ^D?
