### ISSUE TITLE
Dynamic variables fail to interpolate when using a custom InterpolatedStringHandler

### ISSUE THREAD

**Issue by budgetdevv** [dotnet/roslyn#72606]
**Version Used**: 
.NET 8

**Steps to Reproduce**:

1. Run [Sharplab Repro](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAldBKMAU2oGEB7MABygBtmyAMqCAblADGzAM4BuYmUo0AKswAeCeUWIB6HeQDqHZAGtp5KADNyAEwCeMCGEkXzEgBYQYAc2Y3yCBzkohDIcOTGFtYI7sy2Dk4uIciu5BIQ0gh+AUEcwABWzBII1MT2js4S5GrkALzkAEQAEsx8fEEA7sZ8NgCEDVoKeACcABQAkjBZyNwcfBBZowAkDQDeagC+DQCU24MkAOz7VABsShST07Pzi2yomVyXgtcLUBwwTV42AilZGtvEVbEcggygHALqErKDhCBDIWDeUZ7YgbYjEADaTxmcwWflh8J8nxg30EAF0FABmcjIZjWTJoYrkO4PMBYl6Md5EknIQHA0HceEhLLkfEIgBCqH4NkEIrh4slPUEWlBKtVfJBWCpzMCrKmzxxHI+Xx+o1gCHIfCg0wgfAAMswfDFwmbyJZjJAEFkbJwGACiCqgf7VSDRT4JVKZfUYMwOrKCd5w4rkEjlaDUUHgyr1ZQqVgACzkACC3G4DpstqtghtoyoFD+CD9AezKtDCYV0uQ1GLpeJo3ryIz5HTmbVg81lAL3bLADF3QsvQAeZQAPlGygsWTAjdBgZHrcTHa7JbLps3A5V6ez444okE8Ol53I0NbSOzu8zWHB+/bgmoz7lPgptm6YbEAA=)

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

It should compile.

**Actual Behavior**:

```cs
System.TypeLoadException: GenericArguments[1], 'CustomInterpolationHandler', on '<>A{00000008}`3[T1,T2,T3]' violates the constraint of type parameter 'T2'.
   at Program.<Main>$(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by jaredpar** [comment]
@333fred exception happening because we're passing `CustomInterpolationHandler` which is a `ref struct` as a generic argument when generating the dynamic call sites. 

Can this even work? Can't really see a way of mixing these two items here given the types need to be plumbed through generics.

**Comment by 333fred** [comment]
> Can this even work? Can't really see a way of mixing these two items here given the types need to be plumbed through generics.

No, I don't think it could. We could consider a compile-time error here.

**Comment by 333fred** [comment]
One thing to note here is that this is not specific to interpolated strings. If I adjust the code sample to manually call `handler.AppendFormatted((dynamic)"Hello world!");`, that will also fail at runtime, rather than at compile time, with the same error. It seems like we should possibly introduce a general rule that says that, when we attempt to bind a dynamic call, if the receiver is a ref struct, fail.
