### ISSUE TITLE
Constant propagation uses wrong floating-point precision

### ISSUE THREAD

**Issue by bgrainger** [dotnet/roslyn#7262]
Edit: Deleted first example, because it's almost certainly covered by §4.1.6 allowing that "Floating-point operations may be performed with higher precision than the result type of the operation. ... Other than delivering more precise results, this rarely has any measurable effects." 

I'm assuming this means that a constant expression `(int) (23334800f / 5.5f)` is allowed to be performed with double-precision arithmetic (and not coerced to a `float`) before the truncation to `int`.

**Comment by bgrainger** [comment]
Making the temporary `const` results in a shorter example:

```
static void Main()
{
	const float temp = 23334800f / 5.5f;
	System.Console.WriteLine(temp);
	System.Console.WriteLine((int) temp);
}
```

Prints:

```
4242691
4242690
```

IL is:

```
    L_0000: nop 
    L_0001: ldc.r4 4242691
    L_0006: call void [mscorlib]System.Console::WriteLine(float32)
    L_000b: nop 
    L_000c: ldc.i4 4242690
    L_0011: call void [mscorlib]System.Console::WriteLine(int32)
```

**Comment by gafter** [comment]
The compiler should always use precisely the language-guaranteed precision and no more so that the result is deterministic.

**Comment by gafter** [comment]
It appears that the compiler is (improperly) preserving the full double-precision value for the constant `temp`, and using that during constant-folding.

**Comment by gafter** [comment]
The spec says

> Floating-point operations may be performed with higher precision than the result type of the operation. For example, some hardware architectures support an “extended” or “long double” floating-point type with greater range and precision than the double type, and implicitly perform all floating-point operations using this higher precision type. Only at excessive cost in performance can such hardware architectures be made to perform floating-point operations with less precision, and rather than require an implementation to forfeit both performance and precision, C# allows a higher precision type to be used for all floating-point operations. Other than delivering more precise results, this rarely has any measurable effects. However, in expressions of the form x * y / z, where the multiplication produces a result that is outside the double range, but the subsequent division brings the temporary result back into the double range, the fact that the expression is evaluated in a higher range format may cause a finite result to be produced instead of an infinity. **To force a value of a floating point type to the exact precision of its type, an explicit cast can be used.**

My emphasis. The following program demonstrates that we are not following that.

```cs
class Program
{
    static void Main(string[] args)
    {
        float temp1 = (float)(23334800f / 5.5f);
        System.Console.WriteLine((int)temp1);

        const float temp2 = (float)(23334800f / 5.5f);
        System.Console.WriteLine((int)temp2);
    }
}
```

**Comment by bgrainger** [comment]
> To force a value of a floating point type to the exact precision of its type, an explicit cast can be used.

FWIW, this sentence doesn't appear in §4.1.6 in the C# 5.0 spec; I believe it's a recent addition due to the conversation in #6309. (Is there an online reference that has the latest C# spec? I've been unable to find it. Googling for that sentence only turns up a citation in source code: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Lowering/LocalRewriter/LocalRewriter_Conversion.cs,33.)

**Comment by gafter** [comment]
Don't worry, that sentence is not normative. See 6.1.1 for the normative version giving the guarantee.

**Comment by gafter** [comment]
We're still working on figuring out how to deliver the language specifications.
/cc @MadsTorgersen

**Comment by gafter** [comment]
OK, a PR for this bug is now being reviewed.

**Comment by leppie** [comment]
@gafter: Does specifying the precision on a real, imply an explicit cast?
