### ISSUE TITLE
Search in options window doesn't show all matches in the pages tree view

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72639]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Search-in-options-window-doesnt-show-al/10621245)._

---
[severity:It's more difficult to complete my work]
Steps to reproduce:

1. Open the Visual Studio options window.
1. Search for "navigation to".
1. Note that the tree item Text Editor - C# - Advanced is found.
1. Open that page.
1. Change the search term to "source link".

Expected result: The words "source link" should be highlighted on the right side **and** the tree item Text Editor - C# - Advanced should still be shown in the tree.

Actual result: The words "source link" are correctly highlighted on the right side, **but** the only tree item shown is Debugging - General (where another match for "source link" is found).

---
#### Feedback Bot on 3/21/2024, 01:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment]
This should be resolved when we fully migrate to the new unified settings experience.  Tracked by https://github.com/dotnet/roslyn/issues/69396
