### ISSUE TITLE
Class type with all fields mandatory (and optional fields marked specifically)

### ISSUE THREAD

**Issue by EBrown8534** [dotnet/roslyn#7264]
## Summary

I'm curious on what it might be like to implement a type that acts like a struct as far as field/property initialization requirements, but is still a reference type.

That is to say, something along the lines of a `solid class` (et al.) that forces the user to make all constructors implement all properties or fields by default. One could then suffix optional properties/fields with a `?` on the identifier.

Example:

```
public solid class Account
{
    public string Email { get; set; }
    public string Name? { get; set; }

    /* Completely valid */
    public Account(string email)
    {
        Email = email;
    }

    /* Also completely valid */
    public Account(string email, string name)
        : this(email)
    {
        Name = name;
    }

    /* Invalid */
    public class Account()
    {
    }

    /* Another valid constructor */
    public class Account()
        : this("foo")
    {
    }
}
```

If a class is "`solid`" (or however it is marked) it would force all constructors to either:
1. Assign values to all required properties
2. Call another constructor which assigns values to all required properties.

Now, a developer would simply need to suffix the _identifier_ on an object with a question mark to indicate it's optional. As obvious in the above example.

I'm sure you're not keen on introducing a new keyword, so perhaps there are other (better) alternatives to marking the class. I.e. `public class Account!` or similar.
## Introduced Features
1. The ability to mark an entire reference type as containing only required fields/properties;
2. The ability to mark a field/property as optional by suffixing the **identifier** with a question-mark;
3. The requirement for sub-types to fulfill this "contract" on the parent type via use of a `base` constructor;

Point three is not actually a change from the current way in which inheritance is concerned. If a class specifies any explicit constructors, those are the only ones the child-class has access to.

This is not unlike the way Swift handles types, in that all fields are required (excepting those marked with an optional-modifier) to be set somewhere throughout the constructor chains.
## Scope

Both portions of this feature request should only be applicable to `class` types. The idea is to allow a class type to guarantee that certain fields must be set by the constructor. (They could be set to `null`, if supported.)

This should have no considerable effect on inheritance, as inherited classes only have access to the default constructor of the base class **if** that base class doesn't define it's own parameterless constructor. This would mean that this feature would guarantee base-classes to define a constructor, so all child classes would have to define a constructor (at least) that calls one of the base-class constructors.
## Drawbacks

The obvious drawbacks would be that properties or fields which are nullable (reference types, and nullable value types) would still be able to be set to null, though [this proposal](https://github.com/dotnet/roslyn/issues/4443) would remove that possibility if the objects are not marked as nullable.
## Benefits

The obvious benefit here is that it can be guaranteed that a property or field was _explicitly_ set to _something_. This should help indicate model validity, and allow developers to feel a bit safer in their expectations as to how the model should work.

---
# Alternative Solution
## Add a Required Attribute to fields or properties

An alternative solution would be to add a `RequiredAttribute` that is an indicator to the compiler that a class must explicitly set that field or property to some value in all constructors (or call a base constructor that sets it to some value). This may be less difficult to implement. (I don't know enough on the internal operations to know what the difficulty of either is.)
## Example

```
public class Account
{
    [Required]
    public string Email { get; set; }
    public string Name { get; set; }

    /* Completely valid */
    public Account(string email)
    {
        Email = email;
    }

    /* Also completely valid */
    public Account(string email, string name)
        : this(email)
    {
        Name = name;
    }

    /* Invalid */
    public class Account()
    {
    }

    /* Another valid constructor */
    public class Account()
        : this("foo")
    {
    }
}
```

The only difference in this example versus the first is that this example indicates that fields and properties are implicitly optional, and explicitly required. In my opinion, the first method presented is preferable.

**Comment by svick** [comment]
This sounds like something you could write an analyzer for. You couldn't use your `?` syntax, but either using an `[Optional]` attribute instead or your `[Required]` alternative should work.

**Comment by HaloFour** [comment]
Wouldn't this be covered by #227?  At least producing a warning if a non-nullable field/auto-property isn't definitely assigned by any of the constructors?

**Comment by alrz** [comment]
>The obvious benefit here is that it can be guaranteed that a property or field was explicitly set to something. 

Just like records.

**Comment by gafter** [comment]
We are now taking language feature discussion on https://github.com/dotnet/csharplang for C# specific issues, https://github.com/dotnet/vblang for VB-specific features, and https://github.com/dotnet/csharplang for features that affect both languages.
