### ISSUE TITLE
Regions should be included in code block grouping

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Regions-should-be-included-in-code-block/10615000)._

---
If I have regions defined in my code they should be included in the code block grouping. 

In the image, if I were to scroll down past that SERVICE INJECTIONS region it should group and be show as another section in the window under ConfigureServices.

![Bd5d617ee9bd44e6199a66ee4f2d76405638459409903842777_20240313-113630-image.png](https://github.com/dotnet/roslyn/assets/28332578/97d11493-97c0-430c-bde4-1c111b22d98f)

---
#### Feedback Bot on 3/13/2024, 10:07 PM: 

(private comment, text removed)

**Comment by sfernandez131** [comment]
Adding the image from the original post. 

![Bd5d617ee9bd44e6199a66ee4f2d76405638459409903842777_20240313-113630-image.png](https://github.com/dotnet/roslyn/assets/28332578/97d11493-97c0-430c-bde4-1c111b22d98f)

**Comment by dibarbet** [comment]
(Triaging) Talked offline with the editor team - sticky scroll ignores certain structure tags:
```
private static string[] ExcludedStructureTagTypes = new string[]
        {
            PredefinedStructureTagTypes.Nonstructural,
            PredefinedStructureTagTypes.Imports,
            PredefinedStructureTagTypes.Comment
        };
```

Currently we use `PredefinedStructureTagTypes.Nonstructural` for regions.  We would have to either change it to something else (and therefore would add vertical structure guides), or the editor could implement a nonstructural but sticky kind.

Assigning over to @CyrusNajmabadi as feature owner to decide if we want to support this, and if so, which path we would take.

**Comment by CyrusNajmabadi** [comment]
> Currently we use PredefinedStructureTagTypes.Nonstructural for regions.

I don't think that's true.  We use: 
![image](https://github.com/dotnet/roslyn/assets/4564579/db4b0d25-2cd3-4470-982f-4d2cd95b0be4)

So, absent the editor filtering those out, i think this should work.  Tagging @olegtk .

**Comment by dibarbet** [comment]
@CyrusNajmabadi according to this test it seems like it should be nonstructural, but I haven't debugged myself to confirm - https://github.com/dotnet/roslyn/blob/46be15dd576d78a7852192912cab3611bc5f1135/src/EditorFeatures/Test/Structure/StructureTaggerTests.cs#L77

**Comment by CyrusNajmabadi** [comment]
@dibarbet  https://github.com/dotnet/roslyn/pull/72804
