### ISSUE TITLE
Editorconfig in nuget package is not respected if slashes in source file path do not exactly match slashes in .editorconfig path

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#72657]
This was originally found when doing this PR - https://github.com/dotnet/razor/pull/10139

Arcade sets the NugetPackageRoot based on the NUGET_PACKAGES folder.  Arcade [will normalize the NugetPackageRoot](https://github.com/dotnet/arcade/blob/742b88473823f1271366463ee9b57bea63677312/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L11C106-L11C124) (add a trailing slash).

If NUGET_PACKAGES does not include a trailing slash, the NugetPackageRoot will have one (appended by arcade) and they do not match:
![image](https://github.com/dotnet/roslyn/assets/5749229/3fa33800-4d28-4310-87a8-d734a355c649)

This causes source file paths to be passed to the compiler with a double trailing slash `\\` whereas the .editorconfig gets passed with a single trailing slash `\`
![image](https://github.com/dotnet/roslyn/assets/5749229/fdee2689-410b-4e65-af0f-84d739c41ad7)
csc editorconfig arg:
```
/analyzerconfig:C:\Users\dabarbet\source\repos\EditorConfigNugetRepro\.packages\nugetpackagewitheditorconfig\1.0.0\contentFiles\cs\netstandard2.0\.editorconfig
```
csc source file arg
```
C:\Users\dabarbet\source\repos\EditorConfigNugetRepro\.packages\\nugetpackagewitheditorconfig\1.0.0\contentFiles\cs\netstandard2.0\Class1.cs
```

Both files are successfully read by the compiler, however it doesn't figure out that the nuget pkg source file belongs to the nuget package .editorconfig.

To repro, checkout and run the repro.ps1 script here - https://github.com/dibarbet/EditorConfigNugetRepro/tree/main
Binlog from the failing version in mismatch.zip
[mismatch.zip](https://github.com/dotnet/roslyn/files/14726911/mismatch.zip)

Related NuGet issue which is likely the source of the mismatches - https://github.com/NuGet/Home/issues/7968

**Comment by jaredpar** [comment]
It seems like the only thing we could do in the compiler is attempt to normalize the path here. Essentially say that if we see `\\` in a path then we normalize that to simply `\`. That is _probably_ safe to do (can't think of any file system that allows `\\` in a file path).
