### ISSUE TITLE
Calling MSBuildWorkspace.Create() throw exception System.MissingMethodException:“Method not found: 'System.Collections.Immutable.ImmutableArray`1<System.Reflection.Assembly> 

### ISSUE THREAD

**Issue by animalisme** [dotnet/roslyn#72666]
'System.Collections.Immutable.ImmutableArray`1<System.Reflection.Assembly> Microsoft.CodeAnalysis.Host.Mef.MefHostServices.LoadNearbyAssemblies(System.String[])'.
**Source Code **:
 ```
MSBuildWorkspace workspace = MSBuildWorkspace.Create();
// SolutionInfo solutionInfo = SolutionInfo.Create(SolutionId.CreateNewId(), VersionStamp.Default, txt源码解决方案路径.Text);
 
 //MSBuildWorkspace workspace = MSBuildWorkspace.Create();
 var projId = ProjectId.CreateNewId();
 var prjLoading = workspace.OpenProjectAsync(txtBox.Text).Result;
 Solution slnLoading = workspace.OpenSolutionAsync(txtBox.Text).Result;
 
 foreach (var prjId in slnLoading.GetProjectDependencyGraph().GetTopologicallySortedProjects())
 {
     var prj = slnLoading.GetProject(prjId);

     foreach (var doc in prj.Documents)
         slnLoading = slnLoading.AddDocument(DocumentId.CreateNewId(projId), doc.Name, doc.GetTextAsync().Result);
 }
```
**Version Used**: 

**Steps to Reproduce**:

1. Add Microsoft.CodeAnalysis.Workspaces.Desktop to project reference
2. run to the code MSBuildWorkspace workspace = MSBuildWorkspace.Create();

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:

**Actual Behavior**:

**Comment by ToddGrun** [comment]
Can you provide a link to a repo to help reproduce this?

**Comment by animalisme** [comment]
Ok, thank you for your reply,the repo is [https://github.com/0x000N3X4N/SourceCodeObfuscator](url).I want to get the MSBuildWorkspace instance,but can't create it by the method "Create", I update the repo framework to .net 8.0, i think it  doesn't matter with the solution framework.

**Comment by animalisme** [comment]
Or can you show me the step about how to use the MSBuildWorkspace, my ide is vs2022 community and i can't find nuget package about roslyn package, and when i use the  MSBuildWorkspace, i can only add the dll "Microsoft.CodeAnalysis.Workspaces.Desktop" to my project, and then i run the demo project, the MSBuildWorkspace is empty, and then the code `MSBuildWorkspace workspace = MSBuildWorkspace.Create();` throw exception.

**Comment by ToddGrun** [comment]
I took a look at your project and you are running an *extremely* old version of roslyn. Can you try updating to a newer version and see how that works for you?
