### ISSUE TITLE
IDE0040 `for_non_interface_members` option doesn't work

### ISSUE THREAD

**Issue by glen-84** [dotnet/roslyn#72693]
**Version Used**: 

$ dotnet --version
8.0.203

**Steps to Reproduce**:

1. https://github.com/glen-84/AnalyzerIssues
2. See `.editorconfig` and `Ide0040.cs`.

**Diagnostic Id**:

IDE0040

**Expected Behavior**:

To show an error, since the `Example` property should not have an access modifier.

**Actual Behavior**:

No error.

**Comment by dibarbet** [comment]
`for_non_interface_members` will report if there are missing accessibility modifiers everywhere except public interface methods.  It does not report if there are *extra* accessibility modifiers on public interface methods.
