### ISSUE TITLE
Unnecessary creation of ITextBuffer just to get a checksum

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#72703]
I noticed FAR creates a whole bunch of transient ITextBuffers just to compute checksums of files:
https://github.com/dotnet/roslyn/blob/f40cbe605342dfbe2f0eb763c924d32bd0f92f74/src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs#L201

We're basically taking a stream of bytes, creating a reader, then passing it to the EditorTextFactoryService, which loads the buffer of content type UNKNOWN, using all the heavy-weight editor loading machinery (BinaryStringRebuilder, etc), just to produce a SourceText, and from that SourceText we just call GetContentHash().

I think it would be better to just directly hash the bytes and avoid creating the editor text buffers unnecessarily. Or maybe just use a StreamReader and do a single pass if you do need to hash text instead of bytes.

As an aside, SHA1 is super expensive, there are much cheaper text hashing algorithms that are non-cryptographic and hence much faster. We shouldn't worry too much about collisions here at this scale, so a simple Fnv1a should do the trick. Some analysis here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/String-Hashing
MSBuild and NuGet have seen very significant perf wins from switching from a crypto to non-crypto hash.

Sample stack:

```
	TemporaryStorageService.TemporaryTextStorage.ReadText Line 231
	TemporaryStorageService.TemporaryTextStorage.GetChecksum Line 201
	SerializableSourceText.GetChecksum Line 75
	SerializerService.CreateChecksum Line 91
	TextDocumentState.ComputeChecksumsAsync Line 43
	AsyncLazy`1.StartAsynchronousComputation Line 390
	AsyncLazy`1.GetValueAsync Line 356
	TextDocumentState.GetStateChecksumsAsync Line 22
	AbstractSyntaxIndex`1.GetChecksumsAsync Line 115
	AbstractSyntaxIndex`1.GetIndexWorkerAsync Line 80
	AbstractSyntaxIndex`1.GetIndexAsync Line 56
	AbstractSyntaxIndex`1.GetIndexAsync Line 37
	AbstractSyntaxIndex`1.GetRequiredIndexAsync Line 31
	SyntaxTreeIndex.GetRequiredIndexAsync Line 37
	SyntaxTreeIndex.GetRequiredIndexAsync Line 34
	AbstractReferenceFinder`1.GetAllMatchingGlobalAliasNamesAsync Line 898
	NamedTypeSymbolReferenceFinder.DetermineGlobalAliasesAsync Line 24
	AbstractReferenceFinder`1.DetermineGlobalAliasesAsync Line 843
	FindReferencesSearchEngine.AddGlobalAliasesAsync Line 314
	FindReferencesSearchEngine.<>c__DisplayClass28_0.<FindReferencesInDocumentsAsync>g__PerformSearchInProjectAsync|2 Line 65
	FindReferencesSearchEngine.FindReferencesInDocumentsAsync Line 53
	SymbolFinder.FindReferencesInDocumentsInCurrentProcessAsync Line 101
```

**Comment by CyrusNajmabadi** [comment]
You're on an older version of Roslyn.  You should be seeing us call through GetContentHash now.

**Comment by CyrusNajmabadi** [comment]
> I think it would be better to just directly hash the bytes

We can't do this. We need to ensure that the in-memory representation and teh on-disk representation have the same hash.

**Comment by CyrusNajmabadi** [comment]
> As an aside, SHA1 is super expensive

We don't use SHA1 anymore.  We use xxhash128, which is much much faster.  We also do the hash in chunks of 32k at a time.

**Comment by CyrusNajmabadi** [comment]
> so a simple Fnv1a should do the trick. Some analysis here:

Fun fact.  I tried this and collided.  FNv1 is *bad* (at least when using the 32bit impl we have).  xxhash128 though is proven to have effectively no chance of collision whatsoever.

**Comment by KirillOsenkov** [comment]
yes, 32-bit is definitely not enough, 64-bit is fine though. I did that analysis in the wikipage I linked. But as long as you're using xxhash we're good.

**Comment by KirillOsenkov** [comment]
Still I don't think we should be going through the editor buffers here, a simple StreamReader should do the trick. Loading a text buffer is very expensive.

**Comment by CyrusNajmabadi** [comment]
Workign on an alternative approach here.
