### ISSUE TITLE
[Test Failure] curl (23) Failed writing body in prtest/mac/dbg/unit32 on PR #7269

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#7272]
PR: [#7269](https://github.com/dotnet/roslyn/pull/7269) *Fix CS7036 and CS1501 errors showing instead of CS0012* by @dpen2000
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/1800/

**Issue 1: curl (23) Failed writing body**
Error "curl: (23) Failed writing body". Please contact @dotnet/roslyn-infrastructure about this error; the build machine may require maintenance.

/cc: @amcasey @davkean @TyOverby This was the symptom when we claimed the machine was out of disk space. Maybe that happened again?

**Comment by leppie** [comment]
See https://github.com/dotnet/roslyn/pull/7249#issuecomment-162342216

**Comment by jaredpar** [comment]
The mac machines seem to have run out of disk space over the weekend.  This is one of the symptoms I would expect when that happen.

**Comment by davkean** [comment]
We took the machine offline: http://dotnet-ci.cloudapp.net/computer/mic-mac-bld-1/.

@mmitche is trying to increase the size on disk of the Mac machine.

**Comment by davkean** [comment]
There's not a lot actionable out of this now at the moment. The problematic machine has been taken out of commission, we're looking at increasing disk space on these boxes - but nothing really for Roslyn to track.
