### ISSUE TITLE
Compiler has poor error recovery when encountering nullable types in pattern locations

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#72720]
**Version Used**:
`main` from 20 January 2024, but I have confirmation, that this is still the case with the latest `main`

**Steps to Reproduce**:
```cs
class C
{
    int M(string str)
    {
        if (str is ['(', ..string? slice, ')'])
        {
            return slice.Length;
        }
        
        return 0;
    }
}
```
[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCBYAUAb2yglWAFxQFkAKBARgAYUBnYgJwEp9C8tCeiAzFBSbMiDFAG0A5BUkAaFADoFNWgH5GAGygBjAKbzJrSQF123XgS4WLCAOyaduhQBldMAObEAFgG4OFgF9/XmCeOxRaP3MCIKwAoA)

**Expected Behavior**:
`error CS8116: It is not legal to use nullable type 'string?' in a pattern; use the underlying type 'string' instead.`

**Actual Behavior**:
A bunch of parse and binding errors, which don't make it clear what the real error is

**Comment by CyrusNajmabadi** [comment]
> Code can be compiled,

I'm not sure if the code should be compilable.  Patterns don't support nullable types (in any contexts).  So i'm not sure hwy they would be supported here.  In terms of error tolerance, we could certainly attempt to be better to give better error messages though.

**Comment by jcouv** [comment]
This is by-design indeed: "Nullable reference types cannot occur in the following positions: [...] as the type in an is_expression, a catch_clause or a type_pattern" ([nullable spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/nullable-reference-types-specification.md#nullable-reference-types)).

**Comment by CyrusNajmabadi** [comment]
Thanks @jcouv .  I've updated the title.  Will reactivate (but not as a bug, but a request for better error recovery).

**Comment by DoctorKrolic** [comment]
> Nullable reference types cannot occur in the following positions

This doesn't say anything about nullable value types. I've just tested and behavior with them seems weird and inconsistent:
- `obj is int?` [is allowed](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCBYAUAb2yglBAZhWAHtyAbFAWQApzgArAUwGMAXFJ5gShQBeAHw8WKKAGcJMTgH4A3NgC+QA===)
- `obj is not int?` [is suddenly not](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCBYAUAb2yglBAZhWAHtyAbFAWQApzgArAUwGMAXFJ5gShQBeAHw8WKKAGcUMct1icA/AG5sAXyA)
- `int?` in slice pattern [cannot be even parsed](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCBYAUAb2yglYAe2IBsUBZAClgBcB+AbQF0UIAnDgSn0LyyEhKAPQiUAFQAWAUxR0AngAc5xAGYoAzmSgBjObI5yom9rroBXCGTIKUAA3rMW9gDRELdeVIheTKGGIvOlkUJWJ6PmEUKA1qTg4Y0yZArxgLG3cAOiynLR19d1SAjLIWXkFolAEq4QQAdny9GSyACQhNADVrCxkAbijhAF9BoVHCBpQ1a01+wZGsIaA===) (understandable, since this is the issue about it)

Also, while I cannot use top-level type nullability, I can, for instance, declare an underlying type of an array in a pattern as nullable:
```cs
class C
{
    int M(string?[] arr)
    {
        if (arr is ["(", ..string?[] slice, ")"])
        {
            return slice.Length;
        }
        
        return 0;
    }
}
```
Is this by design or it is an implementation flaw and such code should produce an error?

**Comment by jcouv** [comment]
The nullable value type scenario is also by-design, but is covered in [earlier spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.0/pattern-matching.md#declaration-pattern): "It is an error if type [in a declaration pattern] is a nullable value type."

**Comment by CyrusNajmabadi** [comment]
> `obj is int?` is allowed

This is not a pattern. It's a normal `is` expression.  And we have to support that vice for back compat (we'd likely break it otherwise).   But for patterns it is strictly not allowed.

**Comment by CyrusNajmabadi** [comment]
> I can, for instance, declare an underlying type of an array in a pattern as nullable

Correct. This is about top level nullability.

**Comment by jaredpar** [comment]
This issue is labeled "By Design" and there is an active PR out against it. Should we reword this and remove the "By Design" label?

**Comment by jcouv** [comment]
Removed the "by-design" label since the issue was reworded (now about parser error recovery)

**Comment by Rekkonnect** [comment]
Can I take this one up?
