### ISSUE TITLE
[Flaky Build] Microsoft.CodeAnalysis.XYZ.dll is being used by another process

### ISSUE THREAD

**Issue by diryboy** [dotnet/roslyn#7273]
Hit this again when building locally, this is the first time run of cibuild.cmd on a machine. Here's the Build.log https://gist.github.com/diryboy/7fd2cd1d8d3fd11280e4

cc @davkean

**Comment by davkean** [comment]
@jaredpar This is likely vbcscompiler instances hanging around.

**Comment by jaredpar** [comment]
@diryboy can you run handle (from sysinternals) and see what is holding onto the DLL? 

Also I do want to stress, using cibuild.cmd is slownig down your developer process. It's much faster to build with VS or to build BuildAndTest.proj diectly.  

@davkean if it were VBCSCompiler then I would expect this to be showing up in Jenkins as well.

**Comment by davkean** [comment]
@jaredpar We and Jenkins tear down VBCSCompiler.

**Comment by davkean** [comment]
Ah, but CIBuild.cmd also tears it down, so might be something else.

**Comment by jaredpar** [comment]
@davkean Jenkins tears down the compiler via cibuild.cmd

**Comment by diryboy** [comment]
@jaredpar I'll try when I hit this again.

Since you're so curious about the reason why I use cibuild.cmd locally, I'm working on #6642 which changes compiler but lacks a lot of tests right now. As I explained in a previous issue, I built from IDE locally(which uses toolset compiler) successfully and sent a bad PR then caused trouble to the infrastructure team. I want to ensure this does not happen again, so when I feel I can push, I just kick cibuild off locally and then do something else, like watch TV or social media. I'm doing this in my spare time anyway. When I'm in a small loop of change & test, I just use the buttons from VS(Build/Run without Debug/F5). So please don't worry this would slow me down.

@davkean About that "something else", I suspect I have VS open, but I did not have Roslyn.sln open.

**Comment by diryboy** [comment]
@jaredpar I hit this again. log files: https://gist.github.com/diryboy/2daa23004bdd344d753a I added the `handle.exe > handleN.log` each time I saw some yellow from the console window. I tried to examine the handle12.log, looks like there're no "something else", just vbc.exe, VBCSCompiler.exe, and MSBuild.exe maybe.

**Comment by jaredpar** [comment]
@diryboy handle takes an argument.  If you run 

> `handle.exe Microsoft.CodeAnalysis` 

it will show the processes holding that exact file open.  That should tell us what has this opened. 

Also it's important to understand which version of the vbc or VBCSCompiler has the file open.  There are now several copies on your machine: the ones installed with VS, the ones you just built and the ones we installed with the toolset.

**Comment by diryboy** [comment]
Sure, I'll try that if I hit this again. It seems to me that it only happens at the first time run after reboot.

**Comment by diryboy** [comment]
OK, I have hit this again, and tried run handle with the arg, but the reported path is not listed.

For example, the first error being complained was `Binaries\Debug\csccore\Microsoft.CodeAnalysis.CSharp.dll` being used by another process, but handle dump said:
```
MSBuild.exe        pid: 3088   type: File           588: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll
MSBuild.exe        pid: 3088   type: File           5D8: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll
MSBuild.exe        pid: 3752   type: File           574: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll
MSBuild.exe        pid: 3752   type: File           57C: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll
MSBuild.exe        pid: 3756   type: File           548: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll
MSBuild.exe        pid: 3756   type: File           550: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll
MSBuild.exe        pid: 7400   type: File           54C: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.dll
MSBuild.exe        pid: 7400   type: File           554: %programfiles(x86)%\MSBuild\14.0\Bin\Microsoft.CodeAnalysis.CSharp.dll
VBCSCompiler.exe   pid: 8216   type: File           310: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.dll
VBCSCompiler.exe   pid: 8216   type: File           4C0: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.CSharp.dll
VBCSCompiler.exe   pid: 8216   type: File           558: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.VisualBasic.dll
VBCSCompiler.exe   pid: 8216   type: File           644: X:\Path\To\roslyn\Binaries\Debug\Microsoft.CodeAnalysis.EditorFeatures.xml
VBCSCompiler.exe   pid: 8216   type: File           76C: X:\Path\To\roslyn\Binaries\Debug\Microsoft.CodeAnalysis.CSharp.Workspaces.xml
csc.exe            pid: 8424   type: File           2B8: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.dll
csc.exe            pid: 8424   type: File           2BC: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.CSharp.dll
csc.exe            pid: 6456   type: File           278: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.dll
csc.exe            pid: 6456   type: File           27C: X:\Path\To\roslyn\Binaries\Bootstrap\Microsoft.CodeAnalysis.CSharp.dll
```
No entry says csccore.. MSBuild.exe was from VS, VBCSCompiler.exe was from Binaries\Bootstrap, csc.exe was gone by the time I checked pid.

**Comment by diryboy** [comment]
Does the Jenkins machines use Win10? I hit this on 2 Win10 PCs, one RTM one TH2.

**Comment by jaredpar** [comment]
Are you letting cibuild.cmd run to conclusion?  The end of cibuild.cmd explicitly kills all of these processes because they can hang onto files like this.

**Comment by diryboy** [comment]
The last two encounters was actually the first time run after PC boot. But yes I did let the scipt run to conclusion.

**Comment by jaredpar** [comment]
If you let the script run to conclusion I'm unsure how you can get into that state.  The last line of the script explicitly kills VBCSCompiler.

**Comment by jmadkins** [comment]
I'm currently experiencing this issue. Trying to restore Nuget packages and I'm not able to because this Dll is being locked.

**Comment by diryboy** [comment]
My attempt was exclude Roslyn from Windows Defender. Also wanted to disable search indexer, but looks like there's no way to do it. So I just retry 2 times and it works.

**Comment by diryboy** [comment]
Looks like the latest commit d4a72e5 by #9592 does not have this issue. I'll try later on another 2 PCs next week to see if the issue is really gone.

**Comment by davkean** [comment]
Thanks, keep us updated.

**Comment by diryboy** [comment]
I do not encounter this again using the latest bits, hopefully this is no longer an issue.

**Comment by bboyjacks** [comment]
To solve this for myself. I deleted that Tasks.CodeAnalysis.dll file and then restored my Nuget Packages.
