### ISSUE TITLE
Add ability to exclude certain files and folders from analysis without marking them as GENERATED

### ISSUE THREAD

**Issue by innomaxx** [dotnet/roslyn#72736]
## Background and Motivation

Hello community!

We had started migrating a large project with StyleCop Classic to `StyleCop.Analyzers`, which is implemented as Roslyn Analyzer. Here are wide use of `ExcludeFromStyleCop` directives on large amount of files for some reasons. These files are not generated, written by engineers, and count of them is so large.

So we need a solution how to exclude them from being analyzed WITHOUT marking them as generated (that's not true).
We tried use `SuppressMessageAttribute`, but it suppresses just specified rule in `checkId` parameter. We need skip file entirely.

We had also tried `dotnet_analyzer_diagnostic.severity = none` but unfortunately without success.

Reference [#3705 (comment)](https://github.com/dotnet/roslyn/issues/3705#issuecomment-2020497466)

## Proposed API

Add to `.editorconfig` to disable processing by analyzers of specified file

```diff
[path/to/file.cs]
+use_analyzers = false
```

## Usage Examples

`.editorconfig`

Single file

```diff
[path/to/file.cs]
+use_analyzers = false
```

Entire folder

```diff
[path/to/folder/*.cs]
+use_analyzers = false
```

## Alternative Designs

Alternative names:

+ `skip_analyzers = true` (inverted)
+ `dotnet_analyzer_diagnostic.enabled = false` (under existing namespace, diagnostic?)
+ `dotnet.analyzers.enabled = false` (under existing namespace, more common probably)

## Risks

This is just a feature addition, so no existing API will be broken

**Comment by sharwell** [comment]
## Skip all analyzers

Note that if the goal is to skip _all_ analyzers, marking the files as generated code is very likely what you want to use. It can be done like this:

> [!WARNING]
> If you use nullable reference types, and have `<Nullable>enable</Nullable>`, you'll need to manually add `#nullable enable` to files that are being treated as generated. Generated files always default to `#nullable disable` and are not affected by the `<Nullable>` project property.

```ini
[path/to/file.cs]
generated_code = true
```

## Skip only some analyzers

If the goal is to skip only certain analyzers, the current way to handle this is to set the severity for those analyzers to `none` in the file and/or folders where they appear. For example:

**.globalconfig**

```ini
is_global = true

# SA1316: Tuple element names should use correct casing
dotnet_diagnostic.SA1316.severity = warning
```

**.editorconfig**

```ini
[path/to/file.cs]
# SA1316: Tuple element names should use correct casing
dotnet_diagnostic.SA1316.severity = none

[path/to/folder/*.cs]
# SA1316: Tuple element names should use correct casing
dotnet_diagnostic.SA1316.severity = none
```

**Comment by innomaxx** [comment]
> If the goal is to skip only certain analyzers

We discussed skipping only some rules - it looks like an option for us. We will try it. But please keep this issue open, original case is still relevant.

**Comment by sharwell** [comment]
> Unfortunately we don't consider marking files as generated for now to avoid side effects in future

Currently, it's not clear what difference you are expecting to find between `generated_code` and `skip_analyzers`. Based on the proposal above, it appears `generated_code` specifically targets the scenario you are reviewing.
