### ISSUE TITLE
Params Span<T> errors ambiguity for null and inline arrays

### ISSUE THREAD

**Issue by Jozkee** [dotnet/roslyn#72748]
**Version Used**: .NET SDK: Version: 9.0.100-preview.4.24176.14

**Steps to Reproduce**:
```cs
using System.Runtime.CompilerServices;

namespace params_span;

class Program
{
    static void Main(string[] args)
    {

        Foo(null);
        Bar(null);

        
        TwoObjects two = new TwoObjects(new object(), new object());
        Foo(two);
        Bar(two);
    }

    static void Foo(object? value) { Console.WriteLine("Foo with object? parameter"); }
    static void Foo(params object?[] values) { Console.WriteLine("Foo with params object?[] parameter"); }

    static void Bar(object value) { }
    static void Bar(params ReadOnlySpan<object> values) { Console.WriteLine("Bar"); }
}

[InlineArray(2)]
internal struct TwoObjects
{
    private object? _arg0;

    public TwoObjects(object? arg0, object? arg1)
    {
        this[0] = arg0;
        this[1] = arg1;
    }
}
```

**Expected Behavior**:
no errors during compilation

**Actual Behavior**:
```
C:\Users\dacantu\consoleapps\params-span> dotnet run
Restore complete (0.2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  params-span failed with errors (0.2s)
    C:\Users\dacantu\consoleapps\params-span\Program.cs(11,9): error CS0121: The call is ambiguous between the following methods or properties: 'Program.Bar(object)' and 'Program.Bar(params ReadOnlySpan<object>)' [C:\Users\dacantu\consoleapps\params-span\params-span.csproj]    
    C:\Users\dacantu\consoleapps\params-span\Program.cs(16,9): error CS0121: The call is ambiguous between the following methods or properties: 'Program.Bar(object)' and 'Program.Bar(params ReadOnlySpan<object>)' [C:\Users\dacantu\consoleapps\params-span\params-span.csproj]    
    C:\Users\dacantu\consoleapps\params-span\Program.cs(10,13): warning CS8625: Cannot convert null literal to non-nullable reference type. [C:\Users\dacantu\consoleapps\params-span\params-span.csproj]

Build failed with errors in 0.7s

The build failed. Fix the build errors and run again.
```

I would expect that signature resolution of `params Span<T>` would support the scenarios supported by `params T[]`.
This blocks some APIs approved in https://github.com/dotnet/runtime/issues/77873, namely `StringBuilder.AppendFormat(IFormatProvider? provider, [StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> args)`.

cc @stephentoub

**Comment by jjonescz** [comment]
cc @AlekseyTs

**Comment by AlekseyTs** [comment]
# Why ```Bar(null);``` is ambiguous

There is a conversion from `null` to `object`, therefore ```void Bar(object value)``` is applicable.
There is a conversion from `null` to ```ReadOnlySpan<object>```, therefore ```Bar(params ReadOnlySpan<object> values)``` is applicable in normal form.

```
static ReadOnlySpan<object> Test0() => null;

    .method private hidebysig static 
        valuetype [System.Runtime]System.ReadOnlySpan`1<object> Test0 () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 7 (0x7)
        .maxstack 8

        IL_0000: ldnull
        IL_0001: call valuetype [System.Runtime]System.ReadOnlySpan`1<!0> valuetype [System.Runtime]System.ReadOnlySpan`1<object>::op_Implicit(!0[])
        IL_0006: ret
    }
```
There is no conversion between `object` and ```ReadOnlySpan<object>```, therefore none candidate is better.

Why ```Foo(null);``` is not an ambiguity? Because there is a conversion from ```object[]``` to `object`, therefore the candidate with array is better.

# Why ```Bar(two)``` is ambiguous?

Petty much the same thing. Inline array is convertible to ```ReadOnlySpan<object>``` and to `object`, both methods are applicable in normal form. None is better.

Why ```Foo(two);``` works? There is no conversion from inline array to ```object[]```,  ```Foo(params object?[] values)``` is applicable only in expanded form. therefore ```Foo(object? value)``` is better.

**Comment by AlekseyTs** [comment]
Given https://github.com/dotnet/roslyn/issues/72748#issuecomment-2026322892, the behavior looks by design to me.
