### ISSUE TITLE
code cleanup => Remove unnecessary string.ToString() calls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72742]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/code-cleanup--Remove-unnecessary-strin/10616242)._

---
Code cleanup has an option for `dotnet_style_prefer_simplified_interpolation` that removes unnecessary method calls, like ToString() but only in the context of an interpolated string.

Sometimes I encounter unnecessary ToString() calls on strings.
Can you please add a code cleanup option for these calls too?
Potentially, this can be included in the above-mentioned `dotnet_style_prefer_simplified_interpolation`.

Thank you

---
#### Feedback Bot on 3/15/2024, 02:13 AM: 

(private comment, text removed)

**Comment by dibarbet** [comment]
I don't think we want to trigger `dotnet_style_prefer_simplified_interpolation` on `ToString` outside of interpolated strings - the rule is specifically for interpolated strings.

This is likely a better candidate for a third party analyzer (or potentially dotnet/roslyn-analyzers).
