### ISSUE TITLE
primary constructor variables are not visible during debugging

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72757]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-8-wasm-primary-constructor-variables/10612752)._

---
[severity:It's more difficult to complete my work]
In .NET 8, the primary constructor variables are not visible in webassembly debugging 

![image](https://github.com/dotnet/roslyn/assets/41759/e8cf8edd-955e-4949-a535-3e56ae0ca725)
![image](https://github.com/dotnet/roslyn/assets/41759/58c0e741-a250-4af1-a684-23696c90f587)

---
#### Feedback Bot on 3/11/2024, 06:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tmat** [comment]
Displayed autos:

```C#
class D(int a, int b)
{
    public int F(int x)
    {                                            // this, x
        int z = 1;                           // this, x, z
        return a + b;                     // this, z, a, b
    }                                            // this
}
```

Displayed locals:

**Comment by tmat** [comment]
Field by mistake.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/roslyn/issues/74082.
