### ISSUE TITLE
Language changes are breaking real-world use of dynamic

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn#72750]
**Version Used**: 
Version 17.10.0 Preview 3.0 [34721.271.main]

**Steps to Reproduce**:
```C#
using System.Text.Json;

public class C
{
    public static C M(IFoo foo, dynamic value)
    {
        var result = foo.Bar("name", value);
        return JsonSerializer.Deserialize<C>(result);
    }
}

public interface IFoo
{
    object Bar(string name, object value);
}
```

**Expected Behavior**:
Previously this compiled fine.
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYB0AVApgDwBdMApAZwHsYBuAWACgGEBmNAJhQGEGBvBlAWlYYAbFxQBZABQBJAGIUKKAGaKANCgAmATxgQwUAMYoAbhAA2AV1wBKfoL71Bz0xABOKN7jKXzhFAC8KoqYAELuUgBEemC4kRpmVrZ0Ti4CCADsKORUAMq4blAWUABeBZgAIt4FRealuAA8nAB8Ul4+fjYpzgC+DH2M9CwosIQFyhCGuCjyirz2AhTAAFa4hv7hblIYqDG4Gkur665JXf1AA=)

**Actual Behavior**:
Now it fails to compile:
```
error CS1503: Argument 1: cannot convert from 'object' to 'System.IO.Stream'
```
After the recent changes around `dynamic`, the type of `result` is now `object` whereas previously it was `dynamic`.

[jcouv:] Relates to https://github.com/dotnet/roslyn/pull/71421

**Comment by AlekseyTs** [comment]
> Will this also fix the fact that old versions of VS will compile https://dotnetfiddle.net/OdQkAQ as a legacy .NET Framework 4.8 console app but Version 17.10.0 Preview 4.0 will not?

It is not clear to me how this is related to the dynamic invocations. If it is, more details might help to give the answer.

**Comment by mattheww-freshview** [comment]
Specifically

```
DateTime? f1 = parameter.LastModifiedDate != null ? DateTime.Parse(parameter.LastModifiedDate) : null;
```

used to compile, now it doesn't (CS8957) if `parameter` is dynamic.

**Comment by AlekseyTs** [comment]
> I suppose I am trying to clarify if this is a known bug or not. Apologies if this is unrelated.

This looks like the same issue and I think this scenario will be fixed as well. As a temporary workaround you can convert result of ```DateTime.Parse``` calls to `dynamic`.
