### ISSUE TITLE
Why does roslyn give warning CS8002 instead of error CS1577 for unsigned references?

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#7277]
From [stackoverflow](http://stackoverflow.com/questions/33760037/why-does-roslyn-give-warning-cs8002-instead-of-error-cs1577-for-unsigned-referen):

> I'm working on a little project in VS2015 for the company I work for, and as a company policy, all assemblies we produce must be signed.

> I found a little odd behavior when I added a dependency to a nuget package that contained an unsigned assembly. When building the project with vs2015, I get the warning:
```none
CSC : warning CS8002: Referenced assembly 'XXX, Version=A.B.C.D, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
That seemed strange when I first saw it, because I remembered that it didn't compile in VS2013 or earlier. In fact, I get the following error when building the same project in vs2013:
```none
CSC : error CS1577: Assembly generation failed -- Referenced assembly 'XXX' does not have a strong name.
```
I thought that maybe something had changed in the runtime, and this was now supported. I couldn't be more wrong. When running my code built with warnings in VS2015, I now get a runtime error. The exact exception I get is a FileLoadException with message
```none
Could not load file or assembly 'XXX, Version=A.B.C.D, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```
I'm aware that there are some nuget packages out there that sign any unsigned dependency before build (like this one, or this other, or this last one).

> My questions here are: Is there any way that referencing an unsigned assembly from a signed one could work, and I'm missing something? If not, why then this is now a compiler warning, if it's going to give a runtime error later?

**Comment by tmat** [comment]
The change from error to warning was intentional -- it was in fact a feature request from DNX. The runtime error is only reported on Desktop CLR not on CoreCLR.

**Comment by tmat** [comment]
Referencing unsigned assembly from signed is ok on some platforms (like CoreCLR). The compiler doesn't know what platform are you going to run on hence it no longer reports an error. We still report a warning since you might run into problems as you did on Desktop CLR.

**Comment by wangyoutian** [comment]
> The change from an error to a warning was intentional -- it was in fact a feature request from DNX. The runtime error is only reported on Desktop CLR not on CoreCLR.

Can we make it also runnable on Desktop CLR?
