### ISSUE TITLE
Implicit Usings don't appear greyed out like other unused usings

### ISSUE THREAD

**Issue by james1301** [dotnet/roslyn#72776]
**Version Used**: 

17.9.5

**Steps to Reproduce**:

1. Create a .Net 8.0 C# Console app
2. On the Project make sure Implicit Usings are enabled
3. Add a using to the main class for system

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

N/A

**Expected Behavior**:

Using becomes greyed out like other usings that are unused in the class

**Actual Behavior**:

Using appears like it is required

**Comment by Cosifne** [comment]
Might related to IOrganizeImportsService or Semantic classification.

**Comment by CyrusNajmabadi** [comment]
Not repro: 

![image](https://github.com/dotnet/roslyn/assets/4564579/4f49c9d5-7159-4461-8c5f-790ec88c457f)
