### ISSUE TITLE
OperationAnalysisContext should expose the owning symbol

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7279]
While trying to port [CA1806](https://msdn.microsoft.com/en-us/library/ms182273.aspx), I identified that registering an OperationAction suffices, but the diagnostic to report needs to include the name of the owning symbol for the violating expression. I am forced to implement an Operation Block Start action within a nested Operation action just to fetch the owning symbol - we should just expose the `OperationAnalysisContext.OwningSymbol` publically to avoid this scenario.

**Comment by JohnHamby** [comment]
Should probably also add Compilation.

**Comment by JohnHamby** [comment]
Resolved by #8378
