### ISSUE TITLE
Autocomplete for `/** */` Documentation Comments

### ISSUE THREAD

**Issue by Arthri** [dotnet/roslyn#72815]
## Summary
Add a feature which automatically generates XML tags when writing `/**` above a method or another document-able element.

## Background and Motivation
There is a lesser known method of writing documentation comments with the multiline-comment syntax. It would help to make it easier to use if it automatically generated the XML tags like `///` does.

## Proposed Feature
Writing out `/**` above a document-able element such as a method or a type should automatically generate the XML tags to document said element rather than having the user type them out. An example of the writing experience of `/** */`-style documentation `///`-style documentation is provided below.
![Gif showing user write documentation in two styles](https://github.com/dotnet/roslyn/assets/41360489/4a9ff1ef-e5d3-4d7f-9dd5-4a95bde0079d)

**Comment by CyrusNajmabadi** [comment]
Closing out as `/**` comments are not ones we are investing in.
