### ISSUE TITLE
"Remove redundant assignment" removes unrelated code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72829]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-redundant-assignment-removes-un/10627248)._

---
[severity:It's more difficult to complete my work]
If I use the Quick Action IDE0059 "Remove redundant assignement" with a particular setup, it will erroneously remove unrelated code and break logic. This is the problematic code setup:
```
DynamicBuffer<Entity> items = default;
if (SimWorldReader.Common_TryGetInventoryBuffer(..., out items))
{
    ...
}

using var _ = ListPool<DisplayedItemData>.Get(out var displayedInventory);
```
If I use IDE0059 on the variable ``items``, it will correctly remove ``= default``, but it will also erroneously remove ``using var _ =`` a few lines below, which breaks the code logic. ``using var _`` is not a redundant assignment and it is needed to dispose of the ``ListPool<DisplayedItemData>.Get(..)`` return value.

This is a dangerous bug because it alters the logic of the code without telling you.

---
#### Feedback Bot on 3/28/2024, 10:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by obonn1** [comment]
I figured I'd take a crack at this as it seemed simple enough for a first contribution. I'm unsure how to link my PR to the work item.

**Comment by jnm2** [comment]
> I'm unsure how to link my PR to the work item.

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue
