### ISSUE TITLE
`where` is not suggested when adding the first type constraint to a local function

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#72821]
## Version Used
VS 2022 Version 17.9.5
Roslyn 4.9.0 (a98c90d5645537)

## Steps to Reproduce

1. Begin declaring a generic local function with at least one type parameter
2. After closing the argument list parentheses, begin typing `where`

Sample code:
```csharp
static void Outer()
{
    int Inner<T, U, V>()
        // place cursor here
    {
    }
}
```

## Expected Behavior

`where` is suggested, given the presence of type parameter in the local function.

## Actual Behavior

The `where` keyword is not suggested at all. In fact, nothing is suggested in that area.

### Note

After adding the first `where` clause, typing `where` to initiate another clause properly suggests the `where` keyword.
For example, in the following code:
```csharp
static void Outer()
{
    int Inner<T, U, V>()
        where T : class
        // place cursor here
    {
    }
}
```
the `where` keyword is suggested.

**Comment by Rekkonnect** [comment]
Can I take this one up?

**Comment by CyrusNajmabadi** [comment]
yes
