### ISSUE TITLE
Expose IMethodSymbol.ImplementationAttributes

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7282]
Currently we expose `IMethodSymbol.GetDllImportData` which contains the information about the P/Invoke attributes. Both C# and VB compilers populate this data during well known attribute decoding. This is very helpful information for analyzers looking at P/Invoke methods.

We also compute and store the [ImplementationAttributes](http://source.roslyn.io/Microsoft.CodeAnalysis.CSharp/R/37df62720b80ad32.html) that apply to the method during attribute decoding, but it is internal - I already found FxCop rules that need information such as PreserveSig data, and we should expose this to enable public analysis of P/invoke methods.

**Comment by gafter** [comment]
@mavasani Is this still of interest to you?

**Comment by mavasani** [comment]
@gafter, Yes the FXCop rule https://github.com/dotnet/roslyn-analyzers/issues/746 needs this data for analysis.

**Comment by jnm2** [comment]
Just started to need this in a tool that generates C# source from PE binaries.
