### ISSUE TITLE
Why "InvocationExpressionSyntaxAnalyzer.Analyze" Is being called thousands of times in this syntax analyzer ?

### ISSUE THREAD

**Issue by skillmaker-dev** [dotnet/roslyn#72857]
Hi all, I wanted to traverse the syntax tree of this file, and I'm trying to only extract nodes that are of the specified types and fill the children prop recursively so that i can get a tree with parents and children, however when I'm calling the GetInnerNodes Method, the InvocationExpressionSyntaxAnalyzer.Analyze inside if (childNode is InvocationExpressionSyntax invocationExpression) is being called thousands of times with the same parameters, I checked the syntax visualizer and it only contains the right number of invocations:

Here is the file i'm scanning (the same file containing the logic to scan files) :

    public static List<Node> GetInnerNodes(SyntaxNode syntaxNode, Type\[\] allowedTypes, ref CSharpCompilation compilation, Node? parentNode = null)
    
    {
    
   	 	var nodes = new List<Node>();
    
    	foreach (var childNode in syntaxNode.ChildNodes())
    
    	{
    
    		if (childNode is IfStatementSyntax syntax)
    
    		{
    
    			var nodeCustom = IfStatementSyntaxAnalyzer.Analyze(syntax, allowedTypes, ref compilation, parentNode);
    
    			if (nodeCustom is not null) nodes.Add(nodeCustom);
    
    		}
    
    		else if (childNode is MethodDeclarationSyntax methodDeclaration)
    
    		{		
    
    			var nodeCustom = MethodDeclarationSyntaxAnalyzer.Analyze(ref compilation, allowedTypes, methodDeclaration, 			parentNode);
    
    			if (nodeCustom is not null) nodes.Add(nodeCustom);
    
    		}
    
   			 else if (childNode is ClassDeclarationSyntax classDeclaration)
    
    		{
    
    			var nodeCustom = ClassDeclarationSyntaxAnalyzer.Analyze(ref compilation, allowedTypes, classDeclaration, parentNode);
    
    			if (nodeCustom is not null) nodes.Add(nodeCustom);
    
    		}
    
    		else if (childNode is InvocationExpressionSyntax invocationExpression)
    
    		{
    
    			var nodeCustom = InvocationExpressionSyntaxAnalyzer.Analyze(ref compilation, invocationExpression, parentNode);
    
    			if (nodeCustom is not null) nodes.Add(nodeCustom);
    
    		}
    
    		else if (childNode is NamespaceDeclarationSyntax namespaceDeclaration)
    
    		{
    
    			var nodeCustom = new Node
    
    			{
    
    				Id = Guid.NewGuid(),
    
    				ParentNode = parentNode,
    
    				ParentNodeId = parentNode?.Id,
    
    				SyntaxType = namespaceDeclaration.GetType().Name,
    
    				Kind = namespaceDeclaration.Kind().ToString(),
    
    			};
    
    			nodeCustom.Children = GetInnerNodes(childNode, allowedTypes, ref compilation, nodeCustom);
    
    			if (nodeCustom is not null) nodes.Add(nodeCustom);
    
    		}
    
    		else
    
    		{
    
    			// If the current child node is not of the specified types, go deeper
    
    			if (parentNode is not null) nodes.AddRange(GetInnerNodes(childNode, allowedTypes, ref compilation, parentNode));
    
    		}
    
    	}
    
    return nodes;
    
    }
    

And here is the logic behind InvocationExpressionSyntaxAnalyzer.Analyze:

    public static InvocationExpressionNode? Analyze(ref CSharpCompilation compilation, InvocationExpressionSyntax invocationExpression,Node? parentNode = null)
    
    {
    
    	Console.WriteLine(invocationExpression.ToFullString());
    
    	count++;
    
    	var node = new InvocationExpressionNode
    
    		{
    
    			Id = Guid.NewGuid(),
    
   			 	CodeBlock = invocationExpression.ToFullString(),
    
    			ParentNode = parentNode,
    
    			ParentNodeId = parentNode?.Id,
    
    			SyntaxType = invocationExpression.GetType().Name,
    
    			Kind = invocationExpression.Kind().ToString(),
    
    		};
    
    return node;
    
    }
    

the only difference between this analyze and the others is that other nodes can contain nested nodes and therefore i call GetInnerNodes in the children prop recursively: `classNode.Children = NodesService.GetInnerNodes(classDeclarationSyntax, allowedTypes, ref compilation, classNode);`

This is how the code is being called: 

```
var compilation = CSharpCompilation.Create("solutionName").AddReferences(Mscorlib);
var fileContent = File.ReadAllText(file);
var syntaxTree = NodesService.GetSyntaxTree(fileContent);
var rootNode = syntaxTree.GetRoot();
var scannedNodes = NodesService.GetInnerNodes(rootNode, allowedTypes, ref compilation)
```

count shows 11267 and the same parameters are called everytime, The method works fine and gives me the correct nodes tree, however i don't know why this huge number of calls is being done as it makes the code slow

**Comment by CyrusNajmabadi** [comment]
This issue lacks enough contextual information.  What is the code that is calling into this?

**Comment by CyrusNajmabadi** [comment]
Can you please update your code snippets to render/indent well?  Thanks :)

**Comment by skillmaker-dev** [comment]
I've updated the issue with more context

**Comment by skillmaker-dev** [comment]
> When you run this in a debugger, why do you get called so many times?

When I run it in debugger or release the method is called many times (10000) and when i log the syntax being analyzed it is the same syntax (InvocationSyntax in this particular method) over and over, it seems like it is stuck in a loop and somehow it breaks out of the loop and gives the correct results, Maybe i'm doing something wrong with the way i'm using recursion? By the way all the other analyze methods have the same logic as the one in the "if NamespaceDeclarationSyntax ..." They are just separated in separate methods.
Maybe there is something off about the last else ?

**Comment by CyrusNajmabadi** [comment]
> Maybe i'm doing something wrong with the way i'm using recursion?

Maybe.  Without your code, it's nearly impossible to tell :)

What are you different stacks where you're going into your method?  It should make it clear what's going on :)

**Comment by skillmaker-dev** [comment]
> > Maybe i'm doing something wrong with the way i'm using recursion?
> 
> Maybe. Without your code, it's nearly impossible to tell :)
> 
> What are you different stacks where you're going into your method? It should make it clear what's going on :)

Hi, thank you for the help, the issue was actually in another analyze method that i didn't provide, it was mainly about analyzing the if statement i was analyzing in the wrong way, thanks again for your time !

**Comment by CyrusNajmabadi** [comment]
YW.  BTW, you may want to bring questions like this to https://discord.com/channels/143867839282020352/598678594750775301 in the future.  There you can chat with the team and community in real-time :)
