### ISSUE TITLE
[Test Failure] Build Timed Out in prtest/win/vsi/p0 on PR #7263

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7286]
PR: [#7263](https://github.com/dotnet/roslyn/pull/7263) *Find 'Add Using' results with the same Fuzzy-match algorithm used by the spell-checker.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/79/

**Issue 1: Build Timed Out**
The build timed out, or was forcible aborted after reaching the maximum length. View the log right before the flagged timeout message to see what was happening.

**Comment by davkean** [comment]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/1103906/11639041/22538ff6-9cdf-11e5-97e3-910358152188.png)

**Comment by davkean** [comment]
This looks like BasicIntellisense.xml?

**Comment by Pilchie** [comment]
@CyrusNajmabadi Does this look related to your change?  If not, do you want to pull @rchande in to look at it with you?

**Comment by CyrusNajmabadi** [comment]
This was a bug in my PR that the test wonderfully caught.
