### ISSUE TITLE
AbstractFileHeaderDiagnosticAnalyzer uses `CustomSeverityConfigurable` but does not provide a way to set the custom severity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72876]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Analyzer-ignores-settings/10625971)._

---
[severity:I'm unable to use this version] [regression] [worked-in:`17.7.5`]
Analyzer ignores settings
the file (.editorconfig) contains the header settings

```
# File header preferences
dotnet_diagnostic.IDE0073.severity = warning
file_header_template = <copyright file="{fileName}" company="MyCompany">\nCopyright (c) Company. All rights reserved.\n</copyright>
```
and .csproj contains
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>
```
before updating to the current version, during assembly, if I did not specify the header in the file - I received an error, now this setting is ignored

sample of file header
```
// <copyright file="NewStateTests.cs" company="MyCompany">
// Copyright (c) Company. All rights reserved.
// </copyright>
```

---
#### Feedback Bot on 3/27/2024, 11:48 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 3/28/2024, 04:09 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 3/28/2024, 04:10 AM: 

(private comment, text removed)
#### Александр Платоненков on 3/30/2024, 05:02 AM: 

(private comment, text removed)
#### Александр Платоненков on 4/4/2024, 10:56 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 4/3/2024, 01:40 AM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 4/4/2024, 08:05 AM: 

(private comment, text removed)
#### Sam Harwell on 4/4/2024, 11:38 AM: 

<p>Hi <a target='_blank' href="https://developercommunity.visualstudio.com/user/1315100/profile">Александр Платоненков</a>,</p>
<p>You can ignore the previous request for more information. I found the source of the problem.</p>
<p>Thank you for the report and quick responses!</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue is caused by the use of `hasAnyCodeStyleOption: true` here:
https://github.com/dotnet/roslyn/blob/5019bd5e900909dda8bed2339fe2d9db0208e663/src/Analyzers/Core/Analyzers/FileHeaders/AbstractFileHeaderDiagnosticAnalyzer.cs#L23-L24

While this analyzer does use the `file_header_template` option in **.editorconfig**, it does not provide any way to set a diagnostic severity for this setting. This analyzer needs to pass `hasAnyCodeStyleOption: false` so the default severity controls will take effect.

**Comment by arkalyanms** [comment]
@sharwell would you work with @ToddGrun to knowledge transfer?

**Comment by Platonenkov** [comment]
when can we expect correction?

**Comment by sharwell** [comment]
@ToddGrun it should be as simple as changing the above line to `hasAnyCodeStyleOption: false`.
