### ISSUE TITLE
VB cref to C# default property does not show up in find all references

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7288]
- Create a C# project, paste the following code:

```
public class Indexable
{
    public string this[int index]
    {
        get { return ""; }
    }
}
```
- Create a VB project, paste the following code:

```
Class Program
    ''' <see cref="Indexable.Item(Integer)"/>
    Shared Sub Main()
    End Sub
End Class
```
- Reference C# project from VB project
- Do a FAR on "this" in the C# file or on "Item" in VB file

_Expected:_ 2 results - this definition in C# file and cref in the VB file
_Actual:_ 1 result - this definition in C#. The cref is missing

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of feedback.
