### ISSUE TITLE
Let users specify how/when their code styles will be applied.

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn#7289]
If the user has certain code styles specified (e.g., qualify member access with this/Me) there are 4 (quite possibly more) distinct levels of enforcement that they may want applied.  Roughly in order:
1.  Only apply to newly generated code/refactorings.
2.  Allow me to change styles that don't match, but I have to go looking for them (e.g., how "Inline temporary variable" is exposed today.)
3.  Notify me in the IDE (glyph, underline, etc.) but not via the error list (e.g., info).
4.  Notify me in the error list (e.g., info) and also on the command line.
5.  Notify me in the error list and also potentially break my build (e.g., warning, error.)

These should likely be applied to all items mentioned in #7071.

**Comment by dpoeschl** [comment]
6. Autofix on "line commit" (or something similar)

**Comment by dpoeschl** [comment]
We may not want all the levels (or may want a completely different approach), but we can be overly thorough about scenarios up front and reduce later.

**Comment by sharwell** [comment]
Items 4 and 5 (command line build reporting and proper handling of error severity) require the analyzer to be distributed via NuGet as opposed to the current method of installing them as IDE extensions.

**Comment by DustinCampbell** [comment]
This really isn't a feature request, but rather a design discussion.
