### ISSUE TITLE
Pull Diagnostics: Remove direct dependency on EnC, TaskList, Copilot diagnostic sources

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#72896]
These sources are currently hard-coded. Change the implementation to MEF-import diagnostic source providers.

Tracks TODO in code.

**Comment by CyrusNajmabadi** [comment]
Note: we'd like to have separate imports for:

1. copilot fixes.  They shuld move out of analyzer-semantic
2. EnC
3. Todo comments
4. Xaml (once they move to this).
