### ISSUE TITLE
In IIncrementalValuesProvider method Where with CancellationToken is not accessible.

### ISSUE THREAD

**Issue by pacyfist** [dotnet/roslyn#72919]
**Version Used**: 
Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4"
Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2"

**Steps to Reproduce**:

1. I followed the example from the cookbook:
https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md#additional-file-transformation

```csharp
using Microsoft.CodeAnalysis;

namespace CustomGenerator.Generators
{
    [Generator]
    public class AttributeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pipeline = context.AdditionalTextsProvider
                .Where(static (text, cancellationToken) => text.Path.EndsWith(".xml"))
                .Select(static (text, cancellationToken) =>
                {
                    var name = Path.GetFileName(text.Path);
                    var code = text.GetText(cancellationToken);
                    return (name, code);
                });
        }
    }
}
```

2. I got an error CS1593 `Delegate 'Func<AdditionalText, bool>' does not take 2 arguments`

**Diagnostic Id**:

CS1593

**Expected Behavior**:

The code should compile

**Actual Behavior**:

Error during compilation

**Comment by jaredpar** [comment]
@chsienki for comment

**Comment by chsienki** [comment]
This is a doc bug. `Where` doesn't take a cancellation token. I will update the docs.
