### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices should Embed Interop Types to VSLangProj

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7292]
1.  Create a project that references VSLangProj and set Embed Interop Types to true.
2. Add the "Microsoft.VisualStudio.LanguageServices" NuGet package to your project.
3. Build

_Expected results:_ no build errors or warnings.

_Actual results:_ you get a build warning -
CSC: A reference was created to embedded interop assembly 'VSLangProj, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because of an indirect reference to that assembly created by assembly 'Microsoft.VisualStudio.LanguageServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Consider changing the 'Embed Interop Types' property on either assembly.

(Originally filed by @eerhardt internally)

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
