### ISSUE TITLE
Visual Studio back button goes to top of file rather than previous location

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#72934]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-back-button-goes-to-top-of/10630211)._

---
When using Go To Implementation, I often want to go back to the previous file using the back button or ctrl+-. Often when I do, VS takes me back to the top of the previous file rather than the previous line location. See this screenshot for an example of the state:

![image.png](https://aka.ms/dc/image?name=Bd75febf6fb614a589f0a335d517ef96e638476984871812296_20240402-184807-image.png&tid=d75febf6fb614a589f0a335d517ef96e638476984871812296)

---
#### Alison Jin [MSFT] on 4/2/2024, 08:33 PM: 

(private comment, text removed)
#### Rich Kalasky on 4/3/2024, 06:51 AM: 

(private comment, text removed)
#### Feedback Bot on 4/8/2024, 02:13 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out.  We do not own this behavior.  Editor does.
