### ISSUE TITLE
IOperation: Add OperationKind.FieldInitialization

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#7293]
At present there is no obvious-to-a-user way to write an analyzer that examines field initializations. First you have to `RegisterOperationBlockStartAction`, and check that the `OwningSymbol` is a field. That's fine. But then come the problems.

First, you can't `RegisterOperationAction` and specify an `OperationKind` of `FieldInitialization`, because that doesn't exist.

Second, the operation associated with the field is an expression, but there is no single `OperationKind` for all expressions. So you have to register for `OperationKind.Literal`, `OperationKind.BinaryOperationExpression`, and `OperationKind.UnaryOperatorExpression`. (Oh, hah, and I forgot ternary operator.)

Third, once you've registered your callback, it won't just be called for the top-level expression: it will be called for subexpressions as well. For example, if the expression is `0 + 1`, your callback will be called three times: once for the binary operator and once for each literal. And there's no way to tell that you're looking at the top-level expression without dropping back down to syntax.

You can work around this by not registering a operation callback at all. Instead, in your start action, look directly at `operationBlockContext.OperationBlocks.First()`. But then, if you discover an issue, you can't report it directly, because `OperationBlockStartAnalysisContext` doesn't have `ReportDiagnostic`. So you also have to register an end action.

**Comment by genlu** [comment]
@JohnHamby do you think it is reasonable to reuse `IMemberInitializer` for this purpose (for both field and property inline initialization)? If so, I'm already working on some change for `IMemberInitializer`, you can sign this issue to me.

**Comment by JohnHamby** [comment]
I think there needs to be a way to distinguish between member initialization within an aggregate initializer (used to initialize a new instance outside of the declaring type) and member initialization at the point of declaration of the member.

For the analyzer @lgolding is writing, I don't know if both kinds of member initialization should be considered, but I would expect that to be the case for some analyzers.

**Comment by JohnHamby** [comment]
Addressed by #8087
