### ISSUE TITLE
XAML references are partially highlighted when searching for references from a constructor

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7294]
1. Create a new WPF application.
2. Go to MainWindow.xaml.cs, invoke find references on the constructor.

_Expected:_ the reference to the class name in XAML is entirely highlighted.
_Actual:_ it's partially highlighted.
_Observation:_ the number of characters highlighted is the same number as ".ctor".

![image](https://cloud.githubusercontent.com/assets/201340/11640217/4b6ce908-9ce6-11e5-934d-345d9f17c5ed.png)

**Comment by CyrusNajmabadi** [comment]
Not repro.  I get:

![Image](https://github.com/user-attachments/assets/10c28894-a053-4bbe-87f7-63bf12b2b45c)
