### ISSUE TITLE
Find References should support UnsafeAccessorAttribute

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#72958]
See https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute?view=net-8.0.

## Summary

Find All References for a symbol should be able to locate instances of `UnsafeAccessorAttribute` in the same solution that refer to the symbol. This would also apply to Rename features.

## Background and Motivation

`UnsafeAccessorAttribute` is a potential viable replacement for the TestAccessor pattern for unit testing, but only if it preserves the ability to navigate from a definition in code to uses of that code in tests.

## Proposed Feature

Find All References should recognize instances of `UnsafeAccessorAttribute` in the solution, and include those references in results.

## Alternative Designs

None so far

**Comment by CyrusNajmabadi** [comment]
So many concerns :D

**Comment by CyrusNajmabadi** [comment]
note: supporting this is... problematic.  A core part of FAR today is limiting the set of projects looked at for private members.

That said, i would not be opposed to the following:

1. our *syntactic index* looks for attributes of exactly the form `[...UnsafeAccessor(...)]` or `[...UnsafeAccessorAttribute(...)]` in code, and keeps track of the kinds/names of the symbol specified by the attribute.  This means that we would not support, for example, a global using alias that renamed this.  We need the syntactic index to be trivial to maintain without semantic info.
2. when doing a FAR, we would look at the syntactic indices in downstream projects and would see if their cached 'unsafe accessor' info referenced a symbol with the same name/kind as what the user was looking for.  Only in that case would we search that file.
3. When searching that file, when we found these attributes, we would then utilize our own special 'matching' logic, where we'd check the signature of the extern method the attribute was on to see if it was a symbol-match for the symbol in question.

**Comment by sharwell** [comment]
Yes, that's what I was expecting. The indexing functionality seems like it would support this without unreasonable overhead.
