### ISSUE TITLE
IOperation: Can’t represent a ConstantValue of null

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#7295]
`IExpression.ConstantValue` is of type `object`, so there's no way to represent a constant value of `null`. Perhaps it could be `Nullable<object>`, or perhaps `IExpression` could have a property `HasConstantValue`.

**Comment by genlu** [comment]
Isn't the type T in Nullable<T> must be a value type?

**Comment by lgolding** [comment]
You're right. So I guess we need `IExpression.HasConstantValue`.

**Comment by srivatsn** [comment]
We should be consistent with whatever `semanticModel.GetConstantValue()` does.

**Comment by JohnHamby** [comment]
SemanticModel.GetConstantValue returns an Optional<object>. Optional<T> has two properties: HasValue and Value. This will serve.

**Comment by lgolding** [comment]
Yes, IOperation's ConstantValue property is now Optional<object>, which is what was required. Verified.
