### ISSUE TITLE
CheckForOverflowUnderflow causes casts from nint to void* to fail with an OverflowException when the nint is negative

### ISSUE THREAD

**Issue by enclave-alistair** [dotnet/roslyn#72967]
**Version Used**: Appears to have first become an issue in .NET7, still present in .NET8.

Fundamentally, a cast from a `nint` pointer returned from a native function (for example by marshalling using a SafeHandle implementation), where the top bit is set, causes an OverflowException when casting to `void*`, when `CheckForOverflowUnderflow` is enabled in the project.

This issue has been noticed on 32-bit architectures, because that's the only time I've seen the top bit of a pointer set, but could still happen on 64-bit.

In my mind, casts from `nint` to `void*` should not apply a checked cast and trigger an OverflowException. Even when `CheckForOverflowUnderflow` is specified, because a negative `nint` value is absolutely a valid `void*`.

Manual pinvoke means this isn't a huge issue for us (can always use nuint as a return type); but `SafeHandle` uses nint as its handle type, which means the issue happens reliably if marshalling a returned pointer using `SafeHandle`, then casting the wrapped `SafeHandle.handle` to a `void*`. Workaround is to call `nint.ToPointer()` instead, which is defined in the runtime library that does not have `CheckForOverflowUnderflow` set.

The problem comes down to this generated IL (a custom function in a SafeHandle derived class that casts the `nint` to a pointer) differing between .NET8 and .NET 6:

.NET 8:
```csharp
// .method public hidebysig instance void*
  // GetPointer() cil managed
public unsafe void* GetPointer()
// .maxstack 8
// 
// IL_0000: ldarg.0      // this
// IL_0001: ldfld        native int [System.Runtime]System.Runtime.InteropServices.SafeHandle::handle
// IL_0006: conv.ovf.u
// IL_0007: ret
// 
{
  return (void*) checked ((UIntPtr) this.handle);
}
```

.NET 6
```csharp
// .method public hidebysig instance void*
  // GetPointer() cil managed
public unsafe void* GetPointer()
// .maxstack 8
// 
// IL_0000: ldarg.0      // this
// IL_0001: ldfld        native int [System.Runtime]System.Runtime.InteropServices.SafeHandle::handle
// IL_0006: call         void* [System.Runtime]System.IntPtr::op_Explicit(native int)
// IL_000b: ret
// 
{
  return (void*) this.handle;
}
```

**Steps to Reproduce**:

1. Enable CheckForOverflowUnderflow in the csproj.
2. Get a pointer that has the top bit set. In my case, this was discovered and recreated by using mmap with `MAP_PRIVATE | MAP_ANONYMOUS` flags. But any invoke function that returns a pointer that ends up as a negative `nint` will suffice.
3. Cast the nint to void*.
4. OverflowException.

Here's a repo that uses mmap to prove the problem; you can run `dotnet publish -c Release -f net8.0 -r linux-arm` to get a 32-bit ARM binary, which reliably reproduces the problem.

https://github.com/enclave-alistair/RoslynPointerCastingWithCheckedArithmetic

I can't provide SharpLab frustratingly, because there's no way to enable CheckForOverflowUnderflow.

**Expected Behavior**:

- Casting any number to `void*` should not trigger a checked cast, even with `CheckForOverflowUnderflow` switched on.

**Actual Behavior**:

- Casting a number, including nint, to `void*`, triggers a checked cast, and can fail with `CheckForOverflowUnderflow`.

**Comment by jaredpar** [comment]
@cston for comment

**Comment by cston** [comment]
I think casting an `nint` to a pointer type should succeed, even for negative values in a `checked` context.
```csharp
nint x = -1;
void* p = checked((void*)x); // should succeed
```

Adding @tannergooding, in case I'm overlooking something.

**Comment by tannergooding** [comment]
> I think casting a nint to a pointer type should succeed in all case

This isn't how it works for `int -> void*`, `long -> void*`, etc. Pointers are explicitly an unsigned type and thus checked conversions from a signed type should throw if the input is negative, it's how C# has always operated back to v1.0. Doing it with `nint` as well is just consistent with the longstanding behavior.

**Comment by tannergooding** [comment]
It's also worth noting that while historically many P/Invoke APIs have used `IntPtr` because it was convenient, didn't require unsafe, and generally just worked for x86/x64 Windows. But in the every expanding world, more platforms coming online, etc; that isn't really the "right way".

Because pointers are explicitly unsigned and because there are many contexts where `nint` is not a pointer, using `nint` for interop is largely incorrect and can cause problems (some ABIs, like RISC-V, have different behavior depending on if a type is signed or unsigned, so mismatching between C# and native can cause bugs -- the same is true for small types for some platforms and can break for cases like MacOS Arm64).

Thus, you generally want your P/Invoke to be fairly close to the actual C definition, matching types and signedness of said types where possible. If the native API takes a `T*`, you really should be passing a `T*` as well (and the newer P/Invoke source generators help make this easier and more correct: https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation).

**Comment by enclave-alistair** [comment]
Agree with @tannergooding that pointers should typically be referenced when doing P/Invoke using the correct pointer type; the issue then may actually be with SafeHandle, which in a lot of cases is recommended as a sensible way to manage memory/resources allocated by native code, but it uses `nint`, often the wrong type for the resource it wraps, which is how I found the problem.

I can't imagine it would be easy to break SafeHandle at this stage, so what is the recommendation?
