### ISSUE TITLE
Rationalize linked-file related APIs

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#730]
For example, the only publicly available version of "GetOpenDocumentInCurrentContextWithChanges" requires an ITextSnapshot. We have a version that accepts a SourceText but it's internal.

**Comment by CyrusNajmabadi** [comment]
We've been able to work with linked-files effectively for many years.  Closing this out as it's unclear what else we would need here.  If we're missing something, we should directly define what is needed and why.
