### ISSUE TITLE
ReferenceHighlightingViewTaggerProvider.cs should be moved to the newer tagger model

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7301]
Prior to #4046, we had a model where the reference highlighting had a TagSource that provided a single set of tags for all subject buffers in a view. We went away from that model, and we had the intent to move ReferenceHighlightingViewTagger forward to this model. If this caused performance issues, we'd optimize the find references engine to make sure it's not redoing work all the time rather than try to maintain the dubious approach where we try to do a single search for performance.

Right now, the tagger is doing a weird hybrid approach where it's implementing the old TagSource model but with stuff that's assuming there's a subject buffer. I don't see that ending well. It might also be the reason behind #7298, not sure.

(This was discussed with @CyrusNajmabadi.)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski looking at this tagger now, it seems to be sanely written.  So i'm going to close this out.  If you think we do need to do something here, please let me know :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Yes, I think we did end up rewriting this.
