### ISSUE TITLE
Code cleanup fixer "Remove unnecessary imports or usings" breaks code inside #if directives

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73027]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-cleanup-fixer-Remove-unnecessary-i/10638359)._

---
When usings are removed as part of a cleanup, it only considers code for the current configuration. If you have code inside #if directives that requires usings that the other configurations do not, it will remove the usings and break the build for those other configurations. This is especially dangerous when the cleanup is performed as part of a Save operation as it can easily break RELEASE builds.

Consider this pseudocode:

```  
using NamespaceA;
using NamespaceB;

...

#if DEBUG
    // code that requires NamespaceA but not NamespaceB
#else
    // code that requires NamespaceB but not NamespaceA

```

When in a DEBUG configuration, `using NamespaceB` will be removed.  
When in a RELEASE configuration, `using NamespaceA` will be removed.

---
#### Feedback Bot on 4/14/2024, 10:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
Duplicate of #49925

**Comment by sharwell** [comment]
This is a duplicate of the issue above, particularly in relation to the following comment:
https://github.com/dotnet/roslyn/issues/49925#issuecomment-749268021

**Comment by CristianTGT** [comment]
@sharwell This is still an issue - I just had it in VS 2022 and can reproduce it. Could this be looked into? 

The description is accurate. If you have a block as below:

```
#if DEBUG
            string test = "test";
#else
            // Here we want to read from configuration in a dotnet Controller.
            string test =_configuration.GetValue<string>("testConfigValue");
```

GetValue relies on "using Microsoft.Extensions.Configuration;" being present. 
If I then run code cleanup in DEBUG configuration, that using is removed and build fails in all configurations apart from DEBUG

**Comment by CyrusNajmabadi** [comment]
@CristianTGT see https://github.com/dotnet/roslyn/issues/49925#issuecomment-749669276.
