### ISSUE TITLE
CA2000 Use recommended dispose pattern to ensure that object created

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/roslyn#73021]
**Version Used**: 
4.10.0-3.24202.15

**Steps to Reproduce**:
This code in MSBuild generates CA2000:
https://github.com/dotnet/msbuild/blob/6fec6072f0591bede57a71474ddc08b95e3e4c28/src/Build/Evaluation/IntrinsicFunctions.cs#L294

**Diagnostic Id**:
CA2000

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
No warning occurs.

**Actual Behavior**:
The warning is displayed.

**Comment by CyrusNajmabadi** [comment]
CAxxxx diagnostics are produced by dotnet/Roslyn-analyzers. Unfortunately GitHub is not letting me move this issue there :-(

**Comment by YuliiaKovalova** [comment]
no worries, I will create it in their repo.
Thank you!
