### ISSUE TITLE
Resource strings shouldn't be duplicated between the compiler and workspaces layer

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7306]
Consider https://github.com/dotnet/roslyn/blob/67b0e058329fa9ab6eb76945ecc4bea17f9994bc/src/Compilers/Core/Portable/Serialization/ObjectWriter.cs#L198

Rather than having two files with the same strings, we should share the same resx between the two layers.

**Comment by davkean** [comment]
I'll move this to IDE, as it's the higher layer, and hence work will probably go into the workspaces layer.

**Comment by CyrusNajmabadi** [comment]
Closing out we have a system for sharing resources now with shared files.  If someone wants to go find out if there are duplicated resources still, feel free.
