### ISSUE TITLE
Cutting/Pasting a selected Region fails to persist it's collapsed state

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73065]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CuttingPasting-a-selected-Region-fails-/10639658)._

---
[severity:It's more difficult to complete my work]
If the line of a collapsed #Region is selected, copied, then pasted, the pasted Region text does not persist the copied Region's Collapsed state.

i.e. Copy a Collapsed Region line, paste it, and the new pasted Region text is Expanded.

Expected behavior would be that the collapsed state of the pasted region would be maintained.

---
#### Feedback Bot on 4/16/2024, 09:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Closing out as unplanned due to the high complexity to solve this niche case.
