### ISSUE TITLE
Remove reflection hack in GetViewFromIVsIntellisenseHost

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7309]
Right now in [this code](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/VisualStudio/Core/Def/Implementation/Venus/ContainedLanguage.IVsContainedLanguage.cs#L45) we do terrible reflection against the editor. The editor team added an API for us (IVsTextViewIntellisenseHost2) for us to use to get this, but we never moved to it.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski should this still be assigned to ravi?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Well, he _could_ still make contributions. That said, I'll reassign to me.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to amke this change, it has to be assigned to a dev/milestone.  Having a bug open for 9 years is not providing *any* value.
