### ISSUE TITLE
DocumentInfo.Create() allows you to create instances with a null TextLoader

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#7310]
This doesn't really make sense. A document you can't get the text of? Do we use this somewhere, or should a null check be added?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/11004

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi That PR wasn't merged, did we fix this somewhere else?

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we need this, please assign to a dev/milestone.
