### ISSUE TITLE
No semantic syntax highlighting until a change is made

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#73119]
**Version Used**: 17.10.P4

**Steps to Reproduce**:

Have a simple console app. Start VS, open the solution, open a file for the first time.

https://github.com/dotnet/roslyn/assets/9047283/372ab795-ab32-402c-b9af-19dd9a745908

(Basic console app with 1 file and 50 lines of code.)

**Diagnostic Id**:
Not applicable.

**Expected Behavior**:
Types are colorized (and everything else works) immediately after I open VS, a solution and open the first file.

**Actual Behavior**:
Semantic information seems to be available (quick info works, references are highlighted), but types are not colorized. I need to make a change to make it work. Opening the same file the next time, or opening another file works after this point.

**Comment by DoctorKrolic** [comment]
Voting on this one, I've observed that behavior quite a lot in recent time as well, though I thought this is because roslyn solution is too large to colorize quickly

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/72878.
