### ISSUE TITLE
IOperation: Doesn't consider CChar(0) initializer an operation block

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn#7313]
Given this VB code:

```
Public Class C
    Private c As Char = CChar(0)
End Class
```

If an analyzer registers an operation block start action, the callback is never called.

**Comment by JohnHamby** [comment]
This is a compiler issue that won't get fixed for 1.2.

**Comment by mavasani** [comment]
Does not repro on latest Roslyn bits.
