### ISSUE TITLE
Prefix "extension" for "extension method" in Japanese must be "拡張", not "拡張子"

### ISSUE THREAD

**Issue by tats-u** [dotnet/roslyn#73175]
## Repo URL where the string lives

https://github.com/dotnet/roslyn

## File Name

https://github.com/dotnet/roslyn/blob/main/src/Features/CSharp/Portable/xlf/CSharpFeaturesResources.ja.xlf
https://github.com/dotnet/roslyn/blob/main/src/Features/VisualBasic/Portable/xlf/VBFeaturesResources.ja.xlf

## Resource ID

- `extension` (C#)
- `awaitable_extension` (C#)
- `Awaitable_Extension` (VB)

## English String

extension
awaitable, extension
Awaitable, Extension

## Current Translation

拡張子
待機可能、拡張子
待機可能、拡張子

## Suggested Translation

拡張
待機可能、拡張
待機可能、拡張

Note: "・" instaed of "、" is preferred in my opinion because "・" is often used as &.

待機可能・拡張

## Language

Japanese

## Why Fix is needed

"拡張子" means ***file*** extension.
"Extension method" is translated into "拡張メソッド".

--- 
## Roslyn Team Instructions

A Roslyn team member will file a bug through https://aka.ms/ceLocBug which the translation team will consider.

Internal Tracking Issue: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/968500

**Comment by tats-u** [comment]
Shall I send a PR to fix this? I have already pushed its content to my forked repo.

**Comment by huoyaoyuan** [comment]
This may be applicable to other languages too.
Please inform the localization teams to create a name for the *extension* feature.

**Comment by tats-u** [comment]
Yes. It is used as annotating that the currently suggested method candidate is an extension one.

![image](https://github.com/dotnet/roslyn/assets/12870451/1dac4f24-c8ad-4275-906c-b79c5f185248)

It is used as only this purpose.

https://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Microsoft.CodeAnalysis.CSharp.CSharpFeaturesResources.cs,433053edc5e6d83d,references

**Comment by genlu** [comment]
@tats-u thanks for you feedback and I filed an internal bug for the localization team.

**Comment by tats-u** [comment]
I confirm the correction of those translations.
