### ISSUE TITLE
Cache contains wrong information about COM interop after changes in the COM interfaces

### ISSUE THREAD

**Issue by magol** [dotnet/roslyn#73191]
**Version Used**: Visual studio 2022

**Steps to Reproduce**:

1. Create a COM object in C++ using MFC/ATL
2. Create an interop DLL using tlbimp
3. Use the interop DLL in a C# project
4. Make changes in the IDL file for the COM object (eg remove a function)

**Expected Behavior**:
After that I have rebuilt the C++ code, the interop dll and the C# code, I expect that the C# code should work.

**Actual Behavior**:
When I call a COM function located after the removed function, it calls the wrong function.

The only way to get the code to work was to remove `%LOCALAPPDATA%\Microsoft\VisualStudio\Roslyn\Cache`

**Comment by CyrusNajmabadi** [comment]
> The only way to get the code to work was to remove %LOCALAPPDATA%\Microsoft\VisualStudio\Roslyn\Cache

The only information stored in that cache relates to indices used for "navigate to", "find references", "add import" and "as nuget package".  Nothing in there affects the compiler at all.

**Comment by magol** [comment]
That's weird.
I noticed that COM functions returned strange data. And when I stepped in the code with F11, I ended up in the wrong C++ functions. Been troubleshooting this for weeks. But as soon as I deleted the cache directory it started working. There is no information in the cache that it uses to find index in the vtable for COM?

**Comment by CyrusNajmabadi** [comment]
> There is no information in the cache that it uses to find index in the vtable for COM?

Correct.  The cache is purely for a handful of ide features. It has no impact on the compiler whatsoever.

**Comment by genlu** [comment]
@jaredpar The behavior from compiled code seems to be a compiler issue (despite the observation from @magol around removing IDE cache)

**Comment by jaredpar** [comment]
Do you have a standalone repro that we could look at? 

> despite the observation from @magol around removing IDE cache

Wonder if there is an underlying rebuild / up to date issue here that removing the IDE cache subtly works around.
