### ISSUE TITLE
Completion list shouldn't show accessibility modifiers in interfaces

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/roslyn#732]
Filed by @SLaks

Inside an interface body, IntelliSense shows "public" (only; I guess we confused resolved accessibility with legal modifiers).

Inside a property block in an interface, it shows all accessibilities.

**Comment by EricArndt** [comment]
Should any of the accessibility modifiers be shown in IntelliSense since they're not legal to have in the interface body?

![interface](https://cloud.githubusercontent.com/assets/2079517/6499092/4cb2dae6-c2c3-11e4-8a20-0fb2465ccd8b.png)

**Comment by Pilchie** [comment]
No.  That's the bug :smile:

**Comment by EricArndt** [comment]
OK. Just making sure. :smile:
