### ISSUE TITLE
MSBuild won't honor suppressed code analyzer warnings

### ISSUE THREAD

**Issue by twenzel** [dotnet/roslyn#7321]
This is a copy from https://github.com/Microsoft/msbuild/issues/391.

I'm using a (Roslyn) Code Analyzer in our projects (per NuGet). 
For some projects I changed the severity of the analyzer to "Hidden" by right click on the analyzer within the solution tree in Visual Studio and choose "Set Rule Set Severity -> Hidden". VS creates a new .ruleset file for this project. Now all warnings are gone (in "Error List" pane) in Visual Studio.

But when I'm building this solution with MSBuild from command line the warnings still appear.
Is this a bug? Or how can I disable a particular analyzer that will be honored in VS and MSBuild command line?

**Comment by mavasani** [comment]
@twenzel Did you do a save your project file after setting the new severity? I have accidentally run into this many times myself. If you did do a save, then can you also verify that the ruleset property matches your build configuration? The command Set Rule Set Severity sets the CodeAnalysisRuleSet only for Debug and Release configurations, and if you are building for a different config, then the ruleset will not be honored. See the discussion here: dotnet/roslyn#6774 (comment)

**Comment by twenzel** [comment]
Yes the project file was saved and is up to date. The CodeAnalysisRuleSet property is also set for the correct Release/Platform configuration.

**Comment by mavasani** [comment]
Can you share a repro project?

**Comment by twenzel** [comment]
I checked out that this problem occurs only when executing MSBuild on our build server.
When executing on dev machine (VS2015 installed) the configured ruleset will be honored.
So I guess this is not a Roslyn problem but a MSBuild. I'll close this issue and continue discussing on https://github.com/Microsoft/msbuild/issues/391.
