### ISSUE TITLE
CS3006 false-positive on operators with `in` keyword

### ISSUE THREAD

**Issue by Jozkee** [dotnet/roslyn#73212]
**Version Used**: 4.11.0-1.24210.5

**Steps to Reproduce**:
See [sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTBtCBnPAUzGABsBPEAYQBkBlKgezAAdSoIYAXACi4CcAroQCUAXUyYEAZgAEyWVVkBvTLPXy5CFADZZUVuwDGULrMYtC/CF0b993HkoBuEUsJFqNy2V40aEAHZZABNCADMIQVIuAG5fDH8AXz8E/xl5XX1DKBMzCysbO0yABh5YRVlXd1FU1UT/AOCwyOiuAEJY1JSMJKA==) repro.

this also reproes with `explicit`. Also note that the rule warns the method at the bottom. So moving the operator with `in` on top, will make the other warn.

**Diagnostic Id**: CS3006

**Expected Behavior**: Do not warn because there's no overload that only differs on `in`, `ref`, `out`, or array rank.

**Actual Behavior**: It warns.

It looks related to https://github.com/dotnet/roslyn/issues/52134.

**Comment by jaredpar** [comment]
Closing as CLSCompliance issues, particularly for newer features, are not something we are investing in at this time.
