### ISSUE TITLE
Force Type Convert QuickAction Bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73211]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Force-Type-Convert-QuickAction-Bug/10645885)._

---
\[severity:It’s more difficult to complete my work\]  
Using VisualStudio 17.9.6  
When I use char variables for compound assignment operators, I get some Error with QuickAction

```  
char character='A';

// Base Code.throw Error CS0266. Thats Normal.
character+=1;

//use QuickAction Accept Force Type Convert. I got 2 Error CS0266 CS1547
(void)(character+=1); 

//This is Potential result
character+=(char)1; 
  
```

---
#### Feedback Bot on 4/24/2024, 05:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I'm almost 100% positive this is a dupe

**Comment by genlu** [comment]
@CyrusNajmabadi do you have a link to the dupe?
