### ISSUE TITLE
Implement telemetry events for telemetry funnel in C# devkit

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#73224]
In order to get better reliability metrics, we're implementing a telemetry funnel across C# devkit / C# extension.   This will help us better understand where people drop off (even if we're 'functioning' as expected). On the devkit side we're adding (finding) telemetry metrics that represent various stages of the project load (launch, restore, complete).  

On the roslyn side we need to add the following metrics:
1.  SDK acquisition results
2.  Report when devkit sends us the project
3.  Report when we finish loading the information devkit sent.
4.  After project is loaded, report % requests that are still getting sent to the misc files worksapce.

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to be done, it needs to be assigned a milestone.
