### ISSUE TITLE
Type recognition error in Visual Studio

### ISSUE THREAD

**Issue by chrisdaiii** [dotnet/roslyn#73228]
**Microsoft Visual Studio Enterprise 2022 （64-bit）17.9.4**: 

```c#
string Method(dynamic obj)
{
    return String.Emprt;
}

dynamic a = 1;
var str = Method(1);
```

When I move the mouse over str, the dynamic? type is displayed. At the same time, str is recognized as a dynamic type in the following code, and there is no automatic completion list smart prompt.

**Comment by CyrusNajmabadi** [comment]
That's expected as per how the language works with dynamic.  Since the argument is dynamic, the result will be considered dynamic as well, as the call will be resolved at runtime.
