### ISSUE TITLE
Source generator doesn't see DefaultMemberAttribute

### ISSUE THREAD

**Issue by jkurdek** [dotnet/roslyn#73229]
When working with source generators we encountered the following:

```
public class C
{
    [IndexerName("MyIndexer")]   
    public int this[int x]
    {
        get => 1;
        set { }
    }
}
```

This generates `DefaultMemberAttribute(MyIndexer)` on class C. However, when inspecting properties of C from within transform function of `IncrementalSourceGenerator` this information is not available. 

[SharpLab
](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyAMABMugHQBKArgHbBgC2ApiQMID2dADpAwE4DKvAG5gAxgwDOAbhzIAzEVQFmOAN44CGggG0AklRgMAHrwByAQ0YAKAEQBZAJ56DxntYCUAXU3rNcgmBoCYAALMHEtAOACQw8fDTVsTSSCAHMGKIBeAD4CdGlE5I1xdIIVAgBfOIqccqA===)

**Comment by CyrusNajmabadi** [comment]
Can you supply a full repro?

**Comment by jaredpar** [comment]
Closing due to lack of response.
