### ISSUE TITLE
`IDE0010: Populate Switch` gives up with simple `or` pattern match

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#73245]
**Version Used**: 
.NET 8.0.204

**Steps to Reproduce**:

``` csharp
public bool DummySwitch(Values value)
{
    switch (value)
    {
        case Values.One or Values.Two:
            return true;
        default:
            return false;
    }
}

enum Values
{
    One,
    Two,
    Three
}
```
1. 
2. 
3. 

**Diagnostic Id**:

`IDE0010`

**Expected Behavior**:

Warning: Populate switch

**Actual Behavior**:

No Warning

**Additional Context**

If you use the classic switch cases, the warning appears:

```csharp
public bool DummySwitch(Values value)
{
    switch (value)
    {
        case Values.One:
        case Values.Two:
            return true;

        default:
            return false;
    }
}

enum Values
{
    One,
    Two,
    Three
}
```

**Comment by RenderMichael** [comment]
I am happy to try and fix this myself, as long as this is desired behavior. The analysis for this can get arbitrarily complex, and there's gotta be a cutoff somewhere, especially for an analyzer this... minor. But the simple `or` case feels like a scenario which should be supported.

**Comment by CyrusNajmabadi** [comment]
Sure!  Go ahead :)
