### ISSUE TITLE
Suggestion: csc infer target from output parameter and/or lack of Main method

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7325]
Many times I just want to compile something quickly like `csc foo.cs`.

It would be nice if compiler could decide the target based on the presence of a `Main` method and emit it with an appropriate extension. Perhaps with a warning if the target is not the default.

Similarly, it could extended to support something like `csc /out:bar.dll foo.cs` to decide the target as a library too.

**Comment by tmat** [comment]
I'm curious, what do you use libraries compiled that way for?

**Comment by leppie** [comment]
@tmat Nothing specific. But it you do stuff from the command line it becomes handy. Example:
```
csc foo.cs & csc /r:foo.dll baz.cs & csc /r:baz.dll bar.cs & bar
```

**Comment by tmat** [comment]
If you just need to compile a snippet of C# code why not use C# scripts?

**Comment by leppie** [comment]
@tmat: A script implies a program. I dont understand what you mean.

I cant remember how many times I forget to add `/t:library` when just creating a simple class for testing something on the command line (yes, via `copy con`). I agree in project scenario, this would be silly.

**Comment by tmat** [comment]
@leppie Yes, it implies a program. I just can't see a common scenario where I would build a library on command line that I'd need to add a reference to in some other project. 

BTW, why don't you define a shell alias? For example, ```cscl``` which passes /t:library.

**Comment by leppie** [comment]
@tmat: That is not a bad idea :+1:

**Comment by tmat** [comment]
OK, I'll close this issue then. Thanks.

**Comment by leppie** [comment]
For those wanting to add an alias:
```
doskey cscl=csc /t:library $*
```
