### ISSUE TITLE
Unhelpful/annoying intellisense suggestion when calling method with params if the argument is an expression/func

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73257]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unhelpful-intellisense-suggestion-when-c/10648170)._

---
\[severity:It’s more difficult to complete my work\]  
I have the following method:  
`public void AddOldValues(params Expression<Func<T, object>>[] fields)`

The idea being to call it like this with an object:

```  
using var auditScope = client.Audit.Begin(dbCourse); // public AuditScope<T> Begin<T>(T entity)
auditScope.AddOldValues(
    c => c.Field1,
    c => c.Field2,
    c => c.Field3
);
  
```

Very annoyingly, intellisense doesn’t pick up that I’m trying to write a lambda expression so whenever I type ‘c’ it tries to autocomplete an existing member name that happens to begin with c (or sometimes ‘char’)

In order to actually write a new line like the above, I need to:

1.  Type c
2.  Press esc to close intellisense
3.  Write =>c
4.  Press esc again
5.  Write the rest (. FieldName)

Please fix this as it is incredibly annoying…!

---
#### Feedback Bot on 4/27/2024, 09:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I don't repro this.  We're properly in suggestion mode here.
