### ISSUE TITLE
RelationalOperatorType: Invalid OperatorType for Char

### ISSUE THREAD

**Issue by bernd5** [dotnet/roslyn#73267]
The function [RelationalOperatorType](https://github.com/dotnet/roslyn/blob/39b5d9d8f1346123c12a84e58b9c5e9a471f8f6a/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs#L1699) in `Binder_Patterns.cs` returns the wrong operator type for `char`:

```csharp
internal static BinaryOperatorKind RelationalOperatorType(TypeSymbol type)
````

It should be `int` like we do for `byte`.
Currently this seems to have no impact because the type is actually not evaluated/analyzed during codegen / emit - but it should be correct.

**Comment by jaredpar** [comment]
@333fred is this intentional or a bug?

**Comment by 333fred** [comment]
@bernd5 why are you asserting that it should be `int`?

**Comment by bernd5** [comment]
It is like with Byte, SByte ... `char` defines no `operator==`, `operator!=`...
If you write: `achar == 'a'` the integer operator is used.

-----

This function is called by `PatternLocalRewriter.MakeValueTest`:

```csharp
  var operatorType = Binder.RelationalOperatorType(comparisonType);
  Debug.Assert(operatorType != BinaryOperatorKind.Error);
  var operatorKind = BinaryOperatorKind.Equal | operatorType;
```

so we get `BinaryOperatorKind.Equal | BinaryOperatorKind.Char`
This value does not exist in BinaryOperatorKind.

If you would call for example `BuiltInOperators.GetSignature` with this value you get a Debug.Assert error in `BuiltInOperators.LeftType`

**Comment by 333fred** [comment]
It looks like changing that to `int` would likely fail several asserts in local rewriting, such as https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs#L414-L422. Without a specific example of a failure here, I do not want to make any changes.
