### ISSUE TITLE
Error when applying IDE0079 in problems tab

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#73272]
From vscode-dotnettools created by [solrevdev](https://github.com/solrevdev): microsoft/vscode-dotnettools#214  

Type: <b>Bug</b>

In the problems tab I click on the lightbulb next to the first "Remove unnecessary supression (IDE0079) line then choose the single refactoring line then I get an error and the expected refactoring does not happen.

Extension version: 0.1.103
VS Code version: Code - Insiders 1.80.0-insider (7406a9bdfca18f82a3977ba5eac908d41df7ccac, 2023-06-30T05:37:52.506Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30769768
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30779712
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by Cosifne** [comment]
I can't repro the problem using `v2.36.19 (pre-release)`
![image](https://github.com/dotnet/roslyn/assets/24360909/c0f3c558-3352-417a-80aa-09a917f38d49)

then I can get the correct result.
![image](https://github.com/dotnet/roslyn/assets/24360909/7609b261-f49f-4c57-a60f-8be93c46e9dc)

I will close this. If anyone has seen this repro, feel free to paste the code snippet and reopen it.
