### ISSUE TITLE
[BUG]  "Move Type To .." feature not generating new .cs file

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/roslyn#73273]
From vscode-dotnettools created by [cha0tic75](https://github.com/cha0tic75): microsoft/vscode-dotnettools#327  

### Describe the Issue

I am a Unity Game Developer who uses VSCode. I use the "Move Type To..." tool quite frequently and it was working perfectly yesterday morning. After a short break and reboot, I noticed that VSCode had updated to V1.81.0 and a short time later that when ever I wrote a class definition within an existing .cs file and tried to move the class to its own file using the "Move Type To..." feature, by highlighting the class definition and ctrl . "Move Type To <filename>", that the highlighted class definition would be removed but a new .cs file would not be created.  I tried to: close VS Code, close Unity project, reopen unity project and reopen a C# script. I tried to "Regenerate project files" within the Unity preferences window. I tried to downgrade then upgrade the Visual Studio Code package in the Unity Package Manager, I checked VSCode extensions for any updates and updated any that needed. I installed the new Unity Extension. Downgrading C# Dev Kit to V0.2.100. And still the same behaviour.  I loaded some other Unity projects and note that they I am not even presented with the "Move Type To.." option when trying to do the same task.

### Steps To Reproduce

Opened my Unity 2020.3 project, and double clicked on a cs file to open in VSCode.  Wrote a new class definition within the namespace block in the currently opened file, highlighted and pressed ctrl . for context menu, using arrow keys navigated to the "Move Type To <classname>.cs" and pressed enter. The highlighted class definition disappears as it normally would as though it had been moved to the new file but a new cs file is not generated and new tab created with moved class definition is not displayed.

### Expected Behavior

Generally when using the feature, the selected code is removed from the current cs file and placed into a newly generated cs file and a new tab is opened with the moved code.

### Environment Information

- OS: Windows 11 Build 22H2
- VSCode V 1.81.0
- Unity 2020.3.47f1
- Extensions:
      C# Dev Kit V0.3.21
      Unity V0.9.0

**Comment by JoeRobich** [comment]
@cha0tic75 Is this still an issue for you? I was unable to reproduce with C# DevKit v1.4.29.
