### ISSUE TITLE
[Test Failure] CSharpGoToImplementation reports "The symbol has no implementations."

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7329]
PR: [#7290](https://github.com/dotnet/roslyn/pull/7290) *Weed out flaky VSI tests* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/88/

**1 Test Failures:**
CSharpGoToImplementation.Go To Implementation opens in a provisional tab if document wasn't already open

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpGoToImplementation.xml

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1103906/11665742/cccac1ca-9d9d-11e5-87e2-c18a8b3eae5b.png)

**Comment by davkean** [comment]
This is similar to: https://github.com/dotnet/roslyn/issues/6863 and https://github.com/dotnet/roslyn/issues/7256. Are they caused by the same issue?

**Comment by davkean** [comment]
This is being disabled in this PR: https://github.com/dotnet/roslyn-internal/pull/434

**Comment by dpoeschl** [comment]
Executing action [12/8/2015 2:59:03 AM] GoToImplementation
--------------------------------
Tao.Engine.Exceptions.UnexpectedResultException: Expected notification text: []
Actual notification text: [The symbol has no implementations.]
   at Roslyn.VSHosting.Test.RoslynActions.RoslynVisualStudioAction.AfterExecute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Closed\Hosting\RoslynTaoActions\Actions\VisualStudio\RoslynVisualStudioAction.cs:line 157
   at Tao.Engine.DebuggableActionExecutor.AfterExecute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 120
   at Tao.Engine.DefaultActionExecutor.AfterExecute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 50

**Comment by dpoeschl** [comment]
Trying to get a failure on this in https://github.com/dotnet/roslyn-internal/pull/451

**Comment by dpoeschl** [comment]
Reenabled with logging in https://github.com/dotnet/roslyn-internal/pull/451
