### ISSUE TITLE
SyntaxGenerator doesn't support generating OperatorDeclarations

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#733]
We have [PredefinedOperator](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LanguageServices/SyntaxFactsService/PredefinedOperator.cs,d17c5b572f4bf967) which we should probably make public and add an API to SyntaxGenerator that adds a given PredefinedOperator so that Operator declarations can be generated in language independent way.

**Comment by DustinCampbell** [comment]
This was done with #7303 by @CyrusNajmabadi
