### ISSUE TITLE
Opt into client side STJ serialization

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#73317]
We should tell the LSP client to use STJ for client side serialization.  See https://github.com/dotnet/roslyn/pull/72675

This is currently blocked on Razor moving to APIs that do not depend on Newtonsoft.

**Comment by CyrusNajmabadi** [comment]
How much razor work is there?  And are they signed up to do this soon?

**Comment by dibarbet** [comment]
Yes, everyone is moving over,  @phil-allen-msft is p2 a good target for Razor?
