### ISSUE TITLE
New APIs to support "Ref Struct Interfaces" feature 

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#73330]
## Background and Motivation

https://github.com/dotnet/csharplang/blob/main/proposals/ref-struct-interfaces.md

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// Specifies capabilities that may or may not be supported by the common language runtime the compilation is
    /// targeting.
    /// </summary>
    public enum RuntimeCapability
    {
+       /// <summary>
+       /// Indicates that this version of runtime supports generic type parameters allowing substitution with a ref struct.
+       /// </summary>
+       ByRefLikeGenerics = 8,
    }
}
```
 The name of the new enum item matches the name of the field from BCL - `System.Runtime.CompilerServices.RuntimeFeature.ByRefLikeGenerics` (see https://github.com/dotnet/csharplang/blob/main/proposals/ref-struct-interfaces.md#representation-in-metadata).

```diff
namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// Represents a type parameter in a generic type or generic method.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface ITypeParameterSymbol : ITypeSymbol
    {
+       /// <summary>
+       /// True if the 'allows ref struct' constraint was specified for the type parameter.
+       /// </summary>
+       bool AllowsByRefLike { get; }
    }
}
```
The new property is named after a flag in BCL `System.Reflection.GenericParameterAttributes.AllowByRefLike` (see https://github.com/dotnet/csharplang/blob/main/proposals/ref-struct-interfaces.md#representation-in-metadata).

**Comment by 333fred** [comment]
### API Review

* Naming of `Allows` vs `Allow`?
    * English prefers allows here
* Shakespeare's famous question: "To By or not to By?"
    * For consistency with `ITypeSymbol.IsRefLikeType`, we'll name it `ITypeParameterSymbol.AllowsRefLikeType`

**Conclusion**: Approved, with the rename of to `ITypeParameterSymbol.AllowsRefLikeType`. The `RuntimeCapability` name is approved as-is.
