### ISSUE TITLE
Type arguments are not being inferred correctly from method group

### ISSUE THREAD

**Issue by hez2010** [dotnet/roslyn#73347]
**Version Used**: .NET 8

**Steps to Reproduce**:

```cs
var foo = new Foo();
Bar(foo.A<int, int, int, int>); // <--- error
Bar(ReturnMySelf(foo.A<int, int, int, int>)); // <--- ok

void Bar<T1, T2, T3, TResult>(Func<T1, T2, T3, TResult> func) {}
T ReturnMySelf<T>(T x) => x;

class Foo { public extern TResult A<T1, T2, T3, TResult>(T1 a, T2 b, T3 c); }
```

It's too weird that you just return the type itself and then it gets inferred. 

**Expected Behavior**:

The compiler can infer the type arguments in both two `Bar` calls.

**Actual Behavior**:

Only the second call `Bar(ReturnMySelf(foo.A<int, int, int, int>))` can infer the type arguments correctly.

**Comment by huoyaoyuan** [comment]
I believe this is a language issue, natural type of method group doesn't employ such inference.

**Comment by jcouv** [comment]
Yes, I think this is currently by-design. We have a [csharplang proposal](https://github.com/dotnet/csharplang/issues/7687) to make this work.
Note: the current workaround would be to use a lambda `Bar((int x, int y, int z) => foo.A<int, int, int, int>(x, y, z));`.
