### ISSUE TITLE
Overload resolution ambiguity introduced by SDK 8.0.300-preview.24203.14

### ISSUE THREAD

**Issue by danielcweber** [dotnet/roslyn#73346]
The SDK 8 preview that comes with the latest VS2022 preview introduces an overload resolution ambiguity that is not in the stable SDK.

**Version Used**:

8.0.300-preview.24203.14

**Steps to Reproduce**:

See [this repo](https://github.com/danielcweber/OverloadResolutionRepro) for a reproduction and [this](https://github.com/danielcweber/OverloadResolutionRepro/actions/runs/8719145734) or [this](https://github.com/danielcweber/OverloadResolutionRepro/actions/runs/8720044992) workflow run to watch a build fail.

The issue is also in the latest SDK 9 preview. It's not reproducible on dotnetfiddle/sharplab, the latest SDK bits there are seemingly not recent enough.

Everything is fine on 8.0.204.

This might be related to collection expression conversions since the method overload in question has a `params` [] parameter.

Note: I also opened an issue in [the sdk repo](https://github.com/dotnet/sdk/issues/40235) but this might be the more appropriate place.

**Comment by cston** [comment]
Overload resolution is not preferring the method with the more specific `params` array type in this case: see [BetterFunctionMember](https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs#L2239-L2277).

cc @AlekseyTs

**Comment by AlekseyTs** [comment]
The code from the repo:
```
﻿using System;

namespace OverloadResolutionRepro
{
    public class Foo
    {
        public void Method<S>(params Func<Bar, S>[] projections) => throw new NotImplementedException();
        public void Method<S>(params Func<Bar, Wrapper<S>>[] projections) => throw new NotImplementedException();
    }

    public class Bar
    {
        public Wrapper<int> WrappedValue { get; set; } = new Wrapper<int>();
    }

    public struct Wrapper<TValue>
    {
    }

    public class EntryPoint
    {
        static void Main()
        {
            new Foo().Method(x => x.WrappedValue);
        }
    }
}
```

**Comment by danielcweber** [comment]
The error code is CS0121 (if you came here by searching issues for this code) and apparently the bug made it's way into SDK 8.0.300.
