### ISSUE TITLE
`CS1591` fires for protected members on sealed types

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn#73348]
**Version Used**: 
.NET SDK 8.0.300

**Steps to Reproduce**:

```csharp
/// <summary>
/// Base class.
/// </summary>
public abstract class Base
{
    /// <summary>
    /// Gets the value.
    /// </summary>
    protected abstract string Value { get; }
}

/// <summary>
/// Derived class.
/// </summary>
public sealed class Derived : Base
{
    protected override string Value => throw new NotImplementedException();
}
```

**Diagnostic Id**:

[`CS1591: Missing XML comment for publicly visible type or member Derived.Value`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)

**Expected Behavior**:

No warning

**Actual Behavior**:

Warning

**Additional Context**:

The above repro, where we are overriding a method, is the real-world scenario I am hitting.

However, the pathological case of non-virtual protected members in sealed types also returns the diagnostic, though this is bad code:

```csharp
/// <summary>
/// Derived class.
/// </summary>
public sealed class Derived
{
    protected string Value => throw new NotImplementedException();
}
```

**Comment by CyrusNajmabadi** [comment]
Could you clarify why this is wrong?  As the member is publicly visible, it needs xml docs.  This is irrespective if the container is sealed or not.

**Comment by RenderMichael** [comment]
A protected member on a sealed type is functionally private, there's a [whole analyzer](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0628) for that.

**Comment by CyrusNajmabadi** [comment]
That's for a 'new' protected member.  This isn't 'new'. It's an override of a normal protected member.  I would expect this to have docs.   The visibility from the language's perspective is def not 'private here'.

**Comment by RenderMichael** [comment]
This also applies to new protected members, code sample in the Additional Context.

Can you explain why you'd put XML docs on a protected member of a sealed type? You can't use `Derived.Value` anywhere outside `Derived` anyway (at least not typed to `Derived` as opposed to `Base.Value`, which would be the only way to see the XML docs we'd be putting on `Derived.Value`).

**Comment by CyrusNajmabadi** [comment]
Are there doc tools that filter these out?  My understanding was that protected override members in sealed types are kept in doc systems.

**Comment by RenderMichael** [comment]
Not that I'm aware of, though those docs wouldn't be accessible through any public surface. It may be more effort than it's worth filtering those docs out, if this analyzer stops requiring docs here then that should be enough.

**Comment by jaredpar** [comment]
This behavior is "By Design". The type being `sealed` is not taken into consideration here. Just don't see this ever meeting the bar for changing.
