### ISSUE TITLE
F1 on type parameter symbols declared in source opens MSDN at completely unrelated pages

### ISSUE THREAD

**Issue by jhinder** [dotnet/roslyn#73388]
**Version Used**: VS 17.9.6

**Steps to Reproduce**:
Place the caret on the `TIn` symbol and press <kbd>F1</kbd>.

```csharp
class C<TIn>;
```

**Expected Behavior**: The help page for generic types (https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/generics) is opened.

**Actual Behavior**: A [completely unrelated help page](https://learn.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/ind-define-the-tin-for-a-company-address?f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(TIn)%3Bk(DevLang-csharp)%26rd%3Dtrue) for a completely different product is opened, probably because it contains the substring "TIN".

This works for many different words/names: [Cat](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2016.drawing.chartdrawing.stringdimensiontype), [House](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.documentintelligence.addressvalue.house), [Ocean](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2019.drawing.ink.inkeffectstype), [World](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol) -- you get the idea.

If you try this on regular type symbols (e.g. class names) you get to the F1 fallback page. https://learn.microsoft.com/de-de/visualstudio/ide/not-in-toc/default

**Comment by CyrusNajmabadi** [comment]
Closing out due to extremely low priority.
