### ISSUE TITLE
Unify the various code fixes related to implementing equality checking correctly

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7338]
Spun off from a comment thread in https://github.com/dotnet/roslyn-analyzers/pull/743.

Presently, we have a collection of fixes that each add a single method: if you have `==`, we add `Equals`; if you have `Equals` we add `GetHashCode`.  The simplest generalization would be to offer both methods at the same time (assuming neither already existed, of course).  However, a more general approach would be to detect that the user is trying to implement equality checking and offer a more comprehensive series of snippets.

For example, as soon as you have either `==` or `!=`, we should probably offer the other operator, `Equals`, `GetHashCode`, and maybe even `IEquatable<T>` (for value types).  We might also want to tie into the existing `Equals`/`GetHashCode` refactoring that generates a reasonable implementation from the fields (and readonly auto-properties) of the type.

One can imagine further extending this to comparisons, but that might be a separate work item.

**Comment by amcasey** [comment]
FYI @CyrusNajmabadi

**Comment by lorcanmooney** [comment]
It would be nice if `IEquatable<T>` had built-in support, like `IDisposable`, where it would generate _all_ the boilerplate code at once.

**Comment by Pilchie** [comment]
@CyrusNajmabadi: Is this done now with the new dialog based picker, or is there more you were thinking of?

**Comment by CyrusNajmabadi** [comment]
I think it's done now.
