### ISSUE TITLE
Public API for partial properties

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#73411]
## Background and Motivation

Test plan: #73090 

We need to introduce public APIs related to the upcoming [partial properties](https://github.com/dotnet/csharplang/issues/6420) feature.

These APIs generally correspond to existing APIs on `IMethodSymbol`, which are used for key IDE features such as go-to-definition and find-all-references. We expect these APIs to be used by the same features for corresponding scenarios relating to properties.

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
     public interface IPropertySymbol
     {
+        /// <summary>If this is the implementation part of a partial property, returns the symbol for the definition part. Otherwise, returns null.</summary>
+        IPropertySymbol? PartialDefinitionPart { get; }

+        /// <summary>If this is the definition part of a partial property, returns the symbol for the implementation part. Otherwise, returns null.</summary>
+        IPropertySymbol? PartialImplementationPart { get; }
     }
```

```cs
partial class C
{
    // Symbol for this declaration of 'Prop' will:
    // - return null for PartialDefinitionPart
    // - return symbol for below 'Prop' declaration for PartialImplementationPart
    public partial int Prop { get; set; }

    // Symbol for this declaration of 'Prop' will:
    // - return symbol for above 'Prop' declaration for PartialDefinitionPart
    // - return null for PartialImplementationPart
    public partial int Prop { get => 1; set { } }
}
```

Notable behaviors:
- These APIs only return values for original definition source symbols. So, for example, a retargeting symbol with a partial property underlying symbol will return null from these APIs.
- If one of the partial declarations required by the language is missing, the APIs will return null. For example, if only the the definition part of a partial property exists, then accessing `PartialImplementationPart` on it will return null.
- The accessors of a partial property are considered partial methods, and their counterparts are returned from the corresponding APIs on `IMethodSymbol`. For example, if we had the definition part symbol for `C.Prop.get`, and we accessed `PartialImplementationPart` on it, we would get the implementation part symbol for `C.Prop.get`. Also, `IMethodSymbol.IsPartialDefinition` will return `true` for the definition part symbol for `C.Prop.get`.

## Usage Examples

The following is based on the existing helper [ParameterSymbolReferenceFinder.CascadeBetweenPartialMethodParameters](https://github.com/dotnet/roslyn/blob/abca483b0385f07560d60889a9e72aff24498973/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs#L241):
```cs
namespace Microsoft.CodeAnalysis.FindSymbols.Finders;

internal class ParameterSymbolReferenceFinder
{
    private static void CascadeBetweenPartialPropertyParameters(
        IParameterSymbol parameter,
        ArrayBuilder<ISymbol> results)
    {
        // When we find-all-refs to a partial indexer parameter, for example, also include references to the corresponding parameter within the other partial declaration.
        if (parameter.ContainingSymbol is IPropertySymbol property)
        {
            var ordinal = parameter.Ordinal;
            if (ordinal < property.PartialDefinitionPart?.Parameters.Length)
                results.Add(property.PartialDefinitionPart.Parameters[ordinal]);

            if (ordinal < property.PartialImplementationPart?.Parameters.Length)
                results.Add(property.PartialImplementationPart.Parameters[ordinal]);
        }
    }
}
```

## Alternative Designs

- Also include `public bool IPropertySymbol.IsPartialDefinition { get; }` for uniformity with existing `IMethodSymbol.IsPartialDefinition`.

The reason this API is not included in the main proposal because partial properties are required to have an implementation part. [IMethodSymbol.IsPartialDefinition](https://github.com/dotnet/roslyn/issues/51082) was introduced to address EnC scenarios around partial methods lacking an implementation part. But perhaps no such scenario exists for partial properties, since a compilation error occurs when the property lacks an implementation part.

- Don't ship any new APIs and have users dig through the accessor symbols to locate the other property part instead. This seems cumbersome.

## Risks

N/A

**Comment by 333fred** [comment]
- `IsPartialDefinition`
    - What about error scenarios where only the definition exists?
    - This will be particularly common for SG scenarios

**Conclusion**: Approved, with the addition of `IsPartialDefinition`.

**Comment by RikkiGibson** [comment]
API implementation has been merged
