### ISSUE TITLE
Error CS0121 with overloads of params and generic parameters

### ISSUE THREAD

**Issue by ericstj** [dotnet/roslyn#73422]
**Version Used**: 
```
.NET SDK:
 Version:           9.0.100-preview.3.24204.13
 Commit:            81f61d8290
 Workload version:  9.0.100-manifests.e6dcff2c
 MSBuild version:   17.11.0-preview-24178-16+7ca3c98fa
```

**Steps to Reproduce**:

1.   Create two params overloads for a method with a generic parameter as shown below.
2.   In older versions of the compiler, it would choose the better overload as can be seen here: https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQeAzAASHUDC1A3udW7TXgCzUCyAFAEpmrdmIBuEAE7VJKagF5qMAKYB3agGUAPLAQA+IQG5RYtgLmCTZMQF9T1B1Vo9e2gCqGADtIhgAztTuANoAutTSAObCTPY27M7cfB7evgFaKWERUtHMcXHkzv4IUgCuAMYIGZ7kLGTktkA===
3. In the latest version it complains they are ambiguous which forces the caller to allocate the array themselves.

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.
```C#
using System;
public class C {
    public void M() {
        var val = new S<int>();
        M(val);
    }
    
    public void M<T>(params T[] arg) {}
    public void M<T>(params S<T>[] arg) {}
}

public struct S<T> { }
```

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic if possible (e.g. `"IDE0030"`).

**Expected Behavior**:
Compiles successfully

**Actual Behavior**:
```
error CS0121: The call is ambiguous between the following methods or properties: 'C.M<T>(params T[])' and 'C.M<T>(params S<T>[])'
```

**Comment by cston** [comment]
This looks to be a duplicate of https://github.com/dotnet/roslyn/issues/73346.

cc @AlekseyTs to confirm.

**Comment by ericstj** [comment]
Yeah looks like it.  Is there a compiler package I could try out to confirm the fix?

**Comment by ericstj** [comment]
I tested this out with https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.Net.Compilers.Toolset/overview/4.11.0-2.24260.1 and confirmed that it's fixed.
