### ISSUE TITLE
[Test Failure] CSharpWinForms.xml failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7344]
PR: [#434](https://github.com/dotnet/roslyn-internal/pull/434) *Disable SplitFile, CrossLanguage and CSharpGoToImplementation* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p3/79/

**1 Test Failures:**
CSharpWinForms.Change control property in code

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpWinForms.xml

**Comment by davkean** [comment]
This was disabled in https://github.com/dotnet/roslyn-internal/pull/434

**Comment by DustinCampbell** [comment]
Should be fixed with https://github.com/dotnet/roslyn-internal/pull/455
