### ISSUE TITLE
Rename class property changes all occurrences of property name in all comments in project.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73453]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-class-property-changes-all-occurr/10656858)._

---
I'm running into an issue with the renaming feature in my Visual Studio installation (17.9.6) where rather than just renaming the property, all comments containing the word (relevant to the class or not) are found and updated with the new word. A bit confusing I know but please read on for more details.

Explaining the problem:

The first problem is that when I try to rename a property the dialog box doesn't show the 'Include comments' or 'Include strings' options as it did before. I thought this wouldnt be an issue since those are not enabled by default anyways or at least shouldn't be.

However, you can see in this screenshot, my rename of this class property is leading to 82 references in 50 files.
I found that the discrepency between the 5 references to the property and the 82 that VS found is due to 77 instances of the word 'Value' in comments scattered throughout the project I'm working on.

![B26a9547fc1f94d9a804b2cb320718d2a638509196964410693_20240510-163454-image](https://github.com/dotnet/roslyn/assets/1408396/68827765-b368-46f9-8597-beea6128e530)

To give more context, the examples where the word in a comment is being 'renamed' are almost never relevant to the class/ property itself, e.g. 

![Ba1af19cfa80749d8ab0a371cf1241b40638509200439211767_20240510-164042-image](https://github.com/dotnet/roslyn/assets/1408396/9e590723-a21f-4da3-aca3-4561d1aa5813)

 To verify that I wasn't going crazy, I tested this with a new property that has zero references called 'test'. As you can see once again it is picking up all instances of the word 'test' in the comments of the project.

![B58807dd03d724dbdaa479d4211798efe638509198719801386_20240510-163750-image](https://github.com/dotnet/roslyn/assets/1408396/4403c689-8d8c-4795-bb7d-ddec89fa870a)

Thanks for reading and in advance for any help!

---
#### Feedback Bot on 5/10/2024, 03:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment]
This issue is caused by two problems:

1. The expander icon is not being rendered here:

    ![image](https://github.com/dotnet/roslyn/assets/1408396/15d9e559-3f50-417b-a84c-81d061502aa5)

2. The expander is currently collapsed, which is hiding the "Include comments" option

The user should be able to work around this issue by clicking the blank space to expand the options, and the unchecking the option to include comments.

**Comment by cheajer** [comment]
Thank you @sharwell !
