### ISSUE TITLE
Intellisense References not showing correctly when using a Primary-Constructor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73469]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-References-not-showing-corr/10657891)._

---
[severity:It bothers me. A fix would be nice]
When Using a Primary-Constructor the Intellisense-Reference-Counter does not count/show the reference.

Picture 1 shows the Reference of the empty Constructor Edge as Zero ("0 Verweise" is german for "0 References"). Here the calling class is using a primary Constructor:

![B3efbeff3d19649c1bb2e8a6e0bb362a9638511952769773689_20240513-130756-grafik](https://github.com/dotnet/roslyn/assets/1408396/f859acd1-fe90-4fc1-98e5-23e67e3d546f)

Picture 2 shows the Reference of the empty Constructor Edge as 1. Here the calling Class is using a regular Constructor:

![Bb11baced31ff457e93491a09e26662b7638511954391707913_20240513-131038-grafik](https://github.com/dotnet/roslyn/assets/1408396/a1b65e9f-5b07-4dd6-b9be-ef7308c196ef)

---
#### Feedback Bot on 5/14/2024, 04:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dibarbet** [comment]
(Triage) Confirmed that modifying
```
public class Edge
{
    public Edge() { }
}
public class Edge<T> : Edge
{
    public Edge(string s) : base() { }
}
```
to
```
public class Edge
{
    public Edge() { }
}
public class Edge<T>(string s) : Edge()
{
}
```

results in both codelens and an explicit FAR no longer showing a reference for the base constructor.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/76097.
