### ISSUE TITLE
IInvocationExpression doesnt deal with __arglist well

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7346]
it looks like support for __arglist is missing from IInvocationExpression.
Console.WriteLine("...", 1, 2, 3, 4, __arglist(5, 6, 7));

**Comment by leppie** [comment]
Wow! Never knew this worked :) :+1:

**Comment by srivatsn** [comment]
__arglist is so rarely used that it's not a high priority to support it.

**Comment by leppie** [comment]
Looking at the IL produced, this is very interesting. Seems no boxing occurs on IL level for values in `__arglist`.

**Comment by heejaechang** [comment]
@srivatsn I am not sure how much support is worth, but it should at least have some mention about it if it is used in invocation. or not throw exception. which is what happens now.
