### ISSUE TITLE
CSharpReplIntellisense test is disabled in VS but refers to an issue that is closed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7347]
See: Closed\Hosting\Test\Execution\TestLocator.cs

```
yield return "CSharpReplIntellisense.xml"; // https://github.com/dotnet/roslyn/issues/4245
```

It refers to https://github.com/dotnet/roslyn/issues/4245

**Comment by ManishJayaswal** [comment]
@KevinH-MS Do we just need to enable the test now or are there other issues with the test?
