### ISSUE TITLE
Colorization flickers when scrolling through a file

### ISSUE THREAD

**Issue by akhera99** [dotnet/roslyn#73496]
**Version Used**: 
![image](https://github.com/dotnet/roslyn/assets/40616383/b26c5588-a39d-4cfc-bb3e-070e7c2e233e)

**Steps to Reproduce**:
Just scrolling through a file.

Short repro video:

https://github.com/dotnet/roslyn/assets/40616383/c6bedd0e-9f43-4f6e-bf66-ff707af603c3

**Comment by Peter-Juhasz** [comment]
It still happens:

https://github.com/user-attachments/assets/e104cfaa-e36d-489f-af0d-e47be480279d

(until a change is made)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/75796
