### ISSUE TITLE
Inline rename controls show Rename Overload check box too often

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#735]
Ported from TFS WorkItem: **991465**

------------------------------

@slaks reported:*<br><br>The check box certainly should not appear when renaming fields, variables, parameters, or namespaces.<br><br>Ideally, it should not appear unless the the ctor or method is actually overloaded.

------------------------------

**Revisions:**

1) Created By Visual Studio Languages Snap Account (7/21/2014 1:21:27 PM)

------------------------------

**Comment by SLaks** [comment]
> Please go to http://roslyn.codeplex.com/workitem/160 to modify this bug

Is that true?

**Comment by SLaks** [comment]
And, `tour` should be `ctor` (oops)

**Comment by dpoeschl** [comment]
@SLaks Updated the description, thanks. This is actually already fixed. We check for [actual overloads](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/AbstractEditorInlineRenameService.SymbolRenameInfo.cs,58) and pass that through to the [UI](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/Dashboard/Dashboard.xaml,183).

Thanks for reporting this!

**Comment by dpoeschl** [comment]
Behavior verified on fields, variables, parameters, namespaces, and both non-overloaded and overloaded methods.
