### ISSUE TITLE
All analyzers from assembly Microsoft.CodeAnalysis.CodeStyle.Fixes failed to load: Unable to load one or more of the requested types. Method not found: 'Boolean Microsoft.CodeAnalysis.IParameterSymbol.get_IsParamsArray()'.

### ISSUE THREAD

**Issue by bertenbobje** [dotnet/roslyn#73508]
**Version Used**: 
.NET SDK `8.0.300`
**Steps to Reproduce**:

1. Have a .NET 8 project open
2. Check the Roslyn Analyzer logs
3. See that no projects were able to load due to the error below

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**: `All analyzers from assembly Microsoft.CodeAnalysis.CodeStyle.Fixes failed to load: Unable to load one or more of the requested types. Method not found: 'Boolean Microsoft.CodeAnalysis.IParameterSymbol.get_IsParamsArray()'.`

If this is a report about a bug in an analyzer, please include the diagnostic ID and message if possible (e.g. `"IDE0030: Use coalesce expression"`).

**Expected Behavior**:
Roslyn loading for the projects.

**Actual Behavior**:
Roslyn not loading for projects.

**Comment by VahidN** [comment]
Yes, I have lots of similar error messages with .NET SDK 8.0.**300**
```
Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryLambdaExpression.CSharpRemoveUnnecessaryLambdaExpressionDiagnosticAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'Microsoft.CodeAnalysis.SeparatedSyntaxList' from assembly 'Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'.
System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.SeparatedSyntaxList' from assembly 'Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryLambdaExpression.CSharpRemoveUnnecessaryLambdaExpressionDiagnosticAnalyzer.GetParameters(AnonymousFunctionExpressionSyntax expression)
   at Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryLambdaExpression.CSharpRemoveUnnecessaryLambdaExpressionDiagnosticAnalyzer.AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol expressionType, INamedTypeSymbol conditionalAttributeType)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1185
-----
Suppress the following diagnostics to disable this analyzer: IDE0200
```

**Comment by roemba** [comment]
Can confirm this problem still persists with SDK version `8.0.301`

**Comment by solo12zw74** [comment]
Got that in JetBrains Rider IDE, whereas the Visual Studio 2022 works well. And that actually starts after Visual Studio update. I suppose it updates .NET SDK "by the way".

**Comment by solo12zw74** [comment]
What helps me as workaround:
1. Manually install .NET 8.0.206 with `winget install --id Microsoft.DotNet.Sdk.8 --version 8.0.206`
2. Create a global.json file in repo root with the following:
```json
{
  "sdk": {
    "version": "8.0.206",
    "allowPrerelease": false
  }
}
```
