### ISSUE TITLE
Record structs with InlineArray attribute compares only by the first value.

### ISSUE THREAD

**Issue by Ilchert** [dotnet/roslyn#73504]
Related to the dotnet/runtime/issues/96943.

**Version Used**: 
dotnet SDK 8.0.204

**Steps to Reproduce**:
1. Create `record struct` with `InlineArray` attribute
2. Call equals.
3. Record structs with `InlineArray` attribute compares only by the first value.
```C#
var a1 = new A();
a1[0]=1;
a1[1]=2;

var a2 = new A();
a2[0] = 1;
a2[1] = 1;


Console.WriteLine(a1.Equals(a2));

[InlineArray(2)]
record struct A
{
   public int P;
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGYrPAAi1IDoAldBKMAUzoGEB7MABygAbNsgDKIgG5QAxmwDOAbmLEJEZFQikqAXiow2AdyoBBABQBKJUU0BtPAF1tpK7dKOcVlWo04dewyYWLjh29n7OxBAhbuGeRBSkAJymmnQAogCOqBCCcik45pbKRDYAkjCCsGzGyMgQAJ6mBfbEyGzS3MgAJlRyCGjSCCbEAN7EVBNYAMxUsEMAClYAvkA)

**Expected Behavior**:
Should compare all values in inline array and print false in this case.

**Actual Behavior**:
Compares only the first element.

**Comment by jaredpar** [comment]
This combination of features (`record` and `InlineArray`) is not particularly useful. @AlekseyTs did we consider making this combination an error at declaration? Can't see any good reasons to allow this.

**Comment by AlekseyTs** [comment]
> did we consider making this combination an error at declaration? Can't see any good reasons to allow this.

This is an oversight, there was no intent to support record-like behavior for inline arrays.

**Comment by lambdageek** [comment]
Related runtime issue https://github.com/dotnet/runtime/issues/96943 where we're considering changes to the default behavior of `ValueType.Equals` for inline arrays

**Comment by 333fred** [comment]
Discussed in LDM on the [17th](https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-06-17.md#inline-arrays-as-record-structs).

**Comment by AlekseyTs** [comment]
From https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-06-17.md#conclusion-3:

> Applying `InlineArrayAttribute` to a record struct will be an error.

**Comment by AaronRobinsonMSFT** [comment]
The runtime is changing the behavior of the default `Equals()` and `GetHashCode()` to throw whenever a type is marked with `InlineArrayAttribute`.

See https://github.com/dotnet/runtime/pull/103612.
