### ISSUE TITLE
[Test Failure] No identified problem in prtest/win/dbg/eta on PR #7315#issuecomment-162725722

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7350]
PR: [#7315#issuecomment-162725722](https://github.com/dotnet/roslyn/pull/7315#issuecomment-162725722) *Merge update 1 branch to master* by @jasonmalinowski
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2356/

**Issue 1: No identified problem**
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

Tao Crash.  We should add a regex for this case

**Comment by davkean** [comment]
We added one last night - http://dotnet-ci.cloudapp.net/failure-cause-management/2b141ea7-c5f1-44f7-8d3d-083faa06d3cd/.

@dpoeschl
