### ISSUE TITLE
VB IInvocationExpression.ArgumentsInSourceOrder has implicit params arguments already converted to object array

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7353]
basically in VB, it is not possible to distinguish whether a user wrote

string.Format("...", new object[] {1,2,3,}) vs string.Format("...", 1, 2, 3, ...)

only using IOperation. author has to examine syntax tree to figure that out. also this behavior is different than C#.

**Comment by srivatsn** [comment]
The fact that you have look into syntax is okay because functionally they are the same. However, we should be consistent between C# and VB. Tagging @JohnHamby for his opinion.

**Comment by heejaechang** [comment]
@srivatsn I think considering what API says what it does, current VB behavior seems incorrect regardless whether there is a way to get around the issue or not. and @JohnHamby already know about the issue.

**Comment by JohnHamby** [comment]
The VB compiler is erasing the distinction by collecting ParamArray arguments in the bound tree. I'm not sure we can tell these cases apart without enhancing the VB compiler. The API doc comments have been updated to reflect the actual behavior.

**Comment by jinujoseph** [comment]
@genlu , is this addressed ?

**Comment by genlu** [comment]
This is fixed.
