### ISSUE TITLE
"Add await" should be upgraded to a codefix in presence of CS4014

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#73576]
Currently roslyn provides "Add await" refactoring for cases like this:
```cs
async Task<int> GetNumberAsync()
{
    var x = GetNumberAsync()[||];
    return 0;
}
```
However the same refactoring is provided in cases when compiler raises `CS4014` warning about not awaiting a task-returing method inside another async method:
```cs
async void M()
{
    [|DoSomethingAsync()|]; // CS4014 here
}

Task DoSomethingAsync() => Task.CompletedTask;
```
Problems here are:
- The fix for the diagnostic is not on top of the action list:
![devenv_MdHTywR3BD](https://github.com/dotnet/roslyn/assets/70431552/4a688518-005b-43b7-b287-abaa0112eb72)
- There is no fix-all. And even if we can add fix-all to refactorings, I want to fix only warning cases, not every place where `await` can be added

Therefore I think "Add await" should be split into refatoring and a codefix part - it should appear as a codefix with propper fix-all support for cases of `CS4014` and just a refactoring in other valid places

**Comment by CyrusNajmabadi** [comment]
Closing out as marginal.  The user simply needs to press down once.
