### ISSUE TITLE
Consider having constructors automatically inherit documentation from the containing type

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#73579]
## Background and Motivation

AB#2063157
https://developercommunity.visualstudio.com/t/Documentation-Comments-in-F-library-not/10661462

```cs
/// <summary>
/// Represents a list item.
/// </summary>
class ListItem
{
}

class Usage
{
  void Method()
  {
    var listItem = new ListItem();
    //             ^^^ ^^^^^^^^^
  }
}
```

In this example, there is no documentation presented when covering over the tokens marked with `^`. This occurs because the constructor for `ListItem` does not have any documentation comments, even though the containing type does.

## Proposed Solution

Treat constructors with missing documentation comments as automatically inheriting documentation from their containing type.

## Risks

Could lead to duplication of complicated type documentation across every constructor for that type during documentation generation.

**Comment by th3oth3rjak3** [comment]
For additional context for troubleshooters, the original implementation in F# looks like below.

```F#
/// <summary>
/// Represents a list item.
/// </summary>
type ListItem = {
    /// The unique ID of the item.
    Id: int
    /// The name of the item.
    Name: string
    /// True when the item is completed, otherwise false.
    IsComplete: bool
}
```

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  IF you want this, please provide a milestone and an appropriate PR.
