### ISSUE TITLE
Intellisense hover for suggestions, missing assembly references not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73584]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-hover-for-suggestions-miss/10648638)._

---
When I hover on an item, the intellisense suggestions no longer appears. For example, if there’s a missing reference, previously you can just hover on the item with the error, then a suggestion would appear under the error details. On the attached sample, it should’ve added a suggestion below to add “System.ComponentModel” reference.

This also happens to project assembly references.

This started on VS 2022 preview 4.

![Image](https://github.com/dotnet/roslyn/assets/788783/0d4bc783-6cf8-4559-a3c2-94a8906c3cb3)

---
#### Feedback Bot on 4/28/2024, 09:54 PM: 

(private comment, text removed)
#### pepanesit on 5/5/2024, 09:26 PM: 

(private comment, text removed)
#### pepanesit on 5/8/2024, 05:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by genlu** [comment]
I couldn't repro this issue. Will revisit if a repro instruction is provided.

**Comment by jjfellers** [comment]
I am having this exact same issue after the latest update. I cannot find a solution and is killing me. Can we reopen this issue?
