### ISSUE TITLE
Generate Constructor Quick Action doesn't work on Primary Constructors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73581]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Generate-Constructor-Quick-Action-doesn/10658756)._

---
[severity:It bothers me. A fix would be nice]
The quick action "Generate Constructor" on a class or record with a primary constructor, does not generate a normal constructor.

Currently after hitting the refactor button it does nothing.

In addition, having a way to get from primary constructors back to a normal constructor would be nice to have since there is a way to get from a regular constructor to primary constructors.

---
#### Feedback Bot on 5/15/2024, 00:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me:

![image](https://github.com/dotnet/roslyn/assets/4564579/c03f5079-9800-4e7f-85cd-1a4e0b95abda)

> In addition, having a way to get from primary constructors back to a normal constructor

This also exists:

![image](https://github.com/dotnet/roslyn/assets/4564579/9b269807-357b-4a88-82fc-c7fda40c4e57)
