### ISSUE TITLE
Serializable exception proposed by visual studio in dotnet 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73583]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Serializable-exception-proposed-by-visua/10651981)._

---
[severity:It bothers me. A fix would be nice]
When I throw a custom exception like throw new NotFoundException(), visual studio V17.9.6 (community 64bit) and do an Quick action, it's propose to generate a new class. Untill now still okey, but in the class with a dotnet 8 class library it still propose/ puts a [Serializable] attribute (which is obsolete/ deprecated and also an protected method with (SerializationInfo info, StreamingContext context) : base(info, context). You get the warning SYSLIB0051, but it should not generated at all for a DOTNET 8 project.

---
#### Feedback Bot on 5/6/2024, 03:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by DoctorKrolic** [comment]
Obsolete constructor generation was fixed in https://github.com/dotnet/roslyn/pull/72671

**Comment by CyrusNajmabadi** [comment]
Thanks!
