### ISSUE TITLE
Overlapped icons in inheritance margin

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#73615]
![image](https://github.com/dotnet/roslyn/assets/4564579/7b1843f7-fc6a-49ff-a6d7-d5f4323fb60c)

**Comment by Cosifne** [comment]
https://github.com/dotnet/roslyn/pull/73996 Should fix the problem
But if anyone see this stil repro (might be caused by different reason) feel free to reopen.
