### ISSUE TITLE
IDE0290 code fix is invalid in `ref struct`

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn#73614]
**Version Used**: '4.11.0-1.24229.8 (28985c0a)'. Language version: 12.0

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTAnApgMwAIBnAF2wFcBjUwgZQjAAcAbXTAb00J8KeygA3CKVyEASrggATAPIwWATzpMIMADxUAFhGwA+QgH0y2ANyZuvBAGZ6jVrgAUkmfKUq1mnfpLkAlJY8XBi8oUYmhAC8vmaBhAC+FiFWtggALIQAsgD2grgAcrgAHqSOAclBcaHC2CSqMFHh5OYVCZiJGEA

````c#
ref struct Sample
{
    private ReadOnlySpan<char> _str;

    public Sample(ReadOnlySpan<char> str)
    {
        _str = str;
    }

    public void MoveNext()
    {
        var span = _str;
    }
}
````

Use the fix to convert to primary constructor and remove field

````c#
ref struct Sample(ReadOnlySpan<char> str)
{
    public void MoveNext()
    {
        // ❌ CS9110 Cannot use primary constructor parameter 'str' that has ref-like type inside an instance member
        var span = str;
    }
}
````

**Diagnostic Id**: IDE0290 Use primary Constructor

**Expected Behavior**: The code fix is not suggested

**Actual Behavior**: The code fix is suggested

**Comment by GiovanniBraconi** [comment]
If nobody is working on this issue, I'll happily take a look at it 😃

**Comment by CyrusNajmabadi** [comment]
@GiovanniBraconi Absolutely!
