### ISSUE TITLE
intellisense suggestions constructor collection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73627]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/intellisense-suggestions-constructor-col/10662572)._

---
[severity:It bothers me. A fix would be nice]
IntelliSense suggestions don't work for calling constructor with omitting type (C#9 feature) inside collection expression (C#12 feature)

Example
`new List<string>([new(/* suggestions don't work here */)]);`

---
#### Feedback Bot on 5/21/2024, 04:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
No repro in 17.10:

![image](https://github.com/dotnet/roslyn/assets/4564579/158eeb09-6870-43ef-8869-a804ca310240)
