### ISSUE TITLE
Respond to obsoletion of ILanguageClientMiddleLayer

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#73626]
`ILanguageClientMiddleLayer` has been obsoleted. We need to respond and remove our usage of it before its removed.

**Comment by dibarbet** [comment]
Already addressed here - https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Core/LanguageServer/AbstractInProcLanguageClient.cs#L37C113-L37C158

And tracked by https://github.com/dotnet/roslyn/issues/73317
