### ISSUE TITLE
"IDE0305 Use collection expression for fluent" not raised if `ToArray()` is assigned to a `var` variable

### ISSUE THREAD

**Issue by Piedone** [dotnet/roslyn#73638]
### Analyzer

**Diagnostic ID**: [IDE0305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0305): `Use collection expression for fluent`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.CSharp.CodeStyle](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle)

**Version**: 4.9.2

### Steps To Reproduce

1. Use the following code:

```c#
var list = new List<string>
{
    "one",
    "two",
    "three"
};

var array = list.ToArray();

foreach (var item in array)
{
    Console.WriteLine(item);
}
```
2. Observe that `var array = list.ToArray();` line does NOT violate IDE0305.
3. Try the code modified as follows:

```c#
List<string> list =
[
    "one",
    "two",
    "three",
];

string[] array = list.ToArray();

foreach (string item in array)
{
    Console.WriteLine(item);
}
```
4. Observe that `string[] array = list.ToArray();` does violate IDE0305.

### Expected behavior

Both versions violate IDE0305.

### Actual behavior

Only the non-`var` version violates IDE0305.

## Additional context

Full source available [here](https://github.com/Lombiq/OSOE-855-AnalyzersTest/tree/8302ab0a2802b1a53fbad71665510840019eefdd). The offending code is in the root `Program`.

https://github.com/dotnet/roslyn/issues/73639 might be related.

**Comment by CyrusNajmabadi** [comment]
This is by design. Collection expressions have no natural type, and so cannot be used with var.
