### ISSUE TITLE
Outlining Failing for Sub with Optional Parameter

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73640]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Outlining-Failing-for-Sub-with-Optional-/10663862)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.9]
When I add an optional parameter to a Sub, the outlining caret on the left margin disappears.  To see this working properly, see attached Good.png.   Note the caret encircled in red.

![B1844fc0cf45e4e35a0f14f987adec421638519519549933450_Good](https://github.com/dotnet/roslyn/assets/1408396/bf72e87a-c893-4be7-b271-449a044bed73)

I then added an optional parameter to the same sub.  See attached Bad.png that shows the missing caret encircled in red.

![Bfcbd158bc6334e339b5c6139ff4782d8638519519775158311_Bad](https://github.com/dotnet/roslyn/assets/1408396/153f5c64-647b-4495-a079-43b1dc20d50b)

---
#### Feedback Bot on 5/22/2024, 03:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cosifne** [comment]
Fixed in 
https://github.com/dotnet/roslyn/pull/74413
