### ISSUE TITLE
C# needs a feature to "Show all called methods" for any given method implementation.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73669]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-needs-a-feature-to-Show-all-called-m/10654987)._

---
For C#, the "Call Hierarchy" window will list all the "Calls To" for a selected Method, but does not show any of the "Calls From" that method.  The "Calls To" display is redundant, as it duplicates the functionality of "Find all References"; what is missing is the ability to get a list of all the methods called by a given method - even if its just the method names, and any object-type information known for the instance or static type the method belongs to.  

I'm sure this must have been suggested before, but I have not yet been able to find any existing issue for this topic.

---
#### Feedback Bot on 5/8/2024, 00:20 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is call hierarchy.  Which already exists.
