### ISSUE TITLE
Delay updating the problem window contents

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73665]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Delay-updating-the-problem-window-conten/10657487)._

---
Using VS 2022 with C#. When I modify a C# file, it takes about 3 seconds for the problem window to get updated (for example to show that a syntax error has been introduced or fixed). I tried with even the simplest project, a basic Hello World console program. I even have it set to only analyze the current file rather than the whole solution. It seems like there’s an intentional delay being introduced from the point when the user stops typing until the error analysis kicks in. Would there be a way to change or disable that delay?  
In VSCode, the problem window updates instantaneously.  
Thanks in advance for any suggestion!

---
#### Feedback Bot on 5/12/2024, 07:37 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
@kayle?  You guys control the cadence here now.  In the past, we kept things at about 1.5s as a reasonable delay where things didn't feel too spammy, while also showing up in a reasonable amount of time.

**Comment by CyrusNajmabadi** [comment]
Inner issue was reactivated and moved to editor.  Closing this out.
