### ISSUE TITLE
"Quick Actions and Refactorings" should include suggesting changing the existing declaration to "public" as a proposed fix for error CS0737

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73664]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Quick-Actions-and-Refactorings-should-/10658170)._

---
error CS0737 is "XXX does not implement interface member YYY(); YYY() cannot implement an interface because it is not public.

A common fix for this is to simply change the method declaration to be public.  The "Quick Actions and Refactorings" could include this as one of its suggested fixes.  Currently it only suggests adding new method implementations.

Another suggestion it could offer might be to add explicit interface implementations that then use the available non-public methods.

---
#### Feedback Bot on 5/14/2024, 02:38 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Generally, we've avoided fixes that really only add a single keyword to something.  Just changing it by typing something like `pu<tab>` is going to be faster.
