### ISSUE TITLE
"Remove and Sort Usings" doesn't take care of compiler directive 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73662]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Remove-and-Sort-Usings-doesnt-take-ca/10639550)._

---
The "Remove and Sort Usings" option doesn't take care of compiler directive and removes unnecessary using statements.

If a using is required for a call which is inside Release section and we use "Remove and Sort Usings" option from Debug mode it removed using statement(s) which are required for Release mode.

e.g. 
using LibA;
using LibB;

#if DEBUG
    LibA.Call(); 
#else
    LibB.Call(); 
#endif

The "Remove and Sort Usings" option should not remove LibB

---
#### Feedback Bot on 4/17/2024, 02:34 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
This is by design.  If a using is only for a particular configuration, it can be placed in an `#if XXX` block so that it will not be removed.  This has been how this feature has worked since VS2005 and is very intentional in its behavior.
