### ISSUE TITLE
Automatic line wrapping, taking into account the specified formatting and language syntax.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73671]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-line-wrapping-taking-into-acc/10651227)._

---
I would like the word wrap function to take into account the specified formatting settings and language syntax:

*   new line indent according to formatting;
*   omitting space characters and similar ones when moving to the next line;
*   wrap a parameter from several words as a whole, and not in parts;
*   wrap a parameter with type string as a whole, and not just a part, if the total length of the parameter string does not exceed the available string length.  
 

![Image](https://github.com/dotnet/roslyn/assets/788783/b3e1b6fe-ae55-4483-862e-117ffd63b291)

---
#### Feedback Bot on 5/2/2024, 06:09 PM: 

(private comment, text removed)

**Comment by genlu** [comment]
Honestly, I don't really see what benefit this would provide, given that this only has very minimal affect on how the text is displayed. THoguhts? @dotnet/roslyn-ide

**Comment by sharwell** [comment]
This is a feature request for the editor's word wrap feature.
