### ISSUE TITLE
Run code clean up -- Can you remove redundant blank lines like CShapier?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73672]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Run-code-clean-up----Can-you-remove-redu/10648824)._

---
Run code clean up -- Can you remove redundant blank lines like CShapier?
I think we can achive this simple task, let`s  see it in the next upgragde version of vs. Thanks!

---
#### Feedback Bot on 4/30/2024, 00:09 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Yes.  This is controlled by this option:

![image](https://github.com/dotnet/roslyn/assets/4564579/015f334b-d074-4a00-80c8-38a0deb10f1a)
