### ISSUE TITLE
Move more logic from the Controller.Session down to the SignatureHelpService

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#73678]
The EditorFeature Controller.Session for SignatureHelp handles additional scenarios like filtering providers based on trigger character. This logic could also be used by the LSP Handler once we are deserializing the proper SignatureHelpTriggerInfo from [SignatureHelpParams.Context](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Protocol/SignatureHelpParams.cs).

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If this needs to happen, reactive with a milestone for it to be done in.
