### ISSUE TITLE
Shorthand Switch Case Guards 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73670]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Shorthand-Switch-Case-Guards-/10654104)._

---
I would like to suggest an addition to the case guards in the short hand switch statement.

example:

```
var test = "thisisatest";
var check = test switch {
  "this" => "something",
  "atest" => "somethingelse".
  _ => "nothingelse"
}
```
The above will always return the default in variable test.

I think it would be great if this was possible:

```
var test = "thisisatest";
var check = test switch {
  "this" when StartsWith(StringComparison.OrdinalIgnoreCase) => "something",
  "aTest" when Contains(StringComparison.OrdinalIgnoreCase) => "somethingelse".
  _ => "nothingelse"
 }
```

So if test startswith "this" check will be "something".
if test contains "aTest" check will be somethingelse.

This of course for all the other ones (EndsWith, Equals) too and with the other StringComparisons as well.

---
#### Feedback Bot on 5/7/2024, 07:38 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out.  This is a language request change.  Those need to start as discussions over at dotnet/csharplang.
