### ISSUE TITLE
A potential bug in custom string interpolation constructor resolving for `ref` parameters

### ISSUE THREAD

**Issue by PaulusParssinen** [dotnet/roslyn#73690]
**Version Used**: VS Version 17.10.0 Preview 7.0 - reproduces against main branch (see SharpLab)

![image](https://github.com/dotnet/roslyn/assets/26825431/1066bc6d-6d32-4570-9783-75202a824a5c)

As discussed on the C# discord, here's the minimal repro (a left out implementation details, the issue is the binding of the interpolation ctor)

A minimal repro: [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwPQYAQBkoDGApjAM5EAm2CA9tQBZHYB0AcgKIAq2AYjQK4wKEBFBoxsgikQBO2cUxpywSphADmMokTAkEpZgFgAUFmydGLDtz5SRYiSkIlypBlDcAzVE1rYAngKSQrIMTACyAJLcTsRkREbGJgACAEwAjCkADNjJ6cwASoKiuswAwjRgAA4+MgDKsgBuzqQA3Nm5+QAiUBowNKSiBAYV0gCCMBAo/qQe7cbJOXnMnEQAHgjzJo0QcqTA2AC82DBEAO7YAKoIngAcdQgysOoAQvyo0jIAFIMQBADWUxQNAI2GA/gQRAA2ulUrcALoASi2phwZTq6QAbKksiBsGMZOp+LoYAhsABmbBgfiDMFMKoQUjkKhnKAIejYADkWk8nOw/yI/jOSgoJjM6Nu5IArLiqRB/Nh1lUBkwdk8IMAUEQ3DzZCRiFRwdgGTIILpIXJOeyPHyBPooNIxTgaJ4wlA5NICChdvZxNhSAQaFUiE7sBLpak8WUIDB+mSaUx9nSCBAE9g2XKFUqVdhdVoYAbsGreprtaG7bNpPJXeyiO7sJ7vabRH6A0GQ8Z9swxlVg0IAPqRMgIGPEL4AEgARGMZ2MAN7k8lZdIAX0nyJMoYsHmwwpk/wMJi7Pb7FH77A2LgcE8nLzvLzn6Syi7XG6SxhPJAo4SI7JoFDqQNgy+Hl/WAN8UnSABOH5gBWGhrjuB4nhgdQJgoHpSGVcgvkRCCFixXIABZ8V7L8fz/ACgKIECiFdRD7keZ43g+UJ9kREw5xMbAzEAZMJeKOMMMWxWUCSJEkyUpalaWAelGWZXc2Q5bk6L5AUhRFbjsG048yIHIdfgLGip1nedF2XV8UW07SzG3Nw9wPRJrLA7s9LPC9ITIa8p3vB8nxfdd5hXTcFkpUDBhkfgCDJBjkOY94UE+L46gZGAAB5wUhAA+dMYDZXoUDeTxPFkDjjC44xnNgC1JhQYjSNPfALSmL4oQqYcYwQC9g2iyh4U6HIdhQfgiDK5y5x4gAqeQwDZSEqE8JQwS0ZoEAVSacGC99nOSSlkhIz8hCHYtOrSzgsq+bghpGuBsAKIgIAoAB5GBphSmM0oIehdhyxaZEgMljmkTxUxQBAxuc6yzkYLRzGwPFIli1K+H+kQR1LLTtImjBpsqObKGwP7lqIVb1s2kLnPFGNdyYSABXcNwaEaWRgUe7AACsaTJBz/UqIh6BoM4AH5MdyPaDrcwcOqMr5RecqEhwtZVvXmuLUIACRjCgtRkMTiT0L5J3XeE5es0DYqY1DmEV2RlZESg1fUTWhB17Bvpd0rRYqyHrOtNxjnd7XZGYftgASz55mcrbRd2q4bkYlD1HMBD48d9DMOwmjESOHKcZm/GFqW4AVrZMmGzo0HNhMaPQs6TFclSOO7g8q9xFIVJONFsxImwFMJDppgMx51l2UJmgUGBVlUP9fxSQgNYY72wj9oar9z0vLzxFlyqfYZ3M6KbhP4tYuQw5PuBTe0hXSVt8f7YAy2na1nW9Ykr5Jl0F0vjPxLSsRE2d4+3NqnR+1sb4yDtqrR+zsg5yEDjrCGWNL5gnDqEAOz9g6h1QTISO1kto11jloR64hpj+keFFGKIDE7fwhNCfqUgWb+GeASU0/gyre2srHJmsgnhVjyDkTgNBHa4RztgdgBZ/zPGYJcTgPBbjMAAOK/mEQwmQ0xmEyFYfheWNsIF3ygYnGBOsAE7TCgfCKFDsC6MgQ7aBGCZBe2QdVWQtVD6OxYr/OQWCT5WV3rHax+jbGGPsdvXekNqrYCcM1FAuASDqHZBfQBYTcpkj+gDeaFRiiJOSdZNswYqDAKQo/DxnwUEn0QZDDhOTvGeMEj/COyCa5hNjhbROydWnMKEBnFUIjDg5RqZ8eCHTULpw8JnXCvifZ5wAFJc15roKkv4BYUDcH4b6zMwgpNvirBwvdKg1C1NgDayDY4r0OhQJqsgWptTbiOUk3UiC9QoP1fhRYpgjWzn07AAzg7nMuaaFAXxrqjUmZDU5EtTwo3SZQM6F0rrvNGruGGTBuAIyRjGKFaMNSHK+T8mQrlTzHV2L0UkQKEVvmaeLVeQhMUIHmrCy6bzhpEFuq8tJIhs7Qz1HDNFqdkZKHSdipguL6m/LckS9UpLgW3XZeDXB2l8FAA)

**Diagnostic Ids**:  ``CS1620``, ``CS8350``, ``CS8352``

**Expected Behavior**:  The instance method binds the interpolated handler constructor similarly to the extension method.

**Actual Behavior**:  Various ref safety diagnostics emitted for the instance variant.

Not critical but it'd be also _nice to have_ same lowering for the instance versions as the extension varitant (while testing various different combinations of ref keywords, I saw a lot of local tmps , while this static extension has none)

**Comment by 333fred** [comment]
So, I'm thinking this is not bug (or at least, not an implementation bug. It may be a specification bug.) The [constructor resolution](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/improved-interpolated-strings.md#constructor-resolution) section of the interpolated string handler specification says this (emphasis added):

> * Otherwise, the type of every resolved `px` is added to the argument list, in the order specified by the `Arguments` array. **Each `px` is passed with the same `ref` semantics as is specified in `M1`.**

Where `px` is the parameter of the resolved constructor, and `M1` is the method being called (`Append_Instance` or `Append_Extension` in this case). The `ref` semantics of the receiver of an instance method isn't well-specified as far as I can tell; however, I'm somewhat unconvinced it should be allowed to be treated as ref implicitly, given that we may or may not emit `dup`s for some structs. Should this code compile if the builder was a `readonly` parameter, for example? To make forward progress on this, I think a full rules change for C# would need to be proposed, specifying when a receiver would be allowed to be passed by ref to the constructor of an interpolated string handler; those rules could then be verified and reviewed, and we would have a full spec to test the implementation against. That would need to be opened on csharplang, and I would likely be willing to champion such a feature, but the proposal would need to come from someone else.
