### ISSUE TITLE
[Test Failure] BasicExpressionEvaluator failing

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7371]
PR: [#435](https://github.com/dotnet/roslyn-internal/pull/435) *[don't review] Root out flaky VSI tests* by @davkean
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/73/

**1 Test Failures:**
BasicExpressionEvaluator.Evaluate simple expressions (DTEE)

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

BasicExpressionEvaluator.xml

**Comment by davkean** [comment]
Disabled in: https://github.com/dotnet/roslyn-internal/pull/436

**Comment by amcasey** [comment]
```
Expected: myInt = (Integer.MaxValue)
 Expression has been evaluated and has no value
 Actual: myInt = (Integer.MaxValue)
```

**Comment by amcasey** [comment]
First three screenshots show no output for evaluation.  Final screenshot shows it.  Perf issue?

**Comment by amcasey** [comment]
@KevinH-MS You or me? :)

**Comment by davkean** [comment]
These machines are pegged at 100%, so assume that all things that expect a certain result to occur in a specific time are wrong.

**Comment by davkean** [comment]
Talking offline if we want to stop overlapping jobs on these machines.

**Comment by amcasey** [comment]
On my box, the locals window isn't working at all.  Investigating.

**Comment by amcasey** [comment]
Interesting, the failure is actually in the DTEE scenario.

**Comment by amcasey** [comment]
@davkean I stand corrected.  `ImmediateWindowAction` is full of two-second timeouts.

**Comment by davkean** [comment]
:(

**Comment by amcasey** [comment]
Also, rebuilding fixed the locals window.

**Comment by amcasey** [comment]
If you don't specify a timeout on waiting for focus, it waits a minute.  That seems acceptable.

If you don't specify a timeout on waiting for text to appear, it checks immediately.  This fails every time.

**Comment by davkean** [comment]
Instead of waiting, are there some sort of events/tasks that you can listen to that tell you when it's done?

**Comment by amcasey** [comment]
@davkean How would I determine that?

**Comment by davkean** [comment]
I don't know the area, so I can't tell you. Anything that is says "wait this amount of time" is destined for failure on the Jenkins machines.

**Comment by amcasey** [comment]
I've determined that a) no dedicated code marker exists (by code review) and b) no existing code marker serves as a proxy (empirically).

I'll change the timeout to two minutes since the test has been passably successful with a timeout of two seconds.

**Comment by amcasey** [comment]
There are presently no `Flaky` issues referring to this test.
