### ISSUE TITLE
ExternalCodeFunction.FullName includes typename from return type instead of containing type

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7372]
I had some code like:
```C#
        private static void AppendElements(StringBuilder sb, CodeElements codeElements)
        {
            foreach (CodeElement ce in codeElements)
            {
                if (ce.Kind == vsCMElement.vsCMElementFunction)
                {
                    var cf = (CodeFunction2)ce;
                    AppendMethod(sb, cf);

                    if (cf.OverrideKind == vsCMOverrideKind.vsCMOverrideKindAbstract ||
                        cf.OverrideKind == vsCMOverrideKind.vsCMOverrideKindOverride)
                    {
                        var parent = cf.Type.CodeType.Members.Item(cf.Name);
                        AppendMethod(sb, (CodeFunction2)parent);
                    }
                }

                AppendElements(sb, ce.Children);
            }
        }

        private static void AppendMethod(StringBuilder sb, CodeFunction cf)
        {
            var parameters = new List<CodeParameter>();
            foreach (CodeParameter p in cf.Parameters)
            {
                parameters.Add(p);
            }

            sb.AppendLine($"{cf.FullName} has parameters: {string.Join(", ", parameters.Select(p => p.Name))}");
        }
```

And the `cf.FullName` and it returned a string like:

```
ConsoleApplication1.Program.Main has parameters: args
ConsoleApplication1.Program.Equals has parameters: obj
System.Boolean.Equals has parameters: obj
```

**Comment by DustinCampbell** [comment]
Could you clarify what you expect? This looks correct to me.

It looks like you started with a class like so:

```C#
namespace ConsoleApplication1
{
    class Program
    {
        void Main(string[] args)
        {
        }
    
        override bool Equals(object obj) { return base.Equals(obj); }
    }
}
```

Is that right? If so, here's how I see your code operating against it:

1. Iterate members of Program.
2. Dump "Main" -- "ConsoleApplication1.Program.Main has parameters: args"
3. Main is not abstract or override so it moves onto the next element.
4. Dump "Equals" -- "ConsoleApplication1.Program.Equals has parameters: obj"
5. Equals is an override
5a. Find grab the "Equals" method from its return type (that's the `cf.Type.CodeType.Members.Item(cf.Name)` bit)
5b. Dump "Equals" from the return type -- "System.Boolean.Equals has parameters: obj"

Unless I'm missing something, I don't think there's a bug here.

**Comment by Pilchie** [comment]
Oh, great. The mistake was in my head. I was thinking that `cf.Type` was the type containing it, not its return type, so I was thinking the end result should be `object.Equals`. Of course that should be `cf.Parent`.

**Comment by DustinCampbell** [comment]
Just verified that this is working correctly.
