### ISSUE TITLE
ArraySegment<T> s = []; leads to wrong initialization

### ISSUE THREAD

**Issue by wiz0u** [dotnet/roslyn#73738]
### Description

`ArraySegment<T> s = []; `
currently generates
`ArraySegment<T> s = default(ArraySegment<T>);`
which initialize the segment with the following values
(array: null, offset: 0, count: 0)

This leads `s.ToArray()` to throw because "underlying array is null"

I think 
`ArraySegment<T> s = []; `
should instead generate
`ArraySegment<T> s = ArraySegment<T>.Empty;`
so that underlying array is an empty array.

This behavior would match the existing behavior of Array:
`T[] s = [];`
correctly generates
`T[] s = Array<T>.Empty;`

### Reproduction Steps

compile sample code like:
```
ArraySegment<int> s = [];
s.ToArray();
```
and see exception, and what's generated in ILSpy

### Expected behavior

should not throw if segment is correctly initialized, and produce an empty array

### Actual behavior

throws System.InvalidOperationException: 'The underlying array is null.'

### Configuration

tested on VS 2022 17.9.6, LangVersion latest

**Comment by alrz** [comment]
Could an static `Empty` member be looked up on the target-type instead? This wouldn't be considered an optional optimization anymore (as it is right now in a sense that compiler is free to use a optimal codegen for select selected set of well-known types) but I think it's better than the wrong codegen? The type has to conform to collection shape anyway so it wouldn't light up for arbitrary types.

**Comment by CyrusNajmabadi** [comment]
> Could an static Empty member be looked up on the target-type instead? 

Yes.  But that would still take a language change to specify that sort of behavior :)

**Comment by CyrusNajmabadi** [comment]
We should keep this issue here, in terms of seeing if we can get the compiler to add a warning. 

On top fo that, i'd recommend opening a new *discussion* at dotnet/csharplang about this topic.  It can certainly link to this issue, but it should basically be a discussion on what the best way is for ArraySegment to play well in the collection-expression space.

**Comment by wiz0u** [comment]
I'm not very familiar with dotnet/csharplang discussion system. I would prefer if someone more familiar could open that issue there and link back to this issue.

**Comment by CyrusNajmabadi** [comment]
Sure.  I can do that for you.

**Comment by jnm2** [comment]
For those who found this thread first and are looking for that discussion: https://github.com/dotnet/csharplang/discussions/8164

**Comment by jaredpar** [comment]
> Until then, we could have the compiler warn about this.

That would be a breaking change at this point. If we went this route it would be as part of a warning wave. 

I'd still push back that a list on the basis of why is this more special than any other type that has bad default behavior?
