### ISSUE TITLE
Having two embedded resources dependent on the same file causes CS1508 error

### ISSUE THREAD

**Issue by HughPH** [dotnet/roslyn#73735]
**Version Used**: 8.0.204

**Steps to Reproduce**:

1. Create a new Class Library Project
2. Create two text files, text1.txt, text2.txt
3. Make the two files dependent on Class1.cs
4. Make the two files Embedded Resources
5. Try to build - you will get `0>CSC: Error CS1508 : Resource identifier 'TestProject.Class1' has already been used in this assembly`

**Expected Behavior**: No conflicts between embedded resources with different names.

**Actual Behavior**: Resources take on the name of the file they're dependent on, instead of their own names. Solvable by giving each Embedded Resource its own LoglcalName, but that shouldn't be necessary. The default behaviour is confusing at best - I didn't add _any_ resources named "TestProject.Class1"

**Comment by jaredpar** [comment]
Can you post a complete sample that demonstrates this problem?

**Comment by jaredpar** [comment]
Closing due to lack of response.
