### ISSUE TITLE
"Use collection expression" code fix drops comments in certain cases

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/roslyn#73740]
**Version Used**: `Compiler version: 4.10.0-3.24230.3` (abc35d6d)

**Steps to Reproduce**:

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgPrALgbQLprQAgpgvJmAUwHdMkN1UBYAKAG9bMmCSyYVLMB6LsAT0wBjAPZgwhdo2YMazOS1LlUmOpgCMAJgDMAGkwAWAKwA2TAF8pTMzssK2HLD35DR49pg22Z85kUXssVQB2AA4ATj01AAY1c1sLGjMAbiA)
```csharp
int[][][] a = new int[][][]
{
    new int[][] //my comment
    {
        new int[] { 123, 456 }
    },
    new int[][] //my comment 2
    {
        new int[] { 789, 101 }
    }
};
```

**Diagnostic Id**: IDE0300

**Expected Behavior**:
Comments are preserved.

**Actual Behavior**:
Comments are lost when fix is applied.

For the above case its trivial to replace the comments, however for large lookups the comments can help add a lot of context and its very tedious to manually perform changes to manually preserve the comments.

**Comment by CyrusNajmabadi** [comment]
Thanks for the report @JakeYallop .  If you're interested, we'd gladly take a PR if you wanted to contribute to it :)
