### ISSUE TITLE
Regression: static initializer not run on class (worked with the old .NET Framework compiler)

### ISSUE THREAD

**Issue by epsitec** [dotnet/roslyn#73759]
**Version Used**: all .NET Core compilers from .NET Core 3.1 onward to latest shipped with Visual Studio Preview 17.10.0 (C# Tools 4.10.0)

**Steps to Reproduce**:

Run [this minimum sample on sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUASEML1QGYACDSzAdjwG898N0nGD8A3AQzHIDMA9oPIBeclACmAd3IAxYeQAUASgDcTZpgCcy1LQB0UCAFsARpLDryAehvlJADwAOkgMbAAllADm5TAAMMOQ+ksBevuQB5N4AzsCS3HBMAL545Bnk6Zn6AGwxUMASphZgGrhMVAqCbJpk8sKq5PTkaRx2eQ2CTfRthJ0A8sAAFpbkgiNj4lKyQ6NgquX4bdkZVHOWq81bmZQUGwsqzdQ0RiVT/gFqrVttKUA)

Calling `new Foo()` should initialize static member `Foo.other`, but it does not. Uncommenting the static constructor of `Foo` makes the code work as expected.

```cs
public class Program
{
    static int number;
    public static void Main()
    {
        var foo = new Foo();
        System.Console.WriteLine(Program.number); // expecting 10, getting 0 instead
    }
    class Foo
    {
        public Foo() { }
        //static Foo() {}
        static Other other = new Other();
    }
    class Other
    {
        public Other() { Program.number = 10; }
    }
}
```

**Expected Behavior**:

Should call constructor of `Other` and print out `10`.
This is what happens on the plain old .NET Framework, see equivalent [:NET Fiddle](https://dotnetfiddle.net/yhmKCz).

**Actual Behavior**:

Does not call constructor of `Other` and prints out `0`.

**Comment by epsitec** [comment]
There are only two differences in the **IL** generated for the version with `static Foo()` and the one without:

__Without explicit cctor__
> .class nested private auto ansi beforefieldinit Foo
__With explicit cctor__
> .class nested private auto ansi Foo

and in the `.cctor ()` function itself, there is an additional `nop` with the explicit static constructor.

**Comment by huoyaoyuan** [comment]
See https://stackoverflow.com/questions/610818/what-does-beforefieldinit-flag-do

Note that the execution time of static constructor is not strictly defined. It only guarantees to execute before it's determined necessary. The `beforefieldinit` flag is considered an optimization to delay the check and execution.

Quoting ECMA-335, §I.8.9.5:

> [*Note*: __BeforeFieldInit__ behavior is intended for initialization code with no interesting side-effects, where exact timing does not matter. Also, under **BeforeFieldInit** semantics, type 
initializers are allowed to be executed *at or before* first access to any static field of that type, at 
the discretion of the CLI. 
> If a language wishes to provide more rigid behavior—e.g., type initialization automatically 
triggers execution of base class’s initializers, in a top-to-bottom order—then it can do so by 
either: 
> - defining hidden static fields and code in each class constructor that touches the hidden static 
field of its base class and/or interfaces it implements, or

---

Touching static members of *other type* from static constructor is already a dangerous zone. Consider following code:

```csharp
static class A
{
    public static int V1 = 5;
    public static int V3 = B.V2 + 1;
}

static class B
{
    public static int V2 = A.V1 + 1;
}
```

The result of `A.V3` will be changed by the **order of V1 and V3**.

**Comment by epsitec** [comment]
Thank you @huoyaoyuan for your clarification. So this seems to be an _intended_ behavior when `beforefieldinit` flag is present. Am I guaranteed that by providing a static constructor, the type initializers will be executed before the instance constructor runs?

**Comment by epsitec** [comment]
This is not a regression, but an optimization. Good to know.
