### ISSUE TITLE
Reporting Roslyn analyzer name is inaccessible through Error list entry in VSSDK for VisualStudio 2022 17.10

### ISSUE THREAD

**Issue by georgii-borovinskikh-sonarsource** [dotnet/roslyn#73763]
**Version Used**: the one shipped with VisualStudio 2022 17.10

**Steps to Reproduce**:

1. Install VS 2022 17.10
2. Get an entry for the issue/diagnostic raised by a roslyn analyzer from `SVsErrorList` or via `ITableControlEventProcessor`
3. call `ITableEntriesSnapshot.TryGetValue(..., StandardTableKeyNames.BuildTool, ...)`

Don't have a minimal repro, but here's a link to our repository https://github.com/SonarSource/sonarlint-visualstudio/blob/03de2352653ead779eaad954cf0339c133cf14d4/src/Infrastructure.VS/ErrorListHelper.cs#L133

**Expected Behavior**: Prior to 17.10, we used to get a non-null value for our C# & VB.NET analyzers (`"SonarAnalyzer.CSharp"` & `"SonarAnalyzer.VisualBasic"` respectively). We use this to add custom actions in our vs extension for issues raised by our analyzers.

**Actual Behavior**:  `null` is returned

I previously [posted](https://developercommunity.visualstudio.com/t/VSSDK-ITableEntriesSnapshotTryGetValue/10662583) about this issue on the VS feedback forum, but got no response. A colleague suggested to ask for help here. Apologies if this is not the right channel.

**Comment by genlu** [comment]
Is this because switching to pulled diagnostic? @olegtk @sharwell @CyrusNajmabadi

**Comment by olegtk** [comment]
StandardTableKeyNames.BuildTool is mapped to Diagnostic.Source property in pull diagnostic protocol and seems like Roslyn doesn't set it: https://github.com/dotnet/roslyn/blob/d988414c6709c3f23913b5b5ad5afbaa0d098e31/src/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs#L400

**Comment by genlu** [comment]
@CyrusNajmabadi @dibarbet it seems like we used to set this property in legacy diagnostic? Do you know where is the code that does that?

**Comment by genlu** [comment]
ok, this was how it was done in 17.9
https://github.com/dotnet/roslyn/blob/release/dev17.9/src/Features/Core/Portable/Diagnostics/AnalyzerUpdateArgsId.cs

**Comment by dibarbet** [comment]
@CyrusNajmabadi  We don't have direct access to the `DiagnosticAnalyzer` in devenv right?  Since it is likely running OOP.

We might need to feed this into `DiagnosticData` so LSP can access it.

**Comment by CyrusNajmabadi** [comment]
We don't own the error list anymore. So this would need to be a feature request to the platform. 

That said, it's unclear to me why this is needed. Why not just use the error code?  That should be in the list and unique to your analyzers.

**Comment by georgii-borovinskikh-sonarsource** [comment]
@CyrusNajmabadi I mainly raised this issue because it was a completely unexpected change of behavior in one of the Preview version of VS, with the hope of fixing this before it makes it into the stable release.  

For our purposes we can't use the error code as our C# and VB.NET analyzers don't add the language information there (it's just `S123` regardless of the language, but the rule descriptions are language-specific). 

We have found a workaround (we used the HelpLink for [this](https://github.com/SonarSource/sonarlint-visualstudio/commit/082a5b5353261b37eb2d7ba4e9c76f7ffc7ffae8#diff-8d7bb05424776afabb7d9eefbc6224bdf3b18132619b51ea877cadc7afc413b1R152)) and we'll ship it in our next release, but it could have broken some other VS Extensions that relied on this property, but you have more data than me to judge if it's the case.

**Comment by CyrusNajmabadi** [comment]
> For our purposes we can't use the error code as our C# and VB.NET analyzers don't add the language information there (it's just S123 regardless of the language), but the rule descriptions are language-specific.

Wouldn't yo ube able to tell this from the project/doc information?

> with the hope of fixing this before it makes it into the stable release.

This is unlikely to happen.  Sorry :(

>  but the change in VS could have broken some other VS Extensions that relied on this property, 

Possibly.  However, with the ownership transfer, not all features made the cut.  The wins heere were substantial (50k reduction in maintained code, and a large amount of simplification).  So we accepted that it was a perfect drop-in, but had enough value to go through. 

Closing out as it sounds like you've got a workaround.  Thanks!
