### ISSUE TITLE
Programación 

### ISSUE THREAD

**Issue by Feryyy123** [dotnet/roslyn#73767]
### Type of issue

Code doesn't work

### Description

Pida un número entero entre 10 y 20, dicho número representará la cantidad de veces que se tira un dado. En cada tirada pregunte el valor que muestre el dado. Si el número del dado es impar, súmelo a un acumulador y si es par réstelo a dicho número del dado es impar, súmelo a un acumulador y si es par réstelo a dicho acumulador.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isourcegenerator?view=roslyn-dotnet-4.7.0

### Content source URL

https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/ISourceGenerator.xml

**Comment by jasonmalinowski** [comment]
It seems you filed this as a content bug relating to that specific documentation, but I'm unsure what your concern with that is. I think you might be looking for something else?
