### ISSUE TITLE
Visual Studio 2022 adds a duplicate "Option Strict On" to Code File When Pasting VB.NET Code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73771]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-adds-a-duplicate-Opt/10666755)._

---
Visual Studio 2022 17.10 adds a duplicate "Option Strict On" to the top of a VB.NET class file when "Option Strict On" is the **_ONLY_** statement and the user pastes code into the class, causing a compile-time error.  Steps to reproduce:

•	Open a class that has “Option Strict On” as the ONLY statement at the top of the class
•	Copy and paste a function into the class.
•	Visual Studio 2022 adds “Option Strict On” statement on the first line of the class, causing a compile time error, as there are now two (2) "Option Strict On" statements.

ScreenShot1.jpg shows the class file BEFORE I pasted a new function into the class.  

ScreenShot2.jpg shows the class file AFTER I pasted a new function into the class.  Visual Studio 2022 adds another "Option Strict On" at line #1 of the code file, causing a compile-time error.

---
#### Feedback Bot on 5/26/2024, 08:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jasonmalinowski** [comment]
I'm unable to reproduce; asked customer for more info.
