### ISSUE TITLE
Account for partial properties at existing use sites of partial method symbol APIs

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#73772]
Test plan: #73090

Issue referenced in source

## IDE

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Analyzers/CSharp/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs#L234-L240

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Features/Core/Portable/Completion/Providers/AbstractPartialMethodCompletionProvider.cs#L93-L96

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Workspaces/CSharp/Portable/Rename/CSharpRenameRewriterLanguageService.cs#L827-L833

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Workspaces/Core/Portable/Rename/ConflictEngine/DeclarationConflictHelpers.cs#L58-L66

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/OrdinaryMethodReferenceFinder.cs#L37-L42

https://github.com/dotnet/roslyn/blob/f242061ebdb94b2544a297a2666e14ce81ab9c7c/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ParameterSymbolReferenceFinder.cs#L244-L253

**Comment by RikkiGibson** [comment]
I just reviewed this list, I think all the comments listed in the issue are still present in source.

**Comment by Cosifne** [comment]
I am working on the IDE part. Most of them need some changes.

**Comment by RikkiGibson** [comment]
Removed entries which were resolved by #73792

**Comment by tmat** [comment]
Working on EnC support.

**Comment by RikkiGibson** [comment]
I tried to work through the remaining IDE layer bits in #74950, but I was struggling to understand what to do in some cases. @Cosifne do you think you could pick those up, or maybe we could chat offline about how to work through them.
