### ISSUE TITLE
 Version conflict detected for Microsoft.CodeAnalysis.Common Microsoft.CodeAnalysis.CSharp

### ISSUE THREAD

**Issue by gurux-kurumi** [dotnet/roslyn#73782]
Hi,

It's impossible to add Rosly to the Blazor project because of version conflict. Steps to repeat:

1. Create a new Blazor Web App. Select Individual Accounts as the authentication type.
2. Update all Nuget components to the latest versions.
3. Try to install Microsoft.CodeAnalysis.CSharp nuget package and it fails for version conflict.

+++++++++++++++++++++++++++
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.9.2 directly to project BlazorApp8 to resolve this issue. 
 BlazorApp8 -> BlazorApp8.Client -> Microsoft.CodeAnalysis.CSharp 4.9.2 -> Microsoft.CodeAnalysis.Common (= 4.9.2) 
 BlazorApp8 -> Microsoft.EntityFrameworkCore.Tools 8.0.6 -> Microsoft.EntityFrameworkCore.Design 8.0.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).	BlazorApp8

**Comment by jasonmalinowski** [comment]
Indeed adding the reference should help there as @davidwengier has described. If anything maybe a bug can be filed on NuGet to better handle this, but that would be filed against https://github.com/NuGet/Home.
