### ISSUE TITLE
Method defining line move when adding code before method declaration

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Method-defining-line-move-when-adding-co/10667187)._

---
[severity:It bothers me. A fix would be nice]
Check the triangle method, typing texts before it move the vertical line and its codelens thing.....
Though if I type slow and wait a moment before moving out of the method it will move back eventually, but should I type quickly (for example the word static) it will move that line and makes things feels odd

![image](https://github.com/dotnet/roslyn/assets/4564579/45e34ca7-d636-46bc-acbe-d106b364c444)

---
#### Feedback Bot on 5/26/2024, 07:09 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 5/27/2024, 01:56 AM: 

(private comment, text removed)
#### Perndoe Paradox on 5/27/2024, 08:46 AM: 

(private comment, text removed)
#### Feedback Bot on 5/28/2024, 02:16 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 5/28/2024, 02:18 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
We could try making structure-tags have SpanTrackingMode.EdgeInclusive or EdgeNegative behavior here.  Then, insertions at the start should keep the structure at the start.

**Comment by CyrusNajmabadi** [comment]
Closing out as not planned due to lack of broad feedback.  Typing random code before the modifier isn't something we need to spend resources on.

**Comment by Trisibo** [comment]
(I'm not the original reporter of the issue)

Would you consider reopening this issue? It's not a big deal, but it's a bit annoying, and it's not just about typing random code before the modifier, but also when typing valid modifiers like `static`, `protected`, etc. at the start of the line, or changing the return type, and in some situations the structure guides (and I guess the CodeLens stuff) stay in the wrong position indefinitely until some unknown kind of edit is made or the file is reopened.

**Comment by CyrusNajmabadi** [comment]
Reactivating.  The outlining region should not get stuck.  that indicates something going wrong with differential tagging updates.

**Comment by Trisibo** [comment]
Something similar happens with this code:

```
internal static class Program
{
    static void Main()
    {
        var thing = new MyClass("asdf",
            123)
        {
        };
    }

    class MyClass
    {
        public MyClass(string text, int number)
        {
        }
    }
}
```

The structure lines appear at the level of `new` on line 5 (it may not when writing, but it does when pasting the `thing` creation code, or when reopening the file):

![Image](https://github.com/user-attachments/assets/398c24ee-8639-4066-8c92-a436338b30b9)

It doesn't happen when removing the object initializer block (lines 7 and 8) or moving the constructor call arguments to the same line. Adding code to the initializer block doesn't fix it. I don't know how to avoid the issue in this case without changing the code, as restarting Visual Studio or changing and reverting the code doesn't seem to work.

Is this a related issue, or should I create a new report for it?

**Comment by CyrusNajmabadi** [comment]
The roslyn fix has gone in to ensure the structure guide doesn't get stuck in the wrong place: https://github.com/dotnet/roslyn/pull/76194

@olegtk how would you like to track the issue whre it shouldn't move in the first place if the user is typing up against it (it should start-negative semantics, not start-positive semantics.

**Comment by olegtk** [comment]
Thanks, @C@CyrusNajmabadi 
Let's just move the original ticket to the editor area path.

**Comment by CyrusNajmabadi** [comment]
Ok.  Closing this out.  Will move the internal issue.
