### ISSUE TITLE
Filesystem pollution in `/tmp/`

### ISSUE THREAD

**Issue by lonix1** [dotnet/roslyn#73795]
I didn't know which repo to use; I hope this is the right one.

I'm using VSCode on linux, where the `/tmp/` directory is for ephemeral stuff; I assume it's the same for mac. Nonetheless, it is customary for programmes to place files in there in an orderly manner.

.NET however places dozens, sometimes hundreds, of directories in there:
```
e60c456d-f767-4de4-aa80-95caa3e19e5b/
c31c0e23-3700-4692-a0c6-5ff56ea063d8/
cbfffc3d-dd0f-4059-ae96-e882719684fd/
72fa8d52-0773-4be2-9145-bba8604b0ec8/
c2fd93e3-d5f0-48e0-8e56-4e9c74d1f910/
97337a02-5c04-4712-a20a-8bcd718ee3c6/
1449b70c-c6ad-4135-a707-abbc0d461f47/
1e4fdd31-d714-49be-a24b-30b8f84ddeda/
a938dcab-d8a0-425d-b6b3-07f6a7571909/
0fca510e-26b2-46b6-aec1-7b5734d77ce7/
4e57ea5d-ba66-4750-b3de-4f33c9ee69d9/
bd05154b-137e-4b57-89be-7f0e2c45e17d/
93124a82-6861-40e4-b7d7-223d6dc12960/
685d7dde-02a1-443b-8c3a-8ae257fa86f9/
0f410e1f-169a-4f9c-9c3b-ffec86eb280e/
df66c68d-1049-429f-a25e-9db92493589f/
7c7ca279-71d5-4b4c-9b33-cfd9a341fccf/
dddb7114-6331-4443-8fe8-ed7d00a05d98/
a67bb117-97e4-49b6-ba8e-3d2e2e0d314d/
391ad502-3439-4530-992f-6b07c28cb538/
.dotnet/
MSBuildTempa/
NuGetScratcha/
VBCSCompiler/
VS/
vscode-typescript1000/
clr-debug-pipe-b5187e-8d813e1c-in|
clr-debug-pipe-f5a892-f6c70223-out|
clr-debug-pipe-5ddf66-50801f14-in|
clr-debug-pipe-5ee318-a3ebf041-out|
clr-debug-pipe-fa5c84-26a5212d-in|
clr-debug-pipe-6bdf48-7a1a6af5-out|
clr-debug-pipe-f8adc1-0a614cb4-in|
clr-debug-pipe-c9a869-afcad883-out|
clr-debug-pipe-6c7e1a-08eb9d9e-in|
clr-debug-pipe-8fcfba-74fb0027-out|
clr-debug-pipe-dd4d4a-ca3a5fed-in|
clr-debug-pipe-9fe4b3-05c3b713-out|
clr-debug-pipe-52ec9b-f5b59528-in|
clr-debug-pipe-f9730f-4fd7963f-out|
clr-debug-pipe-84cdee-8d3b8002-in|
clr-debug-pipe-19d0d6-927d20d9-out|
clr-debug-pipe-506e87-98e374b3-in|
clr-debug-pipe-30f948-0c5d51c9-out|
clr-debug-pipe-bc3758-1612693a-in|
clr-debug-pipe-b4fe4a-0ad80716-out|
dotnet-diagnostic-f9d9a2-e3e914e3-socket=
dotnet-diagnostic-b6b2dc-a28ff87b-socket=
dotnet-diagnostic-cbb24f-85ec6873-socket=
dotnet-diagnostic-66ac4b-165dda49-socket=
dotnet-diagnostic-8ec12c-31466b49-socket=
dotnet-diagnostic-595545-ee6711b2-socket=
dotnet-diagnostic-319ae6-602a5576-socket=
dotnet-diagnostic-47a525-9e8f2d27-socket=
dotnet-diagnostic-7f15aa-a6958128-socket=
dotnet-diagnostic-78a4c8-1ca2f6c5-socket=
dotnet-diagnostic-1402b7-60e86a1d-socket=
dotnet-diagnostic-a51cc0-0ca962bc-socket=
dotnet-diagnostic-fda3e8-aa45a385-socket=
dotnet-diagnostic-7e3824-76e16196-socket=
dotnet-diagnostic-dc188b-4ff0bd42-socket=
dotnet-diagnostic-6babeb-d4d8be40-socket=
dotnet-diagnostic-7af5a7-4f55732c-socket=
dotnet-diagnostic-b7d7ab-edc5ff20-socket=
dotnet-diagnostic-9ac7f0-6d838f85-socket=
dotnet-diagnostic-01a0cf-20c22909-socket=
MSBuild08cc5=
MSBuildb688c=
MSBuildb1cde=
MSBuild194b5=
MSBuild8a233=
MSBuild56c7b=
MSBuild2331f=
MSBuildae7b2=
MSBuilde916f=
MSBuild05ea0=
MSBuild4019a=
MSBuilde5608=
MSBuildfa0bf=
MSBuild3f1bc=
MSBuild4aa4d=
MSBuild81e97=
MSBuildeb869=
MSBuild3f702=
MSBuilde0700=
MSBuild422fe=
```

*And that's just a small sample*. Of each category there are maybe hundreds of entries.

It's sort of "filesystem pollution", and makes it hard to use `/tmp/`. I've become used to it over the years, but we should probably find a better way. It affects our interaction with all other programmes which use `/tmp/` as well as our own stuff because we also use `/tmp/`.

It would be better to do as other programmes do: create a `/tmp/microsoft/` directory and place everything in there.

(If this is due to multiple .NET tools, please let me know which, so I can copy this issue to those repos too? Thanks.)

**Comment by CyrusNajmabadi** [comment]
VBCSCompiler is likely roslyn.

Could you give some examples of what are in;

1. The directories with Guid names (e.g.e60c456d-f767-4de4-aa80-95caa3e19e5b/)
2. VS/
3. clr-debug-pipe-b5187e-8d813e1c-in
4. dotnet-diagnostic-f9d9a2-e3e914e3-socket=

It will help track down the relevant teams (if not us).

**Comment by CyrusNajmabadi** [comment]
AnalyzerAssemblyLoader is us (roslyn).  It could be the compiler, but it's also possible it's the IDE code. Tagging @jaredpar and @dibarbet .

The rest do seem to be Dotnet/MSbuild.  However, it's possible it's still us wrt to calling into them and not giving them a good /tmp location (i genuinely don't know).  Jared is likely a good starting point here given that vbcscompiler is def us.

**Comment by jaredpar** [comment]
> AnalyzerAssemblyLoader is us (roslyn). It could be the compiler, but it's also possible it's the IDE code. 

This is for Linux correct? If so this is very likely DevKit as the compiler doesn't use `/tmp/` anymore. Our Linux strategy is to do stream based loading vs. shadow copying. The IDE should definitely be using that route as it's a much simpler story. 

@dibarbet sync up with me and I'll help you get this sorted. Should be a very straight forward change.

**Comment by dibarbet** [comment]
Resolving this issue - https://github.com/dotnet/roslyn/pull/73809 removes the cases where we were shadow copying analyzers to /tmp on linux.  This will be in an upcoming prerelease of the C# extension (most likely released next Tuesday).

The others aren't controlled directly by us and mostly look like named pipes as you mention.  For `MSBuildTempa` or `NuGetScratcha` you'll likely need to followup with those teams
