### ISSUE TITLE
Error list goes crazy while doing a refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73800]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-list-goes-crazy-while-doing-a-refa/10662834)._

---
There are 1779 times the same error in the error list:

![image](https://github.com/dotnet/roslyn/assets/4564579/ca3436ed-3dbe-4f40-997c-bd28bcbcb64a)

When you go to the line there is actually not any error

---
#### Feedback Bot on 5/21/2024, 08:10 PM: 

(private comment, text removed)
#### Feedback Bot on 5/27/2024, 01:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by pgroene** [comment]
[10:49 AM] Peter Groenewegen
It reports errors multiple times and when I fix one, it removes only one. It does repro once in a while. In this case it went wild in the duplicated and does not remove them
[10:49 AM] Peter Groenewegen
I think the issue has to do with multiple targets in a project

**Comment by CyrusNajmabadi** [comment]
Closing out as this was rewritten.
