### ISSUE TITLE
Version 17.10.0 Preview 5.0 - Error list not showing all warnings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73801]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Version-17100-Preview-50---Error-list/10646200)._

---
[severity:It's more difficult to complete my work]
In Visual Studio Version 17.10.0 Preview 5, I'm seeing a drastically lower number of warnings in the Error view than I do in Visual Studio Version 17.9.6. It looks like some projects are being excluded from the results, but I'm not seeing an obvious reason for why they are excluded.

I'm not filtering the Error list in any way. I also tried closing VS, deleting the .vs folder, and restarting VS, but it doesn't fix the issue.

The attached screenshot (Screenshot 2024-04-24 090655.png) shows the differences for the same solution file. Our solution contains a mix of VB.NET and C# projects. We also have a combination of .NET Framework 4.8 and .NET Standard 2.0 projects.

---
#### Jason Belaire on 4/24/2024, 03:24 PM: 

(private comment, text removed)
#### Feedback Bot on 4/24/2024, 06:51 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 4/25/2024, 03:56 PM: 

(private comment, text removed)
#### Jason Belaire on 4/26/2024, 09:55 AM: 

(private comment, text removed)
#### Jason Belaire on 4/26/2024, 10:02 AM: 

(private comment, text removed)
#### Feedback Bot on 4/29/2024, 05:28 AM: 

(private comment, text removed)
#### Feedback Bot on 5/31/2024, 06:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Customer mentions:

> After investigating this more thoroughly, this issue appears to be excluding warnings in projects that we haven’t converted to SDK-style project files and are using Microsoft.CodeAnalysis.NetAnalyzers static code analyzers.

> We haven’t been able to convert these projects to the SDK project format because they are ASP.NET Web Forms/MVC projects targeting .NET Framework 4.8. These projects contain the following configuration entry to load our static code analysis rules:

@dibarbet is this fixed by your work to bridge the legacy build errors to the error list?

**Comment by CyrusNajmabadi** [comment]
Closing out as this was rewritten.
