### ISSUE TITLE
VS 17.10.0 preview 4 shows warnings where no Error is.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73802]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-17100-preview-4-shows-warnings-wher/10642779)._

---
[severity:I'm unable to use this version] [regression]
Loading my project (C# LangVersion 10) VS enterprise shows Warnings where no reason is to found.
Clicking on the Warning the Warning disappears and potential other Warnings show up.
The Version 17.10.0 preview 3 did the same with hard Errors - which i have not found in this version anymore.

---
#### Feedback Bot on 4/21/2024, 05:58 PM: 

(private comment, text removed)
#### Kaylee Xu [MSFT] on 4/23/2024, 00:31 AM: 

(private comment, text removed)
#### Peter Johannes on 4/23/2024, 01:06 AM: 

(private comment, text removed)
#### Peter Johannes on 4/24/2024, 06:07 AM: 

(private comment, text removed)
#### Kaylee Xu [MSFT] on 4/24/2024, 02:18 AM: 

(private comment, text removed)
#### Feedback Bot on 4/25/2024, 03:55 PM: 

(private comment, text removed)
#### Feedback Bot on 4/25/2024, 03:55 PM: 

(private comment, text removed)
#### Feedback Bot on 5/31/2024, 06:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Hi.  Could you provide a screenshot of hte issue?  Or a link to a repro where this is happening?
