### ISSUE TITLE
Accessibility issue in document outline window.

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#73810]
I bulid Roslyn main https://github.com/dotnet/roslyn/commit/f1642d72d7faed12f92031e71f3459f003908abe using VS Version 17.11.0 Preview 2.0 [34921.285.main]

This is what shown in the document outline window
![image](https://github.com/dotnet/roslyn/assets/24360909/b1448749-b576-4561-959f-debf3fe6ef85)

**Comment by sharwell** [comment]
I am not able to reproduce this so far.

**Comment by Liv-Goh** [comment]
Encounter the same issue on WinForms Application Form.Designer.cs file using VS Version 17.11.0 Preview 2.0. Need to set VS theme to dark mode to repro this issue.
<img width="490" alt="image" src="https://github.com/dotnet/roslyn/assets/169347065/f4840656-3a6e-4231-944e-e0cb3d104961">

**Comment by sharwell** [comment]
Also filed as AB#2090508 https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2090508

**Comment by sachin-pise** [comment]
Same issue
![VS Document Outline](https://github.com/dotnet/roslyn/assets/163489884/4c5e5a6d-16c5-42f9-820c-17f1434d2fdf)

**Comment by sachin-pise** [comment]
Version 17.11.0 Preview 3.0 - NOT FIXED
