### ISSUE TITLE
Please add support for colorizing c# code that happens to be in raw string literals.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-add-support-for-colorizing-c-cod/10673345)._

---
In C# since the creating of raw string literals it became a must use feature for source generators to use. Both to have fixed raw strings with no interpolation, and both with interpolation. Sometimes combined with StringBuilder's as well to append other raw strings into another raw string to simplify them as well. With being able to have to code inside the raw strings get colorized much like the roslyn test stuffs it would be a great feature to have in the Visual Studio IDE. The IDE would need to be able to pick up on the use of C# like code inside of them however and do the needed highlighting. Also it would help solve issues such as syntax issues where the source generator might emit code that might not be possible to compile because of a mistake in a raw string literal as well so having a visual error in the IDE to tell the user where that problem exists would be insanely helpful for fixing those bugs.

---
### Original Comments
(no comments)

**Comment by genlu** [comment]
You added colorization for C# code with test marker, do we have something available for C# code string in general?
https://github.com/dotnet/roslyn/pull/61197

**Comment by CyrusNajmabadi** [comment]
This is supported.  The StringSyntax constant is `"C#-Test"`
