### ISSUE TITLE
Allow multiple break/continue keywords in a row

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn#73824]
I sometimes want `break break`, or `break continue`, or even `break break continue`, to get out of nested loops. I have to resort to goto in that case.

Am I right in thinking that such a chain can only terminate in a continue (optionally?) Having `break` after `continue` makes no sense, right?

Would feel nicer if the language let me specify a chain of these, and the first one would apply to the nearest loop, then the second one to the second outer loop, and so on. 

It'd be an error if there are more keywords than loops surrounding it. The IDE would highlight the corresponding loop when you place caret on the keyword, just like it does now.

**Comment by Webreaper** [comment]
It would perhaps be useful if you could provide an example of the code you're writing that requires this, and an example of what it would look like if the double-break was implemented in the language.

**Comment by DoctorKrolic** [comment]
I thought of this as well, but given that I don't write nested loops often I didn't bother thinking on details of this. In any case, this is a new C# language feature proposal, so it should start at csharplang repository and go through design process first

**Comment by KirillOsenkov** [comment]
It's not a proposal, it's a sanity check before a proposal

**Comment by CyrusNajmabadi** [comment]
We'd be more likely to do labeled-loops with `continue x;` or `break y;` as a cleaner way to do things here :).
