### ISSUE TITLE
CSharpScript with Single File .NET6 .NET7 .NET8

### ISSUE THREAD

**Issue by DotNetNext** [dotnet/roslyn#73820]
Can not single file release, this BUG has long existed, there has been no solution

**Comment by CyrusNajmabadi** [comment]
What problem are you running into?

**Comment by DotNetNext** [comment]
> What problem are you running into?

https://github.com/dotnet/roslyn/issues/50719

This has not been fixed, and the latest version I use is also faulty and cannot be released as a single file

**Comment by CyrusNajmabadi** [comment]
Closing as a dupe

**Comment by DotNetNext** [comment]
> Closing as a dupe

Why is it Close ?

**Comment by DotNetNext** [comment]
This BUG is a few years old and should be fixed

**Comment by CyrusNajmabadi** [comment]
Because it's a duplicate. You linked to the primary issue tracking the problem.

**Comment by CyrusNajmabadi** [comment]
> This BUG is a few years old and should be fixed

We welcome contributions. :-)

Currently, this issue isn't as important as what we currently have on our plates, so it has need pushed out to a future release.

**Comment by DotNetNext** [comment]
> > This BUG is a few years old and should be fixed
> 
> We welcome contributions. :-)
> 
> Currently, this issue isn't as important as what we currently have on our plates, so it has been pushed out to a future release.

This is obviously a very serious problem that has seriously affected the availability of the library

**Comment by DotNetNext** [comment]
If this can not be packaged, I think it may have to be implemented in a different programming language.

**Comment by CyrusNajmabadi** [comment]
> This is obviously a very serious problem that has seriously affected the availability of the library

As stated above:

We welcome contributions. :-)

Currently, this issue isn't as important as what we currently have on our plates, so it has need pushed out to a future release. 

If you're interested in supplying a fix here, we'd welcome that. Thanks!

**Comment by DotNetNext** [comment]
> > This is obviously a very serious problem that has seriously affected the availability of the library
> 
> As stated above:
> 
> We welcome contributions. :-)
> 
> Currently, this issue isn't as important as what we currently have on our plates, so it has need pushed out to a future release.
> 
> If you're interested in supplying a fix here, we'd welcome that. Thanks!

It's been years. Are you still fixing it? I'm still worried about the future

**Comment by CyrusNajmabadi** [comment]
>  
> 
> > > This is obviously a very serious problem that has seriously affected the availability of the library
> > 
> > As stated above:
> > 
> > We welcome contributions. :-)
> > 
> > Currently, this issue isn't as important as what we currently have on our plates, so it has need pushed out to a future release.
> > 
> > If you're interested in supplying a fix here, we'd welcome that. Thanks!
> 
> It's been years. Are you still fixing it? I'm still worried about the future

As stated above, this is currently a lower priority than our other work.  So that more critical work comes first. 

We do accept contributions though.  So if this is very important to you, we'd accept a well written contribution that solves the issue. 

Thanks!

**Comment by DotNetNext** [comment]
> > > > This is obviously a very serious problem that has seriously affected the availability of the library
> > > 
> > > 
> > > As stated above:
> > > We welcome contributions. :-)
> > > Currently, this issue isn't as important as what we currently have on our plates, so it has need pushed out to a future release.
> > > If you're interested in supplying a fix here, we'd welcome that. Thanks!
> > 
> > 
> > It's been years. Are you still fixing it? I'm still worried about the future
> 
> As stated above, this is currently a lower priority than our other work. So that more critical work comes first.
> 
> We do accept contributions though. So if this is very important to you, we'd accept a well written contribution that solves the issue.
> 
> Thanks!

This problem usually occurs during the early evaluation of a component
Evaluate the feasibility of the components
There's a door, you don't open it
