### ISSUE TITLE
Binary insertion shouldn't insert facades to ExternalAPIs

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#7382]
I see the following files in the directory:

```
System.AppContext.dll
System.Console.dll
System.Diagnostics.StackTrace.dll
System.IO.FileSystem.dll
System.IO.FileSystem.Primitives.dll
```

We should use the ones in ```NetFX\v4.6\ref\Facades``` (I think that's the right set).

**Comment by tmat** [comment]
@terrajobst @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
Disagree - they are per package, putting those facades under 4.6 doesn't even make sense to me.

**Comment by tmat** [comment]
Other teams need to ship the facades in PrivateAssemblies as well. Why would each need to have a copy of the same file in ExternalAPI and then fight for who's gonna deploy it to PrivateAssemblies?

**Comment by davkean** [comment]
What I mean, is that if those facades are in a folder called 4.6 in internalapis then I would not trust them. There's no such AppContext that we shipped for 4.6, those facades come from packages, and hence I would expect them in per package+version folder.

**Comment by davkean** [comment]
Feel free to share them and stop inserting them, but we should be pulling them from System.AppContext package and the System.Console package.

**Comment by jasonmalinowski** [comment]
@tmat, I believe you're done with this (or nearly done with it) with all your recent work?

**Comment by tmat** [comment]
Yes. Done.
