### ISSUE TITLE
Enable argument wrapping code fix for collection expressions

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn#73826]
The current behavior is confusing:
![image](https://github.com/dotnet/roslyn/assets/8040367/9dc63ff9-9c2f-4e49-a0e2-bcc066b2c1a5)

![image](https://github.com/dotnet/roslyn/assets/8040367/68c1ee4f-459e-4cad-a32d-30287795e535)

Expected behavior when the cursor is placed immediately after the `[`:
```cs
List<Foo> items = [
    new Foo(1, 2),
    new Foo(3, 4),
    new Foo(5, 6)];
```

**Comment by CyrusNajmabadi** [comment]
Oh, we do have this:

![image](https://github.com/dotnet/roslyn/assets/4564579/0d30618c-81d7-488c-802e-7d5e3862539f)

So we should see why we're not preferring that, given that the caret is within the collection expr, and not within the argument list.  that's def odd.

**Comment by CyrusNajmabadi** [comment]
Closing out as marginal.
