### ISSUE TITLE
Collection expressions: Suboptimal codegen when concatenating static lists

### ISSUE THREAD

**Issue by rasmushalland** [dotnet/roslyn#73856]
In our application we have a good number of list of well known numeric ids that we type as `enum`s. We declare them as `static readonly IReadOnlyList<enum-type>` fields.

When collection expression became available we switched to expressing many of these lists as collection expressions instead of arrays. While that works nicely and causes the numerical constants to be stored as constant data in the dlls and field initalizion to be performed using `RuntimeHelpers.InitializeArray`, I've observed an inefficiency: Some of these lists use one or more fields as part of their content. In those cases, the IL gets dramatically worse when using collection expressions compared to LINQ `Append` and such.

Example: The codegen for the following code shows the difference in codegen. (sharplab link: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRhQG4BYAKGz3wDoAZASwDsBHUs8jAZhxkYFcAtjgCiOAN7kcUnADd8AGlkAmRTM6qUqgKyqkqgOyqAHKoCc8ydLlZV+BbPwqH6h5oc6Heh4YcmH58gBfcg5uDCUcAGEAZQAHWABDABNxSykuKiQcRKSIRgAbAE8cAEkAJRhkgHkCwoYAZwAXAB5hAD4cBsb8HABeHABtYWo5RWGZJ3GXcbdxj3GvcZ9xowBdNmk8MPwsnLyi0orq2q7Wjq6I/oHqOnom+3G7MZHHZ7lpl9mRj5kUdaCQhQwhFIpE8mAEo1UmRNhkCLtKrlaodETUiqd2p07t0+oNHm9Jt83l8ZPMRosRssRmsNtI4Ttsoj9sVyqiTtizlimpcud1qGDGBDGgAKIYvB4vQnvN6EN4/P4ASmoABUIABBKBQBKFYUKojSIJAA)

```c#
using System.Collections.Generic;
using System.Linq;

public enum E {
    v1, v2, v3, v4, v5, v6, v7, v8, v9,
    v10, v11, v12, v13, v14, v15, v16, v17, v18, v19,
}

public class CSpread {
    public static readonly IReadOnlyList<E> List1 = [E.v1, E.v2, E.v3, E.v4, E.v5, E.v6, E.v7, E.v8];
    public static readonly IReadOnlyList<E> List2 = [..List1, E.v11, E.v12, E.v13, E.v14, E.v3, E.v4];
}

public class CConcat {
    public static readonly IReadOnlyList<E> List1 = [E.v1, E.v2, E.v3, E.v4, E.v5, E.v6, E.v7, E.v8];
    public static readonly IReadOnlyList<E> List2 = List1.Concat([E.v11, E.v12, E.v13, E.v14, E.v3, E.v4]).ToArray();   
}
```

For the collection expression case (`CSpread`) we get the following static initializer, containing quite a bit of IL for the field `List2`:

```c#
static CSpread()
{
    E[] array = new E[8];
    RuntimeHelpers.InitializeArray(array, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
    List1 = new <>z__ReadOnlyArray<E>(array);
    IReadOnlyList<E> list = List1;
    int num = 0;
    E[] array2 = new E[6 + list.Count];
    IEnumerator<E> enumerator = list.GetEnumerator();
    try
    {
        while (enumerator.MoveNext())
        {
            E e = (array2[num] = enumerator.Current);
            num++;
        }
    }
    finally
    {
        if (enumerator != null)
        {
            enumerator.Dispose();
        }
    }
    array2[num] = E.v11;
    num++;
    array2[num] = E.v12;
    num++;
    array2[num] = E.v13;
    num++;
    array2[num] = E.v14;
    num++;
    array2[num] = E.v3;
    num++;
    array2[num] = E.v4;
    num++;
    List2 = new <>z__ReadOnlyArray<E>(array2);
}
```

Whereas with the pre-expression collection code we get a more efficient static initializer:

```c#
static CConcat()
{
    E[] array = new E[8];
    RuntimeHelpers.InitializeArray(array, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
    List1 = new <>z__ReadOnlyArray<E>(array);
    IReadOnlyList<E> list = List1;
    E[] array2 = new E[6];
    RuntimeHelpers.InitializeArray(array2, (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
    List2 = Enumerable.ToArray(Enumerable.Concat(list, new <>z__ReadOnlyArray<E>(array2)));
}
```

This one remains maintains constant code size as the number of elements grows, which the collection expression version does not.

In cases like this I suppose that the compiler has maximal insigt into and control over the generated code and the data, so it seems feasible for it to generate code more like that of the `CConcat` case.

I should mention that this behavior is not a significant problem for us, but beyond the performance cost it does lead to a bit of nagging doubt with regards to the optimizations that the compiler performs for collection expression on compile time known values.

**Comment by CyrusNajmabadi** [comment]
It's unclear to me what's bad or undesirable about the code the compiler emitted.  The destination collection is created with teh right length, and the values are copied directly into it.  

Note that the two forms have very different semantics.  The compiler form produces a read-only-list that cannot be mutated.  While the alternate form produces a mutable array.  The semantics are definitely different.

**Comment by bzd3y** [comment]
@rasmushalland What are you saying is inefficient about this? Just the amount of code?

As far as I can tell, the reason the lengths are different is because your `CConcat` just uses the `Concat` method while the `CSpread` emits IL to accomplish the something similar in terms of concatenating the collections, but statically and as an actual read-only type.

To really compare these the way you are, you'd need to look at the IL for at least `Enumerable.ToArray()` and `Enumerable.Concat` and add that to `CConcat`'s length. Plus, two calls to `RuntimeHelpers.InitializeArray` instead of 1.

I'm pretty sure that would be "longer". For example `Concat()` does two `foreach`/`yield return`s and each of those emits quite a bit of IL.

And as for actual performance, your `CConcat` is going to include some overhead from the method calls, etc. so I'm not sure it is going to be more performant either.

**Comment by rasmushalland** [comment]
My usecase is just to have some hardcoded lists of int/longs/enums for application code to use. Be that as may in readonly memory, an array or a wrapped array. 

Collection expressions in some cases make it possible to initialize such a list very efficiently, by placing the data as readonly data in the assembly and either reference that data directly or memcpy it into an array at class constructor time. Compare that to the way that `CSpread` initializes `List2` in a way that has a IL size proportial to the number of elements.

My observation is simply that having a memcpy cost per element is probably preferable to having an IL and JIT cost per element.

**Comment by CyrusNajmabadi** [comment]
We'd need to see real world cases where this actually mattered.  We don't drive optimizations on speculative concerns.  :-)

**Comment by rasmushalland** [comment]
Fair enough. :)

**Comment by bzd3y** [comment]
I know it has been a while and this is closed, but I think I understand what you were going for more now. But a couple of things, maybe just for academic/educational purposes:

`CSpread` can't work like `CConcat` without there being a dependency on those classes/methods, right? And it would basically be calling them even though you didn't. Maybe that would be okay, but I could also see there being problems with that.

More importantly, I think your point is that the last part of CSpread could just basically do exactly what it did in the first part and assign the values in a loop, just looping through the values known at compile time. How? To do that, they would already have to be in another `IReadOnlyList`. But that is the entire "problem" here, they aren't. That is exactly what the collection initializer is doing for you in the first place.

So I think there's something of a bootstrap problem here, where you want to use the thing you are using to implement the thing you are using.
