### ISSUE TITLE
Visual Studio won't show errors and Error list doesn't switch to code line after doubl click

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73863]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-wont-show-errors-and-Erro/10676127)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.9]

**Environment**
I have a WinForms-.NET-FX 4.8 VB. NET-project in Visual Studio Version 17.10.1 on a 64-bit Win10 PC.

**Problem**
After updating to Version 17.10 (and no manual changes to the VS-settings) there are no error lines anymore:
![NoErrors.png](https://aka.ms/dc/image?name=Bc97d04e6b516465292f37fa8b5691dd6638531665287863059_NoErrors.png&tid=c97d04e6b516465292f37fa8b5691dd6638531665287863059)
The error list window shows an error, but there is no red underline in the code.
If I doubleclick on the entry in the error list window, nothing happens. In earlier versions, the causing code line was selected. After a solution build, the errors are also listed in the output window. If I doubleclick one error there, the LOC is selected correctly.
Even worse: In the error list window there is an error mentioned which is not part of the loaded solution.

---
#### Feedback Bot on 6/5/2024, 00:25 AM: 

(private comment, text removed)
#### Feedback Bot on 6/5/2024, 11:03 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
I can't repro this.  Would need user project to see what's going on.

**Comment by hez2010** [comment]
I guess the author is publishing the project in VS where VS doesn't show the file and line number in output at all.

**Comment by ToddGrun** [comment]
I'm unable to repro too. I tried against a 17.11 Deutsch VS install, VB .Net FX console application, and am able to navigate from the error list and see the squiggles in the editor.

I'm going to go ahead and close. If zodmails from devcommunity can still reproduce this issue, I'd love to get more information to try and track this down.

**Comment by VaporiZed** [comment]
I found the difference in my environment: If I have a local solution, everything works. But if the solution is in a network directory on another computer, the mentioned behavior appears: No error lines and no reaction to a double click in the error list window.

**Comment by ToddGrun** [comment]
@VaporiZed -- Thank you for following up on this. It sounds like this probably isn't a common enough scenario to warrant further investigation on our side. Please let me know if you disagree, otherwise I will keep as closed. Thanks again!

**Comment by CyrusNajmabadi** [comment]
It also seems like it might be an lsp issue with uris and network paths.  Might be something for @kayle to look at.

**Comment by VaporiZed** [comment]
I'm very sorry. I forgot to write, that this is an regression error. I have my solutions in my network since 15 years and it worked, but  since version … 17.10 (?) it doesn't work anymore. I also tried the scenario in another network: same problem.

**Comment by nickcapitoubt** [comment]
I know this one got closed but this issue does exist.  My team was hit by the same problems.  We were not getting errors in our editor and our Error List would show the errors but if you double clicked it would not take you to the file.  We were launching from a UNC Path.  Switching to a mapped network drive fixed it.  So @CyrusNajmabadi  was write it was network path related. Reverting back to 17.8.11 did fix the issue but now that we have a work around i'm running the latest version again.

**Comment by kayle** [comment]
Yes, I can confirm there's an issue in 17.10 & 17.11 for projects opened from a network share. Should be fixed for 17.12.

**Comment by CyrusNajmabadi** [comment]
@kayle thanks.  is there an internal bug i could link to?

**Comment by kayle** [comment]
You can use https://developercommunity.visualstudio.com/t/Error-squiggles-not-showing/10672591 and https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2073453

**Comment by CyrusNajmabadi** [comment]
Perfect.  Thanks!

**Comment by gandi800** [comment]
Is there any update on this getting fixed. This has caused quite the issue for our development team. 

We're experiencing the same issue when opening files from a network location.

**Comment by kayle** [comment]
@gandi800 This should be fixed in 17.12 prev1. It's also experimentally enabled through a targeted notification on 17.11 and 17.10.5
