### ISSUE TITLE
Syntax coloring broken after updating to 17.10

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73862]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Syntax-coloring-broken-after-updating-to/10675230)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.9]
Syntax coloring doesn't work correctly when loading a project and viewing a file. Issue only started after updating to 17.10.

Broken coloring:
![Untitled2.png](https://aka.ms/dc/image?name=B5585eb7fed7d442e9dd3fb0ce985b2f8638531078669967421_Untitled2.png&tid=5585eb7fed7d442e9dd3fb0ce985b2f8638531078669967421)

Correct coloring:
![Untitled.png](https://aka.ms/dc/image?name=B22d17f7db40e4b29a03c247234445108638531078917928610_Untitled.png&tid=22d17f7db40e4b29a03c247234445108638531078917928610)

---
#### Chris Conti on 6/4/2024, 02:02 PM: 

(private comment, text removed)
#### Feedback Bot on 6/4/2024, 08:00 PM: 

(private comment, text removed)
#### Đức Tài Nguyễn on 6/4/2024, 08:31 PM: 

(private comment, text removed)
#### U_1337743 on 6/5/2024, 11:01 AM: 

(private comment, text removed)
#### Feedback Bot on 6/5/2024, 11:02 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Coresi7** [comment]
I have a demo project in [this ticket ](https://developercommunity.visualstudio.com/t/Syntax-color-is-missing-once-upgraded-to/10675577)help to reproduce. I can't give it as public here, refer to the ticket I mentioned to achieve it.

**Comment by cmconti** [comment]
Here's the demo project and screen shot I attached to my posting on https://developercommunity.visualstudio.com/t/Syntax-coloring-broken-after-updating-to/10675230

[ClassLibrary1.zip](https://github.com/user-attachments/files/15621052/ClassLibrary1.zip)

![2024-06-04_16-54-28](https://github.com/dotnet/roslyn/assets/9708707/4f6f4cd3-3c91-4f24-abc2-82c8ff9225f3)

**Comment by sharwell** [comment]
@CyrusNajmabadi This looks related to the tagging of full semantics after frozen partial semantics tagging finishes

**Comment by CyrusNajmabadi** [comment]
Fixed https://github.com/dotnet/roslyn/pull/72878.
