### ISSUE TITLE
C# verbatim character should be removed in error messages

### ISSUE THREAD

**Issue by leppie** [dotnet/roslyn#7387]
Consider the following:
```
[@X] class F {}
```
Roslyn reports that `@X` cannot be found, whereas the legacy compiler reports that `X` cannot be found. 

Where spotted:
- CS0246
- CS0579
<strike>
- CS0164
</strike>
- CA9999

**Comment by gafter** [comment]
This is a matter of using `identifier.ValueText` in the error message instead of `identifier.Text`.

**Comment by leppie** [comment]
@gafter Easier said than done :) Consider: `@List<@F>`

**Comment by gafter** [comment]
We do not support generic attributes today.

**Comment by leppie** [comment]
This is not only about attributes. Consider:
```
class F : @List<@F> {}
```
Legacy compiler says: `'List' could not be found`
Roslyn says: `'@List<@F>' could not be found`

Perhaps passing in `simpleName` instead of `where.ToString()` for `Binder.NotFound` will be sufficient for this case. I dont really understand there is a `whereText` parameter, goes back to before Git history.

**Comment by leppie** [comment]
Passing in `simpleName` seems to bring it inline with the legacy compiler. But I am sure there must have been a reason for `whereText`. Any ideas?

**Comment by gafter** [comment]
@leppie The reason for the change from the previous (C# 5) version of the compiler is that we rewrote the compiler from scratch.

**Comment by gafter** [comment]
Pretty sure this cannot happen with CS0164 as that doesn't have any fill-ins.

**Comment by leppie** [comment]
@gafter I understand a rewrite is not easy at all, but this is what is happening though. As said in previous comment, it is `whereText` (which is `where.ToString()` at the call site) that seems to be odd, and what there is no history for. There must have been some reason for it, even if it was just some workaround at some stage, but from an outsider's point of view, I cannot make that judgement. Else I would try fix it :)

**Comment by leppie** [comment]
@gafter: You are correct :) `CS0164` seems to be a mistake. I picked it up from the squiggleText. My bad :)

**Comment by leppie** [comment]
@gafter Does the `3 - Working` label imply someone is working on the issue?

**Comment by gafter** [comment]
Yeah... almost done.

**Comment by gafter** [comment]
Blocked by #7516
