### ISSUE TITLE
Proposal: Flow attributes on primary constructor parameters to generated fields

### ISSUE THREAD

**Issue by sbomer** [dotnet/roslyn#73899]
In https://github.com/dotnet/runtime/issues/101861 we encountered a scenario where ILLink produces false positive warnings because annotations on a primary constructor parameter aren't present on a generated field. It sounds like we're open to findind a balance between adjusting implementation details to help out ILLink, and not overly constraining the emit strategy. https://github.com/dotnet/roslyn/issues/46646 discusses a similar issue for annotations on generic parameters.

Here's the most straightforward proposal I could think of: we simply copy the annotation from a primary constructor parameter to the generated field/~property~ if possible. Specifically:
- ~For record types, a primary ctor parameter annotation gets copied to the generated property only if the attribute type supports `AttributeTargets.Property`.~ edit: removed this because record primary ctors support `[parameter: ...]` attribute specifications.
- For non-record types, if there is a generated field for a given primary ctor parameter, a parameter annotation gets copied to the generated field only if the attribute type supports `AttributeTargets.Field`. If there's no generated field, nothing changes.

My hope is that this simple proposal solves the problem without needing any other indication that an annotation should or should not be copied to the field/property. But I don't know if that will cause problems, so I wanted to start a discussion.

The main open questions for me are:
- Do we know of any attributes with `AttributeTargets.Parameter | AttributeTargets.Field` (or `AttributeTargets.Parameter | AttributeTargets.Property`) where the semantics are meaningfully different for parameters vs fields (or parameters vs properties)?
- Is it a breaking change for a new compiler version to add annotations to a public property?
- Are there any concerns around guaranteeing the emit strategy for annotations on properties generated for record primary ctor parameters?

@agocke @MichalStrehovsky @jaredpar

**Comment by agocke** [comment]
> Here's the most straightforward proposal I could think of: we simply copy the annotation from a primary constructor parameter to the generated field/property if possible.

More precisely, I think the proposal is to copy the attributes _if compatible with the AttributeTargets_. My understanding is that AttributeTargets aren't actually enforced by the runtime, so it is up to the compiler whether or not to respect them.

> we simply copy the annotation from a primary constructor parameter to the generated field/property if possible. 

I think the proposal is broader than just primary constructors, right? From broader context, I think the goal would be, for any "compiler-hoisted variable", if the source is a legal attribute target, and the destination is a legal attribute target, and the `AttributeTargets` on the attribute allow the attribute to appear on the target, the compiler would place an equivalent attribute on the corresponding compiler-generated variable.

**Comment by jaredpar** [comment]
I agree we need a broader proposal here vs a specific one for primary constructors. Otherwise we will be back here for closures, records, etc ... Think the better path forward is a broader proposal that lets the IL linker get the info it needs without constraining the compiler from evolving its emit approach

**Comment by alrz** [comment]
For comparison, F# encodes the mapping itself in attributes ([sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgNAGxAMwM5wCYgNQB8CwAUAC4CeADgKYAEAwgK6rED2YlATtQLxHV/UBvagDEo7JiGpN2sAOa9+fADIQJU4jJizqAXyA=)) although it annotates the properties instead of fields.

**Comment by agocke** [comment]
@jaredpar Should we make this issue a draft spec, or would you prefer something in `dotnet/designs`?
