### ISSUE TITLE
char-based enums

### ISSUE THREAD

**Issue by orthoxerox** [dotnet/roslyn#7393]
> Every enumeration type has an underlying type, which can be any integral type except char.

Why not char as well? You can already cast `int` enum values to `char`, but every explicit cast is a potential code smell.

**Comment by svick** [comment]
What's the point? You can already have `enum`s with 16-bit underlying type (`ushort`).

**Comment by orthoxerox** [comment]
@svick but then I have to cast its values to char every time I need to use them.

**Comment by gafter** [comment]
@orthoxerox Enums are not implicitly convertible to their underlying type, so allowing char as an underlying type would not prevent you from having to cast its values to char every time you need to use one.

**Comment by orthoxerox** [comment]
@gafter I really shouldn't post issues as soon as I think of them. `ushort`-backed enums are fine.
