### ISSUE TITLE
Hints for reinstalling Nuget disappeared

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73936]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hints-for-reinstalling-Nuget-disappeared/10668689)._

---
[regression] [worked-in:17.9]
Good afternoon, after updating Visual Studio 2022 to version 17.10.0, the prompts for reinstalling the Nuget package disappeared (in this case, it does not suggest that you need to install the latest version of Newtonsoft), so you need to go to the nuget packages and install everything manually. Very uncomfortable.
![изображение.png](https://aka.ms/dc/image?name=B47403d8fab824f1db0d03ae2f26457d6638524894493020204_20240528-133509-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png&tid=47403d8fab824f1db0d03ae2f26457d6638524894493020204)

Sincerely,
Andrey

---
#### Feedback Bot on 5/28/2024, 09:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
Don't repro this.  Would need a repro project from the user on this:

![image](https://github.com/dotnet/roslyn/assets/4564579/bf717bd7-7f6e-4b29-88ce-90278e759c26)

**Comment by ToddGrun** [comment]
I'm not certain of the behavior change either. I see the exact same behavior in 17.8 vs 17.11, both if the package is not present, present (but out of date), and present (and current).

**Comment by ToddGrun** [comment]
Clsoing as no repro, and hopefully the feedback ticket owner will stop by and let us know if there is some trick we are missing to reproduce.
