### ISSUE TITLE
Update to DotNetCompilerPlatform Nuget due to issue #2790?

### ISSUE THREAD

**Issue by TommiRaunio** [dotnet/roslyn#7394]
Hey,

when could we've update to the Nuget package, which we use to add the C#6 features into the razor view? This one: Microsoft.CodeDom.Providers.DotNetCompilerPlatform 

The issue #2790 is a huge trouble for me. The only workaround is to deny the app pool the access right to the VBCSCompiler.exe, but this seems to kill the performance on the razor view compilation.

br,
Tommi

**Comment by jaredpar** [comment]
This particular issue should be fixed in the update 1 version of the package.
