### ISSUE TITLE
CS8795 reported when expression with reference to another assembly happen

### ISSUE THREAD

**Issue by trejjam** [dotnet/roslyn#73964]
**Version Used**:  .Net 8

**Steps to Reproduce**:

1. Clone https://github.com/trejjam/riok-mapperly/blob/feature/failing-projection-with-static-mapper-from-another-assembly
2. Open test/Riok.Mapperly.IntegrationTests/Mapper/UseExternalMapperFromAnotherAssembly.cs in VS Code/VS/Rider
    (Tested in all these, VS Code 1.90, with C# Dev Kit v1.6.8; VS 2022 17.10.2; Rider 2024.1.3, 2024.2 EAP2)
4. See CS8795 on line 12, 14 and in other source generated code as well

**Diagnostic Id**: CS8795 Partial method `UseExternalMapperFromAnotherAssembly.ProjectToTarget(IQueryable<UseExternalMapperFromAnotherAssembly.Source>)` must have an implementation part because it has accessibility modifiers.

**Expected Behavior**:
There will be no CS8795 since the project compiles normally. It seems like a bug in the C# language server.

**Actual Behavior**:
Error CS8795 is reported.

The error goes away when:
- line 12 is removed (it triggers generating of a method with an expression tree)
- line 9 is removed (it adds a reference to a different assembly from an expression tree)
- DateTimeMapper class is moved to the same assembly (expression tree no longer contains type reference to another assembly)

![image](https://github.com/dotnet/roslyn/assets/3594540/b09ffb33-6164-4f7b-9415-d9485572c477)
![image](https://github.com/dotnet/roslyn/assets/3594540/daae8516-974d-41fc-a916-0d67ccd375c9)
![image](https://github.com/dotnet/roslyn/assets/3594540/315119e4-73b7-4956-99b4-72951732e7a5)
![image](https://github.com/dotnet/roslyn/assets/3594540/adbe4e44-94c2-4c10-b829-383522438c01)

**Comment by ToddGrun** [comment]
@jasonmalinowski -- Do you have any context here? Same analyzer id as https://github.com/dotnet/roslyn/issues/65850 and same repo as https://github.com/dotnet/roslyn/issues/69522

**Comment by trejjam** [comment]
The issue is not with Roslyn.

If anyone hits a similar issue, the problem is that in "IDE" mode, you have a dependency as `CompilationReference` (a link to `Compilation` of your dependencies) rather than the final assembly of your dependency. Due to that, you need special handling at some places when processing SyntaxTrees from your dependencies.
