### ISSUE TITLE
An empty VB method should have no operations in that block.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7397]
Consider an empty VB method:

``` vb.net
Sub foo()
End Sub
```

If I register an OperationBlockAction and inspect the Operations in that block, I'd expect it to have no operations.

Instead, it has one LabelStatement operation for an Exit label. This is implementation detail that shouldn't show up in the operation tree. C# doesn't have this issue.

**Comment by jinujoseph** [comment]
lets verify isimplicit flag is set

**Comment by 333fred** [comment]
We should also look into synthesized objects like SynthesizedLocals, https://github.com/dotnet/roslyn/pull/22056#discussion_r138746756.

**Comment by mavasani** [comment]
I verified the operation tree for empty Sub Block is following and none of the nodes are marked implicit:

```
IBlockStatement (2 statements) (OperationKind.BlockStatement) (Syntax: 'Sub Foo'BIN ... End Sub')
  ILabeledStatement (Label: exit) (OperationKind.LabeledStatement) (Syntax: 'End Sub')
    Statement: null
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'End Sub')
    ReturnedValue: null
```

We need to fix this for 15.5.

**Comment by mavasani** [comment]
We can fix this in few ways (and we will probably have to do similar fixes in other places in future, so tagging @AlekseyTs, @jinujoseph and @DustinCampbell for the preferred approach):

1. Mark the bound nodes created in the binder as `WasCompilerGenerated = true`, which will flow into `IOperation.IsImplicit`.
2. Explicitly filter out bound Labeled statement and Return statement nodes with EndBlockStatementSyntax in OperationFactory
3. Explicitly handle bound Label statement and Return statement nodes with EndBlockStatementSyntax in OperationFactory and mark them as `IsImplicit`.

**Comment by mavasani** [comment]
I prefer 2. as this also ensures parity between C# and VB operation trees.

**Comment by DustinCampbell** [comment]
I agree, so long as that doesn't break the following code (though I wouldn't expect it to, since the syntax would be different).

```VB
Sub foo()
    Exit Sub
End Sub
```

Hmmm... that makes me wonder what the operation tree look like for VB code that uses the implicit function variable:

```VB
Function foo%()
    foo = 42
    Exit Function
End Function
```

**Comment by mavasani** [comment]
@DustinCampbell - The `Exit Sub` and `Exit Function` statements both generate:
```
IBranchStatement (BranchKind.Break, Label: exit) (OperationKind.BranchStatement) (Syntax: 'Exit Sub')
```

This indicates to me that we cannot filter out the label statement, and probably should also retain it as an explicit node as there is syntax marking the label:
```
ILabelStatement (Label: exit) (OperationKind.LabelStatement) (Syntax: 'End Sub')
    LabeledStatement: null
```

The ReturnStatement for the first case has null ReturnedValue, while the second case has:
```
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'End Function')
    ReturnedValue: ILocalReferenceExpression: foo (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'End Function')
```


Probably the only change we can make here is to mark the IReturnStatement and ReturnedValue as implicit.

**Comment by DustinCampbell** [comment]
Ah, I hadn't realized that `Exit Sub` and `Exit Function` would be branch statements to the exit label, though it makes complete sense now that I think about it.

So, it seems that, even though these are implementation details, they can be important to the user.

(Now I'm starting to wonder about `On Error Resume Next` :smile:)

**Comment by DustinCampbell** [comment]
And, yeah, I think the return statement and returned value have to be marked as implicit.

**Comment by mavasani** [comment]
The IOperation for the following code also feels weird to me as it has 2 return statements:
```
    Sub foo()
        Return
    End Sub
```

```
IBlockStatement (3 statements) (OperationKind.BlockStatement) (Syntax: 'Sub foo() ... End Sub')
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'Return')
    ReturnedValue: null
  ILabeledStatement (Label: exit) (OperationKind.LabeledStatement) (Syntax: 'End Sub')
    Statement: null
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'End Sub')
    ReturnedValue: null
```

And the below code too:

```
    Function foo%()
        foo = 42
        Return foo
        Exit Function
    End Function
```

```
IBlockStatement (5 statements, 1 locals) (OperationKind.BlockStatement) (Syntax: 'Function fo ... nd Function')
  Locals: Local_1: foo As System.Int32
  IExpressionStatement (OperationKind.ExpressionStatement) (Syntax: 'foo = 42')
    Expression: ISimpleAssignmentExpression (OperationKind.SimpleAssignmentExpression, Type: System.Int32) (Syntax: 'foo = 42')
        Left: ILocalReferenceExpression: foo (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'foo')
        Right: ILiteralExpression (Text: 42) (OperationKind.LiteralExpression, Type: System.Int32, Constant: 42) (Syntax: '42')
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'Return foo')
    ReturnedValue: ILocalReferenceExpression: foo (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'foo')
  IBranchStatement (BranchKind.Break, Label: exit) (OperationKind.BranchStatement) (Syntax: 'Exit Function')
  ILabeledStatement (Label: exit) (OperationKind.LabeledStatement) (Syntax: 'End Function')
    Statement: null
  IReturnStatement (OperationKind.ReturnStatement) (Syntax: 'End Function')
    ReturnedValue: ILocalReferenceExpression: foo (OperationKind.LocalReferenceExpression, Type: System.Int32) (Syntax: 'End Function')
```

**Comment by mavasani** [comment]
@jinujoseph I am marking this for Discussion, there are quite a few corner cases here that we probably need to bring it up at the design meeting.

**Comment by mavasani** [comment]
Design decision: We decided to mark both the label and return statement for end block statement.
