### ISSUE TITLE
Peek definition doesn't work on source-generated methods

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#73970]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
using System.Runtime.InteropServices;

partial class Program
{
    [LibraryImport("lib.dll")]
    public static partial void MyNativeCall();
}
```
Right click on `MyNativeCall` and choose 'Peek definition'

**Expected Behavior**:
It works and shows source-generated definition, same as 'Go to definition' works

**Actual Behavior**:
![devenv_b7QyFrTGLh](https://github.com/dotnet/roslyn/assets/70431552/d611fb64-52fd-4100-bcfe-bb9675109cb6)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski likely a dupe.
