### ISSUE TITLE
OOM during constant string folding due to allocations from ConstantStringValue

### ISSUE THREAD

**Issue by rynowak** [dotnet/roslyn#7398]
Currently in ASP.NET Razor code generation, when we have a large contiguous block of HTML, it gets code-generated as a series of concatenated string constants:

Example:

```
        #pragma warning disable 1998
        public override async Task ExecuteAsync()
        {
            BeginContext(48, 31408, true);
            WriteLiteral(
"<!DOCTYPE html><html prefix=\"og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#\"  lan" +
"g=\"en-US\"  style=\"font-size:62.5%\"  class=\"hiperf\"  dir=\"ltr\" >\r\n\r\n<head data-in" +
"fo=\"v:2.0.5798.31020;a:cc7227b7-f7fe-4e3b-b644-226f3ef2c489;cn:125;az:{did:1f802" +
"c514e1c42e385b028b15ac20ce4, rid: 125, sn: westus-hp, dt: 2015-11-16T22:01:08.08" +
"25616Z, bt: 2015-11-17T01:14:47.5617874Z};ddpi:1;dpio:;dpi:1;dg:tmx.pc.webkit.ch" +
"rome;th:start;PageName:startPage;m:en-us;cb:;l:en-us;mu:en-us;ud:{cid:,vk:homepa" +
"ge,n:,l:en-us,ck:};xd:AA3iOMG;ovc:f;al:;fxd:t;xdpub:2015-11-18 20:26:50Z;xdmap:2" +
"015-11-18 20:30:01Z;axd:;f:muidflt2cf,muidflt9-ismsft,d-thshldie1,d-thshldie2\"  " +
"data-js=\"{&quot;dpi&quot;:1.0,&quot;ddpi&quot;:1.0,&quot;dpio&quot;:null,&quot;f" +
"orcedpi&quot;:null,&quot;dms&quot;:6000,&quot;bds&quot;:7,&quot;dg&quot;:&quot;t" +
"mx.pc.webkit.chrome&quot;,&quot;ssl&quot;:false,&quot;moduleapi&quot;:&quot;http" +
"://www.msn.com/en-us/homepage/api/modules/fetch&quot;,&quot;cdnmoduleapi&quot;:&" +
"quot;http://static-hp-wus.s-msn.com/en-us/homepage/api/modules/cdnfetch&quot;,&q" +
"uot;pdpdeltaupdateapi&quot;:&quot;http://www.msn.com/en-us/homepage/api/pdp/upda" +
"tepdpdata&quot;,&quot;xd&quot;:&quot;aa3iomg&quot;,&quot;signedin&quot;:1,&quot;" +
"sso&quot;:&quot;&quot;,&quot;exchangeenabled&quot;:true,&quot;twitterimpenabled&" +
...
```

For example, taking the home page of MSN.com and running it through Razor yields something like https://gist.github.com/rynowak/de862bfb9199caa578f8

This causes some really intense allocation during Roslyn compilation of the generated code, and will OOM. 

![image](https://cloud.githubusercontent.com/assets/1430011/11722450/999308b8-9f1d-11e5-9774-0074106cc80a.png)
# 

On our side we're going to take some steps to work around this - the way the codegen works today is largely a product of legacy carried forward from CodeDOM :laughing: In the end, we'll still likely be dealing with a need to efficiently codegen C# and compile it using Roslyn during **runtime**, so any advice you have would be beneficial.

Even though the `string.Concat`s happen at compile-time we still end up with an LOH string at runtime, which we'd like to avoid.

We're going to start by getting rid of the `string.Concat`s here, and just emit strings of a non-LOH size with more calls to `WriteLiteral`.

**Comment by gafter** [comment]
@rynowak Can you reproduce this with the compiler in VS2015 Update 1, or is it only the compiler in VS2015 RTM that has this issue?

**Comment by gafter** [comment]
Also, have you considered calling `WriteLiteral` over and over again on pieces of the string, instead of trying to build one huge string to pass to `WriteLiteral` all at once?

**Comment by rynowak** [comment]
> Also, have you considered calling WriteLiteral over and over again on pieces of the string, instead of trying to build one huge string to pass to WriteLiteral all at once?

We've already worked around this issue by doing this. I still wanted to report the issue since it's pretty gnarly if you happen to hit it.

> @rynowak Can you reproduce this with the compiler in VS2015 Update 1, or is it only the compiler in VS2015 RTM that has this issue?

This is from the ASP.NET team, we're using your nightlies (basically), so I'd have to say it still reproes on update 1.

**Comment by gafter** [comment]
This issue could be addressed by using [Ropes](https://en.wikipedia.org/wiki/Rope_(data_structure)) as the compiler's internal representation of string constant values.

**Comment by gafter** [comment]
Fixing this now.

**Comment by gafter** [comment]
A fix for this is in review at https://github.com/dotnet/roslyn/pull/37915

**Comment by gafter** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/37915
