### ISSUE TITLE
Outlining no longer obeys preferences

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#73984]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Outlining-no-longer-obeys-preferences/10674151)._

---
[severity:It's more difficult to complete my work]
For the last couple of weeks or so, WPF and C# files are now collapsed to outlines when opening on my PC, disregarding the preferences. I've tried different options but cannot seem to stop this unwanted outlining behaviour.

![image.png](https://aka.ms/dc/image?name=Bbeea2f4aaa3c4e18a404a95d6e1f69b5638530246411661491_20240603-161720-image.png&tid=beea2f4aaa3c4e18a404a95d6e1f69b5638530246411661491)

---
#### Feedback Bot on 6/4/2024, 00:56 AM: 

(private comment, text removed)
#### Chris Wang [MSFT] on 6/4/2024, 04:42 AM: 

(private comment, text removed)
#### jason.williams on 6/4/2024, 07:38 AM: 

(private comment, text removed)
#### jason.williams on 6/7/2024, 06:56 AM: 

(private comment, text removed)
#### Chris Wang [MSFT] on 6/6/2024, 04:41 AM: 

(private comment, text removed)
#### Feedback Bot on 6/12/2024, 08:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ToddGrun** [comment]
Jason -- Does the outlining go away if you expand the items, close the file, and then re-open the file? VS does remember the outlining state of your file when you close, so if you had closed a file with the outlining regions collapsed, it will collapse the items the next time you open the file, regardless of settings.

**Comment by zotrb** [comment]
Can this be reopened please?
This report was moved onto this ticketing system and so I didn't get any notifications to tell me that people were asking questions here.

This is not fixable on my end:
* It exhibits the same behaviour on 3 different PCs
* It exhibits the same behaviour with all Extensions uninstalled
* It exhibits the same behaviour after uninstalling and reinstalling VS2022
* I don't recall Visual Studio exhibiting this behaviour between 1996 and ~June 2024, so it appears to have been added by a recent change.

My preferences have all outlining options disabled (in the 4 places they occur: C#, F#, VB and XML options). I could not find any outlining options specific to XAML:
![Image](https://github.com/user-attachments/assets/d2886fc8-4e2d-4912-b195-0ae21d41dad1)
![Image](https://github.com/user-attachments/assets/d6d5e4fb-9bae-4faf-b58f-e7f5e8c0dbe5)

When I open (e.g.) any XAML or XML file, outlining is automatically enabled so the view is cluttered with loads of chevron icons:
![Image](https://github.com/user-attachments/assets/d05a9726-f412-4aea-8a33-3d92b1ce3568)

I can choose "stop outlining":
![Image](https://github.com/user-attachments/assets/ae76a60e-18cc-487f-9d23-77c16b6c2941)

...and the chevrons are removed:
![Image](https://github.com/user-attachments/assets/1c5609c0-2aa3-48b0-b865-b07fece39d4c)

Also, if I choose "start automatic outlining" the chevrons come back as expected.

This state is reset if the file is closed. That is, the next time I open any XAML or XML file, outlining is enabled regardless of what settings or preferences I previously chose.

It seems clear from this evidence that it is the outlining feature that is responsible for the chevrons, and that the outlining feature is ignoring the preference options that are set to "do not use outlining" for XML and XAML files. Outlining works as expected on C# files, however.
