### ISSUE TITLE
Figure out how to build and test against dev15 debugger binaries in the open

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn#7399]
We can build against whichever version we want using our existing reference assembly mechanism, but it turns out that our tests depend on having dev14 installed.  Dev14 GACs M.VS.Debugger.Metadata, so the assembly resolver picks that version, rather than the reference assembly in the output directory.  The tests depend on having the real one for a somewhat silly reason - our test mocks subtype the types in M.VS.D.M, so the runtime throws an exception if their constructors aren't around to be called at runtime.  We might be able to work around this problem by emitting our reference assemblies to a subdirectory, so that they're still available for building, but not available at runtime.  Then we could hook assembly resolution and search for the appropriate assembly (either dev14 or dev15) under Program Files.

A solution along those lines would get us building and testing again, but we'd still have to figure out a way to dogfood.  Since the new APIs will be implemented and not just called, it's not clear whether we can use a reflection-light-up approach to consume either the new or the old APIs at runtime.  So self-hosting without actual dev15 binaries is likely to be the biggest problem in this area.

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-interactive @cston @jaredpar

**Comment by ManishJayaswal** [comment]
I think this issue is resolved now as we are running our tests against Dev15 now.
