### ISSUE TITLE
Conditional access expression in other contexts where expression value is ignored

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#74]
Continue of issue #11 and fix commit e86d3640d08302b1b0fb05dcbca44842f2073198 story.

There are more places in C# where expression value is ignored - `Task`-returning `async` methods and `async` lambda expressions:

```c#
using System;
using System.Threading.Tasks;

class Foo<T>
{
    T Method() => default(T); // returns value of unconstrained type parameter type
    
    void M1() => this?.Method(); // ok
    
    async void M2() => this?.Method(); // ok
    
    // error CS0023: Operator '?' cannot be applied to operand of type 'T'
    async Task M3() => this?.Method();
    
    void M4() {
        Action f1 = async () => this?.Method(); // ok
        
        // error CS0023: Operator '?' cannot be applied to operand of type 'T'
        Func<Task> f2 = async () => this?.Method();
    }
}
```

I'm expecting this code compile fine.

**Comment by gafter** [comment]
"Area-Language Design" tells me there may be a shortcoming of our current language design. If that is so it needs to be taken to the language design group before implementation work is planned (except perhaps as a prototype of proposed language changes).

**Comment by AlekseyTs** [comment]
Before resolving this issue, please ensure VB handles similar scenarios in the same way. Please add a unit-test if we don't have one (all VB tests for conditional access are in Compilers\VisualBasic\Test\Semantic\Semantics\ConditionalAccessTests.vb).

**Comment by gafter** [comment]
This issue, its fix, and tests are for C# only. Please add separate issues for VB is you have concerns there.

**Comment by gafter** [comment]
@agocke Can you please verify this is fixed?
