### ISSUE TITLE
Permit Where to do nullability checks

### ISSUE THREAD

**Issue by Forgind** [dotnet/roslyn#74008]
**Brief description:**
People who use linq tend to love linq and don't want to have to go outside it. In this example:
myList.Select(i => i == 1 ? null : 2).Where(i => i != null)

myList is a list of int?. The Select turns it into an IEnumerable<int?>. The Where _could_ turn it into an IEnumerable<int>, which would be ideal, but it instead leaves it as an IEnumerable<int?>. It would be nice to make it IEnumerable<int?>

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

**Comment by Forgind** [comment]
@MiYanni gave me a workaround: .OfType<int> does what I'd want.

**Comment by CyrusNajmabadi** [comment]
Closing out as a workaround was given.
