### ISSUE TITLE
Visual Basic double to integer conversion tests stopped working in .NET 9 Preview 5

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#74026]
**Version Used**: 62f2d479162cfb2353478d9dbd72a597b3b9fd1f (https://github.com/dotnet/roslyn/pull/73656)

Need to have `TargetFramework=net9.0` to reproduce locally.

Errors are like:

```
Failed Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenExpression.CIntTruncate_Implicit_01 [28 ms]
  Error Message:
   System.Exception : Error on 2147483648 -2147483648
  Stack Trace:
     at C1.CheckDouble(Double s, Int32 expected) in a.vb:line 51
   at C1.Main() in a.vb:line 42
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

This issue is mentioned in tests.

**Comment by jjonescz** [comment]
Looks like this is an intentional breaking change: https://github.com/dotnet/runtime/issues/43895.

Simple repro:

```cs
var actual = floatToInt(int.MaxValue);
var expected = int.MinValue;
Console.WriteLine($"{actual == expected} {actual} {expected}");

static int floatToInt(float f) => (int)f;
```

with .NET SDK 9.0.100-preview.5.24307.3 and

```ps1
dotnet run -f net8.0 && echo '---' && dotnet run -f net9.0
```

prints

```
True -2147483648 -2147483648
---
False 2147483647 -2147483648
```

**Comment by jaredpar** [comment]
> Likely cannot simply change the affected tests to observe the new behavior if they are being executed with different runtimes.

One approach to adjust the baseline based on the current runtime. Basically have the one value for `net472` and the other for `net9.0`.
