### ISSUE TITLE
Inheritance margin doesn't work well with screen scaling

### ISSUE THREAD

**Issue by ryzngard** [dotnet/roslyn#74035]
**Version Used**: 17.11.0 Preview 3 [35013.214.main]

**Steps to Reproduce**:

I hooked up multiple monitors to the landing desks in the office, resulting in multiple monitor resolutions. Opening inheritance margin on screen resulted in very large text 

![image](https://github.com/dotnet/roslyn/assets/475144/cc1476dc-e5a1-4628-b51b-af0110ada9e5)

**Comment by CyrusNajmabadi** [comment]
Perhaps we just really wanted you to know the type was disposable?

**Comment by ryzngard** [comment]
It _really_ didn't want me to forget to dispose it. That's a kindness in it's own right I suppose
