### ISSUE TITLE
Remove IBuiltInAnalyzer.OpenFileOnly

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#74048]
Used to limit certain analyzers to open files only, based on options that affect the analysis. 
We use global values of editorconfig options to determine whether or not to enable analysis for open docs.
The actual values of these options can be set in editorconfig files and vary file by file.

Seems like these analyzers should just respond to pull diagnostics and we should remove this check.

Non-trivial implementations:
-	SimplifyTypeNamesDiagnosticAnalyzerBase
-	PreferFrameworkTypeDiagnosticAnalyzerBase
-	AbstractQualifyMemberAccessDiagnosticAnalyzer
-	CSharpTypeStyleDiagnosticAnalyzerBase

Tracks TODO in code.

**Comment by CyrusNajmabadi** [comment]
i'm going to try to do this.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/74340.
