### ISSUE TITLE
Automatic class initialization scaffolding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74078]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Automatic-class-initialization-scaffoldi/10675134)._

---
Automatic class initialization scaffolding.

Let's say I have a class with 12 properties that can be set. I would like to have the possibility to have the scaffolding done by Visual Studio automatically when I create the basic initialization statement:

```
var command = new CreateXyzCommand() 
{
// give me possibility to scaffold all those properties automatically somehow, by IntelliSense I guess
Property1 = xxx,
Property2 = new List<string>() { },
Property3 = new AnotherObject(),
// ...
// Property12 = xxx
}
```

I don't really care what will be inserted instead the xxx words, but even this kind of help would be so helpful...

Second proposition would be to generate automatic mapping from class to class based on types and names which also can be useful if somebody is into this kind of stuff (personally I hate using the mappers to be honest specially if there is only one mapping involved).

```
var command = new CreateXyzCommand()
{
// give me possibility to scaffold all those properties automatically somehow, by IntelliSense I guess
Property1 = fromOther.Property1,
Property2 = fromOther.Property2,
Property3 = xxx-unknown,
// ...
// Property12 = fromOther.Property12
}
```

---
#### Feedback Bot on 6/4/2024, 08:17 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
We have many features to help you with this already in the lightbulb.
