### ISSUE TITLE
Add assembly version information to method tooltips

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74077]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-assembly-version-information-to-meth/10676406)._

---
When editing C# source code and hovering over methods contained in libraries, it would often be oft value to see which version of the assembly this specific method refers to, what is it resolved to.

So instead of showing only the method definition, also show the version of the assembly where it is defined. Maybe even add (optionally) the name and location of the assembly, could be hidden behind a clickable (i) icon.

![image.png](https://aka.ms/dc/image?name=Ba81eaf1bf15e46ab87e9df3e5cd23eb1638531822362211279_20240605-120355-image.png&tid=a81eaf1bf15e46ab87e9df3e5cd23eb1638531822362211279)

---
#### Feedback Bot on 6/6/2024, 01:54 AM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closoing out as unplanned due to no broaad feedback on this, along with the major regressions in the experience this would cause.
