### ISSUE TITLE
Add string to NameOf option in intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74079]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-string-to-NameOf-option-in-intellise/10682511)._

---
As a person working with older code, I often find code like:
`NotifyPropertyChanged("ShowPartNumberFilter")`  

Having IntelliSense recommend, and give the ability to change the code to the below would be a time saver:
`NotifyPropertyChanged(NameOf(ShowPartNumberFilter))`

I can see this as a quick action, as well as a message in the Error List, and a code clean up option.

---
#### Feedback Bot on 6/13/2024, 10:39 PM: 

(private comment, text removed)

**Comment by CyrusNajmabadi** [comment]
Closing out as we are not investing in these experiences.
