### ISSUE TITLE
ISymbol.ToMinimalDisplayString() ignores the SymbolDisplayTypeQualificationStyle.NameOnly formatting option.

### ISSUE THREAD

**Issue by rivierasolutions** [dotnet/roslyn#74071]
**Version Used**: 
```
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.10.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.10.0" />
<PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.10.0" />
```

**Steps to Reproduce**:

1. Create a project in an Microsoft.CodeAnalysis.AdhocWorkspace using MefHostServices
2. Add some code files to the project
3. Use SymbolFinder.FindSymbolAtPositionAsync(...) to find a symbol in any file 
4. call ISymbol.ToMinimalDisplayString(semanticModel, position, SymbolDisplayFormat.MinimallyQualifiedFormat) to display the symbol

A minimal repro, with source-code provided, is ideal.  Using [sharplab](https://sharplab.io/) is preferred for compiler/language issues whenever possible.

**Diagnostic Id**:

If this is a report about a bug in an analyzer, please include the diagnostic ID and message if possible (e.g. `"IDE0030: Use coalesce expression"`).

**Expected Behavior**:
Type qualifications in the symbol do not contain namespaces (expected output):
```
IEnumerable<Note> IEnumerable<Note>.Skip<Note>(int count)
```

**Actual Behavior**:
Type qualifications in the symbol contain namespaces (actual output):
```
System.Collections.Generic.IEnumerable<documents.Note> System.Collections.Generic.IEnumerable<documents.Note>.Skip<documents.Note>(int count)
```

**Comment by rivierasolutions** [comment]
For anyone struggling with this issue: ISymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat) seems to work correctly.

**Comment by CyrusNajmabadi** [comment]
Minimal means it figures out the qualifications from the position/context you pass in. If you don't want that, then just use normal ToDisplayString
