### ISSUE TITLE
Add IL Viewer for .NET languages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74080]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-IL-Viewer-for-NET-languages/10685603)._

---
Hello. I would like to see IL code viewing in Visual Studio, like in the ReSharper extension for .NET Languages

---
#### Feedback Bot on 6/18/2024, 10:10 PM: 

(private comment, text removed)

**Comment by Cosifne** [comment]
Triaged in MetadataAsSource area

**Comment by CyrusNajmabadi** [comment]
Closing as out of scope.  Roslyn is not the IL editor language for .net.  If .net wants this, it can supply its own lsp.
