### ISSUE TITLE
Prepend $(NoWarn) to list analyzer rule generates a false positive.

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/roslyn#74087]
Not sure if the issue goes here or over with the analyzers because I can find no references anywhere to the ID or where project file analyzers reside.

The issue is that if you have a project file that appends warnings to the `$(NoWarn)` value then an analyzer rule kicks in telling you to prepend $(NoWarn) to list and the fix appends to the value although you're already doing that.

**Version Used**: 8.0

**Steps to Reproduce**:

1. Create a simple C# project.
2. In the project file add the following property `<NoWarn>$(NoWarn),CA2201</NoWarn>`. 
3. The IDE will generate an analyzer recommendation saying you should prepend the values to $(NoWarn) which is already being done.

**Diagnostic Id**:
Prepend $(NoWarn) to list

**Expected Behavior**:
This should not generate a false positive because the value(s) are being added to the list.

**Actual Behavior**:
Analyzer generates a warning.

The problem, I believe, is with the comma separates. Most of the documentation shows separating the values with a comma. However in the couple of cases where the docs show appending to $(NoWarn) they are separated by semicolons. There doesn't seem to be any clarification on which one is correct. The analyzer doesn't appear to support using commas. Since this syntax is valid (I believe) the analyzer should support using either comma or semicolon separators. If commas are not allowed then all the examples that show commas being used should be updated to clarify that semicolons are needed instead.

**Comment by jjonescz** [comment]
Should you use a semicolon instead of a comma? I.e., `<NoWarn>$(NoWarn);CA2201</NoWarn>`.

**Comment by Cosifne** [comment]
Closed as this looks like a syntax error in csproj file

**Comment by mtaylorfsmb** [comment]
@Cosifne  How is this a syntax error in the csproj file? Both semicolon and commas are valid in a project file. Refer to the docs to confirm this or else the docs are wrong and need to be updated. The analyzer is the only place that this seems to be a problem with as the warnings seem to go away using either punctuator during a build.
