### ISSUE TITLE
[Test Failure] Hung processs on target machine in prtest/lin/dbg/unit32 on PR #files

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7411]
PR: [#files](https://github.com/dotnet/roslyn/pull/7410/files) *\* by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1986/

**Issue 1: Hung processs on target machine**
A process is hung on the target machine and preventing it from cleaning up the workspace

...

15:11:45 [xUnit] [INFO] - Starting to record.
15:11:45 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
15:11:46 [xUnit] [WARNING] - Can't create the path /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/generatedJUnitFiles. Maybe the directory already exists.
15:11:46 [xUnit] [ERROR] - /mnt/j/workspace/roslyn_prtest_lin_dbg_unit32 does not exist.
15:11:46 ERROR: Step ?Publish xUnit test result report? aborted due to exception: 

anyone saw this issue before?

**Comment by davkean** [comment]
For this you need to take the node offline and see what's process is holding the file - last time this was a product bug in csc.

**Comment by davkean** [comment]
I've taken http://dotnet-ci.cloudapp.net/computer/dci-ub-bld-13/ offline so that we stop putting jobs on it.

**Comment by davkean** [comment]
This is now resolved.

**Comment by dpoeschl** [comment]
Reactivating based on https://github.com/dotnet/roslyn/pull/10053

**Comment by heejaechang** [comment]
@srivatsn @dpoeschl why this is on my plate? looks like IDE bug?

**Comment by heejaechang** [comment]
giving this to @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
Looks like it was reactivated ages ago and then ignored. Just going to close this again.
