### ISSUE TITLE
empty string vs. null string

### ISSUE THREAD

**Issue by kasperk81** [dotnet/roslyn#74126]
```c#
s += null;
```
gets compiled to `s ?? ""`

```c#
s += string.Empty;
```
gets compiled to a method call `s = string.Concat(s, string.Empty)`. can it be `s ?? ""` as well?

**Comment by jaredpar** [comment]
> can it be s ?? "" as well?

Possibly but is there a specific benefit of doing that? Does it shrink IL, have better throughput, etc ....

**Comment by jaredpar** [comment]
Okay but how common is this pattern? Hard to see this being a big item we should be prioritizing.

**Comment by EgorBo** [comment]
> yes there is a codegen [impact](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmbjnEgAzYByArgDZMAUVtEAlMaefx2wAnbAF5sEANx9+ZCNgDU4gHbMm0tLPJwA7MI38AvjIq4a2AKJQADsACe7c916atZ2iPFST/eUvcAdFa2dgZuuvomxmiGQA). @EgorBo assuming runtime can't optimize this pattern?

I think we can tweak the inliner a bit to optimize this case, here it's not optimized because String.Concat is not inlined

**Comment by huoyaoyuan** [comment]
Note: at the compiler's side of view, `string.Empty` is different from `""`, because it's `static readonly`, not a `const`. Roslyn doesn't make assumption or special knowledge about `string.Empty`'s value.

If you use the empty string literal instead, it will be optimized in roslyn.
