### ISSUE TITLE
Static interface methods with a default implementation should be visible on the derived type.

### ISSUE THREAD

**Issue by jamesfoster** [dotnet/roslyn#74138]
**Version Used**: 
Microsoft (R) Visual C# Compiler version 4.9.0-3.24121.1 (a98c90d5)

**Steps to Reproduce**:

1. [sharplab.io example](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwG4EMwAIAeBGLAXiwBEBTMAS1TLgDoBhMM9YMvACgEoBuAWABQGbDgBMRUhWq1GzVmVHd+AwZShswAM3QBjMlgAS6AM4AxXcAD2YAJ4AeACoBlMgBtNAPkFYsAdwAWFPrObppYIIYm5jpWto4u7h4wWFBkvtyCAN7ePrkAAngAbFgh7lhMLGycXDm5WNkCdU1YeQDsKWklCZpKtbkAvn0+BcXoAEbGwGAWXaHlcmyKvIKDKgJ5AMwt4uRUNHDhkWYW1va70nBeAg3Nmy1Fknu085UKGY1NN8357am+jxdeh86qt+kA)

**Diagnostic Id**: CS0117

**Expected Behavior**:

Static interface methods with a default implementation should be visible on the derived type.

**Actual Behavior**:

The derived class inherits from an interface with 2 static methods, but methods with a default implementation are not visible on the type.

**Comment by CyrusNajmabadi** [comment]
This is by design. Interface members are never looked up when calling members on a class. The same is true for non statics as well. 

If you would like to see this changed, it would need to start with a discussion on dotnet/csharplang.
