### ISSUE TITLE
RegexGenerator throwing error CS0165: Use of unassigned local variable.

### ISSUE THREAD

**Issue by ComplexSymbol** [dotnet/roslyn#74133]
**Version Used**: 
Dotnet 7.

**Steps to Reproduce**:
1. Use GeneratedRegex attribute `[GeneratedRegex(@"(?()|.??(?<=))(?!.)", RegexOptions.Compiled, "en-US")]` on a partial method of any name.
2. Allow the regex generator to complete a source implementation of the regex.
3. Compile and observe the source implementation throw an error of CS0165 on the read-only file RegexGenerator.g.cs (Compiler error: `RegexGenerator.g.cs(XX,XX): Error CS0165: Use of unassigned local variable 'lazyloop_iteration' (CS0165)`)

**Minimal cs file:**
```
using System.Text.RegularExpressions;

namespace Test
{
    public class EntryPoint
    {
        public static void Main() { }
    }

    partial class TestClass
    {
        // language=regex
        public const string TestRegex = @"(?()|.??(?<=))(?!.)";

        [GeneratedRegex(TestRegex, RegexOptions.Compiled, "en-US")]
        private static partial Regex MoveLegalityRegex();
    }
}
```

**Relevant Portion of generated source implementation:**
```
// Match a character other than '\n' lazily, optionally.
//{
    int lazyloop_iteration = 0;
    lazyloop_pos = pos;
    goto LazyLoopEnd;
    
    LazyLoopBacktrack:
    if (lazyloop_iteration >= 1)
    {
        return false; // The input didn't match.
    }
    lazyloop_iteration++;
    if (Utilities.s_hasTimeout)
    {
        base.CheckTimeout();
    }
    
    pos = lazyloop_pos;
    slice = inputSpan.Slice(pos);
    if (slice.IsEmpty || slice[0] == '\n')
    {
        return false; // The input didn't match.
    }
    pos++;
    slice = inputSpan.Slice(pos);
    lazyloop_pos = pos;
    
    LazyLoopEnd:;

```
Note that `lazyloop_iteration` was clearly initialized to `0`. The `LazyLoopBacktrack` tag is probably causing this error even though the first instance of `goto LazyLoopBacktrack` is on a line far after `lazyloop_iteration` has been defined. 

**Expected Behavior**:
The regex generator would write a complete, bug-free source implementation of my desired regex.

**Actual Behavior**:
The regex generated code with an unfixable error because RegexGenerator.g.cs is read-only.

**Comment by CyrusNajmabadi** [comment]
This is unrelated to Roslyn.  You might want to report this at dotnet/runtime.  Unfortunately I cannot move this.

**Comment by ComplexSymbol** [comment]
Sorry, someone else told me to report it here. Where specifically should I move this?

**Comment by CyrusNajmabadi** [comment]
Dotnet/runtime

**Comment by ComplexSymbol** [comment]
See https://github.com/dotnet/runtime/issues/103942#issue-2371624105
