### ISSUE TITLE
Test Plan for Overload Resolution Priority

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#74131]
Championed issue: https://github.com/dotnet/csharplang/issues/7706
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-13.0/overload-resolution-priority.md

## C# Compiler

- [ ] spec: confirm LangVer behavior
- [x] spec: confirm for local functions,
- [x] effect in invocation
  - [x] higher values win, lower values lose, default value is zero, same values remain ambiguous
  - [x] pruning happens on applicable candidates
  - [x] applies to extensions
  - [x] in source and metadata (changes in overrides in metadata have no effect)
  - [x] LangVer doesn't affect overload resolution
- [x] effect in object creation and attributes
- [x] effect in delegate conversion
- [x] effect on properties
  - [x] indexers
  - [x] indexed properties
- [x] effect in unary and binary operators
- [x] no effect in function type (`var x = A.B;` with multiple `B` candidates)
- [x] attribute application
  - [x] LangVer 
  - [x] error on overrides (even those restating priority) and explicit interface implementations
  - [x] error on accessors
  - [x] cycles
  - [x] applied twice
  - [x] applied on partial method or indexer
  - [x] nothing on local functions, 
  - [x] spec: error on lambdas, destructors, conversion operators, static constructors
- [x] public API? (not planned yet)
- [x] BCL types ([added](https://github.com/dotnet/runtime/pull/102176))
- [x] notify other teams/languages
- [x] expression tree. Expression<> x = (a) => A.B(a); // priority should be honored, silent source break like params? can yield an error identify and document known scenario, notify BCL team (apply with care)
- [x] interpolation handlers
- [x] query syntax

## VB Compiler
- [ ] TBD (we'll plan and implement in .NET 9)

## Productivity
No IDE impact

**Comment by jaredpar** [comment]
@333fred make sure to create an issue label we can  use for this feature and attach it to this issue

**Comment by 333fred** [comment]
All remaining tests have been covered. Closing out.
