### ISSUE TITLE
Conversions to restricted types are not disallowed in expression trees

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#74143]
We disallow restricted types in expression trees (since https://github.com/dotnet/roslyn/pull/30871). But we exclude conversions to restricted types - https://github.com/dotnet/roslyn/pull/30871#discussion_r230242508 mentions avoiding duplicate diagnostics, but there are other scenarios which result in no diagnostics at all, like:

```cs
using System;
using System.Linq.Expressions;

C.R(() => C.M(new string[] { "a" }));

static class C
{
    public static void R(Expression<Action> e) => e.Compile()();
    public static void M(ReadOnlySpan<string> x) => Console.Write(x[0]);
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAZWAR2oFEAPAB2QFMBnHqAPYweAbmLEAwtQBKAClkBKcgF4AfOSkBZWTC4B3SnlIBtALrkA3uQBEEa+QC+ChWKLEqANko4NxC8XJAygBmQy8sABZyOTZOXn4hAB4qHHUuJTVyLmoJATB2KAAbLkVFVyCQsMoo7WkuCAATAHkYQoBPAGV2CBhko3VWDPVc4QFi6gB1ZCgEEtZjUlMXYgcgA=)

Note that this currently compiles and runs, so fixing this bug would be a breaking change.

**Comment by jjonescz** [comment]
I think most expression trees would compile and run fine. A problematic one was for example with `default(RefStruct)` constant because that would be passed into `Expression.Constant` as an `object` parameter and hence boxed - as explained in https://github.com/dotnet/roslyn/issues/30776#issuecomment-434126806.

**Comment by jaredpar** [comment]
Bringing up part of the conversation from that issue

> However the Expression.Constant(object, Type) requires the default(Struct1) to be boxed into object, which ref structs don't support. 

In this case though `default` isn't a constant, it's a value. Is it just a terminology issue and we typically represent using the `Expression.Constant` API? 

@RikkiGibson as he wrote the statement I'm questioniing 😄

**Comment by agocke** [comment]
> I think most expression trees would compile and run fine.

I'm not sure about most. I think the problematic cases are where ref structs are used as literals (the constant case) or captured. My recollection here was rather than try to enumerate all the problematic cases, we just banned them entirely.
