### ISSUE TITLE
VS cant format

### ISSUE THREAD

**Issue by bcheung4589** [dotnet/roslyn#74142]
![image](https://github.com/dotnet/roslyn/assets/26156344/f4e8ada9-9e1e-4d23-826a-0cd9f0849112)
![image](https://github.com/dotnet/roslyn/assets/26156344/9df87457-0eba-46ef-896f-faa8ab2bc43b)

Cant believe VS has trouble formatting <table /> because I use a component in a table? Is VS telling us we arent supposed to use components in tables? What is this nonsense?

**Comment by bcheung4589** [comment]
Proof VS cant handle the components:
![image](https://github.com/dotnet/roslyn/assets/26156344/e522db94-2dde-48c3-814e-c2bc4f976458)

**Comment by CyrusNajmabadi** [comment]
This is not Roslyn. You might want to report an issue from within VS.  It will create a report on developercommunity that can get routed to the right game.
