### ISSUE TITLE
Create LangVersion 13

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#74194]
Now that `main` is VS  17.12 and .NET 9 it's time to add `LanguageVersion.CSharp13`. 

When doing this work please keep the `ref struct` interfaces support behind the preview flag.

**Comment by CyrusNajmabadi** [comment]
lmk when this happens @jcouv .  there's some ide code to update.  Tnx! :)

**Comment by jcouv** [comment]
@CyrusNajmabadi  I'm aiming to do this today

**Comment by CyrusNajmabadi** [comment]
Perfect!

**Comment by jaredpar** [comment]
Can we close now that #74215 is merged?

**Comment by jcouv** [comment]
Closing as done
