### ISSUE TITLE
Local does not appear while debugging

### ISSUE THREAD

**Issue by rchande** [dotnet/roslyn#742]
In my branch https://github.com/rchande/roslyn/tree/EventOverriding, while debugging the test "EventsNotOffered" in OverrideCompletionProviderTests.vb, the local "text" does not appear in the locals window. If I try to evaluate it in a Watch or the Immediate Window, I see ``` error BC30112: 'Text' is a namespace and cannot be used as an expression.```

**Comment by rchande** [comment]
@amcasey may find this interesting.

**Comment by amcasey** [comment]
Works on my box.  Please retry with current binaries.
