### ISSUE TITLE
IntelliSence show identifer as a type, but compiler interpret it as a property name

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/roslyn#7420]
I have a code like this:

``` cs
class Value
{
    public const int Zero = 0;
}

class Test
{
    public string Value { get; set; }
}
```

and I want to add a property `Property` to a Test class and initialize it from Value::Zero:

![image](https://cloud.githubusercontent.com/assets/795200/11743345/b864c5a6-a017-11e5-9387-a038d7032021.png)

Intellisence list shows me, that `Value` mean a class `Value`, but it will be interpreted by a compiler as property `Value`:

``` cs
class Value
{
    public const int Zero = 0;
}

class Test
{
    public string Value { get; set; }

    public int Property { get; set; } = Value.Zero;
}
```

> error CS0236: A field initializer cannot reference the non-static field, method, or property 'Test.Value'.

May be, icon on the `Value` in an intellisence list should be a "property icon" and tooltip[ should show "property Value"?

**Comment by Phrohdoh** [comment]
For what it's worth: I do not see an issue here regarding the compilation failure.
`Value.Zero` is not `class Value`'s `Zero` member.
`class Value` is not static nor is `Zero`.

I can agree that the intellisense looks to be incorrect.

**Comment by leppie** [comment]
@Phrohdoh Of course it is usable. You just need to use `global::Value.Zero`

**Comment by Phrohdoh** [comment]
Sure, but given his examples I think it is pretty clear how he is wanting to use the value.

**Comment by ViIvanov** [comment]
@Phrohdoh Yes, this is intellisence issue, not compiler issue.

**Comment by Pilchie** [comment]
I suspect we get both symbols back from the compiler, and don't show the property because it isn't valid, but also don't recognize that it shadows the type in this case.

**Comment by CyrusNajmabadi** [comment]
Need info on if this is actually an issue for the ecosystem.

**Comment by ViIvanov** [comment]
The behavior remains the same:

![image](https://user-images.githubusercontent.com/795200/217178750-c6c4bea2-79e3-4b35-a63e-e5b76c5c3003.png)

**Version info**:
Microsoft Visual Studio Enterprise 2022
Version 17.5.0 Preview 5.0
VisualStudio.17.Preview/17.5.0-pre.5.0+33326.253
`csc -version`: 4.4.0-6.22608.27 (af1e46ad)
