### ISSUE TITLE
Duplicate item metadata present in generated editorconfig with CompilerVisibleItemMetadata

### ISSUE THREAD

**Issue by AR-May** [dotnet/roslyn#74234]
---
**Issue moved from dotnet/msbuild#10309**
- Please respond to @kzu.

---

_From @kzu on Friday, June 28, 2024 5:43:42 PM_

### Issue Description

Suppose you have three totally independent packages that provide analyzers that leverage additional files to do some processing. Additionally, all packages consume the same file types (i.e. `.resx` files).

The first package might just add the files as `AdditionalFiles` and check for file extension inside the analyzer:

```xml
  <ItemGroup>
    <AdditionalFiles Include="@(EmbeddedResource)" />
  </ItemGroup>
```

The second package, however, might use an additional piece of metadata for the embedded resources to distinguish them, and thus has a slightly different version:

```xml
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="SourceItemType" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" SourceItemType="EmbeddedResource" />
  </ItemGroup>
```

A third one might even use another totally different metadata annotation on the same items for its own purposes:

```xml
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Foo" />
    <AdditionalFiles Include="@(EmbeddedResource)" Foo="Bar" />
  </ItemGroup>
```

The resulting editorconfig will currently now look like the following:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = Bar
```

Regardless of the somewhat unintuitive behavior when retrieving this item's metadata from the analyzer using the `AnalyzerConfigOptionsProvider` for that file (will you get the empty value or `EmbeddedResource` when asking for `SourceItemType` with `.TryGetValue("build_metadata.AdditionalFiles.SourceItemType", out var value)`?), if you have many files and multiple packages leveraging compiler item metadata, this duplication can make the editorconfig unnecessarily large (and potentially impossible to get the right value, depending on whichever behavior Roslyn itself provides for such duplicated entries).

### Steps to Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Some nuget package via .targets -->
  <ItemGroup>
    <AdditionalFiles Include="@(EmbeddedResource)" />
  </ItemGroup>

  <!-- Some other package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="SourceItemType" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" SourceItemType="EmbeddedResource" />
  </ItemGroup>

  <!-- A third package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Foo" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" Foo="Bar" />
  </ItemGroup>

</Project>
```

### Expected Behavior

Emitted editorconfig similar to:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.Foo = Bar
```

### Actual Behavior

Emitted editorconfig is actually similar to:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = Bar
```

### Versions & Configurations

17.11.0.27902

**Comment by jaredpar** [comment]
@chsienki PTAL

**Comment by chsienki** [comment]
Ok, yeah I see where this is coming from, and we'll need to do the de-duplication in the MSBuild layer that outputs these files.

**Comment by iyilm4z** [comment]
Is there any workaround for a project that depends on your package?

**Comment by iyilm4z** [comment]
@arunchndr Is there any workaround for a project that depends on your package?

**Comment by chsienki** [comment]
So I took a look into this, and I don't think there is anything we can correctly do here.

For the empty entries it's difficult because MSBuild doesn't give us a way to differentiate between a missing value, or an explicitly empty value. For items that have the same `include` but conflicting metadata values, I don't see how it would be possible to decide which one 'wins'. We could theoretically join them together with a `;` or something, like MSBuild does, but the receiver would have to be aware of that behavior and changing it now is more likely to just break the consumer. Having it be the last declared value (the behavior today) is at least deterministic, and you can fairly easily understand it by examining the generated editorconfig.


The correct solution here is to use a different item type, so that it can be disambiguated.

In the above example it would instead be something like 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Some nuget package via .targets -->
  <ItemGroup>
    <AdditionalFiles Include="@(EmbeddedResource)" />
  </ItemGroup>

  <!-- Some other package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="OtherPackageFiles" MetadataName="SourceItemType" />

    <!-- NOTE: added again, but to another item collection that contains the metadata -->
    <AdditionalFiles Include="@(EmbeddedResource)" />
    <OtherPackageFiles Include="@(EmbeddedResource)" SourceItemType="EmbeddedResource" />
  </ItemGroup>

  <!-- A third package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="ThirdPackageFiles" MetadataName="Foo" />
    <!-- NOTE: added again with another collection for the metadata -->
    <AdditionalFiles Include="@(EmbeddedResource)"  />
    <ThirdPackageFiles Include="@(EmbeddedResource)" Foo="Bar" />
  </ItemGroup>

</Project>
```

Will produce something like:

```ini
[.../Resources.resx]
build_metadata.OtherPackageFiles.SourceItemType = EmbeddedResource
build_metadata.ThirdPackageFiles.Foo = Bar
```

And each package would just read the metadata for the specific item it declared.


Closing this as wont-fix.

**Comment by kzu** [comment]
Makes sense. Thanks for taking a look!
