### ISSUE TITLE
IntelliCode-suggested completions don't escape keywords properly

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/roslyn#74253]
**Version Used**:
Latest `main`

**Steps to Reproduce**:
Given that AI is involved, I don't think there is a 100% reliable way to reproduce the bug, But I can somewhat consistently see it using the following snippet:
```cs
void M()
{
    var @params = GetParams();
    UseParams($$
}

void UseParams(MyParams @params) { }

MyParams GetParams() => new();

class MyParams
{
}
```
Invoke completions at `$$`. You will see a bug when there is a starred item at the top of the list.

**Expected Behavior**:
Starred item is properly escaped with `@`.

**Actual Behavior**:
`params` is not escaped, so there is a compiler error if I accept the suggestion:
![devenv_WvFlneZLmh](https://github.com/dotnet/roslyn/assets/70431552/8314d332-3191-4eba-a5f6-bcf1857c4b04)
However, the original completion item, which was picked by the IntelliCode _is_ actually escaped:
![devenv_QFyzc6VTkD](https://github.com/dotnet/roslyn/assets/70431552/8395a356-d5f3-41be-9425-522f63f4a235)

**Comment by Cosifne** [comment]
🤔It might not related to Roslyn. E.g. Roslyn is only providing the completion structure code, the real source is from Copilot or Intellicode.
Assigned to Gen for more investigation.

**Comment by CyrusNajmabadi** [comment]
Closing as external.  This is intellicode @dpugh
