### ISSUE TITLE
SA1200 (stylecop analyzer rule) not working in live analysis, but works fine for build

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#7427]
See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1939#issuecomment-163775747 for repro steps

I wasn't able to repro this for a default C# project - SA1200 works fine for it. The repro is consistent on StyleCop solution.

Implementation of SA1200 registers a SyntaxNode action with SyntaxKind.CompilationUnit, and that doesn't seem to be getting invoked during live analysis for StyleCop solution.

**Comment by mavasani** [comment]
@sharwell This seems to be due to a race condition: https://github.com/dotnet/roslyn/issues/7446. SA1200 seems to be badly affected as it works on syntax nodes at top level of the files.

I'll keep this bug on me and validate SA1200 works after 7446 is fixed.

**Comment by mavasani** [comment]
I'll just used the resolved issue #7446 for verification.

**Comment by ScottGuymer** [comment]
Has there been any update or workaround on this?
