### ISSUE TITLE
IDE0031: Null check can be simplified. Fix doesn't work if accessing a property wrapped in unnecessary parentheses.

### ISSUE THREAD

**Issue by Wirox** [dotnet/roslyn#74273]
**Version Used**: VS 2022 17.10.3

**Steps to Reproduce**:
1. Create a new solution and project (Console App, .NET 8.0)
2. Replace default code with `int? Length(Array array) => array != null ? (array.Length) : null;`
3. Try to apply the fix for IDE0031.

You can also use this code instead of steps 1 and 2: [Repro.zip](https://github.com/user-attachments/files/16108527/Repro.zip)

![repro](https://github.com/dotnet/roslyn/assets/24973388/27e9a358-df97-451f-8bf5-43644eb9f896)

**Diagnostic Id**: IDE0031: Null check can be simplified

**Expected Behavior**: The fix should work and preview should show the changes.

**Actual Behavior**: Applying the fix doesn't do anything. Preview doesn't show anything.
If accessing a method instead of a property (such as `array.ToString()`) or if unnecessary parentheses are removed, the fix works properly.

**Comment by Orachor** [comment]
Hey, I'd like to take a stab at this if possible :)

**Comment by CyrusNajmabadi** [comment]
Go for it :)
