### ISSUE TITLE
BlockOperations don't get generated in some cases

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7428]
If I have a simple `Sub Foo()` and I register for an OperationBlockAction, I get a BlockOperation which has a LabelStatement in it (the label shouldn't be there and that's bug https://github.com/dotnet/roslyn/issues/7397). If I have `Public Overrides Sub Foo()` then there is no BlockOperation and the LabelStatement is returned directly in the `OperationBlockAnalysisContext.OperationBlocks` array. 

Expected: Consistent tree structure here in both cases.

**Comment by srivatsn** [comment]
This also happens for a finalizer block in C#:

```csharp
class foo
{
   ~foo()
   {
   }
}
```

`OperationBlockAnalysisContext.OperationBlocks` produces a single operation of Kind `SequencePointWithSpan` instead of Block.

**Comment by srivatsn** [comment]
This also happens for operator methods in VB:

```VB.NET
Imports System

Public Class C
    Public Shared Operator =(c1 As C, c2 As C) As C
        Throw New Exception()
    End Operator
    Public Shared Operator <>(c1 As C, c2 As C) As C
        Throw New Exception()
    End Operator
End Class
```

**Comment by jinujoseph** [comment]
Can we validate this with new API's

**Comment by mavasani** [comment]
Verify does not repro anymore for any of the mentioned C# or VB cases.
