### ISSUE TITLE
Hitting Debug.Assert in the compiler (TypeWithAnnotations.cs)

### ISSUE THREAD

**Issue by davidwengier** [dotnet/roslyn#74297]
Hitting an assert here locally, when opening Razor.sln on my branch: https://github.com/dotnet/roslyn/blob/0971b49f5852a2ed2d091c3e5343a43e909b10ec/src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs#L55

Looks like it's caused by having an error type with a nullable annotation, in this case `SignatureHelp?`. Dump file: https://microsoftapc-my.sharepoint.com/:u:/g/personal/dawengie_microsoft_com/Ed8PckcjQGJAjwWdgREarC0BgbhVRrmPfFAXrJ3JOBHpyA?e=9kpYEH

**Comment by jjonescz** [comment]
Looks like the `System.Nullable<T>` type itself cannot be found. I don't know why that is happening in the first place - maybe the project is loading incorrectly in the IDE somehow? But I can at least modify the assert to not fail when that happens.
