### ISSUE TITLE
Assert failure in AnalyzerDriver

### ISSUE THREAD

**Issue by Cosifne** [dotnet/roslyn#74315]
When doing daily debug & test I hit this assert failure.
![image](https://github.com/dotnet/roslyn/assets/24360909/43896966-ce07-4327-ac5b-4bb729a96ecd)
Dump: \\mlangfs1\public\shech\Dumpfile\AnalyzerDriverAssert.dmp

**Comment by 333fred** [comment]
The failure here is that the AnalyzerDriver is not handling when the primary constructor base call is invalid. Attempting to run the driver over a compilation that is just `record B(int I) : A(I);`, with no definition for `A`, should reproduce this issue.

**Comment by CyrusNajmabadi** [comment]
ignore previous.  i can hit this.  it was just getting swallowed by another part of the stack.
