### ISSUE TITLE
Avoid recommending synthesizing record parameters in static context within the record

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#74327]
## Version Used
VS 2022 Version 17.10.3
Roslyn 4.10.0 (04fb39164c99c)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

In the following code:
```csharp
public record class Point(int X, int Y)
{
    public static Point Parse(string line)
    {
        // $$
    }
}
```

place the cursor at `$$`, and type `X`. Examine the suggested symbols.

## Expected Behavior

None of the record's primary constructor parameters appear in the suggestions.

## Actual Behavior

The suggestions include primary constructor parameters within a static context. Note that only parameters that are used to synthesize properties within that record type appear.

**Comment by CyrusNajmabadi** [comment]
If this is fixed, make sure to not break nameof
