### ISSUE TITLE
Avoid recommending get-only properties without valid settable options in object initializer

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#74331]
## Version Used
VS 2022 Version 17.10.3
Roslyn 4.10.0 (04fb39164c99c)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

Consider the following code:

```csharp
public sealed class FreightModel
{
    public double WeightKg { get; init; }
    
    public string Name { get; } = "some name";
}

public class ModelFactory
{
    public FreightModel Create(double weight)
    {
        return new()
        {
            // $$
        };
    }
}
```

In the above example code, place the cursor at `$$`, type `Na`, and notice the autocomplete result including the `Name` get-only property.

## Expected Behavior

We don't get the get-only string property

Reason: we don't need a string get-only property the object initializer. We cannot use that property in any way. The only scenario in which we want to show get-only properties is when they are set using an object or list initializer without the construction of a new instance. For example:
```csharp
public class Thing
{
    public List<string> SomeList { get; } = [];
}

new Thing()
{
    // we are only adding the string below to the list, without setting the property itself
    SomeList = 
    {
        "some string within the list"
    }
}
```

## Actual Behavior

The get-only property's name is suggested.

## Notes

Properties can be set in the following ways:
- Setting their value directly to an instance expression
- Setting their nested properties with an object initializer block
- Adding elements with a list initializer block

When none of the above are applicable, the name of the property should not be suggested.

**Comment by CyrusNajmabadi** [comment]
Make sure to not break these showing up in patterns

**Comment by CyrusNajmabadi** [comment]
@Rekkonnect please update this pr.
