### ISSUE TITLE
Gracefully handle incomplete property setter in object initializer

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/roslyn#74348]
## Version Used
VS 2022 Version 17.10.3
Roslyn 4.10.0 (04fb39164c99c)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

```csharp
public class Thing
{
    public int Key { get; set; }
    public string? Value { get; set; }
}

public class Using
{
    public static Thing CreateThing(int key, string? value)
    {
        return new()
        {
            Key = key,
            // $$
        };
    }
}
```

In the code above, place the cursor at `$$`, and type `Value`. Notice that `Value` is not bound to the property of `Thing` and is instead treated as an expression.

Example image:
![image](https://github.com/dotnet/roslyn/assets/8298332/0adf17fa-3852-4166-a54e-74eec4d844f4)

## Expected Behavior

Despite lacking the setter, the member is properly bound.

## Actual Behavior

The part of the object initializer is not handled as a member setter, and so the member appears unbound.

**Comment by CyrusNajmabadi** [comment]
I'm not really understanding the issue. What happens if you add an equals after the member name?

**Comment by Rekkonnect** [comment]
When you add `=` it correctly binds to the property. When you don't add it however it breaks. Given that above we have other member setters, it should be inferred that we are expecting the first identifier to be an object member.

**Comment by Rekkonnect** [comment]
This is a rushed mistake on my end, however it doesn't change much. The bug here isn't the type mismatch, but the lack of recognition of Value as the settable property.

**Comment by CyrusNajmabadi** [comment]
This is a request for slightly better recovery in error cases. 

I'm personally not opposed to it *if* the change is reasonably scoped and sized.  If it's a few lines you make this work, cool.  If it's a lot of effort and complexity, it's likely not worth it. 

Tentatively marking up for grabs. But ultimately up to compiler team if they would accept a change here

**Comment by CyrusNajmabadi** [comment]
Cc @333fred to make sure I'm not stepping on any toes with the above advice. Have talked with @Rekkonnect offline on how to navigate this issue. Thanks!
