### ISSUE TITLE
Rename session randomly dismisses itself

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74347]
**Version Used**: VS 17.11.0 P3

The issue first appeared either in this or the most recent previous preview release.

**Steps to Reproduce**:
Start a rename session and start typing new name.

It happens randomly, sometimes multiple times in a row, sometimes rarely.

See the second try:

https://github.com/dotnet/roslyn/assets/9047283/56430a59-3ec3-45c6-8b6e-300771cba39f

(I have GitHub Copilot enabled as well, perhaps it is related to the newly introduced rename suggestions?)

**Diagnostic Id**:
N/A

**Expected Behavior**:
The rename session stays active while I type the new name and commit it.

**Actual Behavior**:
The rename session dismisses itself after typing the first character (or by itself?, I'm not sure what is the trigger).

**Comment by CyrusNajmabadi** [comment]
I'm also reproing this.  Was doing a bunch of renames yesterday and about one in five would just randomly dismiss.

**Comment by Cosifne** [comment]
I merged a potential fix to this problem, so I am going to close this issue.
If anyone see this repro feel free to open it.

**Comment by grallbring** [comment]
Still happens to me using version 17.12.3:
https://github.com/user-attachments/assets/d9a07178-60fe-4abc-a73a-efcf0ef504cc

**Comment by Peter-Juhasz** [comment]
@grallbring The workaround that worked for me was to disable either in the Rename window or under `GitHub > Copilot > Enable rename suggestions`.

Although I have not enabled it yet since then and I'm on 17.13 P2, I have never encountered this issue since then again.

**Comment by CyrusNajmabadi** [comment]
@AmadeusW 	@gundermanc  ^

**Comment by SirViver** [comment]
I also still have this issue on 17.12.3 and changing GitHub Copilot rename suggestions doesn't influence the problem for me. I think it has more to do with source generators (erroneously?) constantly re-running in the background (in my case the MVVM Community Toolkit ones), which constantly modifies/invalidates the Roslyn model, resulting in the rename to auto-dismiss.

If you try to do a classic rename by just renaming the thing and then invoking the Rename action you get following error:
> Rename operation could not complete due to external change to workspace

Also VS seems to massively memory leak at this point, for example right now growing to 15GB memory usage, but I'm 100% sure its related.

**Comment by CyrusNajmabadi** [comment]
@SirViver please file a vs issue from within vs.  It will collect perf traces and memory dumps to let us see what is going on.

**Comment by SirViver** [comment]
I've now logged an issue from within VS, including a whole bunch of dumps/extra traces, plus a video recording showing the behavior:

https://developercommunity.visualstudio.com/t/Rename-dialog-closes-itself-shortly-afte/10827608

**Comment by LWChris** [comment]
I have this issue as well and got the impression that it is related to when a background process is still processing the previous rename (updating caches or CodeLens, recompiling for analyzers, etc.) If I wait "long enough" (30 seconds) between renames, from memory I'd say it always works. If I attempt two renames in quick succession, I remember lots of instances where the second rename does nothing. But I'm not sure the rename dialog actually disappears for me. I'd say it stays open, but when pressing Enter it closes the popup but doesn't apply the new name.
