### ISSUE TITLE
Infrastructure for shipping experimental language features

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7434]
There is interest in seeing if we can ship experimental features in our normal shipping binaries.  This would all be disabled by default but have the ability for customers to opt into explicitly.   This would be advantageous because it would allow us to get real feedback from customers about features under active development.  In particular we hope it would help us to resolve difficult decisions in the design with real customer feedback.  

This would require:
- Ensure experimental language versions were opted into explicitly.
- Ensure experimental language features don't ship in the public API.  
- Ensure there is a clear statement of guarantees here: Explicitly there are no guarantees with experimental features.  The language is free to change or remove them at any time.  

Note: at this point this is an **exploratory** item.

**Comment by Inverness** [comment]
How would users opt-in to these features?

My first thought is to use special symbols with #define. That way you can easily opt-in on a project-wide or per-file basis.

**Comment by diryboy** [comment]
This is interesting, :+1:

**Comment by paulomorgado** [comment]
:+1:

**Comment by jaredpar** [comment]
@Inverness 

The opt-in would be on a per project basis by a command line switch / MSBuild property.  It would be a mechanism similar to the `/langversion` flag.

**Comment by AdamSpeight2008** [comment]
Why not just have an `/experimental` command switch? So it requires both the `/langversion` and `/experimental` switches to be set before allowing to compile experimental features.

**Comment by jaredpar** [comment]
@AdamSpeight2008 it's not that simple unfortunately.  It's definitely that simple from the perspective of the compiler.  The difficulty is everything else: API, editing experience, testing, etc ...

**Comment by jaredpar** [comment]
Closing for now as this is no longer an explicit goal of the compiler.  Going to be focusing on point releases instead.
