### ISSUE TITLE
[Test Failure] FileHandle is locked. -  CrossLanguage.xml

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#7435]
http://dotnet-ci.cloudapp.net/view/roslyn-internal/job/roslyn-internal_future_win_vsi_p1/58/

it looks like devenv.exe is the one holding onto the filehandle. and test screenshot (http://dotnet-ci.cloudapp.net/view/roslyn-internal/job/roslyn-internal_future_win_vsi_p1/58/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CrossLanguage.html) shows that VS is still having the project opened in VS. test seems flaky

...
Individual TAO Test Failure

Failing integration tests: CrossLanguage.xml 
Indication 1 

Failed to delete project files after 10 seconds

Failed to create a test project because a previous project with the same name could not be deleted. Check FileHandlesDump.txt to see which process is to blame. This can happen when the build machine is under heavy load. Please notify @dotnet/roslyn-infrastructure and let them re-run this test suite.
Indication 2 
...

Handle v3.42
Copyright (C) 1997-2008 Mark Russinovich
Sysinternals - www.sysinternals.com

devenv.exe         pid: 2536   18C4: C:\Users\dotnet-bot\AppData\Local\Temp\VBProj
devenv.exe         pid: 2536   286C: C:\Users\dotnet-bot\AppData\Local\Temp\VBProj
devenv.exe         pid: 2536   2CA0: C:\Users\dotnet-bot\AppData\Local\Temp\VBProj

**Comment by davkean** [comment]
See: https://github.com/dotnet/roslyn/issues/7256.

**Comment by Pilchie** [comment]
This is just a dupe, right?

**Comment by heejaechang** [comment]
I believe so.
