### ISSUE TITLE
constant string allow conversions

### ISSUE THREAD

**Issue by LeonSchourek** [dotnet/roslyn#74369]
## Background and Motivation

I woold like to use numbers in const Strings
i could use that for example for writing sql querrys

## Proposed API
allow const values to be convertet to const strings 

## Usage Examples

``` C#
const double dpi = 2 * 3.14;
const string nerg = $"double of PI is:{dpi}";
```
``` C#
const bool debug = false;
const string debugtext = $"debug enabled: " + debug;
```
``` C#
public enum LivingType
{
	Human,

	Animal
}

public class LivingObject
{
	public string name {  get; set; }
	public LivingType type { get; set; }
}
const string query = $"""
SELECT
	*
FROM
	{nameof(LivingObject)}DB
WHERE
	{nameof(LivingObject.type)} = {(int)LivingType.Human}
""";
```
## Risks

no risks

**Comment by huoyaoyuan** [comment]
Language requests goes to https://github.com/dotnet/csharplang/discussions .

Note that interpolated strings are culture-aware. See https://github.com/dotnet/csharplang/discussions/177 and https://github.com/dotnet/csharplang/discussions/384 .
