### ISSUE TITLE
IEventSymbol.DeclaringSyntaxReferences Syntax is VariableDeclaratorSyntax not EventFieldDeclarationSyntax

### ISSUE THREAD

**Issue by LWehmschulteAtRosenxt** [dotnet/roslyn#74379]
**Version Used**:
Microsoft.CodeAnalysis.CSharp" Version="4.9.2"
Microsoft.CodeAnalysis.Analyzers" Version="3.3.4"

**Steps to Reproduce**:

1. Create a class with a simple event declaration
2. Get Event Symbols from class

```cs
// Dummy Class with Event
partial class SomeClass
{
    public event EventHandler? SomeEvent;
}
```

```cs
// SourceGenerator
private static void GetEvent(ITypeSymbol classSymbol) {
    classSymbol
        .GetAllMembers()
        .Where(x => x.Kind == SymbolKind.Event)
        .OfType<IEventSymbol>()
        .Where(x => x.DeclaredAccessibility == Accessibility.Public)
        .Where(x => !x.IsStatic)
        .ToList()
        .ForEach(evt =>
        {
            var syntax = evt.DeclaringSyntaxReferences.First().GetSyntax(); // VariableDeclaratorSyntax
        });
}
```
![image](https://github.com/user-attachments/assets/ca9aa92b-7b47-4fc2-bef9-d897f1fe55cf)

**Expected Behavior**:
The syntax variable should be of type `EventVieldDeclaration`

**Actual Behavior**:
See the syntax variable is of type `VariableDeclaratorSyntax` and not of type `EventFieldDeclarationSyntax`

**Comment by CyrusNajmabadi** [comment]
This is by design. Like fields, there can be multiple events declared in a single  declaration.  For example:

```c#
class C
{
    event Action A, B;
}
```

So the declaring syntax is the declarator.
