### ISSUE TITLE
Visual Studio 2022 error list doesn't show errors from build failures in Build + Intellisense view

### ISSUE THREAD

**Issue by twest820** [dotnet/roslyn#74380]
**Version Used**:  17.10.3 and .4

**Steps to Reproduce**:

1. Open Visual Studio with default settings.
2. Try to build a broken .NET 8 C# SDK-style project (`<Project Sdk="Microsoft.NET.Sdk">`).

This is a regression to behavior much like https://github.com/dotnet/roslyn/issues/16545. Persists through update from 17.10.3 to 17.10.4, repair of Visual Studio installation, reset to default settings, and deletion of solutions' .vs folders. Visual Studio's long exhibited various levels of flakiness around this from build to build (_e.g._ https://github.com/dotnet/roslyn/issues/16545) but with 17.10.3+ I'm getting a total break. Unsure if 17.10.2 is also affected.

https://github.com/dotnet/roslyn/issues/73801 mentions analogous issues with warnings in 17.10.0, but only for legacy projects. (There's also a bunch of StackOverflow, VS Dev Community, Microsoft Learn, and Reddit threads covering a many similar issues across various project types. Those hits I'm getting are mostly from 2020–2023 but go as far back as 2010.)

**Expected Behavior**:
Build errors are shown in both error list views which include them.

**Actual Behavior**:
* Build errors are not shown unless the error list's dropdown's changed to Build from Build + IntelliSense.
* Setting Tools -> Options -> Text Editor -> C# -> Advanced -> Show compiler errors and warnings for: Entire solution isn't honored by showing the errors (open files is the default but background analysis defaults to the entire solution, so IntelliSense should be getting to look at the affected files and be thus able to report the errors to the error list when enabled for the entire solution).

The Build + IntelliSense view does show errors IntelliSense finds in open files. So a basic workaround is to change the Build + IntelliSense dropdown to Build Only, open all the affected files (going through the build output and double clicking the errors works too), and then change back to Build + IntelliSense (or IntelliSense Only). The Build + IntelliSense view is supposed to automate this process, though.

**Comment by CyrusNajmabadi** [comment]
Closing as i do not repro this and this section was rewritten.
