### ISSUE TITLE
Parameter info/signature help session won't start

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74383]
**Version Used**: VS 17.11.0 P3

**Steps to Reproduce**:

https://github.com/user-attachments/assets/20ab7d52-5225-4185-b9d0-d25edf00fee3

Unfortunately, can't consistently reproduce it. Similarly to #73124, sometimes it is completely broken, sometimes it works.

**Diagnostic Id**:

N/A

**Expected Behavior**:

Parameter info/signature help session is always started and displayed.

**Actual Behavior**:

Neither typing `(` or manually selecting `Edit > IntelliSense > Parameter Info` starts the signature help session.

**Comment by CyrusNajmabadi** [comment]
this doesn't currently repro for me:

![image](https://github.com/user-attachments/assets/f94b95be-da20-4520-adda-573478a00519)

**Comment by CyrusNajmabadi** [comment]
Fix available.
