### ISSUE TITLE
`ref` modifier keyword is missing from completions for `ref struct` primary constructor parameter definition

### ISSUE THREAD

**Issue by Peter-Juhasz** [dotnet/roslyn#74386]
**Version Used**: VS 17.11.0 P3

**Steps to Reproduce**:

```cs
ref struct S($$);
```

![image](https://github.com/user-attachments/assets/eb3611a3-4402-4938-8b46-d1de4a68f3b5)

**Diagnostic Id**:

N/A

**Expected Behavior**:

`ref` keyword is listed as a completion, as it is present using a regular constructor.

**Actual Behavior**:

`ref` is missing.

**Comment by CyrusNajmabadi** [comment]
Not repro:

![Image](https://github.com/user-attachments/assets/199c2571-c9e6-4592-90ee-ad25c26cf2cc)
