### ISSUE TITLE
Saving an AdditionalFiles document in Balanced mode fails to trigger source generator

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn#74395]
**Version Used**: VS 17.12 (35114.17.main)

**Steps to Reproduce**:

0. Configure C# Advanced to (its default) "Balanced" source generator mode.
1. Create a new C# console project
2. Add a package reference to Microsoft.Windows.CsWin32
3. Create a NativeMethods.txt file and give it the content: `GetTickCount`
4. Open Program.cs and write code to consume it.
5. Reactivate the NativeMethods.txt file and clear the content.
6. Save the file.

**Expected Behavior**:

Saving the NativeMethods.txt file, per the wording of the Balanced source generator mode, should trigger source generation, causing an error in Program.cs.

**Actual Behavior**:

Saving the NativeMethods.txt does _not_ trigger source generation. Switching to Program.cs and saving it (though it has no unsaved changes) is necessary for the source generator to run again.

**Proposal**

Saving files in the AdditionalFile item list should trigger source generation the same way that saving Compile items does.

**Comment by CyrusNajmabadi** [comment]
Yes. Def a bug.
