### ISSUE TITLE
EE: Missing compile error when evaluating base class method

### ISSUE THREAD

**Issue by pnelsonmsft** [dotnet/roslyn#7439]
From External Feedback https://vs-feedback/comment/515306:

The CLR doesn't support real func eval of methods without doing virtual dispatch.  The legacy EE shows an error message when a base class method is evaluated.  The new EE shows the wrong value.

**Repro:**
Debug the following code:
```C#
static class Program
{
    static void Main()
    {
        A a = new A();
        a.DoSomething();
    }
    class B
    {
        public override string ToString() => "B";
    }
    class A : B
    {
        public override string ToString() => "A";

        public void DoSomething()
        {
            string s = base.ToString();
            System.Diagnostics.Debugger.Break();
        }
    }
}
```
Evaluate "base.ToString()"

**Expected (Legacy EE behavior):** Error: A call to a virtual method or property through the base keyword will always call the most derived function while debugging.
**Actual:** "A"

**Comment by KevinH-MS** [comment]
We should see what it would take to just make this work (i.e. ask the CLR to support non-virtual calls).

**Comment by pnelsonmsft** [comment]
Started offline conversation with Noah about this - he doesn't appear to be on GitHub.

**Comment by Przemyslaw-W** [comment]
possible dup - #3723

**Comment by KevinH-MS** [comment]
Yes, dup.  Thanks, @Przemyslaw-W!
