### ISSUE TITLE
error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1 .0 to 8.0

### ISSUE THREAD

**Issue by bouchraRekhadda** [dotnet/roslyn#74410]
Building an ASP .NET Core project with `<GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile>` using .NET SDK produces the error
> error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1
.0 to 8.0

### To Reproduce
A reproduction sample is available at https://github.com/bouchraRekhadda/web-sample, to reproduce, **make sure you build using .NET 8 SDK** : `dotnet build WebProject.csproj`

#### Excpected behavior

> Build succeeded. 0 Warning(s) 0 Error(s)

#### Actual behavior
> CSC : error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1
.0 to 8.0.

### Further technical details
- Include the output of `dotnet --info`
>.NET SDK:
> Version:           8.0.202
> Commit:            25674bb2f4
> Workload version:  8.0.200-manifests.8cf8de6d
>
>Runtime Environment:
> OS Name:     Windows
> OS Version:  10.0.22631
> OS Platform: Windows
> RID:         win-x64
> Base Path:   C:\Program Files\dotnet\sdk\8.0.202\
>
>.NET workloads installed:
>There are no installed workloads to display.
>
>Host:
>  Version:      8.0.3
>  Architecture: x64
>  Commit:       9f4b1f5d66
>
>.NET SDKs installed:
>  6.0.418 [C:\Program Files\dotnet\sdk]
>  8.0.202 [C:\Program Files\dotnet\sdk]
- The IDE: Visual Studio 17.9.3

**Comment by bouchraRekhadda** [comment]
>Ok, so then the request here is for the Roslyn targets to create this file using a shorter name

That and understanding why this wasn't an issue on .NET 6 or 8.0.1xx SDKs

**Comment by baronfel** [comment]
@jjonescz may be able to shed some light on that - my guess is that this diagnostic changed or wasn't enabled on those versions. New generators and analyzers are changed with every release, it's not something I'd worry too much about.

**Comment by jjonescz** [comment]
> my guess is that this diagnostic changed or wasn't enabled on those versions

Yes, this diagnostic was broken at some point and fixed in https://github.com/dotnet/razor/pull/9605.

**Comment by 333fred** [comment]
Can I ask why you can't turn on long path support in your CI/CD? I'd need to see the specific paths involved here, but I don't think we can really change much about them here. I expect the file name is `<project path>\.globalconfig`, and there's not exactly room for changing that.

**Comment by bouchraRekhadda** [comment]
> I expect the file name is <project path>\.globalconfig, and there's not exactly room for changing that.

The path is `<ci/cd_path>\.build\obj\net6.0-windows\<project>\x64\Release\net6.0-windows\<project>.GeneratedMSBuildEditorConfig.editorconfig`. 
(**PS**: the `obj\net6.0-windows` is something we have customized for another reason)

**Comment by chsienki** [comment]
@bouchraRekhadda It's possible to control the output location of the generated config file via the `<GeneratedMSBuildEditorConfigFile>` property. I would suggest you set it to something shorter, but ensure its unique per project so generated files don't overwrite each other. For example you might use something like

`<GeneratedMSBuildEditorConfigFile>cipath\.build\$(MSBuildProjectName).gen.config</GeneratedMSBuildEditorConfigFile>`


Completely disabling the file will cause the Razor generator to break in unexpected ways even if we didn't have the LangVersion error.

**Comment by 333fred** [comment]
Going to close this out as by-design.
