### ISSUE TITLE
[Bug]: funny interaction between verbatim strings and the preprocessor

### ISSUE THREAD

**Issue by bottle2** [dotnet/roslyn#74415]
### Issue Description

it won't compile when preprocessor directives are inside verbatim strings.

### Steps to Reproduce

see following sections.

### Expected Behavior

raw strings work okay:

```C#
#if true
Console.WriteLine("""
#if NET6_0_OR_GREATER
    return T.Construct();
#endif
""");
#else
Console.WriteLine("Hello, world!");
#endif
```

### Actual Behavior

now, consider verbatim strings:

```C#
#if false
Console.WriteLine(@"#if NET6_0_OR_GREATER
    return T.Construct();
#endif");
#else
Console.WriteLine("Hello, world!");
#endif
```

corresponding errors copied from Visual Studio's Error List, formatted manually as a table for better readability:

|Severity|Code|Description|Project|File|Line|Suppression State|Details|
|-|-|-|-|-|-|-|-|
|Error|CS1025|Single-line comment or end-of-line expected|CollectiveSuicide|C:\Users\Bento\source\repos\CollectiveSuicide\Program.cs|4|Active||
|Error|CS1028|Unexpected preprocessor directive|CollectiveSuicide|C:\Users\Bento\source\repos\CollectiveSuicide\Program.cs|5|Active||
|Error|CS1028|Unexpected preprocessor directive|CollectiveSuicide|C:\Users\Bento\source\repos\CollectiveSuicide\Program.cs|7|Active||

### Analysis

either one of:

1. parse verbatim strings correctly
2. a) prohibit preprocessor directives inside verbatim strings, b) document this limitation in every page that mentions conditional compilation and verbatim strings, c) improve warnings and errors and d) suggest raw strings if such error occurs

### Versions & Configurations

I hope the MREs are enough. if you really need more info, tell me.

**Comment by CyrusNajmabadi** [comment]
This is by design.  You're in an `#if false` section.  Within that, nothign has meaning until you get to the next `#else` `#elif` or `#endif`.  We have no processing of strings within these non-processed sections (that's been how thigns have worked in  c# 1).

**Comment by CyrusNajmabadi** [comment]
> now, consider verbatim strings:

Your cases are not the same:

use either:

## Both true:

```
#if true
Console.WriteLine("""
#if NET6_0_OR_GREATER
    return T.Construct();
#endif
""");
#else
Console.WriteLine("Hello, world!");
#endif
```

```
#if true
Console.WriteLine(@"
#if NET6_0_OR_GREATER
    return T.Construct();
#endif
");
#else
Console.WriteLine("Hello, world!");
#endif
```

## Both false:

```
#if false
Console.WriteLine("""
#if NET6_0_OR_GREATER
    return T.Construct();
#endif
""");
#else
Console.WriteLine("Hello, world!");
#endif
```

```
#if false
Console.WriteLine(@"
#if NET6_0_OR_GREATER
    return T.Construct();
#endif
");
#else
Console.WriteLine("Hello, world!");
#endif
```

---

You will see the same behavior for each.  That's because there is no processing of strings.  There is simply a question about if we run into pp directives in the intervening section.  And a pp directive is defined by being at the start of the line (modulo whitespace),having a `#` and then a word.

**Comment by bottle2** [comment]
I understand. thanks!
