### ISSUE TITLE
CSharpErrorList.xml is failing

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#7441]
PR: [#452](https://github.com/dotnet/roslyn-internal/pull/452) *Master to future 2015-12-11* by @jmarolf
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p2/82/

**3 Test Failures:**
CSharpErrorList.Error List
CSharpErrorList.Error Level of a warning
CSharpErrorList.Errors during method body editing

**Issue 1: Individual TAO Test Failure**
Failing integration tests: 

CSharpErrorList.xml

**Issue 2: Compile Error**
error CS2001: Source file 'C:\Users\dotnet-bot\AppData\Local\Temp\2\TestProj\Class1.cs' could not be found.

**Issue seems to be Temp files being removed while the test is run**

Bounty

**Comment by davkean** [comment]
@tannergooding @mmitche What would clean up %TEMP% files on these boxes while a job is running?

**Comment by mmitche** [comment]
@davkean Unless there is something special in the test logic, nothing in Jenkins.

**Comment by davkean** [comment]
Have not seen this fail recently, logs are well gone. Let's monitor and reopen if we hit again.

**Comment by genlu** [comment]
We have ran into this issue again a couple of times in #8783:
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/283/
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/287/

**Comment by CyrusNajmabadi** [comment]
Failed for me as well: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/304/console

**Comment by davkean** [comment]
This is probably a timing related thing; it looks like since Update 1 we're running into a lot more of these.

**Comment by davkean** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/292/

**Comment by davkean** [comment]
And again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_vsi_p2/872/

**Comment by DustinCampbell** [comment]
Could Analyzers take a look since this is the Error list test?

**Comment by heejaechang** [comment]
@srivatsn @Pilchie is this update 2 bug or regular bug?

**Comment by Pilchie** [comment]
In general, we'd like to drive down flakiness in tests for 1.2 if possible, since it improves our ability to validate the release.

**Comment by davkean** [comment]
Hit this again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_vsi_p2/171/

**Comment by heejaechang** [comment]
added some diagnostic to https://github.com/dotnet/roslyn-internal/pull/712

**Comment by heejaechang** [comment]
please re-open this if it happens again.
