### ISSUE TITLE
Hovering over a method gives the wrong overload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#74418]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hovering-over-a-method-gives-the-wrong-o/10691661)._

---
[severity:It's more difficult to complete my work]
Please see the attached sample project. This uses the LanguageExt Nuget package, which provides a Match method on the Either type. Match has many overloads, some that take Actions and some that take Funcs.

I was getting a compiler error (which you can see in the sample), and wasted quite a bit of time trying to work out why, until someone pointed out to me that VS is showing the wrong overload when you hover over it.

As VS is unable to work out the return type (which should be Either<string, Unit>), it thinks I'm passing an Action to the method, and so gives a compiler error of "Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement"

However, hovering over the Match method shows information that says that the compiler thinks I'm using an overload that takes Funcs, in which case the error message would be completely wrong. The see attached image VS.png to see this.

If you open the same project in JetBrains Rider, it shows the correct overload, see the attached image Rider.png.

Summary: VS is showing the wrong overload and this is VERY confusing.

---
#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 6/26/2024, 09:19 PM: 

(private comment, text removed)
#### mryossu on 6/27/2024, 08:02 AM: 

(private comment, text removed)
#### Feedback Bot on 7/4/2024, 00:39 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CyrusNajmabadi** [comment]
i don't repro this.  we'd need a rpero case showing this so we could send to the compiler (we use getSymbolInfo to determin ewhat to show).
